### ISSUE TITLE
[output.wavefront] "immediate_flush" flag doesn't work if sdk buffer becomes full

### ISSUE THREAD

**Issue by PhoenixRion** [influxdata/telegraf#10009]
### Relevent telegraf.conf

```toml
[[outputs.wavefront]]
  immediate_flush = true

[agent]
  metric_buffer_limit = 1000000
```

### System info

Telegraf 1.16.3

### Steps to reproduce

1. High metric volume fills output buffer to >50k

I don't have a good method for doing this on demand

### Expected behavior

If the "immediate_flush" flag is set to true then the buffer internal to the wavefront sdk should not impact Telegraf performance

### Actual behavior

Once the buffer is full, an error is emitted in the Write function before the "immediate_flush" flag is checked.  The error is repeated on every flush interval.

This also causes input progress to stop.  In my case reading from Kafka topics can be observed to fall behind.  Restarting Telegraf allows some progress to be made but progress stops if the wavefront sdk buffer becomes full again.

### Additional info

I think this can be fixed with a simple change https://github.com/influxdata/telegraf/compare/master...PhoenixRion:master

I have reached out to Wavefront as well to ask for their input.

Sample error log `E! [agent] Error writing to outputs.wavefront: Wavefront sending error: buffer full, dropping line: ...`

**Comment by PhoenixRion** [comment]
@prydin FYI, my teammate in Europe tested `flush_interval = 1` and said that there was an improvement.  We are actively tuning multiple components so we had to reduce the load before we could see if the sdk buffer would stay below its limit but every bit helps.

**Comment by prydin** [comment]
@PhoenixRion You may pull from here: https://github.com/prydin/telegraf/pull/new/prydin-10009

**Comment by prydin** [comment]
@PhoenixRion Tuning the flush interval may help, but I think the forced flush is a better and more permanent solution.

**Comment by PhoenixRion** [comment]
@prydin Initial testing with the patch is positive.  We have hit a different blocker, so we only have run for a few hours at this point.
