### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by Rossall82** [influxdata/telegraf#10023]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Rename master branch to main

### Current behavior:
master branch

### Desired behavior:
master branch to become main [GH guide here](https://github.com/github/renaming)

### Use case: 
master can be insensitive, and is flagged by markdown scanners such as [alex.js](https://github.com/get-alex/alex), for example.

**Comment by powersj** [comment]
Thanks for the request, we have #7675 already existing to make changes. I'm going to close this as a dup of that.

Thanks again!
