### ISSUE TITLE
Feature Request: httpjson and exec support level of tags if defined in siblings or in parents not just top-level in JSON

### ISSUE THREAD

**Issue by gam-phon** [influxdata/telegraf#1002]
In both these inputs, httpjson and exec, they support just top-level tags

For example:
This configuration:

    tag_keys = [
      "service",
      "provider"
    ]

With this valid JSON:

    {
      "service": "service01",
      "a": 0.5,
      "b": {
          "provider": "providername",
          "d": 0.1,
          "e": 5
      }
    }

Why not metrics be like this:

    httpjson_mycollector_a,service='service01',server='http://my.service.com/_stats' value=0.5
    httpjson_mycollector_b_d,service='service01',server='http://my.service.com/_stats',provider='providername' value=0.1

In the second metric this tag has been added `provider='providername'`

Creating multiple level of tags if defined in the siblings or in parents.

The use case is this: if there is a service supported from multiple providers and each provider has his own stats. and you want to tag the results to group them or query each provider.

**Comment by sparrc** [comment]
closing in favor of https://github.com/influxdata/telegraf/issues/1363
