### ISSUE TITLE
How can I add thousands of SNMP agent to telegraf

### ISSUE THREAD

**Issue by jordandubu** [influxdata/telegraf#10022]
Hello, 
I am wondering how to add multiple agent to telegraf easily. We’re adding like one router per day, and my team and I don’t wanna go to the config file to add a router to telegraf.

I’ve been thinking of using an environment variable, but there is a size limit.
Or creating a php website to add or delete an ip adress.
Or a bash script
It has to be userfriendly a bit

To add more context, I am a student and i have the project of replace my company monitoring solutions with grafana and telegraf.

Any idea ?

Does an agent manager exist ?

One more question, do I have to restart telegraf service each time i add a router ?

```
############################
#Edgrouter Inputs ##########
##
## EdgeRouter devices
##
 [[inputs.snmp]]
   # List of agents to poll
   agents = [
  "pubIP",
  "pubIP",] + ~ thousands of routers to add
```

**Comment by srebhan** [comment]
@jordandubu would it be an option to add a new config file to the config-directory with every new router you want to add? The file should then contain the `inputs.snmp` section for the new device...

**Comment by jordandubu** [comment]
> 
> 
> @jordandubu would it be an option to add a new config file to the config-directory with every new router you want to add? The file should then contain the `inputs.snmp` section for the new device...

Yes, i searched that and it is faster, thanks for the hint :)

**Comment by jordandubu** [comment]
I just wonder how to correctly do that?
should i let the beginning of the telegraf.conf file until the input plugins ?

Should i copy all my input plugins ( 200 lines ) and paste it in a file and doing that for each ip address

like this :
/etc/telegraf/telegraf.d/192.168.1.1
/etc/telegraf/telegraf.d/router2
+ ~ 1000

Would it be possible someday to have a telegraf userfriendly local website to manage the conf ?

**Comment by srebhan** [comment]
Exactly, make each plugin an own file.

> Would it be possible someday to have a telegraf userfriendly local website to manage the conf?

What do you mean? You can already specify a http/https address for telegraf to fetch the config...
