### ISSUE TITLE
Telegraf agent error: error parsing win_perf_counters, Undefined but requested input: win_perf_counters

### ISSUE THREAD

**Issue by batistado** [influxdata/telegraf#10045]
Relevent telegraf.toml
```
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

[[inputs.win_perf_counters]]
[[inputs.win_perf_counters.object]]
	ObjectName = "Processor"
	Instances = ["*"]
	Counters = [
	  "% Idle Time",
	  "% Interrupt Time",
	  "% Privileged Time",
	  "% User Time",
	  "% Processor Time",
	  "% DPC Time",
	]
	Measurement = "win_cpu"
	
[[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
    ]
    Measurement = "win_diskio"
	

[[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes",
    ]
    Instances = ["------"]
    Measurement = "win_mem"
	
[[inputs.win_perf_counters.object]]
    ObjectName = "Paging File"
    Counters = [
      "% Usage",
    ]
    Instances = ["_Total"]
    Measurement = "win_swap"

```
System info
Telegraf 1.17

Steps to reproduce

Copy the above telegraf content to a telegraf.toml file and create a go script that tries to load config:
`
conf := config.NewConfig()
err = conf.LoadConfig(filepath.Join(configPath, configName))
if err != nil {
logger.Error("failed to load config: %v", err)
return err
}
`

Actual behavior
`
Error loading config file ~\telegraf.toml: error parsing win_perf_counters, Undefined but requested input: win_perf_counters
`

Expected behavior
No errors loading the config.

**Comment by powersj** [comment]
The error message "Undefined but requested input" means the version of Telegraf you are running does not have that input plugin available. If you run `./telegraf --input-list` you will see the full list of inputs that your binary understands. Also keep in mind that you must be running a Windows binary for that plugin to work as it is only built for Windows.

I am going to close this as it is a support issue and not an issue with Telegraf, but if you find otherwise, please feel free to re-open this. Also consider asking on our [Community Slack](https://influxdata.com/slack) or [Forums](https://community.influxdata.com/) for additional help.

Thanks!

**Comment by batistado** [comment]
Could you please re-open this since my telegraf support win_perf_counters and I am running this on windows:
`PS C:\Program Files\telegraph> ./telegraf --input-list
Available Input Plugins:
  activemq
  aerospike
  amqp_consumer
  apache
  apcupsd
  aurora
  azure_storage_queue
  bcache
  beanstalkd
  bind
  bond
  burrow
  cassandra
  ceph
  cgroup
  chrony
  cisco_telemetry_gnmi
  cisco_telemetry_mdt
  clickhouse
  cloud_pubsub
  cloud_pubsub_push
  cloudwatch
  consul
  couchbase
  couchdb
  cpu
  dcos
  disk
  diskio
  disque
  dmcache
  dns_query
  docker
  docker_log
  dovecot
  ecs
  elasticsearch
  ethtool
  eventhub_consumer
  exec
  execd
  fail2ban
  fibaro
  file
  filecount
  filestat
  fireboard
  fluentd
  github
  gnmi
  graylog
  haproxy
  hddtemp
  http
  http_listener
  http_listener_v2
  http_response
  httpjson
  icinga2
  infiniband
  influxdb
  influxdb_listener
  internal
  interrupts
  ipmi_sensor
  ipset
  jenkins
  jolokia
  jolokia2_agent
  jolokia2_proxy
  jti_openconfig_telemetry
  kafka_consumer
  kafka_consumer_legacy
  kapacitor
  kernel
  kibana
  kinesis_consumer
  kube_inventory
  kubernetes
  lanz
  leofs
  linux_sysctl_fs
  logparser
  logstash
  lustre2
  mailchimp
  marklogic
  mcrouter
  mem
  memcached
  mesos
  minecraft
  modbus
  mongodb
  monit
  mqtt_consumer
  multifile
  mysql
  nats
  nats_consumer
  neptune_apex
  net
  net_response
  netstat
  nginx
  nginx_plus
  nginx_plus_api
  nginx_sts
  nginx_upstream_check
  nginx_vts
  nsq
  nsq_consumer
  nstat
  ntpq
  nvidia_smi
  openldap
  openntpd
  opensmtpd
  openweathermap
  passenger
  pf
  pgbouncer
  phpfpm
  ping
  postfix
  postgresql
  postgresql_extensible
  powerdns
  powerdns_recursor
  processes
  procstat
  prometheus
  puppetagent
  rabbitmq
  raindrops
  redfish
  redis
  rethinkdb
  riak
  salesforce
  sflow
  smart
  snmp
  snmp_legacy
  snmp_trap
  socket_listener
  solr
  sqlserver
  stackdriver
  statsd
  suricata
  swap
  synproxy
  syslog
  system
  tail
  tcp_listener
  teamspeak
  temp
  tengine
  tomcat
  trig
  twemproxy
  udp_listener
  unbound
  uwsgi
  vsphere
  webhooks
  win_perf_counters
  win_services
  wireguard
  wireless
  x509_cert
  zfs
  zipkin
  zookeeper`
