### ISSUE TITLE
build against master currently fails with invalid dependencies

### ISSUE THREAD

**Issue by johnseekins** [influxdata/telegraf#10040]
### Relevent telegraf.conf

```toml
None
```

### System info

master, Fedora 34, git pull on 2021-11-01

### Steps to reproduce

1. Clone repo locally
2. run `make test`
3. See the following:
```
make test
go test -short -race ./...
go: github.com/harlow/kinesis-consumer@v0.3.6-0.20210911031324-5a873d6e9fec: invalid version: unknown revision 5a873d6e9fec
```

### Expected behavior

Tests actually run

### Actual behavior

Tests fail because go.mod has a requirement for a version of kinesis-consumer that doesn't seem to exist. The last release of harlow/kinesis-consumer is 0.3.5: https://github.com/harlow/kinesis-consumer/releases

**Comment by powersj** [comment]
Hi,

I set up a fresh checkout of telegraf on my system and was unable to reproduce it. Are you still seeing this?

```
ubuntu@nexus:~/telegraf$ make test
go test -short -race ./...
...
go: downloading github.com/harlow/kinesis-consumer v0.3.6-0.20210911031324-5a873d6e9fec

```

Thanks!

**Comment by johnseekins** [comment]
I am still seeing this, yes. Even with another `git pull`. Doesn't telegraf require some strange GO_PROXY setting that I always forget about?
Right!
```
export GOPROXY=https://proxy.golang.org,direct
export GOSUMDB=sum.golang.org
```
That fixes it.

**Comment by johnseekins** [comment]
Actually, that exposes another issue for me:
```
verifying collectd.org@v0.5.0: checksum mismatch
	downloaded: h1:mRTLdljvxJNXPMMO9RSxf0PANDAqu/Tz+I6Dt6OjB28=
	go.sum:     h1:y4uFSAuOmeVhG3GCRa3/oH+ysePfO/+eGJNfd0Qa3d8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by johnseekins** [comment]
I think there's two problems I have here:
1. My local build environment was trying to build with Golang 1.16, which telegraf no longer supports for building.
2. The two proxy settings aren't defined for me, and I always forget about them...

I'll address #1 myself ('cause it's for sure my problem), but #2 is a really annoying thing. Seems like that could be documented better.

**Comment by always-waiting** [comment]
@johnseekins I have same promblem. how did you fix this?

![image](https://user-images.githubusercontent.com/8566918/158127468-59bf2861-0f26-4bd2-b53e-d9aa3501f3bd.png)

package github.com/harlow/kinesis-consumer does not have tag v0.3.6

**Comment by johnseekins** [comment]
I've had to add this to my environment to make it work:
```
export GOPROXY=https://proxy.golang.org,direct
export GOSUMDB=sum.golang.org
```

**Comment by johnseekins** [comment]
I think your problem is different. As I noted above, I had two problems:
1. my environment was configured wrong
2. my build environment was a bit polluted.

I cleaned up my environment and things worked better.

**Comment by always-waiting** [comment]
@johnseekins I found the package
 [kinesis-consumer](https://github.com/harlow/kinesis-consumer/tags), but there was't tag v0.3.6.

**Comment by woorui** [comment]
@always-waiting 

I set `GOPROXY` from `https://goproxy.io,direct` to `https://proxy.golang.org,direct ` and fix this issue.
