### ISSUE TITLE
Docker image permission issues

### ISSUE THREAD

**Issue by T81** [influxdata/telegraf#10052]
Since updating to version 1.20.3 I cannot access the configuration mounted host volume with permission denied. Is it possible to set UID / GID in order to resolve this? Or else which is the best route to approach this issue?

**Comment by powersj** [comment]
Hi,

We recently made a change to our Telegraf container images to run the telegraf process as the `telegraf` user and group. This means that when running Telegraf in a container, you will need to make sure that the `telegraf` user or group is able to see the mount.

There are a number of ways to resolve this. One is to run `chown` on the mount: `RUN chown -R telegraf:telegraf /volume`. Another way is to ensure the `user` parameter for the mount is set to `user: "telegraf:telegraf"`

Let us know what you use or if you find another method.

Thanks!

**Comment by T81** [comment]
Nice thanks. I managed to solve it. I am using Portainer. During container recreation, under "Command & Logging" tab I changed the "User" field, from "telegram" to the appropriate "uid:gid" and now it is working fine. I suppose this change if fine, right?

**Comment by powersj** [comment]
Yep sounds like you are good to go! Thanks for following up.
