### ISSUE TITLE
Support JSON format output when using --test flag

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#10059]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:

The `--test` flag outputs in line protocol format

```cli
telegraf --config=./telegraf.conf --test
```

output be like:

```cli
> measurement,tag1=value1,tag2=value2 field1=1i 1636038000000000000
```

### Desired behavior:

Be able to specify output format using `--test` flag

```cli
telegraf --config=./telegraf.conf --test --output-format=json
```

output be like:

```cli
> {"name":"measurement", "fields":{"field1":1}, "tags":{"tag1":"value1", "tag2":"value2"}}
```

### Use case: 

Useful when using `--test` flag and interfacing with other system using JSON format.

**Comment by srebhan** [comment]
Hey @KEVISONG can you please outline your use-case? I'm a bit hesitant to open this box as we, over time, might accumulate a bunch of formats here, basically duplicating the `outputs.file` plugin with `files=["stdout"]`...
Would using
```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
```
and running telegraf with `--output-filter file --once` also solve your use-case?

**Comment by KEVISONG** [comment]
> Hey @KEVISONG can you please outline your use-case? I'm a bit hesitant to open this box as we, over time, might accumulate a bunch of formats here, basically duplicating the `outputs.file` plugin with `files=["stdout"]`... Would using
> 
> ```toml
> [[outputs.file]]
>   files = ["stdout"]
>   data_format = "json"
> ```
> 
> and running telegraf with `--output-filter file --once` also solve your use-case?

Hi @srebhan

It actually worked and solved my use case : )

But in this way, the config file needs additional modifying - adding `outputs.file` output. It would be great if `--test` can support different format so the config file can remain untouched.

It's a `nice to have` feature.

**Comment by powersj** [comment]
I am going to go ahead and close this per the solution @srebhan pointed out. No need to muddy up `--test` with what could grow into lots of additional options + what the file output plugin already does.

Thanks!
