### ISSUE TITLE
Native Go `ping` requires `CAP_NET_RAW` but Telegraf binary doesn't have capability set in Docker image

### ISSUE THREAD

**Issue by Cougar** [influxdata/telegraf#10069]
### Relevent telegraf.conf

```toml
[[inputs.ping]]
  urls = ["127.0.0.1"]
  method = "native"
  count = 10
  ping_interval = 0.5
  ipv6 = false
```

### System info

Docker 17.09.1-ce, telegraf:1.20.3-alpine

### Steps to reproduce

1. Run Telegraf container with `CapAdd = net_raw`

### Expected behavior

Ping should work

### Actual behavior

```
2021-11-06T23:20:00Z E! [inputs.ping] ping failed: permission changes required, enable CAP_NET_RAW capabilities (refer to the ping plugin's README.md for more info)
```

### Additional info

`cap_net_raw` needs to be added to the Telegraf binary during image build. The same thing has been discussed in Blackbox exporter issue [#689](https://github.com/prometheus/blackbox_exporter/issues/689#issuecomment-699144999). The easiest fix for Alpine based container is just to run `setcap cap_net_raw+ep /usr/bin/telegraf` during build process (it is already installed). Another images may need `libcap` installation first.

When I enter to the container, fix file permission and restart the container, it works with current image too:

```
> docker exec -ti test-monitoring_pingmesh_telegraf bash
bash-5.1# setcap cap_net_raw+ep /usr/bin/telegraf
> docker restart test-monitoring_pingmesh_telegraf
```

**Comment by powersj** [comment]
Hi,

While the [README](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping) suggests using method native, it does layout some [Linux related permission](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ping/README.md#linux-permissions) changes that need to occur to a system for this to work. Effectively Telegraf needs to be run as root or given the `CAP_NET_RAW` capability as you have discovered in the bug.

We did recently make a change to our Docker images to [stop running Telegraf as root](https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/) for security reasons. My suggestion is to either follow the readme's suggestions or to not use the native method.

Using the built-in ping binary does however work out of the box on the Alpine image:

```shell
ubuntu@nexus:~$ cat ping.toml 
[[inputs.ping]]
  urls = ["192.168.2.10"]
  count = 10
  ping_interval = 0.5
  ipv6 = false

[[outputs.file]]
ubuntu@nexus:~$ docker run -d --name=telegraf-alpine -v $PWD/ping.toml:/etc/telegraf/telegraf.conf:ro telegraf:alpine
Unable to find image 'telegraf:alpine' locally
alpine: Pulling from library/telegraf
a0d0a0d46f8b: Pull complete 
0e8cf55ffd68: Pull complete 
4bc5969994dd: Pull complete 
3e3f6d84ea81: Pull complete 
9cc2ae9653b2: Pull complete 
Digest: sha256:314108cc28917dd404d9f5f925a79ad058a5db1a6fcdfa7b7bfe6771235e5eb0
Status: Downloaded newer image for telegraf:alpine
3196572f92d602e5a8ea764eec22a735f098200c4880395c3edb9aa16ad7eb09
ubuntu@nexus:~$ docker logs -f telegraf-alpine 
2021-11-08T14:56:30Z I! Starting Telegraf 1.20.3
2021-11-08T14:56:30Z I! Using config file: /etc/telegraf/telegraf.conf
2021-11-08T14:56:30Z I! Loaded inputs: ping
2021-11-08T14:56:30Z I! Loaded aggregators: 
2021-11-08T14:56:30Z I! Loaded processors: 
2021-11-08T14:56:30Z I! Loaded outputs: file
2021-11-08T14:56:30Z I! Tags enabled: host=3196572f92d6
2021-11-08T14:56:30Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"3196572f92d6", Flush Interval:10s
ping,host=3196572f92d6,url=192.168.2.10 packets_received=1i,percent_packet_loss=0,ttl=63i,minimum_response_ms=0.398,average_response_ms=0.398,result_code=0i,packets_transmitted=1i,maximum_response_ms=0.398,standard_deviation_ms=0 1636383400000000000
ping,host=3196572f92d6,url=192.168.2.10 minimum_response_ms=0.747,average_response_ms=0.747,standard_deviation_ms=0,packets_transmitted=1i,packets_received=1i,ttl=63i,maximum_response_ms=0.747,result_code=0i,percent_packet_loss=0 1636383410000000000
^C
```

I am happy to hear any suggestions, but I am going to close this for now as I am not certain we want to make any further changes or expand the permissions of the docker containers without really good reason given there are options in this case.

Thanks!

**Comment by Cougar** [comment]
Hi,

You don'tneed to run Telegraf as root when `CAP_NET_RAW` is set which is the whole point of this capability. The missing part in Docker image is that to use this capability you have to set this file attribute first.

ping binary works because it has SUID bit set which means that basically it runs as root.
