### ISSUE TITLE
Cookie authentication does not set header Content-type

### ISSUE THREAD

**Issue by heilju** [influxdata/telegraf#10061]
Hi, 

I am trying to use the inputs.http plugin with Cookie authentication. The API I want to query data from requires  a header called 'XSRF_TOKEN' with an authentication token as value in the query request. The value for this header can be retrieved by doing the following POST call:
```
https://eu5.fusionsolar.huawei.com/thirdData/login
Header: Content-type=application/json
{
  "username": "user",
  "password": "secret"
}
```

The required token is returned as a cookie, but only if the Content-Type header is provided with the request. If no Content-Type header is set I receive an error.

Would it be possible to add a telegraf config option that takes a list of headers that are sent with the Cookie auth request (e.g. `cookie_auth_headers={"Content-Type" = "application/json","Custom-Header" = "somevalue"}`)?

**Comment by aslater3** [comment]
I have this same issue

**Comment by aslater3** [comment]
Has anyone found a work around for this?

**Comment by grzanka** [comment]
@heilju Have you finally managed to use telegraf to get data from Huawei Fusionsolar API ?
It seems the issue was fixed in https://github.com/influxdata/telegraf/pull/10404
