### ISSUE TITLE
Feature Request: Percent Utilization on diskio plugin?

### ISSUE THREAD

**Issue by damm** [influxdata/telegraf#1007]
I noticed there's no percent utilization; I know the hard limits but sometimes with other events the disks can't achieve that so it's rather useful to have the OS reported utilization ?

**Comment by sparrc** [comment]
it's in the `disk` plugin

**Comment by sparrc** [comment]
see https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/DISK_README.md

**Comment by damm** [comment]
I don't see it there; I see in the `disk` plugin in the diskio portion of the file.

```go
		fields := map[string]interface{}{
			"reads":       io.ReadCount,
			"writes":      io.WriteCount,
			"read_bytes":  io.ReadBytes,
			"write_bytes": io.WriteBytes,
			"read_time":   io.ReadTime,
			"write_time":  io.WriteTime,
			"io_time":     io.IoTime,
		}
		acc.AddFields("diskio", fields, tags)
```

I don't see where one of these would be percent utilized? I know i'm thinking of the sysstat package (iostat -dxm 5) so if you don't offer that metric that's what the request was for.

**Comment by sparrc** [comment]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/disk.go#L68

**Comment by damm** [comment]
That's the disk used percentage.

**Comment by damm** [comment]
i'll try it.

**Comment by sparrc** [comment]
I see, I thought you were asking for disk used percentage, I'll leave the issue open then

**Comment by sparrc** [comment]
this is a good reference for how the kernel calculates this: http://stackoverflow.com/questions/4458183/how-the-util-of-iostat-is-computed

**Comment by phemmer** [comment]
Note, you can calculate this very easily with the existing data:

influxdb:

    SELECT derivative(last("io_time"),1ms)*100 FROM "diskio" GROUP BY "host","name", time(60s)

**Comment by zargex** [comment]
Hi @phemmer, why you use `last()` to calculate the derivated ?.
I'm using something like `SELECT derivative("io_time",10s) FROM "diskio" where "name" = 'dm-0'` (i'm using 10s because telegraf recollect each 10 seconds).

Thanks.

**Comment by phemmer** [comment]
@zargex you're not using a `GROUP BY`, therefore you don't need `last()`.

**Comment by phemmer** [comment]
Oh, and you don't want `10s`, you want `1ms`. The value isn't how often you have telegraf polling. The value is the unit of the metric.

**Comment by zargex** [comment]
Thanks @phemmer.

**Comment by egar** [comment]
i still not get right values using this Query :
`SELECT derivative(last("io_time"), 1s) FROM "diskio" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY "host", "name"`

result show a hundred and thousand percentage (%)

**Comment by egar** [comment]
sorry my Query :
`SELECT derivative("io_time", 10s) FROM "diskio" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY "host", "name"`

if using last there are no result in graph

**Comment by phemmer** [comment]
@egar You need to use `1ms`, not `1s` in the `derivative` function.

**Comment by egar** [comment]
@phemmer  still not give good result :
SELECT derivative("io_time", 1s) FROM "diskio" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY "host", "name"


![diskbusy](https://cloud.githubusercontent.com/assets/40311/18809686/c1c361e8-82ac-11e6-8267-379b535f7bdf.JPG)

**Comment by phemmer** [comment]
You likely have multiple different disks on a single line in your graph. You can't combine all the disks on the host as a single line as it screws up the calculations. Meaning you need to add a `group by` on the disk.

**Comment by phemmer** [comment]
You still have `1s` in your measurement. You want `1ms` NOT `1s`.

**Comment by egar** [comment]
woow ..so far looks Good let  telegraf sending dadta for 24 hours and let me xcheck again

![diskbusy2](https://cloud.githubusercontent.com/assets/40311/18809762/cdbb6282-82ae-11e6-97f1-18609b9e60b6.JPG)


BIG Thanks @phemmer , ill be back heehehe

**Comment by egar** [comment]
just fast compare using` iostat -xk 2` in my mahchien,
![tmenudisk](https://cloud.githubusercontent.com/assets/40311/18809827/bbd21802-82b0-11e6-986c-0d340a1500c6.JPG)

and this is from Grafana :
![tmenudisk2](https://cloud.githubusercontent.com/assets/40311/18809831/c68984b0-82b0-11e6-93ff-57f3f5e5c785.JPG)

diferent result, grafana more lower % disk util than iostat result in OS directly

latest Query :
`SELECT derivative("io_time", 1ms) FROM "diskio" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY "name"`

**Comment by jamessammut** [comment]
The units look wrong approx 2 orders of magnitude out. My guess pick different units in the graph scale.

**Comment by timka** [comment]
@egar There are two kinds of percent scales in Grafana, 0.0–1.0 and 0-100. Which one did you use? I guess it should be the first one.

**Comment by alexdaviesjump** [comment]
I can confirm that this trick works if you choose the former scale.

**Comment by 7yl4r** [comment]
Thanks to the notes here I was able to get this working in graphite as well `asPercent(perSecond(*.*.diskio.io_time),1000)`, but I wouldn't have realized it otherwise. Is it worth adding something to the disk readme or should this just be closed?

**Comment by danielnelson** [comment]
I added the InfluxQL query to the readme cb04fa1e9c73d89106fa5d753ceb075c396f9736.  We don't usually add graphite example queries since it would get out of hand adding them for every output.

**Comment by 1medusa1** [comment]
Any option to achieve this using prometheus?

**Comment by UlricQin** [comment]
> Any option to achieve this using prometheus?

try this: `rate(diskio_io_time[1m])/1000*100` @1medusa1

**Comment by erkexzcx** [comment]
Using VictoriaMetrics TSDB, pushing as `outputs.influxdb` output. Here is what worked to me:
```
rate(diskio_io_time{host="$host"}[1ms]) / 1000
```

**Comment by fq-zhaang** [comment]
> r

how do you generate the graph?

**Comment by fq-zhaang** [comment]
> @phemmer still not give good result : SELECT derivative("io_time", 1s) FROM "diskio" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY "host", "name"
> 
> ![diskbusy](https://cloud.githubusercontent.com/assets/40311/18809686/c1c361e8-82ac-11e6-8267-379b535f7bdf.JPG)

how do you generate the graph?
