### ISSUE TITLE
Adding support to parse metadata before headers to the CSV parser

### ISSUE THREAD

**Issue by etycomputer** [influxdata/telegraf#10079]
## Feature Request

Adding this option enables the parser to process metadata included before the CSV header.
This information can be included in every metric as a field or tag.

### Proposal:
To add two new options to the CSV parser: `csv_metadata_rows` and `csv_metadata_regex`
`csv_metadata_rows = x` where x is the number of rows that contain the metadata after `csv_skip_rows` and before the header rows. By default, this value would be set to zero.
```
csv_metadata_regex = ["^[#]?\s*(?P<key>[^:=]+)[:=]\s*(?P<value>\w+)$"]
``` 
csv_metadata_regex is a list of regex expressions, each regex must have a `key` and `value` label. 

The regex expression above covers the following scenarios:
```
# comment line
#	option 1: value1
	option 2= value2

	# another comment line
	option3: value3
```
and returns the following metadata:
`option 1`=`value1`
`option 2`=`value2`
`option3`=`value3`

Note that the regex could also be used to ignore comments.

### Example CSV file:

```
version=1.0
file created: 2021-10-08T12:34:18+10:00
timestamp,type,name,status
2020-11-23T08:19:27+10:00,Reader,R002,1
2020-11-04T13:23:04+10:00,Reader,R031,0
2020-11-04T13:29:47+10:00,Coordinator,C001,1
```
### Current behaviour:
The current parser does not support metadata parsing. These rows need to be skipped. 
### Desired behaviour:
The output should include `version` and `file created` as either a tag or a field for every metric following the header.

**Comment by etycomputer** [comment]
Hi @srebhan, @powersj, @Hipska, and @sspaink,

I am going to start working on this new feature for the CSV parse.
Could you all have a look at my proposal and let me know what you think.

The main part that I need feedback on is regarding the `csv_metadata_regex` field. Is this good practice to give users this much flexibility or should I limit them by just letting them create a list of `csv_metadata_delimiter=[":","="]`.

This way they would not be able to have comments between metadata.

Cheers,
Ehsan

**Comment by sspaink** [comment]
Usually the best practice is to keep the configuration as simple as possible, so it would be nice to just use the delimiter option you suggested but if that means not allowing to have comments then probably using the regex would be ok. I am curious what the others think about this, but `csv_metadata_regex` seems to be an acceptable proposal I wouldn't know a better way of doing.

**Comment by srebhan** [comment]
@etycomputer how about allowing the user to specify a "separator" (e.g. `":"`) and then parse key-value pairs removing all non-word characters in the beginning (e.g. all `#`) and trim spaces? This would ease the configuration and covers your use case...

**Comment by etycomputer** [comment]
Hey @srebhan,
I have actually finished working on this feature. Please have a look at #10083.
The Regex approach was very straightforward, it gives greater flexibility and doubles as `Skip` or `Ignore`.
I have fully tested the change with different scenarios and have got lots of unit tests and examples.

Using the "telegraf --config config.conf --test" people can make sure that they have correctly configured their conf file before they use it.

Cheers
Ehsan

**Comment by etycomputer** [comment]
Hi @sspaink @srebhan @reimda @powersj and @Hipska 

The #10083 feature covers the following use-cases:

```toml
name_override="device_status"
csv_metadata_rows = 4
csv_metadata_regex = ["^(?P<key>Version)[=](?P<value>\\d+\\.\\d+)$", "^(?P<key>File Created)[:]\\s+(?P<value>(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([\\+-]\\d{2}:\\d{2})?))$","^[#]\\s+(?P<value>\\w+)\\s+(?P<key>\\w+)", "(?P<key>\\w+)\s+(separator1)\\s+(?P<value>\\w+)"]
csv_tag_columns = ["Version","File Created","Device Type","Key1"]
```

```csv
Version=1.1
# other metadata or information Key1 separator1 Value1
# Value2  Key2
File Created: 2021-11-17T07:02:45+10:00
Time Stamp,Device Type,X,Y,Z,Status
2020-09-07T14:49:53+09:30,Wireless,894.72,496.78,40.70,1
```

```
device_status,Device\ Type=Wireless,File\ Created=2021-11-17T07:02:45+10:00,Key1=Value1,Version=1.1 Key2="Value2",Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900
```

**Comment by srebhan** [comment]
@etycomputer yeah I saw the PR, but I wanted to discuss this with you here. You probably will agree that the regexp in your example is not necessarily easy to understand... ;-)
I propose to have an option to configure the separator or even a set of separators like
```toml
cvs_metadata_separators = [" ", "\t", ":", "="]
```
The parser will then look for key-value pairs in the "skipped rows" at the beginning of the file and will extract all found pairs as tags. You can then easily keep/drop the tags you want using `taginclude`/`tagexclude`...
The benefit is that this is much easier to understand and setup for an unexperienced user.

**Comment by etycomputer** [comment]
@srebhan Thanks for your feedback.

Yes, I do agree that a person with no or limited IT background will have difficulty with the regex approach.
In my defence, I would argue that non-IT savvy people would not be using this tool. 
Nevertheless, the customer is always right. :)

I will try to make the requested changes ASAP.

Kind regards,
Ehsan

**Comment by etycomputer** [comment]
Hi @srebhan I have made the following changes:
I have removed the `csv_metadata_regex` and added `cvs_metadata_separators`.
I have also added another optional parameter for trim sets `cvs_metadata_trim_set`.
