### ISSUE TITLE
Improve or replace --test

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#10080]
## Problem

The telegraf command line option `--test` is often misunderstood especially in that it does **not** send any data to the outputs but only to stdout. Therefore new users wonder why they don't see any data in their configured database(s) as they meant to use `--once`.

### Proposal:

To improve the awareness for the user about the actual behavior when using `--test` I see the following options

1. Keep `--test` and add a (maybe red) output saying: _"NOTE: Telegraf running in **test mode**, no data will be sent to the outputs!"_ or similar.
2. Add a `--dry-run` option disabling the output plugins. Used together with `--once` it resembles the present `--test` option. We can then remove `--test`. Additionally, the new option allows to run multiple gather cycles or listen for inputs with outputs disabled.
3. Like 2 with the additional warning of 1.

What is your opinion on this?

**Comment by Hipska** [comment]
I like option 2, but would love to see `--test` to stay, just as a shortcut to `--once --dry-run`. Although, you are stating it would resemble the same, it is not as it would not output the metrics..

**Comment by powersj** [comment]
If the problem is the lack of understanding of the `--test` option's capabilities then adding a warning log message seems like the most beneficial and straightforward resolution. The UX could look like:

```
❯ ./telegraf --test --config github.toml
2021-11-10T15:01:31Z I! Starting Telegraf 
2021-11-10T15:01:31Z W! Test mode enabled: output plugins are not run
> measurement,key=value field=value timestamp
```

Adding additional options does not seem like the best path forward as it results in even more confusion as to what to use and when. Traditionally `--dryrun`/--dry-run` would show what commands or operations take place without actually doing them. With respect to Telegraf I see that meaning reading in our config file and verifying it before trying to read any inputs/outputs.

If we were to remove options that would effectively be a breaking change to the CLI and something we would want to do at a major release. Adding the warning log message is something we can do now.

**Comment by srebhan** [comment]
@powersj  I'm not sure that people will notice that message if it is not red and blinks. :-) The documentation of the option clearly states that there will not be an output beside stdout. Nevertheless, people open issues of type _"I run telegraf and I don't see any data in my database"_ Often they run with `--test`...
My intention with `--dry-run` was to make the behavior more obvious as I assumed people know it as _"run that command but do not change anything"_. We could even name it `--no-output`? As @Hipska already mentioned we could then just make `--test` an alias for `--once --no-output`...

**Comment by powersj** [comment]
Having a log message embedded in output as a warning is very different than a [far away docs page](https://github.com/influxdata/telegraf/blob/master/docs/COMMANDS_AND_FLAGS.md) inside a repo that does not actually mention that output is not run :) Also note our ["pretty" docs site](https://docs.influxdata.com/telegraf/) does not even mention this flag. Finally, the `--help` option also does not explicitly mention that output is not run either.

The user experience around this option is poor, so changing the argument itself should not be the first solution. In my mind, the following needs to happen:

1) [Commands and flags docs](https://github.com/influxdata/telegraf/blob/master/docs/COMMANDS_AND_FLAGS.md) need to be updated to explicitly say outputs are not run.
2) The [CLI usage](https://github.com/influxdata/telegraf/blob/master/internal/usage.go#L40) output needs to be updated to explicitly say outputs are not run to better match what the [CLI option](https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/telegraf.go#L53) already has
3) Add the [warning message](https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/telegraf.go#L262) that says outputs are not run

**Comment by Hipska** [comment]
Whoops, the CLI option docs in point 2 is even not correct. The processors are run for sure, not sure if aggregators are run.
