### ISSUE TITLE
Add Tencent Cloud’s Cloud Monitor Input Plugin

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#10090]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:

Cloud providers have input plugins that are capable of scraping metrics of cloud services from the monitoring services that they provide.

- [Amazon CloudWatch Statistics Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch)
- [Alibaba (Aliyun) CloudMonitor Service Statistics Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/aliyuncms)

### Desired behavior:

Integrate `Tencent Cloud’s Cloud Monitor` as an input plugin.

### Use case: 

This plugin will enable shipping tons time series data of all kinds of Tencent Cloud services(CVM, CDB and so on) from `Cloud Monitor (CM)` to the influx stack and all other outputs that telegraf supports.

`Cloud Monitor (CM)` is a monitoring services provided by Tencent Cloud, which is analogue of AWS CloudWatch

**Comment by reimda** [comment]
Closing. See details in the PR https://github.com/influxdata/telegraf/pull/9184#issuecomment-1121533624
