### ISSUE TITLE
[FR] input.fail2ban - do not send zero values to database

### ISSUE THREAD

**Issue by mr-manuel** [influxdata/telegraf#10110]
## Feature Request
Add an option to the `input.fail2ban` plugin that allows to choose if you want to write zero records to the database. As zero records I intend when the values of banned and failed are 0.

### Proposal:
Add an option like `log_zero = false|true` that only send data to InfluxDB (or the selected output) when it's true.

### Current behavior:
All data is written to the database.

### Desired behavior:
The admin can choose if all data should be written to the database or only if there are values greater than 0.

### Use case: 
I have about 82% of database records where banned and failed are 0. Since I'm monitoring a lot of servers this would save me a lot of space in the database and on the server. Actually I have a cronjob which is deleting me all records with banned and failed equal 0.

**Comment by powersj** [comment]
For fine tuning your metrics, you can use Starlark to drop metrics with a specific value:

```python
def apply(metric):
    if metric.fields["banned"] != 0 or metric.fields["failed"] != 0:
        return metric
    else:
        return None
```

Take a look at [this blog post](https://www.influxdata.com/blog/how-use-starlark-telegraf/).

**Comment by mr-manuel** [comment]
Thank you very much. So as I understand is this the correct setup in my case?

Reading the docs didn't helped me to fully understand, if I have to use `namepass` to pass the input?

```
# # Read metrics from fail2ban.
[[inputs.fail2ban]]
   ## Use sudo to run fail2ban-client
    use_sudo = true

[[processors.starlark]]
    namepass = ['fail2ban']
    source = '''
def apply(metric):
    if metric.fields["banned"] != 0 or metric.fields["failed"] != 0:
        return metric
    else:
        return None
    '''
```

**Comment by powersj** [comment]
Hi!

This is what I was using:

```toml
[[inputs.fail2ban]]
[[processors.starlark]]
    source = '''
def apply(metric):
    if metric.fields["banned"] != 0 or metric.fields["failed"] != 0:
        return metric
    else:
        return None
    '''
[[outputs.file]]
```

To test this, I was flipping the `!=` to `==` to see if it suddenly showed all the zero-zero records, which is all I had.

Feel free to pop over to our [Community Slack](https://influxdata.com/slack) or [Community Page](https://community.influxdata.com/tag/telegraf), we have a lot of talented community members there who could help answer your question more quickly.

I'm going to go ahead and close this for now as I don't think this is something we would throw in.
