### ISSUE TITLE
Syslog plugin disconnects TCP connection when idle, contrary to documentation 

### ISSUE THREAD

**Issue by DavidAntliff** [influxdata/telegraf#10121]
### Relevent telegraf.conf

```toml
[[inputs.syslog]]
  server = "tcp://telegraf:601"
```

### System info

Telegraf 1.20.3, Arch Linux 20211118

### Steps to reproduce

1. set up syslog-ng OSE with config below
2. set up telegraf with an input.syslog as above
3. send single messages to syslog-ng with:

```
logger -i -d --server localhost this is a test
```

...

syslog-ng config:

```
@version: 3.29
@include "scl.conf"

options {
    create-dirs(yes);
    flush-lines(1);
    time-reopen(10);
};

source s_network {
    udp(ip(0.0.0.0) port(514));
};

destination d_network_telegraf {
    syslog("telegraf" port(601) transport(tcp));
};

log {
    source(s_network);
    destination(d_network_telegraf);
};
```

### Expected behavior

I expect syslog-ng to maintain a TCP connection to telegraf pretty much indefinitely, regardless of any log messages sent through syslog-ng. I would not expect a short period without log messages being received to cause a TCP disconnection because the documentation says that this timeout is based on the time to receive a single message, not the time between messages.

### Actual behavior

Log messages are successfully relayed to telegraf, however after 5 seconds without receiving any further log messages, telegraf closes the TCP connection from syslog-ng.   syslog-ng's default reconnection timeout is 60 seconds, so relaying stops working for about a minute.

syslog-ng can be configured to reconnect in as quickly as 1 second, but this behaviour by telegraf results in frequent disconnections and reconnections.

### Additional info

According to telegraf's documentation:

```
  ## Read timeout is the maximum time allowed for reading a single message (default = 5s).
  ## 0 means unlimited.
  # read_timeout = "5s"
```

A service like syslog-ng does not create a new TCP connection for every log message. Instead, it opens a connection to its configured destination (telegraf) and sends log messages when they become available.

Therefore I think it's unexpected behaviour for telegraf's syslog plugin to close the TCP connection 5 seconds (by default) after the _last_ parsed message received on this port.

The documentation says `read_timeout` is the maximum time allowed for reading a _single_ message, but it is not implemented this way. If log messages are not sent at least once per 5 seconds, the connection is dropped.

I think the `read_timeout` value can be set to `0` to disable this behaviour however that is not clear from the documentation as it only mentions single messages, not TCP connections.

**Comment by DavidAntliff** [comment]
I suggest that the comment in the documentation be reworded to say:

```
  ## Read timeout is the maximum time allowed between any two messages (default = 5s).
  ## 0 means unlimited.
  # read_timeout = "5s"
```

If the intention is to time out the parsing when an incomplete message is received (e.g. half-closed connection, malformed message, unexpected disconnection) then the original wording is OK, but there's a bug in the implementation. On the other hand, if the intention is to disconnect the TCP connection if no message is received within, say, 5 seconds, then it's working as intended, but the config file comment above does not make this clear at all.

**Comment by srebhan** [comment]
@DavidAntliff (or anyone else reading this) can you please test the binary in PR #14828 available as soon as CI finished the tests!? Let me know if this fixes the issue!

**Comment by DavidAntliff** [comment]
@srebhan thanks for the fix! However, I've moved on from the project concerned thus I'm not in a position to test this myself. Hopefully someone else is able to.
