### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by Drewster727** [influxdata/telegraf#1016]
I'm having an issue on my Ubuntu Server 15.10 box with the latest .deb version of telegraf.  0.12.0-1

When running the dpkg install command:
```sudo dpkg -i telegraf_0.12.0-1_amd64.deb```

I get the following:
```
Selecting previously unselected package telegraf.
(Reading database ... 150273 files and directories currently installed.)
Preparing to unpack telegraf_0.12.0-1_amd64.deb ...
Unpacking telegraf (0.12.0-1) ...
Setting up telegraf (0.12.0-1) ...
Failed to get D-Bus connection: Operation not permitted
Failed to get D-Bus connection: Operation not permitted
dpkg: error processing package telegraf (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 telegraf
```

I have tried to remove it and reinstall, it just won't properly install  for some reason and I'm not sure why. Some searching seems to indicate something with systemd? I've not had any issues with this box and installing packages, just telegraf.

Any ideas? 

Thanks

**Comment by sparrc** [comment]
Looks like something to do with systemd, I can't reproduce, what happens if you run `systemctl status`?

**Comment by Drewster727** [comment]
Looks like I get the same message when I run ```systemctl status```

```Failed to get D-Bus connection: Operation not permitted```

any ideas on how to fix this? re-install systemd somehow?

Thanks @sparrc

**Comment by Drewster727** [comment]
update, just ran ```sudo apt-get install --reinstall systemd```

it appears to have reinstalled it. However, running ```systemctl status``` yields the same error.

**Comment by sparrc** [comment]
I have no idea, sorry, but it's certainly not an issue with telegraf. Some googling comes up with some things about possible PID1 failing or the date being set back very far?
