### ISSUE TITLE
CloudEvents output data format support

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#10170]
### Proposal:
Support for Cloud Events JSON output format or a more flexible JSON serializer.

CloudEvents:
https://cloud.google.com/eventarc/docs/cloudevents
https://cloudevents.io/

### Current behavior:
Existing [JSON serializer](https://github.com/influxdata/telegraf/tree/master/plugins/serializers/json) that outputs data in this format:
```json
{
    "fields": {
        "field_1": 30,
        "field_2": 4,
        "field_N": 59,
        "n_images": 660
    },
    "name": "docker",
    "tags": {
        "host": "raynor"
    },
    "timestamp": 1458229140
}
```

### Desired behavior:

```json
{
  "specversion": "1.0",
  "type": "com.github.pull_request.opened",
  "source": "https://github.com/cloudevents/spec/pull",
  "subject": "123",
  "id": "A234-1234-1234",
  "time": "2018-04-05T17:31:00Z",
  "comexampleextension1": "value",
  "comexampleothervalue": 5,
  "datacontenttype": "application/json",
  "data": [
{
    "fields": {
        "field_1": 30,
        "field_2": 4,
        "field_N": 59,
        "n_images": 660
    },
    "name": "docker",
    "tags": {
        "host": "raynor"
    },
    "timestamp": 1458229140
}
  ]
}

```

The addition header information, customer hard codes those attributes, except for “time” which is current time and “id” which is a UUID.

### Use case: 
Want JSON from Telegraf to be manipulated to match the CloudEvents schema to then be loaded into Kafka. Want output support for CloudEvents JSON format to setup flexible since there could be several different subscribers that require CloudEvents format to the data in the future.

```
Data in some JSON format -> Telegraf -> Data in CloudEvents format -> Kafka -> InfluxDB
```

**Comment by powersj** [comment]
next steps: review what would be required to add and see if/how the format has changed since this was proposed to get an idea to see how stable it is.

**Comment by sjwang90** [comment]
@idclark said he was going to work on seeing if he could write a Starlark script to cover what the customer is currently doing with a python script so right now this isn't a major priority.
