### ISSUE TITLE
Timeout parameter for inputs.graylog

### ISSUE THREAD

**Issue by MSommer95** [influxdata/telegraf#10185]
### Proposal: 
Add configurable timeout value to graylog input plugin for the http request.

### Current behavior:
There is currently no parameter the us to configure iirc. 

### Desired behavior:
Having a parameter like: ``timeout = 10s`` for the Graylog input plugin.

### Use case: 
We lose a bit of data every now and then when the request runs into a timeout, which might be avoidable.

**Comment by powersj** [comment]
Hi,

Looks like we do have a configurable timeout in other inputs plugins, so this looks like something that might be helpful.

Thanks!

**Comment by SebastianThorn** [comment]
This seems to be the relevant code:

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/graylog/graylog.go#L130-L137
```go
		tr := &http.Transport{
			ResponseHeaderTimeout: 3 * time.Second,
			TLSClientConfig:       tlsCfg,
		}
		client := &http.Client{
			Transport: tr,
			Timeout:   4 * time.Second,
		}
```

**Comment by MSommer95** [comment]
I would love to make the necessary changes myself, but sadly I never worked with Go before. So I lack the confidence to implement this myself (even if its possibly quite simple, since other input plugins have done it before).

**Comment by SebastianThorn** [comment]
I can give it a shot this weekend!

**Comment by SebastianThorn** [comment]
I made these changes and it compiles, but I can not test it untill Monday when im back at work.
I have no Graylog-cluster at home.

https://github.com/SebastianThorn/telegraf/commit/2596345b7756df10c401712f6307f6f191271dc4
