### ISSUE TITLE
Kinesis input consumer plugin not working after update

### ISSUE THREAD

**Issue by jesusmogollon** [influxdata/telegraf#10197]
### Relevent telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 1000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false
  logtarget = "stderr"
  hostname = ""
  omit_hostname = false

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  database = "lasers"
  skip_database_creation = true
  username = "username"
  password = "password"

[[processors.rename]]
  [[processors.rename.replace]]
    measurement = "N"
    dest = "name"
  [[processors.rename.replace]]
    tag = "LS"
    dest = "serial"
  [[processors.rename.replace]]
    tag = "SID"
    dest = "session"
  [[processors.rename.replace]]
    tag = "ID"
    dest = "id"
  [[processors.rename.replace]]
    field = "T"
    dest = "messageType"
  [[processors.rename.replace]]
    field = "VT"
    dest = "valueType"
  [[processors.rename.replace]]
    field = "ID"
    dest = "id"
  [[processors.rename.replace]]
    field = "V"
    dest = "value"
  [[processors.rename.replace]]
    field = "VS"
    dest = "stringValue"

[[inputs.kinesis_consumer]]
  ## Amazon REGION of kinesis endpoint.
  region = "us-east-2"
  access_key = "*key*"
  secret_key = "*secret*"
  streamname = "lasers"

  shard_iterator_type = "TRIM_HORIZON"

  max_undelivered_messages = 500

  data_format = "json"

  tag_keys = [
    "LS",
    "SID",
    "ID"
  ]

  json_string_fields = ["T","VT","VS"]

  json_name_key = "N"

  json_time_key = "TS"

  json_time_format = "2006-01-02T15:04:05.000Z"
```

### System info

Telegraf 1.20.4 Ubuntu 20.04.3 LTS

### Steps to reproduce

Upgraded to the latest version and kinesis input plugin doesn't collect data anymore

### Expected behavior

Collect data as before or display an error to fix

### Actual behavior

Not collecting any data or displaying errors

### Additional info

I can see the access key used to connect to kinesis and the data is coming into the stream but no getrecords request is issued.
Running the telegraf with debug displays the following:
```
root:/etc/telegraf# telegraf --config telegraf.conf --debug
2021-11-30T18:00:29Z I! Starting Telegraf 1.20.4
2021-11-30T18:00:29Z I! Loaded inputs: kinesis_consumer
2021-11-30T18:00:29Z I! Loaded aggregators:
2021-11-30T18:00:29Z I! Loaded processors: rename
2021-11-30T18:00:29Z I! Loaded outputs: influxdb
2021-11-30T18:00:29Z I! Tags enabled: host=ip-172-31-96-182
2021-11-30T18:00:29Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"server", Flush Interval:10s
2021-11-30T18:00:29Z D! [agent] Initializing plugins
2021-11-30T18:00:29Z D! [agent] Connecting outputs
2021-11-30T18:00:29Z D! [agent] Attempting connection to [outputs.influxdb]
2021-11-30T18:00:29Z D! [agent] Successfully connected to outputs.influxdb
2021-11-30T18:00:29Z D! [agent] Starting service inputs
2021-11-30T18:00:39Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:00:49Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:00:59Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:01:09Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:01:19Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:01:29Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
2021-11-30T18:01:39Z D! [outputs.influxdb] Buffer fullness: 0 / 1000 metrics
```

and keeps like this for ever

**Comment by reimda** [comment]
Hi @jesusmogollon, what version were you using before the update? Can you run `telegraf --config telegraf.conf --debug` with that version and the config you included? Thanks!

**Comment by jesusmogollon** [comment]
@reimda I installed back 1.18.3 and everything runs smoothly.
Same config file.
I did not want to upgrade to see what exact version is not behaving (beside latest), but I may do that this week.

**Comment by srebhan** [comment]
@jesusmogollon does the issue still persist?

**Comment by dr3amville** [comment]
@srebhan this issue still persists in the version 1.24.

**Comment by dr3amville** [comment]
@srebhan any plan to review this issue soon or is it lower on the backlog? 🙂

**Comment by powersj** [comment]
@dr3amville,

The plugins that deal with cloud services are a little harder for us to work on without access or direct experience with them. If I created a debug version of telegraf to try to collect some additional information about what might be happening, would you be willing to give that a try?

Thanks!

**Comment by dr3amville** [comment]
@powersj I could certainly give it a shot. Will try to create a test environment for this if you can provide the debug ver. of telegraf.

**Comment by powersj** [comment]
Alright, I put up https://github.com/influxdata/telegraf/pull/12694 which has some additional logging. If you could give that a shot and provide the logs you get I'd appreciate it. We can then see a bit more about what is going on when the plugin is running and determine where to look into next.

**Comment by powersj** [comment]
@dr3amville were you able to give the artifacts in #12694 a try to see if anything came out of that?
