### ISSUE TITLE
Add config management to telegraf

### ISSUE THREAD

**Issue by isodude** [influxdata/telegraf#10204]
## Feature Request

A tool or config option such that you can view configuration and change them, very much like sysctl.

### Proposal:

Add params to view parsed config
Add params to change config and write to disk
Add params to verify config

### Current behavior:

Telegraf can only generate example config

### Desired behavior:

Telegraf can fully manage config

### Use case:

Ease of use during
* troubleshooting
* deployment

Instead of creating files, I can generate and validate my input and thus always having correct config.
I could verify the config to make sure that everything checks out. This could be a ExecPreStart much like nginx.

Instead of poking through files I can print telegraf config and view what is set.

Adding or changing config for a plugin is simpler on a broad scale by just running one command to change a specific setting for a plugin.

**Comment by sjwang90** [comment]
Hi @isodude, thank you for bringing this up and glad to hear this is something you're looking for Expanded configuration management capabilities in Telegraf is something we're looking to add. Would you add your use case and any other notes to this issue #7519 so we can keep all the information in one place. Thank you!
