### ISSUE TITLE
Adjust telegraf.Logger to be easy to use in whole codebase

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#10212]
## Feature Request

- Adjust `telegraf.Logger` to be easy to use in whole codebase, not only inside `plugins` (`aggregators`, `inputs`, `outputs`, `parsers` and `processors`).
- Moreover, `telegraf.Logger` should be also injected for `plugins/serializers` (as it is for other type of plugins).
- https://github.com/influxdata/telegraf/blob/master/docs/developers/LOGGING.md will need to be adjusted to reflect implemented changes.
- Forbids using `"log"` in whole codebase (by remove rule in `.golangci.yml` introduced in https://github.com/influxdata/telegraf/pull/10191 )

**Comment by srebhan** [comment]
I think all that is needed is to move the logging facility out of `models` to avoid circular dependencies. Then you can just do

```golang
import "github.com/influxdata/telegraf/logger"

var log = logger.New("mycategory", "mymodule", "myalias")

log.Warnf("This might go wrong...")
```
