### ISSUE TITLE
Reg - Adding mutiple conf files in telegraf windows

### ISSUE THREAD

**Issue by parthi-kk** [influxdata/telegraf#10223]
Hello Team, 

How to run the two different telegraf.conf files in windows Server from a single telegraf data collector?

**Comment by powersj** [comment]
Hi,

Please take a look at the [docs here](https://docs.influxdata.com/telegraf/v1.20/administration/configuration/#configuration-file-locations) around using `--config-directory` for multiple configuration files.

I am going to go ahead and close this issue as it is a support issue. Please do check out our Slack or Community Page where others can answer these types of questions and usually faster!

Thanks!
