### ISSUE TITLE
Training: OpenTelemetry

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#10228]
## Overview

Want to understand what OpenTelemetry is as it is often called Telegraf's biggest competitor.

## Questions

- What is OpenTelemetry?
- How do you run OpenTelemetry?
- Where is OpenTelemetry supported (e.g. OSes and Architechtures)?
- Where are their source code repos?
- How do I contribute a new metric gathering tool?
- Where do they compete with Telegraf?
- Are there capabilities around Telegraf to be better compatible with Open Telemetry? (e.g. better logging and tracing?)
- Are there agent functionalities that OpenTelemetry Collector has that Telegraf doesn't?

## Background

Telegraf currently supports an OpenTelemetry [Input](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/opentelemetry/README.md) and [Output](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/opentelemetry/README.md) plugin

## Educational material

- Jacob Marble's [InfluxDays Talk](youtube.com/watch?v=LFAGFX_aCY8)
- https://opentelemetry.io/
- https://opentelemetry.io/docs/collector/

## Expected Result

* Ansers to the above questions :)

**Comment by powersj** [comment]
Moving to internal tracker
