### ISSUE TITLE
OPC UA Client to support Data Change Subscription 

### ISSUE THREAD

**Issue by Jayclifford345** [influxdata/telegraf#10235]
### Proposal:
OPC UA Client should be given the ability to subscribe to OPC UA server tags using a Data Change subscription. This would allow Telegraf to collect all metric changes coming from the OPC UA server. This is much like how the MQTT Client works in the fact we accept all incoming messages from a given topic. 

https://github.com/gopcua/opcua/blob/main/examples/subscribe/subscribe.go

### Current behaviour:
If I have an OPC UA tag that acts as an incremental counter (1, 2, 3, 4, 5). The Telegraf OPC UA client will only collect the current tag state based on the interval trigger. This means state changes within that interval time are lost.

### Desired behaviour:
Using a Data change subscription means that each time the OPC UA server tag updates our client also collects the new value. This means that all tag changes no matter the interval trigger are collected by Telegraf. 

### Use case: 
In most industrial use cases of OPC UA users care about the state changes of tags within a server. This could be an engine value turning from on to off. Or an alarm being triggered.

**Comment by R290** [comment]
Duplicate of https://github.com/influxdata/telegraf/issues/8083?

**Comment by Jayclifford345** [comment]
Hi @R290 you are correct! I will link and close this one out: 
https://github.com/influxdata/telegraf/issues/8083
