### ISSUE TITLE
Enum Processor Plugin not working after upgrade from 1.14.4 to 1.18.3

### ISSUE THREAD

**Issue by RemcoAA** [influxdata/telegraf#10232]
We are testing a Telegraph update from 1.14.4 to 1.18.3 and we have some issues with the Enum Processor Plugin.

We have the following config:

```
name_prefix = "snmp_defensepro"

  [[inputs.snmp.table]]
    name = "_fans"
    oid =  "RADWARE-MIB::rsSystemFansTable"
    inherit_tags = [ "sysname" ]

#Processors
[[processors.enum]]
  namepass = ["snmp_defensepro_fans"]
  order = 1
  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "rsSystemFansStatus"
    default = 0
    ## Table of mappings
    [processors.enum.mapping.value_mappings]
    OK = 1
```

After the upgrade to v1.18.3 the fan metrics are always '0' set by the default rule. While the result of the snmpwalk gives:

RADWARE-MIB::rsSystemFanIndex.1 = INTEGER: 1
RADWARE-MIB::rsSystemFanIndex.2 = INTEGER: 2
RADWARE-MIB::rsSystemFanIndex.3 = INTEGER: 3
RADWARE-MIB::rsSystemFansStatus.1 = STRING: "OK"
RADWARE-MIB::rsSystemFansStatus.2 = STRING: "OK"
RADWARE-MIB::rsSystemFansStatus.3 = STRING: "OK"

So after the upgrade the "OK" is no longer mapped to '1'.

Is this a know issue and is this fixed in later versions?

Has the working of the plugin changed?

**Comment by RemcoAA** [comment]
We have also tested v1.20.4 and also in this version the enum mapping does not work.

**Comment by Hipska** [comment]
Could you give an example of snmp_defensepro_fans when the processor is not enabled. (for example by running telegraf with `--test`)

**Comment by RemcoAA** [comment]
> snmp_defensepro_fans,agent_host=<device-fqdn>,host=telegraf-1,rsSystemFanIndex=3, rsSystemFansStatus="OK" 1638962351000000000
> snmp_defensepro_fans,agent_host=<device-fqdn>,host=telegraf-1,rsSystemFanIndex=1, rsSystemFansStatus="OK" 1638962351000000000
> snmp_defensepro_fans,agent_host=<device-fqdn>,host=telegraf-1,rsSystemFanIndex=2, rsSystemFansStatus="OK" 1638962351000000000

**Comment by Hipska** [comment]
Did you remove anything in there? That doesn't look valid. (The last `,` at the end of the tag list)

**Comment by RemcoAA** [comment]
Yes, I did remove some tags. This is the complete output with the tags.

snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=1,sysname=xxx rsSystemFansStatus="OK" 1638963410000000000
snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=2,sysname=xxx rsSystemFansStatus="OK" 1638963410000000000
snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=3,sysname=xxx rsSystemFansStatus="OK" 1638963410000000000

**Comment by Hipska** [comment]
Sorry, I couldn't find any problem with these metrics and the enum processor.

**Comment by RemcoAA** [comment]
Did you test with the "default = 0" option?

Because when we use this everything is mapped to 0

**Comment by Hipska** [comment]
I'm using this config:
```toml

[[inputs.file]]
  files = ["snmp_defensepro_fans.txt"]

[[processors.enum]]
  namepass = ["snmp_defensepro_fans"]
  order = 1
  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "rsSystemFansStatus"
    default = 0
    ## Table of mappings
    [processors.enum.mapping.value_mappings]
      OK = 1
```
And this is the result:
```
2021-12-22T10:43:36Z I! Starting Telegraf 1.21.1
2021-12-22T10:43:36Z I! Loaded inputs: file
2021-12-22T10:43:36Z I! Loaded aggregators: 
2021-12-22T10:43:36Z I! Loaded processors: enum
2021-12-22T10:43:36Z I! W! Outputs are not used in testing mode!
2021-12-22T10:43:36Z I! Tags enabled: host=dama
> snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=1,sysname=xxx rsSystemFansStatus=1i 1638963410000000000
> snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=2,sysname=xxx rsSystemFansStatus=1i 1638963410000000000
> snmp_defensepro_fans,agent_host=xxx,host=telegraf-ddos-1,label_env=xxx,rsSystemFanIndex=3,sysname=xxx rsSystemFansStatus=1i 1638963410000000000

```

**Comment by RemcoAA** [comment]
Did you also test with v1.18.3 or v1.20.4?

**Comment by Hipska** [comment]
No, but I have a system that runs 1.18.1 and there I have the same expected behaviour. Can you try with latest version of telegraf?

Are you sure this is the only processor that is touching that metric?
