### ISSUE TITLE
datadog output plugin changes "_" -> "." 

### ISSUE THREAD

**Issue by veverjak** [influxdata/telegraf#1024]
Datadog output plugin changes "_" -> "." (https://github.com/influxdata/telegraf/blob/master/plugins/outputs/datadog/datadog.go#L74)  and there is no option to change this behavior. 

It would be nice to have switch to disable this, also default should be that nothing is changed.

Also I am not following influx world for long, but it would IMO make sense to edit metrics on input only.

**Comment by hauleth** [comment]
The documentation wasn't updated since then and I think it should be an option.

**Comment by danielnelson** [comment]
@hauleth Can you open a new issue with the feature request?
