### ISSUE TITLE
I want to monitor log patterns.

### ISSUE THREAD

**Issue by SIKIM92** [influxdata/telegraf#10249]
I want to monitor log patterns.
For example, if the word 'ERROR' is found in the /var/log/message file.
Are there any plugins I can use?

Need to write a script using the exec plugin?

**Comment by srebhan** [comment]
@SIKIM92 first of all, I have to agree with our bot. Please use issues for bugs, feature requests and code-related discussions and ask those questions in either Slack or the forum.
Anyway, you have multiple possibilities e.g. using the [syslog input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog) or the [tail input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tail) with the [grok parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok) and possible a bunch of others. The exact choice depends a bit on your use-case, so please pass by in the `#telegraf` Slack channel or the forum...
