### ISSUE TITLE
Do not accept any media type in the prometheus input

### ISSUE THREAD

**Issue by jonatan-ivanov** [influxdata/telegraf#10248]
### Relevent telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["http://localhost:8080/metrics"]
```

### System info

Telegraf 1.20.4 MacOS 11.6.1

### Steps to reproduce

The issue is related to the [`Accept` header](https://github.com/influxdata/telegraf/blob/31cbd2e504ad0a053a06b7669592009295c6a57e/plugins/inputs/prometheus/prometheus.go#L27) of the Prometheus input plugin:

1. Let's say we have a service that prefers the OpenMetrics format or exclusively supports it
2. Since Telegraf accepts any media types (see: https://github.com/influxdata/telegraf/pull/6745) it should be able to parse the OpenMetrics format in the response (because of `*/*`)
3. But Telegraf is not able to parse the OpenMetrics format (see: https://github.com/influxdata/telegraf/issues/9547) so it fails with:

```
2021-12-09T02:43:40Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://localhost:8080/metrics: reading text format failed: text format parsing error in line 118: invalid escape sequence '\"'
```

### Expected behavior

Telegraf should only accept the formats it supports (no `*/*`):
```
application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3
```

### Actual behavior

Telegraf should not accept everything (see `*/*`):
```
application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3,*/*;q=0.1
```

In this case, if the service only support OpenMetrics, Telegraf should get `406 Not Acceptable` instead of a response in the OpenMetrics format that it tries and fails to parse.

### Additional info

Prometheus itself also defines `*/*` as a fallback but it supports both formats (and it prefers OpenMetrics) so it does not get into any trouble if the client prefers or only supports OpenMetrics:
```
application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
```

**Comment by powersj** [comment]
Next steps: [previous PR](https://github.com/prometheus/prometheus/blob/1fa5a75a3a066778de5a78305141ed0dcb791cc3/scrape/scrape.go#L518) changed the accept header in the Prometheus plugin to accept any media types. However, since that PR it appears that this returns open metrics results now. Telegraf does not support this metric type, and therefore Telegraf should be explicit about what type it wants.
