### ISSUE TITLE
Is there any documentation of telegraf related metrics exposed to Prometheus?

### ISSUE THREAD

**Issue by shubhamcoc** [influxdata/telegraf#10257]
Hi, I have enabled the internal plugin to collect the telegraf related metrics from the Prometheus client output plugin.

I am getting the output below mentioned output along with go stats. 
internal_write_write_time_ns{output="health",version="1.19.3"}  
internal_write_write_time_ns{output="prometheus_client",version="1.19.3"} 

internal_write_metrics_written{output="health",version="1.19.3"}  
internal_write_metrics_written{output="prometheus_client",version="1.19.3"} 

internal_write_metrics_filtered{output="health",version="1.19.3"}  
internal_write_metrics_filtered{output="prometheus_client",version="1.19.3"} 

internal_write_metrics_dropped{output="health",version="1.19.3"}  
internal_write_metrics_dropped{output="prometheus_client",version="1.19.3"} 

internal_write_metrics_added{output="health",version="1.19.3"} 
internal_write_metrics_added{output="prometheus_client",version="1.19.3"} 

internal_write_errors{output="health",version="1.19.3"} 
internal_write_errors{output="prometheus_client",version="1.19.3"} 

internal_write_buffer_size{output="health",version="1.19.3"}  
internal_write_buffer_size{output="prometheus_client",version="1.19.3"} 

internal_write_buffer_limit{output="health",version="1.19.3"} 
internal_write_buffer_limit{output="prometheus_client",version="1.19.3"} 

internal_gather_metrics_gathered{input="internal",version="1.19.3"}  
internal_gather_metrics_gathered{input="statsd",version="1.19.3"} 

internal_gather_gather_time_ns{input="internal",version="1.19.3"} 
internal_gather_gather_time_ns{input="statsd",version="1.19.3"}

internal_gather_errors{input="internal",version="1.19.3"}  
internal_gather_errors{input="statsd",version="1.19.3"} 

internal_agent_metrics_written{go_version="1.16.6",version="1.19.3"}
internal_agent_metrics_gathered{go_version="1.16.6",version="1.19.3"} 
internal_agent_metrics_dropped{go_version="1.16.6",version="1.19.3"} 
internal_agent_gather_errors{go_version="1.16.6",version="1.19.3"} 

If no document is there, I have a few doubts about the metrics, It will be helpful if someone can confirm that the assumptions are correct or not.

1. What are the agent-related metrics? My understanding is, the agent is a framework that calls the input and output plugins functions. (gather and write). so **internal_agent_gather_gathered**, **internal_agent_gather_errors** represent all the input plugins gather errors. Is this assumption correct? 

2. Difference between writing drop and write error? In the case of writing drop telegraf store it in the buffer for retry, in case of write error, it means it failed to write the data to the sink.

3. What does **internal_write_metrics_added** represent?

4. **internal_write_buffer_size** is used for creating batch write or it is used in case of metrics drop only? 

Is there any document that I can refer to?

**Comment by sjwang90** [comment]
I'm going to close this as I believe you received all your questions in slack. We'll add more documentation around the `inputs.internal` plugin for clarification.
