### ISSUE TITLE
Better mongodb metrics organisation

### ISSUE THREAD

**Issue by Victor-D** [influxdata/telegraf#10256]
## Feature Request

Hello guys

I think operation stats such as insert, queries, update, delete etc should not be returned like `mongodb.<operation_name>` but more something like `mongodb.opcounters.<operation_name>`

It will be more easy to select all operations and graph them using a regexp such as `mongodb.opcounters.*`

### Proposal:

Add the `opcounters` metric prefix for operation counters statistics.

### Current behavior:

All operations stats are mixed with other metrics at root :

```
mongo.insert
mongo.query
mongo.update
mongo.delete
mongo.getmore
mongo.command
mongorepl.insert
mongorepl.query
mongorepl.update
mongorepl.delete
mongorepl.getmore
mongorepl.command
[...]
repl_apply_batches_num=219929i,
repl_apply_batches_total_millis=0i,
repl_apply_ops=229847i,
repl_buffer_count=0i,
repl_buffer_size_bytes=0i,
[...]
```

### Desired behavior:

```
mongo.opcounters.insert
mongo.opcounters.query
mongo.opcounters.update
mongo.opcounters.delete
mongo.opcounters.getmore
mongo.opcounters.command
mongo.opcountersrepl.insert
mongo.opcountersrepl.query
mongo.opcountersrepl.update
mongo.opcountersrepl.delete
mongo.opcountersrepl.getmore
mongo.opcountersrepl.command
```

### Use case:

It will be more easy to select all operations and graph them using a regexp such as `mongodb.opcounters.*`

This is an example for operation stats/counters but maybe other metrics could be group too.

Regards
Victor

**Comment by sspaink** [comment]
Sorry for the late response, are you still interested in this feature request? Because this would be a breaking change, in order to roll this out we would require a feature flag to enable it. Would you perhaps be interested in trying to create a pull request?
