### ISSUE TITLE
Modbus plugin: support 8-bit values (boolean)

### ISSUE THREAD

**Issue by meowcat** [influxdata/telegraf#10266]
## Feature Request

We are using `ARRAY[0..63] OF BOOL` in holding registers of our PLC. These are stored as **one byte per bool** (unlike coil registers). When reading out the values via Modbus, one word of two bytes gets read into two booleans (or 8-bit integers, for that matter).

For example, using the `modbus_cli` tool https://github.com/favalex/modbus-cli, they are read with the config
```
First_byte h@13441/xb
Second_byte h@13441/bx
```
(where `h@` is "holding register", `13441` is the address, and `xb`, `bx` are the [pack format](https://docs.python.org/3/library/struct.html#format-characters) strings to extract the higher or the lower byte respectively.

### Proposal:

* Variant 1: Two new `data_type`s called `BYTE8_H`, `BYTE8_L` to refer to the high or low byte, respectively
* Variant 2: One new `data_type` called `BYTE`, which could be read with either `byte_order = AB` or `BA` depending on which one the user wants to access.

### Use case:
See above.

**Comment by meowcat** [comment]
Dirty hack, currently (have to verify which is hi and which is lo):

```
{ name = "bool_13444a", byte_order = "BA", data_type = "UINT16", scale = 0.00390625, address = [13444]},
{ name = "bool_13444b", byte_order = "AB", data_type = "UINT16", scale = 0.00390625, address = [13444]},
```

**Comment by maufc** [comment]
> Dirty hack, currently (have to verify which is hi and which is lo):
> 
> ```
> { name = "bool_13444a", byte_order = "BA", data_type = "UINT16", scale = 0.00390625, address = [13444]},
> { name = "bool_13444b", byte_order = "AB", data_type = "UINT16", scale = 0.00390625, address = [13444]},
> ```

It looks great but I get an error (on request method):
[telegraf] Error running agent: could not initialize input inputs.modbus: configuraton invalid: unknown byte-order "BA"

**Comment by maufc** [comment]
Ok. I tried 

> Dirty hack, currently (have to verify which is hi and which is lo):
> 
> ```
> { name = "bool_13444a", byte_order = "BA", data_type = "UINT16", scale = 0.00390625, address = [13444]},
> { name = "bool_13444b", byte_order = "AB", data_type = "UINT16", scale = 0.00390625, address = [13444]},
> ```

Ok. I tried with register method and it worked. 
Could be a way to make it on reguest method as it allows different data types in the same query?
Thanks!

**Comment by srebhan** [comment]
This will not work with the `request` configuration as it does not support changing the byte-order for a request. You probably need to use two `request` sections with different byte-orders...

**Comment by srebhan** [comment]
@maufc and @meowcat can you please test the binary built by CI from #12255 and let me know if this is what you expected?!?
