### ISSUE TITLE
Best ways to monitor Telegraf

### ISSUE THREAD

**Issue by Victor-D** [influxdata/telegraf#10271]
Hello

What is the best way to monitor Telegraf on hosts ?

I'm thinking of :
Telegraf service status
Custom input module with non 0 exit code
Disabled input module because too many errors
Issue with flushing / writing to remote backend

I also found the inputs.internal module to retrieve internal stats, but it does not work with --test:
```
# telegraf --test --input-filter inputs.internal
2021-12-14T16:29:20Z I! Starting Telegraf 1.15.3
2021-12-14T16:29:20Z I! Using config file: /etc/telegraf/telegraf.conf
2021-12-14T16:29:20Z E! [telegraf] Error running agent: Error: no inputs found, did you provide a valid config file?
```
and I don't want to send theses kind of metrics.

Regards
Victor

**Comment by powersj** [comment]
Your command is using the configuration file `/etc/telegraf/telegraf.conf`, which does not have any inputs enabled. The internal plugin does work with `--test`:

```
./telegraf --test --config config2.toml 
2021-12-14T16:37:15Z I! Starting Telegraf 1.21.0-393c5e60
2021-12-14T16:37:15Z I! Loaded inputs: internal
2021-12-14T16:37:15Z I! Loaded aggregators: 
2021-12-14T16:37:15Z I! Loaded processors: 
2021-12-14T16:37:15Z I! W! Outputs are not used in testing mode!
2021-12-14T16:37:15Z I! Tags enabled: host=ryzen
> internal_memstats,host=ryzen alloc_bytes=10614752i,frees=80600i,heap_alloc_bytes=10614752i,heap_idle_bytes=13778944i,heap_in_use_bytes=13942784i,heap_objects=57390i,heap_released_bytes=11968512i,heap_sys_bytes=27721728i,mallocs=137990i,num_gc=6i,pointer_lookups=0i,sys_bytes=41763848i,total_alloc_bytes=19945224i 1639499836000000000
> internal_agent,go_version=1.17.5,host=ryzen,version=1.21.0-393c5e60 gather_errors=0i,metrics_dropped=0i,metrics_gathered=1i,metrics_written=0i 1639499836000000000
> internal_gather,host=ryzen,input=internal,version=1.21.0-393c5e60 errors=0i,gather_time_ns=0i,metrics_gathered=1i 1639499836000000000
```

If you do not want these metrics going to an output, then you could use the `namedrop` option to not send them anywhere.

We've recently talked about exposing a more detailed error mechanism, but for now the internal plugin is one option, the other is to parse the telegraf log itself looking for specific errors you are concerned about.

**Comment by Victor-D** [comment]
Hello Joshua

Thanks for the quick answer.

Ideally having the possibility to perform a curl http://localhost:xxxx/status on a local telegraph web endpoint generating a json response with the stats would be perfect.

**Comment by Victor-D** [comment]
solution is to add the input plugin and filter it out
or parse the telegraf logs
