### ISSUE TITLE
Telegraf 1.21.1, input plugin `disk` doesn't report data for non-partitioned disks

### ISSUE THREAD

**Issue by 999eagle** [influxdata/telegraf#10297]
### Relevent telegraf.conf

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
```

### System info

Telegraf 1.12.1 running in Docker 20.10.8

### Docker

```
services:
  telegraf:
    image: telegraf:1.21
    environment:
      HOST_PROC: /host/proc
      HOST_MOUNT_PREFIX: /host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/host:ro
      - /sys:/host/sys:ro
```  

### Steps to reproduce

1. Update Telegraf to 1.21.1
2. Look at the `disk` metrics

### Expected behavior

All disks (`/dev/sda1` and `/dev/sdb`) should export data.

### Actual behavior

Only data for `/dev/sda1` is visible, `/dev/sdb` is missing.

### Additional info

The `diskio` input plugin still reports data for `/dev/sdb` after the update to 1.21.1, only `disk` is missing data. I've tried the [Troubleshooting](https://github.com/influxdata/telegraf/tree/v1.21.1/plugins/inputs/disk#troubleshooting) instructions and both expected disks (`/dev/sda1` and `/dev/sdb`) show up in the Docker container as a mount under `/host` with an `ext4` filesystem and `stat` succeeds for both.

Downgrading the Docker image to 1.20.4 fixes the issue and `/dev/sdb` has data again. There's no 1.21.0 image I could test with but data stopped being available after the upgrade from 1.21.0 to 1.21.1.

**Comment by powersj** [comment]
Hi,

Can you provide an example output from 1.20.4 and what are you now seeing on 1.21.1?

Thanks!

**Comment by powersj** [comment]
ok one more, can you run `lsblk` and provide that output as well? Thanks

**Comment by 999eagle** [comment]
Sure

```
# lsblk   
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0 38.2G  0 disk 
└─sda1   8:1    0 38.2G  0 part /
sdb      8:16   0   80G  0 disk /mnt/storage
sr0     11:0    1 1024M  0 rom  
```

**Comment by reimda** [comment]
I think this is a side effect of the change to run Telegraf as a non-root user. (see https://github.com/influxdata/influxdata-docker/pull/536). The partition devices are owned by root:disk but the disk device is owned by root:root.

**Comment by dedworks** [comment]
Same here, we have watchtower updating `telegraf:alpine` every morning, and have no data from the disk since this morning's update. Data starts collecting again when I switch to `telegraf:1.20.4-alpine`

**Comment by dontobi** [comment]
> Same here, we have watchtower updating `telegraf:alpine` every morning, and have no data from any disks since this morning's 1.21.1 update. Trouble clears when I roll back to `telegraf:1.20-alpine` (1.20.4)

I can confirm this. Rolled back to 1.20.4 and everything works.

**Comment by 999eagle** [comment]
@reimda I'm running Telegraf 1.20.4 with a non-root account now and still get data for all disks, so I'm pretty sure it's not about being root or not.

**Comment by eskemojoe007** [comment]
Not as savvy as you all, but running in docker `telegraf:latest` for 1.21.1 lost me data around my secondary disk sizes as well.  Downgrading to 1.20.4 fixed it right up.  Just wanted to provide a +1 on this one.

**Comment by pkoenig10** [comment]
Also seeing this problem on 1.21.1. Downgrading to 1.20.4 resolved the issue. Agree with @999eagle that this doesn't appear to be about running as a non-root user - that change happened in 1.20.3.

**Comment by srebhan** [comment]
Are you sure that in both environments the disk-in-question is mounted? Is it visible for the telegraf user in `/proc/self/mounts`?

**Comment by 999eagle** [comment]
@srebhan Yes, the disk appears inside the container, both in `/proc/self/mounts` and `/host/proc/self/mounts`.

**Comment by srebhan** [comment]
@999eagle can you post your `disk` part of your telegraf configuration and the content of `/proc/1/mountinfo` and `/proc/self/mountinfo` in your container? The background is that the underlying [gopsutil library](https://github.com/shirou/gopsutil) changed the path from [v3.21.8](https://github.com/shirou/gopsutil/blob/5268453c1e25853698065e9e5cb14afc175610c3/disk/disk_linux.go#L224) to [v3.21.10](https://github.com/shirou/gopsutil/blob/36cc0d3c0b09a295f954f0b8f9cb6e4b65719175/disk/disk_linux.go#L224)...

**Comment by srebhan** [comment]
@999eagle and if possible also show `/host/proc/1/mountinfo`...

**Comment by 999eagle** [comment]
@srebhan I've already posted that part of my telegraf config in the initial post. Here it is again:

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
```

Here are the mountinfo contents from inside the container read from the telegraf user:

```
$ cat /proc/1/mountinfo | grep sd[ab]
1506 1450 8:1 / /host ro,relatime master:1 - ext4 /dev/sda1 rw,discard,errors=remount-ro
1616 1506 8:16 / /host/mnt/storage rw,relatime master:67 - ext4 /dev/sdb rw,discard
1768 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1772 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hostname /etc/hostname rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1773 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1791 1450 8:1 /srv/monitor/telegraf.conf /etc/telegraf/telegraf.conf ro,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro

$ cat /proc/self/mountinfo | grep sd[ab]
1506 1450 8:1 / /host ro,relatime master:1 - ext4 /dev/sda1 rw,discard,errors=remount-ro
1616 1506 8:16 / /host/mnt/storage rw,relatime master:67 - ext4 /dev/sdb rw,discard
1768 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1772 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hostname /etc/hostname rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1773 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1791 1450 8:1 /srv/monitor/telegraf.conf /etc/telegraf/telegraf.conf ro,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro

$ cat /host/proc/self/mountinfo | grep sd[ab]
1506 1450 8:1 / /host ro,relatime master:1 - ext4 /dev/sda1 rw,discard,errors=remount-ro
1616 1506 8:16 / /host/mnt/storage rw,relatime master:67 - ext4 /dev/sdb rw,discard
1768 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1772 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hostname /etc/hostname rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1773 1450 8:1 /var/lib/docker/containers/411765e05d8017fe7583eb3b965f1babed5df69ff4bff039898b8b5488b7aeac/hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
1791 1450 8:1 /srv/monitor/telegraf.conf /etc/telegraf/telegraf.conf ro,relatime - ext4 /dev/sda1 rw,discard,errors=remount-ro
```

Apparently, both `sda1` and `sdb` show up in all three mountinfos as expected.

**Comment by srebhan** [comment]
@999eagle sorry for asking for the config twice. :-/

I'm not sure if this makes a difference, but as I said, the underlying library changed the reads. So (with your HOST_PROC setting) the old version (used in telegraf 1.20) references to `/host/proc/self/mountinfo` containing
```txt
1616 1506 8:16 / /host/mnt/storage rw,relatime master:67 - ext4 /dev/sdb rw,discard
```
the newer version (used in telegraf 1.21) references `/host/proc/1/mountinfo` containing
```txt
126 31 8:16 / /mnt/storage rw,relatime shared:67 - ext4 /dev/sdb rw,discard
```

Please note the difference in the mount-point (`/host/mnt/storage` vs. `/mnt/storage`). As a second step, telegraf calls `statfs` (which is equivalent to `stat -f <path to the mountpoint>`) on that mount-point. I.e. it will now check for `/mnt/storage` in the container. Does that mount-point exist in the container? As otherwise the partition is silently dropped... :-(

**Comment by 999eagle** [comment]
Ah hm. No, the path `/mnt/storage` doesn't exist in the container as that's the mount point on the host system. Seems like this issue is caused by https://github.com/shirou/gopsutil/pull/1133 and probably should be fixed in gopsutil by rewriting paths when using the `HOST_PROC` variable before returning from `PartitionsWithContext`.

Could this be fixed in telegraf by either rolling back the library version of gopsutil or rewriting paths in telegraf (most likely by prepending the contents of `HOST_MOUNT_PREFIX`)?

**Comment by srebhan** [comment]
@999eagle to track-down the cause of the issue, can you please run the [artifact built by CI](https://github.com/influxdata/telegraf/pull/10318#issuecomment-998924944). It will only output some debug messages to find out where the partition in question is dropped (so please run `telegraf --debug --once`). Can you send me the (redacted) output please?

**Comment by srebhan** [comment]
> Could this be fixed in telegraf by either rolling back the library version of gopsutil or rewriting paths in telegraf (most likely by prepending the contents of HOST_MOUNT_PREFIX)?

Yeah I first try to see if we can somehow fix the changed behavior and otherwise role-back to the older version even though there might be a reason why this was upgraded...

**Comment by 999eagle** [comment]
@srebhan I think this is the relevant part of the output:

```
[inputs.disk] [SystemPS] partition 5: {"device":"/dev/sda1","mountpoint":"/","fstype":"ext4","opts":["rw","relatime"]}  
[inputs.disk] [SystemPS] => kept...                                                                                     
<snip>
[inputs.disk] [SystemPS] partition 32: {"device":"/dev/sdb","mountpoint":"/mnt/storage","fstype":"ext4","opts":["rw","relatime"]}
[inputs.disk] [SystemPS] => dropped by disk usage ("/mnt/storage"): no such file or directory
```

**Comment by srebhan** [comment]
Exactly. So I guess the correct mount-point is `/host` and `/host/mnt/storage` for `sda1` and `sdb`? This will potentially create false values for `/dev/sda1` as it reads the container root instead of the host one...

**Comment by 999eagle** [comment]
Exactly. The current output contains the mount points for the host (which is to be expected when reading `/host/proc/1/mountinfo`). Prepending `$HOST_MOUNT_PREFIX` to both paths would lead to correct paths inside the container.

**Comment by srebhan** [comment]
@999eagle I pushed a new version of #10318 hopefully fixing this issue. Can you please test once CI finished the build?

**Comment by 999eagle** [comment]
@srebhan no new artifact for amd64 was built there because the tests failed due to a missing container image. Can you please rerun the CI pipeline?

**Comment by srebhan** [comment]
@999eagle I see it and I tried multiple time. However it seems like [CircleCI has issues currently](https://status.circleci.com/)... Will try again ASAP...

**Comment by srebhan** [comment]
@999eagle build passed, you can grab the artifacts now...

**Comment by 999eagle** [comment]
I've tested the new artifact now (again with `--once --debug`), here's the relevant log:

```
D! [inputs.disk] [SystemPS] partition 5: {"device":"/dev/sda1","mountpoint":"/","fstype":"ext4","opts":["rw","relatime"]}
D! [inputs.disk] [SystemPS] -> using mountpoint "/host"...                                                               
D! [inputs.disk] [SystemPS] => kept...                                                                                   
<snip>
D! [inputs.disk] [SystemPS] partition 32: {"device":"/dev/sdb","mountpoint":"/mnt/storage","fstype":"ext4","opts":["rw","relatime"]}
D! [inputs.disk] [SystemPS] -> using mountpoint "/host/mnt/storage"...
D! [inputs.disk] [SystemPS] => kept...
```

Seems like the mount points are now correct and thus both devices are kept! Thanks!

**Comment by voiprodrigo** [comment]
Are these new debug messages going to stay in the release? Installed 1.21.2 and it's a lot of verbosity which probably is no longer necessary?

**Comment by srebhan** [comment]
@voiprodrigo you will only see those messages in debug mode which is not recommended for production. Do you see any issues with keeping those?

**Comment by voiprodrigo** [comment]
@srebhan I run with debug to keep an eye on the buffer messages mostly, and had no issue whatsoever from that. If this output remains in the code, I'll definitely stop running debug. Maybe a good feature would be a possibility to override debug output for a specific output, I'd definitely use that to silence inputs.disk.
