### ISSUE TITLE
output os system information

### ISSUE THREAD

**Issue by duanyifei1937** [influxdata/telegraf#10294]
telegraf how to output os system information an metrics?
like prometheus node-exporter: 
  `node_uname_info{domainname="(none)", instance="localhost:9100", job="node", machine="x86_64", nodename="xxxhelloxxx", release="4.4.0-131-generic", sysname="Linux", version="#157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018"}`
maybe need read system path:
  /proc/sys/kernel/version
  /proc/sys/kernel/osrelease
  .etc.

**Comment by srebhan** [comment]
@duanyifei1937 the easierst is to write a small shell script to output that information in line-protocol. The use the `exec` input plugin to get this into telegraf... Would that solve your issue?

**Comment by powersj** [comment]
Going to go ahead and close this one. As srebhan has suggested if you have a number of custom fields you want to collect using the `exec` plugin is usually best to allow you to customize freely.
