### ISSUE TITLE
The repository 'https://repos.influxdata.com/raspbian bullseye Release' does not have a Release file

### ISSUE THREAD

**Issue by pflugj** [influxdata/telegraf#10317]
### Relevent telegraf.conf

```toml
N/A
```

### System info

telegraf v1.21.1 "Raspbian GNU/Linux" ¨VERSION="11 (bullseye)"

### Steps to reproduce

1. trying to install a described here:
https://docs.influxdata.com/telegraf/v1.21/introduction/installation/
2. result of the command: sudo apt-get update && sudo apt-get install telegraf
./..
E: The repository 'https://repos.influxdata.com/raspbian bullseye Release' does not have a Release file.
...

### Expected behavior

install telegraf

### Actual behavior

Did not install:
E: The repository 'https://repos.influxdata.com/raspbian bullseye Release' does not have a Release file.

**Comment by powersj** [comment]
Hi,

Please use `debian` instead of `raspbian`. We do not keep up with all the various distros and all their releases in our repo, since Raspbian is essentially Debian you can safely swap between those two for our repo.

Thanks!

**Comment by pflugj** [comment]
Thanks but there is only a description for Ubuntu & Debian  nothing for raspbian
This is what I tried: 
wget -qO- https://repos.influxdata.com/influxdb.key | sudo tee /etc/apt/trusted.gpg.d/influxdb.asc >/dev/null
source /etc/os-release
echo "deb https://repos.influxdata.com/${ID} ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo apt-get update && sudo apt-get install telegraf

... and then the message appears:
The repository 'https://repos.influxdata.com/raspbian bullseye Release' does not have a Release file
Any other suggestions?

**Comment by powersj** [comment]
You did not try using debian... you need to update `/etc/apt/sources.list.d/influxdb.list` to use `debian` instead of `raspbian`

Note the debian below will take the place where raspbian currently is:

```s
sudo rm /etc/apt/sources.list.d/influxdb.list
source /etc/os-release
echo "deb https://repos.influxdata.com/debian ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo apt-get update && sudo apt-get install telegraf
```

**Comment by pflugj** [comment]
Oh,  of course.  .. sorry... I see now.
Ran the above commands and everything installed as predicted ;-)
Thanks so much for your help!!
