### ISSUE TITLE
Upgrade aerospike go client to v5/v4

### ISSUE THREAD

**Issue by aratik711** [influxdata/telegraf#10315]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Upgrade the AS go client to v5/v4 (which has quite a few improvements and bug fixes)
https://github.com/aerospike/aerospike-client-go/releases
### Current behavior:
The current AS go client used in telegraf is v1.27.0
### Desired behavior:
Update to the latest stable client, add feature to enable latency related metrics.
### Use case: 
This upgrade will fix support of tlsName for aerospike, also reconsider removal of SSL support.
It will also add support for client connection metrics (https://pkg.go.dev/github.com/aerospike/aerospike-client-go#Client.Stats)
Also support for Cluster.Healthy()
Also add support for Latency related histogram metrics.
I'd be happy to discuss this further and submit a PR for the same.

**Comment by sspaink** [comment]
@aratik711 thank you for making this issue, I don't see any problem with upgrading the aerospike client. If you would like to submit a PR it would be appreciated!

**Comment by aratik711** [comment]
Will do, sometime this week or next

**Comment by aratik711** [comment]
@sspaink can you please review the PR?
