### ISSUE TITLE
inputs.win_perf_counters  - does not work correctly on XP - returns zeros

### ISSUE THREAD

**Issue by myontop** [influxdata/telegraf#1033]
Following configuration does not work correctly on windows XP. 

```

[[inputs.win_perf_counters]]
  PreVistaSupport = true
  PrintValid = true
  [[inputs.win_perf_counters.object]]
     ObjectName = "Memory"
     Counters = ["Committed Bytes", "Commit Limit"]
     Instances = ["------"] 
     Measurement = "win_mem"
```

The fault is that it always returns 0 (zero)
Memory Committed\ Bytes=**0** 

```
2016/04/15 07:56:40 Wrote 3 metrics to output influxdb in 15.625ms
> win_mem,host=aa-351,objectname=Memory Committed\ Bytes=0 14606998100000
00000
> win_mem,host=aa-351,objectname=Memory Commit\ Limit=0 14606998100000000
```

It works nice on Win7 (with or without PreVistaSupport )

**Comment by myontop** [comment]
I have the same problem

**Comment by sparrc** [comment]
Windows XP was released almost 15 years ago, it isn't even supported by Microsoft anymore, we won't be supporting it for telegraf

**Comment by myontop** [comment]
So I am wondering why you added PreVistaSupport flag :)
Anyway, I have fixed this bug on my side.

BTW, you have created nice tool.

**Comment by sparrc** [comment]
I didn't add that flag, TBH I shouldn't have merged it, but can you explain how you fixed the bug please?

**Comment by myontop** [comment]
It was an alignment in struct in pdh.go out of telegraf I guess
It was necessary to add 4bytes padding  into structure to make it running 


type PDH_FMT_COUNTERVALUE_DOUBLE struct {
	CStatus     uint32
//add padding [4]bytes here
	DoubleValue float64
}

**Comment by myontop** [comment]
Regarding XP,  that is true this OS is old. 
My motivation is to find one solution which will be working on all systems we are using: XP ,   win7, Linux on x86,  Linux on arm -  a lot of nodes in total
