### ISSUE TITLE
ARM Docker container images based on Alpine

### ISSUE THREAD

**Issue by dschemp** [influxdata/telegraf#10338]
### Proposal:

Add support for ARMv7 / ARMv8 (arm64) Alpine Docker images just like the non-Alpine / "normal" images.

### Current behavior:

There exists no such images.

### Desired behavior:

Parallel Alpine Docker images for ARMv7 / ARMv8 (arm64)

### Use case: 

Lightweight containers on ARM servers like Raspberry Pi's.

**Comment by reimda** [comment]
Making the changes hasn't been prioritized yet, but ARM docker images would be beneficial to many users. @dschemp are you able to help make the necessary changes to the docker repo? https://github.com/influxdata/influxdata-docker Thanks!

**Comment by dschemp** [comment]
I cannot make any promises but I can look into it.

**Comment by powersj** [comment]
Hi,

The arm64 alpine-based docker images were released along with Telegraf v1.25.0.

Thanks
