### ISSUE TITLE
Telegraf Agent Health Check

### ISSUE THREAD

**Issue by bmhkb4** [influxdata/telegraf#10351]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
The Telegraf agent can sometimes lose connectivity to input or output endpoint.  It fails with a log line fed to stderr, but the process stays up instead of crashing.  I propose either we kill the telegraf binary process, or add a telegraf health check endpoint to trigger a corresponding container orchestrator action, like restarting of the container/process.

### Current behavior:
An input/output connectivity failure reports to the stderr log but the process remains running.

### Desired behavior:
Expose this failure scenario in some way, either through a health check endpoint, or by crashing the process.

### Use case: 
I have my telegraf agent docker container running on Cloud Foundry and soon Kubernetes.  Both of these container orchestrators has the concept of a "liveness check", but as designed, the telegraf agent doesn't not expose this failure in a way that is noticeable by either orchestrator.  By killing the telegraf process, that would trigger a restart of the corresponding container, alternatively, if the failure was exposed via a health check endpoint, we could more appropriately respond to the actual severity of the failure through a liveness probe.

**Comment by powersj** [comment]
Hi,

I like the idea and may have some questions, however, can I get you to file this issue with where our docker files and stored in the [influxdata-docker](https://github.com/influxdata/influxdata-docker) repo?

Thanks!

**Comment by bmhkb4** [comment]
Done! https://github.com/influxdata/influxdata-docker/issues/567 

thanks
