### ISSUE TITLE
VSphere Plugin:  Enable Host_Group Attribute exported in metrics

### ISSUE THREAD

**Issue by hshelly** [influxdata/telegraf#10368]
## Feature Request

Customers are wanting to collect Host_Group Attributes to be exported in metrics collected from VSphere. 
### Proposal:
Enable this field to be included in the customer_attribute_include field list to be optionally collected for metrics.  

### Current behavior:
The VMs associated with any Host_Group are not tagged as being a member.

### Desired behavior:
Ensure the VMs are tagged with host_group attribute and have the ability to look at the system metrics usage (available and usage), the assigned/configured mem and cpu for the VMs.

### Use case: 
Customer wants to leverage this data for capacity planning to compare with what VSphere is reporting versus the reporting from the platform perspective.  Export metrics to visually observer the following:
o	total physical available mem and cpu for the host_group (aggregated for the group and detail for members of the group)
o	total assigned/configured mem and cpu for the vms running on those hosts in the group
o	total used cpu/mem for those vms, as reported by vsphere

@prydin

**Comment by reimda** [comment]
Hi @hshelly, do you still need this feature? Are you able to make the code change and contribute a PR? Thanks!
