### ISSUE TITLE
Webhook listener to listen to webhooks from Jfrog Artifactory

### ISSUE THREAD

**Issue by sammcadams-8451** [influxdata/telegraf#10376]
## Feature Request

Webhook listener to listen to webhooks from Jfrog Artifactory.

### Proposal:

Create a webhook listener similar to the Github webhook listener that collects webhooks from Jfrog Artifactory.  I have already created this in a fork, but believe that others may benefit from the feature.

### Current behavior:

Can't receive webhooks from Artifactory.  

### Desired behavior:

Receive webhooks from Artifactory

### Use case: 

Currently we are looking to collect webhooks from our various CI/CD tools.  Since we already make use of the Github webhook listener, it makes sense to include our repository (Jfrog Artifactory) as well.

**Comment by sspaink** [comment]
Hello @sammcadams-8451 this sounds like a useful extension of to the webhook input plugin, are you interested in creating a pull request? thanks!

**Comment by sammcadams-8451** [comment]
Sure i would be happy too.  I will try and get submitted soon!
