### ISSUE TITLE
http_response to support similar to curl --connect-to

### ISSUE THREAD

**Issue by hvisage** [influxdata/telegraf#10383]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

To add the option to resolve and connect to a different IP (typically localhost) and port(s) instead of the defaults like curl's --connect-to and --resolve allows

### Current behavior:

At present the name is either resolved or passed on to a http_proxy

### Desired behavior:

be able to specify where I need to connect to for a specific URL

### Use case: 

When you are on the host, behind a CDN, firewall, loadbalancer etc., you don't want to connect to the outside (hairpin connection or other CDN fun) but to a specific (typically the localhost, or the specific hosts when called from a tester node and on a specific port or ports if multiple local instances) to test without the interferences of the outside firewall/CDN/loadbalancer/etc.

For a single host (like localhost) it could be faked by adding it to /etc/hosts, but would fail when you want to use it from a tester node when testing for example dockers on various hosts

There might be questions how to do the cases where you might want multiple different hosts/ports for the same URL which I haven't considered yet, but the cases for me is not that complex yet, just a simple localhost in most cases.

**Comment by powersj** [comment]
Hi,

For the http_response plugin we use the golang [HTTP client](https://pkg.go.dev/net/http#Client). Do you know if this is even possible with that? Otherwise, I would suggest using the `exec` plugin with curl directly to get what you are after.

Thanks!

**Comment by hvisage** [comment]
As nice as golang might be, I've seen too many of these "issues" with it and limitations of the libraries when I have a valid, but "different" from the public internet needs.

just close this request with: "Golang's httpclient library can't handle this"

**Comment by powersj** [comment]
> As nice as golang might be, I've seen too many of these "issues" with it and limitations of the libraries when I have a valid, but "different" from the public internet needs.

Thanks for the fast response. I do think curl is the right tool for this request, consider using the exec plugin to combine it with telegraf.

Thanks again
