### ISSUE TITLE
sysstat input plugin

### ISSUE THREAD

**Issue by Drewster727** [influxdata/telegraf#1038]
Hey Guys,

I'm very new to telegraf -- I'm attempting to get the sysstat input plugin working.

I installed telegraf via the .deb file (0.12.0-1) and it's been working great with some of the default installed system plugins. So, I've installed sysstat on my box, and i appended the following to my config:
```
[[inputs.sysstat]]
[inputs.sysstat.options]
    -C = "cpu"
    -B = "paging"
    -b = "io"
    -d = "disk"             # requires DISK activity
    "-n ALL" = "network"
    "-P ALL" = "per_cpu"
    -q = "queue"
    -R = "mem"
    -r = "mem_util"
    -S = "swap_util"
    -u = "cpu_util"
    -v = "inode"
    -W = "swap"
    -w = "task"
```

I went to test with this command:
```telegraf -config telegraf.conf -test```

It tells me the following:
```Error parsing telegraf.conf, Undefined but requested input: sysstat```

What am I missing?

Ubuntu Server 15.10, telegraf 0.12.0-1, influxdb

**Comment by sparrc** [comment]
sysstat plugin was not in 0.12.0, you'll need to wait for the next release, see the changelog
