### ISSUE TITLE
telegraf stops with panic runtime error while using statsd

### ISSUE THREAD

**Issue by pyhas** [influxdata/telegraf#10397]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "192.168.1.1:161" ]
  version = 2
  community = "public"
  name = "snmp"

[[inputs.snmp.field]]
   name = "hostname"
   oid = "RFC1213-MIB::sysName.0"
   is_tag = true
   [[inputs.snmp.table.field]]
     name = "ifName"
     oid = "IF-MIB::ifName"
     is_tag = true
```

### Logs from Telegraf

root@telegraf:/etc/grafana$ telegraf --config telegraf.conf --test
2022-01-07T02:06:50Z I! Starting Telegraf 1.21.2
2022-01-07T02:06:50Z I! Loaded inputs: kernel mem processes snmp statsd swap system
2022-01-07T02:06:50Z I! Loaded aggregators: 
2022-01-07T02:06:50Z I! Loaded processors: 
2022-01-07T02:06:50Z W! Outputs are not used in testing mode!
2022-01-07T02:06:50Z I! Tags enabled: host=grafana
Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .
2022-01-07T02:06:50Z W! [inputs.snmp] module miblist.txt could not be loaded
Parse module: /var/lib/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
2022-01-07T02:06:52Z W! [inputs.snmp] module DPI20-MIB could not be loaded
Parse module: /var/lib/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
2022-01-07T02:06:53Z W! [inputs.snmp] module HPR-MIB could not be loaded
Parse module: /var/lib/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
2022-01-07T02:06:56Z W! [inputs.snmp] module SNMPv2-PDU could not be loaded
Parse module: /var/lib/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
2022-01-07T02:06:56Z W! [inputs.snmp] module TCPIPX-MIB could not be loaded
2022-01-07T02:06:57Z E! [agent] Starting input inputs.statsd: listen udp :8125: bind: address already in use

> snmp,agent_host=192.168.1.1,host=grafana,hostname=router,ifName=Gi0/0/3 ifAlias="FREE",ifConnectorPresent=2i,ifCounterDiscontinuityTime=2940i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=0i,ifHCInUcastPkts=0i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=0i,ifHCOutUcastPkts=0i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifLinkUpDownTrapEnable=1i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1641521218000000000
2022-01-07T02:06:58Z I! [inputs.statsd] Stopping the statsd service
> snmp,agent_host=192.168.1.1,host=grafana,hostname=router,ifName=Po10.2004 ifAlias="Connected-to-IGW2-PO-10.2004",ifConnectorPresent=2i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=1i,ifHCInMulticastPkts=0i,ifHCInOctets=2424388535604i,ifHCInUcastPkts=8184592896i,ifHCOutBroadcastPkts=3i,ifHCOutMulticastPkts=0i,ifHCOutOctets=9574480799123i,ifHCOutUcastPkts=10379010397i,ifHighSpeed=20000i,ifInBroadcastPkts=1i,ifInMulticastPkts=0i,ifLinkUpDownTrapEnable=2i,ifOutBroadcastPkts=3i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1641521218000000000
> snmp,agent_host=192.168.1.1,host=grafana,hostname=router,ifName=Po30 ifAlias="To-KIR_S9306-01_Eth-Trunk-30_GGC-TRAFFIC",ifConnectorPresent=2i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=240i,ifHCInUcastPkts=4i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=0i,ifHCOutUcastPkts=0i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifLinkUpDownTrapEnable=1i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1641521218000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ca98dd]

goroutine 29 [running]:
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).Stop(0xc000991d40)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/statsd/statsd.go:1010 +0x15d
github.com/influxdata/telegraf/agent.stopServiceInputs({0xc00280f840, 0x7, 0x0})
	/go/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x67
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs(0xc000110350, {0x5863728, 0xc0002d2e40}, 0x0, 0xc0009c8d80)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:413 +0x248
github.com/influxdata/telegraf/agent.(*Agent).test.func4()
	/go/src/github.com/influxdata/telegraf/agent/agent.go:943 +0x6c
created by github.com/influxdata/telegraf/agent.(*Agent).test
	/go/src/github.com/influxdata/telegraf/agent/agent.go:941 +0x671
system@grafana:/etc/telegraf$ nano new-snmp-tele.conf 

### System info

Telegraf 1.21.2, Ubuntu 20.04

### Steps to reproduce

1. add the same config provided 
2. run the config in test mode

...

### Expected behavior

telegraf should collect the data without any error

### Actual behavior

telegraf stops after collecting some data with runtime error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ca98dd]

**Comment by MyaLongmire** [comment]
@pyhas I see a few problems here.
1. I cannot run your config without a toml error as `[inputs.snmp.table.field]` needs `[inputs.snmp.table]` section before it.
2. Telegraf is showing an error 

> 2022-01-07T02:06:57Z E! [agent] Starting input inputs.statsd: listen udp :8125: bind: address already in use

this error is about statsd which leads me to my last point
3. You are not panicking on snmp but on statsd. 

> github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).Stop(0xc000991d40)

Can you please post the statsd portion of your config?

**Comment by MyaLongmire** [comment]
This is failing because `listen udp :8125: bind: address already in use` and we have not gotten a response so I am going to close this.

**Comment by Bken22** [comment]
no solution yet ?
