### ISSUE TITLE
Windows Service fails to start

### ISSUE THREAD

**Issue by Timboooh** [influxdata/telegraf#10409]
Hello,
I'm currently running into an issue where Telegraf refuses to start as a service. It does work when I'm starting the program manually from the terminal.

I'm currently running Telegraf 1.21.2 on Windows Server 2019 v1809

When I try to install the service using [this guide](https://docs.influxdata.com/telegraf/v1.21/administration/windows_service/) I get stuck at the last step. (The tests ran successfully.) 
After I run `.\telegraf.exe --service start` from an elevated powershell session. I don't get any console output, and no log file is created.

I've also tried creating the service manually using NSSM. Using Nssm I reroute stdout to a file. This file just stays empty, so no output is created and telegraf just closes silently.

**Comment by Timboooh** [comment]
If I want to start it manually I use: `.\telegraf.exe --config "C:\Program Files\InfluxData\Telegraf\telegraf.conf" --config-directory "C:\Program Files\InfluxData\Telegraf\configs"` (which runs telegraf as expected)

I installed the service using: `.\telegraf.exe --service install --config "C:\Program Files\InfluxData\Telegraf\telegraf.conf" --config-directory "C:\Program Files\InfluxData\Telegraf\configs"`
And then tried to start it using: `.\telegraf.exe --service start`


The folder structure of `C:\Program Files\InfluxData\Telegraf` looks like this:

- configs (folder with my config files, one for every statistic I want to monitor)
- queries (folder with .sql files used in some of my configs)
- log.txt
- telegraf.conf (common config for the agent)
- telegraf.exe (version 1.21.2)

I have tried running Telegraf without the `--config-directory` argument. I copied the contents of one of my config-files in `config` to telegraf.conf. This doesn't make a difference, Telegraf works when started with the manual command, and not when started using any kind of service.

**Comment by powersj** [comment]
Here is my attempt:

```powershell
PS C:\users\powersj\downloads> .\telegraf.exe --config 'C:\Program Files\InfluxData\Telegraf\telegraf.conf' --config-directory 'C:\Program Files\InfluxData\Telegraf\configs'
2022-01-10T18:43:30Z I! Starting Telegraf 1.21.2
2022-01-10T18:43:30Z I! Loaded inputs: mem
2022-01-10T18:43:30Z I! Loaded aggregators:
2022-01-10T18:43:30Z I! Loaded processors:
2022-01-10T18:43:30Z I! Loaded outputs: file
2022-01-10T18:43:30Z I! Tags enabled: host=DESKTOP-6BC121I
2022-01-10T18:43:30Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"DESKTOP-6BC121I", Flush Interval:10s
mem,host=DESKTOP-6BC121I available=5875118080i,used=2714271744i,used_percent=31.60028592969353,available_percent=68.39971407030647,total=8589389824i 1641840220000000000
2022-01-10T18:43:45Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-01-10T18:43:45Z I! [agent] Stopping running outputs
PS C:\users\powersj\downloads> .\telegraf.exe --service install --config 'C:\Program Files\InfluxData\Telegraf\telegraf.conf' --config-directory 'C:\Program Files\InfluxData\Telegraf\configs\'
PS C:\users\powersj\downloads> Get-Service telegraf

Status   Name               DisplayName
------   ----               -----------
Stopped  telegraf           Telegraf Data Collector Service


PS C:\users\powersj\downloads> .\telegraf.exe --service start
PS C:\users\powersj\downloads> Get-Service telegraf

Status   Name               DisplayName
------   ----               -----------
Running  telegraf           Telegraf Data Collector Service

```

Could you try simplifying your config at first to ensure something with the paths is not getting garbled?

**Comment by Timboooh** [comment]
Sorry for the delay.
I tried it again with a simpler configfile. Still the same results. Here are the steps I followed to recreate this:

- Open powershell as admin
- Create folder: `mkdir "C:\Program Files\InfluxData\Telegraf"`
- Move to folder: `cd "C:\Program Files\InfluxData\Telegraf"`
- Download telegraf 1.21.2: `wget https://dl.influxdata.com/telegraf/releases/telegraf-1.21.2_windows_amd64.zip -UseBasicParsing -OutFile telegraf-1.21.2_windows_amd64.zip`
- Extract the archive: `Expand-Archive .\telegraf-1.21.2_windows_amd64.zip -DestinationPath 'C:\Program Files\InfluxData\telegraf'`
- Move telegraf.exe and telegraf.conf one folder up: `mv .\telegraf-1.21.2\* .\`
- Replace telegraf.conf with the following: 
```toml
# Telegraf Configuration

[agent]
  
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "s"

  debug = true
  quiet = false

  logtarget = "file"
  logfile = 'C:\Program Files\InfluxData\Telegraf\log.txt'

  hostname = ""
  omit_hostname = false

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = false
  
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", 'C:\Program Files\InfluxData\Telegraf\metrics.out']
  data_format = "influx"
```
- Test configuration using: `.\telegraf.exe --config .\telegraf.conf` (This runs as expected)
- Install the service using: `.\telegraf.exe --service install --config .\telegraf.conf`
- Check if the service exists: `Get-Service telegraf`
```
Status   Name               DisplayName
------   ----               -----------
Stopped  telegraf           Telegraf Data Collector Service
```
- Start the service using: `.\telegraf.exe --service start`
After a short delay with no output
- I check the status again: `Get-Service telegraf`
- And I get the same result:
```
Status   Name               DisplayName
------   ----               -----------
Stopped  telegraf           Telegraf Data Collector Service
```
No log.txt or metrics.out file is created.
