### ISSUE TITLE
outputs.influxdb configurable datapoint age 

### ISSUE THREAD

**Issue by alexdesmet** [influxdata/telegraf#10410]
## Feature Request

Add a configurable period (in days for example) to drop older measurements being sent to InfluxDB. This will prevent sending datapoints to InfluxDB which are beyond the configured retention time.

### Proposal:

A parameter max_datapoint_age that checks if a datapoint is allowed to be sent to InfluxDB

### Current behavior:

All measurements are being sent to InfluxDB. When inserting a datapoint into InfluxDB with a timestamp that is older than the retention period, InfluxDB  returns an error stating:

Error writing to outputs.influxdb_v2: 500 Internal Server Error: internal error: unexpected error writing points to database: partial write: points beyond retention policy dropped=120

After a while, the connection to InfluxDB is dropped and no new measurements are sent to InfluxDB. Manually restarting telegraf is needed to restore the connection.

### Desired behavior:

If a datapoint is received that exceeds the max_datapoint_age, it is dropped and not sent to InfluxDB. This prevents unnecessary inserts and overloading the database with datapoints that don't need to be stored.

### Use case: 

We use telegraf as a way of inserting datapoints into InfluxDB for several devices (several hundred devices currently). When a client device is offline for an extended period and the connection is restored, it sends all locally cached datapoints. These are now beyond the retention period of InfluxDB (30 days in our case) which causes the behavior above. The direct consequence is that data stops flowing into InfluxDB for all connected clients because the connection is dropped.

**Comment by reimda** [comment]
What version of influxdb are you using? Did you install on-premises or are you using the cloud service?

It sounds like this feature might be difficult to get right. If we add a max_datapoint_age and the user sets the same age as the influxdb instance, clock drift in one direction between telegraf and influxdb would mean telegraf could think the metric hasn't expired but influxdb would think it had. The user could set the max_datapoint_age to be shorter than influxdb's policy but then data is dropped early. Maybe that's more acceptable than influxdb dropping the connection.

I think it would be possible with a starlark processor to check the date and drop the metric if it's older than a threshold.

It would be best if we could find a way to have influxdb tell telegraf what the oldest allowed timestamp is and have telegraf drop the metric if it's older. This would avoid the clock drift problem.

**Comment by alexdesmet** [comment]
Thanks for the response!

We are using a mix of InfluxDB versions 2.0.3 to 2.1.1 self hosted Compute Instances on GCP and the Cloud Service. One DB per environment/customer.

I can see the difficulty in dealing with the time issue, but for us the bad outweighs the good. This week we had another outage due to this behavior and would much rather loose a couple of old datapoints then a dropped connection. Retrieving the oldest allowed timestamp from InfluxDB could work, but then we would have to take the timezone into account which could also be prone to config errors. 

Thanks for pointing me to the starlark processor, I will try and set something up and see how it behaves.

**Comment by powersj** [comment]
Because the range of a user's retention period is a known value, user's can use a method via metricpass to ensure only metrics new enough are passed:

```toml
metricpass = "time >= now() - duration('20m')"
```

This way only metrics older than 20 minutes ago are passed through.
