### ISSUE TITLE
SNMP plugin doesn't write proper instance value

### ISSUE THREAD

**Issue by slemire** [influxdata/telegraf#1043]
I'm having issues polling the virtual server stats off an F5 load-balancer. It seems like the snmp plugin doesn't write the proper value in the instance field. In the example below, it's not writing two levels of OIDs below what I've defined in the configuration. That throws off the mapping table when I try to use it. In the example I'm not using the mapping table but you can see the data written in InfluxDB is missing two OID levels above .47.

```
[[inputs.snmp.table]]
        name = "ltmVirtualServStatEntry"
        oid = ".1.3.6.1.4.1.3375.2.2.10.2.3.1"
```

Database measurements:

```
> select * from ltmVirtualServStatClientBytesIn where time > now() - 1m
name: ltmVirtualServStatClientBytesIn
-------------------------------------
time                    dc      host            instance                                                        ltmVirtualServStatClientBytesIn
1460818130000000000     Home    172.23.10.30    47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49      0
1460818130000000000     Home    172.23.10.30    47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51      0
1460818130000000000     Home    172.23.10.30    47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50      0
1460818140000000000     Home    172.23.10.30    47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51      0
```

Here's the snmpwalk of the OID:
```
slemire@dev:~/telegraf$ snmpwalk -v 2c -c <secret> 172.23.10.30 .1.3.6.1.4.1.3375.2.2.10.2.3.1
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.1.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49 = STRING: "/Common/test_vs1"
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.1.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50 = STRING: "/Common/test_vs2"
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.1.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51 = STRING: "/Common/test_vs3"
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.2.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.2.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.2.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.3.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.3.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.3.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.4.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.4.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.4.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.5.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.49 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.5.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.50 = Counter64: 0
SNMPv2-SMI::enterprises.3375.2.2.10.2.3.1.5.16.47.67.111.109.109.111.110.47.116.101.115.116.95.118.115.51 = Counter64: 0
[...]
```

**Comment by slemire** [comment]
Added pcap file
[snmptable1.pcap.zip](https://github.com/influxdata/telegraf/files/222256/snmptable1.pcap.zip)

**Comment by sparrc** [comment]
Maybe I'm not quite reading this right, what are the 2 OID levels that are missing?

**Comment by slemire** [comment]
.1.16 is missing

**Comment by sparrc** [comment]
got it, I see what you mean, @titilambert do you happen to know why those two elements of the instance wouldn't be included?

**Comment by titilambert** [comment]
hum, I did never hit this bug :(
@slemire The best thing to do, if you can do it, is to make a snmp dump using snmpsim: http://snmpsim.sourceforge.net/
Can you do that ?

**Comment by titilambert** [comment]
This could be fix with https://github.com/influxdata/telegraf/pull/1044

**Comment by slemire** [comment]
Sure thing, I captured the following:

snmprec.py --agent-udpv4-endpoint=172.23.10.30 --protocol-version=2c
[test.snmprec.txt](https://github.com/influxdata/telegraf/files/222635/test.snmprec.txt)

 --start-oid=.1.3.6.1.4.1.3375.2.2.10.2.3.1 --stop-oid=.1.3.6.1.4.1.3375.2.2.10.2.3.1.44 --output-file=test.snmprec

**Comment by titilambert** [comment]
@slemire thanks ! Could you give me your telegraf configuration ?

**Comment by slemire** [comment]
Here's the config

**Comment by slemire** [comment]
Problem is still there using the latest nightly:
Telegraf - Version 0.13.0~n1461140359

**Comment by slemire** [comment]
I think maxRepetition := uint8(32) might have something to do with it.

My OID tree is longer than that.

**Comment by sparrc** [comment]
I see, I think that has come up before, we may want to make that a configurable option. What do you think @titilambert?

**Comment by slemire** [comment]
Um, I think I got confused. The maxRepetition is just the standard SNMP RFC knob to manage the size of SNMP bulk GETs. I've tried smaller and larger settings without success.
