### ISSUE TITLE
Problem to switch from data_format = "json" to "json_v2"

### ISSUE THREAD

**Issue by andrejgorin** [influxdata/telegraf#10443]
Hello!

I'm trying to switch my telegraf configuration **data_format** from "json" to "json_v2". After switching, telegraf just doesn't send any data to output. My configuration is pretty simple, so I'm wondering, where could be a pickle here?

Telegraf version 1.21.1
Example of json data on input `{"humidity":61,"temperature":-15,"did":"AC:67:B2:34:53:5C"}`
What my telegram config part for input looks like:

[agent]
  interval = "20s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  [[outputs.influxdb_v2]]
  urls = ["https://eu-central-1-1.aws.cloud2.influxdata.com"]
  token = "token"
  organization = "mail@gmail.com"
  bucket = "bucket"
  [[inputs.mqtt_consumer]]
  servers = ["ssl://url.s1.eu.hivemq.cloud:8883"]
  topics = ["esp32/pub"]
  topic_tag = ""
  client_id = "User"
  username = "User"
  password = "Pass"
  insecure_skip_verify = true
  data_format = "json"

Telegraf capture with data_format = "json":
`
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex temperature=-12,humidity=67 1642143414140190288
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=63,temperature=-15 1642143415144177293
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=69,temperature=-19 1642143416158730209
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=65,temperature=-20 1642143417159051679
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex temperature=-15,humidity=63 1642143418168529281
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=61,temperature=-20 1642143419172993502
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=61,temperature=-18 1642143420177276965
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=66,temperature=-11 1642143421181740346
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=65,temperature=-15 1642143422199073631
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=66,temperature=-17 1642143423189765754
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=66,temperature=-19 1642143424204542789
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=69,temperature=-20 1642143425208432179
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=67,temperature=-15 1642143426212695791
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=67,temperature=-18 1642143427226305088
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex temperature=-14,humidity=68 1642143428231976075
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=62,temperature=-13 1642143429245326373
mqtt_consumer,did=AC:67:B2:34:53:5C,host=plex humidity=62,temperature=-19 1642143430239292836
`
Can't provide capture with data_format = "json_v2" as it's just empty.

Any help would be very appreciated!

**Comment by powersj** [comment]
Hi,

Take a look at the [json_v2 readme](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2) for some steps on getting started with it. It is a bit more involved with the setup, but much more customizable. 

Using your example JSON above, I used a config like this to get the same data:

```toml
[[inputs.file]]
files = ["data.json"]
data_format = "json_v2"
[[inputs.file.json_v2]]
  [[inputs.file.json_v2.field]]
    path = "humidity"
    type = "int"
  [[inputs.file.json_v2.field]]
    path = "temperature"
    type = "int"
```

I am going to close this as this is more of a support question which is great for our forums or slack channel. But hopefully, that gets you started!

Thanks!

**Comment by andrejgorin** [comment]
Hello,

Thanks for your response! I thought fields should not be explicitly described as both are type of int in input json. Apparently I was wrong. After I described them all started to work.

Have a great day!
