### ISSUE TITLE
Support new /metrics URL in inputs.influxdb

### ISSUE THREAD

**Issue by adoom42** [influxdata/telegraf#10459]
The docs for the influxdb input plugin refer to the `http://localhost:8086/debug/vars` URL: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb

That works fine for InfluxDB 1.x and 2.0.  In 2.1, the `/debug/vars` URL was removed.  You are instructed to use `/metrics` instead: https://docs.influxdata.com/influxdb/v2.1/reference/release-notes/influxdb/#debugvars-removed

`/debug/vars` returns data in JSON format, while `/metrics` returns data in what appears to be a space-delimited key/value format where the key may contain JSON-like elements.  The output also contains comments.

Partial example:
```
$ curl http://localhost:8086/metrics
# HELP boltdb_reads_total Total number of boltdb reads
# TYPE boltdb_reads_total counter
boltdb_reads_total 1105
# HELP boltdb_writes_total Total number of boltdb writes
# TYPE boltdb_writes_total counter
boltdb_writes_total 12
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 7.1365e-05
go_gc_duration_seconds{quantile="0.25"} 0.000206513
go_gc_duration_seconds{quantile="0.5"} 0.00025049
go_gc_duration_seconds{quantile="0.75"} 0.000307708
go_gc_duration_seconds{quantile="1"} 0.007908952
```

Telegraf reports this error in the log:
```
2022-01-18T21:40:03Z E! [inputs.influxdb]: Error in plugin: [url=http://localhost:8086/debug/vars]: document root must be a JSON object
```

That makes sense because when you curl it manually, it returns a 404.
```
$ curl http://localhost:8086/debug/vars
404 page not found
```

Please update the inputs.influxdb plugin to support gathering InfluxDB metrics from the new `/metrics` endpoint (or create a new plugin such as `inputs.influxdb_v2` which does so).

Alternatively, if I'm missing something and users are expected to gather InfluxDB metrics in a totally different way, please update the README.md file for the inputs.influxdb plugin to point people in the right direction.

**Comment by powersj** [comment]
ack on the request and it is in our queue
