### ISSUE TITLE
dns_query input plugin - Pull FQDN IPs when querying

### ISSUE THREAD

**Issue by G0nz0uk** [influxdata/telegraf#10452]
### Proposal
Pull FQDN IPs when querying, FAO @srebhan 

### Current behavior
Doesn't do this :)

### Desired behavior
When you query a FQDN it currently pulls all the nice info through which is great, but it would be nice to show what IP address(es) the lookup found as well like an nslookup.

### Use case
The idea is to them push all this into Grafana.

Thanks

**Comment by sspaink** [comment]
This seems like a good addition to the dns_query plugin, @G0nz0uk would you be interested in trying to implement this feature?

**Comment by srebhan** [comment]
@sspaink I agreed to implement this once I find some time... But I'll be happy if someone beats me at it.

**Comment by srebhan** [comment]
@G0nz0uk to clarify the request, what do you expect if a query returns multiple IP addresses for a FQDN? For example a query for `bbc.co.uk` on `8.8.8.8` would return
```shell
> nslookup bbc.co.uk 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   bbc.co.uk
Address: 151.101.0.81
Name:   bbc.co.uk
Address: 151.101.64.81
Name:   bbc.co.uk
Address: 151.101.128.81
Name:   bbc.co.uk
Address: 151.101.192.81
Name:   bbc.co.uk
Address: 2a04:4e42::81
Name:   bbc.co.uk
Address: 2a04:4e42:200::81
Name:   bbc.co.uk
Address: 2a04:4e42:400::81
Name:   bbc.co.uk
Address: 2a04:4e42:600::81
```

I assume you only want the first IPv4 and IPv6? The fields would be named `ipv4` and `ipv6` then and be of type `string`. Would that work for you?

**Comment by G0nz0uk** [comment]
Hello!  I'd be looking for all the IP's in their cluster returned:



Address: 151.101.0.81
Address: 151.101.64.81
Address: 151.101.128.81
Address: 151.101.192.81

Address: 2a04:4e42::81
Address: 2a04:4e42:200::81
Address: 2a04:4e42:400::81
Address: 2a04:4e42:600::81

**Comment by srebhan** [comment]
Hmmm, as the length is dynamically, how do you expect the information to be represented? As a list of fields (e.g. `ip_0`, ip_1` ... `ip_N`)?  I'm asking about the representation as the number of returned IP addresses might vary and thus you will run into cardinality issues... Also the order is not guaranteed I think.

Furthermore, you can (with the current implementation) only get either `A` **or** `AAAA` records, so you either see IPv4 or IPv6 addresses.

**Comment by aliex-13** [comment]
Hey Guys,

Just looking into the current implementation and it doesn't look like the actual A record value is returned from what I can see...

@srebhan - Based on your comment above, any ideas where this can be found?

Thanks!

**Comment by aliex-13** [comment]
Hey @srebhan - A single IP address being returned will work for me and what I am trying to achieve. 

Based on previous comments, this might be achieved in your PR... Any chance you can put one up?

Thanks!

**Comment by srebhan** [comment]
@aliex-13 please test the binary build in #12519 once CI finished. You need to set `include_fields = ["IP"]` or `include_fields = ["all IPs"]` to enable IP reporting. Let  me know if this helps!
