### ISSUE TITLE
Add smoke tests to verify packaged artifacts

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#10467]
General Process follow this https://github.com/influxdata/telegraf#package-repository:
1. Test repo during release
   * Make sure the release was a success
2. Test packages nightly
   * Make sure there hasn't been any major breaking changes (panics at startup) introduced

This could help avoid potential app breaking changes getting released by testing nightly (e.g. https://github.com/influxdata/telegraf/pull/10296) and also make sure if we change anything to the packaging that things will stay the same.

**Comment by powersj** [comment]
ack - have test scripts for individual RPM/DEB, which satisfy #1, but need to work on nightly.
