### ISSUE TITLE
Outputs. HTTP plug-in error: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by dogfei** [influxdata/telegraf#10469]
my configure is:
```
[agent]
  interval = "10s"
  round_interval = true
  collection_jitter = "1s"
  omit_hostname = true
  
[[outputs.http]]
  url = "http://auto-inspection.tools-system:8000/telegraf"
  timeout = "10s"
  method = "POST"
  data_format = "json"
  json_timestamp_units = "1s"
  [outputs.http.headers]
    Content-Type = "application/json"
    Accept = "application/json"
  
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  [inputs.disk.tagdrop]
    path = ["/etc/telegraf", "/dev/termination-log", "/etc/hostname", "/etc/hosts", "/etc/resolv.conf"]

[[inputs.net]]
  ignore_protocol_stats = true
  interfaces = ["eth*", "bond*", "em*"]
  fielddrop = ["packets_sent", "packets_recv"]
```

I am running in the Kubernetes cluster as daemonset with the following error message

> 2022-01-20T08:39:29Z E! [agent] Error writing to outputs.http: Post "http://auto-inspection.tools-system:8000/telegraf": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

pls,  pls, pls, Look at this problem for me

**Comment by powersj** [comment]
> Client.Timeout exceeded while awaiting headers

This means that there is some sort of connection delay between telegraf and your HTTP target. This could be due to a slow DNS lookup, the telegraf or remote server being overloaded, a busy networking slowing things down, etc. You will want to further increase your timeout setting for the output HTTP plugin.
