### ISSUE TITLE
Add Bounty Source support

### ISSUE THREAD

**Issue by titilambert** [influxdata/telegraf#1046]
Hello 

As I'm currently missing spare time to fix/enhance SNMP plugin (at least 8 opened issues/PRs), it will be cool to be able to use Bounty Source. 
Could you enable Bounty Source on Telegraf github repo ( https://www.bountysource.com/ ) ?

Thanks !

**Comment by sparrc** [comment]
@titilambert can you explain what exactly you want to do with that? post paid bounties for people to implement snmp features?

**Comment by titilambert** [comment]
@sparrc I would to be able to take some days of unpaid leave to be able to complete this work.

**Comment by sparrc** [comment]
I don't think we'll be setting up bountysource for the team anytime soon, and it looks like bounties can be made without our involvement so I'm going to close out the issue
