### ISSUE TITLE
Collecting the mongodb cluster is abnormal

### ISSUE THREAD

**Issue by zhmingyong** [influxdata/telegraf#10461]
### Relevent telegraf.conf

```toml
[[inputs.mongodb]]
   servers = ["mongodb://a_tc_zdhyw_test:shardingTest20211230@172.23.3.61:27010"]
```

### Logs from Telegraf

telegraf  | 2022-01-19T07:33:22Z E! [telegraf] Error running agent: could not initialize input inputs.mongodb: unable to connect to MongoDB: server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: 172.23.3.61:27010, Type: Unknown }, ] }

### System info

Telegraf 1.20.4, CentOS7 2009, Docker version 19.03.15, build 99e3ed8, MongoDB 4.4.4

### Docker

Docker version 19.03.15, build 99e3ed8

### Steps to reproduce

1.Add a dedicated conf for MongoDB like the one above (to simulate a failed conn, just change the port number, for example)
2.Restart Telegraf “docker-compose down && docker-compose up”

### Expected behavior

At least a log message to STDERR, on init, about a failing conn to a MongoDB server (with no retry mechanism)

### Actual behavior

telegraf  | 2022-01-19T07:33:22Z E! [telegraf] Error running agent: could not initialize input inputs.mongodb: unable to connect to MongoDB: server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: 172.23.3.61:27010, Type: Unknown }, ] }

**Comment by powersj** [comment]
I believe this is a dup of https://github.com/influxdata/telegraf/issues/10078, if not please feel free to provide more details as to what you are after.

Thanks!
