### ISSUE TITLE
Add stats about certificate to http_response plugin.

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/telegraf#1047]
The [http_response](https://github.com/influxdata/telegraf/blob/1bf904fe60c96b39b3f39fad467f35b59b982600/plugins/inputs/http_response/README.md) plugin can be used for testing HTTP(S) connections. In case of HTTPS requests it would be useful to save experation date of certificate.

**Comment by sparrc** [comment]
@OrangeTux this sounds good, do you know how to get this from the http response object? https://golang.org/pkg/net/http/#Response

**Comment by OrangeTux** [comment]
@sparrc I think the experiation date can be obtained from TLS attribute of a response object. This is a pointer to a [ConnectionState](https://golang.org/pkg/crypto/tls/#ConnectionState) object which in turn has references to [Certificate](https://golang.org/pkg/crypto/x509/#Certificate) objects which have a NotAfter attribute.

**Comment by reimda** [comment]
The x509_cert can check certs of HTTPS and it produces metrics with fields like expiry, age, startdate, enddate. I think it should do what you're looking for now.
