### ISSUE TITLE
Use nfpm instead of fpm for packaging

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#10475]
nfpm: https://github.com/goreleaser/nfpm

`a simpler, 0-dependency, as-little-assumptions-as-possible alternative to fpm` at the moment we are using fpm which requires ruby if you want to run `make package`. This should make packaging easier.

Moving to nfpm will require us to update the makefile and the ci docker image (https://github.com/influxdata/telegraf/blob/master/scripts/ci-1.17.docker).

**Comment by powersj** [comment]
@sspaink do you still want to do this? Or do you think if we migrate to native packaging that we can skip over this?

**Comment by sspaink** [comment]
I think not doing this would be fine, there isn't a big benefit gain to it. Closing.
