### ISSUE TITLE
Migrate remaining parsers to new structure introduced in #8791

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#10482]
This pull request introduced an improved way to register parsers: https://github.com/influxdata/telegraf/pull/8791

We need to migrate all parsers to use this new structure so we can get rid of the old compatibility code.

- [ ] collectd: https://github.com/influxdata/telegraf/issues/11353
- [ ] dropwizard
- [ ] from_urlencoded
- [ ] graphite
- [ ] grok
- [ ] influx
- [ ] influx_upstream
- [ ] logfmt
- [ ] nagios
- [ ] prometheus
- [ ] prometheusremotewrite
- [ ] value
- [ ] wavefront

**Comment by powersj** [comment]
@sspaink I think we said we were going to open a new bug for each parse in the team call this week? Should those replace this issue? Thanks!

**Comment by sspaink** [comment]
TODO:

- collectd
- dropwizard
- from_urlencoded
- graphite
- grok
- influx
- logfmt
- nagios
- prometheus
- prometheusremotewrite
- value
- wavefront

DONE:

- [csv](https://github.com/influxdata/telegraf/pull/8791)
- [json](https://github.com/influxdata/telegraf/pull/11226)
- [json_v2](https://github.com/influxdata/telegraf/pull/11343)
- [xpath](https://github.com/influxdata/telegraf/pull/11218)

**Comment by sspaink** [comment]
Closing in favor of individual issues.
