### ISSUE TITLE
Feature request - procstat custom tag for each process

### ISSUE THREAD

**Issue by whetherharder** [influxdata/telegraf#1048]
I think it would be quite useful to have a custom tag for each process.
Now we have a possibility to store each process data in separate field using tags. But it is quite difficult to agregate several processes data in one dataset if your processes are changing.

Of course, we can use pid or process name.
But it is not enough if yuo have many aplications with the same name (i.e java).

In that case we have only pid. But i have no idea how to link it with any metadata of paticular application.

May be there are any best pactices ?

Thanks a lot for telegraf!)

**Comment by OrangeTux** [comment]
How would Telegraf be able to identify processes with the same name? 

A partial solution is to use the full command which started the process. But what if you've mulitple processes started by using the exact same command?

**Comment by sparrc** [comment]
@whetherharder can you use tag maps to do this?, ie:

```
[[inputs.procstat]]
  ...
  [inputs.procstat.tags]
    tag1 = "val1"

[[inputs.procstat]]
  ...
  [inputs.procstat.tags]
    tag2 = "val2"
```

also see #1035

**Comment by whetherharder** [comment]
Can not test now, but looks like it is defenitely what i need. Thanks much!

@whetherharder <https://github.com/whetherharder> can you use tag maps to
do this?, ie:

[[inputs.procstat]]
  ...
  [inputs.procstat.tags]
    tag1 = "val1"

[[inputs.procstat]]
  ...
  [inputs.procstat.tags]
    tag2 = "val2"

also see #1035 <https://github.com/influxdata/telegraf/issues/1035>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/influxdata/telegraf/issues/1048#issuecomment-212627138>

**Comment by sparrc** [comment]
okay, I'm going to close for now but please feel free to re-open if it doesn't fill your use-case
