### ISSUE TITLE
Telegraf   and  prometheus

### ISSUE THREAD

**Issue by jkeycat** [influxdata/telegraf#10485]
## if  i  want to  push  metrics  collected by  many telegraf    to    another  one,   and   push  metrics from  this  telegraf   to   remote  prometheus, how to do ? could  you  give  any suggestion?

Opening a feature request kicks off a discussion.

**Comment by powersj** [comment]
Hi,

Please take a look at the [HTTP listener v2 input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener_v2), which can listen for metrics sent from other telegraf which use the [HTTP output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/http).

This isn't a bug, but a support quest. Our [slack](https://influxdata.com/slack) or [forums](https://community.influxdata.com/) are better places for these types of questions, so I am going to go ahead and close this.

Thanks!
