### ISSUE TITLE
Linter for plugin documentation

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#10488]
Documentation of each plugin is in readme.md in the plugin folder. To make them easier to use, we try to keep the structure of the readme.md files similar for all plugins. They should always include a short description of the purpose of the plugin, a sample of its toml configuration, and a description of the plugin's metric format. They can optionally have compatibility notes and other sections.

Since many people edit the plugin docs it is hard to keep the structure similar. Let's add a linter that parses the markdown and checks that the expected sections are present. Since the sample toml config is also kept in the plugin's source code, the linter could also check that the two copies match.

There are other things a linter could do, such as check that all the toml settings that the plugin accepts are documented in the sample config.

This should also make code reviews of plugin changes more simple and help contributors of new plugins know what is required for documentation

**Comment by powersj** [comment]
next steps: @reimda to bring the final PR(s) home and land 'em!

**Comment by reimda** [comment]
Here's a summary of related work:

PRs merged:
* add linter - https://github.com/influxdata/telegraf/pull/10916
* run linter in CI - https://github.com/influxdata/telegraf/pull/11020
* clean up output readmes - https://github.com/influxdata/telegraf/pull/10951

PRs to be merged:
* clean up processor and aggregator readmes - https://github.com/influxdata/telegraf/pull/10960
* clean up input readmes a-d - https://github.com/influxdata/telegraf/pull/10964

no PR yet:
* clean up input readmes e-z

We're currently moving plugin sample configs to be in separate files (https://github.com/influxdata/telegraf/pull/11136 and related). Since that task also requires touching every readme, it makes sense not to do it at the same time as cleaning up the readme linter errors. Moving sample configs should be done in a few days. When it's done I'll continue cleaning up readme linter errors.

**Comment by powersj** [comment]
> Moving sample configs should be done in a few days. When it's done I'll continue cleaning up readme linter errors.

FYI @srebhan has completed these.

**Comment by reimda** [comment]
* #11214

**Comment by reimda** [comment]
* #11274

**Comment by sspaink** [comment]
@reimda I think this is done?

**Comment by reimda** [comment]
Yes it's done
