### ISSUE TITLE
There is a memory leak running the ras plugin

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#10495]
### Relevent telegraf.conf

```toml
[[inputs.ras]]
```

### Logs from Telegraf

telegraf log: nothing

lsof 

COMMAND      PID USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
telegraf 2850918 root  cwd       DIR              252,1      4096        2 /
telegraf 2850918 root  rtd       DIR              252,1      4096        2 /
telegraf 2850918 root  txt       REG              252,1 133894144  2364254 /usr/bin/telegraf
telegraf 2850918 root  DEL       REG                0,1           17334787 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334789 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334788 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334785 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334784 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334782 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334781 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334779 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334778 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17334777 /dev/zero
telegraf 2850918 root  DEL       REG                0,1           17336062 /dev/zero
telegraf 2850918 root  mem       REG              252,1   2029224     3977 /usr/lib/x86_64-linux-gnu/libc-2.31.so
telegraf 2850918 root  mem       REG              252,1    157224     3991 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
telegraf 2850918 root  mem       REG              252,1    191472     3967 /usr/lib/x86_64-linux-gnu/ld-2.31.so
telegraf 2850918 root    0r      CHR                1,3       0t0        6 /dev/null
telegraf 2850918 root    1u     unix 0xffff9f7fb376f800       0t0 17336056 type=STREAM
telegraf 2850918 root    2u     unix 0xffff9f7fb376f800       0t0 17336056 type=STREAM
telegraf 2850918 root    3u     unix 0xffff9f7edd818400       0t0 17336061 type=DGRAM
telegraf 2850918 root    4u  a_inode               0,14         0    10403 [eventpoll]
telegraf 2850918 root    5r     FIFO               0,13       0t0 17336058 pipe
telegraf 2850918 root    6w     FIFO               0,13       0t0 17336058 pipe
telegraf 2850918 root    7u     IPv6           17334771       0t0      TCP *:9126 (LISTEN)
telegraf 2850918 root   10u      REG              252,1     24576     3026 /var/lib/rasdaemon/ras-mc_event.db

### System info

Telegraf 1.21.2 (git: HEAD 30d981d3)

### Docker

docker version:
 
Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.8

### Steps to reproduce

1.  add ras input config
2.  The program runs for a period of time and observes the memory usage
3.It is best to deploy prometheus to access cadvisor container monitoring

### Expected behavior

Memory will slowly increase over time

lsof -p xx

There will be a lot of '/dev/zero'    

### Actual behavior

Memory will slowly increase over time

lsof -p xx

There will be a lot of '/dev/zero'

**Comment by fcddk** [comment]
look project issues: https://gitlab.com/cznic/memory/-/issues/2

**Comment by powersj** [comment]
Can you ping us in here again if a release is made with the fix?

Thanks!

**Comment by fcddk** [comment]
ok, I'm troubleshooting and trying to fix it.

**Comment by powersj** [comment]
Are you still seeing this issue? Looks like that upstream issue was closed, but it isn't clear to me what dependency needs to be updated.

Thanks!
