### ISSUE TITLE
timestream output plugin with multi-measure records

### ISSUE THREAD

**Issue by leinad87** [influxdata/telegraf#10493]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
In last AWS ReInvent conference, multi-measure records where announced: https://youtu.be/QjMZaKkq8YM?t=1163 . This changes the format of data storage, from this:

|time | hostname | measure_name | measure_value|
|--|--|--|--|
|2021-09-20 19:00:00 | host1 | cpu | 0.10|
|2021-09-20 19:00:00 | host1 | mem | 60|
|2021-09-20 19:00:00 | host1 | temp | 77 |

into this:
time | host | cpu | mem | temp
-- | --| --|--|--|
2021-09-20 19:00:00 | host1 | 0.10 | 60 | 77 |

With this new table approach, there is a significant storage reduction and queries on data are simpler. 

There is more info [here](https://repost.aws/questions/QUSWDEvNM-TqCC0Fs8svJUdQ/aws-io-t-timestream-rule-action-multi-measure-record) but I can't find technical documentation.

Should timestream output plugin be able to push multi-measure records?

**Comment by JuanRamiro** [comment]
Definitely!! Multi-record is an excellent option for many time series data and since TimeStream now supports it, Telegraf should also allow us to take advantage of it.

**Comment by JuanRamiro** [comment]
Accordind to AWS [here](https://docs.aws.amazon.com/timestream/latest/developerguide/Telegraf.how-it-works.html) TimeStream output plugin already supports this, but I cant's find this "multi-measure in single row" feature in any of the latest Telegraf versions.

**Comment by sysadmin1139** [comment]
Looking at the Go code, this version of Telegraf doesn't have multi-measure support. I really wish it did!

**Comment by powersj** [comment]
I believe we are waiting on some answers to https://github.com/influxdata/telegraf/pull/11385 before landing this feature.
