### ISSUE TITLE
Cloudwatch Input Plugin Error

### ISSUE THREAD

**Issue by nhproject** [influxdata/telegraf#1049]
Hi all,

I would like to work with the new input plugin of Cloudwatch.
I tried to work with both ENV vars and shared credentials config file, but in both cases I'm getting the following error in the Telegraf log:
``Error in input [cloudwatch]: NoCredentialProviders: no valid providers in chain. Deprecated. ``
``For verbose messaging see aws.Config.CredentialsChainVerboseErrors ``

Can anyone please help me figure out how to solve it?

Thanks!

Nitz

**Comment by sparrc** [comment]
Does the user you are running telegraf under have access to those? The telegraf service runs under the `telegraf` user so env vars or credentials files would need to be specified for that user.

**Comment by nhproject** [comment]
Both were defined to be specified for the telegraf user.
Eventually I managed to fix this issue.
Thanks!!

**Comment by sparrc** [comment]
@nhproject please share how you fixed it!!

**Comment by nhproject** [comment]
I'm working with our tests machine, where I'm logged in with my user, nitzan.
I created the credentials file (/home/nitzan/.aws/credentials), I ran ``sudo chown -R telegraf:telegraf ~/.aws`` (that's what you wrote me, actually), it didn't help.
The telegraf service is running under the telegraf user, so I simply changed it to run under my user and gave back permissions for the credentials file to my user. and it works.
It was a workaround just to see its a user problem and nothing else. In general, I'll work with the telegraf user of course.

**Comment by sofixa** [comment]
@nhproject That's because AWS' CLI and SDKs search for the credentials file in the root folder of the current user(so for telegraf, that would be telegraf and the credentials have to be in /home/telegraf/.aws/credentials or the respective home folder of the telegraf user).

**Comment by nhproject** [comment]
@sofixa I tried that too and it didn't work either, but tbh I created a folder for the telegraf (/home/telegraf), so maybe the home folder of the telegraf is somewhere else and that's why it didn't work.
Anyway, thanks :)
