### ISSUE TITLE
[telegraf] Error running agent: could not initialize input inputs.smart: smartctl not found

### ISSUE THREAD

**Issue by skalec** [influxdata/telegraf#10494]
### Relevent telegraf.conf

```toml
[[inputs.smart]]
```

### Logs from Telegraf

2022-01-23T20:14:45Z I! Starting Telegraf 1.21.2
2022-01-23T20:14:45Z I! Using config file: /etc/telegraf/telegraf.conf
2022-01-23T20:14:45Z I! Loaded inputs: cpu disk diskio docker kernel mem net netstat processes sensors smart swap system
2022-01-23T20:14:45Z I! Loaded aggregators:
2022-01-23T20:14:45Z I! Loaded processors:
2022-01-23T20:14:45Z I! Loaded outputs: influxdb
2022-01-23T20:14:45Z I! Tags enabled: host=Tower
2022-01-23T20:14:45Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Tower", Flush Interval:10s
2022-01-23T20:14:45Z E! [telegraf] Error running agent: could not initialize input inputs.smart: smartctl not found: verify that smartctl is installed and it is in your PATH (or specified in config): provided path does not exist: []

### System info

Ubuntu 20.04, Docker 20.10.5

### Steps to reproduce

1.install this docker
2.start this docker with old config after update container
3.
...

### Expected behavior

running telegraf

### Actual behavior

not starting Telegraf 

### Additional info

when disable smart in Telegraf.conf container is running

**Comment by powersj** [comment]
Hi,

Telegraf has hundreds of plugins for inputs and outputs. These plugins have a wide variety of requirements and additional software that may need to be installed and set up to function properly.

You will need to install `smartmontools` tools in the container before running telegraf for the `smartctl` command exists.

Thanks

**Comment by powersj** [comment]
Which version worked? Are you sure you did not create a custom image?

[This dockerfile](https://github.com/influxdata/influxdata-docker/blob/master/telegraf/1.21/Dockerfile) is used to generate the docker images. You will not see smartmontools installed.

**Comment by skalec** [comment]
I update the container yesterday. How can I fin my installed version. Unfortunately, I am not very familiar with docker.

i want install smart tool but need the root password or can I change it?

**Comment by powersj** [comment]
One method is to create a dockerfile and generate a new image with the package installed:

```
FROM telegraf:1.21

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends smartmontools \
    && apt-get clean -q \
    && rm -Rf /var/lib/apt/lists/*
```

I would suggest asking any other questions on our [community page](https://community.influxdata.com/) or [slack](https://influxdata.com/slack). You will get additional help from the community.

**Comment by skalec** [comment]
Issue can closed I find the manual to my setup and there stand the commands to fix it. I must use Telegraf 1.20.2 and add
Post Arguments

`/bin/sh -c 'apt update && apt install -y smartmontools && apt install -y lm-sensors && telegraf' --user 0`

Sry for my fail.
