### ISSUE TITLE
Docker container stats incorrectly include cache usage in memory usage

### ISSUE THREAD

**Issue by arturhgca** [influxdata/telegraf#10518]
### Relevent telegraf.conf

```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = false
  total = true
  docker_label_include = []
  docker_label_exclude = []
```

### Logs from Telegraf

No relevant logs, as everything runs correctly - the issue lies in semantics.

### System info

Telegraf 1.21.2, Debian 5.10.84-1, Docker 20.10.12

### Docker

No specific container.

### Steps to reproduce

1. Extract container memory usage from telegraf (e.g., `r["_measurement"] == "docker_container_mem", r["_field"] == "usage"`)
2. Compare results to the output of `docker stats`

### Expected behavior

The usage field reported by telegraf matches the usage value reported by Docker.

### Actual behavior

The vale reported by telegraf is always higher. It is the actual memory usage + the cache usage.

### Additional info

In #4383, telegraf was modified to calculate the actual memory usage, just like Docker CLI at the time.

However, some time recently, Docker seems to have changed the relevant section of the API:

![image](https://user-images.githubusercontent.com/29523470/150998712-1aa86a66-694c-4fb8-a564-fc41d85f8560.png)
Source: https://docs.docker.com/engine/reference/commandline/stats/#extended-description

Specifically, it defines `total_inactive_file` and `inactive_file` as the fields that report cache usage. Telegraf uses the `cache` field (which was correct in Docker 19.03 and older), as seen here: https://github.com/influxdata/telegraf/blob/v1.21.2/plugins/inputs/docker/stats_helpers.go#L44-L46

The current Docker API reference (v1.41) [still mentions the old way to calculate actual usage](https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats), which made me question the entire situation. I then decided to test what actually happens in my environment.

Using the SDK in Python (3.9.2), I extracted the following snapshot:

```json
{
    "read": "2022-01-25T14:29:51.814399613Z",
    "preread": "2022-01-25T14:29:50.804529978Z",
    "pids_stats": {
        "current": 24,
        "limit": 23825
    },
    "blkio_stats": {
        ...
    },
    "num_procs": 0,
    "storage_stats": {},
    "cpu_stats": {
        ...
    },
    "precpu_stats": {
        ...
    },
    "memory_stats": {
        "usage": 8721846272,
        "stats": {
            "active_anon": 270336,
            "active_file": 515616768,
            "anon": 29237248,
            "anon_thp": 0,
            "file": 8519098368,
            "file_dirty": 4190208,
            "file_mapped": 8239165440,
            "file_writeback": 405504,
            "inactive_anon": 25927680,
            "inactive_file": 8006184960,
            "kernel_stack": 393216,
            "pgactivate": 647691,
            "pgdeactivate": 693486,
            "pgfault": 61702344,
            "pglazyfree": 1004388,
            "pglazyfreed": 33132,
            "pgmajfault": 546843,
            "pgrefill": 947528,
            "pgscan": 83453204,
            "pgsteal": 25631126,
            "shmem": 0,
            "slab": 120245920,
            "slab_reclaimable": 119894648,
            "slab_unreclaimable": 351272,
            "sock": 0,
            "thp_collapse_alloc": 0,
            "thp_fault_alloc": 0,
            "unevictable": 0,
            "workingset_activate": 0,
            "workingset_nodereclaim": 221331,
            "workingset_refault": 0
        },
        "limit": 20855349248
    },
    "name": "redacted",
    "id": "redacted"
}
```

Of relevance:
* `memory_stats.stats.cache` does not exist;
* calculating `memory_stats.usage - memory_stats.stats.inactive_file` returns the exact value reported by `docker stats`.

**Comment by powersj** [comment]
Hi,

Can you please try the artifacts from #10491 to see if they resolve this?

Thanks

**Comment by arturhgca** [comment]
> Hi,
> 
> Can you please try the artifacts from #10491 to see if they resolve this?
> 
> Thanks

Sure thing! Are they built by CI or do I need to build from source?

**Comment by arturhgca** [comment]
Built it from source and can confirm that the issue is fixed there.
