### ISSUE TITLE
Trim down debug messages in disk

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#10514]
The `inputs.disk` plugin outputs extensive debug information which disrupts observation of e.g. buffer-fullness as reported by @voiprodrigo (see #10318).

Please remove the debug output in disk to make debug usable for those use-cases.

**Comment by srebhan** [comment]
@voiprodrigo opened the issue on your behalf.

We use this debug output to debug errors/strange behavior in Container/host environments. As such, I don't want to throw is away completely.
As a compromise,  we can trim down the output to only the two cases we know for creating trouble (`"dropped by mount prefix"` and `"dropped by disk usage"`). Would that work for you @voiprodrigo?

**Comment by voiprodrigo** [comment]
@srebhan thanks a lot for opening the issue. The approach seems great, appreciate the attention given to this 🙏
