### ISSUE TITLE
Support for parsing custom/multiple time fields in data parsers

### ISSUE THREAD

**Issue by sawo1337** [influxdata/telegraf#10524]
I've been dealing with a rather simple JSON data which shows health metrics from multiple mobile devices where battery level and last seen date is reported. I'm parsing it with inputs.file and I've used timestamp_key and timestamp_format to get the "last seen" field key and it is correctly stored in the time field for the metric. However, if someone wants to keep the time of the actual data log and store "last seen" in a separate field in unix timestamp format, it doesn't seem possible? Or, for example, if you have several date fields, there is no way to convert them all to unix timestamp?

### Proposal:
timestamp_key to support multiple fields and formats per-field or processors.converter to support date parsing

### Current behavior:
timestamp_key supports only one field and stores it in "time", no conversion is possible with processors.converter either

### Desired behavior:
add support either in inputs directly, or in processors.converter where dates to be converted to timestamp format

### Use case:
Pretty much any JSON that has more than one timestamp field that needs to be converted to proper unix timestamp

**Comment by srebhan** [comment]
So you want a "time" datatype for fields where you want to specify the output "flavor"?

**Comment by sawo1337** [comment]
> So you want a "time" datatype for fields where you want to specify the output "flavor"?

You can say that, yes. Basically I want the same thing which can be done already with the functionality of timestamp_key/timestamp_format, but for more than just one key. If you have a time field in the JSON, right now you can't really parse it and store it as unix timestamp in a custom field. Your only options are to either keep it as string in whatever format it comes, or parse it and store it in the time field in the measurement. The same thing applies if you have multiple time fields in the JSON and you want to parse them all as unix timestamps before storing in the database.

**Comment by srebhan** [comment]
@sawo1337 yeah there can be only one `timestamp_key` as the time field is a _special_ field in the metric, but I get what you are saying... @sspaink any thoughts?

**Comment by sawo1337** [comment]
@srebhan I've seen quite a few requests about this, especially for JSON, because for other data formats usually grok + logparser does the job, seems like only JSON is not covered in that aspect. Basically, if you have any form of uptime that you want to store, placing it in the special time field just doesn't work as you can't have historical data this way. Apart from that, if you store metrics that have created/updated fields, it ends up in the same situation.

**Comment by sspaink** [comment]
Sounds reasonable to allow timestamps to be converted to other formats, but just to clarify if your are sending them as fields they would still have to be strings but only the format would change. We could extend the "type" configuration option to accept unix, unix_ms, unix_us, unix_ns as well to convert the timestamp and save them as strings.

**Comment by sawo1337** [comment]
> Sounds reasonable to allow timestamps to be converted to other formats, but just to clarify if your are sending them as fields they would still have to be strings but only the format would change. We could extend the "type" configuration option to accept unix, unix_ms, unix_us, unix_ns to convert the timestamp and save them as strings.

@sspaink  the data is coming as strings, for example "2022-01-25T15:21:51.000Z00:00", the problem arises if I want to parse/convert that as unix timestamp and store it in a int field of my choice. 
At the moment, parsing date field as unix timestamp and storing it is possible only with the default time field as destination. If you have multiple date fields coming from a JSON, for example uptime/last seen fields, at the moment there is no way to convert those to unix timestamps so you can compare them later. I think it makes sense to be able to convert as many fields to unix timestamp as you'd like, rather than just the default time field.

**Comment by srebhan** [comment]
@sspaink I think you should split the time-**type** and time-**format** specification as otherwise you end-up in combinatorics... :-)
