### ISSUE TITLE
Wrong data type in metric with win_perf_counters and influxdb 0.9.6.1

### ISSUE THREAD

**Issue by 123BLiN** [influxdata/telegraf#1053]
Hello,

I dont know how it is possible but it looks like I have an already fixed bug.
in logs for some metrics:
```
win_disk,host=t-websrv-d,instance=HarddiskVolume1,objectname=LogicalDisk %\ Disk\ Write\ Time=0 1461011840049148100
2016/04/18 20:37:20 Gathered metrics, (10s interval), from 1 inputs in 48.0025ms
2016/04/18 20:37:20 ERROR: write failed: field type conflict: input field "%!I(MISSING)nterrupt Time" is type float64, a
lready exists as type %!!(MISSING)s(influxql.DataType=2)
2016/04/18 20:37:20 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```
but I see that this was closed in https://github.com/influxdata/influxdb/issues/3519
in version 0.9.3 - I have 0.9.6.1
Is it possible that win_perf_counters somehow cast to integer and adds "i" in the end of them?

Thanks!
Roman

**Comment by sparrc** [comment]
Nope, sorry, you will need to upgrade or migrate your db. If you need assistance you should contact support
