### ISSUE TITLE
[[inputs.exec]] make a changing data

### ISSUE THREAD

**Issue by Peter753l** [influxdata/telegraf#10542]
hello everyone,

I found a problem while using exec.
my shell:
alert_test_3.sh: |
    #/bin/bash
    echo "IfTable,agent_host=test,hostname=test,ifDescr=test,ifType=6 ifOperStatus=1,ifAdminStatus=1"
    sleep 30s
    echo "IfTable,agent_host=test,hostname=test,ifDescr=test,ifType=6 ifOperStatus=2,ifAdminStatus=1"

telegraf.conf: |
    [agent]
      interval = "60s"
      round_interval = false
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "2s"
      debug = true
      omit_hostname = true

    [[inputs.exec]]
      commands = [
        "bash /etc/telegraf/alert_test_3.sh"
        ]
      data_format = "influx"

but error:
[inputs.exec]: Error in plugin: exec: signal: killed for command 'bash /etc/telegraf/alert_test_3.sh'

I want to make a data of influxdb, the value of the first 30s is 1 and the value of the last 30s is 2, how can I do it?

**Comment by srebhan** [comment]
> I want to make a data of influxdb, the value of the first 30s is 1 and the value of the last 30s is 2, how can I do it?

@Peter753l I'd say by reading the [plugin documentation](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/exec/README.md)... ;-P There it states:

>  ## Timeout for each command to complete.
>  timeout = "5s"

with a default of **5 seconds**, however your script has a sleep of **30 seconds** which will always exceed the timeout and thus Telegraf kills your command. So you either find a way to remove the `sleep` in your script or by increasing the `timeout` A better way for the script might be to set the metric timestamp when outputting the metric. Not 100% if this works though...

**Comment by Peter753l** [comment]
> > I want to make a data of influxdb, the value of the first 30s is 1 and the value of the last 30s is 2, how can I do it?
> 
> @Peter753l I'd say by reading the [plugin documentation](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/exec/README.md)... ;-P There it states:
> 
> ```toml
> ## Timeout for each command to complete.
> timeout = "5s"
> ```
> 
> with a default of **5 seconds**, however your script has a sleep of **30 seconds** which will always exceed the timeout and thus Telegraf kills your command. So you either find a way to remove the `sleep` in your script or by increasing the `timeout` A better way for the script might be to set the metric timestamp when outputting the metric. Not 100% sure if this works though...

**Comment by Peter753l** [comment]
@srebhan 
thank you for your help. When I set timeout=40s, telegraf will not report an error. but I can only get the data after 40s, the data before 40s will not be collected.I don't know why.
Also, how do I change the timestamps to the data, I can't find any relevant information.I would be very grateful if you could provide a link to the information.

**Comment by srebhan** [comment]
@Peter753l the issue is the following, you generate two metrics
```csv
IfTable,agent_host=test,hostname=test,ifDescr=test,ifType=6 ifOperStatus=1,ifAdminStatus=1
IfTable,agent_host=test,hostname=test,ifDescr=test,ifType=6 ifOperStatus=2,ifAdminStatus=1
```
in your script. Those two metrics belong to the same series (same metric name, tag key/values and field key set). Now telegraf reads those two metrics **after** your script finished (not at the time you echo the metrics) and assign the same timestamp. You will now get the same series with identical timestamp, which results in overwritten metrics in Influxdb. If you run `telegraf --test` (i.e. only showing the metric in your terminal) you probably see **two** metrics that are identical (except for `ifOperStatus`). So your issue is that you have the wrong assumption on what telegraf does when you use exec and echo the metric!

I'm still not sure I get your _use-case_ of that script. Do you want to simulate a certain behavior or why do you have two metrics  that are generated in your script within a gather interval? So what are you trying to achieve?

We can also discuss on the #telegraf channel in Slack if you prefer...

**Comment by Peter753l** [comment]
@srebhan Yes, I do want to simulate a situation.
In prometheus I have an alert rule that requires an hour minimum of 1 and currently is 2.
min_over_time(IfTable_ifOperStatus{ifDescr!~"(ifType="6"}[1h]) == 1 and IfTable_ifOperStatus{ifType="6"} == 2 and IfTable_ifAdminStatus{ifType="6"} == 1
My prometheus acquisition cycle is 30s. For work reasons, I need to artificially create this kind of data to keep this alert firing.

**Comment by srebhan** [comment]
@Peter753l if this is for simulation only, you could either try to set the timestamp (last field of the line-protocol) of the two metrics without a sleep, or push the metrics directly to an `influxdb_listener` input-plugin.
Other than that, you can use the [`execd` input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) and output the correct metrics (see the examples there)...
