### ISSUE TITLE
telegraf-tiger: update artifacts comment

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#10556]
## Feature Request

Once all tests pass the Telegraf Tiger will add a comment to PRs with links to download all the built artifacts. This is a great way to test out PRs and verify fixes. However, there are still a number of users who do not see the drop-down link to expand and get the artifacts. 

In the below proposal, the Linux download is the amd64 tarball, the macOS download is the Intel tarball, and the Windows download is the amd64 zip. Given the vast majority of users are running on x86-64/amd64-based systems, it makes sense to provide some quick links to those downloads.

### Proposal:

Download PR build artifacts for [Linux](), [macOS](), and [Windows](). Downloads for additional architectures and packages are available below.
 
:+1: This pull request doesn't change the Telegraf binary size

:package: Click here to get additional PR build artifacts

**Comment by Hipska** [comment]
Maybe have the text "build artefacts"

**Comment by powersj** [comment]
> Maybe have the text "build artefacts"

Good catch - I have added "build" to both areas

**Comment by sspaink** [comment]
I made an internal PR to update the message, looks like this:
![image](https://user-images.githubusercontent.com/3441183/152068585-896aa5c3-52cc-4687-93c9-c02bac93ffca.png)

Only difference from the suggested is I mention "amd64 architecture", thought that might be useful?

**Comment by Hipska** [comment]
Hmm, what if other architecture becomes more popular on a platform? (macOS)

I would put (part of) the filename.

**Comment by sspaink** [comment]
![image](https://user-images.githubusercontent.com/3441183/152210005-662bda12-5ace-4720-a416-645d83054f4d.png)

This maybe?

**Comment by Hipska** [comment]
Yeah looks nice. Why not DMG for macOS? Oh, it looks that isn’t present for PR builds?

**Comment by sspaink** [comment]
That's right a DMG is only created during release when we sign the Mac artifacts: https://github.com/influxdata/telegraf/blob/master/scripts/mac-signing.sh

**Comment by sspaink** [comment]
Sounds like a good change to me, now live:

![image](https://user-images.githubusercontent.com/3441183/152224920-f6c5c50e-9a82-4963-9c6d-5ae77a554153.png)

**Comment by Hipska** [comment]
Why not having  the "click here to get ..." as the second line instead?
