### ISSUE TITLE
[inputs.x509_cert] detect revoked certificates

### ISSUE THREAD

**Issue by xoxys** [influxdata/telegraf#10550]
## Feature Request

Let's Encrypt has revoked some certificates on Friday last week https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449

Due to this revocation, I was wondering if there is a way to monitor such events with a telegraf input plugin. Right now I use `x509_cert` input, but that does not give any indicator if a cert was revoked.

### Proposal:

Maybe something like this could be added to the `x509_cert` input
https://github.com/ribbybibby/ssl_exporter/blob/83f01274fcd87044b269326a81c3d6b3c49de9da/prober/metrics.go#L167-L232

### Current behavior:

There seems to be no indicator on the `x509_cert` metrics to identify invalid certs due to a revocation.

### Desired behavior:

Add the ability to get alerts if a certificate is not valid anymore due to revocation.

**Comment by powersj** [comment]
Hi @xoxys,

Thanks for the request. How would the metric detect the revocation? We currently report the time till expiration, but this would require some sort of other check right? In the proposal, it looks like it uses this [parseResponse](https://github.com/ribbybibby/ssl_exporter/blob/83f01274fcd87044b269326a81c3d6b3c49de9da/vendor/golang.org/x/crypto/ocsp/ocsp.go#L455) function. Is that enough?

Thanks!

**Comment by xoxys** [comment]
Thanks for your feedback. Yes this should be enough. All required information especially the revokedAt attribute should be part of the ocsp response.
