### ISSUE TITLE
Environment variables: Allow default values or error messages if empty

### ISSUE THREAD

**Issue by jangmarker** [influxdata/telegraf#10557]
## Feature Request

When an environment variable is not set but is used for value as a tag, the tag's value will simply be the variable, e.g.:

```
[agent]
  hostname = "${CUSTOM_HOSTNAME}"
```

will lead to hostname having the value `${CUSTOM_HOSTNAME}`.

It would be great to allow to set default values or error messages if the variable is empty, similar to [docker-compose](https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files).

### Proposal:
Similar to [docker-compose](https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files) allow the following syntax (copied from the docs):

> - ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
> - ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.
> Similarly, the following syntax allows you to specify mandatory variables:
> - ${VARIABLE:?err} exits with an error message containing err if VARIABLE is unset or empty in the environment.
> - ${VARIABLE?err} exits with an error message containing err if VARIABLE is unset in the environment.

### Current behavior:
If variable has empty value the variable name is just used verbatim for the tag.

### Desired behavior:
See proposal above.

### Use case: 
- e.g. when using the feature of InfluxDB 2 that allows to manage Telegraf config on the InfluxDB server, for specialization of tags it is useful to set variables in e.g. `/etc/default/telegraf` - but it is a mess if you forget to set the environment variables
- similarly, you might have an ad-hoc configuration stored somewhere that collects large amounts of data so you use it occasionally to debug issues. The configuration is general enough to work on many hosts but needs special environment variables to work properly on the respective host - it's a lot easier to use if telegraf fails if some variables are not set.

**Comment by powersj** [comment]
Hi,

Thanks for the feature request.

Our variable substitution is fairly simple as you have discovered. This is not something built into TOML today, so it a bit of a unique item. I think the next steps are to look into this. My preference would be to reference the [bash docs](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion) for parameter expansion, which shouldn't be too different from docker-compose.

next steps: look into implementing the various substitutions and checking for missing variables
