### ISSUE TITLE
[inputs.vsphere] Invalid API reference link in METRICS.md 

### ISSUE THREAD

**Issue by futhork** [influxdata/telegraf#10569]
The "VMWare vCenter Converter API Reference" link in METRICS.md is stale(leads to redirect at developer.vmware.com/home). It not really bug, but as support request - it would be nice to fix this part of documentation

**Comment by powersj** [comment]
<dropping the support label>

Hi,

Do you know what the link should be?

Thanks!

**Comment by futhork** [comment]
Not really, quick search at vmware site gave nothing. I found this feature request influxdata/telegraf#6719 where 
@goejja and @prydin had left current link, maybe they know where this info was moved.

**Comment by goejja** [comment]
here is another link to [vim.PerformanceManager](https://vdc-download.vmware.com/vmwb-repository/dcr-public/a5f4000f-1ea8-48a9-9221-586adff3c557/7ff50256-2cf2-45ea-aacd-87d231ab1ac7/vim.PerformanceManager.html)

if you need more detailed explanation about one metric, it is better to refer to [Overview Performance Charts](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.monitoring.doc/GUID-FF7F87C7-91E7-4A2D-88B5-E3E04A76F51B.html)

**Comment by powersj** [comment]
Thanks for the links! I have put up a [PR](https://github.com/influxdata/telegraf/pull/10663) to include those links.
