### ISSUE TITLE
inputs/modbus probably bug of scale function 

### ISSUE THREAD

**Issue by gnoto** [influxdata/telegraf#10592]
I have some holding data (temperature) type INT16 to be scaled by 0.1 (example data 387 -> scale at -> 38.7 ° C) but I get to truncate the value of a digit (example data 387 -> becomes -> 38.7 ° C).
I just tried to declare data type as FIXED but obtain an error:

_2022-02-05T11:38:24Z E! [outputs.influxdb_v2] Failed to write metric (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "Temp B1" on measurement "modbus" is type float, already exists as type integer dropped=1_

Is it a bug? Any idea?

Tnx

**Comment by srebhan** [comment]
@gnoto it seems your InfluxDB already has an `integer` value in that column for that series. It's not possible to mix different datatypes in the same column **for the same series**. So either you delete/convert the existing series or start a new one (e.g. by using a different measurement name or add/change a tag). If you use telegraf with the `--test` option you will see the result of the request on the console without data being written to the database...
