### ISSUE TITLE
v1.21.3 not starting due to errors without config change

### ISSUE THREAD

**Issue by jordipalet** [influxdata/telegraf#10590]
I updated today from 1.21.2 to 1.21.3. In a Raspberry PI, no issues, but an identical config in Ubuntu brings lots of:

Feb 05 09:02:31 Camaras systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 05 09:02:31 Camaras systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 05 09:02:31 Camaras telegraf[4094]: 2022-02-05T08:02:31Z I! Starting Telegraf 1.21.3
Feb 05 09:02:31 Camaras telegraf[4094]: 2022-02-05T08:02:31Z W! DeprecationWarning: Plugin "inputs.io" deprecated since version 0.10.0 and will be removed in 2.0.0: use 'inputs.diskio' instead
Feb 05 09:02:40 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:41 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:45 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:46 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:46 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:48 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/SNMPv2-PDU:73:1: unexpected "max-bindings" (expected "END")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/ietf/TCPIPX-MIB:63:12: unexpected "tcpIpxConnLocalPort" (expected "}")
Feb 05 09:02:51 Camaras telegraf[4094]: Parse module: /usr/share/snmp/mibs/miblist.txt:1:12: no match found for .

and never starts.

Can't see why same configs fail in one system, not in the other ... unless is not telegraf itself but some library that the update is not "updating" ?

reverting to 1.21.2, makes it work again.

Any hint about how to resolve this?

**Comment by MyaLongmire** [comment]
@jordipalet Sorry you are having issues. Would mind trying out the artifacts if [this pr](https://github.com/influxdata/telegraf/pull/10551) to see if it fixes your issue. It changes how folders and walked and how mibs are loading to help decrease initialization time and to stop the infinite loop.

**Comment by Hipska** [comment]
Duplicates https://github.com/influxdata/telegraf/issues/10548, please add a comment in that issue with your findings.
