### ISSUE TITLE
jolokia2-Telegraf-Not collecting JVM data

### ISSUE THREAD

**Issue by v4vamsee** [influxdata/telegraf#10610]
### Relevant telegraf.conf

```toml
[[inputs.jolokia2_agent.metric]]
  name = "jolokia_jvm_args"
  mbean = "java.lang:type=Runtime"
  paths = ["InputArguments"]
```

### Logs from Telegraf

2022-02-09T14:53:59Z I! Loaded inputs: cpu disk jolokia2_agent linux_sysctl_fs mem netstat procstat swap
2022-02-09T14:53:59Z I! Loaded aggregators:
2022-02-09T14:53:59Z I! Loaded processors:
2022-02-09T14:53:59Z I! Loaded outputs: influxdb
2022-02-09T14:53:59Z I! Tags enabled: host=srvname
2022-02-09T14:53:59Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"srvname", Flush Interval:10s

### System info

Telegraf 1.21.3 , Linux Centos 3.10.0-1160.49.1.el7.x86_64, Influxdb-1.8.10

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Data collected in the "jolokia_jvm_arguments" bucket.

### Actual behavior

Data is not collected by Telegraf agent's Jolokia2 input.

### Additional info

Running following command works on the server where Telegraf/influxdb is running:

curl http://xxxxx:8199/jolokia/read -H Content-Type:application/json --data-binary '[{"type":"read","mbean":"java.lang:type=Runtime","attribute":["InputArguments"]}]'
[{"request":{"mbean":"java.lang:type=Runtime","attribute":"InputArguments","type":"read"},"value":{"InputArguments":["-Xms1536m","-Xmx1536m","-Xlog:gc*,safepoint:\/sites\/tomcatapps\/am\/logs\/am_gc_20220209_080930.log:um,time","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=\/sites\/tomcatapps\/am\/logs\/","-XX:+UseG1GC","-XX:MaxGCPauseMillis=400","-XX:G1HeapRegionSize=32m","-XX:MaxMetaspaceSize=256m","-XX:MetaspaceSize=256m","-XX:MinMetaspaceFreeRatio=0","-XX:MaxMetaspaceFreeRatio=100","-javaagent:\/sites\/tomcatapps\/am\/jolokia\/jolokia.jar=port=8199,host=xxxx,agentId=am","-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager","-Djava.util.logging.config.file=\/sites\/tomcatapps\/am\/conf\/logging.properties","-Djava.security.egd=file:\/dev\/.\/urandom","-Djavamelody.rewrap-datasources=false","-Dlog4j2.formatMsgNoLookups=true","-DiscUseSlf4j=true","-Dcom.sun.management.jmxremote=true","-Dcom.sun.management.jmxremote.port=8345","-Dcom.sun.management.jmxremote.local.only=false","-Dcom.sun.management.jmxremote.authenticate=false","-Dcom.sun.management.jmxremote.ssl=false","-Djava.rmi.server.hostname=xxxxx","-Dcatalina.base=\/sites\/tomcatapps\/am","-Dcatalina.home=\/sites\/tomcatapps\/am","-Djava.io.tmpdir=\/sites\/tomcatapps\/am\/temp"]},"timestamp":1644420527,"status":200}]

The same works via a web browser: http://xxxxx:8199/jolokia/read/java.lang:type=Runtime/InputArguments

**Comment by powersj** [comment]
Hi,

This looks like you are not collecting any metrics. The config you provided is not complete either. Additionally, the output you showed from your curl command does show stats, but I don't see any reference to `jolokia_jvm_args`. 

Have you taken a look at the [JVM data example](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2/examples/java.conf)?

Thanks!
