### ISSUE TITLE
Elasticsearch plugin have expanding fields in measurement elasticsearch_http

### ISSUE THREAD

**Issue by tjnome** [influxdata/telegraf#10621]
### Relevant telegraf.conf

```toml
[[inputs.elasticsearch]]
  servers = ["https://a-elastic.server.com:9243"]
  http_timeout = "10s"
  local = false
  cluster_health = false
  cluster_stats = false
  node_stats = ["http"]
```

### Logs from Telegraf

Size of the file is 5.6M. If neccessary I'll upload a file. 

A small sample down below. All identifieres are obsfuscated with xxx...

```
elasticsearch_http,cluster_name=xxxxxxx,host=a-elastic.server.com,node_attribute_availability_zone=xxxx,node_attribute_instance_configuration=xxxxxx,node_attribute_logical_availability_zone=xxxxx,node_attribute_node_type=xxxx,node_attribute_region=xxxxx,node_attribute_server_name=instance-xxxxxxxxxxxxx,node_attribute_transform.node=true,node_attribute_xpack.installed=true,node_host=xxxxxxx,node_id=xxxxxxxxxxxxx,node_name=instance-xxxxxxx,node_roles=data\,data_cold\,data_content\,data_frozen\,data_hot\,data_warm\,remote_cluster_client\,transform clients_0_id=xxxxxxx,clients_0_last_request_time_millis=1642369985669,clients_0_opened_time_millis=1642369812571,clients_0_request_count=4,clients_0_request_size_bytes=0,clients_1000_closed_time_millis=1644490827177,clients_1000_id=xxxxxxxxx,clients_1000_last_request_time_millis=1644490817074,clients_1000_opened_time_millis=1644490817074,clients_1000_request_count=1,clients_1000_request_size_bytes=0,clients_1001_id=xxxxxxx,clients_1001_last_request_time_millis=1643357116566,clients_1001_opened_time_millis=1643357116566,clients_1001_request_count=2,clients_1001_request_size_bytes=0,clients_1002_id=xxxxxxxx,clients_1002_last_request_time_millis=1644463330674,clients_1002_opened_time_millis=1644463330674,clients_1002_request_count=2,clients_1002_request_size_bytes=0,clients_1003_id=xxxxxxxx,clients_1003_last_request_time_millis=1640026023762,clients_1003_opened_time_millis=1640026023562,clients_1003_request_count=2,clients_1003_request_size_bytes=0,clients_1004_id=xxxxxxxxx,clients_1004_last_request_time_millis=1639951833064,clients_1004_opened_time_millis=1639951832864,clients_1004_request_count=2,clients_1004_request_size_bytes=0,clients_1005_id=xxxxxxxxx,clients_1005_last_request_time_millis=1643068810062,clients_1005_opened_time_millis=1643068538858,clients_1005_request_count=4,clients_1005_request_size_bytes=0,clients_1006_id=xxxxxxxxx,clients_1006_last_request_time_millis=1640436524670,clients_1006_opened_time_millis=1640436524470,clients_1006_request_count=2,clients_1006_request_size_bytes=0,clients_1007_id=xxxxxxxx,clients_1007_last_request_time_millis=1642167997762,clients_1007_opened_time_millis=1642167997562,clients_1007_request_count=2,clients_1007_request_size_bytes=0,clients_1008_id=xxxxxxxxxx,clients_1008_last_request_time_millis=1643746294761,clients_1008_opened_time_millis=1643746294761,clients_1008_request_count=2,clients_1008_request_size_bytes=0,clients_1009_id=xxxxxxxxx,clients_1009_last_request_time_millis=1641909172085,clients_1009_opened_time_millis=1641909172085,clients_1009_request_count=2,clients_1009_request_size_bytes=0,clients_100_id=xxxxxxxx,clients_100_last_request_time_millis=1641387155373,clients_100_opened_time_millis=1641387155373,clients_100_request_count=2,clients_100_request_size_bytes=0,clients_1010_id=xxxxxxxxxx,clients_1010_last_request_time_millis=1641721966174,clients_1010_opened_time_millis=1641721966174,clients_1010_request_count=2,clients_1010_request_size_bytes=0,clients_1011_id=xxxxxxxxx,clients_1011_last_request_time_millis=1644411725357,clients_1011_opened_time_millis=1644411725357,clients_1011_request_count=2,clients_1011_request_size_bytes=0,clients_1012_id=xxxxxxxxxxx,clients_1012_last_request_time_millis=1644433330465,clients_1012_opened_time_millis=1644433330265,clients_1012_request_count=2,clients_1012_request_size_bytes=0,clients_1013_id=1906497189,clients_1013_last_request_time_millis=1641443676457,clients_1013_opened_time_millis=1641443676257,clients_1013_request_count=2,clients_1013_request_size_bytes=0,clients_1014_id=xxxxxxxxxxx,clients_1014_last_request_time_millis=1644009308872,clients_1014_opened_time_millis=1644009308872,clients_1014_request_count=2,clients_1014_request_size_bytes=0,clients_1015_id=xxxxxxxxx,clients_1015_last_request_time_millis=1640022423076,clients_1015_opened_time_millis=1640022422276,clients_1015_request_count=2,clients_1015_request_size_bytes=0,clients_1016_id=xxxxxxxx,clients_1016_last_request_time_millis=1643292265863,clients_1016_opened_time_millis=1643292265863,clients_1016_request_count=2,clients_1016_request_size_bytes=0,clients_1017_id=xxxxxxxx,clients_1017_last_request_time_millis=1640240069658,clients_1017_opened_time_millis=1640240069257,clients_1017_request_count=2,clients_1017_request_size_bytes=0,clients_1018_id=xxxxxxxxx,clients_1018_last_request_time_millis=1642031061457,clients_1018_opened_time_millis=1642031061257,clients_1018_request_count=2,clients_1018_request_size_bytes=0,clients_1019_id=xxxxxxx,clients_1019_last_request_time_millis=1644418926781,clients_1019_opened_time_millis=1644418926581,clients_1019_request_count=2,clients_1019_request_size_bytes=0,clients_101_id=xxxxxxxxxx,clients_101_last_request_time_millis=1640836230469,clients_101_opened_time_millis=1640836230069,clients_101_request_count=2,clients_101_request_size_bytes=0,clients_1020_id=xxxxxxxxx,clients_1020_last_request_time_millis=1641202219271,clients_1020_opened_time_millis=1641202219071,clients_1020_request_count=2,clients_1020_request_size_bytes=0,...................
```

This continues for a long time.

### System info

Telegraf 1.14.3, Elastic 7.x

### Steps to reproduce

1. Include node_stats = ["http"] with newer version of elastic where cluster-nodes-stats have clients (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html)

2. Run query.
"show field keys from elasticsearch_http" |wc -l
 See that elastic fields are expanding: (Depends on usage of elastic) 

### Expected behavior

Expected behavior is two fields from documentation page:

elasticsearch_http
fields:
current_open (float)
total_opened (float)

### Actual behavior

Actual behavior:

elasticsearch_http
fields:
current_open (float)
total_opened (float)
clients_xxx_last_request_time_millis  float
clients_xxx_opened_time_millis        float
clients_xxx_request_count             float
clients_xxx_request_size_bytes        float
clients_xxx_closed_time_millis        float

Currently we have 27k fields in our production database. Probably caused by change in API: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

### Additional info

If other have same issue you can drop fields on telegraf client to temporary fix the issue
fielddrop = ["clients*"]

**Comment by tjnome** [comment]
> Hi,
> 
> I want to make sure I follow the request: while your config specifically set `node_stats = ["http"]` you do not want it to collect all the fields that are available under HTTP?
> 
> Thanks

I don't see the issue with collecting it but structure need to change. Maybe something like this:

tags:
cluster_name
node_attribute_ml.enabled
node_attribute_ml.machine_memory
node_attribute_ml.max_open_jobs
node_attribute_xpack.installed
node_host
node_id
node_name
_**client_id**_

fields:
current_open (float)
total_opened (float)
_**last_request_time_millis (float)
opened_time_millis (float)
request_count (float)
request_size_bytes (float)
closed_time_millis (float)**_

It could be a new measurement like elasticsearch_http_clients?

**Comment by powersj** [comment]
I can see the desire to have these split out, but two concerns with that:

1) I believe the client ID value would not be bound? This could grow to an enormous value very quickly and the impact on cardinally could be rather large.
2) Changing the data format is something that will break others who are already using this

**Comment by maraswrona** [comment]
I also have run into the same issue. At the moment in my deployment I have ~40k fields in this measurement. It is simply unusable in tools like chronograf or grafana which try to list all the possible field keys and hang / block for a while, not to mention that scrolling through 40k lines and finding what you need is very impractical.

According to InfluxDB best practices you should not be encoding information in field keys, but rather as a tag value. Regarding your cardinality argument, I believe it's actually the same. If you store 10 fields under 1 tag value, or redesign and store 5 fields under 2 tag values, cardinality is the same. 

Besides, this measurement schema is not as documented. In my opinion this is a bug.

**Comment by tjnome** [comment]
Yeah I agree, but still don't have a good solutions. For my use case the "clients" data was complete unnecessary and best solution was to drop the data: _fielddrop = ["clients*"]_
