### ISSUE TITLE
Errors in the wiki page about metrics buffer

### ISSUE THREAD

**Issue by arnoldyahad** [influxdata/telegraf#10644]
hey guys,
I've read the wiki page regarding the metric buffer: https://github.com/influxdata/telegraf/wiki/MetricBuffer#sizing
is there a chance that there is a mistake in the table:

metric_buffer_limit | RSS memory
-- | --
10,000 | 84M
100,000 | 287M
1,000,000 | 2,348G
10,000,000 | 14,060G

For me it seems like 1M metric_buffer_limit should be 2348M and not G (as it implies 2TB )

Am i mistaken or is do i need to have 2.3TB RSS memory for 1M of metric_buffer_limit?

**Comment by Hipska** [comment]
You are right, I think it needed to be a dot instead of comma, fixed it.

Also:
> The best way to measure the actual memory use for your workload is by having Telegraf write to a file output as well as the usual output. Once you have collected enough data you can load this into another Telegraf instance using the tail input and an exec output that always fails, filling the metric buffer limit until it overflows.
