### ISSUE TITLE
Signature Files for 0.12.1 release are not available

### ISSUE THREAD

**Issue by johnrengelman** [influxdata/telegraf#1065]
Can't build a Docker container using telegraf-docker for version 0.12.1 because the signature files are not available.
https://s3.amazonaws.com/get.influxdb.org/telegraf/telegraf_0.12.1-1_amd64.deb.asc returns an Access Denied message.

The .deb file is available.

**Comment by sparrc** [comment]
@rossmcdonald do you know anything about this? I'm not familiar with the process for how these files are generated

**Comment by rossmcdonald** [comment]
@johnrengelman Sorry about that! The signature should now be available. Let me know if you run into any other issues retrieving it.

**Comment by johnrengelman** [comment]
Thanks! Can confirm they are they :)
