### ISSUE TITLE
Instrument plugin info in Telegraf POST requests

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#10650]
In Cloud2, we track the number of requests made to us by each client library. It's from this we've learned about the real level of usage of each language with respect to our platform. Historically it's been Python but recently has been Go. This is useful information for us and I think it would be even more useful to us to have this same information about input plugins used. Any plugin, really, but inputs most importantly.

For client libraries, we include this information in the `user-agent` header of the requests so I feel like we could do something similar here. The problem, is there usually would be many more than one so we'd need to either have `user-agent` contain a list or or use multiple `user-agent` headers and I don't know if that's possible.

Thoughts?

**Comment by powersj** [comment]
@popey I know we briefly chatted about this in Slack, I'm curious if we ever came to a conclusion?
