### ISSUE TITLE
telegraf [inputs.snmp] Error in plugin

### ISSUE THREAD

**Issue by bigblue0** [influxdata/telegraf#10654]
I use telegraf-1.21.3 to  gather metrics from SNMP agents。

snmptable  can get a table information, 

telegraf prompt error messages:
[inputs.snmp] Error in plugin: agent udp://xx.xx.xx.xx:161: gathering table interface: performing bulk walk for field ifOutQLen: error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length.
Is there a problem with the configuration?

**Comment by MyaLongmire** [comment]
Can you please post your config and log files?

**Comment by henriknoerr** [comment]
Hey bigblue0, also try downgrading to 1.20.4 which was before the gosnmp merge.
Many issues was introduced then.

/Henrik

**Comment by bigblue0** [comment]
> Can you please post your config and log files?

I pasted the config about snmp and error log information into the file.
[snmp_input_error.txt](https://github.com/influxdata/telegraf/files/8106966/snmp_input_error.txt)

**Comment by bigblue0** [comment]
> Hey bigblue0, also try downgrading to 1.20.4 which was before the gosnmp merge. Many issues was introduced then.
> 
> /Henrik

I tried 1.20.4, the same error reporting .
