### ISSUE TITLE
Aggregate only some metrics in a measurement

### ISSUE THREAD

**Issue by nward** [influxdata/telegraf#10667]
### Proposal:

Aggregators support field filtering - but this drops all non-matching fields. Plugins return many different fields, some where aggregation is suitable, some where it is not.

For example - the 'diskio' plugin returns various counters which are a good candidate for derivative, but also `iops_in_progress` which is not.

### Current behavior:

Aggregators can aggregate all or nothing from a measurement.

### Desired behavior:

Aggregators can take include/exclude field options, which behave like so:

- `includefield` - matching fields are aggregated
- `excludefield` - matching fields are not aggregated

I am not certain what happens when non-aggregated fields are passed through. I think there are 2 options:
1. A new measurement is created immediately with only the non-aggregated fields. This should not happen if `drop_original` is false.
2. The most recent value is emitted along with the aggregated values when the plugin flushes

### Use case:

Allow plugins with some gauge and some counter metrics to be aggregated in a useful way.

**Comment by Hipska** [comment]
I don't think this is a good proposal, as you can still have the original value in the original metric (that one will still be there). So to me it makes perfect sense to only emit fields that should be aggregated by the filter.

**Comment by nward** [comment]
I’ve tested a few scenarios to get what I wanted in the last week, and thought I had tested both with drop_original enabled and disabled.

I will test again with it disabled - regardless I think this has merit, in situations where you have a measurement with say 8 counters you want to aggregate and 2 gauges you don’t - and the raw counter values are not useful.

Additionally, with drop_original disabled you now get aggregated metrics at fixed intervals, and non aggregated metrics whenever they came in. It’s advantageous to have these metrics with the same timestamps.

**Comment by matthijskooijman** [comment]
> 1. A new measurement is created immediately with only the non-aggregated fields. This should not happen if drop_original is false.

If you need the original values, just use `drop_original=false` and/or use another aggregation to select the values you want. There might be a bit of a challenge to get the timestamps matched up, but I'm not sure how to solve that in a way that is clean and obvious.

> 2. The most recent value is emitted along with the aggregated values when the plugin flushes

This seems rather arbitrary. Why the most recent value and not the max value, mean, etc.?

I would suggest another option:

 3. Emit only the selected aggregated fields and simply drop all other fields.

> According to documentation, they should have the same timestamp

What documentation exactly? From reading https://github.com/influxdata/telegraf/tree/release-1.23/plugins/aggregators/derivative I see nothing about the timestamp of the aggregated values, but in practice I've seen that the timestamp is the moment of aggregation, not the timestamp of the last value included in the aggregation (which I guess makes sense).

**Comment by powersj** [comment]
Going to close this one as I believe the previous posters have given solutions using the existing `drop_original` config option + metric filtering. If there is something more here please feel free to update the issue or file a new issue.
