### ISSUE TITLE
mdstat input plugin does not work when sync progress is less than 10%

### ISSUE THREAD

**Issue by llowrey** [influxdata/telegraf#10683]
### Relevant telegraf.conf

```toml
[[inputs.mdstat]]
```

### Logs from Telegraf

```
2022-02-20T06:00:10Z E! [inputs.mdstat] Error in plugin: error parsing sync line in md device "md1": error parsing float from recoveryLine "      [>....................]  check =  0.0% (335860/9766303232) finish=3876.8min speed=41982K/sec": strconv.ParseFloat: parsing " 0.0": invalid syntax
```

### System info

Telegraf 1.21.4, Fedora 35

### Steps to reproduce

1. enable mdstat input plugin
2. create an mdraid array that is big enough that it won't sync more than 10% within the 10s sampling period
3. put the array into check mode (eg `echo check > /sys/block/md1/md/sync_action`)
4. observe telegraf errors until the progress reaches 10%

### Expected behavior

No error and data collected for arrays with sync progress less than 10%.

### Actual behavior

Errors until sync progress reaches 10%

### Additional info

This can be fixed with a simple single character change

Before:
``recoveryLinePctRE    = regexp.MustCompile(`= (.+)%`)``

After:
``recoveryLinePctRE    = regexp.MustCompile(`= +(.+)%`)``

The change is the addition of a `+` after the space after the `=`. This allows for there to be more than one space between the `=` and the percentage number.

I tried to apply the fix but I'm having trouble getting `make check` to work.

Here's a sample `/proc/mdstat` that could be used for a unit test:

```
Personalities : [raid6] [raid5] [raid4] [raid0]
md42 : active raid6 sdac1[9] sdaa1[3] sdau1[5] sdas1[4] sdar1[1] sdah1[8] sdh1[2] sdv1[0] sdt1[6] sdc1[7]
      31255080960 blocks super 1.2 level 6, 512k chunk, algorithm 2 [10/10] [UUUUUUUUUU]
      [>....................]  check =  1.5% (59364224/3906885120) finish=404.4min speed=158560K/sec
      bitmap: 0/30 pages [0KB], 65536KB chunk

md0 : active raid0 sdad1[6] sdap1[3] sdaj1[4] sdak1[7] sdx1[5] sdf1[0] sdp1[2] sdl1[1]
      15001929728 blocks super 1.2 128k chunks

unused devices: <none>
```

**Comment by powersj** [comment]
Thank you for the test case and the fix! I have put up a [PR here](https://github.com/influxdata/telegraf/pull/10701)

**Comment by llowrey** [comment]
Merged already! You guys are **fast**! Thank you!
