### ISSUE TITLE
Deadlock in mqtt_consumer?

### ISSUE THREAD

**Issue by kitlaan** [influxdata/telegraf#10687]
I've been slowly tracing random loss of connectivity to my MQTT broker.
Finally got it nailed down that the broker disconnected the telegraf client, but telegraf never showed a disconnect on its debugging logs.

Doesn't this code need a `m.messagesMutex.Unlock()` before the `continue`?

https://github.com/influxdata/telegraf/blob/2ca5cfed94cef0b987ce487600c631e8583aa05e/plugins/inputs/mqtt_consumer/mqtt_consumer.go#L269-L277

**Comment by powersj** [comment]
Do you ever see a message like this:

```
fatal error: all goroutines are asleep - deadlock!
```

edit: Saw your PR, do you have logs to show an example of the failures you were seeing versus logs with your PR fixes?

**Comment by kitlaan** [comment]
For this particular issue, yes -- I did see that error message.

For the PR, the native debugging logs ended up just being a log full of the following, and no data flowing.
```D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics.```

Instrumenting the mqtt_consumer code, to log `len(m.sem)` and `len(m.acc.Delivered())`...

Without processor.dedup instantiated, the logs in gist would:
```
len(sem)=1 len(acc)=0 -- new metric; just call onMessage() [sem +1]
len(sem)=2 len(acc)=0 -- new metric just call onMessage() [sem +1]
len(sem)=3 len(acc)=0 -- new metric just call onMessage() [sem +1]
=== influxdb flush (3) [aka, now len(acc)=3]
len(sem)=3 len(acc)=2 -- new metric; call delivered cleanup and loop [acc -1]
len(sem)=4 len(acc)=1 -- ... now call onMessage() and return [sem +1]
len(sem)=5 len(acc)=1 -- new metric; only call onMessage() [sem +1]
len(sem)=6 len(acc)=1 -- new metric; only call onMessage() [sem +1]
=== influxdb flush (3)  [aka, now len(acc)=4]
...
```

With dedup's bug (now merged it seems), `len(sem)` would only grow faster, as there are packets that would never be delivered (and thus there are cases where `len(sem)` couldn't decrease).

With dedup's bug fixed (or without dedup at all), we're now at the whim of `select()` semantics.
> A select blocks until one of its cases can run, then it executes that case. It chooses one at random if multiple are ready.
