### ISSUE TITLE
delete issue

### ISSUE THREAD

**Issue by sorin2343** [influxdata/telegraf#10698]
hello ,

I what to delete a ticket created by me .
the ticket is https://github.com/influxdata/telegraf/issues/1935 .

can you help me ?

thanks
sorin

**Comment by srebhan** [comment]
@sorin2343 LMGTFY... This took me ~10 seconds of googling: https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue
 :-(

**Comment by sorin2343** [comment]
srebhan, I don't have such option

**Comment by srebhan** [comment]
I also don't have it. It seems to be a github issue where we probably cannot help...

**Comment by sorin2343** [comment]
it's about rights . 
Can you help me contact the admin of the repo?

**Comment by srebhan** [comment]
@sspaink or @powersj  any idea here?

**Comment by powersj** [comment]
I have deleted all the bug content for now.

I do not see the delete button either, only on my personal repos. I can submit an issue internally to see if a full admin can.

Thanks!

**Comment by powersj** [comment]
The bug was deleted.
