### ISSUE TITLE
Add Feels_Like temperature

### ISSUE THREAD

**Issue by bosshoss16** [influxdata/telegraf#10695]
I would like to request that "Feels_Like" temperature is added to this plug-in.  I know it is available from OWM, I just do not see it in the plug-in data.

Thank you!

**Comment by powersj** [comment]
Which plugin are you looking at?

**Comment by bosshoss16** [comment]
Hello, I am inquiring about the openweather map plugin.

After some digging around, it appears that the data returned using this plugin is not all that is offered by OWM.  But I am unable to write my own plugin, and this one is very well done.

Thank you.
