### ISSUE TITLE
There is insufficient result space to convert a money value to int.

### ISSUE THREAD

**Issue by SQLPro9** [influxdata/telegraf#1070]
I can run the sciprts in sqlserver.go manually with out any errors but with telegraf im getting below.

root@AMAZ-WE12EC:/etc/telegraf# telegraf -config /etc/telegraf/telegraf.conf
2016/04/20 20:03:03 Starting Telegraf (version 0.12.1)
2016/04/20 20:03:03 Loaded outputs: influxdb
2016/04/20 20:03:03 Loaded inputs: sqlserver
2016/04/20 20:03:03 Tags enabled: host=AMAZ-WE12EC
2016/04/20 20:03:03 Agent Config: Interval:40s, Debug:false, Quiet:false, Hostname:"AMAZ-WE12EC", Flush Interval:10s

2016/04/20 20:10:41 There is insufficient result space to convert a money value to int.
2016/04/20 20:10:45 Gathered metrics, (40s interval), from 1 inputs in 5.357445136s
2016/04/20 20:10:50 Wrote 414 metrics to output influxdb in 16.461024ms
2016/04/20 20:11:21 There is insufficient result space to convert a money value to int.
2016/04/20 20:11:25 Gathered metrics, (40s interval), from 1 inputs in 5.324630545s

any idea which data types needs to change.

**Comment by sparrc** [comment]
> I can run the sciprts in sqlserver.go manually with out any errors but with telegraf im getting below.

what do you mean by this?

**Comment by sparrc** [comment]
cc @zensqlmonitor does this error message look familiar to you?

**Comment by zensqlmonitor** [comment]
I will debug soon and come back.

**Comment by zensqlmonitor** [comment]
[#1083](https://github.com/influxdata/telegraf/pull/1083): SQL Server input. Fix datatype conversion.

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1083
