### ISSUE TITLE
Topk processor plugin - field parameter documentation not correct

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#10725]
Topk documention is using plural "fields" regarding field parameter.

Inserting more than one field is possible but does not work as expected, because its not implemented. Aggregation depends on sorting and is random, you can see it at golang code.
Also there does not exist any test case (at test_sets.go) with aggregation of more than one field.
I see following solutions:
- Update documentation and implement "fields" parameter not as an array
- Implement correct behaviour when using more than one field and describe how such an aggregation is working. Preferred behaviour: Use first field and if not availble at metricset use second one and so on.

**Comment by powersj** [comment]
Hi @1tft,

Would you be able to share a configuration and/or some sample data so I can reproduce and ensure a possible fix?

Thanks

**Comment by 1tft** [comment]
Hello @powersj,
we use following config to get information about backup dumps. We want to check, a new backup file has been created every day. So we analyze field "modification_time" submitted by filestat.

[[processors.topk]]
order = 10
#Attention: telegraf testing mode only workds with period = 0 but than no aggregation is done
period = 120
k = 1
aggregation = "max"
group_by = ["*"]
fields = ["modification_time"]


[[inputs.filestat]]
files = ["/file/path/dumps/*.tar.gz"]
md5 = false


But when filestat does not find any file there is no "modification_time" field (and measurement is completely dropped), thats why we tried field aggreagtion with topk over 2 fields:
   fields = ["modification_time", "exists"]
Configuration was possible, but as I wrote, topk plugin source code does not really handle more than one field regarding aggregation. So you cant trust on output, with more than one field aggregation.
Also there is no documentation, how aggregation over more than one field would work.

**Comment by powersj** [comment]
> Also there is no documentation, how aggregation over more than one field would work.

I completely agree with this :smile: I looked at this briefly last week and go nowhere. Hopefully as we work through this we can update the docs.

> But when filestat does not find any file there is no "modification_time" field (and measurement is completely dropped), thats why we tried field aggreagtion with topk over 2 fields:

Help me understand this a bit more as it is not clear to me. When filestat does not find any files, there should be no metrics produced. And as a result, nothing for the tokp processor to go over. I get no metrics produced until I touch a file in the filestat directory or pattern matching and then will topk start producing metrics:

```s
./telegraf --config config.toml --debug
2022-03-08T19:40:22Z I! Starting Telegraf 1.22.0-2c2fcc46
2022-03-08T19:40:22Z I! Loaded inputs: filestat
2022-03-08T19:40:22Z I! Loaded aggregators: 
2022-03-08T19:40:22Z I! Loaded processors: topk
2022-03-08T19:40:22Z I! Loaded outputs: file
2022-03-08T19:40:22Z I! Tags enabled: 
2022-03-08T19:40:22Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2022-03-08T19:40:22Z D! [agent] Initializing plugins
2022-03-08T19:40:22Z D! [agent] Connecting outputs
2022-03-08T19:40:22Z D! [agent] Attempting connection to [outputs.file]
2022-03-08T19:40:22Z D! [agent] Successfully connected to outputs.file
2022-03-08T19:40:22Z D! [agent] Starting service inputs
# start with empty directory
2022-03-08T19:40:32Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:40:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:40:52Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:41:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:41:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:41:22Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:41:32Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:41:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
# $ touch first.dat
2022-03-08T19:41:52Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:42:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=0i,modification_time=1646768502050854766i 1646768510000000000
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768520000000000
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768530000000000
2022-03-08T19:42:12Z D! [outputs.file] Wrote batch of 3 metrics in 68.83µs
2022-03-08T19:42:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:42:22Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:42:32Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-08T19:42:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768540000000000
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768550000000000
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768560000000000
filestat,file=/home/powersj/telegraf/test/first.dat size_bytes=0i,modification_time=1646768502050854766i,exists=1i 1646768570000000000

**Comment by 1tft** [comment]
> When filestat does not find any files, there should be no metrics produced.

Thats not correct. In case of no found file, filestat input does produce a metric set, but with field exists=0 (but no modification_time field). Thats why topk drops metric set when it only aggregates over "modification_time" field. But of course user wants always a valid metric set, also in case of no file (because of alerting rules etc.)
Currently I use telegraf defaults processor at beginning as workaround, to get always a valid metric set:
`[[processors.defaults]]`
 `   [processors.defaults.fields]`
 `     modification_time = 0`

I opened this issue only regarding topk "fields" parameter. User will think he can use more than one aggregation field (because its an array) but topk plugin does not handle aggregation correctly with multiple fields. I played with several fields and result was random. You can see at plugin code, that it does not respect multiple values at fields parameter correctly and there does not exist any [test case](https://github.com/influxdata/telegraf/blob/master/plugins/processors/topk/topk_test.go) for this situation, so I think nobody has really thought about implementing this.

**Comment by powersj** [comment]
>  so I think nobody has really thought about implementing this.

As I said above, you will have no argument from me about this. This is not a plugin that is easily maintainable, lacks docks and tests etc.

> I played with several fields and result was random. You can see at plugin code, that it does not respect multiple values at fields parameter correctly and there does not exist any [test case](https://github.com/influxdata/telegraf/blob/master/plugins/processors/topk/topk_test.go) for this situation, so I think nobody has really thought about implementing this.

What do you see that makes you think it does not go through both fields? And what are the random results you are seeing?

**Comment by powersj** [comment]
Here was my test with both fields:

```
# no files exist
looking at field: modification_time
looking at field: exists
filestat,file=/home/powersj/telegraf/test/*.dat exists=0i 1646772260000000000
filestat,file=/home/powersj/telegraf/test/*.dat exists=0i 1646772270000000000
filestat,file=/home/powersj/telegraf/test/*.dat exists=0i 1646772280000000000
filestat,file=/home/powersj/telegraf/test/*.dat exists=0i 1646772290000000000
# touch first.dat
looking at field: modification_time
looking at field: exists
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=0i,modification_time=1646772313147109938i 1646772320000000000
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=0i,modification_time=1646772313147109938i 1646772330000000000
# touch third.dat
looking at field: modification_time
looking at field: exists
filestat,file=/home/powersj/telegraf/test/third.dat exists=1i,size_bytes=0i,modification_time=1646772342770310718i 1646772350000000000
filestat,file=/home/powersj/telegraf/test/third.dat modification_time=1646772342770310718i,exists=1i,size_bytes=0i 1646772360000000000
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=0i,modification_time=1646772313147109938i 1646772340000000000
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=0i,modification_time=1646772313147109938i 1646772350000000000
filestat,file=/home/powersj/telegraf/test/first.dat modification_time=1646772313147109938i,exists=1i,size_bytes=0i 1646772360000000000
filestat,file=/home/powersj/telegraf/test/first.dat modification_time=1646772313147109938i,exists=1i,size_bytes=0i 1646772370000000000
```

So it does appear to go through both fields, however, the final output shows both the third and the first files. Is this the "random" output you are referring to? I assume your expectation was to only see the thrid file?

**Comment by 1tft** [comment]
Using my config above https://github.com/influxdata/telegraf/issues/10725#issuecomment-1061605920 I only get one result (`k = 1`). I only want latest file (file with highest modification_time).
When you use topk with `fields = ["modification_time", "exists"]` than you dont get every time latest file (file with highest modification_time), you get "random" file, because topk currently can not work correctly with more than one field aggregation.

**Comment by powersj** [comment]
> When you use topk with fields = ["modification_time", "exists"] than you dont get every time latest file (file with highest modification_time), you get "random" file, because topk currently can not work correctly with more than one field aggregation.

As you said in your original post, the field option is not working as you expect: based on what you have said it sounds like you expect it to check for the first value in the field array, find the max and return that. If the field does not exist, go to the next field and find that one.

The field option instead works by finding a match for each field specified. This means the more fields you check, the more results you will have. This is specified in step 2 of the README:

> 2. Every N seconds, for each bucket, for each selected field: aggregate all the measurements using a given aggregation function (min, sum, mean, etc) and the field.

Note it says for each selected field it runs the aggregation and returns the aggregation for the specified field. The README also specifies the behavior if a field is missing:

> * If a measurement does not have one of the selected fields, it is dropped from the aggregation

As an example, let's assume I have three files:

* first.dat: empty
* second.dat: random data in it
* third.dat: empty

Taking a look at the config with two fields:

```toml
[agent]
  omit_hostname = true

[[processors.topk]]
  period = 15
  k = 1
  aggregation = "max"
  group_by = ["*"]
  fields = ["modification_time", "size_bytes"]

[[inputs.filestat]]
  files = ["/home/powersj/telegraf/test/*.dat"]
  md5 = false

[[outputs.file]]
```

Based on this config I would expect file second.dat to show up as the top for `size_bytes`, since it is the biggest, and third.dat to show up as the top for `modification_time` as it was the one that was created last:

```
2022-03-14T15:20:58Z I! Starting Telegraf 1.22.0-4fcff21c
2022-03-14T15:20:58Z I! Loaded inputs: filestat
2022-03-14T15:20:58Z I! Loaded aggregators: 
2022-03-14T15:20:58Z I! Loaded processors: topk
2022-03-14T15:20:58Z I! Loaded outputs: file
2022-03-14T15:20:58Z I! Tags enabled: 
2022-03-14T15:20:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2022-03-14T15:20:58Z D! [agent] Initializing plugins
2022-03-14T15:20:58Z D! [agent] Connecting outputs
2022-03-14T15:20:58Z D! [agent] Attempting connection to [outputs.file]
2022-03-14T15:20:58Z D! [agent] Successfully connected to outputs.file
2022-03-14T15:20:58Z D! [agent] Starting service inputs
2022-03-14T15:21:08Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-03-14T15:21:18Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
topk: looking at field: modification_time
topk: found top metric: filestat&file=/home/powersj/telegraf/test/third.dat&

topk: looking at field: size_bytes
topk: found top metric: filestat&file=/home/powersj/telegraf/test/second.dat&

filestat,file=/home/powersj/telegraf/test/third.dat exists=1i,size_bytes=0i,modification_time=1647271070329283307i 1647271260000000000
filestat,file=/home/powersj/telegraf/test/third.dat exists=1i,size_bytes=0i,modification_time=1647271070329283307i 1647271270000000000
filestat,file=/home/powersj/telegraf/test/second.dat exists=1i,size_bytes=42i,modification_time=1647270818712850830i 1647271260000000000
filestat,file=/home/powersj/telegraf/test/second.dat exists=1i,size_bytes=42i,modification_time=1647270818712850830i 1647271270000000000
```

For your particular scenario I do think ensuring the `modification_time` field exists will ensure you get the behavior you are after.

Does this help clear up the current state of the topk processor plugin?

**Comment by 1tft** [comment]
Thank you @powersj for your detailed answer.
I see that your output is as expected and I ran such a configuration many days. After some time result was changing, it was not constantly the same. Than I looked at topk source code and didn't find proper handling for more than one aggreation field. There is no sorting, so you can't trust that everytime first field is used for aggregation.
I thought that I can convince you, that when there is no topk testing case with an aggregation over more than one field, than this use case is not really implemented.
I'm not a Golang coder, so I cant explain in detail. Maybe I find a fellow who can explain the specific code lines regarding the sorting issue.

**Comment by powersj** [comment]
> After some time result was changing, it was not constantly the same

Hmm let me think about how I could replicate this. Given you have files going in and out I wonder what might be causing a change.

> There is no sorting, so you can't trust that everytime first field is used for aggregation.

I agree with you on this, as the Go slice holding the fields is un-ordered, but I am not sure I understand how this would change the output.

**Comment by 1tft** [comment]
> I agree with you on this, as the Go slice holding the fields is un-ordered, but I am not sure I understand how this would change the output.

This topk configuration: `fields = ["modification_time", "size_bytes"] k=1 aggregation = "max"`
Initial condition on file system: first.dat has a 1647271070329283308 modification_time and 40 size_bytes
and second.dat has 1647271070329283307 modification_time and 41 size_bytes

With no sorting no aggregation is priorized by topk and so you will get random results with given config. Sometimes first.dat is winner (topk use max on modification_time), sometimes second.dat is winner (topk use max on size_bytes).

**Comment by powersj** [comment]
> This topk configuration: fields = ["modification_time", "size_bytes"] k=1 aggregation = "max"
Initial condition on file system: first.dat has a 1647271070329283308 modification_time and 40 size_bytes
and second.dat has 1647271070329283307 modification_time and 41 size_bytes

In this condition and config I would expect:

* first.dat to get printed due to the higher modification time
* second.dat to get printed due to the larger size

> With no sorting no aggregation is priorized by topk and so you will get random results with given config. Sometimes first.dat is winner (topk use max on modification_time), sometimes second.dat is winner (topk use max on size_bytes).

How are you determining the winner? 

I've been looking at the output to stdout, but now I'm wondering if I am missing something with the way you are observing the metrics that are produced. With two fields specified, there should always be two winners, something like:

```
filestat,file=/home/powersj/telegraf/test/first.dat modification_time=1647360689561896917i,exists=1i,size_bytes=4i 1647360770000000000
filestat,file=/home/powersj/telegraf/test/first.dat exists=1i,size_bytes=4i,modification_time=1647360689561896917i 1647360780000000000
filestat,file=/home/powersj/telegraf/test/second.dat size_bytes=5i,modification_time=1647360687251904103i,exists=1i 1647360760000000000
filestat,file=/home/powersj/telegraf/test/second.dat modification_time=1647360687251904103i,exists=1i,size_bytes=5i 1647360770000000000
```

**Comment by 1tft** [comment]
Thank you for your endurance with this topic!!
Till today I thought with setting `k = 1` I force topk to produce only one result, but thats false. I got 2 results with example configuration of my last post. I haven't noticed this, because I'm using a regex processor which modifies results and so I only got one result at InfluxDB.
With this new insight I have one question to you, what result should topk produce in following situation:
Telegraf topk configuration: `period = 30 fields = ["modification_time", "exists"] k = 1 aggregation = "max"` For filestat I use `interval = "10s"`
Condition on file system: first.dat has a 1647366302986006691 modification_time
and second.dat has different 1647364199292890990 modification_time (same file size, but this should not be relevant)

Regarding my tests, topk produces 2 results:
filestat,file=/telegraf/test/first.dat size_bytes=2i,modification_time=1647364199292890990i,exists=1i 16473665370000000000
filestat,file=/telegraf/test/second.dat size_bytes=2i,modification_time=1647366302986006691i,exists=1i 16473665370000000000

I would expect only 1 result but because of 2 results produced by topk my regex processing generated "random" results for me.

**Comment by 1tft** [comment]
OK, now I understand. You will get k individual results per "fields" value. So please can you update documentation regarding working with more than one fields value? Maybe sth. like this?!

*********
_## How many top buckets to return. k defines amount of results per fields value (and not total amount).
  _# k = 10

_## Over which fields is the aggregation done individually (buckets are aggregated completely independent). Topk produces _k_   results per fields value (for each fields value available at measurement). The more fields values the more result sets.
 _# fields = ["value"]

If a measurement does not have one of the selected fields, it is dropped from the aggregation. If you dont want to lose any measurement think about using Telegraf Defaults Processor Plugin at beginning of processing pipeline.
*********

Thank you for all the time you invested to this topic!!

**Comment by powersj** [comment]
> So please can you update documentation regarding working with more than one fields value? Maybe sth. like this?!

Would you please take a look at #10830 and see if it helps? 

> Thank you for all the time you invested to this topic!!

Most welcome, thank you for the examples as it helped me greatly
