### ISSUE TITLE
Graylog output plugin timestamp behaviour

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#10724]
Since latest Telegraf update behaviour of graylog output plugin changed:
**Old behaviour**: If field named "timestamp" has not a valid gelf timestamp format (unix epoch and maybe milliseconds) graylog output plugin overwrites "false" timestamp field with current time (using correct gelf timestamp format).
**New behaviour**:  Field named "timestamp" with any value is not changed, regardless of value.

When this new behaviour is desired, please write this (specification) down to documention so that users can trust on this. Else please change back to previous behavior (and also write this as desired behaviour to documentation).

**Comment by powersj** [comment]
Hi,

I have a few questions to help understand where this change came from that might be causing the issue:

1. What version was this last working on? 
2. What version are you seeing this not work with?
3. Could you please provide us with an example of data and a config that I could use to reproduce this?

Thanks

**Comment by 1tft** [comment]
1. Dont know exact version, but I think it was any 1.20 Behaviour change occured probably with https://github.com/influxdata/telegraf/commit/7049967fa974cc89d394d0eee0a1c968442d5c5a
2. 1.21.3
3. Use any config with graylog output which produces field "timestamp" with any string value like "dummy", than you will see graylog output will forward this although this is no valid gelf timestamp (and dont replace it with valid timestamp).
E.g. with 
` [[processors.defaults]]   
  [processors.defaults.fields]  
   timestamp = "dummy" `
If you want, I can build an example config with inputs.tail or inputs.filestat and and example log file.

**Comment by powersj** [comment]
Currently, if you are sending a field of "timestamp" with random data you should be seeing these messages from Graylog:

```
open-core-graylog-1        | 2022-02-25 20:19:51,200 WARN : org.graylog2.inputs.codecs.GelfCodec - GELF message <4951eaf0-9678-11ec-8f89-0242ac140004> (received from <172.20.0.1:46473>) has invalid "timestamp": dummy  (type: STRING)
open-core-graylog-1        | 2022-02-25 20:20:01,201 WARN : org.graylog2.inputs.codecs.GelfCodec - GELF message <4f47f300-9678-11ec-8f89-0242ac140004> (received from <172.20.0.1:46473>) has invalid "timestamp": dummy  (type: STRING)
open-core-graylog-1        | 2022-02-25 20:20:11,202 WARN : org.graylog2.inputs.codecs.GelfCodec - GELF message <553dd400-9678-11ec-8f89-0242ac140004> (received from <172.20.0.1:46473>) has invalid "timestamp": dummy  (type: STRING)
```

> Dont know exact version, but I think it was any 1.20 Behaviour change occured probably with https://github.com/influxdata/telegraf/commit/7049967fa974cc89d394d0eee0a1c968442d5c5a

The source of the change is from that PR as it was requested that our Graylog output follow the [Graylog GELF spec](https://docs.graylog.org/docs/gelf). The previous behavior was checking for a few, but not all fields from the spec, to *not* appending a leading `_`. The timestamp field was appending the `_` so the message that was going out would look like: `{\"_timestamp\":\"dummy\"...}`.

With the new behavior, Telegraf specifically does not append `_` to any of the fields specified by the spec. The timestamp field is specifically called out in the GELF spec and should be set by the client library with a unix epoch and not appended with a `_`.

Unless you intended to change the data to conform to the spec, I suggest using a processor to rename the field. I can add additional docs to the Graylog output specifying that GELF spec fields are not touched and should conform to the spec.

Does this explain the new behavior? Thanks!

**Comment by 1tft** [comment]
Yes, graylog is complaining about this timestamp field. Everything is correct.
And you found out the reason, why previously you could set timestamp with "dummy", because it was send out as another field "_timestamp" and not the gelf time specification field "timestamp".
So I think docs should mention: When user sets timestamp field on its own, he has to take care that this field is Gelf standard conform. Graylog output plugin will not touch existing timestamp field. But if timestamp field is missing at event data, Graylog output plugin will insert it with current eventtime, so user dont have to set it on its own.

**Comment by powersj** [comment]
>  So I think docs should mention: When user sets timestamp field on its own, he has to take care that this field is Gelf standard conform. Graylog output plugin will not touch existing timestamp field. But if timestamp field is missing at event data, Graylog output plugin will insert it with current eventtime, so user dont have to set it on its own.

Agreed, I'll put up a PR first thing next week. Thanks for confirming!
