### ISSUE TITLE
Telegraf precision parameter parsing in agent configuration

### ISSUE THREAD

**Issue by Franky1** [influxdata/telegraf#10734]
I happened to notice that I have had a bug in my Telegraf `agent` section configuration for a long time that I hadn't noticed before, and Telegraf hasn't complained about this bug either.

It is about the `precision` parameter in the `agent` section.
The documentation says:

> Valid values are `ns` , `us` (or `µs` ), `ms` , and `s`

So I had the following configuration in my `agent` section:
```
[agent]
  interval = "1s"
  precision = "ns"
```
The configuration works and there was no error message, but the `precision` parameter is ignored in this case and replaced by the value in `interval`. I noticed this behaviour, when I was working with higher resolution timestamps and wondered why all my timestamps were rounded to `1s` after the output from Telegraf. :thinking:

The correct configuration should be:

```
[agent]
  interval = "1s"
  precision = "1ns"
```

**In my opinion, the documentation here is misleading, and if Telegraf doesn't complain, you may not notice this error unless you look very closely at your output timestamps.**

---

Also, the behavior of the `precision` parameter in an input plugin is different, there Telegraf complains.
This does not work:

```
[[inputs.file]]
  precision = "ns"
```
>  [telegraf] Error running agent: Error loading config file xxx.conf: error parsing file, line 31:{363 455}: error parsing duration: time: invalid duration "ns"

This works and of course overrides the global `precision` setting of the `agent` section:

```
[[inputs.file]]
  precision = "1ns"
```

---

IMHO this inconsistent behaviour of the `precision` parameter should be fixed in the `agent` section?

**Comment by Franky1** [comment]
- It is here under `Agent Configuration` on the website:
<https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#agent-configuration>
- The same text also appears in the example config file you can generate with `telegraf config > telegraf.conf`
- In GitHub it is slightly better, because it refers at least to the **Intervals** section.

**Comment by sjwang90** [comment]
I submitted a PR for changing the docs explanation: https://github.com/influxdata/docs-v2/pull/3809

We will want to make sure Telegraf complains when it's misconfigured in the agent like it does when it's set under inputs.

**Comment by Hipska** [comment]
Looking at the code, I can't see why `precision = "ns"` would give an error while on input, but not on general agent config. Could you verify this again please?

**Comment by sjwang90** [comment]
I receive this error when i set `precision = "ns"` under my input. No error when it's under agent.

```
$ telegraf -config /Users/swang/telegraf.d/inputs.http.openweather-object.conf -test
2022-02-25T16:17:54Z I! Starting Telegraf 1.21.4
2022-02-25T16:17:54Z E! [telegraf] Error running agent: Error loading config file /Users/swang/telegraf.d/inputs.http.openweather-object.conf: error parsing http, line 4:{30 269}: error parsing duration: time: invalid duration "ns"
```

**Comment by Hipska** [comment]
Yeah, see my edit. I did see some possible difference..

**Comment by Franky1** [comment]
@Hipska 
Yes i confirm again this behaviour.

```
Win 10 x64
Telegraf 1.21.4 (git: HEAD 583ee20a)
```

This config works without error:

```toml
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "1s"
  precision = "ns"
  debug = true
  logtarget = "file"
  logfile = "precision.log"
  hostname = "localhost"
  omit_hostname = true

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[outputs.file]]
  files = ["precision.out"]
  influx_sort_fields = true
```

This config fails with an error message:

```toml
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "1s"
  # precision = "ns"
  debug = true
  logtarget = "file"
  logfile = "precision.log"
  hostname = "localhost"
  omit_hostname = true

[[inputs.cpu]]
  precision = "ns"
  percpu = false
  totalcpu = true

[[outputs.file]]
  files = ["precision.out"]
  influx_sort_fields = true
```

**Comment by Hipska** [comment]
Can you also confirm that this specific binary produces incorrect configuration with `telegraf config`?

**Comment by Franky1** [comment]
@Hipska
It does not produce incorrect configuration, but the same misleading content as it was in the documentation.

```
Win10 x64
Telegraf 1.21.4 (git: HEAD 583ee20a)
```

```
telegraf.exe config > telegraf.conf
```

leads to this `precision` config in the `agent` section:

```

## By default or when set to "0s", precision will be set to the same
## timestamp order as the collection interval, with the maximum being 1s.
##   ie, when interval = "10s", precision will be "1s"
##       when interval = "250ms", precision will be "1ms"
## Precision will NOT be used for service inputs. It is up to each individual
## service input to set the timestamp at the appropriate precision.
## Valid time units are "ns", "us" (or "µs"), "ms", "s".
precision = ""

```

I am not sure, if the empty string is valid?

**Comment by Hipska** [comment]
Thanks for this confirmation. The empty string is valid and means "use the default". The text pasted by you does not give misleading info, it clearly says that these are the valid units (not values).

**Comment by powersj** [comment]
I have put up a [PR here](https://github.com/influxdata/telegraf/pull/10746) clarifying the requirement to have both an integer + unit. This will fix the internal Telegraf docs + the generated config. Please feel free to wordsmith as needed.

As far as the behavior of setting the precision in the agent with just a unit, this will take more work. What I noticed is if I set `interval = "blah"` telegraf does not complain either. There seem to be some dragons in the agent setup that need attention.

**Comment by Franky1** [comment]
The documentary is now much better.
But what I don't like is that the incorrectly set parameter is simply **ignored silently** and without an error message.
As I wrote at the beginning of the issue, I had this error in my configuration for months without realizing it. And you don't necessarily recognize this misconfiguration either. It wasn't until I started looking at timestamps with `us` precision and looked very closely at the output timestamps that I realized something was wrong. But it took me longer to find the real cause.

**Comment by powersj** [comment]
I do not disagree at all. That was the point of my 2nd paragraph above, that there are issues with the agent config, including other parameters that fail silently. I have spent a whole 20 minutes looking at it and it is not a simple fix, but it is something that should be fixed.

**Comment by powersj** [comment]
I'm going to re-open this as merging my docs PR closed this one.

We still need to go and figure out why invalid agent settings are silently ignored and not printing errors.

**Comment by powersj** [comment]
> @powersj `internal.Duration` vs `time.Duration` is the problem.

I am glad it so clear to you. It would have been great if you could include some additional details. 

I was able to narrow down the change to occurring between v1.18.3 and v1.19.0-rc0 ([Diff between v1.18.3 and v1.19.0-rc0](https://github.com/influxdata/telegraf/compare/v1.18.3...v1.19.0-rc0)). Using this config:

```toml
[agent]
  interval = "5"
[[outputs.file]]
[[inputs.mem]]
```

Behavior in v1.18.3:

```s
2022-03-03T21:44:18Z I! Starting Telegraf 1.18.3
2022-03-03T21:44:18Z E! [telegraf] Error running agent: Agent interval must be positive, found 0s
```

Behavior in v1.19.0-rc0

```s
2022-03-03T21:44:38Z I! Starting Telegraf 1.19.0
2022-03-03T21:44:38Z I! Loaded inputs: mem
2022-03-03T21:44:38Z I! Loaded aggregators: 
2022-03-03T21:44:38Z I! Loaded processors: 
2022-03-03T21:44:38Z I! Loaded outputs: file
2022-03-03T21:44:38Z I! Tags enabled: host=ryzen
2022-03-03T21:44:38Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ryzen", Flush Interval:10s
```

Sure enough, it looks like #8969 is the breaking change, specifically [this implementation of UnmarshalTOML](https://github.com/influxdata/telegraf/commit/9853bf6c54ff18ab0e14a141b7b4580a1e54976a#diff-67213f39b84a013e7db04664cd3ad943b7a237d97b9c6e862d10806ac27def28L76) where we try to parse a value as a Duration first before other data types. However, this does not explain why we fail on setting an interval for input plugins today.

Here are some notes looking at this some more:

- [AgentConfig](https://github.com/influxdata/telegraf/blob/master/config/config.go#L134) and [InputConfig](https://github.com/influxdata/telegraf/blob/master/models/running_input.go#L58) both have `Interval` and `Precision` of type on `time.Duration`.
- Following the agent config execution path, the agent TOML is parsed in [config.go:LoadConfigData()](https://github.com/influxdata/telegraf/blob/master/config/config.go#L840). The `UnmarshalTable` call either sets the interval correctly (i.e. `5s`) or the value silently ignored (i.e. `5`). The AST table correctly sees a string, so some conversation is taking place somewhere as [time.duration](https://pkg.go.dev/time#Duration) is eventually an int64. 
- On the input side, the interval is [set here](https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L284), however, before it gets there and before it runs `UnmarshalTable`, there is a call to [config.go:buildInput()](https://github.com/influxdata/telegraf/blob/master/config/config.go#L1505) where the following is called:

```go
func (c *Config) buildInput(name string, tbl *ast.Table) (*models.InputConfig, error) {
	cp := &models.InputConfig{Name: name}
	c.getFieldDuration(tbl, "interval", &cp.Interval)
	c.getFieldDuration(tbl, "precision", &cp.Precision)
	c.getFieldDuration(tbl, "collection_jitter", &cp.CollectionJitter)
	c.getFieldDuration(tbl, "collection_offset", &cp.CollectionOffset)
...
```

These early checks are looking for plugin settings that are not plugin-specific (e.g. interval, tags) and setting them. On the agent config, it does not make sense to do this since we know all the defined options. This explains the difference in behavior. 

To resolve this, it sounds like we need to possibly check for these duration fields and attempt to parse and set them as durations before parsing the larger config.

Thoughts?

**Comment by powersj** [comment]
Put up https://github.com/influxdata/telegraf/pull/10781 with some more thoughts

**Comment by Hipska** [comment]
Okay, lets clarify a bit more:

> * [AgentConfig](https://github.com/influxdata/telegraf/blob/master/config/config.go#L134) and [InputConfig](https://github.com/influxdata/telegraf/blob/master/models/running_input.go#L58) both have Interval and Precision of type on time.Duration.

Not true, AgentConfig is having `config.Duration` as type. It has its own `UnmarshalTOML` method that indeed silently ignores values it couldn't parse. When the last line would return an error instead of `nil`, I think that would then be more clear what goes wrong..

**Comment by powersj** [comment]
> Not true, AgentConfig is having config.Duration as type. It has its own UnmarshalTOML method that indeed silently ignores values it couldn't parse.

Yes, you are more precise in saying that AgentConfig is config.Duration. However, the AgentConfig's UnmarshalTOML method is never used outside of a single test. The unmarshall table function that is used is from the InfluxData TOML library and does return errors. It will parse a string, like "3" or "3s" to a string. It has no concept of a Duration.

> When the last line would return an error instead of nil, I think that would then be more clear what goes wrong..

Please be more specific about what you are referring to.

**Comment by Hipska** [comment]
Oh, Didn't know this `func (d *Duration) UnmarshalTOML(b []byte) error` method was only used in tests. Why does it even exist then? It should be located in the `_test.go` file then IMHO.

It looks to me that method was created with the intention that it should be used to parse the global agent config toml durations. And according to the observed behaviour, it seems like it is indeed used.

The last line I was referring to, was the last line of the method we are talking about: https://github.com/influxdata/telegraf/blob/80d66dfed9ab71a8bf3c6bfbb48580ff5646652e/config/types.go#L53
I would change this to something like the following:
```go
return fmt.Errorf("could not parse '%s' as duration", b)
```

**Comment by powersj** [comment]
@Hipska Dave and I chatted and while it looks like UnmarhsalTOML isn't used, it actually is during the parsing. I put up #10734 which updates the logic of Unmarshal and adds some tests to catch this in the future.

**Comment by Hipska** [comment]
The updated logic looks correct, and should indeed resolve the agent ignoring settings it couldn't read..
