### ISSUE TITLE
Investigate code coverage

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#10733]
It would be helpful when doing reviews if we could understand the level of code coverage a PR has. Look into adding [codecov](https://github.com/marketplace/codecov), similar to the [flux](https://github.com/influxdata/flux/issues/1094) did.

Current CI runs tests run in parallel. That might conflict with running codecov.

**Comment by sspaink** [comment]
An internal influxdata project is using https://coveralls.io/, next steps is to look into how we can integrate it with Telegraf. Need to see what the approval process is.

**Comment by reimda** [comment]
For Telegraf PRs, we're often interested in coverage stats for the files in the plugin or the files changed in the PR. We may want to add a custom github action that finds these specific stats if coveralls or another existing tool doesn't do it for us.
