### ISSUE TITLE
Value parser: add option to set metric name

### ISSUE THREAD

**Issue by lesinigo** [influxdata/telegraf#10739]
## Feature Request

The [Value data format](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/value) seems to hardcode the field name to `value`, it would be nice to have an option to set a custom field name without resorting to processors or to the `json_v2` parser.

### Proposal:

Add an option to the parser to set the field name or improve documentation if there is already a way to achieve this that I failed to find.

### Current behavior:

Given input data:
```
123456
```

and input parser config:
```
name_override = "something"
data_format = "value"
data_type = "integer"
```

the output currently looks like:
```
something value=123456i 1645785334000000000
```

### Desired behavior:

I'd like a way to make the output look like:
```
something mycustomname=123456i 1645785334000000000
```

### Use case: 

When further aggregating or processing this metrics having different stuff with the same field name of `value` is confusing and error prone. Since the input configuration knows what it is reading, it seems like the logical place to set a meaningful field name.

**Comment by powersj** [comment]
Hi,

This was already done in #8979. Use the `value_field_name = "myfield"` option to set the field name. I have put up #10740 to add this to the docs.
