### ISSUE TITLE
Allow procstat to parse multiple pids in a pidfile

### ISSUE THREAD

**Issue by shubb30** [influxdata/telegraf#10736]
## Feature Request.
Some programs use a single pid file with multtiple PIDs separated by newlines

### Proposal:
Split the contents of the pidfile by `\n` and iterate over the results and create mettrics for each PID found.

### Current behavior:
Splunk, for example uses multiple PIDs in the same file.  When specifying the file, I get the following error:

```
2022-02-24T18:42:00Z E! [inputs.procstat] Error in plugin: strconv.ParseInt: parsing "466053\n466186\n466807\n466920\n539052\n652023\n657827\n663574\n664407": invalid syntax
```

### Desired behavior:
Each PID found in the pidfile should get metrics.

### Use case:
Splunk process monitoring, since Splunk spawns multiple processes off of the main process and has all PIDs in a single pid file.

**Comment by reimda** [comment]
Telegraf reads the file and converts it here: https://github.com/influxdata/telegraf/blob/5014d6b2b3b7d07d0bd4f0bcf74021d47c956a78/plugins/inputs/procstat/native_finder.go#L51

@shubb30 could you prepare a PR to change that function to read multiple PIDs?
