### ISSUE TITLE
Docker Plugin not finding Docker socket

### ISSUE THREAD

**Issue by hrzbrg** [influxdata/telegraf#1074]
Hi

after I updated a testing host from 0.11.1 to 0.12.1 the Docker plugin stopped working. The log shows:
```
Error in input [docker]: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

But when I run `telegraf -config /etc/telegraf/telegraf.conf -input-filter docker -test` it outputs the values to stdout. 

I also tried the most recent nightly, which produces the same error.

docker info is: 
```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 69
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 182
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
```

Regards
hrzbrg

**Comment by whetherharder** [comment]
Looks like permissions problem.
21.04.2016 12:11 пользователь "Sebastian" <notifications@github.com>
написал:

**Comment by sparrc** [comment]
try running as the telegraf user: `sudo -u telegraf telegraf -config /etc/telegraf/telegraf.conf -input-filter docker -test`

**Comment by hrzbrg** [comment]
okay, `sudo usermod -aG docker telegraf` solves it

**Comment by sparrc** [comment]
thanks for posting the solution @hrzbrg
