### ISSUE TITLE
[question] win_perf_counters starting telegraf when monitored process does not exist yet  

### ISSUE THREAD

**Issue by myontop** [influxdata/telegraf#1075]
```
[[inputs.win_perf_counters.object]]
    ObjectName = "Process"
	Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set"]
    Instances = ["my_process_name"]
    Measurement = "stats"
```

When I starting telegraf then process called my_process_name.exe not yet exists.
How to enforce on telegraf that when this process appear then it will report theirs counters.

Currently seems like telegraf validates cfg just once on startup

Should be fixed in your opinion?

The workaround is to use    Instances = ["*"] instead of    Instances = ["my_process_name"], but in this case influxdb is flooded by unnecessary data and also telegraf needs more CPU to gather counters

**Comment by myontop** [comment]
I would suggest to add an option
[[inputs.win_perf_counters.object]]
	**SkipValidation** = true


`if exists == win.ERROR_SUCCESS {
						if m.PrintValid {
							fmt.Printf("Valid: %s\n", query)
						}
						m.AddItem(metrics, query, objectname, counter, instance,
							PerfObject.Measurement, PerfObject.IncludeTotal)
					} else {
						if PerfObject.SkipValidation { //anyway add to counters!
							m.AddItem(metrics, query, objectname, counter, instance,
								PerfObject.Measurement, PerfObject.IncludeTotal)
							fmt.Printf("Added without validation: %s\n", query)
						}
						if PerfObject.FailOnMissing || PerfObject.WarnOnMissing {
							err := m.InvalidObject(exists, query, PerfObject, instance, counter)
							return err
						}
					}`

**Comment by sparrc** [comment]
If you put code in triple backticks (```) it makes it much easier to read

**Comment by sparrc** [comment]
I would rather not put in options for ignoring errors in plugins. I think there are other ways you can workaround this, or just ignore the log messages that come from failure to find the process.

**Comment by myontop** [comment]
I think your understanding is different. 
In different words the function which validates availability of counter works incorrectly because it assumes that the instance is all  time available which is not true.  There are counters where instances are appearing and disappearing on the runtime and the logger must be aware of this.
