### ISSUE TITLE
Telegraf agent support for Azure Arc enabled Servers

### ISSUE THREAD

**Issue by mukesh-dua** [influxdata/telegraf#10761]
## Feature Request
Telegraf agent support for Azure Arc connected Servers to push metrics to Azure Monitor

### Proposal:
Telegraf Agents work with Azure VMs as they get local metadata from IMDS service running within those VMs. With Arc for Servers, you get an HIMDS service running within VMs (created outside of Azure ecosystem). Telegraf agent should allow configuration to consume this local metadata service to fetch details and connect to Azure Monitor

### Current behavior:
Telegraf agent doesn't comes with a mechanism to configure local (Hybrid) IMDS endpoints and fails trying to find service at https://169.254.169.254. When the configuration is specified as mentioned on https://docs.microsoft.com/en-us/azure/azure-arc/servers/agent-overview#linux-agent-installation-details viz. IMDS_ENDPOINT and IDENTITY_ENDPOINT are specified in telegraf configuration, the service fails with error "Failed to start The plugin-driven server agent for reporting metrics into InfluxDB."

### Desired behavior:
Telegraf agents to gather metrics and push to Azure Monitor from an Arc enabled Server

### Use case: 
This feature is required for Microsoft product lines to consume telemetry from resources sitting outside Azure ecosystem.

**Comment by powersj** [comment]
Hi,

Can you be more specific as to what plugins you are using and want enabled to support Azure Arc? An actual config file would be very helpful.

Thanks
