### ISSUE TITLE
outputs.influxdb_v2 - add organization routing 

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#10778]
## Feature Request

Add the `organization_tag` to the options of the InflxDBv2 output plugin, to allow data-driven routing on different organizations.
The v1 plugin allows for full parametrization of the routing inside the influxDB instance, while v2 does not as it's missing the option for the organization.

### Proposal:
In [influxDB 1 output](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb) there are two routing options:
- `database_tag` - The value of this tag will be used to determine the database
- `retention_policy_tag` - The value of this tag will be used to determine the retention policy

those two options cover all the destination objects inside the instance itself, therefore you can have a flexible and full data driven routing

[influxDB 2 output](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb_v2) only has one:
- `bucket_tag` - The value of this tag will be used to determine the bucket

I know that a bucket is the replacement of DB+RP, and therefore it is the equivalent of the 2 options of v1, but needless to say, it does not cover all of the possible routings inside an Influx instance as there is also the organization.

The reasons are pretty simple:
- avoiding conf duplication (as of now you must replicate the `outputs.influxdb_v2` and use static `organization` and filter rules)
- avoiding (continuous) conf editing and service restarts

### Current behavior:
You can't have a full data-driven routing

### Desired behavior:
having a full data-driven routing by adding `organization_tag`

### Use case: 
Writing to a multi-organization InfluxDB instance will require less static code and config maintenance

**Comment by powersj** [comment]
Hi @Trovalo,

With InfluxDB 2, to be able to write across organizations requires the use of an [operator token](https://docs.influxdata.com/influxdb/v2.0/security/tokens/#api-token-types). This type of token is not creatable via the UI or API and is only created at the initial setup. It grants users access across all organizations. The best practice listed in the link above states that users should use an all-access token, which grants access to a single organization.

If Telegraf were to add the `organization_tag` it would require users to provide their operator token to write across different organizations. I am hesitant to allow this in Telegraf as the token [cannot be rotated](https://community.influxdata.com/t/creating-a-new-operator-token-influxdb-v2-0/20559) and InfluxDB practices discourage this use as well.

I realize this means users have to set up different configurations for each org and routing between outputs. However, the concerns around the token would lead to bad behavior.

Thoughts?

**Comment by Trovalo** [comment]
I was not aware of it, I'm still studying the differences between v1 and v2... tbh I gave it for granted (I'm used to relational DBMS) and I find this kind of limitation unusual. (I can say that v1 is way more similar to a classic RDBMS compared to v2).
I'm now evaluating a migration from v1 to v2 that's why I stumbled upon this routing "issue"

Today I played around with the v2 security part to understand it better, and the problem is that the token auth lacks instance-level permissions management.

The "structure three" between v1 and v2 does not seem that different at first sight... but it actually introduced several differences I was not expecting...
```
v2 structure
- Instance
  - Organizations
    - Buckets

v1 structure
- Instance
  - Databases
    - RPs 
```

**v1**
- You create users and GRANT them read/write permissions on DBs (or instance wide admin privilege) 

**v2**:
- Accessed using tokens (read/write on buckets), that are only organization scoped. the only exception is the "Operator Token" (to be used only for instance management)


practically speaking, it's not possible to access InfluxDB with a ReadOnly/WriteOnly **token** that is valid for multiple organizations (unless you use the "operator token", and that's a strong NO).
I've tried to achieve the above using [influx v1 auth](https://docs.influxdata.com/influxdb/v2.1/reference/cli/influx/v1/auth/), but it's impossible as the "authorization" (user) you create is still Organization scoped, and multiple "authorization" with the same name cannot exist.

#### Back to Telegraf
- Being unable to authenticate towards multiple Orgs with a single token makes the idea of the "organization_tag" kind of useless
- There are no possible workarounds

I guess that's it, from the Telegraf side there is nothing to do.

**Comment by powersj** [comment]
Hi @Trovalo,

I agree with the current state of things right now. I also agree that having this feature and use case could be very helpful. While I will close this issue for now, if you have not already, could I have you run this by the InfluxDB team in the #influxdb-v2 channel in Slack? 

Thanks again!

**Comment by Trovalo** [comment]
I'll try to propose/bring this to the slack channel... is that the main "feature proposal" platform? or could I try with a feature request on GitHub? (last time I've seen slack it was very crowded)

**Comment by powersj** [comment]
I think a GitHub feature request would be great as well, and would still ask you to mention it in the slack. Thanks again!

**Comment by Trovalo** [comment]
@powersj done, I've opened a feature request and also mentioned it in slack
