### ISSUE TITLE
Telegraf not fully quiet with --quiet argument

### ISSUE THREAD

**Issue by llowrey** [influxdata/telegraf#10775]
### Relevant telegraf.conf

```toml
n/a
```

### Logs from Telegraf

```
2022-03-03T18:25:18Z I! Starting Telegraf 1.21.4
```

### System info

Telegraf 1.21.4, Fedora 35

### Steps to reproduce

1. run `telegraf --once --quiet`
2.
3.
...

### Expected behavior

No output to console, either `stdout` or `stderr`, when no errors.

### Actual behavior

Telegraf emits one line to `stderr`:

```
2022-03-03T18:25:18Z I! Starting Telegraf 1.21.4
```

### Additional info

I am invoking `telegraf` at the end of backup jobs that are run by cron.  If the script emits anything on `stdout` or `stderr` cron will send an e-mail with the contents. I only want that to happen if there are actual errors.

**Comment by powersj** [comment]
This is already the case in master:

```
❯ ./telegraf --quiet --config config.toml 
^Ctelegraf on  master [?] via 🐹 v1.17.7
❯ ../telegraf-builds/telegraf-v1.21.4 --quiet --config config.toml 
2022-03-07T19:43:52Z I! Starting Telegraf 1.21.4
```

Closing as I don't think there is a need to do anything.

**Comment by llowrey** [comment]
It's broken again, with v1.26.0

I now get this:
```
2023-04-02T07:20:00Z I! Loading config file: /etc/telegraf/telegraf.d/influxdb_v2_output.conf
2023-04-02T07:20:00Z I! Loading config file: /dev/fd/63
```

It can be reproduced with something simple like:
```
]# telegraf --quiet --test --config net.conf
2023-04-02T15:48:45Z I! Loading config file: net.conf
> net,host=bar.#####.com,interface=eth1p0 bytes_recv=5397318197346i,bytes_sent=21141569243i,drop_in=0i,drop_out=0i,err_in=0i,err_out=0i,packets_recv=2877811851i,packets_sent=164236281i 1680450525000000000
```
