### ISSUE TITLE
Add more metrics to Couchbase Input plugin

### ISSUE THREAD

**Issue by Glusk** [influxdata/telegraf#10792]
## Feature Request
Currently, Couchbase [offers](https://docs.couchbase.com/server/current/cli/cbstats/cbstats-all.html) quite a lot more metrics than [Couchbase Input Plugin](https://github.com/influxdata/telegraf/tree/6fa29f29668c3b2d05adca9a6aafd43fb388d2c9/plugins/inputs/couchbase) supports. Perhaps it's time to update the plugin with more metrics.

For example, it would be nice to detect whether a cluster node is operational by tracking something like: `ep_degraded_mode`.

### Proposal:
Lets add more metrics to Couchbase Input Plugin.

### Current behavior:
You have to resort to various hacks to detect whether a cluster node has failed over or shut down. One way is to track per bucket RAM usage (`mem_used`) and look for any sudden drops.

### Desired behavior:
Read all metrics available by Couchbase.

### Use case: 
Gaining access to a larger set of Couchbase metrics simplifies monitoring.

**Comment by powersj** [comment]
Hi,

Thanks for the link of all the metrics. Would you be willing to determine what fields are missing that would be helpful beyond the two you listed above?

Thanks again
