### ISSUE TITLE
inputs.csgo -- TF2 (Team Fortress 2) support?

### ISSUE THREAD

**Issue by ipaqmaster** [influxdata/telegraf#10808]
## Feature Request

Allow inputs.csgo to support TF2 servers.

### Proposal:

Modify inputs.csgo to support tf2 as they run on the same engine (Granted a different version) and trying to use inputs.csgo on a TF2 server results in `E! [inputs.csgo] Error in plugin: bad response` despite using the correct port and rcon password.

Having peaked at csgo.go I suspect this may be possible with relatively minor support changes. It may even be plausible to rename inputs.csgo to inputs.srcds for all stats collection of all source based game servers, if version differences between titles aren't too vast.

### Current behavior:

`E! [inputs.csgo] Error in plugin: bad response` when configured appropriately against a tf2 server rather than a csgo one.

### Desired behavior:

Successful stats collection.

### Use case: 

Realtime TF2 server statistics in environments where quite a few instances are running. In my particular scenario I would like the stats in a Grafana dashboard.

**Comment by ipaqmaster** [comment]
Looking at one of the TF2 servers it was tried on, it appears to be running the `stats` command just fine:
```
CPU    In_(KB/s)  Out_(KB/s)  Uptime  Map_changes  FPS      Players  Connects
24.88  16.62      30.29       767     0            66.60    4        43      
rcon from "127.0.0.1:48022": command "stats"
```

I think the plugin is just expecting more data and is exiting with the "bad response" error early due to an output expectation from csgo servers which may differ slightly from TF2.

**Comment by powersj** [comment]
Happy to see a user put up an external plugin, but I don't see us taking this into the code base at this point.
