### ISSUE TITLE
Jolokia2 auth error

### ISSUE THREAD

**Issue by bryantlin** [influxdata/telegraf#10806]
I am using jolokia2 agent and the following is the authentication part in telegraf.conf.

> [[inputs.jolokia2_agent]]
urls = ["http://xx.xxx.xx.xxx:1111/jolokia"]
username = "test"
password = "test123"
name_prefix = "weblogic."

Below is the error message:

> Error in plugin: Unable to gather metrics for http://xx.xxx.xx.xxx:1111/jolokia: Response from url "http://xx.xxx.xx.xxx:1111/jolokia" has status code 403 (Forbidden), expected 200 (OK)

Is my way of specifying the credentials correct? I am sure the credentials works as I saw results when I accessed to the url from my local, entering the credentials. Is there any other reason resulting in the error?

Thanks!

**Comment by bryantlin** [comment]
Does anyone know the answer to my question above? Thanks.

**Comment by powersj** [comment]
> 403 (Forbidden)

As you noted this is HTTP code generally indicates that you can contact the server, but your login was rejected.

> Is my way of specifying the credentials correct?

They look correct to me and similar to the [examples](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2/examples)

The things I would check are:

* Ensure you are correctly using HTTP or HTTPS in your URL
* Verify the username/password once more
* Double-check for weird characters that might escape a value in the password (e.g. if you have a `/` character)
