### ISSUE TITLE
input powerdns requires write access to socket directory - E! [inputs.powerdns] Error in plugin: dial unix /var/run/pdns/pdns.controlsocket: connect: permission denied

### ISSUE THREAD

**Issue by emollusion** [influxdata/telegraf#10815]
Hi!

The input powerdns seems to require write access to the socket directory in order to be able to read from the socket.

( https://github.com/influxdata/telegraf/blob/release-1.21/plugins/inputs/powerdns )

PowerDNS version 4.5

Error:
```
# sudo -u telegraf telegraf --config /etc/telegraf/telegraf.d/telegraf_pdns.conf --input-filter powerdns --test
2022-03-14T15:32:22Z I! Starting Telegraf 1.21.4
2022-03-14T15:32:22Z I! Loaded inputs: powerdns
2022-03-14T15:32:22Z I! Loaded aggregators: 
2022-03-14T15:32:22Z I! Loaded processors: 
2022-03-14T15:32:22Z W! Outputs are not used in testing mode!
2022-03-14T15:32:22Z I! Tags enabled: host=****
2022-03-14T15:32:22Z E! [inputs.powerdns] Error in plugin: dial unix /var/run/pdns/pdns.controlsocket: connect: permission denied
2022-03-14T15:32:22Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

telegraf config:
```
[[inputs.powerdns]]
  ## An array of sockets to gather stats about.
  ## Specify a path to unix socket.
  unix_sockets = ["/var/run/pdns/pdns.controlsocket"]
```

Does not work:
```
# ls -all /var/run/pdns
total 0
drwxr-xr-x  2 pdns pdns   60 Mar 14 15:36 .
drwxr-xr-x 36 root root 1200 Mar 14 15:36 ..
srwxr-xr-x  1 pdns pdns    0 Mar 14 15:36 pdns.controlsocket
```

Does work:
```
# ls -all /var/run/pdns
total 0
drwxrwx---  2 pdns pdns   60 Mar 14 15:36 .
drwxr-xr-x 36 root root 1200 Mar 14 15:36 ..
srwxr-xr-x  1 pdns pdns    0 Mar 14 15:36 pdns.controlsocket
```

With the same command then giving output:
```
# sudo -u telegraf telegraf --config /etc/telegraf/telegraf.d/telegraf_pdns.conf --input-filter powerdns --test
2022-03-14T15:33:03Z I! Starting Telegraf 1.21.4
2022-03-14T15:33:03Z I! Loaded inputs: powerdns
2022-03-14T15:33:03Z I! Loaded aggregators: 
2022-03-14T15:33:03Z I! Loaded processors: 
2022-03-14T15:33:03Z W! Outputs are not used in testing mode!
2022-03-14T15:33:03Z I! Tags enabled: host=****
> powerdns,host=****,server=/var/run/pdns/pdns.controlsocket backend-queries=0i,corrupt-packets=0i,cpu-iowait=440025i,cpu-steal=40964i,deferred-cache-inserts=0i,deferred-cache-lookup=0i,deferred-packetcache-inserts=0i,deferred-packetcache-lookup=0i,dnsupdate-answers=0i,dnsupdate-changes=0i,dnsupdate-queries=0i,dnsupdate-refused=0i,fd-usage=24i,incoming-notifications=0i,key-cache-size=0i,latency=0i,meta-cache-size=0i,noerror-packets=0i,nxdomain-packets=0i,open-tcp-connections=0i,overload-drops=0i,packetcache-hit=0i,packetcache-miss=0i,packetcache-size=0i,qsize-q=0i,query-cache-hit=0i,query-cache-miss=0i,query-cache-size=0i,rd-queries=0i,real-memory-usage=61353984i,recursing-answers=0i,recursing-questions=0i,recursion-unanswered=0i,ring-logmessages-capacity=10000i,ring-logmessages-size=4i,ring-noerror-queries-capacity=10000i,ring-noerror-queries-size=0i,ring-nxdomain-queries-capacity=10000i,ring-nxdomain-queries-size=0i,ring-queries-capacity=10000i,ring-queries-size=0i,ring-remotes-capacity=10000i,ring-remotes-corrupt-capacity=10000i,ring-remotes-corrupt-size=0i,ring-remotes-size=0i,ring-remotes-unauth-capacity=10000i,ring-remotes-unauth-size=0i,ring-servfail-queries-capacity=10000i,ring-servfail-queries-size=0i,ring-unauth-queries-capacity=10000i,ring-unauth-queries-size=0i,security-status=1i,servfail-packets=0i,signature-cache-size=0i,signatures=0i,sys-msec=220i,tcp-answers=0i,tcp-answers-bytes=0i,tcp-queries=0i,tcp4-answers=0i,tcp4-answers-bytes=0i,tcp4-queries=0i,tcp6-answers=0i,tcp6-answers-bytes=0i,tcp6-queries=0i,timedout-packets=0i,udp-answers=0i,udp-answers-bytes=0i,udp-do-queries=0i,udp-in-errors=0i,udp-noport-errors=3646i,udp-queries=0i,udp-recvbuf-errors=0i,udp-sndbuf-errors=0i,udp4-answers=0i,udp4-answers-bytes=0i,udp4-queries=0i,udp6-answers=0i,udp6-answers-bytes=0i,udp6-queries=0i,unauth-packets=0i,uptime=675i,user-msec=158i,xfr-queue=0i,zone-cache-hit=0i,zone-cache-miss=0i,zone-cache-size=5i 1647271984000000000
```

PowerDNS does not seem to support setting specific socket mode like PowerDNS Recursor, and after service restart the ownership of the directory is reset back to 755.

Am I doing something wrong or is it the plugin?

Thank you!

**Comment by emollusion** [comment]
Yes, the user telegraf has group pdns.
This also corresponds to the working example above where the directory is group writeable, not world read nor write.

**Comment by emollusion** [comment]
I have not found any reference in the [PowerDNS settings](https://doc.powerdns.com/authoritative/settings.html) for socket-mode, only [socket-dir](https://doc.powerdns.com/authoritative/settings.html#socket-dir).
I tested the corresponding setting for PowerDNS as stated for the Recursor, socket-mode, but PowerDNS did not like this and refused to start. Was worth a shot...

**Comment by ShamimShahraeini** [comment]
Hey there, 

I've got the same issue (pdns v4.3 and then upgraded to v4.5 and telegraf v1.23); The ` connect: permission denied` error for the socket, is shown when I try to run the service with `telegraf` user; although I used `usermod telegraf -a -G pdns`!  

![image](https://user-images.githubusercontent.com/50511017/185733100-681e84d3-2660-403c-807b-c4d72c141fee.png)


I also tried to use `socket_mode` and `socket_dir`, but it sounds the pdns authoritative plugin doesn't support it and it couldn't start:
![image](https://user-images.githubusercontent.com/50511017/185733276-00bd5c0d-8914-4c01-9f71-329187ee2ae0.png)

**Comment by Hipska** [comment]
@ShamimShahraeini That error seems to come from telegraf, but not from pdns? Did you configure this correctly?

**Comment by marcinliszka12** [comment]
I have the same. PDNS 4.8.2-1 Debian 11.7. Only chmod g+w /var/run/pdns/pdns.controlsocket fix it temporary till pdns next restart

**Comment by aderumier** [comment]
@powersj 
socket-mode only works with powerdns recursor, but don't exist in authoritative.

telegraf inputs.powerdns is about authoritative mode.

**Comment by powersj** [comment]
@aderumier,

If you have something that can aid users, then I would appreciate a new issue and not commenting on a closed one.

> socket-mode only works with powerdns recursor, but don't exist in authoritative.
> 
> telegraf inputs.powerdns is about authoritative mode.

If that is true, then why does the plugin attempt to connect via the socket and even state the following in the readme:

> The powerdns plugin gathers metrics about PowerDNS using unix socket.

Is this due to a change in powerdns? Or has this never worked.

**Comment by aderumier** [comment]
> @aderumier,
> 
> If you have something that can aid users, then I would appreciate a new issue and not commenting on a closed one.
> 
> > socket-mode only works with powerdns recursor, but don't exist in authoritative.
> > telegraf inputs.powerdns is about authoritative mode.
> 
> If that is true, then why does the plugin attempt to connect via the socket and even state the following in the readme:
> 
> > The powerdns plugin gathers metrics about PowerDNS using unix socket.
> 
> Is this due to a change in powerdns? Or has this never worked.

Hi, it was working for me on powerdns 4.1 (on debian 10), the permissions on socket was ok for group.

on powerdns 4.8 (from powerdns repo on debian12), the group don't have write permissions.

and we can't change the permissions with socket-mode for authoritative powerdns. (this option is only valid with recursor powerdns)

The only working workaround for me is:
"ExecStartPost=/bin/chmod g+w /var/run/pdns/pdns.controlsocket"

https://github.com/influxdata/telegraf/issues/10815#issuecomment-1727194404
