### ISSUE TITLE
Azure Monitor  failed to write batch: [400] 400 Bad Request

### ISSUE THREAD

**Issue by dfoxvt** [influxdata/telegraf#10875]
At present azure have just changed the TLS version and now getting Azure Monitor failed to write batch: [400] 400 Bad Request. I only install the telegraf agent and not the influxDB. Is there a way you can set the TLS minimum version if you are only using the azure to push data to azure monitor ?
Disabling the net capture resolves this.

**Comment by Hr0bar** [comment]
We are currently experiencing the same error, but checking more detailed logs with https://github.com/influxdata/telegraf/pull/10866 revealed the cause may be with Azure US west having some weird issues that we did not pinpoint exactly yet  (cert for westus.monitoring.azure.com was also changed/renewed last week btw):

 [agent] Error writing to outputs.azure_monitor: failed to write batch: [400] 400 Bad Request ResponseBody: {"error":{"code":"RegionMismatch","message":"This endpoint : westus.monitoring.azure.com does not accept metrics for the resource's region : westus. Ensure you are sending to the correct regional endpoint."}}

By any chance are you using Azure US west too ? We do not experience the issue on any other Azure regions.

**Comment by dfoxvt** [comment]
No currently using US west but this is happening for us in UK South and North Europe
