### ISSUE TITLE
Fix plugin filters when using `telegraf config`

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#10888]
The following command currently doesn't work:
`telegraf config --input-filter cpu --output-filter influxdb`

Instead you have to use `telegraf --input-filter cpu --output-filter influxdb config`

Telegraf should be updated to have the command be at the beginning

`--sample-config` should probably be deprecated as well in favor of config

Related to: #10831

### Steps to reproduce

Run `telegraf config --input-filter cpu --output-filter influxdb `
Nothing gets filtered 

### Expected behavior

Plugins get filtered

### Actual behavior

Plugins aren't filtered

**Comment by powersj** [comment]
next steps: look into what change may have caused this, as it was previously working
