### ISSUE TITLE
logfile rotation interval: "0d" default fails to start Telegraf v1.22.0

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#10882]
### Relevant telegraf.conf

```toml
[agent]
  logfile_rotation_interval = "0d"
```

### Logs from Telegraf

```
2022-03-24T13:34:48Z E! [telegraf] Error running agent: Error loading config file config.toml: error parsing [agent]: line 3: (config.AgentConfig.LogfileRotationInterval) time: unknown unit "d" in duration "1d"
```

### System info

v1.22.0

### Steps to reproduce

1. As a part of v1.22.0, the parsing of durations was made more strict. This was after discovering that the durations were silently failing to be set in fields like precision, or even interval.
2. Set the `logifle_rotation_interval` to the default of `0d`
3. Telegraf will fail to start as `d` is not a valid [time.Duration unit](https://pkg.go.dev/time#ParseDuration).
4. In previous releases, setting this value to `1d` for what a user might assume is equivalent to `24h` would not work and would fail silently and set it to 0 instead.

### Expected behavior

Default config with a correct, working setting

### Actual behavior

Default setting, if uncommented will prevent telegraf from starting

### Additional info

A good way to show that using values with `d` for day in them fail is to try an older release and set the `interval` option to `1d`. A user would expect Telegraf to run once a day with that setting however the log messages show it silently is ignored:

```
❯ cat config.toml 
[agent]
  interval = "1d"
[[outputs.file]]
[[inputs.cpu]]
❯ ../telegraf-builds/telegraf-v1.21.4 --config config.toml --debug
2022-03-24T13:43:31Z I! Starting Telegraf 1.21.4
2022-03-24T13:43:31Z I! Loaded inputs: ethtool
2022-03-24T13:43:31Z I! Loaded aggregators: 
2022-03-24T13:43:31Z I! Loaded processors: 
2022-03-24T13:43:31Z I! Loaded outputs: file
2022-03-24T13:43:31Z I! Tags enabled: 
2022-03-24T13:43:31Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
```

However, setting `interval` to `24h` works as expected:

```
2022-03-24T13:45:16Z I! [agent] Config: Interval:24h0m0s, Quiet:false, Hostname:"", Flush Interval:10s
```

**Comment by srebhan** [comment]
Maybe we should really allow for `d` being a valid suffix especially for stuff like log-rotation?

**Comment by powersj** [comment]
> Maybe we should really allow for d being a valid suffix especially for stuff like log-rotation?

Here is my reasoning for not doing that:

- This has been broken and silently failing for nearly three years. I have looked through old issues and I have yet to find one.
- The fix I put in that made the failure more explicit was after a user noticed Telegraf was silently failing to parse incorrect parameters in the first place. 
- I do not think we should maintain logic for something that never worked in the first place

I can see an argument for ensuring prior config worked, in which case, we could check if the value was "0d" and change the value to "0h" in the event someone had uncommented the field. That way existing users of the default are not broken.

Thoughts?

**Comment by srebhan** [comment]
Actually we had these issues but never associated it with this, e.g. #6888 and I'm actually seeing the exact same issue with "not working log-rotation" on one of our systems. It's just that I never would have guessed it's the interval parsing. ;-)

Currently, I'm only seeing log-rotation where "days" make sense as it is a bit cumbersome to work with "168h"... :-)

**Comment by Hipska** [comment]
After seeing another user having this issue after upgrade of telegraf, I also think we should support `%fd` prefix of the duration string for logfile. At least only as a backward compatibility mode with deprecation warning..
