### ISSUE TITLE
Upgrade json_name_key from String to Array of Strings

### ISSUE THREAD

**Issue by vviswadeep** [influxdata/telegraf#10891]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 
As of now the json_name_key supports only string values. If this supports a combination of keys that would help the name to be more Unique

### Current behavior: 
The name can be configured from the value of a single key in the json input

### Desired behavior: 
Name should be configured from the values of multiple keys in the json input

### Use case: 

The Use case for this request is when we consider increased number of integrations with the Telegraf from the OPCUA. 

This [article ](https://www.influxdata.com/blog/telegraf-best-practices/)shows using Buckets as a way to classify and store the data depending on the type of origin of the Information (If it is a Sensor related information it needs to go to the Sensor Bucket) 

When we can configure the name with multiple keys, the exact origin would help to compare and study the behavior of the same time of sensor in a differently installed location. 

This feature helps in sorting of the data in multiple aspects.

**Comment by powersj** [comment]
Closing as the option provided above is preferred.
