### ISSUE TITLE
OPC UA input plugin do not write the optional tags in influx v1.x

### ISSUE THREAD

**Issue by zeldalegends** [influxdata/telegraf#10898]
### Relevant telegraf.conf

```toml
From https://github.com/sjwang90/telegraf/blob/master/plugins/inputs/opcua/README.md:

  ## {name="ProductUri", namespace="0", identifier_type="i", identifier="2262", tags=[["tag1","value1"],["tag2","value2]]}

Please notice that there is an error in the documentation: "value2 should be "value2" (last " missing)

Of course, decommented and put in my telegraf.conf with also an output plugin for influx 1.x
```

### Logs from Telegraf

```text
No errors
```

### System info

last version

### Steps to reproduce

1. Run Telegraf with an output plugin to an influx v1.x and an opc ua input plugin with a node like in the (corrected) example: 
2. {name="ProductUri", namespace="0", identifier_type="i", identifier="2262", tags=[["tag1","value1"],["tag2","value2"]]}
3. Run Chronograf, explore the db and the measurement written
4. No tag1 nor tag2 is written
...

### Expected behavior

tag1 and tag2 should be written showing "value1" and "value2"

### Actual behavior

Neither tag1 nor tag2 appears and is written

**Comment by powersj** [comment]
Hi,

Can you please gather the following:

1) Can you please provide your Telegraf logs and Telegraf config?
2) Can you run with the `[[outputs.file]]` option to provide that output?

Thanks
