### ISSUE TITLE
Centos Stream 9: error getting disk usage ("/sys/kernel/debug/tracing"): permission denied

### ISSUE THREAD

**Issue by shorton3** [influxdata/telegraf#10897]
### Relevant telegraf.conf

```toml
Migrating from Centos 7 to Centos Stream 9, and I am seeing this log when Telegraf runs:

Mar 25 23:09:00 nxtdrp032522-d-centos-stream9 telegraf[927]: 2022-03-25T23:09:00Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/sys/kernel/debug/tracing"): permission denied

Any guidance please?
```

### Logs from Telegraf

```text
Mar 25 23:09:00 nxtdrp032522-d-centos-stream9 telegraf[927]: 2022-03-25T23:09:00Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/sys/kernel/debug/tracing"): permission denied
```

### System info

telegraf-1.22.0-1.x86_64

### Steps to reproduce

1.start telegraf and look in /var/log/messages
2.
3.
...

### Expected behavior

no permission denied logs

### Actual behavior

permission denied logs

**Comment by CalvinSchwartz** [comment]
Same Issue on Raspbian (64bit) on Raspberrypi,  Kernel: 5.10.103-v8+:
'[inputs.disk] [SystemPS] => error getting disk usage ("/run/docker/netns/XXXXXXXXXX"): permission denied'

**Comment by arestifo** [comment]
Same here on Ubuntu 20.04.4 using `Telegraf 1.22.0 (git: HEAD 80a7feb8)` 
uname -a: 
`Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

telegraf output:
` E! [inputs.disk] [SystemPS] => error getting disk usage ("/hostfs/run/docker/netns/XXXXXXXXXX"): permission denied`

**Comment by aratik711** [comment]
@shorton3 @CalvinSchwartz  @arestifo https://access.redhat.com/solutions/5914171
Can you check if it is related to the above
@srebhan not sure if there is anything we can do in this case, Please suggest

**Comment by rwb196884** [comment]
This is happening on Debian `4.19.0-18-amd64` after upgrading via `apt`:
```
Upgrade: telegraf:amd64 (1.21.4-1, 1.22.0-1), ...
```

```
...
Mar 28 11:02:40 mini31 telegraf[13116]: 2022-03-28T10:02:40Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/sys/kernel/debug/tracing"): permission denied
```

**Comment by powersj** [comment]
@reimda it looks like in #10527  you changed a [debug to an error](https://github.com/powersj/telegraf/commit/6ef39deda1b8fe1f587d671cbd9c802dc32d885a#diff-8b5b8537f5ed74417dff77ae61825a839140f430d7ff441b153d0abc743597b8L148), which is causing these messages to show up now. 

As an example, on my local system with no configuration of `[[inputs.disk]]` I get these two messages:

```
2022-03-28T14:37:37Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/var/lib/docker/btrfs"): permission denied
2022-03-28T14:37:37Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/run/user/1000/doc"): operation not permitted
```

This does not stop the plugin from correctly collecting data, only produces the above messages. Running on older versions does not produce such a message without `--debug`.

Should this message get switched back to a debug?

Thanks!

**Comment by alsitn** [comment]
> Same Issue on Raspbian (64bit) on Raspberrypi, Kernel: 5.10.103-v8+: `[inputs.disk] [SystemPS] => error getting disk usage ("/run/docker/netns/XXXXXXXXXX"): permission denied`

You have to add telegraf to dkcer group --> usermod -aG docker telegraf

**Comment by reimda** [comment]
In plugins/input/system/ps.go https://github.com/powersj/telegraf/blob/b9e66f8b9a2d97e09a7e2c1ff5b2bc08bc4eeebc/plugins/inputs/system/ps.go#L157 It looks like we need to be more careful about the log level we're using. I switched everything from debug level to error level, but a 'permission denied' should be a warning as it doesn't cause the plugin to stop working, and only makes it stop producing metrics for the filesystem involved.

**Comment by tagobar** [comment]
> Same here on Ubuntu 20.04.4 using `Telegraf 1.22.0 (git: HEAD 80a7feb8)` uname -a: `Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
> 
> telegraf output: ` E! [inputs.disk] [SystemPS] => error getting disk usage ("/hostfs/run/docker/netns/XXXXXXXXXX"): permission denied`

Same problem with telegraf 1.22.0-1 on clean Debian 11

**Comment by rowansmithau** [comment]
added `tracefs to `ignore_fs` parameter for inputs.disk and seems quiet so far.

**Comment by powersj** [comment]
I have put up #10925 which will reduce the error message to a warning and correctly add tracefs to the list of default ignored filesystem types. If anyone has time, it would be great if you could download a build artifact and ensure the messages look right.

Thanks!

**Comment by nferch** [comment]
I have a similar problem, but the difference is that the problem is occurring on bind mounts that Nomad is creating:

`Apr 11 19:06:00 rumours telegraf[24175]: 2022-04-11T19:06:00Z E! [inputs.disk] [SystemPS] => error getting disk usage ("/var/lib/nomad/alloc/7e95d8a6-db75-b3d3-28d1-d2703df5a017/log-shipper/alloc"): permission denied`

```
#findmnt | grep /var/lib/nomad/alloc/7e95d8a6-db75-b3d3-28d1-d2703df5a017/log-shipper/alloc                      
├─/var/lib/nomad/alloc/7e95d8a6-db75-b3d3-28d1-d2703df5a017/log-shipper/alloc                     /dev/sda[/var/lib/nomad/alloc/7e95d8a6-db75-b3d3-28d1-d2703df5a017/alloc] ext4        rw,noatime,errors=remount-ro
```

Is there any current way to exclude these?

**Comment by aladrin** [comment]
i had to add "fuse.gvfsd-fuse" to my ignores on xfce

**Comment by 0xTH0R** [comment]
I'm getting error permission denied from my second mount point which is inside my work directory but i have try to debug with `telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter disk --test` the result is correct.

Also, i have checked the file permission on host and inside container it is root as the same.

<img width="1063" alt="Screenshot 2567-01-08 at 15 28 24" src="https://github.com/influxdata/telegraf/assets/106047315/a5bbd9e5-a34f-47b3-a2bd-bdc649cb60c5">

<img width="398" alt="Screenshot 2567-01-08 at 15 37 11" src="https://github.com/influxdata/telegraf/assets/106047315/b61c8a01-3515-404d-af6c-8d4532acd810">

I'm not sure if it is the same case with this issue?

**Comment by srebhan** [comment]
@0xTH0R is this a nested mount? If so, can you please open a new issue?

**Comment by rwb196884** [comment]
Same problem on Debian 12 and adding `tempfs` has reduced but not stopped the log spam.

It seems that the thing in brackets is a file system location that corresponds to something in `/proc/mounts`.

It's now complaining about
```
/run/credentials/systemd-tmpfiles-setup.service
```
but `/run` has file system type `tmpfs` which is in `ignore_fs`.
Thereofre I think that this is a bug that `telegraf` is not actually ignoring what's in `ignore_fs`.

**Comment by srebhan** [comment]
@rwb196884 please open a new issue with the information above and an (redacted) excerpt of the log.

**Comment by Coromilly** [comment]
> I'm getting error permission denied from my second mount point which is inside my work directory but i have try to debug with `telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter disk --test` the result is correct.
> 
> Also, i have checked the file permission on host and inside container it is root as the same.
> 
> <img alt="Screenshot 2567-01-08 at 15 28 24" width="1063" src="https://private-user-images.githubusercontent.com/106047315/294846877-a5bbd9e5-a34f-47b3-a2bd-bdc649cb60c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjY1OTYsIm5iZiI6MTcyNDMyNjI5NiwicGF0aCI6Ii8xMDYwNDczMTUvMjk0ODQ2ODc3LWE1YmJkOWU1LWEzNGYtNDdiMy1hMmJkLWJkYzY0OWNiNjBjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxMTMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjU5YmE4MDU5OGM0MGVlMWY4MjAwNTZkYjVlMjRlNTZjZmI0Y2ZlMWI3Yjg3YzFiNzkyMjFhNDJjOTE1YTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q2wGrN4yb5Js3a4UKkU7r8zW7E1usDOz64_VlySXhng"> <img alt="Screenshot 2567-01-08 at 15 37 11" width="398" src="https://private-user-images.githubusercontent.com/106047315/294846885-b61c8a01-3515-404d-af6c-8d4532acd810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjY1OTYsIm5iZiI6MTcyNDMyNjI5NiwicGF0aCI6Ii8xMDYwNDczMTUvMjk0ODQ2ODg1LWI2MWM4YTAxLTM1MTUtNDA0ZC1hZjZjLThkNDUzMmFjZDgxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxMTMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTVlNDFjZTQ3YzNkYmQwZTc5YmVkOThhODE4MjQ3OGRmNGE1NTUwNzU1MmEzMjRjZjc2YWVmZGZlYjhjMDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1rHIBHmWWyqVCdOVzkunBYRniglIucU-Ambi2t2AfgU">
> I'm not sure if it is the same case with this issue?

Your debug command is not correct, you shoud specify telegraf user:

```shell
sudo -u telegraf telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter disk --test
```

**Comment by Sarke** [comment]
> so adding `ramfs` to `ignore_fs` got rid of those.

I am also on Debian 12 and got the same error, but adding `ramfs` didn't work for me.  I still see the same debug errors.

```toml
[[inputs.disk]]
  ignore_fs = ["ramfs", "tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs", "vfat", "nfs4"]
```

```
Telegraf 1.33.3 (git: HEAD@9e67377d)
```

**Comment by srebhan** [comment]
Guys please open a new issue and do not post on a closed one!
