### ISSUE TITLE
telegraf for windows - [inputs.sqlserver] Set deadlock priority to LOW

### ISSUE THREAD

**Issue by asterix67** [influxdata/telegraf#10908]
Hello,
I use telegraf 1.22.0 for windows.
I have few deadlock.

When I trace telegraf's queries, I see  all queries dont use SET DEADLOCK_PRIORITY -10
Only queries SQLServerPerformanceCounters and SQLServerDatabaseIO do "SET DEADLOCK_PRIORITY -10"

Personnally, iI use queries SQLServerRequests, SQLServerVolumeSpace, SQLServerCpu, SQLServerProperties, SQLServerMemoryClerks and it make deadlocks.

**Comment by powersj** [comment]
next steps: look into adding `SET DEADLOCK_PRIORITY -10;` to all queries.

**Comment by asterix67** [comment]
Sorry, I'm french and beginner with github :).


> next steps: look into adding `SET DEADLOCK_PRIORITY -10;` to all queries.

I dont understand.
Where I must look ?

**Comment by asterix67** [comment]
Thank you for your answer.

I'm waiting a next version of telegraf for windows (actually i have 1.2.2).

**Comment by powersj** [comment]
Hi,

>  Do you know if the next version will use SET DEADLOCK_PRIORITY -10 ?

Once this issue is closed it will show up in our next release.

**Comment by SteveKnowless** [comment]
This would be helpful for me as I am also running into this issue when restoring databases to my QA and Development Environments. Thanks for all your help with this

**Comment by tesibelda** [comment]
[inputs.sqlserver] Set deadlock priority to LOW #4988

**Comment by asterix67** [comment]
Hi,
I saw this similar issue.
But it's not solved in windows platform.

In linux platform, we can modify "[plugins/inputs/sqlserver/sqlserver.go]" file to add "SET DEADLOCK_PRIORITY -10;" in each queries.
But in windows platform, this no .go files.

> As a reference, a similar issue that was temporarily solved in previous versions: [inputs.sqlserver] Set deadlock priority to LOW #4988

**Comment by powersj** [comment]
#11522 added these priorities, this will go out in the next bug fix release, v1.23.3 possibly next week.
