### ISSUE TITLE
Does Telegraf use proper license for github.com/eclipse/paho.mqtt.golang dependency?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#10917]
### Relevant telegraf.conf

```toml
not relevant
```

### Logs from Telegraf

```text
not relevant
```

### System info

not relevant

### Docker

not relevant

### Steps to reproduce

1. Check https://github.com/eclipse/paho.mqtt.golang/blob/master/LICENSE to see that this dependency is dual-licensed. It is distributed under `Eclipse Public License` (which seems to be copyleft license) and `Eclipse Distribution License` (which doesn't seem to be viral).
2. Check `github.com/eclipse/paho.mqtt.golang` in https://github.com/influxdata/telegraf/blob/32222d96ce0841fdbd745f4c635980f0d92bc7c1/docs/LICENSE_OF_DEPENDENCIES.md?plain=1#L89

### Expected behavior

1. `github.com/eclipse/paho.mqtt.golang` in https://github.com/influxdata/telegraf/blob/32222d96ce0841fdbd745f4c635980f0d92bc7c1/docs/LICENSE_OF_DEPENDENCIES.md?plain=1#L89 should use `Eclipse Distribution License`

### Actual behavior

1. `github.com/eclipse/paho.mqtt.golang` in https://github.com/influxdata/telegraf/blob/32222d96ce0841fdbd745f4c635980f0d92bc7c1/docs/LICENSE_OF_DEPENDENCIES.md?plain=1#L89 uses `Eclipse Public License - v 1.0`

**Comment by sjwang90** [comment]
@zak-pawel Have brought this up with our legal team. Will hopefully get an answer soon.

**Comment by sspaink** [comment]
Looks like the library has moved to a new license: https://github.com/eclipse/paho.mqtt.golang/blob/master/LICENSE
`Eclipse Public License - v 2.0 (EPL-2.0)` which we are using already, maybe this resolves this issue?

**Comment by zak-pawel** [comment]
@sspaink `Eclipse Public License - v 2.0 (EPL-2.0)` seems to be also copyleft license. 

@sjwang90 Did you get any answer from legal team? Cannot we just switch to `Eclipse Distribution License` in our `LICENSE_OF_DEPENDENCIES.md` file

**Comment by sjwang90** [comment]
Legal is fine with we using copyleft licenses. Our legal team will need to work on listing out all our third party dependencies in the near future but using the EPL license is fine.
