### ISSUE TITLE
Post install script fails on CentOS 5

### ISSUE THREAD

**Issue by adithyabenny** [influxdata/telegraf#1091]
[This] (https://github.com/influxdata/telegraf/blob/master/scripts/post-install.sh#L29) line fails, due to which the `telegraf` user doesn't get added.

It happens cause of `useradd` binary in Centos 5, which doesn't contain certain options.
If the `--system` flag is replaced with `-r`, and `-U` is replaced with `-K USERGROUPS_ENAB=yes`, it works fine across all CentOS versions.

**Comment by sparrc** [comment]
thanks for the report, could you submit a PR?

**Comment by adithyabenny** [comment]
[Done] (https://github.com/influxdata/telegraf/pull/1094)
