### ISSUE TITLE
Error in opcua configuration  (0x80110000)

### ISSUE THREAD

**Issue by anve96** [influxdata/telegraf#10919]
Hi, I am trying to fetch data from an opcua node but when I run the telegraf test I get this error :
  E! [inputs.opcua] status not OK for node TempBearingGearbox: The extension object cannot be (de)serialized because the data type id is not recognized. StatusBadDataTypeIDUnknown (0x80110000).
The opcua configuration is this one  nodes = [
     {name="TempBearingMainDrive", namespace="6", identifier_type="s", identifier="::AsGlobalPV:Signal.BER.TempBearingMainDrive"},
     {name="TempBearingGearbox", namespace="6", identifier_type="s", identifier="::AsGlobalPV:Signal.BER.TempBearingGearbox"},
   ]
Does anyone know what did I do wrong ?
Thank you.

**Comment by R290** [comment]
Did you try requesting similar nodes with software like [UaExpert](https://www.unified-automation.com/products/development-tools/uaexpert.html)? What does it return? And could you post the full Telegraf log with the error?
