### ISSUE TITLE
Environment variable not interpreted in telegraf.conf for lists

### ISSUE THREAD

**Issue by Neferites** [influxdata/telegraf#10922]
### Relevant telegraf.conf

```toml
[[inputs.vsphere]]
  vcenters = [ "https://my-vc.local/sdk" ]
  username = "telegraf@vsphere.local"
  password = "**********"
  
  ## Vm
  vm_metric_include = ["${VM_METRICS_INCLUDE}"]
  vm_metric_exclude = ["${VM_METRICS_EXCLUDE}"]
  
  ## Hosts
  host_metric_include = ["{$HOST_METRICS_INCLUDE}"]
  host_metric_exclude = ["{$HOST_METRICS_EXCLUDE}"]

  host_instances = true ## true by default

  ## Clusters
  cluster_metric_exclude = ["*"] ## Nothing excluded by default
  cluster_instances = false ## true by defalt

  ## Datastores
  datastore_metric_exclude = ["*"] ## Nothing excluded by default
  datastore_instances = false ## false by default for Datastores only

  ## Datacenters
  datacenter_metric_exclude = ["*"] ## Datacenters are not collected by default.
  datacenter_instances = false ## false by default for Datastores only

  max_query_objects = 256

  collect_concurrency = 5
  discover_concurrency = 10

  timeout = "120s"
  insecure_skip_verify = true
```

### Logs from Telegraf

```text
root@94bf9af5b850:/etc/telegraf/telegraf.d# telegraf --config /etc/telegraf/telegraf.d/vsphere.conf --test
2022-03-31T10:30:48Z I! Starting Telegraf 1.21.4
2022-03-31T10:30:48Z I! Loaded inputs: vsphere
2022-03-31T10:30:48Z I! Loaded aggregators: 
2022-03-31T10:30:48Z I! Loaded processors: 
2022-03-31T10:30:48Z W! Outputs are not used in testing mode!
2022-03-31T10:30:48Z I! Tags enabled: host=94bf9af5b850
2022-03-31T10:30:48Z I! [inputs.vsphere] Starting plugin
2022-03-31T10:30:48Z W! [inputs.vsphere] Metric name "cpu.ready.summation", "cpu.usagemhz.average", "cpu.maxlimited.summation", "cpu.usage.average", "cpu.readiness.average", "cpu.demandEntitlementRatio.latest", "cpu.entitlement.latest", "cpu.costop.summation", "mem.active.average", "mem.usage.average", "virtualDisk.numberReadAveraged.average", "virtualDisk.numberWriteAveraged.average", "virtualDisk.totalReadLatency.average", "virtualDisk.totalWriteLatency.average", "sys.osUptime.latest", "net.droppedRx.summation", "net.droppedTx.summation", "net.bytesTx.average", "net.bytesRx.average", "mem.swapped.average" is unknown. Will not be collected
2022-03-31T10:30:48Z I! [inputs.vsphere] Stopping plugin
```

### System info

Telegraf 1.23.5, Docker 20.10.3, Debian 10.7

### Steps to reproduce

1. Source env from file
2. Run telegraf in test mode : telegraf --config /etc/telegraf/telegraf.d/vsphere.conf
...

### Expected behavior

Telegraf should collect metrics from vm on vcenter

### Actual behavior

Metrics are not collected

### Additional info
Hi everyone,
I tried to simplify vsphere.conf using variables, cause i need to pull metrics from many vcenters, with unique credentials.
I used this feature : https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#example-telegraf-environment-variables, but this is not working for list.

I tried many env format like : 
```
export VM_METRICS_INCLUDE="cpu.ready.summation, cpu.usagemhz.average"
export VM_METRICS_INCLUDE="\"cpu.ready.summation\", \"cpu.usagemhz.average\""
export VM_METRICS_INCLUDE="\[\"cpu.ready.summation\", \"cpu.usagemhz.average\"\]"
export VM_METRICS_INCLUDE='["cpu.ready.summation","cpu.usagemhz.average"]'
export VM_METRICS_INCLUDE='"cpu.ready.summation", "cpu.usagemhz.average"'
```

The only workaround i found is to create a variable per metrics, and use it like this : 
```vm_metric_include = ["${VM_METRICS_1}", "${VM_METRICS_2}", and so on]```

Is there any solution to use environment vars, without toml error, or bad metrics ?
Regards

**Comment by reimda** [comment]
There is a unit test related to the environment variables in toml and a corresponding test input file
https://github.com/influxdata/telegraf/blob/master/config/testdata/single_plugin_env_vars.toml

They don't have a case for initializing a list with the contents of an environment variable like you describe, so it looks like the code wasn't written to cover initializing a list.

It seems like useful functionality to me. @Neferites would you be able to prepare a PR to make the code change?

**Comment by Neferites** [comment]
Hello @reimda, i would love to prepare a PR, but i'm not familiar to Go language :(

**Comment by srebhan** [comment]
@Neferites is this still an issue with the latest version?

**Comment by juaniten** [comment]
I confirm that this is still an issue in telegraf latest (1.31.3).

**Comment by srebhan** [comment]
@juaniten could you please show your config and what you set in the environment variable? This definitively works...
