### ISSUE TITLE
please document procstat fields

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [influxdata/telegraf#10949]
### Proposal:

Please add field descriptions on this page:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat

The names of the fields are not detailed enough to explain what the fields mean.  E.g., the name cpu_time_steal does not explain what is being stolen or who stole the CPU time.  That name is not detailed enough to explain how it differs from field cpu_time_user.

If the names are taken from some other software like the Linux kernel or glibc, please include a link to the other software's documentation that describes the meaning of the fields.  Add such a link to this page:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat

Thanks.

**Comment by powersj** [comment]
Hi,

Always happy to implement improvements to our docs. I like your second suggestion about linking to other docs where those fields are defined by upstream projects. I would like to avoid Telegraf from potentially duplicating and then maintaining definitions that already exist elsewhere.

I think the kernel's own docs on [/proc](https://www.kernel.org/doc/html/latest/filesystems/proc.html) go through most of the values themselves and define what they are.

What do you think about that link?

Thanks!
