### ISSUE TITLE
statsd importer to prometheus exporter – format issue

### ISSUE THREAD

**Issue by hryamzik** [influxdata/telegraf#1095]
```
# HELP deploys_test_myservice Telegraf collected metric
# TYPE deploys_test_myservice untyped
deploys_test_myservice{host="prometheus",metric_type="counter"} 4
```

This should be

```
# HELP deploys_test_myservice Telegraf collected metric
# TYPE deploys_test_myservice counter
deploys_test_myservice{host="prometheus"} 4
```

And even ```host``` tag looks odd for me.

**Comment by sparrc** [comment]
in 0.13 you'll be able to use the `tagexclude` parameters to remove tags from telegraf metrics. There's nothing innately wrong with those tags, it's just that you don't happen to want them.

**Comment by hryamzik** [comment]
@sparrc have you ever heard about metric types? Do you realize that untyped and count are not equal?

**Comment by sparrc** [comment]
@hryamzik "metric type" is a vague term and has a different meaning depending on which of the 100s of metric collection systems you're using, so please try to be more specific.

**Comment by hryamzik** [comment]
As we are talking about [prometheus](https://prometheus.io/docs/concepts/metric_types/) and [statsd](https://github.com/etsy/statsd/blob/master/docs/metric_types.md) types, they could e counters, gauges and histograms. If you report counter to statsd it should't be exported to prometheus as untyped as it won't be aggregated as counter in this case and will go to zero after reporting it to a restarted telegraf.

**Comment by sparrc** [comment]
Telegraf metrics, however, do not have the concept of a counter. For that reason the prometheus output doesn't support _any_ types

so if you'd like to re-open the issue with a more specific request, like "Support counter, gauge, and histogram data types in the prometheus output", I would be happy to leave it open.

Just try to keep in mind that being as specific as possible is appreciated, I don't have time to carefully read every issue that comes in :)
