### ISSUE TITLE
Azure output plugin - properly recover after context deadline exceeded

### ISSUE THREAD

**Issue by Hr0bar** [influxdata/telegraf#10950]
## Feature Request

When there is a network issue (corporate proxy, corporate zscaler and other network elements that can cause this) that triggers "context deadline exceeded" the connection is not reinitiated, and telegraf keeps throwing the same error indefinitely.

### Proposal:

Connection is reinitiated after this happens.

### Current behavior:

```
Mar 22 09:52:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:52:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:53:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:53:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:54:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:54:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:55:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:55:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:56:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:56:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:57:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:57:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:58:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:58:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mar 22 09:59:14 HOSTNAME_CENSORED.com telegraf[6436]: 2022-03-22T09:59:14Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westus.monitoring.azure.com/subscriptions/CENSORED/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Desired behavior:

When context deadline exceeded is detected multiple times, the connections should try to get reinitiated.
We are currently using a **workaround** where we set the conntimeout to 10 seconds (IdleConnTimeout: 10 * time.Second in below code added in /plugins/outputs/azure_monitor/azure_monitor.go), which is not ideal solution:

```
	a.client = &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			IdleConnTimeout: 10 * time.Second,
		},
		Timeout: time.Duration(a.Timeout),
	}

```

### Use case: 

To make telegraf successfully send metrics

**Comment by powersj** [comment]
@Hr0bar how often is this happening? Does it only occur after N hours? Is this something you can easily reproduce?

> context deadline exceeded (Client.Timeout exceeded while awaiting headers)

If you give it enough time does this error ever go away? Or does it stay this way till a restart of the service?

**Comment by Hr0bar** [comment]
It happens randomly (perhaps once every two weeks?). Its not caused by telegraf itself, its likely caused by corporate Zscaler or Proxy / network undergoing some changes. 

The issue once occurs stays there forever (multiple days+ for us, until telegraf is restarted)

But it seems to be caused by telegraf trying to keep even non-working(timeouting) connection open indefinitely by default by Azure Monitor output plugin.

Simply setting the "IdleConnTimeout: 10 * time.Second," solves the issue for us. But as mentioned, that is a workaround and proper handling that would be able to detect such condition and try to restart the connection in that case would be better.

**Comment by powersj** [comment]
> It happens randomly (perhaps once every two weeks?). Its not caused by telegraf itself, its likely caused by corporate Zscaler or Proxy / network undergoing some changes.
> 
> The issue once occurs stays there forever (multiple days+ for us, until telegraf is restarted)
> 

Ah interesting that we never recover. I agree that the error is usually network related. I have put up #11030 which will look for that specific error and try to re-create the client. Would you be willing to give that a try?

**Comment by Hr0bar** [comment]
Thanks, looks like a good solution. Deployed https://github.com/influxdata/telegraf/pull/11030 to our servers. Think should be OK, but if some issues occur Ill report back.

**Comment by powersj** [comment]
Thanks for jumping on that. I am going to let this sit for a week before having others review to see if you run into anything. Thanks!

**Comment by Hr0bar** [comment]
No issues so far. Experienced a couple of "context deadline exceeded" errors on multiple servers caused by corporate network issues, after which Telegraf kept functioning as soon as they disappeared. Hard to tell whether the connection would keep functioning or not after issues were gone without this fix (no idea what kind of network issues they were, some allow the connection to keep working after issue is gone some not I guess), but seems there are no issues with the fix itself when the condition occurs. 10+ servers with this fix with 10+ "context deadline exceeded" occurred in last week and no issues caused.

**Comment by powersj** [comment]
Thank for trying the PR. When the team is back in next week I can work to
land this.
