### ISSUE TITLE
Document that the regex processor operates on only string fields, not floats or ints.

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [influxdata/telegraf#10978]
## Feature Request

Please make the documentation say:

> The regex processor operates on only string fields, not floats or ints.

Add that text to this page:

https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex

I spent hours trying to get regex to work on an int field.  If the documentation is updated, maybe it will save other people time.  E.g. see:

https://github.com/influxdata/telegraf/issues/10092

**Comment by powersj** [comment]
Hi,

Thanks for the request, take a look at #10982 and feel free to review.

Thanks again!

**Comment by Jacob-Burckhardt** [comment]
That's great.  Thanks.
