### ISSUE TITLE
telegraph generates invalid OpenTSDB inserts

### ISSUE THREAD

**Issue by Licenser** [influxdata/telegraf#1098]
```
put telegraf.test.disk_inodes_free 1461673240 736630875 fstype=hfs host=Schroedinger path=/Volumes/Time Machine Backups
```

The space in 'path' violate the specification of OpenTSDB's wire protocol[1]:
![image](https://cloud.githubusercontent.com/assets/119093/14817897/4e3c856a-0bba-11e6-9930-34b5e76e2bd6.png)

I'm not 100% sure what the best way to address this would be, but if nothing else goes perhaps just dropping those might work?

[1] http://opentsdb.net/docs/build/html/user_guide/writing.html

**Comment by sparrc** [comment]
I think we could just replace spaces in all tag and field values

**Comment by Licenser** [comment]
yap I think it's simply the case of coming up with a convention that is applied
