### ISSUE TITLE
suspicious assignment to a by-value method receiver

### ISSUE THREAD

**Issue by chavacava** [influxdata/telegraf#10989]
In the code below, the assignment `d.frozen = true` has no effect beyond the method's scope 
https://github.com/influxdata/telegraf/blob/577c0462b8a0c0f98e822672091d9cf6916427d9/plugins/common/starlark/field_dict.go#L40-L42

**Comment by chavacava** [comment]
My bad. Because `Metric` is embedded as a "pointer to", the assignment `d.frozen = true` [actually affects the `FieldDict` instance even if it is a _by-value_ receiver](https://go.dev/play/p/U3Iox52wDZD).

**Comment by reimda** [comment]
That's a bit tricky. Thanks for following up!
