### ISSUE TITLE
suspicious assignment to a by-value method receiver

### ISSUE THREAD

**Issue by chavacava** [influxdata/telegraf#10991]
In the code below, the assignment `d.frozen = true` has no effect beyond the method's scope

https://github.com/influxdata/telegraf/blob/577c0462b8a0c0f98e822672091d9cf6916427d9/plugins/common/starlark/tag_dict.go#L39-L41

**Comment by sspaink** [comment]
Closing because it seems to be a duplicate of: https://github.com/influxdata/telegraf/issues/10989
