### ISSUE TITLE
allow cloudwatch input to specify sts role assume

### ISSUE THREAD

**Issue by kapilt** [influxdata/telegraf#1101]
ie. cross account cloudwatch aggregation, given an instance role.

**Comment by kapilt** [comment]
https://github.com/influxdata/telegraf/issues/1101

**Comment by sparrc** [comment]
@kapilt can you provide more details/reasons? this is a pretty minimal feature request.....

**Comment by johnrengelman** [comment]
@kapilt are you simply asking for the ability to do an IAM assume role for credentials?

**Comment by kapilt** [comment]
@johnrengelman yup exactly that, i'd like to pull metrics across accounts, standard best practice to do that is via iam sts role assume with initial credentials.

**Comment by sparrc** [comment]
I believe that this has been resolved by @johnrengelman, please feel reopen if that's not that case
