### ISSUE TITLE
hope telegraf supports rocketMQ monitor

### ISSUE THREAD

**Issue by ikun6217** [influxdata/telegraf#11026]
## Feature Request
hope telegraf supports rocketMQ monitor

Opening a feature request kicks off a discussion.

**Comment by sspaink** [comment]
Hello @ikun6217,  Telegraf doesn't currently support [Apache RocketMQ](https://rocketmq.apache.org/). Do you think you might be up to the challenge to implement a plugin to support it? Could you perhaps share more details on what metrics you would like to see such a plugin gather?
