### ISSUE TITLE
[inputs.intel_powerstat] throttleTemp and temp in msrData should be represented as int64, not uint64

### ISSUE THREAD

**Issue by pduzinki** [influxdata/telegraf#11028]
### Relevant telegraf.conf

```toml
n/a
```

### Logs from Telegraf

```text
n/a
```

### System info

n/a

### Steps to reproduce

n/a

### Expected behavior

_throttleTemp_ and _temp_ fields in _msrData_ struct should be represented as int64, and not uint64. 

### Actual behavior

_throttleTemp_ and _temp_ fields in _msrData_ struct are represented as int64.

### Additional info

This can be concluded from the chapter _14.8.5.2 Reading the Digital Sensor_ of [Software Developer's Manual](https://cdrdv2.intel.com/v1/dl/getContent/671200)

**Comment by reimda** [comment]
Hi @pduzinki the linked PR has a build you can test: https://github.com/influxdata/telegraf/pull/11035#issuecomment-1126060519

Is that PR going to work for you?

**Comment by pduzinki** [comment]
Hi @reimda, yes, that PR is fine!
