### ISSUE TITLE
inputs.kubernetes not showing lightbits volumes

### ISSUE THREAD

**Issue by fireba11** [influxdata/telegraf#11033]
I'm running telegraf as deamonset on kubernetes to get metrics via inputs.kubernetes
That works fine but all volumes via lightbits don't show up at all.
No error messages in the log, I suspect the kubelet used to gather the info just doesn't see those.
Is there a way to check that so i can complain to the hoster about it? ;-)

**Comment by majst01** [comment]
Hi @fireba11 

your hoster speaking :-)

This feature is going to be released in the next version of the csi driver, the exact release date is not known yet.

**Comment by fireba11** [comment]
@majst01 should i feel stalked now? :-D
Yes, put a ticket there, thanks for the info. telegraf is not the culprit ;-)

**Comment by muliby-lb** [comment]
@fireba11 the stalking was entirely incidental. I saw an alert pop up on "lightbits" and asked the team to look into it and ping @majst01. We take our metrics seriously! :-)
