### ISSUE TITLE
varnish - VBE stats are not extracted if we use dynamic vmod

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#11040]
### Relevant telegraf.conf

```toml
[[inputs.varnish]]
binary = "/usr/bin/varnishstat"
adm_binary = "/usr/bin/varnishadm"
stats = ["VBE*"]
metric_version = 2
timeout = "20s"
```

### Logs from Telegraf

```text
NC
```

### System info

1.22.0 (git: HEAD 80a7feb8)

### Steps to reproduce

1. Use varnish backend with dynamic vmod (https://github.com/nigoroll/libvmod-dynamic))
2. try a telegref --test
3. stats are truncated (probably due to varnishstat output with ()):
> varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000

### Expected behavior

- With standard backend (varnishstat output) (truncated) : ALL OK:

```
VBE.test.server.fail_eacces                    0         0.00 Connections failed with EACCES or EPERM
VBE.test.server.fail_eaddrnotavail             0         0.00 Connections failed with EADDRNOTAVAIL
VBE.test.server.conn                           0          .   Concurrent connections to backend
```
telegraf output (truncated):
```
> varnish,backend=backend,host=XXXX,section=VBE fail_eacces=0i 1651049058000000000
> varnish,backend=backend,host=XXXX,section=VBE fail_eaddrnotavail=0i 1651049058000000000
> varnish,backend=backend,host=XXXX,section=VBE conn=0i 1651049058000000000
```

- With dynamic vmod (broken), we can expect something like that:
```
> varnish,backend=dynamic_director_nameIP_PORT,host=XXXX,section=VBE fail_eacces=0i 1651049058000000000
> varnish,backend=dynamic_director_nameIP_PORT,host=XXXX,section=VBE fail_eaddrnotavail=0i 1651049058000000000
> varnish,backend=dynamic_director_nameIP_PORT,host=XXXX,section=VBE conn=0i 1651049058000000000
```

### Actual behavior

With standard backend (varnishstat output) (truncated):
```
VBE.test.dynamic_director_name(IP:PORT).fail_eaddrnotavail            0         0.00 Connections failed with EADDRNOTAVAIL
VBE.test.dynamic_director_name(IP:PORT).fail_econnrefused             0         0.00 Connections failed with ECONNREFUSED
VBE.test.dynamic_director_name(IP:PORT).fail_enetunreach              0         0.00 Connections failed with ENETUNREACH
VBE.test.dynamic_director_name(IP:PORT).fail_etimedout                0         0.00 Connections failed ETIMEDOUT
```
telegraf output (truncated):
```
> varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000
> varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000
> varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000
> varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000
```

### Additional info

Following PR https://github.com/influxdata/telegraf/pull/9432 cc @rhajek 
It seems that dynamic vmod output is not well parsed due to the format of output:
- Standard one: VBE.test.server.fail_eacces                    0         0.00 Connections failed with EACCES or EPERM
telegraf output: > varnish,backend=IP_PORT,host=XXXX,section=VBE fail_eacces=0i 1651049058000000000
- With dynamic vmod: VBE.test.dynamic_director_name(IP:PORT).fail_enetunreach              0         0.00 Connections failed with ENETUNREACH
telegraf output: > varnish,host=XXXX,section=VBE test.dynamic_director_name=0i 1651049028000000000

Probably due to ()  so the metric is missing also.

**Comment by rhajek** [comment]
Hi @anthosz, thanks for the detailed bug report. I was not able to cover all metrics patterns, because there are lot of varnish plugins and settings. So there is a way how you can extend default parsing rules with custom regexp in `telegraf.conf` 

This should fix your problem.

```toml
[[inputs.varnish]]
    regexps = ['^VBE\.(?P<_vcl>[\w\-]*)\.(?P<backend>[\w\-]*)\((?P<host>[\d\.]*)\:(?P<port>[\d]*)\)\.(?P<_field>[\w\-]*)']
```
Following metric like.`VBE.test.dynamic_director_name(1.2.3.44:6666).fail_eaddrnotavail` should be parsed correctly.

Tip: go regular expressions can be tricky, I use https://regoio.herokuapp.com/ online regexp tool to debug it
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2169548/165537670-e612b5e5-8b04-460e-9e88-64bfbc42565c.png">

**Comment by anthosz** [comment]
Thank you @rhajek !

I zapped this option but I confirm that all is ok now!
