### ISSUE TITLE
x509_cert check certificate on specific page not working

### ISSUE THREAD

**Issue by ekeroth112** [influxdata/telegraf#11048]
### Relevant telegraf.conf

```text
x509_cert.input
this configuration will not work:
sources = ["https://site.com/test:443"

#######
also tried webencoding "/" to "%2F" without luck, service will not start.
sources = ["https://site.com%2Ftest:443"

#######
top-page
sources = ["https://site.com:443"
the product I want to monitor does not respond with certificate at top-page, but at correct site example "site.com/test" he will present the certifcate.
```

### Logs from Telegraf

```text
##with "/test" service will start but following error:
[inputs.x509_cert] Error in plugin: cannot get SSL cert 'https://site.com/test:443': dial tcp: address site.com: missing port in address

##with encoding, service will not start with following error:
Error running agent: could not initialize input inputs.x509_cert: failed to parse cert location - parse "https://site.com%2Ftest:443": invalid URL escape "%2F"

##with just root-page url "site.com"
Error in plugin: cannot get SSL cert 'https://site.com:443': remote error: tls: insufficient security level
```

### System info

telegraf 1.22.1 windows

### Steps to reproduce

1. define url that contain a specific page "site.com/test" and where top-site does not respond with certificate

### Expected behavior

x509_cert to successfully check certificate

### Actual behavior

error message
Error in plugin: cannot get SSL cert 'https://site.com/test:443': dia l tcp: address site.com: missing port in address

### Additional info

could possible be solved with support for web-encoding for https://-url

**Comment by powersj** [comment]
Hi,

Typically when I see a URL with the port + a path element it would look like this:

```
https://site.com:443/test
```

I don't see that case above, can you please try that?

**Comment by ekeroth112** [comment]
ofc! brain.exe stopped working..
