### ISSUE TITLE
Event Hub Consumer subscribtion on specific MQTT topic on IoT Hub

### ISSUE THREAD

**Issue by ivanvaccarics** [influxdata/telegraf#11059]
Dear all, i'm using telegraf to consume data from an IoT Hub on Azure and store the data inside an Influxdb Cloud solution. The data are send from a sensor by using MQTT to the IoT Hub.
Based on the documentation, I'm using the Event Hub Consumer to subscribe to the IoT Hub to receive the data.
My question is:  there is a way to specify a specific (MQTT) topic inside the Event Hub Consumer to subscribe? Or the plugin is in charge to receive all the data?

Thanks a lot!

**Comment by kmfriedt** [comment]
Hi Ivan, did you ever figure this out?
