### ISSUE TITLE
input.sensors won't send to Influx unless root

### ISSUE THREAD

**Issue by sugo512** [influxdata/telegraf#11058]
### Relevant telegraf.conf

```toml
[[inputs.sensors]]
```

### Logs from Telegraf

```text
I! Loaded inputs: cpu disk diskio kernel mem processes swap system
```

### System info

Telegraf 1.22.3 -  5.15.0-27-generic #28-Ubuntu

### Steps to reproduce

1. Run from command line with sudo and sensors is loaded as an input plugin
2.  Loaded inputs: cpu disk diskio kernel mem processes sensors swap system
3.
...

### Expected behavior

Sensors show up in Influx

### Actual behavior

No input in influx

**Comment by powersj** [comment]
Hi!

Can you provide us with some more details about your config, error messages, and platform you are running on?

Thanks

**Comment by sugo512** [comment]
[neofetch.txt](https://github.com/influxdata/telegraf/files/8612394/neofetch.txt)
[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/8612401/telegraf.conf.txt)

I don't have any errors, just that "sensors" does not seem to be loading and creating output unless telegraf is run as sudo. If I do a --test, all looks fine as a regular user, but it won't send to influx.

Let me know if you need anything else.

**Comment by powersj** [comment]
Using --test will not send data to your outputs. Have you run without that?

The team is at a offsite meeting this week, so I am not certain but can you run the sensors command as a normal user?

**Comment by sugo512** [comment]
Yes, without --test it is working fine. All other inputs send to influx. Just sensors won't load.

**Comment by powersj** [comment]
And did you try running the command itself?

**Comment by sugo512** [comment]
Ok - interesting. When I run the command as a non-root user from CLI - it loads sensors. The problem I guess is when it is running as a linux service.

By loading I mean the log info - Loaded inputs: cpu disk diskio kernel mem processes sensors swap system

**Comment by sugo512** [comment]
[tele log serv.txt](https://github.com/influxdata/telegraf/files/8612591/tele.log.serv.txt)

**Comment by powersj** [comment]
In the config you linked sensors is commented out. Is that the config that is under /etc/telegraf that the service is using?

```
# [[inputs.sensors]]
```

**Comment by sugo512** [comment]
There are two entries - mine is at the bottom

**Comment by powersj** [comment]
I don't see that.

Is this file under /etc/telegraf/telegraf.conf?

**Comment by sugo512** [comment]
Crap - could be my own fault - directory problem, hang on

**Comment by powersj** [comment]
Sweet glad it is working!
