### ISSUE TITLE
Feature Request :  name_key argument in json input for dynamic measurement names.

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/telegraf#1106]
Is there a way to override the influxdb measurement name in json input while using that input in tcp listner. There is an option to override in config. Also in influx format we can send measurement name. Is it possible in json format too.

**Comment by sparrc** [comment]
There isn't, you can only do it via the configuration file by specifying `name_override` under the tcp listener, like this:

```
[[inputs.tcp_listener]]
  ...
  name_override = "my_metrics"
```

**Comment by sparrc** [comment]
If this doesn't fit your use-case could you change this issue to a feature request for a `name_key` argument on the json data format? And explain what you need and would like to see with that feature.

**Comment by gaurav-moonfroglabs** [comment]
okay, yes i have already gone through this name_override tag. But that won't make it dynamic. If i want to send multiple api metrics via tcp for different measurements this won't give me dynamic measurement.

Okay i will put the feature request in for the above.

**Comment by gaurav-moonfroglabs** [comment]
How do i change it to feature request... dont see anywhere to attach label to this issue or in new issues.

**Comment by sparrc** [comment]
I just meant in the title, and to give details on the feature you would like

**Comment by gaurav-moonfroglabs** [comment]
okay thanks

**Comment by gaurav-moonfroglabs** [comment]
Hi,

feature req:  parse and fetch measurement name from json fields

We have multiple input format available in telegraf. In influx format we can specify the measurement/series name while sending data. Which makes it pretty dynamic to send data of multiple monitoring type on single tcp listener. 

I tried same thing in json. But in json we cannot specify the measurement name and can only specify in config. So i want to ask if possible i would love to see a feature to parse and fetch measurement name from json fields.

**Comment by sparrc** [comment]
closing in favor of https://github.com/influxdata/telegraf/issues/1363
