### ISSUE TITLE
Ubuntu Repository for 21.04 "Jammy"

### ISSUE THREAD

**Issue by Xyaren** [influxdata/telegraf#11072]
Repository "https://repos.influxdata.com/ubuntu jammy Release" is currently missing and causes errors when installing on the new LTS of Ubuntu (Jammy Jellyfish)

**Comment by powersj** [comment]
Hi,

Jammy may get added, but I would suggest you move to our non-distro specific URL:

```
deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/ubuntu stable main
```

This way no matter what release you are deploying to, you don't need to wait for us to ensure we have the distro available!

Thanks!

**Comment by Xyaren** [comment]
Thanks!
Out of curiosity: why are there distro-specific archives there at all ?

**Comment by powersj** [comment]
>  Out of curiosity: why are there distro-specific archives there at all ?

Not sure; that was how it was originally set up long before I joined. With the huge number of new releases and new distros it became burdensome to keep them all up to date, so we added the distro-agnostic method recently to make it easier on everyone :)

**Comment by Xyaren** [comment]
Fair enough :D

I suggest updating the documentation about that: https://docs.influxdata.com/telegraf/v1.21/introduction/installation/
