### ISSUE TITLE
Move InfluxDB v2 output up in the default config

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#11074]
Currently in the list of outputs in the telegraf.conf default config they are listed as `outputs.influxdb` then alphabetically so `outputs.influxdb_v2` falls lower down the list: https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L1003

We should move `outputs.influxdb_v2` higher - either first or after `outputs.influxdb`

**Comment by reimda** [comment]
Maybe instead of reordering, we should add a note in the influxdb plugin's sample config to remind people when to use influxdb_v2. That way we wouldn't have to reorder the plugins since they're alphabetical.

**Comment by sjwang90** [comment]
The influxdb v1 plugin is already at the top and then the rest (including influxdb_v2 is alphabetical). 

A lot of people, obviously not all, will be coming to use Telegraf with InfluxDB so having the output plugins at the top would ease the process. The concern coming from Marc was that customers were having to search the list when they were looking for `outputs.influxdb_v2`.

**Comment by sjwang90** [comment]
Update won't be implemented until Telegraf 1.25 feature release in December
