### ISSUE TITLE
Influx 1.x: Get uptime statistics from /debug/vars in to the influxdb plugin

### ISSUE THREAD

**Issue by danatinflux** [influxdata/telegraf#11071]
### Proposal:

I'd like to capture this info from the http://(servername):8086/debug/vars output:

```
  {
    "system": {
      "currentTime": "2022-05-09T14:27:15.922004455Z",
      "started": "2022-05-04T06:37:27.660564514Z",
      "uptime": 460188
    },
```

This would allow us to create an alert if the uptime is less than a certain threshold (restart notification), and also deduce how long a process has been up.

### Current behavior:

Not included in current plugin.

### Desired behavior:

Add a section in the 'influxdb' plugin ('uptime?') that would have the three parameters mentioned above.

### Use case: 

This would allow us to run an alert if the uptime is less than a certain threshold (restart notification), and also deduce how long an instance has been up.

**Comment by powersj** [comment]
next steps: look into adding this
