### ISSUE TITLE
PLUGIN : Input : filecount : Metrics new fields

### ISSUE THREAD

**Issue by tguenneguez** [influxdata/telegraf#11087]
## Feature Request
In the plugin https://github.com/influxdata/telegraf/blob/release-1.22/plugins/inputs/filecount, it will be greate to have some fields like :
oldest_file_timestamp
newest_file_timestamp

### Use case: 
With this two fields, we can generate alarming if nothing append in the directeory.
For exemple if we wait for daily file reception.

**Comment by powersj** [comment]
Hi,

Thanks for the request! I can see this being helpful with reporting. If anyone wants to try adding this, please do and we can review a PR.

Thanks!

**Comment by reimda** [comment]
I think the plugin already reads the timestamps, it just needs to keep track of them and add them to the metrics. It makes sense to me to add a setting for this (default disabled) since it's not functionality most users seem to want.
