### ISSUE TITLE
Add option for origin header to jolokia2 plugin, required for ActiveMQ 5.16+

### ISSUE THREAD

**Issue by jonim8or** [influxdata/telegraf#11095]
## Feature Request
Add possibility to set origin header for jolokia2 plugin

### Proposal:
Add an optional field *origin* to the configuration of the jolokia2_agent
```
[[inputs.jolokia2_agent]]
  urls = ["http://agent:8080/jolokia"]
  origin = "http://localhost"
```
### Current behavior:
Origin can't be set, and therefore some jolokia endpoints reject the request

### Desired behavior:
User should be able to set the origin, so that jolokia endpoints can still be used. 

### Use case: Using Jolokia2 to get metrics from ActiveMQ 5.16.x
Since ActvieMQ 5.16.0 the jolokia endpoint [is more strict against CORS requests](https://issues.apache.org/jira/browse/AMQ-7434). As a result ActiveMQ denies the request from telegraf:
```
telegraf_1  | 2022-05-13T07:43:40Z E! [inputs.procstat] Error in plugin: Error running /usr/bin/pgrep: exit status 2
telegraf_1  | 2022-05-13T07:43:40Z E! [inputs.jolokia2_agent] Error in plugin: unable to gather metrics for http://host.docker.internal:8161/api/jolokia: decoding JSON response: json: cannot unmarshal object into Go value of type []
jolokia2.jolokiaResponse: {"error_type":"java.lang.Exception","error":"java.lang.Exception : Origin null is not allowed to call this agent","status":403}
```
Adding an "origin" flag to the headers solves this problem. (I tried this out using curl)
```
$ curl -u admin:admin http://localhost:8161/api/jolokia
{"error_type":"java.lang.Exception","error":"java.lang.Exception : Origin null is not allowed to call this agent","status":403}
$ curl -u admin:admin http://localhost:8161/api/jolokia -H "Origin: http://localhost"
{"request":{"type":"version"},"value":{"agent":"1.6.2","protocol":"7.2","config":{"listenForHttpService":"true","authIgnoreCerts":"false","agentId":"172.24.0.2-1-3d20e575-servlet","debug":"false","agentType":"servlet","policyLocatio
n":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","serializeException":"false","mimeType":"text\/plain","dispatcherClasses":"org.jolokia.http.Jsr160ProxyNotEnabledByDefaultAnymoreDispatcher","authMode":"basic","authMatc
h":"any","streaming":"true","canonicalNaming":"true","historyMaxEntries":"10","allowErrorDetails":"false","allowDnsReverseLookup":"true","realm":"jolokia","includeStackTrace":"true","useRestrictorService":"false","debugMaxEntries":"
100"},"info":{"product":"activemq","vendor":"Apache","version":"5.16.3"}},"timestamp":1652428141,"status":200}
```

**Comment by powersj** [comment]
Thanks for the issue, it sounds like adding an option origin option to set the origin header is what is needed.

**Comment by reimda** [comment]
Hi @jonim8or are you able to put a PR together to add this header?

**Comment by jonim8or** [comment]
I'm afraid i won't be able to do that easily. I'm not a go developer,
haven't even set up an ide for it.
I can help testing it, but i think it is better if a go dev does the
implementation

**Comment by powersj** [comment]
Hi @jonim8or,

I have put up https://github.com/influxdata/telegraf/pull/11692 with a new option called 'origin' that lets you set the 'origin' header during a request. Would you be willing to download the artifacts on that PR, which should be there in 20-30mins, and give it a try?

Thanks!

**Comment by jonim8or** [comment]
Thanks for taking the time to add this. It works!
How I tested it: 

- Start activemq 5.16.3
- start telegraf, configured with jolokia plugin, but without the origin header
- telegraf complains about "Origin null is not allowed to call this agent"
- configure telegraf with origin = "host.docker.internal"
- restart telegraf
- telegraf no longer complains, activemq data shows up in influxdb.
