### ISSUE TITLE
use_sudo option for processes

### ISSUE THREAD

**Issue by mdtancsa** [influxdata/telegraf#11103]
## Feature Request

By allowing ps to be called from sudo, FreeBSD boxes that have as hardening sysctls enabled
security.bsd.see_other_uids=0
security.bsd.see_other_gids=0
security.bsd.see_jail_proc=0

will not yield the proper process counts

### Proposal:

add 
use_sudo = true 
as an option for the [[processes]] inplut plugin

### Current behavior:
only shows the processes telegraf is running as

### Desired behavior:

total count of all processes.

### Use case: 

For monitoring FreeBSD boxes, this will give a better count of processes. 

Locally I am running this on my FreeBSD servers
```
--- processes_notwindows.go     2022-05-16 15:30:19.507217000 -0400
+++ /tmp/processes_notwindows.go        2022-05-16 15:30:00.132251000 -0400
@@ -210,12 +210,12 @@
 }
 
 func execPS() ([]byte, error) {
-       bin, err := exec.LookPath("ps")
+       bin, err := exec.LookPath("sudo")
        if err != nil {
                return nil, err
        }
 
-       out, err := exec.Command(bin, "axo", "state").Output()
+       out, err := exec.Command(bin, "/bin/ps", "axo", "state").Output()
        if err != nil {
                return nil, err
        }
```

with

telegraf ALL=(root) NOPASSWD: /bin/ps axo state

**Comment by powersj** [comment]
Hi,

Thanks for the PR. This sounds like a good idea for your use-case. Would you be interested in opening a PR with the config option to allow for the use of sudo? You could look at the `lvm` plugin as an example.

Thanks!

**Comment by mdtancsa** [comment]
Sure, you mean add some txt like in the readme ?
`
--- README.md   2022-05-16 15:24:02.609757000 -0400
+++ README.md.new       2022-05-18 10:45:31.173344000 -0400
@@ -13,8 +13,30 @@
 ```toml
 # Get the number of processes and group them by status
 [[inputs.processes]]
-  # no configuration
+  ## Use sudo to run ps commands on FreeBSD
+  use_sudo = false
+
 ```
+
+### Using sudo with FreeBSD
+
+With certain hardening settings on FreeBSD (e.g. sysctl security.bsd.see_other_uids=0) you 
+will not be able to see process counts of the system. Running the command via sudo will
+work around this
+
+If your account does not already have the ability to run commands
+with passwordless sudo then updates to the sudoers file are required. Below
+is an example to allow the requires ps commands:
+
+First, use the `visudo` command to start editing the sudoers file. Then add
+the following content, where `<username>` is the username of the user that
+needs this access (typically telegraf):
+
+```text
+<username>  ALL=(root) NOPASSWD: /bin/ps -axo state
+```
+
+
 
 Another possible configuration is to define an alternative path for resolving the /proc location.
 Using the environment variable `HOST_PROC` the plugin will retrieve process information from the specified location.
`

**Comment by powersj** [comment]
My apologies for missing your follow-up comment!

What you have is what I would suggest, except I would comment out the use_sudo option, as the value in the config file is the default and this case should be false.

Then an update to the code would be necessary to check this config option.

Is this a PR you'd be willing to try creating?  Thanks and again my apologies for missing your earlier reply.
