### ISSUE TITLE
Consider combining directory_monitor, file, tail plugins

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#11108]
@hipska noticed that there is functional overlap across these plugins. It might make sense to combine them in some way, either sharing code or consolidating functionality then deprecating/removing one or more of the plugins.

| Plugin / Feature                           | [directory_monitor][1] | [file][2] | [tail][3] |
| :---                                             | :---: | :---: | :---: |
| Read newly appeared files         | ✔️ | ✔️ | ✔️ |
| Parsing                                         | line-by-line, [complete-file][4] | complete-file | line-by-line |
| Move/Remove file after parsing | ✔️ | ❌ | ❌ |
| Supports gzipped file                 | ✔️ | ❌ | ❌ |

[1]: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/directory_monitor
[2]: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/file
[3]: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tail
[4]: https://github.com/influxdata/telegraf/pull/11234

**Comment by powersj** [comment]
next steps: review as part of 2.0 milestone

**Comment by Hipska** [comment]
My preference on this would be to merge `directory_monitor` functionality into `file` and then deprecate `directory_monitor`. The `tail` plugin can stay as is.

Other scenario could be to deprecate both `file` and `tail` plugin in favour of `directory_monitor`.

**Comment by Hipska** [comment]
@powersj next steps?

**Comment by powersj** [comment]
I think we are ok removing older plugins that have long been deprecated, but removing either `directory_monitor`, `file`, or `tail` will break a lot of users and cause a lot of pain for them. So I do not see us removing any of these.

Does that only then leave the gzip support and moving/delete a file?

**Comment by Hipska** [comment]
We could start with adding the functionalities to 1 plugin and marking the others as deprecated..

I think if we do it smart, we can even make the others ones a link/rename, so it is seamless..

**Comment by Hipska** [comment]
@powersj your thoughts?

**Comment by powersj** [comment]
> We could start with adding the functionalities to 1 plugin and marking the others as deprecated..

I am not entirely sure what we as maintainers and our users gain from doing this. Yes, there is duplication but since these plugins are so widely used it will impact a wide group of users. 

Doing this will ultimately lead to lots of questions from users about moving over or we find out that there is different or unexpected behavior that users were depending on which suddenly disappears by consolidating the three plugins.

As I mentioned in my earlier comment, I could see us adding features like the gzip support and moving files possibly if users would find it useful.

**Comment by powersj** [comment]
Sven and I met to further discussion this again and agree this is not something we would do as it would interrupt existing users and only cause confusion.
