### ISSUE TITLE
[inputs.dns_query] Include CNAME target/value in result set

### ISSUE THREAD

**Issue by GRX** [influxdata/telegraf#11116]
### Proposal:
Include the canonical target/value in the result set.

### Current behavior:
Currently the result only includes the domain that has been used to make the DNS query.
E.g.; gmail.google.com will only show gmail.google.com in the result

### Desired behavior:
Include the canonical target/value of the domain name
E.g.: gmail.google.com is an alias of **ww3.l.google.com**

And example from `dig +short gmail.google.com`:
```
www3.l.google.com.
142.250.179.142
```

### Use case: 
This allows the grouping of aliased domains by the domain they are aliasing for

**Comment by powersj** [comment]
Hmm this would be dependent on "github.com/miekg/dns", the library we use if it is even possible. The next steps are to see if it supports this sort of return and what would be required to get that data.

Would you be able to see if you can work up an example using it? Thanks!
