### ISSUE TITLE
Inputs.system does not return number-of-users

### ISSUE THREAD

**Issue by BertGr** [influxdata/telegraf#11129]
### Relevant telegraf.conf

```toml
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
  fielddrop = ["uptime_format"]
```

### Logs from Telegraf

```text
2022-05-18T13:42:11Z D! [agent] Starting service inputs
> system,host=rasp1 load1=0.08,load15=0.09,load5=0.09,n_cpus=4i,n_users=0i 1652881331000000000
2022-05-18T13:42:11Z D! [agent] Stopping service inputs
2022-05-18T13:42:11Z D! [agent] Input channel closed
> system,host=rasp1 uptime=800114i 1652881331000000000
2022-05-18T13:42:11Z D! [agent] Stopped Successfully
```

### System info

Telegraf v1.22.3 on Raspberry Pi 4B (aarch64)

### Steps to reproduce

1. telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --input-filter system

### Expected behavior

Since 4 users are connected I expect:
system,host=rasp1 load1=0.08,load15=0.09,load5=0.09,n_cpus=4i,n_users=**4**i 1652881331000000000

### Actual behavior

But got zero:
system,host=rasp1 load1=0.08,load15=0.09,load5=0.09,n_cpus=4i,n_users=**0**i 1652881331000000000

### Additional info

```
# uptime
 15:49:30 up 9 days,  6:22,  4 users,  load average: 0.17, 0.12, 0.10

/var/run/utmp is readable:
# ls -l /var/run/utmp
-rw-rw-r-- 1 root utmp 2800 May 18 13:46 /var/run/utmp
```
In prior versions (some months ago) reading of n_users was correct

**Comment by reimda** [comment]
I don't immediately know why this is happening. I don't think the system plugin has changed much recently. Telegraf has updated the go module used to get this information (gopsutil) but I would expect updated versions to work the same.

Since you can reproduce the problem, could you do some quick testing and find the most recent release that works and the oldest release that doesn't work? That would help to reduce the number of commits that we need to consider as a cause. Downloads of older versions are all available at https://github.com/influxdata/telegraf/releases

Thanks!

**Comment by BertGr** [comment]
Hi,
Seems a raspian-specific issue. Reading on my Zyxel-NAS is correct.
Due to SD-card-problems I've rebuild my Pi4 (with latest versions). Before I used v1.21.3 with correct results.
Just restored binary v1.21.3 and now result is 0 users while uptime shows 3
```
2022-05-19T22:46:15Z I! Starting Telegraf 1.21.3
2022-05-19T22:46:15Z I! Loaded inputs: system
2022-05-19T22:46:15Z I! Loaded aggregators:
2022-05-19T22:46:15Z I! Loaded processors:
2022-05-19T22:46:15Z W! Outputs are not used in testing mode!
2022-05-19T22:46:15Z I! Tags enabled: host=rasp1
> system,host=rasp1 load1=0.11,load15=0.14,load5=0.15,n_cpus=4i,n_users=0i 1653000376000000000
> system,host=rasp1 uptime=919158i 1653000376000000000
root@rasp1:~/Downloads# uptime
 01:04:45 up 10 days, 15:37,  3 users,  load average: 0.12, 0.13, 0.11
```
On SystemInputPlugin-page is a remark about permissions (I've checked, they are ok) but seems something like that.

gr,
Bert

**Comment by igomura** [comment]
I would add some more details about this issue. I'm watching GCP instances with telegraf. The system plugin works correctly for 5-10 min since telegraf start. After that it reports uptime field only and all other fields get dropped. There are no errors in log file.

Version: telegraf-1.21.4-1.x86_64
Kernel: 3.10.0-1160.36.2.el7.x86_64
Config:
```
[[inputs.system]]
fielddrop = ["uptime_format"]
```

**Comment by igomura** [comment]
It seems to be related to #10003

**Comment by powersj** [comment]
@igomura what architchture is the system you are running on?

**Comment by igomura** [comment]
I'm running it with linux kernel 3.10.0-1160.92.1.el7.x86_64
Even though the related ticket is for `ppc64`, they have the same outcome.
They are missing n_users field while other metrics still reported.

**Comment by powersj** [comment]
@igomura,

Please download an artifact from https://github.com/influxdata/telegraf/pull/13598 and provide the logs.

I do still see the metric on my own system, so I would like to know what is different.

**Comment by igomura** [comment]
I was running this artifact for a day and found no problems. All metrics reported as expected.
Let me upgrade few hosts to 1.28 (currently 1.23) to see if issue is resolved

```
2023-07-12T22:30:00Z I! [inputs.system] Found %!i(int=4) number of users
2023-07-12T22:30:02Z D! [outputs.file] Wrote batch of 2 metrics in 78.78µs
2023-07-12T22:30:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-07-12T22:30:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-07-12T22:30:15Z I! [inputs.system] Found %!i(int=4) number of users
2023-07-12T22:30:22Z D! [outputs.file] Wrote batch of 2 metrics in 73.12µs
2023-07-12T22:30:22Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-07-12T22:30:30Z I! [inputs.system] Found %!i(int=4) number of users
2023-07-12T22:30:32Z D! [outputs.file] Wrote batch of 2 metrics in 89.93µs
2023-07-12T22:30:32Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-07-12T22:30:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
```

**Comment by igomura** [comment]
heh.... same problem with 1.27.2 the module stops working after 2-5 minutes after telegraf restart. It only returns `uptime` and all other metrics disappear. Below is a screenshot how it looks like via Wavefront. There are few telegraph restarts

![Screenshot 2023-07-14 at 12 23 40 PM](https://github.com/influxdata/telegraf/assets/52306882/7785f00f-290c-46db-948a-442b2056f147)

**Comment by igomura** [comment]
and I was wrong regarding the artifact you gave me. It has the same bug. Debug shows module is able to read data, but it does not pass it further after some time

```
Jul 14 19:54:29 test.internal systemd[1]: Starting Telegraf...
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loading config: /etc/telegraf/telegraf.conf
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loading config: /etc/telegraf/telegraf.d/dedup.conf
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loading config: /etc/telegraf/telegraf.d/system.conf
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Starting Telegraf 1.28.0-d8cd3ad8
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 24 parsers, 59 outputs, 4 secret-stores
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loaded inputs: cpu disk diskio filestat mem net puppetagent system systemd_units x509_cert
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loaded aggregators:
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loaded processors: converter dedup (2x) regex
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loaded secretstores:
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Loaded outputs: file wavefront
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! Tags enabled: env=dev host=test.internal region=us-west1 service_env=dev
Jul 14 19:54:29 test.internal telegraf[101523]: 2023-07-14T19:54:29Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"test.internal", Flush Interval:10s
Jul 14 19:54:29 test.internal systemd[1]: Started Telegraf.
Jul 14 19:55:00 test.internal telegraf[101523]: 2023-07-14T19:55:00Z I! [inputs.system] Found %!i(int=2) number of users
Jul 14 19:55:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev load5=0,load15=0,n_cpus=2i,n_users=2i,n_unique_users=1i,load1=0 1689364500000000000
Jul 14 19:55:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev uptime=198410i 1689364500000000000
Jul 14 19:55:09 test.internal telegraf[101523]: systemd_units,active=active,env=dev,host=test.internal,load=loaded,name=sensu-agent.service,region=us-west1,service_env=dev,sub=running load_code=0i 1689364500000000000
Jul 14 19:55:09 test.internal telegraf[101523]: systemd_units,active=active,env=dev,host=test.internal,load=loaded,name=vector.service,region=us-west1,service_env=dev,sub=running load_code=0i 1689364500000000000
Jul 14 19:56:00 test.internal telegraf[101523]: 2023-07-14T19:56:00Z I! [inputs.system] Found %!i(int=2) number of users
Jul 14 19:56:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev uptime=198470i 1689364560000000000
Jul 14 19:57:00 test.internal telegraf[101523]: 2023-07-14T19:57:00Z I! [inputs.system] Found %!i(int=2) number of users
Jul 14 19:57:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev uptime=198530i 1689364620000000000
Jul 14 19:58:00 test.internal telegraf[101523]: 2023-07-14T19:58:00Z I! [inputs.system] Found %!i(int=2) number of users
Jul 14 19:58:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev uptime=198590i 1689364680000000000
Jul 14 19:59:00 test.internal telegraf[101523]: 2023-07-14T19:59:00Z I! [inputs.system] Found %!i(int=1) number of users
Jul 14 19:59:09 test.internal telegraf[101523]: system,env=dev,host=test.internal,region=us-west1,service_env=dev uptime=198650i 1689364740000000000
```

**Comment by BertGr** [comment]
Suppressed by dedup?????

**Comment by igomura** [comment]
I do not think so. 1) dedup is set to 10min (default), 2) load is getting changed all the time, so dedup should pass it. 3) this is the only module which behaves like that

**Comment by powersj** [comment]
Can you please drop the processors and see what is returned?

The code for this value is rather simple: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/system.go#L50-L58

If there is no error, we set the `n_users` field. My PR, which you used, would also print out if any error was encountered. However, that is absent from your output.

**Comment by igomura** [comment]
so, I must admin `dedup` plugin was the root cause of my issue. Once `dedup` was removed (or rather `system` metrics added as an exception) everything become normal. Here is my new config below
```
[[processors.dedup]]
dedup_interval = "10m"
namedrop = ["system"]
```
Thanks for pointing me to the right direction.

**Comment by powersj** [comment]
@BertGr,

It seems the other user resolved thier issue due to the dedup processor.

Are you still seeing this on your platform? If so, could you also file an issue with gopsutil like we did for #10003?

Thanks
