### ISSUE TITLE
kafka_consumer plugin always return "zk: node does not exist"

### ISSUE THREAD

**Issue by huangchaosuper** [influxdata/telegraf#1112]
### telegraf -sample-config -input-filter kafka_consumer -output-filter influxdb  > /etc/telegraf/telegraf.conf

2016/04/28 07:03:44 Starting Telegraf (version 0.12.1)
2016/04/28 07:03:44 Loaded outputs: influxdb
2016/04/28 07:03:44 Loaded inputs: kafka_consumer
2016/04/28 07:03:44 Tags enabled: host=XXXXX
2016/04/28 07:03:44 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"XXXXX", Flush Interval:10s
2016/04/28 07:03:44 Connected to 127.0.0.1:2181
2016/04/28 07:03:44 Authenticated: id=95801443660070949, timeout=6000
2016/04/28 07:03:44 Recv loop terminated: err=EOF
2016/04/28 07:03:44 Send loop terminated: err=<nil>
2016/04/28 07:03:44 Service for input kafka_consumer failed to start, exiting
**zk: node does not exist**

**Comment by sparrc** [comment]
you need to configure the kafka_consumer input to match your environment. You have a problem with your kafka zookeeper peer

**Comment by Aylr** [comment]
@sparrc I had the same issue and found that by changing a single line in telegraf.conf from:
`zookeeper_chroot = "/"`
to
`zookeeper_chroot = ""`

the error was resolved and I got kafka messages pulled into telegraf.

**Comment by sparrc** [comment]
thx @Aylr, we may want to change this default

**Comment by Aylr** [comment]
And, it's important to note this is a stock install of influxdb, telegraf and zookeeper and kafka with no customizations. Thanks!
