### ISSUE TITLE
Cannot go get Telegraft 0.12.1, lots of "use of internal package not allowed"

### ISSUE THREAD

**Issue by caio1982** [influxdata/telegraf#1114]
Hi, I am trying to package Telegraf and I keep getting the errors below when calling go get. I am using Go 1.6.1 and pulling Telegraf 0.12.1 from git://github.com/influxdb/telegraf.git:

```
$ env GOPATH=/tmp/foobar go get -t -d ./telegraf.git/...

package telegraf/agent
	imports github.com/influxdata/telegraf/internal/config: use of internal package not allowed
package telegraf/agent
	imports github.com/influxdata/telegraf/internal/models: use of internal package not allowed
package telegraf/cmd/telegraf
	imports github.com/influxdata/telegraf/internal/config: use of internal package not allowed
package telegraf/internal/config
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/internal/config
	imports github.com/influxdata/telegraf/internal/models: use of internal package not allowed
package telegraf/plugins/inputs/cloudwatch
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/filestat
	imports github.com/influxdata/telegraf/internal/globpath: use of internal package not allowed
package telegraf/plugins/inputs/httpjson
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/lustre2
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/mqtt_consumer
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/system
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/tcp_listener
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/inputs/zfs
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/amon
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/amqp
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/datadog
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/influxdb
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/kafka
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/librato
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed
package telegraf/plugins/outputs/mqtt
	imports github.com/influxdata/telegraf/internal: use of internal package not allowed

```
Is there any branch with the whole s/influxdata/influxdb issue fixed for a test? I read in other bug reports that this is a known problem to be addressed?

**Comment by sparrc** [comment]
that issue has long been fixed, your telegraf directory needs to be in the influxdata directory, not influxdb

**Comment by caio1982** [comment]
What do you mean? I just git cloned it, checked out f76739cb1bd13d50ceb2d931c21cecd8e6d909f8 and ran that go get command and it failed... also, cloning from influxdata instead from influxdb makes no difference for this problem. What should have been done differently?

**Comment by sparrc** [comment]
Then something is wrong with your Go environment, I'm sorry but I don't have time to debug go environment problems for users

**Comment by caio1982** [comment]
Sorry, but I wasn't asking for you to debug it but simply tell me where and what to look for as I can debug it myself :-) my point is that both on Go 1.5.3 and 1.6.1 only Telegraf shows this problem. I didn't have any issues with the same steps using other Go projects, so I assume it's Telegraf that is misbehaving.

**Comment by sparrc** [comment]
There's nothing wrong with Telegraf builds, I can guarantee that 100%, this might be the only project you're building with internal packages.

BTW, why don't you just use `go get github.com/influxdata/telegraf/...`?

**Comment by caio1982** [comment]
Because code cloning, deps download (the one failing) and actual building need to be executed in separate steps in the packaging I am doing for Snappy Ubuntu Core.

**Comment by sparrc** [comment]
My recommendation would be that you should be cloning your repos into your GOPATH. I think if you try building a Go project with an internal directory you'll get the same results (such as https://github.com/shirou/gopsutil)
