### ISSUE TITLE
/plugins/inputs/vsphere collect ESXi version

### ISSUE THREAD

**Issue by ovdu1** [influxdata/telegraf#11152]
## Feature Request: 
collect ESXi Version and build number
In https://vcenter_url/mob, that information is available at **summary.config.product**

### Use case: 
In a large environment, it would be great to have the ESXi version collected as well so we can see at a glance which hosts are on which build number without having to log into each vCenter manually to get that.

**Comment by powersj** [comment]
Hi,

Can you provide some additional details like:

1) example output of these values
2) how you would like those values parsed and stored? (e.g. desired behavior)
3) do you know if the library we use, [github.com/vmware/govmomi](https://github.com/vmware/govmomi) can query those values

Thanks!
