### ISSUE TITLE
vSphere input plugin CPU Temperature

### ISSUE THREAD

**Issue by maxiride** [influxdata/telegraf#11162]
### Proposal:
Expose CPU Temperature metrics of vSphere  Hosts.

### Current behavior:
The current input plugin (https://github.com/influxdata/telegraf/blob/release-1.22/plugins/inputs/vsphere/README.md) doesn't list the temperature as a data source.

From the documentation (https://developer.vmware.com/apis/358/doc/vim.host.NumericSensorInfo.SensorType.html) it's my understanding that this information is available.

### Desired behavior:
Add the CPUs temperature data to the input plugin.

### Use case: 
Monitor CPU temperature for preemptive alerting when a threshold is reached or when CPU temp is higher than a set value for more than X minutes.
Temperature data over time might also show bad ventilantion\cooling of the unit.

____

Picking up from some questions I saw in another feature request issue:

> Hi,
Can you provide some additional details like:
    1. example output of these values
    2. how you would like those values parsed and stored? (e.g. desired behavior)
    3. do you know if the library we use, [github.com/vmware/govmomi](https://github.com/vmware/govmomi) can query those values

1. Time series expressed in Celsius (possibly fahrenheit)
2. Really don't know
3. I think so as it has the enums here https://github.com/vmware/govmomi/blob/ffd45c83211eacbe546299c1595eccd9322b9e21/vim25/types/enum.go#L1909 but I don't see  any endpoint for it from godoc https://pkg.go.dev/github.com/vmware/govmomi#section-readme

**Comment by powersj** [comment]
Thanks @maxiride for the request and for answering the questions

I believe the next steps are looking into pulling in that additional measurement and what it would take with the existing plugin

**Comment by DStrand1** [comment]
Next steps: put up PR adding this as a new metric field

**Comment by DStrand1** [comment]
@maxiride Are you able to test the artifacts in #16109 to see if this PR fixes your issue? Thanks!

**Comment by maxiride** [comment]
> @maxiride Are you able to test the artifacts in #16109 to see if this PR fixes your issue? Thanks!

Picking this up as soon as I can, will post back the feedback.
