### ISSUE TITLE
Using disk plugin from inside docker container to monitor host

### ISSUE THREAD

**Issue by johnrengelman** [influxdata/telegraf#1116]
Linking from https://github.com/influxdata/telegraf-docker/issues/11 for visibility.

When running `telegraf` from within a docker container, I can't seem to get valid disk usage metrics for the host because it queries based on `mountPoint` as specified in the host's `/etc` configs (which is configurable using the `HOST_ETC` envvar. However, the mountpoints are different (i.e. `/` from inside the container is different than `/` on the host, so querying for usage on the `/` mountPoint is invalid).

It seems that the only way to do this is to mount `/` from the host into the container (as `/rootfs`) and then be able to tell the disk plugin to prefix any mount paths with `/rootfs` before querying (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/ps.go#L85)

**Comment by sparrc** [comment]
Do you have any suggestions for a different behavior? Is there a way that docker containers can access disk stats of the host system without mounting it in the container?

**Comment by johnrengelman** [comment]
I'm looking but this is not my strong area...I'm guessing there must be someway to do it, I'm just not up to snuff on my linux system calls.

**Comment by johnrengelman** [comment]
This is my best lead so far...this is how Prometheus does it (https://github.com/prometheus/node_exporter/blob/master/collector/diskstats_linux.go), I'm pretty sure it works from inside a docker container.
Still digging through the code.

**Comment by johnrengelman** [comment]
Ah yeah...ok..so parse the data from `/proc/diskstats` which gives you metrics by device.
Then you can map the device to the mount point from `/etc/fstab` for reporting.

**Comment by sparrc** [comment]
looks like that's what we do for diskio: https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L275, but for disk usage we call statfs: https://github.com/shirou/gopsutil/blob/master/disk/disk_unix.go

**Comment by johnrengelman** [comment]
oh yeah...wrong one..sorry.
This one - https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_linux.go

**Comment by johnrengelman** [comment]
It reads `/proc/mounts`

**Comment by johnrengelman** [comment]
Again, wrong...it ends up making the same system call. Hmm.

**Comment by sparrc** [comment]
I could be wrong, but I don't think there is a way to get the host system filesystem stats without mounting it in your container, since the container has it's own filesystem.

Unless I'm missing something, I think you'll get the same results using the prometheus exporter

**Comment by johnrengelman** [comment]
Looks like Prometheus has the same problem: https://github.com/prometheus/node_exporter/issues/66

I'm thinking the easiest way ATM would be to `-v /:/rootfs:ro -e HOST_ROOT_FS=/rootfs`

**Comment by johnrengelman** [comment]
Yeah, looks that way. 

What do you think of having some sugar that would allow use to do something like my above comment and then stripping the prefix when it's reported?

**Comment by sparrc** [comment]
I'm not sure I follow, what do you want to strip? `/rootfs`?

**Comment by johnrengelman** [comment]
Yeah.

**Comment by johnrengelman** [comment]
Actually, I think there's an additional issue here.
If I set `ETC_HOST=/rootfs/etc`, the it reads the lists of mounts from the host machine's `/etc/fstab` which won't include the `/rootfs` directory, I just mounted into the container.

**Comment by sparrc** [comment]
hmm why do you need to set `ETC_HOST=/rootfs/etc`?

**Comment by johnrengelman** [comment]
don't have to...but without that, then you'll end up reporting all the mount points within the container, which means any other docker volume you mount will get reported...this isn't really true for host metrics.

**Comment by johnrengelman** [comment]
This change is giving me the behavior that I think is appropriate - https://github.com/influxdata/telegraf/pull/1120

**Comment by sparrc** [comment]
closed by #1120

**Comment by harloveleenKaur** [comment]
@johnrengelman  The same is not working for Redhat .
I have my mount under directory /data on the host .  I did run my contianer as : 
docker run -d --name=telegraf2 --restart=always   -v /:/hostfs   -e HOST_MOUNT_PREFIX=/hostfs -e HOST_ETC=/hostfs/etc  telegraf:alpine	

on a RedHat machine . ( The same is wokring on Ubuntu machine )

df -h shows the /data as mounted . But the metrics are not logged in Telegraf .

**Comment by alex-knyazev** [comment]
> @johnrengelman The same is not working for Redhat .
> I have my mount under directory /data on the host . I did run my contianer as :
> docker run -d --name=telegraf2 --restart=always -v /:/hostfs -e HOST_MOUNT_PREFIX=/hostfs -e HOST_ETC=/hostfs/etc telegraf:alpine
> 
> on a RedHat machine . ( The same is wokring on Ubuntu machine )
> 
> df -h shows the /data as mounted . But the metrics are not logged in Telegraf .

Hi! I have the same problem. Did you fix it?

**Comment by danielnelson** [comment]
This issue is very old, can you check out [this FAQ item](https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container) and open a new issue if you still need help.
