### ISSUE TITLE
NTLM authentication support

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#11184]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

NTLM authentication support. Request for support on the following plugins:

- [ ] InfluxDB v1 & v2 Output
- [ ] Stackdriver Input #9175
- [ ] HTTP Input #9192
  - NTLM authentication is not supported by the default HTTP client in Go as it requires multiple rounds (https://github.com/golang/go/issues/20053).

### Current behavior:
No NTLM proxy support on some plugins

### Desired behavior:
Implement NTLM proxy support on requested plugins

### Use case: 
For InfluxDB Output:
Local Telegraf instance is sending to a corporate proxy that requires NTLM authentication.

**Comment by reimda** [comment]
There is a go module that does NTLM proxy auth and might be useful to implement this feature request.

https://github.com/aus/proxyplease

https://github.com/aus/proxyplease/blob/master/ntlm_windows.go

It's MIT licensed so it should be appropriate for including in telegraf.

**Comment by reimda** [comment]
https://github.com/Azure/go-ntlmssp may also be useful. Thanks @srebhan

**Comment by srebhan** [comment]
Closing as there seems to be no interest in this feature. If you need NTLM please reopen the issue of open a new one!
