### ISSUE TITLE
inputs.zookeeper - Some values are strings instead of integer

### ISSUE THREAD

**Issue by jvino** [influxdata/telegraf#11204]
### Relevant telegraf.conf

```toml
[[inputs.zookeeper]]
   servers = [":2181"]
```

### Logs from Telegraf

```text
None
```

### System info

Centos 7

### Steps to reproduce

1. Configure telegraf.conf with minimal configuration  [[inputs.zookeeper]] servers = [":2181"]
2. Start telegraf service
3. telegraf --test | grep zookeeper

### Expected behavior

zookeeper,port=2181,server=localhost,state=standalone add_dead_watcher_stall_time=0i,approximate_data_size=612673i,avg_chronos_read_per_namespace=1463.1099,avg_chronos_write_per_namespace=255.8824,avg_close_session_prep_time=0.0203,avg_commit_commit_proc_req_queued=0.0,avg_commit_process_time=0.0,avg_commit_propagation_latency=0.0,...

### Actual behavior

zookeeper,port=2181,server=localhost,state=standalone add_dead_watcher_stall_time=0i,approximate_data_size=612673i,avg_chronos_read_per_namespace="1463.1099",avg_chronos_write_per_namespace="255.8824",avg_close_session_prep_time="0.0203",avg_commit_commit_proc_req_queued="0.0",avg_commit_process_time="0.0",avg_commit_propagation_latency="0.0",...

**Comment by powersj** [comment]
Thanks for the bug. I came across this recently looking at integration tests and it seems #8863 was incorrectly closed but does give you a workaround for now. It seems floats are not handled correctly.

**Comment by powersj** [comment]
Closed should work with latest verstion and the parse_floats setting.
