### ISSUE TITLE
[[inputs.net]] to include wlan0 data

### ISSUE THREAD

**Issue by WS-Dave** [influxdata/telegraf#11215]
## Feature Request
Getting the network stats on a remote Raspberry Pi (or any Linux) device that is in a location that requires WiFi (no ethernet available)

Currently, can't get the wlan0 data (as seen in  'cat /proc/net/dev') to get picked up

### Proposal:
Allow wlan[x] stats to be included in the [[inputs.net]] pull

### Current behavior:
[[inputs.net]]
\#   ## By default, telegraf gathers stats from any up interface (excluding loopback)
\#   ## Setting interfaces will tell it to gather these explicit interfaces,
\#   ## regardless of status.
\#
     interfaces = ["wlan0"]
(or the default to include all interfaces) does not seem to pick up 

wlan[x] seems to be ignored

### Desired behavior:
wlan[x] to be included

### Use case: 
Allows monitoring of Limux-based IoT devices that may be WiFi only

thx!

**Comment by powersj** [comment]
Hi,

1. Can you give the output of `ip a`
2. Can you give the logs of telegraf without any interfaces, like the following config:

```
[[inputs.net]]
[[outputs.file]]
```

Here is an example with my laptop:

```
net,host=x1c6,interface=wlp2s0 packets_sent=15285i,packets_recv=191690i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=2745164i,bytes_recv=259037006i 1653789533000000000
net,host=x1c6,interface=all ip_reasmfails=0i,icmp_outparmprobs=0i,icmp_inerrors=0i,tcp_estabresets=2i,ip_outrequests=15184i,ip_outdiscards=20i,udplite_inerrors=0i,ip_reasmoks=0i,icmp_inredirects=0i,tcp_retranssegs=1i,tcp_attemptfails=6i,udplite_ignoredmulti=0i,icmp_inparmprobs=0i,tcp_currestab=13i,ip_inhdrerrors=0i,icmp_indestunreachs=40i,icmp_outredirects=0i,icmp_outtimestamps=0i,icmp_inmsgs=40i,icmp_inechos=0i,tcp_outrsts=151i,udp_rcvbuferrors=9599i,ip_indelivers=142496i,ip_forwarding=2i,icmp_outmsgs=40i,ip_inreceives=143583i,ip_indiscards=0i,icmp_inaddrmaskreps=0i,tcp_outsegs=12259i,tcp_passiveopens=0i,udplite_outdatagrams=0i,icmp_inechoreps=0i,icmp_outerrors=0i,udplite_noports=0i,udplite_rcvbuferrors=0i,ip_defaultttl=64i,icmp_intimeexcds=0i,tcp_inerrs=0i,tcp_rtomin=200i,udplite_memerrors=0i,ip_inunknownprotos=0i,ip_fragfails=0i,icmp_intimestampreps=0i,udp_sndbuferrors=0i,udp_outdatagrams=3029i,udplite_sndbuferrors=0i,ip_forwdatagrams=0i,icmp_outaddrmasks=0i,icmp_outechoreps=0i,icmp_outdestunreachs=40i,icmp_insrcquenchs=0i,udp_ignoredmulti=19i,udp_noports=40i,ip_outnoroutes=4i,icmp_outtimeexcds=0i,icmp_inaddrmasks=0i,icmp_outechos=0i,tcp_maxconn=-1i,udp_indatagrams=120155i,ip_fragcreates=0i,icmp_outtimestampreps=0i,icmp_outaddrmaskreps=0i,icmpmsg_intype3=40i,ip_inaddrerrors=1i,ip_fragoks=0i,udp_inerrors=9599i,udplite_incsumerrors=0i,icmpmsg_outtype3=40i,tcp_rtoalgorithm=1i,tcp_activeopens=212i,udp_incsumerrors=0i,udplite_indatagrams=0i,ip_reasmtimeout=0i,icmp_intimestamps=0i,icmp_incsumerrors=0i,icmp_outsrcquenchs=0i,tcp_incsumerrors=0i,udp_memerrors=0i,ip_reasmreqds=0i,tcp_rtomax=120000i,tcp_insegs=12649i 1653789533000000000
```

**Comment by WS-Dave** [comment]
$ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:43:31:b2 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:16:64:e7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.68.140/24 brd 192.168.68.255 scope global dynamic noprefixroute wlan0
       valid_lft 466sec preferred_lft 391sec
    inet6 fe80::8cdc:804f:73a4:89e3/64 scope link 
       valid_lft forever preferred_lft forever
4: br-97a8defb482b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:ab:2b:61:57 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-97a8defb482b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:abff:fe2b:6157/64 scope link 
       valid_lft forever preferred_lft forever
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ae:bb:59:b1 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aeff:febb:59b1/64 scope link 
       valid_lft forever preferred_lft forever
13: vethac7dfbc@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 0e:10:2a:3d:1d:9d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 169.254.62.245/16 brd 169.254.255.255 scope global noprefixroute vethac7dfbc
       valid_lft forever preferred_lft forever
    inet6 fe80::c10:2aff:fe3d:1d9d/64 scope link 
       valid_lft forever preferred_lft forever
21: veth0f9b911@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 7e:89:f1:2f:4f:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet 169.254.214.20/16 brd 169.254.255.255 scope global noprefixroute veth0f9b911
       valid_lft forever preferred_lft forever
    inet6 fe80::ba0a:3e3f:808a:e6b4/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::7c89:f1ff:fe2f:4fe1/64 scope link 
       valid_lft forever preferred_lft forever
27: veth94d55be@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 56:48:cd:99:a2:a1 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 169.254.170.204/16 brd 169.254.255.255 scope global noprefixroute veth94d55be
       valid_lft forever preferred_lft forever
    inet6 fe80::d46a:84ac:aa34:9438/64 scope link 
       valid_lft forever preferred_lft forever
29: veth1bedaba@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ca:7c:16:5b:40:ed brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet 169.254.223.9/16 brd 169.254.255.255 scope global noprefixroute veth1bedaba
       valid_lft forever preferred_lft forever
    inet6 fe80::c0d5:590a:168:58ed/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::c87c:16ff:fe5b:40ed/64 scope link 
       valid_lft forever preferred_lft forever

and from the log
net,host=raspberrypi,interface=eth0 err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=22895i,bytes_recv=12872i,packets_sent=109i,packets_recv=95i 1653850490000000000
net,host=raspberrypi,interface=all icmp_insrcquenchs=0i,icmp_intimestampreps=0i,icmp_outtimestamps=0i,tcp_rtomin=200i,ip_forwdatagrams=0i,icmp_outtimestampreps=0i,ip_indelivers=60i,icmp_intimeexcds=0i,icmp_inparmprobs=0i,icmp_inechoreps=0i,icmp_outparmprobs=0i,udplite_rcvbuferrors=0i,udplite_sndbuferrors=0i,ip_inhdrerrors=0i,icmp_intimestamps=0i,tcp_outsegs=102i,tcp_inerrs=0i,tcp_currestab=1i,udplite_noports=0i,ip_inreceives=68i,tcp_estabresets=0i,icmp_outsrcquenchs=0i,tcp_passiveopens=0i,ip_outnoroutes=0i,icmp_outtimeexcds=0i,udp_incsumerrors=0i,udp_indatagrams=2i,tcp_activeopens=1i,udp_ignoredmulti=6i,icmp_outechos=0i,tcp_rtoalgorithm=1i,udplite_ignoredmulti=0i,ip_reasmtimeout=0i,icmp_outechoreps=0i,icmp_inmsgs=0i,icmp_inaddrmasks=0i,tcp_rtomax=120000i,ip_outdiscards=0i,ip_reasmfails=0i,tcp_outrsts=1i,tcp_insegs=52i,udp_noports=0i,icmp_outdestunreachs=0i,icmp_outmsgs=0i,ip_forwarding=1i,icmp_inerrors=0i,icmp_outaddrmaskreps=0i,tcp_attemptfails=0i,udp_sndbuferrors=0i,udp_rcvbuferrors=0i,ip_fragfails=0i,ip_reasmoks=0i,udplite_incsumerrors=0i,ip_outrequests=104i,icmp_inredirects=0i,tcp_retranssegs=0i,ip_inaddrerrors=0i,ip_reasmreqds=0i,udp_outdatagrams=2i,udplite_outdatagrams=0i,icmp_outerrors=0i,icmp_outaddrmasks=0i,icmp_inaddrmaskreps=0i,udplite_memerrors=0i,udplite_indatagrams=0i,ip_fragoks=0i,ip_fragcreates=0i,icmp_inechos=0i,icmp_outredirects=0i,tcp_maxconn=-1i,udp_memerrors=0i,ip_indiscards=0i,ip_defaultttl=64i,icmp_incsumerrors=0i,tcp_incsumerrors=0i,udp_inerrors=0i,udplite_inerrors=0i,ip_inunknownprotos=0i,icmp_indestunreachs=0i 1653850490000000000
net,host=raspberrypi,interface=eth0 err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=26019i,bytes_recv=13451i,packets_sent=123i,packets_recv=100i,err_in=0i 1653850500000000000
net,host=raspberrypi,interface=all icmp_insrcquenchs=0i,tcp_retranssegs=0i,udp_rcvbuferrors=0i,udplite_memerrors=0i,icmp_inaddrmasks=0i,icmp_indestunreachs=0i,tcp_rtomin=200i,ip_reasmoks=0i,icmp_incsumerrors=0i,icmp_outaddrmasks=0i,icmp_intimestamps=0i,tcp_attemptfails=0i,icmp_outechos=0i,icmp_inparmprobs=0i,icmp_intimeexcds=0i,udp_outdatagrams=2i,udplite_incsumerrors=0i,udplite_sndbuferrors=0i,udplite_outdatagrams=0i,udp_indatagrams=2i,udp_sndbuferrors=0i,ip_forwdatagrams=0i,ip_fragoks=0i,ip_fragcreates=0i,icmp_inechos=0i,tcp_outrsts=1i,tcp_passiveopens=0i,tcp_outsegs=116i,udp_incsumerrors=0i,icmp_inechoreps=0i,tcp_currestab=1i,tcp_rtomax=120000i,udp_memerrors=0i,udplite_inerrors=0i,ip_inunknownprotos=0i,icmp_outparmprobs=0i,icmp_outsrcquenchs=0i,udp_ignoredmulti=6i,icmp_outerrors=0i,icmp_outaddrmaskreps=0i,icmp_inmsgs=0i,ip_outdiscards=0i,ip_outnoroutes=0i,ip_inaddrerrors=0i,ip_reasmtimeout=0i,icmp_inredirects=0i,icmp_outtimeexcds=0i,tcp_incsumerrors=0i,udplite_indatagrams=0i,ip_inhdrerrors=0i,ip_outrequests=118i,tcp_estabresets=0i,udplite_rcvbuferrors=0i,ip_inreceives=73i,ip_indiscards=0i,icmp_outdestunreachs=0i,icmp_outredirects=0i,tcp_activeopens=1i,ip_reasmfails=0i,ip_reasmreqds=0i,tcp_rtoalgorithm=1i,tcp_insegs=57i,ip_defaultttl=64i,icmp_inaddrmaskreps=0i,icmp_outechoreps=0i,tcp_inerrs=0i,tcp_maxconn=-1i,ip_fragfails=0i,icmp_outtimestamps=0i,icmp_intimestampreps=0i,udp_noports=0i,udp_inerrors=0i,udplite_ignoredmulti=0i,udplite_noports=0i,ip_forwarding=1i,ip_indelivers=65i,icmp_outtimestampreps=0i,icmp_inerrors=0i,icmp_outmsgs=0i 1653850500000000000
net,host=raspberrypi,interface=eth0 bytes_recv=14162i,packets_sent=137i,packets_recv=107i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=29109i 1653850510000000000
net,host=raspberrypi,interface=all ip_reasmfails=0i,icmp_outerrors=0i,icmp_outparmprobs=0i,tcp_outrsts=1i,tcp_activeopens=1i,ip_fragcreates=0i,ip_forwarding=1i,icmp_outdestunreachs=0i,icmp_outaddrmaskreps=0i,tcp_inerrs=0i,udp_memerrors=0i,udplite_noports=0i,udplite_rcvbuferrors=0i,ip_reasmoks=0i,udplite_ignoredmulti=0i,udp_sndbuferrors=0i,udplite_incsumerrors=0i,udplite_memerrors=0i,udplite_outdatagrams=0i,ip_inunknownprotos=0i,icmp_indestunreachs=0i,icmp_outmsgs=0i,icmp_inparmprobs=0i,tcp_rtoalgorithm=1i,tcp_outsegs=130i,icmp_intimestamps=0i,icmp_outtimestamps=0i,icmp_outtimeexcds=0i,tcp_incsumerrors=0i,tcp_insegs=64i,icmp_intimestampreps=0i,ip_outnoroutes=0i,tcp_currestab=1i,ip_indiscards=0i,icmp_inaddrmasks=0i,icmp_outechoreps=0i,tcp_rtomax=120000i,udp_incsumerrors=0i,udp_ignoredmulti=6i,udp_noports=0i,ip_fragfails=0i,icmp_inredirects=0i,icmp_outtimestampreps=0i,udp_indatagrams=2i,icmp_intimeexcds=0i,tcp_estabresets=0i,udplite_inerrors=0i,icmp_inechoreps=0i,tcp_maxconn=-1i,udp_rcvbuferrors=0i,ip_reasmtimeout=0i,tcp_rtomin=200i,icmp_outaddrmasks=0i,ip_defaultttl=64i,icmp_outechos=0i,ip_forwdatagrams=0i,icmp_outredirects=0i,tcp_attemptfails=0i,icmp_insrcquenchs=0i,icmp_inaddrmaskreps=0i,icmp_incsumerrors=0i,icmp_inmsgs=0i,udp_inerrors=0i,udplite_indatagrams=0i,udplite_sndbuferrors=0i,ip_inreceives=80i,ip_inhdrerrors=0i,ip_outrequests=132i,ip_reasmreqds=0i,icmp_inechos=0i,icmp_outsrcquenchs=0i,tcp_retranssegs=0i,ip_indelivers=72i,ip_inaddrerrors=0i,ip_outdiscards=0i,icmp_inerrors=0i,tcp_passiveopens=0i,udp_outdatagrams=2i,ip_fragoks=0i 1653850510000000000
net,host=raspberrypi,interface=eth0 bytes_recv=14915i,packets_sent=152i,packets_recv=115i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=32255i 1653850520000000000
net,host=raspberrypi,interface=all ip_inunknownprotos=0i,ip_fragfails=0i,tcp_currestab=1i,tcp_passiveopens=0i,ip_inreceives=87i,icmp_incsumerrors=0i,icmp_inmsgs=0i,icmp_intimestamps=0i,icmp_outerrors=0i,udplite_inerrors=0i,ip_forwarding=1i,icmp_outtimestampreps=0i,tcp_rtomax=120000i,icmp_inredirects=0i,icmp_intimeexcds=0i,icmp_inaddrmasks=0i,tcp_incsumerrors=0i,tcp_rtomin=200i,udplite_sndbuferrors=0i,udplite_incsumerrors=0i,ip_reasmfails=0i,udplite_rcvbuferrors=0i,ip_defaultttl=64i,ip_inhdrerrors=0i,ip_outdiscards=0i,icmp_inechoreps=0i,ip_inaddrerrors=0i,icmp_inerrors=0i,tcp_retranssegs=0i,udp_indatagrams=2i,ip_indiscards=0i,icmp_outechos=0i,icmp_outredirects=0i,icmp_inaddrmaskreps=0i,tcp_rtoalgorithm=1i,udplite_noports=0i,icmp_intimestampreps=0i,icmp_outaddrmasks=0i,udplite_outdatagrams=0i,ip_fragcreates=0i,icmp_inparmprobs=0i,tcp_insegs=71i,ip_reasmtimeout=0i,ip_fragoks=0i,icmp_outtimeexcds=0i,icmp_outechoreps=0i,icmp_indestunreachs=0i,tcp_outsegs=144i,udp_inerrors=0i,udp_sndbuferrors=0i,udp_memerrors=0i,udp_incsumerrors=0i,udplite_indatagrams=0i,ip_reasmoks=0i,ip_outrequests=146i,ip_outnoroutes=0i,icmp_insrcquenchs=0i,udplite_memerrors=0i,ip_indelivers=79i,ip_reasmreqds=0i,icmp_outmsgs=0i,tcp_attemptfails=0i,tcp_outrsts=1i,tcp_estabresets=0i,tcp_activeopens=1i,udp_outdatagrams=2i,udp_noports=0i,ip_forwdatagrams=0i,icmp_inechos=0i,icmp_outtimestamps=0i,tcp_maxconn=-1i,udp_ignoredmulti=6i,udplite_ignoredmulti=0i,icmp_outaddrmaskreps=0i,icmp_outdestunreachs=0i,udp_rcvbuferrors=0i,icmp_outsrcquenchs=0i,icmp_outparmprobs=0i,tcp_inerrs=0i 1653850520000000000
net,host=raspberrypi,interface=eth0 err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=35332i,bytes_recv=15560i,packets_sent=166i,packets_recv=121i,err_in=0i 1653850530000000000


Thank you for looking at this!

**Comment by WS-Dave** [comment]
indeed - telegraf is running in a Docker container
via (including the host proc)

sudo docker run -itd  --restart=always --user 999:994 --name=telegraf       -e HOST_PROC=/host/proc -v /proc:/host/proc:ro -v /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf 

Perhaps - I have an issue with the syntax?

Thx!

**Comment by powersj** [comment]
You will need to add `--net=host` to monitor your host's network devices. By default, the container is in a different namespace. By adding the option I mentioned will put it in the same namespace as the host to see the various containers.

Assuming your user is in the 'docker' group, you can avoid using sudo and omit the user options:

```s
$ docker run -it --name=telegraf --net=host -e HOST_PROC=/host/proc -v /proc:/host/proc:ro -v ~/telegraf/config.toml:/etc/telegraf/telegraf.conf:ro telegraf
2022-06-06T14:28:14Z I! Using config file: /etc/telegraf/telegraf.conf
2022-06-06T14:28:14Z I! Starting Telegraf 1.22.4
2022-06-06T14:28:14Z I! Loaded inputs: net
2022-06-06T14:28:14Z I! Loaded aggregators: 
2022-06-06T14:28:14Z I! Loaded processors: 
2022-06-06T14:28:14Z I! Loaded outputs: file
2022-06-06T14:28:14Z I! Tags enabled: 
2022-06-06T14:28:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
net,interface=enp6s0 err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=11034071i,bytes_recv=367419336i,packets_sent=67239i,packets_recv=273137i 1654525700000000000
net,interface=virbr0 err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=0i,bytes_recv=0i,packets_sent=0i,packets_recv=0i 1654525700000000000
net,interface=docker0 packets_sent=245i,packets_recv=0i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=25434i,bytes_recv=0i 1654525700000000000
net,interface=lxdbr0 drop_in=0i,drop_out=0i,bytes_sent=64116i,bytes_recv=7937i,packets_sent=342i,packets_recv=45i,err_in=0i,err_out=0i 1654525700000000000
net,interface=vethf6163e54 packets_recv=45i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i,bytes_sent=64116i,bytes_recv=8567i,packets_sent=342i 1654525700000000000
net,interface=all icmp_outmsgs=3i,icmpmsg_outtype3=2i,tcp_activeopens=648i,tcp_retranssegs=34i,ip_outdiscards=1i,ip_forwarding=1i,icmp_intimestamps=0i,udp_outdatagrams=14326i,udplite_noports=0i,ip_fragoks=0i,icmp_outparmprobs=0i,icmp_outechoreps=0i,icmp_outsrcquenchs=0i,tcp_rtoalgorithm=1i,udp_inerrors=0i,icmp_intimeexcds=0i,icmp_inredirects=0i,icmp_indestunreachs=0i,udp_incsumerrors=0i,ip_inhdrerrors=0i,ip_forwdatagrams=39i,ip_reasmreqds=0i,tcp_rtomax=120000i,ip_reasmfails=0i,icmp_inparmprobs=0i,icmp_inaddrmasks=0i,icmp_inechos=0i,tcp_incsumerrors=0i,tcp_attemptfails=10i,ip_outrequests=67597i,ip_inaddrerrors=0i,udplite_memerrors=0i,tcp_outsegs=53347i,tcp_currestab=17i,ip_inunknownprotos=0i,tcp_passiveopens=0i,ip_fragfails=0i,icmp_intimestampreps=0i,tcp_insegs=59167i,udplite_ignoredmulti=0i,udplite_rcvbuferrors=0i,ip_reasmoks=0i,ip_outnoroutes=0i,icmp_inerrors=0i,icmp_outaddrmaskreps=0i,icmp_outredirects=1i,ip_inreceives=89832i,ip_fragcreates=0i,icmp_outtimeexcds=0i,icmp_inmsgs=0i,udp_rcvbuferrors=0i,udp_sndbuferrors=0i,udplite_inerrors=0i,ip_indiscards=0i,icmp_inechoreps=0i,icmpmsg_outtype5=1i,tcp_outrsts=387i,tcp_rtomin=200i,udp_ignoredmulti=348i,udp_indatagrams=47067i,icmp_insrcquenchs=0i,icmp_outdestunreachs=2i,icmp_outechos=0i,icmp_outaddrmasks=0i,icmp_outtimestampreps=0i,tcp_estabresets=39i,ip_indelivers=89754i,icmp_outerrors=0i,udp_noports=0i,udplite_incsumerrors=0i,udplite_indatagrams=0i,udplite_sndbuferrors=0i,icmp_incsumerrors=0i,udp_memerrors=0i,icmp_outtimestamps=0i,icmp_inaddrmaskreps=0i,tcp_inerrs=0i,tcp_maxconn=-1i,udplite_outdatagrams=0i,ip_reasmtimeout=0i,ip_defaultttl=64i 1654525700000000000

```

**Comment by WS-Dave** [comment]
Thank you!
I added
--net=host
and all interfaces started reporting.

I changed the config file to just include
interfaces = ["wlan0"]
and things are working perfectly!

I am using the docker user - but I'm still not having success skipping the sudo and user bits.  A battle for another day. :)

Thanks again!
