### ISSUE TITLE
Undocumented regression in `temp` plugin

### ISSUE THREAD

**Issue by quentinmit** [influxdata/telegraf#11294]
### Relevant telegraf.conf

```toml
[[inputs.temp]]
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.22.4 on Debian 11

### Steps to reproduce

1. Configure Telegraf with a bare `temp` input on a Linux system that has `hwmon` devices.

### Expected behavior

In older versions (at least Telegraf <=1.17.3 but I haven't exhaustively tested), each temperature from `/sys/class/hwmon/*/temp_*` is exposed as a stream with a `sensor` tag derived from the filename in `/sys`:

```
sensor=coretemp_core0_critalarm
sensor=coretemp_core0_input
sensor=coretemp_core0_max
sensor=coretemp_core1_crit
sensor=coretemp_core1_critalarm
sensor=coretemp_core1_input
sensor=coretemp_core1_max
...
```

This is also what is documented in the `temp` plugin's README.

### Actual behavior

In new builds (at least Telegraf >=1.22.4, sorry I have't bisected) only the `/sys/class/hwmon/*/temp_*_input` temperatures are exposed:

```
sensor=coretemp_core0
sensor=coretemp_core1
...
```

which means that the max/crit/etc. values are no longer being reported anywhere, nor are any sensors that don't follow the pattern of `temp_*_input`. It looks like this was broken when you pulled in https://github.com/shirou/gopsutil/pull/905

I'm not sure what you should do to fix this now, but metrics shouldn't have undocumented regressions in their structure like this between versions. Ideally you would revert back to the old behavior because there is now missing data, in addition to the schema change. It looks like `gopsutil` now exposes the max and crit levels as fields that you could turn into metrics, but the other values are just dropped by `gopsutil`.

**Comment by quentinmit** [comment]
It's not just `_critalarm` that would still be missing; e.g. one of my systems has `_alarm` and `_min` that wouldn't be exposed. See the docs at https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface - there are a ton of different possible fields (and the names are up to each driver so they're not super consistent across chipsets). Note that a few of them (e.g. `*alarm`) are bitmasks and not actually temperatures in degrees Celsius, so it was always a little weird that they were reported as `temp` measurements. I like what you've done with mapping them to fields.

Probably this needs to be fixed upstream in `gopsutil` to correctly bring back all the values. I'm guessing they just didn't test their change on a large enough variety of systems to discover how inconsistent the `hwmon` files are.

**Comment by quentinmit** [comment]
Testing the artifacts from #11301 on one of my machines, I get:

```
# 1.17.3:
nvme_composite_alarm temp=0
nvme_composite_crit temp=84.85
nvme_composite_input temp=49.85
nvme_composite_max temp=81.85
nvme_composite_min temp=-273.15
nvme_sensor1_input temp=49.85
nvme_sensor1_max temp=65261.85
nvme_sensor1_min temp=-273.15
nvme_sensor2_input temp=54.85
nvme_sensor2_max temp=65261.85
nvme_sensor2_min temp=-273.15
k10temp_tctl_input temp=51.375
k10temp_tdie_input temp=51.375
# 1.23.0:
nvme_composite temp=49.85
nvme_sensor_1 temp=49.85
nvme_sensor_2 temp=54.85
k10temp_tctl temp=50.5
k10temp_tdie temp=50.5
# #11301
nvme_composite_crit temp=84.85
nvme_composite_max temp=81.85
nvme_composite_input temp=49.85
nvme_sensor_1_crit temp=0
nvme_sensor_1_max temp=65261.85
nvme_sensor_1_input temp=49.85
nvme_sensor_2_crit temp=0
nvme_sensor_2_max temp=65261.85
nvme_sensor_2_input temp=54.85
k10temp_tctl_crit temp=0
k10temp_tctl_max temp=0
k10temp_tctl_input temp=50
k10temp_tdie_crit temp=0
k10temp_tdie_max temp=0
k10temp_tdie_input temp=50
```

As expected, `_alarm` and `_min` are still missing.

You're reporting new `max` and `crit` streams with a value of 0 for `k10temp` which isn't supposed to have them. (But 0 is also a valid value for `max` or `crit`, so you can't just ignore a value of 0... this is a painfully broken API.)

And finally, this is specific to Linux... I don't have a Windows machine handy but I would imagine their sensors don't follow this naming convention, so make sure you're not introducing a new regression on non-Linux platforms.

**Comment by srebhan** [comment]
Attempted fix in https://github.com/shirou/gopsutil/pull/1546.
