### ISSUE TITLE
Rewrite the Telegraf CLI

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#11316]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

The current CLI options and flags have naturally grown over the 6-7 years as the capabilities of Telegraf have grown. However, there are some best practices and consistencies that Telegraf's CLI could use. For example, having Telegraf follow the format `telegraf <subcommand> <options>` for all operations.

Internally, options are duplicated across declaration + documentation and it is commonly out of date missing values, or entirely wrong.

In doing this, the Telegraf binary can also grow new features more easily and have them contained to specific subcommands.

### Desired behavior:

```bash
$ ./telegraf
The plugin-driven server agent for collecting and reporting metrics.

Telegraf is a plugin-driven agent and has the concept of 4 distinct plugin types:
  1. Input Plugins: collect metrics from the system, services, or 3rd party APIs
  2. Output Plugins: write metrics to various destinations
  3. Processor Plugins: transform, decorate, and/or filter metrics
  4. Aggregator Plugins: create aggregate metrics (e.g. mean, min, max, quantiles, etc.)
 
Usage:
  telegraf [flags]
  telegraf [command]

Available Commands:
  config     Get example config
  help       Help about any command
  list       List available plugins
  minify     Build minimal telegraf based on a config
  run        Run telegraf with a provided config
  version    Print version of Telegraf
```

I would be a big fan of implementing this with [urfave/cli](https://github.com/urfave/cli) as it is lightweight and [well documented](https://cli.urfave.org/v2/).

As a part of this effort each option will need to be tested to ensure operation across Windows, macOS, and Linux/BSD environments.

See https://github.com/influxdata/telegraf/issues/9835, https://github.com/influxdata/telegraf/issues/10356 https://github.com/influxdata/telegraf/issues/8854 for other related CLI issues

**Comment by powersj** [comment]
next steps: flush out all the details of what commands, subcommands, and test matrix for each.

**Comment by sjwang90** [comment]
We'll want to make sure people who have scripts that are using the current commands won't have too many issues with any rewrite.

**Comment by sspaink** [comment]
Tasks

* Add new command `list` to replace `--deprecation-list, --input-list, --output-list`: https://github.com/influxdata/telegraf/issues/11739
*

**Comment by sspaink** [comment]
Future discussion points:
* Consider deprecate `--usage` flag in favor of using filtering with sample config
* Consider not doing "run" to avoid causing too much inconvenience for existing users
* Discuss list command, one word (list deprecation) or two words (list-deprecation)

**Comment by powersj** [comment]
As we are not planning on doing a Telegraf 2.x at this time anymore, I am closing breaking changes issues and PRs. While we have interest in making these improvements we currently, and for the foreseeable future do not have the capital to maintain two major versions while also supporting our users at the same level.
