### ISSUE TITLE
URL监控不反回响应码

### ISSUE THREAD

**Issue by shaojiechao** [influxdata/telegraf#11330]
1.当被监控的URL所在服务down掉时，通过夜莺的即时查询无法查询到该监控URL的任何信息
2. 当被监控URL所有服务正常时，可以正常查询到该URL的正常返回值
配置如下：
![image](https://user-images.githubusercontent.com/95906788/174727036-14fc18e2-a861-4f45-93bb-1bad7f573f43.png)
服务挂掉时的查询结果：
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/95906788/174727141-f2513ac1-1473-44dd-8d92-4f078260df99.png">
当服务正常时的查询结果：
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/95906788/174727249-11768521-1bd6-409c-ae99-954064d58cd1.png">

**Comment by srebhan** [comment]
Please use English only for issues. I will close this, but please feel free to either reopen the issue and change the title and description, or create a new one in English. Thank you!
