### ISSUE TITLE
Move agent sample config into seperate file

### ISSUE THREAD

**Issue by skillor** [influxdata/telegraf#11331]
### Proposal:

I would like to move the default agent config into a seperate file.

### Current behavior:

The default agent config is here in the code:
https://github.com/influxdata/telegraf/blob/9a9f4021dc35f99174257f1bab90e7d9ecd90505/config/config.go#L342-L433

### Desired behavior:

It would be better if it is in an extra file (similar to the sample.conf in the plugins).

### Use case: 
For example I would like to fetch only the default agent config from the Github API.

**Comment by powersj** [comment]
Keep in mind, you can get that data via `telegraf config` as well.
