### ISSUE TITLE
Procstat plugin - add use_sudo option

### ISSUE THREAD

**Issue by Tulux** [influxdata/telegraf#11352]
## Feature Request

Some metrics such as num_fds or read_bytes are not available or return 0 unless the whole agent is run as root. However running a service as root which may interact with many components or service should be discouraged. Moreover official telegraf RPM creates a telegraf user to be run as.
Therefore various plugins seem to be using a "use_sudo" parameter to work-around this limitation.
My request is to add this parameter to this plugin too.

### Proposal:

Adding "use_sudo" to avoid running Telegraf as root for various metrics.

### Current behavior:

num_fds or I/O metrics may not return anything, while other such as memory_data or memory_swap return 0.

### Desired behavior:

Getting all requested metrics with accurate values.

### Use case:
Install official Telegraf RPM on Rhel 8, then use this configuration:
```
[[inputs.procstat]]
  name_suffix = "<MY_SUFFIX>"
  cgroup = "<MY_CGROUP>"
  pid_tag = true
  fieldpass = [ "cpu_usage", "memory_usage", "memory_data", "memory_rss", "memory_stack", "memory_swap", "memory_vms", "num_threads", "num_fds", "pid_count", "read_bytes", "read_count", "write_bytes", "write_count" ]
```

**Comment by Tulux** [comment]
Hi Joshua,

Thank you for your reply however I am not sure to understand your wish.
I have created #11389 which contains a basic commit on branch procstat_sudo including the config option in the README for the end user. I have looked at the code but it doesn't seem to execute any commands (except for getting some information from a systemd unit) unlike the LVM plugin but it calls a library dependency instead (github.com/shirou/gopsutil/v3/process) so at this stage I don't really know how to get a privilege escalation.

Florent

**Comment by powersj** [comment]
Hi,

Thanks for taking a look and thank you very much for taking the time to start a PR!

At the bottom of the sample config, you will see that the default option when running is to use the [pgrep](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/sample.conf#L45) command. That command is [shelled out](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/pgrep.go#L66). Could try putting a sudo in front of that command, since you are not changing the `pid_finder` option and see if it works?

If this works, we would need to specify in the README that the use sudo would only apply with pgrep.

Thanks!

**Comment by reimda** [comment]
Since the associated PR is closed, should we close this issue too?

**Comment by Tulux** [comment]
I have created this issue to report a limitation with the procstat plugin not being run under root user (most distros telegraf package use a dedicated user instead).
Although at this stage I don't know how to solve it, I don't think this issue should be closed.

**Comment by powersj** [comment]
@Tulux 

Looping back around on this one. Your original config used the `cgroup` functionality of the procstat plugin. In this case, it appears we call `filepath.Glob(procsPath)` to gather the various files under the directory in question. Glob won't be able to read some of the files in your case, and it ignored errors when run.

Unfortunately, without permissions to read the files or folders it is not clear there is anything to do in this case.

**Comment by Tulux** [comment]
Indeed permissions are definitely required. I worked-around this limitation by creating a script that uses **sudo** (https://github.com/Tulux/cgroup-metrics). It is not ideal since it requires a sudo configuration, plus sudo is time-cpu intensive but it works.
