### ISSUE TITLE
[outputs.cloudwatch] proxy support

### ISSUE THREAD

**Issue by scholz** [influxdata/telegraf#11388]
## Feature Request
Add proxy config option for cloudwatch output plugin (input plugin received this a while ago: [#8904](https://github.com/influxdata/telegraf/issues/8904)).

### Proposal:
Additional option "http_proxy" for outputs.cloudwatch similiar to inputs.cloudwatch. It should also allow user credentials or respect environment vars.

### Current behavior:
Communication in proxy situation fails

### Desired behavior:
Communication is done used proxy

### Use case: 
We are trying to connect to aws cloudwatch from a containerized telegraf inside a company network through a proxy. Despite our best efforts cant get it workingr (efforts: /etc/environment into container, setting env vars for the container when starting). Everything works when no proxy is present.

**Comment by reimda** [comment]
The cloudwatch output uses the go module github.com/aws/aws-sdk-go-v2/service/cloudwatch. It's using defaults now but has the option of taking a custom http client which can be configured to take a proxy.

Are you able to put together a PR to make this change? Thanks!
