### ISSUE TITLE
Mac app bundles are versionless

### ISSUE THREAD

**Issue by lashomb** [influxdata/telegraf#11392]
**Issue:**
You can see this if you 'Get Info' on the app bundle in the Finder; It just shows `Version: --`. Likewise, reviewing the list in the System Information utility -> Software -> Applications shows a blank entry. 

In inspecting both the arm64 and amd64 app bundles, their embedded `Info.plist` files are lacking some key fields that macOS uses to determine the installed version.
- CFBundleShortVersionString
- CFBundleVersion

**Request:**
Can we get these added in builds going forward? Software management tools on macOS endpoints rely on this common mechanism used by the OS.

![Screen Shot 2022-06-24 at 4 23 41 PM](https://user-images.githubusercontent.com/532241/175691947-47f942ac-2853-4d12-ae23-7597142b4969.png)

**Comment by lashomb** [comment]
Another example of an opensource project adding in support for macOS versioning. https://github.com/osquery/osquery/pull/7452

**Comment by sspaink** [comment]
@lashomb Thank you for reporting this issue! I've created a pull request that should fix this, once merged it will be included in the following patch or minor release.
