### ISSUE TITLE
Factor out service inputs to an own subdirectory/section

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#11418]
## Feature Request

Currently, gathering input plugins and service input plugins (aka `listeners`) are  mixed in the `plugins/inputs` subdirectory and subsequently share the same TOML prefix. As the naming convention of appending `_listener` is both bulky and not always followed :-) it is sometimes impossible to tell them apart without looking to the code.

### Proposal:

Move all `listener`/service input plugins to a new subdir `plugins/serviceinputs` and also change the TOML section to reflect the change. This way it is easier to know what to expect in both editing/reading the config and reviewing code.

### Current behavior:

Inputs and service-inputs are mixed.

### Desired behavior:

Clearly be able to tell apart both categories without looking at the code.

**Comment by Hipska** [comment]
As a con, users will now need to look into 2 lists to find a plugin they need or want to use.

**Comment by srebhan** [comment]
Closing this as we won't get to it in a foreseeable future...
