### ISSUE TITLE
Prometheus format is not working with http_listener_v2 input

### ISSUE THREAD

**Issue by orangedeng** [influxdata/telegraf#11425]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
  service_address = ":8087"
  paths = ["/metrics/job/my_job"]
  data_format = "prometheus"
```

### Logs from Telegraf

```text
[inputs.http_listener_v2] Parse error: reading text format failed: text format parsing error in line 1: invalid metric name
```

### System info

Telegraf v1.23.0

### Steps to reproduce

1. I am using a prometheu client-go to push metrics to telegraf, example codes are following:
```go
func ReportPrometheus() {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewBuildInfoCollector())
	reg.MustRegister(collectors.NewGoCollector(
		collectors.WithGoCollections(collectors.GoRuntimeMemStatsCollection | collectors.GoRuntimeMetricsCollection),
	))
	push.New("http://192.168.99.171:8087", "my_job").Gatherer(reg).Push()
}
```
2. start telegraf to accept metrics with debug= true
3. error occurs.

### Expected behavior

As [docs](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/prometheus/README.md): 

> The metrics are parsed directly into Telegraf metrics. 

### Actual behavior

Reply errors.

### Additional info

With the metrics push format change to `expfmt.FmtText` from  package `"github.com/prometheus/common/expfmt"`, I can get it working.

But I think it is because the headers needed from `prometheus` [parse](https://github.com/influxdata/telegraf/blob/v1.23.0/plugins/parsers/prometheus/parser.go#L24) are not injected by http listener.

**Comment by reimda** [comment]
The configuration you shared tells telegraf to listen for prometheus text format over http. It doesn't look like your code is compatible with this (unless you switch to expfmt.FmtText).

Have you tried using the prometheus input plugin instead of http_listener_v2 with prometheus data_format? I think it will do what you want. https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md

**Comment by orangedeng** [comment]
I read through the prometheus input docs and I think it doesn't meet my requirement. As the configuration above, I would like to use telegraf as prometheus push gateway role. My real apps will send data to telegraf via http.

**Comment by orangedeng** [comment]
Seems like the proper way to do this is using `expfmt.FmtText`. Thanks for supporting.

**Comment by kakazxl** [comment]
"Additional info
With the metrics push format change to expfmt.FmtText from package "github.com/prometheus/common/expfmt", I can get it working."

could you please give an example of calling push.Fomat()? I change to expfmt.FmtText but still get an error. thanks
