### ISSUE TITLE
plugin sqlserver : prefix ?

### ISSUE THREAD

**Issue by glz-io** [influxdata/telegraf#1143]
Hi,

Do you think it is possible to add a prefix for all metrics ?

At the moment, all measurements are directly in influxdb in the middle of all my linux and windows measurements.

For example:
```
SHOW MEASUREMENTS
[...]
XTP Memory Used (KB) | _Total | Databases
XTP Memory Used (KB) | mssqlsystemresource | Databases
apache
arbor_cpu_15min_used
arbor_cpu_1min_used
arbor_cpu_5min_used
arbor_disk_used
arbor_memory_used
arbor_swap_used
cisco_cpu_1min_used
cisco_cpu_5min_used
cisco_cpu_5sec_used
cisco_memory_free
cisco_memory_used
cpu
disk
[...]
```

Is it possible to have something like:
```
sqlserver_
```

Or a custom field in the config ?

Regards

**Comment by sparrc** [comment]
use `name_prefix`: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-configuration

**Comment by glz-io** [comment]
OK, I forgot about this.

Thanks.
