### ISSUE TITLE
telegraf.go contains a non-existent imports

### ISSUE THREAD

**Issue by Selen34** [influxdata/telegraf#11441]
### Relevant telegraf.conf

```toml
conf just from master branch
```

### Logs from Telegraf

```text
no logs
```

### System info

master branch, OS Windows 10

### Steps to reproduce

there're imports in cmd/telegraf/telegraf.go:
```
import (
...
	"github.com/coreos/go-systemd/daemon"
	"github.com/influxdata/tail/watch"
...
```
But there're not downlable:
https://github.com/coreos/go-systemd/daemon - 404
https://github.com/influxdata/tail/watch - 404

### Expected behavior

imports exists

### Actual behavior

imports not exists

**Comment by powersj** [comment]
Hi,

The go import statements do not always map to a valid URL. For those import statements you are after:

- https://github.com/coreos/go-systemd/ -> [daemon module](https://github.com/coreos/go-systemd/tree/main/daemon)
- https://github.com/influxdata/tail/  -> [watch module](https://github.com/influxdata/tail/tree/master/watch)
