### ISSUE TITLE
invalid version: unknown revision 000000000000

### ISSUE THREAD

**Issue by Selen34** [influxdata/telegraf#11442]
### Relevant telegraf.conf

```toml
just from master branch
```

### Logs from Telegraf

```text
no log
```

### System info

master branch, OS Windows

### Steps to reproduce

1. git pull (from master)
2. try sync all dependencies (I use jetbrains goland)
3.  - error:
```
go: google.golang.org/grpc/naming@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

### Expected behavior

all dependencies are sync

### Actual behavior

error while sync dependencies

**Comment by powersj** [comment]
Hi,

This sounds like an issue with your IDE or some other import. Telegraf does not use this module:

```
❯ go mod why -m google.golang.org/grpc/naming
# google.golang.org/grpc/naming
(main module does not need module google.golang.org/grpc/naming)
```

**Comment by zhangxinming1991** [comment]
go list -m all
go: google.golang.org/grpc/naming@v0.0.0-00010101000000-000000000000:

**Comment by zhangxinming1991** [comment]
i foud the error happend when run go list @powersj

**Comment by conrad784** [comment]
I did not further look into why this is happening, but it was fixed after updating my go v1.16 to the latest v1.19.

**Comment by zak-pawel** [comment]
@conrad784 I have `go version go1.19 linux/amd64` and after I call `go list -m all` I get:
```
go: google.golang.org/grpc/naming@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

I opened an issue for that: https://github.com/lxc/lxd/issues/10745

Workaround for working smoothly with Telegraf in GoLand would be to remove (locally) this directory: `tools/package_lxd_test` and run `go mod tidy`. After that GoLand will index everything.

**Comment by zak-pawel** [comment]
Even nicer workaround:
Add `replace google.golang.org/grpc/naming => google.golang.org/grpc v1.29.1` in Telegraf's `go.mod`

**Comment by powersj** [comment]
> Even nicer workaround: Add `replace google.golang.org/grpc/naming => google.golang.org/grpc v1.29.1` in Telegraf's `go.mod`

Would you be willing to put up a PR for this?
