### ISSUE TITLE
Update measurements descriptions in elasticsearch input README

### ISSUE THREAD

**Issue by ktosiek** [influxdata/telegraf#1145]
EDIT: Turns out the described issue is only a problem with README, not with the current plugin.

It looks like the elasticsearch input plugin creates a huge amount of measurements, including multiple measurements for cpu and memory.
I think those should be merged into fewer measurements with multiple fields for ease of querying and for consistency with similar data in other plugins (like system's cpu/mem).

**Comment by sparrc** [comment]
What version of Telegraf are you using? I'm fairly certain elasticsearch puts its fields into just a few measurements.

**Comment by sparrc** [comment]
Actually I can see now that the README is out of date, is that what you're basing this off of?

**Comment by ktosiek** [comment]
Yes - I haven't tried it yet, and the README scared me a bit :-)
In that case I'll update the issue description.
