### ISSUE TITLE
Feature : Separating variables in OPCUA Plugin in multiple reads

### ISSUE THREAD

**Issue by CamilleLOISEAU** [influxdata/telegraf#11455]
## Feature Request

In order to bypass the MaxNodesPerRead limitation of an OPC UA server, we would like a way to spread the variables we need to read in multiple reads in a single input.

Currently, we are trying to read more than 100 variables in a single input.opcua from an OPC UA server that has the MaxNodesPerRead parameter at 100. 

### Proposal:

Having a parameter to create a new reading inside an opc ua input. We have tested this in a OPC UA Client made with Python and it is possible to read more than 100 variables when they are spread in multiple readings.

### Current behavior:

If we try to read more variables than the amount of MaxNodesPerRead, we get a StatusBadTooManyOperations error, no matter how many input.opcua.groups we use in the plugin.

### Desired behavior:

Being able to have as many separate readings inside the same input.opcua plugin.

### Use case: 

Reading values from an OPC UA server that has fixed parameters and that we want to pull a lot of different variables from.

**Comment by R290** [comment]
See: https://community.influxdata.com/t/telegraf-opcua-input-plugin-statusbadtoomanyoperations/25216. You need to split the configuration into separate plugins (you're allowed to have multiple). To reduce excessive load on the server you can use the `collection_offset` option.

**Comment by powersj** [comment]
@CamilleLOISEAU, hoping you saw the above message about splitting your configuration up to avoid the load and too many reads.

Hopefully that has resolved your issue. I am going to go ahead and close this issue.
