### ISSUE TITLE
curl request to send json input to tcp listener

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/telegraf#1147]
Hey ,

I was unable to send json data to telegraf using tcp listener using either curl or our server programs too. IT says unable to parse json and try reading the headers passed through json. Can you send an example to pass json data to tcp listener in telegraf.

**Comment by sparrc** [comment]
yes, in the input docs: https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json
