### ISSUE TITLE
diskio.read_bytes and diskio.write_bytes fields have float type instead of integer

### ISSUE THREAD

**Issue by Jofagi** [influxdata/telegraf#11484]
### Relevant telegraf.conf

```toml
[[inputs.diskio]]
# No additional configuration for diskio...
```

### Logs from Telegraf

```text
2022-07-10T18:03:22Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "write_bytes" on measurement "diskio" is type float, already exists as type integer dropped=7
2022-07-10T18:03:32Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "read_bytes" on measurement "diskio" is type float, already exists as type integer dropped=7
```

### System info

Telegraf 1.23.1 (git: HEAD 686717fe), Raspbian GNU/Linux 10 (buster)

### Docker

unfortunately this is not running within a docker environment but on the bare machine

### Steps to reproduce

1. enable diskio input plugin
2. configure an influxdb instance as data output
3. restart telegraf

### Expected behavior

diskio's fields should all be written as `integer` according to the documentation

### Actual behavior

`read_bytes` and `write_bytes` are sent as `float` and this results in the above errors because influxdb's `diskio` measurement was set up with `integer` field types.

### Additional info

I've got another system, also running `Raspbian GNU/Linux 10 (buster)` and `Telegraf 1.23.1 (git: HEAD 686717fe)` which works as expected.

The software was installed via `deb https://repos.influxdata.com/debian buster stable` on both systems.

The system having problems is this:
```bash
# uname -a
Linux loxberry 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```
This is a Raspberry Pi 4 hardware.

The system working fine is this:
```bash
# uname -a
Linux pihole 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```
This is a Raspberry Pi 2 hardware.

I tried to work around this by using `processors.converter` and convert the fields to `integer` fields but I couldn't make it convert both fields for some reason. Looks like a bug in `converter` but that's not within the scope of *this* issue...

**Comment by srebhan** [comment]
Are you sure you don't have any processor or other step in between? 

The `diskio` plugin uses the [gopsutil library](https://github.com/shirou/gopsutil) and just "copies" the [fields we get from there](https://github.com/shirou/gopsutil/blob/46f7642940d515ba0bc5ad60697ec1e1c1227eb7/disk/disk.go#L32) which is `uint64`. I neither can find any conversion to float in telegraf nor in the underlying library...

**Comment by Jofagi** [comment]
I figured that the interfering processor statement apparently serves no purpose and commented it out. So my problem is solved.
It would be interesting though, to hear if it could be solved without disabling the processor completely.

Since it's not a bug after all, I'm not sure whether to close the issue as "completed" or "not planned", so I'll leave this up to you :)

**Comment by powersj** [comment]
Hi,

You would need to edit the processor config itself. The `namedrop` option should allow you to remove metrics from a specific processor:

```toml
[[processors.converter]]
  namedrop = ["diskio"]

  [processors.converter.fields]
    float = [
      "Load*",
      "*_bootedTimestamp",
      "*_bytes",
      "*_errors",
      "*_packets",
      "*_quality_*",
    ]
```

Ideally, those processors would have the namepass option to accept the metrics that need to go through them so your additional metrics would not conflict.

Thanks for following up, I am going to close this, but do feel free to follow up!
