### ISSUE TITLE
rabbitmq plugin Eroor

### ISSUE THREAD

**Issue by shenghuofei** [influxdata/telegraf#11492]
when i open rabbitmq input plugin,there some errors:
[inputs.rabbitmq] Error in plugin: decoding answer from "/api/queues" failed: json: cannot unmarshal string into Go struct field Queue.consumer_utilisation of type float64
[inputs.rabbitmq] Error in plugin: getting "/api/federation-links" failed: 404 Not Found
Error in plugin: getting "/api/nodes/rabbit@xxxxxx/memory" failed: 404 Not Found

the rabbitmq version is : 3.4.2
the telegraf version is : Telegraf 1.22.4 (git: HEAD acf67065)

**Comment by powersj** [comment]
404 error means that the URL cannot be found. You need to verify that your `url` setting is correct and that you can manually open those URLs. If you have not set the URL setting it will default to `http://localhost:15672`

**Comment by shenghuofei** [comment]
> 404 error means that the URL cannot be found. You need to verify that your `url` setting is correct and that you can manually open those URLs. If you have not set the URL setting it will default to `http://localhost:15672`

URL is no problem,I can get some metrics,such as rabbitmq_exchange_messages_publish_out, rabbitmq_exchange_messages_publish_out_rate.

Jul 13 09:55:00 telegraf[18064]: 2022-07-13T01:55:00Z E! [inputs.rabbitmq] Error in plugin: decoding answer from "/api/queues" failed: json: cannot unmarshal string into Go struct field Queue.consumer_utilisation of type float64

this error seems value type error

**Comment by shenghuofei** [comment]
> utilization

so rabbitmq 3.4.2 can not use this input plugin?

**Comment by shenghuofei** [comment]
> > Jul 13 09:55:00 telegraf[18064]: 2022-07-13T01:55:00Z E! [inputs.rabbitmq] Error in plugin: decoding answer from "/api/queues" failed: json: cannot unmarshal string into Go struct field Queue.consumer_utilisation of type float64
> > this error seems value type error
> 
> It is - consumer utilization is a float64 in Telegraf and in RabbitMQ: https://github.com/rabbitmq/rabbitmq-server/blob/149a7e78cf0fa4be252a9c21c2b819b508fe0df5/deps/rabbit/docs/rabbitmqctl.8#L1381
> 
> > the rabbitmq version is : 3.4.2
> 
> I missed this at first, but 3.4.2 is from 2014 and not a generally supported version.
> 
> I do not see an issue with Telegraf based on this report.

may i ignore this metric? i add 
```
fielddrop = ["consumer_utilisation"]
```
to input plugin config,but no effect.

**Comment by powersj** [comment]
> so rabbitmq 3.4.2 can not use this input plugin?

The rabbitmq API has changed over time and 3.4.2 may be too old to work with this plugin.

> may i ignore this metric? i add

fielddrop only applies after the plugin has processed the data.

**Comment by shenghuofei** [comment]
> > so rabbitmq 3.4.2 can not use this input plugin?
> 
> The rabbitmq API has changed over time and 3.4.2 may be too old to work with this plugin.
> 
> > may i ignore this metric? i add
> 
> fielddrop only applies after the plugin has processed the data.

ok,i see. thank you very much.
