### ISSUE TITLE
Convert Counter metrics to rates generically in outputs/processors/aggregators

### ISSUE THREAD

**Issue by danielkza** [influxdata/telegraf#11507]
### Proposal:

Properly handle counter metrics so they can be sent in the correct format to different outputs.

### Current behavior:

Currently it seems not all available processors and aggregators can take specific actions based on the metric type - i.e. gauges vs counters. Some output plugins seem to directly support such cases, but it would be nice if there was a way to transform values based on their type in a generic way.

### Desired behavior:

Different aggregators/processor can support filtering/transforming based on metric types. Or ensure all output plugins can transform `counter` metrics to rates in an uniform way.

### Use case: 

My current use case is to send counter values to Cloudwatch as rates. This is necessary when sending metrics with trimmed dimensions for native aggregation. Currently the CW output doesn't seem to support it, and I can't find any other way to achieve it. I could write something with Starlark, but it doesn't expose the `type` of a `Metric` at all.

**Comment by sspaink** [comment]
I am not entirely sure I understand the feature your requesting, could you perhaps provide an example line protocol showing how you would like to transform it? Also I am not sure what you mean by counter metrics and rates, could you explain what they are? Thank you!
