### ISSUE TITLE
snmp table collection issue

### ISSUE THREAD

**Issue by ademxoy** [influxdata/telegraf#11505]
I have a strange case of snmp collection (not collection).  

Summary:
I want to collect the values from 2 different OIDs.  
When I run the oids directly under inputs.snmp, I get values back for both oids.
When I move the oids under inputs.snmp.table, I don't get any results.

I have used this method on different config files (for other devices with different oids) and I don't have any issues with this set up on any other device.  

Config Files & Test Outputs:

```toml
[[inputs.snmp]]
  agents = [ "hostIPAddress" ]
  version = 2
  community = "CommunityString"
  interval = "60s"
  timeout = "50s"
  retries = 0

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "cpu"
    inherit_tags = ["hostname"]
     
    [[inputs.snmp.table.field]]
      name = "hrProcessorLoad1"
      oid = "1.3.6.1.2.1.25.3.3.1.2.1"

    [[inputs.snmp.table.field]]
      name = "hrProcessorLoad2"
      oid = "1.3.6.1.2.1.25.3.3.1.2.2"
```

When I run above in telegraf test config, I get:

```
root@ubuntu:/etc/telegraf/telegraf.d# telegraf --test --config test.conf --debug
2022-07-14T17:30:34Z I! Starting Telegraf 1.23.2
2022-07-14T17:30:34Z I! Loaded inputs: snmp
2022-07-14T17:30:34Z I! Loaded aggregators: 
2022-07-14T17:30:34Z I! Loaded processors: 
2022-07-14T17:30:34Z W! Outputs are not used in testing mode!
2022-07-14T17:30:34Z I! Tags enabled: host=ubuntu
2022-07-14T17:30:34Z D! [agent] Initializing plugins
2022-07-14T17:30:34Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "SNMPv2-MIB::sysName.0"
2022-07-14T17:30:34Z D! [agent] Starting service inputs
2022-07-14T17:30:35Z D! [agent] Stopping service inputs
2022-07-14T17:30:35Z D! [agent] Input channel closed
2022-07-14T17:30:35Z D! [agent] Stopped Successfully
```

When I remove the table in [[inputs.snmp.table.field]], oids seems to be collecting the value (of course not registering to table but to snmp). When I run below config file:

```toml
[[inputs.snmp]]
  agents = [ "hostIPAddress" ]
  version = 2
  community = "CommunityString"
  interval = "60s"
  timeout = "50s"
  retries = 0

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "cpu"
    inherit_tags = ["hostname"]
     
    [[inputs.snmp.table.field]]
      name = "hrProcessorLoad1"
      oid = "1.3.6.1.2.1.25.3.3.1.2.1"

    [[inputs.snmp.field]]
      name = "hrProcessorLoad2"
      oid = "1.3.6.1.2.1.25.3.3.1.2.2"
```

I get this result: 

```
root@ubuntu:/etc/telegraf/telegraf.d# telegraf --test --config test.conf --debug
2022-07-14T17:32:56Z I! Starting Telegraf 1.23.2
2022-07-14T17:32:56Z I! Loaded inputs: snmp
2022-07-14T17:32:56Z I! Loaded aggregators: 
2022-07-14T17:32:56Z I! Loaded processors: 
2022-07-14T17:32:56Z W! Outputs are not used in testing mode!
2022-07-14T17:32:56Z I! Tags enabled: host=ubuntu
2022-07-14T17:32:56Z D! [agent] Initializing plugins
2022-07-14T17:32:56Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "SNMPv2-MIB::sysName.0"
2022-07-14T17:32:56Z D! [agent] Starting service inputs
> snmp,agent_host=correctHostname,host=ubuntu,hostname=correctHostname hrProcessorLoad2=1i 1657819977000000000
2022-07-14T17:32:57Z D! [agent] Stopping service inputs
2022-07-14T17:32:57Z D! [agent] Input channel closed
2022-07-14T17:32:57Z D! [agent] Stopped Successfully
```

When I run snmpget, I see the results:
```
root@ubuntu:/etc/telegraf/telegraf.d$ snmpget -v2c -c "CommunityString" hostIPAddress 1.3.6.1.2.1.25.3.3.1.2.1
iso.3.6.1.2.1.25.3.3.1.2.1 = INTEGER: 1
```
tcpdump and wireshark shows that there is a request & response for all. However, it does not get registered to the table in telegraf.  

Even though it should not matter since I am using oids: I tried snmp_translator: netsnmp & gosmi (restarting telegraf service after changing the config).  

What am I doing wrong here?

**Comment by MyaLongmire** [comment]
when I run the following command it seems like that oid is not a table.
`snmptable -v2c -c public 127.0.0.1 1.3.6.1.2.1.25.3.3.1.2.2 `
```Was that a table? HOST-RESOURCES-MIB::hrProcessorLoad.2```

**Comment by Hipska** [comment]
When collecting table entries, you should not add the index to the given OID.

Try this:
```toml
[[inputs.snmp]]
  agents = [ "hostIPAddress" ]
  version = 2
  community = "CommunityString"
  interval = "60s"
  timeout = "50s"
  retries = 0

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "cpu"
    inherit_tags = ["hostname"]
    index_as_tag = true
     
    [[inputs.snmp.table.field]]
      name = "hrProcessorLoad"
      oid = "1.3.6.1.2.1.25.3.3.1.2"
```

**Comment by ademxoy** [comment]
> when I run the following command
> 
> `snmptable -v2c -c public 127.0.0.1 1.3.6.1.2.1.25.3.3.1.2.1 `
> 
> it gives a response seeming that it is not a table but a single field
> 
> `Was that a table? HOST-RESOURCES-MIB::hrProcessorLoad.1`
> 
> When i run it with oid `1.3.6.1.2.1.25.3.3.1.2.2` I get the same response.

This oid is not a table.  I expected telegraf to create an empty measurement called "cpu", collect individual values for fields under it and add them to the "cpu" measurement along with the inherited tags.

hrProcessorTable OID is: 1.3.6.1.2.1.25.3 but it is not useful in my case.  I can't get the CPU names (management and data processor).  I would not care of management CPU is over 40% but I care if Data Processor CPU is over 10% usage.

That is why I want to collect each field separately (giving its indexes).  1.3.6.1.2.1.25.3.3.1.2.1 is the Management Processor Load, 1.3.6.1.2.1.25.3.3.1.2.2 is the Data Processor Load.

**Comment by Hipska** [comment]
In that case, you need to config them as `inputs.snmp.field` and use a processor after that to split the metric in a separate one.
