### ISSUE TITLE
add median timing calculation to statsd input plugin

### ISSUE THREAD

**Issue by amarinderca** [influxdata/telegraf#11517]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add median timing calculation to statsd input plugin as it is a useful value to have. one or two outlier datapoints can really skew the mean

### Current behavior:
no median value calculated for timings

### Desired behavior:
have median value calculated for timing

### Use case: 
median time taken for a script run

**Comment by powersj** [comment]
next steps: finish review of PR!
