### ISSUE TITLE
test: add integration test to redis-timeseries

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#11523]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add an integration test to the new redis-timeseries plugin.

### Current behavior:

No tests are run on this plugin.

### Desired behavior:

Have tests to aid in ensuring the plugin continues to work.

See https://github.com/influxdata/telegraf/pull/11054 for the original PR to include. Including an example integration test.

**Comment by srebhan** [comment]
Duplicate of #11513, but will keep this one due to better description. ;-)

**Comment by powersj** [comment]
> Duplicate of #11513, but will keep this one due to better description. ;-)

oops! Sorry!
