### ISSUE TITLE
Outputs.Datadog does not support Distribution typed metrics

### ISSUE THREAD

**Issue by skylera93** [influxdata/telegraf#11525]
The Datadog output [uses this API](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics ) which does not support the submission of Distribution typed metrics. This limitation is not mentioned in the plugin's readme, and was a surprise blocker given that work was done to enable Datadog Distributions in the Statsd input plugin. 

It looks like the output would need to submit distribution typed metrics to this API instead. 
https://docs.datadoghq.com/api/latest/metrics/#submit-distribution-points

**Comment by MyaLongmire** [comment]
Sorry to hear you are having some trouble. 
Would you be interested in submitting a pr for this fix?

**Comment by dirrao** [comment]
This is a good to have to track latency metrics distribution. Right now, this plugin doesn't support it.
