### ISSUE TITLE
Provide the ability to use fields from gnmi.tag_subscription as tag fields

### ISSUE THREAD

**Issue by jrventer** [influxdata/telegraf#11543]
## Feature Request
With the new gnmi.tag_subscription on_change subscriptions can be used to map tags to the sampled data. Typical requirement is to get the ifAlias or IP address as a tag to interface counters. With Juniper the Description (ifAlias) and IP Address come through as fields and not tags. it the gnmi.tag_subscription can include a field to tag override/conversion option that will provide flexibility.

Opening a feature request kicks off a discussion.

### Proposal:

add a config option under the gnmi.tag_subscription section to treat specific fields as tag values.
 fields_as_tags = ["interface/subinterfaces/subinterface/state/description","interface/subinterfaces/subinterface/ipv4/addresses/address/state/ip"]

### Current behavior:
Used the file output as per below for the json output to make it easier to read.

```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "json" 

[[inputs.gnmi.subscription]]
   name = "gnmi_iflcounters"
   name_override = "gnmi_ifcounters"
   origin = "openconfig"
   path = "/interfaces/interface/subinterfaces/subinterface/state/counters"
   subscription_mode = "sample"
   sample_interval = "30s"
```

Generates:
```json
{
    "fields": {
        "interface/subinterfaces/subinterface/init_time": 1658585546,
        "interface/subinterfaces/subinterface/state/counters/in_octets": 119651860,
        "interface/subinterfaces/subinterface/state/counters/in_pkts": 980822,
        "interface/subinterfaces/subinterface/state/counters/in_unicast_pkts": 980822,
        "interface/subinterfaces/subinterface/state/counters/out_octets": 10693,
        "interface/subinterfaces/subinterface/state/counters/out_pkts": 157,
        "interface/subinterfaces/subinterface/state/counters/out_unicast_pkts": 157,
        "interface/subinterfaces/subinterface/state/parent_ae_name": "ae0.11"
    },
    "name": "ifcounters",
    "tags": {
        "host": "00b7319b77c1",
        "index": "11",
        "name": "ge-0/0/1",
        "path": "/interfaces/interface/subinterfaces/subinterface",
        "source": "lab-site1-mpls-r1"
    },
    "timestamp": 1658592508
}
```

and 

```toml
[[inputs.gnmi.tag_subscription]]
  name = "desc"
  origin = "openconfig"
  path = "/interfaces"
  subscription_mode = "on_change"
  elements = ["interface","subinterface"]
```

Receives this for Description:

```json
{
    "fields": {
        "interface/subinterfaces/subinterface/state/description": "lab-site1-me-sw1_ospf test"
    },
    "name": "desc",
    "tags": {
        "host": "00b7319b77c1",
        "index": "11",
        "name": "ge-0/0/1",
        "path": "/interfaces/interface/subinterfaces/subinterface",
        "source": "lab-site1-mpls-r1"
    },
    "timestamp": 1658604460
}
```

As you can see the description is a field not a tag.
 For IP address change the event looks like this:

```json
 {
    "fields": {
        "interface/subinterfaces/subinterface/ipv4/addresses/address/state/ip": "100.100.1.108",
        "interface/subinterfaces/subinterface/ipv4/addresses/address/state/origin": "STATIC",
        "interface/subinterfaces/subinterface/ipv4/addresses/address/state/prefix_length": 31
    },
    "name": "ifcounters",
    "tags": {
        "host": "00b7319b77c1",
        "index": "11",
        "ip": "100.100.1.108",
        "name": "ge-0/0/1",
        "path": "/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address",
        "source": "lab-site1-mpls-r1"
    },
    "timestamp": 1658592386
}
```

### Desired behavior:
Output with the Description and IP fields as tags on the sampled subscription where the keys match (name and index)

```json
{
    "fields": {
        "interface/subinterfaces/subinterface/init_time": 1658585546,
        "interface/subinterfaces/subinterface/state/counters/in_octets": 119651860,
        "interface/subinterfaces/subinterface/state/counters/in_pkts": 980822,
        "interface/subinterfaces/subinterface/state/counters/in_unicast_pkts": 980822,
        "interface/subinterfaces/subinterface/state/counters/out_octets": 10693,
        "interface/subinterfaces/subinterface/state/counters/out_pkts": 157,
        "interface/subinterfaces/subinterface/state/counters/out_unicast_pkts": 157,
        "interface/subinterfaces/subinterface/state/parent_ae_name": "ae0.11"
    },
    "name": "ifcounters",
    "tags": {
        "host": "00b7319b77c1",
        "index": "11",
        "description": "lab-site1-me-sw1_ospf test",
        "ip": "100.100.1.108",
        "name": "ge-0/0/1",
        "path": "/interfaces/interface/subinterfaces/subinterface",
        "source": "lab-site1-mpls-r1"
    },
    "timestamp": 1658592508
}
```

### Use case:

- Having the interface IP as a tag value allows easier retrieval of interface stats from systems where they only have the IP address on the interface and require to lookup the interface statistics
- The idAlias Description is typically used with structured information allowing you to filter and identify specific groupings based on specific values in this field.

**Comment by powersj** [comment]
Hi,

> With Juniper the Description (ifAlias) and IP Address come through as fields and not tags.

Keep in mind that adding tags can greatly increase the cardinality of the database with tags that can have many different unique values.

My first thought is that Telegraf already provides a way for users to convert a field to a tag if they want to via the [converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter). Here is a brief example:

```
[[processors.converter]]
  [processors.converter.fields]
    tag = ["field_name"]
```

You can also use the `namepass` [selector](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#selectors) to choose which metrics get used on a specific processor.

**Comment by jrventer** [comment]
Thanks yeah agree on the cardinality for storing the bare ifAlias(description) as a tag. The idea is more to extract some fields from the structured description and store them as tags.

I will have a look at the processors.converter as a option. I ended up using the starlark processor to get a solution saving it in the state variable and then adding it to the normal metrics. 
[[processors.starlark]]
order = 1
namepass = ["gnmi_if_info","gnmi_ifcounters","gnmi_iflcounters"]
source = '''
state = {}
def apply(metric):
  # On-Change Info
  if metric.name == "gnmi_if_info":
    if metric.tags["path"] == "/interfaces/interface/subinterfaces/subinterface":
      if "interface/subinterfaces/subinterface/state/description" in metric.fields.keys():
        ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] +  "." + metric.tags["index"] + "ifAlias"
        state[ifNameDeviceKey] = metric.fields.get("interface/subinterfaces/subinterface/state/description")
      if "interface/subinterfaces/subinterface/state/parent_ae_name" in metric.fields.keys():
        ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] + metric.tags["index"] + "parent_ae_name"
        state[ifNameDeviceKey] = metric.fields.get("interface/subinterfaces/subinterface/state/parent_ae_name")
    elif metric.tags["path"] == "/interfaces/interface":
      if "interface/state/description" in metric.fields.keys():
        ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] + "ifAlias"
        state[ifNameDeviceKey] = metric.fields.get("interface/state/description")
    # Drop measurement and do not publish it
    metric = None
  elif metric.name == "gnmi_iflcounters":
    metric.tags["ifName"] = metric.tags["name"] + "." + metric.tags["index"]
    ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] + metric.tags["index"] + "parent_ae_name"
    for k,v in state.items():
        if ifNameDeviceKey == k:
            metric.tags["parent_ae_name"] = v
            break
        else:
            continue
    if metric.tags.get("parent_ae_name","") != "":
      ifNameDeviceKey = metric.tags["source"] + metric.tags.get("parent_ae_name") + "ifAlias"
    else:
      ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] + "." + metric.tags["index"] + "ifAlias"
    for k,v in state.items():
        if ifNameDeviceKey == k:
            metric.fields["ifAlias"] = v
            if v.find('\u003e') > 0:
              ifAlias = v.split()
              if len(ifAlias) == 4:
                metric.tags["svcName"] = ifAlias[0]
                metric.tags["svcTags"] = ifAlias[1]
                metric.tags["svcInstance"] = ifAlias[3].removesuffix(")")
            break
        else:
            continue
  elif metric.name == "gnmi_ifcounters":
    ifNameDeviceKey = metric.tags["source"] + metric.tags["name"] + "ifAlias"
    for k,v in state.items():
        if ifNameDeviceKey == k:
            metric.fields["ifAlias"] = v
            break
        else:
            continue
  return metric
'''

For the question around the single field - the device only sends all at subscription start and thereafter only on change and the values that changed. The example was when I tested by changing the description so only that field changed.

Below example of a initial event coming through with all the fields.
{
    "fields": {
        "interface/subinterfaces/subinterface/ipv4/state/enabled": false,
        "interface/subinterfaces/subinterface/ipv4/unnumbered/interface_ref/state/interface": "",
        "interface/subinterfaces/subinterface/ipv4/unnumbered/interface_ref/state/subinterface": 0,
        "interface/subinterfaces/subinterface/ipv4/unnumbered/state/enabled": false,
        "interface/subinterfaces/subinterface/ipv6/state/enabled": false,
        "interface/subinterfaces/subinterface/ipv6/unnumbered/interface_ref/state/interface": "",
        "interface/subinterfaces/subinterface/ipv6/unnumbered/interface_ref/state/subinterface": 0,
        "interface/subinterfaces/subinterface/ipv6/unnumbered/state/enabled": false,
        "interface/subinterfaces/subinterface/state/admin_status": "UP",
        "interface/subinterfaces/subinterface/state/description": "lab-site1-pe-sw1_101_11",
        "interface/subinterfaces/subinterface/state/enabled": true,
        "interface/subinterfaces/subinterface/state/ifindex": 556,
        "interface/subinterfaces/subinterface/state/index": 11,
        "interface/subinterfaces/subinterface/state/last_change": 1658586135023947000,
        "interface/subinterfaces/subinterface/state/logical": true,
        "interface/subinterfaces/subinterface/state/name": "ae0.11",
        "interface/subinterfaces/subinterface/state/oper_status": "UP"
    },
    "name": "ifcounters",
    "tags": {
        "host": "00b7319b77c1",
        "index": "11",
        "name": "ae0",
        "path": "/interfaces/interface/subinterfaces/subinterface",
        "source": "lab-site1-mpls-r2"
    },
    "timestamp": 1658592026
}

**Comment by powersj** [comment]
> I ended up using the starlark processor

I like this for your use case.

> The example was when I tested by changing the description so only that field changed.

Keep in mind for an output using Influx Line Protocol, that if the only field is the description and you immediately turn that into a tag, then the metric is not valid as there are no fields present. At least one field is required for a valid metric in those formats.
