### ISSUE TITLE
Define timestamp precision on exec plugins

### ISSUE THREAD

**Issue by 3IMOH** [influxdata/telegraf#1154]
Hello-
Is it possible to define the timestamp precision when configuring an exec (or other) input plugin (similar to the HTTP listener? I have a case where my input has ms unix timestamps. I can convert these before telegraf but it would be nice to be able to just configure that in the plugin.

**Comment by steverweber** [comment]
also looking for something like this... would like to set a default precision in  `[[outputs.influxdb]]` and perhaps allow overrides per plugin.

**Comment by steverweber** [comment]
@3IMOH note in the next release of influxdb 0.13 might have https://github.com/influxdata/influxdb/issues/6037

this might help you out.

**Comment by steverweber** [comment]
seems the milestone changed from 0.13 to long term... perhaps we'll have to wait for 1.0

**Comment by sparrc** [comment]
correct, this will need to wait until https://github.com/influxdata/influxdb/issues/6037, closing because it's an issue with influxdb line protocol, not telegraf.

**Comment by sparrc** [comment]
FWIW, all you need to do is add `000000` to the end of your ms timestamps, so there is at least a simple workaround.
