### ISSUE TITLE
User/System Metadata labels filters in stackdriver

### ISSUE THREAD

**Issue by lpankaz** [influxdata/telegraf#11547]
## Feature Request

I would like to be able to filter metrics from google with information about user/system metadata labels. 

### Current behavior:
I cannot download data regarding metadata labels using stackdriver plugin. Nor can I filter by them, nor have these data, to filter later. 

### Desired behavior:
I would like either to be able to filter downloaded metrics based on metadata labels or do not lose these information. 

### Use case: 
In Cloud Monitoring API I can see some examples with 
metadata.system_labels.[KEY]
metadata.user_labels.[KEYSTRING]
whereas I am unable to use it together with Stackdriver plugin. I also lose information of them after putting data to influx db. 
Do you think it would be possible to add this feature?

**Comment by powersj** [comment]
Hi,

Have you seen the stackdriver README? At the [end of the example configuration](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/stackdriver#configuration), there is a section on filtering based on labels, which sounds like what you are interested in doing? Is your request different than what already exists?

```toml
  ## Filters can be added to reduce the number of time series matched.  All
  ## functions are supported: starts_with, ends_with, has_substring, and
  ## one_of.  Only the '=' operator is supported.
  ##
  ## The logical operators when combining filters are defined statically using
  ## the following values:
  ##   filter ::= <resource_labels> {AND <metric_labels>}
  ##   resource_labels ::= <resource_labels> {OR <resource_label>}
  ##   metric_labels ::= <metric_labels> {OR <metric_label>}
  ##
  ## For more details, see https://cloud.google.com/monitoring/api/v3/filters
  #
  ## Resource labels refine the time series selection with the following expression:
  ##   resource.labels.<key> = <value>
  # [[inputs.stackdriver.filter.resource_labels]]
  #   key = "instance_name"
  #   value = 'starts_with("localhost")'
  #
  ## Metric labels refine the time series selection with the following expression:
  ##   metric.labels.<key> = <value>
  #  [[inputs.stackdriver.filter.metric_labels]]
  #    key = "device_name"
  #    value = 'one_of("sda", "sdb")'
```

Thanks!

**Comment by lpankaz** [comment]
Hi, 
of course I've read README. And what is more - I'm heavily using these filters - resource.labels and metric.labels. Unfortunatelly mentioned metadata.user_labels and metadata.system_labels are something different. Could you please look into that more carefully? Even in my metrics explorer they are shown as different type of filter. 
https://cloud.google.com/monitoring/api/v3/filters#group-filter
 
![filters1](https://user-images.githubusercontent.com/3836905/181201715-e71efb1d-7f67-4dc2-82ce-5e962fec6b45.jpg)
![filter2](https://user-images.githubusercontent.com/3836905/181201720-8a06a65f-fe53-45ef-84a1-adfbf9f82891.jpg)
![filter3](https://user-images.githubusercontent.com/3836905/181201723-2bec8f40-94c2-4b36-8161-63a2c05f9972.jpg)

If there is a possibility right now to use metadata filters, could you please show me an example? As one mentioned in README is not enough.

**Comment by Mariushrek** [comment]
Hello, any news? I am also looking for this feature ;)

Thanks,
Mariusz
