### ISSUE TITLE
nvidia_smi: Field for number of GPUs

### ISSUE THREAD

**Issue by staeglis** [influxdata/telegraf#11546]
## Feature Request

The nvidia_smi input plugin should provide a field for the number of GPUs

### Use case: 

This would allow to check easier that all GPUs are recognized

**Comment by powersj** [comment]
Hi,

The data used by `nvidia_smi` is found directly from the `nvidia-smi` command itself. One of the reported tags is the `index` tag, which is a unique counter value for each GPU. A user could craft a query to group by the index and see how many results they get, which would be the number of GPUs.
