### ISSUE TITLE
No metrics for sqlserver_database_io measurement when I use tagpass

### ISSUE THREAD

**Issue by sairnuth2** [influxdata/telegraf#11554]
Hi,

We have more than 150 tiny small databases on each SQL instance. We would like to have few required metrics ( counters) in the grafana chart as huge amount loading might be causing performance issues. So we tried to make use of fieldpass (Test Case 1) to get the sqlserver_performance metrics, but no luck. So we added counter in tagpass, able to get the required data (Test Case 2) . But now, we are not seeing metrics (Reads/sec or Write Latency) for "sqlserver_database_io" measurements. 

**_**Test case 1:**_**

[agent]
  interval = "60s"
[[inputs.sqlserver]]
  servers = [
    "Server=localhost;Port=xxxx;Integrated Security=SSPI;app name=telegraf;log=1;",
   ]
  database_type = "SQLServer"
  query_version = 2
  ##exclude_query = [ 'Schedulers' , 'SqlRequests']
  
[[processors.pivot]]
  namepass = [
    "sqlserver_performance"
  ]
  tag_key = "counter"
  value_key = "value"
  fieldpass = ["Active*", "Data File(s) Size (KB)", "Log File(s) Size (KB)", "Log File(s) Used Size (KB)", "Percent Log Used"]

[[aggregators.merge]]
  namepass = [
    "sqlserver_performance"
 ]
  drop_original = true

[[inputs.exec]]
  commands = ['powershell "C:\temp\thread.ps1"','powershell "C:\temp\dbsizes.ps1"'] 
  timeout = "15s"
  data_format = "influx"

**_**Test case 2:**_** 

[agent]
  interval = "60s"
[[inputs.sqlserver]]
  servers = [
    "Server=localhost;Port=xxxx;Integrated Security=SSPI;app name=telegraf;log=1;",
   ]
  database_type = "SQLServer"
  query_version = 2
  ##exclude_query = [ 'Schedulers' , 'SqlRequests']
  
  [inputs.sqlserver.tagpass]
    counter = ["Active*", "Data File(s) Size (KB)", "Log File(s) Size (KB)", "Log File(s) Used Size (KB)", "Percent Log Used"]

[[processors.pivot]]
  namepass = [
    "sqlserver_performance"
  ]
  tag_key = "counter"
  value_key = "value"
  ##fieldpass = ["Data File(s) Size (KB)"]
  ##fielddrop = ["Backup/Restore Throughput/sec", "Log Bytes Flushed/sec", "Log Flush Wait Time", "Log Flushes/sec", "Transactions/sec", "Write Transactions/sec"]
 
[[aggregators.merge]]
  namepass = [
    "sqlserver_performance"
 ]
  drop_original = true

[[inputs.exec]]
  commands = ['powershell "C:\temp\thread.ps1"','powershell "C:\temp\dbsizes.ps1"'] 
  timeout = "15s"
  data_format = "influx"

======================================================================
Any suggestions here ? Anything missing?

**Comment by srebhan** [comment]
Can you maybe provide a metric _without_ any filtering? You might want to use `telegraf --test` to avoid sending it to your database...

My guess is that the "Reads/sec" or "Write Latency" for "sqlserver_database_io" metrics do not have a `counter` tag and are thus filtered...

**Comment by sairnuth2** [comment]
I feel the same since there is no counter tag we may not be able to get the
data for other measurements. I feel some issues with the fieldpass is
working as expected, but fielddrop is working without any issues. Let me
check if I can send the output to text file instead of database using
--test option. Thank you for your review and response.
