### ISSUE TITLE
[FOSSA] Issue with licensecheck - POLICY_CONFLICT

### ISSUE THREAD

**Issue by lindenksv** [influxdata/telegraf#11562]

**Comment by srebhan** [comment]
Can you please elaborate a bit more @lindenksv!?

**Comment by lindenksv** [comment]
Sorry this was an error. Please ignore.
<http://katedowninglaw.com/>
         831-454-8334

**Comment by powersj** [comment]
> Sorry this was an error. Please ignore.

Thanks! I'm going to close this then for now.
