### ISSUE TITLE
snmp - output shows host-tag of the local host instead of remote device

### ISSUE THREAD

**Issue by grisu-cl** [influxdata/telegraf#1156]
Hi,
i think commit 9aec58c6b82063cb277c4e1c342f951c730a0da5 breaks the snmp-plugin

```
[agent]
  omit_hostname = false
  [[inputs.snmp.host]]
    address = "10.10.10.1:161"
    get_oids = ["sysUpTime"] 
```
expected output with Telegraf - Version 0.12.1
`sysUpTime,host=10.10.10.1,instance=0 sysUpTime=4331487i 1462473096063976567`
with 10.10.10.1 as the remote device

with Version 0.12.1-30-g9aec58c
`sysUpTime,host=grisu,instance=0 sysUpTime=4340798i 1462473189173558190`
with 'grisu' as the local host

it works with 'omit_hostname = true' ... but that has other impacts

**Comment by sparrc** [comment]
thanks for the report, I will need to change this tag to `snmp_host`, as this is how it should have been from the beginning. I will try to get this into the 0.13 release.

**Comment by ljagiello** [comment]
@sparrc with telegraf-0.13.0-rc3-1 it's still broken.

**Comment by sparrc** [comment]
@ljagiello is there an snmp_host tag? I'm not sure if rc3 has this change, but it will be in 0.13

**Comment by ljagiello** [comment]
There is no tag `snmp_host` only `host`.
