### ISSUE TITLE
Mixed line endings when running telegraf config

### ISSUE THREAD

**Issue by audunmg** [influxdata/telegraf#11571]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
```

### Logs from Telegraf

```text
--
```

### System info

docker image telegraf:1.2.3-alpine

### Steps to reproduce

1. docker run --rm docker.io/library/telegraf:alpine telegraf config > config.conf
2.  config.conf line 24-113 has DOS-style line endings, the rest of the file is UNIX-style line endings
...

### Expected behavior

Consistent line endings.

### Actual behavior

Mixed line endings

### Additional info

Minor issue, but reporting anyways since it's probably easy to fix.

**Comment by srebhan** [comment]
@audunmg can you please attach the generated configuration to see which plugin this comes from? Furthermore, which Telegraf version are you using?

**Comment by sspaink** [comment]
This might have been resolved in: https://github.com/influxdata/telegraf/pull/11501
I don't believe this fix has been released yet.

**Comment by powersj** [comment]
>  I don't believe this fix has been released yet.

Agreed, it looks like we did not grab it in the bug fix release as it is not in the release-1.23 branch. I think we should close this since the fix is in master and the next minor release will pick this up.

**Comment by audunmg** [comment]
Sorry for the late reply. 

Version is Telegraf 1.23.3 (git: HEAD 73121bd1) from docker image docker.io/library/telegraf:alpine (75df61c63ea5)

I'll just close it and reopen if it's still there in the next bugfix release. 

The fix would be in 1.23.4 right?

I'll leave this here for me later, maybe it'll be useful for someone else. This is how I got the line numbers:

    docker run --rm docker.io/library/telegraf:alpine telegraf config | cat -n | grep -e '\x0d'
