### ISSUE TITLE
inputs.vsphere - Add VMs memory configuration as a tag

### ISSUE THREAD

**Issue by 6monlambert** [influxdata/telegraf#11588]
### Proposal:

I need to add the configured memory size of virtual machines in the vSphere input plugin. I worked on the code and was able to compile it. It works with the desired behaviour.

### Current behavior:

vSphere input plugin does not allow us to retrieve the configured memory size of a virtual machine. The only metric available is the **mem.granted.average** which is not always equal to the actual configuration of the machine. 

See [this VMWare website](https://www.vmwareopsguide.com/metrics/chapter-3-memory-metrics/2.3.4-vm/) or [this paper](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/techpaper/perf-vsphere-memory_management.pdf) to understand why.

### Desired behavior:

The vSphere plugin should be able to retrieve the actual configuration of the VM. The value being a configuration metric, and not a performance metric, it should be delivered as a tag. 

For example : 

```
vsphere_vm_virtualDisk,esxhostname=DC0_H0,guest=other,host=host.example.com,moid=vm-35,os=Mac,source=DC0_H0_VM0,vcenter=localhost:8989,vmname=DC0_H0_VM0,memorySizeMB=2048 write_average=144i,read_average=4i 1535660299000000000
vsphere_vm_net,esxhostname=DC0_H0,guest=other,host=host.example.com,moid=vm-38,os=Mac,source=DC0_H0_VM1,vcenter=localhost:8989,vmname=DC0_H0_VM1,memorySizeMB=8192 bytesRx_average=242i,bytesTx_average=308i 1535660299000000000
```
### Use case: 

- Be able to show the VM configuration in dashboards. 
- Make recommendations on the configuration of the VM (either add or remove RAM), by comparing it with the RAM utilization.

**Comment by reimda** [comment]
There is some discussion going on in the linked PR about implementation and whether this should be a tag or field. Thanks for your work on this!

**Comment by kilowatto** [comment]
Hello,

There is any update for this request,
will be very helpfull

**Comment by tguenneguez** [comment]
Sorry for reply on a close issue, but it's strange to have a field with capital letter and unit ?
memorySizeMB should be memory_size (in byte)

It's not possible to disable this field.
If you configure only :
vm_metric_include = [
    "cpu.usage.average",
  ]
You always have the memorySizeMB data.
