### ISSUE TITLE
Unable to parse data within InfluxDB

### ISSUE THREAD

**Issue by defarr18** [influxdata/telegraf#11611]
I am using InfluxDB v2.3 and within Telegraf section I have created a configuration and selected 'System'. After this config was running and exposed all 'System' metrics I can see that within the metrics I am unable to see the data I have stored in the DB. 

In the the Telegraf config, I used - https://github.com/influxdata/telegraf/blob/master/plugins/outputs/prometheus_client/README.md in order to expose the metrics, however, as mentioned above I cannot view the data in the database as part of my metrics. 

Am I doing something wrong or need to do something differently?

**Comment by defarr18** [comment]
The scope of this is to send data I have in the measurement to be exposed on Prometheus in order to set alerts when certain threshold are exceeded.

**Comment by powersj** [comment]
Closing as following up on the [community forum thread](https://community.influxdata.com/t/unable-to-parse-data-within-influxdb/25993/2).
