### ISSUE TITLE
Statsd Input and InfluxDB Output do not support tagexclude

### ISSUE THREAD

**Issue by WilHall** [influxdata/telegraf#1162]
I am using a tag value to filter statsd input to various influxdb outputs. I want to send Telegraf this tag so that I can use `outputs.influxdb.tagpass` to filter on the outputs, but I would also like to use `tagexclude` so that this tag is not sent to InfluxDB, since I don't need to store the value afterwards.

If I try to use `tagexclude` in the Statsd input:
```
2016/05/06 14:35:53 Error parsing telegraf.conf, line 87: field corresponding to `tagexclude' is not defined in `*statsd.Statsd'
```

If I try to use it in the Influxdb output:
```
2016/05/06 14:42:21 Error parsing telegraf.conf, line 62: field corresponding to `tagexclude' is not defined in `*influxdb.InfluxDB'
```

It appears that this option is not supported in either plugin. The documentation isn't quite clear on this, as it seems like a feature that would be implemented generically for inputs and outputs.

**Comment by sparrc** [comment]
sorry, but this is not available until 0.13, 
see the [changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md)
