### ISSUE TITLE
telegraf AMQP - Proxy with Auth

### ISSUE THREAD

**Issue by nathleeuk** [influxdata/telegraf#11626]
### Use Case

At the moment multiple telegraf outputs supports the use of proxys.
I'd like to send data from a server to rabbitmq over the internet using AMQP, but using a proxy on the telegraf agent.

### Expected behavior

no option to add http_proxy with AMQP config

### Actual behavior

no option to add http_proxy with AMQP config

**Comment by reimda** [comment]
It looks like this wouldn't be too difficult to implement. Telegraf provides a dial function to the amqp library here https://github.com/influxdata/telegraf/blob/b80d34a4224177f0d5ee33818daa3f1139c7d1b7/plugins/outputs/amqp/client.go#L52 We could write a different dial function that uses a proxy to connect and use that instead.

@nathleeuk Are you able to put together a PR to make this change? Thanks!

**Comment by nathleeuk** [comment]
Hi @reimda - i'm not in the development world so i'm fairly new to github, i'm not 100% sure what putting together a PR is!

Do you have any docs or guides?

Cheers in advance

**Comment by reimda** [comment]
@nathleeuk PR is short for pull request, a way to share changes to code. It looks like @srebhan went ahead and made the change to the AMQP plugin to support proxies for you.

Would you be able to test the new support and let us know if it works for you? It's not in a telegraf release yet, but it is available in the nightly builds: https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md

In those builds the AMQP plugin will now accept these settings:

```toml
  ## Optional Proxy Configuration
  # use_proxy = false
  # proxy_url = "localhost:8888"
```

Thanks!
