### ISSUE TITLE
mongodb stats error (CommandNotFound) no such command: 'shardConnPoolStats'    

### ISSUE THREAD

**Issue by infa-utpanda** [influxdata/telegraf#11633]
### Relevant telegraf.conf

```toml
[global_tags]
  pod_id = "ci3"
  namespace = "ci3"
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
[[inputs.procstat]]
  exe = "telegraf"
[[inputs.exec]]
  commands = [
    "/opt/scripts/users.sh",
  ]
  timeout = "10s"
  interval = "1m"
  data_format = "influx"
  [inputs.exec.tags]
    alert_group = "mongodb"
[[inputs.exec]]
  commands = [
    "/opt/scripts/metrics.sh"
  ]
  timeout = "15s"
  interval = "1m"
  data_format = "influx"
  [inputs.exec.tags]
    applicationrole = "mongodb"
    alert_group = "mongodb"
[[inputs.mongodb]]
  tagexclude = ["type", "host", "member_status"]
  servers = ["${MONGODB_URL}"]
  gather_perdb_stats = true
  [inputs.mongodb.tags]
    applicationrole = "mongodb"
    alert_group = "mongodb"
```

### Logs from Telegraf

```text
2022-08-08T10:27:10Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:20Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:30Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│ 2022-08-08T10:27:40Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:50Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│2022-08-08T10:28:00Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'
```

### System info

Telegraf 1.23.3 , Alpine Linux 3.15.5 , mongodb 6.0.0

### Steps to reproduce

1. Install MongoDB 6.0
2. Configure and start telegraf

### Expected behavior

Gathering stats.

### Actual behavior

 2022-08-08T10:27:10Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:20Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:30Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│ 2022-08-08T10:27:40Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│  2022-08-08T10:27:50Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'                                                                    │
│2022-08-08T10:28:00Z E! [inputs.mongodb] unable to gather shard connection pool stats: (CommandNotFound) no such command: 'shardConnPoolStats'

**Comment by infa-utpanda** [comment]
@powersj  Generally we do build from docker https://hub.docker.com/_/telegraf images and deployed to kubernetes cluster. Is it possible to get any docker tag reference ?

**Comment by powersj** [comment]
@infa-utpanda I have merged the PR and it will be available in our nightly images that get built tonight (available tomorrow).

See the [nightlies](https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md) docs for the nightly docker images.

**Comment by infa-utpanda** [comment]
@powersj When it will go into release tag  ? like 1.23.3 ?

**Comment by powersj** [comment]
The next bug fix is planned for next week.
