### ISSUE TITLE
SNMP Version 1 Support Broken

### ISSUE THREAD

**Issue by dandickson** [influxdata/telegraf#1163]
I have an old device that only supports snmp version 1, in my configuration I have several devices that I am pulling metrics from with version 2 however my version 1 device is not responding, I have tried the current release and nightly builds, command line snmpget works just fine.

**Comment by sparrc** [comment]
this is now available in 1.0 RC 1 with the new SNMP plugin, please see here to download the latest version: https://github.com/influxdata/telegraf#linux-deb-and-rpm-packages, and [the changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md) for details on the new SNMP plugin.
