### ISSUE TITLE
Parse error using http_listener_v2 to consume Promtail Protobuf stream

### ISSUE THREAD

**Issue by jammiemil** [influxdata/telegraf#11661]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
  ## Address and port to host HTTP listener on
  service_address = ":8080"

  ## Paths to listen to.
  paths = ["/loki/api/v1/push"]

  ## Save path as http_listener_v2_path tag if set to true
  # path_tag = false

  ## HTTP methods to accept.
  methods = ["POST"]
  #data_format = "value"
  xpath_print_document = true
  data_format = "xpath_protobuf"
  xpath_protobuf_file = "logproto.proto"
  xpath_protobuf_type = "logproto.PushRequest"
```

### Logs from Telegraf

```text
2022-08-11T13:08:37Z I! Starting Telegraf 1.23.3
2022-08-11T13:08:37Z I! Loaded inputs: http_listener_v2
2022-08-11T13:08:37Z I! Loaded aggregators:
2022-08-11T13:08:37Z I! Loaded processors:
2022-08-11T13:08:37Z W! Outputs are not used in testing mode!
2022-08-11T13:08:37Z I! Tags enabled: host=DESKTOP-OT4Q7TE
2022-08-11T13:08:37Z D! [agent] Initializing plugins
2022-08-11T13:08:37Z D! [agent] Starting service inputs
2022-08-11T13:08:37Z I! [inputs.http_listener_v2] Listening on [::]:8080
2022-08-11T13:08:45Z D! [inputs.http_listener_v2] Parse error: proto: cannot parse invalid wire-format data
2022-08-11T13:12:48Z D! [agent] Stopping service inputs
2022-08-11T13:12:48Z D! [agent] Input channel closed
2022-08-11T13:12:48Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.23.3, Windows 11, Promtail 2.6.1

### Steps to reproduce

1. Prepare proto Files and set up promtail/telegraf configs
![image](https://user-images.githubusercontent.com/54275278/184162018-1928991c-fe9e-47c4-981c-67bae8d528ae.png)

2.  run promtail and telegraf
```
promtail --config.file promtail.yaml
telegraf --test-wait 300 --config telegraf.conf --debug
```
3. Save extra line to log.log and watch telegraf console for response

### Expected behavior

Expecting the payload to get unpacked and printed to console so i can work out the next parts of the configuration (Identifying Metrics/tags/TS) to push logs upstream

### Actual behavior

Parse error: proto: cannot parse invalid wire-format data

### Additional info

The goal here is to use chained telegraf instances to produce a metrics/logs pipeline with the minimum number of open channels. I can already write my logs to Loki and my metrics to Influxdb upstream but unless i can consume Promtail payload to forward on im going to have to run two separate pipelines.

**Comment by reimda** [comment]
Hi Jamie, I think the "cannot parse invalid wire-format data" error comes when telegraf's xpath_protobuf parser doesn't recognize the input as valid protobuf format data. That might be because the input isn't that format, or maybe because the xpath_protobuf_ settings aren't correct. Could you first check that the input data is proto format and of the type "logproto.PushRequest"? It might be useful to do a packet capture to check.

@srebhan Do you have any other ideas to find why the "cannot parse invalid wire-format data" error is happening?

**Comment by jammiemil** [comment]
Sure, As it happens i did do a pcap but forgot to attach it to the issue >.<

HTTP Stream looks like this:

```
Request:
POST /loki/api/v1/push HTTP/1.1
Host: localhost:8080
User-Agent: promtail/2.6.1
Content-Length: 133
Content-Type: application/x-protobuf

....
.
W{filename="C:\\Users\\jammi\\OneDrive\\Documents\\Promtail to Telegraf Tests\\log.log"}.$
...............This is a Log Line!


Response:
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Thu, 11 Aug 2022 20:53:28 GMT
Content-Length: 29

{"error":"http: bad request"}
```

The payload itself is being sent by promtail, the same payload is consumed quiet happily by Loki so its 'Correct' In the sense that Promtail and Loki are configured to match.

The API im trying to mimic is detailed [here](https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki), Using the protobuf in the link rather than the Json approach below (unfortunately Promtail is hardcoded to use the protobuf, i would be much more comfortable writing a config for the json....)

**Comment by jammiemil** [comment]
For comparison, Heres the equivelent capture if i repoint the same setup to an active loki server:

```
Request:
POST /loki/api/v1/push HTTP/1.1
Host: 192.168.1.1:3100
User-Agent: promtail/2.6.1
Content-Length: 132
Content-Type: application/x-protobuf

....
~
W{filename="C:\\Users\\jammi\\OneDrive\\Documents\\Promtail to Telegraf Tests\\log.log"}.#
...........e..This is a Log Line!

Response:
HTTP/1.1 204 No Content
Date: Thu, 11 Aug 2022 21:23:13 GMT
```

**Comment by jammiemil** [comment]
Ok safe to say I'm very annoyed with myself :)

With a fresh head I started work replicating the issue using a python implementation (Im better with python than go) and started running in to issues with the proto definition files not being found.

Turns out that's because I had set up my folder structure incorrectly 😄 

![image](https://user-images.githubusercontent.com/54275278/184323005-62e32e45-d41e-43cf-aeb9-b232e0ab1ff6.png)

In the above image I have the folder path :

"\github.com\gogo\protobuf\gogoproto\gogo.proto"

When it should actually be

"\github\com\gogo\protobuf\gogoproto\gogo.proto"

Its a subtle change, but unsurprisingly very important!

Now that I've corrected the folder structure i get the following output in telegraf, so i can move on!

```
2022-08-12T09:06:32Z I! Starting Telegraf 1.23.3
2022-08-12T09:06:32Z I! Loaded inputs: http_listener_v2
2022-08-12T09:06:32Z I! Loaded aggregators:
2022-08-12T09:06:32Z I! Loaded processors:
2022-08-12T09:06:32Z W! Outputs are not used in testing mode!
2022-08-12T09:06:32Z I! Tags enabled: host=DESKTOP-OT4Q7TE
2022-08-12T09:06:32Z D! [agent] Initializing plugins
2022-08-12T09:06:32Z D! [agent] Starting service inputs
2022-08-12T09:06:32Z I! [inputs.http_listener_v2] Listening on [::]:8080
2022-08-12T09:07:20Z D! [parsers.xpath_protobuf::http_listener_v2] XML document equivalent: "<?xml version=\"1.0\"?><streams><entries><timestamp><nanos>113627600</nanos><seconds>1660295239</seconds></timestamp><line>This is a log Line!\r</line></entries><labels>{filename=\"C:\\\\Users\\\\jammi\\\\OneDrive\\\\Documents\\\\Promtail to Telegraf Tests\\\\log.log\"}</labels></streams>"
2022-08-12T09:07:20Z D! [parsers.xpath_protobuf::http_listener_v2] Number of configs: 0
```

Thanks for taking a look at this for me, Safe to say ive learnt a bunch of things about protobuf as part of this journey 😮‍💨

**Comment by jammiemil** [comment]
Ok i may have gotten a little ahead of myself....

So the folder path issue DID solve my ability to recreate  the experience in Python, but it did NOT affect telegraf, as telegraf needs the previous folder structure (Python treats the '.' in the path as a folder seperator hence the alternative path needed)

So im now really confused as it worked ONCE under telegraf and then stopped working again and im back to square one...

**Comment by srebhan** [comment]
@jammiemil is it possible that different _types_ of messages are sent over the same line? I can try to add some debugging info to see where it fails to be able to reproduce the issue if you want me to!?

**Comment by srebhan** [comment]
After some debugging on Slack, the issue seems to be that `promtail` is sending the data via gRPC. According to the [documentation](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md), gRPC adds a _"Length-Prefixed-Message"_ header containing 5 byte. Tests dropping the first 5 byte are ongoing...

**Comment by jammiemil** [comment]
After some to-ing and fro-ing i came to the conclusion (perhaps naively) that the best thing to do here would be to add a parser that could be used with http_listener_v2 specifically for Loki. The fruits of my labour can be found here:

https://github.com/jammiemil/telegraf/tree/master/plugins/parsers/loki

I Need to update Documentation and tests still but there are some sections of code im not happy with so my intent was to submit a PR to get some reviewer input, However im failing at the first hurdle as when i try to run the checks:

make check
make check-deps
make test
make docs

I get told i need to import the package ive added, Fair enough:

```
plugins\parsers\loki\parser.go:12:2: no required module provides package github.com/grafana/loki/pkg/logproto; to add it:
        go get github.com/grafana/loki/pkg/logproto
```

But after running go get to add my additional package i get a bunch of errors for packages i had no intention of modifying, Am i missing a trick somewhere:

```
..\..\..\..\go\pkg\mod\k8s.io\client-go@v12.0.0+incompatible\discovery\discovery_client.go:29:2: missing go.sum entry for module providing package github.com/googleapis/gnostic/OpenAPIv2 (imported by k8s.io/client-go/discovery); to add:
        go get k8s.io/client-go/discovery@v12.0.0+incompatible
..\..\..\..\go\pkg\mod\k8s.io\client-go@v12.0.0+incompatible\kubernetes\scheme\register.go:26:2: no required module provides package k8s.io/api/auditregistration/v1alpha1; to add it:
        go get k8s.io/api/auditregistration/v1alpha1
..\..\..\..\go\pkg\mod\k8s.io\client-go@v12.0.0+incompatible\kubernetes\scheme\register.go:36:2: no required module provides package k8s.io/api/batch/v2alpha1; to add it:
        go get k8s.io/api/batch/v2alpha1
..\..\..\..\go\pkg\mod\k8s.io\client-go@v12.0.0+incompatible\kubernetes\scheme\register.go:54:2: no required module provides package k8s.io/api/settings/v1alpha1; to add it:
        go get k8s.io/api/settings/v1alpha1
..\..\..\..\go\pkg\mod\k8s.io\client-go@v12.0.0+incompatible\transport\round_trippers.go:26:2: missing go.sum entry for module providing package k8s.io/klog (imported by k8s.io/client-go/rest); to add:
        go get k8s.io/client-go/rest@v12.0.0+incompatible
```

**Comment by jammiemil** [comment]
I assume this is down to nested dependency stuff, in which case am i better off trying to selectively reproduce the code i want from that package so i dont need the dependancies or trying to somehow resolve the dependancy clashes myself? Or am i way off base here

**Comment by jammiemil** [comment]
I have a parser that seems to be working ok for protobuf, at least it passes its tests (Although I have some concerns about dependencies still above), and this will cover my immediate requirements to route logs via telegraf.

However it would be nice if we could mirror the functionality of the Loki listener more completely by including the Json fallback based on the content type, but I'm fairly sure to do that i would need to go down the full input route mirroring roughly what is done here since content type is not passed to the parsers as far as i can tell:

https://github.com/grafana/loki/blob/9e84648f3e176d82780db98e59a34d0e40560d1d/pkg/loghttp/push/push.go#L54

From a bigger picture POV what would be more preferable? Promtail itself only push's logs using protobuf, and with the parser being pretty much complete barring any issues that arise from further testing the simpler route would be to push push the parser and be done with it. Is it more palatable to have a small partial implementation via the parser or a larger more complete implementation using an input plugin?
