### ISSUE TITLE
[inputs.x509_cert] Error in plugin: cannot get SSL cert

### ISSUE THREAD

**Issue by kka22** [influxdata/telegraf#11687]
### Please direct all support questsions to slack or the forums. Thank you.

Installed Packages
Name         : telegraf
Version      : 1.23.3

try next settings:

 [[inputs.x509_cert]]
    sources = ["smtp://192.168.1.14:25"]
    insecure_skip_verify = true

error:
 [inputs.x509_cert] Error in plugin: cannot get SSL cert 'smtp://192.168.1.14:25': unsupported scheme 'smtp' in location smtp://192.168.1.14:25

try change to tcp://
error:
[inputs.x509_cert] Error in plugin: cannot get SSL cert 'tcp://192.168.1.14:25': tls: first record does not look like a TLS handshake

on the remote host 192.168.1.14:25 Postfix

Any idea?

**Comment by srebhan** [comment]
Support for `smtp` is not yet released in `1.23.x`. As the PR has been merged, you either have to wait for `1.24.0`, use a nightly build or build Telegraf from the master branch.
