### ISSUE TITLE
Tail Input Plugin should remove file handle after a certain time

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#11718]
### Use Case

Some applications log one message per file (e.g. ModSecurity for Apache). After creation such a log file no new logs are written to it.
Using telegraf tail input plugin for such log files mean, that tail input plugins open for every new file a tail handler which watches for any changes of this file. This does not "scale", because of a huge amount of unnecessary handlers.

### Expected behavior

There should be a tail input plugin option, where you can set a duration, when a tail handler should be removed from file (maybe depending of last activity of this file).

### Actual behavior

Tail handlers are only removed after telegraf restart.

**Comment by powersj** [comment]
Hi @1tft,

> After creation such a log file no new logs are written to it.

Would the [`directory_monitor`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/directory_monitor) plugin work in this scenario? It sounds like instead you want to read entire files once they are created and then move on?

**Comment by 1tft** [comment]
@powersj Thank you for your reply and the hint regarding _directory_monitor_ plugin. It sounds exaclty what I need to parse these special logs successfully except the issue, that this plugin does not support subdirectories.
App does not only create a single file for each log entry, it also creates (with time based name) a subdirectory inside another (time based) subdirectory. Because of the large amount of logs one file a day would not work.
So I think a better feature request (because of benefits for other use cases) would be "Directory Monitor Input Plugin should support subdirectories". So I can also ask our InfluxDB support regarding this FR, what do you think?

**Comment by powersj** [comment]
>  So I can also ask our InfluxDB support regarding this FR, what do you think?

Please do. In the meantime I will take this to the team to ask which direction makes more sense to go.

**Comment by sspaink** [comment]
@1tft Currently the plugin drops finished files into a "finished directory". If there are sub-directories, would you expected the finished directory to match the hierarchy of the sub-directories it reads from?

**Comment by 1tft** [comment]
I think same sub-directories hierarchy would be the best to avoid file name collision and to avoid losing information which could be found inside directory names. Currently our subdirectories have time naming, so these information would be helpfull for some use cases.
At the moment we changed logrotating regarding this certain log from daily to hourly. So files are removed (zipped) by logrotator and telegraf open files handlers are not too much. I think we can live with this situation for a good while.
