### ISSUE TITLE
Specific prometheus metrics involving NaN causes serialization error, throwing away all other metrics

### ISSUE THREAD

**Issue by lsegawa** [influxdata/telegraf#11727]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  tagexclude = ["url"]

  ignore_timestamp = true
  metric_version = 2

[[outputs.execd]]
  command = ["java", "-Xms64m", "-Xmx128m", "-jar", "/opt/metrics_exporter/lib/metrics_exporter.jar"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2022-08-26T09:28:25Z D! [agent] Starting service inputs
2022-08-26T09:29:09Z D! [serializers.influx] could not serialize field "latency_request": is NaN; discarding field
2022-08-26T09:29:09Z D! [serializers.influx] could not serialize field "latency_request": is NaN; discarding field
2022-08-26T09:29:09Z D! [serializers.influx] could not serialize field "latency_request": is NaN; discarding field
2022-08-26T09:29:26Z D! [serializers.influx] could not serialize field "latency_request": is NaN; discarding field
2022-08-26T09:29:26Z D! [outputs.execd] Buffer fullness: 129 / 10000 metrics
2022-08-26T09:29:26Z E! [agent] Error writing to outputs.execd: error serializing metrics: "prometheus,host=internal-host,quantile=0.5,service=web-service": no serializable fields
```

### System info

Telegraf 1.22.0, CentOS Linux 7

### Steps to reproduce

1. Use prometheus input plugin with `metric_version = 2` configured to load the prometheus metrics output including the following:
```
# HELP latency_request Metric autogenerated by statsd_exporter.
# TYPE latency_request summary
latency_request{service="web-service",quantile="0.5"} NaN
latency_request{service="web-service",quantile="0.9"} NaN
latency_request{service="web-service",quantile="0.99"} NaN
latency_request_sum{service="web-service"} 0
latency_request_count{service="web-service"} 1
```
2. Make sure that latency_request field is the only field with the combination of the following tag `{service="web-service",quantile="0.5"}`
4. Allow execd outputs plugin to load the data as influx data format
5. As a result, the influx data has a line containing metrics without field and measurement, causing an error and throwing away all other metrics that we wish to collect.
...

### Expected behavior

When serializer discards a field, it should check if it would leave a metrics without field and measurement. If so, it should drop the entire metrics.
```
[serializers.influx] could not serialize field "latency_request": is NaN; discarding field
[agent] Error writing to outputs.execd: error serializing metrics: "prometheus,host=internal-host,quantile=0.5,service=web-service": no serializable fields
```

### Actual behavior

When serializer discards a field, it does not check if it would leave a metrics without field and measurement. And when loading the data to execd output plugin, it finds a metrics with no serialized fields, causing all other metrics to be dropped
```
[serializers.influx] could not serialize field "latency_request": is NaN; discarding field
[agent] Error writing to outputs.execd: error serializing metrics: "prometheus,host=internal-host,quantile=0.5,service=web-service": no serializable fields
```

### Additional info

Names of metrics, tags, filenames are obfuscated due to a security concern, However, the obfuscation of each files are consistent, such that any name that appears multiple times did so in the original files as well.

**Comment by sspaink** [comment]
Instead of updating the serializer, perhaps the execd plugin shouldn't error out of the loop and only log and continue? Updating this line to `continue` instead of returning: https://github.com/influxdata/telegraf/blob/master/plugins/outputs/execd/execd.go#L84 I think that should stop it from dropping all metrics.

**Comment by Hipska** [comment]
@sspaink that only solves the case for execd output. Wouldn't it be better to only send 'valid' metrics to any of the outputs?
