### ISSUE TITLE
use system wide proxy settings for prometheus input plugin

### ISSUE THREAD

**Issue by erwiese** [influxdata/telegraf#11728]
### Use Case

The prometheus input plugin does not read the system wide proxy settings. But it should, analogous to other plugins or any other http client. 

Some other plugins additionaly allow to set the proxy explicitly. "proxy = ..." If not set, the system wide proxy settings are used. I don't know if this is really necessary.

### Expected behavior

read system proxy settings

### Actual behavior

pull request follows

**Comment by powersj** [comment]
next steps: get the PR using the common HTTP client that has config options for this

**Comment by erwiese** [comment]
Hi,
Actually there are 2 different behaviors. Some plugins (outputs.datadog, outputs.websocket, inputs.cloudwatch,..) use 
```
#   ## Set http_proxy
#   # use_system_proxy = false
#   # http_proxy_url = "http://localhost:8888"
```
whereas the other ones (outputs.influxdb, outputs.influxdb_v2, inputs.http_response, outputs.newrelic) implicitely use the system proxy settings if http_proxy is unset:
```
#   ## Set http_proxy (telegraf uses the system wide proxy settings if it's is not set)
#   # http_proxy = "http://localhost:8888"
```

But it's fine go with the second solution, as you said.

**Comment by powersj** [comment]
The point of my comment was to point out that we have a built-in method that we would like you to use. That built in method exposes both of those options `http_proxy_url` and `use_system_proxy`. Feel free to include both.
