### ISSUE TITLE
Using group by for telegraf tag keys 

### ISSUE THREAD

**Issue by mehrdad2000** [influxdata/telegraf#11731]
Hi 
I need to create "Status" tag key and try below configuration, but it's not work as expected.
related issue https://github.com/rhuss/jolokia/issues/513

Telegraf config:

```
  [[inputs.jolokia2_agent.metric]]
     name     = "MyCustomMetric"
     mbean    = "AllBeans:category=Color,Name=*"
     paths    = ["TimeToLive","Metric1","Metric3","Active","TimeoutRate","Status"]
     tag_keys = ["Name","Status"]
```

![image](https://user-images.githubusercontent.com/26499665/187116758-9bd9e916-0687-4377-85c6-8c924d8a2ee0.png)

current output of curl:

```
 curl http://ip:port/jolokia-war-unsecured-1.6.2/read/AllBeans:Name=*,category=Color | jq '.'
    "AllBeans:Name=Customer,category=Color": {
      "TimeToLive": 1000,
      "Metric1": 40,
      "Metric2": 0,
      "Metric3": 0,
      "Name": "Customer",
      "Active": true,
      "Status": "OK",
```

current Influx cli result: 
```
> show tag keys from MyCustomMetric
name: MyCustomMetric
tagKey
------
Name
host
jolokia_agent_url

```

expected Influx cli result:
```
> show tag keys from MyCustomMetric
name: MyCustomMetric
tagKey
------
Name
host
jolokia_agent_url
Status
```

expected group by on grafana
![image](https://user-images.githubusercontent.com/26499665/187116857-1ce64fc0-42b2-41d7-a941-cb7769184153.png)

Any idea?
Thanks

**Comment by Hipska** [comment]
I think the best would be to look into the output received from running telegraf in test mode (`telegraf --test`) and see if it s correct there?

**Comment by mehrdad2000** [comment]
@Hipska I've been check that too, telegraf send “status” to influxdb, and on influxdb store correctly.
But consider it as field, need to consider it as tag to use that in “group by” section on grafana.

Any other idea?

**Comment by Hipska** [comment]
Are you saying telegraf is sending it as field instead of tag? Can you paste an output line from the test?

**Comment by mehrdad2000** [comment]
@Hipska AFAIK tag_keys must be "mbean".
first we should write bean name like this:
     mbean    = "AllBeans:category=Color,Name=*"

then we can consider those beans as tag_keys like below:
     tag_keys = ["Name"] 

now question is: "status" is an attribute that belong to the "Name" bean.
telegraf able to consider attribute of bean as tag_keys?


AllBeans
----Color[category]
---------Customer[Name]   attributes(TimeToLive,Metric1,Metric2,Metric3,Name,Active,Status)

color and customer are bean, Status is attribute of customer bean.

any idea?

**Comment by Hipska** [comment]
Please post test output first, then I might be able to help..

Otherwise please go to the forums or chat like tigerbot already said. This place here is for bug reports or feature requests.

**Comment by mehrdad2000** [comment]
@Hipska here is the output:

```
telegraf --test

> MyCustomMetric,Name=***,host=****,jolokia_agent_url=http://IP:PORT/jolokia-war-unsecured-1.6.2/ TimeToLive=1000,Metric1=40,Metric2=0,Metric3=0,Name="***",Active=true,Status="OK", 1661933410000000000
```

**Comment by Hipska** [comment]
That's an invalid one, and from there it is already visible that `Status` is being sent as a field, not a tag.

**Comment by mehrdad2000** [comment]
@Hipska as i mention "Status" is an attribute of "Customer" bean.

here is the current config: (just add status tag key for test and not work)
```
  [[inputs.jolokia2_agent.metric]]
     name     = "MyCustomMetric"
     mbean    = "AllBeans:category=Color,Name=*"
     paths    = ["TimeToLive","Metric1","Metric3","Active","TimeoutRate","Status"]
     tag_keys = ["Name"]
```

**Comment by Hipska** [comment]
Read again, what would happen if you leave it out of `paths` but keep it in `tag_keys`?

If that doesn't work out, then you would need the convertor processor.

**Comment by mehrdad2000** [comment]
@Hipska if I comment #path it will send all attribute of bean, if I set path it will only send those attribute.
would you please explain more about "convertor processor"?

**Comment by Hipska** [comment]
I didn't say to comment out `paths`, I asked what would happen if you remove `"Status"` item from `paths` and keep it in `tag_keys`?

If that turns out to not to work, then the only solution is to use the [converter](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter) plugin, so you can convert the Status field into a tag, see the examples.

**Comment by mehrdad2000** [comment]
@Hipska as I mention if I remove "Status" from paths and keep it in tag_keys, telegraf won't send "Status" as tag or field. 

about converter, how does it work exactly?
does it have performance impact? 
is it store data somewhere while convert them or work in the memory (on the fly)?

**Comment by Hipska** [comment]
Yes, in memory. Please ask in the forums or Slack for additional questions.
