### ISSUE TITLE
nats_consumer doesn't support saving the subject a JSON message was published on

### ISSUE THREAD

**Issue by chris13524** [influxdata/telegraf#11736]
### Use Case

When consuming messages from NATS, if I have multiple subjects with similar message formats, the fields inside might overlap and show up as the same. This separation cannot currently be seen since the subject information is lost.

My suggestion is to add subject to the metric/measurement such that the subject that the message was published on is persisted.

### Expected behavior

Can access and filter by the subject a message was published on.

### Actual behavior

Subject info is lost, messages containing same fields are treated as the same.

**Comment by reimda** [comment]
Hi @chris13524 could you include an example telegraf.conf that reproduces this? I'm especially interested in which json parser you are using.

The `json` parser is not very flexible in how it chooses the metric name, but the `json_v2` parser lets you provide any gjson query for the metric name with the `measurement_name_path` option. https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2#root-config-options

If you're using `json` you might just need to switch to `json_v2`.

**Comment by chris13524** [comment]
I am using `json` parser indeed. However, I don't think `json_v2` would solve my problem since according to my reading `measurement_name_path` would only be able to point to a field in the message, rather than the subject NATS received the message on. If I added the subject to the JSON message, then this information could be retrieved as you suggest, yes, but I don't think this should be necessary in order to access this information.

```
[[inputs.nats_consumer]]
data_format = "json"
servers = [
  "nats://nats"
]
subjects = [
  "subject1",
  "subject2",
  "subject3"
]
 ```

**Comment by reimda** [comment]
I see what you mean. I'm not sure why I assumed in my last comment that the subject would be in the json.

When the plugin receives the nats message, it already has the nats subject accessible in code. It even logs the subject a couple lines after parsing.
https://github.com/influxdata/telegraf/blob/8d416c4b7a001abaa22a7d38ed6a3580412a3540/plugins/inputs/nats_consumer/nats_consumer.go#L218

It would be straightforward to add the subject as a tag. To maintain backward compatibility we would want to make this optional and require the user to change a setting before the subject tag is added.

@chris13524 would you be able to put together a PR to make this change?

**Comment by werjo-gridfuse** [comment]
Hello, we are preparing a PR that will do this and is adding subject parsing like it's done in the mqtt_plugin. 

https://github.com/gridfuse/telegraf/tree/feat_add_nats_subject_parsing

**Comment by werjo-gridfuse** [comment]
Is there anything i can do to speed things up? :D

**Comment by powersj** [comment]
> Is there anything i can do to speed things up? :D

Sorry, I seem to have missed this PR due to holiday time off. Let me circle back with Sven and we can review.
