### ISSUE TITLE
Add new command to list deprecation and plugins

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#11739]
Backwards compatibility is required

Related: https://github.com/influxdata/telegraf/issues/11316

Deprecate the flags `--deprecation-list, --input-list, --output-list` by adding `DEPRECATED:` to the `Usage` field for each. Then add a new command `list` and `deprecated`.

`telegraf list-plugins` ~ print all plugins
`telegraf list-deprecations` ~ print all deprecated plugins and settings

`telegraf list-plugins | grep inputs.`
`telegraf list-deprecations | grep inputs.`

**Comment by powersj** [comment]
The current behavior of `--input-list` for example prints:

```
 ./telegraf --input-list
Available Input Plugins:
  KNXListener
  activemq
  aerospike
  aliyuncms
  amd_rocm_smi
```

What would the new output look like, such that `grep` would allow someone to filter on inputs?

I was hoping we would do something like:

```
# lists all plugins
telegraf list 
# lists only inputs
telegraf list inputs 
# list deprecated plugins
telegraf list deprecated
```

**Comment by Hipska** [comment]
What about
```
> telegraf list
inputs.example
inputs.internal
...
```
