### ISSUE TITLE
Deprecate global plugin filter flags

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#11741]
Backwards compatibility is required

Related: https://github.com/influxdata/telegraf/issues/11316

Deprecate the global flags `--section-filter, --input-filter, --output-filter, --aggregator-filter, --processor-filter` by adding DEPRECATED: to the Usage field for each.

Currently these flags are being used by `--sample-config` which is deprecated, and by `--deprecated-plugins` which will be deprecated here: https://github.com/influxdata/telegraf/issues/11739.

The input and output filter flags are also being set on the config: https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/telegraf.go#L164-L166 but I am not sure why, investigation needs to be done to understand this use case.

edit: It is possible to filter a provided config with input and output, and this does seem to be used

**Comment by sspaink** [comment]
Research: Should you be able to filter config while running Telegraf? Should aggregators and processors be added?

**Comment by Hipska** [comment]
Oh, I'm doing that actually..

**Comment by sspaink** [comment]
@Hipska Would supporting --aggregator-filter, --processor-filter as well to filter the config while running Telegraf be helpful for you?

**Comment by Hipska** [comment]
I'm currently only using input filter to be able to launch a failover instance with influxdb listener input disabled as the port is already taken by the other instance. I can explain more in detail if needed..

**Comment by Hipska** [comment]
It seems like this filtering is not supported (anymore?) by the `test` command. It's something I would like to see added..

**Comment by powersj** [comment]
Closing as these are in use and no need to deprecate or remove them.
