### ISSUE TITLE
[Prometheus] Summary's values aren't parsed correctly if type is histogram 

### ISSUE THREAD

**Issue by mairovichaa** [influxdata/telegraf#11750]
### Relevant telegraf.conf

```toml
[agent]
    omit_hostname = true
[[inputs.http]]
    data_format = "prometheus"
    urls = ["http://localhost:9095/metrics"]
```

### Logs from Telegraf

```text
It will be provided further.
```

### System info

Telegraf 1.23.4

### Steps to reproduce

1. Export following metrics on `http://localhost:9095/metrics`:

```text
# HELP histogram_example Generated from metric instances with name histogram.example
# TYPE histogram_example histogram
histogram_example_count 2.0
histogram_example{quantile="0.95",} 0.050069503
histogram_example_bucket{le="+Inf",} 2.0
histogram_example_bucket{le="1.0",} 2.0
```

2. Run `telegraf --config telegraf.conf --test`

### Expected behavior

Two last lines in the "Actual behaviour"output are unexpected (wrong) ones.

```text
2022-08-31T17:36:08Z I! Starting Telegraf 1.23.4
2022-08-31T17:36:08Z I! Loaded inputs: http
2022-08-31T17:36:08Z I! Loaded aggregators: 
2022-08-31T17:36:08Z I! Loaded processors: 
2022-08-31T17:36:08Z W! Outputs are not used in testing mode!
2022-08-31T17:36:08Z I! Tags enabled: 
> prometheus,url=http://localhost:9095/metrics histogram_example_count=2,histogram_example_sum=0 1661967368000000000
> prometheus,le=+Inf,url=http://localhost:9095/metrics histogram_example_bucket=2 1661967368000000000
> prometheus,le=1,url=http://localhost:9095/metrics histogram_example_bucket=2 1661967368000000000
> prometheus,quantile=0.95,url=http://localhost:9095/metrics histogram_example=0.050069503 1661967368000000000
```

### Actual behavior

Example of output:
```text
2022-08-31T17:36:08Z I! Starting Telegraf 1.23.4
2022-08-31T17:36:08Z I! Loaded inputs: http
2022-08-31T17:36:08Z I! Loaded aggregators: 
2022-08-31T17:36:08Z I! Loaded processors: 
2022-08-31T17:36:08Z W! Outputs are not used in testing mode!
2022-08-31T17:36:08Z I! Tags enabled: 
> prometheus,url=http://localhost:9095/metrics histogram_example_count=2,histogram_example_sum=0 1661967368000000000
> prometheus,le=+Inf,url=http://localhost:9095/metrics histogram_example_bucket=2 1661967368000000000
> prometheus,le=1,url=http://localhost:9095/metrics histogram_example_bucket=2 1661967368000000000
> prometheus,quantile=0.95,url=http://localhost:9095/metrics histogram_example_count=0,histogram_example_sum=0 1661967368000000000
> prometheus,le=+Inf,quantile=0.95,url=http://localhost:9095/metrics histogram_example_bucket=0 1661967368000000000
```

### Additional info

- Prometheus scrapes metrics from the corresponding endpoint correctly.
- Some libs rely on it [link](https://github.com/micrometer-metrics/micrometer/pull/2653/files#diff-41c2b790f8d73106f2ed93aaaf30e416235b038d05a3f889144deed663ee83dc) (look for "Prometheus doesn't balk at a metric being BOTH a histogram and a summary" comment).

**Comment by reimda** [comment]
I haven't seen a prometheus metric like this that is both a summary and a histogram at the same time. It's not mentioned in the text format spec here https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format

It's interesting that micrometer has code to handle this situation, but it would be helpful if we had some documentation from prometheus itself. Can you provide a link to something from the prometheus project? Thanks.

**Comment by mairovichaa** [comment]
@reimda
thank you for the answer.
 
I didn't find any explicitly documented examples of such case in the prometheus project.
But it's not prohibited explicitly neither.

Here https://prometheus.io/docs/concepts/metric_types/#metric-types it is said:
```
These are currently only differentiated in the client libraries (to enable APIs tailored to the usage of the specific types) and in the wire protocol.
The Prometheus server does not yet make use of the type information and flattens all data into untyped time series.
This may change in the future.
```

I was embarrassed by the second sentence.
I think the current implementation is ok and this issue could be closed.
 
ps:
`This may change in the future.` seems to be a good reason to avoid mixing of Summary and Histogram types.

**Comment by MyaLongmire** [comment]
> I think the current implementation is ok and this issue could be closed.

I am going to close this then. If it needs to be reopened in the future feel free to ping one of us :)
