### ISSUE TITLE
Openstack plugin - allow metrics-gathering by non-admin OSP accounts

### ISSUE THREAD

**Issue by rplevka** [influxdata/telegraf#11769]
### Use Case

telegraf version: `v1.23.2`
input plugin: `openstack`

My OSP account does not have permissions to list the services, but it is perfectly capable of accessing other services API.

The current implementation of the plugin seem to rely on the calls to `<auth_endpoint>/v3/services`, rendering the plugin unusable with non-admin accounts.

Not sure what the request is used for, but the service catalog object is retrieved automatically after a successful authentication with the keystone service:
https://docs.openstack.org/keystone/latest/api_curl_examples.html

maybe parsing this catalog should be sufficient?

### Expected behavior

`admin` permissions should not be required, service catalog should be parsed from the `keystone` authentication response

### Actual behavior

plugin trying to gather the services by accessing the [endpoint](https://github.com/influxdata/telegraf/blob/5b48f5da8c4c9edaec7b2e2e5c10c1bef2b217a6/plugins/inputs/openstack/openstack.go#L167) that requires admin privileges

**Comment by powersj** [comment]
@singamSrikar - any thoughts on this approach?

**Comment by srebhan** [comment]
@rplevka please test the PR in #15468 and let me know if that works for you!

**Comment by rplevka** [comment]
@srebhan hi, commented under the PR. The changes seem to work nicely. Thank you!
