### ISSUE TITLE
Telegraf conf parse error

### ISSUE THREAD

**Issue by JeevanAleti** [influxdata/telegraf#11772]
### Please direct all support questsions to slack or the forums. Thank you.

Hi,

When upgrading telegraf from 1.17.2 to 1.21.4 I see a parse error in telegraf.conf file  when starting telegraf container

telegraf.conf file:

> [[outputs.influxdb]]
  urls = ["https://influx-uat.dev.io:443"]
  database = "infra"
  skip_database_creation = true
  precision = "ns"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "admin"
  password = "admin"
  namepass = ["apache"
  ]
  [outputs.influxdb.tagdrop]
    tagSource = ["statsd"]
  ssl_cert = "/etc/telegraf/influxdb.crt"
  ssl_key = "/etc/telegraf/influxdb.key"
  insecure_skip_verify = false

Error
`E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: error parsing influxdb array, line 61:{1692 2236}: found unexpected format while parsing "tagdrop", expecting string array/slice format on each entry`

I am seeing this error from telegraf version > 1.19.

Any recommendations to change the telegraf conf

**Comment by srebhan** [comment]
@JeevanAleti this is not an error, you need to move the `tagdrop` section down to the end of your plugin config. See the forum for details, I answered your post there.
