### ISSUE TITLE
how to read input JSON keys with spaces in them

### ISSUE THREAD

**Issue by BKFCAW** [influxdata/telegraf#11791]
I am trying to use Telegraf to relay information from the Alpha Vantage API site to InfluxDB.  Here is some typical output from the API request:

{
    "Global Quote": {
        "01. symbol": "ABCDE",
        "02. open": "66.7300",
        "03. high": "66.7300",
        "04. low": "66.7300",
        "05. price": "66.7300",
        "06. volume": "0",
        "07. latest trading day": "2022-09-08",
        "08. previous close": "66.2400",
        "09. change": "0.4900",
        "10. change percent": "0.7397%"
    }
}

All of the JSON keys have spaces in them.  Every attempt I have made to parse these in a Telegraf config file (such as extra quotation marks, escaping with backslash) has failed (I get syntax error messages, and no data in InfluxDB).  I have found several sites that offer **different** suggestions how to do this, and not one of them has worked for me.

Can one actually parse this API output in Telegraf?

**Comment by powersj** [comment]
Hi,

This is not the right place to ask for support. Please next time, post your question on our [forums](https://community.influxdata.com/) or our [slack](https://influxdata.com/slack) where the community can help to get you going.

While you neither showed what you tried or what you were getting, to point you in the right direction, try using the JSON V2 parser like so:

```toml
[[inputs.file]]
  files = ["input.json"]
  data_format = "json_v2"
  [[inputs.file.json_v2]]
    measurement_name = "test"
    [[inputs.file.json_v2.object]]
      path = "Global Quote"
```

I get:

```s
test 01._symbol="ABCDE",02._open="66.7300",03._high="66.7300",04._low="66.7300",05._price="66.7300",06._volume="0",07._latest_trading_day="2022-09-08",08._previous_close="66.2400",09._change="0.4900",10._change_percent="0.7397%" 1663074982000000000
```

You can further add options to the V2 parser to customize the data as you wish.
