### ISSUE TITLE
inputs.ntp error parsing "when" (-) as duration

### ISSUE THREAD

**Issue by dimdin** [influxdata/telegraf#11802]
### Relevant telegraf.conf

```toml
[[inputs.ntpq]]
  options = "-pn"
```

### Logs from Telegraf

```text
E! [inputs.ntpq] Error in plugin: parsing "when" (-) as duration failed: strconv.ParseInt: parsing "-": invalid syntax
```

### System info

Telegraf 1.24.0 (git: HEAD@3c4a6516)

### Steps to reproduce

1. Include in ntp.conf a pool. e.g. 
>    pool -4 0.eu.pool.ntp.org maxpoll 7 iburst
2. run `ntpq -pn`
column "when" must have a "-"
3. run telegraf

### Expected behavior

Not getting an error message

### Actual behavior

The error message about parsing "when" is produced when  the server belongs to a pool or when it is stepping. 

### Additional info

The content of "when" column is "-" to denote that the field is meaningless (this is different that 0)

**Comment by dthpulse** [comment]
I have same issue

**Comment by popey** [comment]
Confirmed here also. 

@reimda is this related to issue #11820 ?

**Comment by srebhan** [comment]
@popey I don't think it is related as `ntpq` does not use a parser IIRC.

**Comment by srebhan** [comment]
@dimdin and @dthpulse can you please test #11827 and let me know if it fixes your issue?
