### ISSUE TITLE
Add missing metrics to Riak plugin

### ISSUE THREAD

**Issue by efcasado** [influxdata/telegraf#11803]
### Use Case

To better monitor a Riak cluster running on the latest stable version (ie. `3.0.10`), Telegraf needs to be able to expose all metrics available.

### Expected behavior

The Riak plugin will be able to expose all metrics available in the latest version of Riak (ie. `3.0.10`).

### Actual behavior

The current version of the Riak plugin works with the latest stable version of Riak (ie. `3.0.10`) but it only exposes a limited number of the available metrics.

The list of metrics supported by the current version of the Riak plugin can be found [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/riak/riak.go#L38).

**Comment by reimda** [comment]
I did a quick review of the associated pr and added a few initial questions. Thanks!

**Comment by efcasado** [comment]
@powersj I am no longer working with Riak so I cannot contribute further here. Let's close this `PR` 😊
