### ISSUE TITLE
New Intel DLB input plugin

### ISSUE THREAD

**Issue by bkotlowski** [influxdata/telegraf#11813]
### Use Case

Intel® Dynamic Load Balancer (Intel® DLB) is a hardware managed system of queues and arbiters connecting producers and consumers. It is a PCI device envisaged to live in the server CPU uncore and can interact with software running on cores, and potentially with other devices.
https://www.intel.com/content/www/us/en/download/686372/intel-dynamic-load-balancer.html 

We would like to have a Telegraf input plugin that exposes Intel DLB metrics 

Expose metrics for Intel DLB in Telegraf collector to enable: 

- reliability testing (faults monitoring)
- application tuning via performance / utilization metrics 
- configuration issues detection 

### Expected behavior

In the near future, we will propose PR which adds a new plugin we have created. The plugin will be able to expose DLB metrics from two sources: 

- DPDK-based app for detailed eventdev metrics per device, per port and per queue 

- Sysfs entries from kernel driver for RAS metrics specific core and uncore events which definitions are provided in JSON files.  

### Actual behavior

Currently, it is not possible to gather and expose Intel DLB metrics.

**Comment by reimda** [comment]
Hi @bkotlowski thanks for offering to submit a PR. Looking forward to it.
