### ISSUE TITLE
Write data to influxdb failed on CentOS6.7  via http or upd

### ISSUE THREAD

**Issue by xulz** [influxdata/telegraf#1184]
Hi, Dev
I installed  telegraf on CentOS 6.7, try to collect the default system metrics to another Influxdb on Ubuntu 16.04.
The write report success on logs but the data were never write to influxdb actually.
Try both http or udp, the result is same. But the database or tags could be created successfully.
In the meantime, the telegraf works perfect on another ubuntu server.

Any clues to resolve it? or this is a bug.

My reproduce Environment:
telegraf.log on centos:
> 2016/05/11 10:09:37 Starting Telegraf (version 0.12.1)
2016/05/11 10:09:37 Loaded outputs: influxdb
2016/05/11 10:09:37 Loaded inputs: diskio kernel mem processes swap system cpu disk
2016/05/11 10:09:37 Tags enabled: dc=us-east-1 host=centos rack=1a
2016/05/11 10:09:37 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"centos", Flush Interval:10s
2016/05/11 10:31:10 Gathered metrics, (10s interval), from 8 inputs in 8.426407ms
2016/05/11 10:31:10 Wrote 13 metrics to output influxdb in 344.993µs

influxdb.log on ubuntu:
> InfluxDB  version: 0.12.2
[http] 2016/05/11 01:32:39 CentOS - - [11/May/2016:01:32:39 -0700] POST /write?consistency=&db=telegraf&precision=s&rp=default HTTP/1.1 204 0 - InfluxDBClient ebbcf949-1752-11e6-801d-000000000000 1.566991ms
[http] 2016/05/11 01:32:40 AnotherUbuntu - - [11/May/2016:01:32:40 -0700] POST /write?consistency=&db=telegraf&precision=s&rp=default HTTP/1.1 204 0 - InfluxDBClient ec673ab2-1752-11e6-801e-000000000000 1.122791ms

**Comment by sparrc** [comment]
the logs show that a write occurred, what makes you think it didn't?

**Comment by xulz** [comment]
The data is not exist in influxdb.

**Comment by xulz** [comment]
I have found the cause: the datetime between 2 machines are not synced.
After I enable ntp service on both machine and set them in same timezone, the issue not reproduced.
sorry for trouble.

close it.
Thanks.
