### ISSUE TITLE
Capture console errors and write them to output

### ISSUE THREAD

**Issue by Giu-seppe** [influxdata/telegraf#11847]
### Use Case

I use Telegraf to acquire data from multiple input plugins and then write the data to InfluxDB.
In some cases, however, some devices may lose communication or not yet be turned on by mistake.
Sometimes the user does not immediately realize that the devices are not communicating or even does not know what exactly is not working.

### Expected behavior

Have a way to save the errors present in the console within InfluxDB (in my case) or in any other Telegraf output.

For example, recently the Modbus plugin in the console communicates, via a message, which device is not communicating through its ID. This would be useful information for diagnosing and solving the problem if shown on the dashboard.

One option is to have a bool with the name of the alarm which if the alarm is shown in the console becomes equal to true.

### Actual behavior

Currently, the error is shown only in the console, and if Telegraf is launched as a service (in my case) not even that :(
Whenever a problem occurs or someone thinks there is a problem, Telegraf is run from the console and the console error messages must be read.
Currently, with the "internal-monitor" plugin, I was only able to see the number of alarms for each plugin but this still does not make it clear what error it is
![797b14f100c740d23fd7da2dd9b5115a4551d1ba_2_690x311](https://user-images.githubusercontent.com/65350358/191309089-ac83e604-50fd-42c9-83c0-070417270044.png)

### Additional info

I searched the documentation but couldn't find anything like it. I still wrote a post in the Influxdata forum but got no response.
This is the topic open in the forum [How to view the status of input plugins in the best way](https://community.influxdata.com/t/how-to-view-the-status-of-input-plugins-in-the-best-way/26546)

I do not know if the option written above is the best solution but it seems really strange to me that such a professional tool does not use it has the possibility to use the console error messages in the best possible way

**Comment by powersj** [comment]
Hi @Giu-seppe,

Do you have an example error message and the information you would like stored? I think one option is to grow the internal tracking metric to expose this type of information.

Thanks!

**Comment by Hipska** [comment]
Hi @Giu-seppe, this sounds a lot like this existing Feature request: https://github.com/influxdata/telegraf/issues/10245#issuecomment-993988479

**Comment by Giu-seppe** [comment]
@powersj This is an example of an error that would be useful to have in output.
later this error could be used to analyze the single error or to notify through a viewer
![image](https://user-images.githubusercontent.com/65350358/191725648-023a1ac1-79cb-41ec-8569-f6c2a8844df2.png)


@Hipska Sorry, I didn't see that open issue.
So I guess I'm writing about that issue for updates, right?
Currently, no nightly version has been produced if I'm not mistaken.
I activated notifications for that issue as well. If you need help with testing, I am available to carry out the tests
