### ISSUE TITLE
Benchmark testing serializers / parsers

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#11850]
It would be interesting to do benchmarking on all parsers/serializers  to compare them and investigate which one is the most performant one for your situation if you have the option to choose.

The parsed metrics across all parsers should result in the exact same set of metrics. Similarly, for the serializers, the same starting set of metrics would be used across all serializers. 

All tests could be about a total set of 1M metrics divided in batches of 1, 1000 or 10K metrics. 

A  different set of metrics should be needed as well:
1. `simple,foo=bar value=1.0`
2. `multiple,foo=bar value1=1.0,value2=2.0,value3=3.0`
3. `string,foo=bar value=1.0,string="example"`

The resulting information could be the total time in order to know how many metric/sec can be processed and how many bytes the source/result is in order to compare the efficiency of the given data format.

**Comment by Hipska** [comment]
It looks like the Wavefront serializer already has some similar benchmark tests: https://github.com/influxdata/telegraf/blob/22b0a26b1d48292460f15acf946d96891bf0c726/plugins/serializers/wavefront/wavefront_test.go#L311-L330

**Comment by srebhan** [comment]
@Hipska do you care to split this issue into parsers and serializers? For the parser we do have `json`, `json_v2` and `xpath_json` covered but it would be good to have a checklist...

**Comment by Hipska** [comment]
Do these produce the same set of metrics? The actual intention of this request is to be able to compare performance between different plugins..

**Comment by srebhan** [comment]
@Hipska I tried to, but the feature-set and format is not 100% the same. See https://github.com/influxdata/telegraf/pull/14148 for the PR. I also noticed that I did not yet submit `xpath_json`... Will do some time later...

**Comment by powersj** [comment]
> The actual intention of this request is to be able to compare performance between different plugins..

Both the parsers and serializers do not always use the same data, data comes in different formats for parsers, may omit a timestamp, may only include a single value, have a variety of different options that may also impact performance, etc. We can draw some inference about the level of performance via the allocations and time taken, but keep in mind these are not direct comparisons.

## Serializer PRs

https://github.com/influxdata/telegraf/pull/14277

## Parser PRs

https://github.com/influxdata/telegraf/pull/14276 (dropwizard, form_urlencoded, grok, logfmt, nagios, opentsdb, prometheus, value, wavefront)
https://github.com/influxdata/telegraf/pull/14257 (csv)
https://github.com/influxdata/telegraf/pull/14303 (avro-json, collectd, prometheus remote write)
https://github.com/influxdata/telegraf/pull/14304 (xpath-xml, xpath-json)
https://github.com/influxdata/telegraf/pull/14310 (binary)
https://github.com/influxdata/telegraf/pull/14311 (avro-binary)
https://github.com/influxdata/telegraf/pull/14312 (xpath-proto)
https://github.com/influxdata/telegraf/pull/14313 (xpath-msgpack)
https://github.com/influxdata/telegraf/pull/14314 (xpath-cbor)
https://github.com/influxdata/telegraf/pull/14315 (influx)

## Results

I am including the following as a record of a single point in time.

go: v1.21.4
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor 

### Serializers

carbon2
```
BenchmarkSerialize-32    	 1000000	      1283 ns/op	     614 B/op	       8 allocs/op
BenchmarkSerializeBatch-32    	  417022	      3249 ns/op	    3019 B/op	      37 allocs/op
```

cloudevents
```
BenchmarkSerialize-32    	  208760	      6799 ns/op	    3759 B/op	      46 allocs/op
BenchmarkSerializeBatch-32    	   37575	     35511 ns/op	   16552 B/op	     187 allocs/op
```

csv
```
BenchmarkSerialize-32    	 1254516	       999.5 ns/op	     238 B/op	       4 allocs/op
BenchmarkSerializeBatch-32    	  664038	      2340 ns/op	     952 B/op	      18 allocs/op
```

graphite
```
BenchmarkSerialize-32    	  478585	      3926 ns/op	    1329 B/op	      24 allocs/op
BenchmarkSerializeBatch-32    	  103387	     14632 ns/op	    5772 B/op	     101 allocs/op
```

influx
```
BenchmarkSerialize-32    	 1625901	       736.1 ns/op	      64 B/op	       1 allocs/op
BenchmarkSerializeBatch-32    	  924888	      1900 ns/op	     256 B/op	       1 allocs/op
```

json
```
BenchmarkSerialize-32    	  449954	      3527 ns/op	    2115 B/op	      33 allocs/op
BenchmarkSerializeBatch-32    	  104626	     15139 ns/op	    9008 B/op	     137 allocs/op
```

msgpack

```
BenchmarkSerialize-32    	 1000000	      1168 ns/op	     856 B/op	       6 allocs/op
BenchmarkSerializeBatch-32    	  421542	      3744 ns/op	    3792 B/op	      23 allocs/op
```

nowmetric
```
BenchmarkSerialize-32    	  980362	      1771 ns/op	     736 B/op	       9 allocs/op
BenchmarkSerializeBatch-32    	  329086	      4998 ns/op	    3549 B/op	      33 allocs/op
```

prometheus
```
BenchmarkSerialize-32    	  533132	      2781 ns/op	    1754 B/op	      31 allocs/op
BenchmarkSerializeBatch-32    	  427512	      4423 ns/op	    2304 B/op	      43 allocs/op
```

prometheusremotewrite
```
BenchmarkSerialize-32    	  922468	      1843 ns/op	     900 B/op	      10 allocs/op
BenchmarkSerializeBatch-32    	  511946	      3348 ns/op	    1728 B/op	      22 allocs/op
```

splunkmetric
```
BenchmarkSerialize-32    	  585975	      2882 ns/op	    1441 B/op	      22 allocs/op
BenchmarkSerializeBatch-32    	  158770	      9863 ns/op	    6440 B/op	      91 allocs/op
```

template
```
BenchmarkSerialize-32    	 1702006	       700.8 ns/op	     152 B/op	       5 allocs/op
BenchmarkSerializeBatch-32    	 1527759	       889.5 ns/op	     184 B/op	       4 allocs/op
```

wavefront
```
BenchmarkSerialize-32    	 1000000	      1595 ns/op	     800 B/op	       8 allocs/op
BenchmarkSerializeBatch-32    	  348702	      4435 ns/op	    3168 B/op	      29 allocs/op
```

### Parsers

avro-json
```
BenchmarkParsing-32    	   36304	     35943 ns/op	   17357 B/op	     379 allocs/op
```

avro-binary
```
BenchmarkParsingBinary-32    	   37970	     31038 ns/op	   17173 B/op	     361 allocs/op
```

binary
```
BenchmarkParsing-32    	  680307	      1968 ns/op	     760 B/op	      46 allocs/op
```

collectd
```
BenchmarkParsing-32    	  506454	      2942 ns/op	    1482 B/op	      54 allocs/op
```

csv
```
BenchmarkParsing-32    	  446920	      3296 ns/op	    5736 B/op	      34 allocs/op
```

dropwizard
```
BenchmarkParsing-32    	  217708	      6960 ns/op	    3224 B/op	      74 allocs/op
```

form_urlencoded
```
BenchmarkParsing-32    	  814705	      1758 ns/op	     832 B/op	      21 allocs/op
```

graphite
```
BenchmarkParse-32    	  651531	      2162 ns/op	     872 B/op	      20 allocs/op

```

grok
```
BenchmarkParsing-32    	  183919	      8338 ns/op	    6822 B/op	      41 allocs/op
```

influx
```
BenchmarkParsing-32    	  630385	      2479 ns/op	    1024 B/op	      41 allocs/op
```

influx-upstream
```
BenchmarkParsing-32    	  515392	      2923 ns/op	    1536 B/op	      42 allocs/op
```

json
```
BenchmarkParsingSequential-32    	   89806	     15458 ns/op	    6746 B/op	     154 allocs/op
```

json_v2
```
BenchmarkParsingSequential-32    	   45105	     25802 ns/op	   14664 B/op	     390 allocs/op
```

logfmt
```
BenchmarkParsing-32    	  465423	      3634 ns/op	    5312 B/op	      46 allocs/op
```

nagios
```
BenchmarkParsing-32    	  275727	      6066 ns/op	    6104 B/op	      54 allocs/op
```

opentsdb
```
BenchmarkParsing-32    	  378328	      3945 ns/op	    5648 B/op	      39 allocs/op
```

prometheus
```
BenchmarkParsing-32    	  135038	     11451 ns/op	    8768 B/op	     144 allocs/op
```

prometheusremotewrite
```
BenchmarkParsing-32    	  459816	      3323 ns/op	    2272 B/op	      52 allocs/op
```

value
```
BenchmarkParsing-32    	 3703618	       371.0 ns/op	     168 B/op	       5 allocs/op
```

wavefront
```
BenchmarkParsing-32    	  147772	     10250 ns/op	    7067 B/op	     219 allocs/op
```

xpath-xml
```
BenchmarkParsingXML-32    	   31641	     38829 ns/op	   25240 B/op	     415 allocs/op
```

xpath-json
```
BenchmarkParsingJSON-32    	   46350	     28728 ns/op	   12739 B/op	     335 allocs/op
```

xpath-msgpack
```
BenchmarkParsingMsgPack-32    	   90050	     14696 ns/op	    6137 B/op	     165 allocs/op
```

xpath-cbor
```
BenchmarkParsingCBOR-32    	   63375	     21042 ns/op	   11211 B/op	     280 allocs/op
```

**Comment by x448** [comment]
Based on go.mod, benchmarks for xpath-cbor seem to be using extremely old version (v1.5.1) of fxamacker/cbor which was obsoleted 4 years ago by v2.0.

- Bumping [fxamacker/cbor](https://github.com/fxamacker/cbor) from v1.5.1 to [v2.6.0](https://github.com/fxamacker/cbor/releases) is recommended for best performance and reliability.

- Using Go struct tags (e.g. toarray, keyasint) or non-default settings (datetime format, case-sensitive field name matching, etc.) can boost speed, reduce allocs, and reduce encoded data size.

Cheers!

**Comment by powersj** [comment]
@x448,

Thanks for calling this out. 

@srebhan - it looks like we pull in cbor indirectly via your cborquery repo. That is set to v1.5.1. Could you update the version and we can try updating the version in Telegraf as well?
