### ISSUE TITLE
Telegraf port

### ISSUE THREAD

**Issue by manjunathnayaka22** [influxdata/telegraf#11863]
### Please direct all support questsions to slack or the forums. Thank you.

Hi,

May I know if telegraf get the SNMP and SNMP traps for same ports from remote agents?

Currently only SNMP input is working for the port 161 but traps not accepting and getting below error. Except 160 and 161 port I cannot use anything new port due to remote agent restriction,

Please let me know how to resolve this port issue in Input SNMP trap.

```toml
[[inputs.snmp_trap]]
service_address = "udp://:160"
path = ["/usr/share/snmp/mibs/"]
```
```text
2022-09-22T11:20:21Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifAlias"
2022-09-22T11:20:21Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifCounterDiscontinuityTime"
2022-09-22T11:20:21Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysUpTime.0"
2022-09-22T11:20:21Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "SNMPv2-SMI::enterprises.9148.3.3.1.2.1.1.3.3"
2022-09-22T11:20:21Z D! [agent] Connecting outputs
2022-09-22T11:20:21Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2022-09-22T11:20:21Z D! [agent] Successfully connected to outputs.influxdb_v2
2022-09-22T11:20:21Z D! [agent] Starting service inputs
2022-09-22T11:20:21Z E! [telegraf] Error running agent: starting input inputs.snmp_trap: listen udp :160: bind: address already in use

[root@XXXXXXXXX telegraf]# netstat -naupl
udp        0      0 1.2.14.5.6:55143       12.13.12.160:160        ESTABLISHED 15470/telegraf
```

![remote-agent-port](https://user-images.githubusercontent.com/94129159/191734622-f63debd6-da76-47ac-8b19-0f0d53cceea1.png)

**Comment by Hipska** [comment]
SNMP traps should only be on port 161 as in your image. Probably there is already another instance of telegraf running on that system?

**Comment by manjunathnayaka22** [comment]
Thank you for your response @Hipska 
I dont see this port is utilized in the system, I did performed this command to validate - netstat -naupl

Currently SNMP for port 161 works fine, as I see the table input in InfluxDB.
If I use port either 160 or 161 in snmp.traps input then I get same error. whatever port I use in snmp.input plugin it shows same error. Not sure if there is a bug in this version of Telegraf-1.23.3-1, or some additional configuration require.

**Comment by Hipska** [comment]
Netstat shows port 160 is in use, so if you try to run a new instance of telegraf and try to also use that port, that will not work.

**Comment by manjunathnayaka22** [comment]
Thank you for your input on this. 
When remote agent support only 161 for SNMP traps(in my example Oracle SBC mentioned above screen shot), then how do I use both plugin of Input.Snmp and Input.Traps

**Comment by Hipska** [comment]
You can use both, they don't conflict. `inputs.snmp` does not listen on a port, it connects to external devices. `inputs.snmp_trap` listens to a specific port, so you can't run 2 telegraf instances that listen on the same port.

**Comment by manjunathnayaka22** [comment]
Thank you for the clarification. I just removed the port of 161 in the Inputs.snmp plugin and added only in Inputs.Traps plugin, after restart the service telegraf service, I am getting the below error. But if I use the same port of 161 in inputs.snmp there is no such error.

Please advice further on this.

[telegraf] Error running agent: starting input inputs.snmp_trap: listen udp :161: bind: address already in use

[[inputs.snmp]]
agents = ["udp://10.10.XX.XX"]
version = 2
path = ["/usr/share/snmp/mibs/"]
community = "test"


[[inputs.snmp_trap]]
#"udp://10.19.61.225:161"
service_address = "udp://:161"
path = ["/usr/share/snmp/mibs/"]

**Comment by Hipska** [comment]
Yes, as said before. That is because there is already a telegraf listening on that port running on the same system.
