### ISSUE TITLE
[[inputs.smart]] doesn't work properly when running telegraf as a service, `smartctl` exit status != 0

### ISSUE THREAD

**Issue by SilentAntenna** [influxdata/telegraf#11862]
### Relevant telegraf.conf

```toml
[[inputs.smart]]
## use_sudo is set to false because sudo is not installed. all other parameters are set to default
use_sudo = false
```

### Logs from Telegraf

```text
## actually not related to the bug here

Sep 22 18:04:14 config telegraf[XXXXXX]: 2022-09-22T10:04:14Z D! [agent] Initializing plugins
Sep 22 18:04:14 config telegraf[XXXXXX]: 2022-09-22T10:04:14Z D! [agent] Connecting outputs
Sep 22 18:04:14 config telegraf[XXXXXX]: 2022-09-22T10:04:14Z D! [agent] Attempting connection to [outputs.influxdb_v2]
Sep 22 18:04:14 config telegraf[XXXXXX]: 2022-09-22T10:04:14Z D! [agent] Successfully connected to outputs.influxdb_v2
Sep 22 18:04:14 config telegraf[XXXXXX]: 2022-09-22T10:04:14Z D! [agent] Starting service inputs
Sep 22 18:04:14 config systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 22 18:04:24 config telegraf[XXXXXX]: 2022-09-22T10:04:24Z D! [outputs.influxdb_v2] Wrote batch of 12 metrics in 6.177244ms
Sep 22 18:04:24 config telegraf[XXXXXX]: 2022-09-22T10:04:24Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Sep 22 18:04:34 config telegraf[XXXXXX]: 2022-09-22T10:04:34Z D! [outputs.influxdb_v2] Wrote batch of 12 metrics in 3.03462ms
Sep 22 18:04:34 config telegraf[XXXXXX]: 2022-09-22T10:04:34Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.24.1, Proxmox VE 7.2-1 (Debian 10.2.1-6)

### Steps to reproduce

1. `apt install smartmontools`
2. `telegraf --input-filter smart --output-filter influxdb_v2 > /etc/telegraf/telegraf.conf`
3. `systemctl start telegraf`

### Expected behavior

Telegraf should output the correct S.M.A.R.T info to the database.

### Actual behavior

The problem occurs only when we run telegraf as a `systemd` service. Executing telegraf manually from the console using `telegraf --debug` or `telegraf --test` will not trigger the bug.

When the config file contains `attributes = true`, The output S.M.A.R.T data contains nothing except the exit status of `smartmonctl`, which is not zero.
When we set `attributes` to `false`, One can see from the data that the S.M.A.R.T plugin calls `smartmonctl` twice per disk in a single time frame. One of them succeeds, and the exit status of the other call is not zero.

### Additional info

I have tried different parameter combinations to find the cause of this problem. It was found that:

- Changing the value of `timeout` and `read_method` doesn't solve the problem.
- Changing the user of telegraf service from `telegraf` to `root` doesn't solve the problem.

It seems like the problem is related to the daemon process.

Previous users have already reported similar issues. See the following links:
<https://community.influxdata.com/t/telegraf-input-smart-is-not-working/11959>
<https://community.influxdata.com/t/telegraf-smart-plugin-returns-after-some-time-exit-status-1-but-works-with-telegraf-test/15020>

**Comment by powersj** [comment]
Hi,

As the user in the first similar issue link you mentioned said, you need to be using elevated permissions. Please check out the [permissions section](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/smart#permissions) of the plugin readme.

> ## use_sudo is set to false because sudo is not installed.

Then sudo needs to be installed or you need to elevate the permissions of the user running the telegraf as a service for the `smartctl` and `nvme-cli` commands.

**Comment by SilentAntenna** [comment]
> Hi,
> 
> As the user in the first similar issue link you mentioned said, you need to be using elevated permissions. Please check out the [permissions section](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/smart#permissions) of the plugin readme.
> 
> ```
> > ## use_sudo is set to false because sudo is not installed.
> ```
> 
> Then sudo needs to be installed or you need to elevate the permissions of the user running the telegraf as a service for the `smartctl` and `nvme-cli` commands.

That solves the problem. Thanks!
