### ISSUE TITLE
The linter 'varcheck' is deprecated

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#11873]
When running the linter locally I get the following message:
> WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 

Suggestion is to remove it from the `linters.enable` in `.golangci.yml`.

Also use the existing `//nolint:varcheck` directive as they will become useless.

**Comment by reimda** [comment]
Hi Thomas, could you make a PR to disable this?

**Comment by Hipska** [comment]
Done: #11910
