### ISSUE TITLE
Elasticsearch input fails if Shield is enabled - needs to support sending authentication

### ISSUE THREAD

**Issue by rmoff** [influxdata/telegraf#1189]
If [Shield](https://www.elastic.co/guide/en/shield/current/) is configured on Elasticsearch, all access requires authentication. From what I can see, the Telegraf plugin does not offer this as a configuration option. Without it, requests fail and the plugin cannot be used: 

```
Error in input [elasticsearch]: elasticsearch: API responded with status-code 401, expected 200
```

**Comment by lsthor** [comment]
Hi, I am facing the same problem too, the temporary solution I found is to include the username and password in the URL, for example, http://username:password@localhost:9200, after I did this I am able to retrieve the stats from the elasticsearch node. Hope this helps.

**Comment by sparrc** [comment]
If elasticsearch "shield" is just basic auth then it's already supported, as @lsthor said above.

If anyone wants to take on an easy github fix then please update the documentation and we can close this issue.

**Comment by sparrc** [comment]
nevermind, this is already done https://github.com/influxdata/telegraf/pull/2065
