### ISSUE TITLE
inputs.cisco_telemetry_mdt plugin doesn't process the returned list properly

### ISSUE THREAD

**Issue by hailumeng** [influxdata/telegraf#11906]
### Relevant telegraf.conf

```toml
[[inputs.cisco_telemetry_mdt]]
 ## Telemetry transport can be "tcp" or "grpc".  TLS is only supported when
 ## using the grpc transport.
 transport = "grpc"

 ## Address and port to host telemetry listener
 service_address = ":57500"

 ## Grpc Maximum Message Size, default is 4MB, increase the size.
 max_msg_size = 4000000

# Send output to file for debugging
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Logs from Telegraf

```text
We are testing with cisco switch using gRCP dialout to telegraf. The specific yang node we are testing is Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware or xpath /device-hardware-xe-oper:device-hardware-data/device-hardware.

Output in influx format from telegraf receiving the date from the node above:
Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware,device=DC1-SDA-FE1,host=telegraf,path=Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware,subscription=3311 device_inventory/hw_type="hw-type-cpu",device_inventory/hw_dev_index=4i,device_inventory/version=" 6",device_inventory/part_number=" GenuineIntel",device_inventory/serial_number="LIT213935NN",device_inventory/hw_description=" Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz",device_inventory/dev_name="CPU",device_inventory/field_replaceable=false,device_inventory/hw_class="hw-class-physical",device_system_data/current_time="2022-09-28T20:49:47.326000+00:00",device_system_data/boot_time="2022-06-09T15:55:07+00:00",device_system_data/software_version="Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.6.2, RELEASE SOFTWARE (fc7)
```

### System info

Telegraf 1.21.4

### Steps to reproduce

1. Configure Cisco Cat9k switch to send telemetry through gRPC to telegraf
2. Check the output of telegraf in influx format
3. 
...

### Expected behavior

Node                                     : DC1-SDA-FE1
Subscription                             : 3011
Path                                     : Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware

/device-inventory/hw-type                                                        : hw-type-emmc
/device-inventory/hw-dev-index                                                   : 0
/device-inventory/version                                                        : V01
/device-inventory/part-number                                                    : C9300-48U
/device-inventory/serial-number                                                  : FCW2137G07W
/device-inventory/hw-description                                                 : c93xx Stack
/device-inventory/dev-name                                                       : c93xx Stack
/device-inventory/field-replaceable                                              : False
/device-inventory/hw-class                                                       : hw-class-physical
/device-inventory/hw-type                                                        : hw-type-chassis
/device-inventory/hw-dev-index                                                   : 1
/device-inventory/version                                                        : V01
/device-inventory/part-number                                                    : C9300-48U
/device-inventory/serial-number                                                  : FCW2137G07W
/device-inventory/hw-description                                                 : C9300-48U
/device-inventory/dev-name                                                       : Switch 1
/device-inventory/field-replaceable                                              : True
/device-inventory/hw-class                                                       : hw-class-physical
/device-inventory/hw-type                                                        : hw-type-pem
/device-inventory/hw-dev-index                                                   : 2
/device-inventory/version                                                        : V02
/device-inventory/part-number                                                    : PWR-C1-1100WAC    
/device-inventory/serial-number                                                  : LIT213935NN
/device-inventory/hw-description                                                 : Switch 1 - Power Supply B
/device-inventory/dev-name                                                       : Switch 1 - Power Supply B
/device-inventory/field-replaceable                                              : True
/device-inventory/hw-class                                                       : hw-class-physical
/device-inventory/hw-type                                                        : hw-type-dram
/device-inventory/hw-dev-index                                                   : 3
/device-inventory/version                                                        : 
/device-inventory/part-number                                                    : 
/device-inventory/serial-number                                                  : 
/device-inventory/hw-description                                                 : Physical Memory
/device-inventory/dev-name                                                       : Memory
/device-inventory/field-replaceable                                              : False
/device-inventory/hw-class                                                       : hw-class-physical
/device-inventory/hw-type                                                        : hw-type-cpu
/device-inventory/hw-dev-index                                                   : 4
/device-inventory/version                                                        :  6
/device-inventory/part-number                                                    :  GenuineIntel
/device-inventory/serial-number                                                  : 
/device-inventory/hw-description                                                 :  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz
/device-inventory/dev-name                                                       : CPU
/device-inventory/field-replaceable                                              : False
/device-inventory/hw-class                                                       : hw-class-physical
/device-system-data/current-time                                                 : 2022-09-28T21:02:14.826000+00:00
/device-system-data/boot-time                                                    : 2022-06-09T15:55:07+00:00
/device-system-data/software-version                                             : Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.6.2, RELEASE SOFTWARE (fc7)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Tue 23-Nov-21 12:41 by mcpre
/device-system-data/rommon-version                                               : IOS-XE ROMMON
/device-system-data/last-reboot-reason                                           : Reload Command
/device-system-data/reason-severity                                              : normal
/device-system-data/unsaved-config                                               : True

### Actual behavior

The issue here with telegraf is it doesn't show the whole list of result like yangsuite shows. There are 4 list members in the expected output but telegraf only shows the last list number which is below:
/device-inventory/hw-type                                                        : hw-type-cpu
/device-inventory/hw-dev-index                                                   : 4
/device-inventory/version                                                        :  6
/device-inventory/part-number                                                    :  GenuineIntel
/device-inventory/serial-number                                                  : 
/device-inventory/hw-description                                                 :  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz
/device-inventory/dev-name                                                       : CPU
/device-inventory/field-replaceable                                              : False
/device-inventory/hw-class                                                       : hw-class-physical
/device-system-data/current-time                                                 : 2022-09-28T21:02:14.826000+00:00
/device-system-data/boot-time                                                    : 2022-06-09T15:55:07+00:00
/device-system-data/software-version                                             : Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.6.2, RELEASE SOFTWARE (fc7)

**Comment by reimda** [comment]
The code that maps from the telemetry response to a telegraf metric is here in the handleTelemetry func:
https://github.com/influxdata/telegraf/blob/fae64e2a6399b7fad880528f0dbb8407740de40f/plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go#L357

If it's not mapping the fields correctly, it would result in missing data.

To fix handleTelemetry, it would help to have a copy of the response packet from your device. With the response we could add a unit test with the expected output to make sure the plugin handles everything.

Do you know if any cisco telemetry tools save the response as a file? You mentioned yangsuite. Does it have a verbose or debugging option that saves the response?

**Comment by carlosabalde** [comment]
I think I'm experiencing the same issue for `Cisco-IOS-XE-process-cpu-oper`: 

```
❯ pyang -f tree Cisco-IOS-XE-process-cpu-oper.yang 
module: Cisco-IOS-XE-process-cpu-oper
  +--ro cpu-usage
     +--ro cpu-utilization
        +--ro five-seconds?          uint8
        +--ro five-seconds-intr?     uint8
        +--ro one-minute?            uint8
        +--ro five-minutes?          uint8
        +--ro cpu-usage-processes
           +--ro cpu-usage-process* [pid name]
              +--ro pid                 uint32
              +--ro name                string
              +--ro tty?                uint16
              +--ro total-run-time?     uint64
              +--ro invocation-count?   uint32
              +--ro avg-run-time?       uint64
              +--ro five-seconds?       decimal64
              +--ro one-minute?         decimal64
              +--ro five-minutes?       decimal64
```

The switch is submitting the whole list of processes, but only the last one is received by the plugin. I assume that's not the expected behavior, right?

**Comment by carlosabalde** [comment]
@tgoehler, please, check my comment in #14512. I think using the `embedded_tags` setting will fix your problem too.
