### ISSUE TITLE
Modbus - Add FLOAT16 data type

### ISSUE THREAD

**Issue by dfousek** [influxdata/telegraf#11907]
### Use Case

Hi !
I want to implement InfluxDB/Telegraf communication using a MorningStarCorp's Solar Charger that uses FLOAT16 (!!) data types. Up to now, I need to pass through LabVIEW routines mainly to perform this FLOAT16-FLOAT32 conversions.

Having searched a bit, it appears that is is not uncommon and indeed there is also a standard for it (IEEE 754) https://en.wikipedia.org/wiki/Half-precision_floating-point_format

**_Note that at the end of the MorningStar document, there are conversion code examples (C, Javascript)_** 

I would very much appreciate this addition to Telegraf/Modbus
Thanks in advance
Dimitri

[technical-doc-prostar-mppt-modbus-specification-en.pdf](https://github.com/influxdata/telegraf/files/9674843/technical-doc-prostar-mppt-modbus-specification-en.pdf)

### Expected behavior

Introduce FLOAT16 data type

### Actual behavior

No equivalent data type

### Additional info

Stick to: IEEE 754 floating numbers format.
https://en.wikipedia.org/wiki/Half-precision_floating-point_format

**Comment by srebhan** [comment]
@dfousek any chance you submit a PR?

**Comment by dfousek** [comment]
Sven, what's PR ?

**Comment by srebhan** [comment]
It is a pull-request, i.e. you implement that new feature and we will add it to Telegraf after review. Here is some documentation on pull requests: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by dfousek** [comment]
Sven, this is a feature request to the developers. I don't have the knowledge to do it.

**Comment by srebhan** [comment]
@dfousek can you please test PR #12340 and let me know if this fixes your problem!? You may want to use the binary built by CI which will be available after all tests passed...
