### ISSUE TITLE
Undefined but requested input: socketstat

### ISSUE THREAD

**Issue by AliRezaBeigy** [influxdata/telegraf#11917]
### Relevant telegraf.conf

```toml
[[inputs.socketstat]]
  socket_types = [ "tcp", "udp" ]
```

### Logs from Telegraf

```text
2022-10-01T17:38:42Z I! Starting Telegraf 1.21.4+ds1-0ubuntu2
2022-10-01T17:38:42Z E! [telegraf] Error running agent: Error loading config file ./telegraf.conf: error parsing socketstat, Undefined but requested input: socketstat
```

### System info

Telegraf 1.21.4, Ubuntu 20

### Steps to reproduce

1. run the config cause undefined error

### Expected behavior

run without issue

### Actual behavior

throws following error:
```error parsing socketstat, Undefined but requested input: socketstat```

**Comment by powersj** [comment]
Hi,

The socketstat plugin was added in [v1.22.0](https://github.com/influxdata/telegraf/releases/tag/v1.22.0).
