### ISSUE TITLE
[inputs/modbus] Add configurable after connection delay

### ISSUE THREAD

**Issue by joerg-git** [influxdata/telegraf#11919]
### Use Case

Hello,
I need a delay after connecting the modbus tcp slave before the first modbus request is executed. This could be a workaound parameter like "delay_after_connect" or "pause_after_connect" in ms (100 - 2000ms). Openhab calls this "afterConnectionDelayMillis" Connection warm-up time. Additional time which is spent on preparing connection which should be spent waiting while end device is getting ready to answer first modbus call. In milliseconds.

### Expected behavior

The modbus master should wait a configurable time (in ms) after establishing the connection before the first request.

### Actual behavior

Actually telegraf (1.24.1) connects the slave and directly starts requesting the slave. For my slave this first request comes to fast and it does not respond. For telegraf this leads to a timeout. When the connection is not closed, the next requests are correctly responded (2nd, 3rd, ...). But I'm using the workaround "close_connection_after_gather" because I don't want to block the slave's modbus port 502 (it can only handle one master at a time). This leads to an endless timeout loop.

**Comment by srebhan** [comment]
@joerg-git I see. Do you care to submit a PR? If so, please let me know (e.g. request a review from me) and I'll take a look.

**Comment by joerg-git** [comment]
@srebhan Unfortunately, I don't know anything about PR and have never coded anything in golang. I also do not know the flow of plugins in telegraf, but is a pause allowed after a successful connection:
```// Connect to a MODBUS Slave device via Modbus/[TCP|RTU|ASCII]
func (m *Modbus) connect() error {
	err := m.handler.Connect()
	m.isConnected = err == nil
  if m.isConnected {
     nextRequest := time.Now().Add(time.Duration(m.Workarounds.AfterConnectPause))
     time.Sleep(time.Until(nextRequest))
  }
	return err
}
```
_AfterConnectPause_ would be a new configuration parameter which has to be added like the _PollPause_ workaround.
If someone is able to integrate this (if it's compliant with coding rules) I'm able to test it.

**Comment by srebhan** [comment]
PR fixing this merged. Please reopen if this didn't fix your issue.
