### ISSUE TITLE
Opensearch output plugin

### ISSUE THREAD

**Issue by mannukalra** [influxdata/telegraf#11922]
### Use Case

A separate output plugin for Opensearch.

### Expected behavior

Seamless output plugin for Opensearch. 

### Actual behavior

Elasticsearch plugin works but after certain workarounds, which may not be compatible with future releases of Opensearch.

**Comment by powersj** [comment]
Hi,

Sorry, I thought this was for on output at first, like #11345. What type of metrics were you interested in seeing from OpenSearch? Is the elasticsearch input plugin not something that works in opensearch still either?

Thanks

**Comment by mannukalra** [comment]
This is embarrassing :(
Apologies, I meant output plugin only.

**Comment by MyaLongmire** [comment]
@mannukalra since you meant the output plugin I am going to close this again. As @powersj mentioned, it is a duplicate of #11345 and all updates will be posted there! :)
