### ISSUE TITLE
Build version info not updated for 1.24.2

### ISSUE THREAD

**Issue by ganeshsrvnn** [influxdata/telegraf#11973]
Hi,

Telegraf version 1.24.2
![version_info](https://user-images.githubusercontent.com/873152/195002846-4388f629-b9f6-4fd3-94e9-bcb384dd9410.jpg)

It seems the build version info for the release 1.24.2 is not updated in build_version.txt file, it has the value as 1.24.1. On building an rpm package the version info of the package is still 1.24.1.
The file at below location should have a modified value as 1.24.2.
https://github.com/influxdata/telegraf/blob/v1.24.2/build_version.txt

regards,
Saravanan G

**Comment by powersj** [comment]
@ganeshsrvnn, out of curiosity why are you building an RPM from a tag, when we provide builds? Are you customizing telegraf somehow?

I have updated the `release-1.24` branch, however I am not going to update the tag as a lot of automated things happen when the tag is updated.

@popey @sspaink FYI not sure why this wasn't done during the last release, but this needs to be done.

**Comment by ganeshsrvnn** [comment]
> @ganeshsrvnn, out of curiosity why are you building an RPM from a tag, when we provide builds? Are you customizing telegraf somehow?

@powersj , I use the recent stable version of go lang to package telegraf from the source code. The purpose was mainly to address any known security vulnerabilities from the older go versions.

**Comment by powersj** [comment]
> I use the recent stable version of go lang to package telegraf from the source code.

Ah ok, typically we should be pulling in the latest on each minor release. Master is already at v1.19.2.

I'm going to go ahead and close this as I don't think there is anything left to do, but thanks for bringing it to our attention.
