### ISSUE TITLE
[input:tomcat] wrong fields in docs

### ISSUE THREAD

**Issue by karniemi** [influxdata/telegraf#11974]
### Relevant telegraf.conf

```toml
not relevant
```

### Logs from Telegraf

```text
not relevant
```

### System info

not relevant

### Steps to reproduce

1. Read the doc
2. Observe/use the system, the documented fields are not there - but something very different
3.
...

### Expected behavior

The fields in the system match the documented fields:
* https://www.influxdata.com/integration/apache-tomcat/
* https://github.com/influxdata/telegraf/blob/master/plugins/inputs/tomcat/README.md

### Actual behavior

At least, "tomcat_jvm_memorypool" does not have these fields, but something very different:
max_threads
current_thread_count
current_threads_busy
max_time
processing_time
request_count
error_count
bytes_received
bytes_sent

**Comment by karniemi** [comment]
With tomcat9 I see fields as listed below. To me, it would seem that someone accidentally copy-pasted the fields from tomcat_connector to tomcat_jvm_memorypool in the documentation.

tomcat_connector:
-----------------
request_count	
processing_time
max_time
max_threads
error_count
current_threads_busy
current_thread_count
bytes_sent
bytes_received

tomcat_jvm_memory:
-------------------
total	
max
free

tomcat_jvm_memorypool:
-------------------
used	
max
init
committed

**Comment by powersj** [comment]
Thank you for the list. I have put up: https://github.com/influxdata/telegraf/pull/12018 can you review that and see if it looks correct?
