### ISSUE TITLE
Cloudwatch plugin needs some throttling

### ISSUE THREAD

**Issue by goller** [influxdata/telegraf#1197]
I'm getting API throttling from AWS when I'm using cloudwatch plugin.  It would be nice to have some throttling.  AWS has guidelines here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html

**Comment by sparrc** [comment]
can this not be controlled by using the `interval` config option?

**Comment by goller** [comment]
Sadly, no:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go#L142
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go#L221

If I'm reading this correctly, this will create 64 concurrent requests to AWS.  Additionally, there is no delay in executing subsequent requests.

**Comment by catufunwa** [comment]
Hey! I'm still getting throttling from AWS even with version 1.0.0-beta3, is there a config I need to add to enable this?

**Comment by sparrc** [comment]
there isn't, it should be doing it automatically, but we might want to add a config option for how many requests per second to limit it to

**Comment by tmonk42** [comment]
Considering that the API rate limit for GetMetricStatistics can be raised (ie: I might want that throttle higher) and I might have other tools querying metrics against the account (ie: I might want that throttle lower), feels correct that the requests per second cap should be a config option.

Relatedly, if I define multiple inputs.cloudwatch sections, is the throttle global for all of Telegraf or per input/namespace?

**Comment by sparrc** [comment]
@tmonk42 it's per input
