### ISSUE TITLE
http_response plugin isn't passing headers

### ISSUE THREAD

**Issue by cheald** [influxdata/telegraf#1198]
I have a Telegraf input configured as so:

```
[[inputs.http_response]]
  address = "http://127.0.0.1/features/"
  response_timeout = 10
  method = "GET"
  [inputs.http_response.headers]
    Host = "mydomain.com"
```

But headers aren't being passed. When I turn on debug logging in nginx, I see that the Host headers is `127.0.0.1`, not `mydomain.com` as expected.

```
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http request line: "GET /features/ HTTP/1.1"
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http uri: "/features/"
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http args: ""
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http exten: ""
2016/05/13 23:30:20 [debug] 4877#0: *6791491 posix_memalign: 00000000020B6790:4096 @16
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http process request header line
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http header: "Host: 127.0.0.1"
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http header: "User-Agent: Go-http-client/1.1"
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http header: "Accept-Encoding: gzip"
2016/05/13 23:30:20 [debug] 4877#0: *6791491 http header done
```

Have I misconfigured the input, or is there an actual bug here?

**Comment by sparrc** [comment]
This is probably because the plugin treats the `host` tag specially as the Host header. I will make it so it can be overridden by user specified headers.

**Comment by sparrc** [comment]
@cheald is that your full telegraf configuration for http_response? there might be an ordering issue with the body and headers arguments

**Comment by sparrc** [comment]
looks like this is actually a golang issue that they can't safely change for backwards-compatability reasons: https://github.com/golang/go/issues/7682. We'll need to modify request.Host directly.

**Comment by cheald** [comment]
Fantastic, thanks!
