### ISSUE TITLE
OPCUA should support DateTime values

### ISSUE THREAD

**Issue by vsinha** [influxdata/telegraf#12006]
### Use Case

I've discovered that the opcua plugin successfully collects datetime values, but these values fail to be serialized in `metric/metric.go`, and so are discarded.

Adding the following to `convertField` causes the values to be properly parsed (verifying with `--test`)
```go
	case time.Time:
		return v.String()
```

I'm happy to submit a PR or follow this work forward-- however I'm not sure why this is happening in the first place. I've configured the OPCUA values to be parsed as the string type in my telegraf.yaml:

```yaml
# Redacted snippet from config file. We have several 'nodes' configured and those all work just fine. 
[inputs.opcua]
  ...
  nodes = [
  {name="TimeValue", namespace="4", identifier_type="s", identifier="Path.To.Time"},
  ]
```

We're using influxdb as the output, but i've been testing from the repo tip using `--test` and can replicate that the datetime values are never returned, even thought the metric itself is 'OK' and the other values are being parsed. Output from the relevant section of the `--test` command (again, redacted.. happy to provide more details):

```
> MyHost,host=MyHostName,id=ns\=4;s\=Path.To.Time Quality="OK (0x0)" 1665621052000000000
> MyHost,host=MyHostName,id=ns\=4;s\=Path.To.Numerical.Value Numerical.Value=2.0999999046325684,Quality="OK (0x0)" 1665621052000000000
```

### Expected behavior

I expect it to forward the datetime values (perhaps as strings) to the outputs.

### Actual behavior

The values are never forwarded to the outputs.

### Additional info

It's possible this should be a bug report instead, my apologies for submitting it as a feature request if so.

**Comment by powersj** [comment]
@srebhan @R290 - thoughts on this? I don't feel I know enough about opc ua to comment

**Comment by vsinha** [comment]
I tweaked my fix slightly to only modify the opcua input plugin itself, and I submitted a PR!

**Comment by R290** [comment]
I don't know much either, but DateTime seems to be an offical datatype: https://reference.opcfoundation.org/Core/Part6/v104/5.1.2/

**Comment by srebhan** [comment]
> @srebhan @R290 - thoughts on this? I don't feel I know enough about opc ua to comment

Me neither. ;-) However, I feel confident to *review* a PR. :-)

**Comment by vsinha** [comment]
@srebhan i have an open PR here that you could review! https://github.com/influxdata/telegraf/pull/12101
