### ISSUE TITLE
Is Telegraf still an agent for collecting, processing, aggregating, and writing metrics?

### ISSUE THREAD

**Issue by blockloop** [influxdata/telegraf#12009]
### Use Case

Given the numerous inputs and outputs that both read and write log formats to log sources does it still make sense to call Telegraf a "metrics" agent? When I introduce Telegraf to new people it isn't immediately obvious to them that although Telegraf may have initially been intended for metrics it works for a number of inputs and outputs including logs and traces. I understand how having log inputs could still classify as a metrics agent if the agent was only collecting stats about those input logs, but it's not. Telegraf is also being used to ingest, process, and output logs _as logs_. 

### Expected behavior

It seems to me that there needs to either a) be a clarification of what the intended use-case for Telegraf is or b) update the phrasing used throughout the documentation to be less metric specific.

I am using Telegraf for collecting logs from machines from various inputs (files, syslog, logstash) and pushing those logs to other outputs (Loki). Telegraf works well and it's fantastic to have a single tool that processes everything since most telemetry is identical in format.

### Actual behavior

The README says "Telegraf is an agent for collecting, processing, aggregating, and writing **metrics**". The project still feels like it's a **metrics agent** that can also do logs and traces. 

### Additional info

Fluentbit is very much like Telegraf with inputs/outputs/processors. I think Telegraf needs to showcase it's ability to do more than just metrics.

**Comment by powersj** [comment]
Hi!

Thanks for the issue. I believe that Telegraf's role has evolved over time in that it was originally great at collecting metrics from things like CPU, memory, etc. However, as you point out it has grown and is now able to parse logs with a variety of included plugins to ultimately create metrics based on logs. I think as an industry the term "metrics, logs, and traces" is used a lot and it means a lot of different things as well.

To make this issue actionable, would you be willing to either put up a PR with some doc changes? Or create a list of places where you think we should update some verbiage?

Thanks!

**Comment by blockloop** [comment]
Yes I can do that. I'll put a PR up soon.
