### ISSUE TITLE
Sflow plugin is unable parse v5 flow from Arista switch 

### ISSUE THREAD

**Issue by MixedGreen** [influxdata/telegraf#12015]
### Relevant telegraf.conf

```toml
[[inputs.sflow]]
  service_address = "udp://:6343"


# Configuration for sending metrics to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://172.21.1.1:8086"]
  token = "$INFLUX_TOKEN"
  organization = "NEW" 
  bucket = "Sflow"


[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["/tmp/metrics.out"]

  ## size.  When set to 0 no size based rotation is performed.
  rotation_max_size = "10MB"
```

### Logs from Telegraf

```text
2022-10-14T07:06:47Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 0 not supported, only version 5
2022-10-14T07:06:49Z D! [inputs.sflow] Unknown sample type: 2
2022-10-14T07:06:49Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 0 not supported, only version 5
2022-10-14T07:06:51Z D! [inputs.sflow] Unknown sample type: 2
2022-10-14T07:06:51Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 0 not supported, only version 5
2022-10-14T07:06:54Z D! [inputs.sflow] Unknown sample type: 2


### additional logs ####

2022-10-14T04:58:15Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 1 not supported, only version 5
2022-10-14T04:58:16Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 1 not supported, only version 5
2022-10-14T04:58:17Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 131082 not supported, only version 5
2022-10-14T04:58:18Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 1 not supported, only version 5
2022-10-14T04:58:19Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 131082 not supported, only
```

### System info

Telegraf 1.24.2, Ubuntu 18.04.6 LTS, Arista EOS 4.23.0F

### Steps to reproduce

1. Create Sflow.conf input plugin
2. Start telegraf
3. Observe logs
4.
...

### Expected behavior

The packets should be parsed and written to File or the Influx location in the telegraf.conf file

### Actual behavior

Log messages show an error that the packet cannot be parsed.

### Additional info

sflowtool output --
[root@localhost ~]# sflowtool -k -p 6343
startDatagram =================================
datagramSourceIP 10.81.108.75
datagramSize 213
unixSecondsUTC 1665723415
localtime 2022-10-14T00:56:55-0400
datagramVersion 5
agentSubId 0
agent 10.81.108.75
packetSequenceNo 5356
sysUpTime 5342000
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 5341
sourceId 0:54001
counterBlock_tag 0:2
dot3StatsAlignmentErrors 0
dot3StatsFCSErrors 0
dot3StatsSingleCollisionFrames 0
dot3StatsMultipleCollisionFrames 0
dot3StatsSQETestErrors 0
dot3StatsDeferredTransmissions 0
dot3StatsLateCollisions 0
dot3StatsExcessiveCollisions 0
dot3StatsInternalMacTransmitErrors 0
dot3StatsCarrierSenseErrors 0
dot3StatsFrameTooLongs 0
dot3StatsInternalMacReceiveErrors 0
dot3StatsSymbolErrors 0
counterBlock_tag 0:1
ifIndex 54001
networkType 6
ifSpeed 10000000000
ifDirection 1
ifStatus 3
ifInOctets 151851948
ifInUcastPkts 22752
ifInMulticastPkts 1978199
ifInBroadcastPkts 12
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 0
ifOutOctets 6996780
ifOutUcastPkts 22761
ifOutMulticastPkts 29542
ifOutBroadcastPkts 1
ifOutDiscards 0
ifOutErrors 0
ifPromiscuousMode 0
endSample   ----------------------
endDatagram   =================================

**Comment by MixedGreen** [comment]
Indeed, however we checked with a PACP and wireshark V3.6.8 and this shows the packets are Sflow V5.
I also had a support case with Arista and they confirmed that V5 is the working version on the switch.

**Comment by powersj** [comment]
Looking at the code [sflow/packetdecoder.go here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sflow/packetdecoder.go#L56) reads the packets and immediately bails if the version is not equal to 5. Printing the version that we got, hence the error messages you see.

The [read function](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sflow/packetdecoder.go#L480) does a binary read in big endian format. The [V5Format struct](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sflow/types.go#L23) is outlined per the [sflow v5 spec](https://sflow.org/sflow_version_5.txt).

That said, having it report "131082" as well as version "1", certainly does not seem right.

In your packet captures, did you see "131082" and if so, what was that field for?

**Comment by MixedGreen** [comment]
From the PCAP the value 131082 doesn't appear anywhere, nor was it in the sflowtool output. We see the Version0 or Version2 error a lot more frequently than the larger numbers.

From the Struct
`type V5Format struct {
	Version        uint32
	AgentAddress   net.IPAddr
	SubAgentID     uint32
	SequenceNumber uint32
	Uptime         uint32
	Samples        []Sample
}`

Comparing with the PCAP 

I see an additional 4 Byte field for "Agent address type" right after the version

![image](https://user-images.githubusercontent.com/115777090/196360167-0380afd5-5589-47e3-84f1-dbb71575435a.png)

Could that be the issue?

**Comment by powersj** [comment]
> Could that be the issue?

The very first thing that is read is the version and that is where it is failing.

I found this comment on an [older issue](https://github.com/influxdata/telegraf/issues/7627#issuecomment-638398144):

> This is because the sflow plugin currently only supports FLOWSAMPLE. COUNTERSSAMPLE is not currently supported.

Is that something you can change?

Otherwise, doing a packet capture when you see a failure would be the next step I think.

**Comment by MixedGreen** [comment]
We are able to change to a FLOWSAMPLE and not send any interface counter data, however the switch stopped sending Sflow packets when we did this. There is an (already active) open case with the vendor to verify the behavior. 

I've attached a PCAP (zipped) with the counters sample information that causes the error message.
[telegraf-sflow.zip](https://github.com/influxdata/telegraf/files/9825980/telegraf-sflow.zip)

**Comment by MixedGreen** [comment]
We got to the bottom of it, the fix was to set the switch to export as FLOWSAMPLE.
On Arista you do this by issuing command "no sflow polling-interval" as COUNTERSSAMPLE is enabled by default.

The output looks like this on the switch:

sFlow Interface (s):
--------------------
Ethernet1 - running(Flow)
Ethernet2 - running(Flow)
Ethernet3 - running(Flow)

Telegraf is writing to Influx and the file without issue.
Thanks for the help!
