### ISSUE TITLE
New zip files for Windows have an internal folder?

### ISSUE THREAD

**Issue by ricardclau** [influxdata/telegraf#1201]
Hi

We were changing our scripts to start installing the latest telegraf version (0.13) from the new urls and we have discovered that the Windows zip files have an internal folder (telegraf-0.13.0-1)

This was not happening before in 0.12 or 0.11

Is this intentional? Any chance the telegraf.exe and conf example can be in the "root" inside the zip file in newer versions? Or at least a consistent folder?

**Comment by sparrc** [comment]
cc @rossmcdonald

**Comment by rossmcdonald** [comment]
This was done on purpose so that the zip contents weren't just dumped into the current directory. I can change it back to the original functionality for the next release if it's a hassle, though. I'm not sure if this helps, but the top-level folder will always be `telegraf-<VERSION>-1` (where the `-1` is the package iteration).

**Comment by ricardclau** [comment]
Well, at least for us, we create a c:\telegraf where we would dump the zip file contents straight away. Maybe some others will follow a different approach, I don't know

I would personally prefer the original functionality but I don't know what other windows users think about this

**Comment by sparrc** [comment]
@rossmcdonald could we not include the version number in the directory? that seems like it would just make things hard for automation

**Comment by rossmcdonald** [comment]
@sparrc I think that's a good compromise. I've never run into any issues with automation, but if that will make things easier than I'll make the change.

**Comment by ricardclau** [comment]
Guys, I am happy either way TBH, I just want it to be consistent across versions for automation :)

Do you know of any other companies actively using the windows telegraf.exe? Maybe we can get some feedback from them as well

Just to put some context, we are using Ansible to install it to both Windows and Linux boxes (have plans to open source the role soon that can talk to both OS as well) and yeah, both approaches can be automated (with and without the folder) with Ansible or any other tool so it is really up to you or the community!

Keep up the good stuff anyway, telegraf is just brilliant!

**Comment by sparrc** [comment]
I don't mind the directory, but would prefer if the version number was not present! I'm not sure what the best or general practice is here but with Golang, when you unzip their zipped packages, is in a directory just called `go/`.

**Comment by ricardclau** [comment]
I just checked consul from Hashicorp and they just pack the consul.exe file in the zip with no folders or anything

Not sure if this is common practice for other go binaries for windows
