### ISSUE TITLE
[[inputs.modbus]] add slave_id in logs

### ISSUE THREAD

**Issue by criticalboot** [influxdata/telegraf#12021]
### Use Case

I have multiple bride devices which will convert RTU to TCP.  Each bridge device is connected to 25 Modbus devices. Some of my devices are failing to send data for various reasons. My goal is to list all the devices which are failing.
From the logs, how to find the faulty ones?  at present IP is logged, I believe If slave_id is also logged we can pinpoint that failing device.
```
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: read tcp 172.21.0.5:42978->192.168.13.106:502: i/o timeout
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: read tcp 172.21.0.5:46838->192.168.13.116:502: i/o timeout
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: dial tcp 192.168.13.122:502: i/o timeout 
```

### Expected behavior

--

### Actual behavior

--

**Comment by criticalboot** [comment]
@MyaLongmire NO, I am running telegraf in docker and the config is below, with debug=true also not printing any extra information about failed ones.
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  # logfile = ""
  logfile="/var/log/telegraf/telegraf.log"
  log_with_timezone = "Asia/Calcutta"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]] 
  urls = ["http://influxdb:8086"]
  token = ${TOKEN}
  organization = "ORG"
  bucket = "logs"
  namepass=["tail"]
  [[inputs.tail]]
    name_override="tail"
    files=["/var/log/telegraf/telegraf.log"]
    from_beginning = false
    watch_method = "poll"
    data_format="grok"
    grok_patterns = ["%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:log-level}! \[inputs.%{GREEDYDATA:plugin}\] Error in plugin: %{WORD:value} tcp %{IP:server}:%{NUMBER:server-port}->%{IP:client}:502: %{GREEDYDATA:error}"]
    grok_custom_pattern_files = []
    grok_custom_patterns = ''' '''
    grok_timezone = "Asia/Calcutta"
  ```

**Comment by MyaLongmire** [comment]
@criticalboot I have put a pr that should add the slave id. Can you please test the artifacts that tiger bot has attached?

**Comment by criticalboot** [comment]
@MyaLongmire A big thanks for putting a pr on this. Now I can parse the log for slave ids. Now I can find the modbus device with is failing. I added a tag for each gateway to distinguish between them. 

I want to made another request, I want some consistency in log to parse with grok.
```
2022-10-19T18:27:03+05:30 E! [inputs.modbus] Error in plugin: connecting failed: dial tcp 192.168.13.134:502: connect: connection refused with slave id: 14
2022-10-19T18:18:50+05:30 E! [inputs.modbus] Error in plugin: slave 10: read tcp 172.21.0.5:33446->192.168.13.121:502: read: connection reset by peer
```
in the above log "slave " part is added in 2 different places for log.  can we adjust the place of slave part in the log?

**Comment by MyaLongmire** [comment]
@criticalboot I have reworded the error to more closely follow the one before. Now they should both read `slave 10: ...`.

If you wouldn't mind giving the new artifacts go, it takes about 45 minutes for ci to run and for them to be posted.
