### ISSUE TITLE
Linter findings in quantile.go should be addressed

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12040]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

`golangci-lint` doesn't find any problems in `plugins/aggregators/quantile/quantile.go`

### Actual behavior

`golangci-lint` found following problems which should be addressed:

```
plugins/aggregators/quantile/quantile.go:45:6  revive  unhandled-error: Unhandled error in call to function algo.Add
plugins/aggregators/quantile/quantile.go:62:4  revive  unhandled-error: Unhandled error in call to function algo.Add
```

### Additional info

Decision needs to be made what to do with metric which couldn't be added to `quantile` aggregator.

**Comment by MyaLongmire** [comment]
next steps: add a logger and log the error
