### ISSUE TITLE
Linter findings for unhandled error in calls to function s.writeProcessedMetrics

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12041]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

`golangci-lint` doesn't find any problems with unhandled error in calls to function `s.writeProcessedMetrics`.

### Actual behavior

`golangci-lint` found following problems which should be addressed:

```
plugins/common/shim/input.go:57:3      revive  unhandled-error: Unhandled error in call to function s.writeProcessedMetrics
plugins/common/shim/processor.go:47:3  revive  unhandled-error: Unhandled error in call to function s.writeProcessedMetrics
```

### Additional info

Decision needs to be made what to do with error returned from `s.writeProcessedMetrics` in goroutine.

**Comment by sspaink** [comment]
I think logging the error is probably the best approach to keep with current behavior but still capture the error. Failing due to the error might be unexpected for current users.

**Comment by MyaLongmire** [comment]
@zak-pawel was this handled by [pr#12088](https://github.com/influxdata/telegraf/pull/12088)?
