### ISSUE TITLE
CompressWithGzip function in internal/internal.go doesn't handle errors properly

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12044]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

`CompressWithGzip` function in `internal/internal.go` handles errors properly (and linters doesn't find any problem).

### Actual behavior

![image](https://user-images.githubusercontent.com/17336997/196484818-ea1ff0bc-b679-425e-9835-5028d3ce1395.png)

In case of error inside goroutine, `CompressWithGzip` will probably never (depends on race condition) return `err` different than `nil`.

Moreover linter found following problems:
```
internal/internal.go:213:3  revive  unhandled-error: Unhandled error in call to function gzipWriter.Close
internal/internal.go:216:3  revive  unhandled-error: Unhandled error in call to function pipeWriter.CloseWithError
```

**Comment by reimda** [comment]
I think we need to refactor CompressWithGzip and actually handle the error. Maybe we need to add a log argument so it has somewhere to write?

I understand err is likely to be nil, but if someone adds a programming error that uses the reader incorrectly, it could return EOF and we would never know about it.

**Comment by srebhan** [comment]
@zak-pawel wouldn't `pipeWriter.CloseWithError(err)` return the error to the side trying to use the compression by reading from it? Yes, `CompressWithGzip` would return a `nil` error in any case, but the user of the output reader will receive the error, wouldn't he?

**Comment by zak-pawel** [comment]
> @zak-pawel wouldn't `pipeWriter.CloseWithError(err)` return the error to the side trying to use the compression by reading from it?

I don't think it would return any meaningful error :)
![image](https://user-images.githubusercontent.com/17336997/208083769-d148bfeb-823c-409d-8f6d-69bd37acaf64.png)

Either there is some great intelligence hidden (and if it's hidden, it's not simple), or error handling `CompressWithGzip` is just wrong on few levels :)
