### ISSUE TITLE
Linter findings for modifying values in value receiver

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12042]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

`golangci-lint` doesn't find any problems for modifying values in value receiver.

### Actual behavior

`golangci-lint` found following problems which should be addressed:

```
plugins/common/starlark/field_dict.go:41:2  revive  modifies-value-receiver: suspicious assignment to a by-value method receiver
plugins/common/starlark/tag_dict.go:40:2    revive  modifies-value-receiver: suspicious assignment to a by-value method receiver
```

**Comment by reimda** [comment]
Even though the method doesn't have a pointer receiver, frozen should be modified through the Metric struct
https://github.com/influxdata/telegraf/blob/b1fc5254e590dc4679ee629806e96a169591a5b7/plugins/common/starlark/field_dict.go#L40

FieldDict has a pointer to Metric struct
https://github.com/influxdata/telegraf/blob/b1fc5254e590dc4679ee629806e96a169591a5b7/plugins/common/starlark/field_dict.go#L17

TagDict is the same situation.

I think we should ignore these linter errors.
