### ISSUE TITLE
Doubts on SQL Server plugin

### ISSUE THREAD

**Issue by ricardclau** [influxdata/telegraf#1206]
Hi

I was testing the SQL Server plugin and I am getting errors when I don't specify any user in the connection string.

Telegraf is running via NSSM using "Local System" as a user, which should be quite close to what a root user is in Linux. I expected it to be able to contact SQL Server but I am getting an error deep in the go sql stdlib

It works when I specify a correct user + password but I was wondering if anyone had success with this plugin with no credentials (avoiding having to create a telegraf SQL Server user)

Any help would be much appreciated! Thanks in advance!

**Comment by zensqlmonitor** [comment]
Hi, 
do you find anything in SQL Server Error Logs ? 
Have you also tried with a local or a domain account ?

**Comment by ricardclau** [comment]
Yeah I need to look at the SQL Server error logs (SQL Server newbie)

We tried with a domain account and everything worked but we would like to avoid having to create a user if "Local System" worked. This is why I opened this issue asking for help

Will dig into the logs to see if I can find anything meaningful

**Comment by zensqlmonitor** [comment]
Principle of least privilege is a better choice.
A dedicated domain account with permission described in the readme file is preferable.
That's the same for linux servers, never connect to a database with the root account.

**Comment by sparrc** [comment]
probably best to create a user, but it sounds like you should open an issue on the https://github.com/denisenkom/go-mssqldb repo and give them the error output and exact steps to reproduce.

**Comment by ricardclau** [comment]
Agreed, thanks for your help and good work on the plugin!
