### ISSUE TITLE
procstat + topk does not sort metrics - returns empty list

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#12068]
I had been trying to get the top 10 processes from linux servers, for which I successfully was able to pull the processes level metrics using the procstat  input plugin configuration (validated with the --test). However when adding the topk processor plugin, there are no metrics returned for the --test and also when running the telegraf as a daemon. Any help on this will be much 
appreciated

procstat plugin config (/tmp/foo.conf)
[[inputs.procstat]]
  pattern = "."
  pid_tag = false

Returns the metrics when running "telegraf --config /tmp/foo.conf --test"

> procstat,host=testmachine,pattern=.,process_name=dsa-connect,user=root child_major_faults=0i,child_minor_faults=0i,cpu_time=307i,cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_system=177.87,cpu_time_user=130.01,cpu_usage=0.7979470386664033,created_at=1665562381000000000i,involuntary_context_switches=0i,major_faults=0i,memory_data=110198784i,memory_locked=0i,memory_rss=19378176i,memory_stack=135168i,memory_swap=0i,memory_usage=0.028819197788834572,memory_vms=730181632i,minor_faults=227200i,nice_priority=20i,num_fds=25i,num_threads=20i,pid=8675i,ppid=8655i,read_bytes=0i,read_count=409097i,realtime_priority=0i,rlimit_cpu_time_hard=9223372036854775807i,rlimit_cpu_time_soft=9223372036854775807i,rlimit_file_locks_hard=9223372036854775807i,rlimit_file_locks_soft=9223372036854775807i,rlimit_memory_data_hard=9223372036854775807i,rlimit_memory_data_soft=9223372036854775807i,rlimit_memory_locked_hard=65536i,rlimit_memory_locked_soft=65536i,rlimit_memory_rss_hard=9223372036854775807i,rlimit_memory_rss_soft=9223372036854775807i,rlimit_memory_stack_hard=9223372036854775807i,rlimit_memory_stack_soft=8388608i,rlimit_memory_vms_hard=9223372036854775807i,rlimit_memory_vms_soft=9223372036854775807i,rlimit_nice_priority_hard=0i,rlimit_nice_priority_soft=0i,rlimit_num_fds_hard=262144i,rlimit_num_fds_soft=1024i,rlimit_realtime_priority_hard=0i,rlimit_realtime_priority_soft=0i,rlimit_signals_pending_hard=256369i,rlimit_signals_pending_soft=256369i,signals_pending=0i,voluntary_context_switches=4i,write_bytes=0i,write_count=1315089i 1666271647000000000
> procstat,host=testmachine,pattern=.,process_name=pybin,user=root child_major_faults=0i,child_minor_faults=899i,cpu_time=150i,cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0.01,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_system=14.12,cpu_time_user=136.36,cpu_usage=0,created_at=1666255635000000000i,involuntary_context_switches=1905i,major_faults=0i,memory_data=55504896i,memory_locked=0i,memory_rss=67457024i,memory_stack=135168i,memory_swap=0i,memory_usage=0.10032200068235397,memory_vms=175239168i,minor_faults=101156i,nice_priority=20i,num_fds=8i,num_threads=1i,pid=269819i,ppid=269815i,read_bytes=0i,read_count=1899951i,realtime_priority=0i,rlimit_cpu_time_hard=9223372036854775807i,rlimit_cpu_time_soft=9223372036854775807i,rlimit_file_locks_hard=9223372036854775807i,rlimit_file_locks_soft=9223372036854775807i,rlimit_memory_data_hard=9223372036854775807i,rlimit_memory_data_soft=9223372036854775807i,rlimit_memory_locked_hard=65536i,rlimit_memory_locked_soft=65536i,rlimit_memory_rss_hard=9223372036854775807i,rlimit_memory_rss_soft=9223372036854775807i,rlimit_memory_stack_hard=9223372036854775807i,rlimit_memory_stack_soft=8388608i,rlimit_memory_vms_hard=9223372036854775807i,rlimit_memory_vms_soft=9223372036854775807i,rlimit_nice_priority_hard=0i,rlimit_nice_priority_soft=0i,rlimit_num_fds_hard=262144i,rlimit_num_fds_soft=1024i,rlimit_realtime_priority_hard=0i,rlimit_realtime_priority_soft=0i,rlimit_signals_pending_hard=256369i,rlimit_signals_pending_soft=256369i,signals_pending=0i,voluntary_context_switches=1693i,write_bytes=132288512i,write_count=37932i 1666271647000000000

Adding the below snippet for topk
[[processors.topk]]
  namepass = ["*procstat*"]
  k = 5
  group_by = ['process_name']
  fields = [ "memory_rss" ]

After adding the above to the same config file at /tmp/foo.conf and running "telegraf --config /tmp/foo.conf --test" does not return any metric

Added the below output config for the stdout to run it with --once and as a daemon, which in wither case does not produce any metric by sorting for top k

[[outputs.file]]
  files = ["stdout" ]

The entire content of the /tmp/foo.conf is as below
[[inputs.procstat]]
  pattern = "."
  pid_tag = false

[[processors.topk]]
  namepass = ["*procstat*"]
  k = 5
  group_by = ['process_name']
  fields = [ "memory_rss" ]

[[outputs.file]]
  files = ["stdout" ]

**Comment by MyaLongmire** [comment]
@sureshsubramaniam sorry to hear you are having issues.

Our processors have recently been getting worked on. Can you test the artifacts of this [pr](https://github.com/influxdata/telegraf/pull/12081) and see if that fixes your issue? Can you also include the version of telegraf you are running?

**Comment by sureshsubramaniam** [comment]
@MyaLongmire  Thanks for responding. The version of the telegraf agent is Telegraf 1.24.2 (git: HEAD@9550e7a5) running on Redhat Linux 8.5. I will grab the PR artifacts and test with the same configurations and update this issue

**Comment by MyaLongmire** [comment]
As the pr has been merged you can grab the artifacts, a build from master, or a nightly build.

**Comment by sureshsubramaniam** [comment]
@MyaLongmire Thanks, i will try a test run today and keep posted with the latest version

**Comment by sureshsubramaniam** [comment]
@MyaLongmire  I took the latest release of telegraf [Telegraf 1.24.3 (git: HEAD@ff7323e1)], it works perfectly fine with the sorting, adding the configurations here for someone who lands here for the top 10 processes metrics 
[[inputs.procstat]]
  interval = "60s"
  mode = "irix"
  pattern = "."
  pid_tag = false
  fieldpass = ["memory_usage","cpu_usage","memory_swap","num_fds","pid" ]

[[processors.topk]]
  period = 10
  add_rank_fields = ["memory_usage","cpu_usage"]
  namepass = ["procstat"]
  k = 5
  group_by = ['process_name']
  fields = [ "memory_usage", "cpu_usage" ]

[[outputs.file]]
  files = ["stdout" ]

telegraf --config ./topk
output
procstat,host=TESTSERVER,pattern=.,process_name=postgres,user=postgres memory_swap=0i,pid=3559527i,num_fds=425i,memory_usage=3.3812456130981445,memory_usage_topk_rank=1i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=postgres,user=postgres cpu_usage=17.089981438031316,pid=3559527i,memory_usage_topk_rank=1i,cpu_usage_topk_rank=1i,memory_swap=0i,num_fds=428i,memory_usage=3.3820314407348633 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_am,user=root pid=1728451i,memory_usage_topk_rank=2i,memory_swap=0i,num_fds=18i,memory_usage=0.7549277544021606 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_am,user=root memory_usage_topk_rank=2i,cpu_usage_topk_rank=3i,memory_usage=0.7518271803855896,num_fds=18i,memory_swap=0i,pid=1728451i,cpu_usage=1.0427138608243114 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_am,user=root memory_usage_topk_rank=2i,cpu_usage_topk_rank=3i,memory_swap=0i,memory_usage=0.0052813878282904625,cpu_usage=0,pid=2825951i,num_fds=4i 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=systemd-journald,user=root pid=1066i,memory_swap=0i,memory_usage_topk_rank=3i,memory_usage=0.4304239749908447,num_fds=38i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=systemd-journald,user=root pid=1066i,memory_usage=0.4304239749908447,cpu_usage=0,memory_swap=0i,num_fds=38i,memory_usage_topk_rank=3i 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_agent,user=root memory_usage=0.5748611092567444,memory_usage_topk_rank=4i,num_fds=51i,pid=2825619i,memory_swap=0i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_agent,user=root memory_swap=0i,num_fds=3i,memory_usage=0.024524644017219543,pid=2824319i,memory_usage_topk_rank=4i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_agent,user=root memory_swap=0i,num_fds=3i,cpu_usage=0,memory_usage=0.024524644017219543,memory_usage_topk_rank=4i,cpu_usage_topk_rank=5i,pid=2824319i 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=ds_agent,user=root memory_swap=0i,memory_usage=0.575062096118927,pid=2825619i,memory_usage_topk_rank=4i,cpu_usage_topk_rank=5i,num_fds=51i,cpu_usage=0.4046226124200408 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=openbeat,user=root pid=1957i,num_fds=11i,memory_swap=0i,memory_usage=0.18275916576385498,memory_usage_topk_rank=5i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=telegraf,user=root memory_usage=0.1714349389076233,num_fds=8i,memory_swap=0i,pid=757424i 1668151880000000000
procstat,host=TESTSERVER,pattern=.,process_name=telegraf,user=root cpu_usage=4.0881979744553405,memory_swap=0i,pid=757424i,memory_usage=0.17455382645130157,num_fds=8i,cpu_usage_topk_rank=2i 1668151890000000000
procstat,host=TESTSERVER,pattern=.,process_name=jbd2/dm-7-8,user=root memory_usage=0,pid=1322i,cpu_usage_topk_rank=4i,cpu_usage=0.202854646500221,memory_swap=0i,num_fds=0i 1668151890000000000
