### ISSUE TITLE
Telegraf can't retrieve remote config file

### ISSUE THREAD

**Issue by eyal-solomon1** [influxdata/telegraf#12089]
### Relevant telegraf.conf

```toml
[agent]  
  interval = "20s"
  round_interval = true
  metric_batch_size = 1000      
  metric_buffer_limit = 10000        
  collection_jitter = "0s"  
  flush_interval = "10s"      
  flush_jitter = "0s"              
  precision = ""                  
  hostname = ""  
  omit_hostname = false

[[outputs.influxdb_v2]]          
  urls = ["${INFLUX_URL}"]  
  token = "${INFLUX_TOKEN}"  
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"


[[inputs.http_listener_v2]]  
  service_address = ":8094"
  methods = ["POST", "PUT","GET"]
  data_format = "influx"
```

### Logs from Telegraf

```
2022-10-23T07:04:28Z I! Error getting HTTP config.  Retry 0 of 3 in 10s.  Status=400
2022-10-23T07:04:38Z I! Error getting HTTP config.  Retry 1 of 3 in 10s.  Status=400
2022-10-23T07:04:48Z I! Error getting HTTP config.  Retry 2 of 3 in 10s.  Status=400
2022-10-23T07:04:58Z E! [telegraf] Error running agent: Error loading config file https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf: Retry 3 of 3 failed to retrieve remote config: 400 Bad Request
```

### System info

Amazon Linux 2

### Docker

official docker image (v 1.22)

### Steps to reproduce

(file is currently public - was like this when got error logs)

according to [Docs](https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#configuration-file-locations) you can specify a remote URL

run `docker run telegraf  --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf`

**(with needed environment variables)**

### Expected behavior

That agent would start and listen on asked port (`8094` for instance)

### Actual behavior

Agent crushes and fails to start (due to not being able to fetch the config file)

**Comment by eyal-solomon1** [comment]
> Below I show I can `wget` the file, and then run the file locally + run the file in a docker container:
> 
> ```
> ❯ wget https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> --2022-10-24 07:10:49--  https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving influxdb-versatile.s3.us-east-2.amazonaws.com (influxdb-versatile.s3.us-east-2.amazonaws.com)... 52.219.94.114
> Connecting to influxdb-versatile.s3.us-east-2.amazonaws.com (influxdb-versatile.s3.us-east-2.amazonaws.com)|52.219.94.114|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 506 [text/plain]
> Saving to: ‘telegraf.conf’
> 
> telegraf.conf               100%[===========================================>]     506  --.-KB/s    in 0s      
> 
> 2022-10-24 07:10:49 (39.3 MB/s) - ‘telegraf.conf’ saved [506/506]
> 
> ~ 
> ❯ cd telegraf
> telegraf on  master via 🐹 v1.19.2 
> ❯ ./telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> 2022-10-24T13:10:59Z I! Starting Telegraf 1.25.0-b3b72aea
> 2022-10-24T13:10:59Z I! Available plugins: 225 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
> 2022-10-24T13:10:59Z I! Loaded inputs: http_listener_v2
> 2022-10-24T13:10:59Z I! Loaded aggregators: 
> 2022-10-24T13:10:59Z I! Loaded processors: 
> 2022-10-24T13:10:59Z I! Loaded outputs: influxdb_v2
> 2022-10-24T13:10:59Z I! Tags enabled: 
> 2022-10-24T13:10:59Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
> 2022-10-24T13:10:59Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
> ^C2022-10-24T13:11:01Z E! [telegraf] Error running agent: connecting output outputs.influxdb_v2: context canceled
> telegraf on  master via 🐹 v1.19.2 took 2s 
> ❯ docker run telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> 2022-10-24T13:11:11Z I! Starting Telegraf 1.24.2
> 2022-10-24T13:11:11Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
> 2022-10-24T13:11:11Z I! Loaded inputs: http_listener_v2
> 2022-10-24T13:11:11Z I! Loaded aggregators: 
> 2022-10-24T13:11:11Z I! Loaded processors: 
> 2022-10-24T13:11:11Z I! Loaded outputs: influxdb_v2
> 2022-10-24T13:11:11Z I! Tags enabled: 
> 2022-10-24T13:11:11Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
> 2022-10-24T13:11:11Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
> ^C2022-10-24T13:11:12Z E! [telegraf] Error running agent: connecting output outputs.influxdb_v2: context canceled
> ```
> 
> ```
> Amazon Linux 2
> ```
> 
> Since you probably are running in AWS are you sure your firewall rules and/or proxies are set up correctly?

Thanks for the detailed response,
Couldn't find any specifications for that, egress traffic is allowed (`wget` the file works on the telegraf container host)
are there more configurations I've might missed ?

**Comment by eyal-solomon1** [comment]
> > wget the file works on the telegraf container host
> 
> Ah good, if you exec into a running container, can you wget from there successfully?
> 
> > are there more configurations I've might missed ?
> 
> I'm not aware off-hand
> 
> > 400
> 
> The 400 status makes me wonder if a proxy is causing issues or maybe a cert is missing in the container? Are you running in an Amazon Linux VM inside EC2? And then running docker on top of that? Or is this fargate, eks, ecs? something else?

wget works 
```
wget https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/production/telegraf.conf
--2022-10-24 15:40:53--  https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/production/telegraf.conf
Resolving influxdb-versatile.s3.us-east-2.amazonaws.com (influxdb-versatile.s3.us-east-2.amazonaws.com)... 52.219.105.114
Connecting to influxdb-versatile.s3.us-east-2.amazonaws.com (influxdb-versatile.s3.us-east-2.amazonaws.com)|52.219.105.114|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 506 [text/plain]
Saving to: 'telegraf.conf'

telegraf.conf                                        100%[=====================================================================================================================>]     506  --.-KB/s    in 0s

2022-10-24 15:40:53 (2.73 MB/s) - 'telegraf.conf' saved [506/506]
```
Using ECS with EC2 as launch type

And as you can see outbound traffic is allowed to all endpoints

<img width="687" alt="Screen Shot 2022-10-24 at 18 44 34" src="https://user-images.githubusercontent.com/74238936/197568504-14ed9d74-4814-4e48-909d-7a50a6a8e22c.png">

**Comment by powersj** [comment]
Can you run `docker image inspect telegraf` on the container image you are using?

Here is my log of docker in an Amazon Linux EC2 instance:

```
[ec2-user@ip-172-31-87-44 ~]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
[ec2-user@ip-172-31-87-44 ~]$ docker run telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
Unable to find image 'telegraf:latest' locally
latest: Pulling from library/telegraf
f606d8928ed3: Pull complete 
47db815c6a45: Pull complete 
bf4849400000: Pull complete 
863a7459c8fe: Pull complete 
0e28af260775: Pull complete 
6f15f27d873f: Pull complete 
9b89a3dd513b: Pull complete 
Digest: sha256:c041b149b338b1edeac1d9cfdaed9531842621e20d3863e04034fb8bfa897f67
Status: Downloaded newer image for telegraf:latest
2022-10-24T15:59:29Z I! Starting Telegraf 1.24.2
2022-10-24T15:59:29Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-10-24T15:59:29Z I! Loaded inputs: http_listener_v2
2022-10-24T15:59:29Z I! Loaded aggregators: 
2022-10-24T15:59:29Z I! Loaded processors: 
2022-10-24T15:59:29Z I! Loaded outputs: influxdb_v2
2022-10-24T15:59:29Z I! Tags enabled: 
2022-10-24T15:59:29Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
2022-10-24T15:59:29Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
^C2022-10-24T15:59:31Z E! [telegraf] Error running agent: connecting output outputs.influxdb_v2: context canceled
```

**Comment by eyal-solomon1** [comment]
> Can you run `docker image inspect telegraf` on the container image you are using?
> 
> Here is my log of docker in an Amazon Linux EC2 instance:
> 
> ```
> [ec2-user@ip-172-31-87-44 ~]$ cat /etc/os-release 
> NAME="Amazon Linux"
> VERSION="2"
> ID="amzn"
> ID_LIKE="centos rhel fedora"
> VERSION_ID="2"
> PRETTY_NAME="Amazon Linux 2"
> ANSI_COLOR="0;33"
> CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
> HOME_URL="https://amazonlinux.com/"
> [ec2-user@ip-172-31-87-44 ~]$ docker run telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> Unable to find image 'telegraf:latest' locally
> latest: Pulling from library/telegraf
> f606d8928ed3: Pull complete 
> 47db815c6a45: Pull complete 
> bf4849400000: Pull complete 
> 863a7459c8fe: Pull complete 
> 0e28af260775: Pull complete 
> 6f15f27d873f: Pull complete 
> 9b89a3dd513b: Pull complete 
> Digest: sha256:c041b149b338b1edeac1d9cfdaed9531842621e20d3863e04034fb8bfa897f67
> Status: Downloaded newer image for telegraf:latest
> 2022-10-24T15:59:29Z I! Starting Telegraf 1.24.2
> 2022-10-24T15:59:29Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
> 2022-10-24T15:59:29Z I! Loaded inputs: http_listener_v2
> 2022-10-24T15:59:29Z I! Loaded aggregators: 
> 2022-10-24T15:59:29Z I! Loaded processors: 
> 2022-10-24T15:59:29Z I! Loaded outputs: influxdb_v2
> 2022-10-24T15:59:29Z I! Tags enabled: 
> 2022-10-24T15:59:29Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
> 2022-10-24T15:59:29Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
> ^C2022-10-24T15:59:31Z E! [telegraf] Error running agent: connecting output outputs.influxdb_v2: context canceled
> ```
```
[
    {
        "Id": "sha256:702613c5fe3808339f71fc74b89ec3ee892bd2a259bfc8328179caf965ca151e",
        "RepoTags": [
            "telegraf:1.22"
        ],
        "RepoDigests": [
            "telegraf@sha256:9b89f91918d2621227dd777ee8c779cf729b8341dd264d1981460298010abbdd"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2022-10-05T23:03:06.128794791Z",
        "Container": "f235dbd1298374b61ca715ce7e414810ee07fd80ea43a1ae957a3c69a38f3e6f",
        "ContainerConfig": {
            "Hostname": "f235dbd12983",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8092/udp": {},
                "8094/tcp": {},
                "8125/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TELEGRAF_VERSION=1.22.4"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"telegraf\"]"
            ],
            "Image": "sha256:c701dd3ff9230717e01ef66603644c243364359fa307d86144e834f49ef84cc0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "20.10.12",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8092/udp": {},
                "8094/tcp": {},
                "8125/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TELEGRAF_VERSION=1.22.4"
            ],
            "Cmd": [
                "telegraf"
            ],
            "Image": "sha256:c701dd3ff9230717e01ef66603644c243364359fa307d86144e834f49ef84cc0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 353963189,
        "VirtualSize": 353963189,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/91799f3b26a44ddc6ef3b9f989da8866692acaa9afd39e5a56793ff747a6d156/diff:/var/lib/docker/overlay2/7772ad23f9bd349e468c388f456bc4a5b6a8c4738ef9e5927662b28d0e50ecf8/diff:/var/lib/docker/overlay2/13a907f8925e86b3335b5c9a6dcff8361d898d583ac15e3429592888574ee133/diff:/var/lib/docker/overlay2/b69682bfb8ee1503f661a74318c7becc70b8564ccac6d0ced95182efa897d100/diff:/var/lib/docker/overlay2/d1001a763e8d36773d785042719003243d9f1a2ab30c4490880882b564ddc750/diff:/var/lib/docker/overlay2/dda48e6189963fc942e30edf5346c5547a4afa091bbdf4f8b5969050aa302e3e/diff",
                "MergedDir": "/var/lib/docker/overlay2/ff0add26ac5dde33563ef5319e45c4c2a6d47c2e11fcd2a2d530dc301b46d483/merged",
                "UpperDir": "/var/lib/docker/overlay2/ff0add26ac5dde33563ef5319e45c4c2a6d47c2e11fcd2a2d530dc301b46d483/diff",
                "WorkDir": "/var/lib/docker/overlay2/ff0add26ac5dde33563ef5319e45c4c2a6d47c2e11fcd2a2d530dc301b46d483/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:8e079fee21864e07daa88efcf74f23ad5ade697c06417d0c04a45dfe580ab7f3",
                "sha256:955c9335e041ebf1840e5d9779a217a5957561086148c7da89bdd4000acd62c4",
                "sha256:186da837555d4da0f772d025f29940370be7a464c2b92871a166941cde9fca3d",
                "sha256:9fd704e23a64c189e3de075545416d0734bf9c1673c243dbf8ae06202da64dd5",
                "sha256:cbf87c336811d8579d74545827f07f99ff24e37d4a3f8ab1e9ba15a4745d8216",
                "sha256:c48eb21fc0e716e9525bab1c581023c5e14456be5190b3aff4e9d9a8e8e9e3d0",
                "sha256:f6a4313d61140e9c57d1cc6199bb78f99ac6a295dd1e69abae61fab3d74e6e57"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```


also adding ECS task definition (relevant parts)
```
{
  "containerDefinitions": [
    {
      "entryPoint": [],
      "portMappings": [
        {
          "hostPort": 0,
          "protocol": "tcp",
          "containerPort": 8094
        }
      ],
      "command": [
        "--config",
        "https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf"
      ],
      "linuxParameters": null,
      "image": "telegraf:1.22",
 
      "name": "telegraf"
    }
  ],
  "networkMode": "bridge",
  "runtimePlatform": {
    "operatingSystemFamily": "LINUX",
    "cpuArchitecture": "X86_64"
  }
}
```

**Comment by powersj** [comment]
```
      "portMappings": [
        {
          "hostPort": 0,
          "protocol": "tcp",
          "containerPort": 8094
        }
```

You have only defined a single port mapping, for container port 8094. Do you need to also specify all the other necessary ports, e.g. 443 for HTTPS, to access the config and InfluxDB?

**Comment by eyal-solomon1** [comment]
> ```
>       "portMappings": [
>         {
>           "hostPort": 0,
>           "protocol": "tcp",
>           "containerPort": 8094
>         }
> ```
> 
> You have only defined a single port mapping, for container port 8094. Do you need to also specify all the other necessary ports, e.g. 443 for HTTPS, to access the config and InfluxDB?

This is for incoming traffic routed by ECS (`0` means a random port is allocated on the host **e.g 0.0.0.0:4912->8094**)
Outgoing traffic is working fine (`wget` the config,`curl` google etc..)

**Comment by powersj** [comment]
> Outgoing traffic is working fine (wget the config,curl google etc..)

Ah right, you said wget in the container worked. I'm honestly at a loss. My version of the hash matches your reported version as well.

Can you reproduce this outside of ECS anywhere?

**Comment by eyal-solomon1** [comment]
> > Outgoing traffic is working fine (wget the config,curl google etc..)
> 
> Ah right, you said wget in the container worked. I'm honestly at a loss. My version of the hash matches your reported version as well.
> 
> Can you reproduce this outside of ECS anywhere?

unfortunately not .. any last suggestions you can think of ?

**Comment by powersj** [comment]
> unfortunately not .. any last suggestions you can think of ?

Do you have any resource limits on the container?

**Comment by yosiasz** [comment]
hold on tiger. this is still and issue.

**Comment by powersj** [comment]
https://github.com/influxdata/telegraf/blob/master/config/config.go#L684

If you unset `INFLUX_TOKEN` does it work?

```
❯ docker run --env INFLUX_TOKEN="FOOBAR" telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
2023-01-10T19:01:55Z I! Error getting HTTP config.  Retry 0 of 3 in 10s.  Status=400
❯ docker run telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
2023-01-10T19:02:42Z I! Starting Telegraf 1.25.0
2023-01-10T19:02:42Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-01-10T19:02:42Z I! Loaded inputs: http_listener_v2
2023-01-10T19:02:42Z I! Loaded aggregators: 
2023-01-10T19:02:42Z I! Loaded processors: 
2023-01-10T19:02:42Z I! Loaded secretstores: 
2023-01-10T19:02:42Z I! Loaded outputs: influxdb_v2
2023-01-10T19:02:42Z I! Tags enabled: 
2023-01-10T19:02:42Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
2023-01-10T19:02:42Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
```

**Comment by eyal-solomon1** [comment]
> https://github.com/influxdata/telegraf/blob/master/config/config.go#L684
> 
> If you unset `INFLUX_TOKEN` does it work?
> 
> ```
> ❯ docker run --env INFLUX_TOKEN="FOOBAR" telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> 2023-01-10T19:01:55Z I! Error getting HTTP config.  Retry 0 of 3 in 10s.  Status=400
> ❯ docker run telegraf --config https://influxdb-versatile.s3.us-east-2.amazonaws.com/telegraf/staging/telegraf.conf
> 2023-01-10T19:02:42Z I! Starting Telegraf 1.25.0
> 2023-01-10T19:02:42Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
> 2023-01-10T19:02:42Z I! Loaded inputs: http_listener_v2
> 2023-01-10T19:02:42Z I! Loaded aggregators: 
> 2023-01-10T19:02:42Z I! Loaded processors: 
> 2023-01-10T19:02:42Z I! Loaded secretstores: 
> 2023-01-10T19:02:42Z I! Loaded outputs: influxdb_v2
> 2023-01-10T19:02:42Z I! Tags enabled: 
> 2023-01-10T19:02:42Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
> 2023-01-10T19:02:42Z E! [agent] Failed to connect to [outputs.influxdb_v2], retrying in 15s, error was 'unsupported scheme ["${INFLUX_URL}"]: ""'
> ```

Thank you for the response, somehow we got it to work (unfortunately can't remember how ..)
you can close this issue
