### ISSUE TITLE
cgroup v2 keyword support

### ISSUE THREAD

**Issue by aiven-amartin** [influxdata/telegraf#12094]
cgroup v2 supports some non-numeric keywords (specifically `max`) for single line values, so this probably needs to be updated:
https://github.com/influxdata/telegraf/blob/4b780889790bf3c855c304cc90e4b8bbafc038db/plugins/inputs/cgroup/cgroup_linux.go#L172

See https://docs.kernel.org/admin-guide/cgroup-v2.html

**Comment by aiven-amartin** [comment]
@reimda I can take a stab yeah. Do you want the change to be within the cgroup input type, or a new `cgroupv2` type?

**Comment by powersj** [comment]
@aiven-amartin,

Are you still interested in working on this? I would be happy to see a PR to the existing cgroup plugin. Did you have thoughts on which way you would implement the fields?
