### ISSUE TITLE
Kafka consumer overwriting host tag

### ISSUE THREAD

**Issue by dvenza** [influxdata/telegraf#1210]
I have a setup where I have several telegraf processes sending data to Kafka via the Kafka output. Then I have one telegraf instance that uses the kafka input to consume the measurements and store them in influxdb.

Since telegraf 0.13 all my measurements have the wrong "host" tag, they seem to be coming from the host that runs the kafka consumer.

This is a big issue for me: telegraf 0.12 crashed every time a new container was spawned in Docker, so I do not want to downgrade, but with 0.13 all my monitoring and dashboards are useless.

**Comment by sparrc** [comment]
this behavior was changed for consistency. A workaround would be for your kafka_consumer telegraf instance to use the `omit_hostname` config option (see https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L62)

**Comment by dvenza** [comment]
But then what about the measurements the kafka_consumer telegraf instance generates by itself from its other inputs (cpu, memory, etc.) ?
They are sent without any host tag?

**Comment by sparrc** [comment]
correct, they wouldn't, this is an unintended consequence of implementing https://github.com/influxdata/telegraf/issues/1054, so I would say it's a bug and I should revert part of that change.

**Comment by dvenza** [comment]
Please, include this fix in the next point release.

**Comment by sparrc** [comment]
you can view the release it will be on in the [changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md)
