### ISSUE TITLE
 E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by bautistamad** [influxdata/telegraf#12118]
### Relevant telegraf.conf

```toml
### TELEMETRY DIAL-IN
[[inputs.cisco_telemetry_mdt]]
  transport = "tcp"
  service_address = ":57000"
 ### embedded_tags = ["Cisco-IOS-XR-mpls-lsd-oper:mpls-lsd/label-summary/owner-count/application-name"]
  [inputs.cisco_telemetry_mdt.tags]
    type = "TELEMETRY"
```

### Logs from Telegraf

```text
2022-10-27T17:57:57Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
2022-10-27T17:57:58Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
2022-10-27T17:58:21Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
2022-10-27T17:58:21Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
2022-10-27T17:58:28Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
2022-10-27T17:58:28Z E! [inputs.cisco_telemetry_mdt] Error in plugin: failed to decode: string field contains invalid UTF-8
```

### System info

Docker version 18.09.1

### Steps to reproduce

1. Add this config to telegraf
2. Restart container
3.
...
 

### Expected behavior

See the container run correctly and see the tag to filter in KIbana.

### Actual behavior

Show this logs and i cant see the metrics with this tag in kibana.

**Comment by powersj** [comment]
Hi,

It would be helpful to know what is in that field and telegraf thinks is not valid UTF-8. Can you collect that string via the CLI and pipe it to `od` so we can get a full idea of what characters are there?

Thanks

**Comment by bautistamad** [comment]
The error happens when I add the first field "transport" and if I can do it, one question, what is "od"?

**Comment by powersj** [comment]
od is a cli tool to dump a file or input into hex/octal. I wanted to see what the string is made up of.

**Comment by bautistamad** [comment]
[[inputs.cisco_telemetry_mdt]]
  transport = "tcp"
  service_address = ":57000"
  embedded_tags = ["Cisco-IOS-XR-mpls-lsd-oper:mpls-lsd/label-summary/owner-count/application-name"]
  [inputs.cisco_telemetry_mdt.tags]
    type = "TELEMETRY"

Od result in octal format:
0000000 133 133 151 156 160 165 164 163 056 143 151 163 143 157 137 164
0000020 145 154 145 155 145 164 162 171 137 155 144 164 135 135 012 040
0000040 040 164 162 141 156 163 160 157 162 164 040 075 040 042 164 143
0000060 160 042 012 040 040 163 145 162 166 151 143 145 137 141 144 144
0000100 162 145 163 163 040 075 040 042 072 065 067 060 060 060 042 012
0000120 040 040 145 155 142 145 144 144 145 144 137 164 141 147 163 040
0000140 075 040 133 042 103 151 163 143 157 055 111 117 123 055 130 122
0000160 055 155 160 154 163 055 154 163 144 055 157 160 145 162 072 155
0000200 160 154 163 055 154 163 144 057 154 141 142 145 154 055 163 165
0000220 155 155 141 162 171 057 157 167 156 145 162 055 143 157 165 156
0000240 164 057 141 160 160 154 151 143 141 164 151 157 156 055 156 141
0000260 155 145 042 135 012 040 040 133 151 156 160 165 164 163 056 143
0000300 151 163 143 157 137 164 145 154 145 155 145 164 162 171 137 155
0000320 144 164 056 164 141 147 163 135 012 040 040 040 040 164 171 160
0000340 145 040 075 040 042 124 105 114 105 115 105 124 122 131 042 012
0000360

**Comment by powersj** [comment]
Sorry, it seems I wasn't clear. You are getting an error from Cisco saying the following:

> string field contains invalid UTF-8

This indicates that a field from the device itself is not returning UTF-8 data. As such Telegraf stops attempting to unmarshal or decide the device. Can you get output from the Cisco device and show what the various fields are reporting? If everything looked good, then I was hoping you would run that output through od to see what shows up.

**Comment by bautistamad** [comment]
Ok i'll  try to get that information and then i'll post behind.
