### ISSUE TITLE
cisco_telemetry_mdt: IOS XE Nested lists overwriting data

### ISSUE THREAD

**Issue by brightonli** [influxdata/telegraf#12114]
### Relevant telegraf.conf

```toml
[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  ## Address and port to host telemetry listener
  service_address = "<ip address>:57001"
  embedded_tags = ["Cisco-IOS-XE-bgp-oper:bgp_state_data/bgp_route_vrfs/bgp_route_vrf/afi_safi"]

[[outputs.file]]
  files = ["<path>"]
  data_format = "json"
```

### Logs from Telegraf

```text
2022-10-27T03:23:42Z I! Starting Telegraf 1.24.2-43cafc00
2022-10-27T03:23:42Z I! Available plugins: 205 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-10-27T03:23:42Z I! Loaded inputs: cisco_telemetry_mdt
2022-10-27T03:23:42Z I! Loaded aggregators: 
2022-10-27T03:23:42Z I! Loaded processors: 
2022-10-27T03:23:42Z I! Loaded outputs: file influxdb_v2
2022-10-27T03:23:42Z I! Tags enabled: host=ultraconfig
2022-10-27T03:23:42Z I! [agent] Config: Interval:15s, Quiet:false, Hostname:"ultraconfig", Flush Interval:15s
2022-10-27T03:23:42Z D! [agent] Initializing plugins
2022-10-27T03:23:42Z D! [agent] Connecting outputs
2022-10-27T03:23:42Z D! [agent] Attempting connection to [outputs.file]
2022-10-27T03:23:42Z D! [agent] Successfully connected to outputs.file
2022-10-27T03:23:42Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2022-10-27T03:23:42Z D! [agent] Successfully connected to outputs.influxdb_v2
2022-10-27T03:23:42Z D! [agent] Starting service inputs
2022-10-27T03:23:43Z D! [inputs.cisco_telemetry_mdt] Accepted Cisco MDT GRPC dialout connection from 10.210.129.101:55699
2022-10-27T03:23:43Z D! [inputs.cisco_telemetry_mdt] No measurement alias for encoding path: Cisco-IOS-XE-bgp-oper:bgp-state-data
2022-10-27T03:23:57Z D! [outputs.file] Wrote batch of 16 metrics in 2.0055ms
2022-10-27T03:23:57Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:23:58Z D! [outputs.influxdb_v2] Wrote batch of 16 metrics in 21.0173ms
2022-10-27T03:23:58Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:12Z D! [outputs.file] Wrote batch of 8 metrics in 5.1155ms
2022-10-27T03:24:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:12Z D! [outputs.influxdb_v2] Wrote batch of 8 metrics in 10.0794ms
2022-10-27T03:24:12Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:27Z D! [outputs.file] Wrote batch of 16 metrics in 976.7µs
2022-10-27T03:24:27Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:27Z D! [outputs.influxdb_v2] Wrote batch of 16 metrics in 4.9853ms
2022-10-27T03:24:27Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:42Z D! [outputs.file] Wrote batch of 8 metrics in 0s
2022-10-27T03:24:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:42Z D! [outputs.influxdb_v2] Wrote batch of 8 metrics in 6.0019ms
2022-10-27T03:24:42Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:57Z D! [outputs.file] Wrote batch of 16 metrics in 994.9µs
2022-10-27T03:24:57Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:24:57Z D! [outputs.influxdb_v2] Wrote batch of 16 metrics in 6.9933ms
2022-10-27T03:24:57Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:25:02Z D! [agent] Stopping service inputs
2022-10-27T03:25:02Z D! [agent] Input channel closed
2022-10-27T03:25:02Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-10-27T03:25:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:25:02Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-10-27T03:25:02Z I! [agent] Stopping running outputs
2022-10-27T03:25:02Z E! [inputs.cisco_telemetry_mdt] Error in plugin: GRPC dialout receive error: rpc error: code = Canceled desc = context canceled
2022-10-27T03:25:02Z D! [inputs.cisco_telemetry_mdt] Closed Cisco MDT GRPC dialout connection from 10.210.129.101:55699
2022-10-27T03:25:02Z D! [agent] Stopped Successfully
```

### System info

Telegraf release-1.24, Windows Server 2016 Standard, Cisco IOS XE Version 17.06.03

### Steps to reproduce

1.Configure IOS-XE device (in my case Catalyst 9300)
2. Configure Telegraf input plugin
3. Check data within InfluxDB/ outfiled .json

### Expected behavior

If we were to use the following path as an example:

```
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp-route-vrfs/_bgp-route-vrf_/bgp-route-afs/_bgp-route-af_/afi-safi
```

I have italicized the lists in the yang model above for convenience.

If for example there were 4 elements in bgp-route-vrf (key:vrf), and 18 in bgp_route_af (key:afi_safi), I would assume that there would be 4*18=72 different metrics/combinations of **afi_safi** and **vrf**. 

### Actual behavior

I am however, only getting 4 metrics. 

I believe this is because the cisco device is sending separate payloads for each element in the first list (4). And therefore in the **cisco_telemetry_mdt** input plugin, for each payload it is creating a new `metric.NewSeriesGrouper()`, which has a variable `metrics:  make(map[uint64]telegraf.Metric)`  whose key is `groupID(g.hashSeed, metric.Name(), metric.TagList(), metric.Time())`. So for each of the 18 elements in the nested list, they will all have the same key and therefore will overwrite the existing data in the map instead of placing a new key:value pair, giving me only **vpnv6-flowspec** for the **afi_safi** value, when I should be getting others such as **ipv4-unicast** etc

Then if we were to go further down the yang model, I would assume there would be multiple bgp_neighbor_route_entries as well, which is not the case.

I have attempted to try using the embeddedTags parameter in the plugin config, but could not get it working. I also can't seem to see how it would help, however I do not have any golang experience and could have misunderstood the code.

### Additional info

I have attached a json of what the yang model should be producing (obtained via rest-conf), as well as the telegraf output json

[telegraf-outputs.zip](https://github.com/influxdata/telegraf/files/9883391/telegraf-outputs.zip)

**Comment by powersj** [comment]
Hi,

> I have italicized the lists in the yang model above for convenience.

I have near zero experience with this plugin, but looking at [the extra tags logic](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go#L600-L606) it includes the subfield name in each of these keys.

> I have attached a json of what the yang model should be producing (obtained via rest-conf), as well as the telegraf output json

Your attachment did not come through can you please also run with the following to output what metrics you collected to standard out please.

```
[[outputs.file]]
```

Thanks

**Comment by brightonli** [comment]
> Hi,
> 
> > I have italicized the lists in the yang model above for convenience.
> 
> I have near zero experience with this plugin, but looking at [the extra tags logic](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go#L600-L606) it includes the subfield name in each of these keys.

I believe I am not getting past the if statement in the [the extra tags logic](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go#L600-L606), as the `subfield.Name` is splitting text using '-', while the keys in from [extratags](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go#L572) are using '_'

> 
> > I have attached a json of what the yang model should be producing (obtained via rest-conf), as well as the telegraf output json
> 
> Your attachment did not come through can you please also run with the following to output what metrics you collected to standard out please.
> 
> ```
> [[outputs.file]]
> ```
> 

I have reuploaded the files. Hopefully should be good now

**Comment by powersj** [comment]
Can you also please attach what Telegraf produces with the `[[outputs.file]]`?

**Comment by brightonli** [comment]
> Can you also please attach what Telegraf produces with the `[[outputs.file]]`?

The output of the `[[outputs.file]]` is the telegraf-output.json in the attached zip folder above.

**Comment by powersj** [comment]
> The output of the [[outputs.file]] is the telegraf-output.json in the attached zip folder above.

Ah I was expecting line protocol, so when I saw JSON I wasn't sure what this was from

**Comment by powersj** [comment]
In 20-30mins there will be a build uploaded to #12139. That will have some additional debug output. Can you please get me the full logs from it?

**Comment by brightonli** [comment]
Here are all the related outputs after running the build.
I had the following embedded_tags in the config:
embedded_tags  = ["Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_vrfs/bgp_route_vrf/bgp_route_af/afi_safi, "Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_vrfs/bgp_route_af"]
[fix-12139-debug.zip](https://github.com/influxdata/telegraf/files/9914695/fix-12139-debug.zip)

**Comment by powersj** [comment]
Thank you!

It does look like there is the `_` vs `-` as you suggested and the code confirms this as well:

```
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
looking for extra tags: map[afi_safi:{}]
  subfield skipped: afi-safi
```

I've pushed another commit with a change to the comparison. That should be available in 20-30mins, could you give that another spin and see how much further you get this time?

Thanks again!

**Comment by brightonli** [comment]
I have attached the output of the new commit. It looks like it is upacking the different afi-safis for each vrf. But doesn't seem to contain any children data anymore.
[fix-12139-debug-2.zip](https://github.com/influxdata/telegraf/files/9947053/fix-12139-debug-2.zip)

**Comment by brightonli** [comment]
Hey @powersj .

Any update on this, or anything I can help with?

Regards,
Brighton

**Comment by brightonli** [comment]
Hey @powersj. Sorry about the wait. Had some issues with the VM I was working on.
Here is the data from the new commit
[fix-12139-debug-3.zip](https://github.com/influxdata/telegraf/files/10072151/fix-12139-debug-3.zip)

**Comment by powersj** [comment]
That looks like a step backwards from the first and second debug output :( I need to look at what this is trying to do in more detail.

Do you know if I can use the simulator to reproduce this? This would be much easier to understand and debug with that, rather than trying to do this back and forth and then try to pick this up each week.

**Comment by brightonli** [comment]
Hey.

I tried to see if you can do telemetry in a network lab GNS3, but doesn't look like I can. I'll try and set something up for you so that you can remote to the telegraf device over the next few days.

**Comment by brightonli** [comment]
Hey @powersj,

I've setup a isolated lab for you to test on. I have emailed you at [powersj@fastmail.com](mailto:powersj@fastmail.com) with the details on how to connect. Let me know if you have any issues.

**Comment by powersj** [comment]
Thanks for direct access to the system.

> I would assume that there would be 4*18=72 different metrics/combinations of afi_safi and vrf.

For vrf I only see the following entries ever get collected, I assume these are the 5 (4?) you refer to?

* default
* Mgmt-vrf 
* TEST
* ITS_Z3 
* MSS

And for afi-saif I see these 19

* ipv4-flowspec
* ipv4-mdt
* ipv4-multicast
* ipv4-mvpn
* ipv4-unicast
* ipv6-flowspec
* ipv6-multicast
* ipv6-mvpn
* ipv6-unicast
* l2vpn-e-vpn
* l2vpn-vpls
* nsap-unicast
* rtfilter-unicast
* vpnv4-flowspec
* vpnv4-multicast
* vpnv4-unicast
* vpnv6-flowspec
* vpnv6-multicast
* vpnv6-unicast

My understanding is you were expecting different metrics for the combinations of vrf and afi-saif combinations? As-is, telegraf does appear that we get multiple vrf metrics. What is missing is all the various afi-saif values. The resulting metrics appear to show the value of afi-saif with whatever gets read last as you thought.

For example here is the `MSS` vrf processing:

```
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_vrfs
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_vrf
Cisco-IOS-XE-bgp-oper:bgp-state-data/vrf
name:"vrf"  string_value:"MSS": MSS
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_afs
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv4-multicast": vpnv4-multicast
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv4-unicast": vpnv4-unicast
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv6-unicast": vpnv6-unicast
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv6-multicast": vpnv6-multicast
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv4-flowspec": vpnv4-flowspec
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_af
Cisco-IOS-XE-bgp-oper:bgp-state-data/afi_safi
name:"afi-safi"  string_value:"vpnv6-flowspec": vpnv6-flowspec
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filters
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/route_filter
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_entries
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_neighbors
Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_peer_groups
########
PARSING GROUPER METRICS
---
Cisco-IOS-XE-bgp-oper:bgp-state-data
tags
  path = Cisco-IOS-XE-bgp-oper:bgp-state-data
  source = TU-QLD-CRK-L0-SW-CCR-TST-01
  subscription = 202
fields
  bgp_route_vrfs/bgp_route_vrf/vrf = MSS
  bgp_route_vrfs/bgp_route_vrf/bgp_route_af/afi_safi = vpnv6-flowspec
  bgp_route_vrfs/bgp_route_vrf/bgp_route_af/bgp_route_filter/route_filter = bgp-rf-all
2022-12-14 06:13:07.019 +1100 AEDT
```

We can see telegraf read all the various paths and collect the you expect, but a metric is only produced for the last set of values.

>I have attempted to try using the embeddedTags parameter in the plugin config, but could not get it working. I also can't seem to see how it would help, however I do not have any golang experience and could have misunderstood the code.

If you look at [this previous issue comment](https://github.com/influxdata/telegraf/issues/7093#issuecomment-593335423), there really is no way for Telegraf to know about all the various combinations of Cisco versions, models, etc. and know what should be a tag and what should not be. It does sound like you need to specify values with the `embedded_tags` option and I think the root cause of this entire bug is not getting these quite right.

I tried using:

```
"Cisco-IOS-XE-bgp-oper:bgp-state-data/bgp_route_vrfs/bgp_route_vrf/bgp_route_af/afi-safi",
```

And the number of metrics generated increased greatly as a number of new metrics with different afi-safi states showed up.

If you are having trouble figuring out which tag to include, my suggestion is to go back to the [YANG models](https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/1761) for your specific OS type and version and use [pyang](https://github.com/mbj4668/pyang) to explore what the path should be.

I am going to leave that final part to you as I have spent far too much time on this, but I do appreciate you sharing the system as it helped me better understand how this plugin works.

Do let me know if that embedded plugin is a better result and if you have greater success. Thanks

**Comment by powersj** [comment]
> However, the output is showing prefixes being copied into other afi_safi, when they should be empty.

looks like the debug logs I still have showed only unicast had prefix defined as you mentioned, when you add it as an embedded tag it should check if the value exists before adding it, rather than grabbing some default. If you omit it does it still show up as a field in every metric?

> Also, the metrics that are unpacked from the embedded tags do not include the vrf, as part of the metric itself. I can tell what vrf it is part of due to the order that the metrics are outputted, however, if outputting to a plugin

Right, I am assuming that this is because you have two elements in your path that need to be resolved. This does not seem like a use-case that was well tested let alone documented. I briefly also tried to add `bgp_route_vrfs/bgp_route_vrf/vrf` as a tag with no success and it sounds like you had the same issue.

Have you considered asking how to monitor these on the cisco forums? I am wondering if someone has had great success with a MDT and telegraf config over there with capturing these types of metrics?

**Comment by brightonli** [comment]
> looks like the debug logs I still have showed only unicast had prefix defined as you mentioned, when you add it as an embedded tag it should check if the value exists before adding it, rather than grabbing some default. If you omit it does it still show up as a field in every metric?

The problem is that if you then omit that prefix path in the embedded tags, it no longer shows all the prefixes and only shows the one. I believe what's happening when you include it as an embedded tags, is that the parent list (i.e. afi_safi) that dont have any of that specific field (i.e. prefixes) are getting the last value of that field from the previous element in the parent list and using that, as the `SeriesGrouper` object is not getting reset. Perhaps for these embedded metrics, the value has to be manually removed for the `metrics` mapping after each one is found?

 

> Have you considered asking how to monitor these on the cisco forums? I am wondering if someone has had great success with a MDT and telegraf config over there with capturing these types of metrics?

Haven't seen anyone talk about this problem with IOS-XE. Have used telemetry with IOS-XR and NX-OS with telegraf and have not had this issue occur for them. I have gotten in contact with the support team at Cisco and they are trying to see what the difference between the data sent from different OS are like. I have also tried with the no longer supported bigmuddy-network-telemetry-pipeline and did not have the problem there. Maybe there's a part of that code that could be integrated into Telegraf?

**Comment by powersj** [comment]
> I have also tried with the no longer supported bigmuddy-network-telemetry-pipeline and did not have the problem there. 

Oh this is interesting. Do you specify the metrics you want to collect similar to telegraf? I think my big hesitation is lack of access to this hardware.

> Maybe there's a part of that code that could be integrated into Telegraf?

I would be curious to hear if they found anything. Did you get any update from Cisco or others in the community?

**Comment by brightonli** [comment]
> Oh this is interesting. Do you specify the metrics you want to collect similar to telegraf? I think my big hesitation is lack of access to this hardware.

So all I had to configure for big muddy was the protocol (grpc), encapsulation (gpb) and port (57000). Everything configured on the switch side is exactly the same. I have attached the output previously retrieved from big muddy. You can see that when it locates a nested list it appends "PIPELINE_EDIT" to it which I assume means it it also performing some additional logic to properly unpack it. 

> I would be curious to hear if they found anything. Did you get any update from Cisco or others in the community?

The response I have gotten back from Cisco is below. And so following from what they said I tried to make the subscription directly to the list of interest, but kept getting back a runtime error on the switch, so I am waiting back for a response from them.

The splitting into different TelemetryField messages (data_gpbkv field in telemetry.proto<[https://github.com/CiscoDevNet/bigmuddy-network-telemetry-proto/blob/final/proto_archive/telemetry.proto>](https://urldefense.com/v3/__https:/github.com/CiscoDevNet/bigmuddy-network-telemetry-proto/blob/final/proto_archive/telemetry.proto*3E__;JQ!!ErjpxIHqbccHOw!nEziICrEPWEw1WjUh17duDTLbk7fG4rizkdBmS8wjG8X052N5EYX3hMR6plBZDpZ_3PGStH9cw$);) is done based on what path was subscribed to. Generally, each row in the list that was subscribed to will be its own TelemetryField, with all the keys to that row separated out. Any child lists below the path that was subscribed to will be embedded (including all entries) directly in the “Content” field of the parent row. If it is desired to see, for example, each entry in the bgp-route-af list as a separate TelemetryField, then the subscription should be made directly to that list rather than to the top-level node.
 
As for the splitting into top-level Telemetry messages, yes, that is currently being done based on the elements of the first list (although this can vary depending on the source of the data – in some cases all elements are packed into a single message). The NX-OS and IOS-XE does behave differently in this regard, and there have been some discussions, but as of now there is no work planned for this standardization.

**Comment by brightonli** [comment]
> It doesn't require you to specify any settings or paths for data to collect like with Telegraf?

I might be misunderstanding you, but on Telegraf, excluding the embedded tags (if you use them), there's no other path related settings you need to configure on Telegraf. The paths are all configured on the switch. And so whatever paths were configured on the switch side to work with Telegraf are the same as what is used for Big Muddy. Nothing additional was required

> This is saying to be more explicit with your list of subscriptions then and not to assume that parsing will go through and grab everything?

Yep that's what I assumed Cisco meant. But that caused the runtime error. Not too sure if it was the switch that couldn't handle it, or maybe Telegraf couldn't process it and hence terminated the connection.

**Comment by powersj** [comment]
> excluding the embedded tags (if you use them)

Right this is what I meant calling out specific things to tag as well. Is the output from Big Muddy something you can use with an `exec` plugin to pull in with telegraf directly?

**Comment by brightonli** [comment]
From what I see Big Muddy does a way to export/stream out the data via TCP (https://github.com/CiscoDevNet/bigmuddy-network-telemetry-pipeline/tree/final). I could potentially create a Python script which acts as a TCP client which returns the data via the `exec` plugin. Does this seem like a viable approach?

I also see that Telegraf has a `socket_listener`, but from what I see it also just acts as server. Is there any way for Telegraf to act as client and dial out a connection to Big Muddy?

**Comment by powersj** [comment]
Looking at that repo I see:

> Supported downstream consumers include Apache Kafka, [Influxdata TICK stack](https://docs.influxdata.com/), [prometheus](https://prometheus.io/), dedicated gRPC clients, as well as dump-to-file for diagnostics.

If you want to pull the data you could use Telegraf to scrape from a prometheus endpoint, use the kafka plugin to subscribe messages. This might be smoother experience than using an external script, but that could be an option. I didn't look hard enough to see what the TICK stack pipeline looked like.

**Comment by brightonli** [comment]
Hi sorry about taking so long to respond. Got sick, and then took a bit to setup.

So I have attempted to output from BigMuddy Telemetry Pipeline to Kafka and then use the Telegraf's Kafka plugin to subscribe/consume the messages. I believe the BigMuddy Telemetry Pipeline to Kafka part is working, as running `kafka-console-consumer.sh ` shows valid data (I have attached one example as Kafka_read). However, the data outputted on Telegraf's end doesn't look quite right.  I can see the fields in the json dump, but all the values seem to be 0 or empty. Not sure if I have potentially misconfigured the input plugin config, or if there's some other intermediary step required.  

[pipeline-kafka-telegraf.zip](https://github.com/influxdata/telegraf/files/10614085/pipeline-kafka-telegraf.zip)

**Comment by powersj** [comment]
>  data_format = "json"

You are going to have to tell telegraf more about the JSON and how to parse it given the complex structure of the JSON itself. The "json" parser is very simple and very good at reading flat data, and that is about it.

My suggestion is to use the json_v2 parser, and define the objects, fields, and tags you need.
