### ISSUE TITLE
Docker image for telegraf 1.25

### ISSUE THREAD

**Issue by inselbuch** [influxdata/telegraf#12125]
### Use Case

would like to use new plugin that requires version 1.25

### Expected behavior

published on dockerhub.com telegraf version 1.25

### Actual behavior

not published

### Additional info

please

**Comment by powersj** [comment]
Hi,

The next minor release, 1.25 is scheduled for December. For now you can use the [nightly docker image](https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md) if you want to try new plugins.
