### ISSUE TITLE
inputs.gnmi doesnt support double_val for gnmi v0.8.0

### ISSUE THREAD

**Issue by richursa** [influxdata/telegraf#12137]
### Relevant telegraf.conf

```toml
# gNMI telemetry input plugin
[[inputs.gnmi]]
 ## Address and port of the gNMI GRPC server
```

### Logs from Telegraf

```text
2022-09-02T16:19:36Z I! [inputs.gnmi] Discarded empty or legacy type value with path: "/interfaces/interface/ethernet/poe/state/power-used"
```

### System info

Telegraf 1.24.0

### Steps to reproduce

1. Let telegraf do a gnmi subscription on Routers that support double_val eg Cisco IOS XE 17.10 
2. Observe logs to see error `docker logs -f  telegraf`
...

### Expected behavior

double_val should be correctly parsed by telegraf. 

### Actual behavior

telegraf doesnt support double_val and throws and error.

**Comment by reimda** [comment]
Hi @richursa thanks for the issue and the PR to fix it. I see it's marked draft. Whenever you're ready for review, mark it as a normal PR and we'll take a look.

**Comment by richursa** [comment]
Hi @reimda thanks for looking into this. I have marked it ready for review.
