### ISSUE TITLE
Error parsing opcua_listener

### ISSUE THREAD

**Issue by Skr3ms** [influxdata/telegraf#12136]
### Please direct all support questsions to slack or the forums. Thank you.

Hey together,

i want to use the plugin but when i try to start telegraf i got this error message.
`error running agent: Error loading config file telegraf_opc.conf: error parsing opcua_listener, Undefined but requested input: opcua_listener`
Does anybody know how to implement opcua_listener correctly?

Best greetings
Alex

**Comment by MyaLongmire** [comment]
`opcua_listener` is only available on master and in nightly builds currently, as it is a new feature. It will be in the package release of v1.25.0
