### ISSUE TITLE
Make n_users (System Input Plugin) configurable

### ISSUE THREAD

**Issue by dmgeurts** [influxdata/telegraf#12144]
### Use Case

Currently, the n_users number represents the active terminals, but this may not be equal to the number of users. For example a user running terminal management like screen or byobu will be a single user, but each terminal they have open will be reported as a user by `[[inputs.system]]`

### Expected behavior

It would be great to be able to configure if one would like to count actual logged in users, or open terminals (pts sessions).

I guess this could possibly be done by adding the option to ignore `tmux` pts sessions?

### Actual behavior

The user count includes all virtual terminals a user may have open, and thus Telegraf reports the same number of users for a system with 7 distinct users logged in and a single user logged in once, but with 6 virtual terminals open.

**Comment by powersj** [comment]
The `system` plugin gets the value for `n_users` via a call to [gopsutil](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/system.go#L50-L52). Looking at [gopsutil's Users()](https://github.com/shirou/gopsutil/blob/master/host/host.go#L130-L132) it calls a couple different functions depending on the platform. In general, it appears to return a slice of [UserStat](https://github.com/shirou/gopsutil/blob/50f22507f515f3101b72e643bf1282a4fdc173b3/host/host.go#L34) structs, where the user defined is one of them.

I have put up #12147 that would add an `n_unique_users` value. Can you give that a shot and verify it returns the correct value?

**Comment by dmgeurts** [comment]
This is working great, thank you!
