### ISSUE TITLE
Add s390x rpm packages to influxdata repository

### ISSUE THREAD

**Issue by ake5** [influxdata/telegraf#12146]
### Use Case

To use telegraf rpm packages we need them in the official influxdata rhel repository. On github these packages are already available for separate download.

### Expected behavior

telegraf rpm s390x packages are also avaible at https://repos.influxdata.com/rhel

### Actual behavior

Only arm, i386 and amd64 rpm packages are avaible

**Comment by powersj** [comment]
I have an internal PR up to add s390x, ppc64[el|le], and riscv64 to the deb and rpm repos. I'm waiting on a review + some testing. Will let you know once it is merged and packages are available.

**Comment by ake5** [comment]
hi, any news on this?

**Comment by powersj** [comment]
Hi - I have pinged the folks internally again, will get back to you shortly

**Comment by powersj** [comment]
@ake5 my PR was landed and the repos updated. Looking at the [stable repo](http://repos.influxdata.com/stable/) I now see folders for x390x, riscv64, and ppc64le for the RPM packages!

Can you confirm and let me know!

**Comment by ake5** [comment]
Yes, its working. Thank you very much !
