### ISSUE TITLE
Linter findings for using deprecated fields from gnmi library

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12151]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

`golangci-lint` doesn't find any problems with using deprecated fields from `gnmi` library.

### Actual behavior

`golangci-lint` found following problems which should be addressed:
```
plugins/inputs/gnmi/gnmi.go:699:19   staticcheck  SA1019: val.DecimalVal is deprecated: Do not use. 
plugins/inputs/gnmi/gnmi.go:701:11   staticcheck  SA1019: val.FloatVal is deprecated: Do not use. 
```

### Additional info

Introduced during bumping `gnmi` lib in this PR: https://github.com/influxdata/telegraf/pull/12140
Unfortunately `golangci-lint` (PR check) didn't find any problem because it checks only lines which are changed in PR.

**Comment by zak-pawel** [comment]
@richursa Will you have some time to address these issues?

**Comment by richursa** [comment]
Hi @zak-pawel, there are still routers which use older gnmi spec, that will need those depreciated fields in plugin to parse data properly for.

The depreciated fields have been kept to maintain backward compatibility with older gnmi specs.
