### ISSUE TITLE
Drop Metrics if field value greater than

### ISSUE THREAD

**Issue by dennisbleul** [influxdata/telegraf#12159]
### Please direct all support questsions to slack or the forums. Thank you.

Hello all,

I would like to discard all metrics when a field value is greater than.

Anybody have an idea how I can solve this?

Greetings from Switzerland
Dennis

**Comment by srebhan** [comment]
@dennisbleul currently there is no good solution to "discard all". The closest you can get is to set a `tag` dependent on you field value e.g. with the starlark processor and the use `tagdrop`...

**Comment by dennisbleul** [comment]
Thank you for your answer. 

I think this will solve my problem.
