### ISSUE TITLE
Replica and Sentinel stats are not gathered in redis_sentinel input plugin

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12152]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

N/A

### Steps to reproduce

N/A

### Expected behavior

Replica and Sentinel stats are gathered in `redis_sentinel` input plugin

### Actual behavior

Replica and Sentinel stats are not gathered in `redis_sentinel` input plugin.

`gatherMasterStats` always returns empty `masterNames`.
![image](https://user-images.githubusercontent.com/17336997/199634086-0467e855-d60b-4a5f-8813-7caf50c87b6c.png)

Thus, `gatherReplicaStats` and `gatherSentinelStats` will never be called.
![image](https://user-images.githubusercontent.com/17336997/199634255-26996749-0756-48fd-a0dc-2e69dca99daf.png)

Introduced in this PR https://github.com/influxdata/telegraf/pull/10042 and I believe it wasn't intended.

@spideyfusion What do you think?

**Comment by spideyfusion** [comment]
@zak-pawel You're totally right. As we iterate over the Sentinel masters, we never append any of them to the returned list. 😅 

I'll get it fixed ASAP and improve test coverage.

**Comment by 135zyf** [comment]
When is the problem expected to be fixed? Recently, I plan to upgrade the Telegraf version we use in batches to better monitor Redis.

**Comment by spideyfusion** [comment]
@135zyf I'll be tackling this issue tomorrow.

**Comment by 135zyf** [comment]
Thank you very much！
