### ISSUE TITLE
Telegraf installation on Windows does not work if statsd is part of the telegraf configuration.

### ISSUE THREAD

**Issue by mritunjaykumar** [influxdata/telegraf#1216]
I am using 0.12 version for InfluxDB and 0.13 version of Telegraf.

Following are the steps that I took to get Telegraf running on my windows 7 desktop:

1. Installed Telegraf from https://github.com/influxdata/telegraf#windows-binaries-experimental
	- downloaded https://dl.influxdata.com/telegraf/releases/telegraf-0.13.0_windows_amd64.zip
	- extracted that zip into folder C:\telegraf

2. Changed directory to "C:\telegraf\telegraf-0.13.0-1"
3. Ran command:
		telegraf -sample-config -input-filter cpu:mem -output-filter influxdb > telegraf.conf
	
4. I added following block of text as statsd config to the telegraf.conf file:	
		# Statsd Server
		[[inputs.statsd]]
		## Address and port to host UDP listener on
		service_address = "172.21.37.102:8125"
		## Delete gauges every interval (default=false)
		delete_gauges = false
		## Delete counters every interval (default=false)
		delete_counters = false
		## Delete sets every interval (default=false)
		delete_sets = false
		## Delete timings & histograms every interval (default=true)
		delete_timings = true
		## Percentiles to calculate for timing & histogram stats
		percentiles = [90]

		## separator to use between elements of a statsd metric
		metric_separator = "_"

		## Parses tags in the datadog statsd format
		## http://docs.datadoghq.com/guides/dogstatsd/
		parse_data_dog_tags = false

		# Statsd data translation templates, more info can be read here:
		# https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite
		 templates = [
			 "cpu.* measurement*"
		 ]

		## Number of UDP messages allowed to queue up, once filled,
		## the statsd server will start dropping packets
		allowed_pending_messages = 10000

		## Number of timing/histogram values to track per-measurement in the
		## calculation of percentiles. Raising this limit increases the accuracy
		## of percentiles but also increases the memory usage and cpu time.
		percentile_limit = 1000

5. Ran following command:
		telegraf -config telegraf.conf -input-filter cpu:mem -output-filter influxdb
		
It has worked for CPU and Memory as I can query InfluxDB using "influx" console and find out some records when I filter on the host.

6. Stop telegraf.
7. Run telegraf again with following command:
		telegraf -config telegraf.conf

	Expected:
		No error, and it should start sending CPU, MEM, and statsd data to the influxdb.

	Actual:
		C:\telegraf\telegraf-0.13.0-1>telegraf -config telegraf.conf
		2016/05/17 16:31:25 Starting Telegraf (version 0.13.0)
		2016/05/17 16:31:25 Loaded outputs: influxdb
		2016/05/17 16:31:25 Loaded inputs: cpu mem statsd
		2016/05/17 16:31:25 Tags enabled: host=MW00979991
		2016/05/17 16:31:25 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"MW00979991", Flush Interval:10s
		2016/05/17 16:31:25 Started the statsd service on 172.21.37.102:8125
		2016/05/17 16:31:25 **ERROR: ListenUDP - listen udp 172.21.37.102:8125: bind: The requested address is not valid in its context.**

**Comment by sparrc** [comment]
you cannot choose any IP address you wish, it needs to be the public IP address of your server, or `localhost`. See http://stackoverflow.com/questions/4146885/socket-bind-returns-the-requested-address-is-not-valid-in-its-context-on-wi
