### ISSUE TITLE
improve inputs.modbus device name configuration 

### ISSUE THREAD

**Issue by logmod** [influxdata/telegraf#12178]
### Use Case

I would like to have the option to get rid of the amgibious "name" tag that is hardcoded into the plugin when using a request style configuration.

When using the register style config it makes sense to set the name of the device as it is defined by a unique slave id. When using the  request style configuration multiple slave ids can be requested and here the only useful interpretation for the name configuration is the modbus gateway itself as there may be multiple slave devices in the request.

### Expected behavior

Allow to omit the name tag (i.e. not creating the tag at all) in the request style config section as any number of custom tags can be added here anyway.

` [inputs.modbus.request.tags] `
`omit_name = true `

Related request:  Please clarify the configuration example that this tag may describe the modbus communication interface and not specific slave devices in case of a request style configuration.

### Actual behavior

- The [[inputs.modbus]] section requires a `name ="Device"` configuration, otherwise the plugin will fail to start.  
- Repeating the name directive in the  `[[inputs.modbus.request]]` section is ignored.
- The name tag is hardcoded and cannot be changed.
- The name tag has a potentially ambigious meaning in relation to the "name" directive used to name the modbus measurement fields (I think that this tag should rather have been called "device").

**Comment by powersj** [comment]
> Allow to omit the name tag

This already exists, via [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) with the `tagexclude` option:

```
tagexclude = ["name"]
```

**Comment by logmod** [comment]
Thank you, I was not aware of metric filtering. Problem solved. Can I create a pull request to amend the sample configuration regarding the use of the name tag?

**Comment by powersj** [comment]
> Can I create a pull request to amend the sample configuration regarding the use of the name tag?

Please do!

**Comment by srebhan** [comment]
Closing this issue as you can do what you want using `tagexclude`
