### ISSUE TITLE
SNMP - Problem using tables with mapping and subtables.

### ISSUE THREAD

**Issue by joelsdc** [influxdata/telegraf#1217]
Hi, 

I'm facing a very strange scenario.

I'm gathering interface information from a Juniper SRX filtering by subtables and using mappings (to have the instance reflect the interface name instead of the interface id)

Example config:

```
[[inputs.snmp.host]]
address = "XXXXXXX:161"
community = "public"
version = 2
timeout = 2.0
retries = 2
[[inputs.snmp.host.table]]
  name = "iftable" 

[[inputs.snmp.table]]
name = "iftable"
# ifName
mapping_table = ".1.3.6.1.2.1.31.1.1.1.1"
sub_tables=["If_bytes_recv", "If_bytes_send", "Juniper_If_Discards_IN", "Juniper_If_Errors_IN", "Juniper_If_Errors_OUTS"]

[[inputs.snmp.subtable]]
name = "If_bytes_recv"
# ifHCInOctets
oid = ".1.3.6.1.2.1.31.1.1.1.6"
unit = "octets"

[[inputs.snmp.subtable]]
name = "If_bytes_send"
# ifHCOutOctets
oid = ".1.3.6.1.2.1.31.1.1.1.10"
unit = "octets"

[[inputs.snmp.subtable]]
name = "Juniper_If_Discards_IN"
# ifJnxInDiscards
oid = ".1.3.6.1.4.1.2636.3.3.1.1.14"

[[inputs.snmp.subtable]]
name = "Juniper_If_Errors_IN"
# ifJnxInErrors
oid = ".1.3.6.1.4.1.2636.3.3.1.1.9"

[[inputs.snmp.subtable]]
name = "Juniper_If_Errors_OUTS"
# ifJnxOutErrors
oid = ".1.3.6.1.4.1.2636.3.3.1.1.24"
```

This works as expected, and gives the following output:

```
[...]
> ifHCInOctets,instance=reth0.1001,snmp_host=XXXXXXX,unit=octets ifHCInOctets=26687618662338i 1463527886548303996
> ifHCOutOctets,instance=reth0.1001,snmp_host=XXXXXXX,unit=octets ifHCOutOctets=23986442727419i 1463527888165133855
> ifJnxInDiscards,instance=reth0.1001,snmp_host=XXXXXXX ifJnxInDiscards=0i 1463527887327576478
> ifJnxInErrors,instance=reth0.1001,snmp_host=XXXXXXX ifJnxInErrors=0i 1463527888043361220
> ifJnxOutErrors,instance=reth0.1001,snmp_host=XXXXXXX ifJnxOutErrors=0i 1463527888479930803
[...]
```

Without the mapping, the instance would reflect the equivalent interface id number.

I'm trying to do something similar, (table with subtables and mappings) but gathering information from a Radware Alteon load-balancer.

Example config:

```
[[inputs.snmp.host]]
address = "XXXXXXX:161"
community = "public"
version = 2
timeout = 2.0
retries = 2
[[inputs.snmp.host.table]]
  name = "Alteon_VIPs"

[[inputs.snmp.table]]
name = "Alteon_VIPs"
# slbStatVServerEntry
oid = ".1.3.6.1.4.1.1872.2.5.4.2.4.1"
# slbStatVServerIpAddress
mapping_table = ".1.3.6.1.4.1.1872.2.5.4.2.4.1.14"
sub_tables=["Alteon_VIP_traffic", "Alteon_VIP_sessions"]

[[inputs.snmp.subtable]]
name = "Alteon_VIP_sessions"
# slbStatVServerCurrSessions
oid = ".1.3.6.1.4.1.1872.2.5.4.2.4.1.2"

[[inputs.snmp.subtable]]
name = "Alteon_VIP_traffic"
# slbStatVServerHCOctets
oid = ".1.3.6.1.4.1.1872.2.5.4.2.4.1.13"
unit = "octets"
```

I'm getting this error instead of the expected output:

```
* Plugin: snmp, Collection 1
2016/05/17 16:36:32 SNMP Error for host 'XXXXXXX:161': Unable to decode packet: nil
```

The strange thing is, depending on the combination of settings you get different results:
1. Remove the mapping_table, keep the sub_tables: it works perfect and output is as expected (but the instance= obviously has no name mapping)
2. Keep the mapping_table, remove the sub_tables: it works perfect and output is as expected (instance= has correct mapping, but as no sub_tables are specified we get all the subtables)
3. Keep the mapping_table, and sub_tables with only 1 sub_table name: it works as expected (instance= has correct mapping, and only the sub_table specified is shown)

In the 3rd scenario, I would like to add more than one subtable (like with the interfaces with the Juniper). 

I doubt its a SNMP or device problem, as I can -
- not filter at all -> works
- filter by 1 subtable -> works 
- filter by the other subtable -> works
- but if I filter by both subtables, then I get the above error msg

Any idea on what can cause this issue?

I can provide any information you require as I have spent quite some time debugging this.

Thank you!

**Comment by sparrc** [comment]
cc @titilambert

**Comment by danielnelson** [comment]
@joelsdc Sorry that we were unable to solve this for you, if it is still an issue for you then you could try using the newer snmp plugin, which has been rewritten since this issue was submitted.
