### ISSUE TITLE
support different retention policy bases on different input plugin

### ISSUE THREAD

**Issue by jsvisa** [influxdata/telegraf#1218]
I want to collect different metrics with the differ retention policies, by now seems I have to start two telegraf client, If telegraf support configing retentions policy based on plugin, not a global one,  then I can handle it in one client.

**Comment by sparrc** [comment]
you can do this be specifying multiple influxdb outputs within the same config file, and using metric filtering. https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#output-configuration
