### ISSUE TITLE
Reduce the number of methods in inputs.procstat's Process interface

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#12206]
related #12174 

Process has >15 methods taken directly from gopsutil that read data into structs. The plugin itself only calls the methods one after another in its Gather method. The mock interface probably should have only one method that returns everything Gather needs. In other words it's mocked at the wrong level for testing.

We'd like to reduce the number of methods in Process so we can run the interfacebloat linter without having to add //nolint

**Comment by powersj** [comment]
next steps: look at what is required to reduce interface
