### ISSUE TITLE
Reduce the number of methods in the metric interface

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#12207]
related #12174

Metric has a bunch of "deprecated" methods that nobody ever got rid of, and it mixes a few concepts (building a metric, using a metric, and tracking a metric) in one interface. It would be cleaner if there were multiple separate smaller interfaces for each concept.

We'd like to reduce the number of methods in Metric so we can run the interfacebloat linter without having to add //nolint.

**Comment by powersj** [comment]
next steps: look at what is required to reduce interface

**Comment by abhi-jha** [comment]
Hi. Is this something being worked on or can I take it up? I am ready to take up tasks.

**Comment by powersj** [comment]
> Hi. Is this something being worked on or can I take it up? I am ready to take up tasks.

If a bug is not assigned to someone and you don't see an existing PR, feel free to work on it!

**Comment by abhi-jha** [comment]
What do I need to do to get it assigned to me?

**Comment by powersj** [comment]
> What do I need to do to get it assigned to me?

done
