### ISSUE TITLE
inputs.modbus: Read register span in one go and drop unused fields

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#12222]
### Use Case

We currently only need a (big) subset from one of our edge devices, but this results in Telegraf sending about 200 read requests which takes about 4 seconds. The subsets are not completely contiguous in the address space, but the gaps in between the blocks are only about 1-4 registers. If we manually fill these gaps with "Spare" fields the performance increase significantly to 150ms.

We then manually drop the `Spare*` fields.

### Expected behavior

Telegraf sends one big read request for the entire configured register span and drops the unused fields.

### Actual behavior

Separate read requests are sent for every contiguous register block, which slows down performance a lot.

**Comment by srebhan** [comment]
Do you use the `omit` flag to drop the unused registers? Like
```toml
[[inputs.modbus.request]]
    ## Holding example
    ## All of those examples will result in FLOAT64 field outputs
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    fields = [
      { address=0, name="voltage",      type="INT16",   scale=0.1   },
      { address=1, name="current",      type="INT32",   scale=0.001 },
      { address=3, name="",        type="UINT32",  omit=true   },
      { address=5, name="",        type="UINT32",  omit=true   },
      { address=7, name="energy",       type="FLOAT32", scale=0.001, measurement="W" },
      { address=9, name="frequency",    type="UINT32",  scale=0.1   },
      { address=8, name="power_factor", type="INT64",   scale=0.01  },
    ]
```

**Comment by LarsStegman** [comment]
Ah, we used `fielddrop`, but yes, something similar. We would like to have Telegraf automatically figure out how to optimize reading, as this would make the configuration file smaller.

**Comment by srebhan** [comment]
There is https://github.com/influxdata/telegraf/pull/11273 and #11106. Will try to accelerate those a bit if you promise to test them. ;-)

**Comment by LarsStegman** [comment]
Of course there already is a PR on this. It keeps amazing me how active this project is. Every time I think of something I can find an issue or a PR already working on it. I'll discuss with the team tomorrow if they want to test this. Thanks!
