### ISSUE TITLE
Enhance MQTT output plugin's routing capabilities

### ISSUE THREAD

**Issue by serroba** [influxdata/telegraf#12221]
### Use Case

The current plugin is very strict and opinionated on what is allow to be used as parts of the topic definition in MQTT.

This is what is currently possible to do: https://github.com/influxdata/telegraf/blob/af43d0183c4b4035d6f5cec20ff7e5683ef4149f/plugins/outputs/mqtt/sample.conf#L16

```
 ## MQTT Topic for Producer Messages
  ## MQTT outputs send metrics to this topic format:
  ## <topic_prefix>/<hostname>/<pluginname>/ (e.g. prefix/web01.example.com/mem)
  topic_prefix = "telegraf"
```

This feature request is about allowing to use a more dynamic expression of topics, taking into accounts `tags` as part of routing keys in MQTT.

### Expected behavior

When I enable MQTT as an output plugin, I would like to be allowed to use tags and potentially environment variables as part of the routing key

### Actual behavior

The current behaviour only allows to use a combination of a fixed `topic_prefix`, `hostname` which would end up being the container ID if no hostname has been defined in the global values and a suffix representing the input plugin.

### Additional info

This has initially being discussed on slack and we have discussed some possible ways to solve this:

https://influxcommunity.slack.com/archives/CH99HUH8V/p1666854669387089

Of particular/relevant interest:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1817347/201030324-4db818a7-085e-4148-82b9-cce2c4dc7c31.png">

We are evaluating in the next couple of weeks offer some PRs if this ideas seems reasonable to as starting point.

**Comment by powersj** [comment]
next steps: review #12224, thanks for the PR!
