### ISSUE TITLE
Need to convert Hex to IEEE-754 Float from files with tail

### ISSUE THREAD

**Issue by orypilant** [influxdata/telegraf#12234]
### Use Case

**I am using the tail plugin to read data from files. In these files I have Hexa data that I need to convert to IEEE-754 Float, and then I need to apply some math operations.**

My input file :

`2022-10-28 17:44:47 AAA01 BBB01 01 43 1E 00 CD 50 00 00 AB CD 2C 0F 00 00 00 00 01 01 01 00 01 00 01 01 01 00 02 00 0B 00 0B 02 00 00 00 1D 02 00 00 00 13 02 00 00 00 12 02 00 00 00 23 02 00 00 00 02 02 00 00 00 11 02 00 00 00 00 02 00 00 00 02 02 00 00 00 14 02 00 00 00 01 02 00 00 00 06 02 00 00 00 0C 02 00 00 00 05 02 00 00 00 04 02 C2 20 00 00 02 C0 C7 21 A9 02 C0 87 6B 9A 02 42 BE 45 E9 02 42 BE 45 E9 02 00 00 00 00 02 00 04 00 04 02 00 00 00 00 02 00 00 00 10 02 00 00 00 00 02 00 4F 00 4F 02 00 00 00 00 02 00 00 00 00 02 00 08 00 08 02 00 00 00 17 02 FF FF FF D8 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 05 02 05 02 6A E6`

`2022-10-28 17:44:48 AAA01 BBB01 01 43 24 00 CD 50 00 00 AB CD 2C 0F 00 00 00 00 01 01 01 00 01 00 01 01 01 00 02 00 0B 00 0B 02 00 00 00 1D 02 00 00 00 13 02 00 00 00 12 02 00 00 00 23 02 00 00 00 02 02 00 00 00 11 02 00 00 00 00 02 00 00 00 02 02 00 00 00 14 02 00 00 00 01 02 00 00 00 06 02 00 00 00 0C 02 00 00 00 05 02 00 00 00 04 02 C2 20 00 00 02 C0 C6 FB A4 02 C0 87 64 4A 02 42 BE 2B 19 02 42 BE 2B 19 02 00 00 00 00 02 00 04 00 04 02 00 00 00 00 02 00 00 00 10 02 00 00 00 00 02 00 4F 00 4F 02 00 00 00 00 02 00 00 00 00 02 00 08 00 08 02 00 00 00 17 02 FF FF FF D8 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 05 02 05 02 0C 91`

`2022-10-28 17:44:49 AAA01 BBB01 01 43 2A 00 CD 50 00 00 AB CD 2C 0F 00 00 00 00 01 01 01 00 01 00 01 01 01 00 02 00 0B 00 0B 02 00 00 00 1D 02 00 00 00 13 02 00 00 00 12 02 00 00 00 23 02 00 00 00 02 02 00 00 00 11 02 00 00 00 00 02 00 00 00 02 02 00 00 00 14 02 00 00 00 01 02 00 00 00 06 02 00 00 00 0C 02 00 00 00 05 02 00 00 00 04 02 C2 20 00 00 02 C0 C6 D2 FF 02 C0 87 5F 2F 02 42 BE 31 E6 02 42 BE 31 E6 02 00 00 00 00 02 00 04 00 04 02 00 00 00 00 02 00 00 00 10 02 00 00 00 00 02 00 4F 00 4F 02 00 00 00 00 02 00 00 00 00 02 00 08 00 08 02 00 00 00 17 02 FF FF FF D8 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 03 00 00 00 00 05 02 05 02 1C 99`

**I need to join a part of data to get 32 bits Hexa data:**   

 42 BE 45 E9 =>  42BE45E9

**After, i need to convert Hex data to IEEE-754 Float**

[https://www.h-schmidt.net/FloatConverter/IEEE754.html](url)

42BE45E9 => -6.22285890579  **This point is important; I need this feature.**

### Expected behavior

**For example :  ( Thanks to Sven Rebhan )**

```
[[inputs.tail]]
  files = ["test_configs/slack_oryble_modbus_from_file.bin"]
  name_override = "hexa2_log"
  from_beginning = true
  max_undelivered_lines = 10000
  character_encoding = "utf-8"
  data_format = "grok"
  grok_timezone = "Local"
  grok_patterns = ['%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02 15:04:05"}\s%{WORD:AAAinfo:tag} %{WORD:BBBinfo:tag} (?:\w+ ){107}%{HEX32:value} .*']
  grok_custom_patterns = '''
    HEX32 \b((?:[0-9A-Fa-f.]{2} ){3}[0-9A-Fa-f.]{2})\b
  '''

[[processors.parser]]
  namepass = ["hexa2_log"]
  parse_fields = ["value"]
  drop_original = true
  data_format = "binary"
  hex_encoding = true
  endianess = "be"

  [[processors.parser.binary]]
    entries = [{ name = "value",   type = "float32" }]
```
**and produce**

```
hexa2_log value=-6.222858905792236 1668426863387796678
hexa2_log value=-6.218217849731445 1668426863387918180
hexa2_log value=-6.213256359100342 1668426863388057782
```

### Actual behavior

This feature doesn't exict actualy.

I post on Slack a question to know how to do that and it's not possible actualy.

I need to make a request to get this feature.

[https://influxcommunity.slack.com/archives/CH99HUH8V/p1668022573174059](url)

**Comment by srebhan** [comment]
@orypilant can you please test the binary built in #12232 and let me know if this fixes your issue!?
