### ISSUE TITLE
Conntrack new added statistics not supported in latest version

### ISSUE THREAD

**Issue by BhumikaMatharu** [influxdata/telegraf#12256]
### Please direct all support questsions to slack or the forums. Thank you.

In this pull request https://github.com/influxdata/telegraf/pull/8958, additional conntrack tools were added to the input plugin but on checking the source code for the latest releases, I couldn't find this change.

Can you add this change in your next release or any idea in which release this change will be there?

**Comment by powersj** [comment]
That was merged last month as a feature which means it will be in our next minor release, v1.25.0, in December. For now you can use builds with these included, by using the nightly builds: https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md
