### ISSUE TITLE
telegraf 0.13 docker plugin problem: why do you consider "container_id" as value not key?

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#1225]
In telegraf 0.13, the container_id becomes a value not a key, which is different from telegraf 0.12. I have to do extra works to fit for that. Is there any strong reason to make the change?

**Comment by sparrc** [comment]
yes, see https://github.com/influxdata/telegraf/pull/1015#issuecomment-211090770 for reasoning
