### ISSUE TITLE
add capacity to reformat datas for mongodb output plugin 

### ISSUE THREAD

**Issue by nicho2** [influxdata/telegraf#12261]
### Use Case

Hello,
I have some datas with json nested fields , and i search to send it in mongodb in a json format 

 3ddlmlite_diag_devices,device_id=00:80:E1:0B:14:31,host=FRL17172,type=diagnostic F4CE36DBF3AA2794="{\"shortAddress\": \"0000\", \"status\": \"online\"}" 00047400001212AC="{\"shortAddress\": \"AB1A\", \"status\": \"online\"}" 0000004740000AEFC89="{\"status\": \"offline\"}" 1668696305161661200

is-it possible to have this keyword:

   data_format = "json"

	json_nested_fields_include = ["*"]

	json_transformation = '''$merge([fields, {"tags": tags, "timestamp": $fromMillis(timestamp*1000)}])'''

Thanks

### Expected behavior

have in mongo:

```
{
	"00047400001212AC": {
		"shortAddress": "AB1A",
		"status": "online"
	},
	"0004740000AEFC89": {
		"status": "offline"
	},
	"F4CE36DBF3AA2794": {
		"shortAddress": "0000",
		"status": "online"
	},
	"tags": {
		"device_id": "00:80:E1:0B:14:31",
		"host": "FRL17172",
		"type": "diagnostic"
	},
    "timestamp": {
        "$date": "2022-11-17T15:25:40.000Z"
    },
 "_id": {
        "$oid": "637652793f05dd8a1aa7f4b2"
    },
}
```

### Actual behavior

I have 

```
{
    "timestamp": {
        "$date": "2022-11-17T15:25:40.000Z"
    },
    "tags": {
        "device_id": "00:80:E1:0B:14:31",
        "host": "FRL17172",
        "type": "diagnostic"
    },
    "00047400001212AC": "{\"shortAddress\": \"AB1A\", \"status\": \"online\"}",
    "_id": {
        "$oid": "637652793f05dd8a1aa7f4b2"
    },
    "0004740000AEFC89": "{\"status\": \"offline\"}",
    "F4CE36DBF3AA2794": "{\"shortAddress\": \"0000\", \"status\": \"online\"}"
}
```

**Comment by powersj** [comment]
@srebhan can your recent change help in this case?

**Comment by nicho2** [comment]
Hello,
@srebhan's evolution have help me very very much (with mqtt) .
Now it's new request to can change format also in the mongodb output plugin.
Actually this plugin haven't this capacity

**Comment by srebhan** [comment]
@nicho2 looking at this feature-request a bit more I think it is not feasible to implement a custom mapping for MongoDB. Closing this as _won't fix_...
