### ISSUE TITLE
statsd service input overwriting host tag

### ISSUE THREAD

**Issue by robrankin** [influxdata/telegraf#1227]
Seems same as #1210 however thought I'd mention it separately.

Since upgrade to 0.13 statsd metrics are having their hostname overwritten by the system running the telegraf statsd service input.

Implemented the workaround (set the `omit_hostname`) option, but of course I've now lost the hostname for locally collected system metrics.

**Comment by sparrc** [comment]
it's the same problem, but thanks for opening anyways, I've got a PR ready to fix this #1228
