### ISSUE TITLE
Drop influxdb measurement (with tags) from telegraf from starlark plugin

### ISSUE THREAD

**Issue by maloy-ghosh** [influxdata/telegraf#12279]
### Use Case

- The underlying device streams add/del/update telemetry events.
- Currently I am collecting events via syslog and pushing dynamic metrics to influx via starlark plugin. 
- **When the underlying agent is reset, old data is of no use.**
- **We want to drop series from influx measurement for this particular agent on this trigger.**

### Expected behavior

Measurements matching tags would be deleted from influxdb.

### Actual behavior

Currently I did not find any support for deleting old measurement from influxdb.

**Comment by srebhan** [comment]
@maloy-ghosh maybe I didn't get your request, but are you expecting Telegraf to delete data from InfluxDB?

**Comment by maloy-ghosh** [comment]
> @maloy-ghosh maybe I didn't get your request, but are you expecting Telegraf to delete data from InfluxDB?

@srebhan Yes (Delete old data from a specific measurement for the specific agent )

I was going through some old issue reports (https://github.com/influxdata/telegraf/issues/4884#issuecomment-431292226), where it was mentioned that telegraf cannot delete data from influx, it can only add. 

Is it still the same?

**Comment by srebhan** [comment]
Yes. Telegraf is a **collection** agent! So deleting stuff on the output side will not happen. You can likely use [InfluxDB's tasks](https://docs.influxdata.com/influxdb/v2.5/process-data/) or retention policy.

Closing this issue as this is completely out-of-scope for Telegraf.
