### ISSUE TITLE
Plugins can replace global_tags

### ISSUE THREAD

**Issue by blockloop** [influxdata/telegraf#12300]
### Relevant telegraf.conf

```toml
# vi: ft=conf
[global_tags]
  host = "my-host"

[agent]
  interval = "3s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 50000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "my-host"
  omit_hostname = false

[[outputs.file]]
  files = ["stdout"]

# Statsd Server
[[inputs.statsd]]
  protocol = "udp"
  service_address = ":8125"
  datadog_extensions = true
```

### Logs from Telegraf

```text
$ telegraf --config telegraf.conf
2022-11-28T23:44:35Z I! Starting Telegraf 1.24.3
2022-11-28T23:44:35Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-11-28T23:44:35Z I! Loaded inputs: statsd
2022-11-28T23:44:35Z I! Loaded aggregators:
2022-11-28T23:44:35Z I! Loaded processors:
2022-11-28T23:44:35Z I! Loaded outputs: file
2022-11-28T23:44:35Z I! Tags enabled: host=my-host
2022-11-28T23:44:35Z I! [agent] Config: Interval:3s, Quiet:false, Hostname:"my-host", Flush Interval:1s
2022-11-28T23:44:35Z I! [inputs.statsd] UDP listening on "[::]:8125"
2022-11-28T23:44:35Z I! [inputs.statsd] Started the statsd service on ":8125"
http_requests,host=hello,metric_type=counter value=3i 1669679088000000000
```

### System info

Telegraf 1.24.2, Ubuntu

### Steps to reproduce

1. Set global_tags
2. run telegraf with any input that accepts tags
3. emit a metric with a global_tag set to something different
4. observe the tag from global tags is overridden
...

### Expected behavior

global_tags should be static and should take precedence over anything else If a plugin appends a conflicting tag it should be prepended with some marker to indicate that it was a conflict. Prometheus does this.

### Actual behavior

Plugins can replace arbitrary global_tags 

### Additional info

If you run telegraf with the config above and then use `nc` to push a metric it's easy to observe

```
echo "http.requests:1|c|#host:hello" | nc -u -w0 127.0.0.1 8125
```

The following workaround works, but it's gross

```
[[processors.rename]]
  order = 10
  [[processors.rename.replace]]
    tag = "host"
    dest = "remote_host"

  [processors.rename.tagdrop]
    host = ["<real hostname here>"]


[[processors.rename]]
  order = 20
  [[processors.rename.replace]]
    tag = "orig_host"
    dest = "host"
```

**Comment by powersj** [comment]
> global_tags should be static and should take precedence over anything else

The [configuration docs](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#global-tags) specifies the opposite: global tags are overridden by tags set by plugins.

> If a plugin appends a conflicting tag it should be prepended with some marker

This would have implications around cardinality for some outputs and is quite the change in behavior. While we could put this behind an option your existing workaround via the use of processors is a preferred solution.

**Comment by blockloop** [comment]
Ah, thank you. I missed that part of the doc. Is there a better way to force a single tag outside of the trick I used?

**Comment by powersj** [comment]
> Is there a way to tell an input to skip tags from the input?

Not at this time.

> If I use tagexclude on the input then it drops the tag entirely, even the original from [global_tags]

Right tagexclude is filtering that happens at the very end of a plugin.

**Comment by srebhan** [comment]
@blockloop a PR to configure the precedence would be welcome... :-)

**Comment by srebhan** [comment]
@blockloop and as a workaround, you could add an [override processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/override) to override the plugin tags with what you want instead of using global tags...
