### ISSUE TITLE
Allow Config Path/URL to be specified using environment variable

### ISSUE THREAD

**Issue by skotekar** [influxdata/telegraf#12311]
### Use Case

When running telegraf in a docker container or via docker compose file, we cannot specify the --config command line option.
For such cases it will be useful to read the config file path (mostly for URL based remote path) via an environment variable.

### Expected behavior

Allow remote config path/url to be specified via environment variable.

### Actual behavior

Remote config path/URL can be specified using environment variable.

We could still let the --config parameter override the environment variable setting.

**Comment by powersj** [comment]
if you run the telegraf binary by itself it will tell you where it looks for configs by default:

```
$TELEGRAF_CONFIG_PATH, /home/powersj/.telegraf/telegraf.conf, or /etc/telegraf/telegraf.conf
```

**Comment by skotekar** [comment]
Ohh, okay, I didn't know about the TELEGRAF_CONFIG_PATH environment variable.

I think that should work as long as I can specify a URL as its value. Will check soon.
