### ISSUE TITLE
useradd -K not supported on Suse Linux

### ISSUE THREAD

**Issue by kohlerm** [influxdata/telegraf#1232]
When installing the rpm package on SLES 11 SP2 (corrected) I get:

```
Installing: telegraf-0.13.0-1 [done]
Additional rpm output:
useradd: invalid option -- 'K'
Try `useradd --help' or `useradd --usage' for more information.
chown: invalid user: `telegraf:telegraf'
useradd: invalid option -- 'K'
Try `useradd --help' or `useradd --usage' for more information.
chown: invalid user: `telegraf:telegraf'
```

UPG is a debian feature and as such is not available on Suse. 
See discussion here

http://unix.stackexchange.com/questions/37194/why-is-the-default-umask-value-for-useradd-in-opensuse-set-to-022

This might be an issue for other non-debian Linux flavors as well.

**Comment by sparrc** [comment]
🙈  I had a feeling this might not work on some OSes, caused by @adithyabenny's fix for https://github.com/influxdata/telegraf/issues/1091

cc @rossmcdonald

**Comment by kohlerm** [comment]
I copied the /etc/init.d/telegraf file manually and it also does not work on SLES 11

more /var/log/telegraf/telegraf.log
start-stop-daemon: unrecognized option '--chuid'
Try `start-stop-daemon --help' for more information.
start-stop-daemon: unrecognized option '--chuid'
Try `start-stop-daemon --help' for more information.

I removed the option and it work,  running telegraf as user root.

**Comment by lanox** [comment]
@kohlerm  how did you get it to work ?
