### ISSUE TITLE
Is there a SVG logo of the Telegraf Tiger?

### ISSUE THREAD

**Issue by loganmarchione** [influxdata/telegraf#12327]
### Use Case

I'm looking for a SVG logo of the Telegraf Tiger to use in a network diagram. However, I only see a [PNG logo](https://github.com/influxdata/telegraf/blob/master/assets/TelegrafTiger.png), which doesn't scale well.

![](https://raw.githubusercontent.com/influxdata/telegraf/master/assets/TelegrafTiger.png)

I found [this page](https://influxdata.github.io/branding/visual/mascot/) on Influx's GitHub Pages site. Is this the "official" logo for Telegraf?

![](https://influxdata.github.io/branding/img/mascots/tiger.png)

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by powersj** [comment]
> I found [this page](https://influxdata.github.io/branding/visual/mascot/) on Influx's GitHub Pages site. Is this the "official" logo for Telegraf?

Yeah I believe that these are the new logos after the rebranding.

@sspaink do you have a svg of the older logo?
