### ISSUE TITLE
[inputs.sqlserver] sqlserver plugin waits indefinitely if sqlservers responds very slow  

### ISSUE THREAD

**Issue by goswamisandeep** [influxdata/telegraf#12321]
Lets say we have a  sqlserver which is very slow , and it responds to queries very slow . Current sqlserver plugin code does not have a timeout to cancel query execution .

In my setup we had a very slow sqlserver , it took almost 40 minutes for one iteration to get completed.

Relevent slack chat https://influxcommunity.slack.com/archives/CH99HUH8V/p1669714123768709

submitting code via https://github.com/influxdata/telegraf/pull/12319

**Comment by powersj** [comment]
next steps: once update is made, review PR
