### ISSUE TITLE
test: test-licenses fails for github.com/signalfx/gohistogram

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#12344]
### Relevant telegraf.conf

```toml
n/a
```

### Logs from Telegraf

```text
2022/12/06 15:26:47 ERR: "github.com/signalfx/gohistogram" (MIT License) download from "https://raw.githubusercontent.com/signalfx/gohistogram/master/LICENSE" failed 404: Not Found
```

### System info

master

### Steps to reproduce

https://app.circleci.com/pipelines/github/influxdata/telegraf/14136/workflows/954e2798-54f9-408f-83b2-b5174447f3c7/jobs/224674

### Expected behavior

test pass

### Actual behavior

fails

**Comment by powersj** [comment]
Indirect dependency asked in https://github.com/signalfx/golib/issues/241 about status

**Comment by breedx-splk** [comment]
@powersj Many apologies for this! We have had the repo restored. Can you please confirm that the license validation is working again? 🙏🏻

**Comment by powersj** [comment]
Resolved, see https://github.com/signalfx/golib/issues/241. Thanks @breedx-splk
