### ISSUE TITLE
[inputs.vsphere] SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by Moep90** [influxdata/telegraf#12350]
### Relevant telegraf.conf

```toml
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "10s"
  precision = "1s"


[[inputs.vsphere]]
 
  vcenters = ["https://vcenter.example.com/sdk"]
  username = "monitoring@example.com"
  password = "<mypassword>"
  insecure_skip_verify = true
  ip_addresses = ["ipv4"]

  interval = "300s"
  max_query_metrics = 256
  collect_concurrency = 3

  force_discover_on_init = false

  vm_metric_exclude = [""]

  host_metric_include = ["*"]
```

### Logs from Telegraf

```text
$ telegraf --input-filter vsphere --test
2022-12-07T10:54:03Z I! Using config file: /etc/telegraf/telegraf.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x3380c92]

goroutine 27 [running]:
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*Endpoint).Collect(0x0, {0x67eeff0?, 0xc000076080}, {0x680b1a0?, 0xc000778620})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:891 +0x72
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*VSphere).Gather.func1(0xc000092f90?)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/vsphere.go:138 +0x78
created by github.com/influxdata/telegraf/plugins/inputs/vsphere.(*VSphere).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/vsphere.go:136 +0x65
```

### System info

telegraf 1.24.1-1, Debian 10 + 11

### Steps to reproduce

1. Create user named monitoring in vCenter
2. Give "monitoring user in vCenter the "Administrator" role
3. Put the config into telegraf
4. run `telegraf --input-filter vsphere --test`

### Expected behavior

Metrics should be gathered from vCenter or at least report whats wrong with the config.

### Actual behavior

SIGSEGV: segmentation violation

### Additional info

User is created in vCenter.
User has (for testing) Administrator permissions.
Administrator permissions are still the vcenter default.
vSphere 7.0.3.00600

**Comment by powersj** [comment]
Hi,

Before I dive further into this, did you not see any errors in your output? only the crash?

> telegraf 1.24.1-1
> /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:891

Line 891 is the call below to `GetClient` which is nil. This is set up during the `Start` phase of the plugin.

```
func (e *Endpoint) Collect(ctx context.Context, acc telegraf.Accumulator) error {
	// If we never managed to do a discovery, collection will be a no-op. Therefore,
	// we need to check that a connection is available, or the collection will
	// silently fail.
	if _, err := e.clientFactory.GetClient(ctx); err != nil {
		return err
	}
        ...
```

When I try running this locally I get an error during the `Start` phase. However, when running with `--test` we do not stop when an error happens during `--test`:

```
2022-12-07T14:50:20Z D! [inputs.vsphere] Creating client: vcenter.example.com
2022-12-07T14:50:20Z E! [agent] Starting input inputs.vsphere: unable to create new endpoint: Post "https://vcenter.example.com/sdk": dial tcp: lookup vcenter.example.com: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x3555fa0]

goroutine 33 [running]:
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*Endpoint).Collect(0x0?, {0x6a9e568?, 0xc0000780c8?}, {0x6abac40?, 0xc000cda1c0?})
	/home/powersj/telegraf/plugins/inputs/vsphere/endpoint.go:897 +0x60
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*VSphere).Gather.func1(0x0?)
	/home/powersj/telegraf/plugins/inputs/vsphere/vsphere.go:140 +0x78
created by github.com/influxdata/telegraf/plugins/inputs/vsphere.(*VSphere).Gather
	/home/powersj/telegraf/plugins/inputs/vsphere/vsphere.go:138 +0xb3
```

We do stop when normally running (i.e. no `--test` or `--once`)

```
2022-12-07T14:55:36Z D! [inputs.vsphere] Creating client: vcenter.example.com
2022-12-07T14:55:37Z E! [telegraf] Error running agent: starting input inputs.vsphere: unable to create new endpoint: Post "https://vcenter.example.com/sdk": dial tcp: lookup vcenter.example.com: no such host
telegraf on  master [!?] via 🐹 v1.19.3 took 2s 
$
```

**Comment by powersj** [comment]
next steps: look at git blame in agent code and see why we are not checking for errors during the `Start` phase of `--test`.

There was a change previously made to let users test their configs to ensure they correctly load, but in reality this is an issue that we should catch during `Start` and not continue further.

**Comment by powersj** [comment]
I put up #12353 that should algin the --test/--once behaviors with normal telegraf runs. Can you confirm this prevents the crash?

Thanks

**Comment by Moep90** [comment]
@powersj If you mean me? I cant really test it from here.

**Comment by powersj** [comment]
> I cant really test it from here.

There are artifacts on that PR you can download and try out. Are you not able to download them?
