### ISSUE TITLE
opentelemetry plugin doesnt work with statsd timing type

### ISSUE THREAD

**Issue by povilasv** [influxdata/telegraf#12363]
### Relevant telegraf.conf

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Log at debug level.
  debug = true
  quiet = false
[[inputs.statsd]]
   protocol = "udp"
   max_tcp_connections = 250
   tcp_keep_alive = false
   service_address = ":8125"
   delete_gauges = true
   delete_counters = true
   delete_sets = true
   delete_timings = true
#   percentiles = [50.0, 90.0, 99.0, 99.9, 99.95, 100.0]
   metric_separator = "_"
#   parse_data_dog_tags = false
   allowed_pending_messages = 10000
   percentile_limit = 1000
[[outputs.opentelemetry]]
   service_address = "localhost:443"
   insecure_skip_verify = true
   compression = "gzip"
```

### Logs from Telegraf

```text
2022-12-08T20:35:01Z D! [outputs.opentelemetry] skipping unrecognized histogram field field="upper" value=%!q(float64=10)
2022-12-08T20:35:01Z D! [outputs.opentelemetry] skipping unrecognized histogram field field="lower" value=%!q(float64=10)
test_service_stage_metrics_biz_success_v4,host=povilas-thinkpad,hostname=$HOSTNAME,metric_type=timing,namespace=$NAMESPACE,nodename=$NODENAME,type=app sum=100,upper=10,lower=10,count=10i,mean=10,median=10,stddev=0 1670531700000000000
2022-12-08T20:35:01Z W! [outputs.opentelemetry] failed to add point: unsupported histogram count value type int64
2022-12-08T20:35:01Z D! [outputs.file] Wrote batch of 1 metrics in 213.753µs
```

### System info

Linux

### Steps to reproduce

1. Run telegraf with config
2. Test with ` echo "test.service.stage.metrics.biz.success_v4:10|ms|@0.1" | nc -w 1 -u localhost 8125`

### Expected behavior

sends all the data to opentelemetry endpoint

### Actual behavior

throws errors; debug logs indicate drops data.

### Additional info

I've investigate this issue and it's:

1. Statsd timings are aggregated wtih mean, median, sum, upper, lower, etc, and are set as `untyped` metric type
_>https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L244-L265

2. Opentelemetry plugin when resolving the untyped metric sees that it has `count` field and assumes Prometheus Histogram

https://github.com/influxdata/influxdb-observability/blob/main/influx2otel/metrics_telegraf_prometheus_v1.go#L52-L56

Because timing type uses special `metric_type=timing` tag we can assume that it's timing summary and convert everything to gauges.

I've opened PR in the library -> https://github.com/influxdata/influxdb-observability/pull/136

**Comment by powersj** [comment]
next steps: see what happens with upstream and get someone more knowledgable to comment on the change
