### ISSUE TITLE
MutlipleLines outputs instead of Single Line for same timestamp for OPCUA tags

### ISSUE THREAD

**Issue by ilyas032019** [influxdata/telegraf#12373]
### Please direct all support questsions to slack or the forums. Thank you.

Hi Team,
Currently i'm using this plugin to fetch data from OPCUAclients.
My observation is on the design from, for each tag(from the opcua taglist configured in conf file) this plugin outputs the data as individual lines for each tag even if its receive data at same exact timestamps.

the issue comes when i use this telegraf plugin in QuestDB. I configured 10 OPCUA tag and i see 10 rows with same timestamps in the table out of which 9 are NULL and only 1 have values.

Actual QuestDB table output: For Same Timestamps multiple rows for multiple tags
"timestamp","tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"
"2022-12-10T23:59:28.000000Z",18.58072,,,,,,,,,
"2022-12-10T23:59:28.000000Z",,4.30858,,,,,,,,
"2022-12-10T23:59:28.000000Z",,,1155.558,,,,,,,
"2022-12-10T23:59:28.000000Z",,,,1411.614,,,,,,
"2022-12-10T23:59:28.000000Z",,,,,238.6185,,,,,
"2022-12-10T23:59:28.000000Z",,,,,,1280.09,,,,
"2022-12-10T23:59:28.000000Z",,,,,,,800.7842,,,
"2022-12-10T23:59:28.000000Z",,,,,,,,47.16882,,
"2022-12-10T23:59:28.000000Z",,,,,,,,,38.81365,
"2022-12-10T23:59:28.000000Z",,,,,,,,,,18.58072

Expected QuestDB table output:: One line output for same timestamp. If value not present then NULL is obviuos output.
"timestamp","tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"
"2022-12-10T23:59:28.000000Z",18.58072, 4.30, 1155.5, 1411.6, 238.61, 1280.09, 800.78, 47.16882, 38.81, 18.58

Can we change this please. This might improve the throughput as well.

Thanks

**Comment by srebhan** [comment]
First of all, you mentioned yourself: :-) 
> Please direct all support questsions to slack or the forums. Thank you.

Please use the [merge aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge) for achieving this!

**Comment by ilyas032019** [comment]
Hi thanks for mentioning the agent. Is it applied in outputs section or agent secrion?

**Comment by ilyas032019** [comment]
This plugin is not working. 
config
![image](https://user-images.githubusercontent.com/52610479/208268730-33fc51f0-2e02-45b9-8dd3-7015e2f78512.png)

Metrics Output:
![image](https://user-images.githubusercontent.com/52610479/208268793-e4e68a51-a01d-456e-9956-7e7f1316c8e3.png)

Any more suggestions

**Comment by srebhan** [comment]
Your series key is different for each line because you do have `i` in the tags which has a different value for each line. You also might want to make `Quality` a tag to merge all fields that are `OK` and all `NOK`... So you should use
```toml
  tagexclude = ["i"]
```
in your `inputs.opcua` section to get rid of the `i` tag and maybe use the [converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter) to make `Quality` a tag. Afterwards, merge will work.
