### ISSUE TITLE
log file aggregator centralize log server

### ISSUE THREAD

**Issue by mehrdad2000** [influxdata/telegraf#12370]
### Please direct all support questsions to slack or the forums. Thank you.

Hi
I have 3 servers that generate log file daily with size about 12GB (12*3=36GB)

How can I use telegraf to gather these files on centralize log server.

Thanks,

**Comment by srebhan** [comment]
@mehrdad2000 please use the Forum or Slack channel as Tigerbot suggests for questions like this. Issues are for problems you have with plugins or Telegraf or for requesting missing features!
