### ISSUE TITLE
 Error in plugin: strconv.ParseFloat: parsing "-4}}": invalid syntax

### ISSUE THREAD

**Issue by dl1mx** [influxdata/telegraf#12388]
### Please direct all support questsions to slack or the forums. Thank you.

Hi,

I'm trying to import data from an MQTT broker from my heater into influxDB, but I'm getting an error in the mqtt_consumer plugin saying there is an invalid syntax.

here is the log:
2022-12-13T11:15:03Z E! [inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "60.000}}": invalid syntax
2022-12-13T11:15:08Z E! [inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "-4}}": invalid syntax

here is the config:
```
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "ebusd/broadcast/sollw/#"
    measurement = "_/_/measurement/_"
    tags = "tag/device/_/_"
    fields = "_/_/_/test"
    [inputs.mqtt_consumer.topic_parsing.types]
      test = "float"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "ebusd/broadcast/betrd/#"
    measurement = "_/_/measurement/_"
    tags = "tag/device/_/_"
    fields = "_/_/_/test"
    [inputs.mqtt_consumer.topic_parsing.types]
      test = "float"
```

here is the data:
```
{
     "status": {"value": 9},
     "zustand": {"value": "48"},
     "stellgrad": {"value": null},
     "kesseltemp": {"value": 66.0},
     "ruecklauftemp": {"value": null},
     "boilertemp": {"value": 57},
     "aussentemp": {"value": -5}}
	 
{
     "kesselsolltemp": {"value": 56.000},
     "aussentemp": {"value": -11.801},
     "leistungszwang": {"value": null},
     "status": {"value": "05"},
     "brauchwassersolltemp": {"value": 60.000}}
```

Software used:
mosquitto 1.5.8
InfluxDB shell version: 1.8.10
https://github.com/john30/ebusd/

Can anybody help me to get this solved? I assume it has something to do with the missing newline after the last value. Because I'm not the author of this software I cannot change the MQTT content.

Best reagrds,
Marco

**Comment by srebhan** [comment]
Hmmm this more looks like parsing your **message** fails than the topic parsing fails! Please remember topic-parsing is for extracting elements **from the MQTT topic** itself, not from the data sent in this topic. Can you please post your (redacted) complete MQTT config!?

**Comment by dl1mx** [comment]
Thanks, I changed this device to a separate section in telegref.conf and now it works. Here is the config:

[[inputs.mqtt_consumer]]
   servers = ["tcp://192.168.xxx.xxx:1883"]
   topics = [
     "ebusd/broadcast/#"
   ]
   username = "xxx"
   password = "xxx"
   data_format = "json"
   data_type = "float"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "ebusd/broadcast/+/+"
    measurement = "_/_/measurement/_"
    tags = "device/unit/_/_"
