### ISSUE TITLE
Make --watch-config aware of addition and removal of .conf files

### ISSUE THREAD

**Issue by protonmarco** [influxdata/telegraf#12389]
### Use Case

This feature would avoid to have to `kill -1` telegraf each time a .conf file is added or removed inside the config directory.

### Expected behavior

once `--watch-config [notify, poll]` is set it should be aware of:
- changes inside .conf files (already accomplished)
- .conf removals
- .conf additions

and reload configuration accordingly.

### Actual behavior

Currently `--watch-config [poll, notify]` reloads the configuration only when the content of a .conf file changes. 
When a .conf file is added or removed, a manual configuration reload is still needed.

**Comment by powersj** [comment]
Create is covered by #12264 as well.

**Comment by gazpachoking** [comment]
This would be great. I already get logging messages when config files are added and deleted, seems like it would be a pretty easy step to have trigger a reload.

```
2023-03-24T16:44:28Z W! Config file deleted
2023-03-24T16:52:16Z I! Config file appeared
```

**Comment by powersj** [comment]
@protonmarco,

I have a PR that adds the ability to watch directories for addition and removal of configuration files: https://github.com/influxdata/telegraf/pull/15645 could you download the artifacts in that PR and verify that this resolves your use-case?

Thanks!
