### ISSUE TITLE
mysql_slave_Slave_SQL_Running metric is missing after update to 1.25.0

### ISSUE THREAD

**Issue by d-kuhn** [influxdata/telegraf#12398]
### Relevant telegraf.conf

```toml
[[inputs.mysql]]
servers = ["telegraf@unix(/var/run/mysqld/mysqld.sock)/"]
gather_slave_status = true
```

### Logs from Telegraf

```text
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Starting Telegraf 1.25.0
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Loaded inputs: cpu disk diskio filestat kernel mem mysql powerdns processes swap system
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Loaded aggregators:
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Loaded processors:
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Loaded secretstores:
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Loaded outputs: prometheus_client
Dec 14 13:19:21 designate-publicdns-3 telegraf[2992]: 2022-12-14T13:19:21Z I! Tags enabled: host=designate-publicdns-3
Dec 14 13:19:21 designate-publicdns-3 systemd[1]: Started Telegraf.
```

### System info

Telegraf 1.25.0, Ubuntu 18.04 LTS

### Steps to reproduce

1. Install telegraf 1.25.0
2. Add `gather_slave_status = true` to telegraf.config in the mysql input configuration
3. Check for the availability of the `mysql_slave_Slave_SQL_Running` metric with curl  `curl -s  10.129.2.39:9273/metrics  | grep -i mysql_slave_Slave_SQL_Running`

### Expected behavior

The `mysql_slave_Slave_SQL_Running` metric should be available

### Actual behavior

the `mysql_slave_Slave_SQL_Running` metric is not available 

### Additional info

Running telegraf 1.24.4 with the same configuration works as expected: 

```
root@designate-publicdns-3:~# curl -s  10.129.2.39:9273/metrics  | grep -i mysql_slave_Slave_SQL_Running
# HELP mysql_slave_Slave_SQL_Running Telegraf collected metric
# TYPE mysql_slave_Slave_SQL_Running untyped
mysql_slave_Slave_SQL_Running{host="designate-publicdns-3",server="/var/run/mysqld/mysqld.sock"} 1


root@designate-publicdns-3:~# apt install telegraf
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  telegraf
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/45.0 MB of archives.
After this operation, 5235 kB of additional disk space will be used.
(Reading database ... 76588 files and directories currently installed.)
Preparing to unpack .../telegraf_1.25.0-1_amd64.deb ...
Unpacking telegraf (1.25.0-1) over (1.24.4-1) ...
Setting up telegraf (1.25.0-1) ...
Installing new version of config file /etc/telegraf/telegraf.conf.sample ...

root@designate-publicdns-3:~# systemctl restart telegraf

root@designate-publicdns-3:~# curl -s  10.129.2.39:9273/metrics  | grep -i `mysql_slave_Slave_SQL_Running
root@designate-publicdns-3:~#
```

**Comment by exabrial** [comment]
Workaround is to downgrade to telegraf_1.24.4-1:

Example for Ubuntu 22.04:

```
sudo apt -y install telegraf=1.24.4-1 --allow-downgrades && sudo systemctl restart telegraf.service
```

**Comment by powersj** [comment]
There was a single change to the mysql plugin between [v1.24.4 and v1.25.0](https://github.com/influxdata/telegraf/compare/v1.24.4...v1.25.0) via https://github.com/influxdata/telegraf/commit/c6663aca4f87073b8fa7edb511b163b0edcc38a8#diff-57876cf514e1f657ef136c84326f00f73b12ce2ee03d4060ffe863a3a3940e51 which was to `gatherSlaveStatuses`

@zak-pawel @srebhan is the change causing issues with the `rows.Scan(valPtrs...)` on the next line?

The dependency on `github.com/go-sql-driver/mysql` did not update or change.

> Check for the availability of the mysql_slave_Slave_SQL_Running metric with curl curl -s 10.129.2.39:9273/metrics | grep -i mysql_slave_Slave_SQL_Running

fwiw I prefer showing issues with inputs using the `[[outputs.file]]` output and showing what the metrics to stdout report as. It reduces any possible issues or changes to outputs as a potential cause and does not add any extra steps.

**Comment by zak-pawel** [comment]
@d-kuhn Should be fixed in https://github.com/influxdata/telegraf/pull/12409

**Comment by exabrial** [comment]
I just wanted to say thank you for the incredibly quick turnaround on the regression.
