### ISSUE TITLE
Error writing to output [Kafka]: Failed to send kafka message

### ISSUE THREAD

**Issue by AliGouta** [influxdata/telegraf#1239]
## Bug report

Getting this error after making telegraf (v0.12) sending data to kafka:

`Error writing to output [Kafka]: Failed to send kafka message: write tcp HOST_SOURCE_FQDN:44627 -> KAFKA_BROKER:9092 i/o timeout`

### System info:

Telegraf 0.12, System RedHat, Kafka 0.82

### Steps to reproduce:

The kafka output section in telegraf.conf:

```
[[outputs.kafka]]
  brokers = ["kafka01:9092","kafka02:9092","kafka03:9092","kafka04:9092"]
  topic = "ouput_topic"
  data_format = "influx"
  routing_tag = "fqdn"
  compression_codec = 2
  required_acks = 0

```
### Expected behavior:

Getting this kind of message in the log:

`Wrote 31 metrics to output kafka in 388 ms`

### Actual behavior:

Instead I am getting:

`Error writing to output [Kafka]: Failed to send kafka message: write tcp HOST_TELEGRAF_FQDN:44398->KAFKA_BOKER:9092: i/o timeout`

### Use case:

Kafka is so used everywhere. It makes sens to investigate this issue

**Comment by sparrc** [comment]
@AliGouta do you consistently get this error message? do any writes succeed? can you provide more log output before and after this happens?

**Comment by AliGouta** [comment]
Yes, I consistently get this error message. I have to restart telegraf to get it back sending to Kafka, otherwise it will indefinitely throws the error. The log output is the same each time Telegraf tries to send data to kafka. It always throws:

`Error writing to output [Kafka]: Failed to send kafka message: write tcp HOST_TELEGRAF_FQDN:44398->KAFKA_BOKER:9092: i/o timeout`

Same source port...

**Comment by framiere** [comment]
@AliGouta is the issue #1113 of any help ?

**Comment by sparrc** [comment]
hm, strange, I haven't seen that issue before. @AliGouta do you have any advice on reproducible steps to create the issue? Have you tried playing with the max_retry argument to see if it helps?

**Comment by sparrc** [comment]
could be that you have a typo in your config, see https://github.com/Shopify/sarama/issues/632

it _does_ look like the config you provided has a typo:

```
[[outputs.kafka]]
  brokers = ["kafka01:9092","kafka02:9092","kafka03:9092","kafka04:9092"]
  topic = "ouput_topic" <--------------------------missing a "t", should be "output_topic"??
  data_format = "influx"
  routing_tag = "fqdn"
  compression_codec = 2
  required_acks = 0
```

**Comment by framiere** [comment]
Ali's topic is valid as data is flowing, but stops at some point (as restart make the data flow again).
While digging this subject I stumbled onto Shopify/sarama#294 which looks very much alike what @AliGouta is experiencing.
@sparrc any idea how can Sarama logs can be activated in Telegraf ?

**Comment by sparrc** [comment]
true, @AliGouta could you set `max_retry = 3` and confirm if that works for you? Upgrading to 0.13 should also fix it, as I've changed the kafka output to default to max_retry=3 if nothing is specified.

**Comment by AliGouta** [comment]
@sparrc, Changing max_retry to 3 seems to fix the issue, my telegraf was running for a couple of days dumping the data successfully in kafka. I will make it running for a long period of time and get back to you if there is an issue. You may close the issue at the moment. Thank you!

**Comment by sparrc** [comment]
thx
