### ISSUE TITLE
x509_cert plugin broken in release 1.25.0

### ISSUE THREAD

**Issue by danclough** [influxdata/telegraf#12402]
### Relevant telegraf.conf

```toml
[agent]
    debug = true
[[inputs.x509_cert]]
    sources = ["https://www.google.com:443"]
    exclude_root_certs = true
```

### Logs from Telegraf

```text
[inputs.x509_cert] Invalid certificate at index  0!
[inputs.x509_cert]   cert DNS names:    [www.google.com]
[inputs.x509_cert]   cert IP addresses: []
[inputs.x509_cert]   opts.DNSName:      www.google.com
[inputs.x509_cert]   verify options:    {www.google.com 0x400154ac90 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
[inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
[inputs.x509_cert]   location:          https://www.google.com:443
[inputs.x509_cert]   tlsCfg.ServerName:
[inputs.x509_cert]   ServerName:
```

### System info

Telegraf 1.25.0, Ubuntu 22.04

### Steps to reproduce

1. Install Telegraf 1.25.0-1 from InfluxDB apt repo
2. Configure x509_cert plugin to check Google's TLS certificate via `sources = ["https://www.google.com:443"]`
3. Set `debug = true`
4. Observe debug output reporting that the Google TLS certificate is signed by unknown authority
5. Downgrade Telegraf to 1.24.4-1
6. Restart Telegraf
7. Observe that debug output no longer reports a problem with the Google TLS certificate
...

### Expected behavior

Certificates that are signed by trusted CAs (global or local) should be reported as valid.

### Actual behavior

All certificates, even ones signed by globally trusted CAs, are reported as invalid.

**Comment by srebhan** [comment]
@danclough thanks for reporting the issue. Can you please test #12404 and let me know if it fixes your issue!?!

**Comment by danclough** [comment]
@srebhan Thank you.  I installed the .deb from the PR artifacts and confirmed that leaf certs from globally trusted orgs like Google/Let's Encrypt are now correctly marked as valid.

I am still having an issue with locally-trusted certs from a private CA that is in the OS ca-certificates.crt trust store.  I can file a separate report for that.
