### ISSUE TITLE
redfish input plugin - add Metrics "PowerConsumedWatts"

### ISSUE THREAD

**Issue by yoitsu1838** [influxdata/telegraf#12414]
### Use Case

Graphical representation of total power consumption on InfluxDB by telegraf

### Expected behavior

Adding  the value and field of "PowerConsumedWatts" to"redfish_power_powersupplies

### Actual behavior

Not getting the value and field of "PowerConsumedWatts" 

Now getting last_power_output_watts, line_input_voltage, power_capacity_watts, power_input_watts and power_output_watts.

**Comment by powersj** [comment]
closing as a dup of #9575
