### ISSUE TITLE
Unit telegraf.service could not be found CentOS 7

### ISSUE THREAD

**Issue by aleksrosz** [influxdata/telegraf#12434]
### Relevant telegraf.conf

```toml
It is not relevant. The configuration is correct. It is working using "telegraf start"
```

### Logs from Telegraf

```text
It is not relevant. The configuration is correct. It is working using "telegraf start"
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79), CentOS 7

### Steps to reproduce

1. yum install telegraf
2. Edit configfile
3. systemctl start telegraf 
Error: "Unit telegraf.service could not be found"

### Expected behavior

Systemd will start telegraf.service

### Actual behavior

Systemd doesn't see telegraf service after installation

**Comment by Hipska** [comment]
Does it recognise the service after doing `systemctl daemon-reload`?

**Comment by aleksrosz** [comment]
I tried and nothing changed

**Comment by aleksrosz** [comment]
During installation, something happened with available storage and Telegraf was not installed successfully. After reinstallation, it works correctly.
