### ISSUE TITLE
Change statsd input number of threads/workers 

### ISSUE THREAD

**Issue by liorfranko** [influxdata/telegraf#12432]
### Please direct all support questsions to slack or the forums. Thank you.

We use telegraf with statsd input as a sidecar in Kubernetes.
We've reached the maximum number of events one telegraf can process at a given time.
We're looking for a way to increase the number of threads/workers.
We see the following PR:
https://github.com/influxdata/telegraf/pull/12318
But it looks like it was reverted or something because we don't see `max_parser_threads` in the docs.
We also saw the following PR:
https://github.com/influxdata/telegraf/pull/6922
But it's not merged.

Can we increase the number of threads?

**Comment by Hipska** [comment]
Most probably because the PR #12318 isn't merged yet. You can however try to download the build artefacts here: https://github.com/influxdata/telegraf/pull/12318#issuecomment-1339287861
