### ISSUE TITLE
Influxdb v1 debug vars but havent in influxdb v2

### ISSUE THREAD

**Issue by robbyq92** [influxdata/telegraf#12443]
### Please direct all support questsions to slack or the forums. Thank you.

Hi, in last time i used this plugin for monitor my debug vars influxdb v1, but now i cant used this:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb

we have any similar for influxdbv2?

**Comment by robbyq92** [comment]
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb

for influxdb normal v1 we have this but for influxdb v2 we havent this?

**Comment by robbyq92** [comment]
any helps?

**Comment by powersj** [comment]
Please see [#10459](https://github.com/influxdata/telegraf/issues/10459)
