### ISSUE TITLE
How to reference secret in postgres connection string

### ISSUE THREAD

**Issue by MNDBA** [influxdata/telegraf#12458]
### Please direct all support questsions to slack or the forums. Thank you.

I configured the secretstores.os plugin to store a secret in Windows Credential Manager. I can list the secret using this telegraf command, see below example.

telegraf secrets get secretstore postgrespassword

I want to pass the secret value into the connection string of the outputs.postgresql. See the following example that does not work.

connection = "host=10.10.10.10 user=dbaadmin password=@{secretstore:postgrespassword} dbname=timescale"

This returns a generic password error.

failed SASL auth (FATAL: password authentication failed for user "dbaadmin" (SQLSTATE 28P01))

How can I replace the password value in the middle of the connection string with the secret returned from secretstores.os?

**Comment by srebhan** [comment]
@MNDBA PR #12067 adds support for using secrets in the postgres plugin. Please let me know if it works for you! The PR currently marked as "draft" as it needs rebasing. Will do this in the next days...

**Comment by MNDBA** [comment]
Thanks for the quick response @srebhan 

This looks useful but it is for the inputs.postgres plugin. I am looking to use a secret to store the connection string for the outputs.postgres plugin. Do you know if there are any plans to add secret support for the outputs.postgres plugin?

**Comment by srebhan** [comment]
@MNDBA there are no concrete plans yet on how to migrate all remaining plugins. Help (i.e. pull-requests) is welcome! Please at least open a feature request so that we get an idea on what people need...

**Comment by srebhan** [comment]
Closing this issue in favor of an to-be-filed feature request.
