### ISSUE TITLE
Expose option to increase max message size in gNMI plugin.

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#12463]
### Use Case

I'd like to have the ability to edit the max message size of the data set that gets streamed in using the gNMI plugin.

My input stanza:
```
[[inputs.gnmi]]
  addresses = ["10.30.2.8:10161"]
  username = "$user"
  password = "$password"
  redial = "10s"
  enable_tls = true
  insecure_skip_verify = true

  [[inputs.gnmi.subscription]]
    name = "test"
    path = "/slots[name=2]"
    subscription_mode = "sample"
    suppress_redundant = false
     sample_interval = "60s"
```
I would like an option like `max_msg_size` that I can assign a value so I can receive datasets that currently exceed the current max size.

This is the error that I'm currently seeing:
```
2023-01-04T20:18:58Z E! [inputs.gnmi] Error in plugin: aborted gNMI subscription: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8167002 vs. 4194304)
```

### Expected behavior

I would expect the data to stream in and proceed to go out to the specified output plugin.

### Actual behavior

Currently seeing the following error when a data set exceeds the max message size:
```
2023-01-04T20:18:58Z E! [inputs.gnmi] Error in plugin: aborted gNMI subscription: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8167002 vs. 4194304)
```the 

### Additional info

I'm currently using Telegraf v1.23.4
[InfluxData Community Support Link for this issue](https://community.influxdata.com/t/telegraf-how-to-increase-allowed-message-size/28001)

**Comment by powersj** [comment]
Thanks for the issue!

**Comment by powersj** [comment]
@mohsin106 I put up #12495 with a new option. That PR should have artifacts attached to it in 20-30mins. Would you be willing to try those artifacts out and ensure that the new setting resolves your issues?

Thanks!
