### ISSUE TITLE
UPSD issue "partial write: field type conflict"

### ISSUE THREAD

**Issue by rhaamo** [influxdata/telegraf#12461]
### Relevant telegraf.conf

```toml
[[inputs.upsd]]
    server = "127.0.0.1"
    port = 3493
    username = "upsmonitor"
    password = "xxx"
```

### Logs from Telegraf

```text
# log from host 2 if host 1 started first
E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "firmware" on measurement "upsd" is type string, already exists as type integer dropped=1

# log from host 1 if host 2 started first
E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "firmware" on measurement "upsd" is type integer, already exists as type string dropped=1
```

### System info

telegraf 1.25.0-1

### Steps to reproduce

I have the UPSD input enabled on two servers, apparently the "firmware" returned on one host is integer, and string on the other.
Depending on which host writes first, the second cannot write because of different type.

Doing an "upsc xxx | grep firmware" on the hosts I get:
- host 1: `ups.firmware: 02`
- host 2: `ups.firmware: 02.08.0010`

In the influxdb depending on which one starts first (dropping measurements between tests), I get:
```
time                battery_charge_percent dc   firmware host                    load_percent model            os    output_voltage serial status_OL status_flags time_left_ns ups_name         ups_status
----                ---------------------- --   -------- ----                    ------------ -----            --    -------------- ------ --------- ------------ ------------ --------         ----------
1672899550000000000 100                    Home 2        courgette.xxx.xxxxxx.xx 41           Ellipse ECO 1200 Linux 230            0      true      8            581000000000 selfhosting-rack OL
```

or

```
time                battery_charge_percent dc   firmware   host                load_percent model        os    output_voltage serial status_OL status_flags time_left_ns  ups_name ups_status
----                ---------------------- --   --------   ----                ------------ -----        --    -------------- ------ --------- ------------ ------------  -------- ----------
1672899280000000000 100                    Home 02.08.0010 curry.xxx.xxxxxx.xx 20           Eaton 3S 550 Linux 230            Blank  true      8            1200000000000 curry    OL
```

### Expected behavior

all hosts writes the same type for firmware and metrics don't get dropped

### Actual behavior

different value type for firmware and all values get dropped

### Additional info

`telegraf --test --input-filter upsd --config-directory /etc/telegraf/telegraf.d/`

`upsd,dc=Home,host=courgette.xxx.xxxxxx.xx,model=Ellipse\ ECO\ 1200,os=Linux,serial=0,status_OL=true,ups_name=selfhosting-rack battery_charge_percent=100i,firmware=2i,load_percent=40i,output_voltage=230,status_flags=8i,time_left_ns=631000000000i,ups_status="OL" 1672900267000000000`
and
`upsd,dc=Home,host=curry.xxx.xxxxxx.xx,model=Eaton\ 3S\ 550,os=Linux,serial=Blank,status_OL=true,ups_name=curry battery_charge_percent=100i,firmware="02.08.0010",load_percent=20i,output_voltage=230,status_flags=8i,time_left_ns=1248000000000i,ups_status="OL" 1672900306000000000`

**Comment by powersj** [comment]
Hi,

Can you give the artifacts on https://github.com/influxdata/telegraf/pull/12486 a try? It should ensure that the firmware is always a string. The artifacts are attached in 20-30mins after this post once tests pass.

Thanks!

**Comment by rhaamo** [comment]
Thanks @powersj !

After test it seems ok:

Getting `firmware="2"`
```
> upsd,dc=Home,host=courgette.x,model=Ellipse\ ECO\ 1200,os=Linux,serial=0,status_OL=true,ups_name=selfhosting-rack battery_charge_percent=100i,firmware="2",load_percent=39i,output_voltage=230,status_flags=8i,time_left_ns=631000000000i,ups_status="OL" 1673506730000000000
```
and `firmware="02.08.0010"`
```
> upsd,dc=Home,host=curry.x,model=Eaton\ 3S\ 550,os=Linux,serial=Blank,status_OL=true,ups_name=curry battery_charge_percent=100i,firmware="02.08.0010",load_percent=19i,output_voltage=230,status_flags=8i,time_left_ns=1377000000000i,ups_status="OL" 1673506737000000000
```

**Comment by powersj** [comment]
Thank you for confirming!

**Comment by lpaseenba** [comment]
We have a similar problem but with load_percent. One UPS model gives int and another model gives float

```$ upsc ups 2>/dev/null|grep -E "ups.load|device.model"
device.model: Back-UPS ES 600M1
ups.load: 7
```


```$ upsc ups 2>/dev/null|grep -E "ups.load|device.model"
device.model: Back-UPS CS 350
ups.load: 20.0
```

And this of course means we can only get upsd data from one group blocking all data from whoever comes second.

```
Jan 12 09:59:42 redacted telegraf[901]: 2023-01-12T14:59:42Z E! [outputs.influxdb_v2] Failed to write metric to test (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "load_percent" on measurement "upsd" is type integer, already exists as type float dropped=2
```

**Comment by powersj** [comment]
@Ipaseenba please file a new issue and I can look at it
