### ISSUE TITLE
Out requirement is to use telegraf as a service but we need to have a provision to collect the metrics from different data sources dynamically loading the config files without restarting telegraf services

### ISSUE THREAD

**Issue by pratap24** [influxdata/telegraf#12460]
### Please direct all support questsions to slack or the forums. Thank you.

Hi Team,

We are trying to see telegraf will fit for  our use case where the telegraf should be running as a service, and it should have an ability to collect the metrics data from various data sources  dynamically with help of different configs, without requiring restart of telegraf services.

Basically the telegraf service should be looking for the configs,  as and when there is a new config available, it should collect the telemetry and finish the collection data.

Does the current telegraf fit for my use case, please let us know as earliest as possible.

Thanks
Pratap

**Comment by powersj** [comment]
> collect the metrics data from various data sources dynamically with help of different configs, without requiring restart of telegraf services.

As with almost any service, it will not automatically reload the configuration on a change. It is up to the end-user to reload the service.

However, telegraf does have an option to watch a config file that you could add to the service definition to reload on an update to the file. Any change to the file would stop telegraf in the current state and restart telegraf for you with the new config.

**Comment by srebhan** [comment]
@pratap24 in addition to what @powersj said, there is a way to trigger reloading of the config in Linux sending a `SIGHUP`.
