### ISSUE TITLE
Global configuration to log any data points with a timestamp that is older than a configured cutoff date

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#12465]
### Use Case

Sometime data with a very old timestamp is send to telegraf (e.g. via http listener etc.). We want to know details, which dataset has such an invalid timestamp. Metrics with old timestamp are ignored by InfluxDB etc.
Our current approach: Inside Telegraf we included a Python script (as telegraf processor plugin) to analyse every received event regarding timestamp. When timestamp is too old (older than our Influxdb retention intervall) we log this event. So we know who/waht we have to contact and ask for fixing invalid metrics.

### Expected behavior

Telegraf logs (e.g. with severity warning) any data points with a timestamp that is older than a configured cutoff date (relative date).

### Actual behavior

Currenlty you have to implement this feature (find datasets with old timestamp) via custom processor script.

### Additional info

Sending events with a very old timestamp (older than retention) to Influxdb produces HTTP Error "400 Bad Request". No usefull information is logged (IP is useless, when you use loadbalancer in front of InfluxDB and client information does not help really, when client is sending metric data from different sources).

**Comment by 1tft** [comment]
We are using the old (1.x) InfluxDB Output plugin (because of old InfluxDB Enterprise). We see HTTP 400 on InfluxDB Server side (log).
I understand that telegraf can not know how many data points are bounced because of old timestamp, when sending data to output. If it is not possible for telegraf to get retention policy information of data sink (for a dynamic threshold), I suggested a threshold which can be set by user manually.
When you think that my idea regarding a configuration setting to log any data points with a timestamp that is older than a configured cutoff date is not really usefull (for telegraf 2.x), its ok for us. We can live with our custom solution regarding a custom processor which logs this information. I can post this small script here, maybe other users find it usefull...
We also asked InfluxData to implement on InfluxDB server side a better/detailed logging regarding data with old timestamps. Maybe they imlement this for logging severity level "debug" or so.

**Comment by 1tft** [comment]
This starlark approach is similar to ours (but nobody of us has starlark knowledge, thats why we cant use it). We use a Python Script (as processor) and log all invalid data sets to STDERR. So it logs directly to telegraf agent log, which is already monitored by central logging solution and has already logrotating enabled.

Python script "timestamp_too_old_checker.py": 
```
#!/usr/bin/env python3
import sys
from datetime import datetime
 
NANOSECONDS_TO_SECONDS_FACTOR = 1000000000
 
if __name__ == "__main__":
  if len(sys.argv) != 2:
    print(f"Number of arguments is {len(sys.argv)} but should be 2.", file=sys.stderr)
    sys.stderr.flush()
    sys.exit()
 
  too_old_threshold_in_days = int(sys.argv[1])
 
  for data_point in sys.stdin:
    timestamp_nanoseconds = int(data_point[data_point.rindex(" ") + 1:].rstrip("\n"))
    timestamp_seconds = timestamp_nanoseconds / NANOSECONDS_TO_SECONDS_FACTOR
    data_point_dt = datetime.utcfromtimestamp(timestamp_seconds)
    data_point_age = datetime.now() - data_point_dt
 
    if data_point_age.days <= too_old_threshold_in_days:
      print(data_point)
      sys.stdout.flush()
    else:
      print(f"Data point older than {too_old_threshold_in_days} days: {data_point}", file=sys.stderr)
      sys.stderr.flush()
```

Telegraf Config:
```
[[processors.execd]]
   order = 10
   command = ["/etc/telegraf/scripts/timestamp_too_old_checker.py 30"]
```

**Comment by srebhan** [comment]
@1tft not sure if I understand your message correctly... Currently we do not have a dedicated "this is too old" filter, nor do we have any processor in place that is dedicated to handle this besides the general starlark processor.

The above is a working solution, it's built-into Telegraf in any recent version and for someone understanding python, starlark is a no-brainer. [Starlark](https://github.com/google/starlark-go) itself is open-source and maintained. 

I'm not sure what is your request is!?! What prevents you from using the above solution?

**Comment by 1tft** [comment]
@srebhan Thank you for this solution! I pasted another valid solution, because I wanted to show our current solution and I like possibility to log these messages to telegraf default logging output (file). So other users and ChatGPT 😀 can now find here different solutions for this common problem. I suggested this feature request because (as you said) currently there does not exist any "dedicated this is to old filter" telegraf filter.
I thought, maybe Telegraf guys find it usefull to implement such a feature. I confirm there are more than one solution for this use case so this feature request feature is not realy important.

**Comment by srebhan** [comment]
@1tft thanks for posting your solution, much appreciated!

Please note that you can log to the default logfile in starlark using the `logging` module (see [this example](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/logging.star)).
My concern is that we end-up with a very specific plugin to accommodate this use-case... 

Do you agree to close this feature-request as there is a solution (in fact multiple)?

**Comment by 1tft** [comment]
Hello @srebhan,
thank you for this additional information. Of course this FR can be closed. When nobody else finds it usefull to implement such a feature.
So we will use described possibilities to analyze datasets regarding old timestamps also in future (with telegraf 2.x 😃).
