### ISSUE TITLE
New P4Runtime input plugin

### ISSUE THREAD

**Issue by jokuniew** [influxdata/telegraf#12470]
### Use Case

[P4Runtime](https://github.com/p4lang/p4runtime) is a gRPC server whose API is used to interact with a control plane specification for controlling the data plane elements of a device defined or described by a P4 program.

P4Runtime Specification: https://p4.org/p4-spec/docs/p4runtime-spec-working-draft-html-version.html

P4 programmable pipelines provide the flexibility of adding custom counters that can help observe the pipeline's operation. We provide the means to evaluate the effectiveness of those pipelines via exposed counters. That is the motivation why we would like to have a Telegraf input plugin that exposes P4Runtime Counters metrics.

### Proposal:
In the near future we will propose PR which adds a new plugin we have created. It will be able to provide the following metrics:

**Tags:**
- `p4program_name`: P4 program name provided by a user.
- `counter_name`: Name of the given counter in P4 program.
- `counter_index`: Index at which metrics are collected in P4 counter.
- `counter_type`: Type of counter (BYTES, PACKETS, BOTH).

**Fields:**

- `bytes`: Number of bytes gathered in counter.
- `packets` Number of packets gathered in the counter.

### Expected behavior

P4 Counters' insights are gathered regularly from P4Runtime through gRPC connection.

### Actual behavior

There are tools which use P4Runtime Protobuf to communicate interactively/through user's scripts with the control plane. 
There are no tools that provide continuous telemetry gathering for P4Runtime.

**Comment by powersj** [comment]
next steps: continue reviews of PR
