### ISSUE TITLE
Help me to setup this.

### ISSUE THREAD

**Issue by balajeek** [influxdata/telegraf#12474]
### Please direct all support questsions to slack or the forums. Thank you.

I saw this grafana dashboard to monitor sql server databases, and interested in setting it up.  
I installed latest version of InfluxDB and Grafana on my local desktop and i can login in to influxdb web ui and i also configured the datasource influxdb on grafana.  So far successfull.

Now I don't understand what i need to install on the SQL Server machine, i did create the user as mentioned, but the plugin you are mentioning, where is it and how do i install it.

Idea is InfluxDB and Grafana will be on my local desktop.
Telegraph and any other tool to collect metrics will on the sql server machine.
Hope this is correct.

So please let me know.  I am on Windows.
Thank you.

**Comment by srebhan** [comment]
@balajeek please do not use the issues for those kind of help questions. As the bot mentioned, please use the forum or slack channel!
