### ISSUE TITLE
Feature request: One server with multiple request handler for webhooks style plugins

### ISSUE THREAD

**Issue by francois2metz** [influxdata/telegraf#1248]
### Proposal:

While working on #1247 to add Rollbar, we mostly copied the original `github_webhooks` plugin. 
For this kind of webhook powered service, listening on a new port is quite cumbersome. We plan to add support for at least 2 similar service.

The proposal is to have a global http listener (and maybe https :heart_eyes:) handled by telegraph. 
Plugins would register handlers such as  `/github_webhhoks` or `/rollbar_webhooks`. If there is any handlers, telegraf will start listening on a globally defined port. 

### Current behavior:

One port for each listening services.

### Desired behavior:

One port for all listening services.

### Use case: [Why is this important (helps with prioritizing requests)]

To support multiple webhook style plugin. We plan to add mandrill and filestack plugins soon.

**Comment by francois2metz** [comment]
Would be interested if we provide a patch?

**Comment by sparrc** [comment]
yes, always :)

**Comment by francois2metz** [comment]
Since https://github.com/influxdata/telegraf/pull/1289 has been merged \o/
