### ISSUE TITLE
secret-store for mysql plugin

### ISSUE THREAD

**Issue by jfrye121** [influxdata/telegraf#12487]
### Use Case

Currently, there is no implementation of feat:secret-store #11232  for mariadb/mysql plugin. Ideally, it would be best practice to avoid having passwords in plain text in the configuration file. Therefore, the hope is to be able to use use secret-store to encrypt the credentials for the mariadb/mysql plugin

### Expected behavior

[[inputs.mysql]]
  servers = ["dbuser:encryptedpassword@tcp(ipaddress)/>
  metric_version = 2
  table_schema_databases = []
  perf_summary_events = []
  gather_table_schema = true
  gather_process_list = true
  gather_info_schema_auto_inc = true
  gather_user_statistics = true
  gather_slave_status = true
  gather_table_io_waits = true
  gather_table_lock_waits = true
  gather_index_io_waits = true
  gather_event_waits = true
  gather_file_events_stats = true
  gather_perf_events_statements = true
  interval_slow = "30m"

telegraf secrets set secretstore secretkey

telegraf secrets set mysql monitoringuser----not sure if this is how it actually works. Please forgive me.

### Actual behavior

You cannot use secrets-store with the mysql/mariadb plugin

### Additional info

This request comes from a conversation by Sven Rebhan and theRetroDBA on Slack #telegraf channel on 2023/01/09

**Comment by powersj** [comment]
@srebhan will take a look, thanks!

**Comment by jfrye121** [comment]
I will try to check this periodically if there are any questions for me!

**Comment by srebhan** [comment]
@jfrye121 can you please test the binary built in #12591 once CI finished the build!? Let me know if that works for you!

**Comment by jfrye121** [comment]
Sorry- I have not gotten around to this. I will try to get this tested next week

**Comment by srebhan** [comment]
@jfrye121 you can either build telegraf from master or test a nightly build as the PR is already merged...
