### ISSUE TITLE
Please add "secrets" support for  influxdb_v2 output 

### ISSUE THREAD

**Issue by jackbenimble999** [influxdata/telegraf#12484]
### Use Case

We are using a telegraf plugin write data to InfluxDB, and would like to keep the token in the configuration file hidden from the user as it is distributed to the customer site. 

### Expected behavior

Would like for  secrets to be supported  for the influxdb_v2 output plugin.

### Actual behavior

 secrets is not yet supported  for the influxdb_v2 output plugin.

### Additional info

@srebhan suggested I submit this.

**Comment by powersj** [comment]
@srebhan will take a look, thanks!

**Comment by srebhan** [comment]
@jackbenimble999 can you please check PR #12497 which should also add support for secrets in the token field of `outputs.influxdb_v2`.
