### ISSUE TITLE
[inputs.prometheus] Error in plugin: Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by ricardoleal** [influxdata/telegraf#12485]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["http://localhost:9710/probe?target=https://fortigate.local:8443"]
  response_timeout = "120s"
  metric_version = 2
```

### Logs from Telegraf

```text
E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### System info

Telegraf 1.25.0, Debian 10 (20220310-944), AWS

### Steps to reproduce

1. Use telegraf version 1.25.0
2. Use https://github.com/bluecmd/fortigate_exporter 

### Expected behavior

`Telegraf` can scrape metrics for that prometheus exporter.

### Actual behavior

When using version 1.25.0 telegram can't scrape metrics and trows the following error:

`E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by powersj** [comment]
If you wget/curl that URL from the same place you are running Telegraf, what response do you get?

**Comment by ricardoleal** [comment]
The `curl` command with proper authentication gives the metrics.

**Comment by ricardoleal** [comment]
> > gives the metrics.
> 
> How long does it take to complete? Is it instant?

Yes i have measure the time ... 10s

**Comment by powersj** [comment]
> The curl command with proper authentication gives the metrics.

What does proper authentication mean? Your config did not provide any indication you are using any authentication in your report.

>  The curl command with proper authentication gives the metrics.

Can you share exactly what commands you had to run, with any credentials omitted, the output to so I can understand the flow you are trying to achieve. 

> Client.Timeout exceeded while awaiting headers

You only provided a single log line. Does this error always show up? Has this ever worked before? Does it work on other URLs?

This error tends to mean that something along the connection took longer than your timeout. With a 120 second timeout I would expect a local request to certainly finish. Does your log message show it took 120 seconds? Or does it show up sooner?

As I do not have accees to a Fortigate API key or system I cannot go and attempt to reproduce this. You are going to have to help narrow this down further. It is very unlikely that the URL handing in the plugin suddenly stopped working, so I am more inclined to say something else is up (e.g. creds, firewall, other networking, etc.)

**Comment by ricardoleal** [comment]
The expected result with curl is 
```
$ time curl -s http://localhost:9710/probe?target=https://fortigate.local:8443 | head
# HELP fortigate_certificate_cmdb_references Number of times the certificate is referenced
# TYPE fortigate_certificate_cmdb_references gauge
fortigate_certificate_cmdb_references{name="Fortinet_CA_SSL",scope="global",source="factory",vdom="root"} 0
fortigate_certificate_cmdb_references{name="Fortinet_CA_SSL",scope="vdom",source="factory",vdom="root"} 5
fortigate_certificate_cmdb_references{name="Fortinet_CA_Untrusted",scope="global",source="factory",vdom="root"} 0
fortigate_certificate_cmdb_references{name="Fortinet_CA_Untrusted",scope="vdom",source="factory",vdom="root"} 4
fortigate_certificate_cmdb_references{name="Fortinet_Factory",scope="global",source="factory",vdom="root"} 5
fortigate_certificate_cmdb_references{name="Fortinet_Factory",scope="vdom",source="factory",vdom="root"} 2
fortigate_certificate_cmdb_references{name="Fortinet_Factory_Backup",scope="global",source="factory",vdom="root"} 0
fortigate_certificate_cmdb_references{name="Fortinet_Factory_Backup",scope="vdom",source="factory",vdom="root"} 0

real	0m10.233s
user	0m0.009s
sys	0m0.000s
```

Now i'm using `telegraf 1.24.4` and it works, both `curl` and `telegraf` scrape.

If i change to `telegraf 1.25.0` the `curl` still works but `telegraf` can't scrape and throws that error:
```
E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by powersj** [comment]
> The expected result with curl is

1. I do not see any authentication in that request. Are you using any authentication with Telegraf? Can you please provide your full config and full logs.

> E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2. Does this error always show up? Has this ever worked before? Does it work on other URLs?

> Now i'm using telegraf 1.24.4 and it works, both curl and telegraf scrape.
> If i change to telegraf 1.25.0 the curl still works but telegraf can't scrape and throws that error:

3. Do you have a system proxy set? The only difference in versions I see is https://github.com/influxdata/telegraf/commit/215e8e030a34455605cff522280140eed8838df4

**Comment by ricardoleal** [comment]
> 1. I do not see any authentication in that request. Are you using any authentication with Telegraf? Can you please provide your full config and full logs.

I guess i've lead you into a wrong assumption.
Telegraf here don't make any authentication.
[fortigate_exporter](https://github.com/bluecmd/fortigate_exporter) has the authentication.

This works in this way:
- Register into fortigate_exporter the url and token auth;
- Telegraf make a query to fortigate_exporter.

So assuming this we have :

Fortigate exporter config.
```
# /etc/fortigate/fortigate.yaml 
"https://fortigate.local:8443":
  token: "2141234535325234edsfsdf"
  probes:
    exclude:
      - Wifi
```
Telegraf config:
```
[[inputs.prometheus]]
  urls = ["http://localhost:9710/probe?target=https://fortigate.local:8443"]
  response_timeout = "120s"
  metric_version = 2
```

> 
> > E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:9710/probe?target=fortigate.local:8443: Get "http://localhost:9710/probe?target=https://fortigate.local:8443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 
> 2. Does this error always show up? Has this ever worked before? Does it work on other URLs?
> 
> > Now i'm using telegraf 1.24.4 and it works, both curl and telegraf scrape.
> > If i change to telegraf 1.25.0 the curl still works but telegraf can't scrape and throws that error:
> 

The only error i've is this when using telegraf 1.25.0

> 3. Do you have a system proxy set? The only difference in versions I see is [215e8e0](https://github.com/influxdata/telegraf/commit/215e8e030a34455605cff522280140eed8838df4)

No just a normal EC2 instance, and if you make the curl outside of telegraf it works (in the same ec2 ofc).

**Comment by powersj** [comment]
Looking at the diff between [v1.24.4 and v1.25.0](https://github.com/influxdata/telegraf/compare/v1.24.4...v1.25.0) there were a few changes:

* [add proxy support](https://github.com/influxdata/telegraf/commit/215e8e030a34455605cff522280140eed8838df4) - your config doesn't show it, probably not relevant
* [add custom headers](https://github.com/influxdata/telegraf/commit/d4eda21742b0f06f8b106b094bfba28b0086964b) - you don't have any set, not relevant
* [setting default port](https://github.com/influxdata/telegraf/commit/9d5c879cac68f54c61ccfd328e7fdeb848d03f71) - this is for k8s monitoring, not relevant
* [allow scrape config](https://github.com/influxdata/telegraf/commit/c3562ae8b27cb9b382ec86d41e183156f3f18f3d) - this is for k8s monitoring, not relevant

Can you grab a trace of the networking to see what is going on?

**Comment by ZPascal** [comment]
Hi @powersj, we have the exact same error case with a similar setup.

## Setup:
- All applications are running in an Alpine 3.17 container
- Python self-developed Prometheus middlewear to cast metrics from the scraper and change them to a compliant Prometheus line protocol
- No authentication between middlewear and telegraph and all applications are configured within a "localhost" setup
- Curl call to middlewear metrics endpoint is possible and returns a valid result (response time < 10s) 
- Telegraf Prometheus plugin is set up with a timeout of 150s

### Process setup:
[![Process setup](https://mermaid.ink/img/pako:eNo9kEFPwzAMhf9KlBNI28pa6LYekBggLkxCjNuyg5c4baQ0qVKHaer630mFtJv9-en52QOXXiGvuLb-LBsIxD6_hRPu5fCDFusA-sjm8-frB9KVbe--gm-RGow92xmlLJ4Rwr1w20nE_lWvhx1SMLJnexmgw3DkM95iaMGotGkQjjHBk0mLglepVKghWhJcuDFJIZLfX5zkFYWIMx47BYRvBlKallcabH-j78qQDzdoPShM7cDp0k1n1aanZCm906aeeAw24Yao66ssm8aL2lATTwvp26w3avpB87spszIv15AXWK4KeCoKJU_LzVrnj0utVg_LHPg4jn9ftWuE?type=png)](https://mermaid.live/edit#pako:eNo9kEFPwzAMhf9KlBNI28pa6LYekBggLkxCjNuyg5c4baQ0qVKHaer630mFtJv9-en52QOXXiGvuLb-LBsIxD6_hRPu5fCDFusA-sjm8-frB9KVbe--gm-RGow92xmlLJ4Rwr1w20nE_lWvhx1SMLJnexmgw3DkM95iaMGotGkQjjHBk0mLglepVKghWhJcuDFJIZLfX5zkFYWIMx47BYRvBlKallcabH-j78qQDzdoPShM7cDp0k1n1aanZCm906aeeAw24Yao66ssm8aL2lATTwvp26w3avpB87spszIv15AXWK4KeCoKJU_LzVrnj0utVg_LHPg4jn9ftWuE)

#### Presumption:
- The timeout inside the plugin is not used by the http client (ill verfiy that. I've got a local setup to reproduce the case)

**Comment by ZPascal** [comment]
**FYI:** @powersj & @ricardoleal I found the problem and as I mentioned it is related to an unspecified timeout for the default http client. I have already solved the problem locally and will prepare a PR tomorrow to fix the issue also here.
