### ISSUE TITLE
[telegraf] Error running agent: starting input inputs.snmp_trap: listen udp :162: bind: address already in use

### ISSUE THREAD

**Issue by jcourt2006** [influxdata/telegraf#12489]
### Please direct all support questsions to slack or the forums. Thank you.

Hallo,
     I am using image: registry-all.docker.ing.net/telegraf:1.18.3
we cannot bind to UDP 162 using root inside.
Can you please help solve this issue.

**Comment by srebhan** [comment]
@jcourt2006 can you please check if port 162 is already used by something before starting Telegraf? Furthermore, can you make sure you do not have multiple `snmp_trap` plugins with the same port?
