### ISSUE TITLE
make docs to build all docs

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#12499]
### Use Case

When running `make docs` on a system, it currently only does that for plugins of your current operating system as this has been pointed out in https://github.com/influxdata/telegraf/pull/12426#issuecomment-1375917070.

### Expected behavior

The tool should build all docs regardless of current operating system.

### Actual behavior

The tool only builds the docs for plugins that work on current operating system.

### Additional info

Building for example Windows docs works fine with the following command: `GOOS=windows make docs`.

**Comment by powersj** [comment]
To embed the docs we run the following target in the makefile for each plugin type:

```makefile
go generate -run="readme_config_includer/generator$$" ./plugins/$*/...
```

which translates to:

```shell
go generate -run="readme_config_includer/generator$" ./plugins/inputs/...
go generate -run="readme_config_includer/generator$" ./plugins/outputs/...
go generate -run="readme_config_includer/generator$" ./plugins/processors/...
go generate -run="readme_config_includer/generator$" ./plugins/aggregators/...
go generate -run="readme_config_includer/generator$" ./plugins/secretstores/...
```

Per `go help generate` the `$GOOS` value *is* set when the generator is run, so our build tags are going to exclude plugins that are not supported for the user's value of `GOOS`.

Running the go generate 3x times for Windows, Linux, and Darwin seems excessive. @srebhan thoughts here?

**Comment by srebhan** [comment]
I have no idea on how to work around the `GOOS` thing besides really run the code multiple times _or_ have the generator tag in a non-OS dependent file i.e. without build flags...

**Comment by Hipska** [comment]
I tried with the 4 types on my machine and it runs fast enough IMHO. Only problem I had was figuring out how to run these steps multiple times in the makefile.

**Comment by powersj** [comment]
@Hipska can you take a look at https://github.com/influxdata/telegraf/pull/12503 thanks!

**Comment by Hipska** [comment]
That's also a way to achieve it 😄
