### ISSUE TITLE
Multiple config files for mqtt_consumer with only one common file for credentials

### ISSUE THREAD

**Issue by jkwim** [influxdata/telegraf#12505]
### Please direct all support questsions to slack or the forums. Thank you.

Since I could not find a clear answer elsewhere I am posting this request here. Pardon me.

I want to use multiple configuration files for mqtt_consumer plugin.

The structure looks like this:

```
[[inputs.mqtt_consumer]]
  client_id = "telegraf"
  username = "xxxxxx"
  password = "xxxxx"
  data_format = "json_v2"
  servers = [ "tcp://127.0.0.1:1883" ]
  topics = [ "some/+/topic" ]

[[inputs.mqtt_consumer.json_v2]]
    measurement_name = "mydata"
```

I have several files in the same format which defines the input plugin instances. At the moment I have different `client_id`'s in different files.

Is there a way to consolidate the login credentials so that only a single client_id & connection to MQTT server is used instead of multiple connections.

My ideal expectation is to be able to store the credentials and client_id in a single config file and only add  topics and JSON parsing config in multiple files. This is to facilitate easy maintenance like adding/deleting new datasets easily.

One more question is whether the `topics` parameter can be moved outside the `[[inputs.mqtt_consumer]]` in to a section further down.

```
[[inputs.mqtt_consumer]]
.
.
.
  topics = [ "some/+/topic" ]

```

**Comment by srebhan** [comment]
@jkwim I'm not sure if I fully get your request, but let me try to answer some of the points. Telegraf configuration is based on independent instances of plugins that are configured, so there is no "cross-reference" or "common sections". This being said, you can easily define a list of topics in one `mqtt_consumer` instance as `topics` is an array. The same holds for the JSON v2 parser, multiple instance on how to parse the data can be defined.
If you for some reason cannot do the list of topic and/or list of parsers approach, you can still define multiple plugins and reference a shared `username` and `password` from a [secret-store](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#secret-store-secrets). However, this will open multiple connections to your broker...

**Comment by jkwim** [comment]
> @jkwim I'm not sure if I fully get your request, but let me try to answer some of the points. Telegraf configuration is based on independent instances of plugins that are configured, so there is no "cross-reference" or "common sections". This being said, you can easily define a list of topics in one `mqtt_consumer` instance as `topics` is an array. The same holds for the JSON v2 parser, multiple instance on how to parse the data can be defined. If you for some reason cannot do the list of topic and/or list of parsers approach, you can still define multiple plugins and reference a shared `username` and `password` from a [secret-store](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#secret-store-secrets). However, this will open multiple connections to your broker...
> 
> Does that answer your questions?

Yes, you have answered my questions and it is clear.

Following are the things that I wanted:
1. Have different configuration files for different sets of data so that I can easily start/stop collection by renaming the files with a different extension
2 Avoid having to duplicate credentials in every file (ie. every instance of the plugin)

So in my current setup every config file creates a new instance and hence a new connection.

I have one additional question:

If I want to split the JSON v2 parsers of a single instance in to multiple files, is there a way to cross reference/point the two files together? Can the order of reading of the files be controlled by a file naming convention?

**Comment by srebhan** [comment]
No. You could use `data_format = "value"`  to store the payload as-is in a field and then use the parser processor, but not sure if you want to add this complexity...

**Comment by jkwim** [comment]
OK. Understood.

Thanks for the explanations!

**Comment by jkwim** [comment]
OK. Understood.

Thanks for the explanations!
