### ISSUE TITLE
UPSD: Some values are missing

### ISSUE THREAD

**Issue by lpaseenba** [influxdata/telegraf#12517]
### Relevant telegraf.conf

```toml
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "120s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
[[inputs.upsd]]
```

### Logs from Telegraf

```text
telegraf --config /etc/telegraf/telegraf.conf --input-filter upsd --debug --test 2>&1|sed "s/$HOSTNAME/redacted1/g"
2023-01-17T19:40:02Z I! Starting Telegraf 1.25.0
2023-01-17T19:40:02Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-01-17T19:40:02Z I! Loaded inputs: upsd
2023-01-17T19:40:02Z I! Loaded aggregators:
2023-01-17T19:40:02Z I! Loaded processors:
2023-01-17T19:40:02Z I! Loaded secretstores:
2023-01-17T19:40:02Z W! Outputs are not used in testing mode!
2023-01-17T19:40:02Z I! Tags enabled: host=sisko
2023-01-17T19:40:02Z D! [agent] Initializing plugins
2023-01-17T19:40:02Z D! [agent] Starting service inputs
2023-01-17T19:40:03Z D! [agent] Stopping service inputs
2023-01-17T19:40:03Z D! [agent] Input channel closed
2023-01-17T19:40:03Z D! [agent] Stopped Successfully
> upsd,host=sisko,model=SMART-UPS\ 3000\ RM\ XL,serial=QS0437220978,status_OL=true,ups_name=rm2 battery_charge_percent=100,battery_voltage=55.65,firmware="93.14.D",input_frequency=60,input_voltage=120.9,internal_temp=36.9,load_percent=12.4,nominal_battery_voltage=48i,output_voltage=121.5,status_flags=8i,time_left_ns=8340000000000i,ups_status="OL" 1673984403000000000
> upsd,host=sisko,model=SMART-UPS\ 3000\ RM\ XL,serial=QS0437220975,status_OL=true,ups_name=rm1 battery_charge_percent=100,battery_voltage=55.05,firmware="93.14.D",input_frequency=60,input_voltage=120.9,internal_temp=31.9,load_percent=19.2,nominal_battery_voltage=48i,output_voltage=120.9,status_flags=8i,time_left_ns=5820000000000i,ups_status="OL" 1673984403000000000
```

### System info

Centos 7 and Telegraf 1.25.0

### Steps to reproduce

1. aquire some different UPS models
2. analyze the output and note differences
3.
...

### Expected behavior

all or at least more values are recorded

### Actual behavior

several values are missing, for example:
- battery.date
- battery.runtime
- battery.runtime.low
- input.transfer.high
- input.transfer.low
- ups.delay.shutdown
- ups.delay.start

### Additional info

I attached sample output from `upsc` and `telegraf -debug` from 4 different UPS models.
The last one gives two lines in telegraf and that's ok since it has two UPSes (rm1 & rm2) but it's the same model so same info on both.

For example, sample4 is the one that's missing battery date because there it's only `battery.date` and no `battery.mfr.date` (no clue what the diff would be since it's also a `ups.mfr.date`)

[sample1_telegraf.txt](https://github.com/influxdata/telegraf/files/10438777/sample1_telegraf.txt)
[sample1_upsc.txt](https://github.com/influxdata/telegraf/files/10438778/sample1_upsc.txt)
[sample2_telegraf.txt](https://github.com/influxdata/telegraf/files/10438779/sample2_telegraf.txt)
[sample2_upsc.txt](https://github.com/influxdata/telegraf/files/10438780/sample2_upsc.txt)
[sample3_telegraf.txt](https://github.com/influxdata/telegraf/files/10438781/sample3_telegraf.txt)
[sample3_upsc.txt](https://github.com/influxdata/telegraf/files/10438782/sample3_upsc.txt)
[sample4_telegraf.txt](https://github.com/influxdata/telegraf/files/10438783/sample4_telegraf.txt)
[sample4_upsc.txt](https://github.com/influxdata/telegraf/files/10438784/sample4_upsc.txt)

**Comment by powersj** [comment]
Thanks for attaching examples!

All of these look like good candidates as new fields:

* battery.date - string (e.g. 18/04/22 or 2020/04/27)
* battery.runtime - number (e.g. 5820)
* battery.runtime.low - number (e.g. 300, -1)
* input.transfer.high - number (e.g. 139)
* input.transfer.low - number (e.g. 92)
* ups.delay.shutdown - number (e.g. 20, 180)
* ups.delay.start - number (e.g. 30, 060)

I'll take a look as a follow-up to the other upsd issue.

**Comment by powersj** [comment]
Hi @lpaseenba,

I put up https://github.com/influxdata/telegraf/pull/12543 which includes the float fixes found in #12516 as well as these additional fields. Do note that that to parse everything in float you need to enable `force_float = true` in your config.

Can you give the artifacts which will attach to that PR in the next 20-30mins a try and let me know if that gets all the fields as you expect them?

Thanks!

**Comment by lpaseenba** [comment]
Setup a new bucket to test it and it seems to work as expected. 
Of course it (binary and option) need to roll out everywhere at the same time since it does cause conflict otherwise.
This is because that until every binary+config is updated the float-only binary will probably always fail to send data since some values like "nominal_input_voltage" and others are (for us) currently stored as int and now goes as float.

Good part with influxdb is that in our case a new shard is created every day so we would be out of data for at most one day.

**Comment by lpaseenba** [comment]
Looking closer I see an issue with this image. When a ups doesn't provide value it still gets stored as 0. 
For example, one UPS doesn't provide ups.delay.start and it now get populated with a value of 0.0 which could in some settings generate alerts.

**Comment by powersj** [comment]
I pushed an update to ignore nil float values, can you give that a try once new artifacts are up? Thanks again!

**Comment by lpaseenba** [comment]
Ok, that seems to work, `ups_delay_start` is no longer added to the influxdb.
