### ISSUE TITLE
[outputs.mqtt] Extend support to native MQTT v5 protocol to the outgoing connection

### ISSUE THREAD

**Issue by serroba** [influxdata/telegraf#12526]
### Use Case

I would like to take better advantage of the MQTT v5 protocol. In particular, I would like to be able to defined an [Message Expiry Interval](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901064) and to also define [User Defined Properties](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901068)

### Expected behavior

I would like to have an extension of the current `[outputs.mqtt]` config, so I can define the Message Expiry Interval and the User Properties.

```
# Configuration for MQTT server to send metrics to
[[outputs.mqtt]]
  ## MQTT Brokers
  ## The list of brokers should only include the hostname or IP address and the
  ## port to the broker. This should follow the format `[{scheme}://]{host}:{port}`. For
  ## example, `localhost:1883` or `mqtt://localhost:1883`.
  ## Scheme can be any of the following: tcp://, mqtt://, tls://, mqtts://
  ## non-TLS and TLS servers can not be mix-and-matched.
  servers = ["localhost:1883", ] # or ["mqtts://tls.example.com:1883"]

  ## Protocol can be `3.1.1` or `5`. Default is `3.1.1`
  procotol = "5"
  [outputs.mqtt.v5]
  message_expiry_interval = $TIME
  [outputs.mqtt.v5.user_properties]
  foo=bar
```

### Actual behavior

The current behaviour only covers the common aspects between v3 and v5. There is no way to indicate any of the more advance features.

### Additional info

The current implementation of v5 is using the paho library. The library [already exposes as part of the interface all what we need](https://github.com/eclipse/paho.golang/blob/master/paho/cp_publish.go#L12). The question here really is about defining how we want to allow the configuration.

I am expanding the existent configuration of the output plugin, but this would lead to a rather awkward partial polymorphic implementation (only some features are actually polymorphic, the new ones aren't).

I don't know of a better approach though, so flexible on the actual implementation.

**Comment by powersj** [comment]
Hi,

Thanks for the interest and taking time to look into this.

@srebhan and I are good with proposal of a `v5` specific settings section, both with a) exposing publish properties + a map for user specified properties.

Looking forward to seeing a PR!

**Comment by serroba** [comment]
thank you @powersj 

I have had troubles finding time to actually start this work, probably will be able to do so at some point next week.
In the meantime, I'd like to show what I have in mind this work will look like from the config side of things:

```
[outputs.mqtt.v5]
  content_type = ""
  response_topic = ""
  message_expiry = 0
  topic_alias = 0

  [[outputs.mqtt.v5.user_properties]]
  key = "key1"
  value = "value1"

  [[outputs.mqtt.v5.user_properties]]
  key = "key2"
  value = "value2"
```

If you think we need to adjust things, please let me know
