### ISSUE TITLE
Input plugin "logstash" should support opensearch

### ISSUE THREAD

**Issue by gunzl1ng3r** [influxdata/telegraf#12534]
### Use Case

When using logstash to forward messages to "opensearch", the output is called `opensearch`, instead of `elasticsearch` which is currently hardcoded in the logstash input plugin

### Expected behavior

I would like the logstash plugin to cover both opensearch and elasticsearch

### Actual behavior

Currently `elasticsearch` is hardcoded in <https://github.com/influxdata/telegraf/blob/master/plugins/inputs/logstash/logstash.go#L271>

**Comment by powersj** [comment]
Hi,

> the output is called opensearch

When a user says "output" we are generally referring to one of the output plugins that is used. As we do not have an opensearch plugin (yet), what are you referring to?

**Comment by gunzl1ng3r** [comment]
Hi, let me clarify: the logstash output is called "opensearch".

The affected telegraf input plugin is "logstash".

Within this plugin, there is a part of the code that treats a logstash output differently when it is called "elasticsearch". (see the link to the code in the original post)

What I would like to achieve with this issue is that this part of the code does the same for "opensearch".

**Comment by powersj** [comment]
Take a look at https://github.com/influxdata/telegraf/pull/12536 and let me know if that gets you what you are after. There will be artifacts attached to that PR in the next 20-30mins that you can try out.

Please do give them a try and if you could provide some example output confirming it collects the opensearch data I would appreciate it.

Thanks

**Comment by gunzl1ng3r** [comment]
Hey, thanks for the super fast update.

The metrics are now discovered.

![grafik](https://user-images.githubusercontent.com/6085597/214104385-ce9550a7-3786-4384-a4fd-9f9a4ce4513d.png)

As I understand the code it comes from this part of the output and provides access to the part concerning the "bulk_requests" and "documents".

```
"outputs": [
  {
    "id": "c144e1c4c27e84ae4d95b5faa6f635c858eb30ceb2f4b1ef1b0616b0976da9d0",
    "events": {
      "duration_in_millis": 47570205,
      "in": 84732658,
      "out": 84732658
    },
    "name": "opensearch",
    "documents": {
      "successes": 84732658
    },
    "bulk_requests": {
      "responses": {
        "200": 1003468
      },
      "successes": 1003468
    }
  }
]
```

**Comment by powersj** [comment]
Thanks for confirming!
