### ISSUE TITLE
Improved logging to identify which snmp target is slow

### ISSUE THREAD

**Issue by tnxfi** [influxdata/telegraf#12530]
### Use Case

Currently inputs snmp logs only that a collection is skipped. It doesn't give any information on which collection took too long and was skipped.

It would be nice to get information on the agent which took too much time.

Currently I have about 150 snmp items in /etc/telegram/telegram.d/, each is in its own file. I'm seen 1-4 "Collection took longer than expected; not complete after interval of 1m0s" -messages per 60s interval. This seems to affect hosts that are not the source of the actual collecting problem. I'm assuming this is because a slow host is blocking a thread where the affected host is also running.

If I knew which host is slow, I could change the polling interval for it or possibly even leave it out. But currently identification is hard without any hints from the input poller.

### Expected behavior

Output could be improved to include agent taking too much time (for example: udp://192.168.1.1:161).
There are few ways of doing this, debug output could contain timing information on each polled target, which would help identify ones that take a long time. Or if there is clear single culprit identifiable, the output could name it.

### Actual behavior

Currently inputs.snmp gives generic error when a target takes too long to collect. Even on debug-logging the information is very generic.
```
Jan 21 09:28:00 amanda-tnnet-fi telegraf[144873]: 2023-01-21T07:28:00Z D! [inputs.snmp] Previous collection has not completed; scheduled collection skipped
Jan 21 09:28:00 amanda-tnnet-fi telegraf[144873]: 2023-01-21T07:28:00Z D! [inputs.snmp] Previous collection has not completed; scheduled collection skipped
Jan 21 09:28:00 amanda-tnnet-fi telegraf[144873]: 2023-01-21T07:28:00Z W! [inputs.snmp] Collection took longer than expected; not complete after interval of 1m0s
Jan 21 09:28:00 amanda-tnnet-fi telegraf[144873]: 2023-01-21T07:28:00Z W! [inputs.snmp] Collection took longer than expected; not complete after interval of 1m0s
```

### Additional info

As a workaround, is there any way to increase the amount of threads Telegraf uses for snmp-polling? Currently it seems that there is thread pool model and slow devices might block the amount of workers in the pool. I know there are a few slow devices, which give out snmpwalks veeeery slooowly when running them manually. Current system has 4 cpu's, which are not saturated. But if the pool is inherited from that amount, it doesn't take many slow devices to jam the pool.

**Comment by powersj** [comment]
> Previous collection has not completed; scheduled collection skipped

This message comes from the [agent itself](https://github.com/influxdata/telegraf/blob/e9356b5cb3565ca28ad15c89ce71ac989ed593a7/agent/agent.go#L504) not the plugin. It is triggered when the current collection interval's ticker elapses and the collection has not finished. The message is generic since the agent does not have information about what the plugin is doing and the plugin itself is still running without knowledge of the interval.

> Output could be improved to include agent taking too much time (for example: udp://192.168.1.1:161).

The mechanism commonly used in telegraf plugins to catch long running tasks is a timeout. I am not super familiar with inner workings of our snmp plugins, but I do see a timeout config option in `inputs.snmp`. @Hipska can you help me understand how the `timeout` parameter could play into this? Do we have any other existing issues related to this?

Thanks!

**Comment by tnxfi** [comment]
In my understanding, the timeout in inputs.snmp refers to the lower level timeout in actual snmp-commands againts the devices.

If the current notification system doesn't support easy access to information on which device is causing the issue, would it be possible to print out some timing information from the snmp-plugin itself? For example print time used for gathering information per device (an entry in agents list) when using debug-level logging.

Any sysadmin should know the feeling, when they see a logline that reads "something took longer than expected" and the only thing you know, is that the haystack is a few hundred devices. For some, it may be thousands,

**Comment by Hipska** [comment]
Hi @tnxfi, see the blog post [Telegraf Best Practices: SNMP Plugin](https://www.influxdata.com/blog/telegraf-best-practices-snmp-plugin/?utm_source=github&utm_medium=social) where we advise to split the snmp input config for each agent. Additionally, you can add `alias` to it so you know exactly which device is slow in responding to requests. I hope this helps.

**Comment by tnxfi** [comment]
I have split the configuration right after initial setup, as having multiple devices in one file was just a bunch of problems.
Somehow I had thought that alias was only relevant for outputs, not for log files. 
Good tip, thank you. I did small script to convert the device names I had in filenames to aliases and truly now I get output with names: [inputs.snmp::tks1.jkl].

Considering I had been to the Best practices page multiple times and read the documentation page on config options and I still had no clue setting an alias might help logging, it might be useful to give bit better pointers in either of those.
Of course later generations will likely find this bugtracker entry, which may point them to the right direction.
