### ISSUE TITLE
Linux package signing key rotation

### ISSUE THREAD

**Issue by jdstrand** [influxdata/telegraf#12542]
We're rotating our Linux package signing key on 2023-01-26. Please see https://www.influxdata.com/blog/linux-package-signing-key-rotation/ for details.

**Comment by powersj** [comment]
next steps: land PRs tomorrow after repo is updated

**Comment by jdstrand** [comment]
> We're in the process of updating https://repos.influxdata.com/influxdb.key now to contain the updated revoked key.

This is now done.
