### ISSUE TITLE
unsupported input type for mean aggregate: string

### ISSUE THREAD

**Issue by JoeH20** [influxdata/telegraf#12545]
### Please direct all support questsions to slack or the forums. Thank you.

When attempting to display the uptime_format field I get this message on the screen: 
unsupported input type for mean aggregate: string

from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "system")
  |> filter(fn: (r) => r["_field"] == "uptime_format")
  |> filter(fn: (r) => r["host"] == "MY_HOST")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")

**Comment by powersj** [comment]
Hi,

Looking at the [system README](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/system), the field `uptime_format` is a string. As such that is not something you can aggregate on. That field was also deprectated a while back, so you probably mean to use the `uptime` field instead.
