### ISSUE TITLE
[inputs.opcua] How to convert nodeid string to expected config?

### ISSUE THREAD

**Issue by axi92** [influxdata/telegraf#12553]
### Please direct all support questsions to slack or the forums. Thank you.

I have the same problem as here described #12396
My NodeID string is this: `ns=6;s=::AsGlobalPV:gDIMerker_Map_1`
How do I get the config for the input.opcua from this?

I tried this:
```
  nodes = [
    {name="gDIMerker_Map_1", namespace="6", identifier_type="s", identifier="gDIMerker_Map_1"},
  ]
```
But that does not work.

![image](https://user-images.githubusercontent.com/1394837/214802234-1559c3eb-958c-4ab5-8fbc-acda347c2768.png)
(B&R)

**Comment by R290** [comment]
Try this:

```
  nodes = [
    {name="gDIMerker_Map_1", namespace="6", identifier_type="s", identifier="::AsGlobalPV:gDIMerker_Map_1"},
  ]
```

**Comment by axi92** [comment]
Now I get this error:
`E! [inputs.opcua] Error in plugin: error in Client Connection: User does not have permission to perform the requested operation. StatusBadUserAccessDenied (0x801F0000)`
