### ISSUE TITLE
[inputs.vsphere] HTTP/HTTPS Proxy setting

### ISSUE THREAD

**Issue by nussi1000** [influxdata/telegraf#12557]
### Use Case

We use a HTTP proxy to reach vSphere. 
To collect the Metrics with vSphere input and Telegraf there is a setting needed to specify the HTTP_PROXY and HTTPS_PROXY Setting.

### Expected behavior

It would be nice to configure the two settings HTTP_PROXY and HTTPS_PROXY in the Telegraf Configuration

### Actual behavior

Currently this is not possible

**Comment by nussi1000** [comment]
Hi powersj
Thanks! This worked for me for the [input.vsphere]. 
But now i face issues with the [outputs.influxdb].
InfluxDB is not behind a proxy. But it seems that it takes the HTTP_PROXY Variable into account. I tried to unset it with http_proxy configuration in telegraf.conf by doing: http_proxy=''
This did not solve the issue.

Error after enabling debug mode:

`2023-01-26T22:11:35Z E! [outputs.influxdb] when writing to [http://influxdb:9000]: Post http://influxdb:9000/write?db=db_name: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2023-01-26T22:11:35Z D! [outputs.influxdb] Buffer fullness: 3399 / 10000 metrics
2023-01-26T22:11:35Z E! [agent] Error writing to outputs.influxdb: could not write any address`

**Comment by powersj** [comment]
It appears setting `http_proxy=""` means it shows up as nil and not "". As such the [environment proxy will be picked here](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/http.go#L150-L155).

@srebhan I thought a string would resolve to empty string?

**Comment by srebhan** [comment]
I think the issue is that an empty string is the `nil` value for string. Therefore, to distinguish the unset vs. explicitly empty case you would need to make the variable a string pointer (`*string`). If the _pointer_ is `nil` the string was _not_ set, otherwise, if the pointer's string _value_ is `nil` it was explicitly set to an empty string.

**Comment by nussi1000** [comment]
Thanks for the explanation.
Is this planned to be addressed in an upcoming version?

**Comment by srebhan** [comment]
If someone provides a PR... Any volunteers?

**Comment by nussi1000** [comment]
@srebhan 
It works perfectly! Thanks
