### ISSUE TITLE
Repository https://repos.influxdata.com/ubuntu not available

### ISSUE THREAD

**Issue by Slm0n87** [influxdata/telegraf#12558]
### Relevant telegraf.conf

```toml
-
```

### Logs from Telegraf

```text
-
```

### System info

Tested with Ubuntu 20.04 and Ubuntu 22.04

### Steps to reproduce

Install repository like in documentation for Ubuntu, see https://docs.influxdata.com/telegraf/v1.21/introduction/installation/
run apt update

### Expected behavior

Installation should work

### Actual behavior

# apt update
Ign:1 https://repos.influxdata.com/ubuntu jammy InRelease
Err:2 https://repos.influxdata.com/ubuntu jammy Release
  404  Not Found [IP: 52.222.236.105 443]
...
Reading package lists... Done
E: The repository 'https://repos.influxdata.com/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Additional info

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

**Comment by powersj** [comment]
Please see the pinned issue, https://github.com/influxdata/telegraf/issues/12542, the GPG rotation is occurring today.
