### ISSUE TITLE
[[inputs.win_perf_counter]] UsePerfCounterTime is timezone-sensitive

### ISSUE THREAD

**Issue by eadwu** [influxdata/telegraf#12562]
### Use Case

Something like `timestamp_timezone` for `win_perf_counter`. This should be rare but came across this while messing with Mimir spamming `err-mimir-too-far-in-future` errors.

Tested in WSL, where VM is in a different timezone from Host (Windows), and due to the time difference from timezones.

### Expected behavior

Normalized timestamps to Local or UTC time.

### Actual behavior

Timestamps are relative to Windows system, which may or may not be consistent correct in respect to the receiving end.

### Additional info

```
Jan 27 17:11:43 mimir[]: level=error caller=push.go:130 user=anonymous msg="push error" err="rpc error: code = Code(400) desc = received a sample whose timestamp is too far in the future, timestamp: 1674871010000 series: 'win_proc_Percent_Processor_Time' (err-mimir-too-far-in-future). To adjust the related per-tenant limit, configure -validation.create-grace-period, or contact your service administrator."
```

```
Date(1674871010000)
'Fri Jan 27 2023 21:06:42'
```

Timestamp in and of themselves are 100% accurate.

Currently just popped `validation.create-grace-period` (in mimir) up to 24h to prevent this.

**Comment by powersj** [comment]
Hi,

I put up #12566 which adds a config option to set the timestamp timezone as either "local", the default, or to "utc". Could you give the artifacts attached to that PR a try? They should be attached as a comment in the next 20-30mins?

Thanks!

**Comment by eadwu** [comment]
Just ran with the following config and got the same timestamps for both rows. Looks like it might be a problem with the mimir side. Not sure why if all timestamps should be UTC but only the `win_perf_counters` get rejected.

Will get back once I have more information.

```
[agent]
debug = true
flush_interval = "40s"
interval = "10s"
metric_batch_size = 32768
metric_buffer_limit = 524288
round_interval = true

[inputs]
[[inputs.win_perf_counters]]
TimestampTimezone = "local"

[[inputs.win_perf_counters.object]]
Counters = ["Available Bytes"]
Instances = ["------"]
Measurement = "win_mem"
ObjectName = "Memory"

[[inputs.win_perf_counters]]
TimestampTimezone = "utc"

[[inputs.win_perf_counters.object]]
Counters = ["Available KBytes"]
Instances = ["------"]
Measurement = "win_mem"
ObjectName = "Memory"

[outputs]

[[outputs.file]]
files = ["stdout"]
data_format = "prometheus"
prometheus_export_timestamp = true
```

**Comment by powersj** [comment]
> Are the metrics usually in local time or UTC time?

Currently released versions of telegraf would use the local timestamp.

**Comment by powersj** [comment]
@eadwu were you ever able to test the PR? Do you know if it resolves your issue?

**Comment by eadwu** [comment]
I stopped using mimir since I couldn't get it working the way I wanted but I'll try again this week if I have spare time.

**Comment by powersj** [comment]
I'm going to close this the PR, but if it is something you want to re-visit let me know.
