### ISSUE TITLE
timezone configuration to xpath parser

### ISSUE THREAD

**Issue by dealerj1** [influxdata/telegraf#12567]
### Use Case

Example input XML `<Statistics><S T="2022-12-31 22:46:33" V="21,600"/></Statistics>`

```
[[inputs.http]]
   urls = ...
   data_format = "xml"
   method = ...
   [[inputs.http.xpath]]
     metric_name = "'temperature'"
     metric_selection = "Statistics/S"
     timestamp = "@T"
     xpath_timezone = "Europe/Budapest"
```
This stores the T XML attribute in UTC.

### Expected behavior

There is a way to set the timezone. Otherwise, it will be treated as UTC.

### Actual behavior

Currently, the plugin is unable to convert the date to local time.

### Additional info

Please assign the issue to srebhan.

**Comment by powersj** [comment]
@srebhan looks like there is no timezone option with the xpath parser currently? Is this as simple as adding the timezone parameter, similar to [csv parser](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/csv/parser.go#L44) or in [json_v2](https://github.com/influxdata/telegraf/blob/e84bc0c590086dc47c1da6ae874b4c6d9e6cafbd/plugins/parsers/json_v2/parser.go#L114)?

**Comment by srebhan** [comment]
@dealerj1 can you please test the binary built in PR #12820 once CI finished the tests? Let me know if this is what you had in mind!
