### ISSUE TITLE
The timeout parameter inside the Prometheus plugin is wrongly named to parse the timeout directly from the configuration

### ISSUE THREAD

**Issue by ZPascal** [influxdata/telegraf#12565]
### System info

Telegraf 1.25.0

### Change request

It only changes inside a code line to make it not necessary to forward the timeout and to use it directly from the configuration. 

### Expected behavior

The parameter should be parsed directly and not converted like [this](https://github.com/influxdata/telegraf/blob/4b1b74fefff050e034cb69656e730c11db150c6e/plugins/inputs/prometheus/prometheus.go#L166) line handle it.

### Actual behavior

I've prepared a fix for the [root cause](https://github.com/influxdata/telegraf/issues/12485) to solve the corresponding case. The parameter is forwarded to the corresponding library to not break someone's use case. In future it would be better to parse the configuration as timeout directly from the forwarded configuration.

### Background

We've already discussed the topic here: https://github.com/influxdata/telegraf/pull/12559#discussion_r1089055806

From my understanding, the parameter should be replaced in the future with a new name called `timeout` to directly parse the configuration. I've decided to handle it not directly inside this [PR](https://github.com/influxdata/telegraf/pull/12559#pullrequestreview-1275196432) because it's a breaking change.

**Comment by powersj** [comment]
next steps: deprecate the old value, create new, better named option

**Comment by ZPascal** [comment]
@powersj I would recommend naming the parameter classical as `timeout`. Should I prepare the PR for the next major release?

**Comment by powersj** [comment]
> recommend naming the parameter classical as timeout

Sounds good

> Should I prepare the PR for the next major release?

Would happily take a PR!

**Comment by ZPascal** [comment]
@powersj Great, I'll prepare the PR for it.
