### ISSUE TITLE
MQTT.output format optimization

### ISSUE THREAD

**Issue by myg1th0b** [influxdata/telegraf#12589]
### Use Case

An increasing amount of IoT devices support MQTT these days, however some are not (due to age or design or other reasons). Other popular alternatives to MQTT are JSON http or Modbus TCP for example. 

In a typical smart home or any business environment with many different devices there is a good use case for Telegraf to act as a centralized communications bus (a bit like Kafka), especially since there is already a vast amount of input and output plugins available. This consolidates many different devices like power inverters, thermostats, heating pumps, etc. into a single tool which then can both write the timeseries data to influxdb but also reformat the various inputs to a consistent outplut like for example mqtt which then is easy to consume by other tools, like automation (iobroker, Homeassistant, openHAB, etc..)

My proposal is to optimize the mqtt.output feature such that the resulting mqtt messages are more aligned with common practices for mqtt where you often see a value/key pair having forming it's own (sub-)topic. Currently you would most likely see MQTT messages in a format where you have a topic like 

```
/source-device/type-of-data/key/value
/thermostat_A/room/temperature/18
/thermostat_A/room/humidity/45
```

This would encompassing to take in different key:value data pairs from the input (e.g. modbus) and transfer them into some logic and flexible mqtt topic structure like explained above. 

### Expected behavior

Take input of key:value data pairs and optionally any descriptive tags from incoming source data such as for example modbus or http json and construct an mqtt.output with a format that is easy to understand and parse for any mqtt consumer.

The expected format would be like illustrated above for thermostat that provides for a room temperature and humidity for example:
The topic would for example come from:
device-name (probably form the input plugin device name tag)
room either a tag for this value or optionally inserted by the user in the config file
the last two values would be key and value from the measurement.

```
/thermostat_A/room/temperature/18
/thermostat_A/room/humidity/bedroom/45
```

### Actual behavior

Currently for example in my case the modbus plugin creates a contiguous stream of data (tag key value, ...) which are all posted into a single mqtt topic. for example:

/telegraf/modbus/thermostat/temperature 18, humidity 45

### Additional info

Let me know if you want me to provide an actual example of modbus data and how I'd like it structured.

**Comment by srebhan** [comment]
@myg1th0b can you please try the binary built in #12697 once CI finished the build and let me know if that fixes your problem!?
