### ISSUE TITLE
MongoDB input errors are badly formatted

### ISSUE THREAD

**Issue by ozon2** [influxdata/telegraf#12598]
### Relevant telegraf.conf

```toml
-
```

### Logs from Telegraf

```text
-
```

### System info

Telegraf 1.25.1

### Steps to reproduce

Run Telegraf with with a MongoDB input and a MongoDB server that requires credentials.

### Expected behavior

I expect a helpful log message telling me I need to configure authentication.

### Actual behavior

The log is badly formatted and hard to understand:
```
failed to gather data: %!w(mongo.CommandError={13 command serverStatus requires authentication [] Unauthorized <nil> [236 0 0 0 17 111 112 101 114 97 116 105 111 110 84 105 109 101 0 1 0 0 0 100 31 201 99 1 111 107 0 0 0 0 0 0 0 0 0 2 101 114 114 109 115 103 0 45 0 0 0 99 111 109 109 97 110 100 32 115 101 [...] 0 0 0]})
```

**Comment by powersj** [comment]
next steps: finish review of #12599
