### ISSUE TITLE
[feature request] version checking

### ISSUE THREAD

**Issue by beckettsean** [influxdata/telegraf#1259]
### Proposal:

On startup, if connection to the configured InfluxDB or Kapacitor fails, check for a version mismatch rather than reporting a potentially cryptic error.
### Current behavior:

If there's an incompatibility between Telegraf and another TICK component the error message may be cryptic or not even logged until a particular action is attempted and fails.
### Desired behavior:

On startup, Telegraf detects it is connected to an older, potentially incompatible database and issues a warning in the logs. Potentially if the mismatch is very great, Telegraf exits with the error.
### Use case:

Makes version mismatch issues much easier to diagnose and saves time and confusion.

**Comment by sparrc** [comment]
how do I get the version of influxdb & kapacitor?

**Comment by beckettsean** [comment]
https://docs.influxdata.com/kapacitor/v0.13/api/api/#ping
https://docs.influxdata.com/influxdb/v0.13/concepts/api/#ping

**Comment by sparrc** [comment]
thanks, but are there any known version mismatches? I'm not really sure what version differences I'd be looking for.

**Comment by beckettsean** [comment]
It's more of a kapacitor issue. I don't know that there have been many breaking changes to the write path since 0.10, nor are there any planned for 1.0 that I know of.

However, a redesigned line protocol is likely eventually, and that would be a breaking change for telegraf. 

I think the best thing would be for telegraf to compare the InfluxDB version with its own, and issue a log or STDOUT warning if the versions don't match.

**Comment by danielnelson** [comment]
Lets tackle this when InfluxDB 2.0 comes out, or if we have an incompatibility we need to check for.
