### ISSUE TITLE
[inputs.internet_speed] ping test failed : x509: certificate has expired

### ISSUE THREAD

**Issue by Xer69** [influxdata/telegraf#12595]
### Relevant telegraf.conf

```toml
[[inputs.internet_speed]]
  ## This plugin downloads many MB of data each time it is run. As such
  ## consider setting a higher interval for this plugin to reduce the
  ## demand on your internet connection.
  interval = "5m"

  ## Enable to reduce memory usage
  # memory_saving_mode = false

  ## Caches the closest server location
  # cache = true
```

### Logs from Telegraf

```text
2023-02-02T09:31:04Z D! [inputs.internet_speed] Found server: [16835]     2.10km 
Lyon (France) by La Fibre Pro
2023-02-02T09:31:04Z D! [inputs.internet_speed] Starting Speed Test
2023-02-02T09:31:04Z D! [inputs.internet_speed] Running Ping...
2023-02-02T09:31:08Z E! [inputs.internet_speed] Error in plugin: ping test failed: Get "https://speedtest.muona.com:8080/speedtest/latency.txt": x509: certificate has expired or is not yet valid: current time 2023-02-02T09:31:08Z is after 2022-08-28T12:56:43Z
```

### System info

image: telegraf:1.25.1

### Docker

  ```
  telegraf:
    image: telegraf:1.25.1
    user: telegraf:995
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
```

### Steps to reproduce

1. docker-compose up -d
2. docker-compose logs telegraf

### Expected behavior

I expect Download/Upload/Latency to be mesured

### Actual behavior

The server don't provide a valid certificat.
As I see, it is not yet possible to force another server : https://github.com/influxdata/telegraf/issues/11625

**Comment by srebhan** [comment]
@Xer69 what do you expect us to do? The certificate of that server is invalid, so you should maybe contact those guys in order to renew their cert...

**Comment by Xer69** [comment]
thank you @powersj ! I'll wait the release to test this but sound really great :)
@srebhan I ask them to update their cert or leave the speedtest service ;) (but I prefer the option to blacklist their server)
