### ISSUE TITLE
processors.starlark and aggregators.basicstats will be core when used together

### ISSUE THREAD

**Issue by iceyfighting** [influxdata/telegraf#12649]
### Relevant telegraf.conf

```toml
[[inputs.execd]]
  command = ["xx", "-config", "/home/work/xx.conf", "-poll_interval", "10s"]
  name_override = "info"
  signal = "none"


[[processors.starlark]]
    script = "data_preprocess.star"


[[aggregators.basicstats]]
   period = "60s"
   drop_original = true
   stats = ["rate"]

[[processors.rename]]
  [[processors.rename.replace]]
    field = "pkts_rate"
    dest = "pps"
```

### Logs from Telegraf

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa15d73]

goroutine 74 [running]:
panic({0x525ffc0, 0x97ca400})
        /home/go19/src/runtime/panic.go:987 +0x3ba fp=0xc00eab13c0 sp=0xc00eab1300 pc=0x43bcfa
runtime.panicmem(...)
        /home/go19/src/runtime/panic.go:260
runtime.sigpanic()
        /home/go19/src/runtime/signal_unix.go:835 +0x2f6 fp=0xc00eab1410 sp=0xc00eab13c0 pc=0x452b36
github.com/influxdata/telegraf/plugins/common/starlark.FieldDict.Items({0x0?})
```

### System info

Telegraf 1.25.0 

### Docker

no

### Steps to reproduce

1. The first step is to preprocess the data with processors.starlark
2. The second step is to calculate the data with aggregators.basicstats
3. The third step is to rename the field with processors.rename
...

### Expected behavior

After the data is processed normally, it is pushed to output

### Actual behavior

When I execute the above three steps, startlark executes twice, causing the program core to be in the starlark library function

### Additional info

ss

**Comment by srebhan** [comment]
To debug this I would need the referenced script and at least one data-sample that triggers the issue...

**Comment by iceyfighting** [comment]
You can customize any data, as long as it conforms to the conf stage defined above. because in the Aggregators phase, the Processors phase will be executed, startlark(Processors) will be used, and startlark will also be used in the Processors phase, so starlark will be executed twice, resulting in competition between different coroutines, and the final program will be Hangs due to memory problem

**Comment by iceyfighting** [comment]
WARNING: DATA RACE
Read at 0x00c00045a670 by goroutine 82:
  go.starlark.net/starlark.Call()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:1235 +0x66b
  go.starlark.net/starlark.(*Function).CallInternal()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/interp.go:325 +0x4c5a
  go.starlark.net/starlark.Call()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:1218 +0x3e9
  github.com/influxdata/telegraf/plugins/common/starlark.(*StarlarkCommon).Call()
      /home/go_workspace/telegraf/plugins/common/starlark/starlark.go:139 +0x184
  github.com/influxdata/telegraf/plugins/processors/starlark.(*Starlark).Add()
      /home/go_workspace/telegraf/plugins/processors/starlark/starlark.go:56 +0x1bb
  github.com/influxdata/telegraf/models.(*RunningProcessor).Add()
      /home/go_workspace/telegraf/models/running_processor.go:95 +0x118
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1()
      /home/go_workspace/telegraf/agent/agent.go:569 +0x511
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func2()
      /home/go_workspace/telegraf/agent/agent.go:577 +0x47

Previous write at 0x00c00045a670 by goroutine 84:
  go.starlark.net/starlark.Call()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:1213 +0x2f6
  go.starlark.net/starlark.(*Function).CallInternal()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/interp.go:325 +0x4c5a
  go.starlark.net/starlark.Call()
      /home/go/pkg/mod/go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:1218 +0x3e9
  github.com/influxdata/telegraf/plugins/common/starlark.(*StarlarkCommon).Call()
      /home/go_workspace/telegraf/plugins/common/starlark/starlark.go:139 +0x184
  github.com/influxdata/telegraf/plugins/processors/starlark.(*Starlark).Add()
      /home/go_workspace/telegraf/plugins/processors/starlark/starlark.go:56 +0x1bb
  github.com/influxdata/telegraf/models.(*RunningProcessor).Add()
      /home/go_workspace/telegraf/models/running_processor.go:95 +0x118
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1()
      /home/go_workspace/telegraf/agent/agent.go:569 +0x511
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func2()
      /home/go_workspace/telegraf/agent/agent.go:577 +0x47
Goroutine 82 (running) created at:
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors()
      /home/go_workspace/telegraf/agent/agent.go:562 +0x72
  github.com/influxdata/telegraf/agent.(*Agent).Run.func2()
      /home/go_workspace/telegraf/agent/agent.go:163 +0x3b0


Goroutine 84 (running) created at:
  github.com/influxdata/telegraf/agent.(*Agent).runProcessors()
      /home/go_workspace/telegraf/agent/agent.go:562 +0x72
  github.com/influxdata/telegraf/agent.(*Agent).Run.func4()
      /home/go_workspace/telegraf/agent/agent.go:181 +0x2c4


==================

**Comment by powersj** [comment]
> You can customize any data, as long as it conforms to the conf stage defined above.

This is especially unhelpful. While I am thankful you at least provided a config, it is far more effective when the config is something we can actually use without having to take it apart and figure out what you were doing.

> The first step is to preprocess the data with processors.starlark
> The second step is to calculate the data with aggregators.basicstats
> The third step is to rename the field with processors.rename

This is not the execution flow. In Telegraf, the processors are *all* run, and then the aggregators are run, and then *all* the processors are run again. See #7993. A more correct list is:

> The first step is to preprocess the data with processors.starlark
> The second step is to rename the field with processors.rename
> The third step is to calculate the data with aggregators.basicstats
> The fourth step is to preprocess the data with processors.starlark
> The fifth step is to rename the field with processors.rename

You can confirm this using logging in the starlark processor, you will see the fields are called "pps", not "pkts_rate".

Given the data race is called out in your starlark script I would be interested in seeing it + seeing some example data.

**Comment by powersj** [comment]
For the record here is my attempt locally, so clearly I am missing some part of this:

```json
{
  "pkts_rate": 33
}

```

```toml
[[inputs.file]]
   files = ["input.json"]
   data_format = "json"

[[processors.starlark]]
  source = '''
def apply(metric):
  return metric
'''

[[aggregators.basicstats]]
   period = "60s"
   drop_original = true
   stats = ["rate"]

[[processors.rename]]
  [[processors.rename.replace]]
    field = "pkts_rate"
    dest = "pps"

[[outputs.file]]
```

```s
❯ ./telegraf --config config.toml 
2023-02-10T14:14:46Z I! Starting Telegraf 1.26.0-4d0f0598
2023-02-10T14:14:46Z I! Available plugins: 230 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-02-10T14:14:46Z I! Loaded inputs: file
2023-02-10T14:14:46Z I! Loaded aggregators: basicstats
2023-02-10T14:14:46Z I! Loaded processors: rename starlark
2023-02-10T14:14:46Z I! Loaded secretstores: 
2023-02-10T14:14:46Z I! Loaded outputs: file
2023-02-10T14:14:46Z I! Tags enabled: host=ryzen
2023-02-10T14:14:46Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ryzen", Flush Interval:10s
file,host=ryzen pps_rate=0 1676038560000000000
file,host=ryzen pps_rate=0 1676038620000000000
file,host=ryzen pps_rate=0 1676038680000000000
file,host=ryzen pps_rate=0 1676038740000000000
file,host=ryzen pps_rate=0 1676038800000000000
```

**Comment by iceyfighting** [comment]
Because my side is the production traffic data, and the data is pulled every minute, so the input on my side is a command to be obtained regularly. The format of the obtained data is roughly as follows:
{"rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0", tag1: A, tag2:B, tag3:C}
The data enters telegraf in the form of field, and processors.starlark mainly distinguishes the data from the field field into the tag field


def apply(metric):
   for k, v in metric.fields.items():
   if k in tag_string_list:
   metric.tags[k] = v
   metric.fields.pop(k)
  return metric

**Comment by powersj** [comment]
> The data enters telegraf in the form of field, and processors.starlark mainly distinguishes the data from the field field into the tag field

Don't use starlark for this. Use a [converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter) to convert an array of string fields into tags. It is faster, more efficient, and ensures you don't mess something up with the starlark processor:

```toml
[[processors.converter]]
  [processors.converter.fields]
    string = ["fieldname", "otherfield"]
```

**Comment by iceyfighting** [comment]
But there are nested dictionaries in my field, such as: in: {"field1":0, field2: 2, "tag1": "nice", "tag2":"good"}, which can be supported by the converter processor What about parsing and converting?

**Comment by powersj** [comment]
I can only go off of what you share with me and what you showed in your comment yesterday demonstrates taking a string field and converting it to a tag. As I said in that message, using starlark for that is inefficient and error prone. Now your most recent message shows that same starlark code, but with additional changes.

If you wanted to parse JSON more efficiently you could/should also be looking at the JSONv2 which is great at handling nested JSON objects in your original data parsing.

If you are not going to share you complete config and not share a way to reproduce this issue, then I am going to close this issue.

**Comment by iceyfighting** [comment]
# Example Input:
`{"host":"host1","name":"data","rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0", "in":"no"} `或 
when "in" field is not equal to "no" , the input will add  "in":{"bw":"1024K", "out_pkts_pass": "1234", "out_bytes_pass": "23456"},  otherwise it will not be added
`{"host":"host1","name":"data","rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0", "in":{"bw":"1024K", "out_pkts_pass": "1234", "out_bytes_pass": "23456"}} `

when "log_info" field exists, the input will add  "log_info": {"info":{"error_input_bytes": "123", "error_input_pkts": "1234", "notice_input_bytes": "3", "notice_input_pkts": "4"}}},  otherwise it will not be added

`{"host":"host1","name":"data","rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0", "in":{"bw":"1024K", "out_pkts_pass": "1234", "out_bytes_pass": "23456"}, "log_info": {"info" :{"error_input_bytes": "123", "error_input_pkts": "1234", "notice_input_bytes": "3", "notice_input_pkts": "4"}} }`

# Example Output:
# 
```
{"host":"host1","name":"data","tx_bytes":"0","tx_pkt":"0", "in":"no"}
 {"host":"host1","name":"data","rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0",  "bw":"1024K", "out_pass_pps": "1234", "out_pass_bps": "23456"} 
{"host":"host1","name":"data","rx_bytes":"10","rx_pps":"0","timestamp":1676351945,"tx_bytes":"0","tx_pkt":"0", "bw":"1024K", "out_pkts_pass": "1234", "out_bytes_pass": "23456" , "log_info_error_input_bps": "123", "log_info_error_input_pps": "1234", "log_info_notice_input_bps": "3", "log_info_notice_input_pps": "4"} 
```


```
state = {
  "last": None
}

tag_string_list = [ "in"]
option_field = ["log_info"]
byte_map_dict = {"error_input_bytes": "error_input_bits", "notice_input_bytes": "notice_input_bits"}
log_fields_list = ["error_input_pkts", "notice_input_pkts"]

def apply(metric):
    # Load from the shared state the metric assigned to the key "last"
    last = state["last"]
    # Store the deepcopy of the new metric into the shared state and assign it to the key "last"
    # NB: To store a metric into the shared state you have to deep copy it
    state["last"] = deepcopy(metric)
    if last != None:
        # Create a new metric named "cpu_diff"
        result = Metric("cpu_diff")
        # Set the field "value" to the difference between the value of the last metric and the current one
        result.fields["value"] = last.fields["value"] - metric.fields["value"] / 1000000000
        for k in metric.fields.keys():
                field_computer(last, metric, k, interval_seconds, result)
        result.tags.update(metric.tags)
        return result

def new_metric(metric):
    for k, v in metric.fields.items():
        if k in tag_string_list:
            metric.tags[k] = v
            metric.fields.pop(k)
        elif k in tag_float_list:
            metric.tags[k] = str(v)
            metric.fields.pop(k) 
        elif k == 'in' and v != "no" and v != None: // flatten the json in the "in" field
            j = json.decode(str(v))
            metric.fields.pop('out')
            metric.tags["bw"] = j["bw"]
            metric.fields["out_pass_pkts"] = float(j["out_pkts_pass"])
            metric.fields["out_pass_bits"] = float(j["out_bytes_pass"]) * 8
        elif k == 'in' and v == "no":
            metric.tags[k] = v
            metric.fields.pop(k)
        elif k in rename_field_list:
            if "bytes" in k[-5:]:
                new_name = k.replace("bytes", "bits", 5)
                metric.fields[new_name] = float(v) * 8
                metric.fields.pop(k)
            elif "pkts" not in k[-4:]:
                metric.fields[k+"_pkts"] = float(v)
                metric.fields.pop(k)
            else:
                metric.fields[k] = float(v)
        elif k in option_field: //  Flatten the json in the log_info field
            if metric.fields.get(k) != None:
                j = json.decode(str(metric.fields.get(k)))
                metric.fields.pop(k)
                if "total_stats" in j.keys():
                    total_drop_json = j["info"]
                    for field in log_fields_list:
                        if field in total_drop_json.keys():
                            new_key = k+ "_" + field
                            metric.fields[new_key] = float(total_drop_json[field])
                    for field in byte_map_dict:
                        if field in total_drop_json.keys():
                            new_key = k + "_" + byte_map_dict[field]
                            metric.fields[new_key] = float(total_drop_json[field]) * 8

def field_computer(last_metric, metric, field, interval_seconds, result):
    if "bits" in field[-4:]:
        new_field = field.replace("bits", "bps", 4)
    elif "pkts" in field[-4:]:
        new_field = field.replace("pkts", "pps", 4)
    if last_metric.fields.get(field) != None 
        data_dif = metric.fields[field] - last_metric.fields[field]
        if data_dif < 0:
            result.fields[new_field] = metric.fields[field] / interval_seconds
        else:
            results.fields[new_field] = data_dif / interval_seconds
    else:
        result.fields[new_field] = metric.fields[field] / interval_seconds
```

This is a bit complicated. We use startlark to not only flatten the nested json, but also modify the field name and dif the field to avoid the core problem caused by startlark and aggregators. So can you give me some suggestions for using the program according to the data characteristics of my input

**Comment by srebhan** [comment]
Hey @iceyfighting. If I save your three data examples to a file and use the following config
```toml
[[inputs.file]]
  files = ["test_configs/jsontest_issue_12649_1.json","test_configs/jsontest_issue_12649_2.json","test_configs/jsontest_issue_12649_3.json"]
  data_format = "xpath_json"

  xpath_native_types = true

  [[inputs.file.xpath]]
    metric_name = "'foo'"
    field_selection = "descendant::*[not(child::*)]"
    field_name_expansion = true
    timestamp = "/timestamp"
    timestamp_format = "unix"
```

I get
```text
> foo,host=Hugin host="host1",in="no",name="data",rx_bytes="10",rx_pps="0",timestamp=1676351945,tx_bytes="0",tx_pkt="0" 1676351945000000000
> foo,host=Hugin host="host1",in_bw="1024K",in_out_bytes_pass="23456",in_out_pkts_pass="1234",name="data",rx_bytes="10",rx_pps="0",timestamp=1676351945,tx_bytes="0",tx_pkt="0" 1676351945000000000
> foo,host=Hugin host="host1",in_bw="1024K",in_out_bytes_pass="23456",in_out_pkts_pass="1234",log_info_info_error_input_bytes="123",log_info_info_error_input_pkts="1234",log_info_info_notice_input_bytes="3",log_info_info_notice_input_pkts="4",name="data",rx_bytes="10",rx_pps="0",timestamp=1676351945,tx_bytes="0",tx_pkt="0" 1676351945000000000
```

as output. Is this what you want? The `field_name_expansion = true` is in to prevent field name collisions...

**Comment by iceyfighting** [comment]
Thanks for still looking at my question, the field names in the nested json are concatenated, can this be customized? Like my output above log_info_error_input_bps not log_info_info_notice_input_bytes. 
Or you use xpath to process the input, then use aggregators.basicstats to calculate the rate and use processors.rename to rename it, and I can finally achieve my goal of output

**Comment by srebhan** [comment]
@iceyfighting as I wrote ;-)
> [...] The field_name_expansion = true is in to prevent field name collisions...

Removing this line (or setting it to false) will only keep the name of the leaf-node...

**Comment by iceyfighting** [comment]
Thank you very much, I will try your way to parse and rename nested json in the future, I hope it will be useful
