### ISSUE TITLE
processor: unpivot fields into new measurements

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/telegraf#12652]
Hello,

I have been using the plugin for a while and I am more than happy with the performance.
I am actually sending data to an Influx data base and I see that all the datapoints are created as fields under one measurement with the predefined name in the plugin.
I am wondering if it would be posible to store the points as differents measurement with only one field that could be "value".

Thanks in advance.

**Comment by powersj** [comment]
Hi,

To confirm I am following correctly, you want to take the following metric:

```s
metric,building="5a" temperature=42,humidity=22
```

and turn it into this:

```s
temperature,building="5a" value=42
humidity,building="5a" value=22
```

If so, I think it makes the most sense to do this with a processor, rather than at the individual input or output level. We already have the [unpivot processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/unpivot), which does something similar, but does not make new measurements.

The thing to be aware of is if measurement names suddenly conflict, this could lead to some odd behavior.

Thanks!

**Comment by alexmc1510** [comment]
Hello, thank you very much. You understood the problem correctly and you suggested what I thought. I will do in that way and...of course, I will pay attention to the name of the measurement. Could I take advantage of the thread to ask 2 more questions?
- I have some signals that change once a week or even more. When I launch the query in Influx, sometimes is very difficult to find the last value as it changed some weeks ago. Where do you suggest I could, for example, force a record every day at 00:00 so I would have a complete "picture" of the signals without the need of looking for the last value in the past?
- Is there a possibility to create and force a field with a fixed value? for example to record the location of the IoT device. Should I use other input or output plugin?

Thanks in advance for your help

**Comment by powersj** [comment]
Hi,

> You understood the problem correctly and you suggested what I thought. I will do in that way and...of course,

To be clear, other than the unpivot processor, there is no processor to do this exactly as I showed above. I want to use this issue to either add this functionality to the unpivot processor or create a new processor that does this.

> Where do you suggest I could, for example, force a record every day at 00:00 so I would have a complete "picture" of the signals without the need of looking for the last value in the past?

This is best done with a cronjob + running telegraf with the `--once` flag. Once will run the complete Telegraf collection cycle exactly once: your input will collect the values and send them to your output.

> Is there a possibility to create and force a field with a fixed value? for example to record the location of the IoT device. Should I use other input or output plugin?

Yes, location is commonly added as a tag given it is a string value. You can add [global tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#global-tags) that apply to all your data. Or you [plugin specific tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#plugins) to each plugin.

**Comment by powersj** [comment]
Hi @alexmc1510,

I have put up #12659 with a possible fix. It creates a new option in the pivot processor called `metric_mode`. Setting this to `metric_mode = "field"` I believe would get you what you are after.

Could you download the artifacts in 20-30mins on that PR and give it a try?

Thanks!

**Comment by alexmc1510** [comment]
Hello,

Sorry for the delay. I have checked the artifacts and it work fine. Well done.

Regarding the other questions, find below my answers:
>Where do you suggest I could, for example, force a record every day at 00:00 so I would have a complete "picture" of the signals without the need of looking for the last value in the past?

>>This is best done with a cronjob + running telegraf with the --once flag. Once will run the complete Telegraf collection cycle exactly once: your input will collect the values and send them to your output.


Cronjob would work if you collect data with telegraf timestamp but if you collect data with source timestamp, the timestamp of the measurement will come from the memory of the PLC o NC that stores the last value and the date when data changed. It should be maybe a task inside InfluxDB that would make a kind of "image" of values at 00:00 with the last value found during all the time...

>Is there a possibility to create and force a field with a fixed value? for example to record the location of the IoT device. Should I use other input or output plugin?

>>Yes, location is commonly added as a tag given it is a string value. You can add [global tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#global-tags) that apply to all your data. Or you [plugin specific tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#plugins) to each plugin.

Maybe location was a bad example....imagine I collect data from a numerical control where I want to "collect" a fix value for: manufacturer, firmware version, ID, location....basically, hundreds of metadata that will complement the real group of values. Would it be possible to do that?

**Comment by powersj** [comment]
> Sorry for the delay. I have checked the artifacts and it work fine. Well done.

Thank you for confirming. This will go out in our next minor release, v1.26, scheduled in March.

> basically, hundreds of metadata that will complement the real group of values. Would it be possible to do that?

I don't see why not, but it entirely depends on the input control, data type, etc. as to how best to do this. I'd suggest dropping by our [forums](https://community.influxdata.com/c/ts-collect/6) or [slack](https://www.influxdata.com/slack/) where additional folks could answer this given a bit more details about how you plan to do this.

Thanks again!
