### ISSUE TITLE
Allow password of the secret store to be entered on the command line when managing secrets

### ISSUE THREAD

**Issue by jackbenimble999** [influxdata/telegraf#12651]
### Use Case

This will be used when installing telegraf secrets from a command line in an installer: 

This  would allow the password for the secret store to be set from a command line as follows: 

telegraf  --config telegraf_mqtt_to_influxdb.conf secrets set os_secrets my_secret_password xxxxxxx --secret-store-password yyyyy

Thanks! 

### Expected behavior

1. telegraf  --config telegraf_mqtt_to_influxdb.conf secrets set os_secrets my_secret_password xxxxxxx --secret-store-password yyyyy
2. password for the secrets store will be used the parameter from the command line

### Actual behavior

1. telegraf  --config telegraf_mqtt_to_influxdb.conf secrets set os_secrets my_secret_password xxxxxxx --secret-store-password yyyyy
2. No password is stored, no prompted for.

**Comment by powersj** [comment]
next steps: look into adding the option

**Comment by srebhan** [comment]
@jackbenimble999 can you please check the binary built in PR #12812 once CI is finished and let me know if this fixes your issue!?
