### ISSUE TITLE
Telegraf not using endpoint_url for cloudwatch input

### ISSUE THREAD

**Issue by v4vamsee** [influxdata/telegraf#12653]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
debug = false
quiet = false
logtarget = "file"
logfile = "/var/log/telegraf/telegraf.log"
logfile_rotation_interval = "24h"
logfile_rotation_max_archives = -1
hostname = ""
omit_hostname = false

[[outputs.influxdb]]
urls = ["http://localhost:8086"]
database = "telegraf_PRD"
retention_policy = ""
write_consistency = "any"

[[inputs.cloudwatch]]
region = "us-east-2"
access_key = "xxxxx"
secret_key = "xxxx"
period = "5m"
delay = "5m"
interval = "5m"
namespaces = ["AWS/ElastiCache"]
ratelimit = 25
endpoint_url = "https://vpcendpoint.monitoring.us-east-2.vpce.amazonaws.com"

[[inputs.cloudwatch.metrics]]
names = ["IsMaster", "CPUUtilization", "EngineCPUUtilization", "SwapUsage", "BytesUsedForCache", "FreeableMemory", "NetworkBytesIn", "NetworkBytesOut", "ReplicationBytes", "ReplicationLag", "CurrConnections", "NewConnections", "CurrItems", "Reclaimed", "CacheHits", "CacheMisses", "Evictions", "GetTypeCmds", "SetTypeCmds"]

[[inputs.cloudwatch.metrics.dimensions]]
name = "CacheClusterId"
value = "*"
```

### Logs from Telegraf

```text
Telegraf shows following in the log:

2023-02-07T14:54:16Z E! [inputs.cloudwatch] failed to list metrics with namespace AWS/EFS: operation error CloudWatch: ListMetrics, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post “https://monitoring.us-east-2.amazonaws.com/”: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-02-07T14:54:16Z E! [inputs.cloudwatch] failed to list metrics with namespace AWS/EBS: operation error CloudWatch: ListMetrics, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post “https://monitoring.us-east-2.amazonaws.com/”: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-02-07T14:55:18Z E! [inputs.cloudwatch] failed to list metrics with namespace AWS/ElastiCache: operation error CloudWatch: ListMetrics, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post “https://monitoring.us-east-2.amazonaws.com/”: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### System info

telegraf 1.25.0, CentOS Linux release 7.9.2009 (Core)

### Steps to reproduce

1.Copy the telegraf configuration listed above
2.Restart telegraf agent
3.Review logs 

### Expected behavior

Telegraf is expected to connect to the endpoint_url and not the default monitoring url:https://monitoring.us-east-2.amazonaws.com

### Actual behavior

Telegraf is not enforcing the override "endpoint_url" i.e. its not connecting to the endpoint listed in config. Instead its connecting to default monitoring url: https://monitoring.us-east-2.amazonaws.com

### Additional info

Performed additional testing through https://community.influxdata.com/t/telegraf-not-using-endpoint-url-for-cloudwatch/28475/13

Testing results:

[cloudwatch_testing.tar.gz](https://github.com/influxdata/telegraf/files/10689383/cloudwatch_testing.tar.gz)

**Comment by powersj** [comment]
I'll take a look at the next steps on this one.

Based on the back and forth I had in the community forum post it looks like the [cloudwatch_logs output](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/cloudwatch_logs/cloudwatch_logs.go#L156-L169) sets some configuraiton values based on the endpoint URL which is missing from [cloudwatch input here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go#L189-L209). This may apply to other AWS based plugins as well.

**Comment by srebhan** [comment]
@v4vamsee the `endpoint_url` is only used for credential handling. So far the plugin does not support specifying a custom endpoint URL for the metrics... This needs to be added.

**Comment by powersj** [comment]
@v4vamsee,

In 20-30mins there should be artifacts attached to PR https://github.com/influxdata/telegraf/pull/12657. In that PR if you specify the region and endpoint, a new client will be specified pointing to the endpoint.

Can I ask that you try two scenarios:

1) try that the endpoint + region is set and works to resolve this issue
2) ensure that without the endpoint set it still works but goes via your proxy. I want to ensure the other use case continues to work as expected.

Thanks!

**Comment by v4vamsee** [comment]
I can confirm this particular PR is successful during my testing. Attached are the results.
[cloutwatch_testing2.tar.gz](https://github.com/influxdata/telegraf/files/10701025/cloutwatch_testing2.tar.gz)

**Comment by powersj** [comment]
Thanks for the quick test and confirmation. I really appreciate it. I will get this reviewed and hopefully in next week's bug fix release.

**Comment by powersj** [comment]
@v4vamsee can I ask you try that test one more time with the [latest artifacts](https://github.com/influxdata/telegraf/pull/12657#issuecomment-1425950501). After the review we wanted to see if a simpler option that keeps the config settings consistent would work as well.

Really appreciate it.

**Comment by v4vamsee** [comment]
I can confirm the new artifacts are successful during my testing. Attached are the results.
[cloudwatch_testing3.tar.gz](https://github.com/influxdata/telegraf/files/10710014/cloudwatch_testing3.tar.gz)

**Comment by powersj** [comment]
Thank again!
