### ISSUE TITLE
parsing metrics failed: invalid character

### ISSUE THREAD

**Issue by ANAPHYL4X15** [influxdata/telegraf#12665]
Getting this error while trying to parse data from a Tesla wall connector
`[inputs.http] Error in plugin: [url=http://192.168.2.82/api/1/lifetime]: parsing metrics failed: invalid character 'a' in literal null (expecting 'u')`
Not sure how to proceed.

here's the data its trying to parse:
{
    "contactor_cycles": 181,
    "contactor_cycles_loaded": 7,
    "alert_count": 18,
    "thermal_foldbacks": 1,
    "avg_startup_temp":nan,
    "charge_starts": 181,
    "energy_wh": 3134125,
    "connector_cycles": 133,
    "uptime_s": 52993842,
    "charging_time_s": 555084
}

**Comment by ANAPHYL4X15** [comment]
if I had to guess, its an issue with the "avg_startup_temp" value being "nan". if so, is there a way to tell it to ignore or exclude that from the parser? I can't change the data served to me from the wall connector.

**Comment by powersj** [comment]
Unfortunately, that is not valid JSON. My suggest is to possibly use the exec processor to use an external script to pull that data down and possibly fix it.
