### ISSUE TITLE
User permissions type

### ISSUE THREAD

**Issue by MrPessimist** [influxdata/telegraf#12673]
### Please direct all support questsions to slack or the forums. Thank you.

Hi

I am new to this and it occurred to me to create users in influxdb from different orgs so that, from different remote servers, they can telegraph write/send metrics to a specific bucket.

What type of permissions should or would be enough to have in each user that I will configure in the remote telegraf agent on the bucket to be able to write data?

My idea is to have a user restricted by org so that he can only do what he has to do, write metrics.

Thanks in advance.

**Comment by MrPessimist** [comment]
corresponds to a question for influxdb not telegraf.

**Comment by powersj** [comment]
> What type of permissions should or would be enough to have in each user that I will configure in the remote telegraf agent on the bucket to be able to write data?

If you are using InfluxDB v2 or InfluxDB Cloud, there are no users, if you look at the input plugin it takes a token. That token needs write access... to write.

If you are using InfluxDB v1 a user needs write access to the database, again to write.

> corresponds to a question for influxdb not telegraf.

Yet you filed an issue in the telegraf repo? As the telegraf-tiger posted, this is a much better succession for the Community Slack or Forums.
