### ISSUE TITLE
Non-Unix based timestamps (sec, ms, us, ns)

### ISSUE THREAD

**Issue by eadwu** [influxdata/telegraf#12674]
### Use Case

Apparently some services can give out timestamps that are given out in milliseconds based off a timezone that is not UTC ... and no existing format allows for it currently.

i.e. A timestamp in seconds since epoch but based off MST.

### Expected behavior

Normalize timestamps based off the desired timezone that are not in a Golang `time` layout format - specifically in milliseconds.

### Actual behavior

No such behavior exists - closest is `unix*` but those are fixed UTC timezones.

### Additional info

Maybe something like

```diff
diff --git a/internal/internal.go b/internal/internal.go
--- a/internal/internal.go
+++ b/internal/internal.go
@@ -254,12 +254,25 @@ func CompressWithGzip(data io.Reader) io.ReadCloser {
 // UTC location.
 func ParseTimestamp(format string, timestamp interface{}, location string, separator ...string) (time.Time, error) {
 	switch format {
-	case "unix", "unix_ms", "unix_us", "unix_ns":
+	case "unix", "unix_ms", "unix_us", "unix_ns", "sec", "ms", "us", "ns":
 		sep := []string{",", "."}
 		if len(separator) > 0 {
 			sep = separator
 		}
-		return parseUnix(format, timestamp, sep)
+
+		t, err := parseUnix(format, timestamp, sep)
+		if err != nil {
+			return t, err
+		}
+
+		switch format {
+		case "sec", "ms", "us", "ns":
+			// Get rid of timezone information to normalize with respect to another timezone
+			const format = "2006-01-02 15:04:05.999999999"
+			return parseTime(format, t.Format(format), location)
+		default:
+			return t, err
+		}
 	default:
 		v, ok := timestamp.(string)
 		if !ok {
@@ -274,13 +287,13 @@ func parseUnix(format string, timestamp interface{}, separator []string) (time.T
 	// Extract the scaling factor to nanoseconds from "format"
 	var factor int64
 	switch format {
-	case "unix":
+	case "unix", "sec":
 		factor = int64(time.Second)
-	case "unix_ms":
+	case "unix_ms", "ms":
 		factor = int64(time.Millisecond)
-	case "unix_us":
+	case "unix_us", "us":
 		factor = int64(time.Microsecond)
-	case "unix_ns":
+	case "unix_ns", "ns":
 		factor = int64(time.Nanosecond)
 	}
```

**Comment by Hipska** [comment]
Sounds good, you can create a PR for this and then someone will review. Be sure to add new tests as well..

**Comment by powersj** [comment]
Hi,

Are you willing to put up a PR with tests for this? We do have concerns about the format strings causing confusion as to what `ms` vs `unix_ms` means. I would hate to see a user start using `ms` because their timestamps are in milliseconds, but not realize it might add some unexpected offset that does not actually apply. So that format string would need to be different.

The other option we considered and thought about was using a processor to add an offset to the timestamp itself, rather than adding and maintaining another config options.

Thanks!
