### ISSUE TITLE
Deprecate `fieldpass` and `fielddrop` modifiers

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#12675]
### Use Case

The current naming is not consistent and this it is not clear what it does. We have had several users on the community Slack/forums (including me) that were confused by this naming.

Let's take a look at current documentation: [Metric filtering](https://github.com/influxdata/telegraf/blob/v1.25.2/docs/CONFIGURATION.md#metric-filtering)

You have the following selectors which indicate wether or not a metric will be emitted for a particular plugin:

- name**pass**
- name**drop**
- tag**pass**
- tag**drop**

*Note that they all have the same consistent suffix of `pass` or `drop`.*

Then we have the following modifiers which indicate wether or not an item will be dropped from the metric:

- field**pass**
- field**drop**
- tag**include**
- tag**exclude**

So here, one would expect something like field-include/exclude as field-pass/drop may sound like they indicate the metric not being emitted to the plugin.

### Expected behavior

Being able to use `fieldinclude` and `fieldexclude`  for any plugin to be more consistent with the already existing `taginclude` and `tagexclude`.

When still using `fieldpass` and `fielddrop` a deprecation warning should be emitted at startup.

### Actual behavior

Only able to use `fieldpass` and `fielddrop`.

**Comment by gazpachoking** [comment]
Yep, agree this is confusing. I was looking for a selector to filter metrics based on whether it contained a field, and assumed it would be fieldpass. Seems that there isn't such a selector at all though (please correct me if I'm wrong about this.)

**Comment by Hipska** [comment]
> Yep, agree this is confusing. I was looking for a selector to filter metrics based on whether it contained a field, and assumed it would be fieldpass. Seems that there isn't such a selector at all though (please correct me if I'm wrong about this.)

This can now be done with the `metricpass` CEL-expression.

**Comment by Hipska** [comment]
Isn't that exactly what I'm describing in the "Expected behaviour"?

**Comment by srebhan** [comment]
Yeah just wanted to make sure we are on the same page...

**Comment by hackery** [comment]
The [docs on influxdata.com](https://docs.influxdata.com/telegraf/v1/configuration/) has not been updated in line with this change, and will be many people's landing page for Telegraf configuration.
Opened https://github.com/influxdata/docs-v2/issues/6448 there.
