### ISSUE TITLE
[inputs.x509_cert] Error in plugin: cannot get SSL cert

### ISSUE THREAD

**Issue by skinfrakkiirid** [influxdata/telegraf#12684]
### Please direct all support questsions to slack or the forums. Thank you.

Getting the following issue with one certificate:

[inputs.x509_cert] Error in plugin: cannot get SSL cert: tls: failed to parse certificate from server: x509: invalid certificate policies

I can test from openssl and it works fine. My other certs I'm checking with telegraf is working fine as well:

openssl s_client -servername server -connect server:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Jun 21 22:55:36 2022 GMT
notAfter=Jun 20 22:55:36 2025 GMT

**Comment by srebhan** [comment]
@skinfrakkiirid which version of Telegraf are you using? Can you share a certificate that triggers the issue?

**Comment by srebhan** [comment]
Maybe related upstream issue: https://github.com/golang/go/issues/53773

**Comment by skinfrakkiirid** [comment]
Telegraf 1.25.0 (git: HEAD@4d17ec79). I can't share the certificate due to where I work, however this certificate differs by being issued from a local Windows CA. The other three are from DIgisign:

[[inputs.x509_cert]]
#   ## List certificate sources, support wildcard expands for files
#   ## Prefix your entry with 'file://' if you intend to use relative paths
  sources = ["https://server1:443", "https://server2:443", "https://server3:443", "https://server4:443"]
  timeout = "15s"
  exclude_root_certs = true

**Comment by srebhan** [comment]
The error is definitively coming from Golang's x509 library (or any underlying lib). However, without being able to reproduce the issue even filing a bug upstream seems hopeless. Are you somehow able to reproduce this in a non-sensitive environment? Like creating a (short-lived or expired) dummy cert that we can use for testing?

**Comment by powersj** [comment]
FYI we've been having this discussion on the forum as well: https://community.influxdata.com/t/inputs-x509-cert-error-in-plugin-cannot-get-ssl-cert-issue/28637/21

**Comment by srebhan** [comment]
The policies are

```text
X509v3 extensions:
X509v3 Subject Alternative Name:
DNS:dnsserver1, DNS:dnsserver2 IP Address:address1, IP Address:address2
X509v3 Subject Key Identifier:
98:FF:66:3C:58:26:36:A1:F5:CB:C2:B3:BC:3C:33:90:3E:8A:5E:80
X509v3 Authority Key Identifier:
keyid:13:57:08:E7:5E:7E:92:45:E9:AF:CC:80:B2:D5:D2:A4:E2:30:87:6B
```

according to the forum post. Found upstream issue https://github.com/golang/go/issues/58821 which is related. Unfortunately there is currently no way to work around that issue.

**Comment by srebhan** [comment]
@skinfrakkiirid go-1.22 was released and this should have a fix for your issue. Can you please test the binary in PR #14697 and let us know if this fixes your issue!?!
