### ISSUE TITLE
Telegraf remains in stopped state after upgrade on Debian

### ISSUE THREAD

**Issue by drdev** [influxdata/telegraf#12686]
### Relevant telegraf.conf

Not related to telegraf configs, instead incorrect usage of `deb-systemd-invoke` in postinst script causes problems

### Logs from Telegraf

Not relevant, logs from `/var/log/syslog` instead:

```text
Feb 15 16:55:50 node1 systemd[1]: Stopping Telegraf...
Feb 15 16:55:50 node1 systemd[1]: telegraf.service: Succeeded.
Feb 15 16:55:50 node1 systemd[1]: Stopped Telegraf.
```

### System info

Debian 10.13, Telegraf 1.25.2

### Steps to reproduce

1. Make sure Telegraf service is running
  ```shell
   $ systemctl is-active telegraf.service
   active
   ```
2. Check Telegraf version
   ```shell
   $ telegraf --version
   Telegraf 1.25.0 (git: HEAD@4d17ec79)
   ```
3. Upgrade telegraf
   ```shell
   $ apt update && apt install telegraf
   ...
   $ telegraf --version
   Telegraf 1.25.2 (git: HEAD@67c08c51)
   ```
5. Check service status
   ```shell
   $ systemctl is-active telegraf.service
   inactive
   ```
6. Start service successfully
   ```shell
   $ systemctl start telegraf && systemctl is-active telegraf.service
   active
   ```

### Expected behavior

Service should remain running when upgraded

### Actual behavior

Service is stopped on upgrade

### Additional info

This causes problems if unattended upgrades are enabled on a host. This should be fixed asap.

**Comment by powersj** [comment]
> Telegraf 1.25.0 (git: HEAD@4d17ec79)


This is a known issue with 1.25.0. It will stop on an upgrade. When you upgrade away from 1.25.0, the maintainers scripts of that version were used. Going forward this will not be an issue as it was fixed in 1.25.1 and later versions.
