### ISSUE TITLE
add information how to use the keys in the repository

### ISSUE THREAD

**Issue by maxadamo** [influxdata/telegraf#12687]
Would you mind adding some information on how to use your apt repository, and which key should be used? 
The keys have in my opinion counter-intuitive names but a README file, would help everyone to sort the problem out in a minute. 
And if you believe that this is well-documented elsewhere, would it be possible to add the link to the documentation inside the README file? 
If I'm allowed to say it, it's matter of being practical, because the README file is the first thing that everyone always try to open. 

I apologize for being very direct, but I spent a week before being able to figure out that the name of the key that I should have used is suffixed with "_archive-compat_".

**Comment by powersj** [comment]
> Would you mind adding some information on how to use your apt repository, and which key should be used?

As I mentioned in my [other response](https://github.com/influxdata/telegraf/issues/12563#issuecomment-1431898103) this is literally already in the [README](https://github.com/influxdata/telegraf/blob/master/README.md#package-repository)

Is that section not clear?

**Comment by maxadamo** [comment]
> > Would you mind adding some information on how to use your apt repository, and which key should be used?
> 
> As I mentioned in my [other response](https://github.com/influxdata/telegraf/issues/12563#issuecomment-1431898103) this is literally already in the [README](https://github.com/influxdata/telegraf/blob/master/README.md#package-repository)
> 
> Is that section not clear?

Sorry for the misunderstanding. I am trying to offer you my perspective. 
A while ago I had configured the repo (I'm syncing it with apt-mirror). At some point the repo broke, and my landing page, is not the github page of the project, but the one that I have configured in apt-mirror.conf: https://repos.influxdata.com/ 

**p.s.:** I admit that this has nothing to do with Telegraf, and I have to apologize. Maybe I should report the issue to Influx repo, or maybe you got another project for the APT repository.

**Comment by maxadamo** [comment]
and if I can (than I can close the issue, because it's not an issue with Telegraf), if you google for: 
influxdb NO_PUBKEY D8FF8E1F7DF8B07E
You find quite a few results for this search, which means that something is rotten in the state of the repository... because I'm not the only one facing this issue in the last few weeks. 

Cheers. And thanks :)

**Comment by powersj** [comment]
> and my landing page, is not the github page of the project, but the one that I have configured in apt-mirror.conf: https://repos.influxdata.com/

ok that helps me understand your workflow.

I think updating that page to document what each key represents is a very valid request and probably would have saved you some time. Let me talk to folks and see if we could add something.

**Comment by powersj** [comment]
@maxadamo,

We have added docs to the repo page itself now that documents how to use the repo and what each of the keys provides. Hopefully that will help others in the future. Thanks for bringing this up.

http://repos.influxdata.com/

You may need to do a hard-refresh to see the updates

**Comment by maxadamo** [comment]
thanks a lot for you support @powersj !
