### ISSUE TITLE
Telegraf showing no Metrics dropped when logs showing "Context Deadline exceeded Error"

### ISSUE THREAD

**Issue by pratikdas44** [influxdata/telegraf#12682]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
 brokers = []
 topics = []
 ------

[[inputs.internal]]
  collect_memstats = true
  interval = "5m"
  [inputs.internal.tags]
    input_type = "internal"

[[processors.converter]]
  order = 1
  [processors.converter.fields]
    float = ["*"]
  [processors.converter.tagdrop]
    input_type = ["internal"]

[[processors.starlark]]
  order = 2
  ## The Starlark source can be set as a string in this configuration file, or
  ## by referencing a file containing the script.  Only one source or script
  ## should be set at once.

  ## Source of the Starlark script.
  source = '''
load("json.star", "json")
def apply(metric):
    metric_list = []
    metric_new = Metric("measurement_name")
    metric_new.time = metric.time
    for k,v in metric.tags.items():
        metric_new.tags[k] = v
    dict_fields = {}
    for k,v in metric.fields.items():
        ##doing some preprocessing;
    return metric_list
'''
[processors.starlark.tagdrop]
   input_type = ["internal"]

[[outputs.influxdb_v2]]
  ## Test internal bucket
 urls = ["${OUTPUT_URL}"]
 token = "${TOKEN}"
 organization = "${ORGANIZATION}"
 bucket = ""
 flush_interval = "2m"
 flush_jitter = "20s"
 timeout = "15s" //changed now, earlier it was default "5s"
 content_encoding = "gzip"
 influx_sort_fields = true
 [outputs.influxdb_v2.tagdrop]
   input_type = ["internal"]

[[outputs.influxdb_v2]]
  urls = ["${OUTPUT_URL}"]
  namedrop = ["exe_*"]
  token = "${TOKEN}"
  organization = "${ORGANIZATION}"
  bucket = ""
  flush_interval = "5m"
  flush_jitter = "25s"
  content_encoding = "gzip"
  timeout = "15s" //changed now, earlier it was default "5s"
 influx_sort_fields = true
 [outputs.influxdb_v2.tagpass]
   input_type = ["internal"]
```

### Logs from Telegraf

```text
2023-02-13T06:14:00Z E! [outputs.influxdb_v2] When writing to [http://url:8086/]: Post "http://url:8086/api/v2/write?bucket=""&org=""": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-02-13T06:14:00Z D! [outputs.influxdb_v2] Buffer fullness: 5755 / 300000 metrics
2023-02-13T06:14:00Z E! [agent] Error writing to outputs.influxdb_v2: failed to send metrics to any configured server(s)
2023-02-13T06:14:10Z D! [sarama] client/metadata fetching metadata for all topics from broker broker-ip
2023-02-13T06:16:05Z E! [outputs.influxdb_v2] When writing to [http://url:8086/]: Post "http://url:8086/api/v2/write?bucket=""&org=""": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-02-13T06:16:05Z D! [outputs.influxdb_v2] Buffer fullness: 10251 / 300000 metrics
2023-02-13T06:16:05Z E! [agent] Error writing to outputs.influxdb_v2: failed to send metrics to any configured server(s)
2023-02-13T06:17:57Z D! [outputs.influxdb_v2] Wrote batch of 8 metrics in 3.599117ms
2023-02-13T06:17:57Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 300000 metrics
```

### System info

Telegraf - 1.23.3, Ec2 Instance - r5.large, InfluxDB - 2.0.9

### Steps to reproduce

1. The Telegraf Logs show "Context Deadline Error" starting from 13 Feb 06 AM UTC which continued until the next 21 hours, and stopped only when Telegraf Container was restarted.
![image](https://user-images.githubusercontent.com/30981073/218962766-3d9b3384-fce1-40c3-90e5-6278fc6f14ba.png)

2. I am seeing the Error using Telegraf internal Plugin, however, no metrics were dropped. But In InfluxDB, no metrics were showing for that time period.
![image](https://user-images.githubusercontent.com/30981073/218964282-1586362e-196b-408f-9d42-f9cb94e568f5.png)

3. No other metric is present to indicate the error message.
...

### Expected behavior

There should be some way to debug the cause of the error. Since Metrics are also not getting dropped, not able to debug. 

### Actual behavior

Errors are indicating some thing is wrong, no other metric present to actually indicate the cause

**Comment by powersj** [comment]
> There should be some way to debug the cause of the error. 

I am not aware of any further information we can provide.

Does this error continue forever, or does it recover?

**Comment by powersj** [comment]
This is the same as #12682, right? As such I'll close this as a dup.

**Comment by pratikdas44** [comment]
No, this is different as here, I am getting "error" stats using Internal Plugin in Telegraf, which is non-zero once the "Context Deadline" error comes in. However, its shows metrics are not dropped. But metrics of kafka were never written into influxdb.

**Comment by powersj** [comment]
>However, its shows metrics are not dropped. But metrics of kafka were never written into influxdb.

Because metrics are *not* dropped. The message would say if metrics were dropped. You will note the metric buffer increases as these errors occurred. It means the metrics are kept in the buffer until they can be tried again.
