### ISSUE TITLE
InfluxDB output plugin - recover after Context Deadline

### ISSUE THREAD

**Issue by pratikdas44** [influxdata/telegraf#12685]
### Use Case

Would want a similar behaviour as mentioned in this issue - https://github.com/influxdata/telegraf/issues/10950 and solution for that mentioned here - https://github.com/influxdata/telegraf/pull/11030

### Expected behavior

Telegraf Shows Context Deadline exceeded (Client.Timeout while awaiting headers), due to which metrics are not written to InfluxDB. However, after restarting Telegraf works fine. Telegraf should recover automatically, incase this message is coming since say last few time continously.

### Actual behavior

Telegraf Shows Context Deadline exceeded (Client.Timeout while awaiting headers), due to which metrics are not written to InfluxDB until not restarted.

### Additional info

![image](https://user-images.githubusercontent.com/30981073/219091261-af2e494f-23be-4250-820c-fe9c8ec972ac.png)

More details are mentioned here - https://community.influxdata.com/t/context-deadline-error-telegraf/28607/6

**Comment by powersj** [comment]
> Telegraf should recover automatically,

Can you show logs that show it constantly failing please? Are you saying it never recovers even after a few minutes?

**Comment by pratikdas44** [comment]
Ok, so I am using two input - kafka and internal plugin. However, the internal plugin metrics are always written but for kafka, metrics are going to buffer. Only after restarting telegraf, those metrics went. Notice in the screenshot, batch of 8 metrics (internal metrics) are always going but Kafka one is not. Two set of metrics were always going 39 and 8, however, before the error 900 something metrics came up. Not sure, if that can impact anything.

![image](https://user-images.githubusercontent.com/30981073/219113374-624ef8c4-ab54-49f0-8536-e1d9af0a07b7.png)

![image](https://user-images.githubusercontent.com/30981073/219114691-c4aa10ef-eb92-4599-9843-32c984366d88.png)

**Comment by powersj** [comment]
Can you share you full config please?
Do you eventually get log messages that show buffer over flow?

**Comment by pratikdas44** [comment]
No, we did not got kafka metrics until we restarted the docker container. Internal metrics were always there.
![image](https://user-images.githubusercontent.com/30981073/220373923-e16a510b-9ca6-4be3-bd03-7d3161ed0c9a.png)

**Comment by powersj** [comment]
Do you have two different influxdb servers? Again, can we please see a full config?

**Comment by pratikdas44** [comment]
No Same influxdb server, but two different bucket. Here is the full config:

[[inputs.kafka_consumer]]
 brokers = []
 topics = []

[[inputs.internal]]
  collect_memstats = true
  interval = "5m"
  [inputs.internal.tags]
    input_type = "internal"

[[processors.converter]]
  order = 1
  [processors.converter.fields]
    float = ["*"]
  [processors.converter.tagdrop]
    input_type = ["internal"]

[[processors.starlark]]
  order = 2
  source = '''
load("json.star", "json")
def apply(metric):
    metric_list = []
    metric_new = Metric("measurement_name")
    metric_new.time = metric.time
    for k,v in metric.tags.items():
        metric_new.tags[k] = v
    dict_fields = {}
    for k,v in metric.fields.items():
        ##doing some preprocessing;
    return metric_list
'''
[processors.starlark.tagdrop]
   input_type = ["internal"]

[[outputs.influxdb_v2]]
 urls = ["${OUTPUT_URL}"]
 token = "${TOKEN}"
 organization = "${ORGANIZATION}"
 bucket = ""
 flush_interval = "2m"
 flush_jitter = "20s"
 timeout = "15s" //changed now, earlier it was default "5s"
 content_encoding = "gzip"
 influx_sort_fields = true
 [outputs.influxdb_v2.tagdrop]
   input_type = ["internal"]

[[outputs.influxdb_v2]]
  urls = ["${OUTPUT_URL}"]
  namedrop = ["exe_*"]
  token = "${TOKEN}"
  organization = "${ORGANIZATION}"
  bucket = ""
  flush_interval = "5m"
  flush_jitter = "25s"
  content_encoding = "gzip"
  timeout = "15s" //changed now, earlier it was default "5s"
 influx_sort_fields = true
 [outputs.influxdb_v2.tagpass]
   input_type = ["internal"]

**Comment by pratikdas44** [comment]
Hi, @powersj I tried with timeout as "1s" for testing purpose and tried with interval both as "1m" for input and output configuration, with offset of kafka set of oldest. Rest all configuration are same. I am still seeing the same message.
![image](https://user-images.githubusercontent.com/30981073/220895740-429aaaaf-6490-4600-8acd-48ee3e5737f5.png)
![image](https://user-images.githubusercontent.com/30981073/220895992-3d255aa0-4f05-441f-a942-c3800a3c86fe.png)
![image](https://user-images.githubusercontent.com/30981073/220897028-8aed797b-4e2e-45e4-ba1c-3508cab64754.png)

Data didnot went to InfluxDB. Also, I am seeing anytime the message as mentioned in the new code. Following are the configuration - 
`[agent]
metric_batch_size = 16000
metric_buffer_limit = 300000
debug = true
round_interval = true

[[inputs.kafka_consumer]]
  brokers = []
 .............................
  interval = "1m"

[[processors.starlark]]
  order = 2
  source = '''
load("json.star", "json")
def apply(metric):
    return metric_list
'''

[[processors.converter]]
  order = 1
  [processors.converter.fields]
    integer = ["*"]

[[outputs.influxdb_v2]]
tagexclude = ["method","name","host","status"]
fielddrop = ["value"]
 urls = ["http://url:8086/"]
 token = ""
 organization = ""
 bucket = ""
flush_interval = "1m"
timeout = "1s"
 content_encoding = "gzip"
 influx_sort_fields = true`

How should I test here?

**Comment by powersj** [comment]
> I am seeing anytime the message as mentioned in the new code.

Sorry, not sure I understood this. You *are* seeing the following message using my PR?

> caught context deadline exceeded, closing idle connections

**Comment by pratikdas44** [comment]
Sorry, I mean "I am not seeing the message anytime". I am not seeing the following message - `caught context deadline exceeded, closing idle connections`

**Comment by powersj** [comment]
Hmm, I pushed another change that handles this higher up and slightly differently, can you give that a try once new artifacts are added please?

**Comment by pratikdas44** [comment]
Not working, One scenario happened when once I got the Context deadline error, however from next time metrics started to go. However, this happened only once, and never again. I tried changing the timeout the offset type to oldest and newest. But when the error came, it was always coming for offset as oldest and timeout for 3s. For offset - newest, not able to replicate Context Deadline Error. 

![image](https://user-images.githubusercontent.com/30981073/221372709-def88bf6-b010-4bc0-8789-f560f0a7a494.png)

**Comment by powersj** [comment]
> One scenario happened when once I got the Context deadline error, however from next time metrics started to go. However, this happened only once, and never again.

That sounds like an improvement? Or are you saying you were unable to reproduce after that?

> For offset - newest, not able to replicate Context Deadline Error.

Why are you changing the offset suddenly? It seems like you had something that was reproducing the issue.

**Comment by pratikdas44** [comment]
I was always able to reproduce the error, but didnot able to resolve, as it happened for once. Since, it was not resolving, I tried with offset as newest, but for that case I was not able to reproduce the error itself. To summarize, I was always able to get the error with my current configuration which is oldest offset however, only once it got resolved, rest of the times the error kept repeating until restart of telegraf.

**Comment by powersj** [comment]
> only once it got resolved, rest of the times the error kept repeating until restart of telegraf.

This is why I am still suspect that this is something in your networking that is causing this.

**Comment by pratikdas44** [comment]
But the Objective of new code is to make sure, if error comes then it should be resolved later on its own, by for eg re-establishing the connection, right?

**Comment by powersj** [comment]
Your hypothesis was that a new client was needed, but if your network is for example blocking telegraf or a proxy is caching the request or some other network issue is occurring, even a new client may not be enough. Without additional information about what might be going on or how this is an issue with telegraf itself it is not clear what the next steps are.

We have many, many users of the influxdb output. In all previous cases of this error it has generally been resolved through networking related changes on the users part. While we do see some users get this message occasionally it also resolves it after a retry or two.

**Comment by pratikdas44** [comment]
One change we had done from our side, was changing the http timeout option, prior to that, restarting the telegraf was the only solution we had used. 

But, I still didnot saw the following message anytime `caught context deadline exceeded, closing idle connections`

**Comment by powersj** [comment]
I am not sure how to continue helping you. At this point we are guessing.
