### ISSUE TITLE
Postgresql Output Plugin Schema Customization using SQL Templating

### ISSUE THREAD

**Issue by PWSys** [influxdata/telegraf#12688]
### Please direct all support questsions to slack or the forums. Thank you.

The default schema behavior is the "Wide" format, with each metric having a table with a column per field.  

Is it possible to leverage a "Narrow" schema?   Something like: time,id,value?

The ReadMe indicates the following:
 
> The postgresql plugin uses templates for the schema modification SQL statements. This allows for complete control of the schema by the user.

>Documentation on how to write templates can be found [sqltemplate docs](https://pkg.go.dev/github.com/influxdb/telegraf/plugins/outputs/postgresql/sqltemplate)

The link to the documentation just forwards to https://pkg.go.dev/github.com/influxdata/telegraf.  I'm not sure if this is possible using SQL templating.

**Comment by powersj** [comment]
Hmm looking at the URL it is meant to pull up the following page:

https://pkg.go.dev/github.com/influxdata/telegraf/plugins/outputs/postgresql/sqltemplate

I'll fix that URL.

As far as the narrow/wide, sounds like you are tring to [unpivot](https://github.com/influxdata/telegraf/tree/master/plugins/processors/unpivot) your data?
