### ISSUE TITLE
Use '_timestamp' field out of the collected JTI metrics

### ISSUE THREAD

**Issue by rapik0088** [influxdata/telegraf#12695]
### Use Case

Juniper JTI/gRPC input plugin

raw output:

```json
{"fields":
{"/interfaces/interface/init-time":1668001351,
"/interfaces/interface/state/counters/carrier-transitions":35,
"/interfaces/interface/state/counters/in-broadcast-pkts":0,
"/interfaces/interface/state/counters/in-discards":0,
"/interfaces/interface/state/counters/in-errors":2477,
"/interfaces/interface/state/counters/in-fcs-errors":2477,
"/interfaces/interface/state/counters/in-multicast-pkts":28038633,
"/interfaces/interface/state/counters/in-octets":1474691673838479,
"/interfaces/interface/state/counters/in-pause-pkts":0,
"/interfaces/interface/state/counters/in-pkts":2851708507740,
"/interfaces/interface/state/counters/in-unicast-pkts":2851680793661,
"/interfaces/interface/state/counters/in-unknown-proto-pkts":0,
"/interfaces/interface/state/counters/out-broadcast-pkts":1456,
"/interfaces/interface/state/counters/out-discards":0,
"/interfaces/interface/state/counters/out-errors":0,
"/interfaces/interface/state/counters/out-multicast-pkts":29243509,
"/interfaces/interface/state/counters/out-octets":5862030063686605,
"/interfaces/interface/state/counters/out-pause-pkts":0,
"/interfaces/interface/state/counters/out-pkts":11638760132998,
"/interfaces/interface/state/counters/out-unicast-pkts":11638757748219,
"/interfaces/interface/state/counters/out-unknown-proto-pkts":0,
"/interfaces/interface/state/high-speed":10000,"_component_id":0,"_sequence":32,"_subcomponent_id":0,"_timestamp":1676560510002},
"name":"/junos/system/linecard/interface/traffic/",
"tags":{"/interfaces/interface/@name":"xe-0/0/0","device":"10.16.18.21","host":"apollo0116a.gaia.ucom.am","path":"sensor_1000:/junos/system/linecard/interface/traffic/:/junos/system/linecard/interface/traffic/:PFE","system_id":"R1-M9"},
"timestamp":1676560510179198}
```

### Expected behavior

Telegraf uses "_timestamp" field in associated with the JTI collected metrics

### Actual behavior

Telegraf generates its own "timestamp" at the moment the metrics received.

**Comment by powersj** [comment]
next steps: add `use_metric_timestamp` option that converts the ms timestamp to nanosecond and applies to metric.

**Comment by rapik0088** [comment]
here is the workaround with starlark:

[[processors.starlark]]
source = '''
def apply(metric):
    metric.time = metric.fields['_timestamp']*1000000
    return metric

**Comment by powersj** [comment]
@rapik0088 I have put up https://github.com/influxdata/telegraf/pull/12730 which adds a setting to choose where the timestamp comes from. Could you download the artifacts from that PR, available in 20-30mins and see if it also works for you?

Thanks!

**Comment by rapik0088** [comment]
------------------------
[[inputs.jti_openconfig_telemetry]]
   timestamp_source = "data"
------------------------
works correctly. confirmed.

unfortunatelly it does not solve the artifact issue....

![image](https://user-images.githubusercontent.com/19273475/221172626-ed214457-bbdc-4bd3-b511-ba6f8aa4ed3b.png)

![image](https://user-images.githubusercontent.com/19273475/221172693-d0a0b45b-4ae5-4adb-bb9c-606e4aa58e01.png)

**Comment by rapik0088** [comment]
i've done some more investigation.
here is the timepstamps collection
[timestamps.csv](https://github.com/influxdata/telegraf/files/10823759/timestamps.csv)
the interval Juniper routers generate metrics is not exact 2000ms. it is from 2000 to 2050ms
the average is about 2030ms

but the visualization descritization time is exact 1/2/4/8s

2000ms / 30ms = 66 samples, 
66 samples * 2000ms = 132s = 2 mins 12 seconds

it exactly corresponds to Grafana gaps.
-- Grafana Prometheus Source ---
irate(_junos_system_linecard_interface_traffic___interfaces_interface_state_counters_in_octets{system_id="$system_id", _interfaces_interface_name="$interface_name"}[2s])
-----------------------------------

**Comment by rapik0088** [comment]
anyway the 
[[inputs.jti_openconfig_telemetry]]
timestamp_source = "data"
is a properl option.
i kindly ask you to integrate it in the next Telegraf release.
