### ISSUE TITLE
Wireguard Allowed IP as a tag

### ISSUE THREAD

**Issue by MSommer95** [influxdata/telegraf#12705]
### Use Case

Having the Allowed IPs as a tag would allow for more detailed evaluation of the collected metrics. 
Seeing the CIDR makes it easier to distinguish different peers. 

### Expected behavior

wireguard_peer metrics would get a new tag for allowed ips in the CIDR format.

Example:
``allowed_ip=192.168.4.3/32``

### Actual behavior

There currently is no tag aside from the public_key to distinguish peers.

**Comment by powersj** [comment]
Hi,

The value of AllowedIPs is stored of an list of IPv4 and IPv6 address that a peer is allowed to communicate on. How would we represent multiple addresses?

**Comment by MSommer95** [comment]
Hey, 
I wasnt aware that the value is stored as a list, I was under the assumption that it was similar to the representation ``wg show`` implements.

**Comment by MSommer95** [comment]
> Hi,
> 
> The value of AllowedIPs is stored as a list of IPv4 and IPv6 address that a peer is allowed to communicate on. How would we represent multiple addresses?

Do you think joining the list into a single string would be possible / good practice in that case? I am not sure what the proper way of handling a list for telegraf tags is.

For example:
``allowed_ips=192.168.4.3/32,172.0.1.100/32``

This would still allow for visualisations to incorporate the information.

**Comment by powersj** [comment]
next steps: add new field with CSV string called "allowed_peer_cidr"

**Comment by powersj** [comment]
@MSommer95 can you give the artifacts in https://github.com/influxdata/telegraf/pull/12729 a try and provide the output example? I am curious how/if CIDRs like 0.0.0.0/0 show up or not.

**Comment by MSommer95** [comment]
@powersj Hey, checked out the artifacts and tested it against my current pivpn (configured one client with `0.0.0.0/0` additional to its usual CIDR. 

```
wireguard_peer,device=wg0,host=raspberrypi,public_key=XXXXXXX,allowed_ips=2i,allowed_peer_cidr="0.0.0.0/0,10.223.217.2/32",persistent_keepalive_interval_ns=0i,protocol_version=1i 1677189070000000000
```
Looks good to me!

**Comment by powersj** [comment]
thank you!
