### ISSUE TITLE
Telegraf Proxy input/output plugins

### ISSUE THREAD

**Issue by vsinha** [influxdata/telegraf#12710]
Introduce two new plugins to allow writing the telegraf internal representation from one telegraf instance to another, proxying all outgoing messages from a `source` telegraf to a given `sink` telegraf. These would allow for telegraf to be used as a dynamic forward proxy, to hop between different environments (such as prod and local) or to allow for dynamic scaling of either sources or listeners.

These could perhaps be implemented via the golang `rpc` module https://pkg.go.dev/net/rpc.

There are two ways to do this, `source-listener` and `sink-listener`.

## `source-listener`
  - `outputs.telegraf_listener` running on the `source` telegraf would expose an endpoint and wait for a `inputs.telegraf_subscriber` to request a message subscription. Other than this the output acts as a regular output and forwards any messages intended to be output by the `source` telegraf instance.
  - `inputs.telegraf_subscriber` running on the `sink` would take an endpoint of an `outputs.telegraf_listener` and upon startup reach out to that endpoint and set up a connection to begin receiving messages. After this, the input handles any incoming messages
 

### Example usage
Imagine we have a `prod` telegraf instance handling real data on one or more inputs and one or more outputs. As part of development, we'd like to be able to mirror these messages to a developer's local environment, to allow them to test a local instance against real production data. In this situation, we would configure the `prod` telegraf to have a `outputs.telegraf_listener` waiting at some endpoint, and configure the local environment to subscribe to events from the `prod` telegraf on startup.

## `sink-listener`
  - `outputs.telegraf` running on the `source` would take the URL of a telegraf `sink` instance, and write all outgoing messages to the `sink`
  - `inputs.telegraf_listener` running on the `sink` would expose an endpoint in similar fashion to `inputs.influxdb_listener` and wait for messages from sending telegraf instance.

I can't think of a good use case for this but it seemed possible so wanted to include it here.

**Comment by vsinha** [comment]
Oh, maybe I've made a mistake. I think [http_listener](https://github.com/influxdata/telegraf/blob/release-1.14/plugins/inputs/http_listener_v2/README.md) is equivalent to the `sink-listener` described above.

**Comment by Hipska** [comment]
You can already setup telegraf as a proxy by using any of the existing inputs and outputs.

Easiest is indeed using `outputs.influxdb_v2`  to send to `inputs.influxdb_v2_listener` on another telegraf. Can as well be done with http equivalent or just TCP socket.

**Comment by vsinha** [comment]
I think what you've outlined is the `sink-listener` option, and the `source-listener` is still not possible with today's plugins

**Comment by Hipska** [comment]
Indeed, I think I skipped that section, but it seems currently `outputs.prometheus_client` is behaving the way you described.

I agree there could be a need for something like a `outputs.http_listener` or something similar could be of added value, but this current feature request is too generic. Can you open a more specific one?
