### ISSUE TITLE
Go Mod Tidy and Make not working

### ISSUE THREAD

**Issue by dp1140a** [influxdata/telegraf#12726]
### Relevant telegraf.conf

```toml
No config this is a bug in the make from source
```

### Logs from Telegraf

```text
None
```

### System info

latest pull from Git

### Steps to reproduce

1. go mod tidy

### Expected behavior

Go mod tidy completes

### Actual behavior

go: finding module for package github.com/influxdata/telegraf/plugins/inputs/p4runtime
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/opensearch_query: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/opensearch_query
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/p4runtime: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/p4runtime
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/win_wmi: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/win_wmi
telegraf/plugins/outputs/mqtt imports
	github.com/influxdata/telegraf/plugins/common/mqtt: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/common/mqtt
telegraf/plugins/parsers/json tested by
	telegraf/plugins/parsers/json.test imports
	github.com/influxdata/telegraf/internal/fuzz: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/internal/fuzz

**Comment by powersj** [comment]
What version of Go are you using?
Are you using a proxy?
Are you checking out a specific tag?

```
❯ go version
go version go1.20.1 darwin/amd64
telegraf on  master via 🐹 v1.20.1
❯ git rev-parse HEAD
245705cf249291ed89a28464a11860df0eea8cf6
telegraf on  master via 🐹 v1.20.1
❯ go mod tidy
telegraf on  master via 🐹 v1.20.1
```

**Comment by dp1140a** [comment]
go version go1.19.6 linux/amd64
❯ git rev-parse HEAD
245705cf249291ed89a28464a11860df0eea8cf6
❯ go mod tidy
go: finding module for package github.com/influxdata/telegraf/plugins/common/mqtt
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/opensearch_query: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/opensearch_query
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/p4runtime: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/p4runtime
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/win_wmi: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/win_wmi
telegraf/plugins/outputs/mqtt imports
	github.com/influxdata/telegraf/plugins/common/mqtt: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/common/mqtt
telegraf/plugins/parsers/json tested by
	telegraf/plugins/parsers/json.test imports
	github.com/influxdata/telegraf/internal/fuzz: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/internal/fuzz

**Comment by dp1140a** [comment]
Sorry I should have mentioned above that the list of what it does find is pretty long

go mod tidy
go: finding module for package github.com/coreos/go-systemd/daemon
go: finding module for package github.com/influxdata/telegraf/internal/goplugin
go: finding module for package github.com/influxdata/telegraf/agent
go: finding module for package github.com/influxdata/telegraf/logger
go: finding module for package github.com/influxdata/telegraf/plugins/aggregators/all
go: finding module for package github.com/influxdata/telegraf
go: finding module for package github.com/influxdata/telegraf/internal/choice
go: finding module for package github.com/influxdata/telegraf/plugins/inputs
go: finding module for package github.com/influxdata/telegraf/plugins/serializers/influx
go: finding module for package github.com/influxdata/telegraf/config
.
.
.
go: found google.golang.org/protobuf/types/known/emptypb in google.golang.org/protobuf v1.28.1
go: finding module for package github.com/bmizerany/assert
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/p4runtime
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/win_wmi
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/opensearch_query
go: finding module for package github.com/influxdata/telegraf/plugins/common/mqtt
go: finding module for package github.com/influxdata/telegraf/internal/fuzz
go: found github.com/bmizerany/assert in github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869
go: finding module for package github.com/influxdata/telegraf/internal/fuzz
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/opensearch_query
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/p4runtime
go: finding module for package github.com/influxdata/telegraf/plugins/inputs/win_wmi
go: finding module for package github.com/influxdata/telegraf/plugins/common/mqtt
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/opensearch_query: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/opensearch_query
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/p4runtime: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/p4runtime
telegraf/plugins/inputs/all imports
	github.com/influxdata/telegraf/plugins/inputs/win_wmi: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/inputs/win_wmi
telegraf/plugins/outputs/mqtt imports
	github.com/influxdata/telegraf/plugins/common/mqtt: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/plugins/common/mqtt
telegraf/plugins/parsers/json tested by
	telegraf/plugins/parsers/json.test imports
	github.com/influxdata/telegraf/internal/fuzz: module github.com/influxdata/telegraf@latest found (v1.25.2), but does not contain package github.com/influxdata/telegraf/internal/fuzz

**Comment by powersj** [comment]
```
root@j:~# go version
go version go1.19.6 linux/amd64
root@j:~# git clone https://github.com/influxdata/telegraf
Cloning into 'telegraf'...
remote: Enumerating objects: 80149, done.
remote: Counting objects: 100% (631/631), done.
remote: Compressing objects: 100% (554/554), done.
remote: Total 80149 (delta 134), reused 307 (delta 73), pack-reused 79518
Receiving objects: 100% (80149/80149), 55.42 MiB | 21.75 MiB/s, done.
Resolving deltas: 100% (48643/48643), done.
root@j:~# cd telegraf/
root@j:~/telegraf# git rev-parse HEAD
6a2f6f301f834edd3608e37194f95e3238f80e04
root@j:~/telegraf# go mod tidy
go: go.mod file indicates go 1.20, but maximum version supported by tidy is 1.19
```

Are you manually updating the go.mod file? In any case, I was able to run it with no issues.

Are you importing telegraf into your code where you are running go mod tidy? It is not clear why I see references v1.25.2 when you said you are checking out master.

**Comment by dp1140a** [comment]
No manual updating.   Steps were:

```
git clone https://github.com/influxdata/telegraf.git
cd telegraf
go mod tidy
```

I had also opened the code in Goland which could not sync dependencies either. 

BUT something changed.  I deleted the folder here and started form scratch. 
```
git clone https://github.com/influxdata/telegraf.git
cd telegraf
go mod tidy
go: go.mod file indicates go 1.20, but maximum version supported by tidy is 1.19
make
... lots of output
CGO_ENABLED=0 go build -ldflags " -X github.com/influxdata/telegraf/internal.Commit=6a2f6f30 -X github.com/influxdata/telegraf/internal.Branch=master -X github.com/influxdata/telegraf/internal.Version=1.26.0-6a2f6f30" ./cmd/telegraf
```

which worked.  Not sure what happened but yeah.

**Comment by divyakasi-web** [comment]
i am getting the below error in ci/cd pipeline after upgraded the go version from 1.19 to 1.20. After that i was upgraded the mod version also. but still issue is not resolved. please give me a solution for this. 

**go: go.mod file indicates go 1.20, but maximum version supported by tidy is 1.19
Running after_script
00:02
Running after script...
$ if [ "$ONEPIPELINE_PROJECT_NAME" != "" ]; then cd $CI_PROJECT_DIR; . ./functions.sh; source $CI_BUILDS_DIR/$variablesFile.txt; assert_stage; fi
variablesFile.txt already exist
cicd_pipelineId=35397
cicd_pipeline_name=tns-ays-service
cicd_pipeline_dev_poc=ashok.kumar.reddy.mandlem@verizon.com,manikandan.elumalai@verizon.com
cicd_pipeline_qe_poc=ashok.kumar.reddy.mandlem@verizon.com,manikandan.elumalai@verizon.com
cicd_pipelineBuildId=1173301
Inside assert_stage
https://prest-uat.ebiz.verizon.com/cicd/public/stageList?pipelineId=35397
4860773
https://prest-uat.ebiz.verizon.com/cicd/public/stageBuilds?pipelineBuildId=1173301&stageId=4860773
https://prest-uat.ebiz.verizon.com/cicd/public/stageBuilds?pipelineBuildId=1173301
[{"buildId": 37763116, "endTime": null, "stageId": 4860773, "duration": null, "startTime": "2025-01-24T10:48:14", "updatedOn": "2025-01-24T10:48:14", "actualValue": null, "buildStatus": "In Progress", "buildMessage": "37763116", "stageBuildId": 5619375, "artifactoryUrl": null, "actualValueJson": null, "pipelineBuildId": 1173301, "qualityGateValue": null, "buildBreakerValue": null, "qualityGateValueJson": null}]
2025-01-24T10:48:14
-------  STAGE BUILD START TIME -----------
BUILD DURATION SECS ::2
https://prest-uat.ebiz.verizon.com/cicd/public/stageBuilds?pipelineBuildId=1173301&stageId=4860773
{ "buildId": 37763116, "updatedOn": "2025-01-24 10:48:16", "endTime": "2025-01-24 10:48:16", "duration": "2", "actualValue": null, "buildStatus": "failure", "buildMessage": 37763116, "qualityGateValue": null, "buildBreakerValue": null }
--------- PREST STAGE PIPELINE BUILD ID UPDATE RESP ----------
{"rows_affected":1}
CHECKING IF STAGE IS BUILD
FOUND THAT STAGE IS BUILD, CALLING BUILD PACKAGE FN FOR UPDATING PACKAGE DETAILS
-------  CHECKING IF APP_PACKAGE_NAME & APP_PACKAGE_URL ARE DEFINED OR NOT -----------
-------  APP_PACKAGE_NAME & APP_PACKAGE_URL ARE NOT DEFINED -----------
CHECKING IF STAGE IS DEPLOY
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1**
