### ISSUE TITLE
Unable to start telegraf.service after fresh install, with working config

### ISSUE THREAD

**Issue by runningAgain** [influxdata/telegraf#12743]
### Relevant telegraf.conf

```toml
[global_tags]
# Configuration for telegraf agent

[agent]
interval = "10s"
round_interval = true
metric_batch_size = 10000
metric_buffer_limit = 100000
collection_jitter = "0s"
flush_interval = "30s"
flush_jitter = "0s"
precision = ""
debug = true
quiet = false
logfile = "/var/log/telegraf.log"
hostname = "awscentos"
omit_hostname = false

###############################################################################
# OUTPUT PLUGINS #
###############################################################################
# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
urls = ["http://XXX.XXX.XXX.XXX:8086"]
database = "XXX"
retention_policy = "XXX"
write_consistency = "any"
timeout = "10s"
username = "XXX"
password = "XXX"
user_agent = "linux_telegraf"

###############################################################################
# INPUT PLUGINS #
###############################################################################
[[inputs.cpu]]
percpu = true
totalcpu = true
collect_cpu_time = false

[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs", "nfs4"]

[[inputs.diskio]]
devices = ["nvme0n1p2"]
skip_serial_number = false

[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]

[[inputs.procstat]]
pattern = "java"
process_name = "java"
```

### Logs from Telegraf

```text
see the following log if i start telegraf on commandline (not as a service !!!):

[root@ip-10-0-13-155 centos]# tail -f /var/log/telegraf.log
2023-02-25T16:22:26Z I! Loaded secretstores:
2023-02-25T16:22:26Z I! Loaded outputs: influxdb
2023-02-25T16:22:26Z I! Tags enabled: host=awscentos
2023-02-25T16:22:26Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"awscentos", Flush Interval:30s
2023-02-25T16:22:26Z D! [agent] Initializing plugins
2023-02-25T16:22:26Z D! [agent] Connecting outputs
2023-02-25T16:22:26Z D! [agent] Attempting connection to [outputs.influxdb]
2023-02-25T16:22:26Z W! [outputs.influxdb] When writing to [http://XXX.XXX.XXX.XXX:8086]: database "XXX" creation failed: 403 Forbidden
2023-02-25T16:22:26Z D! [agent] Successfully connected to outputs.influxdb
2023-02-25T16:22:26Z D! [agent] Starting service inputs
2023-02-25T16:22:56Z D! [outputs.influxdb] Wrote batch of 51 metrics in 24.747196ms
2023-02-25T16:22:56Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2023-02-25T16:23:26Z D! [outputs.influxdb] Wrote batch of 54 metrics in 10.670334ms
2023-02-25T16:23:26Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
```

### System info

Telegraf 1.25.2, CentOS Linux release 8.5.2111 (aarch64)

### Steps to reproduce

1. clean install on a CentOS Linux release 8.5.2111 (aarch64) system with yum install telegraf
2. try to start / restart service will fail with below messages
3.
...

### Expected behavior

service starts successfully

### Actual behavior

Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Starting Telegraf...
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513aac]
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: goroutine 1 [running]:
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.Purge.func1(0x40001878e8?)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x2c
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.Purge()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.Panic({0x4869000, 0x400007a9c0})
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x288
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.NewCoffer()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x60
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]: github.com/awnumar/memguard/core.init.0()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1466]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 1.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Stopped Telegraf.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Starting Telegraf...
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513aac]
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: goroutine 1 [running]:
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.Purge.func1(0x40001878e8?)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x2c
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.Purge()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.Panic({0x4869000, 0x400007a9a0})
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x288
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.NewCoffer()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x60
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]: github.com/awnumar/memguard/core.init.0()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1471]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 2.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Stopped Telegraf.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Starting Telegraf...
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513aac]
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: goroutine 1 [running]:
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.Purge.func1(0x40001fd8e8?)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x2c
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.Purge()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.Panic({0x4869000, 0x400010c960})
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x24
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x288
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.NewCoffer()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x60
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]: github.com/awnumar/memguard/core.init.0()
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1476]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:47 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 3.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Stopped Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Starting Telegraf...
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513aac]
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: goroutine 1 [running]:
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.Purge.func1(0x40001878e8?)
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x2c
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.Purge()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.Panic({0x4869000, 0x400007a9a0})
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x24
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x288
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.NewCoffer()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x60
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]: github.com/awnumar/memguard/core.init.0()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1481]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 4.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Stopped Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Starting Telegraf...
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513aac]
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: goroutine 1 [running]:
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.Purge.func1(0x40001fb8e8?)
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x2c
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.Purge()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.Panic({0x4869000, 0x400010c960})
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x24
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x288
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.NewCoffer()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x60
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]: github.com/awnumar/memguard/core.init.0()
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal telegraf[1486]:         /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Stopped Telegraf.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Start request repeated too quickly.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 25 16:14:48 ip-10-0-13-155.eu-central-1.compute.internal systemd[1]: Failed to start Telegraf.

### Additional info
[root@ip-10-0-13-155 centos]# yum list installed | grep telegraf
telegraf.aarch64                    1.25.2-1                                   @influxdata
[root@ip-10-0-13-155 centos]# cat /etc/yum.repos.d/influxdata.repo
[influxdata]
name = InfluxData Repository - Stable
baseurl = https://repos.influxdata.com/stable/$basearch/main
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key
[root@ip-10-0-13-155 centos]#

**Comment by powersj** [comment]
When you say you are running as a service, are you also running it in a container? That panic is from the external library we use for secret store report. It means it was unable to reserve memory space.

**Comment by ChrisLoubser-Mytra** [comment]
I am seeing the same thing, and not using any secret stores

**Comment by powersj** [comment]
> I am seeing the same thing, and not using any secret stores

It would be far more useful to respond with logs, a config, and anything else we need to know to reproduce the issue. Thanks
