### ISSUE TITLE
Upgrade mssql/sqlserver plugins from `denisenkom/go-mssqldb` to `microsoft/go-mssqldb`

### ISSUE THREAD

**Issue by cruscio** [influxdata/telegraf#12745]
### Use Case

Microsoft has forked [denisenkom/go-mssqldb](https://github.com/denisenkom/go-mssqldb), and in the parent repo [README](https://github.com/denisenkom/go-mssqldb#readme), denisenkom now recommends using the [fork](https://github.com/microsoft/go-mssqldb) for more recent updates. 

If the original isn't going to be maintained, should the following plugins (along with various documentation/testing references; screenshot below) be updated to use the Microsoft library? 

For example:
- [sql](https://github.com/influxdata/telegraf/blob/a90b6eb119b0b60fb504d43ce926365814f98147/plugins/inputs/sql/drivers.go#L6) Input
- [sql](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/sql/sql.go#L13) Output
- [sqlserver](https://github.com/influxdata/telegraf/blob/a90b6eb119b0b60fb504d43ce926365814f98147/plugins/inputs/sqlserver/sqlserver.go#L15) Input (note: there are multiple imports of the library in this input plugin's code)

### Expected behavior

N/A

### Actual behavior

N/A

### Additional info

![image](https://user-images.githubusercontent.com/30699280/221572731-1979d6af-fa81-4aa1-88c3-f4a2fc824b92.png)

**Comment by powersj** [comment]
Hi,

I think it makes sense, however, this is not a simple find and replace. This will require a good deal of testing from users as well.

It seems that a number of the Azure related libraries are updated with quite a number of changes. I got most of them figured out, but `github.com/logzio/azure-monitor-metrics-receiver` is giving me grief. It appears it pulls in the older `armmonitor` and `armresource` packages, which would need to be updated first. Additionally, some changes to how we call things in the azure monitor plugins.

I have PR #12748 as a draft and will look at it a bit more later or if someone wants to take it and run with it, that would be most helpful as well.

**Comment by powersj** [comment]
I filed an upstream issue with azure-monitor-metircs-receiver around updating their dependencies: https://github.com/logzio/azure-monitor-metrics-receiver/issues/2

**Comment by powersj** [comment]
For those watching this issue, I have put up #13524 with the migration now that the logzio dependency was updated. It would be great to have feedback if the migration works successfully.
