### ISSUE TITLE
Publish windows/amd64 telegraf image

### ISSUE THREAD

**Issue by shubham1172** [influxdata/telegraf#12760]
### Use Case

Users who want to run their workloads on Windows nodepool on Kubernetes require images to support windows/amd64. The alternate option today is to write your own Dockerfile which uses the Telegraf Windows binary.

### Expected behavior

windows/amd64 should be a supported platform.

### Actual behavior

Only linux/*** platforms are supported.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/22132944/221755594-637218e5-fa9d-4b6d-a304-7076bb77eb86.png">

**Comment by powersj** [comment]
Thanks for the issue request. I am curious to see if others would find this useful.

**Comment by powersj** [comment]
Hi,

We talked about this internally with security, product, and engineering and considered including this in future releases. We unfortunately decided against hosting an official telegraf image based on a Windows image at this time.

While this is probably not what you were hoping to hear, we do appreciate you putting up the feature request. If interest in this does greatly change overtime we could revisit this at a later date.

Thanks again!
