### ISSUE TITLE
Add name to IP addresses in Ping plugin

### ISSUE THREAD

**Issue by csupi003** [influxdata/telegraf#12761]
### Use Case

I would like to name the IP addresses in the config file.
FQDN is not an option because it's different how I would like to name them. 
It would be easier to name them once rather that in InfluxDB query. 

### Expected behavior

Ability to add names to IP addresses in Ping plugin

### Actual behavior

Only possible via InfluyDB query

**Comment by powersj** [comment]
Hi,

How many IP addresses do you have in your config?
Are you looking to add a tag like `name="hosta"` for example?

**Comment by csupi003** [comment]
Hi, 
Exactly like that. 
Just started using it but I can already count 70+ for which I would like to do it.

**Comment by powersj** [comment]
I do not see us adding a "name" tag to the plugin itself. This is a very specific request for your use-case and as such my suggestion is to do this with starlark. 

Namely, you can keep a dictionary of ip's and names and loop through the metrics adding the name tag when an IP is matched.

```toml
[[outputs.file]]

[[inputs.ping]]
  urls = ["192.168.1.1", "192.168.1.2"]

[[processors.starlark]]
  source = '''
lookup = {
    "192.168.1.1": "hosta"
}

def apply(metric):
    if metric.tags["url"] and metric.tags["url"] in lookup:
        metric.tags["name"] = lookup[metric.tags["url"]]

    return metric
'''

```

**Comment by csupi003** [comment]
Starlark worked perfectly!
Thanks a lot for the suggestion.
