### ISSUE TITLE
 Error loading config file  with tls_renegotiation_method

### ISSUE THREAD

**Issue by Majic-eyes** [influxdata/telegraf#12768]
### Please direct all support questsions to slack or the forums. Thank you.

Hello, just adding this parameter ( tls_renegotiation_method (once, freely or never)  to my config file provoke an error  as below : 

2023-02-28T22:34:52Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/http_response_ATLIHM.conf: plugin inputs.http_response: line 1: configuration specified the fields ["tls_renegotiation_method"], but they weren't used

Do you have any idea why ?

I had this error : 
 local error: tls: no renegotiation
so i wanted to set this parameter and it doesnt seem to work...

Thank you 
regards

**Comment by powersj** [comment]
> configuration specified the fields ["tls_renegotiation_method"], but they weren't used

This usually means you are running a version of telegraf that does not know or understand that field.

**Comment by Majic-eyes** [comment]
Oh Thank you for your quick answer.
I'll see if we can upgrade it then.

Regards
