### ISSUE TITLE
[inputs.conntrack] : Error in plugin: failed to retrieve conntrack statistics: open /proc/net/stat/nf_conntrack: no such file or directory"

### ISSUE THREAD

**Issue by BhumikaMatharu** [influxdata/telegraf#12773]
### Please direct all support questsions to slack or the forums. Thank you.

I am trying to use the latest metrics added in inputs.conntrack. I am using ubuntu 18.04
Getting the following error, is this input plugin kernel/OS dependent?

![image](https://user-images.githubusercontent.com/50544476/222287509-39ff581d-a4d5-4745-9f1c-0a1df22a3d78.png)

Here is some debugging I did,
In the telegraf code, I see the plugin is looking for these directories : dirs = ["/proc/sys/net/ipv4/netfilter","/proc/sys/net/netfilter"] which is what I added in config.

On inspecting https://github.com/shirou/gopsutil/tree/master/net/net_linux.go
I saw the file path '/proc/net/stat/nf_conntrack' is getting picked from here https://github.com/shirou/gopsutil/blob/master/net/net_linux.go#:~:text=return%20conntrackStatsFromFile(common.HostProc(%22net/stat/nf_conntrack%22)%2C%20percpu)

Is it overriding whatever path we give in config?

I found this related feature request - https://github.com/influxdata/telegraf/issues/8955 but the fix for it seems to be something else.

Would be helpful if you can shed some light on this as this is breaking the telegraf.

**Comment by powersj** [comment]
Talk on slack, summary here:

There are two collections that take place in the conntrack plugin. The first uses the directories and files that you specify in your config (e.g. files and dirs. The second use the  options from collect. That is where gopsutil comes in and it will gather additional values.

Your error message says "no such file or directory", which means telegraf either cannot see that file or it truly does not exist.
