### ISSUE TITLE
Allow input.prometheus to select pods based on namespace annotation

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12776]
### Use Case

It is quite common for Kubernetes namespace to store flags/settings in form of annotations. One example is whether namespace is a production or dev environment.  It would be nice if input.prometheus can filter pods based on namespace annotations.

### Expected behavior

Config option similar to `tagpass`/`tagdrop`, but for namespace annotation. If namespace tags match `annotation_pass` then pods in namespace are further considered for scraping, subject to other plugin settings. Likewise for `annotation_drop`: when matches, pods wont be scraped.

### Actual behavior

-

**Comment by powersj** [comment]
next steps: wrap up PR reviews
