### ISSUE TITLE
Allow RS485 mode in MODBUS Plugin

### ISSUE THREAD

**Issue by AfdhalAtiffTan** [influxdata/telegraf#12784]
### Use Case

I would like a Raspberry Pi (or any SBC) to be able to drive TX, RX, and RTS pins for driving an RS485 transceiver (e.g. MAX3430).

### Expected behavior

Duplex communication should be reduced to simplex on the UART. At the moment I had to drive the tri-state pin via TX pin like this [schematic](https://www.abelectronics.co.uk/docs/pdf/schematic-rs485pi.pdf).

### Actual behavior

RTS pin is not driven. As a result the TX and RX are looped.

### Additional info

I have tried using stty to allow for "crtscts" option, but it appears that the MODBUS plugin automatically disables it.

**Comment by srebhan** [comment]
@AfdhalAtiffTan can you please test the binary built in PR #12786 once CI finished the tests!? Let me know if this fixes your problem.

**Comment by srebhan** [comment]
Any testing results @AfdhalAtiffTan?

**Comment by AfdhalAtiffTan** [comment]
Hi @srebhan,

Sorry not yet as I have other priority at the moment. Will revisit later.

Thank you.

**Comment by AfdhalAtiffTan** [comment]
Hi @srebhan 

Just had a quick play and I received this error:
`E! error loading config file telegraf.toml: error parsing modbus, line 42: (serial.RS485Config.DelayRtsBeforeSend) cannot unmarshal TOML string into time.Duration`

I am not familiar with Golang, any advice?

Thank you.

**Comment by srebhan** [comment]
@AfdhalAtiffTan thanks for testing and finding the issue. Can you please give the fixed binary in the PR a second try!?

**Comment by AfdhalAtiffTan** [comment]
@srebhan 

Using:
```
[inputs.modbus.rs485]
## Delay RTS prior to sending
delay_rts_before_send = "2ms"
## Delay RTS after to sending
delay_rts_after_send = "2ms"
## Pull RTS line to high during sending
rts_high_during_send = true
## Pull RTS line to high after sending
rts_high_after_send = false
## Enabling receiving (Rx) during transmission (Tx)
rx_during_tx = false
```

TX appears to be working:
![TEK00001](https://user-images.githubusercontent.com/7511333/223435730-fc74d9cf-4d92-4c65-9f33-b516196edfaa.PNG)

I can't test RX at the moment but I believe it should be working ok.

Thank you!

**Comment by srebhan** [comment]
Thanks for testing @AfdhalAtiffTan. Will try to get this merged then. If you run into problems in further tests, please file an issue!

**Comment by AfdhalAtiffTan** [comment]
Will do.

Thank you!
