### ISSUE TITLE
[inputs.sqlserver] SERVERPROPERTY(''IsHadrenabled'')

### ISSUE THREAD

**Issue by soccypowa** [influxdata/telegraf#12799]
### Use Case

My case is that I have a little "quick info" panel in my Grafana dashboard, as in #12351 IsClustered is added, it would be usefull to have the information of IsHadrenabled at hand to if the instance is part of an Availability Group setup, in my case the later one is more present then the former, a great addition would be to have at hand information about who is Primary.

### Expected behavior

Expected is to have the serverproperty IsHadrenabled at hand to display in such an information panel, as IsClustered is available today.

### Actual behavior

It is not available

**Comment by powersj** [comment]
Happy to take see a PR with the change!

next steps: look into what is required for this property

**Comment by soccypowa** [comment]
I've been meaning to get back on this issue, as I think it is simple enough so even I can fix it, but there is some design consideration, and surely a best practice, on how to best implement it.

Ive been looking at #12351 and the implementation of the IsClustered property, as they are virtually the "same". What gets me here is the choice to make IsClustered into the field "instance_type", to me I think of Availability Group participants as an "instance type" too. I don't know if that is symanticly correct or not. Anyway.

Either you just put this as another field right along the row of other fields, calling it something like "IsHadrenabled".

OR you could make the field Instance_type into something holding other values than 0 and 1, for example you could extend it to 2 when IsHadrenabled is set to 1, or if both IsClustered and IsHadrenabled (obviously this is a possibility) is set to 1, setting it to 3. The 0 and 1 keeping their original meaning to not break any current implementation.

What would be the best approach here?

**Comment by powersj** [comment]
@Trovalo any guidance on this idea?

**Comment by soccypowa** [comment]
We're gonna do this in a local build instead...

**Comment by srebhan** [comment]
@soccypowa sorry to hear. I would really love to see this in Telegraf. In case you reconsider your decision, please feel free to ping us for a review in timely manner!

**Comment by soccypowa** [comment]
@srebhan Ah, I reopen it then, and lets see what happens 🙃

**Comment by Trovalo** [comment]
@srebhan  I've got nothing against it, I just don't find it that useful, the code is pretty easy and correct... it can already be merged

here is the reason (from the PR conversation)
> {...}
> Also, the properties just says if the feature is enabled, and that does not mean it's actually used...
> Do you want to check if the feature is enabled? you can use that property...
> Do you want to check if the feature is actually used? that property is not enough...
> 
> I'd query the usage and maybe check how many "Always On availability groups" I've got on the instance
