### ISSUE TITLE
Creating Static Database in Telegraf during run time

### ISSUE THREAD

**Issue by pratikdas44** [influxdata/telegraf#12803]
### Use Case

I need to add some meta-data information in telegraf at run-time, the source of information will be External file. The idea is to insert meta-data into influxdb, along with incoming data (which is kafka here) as fast as possible.

### Expected behavior

Telegraf should be able during read from file during processing time, and add the information to each metrics.

### Actual behavior

Using execd processor, however not able read the metrics. 

### Additional info

Question asked in community - https://community.influxdata.com/t/creating-static-database-in-telegraf-in-run-time/28822

**Comment by srebhan** [comment]
@pratikdas44 I think using a json file would be the best here. Does that work for you?

**Comment by pratikdas44** [comment]
I can manage that, if that works fine and is faster.

**Comment by srebhan** [comment]
@pratikdas44 can you please test the binary in PR #12809 once CI finished the tests!? You should use a config similar to [this unit-test](https://github.com/influxdata/telegraf/tree/a90226a39b0c2953bf1d147dd7d0cc3dd300d466/plugins/processors/lookup/testcases/normal_lookup_csv_key_name_value) i.e.

```toml
[[processors.lookup]]
    files = ["testcases/normal_lookup_csv_key_name_value/lut.csv"]
    format = "csv_key_name_value"
    key = '{{.Tag "your-tag-name"}}'
```

and a CSV file in the form

```csv
key-tagvalue-A,tag-name-to-add1,tag-tag-value-to-add1,...,tag-name-to-addN,tag-tag-value-to-addN
...
key-tagvalue-Z,tag-name-to-add1,tag-tag-value-to-add1,...,tag-name-to-addM,tag-tag-value-to-addM
```

Let me know if this fixes your issue!

**Comment by pratikdas44** [comment]
Processor Plugin working fine as expected.
