### ISSUE TITLE
Need less inputs, how can I control the inputs?

### ISSUE THREAD

**Issue by SpaHuang** [influxdata/telegraf#12816]
### Please direct all support questsions to slack or the forums. Thank you.

The telegraf file is to big, I don't need all of inputs, how can I control the inputs when I build it. Thanks for answer.

**Comment by srebhan** [comment]
@SpaHuang Telegraf will only load the plugins you configure. You might want to look at the filter command-line options
```text
   --section-filter value                                 filter the sections to print, separator is ':'. Valid values are 'agent', 'global_tags', 'outputs', 'processors', 'aggregators' and 'inputs'
   --input-filter value                                   filter the inputs to enable, separator is ':'
   --output-filter value                                  filter the outputs to enable, separator is ':'
   --aggregator-filter value                              filter the aggregators to enable, separator is ':'
   --processor-filter value                               filter the processors to enable, separator is ':'
   --secretstore-filter value                             filter the secret-stores to enable, separator is ':'
```
when creating the config.

If your concern is the size of the **Telegraf binary** itself, [this blog](https://www.influxdata.com/blog/how-reduce-telegraf-binary-size/) might be interesting for you.
