### ISSUE TITLE
Ability to drop metrics with certain age from the buffer

### ISSUE THREAD

**Issue by butschi84** [influxdata/telegraf#12833]
### Use Case

- We use telegraf to ingest metrics into mimir (outputs.http)
- Mimir has a setting (configurable), that will not accept metrics when the timestamp is offset / to old (for example 2 minutes)
- If we assume that mimir has a temporary problem (is not reachable for 1h) and then comes up again, all telegraf agents will try to send old data from their buffer

### Expected behavior

Telegraf agent should have a global setting to just drop data out of the buffer, when the data has a timestamp of certain age (configurable)

### Actual behavior

Telegraf agent will fail to send any data after mimir had a temporary outage - because it tries always to send the oldest data first. 
To fix the issue, the agent has to be restarted in order to clear the buffer

**Comment by powersj** [comment]
Hi,

> mimir

Does mimir respond with a 4xx return code when the metrics are too old? If so, I believe the `non_retryable_statuscodes = [409, 413]` option could be used to toss the metrics that it won't accept.
