### ISSUE TITLE
FreeBSD invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wanted156** [influxdata/telegraf#12838]
Hey,

so i've downloaded the binary from the github releases, the FreeBSD amd64 version. I've extracted it with tar xf {filename}, and once I go into the extracted directory, usr, bin and try to start the file, I get the following:

```
root@grafana:~/tmp/telegraf-1.25.3/usr/bin # ./telegraf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99407f]

goroutine 1 [running]:
github.com/awnumar/memguard/core.Purge.func1(0xc0002af930)
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x3f
github.com/awnumar/memguard/core.Purge()
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x25
github.com/awnumar/memguard/core.Panic({0x5291980, 0xc0001ae6e0})
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85 +0x25
github.com/awnumar/memguard/core.NewBuffer(0x20)
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x2d5
github.com/awnumar/memguard/core.NewCoffer()
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:30 +0x34
github.com/awnumar/memguard/core.init.0()
        /go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x2e
root@grafana:~/tmp/telegraf-1.25.3/usr/bin #
```

I also tried to build the package myself from the source code, but eventually stumbled across the same issue. I saw an older issue where this was supposedly fixed, maybe I am missing something?

**Comment by powersj** [comment]
To confirm, are you doing this in a jail? Take a look at https://github.com/influxdata/telegraf/issues/12502 and https://github.com/influxdata/telegraf/tree/master/plugins/secretstores/os#systemd-nspawn which is specific to `systemd-nspawn`, but it applies to jails if so

**Comment by wanted156** [comment]
Yep I confirm, this was done in a jail. I just took a look in the linked issue and it indeed was the mloc/sysvipc property that had to be set. Maybe mention that the same issue is present in a jail on the readme page, hopefully it will avoid some new duplicate issues :) It works now, thank you for the quick help!

**Comment by hardwareadictos** [comment]
Same issue here into a TrueNAS Jail
