### ISSUE TITLE
inputs.prometheus:  fine grained control over pod labels/annotations as tags

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12850]
### Use Case

Often just a subset of pod label/annotations requires to be included as tags. Existing `taginclude`/`tagexclude` is too coarse as they work on a set of tags combined from prometheus labels, pod annotations and labels, global tags, etc. Currently there is no way to express "include just this pod label as a metric tag".

### Expected behavior

New config options which act like `taginclude`/`tagexclude`, but as acting on pod labels and annotations exclusively , before they are added to metric tag set.

### Actual behavior

-

**Comment by powersj** [comment]
Thanks for the issue and the PR to go along with it.

next steps: review the PR

**Comment by srebhan** [comment]
@redbaron can you provide an example of unfiltered metrics and what you want to filter for me to understand? Is the problem that the tag-name is constructed from multiple parts?

**Comment by redbaron** [comment]
Assuming there is a pod with annotation keys: `[ a1,a2,a3 ]` which produces prometheus metric with labels `[ l1, l2, l3]`.

If I'd like to keep just subset of annotations as metric tag, I can't say `taginclude: [a1]`, because it will drop all labels, I have to do `tagexclude: [a2, a3]`. Problem with that is:
- there are dozens of annotations/labels per pod
- those labels are added/removed as the way apps are deployed to the cluster change.

So `tagexclude` have to be constantly kept up to date with whatever a teams are doing on the cluster. 

With my proposed change it is no necessary anymore, we know set of annotations we'd like to see as metric tag and we pick just them, ignoring anything else:

`pod_annotation_include: [a1]`

**Comment by redbaron** [comment]
@srebhan, did I answer your question?

**Comment by redbaron** [comment]
@srebhan , @powersj , this is an important change for us as it allows managing metric collection in Kubernetes clusters more sanely. I am keeping PR mergeable by rebasing it for now, but would like to have some conclusions on this feature if possible.
