### ISSUE TITLE
Cannot use timeout for inputs.prometheus plugin with v1.26.0

### ISSUE THREAD

**Issue by jheinitz** [influxdata/telegraf#12859]
### Relevant telegraf.conf

```toml
# Original Config:
# ----------------
[[inputs.prometheus]]
   urls = ["http://127.0.0.1:8779/metrics"]
   username = "*****"
   password = "*****"
   response_timeout = "10s"
   [inputs.prometheus.tags]
     component = "kafka"

# Adapted Config:
# ----------------
[[inputs.prometheus]]
   urls = ["http://127.0.0.1:8779/metrics"]
   username = "*****"
   password = "*****"
   # response_timeout = "10s"
   timeout = "10s"
   [inputs.prometheus.tags]
     component = "kafka"
```

### Logs from Telegraf

```text
Log for Original Config:
------------------------
2023-03-14T10:20:25Z I! Loading config file: /etc/telegraf/telegraf.d/in.jmx_prometheus-kafka.conf
2023-03-14T10:20:25Z W! DeprecationWarning: Option "response_timeout" of plugin "inputs.prometheus" deprecated since version 1.26.0 and will be removed in 2.0.0: use 'timeout' instead

Log for Adapted Config:
-----------------------
2023-03-14T10:21:40Z I! Loading config file: /etc/telegraf/telegraf.d/in.jmx_prometheus-kafka.conf
2023-03-14T10:21:40Z E! error loading config file /etc/telegraf/telegraf.d/in.jmx_prometheus-kafka.conf: error parsing prometheus, line 6: field corresponding to `timeout' in prometheus.Prometheus cannot be set through TOML
```

### System info

Telegraf v1.26.0, RHEL 8.6 Docker 20.10.17

### Steps to reproduce

1. Use original config from above
2. Launch telegraf container
3. see warning in log (see above)
4. modify config to use timeout instead of response_timeout
5. restart telegraf container
6. see error in log (see above)
...

### Expected behavior

Telegraf should no longer issue a warning and accept the new parameter `timeout = "10s"` and should start up.

### Actual behavior

Telegraf complains about the parameter `timeout = "10s"` and does not start

**Comment by powersj** [comment]
@jheinitz,

Thanks for the quick issue. I have put up #12864 with a fix, it seems we did not get the deprecation quite right. For now, you can continue to use `response_timeout` to set the timeout.

Thanks again

**Comment by jheinitz** [comment]
Hello,

I just wanted to let you know that I validated the fix using the latest nightly. The deprecation warning is only shown when the response_timeout parameter is present and I was able  to add the `timeout:` parameter.

Thanks for the quick fix and for your great work!

Kind regards

Jens

**Comment by powersj** [comment]
Thank you for confirming!
