### ISSUE TITLE
Phusion Passenger input will exit without gathering metrics when xmllint is missing

### ISSUE THREAD

**Issue by martinseener** [influxdata/telegraf#1286]
### System info:

Telegraf 0.13.0
Debian Squeeze LTS

### Steps to reproduce:

Try to gather passenger stats with passenger-status and missing "xmllint" package on your system, passenger-status will output the following (i've left most of the XML but instead only the last part of it and the additional message which will break the input plugin since its no xml anymore

`</server_socket></server_sockets></process></processes></group></groups></info>
*** Tip: if you install the 'xmllint' command then the XML output will be indented.`

### Proposal:

Add this to the Unit tests and let the input try to ignore this last line and use the xml only so the input will work without xmllint anyways!

**Comment by sparrc** [comment]
wow, I can't believe passenger-status would do that, is there any way to turn it off?

**Comment by sparrc** [comment]
It looks like passenger-status will actually return JSON by default, which I would strongly prefer to xml. So the preferable solution to this bug would be to change the passenger plugin to parse JSON instead of XML.

**Comment by sparrc** [comment]
@martinseener can you try changing `passenger-status -v --show=xml` to `passenger-status --show=xml` and see if that fixes it?

**Comment by sparrc** [comment]
I've opened an issue with the phusion passenger project as well, because I think that this command should always produce machine-readable output: https://github.com/phusion/passenger/issues/1816

**Comment by martinseener** [comment]
Actually without `-v` the output will be the same. I've figured out that this Tip: line is being outputted as "STDERR.puts" so as STDERR instead of STDOUT, so if iam correct, os/exec.Command() in Go will only read the STDOUT thing in, but iam not 100% sure about this. If i am, it would mean that it's not actually a bug since it doesn't read the Tip line. Anyways iam getting `2016/05/27 14:01:31 Error in input [passenger]: exit status 1`
with the config
`[[inputs.passenger]]
  command = "/usr/local/rvm/bin/rvm all do passenger-status --show-xml -v"`
whereas i also have the following line in place in the sudoers file
`telegraf ALL=(ALL) NOPASSWD: /usr/local/rvm/bin/rvm all do passenger-status`

So iam not sure if its a problem with calling passenger-status or if the output makes problems. We're using passenger 3.0.12 here on this test machine (older one)

**Comment by sparrc** [comment]
in that case we can just use Output() instead of CombinedOutput() for this command to fix the issue

**Comment by martinseener** [comment]
But the code already says:
`exec.Command(cmd, args...).Output()` ... so this isn't really a bug, right??

**Comment by sparrc** [comment]
correct, that should only be reading stdout, so it appears that the command is actually pushing that to stdout not stderr.

**Comment by martinseener** [comment]
By the way, Passenger 4 also outputs this Tip-thing but the plugin should not care about that if it only reads STDOUT and not STDERR as well, so ill close this bug, since it's not really a bug ;) Thanks anyway!
