### ISSUE TITLE
Add compression for the file output plugin (prefereably zstd)

### ISSUE THREAD

**Issue by zekena2** [influxdata/telegraf#12875]
### Use Case

With compression enabled that will save storage as we keep these files in s3 for backfilling purposes. Right now we keep files in disk using the file output plugin until we've network connectivity and then put them in s3 for backfilling into influxdb later. Compression will save us disk space and object storeage costs.

### Expected behavior

Enable compression as an option with possible multiple algorithms, I'd prefer at least zstd to be available.

### Actual behavior

Not implemented for the file output plugin.

**Comment by abhi-jha** [comment]
Hi. I wanted to take up a few tasks to contribute and this looks interesting to me.

**Comment by zekena2** [comment]
Hey @abhi-jha, I didn't start yet as I'm busy with other stuff rn so you can go ahead and work on it but I've taken a look on the library that might be used and I found this one https://github.com/klauspost/compress which isn't dependant on CGO like most of the other wrappers like [datadog](https://github.com/DataDog/zstd) and [valyala](https://github.com/valyala/gozstd) ones but has assembly code instead (telegraf won't accept CGO afaik).

**Comment by abhi-jha** [comment]
I am happy to take it up. Wanted to have a quick chat with the maintainers on approaching this. I am still in exploratory phase and trying to see things around.

**Comment by zekena2** [comment]
This is the only discussion I saw https://github.com/klauspost/compress/pull/464 so benchmarking is needed to compare between the two platforms.
