### ISSUE TITLE
Linter: gosec, Rule: G106 - Audit the use of ssh.InsecureIgnoreHostKey. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12893]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G106 - Audit the use of ssh.InsecureIgnoreHostKey](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-322: Key Exchange without Entity Authentication](https://cwe.mitre.org/data/definitions/322.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1
