### ISSUE TITLE
Linter: gosec, Rule: G109 - Potential Integer overflow made by strconv.Atoi result conversion to int16/32. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12896]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G109 - Potential Integer overflow made by strconv.Atoi result conversion to int16/32](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-190: Integer Overflow or Wraparound](https://cwe.mitre.org/data/definitions/190.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1
