### ISSUE TITLE
Linter: gosec, Rule: G110 - Potential DoS vulnerability via decompression bomb. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12897]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G110 - Potential DoS vulnerability via decompression bomb](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-409: Improper Handling of Highly Compressed Data (Data Amplification)](https://cwe.mitre.org/data/definitions/409.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule following findings were found in current code:
```
internal/content_coding.go:258:11                     gosec  G110: Potential DoS vulnerability via decompression bomb
plugins/outputs/graylog/graylog_test_linux.go:154:12  gosec  G110: Potential DoS vulnerability via decompression bomb
plugins/outputs/logzio/logzio_test.go:75:12           gosec  G110: Potential DoS vulnerability via decompression bomb
plugins/outputs/sumologic/sumologic_test.go:250:14    gosec  G110: Potential DoS vulnerability via decompression bomb
```

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1

Potential fixes: https://stackoverflow.com/questions/67327323/g110-potential-dos-vulnerability-via-decompression-bomb-gosec
