### ISSUE TITLE
Linter: gosec, Rule: G108 - Profiling endpoint automatically exposed on /debug/pprof. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12895]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G108 - Profiling endpoint automatically exposed on /debug/pprof](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-200: Exposure of Sensitive Information to an Unauthorized Actor](https://cwe.mitre.org/data/definitions/200.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1

we have pprof behind an option so sounds harmless?

**Comment by zak-pawel** [comment]
@powersj Exactly, in Telegraf it is done properly.
