### ISSUE TITLE
Linter: gosec, Rule: G203 - Use of unescaped data in HTML templates. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12904]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G203 - Use of unescaped data in HTML templates](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')](https://cwe.mitre.org/data/definitions/79.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1 seems harmless to add, no?
