### ISSUE TITLE
Linter: gosec, Rule: G201 - SQL query construction using format string. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12902]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G201 - SQL query construction using format string](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')](https://cwe.mitre.org/data/definitions/89.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1
