### ISSUE TITLE
Windows input win_perf_counters

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/telegraf#1291]
First , this is starting to look really good - small cpu footprint when collecting quiete a few counters - almost as good as typeperf locally :)

Two problems ive encountered now on my first run:
1. Cannot use wildcards on instance names - would be nice to catch just a few chosen processes
   Instance = ["*beginningofanyprocessname*"]
2. Also, the value that gets written into influx maxes out at 100 even though the process is using more cpu% - on a 8core machine when running for example 7zip to creata an archine the 7zG process is using 5-600% of total 800% available but telegraf only enters 100 on %usage for the 7zG process.

**Comment by sparrc** [comment]
any ideas @TheFlyingCorpse?

**Comment by TheFlyingCorpse** [comment]
@discoduck2x: 
1) Right, this feature IS missing iirc. It could be implemented in a few ways, any suggestions on how you would write a query for it?
2) I am not doing anything to the values, it is how perfmon sees them.

An "issue" with the current implementation I did is that it doesnt re-check for new matches on the perfcounters regularly, say every 10 mins or so. Depending on how often you restart / start new instances, it might not show at all with Telegraf, which should also be looked at incase you fall under this.

**Comment by discoduck2x** [comment]
@TheFlyingCorpse 
1) unfortunatley im not a developer, mearly a metric thirsty tech ops, wish i could help
2) but then what are you using to check the counters? a "lib" or function/third party implementation? feels like that implementation somehow isnt getting the correct value for the process cpu counters , if you check with perfmon manually, or with typeperf , or with any other "standard" way to query performance counters you get the "correct" values. 

typeperf/perfmon gives this data:
![image](https://cloud.githubusercontent.com/assets/12600004/15887058/6c381418-2d60-11e6-9dde-67c732211c00.png)
...where telegraf simply will flat out with just 100 . . .  .

I've been until now using typeperf and dumping that into csv files which i later parse and ship to influx, its the most non cpu intrusive way to collect windows counters - 1-2% cpu and no spikes whatsoever while collecting alot of counters , but the way to process it is "ugly" and a good agent like telegraf would make it into everybody´s livingroom (windowspeeps)

**Comment by elvarb** [comment]
> 1) Right, this feature IS missing iirc. It could be implemented in a few ways, any suggestions on how you would write a query for it?
The easiest implementation and possibly the fastest is to just query * and then have telegraf do the filtering

**Comment by discoduck2x** [comment]
@elvarb but not sufficient,, for counters with many instances you will get a CPU spike/hit every time you query them, sure * is fine for non timecritical/lowlatency systems but for such its not ok to hog down your hosts.

**Comment by elvarb** [comment]
@discoduck2x Depends on the counter, some are extremely fast. The only other method is to query * when Telegraf starts and make independent queries out of the result.

**Comment by Prunar** [comment]
Any idea when this will be implemented? Really usefull for instances that change name. E.g. include runtime version in name.

**Comment by discoduck2x** [comment]
@TheFlyingCorpse @sparrc 
any updates? still not able to use telegraf for windows since both issues remain

**Comment by VVvKamper** [comment]
2. Also, the value that gets written into influx maxes out at 100 even though the process is using more cpu% - on a 8core machine when running for example 7zip to creata an archine the 7zG process is using 5-600% of total 800% available but telegraf only enters 100 on %usage for the 7zG process.

This is because of missing `PDH_FMT_NOCAP100` flag on `pdh_GetFormattedCounterValue` [(source)](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/pdh.go#L334) and `pdh_GetFormattedCounterArrayW` [(source)](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/pdh.go#L381) calls. I fixed this in local installation, but i'm not sure how it will affect the rest of the win perf counters.

**Comment by discoduck2x** [comment]
@VVvKamper nice catch - any chance you providing a test bin for dl somewhere?

**Comment by VVvKamper** [comment]
Yes, i uploaded it on https://ufile.io/4ecb6. Builded from 1.2.1 tag with following fix.

Fix was just to change format option from `uintptr(PDH_FMT_DOUBLE)` to `uintptr(PDH_FMT_DOUBLE|PDH_FMT_NOCAP100)`.

**Comment by sparrc** [comment]
wow, good catch, can you submit a PR @VVvKamper?

Windows is really something else 🤦‍♂️

**Comment by discoduck2x** [comment]
@sparrc - both species can cooexist in perfect harmony...almost....well ok they should in theory

**Comment by VVvKamper** [comment]
@sparrc I submitted PR. Feel free to ask for changes cause it's my first PR :)

**Comment by discoduck2x** [comment]
still no update to #1 on this one?

**Comment by christianhill** [comment]
Just started using Telegraf, quite impressed with what I'm seeing so far.

However, I too would like to see the ability to use wildcards on instance names, if possible. It'd be a pain to have to edit the config every time we add new queues to a server.

**Comment by danielnelson** [comment]
Wildcard support should be fixed by #4189, it would be great if everyone could try it out using the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds).
