### ISSUE TITLE
"Enforced encryption by server" property collected in SQLServerProperties

### ISSUE THREAD

**Issue by MartinHBA** [influxdata/telegraf#12933]
### Use Case

Hi, would appreciate if plugin sqlserver could collect property of server "enforced encryption"
that would be awesome and can help us to reduce collecting scripts and have evidence for auditors that throughout time servers are and always have been with enforced TLS encryption in transit 
sqlserver - database_type = "SQLServer" - SQLServerProperties

### Expected behavior

there is new true/false value under SQLServerProperties, could be called enforcedEncryption (true/false)

### Actual behavior

can't find such feature in current sqlserver plugin

**Comment by powersj** [comment]
@Trovalo similar request, any objection?

**Comment by Trovalo** [comment]
Fine to me

**Comment by MartinHBA** [comment]
@Trovalo , I forked this, but not sure which go file should be updated for actual script. There are these files with TSQL Scripts:
`sqlqueriesV1.go
sqlqueriesV2.go
sqlserverqueries.go`

**Comment by Trovalo** [comment]
The currently "active" script for on-prem SQL Server is [plugins/inputs/sqlserver/sqlserverqueries.go](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserverqueries.go).
