### ISSUE TITLE
UPSD: status flags should be a fields values, not tags

### ISSUE THREAD

**Issue by gertvdijk** [influxdata/telegraf#12938]
### Relevant telegraf.conf

```toml
[[inputs.upsd]]
  server = "127.0.0.1"
```

### Logs from Telegraf

```text
# 1/2, online: tag status_OL=true, status_OB missing
$ telegraf --config /etc/telegraf/telegraf.conf.upstest --debug --once
2023-03-25T16:52:04Z I! Loading config file: /etc/telegraf/telegraf.conf.upstest
2023-03-25T16:52:04Z I! Starting Telegraf 1.26.0
2023-03-25T16:52:04Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-03-25T16:52:04Z I! Loaded inputs: upsd
2023-03-25T16:52:04Z I! Loaded aggregators: 
2023-03-25T16:52:04Z I! Loaded processors: 
2023-03-25T16:52:04Z I! Loaded secretstores: 
2023-03-25T16:52:04Z I! Loaded outputs: file
2023-03-25T16:52:04Z I! Tags enabled: host=myhostname
2023-03-25T16:52:04Z D! [agent] Initializing plugins
2023-03-25T16:52:04Z D! [agent] Connecting outputs
2023-03-25T16:52:04Z D! [agent] Attempting connection to [outputs.file]
2023-03-25T16:52:04Z D! [agent] Successfully connected to outputs.file
2023-03-25T16:52:04Z D! [agent] Starting service inputs
2023-03-25T16:52:04Z D! [agent] Stopping service inputs
2023-03-25T16:52:04Z D! [agent] Input channel closed
2023-03-25T16:52:04Z I! [agent] Hang on, flushing any cached metrics before shutdown
{"fields":{"battery_charge_percent":95,"firmware":"01.18.0022","input_frequency":50,"input_transfer_high":285,"input_transfer_low":165,"input_voltage":237,"load_percent":17,"output_voltage":238,"status_flags":8,"time_left_ns":1647000000000,"ups_delay_shutdown":20,"ups_delay_start":30,"ups_status":"OL"},"name":"upsd","tags":{"host":"myhostname","model":"Ellipse PRO 650","serial":"<omitted>","status_OL":"true","ups_name":"myups"},"timestamp":1679763124}
2023-03-25T16:52:04Z D! [outputs.file] Wrote batch of 1 metrics in 65.212µs
2023-03-25T16:52:04Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-03-25T16:52:04Z I! [agent] Stopping running outputs
2023-03-25T16:52:04Z D! [agent] Stopped Successfully

# 2/2, on battery: tag status_OB=true, status_OL missing
$ telegraf --config /etc/telegraf/telegraf.conf.upstest --debug --once
2023-03-25T16:56:03Z I! Loading config file: /etc/telegraf/telegraf.conf.upstest
2023-03-25T16:56:03Z I! Starting Telegraf 1.26.0
2023-03-25T16:56:03Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-03-25T16:56:03Z I! Loaded inputs: upsd
2023-03-25T16:56:03Z I! Loaded aggregators: 
2023-03-25T16:56:03Z I! Loaded processors: 
2023-03-25T16:56:03Z I! Loaded secretstores: 
2023-03-25T16:56:03Z I! Loaded outputs: file
2023-03-25T16:56:03Z I! Tags enabled: host=homeserver
2023-03-25T16:56:03Z D! [agent] Initializing plugins
2023-03-25T16:56:03Z D! [agent] Connecting outputs
2023-03-25T16:56:03Z D! [agent] Attempting connection to [outputs.file]
2023-03-25T16:56:03Z D! [agent] Successfully connected to outputs.file
2023-03-25T16:56:03Z D! [agent] Starting service inputs
2023-03-25T16:56:03Z D! [agent] Stopping service inputs
2023-03-25T16:56:03Z D! [agent] Input channel closed
2023-03-25T16:56:03Z I! [agent] Hang on, flushing any cached metrics before shutdown
{"fields":{"battery_charge_percent":94,"firmware":"01.18.0022","input_frequency":50,"input_transfer_high":285,"input_transfer_low":165,"input_voltage":233,"load_percent":17,"output_voltage":237,"status_flags":16,"time_left_ns":1927000000000,"ups_delay_shutdown":20,"ups_delay_start":30,"ups_status":"OB"},"name":"upsd","tags":{"host":"myhostname","model":"Ellipse PRO 650","serial":"<omitted>","status_OB":"true","ups_name":"myups"},"timestamp":1679763364}
2023-03-25T16:56:03Z D! [outputs.file] Wrote batch of 1 metrics in 112.766µs
2023-03-25T16:56:03Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-03-25T16:56:03Z I! [agent] Stopping running outputs
2023-03-25T16:56:03Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.26.0, on Debian 11 with nut-client/-server 2.7.4-13

### Steps to reproduce

1. Feed stats in Influx with UPS online
2. Pull the power from your UPS, keep feeding stats to Influx while UPS on battery for at least one data point. Then restore line power.
3. Observe two tables are returned in time range with both statuses.

### Expected behavior

I believe _tag_ names should be stable when something like a status changes. I would have expected to *not* have `status_OL` and `status_OB` tags here, because we already have a `ups_status`: `"OB"`/`"OL"` _field_.

To be explicit, here in JSON-output as example:

when on line power, no `status_OL` tag:
```json
{
    "fields": {
         [...]
        "ups_status": "OL"
    },
    "name": "upsd",
    "tags": {
        "host": "myhostname",
        "model": "Ellipse PRO 650",
        "serial": "<omitted>",
        "ups_name": "myups"
    },
    "timestamp": 1679763364
}
```

when on battery, no `status_OB` tag:
```json
{
    "fields": {
         [...]
        "ups_status": "OB"
    },
    "name": "upsd",
    "tags": {
        "host": "myhostname",
        "model": "Ellipse PRO 650",
        "serial": "<omitted>",
        "ups_name": "myups"
    },
    "timestamp": 1679763364
}
```

### Actual behavior

when on line power, `status_OL` tag appears, `status_OB` disappears:
```json
{
    "fields": {
         [...]
        "ups_status": "OL"
    },
    "name": "upsd",
    "tags": {
        "host": "myhostname",
        "model": "Ellipse PRO 650",
        "serial": "<omitted>",
        "status_OL": "true",
        "ups_name": "myups"
    },
    "timestamp": 1679763364
}
```

when on battery, `status_OB` tag appears, `status_OL` disappears:
```json
{
    "fields": {
         [...]
        "ups_status": "OB"
    },
    "name": "upsd",
    "tags": {
        "host": "myhostname",
        "model": "Ellipse PRO 650",
        "serial": "<omitted>",
        "status_OB": "true",
        "ups_name": "myups"
    },
    "timestamp": 1679763364
}
```

What's the actual problem? Well, I suddenly get _multiple tables_ (and thus multiple UPSs) when the status changes. Screenshot as shown in InfluxDB notebook:

![Screenshot_20230325_174740-1](https://user-images.githubusercontent.com/1550527/227731421-83f3faf2-d5d3-44f2-83e9-85b569487d20.png)

### Additional info

The current work-around is to apply a `tagexclude = ["status_*"]` configuration to omit the wrong data, which should not be needed.

**Comment by powersj** [comment]
> Observe two tables are returned in time range with both statuses.

The tables you are referring to are Flux query tables. I do not know Flux well enough to understand if there is a way to ignore these tag values and instead return a single table. Something like [`group`](https://docs.influxdata.com/influxdb/v2.0/query-data/flux/group-data/).

However, the tag name is not changing, but instead [a different tag that reacts to the reported status variables](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/upsd/upsd.go#L133-L180). We wouldn't rename tag names between versions as that would then affect all current users.

Not sure there is anything for telegraf to do on this one.

**Comment by gertvdijk** [comment]
Thanks for your reply! I am not sure you understand the issue here. IMO one should not add/remove tags based on a value of a status. It would indicate it's a different device, similar as you said it would break it for other users if we rename tags: that's what happening here on every status change!

To be clear, what I'm asking for is this (snippet):

```
# NEW:
fields["status_CAL"] = "false"
fields["status_TRIM"] = "false"
fields["status_BOOST"] = "false"
fields["status_OL"] = "false"
fields["status_OB"] = "false"
fields["status_OVER"] = "false"
fields["status_LB"] = "false"
fields["status_RB"] = "false"

# Similar as before:
if choice.Contains("CAL", statuses) {
    status |= 1 << 0
    fields["status_CAL"] = "true"
}
if choice.Contains("TRIM", statuses) {
    status |= 1 << 1
    fields["status_TRIM"] = "true"
}
if choice.Contains("BOOST", statuses) {
    status |= 1 << 2
    fields["status_BOOST"] = "true"
}
if choice.Contains("OL", statuses) {
    status |= 1 << 3
    fields["status_OL"] = "true"
}
if choice.Contains("OB", statuses) {
    status |= 1 << 4
    fields["status_OB"] = "true"
}
if choice.Contains("OVER", statuses) {
    status |= 1 << 5
    fields["status_OVER"] = "true"
}
if choice.Contains("LB", statuses) {
    status |= 1 << 6
    fields["status_LB"] = "true"
}
if choice.Contains("RB", statuses) {
    status |= 1 << 7
    fields["status_RB"] = "true"
}
return status
```

- tags to fields (it's a measurement, not a fact)
- all fields always present, the measurement value in the value

**Comment by powersj** [comment]
> To be clear, what I'm asking for is this (snippet):

ah yes I missed you changing the tag to a field. That is a hard pass due to the affect that would have on existing users. If you wanted to do that, you can use the [converter processor plugin](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter)

> It would indicate it's a different device,

Help me understand why you are saying the addition or removal of a tag indicates a different device?

**Comment by gertvdijk** [comment]
> Help me understand why you are saying the addition or removal of a tag indicates a different device?

That's how series work in Influx, how you identify an entity, no? IIUC the set of tags with their values define the key (instance ID) of the series of field values (tags are indexed). (See also below at the bottom, screenshot in Grafana.)

It would also be wrong if the disks input plugin would emit the disk usage in tag values instead of field values. Or if a temperature sensor would output the temperature as tag value instead of a field value. Right?

If a measurement is fed to Telegraf/Influx with different tags every time, the key index would be unstable and have a high cardinality. This then requires inefficient queries using 'group by' or manual processors to fix this and so on that, as you indicate (and the storage layer can't optimize as well). Configuring alerts based on a trend with debugging in a graph (as in Grafana 9), would be a pain too if the tags aren't stable.

I feel like I'm new to Telegraf and Influx, but this seems a basic concept to me that this input plugin (and apcupsd as well) doesn't follow.

See also how other input plugins have status flags as **field value**:
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/bond/bond.go#L131
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/ceph/ceph.go#L403-L410
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/dpdk/README.md?plain=1#L276
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/ecs/README.md?plain=1#L97-L99
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/elasticsearch/README.md?plain=1#L111-L146
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/haproxy/README.md?plain=1#L107-L113

Also found one example that counter my view, so in favour of yours/upsd:
- https://github.com/influxdata/telegraf/blob/5e7c5c84e911fd2c06d3723d47e458bde26aba9c/plugins/inputs/docker/README.md?plain=1#L240 (haven't looked at this, but looks like same mistake to me....)

(stopped at h)

> due to the affect that would have on existing users

> We wouldn't rename tag names between versions as that would then affect all current users.

With that argument we could never change anything in software when a mistake was made in its design. 😕 
My point is that this shouldn't be tags in the first place.

> The tables you are referring to are Flux query tables. 

Perhaps good to add that that these will show as different series in Grafana as for example shown here when a status tag suddenly appears (showing two UPSs, but there's one):

![Screenshot_20230328_014243](https://user-images.githubusercontent.com/1550527/228091276-512c2070-6525-4962-a435-377cbaecd4ab.png)

Similar in Alerts, a different series for each status, each being reported on (unless you manually fix this like I did...).

![Screenshot_20230328_015333](https://user-images.githubusercontent.com/1550527/228092444-07df7952-a6de-4ac7-9128-7ea2dffa5cf6.png)

HTH, and I'm happy to be proven wrong also. 😃

**Comment by powersj** [comment]
Hi,

> But OTOH, I just realized I reply to a/the maintainer of Telegraf, so I could be completely wrong here of course! no_mouth see_no_evil

I can be wrong too :) With over 300 plugins and many different services that we connect to I cannot be an expert in all of them. It is why I was asking to be sure I am clear about what your concern is and that I have no over-looked something.

> It would also be wrong if the disks input plugin would emit the disk usage in tag values instead of field values. Or if a temperature sensor would output the temperature as tag value instead of a field value. Right?

> If a measurement is fed to Telegraf/Influx with different tags every time, the key index would be unstable and have a high cardinality.

If you look at how status is determined it is a value where multiple of those status values can exist at any given time. Using a single status value is not possible with USPD without using a CSV string and this makes filtering and grouping more difficult than it needs to be.

Should there be default values for all of those settings? Maybe, but not all UPS devices may ever report all those options. Given these are booleans then the impact is small, but it was originally decided not to include them. If anything were to change, setting the default values with every metric might be it.

You are correct that it is best to avoid continuous values, like random floats or ints. Constantly changing tags do result in high cardinality and that can be an issue. However,  the eight status fields you are referencing in this issue are booleans which can only ever have 2 values at most (although only 1 right now); as such high cardinality is not a concern.

Tags in InfluxDB are generally things you want to filter and group on. Filtering on if the power status on or off is something a user would probably want to do. Or for example, create an alert on a certain status. Hence, these are tags. Again, I believe some sort of join or group could help with your queries.

I am not sure I would say the tag is changing every time. For example:

> metric,serial=abcdefg,status=true value=40
> metric,serial=abcdefg value=41
> metric,serial=abcdefg,status=true value=41

There are two series in the above example. The first and third metrics are part of the same series. Now if status was a float that constantly changed, like 40.1, 40.2, 40.3 I would agree that we have a problem and high-cardinality will be an issue.

> With that argument we could never change anything in software when a mistake was made in its design. confused

Telegraf aims to not break backward compatibility with users' configs as well as tags and fields. If we make a change to tags and fields it is reserved for a serious issue, usually in the case of run-away cardinality, which I hope I have explained above this is not the case here. We also provide the user with the converter processor I mentioned as well if a user wanted to ever override the selection of a tag or field.

Hopefully that helps explain why I am pushing back on switching the values from a tag to a field in the code and instead suggesting you either a) look at a join/group in your query or b) use the converter processor instead.

Thanks!
