### ISSUE TITLE
Support for TLS Auth using a passphrase protected private key

### ISSUE THREAD

**Issue by allej** [influxdata/telegraf#12932]
### Use Case

We're using telegraf InfluxDB v1.x output plugin to write graphite metrics to our secured corporate InfluxDB instance. The setup requires TLS client certificate authentication. Our private-key files are passphrase protected rsa keys in pem format.

Relevant `telegraf.conf`:
```
[[outputs.influxdb]]
  urls = ["https://<influx-server-url>"]
  tls_ca = "/etc/telegraf/certs/ca-chain.pem"
  tls_cert = "/etc/telegraf/certs/user_cert.pem"
  tls_key = "/etc/telegraf/certs/user_key.pem"
  #tls_key = "/etc/telegraf/certs/user_key_nopw.pem"
  tls_key_pwd = "psst"
  tls_key_password = "psst"
  tls_renegotiation_method = "once"
  insecure_skip_verify = true
```

### Expected behavior

Startup properly and connect to InfluxDB using TLS client certificate auth.

### Actual behavior

Starting telegraf fails with this error message:
```
docker run -it --rm --name=telegraf -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro -v $PWD/certs/:/etc/telegraf/certs/:ro -p 127.0.0.1:2003:2003 telegraf
2023-03-24T13:32:22Z I! Loading config file: /etc/telegraf/telegraf.conf
2023-03-24T13:32:22Z E! error loading config file /etc/telegraf/telegraf.conf: error parsing influxdb array, could not load keypair /etc/telegraf/certs/user_cert.pem:/etc/telegraf/certs/user_key.pem: tls: failed to parse private key
```
Using basically the same `telegraf.conf` using a private key _without_ passphrase works properly.

### Additional info

There seem to be some configuration code in place for this to work (see [plugins/common/tls/config.go](https://github.com/influxdata/telegraf/blob/master/plugins/common/tls/config.go#L20)), but the parameter `tls_key_pwd` (or `tls_key_password`) is never used in the InfluxDB v1.x output plugin and does not have any effect.
There was a similar requirement discussed in [PR #10020](https://github.com/influxdata/telegraf/pull/10020/)

**Comment by rajiv-k** [comment]
@powersj I would like to give this a try.

**Comment by rajiv-k** [comment]
@powersj I would like to give this a try.

**Comment by powersj** [comment]
PRs are always welcome
