### ISSUE TITLE
Linter: gosec, Rule: G403 - Ensure minimum RSA key length of 2048 bits. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12948]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G403 - Ensure minimum RSA key length of 2048 bits](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE CATEGORY: Cryptographic Issues](https://cwe.mitre.org/data/definitions/310.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule no findings were found in current code.

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1

**Comment by srebhan** [comment]
Even though I cannot imagine where this applies (because I think we don't generate RSA keys ourselves) I think it might become aware of those spots for future PRs.
