### ISSUE TITLE
Linter: gosec, Rule: G402 - Look for bad TLS connection settings. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12947]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G402 - Look for bad TLS connection settings](https://cwe.mitre.org/data/definitions/295.html)

Rule is mapped to [CWE-295: Improper Certificate Validation](https://cwe.mitre.org/data/definitions/200.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule following findings were found in current code:
```
plugins/common/tls/config.go:79:12                                                 gosec  G402: TLS MinVersion too low.
plugins/common/tls/config.go:98:23                                                 gosec  G402: TLS InsecureSkipVerify may be true.
plugins/common/tls/config.go:144:16                                                gosec  G402: TLS MinVersion too low.
plugins/common/tls/config_test.go:562:15                                           gosec  G402: TLS MinVersion too low.
plugins/inputs/aerospike/aerospike.go:69:17                                        gosec  G402: TLS MinVersion too low.
plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go:113:22  gosec  G402: TLS MinVersion too low.
plugins/inputs/http_listener_v2/http_listener_v2_test.go:157:22                    gosec  G402: TLS MinVersion too low.
plugins/inputs/influxdb_listener/influxdb_listener_test.go:119:22                  gosec  G402: TLS MinVersion too low.
plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go:117:22            gosec  G402: TLS MinVersion too low.
plugins/inputs/mongodb/mongodb.go:68:24                                            gosec  G402: TLS InsecureSkipVerify may be true.
plugins/inputs/opensearch_query/opensearch_query.go:127:53                         gosec  G402: TLS InsecureSkipVerify set true.
plugins/inputs/prometheus/kubernetes.go:227:92                                     gosec  G402: TLS InsecureSkipVerify set true.
plugins/inputs/vsphere/client.go:136:13                                            gosec  G402: TLS MinVersion too low.
plugins/inputs/x509_cert/x509_cert.go:87:13                                        gosec  G402: TLS MinVersion too low.
plugins/inputs/x509_cert/x509_cert_test.go:73:23                                   gosec  G402: TLS InsecureSkipVerify set true.
plugins/outputs/opentelemetry/opentelemetry.go:92:73                               gosec  G402: TLS MinVersion too low.
```

### Additional info

For this rule no additional configuration can be provided.

**Comment by powersj** [comment]
+1

**Comment by srebhan** [comment]
I'm not sure on this one. +1 if it is though as becoming aware of the locations and to go through the findings and silence or fix them. Otherwise, the user _might_ request an insecure setting due to the remote endpoint or due to requirements of the client used.

**Comment by zak-pawel** [comment]
I'm also not sure.
I quickly reviewed all findings and it seems that all of them should be silenced. And probably all new issues will be silenced too.

Or we can set `MinVersion` to `VersionTLS13` everywhere explicitly. And don't allow to set `InsecureSkipVerify` to `true`.
But I don't know how many plugins will stop working in real-life conditions after that...

@srebhan @powersj Your thoughts on this?

**Comment by powersj** [comment]
> And don't allow to set InsecureSkipVerify to true.

heh yeah that isn't an option for many plugins and would break plenty of folks

so I guess my +1 becomes -1 if we would just ignore everything.

**Comment by zak-pawel** [comment]
@srebhan What do you think?
+1?
-1?
