### ISSUE TITLE
how to change the key of measurement name : "name" in json output format? I didn't find in any doc.

### ISSUE THREAD

**Issue by Pickles-wave** [influxdata/telegraf#12972]
### Please direct all support questsions to slack or the forums. Thank you.

This is the current output:
`{
   "**name**":"security_rule_hits",
   "fields":{
                "in_bytes":0,
                "out_bytes":0
                },
   "tags":{
                 "host":"localhost.localdomain"
              },
"timestamp":1679988594
}`

I want to change it to this:
`{
   "**other_name**":"security_rule_hits",
   "fields":{
                "in_bytes":0,
                "out_bytes":0
                },
   "tags":{
                 "host":"localhost.localdomain"
              },
"timestamp":1679988594
}`

Thank you very much if you can help!

**Comment by Pickles-wave** [comment]
I tried this plugin,It can only change the value of measurement,but i want to change the key :"name";

**Comment by Pickles-wave** [comment]
And this usage:
 [[processors.rename.replace]]
    field = "lower"
    dest = "min"
It's just can change the key of fields or tags.

**Comment by powersj** [comment]
ah... you are trying to change the "measurement name" key "name" to something else with the [json serializer](https://github.com/influxdata/telegraf/blob/master/plugins/serializers/json/json.go#L136). I don't believe this is possible.

**Comment by Pickles-wave** [comment]
emmm...I suspected it was written in code,I didn't expect it's true.
Anyway,Thank you so much for your help!
