### ISSUE TITLE
Interpreting MQTT binary streams that include null bytes

### ISSUE THREAD

**Issue by moracca** [influxdata/telegraf#12983]
Hello, I've run into a bit of an issue while setting up telegraf to consume MQTT messages from a wireless controller.

The controller in question has defined a binary data structure for this particular message that includes various fields of specific data types/lengths:

![image](https://user-images.githubusercontent.com/7213746/228640491-7729b8b8-1128-4ff9-a075-8346ab164a82.png)

I've roughly translated that into the following fields config in my telegraf config:
```
  [[inputs.mqtt_consumer.binary]]
    metric_name = "mgmt_response_ctrl"
    entries = [
      { name = "message_type", type = "uint8", assignment = "field" },
      { name = "message_sub_type", type = "uint8", assignment = "field" },
      { name = "length", type = "uint16", assignment = "field" },
      { name = "controller_name", type = "string", bits = 512 },
      { name = "api_version", type = "string", bits = 128 },
      { name = "sw_version", type = "string", bits = 128 }
    ]
    [inputs.mqtt_consumer.binary.filter]
      selection = [
        { offset = 0, bits = 8, match = "0x02" },
        { offset = 8, bits = 8, match = "0x01" }
      ]
```
as this message is indicated by the first bytes being 02 01, matching the filter selection.

The issue comes when I parse the 3 string values (controller_name, api_version, sw_version).  These values are 64 byte, 16 byte, and 16 byte (respectively) char fields (hence the 512/128/128 bits values in my field entries).  Most times, however, the content of these fields doesn't actually consume the full 64 bytes.  Instead, it will have a little bit of data then be zero-padded until the end of the fixed field boundary.

As an example, here is a payload:
```
0201 0060 4c44 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 332e 3000 0000 0000 0000 0000 0000 0000
362e 312e 312e 3000 0000 0000 0000 0000 
```
which should in theory translate to the following fields
```
message type = 2 (02)
message_subtype = 1 (01)
length = 96 (0060)
controller_name = LD (4c4400...)
api_verision = 3.0 (332e 3000...)
software_version = 6.1.1.0 (362e 312e 312e 3000...) 
```

When this is parsed however, and then fed to my postgresql output, I get the following error:
```
2023-03-28T06:55:02Z E! [outputs.postgresql] PG CopyFrom - map[columnNames:[time tag_id message_type message_sub_type length controller_name api_version sw_version] err:ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021) pid:67065 tableName:[stats mgmt_response_ctrl] time:3.727603ms]
2023-03-28T06:55:02Z E! [outputs.postgresql] write error (permanent, dropping sub-batch): ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021)
```

I also tried setting a specific bits value (512) in conjunction with a terminator = "null", but it doesn't allow both, and I'm not sure this is the best place to handle it anyway.  

I als tried using a processor to rtrim the value before it gets to postgres in the hopes it would sanitize it, but that didn't work for me either, although its likely I've just done something wrong here:
```
[[processors.converter]]
  [processors.converter.fields]
    string = ["controller_name"]

[[processors.strings]]
  [[processors.strings.trim_right]]
    field = "controller_name"
    cutset = "0x00"
```

Any suggestions on how to work around this are appreciated!

**Comment by moracca** [comment]
I feel like there must be an easy workaround here, because if I output to stdout instead of postgresql, the values look fine:
```
mgmt_response_ctrl,host=Mac-Pro.local,topic=3.0/LOC/dev139/LD/MGR message_sub_type=1i,length=24576i,message_type=2i,api_version="3.0",sw_version="6.1.1.0",controller_name="LD" 1680191807054693000
```

**Comment by moracca** [comment]
In my case, I found that I was able to work around this using the regex processor and matching `\u0000` in the strings:

```
[[processors.regex]]

  [[processors.regex.fields]]
    key = "controller_name"
    pattern = "\u0000"
    replacement = ""

  [[processors.regex.fields]]
    key = "api_version"
    pattern = "\u0000"
    replacement = ""

  [[processors.regex.fields]]
    key = "sw_version"
    pattern = "\u0000"
    replacement = ""
```

**Comment by powersj** [comment]
> ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021)

The null byte is [not allowed](https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough/) text values in postgres.

I do not see this as a bug, rather clean your data using a processor, which the reporter seems to have done.

**Comment by Hipska** [comment]
Other outputs know and take care of things that are not possible at the backend. Like for example some don't support string fields, they then give the option to add as tag or ignore them.. A similar thing can be done for the postgres output..

**Comment by powersj** [comment]
While we could, that leads to a never ending list of things that our outputs do. For example, the influxdb output does not go through and escape new lines, which are not allowed in line protocol. There already exists a method for resolving both of these via processors, adding yet another option is redundant.
