### ISSUE TITLE
Add ingest statistics to Elasticsearch Input Plugins

### ISSUE THREAD

**Issue by wp-perc** [influxdata/telegraf#13004]
### Use Case

I'd like to create dashboard about Ingest statistics from Elasticsearch API.
It is possible to add support for ingest node stats?

### Expected behavior

Add ingest to `node_stats`, ten all stats from `/_nodes/stats/ingest` and '/_nodes/<node_id>/stats/ingest` should be read by Telegraf and sent to the output plugins.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html for more reference.

### Actual behavior

`ingest` endpoint is simply ignored.

**Comment by powersj** [comment]
Hi,

Can you provide example data from those endpoints such that we could a) take a look at the format and b) develop against it?

Thanks

**Comment by hackery** [comment]
Examples can be seen by creating an [ingest pipeline](https://www.elastic.co/docs/manage-data/ingest/transform-enrich/ingest-pipelines) and then visiting `/_nodes/stats`.

```JSON
{
  "_nodes": {
    "total": 13,
    "successful": 13,
    "failed": 0
  },
  "cluster_name": "...",
  "nodes": {
    "...": {
      "timestamp": 1759154494695,
      "name": "...",
      "ingest": {
        "total": {
          "count": 14967691824,
          "time_in_millis": 7117034,
          "current": 0,
          "failed": 0
        },
        "pipelines": {
          "hackery_pipeline_name": {
            "count": 14962110805,
            "time_in_millis": 4461080,
            "current": 0,
            "failed": 0,
            "processors": [
              {
                "compound:CompoundProcessor-null": {
                  "type": "conditional",
                  "stats": {
                    "count": 19046557,
                    "time_in_millis": 4335,
                    "current": 0,
                    "failed": 0
                  }
                }
              },
```

Looking at how `gatherNodeStats` goes through a list of interfaces calling `FlattenJSON` on these sub-structures, perhaps it would be simple to do so for `total` and the `pipelines` values but I'm not sure how the flattener would behave for the nested `processors` values.

> Note that in be above, `compound:CompoundProcessor-null` should be a unique value for the processor stage, but this pipeline did not set `tag` values for the stages. Where the user has not done this, multiple stages will be indistinguishable.
