### ISSUE TITLE
Does Telegraf support automatic creation of influx buckets that do not exist?

### ISSUE THREAD

**Issue by ProbieGw** [influxdata/telegraf#13007]
### Use Case

I have multiple servers, and I want to collect metrics through telegraf, each server is a bucket, but I don't want to create it manually, because it's too much trouble

### Expected behavior

![image](https://user-images.githubusercontent.com/57038615/229285944-448a5a5c-581c-42e5-aa58-27bcdf35b6a0.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/57038615/229285972-9b6246cd-5c52-4493-bcf3-d7c88326c583.png)

**Comment by powersj** [comment]
> I have multiple servers, and I want to collect metrics through telegraf, each server is a bucket, but I don't want to create it manually, because it's too much trouble

If you use InfluxDB v1 then the v1 output plugin will attempt to create the bucket. However, with InfluxDB v2 output plugin this is not possible.

> I don't want to create it manually, because it's too much trouble

Give the [influx cli](https://docs.influxdata.com/influxdb/v2.1/organizations/buckets/create-bucket/#create-a-bucket-using-the-influx-cli) or client libraries a try to quickly loop through and make the buckets.
