### ISSUE TITLE
SecretStore `set` keyring and collection are swapped between execution and documentation

### ISSUE THREAD

**Issue by cruscio** [influxdata/telegraf#13001]
### Relevant telegraf.conf

```toml
[[secretstores.os]]
  id = "generic"
  collection = "collection"
  keyring = "keyring"
```

### Logs from Telegraf

```text
enter secret:
2023/03/31 16:16:44 I! Loading config file: C:\telegraf\telegraf.conf
```

### System info

1.26.0

### Steps to reproduce

1. Create a telegraf config with the above `secretstores` section
2. Run `.\telegraf.exe --debug --config .\telegraf.conf secrets set generic key_name`
3. Enter in a value for the secret when prompted

### Expected behavior

Per the documentation, the order is "_special_" and should be: `<keyring>:<collection>:<key>`

https://github.com/influxdata/telegraf/tree/master/plugins/secretstores/os#windows

> On Windows you can use the Credential Manager Control panel or [Telegraf](https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/README.md) to manage your secrets. Please use generic credentials and respect the special &lt;keyring&gt;:&lt;collection&gt;:&lt;key&gt; format of the secret key. The secret value needs to be stored in the Password field.

### Actual behavior

set command does not "_respect the special &lt;keyring&gt;:&lt;collection&gt;:&lt;key&gt; format of the secret key_", and it appears in credential manager as `<collection>:<keyring>:<key>`
 
![image](https://user-images.githubusercontent.com/30699280/229177512-cfd60c5e-f480-4a58-aa9d-461cc20f863e.png)

### Additional info

* I didn't check if the credential loaded differently or if that's backward too.
* Or maybe it's just the documentation that's backward?
* Not really interested in pursuing this further; just wanted to let you know there was an inconsistency in behavior and documentation.

**Comment by powersj** [comment]
It does look like it is reversed. What I think caused this is if you omit collection it will show up as the word "keyring" in the credential manager, which probably will cause even more confusion :)

**Comment by srebhan** [comment]
@cruscio can you please contribute a PR?

**Comment by powersj** [comment]
@cruscio and @knollet can both of you take a look at #13399 and let me know if that aligns with your understanding?

**Comment by cruscio** [comment]
Looks good @powersj , thanks

**Comment by powersj** [comment]
Thanks for confirming!

**Comment by knollet** [comment]
Yes, very nice, thanks.
