### ISSUE TITLE
io stats per process

### ISSUE THREAD

**Issue by whetherharder** [influxdata/telegraf#1300]
## Feature Request

It would be quite useful to have io statistics (iops, reads/per-sec,writes/sec etc), for paticular process. It would be perfect, to have also network stats per process. 
If there is already a way to get such statistics, using existing set of plugins, let me know please

**Comment by sparrc** [comment]
there's the procstat plugin: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat

**Comment by whetherharder** [comment]
Sorry for bothering you with io stats they are already present as it is writen in docs!. My problem is that not all metrics were pushed to influxdb

So 
select * from "procstat" limit 1
returns
cpu_time_guest	cpu_time_guest_nice	cpu_time_idle	cpu_time_iowait	cpu_time_irq	cpu_time_nice	cpu_time_soft_irq	cpu_time_steal	cpu_time_stolen	cpu_time_system	cpu_time_user	cpu_usage	host	involuntary_context_switches	memory_rss	memory_swap	memory_vms	num_threads	pattern	pid	process_name	service_name	voluntary_context_switches

while telegraf -test -config input.procstat.custom.zookeeper.conf returns
[root@SRV2-VTG-VM47 telegraf.d]# telegraf -test -config input.procstat.custom.zookeeper.conf
* Plugin: procstat, Collection 1
> procstat,host=SRV2-VTG-VM47,pattern=zookeeper,pid=16022,process_name=telegraf,service_name=zookeeper cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_stolen=0,cpu_time_system=0.01,cpu_time_user=0.02,involuntary_context_switches=1i,memory_rss=15986688i,memory_swap=0i,memory_vms=511963136i,**num_fds=5i**,num_threads=14i,**read_bytes=0i,read_count=906i**,voluntary_context_switches=53i,**write_bytes=3i,write_count=3i** 1464736322487619429

My configuration is:
Telegraf - version 0.13.1
InfluxDb  - version 0.9.3

May be InfluxDb is too old

**Comment by whetherharder** [comment]
Looks like a bug or some misconfiguration
I tried to reproduce the same scenario on influxdb 13.0 and the result was the same -- a part of fields are not pushed to influxdb

I have a guess, that the reason is in some kind of configured or hardcoded limit of fields to transmit. The set fields that is pushed is always identical

**Comment by sparrc** [comment]
Only possiblity I can think of would be that it's a permissions issue, could you try running `sudo -u telegraf telegraf -test -config input.procstat.custom.zookeeper.conf` and see if the output is different?

**Comment by whetherharder** [comment]
I am running telegraf under root as as a service
31.05.2016 18:30 пользователь "Cameron Sparr" <notifications@github.com>
написал:

**Comment by whetherharder** [comment]
But i will check this point. Thanks
01.06.2016 16:51 пользователь "Cameron Sparr" <notifications@github.com>
написал:

**Comment by sparrc** [comment]
Unless you're rolling your own init.sh or telegraf.service scripts I think it will run under the telegraf user anyways

**Comment by sparrc** [comment]
@whetherharder any updates

**Comment by Finistere** [comment]
I just tried running `sudo -u telegraf telegraf -test -config custom_procstat.conf` and got:

* Plugin: procstat, Collection 2
> procstat,host=hadoop-node-1,pattern=bash,pid=2129,process_name=bash cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_stolen=0,cpu_time_system=0.06,cpu_time_user=0.01,involuntary_context_switches=5i,memory_rss=2183168i,memory_swap=0i,memory_vms=118153216i,num_threads=1i,voluntary_context_switches=441i 1468763178088860035

I don't see any I/O stat in it.

Configuration:
Telegraf 0.13.1
CentOS 7.2

Is there something I might have missed ?

**Comment by sparrc** [comment]
@Finistere I believe the issue would be that your telegraf user doesn't have permission to gather these stats. What happens when you run as root?

**Comment by Finistere** [comment]
@sparrc Indeed, with root it works fine. The records are also correctly stored in InfluxDB (version 0.13.0). I will include telegraf user in the group launching my processes.
Thanks for the help!

**Comment by bennco1** [comment]
Hello - can anyone advise how to change the telegraf process from running as telegraf to root?

**Comment by sparrc** [comment]
closing as it appears to be a permissions issue.

If there is a specific workaround that should be pointed out, please submit a PR to change the plugin README, thanks

**Comment by Zeka13** [comment]
I don't think it works nowadays ..
