### ISSUE TITLE
Add capacity, used and free space of ZFS pool on Linux

### ISSUE THREAD

**Issue by PierreF** [influxdata/telegraf#13014]
### Use Case

I want to graph the percent of my ZFS disk space utilization (close to `df` Use% on classical filesystem).

Using value for standard `df` (or disk input) result in unexpected behavior, because the utilization percent will grow on ALL filesystems when data is written to a single one. So on a graph, you could see an increase in utilization of an filesystem even if nothing changed for this filesystem.

Actually with ZFS, only the ZFS pool capacity don't have this issue (that probably why `zfs list` don't have a capacity utilization in %).

### Expected behavior

Have the same zfs_pool metrics that FreeBSD had:
zfs_pool
* allocated (integer, bytes)
* capacity (integer, bytes)   <--- BTW this isn't bytes, but a %. It's the value I want
* dedupratio (float, ratio)
* free (integer, bytes)
* size (integer, bytes)

### Actual behavior

Those metrics aren't available on Linux, only on FreeBSD

### Additional info

The metrics I want are available on FreeBSD, gathered using `zpool` command output.

This command seems to works exactly the same on Linux (at least Ubuntu 22.04) and works from user. Could we use the same gather that is used on FreeBSD ? Probably in addition to the one used with Linux which gather more metrics.

This should also bring the zpool health as tags like on FreeBSD (which should fix #10619).

The only issue I see with this approach is that tags for "zfs_pool" measurement which not be the same between Linux version and the FreeBSD version. And since on Linux (with ZFS >= 2.1.x) we have a per-dataset "zfs_pool" measurement, it will make merging both set of tags complicated.

I can help with a PR to also run `zpool list` (and `zfs list` ?) on Linux to gather those metrics like on FreeBSD, but we need to resolve under which name with which tags we should do that.

**Comment by powersj** [comment]
Hi,

This sounded like a familiar request and I went back and found two PRs: 

- #6724
- #2616

There were discussions about using the CLI commands, but it was generally not accepted due to changing formats, permissions, etc. It did sound like there was a `zpool_influxdb` command to get some data out in a stable manner.

Is that command available to you?

**Comment by PierreF** [comment]
Hi,

thanks for your quick answer. I've missed the existing issues when searching for existing report. I should be able to use zpool_influxdb which looks a good fit. If not (due to possible cross-compile issue), I should be able to make a Go wrapper around zpool command in similar way to zpool_influxdb with exec plugin.

Closing the issue since my request have a valid answer for my use-case.
