### ISSUE TITLE
How to register the URL for automatic updates? 

### ISSUE THREAD

**Issue by kostik-pozh** [influxdata/telegraf#13028]
### Please direct all support questsions to slack or the forums. Thank you.

Hi.
How to add the URL for automatic updates?

my config
[[inputs.ping]]
urls = ["192.168.88.1", "192.168.88.87"]

how to make a separate file in which there will be a list of hosts and when updating this file, the list is updated in the plugin.

for example

[[inputs.ping]]
urls = ["../etc/telegraf/icmp.yml"]

in file icmp.yml

- targets:
  - '185.195.152.117'
  labels:
    project: 'test2'
    env: 'ip2'
    
and when adding a new host to icmp.yml, the plugin config was updated automatically without
systemctl restart telegraf

Is there a solution?

**Comment by powersj** [comment]
answered on forum: https://community.influxdata.com/t/how-to-register-the-url-for-automatic-updates/29369/2
