### ISSUE TITLE
kafka output: add ability to choose partition

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#1304]
If I have more than one partitions for one Kafka topic, how to I choose which partitions to send data to?

It seems there's no such option in 
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/kafka/kafka.go.

Are you planning to add this feature?

**Comment by sparrc** [comment]
no plans but should be rather simple to implement, PRs appreciated :)

**Comment by jregovic** [comment]
To do this would require that the telegraf agent have _a priori_ knowledge of the number of topics and some has function has been provided to determine the partition from some data. I can't think of an efficient way to assign the partition given that some measurements may have a dynamic number of metrics based on tags.

Would computing something based off the tags used in topic and topic suffixes work? Ideally, you'd want to determine the partition at startup and not every time the agent emits data, yeah?

I have a need for this and I am trying to figure out the best way to do it.

**Comment by danielnelson** [comment]
I believe this has been implemented.  You can use the `routing_key` and `routing_tag` options to select a tag value, static value, or random value as the partition key.  Items with the same partition key will be written to the same partition.
