### ISSUE TITLE
socket_listener: ifname not set

### ISSUE THREAD

**Issue by ghost** [influxdata/telegraf#13045]
In here, `ifname` is redeclared inside the `if` block resulting in the outer `ifname` always being an empty string when its passed to `setupUDP`.

https://github.com/influxdata/telegraf/blob/35edd1863fb135570abe2d6a0c0241bbdc3c6ec8/plugins/inputs/socket_listener/socket_listener.go#L142-L148

Also there is no way to specify the interface from the config file unless you use the `%scope` as with IPv6 which is not really a convention for IPv4.

The documentation states that "If ifi is nil, ListenMulticastUDP uses the system-assigned multicast interface, although this is not recommended because the assignment depends on platforms and sometimes it might require routing configuration."

Perhaps a new configuration option of `ServiceInterface` is warranted.

**Comment by powersj** [comment]
Hi,

Can you try the artifacts attached to #13084? There will be some attached in 20-30mins once CI is done running.

Thanks

**Comment by mt-rcampo** [comment]
It works by specifying something like `service_address = "udp://239.192.10.21%eth0:10001"` This of course is not standard for IPv4. I also dont see any mention of using `%zone` in the sample config.

A few things to note, the interface specified must be UP and it must have an IP else Linux will use the system specified interface for multicast.
Not specifying '%zone':
![image](https://user-images.githubusercontent.com/104592970/231843410-1e7054b1-6326-4928-8556-516c537223f3.png)


Specifying `%eth0`:
![image](https://user-images.githubusercontent.com/104592970/231843145-097498f0-a8fd-4d9a-be5a-6f96f5eac088.png)

Link State:
![image](https://user-images.githubusercontent.com/104592970/231843615-86b7dcff-6c79-4862-a54b-2a04cdb05811.png)

**Comment by srebhan** [comment]
@ghost this issue should be solved in recent versions of Telegraf after the socket restructuring. The [new code](https://github.com/influxdata/telegraf/blob/fe7321e35bfac1ebff52793e7826bee6a0551536/plugins/common/socket/socket.go#L69) does the right thing IMO. Could you please confirm that the issue no longer exists!?
