### ISSUE TITLE
socket_listener loses track of connections when they don't initialize properly

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#13051]
### Relevant telegraf.conf

```toml
.
```

### Logs from Telegraf

```text
.
```

### System info

35edd18

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

.

### Actual behavior

.

### Additional info

While reviewing the code, I noticed several cases in `(*streamListener).setupConnection()` that will cause the plugin to lose track of the connection. Basically the function returns early before it gets to the part where it adds the connection to `(*streamListeneter).connections`.

https://github.com/influxdata/telegraf/blob/35edd1863fb135570abe2d6a0c0241bbdc3c6ec8/plugins/inputs/socket_listener/stream_listener.go#L107-L119

As these errors are non-fatal to the initialization of the socket instance, it has various side effects, one of them being that when calling `close` (e.g. during shutdown), it won't close the connections, and will block until the client does.

https://github.com/influxdata/telegraf/blob/35edd1863fb135570abe2d6a0c0241bbdc3c6ec8/plugins/inputs/socket_listener/stream_listener.go#L150-L154

**Comment by powersj** [comment]
next steps: finish review of #13056
