### ISSUE TITLE
Upgrade azure packages

### ISSUE THREAD

**Issue by asaharn** [influxdata/telegraf#13067]
As [go-autorest](https://github.com/Azure/go-autorest#note-the-modules-in-this-repo-will-go-out-of-support-by-march-31-2023--additional-information-can-be-found-here) went out of support on 31st March 2023. 

Related Azure plugins need to be moved from go-autorest.

**Comment by asaharn** [comment]
We updated [Azure Data Explorer](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/azure_data_explorer#azure-data-explorer-output-plugin) output plugin with the latest libs after which we are not able to build telegraf, since there is a lib `logzio/azure-monitor-metrics-receiver` used by [Azure Monitor](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/azure_monitor#azure-monitor-output-plugin) haivng compatibility issues with the `armresources`(since this got upgraded with our changes and using azidentity now). 
To resolve this [Azure Monitor](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/azure_monitor#azure-monitor-output-plugin) will need to upgrade to the latest.


![image](https://user-images.githubusercontent.com/102726227/230962784-5c7b7ccb-78ac-43ef-9e84-73acc541abd5.png)

**Comment by powersj** [comment]
This sounds like a dup of #12535. You can see my comments over there and feel free to add more over there, and see my upstream issue for [logzio/azure-metrics-monitor-receiver here](https://github.com/logzio/azure-monitor-metrics-receiver/issues/2)

I am going to close this as a dup for now, but you disagree let me know.
