### ISSUE TITLE
Add binary metric to monitor gnmi connection state

### ISSUE THREAD

**Issue by protonmarco** [influxdata/telegraf#13088]
### Use Case

This would be very needed to monitor the state of the different gnmi connections, in order also to understand the reliability of the data coming in.

### Expected behavior

I would expect to have a metric showing 0 or 1 based on the gnmi status of an host, with the hostname as a tag.
Example: gnmi_status{source="my_hostname"} 0/1

### Actual behavior

At the moment such metric is not present.
The nearest thing is the `internal_gather_errors{input="gnmi"}` from the telegraf internal plugin, but it is a timeseries which doesn't fit the use case of having a metric that represent the state of the connection.

**Comment by protonmarco** [comment]
I understand the hesitancy, but I think that given the nature of the plugin it is worth having such internal metric, I'm going to reply to your points to give more context:

> - Adding this results in yet another type of metric that gets created and I'm not clear on what status means or what the error is

The metric would just reflect the gnmi connection status towards the host, I think it can be summed up with this logic:
does it have at least one active subscription towards the host X? -> gnmi_status{source="X"} 1
else -> gnmi_status{source="X"} 0 (whatever is the problem, which most of the time, if not always, gets logged in telegraf logs)

> - When a connection failure occurs you stop getting metrics, which is pretty clear something is wrong

Yes and no, on aggregated data this information gets lost easily. 
A couple of real examples can be when you aggregate interface traffic from multiple devices and one goes down, if it doesn't hold a big % of that traffic it's hard to spot, or when you aggregate state metric like device alerts, you can have a dashboard which shows no alerts while you may have lost the connection with most of the devices. 

> - Using other plugins like ping or even exec to test connectivity

These plugins doesn't solve this specific problem as you can have a valid ping but no gnmi connection (for example because of tls certificates expired or simply because gnmi is being blocked or is not configured anymore on the switch) and exec is not suitable for switches as streaming telemetry -hence gnmi- was born mainly to move away from polling based telemetry, which is cpu-intensive for the switches/etc.

> - What do you report if you can connect, but a different error shows up (e.g. 404/401)?

Is there a state where you can establish a successful gnmi connection but not get metrics?
I need to research this a bit because right now I can't think of an example of such state, I think it's safe to assume that even if a single subscription is up the status is ok else ko.

> - More importantly, on errors, which we treat as fatal in nearly every case of an input we usually do not send any metrics. We report the error and move on.

I understand, in this case it would mean adding an internal metric to the gnmi plugin which stays always on (if flagged), I hope it doesn't have big implication on telegraf logic.

**Comment by powersj** [comment]
> Yes and no, on aggregated data this information gets lost easily.

Thanks for bringing up this and detailing this scenario.

> Is there a state where you can establish a successful gnmi connection but not get metrics?
> I need to research this a bit because right now I can't think of an example of such state, I think it's safe to assume that even if a single subscription is up the status is ok else ko.

I may be over complicating this so went looking at the code ;)

1. Each [server gets a go function kicked off](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/gnmi/gnmi.go#L188-L201)
2. The handler function itself sits [unitl there is a context error](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/gnmi/handler.go#L82-L106)
3. When there is an error we report connection closed. This seems like a possible place to report the internal stat. Return everything is good when we log we are connected and return disconnected if we drop out of the for loop due to a context error? This is not something that would get reported at each interval as this is a service input, but it would report 0 at the start, report 1 when disconnected and report back to 0 when we reconnect.

Does that line up with what you were after?

**Comment by protonmarco** [comment]
> This is not something that would get reported at each interval as this is a service input, but it would report 0 at the start, report 1 when disconnected and report back to 0 when we reconnect.
>
> Does that line up with what you were after?

If this would be the logic behind and the output is a timeseries, I think it would work nicely.

**Comment by powersj** [comment]
I have put up #13149 with a possible fix. Would you be willing to download the artifacts that will attach in 20-30mins and give it a try and verify that it reports the status, per server, 0 for disconnected and 1 for connected.

Please let me know if have any better naming/bikeshedding of the metric as well :)

Thanks!

**Comment by powersj** [comment]
> Works like a charm and I think the naming is ok too.
> Thanks a lot!

Thank you very much for the prompt feedback. I will add a couple lines based on your comment :)

Thanks again!
