### ISSUE TITLE
timestamp is dropped by processors.parser if merge = "override" is set

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13102]
### Relevant telegraf.conf

```toml
[[inputs.file]]
  files = ["/path/to/minimal.log"]
  data_format = "grok"
  grok_patterns = ["^%{GREEDYDATA:whole_line}$"]
  name_override = "watchtheclock"

[[processors.parser]]
  order = 10
  parse_fields = ["whole_line"]
  namepass = ["watchtheclock"]
  data_format = "json_v2"
  merge = "override"       # <<<<<<< why does this kill the newly parsed timestamp?! shouldn't this drop the current time?

[[processors.parser.json_v2]]
  order = 20
  namepass = ["watchtheclock"]
  timestamp_format = "02/Jan/2006:15:04:05.000000 -0700"
  timestamp_path = "timestamp.time"

  ## just to fill it with sth. This is irrelevant
    [[processors.parser.json_v2.tag]]
       path = "t"
       type = "string"
       optional = false
    [[processors.parser.json_v2.field]]
       path = "f"
       type = "int"
       optional = false

[[outputs.file]]
  files = ["stdout"]   ## testing ... testing ... one two three
  data_format = "influx"
```

### Logs from Telegraf

```text
me@host:~/telegraf-json_v2-processor-bug$ telegraf --test --config not_working.conf --debug --t
est-wait 1
2023-04-17T14:12:00Z I! Loading config file: not_working.conf
2023-04-17T14:12:00Z I! Starting Telegraf 1.26.0
2023-04-17T14:12:00Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-04-17T14:12:00Z I! Loaded inputs: file
2023-04-17T14:12:00Z I! Loaded aggregators:
2023-04-17T14:12:00Z I! Loaded processors: parser
2023-04-17T14:12:00Z I! Loaded secretstores:
2023-04-17T14:12:00Z W! Outputs are not used in testing mode!
2023-04-17T14:12:00Z I! Tags enabled: host=host.fqdn
2023-04-17T14:12:00Z D! [agent] Initializing plugins
2023-04-17T14:12:00Z D! [agent] Starting service inputs
> watchtheclock,host=hostname.dom.ex,t=test f=123i,whole_line="{\"timestamp\":{\"time\":\"17/Apr/2023:09:56:41.
731416 +0200\"}, \"t\":\"test\", \"f\":123}" 1681740720000000000
2023-04-17T14:12:01Z D! [agent] Stopping service inputs
2023-04-17T14:12:01Z D! [agent] Input channel closed
2023-04-17T14:12:01Z D! [agent] Processor channel closed
2023-04-17T14:12:01Z D! [agent] Stopped Successfully
me@host:~/telegraf-json_v2-processor-bug$
```

### System info

1.26.0-1 RHEL 8.7

### Steps to reproduce

1. Try to parse timestamp with json_v2 and 'merge = "override"' in a "processors.parser" block.
2. watch how your timestamp is discarded, even though docs claim that the newly parsed data (ok, it only says metrics, but even still...) takes precedence.
3. create the above file to demonstrate in bug report.
...

### Expected behavior

The metric having the timestamp I parse into it.

### Actual behavior

The metric is stamped with the current time

### Additional info

```
me@host:~/telegraf-json_v2-processor-bug# cat minimal.log
{"timestamp":{"time":"17/Apr/2023:09:56:41.731416 +0200"}, "t":"test", "f":123}
```

**Comment by powersj** [comment]
Hi,

To ensure I am not missing an easier solution, are you not using the JSON parser from the start with the file input plugin because the log has additional items like a timestamp? Or is the log itself JSON?

For what it is worth, the [merge function](https://github.com/influxdata/telegraf/blob/master/plugins/processors/parser/parser.go#L110-L121) only adds fields, tags, and name. I do not see any reference to a timestamp in that processor.

Thoughts?

**Comment by knollet** [comment]
Because this is only a minimal example-config which should work. The actual config was larger, more complex and used a pipeline of processors, which the json_v2 parser was a part of after some preprocessing.

I am not looking for a workaround to this problem. We already have it working.

This is just a bugreport.

Yes, the docs only say fields, tags and name are updated by this, but it, then, makes no sense to me, why the timestamp shouldn't, You can specify that it should be parsed.
If merge is intended to not update the timestamp, the plugin should error out refusing to parse the timestamp at all.

**Comment by powersj** [comment]
> If merge is intended to not update the timestamp, the plugin should error out refusing to parse the timestamp at all.

We will talk about what to do with this, off the cuff it sounds like we either add an option to look at the timestamp or add better docs to specify that the timestamp is not included.

**Comment by Hipska** [comment]
Ideal situation would be if the parser would be smart and magically know if there is a new timestamp parsed. But a config option to indicate which timestamp to keep would be the best and more flexible result I guess.

**Comment by knollet** [comment]
There already are options, which are there if and only if there is a new timestamp parsed:
timestamp_path and timestamp_format.
You don't have to somehow magically get that information. It's already there.

**Comment by Hipska** [comment]
No that is a setting specific from `json_v2` parser, not something that is global for the `parser` processor.

**Comment by knollet** [comment]
The Plugins could set the timestamp to -1 if nothing is parsed, and the parser-wrapper could then decide to not merge it, if "merge=override" is set. Set it to "now()" if merge=override is not set.

If it is not -1, then merge it if merge=override is set, and leave it if it is not set.

**Comment by Hipska** [comment]
That makes sense if you specifically can request to parse a timestamp on the processor, but some parsers/protocols always have a timestamp. (See graphite, influx, prometheus, ...)

I think it would still be best and easiest to specifically define if you want to overwrite the metric timestamp or not in those cases. It would give the most flexibility.

**Comment by knollet** [comment]
fine by me. It solves the problem.
It may be not the nicest, roundest solution, but it seems not to be so trivial, after all.

**Comment by Hipska** [comment]
Great, can You write a detailed feature request for this?

**Comment by knollet** [comment]
Yes, i'm ok with that.

**Comment by powersj** [comment]
PR https://github.com/influxdata/telegraf/pull/13147

Artifacts with the new option will be available in 20-30mins. I would appreciate if you could download the artifact for your platform and let us know if it resolves your scenario!

Thanks!
