### ISSUE TITLE
Redis commands non-default (0) database

### ISSUE THREAD

**Issue by Tenzer** [influxdata/telegraf#13100]
### Use Case

I'd like to use Telegraf's Redis plugin for monitoring a queue size in a Redis database. We are currently using the `input.exec` plugin and calling `redis-cli` to do this, but I thought I instead would try and get it switched over to be done via `input.redis.commands`, but found that it wasn't possible because the queue is not in Redis database 0, and there's no way to change the database to run the Redis command in.

### Expected behavior

There should be a way to change the logical Redis database used for the connection. It could be at the connection level or, if possible, on the command level.

### Actual behavior

There currently isn't any way of doing this.

### Additional info

go-redis - the library used for connecting to Redis - already have functionality in place for choosing the Redis database when establishing the connection: https://redis.uptrace.dev/guide/go-redis.html#connecting-to-redis-server.

It should be relatively little work to follow the pattern it uses for providing the database ID via the path portion of the connection string and defaulting to database ID 0 if the path is `/` or empty. Does that sound like a reasonable change to make?

**Comment by powersj** [comment]
Hi,

If we were to add a `database` parameter to the command subsection can telegraf use the existing client and switch to that database to run the command? Or would telegraf need a different client for each database?

If that is not possible, then I think you would need to specify at the higher plugin level. Would the plugin then only collect specific commands that the user specifies for that database?

Thanks!

**Comment by Tenzer** [comment]
Yes, you can change the database for the active connection using the [SELECT](https://redis.io/commands/select/) command.

If the code ends up effectively running `SELECT <db>` followed by `LLEN <key>` or whatever custom command you want, then it might make sense to make use of [pipelining](https://redis.uptrace.dev/guide/go-redis-pipelines.html#pipelines) to reduce the number of roundtrips required to the database, although that also can be done at a later stage.

Alternatively, it might make sense to store which database currently is selected, so the `SELECT` command only needs to be run in case a custom command requires a different database. It doesn't look like Go Redis stores this information and keeps it up to date as the database is switched for the connection.

**Comment by powersj** [comment]
> Yes, you can change the database for the active connection using the [SELECT](https://redis.io/commands/select/) command.

Excellent. I think re: pipelineing, that could come later if we find the initial performance is sufficient.

I was looking at the `[[inputs.redis.commands]]` config and it appears that the output of those values all get dumped into one metric called `redis_commands`. If we suddenly started grabbing values from different databases I think it would make sense to be able to differentiate between the results.

My off the cuff thought to ensure we maintain backwards compatability:

* Create a `[[inputs.redis.database]]` config option that is essentially the same as the `[[inputs.redis.commands]]`, but includes a database parameter that defaults to `0`
* In something similar to `gatherCommandValues` function, we would switch to whatever database is declared, run the Do command and generate a new `redis_database` metric per database with a tag called `database`.
* At the end of the function return the connection back to database 0

Does that sound like a way forward?

**Comment by powersj** [comment]
@Tenzer did you have any thoughts on my previous comment? I want to ensure we have a way forward. Thanks
