### ISSUE TITLE
VMware and GPU info (Nvidia)

### ISSUE THREAD

**Issue by csupi003** [influxdata/telegraf#13109]
### Use Case

We have a VMware cluster with 10+ hosts with Nvidia GPUs and 100+ VMs using those GPUs. VMware monitoring works fine however the telegraf install with nvidia-smi plugin looks challenging with 100+ VMs. 

Would it be possible to somehow to use the vSphere plugin to gather info about the GPUs? 

Thanks in advance

### Expected behavior

Get GPU info with vSphere plugin. 

### Actual behavior

GPU info is not available

**Comment by powersj** [comment]
> Would it be possible to somehow to use the vSphere plugin to gather info about the GPUs?

what info does the vSphere API present with respect to GPUs?

**Comment by csupi003** [comment]
According to this document GPU temperature, utilization, and memory usage.

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-1EEF05FA-BD39-4594-92D2-EFB92EE98A65.html

**Comment by powersj** [comment]
That document is about the UI not the API :) That also looks to be specific to the host and not the VMs.

Looking at the [vmware/govmomi library](https://github.com/search?q=repo%3Avmware%2Fgovmomi+gpu&type=code) which is what is used by telegraf, I see a few references to GPU profiles, but not related to temperature, utilization, or memory usage.

Looking at the [vCenter REST APIs](https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/) and searching for GPU or looking at the hardware listed under VMs, I also don't see GPU items.

I would recommend asking in the VMware communities to see if this even exists at the API level and then seeing if it is possible with the govmomi library. Not even sure I am looking at the right areas.

**Comment by csupi003** [comment]
oh yes you are right, thanks a lot for the investigation, I'll will ask the VMware community.
