### ISSUE TITLE
Gather Rabbitmq metrics for 2 hosts on a third one results in overwrite of host 1 in the DB

### ISSUE THREAD

**Issue by martinseener** [influxdata/telegraf#1311]
### System info:

Telegraf 0.13.0

### Steps to reproduce:
Use the Rabbitmq plugin and gather metrics on a "monitoring" node for 2 HAProxy nodes say
Monitoring node -> [[inputs.rabbitmq]] urls = ["rabbit@rmq1", "rabbit@rmq2"]

When looking into the database we will have metrics from node "monitoring" and "rmq2" so rmq1 metrics ARE "monitoring" metrics.

### Expected behavior:

I expect that metrics from rmq1 are tagged with host "rmq1" instead of "monitoring"

### Actual behavior:
the plugin seems to overwrite the host with its own, at least for the first url metrics are gathered from

### Use case:
Problem occurs when monitoring from a "third-party" a set of nodes. (dont have tried monitoring a single node from third party but i expect this ones metrics have also overwritten hostname). The use case is monitoring a cluster from a "monitoring" server which correctly uses the respective host names instead of its own for at least the first monitored node.

**Comment by sparrc** [comment]
I'm not sure I fully understand.... one of your metrics gets the tag `server=monitoring`? Can you show me influxdb query output?

**Comment by martinseener** [comment]
I'am really sorry. I worked on HAproxy this morning which obviously influenced my bug report. I meant the Rabbitmq plugin.

When gathering metrics from 2 rabbit nodes from a monitoring server (which itself has nothing to do with rabbitmq but only monitors it with telegraf) the metrics written will have "host = monitoringserver.domain.com" and "host = rmq2.domain.com" but i expected "host" to have "rmq1.domain.com" for the first node ("WHERE host =" in the Query). Is it more clear what i mean?

**Comment by sparrc** [comment]
the `host` tag is always the server that telegraf is running on. I believe the tag you want for rabbitmq is the `url` tag, which indicates the remote host being monitored.

sorry if that's confusing, but there really isn't any way for telegraf to know whether a user cares more about the host that telegraf is running on, or the remote host being monitored. So in general `host` is used as the telegraf host and another tag must be used for the remote host.
