### ISSUE TITLE
Using /lib/systemd as a test for installing/enabling telegraf.service

### ISSUE THREAD

**Issue by jbp4444** [influxdata/telegraf#13119]
### Use Case

When installing Telegraf into a chroot environment, the test used for enabling the systemd service can fail:

```
if [[ -d /run/systemd/system ]]; then
    cp -f /usr/lib/telegraf/scripts/telegraf.service /usr/lib/systemd/system/telegraf.service
    systemctl enable telegraf
    systemctl daemon-reload
fi 
```
An alternative would be to use /lib/systemd -- which does exist in Rocky/RHEL and Ubuntu, and should exist in anything that runs systemd.
```
if [[ -d /lib/systemd ]]; then
    cp -f /usr/lib/telegraf/scripts/telegraf.service /usr/lib/systemd/system/telegraf.service
    systemctl enable telegraf
    systemctl daemon-reload
fi 
```

### Expected behavior

System start up should be the same, but should now work with installs into chroot environments.

### Actual behavior

When installed in a chroot, the current Telegraf package never gets enabled since the /run directory does not exist.

**Comment by powersj** [comment]
> When installing Telegraf into a chroot environment,

In a chroot, the `systemctl` commands would also not be safe to run as well, right? Would this be safer:

1. if `/lib/systemd` exists cp the service file
2. if that worked, check if `/run/systemd/system` exists meaning systemd is up and running and then run the two systemctl commands?

**Comment by jbp4444** [comment]
I'm not sure that would work (at least not for us) ... it means the chroot would not enable the service, which would not create the symlinks/etc. that come with "systemctl enable".  

Since this is "at install time" that we're talking about, do you need to know that systemd is running?  isn't it enough to know that systemd will be running (i.e. /lib/systemd exists)?  (awkward way to say that, but hopefully you get what I mean)

**Comment by powersj** [comment]
>  it means the chroot would not enable the service, which would not create the symlinks/etc. that come with "systemctl enable".

How do you have `systemctl` working in a chroot, without `/run/systemd`? I assume you aren't using it and are instead manually setting up what `systemctl enable` would do?

**Comment by jbp4444** [comment]
Sorry for the delay -- when we're in the `chroot`, we're creating a ramdisk that a to-be-booted system will use, so `systemd` isn't running at that time (and `/run/systemd `isn't present).

**Comment by powersj** [comment]
It really sounds like for your use case you are far better off grabbing the tarball, extracting it, and putting creating the necessary service symlinks in place that you need. I not inclined to edit the current maintainers scripts to start moving files around manually and instead continue to rely on the systemctl commands to do the right thing.

**Comment by jbp4444** [comment]
I realize this is going off from the usual paths ... but if one wanted to install Telegraf _inside_ a Docker container (e.g. to monitor per-container resource usage), then the standard `docker build` command also runs into this problem.  E.g.
```
FROM rockylinux:8.7
COPY influx.repo /etc/yum.repos.d/influx.repo
RUN  yum --assumeyes install telegraf
```
This will install the package files into the container but since /run/systemd isn't present in the docker-build environment, it also does not enable the service (yes, you'd need some other tooling to run [systemd/equivalent](https://github.com/gdraheim/docker-systemctl-replacement) inside the container).

**Comment by powersj** [comment]
> I realize this is going off from the usual paths ... 

This is the crux of the issue :) 

> but if one wanted to install Telegraf inside a Docker container

We provide containers for this use-case, if someone wants to build their own, then we are right back to doing something custom. 

The rpms and debs we provide are built and expected to be used on a running system. A user building an image from scratch would be best served using the tarball or ensuring systemd is running and/or available, or running the extra commands required.

Finally, making such a change does have the potential to impact users who are not expecting the systemd service to get set up, using a different init system, or relying on the existing behavior.

This is not a change I am willing to make at this time. I am going to close this as not in plan.

**Comment by NateCrawford** [comment]
Inside a container, "systemctl enable" and "systemctl disable" are some of the few systemctl commands that actually work. 

This sort of thing should work:
```
if [[ -d /usr/lib/systemd/system ]]; then
   cp -f /usr/lib/telegraf/scripts/telegraf.service /usr/lib/systemd/system/telegraf.service
   systemctl enable telegraf
   if [[ -d /run/systemd/system ]]; then
       systemctl daemon-reload
   fi
fi 
```
