### ISSUE TITLE
sadc_interval in inputs.sysstat is undocumented but should be

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13125]
### Use Case

`inputs.sysstat` sometimes reports 
> `Collection took longer than expected; not complete after interval of 10s`

inputs.sysstat uses `sadc` to collect information.

so if I have
```
[[inputs.sysstat]]
  interval = "10s"
  ...

```
then the "CollectInterval" will be set to 9 seconds (interval-1)  
(see: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sysstat/sysstat.go#L152 )

sadc by itself is asked to collect twice ( "2" hardcoded, line 159), once at upstart, then wait "CollectInterval" then collect again.
So the second collection by sadc begins at "CollectInterval" seconds, and may potentially on some rare and slow and loaded system, take more than half a sec. (We're at CollectInterval+0.5 then), then sadf is started to parse this. If this takes more than the remaining time to "interval" (interval=10s in our example, so there would be only half a second be left, and remember, our example is loaded and slow), then you get the "Collection took longer than expected".

So. In a documented way, the second collection of sadc and the parsing of sadf together have always to be in less than 1s. Not configurable.

Enter sadc_interval: This lets you set the CollectionInterval, and with this, potentially fix the "Collection took longer than expected" problem by setting
```
  interval = "10s"
  sadc_interval = "8s"
```
...this way, the second collection and the sadf-parsing would have two seconds and would less likely timeout.

### Expected behavior

Find this information in the plugin readme

### Actual behavior

`sadc_interval` is not documented.

### Additional info

Another, perhaps even better, fix would be to make `parseInterval` configurable.

**Comment by powersj** [comment]
Hi,

> may potentially on some rare and slow and loaded system

I am curious what rare system are you on? :)

I have put up #13151 which exposes both intervals in the sample config. Could you please give it a try to ensure I have the done the conversions to seconds correctly and consistently.

Thanks!
