### ISSUE TITLE
Dashboard auto logs out user

### ISSUE THREAD

**Issue by gsilva2016** [influxdata/telegraf#13120]
### Use Case

Need to load/start a dashboard in telegraf and let it display for hours 

### Expected behavior

Start a telegraf dashboard and displays for hours/day. 

### Actual behavior

Started a telegraf dashboard and displays for X amount of time until the signed-in user is auto logged out and the user needs to sign-in again to go back to the dashboard.

**Comment by powersj** [comment]
Telegraf is not a dashboard. It is a CLI agent to collect metrics. I think you are using some sort of dashboard tool (e.g. grafana?!).

**Comment by gsilva2016** [comment]
It seems the influxdb2 controls the settings for the grafana dashboard telegraf sending data for. I found setting referencing https://community.influxdata.com/t/disabling-or-setting-session-idle-timeout/25207/4. Thanks
