### ISSUE TITLE
Add Google API Endpoint Configuration Option for outputs.stackdriver 

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13132]
### Use Case

When using the outputs.stackdriver plugin the Google API endpoint appears to be hardcoded in the plugin to point to custom.googleapis.com. This was fine in the past, but since this plugin can also be used for other purposes like sending to Google Managed Prometheus it would be greatly beneficial to make the API endpoint configurable. Currently, metrics being sent in go into a Custom (for lack of a better word) bucket in Google which greatly increases the metric prefix, and makes the metric more difficult to find. 

Currently hardcoded:
custom.googleapis.com

I think it should probably default to the above endpoint, but should be configurable so you can point it to a different endpoint if needed:
prometheus.googleapis.com

### Expected behavior

Use outputs.stackdriver to send metrics into Google Managed Prometheus (or other use case).
Configure the plugin to send to `prometheus.googleapis.com`.
Metrics show up in their correct location in the Google Metrics Explorer, not in the Custom bucket. 

Example of a correct result:

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/69858641/234040733-9f0cdb6f-8cd8-4a52-8167-c026c64f0add.png">

Current result:

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/69858641/234041699-1df39fa1-258d-4038-a73b-0fed188a767c.png">

### Actual behavior

Metrics are sent to the Custom bucket and when connected to Grafana the return metric has a really long prefix:

Current configuration using Telegraf:
custom_googleapis_com:store_pc_metrics_disk_inodes_free{monitored_resource=""}

What it looks like if I use another tool like the [OpenTelemetry Google Managed Prometheus exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlemanagedprometheusexporter) which sends to the correct API endpoint (different metric, but you get the idea):
prod_compute_services_machine_metrics_win_cpu_Percent_Interrupt_Time{}

### Additional info

Issue submitted per @jpowers

**Comment by powersj** [comment]
@crflanigan,

Thank you for the issue. can you take a look at https://github.com/influxdata/telegraf/pull/13168 and let me know if that is what you are after? 

Also can or should we allow an empty prefix? Based on the [docs](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors) it looked like this was required in some form.
