### ISSUE TITLE
Azure Arc-enabled SQL Managed Instance Support

### ISSUE THREAD

**Issue by nikosheng** [influxdata/telegraf#13145]
### Use Case

We need to use telegraf to stream the metrics of azure arc-enabled sql managed instance to influxdb, however, currently the sql server plugin is not supporting the arc-enabled sql mi.

### Expected behavior

Support azure arc-enabled sql managed instance

### Actual behavior

Error occurs while deploying the sql server plugin and try to grap the metrics
```
2023-04-26T08:44:00Z E! [inputs.sqlserver] Error in plugin: query SQLServerWaitStatsCategorized failed for server: 10.224.0.57 and database: <empty-database-name> with Msg 50000, Level 11, State 1:, Line 5, Error: mssql: Telegraf - Connection string Server:sqlinstance1-0,Database:master is not a AzureSQLManagedInstance. Check the database_type parameter in the telegraf configuration.
```

**Comment by powersj** [comment]
Hi,

> azure arc-enabled sql managed instance

How is this different than a vanilla sql server instance? Does it require different authentication? The [go-mssqldb](https://github.com/denisenkom/go-mssqldb) in use seems to support Azure-hosted SQL servers.

> Connection string Server:sqlinstance1-0,Database:master is not a AzureSQLManagedInstance

Did you try "AzureSQLDB" or even "SQLServer"? Can you share the full connection string and how you are authenticating?

**Comment by nikosheng** [comment]
@powersj Thanks Joshua, I have tried `AzureSQLDB` and `SQLServer` database type but all fail. I am not sure which code snippet to validate the sql server type but for azure arc-enabled sql managed instance, which is a sql server running in container environment, is not supposed to be a different type of SQL Server.

**Comment by nikosheng** [comment]
@powersj  I would like to submit a PR to fix the issue to support Azure Arc-enabled SQL MI as well and I have tested and it works in my environment. It would be great if you could share with me if it is to directly include it in `AzureSQLManagedInstance` database type or we need to create a new type to support Azure Arc-enabled SQL MI

**Comment by nikosheng** [comment]
| I would be inclined to give this type it's own type in Telegraf. As Microsoft gave it a unique number and in the event that we find some sort of difference down the road. What do you think?

@powersj  Agree with your suggestion and I will create a new type to include the new sql server engine. Meanwhile, I also suggest to include the metrics for in-memory OLTP for SQL Server as it is a widely adopted feature in SQL Server and lots of the developers would love to search the in-memory OLTP metrics by telegraf.

**Comment by powersj** [comment]
> @powersj Agree with your suggestion and I will create a new type to include the new sql server engine.

Awesome look forward to the PR

> Meanwhile, I also suggest to include the metrics for in-memory OLTP for SQL Server as it is a widely adopted feature in SQL Server and lots of the developers would love to search the in-memory OLTP metrics by telegraf.

No opposed to this as well, but can you propose that in a second PR please?

Thanks!
