### ISSUE TITLE
Capability to drop __name label when sending logs to Loki

### ISSUE THREAD

**Issue by liam-howe-maersk** [influxdata/telegraf#13146]
### Use Case

We run a Grafana Loki backend for our logging and we have a strict allow list for what labels we allow to be ingested in to our system to help with performance and to follow suggestions from Grafana. We have a team using the telegraf agent to forward their logs to our Loki instance and we are currently blocking them because we discovered these logs include the label `__name`, we would like the ability to drop this label when sending logs to Loki so we can continue blocking this label.

### Expected behavior

I can provide some configuration that will prevent this tag from being added if we do not wish it to be, for example, including the `__name` tag in the `fielddrop` or `tagexclude` configuration options

### Actual behavior

The `__name` tag is added to the label in the Loki stream, there is no way to prevent this.

### Additional info

Reference for where this tag is added to the stream without any option to prevent it https://github.com/influxdata/telegraf/blob/bdfbe67cb099df7af1752d96534cd047c3c3bb4d/plugins/outputs/loki/loki.go#L122

**Comment by powersj** [comment]
Hi,

> for example, including the __name tag in the fielddrop or tagexclude configuration options

At the point where the `__name` tag is added, field and tag filters have already run.

> The __name tag is added to the label in the Loki stream, there is no way to prevent this.

This was added after the report in #10000, where the [user outlines here](https://github.com/influxdata/telegraf/pull/10001#issuecomment-953063750) how without somehow including the name you cannot differentiate between metrics. 

Is your intention to completely remove the metric name from data you send? Or could this field have an option to be renamed instead?

**Comment by liam-howe-maersk** [comment]
The use case that we have is that a team is forwarding logs from logstash to an `inputs.socket_listener` in a telegraf agent and then using `outputs.loki` to forward these log lines on to our Loki instance. In this case the `__name` is always `socket_listener` so we don't need this information, especially as a label, we could perhaps have it appended to the log line itself as `__name=socket_listener`, but really we don't need it at all.

**Comment by liam-howe-maersk** [comment]
I'm afraid `labeldrop` in Loki doesn't work if you are referring to the [labeldrop stage in promtail](https://grafana.com/docs/loki/latest/clients/promtail/stages/labeldrop/) as this is applied at the stage that you use promtail to scrape the logs in order to send to Loki, however, in this case we are using the telegraf agent itself to send the logs directly to Loki so there is no opportunity to run the promtail `labeldrop` stage.

We have checked out the feature branch implementation that you have provided with https://github.com/influxdata/telegraf/pull/13157 and confirm that this does what we are looking for so from our point of view we are very happy for this change to be implemented! Thanks a lot for looking in to it.
