### ISSUE TITLE
The usage of input.sphere for resourcepool 

### ISSUE THREAD

**Issue by nookseal** [influxdata/telegraf#13152]
As from the README state that it is now supported for resource pool metric, I've seen that resource pool metric 
refer to this #6782 

**Configuration from README file** [https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/README.md](url)
````
  ## Resource Pools
  # datastore_include = [ "/*/host/**"] # Inventory path to datastores to collect (by default all are collected)
  # datastore_exclude = [] # Inventory paths to exclude
  # datastore_metric_include = [] ## if omitted or empty, all metrics are collected
  # datastore_metric_exclude = [] ## Nothing excluded by default
  # datastore_instances = false ## false by default

  ## Datastores
  # datastore_include = [ "/*/datastore/**"] # Inventory path to datastores to collect (by default all are collected)
  # datastore_exclude = [] # Inventory paths to exclude
  # datastore_metric_include = [] ## if omitted or empty, all metrics are collected
  # datastore_metric_exclude = [] ## Nothing excluded by default
  # datastore_instances = false ## false by default
````

**Logs from Telegraf**
````
telegraf    | 2023-04-27T03:39:34Z I! Loading config: /etc/telegraf/telegraf.d/vsphere-metrics.conf
telegraf    | 2023-04-27T03:39:34Z E! error loading config file /etc/telegraf/telegraf.d/vsphere-metrics.conf: error parsing data: line 150: key 'datastore_metric_include' is in conflict with line 82d
             telegraf exited with code 1
````

which means that it's the duplicate attribute on the configuration file, what is the exact name should I use to be able to gather resource pool metrics? [https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md#resource-pool-metrics](url)

**Comment by Hipska** [comment]
Which version of telegraf are you using? I recommend using latest version.

**Comment by nookseal** [comment]
> Which version of telegraf are you using? I recommend using latest version.

The latest version.

````Telegraf 1.26.2 (git: HEAD@a3a884a1)````
