### ISSUE TITLE
[feature request] Add enable/disable option to plugins

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/telegraf#1317]
### Proposal:
I have several instances of the same plugin. For testing, I want to disable some of them without removing their configuration.
I would like to have an option in the config file as follows:
```
[[input.pluginname]]
name_suffix = "_devices"
enabled = false
```
(default to ```true``` of no ```enabled``` option is defined)
Filtering doesn't work as the plugins share the same name (filtering doesn't support prefixes/suffixes)

### Current behavior:
No such functionality. I could auto generate the config file, but that's not a sustainable solution.

### Desired behavior:
1. Provide an option to selectively enable/disable plugins.
***OR***
2. add an option to ```--filter-input``` to observe prefixes/suffixes

### Use case:
- Testing many instances of the same plugin
- Having changing environments

**Comment by sparrc** [comment]
this won't be supported, sorry, you'll just need to comment them out

**Comment by sparrc** [comment]
ie, in a way, it is already supported, but via commenting rather than a config option

**Comment by bbczeuz** [comment]
Why? Commenting everything out is not a real solution and makes it hard to read. InfluxDB supports this, too. With the 'enabled' option, one can precreate a template configuration and enable plugins as required. A minimum implementation checks for 'enabled=false' and ignores the tree. Checking when filtering is a secondary.
