### ISSUE TITLE
gocritic->badRegexp - Detects suspicious regexp patterns. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13176]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [badRegexp](https://go-critic.com/overview.html#badregexp) - Detects suspicious regexp patterns.

### Example

**Before:**
```
regexp.MustCompile(`(?:^aa|bb|cc)foo[aba]`)
```

**After:**
```
regexp.MustCompile(`^(?:aa|bb|cc)foo[ab]`)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/gnmi/gnmi.go:30:40               gocritic  badRegexp: `\w` intersects with `_` in [\w-_]
plugins/serializers/graphite/graphite.go:19:51  gocritic  badRegexp: suspicious char range `"-:` in [^ "-:\<>-\]_a-~\p{L}]
plugins/serializers/graphite/graphite.go:19:51  gocritic  badRegexp: suspicious char range `>-\]` in [^ "-:\<>-\]_a-~\p{L}]
plugins/serializers/graphite/graphite.go:20:51  gocritic  badRegexp: suspicious char range ` -:` in [^ -:<-~\p{L}]
plugins/serializers/graphite/graphite.go:20:51  gocritic  badRegexp: suspicious char range `<-~` in [^ -:<-~\p{L}]
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by Hipska** [comment]
Yes, will be helpful as most are not very good with creating/understanding RegEx..

**Comment by srebhan** [comment]
I actually think that the graphite detection might have uncovered a bug...

**Comment by zak-pawel** [comment]
I planned to ask each of you to review/check these findings to collectively achieve the best solution :)

Maybe @G-regL (author of https://github.com/influxdata/telegraf/pull/9249) will help with `graphite`?

**Comment by Hipska** [comment]
Update the regex is the plan I guess…
