### ISSUE TITLE
gocritic->codegenComment - Detects malformed ‘code generated’ file comments. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13180]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [codegenComment](https://go-critic.com/overview.html#codegencomment) - Detects malformed ‘code generated’ file comments.

### Example

**Before:**
```
// This file was automatically generated by foogen
```

**After:**
```
// Code generated by foogen. DO NOT EDIT.
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by Hipska** [comment]
I don't see any added value? Is there a global rule for when a 'generated code' comment is malformed?

**Comment by powersj** [comment]
I am not sure I see the value as well. While it looks like `protoc-gen-go` already follows this, if some other tooling uses a different format who cares? Can you point to a "standard" for this?

**Comment by zak-pawel** [comment]
https://pkg.go.dev/cmd/go/internal/generate#pkg-variables
![image](https://user-images.githubusercontent.com/17336997/236498534-b0a56cf5-8c3c-4913-a5ea-b079f15aa5e6.png)

Thanks to following that standard, other linters and tools can potentially ignore such files during searches/scans.
