### ISSUE TITLE
gocritic->deferInLoop - Detects loops inside functions that use defer. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13182]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [deferInLoop](https://go-critic.com/overview.html#deferinloop) - Detects loops inside functions that use defer.

### Example

**Before:**
```
for _, filename := range []string{"foo", "bar"} {
	 f, err := os.Open(filename)
	
	defer f.Close()
}
```

**After:**
```
func process(filename string) {
	 f, err := os.Open(filename)
	
	defer f.Close()
}
/* ... */
for _, filename := range []string{"foo", "bar"} {
	process(filename)
}
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/haproxy/haproxy_test.go:137:3  gocritic  deferInLoop: Possible resource leak, 'defer' is called in the 'for' loop
plugins/outputs/sql/sql.go:251:4              gocritic  deferInLoop: Possible resource leak, 'defer' is called in the 'for' loop
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by Hipska** [comment]
No opinion..

**Comment by powersj** [comment]
Think we are good with this one then
