### ISSUE TITLE
gocritic->deprecatedComment - Detects malformed ‘deprecated’ doc-comments. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13183]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [deprecatedComment](https://go-critic.com/overview.html#deprecatedcomment) - Detects malformed ‘deprecated’ doc-comments.

### Example

**Before:**
```
// deprecated, use FuncNew instead
func FuncOld() int
```

**After:**
```
// Deprecated: use FuncNew instead
func FuncOld() int
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
cmd/telegraf/main_test.go:466:1    gocritic  deprecatedComment: the proper format is `Deprecated: <text>`
plugins/parsers/registry.go:193:1  gocritic  deprecatedComment: use `Deprecated: ` (note the casing) instead of `DEPRECATED: `
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by powersj** [comment]
ship it!
