### ISSUE TITLE
gocritic->flagDeref - Detects immediate dereferencing of `flag` package pointers. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13194]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [flagDeref](https://go-critic.com/overview.html#flagderef) - Detects immediate dereferencing of `flag` package pointers.

### Example

**Before:**
```
b := *flag.Bool("b", false, "b docs")
```

**After:**
```
var b bool; flag.BoolVar(&b, "b", false, "b docs")
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by Hipska** [comment]
No opinion, don't see why it needs to be the suggestion.

**Comment by srebhan** [comment]
No opinion either.

**Comment by powersj** [comment]
we migrated off of using flags to urfave so I think we should not need this. Not sure about all the stuff in tools, but in general I think this may not be worth it

**Comment by srebhan** [comment]
I do agree with Josh.
