### ISSUE TITLE
gocritic->offBy1 - Detects various off-by-one kind of errors. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13198]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [offBy1](https://go-critic.com/overview.html#offby1) - Detects various off-by-one kind of errors.

### Example

**Before:**
```
xs[len(xs)]
```

**After:**
```
xs[len(xs)-1]
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/snmp/netsnmp.go:251:22  gocritic  offBy1: Index() can return -1; maybe you wanted to do Index()+1
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would review current findings and enable this checker.

**Comment by Hipska** [comment]
The finding should indeed be fixed, although not likely to ever occur.

**Comment by powersj** [comment]
all agreed
