### ISSUE TITLE
gocritic->mapKey - Detects suspicious map literal keys. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13196]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [mapKey](https://go-critic.com/overview.html#mapkey) - Detects suspicious map literal keys.

### Example

**Before:**
```
_ = map[string]int{
	"foo": 1,
	"bar ": 2,
}
```

**After:**
```
_ = map[string]int{
	"foo": 1,
	"bar": 2,
}
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/processors/strings/strings_test.go:38:4  gocritic  mapKey: suspucious whitespace in " whitespace " key
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by powersj** [comment]
all agreed
