### ISSUE TITLE
gocritic->syncMapLoadAndDelete - Detects sync.Map load+delete operations that can be replaced with LoadAndDelete. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13207]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [syncMapLoadAndDelete](https://go-critic.com/overview.html#syncmaploadanddelete) - Detects sync.Map load+delete operations that can be replaced with LoadAndDelete.

### Example

**Before:**
```
v, ok := m.Load(k); if ok { m.Delete($k); f(v); }
```

**After:**
```
v, deleted := m.LoadAndDelete(k); if deleted { f(v) }
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by Hipska** [comment]
Doesn't seem necessary for me.
