### ISSUE TITLE
gocritic->returnAfterHttpError - Detects suspicious http.Error call without following return. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13200]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [returnAfterHttpError](https://go-critic.com/overview.html#returnafterhttperror) - Detects suspicious http.Error call without following return.

### Example

**Before:**
```
if err != nil { http.Error(...); }
```

**After:**
```
if err != nil { http.Error(...); return; }
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by Hipska** [comment]
Looks like a very specific check not really relevant for telegraf?

**Comment by powersj** [comment]
-1

**Comment by powersj** [comment]
Closing as won't fix.
