### ISSUE TITLE
gocritic->sloppyTypeAssert - Detects redundant type assertions. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13203]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [sloppyTypeAssert](https://go-critic.com/overview.html#sloppytypeassert) - Detects redundant type assertions.

### Example

**Before:**
```
func f(r io.Reader) interface{} {
	return r.(interface{})
}
```

**After:**
```
func f(r io.Reader) interface{} {
	return r
}
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1

**Comment by ross-lightsource** [comment]
this check is throwing a number of incorrect warnings in my code and I'd like to disable it for my project. How do I disable a single checker?

**Comment by zak-pawel** [comment]
@ross-lightsource 
I would start by reading the `go-critic` linter's [README ](https://github.com/go-critic/go-critic)(if you’re using it directly).  
Or the [description of the `go-critic` configuration](https://golangci-lint.run/usage/linters/#gocritic) in `golangci-lint` (if you’re using that).
