### ISSUE TITLE
gocritic->sloppyTestFuncName - Detects unsupported test and benchmark funcs. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13202]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [sloppyTestFuncName](https://go-critic.com/overview.html#sloppytestfuncname) - Detects unsupported test and benchmark funcs.

### Example

**Before:**
```
func TessstUnit(t *testing.T)
```

**After:**
```
func TestUnit(t *testing.T)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/riemann_listener/riemann_listener_test.go:32:1  gocritic  sloppyTestFuncName: function testStats looks like a test helper, consider to change 1st param to 'tb testing.TB'
plugins/inputs/riemann_listener/riemann_listener_test.go:44:1  gocritic  sloppyTestFuncName: function testMissingService looks like a test helper, consider to change 1st param to 'tb testing.TB'
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by powersj** [comment]
all agreed
