### ISSUE TITLE
gocritic->unnecessaryDefer - Detects redundantly deferred calls. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13210]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [unnecessaryDefer](https://go-critic.com/overview.html#unnecessarydefer) - Detects redundantly deferred calls.

### Example

**Before:**
```
func() {
	defer os.Remove(filename)
}
```

**After:**
```
func() {
	os.Remove(filename)
}
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
agent/agent_posix.go:18:2                            gocritic  unnecessaryDefer: defer signal.Stop(flushRequested) is placed just before return
config/secret_test.go:99:2                           gocritic  unnecessaryDefer: defer ReleaseSecret(retrieved) is placed just before return
plugins/outputs/groundwork/groundwork_test.go:71:2   gocritic  unnecessaryDefer: defer server.Close() is placed just before return
plugins/outputs/groundwork/groundwork_test.go:123:2  gocritic  unnecessaryDefer: defer server.Close() is placed just before return
plugins/outputs/groundwork/groundwork_test.go:192:2  gocritic  unnecessaryDefer: defer server.Close() is placed just before return
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by powersj** [comment]
all agreed
