### ISSUE TITLE
Deployment status of gocritic checkers (group: diagnostic).

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13212]
### Current status:

| Checker | Issue | To enable? | PR(s) | Work finished? |
| --- | :-: | :-: | :-: | :-: |
| appendAssign: Detects suspicious append result assignments | https://github.com/influxdata/telegraf/issues/13171 |  |  |  |
| argOrder: Detects suspicious arguments order | https://github.com/influxdata/telegraf/issues/13172 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| badCall: Detects suspicious function calls | https://github.com/influxdata/telegraf/issues/13173 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| badCond: Detects suspicious condition expressions | https://github.com/influxdata/telegraf/issues/13174 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| badLock: Detects suspicious mutex lock/unlock operations | https://github.com/influxdata/telegraf/issues/13175 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| badRegexp: Detects suspicious regexp patterns | https://github.com/influxdata/telegraf/issues/13176 |  |  |  |
| badSorting: Detects bad usage of sort package | https://github.com/influxdata/telegraf/issues/13177 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| builtinShadowDecl: Detects top-level declarations that shadow the predeclared identifiers | https://github.com/influxdata/telegraf/issues/13178 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| caseOrder: Detects erroneous case order inside switch statements | https://github.com/influxdata/telegraf/issues/13179 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| codegenComment: Detects malformed 'code generated' file comments | https://github.com/influxdata/telegraf/issues/13180 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| commentedOutCode: Detects commented-out code inside function bodies | https://github.com/influxdata/telegraf/issues/13181 | Y | https://github.com/influxdata/telegraf/pull/13714 | Y |
| deferInLoop: Detects loops inside functions that use defer | https://github.com/influxdata/telegraf/issues/13182 | Y | https://github.com/influxdata/telegraf/pull/13280 | Y |
| deprecatedComment: Detects malformed 'deprecated' doc-comments | https://github.com/influxdata/telegraf/issues/13183 | Y | https://github.com/influxdata/telegraf/pull/13714 | Y |
| dupArg: Detects suspicious duplicated arguments | https://github.com/influxdata/telegraf/issues/13184 | Y | https://github.com/influxdata/telegraf/pull/13713 | Y |
| dupBranchBody: Detects duplicated branch bodies inside conditional statements | https://github.com/influxdata/telegraf/issues/13185 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| dupCase: Detects duplicated case clauses inside switch or select statements | https://github.com/influxdata/telegraf/issues/13186 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| dupSubExpr: Detects suspicious duplicated sub-expressions | https://github.com/influxdata/telegraf/issues/13187 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| dynamicFmtString: Detects suspicious formatting strings usage | https://github.com/influxdata/telegraf/issues/13188 | Y | https://github.com/influxdata/telegraf/pull/13279 | Y |
| emptyDecl: Detects suspicious empty declarations blocks | https://github.com/influxdata/telegraf/issues/13189 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| evalOrder: Detects unwanted dependencies on the evaluation order | https://github.com/influxdata/telegraf/issues/13190 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| exitAfterDefer: Detects calls to exit/fatal inside functions that use defer | https://github.com/influxdata/telegraf/issues/13191 | Y | https://github.com/influxdata/telegraf/pull/13280 | Y |
| externalErrorReassign: Detects suspicious reassigment of error from another package | https://github.com/influxdata/telegraf/issues/13192 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| filepathJoin: Detects problems in filepath.Join() function calls | https://github.com/influxdata/telegraf/issues/13193 |  |  |  |
| flagDeref: Detects immediate dereferencing of `flag` package pointers | https://github.com/influxdata/telegraf/issues/13194 | N | x | Y |
| flagName: Detects suspicious flag names | https://github.com/influxdata/telegraf/issues/13195 | Y | https://github.com/influxdata/telegraf/pull/13713 | Y |
| mapKey: Detects suspicious map literal keys | https://github.com/influxdata/telegraf/issues/13196 | Y | https://github.com/influxdata/telegraf/pull/13713 | Y |
| nilValReturn: Detects return statements those results evaluate to nil | https://github.com/influxdata/telegraf/issues/13197 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| offBy1: Detects various off-by-one kind of errors | https://github.com/influxdata/telegraf/issues/13198 | Y | https://github.com/influxdata/telegraf/pull/13713 | Y |
| regexpPattern: Detects suspicious regexp patterns | https://github.com/influxdata/telegraf/issues/13199 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| returnAfterHttpError: Detects suspicious http.Error call without following return | https://github.com/influxdata/telegraf/issues/13200 | N | x | Y |
| sloppyReassign: Detects suspicious/confusing re-assignments | https://github.com/influxdata/telegraf/issues/13201 | Y | https://github.com/influxdata/telegraf/pull/13712 | Y |
| sloppyTestFuncName: Detects unsupported test and benchmark funcs | https://github.com/influxdata/telegraf/issues/13202 | Y | https://github.com/influxdata/telegraf/pull/13711 | Y |
| sloppyTypeAssert: Detects redundant type assertions | https://github.com/influxdata/telegraf/issues/13203 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| sortSlice: Detects suspicious sort.Slice calls | https://github.com/influxdata/telegraf/issues/13204 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| sprintfQuotedString: Detects "%s" formatting directives that can be replaced with %q | https://github.com/influxdata/telegraf/issues/13205 | Y | https://github.com/influxdata/telegraf/pull/13279 | Y |
| sqlQuery: Detects issue in Query() and Exec() calls | https://github.com/influxdata/telegraf/issues/13206 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| syncMapLoadAndDelete: Detects sync.Map load+delete operations that can be replaced with LoadAndDelete | https://github.com/influxdata/telegraf/issues/13207 | Y | https://github.com/influxdata/telegraf/pull/13711 | Y |
| truncateCmp: Detects potential truncation issues when comparing ints of different sizes | https://github.com/influxdata/telegraf/issues/13208 | Y | https://github.com/influxdata/telegraf/pull/13711 | Y |
| uncheckedInlineErr: Detects unchecked errors in if statements | https://github.com/influxdata/telegraf/issues/13209 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |
| unnecessaryDefer: Detects redundantly deferred calls | https://github.com/influxdata/telegraf/issues/13210 | Y | https://github.com/influxdata/telegraf/pull/13280 | Y |
| weakCond: Detects conditions that are unsafe due to not being exhaustive | https://github.com/influxdata/telegraf/issues/13211 | Y | https://github.com/influxdata/telegraf/pull/13247 | Y |

**Comment by powersj** [comment]
next steps: review the above issues and determine course of action

I'll try to get my reviews in by EOD Monday

**Comment by powersj** [comment]
I'm closing this "tracking" issue as there are only two left and we can follow up in those.
