### ISSUE TITLE
gocritic->weakCond - Detects conditions that are unsafe due to not being exhaustive. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13211]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [weakCond](https://go-critic.com/overview.html#weakcond) - Detects conditions that are unsafe due to not being exhaustive.

### Example

**Before:**
```
xs != nil && xs[0] != nil
```

**After:**
```
len(xs) != 0 && xs[0] != nil
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by zak-pawel** [comment]
I would enable this checker.

**Comment by powersj** [comment]
all agreed
