### ISSUE TITLE
Error on net stats

### ISSUE THREAD

**Issue by njordr** [influxdata/telegraf#1323]
### System info:

telegraf version: 0.13.1
system: red hat 5.2

### Steps to reproduce:

1. start telegraf

### Actual behavior:
2016/06/03 12:09:51 ERROR in input [processes]: read /proc/net/stat: is a directory

### Additional info:

[root@cw-spmi-oas05 ~]# ls /proc/net/stat
arp_cache  ndisc_cache  rt_cache

uname -a
Linux cw-spmi-oas05 2.6.18-92.el5 #1 SMP Tue Apr 29 13:16:15 EDT 2008 x86_64 x86_64 x86_64 GNU/Linux

Sadly it's the same machine of https://github.com/influxdata/telegraf/issues/1322 (very old machine)
[telegraf.zip](https://github.com/influxdata/telegraf/files/297381/telegraf.zip)

**Comment by sparrc** [comment]
hmm...this is one of those instances where I'm not really sure how it ever works without failing. I'll have a PR up soon
