### ISSUE TITLE
Order metrics by timestamp for outputs.opentelemetry

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13233]
### Use Case

Similiar to https://github.com/influxdata/telegraf/pull/12994

If metrics are sent out of order after they're buffered they're rejected and can cause the agent problems. Let me know if you need more than that, as it's basically the same problem we have with stackdriver that @powersj has appeared to solved for. 

### Expected behavior

Network interruption, metrics buffer, metrics are sent in order by timestamp.

### Actual behavior

Network interruption, metrics buffer, metrics are sent out of order by timestamp.

Issue created per @powersj

**Comment by powersj** [comment]
@crflanigan I have put up https://github.com/influxdata/telegraf/pull/13292 which has very similar logic to the fix in stackdriver. Can you do the following:

1) provide logs (you can send them privately if you don't want them public) showing the issue with telegraf
2) try the artifacts in #13292 and see if the issue is resolved

Thanks!

**Comment by powersj** [comment]
> I will reach back out about this once they have their new release ready for testing.

Awesome thanks for trying out the PR! Let me know what you hear back

**Comment by powersj** [comment]
@crflanigan did you ever hear anything further? I'm curious as to what we should do with the PR

**Comment by crflanigan** [comment]
Hi Josh,

We haven't been able to test it yet as Google just finished adding the PR
into their next release.
We are however using the Open Telemetry output plugin to send from Telegraf
agent to Telegraf server in case we end up needing to send metrics to the
Telegraf server from an open telemetry source.

We could probably test this PR in our agent to server testing, @JonWalz2
what do you think?

**Comment by crflanigan** [comment]
Hey @powersj ,

I just tried to download the binaries, but they may have aged out because when I click on the link to download it gives me a `{"message":"not found"}` error page.

**Comment by powersj** [comment]
ha! I'll close and re-open this.

**Comment by powersj** [comment]
ok I've closed and re-opened the PR. Tests are re-running and should upload new artifacts in 20-30mins.

**Comment by crflanigan** [comment]
Hey buddy,
Looks like the tests ran but no binaries were generated.

**Comment by powersj** [comment]
@crflanigan fixed, sorry for the delay

**Comment by crflanigan** [comment]
Will endevour to test today.

**Comment by crflanigan** [comment]
Was tied up all day long. Hoping to test tomorrow.

**Comment by crflanigan** [comment]
We tested this a little today and it seems to be working correctly. We are going to test buffering up the metrics and will let you know.

**Comment by powersj** [comment]
Thanks for the feedback here as well! I might hold off on getting a final review of this one until hearing back again. I feel confident about this one, but would love all the additional testing you can do.

**Comment by crflanigan** [comment]
Hey buddy,

We just buffered for one hour and got the buffer to 3,602 points, and it worked great!

We are going to buffer for 12 hours and let you know.

**Comment by powersj** [comment]
Thanks again for the test and confirmation!
