### ISSUE TITLE
Deprecate protocol stats in net input plugin

### ISSUE THREAD

**Issue by dpward** [influxdata/telegraf#13248]
#382 adjusted the `net` input plugin to obtain protocol statistics, by reading `/proc/net/snmp`. This is only possible under Linux, and the data is completely orthogonal to everything else that the `net` plugin collects (none of the same fields are used in the measurements, and it is not keyed by network interface). The documentation says this behavior is available "for the time being", and it can be disabled with the configuration option `ignore_protocol_stats = true`.

The `nstat` plugin (#1104) was introduced shortly afterwards. It not only collects the same data from `/proc/net/snmp`, but also the data in `/proc/net/snmp6` and `/proc/net/netstat`. It also lists the resulting metrics in its documentation.

I believe the `net` plugin should deprecate (and eventually remove) protocol statistics collection, by making `ignore_protocol_stats = true` the default and adjusting the documentation to discourage its use. This will simplify its behavior and greatly reduce the amount of data it produces by default.

**Comment by Hipska** [comment]
Changing the default behaviour can become difficult to convince the maintainers, but it definitely makes sense to add depreciation notices as there is a working alternative..

**Comment by powersj** [comment]
+1 to deprecation notice to at least start

next steps: add deprecation to the config option
