### ISSUE TITLE
Filecount-Plugin - Don't follow File-Symlinks

### ISSUE THREAD

**Issue by dziebart** [influxdata/telegraf#13250]
### Use Case

Currently, if you want to monitor the sizes of certain directories, you would be best to use the Filecount-Plugin.

Directories, which are symlinks, and should not be considered can be excluded via `follow_symlinks = false`.

Consider following situation:

```
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-a.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-b.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-c.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-d.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-e.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-app-f.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-cch-a.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
lrwxrwxrwx 1 root root         36 Sep 27  2022 ubuntu-22.04-minimal-cch-b.tgz -> disks-ubuntu-22.04-minimal-srv-a.tgz
-rw-r--r-x 1 root root  800161942 Jan  3 13:52 disks-ubuntu-22.04-minimal-srv-a.tgz
```

This will result in the file `disks-ubuntu-22.04-minimal-srv-a.tgz` being counted 9 times.

### Expected behavior

Using a dedicated config-setting (e.g. `follow_file_symlinks = false`), one should be able to stop telegraf following file-symlinks to determine the amount of bytes occupied in the target directory.

### Actual behavior

There is currently no way to prevent this.

### Additional info

Telegraf-metric:
```
1683537101000000000 57440 /home/test    devstack 608295075691
```
Actual size:
```
# du -sh /home/test/
233G /home/test
```

**Comment by powersj** [comment]
Hi,

This seems like a reasonable request to add while walking a directory. 

However, I expect the regular only setting would have ignored symlink files since they have a symlink mode set, but apparently that is not the case. This makes me think this is actually a bug. The reported mode setting for the files is not showing up as symlinks during traversal.
