### ISSUE TITLE
Error 400 Bad Request vSphere & Invalid Slack Link

### ISSUE THREAD

**Issue by l3nnartt** [influxdata/telegraf#13266]
### Please direct all support questsions to slack or the forums. Thank you.

Hey, the slack link is invalid!
I have the following error, i use the defaults from [this readme](https://github.com/influxdata/telegraf/blob/release-1.26/plugins/inputs/vsphere/README.md#configuration).
thanks in advance! :)
```
2023-05-11T10:15:46Z I! [inputs.vsphere] Starting plugin
2023-05-11T10:15:46Z D! [inputs.vsphere] Creating client: xxxx.xxxxxx.xxxx
2023-05-11T10:15:46Z E! [telegraf] Error running agent: starting input inputs.vsphere: POST "/": 400 Bad Request
```

**Comment by l3nnartt** [comment]
![image](https://github.com/influxdata/telegraf/assets/69513317/a714154f-9634-4894-b3d7-f15ef66e547b)

**Comment by l3nnartt** [comment]
Hey! The Slack Link seems now working right, thx!
On windows the same telegraf configuration works right, so i didnt delve further with the problem.

**Comment by powersj** [comment]
> Hey! The Slack Link seems now working right, thx!

excellent - thanks for confirming

> On windows the same telegraf configuration works right, so i didnt delve further with the problem.

ok - then I think I will close this, but if you do have further issues feel free to hit us up on slack or the forums!
