### ISSUE TITLE
the `xpath_json` parser is not documented in the influx documentation page

### ISSUE THREAD

**Issue by memetb** [influxdata/telegraf#13263]
### Use Case

When going to https://docs.influxdata.com/telegraf/v1.14/data_formats/, there is no mention of xpath_json, which is actually a useful parser for certain use cases (c.f. https://community.influxdata.com/t/json-v2-array-of-objects-parsing-with-mqtt-consumer/29325)

### Expected behavior

Expected behaviour is that the docs should link to the already existing documentation, which can be found here https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath

### Actual behavior

Documentation does not list xpath_json as an input data format.

**Comment by powersj** [comment]
Hi,

Can you please go file an issue in the docs repo to get that added please? Here is a direct link:

https://github.com/influxdata/docs-v2/issues/new?body=_Describe%20the%20issue%20here._%0a%0a%23%23%23%23%23%20Relevant%20URLs%0a-%20https://docs.influxdata.com/telegraf/v1.26/data_formats/input/%0a-%20_Provide%20other%20relevant%20URLs%20%28project%20issues,%20community%20threads,%20etc.%29_%0a

Thanks!
