### ISSUE TITLE
RPM GPG issue when upgrading the package

### ISSUE THREAD

**Issue by SpiderD555** [influxdata/telegraf#13274]
### Relevant telegraf.conf

```toml
Not applicable
```

### Logs from Telegraf

```text
Not applicable
```

### System info

RHEL 8.7, Telegraf 1.25.2, x86_64

### Steps to reproduce

1. Install recent version of Telegraf (but not the latest one) with yum localinstall (for example [this one](https://dl.influxdata.com/telegraf/releases/telegraf-1.25.2-1.x86_64.rpm))
2. Add yum repository as [per your guide](https://www.influxdata.com/blog/linux-package-signing-key-rotation/)
3. Try to upgrade telegraf

### Expected behavior

yum installs latest version

### Actual behavior

yum fetches the old gpg key (the one that starts with 05CE 1508) and then fails to upgrade to the latest package version due to GPG key mismatch

### Additional info

I am not an expert on yum nor packaging, but it looks to me that your rpm release has a hardcoded reference to the old GPG key

**Comment by powersj** [comment]
Hi,

> the one that starts with 05CE 1508

That key is no longer used in signing packages. Can you provide some logs showing what you are seeing please? Can you also ensure that you have also updated to the latest key?

**Comment by SpiderD555** [comment]
It seems I had the Influxdata repository configured twice by mistake in /etc/yum.repos.d folder, and the one with old key took precedence. After renaming the wrong repository it all started to work. It seems the issue was on my side this time, sorry for taking your time.
