### ISSUE TITLE
azure_monitor plugin and 30-minutes limit while offline

### ISSUE THREAD

**Issue by alekmag** [influxdata/telegraf#13273]
### Relevant telegraf.conf

```toml
[[inputs.system]]
  name_override = "uptime"
  interval = "1m"
  fieldpass = ["uptime"]

[[outputs.azure_monitor]]
  namepass = ["uptime"]
  region = "$AZURE_REGION"
  resource_id = "$AZURE_RESOURCE_ID"
```

### Logs from Telegraf

```text
May 15 14:41:41 hostname telegraf[9020]: 2023-05-15T14:41:41Z D! [agent] Successfully connected to outputs.azure_monitor
May 15 14:41:41 hostname telegraf[9020]: 2023-05-15T14:41:41Z D! [agent] Starting service inputs
May 15 14:41:51 hostname telegraf[9020]: 2023-05-15T14:41:51Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:01 hostname telegraf[9020]: 2023-05-15T14:42:01Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:11 hostname telegraf[9020]: 2023-05-15T14:42:11Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:21 hostname telegraf[9020]: 2023-05-15T14:42:21Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:31 hostname telegraf[9020]: 2023-05-15T14:42:31Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:41 hostname telegraf[9020]: 2023-05-15T14:42:41Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:42:51 hostname telegraf[9020]: 2023-05-15T14:42:51Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:04 hostname telegraf[9020]: 2023-05-15T14:43:04Z D! [outputs.azure_monitor] Wrote batch of 1 metrics in 3.017613361s
May 15 14:43:04 hostname telegraf[9020]: 2023-05-15T14:43:04Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:11 hostname telegraf[9020]: 2023-05-15T14:43:11Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:21 hostname telegraf[9020]: 2023-05-15T14:43:21Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:31 hostname telegraf[9020]: 2023-05-15T14:43:31Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:41 hostname telegraf[9020]: 2023-05-15T14:43:41Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:43:51 hostname telegraf[9020]: 2023-05-15T14:43:51Z D! [outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
May 15 14:44:01 hostname telegraf[9020]: 2023-05-15T14:44:01Z D! [outputs.azure_monitor] Wrote batch of 1 metrics in 202.970441ms

... broken connection ...

May 15 14:44:15 hostname telegraf[9020]: 2023-05-15T14:44:15Z D! [outputs.azure_monitor] Buffer fullness: 1 / 10000 metrics
May 15 14:44:16 hostname telegraf[9020]: 2023-05-15T14:44:16Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westeurope.monitoring.azure.com/subscriptions/a1b2c3d4-f366-4320-8804-de34>
May 15 14:44:25 hostname telegraf[9020]: 2023-05-15T14:44:25Z D! [outputs.azure_monitor] Buffer fullness: 1 / 10000 metrics
May 15 14:44:26 hostname telegraf[9020]: 2023-05-15T14:44:26Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westeurope.monitoring.azure.com/subscriptions/a1b2c3d4-f366-4320-8804-de34>
...
May 15 14:45:15 hostname telegraf[9020]: 2023-05-15T14:45:15Z D! [outputs.azure_monitor] Buffer fullness: 2 / 10000 metrics
May 15 14:45:16 hostname telegraf[9020]: 2023-05-15T14:45:16Z E! [agent] Error writing to outputs.azure_monitor: Post "https://westeurope.monitoring.azure.com/subscriptions/a1b2c3d4-f366-4320-8804-de34>

... connection restored after > 30min ...

May 15 15:47:15 hostname telegraf[9020]: 2023-05-15T15:47:15Z D! [outputs.azure_monitor] Buffer fullness: 62 / 10000 metrics
May 15 15:47:16 hostname telegraf[9020]: 2023-05-15T15:47:16Z E! [agent] Error writing to outputs.azure_monitor: failed to write batch: [400] 400 Bad Request: {"error":{"code":"BadRequest","message":"'time' should not be older than 30 minutes and not more than 4 minutes in the future\r\n"}}
May 15 15:47:25 hostname telegraf[9020]: 2023-05-15T15:47:25Z D! [outputs.azure_monitor] Buffer fullness: 62 / 10000 metrics
May 15 15:47:26 hostname telegraf[9020]: 2023-05-15T15:47:26Z E! [agent] Error writing to outputs.azure_monitor: failed to write batch: [400] 400 Bad Request: {"error":{"code":"BadRequest","message":"'time' should not be older than 30 minutes and not more than 4 minutes in the future\r\n"}}
```

### System info

Telegraf 1.26.0 (git: HEAD@064650c8), Linux

### Steps to reproduce

1. start telegraf
2. block connection to Azure
3. wait more than 30 minutes (to exceed azure monitor limit)
4. restore connection

### Expected behavior

Old data is dropped (what I was expecting after spotting `Reset()` function in `azure_monitor.go `

### Actual behavior

Plugin is stuck on trying to send metrics which Azure considers outdated (returning 400). No data is transmitted to Azure anymore.

I'm looking into telegraf code for the first time but it may be some clue - it seems to me like cache in azure-monitor plugin is cleaned, but the old messages are still stored in telegraf buffer so are re-transmitted.

It is possible to avoid it setting `metric_buffer_limit` to value smaller than metrics gathered in 30m but it's quite "hacky" as we have some on-event metrics transmitted (and if limit is exceed after 30m the result is the same - I see 400-Errors to the end)

**Comment by powersj** [comment]
Hi,

Per [this overview page](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-custom-overview) they mention "Azure Monitor accepts metric data with timestamps as far as 20 minutes in the past and 5 minutes in the future." The difference in that statement and your error message make me a little uneasy with any hard-coded expiration values.

Let us talk this one over and think about a set of next steps.

**Comment by powersj** [comment]
next steps: work on way to parse the error message and when we get a message about data being too old or new, we toss the data.

**Comment by clowa** [comment]
Hi @powersj,
just want to let you now I'm facing the same error message too.

I was thinking if a further possible solution would be to simply limit the buffer size by the age of the metrics instead of or in addition to metrics count. With this solution it wouldn't be tied to a specific vendor or API response and maybe other could profit from this too - for example, simply set up the period of time that should be able to be bridged in the event of an internet failure or something else.
However, I'm not familiar with the code base and don't know how difficult this would be to implement - what do you think?

**Comment by powersj** [comment]
> what do you think?

Many outputs do not have the same limitation around the age of data. For example, influxdb, file, etc. by default do not care if the datapoint was in the 1970s or some date far in the future. Additionally, buffers are unique to each output. That way if only one output is offline other plugins continue to work as expected.

I would prefer we do this on a plugin-by-plugin basis. My preference is my stated next steps above, where we always try to send the data, and only if we get an error back do we toss the data.

**Comment by powersj** [comment]
@alekmag can you take a look and try the artifacts in https://github.com/influxdata/telegraf/pull/14185?

Thanks
