### ISSUE TITLE
VSphere - VSAN Metrics collection not working as expected

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#13283]
We have the below configuration for the vsan metrics collection as part of the vsphere input plugin.
IT return the error when running the test against the configuration

Error:
#-> telegraf --config vsan.conf --test
2023-05-18T09:36:13Z I! Loading config: vsan.conf
2023-05-18T09:36:13Z W! DeprecationWarning: Option "force_discover_on_init" of plugin "inputs.vsphere" deprecated since version 1.14.0 and will be removed in 2.0.0: option is ignored
2023-05-18T09:36:13Z W! DeprecationWarning: Option "force_discover_on_init" of plugin "inputs.vsphere" deprecated since version 1.14.0 and will be removed in 2.0.0: option is ignored
2023-05-18T09:36:13Z E! error loading config file vsan.conf: plugin inputs.vsphere: line 2: configuration specified the fields ["vsan_metric_include" "vsan_metric_exclude" "vsan_metric_skip_verify"], but they weren't used

Telegraf Version: #-> telegraf --version
Telegraf 1.26.2 (git: HEAD@a3a884a1)

Telegraf VSAN config:
#-> cat vsan.conf
## Realtime instance
[[inputs.vsphere]]
  interval = "30s"
  vcenters = [ "https://vpshere-host/sdk" ]
  username = "<User>
  password = '<password>'

  insecure_skip_verify = true
  force_discover_on_init = true

  # Exclude all other metrics
  vm_metric_exclude = ["*"]
  datastore_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]
  host_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]

  vsan_metric_include = [ "summary.*" ]
  vsan_metric_exclude = [ ]
  vsan_metric_skip_verify = false

  collect_concurrency = 5
  discover_concurrency = 5

# Historical instance
[[inputs.vsphere]]

  interval = "300s"
  vcenters = [ "https://vpshere-host/sdk" ]
  username = "<User>
  password = '<password>'

  insecure_skip_verify = true
  force_discover_on_init = true

  # Exclude all other metrics
  vm_metric_exclude = ["*"]
  datastore_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]
  host_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]

  vsan_metric_include = [ "performance.*" ]
  vsan_metric_exclude = [ ]
  vsan_metric_skip_verify = false

  collect_concurrency = 5
  discover_concurrency = 5

**Comment by powersj** [comment]
> Telegraf 1.26.2 (git: HEAD@a3a884a1)

vsan feature is not yet released. You need to either build from master or use one of the nightly builds. It will be released in an official build with 1.27.0 in June.

**Comment by vdudejon** [comment]
I'm using 1.27 but the vsan metrics don't seem to be working, I'm not seeing any metrics with 'vsan' in the name from telegraf

**Comment by jaymzmac** [comment]
Using 1.27.1 and also unable to see any vsan metrics. Created https://github.com/influxdata/telegraf/issues/13519 to track the issue.
