### ISSUE TITLE
[feature request] support jolokia bulk requests

### ISSUE THREAD

**Issue by caseylucas** [influxdata/telegraf#1328]
### Proposal:

It would be great if the jolokia plugin would pull JMX data via the jolokia bulk request https://jolokia.org/features/bulk-requests.html mechanism in order to reduce round trips to the JVM.
### Current behavior:

Jolokia plugin makes one HTTP request for every mbean.
### Desired behavior:

One request per JVM
### Use case:

With lots of JMX data collected per JVM, telegraph will need to machine gun the JVMs as it collects all of the stats.  Each mbean translates into a separate HTTP requests.  With bulk requests, the multiple HTTP requests could be reduced to one.

**Comment by bodsch** [comment]
+1

**Comment by phemmer** [comment]
PR is up for this over at #2253
In my use case it's about 260 times faster.
