### ISSUE TITLE
Directory for statefile deployment via package management

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13290]
### Use Case

My deployment department installs the telegraf package for me (because I am not root)
I want to use the statefile, but don't have write permissions anywhere fitting and have to use `/tmp`, as I may only administrate telegraf itself and its config.

### Expected behavior

I can use `/var/lib/telegraf` to store my statefile

### Actual behavior

I can't write the statefile anywhere but `/tmp` or `/etc/telegraf` which both is not fitting

### Additional info

proposed solution:
Have the telegraf package (rpm, deb) create `/var/lib/telegraf` for this, as it would be the natural place to store the statefile.

additional idea:
Add
`# statefile = /var/lib/telegraf/statefile`
to default config to guide user to use this directory

additional² idea:
Add
`statefile = /var/lib/telegraf/statefile`
to default config, so that stateful plugins automatically preserve their state from day one. (because why not?)

**Comment by powersj** [comment]
> I can't write the statefile anywhere but /tmp or /etc/telegraf which both is not fitting
> Have the telegraf package (rpm, deb) create /var/lib/telegraf for this, as it would be the natural place to store the statefile.

I can understand `/tmp`, but how do you have access to `/etc/telegraf` without root access? That should be owned by `root:root`. I ask because in general it looks like the files under `/var/lib/` are also `root:root`, which would be the same problem, right?

> Add
statefile = /var/lib/telegraf/statefile
to default config, so that stateful plugins automatically preserve their state from day one. (because why not?)

While I can understand the idea, this is an opt-in piece of functionality that we do not want to force or have a bunch of folks start using.

**Comment by knollet** [comment]
> I can understand `/tmp`, but how do you have access to `/etc/telegraf` without root access? That should be owned by `root:root`. I ask because in general it looks like the files under `/var/lib/` are also `root:root`, which would be the same problem, right?

You're right about `/etc/telegraf`.
You're not right about `/var/lib/telegraf`. 
According to the FHS (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) /var/lib/* is for 
> State information. Persistent data modified by programs as they run (e.g., databases, packaging system metadata, etc.). 

There are many `root:root` directories, e.g. rpm is `root:root`, but rpm will be exclusively run as root, so no problem there.
Services which don't run as root have write permissions:
postfix, setroubleshoot, unbound, mlocate(slocate-user), chrony, etc.
`/var/lib/*` is explicitly for this purpose.

See also:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html

>State information is generally used to preserve the condition of an application (or a group of inter-related applications) between invocations and between different instances of the same application. State information should generally remain valid after a reboot, should not be logging output, and should not be spooled data.
>
> An application (or a group of inter-related applications) must use a subdirectory of /var/lib for its data. There is one required subdirectory, /var/lib/misc, which is intended for state files that don't need a subdirectory; the other subdirectories should only be present if the application in question is included in the distribution. [[41]](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html#ftn.idm236090984800)


--- 
> While I can understand the idea, this is an opt-in piece of functionality that we do not want to force or have a bunch of folks start using.

That's ok. I am only really interested in getting this directory. The rest is just cosmetics :)

**Comment by powersj** [comment]
> You're right about /etc/telegraf.

You didn't answer how you are using /etc/telegraf ;)

> So, the /var/lib/telegraf would have to be assigned to the telegraf user, of course.

The proposal then is to create the `/var/lib/telegraf` directory owned by `telegraf:telegraf` and with 755 permissions during package install/upgrade if it does not already exist? I'll want a +1 from @jdstrand before if this is accurate.

**Comment by knollet** [comment]
> You didn't answer how you are using /etc/telegraf ;)
It's not overwritten by package updates and we changed the permissions for our deployment. It's not relevant for this. Just disregard.

**Comment by jdstrand** [comment]
Automatically creating `/var/lib/telegraf` for use with `statefile` makes sense to me.

The [docs](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) say this about `statefile`: "_Name of the file to load the states of plugins from and store the states to. If uncommented and not empty, this file will be used to save the state of stateful plugins on termination of Telegraf. If the file exists on start, the state in the file will be restored for the plugins._" I'm not sure what would typically be in the statefile for telegraf, but to err on the safe side, I recommend `telegraf:telegraf` 0700. `root:telegraf` 0770 would also be ok, but please don't use 0755 or 0775 (or anything with 'other' permissions).

Unrelated to security, while I think it is fine to create the directory on install, I suggest not changing the default for `statefile` and continue to make it opt-in (though feel free to document `/var/lib/telegraf` in the configuration). I suspect doing it this way will ease upgrades. I defer to @powersj on this point.

**Comment by powersj** [comment]
@jdstrand thank you for the response! I have put up https://github.com/influxdata/telegraf/pull/13306 with updates to the RPM and DEB post installs to create the folder and the file.
