### ISSUE TITLE
Improve API Compatibility in Cloudwatch Stream Input Plugin

### ISSUE THREAD

**Issue by khurramcheema** [influxdata/telegraf#13298]
### Use Case

We recently migrated from the Clouwtach API plugin to the Clouwatch Stream plugin. We also enabled the option `api_compatability,` but we didn't get the same structure of measurements in influx.

When we use Cloudwatch API-based input plugin, it looks like 
`cloudwatch_aws_elb,load_balancer_name=p-example,region=us-east-1 latency_average=0.004810798017284538,latency_maximum=0.1100282669067383,latency_minimum=0.0006084442138671875,latency_sample_count=4029,latency_sum=19.382705211639404 1459542420000000000`

When we use Cloudwatch Stream-based input plugin with `api_compatability=true`
`aws_elb_latency,load_balancer_name=p-example,region=us-east-1 average=0.004810798017284538,maximum=0.1100282669067383,minimum=0.0006084442138671875,samplecount=4029,sum=19.382705211639404 1459542420000000000`

Note the name of the measurement in both cases; this breaks all the Kapacitor alerts and Grafana dashboards.

Task:
- Improve the Cloudwatch Stream Plugin so that when api_compatability is set to true, it creates the same structure as with the API-based plugin.

### Expected behavior

When `api_compatability` is set to true, we should get the exact structure as with Cloudwatch-api based input plugin.

### Actual behavior

We are getting a different structure with the new plugin

**Comment by powersj** [comment]
Hi,

> When api_compatability is set to true, we should get the exact structure as with Cloudwatch-api based input plugin.

The first time I read the comment in the readme I thought "These fields are optionally renamed to match the CloudWatch API for easier transition from the API to Metric Streams." was not in reference to the other telegraf cloudwatch plugin. 

I assume your reading of this statement means that this setting should keep the field values between the telegraf cloudwatch and cloudwatch_metric_streams identical?

I see you also put up a PR with a fix, but not against our repo. Is that something you want to put up?

Thanks!

**Comment by khurramcheema** [comment]
@powersj yes, that was my understanding, and if we have to switch from telegraf cloudwatch to cloudwatch_metric_streams, the transitions are not smooth; it breaks everything (alerts, grafna etc) as the structure changes. There is some issue, which might be related to this change, I'll add to telegraf master once we fix that

**Comment by powersj** [comment]
> There is some issue, which might be related to this change, I'll add to telegraf master once we fix that

Were you going to put that PR up soon?

**Comment by khurramcheema** [comment]
yes soon, the next week

**Comment by powersj** [comment]
@khurramcheema did you mean to close this issue? Or were you going to put up a PR?
