### ISSUE TITLE
Improve outputs.stackdriver to better support GMP use case

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13303]
### Use Case

The idea would be that we could modify the stackdriver plugin to support GMP requirements, like sending metrics with type defined (gauge or counter), sent as a double (float64 I think is the compatible data type), etc. But it will likely need to be an option that needs to be enabled so that it doesn’t change the way stackdriver legacy users have their metrics emitted. Probably something like maybe an extra config option in the plugin config which defaults to legacy but can be set to send as GMP.

The following requirements from Google are needed at a minimum:

The API endpoint should be configurable as configured in this [PR](https://github.com/influxdata/telegraf/pull/13168).

Metrics must have a KIND set and the metric prefix should be suffixed with gauge-kind metrics ending in /gauge, cumulative-type metrics must end in /counter, and histogram-type metrics must end in /histogram.

Example:
prometheus/tempodb_backend_bytes_total/gauge
 
The metric value should be of type float64. Currently metrics coming in are in int64. Unfortunately int64 metrics can't be queried using PromQL in GMP.
 
GMP only officially supports having two forward slashes (and no more), the “prometheus.googleapis.com/” part that seperates the metric, and the part that sets the metric as a gauge or counter. Currently there are more than two as shown below:

<img width="698" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/edaf59b8-f649-4316-9e18-64cfd94ecf5f">

### Expected behavior

Metrics would come in through the correct API endpoint, with the correct amount of forward slashes, with the Kind set to the proper metric type, with a data type of float64.

### Actual behavior

The inverse of above.

### Additional info
Issue created per @powersj 
_No response_

**Comment by powersj** [comment]
Thank you for the issue!

next steps: work through the various requests and config options to enable these:

- Metrics must have a KIND set - we can set this to gauge today. Technically the readme says this does not support histogram or delta metrics
- The metric value should be of type float64
- GMP only officially supports having two forward slashes: looks like today we do [a path join](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/stackdriver/stackdriver.go#LL211C26-L211C42) to build the name. We could switch this to a string join with an `_` for example.

As mentioned all of this will need to be behind an option(s). My initial thought is to have a single option for gmp_compatability which would do the above, but I need to get back into the code and see what we can do.

**Comment by powersj** [comment]
Hi,

I have put up PR #13454. It adds two more options that if you set as follows:

`metric_name_format = "official"`
`metric_data_type = "float64"`

It allows you to send metrics in the above format, with the kind appended, and finally forces items as Go's int64/Google cloud's double value.

Can you please give the artifacts a try?

Thanks!

**Comment by crflanigan** [comment]
Hey buddy,
This looks good to me as I have communicated with you over email.

I've asked Google to comment but they said at first glance it looks good, and I'm able to find the metrics in GMP.
