### ISSUE TITLE
[[inputs.temp]] fails on warning error

### ISSUE THREAD

**Issue by jbardy33** [influxdata/telegraf#13308]
### Relevant telegraf.conf

```toml
[[inputs.temp]]
# no configuration
```

### Logs from Telegraf

```text
[inputs.temp] Error in plugin: error getting temperatures info: Number of warnings: 2
```

### System info

Telegraf 1.26.1 (git: HEAD@8f421f25)

### Steps to reproduce

1. add [[inputs.temp]] to a system which will potentially throw a warning error
...

### Expected behavior

warning should be ignored and temp info should be sent to influxDB

### Actual behavior

no temp info is sent

### Additional info

running on rocky linux 8, please let me know if any additional issue is needed.

**Comment by powersj** [comment]
Thanks for the quick bug report!

next steps: get confirmation that the artifacts in #13307 ensure the warnings are gone and only errors are returned
