### ISSUE TITLE
Fail to run telegraf

### ISSUE THREAD

**Issue by panhouxu** [influxdata/telegraf#13318]
- run command 'telegraf.exe --config telegraf.conf' would encounter following error. 

![image](https://github.com/influxdata/telegraf/assets/26575569/b5904dbe-ebb4-4d27-9c50-b43af140f887)

- Telegraf verson: v1.26.3
- partial content of the configure file.
![image](https://github.com/influxdata/telegraf/assets/26575569/1f460a82-e95a-4c1b-ab80-7e1e8b9f936a)

**Comment by srebhan** [comment]
Are you sure your editor has `C:\Program Files(x86)\InfluxData\telegraf\telegraf.conf`?

**Comment by powersj** [comment]
The line numbers can be off at times in error messages. You need to search your document for `use_sudo` and see where it shows up. Ultimately, this is about finding where that line is and commenting it out as you are on Windows.
