### ISSUE TITLE
telegraf 0.13.1 -> influx 0.13.0 database creation error

### ISSUE THREAD

**Issue by ScubaDrew** [influxdata/telegraf#1331]
I am trying to get telegraf 0.13.1 to log to an influxdb 0.13.0

```
2016/06/04 02:11:30 Output [influxdb] buffer fullness: 123 / 10000 metrics. Total gathered metrics: 123. Total dropped metrics: 0.
2016/06/04 02:11:30 Database creation failed: json: cannot unmarshal number into Go value of type client.Response
2016/06/04 02:11:30 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```

I've checked connectivity and permissions many times. Seems to be fine.

```
[[outputs.influxdb]]
  urls = ["http://172.20.0.166:30084"] # required
  database = "telegraf" # required
  precision = "s"
  retention_policy = "default"
  write_consistency = "any"
  timeout = "5s"
  username = "test"
  password = "test"
```

I've searched and do not see anything related to this json unmarshal number into go value of type client.Response 

Thanks for any help,
Drew

**Comment by sparrc** [comment]
can you run the create database command using `curl` and show me the result?

```
curl -GET 'http://172.20.0.166:30084/query?pretty=true' --data-urlencode "q=CREATE DATABASE telegraf"
```

**Comment by ScubaDrew** [comment]
Hey @sparrc -- thanks for the reply.

Here is what I get:

`404 page not found`

If I run `curl http://172.20.0.166:30084`

The response is:

`<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>InfluxDB - Admin Interface</title>

    
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/dropdowns-enhancement.css" rel="stylesheet">
    <link href="css/admin.css" rel="stylesheet">`

so it appears I have a working connection.

**Comment by sparrc** [comment]
No problem, it sounds like the InfluxDB client should also be checking the response code before it tries to marshal the response message to json as well, that error message is not very helpful.

**Comment by juldou** [comment]
Whenever I type this, but with my domain and port 8086, the terminal is just waiting and nothing happens. 
Notice that I have telegraf on another server as influxdb. I also have telegraf and influxdb in docker container. 

curl -GET 'http://172.20.0.166:30084/query?pretty=true' --data-urlencode "q=CREATE DATABASE telegraf"

where can be problem?

**Comment by danielnelson** [comment]
@juldou My guess is that port is being blocked by a firewall, but please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
