### ISSUE TITLE
[feature request] JSON Parser, add more flexibility to define Tags & Metrics

### ISSUE THREAD

**Issue by dgarros** [influxdata/telegraf#1332]
### Proposal:
Today, the JSON parser have some strong assumptions on how the data should looks like. 
Metric must be "integer" and all tag_keys must be statically defined.  
These assumptions are not working in many cases and require the format of the data to be known in advance. 

### Desired behavior:
It would be great to have a more flexible system
Here are some form of flexibility I'm thinking about : 
- 1/ define the name of the Metrics and consider that everything else is a Tag
- 2/ Consider all "strings" tags and all "integer/float" metrics
I can see use cases for both

### Use case: 
Anything where the format of the data is a little dynamic,
Also even if the format is known in advance, the less hardcoded information on telegraf's configuration the better. Otherwise each change in the data format require a change of configuration.

**Comment by sparrc** [comment]
closing in favor of https://github.com/influxdata/telegraf/issues/1363
