### ISSUE TITLE
How to write output in separate file for each snmp trap port

### ISSUE THREAD

**Issue by rafeeqsid** [influxdata/telegraf#13323]
### Please direct all support questsions to slack or the forums. Thank you.

How to write in output separate file for each snmp trap port.whether it is possible or not?

[[inputs.snmp_trap]]
  service_address = "udp://:162"
  service_address = "udp://:25001"
  service_address = "udp://:25002"
  service_address = "udp://:25003"

[[outputs.file]]
  
  files = ["stdout", "/tmp/metrics.out"]   ## This is default settings

Eg:-
  /tmp/metrics-162.out
  /tmp/metrics-25001.out
  /tmp/metrics-25002.out
  /tmp/metrics-25003.out

**Comment by powersj** [comment]
This was answered in slack, but essentially you would want to put each snmp_trap in a unique input. Tag each metric coming out of that input. Create a separate output for each trap and then use `tagpass` to only allow metrics with a specific tag to go there.

Closing as this is not an issue but a question.
