### ISSUE TITLE
Chore relating to  docs: Indicate secret-store support #12592 

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13328]
### Use Case

I didn't know the `@{syntax}` was only limited to certain fields in certain plugins until I stumbled upon this PR #12592.

### Expected behavior

You could document in the secretstore documentation (where it is explained how the `@{syntax}` works), that it only works where explicitly advertised. (and can't for example be used as a tag on a random metric, or somesuch)

### Actual behavior

When `@{this}` doesn't work and an authentication fails, it's hard to realize why, because the docs of plugins not supporting `@{this}` don't tell me about it. It doesn't error out, either. It just uses the unresolved `@{string}` as a password and fails with that.

**Comment by srebhan** [comment]
@knollet I would appreciate a PR that fixes the documentation... :-)
