### ISSUE TITLE
Telegraf Directory Monitoring to monitor for new Telegraf Config. files

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [influxdata/telegraf#13331]
Can I use the directory_monitoring input plugin of telegraf to monitor the telegraf.d directory so that, when I add new configuration file to telegraf, it get's picked up automatically without needing to restart telegraf? 
I am really trying to achieve this flow but facing errors and I wanted to know whether this is even possible or no, if someone could help.

**Comment by powersj** [comment]
Answered on the forums, so closing. In short you can use the `--watch-config` along with the `--config-directory` CLI options.

**Comment by Sir-gits-a-lot** [comment]
I need the answer to this specific issue whether it can happen through directory_monitoring input plugin because --watch-config will indeed restart telegraf which is something that I don't want as that will give wrong info. the system monitoring telegraf as a service.
Can you help me with the directory_monitoring input plugin doubt itself? 
I have actually tried the --watch-config flag that was something I was using all this while. Now only, I need to change the approach due to the restart (SIG HUP) signal mechanism --watch-config employs.

**Comment by powersj** [comment]
Telegraf does not live reload configs. It needs the sighup. Directory monitor is not an option.
