### ISSUE TITLE
Allow boolean flags to be not case sensitive

### ISSUE THREAD

**Issue by jheinitz** [influxdata/telegraf#13343]
### Use Case

Hello!

I'm talking about version 1.26.3, but I think it is valid also for older versions. I'm deploying my telegraf instances through ansible. When I have a template that sets the `debug` variable in `telegraf.conf`, I use something like `{{ telegraf.debug_flag | default(false) }}`. Even if I specify `false`, Ansible would change it to either `False` or ` True`. But with `True` or `False` I get an error that the TOML syntax is invalid and the telegraf process stopps with an error. 

I know that I can handle it in Ansible, but wouldn't it be better to allow either `false`, `False` or `FALSE` to be valid options for boolean flags?

Thanks and best regards

Jens

### Expected behavior

Allow Telegraf to run with `debug = False`

### Actual behavior

Telegraf does not start with `debug = False`. It must be written as `debug = false`.

**Comment by jheinitz** [comment]
Hi!

I was not aware that the TOML specs are like that. But that makes perfectly sense to me now. I will stick with the `lower` function in Ansible than. 

All the best and thanks for your quick reply. Have a nice weekend.

BR Jens

**Comment by powersj** [comment]
> Have a nice weekend.

Thanks - You as well!
