### ISSUE TITLE
Handle PEN messages correctly

### ISSUE THREAD

**Issue by vknyazhev** [influxdata/telegraf#13353]
### Use Case

 Error processing IPFIX messages using telegraf [[inputs.netflow]] #13305. The question of interpreting the content of IPFIX messages with PEN fields remains open.

### Expected behavior

When receiving IPFIX messages containing PEN numbers are not interpreted as ntop fields with the corresponding content

### Actual behavior

When receiving IPFIX messages containing PEN numbers are not interpreted as 
ntop fields with the corresponding content[IPFIXCGS.pcap.txt](https://github.com/influxdata/telegraf/files/11579148/IPFIXCGS.pcap.txt)

**Comment by powersj** [comment]
@srebhan assigning to you since you were already looking at this.

**Comment by srebhan** [comment]
@vknyazhev please check the binary in PR #13360 once CI finished the build/tests. For testing, please download the [ntop mapping file](https://raw.githubusercontent.com/influxdata/telegraf/d9b0ce8556dee602147d6f71b35c8f0a6098681b/plugins/inputs/netflow/mappings_netflow/ntop.csv) from the PR and use

```toml
[[inputs.netflow]]
  service_address = "udp://:2055"
  private_enterprise_number_files = ["ntop-35632.csv"]
```
