### ISSUE TITLE
ping plugin is broken after introducing CombinedOutputTimeout for exec command runners

### ISSUE THREAD

**Issue by alekiv** [influxdata/telegraf#1335]
## Bug report
Looks like after implementing CombinedOutputTimeout for exec command runners ping command got killed before it timeouts internally.
 
### System info:
telegraf v0.13.1
OS: Debian Jessie
192.168.101.6 destination is not accessible for pings
 
### Steps to reproduce:
Configure ping plugin as follows:

[[inputs.ping]]
  ## NOTE: this plugin forks the ping command. You may need to set capabilities
  ## via setcap cap_net_raw+p /bin/ping
  ## urls to ping
  urls = [ "192.168.101.6" ]# required
  ## number of pings to send (ping -c <COUNT>)
  count = 5 # required
  ## interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
  ping_interval = 0.0
  ## ping timeout, in s. 0 == no timeout (ping -t <TIMEOUT>)
  timeout = 5.0
  ## interface to send ping from (ping -I <INTERFACE>)
  #interface = ""

### Expected behavior:
ping plugin detects that 192.168.101.6 is not accessible and sends data to influxdb

### Actual behavior:
telegraf kills plugin due to internal timeout, which probably equals with timout configured under plugin settings and doesn't take into account number of pings (eg. count = 5)
telegraf log:
Fatal error processing ping output
, Command timed out.

After ping count change from 5 to 1, telegraf doesn't kill ping exec by timeout.

**Comment by sparrc** [comment]
yep, see pr #1305
