### ISSUE TITLE
Unsupported input type for mean aggregate: string - Telegraf MQTT

### ISSUE THREAD

**Issue by s4en** [influxdata/telegraf#13354]
I've connect Telegraf with InfluxDB and everything works when i start
`telegraf --config http://192.168.XXX.XXX:XXXX/api/v2/telegrafs/XXXXXXXX`
I see the data.

When i try to use the Data Explorer to show some graph i got an Error:

> unsupported input type for mean aggregate: string

So the Script Editor looks like this

```
from(bucket: "mqtt_consumer")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["_measurement"] == "mqtt_consumer")
  |> filter(fn: (r) => r["host"] == "influxdb")
  |> filter(fn: (r) => r["topic"] == "inverter/total/YieldDay")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```
In the mqtt config is use:
`data_format = "influx"`

**Comment by srebhan** [comment]
@s4ren, the error indicates that the field `value` you are trying to graph has **string** (i.e. text) values. This might be due to a missing conversion in Telegraf when parsing the data. It would be helpful to see a message of your MQTT topic filling that field and your corresponding config...
