### ISSUE TITLE
Prometheus plugin: incorrect counter retrieval for summary and histogram types

### ISSUE THREAD

**Issue by tobischo** [influxdata/telegraf#1336]
### System info:
Telegraf 0.13.1

### Steps to reproduce:

1. Setup a service with prometheus /metrics endpoint
2. Load data metrics endpoint of that service

### Expected behavior:
When parsing the output anything with a `_count` should be properly parsed into the count field of the `telegraf.Metric`

### Actual behavior:
The count value stays 0 and is sent with 0 in every dataset.
e.g.
```
http_request_duration_seconds,code=200,host=localhost,method=get,path=/metrics,url=http://localhost:4007/metrics 0.5=0.003071558,0.9=0.003609577,0.99=0.003609577,count=0,sum=0.009393333 1465218854910415916
```
### Additional info:
There are actually tests for this, but they test it in the same wrong way, namely by expecting 0.
See for test data: https://github.com/influxdata/telegraf/blob/bac1c223deb42119117852c5866ffa0de42659f5/plugins/inputs/prometheus/parser_test.go#L31
See for (invalid) expectation: https://github.com/influxdata/telegraf/blob/bac1c223deb42119117852c5866ffa0de42659f5/plugins/inputs/prometheus/parser_test.go#L141

The issue appears to be caused by selecting the wrong prometheus metrics type when filling the `telegraf.Metric`

See https://github.com/influxdata/telegraf/blob/bac1c223deb42119117852c5866ffa0de42659f5/plugins/inputs/prometheus/parser.go#L77 where actually the wrong type is selected for count but not for sum.

**Comment by sparrc** [comment]
closed by #1337
