### ISSUE TITLE
Remove deprecated and ignored options for v1.30.0

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#13374]
### Use Case

Remove deprecated options that are ignored since some time.

related to #13351 

### Expected behavior

Options gone.

### Actual behavior

Options there.

### Additional info

The following options are affected
- [ ] `flush_buffer_when_full` in `agent` section (see `config/config.go`)
- [ ] `metric_buffer` in `inputs.mqtt_consumer`
- [ ] `metric_buffer` in `inputs.nats_consumer`

**Comment by powersj** [comment]
Next steps: as v1.30 will be in March 2024, then after new years 2024, circle around to this and removes these

**Comment by srebhan** [comment]
Moved items into #13375 to reduce information scattering...
