### ISSUE TITLE
Remove deprecated options for v1.30.0

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#13375]
### Use Case

Remove deprecated options that are replaced by others since some time.

related to https://github.com/influxdata/telegraf/pull/13351

### Expected behavior

Options should be removed. If possible a way to migrate configs containing those options should be provided.

### Actual behavior

Options there.

### Additional info

The following options are affected
- [x] `inputs.disk`: `mountpoints` replaced by `mount_points`
 #14141
 #14913
- [x] `inputs.mqtt_consumer`: `metric_buffer` is ignored
 #14233
 #14914
- [x] `inputs.nats_consumer`: `metric_buffer` is ignored
 #14234
 #14915
- [x] ~~`inputs.statsd`: `convert_names` replaced by `metric_separator`~~ *Removed deprecation*
- [x] `outputs.influxdb`. `url` replaced by `urls`
 #14341
 #14916

**Comment by powersj** [comment]
Next steps: as v1.30 will be in March 2024, then after new years 2024, circle around to this and removes these
