### ISSUE TITLE
Remove deprecated plugins for v1.30.0

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#13376]
### Use Case

Remove deprecated plugins that are replaced by newer ones since some time.

related to #13351

### Expected behavior

Plugins should be removed. If possible a way to migrate configs containing those plugins should be provided.

### Actual behavior

Plugins there.

### Additional info

The following plugins are affected
- [x] `inputs.cassandra` replaced by `inputs.inputs.jolokia2`
 #13377
 #14859
- [x] `inputs.httpjson` replaced by `inputs.http`
 #13532
 #14860
- [x] `inputs.io` replaced by `inputs.diskio`
 #13536
 #14861
- [x] `inputs.jolokia` replaced by `inputs.jolokia2`
 #14114
 #14862
- [x] `inputs.kafka_consumer_legacy` replaced by `inputs.kafka_consumer`
 #14122 
 *Note: This plugin requires manual migration!*
 #14863
- [x] `inputs.snmp_legacy` replaced by `inputs.snmp`
 #14123 
  *Note: This plugin requires manual migration!*
 #14864
- [x] `inputs.tcp_listener` replaced by `inputs.socket_listener`
 #14119
 #14865
- [x] `inputs.udp_listener` replaced by `inputs.socket_listener`
 #14120
 #14866
- [x] `outputs.riemann_legacy` replaced by `outputs.riemann`
 #14121 
 #14867

**Comment by powersj** [comment]
Next steps: as v1.30 will be in March 2024, then after new years 2024, circle around to this and removes these

**Comment by Hipska** [comment]
Maybe a good idea to start working with GitHub milestones again for these kind of tasks?
