### ISSUE TITLE
New Intel Baseband Accelerator Input Plugin

### ISSUE THREAD

**Issue by bkotlowski** [influxdata/telegraf#13395]
**Feature Request** 

Intel Baseband Device that provides Wireless Baseband hardware acceleration. These devices play a key role in accelerating 5G and 4G Virtualized Radio Access Networks (vRAN) workloads, increasing the overall compute capacity of a commercial, off-the-shelf platforms. 

Intel Baseband devices integrate various features critical for 5G and LTE (Long Term Evolution) networks, including e.g.: 

- Forward Error Correction (FEC) processing, 
 - 4G Turbo FEC processing, 
 - 5G Low Density Parity Check (LDPC) 
 - a Fast Fourier Transform (FFT) block providing DFT/iDFT processing offload for the 5G Sounding Reference Signal (SRS) 

We would like to have a Telegraf input plugin that exposes Intel Baseband metrics.

**Proposal:**

In the near future, we will propose PR which adds a new plugin we have created. The plugin will be able to expose Intel Baseband metrics.

**Desired behavior:** 

This plugin will allow Intel Baseband metrics to be gathered and exposed.

**Comment by powersj** [comment]
next steps: review PR once up
