### ISSUE TITLE
Add periodic refresh to regular-expression-matched Kafka topics

### ISSUE THREAD

**Issue by athornton** [influxdata/telegraf#13409]
### Use Case

In Rubin Observatory's use case, Kafka topics come and go quite frequently.  We use regular expressions to match those topics, and we would prefer to not have to restart telegraf to pick up topic changes.

### Expected behavior

At the expiration of some periodic timer, rescan the available topics from the Kafka broker and if the list of topics you're listening for changed, pick up the new topics without a restart.

### Actual behavior

Currently, this requires a restart of telegraf.

**Comment by powersj** [comment]
next steps: review #13410
