### ISSUE TITLE
"cpu.usage.average" is  missed from vm_metric_include 

### ISSUE THREAD

**Issue by orasia** [influxdata/telegraf#13415]
### Relevant telegraf.conf

```toml
vm_metric_include = [
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.run.summation",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.wait.summation",
```

### Logs from Telegraf

```text
no log
```

### System info

all

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

null

### Actual behavior

null

### Additional info

"cpu.usage.average" is  missed from vm_metric_include 

  vm_metric_include = [
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.run.summation",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.wait.summation",

**Comment by powersj** [comment]
Closing due to lack of information.

Additionally, we have seen this question come up from time to time here and on the forum. There usually is a delay in seeing some metrics as they are "historical" metrics, see: https://github.com/influxdata/telegraf/issues/8316#issuecomment-738190387
