### ISSUE TITLE
How to remove the built-in metrics of telegraf in the output plugin？

### ISSUE THREAD

**Issue by stone-98** [influxdata/telegraf#13421]
### Use Case

I configured a cpu input plugin and Prometheus input plugin. I found that the cpu metric was removed, and telegraf also included some internally set metrics, such as go_memstats_mcache_sys_bytes,go_memstats_mspan_inuse_bytes, etc. I don't need these metrics. I use outputs.prometheus_client.tagpass to configure and filter but it does not work. How should I delete the internally set metrics?

### Expected behavior

I can remove telegraf's built-in metrics through some configuration.

### Actual behavior

Haven't found a way yet.

**Comment by srebhan** [comment]
@stone-98 can you please share your config?!? Furthermore, I suggest to ask those question on Slack or the forums...
