### ISSUE TITLE
When can release the new features of vsan metric？

### ISSUE THREAD

**Issue by roleilijian** [influxdata/telegraf#13422]
### Use Case

We plan to use Telegraf to collect VSAN metrics, but the currently released versions do not support it. So, could you please inquire about a release plan that supports the VSAN metric feature?

### Expected behavior

Obtain VSAN metrics

### Actual behavior

The current version cannot obtain VSAN metrics

**Comment by srebhan** [comment]
@roleilijian are you talking about https://github.com/influxdata/telegraf/pull/11955? If so it will be released with v1.27.0 which is due...TODAY :rocket: ;-)

**Comment by roleilijian** [comment]
Thank you for your replay
