### ISSUE TITLE
CBOR parser plugin

### ISSUE THREAD

**Issue by tulku** [influxdata/telegraf#13464]
### Use Case

Telegraf currently supports many formats in which the data can be encoded, like `json`, `avro`, and `binary`. It would be nice to also support the [CBOR](https://en.wikipedia.org/wiki/CBOR) format as a more compact alternative to `json` but not as rigid as the `binary` plugin (where the different messages would need to be defined).

There is a CBOR Golang library that looks properly maintained and licensed under MIT:
https://github.com/fxamacker/cbor

### Expected behavior

I would expect the plugin to have a configuration similar to the JSON plugin, or even more straightforward if the data types from the CBOR message are used to derive the output types. Similar options to list the keys that would be converted to tags would be required.

### Actual behavior

There is currently no way to decode a CBOR message in telegraf.

### Additional info

During the work on the `binary` plugin it was discussed that supporting CBOR would be better suited for a different plugin (https://github.com/influxdata/telegraf/issues/6804#issuecomment-567897526), which I agree.

**Comment by powersj** [comment]
Hi,

This looks like an interesting format, but I have two concerns with this:

1) You said similar config to JSON plugin, but we have two JSON parsers: `json` and `json_v2`. Both have their advantages, limitations, as well as open issues. Which one were you looking at using.

2) While the upstream library is impressive, how widely used is the format versus say something like gRPC? What are potential use cases as right now it looks fairly narrow.

Thanks

**Comment by tulku** [comment]
Hi @powersj thank you for your reply!

> Hi,
> 
> This looks like an interesting format, but I have two concerns with this:
> 
> 1. You said similar config to JSON plugin, but we have two JSON parsers: `json` and `json_v2`. Both have their advantages, limitations, as well as open issues. Which one were you looking at using.

It is true that they have different configuration mechanisms. My comment was maybe a bit confusing but alluded to the fact that despite being a binary format, the configuration should be closer to the JSON (any) plugin than to the `binary` one. Basically working on keys instead of bytes and lengths.

For my use case, the simplest configuration would be:
1. Specify a list of keys that should be treated as tags. (like [`tags_keys`](https://github.com/influxdata/telegraf/blob/24b3d83f4958a47c506aca15a674bf67fc7af8ba/plugins/parsers/json/README.md?plain=1#L35) in the `json` plugin)
2. Specify a key that can be used as a measurement (like  [`measurement_name`] (https://github.com/influxdata/telegraf/blob/24b3d83f4958a47c506aca15a674bf67fc7af8ba/plugins/parsers/json_v2/README.md?plain=1#L17) and `measurement_name_path` (https://github.com/influxdata/telegraf/blob/24b3d83f4958a47c506aca15a674bf67fc7af8ba/plugins/parsers/json_v2/README.md?plain=1#L18) from the `json_v2` plugin.
3. By default the plugin will treat all keys not configured to be tags as fields.

Options that can be useful:
4. Specify a list of keys to be ignored.
5. In case there are multiple time fields in the message, specify which time key to use for a particular field key (which would be similar to the object configuration in `json_v2` probably), but for our particular need a regex matching the <key> to a <key>_time would be even better so that there is no need to explicitly list the known keys and their timestamp.

We should not need to define a type per key though, as CBOR already provides the types in the serialization. We might want to offer a mapping between CBOR types and Telegraf types, but that would be optional also as the basic types should be pretty standard how to map them.

Even though the proposed library supports other more advanced CBOR features (like reading the CBOR TAGs), I would consider them niceties or future additions than initial requirements.

> 2. While the upstream library is impressive, how widely used is the format versus say something like gRPC? What are potential use cases as right now it looks fairly narrow.

It is true that CBOR is less used than something like Protobuf. However, CBOR has some nice use-cases, mainly because it does not need an external tool nor pre-defined `.proto` files. It is basically a replacement of JSON, but with a much more concise representation and made standard by the [IETF](https://datatracker.ietf.org/doc/html/rfc7049). Making it possible to have the flexibility of a self-describing format without the massive space needed for something like JSON.

Libraries like [tinycbor](https://github.com/intel/tinycbor) are already included in the [Espressif IDF](https://github.com/espressif/idf-extra-components/tree/master/cbor) (ESP32 code library / framework / tools). Libraries like [ciborium-ll](https://lib.rs/crates/ciborium-ll) can be used for embedded Rust applications that want serialize in CBOR.

Because of the flexibility it offers, and how readily available it is in embedded tools, CBOR is already seeing significant adoption in the IoT space, and it is my impression that it will continue to grow.

It might be worth mentioning that telegraf already supports the `Avro` format which could be considered to be in between CBOR and Protobuf, but the support for Avro in the embedded space is more limited than CBOR.

> Thanks

Thank you!

**Comment by powersj** [comment]
Thanks for the detailed reply. Is this something you would either be willing to help test or even help develop the PR?

@srebhan and I chatted about this a little bit today and are not opposed, but are more interested in adding this to the existing xpath parser, which can parse json, proto, etc. already. He is going to take a quick look at this and should get back later this week.

**Comment by tulku** [comment]
Hi @powersj, thanks again for looking into this.

I was unaware of the XPath parser, it certainly looks like a good fit to add CBOR instead of creating a new plugin. Given that it supports MessagePack, I will take some of our CBOR messages, re-serialize them as MessagePack and experiment with the plugin configuration. Still, on a quick glance, it looks very usable.

Regarding testing, I will be able to test the code for sure, building and running Telegraf from source should not be a problem. Hopefully, I will be able to get a working configuration with MessagePack and then try changing to CBOR. However, I am unfamiliar with Go, so even though I could hack something together, probably not of good enough quality to be accepted.

Thanks again!
