### ISSUE TITLE
mqtt_consumer stops working after receiving initial messages in 1.27.0, works fine in 1.26.3

### ISSUE THREAD

**Issue by webdeck** [influxdata/telegraf#13476]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]

  topics = [
    "rpi/#",
    "sensor/#",
    "waittimes/#",
    "weather/#",
  ]

  username = "redacted"
  password = "redacted"

  data_format = "value"
  data_type = "float"
```

### Logs from Telegraf

```text
No errors are logged in the log file, even with --debug being used.

I have a number of topics whose values are not floats and generate expected parsing errors in the log, such as:

2023-06-20T00:38:00Z E! [inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "2023,06,20,00,37,23": invalid syntax
2023-06-20T00:38:00Z E! [inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "True": invalid syntax

With 1.26.3, I see these expected parsing errors for every publish.  With 1.27.0, I see an intial round of these parsing errors from the first publish of the retained topic values, but then I don't see any more entries in the log, and I don't see any subsequent data published into influxDB.
```

### System info

telegraf 1.27.0, macos 13.4.1 (using homebrew)

### Docker

n/a

### Steps to reproduce

1. Exact same configuration file works as expected with 1.26.3 (and prior - been running this for many months.)
2. Run 1.27.0 and see the failed behavior
3. Switch back to 1.26.3 and it works again - all I am switching is which compiled binary I am running, no libraries or config files are changing.

### Expected behavior

Expect every published topic value to be stored in influxdb.

### Actual behavior

Only the initial value for each topic is stored in influxdb.  Other inputs such as SMTP are working fine, I am only having issues with mqtt_consumer.

### Additional info

Happy to provide additional information if you need it.  There are over 4000 topics in total that I am subscribing to via the wildcards.

**Comment by powersj** [comment]
Hi,

There was a change made to the MQTT consumer in v1.27 which would now acknowledge metrics after they come through or if they error out during parsing. The previous behavior was that metrics would never get acknowledged and depending on the MQTT QOS level these messages would keep coming in, over and over again.

The fact that you said that no further messages come in is a bit concerning, but it could also mean that since messages are acknowledged there are not any. Although based on your comments it does not sound like the case.

I have put up https://github.com/influxdata/telegraf/pull/13478 which will have some debug artifacts shortly. Could you please pull one of them down and provide the *FULL* logs from the clients? I want to see what the mqtt client itself is doing.

Thanks

**Comment by webdeck** [comment]
Thank you - here is the debug log.  Looks like a ping check is failing after a minute and disconnecting.  I'm using mosquitto as my broker and topics are being updated every 15 seconds or so, which I can see via other MQTT clients.  Everything is published and subscribed with qos 0, most with retained set to true.
[t.log](https://github.com/influxdata/telegraf/files/11835838/t.log)

**Comment by powersj** [comment]
Thanks for the logs! It does seem that the mqtt client times out and doesn't get a ping back. I am not sure why we have the auto reconnect option of the client set to false, so I'll need to research that. However, for the time being I've pushed another change which changes autoreconnect to true. 

Can you give the new artifacts, available in 20-30mins, a try and verify that it does indeed attempt to reconnect after any failure?

Thanks!

**Comment by webdeck** [comment]
The new build didn't seem to make a difference.  I removed all the ParseFloat errors from the long to clean it up.  FYI, my mosquitto.conf has default settings for keepalive_interval (60) and max_keepalive (65535).
[t.log](https://github.com/influxdata/telegraf/files/11840664/t.log)

**Comment by powersj** [comment]
Something else is occurring, because if you are truly disconnected then we should attempt to reconnect at every gather cycle or eventually timeout. I have pushed another change that will print out the state, so we can figure out what the client thinks is the current status.

Can I ask a few things:

1) Can you try with the new build
2) Can you remove all unnecessary inputs, it makes the log a lot easier to read
3) Can you wait more than 60 seconds before quitting. The spec says `If the Keep Alive value is non-zero and the Server does not receive a Control Packet from the Client within one and a half times the Keep Alive time period, it MUST disconnect the Network Connection to the Client as if the network had failed`. That means it may take 90 seconds before it disconnects.

Thanks!

**Comment by webdeck** [comment]
Okay, I removed all other inputs.  I've attached a redacted version of the config file I used on this run, along with the log output.  It should be receiving a ton of messages, but after the first minute there is just a trickle coming in and reconnects happening.  I am also including a graph showing where the data goes missing during this test.

[t.log](https://github.com/influxdata/telegraf/files/11854375/t.log)
[telegraf-redacted.conf.txt](https://github.com/influxdata/telegraf/files/11854378/telegraf-redacted.conf.txt)
<img width="763" alt="Screenshot 2023-06-23 at 8 30 38 PM" src="https://github.com/influxdata/telegraf/assets/5542961/3ef350d9-9fa7-439a-9d89-47bdbc1a6784">

**Comment by powersj** [comment]
When you publish your messages what QOS is used?

**Comment by webdeck** [comment]
QOS 0 with retain True

**Comment by powersj** [comment]
@webdeck,

Sven and I chatted more about this and he thinks he found a case where no metrics are created and we were not acking the message. I've pushed another change with that + prints the message that as they are received. Can you try the tests again?

I'd like to be able to reproduce this locally, but I am not sure what we are missing.

Thanks!

**Comment by webdeck** [comment]
Sorry, still not working.  Log attached.
[t.log](https://github.com/influxdata/telegraf/files/11931396/t.log)

**Comment by webdeck** [comment]
Let me know if there is anything else I can provide to help you track this down.  I'm continuing to run 1.26.3 homebrew version that I restored from backup in the interim.  Could it be related to the volume of topics/messages?  There are over 4000 topics that are covered by those topic wildcards, and they are updated every 5-60 seconds, depending on the topic, but most are either 15 or 60 second updates.  Many of the topics contain string values that are not parsable to Float, but I don't care about those, but perhaps that is related to the root cause if you can't reproduce it?  Here's an example set of topics, some of which can be parsed as Floats, and some that can't.
<img width="309" alt="Screenshot 2023-07-04 at 8 39 44 PM" src="https://github.com/influxdata/telegraf/assets/5542961/f58fc6d7-fd7e-45db-967f-99afc5efa1d5">

**Comment by powersj** [comment]
> Many of the topics contain string values that are not parsable to Float, but I don't care about those, but perhaps that is related to the root cause if you can't reproduce it?

I am wondering if this is the case as well. However, I am also not seeing any errors related to parsing in the log. Are you omitting these? I would expect to see many `Error in plugin: strconv.ParseFloat: parsing...` messages like you have in your original issue report.

The logic that was concerning to @srebhan and I was right after parsing, either we fail to prase, ack the message and return an error, or we should loop through the metrics that were generated by the parsing. 

Looking at the logs you get an initial influx of metrics that then tails off:

```s
2023-07-02T20:41:52Z D! [outputs.influxdb] Wrote batch of 481 metrics in 16.998208ms
2023-07-02T20:42:02Z D! [outputs.influxdb] Wrote batch of 211 metrics in 11.116041ms
2023-07-02T20:42:12Z D! [outputs.influxdb] Wrote batch of 92 metrics in 9.733625ms
2023-07-02T20:42:22Z D! [outputs.influxdb] Wrote batch of 78 metrics in 10.944625ms
2023-07-02T20:42:32Z D! [outputs.influxdb] Wrote batch of 60 metrics in 11.053292ms
2023-07-02T20:42:42Z D! [outputs.influxdb] Wrote batch of 60 metrics in 8.310375ms
2023-07-02T20:42:52Z D! [outputs.influxdb] Wrote batch of 60 metrics in 8.696541ms
2023-07-02T20:43:02Z D! [outputs.influxdb] Wrote batch of 56 metrics in 11.052208ms
2023-07-02T20:43:12Z D! [outputs.influxdb] Wrote batch of 56 metrics in 10.174209ms
2023-07-02T20:43:22Z D! [outputs.influxdb] Wrote batch of 56 metrics in 9.258208ms
2023-07-02T20:43:32Z D! [outputs.influxdb] Wrote batch of 28 metrics in 7.999917ms
2023-07-02T20:43:42Z D! [outputs.influxdb] Wrote batch of 3 metrics in 17.465791ms
2023-07-02T20:43:52Z D! [outputs.influxdb] Wrote batch of 2 metrics in 7.208334ms
2023-07-02T20:44:02Z D! [outputs.influxdb] Wrote batch of 1 metrics in 7.081417ms
2023-07-02T20:44:12Z D! [outputs.influxdb] Wrote batch of 1 metrics in 11.868167ms
2023-07-02T20:44:22Z D! [outputs.influxdb] Wrote batch of 1 metrics in 6.939583ms
```

This makes me think we were not acking some scenario and as a result are waiting to finish something. Or maybe we are acking when we shouldn't?! I've pushed another change that will only ack when we are using a persistent session. Could you give that a try?

Thanks

**Comment by webdeck** [comment]
Sorry, I removed the parsing errors to shorten the log, as I indicated earlier.  I have attached the full log here from the PREVIOUS run with those errors included.  I will do another test with the new version in the next response.
[t.log](https://github.com/influxdata/telegraf/files/11962785/t.log)

**Comment by webdeck** [comment]
The new build is worse.  Looks like it just stops.  Here is the full log.
[t.log](https://github.com/influxdata/telegraf/files/11962819/t.log)

**Comment by powersj** [comment]
Huge thank you for those logs with error messages and the quick tests. 

There are exactly 1000 messages about being unable to parse the message in both logs. That also corresponds to the default setting for the `MaxUndeliveredMessages`. This made me take a look at the value and how it is used in more detail. My guess was that we were filing up the semaphore, which is limited by the max undelivered messages value and not releasing.

I've pushed another change to ensure we are releasing the semaphore when errors during parsing or other issues occur.

**Comment by webdeck** [comment]
That seems to have fixed it!  Thank you so much for working back and forth with me on this.  Sorry again for the confusion over the parse errors in the log.  Here is the latest run.
[t.log](https://github.com/influxdata/telegraf/files/11974727/t.log)

**Comment by powersj** [comment]
woohoo thank you for the confirmation!

**Comment by maraswrona** [comment]
@powersj I just found this issue and I think it explains what is happening to me also.

I'm running telegraf 1.29.2 via docker. I'm using mqtt_consumer plugin with `data_format = "json"` for my payload (I'm not using json_v2). I noticed that the mqtt consumer stops pushing data to influxdb after ~15 minutes. In my case the input does contain some strings and the topic updates are coming in every 1s. An error every 1s for 15s is 900 errors, so it got me thinking when you mentioned that the setting  `max_undelivered_messages` is 1000. 

I tried to reduce that to e.g. 300 and 120 respectively and indeed my data stops coming after 5 and 2 minutes so it must be it.

Before I dive any deeper into this - would you like a separate issue raised, or are you ok discussing this here?

**Comment by powersj** [comment]
@maraswrona - please file a new issue and be sure to include your complete config and logs.

**Comment by maraswrona** [comment]
Thanks @powersj . I described it here: https://github.com/influxdata/telegraf/issues/14685
