### ISSUE TITLE
Telegraf running on ARM machine returns 'cannot allocate memory' error for inputs.Ping with many urls[] and method.exec

### ISSUE THREAD

**Issue by bbdshow** [influxdata/telegraf#13472]
### Use Case

By observing the memory of the ARM machine, we found that the memory usage was healthy, but still reported this error.
So the suspicion is that a large number of exec.Com mands (exec.LookPath(ping)) are created at the same time.
We have a scenario where len(urls) > 1000, so we particularly want a concurrency control policy for inputs.Ping.

Such as

``` go
type Ping struct {
	//add concurrent config arg
	concurrent int `toml:"concurrent"`
	//...
}

func (p *Ping) Gather(acc telegraf.Accumulator) error {
	if p.concurrent > 0 {
		return p.limitGather(acc)
	}
       // ...
}

func (p *Ping) limitGather(acc telegraf.Accumulator) error {
	// concurrent limit
	c := make(chan struct{}, p.concurrent)

	wg := sync.WaitGroup{}
	for _, host := range p.Urls {
		c <- struct{}{}
		wg.Add(1)
		go func(host string) {
			defer func() {
				<-c
				wg.Done()
			}()

			switch p.Method {
			case "native":
				p.pingToURLNative(host, acc)
			default:
				p.pingToURL(host, acc)
			}
		}(host)
	}

	wg.Wait()
	return nil
}
```	

### Expected behavior

The limits will be adjusted according to the operating environment to achieve accurate Ping results

### Actual behavior

If the existing version can be configured to achieve the above requirements, I hope to inform you, thank you very much!

### Additional info

Telegraf is deployed on an ARM virtual machine using docker containers

ARM VM. 
memory: 16GB
The container does not limit resource usage

error info:
E! [inputs.ping] Error in plugin: host xx.xx.xx.xx fork/exec /usr/bin/ping: cannot allocate memory

**Comment by powersj** [comment]
Hi,

> fork/exec /usr/bin/ping: cannot allocate memory

As you mentioned, this is a limitation of your system. It is possible you ran out of memory, that you ran out of PID, or some other resource.

> The limits will be adjusted according to the operating environment to achieve accurate Ping results

I don't see us adding some dynamic creation based on the size of the system. This is left to the user to use the correctly sized system, or ensuring their system is setup to handle the required work.

**Comment by bbdshow** [comment]
Hi, if you are willing to adopt this feature, I would like to provide the corresponding code implementation as well as test cases!

**Comment by powersj** [comment]
We have confirmation of users, who use [many thousands of systems](https://github.com/influxdata/telegraf/issues/6360) with ping.

> Perhaps it would be better to support the restriction feature

This same question could come up on a number of other plugins that do things concurrently. The concurrency is handled at the plugin level. If we had numerous issues where users who were running into resource limitations this is a possibility we might look at refactoring to allow a more global approach.

> if you are willing to adopt this feature, I would like to provide the corresponding code implementation as well as test cases!

My first concern with doing this at the plugin level is now you are giving the user one more way to run into the global interval counter. The user already has to consider that their ping interval and count needs to be less than the overall interval, but now if the plugin is going to split up pings the user has to keep in mind how many URLs they have and ensure that all batches complete. 

My second concern is how would you determine how to batch up? Are you only going to batch based on that one specific error message? Or have a setting that let's the user batch?

**Comment by bbdshow** [comment]
Thanks for the reply, this question is the same amount of tasks, really only on ARM machines. 

I can understand the two questions you raised, and I'm going to think about it in more detail to see if there's a better solution to avoid the extra amount of computation that users generate to think about how to configure it!

🤝

**Comment by powersj** [comment]
>  really only on ARM machines.

What type of arm processor is in use in this situation?

> I'm going to think about it in more detail to see if there's a better solution to

Sounds good! thanks
