### ISSUE TITLE
Feature Request: NSQ Input plugin

### ISSUE THREAD

**Issue by jchauncey** [influxdata/telegraf#1347]
### Proposal:
An input plugin that can pull data from a configurable topic and send that data to an output source. The data could/should be wire protocol compatible to allow for easy translation.

### Current behavior:
There are plugins to support queues like RabbitMQ. 

### Use case: [Why is this important (helps with prioritizing requests)]
Right now the Deis team is working on scaling our monitoring stack on kubernetes infrastructure. We have proposed using NSQ to allow work to be processed outside of the producer. We have built our own consumer to pull data from NSQ and forward it to influxdb but it seems like this could be easily encapsulated within our existing telegraf instances.

**Comment by sparrc** [comment]
Sounds good, we can call it `nsq_consumer`, what is wire protocol? Do you mean influx line protocol?

**Comment by jchauncey** [comment]
Yeah don't know why I keep calling it that. I have a working consumer that does this so I'll probably submit a pr soon.
