### ISSUE TITLE
Improve the support of rabbitmq stream queue on amqp_consumer input plugin 

### ISSUE THREAD

**Issue by massimogallina** [influxdata/telegraf#13479]
### Use Case

We would like to consume messagges from RabbitMQ stream queues (https://www.rabbitmq.com/streams.html).

### Expected behavior

Telegraf can read all the messagges of the stream queue, and define the consume start point.

### Actual behavior

The new messagges are correctly consumend, but the old messagges are never read by telegraf. It is because the plugin does not permit to define the `x-stream-offset` parameter and by default the consumer start read from the `next` chink (see https://www.rabbitmq.com/streams.html#consuming).

**Comment by powersj** [comment]
Hi,

It looks like we could possibly add this as a header to the request via `x-stream-offset` and it should just work?

Based on the docs are a few valid options. These first three are very specific values:

* `first` - start from the first available message
* `last` - start reading from the last written message
* `next` - same as not specifying any offset (default)

The next three values are instead potentially random values, harder to validate:

* Offset - a numerical value
* Timestamp - unix timestamp
* Interval - a string value with a number + one of (`Y`, `M`, `D`, `h`, `m`, `s`)

That said, I think this sounds doable, with a little validation. Would you be willing to put up a PR with the change? or if not be able to test a change?
