### ISSUE TITLE
Telegraf should send stats about itself

### ISSUE THREAD

**Issue by lswith** [influxdata/telegraf#1348]
### Proposal:

I would like to see telegraf send metrics about it's own internals. This means what it prints to its logs:
- time take to send to output
- how many stats sent to output

It would also be nice for telegraf to count the number of errors it received from a particular input and send that as well. i.e. count failures
### Use case:

At my company we use telegraf extensively and would like to make sure it is running under the correct load etc. Having telegraf tell us these statistics would be nice so that we can better monitor telegraf's performance.

**Comment by sparrc** [comment]
agreed, this would be a good idea 👍

**Comment by stuartbfox** [comment]
Big +1 from me as well

**Comment by zp-markusp** [comment]
+1

**Comment by toni-moreno** [comment]
I also would like to have basic system info from my process ( to check the impact on the host system) something like.
* % cpu
* memory 
* open files

And  also virtual machine related stats heap/gc/gouroutines. ( you can see as I did in another influx agent).
https://github.com/toni-moreno/snmpcollector/blob/master/pkg/selfmon.go

Thank you very much for this great tool!

**Comment by zp-markusp** [comment]
As some checks from telegraf seems to be quite expensive if the system is under heavy load this issue for me is getting more and more important.
I really need to be able to see how long certain check required in the past to worst case disable those checks on mission critical systems.

So for me the most critical metrics would be:
- total execution time of all checks (being able to alert if execution time > execution interval)
- execution time of individual checks (being able to identify which checks are causing a high execution time)
- peak mem usage during execution
- total cpu usage 

regards, Markus

**Comment by kostasb** [comment]
+ ingress number of points per input and total

**Comment by johnrengelman** [comment]
Other items to report:
Metric buffer usage
# of dropped metrics
# of reported metrics

These are necessary when running a telegram relay layer using http_listener
