### ISSUE TITLE
internet_speed - store location

### ISSUE THREAD

**Issue by nodiaque** [influxdata/telegraf#13490]
### Use Case

Hello,

I currently am using internet_speed plugins and it's great that it save the source, but it would be great to have the location of that source also. I see in the log output that it says that it's using <location> (source) but I don't see anywhere in my influxdb the location, only the source itself.

Thank you

### Expected behavior

store both location and source

### Actual behavior

store only the source url

**Comment by powersj** [comment]
Hi,

When I added a few tags to this plugin, we decided against any more due to the increase in cardinality. I have put up #13497 which adds the location as a field. A user can use a processor to make this a tag if they want as well.

Thanks

**Comment by nodiaque** [comment]
Thank you for the information. How do I make a processor to convert a field into a tag?

**Comment by powersj** [comment]
I beleive this should be a working example, let me know if it is not ;) This will only look at the `internet_speed` metric and convert the field called "location" to a tag.

```toml
[[processors.converter]]
  namepass = "internet_speed"
  [processors.converter.fields]
    tag = ["location"]
```

**Comment by nodiaque** [comment]
I put this in telegraf conf or it's into influxdb?

**Comment by powersj** [comment]
Telegraf and as a result the location will show up as a tag in influxdb
