### ISSUE TITLE
FreeBSD memory input hang

### ISSUE THREAD

**Issue by jbergstroem** [influxdata/telegraf#1351]
Just ran into a telegraf process eating all cpu (one core) on a FreeBSD system. The log seems to point to an issue with the memory module.
- OS: FreeBSD 10.3
- CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (3400.07-MHz K8-class CPU)
- MEMORY: hw.physmem: 34001588224
- Telegraf version: 0.13.1 (installed with `pkg install telegraf`)
- InfluxDB version: 0.13.1 (installed with `pkg install influxdb`)
- loaded modules: disk diskio kernel mem processes swap system cpu

Happy to provide config on request, but its very vanilla; basically sample config.

Here's some dtruss output:

```
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.699896689 })       = 0 (0x0)
clock_gettime(4,{ 4073197.699925793 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.701896090 })       = 0 (0x0)
clock_gettime(4,{ 4073197.701925426 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.703897541 })       = 0 (0x0)
clock_gettime(4,{ 4073197.703926417 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.705894590 })       = 0 (0x0)
clock_gettime(4,{ 4073197.705923822 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.707896456 })       = 0 (0x0)
clock_gettime(4,{ 4073197.707925374 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.709894262 })       = 0 (0x0)
clock_gettime(4,{ 4073197.709923261 })       = 0 (0x0)
_umtx_op(0x1c802c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x7fffdedf4e20) ERR#60 'Operation timed out'
clock_gettime(4,{ 4073197.711896483 })       = 0 (0x0)
clock_gettime(4,{ 4073197.711926017 })       = 0 (0x0)
```

..and output from the logfile giving us a hint:

```
2016/06/07 21:42:09 Output [influxdb] wrote batch of 42 metrics in 12.175143ms
2016/06/07 21:42:19 Output [influxdb] buffer fullness: 42 / 1000 metrics. Total gathered metrics: 520917. Total dropped metrics: 0.
2016/06/07 21:42:19 Output [influxdb] wrote batch of 42 metrics in 11.24492ms
2016/06/07 21:42:30 Output [influxdb] buffer fullness: 0 / 1000 metrics. Total gathered metrics: 520917. Total dropped metrics: 0.
2016/06/07 21:42:39 Output [influxdb] buffer fullness: 83 / 1000 metrics. Total gathered metrics: 521000. Total dropped metrics: 0.
2016/06/07 21:42:39 Output [influxdb] wrote batch of 83 metrics in 12.411225ms
2016/06/07 21:42:49 ERROR: input [mem] took longer to collect than collection interval (10s)
2016/06/08 11:51:11 Starting Telegraf (version )
2016/06/08 11:51:11 Loaded outputs: influxdb
2016/06/08 11:51:11 Loaded inputs: disk diskio kernel mem processes swap system cpu
```

**Comment by sparrc** [comment]
Why does your telegraf package not have a version? (`2016/06/08 11:51:11 Starting Telegraf (version )`)

Also could you please try setting `collection_jitter = "3s"` so that all plugins are not collecting their metrics at the same time?

**Comment by jbergstroem** [comment]
Thanks for the quick reply!

@sparrc said:
> Why does your telegraf package not have a version? (2016/06/08 11:51:11 Starting Telegraf (version ))

I think this is tied to how it's packaged in ports; the influxdb package has a similar issue and I've notified  packagers. Hints likely to be found [here](https://svnweb.freebsd.org/ports/head/net-mgmt/telegraf/).

> Also could you please try setting collection_jitter = "3s" so that all plugins are not collecting their metrics at the same time?

Done. Btw, this is the first time in 5d of running telegraf on this host I've encountered this.

**Comment by sparrc** [comment]
hm it might not be related to the collection_jitter at all then. My best guess is that this line of code is hanging: https://github.com/shirou/gopsutil/blob/master/internal/common/common_freebsd.go#L22

which is getting called when querying for memory stats here: https://github.com/shirou/gopsutil/blob/master/mem/mem_freebsd.go#L14

gopsutil has a utility for timing out hung system calls but it's not being used in this case, not sure why.

**Comment by jbergstroem** [comment]
@sparrc thanks for summing it up. Can I do anything else to help out? Sorry, not very acquainted to Telegraf just yet.

**Comment by sjwang90** [comment]
Closing due to lack of interest and discussion. Feel free to reopen if desired.
