### ISSUE TITLE
AWS RDS input plugin

### ISSUE THREAD

**Issue by TrevorChan1** [influxdata/telegraf#13528]
### Use Case

Hello! I am currently working on an application where metrics are gathered from all RDS instances located on an AWS account and exported. The metrics gathered are similar to the ones available in the mysql inputs plugin (along with some custom queries), but I also want to be able to auto-discover DB instances similar to what the cloudwatch plugin is able to do (since I can't find a way to dynamically input all instances without external scripting). The reason I can't use the mysql input plugin for this is because I would like to be able to auto-discover all RDS instances on the account, and I can't use the cloudwatch input plugin for this because I need to directly query each database for mysql metrics and custom values (along with preferring not to create a custom cloudwatch dashboard for each metric for each database)

I think that an RDS input plugin would be very helpful for automating gathering metrics from databases stored in RDS instances on AWS.

### Expected behavior

An RDS input plugin could work like a mixture between the mysql and cloudwatch input plugins. Since Telegraf already has the capability to group together AWS input sources through dimensions, would it be possible to query database instances within configuration file-specified RDS dimensions for mysql metrics and export them (given that credentials are supplied for the databases)?

If possible, I would love for an RDS input plugin with the abilities:
- Able to group input sources based on AWS dimensions, similar to Cloudwatch
- Query each of the DB instances specified for mysql metrics
- Adding in custom queries to be performed on the databases and exported

For example:
```
[[inputs.rds]]
    ## Amazon Region
    region = "us-east-1"
    period = "1m"
    interval = "1m"

    [[inputs.rds.metrics]]

        # Example mysql metrics
        gather_user_statistics = true
        gather_all_slave_channels = true
        gather_slave_status = true

        # Custom queries to be run along with the mysql metric
        custom_query = [
        "SELECT ...",
        "SELECT ..."
        ]

        [[inputs.rds.dimensions]]
            name = "DBInstanceIdentifier"
            value = "*"
```

### Actual behavior

Currently, I am able to grab metrics about the underlying OS data from cloudwatch using the cloudwatch input plugin and grab mysql metrics from hard-coded rds instance endpoints. To my knowledge, I am unable to dynamically fetch all RDS instance endpoints on each telegraf iteration using the mysql plugin, nor perform custom select statement queries.

I hope this is something that others find helpful / useful. Thank you for your time!

**Comment by powersj** [comment]
Hi,

> Query each of the DB instances specified for mysql metrics

My understanding of RDS is that it is not just MySQL, but also Oracle, MS SQL, Postgresql, etc. I would expect any solution to be able to distinguish between those. Do you know if that is possible during auto-discovery? 

The one item I don't see spelled out here is authentication. How would you manage that without hard-coding values. It does sound like MySQL and PostgreSQL support IAM auth, but not the others. What was your thinking on that?

> nor perform custom select statement queries.

This is what the [sql](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sql) input plugin is for today. Please take a look at that plugin to see what goes into taking a query and turning it into a metric.

I think the auto-discovery would be interesting, but due to the lack of hearing this request before, and the difficulty in supporting many of these cloud plugins I am hesitant. Is this something you are thinking of contributing?

Thanks

**Comment by TrevorChan1** [comment]
Thank you for the quick response!

> My understanding of RDS is that it is not just MySQL, but also Oracle, MS SQL, Postgresql, etc. I would expect any solution to be able to distinguish between those. Do you know if that is possible during auto-discovery?

In the RDS dimensions, one of them is EngineName (like postgres), so I believe it should be able to distinguish which engine is running on each instance. That being said, the instances I'm using are all running either postgres or mysql so I am unsure how the authentication would work for the other engines. 

Thank you for pointing out the sql input plugin to me! I'll check that out for the custom query portion.

> I think the auto-discovery would be interesting, but due to the lack of hearing this request before, and the difficulty in supporting many of these cloud plugins I am hesitant. Is this something you are thinking of contributing?

I feel like RDS is a pretty well-known tool and having all RDS instance metric-gathering automated within an account would be convenient, but if there's already Telegraf input plugins for most of the engines and other people haven't requested this feature I don't know how common of a use case this is. For contributing, I don't have much experience with the Go language and I'm not sure how much help I'll be able to bring.

In terms of the auto discovery, do you know if it's possible to connect a dynamic input to the sql / mysql input plugins for the `servers` value? There's a way to list all DB instances using the AWS CLI, so I'm wondering if there's a way to manually just run that every iteration and connect the output to the input plugins (like if I set an environment variable with the values in inputs.exec, can inputs.mysql use that value of the environment variable)?

**Comment by powersj** [comment]
> I feel like RDS is a pretty well-known tool

Well, being well-known, and being able to support something are two very different things ;)

> do you know if it's possible to connect a dynamic input to the sql / mysql input plugins for the servers value? 

It is not. The plugins run separately with no knowledge of each other. You would not be able to somehow chain different inputs with each other. 

> For contributing, I don't have much experience with the Go language and I'm not sure how much help I'll be able to bring.

What I would typically suggest of someone in your case to do is to use the exec input plugin. Write your own script to find all the servers, get your metrics, and report them. Then you can still make use of telegraf to run the process, any of the processing of the metrics, and sending them to outputs.

**Comment by TrevorChan1** [comment]
> What I would typically suggest of someone in your case to do is to use the exec input plugin. Write your own script to find all the servers, get your metrics, and report them. Then you can still make use of telegraf to run the process, any of the processing of the metrics, and sending them to outputs.

I'll try it out, thank you!
