### ISSUE TITLE
[[inputs.amqp_consumer]] with auto_delete = true?

### ISSUE THREAD

**Issue by giuliboy** [influxdata/telegraf#13529]
### Please direct all support questsions to slack or the forums. Thank you.

sometimes our containerized telegraf is being stopped by the developers and we leave a queue on our rabbitmq that is blowing up because the queue was not declared auto delete. Is there a way to configure this feature via telegraf.conf?

**Comment by giuliboy** [comment]
this is not resolved . 
the underlying issue we have is that telegraf is not reliably consuming and for some reasons stops consumption . 
The logs show:


syfbusinessintelligence-telegraf-1  | 2023-07-08T17:46:59Z E! [agent] Error writing to outputs.influxdb_v2: failed to send metrics to any configured server(s)
syfbusinessintelligence-telegraf-1  | 2023-07-08T17:47:00Z E! [outputs.influxdb_v2] When writing to [https://westeurope-1.azure.cloud2.influxdata.com]: retry time has not elapsed

**Comment by powersj** [comment]
> telegraf is not reliably consuming and for some reasons stops consumption .

The two log lines you provided are about errors sending to influxdb, not telegraf consuming metrics from amqp consumer. The amqp consumer plugin has a max undelivered messages setting, which will prevent additional metrics from getting consumed if you are unable to send metrics. This is to prevent data loss and ensure your data gets from telegraf to your output. 

> retry time has not elapsed

One possibility is that you have hit a service limit and are being throttled. As a result metrics are not getting written to. It could also be some sort of connection issue. Your full logs should show a return code from influxdb that would provide additional background as to what is happening.

**Comment by giuliboy** [comment]
thanks , yes today we discovered, that we are running into a influx service related issue that prevents telegraf from further pushing data into.
Thanks -> Closed
