### ISSUE TITLE
[Feature Request] Prometheus Output should send counters for string data

### ISSUE THREAD

**Issue by Lswith** [influxdata/telegraf#1353]
### Proposal:
Have the prometheus output plugin, output fields that are strings. 
### Current behavior:
The prometheus output plugin currently drops all fields which are booleans or strings. This means that any plugins which only output strings (the consul plugin) aren't shown in the prometheus output at all.
### Desired behavior:
For every string field, add a label to the prometheus metric and increment a counter. This basically means that for every combination of field strings, a counter is incremented. This would allow non-string fields to still be outputted to prometheus for collection.

### Use case: [Why is this important (helps with prioritizing requests)]
Currently, the consul input, outputs the status of a service as either 'passing', 'critical', 'warning', etc. These consul statuses cannot be parsed by the prometheus output and are simply dropped. I would like to use the consul input to determine if the service is passing and output this to prometheus.

**Comment by sparrc** [comment]
I don't think that this would be a good idea to do generally. There is your use-case where it would be nice to increment a counter for a string, but there are many use-cases where that may not be the case.

There is also the possibility of memory usage growing out of control with this. For example, if a user was storing UUIDs as string fields in their influx database, the map storing these counters could basically grow infinitely.

Beyond that, I personally don't think it's a good idea to try to one-off solutions like this into outputs that simply don't support strings, such as prometheus.
