### ISSUE TITLE
Enhanced Error Detection and Reporting in 'inputs.http'

### ISSUE THREAD

**Issue by mighty-nyaina** [influxdata/telegraf#13548]
### Use Case

I would like to request a feature for Telegraf to enhance error detection and reporting capabilities in the inputs.http plugin. This feature will allow users to define custom error detection criteria and perform specific actions when errors are detected, such as sending alerts or forwarding error messages to other outputs.

### Expected behavior

When the new error detection feature is implemented in the inputs.http plugin, users will be able to configure error detection rules based on their specific use cases. They will define criteria to identify errors in the HTTP responses, such as specific strings, status codes, or response patterns. Telegraf will evaluate the configured rules and trigger the specified actions whenever an error is detected. The actions can include sending notifications, logging errors, or forwarding error messages to other outputs like AMQP brokers.

### Actual behavior

Currently, the inputs.http plugin in Telegraf does not provide built-in error detection functionality. Users have limited options to handle errors in HTTP responses, making it difficult to customize error detection and perform targeted actions based on specific error conditions. This lack of error detection capabilities hinders the ability to effectively monitor and react to errors in HTTP data collection.

**Comment by srebhan** [comment]
Hmmm shouldn't this be possible right now using the [http_response input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_response) and a starlark processor?

**Comment by mighty-nyaina** [comment]
@srebhan Yes but using the 'http_response' plugin in addition to the 'http' plugin can indeed result in two calls for each request. So, this could be a drawback for APIs billed based on the number of calls

**Comment by powersj** [comment]
> Telegraf will evaluate the configured rules and trigger the specified actions whenever an error is detected.

Telegraf is not an error detection tool. It collects raw metrics, parses data to generate metrics. The existing http_response plugin is what you would use to generate those metrics and whatever tools you used beyond to react to the results of those metrics is up to you.

**Comment by srebhan** [comment]
@mighty-nyaina out of interest, which information is missing in the `http_response` plugin?

**Comment by srebhan** [comment]
@mighty-nyaina I might be wrong but if you set the `response_body_field` to some valid string, the output of the `http_response` plugin will contain the message body in the specified field. You can then use the [parser processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/parser) on that field without the need of a the `http` plugin. What am I missing?

**Comment by mighty-nyaina** [comment]
@srebhan yes, you're right. Thanks for explanation!
