### ISSUE TITLE
Add Example Folder to Plugins

### ISSUE THREAD

**Issue by Jayclifford345** [influxdata/telegraf#13545]
### Use Case

https://github.com/InfluxCommunity/Telegraf-Community-Configs

Currently holds a few examples from different plugins. The idea would be to merge these into the main repo as an example folder on a plugin-by-plugin basis

### Expected behavior

plugins --> input --> opcua --> examples --> basic-example.conf
                                                                        --> certificate-example.conf

### Actual behavior

Foo

**Comment by powersj** [comment]
next steps: look at adding additional examples as test cases if possible. When adding these, ensure they do not use deprecated options. Ensure examples are maintainable as best as possible as well.

**Comment by powersj** [comment]
Going to close, but happy to see PRs that add additional examples into plugins in the future.
