### ISSUE TITLE
Outputs.Stackdriver inherit "instance" label from sending agent when used in a client server configuration

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13555]
### Use Case

When using the `outputs.stackdriver ` output plugin in a client server configuration (one or more Telegraf agents sending to a single Telegraf server which sends to GMP using `outputs.stackdriver`). 

In the context of GMP, the label `instance` is an identifier for the specific machine that’s emitting metrics. This works great when you're using Telegraf to send straight to GMP, but if you're sending to a Telegraf server via `outputs.stackdriver` you need to set instance at the `outputs.stackdriver.resource_labels` block level as that's a requirement. But to get the hostname of the agent sending metrics you also have to set `instance` on the agent side but this agent side `instance` label appears to be renamed to `metric_instance` by `outputs.stackdriver`.

It would be great if `instance` is left as an empty string and could be inherited by the sending agent or something along those lines. Like if in server mode and the sending agent has `instance` already set and instance on the `outputs.stackdriver.resource_labels` is set to an empty string the `instance` that is sent is the instance from the agent sending the metrics to the Telegraf server.

### Expected behavior

Use a Telegraf agent to send to a Telegraf server which sends metrics to GMP via `outputs.stackdriver` which uses the `instance` of the agent sending the metrics instead of what is being set at the Telegraf server and not renaming the agent `instance` to `metric_instance`.

### Actual behavior

The agent `instance` is renamed to `metric_instance`. The `instance` label is present with whatever value is set, or missing altogether if left as empty string. 

Example:
```
win_mem_Available_MBytes_gauge{cluster="st9999",host="servername",job="googleproject",location="us-east1-b",metric_instance="computername",namespace="test",objectname="Memory",project_id="googleproject",role="Corporate Laptop"}
```

### Additional info

So yeah, it works perfect if you send from the agent directly to Google, but if you use Telegraf as a server it doesn't preserve `instance` from the sending agent, and instead renames it to `metric_instance`. This is important because the way GMP optimizes query performance when using `instance` as the device sending the metrics.

**Comment by powersj** [comment]
Hey,

Not quite clear to me initially as to what is doing the renaming of `instance` to `metric_instance`.

> Use a Telegraf agent to send to a Telegraf server 

Can you help me understand what you are doing here? If you output the metrics to stdout using `[[outputs.file]]` does the rename exist there as well?

Thanks!

**Comment by crflanigan** [comment]
Hi @powersj ,

We are sending metrics from a Telegraf agent on a workstation using the Open Telemetry output plugin to a Telegraf server with `instance` set as `$HOSTNAME`, and then from there it is sent to GMP.

I'm not positive where this rename is happening, but when we write to `outputs.file` we see that `instance` is preserved:
```
win_process_Percent_Processor_Time,entity=SecurityHealthService,host=telegrafserver,instance=computername,objectname=Process,role=Corporate\ Laptop gauge=0 1688577480000000000
```
But when it is viewed in Google we see `instance` and `metric_instance`, or just `metric_instance` when `instance` is left as empty string in the Stackdriver resoure labels. 

In case this helps, when we send the metrics using another method like through a Prometheus remote-write receiver to Google we see the workstation's hostname as `instance`.

**Comment by powersj** [comment]
> I'm not positive where this rename is happening, but when we write to outputs.file we see that instance is preserved:

The outputs.file output is from the telegraf server and not the originating workstation?

The resource labels are created based on what is in your configuration. There does not appear to be any changes or modifications that occurs to those, nor any way to inherit today as you pointed out.

It sounds like your first telegraf creates metrics with a tag called "instance" and your hope is to have that added as a resource label? Today tags are all added as a metric label.

**Comment by powersj** [comment]
> I wasn't sure what to make of it so I figured I'd let you know to see if it could be adjusted. Does that make sense?

Yeah I think it does now.

I think a new option that allows a user to specify tags as resource labels makes sense then. For example:

```toml
## Tags as resource labels
## Tags defined in this option, when they exist, are added as a resource label
## and not included as a metric label. The values from tags override the values
## defined under the resource_labels config options.
# tags_as_resource_label = []
```

Questions for you:

1. What do you think about the config option above?
2. Should the tag also be removed from the metric label, or exist in both metric label and resource label if it is defined in the above config option?
3. Are you good with tags overriding locally defined resource labels. That seemed to be the behavior you were proposing, but I wanted to confirm. This way the labels set on previous metrics take precedence.

**Comment by crflanigan** [comment]
> Questions for you:
> What do you think about the config option above?
Hi @powersj, 
I looked at this with my peer @JonWalz2 and we think this sounds like a great config option!

> Should the tag also be removed from the metric label, or exist in both metric label and resource label if it is defined in the above config option?

Are you thinking we would specify `instance` as a resource label with the value of empty string and then specify `instance` in `tags_as_resource_label` which would change the resource label from empty string to whatever is sent in the instance tag from the agent? If so, sounds good to us!

> Are you good with tags overriding locally defined resource labels. That seemed to be the behavior you were proposing, but I wanted to confirm. This way the labels set on previous metrics take precedence.

What might be better is that if we define `instance` in the `tags_as_resource_label` we wouldn't have to define it all in the resource label. That make more sense as you only have to define it once. Thoughts?

**Comment by powersj** [comment]
> What might be better is that if we define instance in the tags_as_resource_label we wouldn't have to define it at all in the resource label. That make more sense as you only have to define it once. Thoughts?

This was my intention as well. Thanks for reviewing!

next steps:

* add new `tags_as_resource_label` option
* When defined any matching tags are removed from a metric label and added instead as a resource label
* values that are discovered take precedence over user-defined resource labels

**Comment by powersj** [comment]
@crflanigan,

I have put up https://github.com/influxdata/telegraf/pull/13575 with the new `tags_as_resource_label` option. There should be artifacts to try in the next 10-15mins!


What I am still a little uncertain about is removing the tag as a metric label as well. I think it makes sense to do, but not sure I've thought through, or fully understand, if any other consequences exists in doing so.

Thanks!

**Comment by crflanigan** [comment]
Thanks @powersj !!

I will test this out next week and let you know!

**Comment by crflanigan** [comment]
@powersj 
It looks like theres a Windows GitOps test that's failing so I'm not sure the binaries will generate.

**Comment by powersj** [comment]
yeah, looking at this right now. I may have to look with fresh eyes on Monday as it is not obvious what I changed would cause this, so I think a change we accepted today is regressing something.

**Comment by powersj** [comment]
ok artifacts are now available! Still looking into root cause of the test failures, but it very likely we have multiple tests hitting port 8000 and the timing of the tests is different and so a collision is happening.

**Comment by crflanigan** [comment]
@powersj, 
Oooooh, ok, so you changed the naming so it would be more in line with Google verbiage?

**Comment by powersj** [comment]
exactly!

**Comment by crflanigan** [comment]
Hey @powersj, 

This appears to be working great!
We just tested having Instance specified in the Stackdriver resource label (which overwrites whatever is specified there), and commenting out the instance label:

```
[[outputs.stackdriver]]
  project = "sandbox"
  resource_type = "prometheus_target"
  #namespace = "casey" 
  metric_name_format = "official"
  metric_data_type = "double"
  metric_type_prefix  = "prometheus.googleapis.com" 
  tags_as_resource_label = ["instance"]
  [outputs.stackdriver.resource_labels]
    cluster = "onprem"
    job = "CaseyTest"
    # instance = "test"
    location = "us-east1-b"
    namespace = "store_pc_metrics"
  ```
  
  We are going to keep playing with it, but this feature looks great!

**Comment by crflanigan** [comment]
Hi @powersj,

I just noticed something when trying to use the following configuration:

Agent:
```
[inputs.mem]
  [inputs.mem.tags]
    job = "inputs.mem"

[inputs.processes]
  [inputs.processes.tags]
    job = "inputs.processes"
 ```
 
 Server (Values that are `{{}}` are hydrated by a key value store when Telegraf is deployed):
 
 ```
     # Configuration for sending metrics to GMP
    [[outputs.stackdriver]]
      project = "{{.PROJECT_ID}}"
      resource_type = "prometheus_target"
      metric_name_format = "official"
      metric_data_type = "double"
      metric_type_prefix = "prometheus.googleapis.com"
      tags_as_resource_label = ["instance", "job"]
      # Ignore metrics from inputs.internal
      namedrop = ["internal_*"]
      [outputs.stackdriver.resource_labels]
        cluster = "{{.CLUSTER_NAME}}"
        job = "Telegraf"
        instance = "{{.CLUSTER_NAME}}"
        location = "{{.LOCATION}}"
        namespace = "{{.NAMESPACE_LABEL}}"
  ```
  
  When I output to file from the client I see what's expected (tags are set as expected):
  
  ```
  mem,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.mem active=965160960i,available=1003286528i,used_percent=94.1601037979126,available_percent=5.839896202087402,inactive=954462208i,wired=693956608i,total=17179869184i,used=16176582656i,free=48824320i 1694460660000000000
processes,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes blocked=0i,zombies=1i,stopped=0i,running=3i,sleeping=428i,total=432i,unknown=0i,idle=0i 1694460660000000000
```
But when I look at the metrics in Google or Grafana I notice that it looks like the metrics are sometimes tagged with another inputs tag, IE `job=inputs.mem` but for a processes metric.

<img width="751" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/365dd2a1-9fa5-479f-a726-91e766ec1f36">

What do you think?
Should I open a new issue?

**Comment by crflanigan** [comment]
I'm also noticing that if you set a tag and configure the tag to be used as a resource label, and then you stop sending that tag it will remain for all new metrics. 

Example: I send metrics in with a job of inputs.mem. Then I stop the agent and start sending again without the job tag, it will persist. Then if I send another tag in it will change to that one for all new metrics.

<img width="1091" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/04f70b35-baeb-4e8f-b4de-6cdc6c4b882c">

**Comment by crflanigan** [comment]
My guess at what's going on is that the `tag_as_resource_label` sends the label using whatever the last applicable tag was in a batch. So if it gets a metric with a tag of `job="hamburgers"` it will send all the metrics in the batch with a label of `job="hamburgers"` even if there were metrics with a tag with the name `job="hotdogs". `

**Comment by powersj** [comment]
The resource labels are generated for each metric in a batch. See [here](https://github.com/powersj/telegraf/blob/8cde34bfebbd4d0ea8c7d9a091983cff77b7686d/plugins/outputs/stackdriver/stackdriver.go#L229-L235). This code is inside a for loop, going through each metric. The resource label is not reused in each loop either.

If debugging in stackdriver is difficult we could build a test version of telegraf to print exactly what resource label is used.

**Comment by crflanigan** [comment]
Sure, that would be great!

**Comment by powersj** [comment]
@crflanigan can you file a new issue as well and we can use that to work through this
