### ISSUE TITLE
feat: [outputs.datadog] to support submitting metrics alongside Datadog Agents

### ISSUE THREAD

**Issue by jdheyburn** [influxdata/telegraf#13561]
### Use Case

Some deployments of ours write to Datadog agents (via DogStatsD), others to telegraf (via inputs.statsd).

We would like the telegraf agent to be able to submit metrics to Datadog in a format that Datadog agent does already. Currently due to the way the telegraf output plugin for Datadog is implemented, they cannot run side-by-side.

@jrimmer-housecallpro Had already done some work in #10979 to do this, but stated in there that:

> Note that this behavior does *not* play
super-well if running simultaneously with current Datadog agents; they
will attempt to change to `Rate` with `interval=10`. We prefer this
method, however, as it reflects the raw data more accurately.

### Expected behavior

N/A

### Actual behavior

N/A 

### Additional info

I think it would it make sense to allow some flag in the datadog output config that would allow it to play nicely by:

- Allow interval to be configurable (or perhaps default to 10)
- Calculate the value of the metric from the interval
- Set metric type to be a rate

Example pseudo (ish) code:

```go
switch m.Type() {
  case telegraf.Counter:
    if d.ShouldPlayNicelyWithDatadogAgent() {
      interval = 10 // could pull this from config
      dogM[1] = dogM[1] / interval
      tname = "rate"
    } else {
      // this is the status quo
      interval = 1
      // no change to dogM
      tname = "count"
    }
  case telegraf.Gauge:
    tname = "gauge"
  default:
    tname = ""
}
metric := &Metric{
  Metric: dname,
  Tags: metricTags,
  Host: host,
  Type: tname,
  Interval: interval,
}
metric.Points[0] = dogM
```

**Comment by srebhan** [comment]
@jdheyburn given that you already show some code, would you be so kind to submit a PR?!?

**Comment by jdheyburn** [comment]
@srebhan Yes of course, I am just in the process of testing locally before I raise a PR for the same - assuming that other folks agree that this would be a useful addition 👍🏻

**Comment by techministrator** [comment]
Hi @jdheyburn, this is definitely useful. May I know have we got any progress of creating the PR for this yet?

**Comment by jdheyburn** [comment]
To close the loop, I won't be able to contribute to this. We are migrating off telegraf for this particular use case.

**Comment by powersj** [comment]
@techministrator,

If we continued to work on this would you be able to test a change?

@jdheyburn,

Thanks for following up. Did you have anything you could contribute?

**Comment by jdheyburn** [comment]
I'm starting to think that the above sawtooth is a bi-product of the metric being incorrectly displayed `as_count()`. Given that this is a rate metric, it should be displayed as such.

In either case, when you zoom out to a larger timeframe, Datadog aggregates (rolls up) the datapoints anyway, so switching between the two is indifferent.

As count:

![image-2024-1-16_19-9-23](https://github.com/influxdata/telegraf/assets/34041368/476cc3f0-c436-4fa2-aef8-883a0c414cdf)


As rate: 
![image-2024-1-16_19-9-46](https://github.com/influxdata/telegraf/assets/34041368/77bb8f96-9115-4e9f-a6a2-592ee3e1ee46)
