### ISSUE TITLE
postgres_extensible: allow specifying version upper bound

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#13568]
### Use Case

PostgreSQL 13 renamed fields in `pg_stat_statements` view: `total_time` - > `total_exec_time`.  There is already a way to specify minimal version to run query on, but it is not enough to handle this case. Upper version bound should be specified as well.

### Expected behavior

Maybe add a "semver" field  which accepts a string as a semver constraint? Something like "< 13.0" and deprecate `version` (which should be called `minversion`) in favour of it. Semver constraint can express arbitrary version constraints which should cover all the cases

### Actual behavior

-

**Comment by powersj** [comment]
next steps: rename `version` to `minVersion` and deprecate the old field. And create a new `maxVersion` field.

@redbaron is this something you would be interested in putting up a PR for?
