### ISSUE TITLE
[REG 2.6->2.7] Env variable expansion is not done when variable is empty

### ISSUE THREAD

**Issue by orgads** [influxdata/telegraf#13565]
### Relevant telegraf.conf

```toml
urls = ["http://${INFLUXDB_HOST}:8086/${INFLUXDB_PATH}"]
```

### Logs from Telegraf

```text
Wrote batch of 3 metrics in 205.779µs
Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.27.1

### Steps to reproduce

1. export INFLUXDB_HOST=influx
2. export INFLUXDB_PATH=''
3. Run telegraf

### Expected behavior

It should post to `/api/v2/write?bucket=mybucket&org=myorg`

### Actual behavior

It posts to `/$%7BINFLUXDB_PATH%7D/api/v2/write?bucket=mybucket&org=myorg`

### Additional info

InfluxDB responds with 200 OK and some HTML (on real write operation it's 204 with no content), so no error is detected.

**Comment by srebhan** [comment]
@orgads can you please test the binary in #13570 once CI finished the tests successfully!? Let me know if this fixes your issue!

**Comment by orgads** [comment]
Tested, and it fixes the issue. Thanks!

**Comment by srebhan** [comment]
Thanks for testing!
