### ISSUE TITLE
Issue with Stackdriver Plugin in Telegraf - Filtering Metrics based on User Labels

### ISSUE THREAD

**Issue by RahulKeluskar** [influxdata/telegraf#13571]
### Relevant telegraf.conf

```toml
# ------------------------------------------------------------------

# Main GCP metrics required for monitoring of issues and outages

# ------------------------------------------------------------------

[agent]

  debug = true

[[inputs.stackdriver]]

  project = "<>"

  metric_type_prefix_include = [
    "loadbalancing.googleapis.com/l3/external/egress_bytes_count",
    "loadbalancing.googleapis.com/l3/internal/egress_bytes_count",
    "loadbalancing.googleapis.com/l3/external/ingress_bytes_count",
    "loadbalancing.googleapis.com/l3/internal/ingress_bytes_count",
    "loadbalancing.googleapis.com/l3/external/egress_packets_count",
    "loadbalancing.googleapis.com/l3/external/ingress_packets_count",
    "loadbalancing.googleapis.com/l3/internal/rtt_latencies",
    "loadbalancing.googleapis.com/l3/external/rtt_latencies",
    "router.googleapis.com/nat/nat_allocation_failed",
    "router.googleapis.com/nat/allocated_ports",
    "router.googleapis.com/nat/port_usage",
    "router.googleapis.com/nat/open_connections",
    "router.googleapis.com/nat/sent_bytes_count",
    "router.googleapis.com/nat/received_bytes_count",
    "compute.googleapis.com/nat/allocated_ports",
    "compute.googleapis.com/nat/port_usage",
    "compute.googleapis.com/nat/open_connections",
    "logging.googleapis.com/user/",
    "logging.googleapis.com/log_entry_count",
    "dns.googleapis.com/query/response_count",
    "dns.googleapis.com/query/latencies",
    "compute.googleapis.com/instance/uptime",
    "networking.googleapis.com/cloud_netslo/active_probing/probe_count",
  ]
  #delay = "2m"
  interval = "2m"
  rate_limit = 50
  #window = "1m"

[[inputs.stackdriver.filter.user_labels]]
   key = "deployment"
   value = 'one_of("cf", "cf-cells-1")'

[[outputs.socket_writer]]
  address = "tcp://localhost:8094"
  data_format = "influx"
[[outputs.file]]
  files = ["stdout", "/tmp/metrics/metrics"]
  data_format = "influx"
```

### Logs from Telegraf

```text
E! [inputs.stackdriver] Failed iterating time series responses: "name:\"projects/<>\"  filter:\"metric.type = \\\"compute.googleapis.com/instance/uptime\\\" AND metadata.user_labels.\\\"deployment\\\" = \\\"cf\\\"\"  interval:{end_time:{seconds:1688554800}  start_time:{seconds:1688554790}}": rpc error: code = InvalidArgument desc = Field filter had an invalid value of "metric.type = "compute.googleapis.com/instance/uptime" AND metadata.user_labels."deployment" = "cf"": Resource metadata filters are only allowed on aligned metrics.
```

### System info

Telegraf 1.26.0

### Steps to reproduce

1. Set up a Telegraf instance with the Stackdriver plugin configured.
2. In the Telegraf configuration, define the following filter for user labels:
```
[[inputs.stackdriver.filter.user_labels]]
key = "deployment"
value = 'one_of(<user_labels_comma_separated>)'
```

### Expected behavior

1. The Stackdriver plugin in Telegraf should allow filtering metrics based on user labels.
2. When using the filter configuration in Telegraf, specifically `[[inputs.stackdriver.filter.user_labels]]`, the plugin should successfully filter metrics based on the specified user labels.

### Actual behavior

When attempting to filter metrics using the Stackdriver plugin in Telegraf, we encountered the following error:
E! [inputs.stackdriver] Failed iterating time series responses: "name:\"projects/<>\"  filter:\"metric.type = \\\"compute.googleapis.com/instance/uptime\\\" AND metadata.user_labels.\\\"deployment\\\" = \\\"cf\\\"\"  interval:{end_time:{seconds:1688554800}  start_time:{seconds:1688554790}}": rpc error: code = InvalidArgument desc = Field filter had an invalid value of "metric.type = "compute.googleapis.com/instance/uptime" AND metadata.user_labels."deployment" = "cf"": Resource metadata filters are only allowed on aligned metrics.
Which causes telegraf to fail.

### Additional info

1. We have successfully visualized the desired metrics on GCP's Stackdriver using the user label filter, taking the `uptime_total` metric as an example.
Cheking if the user labels exist on gcp:
![image](https://github.com/influxdata/telegraf/assets/29747506/65d2e07a-c731-4418-bf9d-54392f97f588)
Visualising the uptime_total metric on gcp:
![image](https://github.com/influxdata/telegraf/assets/29747506/1e6d4177-9bdc-4f95-82a6-75ef621e97b5)
![image](https://github.com/influxdata/telegraf/assets/29747506/8e1035e3-e603-4a79-a321-f2e631af4d02)

2. The metrics are visualized correctly when using the Stackdriver plugin in Grafana.
![image](https://github.com/influxdata/telegraf/assets/29747506/a110a364-9830-4a85-b908-6830a2a156d3)
(we want a similar visualisation with our config
3. However, when pushing metrics from Telegraf using the Stackdriver plugin, the filtering based on user labels does not work as expected, resulting in the aforementioned error.

Please let us know if you require any further information or clarification regarding this issue.

**Comment by powersj** [comment]
Hi,

> Field filter had an invalid value of "metric.type = "compute.googleapis.com/instance/uptime" AND metadata.user_labels."deployment" = "cf"
> Resource metadata filters are only allowed on aligned metrics.

This error is not from telegraf, but from the StackDriver client itself complaining that your metrics are not aligned.

It is not immediately clear to me why this message appeared. While you demonstrated something similar with grafana, I do not know enough about that plugin and how it compares to telegraf's usage of the stackdriver client either.
