### ISSUE TITLE
Implement ability to specify input precision in influxdb parser

### ISSUE THREAD

**Issue by btasker** [influxdata/telegraf#13600]
### Use Case

The `influxdb` line protocol parser expects that timestamps be provided using a nanosecond precision.

This works fine where the operator has control over the data being fed in (for example exec plugins), but can be problematic where LP is instead being pulled from a queue (MQTT, Kafka etc).

For example, those migrating to Telegraf from our Cloud2 MQTT Native Collector may be writing points with millisecond precision into their brokers (the collector exposed an option to override precision).

Telegraf will then pass these timestamps through unchanged resulting in points being recorded against the wrong time

Stand up a broker
We can build a simple testcase as follows
```sh
mkdir mosquitto/config -p
cat << EOM > mosquitto/config/mosquitto.conf
listener 1883 0.0.0.0
allow_anonymous true
log_dest stdout
EOM

docker network create telegraf_mqtt
docker run -it -d \
--rm \
--name=mosquitto \
--network=telegraf_mqtt \
-h mosquitto \
-p 1883:1883 -p 9001:9001 \
-v $PWD/mosquitto/config:/mosquitto/config \
eclipse-mosquitto
```

Then create a simple telegraf config to subscribe and stand up telegraf
```
cat << EOM > telegraf.conf
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  flush_interval = "5s"
  flush_jitter = "0s"
  debug = true
  quiet = false

[[inputs.mqtt_consumer]]
  servers = ["mosquitto:1883"]
  qos = 0
  connection_timeout = "30s"
  topics = ["testtopic/#"]
  data_format = "influx"
  max_undelivered_messages = 1500

[[outputs.file]]
   files = ["stdout"]
EOM

docker run \
--rm \
--name=mqtt_telegraf \
--network=telegraf_mqtt \
-h telegraf \
-v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf \
telegraf:latest
```

You should now be able to watch Telegraf's output with
```
docker logs -f mqtt_telegraf
```

Now, we want to write a point with ms into the broker
```sh
docker exec -it mosquitto \
mosquitto_pub -h 127.0.0.1 -t testtopic/helloworld -p 1883 -m "mymeasure,foo=bar value=1 1689057643544"
```

Telegraf's log should print the point back with the timestamp unchanged:
```text
2023-07-11T14:43:07Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
mymeasure,foo=bar,host=telegraf,topic=testtopic/helloworld value=1 1689057643544
```

The ideal would be if were possible to pass a `precision` to the influxdb parser (or perhaps even just be able to set against specific input types) so that the parser can adjust the timestamp's precision to ns.

### Expected behavior

The parser should convert to `ns` or otherwise adjust the points

### Actual behavior

The point is output without the timestamp changed

**Comment by powersj** [comment]
Thanks for the FR.

> The ideal would be if were possible to pass a precision to the influxdb parser (or perhaps even just be able to set against specific input types) so that the parser can adjust the timestamp's precision to ns.

The line protocol spec specifically calls out that timestamps are suppose to be in nanoseconds. Although it seems a lot of the influxdb tools have grown the ability to support different timestamp precisions.

This FR appears to essentially be https://github.com/influxdata/telegraf/pull/13419

Do you think that PR would do what you want?
