### ISSUE TITLE
Add s3 as an option for directory_monitor

### ISSUE THREAD

**Issue by zekena2** [influxdata/telegraf#13619]
### Use Case

I want to import files from s3 as I do it from the file system using the directory_monitor plugin. It might make sense to create a new plugin especially for object storage. Another feature is deleting these files. AFAIK the directory_monitor doesn't remove the files.

### Expected behavior

Either directory_monitor supports s3 URIs in `directory` config or a separate plugin that does the same thing.

### Actual behavior

I have to mount s3 in the same filesystem as telegraf in order to use s3 which is an unnecessary overhead.

**Comment by powersj** [comment]
Hi,

Let's talk through your use case a bit.

1. Would you want the user to provide a link to a specific bucket? Or a folder in a bucket? or either?
2. Once a file is read, would you want it to remain in the same bucket just a different folder? Or moved to a different bucket entirely?

The directory monitor plugin does filesystem level operations. Needing to duplicate the commands to the equivalent s3 commands in the same plugin seems error prone. 

This has come up before and is already an open feature reqeust in #6617. In that issue Thomas correctly points out that you can mount the bucket, but you say that is unnecessary overhead. I can understand the desire to skip that step.

In either case, I would prefer if we close this, track this in #6617, and if you want to really help, a proposed TOML of settings and answers the above would be very helpful.

**Comment by zekena2** [comment]
Fair enough I didn't know that this issue existed.

**Comment by powersj** [comment]
No worries, we can continue the conversation over there!

**Comment by srebhan** [comment]
@powersj one option would be to use https://rclone.org/ which has a Golang library providing filesystem-level abstractions. Not sure if this is sufficient, but it might be...
