### ISSUE TITLE
[inputs.jenkins] Jenkins node labels as metric tags

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#13626]
### Use Case

Jenkins supports to add labels to jenkins nodes (computers). This helps to add metadata to nodes like project or staging etc.. We need these labels also as metric tags to build useful queries for dashboards and alerts.

### Expected behavior

[[inputs.jenkins]] should supports a config parameter to activate scraping of these labels.

### Actual behavior

Currenlty [[inputs.jenkins]] ignores node labels.

### Additional info

Example output of `http://my-jenkins-instance:8080/computer/api/json?pretty=true`
As you can see, labels are included in Jenkins rest API Output. Labels key is named "assignedLabels" and presented as array.
(Removed some other objects of output)

```
{
  "_class" : "hudson.model.ComputerSet",
  "busyExecutors" : 10,
  "computer" : [
    {
      "_class" : "hudson.model.Hudson$MasterComputer",
      "actions" : [
        {
          
        }
      ],
      "assignedLabels" : [
        {
          "name" : "project14"
        },
        {
          "name" : "test_node"
        }
      ],
      "description" : "Jenkins Node01",
      "temporarilyOffline" : false
},
{
  "_class" : "hudson.model.ComputerSet",
  "busyExecutors" : 20,
  "computer" : [
    {
      "_class" : "hudson.model.Hudson$MasterComputer",
      "actions" : [
        {
          
        }
      ],
      "assignedLabels" : [
        {
          "name" : "project15"
        }
      ],
      "description" : "Jenkins Node02",
      "temporarilyOffline" : false
}
```

**Comment by 1tft** [comment]
A comma-seperated list sounds really good (regarding query possibilities).
Currently jenkins api output seems to sort labels alphatically. But to be always sure, that same labels (in different order) assigned by user (to jenkins nodes) produce always same line protocol tag, tag values should be (no matter how) sorted (because of cardinality issue).
When there aren no labels (or empty) by jenkins assigned I think a line protocol tag like `label="no_labels_set"` would be better than a missing label tag.

**Comment by powersj** [comment]
Hi,

I have put up https://github.com/influxdata/telegraf/pull/13649. In 20-30mins it should have artifacts attached that you can try out. Could you please give those a spin and let me know if the output looks good?

The new `node_lables_as_tag` config option needs to be set to `true`. Then a tag called `labels` is added, either with `none` for no labels or with a sorted, comma-separated list (e.g. `labels=label1,label2`).

Thanks!

**Comment by 1tft** [comment]
Thank you for that ultra fast PR. Will test it detailed with our Jenkins servers next week. Still found a typo issue: lables != labels

**Comment by 1tft** [comment]
Tested telegraf binary in our environment and found no issues. Thank you!
Maybe you can replace "," (used separator) within node Labels with "_". Dont know exactly if Jenkins allows "," within Labels but I found information that some special characters like "||" are allowed.
Replacing "," would harden the code.

**Comment by powersj** [comment]
> Replacing "," would harden the code.

Agreed, thank you for testing and confirming the fix!
