### ISSUE TITLE
docker input plugin should include info.RestartCount

### ISSUE THREAD

**Issue by shapiroj** [influxdata/telegraf#13645]
### Use Case

docker input plugin currently reports OOMKilled, pid, exitcode, and containerID for docker_container_status fields.   To make it easier to track restart counts it would be useful to also report the info.RestartCount. 

### Expected behavior

The value that is reported in docker inspect stitcher -f {{.RestartCount}} should be included as a field in the docker_container_status metric.

### Actual behavior

This field is not currently reported.

### Additional info

This should be a simple change.  The content is already in the info metric reported to the plugin.  It's just not extracted like the other fields.

**Comment by powersj** [comment]
Hi,

In 20-30mins, there should be artifacts attached to https://github.com/influxdata/telegraf/pull/13646 which adds the new restart_count field. Could you please download one of the artifacts, test it, and confirm this resolves your request?

Thanks!

**Comment by shapiroj** [comment]
Yes, confirmed the fix.  Thanks for the fast turnaround.
docker_container_status,container_image=sha256,container_name=modest_hertz,container_status=exited,container_version=370ea525bcdc5cdf2ae7bbd02ed9d40feec528555930e6bf5b99fdcb454d48ad,engine_host=myhost.com,server_version=20.10.18,finished_at=1689260439621555748i,started_at=1689260428449854388i,uptime_ns=11171701360i,oomkilled=false,pid=0i,exitcode=0i,restart_count=0i,container_id="13cda58b11b3c5b186b6e99dc3b550186f7cdbad1ca0e8f8b328bc2c11f55c01" 1689786060000000000
