### ISSUE TITLE
Can't drop anything

### ISSUE THREAD

**Issue by sezanzeb** [influxdata/telegraf#13644]
Using

```ini
	[inputs.mqtt_consumer.tagdrop]
		topic = [ "*" ]
```

I don't get any output at all to the console anymore (via the `[[outputs.file]]`) plugin. Using `device = [ "*" ]` to drop the "device" tag from the input also prevents telegraf from logging anything to stdout. No matter what I do, I just can't get telegraf to remove anything.

I tried to get this to work for probably an hour now... I'm sorry that I have to ask such a trivial question here. But on the other hand I would have expected that removing a tag or field would be extremely easy to do. If this was python or javascript it would have been solved with a single line of something like `del datapoint["topic"]`. I'm tempted to think that telegraf is buggy considering this.

Here is the complete configuration.

```ini
[[inputs.mqtt_consumer]]
	servers = ["mqtt://broker:1883"]
	topics = [ "#" ]
	data_format = "json_v2"

	[[inputs.mqtt_consumer.topic_parsing]]
		topic = "foo/+/+"
		measurement = "_/_/measurement"
		tags = "_/serial/_"

	[[inputs.mqtt_consumer.json_v2]]
		[[inputs.mqtt_consumer.json_v2.tag]]
			path = "device"

		[[inputs.mqtt_consumer.json_v2.field]]
			path = "power1"
			type = "float"

	[inputs.mqtt_consumer.tagdrop]
		topic = [ "*" ]

[[outputs.file]]
	files = ["stdout"]
```

I just want to avoid writing the topic into the database...

And could telegraf please not automatically add a "topic" column to my database?

**Comment by powersj** [comment]
> [inputs.mqtt_consumer.tagdrop]
		topic = [ "*" ]

As [documented under metric selectors](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#selectors), tagdrop means that the *input* will drop all metrics that have a matching tag. In this case, a glob of everything, meaning you will produce no metrics. The fact that you did not see anything to the file output should have given you a hint.

If you want to drop a tag, look for a metric modifier, such as `tagexclude`, to drop a specific tag.

> If this was python or javascript it would have been solved with a single line of something like del datapoint["topic"]

The telegraf configuration file is not a programming language, it is a configuration. Please familiarize yourself with the [various options](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md).

Finally, this is the bug tracker and *not* for support. Next time please ask this question in our [Community Slack](https://influxdata.com/slack) or [Community Forums](https://community.influxdata.com/).

**Comment by sezanzeb** [comment]
> The telegraf configuration file is not a programming language, it is a configuration

Oh, right, my degree in computer science and years of experience as a developer were not enough to see that. Thank you!

https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#using-taginclude-and-tagexclude shows tagexclude in an input plugin, but it only had an effect when adding it to the output plugin by the way.

**Comment by sezanzeb** [comment]
And thanks for helping.
