### ISSUE TITLE
Add the PATCH method to the http output plugin

### ISSUE THREAD

**Issue by tulku** [influxdata/telegraf#13650]
### Use Case

When sending information to a 'REST oriented' API, sometimes the PATCH method is used when only partial updates to objects are done. In contrast, PUT is normally used to update entire entities (meaning that you should send more information than the info that just changes).

When writing the endpoint that we are interacting with I guess it's not terrible to use PUT instead of PATCH, but this is not always an option.

### Expected behavior

Be able to use PATCH when sending data to an HTTP endpoint.

### Actual behavior

The plugin currently offers the option to use the POST and the PUT HTTP verbs, but not PATCH:
https://github.com/influxdata/telegraf/blob/21ab457923c8d3a047ade166e5e834b6a47ecfc3/plugins/outputs/http/http.go#L88

### Additional info

Thanks!

**Comment by powersj** [comment]
@tulku thanks for the feature request

In 20-30mins, can you please download one of the artifacts on https://github.com/influxdata/telegraf/pull/13651 and test that the "PATCH" method now works?

Thanks!

**Comment by tulku** [comment]
Hi @powersj Thanks for implementing this so quickly!

I just tested the code in the PR and works as expected. I used the following config:
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "1ns"
  debug = false
#   hostname = 
  omit_hostname = false

# # Read metrics about cpu usage
[[inputs.cpu]]
  alias = "cpu"
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = false
  ## If true and the info is available then add core_id and physical_id tags
  core_tags = false
  [inputs.cpu.tags]
    bucket_name = "monitoring"

# Collect statistics about itself
[[inputs.internal]]
  alias = "telegraf-monitor"
  ## If true, collect telegraf memory stats.
  collect_memstats = true
  [inputs.internal.tags]
    bucket_name = "monitoring"

[[outputs.http]]
    # Example of information pushed to the API:
    # {
    # "data": [
    #     {
    #     "last_telemetry_timestamp": 1689871440.000225
    #     },
    #     {
    #     "last_telemetry_timestamp": 1689871440.000251,
    #     "version": "1.28.0-64c40a37"
    #     },
    #     {
    #     "last_telemetry_timestamp": 1689871440.000251,
    #     "version": "1.28.0-64c40a37"
    #     },
    #     {
    #     "last_telemetry_timestamp": 1689871440.000251,
    #     "version": "1.28.0-64c40a37"
    #     }
    # ]
    # }
    alias = "output_http_update_timestamp"
    ## URL is the address to send metrics to
    url = "https://webhook.site/ca420b71-d2c2-4c07-90c6-1d9a731d9efc"
    ## Timeout for HTTP message
    timeout = "5s"
    method = "PATCH"
    content_encoding = "identity"
    use_batch_format = true

    data_format = "json"
    json_timestamp_units = "1ns"
    json_transformation = '''
    {
        "data": [
            metrics.{
                "hostname": tags.hostname,
                "version": tags.version,
                "last_telemetry_timestamp": timestamp/1e9
            }
        ]
    }
    '''

    [outputs.http.headers]
        Content-Type = "application/json"
```

which sends some data to an endpoint in https://webhook.site/ using the PATCH verb, and worked perfectly.

Thanks again!

**Comment by powersj** [comment]
Thanks for confirming - I'll get Sven to review next week and this will land in 1.28 and the nightlies.
