### ISSUE TITLE
redistimeseries output plugin support add lables 

### ISSUE THREAD

**Issue by langlichong** [influxdata/telegraf#13658]
### Use Case

test with cpu input plugin 

configuration is below:

cpu input plugin is the default:
```
 [[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = false
  ## If true and the info is available then add core_id and physical_id tags
  core_tags = false
```
and redistimeseries is :
```
[[outputs.redistimeseries]]
  ## The address of the RedisTimeSeries server.
  address = "here is my redis stack server ip and port"

  ## Redis ACL credentials
  # username = ""
  # password = ""
  database = 1

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  # insecure_skip_verify = false
```
and processors.override ： only define a new name 
```
 [[processors.override]]
#   ## All modifications on inputs and aggregators can be overridden:
#   # name_override = "new_name"
#   # name_prefix = "new_name_prefix"
#   # name_suffix = "new_name_suffix"
#
#   ## Tags to be added (all values must be strings)
#   # [processors.override.tags]
#   #   additional_tag = "tag_value"
name_override = "cpu_metric"
```

then test ：
```
 telegraf  --config  telegraf_config_demo\redistimeseries.conf --test
```
get output : 
```
 cpu_metric,cpu=cpu11,host=xxxx usage_guest=0,usage_guest_nice=0,usage_idle=78.78787878787878,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=21.21212121212121 1690197560500000000
> cpu_metric,cpu=cpu-total,host=xxxx usage_guest=0,usage_guest_nice=0,usage_idle=95.22613065326634,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=1.0050251256281406,usage_user=3.7688442211055277 1690197560500000000
```
the remove --test , to write to redis , and in redis server found that each key has a additional prefix of 'cpu_metric_' , like 'cpu_metric_usage_nice' ,  'cpu_metrics_usage_user'

### Expected behavior

why add the processors.override 's  name_override as a key prefix  other than a  time-series lable 

### Actual behavior

in redis server found that each key has a additional prefix of 'cpu_metric_' , like 'cpu_metric_usage_nice' ,  'cpu_metrics_usage_user' etc.

**Comment by powersj** [comment]
> why add the processors.override 's name_override as a key prefix other than a time-series lable

Because you could easily have conflicts if you have metrics with he same field name.

```
metric value=42
foobar value=0.3343434
```

These two metrics would both report `value` without the metric name prefix, even though these are entirely different metrics. By appending the metric name you are "namespacing" the metric value.

The GitHub issues are for issues, if you have additional questions or concerns, my suggestion is to head over to the [forums](https://community.influxdata.com/) or [slack](https://influxdata.com/slack) where other folks can answer your questions.

Thanks!

**Comment by langlichong** [comment]
> 



> metrics with he same field name

firstly,thank you for your answer .  

i am new in iot field.

i do think that different metrics may be with the same field name , and if  they are different metric ,then they should be in different measurements , to one measurement like a relational table , all field names in the measurments should be  unique , if have same filed name , is that an design issue ?  

like cpu input plugin, there are no duplicate filed names in the outputs  , and each input plugin will to mapping only one measurements or metric (i think the two are all similar to  a table ), i do not understand that you  said will have same name files is an issue , in my case , the all fields output of cpu plugin are diffrent , and all fileds are just in one measurement (default name are cpu similar to a table),  the measurement name of cpu just like a context ,  i think in the "cpu" context ,there will no needs to add  prefix , imagine that (a table named cpu , and each its field name has a prefix of cpu , thus is strange) , may be some points i made mistake thus i had such think !

**Comment by powersj** [comment]
>  to one measurement like a relational table

I would suggest reading up on how redis, which is not a relational database at all, is structured and how metrics are stored there. This really is a question about "how does redis  store data".

See https://redis.com/ebook/part-1-getting-started/chapter-1-getting-to-know-redis/1-1-what-is-redis/1-1-1-redis-compared-to-other-databases-and-software/ as a start
