### ISSUE TITLE
fpm plugin takes too long

### ISSUE THREAD

**Issue by lunetics** [influxdata/telegraf#1366]
I got a problem with the phpfpm plugin. 

System: Freebsd 10.3-p4 / telegraf 1.0.0.b1 / influx 0.13

The log error gives alot of errors for the plugin:

```
2016/06/12 03:39:40 Output [influxdb] buffer fullness: 49 / 10000 metrics. Total gathered metrics: 6971. Total dropped metrics: 0.
2016/06/12 03:39:40 Output [influxdb] wrote batch of 49 metrics in 14.777082ms
2016/06/12 03:39:40 ERROR: input [phpfpm] took longer to collect than collection interval (5s)
2016/06/12 03:39:46 ERROR: input [phpfpm] took longer to collect than collection interval (5s)
2016/06/12 03:39:50 Output [influxdb] buffer fullness: 57 / 10000 metrics. Total gathered metrics: 7028. Total dropped metrics: 0.
2016/06/12 03:39:50 Output [influxdb] wrote batch of 57 metrics in 5.113372ms
2016/06/12 03:39:50 ERROR: input [phpfpm] took longer to collect than collection interval (5s)
2016/06/12 03:39:55 ERROR: input [phpfpm] took longer to collect than collection interval (5s)
2016/06/12 03:40:00 Output [influxdb] buffer fullness: 44 / 10000 metrics. Total gathered metrics: 7072. Total dropped metrics: 0.
```

But at least there is data in influxdb, but only every 15 seconds (config flush_interval=10s and interval=5s)

I'm using the fcgi connect type. Using it via the following direct connection to test, the status answer does take a fraction of a second:

https://www.thatsgeeky.com/2012/02/directly-connecting-to-php-fpm/

any idea what could be wrong?

**Comment by sparrc** [comment]
any debug ideas @kureikain ?

**Comment by kureikain** [comment]
@sparrc  Let me lookingto this. Thanks

**Comment by danielnelson** [comment]
I'm going to close this issue due to its age and lack of updates.  If you still are experiencing the issue then can you retest and update the report.
