### ISSUE TITLE
Update README docs to reflect flavours of Azure Data Explorer that are supported

### ISSUE THREAD

**Issue by ag-ramachandran** [influxdata/telegraf#13676]
### Use Case

There are multiple Azure Data explorer workloads that are available for customers to use. 

Updating the README helps customers see if Telegraf supports the use case they want. For examle telegraf plugin supports ADX on Azure, ADX on the synapse workload and ADX on Fabric

### Expected behavior

Updating the documentation removes ambiguity on the supported flavors

### Actual behavior

Updating the documentation removes ambiguity on the supported flavors

### Additional info

This is only a documentation update

**Comment by powersj** [comment]
Thanks for the issue + RP!

next steps: review PR
