### ISSUE TITLE
ssacli plugin for HP raid controller

### ISSUE THREAD

**Issue by csupi003** [influxdata/telegraf#13674]
### Use Case

I would like to get data from ssacli which is used with HP raid controller. 

### Expected behavior

Get status of the controller and disks

### Actual behavior

Currently there's no plugin for it. 

### Additional info

A great collection of available commands can be found here: https://gist.github.com/mrpeardotnet/a9ce41da99936c0175600f484fa20d03

**Comment by powersj** [comment]
Hi,

> Currently there's no plugin for it.

Is this something you are interested in contributing? It is rather difficult to write and maintain a plugin which we do not easy access to :)

One of the key things that would also be good to know is if the CLI could output in an easily parsable format like JSON?

Thanks
