### ISSUE TITLE
x509_cert input incorrectly validates Lets Encrypt certificates

### ISSUE THREAD

**Issue by mbhs-josh** [influxdata/telegraf#13687]
### Relevant telegraf.conf

```toml
#Reads metrics from a SSL certificate
[[inputs.x509_cert]]
interval = "1m"
  ## List certificate sources, support wildcard expands for files
  ## Prefix your entry with 'file://' if you intend to use relative paths
  sources = [
		"https://letsencrypt.org"
	]

  ## Only output the leaf certificates and omit the root ones.
  exclude_root_certs = false
```

### Logs from Telegraf

```text
2023-07-28T04:56:01Z D! [inputs.x509_cert] Invalid certificate 4001772137d4e942b8ee76aa3c640ab7
2023-07-28T04:56:01Z D! [inputs.x509_cert]   cert DNS names:    []
2023-07-28T04:56:01Z D! [inputs.x509_cert]   cert IP addresses: []
2023-07-28T04:56:01Z D! [inputs.x509_cert]   cert subject:      CN=ISRG Root X1,O=Internet Security Research Group,C=US
2023-07-28T04:56:01Z D! [inputs.x509_cert]   cert issuer:       CN=DST Root CA X3,O=Digital Signature Trust Co.
2023-07-28T04:56:01Z D! [inputs.x509_cert]   opts.DNSName:      
2023-07-28T04:56:01Z D! [inputs.x509_cert]   verify options:    { 0xc0018272c0 <nil> 0001-01-01 00:00:00 +0000 UTC [0] 0}
2023-07-28T04:56:01Z D! [inputs.x509_cert]   verify error:      x509: certificate signed by unknown authority
2023-07-28T04:56:01Z D! [inputs.x509_cert]   tlsCfg.ServerName: 
2023-07-28T04:56:01Z D! [inputs.x509_cert]   ServerName:
```

### System info

Telegraf 1.26, Windows Server 2016

### Steps to reproduce

1. Use the `x509_cert` input to monitor a website that uses a Lets Encrypt certificate. Eg, https://letsencrypt.org

### Expected behavior

The root signing certificate for Lets Encrypt `ISRG Root X1` is cross signed by:
1. Self signed
2. `DST Root CA X3`

This results in the certificate having two possible chains of trust to evaluate the validity of the certificate. One chain is valid, one chain is not.

**Chain 1 - valid**
1. `ISRG Root X1`
2. `R3`
3. `lencr.org`

**Chain 2 - Invalid**
1. `DST Root CA X3`
2. `ISRG Root X1`
3. `R3`
4. `lencr.org`

See https://letsencrypt.org/certificates/ for further details.

I expect that the `x509_cert` input would detect that multiple chains exist for the certificate and return the first valid chain.

Alternatively, I would expect that both chains be reflected in the output. Optionally, with a config option to ignore invalid chains when multiple chains are present.

### Actual behavior

Only one certificate chain is shown in the output.

1. `DST Root CA X3` [missing from output]
2. `ISRG Root X1` [intermediate - invalid]]
3. `R3` [intermediate - valid]
4. `lencr.org` [leaf - valid]

**Comment by srebhan** [comment]
@mbhs-josh I'm not sure about your argumentation... Let's encrypt delivers [three certificates (attached)](https://github.com/influxdata/telegraf/files/12231717/cert-.zip) with the following content
1. `Subject: CN = lencr.org` and `Issuer: C = US, O = Let's Encrypt, CN = R3`
2. `Subject: C = US, O = Let's Encrypt, CN = R3` and `Issuer: C = US, O = Internet Security Research Group, CN = ISRG Root X1`
3. `Subject: C = US, O = Internet Security Research Group, CN = ISRG Root X1` and `Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3`

The first certificate is verified against the second one and then against  `ISRG Root X1` which is trusted in your system. Therefore, this certificate is reported as _valid_ by Telegraf.

The second certificate is verified against  `ISRG Root X1` which is trusted in your system. Therefore, this certificate is reported as _valid_ by Telegraf.

The third certificate is the cross-signing one, but `DST Root CA X3` is no longer valid and trusted by systems AFAICS. So the _issuer_ of the third certificate is "unknown" as Telegraf reports and thus the certificate is not valid.

I'm not sure what your expectation is but Telegraf does _NOT_ report verification chains per-se, it only reports if the certificates _received from a location_ are valid or not...

**Comment by mbhs-josh** [comment]
Thanks for your detailed reponse @srebhan.

I have spent some more time trying to fully understand how the x509_cert plugin functions and how cross signing works. I am quite confident now that my original interpreation of how it should function was wrong.

I was confused by the `exclude_root_certs` parameter and thought that it would include the corresponding root certificate from the system in the generated metrics. Therefore as both are applicable roots, I assumed that this meant that both the `ISRG Root X1` and `DST Root CA X3` root certificates should be included in the metric output. When only the `ISRG Root X1` certificate signed by `DST Root CA X3` was included I intrepeted that as a bug.

I realise now that this was wrong, as the metric output only includes the certificates returned from the specified source and does not also include the system root certificates. So where I had incorrectly assumed that the `ISRG Root X1`  root certificate was being retrieved from the system root certificates, it was actually being sent to us with the other intermediate certificates from Lets Encrypt.

**Comment by srebhan** [comment]
@mbhs-josh exactly. To be fair I also had to investigate in detail how Let's encrypt does the "backward compatibility" which is what the "DST" signed-cert is sent for. However, I agree that the option name `exclude_root_certs` is misleading and that option should rather be named `check_leaf_certs_only`. :-)

Shall we close the issue then?

**Comment by mbhs-josh** [comment]
@srebhan yes. I am happy to proceed with closing this issue.

Thanks again!
