### ISSUE TITLE
What timestamp does telegraf emit the metrics to influx db

### ISSUE THREAD

**Issue by samskan** [influxdata/telegraf#13688]
Timed stamp used for the metrics when emitted to influx

I am using the [[inputs.prometheus]] to fetch the data. And output looks like below
    [[outputs.socket_writer]]
      address = "tcp://127.0.0.1:8089"
      data_format = "influx"

With what timestamp does telegraf emit the metrics to influx? Where does it get the time stamp from?
Is there a way to use the timestamp when the metrics was emitted?

**Comment by powersj** [comment]
> With what timestamp does telegraf emit the metrics to influx? Where does it get the time stamp from?
Is there a way to use the timestamp when the metrics was emitted?

It depends on the input plugin and data source that you are collecting metrics from.

Please head over to the slack or forums and other can help out!
