### ISSUE TITLE
New input plugin: Linux KSM 

### ISSUE THREAD

**Issue by costasd** [influxdata/telegraf#13695]
### Use Case

Hello,

Linux Kernel has, since 2.6.32, a memory deduplication feature,called `Kernel Samepage Merging`, or `KSM` for short. See [here](https://www.kernel.org/doc/html/latest/mm/ksm.html) for the full details around it. It's primarily used in virtual machine environments, but may be used effectively in any environment that contains processes that might carry identical pages of memory.

In order to tune and monitor its operation and performance, Linux exports a set of metrics and knobs under sysfs, under `/sys/kernel/mm/ksm`, with each metric contained in a single file.
e.g.
```
/sys/kernel/mm/ksm/pages_shared
    how many shared pages are being used

$ cat /sys/kernel/mm/ksm/pages_shared
1234
```
See [ksm sysfs](https://www.kernel.org/doc/html/latest/admin-guide/mm/ksm.html) for the full list of metrics/knobs.

I believe it'd be great to have support in telegraf for ingesting these metrics, as they're useful for tracking how different parameters affect deduplication and its performance, especially in memory-constrained or overcommitted environments.

### Expected behavior

No expectations, checked if there's support for ingesting KSM metrics in Telegraf.

### Actual behavior

No support exists currently.

**Comment by powersj** [comment]
next steps: continue to review PR
