### ISSUE TITLE
InfluxDB plugin: remove 'IF NOT EXISTS' from 'CREATE DATABASE'

### ISSUE THREAD

**Issue by alexzorin** [influxdata/telegraf#1370]
InfluxDB > 0.13 will no longer parse 'IF NOT EXISTS' (and is currently ignoring it) - (https://github.com/influxdata/influxdb/issues/5707).

This affects the Telegraf InfluxDB plugin (https://github.com/influxdata/telegraf/blob/204ebf6bf624bd022f2a2971c00c349ac9c4f338/plugins/outputs/influxdb/influxdb.go#L150). Making this change, behavior will remain the same for InfluxDB 0.10 and newer, not sure about older.

**Comment by arthtux** [comment]
:+1: 
in log on influxdb
`WARNING: IF NOT EXISTS is deprecated as of v0.13.0 and will be removed in v1.0`

**Comment by arthtux** [comment]
#1409 I delete create database reference in plugins/output/influxdb

**Comment by danielnelson** [comment]
Closing, the `IF NOT EXISTS` part is no longer in the current influxdb output.
