### ISSUE TITLE
FIPs compliance

### ISSUE THREAD

**Issue by christienolson** [influxdata/telegraf#13716]
### Please direct all support questsions to slack or the forums. Thank you.

This was asked in https://github.com/influxdata/telegraf/issues/8363, but curious if there's any on the upcoming roadmap for addressing FIPs compliance

**Comment by powersj** [comment]
@christienolson,

To my knowledge, Telegraf can certainly run in a FIPS enabled system. Are you after metrics about the system running in FIPS mode? Or are you after ensuring that Telegraf is certified as FIPS 140-2 compliant and at a certain level for example? Or something else?

Thanks

**Comment by christienolson** [comment]
@powersj - the latter - if Telegraf is (_or will be_) FIPS compliant.
