### ISSUE TITLE
OTLP Input Data Format

### ISSUE THREAD

**Issue by lhns** [influxdata/telegraf#13726]
### Use Case

I would like to consume otlp metrics/traces/logs from a kafka topic directly. This would make metrics open telemetry based metrics pipelines much more robust against dropped metrics.

### Expected behavior

I would expect there to be an `otlp` data_format in the future.

### Actual behavior

Currently there doesn't seem to be any support for otlp as an [Input Data Format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md)

**Comment by powersj** [comment]
Hi,

We have the `opentelemetry` input plugin today and it appears to use the https://github.com/influxdata/influxdb-observability/tree/main/otel2influx library to convert open telemetry metrics into line protocol. I could possibly see us adding that as a parser versus needing to parse the messages with the json or xpath parsers.

@jacobmarble do you have any thoughts on adapting the otel2influx repo as a parser for otel data from other inputs?

Thanks

**Comment by lhns** [comment]
Hi, thanks for your response! The input plugin is what I am currently using. But I noticed that when I am backfilling data after an outage telegraf might get overwhelmed and will start dropping data. Using kafka I would expect the system to ingest data at its own pace.

**Comment by neelayu** [comment]
Hey @powersj 
OTLP parser would also be a useful feature.

**Comment by srebhan** [comment]
@lhns and @neelayu you could use the OLTP protocol-buffer file(s) and the `xpath_protobuf` parser. Any issue with this?

**Comment by jacobmarble** [comment]
> We have the `opentelemetry` input plugin today and it appears to use the https://github.com/influxdata/influxdb-observability/tree/main/otel2influx library to convert open telemetry metrics into line protocol. I could possibly see us adding that as a parser versus needing to parse the messages with the json or xpath parsers.
> 
> @jacobmarble do you have any thoughts on adapting the otel2influx repo as a parser for otel data from other inputs?

(11.75 months late, I know...)

That sounds fine. There are tests in influxdata/influxdb-observability to ensure that neither Telegraf nor otelcol-contrib breaks, so it's pretty safe to refactor within that repository.

**Comment by srebhan** [comment]
@jacobmarble I think we could also directly parse the protobuf message with the corresponding [OTLP protobuf definitions](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/collector). The [XPath parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath) can then be used to extract the desired information into a metric.
