### ISSUE TITLE
Prometheus Input : Metrics_version = 1 appending _gauge or _counter at the end of metrics name 

### ISSUE THREAD

**Issue by pmathur231** [influxdata/telegraf#13732]
### Relevant telegraf.conf

```toml
[[outputs.prometheus_client]]
  listen = ":9237"
  path = "/metrics"
  export_timestamp = true



[[inputs.prometheus]]
  urls = [
    "http://<server_link>:9236/metrics"
  ]
  metric_version = 1

  [inputs.prometheus.tags]
    instance="<>"
    job="<>"
```

### Logs from Telegraf

```text
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Loaded inputs: prometheus (2x)
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Loaded aggregators:
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Loaded processors:
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Loaded secretstores:
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Loaded outputs: http prometheus_client
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! Tags enabled: host=<>
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"<>", Flush Interval:10s
Aug  7 14:37:50  telegraf[3791700]: 2023-08-07T19:37:50Z I! [outputs.prometheus_client] Listening on http://0.0.0.0:9237/metrics
```

### System info

Telegraf 1.25, Linux server

### Steps to reproduce

Use the telegraf config shared above and access metrics in Grafana . metrics_version=1 isn't outputting exact name , instead its appending gauge or counter at the end of metrics name

Example - 
gitaly_authentications_total is converted to gitaly_authentications_total_counter

### Expected behavior

All metrics pulled should have exact names with no appends

### Actual behavior

Example - 
gitaly_authentications_total is converted to gitaly_authentications_total_counter
gitaly_catfile_processes is converted to gitaly_catfile_processes_gauge

### Additional info

Using metrics_version=2 is giving me Duplicate timestamp error with certain metrics. Its an issue with Histogram i guess. so i am trying to make metrics_version=1 work for me.

**Comment by powersj** [comment]
Hi,

If I use the following metrics file:

```s
# HELP go_memstats_heap_alloc_bytes Notes.
# TYPE go_memstats_heap_alloc_bytes counter
gitaly_authentications_total 42
# HELP gitaly_catfile_processes Notes.
# TYPE gitaly_catfile_processes gauge
gitaly_catfile_processes 44
```

I see the following metric in line protocol format:

```
gitaly_authentications_total,instance=<>,job=<>,url=http://0.0.0.0:8000/metrics value=42 1691671980000000000
gitaly_catfile_processes,instance=<>,job=<>,url=http://0.0.0.0:8000/metrics gauge=44 1691671980000000000
```

and navigating to prometheus endpoint see:

```s
# HELP gitaly_authentications_total Telegraf collected metric
# TYPE gitaly_authentications_total untyped
gitaly_authentications_total{instance="<>",job="<>",url="http://0.0.0.0:8000/metrics"} 42 1691671980000
# HELP gitaly_catfile_processes Telegraf collected metric
# TYPE gitaly_catfile_processes gauge
gitaly_catfile_processes{instance="<>",job="<>",url="http://0.0.0.0:8000/metrics"} 44 1691671980000
```

I am not seeing the same suffix as you. Can you provide your metrics file or provide me with enough to reproduce? Looking at the code the v1 does not seem to touch the metric name [during parsing](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/parser.go#L87).

**Comment by pmathur231** [comment]
Thanks for responding !

```
It's very strange that I see no issues when accessed prometheus endpoint on the browser 
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 77054.3
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 15000
```

but in Grafana , metrics name are appended with either _counter or _gauge values. 

![image](https://github.com/influxdata/telegraf/assets/119896476/cd82f3c4-7975-4c12-a49b-24c8a28fd560)


Regards

**Comment by powersj** [comment]
Hi,

I would look into whatever is scraping your endpoint. Sounds like it is occurring after telegraf produces metrics, not as a result of telegraf.

**Comment by pmathur231** [comment]
prometheus exporter is scraping the metrices. here is the yml file 

`global:
  scrape_interval: 15s
  scrape_timeout: 15s
  external_labels:
    gl_host: <>
    gl_env: prod_s3b_geo
    gl_layer: git
remote_read: []
remote_write:
- url: <>
  basic_auth:
    username: <>
    password: <>
rule_files:
- "/var/opt/gitlab/prometheus/rules/*.rules"
scrape_configs:
- job_name: prometheus
  metrics_path: "/metrics"
  scheme: http
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - <instance>:9090
- job_name: gitaly
  metrics_path: "/metrics"
  scheme: http
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - <instance1>:9236
    - <instance2>:9236
    - <instance3>:9236
alerting:
  alertmanagers: []`

Pls note prometheus is giving correct results in Grafana when active, keeping Telegraf turned off.

**Comment by powersj** [comment]
You lost me :) If you navigate to the endpoint at it shows the correct names, how is this a telegraf issue?

**Comment by pmathur231** [comment]
I had forgotten to mention that this occurs only when we go with metric_version=1. With metric version = 2 , metrics name are showing up correctly

**Comment by powersj** [comment]
> I had forgotten to mention that this occurs only when we go with metric_version=1

ok but again, if the metrics show up at the endpoint correctly, what is there for telegraf to do? I need a way for you to help me reproduce this and demonstrate the telegraf is appending these values.

**Comment by pmathur231** [comment]
So I added [outputs.file] and can see _counter and _gauge being appended to prometheus output 
Config added to telegraf.conf - 

[[outputs.file]]
  files = ["stdout","<filename>"]
  prometheus_export_timestamp = true
  data_format = "prometheus"

Sample output from file - 
geo_merge_request_diffs_synced_gauge
ruby_gc_stat_total_freed_pages_gauge
gitlab_external_http_total_counter
gitlab_transaction_db_count_total_counter

Pls share what you think 
Thanks !

**Comment by powersj** [comment]
> data_format = "prometheus"

The serializer has a function called `Add` which will create the metric name based on the metric name + field + type as [seen here](https://github.com/influxdata/telegraf/blob/master/plugins/serializers/prometheus/collection.go#L186).

In your case you are trying to pass prometheus data in as the same as prometheus data out. However, the serializer has no idea where the source data is from and as such it will attempt to create the new metric name in the style of prometheus, specifically `measurement_field_type`. So I do not consider this is an issue or something we would change.

Now if you were to use `metric_version=2`, where a `prometheus` metric is created, there is [an exception in the serializer](https://github.com/influxdata/telegraf/blob/master/plugins/serializers/prometheus/convert.go#L121-L124) that will return only the field key and produce identical metric names. This is probably what you want from the start.

You mentioned having issues with timestamps and that is something I would suggest asking for help on our [forums](https://community.influxdata.com/) or [slack](https://influxdata.com/slack) where others could help you out.

**Comment by pmathur231** [comment]
Seems like your slack channel is Private, its not accessible. Is there any public telegraf slack channel which I can be part of ?

**Comment by powersj** [comment]
Hmm seems the link expired. I'll ask internally what is up.

**Comment by powersj** [comment]
Hi,

Slack link was renewed: https://influxdata.com/slack

Give it a shot!
