### ISSUE TITLE
[FEATURE] ability to control type of datetime column in postgresql output

### ISSUE THREAD

**Issue by jcpunk** [influxdata/telegraf#13747]
### Use Case

Currently the postgreql column for datetime is hard coded to `PgTimestampWithoutTimeZone`.  This is problematic when I'm attempting to use timezone specific date sources.

### Expected behavior

Ability to specify timestamp column should contain a timezone.  And the ability to force a specific timezone (ie UTC or America/Chicago) to be used.  When reading in unix timestamps the documented behavior for telegraf is to omit the timezone which can lead to data confusion.

### Actual behavior

Hard coded to contain no timezone

### Additional info

Location of hard coded data type:
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/postgresql/datatypes.go#L56

Note on query issues:
> If a time zone is specified in the input for time without time zone, it is silently ignored.

from https://www.postgresql.org/docs/current/datatype-datetime.html

**Comment by srebhan** [comment]
@jcpunk I'm not completely sure I can follow the problem you have with timezones. Currently, the time column is _always_ in UTC (see [code](https://github.com/influxdata/telegraf/blob/1381513e61c765911f1f0e488410c0b01560c228/plugins/outputs/postgresql/table_source.go#L264)) so the stored time is _always_ representing the time of your metric.

Is there any specific reason you do _not_ want to use UTC for storing the data?  I strongly recommend against this as you easily run into issues with day-light-saving time-zones...

**Comment by srebhan** [comment]
> I can live with converting my messages to UTC.

You don't need to do this as the output does it for you. It takes the metric timestamp and stores it in UTC in the database. So in my understanding, all you need to do is to make sure the timestamp in your queries is also UTC...

**Comment by jcpunk** [comment]
Unfortunately I don't have great control over the query being sent.  It really wants to use local time and expects the database to "do the right thing".  With the column dropping the timezone, my return results are usually about 6 hours off due to my local TZ.

**Comment by srebhan** [comment]
Understood. Will care for it.

**Comment by srebhan** [comment]
@jcpunk please test PR #13763! It also contains the time-column renaming PR (#13750).
