### ISSUE TITLE
Telegraf is not starting

### ISSUE THREAD

**Issue by KxmischerLasse** [influxdata/telegraf#13757]
### Relevant telegraf.conf

```toml
Default config
```

### Logs from Telegraf

```text
× telegraf.service - Telegraf
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-08-13 13:00:30 CEST; 37min ago
       Docs: https://github.com/influxdata/telegraf
   Main PID: 681 (code=exited, status=1/FAILURE)
        CPU: 131ms

Aug 13 13:00:30 HOSTNAME systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Aug 13 13:00:30 HOSTNAME systemd[1]: Stopped telegraf.service - Telegraf.
Aug 13 13:00:30 HOSTNAME systemd[1]: telegraf.service: Start request repeated too quickly.
Aug 13 13:00:30 HOSTNAME systemd[1]: telegraf.service: Failed with result 'exit-code'.
Aug 13 13:00:30 HOSTNAME systemd[1]: Failed to start telegraf.service - Telegraf.
```

### System info

Telegraf 1.27.3, Debian 12 and Ubuntu 22.04

### Steps to reproduce

1.Install Telegraf on Debian 12 or Ubuntu 22.04
2. run systemctl status telegraf

### Expected behavior

Telegraf should start

### Actual behavior

telegraf doesnt start

### Additional info

i have the issue on debian 12 and ubuntu 22.04

**Comment by powersj** [comment]
> Default config

The default config does not come with an output configured. So it will not start. That is up to you to configure.

> Logs from Telegraf

These are not the logs from telegraf ;) You provided the output of `systemctl status telegraf`. What you should look at, are the actual logs via: `journalctl --no-pager --unit telegraf`.

Closing this as not starting by default is the correct behavior.

**Comment by Omkar8284** [comment]
ul 25 23:05:32 omkar systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jul 25 23:05:32 omkar systemd[1]: Failed to start Telegraf.
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 4.
Jul 25 23:05:32 omkar systemd[1]: Stopped Telegraf.
Jul 25 23:05:32 omkar systemd[1]: Starting Telegraf...
Jul 25 23:05:32 omkar telegraf[134147]: time="2024-07-25T23:05:32+05:30" level=warning msg="DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null." func="gosnowflake.(*defaultLogger).Warn" file="log.go:244"
Jul 25 23:05:32 omkar telegraf[134147]: 2024-07-25T17:35:32Z I! Loading config: /etc/telegraf/telegraf.conf
Jul 25 23:05:32 omkar telegraf[134147]: 2024-07-25T17:35:32Z I! Loading config: /etc/telegraf/telegraf.d/system.conf
Jul 25 23:05:32 omkar telegraf[134147]: 2024-07-25T17:35:32Z E! error loading config file /etc/telegraf/telegraf.d/system.conf: error parsing data: line 128: invalid TOML syntax
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jul 25 23:05:32 omkar systemd[1]: Failed to start Telegraf.
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Jul 25 23:05:32 omkar systemd[1]: Stopped Telegraf.
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Start request repeated too quickly.
Jul 25 23:05:32 omkar systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jul 25 23:05:32 omkar systemd[1]: Failed to start Telegraf.

**Comment by igorKur** [comment]
Logs from Telegraf

Mar 16 13:38:00 DESKTOP-M7UUS00 systemd[1]: Started telegraf.service - Telegraf.
Mar 16 13:38:01 DESKTOP-M7UUS00 telegraf[3537]: 2025-03-16T10:38:01Z I! Loading config: /etc/telegraf/telegraf.conf
Mar 16 13:38:01 DESKTOP-M7UUS00 telegraf[3537]: 2025-03-16T10:38:01Z I! Loading config: /etc/telegraf/telegraf.d/IP.conf
Mar 16 13:38:01 DESKTOP-M7UUS00 telegraf[3537]: 2025-03-16T10:38:01Z E! loading config file /etc/telegraf/telegraf.d/IP.conf failed: error pars>
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Killing process 3550 (dbus-daemon) with signal SIGKILL.
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Start request repeated too quickly.
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 16 13:38:01 DESKTOP-M7UUS00 systemd[1]: Failed to start telegraf.service - Telegraf.

What is the problem and how to fix it?

**Comment by igorKur** [comment]
System info
Telegraf 1.34, InfluxDB v2.7.11, Debian 12 and Ubuntu 24.04.1 LTS

Docker
No response

Steps to reproduce
1.Install Telegraf on Debian 12 or Ubuntu 22.04
2. run systemctl status telegraf

Expected behavior
Telegraf should start

Actual behavior
telegraf doesnt start

Additional info
i have the issue on debian 12 and ubuntu 22.04

**Comment by KxmischerLasse** [comment]
have you added an telegraf config?

**Comment by igorKur** [comment]
yes

**Comment by igorKur** [comment]
Extract from the sample

 journalctl -u telegraf

**Comment by igorKur** [comment]
/etc/telegraf/telegraf.d/dts.conf

  GNU nano 7.2                                            /etc/telegraf/telegraf.d/dts.conf                                                     # Configuration for telegraf agent
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://172.24.156.164:8086"]
  token = "qJBSUQ93ea83tCv7OJ7npQ0BKhVQxQgy5DS4_Ghf_yPjkwS6y0l_2s0QXooWvvkoGORHLxQwxbQ==" // changed
  organization = "dts"
  bucket = "dts"

[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.99.20:1883"]
  topics = ["#"]
  username = "IoT"
  password = "dts6413"
  data_format = "value"
  data_type = "float"

**Comment by igorKur** [comment]
/etc/telegraf/telegraf.conf

 interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Collection offset is used to shift the collection by the given amount.
  ## This can be be used to avoid many plugins querying constraint devices
  ## at the same time by manually scheduling them in time.
  # collection_offset = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"


 [ Read 14004 lines ]
