### ISSUE TITLE
No repository available for Debian 12 (bookworm)

### ISSUE THREAD

**Issue by CMoH** [influxdata/telegraf#13759]
### Please direct all support questsions to slack or the forums. Thank you.

[Debian 12.1 (bookworm) was released on July 22nd, 2023](https://www.debian.org/releases/bookworm/), but the InfluxData repositories at https://repos.influxdata.com/debian/dists/ do not cover this new release.

Is a release for Telegraf on Debian bookworm planned already? When can we expect this version to be supported by InfluxData?

**Comment by powersj** [comment]
Please use the instructions found on the README, which directs users to use the "stable" repo. Telegraf is a static go binary, so there is no difference in the binaries between each Linux package. In fact, each package is the same just for each release of Debian.

Closing as we do not create different packages and do not wish to continue adding release-specific folders.

**Comment by CMoH** [comment]
If others bump into this, apparently my ansible debian playbook held the (possibly erroneous) line 

```
apt_repository:
-    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
```

and I changed it to

```
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} stable main"
```

Seems to work. Well, time to upgrade the older systems.
