### ISSUE TITLE
Add option to verify configuration

### ISSUE THREAD

**Issue by UweSauter** [influxdata/telegraf#13782]
### Use Case

This is a follow-up to #13781.

Currently Telegraf does not show its configuration if executed with `--debug`. I'm also not aware of another way to check if Telegraf did parse the configuration correctly.

### Expected behavior

Having something like `telegraf verify --config $FILE` that then shows the configuration hierarchy would allow to find misconfigurations more easily. This could be a one-shot command that exits after showing the configuration.

An alternative could be to add `--show-config` which would log the same information on program start and whenever a configuration change is detected (if `--watch-config` is used).

### Actual behavior

Command `verify` and option `--show-config` are both not available.

**Comment by crflanigan** [comment]
Hello @UweSauter, 

I think you might be looking for this:

`./telegraf --config telegraf.conf --test`

This will start Telegraf, use a target config, and generate some output.

**Comment by UweSauter** [comment]
Hi @crflanigan.

No. I'm aware of that but that only helps with input plugins. `--test` is of no use for the other plugins because they are might be initialized but the are not used and thus misconfigurations for those plugins cannot be detected.

I'd like Telegraf to show the whole configuration (for all enabled plugins) so that configuration errors can be easily found.

The reason why I think this is needed is explained in #13781.

**Comment by powersj** [comment]
Hi,

While the issue you had in #13781 is unfortunate, it really comes down to TOML syntax and we can work to fix up the sample configurations in that issue.

Telegraf's method for validating a config is with `--test` or `--once`.

As @crflanigan suggested, `--test` is a great first way to verify that your config is working, with respect to everything except the outputs. To use the outputs, using `--once` is what we recommend as it would run the entire config for a full collection and flush cycle. While this also has some shortcomings when using service inputs it is currently the best option.

With a new option, you may have spotted that your output was using a different data format, but most users would not have picked up that it was missing in the first place, especially as a configuration grows and grows. The more expedient method is to use `--once` and ensure the value at the output.

To properly validate a config in the first place we would need to run each plugin's `Init` and in some cases even do a cycle of `Gather` or `Write`. This essentially means running `--once`. When we load the configuration files we do not load them into one master config but rather take the AST and create the various plugins by type (e.g. inputs, outputs, aggregators, etc.) and apply any top-level settings. Marshaling the newly created plugins back into output after already running all the plugins is essentially running with `--test` or `--once` with extra output.

**Comment by Hipska** [comment]
@UweSauter Check out v1.32.0 which now has a command to actually check the config. See https://github.com/influxdata/telegraf/pull/15732
