### ISSUE TITLE
Support Nacos input plugins.

### ISSUE THREAD

**Issue by stone-98** [influxdata/telegraf#13788]
### Use Case

Nacos is an open-source service discovery and configuration management platform. It provides the capabilities of both a service registry and a configuration center. In a distributed system, Nacos helps services register and discover each other, enabling dynamic service discovery. Additionally, it allows for centralized management of configurations, making it easier to update and synchronize configurations across multiple services.

As for its user base, Nacos has gained considerable popularity among developers and organizations worldwide. Many users rely on Nacos to simplify their service registration and discovery processes, leading to its widespread adoption in various industries and projects.

Now Telegraf does not support Nacos input plugins, hope Telegraf can support it.

link: https://github.com/alibaba/nacos

### Expected behavior

Support Nacos input plugins.

### Actual behavior

Now Telegraf does not support Nacos input plugins.

**Comment by powersj** [comment]
Hi,

What exactly would you like telegraf to support with respect to Nacos? Have it gather metrics from the service itself? If so, what API do you want us to hit and what clients are available and what metrics are interesting?

Thanks

**Comment by stone-98** [comment]
Official document link: https://nacos.io/en-us/docs/v2/guide/admin/monitor-guide.html

**Comment by stone-98** [comment]
Can I create a pull request for this feature point?

**Comment by powersj** [comment]
> Currently, prometheus, elastic search and influxdb are supported.

It appears that it already supports pushing to influxdb directly already.

For the prometheus metrics, a user could use the existing prometheus input plugin as well.

What are you looking to gather that requires a new plugin?
