### ISSUE TITLE
telegraf.conf cannot be parsed if saved with notepad (UTF8 BOM)

### ISSUE THREAD

**Issue by StianOvrevage** [influxdata/telegraf#1378]
When editing telegraf.conf with notepad the file is encoded in UTF-8 BOM and telegraf cannot get past the BOM and quits with:

Error parsing telegraf.conf, toml: line 1: parse error

So, it would be nice to have the config loader/parser accept UTF-8 BOM encoded files.

**Comment by Pomyk** [comment]
http://utf8everywhere.org/#faq.boms

**Comment by sparrc** [comment]
Sorry @StianOvrevage but I have to agree with @Pomyk. I would recommend using Notepad++ which doesn't save with a BOM. It's a slippery slope to litter the codebase with special handling of little Windows-isms like this....

http://www.larshaendler.com/2015/01/20/remove-bom-with-notepad/

**Comment by StianOvrevage** [comment]
I understand from your point of view. But alas it is quite a hassle for Windows server operators to not be able to edit config files with any native Windows program, and I suspect to be a barrier to adoption and source of frustration.

**Comment by sparrc** [comment]
fair enough......I can make it skip the first byte in certain cases :/

**Comment by StianOvrevage** [comment]
You rock! :D

**Comment by stevebanik-ndsc** [comment]
The toml error also appears if the file is edited in Powershell ISE with psedit.  To get around the error in 1.5.2, I opened the .conf in Notepad++, converted to UTF-8 and saved the conf file.
