### ISSUE TITLE
Telegraf Plugin For Apache Druid

### ISSUE THREAD

**Issue by arunkumarck** [influxdata/telegraf#13797]
### Use Case

In an IoT scenario, where one is using Telegraf to persist data from RabbitMQ or Kafka to Postgres using telegraf,
it will be good to be able to write a plugin for Apache Druid and Use It.

### Expected behavior

I appreciate the fact that Telegraf is opensource and is related to Influx.
But keeping up the opensource spirit, can a plugin be written for Apcache Druid.

### Actual behavior

Persist Data into Apache Druid using Telegraf

**Comment by powersj** [comment]
Hi,

We are never opposed to adding new plugins, but the more information you provide the more likely it is to happen ;)

For example, what is the data format required to send data to Apache Druid? Are there any libraries we can use to do this that already exist in Go? What kind of options might a user need?

Additionally, as you mentioned this is an open source project, so we are always willing to see you contribute the code and work through a PR with you.

**Comment by arunkumarck** [comment]
You have a plugin to input from Kafka topics and write it to PostgresSQL.
Can we have a similar plugin from your end to input from Kafka and write to Apache Druid ?

* Individually, I am looking at persisting JSON data that is published to Kafka topics and persist the same to Apache Druid.
* But I believe this will be in most of the cases especially mobile applications and IoT Gateways

**Comment by arunkumarck** [comment]
Specifically, like the one you have written for influx db.
from google:
Telegraf has input and output plug-ins that must be configured upfront before starting it. For example, it has an Apache Kafka consumer input plug-in that makes it possible to read messages from a Kafka topic and an output plug-in that helps write any input data to InfluxDB

**Comment by powersj** [comment]
> Individually, I am looking at persisting JSON data that is published to Kafka topics and persist the same to Apache Druid.

Can you use the HTTP output with the JSON format?

You have not told me about any available clients that telegraf could use to talk to Apache Druid.

**Comment by arunkumarck** [comment]
I figured out that Druid has it's own software to ingest from Kafka and store in Druid which I will use https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion/

Meanwhile, if a Telegraf plugin is written, for outputting to Druid, Yes it will use HTTP.
Since Telegraf is written in GO, the vertical scaling might be better

**Comment by iercan** [comment]
I was also searching for this plugin, then I discovered there is influxdb emitter extension for druid. By using it, you can directly write metrics to influxdb without needing telegraf. See it here 

https://druid.apache.org/docs/latest/development/extensions-contrib/influxdb-emitter/
