### ISSUE TITLE
Telegraf post remove script doesn't work on AMZN AMIs

### ISSUE THREAD

**Issue by chebrolus** [influxdata/telegraf#1379]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

_Please note, the quickest way to fix a bug is to open a Pull Request._
## Bug report

When you run yum remove telegraf on Amazon Linux AMI it doesn't remove init script for telegraf.
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Amazon Linux
### Steps to reproduce:
1. Uninstall telegraf on Amazon Linux AMI
2. You will notice /etc/init.d/telegraf still exist and same is the case with chkconfig
### Expected behavior:

Expect all telegraf related scripts removed
### Actual behavior:

Still leave telegraf init script in /etc/init.d
### Additional info:

[Include gist of relevant config, logs, etc.]
## Feature Request

Opening a feature request kicks off a discussion.
### Proposal:

Install script does support Amazon Linux for these scripts and can follow similar conditional approach and remove telegraf related stuff in post remove

**Comment by schebrolu** [comment]
[PR #1381](https://github.com/influxdata/telegraf/pull/1381)

**Comment by sjwang90** [comment]
fixed
