### ISSUE TITLE
secrets with no secret store references should behave like plain strings

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#13807]
### Use Case

secretstore `memguard` is quite complicated, but it is invoked every time "secret-capable" config option is accessed even if there is no references to a secret store.

There is no value in "protecting" what essentially a plaintext string.

### Expected behavior

config parameters  with no secret store references should be short-circuit to a plaintext string, skipping `memguard `completely.

### Actual behavior

`memguard` is used every time config parameter with potential secret in it is accessed, even if there is no references to secret stores.

### Additional info

Memguard can be quite challenging to deal with:  #13804, #13806.  Skipping it entirely when it doesn't add any value simplifies telegraf setup.

**Comment by powersj** [comment]
next steps: similar to https://github.com/influxdata/telegraf/issues/13804, want to get on the same page with Sven and go through each of these.
