### ISSUE TITLE
Avro Parser: get metric name from the message

### ISSUE THREAD

**Issue by BelousovAntonV** [influxdata/telegraf#13823]
### Use Case

We are getting different metrics from the one Kafka topic. They have the same structure. but different data type of value and differen metric names.  So we have only 4 schemas and about 100 metrics at the moment. We want to take metric name dynamically, instead of hard coded value. 

### Expected behavior

The metric name could be taken from the message field.

### Actual behavior

Metric name could be hardcoded only.

### Additional info

We realized this change in the our solution by adding new option `avro_measurement_field` which if specified has a higher priority than the `avro_measurement option`

Ready for PR. Here is the description from the updated readme:

```
  ## Measurement field name; The meauserment name will be taken from this field
  ## If not set, determine measurement name from the following options
  # avro_measurement_field = "MeasureName"
```

**Comment by powersj** [comment]
> The metric name could be taken from the message field.

Is this config option then a path to the measurement field in the original data? Or is this field the telegraf field name itself? Do you drop the field afterwards?

As you can tell from my other response, this is borderline something that should be done in a processor and not in the parser.

**Comment by BelousovAntonV** [comment]
> Is this config option then a path to the measurement field in the original data?

Yes, it is the name of the field in the original message. It could be add as a metric field also if it will be specified in the `avro_fields` option, but by default it is used only for getting metric name dynamically instead of hard coded value.

**Comment by powersj** [comment]
Thanks for the response - I'm good with this if you want to put up a PR
