### ISSUE TITLE
Kafka_consumer: Add message headers as metric tags.

### ISSUE THREAD

**Issue by BelousovAntonV** [influxdata/telegraf#13822]
### Use Case

We are writing data to the topic using message headers for future filtering. We want to add message headers as tags to not duplicate them in the message internally.

### Expected behavior

Added option `message_headers_to_tags_list` that will contain the name list kafka message headers that should be added to the metric as tags

### Actual behavior

If you want to pass any tags you should add these values to the message internally 

### Additional info

We realized this behaviour in the our solution. It contains two new options:

1. `message_headers_to_tags_list = ["Header1", "Header2", ...]` that contains a list of message header names that should be added to the metric as tags
2. `kafka_version = "2.6.0"`

Ready for PR. Here is a description from the updated readme
```

  ## The list of Kafka message headers that should be pass as metric tags
  ## works only for Kafka version 0.11+, if not the message headers are not available
  # message_headers_to_tags_list = ['Country','City']

  ## Set the minimal supported Kafka version. Should be a string contains 
  ## 4 digits in case if it is 0 version and 3 digits for versions starting
  ## from 1.0.0 separated with dot. This setting enables the use of new
  ## Kafka features and APIs.  Must be 0.10.2.0(used as default) or greater.
  ## Please, check the list of supported versions on 
  ## https://pkg.go.dev/github.com/Shopify/sarama#SupportedVersions
  ##   ex: kafka_version = "2.6.0"
  ##   ex: kafka_version = "0.10.3.0"
  # kafka_version = "0.10.2.0"
```

**Comment by BelousovAntonV** [comment]
Discussable: the list of names could be replaced with map for aliasing. We do not need that functionality and our tag names are equal to the message header names, but it could be usefull for cases when headers are named like `"Header_Country", "Header_City"` for some reason. In this case map `{"City":"Header_City", "Country":"Header_Country"}` will allow to rename headers.

**Comment by powersj** [comment]
> Added option message_headers_to_tags_list that will contain the name list kafka message headers that should be added to the metric as tags

Call it `msg_headers_as_tags`, no need to call it a list when it is one.

> kafka_version = "2.6.0"

This option already exists, are you calling this out to show you updated the description? 
Or are you making changes here? 
Does this PR require a certain version?

> Discussable: the list of names could be replaced with map for aliasing.

no - thanks, but this is what processors are for

**Comment by BelousovAntonV** [comment]
> This option already exists, are you calling this out to show you updated the description?
At the moment this option does not work. Here what you can find in the code of Kafka Consumer: 
```
	// Kafka version 0.10.2.0 is required for consumer groups.
	cfg.Version = sarama.V0_10_2_0
```
Also it is not declared in the KafkaConsumer struct

>  Or are you making changes here?
So yes, I'm making changes, now version it could be specified and changed
```
	// Kafka version 0.10.2.0 is required for consumer groups.
	// Try to parse version from config. If can not, set default
	if kafka_version, err := sarama.ParseKafkaVersion(k.KafkaVersion); err == nil {
		cfg.Version = kafka_version
	} else {
		cfg.Version = sarama.V0_10_2_0
	}
```

> Does this PR require a certain version?
Yes and no. To get message headers the version of kafka should be 0.11+, in other cases headers will not be received and Message.Headers will be empty array. But if this functionality is not needed the version could be 0.10.2.0, which is default now.

**Comment by powersj** [comment]
> Also it is not declared in the KafkaConsumer struct

ha! thank you for catching this. Good to see a PR
