### ISSUE TITLE
Add Username support for authentication in redis and sentinel input plugin within Telegraf

### ISSUE THREAD

**Issue by hemanth-vulavala** [influxdata/telegraf#13836]
### Use Case

The use case for addressing the limitation in Telegraf's Redis Input Plugin and Sentinel Input Plugin, where they do not support the use of a username for authentication, while Redis itself supports both username and password for authentication, can be illustrated with the following scenario:

Imagine a large-scale enterprise environment where data is stored in multiple Redis databases for various applications. Each Redis database is designed to hold sensitive and critical information. To ensure robust security, the company has set up a policy where authentication requires both a username and a password.

In this context, Telegraf is utilized to collect data from these Redis databases for monitoring and analysis purposes. However, due to the current limitation in Telegraf, it can only use a password for authentication when connecting to Redis instances. This means that the username-based authentication policy cannot be adhered to, creating a security gap.

The use case highlights the importance of having consistent and comprehensive security measures across all components of the infrastructure. Telegraf, as a crucial data collection tool, needs to align with Redis's authentication capabilities to ensure that sensitive data remains protected. By enabling Telegraf's Redis Input Plugin and Sentinel Input Plugin to accept a username for authentication, the enterprise can confidently uphold its security policy and collect data without compromising security standards.

In summary, the use case underscores the need for Telegraf to support username-based authentication in its Redis and Sentinel Input Plugins to ensure security consistency and compatibility with Redis's authentication mechanisms

### Expected behavior

The expected behavior is that Telegraf's Redis Input Plugin and Sentinel Input Plugin should be enhanced to support both usernames and passwords for authentication, aligning with the authentication capabilities provided by Redis. Currently, these plugins only allow for the use of a password during the authentication process.

With the enhancement, when configuring these plugins in Telegraf's configuration file, users should have the option to provide both a username and a password for authenticating with Redis instances. This would allow Telegraf to connect to Redis databases that require both a username and password for access.

By introducing this support, Telegraf users can establish a more secure and consistent approach to data collection from Redis databases. This improvement ensures that Telegraf can adhere to various security policies and authentication mechanisms set up by organizations, without compromising on security standards.

In summary, the expected behavior is that Telegraf's Redis and Sentinel Input Plugins should offer the flexibility to use both usernames and passwords for authentication, in line with Redis's authentication capabilities, thereby enhancing security and compatibility in data collection processes

### Actual behavior

The current actual behavior is that Telegraf's Redis Input Plugin and Sentinel Input Plugin only support the use of passwords for authentication when connecting to Redis instances. Unfortunately, these plugins do not provide the option to include a username as part of the authentication process, even though Redis itself supports both username and password for authentication.

This limitation means that when using Telegraf to collect data from Redis databases, it's not possible to establish connections to instances that require both a username and a password for access. As a result, organizations that rely on Telegraf for data collection might find themselves unable to comply with security policies that mandate the use of both authentication credentials.

In essence, the actual behavior is that the current version of Telegraf lacks the functionality to fully align with Redis's authentication capabilities, which includes the use of usernames during the authentication process. This limitation could potentially hinder secure data collection practices and limit compatibility with various authentication setups within Redis environments.

### Additional info

acording to redis documenttation they support both username and password for authentication

https://redis.io/docs/management/security/acl/#:~:text=The%20Redis%20ACL%2C%20short%20for,a%20valid%20password%20to%20authenticate.

**Comment by powersj** [comment]
Hi,

The redis plugin has two ways to specify a username, either 1) via the server connection string (e.g. `tcp://username:password@address` 2) via the `username` option. Neither of these are very well documented, however, have you tried them and found them to not be working?

The redis sentinel plugin does not have either of these options. Can you please confirm this works with the redis plugin and if it does we could add it to redis sentinel?

**Comment by hemanth-vulavala** [comment]
i couldn't found the option 1 related documentation w.r.t username .

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/redis/README.md

will check above two options and share you the feedback

**Comment by powersj** [comment]
```toml
  ## specify username for ACL auth (Redis 6.0+)
  # username = "default"
```

**Comment by hemanth-vulavala** [comment]
**Option 1:**
[[inputs.redis]]
  servers = ["tcp://username:password@hostname:6379"]
**Option2:**
[[inputs.redis]]
  servers = ["tcp://hostname:6379"]
  username = "test"
  password = "test"

both options are working fine for input.redis plugin 
**please let us know , if any plan for supporting for intput.inputs.redis_sentinel plugin**

**Comment by powersj** [comment]
@hemanth-vulavala

Thank you for confirming! 

Could you please download the artifacts in https://github.com/influxdata/telegraf/pull/13864 and give them a try to confirm that it is working for redis_sentinal? 

The PR will allow a username and password in the server URI, similar to option 1 you specified above. I have also updated the documentation to show the passing of an optional username and password.

Thanks!

**Comment by hemanth-vulavala** [comment]
will test and share our feedback

**Comment by hemanth-vulavala** [comment]
preared image from shared binary by you.
redis and sentinel input plugins are loaded with any errors after enaablig username and password for both redis and sentinel.
