### ISSUE TITLE
[feature request] support using environment variables to override/provide configuration

### ISSUE THREAD

**Issue by seanmcgary** [influxdata/telegraf#1383]
### Proposal:

Telegraf should support configuration/configuration overrides via environment variables in the same way that Influxdb and Kapacitor do. In addition, this should make the `-config` flag optional if the required configuration values are provided through the environment.
### Current behavior:

Currently configuration can only be provided via a config file with the `-config` flag at runtime. Environment variables are only supported when referenced inside a configuration file.

example:

```
[[inputs.memcached]]
  servers = ["$MY_TEST_SERVER"]
  ...
```
### Desired behavior:

Telegraf should support using environment variables to override/provide configuration in the same way that Influxdb and Telegraf do.

``` bash
export TELEGRAF_<section name>_<section property>="some value"
```

For example:

``` toml
[agent]
  interval = "10s"
```

could be written as 

```
TELEGRAF_AGENT_INTERVAL="10s"
```
### Use case:

This is particularly useful when running Telegraf in a container where configuration is easy to provide via environment variables rather than writing out a specific config. 

This would also make Telegraf consistent with Influxdb and Kapacitor.

**Comment by sparrc** [comment]
this would be nice but is actually not trivial to implement, unfortunately.

Because of the plugin nature of Telegraf, the agent itself has no knowledge of the various options in each plugin's config, we simply take the given toml and try to apply it onto the plugin structs.

**Comment by otzy007** [comment]
It would be nice to be able to configure via environment variables various plugins. This way telegraf can be easier dockerized and used to monitor various systems.

**Comment by devkid** [comment]
@sparrc Wouldn't it be easily possible to look for all environment variables starting with `TELEGRAF_` when reading the toml file and just fill them into the struct before passing the whole thing to the plugins?

**Comment by mickey** [comment]
At my current company, we "build" the config from a directory of `.toml.erb` files. This gives us the possibility to embed config variable dependant on the host easily but also split the config into multiple files, generating tons of input blocks with a loop iterating on some config, ....

**Comment by lhoss** [comment]
I'm quite new to telegraf (TICK in general), as I started deploying influxdb, telegraf (in mesos/marathon docker 👍 ) only yesterday  (and looks good except some issues, like howto tell telegraf the container's host hostname ..)

but I'm wondering why nobody mentioned there's a feature already to support setting config values from (system/os)ENV vars, see: https://github.com/influxdata/telegraf/pull/951/files
Though I agree this can be improved "make Telegraf consistent with Influxdb and Kapacitor" 👍

**Comment by devkid** [comment]
@lhoss The pull request you mentioned enabled the use of environment variables inside the config file (which was mentioned by @seanmcgary in the first post already) but not the configuration solely by environment variables without the need for a config file.

**Comment by danielnelson** [comment]
Closing, we don't intend to directly provide full environment variable configuration.
