### ISSUE TITLE
Systemd seems to be causing telegraf to log errors on restart, but should not.

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13842]
### Use Case

This is more like a soft bug report.

`/usr/lib/telegraf/scripts/telegraf.service` currently contains a line

    KillMode=control-group

When you have some "non-atomic" extra process checks running (`inputs.exec`, `inputs.ping`), i.e. checks which don't always return very quickly, and you restart your telegraf with `systemctl restart telegraf`, systemd sends `SIGTERM` to all of those processes which (usually) then die.
Telegraf, still running, logs those dying processes as errors:
``` 
2023-08-24T13:37:03Z E! [inputs.ping] Error in plugin: host "host1.example": signal: terminated - PING host1.example (1.2.3.4) 16(44) bytes of data.
24 bytes from 1.2.3.4: icmp_seq=1 ttl=62 time=0.363 ms
2023-08-24T13:37:03Z E! [inputs.ping] Error in plugin: host "host2.example": signal: terminated - PING host2.example (1.2.3.5) 16(44) bytes of data.
24 bytes from 1.2.3.5: icmp_seq=1 ttl=126 time=0.287 ms
2023-08-24T13:37:03Z E! [inputs.ping] Error in plugin: host "host3.example": signal: terminated - PING host3.example (1.2.3.6) 16(44) bytes of data.
24 bytes from 1.2.3.6: icmp_seq=1 ttl=62 time=0.359 ms
2023-08-24T13:37:03Z E! [inputs.ping] Error in plugin: host "host4.example": signal: terminated - PING host4.example (1.2.3.7) 16(44) bytes of data.
24 bytes from 1.2.3.7: icmp_seq=1 ttl=60 time=0.378 ms
2023-08-24T13:37:06Z I! [inputs.something] Stopping plugin
2023-08-24T13:37:06Z I! [agent] Hang on, flushing any cached metrics before shutdown
```

### Expected behavior

systemd telling telegraf to shutdown, telegraf doing it graciously and not logging killed processes which were killed on command.

This could probably be achieved by using `KillMode=mixed` instead of `KillMode=control-group` in `/usr/lib/telegraf/scripts/telegraf.service`

### Actual behavior

systemd terminating all processes, prompting the surprised telegraf to log all those dead child processes before gracefully shutting down itself.

### Additional info

You can't test this only with telegraf.
With a simple sample config, and a manually started instance which you then, for a test, terminate with `C-c` you won't see this, because this way, telegraf is terminating it's children gracefully and no error is logged.

### Why is this relevant?

We monitor our telegraf logs for errors so we can intervene when something goes wrong. This "bug" produces false positives on configuration changes which actually don't fail at all, but just come with a telegraf restart.
I don't like that.

**Comment by srebhan** [comment]
I think your reasoning is sound @knollet. Can you please test with `KillMode=mixed` and put up a PR if it solves the issue?!

**Comment by knollet** [comment]
Please disregard my clumsy fight with the CI pipeline

**Comment by srebhan** [comment]
Can you please indicate if PR #13849 fixes the issue!?

**Comment by knollet** [comment]
I tested it with the telegraf-version I have installed and an override.conf in the systemd folder, b/c I currently am unable to build telegraf, and couldn't test a complete build (I will see if I can get it working)

If you can create an artifact from the PR for me, I am happy to test it.

**Comment by srebhan** [comment]
Your test is fine as the binary is not changed. Thanks for testing!
