### ISSUE TITLE
nfsstat Not Showing 

### ISSUE THREAD

**Issue by skinfrakkiirid** [influxdata/telegraf#13851]
Enabled [[inputs.nfsclient]] with default configuration. However, I am not seeing an nfsstat measurement. I don't see any errors in the telegraf log. When running test on the telegraf config I see the following:

input=nfsclient,version=1.25.0 errors=0i,gather_time_ns=0i,metrics_gathered=0i 1693522897000000000

**Comment by skinfrakkiirid** [comment]
Any ideas?

**Comment by powersj** [comment]
Hi,

As the bot mentioned this is not a bug but a question. Please use the forums or the community slack.

I will say that you said you enabled nfsclient with the default config. This means that fullstat is set to false. You might not be collecting anything. Additionally, check out what is reported in `/proc/self/mountstats` as that is where data is collected.
