### ISSUE TITLE
Add disk usage to docker input plugin

### ISSUE THREAD

**Issue by R290** [influxdata/telegraf#13858]
### Use Case

I'd like to be able to monitor Docker volume size over time using the Telegraf Docker input plugin.

### Expected behavior

A configuration setting for setting the preferred objects to be monitored: containers / images / volumes / build cache (as defined in https://pkg.go.dev/github.com/docker/docker@v24.0.5+incompatible/api/types#DiskUsageObject)

Possibly a few additional settings to include or exclude objects based on their name, preferably with wild card support.

### Actual behavior

None of the settings are available; disk usage is not implemented in the Docker input plugin.

### Additional info

The Docker client of the existing plugin natively supports querying disk usage. For example, see:

- https://pkg.go.dev/github.com/docker/docker@v24.0.5+incompatible/api/types#DiskUsage
- https://github.com/moby/moby/blob/v24.0.5/client/disk_usage.go

This should make implementation trivial, although there needs to be agreement on the configuration scheme.

**Comment by powersj** [comment]
Hi @R290,

> A configuration setting for setting the preferred objects to be monitored: containers / images / volumes / build cache

Are all of these actually interesting?

Adding a `storage_objects = []` settings which could take the things we want to collect seems possible. Then if a user wanted to further exclude/include they can use metric filtering. I'd like to avoid needing to have an include/exclude for every object. Thoughts?

Thanks!

**Comment by R290** [comment]
`storage_objects` should in this case contain the type of object to monitor (containers / volumes / etc.)? Further filtering would be based on using tagpass / tagdrop on tags like `container_name` or `volume_name` or do we use something more generic like `storage_object_name`?

**Comment by R290** [comment]
Yes, I'll put something together and we can go from there.

**Comment by R290** [comment]
It seems that we are using quite an old Docker api version: https://github.com/influxdata/telegraf/blob/67f9a0ea8276e06e3c3d4028cbbd113dfe9bbc6f/plugins/inputs/docker/client.go#L14

Somehow, the use of `DiskUsageOptions` is ignored in the older api version and all storage object types are always returned. Setting the the version to 1.42 (the latest at this moment) seems to resolve this. I don't know if we can just change this? All docker tests pass with 1.42.

**Comment by powersj** [comment]
Thanks for looking into this further.

I am good with updating the version. Looking through the [Engine API version docs](https://docs.docker.com/engine/api/version-history/) there are quite a number of changes, but it does look like they try to keep compatability.

**Comment by powersj** [comment]
Not sure why the bot tried closing this again :\ hopefully with us commenting on it, it will go away.
