### ISSUE TITLE
Filter kuberetes_inventory input plugin nodes and pods by node name

### ISSUE THREAD

**Issue by Noy-Simon** [influxdata/telegraf#13878]
### Use Case

When this plugin is installed on large clusters it creates stress on the API server since it requests information on all of the pods & nodes in the cluster
To support scaling we want to install it on a daemonset 
But without the option to filter by node name it will still get all the information for each pod in the daemon and create an even bigger pressure on the API server

### Expected behavior

Configure metrics on pods & nodes by node name on a daemon and get the relevant information with good performance 

### Actual behavior

A lot of pressure on the API server and timeout failures to get inventory date

**Comment by powersj** [comment]
Hi,

I know there are some differences, but I think they are now minimal between the `kubernetes` and `kube_inventory` plugins. The `kubernetes` plugin how the ability to filter based on labels. Would that work in your scenario?

If not, I would be happy to see you continue to work on your PR. If you can't filter on labels, I would suggest we add the ability to filter on a name versus setting exactly once name to look for.

**Comment by Noy-Simon** [comment]
Hey 
The issue is that if we are using the inventory plugin in a large cluster of 500 nodes for example 
And we want to use a daemonset so we can scale out 
We are creating a lot of stress on the API server 
Even if we filter by label it still means that we will go to the API server 500 times at once to get the information on all the pods and the nodes in the system and filter it after it 
In lab conditions, the average latency on the API server rose by 30s in this scenario 
If we don't want to use a daemon but a deployment instead we are limited by the buffer size so we are not really scalable 

What I did in my PRs is 
1- Allow to get the pods data from the kubelet like we do in the Kubernetes plugin 
This reduces 90% of the pressure on the API server
2- Allow to filter by node name in the request to the API server 
This handles the last 10% of the pressure 

Both of them together allows telegraf to be scalable for large clusters
