### ISSUE TITLE
Add adb input as input option

### ISSUE THREAD

**Issue by LeeTeng2001** [influxdata/telegraf#13882]
### Use Case

I would like to monitor android device usage through adb. I could work on this feature

### Expected behavior

telegraf can use adb as input plugin

### Actual behavior

telegraf can use adb to feed input

**Comment by LeeTeng2001** [comment]
- What metrics are you interested in creating?

Android overall/specific application device usage, specifically the output from [dumpsys](https://developer.android.com/tools/dumpsys)

- Does the adb have metrics or an endpoint to collect data from it?

yes, through the dumpsys command

- What format are the metrics provided in?

Text output from shell

- Is there a library you would use to do the data collection?

no, I would parse it manually in Go

**Comment by powersj** [comment]
Hi @LeeTeng2001,

Thanks for the information and background. Maintaining a plugin that does is not something we want to take on. My suggestion is if you wish to create this plugin we would be happy to link to it as an external plugin or for you to use an external script + the inputs.exec plugin.

Thanks
