### ISSUE TITLE
Provide better logging output control

### ISSUE THREAD

**Issue by tulku** [influxdata/telegraf#13881]
### Use Case

Google Container Engine (and probably other cloud services and `journalctl`) automatically classifies logs from the running services as errors or not, depending on the source of the log line. Log lines written to `stderr` are errors, while lines logged to `stdout` are not (usually info).

Telegraf logs are written to `stderr` (more detail in following sections), making all logs errors, which can be very distracting when reviewing what the service is doing, as shown in the following screen capture:

![image](https://github.com/influxdata/telegraf/assets/764126/f4143535-ed74-49ff-bad5-0ddb665a6c2a)

Avoiding `INFO` messages to be classified as errors would help significantly when setting up alerts and filtering logs.

### Expected behavior

It is a common practice to log info messages to `stdout` while error messages to `stderr` (or more generally level >= warning write to `stderr`). I would consider splitting logs between stdout and stderr as the 'expected behavior'. Having the option to set the log target per log level would be great, but the split could be fixed.

A simpler change, adding the option to log everything to `stdout` would also help a bit, at least reducing the noise that having everything marked as error produces.

### Actual behavior

The configuration option `logtarget` only supports `stderr` or `file` as options.

It would be doable to use `file` and set `/dev/stdout` as a file so that all logs are written to stdout, but this can produce permission problems.

**Comment by powersj** [comment]
Hi,

@srebhan and myself met to discuss this yesterday.

Telegraf currently utilizes https://github.com/influxdata/wlog to log messages. Unlike newer loggers it provides a single target to send logs to. This is why currently there is only a stderr vs file option exposed. Telegraf also produces log messages very early in the process, even before the configuration is even read, and can be modified by the configuration.

To tackle this request we would need to revamp either the library to accept and route different targets or revamp telegraf's own logging and config handling. Neither of these are things we plan to tackle for the foreseeable future. If someone where to propose a PR we would be willing to review it, however it would need to ensure backwards compatibility with the existing configs and format of the logs. As such I am going to close this as won't fix.
