### ISSUE TITLE
[[inputs.jenkins]]: Add build timestamp as field

### ISSUE THREAD

**Issue by kpdo** [influxdata/telegraf#13892]
### Use Case

In the "jenkins_job" measurement I need the timestamp of the build as a field. My use case is to send an alert when the last build was too old (for example because a scheduled build didn't run for some reason). 

Currently (as a workaround) I add the timestamp field manually using starlark but I'd like to avoid that:

[[processors.starlark]]
  namepass = ["jenkins_job"]

  source = '''
def apply(metric):
  metric.fields["timestamp"] = metric.time / 1000000 # convert nanoseconds to milliseconds
  return metric
'''

### Expected behavior

For the measurement "jenkins_job" I expected the jenkins input plugin to also return the timestamp of the build as field. It seems like it is already used to set the metric timestamp so it should be easy to also include it in the fields.

### Actual behavior

Currently the timestamp is not included in the fields for the measurement "jenkins_job".

### Additional info

The Jenkins API returns the start timestamp of the build in milliseconds like this:

GET https://myjenkins.com/job/my-job-name/42/api/json
`{
  ...
  "timestamp" : 1694176524866,
  ...
}`

**Comment by powersj** [comment]
Hi,

The timestamp from the data is used to set the timestamp of the metric. Adding it as a field and a timestamp is redundant, but I understand there could be scenarios where you need it as a field. In those cases, we would tell you to use a processor to make this change, which you have already figured out.

Going to close this as not something we would add.
