### ISSUE TITLE
opcua_listener: set individual values for monitoring parameters instead of relying on defaults

### ISSUE THREAD

**Issue by reindlt** [influxdata/telegraf#13891]
### Use Case

Currently, there is only the possibility to set the publishing interval (field `subscription_interval` in config) of an opcua subscription -> https://community.influxdata.com/t/opcua-listener-subscription-interval/30808

However, there are other parameters (e.g. sampling interval, queue size, ...) which might effect data collection. These parameters are all set to fixed values by default and cannot be changed. A reference for available parameters can be found [here](https://reference.opcfoundation.org/Core/Part4/docs/5.12.1).

It should be possible to change these paremeters via the config so that more individual subscription settings are possible. The following parameters should be editable on a per node basis:

- SamplingInterval
- Queue parameters such as QueueSize and DiscardOldest

It should also be possible to add a DataChangeFilter as filter.

### Expected behavior

SamplingInterval, QueueSize, DiscardOldest parameters and a DataChangeFilter can be set in the config per node. The monitored items should be created with these parameters set to the values specified in the config instead of the fixed values specified in code.

### Actual behavior

Each subscription and monitored item is created with the same fixed settings and cannot be changed.

**Comment by powersj** [comment]
@LarsStegman thoughts on exposing these options for `opcua_listener`?

**Comment by LarsStegman** [comment]
A good idea!
