### ISSUE TITLE
http_listener_v2 returns a "No Content" response code 204

### ISSUE THREAD

**Issue by ilyabram** [influxdata/telegraf#13896]
### Please direct all support questsions to slack or the forums. Thank you.

When using http_listener_v2 plugin, it works as expected, however returns "No Content" response code 204.
Performing HTTP POST with JSON, and relaying it to InfluxDB.
The relay operation succeeds, only the "No Content" response code 204 is retruned to the http client (which intiates the POST command)
Expected to return a success code 200 on HTTP.

Is it an expected behaviour for http_listener_v2 plugin ?

**Comment by powersj** [comment]
> Is it an expected behaviour for http_listener_v2 plugin ?

Yes - because we have not actually written the data, but accepted the data, we did not want to say OK. The [specific line is here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_listener_v2/http_listener_v2.go#L249).
