### ISSUE TITLE
Config Variable and Docu are Different :  resource_pool_metric_exclude

### ISSUE THREAD

**Issue by Muy69** [influxdata/telegraf#13905]
### Relevant telegraf.conf

The Variable in the Config for resourcepool_metric_exclude was changed in 1.28

prior 1.28
#resourcepool_metric_exclude = ["*"]

after 
#resource_pool_metric_exclude = ["*"]

Telegraf will not start with the old Configs . 

...
 vm_metric_exclude = ["*"] # Exclude realtime metrics
  host_metric_exclude = ["*"] # Exclude realtime metrics
  datastore_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
**  #resourcepool_metric_exclude = ["*"] **
  resource_pool_metric_exclude = ["*"]
...

## Logs from Telegraf

2023-09-12T10:14:02Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.vsphere: line 306: configuration specified the fields ["resourcepool_metric_exclude"], but they weren't used

### System info

Telegraf 1.28, Ubuntu 22.04 , VM

### Steps to reproduce

1. If you use the Variable as resource_pool_metric_exclude = ["*"] it will work 
2. If you have an existing / Old Config  resourcepool_metric_exclude = ["*"]  , it will **not** work . 

### Expected behavior

Please allign the Telegraf Docu with the Changes of the Variable in Version 1.28

**resource_pool_metric_exclude** 

### Actual behavior

Currently there is a Dokumentation to the old Variable  . 

**resourcepool_metric_exclude**

**Comment by Hipska** [comment]
Introduced by #13905

**Comment by powersj** [comment]
> Introduced by #13905

@Hipska #13905 is this issue report

I put up #13907 which updates the typo in the readme.

**Comment by Hipska** [comment]
My bad, wrong paste. Introduced by https://github.com/influxdata/telegraf/pull/13720

**Comment by Hipska** [comment]
@Muy69 what was the exact telegraf version when this config parameter worked without problems?

**Comment by Muy69** [comment]
I upgraded from 1.27.4-1 -> 1.28.0.1

**Comment by Hipska** [comment]
But did it actually work? Or was the setting just ignored?

**Comment by Muy69** [comment]
It was ignored and I didnt receive an Error afterwards.

**Comment by Hipska** [comment]
Okay, but now you do. Thanks for reporting!
