### ISSUE TITLE
inputs.systemd_units: value not in map: condition

### ISSUE THREAD

**Issue by sergeymakinen** [influxdata/telegraf#13900]
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
  interval = "15s"
  timeout = "15s"
```

### Logs from Telegraf

```text
Sep 10 17:00:00 debian telegraf[405343]: 2023-09-10T14:00:00Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'sub', value not in map: condition
```

### System info

Telegraf 1.27.4, Debian 12.1

### Steps to reproduce

1. 
  ```bash
cat <<EOF >/etc/systemd/system/test.service
[Unit]
Description=Test

[Service]
Type=oneshot
ExecCondition=/bin/sh 'sleep 15; exit 0'
ExecStart=/usr/bin/true
EOF
   ```
2.
  ```bash
cat <<EOF >/etc/systemd/system/test.timer
[Unit]
Description=Test

[Timer]
OnCalendar=minutely
Persistent=true

[Install]
WantedBy=timers.target
EOF
   ```
3. `systemctl enable --now test.timer`
4. 
  ```bash
# while [ $? -ne 0 ]; do systemctl list-units --all --plain --type=service | grep cond; done
test.service                         loaded    activating condition start Test
  ```

### Expected behavior

At the same time you get `test.service                         loaded    activating condition start Test` at the console, Telegraf prints the `[inputs.systemd_units] Error in plugin: Error parsing field 'sub', value not in map: condition` message.

### Actual behavior

A condition status is either honored or ignored.

**Comment by powersj** [comment]
Hi,

Thanks for the issue. It does look like we are missing some additional upstream states from:

https://github.com/systemd/systemd/blob/main/src/basic/unit-def.c#L182-L208

service_state_table
* condition
* reload-signal
* reload-notify
* final-watchdog
* dead-before-auto-restart
* failed-before-auto-restart
* dead-resources-pinned
* auto-restart-queued
* cleaning
	
mount_state_table
* cleaning
	
swap_state_table
* cleaning

**Comment by powersj** [comment]
@sergeymakinen,

Can you give the artifacts in #13915 a try please? They will be added as a comment in 20-30mins after this comment.

**Comment by sergeymakinen** [comment]
Hey @powersj, thanks! Looks good now:

```
> systemd_units,active=activating,host=debian,load=loaded,name=test.service,sub=condition active_code=4i,load_code=0i,sub_code=14i 1694548061000000000
```
