### ISSUE TITLE
Wrong perms for main config file and config dir in 1.28

### ISSUE THREAD

**Issue by clsmyth** [influxdata/telegraf#13904]
### Relevant telegraf.conf

```toml
none
```

### Logs from Telegraf

```text
none
```

### System info

telegraf 1.28, RockyLinux 8

### Steps to reproduce

1. install telegraf
2. observe /etc/telegraf/telegraf.conf gets installed with mode 0644 , and /etc/telegraf/telegraf.d gets installed with mode 0750 .
3. observe this prevents telegraf from starting. 

### Expected behavior

telegraf should start

### Actual behavior

telegraf does not start

### Additional info

# ll /etc/telegraf/
total 500
drwxr-xr-x 2 root root   4096 Sep 12 05:22 crypto
-rw-r----- 1 root root   1016 Sep 12 05:22 telegraf.conf
-rw-r--r-- 1 root root 497518 Sep 11 15:52 telegraf.conf.sample
drwxr-x--- 2 root root   4096 Sep 12 05:23 telegraf.d

**Comment by Hount** [comment]
With CentOS 7 the whole telegraf.conf file is lost during update. 
Behavior is unsurprisingly the same. Telegraf does not start.

**Comment by moucho** [comment]
> With CentOS 7 the whole telegraf.conf file is lost during update. Behavior is unsurprisingly the same. Telegraf does not start.

The same in AlmaLinux 8

**Comment by nerijus** [comment]
`/usr/lib/systemd/system/telegraf.service` from rpm package has:
```
[Service]
User=telegraf
```
`/etc/telegraf/telegraf.conf` and `/etc/telegraf/telegraf.d` should be owned by user `telegraf`.

**Comment by sorsbyl** [comment]
It looks like it's related to this change:
https://github.com/influxdata/telegraf/pull/13778/files#diff-411c324e96e90a396aca7d995d301782312bcf7616538e1015000613f955549d

**Comment by powersj** [comment]
Hi,

Thanks for the issue report. 

> With CentOS 7 the whole telegraf.conf file is lost during update.

@Hount and @moucho can you please explain that the telegraf.conf file is "lost during update"? I want to be sure this is just wrong group permissions and nothing more.

**Comment by sorsbyl** [comment]
> Hi,
> 
> Thanks for the issue report.
> 
> > With CentOS 7 the whole telegraf.conf file is lost during update.
> 
> @Hount and @moucho can you please explain that the telegraf.conf file is "lost during update"? I want to be sure this is just wrong group permissions and nothing more.

We've had a similar issue. We upgraded from 1.27 to 1.28 and we no longer have a telegraf.conf file which crashes telegraf. We've tested a fresh install which works fine.

**Comment by powersj** [comment]
I am going to revert the change via #13909. While the intent was that this only changed on fresh installs, we did miss the group permissions, but the fact that users are seeing issues on upgrades says this was not tested through enough scenarios.

**Comment by moucho** [comment]
> Hi,
> 
> Thanks for the issue report.
> 
> > With CentOS 7 the whole telegraf.conf file is lost during update.
> 
> @Hount and @moucho can you please explain that the telegraf.conf file is "lost during update"? I want to be sure this is just wrong group permissions and nothing more.

Just that the update deletes the file /etc/telegraf/telegraf.conf

**Comment by giner** [comment]
This fails on a fresh install as well (Debian package) because the owner of the configs is root while telegraf runs as telegraf user.

**Comment by soymgomez** [comment]
Same here with AlmaLinux 8. 

I upgraded to version 1.28 from a working installation and when I finished the dnf upgrade the /etc/telegraf/telegraf.conf file did not exist.

**Comment by powersj** [comment]
Hi,

The package repo now contains version v1.28.1 now which includes the revert. Waiting on upstream reviews for the docker image.

@soymgomez, @Hount, @moucho, I would still very much like to see a `ls -la /etc/telegraf` from the upgrade to v1.28.0 if possible.

Thanks folks!

**Comment by moucho** [comment]
> Hi,
> 
> The package repo now contains version v1.28.1 now which includes the revert. Waiting on upstream reviews for the docker image.
> 
> @soymgomez, @Hount, @moucho, I would still very much like to see a `ls -la /etc/telegraf` from the upgrade to v1.28.0 if possible.
> 
> Thanks folks!

[root@test]# ls -lah /etc/telegraf/
total 1004K
drwxr-xr-x    7 root     root 4,0K sep 13 08:08 .
drwxr-xr-x. 129 root     root  20K sep 13 08:00 ..
drwxr-x---    3 telegraf root 4,0K ago 19  2021 .cache
-rw-r--r--    1 root     root 467K ago 21 16:03 telegraf.conf.rpmnew
-rw-r-----    1 telegraf root  320 ago  5  2020 telegraf.conf.rpmsave
-rw-r--r--    1 root     root 486K sep 11 17:52 telegraf.conf.sample
drwxr-x---    2 telegraf root 4,0K sep 13 08:08 telegraf.d
drwxr-x---    2 telegraf root 4,0K ago  5  2020 telegraf.debug

**Comment by Hount** [comment]
> Hi,
> 
> The package repo now contains version v1.28.1 now which includes the revert. Waiting on upstream reviews for the docker image.
> 
> @soymgomez, @Hount, @moucho, I would still very much like to see a `ls -la /etc/telegraf` from the upgrade to v1.28.0 if possible.
> 
> Thanks folks!

Oh, we just finished upgrading rest of the fleet to 1.28.1. I believe we have no more broken 1.28 anywhere. But this should not be difficult to reproduce as 100% of our Centos7 telegraf 1.28 acted the same :)

**Comment by Hount** [comment]
@powersj found one.

`$ yum info telegraf
Installed Packages
Name        : telegraf
Arch        : x86_64
Version     : 1.28.0
Release     : 1
Size        : 189 M
Repo        : installed
From repo   : influxdb
Summary     : Plugin-driven server agent for reporting metrics into InfluxDB.
URL         : https://github.com/influxdata/telegraf
License     : MIT
Description : Plugin-driven server agent for reporting metrics into InfluxDB.
`

`$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)`

`$ ls -la /etc/telegraf/
total 972
drwxr-xr-x    3 root root    109 Sep 12 05:02 .
drwxr-xr-x. 100 root root   8192 Sep 12 04:56 ..
-rw-r--r--    1 root root 474795 Jun 12 14:25 telegraf.conf.rpmnew
-rw-r--r--    1 root root   5423 Feb 14  2023 telegraf.conf.rpmsave
-rw-r--r--    1 root root 497518 Sep 11 15:52 telegraf.conf.sample
drwxr-xr-x    2 root root     21 Sep 12 05:01 telegraf.d
`
