### ISSUE TITLE
telegraf doesn't seem to have an "up" indicator like node_exporter to determine if the server is online.   What indicator should I use to determine if a node is online?

### ISSUE THREAD

**Issue by MagicStarTrace** [influxdata/telegraf#13920]
### Please direct all support questsions to slack or the forums. Thank you.

I'm currently working with Prometheus to monitor whether the server is online or not, and don't have the right metrics for that

Thank You!

**Comment by srebhan** [comment]
@MagicStarTrace not sure I can follow... Simply check if any of the metrics arrived in `interval + epsilon` from now should be a perfect "up" indicator...
