### ISSUE TITLE
AWS PutMetricData API now accepts 1000 metrics per API call

### ISSUE THREAD

**Issue by paulbrimicombe** [influxdata/telegraf#13929]
### Use Case

We use the CloudWatch output plugin and find it very useful. Currently the batch size for PutMetricData API calls is set to 20:

https://github.com/influxdata/telegraf/blob/4b447d04830e4ab908a348f8446a1c125ecd106f/plugins/outputs/cloudwatch/cloudwatch.go#L191

This has now been increased to 1000 metrics (see https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html#:~:text=Each%20request%20is%20also%20limited%20to%20no%20more%20than%201000%20different%20metrics and https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html#:~:text=cannot%20be%20changed.-,MetricDatum%20items,-1000/PutMetricData)

Since there is a per-API-call cost, increasing the number of metrics per API call from Telegraf will greatly reduce our costs

### Expected behavior

Telegraf should use the maximum batch size when publishing metrics to AWS.

### Actual behavior

Telegraf posts a maximum of 20 metrics per batch when publishing metrics to AWS.

**Comment by powersj** [comment]
Hi,

Thanks for letting us know about this. Can you give the artifacts in #13930 a try please?

**Comment by paulbrimicombe** [comment]
@powersj is it worth allowing this parameter to be configured in the CloudWatch output plugin? There might be reasons why people want to use a smaller batch size (e.g. to avoid the 1MB request body limit for the PutMetricData API call).

**Comment by powersj** [comment]
Possibly. Telegraf globally and per output has the `metric_batch_size` option, which sets the number of metrics to send at once. A user could set this below 1000 to force a lower value.

**Comment by paulbrimicombe** [comment]
Thanks very much for this change @powersj — we've deployed to production with the latest Telegraf release and it has reduced the number of API calls significantly. 🎉
