### ISSUE TITLE
procstat metric not populated on FreeBSD arm64

### ISSUE THREAD

**Issue by sdalu** [influxdata/telegraf#13933]
### Relevant telegraf.conf

```toml
[[inputs.procstat]]
  exe                   = "influxd"
  tagexclude            = [ "pid_finder", "exe", "pidfile" ]

[[inputs.procstat]]
  exe                   = "telegraf"
  tagexclude            = [ "pid_finder", "exe", "pidfile" ]
```

### Logs from Telegraf

```text
2023-09-15T21:17:42Z I! Loading config: /usr/local/etc/telegraf.conf
2023-09-15T21:17:42Z I! Starting Telegraf unknown brought to you by InfluxData the makers of InfluxDB
2023-09-15T21:17:42Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 4 secret-stores
2023-09-15T21:17:42Z I! Loaded inputs: procstat (10x)
2023-09-15T21:17:42Z I! Loaded aggregators: 
2023-09-15T21:17:42Z I! Loaded processors: converter override (4x) regex
2023-09-15T21:17:42Z I! Loaded secretstores: 
2023-09-15T21:17:42Z I! Loaded outputs: influxdb_v2
2023-09-15T21:17:42Z I! Tags enabled: host=brain.home.sdalu.com
2023-09-15T21:17:42Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"brain.home.sdalu.com", Flush Interval:30s
2023-09-15T21:17:42Z D! [agent] Initializing plugins
2023-09-15T21:17:42Z D! [agent] Connecting outputs
2023-09-15T21:17:42Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2023-09-15T21:17:42Z D! [agent] Successfully connected to outputs.influxdb_v2
2023-09-15T21:17:42Z D! [agent] Starting service inputs
2023-09-15T21:18:13Z D! [outputs.influxdb_v2] Wrote batch of 10 metrics in 243.505683ms
2023-09-15T21:18:13Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.28.0 FreeBSD 13.2 arm64

### Steps to reproduce

1. run the configuration

### Expected behavior

Some `procstat` and `procstat_lookup` metrics, like:
~~~
> procstat,host=rork.home.sdalu.com,org_destination=IT,process_name=telegraf,user=telegraf cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_system=2654.42098,cpu_time_user=816.839403,cpu_usage=0.035786768916299505,created_at=1694607213273000000i,memory_data=0i,memory_locked=0i,memory_rss=193368064i,memory_stack=0i,memory_swap=0i,memory_usage=0.37625008821487427,memory_vms=5346725888i,num_threads=32i,pid=2422i,ppid=2421i,read_bytes=0i,read_count=1115i,write_bytes=0i,write_count=0i 1694812868000000000
> procstat_lookup,host=rork.home.sdalu.com,org_destination=IT,result=success pid_count=1i,result_code=0i,running=1i 1694812868000000000
~~~

### Actual behavior

Only `procstat_lookup` is generated, no `procstat`

### Additional info

Don't know if behaviour is specific to `arm64` or the whole arm family.
Tested on `amd64`, and it's working fine, so it is not specific to FreeBSD

**Comment by powersj** [comment]
Hi,

As I mentioned in the previous issue we do not provide an arm64 build for FreeBSD, so to work on this I would need you to build and test PRs.

The `procstat` metric is generated in the [addMetric](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/procstat.go#L129) function here.

> procstat_lookup,host=rork.home.sdalu.com,org_destination=IT,result=success pid_count=1i,result_code=0i,running=1i 1694812868000000000

Is this the actual output of procstat_lookup? Before diving much further into this I want to be certain that running is actually non-zero. If it is zero, then there will be no `procstat` metric generated or if there were any errors updating the processes.

Finally, the data is all gathered via gopsutil's library, so I think we should try outside of telegraf as well.

If you create a directory and create two files:

main.go:

```go
package main

import (
	"fmt"
	"os"

	"github.com/shirou/gopsutil/process"
)

func main() {
	currentPid := os.Getpid()
	myself, err := process.NewProcess(int32(currentPid))
	if err != nil {
		panic(err)
	}
	fmt.Println(myself.Name())
	fmt.Println(myself.String())
	fmt.Println(myself.NumThreads())
	fmt.Println(myself.RlimitUsage(true))
	fmt.Println(myself.Status())
}
```

go.mod - replace the go version with whatever you have locally:

```
module test-process

go 1.21
```

And either run this directly via `go run .` or build it `go build .` and run the `test-process` binary.

**Comment by sdalu** [comment]
Sorry for the late answer

> 
> > procstat_lookup,host=rork.home.sdalu.com,org_destination=IT,result=success pid_count=1i,result_code=0i,running=1i 1694812868000000000
> 
> Is this the actual output of procstat_lookup? Before diving much further into this I want to be certain that running is actually non-zero. If it is zero, then there will be no `procstat` metric generated or if there were any errors updating the processes.
> 

Yes that's actual output

> Finally, the data is all gathered via gopsutil's library, so I think we should try outside of telegraf as well.
> [...]
> And either run this directly via `go run .` or build it `go build .` and run the `test-process` binary.

Output is:
~~~
 <nil>
{"pid":91329}
0 <nil>
[] not implemented yet
 <nil>
~~~

**Comment by powersj** [comment]
Gopsutil is providing a nil name and other metrics, which means we are skipping the process. [Here is the code in Telegraf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/procstat.go#L310-L313), which checks for the nil name and commets that if this is nil we assume we are not getting anything else. Which based on the output, seems to also return default values or nil.

I would suggest an upstream issue as part of the gopsutil project to get this added or enabled there. You can use the example code I provided in my previous comment of a way to reproduce.

**Comment by powersj** [comment]
@sdalu,

I have put up https://github.com/influxdata/telegraf/pull/15272 which includes an update to gopsutil library. Your upstream issue appears to have been fixed back in March so it is likely that our last release already has this fix. Could you please download artifacts from that PR, which will be attached as a comment ~30mins from this message, and let me know if this resolves this issue?

Thanks!

**Comment by sdalu** [comment]
I don't see any more blank panels in my Grafana board, it seems fixed.
