### ISSUE TITLE
Add support for `data_format` to outputs.stackdriver

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13959]
### Use Case

The GMP/Google API is picky about the naming convention it receives when sending to GMP. Since it's built using the [Prometheus data](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) model it can only accept metrics using this regex pattern `[a-zA-Z_:][a-zA-Z0-9_:]*` 

Currently I'm using this regex processor to handle for this: 
```
    [[processors.regex]]
      # Rename metric names (measurement names) that don't match Prometheus requirements
      [[processors.regex.metric_rename]]
        pattern = "[^a-zA-Z0-9_]+"
        replacement = "_"

      # Rename tag keys that don't match Prometheus requirements
      [[processors.regex.tag_rename]]
        pattern = "[^a-zA-Z0-9_]+"
        replacement = "_"

      # Rename field keys that don't match Prometheus requirements
      [[processors.regex.field_rename]]
        pattern = "[^a-zA-Z0-9_]+"
        replacement = "_"
 ```

It would be great to be able to use the Prometheus or Prometheus Remote Write serializers to sanitize the metrics automatically. 

### Expected behavior

Send metrics that don't adhere to the Prometheus data model. Those metrics pass through the desired serializer specified in the output config and are corrected. Metrics are sent and accepted by the GMP API as expected.

### Actual behavior

The `data_format` option doesn't appear to do anything and when I look in the code I don't see what appears the be the required function:

```
func (f *Stackdriver) SetSerializer(serializer serializers.Serializer) {
	f.serializer = serializer
}
```

**Comment by powersj** [comment]
In outputs where we use the serializer (e.g. influxdb, file, http) telegraf will send the metric to get serialized, then take that result, a `[]byte`, and send those bytes or string.

Stackdriver output is special. This output takes the batch of metrics and pieces together a TimeSeries gRPC message. The message is made up of a group of metrics which is a type+labels, resources made up of type+labels, and points made up of intervals and values, as well as a kind.

If we were to serialize the metrics it would not do as any good as we would toss the byte array and still have to go through the above process.

Your current solution can continue to work.

Before I propose anything though, what is the behavior when a metric or field is named with these invalid characters? Does the whole batch get discarded? Error from stackdriver?

**Comment by crflanigan** [comment]
Hi Josh,

When metrics that run afoul with the naming convention you see a lot of these errors:

```
E! [agent] Error writing to outputs.stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: prometheus_target{job:test,cluster:st0603,namespace:store,location:us-west1-b,instance:hostaname} timeSeries[0-3,5,6,8,10,11,14,18,24]: prometheus.googleapis.com/prod.compute_services.machine_metrics.win_diskio_Percent_Disk_Write_Time_gauge/gauge{objectname:LogicalDisk,host:telegraf-5b7c69f8db-8xlwk,env:Production_Windows}; Field timeSeries[12] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[17] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[4] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[13] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[9] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[21] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[22] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[23] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[19] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[25] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[15] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[20] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[7] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[16] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.
```

**Comment by powersj** [comment]
> Field timeSeries[12] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.

This message reads like you wrote too fast?

I am asking because are we certain we are getting an error about an invalid name? I tried some metric and field names with a hyphen:

```s
metric-foo value-foo=43 1695239090000000000
2023-09-20T19:44:51Z D! [outputs.file] Wrote batch of 1 metrics in 26.37µs
2023-09-20T19:44:51Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-09-20T19:44:56Z D! [outputs.stackdriver] Wrote batch of 1 metrics in 5.197958906s
2023-09-20T19:44:56Z D! [outputs.stackdriver] Buffer fullness: 0 / 10000 metrics
```

And that seems to write sucessfully.

**Comment by crflanigan** [comment]
Well, the sending metrics too fast error is a little different:

E! [outputs.stackdriver] Unable to write to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: prometheus_target{namespace:store,location:us-west1-b,job:Telegraf,cluster:st0603,instance:st0603} timeSeries[0-115]: prometheus.googleapis.com/win_process_Percent_Processor_Time_gauge/gauge{objectname:Process,host:telegraf-5cdc787bff-8rnll,job:inputs.win_perf_counters,role:${THDRole},instance:hostname,entity:CSFalconContainer}

The hyphen was shown as invalid when we try to send metrics using a tag called `project-id`. Here's an example I found in my history:

2023-09-06T00:35:05Z E! [agent] Error writing to outputs.stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[1].metric.labels had an invalid value of "project-id": Label key contains invalid characters.;

**Comment by powersj** [comment]
ok I was able to reproduce when I added a tag:

```
metric-foo,tag-foo=foobar value-foo=43 1695240780000000000
2023-09-20T20:13:00Z D! [outputs.stackdriver] received 1 metrics
2023-09-20T20:13:00Z D! [outputs.stackdriver] split into 1 groups by timestamp
2023-09-20T20:13:00Z D! [outputs.file] Wrote batch of 1 metrics in 32.57µs
2023-09-20T20:13:00Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[0].metric.labels had an invalid value of "tag-foo": Label key contains invalid characters.
error details: name = Unknown  desc = total_point_count:1 errors:{status:{code:3} point_count:1}
 - message: One or more TimeSeries could not be written: Field timeSeries[0].metric.labels had an invalid value of "tag-foo": Label key contains invalid characters.
```

This makes me hesitate to modify the metric name or field name, as only the label name complained?

**Comment by crflanigan** [comment]
If I look at the docs this is what I'm seeing:

Every time series is uniquely identified by its metric name and optional key-value pairs called labels.

The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.

Note: The colons are reserved for user defined recording rules. They should not be used by exporters or direct instrumentation.

Labels enable Prometheus's dimensional data model: any given combination of labels for the same metric name identifies a particular dimensional instantiation of that metric (for example: all HTTP requests that used the method POST to the /api/tracks handler). The query language allows filtering and aggregation based on these dimensions. Changing any label value, including adding or removing a label, will create a new time series.

Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ (two "_") are reserved for internal use.

Label values may contain any Unicode characters.

A label with an empty label value is considered equivalent to a label that does not exist.



Wouldn't the `prod.compute_services.machine_metrics.` error apply to the metric name?

**Comment by powersj** [comment]
Can you give me a link to these docs please? If these rules were enforced I would expect to get a failure:

```
_metric:foobar _myvalue=42 1695308520000000000
__metric:foo+bar __myvalue=42 1695308520000000000
metric:foo--bar my--value=42 1695308520000000000
2023-09-21T15:02:03Z D! [outputs.stackdriver] received 3 metrics
2023-09-21T15:02:03Z D! [outputs.stackdriver] split into 1 groups by timestamp
2023-09-21T15:02:03Z D! [outputs.file] Wrote batch of 3 metrics in 56.3µs
```

![Screenshot from 2023-09-21 09-03-24](https://github.com/influxdata/telegraf/assets/6453401/ab110a85-be1f-4d17-83f8-e3bca04b520c)

The reason I am challenging this is most importantly I do not want to break existing users who could not be following these rules. 

Additionally, if we do not get an error back I am not sure why we should start enforcing these rules as well. We could look at making something like this opt-in, but I want to also see a reference to these rules.

Thanks!

**Comment by crflanigan** [comment]
Sure buddy, [here's](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) the docs. 

And to be clear, I have seen the metrics get into Google (though it seems to be inconsistent), but if you try to query them using Grafana they will error. 

<img width="424" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/c20b9ba8-f28e-49d4-a991-d21f16938a69">

<img width="1102" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/e8f5af62-8556-44a7-a135-b0659149be04">


If you have concerns about impacting existing users then I don't see a problem with just staying with my current regex processor design. When I put in the Issue I really only meant to enable the use of one of the serializers, not change the behavior of the plugin.

**Comment by powersj** [comment]
> If you have concerns about impacting existing users then I don't see a problem with just staying with my current regex processor design.

I think this is the right answer.

> Sure buddy, [here's](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) the docs.

Heh I thought you were going to point at some Stackdriver doc, I didn't realize you were going right for the prometheus docs.

> The GMP/Google API is picky about the naming convention it receives when sending to GMP. Since it's built using the [Prometheus data](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) model it can only accept metrics using this regex pattern [a-zA-Z_:][a-zA-Z0-9_:]*

I think I misread this, as I took it to mean that the Stackdriver API was picky about naming and only accepted prometheus based naming.

**Comment by crflanigan** [comment]
Ah gotcha, yeah, that's fine. I will close this, thanks for taking a look though!
