### ISSUE TITLE
RabbitMQ Input secretstore support

### ISSUE THREAD

**Issue by yonathanamir** [influxdata/telegraf#13956]
### Use Case

Currently authentication with the RabbitMQ broker is supported with the username and password options for the RabbitMQ Input plugin only as plain strings, and not with secretstore support even though they can be considered vital secrets.

### Expected behavior

RabbitMQ input should support secretstore for username and password.

### Actual behavior

RabbitMQ input plugin does not support using the secret store for the username and password options.

**Comment by powersj** [comment]
Thanks for the issue and PR

next steps: review PR
