### ISSUE TITLE
inputs.tail do not work under redhat el5 !

### ISSUE THREAD

**Issue by abarban** [influxdata/telegraf#1395]
Hi,
2 different problem with inputs, tail plugin:

- errot on startup:

```
2016/06/21 17:51:44 Seeked /var/log/httpd/20160621-influx_log - &{Offset:0 Whence:0}
2016/06/21 17:51:44 FATAL -- failed to create Watcher
goroutine 66 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/hpcloud/tail/util.Fatal(0x13a5d60, 0x18, 0x0, 0x0, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/util/util.go:21 +0xbc
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc820727480)
	/home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:230 +0x85
created by github.com/hpcloud/tail/watch.glob.func1
	/home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:53 +0x230
```

- when read the file, do not insert nothing on influx:

```
2016/06/21 10:48:32 Agent Config: Interval:10s, Debug:true, Quiet:false, Hostname:"host", Flush Interval:10s
2016/06/21 10:48:40 Input [tail] gathered metrics, (10s interval) in 70.552Âµ
2016/06/21 10:48:50 Input [tail] gathered metrics, (10s interval) in 32.399Âµ
2016/06/21 10:48:50 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
2016/06/21 10:49:00 Input [tail] gathered metrics, (10s interval) in 30.729Âµ
2016/06/21 10:49:00 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
2016/06/21 10:49:10 Input [tail] gathered metrics, (10s interval) in 22.839Âµ
2016/06/21 10:49:10 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
```

Influx 1.0.0.beta1
Telegraf 1.0.0.beta1
RedHat EL5 64bit

file example:

```
httpdhit,virtual=xxx time_taken=474970,status=200 1466524500000000000
httpdhit,virtual=xxx time_taken=58032,status=200 1466524501000000000
httpdhit,virtual=xxx time_taken=517798,status=200 1466524501000000000
httpdhit,virtual=x time_taken=276772,status=200 1466524517000000000
```

**Comment by abarban** [comment]
[[inputs.tail]]
files = ["/var/log/httpd/20160621-influx_log"]
from_beginning = true
data_format = "influx"

The other parts all work!

**Comment by abarban** [comment]
It could be due to the compilation with go 1.6.x which is not compatible with 2.6.18 kernel?

**Comment by sparrc** [comment]
I wasn't aware go 1.6.2 is incompatible with kernel 2.6.18, do you have a reference for that?

**Comment by abarban** [comment]
Here https://golang.org/dl/ there is a reference on Linux download for kernel 2.6.23 or later.
Do you think it's possibile to try compile with older version?

**Comment by sparrc** [comment]
probably, but it won't be officially supported

**Comment by abarban** [comment]
Ok!
Unfortunately I still have many servers RedHat EL5!
I'll try to compile it! I'm trying to configure TAIL or LOGPARSER to have response code and time_taken from apache/nginx log, to live monitoring performance.

**Comment by abarban** [comment]
Tested on last update of EL5 - 5.11 kernel 2.6.18-410, with same errors.
Compiled with Go 1.5.4 under EL6, same results.
Would try to compile under EL5 with Go 1.5.4.
If nothing can work good, I'll try a dedicated solution only to stream this type of log.

**Comment by johankcarlsson** [comment]
I just got the same problem/symptom.
See logs below.
If I have "from_beginning = true" it manage to read a lot of lines before it fails. If it is "false" that it fails directly.
I run:
Red Hat Enterprise Linux Server release 5.11
Telegraf - version 1.0.1


2016/10/07 16:08:59 Output [file] wrote batch of 1000 metrics in 11.952114ms
2016/10/07 16:08:59 FATAL -- failed to create Watcher
goroutine 15 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/hpcloud/tail/util.Fatal(0x16069c0, 0x18, 0x0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/util/util.go:21 +0xbc
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc820caccc0)
        /home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:230 +0x85
created by github.com/hpcloud/tail/watch.glob.func1
        /home/ubuntu/telegraf-build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:53 +0x230

[[inputs.logparser]]
  ## file(s) to tail:
  files = ["/var/opt/pws/log/smart.log"]
  from_beginning = true
  name_override = "smart_soap"
  ## For parsing logstash-style "grok" patterns:
  [inputs.logparser.grok]
    #patterns = ["%{COMBINED_LOG_FORMAT}"]
	patterns = ["%{CUSTOM_LOG}"]
    custom_patterns = '''
      CUSTOM_LOG %{TIMESTAMP_ISO8601:thetime}%{SPACE}%{LOGLEVEL:loglevel}%{SPACE}%{NOTSPACE}%{NOTSPACE}%{SPACE}%{NOTSPACE}%{SPACE}%{NOTSPACE}%{SPACE}<<<<<<<<<<<<<<<<<<< \|%{WORD:status}\|%{SPACE}%{NOTSPACE}%{SPACE}%{WORD:service}.%{WORD:method}%{SPACE}Partner:%{SPACE}%{DATA:partner}.%{SPACE}msisdn:%{SPACE}%{DATA:msisdn},%{GREEDYDATA}Duration:%{SPACE}%{DATA:duration}ms,%{SPACE}Size:%{SPACE}%{DATA:size}'''

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

**Comment by toni-moreno** [comment]
As I know golang tools are not supported below Centos/RHEL 6. See yourself at https://golang.org/doc/install

**Comment by johankcarlsson** [comment]
OK, sorry I missed that

**Comment by toni-moreno** [comment]
Ops. Sorry, supported linux version had been commented before in this thread...

**Comment by toni-moreno** [comment]
Have you tried yourself compile the golang tools from source code over RHEL 5 Instead of download precompiled packages and after compile telegraf with your own go on rhel5 ?

**Comment by sparrc** [comment]
I'm going to close out the issue because it sounds like it's a Go compatability problem. You can continue to discuss workarounds as needed, but we won't be fixing this in Telegraf.

**Comment by johankcarlsson** [comment]
No I have not tried to compile the binaries on RHEL5. I'm lazy so I will use Logstash/Elastic in this specific case and save Telegraf/Logparser for other servers running newer versioins of RHEL.

**Comment by toni-moreno** [comment]
@johankcarlsson Hi ,  I'm missing something , are you migrating tom ELK to TICK ?  I would like to know about your experience... can I contact you in any way?

Thank-you.

**Comment by johankcarlsson** [comment]
Actually I was testing Telegraf logparser for the first time. We have earlier experience of Logstash/Elastic but now I wanted to test Telegraf/InfluxDB, since I realy like the Influx stack.
I will test it on some other servers. :-)

**Comment by johankcarlsson** [comment]
Just want to add that I find Influx stack A lot easier to work with then ElasticSearch. But of course Elastic is probably more suitable for logdata with much text.
