### ISSUE TITLE
AMQP Consumer Input secretstore support

### ISSUE THREAD

**Issue by yonathanamir** [influxdata/telegraf#13955]
### Use Case

Currently authentication with the AMQP broker is supported by the in both the AMPQ input and output, however, only the output supports using the secretstore for these values.

### Expected behavior

AMQP Consumer input should support secretstore for username and password just like the AMQP output plugin.

### Actual behavior

AMQP Consumer input plugin does not support using the secret store for the username and password options.

**Comment by powersj** [comment]
Thanks for the issue and PR

next steps: review PR
