### ISSUE TITLE
processors.lookup enhancement

### ISSUE THREAD

**Issue by richardeaxon** [influxdata/telegraf#13967]
### Use Case

I have a lengthy list of value replacements that I need to do for a field. The source is from various log files read via inputs.tail where I am trying to normalize data from various sources into a common format. I then tried using lookup which allows me to use our original source CSV data. Works fine except that a new tag is created, not a new field or field replacement.

### Expected behavior

Allow lookup to in-place replace or create a new field, not just new tags.

### Actual behavior

N/A

### Additional info

Is there another way to achieve what I require that I have overlooked?

**Comment by powersj** [comment]
Hi,

Unfortunately the lookup processor only supports the addition of tags. Could you provide an example metric in line protocol and example expected behavior please? Then we could possible provide an actual example.

**Comment by richardeaxon** [comment]
Sample log:

```
2023-09-17T03:42:14.558986+10:00 device1.net [Local] 10.67.11.35 2c:4a:11:52:25:70 device1 EVENT-ID:20-004 PORT-4-STATE_CHANGE: port(port 1/4.1): :operState enabled
2023-09-17T03:42:14.559247+10:00 device1.net [Local] 10.67.11.35 2c:4a:11:52:25:70 device1 EVENT-ID:20-004 PORT-4-STATE_CHANGE: port(port 1/4.1): :linkState Up
2023-09-17T03:42:14.561970+10:00 device1.net [Local] 10.67.11.35 2c:4a:11:52:25:70 device1 EVENT-ID:62-046 PTP-4-STATE_CHANGE: ptp(ptp 1/5.2): :PTP Up
```

telegraf.conf:

```
[[inputs.tail]]
  files = ["/home/ec2-user/log_sample/sample.log"]
  data_format = "grok"
  from_beginning = true
  grok_patterns = [
    '^%{TIMESTAMP_ISO8601:timestamp:ts} %{HOSTNAME:source}.*EVENT-ID:%{EVENT:process} %{EVENT:event}: .*\(%{DATA:resource}\): :%{GREEDYDATA:message}$'
  ]
  grok_custom_patterns = '''
    EVENT (?:[\w-]+)
  '''

[[processors.lookup]]
  files = ["/home/ec2-user/telegraf/conf/process_lut.csv"]
  format = "csv_key_values"
  key = '{{.Field "process"}}'

```

process_lut.csv:

```
-,process
20-004,aaa
62-046,bbb
```

Sample output:

```
tail,host=collector1,path=/home/ec2-user/log_sample/sample.log,process=aaa resource="port 1/4.1",message="operState enabled",source="device1.net",process="20-004",event="PORT-4-STATE_CHANGE" 1694886134558986000
tail,host=collector1,path=/home/ec2-user/log_sample/sample.log,process=aaa process="20-004",event="PORT-4-STATE_CHANGE",resource="port 1/4.1",message="linkState Up",source="device1.net" 1694886134559247000
tail,host=collector1,path=/home/ec2-user/log_sample/sample.log,process=bbb source="device1.net",process="62-046",event="PTP-4-STATE_CHANGE",resource="ptp 1/5.2",message="PTP Up" 1694886134561970000
```

Desired output is not a new tag with name "process" is created, but the field is replaced. As seen above there is now a tagname "process" and a fieldname "process".

I can use the processors.converter to copy the tag to a field again, but this just seams inefficient.

**Comment by richardeaxon** [comment]
Closing issue. I can work around the problem on the Apache Druid ingestion side.
