### ISSUE TITLE
Windows ZIP package doesnt conform to ZIP standard

### ISSUE THREAD

**Issue by Hr0bar** [influxdata/telegraf#13974]
### Steps to reproduce

1. wget https://dl.influxdata.com/telegraf/releases/telegraf-1.28.1_windows_amd64.zip
2. unzip telegraf-1.28.1_windows_amd64.zip

The above results in:
```
wget https://dl.influxdata.com/telegraf/releases/telegraf-1.28.1_windows_amd64.zip
[root@server ~]# unzip telegraf-1.28.1_windows_amd64.zip
Archive:  telegraf-1.28.1_windows_amd64.zip
warning:  telegraf-1.28.1_windows_amd64.zip appears to use backslashes as path separators
  inflating: telegraf-1.28.1/telegraf.conf
  inflating: `telegraf-1.28.1/telegraf.exe`
[root@server ~]# echo $?
1
```

### Expected behavior

ZIP windows package is valid per ZIP specification

### Actual behavior

ZIP windows package is not per ZIP specification

### Additional info

 The ZIP specification says:

   4.4.17 file name: (Variable)

       4.4.17.1 The name of the file, with optional relative path.
       The path stored MUST NOT contain a drive or
       device letter, or a leading slash.  All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility with Amiga
       and UNIX file systems etc.  If input came from standard
       input, there is no file name field.  

The actual contents are:

```
Archive:  telegraf-1.28.1_windows_amd64.zip
Zip file size: 54935075 bytes, number of entries: 2
-rw----     2.0 fat   497518 b- defN 23-Sep-12 15:16 telegraf-1.28.1\telegraf.conf
-rwx---     2.0 fat 200592888 b- defN 23-Sep-12 15:19 telegraf-1.28.1\telegraf.exe
2 files, 201090406 bytes uncompressed, 54934787 bytes compressed:  72.7%

```

The above behaviour causes many scripts/tools such as Ansible to assume error on unzip, as unzip returns RC 1 in this case.
PowerShell had same issue couple years ago: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/48

Maybe an issue with the zip command on the CI/package server? The zip command in makefile

`(cd $(dir $(DESTDIR)) && zip -r - ./*) > $(pkgdir)/telegraf-$(tar_version)_$@ ;\
`
seems OK, I tested it on various zip versions and all produced forward slashes, not backwards as happens here

**Comment by powersj** [comment]
> Maybe an issue with the zip command on the CI/package server? The zip command in makefile

After a quick look, my guess is it has to do with the signing part of CI, via [windows-signing.ps1](https://github.com/influxdata/telegraf/blob/master/scripts/windows-signing.ps1).

If I grab a nightly artifact from the [build stage](https://app.circleci.com/pipelines/github/influxdata/telegraf/18161/workflows/3db7a92d-9f21-4e81-ba2b-0f2b22cdaede/jobs/279861/artifacts), which is not signed, all looks good:

```s
❯ unzip telegraf-nightly_windows_amd64.zip 
Archive:  telegraf-nightly_windows_amd64.zip
   creating: telegraf-1.29.0/
  inflating: telegraf-1.29.0/telegraf.exe  
  inflating: telegraf-1.29.0/telegraf.conf  
❯ echo $?
0
```
