### ISSUE TITLE
ElasticSearch Plugin should support SSL configuration

### ISSUE THREAD

**Issue by mglazer** [influxdata/telegraf#1397]
## Feature Request

The ElasticSearch plugin currently doesn't support SSL as the HTTP JSON endpoint does.
### Proposal:

Make the ES plugin work with SSL.
### Current behavior:

The ES plugin fails when connecting to an SSL enabled ES node.
### Desired behavior:

The ES plugin doesn't fail.
### Use case:

All of our ES nodes run with SSL enabled. So not having this makes the ES plugin not usable.

**Comment by mglazer** [comment]
PR: https://github.com/influxdata/telegraf/pull/1398

**Comment by danielnelson** [comment]
Looks like the PR was merged so closing
