### ISSUE TITLE
feature(inputs.kafka_consumer). Override metric name from the kafka message header

### ISSUE THREAD

**Issue by BelousovAntonV** [influxdata/telegraf#13980]
### Use Case

We are using Kafka input and Avro parser in our configuration. The issue is that for the moment we have only 2 possibilities to get metric name - statically from the configuration and dynamically from the message field. For one of our solutions we can not use static metric name, because we have several different metrics in the same Kafka topic. But when we take metric name dynamically we should add this field to the message itself. I want to add possibility to add metric name from kafka header, in this case we will not duplicate this information in the fields and could take it from the message headers. 

But I need some help and discussion about this, because metric is building in the parser and only the message value pass as a parameter from input plugin to parser. Besided it could be different input used with no headers in message which is Kafka specific I think.

### Expected behavior

Set option for kafka_consumer input plugin like `override_metric_name_from_header` where the header name should be specified. In case if it is specified and found in message headers the value from this header should override the metric name. 

### Actual behavior

There is no possibility to set metric name from the message header value. 

### Additional info

I need your advise. Should I pass message headers to the avro parser as an optional parameter or is it better to override metric name in kafka_consumer plugin? From my point of view the second option is better, becase it could be used with any parser and message headers is a kafka specific functionality. But, in this case it will be necessuary to specify metric name in the parser configuration also, which could be a little bit confusing.

**Comment by powersj** [comment]
The metric name via a header should be set and done in the input, not the parser. Happy to see a PR for this.

**Comment by BelousovAntonV** [comment]
Hello @powersj, I've commited this functionality, sorry for long waiting.
