### ISSUE TITLE
Telegraf 1.27.4 modbus plugin --> record metric only if value 

### ISSUE THREAD

**Issue by tbar315** [influxdata/telegraf#14000]
### Please direct all support questsions to slack or the forums. Thank you.

Hi all,
What is the way, in telegraf with modbus plugin,  if i want to record all the metrics only if one modbus metric exced a value ?
Thanks for all.

**Comment by srebhan** [comment]
@tbar315 can you please show an example of metrics and your expected outcome?

**Comment by tbar315** [comment]
@srebhan 
`holding_registers = [
    ##{ name = "Pression_Jaune1", byte_order = "AB",   data_type = "FIXED", scale=0.01,  address = [8]},
    ##{ name = "Pression_Jaune2",      byte_order = "AB",   data_type = "FIXED", scale=0.1,   address = [0]},
    { name = "P30A_Mes_P_Jaune",     byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3018,3019]},
    { name = "P30A_Mes_P_Vert",     byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3016,3017]},
    { name = "P30A_Cons_P_Jaune",    byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3062,3063]},
    { name = "P30A_Cons_P_Vert",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3058,3059]},
    { name = "P30A_Cons_D_Jaune",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3060,3061]},
    { name = "P30A_Mes_D_Jaune",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3030,3031]},
    { name = "P30A_Cons_D_Vert",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3056,3057]},
    { name = "P30A_Mes_D_Vert",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3028,3029]},
    { name = "P30A_MW1206",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [1206]},
    { name = "P1_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3540]},
    { name = "P2_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3554]},
    { name = "P3_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3568]},
    { name = "P4_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3582]},
    { name = "P5_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3596]},
    { name = "P6_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3610]},
    { name = "PGAV1_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3512]},
    { name = "PGAV2_Etat",   byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3526]},
    { name = "Temp_Huile",      byte_order = "CDAB",  data_type = "FLOAT32-IEEE", scale=1.0, address = [3000,3001]},
	{ name = "status_install",      byte_order = "AB",   data_type = "INT16", scale=1.0, address = [3512]},
   
    
   
  ]
  
  
  [[processors.starlark]]
  ## The Starlark source can be set as a string in this configuration file, or
  ## by referencing a file containing the script.  Only one source or script
  ## should be set at once.

  ## Source of the Starlark script.
  source = '''
def apply(metric):
  var1 = int(metric.fields["P30A_MW1206"])
  ## 0x08 = bit 3 0x10 = bit4
  if var1 & 0X08 == 0x08:
   metric.fields["P30A_Select_Mat_J"] = 1
  else:
   metric.fields["P30A_Select_Mat_J"] = 0

  if var1 & 0X10 == 0x10:
   metric.fields["P30A_Select_GSP_J"] = 1
  else:
   metric.fields["P30A_Select_GSP_J"] = 0
  return metric
'''`

I want if status_install is > 0 that telegraf don't send anything to Influxdb.
It is to prevent large amount of datas recording that are not signifiant.

Thank you very much

**Comment by srebhan** [comment]
@tbar315 you can filter this in your starlark processor... Like

```toml
  [[processors.starlark]]

  source = '''
def apply(metric):
  if metric.fields.get("status_install", 0) <= 0:
    return None

  var1 = int(metric.fields["P30A_MW1206"])
 
  if var1 & 0X08 == 0x08:
   metric.fields["P30A_Select_Mat_J"] = 1
  else:
   metric.fields["P30A_Select_Mat_J"] = 0

  if var1 & 0X10 == 0x10:
   metric.fields["P30A_Select_GSP_J"] = 1
  else:
   metric.fields["P30A_Select_GSP_J"] = 0
  return metric
'''
```

**Comment by tbar315** [comment]
Thank you very much for your reply.
regards

**Comment by srebhan** [comment]
@tbar315 does it solve your problem?

**Comment by tbar315** [comment]
I will try it tomorrow .. i'm in another project. 
Thanks a lot.

**Comment by srebhan** [comment]
Feel free to reopen the issue if you cannot find a solution!
