### ISSUE TITLE
In input.intel_pmt add pci_bdf tag to uniquely identify GPUs and other peripherals

### ISSUE THREAD

**Issue by bensallen** [influxdata/telegraf#14003]
### Use Case

In the current intel_pmt plugin, the `numa_node` of the intel_pmt device is used as a way to uniquely identify which CPU socket the sample belongs to. However, with GPUs and other future peripherals, an additional tag is needed to uniquely identify samples.

### Expected behavior

Add the parent of intel_pmt's device PCI Bus:Device.Function (BDF) as the tag `pci_bdf` for example 

```
pci_bdf=0000:e7:03.1
```

### Actual behavior

Nothing but the `numa_node` tag is used to uniquely identify a sample in intel_pmt, when there are multiple devices of the same GUID.

**Comment by powersj** [comment]
next steps: get intel to review PR
