### ISSUE TITLE
When metrics pass through inputs/outputs.opentelemetry they have `_gauge` added as a field in the metric

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#14027]
### Use Case

It's undesirable to have `_gauge` appened to the metric name when it passes through the opentelmetry plugins, where you then pass the metrics to another output plugin. 

Example:

A metric is sent from a Telegraf agent to a Telegraf server using inputs/outputs opentelemetry plugin. 

When you send the metric from Telegraf it looks something like this:

```
processes,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes idle=0i,blocked=0i,zombies=1i,stopped=0i,running=5i,sleeping=481i,total=488i,unknown=1i 1696036270000000000
```

When it is received and passed through the opentelemetry plugins it looks like this:

```
processes_blocked,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=0i 1696036270000000000
processes_zombies,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=1i 1696036270000000000
processes_stopped,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=0i 1696036270000000000
processes_running,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=5i 1696036270000000000
processes_sleeping,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=481i 1696036270000000000
processes_total,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=488i 1696036270000000000
processes_unknown,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=1i 1696036270000000000
processes_idle,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=0i 1696036270000000000
```

Note the `gauge` metric remapping. 

This eventually generates a metric name (using outputs.stackdriver) that looks like this:

`prometheus/processes_idle_gauge/gauge` 

Or when visualized looks like this:

`processes_idle_gauge`

It would be great if there was a processor which could map the (in this case) `processes_idle` part in the metric as it's passing down the telegraf pipeline that replaces `gauge` with the actual measurement, or modify the opentelemetry plugin such that you can indicate you don't wish the metric name to be remapped to gauge. 

### Expected behavior

Send metrics into a telegraf server using the inputs/outputs opentelemetry plugins. 
The metrics are sent to their requisite outputs.
The metrics are sent without `_gauge` appended to the metric. 

### Actual behavior

Metrics have `_gauge` appended to the metric.

While it's not the end of the world, it's a bit weird for end users to have to search for metrics with the extra `_gauge` bit at the end of the metrics.

**Comment by crflanigan** [comment]
Issue submitted @powersj

**Comment by powersj** [comment]
Hi,

> The metrics are sent without _gauge appended to the metric.

This is a consequence of using the open telementry output. As mentioned in the plugin's readme schema section: when metrics are serialized the metric name needs to get serialized into Prometheus style and as such becomes `measurementName + field name`. For example:

```s
mem total_mem=42,used_mem=2
```

becomes

```s
mem_total_mem gauge=42
mem_used_mem gauge=2
```

These later metrics are what ends up in stackdriver, which then constructs the metric name based on the name format option:

```
# path/default
prefix/namespace/metricName/fieldName

# official
namespace_metricName_fieldName
```

> It would be great if there was a processor which could map the (in this case) processes_idle part in the metric as it's passing down the telegraf pipeline that replaces gauge with the actual measurement, 

When you say map, how would you see this happening? Split on the underscore?

Keep in mind, you could still pass a non-flatten metric (e.g. `mem total_mem=42,used_mem=2`) to the Stackdriver output. In which case, we absolutely need to take both the field name into account to correctly namespace the names.

> or modify the opentelemetry plugin such that you can indicate you don't wish the metric name to be remapped to gauge.

We still need some field name. What would you want this to be if not gauge?

**Comment by powersj** [comment]
> I'm not totally sure how it all will work, it's just a little weird to have gauge in the metric.

I don't disagree, but it has to be named something :)

I certainly do not want to hard-code or even provide an option in stackdriver that takes metric field's named "gauge" and tosses them. Have you found that using the opentelementry output/input is worth the cost of renaming versus say using the http output + http_listener_v2 input?

**Comment by crflanigan** [comment]
Hey buddy,

The design desiion for using outputs/inputs.opentelemetry is due to the flexibility of other applications instrumented in the opentelemetry format being able to send to the proxy. We're kind of locked in at this point. It sounds like there's nothing to be done here?

**Comment by powersj** [comment]
> It sounds like there's nothing to be done here?

The other option you possibly have is to use metric version 1 instead of 2. Instead of renaming the metric field, all metrics produced are called "prometheus" and then field name is left unchanged.

This would mean that your metrics in Stackdriver would show up as: `prometheus_total_mem/gauge` instead of `total_mem_gauge/gauge`.

Otherwise I think the rename processor is something you could use to replace gauge with something more generic.

Thoughts?

**Comment by crflanigan** [comment]
Ok, so if we use version two `prometheus` would be prepended to the metric and version one would append the `gauge` to the metric?

**Comment by powersj** [comment]
> Ok, so if we use version two prometheus would be prepended to the metric and version one would append the gauge to the metric?

Yeah take a look at the different metrics produced with the two versions listed on the [prometheus readme](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus#output).

> I was thinking a processor too. Basically inputs.opentelemetry -> processor to normalize the metrics
-> outputs.stackdriver.

How would you like to see the processor transform the metric? Can you fill in the diff for this metric:

```diff
- processes_blocked,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes gauge=0i 1696036270000000000
```

**Comment by crflanigan** [comment]
Hey buddy,

When I look at this in my mind ideally it should be something like:

`-MetricPrefix ,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes processes_blocked=0i 1696036270000000000`

Where the metric prefix is `process` or in our case `win_process`.

Does that make sense?

**Comment by powersj** [comment]
> Where the metric prefix is process or in our case win_process.
> Does that make sense?

Not sure :) You are referring to the metric name as the metric prefix? I want to be clear, that in line protocol that very first field is literally the name of the metric and not some prefix. We do have another setting for creating a metric prefix (e.g. `name_prefix`).

We have the rename processor today, but you have to know what you want to rename things as. Because you are trying to rename dynamically, I would use starlark:

```s
[[processors.starlark]]
  source = '''
def apply(metric):
  if "gauge" in metric.fields:
    metric.fields[metric.name] = metric.fields["gauge"]
    metric.fields.pop("gauge")
    metric.name = "win_process"

  return metric
'''
```

This issue is knowing what to rename the metric as, in case you have metrics from multiple metric sources.

**Comment by crflanigan** [comment]
Ok, I will have to test using starlark. 
I guess we can close this for now, unless you want to leave it open in case someone in the community has any other thoughts.

Thanks!

**Comment by powersj** [comment]
ok! Let me know if you run into any issues with the above.

**Comment by eero-t** [comment]
OpenTelemetry has a spec on how its data is converted to OpenMetrics and Prometheus formats and back: https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/

**Comment by crflanigan** [comment]
Hey all,

We ended up modifying how metrics coming directly from outputs.stackdriver to Prometheus/GMP were sent to match how the metrics are renamed by inputs/outputs.opentelemetry. 

This is the code we used to make it work in our preliminary testing:

```
[[processors.starlark]]
  source = '''
def apply(metric):
    for field_name in list(metric.fields.keys()):
        # Perform operations on each field
        metric.fields[field_name + "_gauge"] = metric.fields.pop(field_name)
    return metric
 '''
 ```
 
 Hopefully this helps someone.
