### ISSUE TITLE
telegraf.snmp - Multiple Community 

### ISSUE THREAD

**Issue by euphoplat** [influxdata/telegraf#14029]
### Please direct all support questsions to slack or the forums. Thank you.

Hi !

I have an environment with two SNMP Community.
First in v2, other in v3.

I don't find how to configure two snmp community.
I've tried to configure like this : 
[[inputs.snmp.2]]
or
[[inputs.snmp2]]

but nothing work.

First question : It's possible ? 
Second question : How ? 

Thanks !

**Comment by powersj** [comment]
Good answer in the forums: https://community.influxdata.com/t/telegraf-snmp-multiple-community/31693/2

closing as answered over there.
