### ISSUE TITLE
New Telegraf Build with GOVMOMI 3.1.0

### ISSUE THREAD

**Issue by Muy69** [influxdata/telegraf#14020]
### Use Case

With the new Build of GOVMOMI the API were added , vsphere 8u1c are now supported. 

https://github.com/vmware/govmomi/releases/tag/v0.31.0

### Expected behavior

New Build will enable the Vsphere / vsan Extention to provide 30sec Telemetrie Data + VSAN ESA compatible Metrics

### Actual behavior

Currently only Telemetry Data are deliverd as of vSphere 8 GA ( only )  which are 300s compare to 30s

### Additional info

I have the ability to test the Telegraf in a VSAN ESA ( vsphere 8u1 ) Enviroment

**Comment by powersj** [comment]
@Muy69,

Can you point to what issue or PR in that release changes that enables the increased delivery?

I have put up https://github.com/influxdata/telegraf/pull/14022 which updates the library. In addition to the above question, please give this a shot. It is a rather large update in versions, so I am curious to see if anything else changed or broke between versions.

Thanks

**Comment by powersj** [comment]
> If you update the Library anyway with the next build , then there is no increased delivery necessary .

Again, can you point to why you think this is fixed in the upstream library. I would like to see an issue, commit, or something similar.

**Comment by srebhan** [comment]
@powersj the update for GA 8.0 U1 (and U2) was already added in [v0.31.0](https://github.com/vmware/govmomi/releases/tag/v0.31.0) and this issue is a follow-up on #13890...

**Comment by powersj** [comment]
@Muy69 what I was after is knowing that there is actually a change in the upstream library that you know will fix your issue. It does appear to be these changes:

* https://github.com/vmware/govmomi/commit/a03f4735570027d2e6e2bc9cb7584a0af19f9353 Fix errors w 8.0U2 GA update
* https://github.com/vmware/govmomi/commit/515df5df534fae9704cba6cd3c7f03f91fec1942 Update generated types to vSphere 8.0U2 GA
* https://github.com/vmware/govmomi/commit/b7ceedeabe58705badc3b7eb8b2194fe2f8b82ce Prep to update types to vSphere 8.0U2 GA
* https://github.com/vmware/govmomi/commit/ccd07a015a0e614118a9075f423f5992fad6dc32 Update generated types to vSphere 8.0U1c GA
* https://github.com/vmware/govmomi/commit/4c00586f9b552873b1e78ce9a04d47e992b962cd Prep to update types to vSphere 8.0U1c GA

This library has not been updated in a ~year. combined with our inability to properly support vmware and the wide use cases of this plugin, I am not thrilled at blindly updating to a newer version without seeing and understanding that it actually fixes the issue.

Please try the PR artifacts once up and let us know.
