### ISSUE TITLE
Add user agent headers to Azure Data Explorer

### ISSUE THREAD

**Issue by ag-ramachandran** [influxdata/telegraf#14046]
### Use Case

To troubleshoot issues when customers are using the Azure Data Explorer plugin, add a set of additional headers that contain information on IngestiontType used and if TablePerMetric options are used

### Expected behavior

Given a cluster URI, we can find the IngestionType and TablePerMetric types and look at the telemetry data coming in for troubleshooting

### Actual behavior

This feature does not exist. We have to go to the Customer to get these details to start troubeshooting

**Comment by powersj** [comment]
next steps: final review on PR
