### ISSUE TITLE
telegraf.service mask reversed by post-install.sh on Debian systems

### ISSUE THREAD

**Issue by palash-delphix** [influxdata/telegraf#14052]
### Relevant telegraf.conf

```toml
Not applicable
```

### Logs from Telegraf

```text
Not applicable
```

### System info

Ubuntu 20.04

### Steps to reproduce

1. Install an older version of telegraf's debian package 
2. Mask `telegraf.service` using `systemctl mask --now telegraf.service`
3. Upgrade telegraf to the latest version
4. Notice that `telegraf.service` is now enabled.

### Expected behavior

`telegraf.service` should remain masked.

### Actual behavior

`telegraf.service` is enabled

### Additional info

According to the [man page](https://manpages.debian.org/jessie/systemd/systemd.unit.5.en.html), the recommended area for systemd unit files managed by the package is `/lib/systemd/system`.  `systemctl mask` creates a symlink in such a manner:
```
$ sudo systemctl mask --now telegraf.service
Created symlink /etc/systemd/system/telegraf.service → /dev/null.
```

But since the [post-install.sh](https://github.com/influxdata/telegraf/blob/master/scripts/deb/post-install.sh#L29) removes `/etc/systemd/system/telegraf.service`, the `mask` operation is essentially reversed allowing the service to start again.

**Comment by palash-delphix** [comment]
@powersj  We roll our own version of the service that fits our needs (like service dependencies, configuration etc) which is why we mask the stock telegraf service.

**Comment by palash-delphix** [comment]
@powersj thanks for the quick fix. Can you confirm the release cadence of the telegraf package? I see that y'all release on a monthly schedule afaict but just want to confirm if we should implement a workaround for this issue.

**Comment by powersj** [comment]
If you look at the PR you will see it attached to a milestone with a date ;)

https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#when-is-the-next-release-when-will-my-pr-or-fix-get-released
