### ISSUE TITLE
[[inputs.jenkins]] job_include does not work for jobs inside folders

### ISSUE THREAD

**Issue by BlocDrummer** [influxdata/telegraf#14054]
### Relevant telegraf.conf

```toml
[[inputs.jenkins]]
  url = "https://myjenkins.com"
  username = "xxx"
  password = "xxx"
  job_include = ["myfolder/myjob"]
```

### Logs from Telegraf

```text
telegraf -test -config jenkins.conf --debug
2023-10-05T16:49:27Z I! Loading config: jenkins.conf
2023-10-05T16:49:27Z I! Starting Telegraf 1.28.2 brought to you by InfluxData the makers of InfluxDB
2023-10-05T16:49:27Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-10-05T16:49:27Z I! Loaded inputs: jenkins
2023-10-05T16:49:27Z I! Loaded aggregators:
2023-10-05T16:49:27Z I! Loaded processors:
2023-10-05T16:49:27Z I! Loaded secretstores:
2023-10-05T16:49:27Z W! Outputs are not used in testing mode!
2023-10-05T16:49:27Z I! Tags enabled: host=myhost.com
2023-10-05T16:49:27Z D! [agent] Initializing plugins
2023-10-05T16:49:27Z D! [agent] Starting service inputs
> jenkins,host=myhost.com,port=443,source=myjenkins.com busy_executors=2i,total_executors=55i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=Built-In\ Node,port=443,source=myjenkins.com,status=online num_executors=0i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=mynode1,port=443,source=myjenkins.com,status=online num_executors=5i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=mynode2,port=443,source=myjenkins.com,status=online num_executors=5i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=mynode3,port=443,source=myjenkins.com,status=online num_executors=15i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=mynode4,port=443,source=myjenkins.com,status=online num_executors=15i 1696524568000000000
> jenkins_node,host=myhost.com,node_name=mynode5,port=443,source=myjenkins.com,status=online num_executors=15i 1696524568000000000
2023-10-05T16:49:27Z D! [agent] Stopping service inputs
2023-10-05T16:49:27Z D! [agent] Input channel closed
2023-10-05T16:49:27Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.28.2, RHEL 8

### Steps to reproduce

1. (optional) test the config without job_include -> jobs inside folders are also returned
2. test the config using job_include with a job that is inside a folder -> the job is not returned

### Expected behavior

I expected a "jenkins_job"-metric to be returned for every job

### Actual behavior

No "jenkins_job"-metric is returned for jobs inside folders when you use job_include

### Additional info
Other people have had the same problem, see https://github.com/influxdata/telegraf/issues/10677

_No response_

**Comment by powersj** [comment]
Hi,

> Steps to reproduce
> (optional) test the config without job_include -> jobs inside folders are also returned
> test the config using job_include with a job that is inside a folder -> the job is not returned

These are not steps to reproduce ;) These are observations about the behavior. 

To ensure I am understanding you are saying is the use of the `job_include` config option omits jobs in folders that you think should match?

I have put up https://github.com/influxdata/telegraf/pull/14105 which is similar to a previous PR to collect some additional info about what jobs we are looking at and if we are filtering any.

Please give those artifacts a try once without `job_include` defined and a second time with `job_include` defined and provide the *full* log output for each please.

**Comment by powersj** [comment]
Thank you for doing that! I have pushed another change which swaps the order of the filtering. Please try that with the `job_include` option.

Based on your config your goal is to filter out everything expect for one job, `Deploy_Stage3_Pipeline`, which is under the `StageXXX_Deployment` folder, is that correct?

```toml
job_include = ["StageXXX_Deployment/Deploy_Stage3_Pipeline"]
```

That appears to produce the metric:

```s
jenkins_job,host=host01.domain.com,name=Deploy_Stage3_Pipeline,parents=StageXXX_Deployment,port=443,result=SUCCESS,source=myjenkins.domain.com duration=13066i,number=3746i,result_code=0i 1697473800000000000
```

When you ran with the `job_include` setting above, you got zero results. It appears that we drop the `StageXXX_Deployment` folder before we even try to look at its sub-folders because it does not match the filter provided by the `job_include` setting:

```s
2023-10-16T16:59:38Z I! [inputs.jenkins] dropping job: StageXXX_Deployment
```
