### ISSUE TITLE
Allow specifying separators while using glob match for filtering

### ISSUE THREAD

**Issue by akash-rubrik** [influxdata/telegraf#14056]
### Use Case

I'm using [[inputs.socket_listener]] plugin to collect graphite-style metrics. The problem comes while using filters like namepass/namedrop where wildcard includes the graphite measurement separator `.`. So there is no way to explicitly say, pass all metrics where 2nd measurement is anything but 3rd measurement is 'B'. The only way of saying this is `A.*.B` but this implicitly allows metrics like `A.X.Y.B`. Browsing through the code, seems like this type of match is supported by the underlying glob match library.

Requesting here to add a way to explicitly specify separator inside config keys like namepass, namedrop, tagpass, tagdrop; so that glob match can use those separators to be not included in the wildcard match.

### Expected behavior

given the following input plugin:

```
[[inputs.socket_listener]]
  ## URL to listen on
  service_address = "<>"
  data_format = "graphite"

  templates = [
    "measurement*",
  ]

  namepass = [
    "A.*.B"
  ]
```

`A.C.B` should pass
`A.C.D.B` should *not* pass

### Actual behavior

Both `A.C.B` & `A.C.D.B` pass.

**Comment by srebhan** [comment]
@akash-rubrik this is not possible for `namepass` (and a few others like tagpass) as the [underlying library](https://github.com/gobwas/glob) does not support those expressions.

However, for those cases `metricpass` comes to the rescue. You can use `metricpass = 'name.matches("mock.(?:[^.]*).test")'` which will solve your issue IMO...

**Comment by akash-rubrik** [comment]
@srebhan  Can you describe more on what does underlying library not support? I was trying to point to the separator parameter in the `Compile` function. see below example:

```
package main

import (
	"fmt"
	"github.com/gobwas/glob"
)

type GlobCheck struct {
	Pattern glob.Glob
}

// Match Method to check if the pattern matches the given string
func (gc *GlobCheck) Match(s string) bool {
	return gc.Pattern.Match(s)
}

// PrintMatch Method to print a message if the pattern matches the given string
func (gc *GlobCheck) PrintMatch(s string) {
	if gc.Match(s) {
		fmt.Printf("Match found for %s!\n", s)
	} else {
		fmt.Printf("No match found for %s!\n", s)
	}
}

func main() {
	// create a new instance of GlobCheck with a simple glob
	gc1 := &GlobCheck{Pattern: glob.MustCompile("a.*.b")}
	gc2 := &GlobCheck{Pattern: glob.MustCompile("a.*.b", '.')}

	// check if the glob matches and print a message if successful
	gc1.PrintMatch("a.c.d.b") // true
	gc2.PrintMatch("a.c.d.b") // false
	gc1.PrintMatch("a.c.b") // true
	gc2.PrintMatch("a.c.b") // true
}
```

**Comment by akash-rubrik** [comment]
`metricpass` as you pointed out, looks like a regex matcher to me. I wouldn't want to use a regex match because of its relatively poor performance which really gets amplified at our scale.

**Comment by srebhan** [comment]
I see. You are right that `metricpass` has a poor performance compared to `namepass` so I do understand it is not an option.

How should we configure the separator? Would the following work for you
```toml
  ...
  namepass = ["A.*.B", "X/*/Y"]
  namepass_separators = "./"
```

If so, would you be willing to submit a PR?

**Comment by akash-rubrik** [comment]
Yeah, I can try working on it. Still relatively new to GO-lang so it may take a bit to create PR.

Something like `namepass_separators = "./"` sounds good to me.
I was thinking of configuring this inside the filters like namepass itself so that the separator scope is within the filter itself and it gives the option to have a different separator for each kind of filter if required. Something like:

```
[[inputs.socket_listener]]
  ...
  [inputs.socket_listener.namepass]
    delimiter = ["."]
    patterns = ["A.*.B", "X/*/Y"]
```

How does this compare?

**Comment by srebhan** [comment]
@akash-rubrik while I do like it, it means _every_ current user of `namepass` needs to change the config. This cannot happen as we do promise old configs to run with newer Telegraf versions (at least for a reasonable period). So if `namepass_separators` doesn't sound too bad to you I suggest we go with this....

**Comment by akash-rubrik** [comment]
Sounds reasonable! Thanks for reviewing. I will start working on a PR for this.

**Comment by srebhan** [comment]
@akash-rubrik any update on the PR?

**Comment by akash-rubrik** [comment]
@srebhan Apologies, I haven't been getting time to pick this up. Can I let you know whenever I get some bandwidth?

**Comment by srebhan** [comment]
Sure. Just submit the PR and let me know!
