### ISSUE TITLE
Redis Timeseries' TS.ADD only accepts numeric values.

### ISSUE THREAD

**Issue by aurangzeb099** [influxdata/telegraf#14058]
### Relevant telegraf.conf

```toml
[[outputs.redistimeseries]]
  ## The address of the RedisTimeSeries server.
  address = "127.0.0.1:6379"
```

### Logs from Telegraf

```text
ERROR:
 Error writing to outputs.redistimeseries: adding sample failed: ERR TSDB: invalid value
```

### System info

Telegraf 1.27.3 , Docker version 23.0.1,

### Steps to reproduce

1.telegraf outputs to redistimeseries
2. docker image for redis-stack
docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
3. example metric .
saTable,agent_host=172.16.30.244,host=localhost.net,index=1,saRowId=1 saError=167968771i,saSerialNumber="0",saVer="49.50",saStatus=0i,saMac="00:0l:d3:01:d7:38", 1696489223000000000
...

### Expected behavior

String and integer should store in redistimeseries.

### Actual behavior

 it seems like Redis Timeseries' TS.ADD only accepts numeric values. In your example metric all fields except saMac can be converted or represented by numeric values. Some by accident like saVer or saSerialNumber which are strings but contain "numeric-like" values.

**Comment by srebhan** [comment]
@aurangzeb099 can you please test the binary in PR #14060 available as soon as CI finishes the tests successfully! Please let me know if this fixes your issue!

**Comment by Hipska** [comment]
Normally, if your fields have the wrong datatype, you should use the [processors.converter](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter) plugin.

**Comment by srebhan** [comment]
That's true, however the current behavior of the plugin has to be preserved and that's "autoconvert"...

**Comment by Hipska** [comment]
Does it? Isn’t that why this issue is created?

**Comment by Hipska** [comment]
@srebhan?

**Comment by srebhan** [comment]
No. Currently the "string" of the value is just appended to the `TS.ADD` command, so it works it it is a float or integer or _a string_ of a float or integer! The plugin fails if the value is a _true_ string like `"abc"` but works if the value is a string like `"1.23"`...

**Comment by Hipska** [comment]
Okay, but that is only after implementation of #14060 right?
