### ISSUE TITLE
Dedup plugin save state

### ISSUE THREAD

**Issue by gazpachoking** [influxdata/telegraf#14059]
### Use Case

Keep the dedup plugin deduping across config reloads.

### Expected behavior

Dedup plugin only emits metrics when the metric changes, even after the config gets reloaded.

### Actual behavior

Config reloading causes metrics to be emitted again, even if there were no changes.

**Comment by srebhan** [comment]
Next steps: PR is ready to review and needs a second pair of eyes. Will probably happen end of the week.
