### ISSUE TITLE
Telegraf.conf file operation not permitted after Docker Desktop upgrade

### ISSUE THREAD

**Issue by jaffro2k** [influxdata/telegraf#14102]
### Please direct all support questsions to slack or the forums. Thank you.

Hello - I have an issue after upgrading Docker Desktop where my Telegraf container no long starts (is stuck restarting) with the following error:

2023-10-13 19:02:38 2023-10-13T08:02:38Z I! Loading config: /etc/telegraf/telegraf.conf
2023-10-13 19:02:38 2023-10-13T08:02:38Z E! error loading config file /etc/telegraf/telegraf.conf: open /etc/telegraf/telegraf.conf: operation not permitted

I've checked the permissions on the file which seem OK.  Any ideas or thoughts as to how I troubleshoot further?

**Comment by powersj** [comment]
> Any ideas or thoughts as to how I troubleshoot further?

We would need more details :)

You have not shared how you are mounting the file into docker, the permissions and ownership of the file, or what versions of telegraf or docker image you are even using.

As mentioned by the bot, this is not the place for support questions. Please open a forum thread or ask on slack and provide the additional requested details.

Thanks!
