### ISSUE TITLE
some metrics that generate by jolokia and send via telegraf to questdb drop because hast dot in it

### ISSUE THREAD

**Issue by mehrdad2000** [influxdata/telegraf#14116]
Hi
Is there any way to fix this issue with telegraf?

https://github.com/questdb/questdb/issues/3856

need to send metric with jolokia to questdb but some metrics has dot in their name and questdb drop them.

like these:
-PeakUsage.init
-CollectionUsage.max
-Usage.max

Any idea?
Thanks

**Comment by powersj** [comment]
The slack and forums are a better place for questions like this.

Please also take a look at the various processors we over. I would start with the [rename processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/rename) if you know what specific tag or field names you need to rename.

**Comment by mehrdad2000** [comment]
@powersj 
Thanks work perfectly, totally forgot rename feature of telegraf 😄

i have another issue, i have java app that generate some monitoring metric and use influxdb java client and directly write to influxdb.

now want to write to questdb instead of influxdb. the problem is 1-i don’t want change my code, questdb has library.
2-questdb only accept tcp while influxdb java client send over http protocol.

now question is, is it possible to use telegraf to input http from influxdb then sent to output tcp to questdb?

any idea?
Thanks
