### ISSUE TITLE
redfish enable/disable specific metrics categories

### ISSUE THREAD

**Issue by rismoney** [influxdata/telegraf#14140]
### Use Case

It can be quite expensive on big systems to query thermals, power, voltage, etc.

### Expected behavior

Be able to just enable power collection

### Actual behavior

You get all metrics thermals, power, voltage.

### Additional info

Not sure what the best way to do this, but filtering, if I understand correctly is performed after the input is collected, and doesn't alleviate the https queries going out for all the additional calls.

**Comment by powersj** [comment]
Hi,

Looking at the [Gather function](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/redfish/redfish.go), there really is only two things we could break this down into:

* Thermal - which produces temperatures and fans
* Power - which produces power control, power supplies, and voltages

Generally, we have a config option that is used to specify which parts you would want to collect. Something like:

```toml
## Specify the metrics to collect
# collection = ["thermal", "power"]
```

You could possibly also disable the call to getChassis if the tagSetChassisLocation is not set.

Is this what you are after? Would you be willing to put up a PR?

**Comment by rismoney** [comment]
That is definitely what I am after!

collection = ["power"] would totally work and reduce a huge burden across the 1000s of systems interrogated.  Unfortunately I don't think I can contribute a PR at this time.

**Comment by powersj** [comment]
I put up a quick PR in #14143. In 20-30mins there will be artifacts attached to that PR that you could download. Could you give the new option a try and confirm you get what you expect:

```toml
include_metrics = ["power"]
```

Thanks!

**Comment by rismoney** [comment]
Wow that was fast!  I will attempt to do this now.  Will report back shortly.

**Comment by rismoney** [comment]
I tested exactly this, and it worked 100% as expected!  I am so thankful and kudos to you!
