### ISSUE TITLE
Telegraf SIGSEGV in mikrotik routeros container due to memguard

### ISSUE THREAD

**Issue by sarim** [influxdata/telegraf#14157]
### Relevant telegraf.conf

```toml
Not Relevant
```

### Logs from Telegraf

```text
10-23 00:48:11 container,info,debug import successful, container e9d7ed00-bbae-4aa9-903b-0a1fee102ea5
 10-23 00:49:08 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 10-23 00:49:08 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x676450]
 10-23 00:49:08 container,info,debug 
 10-23 00:49:08 container,info,debug goroutine 1 [running]:
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.Purge.func1(0x58413e0?)
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x30
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.Purge()
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x24
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.Panic(...)
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.NewBuffer(0x20)
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x410
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.NewCoffer()
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:31 +0x64
 10-23 00:49:08 container,info,debug github.com/awnumar/memguard/core.init.0()
 10-23 00:49:08 container,info,debug t/bitnami/blacksmith-sandox/telegraf-1.28.2/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x34
```

### System info

Telegraf 1.28.2. Mikrotik Routeros 7.11.2

### Docker

Mikrotik doesn't use docker or podman. It has its own container implementation based on linux kernel.

### Steps to reproduce

1. Import telegraf container. Official "telegraf" image or, "bitnami/telegraf"
2. Run container

### Expected behavior

Telegraf runs successfully.

### Actual behavior

SIGSEGV

### Additional info

I tried the official "telegraf" image from dockerhub. It panics, but doesn't log stacktrace. Then I tried "bitnami/telegraf" container. It showed the stracktrace. I'm guessing the official container is panicing due to same reason.

I know this bug report is kinda pointless as I already found similiar issues. But for sake of completeness and future googlers with terms "telegraf mikrotik", I thought it should be posted.

Relevant:
#13804
#13998

**Comment by powersj** [comment]
Those relevant PRs also link to other issues explaining that this means in a docker environment that the memguard library was unable to lock memory.

Once those relevant PRs are implemented you will have an option to disable this behavior. Additionally, you could ensure you have lockable memory. In either case I am closing this PR as this is already covered by others.
