### ISSUE TITLE
Telegraf version 1.28.2 backwards incompatibility with response_timeout in inputs.prometheus TOML

### ISSUE THREAD

**Issue by HristianIliev** [influxdata/telegraf#14171]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
    response_timeout = "5s"
```

### Logs from Telegraf

```text
2023-10-24T07:59:43Z E! error loading config file /etc/telegraf/telegraf.conf: error parsing prometheus, line 15: field corresponding to `response_timeout' in prometheus.Prometheus cannot be set through TOML
```

### System info

1.28.2

### Steps to reproduce

1. Create telegraf.conf with inputs.prometheus and response_timeout property
2. Start telegraf with version 1.28.2

### Expected behavior

I expect the response_timeout to prometheus to be set to 5s without failed container start

### Actual behavior

The attached logs are shown and the container fails to start.

**Comment by Hipska** [comment]
The returned error is a bit strange, but the [documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) it has been deprecated since 1.26 and you should use `timeout` instead.

**Comment by HristianIliev** [comment]
I just tried it with timeout and it worked. Thanks!
