### ISSUE TITLE
json_v2 array parsing

### ISSUE THREAD

**Issue by coolibre** [influxdata/telegraf#14184]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://172.17.0.1:8086"]  # Replace with your InfluxDB container name or IP
  database = "your_database_name"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.file]]
    files = ["/etc/telegraf/data.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        [[inputs.file.json_v2.object]]
            path = "book"
            tags = ["title"]
            disable_prepend_keys = true
```

### Logs from Telegraf

```text
2023-10-25T13:46:12Z I! Loading config: /etc/telegraf/telegraf.conf
2023-10-25T13:46:12Z I! Starting Telegraf 1.28.2 brought to you by InfluxData the makers of InfluxDB
2023-10-25T13:46:12Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-10-25T13:46:12Z I! Loaded inputs: file
2023-10-25T13:46:12Z I! Loaded aggregators: 
2023-10-25T13:46:12Z I! Loaded processors: 
2023-10-25T13:46:12Z I! Loaded secretstores: 
2023-10-25T13:46:12Z I! Loaded outputs: influxdb
2023-10-25T13:46:12Z I! Tags enabled: host=738d095e0e61
2023-10-25T13:46:12Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"738d095e0e61", Flush Interval:10s
```

### System info

Docker 24.0.6, Influx1.8

### Steps to reproduce

1. Using the example from plugins/parsers/json_v2/testdata/multiple_arrays_in_object/input.json
...

### Expected behavior

see all chapters in influxdb

file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="A Long-expected Party",name="Bilbo",random=1,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="The Shadow of the Past",name="Bilbo",random=1,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="A Long-expected Party",name="Frodo",random=1,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="The Shadow of the Past",name="Frodo",random=1,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="A Long-expected Party",name="Bilbo",random=2,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="The Shadow of the Past",name="Bilbo",random=2,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="A Long-expected Party",name="Frodo",random=2,species="hobbit"
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",chapters="The Shadow of the Past",name="Frodo",random=2,species="hobbit"

### Actual behavior

 select * from file
name: file
time                author  chapters               host         name  random species title
----                ------  --------               ----         ----  ------ ------- -----
1698241530000000000 Tolkien The Shadow of the Past c5db5105370d Frodo 2      hobbit  The Lord Of The Rings
1698241540000000000 Tolkien The Shadow of the Past c5db5105370d Frodo 2      hobbit  The Lord Of The Rings
1698241550000000000 Tolkien The Shadow of the Past c5db5105370d Frodo 2      hobbit  The Lord Of The Rings
1698241560000000000 Tolkien The Shadow of the Past c5db5105370d Frodo 2      hobbit  The Lord Of The Rings
1698241580000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241590000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241600000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241610000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241620000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241630000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241640000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241650000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241660000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241670000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241680000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241690000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241700000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241710000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241720000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241730000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241740000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241750000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241760000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241770000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241780000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241790000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241800000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241810000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241820000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241830000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241840000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241850000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241860000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241870000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241880000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241890000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241900000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241910000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241920000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241930000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241940000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241950000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241960000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241970000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241980000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698241990000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242000000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242010000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242020000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242030000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242040000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242050000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242060000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242070000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242080000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242090000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242100000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242110000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242120000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242130000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242140000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242150000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242160000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242170000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242180000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242190000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242200000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242210000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242220000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242230000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242240000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242250000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242260000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242270000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242280000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242290000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242300000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242310000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242320000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242330000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings
1698242340000000000 Tolkien The Shadow of the Past 738d095e0e61 Frodo 2      hobbit  The Lord Of The Rings

For all arrays only the last array item is landing in influx.

**Comment by powersj** [comment]
Hi,

That is because this is a really bad example to actualy use ;) All the data you are producing is effectively duplicate data. Please see [duplicate data](https://docs.influxdata.com/influxdb/v2/write-data/best-practices/duplicate-points/) in the influxdb docs, which states:

> For points that have the same measurement name, tag set, and timestamp, InfluxDB creates a union of the old and new field sets.

Your data all has the same measurement name, the same tag (title), and timestamp. Which means the data is all the same and the last one wins.

In terms of parsing the data, it is parsing it correctly and produce the expected output, when using the file output:

```toml
[agent]
  omit_hostname = true
  debug = true

[[outputs.file]]

[[inputs.file]]
    files = ["./plugins/parsers/json_v2/testdata/multiple_arrays_in_object/input.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        [[inputs.file.json_v2.object]]
            path = "book"
            tags = ["title"]
            disable_prepend_keys = true

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "testing"
  timeout = "5s"
  username = "admin"
  password = "1.8mys3cret"
```

```s
❯ ./telegraf --config config.toml --once
2023-10-25T14:16:10Z I! Loading config: config.toml
2023-10-25T14:16:10Z I! Starting Telegraf 1.29.0-7c5b3ea0 brought to you by InfluxData the makers of InfluxDB
2023-10-25T14:16:10Z I! Available plugins: 241 inputs, 9 aggregators, 29 processors, 24 parsers, 60 outputs, 5 secret-stores
2023-10-25T14:16:10Z I! Loaded inputs: file
2023-10-25T14:16:10Z I! Loaded aggregators: 
2023-10-25T14:16:10Z I! Loaded processors: 
2023-10-25T14:16:10Z I! Loaded secretstores: 
2023-10-25T14:16:10Z I! Loaded outputs: file influxdb
2023-10-25T14:16:10Z I! Tags enabled: 
2023-10-25T14:16:10Z D! [agent] Initializing plugins
2023-10-25T14:16:10Z D! [agent] Connecting outputs
2023-10-25T14:16:10Z D! [agent] Attempting connection to [outputs.file]
2023-10-25T14:16:10Z D! [agent] Successfully connected to outputs.file
2023-10-25T14:16:10Z D! [agent] Attempting connection to [outputs.influxdb]
2023-10-25T14:16:10Z D! [agent] Successfully connected to outputs.influxdb
2023-10-25T14:16:10Z D! [agent] Starting service inputs
2023-10-25T14:16:10Z D! [agent] Stopping service inputs
2023-10-25T14:16:10Z D! [agent] Input channel closed
2023-10-25T14:16:10Z I! [agent] Hang on, flushing any cached metrics before shutdown
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=1,name="Bilbo",species="hobbit",chapters="A Long-expected Party" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=1,name="Bilbo",species="hobbit",chapters="The Shadow of the Past" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=1,name="Frodo",species="hobbit",chapters="A Long-expected Party" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=1,name="Frodo",species="hobbit",chapters="The Shadow of the Past" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=2,name="Bilbo",species="hobbit",chapters="A Long-expected Party" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=2,name="Bilbo",species="hobbit",chapters="The Shadow of the Past" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=2,name="Frodo",species="hobbit",chapters="A Long-expected Party" 1698243371000000000
file,title=The\ Lord\ Of\ The\ Rings author="Tolkien",random=2,name="Frodo",species="hobbit",chapters="The Shadow of the Past" 1698243371000000000
2023-10-25T14:16:10Z D! [outputs.file] Wrote batch of 8 metrics in 70.171µs
2023-10-25T14:16:10Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-10-25T14:16:10Z D! [outputs.influxdb] Wrote batch of 8 metrics in 18.855505ms
2023-10-25T14:16:10Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2023-10-25T14:16:10Z I! [agent] Stopping running outputs
2023-10-25T14:16:10Z D! [agent] Stopped Successfully
```

Closing this as this is not an issue with telegraf.

Thanks
