### ISSUE TITLE
Allow to collect data on start even when round_interval is set to true

### ISSUE THREAD

**Issue by talfridmen** [influxdata/telegraf#14186]
### Use Case

I have set up a telegraf instance on multiple servers collecting the same metrics from each one. For ease of use, I want them all to collect data on (approx.) the same time. This way it will be easier to implement some of the graphs in a grafana dashboard. 
On the other hand, I want to always collect data when the telegraf instance starts. This will allow me to have information to present in the graphs until the point where the rounded collection interval occurs.

### Expected behavior

If configured to do so, Telegraf will collect metrics from all plugins and flush the metrics immediately when it starts.

### Actual behavior

You can either set round_interval to false and get it to collect as soon as it starts - but then I cannot synchronize all servers.
Or I can set round_interval to true, but then I do not collect data immediately, so I have nothing to show in the graphs until it reaches the rounded interval.

### Additional info

I am currently using multiple input plugins, including a few exec ones, to collect generic and specialized metrics from my servers.
I am using a prometheus_client output plugin, so if it is a bug there, of course I would love to know that.

I was considering changing my service file to run telegraf with --once before it starts, but as I am using prometheus, I cannot ensure the collection will be synchronized with the export. It might work for plugins that push data, but for prometheus it pulls the data.

**Comment by powersj** [comment]
If we allow collection to start right away, then that is not a round interval ;)

**Comment by talfridmen** [comment]
That is true - but as i stayed, i want to have both.
For example set a config param `collect_on_start` and if it is set to true, it will collect on start and then next time according to round interval.
If the interval is 1h, and I started the process at 10:45, it will collect at 10:45 once, and then at 11:00, 12:00, and so on.
Of course the param `collect_on_start` should be default false.

**Comment by powersj** [comment]
Then I would use the --once option; we are not adding another option for this one-off case.

You mention a concern with using --once with Prometheus and synchronization because it pulls data, not push. My thought was the opposite. Using once, will call plugin's Gather function, which Prometheus has. It is the service plugins, which wait for data to come in via pushes that do not work under the usage of once.

**Comment by talfridmen** [comment]
As stated above, I am using prometheus *output* plugin. Not input. 
So I could collect all the data, but it won't be collected from telegraf to the prometheus instance as it is a pull system and bot a push system.

If you could help me to find a way I might be able to implement this, it would be great.
Thanks

**Comment by powersj** [comment]
I did miss that this was the output.

Which input plugins are you using? And are you really using a 1 hour interval?

I am not keen on adding a new boolean agent option that only works when the round interval is set to true. In most cases users are collecting data much faster than at that interval, and waiting for the first collection is a non-issue. As a result, the impact this config option has versus the cost of maintaining, documenting, and ensuring this option for this one scenario works is not something I want to take on.

**Comment by talfridmen** [comment]
Thanks for your response (and sorry for a late one on my part).
I have found a workaround for this, which includes having a spare telegraf configuration file, using the telegraf.d for all configurations except for the agent section.
This way when the server boots, I run telegraf first with the spare config file that has round_interval set to false, wait for a scrape, and then kill that task and start the main telegraf instance.
Was a bit of a hussle but seems to be working quite well :)
