### ISSUE TITLE
Using web app in bot (react js)

### ISSUE THREAD

**Issue by EhsanBeheshtAein** [influxdata/telegraf#14193]
### Please direct all support questsions to slack or the forums. Thank you.

Hello friends
I tried to connect a React project to Backend written with NodeJS
So that I can open the bot web app and transfer some data from the bot to the web app and vice versa
I did not find an example for this
I tried to implement the code with the documentation, but unfortunately it doesn't work!

Please tell me if you have an example in this field or know a way that will help me. 🙏

**Comment by powersj** [comment]
You have the wrong telegraf... I believe you mean https://github.com/telegraf/telegraf
