### ISSUE TITLE
Update google/gnxi dependency

### ISSUE THREAD

**Issue by pkthapa** [influxdata/telegraf#14202]
### Please direct all support questsions to slack or the forums. Thank you.

Docker is a software container platform which is used to run applications side by side within isolated containers. There exists a vulnerability due to the unprotected TCP socket where an attacker can create a Docker container with read and write permissions on the host server enabling them to edit files owned by root.

Impacted version: https://github.com/moby/moby/tree/v1.13.1

Reported by Blackduck scan.
Issue reference: https://github.com/google/gnxi/issues/356

**Comment by powersj** [comment]
Hi,

I would really appreciate next time if you would use the security reporting method defined in the repo [security policy](https://github.com/influxdata/telegraf/security/policy). Additionally, it would be very helpful is you provided a link to the actual CVE and not only the output from a scanner.

> There exists a vulnerability due to the unprotected TCP socket where an attacker can create a Docker container with read and write permissions on the host server enabling them to edit files owned by root.

Telegraf is not used to run, create, or delete containers.

Telegraf references github.com/docker/docker still, which is on version v24.0.6+incompatible, much later than version v1.13.1.

You mention the dependency google/gnxi, which did appear to be using this older module until yesterday. However, that dependency is used in our gnmi input, which is not involved in docker containers either.

I will merge your PR as an update to google/gnxi dependency, once you update your PR.
