### ISSUE TITLE
Elastic stack related plugins should take into account proxy environment variables

### ISSUE THREAD

**Issue by oserde** [influxdata/telegraf#14206]
### Use Case

We use telegraf agent within a corporate network, but have some elasticsearch servers in the cloud. In order to connect to internet things, we need to go through an HTTP/HTTPS proxy. Right know, elasticsearch, elasticsearch_query, kibana, and logstash plugins are not taking into account standard proxy variables such as HTTP_PROXY, HTTPS_PROXY and NO_PROXY, and there is no specific config attribute to go through a proxy neither.

### Expected behavior

By setting http_proxy or https_proxy environment variables, telegraf plugins should send http or https request through a proxy

### Actual behavior

These plugins do not take into account http proxy variables.

**Comment by powersj** [comment]
next steps: review PR, however we do need to be backwards compatible as Sven's review points out.
