### ISSUE TITLE
inputs.exec failing

### ISSUE THREAD

**Issue by skinfrakkiirid** [influxdata/telegraf#14204]
### Please direct all support questsions to slack or the forums. Thank you.

Trying to run the following in inputs.exec:

# [[inputs.exec]]
[[inputs.exec]]
   interval = "60s"
   commands = [
       "/usr/local/bin/python3.7 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt influxdb-lp -vv",
   ]
   timeout = "50s"
   data_format = "influx"

Get the following error in the log:

[inputs.exec] Error in plugin: exec: exit status 1 for command '/usr/local/bin/python3.7 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt influxdb-lp -vv': Traceback (most recent call last):...

**Comment by powersj** [comment]
This is not an issue with telegraf, this is reporting that it failed to run the command you specified. Specifically, it looks like a traceback from the python app occured.
