### ISSUE TITLE
Support qbittorrent resource parameter collection

### ISSUE THREAD

**Issue by RWDai** [influxdata/telegraf#14205]
### Use Case

qbittorrent is an open source download library
add a plugin to support

### Expected behavior

able to monitor the basic status of qb

### Actual behavior

none

```[tasklist]
### Tasks
```

**Comment by RWDai** [comment]
If no one is interested in the implementation of this function, and this plugin can be merged into the repository, you can assign this task to me.

**Comment by powersj** [comment]
@RWDai,

Before you start working on the plugin some questions:

1. Why are collecting metrics from qbittorrent interesting?
2. What metrics to you intend to capture and create?
3. How will you collect the metrics? Is there an API available to collect these metrics? Or some endpoint or file to read?

If we are going to add a new plugin we generally want this to be something that would be rather popular and have demand behind. Otherwise, I would suggest creating a plugin as an external plugin that others could still use.

Thanks

**Comment by RWDai** [comment]
Thanks reply!
1. First of all , [qbittorrent](https://github.com/qbittorrent/qBittorrent) is a  popular open-source bittorrent client  ,similar projects include [transmission](https://github.com/transmission/transmission) ,and so on. qbittorrent can be used to download BT and PT , a lot of people run them on their own servers (or NAS, etc.) for a long time , but there is a lack of monitoring of their status.
2. Such as `uptime`,`download rate`,`upload rate`,`task status`,`torrent nub` and so forth.
3. Official[web api](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)) .

Just looking at the number of stars and [one of docker image](https://hub.docker.com/r/linuxserver/qbittorrent) downloads in these two warehouses, you can tell that there is definitely a lot of demand. 

Ref repository:[prometheus expoerter](https://github.com/caseyscarborough/qbittorrent-exporter)、[third-party client implementation in go](https://github.com/ludviglundgren/qbittorrent-cli)、[third-party client impl in popular]([rmartin16/qbittorrent-api](https://github.com/rmartin16/qbittorrent-api))

**Comment by powersj** [comment]
@RWDai,

Happy to see a PR to add a new plugin. Please ensure you add tests for the various endpoints you plan to hit.

Thanks

**Comment by srebhan** [comment]
@RWDai just one more question from my side. Which endpoints of the WebAPI are you planning to query? I'm asking as for example the [transfer info](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#transfer-info) could be queried via the `inputs.http` plugin and parsed with one of the JSON parsers...

**Comment by RWDai** [comment]
@srebhan its good question.You must want knonw why add a new plugin is better then use `inputs.http` plugin.
Because the API provided can only transmit the changed part of the data, this makes information collection faster. The instance I am currently using takes several seconds to completely request this interface, but it only takes tens to hundreds of milliseconds to transmit only the data changes.[api-get-main-data](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-main-data)
If you use the `inputs.http` plugin, you can only let the API return complete information each time. When the amount of data is large, the performance will be poor, but there is really not much difference other than that.

**Comment by srebhan** [comment]
@RWDai thanks for the explanation! I'm fine with a separate plugin.

**Comment by powersj** [comment]
@RWDai,

Were you planning on resubmitting your plugin?

**Comment by RWDai** [comment]
I probably won't submit again for a long time.The maintenance of qb sdk in go language is not active. If I submit this plug-in, it may mean that I need to maintain a qb sdk.
