### ISSUE TITLE
disk probe stuck - Can't ignore bad fs_type

### ISSUE THREAD

**Issue by rubycut** [influxdata/telegraf#1422]
### Relevant telegraf.conf:

```
[disk]
# ignore binds
ignore_fs = ["none"]
```
### System info:

Telegraf 0.13
### Steps to reproduce:
1. Have a mount --bind which is stuck, you can't type even `ls` on this bind (if it points to non existing nfs for example) and therefore telegraf should not touch it.
2. run `telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -test |grep disk`
### Expected behavior:

Telegraf should skip mount which is stuck
### Actual behavior:

disk plugin is stuck, and telegraf is also stuck, doesn't exist.
### Additional info:

It seems that  we first gather disk usage, and after that we decide to run continue based on ignore_fs. 

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/ps.go#L86

Can I prepare pull request?

**Comment by sjwang90** [comment]
Close due to lack of activity. If this is still an issue with the latest Telegraf feel free to reopen.
