### ISSUE TITLE
Allow aliases for ec2 metadata tags to avoid naming conflicts on backend.

### ISSUE THREAD

**Issue by justinvice** [influxdata/telegraf#14226]
### Use Case

The naming conventions used for the currently supported ec2 metadata [tags](https://github.com/influxdata/telegraf/tree/master/plugins/processors/aws/ec2), have the potential for colliding with backend naming of tags. For example, the AWS account id tag is sent as 'accountId' and in the case of New Relic this tag already has special meaning. Providing the ability to assign an alias (i.e. accountId -> awsAccountId) would prevent potential naming collisions.

### Expected behavior

1. User, optionally, defines alias mappings (i.e., accountId -> awsAccountId)
2. The alias is used for the tag (dimension) name when viewed in backend (New Relic in this case, though the same applies for Prometheus)

### Actual behavior

Aliases are not currently supported, so dimension names are just as currently defined in the [readme](https://github.com/influxdata/telegraf/tree/master/plugins/processors/aws/ec2#readme).

**Comment by powersj** [comment]
Hi,

I want to be certain I am clear on when the conflict is occurring. If this is between the processor and the new relic output, you can use the [rename processor](https://github.com/influxdata/telegraf/tree/c6f1c66bf83daa2b2e324a734cfa813c492aa53c/plugins/processors/rename) post aws-ec2 processor to rename the value as you want.

Would that work?

Thanks

**Comment by jvice** [comment]
@powersj  We are running 2 output processors in parallel, Prometheus and New Relic. Given that the tag in question, accountId, was showing correctly in Prometheus, my suspicion was that this was at the output processor stage. This was validated by your suggestion above to use the rename processor. It works perfectly, so thank you. 

My intention here was to create an issue, per the contributors guide, and to follow up my first (PR) contribution. I guess I can defer that to a later time :-).

**Comment by powersj** [comment]
> It works perfectly, so thank you.

Glad to hear!

> My intention here was to create an issue, per the contributors guide, and to follow up my first (PR) contribution. I guess I can defer that to a later time :-).

Oops, I'm sorry! Always happy to see contributions.
