### ISSUE TITLE
How does telegraf perform this conversion?

### ISSUE THREAD

**Issue by nieyuan1980** [influxdata/telegraf#14231]
How does telegraf perform this conversion?
Hi everyone, I am using telegraf to receive the collected data from mqtt.

The data received is in json format:
```
{
  "version": 2.1,
  "information": {
    "adsid":"COTXJJSZC0101",
    "meterid": "METKTZYDAK101",
    "Address 1",
    "com": "com1",
    "data": [
      {
        "Tagname": "2759-A-1O-METKTZYDAK101-EPAD0CC",
        "quality": 0,
        "value": 67378.201,
        "Time": "2022-11-01 17:17:45"
      },
      {
        "Tagname": "2759-A-1O-METKTZYDAK101-IA000CC",
        "quality": 0,
        "value": 5.200,
        "Time": "2022-11-01 17:17:45"
      }
    ]
  }
}
```
I want to convert it to ```line protocol```compliant format:
**metktzydak101,epad0cc=67378.201,ia000cc=5.200 1667323065**

I don't quite understand how to merge multiple lines into one in this process
I'm a beginner and would love your help.Thank You!

**Comment by srebhan** [comment]
@nieyuan1980 as the bot suggests, the best place to ask those is the Slack channel (or the forum). Regarding your question, you need to parse the JSON into two metrics with the same measurement name and tags-set but different field names and then use the [merge aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge) to collect them to one metric.
