### ISSUE TITLE
telegraf collects data via prometheus scrape

### ISSUE THREAD

**Issue by bbker** [influxdata/telegraf#14230]
### Use Case

We collect Prometheus indicators through Telegraf, and we want to have a configuration item so that when Prometheus scrape, Telegraf will perform the collection and expose the metrics.

### Expected behavior

when prometheus scrape, Telegraf will perform the collection and expose the metrics.

### Actual behavior

```toml
[[inputs.sql]]
 interval = "30s"
 ......
[[outputs.prometheus_client]]
 expiration_interval = "30s"
```

At present, there may be an issue with expired metrics. Normally, only the second line of metrics below should be displayed. Due to the configuration of "expiration_interval", historical data is preserved. I tried to keep the scraper time of prometheus consistent with "expiration_interval", but there may still be issues with historical metrics or empty metrics

```
mysql_eventSql{currentTime="2023-11-01 10:23:30",dbName="aaimp_test",group="192.16.4.32",host="S-OMMP-03",hostIp="",processId="103504",state="Sending data",time="0",userName="root"} 1 1698805410000
mysql_eventSql{currentTime="2023-11-01 10:24:00",dbName="aaimp_test",group="192.16.4.32",host="S-OMMP-03",hostIp="",processId="103504",state="executing",time="0",,userName="root"} 1 1698805440000
```

### Additional info

Sorry my English is not good, I use translation software to translate, hope to get help, thank you!

**Comment by powersj** [comment]
Hi,

Can you please download the artifacts in https://github.com/influxdata/telegraf/pull/14232 and confirm that the PR resolves the issue?

I confirmed this occurs with the v1 metric version, but not v2. It appears the v1 can have some overlap between when data expires and the next interval. This leads to series showing up that should have expired out.

The v2 metric version ensures we expire during each collect and add phase as well to ensure that the data is refreshed, and expiry happens to prevent duplicate series.

**Comment by powersj** [comment]
@bbker - I'm still interested in getting your feedback on the above PR. Please do let me know if you give it a try.

**Comment by bbker** [comment]
> @bbker - I'm still interested in getting your feedback on the above PR. Please do let me know if you give it a try.
Sorry for the delay in some work, thank you for your support, I will try it in a few days
