### ISSUE TITLE
MQTT Consumer on Telegraf 1.28.3 creates "could not mark message delivered" errors on Linux but not on Windows

### ISSUE THREAD

**Issue by gerhard76** [influxdata/telegraf#14242]
Hi Folks,

I am running telegraf on a Raspi 4, which collects metrics from MQTT, does some processing and stores it to Influx, so nothing special. 
A couple of days ago I updated my Telegraf version from 1.24.4 to 1.28.3 and since then I get "could not mark message delivered" errors from the mqtt_consumer plugin (~20 per hour). 

I use an almost copy-paste telegraf-config on a Windows PC (same telegraf version) and I don't get any of these errors. I also compared the output in Influx on Raspi vs. Influx on Windows around the time of some of the errors, but they are identical. So at least from the data point of view everything is fine. 

I had a look at the bit of code that generates this error in the "onDelivered" function of the [mqtt_consumer](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mqtt_consumer/mqtt_consumer.go) but I know too little about Go to make a guess what actually happens . I read that recently a lot changes were related to MQTT, so I guess this is related. However, I just wonder if this might have side-effects, when the last line of the "onDelivered" function in the mqtt_consumer:
delete(m.messages, track.ID())
is not executed and I am kind of accumulating a lot of over time.

Thanks for any input/advice/etc.

Cheers,
Gerhard

Telegraf receives (according to the internal plugin) approx 500 messages/min, so no heavy load

**Comment by powersj** [comment]
Hi,

We have been working with a user on this issue already and discovered a condition where Telegraf will send and attempt to acknowledge the metric before it can even record the metric. This results in trying to acknowledge a metric that telegraf does not actually know about.

I have put up #14243, that we have had another user confirm appears to be working.

Thanks

**Comment by gerhard76** [comment]
Hi Joshua,
thank you for the quick response and fixing this issue. I am looking forward to the next Telegraf release. 
Cheers,
Gerhard
