### ISSUE TITLE
how to use multiple config

### ISSUE THREAD

**Issue by Ephemeraler** [influxdata/telegraf#14248]
### Please direct all support questsions to slack or the forums. Thank you.

I have some telegraf config which has different inputs and outpus.prometheus_client that have different port, but when I execute curl  http://localhost:9273/metrics curl http://localhost:9274/metrics, I can get all metrics from each api. Shouldn't it just expose the inputs enabled in one's own configuration file？

**Comment by powersj** [comment]
No, the config's are not specific to a single file. Every config file is read in and combined. If you need to filter what input plugin or metric goes to what output, you need to look at [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering).

Closing.
