### ISSUE TITLE
Allow getting multiple values for the same series in prometheus_output plugin when using export_timestamps = true

### ISSUE THREAD

**Issue by talfridmen** [influxdata/telegraf#14246]
### Use Case

I have a telegraf instance that is exporting its metrics using the prometheus_client output plugin, with export_timestamps = true.
My prometheus server is set to scrape the prometheus_client every 1m, but I some of the metrics telegraf collects are set to run in a shorter interval (i.e. 10s).
This means that even though telegraf collects that data every 10s, I only get the last one collected before prometheus server scrapes the information.
What I would like is to be able to configure something like retention that will keep older metrics of the same series for a specific duration. of course this is only relevant when using the export_timestamps flag too.

### Expected behavior

When I scrape once ever minute, but collect data from the server once every 10s, I will receive all 6 datapoints in the prometheus output.
i.e. something like:
```
# HELP test_metric Telegraf collected metric
# TYPE test_metric gauge
test_metric{test_tag="test1"} 1 1699083882000
test_metric{test_tag="test1"} 2 1699083883000
test_metric{test_tag="test1"} 3 1699083884000
test_metric{test_tag="test1"} 4 1699083885000
test_metric{test_tag="test1"} 5 1699083886000
test_metric{test_tag="test1"} 6 1699083887000
test_metric{test_tag="test2"} 11 1699083882000
test_metric{test_tag="test2"} 12 1699083883000
test_metric{test_tag="test2"} 13 1699083884000
test_metric{test_tag="test2"} 14 1699083885000
test_metric{test_tag="test2"} 15 1699083886000
test_metric{test_tag="test2"} 16 1699083887000
...
```

### Actual behavior

prometheus only gets the last metric collected by telegraf every 1m, no matter the input interval.

**Comment by powersj** [comment]
In short this is not possible and not something we could change. In the example above, you have two series, so I would expect to see two lines:

```
test_metric{test_tag="test1"} 6 1699083887000
test_metric{test_tag="test2"} 16 1699083887000
```

If you want data more often you need to scrape your endpoint more often or use a different output/serializer.
