### ISSUE TITLE
Add Support to `outputs.stackdriver` to Transmit Histograms

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#14258]
### Use Case

You receive histograms from devices using `inputs.prometheus` or other method that you can pass to `outputs.stackdriver` which then can pass to the Google API to be visualized.

Example snippet from `inputs.prometheus`:

```
# TYPE http_client_response_size histogram
# HELP http_client_response_size The size of HTTP response messages
http_client_response_size_count{http_flavor="1.1",http_method="GET",http_status_code="404",net_peer_name="server"} 1.0 1698951401392
http_client_response_size_sum{http_flavor="1.1",http_method="GET",http_status_code="404",net_peer_name="server"} 35.0 1698951401392
http_client_response_size_bucket{http_flavor="1.1",http_method="GET",http_status_code="404",net_peer_name="server",le="0.0"} 0.0 1698951401392
http_client_response_size_bucket{http_flavor="1.1",http_method="GET",http_status_code="404",net_peer_name="server",le="5.0"} 0.0 1698951401392
```

### Expected behavior

This doesn't appear to exist at this time.

### Actual behavior

This doesn't appear to exist at this time.

**Comment by powersj** [comment]
Hey @crflanigan,

The above example seems to translate to the following internally, with type histogram:

> http_client_response_size,http_flavor=1.1,http_method=GET,http_status_code=404,net_peer_name=server,url=http://localhost:8000/metrics count=1,sum=35,0=0,5=0 1698951401000000000

It looks like we can use the `monitoringpb.TypedValue_DistributionValue` type when we find a histogram and build the value. I need to work through this some more, but hope to have a PR soon. My biggest concern will be testing. So if you have some real examples of histograms that you are see in your data I'd love to see them.

Thanks

**Comment by crflanigan** [comment]
Hey buddy!

Yes, I think I have a use case that I can use to test this!

When you have the PR ready I can give it a shot.

Thanks!

**Comment by powersj** [comment]
@crflanigan, ok I have put up #14275. Do you want to give it a try once artifacts are added to the PR?

If you run into issues, could you provide the output of `[[outputs.file]]` as well, so I can see what the metric looks like? I haven't played with the end result in Stackdriver either, so let me know if that looks correct as well.

Thanks!

**Comment by crflanigan** [comment]
@powersj 

Sure thing!
