### ISSUE TITLE
`ipset` plugin does not handle unexpected fields correctly

### ISSUE THREAD

**Issue by attie** [influxdata/telegraf#14259]
The `ipset` plugin expects the lines to appear in the following format:

```
add ${set} ${rule} packets ${packets_total} bytes ${bytes_total}
```

However, in my setup I also have timeouts, so that the sets are cleared periodically, which presents the following format:

```
add ${set} ${rule} timeout ${timeout_seconds} packets ${packets_total} bytes ${bytes_total}
```

Currently, the plugin naively expects that the packet and byte count fields will be in positions `4` and `6` respectively, which is not true. Naturally, this leads to incorrect data, with the timeout value being presented as a packet count, and the packet count being presented as a byte count.

https://github.com/influxdata/telegraf/blob/a72550a02094baf939b1881a225af9763ff2cc3d/plugins/inputs/ipset/ipset.go#L76-L83

Create a set with timeouts as follows:

```bash
ipset create counter-test hash:ip family inet hashsize 1024 timeout 1800 counters
```

**Comment by powersj** [comment]
Hi,

This is not great to see when we are parsing output from a CLI :( Thanks for providing an example, I've been able to reproduce and have put up #14262. If you could grab the artifacts from the above in 30 or so minutes and verify you are seeing the correct data I would greatly appreciate it.

My notes:

```s
root@j1:~# ipset version
ipset v7.15, protocol version: 7
root@j1:~# ipset create counter-test hash:ip family inet hashsize 1024 timeout 1800 counters
root@j1:~# ipset create counter-test2 hash:ip family inet hashsize 1024 counters
root@j1:~# ipset add counter-test 192.168.1.1 packets 8 bytes 672
root@j1:~# ipset add counter-test2 192.168.1.1 packets 8 bytes 672
```

The plugin uses the `ipset save` command, which produced:

```s
root@j1:~# ipset save
create counter-test hash:ip family inet hashsize 1024 maxelem 65536 timeout 1800 counters
add counter-test 192.168.1.1 timeout 1792 packets 8 bytes 672
create counter-test2 hash:ip family inet hashsize 1024 maxelem 65536 counters
add counter-test2 192.168.1.1 packets 8 bytes 672
```

And produced:

```s
ipset,rule=192.168.1.1,set=counter-test packets_total=1754i,bytes_total=8i 1699457860000000000
ipset,rule=192.168.1.1,set=counter-test2 packets_total=8i,bytes_total=672i 1699457860000000000
```

**Comment by attie** [comment]
Thanks for the quick response! I'll comment on the PR...
