### ISSUE TITLE
Using secret-store in postgresql_extensible plugin

### ISSUE THREAD

**Issue by aj-kyriba** [influxdata/telegraf#14265]
### Please direct all support questsions to slack or the forums. Thank you.

Usecase: Use secret-store to set password for postgres address

Details: 
I am trying to configure a postgresql_extensible plugin, which will allow me to connect to a PG database. 
In my **_address_** , i want to securly pass the password and hence i tried to use secret-store as follows:

````
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-d-config
  namespace: monitoring
data:
  local_secrets.json: |-
    {
      "PG_PASSWORD": "actual_password"
    }
  postgres-input.conf: |-
    [[secretstores.os]]
      id = "local_secrets"
      
    [[inputs.postgresql_extensible]]
      address = "host=postgres-endpoint port=5432 user=telegraf password=@{local_secrets:PG_PASSWORD} dbname=postgres sslmode=require"
```
 `

But i receive the error 
`E! retrieving resolver failed: linking secrets failed: resolving "@{local_secrets:PG_PASSWORD}" failed: The specified item could not be found in the keyring`

Can you please let me know how to use this feature correctly?
Thanks in advance

**Comment by powersj** [comment]
Please take a look at https://www.influxdata.com/blog/storing-secrets-telegraf/ which gives an overview of the various secret store options.

> The specified item could not be found in the keyring

This is an error saying Telegraf was unable to find the secret in your specified store. For example, if you are using linux, then it means the kernel keyring for that user did not have the password. With the OS secret store you need to ensure that the user who runs Telegraf can see the password.

In your config, you are passing the password as an enviornment variable, you may not even need the secret store and could instead just pass `$PG_PASSWORD` in your config.

I'm going to close this as the github issues are for real issues not support, but if you have further questions feel free to ask us and our community in the above slack and forums.

Thanks!
