### ISSUE TITLE
Support test output

### ISSUE THREAD

**Issue by vmp6513** [influxdata/telegraf#14271]
### Use Case

Verify the **validity of the output** through the test mode.

### Expected behavior

Through the test mode, telegraf can verify the validity of the output connection, the validity of the certificate, and the validity of the authorization. If the verification fails, telegraf can output more detailed error information.

### Actual behavior

As of the latest version, test mode can only be used on the input side.

### Additional info

Now I have added a number of outputs to the configuration file, such as kafka, syslog, zabbix, etc. Each time I started telegraf I needed to use additional scripts to verify that these output connections were working and that authorization was valid. These scripts were generic and easy to maintain.

**Comment by powersj** [comment]
Hi,

> Through the test mode, telegraf can verify the validity of the output connection, the validity of the certificate, and the validity of the authorization. If the verification fails, telegraf can output more detailed error information.

Have you seen and used `--once`?
