### ISSUE TITLE
Add custom template in Postgres output plugin

### ISSUE THREAD

**Issue by parvez-cet21** [influxdata/telegraf#14270]
### Please direct all support questsions to slack or the forums. Thank you.

I have below telegraf.conf Working fine but it creates only one table for both queries of input table I want two different tables each named of query filename like test.sql data should be populated in Postgres table test same goes for datasets.sql data should be in datasets table in psql.
How can I achieve above scenerio bu altering the below configuration
`[global_tags]

[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000

  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  # logtarget = "file"
  # logfile = ""
  # logfile_rotation_interval = "0h"
  # logfile_rotation_max_size = "0MB"
  # logfile_rotation_max_archives = 5
  # hostname = "192.168.1.100"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

# Publishes metrics to a postgresql database
[[outputs.postgresql]]
  connection = "postgres://XXXX:XXXX@localhost/DBNAME?sslmode=disable"
  # schema = "public"
  # create_templates = [
  #   '''CREATE TABLE IF NOT EXISTS datasets(["time","name","quantity"])'''
  # ]

  ## Schema to create the tables into
  schema = "public"
  ## Templated statements to execute when creating a new table.
  create_templates = [
      '''CREATE TABLE {{ .table }} ({{ .columns }})''',
  ]
  add_column_templates = [
      '''ALTER TABLE {{ .table }} ADD COLUMN IF NOT EXISTS {{ .columns|join ", ADD COLUMN IF NOT EXISTS " }}''',
  ]
  tag_table_add_column_templates = [
      '''ALTER TABLE {{.table}} ADD COLUMN IF NOT EXISTS {{.columns|join ", ADD COLUMN IF NOT EXISTS "}}''',
  ]

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################
[[inputs.sql]]
  driver = "sqlserver"
  dsn = "sqlserver://XXX:XXXX@XXX.XXX.X.XX:PORT?database=master&connection+timeout=30"

  timeout = "5s"

  [[inputs.sql.query]]
    query_script = "test.sql"

  #   tag_columns_exclude = ['timestamp','host','time']
  #   field_columns_exclude = ['timestamp','host','time']

  [[inputs.sql.query]]
    query_script = "datasets.sql"
    # tag_columns_include = []
    # tag_columns_exclude = ['timestamp','host']

    # field_columns_include = []
    # field_columns_exclude = ['timestamp','host']

`

**Comment by powersj** [comment]
As mentioned in your preivous support request please use the above links to slack and forums.

Also look at the measurement config option for the sql plugin.
