### ISSUE TITLE
Cassandra input plugin - wrong measurements when using wildcards and Cassandra 2.x

### ISSUE THREAD

**Issue by zdravec** [influxdata/telegraf#1427]
## Bug report
I'm usinng cassandra 2.x and telegraf to collect metrics and send them to riemann. I want to read `_WriteTotalLatency_` for all tables and I'm using wildcards, see telegraf.conf. Jolokia returns a list of all metrics, but to riemann is send only one, combining the whole jolokia response.

### Relevant telegraf.conf:
```
[[inputs.cassandra]]
  context = "/jolokia/read"
  servers = [":8778"]
  metrics  = [
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=WriteTotalLatency"
	]
```

### System info:
Telegraf - version 1.0.0-beta1

### Steps to reproduce:
telegraf -test -config telegraf.conf

### Expected behavior:
```
Plugin: cassandra, Collection 1
host  url http://:8778/jolokia/read/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=WriteTotalLatency
\> cassandraColumnFamily,host=cassandra-0,keyspace=system,mname=WriteTotalLatency,scope=size_estimates WriteTotalLatency_Count=381517 1467200344000000000
\> cassandraColumnFamily,host=cassandra-0,keyspace=system,mname=WriteTotalLatency,scope=schema_triggers WriteTotalLatency_Count=329 1467200344000000000
\> cassandraColumnFamily,host=cassandra-0,keyspace=system,mname=WriteTotalLatency,scope=schema_aggregates WriteTotalLatency_Count=474 1467200344000000000
```
### Actual behavior:
```
Plugin: cassandra, Collection 1
host  url http://:8778/jolokia/read/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=WriteTotalLatency
\> cassandraColumnFamily,host=cassandra-0,keyspace=*,mname=WriteTotalLatency,scope=* WriteTotalLatency_org.apache.cassandra.metrics:keyspace\=system\,name\=WriteTotalLatency\,scope\=IndexInfo\,type\=ColumnFamily="map[Count:0]",WriteTotalLatency_org.apache.cassandra.metrics:keyspace\=system\,name\=WriteTotalLatency\,scope\=available_ranges\,type\=ColumnFamily="map[Count:0]",WriteTotalLatency_org.apache.cassandra.metrics:keyspace\=system\,name\=WriteTotalLatency\,scope\=batchlog\,type\=ColumnFamily="map[Count:0]"" 1467202491424240892
```

### Additional info:
The current solution only works for Cassandra 3.x, but not for Cassandra 2.0, because of the metric type. It is "ColumnFamily" in Cassandra 2.x and "Table" in Cassandra 3.x
Copy from plugins/inputs/cassandra/cassandra.go, it only checks for metric type "Table":
`if tokens["type"] == "Table" && (tokens["keyspace"] == "*" ||
		tokens["scope"] == "*")`

**Comment by sparrc** [comment]
thanks for the report, if you could submit a PR to fix it would be greatly appreciated.
