### ISSUE TITLE
How does Telegraf collect remote NGINX log information

### ISSUE THREAD

**Issue by tengdagg** [influxdata/telegraf#14281]
### Please direct all support questsions to slack or the forums. Thank you.

Telegraf and NGINX are not on the same host, how can I use Telegraf to get metrics and log information for remote nginx and pass it to influxdb

**Comment by powersj** [comment]
Hi,

Please use the slack or foums linked above to ask questions like this.

All of the nginx input plugins take a URL so that telegraf could be used remotely.

Thanks
