### ISSUE TITLE
Authentication in Aerospike Input plugin

### ISSUE THREAD

**Issue by usdin** [influxdata/telegraf#1429]
Proposal:
Aerospike Input plugin should be able to collect data from authenticated Aerospike.

Current behavior:
Right now aerpsike plugin can't collect data from security enabled Aerospike.

Desired behavior:
Aerospike Input plugin should be able to collect data from authenticated Aerospike. Credentials can be put in config file.

Use case: [Why is this important (helps with prioritizing requests)]
Many other input plugins supports authentication but Aerospike input plugin. We are using authentication on Aerospike. It will be good if Telegraf provide this feature.

**Comment by danielnelson** [comment]
@usdin, I know it has been quite awhile, but if you are still interested in this feature I have a pull request that adds TLS with username/password support.  Is this something you could help test?
