### ISSUE TITLE
How do I modify my telegraf configuration

### ISSUE THREAD

**Issue by tengdagg** [influxdata/telegraf#14292]
### Please direct all support questsions to slack or the forums. Thank you.

I want to use my NGINX log_format to collect logs using grok custom mode for analysis, this is my NGINX log format

log_format  main  '$remote_addr $remote_user [$time_local] "$http_host" "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '$upstream_addr $request_time $upstream_response_time';
                      
  telegraf.conf
  [[inputs.tail]]
  	 name_override = "nginxlog"
  	 files = ["/opt/nginx/logs/access.log"]
   	 from_beginning = true
  	 pipe = false
  	 data_format = "grok"
  	 grok_patterns = ["%{COMBINED_LOG_FORMAT}"]
  	 
 How do I modify my telegraf configuration

**Comment by powersj** [comment]
Please use the above items to ask questions.

Thanks
