### ISSUE TITLE
Update input dpdk plugin. Add support for more metrics and tags

### ISSUE THREAD

**Issue by PanKaker** [influxdata/telegraf#14307]
### Use Case

Telegraf input dpdk plugin should
1) support new 'ethdev' metric:  `ethdev/info`
2) expose fields: `pid `and `version `of DPDK
3) have support to read from multiple in-memory sockets 
4) expose numerical state of `/ethdev/link_status`. (0 for "DOWN", and 1 for "UP")
5) Support  new configuration option `unreachable_socket_behavior`

### Expected behavior

Telegraf should support all above

### Actual behavior

Current version doesn't support it

### Additional info

The features above will be covered in upcoming PR

**Comment by powersj** [comment]
next steps: review PR, thank you!
