### ISSUE TITLE
Max connections in telegraf output for postgres sql

### ISSUE THREAD

**Issue by rakopoul** [influxdata/telegraf#14306]
### Use Case

We use postgres plugin to monitor connections of postgresql (through influxdb we monitor the values in Grafane dashboards).
We would like to create an alert when total connections reach a percentage of max_connections.

We have metrics for each db, so we can find the sum easily in grafana query, though to have the max_connections number to find the percentage we would need to add custom exec in telegraf conf (along with a custom script) and new line of data in influx.

This would be very helpful if would be added in plugin output.

```
bash-5.0# psql -U postgres -c "SHOW max_connections"
 max_connections
-----------------
 100
(1 row)
```

This is the metric that would be very helpful if it can be added.

### Expected behavior

max_connections param sent through telegraf plugin

### Actual behavior

max_connections param is not sent through telegraf plugin

**Comment by powersj** [comment]
Hi,

The existing `postgresql` plugin will gather metrics via `pg_stat_bgwriter` and `pg_stat_database` views/tables. I do not see us changing the plugin to start gathering one-off metrics. I would suggest using the the `sql` plugin to run your custom query and generate a metric based on that.
