### ISSUE TITLE
Windows ping plugin type error

### ISSUE THREAD

**Issue by dmitrysdm** [influxdata/telegraf#1433]
This example does not work: Error parsing .\exec_telegraf.conf, Undefined but requested input: ping

[[inputs.ping]]
# [ping]

```
    # urls to ping
    urls = ["localhost"] # required
    # number of pings to send (ping -c <COUNT>)
    count = 1 # required
    # # interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
    ping_interval = 0.0
    # # ping timeout, in s. 0 == no timeout (ping -t <TIMEOUT>)
    timeout = 0.0
    # # interface to send ping from (ping -I <INTERFACE>)
    # interface = ""
```

I am also try config from https://github.com/influxdata/telegraf/issues/222 , but unsuccessful

**Comment by MendelGusmao** [comment]
This plugin doesn't work on Windows, actually... There is no such implementation so far.

**Comment by DracoAter** [comment]
As this is not closed yet, submitting a bug about Windows ping here.

Windows ping output conflicts with default ping output:

OS: Ubuntu 16.04
Telegraf: Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
Output:
> ping,url=8.8.8.8,host=bunker packets_received=3i,percent_packet_loss=0,average_response_ms=15.474,standard_deviation_ms=2.246,packets_transmitted=3i 1487076994000000000

OS: Windows 7
Telegraf: Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
Output:
>  ping,url=192.168.29.10,host=overlord packets_transmitted=3i,reply_received=3i,packets_received=3i,percent_packet_loss=0,percent_reply_loss=0,average_response_ms=6i,minimum_response_ms=6i,maximum_response_ms=7i 1487078577000000000

The conflicting fields are _average_response_ms_, which is float in linux and integer in windows.

Error is (seen in Windows machine):
> InfluxDB Output Error: {"error":"field type conflict: input field \"average_response_ms\" on measurement \"ping\" is type int64, already exists as type float"}
>

**Comment by dudusakharovich** [comment]
Hey @sparrc

I'm unable to use the ping input on windows machine.
What is the proper configuration which will make it succeed ?

**Comment by danielnelson** [comment]
@dudusakharovich Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.  Also, if you want your problem solved you should follow proper protocol for asking technical questions: include detailed information about what you are trying, what you expect to happen, and what actually happened.
