### ISSUE TITLE
can not enable TLS for inputs.influxdb_v2_listener 

### ISSUE THREAD

**Issue by ggzzzzzzz** [influxdata/telegraf#14337]
### Please direct all support questsions to slack or the forums. Thank you.

Is TLS supported for the plugin [[inputs.influxdb_v2_listener]] ?

# telegraf -config  /etc/telegraf/telegraf_infux.conf -test
2023-11-23T11:54:04Z I! Loading config: /etc/telegraf/telegraf_infux.conf
2023-11-23T11:54:04Z E! error loading config file /etc/telegraf/telegraf_infux.conf: plugin inputs.influxdb_v2_listener: line 23: configuration specified the fields ["tls-key" "tls-cert"], but they weren't used

======/etc/telegraf/telegraf_infux.conf============

[global_tags]
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 75000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
  debug = true
  quiet = false
  logtarget = "file"
  logfile = "/etc/telegraf/logs/telegraf_listener.log"
  logfile_rotation_max_size = "10MB"
  logfile_rotation_max_archives = 2
[[inputs.influxdb_v2_listener]]
  service_address = ":8087"
  data_format = "influx"
  bucket_tag = "Harvest"
  token = "<token>"
  parser_type = "upstream"
[[outputs.influxdb_v2]]
  urls = ["https://server1.corp.com"]
  token = "<token>"
  organization = "ORG"
  bucket = "Harvest"
  insecure_skip_verify = true
[[outputs.influxdb_v2]]
  urls = ["http://<IP_address>:8086"]
  token = "<token>"
  organization = "ORG"
  bucket = "Harvest"
  insecure_skip_verify = true

**Comment by srebhan** [comment]
@ggzzzzzzz I think this is a typo in your config. The log line

```text
2023-11-23T11:54:04Z E! error loading config file /etc/telegraf/telegraf_infux.conf: plugin inputs.influxdb_v2_listener: line 23: configuration specified the fields ["tls-key" "tls-cert"], but they weren't used
```
mentions `tls-key` and `tls-cert` but the actual options are `tls_key` and `tls_cert`. Please note the **underscore** instead of the dash!

**Comment by ggzzzzzzz** [comment]
thanks, yes, it should be underscore, after changed to underscore, it works
