### ISSUE TITLE
OPC UA PubSub input plugin

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/telegraf#14364]
### Use Case

Hello,

Due to the continuous implementation of OPC UA PubSub (MQTT) I thing it would be good to create a specific plugin or just an adaptation of JSON or JSON_V2 processors to consume OPC UA data published in data and metada topics in a broker, following OPC UA Part 14.

Regards

### Expected behavior

.

### Actual behavior

.

### Additional info

Request

**Comment by powersj** [comment]
Hi,

If you want someone to develop a new plugin to support a specific set of standards, then it is extremely helpful to provide as much detail as possible ;)

For example, what is missing from the current `opcua` or `opcua_listener` plugins to support this? Does a client already exist to communicate?

**Comment by alexmc1510** [comment]
Hello, you are fully right. I didn't have the laptop with me when I wrote the message.

Basically OPC UA PubSub follows a specification (part14) that stablishes the topic and payload structure for a message:

Topic: data
`{"MessageId":"1301","MessageType":"ua-data","PublisherId":"ua-zedc-kuka","Messages":[{"DataSetWriterId":40735,"Timestamp":"2023-11-28T14:40:31.1462199Z","Payload":{"ActualPosition":{"Value":-96.72047424316406}}},{"DataSetWriterId":43738,"Timestamp":"2023-11-28T14:40:31.1462199Z","Payload":{"ActualPosition":{"Value":-43.12690734863281}}},{"DataSetWriterId":64966,"Timestamp":"2023-11-28T14:40:31.6481097Z","Payload":{"ActualPosition":{"Value":-138.08384704589844}}},{"DataSetWriterId":10525,"Timestamp":"2023-11-28T14:40:31.6481097Z","Payload":{"ActualPosition":{"Value":73.17094421386719}}},{"DataSetWriterId":49549,"Timestamp":"2023-11-28T14:40:31.6481097Z","Payload":{"ActualPosition":{"Value":0.008375259116292}}}]}`

Topic: metadata
`{"MessageId":"1445","MessageType":"ua-metadata","PublisherId":"ua-zedc-kuka","DataSetWriterId":15636,"MetaData":{"Name":"urn:ua-zedc-kuka;nsu=http://opcfoundation.org/UA/CloudPublisher/;s=CurrentWorkingSetMBs","Fields":[{"Name":"CurrentWorkingSetMBs","FieldFlags":0,"BuiltInType":8,"DataType":{"Id":24},"ValueRank":-1,"MaxStringLength":0,"DataSetFieldId":"a025e999-abfa-4e69-9a91-dc735ecf9601"}],"ConfigurationVersion":{"MajorVersion":1,"MinorVersion":1}}}`

I would like to store the data topic in influxdb, taking into account that normally, everything belonging Payload will be measurement with field value, timestamp is in the main object and datasetwriterid should be added as tag as it is the key for linking data with metadata.
For metadata I am still thinking how to manage and where to store so all the help is appreciated.

Regards,

**Comment by alexmc1510** [comment]
Hello, thanks for your reply. Maybe there is a misunderstanding. The plugin
already exists, it is input.mqtt, the thing is how to process/parse the
payload structure officially delivered by OPC UA PubSub.

Is it more clear now?

Regards

**Comment by powersj** [comment]
> Is it more clear now?

Yes, however, like your previous support request in #14079, this is not the place to ask these questions. The issue tracker is for issues and feature requests. Please use the above links to the forums or slack to get help with parsing specific json.

Thanks
