### ISSUE TITLE
panic: negative refcount when returning deepcopy from starlark

### ISSUE THREAD

**Issue by shuebner** [influxdata/telegraf#14360]
### Relevant telegraf.conf

```toml
[[processors.starlark]]
  alias = "deepcopy_error"
  source = '''
def apply(metric):
  other = deepcopy(metric)
  other.name = "other"
  return [metric, other]
'''
```

### Logs from Telegraf

```text
2023-11-28T05:33:13Z I! Loading config: /etc/telegraf/telegraf.conf
2023-11-28T05:33:13Z I! Loading config: /etc/telegraf/telegraf.d/nats_consumer.conf
2023-11-28T05:33:13Z I! Loading config: /etc/telegraf/telegraf.d/output_process-values_influxdb.conf
2023-11-28T05:33:13Z I! Loading config: /etc/telegraf/telegraf.d/processor.conf
2023-11-28T05:33:13Z I! Starting Telegraf 1.27.4
2023-11-28T05:33:13Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 23 parsers, 59 outputs, 4 secret-stores
2023-11-28T05:33:13Z I! Loaded inputs: nats_consumer
2023-11-28T05:33:13Z I! Loaded aggregators:
2023-11-28T05:33:13Z I! Loaded processors: starlark
2023-11-28T05:33:13Z I! Loaded secretstores:
2023-11-28T05:33:13Z I! Loaded outputs: influxdb_v2
2023-11-28T05:33:13Z I! Tags enabled:
2023-11-28T05:33:13Z I! [agent] Config: Interval:1s, Quiet:false, Hostname:"", Flush Interval:10s
2023-11-28T05:33:13Z I! [inputs.nats_consumer] Started the NATS consumer service, nats: nats://testnats:4222, subjects: [mysubject], jssubjects: [], queue: telegraf_consumers
panic: negative refcount
```

### System info

telegraf:1.27-alpine, Docker version 20.10.9, build c2ea9bc90, Windows 10.0.19044

### Steps to reproduce

1. start telegraf with the processor config above (any source and sink should do)
2. let it consume a message from any source
3. boom
...

### Expected behavior

The above processor should return two metrics, the original one and the newly created, slightly altered one.

### Actual behavior

Telegraf process crashes with "panic: negative refcount"

**Comment by shuebner** [comment]
Hi,
thanks for the quick response. I dug a little deeper and found out the following:

Your config works for me.

In my full local config I use a nats_consumer input.
As soon as I add that to the config, the panic surfaces.

The refcount message appears in the log as soon as the message is consumed by telegraf.
This is independent of whether message consumption is triggered by interval or by force via SIGUSR1.

It is the same with 1.28.4.
Without the processor, no error is logged.

This is my full config for repro.

```toml
[agent]
  debug = true
  omit_hostname = true

[[inputs.nats_consumer]]
  servers = ["nats://testnats:4222"]
  subjects = ["mysubject"]
  data_format = "influx"

[[outputs.file]]

[[processors.starlark]]
  alias = "deepcopy_error"
  source = '''
def apply(metric):
  other = deepcopy(metric)
  other.name = "other"
  return [metric, other]
'''
```

I can prepare a running repro as a C# test with Testctontainers if necessary.

**Comment by Hipska** [comment]
@powersj I first thought about #14137, but that isn't released yet. This looks somewhat related to #13156

**Comment by powersj** [comment]
I was curious to see how far back this issue goes, and apparently it has been an issue since starlark was introduced in v1.15.0 (yikes). The root cause is related to the deep copy + tracking metrics. 

Plugin's like nats consumer and mqtt consumer, use a special metric type to track the metric as it makes its way through telegraf. That way Telegraf will only consume so many messages and also have the ability to tell the original sender that the metric was successfully (or not) processed.

It seems when we make a copy, we make a deep copy, but use the same tracking information as the original metric. This means that we were double acknowledging a metric, hence why the reference count was going negative.

**Comment by srebhan** [comment]
We can reproduce the issue via
```toml
[agent]
  debug = true
  omit_hostname = true

[[inputs.tail]]
  files = ["test_configs/starlark_tracking_metric.influx"]
  from_beginning = true
  data_format = "influx"

[[processors.starlark]]
  alias = "deepcopy_error"
  source = '''
def apply(metric):
  other = deepcopy(metric)
  other.name = "other"
  return [metric, other]
'''

[[outputs.file]]
  files = ["stdout"]
```

**Comment by srebhan** [comment]
@shuebner can you please test the binary in PR #14395 available once CI finished the tests?! Let me know if this fixes the issue for you!
