### ISSUE TITLE
Consider adding `logOnce` mechanism to `telegraf.Logger`

### ISSUE THREAD

**Issue by p-zak** [influxdata/telegraf#14367]
### Use Case

In some plugins, situations occasionally occur where errors related to metric retrieval occur (for a moment or continuously) in each subsequent call of the `Gather()` function. 
In order not to spam logs constantly with the same error, a user might want to log an error of a specific type only during its initial occurrence. 
Such functionality could be provided by adding a mechanism to the `telegraf.Logger`, tentatively named `logOnce`.

### Expected behavior

The user can utilize the generic `logOnce` mechanism.

### Actual behavior

There is no generic `logOnce` mechanism.

**Comment by powersj** [comment]
Hey,

Is this the same as what @srebhan proposed in https://github.com/influxdata/telegraf/issues/10229?

**Comment by p-zak** [comment]
That's right! Missed it...
