### ISSUE TITLE
Clickhouse plugin defines source tag incorrectly which causes filtering issue on wavefront proxy level

### ISSUE THREAD

**Issue by achaknalwar** [influxdata/telegraf#14396]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/clickhouse/clickhouse.go#L488

### Relevant telegraf.conf

```toml
[[inputs.clickhouse]]
  username = "default"
  servers  = ["http://127.0.0.1:8123"]
  auto_discovery = false
```

### Logs from Telegraf

```text
# telegraf --config /etc/telegraf/telegraf.d/system_metrics_input.conf --input-filter clickhouse --test --debug
2023-12-07T02:06:28Z I! Loading config file: /etc/telegraf/telegraf.d/system_metrics_input.conf
2023-12-07T02:06:28Z I! Starting Telegraf 1.26.0
2023-12-07T02:06:28Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-12-07T02:06:28Z I! Loaded inputs: clickhouse
2023-12-07T02:06:28Z I! Loaded aggregators:
2023-12-07T02:06:28Z I! Loaded processors:
2023-12-07T02:06:28Z I! Loaded secretstores:
2023-12-07T02:06:28Z W! Outputs are not used in testing mode!
2023-12-07T02:06:28Z I! Tags enabled: host=ip-10-10-101-12
2023-12-07T02:06:28Z D! [agent] Initializing plugins
2023-12-07T02:06:28Z D! [agent] Starting service inputs
> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=asynchronous_metric_log bytes=304731574i,parts=12i,rows=141915958i 1701914789000000000
> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=metric_log bytes=64341229i,parts=7i,rows=254541i 1701914789000000000
> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=part_log bytes=36972620i,parts=5i,rows=780156i 1701914789000000000
> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=query_log bytes=2203232396i,parts=12i,rows=12067705i 1701914789000000000
> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=query_thread_log bytes=7267232403i,parts=11i,rows=77785746i 1701914789000000000
```

### System info

Telegraf 1.26.0, Ubuntu 22.04 jammy

### Steps to reproduce

1. Deploy instance with mentioned Ubuntu version
2. Install telegraf package 
3. Create telegraf config for clickhouse
4. restart telegraf service
...

### Expected behavior

source should be renamed to source_name to avoid overwriting of sourceName tag

### Actual behavior

source is causing filtering issue

**Comment by powersj** [comment]
> source should be renamed to source_name to avoid overwriting of sourceName tag

I'm not following. You want `source` to become `source_name` so it avoids overwriting `sourceName`? Which of these is used by wavefront? Why not rename with a processor?

Given this metric, what did you expect it to look like:

> clickhouse_tables,database=system,host=ip-10-10-101-12,source=127.0.0.1,table=asynchronous_metric_log bytes=304731574i,parts=12i,rows=141915958i 1701914789000000000

**Comment by achaknalwar** [comment]
wavefront uses sourceName 

Renaming with preprocessor not possible because sourceName is used as default hostname for other plugins. Only for clickhouse I observed that sourceName getting replaced with 127.0.0.1

So it should look like following:
clickhouse_tables,database=system,host=ip-10-10-101-12,**source_name**=127.0.0.1,table=asynchronous_metric_log bytes=304731574i,parts=12i,rows=141915958i 1701914789000000000

**Comment by achaknalwar** [comment]
let me give it a try with suggested code. Thanks.
