### ISSUE TITLE
gocritic->preferDecodeRune - Detects expressions like []rune(s)[0] that may cause unwanted rune slice allocation. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14406]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [performance](https://go-critic.com/overview.html#checkers-from-the-performance-group) - Performance checks tell you about potential issues that can make your code run slower than it could be.
- checker: [preferDecodeRune](https://go-critic.com/overview.html#preferdecoderune) - Detects expressions like []rune(s)[0] that may cause unwanted rune slice allocation (see Go issue for details: https://github.com/golang/go/issues/45260).

### Example

**Before:**
```
r := []rune(s)[0]
```

**After:**
```
r, _ := utf8.DecodeRuneInString(s)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/parsers/csv/parser.go:202:21  gocritic  preferDecodeRune: consider replacing []rune(p.Delimiter)[0] with utf8.DecodeRuneInString(p.Delimiter)
plugins/parsers/csv/parser.go:206:21  gocritic  preferDecodeRune: consider replacing []rune(commaByte)[0] with utf8.DecodeRuneInString(commaByte)
plugins/parsers/csv/parser.go:209:23  gocritic  preferDecodeRune: consider replacing []rune(p.Comment)[0] with utf8.DecodeRuneInString(p.Comment)
plugins/serializers/csv/csv.go:49:19  gocritic  preferDecodeRune: consider replacing []rune(s.Separator)[0] with utf8.DecodeRuneInString(s.Separator)
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1 - the link describing the linter is very helpful to show the perf gains
