### ISSUE TITLE
gocritic->preferWriteByte - Detects WriteRune calls with rune literal argument that is single byte and reports to use WriteByte instead. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14409]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [performance](https://go-critic.com/overview.html#checkers-from-the-performance-group) - Performance checks tell you about potential issues that can make your code run slower than it could be.
- checker: [preferWriteByte](https://go-critic.com/overview.html#preferwritebyte) - Detects WriteRune calls with rune literal argument that is single byte and reports to use WriteByte instead.

### Example

**Before:**
```
w.WriteRune('\n')
```

**After:**
```
w.WriteByte('\n')
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1
