### ISSUE TITLE
gocritic->preferStringWriter - Detects w.Write or io.WriteString calls which can be replaced with w.WriteString. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14408]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [performance](https://go-critic.com/overview.html#checkers-from-the-performance-group) - Performance checks tell you about potential issues that can make your code run slower than it could be.
- checker: [preferStringWriter](https://go-critic.com/overview.html#preferstringwriter) - Detects w.Write or io.WriteString calls which can be replaced with w.WriteString.

### Example

**Before:**
```
w.Write([]byte("foo"))
```

**After:**
```
w.WriteString("foo")
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/intel_dlb/intel_dlb_test.go:887:12  gocritic  preferStringWriter: fileobj.WriteString(testFileContent) should be preferred to the fileobj.Write([]byte(testFileContent))
plugins/inputs/x509_cert/x509_cert_test.go:47:11   gocritic  preferStringWriter: tmpfile.WriteString(pki.ReadServerCert()) should be preferred to the tmpfile.Write([]byte(pki.ReadServerCert()))
plugins/inputs/x509_cert/x509_cert_test.go:163:13  gocritic  preferStringWriter: f.WriteString(test.content) should be preferred to the f.Write([]byte(test.content))
plugins/inputs/x509_cert/x509_cert_test.go:196:11  gocritic  preferStringWriter: f.WriteString(cert) should be preferred to the f.Write([]byte(cert))
plugins/inputs/x509_cert/x509_cert_test.go:245:11  gocritic  preferStringWriter: f.WriteString(cert) should be preferred to the f.Write([]byte(cert))
plugins/inputs/x509_cert/x509_cert_test.go:282:13  gocritic  preferStringWriter: f.WriteString(test.content) should be preferred to the f.Write([]byte(test.content))
tools/readme_config_includer/generator.go:94:3     gocritic  preferStringWriter: buf.WriteString("\n") should be preferred to the buf.Write([]byte("\n"))
tools/readme_config_includer/generator.go:101:4    gocritic  preferStringWriter: buf.WriteString("\n") should be preferred to the buf.Write([]byte("\n"))
tools/readme_config_includer/generator.go:109:3    gocritic  preferStringWriter: buf.WriteString("\n") should be preferred to the buf.Write([]byte("\n"))
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1

**Comment by Hipska** [comment]
Shouldn’t the preferred way be `buf.Write('\n')` for `buf.Write([]byte("\n"))`?

**Comment by zak-pawel** [comment]
> Shouldn’t the preferred way be `buf.Write('\n')` for `buf.Write([]byte("\n"))`?

@Hipska 
You're somewhat right, but instead of `buf.Write('\n')` (which won't compile), we may consider using `buf.WriteByte('\n')` as an alternative to proposed solution: `buf.WriteString("\n")`.
Remark: it will only work for single-byte strings.

**Comment by Hipska** [comment]
Yes sure. Was specifically referring to the ones with newline chars.
