### ISSUE TITLE
[outputs.elasticsearch] use measurement_name in indexname

### ISSUE THREAD

**Issue by moiney** [influxdata/telegraf#14418]
### Use Case

Currently, you can only use tags and date as template for the indexname in ElasticSearch outputs.
It would be great to use the name of the measure as well, as one could have the need for different retention policiers or indexing for different measures.

### Expected behavior

It should be possible to use measurement name in the indexName, something like 
`index_name = "telegraf-{{measurement_name}}-{{tag1}}-%Y.%m.%d"`
We could use other delimiters to mark a clear difference between measurement name and tags.

### Actual behavior

For Elastic output, you can use {{tag}} to reference a tag, or date specifier through % notation.

### Additional info

I'm fine with implementing it myself, but I don't know what would be the appropriate way of specifying measurement_name vs tags, given all {{}} currently means tags.

**Comment by powersj** [comment]
Hi,

Are you actually using elasticsearch or opensearch? I ask only because the opensearch plugin has this ability already.

> I don't know what would be the appropriate way of specifying measurement_name vs tags, given all {{}} currently means tags.

You could look at checking for a specific value first, like `{{measurement_name}}` before checking for tags if possible.

**Comment by moiney** [comment]
I didn't realise there was an Opensearch output plugin that came out. I'll switch to it since we're using Opensearch anyway.

I still think this feature is worth it for ElasticSearch users in the future.
