### ISSUE TITLE
gocritic->sliceClear - Detects slice clear loops, suggests an idiom that is recognized by the Go compiler. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14412]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [performance](https://go-critic.com/overview.html#checkers-from-the-performance-group) - Performance checks tell you about potential issues that can make your code run slower than it could be.
- checker: [sliceClear](https://go-critic.com/overview.html#sliceclear) - Detects slice clear loops, suggests an idiom that is recognized by the Go compiler.

### Example

**Before:**
```
for i := 0; i < len(buf); i++ { buf[i] = 0 }
```

**After:**
```
for i := range buf { buf[i] = 0 }
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1

**Comment by rkerno** [comment]
FYI - Here's the original reference to the compiler that implements this: https://codereview.appspot.com/137880043
