### ISSUE TITLE
Reduce CircleCI Usage

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#14414]
### Use Case

In the last 30 days we have used over 2.7 million tokens with the top 5 jobs as follows:

```
Job                    Tokens (% of total)
- test-go-windows 	1300k (47.4%)
- test-go-mac 		 655k (23.6%)
- test-integration 	 146k ( 4.4%)
- test-go-linux 	 121k ( 4.0%)
- test-go-linux-386 	  85k ( 2.8%)
```

As 71% of all our token usage is due to two jobs, test-go-windows and test-go-mac, we need to re-evaluate the usage and value of these jobs and ensure we can justify the cost.

These two jobs cost so much as they are not running in a container with our customer image. Instead, Windows uses the Windows orb and macOS uses the XCode + macOS environment. These incur much higher costs.

## Costs

These values are taken from [resource classes](https://circleci.com/product/features/resource-classes/) and are based on what we use as of this issue:

* Docker large       -  20 credits/min
* Linux VM xlarge    - 100 credits/min (used for integration tests)
* macOS M1 medium    - 150 credits/min
* Windows xlarge     - 120 credits/min

There are no smaller macOS executors that are not deprecated. There are smaller Windows, but those would only take longer as well.

## Job Execution

The two windows and mac jobs are primarily used to:

1) Lint the code
2) Run unit tests

There is value in these jobs in order to catch OS specific lint and test issues.

## Proposal

The fast, get it done proposal would include:

* Stop running test-go-windows and test-go-mac on every PR
* Ensure these tests are run on master, post-commit
* Increase size of test-integration runner to reduce overall time

While this would immediately save us a huge amount of tokens, the cost to the project is the lost of PR-based testing on these platforms. Any test or lint issues would then be revealed post-merge. This would require the maintainers to then fix or revert the previous commit.

### Alternatives

* Using larger systems may help, but only about half the runtime is CPU bound. Primarily when the linters is run and at the start of unit tests.

**Comment by zak-pawel** [comment]
@powersj 
For linter tasks maybe it makes sense to run:
- `GOOS=windows golangci-lint run ./...`
- `GOOS=darwin golangci-lint run ./...`

in Linux containers?

**Comment by srebhan** [comment]
How about also running all tests for the different archs in one job on a linux container? This would probably also benefit from caching...
