### ISSUE TITLE
Deployment status of gocritic checkers (group: performance).

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14415]
### Current status:

| Checker | Issue | To enable? | PR(s) | Work finished? |
| --- | :-: | :-: | :-: | :-: |
| appendCombine - Detects append chains to the same slice that can be done in a single append call | https://github.com/influxdata/telegraf/issues/14402 | Y | https://github.com/influxdata/telegraf/pull/14451 | |
| equalFold - Detects unoptimal strings/bytes case-insensitive comparison | https://github.com/influxdata/telegraf/issues/14403 | Y | https://github.com/influxdata/telegraf/pull/14452 | Y |
| hugeParam - Detects params that incur excessive amount of copying | https://github.com/influxdata/telegraf/issues/14404 | Y | https://github.com/influxdata/telegraf/pull/14454 | Y |
| indexAlloc - Detects strings.Index calls that may cause unwanted allocs | https://github.com/influxdata/telegraf/issues/14405 | Y | https://github.com/influxdata/telegraf/pull/14449 | Y |
| preferDecodeRune - Detects expressions like []rune(s)[0] that may cause unwanted rune slice allocation | https://github.com/influxdata/telegraf/issues/14406 | Y | https://github.com/influxdata/telegraf/pull/14453 | Y |
| preferFprint - Detects fmt.Sprint(f/ln) calls which can be replaced with fmt.Fprint(f/ln) | https://github.com/influxdata/telegraf/issues/14407 | Y | https://github.com/influxdata/telegraf/pull/14453 | Y |
| preferStringWriter - Detects w.Write or io.WriteString calls which can be replaced with w.WriteString | https://github.com/influxdata/telegraf/issues/14408 | Y | https://github.com/influxdata/telegraf/pull/14452 | Y |
| preferWriteByte - Detects WriteRune calls with rune literal argument that is single byte and reports to use WriteByte instead | https://github.com/influxdata/telegraf/issues/14409 | Y | https://github.com/influxdata/telegraf/pull/14449 | Y |
| rangeExprCopy - Detects expensive copies of for loop range expressions | https://github.com/influxdata/telegraf/issues/14410 | Y | https://github.com/influxdata/telegraf/pull/14449 | Y |
| rangeValCopy - Detects loops that copy big objects during each iteration | https://github.com/influxdata/telegraf/issues/14411 | Y | https://github.com/influxdata/telegraf/pull/14454 | Y |
| sliceClear - Detects slice clear loops, suggests an idiom that is recognized by the Go compiler | https://github.com/influxdata/telegraf/issues/14412 | Y | https://github.com/influxdata/telegraf/pull/14449 | Y |
| stringXbytes - Detects redundant conversions between string and []byte | https://github.com/influxdata/telegraf/issues/14413 | Y | https://github.com/influxdata/telegraf/pull/14452 | Y |

**Comment by powersj** [comment]
next steps: do PR reviews

**Comment by powersj** [comment]
Closing as all PRs are merged
