### ISSUE TITLE
[inputs.php-fpm] Adding full metrics

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#14421]
### Use Case

Add support to per process monitoring (full status page) for [php-fpm input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/phpfpm)

It allow to get some metrics to be able to follow consumption of memory/cpu/etc by request/uri/script.

### Expected behavior

- Add full metrics by process:

```
    phpfpm:
        tags:
            pool
            url
            user
            request uri
            request method
            script
        fields:
            state
            start time (optionnal)
            start since (optionnal)
            requests
            request duration
            content length
            last request cpu
            last request memory
```

### Actual behavior
```
phpfpm
    tags:
        pool
        url
    fields:
        accepted_conn
        listen_queue
        max_listen_queue
        listen_queue_len
        idle_processes
        active_processes
        total_processes
        max_active_processes
        max_children_reached
        slow_requests
```

### Additional info

Full info in json mode can be found via the path 127.0.0.1/fpm-status?full&json

Related to previous closed ticket: https://github.com/influxdata/telegraf/issues/5737

**Comment by powersj** [comment]
Hi,

Is this something you plan on contributing?

If not, could you share what that URL looks like to aid in someone implementing this? We would need to consider if a different metric name also makes sense to distinguish the current metrics any new things we collect.

**Comment by powersj** [comment]
@anthosz,

Does the current plugin work with JSON output? It looks like we currently parse any output line by line.

Does 127.0.0.1/fpm-status?full produce the same data you provided, but not in JSON?

Can you give the artifacts in https://github.com/influxdata/telegraf/pull/14423 a try? I have added everything missing as a field for now.

Thanks!

**Comment by powersj** [comment]
ok new PR: #14421 if you could give that a shot in 20-30mins once new artifacts are attached. You will need to 1) use the JSON URL and 2) a new config option to specify the new metrics.

```toml
[[inputs.phpfpm]]
  urls = ["http://127.0.0.1/fpm-status?json&full"]
  format = "status"
```

Technically you could probably do this with the JSON parser or XPATH parsers... but this isn't too hard to add.

**Comment by anthosz** [comment]
@powersj no output anymore with:
```
[[inputs.phpfpm]]
  urls = ["http://127.0.0.1/fpm-status?json&full"]
  format = "status"
```

If I remove the format = "status" + json, I have the original output.

Telegraf 1.30.0-0c0ea62c (git: pull/14430@0c0ea62c)

**Comment by powersj** [comment]
Ugh my bad, it should be `format = json` obviously since you are getting JSON data ;)

**Comment by anthosz** [comment]
> Ugh my bad, it should be `format = json` obviously since you are getting JSON data ;)

At the time I didn't even make the connection -_-

But yep, I confirm that all is good :)
