### ISSUE TITLE
Mistake in CHANGELOG.md regarding #13791

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#14426]
### Relevant telegraf.conf

```toml
none
```

### Logs from Telegraf

```text
none
```

### System info

irrelevant

### Steps to reproduce

`CHANGELOG.md`:
```
## v1.28.0 [2023-09-11]

### Important Changes

- [#13791](https://github.com/influxdata/telegraf/pull/11493) `metricpass`
Removed the Python compatibility support for "not", "and", and "or" keywords.
This support was incorrectly removing these keywords from actual data. Users
should instead use the standard "!", "&&", and "||" operators.
```

The Link does point to the wrong PR. 13791 is correct. .../11493 is not.

### Expected behavior

Link pointing to the correct PR

### Actual behavior

Link pointing to the wrong PR

### Additional info

Not very important. But actually confused me.

**Comment by srebhan** [comment]
@knollet would you care to send a quick PR?!? Planning to do a release today and definitively want this corrected...
