### ISSUE TITLE
Drop responses with excessively large bodies from Prometheus exporters

### ISSUE THREAD

**Issue by hhiroshell** [influxdata/telegraf#14437]
### Use Case

When Telegraf runs in a Kubernetes cluster, it automatically detects newly deployed pods and scrapes metrics from their exporters.
If new pods with exporters return excessively large responses, it can cause an overflow in Telegraf's buffer. This situation affects all metrics of pods scraped by the Telegraf.
This issue is more serious in multi-tenant clusters because a pod from one cluster user can affect the pods of other users.

### Expected behavior

- Drop responses with excessively large bodies from Prometheus exporters.
- The body size threshold can be adjusted by a configuration file parameter.

### Actual behavior

- Telegraf attempts to read all responses from the target exporters. However, if the metrics exceed the buffer capacity, it is unpredictable which metrics will be dropped.

### Additional info

It seems possible to implement this by checking the value of the Content-Length response header, around the location indicated by the link below.

- https://github.com/influxdata/telegraf/blob/2b731c2d577a34ecacbb921af89a33d8b84aaecd/plugins/inputs/prometheus/prometheus.go#L430-L438

If this approach seems reasonable, I will implement it.

**Comment by powersj** [comment]
Hi,

How large of a response are you seeing? Is adjusting the buffer size not an option?

I am not opposed to such an option, but I want to be sure the existing options do not already help the situation.

Thanks

**Comment by hhiroshell** [comment]
Hello @powersj 

Recently, I encountered a situation where the amount of metrics from an exporter increased over time. In this case, no matter what buffer size is set, eventually causing an overflow is inevitable.

The issue is caused by an error in the implementation of the tag normalization for the exporter. But cluster users cannot always be clever enough to avoid introducing such bugs. So it's desirable that they do not affect the metrics of other pods.

Thanks

**Comment by powersj** [comment]
Hi,

I have put up #14455 which includes a new config option called `content_length_limit`. This would let you set a max content length. If the content length of a page exceeds that limit, then we would skip that URL.

As-is this does not produce any errors only a debug message, but I think I might want to change that.

Can you try the artifacts in #14455? And let me know if that would help your situation?

Thanks!

**Comment by hhiroshell** [comment]
Hi,

Thanks @powersj !
I will try out the artifacts within a few days. Please wait!

**Comment by hhiroshell** [comment]
Hi,

I found that, in many cases, exporters return responses using chunked encoding. The responses don't have a "Content-Length" header in such situations.
Therefore, it is necessary to check the size of the response body against the actual body, but only after the entire body has been received.

For now, that's all for the update. I will experiment and try to find an implementation that works well.

**Comment by Hipska** [comment]
Couldn't this also be solved by using a tracking accumulator? So that new metrics are only added to the buffer when there is actually place for them?

**Comment by powersj** [comment]
> Couldn't this also be solved by using a tracking accumulator?

That is only used for plugins that communicate back to the resource (i.e. give me N messages). The issue here is that the prometheus endpoint is producing huge numbers of metrics and telegraf cannot say give me only N, it is all or nothing.

**Comment by hhiroshell** [comment]
> Therefore, it is necessary to check the size of the response body against the actual body, after the entire body has been received.

I started to implement it. https://github.com/influxdata/telegraf/pull/14548
Some CI tasks are failing, but the feature works in my dev environment.

I'm trying to fix the CI issues. please wait.
