### ISSUE TITLE
Update or Deprecate Aerospike input plugin

### ISSUE THREAD

**Issue by hev** [influxdata/telegraf#14450]
### Use Case

Users should use the [aerospike-prometheus-exporter](https://github.com/aerospike/aerospike-prometheus-exporter) + prometheus input plugin to ensure they get all supported Aerospike metrics regardless of version. 

### Expected behavior

Metrics will better align with aerospike metric reference regardless of Aerospike server version. 

### Actual behavior

Current behavior does not get all available metrics documented.

**Comment by Hipska** [comment]
What about updating the current Aerospike plugin to add support for these new/available metrics?

**Comment by hev** [comment]
I am not opposed to that -- and aerospike exporter would be a good reference for doing so. That said, the exporter is supported by Aerospike so it's more likely to get updates if/when API calls change or are added. Take a look at the exporter and let me know what you think.

**Comment by srebhan** [comment]
@hev a PR to update the plugin would be welcome!
