### ISSUE TITLE
Enhancement to Processors.s2geo: Dynamic cell_level

### ISSUE THREAD

**Issue by cruscio** [influxdata/telegraf#14467]
### Use Case

I'm trying to use Influx to track and visualize my OwnTracks location data.

OwnTracks emits [location data](https://owntracks.org/booklet/tech/json/) with a latitude, longitude, and accuracy (in meters). Given that a phone's location accuracy can vary over time, it'd be nice if it was possible to set s2Geo `cell_level` dynamically as well.

### Expected behavior

Ability to dynamically set cell_level for each measurement when processing lat/lon/area measurements into s2geo cell Ids

### Actual behavior

`cell_level` is set to a numeric value in the processor configuration, constant at runtime. All processed measurements share a singular cell level.

### Additional info

The desired outcome could be accomplished a couple ways: 

1. User provides `area`:
A configuration parameter `accuracy_field ## Area in meters squared used to determine cell_level`, similar to `lat_field` and `lon_field`. The processor would use the value in that field to select the appropriate cell_level based on the nearest _average area_ in the [official ranges](http://s2geometry.io/resources/s2cell_statistics.html). 

    - Stretch goal: in addition to writing the cell id to `tag_key` also have a config value for where to write the cell_level that was used (or is this easily determinable from the cell ID itself, and therefore redundant?).
    - Side question: is there something available for distance that's similar to `time.ParseDuration()`, where a value could include units (e..g. `2km` vs `3m` vs `'5cm`)? Or would this need to be a fixed unit (e.g. all values in meter: `2000`, `3`, and `0.05` respectively)?

2. User provides `cell_level`: 
A configuration parameter `cell_level_tag` that would override `cell_level` when the tag exists on a measurement (similar to how `bucket` and `bucket_tag` logic works iirc?). If this tag exists and contains an int from 0 to 30, it would be used during processing of the measurement.

Option 1 would be more work, but well within the spirit of the processor: Given a geographical point/area (non-S2 things), determine Cell ID (S2 thing). Option 2 _would_ be easier to implement; however, it requires inputting an S2-thing into the thing that generates S2 things. Option 1 feels more proper/correct; it seems reasonable to expect the S2Geo processor to handle all the S2Geo-specific calculations.

Either option would be an awesome enhancement.

**Comment by powersj** [comment]
Hi @cruscio,

I have implimented option 2 in https://github.com/influxdata/telegraf/pull/14472 Can you give that a try once artifacts are posted to it? Thanks!

It adds a new `cell_level_field` option. This is the field key that the processor will look for to determine the cell level.

**Comment by powersj** [comment]
@cruscio,

Did you want to give my PR a try?

**Comment by cruscio** [comment]
Hey @powersj - Been meaning to since I saw the PR. I tried a couple days ago and couldn't run the PR build on my mac ("app that can’t be checked for malicious software"), and wasn't sure which linux_arm*.tar.gz to grab for testing on a Raspberry Pi - and at that point I ran out of time. I'll try to figure out a place to run one of the builds soon. Looking at the code, this seems to be exactly what I need. Thanks.

**Comment by powersj** [comment]
> "app that can’t be checked for malicious software"

ah yes we don't sign build artifacts. You can override this in Security and Privacy if you feel compfortable.

> wasn't sure which linux_arm*.tar.gz to grab for testing on a Raspberry Pi

Think it depends on which Pi, if it is newer you might try the arm64 one, otherwise try armhf.
