### ISSUE TITLE
[inputs.php-fpm] pid missing in the tag

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#14461]
### Relevant telegraf.conf

```toml
[[inputs.phpfpm]]
  urls = ["http://127.0.0.1:8080/fpm-status?json&full"]
  format = "json"
```

### Logs from Telegraf

```text
Not relevant
```

### System info

Telegraf 1.29.1

### Docker

Not relevant

### Steps to reproduce

1. Run it when multiple php workers are present
2. Only one value can be extracted due to the fact all tags are identical

### Expected behavior

    phpfpm:
        tags:
            pool
            url
            user
            request uri
            request method
            script
            pid
        fields:
            state
            start time (optionnal)
            start since (optionnal)
            requests
            request duration
            content length
            last request cpu
            last request memory

### Actual behavior

    phpfpm:
        tags:
            pool
            url
            user
            request uri
            request method
            script
        fields:
            state
            start time (optionnal)
            start since (optionnal)
            requests
            request duration
            content length
            last request cpu
            last request memory

### Additional info

In the previous feature request #14421, I forgot to mention the pid.

Due to that, when we try to monitor it with multiple pid, we can extract only one of the values (tags are common so value is random)

cc @powersj

**Comment by powersj** [comment]
Hmm, using a PID as a tag is strongly discouraged given the possible variety of values. It can lead to huge cardinality in InfluxDB, for example.

That said, I don't think there is any other field or tag we could use. 

> multiple php workers are present

Is this always the case? Trying to understand if we could make the PID as a tag be opt-in.

**Comment by anthosz** [comment]
> Is this always the case? Trying to understand if we could make the PID as a tag be opt-in.

Yes, the goal of fpm is to have generaly several workers.

Depending if static or dynamic, we can have few workers or hundred of workers.

Once a worker reach the limitation of job, the worker is killed and a new one replace it.

But indeed, I cannot found anything to replace the pid for the reference.

**Comment by powersj** [comment]
ok I've put up #14462 which adds the PID as a field. In general we don't add PIDs as tags as I mentioned, so this gives the user the option to convert the PID to a tag via the converter processor, via something like:

```toml
[[processors.converter]]
  namepass = ["phpfpm_process"]
  [processors.converter.fields]
    tag = ["pid"]
```

**Comment by anthosz** [comment]
@powersj when do you think it will be merged?

**Comment by powersj** [comment]
Unfortunately, the other maintainer is on holiday already. We will land PRs the first week of January. You are welcome to grab the builds from the PR if you want to run with them for now.
