### ISSUE TITLE
Add binary serializer 

### ISSUE THREAD

**Issue by Ignatella** [influxdata/telegraf#14473]
### Use Case

There is binary parser plugin, but no binary serializer plugin. Binary serialization is needed with  `file` or `socket_writer` plugins when communicating with e.g. raw tcp receiver or driver.

### Expected behavior

User can define structure of output telegram. Big nad little endianness is supported, fields can be ordered and converted to target data type

### Actual behavior

Not supported

**Comment by powersj** [comment]
Hi,

Looks like you submitted a PR! Thanks for that. Is that something you plan on wrapping up?

**Comment by Ignatella** [comment]
@powersj Hi,

Yes, sure, just got overwhelmed with things around, plan is to fix mentioned in PR things by the end of the week
