### ISSUE TITLE
skip PDH_CSTATUS_NO_INSTANCE error when using raw values

### ISSUE THREAD

**Issue by hiroshi-iim** [influxdata/telegraf#14486]
### Use Case

I using win_perf_counter plugin in Telegraf and collect data from process with "UseRawValues = true".
```
[[inputs.win_perf_counters]]
UseWildcardsExpansion = true

[[inputs.win_perf_counters.object]]
  UseRawValues = true
  ObjectName = "Process"
  Instances = ["*"]
  Counters = [
    "ID Process",
    "% Processor Time",
  ]
```
With this configuration, sometimes telegraf logs this error
```
E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": error while getting value for counter "\\\\...\\Process(...)\\ID Process": The specified instance of the performance object was not found.
```

Is there any telegraf setting that skip this error?

### Expected behavior

Ignore this error and get values of existing instances.

### Actual behavior

Get error and no values.

### Additional info

After adding `IgnoredErrors = ["PDH_CSTATUS_NO_INSTANCE"]` logs same error.

**Comment by powersj** [comment]
Hi,

That error message is coming from [the gather function here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/win_perf_counters.go#L459-L463). We do not check for ignored errors here. The ignored errors occurs prior to this when we go around collecting when [telegraf sees what counters exist here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/win_perf_counters.go#L427-L432).

I need to sync with the other maintainer and decide if we want to extend the check error or not.

**Comment by powersj** [comment]
Hi @hiroshi-iim,

Can you download an artifact on #14526 and try that? I've added the check error function to that call. If you could verify that the error is in fact hidden, please I would appreciate it.

Thanks!

**Comment by hiroshi-iim** [comment]
Thanks @powersj,

I tried that. But it still logs error and couldn't get values of existing instances.
```
2024-01-04T23:46:30Z E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": error while getting value for counter "\\\\...\\Process(...)\\ID Process": The specified instance of the performance object was not found.
```
With `IgnoredErrors = ["PDH_CSTATUS_NO_INSTANCE"]`, It logs this error.
```
2024-01-04T23:59:00Z E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": %!w(<nil>)
```

In my opinion, to skip this error, how about adding `PdhCstatusNoInstance` to `func isKnownCounterDataError`? 

https://github.com/influxdata/telegraf/blob/d7a5bf6d7087ee270b7bcaf39017b01e1591a9af/plugins/inputs/win_perf_counters/win_perf_counters.go#L484-L492

https://github.com/influxdata/telegraf/blob/d7a5bf6d7087ee270b7bcaf39017b01e1591a9af/plugins/inputs/win_perf_counters/win_perf_counters.go#L573-L583

**Comment by powersj** [comment]
> I tried that. But it still logs error and couldn't get values of existing instances.

To be clear, we are not removing this error from ever showing up by default. You would need to opt-in to have it hidden. Hiding it from everyone would create confusion to users when they do not get data back as it is an actual error in certain cases.

> func isKnownCounterDataError

This is not where the error is coming from.

> With IgnoredErrors = ["PDH_CSTATUS_NO_INSTANCE"], It logs this error.

Good, then we can confirm that it turned the error into nil and we can check for it now. I have updated the PR to verify that and it should now avoid printing the error when added to the `IgnoredErrors` option.

**Comment by hiroshi-iim** [comment]
Hi @powersj 

My understanding is that the error comes from `GetRawCounterValue` in `gatherComputerCounters` looping `hostCounterInfo.counters`.  When the error occured at Nth of `hostCounterInfo.counters` `gatherComputerCounters` returns with error state and does not process elements after N+1th. Is the understanding correct?
I think that the error(`PdhCstatusNoInstance`) means one of the instances is invalid and others might be still valid in the use case which I commented before.
So, I expected that `gatherComputerCounters` process all elements of `hostCounterInfo.counters` regardless of `PdhCstatusNoInstance` error.

Thanks.

**Comment by powersj** [comment]
> My understanding is that the error comes from GetRawCounterValue in gatherComputerCounters looping hostCounterInfo.counters.

Yes, except it can also come from `GetFormattedCounterValueDouble` or `GetRawCounterArray` or `GetFormattedCounterArrayDouble`.

> When the error occured at Nth of hostCounterInfo.counters gatherComputerCounters returns with error state and does not process elements after N+1th. Is the understanding correct?

Yes

> So, I expected that gatherComputerCounters process all elements of hostCounterInfo.counters regardless of PdhCstatusNoInstance error.

Do you have an example that throws this error, but has additional data?

**Comment by hiroshi-iim** [comment]
Hi @powersj 

> Do you have an example that throws this error, but has additional data?

For example
```
[agent]
  round_interval = true
  precision = "5s"
  interval = "5s"

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true

[[inputs.win_perf_counters.object]]
  UseRawValues = true
  ObjectName = "Process"
  Instances = ["OUTLOOK*", "python*"]
  Counters = [
    "ID Process",
    "% Processor Time",
]    

[[outputs.file]]
  files = ["stdout"]
  data_format = "csv"
  csv_timestamp_format = "2006-01-02T15:04:05Z07:00"
```

1. Start outlook and run `python -c "while True: i=1"`.
2. Then start telegraf with above configuration.
3. Wait until telegraf outputs records for 1st interval.
4. Then Quit outlook.

In this senario, telegraf outputs error logs shown in below and stops to output records until counters are refreshed.
```
E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process": The specified instance of the performance object was not found.
```

Next, I temporarily modified `isKnownCounterDataError` function to return true when errorcode is `PdhCstatusNoInstance` and ran same senario. 
In the case telegraf outputs warn logs shown in below but continue to output records for python instance which had consistent value.
```
W! [inputs.win_perf_counters] Error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process", instance: OUTLOOK, will skip metric: The specified instance of the performance object was not found.
```

Actually I have to set `Instances = ["*"]` in real case. In that case there are more chances to see `PdhCstatusNoInstance` error.

Thanks.

**Comment by powersj** [comment]
@hiroshi-iim,

ok, please file a new issue with the above info and we can talk further about ignoring `PdhCstatusNoInstance`. For the purpose of this bug I'd like to keep it to the additional check error for now.

**Comment by hiroshi-iim** [comment]
Thanks @powersj 

I created the issue https://github.com/influxdata/telegraf/issues/14557
