### ISSUE TITLE
MongoDB plugin always shows 0 replication lag

### ISSUE THREAD

**Issue by lassizci** [influxdata/telegraf#1449]
### Relevant telegraf.conf:

```
[[inputs.mongodb]]
  servers = ["127.0.0.1:27017"]
```
### System info:

telegraf 1.0.0-beta2
mongodb 3.2.7

repl_lag seems to always output 0i even  though there's replication lag on the secondaries. I've been monitoring this through mongodb cloud. I do get all the other metrics pretty much as expected.

**Comment by daviesalex** [comment]
What does SHOW SLAVE STATUS show?

**Comment by apinyarr** [comment]
+1

**Comment by im-vincent** [comment]
Use two configuration files
```
/usr/bin/telegraf -config-directory /etc/telegraf/telegraf.d

vi rs0-0.conf
[[inputs.mongodb]]
  servers = ["8.8.8.8:27017"]
#PRIMARY

vi rs0-1.conf
[[inputs.mongodb]]
  servers = ["8.8.8.8:27018"]
#SECONDARY
```

Modify the `mongostat.go` 

```
-	"gopkg.in/mgo.v2/bson"

 type ReplSetMember struct {
-	Name       string               `bson:"name"`
-	State      int64                `bson:"state"`
-	OptimeDate *bson.MongoTimestamp `bson:"optimeDate"`
+	Name       string    `bson:"name"`
+	State      int64     `bson:"state"`
+	OptimeDate time.Time `bson:"optimeDate"`
 }

-		if me.OptimeDate != nil && master.OptimeDate != nil && me.State == 2 {
+		if me.State == 2 {
 			// MongoTimestamp type is int64 where the first 32bits are the unix timestamp
-			lag := int64(*master.OptimeDate>>32 - *me.OptimeDate>>32)
+			lag := master.OptimeDate.Unix() - me.OptimeDate.Unix()

```

From Source:

Telegraf manages dependencies via gdm, which gets installed via the Makefile if you don't have it already. You also must build with golang version 1.5+.

Install Go
Setup your GOPATH
Run go get github.com/influxdata/telegraf
Run cd $GOPATH/src/github.com/influxdata/telegraf
Run make

**Comment by sparrc** [comment]
@im-vincent could you submit a PR?

**Comment by im-vincent** [comment]
I have already submit a PR as https://github.com/im-vincent/telegraf/

**Comment by sparrc** [comment]
@im-vincent I haven't received a PR

**Comment by im-vincent** [comment]
PR https://github.com/influxdata/telegraf/pull/2125

Is that right?

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/2125

**Comment by 1medusa1** [comment]
Downloaded the rpm straight from influxdb and this is not working

**Comment by chezneUE** [comment]
Also having issue this is my configuration one configuration file telegraf.conf input plugin content part below:

[[inputs.mongodb]] # PRIMARY
servers = ["mongodb://telegraf:telegraf@localhost:27017/?replicaSet=s0&authSource=admin"]

[[inputs.mongodb]] # SECONDARY
servers = ["mongodb://telegraf:telegraf@10.0.0.1:27017/?replicaSet=s0&authSource=admin"]

[[inputs.mongodb]] # SECONDARY
servers = ["mongodb://telegraf:telegraf@10.0.0.2:27017/?replicaSet=s0&authSource=admin"]
