### ISSUE TITLE
procstat pattern allow list as input

### ISSUE THREAD

**Issue by hertz1987** [influxdata/telegraf#14498]
### Use Case

We need to gather multiple processes (>50) with the same settings ( fieldpass & tagexclude ), but don't want to repeat these settings in all those configuration files (procstat/<process>.conf), instead we wish to use a single configuration file

### Expected behavior

A single procstat.conf would be sufficient for gathering all processes:
[[inputs.procstat]]
pattern = ['patternA',
                 'patternB',
                 'patternC',
                  ...,
                 'patternZZZ'
                 ]

fieldpass = ['memory_rss', 'memory_swap']
tagexclude = ['pattern']

### Actual behavior

We must either:
1. write all patterns in one line (which is pretty ugly when there are more than 50 process patterns):

[[inputs.procstat]]
pattern = 'patternA|patternB|patternC|...|patternZZZ'

fieldpass = ['memory_rss', 'memory_swap']
tagexclude = ['pattern']

or
2. write a configuration file for each process, but the settings ( fieldpass / tagexclude /...) would be redundant across all these configuration files which makes maintenance quite difficult:

patternA.conf:
[[inputs.procstat]]
pattern = 'patternA'
fieldpass = ['memory_rss', 'memory_swap']
tagexclude = ['pattern']

patternB.conf:
[[inputs.procstat]]
pattern = 'patternB'
fieldpass = ['memory_rss', 'memory_swap']
tagexclude = ['pattern']

...

patternZZZ.conf:
pattern = 'patternZZZ'
fieldpass = ['memory_rss', 'memory_swap']
tagexclude = ['pattern']

**Comment by srebhan** [comment]
@hertz1987 sorry for the late response!

The main concerns from my side regarding the suggested change are

1.  The code becomes more complex as we also need to accumulate the found processed for the "total" metrics
2. It becomes unclear what the "total" metrics are about. Do we now get one total per pattern? Or a total for the array of patterns? Or both?
3. It might serve as an example for requesting this to other plugins where the above issues are even more severe.

There are additional timing issues when assuming you want a total over the whole list, but that's another story.

Honestly speaking, as for all large installations, you should create a template and just generate the plugin configs from the template and your list if you want to avoid editing those manually...

**Comment by srebhan** [comment]
@hertz1987 this should be possible since PR #14948 by using `filter` section(s). Could you please use a [nightly build](https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md) to verify this issue is solved?
