### ISSUE TITLE
[diskio] Change skip_serial_number to on by default to avoid high cardanity

### ISSUE THREAD

**Issue by daviesalex** [influxdata/telegraf#1450]
Troubleshooting InfluxDB performance with @jwilder , @toddboom , @benbjohnson , @pauldix  and @fred-influx we have realized that under the default config, the "serial" data in the diskio plugin in real world environments is too high cardinality and produces pathological performance.

Users are unlikely to expect this from telegraf, so this issue is a feature request to set skip_serial_number = true by default, so one would have to disable it to get this data, i.e.:

```
[[inputs.diskio]]
  skip_serial_number = false
```

RFC

**Comment by sparrc** [comment]
👍
