### ISSUE TITLE
telegraf.service: Got notification message from PID XXX, but reception only permitted for main PID YYY

### ISSUE THREAD

**Issue by shrx** [influxdata/telegraf#14500]
### Relevant telegraf.conf

```toml
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  hostname = ""
  omit_hostname = true
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "home"
  skip_database_creation = true
  username = "telegraf"
  password = "XXXXXX"
 [[inputs.exec]]
   commands = [
     "/home/pi/bin/script1",
     "/home/pi/bin/script2"
   ]
   timeout = "6s"
   data_format = "influx"
```

### Logs from Telegraf

```text
Dec 23 00:59:04 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3572831, but reception only permitted for main PID 3571618
Dec 23 00:59:08 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3572834, but reception only permitted for main PID 3571618
Dec 23 01:00:04 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3572948, but reception only permitted for main PID 3571618
Dec 23 01:00:08 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3572951, but reception only permitted for main PID 3571618
Dec 23 01:01:01 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3573066, but reception only permitted for main PID 3571618
Dec 23 01:01:05 raspberrypi systemd[1]: telegraf.service: Got notification message from PID 3573069, but reception only permitted for main PID 3571618
```

### System info

Telegraf 1.29.1-1

### Steps to reproduce

script1 and script2 are producing the following output, respectively:

device1 power_on=0i,set_temperature=25.0,current_temperature=22.0
device2 detected=1i,rssi=-62i

### Expected behavior

No systemd warnings.

### Actual behavior

There are systemd warnings for each script execution.

**Comment by shrx** [comment]
A solution appears to be adding `NotifyAccess=all` under the `[Service]` section in /lib/systemd/system/telegraf.service

**Comment by powersj** [comment]
@shrx,

Thanks for looking into this. I think we should carry that by default and not require users to include it, but I am not 100% certain of the implications still. I have put up https://github.com/influxdata/telegraf/pull/14517 which would make the change.

**Comment by powersj** [comment]
@shrx - can I get you to try the artifacts in #14517 please and confirm it suppresses the messages?

**Comment by shrx** [comment]
> @shrx - can I get you to try the artifacts in #14517 please and confirm it suppresses the messages?

Sure, I'll be glad to test the fix.
