### ISSUE TITLE
Extend systemd_unit plugin to gather restart-count and other information

### ISSUE THREAD

**Issue by FlashSystems** [influxdata/telegraf#14521]
### Use Case

The `systemd_units` plugin is missing some information, that is essential for my use case:

- The restart count of the unit
- If the unit is enabled or not
- The preset-state of the unit

### Expected behavior

It would be great if more information about a systemd unit would be available. I'd suggest "restart count", "memory usage", enable-, preset-state and the last exit status of the main process.

### Actual behavior

I had a look at the implementation of the `systemd_units` plugin and noticed that it calls `systemctl list-units`. Using this interface has two drawbacks in my opinion:
- Its output is hard to parse because the output is meant for human consumption.
- Some vital information (like the restart count) is missing.

### Additional info

I'm far from fluent in Go, but I had a shot converting the `systemd_units` plugin from using `systemctl list-units` to `systemctl show`. This call is able to return much more information, supports the same filtering and returns the result as easy to parse name-value-pairs.
This works quite well. Before creating a PR to change the `systemd_units` plugin, I need some advice:
- Would the conversion from `systemctl list-units` to `systemctl show` be appreciated? It would allow gathering much more metrics about the systemd units.
- How should I implement new measurements like the restart count? Should I use a feature-flag in the config so that users upgrading experience no change in functionality, or should new values just be added?

Your advice is much appreciated.

**Comment by powersj** [comment]
Hi,

> Would the conversion from systemctl list-units to systemctl show be appreciated?

Seems like this was mentioned (I won't say discussed) in the [original PR](https://github.com/influxdata/telegraf/pull/4532#issuecomment-469325625), with the only comment that you would need to call out for every unit. The immediately consequence I can think of is that the current plugin can take wild-cards, how would that work with `systemctl show`, which needs a specific unit name?

Off hand, and don't hold me to this, but I would consider adding a new config option that takes a list of units to monitor. Those could use `systemctl show <unit>` directly. We would then have to discuss whether to create a new metric or not as well as if we should allow patterns or disable patterns when set.

> How should I implement new measurements like the restart count? Should I use a feature-flag in the config so that users upgrading experience no change in functionality, or should new values just be added?

This may depend on the above answers ;) If this is something that needs a flag to switch over to, then you are freer to break backwards compatibility and do what makes sense.

**Comment by FlashSystems** [comment]
Thank you @powersj, for the information about the original PR. I use `systemctl show --all '*'` for my [`checkunits` utitlity](https://github.com/FlashSystems/CheckUnits) since systemd 239 (Released in June 2018), and it has worked flawlessly ever since. Using `--all` is also the [workaround](https://github.com/systemd/systemd/issues/12273#issuecomment-482089316) mentioned in systemd [Bug 12273](https://github.com/systemd/systemd/issues/12273) that lead to some units not being shown.

I tried to find a virtual machine having an old systemd version to verify that it works. The oldest I could find was systemd 247 (released in November 2020). Using `--all` and a glob pattern shows all units (active or not), and the glob pattern works as expected.

I've tested the conversion from `systemd list-units` to `systemd show` on the current systemd release 255 and the output of the plugin is exactly the same.

I think there are three options to go forward with this:

## Convert the plugin to `systemd show`
According to my tests, this should be a drop-in replacement. But maybe there are some systemd versions out there that don't have the fix for bug 12273 and where the `--all` workaround does not work. There is a risk for regressions or behavior change.

## Make `systemd list-units` and `systemd show` switchable by an option
This is the option I dislike the most. It would make the code very cumbersome and hard to maintain. Essentially, there would be two plugins merged into one. The parsing and internal mapping of the values are very different between the `systemd list-units` and the `systemd show` variants.

## Create a second `systemd_unit2` plugin
I don't expect `systemd_unit` plugin to ever gain additional features because the output of `systemd list-units` is fixed and unlikely to change. This plugin should only require maintenance updates.
Having the new features (and the extensibility) put into a new plugin might be a good solution. If no regressions occur, the old plugin can be deprecated and removed eventually.

# Conclusion
I'd prefer the third option because the risk of regression is practically zero, and it's the easiest to maintain. This would also solve the problem of the new values because the new plugin would allow me to do "what makes sense" ;)

**Comment by powersj** [comment]
Thanks for digging into this and writing this up!

We would gladly take a PR for your second option. In doing so, you could extend/change the metrics that are generated without the need to maintain backwards compatibility. The option setting is essentially "opting-in" to a new metric format as well.

I would break out the two methods into different files and have the existing systemd_units.go's gather call the correct one depending on the config, while still defaulting to the existing systemd list-units.
