### ISSUE TITLE
HTTP Listener v2 - configuration options nice to have

### ISSUE THREAD

**Issue by ricdainf** [influxdata/telegraf#14529]
### Use Case

To be much more effective in integration with remote Common HTTP worker, API and webservice HTTP i am proposing some new features on HTTP Listener plugin for simple configuration customization.

1 - wildcard permit dynamic URL paths ;
2 - introduction some validation on input HTTP request on top on headers or body
3 - HTTP response code customizable

### Expected behavior

1 - wildcard permit dynamic URL paths ;
If an HTTP client send a request to HTTP Listener v2 plugin actually can process correctly the static ( http://{TELEGRAFHOST}/masterpath' ) but not dynamic ( http://{TELEGRAFHOST}/masterpath/{ID_CLIENT}/notification/{ID_NOTIFICATION}).

the proposal customization is the introduction of "*" or similar character to implement this in paths variable like
Example : 
paths = ["/masterpath/*/*/*"]

2 - introduction some validation on input HTTP request on top on headers or body
Example : 
http_headers_validation = ["HTTP_HEADER1" = "PARSE_VALIDATION_REGEX1","HTTP_HEADER2" = "PARSE_VALIDATION_REGEX2"]
http_body_validation = ["HTTP_BODY1" = "PARSE_BODY_VALIDATION_REGEX2","HTTP_BODY2" = "PARSE_BODY_VALIDATION_REGEX2"]

3 - HTTP response code customization parameter
If you permit the customization of http_response_code you can Integrate with HTTP client in better way (someone expect 100 or 200 code not only 204) 
Customize the message for negative response and introducing validation parse error response (like 400 as malformed request)

Example :
http_reponse_ok_code=200
http_response_nok_validation_code=400
http_response_nok_code=403

### Actual behavior

1 - wildcard permit dynamic URL paths ;
not present feature

2 - introduction some validation on input HTTP request on top on headers or body
not present feature

3 - HTTP response code 

Actually HTTP code are 204 if is ok and 404 if the paths are not respected / Not found

**Comment by powersj** [comment]
Hi,

While I can understand the use-case, if you need this level of customization to match a particular use-case I suggest pairing your own implementation with the execd plugin. That way you can customize your setup to match exactly what you need and can continue to pass metrics into Telegraf.
