### ISSUE TITLE
Add options to OPC UA listener plugin for handling a failed connection

### ISSUE THREAD

**Issue by annamooseity** [influxdata/telegraf#14533]
### Use Case

We have several sites with multiple OPC UA servers that may or may not be on at a given time. We would like the ability to for Telegraf to still collect information from other successfully initiated inputs even if it can't talk to the OPC UA server. Ideally, we'd have three options when Telegraf fails to start subscriptions:

1. Exit out of Telegraf (current behavior)
2. Ignore this plugin failure, and continue running all others
3. Continue running other plugins, and try to re-establish the connection every collection interval

### Expected behavior

The user has the option of continuing running Telegraf with all other plugins, even if a particular server is off.

### Actual behavior

Right now, Telegraf gives up as soon as it cannot connect to a OPC UA server. 

### Additional info

Adding error handling for inputs has been discussed a LOT in several tickets, like #11313 and #13834, plus some others I can't find right now. The verdict was to implement this type of error handling on a per-input basis. The Kafka consumer plugin does something similar.

**Comment by powersj** [comment]
Thanks for the issue and for putting up a PR! Will review hopefully this week.
