### ISSUE TITLE
Modbus plugin - possibility to insert different tags for each saved metric

### ISSUE THREAD

**Issue by AutomationTeam-ATeam** [influxdata/telegraf#14549]
### Use Case

Saving many variables and needing to insert tags with specific value for each variable, these tags would be useful to be able to filter later with queries.
In my case the tags I wanted to save with the metric are engineering unit and phase number

### Expected behavior

Insert each variable with its own tags in order to have greater flexibility in writing the metrics

Here is an example of what the configuration file might look like:
```
[[inputs.modbus.request]]
      slave_id = 1
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Phase to neutral Voltage, THD 1" , type =  "FLOAT32",omit = false, tags=[["unit", "%"], ["phase","1"]]},
      { address =224 , name = "Phase to Phase Voltage, RMSAmplitude 3" , type =  "FLOAT32", omit = false, tags=[["unit", "V"], ["phase","3"]] },
      { address =240 , name = "Phase Reactive Power (+/-) 1" , type =  "FLOAT32", omit = false , tags=[["unit", "var"], ["phase","2"]] },
      { address =250 , name = "Phase Apparent Power 3" , type =  "FLOAT32", omit = false , tags=[["unit", "VA"], ["phase","1"]] },
      ]
```

With this configuration the variables would be these:
```
EnergyMeter, unit=%,phase=1 Phase to neutral Voltage, THD 1="fieldValue" 1664466060000000000
EnergyMeter, unit=V,phase=2 Phase to Phase Voltage, RMSAmplitude 3="fieldValue" 1664466060000000000
EnergyMeter, unit=var,phase=3 Phase Reactive Power (+/-) 1="fieldValue" 1664466060000000000
EnergyMeter, unit=VA,phase=1 Phase Apparent Power 3="fieldValue" 1664466060000000000
```

### Actual behavior

Currently for each variable you need to create a group (I don't know if creating hundreds of groups affects performance, but it certainly increases the complexity of the configuration file)

```
 [[inputs.modbus.request]]
      slave_id = 1
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Phase to neutral Voltage, THD 1" ,type =  "FLOAT32", omit = false },
]

    [inputs.modbus.request.tags]
      unit= "%"
      phase= "1"

 [[inputs.modbus.request]]..... a request for each variable with different tags value
```

### Additional info

A plugin that already implements this function is the [opcua](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/inputs/opcua/README.md) plugin

**Comment by powersj** [comment]
Hi,

In principle I have no objection to this, I however am not the most up to speed on the modbus plugin.

Is this something you are interested in putting up a PR for? It looks like you would want to [extend the modbus request definition here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/modbus/configuration_request.go#L16-L25) to add a the tags as a `map[string]string`. This would be slightly different than your proposed structure of lists, and would look like:

```toml
tags={unit = "VA", phase="1"}
```

We would want to add tests for these of course and also ensure we add documentation that these tags would take the highest precedence over other defined tags.

**Comment by srebhan** [comment]
@AutomationTeam-ATeam please look at the `"metric" configuration style` section of the config. This was introduced to exactly do this! You define your metrics and let Telegraf group the required fields to come-up with the requests...
