### ISSUE TITLE
config file cannot be read for MySQL inputs

### ISSUE THREAD

**Issue by abhiyada** [influxdata/telegraf#1454]
Trying to configure MySQL input in telegraf.conf. Telegraf is already running on the host gathering server stats(CPU/Disk/Memory). Editing conf file under [[inputs.mysql]] results in the error when parsing conf file.

Telegraf.conf:
```
[[inputs.mysql]]
#   ## specify servers via a url matching:
<username>:<pwd>@tcp(127.0.0.1:3306)/dbname?tls=[true|false]
#   ##  see https://github.com/go-sql-driver/mysql#dsn-data-source-name
#   ##  e.g.
#   ##    db_user:passwd@tcp(127.0.0.1:3306)/?tls=false
#   ##    db_user@tcp(127.0.0.1:3306)/?tls=false
#   #
#   ## If no servers are specified, then localhost is used as the host.
servers = ["tcp(127.0.0.1:3306)/"]
#   ## the limits for metrics form perf_events_statements
   perf_events_statements_digest_text_limit  = 120
   perf_events_statements_limit              = 250
   perf_events_statements_time_limit         = 86400
#   #
#   ## if the list is empty, then metrics are gathered from all databasee tables
#   table_schema_databases                    = []
#   #
#   ## gather metrics from INFORMATION_SCHEMA.TABLES for databases provided above list
   gather_table_schema                       = true
```

## Directions

Upon saving the file and running 'telegraf -config telegraf.conf -test', returns error message:
Error parsing telegraf.conf, toml: line 886: parse error

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
Can you please cleanup this issue report?

**Comment by sparrc** [comment]
this line: `<username>:<pwd>@tcp(127.0.0.1:3306)/dbname?tls=[true|false]` should not be uncommented.
