### ISSUE TITLE
[inputs.win_perf_counters] skip PdhCstatusNoInstance error

### ISSUE THREAD

**Issue by hiroshi-iim** [influxdata/telegraf#14557]
### Use Case

I plan to collect processes metrics on Windows host using configuration like below.
```
[agent]
  round_interval = true
  precision = "5s"
  interval = "5s"

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true

[[inputs.win_perf_counters.object]]
  UseRawValues = true
  ObjectName = "Process"
  Instances = ["OUTLOOK*", "python*"]
  Counters = [
    "ID Process",
    "% Processor Time",
]    

[[outputs.file]]
  files = ["stdout"]
  data_format = "csv"
  csv_timestamp_format = "2006-01-02T15:04:05Z07:00"
```

I tested this configuration with the following steps.
1. Start outlook and run `python -c "while True: i=1"`.
2. Then start telegraf with above configuration.
3. Wait until telegraf outputs records for 1st interval.
4. Then Quit outlook.

### Expected behavior

Telegraf continues to output records of running processes (matching "python*" in this case).

### Actual behavior

Telegraf outputs error logs shown below and stops to output records until counters are refreshed.
```
E! [inputs.win_perf_counters] Error in plugin: error during collecting data on host "localhost": error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process": The specified instance of the performance object was not found.
```

### Additional info

I temporarily modified `isKnownCounterDataError` function to return true when errorcode is `PdhCstatusNoInstance` and ran same senario. In the case telegraf outputs warn logs shown below but continues to output records of python instance which has consistent value.
```
W! [inputs.win_perf_counters] Error while getting value for counter "\\\\{my computer name}\\Process(OUTLOOK)\\ID Process", instance: OUTLOOK, will skip metric: The specified instance of the performance object was not found.
```

Actually I have to set `Instances = ["*"]` in real case. In that case there are more chances to see `PdhCstatusNoInstance` error.

This is derived from https://github.com/influxdata/telegraf/issues/14486

**Comment by powersj** [comment]
@hiroshi-iim 

Thanks for filing the second issue.

My only open question is if we should make this change opt-in, via a config setting. I don't think there is any harm in adding this and users would only be getting additional data, not less.

I have put up https://github.com/influxdata/telegraf/pull/14570 which incorporates both PRs. Could you confirm it gets the data for you?

Thanks!

**Comment by hiroshi-iim** [comment]
Hi @powersj 

> I don't think there is any harm in adding this and users would only be getting additional data, not less.

I completely agree with you.

> I have put up https://github.com/influxdata/telegraf/pull/14570 which incorporates both PRs. Could you confirm it gets the data for you?

The new module works perfectly as expected.

Thanks!
