### ISSUE TITLE
Docs: how does CSV parser convert types when they're not explicit?

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/telegraf#14555]
The CSV parser config says:

```
...
 ## If this is not specified, type conversion will be done on the types above.
 csv_column_types = []
```

What does that mean?

I found the test for explicitly set types, but not for automatic conversion.

Related links:
https://github.com/influxdata/telegraf/blob/db8552a140e55d3003fe6f1d00283b2bb7d11bfa/plugins/parsers/csv/README.md?plain=1#L33

**Comment by powersj** [comment]
> What does that mean?

It is trying to say that the type, if not specified, will attempt to be set to one of the following types, in this order:

>  ## For assigning explicit data types to columns.
>  ## Supported types: "int", "float", "bool", "string".

Specifically, we try to convert the value to an int, if that fails a float, if that fails a bool, and if that fails keep it as a string. See [here in the code](https://github.com/influxdata/telegraf/blob/db8552a140e55d3003fe6f1d00283b2bb7d11bfa/plugins/parsers/csv/parser.go#L426-L435).

**Comment by jstirnaman** [comment]
Thanks. I'll add that to the README.
