### ISSUE TITLE
How do you test a new or mofied input plugin? 

### ISSUE THREAD

**Issue by AeonJJohnson** [influxdata/telegraf#14567]
### Please direct all support questsions to slack or the forums. Thank you.

I am testing modifications to a input.plugin (lustre2) that I will sub a PR for if it works as intended. I am not sure how to go about testing my mods. I have the modified .go files (lustre2.go and lustre2_test.go) and a functional golang env with GOPATH env variable set.

I cd to telegraf/plugins/input/lustre2 and run `go test -v .` and I get OK status for all functions but no resulting data output string. I want to verify I designated the proper fields and the data is output properly. I cannot figure out how to get the golang test process to actually output the data strings of tags and metrics resulting from the test. lustre2_test.go creates a test file tree with dummy value files for lustre2 to parse and process but I can't see any output that verifies that.

Hints? A helpul pointer on how to properly employ `go test` to test this thoroughly?

Many thanks!

**Comment by powersj** [comment]
Responded over on the forums! Thanks and looking forward to some updates to lustre2!

https://community.influxdata.com/t/how-do-you-test-a-modified-input-plugin-lustre2-in-go/32783
