### ISSUE TITLE
 [inputs.file] Error in plugin: could not find file(s):

### ISSUE THREAD

**Issue by constantin-baciu** [influxdata/telegraf#14571]
### Relevant telegraf.conf

```toml
[[inputs.file]]
  files = ["/opt/perf.log"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2024-01-12T15:17:45Z E! [inputs.file] Error in plugin: could not find file(s): /opt/perf.log
```

### System info

Amazon Linux 2

### Steps to reproduce

1. Grant read permissions to /opt to the telegraf user
2. Grant read permissions to /opt/perf.log to telegraf user
3. Restart telegraf
...

### Expected behavior

The expected behavior would be that the file is read and output is sent (to influxdb in this case).

### Actual behavior

The telegraf service cannot read the file

### Additional info

Here's how I check for permissions:

```
 getfacl /opt
getfacl: Removing leading '/' from absolute path names
# file: opt
# owner: root
# group: root
user::rwx
user:telegraf:r--
group::r-x
group:Telegraf:r--
mask::r-x
other::r-x


getfacl /opt/perf.log
getfacl: Removing leading '/' from absolute path names
# file: opt/perf.log
# owner: telegraf
# group: telegraf
user::rwx
user:telegraf:r--
group::r-x
mask::rwx
other::rwx
```

And the telegraf service is running as the telegraf user:
```
ps -ef | grep telegraf
telegraf  3764     1  0 14:59 ?        00:00:07 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
root     17741  5313  0 15:22 pts/0    00:00:00 grep --color=auto telegraf
```

Trying to use the inputs.tail plugin results in the file not being read but no messages show up in the log.

**Comment by powersj** [comment]
Hi,

> Grant read permissions to /opt to the telegraf user
>  getfacl /opt
> user:telegraf:r--
> group:Telegraf:r--

While `/opt` has read privileges for telegraf, to traverse a directory you also need execute bits set.

**Comment by constantin-baciu** [comment]
Oh, wow... that was easy!

Thanks!

And, sorry I've opened up a bug for this.
