### ISSUE TITLE
kafka_consumer should call markmessage on messages that failed parsing

### ISSUE THREAD

**Issue by jkerfs** [influxdata/telegraf#14579]
### Use Case

I have a kafka topic that unfortunately has a mixture of json and avro messages!  I know this is very bad practice; I'm the consumer of the topic not the publisher, so I have to handle it.  I have configured telegraf to just consume the avro messages (these are the only ones that I care about).

Sometimes there are long stretches of json messages, and these will then fail the parsing since they are not valid binary avro messages.  I would like for these messages that failed parsing to be marked as processed so the offset of the partition can be updated even when there are no valid parseable message for a long span.

### Expected behavior

When a kafka message fails parsing, the message is still marked and can then be used to commit the consumer group's offset on the partition.

### Actual behavior

When a kafka message fails parsing, the message is ignored and will not be used as the offset to commit.

### Additional info

This diff would solve the problem, I believe:
```diff
	metrics, err := h.parser.Parse(msg.Value)
	if err != nil {
+ 		session.MarkMessage(msg, "")
		h.release()
		return err
	}
```

Although I think it may be preferable to include `session.MarkMessage` in the `h.release()` method so that we can ensure that the handling of messages that exceed max length and messages that fail parsing are released and marked identically. 

Happy to put up a PR if this would be an acceptable behavior change.

**Comment by powersj** [comment]
Hi,

> Happy to put up a PR if this would be an acceptable behavior change.

I was a little surprised we did not already do this. Please do put up a PR, thanks!
