### ISSUE TITLE
Protobuf input support for Prometheus input plugin

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/telegraf#1458]
### Proposal:

Support protobuf input for the [Prometheus](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) input plugin.

**Comment by sparrc** [comment]
for reference, the bug is here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L133, we are not actually parsing the http headers there is just an empty map being created. This was likely a placeholder that got overlooked.
