### ISSUE TITLE
telegraf collect strange but regular wrong data

### ISSUE THREAD

**Issue by lnkisi** [influxdata/telegraf#1459]
Hello, I use telegraf to collect some system metrics. But its works sometimes can't be trusted. I found the unexpected performance data yesterday. But I checked my server. It works normally. 

![2016-07-07 10 59 46 am](https://cloud.githubusercontent.com/assets/6847879/16641359/655e38aa-4432-11e6-9d17-64290eb36583.png)

**Comment by sparrc** [comment]
Can you provide more evidence and specific information?
