### ISSUE TITLE
why does procstat plugin store PID as a tag?

### ISSUE THREAD

**Issue by beckettsean** [influxdata/telegraf#1460]
Seems like the process ID should be a field not a tag, in order to reduce series cardinality. I'm not sure I see a compelling use case for `GROUP BY pid`, given that over time each process name could generate over 32000 series. If `pid` was a field it would still be possible to search for a specific PID, although regex doesn't work on fields.

**Comment by sparrc** [comment]
I agree this should probably be a field, cc @daviesalex @sebito91

**Comment by daviesalex** [comment]
I think this is basically the same issue as https://github.com/influxdata/telegraf/issues/1451 albeit with a different proposed fix.

We do need to fix this, for sure. Moving to a field is one thing, but searching on tags is convenient - but if you only do this for processes. I'll add this comment to that issue

**Comment by daviesalex** [comment]
Also, boring fact that turned out to be relevant for us when we moved to RHEL, pid_max can be set to PID_MAX_LIMIT which is 2^22 in modern kernels by default. The default is now 32768; it was lower in older kernels.

**Comment by aderumier** [comment]
Hi,I'm also hitting this bug, I have around 150000 uniques values in pid tag (and around 2000 hosts in host tag).
I think this is why my influxdb take 1h to start .

**Comment by adrianlzt** [comment]
I have found that have the cardinality problem because of this.
Is there any way to "clean" the pid as a tag?
I see that "pid" is listed as a tag and as a value.

**Comment by sparrc** [comment]
in release 1.2 you will be able to drop the pid using a config option in the plugin
