### ISSUE TITLE
[KNX Input Plugin] Add Datapoint Type 14.1200

### ISSUE THREAD

**Issue by userwithoutpassword** [influxdata/telegraf#14617]
### Use Case

Im trying to use Datapoint Typ 14.1200 but the plugin doesnt support it.
basically its the same as 14.076 the ony difference is it has another unit.
14.076 has "m³"
14.1200 has "m³/h"

Thats the only difference.
Is there a way to add this Datapoint?

### Expected behavior

..

### Actual behavior

Doesnt start

**Comment by srebhan** [comment]
@userwithoutpassword the datapoint has to be added to [the underlying library](https://github.com/vapourismo/knx-go/blob/master/knx/dpt/types_14.go) and then we can bump the dependency...

**Comment by userwithoutpassword** [comment]
can i do this on my own?

**Comment by srebhan** [comment]
@userwithoutpassword sure, if you know git and Golang a bit and do have a Github account that should be no problem. You should fork the [upstream repository](https://github.com/vapourismo/knx-go) and [create a pull-request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) there.

As soon as your PR is merged there, we can update the dependency in Telegraf to use the new upstream version. Let me know once you are at that point and I can guide you through the Telegraf part!

**Comment by userwithoutpassword** [comment]
okay thanks. I did a pull request. Now we have to wait

**Comment by userwithoutpassword** [comment]
> @userwithoutpassword sure, if you know git and Golang a bit and do have a Github account that should be no problem. You should fork the [upstream repository](https://github.com/vapourismo/knx-go) and [create a pull-request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) there.
> 
> As soon as your PR is merged there, we can update the dependency in Telegraf to use the new upstream version. Let me know once you are at that point and I can guide you through the Telegraf part!

Hey. Now it has been merged.

regards

**Comment by powersj** [comment]
@userwithoutpassword,

Thanks for letting us know! I have put up https://github.com/influxdata/telegraf/pull/14636 which will have artifacts in 20-30mins. Can you please download artifacts from that PR and verify it resolves your original issue?

Thanks!

**Comment by userwithoutpassword** [comment]
My first try failed. I'm getting

`2024-01-29T19:24:19Z I! Loading config: http://192.168.1.114:8086/api/v2/telegrafs/0c72005f1f9de000
2024-01-29T19:24:19Z I! Starting Telegraf 1.30.0-3c4f7593 brought to you by InfluxData the makers of InfluxDB
2024-01-29T19:24:19Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 61 outputs, 6 secret-stores
2024-01-29T19:24:19Z I! Loaded inputs: knx_listener
2024-01-29T19:24:19Z I! Loaded aggregators: 
2024-01-29T19:24:19Z I! Loaded processors: 
2024-01-29T19:24:19Z I! Loaded secretstores: 
2024-01-29T19:24:19Z I! Loaded outputs: influxdb_v2
2024-01-29T19:24:19Z I! Tags enabled: host=influxdbTEST
2024-01-29T19:24:19Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"influxdbTEST", Flush Interval:10s
2024-01-29T19:24:19Z E! [telegraf] Error running agent: starting input inputs.knx_listener: cannot create datapoint-type "14.1200" for address "2/6/20"`

**Comment by srebhan** [comment]
@userwithoutpassword did take a quick look and it seems like the upstream library is broken with all DPTs that don't follow the `DPT_[xx]x.yyy` pattern with **three** digits after the dot. Unfortunately you do have **four** digits after the dot and [this code](https://github.com/vapourismo/knx-go/blob/4375cb048e09cce3b56a4b73faec2779d7174319/knx/dpt/types_registry.go#L225) then mangles the `DPT_141200` into `141.200` instead of `14.1200`. :-( You probably should fix this there by having a special 4-digits-minor registration...

**Comment by userwithoutpassword** [comment]
Yes thats right. DPT_141200 gets transformed into 141.200.
At the moment this datapoint is the only one with 4 instead of 3 digits after the dot and 141.200 is not currently in use and not defined by the KNX Association. So I just added one line to replace 141.200 with 14.1200.

Problem is the naming of the DPT variables.  Because of format like DPT_121200 u dont know if its 12.1200 oder 121.200.
A better way of name is DPT_12_1200

**Comment by srebhan** [comment]
@userwithoutpassword can you please test the binary in PR #14918 available as-soon-as CI finished the tests successfully!?!

Upstream fixed the registry so this should work now with DPT14.1200. Let me know if this fixes the issue!

**Comment by userwithoutpassword** [comment]
> @userwithoutpassword can you please test the binary in PR #14918 available as-soon-as CI finished the tests successfully!?!
> 
> Upstream fixed the registry so this should work now with DPT14.1200. Let me know if this fixes the issue!

sure i ll do, maybe later today/night or tomorrow.

**Comment by userwithoutpassword** [comment]
> @userwithoutpassword can you please test the binary in PR #14918 available as-soon-as CI finished the tests successfully!?!
> 
> Upstream fixed the registry so this should work now with DPT14.1200. Let me know if this fixes the issue!

Yes its working!
