### ISSUE TITLE
redis plugin returns data for first server only

### ISSUE THREAD

**Issue by rubycut** [influxdata/telegraf#1462]
### Relevant telegraf.conf:

[[inputs.redis]] 
  servers = [ "localhost:6379","localhost:6091","localhost:6022","localhost:6052","localhost:6102","localhost:6382","localhost:6031","localhost:6381","localhost:6042","localhost:6061","localhost:6011","localhost:6012","localhost:6021","localhost:6082","localhost:6081","localhost:6072","localhost:6041","localhost:6092","localhost:6071","localhost:6062","localhost:6101","localhost:6380","localhost:6051","localhost:6032"
  ]
### System info:

telegraf 0.13-1
### Steps to reproduce:
1. run above config.
### Expected behavior:

Should return results for all ports.
### Actual behavior:

Returns results only for port 6379

**Comment by rubycut** [comment]
```
[[inputs.redis]]
  servers = [ "localhost:6091" ]
[[inputs.redis]]
  servers = [ "localhost:6022" ]
[[inputs.redis]]
  servers = [ "localhost:6052" ]
```

This also doesn't work.

**Comment by sparrc** [comment]
that's strange, are you getting any errors in the logs? does it work with two servers?

**Comment by rubycut** [comment]
Nope, 2 or 100, always sends output for first specified server.

There is no errors in the log.

**Comment by sparrc** [comment]
could you provide your full config and any other system information? I'm not able to reproduce your issue so far.

Also, can you manually use telnet to connect and list INFO on your that are not working? like this:

```
tars :: src/github.com/influxdata/telegraf ‹master› % telnet localhost 7380
Trying ::1...
Connected to localhost.
Escape character is '^]'.
INFO
$2094
# Server
redis_version:3.2.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ed627d97d5dc311e
redis_mode:standalone
...
```

you should get a list of all available metrics.

**Comment by sparrc** [comment]
I've pushed a change to log redis errors better, which will be available in 1.0.0-beta3

**Comment by danielnelson** [comment]
@rubycut Is this still an issue?

**Comment by rubycut** [comment]
@danielnelson I don't know, we are not using official telegraf plugin, we are using our own external plugin. It should be trivial to test, just start two local instances of redis from command line and try fetching data.

**Comment by danielnelson** [comment]
Thanks for the update, based on my testing this appears to have been fixed.
