### ISSUE TITLE
Reference a IP address list in a text file instead of within the telegraf.conf

### ISSUE THREAD

**Issue by G0nz0uk** [influxdata/telegraf#14630]
### Use Case

Hello,

Is it possible to point to a IP list file instead of putting all the IP addresses to poll into the various telegraf.conf files?

For example currently it's like this on our Linux server:
agents = [ "10.116.1.100:161","10.116.1.101:161","10.116.1.102:161" ]

Can we use something like this instead:

agents = /etc/telegraf/telegraf.d/ipaddresses.txt

Thanks

### Expected behavior

To be able to refer to an IP list of IP addresses would be great

### Actual behavior

It can't be done at the moment hence the feature request.  It looks like others want this too from what I have read on the Telegraf Slack channel and Influx forums, but no one has bothered to let you guys know.

### Additional info

We have a database that houses many IP addresses for certain devices that are always changing, if can export to csv (maybe txt), so we would like to export this to a location for Telegraf to pick up so we never have to keep editing the numerous telegraf.conf files.  Telegraf will just see the new file of IP address to poll.

Thanks

**Comment by powersj** [comment]
Hi,

We have had requests in the past to enable the telegraf config to read from additional files. This is not something we wish to add to Telegraf. Instead, we ask that you use a configuration management tool to produce your config from whatever sources you need.

Thanks
