### ISSUE TITLE
Allow monitoring of NFS drives on Windows like on Linux

### ISSUE THREAD

**Issue by Space2Man** [influxdata/telegraf#14647]
### Use Case

We are using telegraf to monitor disk / drive utilisation on Windows. We have mounted an NFS share on Windows from a storage appliance and would like to monitor it's utilisation to avoid running out of space.

Telegraf is running as a dedicated user and that user has the NFS share mounted as drive Y. But it does not show up, telegraf only detects the local drives.

On Linux mounted NFS share are checked and metrics are sent as well.

### Expected behavior

Show utilisation of mounted NFS share on Windows as well.

### Actual behavior

Utilisation of mounted NFS share is only available on Linux.

**Comment by Space2Man** [comment]
If I check the drives with PowerShell via `Get-CimInstance -ClassName Win32_LogicalDisk` then the NFS drive is listed with a drive type 4 and size and freespace are listed as well.

**Comment by powersj** [comment]
Hi,

You didn't mention which plugin you are using ;) I assume you are using the `inputs.disk` plugin?

That plugin uses [gopsutil](https://github.com/shirou/gopsutil/) to collect data about disks. I'm not sure what the library does off hand, but it would be good to file an upstream issue about supporting NFS mounts if you do not see it from Telegraf.

**Comment by Space2Man** [comment]
Ah, sorry, that was the `inputs.disk` plugin. I had found that library also and yes, it makes sense to check with them as well.

**Comment by Space2Man** [comment]
Issue can be closed. It's a permissions thing. It seems like the "local system account" does not see the drive. I always checked as the user I am and saw that Get-CimInstance found the infos. So now I tested to run telegraf from cmdline and not as service and there I see the utilisation of the NFS mount ... so I need to let telegraf run as specific user.
