### ISSUE TITLE
Missing temperature sensor should not generate a warning

### ISSUE THREAD

**Issue by danepowell** [influxdata/telegraf#14645]
### Use Case

On many (probably most) systems, there's at least one temperature sensor with no data (see https://github.com/influxdata/telegraf/issues/5692 ), and this is completely normal and expected.

### Expected behavior

The missing temperature is logged only as a debug message, given that this is normal and expected behavior. The [developer guidelines](https://github.com/influxdata/telegraf/blob/master/docs/developers/LOGGING.md#when-not-to-log) say:

> Don't log a warning every time a plugin is called for situations that are normal on some systems.

### Actual behavior

The missing temperature is logged as a warning, leading to logs full of this warning and decreasing the visibility of more serious warnings:

> [inputs.temp] Couldn't read temperature from "/sys/class/hwmon/hwmon2/temp1_input": read /sys/class/hwmon/hwmon2/temp1_input: no data available

**Comment by powersj** [comment]
Hi,

Willing to put up a PR?

At first I was a little hesitant to make this change given the history. I think the temp plugin pre-dates the dev guidelines ;) However, after thinking about it, it makes a lot of sense to either print them once, or change them to debug.

**Comment by danepowell** [comment]
Happy to post a PR, thanks. Just wanted to make sure it would be accepted.
