### ISSUE TITLE
Return service parameter to configuration of Nebius Cloud Monitoring

### ISSUE THREAD

**Issue by abrekhov** [influxdata/telegraf#14657]
### Use Case

Internal Nebius Dev Team asked to put "service" parameter back to configuration so they can use it instead of "custom" value to route metrics from managed services on there VM's.

### Expected behavior

Service parameter can be any value which corresponds to cloud service or custom (if it is cloud user's metrics).

### Actual behavior

Now the value is custom by default and cannot be changed.

**Comment by powersj** [comment]
next steps: review pr
