### ISSUE TITLE
SNMP failure with gosmi

### ISSUE THREAD

**Issue by llamafilm** [influxdata/telegraf#14668]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
  path = ["./mibs_debug"]
  agents = ["10.91.77.31"]
  version = 2
  community = "public"
  
  [[inputs.snmp.field]]
    oid = 'DOLBY-CP850-MIB::cp850FaderLevel.0'
    conversion = 'float'
```

### Logs from Telegraf

```text
$ telegraf --config telegraf_debug.conf --test --debug
2024-02-01T18:56:12Z I! Loading config: telegraf_debug.conf
2024-02-01T18:56:12Z I! Starting Telegraf 1.29.2 brought to you by InfluxData the makers of InfluxDB
2024-02-01T18:56:12Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
2024-02-01T18:56:12Z I! Loaded inputs: snmp
2024-02-01T18:56:12Z I! Loaded aggregators: 
2024-02-01T18:56:12Z I! Loaded processors: 
2024-02-01T18:56:12Z I! Loaded secretstores: 
2024-02-01T18:56:12Z W! Outputs are not used in testing mode!
2024-02-01T18:56:12Z I! Tags enabled: 
2024-02-01T18:56:12Z D! [agent] Initializing plugins
2024-02-01T18:56:12Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field : translating: cannot make DOLBY-CP850-MIB::cp850FaderLevel.0 numeric, please ensure all imported mibs are in the path
```

### System info

Telegraf 1.29.2, Ubuntu 22.04

### Steps to reproduce

Run telegraf with `snmp_translator='gosmi'`

### Expected behavior

With `netsnmp` translator, the output is like this:
```
> snmp,source=10.91.77.31 cp850FaderLevel.0=70 1706813228000000000
```

### Actual behavior

Error shown above

### Additional info

Here is the folder of MIBs I'm using.
[mibs.tgz](https://github.com/influxdata/telegraf/files/14129580/mibs.tgz)

snmptranslate works
```
$ snmptranslate -M ./mibs_debug/ -m DOLBY-CP850-MIB 1.3.6.1.4.1.6729.2.1.1.1.3.2.1.0
DOLBY-CP850-MIB::cp850FaderLevel.0
```

**Comment by powersj** [comment]
> please ensure all imported mibs are in the path

My limited understanding of the snmp plugin is the different translators have different path traversals. When you switched to gosmi, you may need to specify the direct MIB, just like you do with snmptranslate.

So look at updating the `path = ["/usr/share/snmp/mibs"]` parameter and that should work.

**Comment by llamafilm** [comment]
I tried `path = ["./mibs_debug/DOLBY-CP850.mib"]` and it still has the same issue.
And the [documentation](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/README.md) says to use a folder, not a specific MIB file:
```
  ## Path to mib files
  ## Used by the gosmi translator.
  ## To add paths when translating with netsnmp, use the MIBDIRS environment variable
  # path = ["/usr/share/snmp/mibs"]```

**Comment by powersj** [comment]
@Hipska what are we missing?

**Comment by llamafilm** [comment]
I think I was using the wrong syntax for `snmptranslate` before; that part is working now so I updated the post.

**Comment by llamafilm** [comment]
Yes it works fine if I specify the numeric OID like that.

**Comment by llamafilm** [comment]
Why is this closed? Isn't is supposed to work with textual names?

**Comment by powersj** [comment]
> Why is this closed? Isn't is supposed to work with textual names?

This and your other request came across as a call for support/questions. I was hoping @Hipska would guide you to a config, but I'll reopen this and we can look.
