### ISSUE TITLE
Redfish and Telegraf secrets

### ISSUE THREAD

**Issue by Nikoos** [influxdata/telegraf#14682]
### Use Case

Hello team,

I will need to connect Supermicro IPMI with builtin Redfish compliant API to Telegraf in order to query power consumption, as for now, clear text login and passwords are only supported in the redfish plugin, adding support to telegraf secrets will add more security to this input plugin.

Regards,

Nikos

### Expected behavior

Redfish input plugin should add support for the following configuration to enhance security : 

```
[[inputs.redfish]]
  ## Redfish API Base URL.
  address = "https://ipmi-ipmi-xxxxxxxxxxxxxx"

  ## Credentials for the Redfish API.
  username = "@{telegraf:ipmi_username}"
  password = "@{telegraf:ipmi_password}"
```

### Actual behavior

When using telegraf secrets, the following behavior can be seen in the log file : 

```
E! [inputs.redfish] Error in plugin: received status code 401 (Unauthorized) for address https://ipmi-xxxxxxxxxxxxxx, expected 200
```

### Additional info

Tested with the latest telegraf version available at the moment : 1.29.4 (git: HEAD@4441c4ed)

Regards,

Nikos

**Comment by powersj** [comment]
Thanks for the feature request.

@DStrand1 might be another good, short one for you!

**Comment by powersj** [comment]
@Nikoos - we've merged #14702 - it would still be good if you could download one of the artifacts from that PR and verify it works as expected. Thanks!

**Comment by Nikoos** [comment]
@powersj , sure will test in 5 minutes

**Comment by Nikoos** [comment]
Thanks for your quick add, it works perfectly.

Regards,

Nikos
