### ISSUE TITLE
Telegraf APCUPSD plugin "status":   status.Status should be a FIELD and not a TAG

### ISSUE THREAD

**Issue by KonVei82** [influxdata/telegraf#14700]
### Use Case

I have no idea why this one is a TAG and not a FIELD, since it can have multiple states that change (calibration, trim, boost, online, onbatt, overload, battlow, replacebatt).

In order to not break backwards compatibility it can remain as a TAG and be added as a FIELD as well.  

### Expected behavior

fields := map[string]interface{}{
                                "status":    status.Status,

### Actual behavior

			tags := map[string]string{
				"status":   status.Status,

**Comment by powersj** [comment]
> I have no idea why this one is a TAG and not a FIELD

Like other tags, they are usually strings and something you would want to filter/sort/index off on.

If you do not want it as a tag, then use the converter processor to change it.
