### ISSUE TITLE
starlark global state - save into statefile?

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#14704]
### Use Case

The starlark processor offers a global dict variable `state` which can be used to transfer data from one call of `apply()` to the next. Would it be possible to save the contents of `state` to the statefile?

The variable is useful for relating multiple metrics to each other. Saving it into the statefile would enable users to do so across restarts of telegraf.

### Expected behavior

starlark `state` variable is saved into the global statefile

### Actual behavior

currently `state` is not saved into the statefile.

**Comment by powersj** [comment]
next steps: Look at creating the `SetState` and `GetState` methods (see plugin.go) for the starlark processor.

**Comment by powersj** [comment]
@knollet I've put up #15038 which extends the starlark processor to save and get state. Would it be possible to have you test out the artifacts in that PR to confirm it is working?

Thanks!

**Comment by LarsStegman** [comment]
@powersj would it make sense to have the aggregator store its state as well? I don't even know if aggregators can store their state, to be honest.

**Comment by powersj** [comment]
I forgot to go back and look at the aggregators, but it does look like the starlark aggregator can make use of the state variable. I've tried it real quick with the example aggregator script and updated the PR.

**Comment by knollet** [comment]
will do.

**Comment by powersj** [comment]
Hey folks,

Any updates on testing?

**Comment by knollet** [comment]
I'm sorry, I haven't gotten around to it yet. I will try to give it a try today.

**Comment by knollet** [comment]
Hi,

It seems it doesn't do anything.
If I see correctly, the state variable has to be "declared" before using it. As there are no "global" or "nonlocal" keywords in starlark, I can't use `state` in `apply()` and have it reference an outer scope at all if I didn't define it prior.

My code it this:

```
source = '''

state = { "counter": 0 }     ## "declaration of state"

def apply(metric):
    state["counter"] += 1
    state["metric"] = metric
    metric.fields["cntr"] = state["counter"]
    return metric
'''
```

If this declaration statement (`state = { "counter": 0 }`) is executed after fetching the state back from the statefile, the statefile-saved state is overwritten by that and it doesn't do anything at all.

Also:
Looking at the statefile I couldn't find an entry in which the infos were stored at all (all entries were `{}`), so the above might not be the problem.

**Comment by knollet** [comment]
My complete config is this, you just have to add an output and you can test this

```
## test of https://github.com/influxdata/telegraf/pull/15038
## is the starlark state saved now and does it work?

## tests
## - [ ] does the state work?
## - [ ] can I save a metric object?
## - [ ] what does happen with a tracking metric (how to test-produce one?)

#########
# Input #
#########

[[inputs.mock]]
interval = "10s"
metric_name = "neverending_counter"
[[inputs.mock.constant]]
name = "cntr"
value = 0

#######################
# starlark processing #
#######################

[[processors.starlark]]
namepass = ["neverending_counter"]
source = '''

state = { "counter": 0 }

def apply(metric):
    state["counter"] += 1
    state["metric"] = metric
    metric.fields["cntr"] = state["counter"]
    return metric
'''
```

**Comment by powersj** [comment]
Thanks for giving it a try, and now I realize I was seeing the same thing :\ We will take a look into this a bit more as it doesn't seem to be a straightforward way to expose the global variables from each starlark instance. The globals var doesn't keep it for each instance from what I saw. Need to dig into this a bit more to see what I've missed.

**Comment by srebhan** [comment]
@knollet please test the binary in PR #15170, available as soon as CI finished the tests, and let me know if this fixes the issue! Note: You should **not** declare the state explicitly but rely on the implicit declaration. Your [example above](https://github.com/influxdata/telegraf/issues/14704#issuecomment-2034521603) should then read

```toml
[[processors.starlark]]
namepass = ["neverending_counter"]
source = '''
def apply(metric):
    state["counter"] = state.get("counter", 0) + 1
    state["metric"] = metric
    metric.fields["cntr"] = state["counter"]
    return metric
'''
```

**Comment by knollet** [comment]
Ok, well, ...

I use this config (yes, I anonymized it first, and it's the same with the anonymized version!)

```
#########
# Input #
#########

[[inputs.mock]]
interval = "10s"
metric_name = "neverending_counter"
[[inputs.mock.constant]]
name = "cntr"
value = 0

#######################
# starlark processing #
#######################

[[processors.starlark]]
namepass = ["neverending_counter"]
source = '''

# state = { "counter": 0 }

def apply(metric):
    state["counter"] = state.get("counter",0) + 1
    # state["metric"] = metric
    metric.fields["cntr"] = state["counter"]
    return metric
'''


##########
# output #
##########

[[outputs.influxdb]]
  alias = "neverending counter"
  urls = ["https://thisisaninflux:8086"]
  database = "thedatabase"
  username = "theusername"
  password = "thepassword"
  retention_policy = ""
  skip_database_creation = true
  write_consistency = "any"
  timeout = "5s"
  user_agent = "telegraf ${HOSTNAME}"
  content_encoding = "gzip"
  namepass = ["neverending_counter"]
```

And I get this
```
[telegraf@myhostname ~]$ telegraf
2024-04-18T14:25:24Z I! Loading config: /etc/telegraf/telegraf.conf
2024-04-18T14:25:24Z I! Loading config: /etc/telegraf/telegraf.d/silent_death.conf
[telegraf@myhostname ~]$ echo $?
1
```

Telegraf just silently dies, no panic, no stacktrace, nothing.

**Comment by knollet** [comment]
Ok. Seems to work now.

But I think I know why it died silently: For some reason my already existing statefile wasn't readable for telegraf. For some reason that didn't stop telegraf to run with an `[[inputs.tail]]` which also should have tried to use the defunct statefile, but with a starlark processor it silently dies.
I just deleted those files and voila, it worked.

I see that you did a marshall of the state in a binary format. Just from that, I hope this doesn't introduce a security problem where one could instanciate some object into telegraf doing something nasty (for example if somebody saves functions to the state and calls them later).
As a workaround I would marshall using json and spec that `state` may only be used for jsonable data (but that would maybe break existing code, idk).

**Comment by srebhan** [comment]
> As a workaround I would marshall using json and spec that state may only be used for jsonable data (but that would maybe break existing code, idk).

This won't work as JSON does not know anything about **integers** so if your state has an integer is will be a float the next time you start... :-( I don't think it is possible to do nasty things as we do decode this to a `map[string]interface{}` and the golang gob decode should be pretty solid...

**Comment by srebhan** [comment]
> Also, prior to this change, I believe you had to declare state globally, as I said above, and now you don't, so perhaps there could be an deprecation warning if one does, but idk how one would go about that. Perhaps check for object identity (of the state dict) before and after the initialization (parsing) of source.

Both works, but for state-persistence you should not declare the `state` as it would otherwise overwrite the persisted state so the change is backward compatible...
