### ISSUE TITLE
feat(outputs.http): Support secret store for Authorization header

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#14701]
### Use Case

I want to livestream data to Grafana but a custom Authorization header is needed for that. 

### Expected behavior

There are two ways this could be implemented:
1. Create a custom property `AuthorizationHeader config.Secret`
2. Change the type of Headers to `map[string]config.Secret`

I think the second option is preferable, because then any header can be a secret. What do you think?

### Actual behavior

Not supported.

**Comment by powersj** [comment]
Hi,

Are you willing to put up a PR?

> Change the type of Headers to map[string]config.Secret

We need to verify if this even works or needs to be a pointer to the secrets.

> Create a custom property AuthorizationHeader config.Secret

This would be a fine fallback option.

**Comment by LarsStegman** [comment]
Yes, I am willing to do that! I will put some time into it this week.
