### ISSUE TITLE
[inputs.modbus] input datatypes STRING8L, STRING8H

### ISSUE THREAD

**Issue by agiilit-admin** [influxdata/telegraf#14748]
### Use Case

Some manufacturers seem to store ascii string characters in LSB of a modbus 16bit register, while MSB of each register is not used. It would be helpful if a string type STRING8L could be used when configuring modbus input plugin for such devices. A STRING8H type would be similar, but MSB and LSB swapped.

In configuration files, STRING8L and STRING8H could be used as input types just as STRING type. Example:
```
fields = [
  ...
  { address=9, name="firmware", type="STRING8L", length=16 },
]
```

In current modbus input plugin implementation, type conversion for STRING type involves copying MSB and MSB to output buffer:
```
for i := 0; i < len(b); i += 2 {
        v := tohost(b[i : i+2])
        buf.WriteByte(byte(v >> 8))
        buf.WriteByte(byte(v & 0xFF))
}
```
For STRING8L and STRING8H copying MSB or LSB to `buf` would be simply omitted. Length configuration attribute will continue to refer to memory chunk length in modbus registers (number of 16bit words). Endianness handling would not change in any way.

### Expected behavior

With STRING8L support a test like this would pass:

```
{
        name:       "register130_string8L",
        address:    130,
        dataTypeIn: "STRING8L",
        length:     14,
        write:      []byte{0x00, 0x4d, 0x00, 0x6f, 0x00, 0x64, 0x00, 0x62, 0x00, 0x75, 0x00, 0x73, 0x00, 0x20,
                           0x00, 0x53, 0x00, 0x74, 0x00, 0x72, 0x00, 0x69, 0x00, 0x6e, 0x00, 0x67, 0x00, 0x00},
        read:       "Modbus String",
},
```

STRING8H support:
```
{
        name:       "register150_string8H",
        address:    150,
        dataTypeIn: "STRING8H",
        length:     14,
        write:      []byte{0x4d, 0x00, 0x6f, 0x00, 0x64, 0x00, 0x62, 0x00, 0x75, 0x00, 0x73, 0x00, 0x20, 0x00,
                           0x53, 0x00, 0x74, 0x00, 0x72, 0x00, 0x69, 0x00, 0x6e, 0x00, 0x67, 0x00, 0x00, 0x00},
        read:       "Modbus String",
},
```

### Actual behavior

Apparently, without STRING8L, STRING8H support, the above tests fail.

### Additional info

Seems to be trivial to implement so that the tests pass. Have not tested the modifications in a real-world deployment, though.

**Comment by agiilit-admin** [comment]
Perhaps names STRINGL, STRINGH would be more logical.

**Comment by srebhan** [comment]
@agiilit-admin would you consider this a "workaround" instead of a real feature? Asking because this seems just odd and a waste of bytes... ;-)

**Comment by agiilit-admin** [comment]
Workaround or real feature, ascii characters in LSB is the way Carlo Gavazzi EM340 energy meter serial numbers are encoded. This is one workaround for processing them:
```
# Remove zero bytes from strings
[[processors.starlark]]
  order = 10
  source = """
def apply(metric):
    for k, v in metric.fields.items():
        if type(v) == 'string':
            metric.fields[k] = ''.join([c for c in metric.fields[k].elems() if ord(c)!=0])

    return metric
"""
```

which is a bit kludgy because one could argue that according to the documentation the string should not contain zero bytes in the first place. The current documentation is somewhat ambigous:

-  Please note, if the byte-sequence contains a `null` byte, the string is truncated at this position.

The current telegraf modbus plugin implementation truncates the string at the last `null` byte.

**Comment by srebhan** [comment]
@agiilit-admin can you please try the binary in #14764 available as soon as CI finishes all tests!?! This PR adds a workaround so you should use
```toml
[[inputs.modbus]]
  ...
  fields = [
    ...
    { address=9, name="firmware", type="STRING", length=16 },
    ...
  ]
  
  [inputs.modbus.workarounds] 
    string_register_location = "lower"
```

to use the lower byte **after** byte-order conversion. Similar for the _upper_ byte.

Let me know if this allows fixing the issue!

**Comment by agiilit-admin** [comment]
Thanks! However, currently unable to test the solution since all my modbus devices are on a remote Raspberry PI OS (Debian 11), and there are problems compiling branch modbus_issue_14748 on said RPi with go1.22:
```
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:31:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
make: *** [Makefile:112: build_tools] Error 1
```
Any possibility of a linux_arm64.tar.gz PR artifact?

**Comment by agiilit-admin** [comment]
Missed the additional PR build artifacts link, sorry. Anyway, the workaround a) works b) solves the LSB string problem with the energy meter. Thanks again!

**Comment by srebhan** [comment]
@agiilit-admin thanks for testing. Next time when you compile, you should disable CGO, just as a hint.
