### ISSUE TITLE
Domain name appender for Windows

### ISSUE THREAD

**Issue by wp-perc** [influxdata/telegraf#14783]
### Use Case

I want host tag of metrics from my host to be the same value as the host FQDN and, if possible, lowercased. It has to be done automatically, without manually changing the hostname property every time for each and every host.

### Expected behavior

Telegraf must be able to understand the FQDN of the current Windows server is running on, similarly to Linux. Also, FQDN should be lowercased, to avoid issues with case-sensitive queries and comparisons.

### Actual behavior

Telegraf uses %COMPUTERNAME% as default value for hostname

### Additional info

Real FQDN can be obtained in different ways:
- perform a DNS reverse lookup
- use (if available) %USERDNSDOMAIN% variable
- append a constant value (provided by config file)

I am obtaining it using a Starlark processor (see below), but I think this should be a feature provided by default.

My starlark plugin:
```
### Processor Add Domain and Lowercase
# This Starlark processor append a domain name to `host` tag
# (if it is not a domain name) and converts it to lowercase.
# Domain name must be stored in constant `domain_name`.
[[processors.starlark]]
  # Embedded code
  source = '''
def apply(metric):
    fqdn = metric.tags["host"]

    # FQDN are recognized by looking for character `.`
    # If `.` is not found, `domain_name` is appended
    sep_index = fqdn.find(".")
    if sep_index < 0:
        fqdn += "." + domain_name

    # Forces lowercase
    metric.tags["host"] = fqdn.lower()

    return metric
'''

  # Processor constants
  [processors.starlark.constants]
    # Domain name to append to `host` tag
    domain_name = "mydmain.test"
```

**Comment by powersj** [comment]
Hi,

> Telegraf must be able to understand the FQDN of the current Windows server is running on, similarly to Linux.

We have no plan to change the behavior on Windows. This would cause chaos for our users. Additionally, [on Linux](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/os/sys_linux.go) Go uses the value from uname, this may not be the FQDN either.

Your workaround is probably the best method for now + the string processor to lower case the value.
