### ISSUE TITLE
Need to monitor the website http_response status 

### ISSUE THREAD

**Issue by RAVITEJA508** [influxdata/telegraf#14782]
### Use Case

I want to monitor the website which consits of SSO credentials .
i couldn't see that there is no option monitor the website which has OKTA SSO authorization .

### Expected behavior

Need to view the ouptut in dashboards as url status is  200 or OK or down or 403/403/400/500 error 

### Actual behavior

Actually i’m trying to monitor the jenkins website status whether it is up or down or 200 .
For this I configured in telegraf plugin metrics as below

```toml
[[inputs.http_response]]
 # ## Deprecated in 1.12, use 'urls'
 # ## List of urls to query. 
name_override = "status_url" 
urls = ["https://info-jenkins.com", "https://info-jenkins1.com" ] 
response_timeout = "5s" 
# ## HTTP Request Method method = "GET"
 ###interval = "30s" 
# ## Whether to follow redirects from the server (defaults to false) 
follow_redirects = true
```

Now when i’m trying to fetch the url status from grafana . Some webistes status showing me as 403 status code and some showing as 200 status-code .and i’m able to access the website url also .can anyone help me with this .

note : to login to the jenkins url website i need to enter the SSO credentials .

Input plugin metric -

```toml
[[inputs.http_response]] 
# ## Deprecated in 1.12, use 'urls' 
# ## Server address (default [http://localhost](http://localhost/))
 # # address = "[http://localhost](http://localhost/)"
 # ## List of urls to query.
 name_override = "status_url" 
urls = ["[https://url.com](https://url.com/)", "[https://url.com](https://url.com/)"] 
response_timeout = "5s" 
# # # HTTP Request Method method = "GET"
 ###interval = "30s" 
# ## Whether to follow redirects from the server (defaults to false) follow_redirects = true
```

Output of telegraf debug

```s
$ telegraf -config /etc/telegraf/telegraf.conf -input-filter http_response -test
2024-02-12T15:30:21Z I! Starting Telegraf 1.21.2
2024-02-12T15:30:21Z I! Loaded inputs: http_response
2024-02-12T15:30:21Z I! Loaded aggregators:
2024-02-12T15:30:21Z I! Loaded processors:
2024-02-12T15:30:21Z W! Outputs are not used in testing mode!
2024-02-12T15:30:21Z I! Tags enabled: host=hostname

status_url,host=hostname,method=GET,result=success,server=https://url1.com/,status_code=401 content_length=450i,http_response_code=401i,response_time=0.020731181,result_code=0i,result_type=“success” 1700000
status_url,host=hostname,method=GET,result=success,server=https://url2.com/,status_code=500 content_length=8176i,http_response_code=500i,response_time=0.013636198,result_code=0i,result_type=“success” 1707750000 
2024-02-12T15:30:21Z E! [inputs.http_response] Error in plugin: only http and https are supported
status_url,host=hostname,method=GET,result=success,server=https://url3.com/,status_code=500 content_length=7758i,http_response_code=500i,response_time=0.014732737,result_code=0i,result_type=“success” 170770000
status_url,host=hostname,method=GET,result=success,server=https://url4.com/,status_code=500 content_length=6579i,http_response_code=500i,response_time=0.046924287,result_code=0i,result_type=“success” 1707000
status_url,host=hostname,method=GET,result=success,server=https://url5.com/,status_code=401 content_length=450i,http_response_code=401i,response_time=0.005292509,result_code=0i,result_type=“success” 170700
status_url,host=hostname,method=GET,result=success,server=https://url6.com/,status_code=401 content_length=450i,http_response_code=401i,response_time=0.066148339,result_code=0i,result_type=“success” 17077 
2024-02-12T15:30:22Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

**Comment by powersj** [comment]
Hi,

> Actually i’m trying to monitor the jenkins website status whether it is up or down or 200 .

To be sure I am following the flow here, you are providing a URL to the root of your jenkins server? Then when loading this page you first have to sign in?

Can you share minus the domain name, the URLs you are using?

My experience with Jenkins has been that you can load and view the interface, which means this plugin should work without logging in. However, in your case are you saying you need to first login to view jenkins?

Thanks

**Comment by RAVITEJA508** [comment]
yes the url belongs to the jenkins server . while logging to jenkins UI it will ask SSO credentials to view jobs/manage jenkins info .

url : https://jenkins.inf.com/

yes , i can view the basic info of jenkins without logging  the UI also.

**Comment by powersj** [comment]
> yes , i can view the basic info of jenkins without logging the UI also.

Then why do you need to log in?

**Comment by RAVITEJA508** [comment]
i don't want to login .i just want to monitor the url status . but the 403 status is showing while monitoring the  url https response

**Comment by RAVITEJA508** [comment]
@powersj 

when i tried to do curl the below output came 



```
curl -vvv https://jenkins.inf.com/
*   Trying 10.10.55.211:443...
* Connected to jenkins.inf.com (10.10.55.211) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET / HTTP/1.1
> Host: jenkins.inf.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Server: nginx/1.14.0 (Ubuntu)
< Date: Wed, 14 Feb 2024 04:15:31 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 837
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Set-Cookie: JSESSIONID.f6879ba6=nodebfcr4sjop8gxh9576.node0; Path=/; Secure; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Hudson: 1.395
< X-Jenkins: 2.249.2
< X-Jenkins-Session: c8449149
< X-Hudson-CLI-Port: 33924
< X-Jenkins-CLI-Port: 33924
< X-Jenkins-CLI2-Port: 33924
< X-You-Are-Authenticated-As: anonymous
< X-Required-Permission: hudson.model.Hudson.Read
< X-Permission-Implied-By: hudson.security.Permission.GenericRead
< X-Permission-Implied-By: hudson.model.Hudson.Administer
<
<html><head><meta http-equiv='refresh' content='1;url=/securityRealm/commenceLogin?from=%2F'/><script>window.location.replace('/securityRealm/commenceLogin?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>                                                                                                                                                                                                                                                                                                            * Connection #0 to host jenkins.inf.com left intact
```



i think its not permission issue. Why because i can able to view the page UI by default .

**Comment by Hr0bar** [comment]
Seems working as expected, but you can try monitoring these endpoints that are supposed to be non-password/SSO protected:

https://info-jenkins.com/login
or
https://info-jenkins.com/static/<anystring>/images/svgs/logo.svg

Or you can query some API endpoints.
from:
https://devops.stackexchange.com/questions/3720/jenkins-health-check-url

Or alternatively you could create/set your custom jenkins web HTTP endpoint for monitoring the status of the service, that is not password/SSO protected by disabling it for that particular endpoint.

**Comment by powersj** [comment]
@RAVITEJA508,

Not sure where to go with this issue. While you are getting a 403, that is essentially a valid response in that you are not logged in. As @Hr0bar has pointed out, you could point at the login page, which shouldn't get you a 4xx error code, but a 2xx code or some image or API endpoint.

Otherwise, I think we should close this issue.
