### ISSUE TITLE
Telegraf Logparser - Response code: tag or field?

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/telegraf#1479]
### Proposal:

Response Code should be tag in the logparser plugin
### Current behavior:

It is a field
### Desired behavior:

Is should be a tag
### Use case: [Why is this important (helps with prioritizing requests)]

There are a limited number of variants for response code so it shouldn't increase series cardinality too much. It is very likely that you would want to use response code in a WHERE or GROUP BY query. This was initially proposed in the Google group and got a thumbs up from @beckettsean

**Comment by sparrc** [comment]
👍

**Comment by Mikanoshi** [comment]
And this totally disables queries like `WHERE resp_code >= 400` :)
But when adding resp_code as int it disables GROUP BY... So had to add the code twice.
Casting values to integer in WHERE would be useful #5930

**Comment by sparrc** [comment]
oh, shoot, now I remember that is why I made it a field in the first place. I'll have to think if I want to change it back now

**Comment by jcmcken** [comment]
This change basically invalidates the discussion [here](https://www.influxdata.com/telegraf-correlate-log-metrics-data-performance-bottlenecks/), due to comparators not working with tags (as mentioned by @Mikanoshi)

**Comment by sparrc** [comment]
if you want it as a field, you can change this by using your own custom log format:

```
COMMON_LOG_FORMAT_FIELD_RC %{CLIENT:client_ip} %{NOTSPACE:ident} %{NOTSPACE:auth} \[%{HTTPDATE:ts:ts-httpd}\] "(?:%{WORD:verb:tag} %{NOTSPACE:request}(?: HTTP/%{NUMBER:http_version:float})?|%{DATA})" %{NUMBER:resp_code:int} (?:%{NUMBER:resp_bytes:int}|-)
```

**Comment by danielnelson** [comment]
Closing, use sparrc's technique to move the item to a tag if desired.
