### ISSUE TITLE
Jolokia support multiple dimensions

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1481]
### Proposal:

Currently jolokia doesn't support data returned with multiple dimensions.

### Current behavior:

Config:
```
[[inputs.jolokia.metrics]]
	name = "garbage_collector"
	mbean = "java.lang:type=GarbageCollector,*"
	attribute = "CollectionCount,CollectionTime"
```

Output:

    * Plugin: jolokia, Collection 1
    > jolokia,host=fll2gbow02dev,jolokia_host=127.0.0.1,jolokia_port=7777 garbage_collector_java.lang:name\=ConcurrentMarkSweep\,type\=GarbageCollector="map[CollectionTime:116 CollectionCount:3]",garbage_collector_java.lang:name\=ParNew\,type\=GarbageCollector="map[CollectionCount:54 CollectionTime:941]" 1468266458664897695

### Desired behavior:

```
* Plugin: jolokia, Collection 1
> jolokia,host=fll2gbow02dev,jolokia_host=127.0.0.1,jolokia_port=7777,name=ConcurrentMarkSweep,type=GarbageCollector CollectionTime=116i CollectionCount=3i 1468266458664897695
> jolokia,host=fll2gbow02dev,jolokia_host=127.0.0.1,jolokia_port=7777,name=ParNew,type=GarbageCollector CollectionCount=54i,CollectionTime=941i 1468266458664897695
```

**Comment by trehn** [comment]
Hm, I don't know anything about Go, but to me it looks like at least it was meant to be handled:

https://github.com/influxdata/telegraf/blob/8742ead58539581fd18fd5c0a606936546ead24b/plugins/inputs/jolokia/jolokia.go#L248

So maybe this is a bug rather than a new feature.

**Comment by sparrc** [comment]
I don't have the ability to test, but PRs would be appreciated :).

**Comment by kostasb** [comment]
+1 on this

```
> select heap_memory_usage_NonHeapMemoryUsage from jolokia where time > now() - 40s
name: jolokia
-------------
time			heap_memory_usage_NonHeapMemoryUsage
1469016050000000000	map[committed:2.22101504e+08 init:2.3527424e+07 used:2.20133792e+08 max:2.197815296e+09]
```

The desired behavior would be to unpack the map returned by JMX into multiple fields of the proper type instead of storing the map into a single string field.

Not sure if it is a bug or just not included in the plugin's implementation.

**Comment by trehn** [comment]
I have created a PR with a quick fix.

A workaround until it is merged is to configure multidimensional attributes separately, e.g.

```
  [[inputs.jolokia.metrics]]
    name = "heap_memory_usage"
    mbean  = "java.lang:type=Memory"
    attribute = "HeapMemoryUsage"

  [[inputs.jolokia.metrics]]
    name = "non_heap_memory_usage"
    mbean  = "java.lang:type=Memory"
    attribute = "NonHeapMemoryUsage"
```

instead of

```
  [[inputs.jolokia.metrics]]
    name = "heap_memory_usage"
    mbean  = "java.lang:type=Memory"
    attribute = "HeapMemoryUsage,NonHeapMemoryUsage"
```
