### ISSUE TITLE
Jolokia Plugin Logging Empty RequestURI

### ISSUE THREAD

**Issue by kevinjos** [influxdata/telegraf#1482]
## Bug report

The Jolokia Plugin currently logs the RequestURI on failed requests. This net/http Request struct member is often empty.
### System info:

Tested on OS X and Centos7 with telegraf 1.0.0-beta2 and dev/master checkout.
### Steps to reproduce:
1. cd plugins/inputs/jolokia/; go test
### Expected behavior:

logging the Request.URL or similar
### Actual behavior:

logs an empty RequestURI
### Additional info:

I may be useful to log the whole request struct with "%+v"

**Comment by sparrc** [comment]
sure, PRs are appreciated :)

**Comment by sparrc** [comment]
going to close this, PRs welcome but it's not really worth keeping this on the issue tracker
