### ISSUE TITLE
Allow regex input for the processor plugin `converter`

### ISSUE THREAD

**Issue by rc-networks** [influxdata/telegraf#14851]
### Use Case

When dealing with a large number of data input.
It would be great if we have a way to select field and tags to be converted using regex.

For example:
```
[[processors.converter]]
  [processors.converter.fields]
    integer = ["^(?!fieldXXX$|fieldYYY$).*"]
```

Instead of writing 10s or 100s of fields, this would be better and cleaner.

### Expected behavior

Converter checks all the fields or tags against the provided regex and does the required convert operations

### Actual behavior

Tested the regex given above but it does not work.
Best case is we just use something like:
```
integer = ["*"]
````
and ignore everything else that's failing the conversion.

**Comment by powersj** [comment]
Hi,

> Best case is we just use something like:

Yes, you can use globs with the converter processor, but not full regex. We certainly would not change this as it could cause a sorts of issues with existing user's setup and configurations.
