### ISSUE TITLE
InfluxDB input

### ISSUE THREAD

**Issue by joshuaspence** [influxdata/telegraf#1485]
Currently Telegraf has an `influxdb` input which works by querying a HTTP endpoint. I am looking for an alternative InfluxDB input that is more similar to the `statsd` input. The `statsd` input essentially sets up a TCP listener that other application can send StatsD-formatted data to. Is there an equivalent for InfluxDB?

**Comment by sparrc** [comment]
there isn't an http influxdb service plugin, but you could use the tcp_listener, udp_listener, etc. plugins, which can parse the influx line-protocol data format.

There is also https://github.com/influxdata/telegraf/pull/1407 which would add an http input plugin.
