### ISSUE TITLE
Feature Request : NATS output plugin 

### ISSUE THREAD

**Issue by prune998** [influxdata/telegraf#1487]
## Feature Request

Create a NATS (streaming ?) output plugin

### Desired behavior:
Being able to send metrics to a NATS Queue server, possibly using the streaming protocol
https://github.com/nats-io/nats-streaming-server/blob/master/README.md
http://site-nats-streaming-staging.zeppole.buffalo.im/

### Use case: 
When you have a large number of servers, you may want to use a broker in between the gathering client (telegraf) and the influx server.
NATS is a new queue system and is written in GO.
There already is an input plugin.

**Comment by smetj** [comment]
This would be a good idea!

**Comment by pires** [comment]
This makes sense. I'll pick it up during the weekend.
