### ISSUE TITLE
Telegraf 1.28, is not starting due to the error "error parsing file array, undefined but requested serializer: json"

### ISSUE THREAD

**Issue by akshayktk** [influxdata/telegraf#14886]
### Please direct all support questsions to slack or the forums. Thank you.

Tried to use release-1.28 version. Steps followed:

Note: tried both parser.json and parser.json_v2 in the BUILDTAGS

> export BUILDTAGS="custom inputs.cpu parsers.json_v2 outputs.file"
> make build
> ./telegraf config -input-filter cpu  --output-filter file config>telegraf.conf
> ./telegraf --config telegraf.conf

telegraf.conf:
```
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "json"
```

**Error:**
```
2024-02-23T05:57:12Z I! Loading config: telegraf.conf
2024-02-23T05:57:12Z E! error loading config file telegraf.conf: error parsing file array, undefined but requested serializer: json
```

Came to know similar issue is already reported under 
https://github.com/influxdata/telegraf/issues/13441

However, this fix is not yet available in release-1.28, release-1.29 branches. Please let me know the steps to resolve this issue for using release-1.28 branch.

**Comment by srebhan** [comment]
Sure 1.26 works as there serializer were not factored out yet. AS I WROTE you need to add `serializers.json` (note **serializers**) to your build tags! I really encourage you to use the `custom-builder` tool as this does the whole thing for you!

**Comment by akshayktk** [comment]
Great!, 
It worked after adding serializers.json in my build tags.
I would like to learn more about custom-builder, it would be helpful if you could provide some references.

**Comment by srebhan** [comment]
Here is a blog post describing what it does: https://www.influxdata.com/blog/how-reduce-telegraf-binary-size/ Also feel free to join us on Slack if you need assistance!
