### ISSUE TITLE
Add metric vm drs score

### ISSUE THREAD

**Issue by fferraro87** [influxdata/telegraf#14900]
### Use Case

it will be interested monitoring vm drs score value on my vmware cluster

### Expected behavior

you can see vm drs score value from summary on cluster page on vsphere

### Actual behavior

now i don't have this metric exposed by telegraf agent

**Comment by Muy69** [comment]
The Problem would be where the Metric is located . 

Govnomi is not specific , so first we should supply the Developer with a info how to extract the VM DRS Score Data.

**Comment by powersj** [comment]
Hi,

The vsphere plugin is not one I'm thrilled about editing given its unique structure and my complete lack of ability to test changes.

Is this not already exposed via some cluster-level metric already?

It looks like we do have access to the `ClusterComputeResource`, however it is not in a place where we are generating metrics. Instead, we generate a map with references to the various metrics exposed.
