### ISSUE TITLE
[input.azure_monitor] Invalid api version

### ISSUE THREAD

**Issue by xolott** [influxdata/telegraf#14909]
### Relevant telegraf.conf

```toml
# Gather Azure resources metrics from Azure Monitor API
[[inputs.azure_monitor]]
    # can be found under Overview->Essentials in the Azure portal for your application/service
    subscription_id = "xxx"
    # can be obtained by registering an application under Azure Active Directory
    client_id = "xxx"
    # can be obtained by registering an application under Azure Active Directory
    client_secret = "xxx"
    # can be found under Azure Active Directory->Properties
    tenant_id = "xxx"

    [[inputs.azure_monitor.resource_target]]
        resource_id = "/subscriptions/xxx/resourceGroups/MC_xxx/providers/Microsoft.Network/loadBalancers/kubernetes"
        metrics = [ "AllocatedSnatPorts", "SnatConnectionCount", "UsedSnatPorts" ]
```

### Logs from Telegraf

```text
2024-02-28T20:27:37Z I! Loading config: /etc/telegraf/telegraf.conf
2024-02-28T20:27:37Z I! Starting Telegraf 1.29.5 brought to you by InfluxData the makers of InfluxDB
2024-02-28T20:27:37Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
2024-02-28T20:27:37Z I! Loaded inputs: azure_monitor
2024-02-28T20:27:37Z I! Loaded aggregators:
2024-02-28T20:27:37Z I! Loaded processors:
2024-02-28T20:27:37Z I! Loaded secretstores:
2024-02-28T20:27:37Z I! Loaded outputs: sumologic
2024-02-28T20:27:37Z I! Tags enabled: host=vm-sumologic-integration-centralus-001
2024-02-28T20:27:37Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"vm-sumologic-integration-centralus-001", Flush Interval:10s
2024-02-28T20:27:37Z D! [agent] Initializing plugins
2024-02-28T20:27:38Z E! [telegraf] Error running agent: could not initialize input inputs.azure_monitor: error checking resource targets metrics validation: error getting metric definitions response for resource target /subscriptions/xxx//subscriptions/xxx/resourceGroups/MC_rxxx/providers/Microsoft.Network/loadBalancers/kubernetes: error listing metric definitions for the resource target /subscriptions/xxx//subscriptions/xxx/resourceGroups/MC_xxx/providers/Microsoft.Network/loadBalancers/kubernetes: GET https://management.azure.com/subscriptions/xxx/subscriptions/xxx/resourceGroups/MC_xxx/providers/Microsoft.Network/loadBalancers/kubernetes/providers/Microsoft.Insights/metricDefinitions
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidApiVersionParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidApiVersionParameter",
    "message": "The api-version '2021-05-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
  }
}
--------------------------------------------------------------------------------
```

### System info

Telegraf 1.29.5 (git: HEAD@138d0d54), Ubuntu 22.04.3 LTS

### Steps to reproduce

1. Created an application in Entra ID
2. Created a secret (password) for that application
3. Install and run telegraf with that config (omitted the output for simplicity)

### Expected behavior

It should work

### Actual behavior

Throwing an error and the telegraf process ends

**Comment by powersj** [comment]
Looking at upstream issues:

* https://github.com/Azure/azure-sdk-for-go/issues/6082: talks about not the reporter not specifying a resource group + location
* https://github.com/Azure/azure-sdk-for-go/issues/10712: user not providing a resource group

I don't see a `resource_group` in your `inputs.azure_monitor.resource_target` config, other than in the URI. Can you try adding that please?

**Comment by xolott** [comment]
That fixed the issue. Thanks

**Comment by powersj** [comment]
> That fixed the issue. Thanks

Awesome! Thanks for looping around and confirming. That error message from Azure is really unfortunate. I immediately wondered if we had an out-of-date library in use.

I'm going to go ahead and close this, but thanks again!

**Comment by yramazany** [comment]
[[inputs.azure_monitor]]
  # can be found under Overview->Essentials in the Azure portal for your application/service/7c-msdn-48-partner
  subscription_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  #subscription_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be obtained by registering an application under Azure Active Directory
  client_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be obtained by registering an application under Azure Active Directory
  client_secret = "fvE8Q~xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be found under Azure Active Directory->Properties
  tenant_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  #subscription_id = "7c5d658e-f4b9-4518-87da-47803dce1345"
  #api_version = "2020-06-01"
 
  
 [[inputs.azure_monitor.resource_target]]
    # can be found under Overview->Essentials->JSON View in the Azure portal for your application/service
    # must start with 'resourceGroups/...' ('/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx'
    # must be removed from the beginning of Resource ID property value)
    resource_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
    # the metric names to collect
    # leave the array empty to use all metrics available to this resource
    metrics = [  ]
    # metrics aggregation type value to collect
    # can be 'Total', 'Count', 'Average', 'Minimum', 'Maximum'
    # leave the array empty to collect all aggregation types values for each metric
    aggregations = [  ]
	#resource_group = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"

![errorazure](https://github.com/influxdata/telegraf/assets/163828184/69fed438-2efc-4c1d-bb3e-16efeb7233b5)

**Comment by yramazany** [comment]
> Looking at upstream issues:
> 
> * [InvalidApiVersionParameter - 2018-09-30 Azure/azure-sdk-for-go#6082](https://github.com/Azure/azure-sdk-for-go/issues/6082): talks about not the reporter not specifying a resource group + location
> * [SQL Server SDK doesn't validate that user provided a nonempty resource group Azure/azure-sdk-for-go#10712](https://github.com/Azure/azure-sdk-for-go/issues/10712): user not providing a resource group
> 
> I don't see a `resource_group` in your `inputs.azure_monitor.resource_target` config, other than in the URI. Can you try adding that please?


 [[inputs.azure_monitor]]
  # can be found under Overview->Essentials in the Azure portal for your application/service/7c-msdn-48-partner
  subscription_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  #subscription_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be obtained by registering an application under Azure Active Directory
  client_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be obtained by registering an application under Azure Active Directory
  client_secret = "fvE8Q~xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  # can be found under Azure Active Directory->Properties
  tenant_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  #subscription_id = "xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
  #api_version = "2020-06-01"
 
  
 [[inputs.azure_monitor.resource_target]]
    # can be found under Overview->Essentials->JSON View in the Azure portal for your application/service
    # must start with 'resourceGroups/...' ('/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx'
    # must be removed from the beginning of Resource ID property value)
    resource_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
    # the metric names to collect
    # leave the array empty to use all metrics available to this resource
    metrics = [  ]
    # metrics aggregation type value to collect
    # can be 'Total', 'Count', 'Average', 'Minimum', 'Maximum'
    # leave the array empty to collect all aggregation types values for each metric
    aggregations = [  ]
	#resource_group = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx"
![errorazure](https://github.com/influxdata/telegraf/assets/163828184/f953eb30-4054-454a-8f20-5dd3ec73b7b9)

**Comment by powersj** [comment]
@yramazany,

Please don't comment on closed issues. For support please use the [Community Slack](https://influxdata.com/slack) or [Community Forums](https://community.influxdata.com/).

This issue was due to not having a resource_group in the config. Given your pasted config, your resource_group looks commented out.
