### ISSUE TITLE
Inquiry regarding pull request conditions

### ISSUE THREAD

**Issue by jiee-altibase** [influxdata/telegraf#14905]
### Use Case

I am developing an Altibase input plugin for Telegraf. 
Altibase is a relational DBMS similar to MySQL. 
Since Altibase does not provide a Go driver, I plan to use the Go ODBC driver(github.com/alexbrainman/odbc) and UnixODBC. 
To do this, CGO_ENABLED=1 must be set in the Telegraf Makefile. 
Once the development of the Altibase input plugin for Telegraf is complete, I plan to submit a pull request, and I will also request that the CGO_ENABLED=1 change be included in the Makefile. 
I am inquiring in advance whether a pull request approval is possible under these conditions.

### Expected behavior

$ make build
CGO_ENABLED=1 go build -tags "" -ldflags " -X github.com/influxdata/telegraf/internal.Commit=e48b72f9 -X github.com/influxdata/telegraf/internal.Branch=master -X github.com/influxdata/telegraf/internal.Version=1.30.0-e48b72f9" ./cmd/telegraf

### Actual behavior

$ make build
CGO_ENABLED=0 go build -tags "" -ldflags " -X github.com/influxdata/telegraf/internal.Commit=e48b72f9 -X github.com/influxdata/telegraf/internal.Branch=master -X github.com/influxdata/telegraf/internal.Version=1.30.0-e48b72f9" ./cmd/telegraf
# github.com/alexbrainman/odbc/api
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:17:9: undefined: SQLSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:18:9: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:19:9: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:23:10: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:24:10: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:25:10: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:29:12: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:30:12: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:31:12: undefined: SQLUSMALLINT
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:32:12: undefined: SQLUINTEGER
../../../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20230814102256-1421b829acc9/api/api.go:32:12: too many errors
make: *** [Makefile:132: build] Error 1

### Additional info

I would like to submit a pull request that includes the CGO_ENABLED=1 setting in the Makefile. I'm wondering if this is possible.

**Comment by srebhan** [comment]
@jiee-altibase we cannot support CGO enabled builds of Telegraf as this creates external dependencies (e.g. libc) and prevents the current static builds. 

There are two ways forward, either implement a pure golang SQL driver _or_ provide an external plugin similar to https://github.com/lili-altibase/AMS...

**Comment by jiee-altibase** [comment]
@srebhan Thank you for the prompt response and that was helpful!

**Comment by srebhan** [comment]
I wish I had better news... ;-) In case you go the external plugin route, please submit a PR adding it to `EXTERNAL_PLUGINS.md`! Should we close this issue?
