### ISSUE TITLE
Replace hardcoded string with a variable for acc.AddFields() call in win_eventlog input plugin.

### ISSUE THREAD

**Issue by nonpolarity** [influxdata/telegraf#14944]
### Use Case

In our department several teams share the same telegraf service, and also share the same input plugin win_eventlog. To differentiate the metrics, we expect the metrics with different names corresponding to team name.
By importing the win_eventlog package and wrapping Gather() function, we can create different plugins for each team. 
The problem is that,  although metrics are collected through different plugins, all metrics name are "win_eventlog", because it is hardcoded.
https://github.com/influxdata/telegraf/blob/9a9bb16c08adab133f2d995d6e26bdad130999ef/plugins/inputs/win_eventlog/win_eventlog.go#L247

### Expected behavior

We can customize the name in metrics.

### Actual behavior

All the metircs with the same hardcoded name "win_eventlog".

### Additional info

Possible solution:
Add PluginName to WinEventLog:
```
type WinEventLog struct {
	PluginName string ``toml: plugin_name`
	...
}
```
And initialize the variable at init():
```
func init() {
	inputs.Add("win_eventlog", func() telegraf.Input {
		return &WinEventLog{
			PluginName:        "win_eventlog",
...
}
```
at Gather(), just replace the hardcoded string with the variable:
```
			acc.AddFields(w.PluginName, fields, tags, timeStamp)
```

After the change, we can import the win_eventlog package and customize the metrics name during init(), such as "win_eventlog_teamA"

**Comment by srebhan** [comment]
@nonpolarity I replied in the PR already. Please try

```toml
[[input.win_eventlog]]
  name_override = "win_eventlog_teamA"
  ...

[[input.win_eventlog]]
  name_override = "win_eventlog_teamB"
  ...
```
it will do _exactly_ what you are asking for!

**Comment by nonpolarity** [comment]
> @nonpolarity I replied in the PR already. Please try
> 
> ```toml
> [[input.win_eventlog]]
>   name_override = "win_eventlog_teamA"
>   ...
> 
> [[input.win_eventlog]]
>   name_override = "win_eventlog_teamB"
>   ...
> ```
> 
> it will do _exactly_ what you are asking for!

Yes it works, thanks!
