### ISSUE TITLE
Remote host WMI collection capabilty in the win_wmi plugin 

### ISSUE THREAD

**Issue by shockogit** [influxdata/telegraf#14942]
### Use Case

The abilty for the WMI plugin https://github.com/influxdata/telegraf/blob/9a9bb16c08adab133f2d995d6e26bdad130999ef/plugins/inputs/win_wmi/win_wmi.go#L1 to collect data from a **_remote_** host.

### Expected behavior

The abilty to specify a remote host(s) to gather WMI data from

### Actual behavior

Only local host is supported so agent must run on host. No agentless capbilty. 

### Additional info

WMI is generally a datastore accessed rmeotly by numerous native windows tools. Seems logical to add this feature.

**Comment by powersj** [comment]
Hi,

I had some déjà vu thinking we already did this, but https://github.com/influxdata/telegraf/pull/12556 was about `win_perf_counters`.

Let me talk to folks about this tomorrow. It seems this has [come up before](https://github.com/influxdata/telegraf/issues/6489#issuecomment-542270876).

**Comment by powersj** [comment]
Sven is going to look into doing this. This should be similar to what we have for win_perf_counters in terms of auth, and does mean that this would only be available from a windows machine to a windows machine.

**Comment by shockogit** [comment]
it would be super usefule. For windows, I find myself more and more gathering the win_perf_counters remotely. I have several use cases for wmi, in particular the Citrix EUEM metrics.

**Comment by srebhan** [comment]
@shockogit please test the binary in #14973 and let me know if it works for your use-case!

**Comment by shockogit** [comment]
> @shockogit please test the binary in #14973 and let me know if it works for your use-case!

Works perfectly!
