### ISSUE TITLE
Bigquery ADC has missing scope and incorrect context

### ISSUE THREAD

**Issue by tgupta3** [influxdata/telegraf#14957]
### Relevant telegraf.conf

```toml
[[outputs.bigquery]]
  project = "my-project"
  dataset = "test"
```

### Logs from Telegraf

```text
2024/03/08 02:15:00 E! inserting metric "<Trim>" failed: Post "https://bigquery.googleapis.com/bigquery/v2/projects/<trim>/datasets/test/tables/<trim>/insertAll?alt=json&prettyPrint=false": Post "https://oauth2.googleapis.com/token": context canceled
```

### System info

Telegraf latest on alpine

### Steps to reproduce

1. Create a bigquery output plugin field in telegraf.conf making sure credentials file is omitted. 
2. Observe the logs, and it will report incorrect response from STS server or contextcanclled.
...

### Expected behavior

- ADC should be able to discover the default credentials and use that to exchange the token for the required scope.

### Actual behavior

Token exchange fails.

**Comment by powersj** [comment]
next steps: wrap up PR
