### ISSUE TITLE
Drop `chronyc` requirement from documentation and sample configuration

### ISSUE THREAD

**Issue by cschug** [influxdata/telegraf#14964]
### Use Case

With release of [Telegraf 1.30.0](https://github.com/influxdata/telegraf/releases/tag/v1.30.0) the dependency on the `chronyc` binary was dropped in code #14629 but the documentation and the sample configuration still state it's an requirement ("requires chronyc executable") which should be removed, too.

- https://github.com/influxdata/telegraf/blob/v1.30.0/plugins/inputs/chrony/README.md?plain=1#L20
- https://github.com/influxdata/telegraf/blob/v1.30.0/plugins/inputs/chrony/sample.conf#L1

### Expected behavior

Sync documentation and sample configuration with code.

### Actual behavior

Documentation and sample code do not reflect the latest changes.

**Comment by srebhan** [comment]
@cschug would you be willing to put this into a pull-request?

**Comment by cschug** [comment]
@srebhan sure, it's done.
