### ISSUE TITLE
[[inputs.radius]] Set NAS-IP-Address

### ISSUE THREAD

**Issue by kpdo** [influxdata/telegraf#14962]
### Use Case

I want to use the inputs.radius plugin to send an authentication request to a radius server.

### Expected behavior

I expected to receive an "Access-Accept" packet

### Actual behavior

I received an "Access-Reject" packet (although the credentials were correct)

### Additional info

https://datatracker.ietf.org/doc/html/rfc2865#page-29 states that "Either NAS-IP-Address or NAS-Identifier MUST be present in an Access-Request packet". Currently, the inputs.radius plugin supports neither so it's not possible to send an Access-Request packet that conforms to RFC 2865.

When I set the NAS-IP-Address the authentication works fine. I tested it using this script:

````
package main

import (
        "context"
        "log"
        "net"

        "layeh.com/radius"
        "layeh.com/radius/rfc2865"
)

func main() {
        packet := radius.New(radius.CodeAccessRequest, []byte(`mysharedsecret`))
        rfc2865.UserName_SetString(packet, "myuser")
        rfc2865.UserPassword_SetString(packet, "mypassword")
        rfc2865.NASIPAddress_Set(packet, net.ParseIP("123.123.123.123")) // this is what's currently missing in inputs.radius
        response, err := radius.Exchange(context.Background(), packet, "122.122.122.122:1111")
        if err != nil {
                log.Fatal(err)
        }

        log.Println("Code:", response.Code)
}
````

It should either be possible to set the NAS-IP-Address manually in the config or the plugin should automatically set the NAS-IP-Address to the IP of the host that sends the request.

**Comment by powersj** [comment]
Thanks for the issue. It looks as simple as adding that line with the IP address of the system? What if we are on a system with multiple IP addresses, does it need to be on the same subnet or just any IP address?

@Hr0bar - thoughts on a method to add this that is backwards compatible? Can we add it without worrying about existing usage or does this need to be behind an option?

**Comment by Hr0bar** [comment]
Indeed, similar is already part of the tacacs plugin: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tacacs where it can be set (and default is localhost for local tacacs servers where telegraf is running)

I dont know what is the default if its not set in the radius client currently, probably the attribute is not in the packet altogether. But we can just add an option for it that is set only when its configured, so the default stays whatever it is currently or ?  I would have to check what we have configured for our use case, but probably anonymous access allowed for our monitoring user (we enforce NAS IP addresses for real network devices), so we never added this option. But definitely useful to be added as its very commonly required.

Think adding this is very straightforward, but not sure about tests... whether the local + docker test server is easily configurable for this, probably yes...

**Comment by powersj** [comment]
> we can just add an option for it that is set only when its configured, so the default stays whatever it is currently

This sounds good.

> Think adding this is very straightforward, but not sure about tests... whether the local + docker test server is easily configurable for this, probably yes...

Yeah let me give it a shot with it set and see if we can come up with a consistent test. Otherwise I can test that it is set or something similar.

Thank you for the fast response!

**Comment by Hr0bar** [comment]
I did a quick mock for the local test, seems straightforward 
https://github.com/Hr0bar/telegraf/commit/c9f645a4df65ee73f94409b355299d4d85ae873e

The integration test needs checking how it exactly behaves in the container radius server,  there are certainly config options to set it per client, currently it accepts whole ipv4 range:
client localtest {
	ipaddr = 0.0.0.0/0
	secret = testsecret
}

But no idea if it simply trusts the received packet NAD IP address info or if it checks the actual real client IP address

**Comment by Hr0bar** [comment]
> 
> I did try a few integration tests, with setting this option and saw no difference. I decided to keep setting this value to a unit test as such.

Did not try it, but setting additional client in the test data with ipaddr set to some random IP address should result in the request being rejected (for testing negative case), unless its ignored for some reason:

https://github.com/2stacks/docker-freeradius/blob/master/etc/raddb/clients.conf

Right now there is only one client that is allowed from everywhere (0.0.0.0/0) in plugins/inputs/radius/testdata/raddb/clients.conf

**Comment by powersj** [comment]
> Right now there is only one client that is allowed from everywhere (0.0.0.0/0) in plugins/inputs/radius/testdata/raddb/clients.conf

Right I changed that to some value to `123.123.123.0/24`, set the IP in the request, and as a result saw the client timeout successfully. The timeout has to be set to something other than 0 otherwise the client will hang.
