### ISSUE TITLE
MQTT Consumer Measurement Name By Topic

### ISSUE THREAD

**Issue by m-r-mccormick** [influxdata/telegraf#14982]
### Use Case

Measurements must have a consistent data type, otherwise they won't be pushed to influxdb. MQTT brokers can have a significant number of topics (millions) with varying data types. If a single measurement name is used for a wildcard subscription like `Root/#`, and a global `_measurement` is used, data type conflicts can prevent data from being pushed to influx. Due to the huge volume of unique topics with varying data types, crafting a fancy config entry per topic is not feasible. Since the topic is an excellent primary key identifier to distinguish between 'measurements' and therefore types, it would be great if the topic could be pushed into the `_measurement` field. There doesn't currently appear to be a clean way of configuring this.

### Expected behavior

MQTT Payload Format:
```json
{
	"Name": "My Name",
	"Value": 1.0,
	"Timestamp": "2024-03-05T18:15:00.000Z",
}
```

Telegraf Config:
```yml
[[inputs.mqtt_consumer]]
  servers = [ "tcp://broker:1883" ]
  topics = [
    "Root/#"
  ]
  topic_tag = "Topic"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name_path = "Topic"
    timestamp_path = "Timestamp"
    timestamp_format = "2006-01-02T15:04:05Z07:00" # ISO 8601 Format.
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "Value"
      optional = false
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "Name"
      optional = true
```

json_v2 required to parse different types such as boolean.

Expected Behavior: The MQTT topic becomes the `_measurement` field.

### Actual behavior

Nothing gets pushed to influxdb because the `measurement_name_path` only appears to look inside the payload json for the specified `Topic` field.

Edit: Added Output:

```
2024-03-13T00:39:39Z E! [outputs.influxdb_v2] Failed to write metric to bucket (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "Value" on measurement "mqtt_consumer" is type boolean, already exists as type float dropped=11

```

**Comment by powersj** [comment]
Hi,

We currently have the `topic_tag` config option that would let you send the topic to a specific tag. From here you can use the converter processor as:

```toml
[[processors.converter]]
  [processors.converter.tags]
    measurement = ["topic"]
```

The above would take the topic tag and make it the name of the measurement:

```diff
- mqtt_consumer,topic=sensor temp=42
+ sensor temp=42
```
