### ISSUE TITLE
Advice request: statsd aggregation

### ISSUE THREAD

**Issue by mrwilby** [influxdata/telegraf#1498]
We use the telegraf statsd input to monitor various subsystems in our stack. 

Many of our web services are based upon the dropwizard framework which includes codahale's excellent Metrics (http://metrics.dropwizard.io) middleware.

We use a statsd (dropwizard) Metrics plugin which is responsible for delivering metrics from dropwizard over the statsd protocol to the telegraf statsd input.

The challenge: The metrics/dropwizard statsd plugin emits metrics which are already pre-aggregated (for example, timing, histograms):

(this is what the telegraf statsd plugin receives from dropwizard metrics):

2016/07/15 11:20:29 STATSD: my_metric.max:582.05|ms
2016/07/15 11:20:29 STATSD: my_metric.mean:375.53|ms
2016/07/15 11:20:29 STATSD: my_metric.min:350.13|ms
2016/07/15 11:20:29 STATSD: my_metric.stddev:9.41|ms
2016/07/15 11:20:29 STATSD: my_metric.p50:376.16|ms
2016/07/15 11:20:29 STATSD: my_metric.p75:377.71|ms
2016/07/15 11:20:29 STATSD: my_metric.p95:390.73|ms
2016/07/15 11:20:29 STATSD: my_metric.p98:390.73|ms
2016/07/15 11:20:29 STATSD: my_metric.p99:390.73|ms
2016/07/15 11:20:29 STATSD: my_metric.p999:390.73|ms
2016/07/15 11:20:29 STATSD: my_metric.count:11|g
2016/07/15 11:20:29 STATSD: my_metric.m1_rate:0.00|ms
2016/07/15 11:20:29 STATSD: my_metric.m5_rate:0.00|ms
2016/07/15 11:20:29 STATSD: my_metric.m15_rate:0.00|ms
2016/07/15 11:20:29 STATSD: my_metric.mean_rate:0.00|ms

In turn, the telegraf statsd plugin then re-aggregates this data, emitting these metrics to the outputs:

...
my_metric.stddev,host=1.105,metric_type=timing 90_percentile=9.41,count=1i,lower=9.41,mean=9.41,stddev=0,upper=9.41 1468581632000000000
...

(one influxdb line per originally received statsd metric).

What is the recommended way to deal with this kind of metrics data pipeline where we already pre-aggregate and would prefer the dropwizard metrics to be passed through?

I am contemplating some changes to the statsd input to disable aggregation for certain named metrics, but I would like to ask if there is a better approach you could suggest.

Thanks in advance!

**Comment by sparrc** [comment]
I've never heard of a statsd server that doesn't aggregate metrics, so IMHO dropwizard should be fixed to not do the aggregation itself, or to send the statsd metrics as gauges, not histogram/timings (gauges do not get aggregated).

That being said, do you know of any precedent for a statsd server that has the option of disabling aggregation on timings?

**Comment by mrwilby** [comment]
@sparrc - thanks. Did some more digging since my earlier post.

Gut feel: I think the right thing to do here is to change dropwizard to send metrics in influxdb line format, and deliver to the telegraf UDP/TCP 'service' plugin instead. I am still validating if this is indeed the better approach.

Thanks for sharing your thoughts!

**Comment by mrwilby** [comment]
Yep this can be closed. Got it sorted now - switched to a dropwizard metrics component which can log in native influxdb line protocol coupled with an appropriate telegraf input service. Thanks

**Comment by cskinfill** [comment]
@mrwilby love to know/see what you ended up doing ... which metrics component are you using to write in influxdb protocol?

**Comment by mrwilby** [comment]
@cskinfill This problem was scoped around DropWizard integration with the Influx ecosystem. We ended up using a slightly customized version of https://github.com/iZettle/dropwizard-metrics-influxdb (dropwizard-side) and then we use the telegraf tcp listener on the telegraf side.
