### ISSUE TITLE
tagpass, tagdrop does not remove tags

### ISSUE THREAD

**Issue by Snelius30** [influxdata/telegraf#14990]
### Relevant telegraf.conf

```toml
Nope
```

### Logs from Telegraf

```text
Nope
```

### System info

any version

### Steps to reproduce

Nope

### Expected behavior

Removed tags in the output

### Actual behavior

Tags are present

### Additional info

In the [doc](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#routing-metrics-to-different-outputs-based-on-the-input) we have mention **"The tag is removed in the outputs before writing."** which awesome behaviour but actual it does not remove a tags and they are present in the output.

**Comment by kklis** [comment]
@srebhan It is stated in the example https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#routing-metrics-to-different-outputs-based-on-the-input

"Metrics are tagged with influxdb_database in the input, which is then used to select the output. The tag is removed in the outputs before writing."
