### ISSUE TITLE
Inquire about the usage of Telegraf in EKS Fargate

### ISSUE THREAD

**Issue by hoonchulyang** [influxdata/telegraf#14998]
### Please direct all support questsions to slack or the forums. Thank you.

We are currently using AWS EKS Fargate and have deployed Telegraf as a sidecar using the telegraf-operator. It seems that there is currently no input plugin specifically designed for Fargate.

Could you advise on which input plugin could be utilized for metric monitoring when using Fargate?

Thank you.

**Comment by srebhan** [comment]
@hoonchulyang from [documentation](https://docs.aws.amazon.com/eks/latest/userguide/monitoring-fargate-usage.html) and [here](https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate) it looks like this can simply be done using the [prometheus input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) can't it?

What do you have in mind when you say "specific plugin"?
