### ISSUE TITLE
inputs.ping: Can force IPv6-only but not IPv4-only

### ISSUE THREAD

**Issue by detobate** [influxdata/telegraf#15005]
### Use Case

For FQDNs with both A and AAAA records, the current options are: prefer IPv6, or force IPv6.
It'd be good if we can force IPv4-only (to then compare with forced IPv6-only tests)

### Expected behavior

Configuration var:
`ipv4 = true`

to force IPv4-only tests

### Actual behavior

`ipv4 = true` is not a valid configuration option

**Comment by powersj** [comment]
Hi,

In 20-30mins after this message, there will be test artifacts in #15011. Can you give those a shot and confirm it resolves your request?

Thanks!
