### ISSUE TITLE
riemann output  concatenating tags to metric name

### ISSUE THREAD

**Issue by rj-reilly** [influxdata/telegraf#1501]
Hi, I see when sending data from telegraf to riemann the tags are just joined together and added to the metric name, is this correct behavior ? I would think it should sent the tags to riemann as tags like 
```
{
host: "www1",
service: "http req",
metric: 2.53,
state: "critical",
description: "Request took 2.53 seconds.",
tags: ["http","tag2"]
}
```
instead we get 
win_cpu_testlivdev1_Processor%_Idle_Time where test, liv and dev are the tags. 

Thanks
Rob

**Comment by sparrc** [comment]
Yes those should be tags if that is available in the riemann data type. PRs appreciated :)

**Comment by devilldog** [comment]
OK, have not worked with GO before but the the output plugin looks relatively simple, I will see what I can do. Thanks !
Rob

**Comment by sparrc** [comment]
closing in favor of #1845
