### ISSUE TITLE
Counter metrics aren't accumulating

### ISSUE THREAD

**Issue by hert525** [influxdata/telegraf#15019]
### Please direct all support questsions to slack or the forums. Thank you.

Using Telegraf to consume JSON from Kafka and write as Counter metrics to Prometheus, but the Counter metrics aren't accumulating
![image](https://github.com/influxdata/telegraf/assets/19421393/1c621f84-6f15-40b7-b7a1-bc8ff75e4e5c)

**Comment by powersj** [comment]
We discussed this further in slack, but telegraf's prometheus output does not mimic the internals of prometheus. Rather it reports metrics in the style and format of prometheus. If a user wants to keep track and increment a metric value, then using starlark or even an aggregator are required.
