### ISSUE TITLE
Telegraf Varnish plugin (input) issue with Varnish 4.1

### ISSUE THREAD

**Issue by Lebvanih** [influxdata/telegraf#1502]
Hello,

We experienced some issue with the varnish input plugin. I am not entirely sure if this can be considered as a bug of the plugin or a missing part in the documentation, but here is my report.
### Information about the environment
- Telegraf version: 0.13.1 (.deb provided from influxdata repositories) 
- OS: debian 8
- Varnish version: 4.1.2
### Issue

From our logs we can see that the plugin is not able to collect metrics while a direct call to "varnishstats -1" is working without issue (test was done as root).

> 2016/07/16 11:07:00 ERROR in input [varnish]: error gathering metrics: error running varnishstat: Command timed out.

After digging a bit we found out that it was a right issue, if varnishstat is launched as telegraf user, he is not able to read the shared memory of varnish:

> root@host:~# su - telegraf -s /bin/bash
> telegraf@host:~$ varnishstat -1
> Can't open log - retrying for 5 seconds

We didn't had this issue with varnish 4.0.x so we checked the Changelog of varnish 4.1 regarding these tools and here is what we found:

> varnishlog, varnishncsa and other Varnish shared log utilities now must be run in a context with varnish group membership.
### Current "solution"

As "workaround" we added telegraf user to varnish group and restarted varnish 

> usermod -a -G varnish telegraf
> systemctl restart telegraf

And this fixed our issue.

The workaround is perfectly fine for us, however we couldn't find any documentation regarding this in the readme or the current open issue for this telegraf plugin and I believe that this should either be documented or fixed using another solution (if any)

**Comment by sparrc** [comment]
It's not possible to fix, but I agree that it should be documented. Any PRs would be greatly appreciated :).

**Comment by henryford** [comment]
This has been documented in 8a2373e8c89bb493ebb9217856a4c038c36d5105 - the issue probably can be closed.

**Comment by danielnelson** [comment]
Thanks for the heads up @henryford.
