### ISSUE TITLE
Get timeout error on windows container when start as the system service.

### ISSUE THREAD

**Issue by czd890** [influxdata/telegraf#15032]
### Relevant telegraf.conf

```toml
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "5s"
  logfile = "/telegraf_log.log"


[[outputs.influxdb]]
  urls = ["******"]
  database = "******"
  username = "******"
  password = "******"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
    Measurement = "win_cpu"
```

### Logs from Telegraf

```text
"2024-03-21T07:06:31Z I! Starting Telegraf 1.30.0 brought to you by InfluxData the makers of InfluxDB",
"2024-03-21T07:06:31Z I! Available plugins: 233 inputs, 9 aggregators, 31 processors, 24 parsers, 60 outputs, 5 secret-stores",
"2024-03-21T07:06:31Z I! Loaded inputs: win_perf_counters",
"2024-03-21T07:06:31Z I! Loaded aggregators: ",
"2024-03-21T07:06:31Z I! Loaded processors: ",
"2024-03-21T07:06:31Z I! Loaded secretstores: ",
"2024-03-21T07:06:31Z I! Loaded outputs: influxdb",
"2024-03-21T07:06:31Z I! Tags enabled: host=ip-172-17-66-139.ec2.internal",
"2024-03-21T07:06:31Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:\"ip-172-17-66-139.ec2.internal\", Flush Interval:5s",
"2024-03-21T07:06:31Z D! [agent] Initializing plugins",
"2024-03-21T07:06:31Z D! [agent] Connecting outputs",
"2024-03-21T07:06:31Z D! [agent] Attempting connection to [outputs.influxdb]",
"2024-03-21T07:06:31Z D! [agent] Successfully connected to outputs.influxdb",
"2024-03-21T07:06:31Z D! [agent] Starting service inputs",
"2024-03-21T07:06:36Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics",
"2024-03-21T07:06:36Z D! [inputs.win_perf_counters] Gathering from localhost",
"2024-03-21T07:06:36Z D! [inputs.win_perf_counters] Gathering from localhost finished in 0s",
"2024-03-21T07:06:40Z D! [inputs.win_perf_counters] Gathering from localhost",
"2024-03-21T07:06:40Z D! [inputs.win_perf_counters] Gathering from localhost finished in 1.1828ms",
```

### System info

windowsservercore-ltsc2022, telegraf-1.30.0

### Docker

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022

shell ["powershll"]
Run 
  Invoke-WebRequest https://dl.influxdata.com/telegraf/releases/telegraf-1.30.0_windows_amd64.zip -OutFile C:\test\telegraf.zip
  Expand-Archive C:\test\telegraf.zip -DestinationPath 'C:\Program Files\telegraf'
  New-Service -Name telegraf -BinaryPathName 'C:/Program Files/telegraf/telegraf-1.30.0/telegraf.exe --config c:\telegraf.conf' -StartupType Automatic

### Steps to reproduce

1. refer to docker

### Expected behavior

the telegraf-1.30.0 as the system service shoud be running on aspnet:4.8-windowsservercore-ltsc2022
 container.

### Actual behavior

event log:  A timeout was reached (30000 milliseconds) while waiting for the Telegraf Data Collector Service service to connect.

### Additional info

If we replace the telegraf-1.30.0 to telegraf-1.6.4, it's works.

**Comment by powersj** [comment]
Hi,

We do not provide support for windows containers, nor claim it will or should work. However, your telegraf logs look fine and are able to collect as expected.

> If we replace the telegraf-1.30.0 to telegraf-1.6.4, it's works.

:) 1.6.4 is many, many years old. Looking around I do see some issues with starting go services in windows containers: https://github.com/golang/go/issues/56335

I'm going to close this as there is nothing we can actively do to resolve this right now.

**Comment by maksagit** [comment]
The latest working version of Telegraf in the Windows docker container (mcr.microsoft.com/dotnet/framework/aspnet:4.8.1) is 1.25.0. 
Starting from version 1.25.1 the telegraf service does not start

**Comment by powersj** [comment]
@maksagit please see my last message - we do not support windows containers. If telegraf is not working there, then reproduce outside of the container and/or follow-up with the container author.
