### ISSUE TITLE
inputs.knx_listener is ignoring "String-Value" for 1Bit DPTs

### ISSUE THREAD

**Issue by userwithoutpassword** [influxdata/telegraf#15039]
### Use Case

Having correct Strings Value for 1Bit DPTs

### Expected behavior

https://github.com/vapourismo/knx-go/blob/master/knx/dpt/types_1.go

For each DPT 1.xxx Subtype there are Strings defined what means logical "0" and what means logical "1"
For example: DPT1.008 :   1 => "Down" and 0 => "Up"

Instead of writing "true und false" to the database it would be better writing these StringValues instead

### Actual behavior

All 1Bit DPTs are interpreted as boolean (false,true)

**Comment by powersj** [comment]
Hi,

> All 1Bit DPTs are interpreted as boolean (false,true)

Looking at the [listen](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/knx_listener/knx_listener.go#L177-L191) function it looks like we set the value based on what we receive from the knx-go library. Becuase the type is boolean, we will also return a boolean. Looking at your issue [from yesterday](https://github.com/vapourismo/knx-go/issues/81) it does look like there is a string field, but we do not call that.

@srebhan thoughts?

**Comment by srebhan** [comment]
@powersj I do agree, we just take what the library provides. Not sure on how to decide when to take the string...

**Comment by userwithoutpassword** [comment]
but the library also provides "String"

https://github.com/vapourismo/knx-go/blob/master/knx/dpt/types_1.go

**Comment by srebhan** [comment]
@userwithoutpassword so how do we decide when to take the "value" and when to take the "string"?

**Comment by userwithoutpassword** [comment]
I would say only use "string" for DPT 1.xxx

**Comment by srebhan** [comment]
@userwithoutpassword please test the binary in PR #15069 available once CI finished the tests! You need to set `as_string = true` for the `measurement`s you want to be represented as string... Let me know if this is what you intended!
