### ISSUE TITLE
Elasticsearch output cannot be used with data streams

### ISSUE THREAD

**Issue by cnemo-cenic** [influxdata/telegraf#15051]
### Use Case

Setup an index template and data stream in Elasticsearch. Configure Telegraf to index into Elasticsearch with the "create" optype.

### Expected behavior

Data ingests into Elasticsearch correctly.

### Actual behavior

Elasticsearch returns an error, because only the "create" operation type can be used with data streams (not the default "index" operation type).

### Additional info

https://github.com/olivere/elastic/issues/1464

>Indexing requests add documents to a data stream. These requests must use an op_type of create.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/set-up-a-data-stream.html

**Comment by powersj** [comment]
Need the CLA signed, then we can wrap up reviews of the PR. Thanks!

**Comment by cnemo-cenic** [comment]
@powersj Thanks. I definitely want that to happen, and I am optimistic it will be done at some point. But as of yet my employer has not been able to execute the decision.

**Comment by MartVisser** [comment]
Any update on this? I would like to use this feature.
