### ISSUE TITLE
Inputs.ClickHouse. Show all database.

### ISSUE THREAD

**Issue by Nebuc4adnezzar** [influxdata/telegraf#15062]
### Please direct all support questsions to slack or the forums. Thank you.

how do I transfer the metrics of all databases? By default, the metrics of two databases are transmitted: default and system. Thanks.

**Comment by srebhan** [comment]
@Nebuc4adnezzar this is a support question, please use the suggested channels (forum and Slack) and provide some more information on what you are trying to do (your expectations) and what you tried so far (your config).
