### ISSUE TITLE
`response_timeout` deprecated option for Prometheus input still broken

### ISSUE THREAD

**Issue by nick-kentik** [influxdata/telegraf#15076]
### Relevant telegraf.conf

```toml
[inputs.prometheus]
urls = ["http://localhost:8192"]
response_timeout = "5s"
```

### Logs from Telegraf

```text
$ telegraf --version
Telegraf 1.30.0 (git: HEAD@3c03ddcf)
$ telegraf --config test-config.conf --test --debug
2024-03-28T11:26:00Z I! Loading config: test-config.conf
2024-03-28T11:26:00Z E! error loading config file test-config.conf: error parsing prometheus, line 3: field corresponding to `response_timeout' in prometheus.Prometheus cannot be set through TOML
```

### System info

Telegraf 1.30.0, Linux AMD64 (Debian Bookworm)

### Docker

N/a

### Steps to reproduce

1. Try to run Telegraf against a prometheus input containing the deprecated (but not removed) `response_timeout` option
2. Observe failure
3. ???
...

### Expected behavior

The field is deprecated in favour of `timeout`, but not removed, so should continue to function.

### Actual behavior

Telegraf fails to start

### Additional info

Follow-up to https://github.com/influxdata/telegraf/issues/12859

I'm currently attempting an upgrade of Telegraf from the 1.21 series to latest across a fleet of hundreds of servers. Until this bug is fixed, there is no telegraf config that both supports a timeout for this input, and works across both versions, making the upgrade difficult to manage.

**Comment by nick-kentik** [comment]
OK @powersj, I think I've tracked down the problem here: the `Prometheus` type has two fields labeled with `response_timeout`. The toplevel [`ResponseTimeout`](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L77), and the one in the embedded [`HTTPClientConfig`](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L89) -> [`httpconfig.HTTPClientConfig.ResponseTimeout`](https://github.com/influxdata/telegraf/blob/master/plugins/common/http/config.go#L26)

I guess the solution is to remove the former and use the latter? I'll see how it looks in a PR.

**Comment by powersj** [comment]
Looks like v1.28.2 was the last working release. After that release https://github.com/influxdata/telegraf/pull/14153 landed which updated the HTTP Client config struct with a field also called `response_timeout`. Because the Prometheus plugin includes the HTTP client config struct there seems to be a conflict.

While I have put up #15078 with a potential solution, I need to chat with the team over the implications.

Thanks

**Comment by nick-kentik** [comment]
No worries, thanks for looking into it. If 1.28.2 works, I can take us that far and update the config after to remove the deprecated stuff, so that's enough to unblock me personally.

Hazards of falling so far behind!
