### ISSUE TITLE
Bug with metric_separator in Statsd input plugin

### ISSUE THREAD

**Issue by bogo666** [influxdata/telegraf#1507]
### Relevant telegraf.conf:
```
[[outputs.file]]
files = ["/tmp/metrics.out"]
data_format = "json"

[[inputs.statsd]]
service_address = ":8125"
delete_gauges = false
delete_counters = false
delete_sets = false
delete_timings = true
percentiles = [90]
*metric_separator = "!"*
parse_data_dog_tags = false
```
### System info:

OS: CentOS 7
Telegraf Version: 0.13.1
(Installed from Influxdata-provided stable RPM)

### Steps to reproduce:

1. Send metric to telegraf on localhost using Statsd protocol. The metric is a counter using name (containing field separators and periods): rad-proxy.localhost!acct!requests!start!by_nas!10.10.13.2

2. Read /tmp/metrics.out logfile and note the interpretation of both periods '.' and bangs '!':

{"fields":{"value":1},"name":"rad-proxy!localhost!acct!requests!start!by_nas!10!10!13!2","tags":{"host":"nbn-proxy.localhost","metric_type":"counter"},"timestamp":1468817910}

### Expected behavior:

When using a statsd configuration parameter for metric_separator for a character different from a period "." (e.g. bang "1"), the metric string should not interpret period "." characters as a field delimiter.

The JSON logline should have been:

{"fields":{"value":1},"name":"rad-proxy.localhost!acct!requests!start!by_nas!10.10.13.2","tags":{"host":"nbn-proxy.localhost","metric_type":"counter"},"timestamp":1468817910}

### Actual behavior:

The JSON logline contained:

{"fields":{"value":1},"name":"rad-proxy!localhost!acct!requests!start!by_nas!10!10!13!2","tags":{"host":"nbn-proxy.localhost","metric_type":"counter"},"timestamp":1468817910}

The string "rad-proxy.localhost" was incorrectly split into two fields, and the IP address "10.10.13.2" was incorrectly split into 4 fields.

### Additional info:

A diff of the source from the 0.13.1 release to master for the file plugins/inputs/statsd/statsd.go seems to indicate that this bug would apply to master.

**Comment by optimisticanshul** [comment]
@sparrc Is this because of this https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L514-L517

**Comment by sparrc** [comment]
nope, it's not, s.ConvertNames should be set to 'false' in this case so that shouldn't be relevant to this issue. It is most likely a bug in the graphite parser.

**Comment by sparrc** [comment]
I actually don't think that this is a bug, now that I've looked at the code.

The reason is that `metric_separator` actually refers to an _output_ metric separator.

In my understanding, graphite and statsd both have the limitation that a `.` is an input metric separator. This is a constant and adding support for arbitrary input separators would be a significant project.

@bogo666 can you provide an example of a statsd server which allows for arbitrary (ie, non-`.`) separators on the input-side?

I'm going to close this issue, but feel free to open a separate feature request if you think it's necessary for telegraf to support arbitrary metric separators.

**Comment by ushuz** [comment]
@sparrc A little bit off-topic, but why use `_` as default separator instead of `.`? Is `_` the recommended separator of influxdb?

**Comment by sparrc** [comment]
yep

**Comment by timbunce** [comment]
@sparrc what are the consequences of using a different separator in influxdb?

Using `_` seems strange to me when many of our metric names include underscores, so the individual metric names can't be separated out. Compare `mls_image_resizer_raw_img_get` with `mls.image_resizer.raw_img.get`.

I found [an article](http://techblog.shutl.com/2016/06/moving-from-graphite-to-influxdb/) that says:
> We also set the metric_separator to a dot. By default, Telegraf will replace the dot separators in statsd metrics with an underscore. This is easier to query in InfluxDB, but we found that keeping dots plays nicer with Grafana, which has a function to split measurement names on dots to construct labels for graphs.

As a novice that's more intriguing than helpful.

I'd appreciate an explanation of the pros/cons of `_` vs `.` vs `/` etc. In the form of an update to the docs would be great.

**Comment by sparrc** [comment]
there are no consequences, it's just the default, change it to `.` if it's easier for you, that's why the config option exists
