### ISSUE TITLE
inputs.systemd_units "Error in plugin: listing unit files failed" in v1.30.0 and v1.30.1

### ISSUE THREAD

**Issue by JamieSimon2** [influxdata/telegraf#15093]
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
  timeout = "3s"
  unittype = "service"
  interval = "20s"
  [inputs.systemd_units.tags]
    interval_type = "r0"
```

### Logs from Telegraf

```text
2024-04-02T17:15:00Z E! [inputs.systemd_units] Error in plugin: listing unit files failed: Rejected send message, 2 matched rules; type="method_call", sender=":1.584082" (uid=1003 pid=387836 comm="/usr/bin/telegraf -config /etc/telegraf/telegraf.c") interface="org.freedesktop.systemd1.Manager" member="ListUnitFilesByPatterns" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
```

### System info

OS: Centos 7, running systemd 219

### Docker

(OS details)
```
$ systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

$ ps -ef  |grep dbus
dbus        1537       1  0 Mar26 ?        00:09:36 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```

### Steps to reproduce

1. Configure telegraf with above input on Centos 7 host
2. Launch telegraf
3. Note logged errors
...

### Expected behavior

Expect no error for `inputs.systemd_units` plugin. :) 

### Actual behavior

Telegraf runs with other configured inputs normally, but fails to collect/send `inputs.systemd_units` data.

### Additional info

This bug follows https://github.com/influxdata/telegraf/issues/14980.

**Comment by JamieSimon2** [comment]
@srebhan as requested in https://github.com/influxdata/telegraf/issues/14980. Cheers and let us know if we can provide more details.

**Comment by JamieSimon2** [comment]
@srebhan I'm very grateful for your quick turnaround! I'm coordinating with my team to identify a host we can test PR #15108 on, I'll follow up here ASAP.

Centos7 is deprecated in our environment in favor of modern distributions. We identified this issue during a sweep to upgrade to "latest" for security compliance. We anticipate continued use of Centos7 for some time, as we upgrade/migrate, but I couldn't guess how long that will take. I want to acknowledge and appreciate your effort on this old-OS-issue. 🙏

**Comment by JamieSimon2** [comment]
@srebhan I've deployed `telegraf-1.31.0~ee0025ec-0.x86_64.rpm`, with 1-line config adjustment, to our pilot host and verified absence of `systemd_units` related errors in logs; operation appears normal. Unfortunately I can't access the Other Team's Grafana to view telegraf metrics yet, but will post updates when I can, or the Other Team confirms. 😁  

Have a great weekend!

**Comment by JamieSimon2** [comment]
@srebhan our Other Team confirmed data receipt & validity. The fix is good! 👍 
When may we expect release v1.31.0 to post to https://repos.influxdata.com/rhel/7/x86_64/stable/ ?
Again, thanks for your speedy and capable work.

**Comment by srebhan** [comment]
v1.31.0 is scheduled for [June 10th](https://github.com/influxdata/telegraf/milestone/106) until then you can use a nightly build _after_ the PR is merged...
