### ISSUE TITLE
Meaning of field `expiry`  is not clear

### ISSUE THREAD

**Issue by ibudasov** [influxdata/telegraf#15096]
### Please direct all support questsions to slack or the forums. Thank you.

Hi Telegraf,

I am creating this issue, because it took me some time to figure out what does `expiry` field of `inputs.x509_cert` means.
So i figured it out and created a related Pull Request, so other people would enjoy more detailed description.

I am creating this issue only to support my PR.

**Comment by powersj** [comment]
Closing as https://github.com/influxdata/telegraf/pull/15099 landed.
