### ISSUE TITLE
Input plugin http - Dynamique URL

### ISSUE THREAD

**Issue by blaik771** [influxdata/telegraf#15092]
### Use Case

Hello,

I'm not sure if I'm in the right place to express my concern/request. Currently, I'm using the "input.http" plugin to query a server's API. It works very well when I know the URL I need to query. However, there are times when I don't know the URL I need to query.

Let's say I own a cinema. To find out the number of viewers in my theater, I would query the following API: api/v1/CinemaRoom. This will return the names of my rooms, the names of my viewers, and their IDs for each room. However, to get details about the quality of a viewer's experience, I need to query a subpage of CinemaRoom, which is api/v1/CinemaRoom/userID. The issue is that userID is a random ID that I don't know in advance.

So, I'd like to know if there's a possibility to:

either query "api/v1/CinemaRoom/*"
or use a variable to query "api/v1/CinemaRoom/$ID"

### Expected behavior

either query "api/v1/CinemaRoom/*"
or use a variable to query "api/v1/CinemaRoom/$ID"

### Actual behavior

i can't...

**Comment by powersj** [comment]
Hi,

> use a variable to query "api/v1/CinemaRoom/$ID"

You can use an environment variable, but not any other type of variable.

> The issue is that userID is a random ID that I don't know in advance.

Based on your description it makes much more sense for you to use your own code to query and determine the URLs collect the data and then you could return that data to Telegraf to parse via the `exec` plugin. That plugin could call your code and parse the output. meaning you can still leverage Telegraf to collect at intervals, parse, and send metrics.

**Comment by powersj** [comment]
> Is it not possible to use a tag that I've retrieved in a previous query?

Unfortunately, not. Inputs all run at the same time and are not able to pass information between each other, including metrics.
