### ISSUE TITLE
[outputs.sql] support MySQL drivers?

### ISSUE THREAD

**Issue by JW623** [influxdata/telegraf#15101]
### Please direct all support questsions to slack or the forums. Thank you.

I have read some documents [outputs.sql] supports MySQL driver, but how do i setting it up?

**Comment by srebhan** [comment]
@JW623 without any further information it is hard to tell how to help you. What did you try? Do you see an error message?
As a starting point, you could read the [documentation of the plugin]()...

```toml
[[outputs.sql]]
  driver = "mysql"
  ...
```

**Comment by JW623** [comment]
Hi sorry for not including my code. I have configured this inside my telegraf.
[[outputs.mysql]]
  driver = "mysql"
  dsn = "tcp://root:P@ssw0rd@localhost:3306/telegraf"
  table = "metrics"

and the return error is:
E! error loading config file telegraf.conf: error parsing mysql array, undefined but requested output: mysql

**Comment by powersj** [comment]
@JW623,

Please stop using GitHub issues for support. You have been told in previous issue as well and the bot reminds you to use the slack and/or forums instead.

> error parsing mysql array, undefined but requested output: mysql

This tells you exactly what is wrong. There is no msql output! There is an `sql` output.
