### ISSUE TITLE
[inputs.systemd_units] cpu usage goes through the roof!

### ISSUE THREAD

**Issue by electrofloat** [influxdata/telegraf#15104]
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
```

### Logs from Telegraf

```text
-
```

### System info

Ubuntu 22.04

### Steps to reproduce

Start telegraf with [inputs.systemd_units] used.

### Expected behavior

Same cpu usage as before.

### Actual behavior

With the new implementation of systemd_units, every time telegraf runs (which is every 10s), a systemd process eats a lot of cpu.

Attached 2 picture of grafana graphs, I think you can guess when I upgraded to 1.30.1. I've just reverted it back again to 1.29.5-1.

![Screenshot from 2024-04-04 16-35-19](https://github.com/influxdata/telegraf/assets/477252/a6551b83-216b-4b46-976a-4a0a884670bf)

![Screenshot from 2024-04-04 16-35-41](https://github.com/influxdata/telegraf/assets/477252/ee7cc4af-54fc-40d7-b5cd-3fcdcbe3e1c8)

**Comment by srebhan** [comment]
@electrofloat thanks for reporting the issue! During the rewrite we also added some features like reporting disabled/unloaded units and my guess would be that this causes the issue. Could you assist in debugging the issue by testing some PR binaries?

**Comment by electrofloat** [comment]
@srebhan I can try, yes.

**Comment by srebhan** [comment]
@electrofloat thanks! Can you please test the binary in PR #15108 available after CI finished the tests?!? Please set the new option `loaded_only` to `true` and let me know if this helps!

**Comment by electrofloat** [comment]
It is better. Instead of about 100%, It only causes the PID1 systemd process to use about 15% cpu every 10 secibds, but v1.29.5-1 uses 0%. (I've just checked)

**Comment by srebhan** [comment]
@electrofloat I added another optimization, can you please test the binary in the PR when CI finished the tests!? Let me know if this reduces the load further...

**Comment by electrofloat** [comment]
It seems much better now. Seems the systemd process stays at 0%, with the `loaded_only` `true` option. I haven't tested whether it still provides the exact same metrics as before or not, only tested the cpu usage.

Also.. shouldn't the new option default to true? So that it works exactly like before the rewrite, and people don't have to change anything in the config to stay with the previous (before rewrite) behavior?

**Comment by srebhan** [comment]
@electrofloat will discuss it with the team as unfortunately we released 1.30. with the behavior being to also report non-loaded units...

**Comment by srebhan** [comment]
@electrofloat we decided to revert to the pre-v1.30.0 behavior and I adapted the PR accordingly. Could you please test it again, just to be sure!? Please note that the option now is inverted and no longer called `loaded_only` but `collect_disabled_units`.

**Comment by electrofloat** [comment]
Yes, it seems to be working as expected now, without any config change.
