### ISSUE TITLE
inputs.sysstat setting a very long interval for sadc following a SIGHUP

### ISSUE THREAD

**Issue by nick-kentik** [influxdata/telegraf#15102]
### Relevant telegraf.conf

```toml
[[inputs.sysstat]]
  alias = "sysstat"
  sadc_path ="/usr/lib/sysstat/sadc"
  group = true
  [inputs.sysstat.options]
    -B = "paging"
    -q = "queue"
```

### Logs from Telegraf

No logs; I'm tracking down a "telegraf stops outputting metrics" kind of bug in v1.27.4 which seems to occur shortly after a reload. I've noticed this bug, but don't know if it's causing that behaviour or not yet.

### System info

Telegraf 1.27.4, Debian Bullseye

### Steps to reproduce

1. Run telegraf with the sysstat plugin enabled
2. Reload telegraf after some time; wait some more time
3. `ps aux | grep sadc`

### Expected behavior

`sysstat` should only run `sadc` with a reasonable interval - 29 seconds seems the norm. E.g.:

```
telegraf 1070266  0.0  0.0   6904  2224 ?        S    10:36   0:00 /usr/lib/sysstat/sadc -S DISK 29 2 /tmp/sysstat-3353205380
```

### Actual behavior

What we actually see is something more like:

```
telegraf 1363512  0.0  0.0   6896  2240 ?        S    10:34   0:00 /usr/lib/sysstat/sadc -S DISK 7185 2 /tmp/sysstat-1840924743
```

### Additional info

The relevant code: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sysstat/sysstat.go

I think that what's happening here is that the package-global variable `firstTimestamp` is not interacting well with config being reloaded. Let's walk through it:

The first run, `SadcInterval` is set to 0 (default value), so on line 109, we store `time.Now()` into `firstTimestamp`.

The second run, we store a value into `s.interval` on line 111; subsequent runs skip this block entirely, since `s.interval` is no longer zero.

Let's throw a reload into the mix - say two hours later. Now `s.interval` is zero again (since we have a new instance of `*sysstat.Sysstat`, but `firstTimestamp` is still `time.Now() - (2 * time.Hour)`. So we hit line 111 again and set `s.interval` to two hours plus 0.5 seconds.

Down in gather, on line 153, we use `s.interval` to calculate a timeout for the command (we cut a second off it - `parseInterval` - to allow time for parsing). We then use this "two hours, plus half a second, minus a second" value to calculate the timeout for the command, and the argument to sadc itself.

The run *after* this one, everything is back to normal again - until another reload shows up. Each reload, we go through this path again, and the value for `time.Since` stretches longer and longer. At a minimum, this cripples the `sysstat` plugin, and there's a chance it's responsible for crippling the entire telegraf process too.

I think there's a configuration workaround, which is to hardcode an `SadcInterval`. This way, `s.interval` will never be 0 and so the value of `firstTimestamp` will never be used. I'm about to try that now, but figured it was worth reporting this ASAP.

In terms of a fix, just pulling the package-global variables into the config struct should sort it?

I guess it's also possible that the context-cancelling `Gather()` proposed in https://github.com/influxdata/telegraf/issues/13913 would have helped to mitigate this, so it might be worth having another look at that proposal.

**Comment by powersj** [comment]
Hi @nick-kentik,

> I think there's a configuration workaround, which is to hardcode an SadcInterval. This way, s.interval will never be 0 and so the value of firstTimestamp will never be used. I'm about to try that now, but figured it was worth reporting this ASAP.

What did you find out with this?

> In terms of a fix, just pulling the package-global variables into the config struct should sort it?

Were you able to try this as well? Or would you be willing to put up a PR with this change?

Thanks!

**Comment by powersj** [comment]
> we're trying hard to return to the upstream codebase after living with a fork for several years

Heh please feel free to file issues or put up PRs for other changes.

>  I could try for a PR next week, though - it shouldn't be too difficult to add a test case for the condition.

Please do! Thanks!

**Comment by nick-kentik** [comment]
PR created in https://github.com/influxdata/telegraf/pull/15212 - this issue isn't completed until that is merged.
