### ISSUE TITLE
docs: create a documentation for agent

### ISSUE THREAD

**Issue by RodrigoDornelles** [influxdata/telegraf#15118]
I find it interesting, just as inputs and outpus have their README, create one in the /agents folder to explain the settings in .conf code snippet.

* <https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent>

**Comment by srebhan** [comment]
@RodrigoDornelles PRs are welcome!

**Comment by powersj** [comment]
@RodrigoDornelles,

> create one in the /agents folder to explain the settings in .conf

Hmm I wouldn't expect users to go into the agent folder looking for docs on agent configuration details. As you point out the agent configuration details are in the configuration document. Otherwise we get into a situation where the values are documented in two places.

Is that all you were looking for or are you also looking for more details on the agent itself?

**Comment by RodrigoDornelles** [comment]
> @RodrigoDornelles,
> 
> > create one in the /agents folder to explain the settings in .conf
> 
> Hmm I wouldn't expect users to go into the agent folder looking for docs on agent configuration details. As you point out the agent configuration details are in the configuration document. Otherwise we get into a situation where the values are documented in two places.
> 
> Is that all you were looking for or are you also looking for more details on the agent itself?

I really liked having README.md in the source code directories, it was guiding me through the source what I needed.

Yes, this is a good part of what I needed in this configuration file.

To do something non-redundant, my suggestion is to put an example with fictitious fields and a short brief about it, and a link to this configuration documentation.

**Comment by powersj** [comment]
I'm not sure what you are after by adding fictitious fields, but I have put up #15150. You are free to comment on that or improve upon it.
