### ISSUE TITLE
Add metrics to monitor SQL Server Persistent Version Store (PVS) within Accelerated Database Recovery (ADR)

### ISSUE THREAD

**Issue by crenstrom** [influxdata/telegraf#15136]
### Use Case

Accelerated Database Recovery (ADR) was added in SQL Server version 2019 and utilizes the Persistent Version Store to store data.  Usage of the storage grows and shrinks with use.  Monitoring the size and usage is helpful for understanding overall database size and use distribution, as well as identifying and troubleshooting ADR-related performance problems.

### Expected behavior

Metrics about Persistent Version Store are collected from DMV sys.dm_tran_persistent_version_store_stats, along with some relevant database information from sys.databases.

### Actual behavior

Currently, these metrics are not collected by telegraf.

### Additional info

I have written and tested the code successfully and plan to submit it to the project.  I'm following the CONTRIBUTING.md documentation to figure out how to do that.

**Comment by powersj** [comment]
Hi,

> I have written and tested the code successfully and plan to submit it to the project. I'm following the CONTRIBUTING.md documentation to figure out how to do that.

Thank you! Look forward to seeing your PR!
