### ISSUE TITLE
jolokia2_agent cassandra example config missing per table and all table metrics

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [influxdata/telegraf#15139]
### Use Case

if you want to collect metrics on a per table or all tables aggregated, you need to add additional configuration to the example telegraf jolokia2_agent cassandra.conf file (telegraf/plugins/inputs/jolokia2_agent/examples/cassandra.conf)### 

### Expected behavior

adding additional configuration should result in more metrics being collected as per https://cassandra.apache.org/doc/3.11/cassandra/operating/metrics.html#table-metrics

### Actual behavior

you get the additional metrics listed https://cassandra.apache.org/doc/3.11/cassandra/operating/metrics.html#table-metrics for each table in your Cassandra cluster. And separately as aggregate metrics for "all" tables

### Additional info

the following are what need to be added to example cassandra configuration. I would suggest leaving them commented out indicate that they can be optional enabled if per table metrics are desired (which can be a significant amount of metrics as there are 65 stats/metrics per table)
```
  [[inputs.jolokia2_agent.metric]]
    name  = "Table"
    mbean = "org.apache.cassandra.metrics:name=*,keyspace=*,scope=*,type=Table"
    tag_keys = ["name","scope","keyspace"]
    field_prefix = "$1_"

  [[inputs.jolokia2_agent.metric]]
    name  = "TableAll"
    mbean = "org.apache.cassandra.metrics:name=*,type=Table"
    tag_keys = ["name"]
    field_prefix = "$1_"
```

**Comment by powersj** [comment]
Hi,

Happy to see a PR to add this to the docs. Are you willing to add this to the docs for folks to use in the future?

Thanks!
