### ISSUE TITLE
Add Ceph Cluster Performance Statistics

### ISSUE THREAD

**Issue by spjmurray** [influxdata/telegraf#1513]
## Feature Request

Add Ceph Cluster Performance Statistics

### Current behavior:

The ceph plugin is only concerned with a small set of data available from the admin socket.

### Desired behavior:

Things like `ceph status`, `ceph df` and `ceph osd pg stat` gives a far richer set of performance metrics, e.g. placement group states, IOPs/read/writes on a global and per pool basis.

### Use case: [Why is this important (helps with prioritizing requests)]

We rely on this for road map capacity planning, maintenance window schedule planning, performance profiling, spotting errors etc.

![What we need](http://www.incubator.datacentred.io/telegraf-ceph.png)

**Comment by spjmurray** [comment]
FYI that image was a live capture of a real CRUSH map update, and exactly what we want to see!

**Comment by Buhrietoe** [comment]
I made a similar thing here if it is of use: https://github.com/Buhrietoe/ceph-metrics
It just uses the exec plugin. We use it here in production in a container. It can be easily extended and supports multiple clusters (although serially). Dump mycluster.conf and mycluster.keyring into /etc/ceph/clusters/

**Comment by allen13** [comment]
Using the supported ceph python library really makes things a lot easier on the implementation side. It would be nice if someone could do a pure go implementation but @Buhrietoe's solution is completely functional in the meantime.

**Comment by aderumier** [comment]
@spjmurray  Very nice plugin. Could you share your grafana dashboard ?

**Comment by spjmurray** [comment]
@aderumier Sorry this took so long!

https://gist.github.com/spjmurray/41a6cf650a725ae21729af9e9b12697e
