### ISSUE TITLE
add power_limit to nvidia_smi

### ISSUE THREAD

**Issue by jpvlerbe** [influxdata/telegraf#15142]
### Use Case

To get the usage of the gpu I would like to use the percentage of power used. So from the output of nvidia-smi power_draw/power_limit

This seems to be a better metric to show usage than either the ram usage or gpu usage.

### Expected behavior

next to power_draw include power_limit field

### Actual behavior

only power_draw is included

### Additional info

Or can somehow add this to the configuration?

**Comment by powersj** [comment]
Hi,

Please provide the output of `/usr/bin/nvidia-smi -q -x` so we can see an example.

In v12 I see [numerous power limit fields](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nvidia_smi/testdata/rtx-3080-v12.xml#L188-L192).

Thanks

**Comment by jpvlerbe** [comment]
I am referring to this metric
![image](https://github.com/influxdata/telegraf/assets/45239736/4e71dfdd-56f2-4e60-bb85-220cc67184c6)

which I am assuming corresponds to current_power_limit

I tried with fieldinclude=["current_power_limit"] but I am guessing that does not work as it is not in the list from the README or in parser.go (probably adding a line after line 80?)

**Comment by powersj** [comment]
@jpvlerbe I need you to run the nvidia-smi command above and get the output. Telegraf does not parse that table output, but instead the output from that command. I need to see what is available from the data that telegraf can see.

FWIW that 350W is the total cap value. Not something I would expect to see change.

**Comment by jpvlerbe** [comment]
`$ nvidia-smi -q -x | grep power                                                                                                                                                                    <clocks_throttle_reason_sw_power_cap>Not Active</clocks_throttle_reason_sw_power_cap>                                                                                                         <clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>                                                                           <power_readings>                                                                                                                                                                                      <power_state>P8</power_state>                                                                                                                                                                 <power_management>Supported</power_management>                                                                                                                                                <power_draw>35.32 W</power_draw>                                                                                                                                                              <power_limit>420.00 W</power_limit>                                                                                                                                                           <default_power_limit>420.00 W</default_power_limit>                                                                                                                                           <enforced_power_limit>420.00 W</enforced_power_limit>                                                                                                                                         <min_power_limit>100.00 W</min_power_limit>                                                                                                                                                   <max_power_limit>450.00 W</max_power_limit>                                                                                                                                           </power_readings>                                                                                                                                                                                     <clocks_throttle_reason_sw_power_cap>Active</clocks_throttle_reason_sw_power_cap>                                                                                                             <clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>                                                                           <power_readings>                                                                                                                                                                                      <power_state>P8</power_state>                                                                                                                                                                 <power_management>Supported</power_management>                                                                                                                                                <power_draw>28.49 W</power_draw>                                                                                                                                                              <power_limit>350.00 W</power_limit>                                                                                                                                                           <default_power_limit>350.00 W</default_power_limit>                                                                                                                                           <enforced_power_limit>350.00 W</enforced_power_limit>                                                                                                                                         <min_power_limit>100.00 W</min_power_limit>                                                                                                                                                   <max_power_limit>365.00 W</max_power_limit>                                                                                                                                           </power_readings>  `

I have 2 GPUs btw

**Comment by jpvlerbe** [comment]
`$ nvidia-smi -q -x | grep power
                        <clocks_throttle_reason_sw_power_cap>Not Active</clocks_throttle_reason_sw_power_cap>
                        <clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>
                <power_readings>
                        <power_state>P8</power_state>
                        <power_management>Supported</power_management>
                        <power_draw>35.32 W</power_draw>
                        <power_limit>420.00 W</power_limit>
                        <default_power_limit>420.00 W</default_power_limit>
                        <enforced_power_limit>420.00 W</enforced_power_limit>
                        <min_power_limit>100.00 W</min_power_limit>
                        <max_power_limit>450.00 W</max_power_limit>
                </power_readings>
                        <clocks_throttle_reason_sw_power_cap>Active</clocks_throttle_reason_sw_power_cap>
                        <clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>
                <power_readings>
                        <power_state>P8</power_state>
                        <power_management>Supported</power_management>
                        <power_draw>28.49 W</power_draw>
                        <power_limit>350.00 W</power_limit>
                        <default_power_limit>350.00 W</default_power_limit>
                        <enforced_power_limit>350.00 W</enforced_power_limit>
                        <min_power_limit>100.00 W</min_power_limit>
                        <max_power_limit>365.00 W</max_power_limit>
                </power_readings>`

I have 2 gpu's btw

**Comment by powersj** [comment]
> I guess this is the v11 scheme, and the limit I am after is "power_limit"

You are making this harder than it needs to be with all these edits ;) just copy and paste without grep would have answered everything I need. 

In ~30mins from this post, there will be artifacts in https://github.com/influxdata/telegraf/pull/15144 attached as a comment. Please download one of them and ensure the new power_limit field shows up.
