### ISSUE TITLE
the gnmi input plugin should support the gRPC Keepalive configuration

### ISSUE THREAD

**Issue by retnuh** [influxdata/telegraf#15148]
### Use Case

When the service on the target end of a gnmi subscription becomes unavailable, "on change" gnmi subscriptions won't notice and won't attempt to reconnect until 2 hours after the last data was received.

The gRPC library already contains functionality to address these issues:
https://pkg.go.dev/google.golang.org/grpc/keepalive

### Expected behavior

the gRPC library supports keep alive configuration to handle this appropriately; exposing this configuration will allow the telegraf end user to customize the behaviour of their gRPC connections.

### Actual behavior

Currently there is no way to configure the keep alive behaviour of gRPC connections.

**Comment by powersj** [comment]
next steps: get final reviews in 15149, thanks again for the PR
