### ISSUE TITLE
Add Process Filter Rule Type

### ISSUE THREAD

**Issue by moonyoungCHAE** [influxdata/telegraf#15152]
### Use Case

In some metrics (like log data), it requires inclusion filtering, not exact matching of fields or tags.
(Or regex filtering could be the another solution.)

Input
```
message="user name=bob, phone_numbe=12345678"
message="user request input"
```

### Expected behavior

Filter metric by inclusion or regex.

Output
`message="user request input"`

### Actual behavior

Currently there is no way to filter by inclusion or regex.

### Additional info

If this feature seems appropriate, I'd like to contribute. :)

**Comment by srebhan** [comment]
@moonyoungCHAE any reason why a [`metricpass` filter](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#selectors) is not sufficient? For regexp you could also use the [`regexp` processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex) and set a filtering tag to afterwards use `tagexclude`/`taginclude`...
