### ISSUE TITLE
Unix domain socket listener

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1516]
### Proposal:

Similar to the tcp_listener and udp_listener input plugins, it would be useful to have a unix_listener input plugin.
### Current behavior:

No unix domain socket listener.
### Desired behavior:

Have a unix domain socket listener.
### Use case: [Why is this important (helps with prioritizing requests)]

The main benefit of a unix domain listener over a tcp listener on 127.0.0.1 is access control. Permissions of who can write to the unix domain socket can be controlled. With the tcp listener, anyone on the server could submit metrics, possibly polluting, poisoning, or overwhelming the output database.

I'd be willing to write this. It'd be very trivial to do, just wanted to open the idea up here first.

**Comment by sparrc** [comment]
please do! 👍

**Comment by schotlandzegtja** [comment]
This sounds very useful.
