### ISSUE TITLE
[gNMI plugin] Add Secretstores support for device username and password

### ISSUE THREAD

**Issue by mrhorrible78** [influxdata/telegraf#15172]
### Use Case

The credentials used to connect to a device via the gNMI plugin are stored in clear text in the telegraf.conf file.  It would be great if the username and password were able to be stored as secrets instead.  In my specific use case, I'd like to use docker secrets.

### Expected behavior

The gNMI plugin should support secretstores for device usernames and passwords

### Actual behavior

Currently, usernames and passwords are stored in clear text within the configuration file.

**Comment by powersj** [comment]
Hi,

I've put up PR #15172 which adds support to secret stores to the username and password config files. In 20-30mins downloadable artifacts will be attached to the PR. Could you please download them and ensure it works?

Thanks!

**Comment by mrhorrible78** [comment]
> Hi,
> 
> I've put up PR #15172 which adds support to secret stores to the username and password config files. In 20-30mins downloadable artifacts will be attached to the PR. Could you please download them and ensure it works?
> 
> Thanks!

I grabbed the telegraf_1.31.0~9f169c21-0_amd64.deb, created a container, and tested the Docker secretstore function and it works for my use case.  Thank you for the quick turn around on this feature request!
