### ISSUE TITLE
Support Kafka output graceful failure & retry

### ISSUE THREAD

**Issue by gfletcherMerc** [influxdata/telegraf#15181]
### Use Case

[#12111](https://github.com/influxdata/telegraf/pull/12111) implemented support for graceful failure & retry for the kafka_consumer input plugin.

As part of this, support for the following config entries were added to the kafka_consumer input plugin:

metadata_retry_max
metadata_retry_type
metadata_retry_backoff
metadata_retry_max_duration

These are settings supported the the sarama Kafka library and were exposed for use. The majority of the 'meat' behind this PR was introduced into the common/kafka plugin, which is also shared by the output kafka plugin.

The settings seem to be usable by the kafka output plugin, so is the kafka output plugin already tolerant to kafka connection failures?  Perhaps this is simply a documentation update?

### Expected behavior

metadata_retry options are usable for kafka output plugin.
Documentation describes the metadata_retry options.

### Actual behavior

Documentation does not describe the metadata_retry options.

**Comment by powersj** [comment]
@gfletcherMerc,

I believe you are correct, in that this is only a doc update that is required. It appears that #12111 added the option to the common options, which means both the input and output can make use of those config options.

I've put up #15182, which adds the config options to the output's sample configuration.
