### ISSUE TITLE
inputs.snmp gosmi path

### ISSUE THREAD

**Issue by luweijun1992** [influxdata/telegraf#15218]
### Please direct all support questsions to slack or the forums. Thank you.

The following information, manufacturer mibs independent folder
Can I set the mibs path to the top-level directory?
```
path = ["/opt/telegraf/mibs"]
```
![image](https://github.com/influxdata/telegraf/assets/58923704/d353275b-0f11-46ef-8727-e310950a4420)

**Comment by srebhan** [comment]
@luweijun1992 yes. Please use the suggested support channels for this kind of questions to help us keeping the issues as exactly this, issues.
