### ISSUE TITLE
[opentelemetry input plugin] grpc: received message larger than max

### ISSUE THREAD

**Issue by rainbowwiki** [influxdata/telegraf#15230]
### Use Case

 client send opentelemetry to telegraf

### Expected behavior

telegraf can receive the opentelemetry metrics

### Actual behavior

Thu, 25 Apr 2024 12:48:54 GMT - severe: [telemetry.OpenTelemetry_Exporter.f5telemetry_default::My_Consumer] error: Service request
Thu, 25 Apr 2024 12:48:54 GMT - severe: [telemetry.OpenTelemetry_Exporter.f5telemetry_default::My_Consumer] Error on attempt to send metrics:
Traceback:
Error: 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (7560819 vs. 4194304)

### Additional info

How can I adjust the max size for opentelemetry plugin?

**Comment by powersj** [comment]
Hi,

Those logs do not look like Telegraf logs, but instead the logs from your exporter service?

Can you please share your telegraf logs and config please.

**Comment by powersj** [comment]
Please share your logs and config, you can omit any IP addresses or secrets.

**Comment by rainbowwiki** [comment]
this is my config, telegraf side no log

**Comment by powersj** [comment]
Thanks for the config

> telegraf side no log

Your config has logs sent here:

> logtarget = "file"
> logfile = "/var/log/telegraf/telegraf.log"

I have also put up #15231 which introduces a new option called `max_msg_size`. In 30mins after this message, artifacts should be attached to that PR that you can download and try. Please let me know if setting that value to something like "8MB" or higher helps out.

**Comment by rainbowwiki** [comment]
thanks for your support! will test and give you feedback~

**Comment by powersj** [comment]
@rainbowwiki have you had a chance to give the PR a try? Thanks!

**Comment by rainbowwiki** [comment]
@powersj  Hi man, sorry for the message delay, we tryed and work now, thanks!

**Comment by powersj** [comment]
Thanks for confirming!
