### ISSUE TITLE
Add field templating (opcua)

### ISSUE THREAD

**Issue by JeroenVanHoye** [influxdata/telegraf#15253]
### Use Case

Logging many measurements with the same fields.

### Expected behavior

Behave like "default_tags" configuration.

### Actual behavior

You have to repeat all fields for each measurement.

### Additional info

With opcua we monitor objects that have the same fields each time. In opcua config I use groups to define a measurement name and add some fields to this measurement. The address-indentifiers contain the name of the measurement. So if you could define one field list for an object and make it repeat the template for each measurement while replacing the measurement name. This would make configuring measurements much easier and less prone to typo's.

I could see this feature work for modbus as well, define a type of energy meter and its addresses once and just define a measurement and add the field template to it.

**Comment by srebhan** [comment]
@JeroenVanHoye please use templates and generate the config using an external tool to achieve this! Adding this kind of complexity to Telegraf is currently not planned.

**Comment by JeroenVanHoye** [comment]
Hi,
Thanks for the feedback.
I know templating can be a complex matter, that's why I proposed to integrate it in telegraf itself. To make is less complex for others that have to work on my configuration in the future.
We have an old internal tool to generate text that is not well maintained, do you have any suggestions on easy to use config generators? (not easy to find on google since every time you use the term "text generator" it floods the page with AI/GPT applications)

**Comment by powersj** [comment]
Hi,

> I know templating can be a complex matter, that's why I proposed to integrate it in telegraf itself.

It is definitely a complex issue that can spiral into a huge amount of combinations. This is why we have generally said no to these types of requests and instead pointed users at software like [ansible](https://docs.ansible.com/) and/or [jinja](https://jinja.palletsprojects.com/en/3.1.x/). Jinja is a very popular templating engine. Ansible offers full blown automation and even jinja templating as a part of it as well.
