### ISSUE TITLE
Ubuntu 24.04 Noble Numbat packages

### ISSUE THREAD

**Issue by sblaisot** [influxdata/telegraf#15281]
### Use Case

Ubuntu 24.04 is publicly released. I want to install Telegraf on Ubuntu 24.04 servers from influxdata repositories

### Expected behavior

Available packages for Ubuntu 24.04 Noble Numbat in influxdata repositories

### Actual behavior

No support for Ubuntu 24.04 in influx data repositories : https://repos.influxdata.com/ubuntu/dists/

### Additional info

Do you plan to release packages for Ubuntu 24.04? Do you have an eta for these packages?

**Comment by sblaisot** [comment]
Oh, I missed the changes in the installation instructions and it works with `deb https://repos.influxdata.com/ubuntu stable main` so I'm closing this issue

**Comment by slm0n87** [comment]
@sblaisot , the official install docs currently pointing to "https://repos.influxdata.com/debian stable main" for "Ubuntu 20.04 LTS and newer"
Do you know what ubuntu users now should use?

**Comment by hackery** [comment]
According to https://repos.influxdata.com/ we should be using `https://repos.influxdata.com/debian stable main` for all Debian-based releases regardless of distribution or codename.
Browsing the repo, these lead to the same packages.
(It would still be good if they included the link for `noble` as for previous codenames)
