### ISSUE TITLE
Windows performance counter "CPU Wait Time Per Dispatch" return wrong value.

### ISSUE THREAD

**Issue by rainqt** [influxdata/telegraf#1528]
## Bug report

telegraf always return wrong value (100) from counter "Hyper-V Hypervisor Virtual Processor(*)\CPU Wait Time Per Dispatch"
### Relevant telegraf.conf:

default config
[[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Hypervisor Virtual Processor"
    Counters = ["% Guest Run Time","% Hypervisor Run Time","% Total Run Time","CPU Wait Time Per Dispatch"]
    Instances = ["*"]
    Measurement = "hyperv_vcpu"
    IncludeTotal=false
### System info:

telegraf 0.13.1
telegraf 1.0.0 beta3
OS: Windows server 2012 R2, hyper-v role installed.
### Steps to reproduce:
1. try to collect data from counters "Hyper-V Hypervisor Virtual Processor(_)\CPU Wait Time Per Dispatch" or "Hyper-V Hypervisor Root Virtual Processor(_)\CPU Wait Time Per Dispatch"
### Expected behavior:

should return the correct value
### Actual behavior:

telegraf always return "100"

**Comment by lucadistefano** [comment]
this may be the same of #1291 point 2 and #2483

**Comment by danielnelson** [comment]
I think it is likely that this was fixed by #2483.  @rainqt can you retest?  If needed, you can get a nightly build here 
https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_windows_amd64.zip

**Comment by rainqt** [comment]
@danielnelson, i retest on nightly build and telegraf returns the correct data. Works great!
