### ISSUE TITLE
add option to disable procstat memory map collection 

### ISSUE THREAD

**Issue by shenghaoyang** [influxdata/telegraf#15295]
### Use Case

PR #13779 added memory map collection via `/proc/pid/smaps` for processes monitored using the procstat plugin on Linux to provide enhanced memory utilization statistics.

However, memory map collection via `/proc/pid/smaps` for processes with many mappings (where reading `smaps` takes upwards of _seconds_) causes `mmap_sem` for the target process to be read locked for extended periods of time.

These long lived read locks can stall VM intensive applications - in our workload a memory map change via `mmap` attempts to write lock `mmap_sem` while Telegraf has it read locked, after which all other threads in the application block as soon as they take a page fault.

See https://nelhagedebugsshit.tumblr.com/post/140317144518/when-observing-your-database-stalls-it for more details.

### Expected behavior

Telegraf provides an option to skip the body of [collectMemmap](https://github.com/influxdata/telegraf/blob/7966827530f5180a54214067545f1218c7a100a4/plugins/inputs/procstat/os_linux.go#L25) for Linux hosts.

### Actual behavior

Telegraf has no such option.

**Comment by srebhan** [comment]
@shenghaoyang please check the binary in PR #15299, available as soon as CI finished the tests, and let me know if this is what you intented. For your use-case you should add `properties = ["cpu", "limits", "memory"]` to the`inputs.procstat` section of your config with the PR above and omit the `mmap` property...

**Comment by shenghaoyang** [comment]
Thanks @srebhan!

We've tested that those are working as expected - we can't see Telegraf reading memory maps anymore after removing `mmap` from the set of collected properties  🎉
