### ISSUE TITLE
improve documentation for postgres input

### ISSUE THREAD

**Issue by tcurdt** [influxdata/telegraf#15296]
### Please direct all support questsions to slack or the forums. Thank you.

There is no better issue type.

The postgres plugin does not specify what permissions the database user needs as a minimum. But this should be covered in the docs:

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql/README.md

Please add this.

**Comment by powersj** [comment]
> There is no better issue type.

Well the support option really isn't mean to be used, but rather get you to go ask your question else where ;) I'd happily take a bug or a feature request for doc updates.

> Please add this.

Do you happen to know the answer? 

Based on a quick search it looks like this is limited to `pg_stat_database` per [the docs](https://www.postgresql.org/docs/current/predefined-roles.html) to get access to the `pg_stat_*` views. Does that align with what you see?

Will you put up a PR with this update?

**Comment by tcurdt** [comment]
> Well the support option really isn't mean to be used, but rather get you to go ask your question else where ;) 

But it really isn't a question of that sort :)

> I'd happily take a bug or a feature request for doc updates.

The structure of the template didn't really lend itself to those types. Maybe worth adding another issue type?

> Do you happen to know the answer?

Unfortunately I don't

> Based on a quick search it looks like this is limited to pg_stat_database per [the docs](https://www.postgresql.org/docs/current/predefined-roles.html) to get access to the pg_stat_* views. Does that align with what you see?

That's also what I found. But I could not figure out to what permission this translates to.
I suspect "SELECT"?

But I had trouble with that - but that might have been me doing something wrong.

> Will you put up a PR with this update?

I would - but I still don't know the answer.

**Comment by powersj** [comment]
> That's also what I found. But I could not figure out to what permission this translates to.
I suspect "SELECT"?

I would suggest first, always looking at the Postgres docs, which are incredibly detailed. In this case, it looks like [there are a number of different roles](https://www.postgresql.org/docs/10/default-roles.html) that are available for monitoring the pg_stat.* views.

Then you can take whatever role you want and grant it to the user + access to that database as it states at the end:

```sql
GRANT pg_read_all_stats TO <user>;
```

Does that work?

**Comment by tcurdt** [comment]
I didn't find the predefined roles, thanks for digging that up.

Question remains whether it needs to be `pg_read_all_stats` or `pg_monitor`.
And it also sounds like this will give monitoring access to all databases? (which would be fine)

For now I have given full privileges to the `telegraf` user. Would be nice to revisit this.

**Comment by powersj** [comment]
> Question remains whether it needs to be pg_read_all_stats or pg_monitor.

I'm not sure why you say this. As I said, the plugin only reads from `pg_stat_*`, specifically `pg_stat_database` and `pg_stat_bgwriter`. As the postgres docs say:

* pg_read_all_stats: Read all pg_stat_* views
* pg_monitor: ... this role is a member of pg_read_all_settings, ..

You probably only need to give it `pg_read_all_stats`.

**Comment by tcurdt** [comment]
> > Question remains whether it needs to be pg_read_all_stats or pg_monitor.
> 
> I'm not sure why you say this. As I said, the plugin only reads from `pg_stat_*`, specifically `pg_stat_database` and `pg_stat_bgwriter`.

Ah, sorry, I did not read the "only" as explicit before.

> You probably only need to give it `pg_read_all_stats`.

Worth trying. Thanks for the help.

**Comment by tcurdt** [comment]
With #3557766 I think this ticket can be closed.
