### ISSUE TITLE
bad handshake telegraf error for inputs.mqtt

### ISSUE THREAD

**Issue by sayaligo** [influxdata/telegraf#15304]
### Please direct all support questsions to slack or the forums. Thank you.

i have a deployed mqtt broker url to which I am connecting with username and password. once i connect, in websocket clients I have different host and port to which I need to connect. In my telegraf.conf what should be my server address and port ? the one with actual url or the host in connection ? i get bad handshake when i use the host and port of websocket client.

**Comment by powersj** [comment]
Going to close this and I think you've started a slack thread we can chat on more.
