### ISSUE TITLE
[documentation]: improve details on kubernetes input configuration

### ISSUE THREAD

**Issue by tcurdt** [influxdata/telegraf#15334]
Here [the documentation](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/kubernetes/README.md) states

> This means that telegraf is running on every node within the cluster. Therefore, you should configure this plugin to talk to its locally running kubelet. To find the ip address of the host you are running on you can issue a command like the following:

```
curl -s $API_URL/api/v1/namespaces/$POD_NAMESPACE/pods/$HOSTNAME --header "Authorization: Bearer $TOKEN" --insecure | jq -r '.status.hostIP'
```

> In this case we used the downward API to pass in the $POD_NAMESPACE and $HOSTNAME is the hostname of the pod which is set by the kubernetes API.

Unfortunately it is pretty unclear where `API_URL` and `TOKEN` could be coming from. There is no link and no example.

**Comment by powersj** [comment]
Hi,

There is a fine line between the Telegraf docs being how-to guides for each of the items and docs on using it with Telegraf. I would expect a user who is setting up and running K8s to know what their API URL is in their deployment. The Telegraf docs should not be used to explain how to set up or use a cloud provided K8s instance versus using something local like kind or k3s and then access these the deployment.

For the token, while it may not be as obvious, using a quick search on whatever distributions you are to create programmatic access or a bearer token should be fairly simple (e.g. [K8s access cluster API docs](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/)

That said, can you help me understand what might help aid here?

**Comment by tcurdt** [comment]
> There is a fine line between the Telegraf docs being how-to guides for each of the items and docs on using it with Telegraf. 

Certainly. But it would be nice to provide links and remove ambiguities.

> I would expect a user who is setting up and running K8s to know what their API URL is in their deployment.

For K3s I would assume the "API URL" refers to the Kubernetes server running on port 6443.
But normal authentication is done via client cert and not via token.

> For the token, while it may not be as obvious, using a quick search on whatever distributions you are to create programmatic access or a bearer token should be fairly simple (e.g. [K8s access cluster API docs](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/)

K3s seems to [refer to tokens](https://docs.k3s.io/cli/token) to "bearer token used to authenticate the joining node to the cluster".

So the K3s docs seems to be a bit of a let down here. But the [link to the K8s documentation](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#without-kubectl-proxy) would be a great add to the README.

It does explain how to obtain a service-account-token.
If that's the bearer token needed for Telegraf - that would be good to mention.

> That said, can you help me understand what might help aid here?

Did this help from my end?

**Comment by powersj** [comment]
> Did this help from my end?

Very much, thank you! Can you please give #15335 a look and let me know if it clears things up?

Thanks
