### ISSUE TITLE
Add Python example for Execd plugin

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/telegraf#15333]
Submitted in https://github.com/influxdata/DAR/issues/370

### Use Case

Use Execd to execute a Python script

## What needs to be added or updated?
In looking over the [page](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) for telegraf's inputs.execd there doesn't seem to be a example written in python. Here's an example for python. 

```python
#!/usr/bin/env python3

import os
import sys
import time

counter = 0

while True:
  print("counter_python count=" + str(counter))
  sys.stdout.flush()

  counter += 1
  time.sleep(1)

```

We seem to reference python a lot, this is just adding my 0.02 for telegraf's inputs.execd plugin.

## What product(s) and version(s) does this apply to?
- _telegraf._

## Link(s) to documentation that needs to be changed
- _https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd_

    

### Expected behavior

N/A

### Actual behavior

N/A

### Additional info

I'm transferring [this DAR issue](https://github.com/influxdata/DAR/issues/370) to influxdata/telegraf.

**Comment by powersj** [comment]
Could you take a look at #15337 and let me know if that works?

Thanks
