### ISSUE TITLE
Internet Speed Monitor - add packet loss

### ISSUE THREAD

**Issue by andrasg** [influxdata/telegraf#15344]
### Use Case

Today packet loss information is not provided by this input plugin. The underlying speedtest_go seems to already support capture of packetloss values.

### Expected behavior

It would be great to add the packet loss percentage reported by speedtest to the data that is captured by the plguin.

### Actual behavior

Packet loss data is not captured in the data.

**Comment by powersj** [comment]
Fixed by https://github.com/influxdata/telegraf/pull/15329 will release in v1.31 in June.
