### ISSUE TITLE
Support for explicit credentials for monitoring remote systems via win_perf_counters plugin

### ISSUE THREAD

**Issue by shockogit** [influxdata/telegraf#15378]
### Use Case

The [win_perf_counters](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/README.md) plugin does not currently allow us to specify credentials for remote monitoring of Windows Performance counters . 

### Expected behavior

We can specify a username/password for monitoring windows performance counters remotely using the `win_perf_counters` plugin.

### Actual behavior

The plugin only uses the credentials context in which the agent is running.

### Additional info

This means we have to run the agent as a user that has credentials to access the target system. In many environment running a _process_ on windows as another user generates security alerts or is prohibited. Allowing credentials to be specified in the .conf file makes the plugin more portable.

**Comment by srebhan** [comment]
@shockogit after digging deep into the Windows API, I'm almost certain that the Windows API does **not** provide the possibility to specify credentials. The [API](https://learn.microsoft.com/en-us/windows/win32/api/pdh/) only talks about [specifying the remote machine in the counter path](https://learn.microsoft.com/en-us/windows/win32/perfctrs/specifying-a-counter-path). However that path documentation does not show a possibility to specify credentials. Long story short, I don't think this is supported by the Windows API and thus cannot be done in Telegraf!

Additionally, [Microsoft itself](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/PerfCtrs/about-performance-counters.md#getting-started) recommends to use the WMI Counter class when monitoring remote counters:

> Use [WMI Performance Counter Classes](https://github.com/MicrosoftDocs/win32/blob/docs/windows/desktop/WmiSdk/monitoring-performance-data) when you want to collect performance data from a local or remote system using WMI.

So I'm inclined to close this issue as "not planned" until someone can show a way to achieve this with the Windows API...

**Comment by shockogit** [comment]
> @shockogit after digging deep into the Windows API, I'm almost certain that the Windows API does **not** provide the possibility to specify credentials. The [API](https://learn.microsoft.com/en-us/windows/win32/api/pdh/) only talks about [specifying the remote machine in the counter path](https://learn.microsoft.com/en-us/windows/win32/perfctrs/specifying-a-counter-path). However that path documentation does not show a possibility to specify credentials. Long story short, I don't think this is supported by the Windows API and thus cannot be done in Telegraf!
> 
> Additionally, [Microsoft itself](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/PerfCtrs/about-performance-counters.md#getting-started) recommends to use the WMI Counter class when monitoring remote counters:
> 
> > Use [WMI Performance Counter Classes](https://github.com/MicrosoftDocs/win32/blob/docs/windows/desktop/WmiSdk/monitoring-performance-data) when you want to collect performance data from a local or remote system using WMI.
> 
> So I'm inclined to close this issue as "not planned" until someone can show a way to achieve this with the Windows API...

That makes perfect senese and thanks for looking at this guys.
