### ISSUE TITLE
BEST APPROACH TO DEPLOY TELEGRAF  IN PRODUCTION HAVING NEW FEATURES

### ISSUE THREAD

**Issue by ashishrathore1** [influxdata/telegraf#1537]
Currently we are using telegraf v 0.13.1 in our production environment . But there were certain bugs which were noted in it for e.g lower version cassandra . So what should be our strategy , whether we should wait for telegraf 1.x version or should modify code ourself in same telegraf version and deploy.

What should be the best approach for this.

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
