### ISSUE TITLE
SQL Server AAD Azure Auth method doesn't work if multiple User assigned identies are existing.

### ISSUE THREAD

**Issue by Jan747** [influxdata/telegraf#15404]
### Relevant telegraf.conf

```toml
inputs:
    - sqlserver:
        interval: "30s"
        servers:
          -"Server=dbserver.database.windows.net;Port=1433;database=dbname;hostNameInCertificate=*.database.windows.net;TrustServerCertificate=true;app name=telegraf;log=1;"
        auth_method: "AAD"
        database_type: "AzureSQLDB"
        exclude_query: 
          - "AzureSQLDBSchedulers"
          - "AzureSQLDBRequests"
```

### Logs from Telegraf

```text
[inputs.sqlserver] Error in plugin: error creating AAD token provider for system assigned Azure managed identity : adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```

### System info

Telegraf 1.25.0-alpine; Kubernetes 1.30; Azure VM with two MIs

### Steps to reproduce

1. Create Azure VM and install Kubernetes
2. Assign two identities to the created VM.
3. Create Azure SQL DB
4. Deploy and setup Telegraf

### Expected behavior

The option to select the desired Managed Identity(MI) or to specify its name in the Conf, if more then one MI is assigned to a vm.

At the top of the error log it is called clientId / resourceId. 

### Actual behavior

Authentication to the SQL DB isn't possible.

**Comment by powersj** [comment]
Hi,

The error is coming during [this call to refreshToken()](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go#L496-L499). Following that down, I am thinking it comes from [the call to NewServicePrincipalTokenFromMSI](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go#L539) where we [hardcode the resourceID](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go#L82) as `https://database.windows.net/`.

Does that seem like the value that needs to be user-configurable?

**Comment by Jan747** [comment]
Hello @powersj , 

thank you for your hints. I think in my case we need a new varibale for userAssignedID. And create a case if userAssigenedID is given it should use NewServicePrincipalTokenFromMSIWithUserAssignedID to get the new token instead of [NewServicePrincipalTokenFromMSI](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go#L539). 

https://github.com/Azure/go-autorest/blob/main/autorest/adal/token.go#L64 userAssignedID string

Also some other finding: The base libaray https://github.com/Azure/go-autorest/tree/main/autorest/adal is out off support. 
"This module will go out of support by March 31, 2023. For authenticating with Azure AD, use module [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) instead."

So a migration from adal to azidentiy is needed.

**Comment by Jan747** [comment]
Hey I created a PR. Can someone review it. I am not a golang developer please have a look.

**Comment by luizfelmach** [comment]
I have the same connection problem.

Inside a Telegraf container with sqlcmd, I run the following command:

```bash
sqlcmd -S <server>.database.windows.net -d <database> -G
```

It works and I’m able to connect to the database.

But in Telegraf, with this configuration:

```
inputs:
  - sqlserver:
      interval: "1m"
      database_type: "AzureSQLDB"
      auth_method: "AAD"
      servers:
        - "Server=<server>.database.windows.net;Database=<database>;"
```

It throws the error mentioned in the issue. Is anyone else experiencing this problem?

Note: Telegraf is not using AZURE_CLIENT_ID.
