### ISSUE TITLE
TOML indentation problem, snmp input plugin

### ISSUE THREAD

**Issue by mire3212** [influxdata/telegraf#1541]
I've got Telegraf capturing data from a machine and dumping that into InfluxDB. I'm trying to get it to also capture SNMP data and write that data into InfluxDB. I've configured it in the same way I've seen from the docs, and yet my data isn't showing up in InfluxDB. I can't seem to figure out why, any thoughts?

`Telegraf - version 0.13.1`
`Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0`

```
   interval 10s
...
 [[inputs.snmp]]
   snmptranslate_file = "/etc/telegraf/oids.txt"
 
   [[inputs.snmp.host]]
     address = "192.168.100.41:161"
     community = "public"
     version = 2
     timeout = 2.0
     retries = 2
     collect = ["if_out_octets", "if_in_octets"]

   [[inputs.snmp.bulk]]
      name = "if_out_octets"
      max_repetition = 127
      oid = ".1.3.6.1.2.1.31.1.1.1.10.48"

   [[inputs.snmp.bulk]]
      name = "if_in_octets"
      max_repetition = 127
      oid = ".1.3.6.1.2.1.31.1.1.1.6.48"
```

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

**Comment by mire3212** [comment]
I believe the issue is actually a potential bug.

It appears that having spaces in the config file in front of the descriptors is preventing telegraf from reading the config.

Example:

This doesn't work:
```
...[[inputs.snmp.host]]]
      stuff
      here
```
(. = space for clarification)

This does work:

```
[[inputs.snmp.host]]
   stuff
   here
```

**Comment by sparrc** [comment]
that is strange, can you post your full working and non-working config, maybe in a gist?

**Comment by mire3212** [comment]
I don't have the original configs anymore and I've re-worked a lot of since this post in an effort to get it working.  :/

**Comment by sparrc** [comment]
I believe this has been solved by https://github.com/influxdata/telegraf/pull/1389
