### ISSUE TITLE
[[outputs.datadog]] - HTTP 403

### ISSUE THREAD

**Issue by constantin-baciu** [influxdata/telegraf#15419]
### Please direct all support questsions to slack or the forums. Thank you.

Hi, 

I'm trying to get telegraf to pickup a file that is formatted as InfluxDB input (using the tail plugin) and send it to DataDog.
The API key is setup properly (tested via Postman).
But, in the telegraf logs, all I see is this:

[agent] Error writing to outputs.datadog: received bad status code, 403: {"errors":["No API key specified in DD-API-KEY header"]}

Is this output plugin still maintained? Or should I look for other means of sending the metrics over to DataDog?

Thanks!

**Comment by powersj** [comment]
Hi,

It looks like the plugin currently encodes the API key as part of the request URL: https://github.com/influxdata/telegraf/blob/master/plugins/outputs/datadog/datadog.go#L181-L185

The [v2 docs](https://docs.datadoghq.com/api/latest/metrics/), seem to point at the DD-API-Key header. However, it looks like we are using the [v1 api](https://docs.datadoghq.com/dashboards/guide/dashboard-lists-api-v1-doc/) method by default.

Can you confirm the URL you are using?

**Comment by constantin-baciu** [comment]
Hi,

Here's the URL I'm using:

https://api.us5.datadoghq.com/api/v2/series

I'll try with v1 as well.

Thanks!

**Comment by powersj** [comment]
Yeah let me know if v1 works out. That might work, but long-term it does seem that we would want to move to support v2.
