### ISSUE TITLE
Detect new files in config directory

### ISSUE THREAD

**Issue by llamafilm** [influxdata/telegraf#15417]
### Use Case

In our system, telegraf is deployed on a new instance with some base config files in the `telegraf.d` directory.  An external service keeps track of the list of targets to be monitored, and sometimes adds new files to this directory when new targets are discovered.

### Expected behavior

When using `-config-directory` and`--watch-config` together, it should reload automatically after detecting new files in that directory.

### Actual behavior

It reloads when a file is modified, but not when a new file is created.

**Comment by powersj** [comment]
Dup of https://github.com/influxdata/telegraf/issues/12264
