### ISSUE TITLE
Gather metrics immediately upon startup

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#15414]
### Use Case

Some metrics should be collected rarely, yet when working on a config you want them to be gathered immediately to shorten "edit-try" cycle.

Currently when config specifies long `interval` Telegraf waits for `interval` after startup to collect them, which is inconvenient when I am iterating on a config.

### Expected behavior

run gather on all plugins immediately upon startup.

### Actual behavior

every plugin first collection happens in `interval` time after the startup

**Comment by josephbrosef** [comment]
If this is specifically around editing config files then running a once off input collection to validate its working as expected etc, could you use the --test flag?

1. --once: Run one collection and flush interval then exit
2. --test: Run only inputs, output to stdout, and exit

https://github.com/influxdata/telegraf/blob/master/docs/COMMANDS_AND_FLAGS.md

**Comment by redbaron** [comment]
That would work indeed in local dev, but I should have mentioned that execution environment I am working in is Kubernetes and config is stored in the ConfigMap. I often edit it inplace , uncomment `[output.file]` section to get quick overwview of metrics collected and work on `inputs`  part of the config.  I wont be able to do it locally, because my local connectivity is very different than Kubernetes cluster telegraf is in.

**Comment by srebhan** [comment]
@redbaron did you try setting `round_interval = false`?

**Comment by redbaron** [comment]
> @redbaron did you try setting `round_interval = false`?

I don't have `round_interval` set in my config, so I assume there is no rounding

**Comment by powersj** [comment]
> > @redbaron did you try setting `round_interval = false`?
> 
> I don't have `round_interval` set in my config, so I assume there is no rounding

`round_interval` is true by default, can you give it a try in your situation please?

How large of an interval are you set to run with?

**Comment by pkolmann** [comment]
Thanks for the hint regarding `round_interval`. This works for me.
