### ISSUE TITLE
telegraf plugins parsers does not list available parsers

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#15425]
### Use Case

I want to check whether my custom build includes the parsers I need

### Expected behavior

```shell
telegraf plugins parsers
```
Includes `parsers.json` etc.

### Actual behavior

```shell plugins
telegraf plugins parsers
```
Shows all plugins, including inputs, outputs, secretstores, but no parsers

**Comment by LarsStegman** [comment]
I have not yet looked at how the custom builder works exactly. I can take a look if you think it's not too much work to understand it.

**Comment by powersj** [comment]
Thanks - It is pretty much this file that prints out the plugins that were registered with that binary: https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/cmd_plugins.go

**Comment by LarsStegman** [comment]
See #15426
