### ISSUE TITLE
Add a plugin to retrieve metrics from IIS app pools

### ISSUE THREAD

**Issue by haljoh** [influxdata/telegraf#15432]
The plugin should be able to retrieve metrics from IIS app pools.

    The plugin should be able to retrieve the following metrics:

    - percentProcessorTime
    - privateBytes
    - workingSet
    - handleCount
    - threadCount
    - ioReadBytesPerSec
    - ioWriteBytesPerSec

Each metric shall be reported with a label that includes the app pool name.

**Comment by powersj** [comment]
Hi,

Is this something you plan to work on and provide a PR for?

If not, is there an API available to gather this information that you can point to? Or better yet, is there an existing Go library that can be leveraged to collect that data?

Thanks
