### ISSUE TITLE
Telegraf Influxdb input: Add missing data from debug vars

### ISSUE THREAD

**Issue by cpinflux** [influxdata/telegraf#15437]
### Use Case

/debug/vars provides this information:

```
"build": {"Branch":"unknown","Build Time":"","Commit":"d97e21d4473164bb3ba0055ecd1971f2529b6d82","Version":"v1.11.5"},
"cmdline": ["influxd"],
"crypto": {"FIPS":false,"ensureFIPS":false,"implementation":"Go","passwordHash":"bcrypt;cost=10"},
```
But as there is no explicit struct defined for these, unlike system and memstats, and they are not preformatted with tags and fields like the rest of the data, they are ignored by telegraf. 

It would be very handy to know what version of InfluxDB is running over a large estate

### Expected behavior

These three lines should be either converted into three different measurements or added into the influxdb base measurement that currently contains only a custom "n_shards" field.

I prefer the influxdb measurement route to keep n_shards company. If this were the path taken I would probably also suggest duplicating the influxdb_system output into there as well for neatness.

### Actual behavior

Data is not present in output at all

### Additional info

[telegraf_influxdb.txt](https://github.com/user-attachments/files/15514244/telegraf_influxdb.txt)
[debug_vars.txt](https://github.com/user-attachments/files/15514245/debug_vars.txt)

**Comment by srebhan** [comment]
@cpinflux please test the binary in PR #15438, available as soon as CI finished the tests, and let me know if this fixes the issue!

**Comment by srebhan** [comment]
Successfully tested as stated in the PR...
