### ISSUE TITLE
http_listener_v2 confuses prometheus clients by responding with HTTP status code 204

### ISSUE THREAD

**Issue by yacoob** [influxdata/telegraf#15453]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
  service_address = "127.0.0.1:9999"
  paths = ["/metrics/job/home.backup"]
  data_format = "prometheus"
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.30.3 (git: HEAD@fd4af886)

### Steps to reproduce

1. Configure http listener expecting prometheus input (aka prometheus push gateway lookalike)
2. Push to it with a client using official [golang prometheus client](https://github.com/prometheus/client_golang/tree/main/prometheus/push) - in my case it's [resticprofile](https://creativeprojects.github.io/resticprofile/status/prometheus/index.html)

### Expected behavior

Metrics are pushed without an error.

### Actual behavior

With `resticprofile`, I get:

```
unexpected status code 204 while pushing to http://localhost:9999/metrics/job/home.backup:
```

Official golang client considers the push a success if the client [receives status 200 or 202](https://github.com/prometheus/client_golang/blob/8491260a42258b8aeee8e1dd4a54352845605508/prometheus/push/push.go#L313). Telegraf replies with 204, so the push is considered a failure (as in, an `Error` object is returned from `Pusher.push()`. FWIW, the metrics do go through. `resticprofile` also treats this as a warning, not a failure.

**Comment by powersj** [comment]
https://github.com/influxdata/telegraf/pull/15454
