### ISSUE TITLE
gocritic->sloppyLen - Detects usage of `len` when result is obvious or doesn’t make sense. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15498]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [diagnostic](https://go-critic.com/overview.html#checkers-from-the-diagnostic-group) - Diagnostics try to find programming errors in the code. They also detect code that may be correct, but looks suspicious.
- checker: [sloppyLen](https://go-critic.com/overview.html#sloppylen) - Detects usage of `len` when result is obvious or doesn’t make sense.

### Example

**Before:**
```
len(arr) <= 0
```

**After:**
```
len(arr) == 0
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/inputs/aerospike/aerospike.go:221:5                 gocritic  sloppyLen: len(a.Namespaces) <= 0 can be len(a.Namespaces) == 0
plugins/inputs/aerospike/aerospike.go:265:5                 gocritic  sloppyLen: len(a.Sets) <= 0 can be len(a.Sets) == 0
plugins/inputs/dovecot/dovecot.go:49:5                      gocritic  sloppyLen: len(d.Filters) <= 0 can be len(d.Filters) == 0
plugins/inputs/file/file.go:86:6                            gocritic  sloppyLen: len(files) <= 0 can be len(files) == 0
plugins/inputs/opcua_listener/opcua_listener_test.go:224:9  gocritic  sloppyLen: len(newRemaining) <= 0 can be len(newRemaining) == 0
plugins/inputs/opcua_listener/opcua_listener_test.go:364:9  gocritic  sloppyLen: len(newRemaining) <= 0 can be len(newRemaining) == 0
plugins/inputs/x509_cert/x509_cert.go:514:6                 gocritic  sloppyLen: len(files) <= 0 can be len(files) == 0
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by powersj** [comment]
+1
