### ISSUE TITLE
TOML parser issue

### ISSUE THREAD

**Issue by sebastianJot** [influxdata/telegraf#15517]
### Relevant telegraf.conf

```toml
[[processors.enum]]
mapping = [
    { field = "powerSupplyStatus", value_mappings = { Up = 1, Down = 0 } },
]
```

### Logs from Telegraf

```text
E! error loading config file /etc/telegraf/telegraf-snmp.conf.netdevdc2: error parsing enum, unmarshalling failed: line 228: (enum.Mapping.ValueMappings) cannot unmarshal TOML array table into map[string]interface {} (need slice)
```

### System info

Podman 4.6.1

### Steps to reproduce

1. Configure enum processor:

```
[[processors.enum]]
  [[processors.enum.mapping]]
    ## Name of the field to map. Globs accepted.
    field = "powerSupplyStatus"
    [processors.enum.mapping.value_mappings]
      "Up" = 1
      "Down" = 0
```

2. Fill config file within python script using toml and tomli_w libraries

3. Output is then:
`[[processors.enum]]
mapping = [
    { field = "powerSupplyStatus", value_mappings = { Up = 1, Down = 0 } },
]`
which is correct TOML format

4. Telegraf is unable to start due to TOML parser error:
` E! error loading config file /etc/telegraf/telegraf-snmp.conf.netdevdc2: error parsing enum, unmarshalling failed: line 228: (enum.Mapping.ValueMappings) cannot unmarshal TOML array table into map[string]interface {} (need slice)`

### Expected behavior

Map strings value to integers

### Actual behavior

Telegraf stops with error message

**Comment by powersj** [comment]
> which is correct TOML format

Unfortunately, our current TOML parser uses an older version of the spec and has troubles reading inline tables in some situations, like this one. See #15252 as a prior example. To solve your issue, you need to use the explicit notation
