### ISSUE TITLE
Metrics aren't displayed (outputs.prometheus_client)

### ISSUE THREAD

**Issue by 1Kyl0** [influxdata/telegraf#15516]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
  agents = ["my_private_ip"]
  version = 2
  community = "my_private_community"
  name = "test-1"
  interval = "2m"
  timeout = "30s"

[[inputs.snmp.table]]
  name = "test"
  [[inputs.snmp.table.field]]
    name = "Instance"
    oid = "1.3.6.1.4.1.4131.1.6.2.2.1.2"
  [[inputs.snmp.table.field]]
    name = "Values"
    oid = "1.3.6.1.4.1.4131.1.6.2.2.1.3"
    
 [[outputs.prometheus_client]]
   listen = ":9273"
   path = "/metrics"
   expiration_interval = "0"
   collectors_exclude = ["gocollector", "process"]
```

### Logs from Telegraf

```text
--- many lines before
> cpu,cpu=cpu30,host=my_servername usage_guest=0,usage_guest_nice=0,usage_idle=100,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=0 1718357997000000000
> cpu,cpu=cpu31,host=my_servername usage_guest=0,usage_guest_nice=0,usage_idle=100,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=0 1718357997000000000
> cpu,cpu=cpu-total,host=my_servername usage_guest=0,usage_guest_nice=0,usage_idle=99.68808476715999,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0.18714909507691876,usage_user=0.12476606332409301 1718357997000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_ASI_1_Dispo",Values="0" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="CL_Boucle_1_Salle_1_Clim_4_Alr",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_TGO_PresUOndul4",Values="0" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_TGBT_PresUJDB",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Salle_1_Voie_1_TDO_2_ArrUrg",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="CL_Boucle_1_Salle_1_Clim_2_EauDeVille",Values="0" 1718358036000000000
--- many lines after
```

### System info

Telegraf 1.30.0, Debian 12

### Steps to reproduce

1. Intall Telegraf
2. Config inputs.snmp and outputs.prometheus_client
3. Connect prometheus to telegraf output
...

### Expected behavior

Inputs.snmp of telegraf work fine and it manages to recover the metrics I am looking for (see log).
I exec telegraf --config telegraf.conf --test and I can see metrics. 
I exec telegraf --config telegraf.conf --debug and I see this line 2024-06-14T08:30:16Z D! [outputs.prometheus_client] Wrote batch of 675 metrics in 4.619028ms (it refers to my metrics) 
So if go on localhost:9273/metrics I should see the metrics and they must also be on prometheus.

### Actual behavior

Inputs.snmp of telegraf work fine and it manages to recover the metrics I am looking for (see log).
I exec telegraf --config telegraf.conf --test and I can see metrics. 
I exec telegraf --config telegraf.conf --debug and I see this line 2024-06-14T08:30:16Z D! [outputs.prometheus_client] Wrote batch of 675 metrics in 4.619028ms (it refers to my metrics) 
But when I go to the page or to prometheus the metrics are not there (only appear default metrics)
the problem therefore doesn't come from the connection and the recovery of the metrics, but from the display in the outputs.prometheus_client.

### Additional info

Your help is welcome because I'm stuck

Thanks

**Comment by powersj** [comment]
HI,

> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_ASI_1_Dispo",Values="0" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="CL_Boucle_1_Salle_1_Clim_4_Alr",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_TGO_PresUOndul4",Values="0" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Chaine_1_Voie_1_TGBT_PresUJDB",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="EL_Salle_1_Voie_1_TDO_2_ArrUrg",Values="1" 1718358036000000000
> test,agent_host=my_private_ip,host=my_servername Instance="CL_Boucle_1_Salle_1_Clim_2_EauDeVille",Values="0" 1718358036000000000

These metrics are all strings, not numeric. Prometheus requires numeric data types otherwise it cannot represent the values. Either convert the fields from strings to some numeric type or the data will not be able to show up.

**Comment by 1Kyl0** [comment]
HI,

Oh okay, it makes sense now put like that :) 
So here it's my current config :
`[[inputs.snmp.table]]
  name = "test"
  [[inputs.snmp.table.field]]
    name = "Instance"
    oid = "1.3.6.1.4.1.4131.1.6.2.2.1.2"
  [[inputs.snmp.table.field]]
    name = "Values"
    oid = "1.3.6.1.4.1.4131.1.6.2.2.1.3"
    conversion = "float"`
    
It works and I can see well in prometheus. 
But now the problem comes from the fact that I see that one metric by one metric.
Example :
test_Values{Instance="EL_Chaine_1_Voie_1_ASI_2_ChargeOndul",agent_host="my_private_ip",host="my_servername"} 1

So in prometheus metric are display one by one, and not in the same time (the new metric replaces the old one).
I think I've already seen this topic in issues but I can't find it to see the solution.
I have to collect and display approximately 675 metric for this simple collect (in the same time).

**Comment by 1Kyl0** [comment]
I found !!!!! 
I forgot to add in_tag = true for instances field and now with this argument it's works fine. 

Thanks for your help.
