### ISSUE TITLE
testifylint->useless-assert - Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15538]
### Description

This issue starts a discussion about enabling:
- linter: [testifylint](https://github.com/Antonboom/testifylint) - Checks usage of github.com/stretchr/testify.
- checker: [useless-assert](https://github.com/Antonboom/testifylint?tab=readme-ov-file#useless-assert) - Protection from bugs and possible dead code.

### Example

Currently the checker guards against assertion of the same variable:

```
❌
assert.Equal(t, tt.value, tt.value)
assert.ElementsMatch(t, users, users)
// And so on...
assert.True(t, num > num)
assert.False(t, num == num)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by srebhan** [comment]
Makes sense to me as the developer probably wanted to test something else. ;-)

**Comment by powersj** [comment]
+1
