### ISSUE TITLE
[chrony] unix socket connection is broken

### ISSUE THREAD

**Issue by Frankkkkk** [influxdata/telegraf#15549]
### Relevant telegraf.conf

```toml
[[inputs.chrony]]
    server = "unix:///var/run/chrony/chronyd.sock"
    metrics = ["activity", "tracking", "sources", "sourcestats"]
```

### Logs from Telegraf

```text
[pid 612402] write(9, "\6\1\0\0\0,\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 416 <unfinished ...>
[pid 612402] <... write resumed>)       = 416
[pid 612402] read(9,  <unfinished ...>
[pid 612402] <... read resumed>0xc003368400, 1024) = -1 EAGAIN (Resource temporarily unavailable)
```

### System info

1.13 - 78cbf533d2

### Steps to reproduce

1. Use the chrony plugin
2. Set the server to be `unix:///var/run/chrony/chronyd.sock`
3. Launch telegraf as root (or at least as a user that con use the unix socket)
4. See it hang

### Expected behavior

The chrony plugin should work

### Actual behavior

The plugin hangs *when using the unix socket* when:
- telegraf is launched as root
- or the connection is manually specified to use the socket

The reasons are two fold:
- Chrony uses datagram (`unixgram`) unix socket and not stream (`unix`) ones.
- The socket should be duplicated in order not to hang other connections to it

Here is a working [example by facebook](https://github.com/facebook/time/blob/4db09adcc1ec9ae3b6dda1dfcf41db77ca89b246/cmd/ntpcheck/checker/chrony.go#L38)

### Additional info

I guess this is hard to reproduce, because the unix socket is rarely used as telegraf cannot talk to it (thus it instead connects via UDP to the chrony deamon).

The unix socket is however needed to access the `serverstats` metrics. Most of the other ones can be reached using the udp socket.

**Comment by powersj** [comment]
Thanks for the various issues and PRs

next steps: review PR
