### ISSUE TITLE
Skip individual processor before aggregator

### ISSUE THREAD

**Issue by R290** [influxdata/telegraf#15580]
### Use Case

The OPC-UA input plugin returns a metric for each individual node. My processor uses information from multiple nodes and therefore the merge aggregator is used to combine the metrics. 

### Expected behavior

The processor has a flag which, if set to true, only applies the processor to aggregated metrics. The metrics coming directly from the input are skipped silently.

### Actual behavior

Some form of workaround is needed, either by using temporary tags or in the processor itself.

### Additional info

The requested feature is similar to the `SkipProcessorsAfterAggregators` flag, although I'd like to be able to set this on a individual processor level.
```[tasklist]
### Tasks
```

**Comment by srebhan** [comment]
TBH, all of this run-after-aggregator processing is awkward (at best) and should be directly defining a (more flexible) processing pipeline in the long-run. This being said, adding more complexity to it won't make it easier for us to replace this in the future. Therefore I think you should use the tag-workaround... @powersj and @DStrand1, what do you think?

**Comment by powersj** [comment]
> Therefore I think you should use the tag-workaround

Agreed - our metric routing solution continues to be the use of tags and metric names combined with the appropriate namepass/tagpass options.

**Comment by R290** [comment]
Thanks for the clear answers, the tag workaround it is. Tagging related open issue #12523 so this issue does not get lost as a potential use case when the run loop is rewriten.
