### ISSUE TITLE
vsphere get guest.os 

### ISSUE THREAD

**Issue by sudo77** [influxdata/telegraf#15616]
### Please direct all support questsions to slack or the forums. Thank you.

Is it possible to get the  OS Type and Version of the VM, In telegraf I can not find any option to collect this kind of Data.
For example the the value of the OS collected by the vmware tools. Windows 2019, Linux ohter, Linunx Debian ....

**Comment by powersj** [comment]
The vsphere plugin should return a "guest" field, which comes from either `config.guestId` or `guest.guestId` in vsphere.
