### ISSUE TITLE
Installing telegraf version  telegraf-1.9.0-1.arm64.rpm giving system architecture incompatible error

### ISSUE THREAD

**Issue by Kajalagg98** [influxdata/telegraf#15619]
### Please direct all support questsions to slack or the forums. Thank you.

I am using Amazon Linux 2 which is Graviton(Arm64) based. When I tried installing telegraf version telegraf-1.9.0-1.arm64.rpm on it I got error `Not a compatible architecture: arm64`. After going through Telegraf release notes, what I understand is 1.9.0 is supporting arm 32-bit and not 64-bit. If this is correct, let me know which next upgraded version rpm I should use so that it will support arm 64-bit?

On running command "uname -m" on my system, the o/p I got is `aarch64`.

Can you plz share the next version(next to 1.9.0) correct rpm that I can use on my machine?
Thanks.

**Comment by powersj** [comment]
> telegraf-1.9.0-1.arm64.rpm

This version is so old, like 5-6 years old I cannot comment on how it was built. However, I too would expect the arm64 builds to work on a Graviton system.

Please use a build from the latest version, v1.31.1, and try again: https://github.com/influxdata/telegraf/releases/tag/v1.31.1
