### ISSUE TITLE
TLS1.2 with AES256-SHA256 stopped working in 1.29.5 (1.29.4 works) with inputs.http_reponse

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#15612]
### Relevant telegraf.conf

```toml
[[inputs.http_response]]
  urls = ['https://localhost:9201/someendpoint']

  insecure_skip_verify = true
  response_timeout = "5s"

```
stunnel.conf to create an endpoint which telegraf doesn't connect to.
```
[aservicename]
accept = 9201
connect = 8086  # some port which should answer in some sort of http

cert = .../ssl-cert-snakeoil.pem
key = .../ssl-cert-snakeoil.key

# if these lines are missing, it works. If they're there, it doesn't
ciphers = AES256-SHA256
sslVersion = TLSv1.2
```

### Logs from Telegraf

```text
2024-07-09T14:06:59Z D! [inputs.http_response]  Network error while polling https://localhost:9201/someendpoint: Get "https://localhost:
9201/someendpoint": remote error: tls: handshake failure

> http_response,host=somehostname,method=GET,result=connection_failed,server=https://localhost:9201/someendpoint result_code=3i,result_type="connection_failed" 1720534020000000000
```

### System info

telegraf >=1.29.5 on rhel8

### Steps to reproduce

1. Have a service with TLS 1.2 and AES256-SHA256
2. have the telegraf-plugin inputs.http_response connect to it
3. use telegraf >= 1.29.5 (1.29.4 works)
...

### Expected behavior

Connect as before. As, for example, `curl -kvvv ...` does.

### Actual behavior

"handshake failure"

**Comment by powersj** [comment]
In your telegraf config's `http_response` config, if you set `tls_cipher_suites = ["all"]` what happens? TLS 1.2 is still the default in Telegraf, so I would not expect that to be the issue here. In this case, I believe AES256-SHA256 is considered weak and part of the insecure cipher list.

> tls: handshake failure

This can be a variety of things, but most commonly when it is a consistent issue it means that the server is using too old of a version of SSL/TLS or an insecure cipher suite.

New versions of Go that Telegraf builds with can change the default cipher list, by moving some to the insecure list because of known security issues. The current list is: https://go.dev/src/crypto/tls/cipher_suites.go

v1.29.5 upgraded [to go1.22.0](https://github.com/influxdata/telegraf/pull/14697), which did make changes to the supported ciphers.

> on rhel8

:\

**Comment by knollet** [comment]
Ah, I didn't see the go version bump in the Changelog. Thanks.
I'll try the config

**Comment by knollet** [comment]
Ok, your cipher suite didn't work.
I added all cipher suits in
https://github.com/influxdata/telegraf/blob/6a36d27a3d116a95025e9f26bc5f9cb16be1218e/docs/TLS.md
and it doesn't work.
`tls_min_version` and `tls_max_version` aren't supported in 1.29.5?

**Comment by powersj** [comment]
> I added all cipher suits in ... and it doesn't work.

Let's take a step back and verify the actual IANA name. It may be that you actually need `TLS_RSA_WITH_AES_256_CBC_SHA256`? @srebhan is this correct, because I don't see this ever supported, so I'd be shocked if it suddenly stopped.

> tls_min_version and tls_max_version aren't supported in 1.29.5?

These absolutely are supported. Why do you ask this?

**Comment by knollet** [comment]
> > tls_min_version and tls_max_version aren't supported in 1.29.5?
> 
> These absolutely are supported. Why do you ask this?

Ah, I see `tls_max_version` is not defined in a client context. In a server context, it's defined.

**Comment by knollet** [comment]
> > I added all cipher suits in ... and it doesn't work.
> 
> Let's take a step back and verify the actual IANA name. It may be that you actually need `TLS_RSA_WITH_AES_256_CBC_SHA256`?

`error parsing http_response, could not parse client cipher suites: "TLS_RSA_WITH_AES_256_CBC_SHA256" unsupported cipher`

:/

**Comment by powersj** [comment]
Can you please show logs of Telegraf ever working with this cipher? This is a known weak cipher that does not to seem to have ever been supported by Go. TLS_RSA_WITH_AES_256_CBC_SHA256 does look to be the other name and the only references upstream I see are of people requesting, but upstream Go declining to add support:

* https://github.com/golang/go/issues/26652
* https://github.com/golang/go/issues/31933

I setup stunnel with your config and confirmed the cipher in use:

```shell
$ echo -n '' | openssl s_client -connect 192.168.100.134:9201 2>&1 | grep Cipher
New, TLSv1.2, Cipher is AES256-SHA256
    Cipher    : AES256-SHA256
```

When connecting with v1.29.4 this still fails:

```shell
$ ../telegraf-builds/telegraf-v1.29.4 --config config.toml --once
2024-07-09T17:35:19Z I! Loading config: config.toml
2024-07-09T17:35:19Z I! Starting Telegraf 1.29.4 brought to you by InfluxData the makers of InfluxDB
2024-07-09T17:35:19Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
2024-07-09T17:35:19Z I! Loaded inputs: http_response
2024-07-09T17:35:19Z I! Loaded aggregators: 
2024-07-09T17:35:19Z I! Loaded processors: 
2024-07-09T17:35:19Z I! Loaded secretstores: 
2024-07-09T17:35:19Z I! Loaded outputs: file
2024-07-09T17:35:19Z I! Tags enabled: 
2024-07-09T17:35:19Z D! [agent] Initializing plugins
2024-07-09T17:35:19Z D! [agent] Connecting outputs
2024-07-09T17:35:19Z D! [agent] Attempting connection to [outputs.file]
2024-07-09T17:35:19Z D! [agent] Successfully connected to outputs.file
2024-07-09T17:35:19Z D! [agent] Starting service inputs
2024-07-09T17:35:19Z D! [inputs.http_response] Network error while polling https://192.168.100.134:9201: Get "https://192.168.100.134:9201": remote error: tls: handshake failure
2024-07-09T17:35:19Z D! [agent] Stopping service inputs
2024-07-09T17:35:19Z D! [agent] Input channel closed
2024-07-09T17:35:19Z I! [agent] Hang on, flushing any cached metrics before shutdown
http_response,method=GET,result=connection_failed,server=https://192.168.100.134:9201 result_code=3i,result_type="connection_failed" 1720546519000000000
2024-07-09T17:35:19Z D! [outputs.file] Wrote batch of 1 metrics in 31.08µs
2024-07-09T17:35:19Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2024-07-09T17:35:19Z I! [agent] Stopping running outputs
2024-07-09T17:35:19Z D! [agent] Stopped Successfully
```

**Comment by knollet** [comment]
ok, 
it doens't work on Version 1.31.0 with any Cipher in https://go.dev/src/crypto/tls/cipher_suites.go

I checked out tag v1.29.5 and used all ciphers in `telegraf/plugins/common/tls/common.go`. Didn't work. Interesting is, that TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 and TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 weren't parseble. This surprises me, because it looks to me that `common.go` is the lookup table used by `ParseCiphers()` in this version.
I didn't compile v1.29.5 myself but got an rpm from our repo. Should be your v1.29.5 release.

**Comment by knollet** [comment]
ok, thank you, I got it.
Seems it really didn't use AES256-SHA256 but some other, and I could find other supported ciphers with 
https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers
which are still weak, probably, but I can list them.

**Comment by srebhan** [comment]
@powersj I can't find `TLS_RSA_WITH_AES_256_CBC_SHA256` in the list of supported suites either, so I guess @knollet is right, `curl` and `openssl` might just negotiate a different suite...

@knollet could you please test a [nightly build]() with `tls_cipher_suites = ["all"]` and check if the plugin works with this setting? Alternatively you could brute-force test what the server supports with [this script](https://blog.lxsang.me/post/id/31)...

**Comment by knollet** [comment]
Ok, there's a problem, but it seems, you already have it fixed.

Since 1.29.5 weak ciphers are disabled, but plugins/common/tls/config.go doesn't define `tls_cipher_suites` for **clients** until 1.31.0.

So you can't use weak ciphers as a client with the versions in between.

**Comment by srebhan** [comment]
@knollet exactly, please note that Golang (more precisely the crypto/tls package) disabled those ciphers by default and we picked it up with a version bump. So if you do a custom build with an older Golang version, this will work...

Can we close this issue?

**Comment by knollet** [comment]
As far as I'm concerned, you can close it. Thanks.
