### ISSUE TITLE
Use rfc3339 timestamps w/ timezone in log output

### ISSUE THREAD

**Issue by joshuaspence** [influxdata/telegraf#1564]
Currently Telegraf logs (written to `/var/log/telegraf/telegraf.log` at least for us) do not contain the timestamp. This makes it difficult to accurately ingest the logs into a logging pipeline such as Logstash.

**Comment by phemmer** [comment]
If you're using an OS which uses systemd, personally I'd recommend editing the systemd service file and remove the redirection to the log files and let it instead go to journald. This offers a lot more flexibility in what you can do with the logs, and will also solve the timestamp issue.
If you're not using an os with systemd, you can send the output into syslog by adding the following to the end of the start command: `2>&1 | logger -t telegraf`. This would also solve the timestamp issue.

The benefit of both these solutions is that they're standard practices. There's a good chance you're already consuming journald/syslog data, and so you don't need any telegraf specific configuration for logstash to read the logs.

**Comment by sparrc** [comment]
There are timestamps?:

```
2016/08/01 09:39:26 Starting Telegraf (version 1.0.0-beta3-24-g1357525)
2016/08/01 09:39:26 Loaded outputs: file
2016/08/01 09:39:26 Loaded inputs: snmp
2016/08/01 09:39:26 Tags enabled: host=tars
2016/08/01 09:39:26 Agent Config: Interval:5s, Debug:false, Quiet:false, Hostname:"tars", Flush Interval:5s
2016/08/01 09:39:30 Hang on, flushing any cached metrics before shutdown
2016/08/01 09:39:30 Output [file] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
```

**Comment by joshuaspence** [comment]
Gah sorry, I meant timezones not timestamps.

**Comment by sparrc** [comment]
OK
