### ISSUE TITLE
add regular expression support for dynatrace output counter metrics

### ISSUE THREAD

**Issue by dhruvthak** [influxdata/telegraf#15659]
### Use Case

Metrics:
```
simple_abc_metric
simple_def_metric
```

In Dynatrace configuration, we pass `/simple_[a-z]+_metric/` to `AddCounterMetrics`

### Expected behavior

The expectation was a regular expression match support

### Actual behavior

Instead counter names were string compared

### Additional info

Code reference: [dynatrace.go#L233](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/dynatrace/dynatrace.go#L233)

Proposed change:
If the passed value is a regular expression match i.e., starts and ends with a `/` a regular expression match to be performed else a literal string match to ensure the existing behavior is not affected.

Looking to open a pull request for this change.

**Comment by powersj** [comment]
Hi,

> The expectation was a regular expression match support

Not opposed to introducing this, however:

>  i.e., starts and ends with a / a regular expression match to be performed

Please create a new configuration option that expects regular expressions. Assuming a leading slash is not safe in the event that someone has used a leading slash in a metric name.

**Comment by dhruvthak** [comment]
Makes sense. Updated proposal:

Add a separate configuration option:

```
AddCounterMetricsPatterns []string        `toml:"additional_counters_patterns"`
```

**Comment by powersj** [comment]
> Makes sense. Updated proposal:
> 
> Add a separate configuration option:
> 
> ```
> AddCounterMetricsPatterns []string        `toml:"additional_counters_patterns"`
> ```

Sounds good! Look forward to seeing a PR!
