### ISSUE TITLE
ipmi_sensor - configurable timeout?

### ISSUE THREAD

**Issue by JimtotheB** [influxdata/telegraf#1565]
Tons and tons of these, command fails more often than it works, at least with a dozen or so ipmi hosts.

``` shell
2016/08/01 04:13:35 ERROR in input [ipmi_sensor]: run /usr/bin/ipmitool ipmitool -H esxi0-idrac.jostle.pw -U ****** -P ****** -I lanplus sdr:  (Command timed out.)
2016/08/01 04:13:35 ERROR in input [ipmi_sensor]: run /usr/bin/ipmitool ipmitool -H esxi3-idrac.jostle.pw -U ****** -P ****** -I lanplus sdr:  (Command timed out.)
2016/08/01 04:13:35 ERROR in input [ipmi_sensor]: run /usr/bin/ipmitool ipmitool -H esxi4-idrac.jostle.pw -U ****** -P ****** -I lanplus sdr:  (Command timed out.)
2016/08/01 04:13:35 ERROR in input [ipmi_sensor]: run /usr/bin/ipmitool ipmitool -H esxi8-idrac.jostle.pw -U ****** -P ****** -I lanplus sdr:  (Command timed out.)
```

The default timeout for lanplus is 2 seconds, which seems to be fine when there is not much else going on, apparently not so much when its in a busy environment. The -N flag allows this to be set to a higher value.

Edit: Adding each host as an individual input, and setting a hight collection_jitter helps a bit, but there are still a ton of random timeouts.

**Comment by sparrc** [comment]
sure, would make sense to have a timeout here

**Comment by danielnelson** [comment]
Added in #2818
