### ISSUE TITLE
input.nstat can not get net interface data, but input.net can do it.

### ISSUE THREAD

**Issue by ikakarotto** [influxdata/telegraf#15669]
### Use Case

Plugin "inputs.net" deprecated since version 1.27.3 and will be removed in 1.36.0: use the 'inputs.nstat' plugin instead for protocol stats. But I can not net interface from input.nstat, such as net_bytes_recv、net_bytes_sent、net_packets_recv、net_packets_sent。

### Expected behavior

As mentioned above.

### Actual behavior

As mentioned above.

**Comment by powersj** [comment]
The entire plugin is not deprecated, only the option ignore_protoocl_stats if set to false. Youc an continue using the net plugin.
