### ISSUE TITLE
wireguard error when running telegraf in docker

### ISSUE THREAD

**Issue by pietrouk** [influxdata/telegraf#15664]
### Please direct all support questsions to slack or the forums. Thank you.

This is my docker compose:

`  telegraf:
    image: telegraf:latest
    container_name: telegraf
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host 
    volumes:
      - /home/pi/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/wireguard:/etc/wireguard`

I get this error:
`2024-07-25T09:01:20Z E! [inputs.wireguard] Error in plugin: error enumerating Wireguard devices: operation not permitted`

From the readme I understand I need to run the following command, but it's not clear to me how I can do it from within docker
`sudo setcap CAP_NET_ADMIN+epi $(which telegraf)`

**Comment by NiklasBeierl** [comment]
I think your problem originates from the fact that docker doesn't expose the hosts netlink interface, even with `network=host`, see here: https://github.com/docker/cli/issues/5576
