### ISSUE TITLE
dns_query input: Return query_time_ms when there is a timeout

### ISSUE THREAD

**Issue by smalenfant** [influxdata/telegraf#15715]
### Use Case

During graphing of DNS latency metrics, it should report query_time_ms to the timeout value. Currently seems like there is no issue unless you look at result codes. 

### Expected behavior

Report query_time_ms during query timeout

### Actual behavior

No query_time_ms reported when request is in timeout. Timeout was default (2s)

```
dns_query,hostname=myhostname,record_type=A,result=timeout,server=172.16.15.85 result_code=1i 1723055741000000000
```

**Comment by powersj** [comment]
Hi,

> Currently seems like there is no issue unless you look at result codes.

Looking at the code, the query time is always initialized to 0 and returns 0 when there is an issue, this is actually what I would expect if anything other than a valid query occurs.

Using the timeout value for timeouts does not cover the cases when other errors occur other than timeouts. Additionally, setting the query time to the timeout value can still make a user wonder why data is coming back in when the query may be failing.

**Comment by smalenfant** [comment]
It looks like timeout are a special case, maybe we could add the query_time_ms inside since it is covered by a special return. 

```
	addr := net.JoinHostPort(server, strconv.Itoa(d.Port))
	r, rtt, err := c.Exchange(&msg, addr)
	if err != nil {
		var opErr *net.OpError
		if errors.As(err, &opErr) && opErr.Timeout() {
			tags["result"] = "timeout"
			fields["result_code"] = uint64(Timeout)
                         fields["query_time_ms"] = float64(rtt.Nanoseconds()) / 1e6
			return fields, tags, err
		}
		return fields, tags, err
	}
```

**Comment by powersj** [comment]
Right, but it does not re-initialize the map. What version of telegraf are you running because this was not always the case.
