### ISSUE TITLE
NATS JetStream output ( in addition to the existing Kafka output ).

### ISSUE THREAD

**Issue by gedw99** [influxdata/telegraf#15710]
### Use Case

https://www.influxdata.com/time-series-platform/telegraf/ shows 1 of the 4  the supported outputs is Kafka.

I was wondering if a NATS Jetstream Output is worthy of addition and if the team and others would find it useful for their use cases.

My use case is a ton of scientists running experiments on diverse hardware. We are NATS Jetstream centric, and golang centric and have to run on Private and Public servers due to Government and Privacy restrictions of data. NATS is SOC 2 Type 1 certified too, with Type 2 happening soon, which helps with compliance. https://www.synadia.com/blog/synadia-soc2-compliant/

So if the Output was NATS Jetstream, it would open up the possibility of then reacting to the Metrics coming into NATS Jetstream in a myriad of possibilities.

The other thing about NATS Jetstream, is that it's easy (ish) to setup a global super cluster, and so have responsive endpoints everywhere, with mirroring between each DC your in. Any part can go down and come back up and it's all just fine. Its like having BGP / Anycast, without all the fuss.

It would not be that hard to add NATS Jetstream as an Output. https://github.com/nats-io/nats-kafka is one way...

### Expected behavior

none

### Actual behavior

none

**Comment by powersj** [comment]
Hi,

> https://github.com/influxdata/telegraf/blob/master/plugins/outputs/nats/nats.go looks like it does what I need ?

Right, we already have a NATS output that also has jetstream support.

Closing as completed, but if there is something missing in that output you can file a request.
