### ISSUE TITLE
Prevent discarding of messages in AMQP Consumer plugin

### ISSUE THREAD

**Issue by ptoews** [influxdata/telegraf#15741]
### Use Case

We're using the AMQP Consumer plugin with the JSON v2 decoder, and don't want to discard any messages going through our pipeline.
Specifically, even when the decoder cannot parse the incoming message because the decoder configuration is wrong.

### Expected behavior

The consumer should either crash or at least reject the message when it cannot be parsed (ideally depending on configuration)

### Actual behavior

The messages are discarded and (as I understand) even acknowledged to the broker.

### Additional info

I think this is the relevant part of the code: https://github.com/influxdata/telegraf/blob/fc198910cfd8ce849ed2a834de6038482cd62ead/plugins/inputs/amqp_consumer/amqp_consumer.go#L423-L432

**Comment by powersj** [comment]
Hi,

> The consumer should either crash or at least reject the message when it cannot be parsed (ideally depending on configuration)

Telegraf should never crash - a crash implies an unexpected error that was not recoverable and implies that the code needs better handling.

> Specifically, even when the decoder cannot parse the incoming message because the decoder configuration is wrong.

We acknowledge the message as we will never be able to parse the message given the current config. Without doing this, some users would have issues with Telegraf not removing messages from their queues. I understand that you are probably trying to get the parser going, in which case I would highly suggest you use some sample messages + the file input and get it working. Then you can switch over to the amqp consumer plugin and avoid discarding messages.

Depending on your output, you can also use the value processor, and pass on the raw message and not use Telegraf to parse the message.

I am not inclined to change this behavior, as it is consistent across all the other consumers as well without some larger justification.

**Comment by srebhan** [comment]
@powersj after studying https://www.rabbitmq.com/docs/confirms#basics I think that `d.Nack(false, false)` is the correct thing as it will give a negative confirmation and will **not** re-enqueue the message but send it to a "deadletter box" if configured. This leaves the server admin the possibility to decide if they want to drop or handle the message.

For backward compatibility reasons I would make this a config option, but I think the above `nack-requeue` should be the correct default.

**Comment by srebhan** [comment]
@ptoews please test the binary in PR #15796, available as soon as CI finished the tests, and let me know if this is what you had in mind! Messages will be NACKed on parsing errors and you can configure a dead-letter exchange for not loosing any of those...

**Comment by srebhan** [comment]
@ptoews any chance you can test this? There is a release on Monday and we would really like to include this fix...

**Comment by ptoews** [comment]
@srebhan Sorry for not responding, I am currently on vacation. Based on what I've read this is a great improvement, the messages will not be discarded and can be manually requeued after fixing the issue. However, this probably won't fully cover our requirements, as it would allow gaps in the data if later data can be correctly parsed; In our scenario, we would rather get no new data from a source until the issue is fixed than having a gap somewhere in the past that we have to fill. Maybe we can block/shutdown the pipeline if we receive messages in the dead letter queue.

Anyway, this solves the most important issue of not losing data, so thank you for the quick fix and I am looking forward to try it out!

**Comment by srebhan** [comment]
@ptoews thanks for letting me know! I will discuss with the team if we schedule the PR for the release on Monday or postpone to the next release leaving some time for testing...

**Comment by srebhan** [comment]
@ptoews we decided to get this thoroughly tested before merging to avoid this causing issues! Could you please test the PR as soon as you are back from vacation?

**Comment by ptoews** [comment]
@srebhan The download links in that PR don't work for me, I get a "not found"

**Comment by srebhan** [comment]
@ptoews we don't keep the binaries forever... ;-) I triggered a rebuild and the binaries should be available in about 30 min...

**Comment by ptoews** [comment]
Thanks! I just tested it and it works as expected. I configured a dead letter exchange for the queue that telegraf uses, and after applying an invalid telegraf config, it discards the messages from the original queue and I can receive them from a deadletter queue with lots of information about the rejection.
