### ISSUE TITLE
How to optimize ping plugin concurrency

### ISSUE THREAD

**Issue by CCIE1024** [influxdata/telegraf#15747]
### Please direct all support questsions to slack or the forums. Thank you.

[agent]
  interval = "1s"
  round_interval = true
  collection_jitter = "700ms"
  flush_interval = "1s"
  flush_jitter = "700ms"
  metric_batch_size = 50000
  metric_buffer_limit = 100000
  precision = "1ms"
  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_interval = "7d"
  logfile_rotation_max_size = "100MB"
  logfile_rotation_max_archives = 5

[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]

[[inputs.ping]]
  urls = ["100.9.4.13", ... # have 4000 IP 
  ]
  method = "native"
  ping_interval = 1.0
  timeout = 0.2
  deadline = 1

Above is my configuration file，then，i run
the task, log is show as below 
2024-08-16T01:50:53Z W! [inputs.ping] Collection took longer than expected; not complete after interval of 1s

how to optimize the concurrency

**Comment by srebhan** [comment]
As I said on Slack, all of the pings ARE already happening concurrently. You are creating 4000 threads every second flooding the network-interface with 4000 ICMP packets and expect this to come back... I don't think this will work as it will probably produce a high load on your scheduler, machine and network interface...
