### ISSUE TITLE
Cloudwatch input: some metrics can only be gathered on 3m or 5m period/delay (documentation & defaults issue)

### ISSUE THREAD

**Issue by zarnovican** [influxdata/telegraf#1574]
## Bug report

I have compared the list of series/fields returned by `cloudwatch` plugin with the list of metrics returned by `aws` command. Strangely, there is one _consistently_ missing in telegraf output.

All the examples below have counts specific to my case, since the number of metrics depend on number of AWS objects. I have tried to come up with a generic set of scripts, so that somebody else case verify this against a different AWS account.

I'm interested only in AWS/RDS namespace. I have tried two other namespaces (S3/EC2) and they _don't_ seem to be affected.
### Relevant telegraf.conf:

```
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"
  precision = "s"

[[inputs.cloudwatch]]
  access_key = 'xxx'
  secret_key = 'yyy'
  region = 'eu-west-1'
  period = '1m'
  delay = '1m'
  interval = '1m'
  namespace = 'AWS/RDS'
```
### System info:

Telegraf: 0.13.1, 1.0.0-beta3
### Steps to reproduce:
1. using the config above, run `telegraf -test -config telegraf.conf > telegraf.out`
2. produce a stripped down list of unique series and `_average` field

``` bash
cat telegraf.out | awk '$2 ~ /cloud/ { split($3,a,"="); print $2" "a[1] }' | sed -e 's/,region=[^ ,]*//' -e 's/,unit=[^ ,]*//' -e 's/,host=[^ ,]*//' | sort > telegraf_stripped.out
```
1. get a list metrics from Amazon using `aws` command

``` bash
aws cloudwatch list-metrics --namespace 'AWS/RDS' > aws.out
```
1. convert JSON to telegraf-like output using helper `awsmetric2series` script (see below for code).

``` bash
python awsmetric2series.py < aws.out | sort > aws_metrics.out
```
1. compare the two lists
### Expected behavior:

Ideally, those two lists should match one-to-one.
### Actual behavior:

There is a single line (in my case) that is _always_ missing from Telegraf, but the metric definitely exists in CloudWatch.

```
$ wc -l telegraf_stripped.out 
94 telegraf_stripped.out
$ wc -l aws_metrics.out 
95 aws_metrics.out
```

And it is always the same one:

```
$ diff -u telegraf_stripped.out aws_metrics.out
--- telegraf_stripped.out   2016-08-03 11:44:00.045268778 +0200
+++ aws_metrics.out 2016-08-03 11:43:40.014105917 +0200
@@ -19,6 +19,7 @@
 cloudwatch_aws_rds,database_class=db.m3.medium write_latency_average
 cloudwatch_aws_rds,database_class=db.m3.medium write_throughput_average
 cloudwatch_aws_rds database_connections_average
+cloudwatch_aws_rds,db_instance_identifier=emdb2 cpu_utilization_average
 cloudwatch_aws_rds,db_instance_identifier=emdb2 database_connections_average
 cloudwatch_aws_rds,db_instance_identifier=emdb2 disk_queue_depth_average
 cloudwatch_aws_rds,db_instance_identifier=emdb2 freeable_memory_average
```
### Additional info:

We have two RDS instances. The CPU untilization for the other one is fine.

```
$ grep cpu_utilization aws_metrics.out
cloudwatch_aws_rds cpu_utilization_average
cloudwatch_aws_rds,database_class=db.m3.medium cpu_utilization_average
cloudwatch_aws_rds,db_instance_identifier=emdb2 cpu_utilization_average
cloudwatch_aws_rds,db_instance_identifier=emdb3 cpu_utilization_average
cloudwatch_aws_rds,engine_name=postgres cpu_utilization_average
```

```
$ grep cpu_utilization telegraf_stripped.out 
cloudwatch_aws_rds cpu_utilization_average
cloudwatch_aws_rds,database_class=db.m3.medium cpu_utilization_average
cloudwatch_aws_rds,db_instance_identifier=emdb3 cpu_utilization_average
cloudwatch_aws_rds,engine_name=postgres cpu_utilization_average
```

Very rough script `awsmetric2series.py` to convert `aws` json output to flat list.
https://gist.github.com/zarnovican/f2b268ffe19c5a0a69d275ac3f81a34b#file-awsmetric2series-py

``` python
from __future__ import print_function

import json
import re
import sys

def snake_case(name):
    name = name.replace('/', '_')
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

j = json.load(sys.stdin)

for m in j['Metrics']:
    print('cloudwatch_'+snake_case(m['Namespace']), end='')
    d = [ snake_case(dim['Name'])+'='+dim['Value'] for dim in m['Dimensions'] ]
    if len(d) > 0:
        print(','+','.join(d), end='')
    print(' ', end='')
    print(snake_case(m['MetricName']+'_average'))
```

**Comment by sparrc** [comment]
any ideas @johnrengelman @joshglympse ?

**Comment by johnrengelman** [comment]
@zarnovican can you replace the single quotes `'` with double quotes `"` and try again? When I tested locally, I found that single quoted values for any of the durations where not correctly parsed and were thus resulting in invalid queries to cloudwatch (because they would default to 0 seconds).

**Comment by johnrengelman** [comment]
@zarnovican I did some testing with one of my larger accounts tonight and this is what I found.
When I queried Cloudwatch directly, I saw 408 possible metrics.
When I used your configuration above, Telegraf would output a variable amount, generally in the ~350 - 360 range.

I then tried upping the `period` and `delay` numbers and as I increased them, I would get outputs closer to 408, but they were still variable. 
Once I got to `period="5m"` and `delay="5m"`, then Telegraf was consistently outputting the same 408 metrics as I was getting from Cloudwatch.

I also found this line in the Cloudwatch docs: https://aws.amazon.com/cloudwatch/faqs/#monitoring
> The minimum granularity supported by CloudWatch is 1 minute data points. Many metrics are received and aggregated at 1-minute intervals. Some are received at 3-minute or 5-minute intervals.

So, you will for sure not get all the metrics when using a 1 minute granularity b/c cloudwatch will simply not return metrics that are not available at that level (lame)

Ultimately, I don't think there is a bug here (at least I haven't been able to find one that doesn't resolve by increasing the `period` and `delay` values), and it's just dealing with the complexities of the cloudwatch API.

**Comment by sparrc** [comment]
thanks for the sleuthing @johnrengelman, I will close this issue once we've updated the documentation to account for this. We might also want to increase the default values for `period` and `delay` to `5m`?

**Comment by zarnovican** [comment]
Hi have re-tested the issue today and I'm not able to reproduce it anymore. I have tested telegraf 0.13.1, 1.0.1 and intervals 1m, 10m. None of the four combinations produced the original problem. My conclusion is that _something_ probably changed on AWS end.

BTW, I have switched from 1m to 10m interval some time ago. The reasons were financial. On 1m interval, the number of CloudWatch queries was above the AWS free threshold 1mil/month.

**Comment by johnrengelman** [comment]
@sparrc I don't think we should set the minimum as there are metrics that you can get at 1 and 3 mins. So it should be up to you. You'd just have to break at those metrics into a separate input. 

I think updating the docs with this info and including a note in the sample config comments should be sufficient.

**Comment by johnrengelman** [comment]
@sparrc just re-read your comment so I'll clarify mine.
I will submit a PR to update the defaults to `"5m"` as that is more appropriate and offers a better initial UX. But we wont' prevent a user from decreasing it. (Thought your comment was to set the minimum).

**Comment by sparrc** [comment]
@johnrengelman was this just a defaults/doc issue? can this be closed?

**Comment by sparrc** [comment]
going to close for now, let me know if this isn't solved and I'll reopen
