### ISSUE TITLE
Information about to set time zone into outputs.postgresql code in Telegraf

### ISSUE THREAD

**Issue by Paolo5196** [influxdata/telegraf#15765]
### Please direct all support questsions to slack or the forums. Thank you.

Hello everybody!

For my work I start to use InfluxDB with the its plug-in Telegraf.

The my scope is this: I read he data some Modbus device confiurated into the filed and then I use the outputs.postgresql into the Telegraf for report the data read in my Postgresql database.

My problem is the time zone used from Telegraf for write the data; because it use the UTC time and not Italian time.

Is there a setting to insert into outputs.postgresql for export into Postgesql database the correct Italian timestamp?

Now I set it like these:

_[[outputs.postgresql]]
  connection = "host=localhost user=postgres password=postgress sslmode=disable dbname=influxpg"
  ##tags_as_foreign_keys=true
  #timestamp_column_name = "dthhrl"
  timestamp_column_type = "timestamp without time zone"
  tagexclude = ["type"]_

Many thanks for the future answers :)

Paolo

**Comment by srebhan** [comment]
According to the [PostgreSQL documentation](https://www.postgresql.org/docs/current/datatype-datetime.html#:~:text=PostgreSQL%20assumes%20your%20local%20time,being%20displayed%20to%20the%20client.):
All timezone-aware dates and times are stored internally in UTC. They are converted to local time in the zone specified by the [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) configuration parameter before being displayed to the client... So what do you expect Telegraf to do?
