### ISSUE TITLE
Wrong type for field [[inputs.mysql]]

### ISSUE THREAD

**Issue by dmgeurts** [influxdata/telegraf#15786]
After configuring Telegraf for monitoring a Galera cluster I get the following error, have I configured something double/wrong?

```
[outputs.influxdb_v2] Failed to write metric to ipn_mysql (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "wsrep_local_recv_queue_avg" on measurement "mysql" is type integer, already exists as type float dropped=2
[outputs.influxdb_v2] Failed to write metric to ipn_mysql (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "wsrep_flow_control_paused" on measurement "mysql" is type integer, already exists as type float dropped=1
```

Telegraf v1.31.1
InfluxDB v2.7.10
Plugin config:

```
[[inputs.mysql]]
  flush_interval = "30s"
  interval = "30s"
  metric_buffer_limit = 15000
  servers = ["telegraf@unix(/run/mysqld/mysqld.sock)/"]
  metric_version = 2
  gather_table_schema = true
  table_schema_databases = []
  gather_process_list = true
  gather_user_statistics = false
  gather_info_schema_auto_inc = false
  gather_innodb_metrics = false
  mariadb_dialect = true
  gather_global_variables = true
  gather_table_io_waits = true
  gather_table_lock_waits = true
  gather_index_io_waits = true
  gather_event_waits = true
  gather_file_events_stats = false
  gather_perf_events_statements = false
  gather_perf_sum_per_acc_per_event = false
  perf_events_statements_digest_text_limit = 120
  perf_events_statements_limit = 250
  perf_events_statements_time_limit = 86400
  interval_slow = "30m"
  [inputs.mysql.tags]
    type = "MySQL"
```

I recreated the bucket, to see if a config change had changed the format of a field, but the issue remained.
`wsrep_flow_control_paused` does appear in the bucket and is updated, but `wsrep_flow_control_paused` is not. How can it have a type recorded when there’s no value for it?

It seems that the input plugin is wrongly selecting integer when writing this value as in fact it’s a float:

```
MariaDB [(none)]> SHOW STATUS LIKE 'wsrep_flow_control_%';
+------------------------------+-------------+
| Variable_name                | Value       |
+------------------------------+-------------+
| wsrep_flow_control_paused_ns | 81185199    |
| wsrep_flow_control_paused    | 0.000136925 |
| wsrep_flow_control_sent      | 0           |
| wsrep_flow_control_recv      | 2           |
| wsrep_flow_control_active    | false       |
| wsrep_flow_control_requested | false       |
+------------------------------+-------------+
6 rows in set (0.001 sec)
```

[Slack Message](https://influxcommunity.slack.com/archives/CH99HUH8V/p1724779593314899)

Workaround:

```
[[processors.converter]]
  [processors.converter.fields]
    float = ["wsrep_flow_control_paused","wsrep_local_recv_queue_avg","wsrep_apply_oool","wsrep_cert_deps_distance"]
```

**Comment by srebhan** [comment]
@dmgeurts please test the binary in PR #15791, available as soon as CI finished the tests, and let me know if this fixes the issue!

**Comment by dmgeurts** [comment]
Thank you, testing now. I say your comment about which should be float and which should be int. I don't have a definitive list but would grep the URL I sent you myself.

The latest code has made `wsrep-flow-control-paused-ns` a float when it is an integer.

This is my extrapolation from the URL I sent:

```
_Field                	Source	Example	Type
wsrep_commit_oooe	Galera	0	Float
wsrep_commit_oool	Galera	0	Float
wsrep_commit_window	Galera	0	Float
wsrep_desync_count	Galera	0	Integer
wsrep_local_recv_queue	Galera	0	Integer
wsrep_local_recv_queue_min	Galera	0	Integer
wsrep_local_replays	Galera	0	Integer
wsrep_local_send_queue_min	Galera	0	Integer
wsrep_repl_other_bytes	Galera	0	Integer
wsrep_local_send_queue_avg	Galera	0.145	Float
wsrep_flow_control_paused	Galera	0.184353	Float
wsrep_apply_oool	Galera	0.195248	Float
wsrep_apply_oooe	Galera	0.67112	Float
wsrep_local_index	Galera	1	Integer
wsrep_local_send_queue	Galera	1	Integer
wsrep_gmcast_seqment	Galera	2	Integer
wsrep_cluster_weight	MySQL	3	Integer
wsrep_open_connections	Galera	3	Integer
wsrep_local_recv_queue_avg	Galera	3.348452	Float
wsrep_local_state	Galera	4	Integer
wsrep_protocol_version	Galera	4	Integer
wsrep_apply_window	Galera	5.163966	Float
wsrep_flow_control_sent	Galera	7	Integer
wsrep_local_recv_queue_max	Galera	10	Integer
wsrep_local_send_queue_max	Galera	10	Integer
wsrep_flow_control_recv	Galera	11	Integer
wsrep_cert_deps_distance	Galera	23.88889	Float
wsrep_open_transactions	Galera	25	Integer
wsrep_cluster_conf_id	MySQL	34	Integer
wsrep_local_cert_failures	Galera	333	Integer
wsrep_local_bf_aborts	Galera	960	Integer
wsrep_apply_waits	Galera	13549	Integer
wsrep_local_commits	Galera	14981	Integer
wsrep_replicated	Galera	16109	Integer
wsrep_received	Galera	17831	Integer
wsrep_cert_index_size	Galera	30936	Integer
wsrep_last_committed	Galera	409745	Integer
wsrep_repl_keys	Galera	797399	Integer
wsrep_replicated_bytes	Galera	6526788	Integer
wsrep_received_bytes	Galera	6637093	Integer
wsrep_repl_keys_bytes	Galera	11203721	Integer
wsrep_repl_data_bytes	Galera	265035226	Integer
wsrep_flow_control_paused_ns	Galera	20222491180	Integer
```

**Comment by srebhan** [comment]
@dmgeurts I updated the PR. Please test and double check the fields I changed in [here](https://github.com/influxdata/telegraf/pull/15791/files)!

**Comment by dmgeurts** [comment]
Thank you. Please can you change `"wsrep_flow_control_paused_ns": ParseFloat,` to an Integer?

**Comment by dmgeurts** [comment]
Thank you, will test as soon as the code is available, but it may end up being next week.

**Comment by srebhan** [comment]
@dmgeurts ping... We do have a release on Monday and I would love to include this fix if possible...

**Comment by dmgeurts** [comment]
Thank you for the reminder, will test now.

**Comment by dmgeurts** [comment]
I'm getting a 404 on the [*amd64.deb](https://output.circle-artifacts.com/output/job/2365a68f-0b85-4f19-b91a-c6951903a689/artifacts/0/build/dist/telegraf_1.32.0~4e0a8e92-0_amd64.deb) download.

**Comment by srebhan** [comment]
That's because you waited for too long... ;-) Triggered a rebuild that should be finished in ~30min. Let me know if you do have any issues afterwards...

**Comment by dmgeurts** [comment]
I think we have a winner ! Thank you

**Comment by dmgeurts** [comment]
Spoke too soon, 'wsrep_cert_interval' is also a float... Gah, not documented in the Galera documentation. Let me check the actual values reported for the entries without examples. Sorry, I could have done this earlier.

**Comment by dmgeurts** [comment]
I've just checked the other 'non-example' wsrep variables and none of them have a value of type float.

**Comment by srebhan** [comment]
So this leaves us with `wsrep_cert_interval`?

**Comment by srebhan** [comment]
@dmgeurts added `wsrep_cert_interval` to the float list...

**Comment by srebhan** [comment]
@dmgeurts could you give this a final test?

**Comment by dmgeurts** [comment]
So far so good!

**Comment by srebhan** [comment]
Please keep the issue open until the PR is merged, which will automatically close the issue. This way we can keep track of what is fixed in master and what is not, making the issue discoverable to others...
