### ISSUE TITLE
Unable to drop a measurement created by telegraf

### ISSUE THREAD

**Issue by stevenh** [influxdata/telegraf#1579]
## Bug report
It seems be be impossible to drop a measurement without first stopping telegraf.

### System info:
influxdb 0.12.2
telegraf 0.13.1
linux 3.10
telegraf.conf
```conf
[[inputs.statsd]]
  allowed_pending_messages = 100000
  delete_counters = false
  delete_gauges = false
  delete_sets = false
  delete_timings = false
  metric_separator = "."
  percentile_limit = 1000
  percentiles = [50, 90, 99]
  service_address = ":8125"
```
### Steps to reproduce:
1. Run telegraf and ingest some stats via the statsd plugin.
2. Reconfigure telegraf so the stats are renamed e.g. change metric_separator .
3. Drop the old measurements using influx cli
4. List measurements and the drop measurement will be back.

### Expected behavior:
Dropped measurements should stay dropped unless the generator is still sending them.

### Actual behavior:
Measurements that are no longer being reported via statsd protocol either due to a client change or a telegraf configuration change so the names are now different are re-created.

**Comment by stevenh** [comment]
Telegraf doesn't seem to be only factor here even with it off something seems to be still re-creating the metrics, which is even more strange given statds plugin in Telegraf is how the stats are actually getting ingested in, so with it off there should be nothing adding new stats.

**Comment by sparrc** [comment]
telegraf doesn't dynamically load the configuration file, so I think the problem is just that telegraf is still running with the old config, likely a dupe of #272

**Comment by stevenh** [comment]
I pretty sure that's not the case @sparrc as I've restarted Telegraf and now turned it off, and its still happening, so it may well not be Telegraf, investigating more as what worked to enable us to delete measurements in labs isn't working in production and its most odd.

**Comment by stevenh** [comment]
Closing as this is actually a bug in influxdb see: https://github.com/influxdata/influxdb/issues/7112#event-744621177
