### ISSUE TITLE
Linter: revive, Rule: `banned-characters` - Checks given banned characters in identifiers(func, var, const). Comments are not checked. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15804]
### Description

This issue starts a discussion about enabling:
- linter: [revive](https://revive.run/) - Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. Revive provides a framework for development of custom rules, and lets you define a strict preset for enhancing your development & code review processes.
- rule: [banned-characters](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#banned-characters) - Checks given banned characters in identifiers(func, var, const). Comments are not checked..

### Configuration:

This rule requires a slice of strings, the characters to ban.

#### Example configuration:

```
      - name: banned-characters
        arguments: ["Ω", "Σ", "σ"]
```

### Expected output

Decision about enabling or not enabling this rule.

### Findings

For this rule (with default configuration), no findings were found in the current codebase.

**Comment by zak-pawel** [comment]
It makes sense to enable this one, if we have an idea for a list of those characters.

**Comment by srebhan** [comment]
Can we whitelist chars? If so I think `[a-zA-Z0-9]` is a good starting point....

**Comment by zak-pawel** [comment]
> Can we whitelist chars?

@srebhan I don't think so.

**Comment by srebhan** [comment]
Then I would keep this one disabled and reject strange names during review...

**Comment by zak-pawel** [comment]
I feel the same way.
