### ISSUE TITLE
Linter: revive, Rule: `get-return` - Checks if functions with names prefixed with `Get` return values. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15819]
### Description

This issue starts a discussion about enabling:
- linter: [revive](https://revive.run/) - Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. Revive provides a framework for development of custom rules, and lets you define a strict preset for enhancing your development & code review processes.
- rule: [get-return](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#get-return) - Typically, functions with names prefixed with Get are supposed to return a value.

#### Example configuration:

```
      - name: get-return
```

### Expected output

Decision about enabling or not enabling this rule.

### Findings

For this rule (with above configuration), the following findings were found in the current codebase:
```
config/config.go:1615:1                             revive  get-return: function 'getFieldString' seems to be a getter but it does not return any result
config/config.go:1625:1                             revive  get-return: function 'getFieldDuration' seems to be a getter but it does not return any result
config/config.go:1641:1                             revive  get-return: function 'getFieldBool' seems to be a getter but it does not return any result
config/config.go:1666:1                             revive  get-return: function 'getFieldInt' seems to be a getter but it does not return any result
config/config.go:1681:1                             revive  get-return: function 'getFieldInt64' seems to be a getter but it does not return any result
config/config.go:1698:1                             revive  get-return: function 'getFieldStringSlice' seems to be a getter but it does not return any result
config/config.go:1715:1                             revive  get-return: function 'getFieldTagFilter' seems to be a getter but it does not return any result
plugins/aggregators/basicstats/basicstats.go:265:1  revive  get-return: function 'getConfiguredStats' seems to be a getter but it does not return any result
plugins/inputs/smart/smart.go:555:1                 revive  get-return: function 'getAttributes' seems to be a getter but it does not return any result
plugins/inputs/smart/smart.go:572:1                 revive  get-return: function 'getVendorNVMeAttributes' seems to be a getter but it does not return any result
```

**Comment by zak-pawel** [comment]
I would enable it.

**Comment by srebhan** [comment]
Agreed as not returning this is somewhat confusing. However, we need to come up with a better name for the pattern
```golang
func getSomething(a interface{}, b *string) {
  if v, ok := a.(string); ok {
    *b = a
  }
}
```
which is what most of those functions do IMO... Any suggestions?

**Comment by zak-pawel** [comment]
@srebhan `set` instead of `get`? 😁

**Comment by srebhan** [comment]
Well `set` has another ambiguity and doesn't really improve semantics IMO... Maybe we can convert the function to not take a pointer but actually return the value?

**Comment by DStrand1** [comment]
> Well `set` has another ambiguity and doesn't really improve semantics IMO... Maybe we can convert the function to not take a pointer but actually return the value?

I agree with this suggestion, and enabling the linter as well
