### ISSUE TITLE
Linter: revive, Rule: `enforce-repeated-arg-type-style` - Maintains consistency in the declaration of repeated argument and return value types in Go functions. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15811]
### Description

This issue starts a discussion about enabling:
- linter: [revive](https://revive.run/) - Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. Revive provides a framework for development of custom rules, and lets you define a strict preset for enhancing your development & code review processes.
- rule: [enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) - This rule is designed to maintain consistency in the declaration of repeated argument and return value types in Go functions. It supports three styles: `any`, `short`, and `full`. The `any` style is lenient and allows any form of type declaration. The `short` style encourages omitting repeated types for conciseness, whereas the `full` style mandates explicitly stating the type for each argument and return value, even if they are repeated, promoting clarity.

### Configuration:

_Configuration (1)_: (string) as a single string, it configures both argument and return value styles. Accepts `any`, `short`, or `full` (default: `any`).

_Configuration (2)_: (map[string]any) as a map, allows separate configuration for function arguments and return values. Valid keys are `"funcArgStyle"` and `"funcRetValStyle"`, each accepting `any`, `short`, or `full`. If a key is not specified, the default value of `any` is used.

_Note_: The rule applies checks based on the specified styles. For `full` style, it flags instances where types are omitted in repeated arguments or return values. For `short` style, it highlights opportunities to omit repeated types for brevity. Incorrect or unknown configuration values will result in an error.

#### Example configuration:

Example (1):

```
      - name: enforce-repeated-arg-type-style
        arguments: ["short"]
```

Example (2):

```
      - name: enforce-repeated-arg-type-style
        arguments:
          - funcArgStyle: "full"
          - funcRetValStyle: "short"
```

### Expected output

Decision about enabling or not enabling this rule.

### Findings

For this rule, with configuration 1, `254` findings (of type: `enforce-repeated-arg-type-style: repeated argument type can be omitted` / `enforce-repeated-arg-type-style: repeated return type can be omitted`) were found in the current codebase.

For this rule, with configuration 2, `283` findings (of type: `enforce-repeated-arg-type-style: argument types should not be omitted`) were found in the current codebase.

**Comment by srebhan** [comment]
@zak-pawel could you please provide an example? I'm not sure I understand what this checks... Is it only the function-declaration style?

**Comment by zak-pawel** [comment]
@srebhan 
`short` will complain about:
```
func method(arg1 string, arg2 string) (ret1 string, ret2 string) {
	return "", ""
}
```
--v
```
enforce-repeated-arg-type-style: repeated argument type can be omitted
enforce-repeated-arg-type-style: repeated return type can be omitted
```


`full` will complain about:
```
func method(arg1, arg2 string) (ret1, ret2 string) {
	return "", ""
}
```
--v
```
enforce-repeated-arg-type-style: argument types should not be omitted
enforce-repeated-arg-type-style: return types should not be omitted
```


Arguments style and returned values style can be configured independently.

**Comment by srebhan** [comment]
Ahhhh I see. I don't prefer one over the other but a consistent style would make sense. Maybe `short` then as it is shorter? ;-)

**Comment by zak-pawel** [comment]
I'm ok with that

**Comment by DStrand1** [comment]
I agree, lets go with `short`
