### ISSUE TITLE
Linter: revive, Rule: `file-header` - Helps to enforce a common header for all source files. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15816]
### Description

This issue starts a discussion about enabling:
- linter: [revive](https://revive.run/) - Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. Revive provides a framework for development of custom rules, and lets you define a strict preset for enhancing your development & code review processes.
- rule: [file-header](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#file-header) - This rule helps to enforce a common header for all source files in a project by spotting those files that do not have the specified header.

### Configuration:

(string) the header to look for in source files.

#### Example configuration:

```
      - name: file-header
        arguments:
          - This is the text that must appear at the top of source files.
```

### Expected output

Decision about enabling or not enabling this rule.

**Comment by zak-pawel** [comment]
If we don't intend to enforce a header in every file, then this rule doesn't make sense for us.

Example of header:
```
// Copyright 2024 The Telegraf Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
```

**Comment by srebhan** [comment]
We had such a header way back IIRC and decided to remove it, so -1 on this one.
