### ISSUE TITLE
Linter: revive, Rule: `enforce-map-style` - Enforces consistent usage of `make(map[type]type)` or `map[type]type{}` for map initialization. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#15810]
### Description

This issue starts a discussion about enabling:
- linter: [revive](https://revive.run/) - Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. Revive provides a framework for development of custom rules, and lets you define a strict preset for enhancing your development & code review processes.
- rule: [enforce-map-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-map-style) - This rule enforces consistent usage of `make(map[type]type)` or `map[type]type{}` for map initialization. It does not affect `make(map[type]type, size)` constructions as well as `map[type]type{k1: v1}`.

### Configuration:

(string) Specifies the enforced style for map initialization. The options are:
- "any": No enforcement (default).
- "make": Enforces the usage of `make(map[type]type)`.
- "literal": Enforces the usage of `map[type]type{}`.

#### Example configuration:

1:
```
      - name: enforce-map-style
        arguments: ["make"]
```

2:
```
      - name: enforce-map-style
        arguments: ["literal"]
```

### Expected output

Decision about enabling or not enabling this rule.

### Findings

For this rule, with configuration 1, `1519` findings (of type: `enforce-map-style: use make(map[type]type) instead of map[type]type{}`) were found in the current codebase.

For this rule, with configuration 2, `825` findings (of type: `enforce-map-style: use map[type]type{} instead of make(map[type]type)`) were found in the current codebase.

**Comment by srebhan** [comment]
I'm a fan of `map[type]type{}` where ever possible as this is more readable IMO. So I'm inclined to enable this rule.

**Comment by zak-pawel** [comment]
And I'm a fan of using `make(map[type]type)` ;)
I wonder if it makes sense to enable this rule, just to force the developer to use a version that they may not necessarily like. 
After all, both versions work in exactly the same way.

**Comment by srebhan** [comment]
Maybe I misunderstood the rule... I like
```golang
a := make(map[string]string, len(x))
for k, v := range x {
  a[k] = v
}
```
but
```golang
b := map[string]string {
  "source": host,
  "machine": "warp drive",
}
```

**Comment by zak-pawel** [comment]
@srebhan This rule enforces the initialization of **only empty maps** in a chosen way.

So:
`a := make(map[string]string)` or `a := map[string]string{}`

**Comment by srebhan** [comment]
Then I'd prefer the `make` way!

**Comment by zak-pawel** [comment]
@srebhan 
Yes, me too. 
But my question is this: do we want to force this on developers? This is only a matter of preference, each of these options does exactly the same thing and is just as fast, so there will be no gain from performance improvement.

**Comment by srebhan** [comment]
Having a consistent uniform way of doing things improves readability IMO so I do see value in enforcing this.
