### ISSUE TITLE
ADAL in use after it has bee deprecated

### ISSUE THREAD

**Issue by przemas75** [influxdata/telegraf#15848]
### Relevant telegraf.conf

```toml
none
```

### Logs from Telegraf

```text
none
```

### System info

Telegraf 1.31.3 all

### Steps to reproduce

1. https://github.com/influxdata/telegraf/blob/fc2d71474c4ec58fcc1cd3795aa9394de3acace0/go.mod#L20
2.
3.
...

### Expected behavior

Removal of this dependency. MSAL is already included.

### Actual behavior

ADAL stil in place.

### Additional info

I can't find any info regarding ADAL removal, since it was deprecated like a year ago:
https://learn.microsoft.com/en-us/entra/identity-platform/msal-migration

**Comment by srebhan** [comment]
@przemas75 can we be sure this will not work with any of the Azure instances out there anymore? Citing from the page you linked:

>While existing apps that use ADAL will continue to work, Microsoft will no longer release security fixes on ADAL.

So removing this would likely break those existing apps, won't it? How about adding the new mechanism and print a warning if someone chooses to use ADAL?
