### ISSUE TITLE
Error on connect to proxy Server 

### ISSUE THREAD

**Issue by Farhaddll1993** [influxdata/telegraf#15851]
### Please direct all support questsions to slack or the forums. Thank you.

Hi guys. 
I have installed lots of package on ubuntu as proxy server likes shadowSocks, dante-sever , squid and etc...
I couldn't connect to node.js 
I think I had problem on packages.

Could you please tell me Which package I have to install on ubunto to use as httpProxyServer and how should I configure it in my node.js application for telegraf and how should I my Proxy Agent?

Thank you for your helping.

**Comment by srebhan** [comment]
@Farhaddll1993 are you, by chance, looking for the bot-framework over at https://github.com/telegraf/telegraf? This is the data-collection agent and I cannot figure out what the issue is based on the information you provide... :-)
