### ISSUE TITLE
Allow the use of secrets for HTTP Basic Authentication in the prometheus input plugin 

### ISSUE THREAD

**Issue by harsh-w** [influxdata/telegraf#15855]
### Use Case

The prometheus input plugin supports HTTP Basic Authentication with ```username``` and ```password``` fields. However, these cannot be secrets  

For example the below config will NOT work
```
# Read metrics from one or many prometheus clients
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9100/metrics"]

 ## HTTP Basic Authentication username and password. ('bearer_token' and
  ## 'bearer_token_string' take priority)
  username = "@{mystore:user_secret}"
  password = "@{mystore:pass_secret}"
```

### Expected behavior

assuming a ```secretstore.os``` with ```id = mystore```, then ```username``` and ```password``` should be loaded from the store with the corresponding values of ```user_secret``` and ```pass_secret```

### Actual behavior

Since username and password are defined in prometheus.go as ```string``` instead of ```config.Secret``` the string value is taken viz "@{...}" instead of the value being replaced by the secret. Thus hardcoding the username and password works. However when using the "@{}" notation, there's no replacement and any prometheus URL that is protected by Basic Auth fails with a 401:Unauthorized

### Additional info

it's easy to change the behavior 

in ```telegraf/plugins/inputs/prometheus/prometheus.go```, struct Prometheus is defined as 
```
type Prometheus struct {
	URLs                 []string          `toml:"urls"`
	BearerToken          string            `toml:"bearer_token"`
	BearerTokenString    string            `toml:"bearer_token_string"`
	Username             string            `toml:"username"`
	Password             string            `toml:"password"`
```

This can change to 
```
type Prometheus struct {
	URLs                 []string          `toml:"urls"`
	BearerToken          string            `toml:"bearer_token"`
	BearerTokenString    string            `toml:"bearer_token_string"`
	Username             config.Secret     `toml:"username"`
	Password             config.Secret     `toml:"password"`
```

```func (p *Prometheus) gatherURL``` then needs to handle ```Username``` and ```Password``` appropriately

**Comment by srebhan** [comment]
@harsh-w please test the binary in PR #15865, available as soon as CI finished the tests, and let me know if this fixes the issue!
