### ISSUE TITLE
AWS EC2 issues

### ISSUE THREAD

**Issue by kirillmandrygin** [influxdata/telegraf#15906]
Some additional feature was added to aws ec2 processor here: #15795 , and It is working good but I have two issues:

1. Error when I run telegraf with --test:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x740411b]

goroutine 109 [running]:
github.com/influxdata/telegraf/plugins/processors/aws_ec2.(*AwsEc2Processor).Stop(0xc00252e9c0?)
	/go/src/github.com/influxdata/telegraf/plugins/processors/aws_ec2/ec2.go:166 +0x3b
github.com/influxdata/telegraf/models.(*RunningProcessor).Stop(...)
	/go/src/github.com/influxdata/telegraf/models/running_processor.go:115
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc001fec0c0)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:666 +0x172
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors in goroutine 14
	/go/src/github.com/influxdata/telegraf/agent/agent.go:656 +0x3e
```

2. Metadata tag added with slash (for example: `test_metric{/Name="test-instance"}`), is this expected behaviour?

**Comment by srebhan** [comment]
@kirillmandrygin please test the binary in PR #15965, available once CI finished the tests, and let me know if this fixes your issues!

**Comment by srebhan** [comment]
@kirillmandrygin could you please test the fix ASAP so we can include it in today's release?!?

**Comment by kirillmandrygin** [comment]
@srebhan yes, I can, please give me 30 minutes

**Comment by kirillmandrygin** [comment]
@srebhan I have an issue with downloading the build artifacts: https://github.com/influxdata/telegraf/pull/15965#issuecomment-2396253351

**Comment by kirillmandrygin** [comment]
@srebhan I can confirm it is working good now, I don't have any errors and i get name of tags without slash. Thank you!
