### ISSUE TITLE
Kafka producer w/json format

### ISSUE THREAD

**Issue by MikeMester** [influxdata/telegraf#1590]
We are looking at using the Kafka output functionality of telegraf.  We do notice a small amount of errors when data is sent via the kafka output when the data format is selected as json.  The lab setup is:

Telegraf -> kafka <- streamsets 

We like to use kafka in the middle because we will have multiple consumers on the backend.  JSON allows us to edit the fields in streamsets.  

Occasionally I get a record that looks a bit like this.
"Y3B1LGNwdT1jcHUxLGhvc3Q9a2Fma2EtMDEgdXNhZ2VfZ3Vlc3Q9MCx1c2FnZV9ndWVzdF9uaWNlPTAsdXNhZ2VfaWRsZT05OC40OTI0NjIzMTEzMzQzNix1c2FnZV9pb3dhaXQ9MCx1c2FnZV9pcnE9MCx1c2FnZV9uaWNlPTAsdXNhZ2Vfc29mdGlycT0wLHVzYWdlX3N0ZWFsPTAsdXNhZ2Vfc3lzdGVtPTAuMzAxNTA3NTM3Njg2MDUxNDMsdXNhZ2VfdXNlcj0xLjIwNjAzMDE1MDc0NTM0ODEgMTQ3MDQ2NTQ0MDAyMDM5NjU5NQ=="

probably every 6-7 records.

thanks,

Mike

**Comment by sparrc** [comment]
that is strange, can you provide your version, configuration, and any steps to reproduce?

**Comment by MikeMester** [comment]
Telegraf - version 0.13.2
Kafka version - (we use confluent.io version 3.0 platform.  pretty sure its 0.10)

Steps are just startup the agent and try to consume off the topic.  I use streamsets.  www.streamsets.com.  Setup a kafka origin of 0.9+ library and start up the pipeline.  Some of the records will be fine json docs, others will be the garbage above.

`# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply prepend
# them with $. For strings the variable must be within quotes (ie, "$STR_VAR"),
# for numbers and booleans they should be plain (ie, $INT_VAR, $BOOL_VAR)


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at
  ## most metric_batch_size metrics.
  metric_batch_size = 1000
  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## Run telegraf in debug mode
  debug = true
  ## Run telegraf in quiet mode
  quiet = false
  ## Override default hostname, if empty use os.Hostname()
  hostname = "{{ ansible_hostname }}"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.kafka]]
  ## URLs of kafka brokers
  brokers = ["kafka-01:9092"]
  ## Kafka topic for producer messages
  topic = "telegraf"
  ## Telegraf tag to use as a routing key
  ##  ie, if this tag exists, it's value will be used as the routing key

  ## CompressionCodec represents the various compression codecs recognized by
  ## Kafka in messages.
  ##  0 : No compression
  ##  1 : Gzip compression
  ##  2 : Snappy compression
  compression_codec = 0

  ##  RequiredAcks is used in Produce Requests to tell the broker how many
  ##  replica acknowledgements it must see before responding
  ##   0 : the producer never waits for an acknowledgement from the broker.
  ##       This option provides the lowest latency but the weakest durability
  ##       guarantees (some data will be lost when a server fails).
  ##   1 : the producer gets an acknowledgement after the leader replica has
  ##       received the data. This option provides better durability as the
  ##       client waits until the server acknowledges the request as successful
  ##       (only messages that were written to the now-dead leader but not yet
  ##       replicated will be lost).
  ##   -1: the producer gets an acknowledgement after all in-sync replicas have
  ##       received the data. This option provides the best durability, we
  ##       guarantee that no messages will be lost as long as at least one in
  ##       sync replica remains.
  required_acks = 1

  ##  The total number of times to retry sending a message
  max_retry = 3

  ## Optional SSL Config
  # ssl_ca = "/etc/telegraf/ca.pem"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false

  ## Data format to output.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"



###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]


# Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  ## Only collect metrics for these containers, collect all if empty
  container_names = []
  ## Timeout for docker list, info, and stats commands
  timeout = "5s"


# Read metrics about memory usage
[[inputs.mem]]
  # no configuration


# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  # interfaces = ["eth0"]


# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration`

**Comment by MikeMester** [comment]
![screen shot 2016-08-06 at 1 58 18 am](https://cloud.githubusercontent.com/assets/5067775/17455321/83bdea62-5b79-11e6-84f2-cc4e9d82c3cf.png)
![screen shot 2016-08-06 at 1 58 32 am](https://cloud.githubusercontent.com/assets/5067775/17455322/895b83c6-5b79-11e6-90a9-ccaf4a5a0e4e.png)

**Comment by MikeMester** [comment]
Also I should note that this is CentOs 7.  The install was straight from the influxdb yum repo.

**Comment by sparrc** [comment]
@MikeMester if you setup your telegraf configuration with a `file` output do you get the same messages? you can do it like this:

```toml
# Send telegraf metrics to file(s)
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

  ## Data format to output.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"
```

this will output the messages to stdout and will make it easier to reproduce and debug.

**Comment by sparrc** [comment]
@MikeMester, the messages that you are receiving are base64 encoded influx line-protocol. I don't think that this is coming from telegraf, especially since your config is setup to output the data in json.
