### ISSUE TITLE
Write CSV Header with Every Remote File

### ISSUE THREAD

**Issue by caallinson** [influxdata/telegraf#15912]
### Use Case

Remote File plug-in can be configured to use CSV as an output format, but the CSV Header (`csv_header`) option only prints the header in the first file.

### Expected behavior

Each file written will have the CSV header row

### Actual behavior

Only the first file written has the CSV header row

**Comment by srebhan** [comment]
@caallinson please test the binary in PR #15968, available as soon as CI finished the tests, and let me know if it fixes the issue!
