### ISSUE TITLE
DBus envvar message

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#15934]
### Relevant telegraf.conf

```
None. The message appears directly **before**

telegraf[1564]: 2024-09-15T23:07:55Z I! Loading config: /etc/telegraf/telegraf.conf
```

### Logs from Telegraf

```text
telegraf[1564]: time="2024-09-16T01:07:55+02:00" level=warning msg="DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null." func="gosnowflake.(*defaultLogger).Warn" file="log.go:244"
```

### System info

telegraf 1.31.3 + telegraf 1.32.0, RHEL8

### Steps to reproduce

1. Install telegraf 1.31.3 or telegraf 1.32.0 on RHEL8
2. look at the journal (journalctl -u telegraf)

### Expected behavior

We'd either expect no message, if it works without this envvar or we'd expect documentation, that we should set this variable and what to.

### Actual behavior

This warning message, worrying us.

**Comment by 1tft** [comment]
We also get this warning when we execute (under root or telegraf user) `telegraf --version`:

```
telegraf --version
WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
Telegraf 1.31.3 (git: HEAD@ecf94b12)
```

with Telegraf 1.30.3 we dont get this warning:

```
telegraf --version
Telegraf 1.30.3 (git: HEAD@fd4af886)
```

So it seems not directly related to https://github.com/influxdata/telegraf/pull/14539


Currently for telegraf user this dbus variable is not set. `printenv DBUS_SESSION_BUS_ADDRESS` result is empty.
So maybe this variable should be set during telegraf installation?

**Comment by 1tft** [comment]
### Update
Today I noticed, that _DBus envvar warning message_ disappeared between v1.32.0 and v1.32.1 release.

```
root@mypc:/# telegraf --version
WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null. 
Telegraf 1.32.0 (git: HEAD@dcfadf8b)

# ... installting latest Telegraf version

root@mypc:/# telegraf --version
Telegraf 1.32.1 (git: HEAD@946e4d7d)

```

**Comment by srebhan** [comment]
@knollet and @1tft the issue is in the go-snowflake driver and there is _nothing_ Telegraf can do about it. Between v1.32.0 and v1.32.1 we updated the driver and thus pulled in a fix in go-snowflake to no longer produce the issue. @knollet can you confirm the issue disappears in latest Telegraf?

**Comment by 1tft** [comment]
@srebhan Yes, DBus envvar warning message disappeared with latest telegraf version. Have been tested it on Ubuntu 22.04 and RHEL8 two weeks ago.
