### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by AlvinChiou** [influxdata/telegraf#1594]
Source: https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md

Hi! 
Original
```
nssm install Telegraf c:\telegraf\telegraf.exe -config c:\telegraf\telegraf.config
```
may cause this error:
``` 
Telegraph: Unexpected status SERVICE_PAUSED in response to START control
```
Please modify that:
```
nssm install Telegraf c:\telegraf\telegraf.exe -config c:\telegraf\telegraf.conf
```
thanks!

**Comment by sparrc** [comment]
as of 1.0, windows users will no longer need to use nssm, see the latest readme for instructions installing telegraf as a real windows service. There will be a release candidate build available in the coming weeks.
