### ISSUE TITLE
[[inputs.systemd_units]] scope="user" should support explicitly setting users other than telegraf

### ISSUE THREAD

**Issue by daniel-trnk** [influxdata/telegraf#16047]
### Use Case

Collect systemd unit metrics for systemd units run with a user scope by users other than the telegraf user.

Since https://github.com/influxdata/telegraf/pull/15458, [[inputs.systemd_units]] allows gathering metrics on systemd units run with a user scope in addition to the default system scope. However,  it does not allow explicitly setting a user and instead takes the telegraf user.

In most cases, however, relevant services that need to me observed are not run as the telegraf user, but as other users on the system.

### Expected behavior

Allow a config like
```
 scope = "user"
 user = "prod"
 ```
Set the user for the systemd user scope unit metrics collection to that user instead of the telegraf user.

### Actual behavior

User is set to the current telegraf user.

**Comment by srebhan** [comment]
@daniel-trnk this is not possible I think even with the `systemctl` command as root as you are connecting to the user service manager and this is per logged in user... So the only possibility to do this with `systemctl` is to execute the command as the user you want to query and therefore the same applies to Telegraf.

**Comment by yfyf** [comment]
> @daniel-trnk this is not possible I think even with the systemctl command as root as you are connecting to the user service manager and this is per logged in user... So the only possibility to do this with systemctl is to execute the command as the user you want to query and therefore the same applies to Telegraf.

That's not true, it is possible. You can list / show units for other users using [systemctl --user --machine=someuser@.host](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#-M). It would be great to see this feature, as now there's no way to get unit statistics for user services.
