### ISSUE TITLE
[Feature Request] Possibility for logparser to substitution timestamp from log file string

### ISSUE THREAD

**Issue by dmitrysdm** [influxdata/telegraf#1604]
The ability for logparser to substitution Timestamp from log file, instead that generated by telegraf:
For example, if there is a kind of log, that alrady contain timestamp field:

`8/08/2016 00:10:22 info get filelist from ftpdirectory: /GuestDir/Folders/Taiz
`

Better solution - to get Logstamp from log file.
Now telegraf generate own logstamp, at same time,exist as different field Timestamp after log string was parsed. 
As result, after logparser exist two logstamp filds, that is not well useful with Grafana, because by default Grafana used field from telegraf\influxdb. 
In other case better solution is left only one logstash field ( on user choise ) - from logfile, or from telegraf.

In Logstash exist follow configuration for getting this:
```
  date {
    type => "Logs"
    match => [ "Time", "MM/dd/YYYY HH:mm:ss" ]
    target => "Logtimestamp"
  }
```

**Comment by sparrc** [comment]
@dmitrysdm timestamp parsing is already available in the logparser plugin. Please refer to the influx grok patterns: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/logparser/grok/patterns/influx-patterns

as well as the logparser doc: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser
