### ISSUE TITLE
how to use nvidia-smi in kubernetes damonset?

### ISSUE THREAD

**Issue by rockburning** [influxdata/telegraf#16051]
### Use Case

Is there any suggestion on how to use nvidia-smi input plugin in damonset to get the node GPU metric

### Expected behavior

to get gpu metric in k8s damonset

### Actual behavior

cannot get the nvidia-smi in k8s damonset

**Comment by srebhan** [comment]
Well you run Telegraf on the nodes with the plugin enabled? I don't get the question here, sorry.
