### ISSUE TITLE
JSON object values are not added as tags

### ISSUE THREAD

**Issue by ptoews** [influxdata/telegraf#16115]
### Relevant telegraf.conf

```toml
data_format = "json_v2"
  [[inputs.amqp_consumer.json_v2]]
    measurement_name_path = "measurement_name"
    timestamp_path = "timestamp"
    timestamp_format = "2006-01-02T15:04:05.999999Z"
    [[inputs.amqp_consumer.json_v2.object]]
      path = "@this"
      excluded_keys = ["timestamp", "measurement_name", "data"]
      tags = ["config_ids"]
```

### Logs from Telegraf

```text
2024-10-31T10:53:15Z I! Loading config: /etc/telegraf/telegraf.conf
2024-10-31T10:53:15Z I! Starting Telegraf 1.31.1 brought to you by InfluxData the makers of InfluxDB
2024-10-31T10:53:15Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
2024-10-31T10:53:15Z I! Loaded inputs: amqp_consumer                                                                                                                               2024-10-31T10:53:15Z I! Loaded aggregators:
2024-10-31T10:53:15Z I! Loaded processors:
2024-10-31T10:53:15Z I! Loaded secretstores:
2024-10-31T10:53:15Z I! Loaded outputs: file influxdb
2024-10-31T10:53:15Z I! Tags enabled: host=e74844de41df
2024-10-31T10:53:15Z I! [agent] Config: Interval:1s, Quiet:false, Hostname:"e74844de41df", Flush Interval:1s
```

### System info

Telegraf 1.31.1

### Steps to reproduce

1. Send this message: 
```
{
  "timestamp": "2024-10-31T10:53:21.075078Z",
  "measurement_name": "test",
  "config_ids": {
    "A": "abc1",
    "B": "abc2",
    "C": "abc3"
  },
  "dummy": 1
}
```

### Expected behavior

The config ids are stored as tags, e.g.
`test,host=e74844de41df,config_ids_A="abc1",config_ids_B="abc2",config_ids_C="abc3" dummy=1 1730372001075078000`

### Actual behavior

The config ids are stored as fields: `test,host=e74844de41df config_ids_A="abc1",config_ids_B="abc2",config_ids_C="abc3",dummy=1 1730371605580839000`

### Additional info

[The docs](https://github.com/influxdata/telegraf/blob/bb811daef4292be26a3e9ed4d7f6b6fedb6333fd/plugins/parsers/json_v2/README.md?plain=1#L176) mention that tags can be set to the key of a JSON object, so that each value will become a tag; however this does not seem to work in my case.

**Comment by srebhan** [comment]
Please use the [XPath parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath) for this! Using
```toml
[[inputs.file]]
  files = ["test_configs/jsontest_issue_16115.json"]

  data_format = "xpath_json"
  xpath_native_types = true

  [[inputs.file.xpath]]
    metric_name = "/measurement_name"
    tag_selection = "/config_ids/*"
    tag_name_expansion = true
    timestamp = "/timestamp"
    timestamp_format = "rfc3339nano"

    [inputs.file.xpath.fields]
      dummy = "/dummy"
```

with your example above I get

```
> test,config_ids_A=abc1,config_ids_B=abc2,config_ids_C=abc3,host=Hugin dummy=1 1730372001000000000
```

**Comment by ptoews** [comment]
Thanks, it works! Is there anything going to be done to the json_v2 parser though? Maybe update the docs?

**Comment by srebhan** [comment]
I would accept a PR stating the fact that the json_v2 parser should be avoided in favor of xpath especially with arrays. Would you be willing to put up that PR? :-)
