### ISSUE TITLE
feat(inputs.modbus) See Hosts on Errormessages

### ISSUE THREAD

**Issue by SoeNorKle** [influxdata/telegraf#16112]
### Use Case

To get a meaningful errormessage I have to see which host generated an error on a modbus request.

### Expected behavior

Print the hostname if a request fails 

### Actual behavior

Only print the slaveID in the error message

**Comment by srebhan** [comment]
@SoeNorKle please test the binary in PR #16114, available once CI finished the tests, and let me know if that's what you had in mind. I've added either the configured `device` setting or the `controller` setting (for connection related issues) to the error messages...

**Comment by SoeNorKle** [comment]
@srebhan Thanks for your effort. The code looks good and you changed more than I needed but thats great. I'll test the binary but I've no test environment atm. I'll let you know if I could test it and could generate some Errors to validate your adaptions.
