### ISSUE TITLE
Processors are initialised twice

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#16143]
### Relevant telegraf.conf

```toml
[[processors.regex]]
  alias = "foo"
  namepass = ["metric1"]

  [[processors.regex.tags]]
    key = "index"
    pattern = "^(\\d+)\\.\\d+$"
    replacement = "${1}"
    result_key = "FooBar"


[[processors.regex]]
  alias = "bar"
  namepass = ["metric2"]

  [[processors.regex.tags]]
    key = "index"
    pattern = "^(\\d+)\\.\\d+$"
    replacement = "${1}"
    result_key = "FooBar"
```

### Logs from Telegraf

```text
2024-11-05T13:23:12Z I! [processors.regex::foo] tags: Using explicit mode...
2024-11-05T13:23:13Z I! [processors.regex::bar] tags: Using explicit mode...
2024-11-05T13:23:13Z I! [processors.regex::foo] tags: Using explicit mode...
2024-11-05T13:23:13Z I! [processors.regex::bar] tags: Using explicit mode...
```

### System info

Telegraf 1.32.2 (git: HEAD@160548d7)

### Steps to reproduce

Run telegraf, observe logs.

### Expected behavior

Only single initialisation of processors.

### Actual behavior

Processors executing initialisation twice.

### Additional info

Might be related to `skip_processors_after_aggregators`, but enabling that didn't have any effect.

**Comment by srebhan** [comment]
@Hipska please test the binary in PR #16290, available after CI finished the tests, and let me know if that fixes the issue!

**Comment by Hipska** [comment]
As far as I can see, that PR only stops second initialisation when `skip_processors_after_aggregators` is set to true. In normal scenarios, they are still initialised twice.

**Comment by srebhan** [comment]
Which is correct as there are two instances created, one before the aggregators and one after. This is necessary to avoid side effects between the two stages.

**Comment by Hipska** [comment]
I think it is exactly the creation of 2 instances is what I reported. Why can't they be initialised once and executed twice?

**Comment by srebhan** [comment]
Because then any internal state of the processor is modified! You will get all sorts of side effects.

**Comment by Hipska** [comment]
The side effects are already there. Now only in a weird and confusing way: not sharing global state for example.

**Comment by Hipska** [comment]
@srebhan ?

**Comment by srebhan** [comment]
Back from holiday. The behavior was like this for ages and we cannot change this! As pushed out in the release on Friday, we will change the default to _not_ execute processors twice except for explicitly setting it. Other than this I will not introduce "execute one thing twice" behavior as nobody will be able to handle this.
