### ISSUE TITLE
amqp_consumer input : allow queue arguments from config

### ISSUE THREAD

**Issue by n1b0r** [influxdata/telegraf#16140]
### Use Case

I need to be able to set a `max-length` attribute for the queue declared by telegraf on rabbitmq

### Expected behavior

I expect to be able to configure queue arguments.
```
queue_arguments = {"x-max-length": 100}
```

### Actual behavior

I cannot set queue arguments

**Comment by n1b0r** [comment]
Hello @srebhan could you tell me when this feature will be included in a release ?

**Comment by n1b0r** [comment]
any news @srebhan ?

**Comment by srebhan** [comment]
@n1b0r if you click on the PR you can see the milestone on the right-hand side. For this PR it says v1.33.0. Clicking on the milestone you will see the planned release date which is December 9th for v1.33.0...
