### ISSUE TITLE
(inputs.mysql) MariaDB example in dev/docker-compose.yml not fully functional

### ISSUE THREAD

**Issue by grooverdan** [influxdata/telegraf#16159]
### Use Case

docker-compose up

### Expected behavior

All inputs tested.

### Actual behavior

Missing mariadb_dialect setting causes the non-MariaDB dialect to be used.

**Comment by srebhan** [comment]
@grooverdan the files in `dev` were meant for doing (manual) integration tests. As we now do have _real_ integration tests I would rather love to remove the `dev` directory altogether. What do you think?

Does this also affect the _actual_ integration tests in `mysql_test.go`?
