### ISSUE TITLE
prometheus: 1.30.0+ parsing error in logs

### ISSUE THREAD

**Issue by aerickson** [influxdata/telegraf#16157]
### Relevant telegraf.conf

```toml
# Global Agent Configuration
[agent]
  interval = "10s"             # Collection interval for all metrics
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  logfile = "/etc/telegraf/run.log"
  debug = true
  quiet = false
  hostname = ""
  omit_hostname = false

# OUTPUT PLUGINS
# Expose metrics in Prometheus format via Prometheus client
[[outputs.prometheus_client]]
  listen = ":9273"           # Port where metrics are exposed
  path = "/metrics"          # Path where metrics are exposed
  metric_version = 2         # Use OpenMetrics format (recommended)
  expiration_interval = "0"  # Never expire metrics

[[inputs.exec]]
  commands = ["/usr/bin/echo fc_ceph_df_usage_percent{crush_type=\\\"osd\\\"} 35.85032"]
  data_format = "prometheus"
```

### Logs from Telegraf

```text
2024-11-06T20:37:12Z I! Loaded secretstores: 
2024-11-06T20:37:12Z I! Loaded outputs: prometheus_client
2024-11-06T20:37:12Z I! Tags enabled: host=7045c59748de
2024-11-06T20:37:12Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"7045c59748de", Flush Interval:10s
2024-11-06T20:37:12Z D! [agent] Initializing plugins
2024-11-06T20:37:12Z D! [agent] Connecting outputs
2024-11-06T20:37:12Z D! [agent] Attempting connection to [outputs.prometheus_client]
2024-11-06T20:37:12Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
2024-11-06T20:37:12Z D! [agent] Successfully connected to outputs.prometheus_client
2024-11-06T20:37:12Z D! [agent] Starting service inputs
2024-11-06T20:37:20Z W! [parsers.prometheus::exec] Unknown format ""... Trying to continue...
2024-11-06T20:37:22Z D! [outputs.prometheus_client] Wrote batch of 2 metrics in 164.375µs
2024-11-06T20:37:22Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
```

### System info

versions mentioned below in additional info

### Docker

using the official telegraf docker images

### Steps to reproduce

1. use telegraf.conf above
2. start telegraf on version 1.30.0 or later
3. `Unknown format ""... Trying to continue...` error will be seen, data is present at /metrics.

### Expected behavior

No complaint about the input (`Unknown format ""... Trying to continue...`) in the logs, as it's valid. 

Reliable input.exec behavior (see actual for bugged behavior).

### Actual behavior

* Error is given in log file
  * Error message seems benign, but it does seem to make longer-running input.exec inputs behave erratically (metrics disappears from /metrics intermittently). 

### Additional info

```
# bug not present / working:
#   1.18.3, 1.20.2, 1.26.3, 1.29.5
#
# bug present: 
#   1.32.2, 1.31.3, 1.30.3, 1.30.0
```

**Comment by srebhan** [comment]
@aerickson ignore the warning for now as this is due to the fact that there is no `Content-Type` header. I'll put up a fix removing it in a minute. However, I'm running your configuration locally and I **cannot** see the metric to disappear when running `watch -n1 'wget -O - 127.0.0.1:9273/metrics | grep fc_ceph_df_usage_percent'`...

So why do you think it is gone with the config above?

**Comment by srebhan** [comment]
@aerickson please test the binary in PR #16166, available as soon as CI finished the tests (~30min), and let me know if that silences the warning...

**Comment by aerickson** [comment]
Confirmed that the message about the `Unknown format` is gone.

I noticed a message `2024-11-08T00:00:05Z D! [inputs.exec] No metrics were created from a message. Verify your parser settings. This message is only printed once.` that I hadn't seen before, but everything seems to work. Is there any way to get more insight into the particular exec that had that error?

Thank you! :)

**Comment by aerickson** [comment]
re: unrelated issue, I added an additional debug to reveal the command that failed to yield a metric. 

```
diff --git a/plugins/inputs/exec/exec.go b/plugins/inputs/exec/exec.go
index efe8c2968..c1ad5c9fe 100644
--- a/plugins/inputs/exec/exec.go
+++ b/plugins/inputs/exec/exec.go
@@ -179,6 +179,7 @@ func (e *Exec) processCommand(command string, acc telegraf.Accumulator, wg *sync
        if len(metrics) == 0 {
                once.Do(func() {
                        e.Log.Debug(internal.NoMetricsCreatedMsg)
+                       e.Log.Debugf("Command without metrics: %q", command)
                })
        }
 
```

Let me know if that would be useful and I can make a PR. Thanks.

**Comment by srebhan** [comment]
Please commit your change as a PR!  I would also print the returned "buffer" that did not yield a metric.
