### ISSUE TITLE
built old version of godep

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/telegraf#1616]
not sure what version of godep is being used to build telegraf, documentation doesn't say and latest version has issues adding new packages. making it hard test fixes to generate pull requests.

```
GOPATH=$PWD
go get github.com/influxdata/telegraf
cd $GOPATH/src/github.com/influxdata/telegraf
make
godep get github.com/jackc/pgx
godep save
# godep: open Godeps/Godeps.json: not a directory
```

**Comment by sparrc** [comment]
we're not using godep: https://github.com/influxdata/telegraf#from-source

**Comment by james-lawrence** [comment]
ah the filename lead me down the wrong path, sorry.
