### ISSUE TITLE
testifylint->encoded-compare - Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#16184]
### Description

This issue starts a discussion about enabling:
- linter: [testifylint](https://github.com/Antonboom/testifylint) - Checks usage of github.com/stretchr/testify.
- checker: [encoded-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#encoded-compare) - Protection from bugs and more appropriate `testify` API with clearer failure message.

`encoded-compare` detects JSON-style string constants (usable in `fmt.Sprintf` also) and JSON-style/YAML-style named
variables. If variable is converted to `json.RawMessage`, then it is considered JSON unconditionally.

When fixing, `encoded-compare` removes unnecessary conversions to `[]byte`, `string`, `json.RawMessage` and calls of
`strings.Replace`, `strings.ReplaceAll`, `strings.Trim`, `strings.TrimSpace`, and adds a conversion to `string` when
needed.

### Example

**Before:**
```
assert.Equal(t, `{"foo": "bar"}`, body)
assert.EqualValues(t, `{"foo": "bar"}`, body)
assert.Exactly(t, `{"foo": "bar"}`, body)
assert.Equal(t, expectedJSON, resultJSON)
assert.Equal(t, expBodyConst, w.Body.String())
assert.Equal(t, fmt.Sprintf(`{"value":"%s"}`, hexString), result)
assert.Equal(t, "{}", json.RawMessage(resp))
assert.Equal(t, expJSON, strings.Trim(string(resultJSONBytes), "\n")) // + Replace, ReplaceAll, TrimSpace

assert.Equal(t, expectedYML, conf)
```

**After:**
```
assert.JSONEq(t, `{"foo": "bar"}`, body)
assert.YAMLEq(t, expectedYML, conf)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, the following findings were found in the current codebase:
```
plugins/serializers/json/json_test.go:199:2            testifylint  encoded-compare: use require.JSONEq
plugins/serializers/json/json_test.go:223:2            testifylint  encoded-compare: use require.JSONEq
plugins/serializers/json/json_test.go:242:2            testifylint  encoded-compare: use require.JSONEq
plugins/serializers/nowmetric/nowmetric_test.go:194:2  testifylint  encoded-compare: use require.JSONEq
plugins/serializers/nowmetric/nowmetric_test.go:216:2  testifylint  encoded-compare: use require.JSONEq
plugins/serializers/nowmetric/nowmetric_test.go:236:2  testifylint  encoded-compare: use require.JSONEq
```

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by srebhan** [comment]
Yes, please go ahead @zak-pawel!
