### ISSUE TITLE
testifylint->contains - Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#16183]
### Description

This issue starts a discussion about enabling:
- linter: [testifylint](https://github.com/Antonboom/testifylint) - Checks usage of github.com/stretchr/testify.
- checker: [contains](https://github.com/Antonboom/testifylint?tab=readme-ov-file#contains) - Code simplification and more appropriate `testify` API with clearer failure message.

### Example

**Before:**
```
assert.True(t, strings.Contains(a, "abc123"))
assert.False(t, !strings.Contains(a, "abc123"))

assert.False(t, strings.Contains(a, "abc123"))
assert.True(t, !strings.Contains(a, "abc123"))
```

**After:**
```
assert.Contains(t, a, "abc123")
assert.NotContains(t, a, "abc123")
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by srebhan** [comment]
Yes, please go ahead @zak-pawel!
