### ISSUE TITLE
testifylint->regexp - Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#16185]
### Description

This issue starts a discussion about enabling:
- linter: [testifylint](https://github.com/Antonboom/testifylint) - Checks usage of github.com/stretchr/testify.
- checker: [regexp ](https://github.com/Antonboom/testifylint?tab=readme-ov-file#regexp ) - Code simplification.

### Example

**Before:**
```
assert.Regexp(t, regexp.MustCompile(`\[.*\] DEBUG \(.*TestNew.*\): message`), out)
assert.NotRegexp(t, regexp.MustCompile(`\[.*\] TRACE message`), out)
```

**After:**
```
assert.Regexp(t, `\[.*\] DEBUG \(.*TestNew.*\): message`, out)
assert.NotRegexp(t, `\[.*\] TRACE message`, out)
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, no additional configuration can be provided.

**Comment by srebhan** [comment]
Yes, please go ahead @zak-pawel!
