### ISSUE TITLE
 No metrics were created from a message

### ISSUE THREAD

**Issue by rwb196884** [influxdata/telegraf#16187]
### Please direct all support questsions to slack or the forums. Thank you.

```
W! [inputs.mqtt_consumer] No metrics were created from a message. Verify your parser settings. This message is only printed once.
```

What message? What metrics?
What a useless message.
Can anything be done about it?

**Comment by rwb196884** [comment]
It's impossible to get in to Slack because when I enter my email address it sends me a code and then complains that I'm already registered.

**Comment by rwb196884** [comment]
Seems to be broken anyway. 
![image](https://github.com/user-attachments/assets/ae8489c4-810b-4384-b7b5-c6a338598365)

**Comment by srebhan** [comment]
You do have a typo in the url! Use https://www.influxdata.com/slack...
