### ISSUE TITLE
Broken Installation Page [Telegraf]

### ISSUE THREAD

**Issue by ankurparihar** [influxdata/telegraf#16196]
### Please direct all support questsions to slack or the forums. Thank you.

Hi team,

I need the .deb binary for installing and trying out telegraf locally, however on the downloads page there's no binary provided in Linux-options, I've checked linux-amd64

[Telegraf downloads page](https://www.influxdata.com/downloads/#telegraf)

It shows download link for .tar.gz file, along with `tar xf` command, which only extracts it, but doesn't install telegraf in PATH.

How can I install telegraf command in path, or is there any link to download .deb file that I can use with dpkg to install telegraf locally?

Thanks

**Comment by ankurparihar** [comment]
Yes, I was later able to download from GitHub, however expectation was that I'll get download link in the page itself since that's what installation page says - 
![Screenshot 2024-11-19 at 1 23 38 PM](https://github.com/user-attachments/assets/7ff83b1c-43d9-41c8-bcd0-ff6e7ece494a)

Can you please also check the installation instructions - 
![Screenshot 2024-11-19 at 1 25 10 PM](https://github.com/user-attachments/assets/c9165586-3413-4a9d-946f-eb66eb518183)

It doesn't install anything after running tar, tar only unzips, after that in that there are `var`, `etc`, `usr` folders, users won't know what to do with them and where is the correct binary

**Comment by srebhan** [comment]
@ankurparihar well in your example you have chosen the generic "Linux Binary (64-bit)" platform and **not** the debian one. You can extract to `/` as root and stuff is installed... I'm not sure what your request is?!?

**Comment by ankurparihar** [comment]
I don't see and .deb files when selecting debian,

![Image](https://github.com/user-attachments/assets/f15e0522-5735-4182-bcf2-d6e1c3f0591c)

I'll rephrase it - 

Please provide a .deb file to download from the installation page itself, so that a normal user can just do `sudo dpkg -i telegraf.deb`

**Comment by srebhan** [comment]
@ankurparihar you can download the deb file from the [github release page](https://github.com/influxdata/telegraf/releases). The download page is for an easy way of installing the package. We won't change the download page and what you request is already possible.
