### ISSUE TITLE
[DOUBT] Can we send push notification for logs using ntfy push notification server which we can selfhost ?

### ISSUE THREAD

**Issue by Greatz08** [influxdata/telegraf#16217]
It would be great if we can set it to send push notification server regarding any specific logs or issues which this program captures to my other devices like my android phone ?

**Comment by srebhan** [comment]
@Greatz08 you could use the [exec output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/exec) to call a nfty client with the corresponding message... Did you try this?
