### ISSUE TITLE
Allow configuration of the message key in structured logs

### ISSUE THREAD

**Issue by alexgokhale** [influxdata/telegraf#16241]
### Use Case

This feature would enable configuration of the message key used for structured logging, which currently defaults to `slog.MessageKey` (which is `"msg"`.

A number of log ingestion pipelines rely on the key being `"message"`.
It would be very helpful to be able to configure this value without having to rely on another tool, such as fluentbit, to transform the logs.

My current use case would benefit from not having to add this additional overhead, when it's arguably not necessary.

### Expected behavior

This will allow a config option, `structured_log_message_key`, or similar, which when set to a different value, such as `message` (instead of the default `msg`), would produce structured logs in the following format:

```
{"time":"2024-11-27T22:31:08.995949Z","level":"INFO","message":"Loading config: telegraf.conf"}
```

### Actual behavior

This functionality is currently not yet available, so the logs would continue to be produced as follows:

```
{"time":"2024-11-27T22:31:08.995949Z","level":"INFO","msg":"Loading config: telegraf.conf"}
```

**Comment by srebhan** [comment]
Hmmm wouldn't it be better then to simply change the key to `message` instead of adding a new option?

**Comment by alexgokhale** [comment]
> Hmmm wouldn't it be better then to simply change the key to `message` instead of adding a new option?

@srebhan I'd be very happy for that to occur, I was just conscious of making what would be a breaking change for anyone who now relies on the key being `msg`. If you think that isn't much of a risk I'll update the PR to just make that change instead.

**Comment by srebhan** [comment]
Let me discuss this in the team...

**Comment by srebhan** [comment]
Ok decided to keep the option to not break people. Thanks for your contribution and patience!
