### ISSUE TITLE
Support Avro format for kafka producer and consumer?

### ISSUE THREAD

**Issue by Madhu1512** [influxdata/telegraf#1630]
is there any plan to support Avro format for Kafka producer and consumer and also other queues?

Avro Schema for Influxdb format:

```
{
          "namespace": "telegraf.avro",
          "type": "record",
          "name": "telegraf",
          "fields": [
            {
            "name": "timestamp",
            "type": {"type":"long", "logicalType":"timestamp-millis"}
            },
            {
            "name": "name",
            "type": "string"
            },
            {
            "name": "tags",
            "type": {"type" : "map", "values" : "string"}
            },
            {
            "name": "fields",
            "type": {"type" : "map", "values" : "double"},
            "type": {"type" : "map", "values" : "float"},
            "type": {"type" : "map", "values" : "boolean"},
            "type": {"type" : "map", "values" : "int"},
            "type": {"type" : "map", "values" : "long"},
            "type": {"type" : "map", "values" : "bytes"},
            "type": {"type" : "map", "values" : "string"},
            "type": {"type" : "map", "values" : "null"}
            }
          ]
        }
}
```

**Comment by sparrc** [comment]
There are no plans for this, can you explain the use-case? tbh the fact that it's very specific _and_ doesn't natively support timestamps doesn't make it a very attractive format from a telegraf perspective.

**Comment by sparrc** [comment]
closing for lack of updates

**Comment by ermik** [comment]
If influx is used as a warehousing solution for time-series format third-party data it would originate at an ingest point somewhere at the edge of the system (API consumer). That data may flow in a number of different ways to different consumers and kafka messages are a possible way to do it with avro and schema registry being an additional layer of scaffolding.

**Comment by johntdyer** [comment]
+1

**Comment by dmiddelhede** [comment]
+1

**Comment by cobolbaby** [comment]
+1

**Comment by timhallinflux** [comment]
Has anyone considered using Apache NiFi for the creation of this?  Telegraf can write to NiFi and I believe NiFi has an Avro output processor.  There are a number of other benefits to Nifi as well...

**Comment by samhld** [comment]
@timhallinflux would a request for NiFi input/output plugins be worthwhile?
