### ISSUE TITLE
Error thrown by mysql input plugin when gather_perf_events_statements enabled

### ISSUE THREAD

**Issue by xert** [influxdata/telegraf#1646]
### Relevant telegraf.conf:

```
[[inputs.mysql]]
# ...
## gather metrics from PERFORMANCE_SCHEMA.EVENTS_STATEMENTS_SUMMARY_BY_DIGEST
gather_perf_events_statements             = true
```

### System info:

Telegraf compiled from master branch

### Steps to reproduce:

1. Configure at least one mysql server in inputs.mysql
2. Enable gather_perf_events_statements
3. Run telegraf -test

### Expected behavior:

No errors

### Actual behavior:

`2016/08/18 09:10:55 Errors encountered: [sql: expected 15 destination arguments in Scan, not 14], [sql: expected 15 destination arguments in Scan, not 14]`

**Comment by sparrc** [comment]
@Maksadbek any ideas?

**Comment by sparrc** [comment]
@xert please provide your mysql version and full config file
