### ISSUE TITLE
Some disks not found

### ISSUE THREAD

**Issue by socol1** [influxdata/telegraf#1648]
df -h
![image](https://cloud.githubusercontent.com/assets/18021407/17768630/66ece170-6567-11e6-8df7-fa1aec8e7b60.png)
select * from disk  where host ='digit-fdfs01' order by time desc limit 30

![image](https://cloud.githubusercontent.com/assets/18021407/17768655/8ea94b86-6567-11e6-871c-5e0a02745d3d.png)

kapacitor-0.13.1.x86_64
influxdb-0.13.0.x86_64

uname -a
Linux digit-fdfs01 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phemmer** [comment]
Can you provide the output of:
* `cat /proc/filesystems`
* `grep /dev/sdb1 /etc/mtab`
* `grep /dev/sdb1 /proc/mounts`

**Comment by socol1** [comment]
![image](https://cloud.githubusercontent.com/assets/18021407/17786752/d6422dfe-65b8-11e6-98fa-af8777521280.png)

**Comment by phemmer** [comment]
Hrm, that all looks fine at first glance. Was thinking maybe there was something in those files that the library telegraf uses didn't handle.

I'm assuming there's nothing special in your telegraf config? No `ignore_fs` `tagdrop` etc?

**Comment by socol1** [comment]
![image](https://cloud.githubusercontent.com/assets/18021407/17795232/471656d8-65e9-11e6-9c7d-31b9ea3ff2f9.png)
The config is default, I think the problem is partitioning tool, I use the partition tool is parted ,not fdisk

**Comment by phemmer** [comment]
Went through the code again, and I think I see something that might cause this to happen. Is telegraf running as an unprivileged user, or is it running as root? If it's running as an unprivileged user, does this user have access to the mount points?

**Comment by socol1** [comment]
Good job, you are right, thanks phemmer
