### ISSUE TITLE
httpjson: support configurable response_timeout

### ISSUE THREAD

**Issue by gam-phon** [influxdata/telegraf#1650]
There is no configurable response_timeout in httpjson input.  I have an endpoint that takes more than the default timeout to response.

Here is the default response_timeout, which is hard coded, for httpjson:
```
		tr := &http.Transport{
			ResponseHeaderTimeout: time.Duration(3 * time.Second),
			TLSClientConfig:       tlsCfg,
		}
		client := &http.Client{
			Transport: tr,
			Timeout:   time.Duration(4 * time.Second),
		}
```

**Comment by gam-phon** [comment]
I have opened a pull request to add this. Could you please check it out and tell me if there is something missing?

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1651
