### ISSUE TITLE
[[inputs.http_response]] insecure_skip_verify not working

### ISSUE THREAD

**Issue by skares** [influxdata/telegraf#1653]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]
telegraf 0.13.2, Centos 7

### Steps to reproduce:

1. insecure_skip_verify = true in http_response config
2. # telegraf -config /etc/telegraf/telegraf.conf -input-filter http_response -test -debug
Error parsing /etc/telegraf/telegraf.conf, line 689: field corresponding to `insecure_skip_verify' is not defined in `*http_response.HTTPResponse' 

### Expected behavior:

Skip SSL Host and Certificate warnings

### Actual behavior:

Error parsing telegraf.conf, Field not defined.

### Additional info:

[Include gist of relevant config, logs, etc.]

Config section:
# # HTTP/HTTPS request given an address a method and a timeout
[[inputs.http_response]]
#   ## Server address (default http://localhost)
address = "https://cloud9.coremedia.com/status.php"
#   ## Set response_timeout (default 5 seconds)
   response_timeout = "15s"
#   ## HTTP Request Method
  method = "GET"
 insecure_skip_verify = true

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
that feature is not available is 0.13.2, see `telegraf -usage http_response`

you'll need to use a beta version
