### ISSUE TITLE
Ping logs a parse error on timeout

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1654]
### Relevant telegraf.conf:

```
[[inputs.ping]]
  urls = ["1.2.3.4"]
  count = 1
```
### System info:

Telegraf 1.0b3
FreeBSD 10.1
### Steps to reproduce:
1. `telegraf -config telegraf.conf -test`
### Expected behavior:

```
* Plugin: ping, Collection 1
> ping,url=1.2.3.4 packets_received=0i,packets_transmitted=1i,percent_packet_loss=100 1471624766000000000
```
### Actual behavior:

```
* Plugin: ping, Collection 1
2016/08/19 12:39:56 , Command timed out.
Fatal error processing ping output
```

---

I think it would be beneficial here to use the setcap perm CAP_NET_RAW on linux when available, and not shell out to the `ping` utility.

**Comment by ondrejmo** [comment]
I have the same problem, but in version 0.13.1 in docker.

**Comment by rvrignaud** [comment]
Same problem here with ubuntu 16.04 with both iputils-ping and inetutils-ping.

**Comment by sparrc** [comment]
To be clear, the issue is that it's not logging any metrics, not that it's timing out in the first place?

I guess this was intentional, the idea was that metrics will only get collected if the `ping` command tells us that packets were or weren't transmitted. In this case `ping` isn't telling us anything, just timing out.

**Comment by ianwalter** [comment]
I think I might have the same issue, although my config looks like: 
```
[[inputs.ping]]
  urls = ["iankwalter.com", "optick.io"] # required 
  count = 4 # required
  timeout = 0.0
```
And log looks like:
```
PING optick.io (208.77.22.107): 16 data bytes
24 bytes from 208.77.22.107: icmp_seq=0 ttl=55 time=37.153 ms
24 bytes from 208.77.22.107: icmp_seq=1 ttl=55 time=34.952 ms, Command timed out.
Fatal error processing ping output
```
Executing ping from the command line doesn't result in a timeout.

Also, the README should be updated because it has a capital `Timeout` instead of `timeout` and I had to set it to `0.0` and not `0` otherwise I get this error:
```
Error parsing /usr/local/etc/telegraf.conf, line 125: ping.Ping.Timeout: `float64' is not any types of int
```

**Comment by ianwalter** [comment]
Also, if it does legitimately timeout, shouldn't this be logged somehow? Wouldn't it be desirable to be able to track timeouts and maybe even hook it up to Kapacitor for alerting?

**Comment by lokenx** [comment]
Having similar issues it seems with the below config but running on a Raspberry Pi 3. I can ping Google fine (with the same time as is being reported) manually.

```
[[inputs.ping]]
  urls = ["www.google.com"]
  count = 3
  ping_interval = 20.0
  Timeout = 3.0


2016/09/07 22:28:54 ERROR in input [ping]: PING www.google.com (172.217.2.132) 16(44) bytes of data.
24 bytes from 172.217.2.132: icmp_seq=1 ttl=55 time=5.49 ms, Command timed out.
Fatal error processing ping output
```

**Comment by sparrc** [comment]
@lokenx you're configuration doesn't make sense, with count=3 and interval=20 your pings would take 60s, but then your timeout is only 3s..?

**Comment by lokenx** [comment]
@sparrc I  assumed the Timeout was for an individual ping to timeout if there's no response within that time? Or did I miss read the docs?

**Comment by sparrc** [comment]
yes, ping's -w timeout is a _total_ timeout over the entire request:

```
-w deadline
  Specify a timeout, in seconds, before ping exits regardless of how many packets have been sent or received. In this case ping does not stop after count packet are sent, it waits either for deadline expire or until count probes are answered or for some error notification from network.
```

if you want to submit a PR to make that more clear in the doc I'd appreciate it a lot :)

**Comment by lokenx** [comment]
@sparrc ah I wasn't sure if it was some a custom timeout variable or something, can definitely look at that once I get it working!

I removed the timeout and left count at 3:

```
2016/09/08 13:29:21 ERROR in input [ping]: PING www.google.com (172.217.1.100) 16(44) bytes of data.
24 bytes from 172.217.1.100: icmp_seq=1 ttl=55 time=5.56 ms, Command timed out.
Fatal error processing ping output
```

Super new to telegraf/influxdb/etc so not sure info I can provide to help see what's happening!

**Comment by sparrc** [comment]
@lokenx the default timeout is set to 10s or 5s I think....also I'd ask if you really need multiple pings to be sent? by default telegraf is going to ping once every 10s, sending multiple pings within a single collection interval is a bit of a niche use-case.

**Comment by lokenx** [comment]
@sparrc ah OK that makes sense, now it's working with a single count! Sweet! I'll checkout the docs too 👍

**Comment by kostasb** [comment]
**Bug:** Telegraf ping input plugin assumes a default ping_interval of 0, which should be 1 instead.

**Steps to reproduce:** 
run the ping input plugin against any URL with a count > 1 , leaving the interval and timeout config parameters to default 0.

**Details:**
The default Linux ping interval is to wait for one second between each packet, but Telegraf assigns a default value of 0.

This does not affect the actual ping exec command as no argument is passed to it in this case, but it does affect the calculation of totalTimeout as per `totalTimeout := float64(p.Count)*p.Timeout + float64(p.Count-1)*p.PingInterval` , which results to 0.

When the CombinedOutputTimeout function is called as `out, err := internal.CombinedOutputTimeout(c,time.Second*time.Duration(timeout+1))` the Duration passed to it as argument is timeout+1=1.

If the actual execution time for the execution of "ping" lasts longer than 1 second (which it will , when count is >1 ), a timeout error is thrown by CombinedOutputTimeout.

Setting the timeout config option to a value other than 0 can conceal the bug.

@sparrc

**Comment by sparrc** [comment]
@kostasb can you open a separate issue? I'm actually not sure what the original issue is here anymore, I think people are simply misconfiguring the plugin, and we need to make it more clear that it's easy to configure yourself into a ping command that will timeout.

**Comment by kostasb** [comment]
@sparrc I submitted a new issue for this.
In a few words, if you don't set a ping interval and you have count >1, the plugin will use 0 interval to calculate the execution timeout, while ping utility uses an interval of 1 for each ping, so Telegraf doesn't wait enough time.
