### ISSUE TITLE
elasticsearch input not all data is outputed

### ISSUE THREAD

**Issue by yosefy** [influxdata/telegraf#1656]
## Bug report
telegraf outputs only elasticsearch_indices_*
not filesystem, not cpu.. nothing

### Relevant telegraf.conf:
[[inputs.elasticsearch]]
  servers = ["http://localhost:9200"]
  local = true
  cluster_health = false
### System info:
ubutnu 14.04
[Include Telegraf version, operating system name, and other relevant details]

telegraf nightly

thanks

**Comment by yosefy** [comment]
ok found the problem
elasticsearch 0.90 :

By default, indices stats are returned. With options for indices, os, process, jvm, network, transport, http, fs, and thread_pool

**Comment by sparrc** [comment]
elasticsearch 0.9 is 3 years old and not going to be supported for the full range of metrics. I doubt that elasticsearch itself even supports the full range of metrics.
