### ISSUE TITLE
Ping parse error when count > 0 and ping_interval not specified

### ISSUE THREAD

**Issue by rvrignaud** [influxdata/telegraf#1658]
### Relevant telegraf.conf:

```
[[inputs.ping]]
urls = ['google.fr']
count = 10
```

### System info:

telegraf version : 0.13.2-1
ubuntu 16.04

### Steps to reproduce:

1. paste above configuration
```
# telegraf -test -config /etc/telegraf/telegraf.conf
* Plugin: ping, Collection 1
2016/08/22 14:55:50 PING google.fr (64.233.167.94): 16 data bytes
24 bytes from 64.233.167.94: icmp_seq=0 ttl=52 time=1.283 ms, Command timed out.
Fatal error processing ping output
```

### Expected behavior:
This should output a valid metric and do not fail.

### Actual behavior:
This fail and do not return any data

### Additional information
When adding `ping_interval` value, it works as expected

**Comment by phemmer** [comment]
Looks like a dup of #1654

**Comment by sparrc** [comment]
yep
