### ISSUE TITLE
Add sensor plugin

### ISSUE THREAD

**Issue by exzz** [influxdata/telegraf#168]
Read and forward sensor values (voltage and temperature)

thx

**Comment by sparrc** [comment]
Could you be more specific? Where would we read this data from? What format would it be in?

Also see the exec plugin, which can read arbitrary json data, would that fit your needs?

**Comment by exzz** [comment]
I am thinking about data reported by sensors command. Of course I can use exec plugin to run and parse command line output, but I would prefer a lightweight solution. Collectd use directly libsensors (sensors/sensors.h) to extract voltages, temperatures and fan status.

**Comment by sparrc** [comment]
I see, I thought you were talking about general sensor data, but you mean sensors that are builtin to the machine. This is a good idea and will almost certainly involve using CGo
