### ISSUE TITLE
couchbase address string together with password opened to the world

### ISSUE THREAD

**Issue by yosefy** [influxdata/telegraf#1680]
## Bug report

Security problem
### System info:

[Include Telegraf version, operating system name, and other relevant details]
ubuntu 14.04

[[inputs.couchbase]]
  servers = ["http://admin:xxxxx@localhost:8091"]
### Expected behavior:

take couchbase cluster name via rest api from cluster
### Actual behavior:

takes address string together with password and opens up to the world
for part of the metrics
for example couchbase_bucket_item_count
### Additional info:

couchbase comunity 4.1
telegraf nightly

**Comment by danielnelson** [comment]
Fixed in 1.4.0, thanks @DanKans
