### ISSUE TITLE
How collected data

### ISSUE THREAD

**Issue by gouki777** [influxdata/telegraf#1681]
hi 
I need netstat collected data. but ,Is not I want data.
How to eliminate the unnecessary data. 
i only need NETSTAT   "tcp_established" “tcp_time_wait”
other data i not need.   How to implement

	tele.conf
i write it.but is not good...

 # Read TCP metrics such as established, time wait and sockets counts.
 [[inputs.netstat]]
   # no configuration
 counts =["tcp_established", "tcp_established", "tcp_fin_wait1", "tcp_fin_wait2", "tcp_time_wait"]

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
