### ISSUE TITLE
NETCONF, Sflow, Juniper Network Analytics support (feature request)

### ISSUE THREAD

**Issue by Ebrink** [influxdata/telegraf#1682]
With the redesign of the SNMP plugin for Telegraf done and working nicely, I want to suggest support for NETCONF, Sflow and/or Juniper Network Analytics.

The folks over at Juniper have already created some python scripts that populate InfluxDB with streaming metrics (see: https://github.com/Juniper/open-nti and https://github.com/brunorijsman/juniper-grafana), and it would be nice to have those integrated into telegraf and receive streaming information about your environment.

**Comment by sparrc** [comment]
I believe this is a dupe of https://github.com/influxdata/telegraf/issues/174?

**Comment by Ebrink** [comment]
Fair enough, missed that one. This can be closed.
