### ISSUE TITLE
CPU is too high

### ISSUE THREAD

**Issue by socol1** [influxdata/telegraf#1688]
![image](https://cloud.githubusercontent.com/assets/18021407/18112852/a5736f7c-6f5d-11e6-92a0-07d87bd03445.png)
What can I do ?

**Comment by phemmer** [comment]
Can you provide the telegraf version, what OS you're using, and your config?

Also if you can send telegraf a `SIGQUIT` (note this will cause telegraf to exit), and provide the output it dumps (it'll be on the application's STDERR, wherever you have that going), we can see what it was doing.

**Comment by socol1** [comment]
@phemmer  
Telegraf - version 0.13.1
os - Red Hat Enterprise Linux Server release 6.5 (Santiago)
uname -a  Linux 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by socol1** [comment]
info  is upload

**Comment by sparrc** [comment]
@socol1 can you provide some details on the system you are running on? There is nothing very abnormal about the stack-trace that I can tell.

but, these are the instances that I would say are likely causing the most CPU usage (in order):

1. 18 procstat plugins
1. exec plugin running once every second (this might be the biggest contributor, as I have no idea what it's doing)
1. 18 net_response plugins
1. the 2 inputs.net plugins could be combined into a single instance

I would recommend trying running without the procstat plugins and see how that affects your CPU usage, as well as trying without the exec plugin.

I would also recommend, with the procstat plugin, to use .pid files. If you are not using pid files, then the plugin needs to search for the given executable patterns at each interval. When given a pid file, it simply needs to read the file.

**Comment by socol1** [comment]
@phemmer  thanks ,I'll try it.

**Comment by sparrc** [comment]
@socol1 why did you close the issue? if you solved it can you explain  how?

**Comment by lin-credible** [comment]
#2533
@sparrc

**Comment by socol1** [comment]
@phemmer sorry  Recently changed jobs，I closed the following items：
1）exec plugin
2）procstat plugins
