### ISSUE TITLE
Get Jolokia metric java.lang:name=ConcurrentMarkSweep,type=GarbageCollector

### ISSUE THREAD

**Issue by ihard** [influxdata/telegraf#1693]
Ubuntu 14.04
telegraf 1.0.0-rc1-1

I am trying to get metrics via jolokia and send to graphite

  [[inputs.jolokia.metrics]]
    name = "last_gc_info"
    mbean = "java.lang:name=ConcurrentMarkSweep,type=GarbageCollector"
    attribute = "LastGcInfo"

[[outputs.graphite]]
  servers = ["127.0.0.1:2003"]
  prefix = ""
  template = "host.tags.measurement.field"
  timeout = 2

and generate metrics:
`
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageAfterGc_CMS_Old_Gen "map[init:1.34217728e+08_committed:1.34217728e+08_max:1.34217728e+08_used:3.7298032e+07]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageBeforeGc_Compressed_Class_Space "map[init:0_committed:7.110656e+06_max:1.073741824e+09_used:6.722632e+06]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageAfterGc_Compressed_Class_Space "map[max:1.073741824e+09_used:6.722632e+06_init:0_committed:7.110656e+06]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageAfterGc_Par_Survivor_Space "map[init:1.3369344e+07_committed:1.3369344e+07_max:1.3369344e+07_used:2.085712e+06]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageBeforeGc_Par_Survivor_Space "map[init:1.3369344e+07_committed:1.3369344e+07_max:1.3369344e+07_used:2.085712e+06]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageAfterGc_Metaspace "map[committed:5.7442304e+07_max:-1_used:5.6037976e+07_init:0]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_memoryUsageBeforeGc_Metaspace "map[init:0_committed:5.7442304e+07_max:-1_used:5.6037976e+07]" 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_startTime 6.30074714e+08 1472657380
hostname.telegraf.127_0_0_1.app.8088.jolokia.last_gc_info_duration 184 1472657380
`

how to get the normal metrics?

**Comment by sparrc** [comment]
this should be fixed by https://github.com/influxdata/telegraf/pull/1639 once it's merged

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1639
