### ISSUE TITLE
UTF16PtrToString invalid for multi-instance win_perf_counters 

### ISSUE THREAD

**Issue by recursiveDream** [influxdata/telegraf#1703]
## telegraf

OS: Windows 2008 R2
Ver: 1.0.0
## Problem

Observe any windows performance counter with multiple instances and note the # suffix.  None of these metrics are reported.

```
win_per_counters.go/Gather()
---------------------------------
Problem Code: var s string = win.UTF16PtrToString(c.SzName)
    * When processing a metric.instance with a suffix of  #, only the first two characters are returned from UTF16PtrToString

Hack Fix:
--->                    var multi_instance bool;

--->                    } else if strings.Contains(metric.instance, "#") {
--->                        add = true
--->                        multi_instance = true
--->                    }

--->                            if multi_instance {
--->                                tags["instance"] = metric.instance
--->                            } else {
--->                                tags["instance"] = s
--->                            }
```

**Comment by sparrc** [comment]
I don't really understand what this "problem code" writeup is....can you submit a PR if you know how to fix it?

**Comment by recursiveDream** [comment]
I refrained from a PR due to this being a temporary fix )to convey the issue) and not the proper code-fix.  The problem code extends into golang/win and golang/syscall, and I haven't determined the root cause.

**Comment by bullshit** [comment]
This isn't a issue of UTF16PtrToString. Please see #2352

**Comment by danielnelson** [comment]
I'm going to close this issue since it is quite old and this plugin has had quite a few changes since it was reported.  @recursiveDream Can you test with the latest Telegraf build and if you are having problems report a new issue or comment on #2879.
