### ISSUE TITLE
Ping plugin - report separately for each defined host

### ISSUE THREAD

**Issue by dtanner** [influxdata/telegraf#1705]
## Feature Request

The ping plugin would be more useful for me if it reported each defined host's metrics individually.  This would allow reports to better identify problematic network paths.

### Current behavior:

Currently the plugin combines and statistics for all of the defined hosts. 

### Desired behavior:

Report separately for each defined host

### Use case: 

In my situation, we suspect a sporadic networking issue in one of our data centers.  We've configured a ping test for all of our locations, and are able to see that an issue occurs when we chart the combined metrics.  But we're not able to easily pinpoint which location or locations are bad, since the reported metrics are combined/averaged.

Would this change be a useful global change for others?  Or would it be a new option, keeping existing behavior by default.?  I'd be willing to take a crack at the implementation; I'm pretty green at go yet, but it seems like a pretty simple change.  Thanks for your thoughts.

**Comment by sparrc** [comment]
the ping metrics are already tagged with a `url` tag of the host that it is configured to ping, is that what you are looking for? all metrics also have the `host` tag of the system that they are being collected on.

**Comment by dtanner** [comment]
Ah - thanks @sparrc. Yup - that's what I'm looking for, so no enhancement needed.  Thanks!
