### ISSUE TITLE
telegraf and procstat

### ISSUE THREAD

**Issue by ricou84** [influxdata/telegraf#1708]
hello.

the telegraf service is run by telegraf. 
I use procstat input to monitor users metric like this. 
ex : 
/etc/telegraf/telegraf.d/bapplipuppet-procstat.conf
[[inputs.procstat]]
  prefix = "bapplipuppet"
  user = "bapplipuppet"

telegraf reports log like this:
2016/09/02 17:36:00 Error: procstat getting process, exe: []    pidfile: [] pattern: [] user: [bapplipuppet] Failed to execute /usr/bin/pgrep. Error: 'exit status 1'

I have a workaround : running telegraf as root by modifying the init.d (centos 6), or systemd-unit (centos 7)

But i would like to not use this workdaround if not necessary.

Does somebody have a trick to do it?

Thank a lot

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
