### ISSUE TITLE
TCP Output Plugin

### ISSUE THREAD

**Issue by sumkincpp** [influxdata/telegraf#1711]
## Feature Request

Proposal for adding a new Output plugin for "TCP/UDP Socket Connector" which will allow to send telegraph metrics over TCP/UDP in raw format, i.e. sending metrics like following over tcp/udp socket :

```
dns_query,domain=google.com,host=lab-x1,record_type=A,server=8.8.8.8 query_time_ms=2.729463 1473090404000000000
```

**Comment by sparrc** [comment]
half of this will be closed by https://github.com/influxdata/telegraf/pull/1526

**Comment by sparrc** [comment]
creating a separate issue for UDP Output: #1721
