### ISSUE TITLE
single quote bug in toml parser

### ISSUE THREAD

**Issue by annProg** [influxdata/telegraf#1712]
Hi,

I want to write a regex inclue single quote, I read the offical toml document: 

Since there is no escaping, there is no way to write a single quote inside a literal string enclosed by single quotes. Luckily, TOML supports a multi-line version of literal strings that solves this problem. Multi-line literal strings are surrounded by three single quotes on each side and allow newlines. Like literal strings, there is no escaping whatsoever. A newline immediately following the opening delimiter will be trimmed. All other content between the delimiters is interpreted as-is without modification.
```
regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

If I have a regex like `\d'\w`, it will work fine
```
require_str = '''\d'\w'''
```

But if the regex is end with `'`,   for example : `\d'`, toml parse failed:
```
require_str = '''\d''''
```

```
[root@localhost bin]# ./telegraf -config url.conf -test
Error parsing url.conf, toml: line 80: parse error
```

**Comment by sparrc** [comment]
what if you did

```
require_str = '''
\d'
'''
```
?

**Comment by annProg** [comment]
@sparrc parse successful, thanks!
