### ISSUE TITLE
Modification in Aerospike input plugin

### ISSUE THREAD

**Issue by usdin** [influxdata/telegraf#1720]
## Feature Request

We want Aerospike plugin to support **authentication**. We also need **latency info**. 
Also in dev branch I see that plugin is collecting data for whole cluster, IMO it will be better to collect data of specified nodes only, what if node where Telegraf is running goes down. 
### Proposal:

By using "Connection" struct from aerospike library instead of client, we can collect data for specific node. Connection can be authenticated. Also collecting latency info will require lot of parsing.

**Comment by sparrc** [comment]
Please specify your exact needs & expectations for:

1. authentication
1. latency info
1. node info? although AFAICT we are already collecting this

**Comment by usdin** [comment]
1. Enterprise Edition of Aerospike have authentication support. If Auth is enabled current aerospike input plugin won't be able to collect data. If user provide username:password in config plugin should authenticate itself and collect data.
2. Enterprise AMC shows the latency info, [http://www.aerospike.com/docs/amc/user_guide/enterprise/latency_charts.html]. By collecting latency info we can show these graph in Grafana. Latency info is heavily used by our developers. Also  AMC(both Community Edn and Enterprise) shows throughput graph we can collect that too. 
3. I was referring to current master branch, there you are collecting data of every nodes in cluster. I was suggesting to collect data of specified node only. In our deployment we are running telegraf in  every node, collecting data for whole cluster from each node put lot of duplicate data and if we collect aerospike data from one node it may be SPOF.

**Comment by sparrc** [comment]
> Enterprise AMC shows the latency info, [http://www.aerospike.com/docs/amc/user_guide/enterprise/latency_charts.html]. By collecting latency info we can show these graph in Grafana. Latency info is heavily used by our developers. Also AMC(both Community Edn and Enterprise) shows throughput graph, we can collect that too.

A UI feature doesn't help telegraf very much though, do you have a link to documentation that shows how to fetch this information directly from aerospike? can it be fetched at all from the free edition?

> I was referring to current master branch, there you are collecting data of every nodes in cluster. I was suggesting to collect data of specified node only. In our deployment we are running telegraf in every node, collecting data for whole cluster from each node put lot of duplicate data and if we collect aerospike data from one node it may be SPOF.

before you start working on this, can you explain what the current telegraf data schema looks like (in your setup), and what you would like to see it look like instead?

**Comment by usdin** [comment]
Latency can be collected in same way as name-space and their stats are collected. You can read more [here](http://www.aerospike.com/docs/operations/monitor/v3port/asinfo_latency_monitoring.html). 

I won't be changing schema except for latency, for that I am planning separate measurement.

**Comment by usdin** [comment]
Hi,
I've created PR, please have a look
https://github.com/influxdata/telegraf/pull/2279

**Comment by usdin** [comment]
@sparrc Please look https://github.com/influxdata/telegraf/pull/2279
