### ISSUE TITLE
telegraf init script should not sudo

### ISSUE THREAD

**Issue by lukebigum** [influxdata/telegraf#1727]
If you try start Telegraf from a configuration management daemon like Puppet that's not attached to a TTY, the sudo command in your Red Hat init script fails:

> 2016/09/08 08:52:40 Gathered metrics, (10s interval), from 8 inputs in 17.619436ms
> sudo: sorry, you must have a tty to run sudo

I can see that you are trying to make the user experience slightly better, but it is best not to assume you can gain elevated privileges on your own (what if I don't even have sudo installed?). Leave it up to the operator to do so, and throw an error message if you can detect you don't have privileges.

Haven't checked if any other Influx Data init scripts do this, but if they do they should change as well.

**Comment by sparrc** [comment]
cc @rossmcdonald

**Comment by sparrc** [comment]
@lukebigum what version of telegraf are you running?

**Comment by sparrc** [comment]
I believe this is fixed in 1.0, can you upgrade?: https://github.com/influxdata/telegraf/pull/1205

**Comment by lukebigum** [comment]
It has been fixed, thanks. I downloaded 0.13 RPMs yesterday, now they are 1.0 :-)
