### ISSUE TITLE
Issues with tag matching in Graphite templates

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#1731]
version: 1.0.0

Configuring multiple templates for the Graphite input format will result in the shortest template matching successfully while the rest are ignored.

Example:
```
templates=["measurement.host.metric.metric.metric"]
input: net.server001.a.b.c 2
output: net,host=server001,metric=a.b.c value=2 timestamp
```

```
templates=["measurement.host.metric.metric.metric","measurement.host.metric.metric"]
input: net.server001.a.b.c 2
output: net,host=server001,metric=a.b value=2 
```

```
templates=["measurement.host.metric.metric.metric","measurement.host.metric.metric","measurement.host.metric"]
input: net.server001.a.b.c 2
output: net,host=server001,metric=a value=2
```

Greedy matching (like metric*) which is supported for measurements and fields but not tags, could be considered as a solution.

**Comment by teraflik** [comment]
@sparrc Does telegraf support wildcard matching for tags?

For example
```
templates=["measurement.host.metric"]
input: net.server001.a.b.c 2
```

Will the output be
`net,host=server001,metric=a value=2` or  `net,host=server001,metric=a.b.c value=2`

If it will be the first, is there a way to achieve second?
