### ISSUE TITLE
Exec which outputs valid JSON fails

### ISSUE THREAD

**Issue by Daxda** [influxdata/telegraf#1736]
## Bug report

I'm not sure if this is indeed a bug I encounter, but I can't seem to get the `inputs.exec` to work correctly. When running telegraf directly (no systemd) the error message doesn't appear. But it appears when running it with `systemctl start telegraf`.

### Relevant telegraf.conf:

```
[[inputs.exec]]
  commands = ["/tmp/zone_stats.sh"] 
  timeout = "5s"
  name_override = "zone_stats"
  data_format = "json"
```

### System info:

OS: CentOS 7
TICK stack: v1.0.0 (master c4953cf494f6019995434a6c152496013b7b474b)
(Telegraf v1.0.0)

### Steps to reproduce:

1. Copy the script (in Additional Info section) to `/tmp/zone_stats.sh`.
    (Change the paths to example files if needed)
2. Edit `/etc/systemd/system/multi-user.target.wants/telegraf.service` and define the config file we want to use instead.
3. Reload and restart the service with `systemctl daemon-reload && systemctl start telegraf`
4. `tail -f` the `/etc/telegraf/telegraf.log` for `ERROR`s.

### Expected behavior:

My **valid** JSON data should be dumped into the influxdb.

### Actual behavior:

An error message appears in `telegraf.log` which reads:

```
ERROR in input [exec]: Errors encountered: [point without fields is unsupported]
```

### Additional info:

I'm using a simple bash script which `wc -l` a few zone files and echos valid JSON to stdout:

```bash
tracked_zones="name1.zone name2.zone"
zone_dir="/var/named"
sep=""

output="{"
for zone_filename in $tracked_zones
do
	current_zone="$zone_dir/$zone_filename"
	if [ -f "$current_zone" ]
	then
		count=$(wc -l "$current_zone" | cut -d " " -f 1)
		output="$output$sep\"$zone_filename\": $(($count - 12))"
		sep=","
	fi
done
echo -e "$output}"
```

Example output:
```json
{"name1.zone": 24,"name2.zone": 8}
```

**Comment by sparrc** [comment]
thank you for the detailed information, this might be a permissions issue, can you try running telegraf directly as the telegraf user?

```
sudo -u telegraf telegraf --config /etc/telegraf/telegraf.conf
```

**Comment by Daxda** [comment]
Thanks for the hint!

```
sudo -u telegraf /tmp/zone_stats.sh 
{}
```

Now I start to understand why the message ocurr.
