### ISSUE TITLE
SNMP plugin only specific oid´s

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/telegraf#1739]
Ive got a cisco 6500 VSS stack with ALOT of interfaces, only a few are really interested and i want to be able to ONLY pull the IF-MIB::ifHCOutOctets & IF-MIB::ifHCInOctets oids from a specific subset of interfaces. If i snmpwalk/get the oids like
**snmpget -v2c -c'public' 10.60.129.1 IF-MIB::ifHCInOctets.12**
i get data like
**IF-MIB::ifHCInOctets.12 = Counter64: 403270057137**
but how to tie this together in the .conf i dont understand - only output from telegraf with -test is 
"* Plugin: snmp, Collection 1"

using inputs.snmp.table with IF-MIB::ifXTable returns too much and actually loads the switches 20-40% so its not possible to do it the bulky way.

any help would really be appritiated

**Comment by sparrc** [comment]
using snmp.field gets a specific OID:

```
# Retrieves SNMP values from remote agents
[[inputs.snmp]]
  agents = [ "127.0.0.1:161" ]
  timeout = "5s"
  version = 2

  # SNMPv1 & SNMPv2 parameters
  community = "public"

  # SNMPv2 & SNMPv3 parameters
  max_repetitions = 50

  # SNMPv3 parameters
  #sec_name = "myuser"
  #auth_protocol = "md5"         # Values: "MD5", "SHA", ""
  #auth_password = "password123"
  #sec_level = "authNoPriv"      # Values: "noAuthNoPriv", "authNoPriv", "authPriv"
  #context_name = ""
  #priv_protocol = ""            # Values: "DES", "AES", ""
  #priv_password = ""

  # measurement name
  name = "system"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.0.0.1.1"
  [[inputs.snmp.field]]
    name = "uptime"
    oid = ".1.0.0.1.2"
  [[inputs.snmp.field]]
    name = "load"
    oid = ".1.0.0.1.3"
  [[inputs.snmp.field]]
    oid = "HOST-RESOURCES-MIB::hrMemorySize"
```
