### ISSUE TITLE
Support for AWS Elasticsearch

### ISSUE THREAD

**Issue by joshuaspence** [influxdata/telegraf#1754]
Telegraf has an Elasticsearch input but it cannot be used with Amazon's Elasticsearch service because the requests aren't signed as per http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html. As a workaround, it should be possible to use a proxy to sign requests from Telegraf (such as https://github.com/coreos/aws-auth-proxy), but it would be great if Telegraf could support the AWS request signing natively.

**Comment by egee-irl** [comment]
Unsure if this helps but for folks Googling, Telegraf does not work with AWS managed ElasticSearch directly due to the issues @joshuaspence stated above.

A workaround is to simply plug Telegraf into CloudWatch using the ES namespace.

**Comment by harpritc** [comment]
Hi is it case still open? Do we have the support now for AWS Elastic search?

**Comment by danielnelson** [comment]
@harpritc Still open and unresolved, I could take a look at this though if you can help test.

**Comment by danielnelson** [comment]
After looking at the amount of new options that would need to be added to the plugin to support this, I've soured on the idea of implementing this feature.  Also, based on my reading, this shouldn't be needed if running Elasticsearch and Telegraf in the same VPC, so it shouldn't affect all users of Amazon Elasticsearch Service.

I am going to close this issue, for those using a internet facing AWS Elasticsearch, you will need to use an request signing proxy.

**Comment by harpritc** [comment]
Sure, that will be great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
