### ISSUE TITLE
Allow `omit_hostname` to be configured for individual inputs

### ISSUE THREAD

**Issue by joshuaspence** [influxdata/telegraf#1757]
Currently, the `omit_hostname` parameter can only be set in the global configuration. We are using Telegraf to monitor a remote system and, as such, wish to omit the hostname (which is irrelevant to the collected data) from one given input. It seems, however, that `omit_hostname` cannot be used on individual inputs:

```
Error parsing /etc/telegraf/telegraf.conf, line 41: field corresponding to `omit_hostname' is not defined in `*elasticsearch.Elasticsearch'
```

**Comment by sparrc** [comment]
use `tagexclude`, see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md
