### ISSUE TITLE
[statsd feature request] Support raw metric type

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#1759]
Some statsd clients, like [python-statsd](https://python-statsd.readthedocs.io/en/latest/statsd.raw.html) support a raw metric type, which is not a part of [etsy statsd specification](https://github.com/etsy/statsd/blob/master/docs/metric_types.md).

Raw metric format can look like `metric_name:1.0|r`

Telegraf could support raw metrics by enabling a configurable setting "raw_metric_type = data_format " for the user to set the data type that they want Telegraf to assume for raw metrics (string,float,int).

**Comment by danielnelson** [comment]
If anyone still wants this feature please comment and we can reopen.
