### ISSUE TITLE
Report DB Metrics In Redis Plugin

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/telegraf#1767]
## Feature Request

Redis `INFO` also gives some useful info about the DBs in a given instance. It tells you

- number of keys
- number of keys with TTLs set

Newer version also tell you the avg_ttl

I think it would be useful if the redis plugin also tracked these metrics about the specific databases that make up the redis instance

### Proposal:

New measurement: 

`redis_database`

Tag(s):

db_number

Fields:

keys
expires
avg_ttl (if available)

I think this should just always be sent, but there could also be a config value to turn this feature on and off

### Current behavior:

The plugin doesn't send info about the databases

### Desired behavior:

The plugin sends info about the databases

### Use case: [Why is this important (helps with prioritizing requests)]

The number is keys is especially helpful if there are multiple databases running on a single instances we can see the memory used by the instance, but can't see how many keys are in a given database. This gives us a better visibility into the Redis instance.

**Comment by phemmer** [comment]
The plugin already does this. See the `redis_keyspace` measurement.

**Comment by mpchadwick** [comment]
Your right I noticed that after opening the issue. The docs make no mention of this feature, but that's a separate issue.

**Comment by sparrc** [comment]
@mpchadwick could you submit a docs change PR? It's quite easy to edit in-browser and submit
