### ISSUE TITLE
Couchbase plugin does not handle memcached buckets

### ISSUE THREAD

**Issue by theborax** [influxdata/telegraf#1771]
I found a bug when testing a bit with telegraf and couchbase. Basically the plugin does not handle memcached (pure in-memory) buckets at all. The output from an ordinary bucket looks like the following:
data_used=14208526,disk_fetches=0,disk_used=36212218,item_count=58,mem_used=106753224,ops_per_sec=0,quota_percent_used=1.509605692798981 1473931335000000000

whilst it does not use any disk at all if it's a memcached bucket, so the output becomes:
data_used=,disk_fetches=,disk_used=,item_count=14,mem_used=5776,ops_per_sec=0,quota_percent_used=0.0003586212793986003 1473931335000000000

which influx does not like at all... I propose that all disk related parameters should be dropped in case they are missing.

**Comment by yellowmegaman** [comment]
I'm experiencing the same problem. Got both in-memory and ordinary buckets.
Worst of all, while failing to write data related to memcached bucket, it won't  write any other data, resulting in error:

disk_fetches=,\\,disk_used=,\\,item_count=0,data_used=,mem_used=0,ops_per_sec=0,quota_percent_used=0 1475066910000000000': missing field value\nunable to parse

finally resulting in:
"Could not write to any InfluxDB server in cluster"

Telegraf 1.0.0
Debian jessie / Ubuntu 14.04
Couchbase CE 4.0.0-4051-1

Proposal: let us choose bucket name(s) to gather metrics from. (as a parameter)
Thanks a lot in advance!

**Comment by folex** [comment]
Got same problem as @yellowmegaman
