### ISSUE TITLE
Input Plugin Request: Kubernetes

### ISSUE THREAD

**Issue by jchauncey** [influxdata/telegraf#1774]
### Proposal:
Right now it is possible to gather some kubernetes metrics via the prometheus url within kubernetes api. However, we have found that the metrics we receive from that endpoint are not particularly useful because they are not in the correct unit. For example, they only report CPU usage as `usage in seconds`. 

Our current solution also has a scalability issue: Since we run the telegraf daemon in a daemonset (runs on every node of the cluster) we eventually knock over the API server because we are polling it too often.

### Desired behavior:
Instead we should poll the local kubelet api. It contains a `/stats` handler that contains the following useful urls:

* `/stats/summary`
* `/stats/container`

Both of these endpoints contain detailed information about the pods and containers running on a particular host. This gives us the advantage of being able to scale a kubernetes installation to hundreds of nodes each one running telegraf without killing the API server. 

### Use case: [Why is this important (helps with prioritizing requests)]
Right now Deis ships telegraf as part of our default monitoring solution. By getting this change into telegraf it would allow us to install deis as part of a kubernetes fleet of dozens or even hundreds of nodes without having change the telegraf configuration. 

I will begin work on this plugin fairly soon but I wanted to get this formality out of the way first =).

**Comment by sparrc** [comment]
sounds good :+1:
