### ISSUE TITLE
Make Input/Output Plugins Optional in Main Configuration

### ISSUE THREAD

**Issue by jamescarr** [influxdata/telegraf#1781]
_Please note, the quickest way to fix a bug is to open a Pull Request._
## Bug report

I set up our ansible roles to spit out relevant intput / output configurations under `/etc/telegraf/telegraf.d` which, when the playbook runs, generates them all and starts telegraf at the end. 

Unfortunately, it seems that telegraf will fail to start if no inputs or outputs are defined in the main configuration. 
### Steps to reproduce:
1. Omit inputs or outputs from the main config and include them instead under `/etc/telegraf/telegraf.d`
2. start telegraf
3. check error log
### Expected behavior:

Inputs / Outputs defined under the `telegraf.d` dir should simply be picked up when starting telegraf. Telegraf shouldn't complain of their absence in the main config.
### Actual behavior:

Telegraf complains about missing `inputs` or `outputs` section and exits.

**Comment by envintus** [comment]
This would helpful once fixed. We're creating a telegraf container that by default has no inputs. The inputs themselves will be fleshed out using kubernetes configMaps, so testing a container build is a bit of trouble since a simple configuration with just the base agent configs causes the container to exit.

**Comment by francois2metz** [comment]
I cannot reproduce it. Can you try again? Or give me a sample of your config files.

**Comment by danielnelson** [comment]
@envintus Please reopen if you are still experiencing this issue.
