### ISSUE TITLE
Cloudwatch Input error retrieving metrics on 1.0.0-alpine

### ISSUE THREAD

**Issue by johnrengelman** [influxdata/telegraf#1783]
It appears that the Alpine images are missing the necessary certificates to establish HTTPs connection.
The `cloudwatch` input returns this error:

```
Post https://monitoring.us-east-1.amazonaws.com/: x509: failed to load system roots and no roots provided
```

**Comment by sparrc** [comment]
@johnrengelman what is the bug here exactly? are you requesting that telegraf's default docker images install https by default? shouldnt that be a bug in the docker repo?

**Comment by johnrengelman** [comment]
@sparrc it looks like maybe Amazon rotated the cert (around Sept. 5, 2016), so the container just had an out-of-date cert. It appears that the Dockerfile is installing the CA base certificates, so I think we're fine.

**Comment by sparrc** [comment]
OK, thanks, in that case I'll close this out
