### ISSUE TITLE
Windows Service results in no log output

### ISSUE THREAD

**Issue by peter-murray** [influxdata/telegraf#1786]
### System info:
* telegraf version 1.0.0
* Windows Server 2012R2

### Steps to reproduce:
Install the Windows service and then run it, there is no log output provided in files or the event log.

### Expected behavior:
Log some output from the telegraf process

### Actual behavior:
Nothing logged anywhere

### Additional info:
In the old days of using the nssm wrapped approach, you could just redirect the stdout and stderr to a file, which worked fine.

Now that the service is being run using the Go service libraries, you probably have to utilize the event log and/or some log file output that captures the stdout/stderr differently under Windows.

**Comment by sparrc** [comment]
https://github.com/influxdata/telegraf/pull/1838 added the ability to specify the logfile as a configuration option.

I've created a separate issue for sending to the Windows event log: https://github.com/influxdata/telegraf/issues/1840
