### ISSUE TITLE
SNMP per host community 

### ISSUE THREAD

**Issue by vasya4k** [influxdata/telegraf#1787]
Trying to make my config work after the upgrade. As it was previously, each host had it's own community:

[[inputs.snmp.host]]
    address = "xxx-91-s1.ss:161"
    # SNMP community
    community = "GmCuy" # default public

Now it appears not longer possible:

 [[inputs.snmp]]
  agents = [ "172.16.1.13" ]
  version = 2
  community = "public"
  interval = "10s"
  timeout = "10s"

  name = "pts_stats"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "ifTable"
    oid = "IF-MIB::ifPhysAddress.1"

As the community string is defined for all agents. I have not tried yet but I think it might be possible to add  [[inputs.snmp]] twice or as many times as needed still it is really inconvenient.  One possible solution might be to allow for something like 

agents = [ "172.16.1.13:161:public", "172.16.1.13:161:public"]
 
This is important as most of the network devices do not share the same community string for security reasons. This would also help if telegraf config is auto generated with a script.

**Comment by sparrc** [comment]
Sorry for the inconvenience, but this is no longer possible. You can define multiple [[inputs.snmp]] instances in your config file.

telegraf config is auto-generated: `telegraf --sample-config`

**Comment by vasya4k** [comment]
Why not it is not that hard to add I guess ? What about the other features like sub tables and include instances they are not longer available as well any plans to reimplement ? It might be a silly question but what was the reason behind this rewrite ?

**Comment by sparrc** [comment]
most of the feedback from users on the old snmp plugin were negative, it had a large number of outstanding issues, the code was not maintainable, and the plugin author did not have time to help. see https://github.com/influxdata/telegraf/pull/1389

**Comment by helotpl** [comment]
I have same problem. Is there solution?

**Comment by danielnelson** [comment]
@helotpl The solution is to define the plugin again for each community.  We know this can be difficult if you have many community values but attempting to support all possible configs without duplication results in the configuration becoming too complicated.
