### ISSUE TITLE
snmp config help

### ISSUE THREAD

**Issue by madsholme** [influxdata/telegraf#1788]
I have ben trying to get telegraf to monitor and log snmp from a cisco asa 5585 unit for a week now, but i am having a hard time to figure out how to get it to log the data in a correct form. The idea is to log it into influxdb, and use grafana to do some statestic on it.

What i need is:
Out and In trafic on the 3 ports.

On my linux maschine i can do these commands:

user@admGrafana:~$ snmpwalk -v 2c -c public 172.18.0.5 IF-MIB::ifDescr
IF-MIB::ifDescr.1 = STRING: Adaptive Security Appliance 'outside' interface
IF-MIB::ifDescr.2 = STRING: Adaptive Security Appliance 'SKOLE_Inside' interface
IF-MIB::ifDescr.3 = STRING: Adaptive Security Appliance 'Skole_DMZ' interface

user@admGrafana:~$ snmpwalk -v 2c -c public 172.18.0.5 IF-MIB::ifOutOctets
IF-MIB::ifOutOctets.1 = Counter32: 2048815989
IF-MIB::ifOutOctets.2 = Counter32: 2688875990
IF-MIB::ifOutOctets.3 = Counter32: 3395303959

user@admGrafana:~$ snmpwalk -v 2c -c public 172.18.0.5 IF-MIB::ifOutOctets
IF-MIB::ifOutOctets.1 = Counter32: 2043223976
IF-MIB::ifOutOctets.2 = Counter32: 2557510871
IF-MIB::ifOutOctets.3 = Counter32: 3395303406

I have managed to get it to log uptime from it by using this config:

[[inputs.snmp]]
  agents = [ "172.18.0.5:161" ]
  version = 2
  community = "public"
  name = "system"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "iso.3.6.1.2.1.1.5.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "iso.3.6.1.2.1.1.3.0"

How do i get it to use my MIB files, so i can use IF-MIB::ifOutOctets, instead of iod numbers?
How do i get it to log the above, so it tags the data from each interface?

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

**Comment by vasya4k** [comment]
You would probably want to use a previous version of telegraf 0.13.1  as it was much easier to deal with plus it had a helpful redme. Currently you need to do something like this to make it work:

[[inputs.snmp]]
	agents = [ "172.18.0.5:161" ]
	version = 2
	community = "public"
	name = "system"
 [[inputs.snmp.table]]
    name = "bytes_recv"
   [[inputs.snmp.table.field]]
      name = "your_interface_name"
      oid = "IF-MIB::ifOutOctets.1" 
   [[inputs.snmp.table.field]]
      name = "your_second_interface_name"
      oid = "IF-MIB::ifOutOctets.2" 

It was possible to  filter interfaces with a list in 0.13.1 however I think this is no longer possible.

**Comment by madsholme** [comment]
thanks for the reply.

last question, the output i get, for OutOctets and InOctes, how do i convert those to kbit/s or mbit/s ?

**Comment by sparrc** [comment]
thanks @vasya4k but obviously I disagree about reverting to an unsupported version

**Comment by vasya4k** [comment]
you need yo use derivative function in Grafana example:

SELECT 8 * derivative(mean("ifHCInOctets"),1s) AS "ifHCInOctets" FROM "ifHCInOctets" WHERE "instance" ='xe-8/0/2' AND "snmp_host"='xxx' AND $timeFilter GROUP BY time($interval) fill(null)

You need to switch to raw mode in query editor.
P.S/
 I am not against the new version just wondering why ? I personally can work around the missing features but I lot of people won't. Collecting metrics from network devices is a huge use case for influx DB having feature reach SNMP collector will definitely make Influx DB more popular and possibly bring new clients for the enterprise version.

**Comment by madsholme** [comment]
thanks. do i need to add a url to my oid files somwhere? 

I keep getting:

ParseInt: parsing "IF-MIB::ifInOctets": invalid syntax
2016/09/19 12:58:10 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0

if i look at the readme, there isent much information on how to add it?
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp

i have tried to change it to oids:

[[inputs.snmp.table]]
name = "bytes_recv"
[[inputs.snmp.table.field]]
name = "Outside"
oid = ".3.6.1.2.1.2.2.1.10.1" 
[[inputs.snmp.table.field]]
name = "Skole_inside"
oid = ".3.6.1.2.1.2.2.1.10.2"
[[inputs.snmp.table.field]]
name = "Skole_DMZ"
oid = ".3.6.1.2.1.2.2.1.10.3"

[[inputs.snmp.table]]
name = "bytes_sent"
[[inputs.snmp.table.field]]
name = "Outside"
oid = ".3.6.1.2.1.2.2.1.16.1" 
[[inputs.snmp.table.field]]
name = "Skole_inside"
oid = ".3.6.1.2.1.2.2.1.16.2"
[[inputs.snmp.table.field]]
name = "Skole_DMZ"
oid = ".3.6.1.2.1.2.2.1.16.3"

but it says:
2016/09/19 13:04:00 ERROR: input [snmp] took longer to collect than collection interval (10s)
2016/09/19 13:04:00 ERROR in input [snmp]: agent 172.18.0.5:161: performing bulk walk: Request timeout (after 5 retries)
2016/09/19 13:04:00 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0

i can use snmpwalk with both iods and the names just fine?

**Comment by vasya4k** [comment]
Try 

[[inputs.snmp.table]]
name = "bytes_sent"
[[inputs.snmp.table.field]]
name = "bytes"
oid = "IF-MIB::ifOutOctets" 
[[inputs.snmp.table.field]]
name = "descr"
oid = "IF-MIB::ifDescr"
is_tag = true

That way it will collect statistics from all interfaces and will add descriptions as tags. If you want to get just one interface you could go like this I think:

[[inputs.snmp.field]]
    name = "bytes_sent"
    oid = "IF-MIB::ifOutOctets"
[[inputs.snmp.field]]
    name = "bytes_sent"
    oid = "IF-MIB::ifDescr"
    is_tag = true

Instead of the whole table block. Sorry i do not have the current version running had to roll back as cannot afford down time. But the above should work i think. Let me know if it does not.

**Comment by madsholme** [comment]
thanks for taking your time, its hard to find proper guides on this.

i tried the above, and it gave the following output:

user@admGrafana:~$ telegraf -config telegraf_snmp.conf
2016/09/19 13:37:42 Attempting connection to output: influxdb
2016/09/19 13:37:42 Successfully connected to output: influxdb
2016/09/19 13:37:42 Starting Telegraf (version 1.0.0)
2016/09/19 13:37:42 Loaded outputs: influxdb
2016/09/19 13:37:42 Loaded inputs: snmp
2016/09/19 13:37:42 Tags enabled: host=admGrafana
2016/09/19 13:37:42 Agent Config: Interval:10s, Debug:true, Quiet:false, Hostname:"admGrafana", Flush Interval:10s
2016/09/19 13:37:50 ERROR in input [snmp]: agent 172.18.0.5:161: performing bulk walk: marshal: Unable to parse OID: strconv.ParseInt: parsing "IF-MIB::ifOutOctets": invalid syntax
2016/09/19 13:37:50 Input [snmp] gathered metrics, (10s interval) in 342.954µs

if i change it to use the oid numbers like so:

[[inputs.snmp.table]]
name = "bytes_sent"
[[inputs.snmp.table.field]]
name = "bytes"
oid = ".3.6.1.2.1.2.2.1.16"
[[inputs.snmp.table.field]]
name = "descr"
oid = ".3.6.1.2.1.2.2.1.2"
is_tag = true

i get:

2016/09/19 13:42:50 ERROR: input [snmp] took longer to collect than collection interval (10s)
2016/09/19 13:42:50 ERROR in input [snmp]: agent 172.18.0.5:161: performing bulk walk: Request timeout (after 5 retries)
2016/09/19 13:42:50 Input [snmp] gathered metrics, (10s interval) in 10.004370636s
2016/09/19 13:42:50 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0

**Comment by vasya4k** [comment]
Have you tried with fields instead 
[[inputs.snmp.field]]
name = "bytes_sent"
oid = "IF-MIB::ifOutOctets.1"
[[inputs.snmp.field]]
name = "bytes_sent"
oid = "IF-MIB::ifDescr.1"
is_tag = true

try both numbers and text formats for an OID

**Comment by madsholme** [comment]
thanks that seems to be working :) so the counter that comes in, need to be multiplied with 8, and that gives me the speed value in? kbit?

**Comment by vasya4k** [comment]
You get negatives because you are not filtering it to a specific interface. All of your data points should be tagged with an interface description. Please log into influxdb  web interface and run these queries and paste output here:

SHOW TAG KEYS FROM "bytes_sent"
SHOW TAG VALUES FROM "ifInDiscards" WITH KEY = "every key name from the above"

**Comment by madsholme** [comment]
SHOW TAG KEYS FROM "bytes_sent"
-this shows nothing

if i do
SHOW TAG KEYS
i get:
agent_host
bytes_sent
host

If i do either of those i get nothing..

as a test, i wrote a small sh script, that adds they value from: 
snmpget -v 2c -c public 172.18.0.5 IF-MIB::ifInOctets.1 -Ov

into my influxdb, and that seems to be working ok, but i cant figure out how to make those numbers into anything meaning full? (like speed)

**Comment by vasya4k** [comment]
Let`s start again :

SHOW MEASUREMENTS
and after for every measurement 
SHOW TAG KEYS FROM "measurement"
SHOW TAG VALUES FROM "measurement" WITH KEY ="every key name from the above"

Paste here i will have a look

**Comment by madsholme** [comment]
SHOW TAG VALUES FROM "SkoleAsa" WITH KEY ="host"
outputs:

key	value
host	"admGrafana"

SHOW TAG VALUES FROM "SkoleAsa" WITH KEY ="bytes_sent"
outputs:

key	value
bytes_sent	"Adaptive Security Appliance 'outside' interface"

SHOW TAG VALUES FROM "SkoleAsa" WITH KEY ="agent_host"
outputs:


key	value
agent_host	"172.18.0.5"

**Comment by vasya4k** [comment]
Ok somehow your measurement name is SkoleAsa and tag key is bytes_sent value of that key is Adaptive Security Appliance 'outside' interface . Now query in grafana would be:

SELECT 8 * derivative(mean("SkoleAsa"),1s) AS "SkoleAsa" FROM "SkoleAsa" WHERE "bytes_sent" ='Adaptive Security Appliance 'outside' interface' AND "agent_host"='172.18.0.5' AND $timeFilter GROUP BY time($interval) fill(null)

Perhaps query can fail as you might need to escape 'outside' quotes. /^Adaptive Security Appliance 'outside' interface$/  Or something like that you need to look it up in grafana docs

**Comment by madsholme** [comment]
Perfect thanks for taking your time! i think i am starting to understand the idea behind it :)

**Comment by PsychoSid** [comment]
Just caught this as going through the same pain. Is there anyway to pull from all available interfaces without having to explicitly name each one with the new SNMP plugin. It was very easy with CollectD ?

**Comment by vasya4k** [comment]
Yeah that is what this new version does by default. The pain comes when you have 50000 interfaces.

 [[inputs.snmp.table]]
    name = "interface_counters"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "bytes_recv"
      oid = ".1.3.6.1.2.1.31.1.1.1.6"
    [[inputs.snmp.table.field]]
      name = "bytes_sent"
      oid = ".1.3.6.1.2.1.31.1.1.1.10"
    [[inputs.snmp.table.field]]
      name = "interface_name"
      oid = ".1.3.6.1.2.1.31.1.1.1.1"
      is_tag = true

That should work however this will use "interface_counters" as a measurement name and other names will be tags of that  measurement.

**Comment by madsholme** [comment]
would it be possible to use the old snmp plugin with the new version of telegraf?

**Comment by PsychoSid** [comment]
@vasya4k Thanks works a treat

**Comment by ashuw018** [comment]
@vasya4k  was going through this one and found very useful information regarding SNMP. i have a query

======
SELECT 8 * derivative(mean("ifHCInOctets"),1s) AS "ifHCInOctets" FROM "ifHCInOctets" WHERE "instance" ='xe-8/0/2' AND "snmp_host"='xxx' AND $timeFilter GROUP BY time($interval) fill(null)
=====

With the above query as suggested by you. is the data unit will become bit/sec or bytes/sec or mb/sec ? and also what unit we will need to set in X axes unit setting field of Grafana graph panel ?

Thanks.
