### ISSUE TITLE
Add SNMP plugin to the default config file template

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#1789]
The legacy snmp plugin is marked as deprecated in the template config file but there is no section for the new snmp plugin.

```
# # DEPRECATED! PLEASE USE inputs.snmp INSTEAD.
# [[inputs.snmp_legacy]]
```

https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf

**Comment by sparrc** [comment]
it should be in the default file that gets installed with 1.0.0, I'm not sure how it happened that I didn't merge this change into master as well
