### ISSUE TITLE
Is there a built-in port check metric function and error log collecting function?

### ISSUE THREAD

**Issue by iyouruby** [influxdata/telegraf#1799]
I want to check my application's tcp port 3303. Is there a built-in port check function? I also want to collect the error log infomation to influxdb, and alerting by kapacitor. How can I do that?

**Comment by sparrc** [comment]
you probably want https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response

**Comment by iyouruby** [comment]
@sparrc Thanks.
