### ISSUE TITLE
is it a bug

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [influxdata/telegraf#1802]
os:centos7
telegraf v:1.0
when i use the same config file but different way to start  will get different result

1. systemctl start telegraf
![qq 20160922173149](https://cloud.githubusercontent.com/assets/18111540/18743195/7c6b9976-80ea-11e6-94cf-67a520dbcbec.png)

2. telegraf -config /etc/telegraf/telegraf.conf
![qq 20160922173305](https://cloud.githubusercontent.com/assets/18111540/18743229/a5dc2c80-80ea-11e6-8f7a-f78ea71b558e.png)

the docker service is on
the config：
![qq 20160922173442](https://cloud.githubusercontent.com/assets/18111540/18743280/e1f7d868-80ea-11e6-9fe5-ab675bc58bc7.png)

**Comment by sparrc** [comment]
it's a permissions issue, the telegraf user needs to be able to access the docker socket. try `sudo -u telegraf telegraf -config /etc/telegraf/telegraf.conf`
