### ISSUE TITLE
[Feature] Self/Agent metrics

### ISSUE THREAD

**Issue by johnrengelman** [influxdata/telegraf#1808]
### Proposal:
Input plugin that collects metrics from the telegraf agent about the operation of inputs.
Things that would be interesting to see would be metric buffer fullness, total metrics collected, dropped metrics.

### Use case: [Why is this important (helps with prioritizing requests)]
This would be useful when using the new `http_listener` input as a middle tier to batch metrics from a large deployment. You could then use these metrics to scale the middle tier.

**Comment by phemmer** [comment]
See #1348

**Comment by johnrengelman** [comment]
Thanks @phemmer. Wasn't able to find that earlier for some reason.
