### ISSUE TITLE
mips64 version

### ISSUE THREAD

**Issue by evanrich** [influxdata/telegraf#1809]
Is there a mips64 version avialable?  I'd like to install this on an Ubiquiti edgerouter lite, but amd64 won't work.

**Comment by sparrc** [comment]
golang does appear to have experimental support for mips64, but you will need to build from source to get it.

**Comment by dnascimento** [comment]
@evanrich one of the dependencies does not compile mips64:
```
[ERROR] run: Command 'GOOS=linux GOARCH=mips64 go build -o /go/src/github.com/influxdata/telegraf/build/telegraf -ldflags="-X main.version=11.0.0-beta3-187-gbabd37b -X main.branch=master -X main.commit=babd37bf3525cf6de09336ca94d731ba331ef94f" ./cmd/telegraf' failed with error: # github.com/shirou/gopsutil/host
../../shirou/gopsutil/host/host_linux.go:116: undefined: sizeOfUtmp
../../shirou/gopsutil/host/host_linux.go:121: undefined: sizeOfUtmp
../../shirou/gopsutil/host/host_linux.go:123: undefined: utmp
```
I created a git issue: https://github.com/shirou/gopsutil/issues/273

Be aware that telegraf is a 26MB binary and it consumes quiet a lot of resources. 
@sparrc ever you considered to develop a C based telegraf, micro-telegraf, designed for IoT devices?

**Comment by sparrc** [comment]
@dnascimento we haven't considered doing that, if your resources are that constrained you might want to consider just running collectd

**Comment by dnascimento** [comment]
Fantastic! Just what we were looking for! Thanks @sparrc 
https://github.com/influxdata/influxdb/blob/master/services/collectd/README.md
