### ISSUE TITLE
Add RabbitMQ Queue idle_since

### ISSUE THREAD

**Issue by jmmk** [influxdata/telegraf#1811]
When a queue has no traffic, there will be an extra field in the JSON called `idle_since`.

`idle_since` is nice to monitor queue activity/uptime. Tracking the message rates over time could give a similar number, but it's not as straightforward and you wouldn't have the timestamp which can be very useful for diagnosing issues.

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1844

**Comment by tivnet** [comment]
Better would be `idle_for` (seconds).
