### ISSUE TITLE
Improve SNMP plugin error logging

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#1814]
It would help with troubleshooting if errors mentioned particular failing OID's in the SNMP plugin.

E.g. appending the OID that failed to the error log would help identify problematic ones: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/snmp.go#L448

**Comment by phemmer** [comment]
Agree. Its a trivial change. I'll try to get to it tonight, and see if there's any other errors which can benefit from more context.

**Comment by Ebrink** [comment]
It would also be helpfull if the errorlog would contain the specific SNMP instance and/or device that is failing. Every once in a while I get a "snmp collection took longer than collection interval", but it is hard to find out which instance or device produces the error with 53 SNMP instances polling 400+ devices.

**Comment by kostasb** [comment]
@phemmer For the OID, I think it would suffice to append the string to the message as `"performing get on %s",oid`.  It would also be useful to specify the actual agent that encountered the polling error.

**Comment by kostasb** [comment]
@phemmer @sparrc  We are still logging some messages, particularly full-on timeouts without an agent / OID to identify what the failure was about:

```
2016/12/13 12:31:15 E! ERROR: input [inputs.snmp] took longer to collect than collection interval (5m0s)
```

**Comment by phemmer** [comment]
I have a local branch where I've done most of the work on this, just need to finish it up (mostly just make sure I didn't miss anything). I'll see if I can get to it this weekend.

**Comment by kostasb** [comment]
Thanks @phemmer for the PR.

As for the `took longer to collect than ...` error messages, I believe @sparrc plans on adding a naming scheme for plugins: https://github.com/influxdata/telegraf/issues/1815
