### ISSUE TITLE
values send from telegraf to influxdb different when insterted as metric

### ISSUE THREAD

**Issue by egar** [influxdata/telegraf#1819]
## issue
since using exec input for sending lsof OS metric ,After a few hours monitoring metric from  exec inputs telegraf dieferent when insert to Inluxdb

### Relevant telegraf.conf:

using exec inputs

```
 [[inputs.exec]]
   commands = ["/etc/telegraf/telegraf.d/lsof.sh"]
   data_format = "influx"
```
 [root@ovocollpapp1 ~]# more /etc/telegraf/telegraf.d/lsof.sh 
#! /bin/bash
#cat /proc/sys/fs/file-nr | awk '{ print $1 }'
LSOF=`/usr/sbin/lsof | wc -l`
HOST=`uname -n`
echo "lsof,host=$HOST value=$LSOF

### System info:

RHEL 6.8

Telegraf - version 1.0.0

### Steps to reproduce:

UNKNOWN

### Expected behavior:
metric value from telegraf should be same in influxdb 

### Actual behavior:

diferent value metric from telegraf and influxdb : 

Telegraf
```
telegraf --config /etc/telegraf/telegraf.conf -test -input-filter exec
* Plugin: exec, Collection 1
> lsof,apps=OVO,host=ovocollpapp1 value=**3050** 1475023996000000000

telegraf --config /etc/telegraf/telegraf.conf -test -input-filter exec
* Plugin: exec, Collection 1
> lsof,apps=cdds,host=cddspapp7 value=19507 1475024665000000000

```
In Influxdb
```
time	                 apps	host	      value
2016-09-28T00:57:00Z	"OVO"	"ovocollpapp1"	 923
2016-09-28T01:04:51Z	"cdds"	"cddspapp7"	2562
```

### Proposal:
try to discover why value is diferent , please also help

**Comment by egar** [comment]
found soemthing,

when running telegraf not as a service, value of metric same :  

`telegraf --config /etc/telegraf/telegraf.conf &`

from  influxdb :+1: 
`time	apps	host	value
2016-09-27T18:37:30Z	"OVO"	"ovocollpapp1"	3391
2016-09-27T18:37:50Z	"OVO"	"ovocollpapp1"	3240
2016-09-27T18:38:00Z	"OVO"	"ovocollpapp1"	3241
2016-09-27T18:38:10Z	"OVO"	"ovocollpapp1"	3146
2016-09-27T18:38:20Z	"OVO"	"ovocollpapp1"	3051
2016-09-27T18:38:30Z	"OVO"	"ovocollpapp1"	3051`

**Comment by phemmer** [comment]
This is almost certainly permissions. The user telegraf is running as does not have permissions to view file descriptors of all the processes you see as a user.

**Comment by egar** [comment]
what best practice for this case adding somw sudoer permision?

**Comment by sparrc** [comment]
permissions issue
