### ISSUE TITLE
Consul input plugin with InfluxDB output - multiple checks per service

### ISSUE THREAD

**Issue by bondido** [influxdata/telegraf#1825]
## Bug report

Consul input plugin with InfluxDB output doesn't report all data in case of collecting data from service with more than one check configured. Status from only one (randomly choosed per probe/timestamp) check is written to influxdb database.
Also, if any service is in maintenance mode (which is in fact temporarily configured 'critical' check on this service), this information is not always written to influxdb.
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf - version 1.0.0
InfluxDB - version 0.13.0
Consul - version 0.6.4
OS: Ubuntu 14.04.5 LTS
### Steps to reproduce:
1. Configure telegraf with Consul input and InfluxDB output plugin.
2. Monitor consul service with more than one check defined.
### Expected behavior:

Write consul service's all checks status in InfluxDB.
### Actual behavior:

Write status of only one check per service per probe/timestamp in InfluxDB.

**Comment by harnash** [comment]
@bondido thanks for report. I'll look into it and hopefully fix it this week.

**Comment by sparrc** [comment]
closed by #1994
