### ISSUE TITLE
Support -x option for procstat plugin

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#1828]
pgrep supports the "-x" argument which exactly matches the given pattern.

It helps better narrow down process names.

We should make this an option for Telegraf's procstat plugin.

**Comment by russorat** [comment]
seems like we should favor the ability to add arbitrary arguments to procstat as described in https://github.com/influxdata/telegraf/issues/2505 instead of a single command. What are your thoughts?

**Comment by danielnelson** [comment]
Let's close and do what is described in #2505.
