### ISSUE TITLE
is not defined in `*snmp.Snmp'

### ISSUE THREAD

**Issue by dragonxtek** [influxdata/telegraf#1837]
I'm trying to execute snmp plugin, but I can't. I tried with examples in https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp_legacy 
I used default configuration and I change the input configuration by the follow:
For the first input plugin:

> # Very Simple Example
[[inputs.snmp]]
  [[inputs.snmp.host]]
    address = "127.0.0.1:161"
    # SNMP community
    community = "public" # default public
    # SNMP version (1, 2 or 3)
    # Version 3 not supported yet
    version = 2 # default 2
    # Simple list of OIDs to get, in addition to "collect"
    get_oids = [".1.3.6.1.2.1.2.2.1.4.1"]

 I got this error correspondig to line: [[inputs.snmp.host]]

**field corresponding to `host' is not defined in `*snmp.Snmp'**

For the second example:

> # Simple example
[[inputs.snmp]]
  ## Use 'oids.txt' file to translate oids to names
  ## To generate 'oids.txt' you need to run:
  ##   snmptranslate -m all -Tz -On | sed -e 's/"//g' > /tmp/oids.txt
  ## Or if you have an other MIB folder with custom MIBs
  ##   snmptranslate -M /mycustommibfolder -Tz -On -m all | sed -e 's/"//g' > oids.txt
  snmptranslate_file = "/tmp/oids.txt"
  [[inputs.snmp.host]]
    address = "127.0.0.1:161"
    # SNMP community
    community = "public" # default public
    # SNMP version (1, 2 or 3)
    # Version 3 not supported yet
    version = 2 # default 2
    # Which get/bulk do you want to collect for this host
    collect = ["ifnumber", "interface_speed"]
  [[inputs.snmp.get]]
    name = "ifnumber"
    oid = ".1.3.6.1.2.1.2.1.0"
  [[inputs.snmp.get]]
    name = "interface_speed"
    oid = "ifSpeed"
    instance = "1"

 I got this error corresponding to line: snmptranslate_file = "/tmp/oids.txt"

**field corresponding to `snmptranslate_file' is not defined in `*snmp.Snmp'**

I'm running Telegraf v1.0.0-beta3-136-gca8e512 over Ubuntu 16.04. I tested snmp, and it works without problems. I created oids.txt without problems.

To reproduce just run telegraf -config telegraf.conf

I need to define the snmp attributes to a specific file? Where is it? How I can run the examples?

**Comment by sparrc** [comment]
please use the updated snmp plugin: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp

where did you find a link to the old plugin? it was deprecated in 1.0

**Comment by dragonxtek** [comment]
I found it googling
I'm trying lot examples because none works for me.
I created the issue #1833 with the updated snmp plugin. Please help me
Thanks
