### ISSUE TITLE
Telegraf logger should send to windows event log

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#1840]
self-explanatory, in the telegraf logger package: https://github.com/influxdata/telegraf/blob/master/logger/logger.go

We should probably have a windows Writer which will determine the log level of the incoming message, and then call the appropriate Error/Warning/Info function of the kardianos/service logger: https://godoc.org/github.com/kardianos/service#Logger

**Comment by sjwang90** [comment]
We would welcome any PRs or help looking into what work needs to be done to get this implemented.

**Comment by Jagularr** [comment]
Telegraf now has an eventlog setting that will log to windows event log, whether or not it is being ran as a service. Going to close this one, if there's a reason it should be re-opened or I've missed something, let me know.
