### ISSUE TITLE
Telegraf has docker container

### ISSUE THREAD

**Issue by viswa-devops947** [influxdata/telegraf#1841]
Hi,

I am running Telegraf has docker container in my environment.
currently it is getting disk usage of container not the Host.
How can i get the Host level metrics?

I mount /proc to /rootfs/proc for docker container.

in telegraf.conf

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.diskio]]

Thanks,
 Viswa.

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
