### ISSUE TITLE
Problem configutarion with kafka_consumer

### ISSUE THREAD

**Issue by perez1987** [influxdata/telegraf#1858]
Hello,

I am trying to configure an input in consumer telegraf Kafka. This is the configuration:

[[inputs.kafka_consumer]]
  topics = ["IPFeed"]
  zookeeper_peers = ["172.20.106.114:2181"]
  consumer_group = "telegraf_metrics_consumers"
  metric_buffer = 100000
  offset = "newest"

I'm getting this error:

telegraf_1       | 2016/10/06 11:29:22 Using config file: /etc/telegraf/telegraf.conf
telegraf_1       | 2016/10/06 11:29:22 Database creation failed: Get http://influxdb:8086/query?db=&q=CREATE+DATABASE+%22telegraf%22: dial tcp 172.18.0.2:8086: getsockopt: connection refused
telegraf_1       | 2016/10/06 11:29:22 Starting Telegraf (version 1.0.0-rc1)
telegraf_1       | 2016/10/06 11:29:22 Loaded outputs: influxdb
telegraf_1       | 2016/10/06 11:29:22 Loaded inputs: system elasticsearch zookeeper kafka_consumer cpu disk mem swap diskio
telegraf_1       | 2016/10/06 11:29:22 Tags enabled: host=7874e63bd379
telegraf_1       | 2016/10/06 11:29:22 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"7874e63bd379", Flush Interval:10s
telegraf_1       | 2016/10/06 11:29:22 Connected to 172.20.106.114:2181
telegraf_1       | 2016/10/06 11:29:22 Authenticated: id=96617993111470459, timeout=4000
telegraf_1       | 2016/10/06 11:29:23 Recv loop terminated: err=EOF
telegraf_1       | 2016/10/06 11:29:23 Send loop terminated: err=<nil>
telegraf_1       | 2016/10/06 11:29:23 Service for input kafka_consumer failed to start, exiting
telegraf_1       | kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

Can you help me? Thank you!

**Comment by sparrc** [comment]
@perez1987 what version of kafka are you using?

**Comment by perez1987** [comment]
@sparrc kafka_2.11-0.8.2.2

**Comment by sparrc** [comment]
I'm not really sure what the problem is then, because version 0.8 of kafka should be supported. Can you connect to the kafka broker otherwise? do you have any ideas on how to reproduce?

**Comment by perez1987** [comment]
Yes, I can connect to the server locally kafka and works well but when the input set in telegraf gives the error that indicated in my previous message.

Any idea?

**Comment by sparrc** [comment]
I didn't mean locally, I meant over your network, you're not using localhost in your config?

**Comment by perez1987** [comment]
No, kafka is on another server @sparrc

**Comment by sparrc** [comment]
sorry but I can't help you with debugging network errors, it looks like your influxdb instance is having troubles connecting as well

if you can submit more proof that the kafka consumer is working and connectable, or steps to reproduce, then I can dig into it.
