### ISSUE TITLE
Forwarding data from telegraf to different sources

### ISSUE THREAD

**Issue by jmat6** [influxdata/telegraf#1866]
Hi

I have a doubt. Is it possible for telegraf to send metrics to an elastic search cluster directly? If not, any other way of achieving this (either through logstash/fluentd)?

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
