### ISSUE TITLE
Input plugin "Postgresql" support multi pg-instance 

### ISSUE THREAD

**Issue by lazywhite** [influxdata/telegraf#1867]
if I have multi postgresql instance running on host, can telegraf support to configure each of them and send monitoring data ?

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
