### ISSUE TITLE
panic: division by zero in statsd allowed_pending_messages

### ISSUE THREAD

**Issue by arussellsaw** [influxdata/telegraf#1869]
## Bug report
panic on statsd input where allowed_pending_messages < 1

minimal PR, looking for quick wins for hacktoberfest 😸 

found via a tweet from a pal: https://twitter.com/rubynerd/status/775399499128856576

### Relevant telegraf.conf:

```
[[inputs.statsd]]
  allowed_pending_messages = 0
```

### System info:

telegraf 1.0, MacOS 10.10

### Steps to reproduce:

1. setup statsd input with 0 allowed_pending_messages
2. get input to start dropping messages

### Expected behavior:
no panics, either automatically adjusting value or quitting cleanly with error message

### Actual behavior:
a panic of division by zero

### Current behavior:
panic when dropping messages
### Desired behavior:
adjust pending messages to at least 1, warn the user

**Comment by sparrc** [comment]
TFW users tweet about issues rather than opening bug reports.....

it's already fixed in 1.0.1: https://github.com/influxdata/telegraf/pull/1785

**Comment by arussellsaw** [comment]
oh no! i thought i'd gotten here in time for hacktoberfest.

**Comment by sparrc** [comment]
sorry mate, appreciate the effort though :), now that I think about it I think it could still panic if a user actively set the value to 0....maybe there is still a bug?

the PR I linked to just fixed it so that not setting a value wouldn't default to 0

**Comment by arussellsaw** [comment]
i have a PR ready with a warn and adjust to 1 if that's the desired behaviour

**Comment by arussellsaw** [comment]
https://github.com/influxdata/telegraf/pull/1870
