### ISSUE TITLE
plugin statsd does not allow field

### ISSUE THREAD

**Issue by rolele** [influxdata/telegraf#1876]
## Bug report
telegraf statsd plugin behave strangely with fields of the line protocol
[key+tags] [fields] [timestamp]

### System info:
Telegraf - version 1.0.1

### Steps to reproduce:

I am using python (note the space between [key+tags] [fields])
````
import statsd
c = statsd.StatsClient('telegraf', 8125)
c.timing('example.timing7,service=payroll,region=us-west value=22,test=666', 1200)
````

### Expected behavior:
key = example.timing7
tags = service=payroll,region=us-west
fields = value=22,test=666

### Actual behavior:

key = example.timing7
tags = service=payroll,region=us-west,

````
> SELECT * FROM example_timing7
name: example_timing7
---------------------
time                    count   host            lower   mean    metric_type     service stddev  test    upper
2016-10-11T02:49:50Z    1       e26dcbf784ab    1200    1200    timing          payroll 0       666     1200

> SHOW FIELD KEYS FROM example_timing7
name: example_timing7
---------------------
fieldKey        fieldType
count           integer
lower           float
mean            float
stddev          float
upper           float


> SHOW TAG KEYS FROM example_timing7
name: example_timing7
---------------------
tagKey
host
metric_type
service
test

> SHOW series
example_timing7,host=e26dcbf784ab,metric_type=timing,service=payroll,test=666

> SHOW TAG VALUES FROM example_timing7 WITH KEY = test
name: example_timing7
---------------------
key     value
test    666

````
### Additional info:

it looks like "test" in considered as a tag and "value" is completely ignored
I tried with another label then "value" to see if the term "value" was the problem but it is not.

## Feature Request
I could see that the statsd plugin was announcing the field line protocol implementation since 3 Nov 2015, Do you have any plan to add it?

### Use case: [Why is this important (helps with prioritizing requests)]

Statsd is used by a lot of companies. I think the adoption of telegraf (and influxdb) depend on plugins such as statsd. I think telegraf is a huge step forward to promote the adoption of influxdb already (compared to graphite). But I feel frustrated by the way statsd plugin behave. Maybe I am doing something wrong.

**Comment by rolele** [comment]
It appears that the python client that I am using could format the udp request in a different way that I originally written.
I decided to go with simple curl command to telegraf to test the behaviors of each query.
It appears that I easily can add tags to influxdb using
````
echo "glork4,service=payroll,region=us-west:100|ms|@0.9" | nc -u -w0 192.168.99.100 8125

> select * from glork4
name: glork4
------------
time                    count   host            lower   mean    metric_type     region  service stddev  upper
1476159310000000000     1       cac7d1665671    100     100     timing          us-west payroll 0       100
````
but I can not see how I can send field to be indexed as well.

**Comment by sparrc** [comment]
the statsd protocol is separate from influx line-protocol. Only a single "field" is supported.

**Comment by rolele** [comment]
@sparrc 
What about this claim that was made last year: "COMING SOON: there will be a way to specify multiple fields."
Is there any plan to implement this?

**Comment by sparrc** [comment]
no, sorry, I will remove that
