### ISSUE TITLE
Add support for BTRFS filesystem

### ISSUE THREAD

**Issue by bricewge** [influxdata/telegraf#1881]
For the moment the `disk` plugin report wrong measurements on `btrfs` filesystems. The issue isn't apparent until your the partition become full, here is relevant article from the [btrfs's wiki](https://btrfs.wiki.kernel.org/index.php/FAQ#Understanding_free_space.2C_using_the_original_tools). To get the proper size we should use a method similar to `btrfs fi df` instead of the `df` way.

The quicker way would be to fix this in the `disk` plugin but having a separated plugin like `zfs` seems the way to go since `btrfs` have a lot more features than usual filesystems.

**Comment by clara-j** [comment]
I created this python script to capture some btrfs stats in telegraf.  I haven't done anything for df yet but should be possible.  Take a look at this and see if this is useful for you.  

https://github.com/clara-j/telegraf-btrfs-exec

**Comment by danielnelson** [comment]
Cool, one thing I wonder (doing 0 research) is if it is possible to get these stats through procfs.  This would perform quite a bit better than running the cli tools.  If not I suggest taking a look at the unbound input for a basic structure.

**Comment by clara-j** [comment]
I also have done 0 research.  Only started using telegraf 2 days ago and decided to build this in python last night to learn that too since hadn't used it before either.  I think some, if not all, stats may be available through /sys/fs/btrfs/ but haven't looked into it to make sense of it.

Thanks for the tip on unbound input.

**Comment by clara-j** [comment]
I have made an update to now support btrfs filesystem usage/df

Will make sure everything is working well and if so I will start looking into making a plugin.

**Comment by sspaink** [comment]
@clara-j I hope your doing well, its been a while but are you still interested in working on this plugin? Seeing as you wrote it in Python perhaps making it an external plugin would be a good idea.
