### ISSUE TITLE
Error in metric path order for Graphite Output in windows metric names

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#1884]
## Bug report

I've notice 2 extrange behaviour of the output Graphite Plugin

- A non expected Hostname appears in the Graphite metric path in the incorrect place
- A extra level Appears with Object Name ("Processor Information") in the Windows Performance Counters , when I've renamed as "win_cpu_ext"

### Relevant telegraf.conf:
```
[[outputs.graphite]]
  servers = ["server:2003"]
  prefix = "sales.pre.cluster23.servernameXX"
  template = "measurement.tags.field"
  timeout = 2

  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor Information"
    Instances = ["_Total"]
    Counters = ["% Processor Time" , "% User Time" , "% Privileged Time" , "% Interrupt Time" , "% DPC Time"]
    Measurement = "win_cpu_ext"
    WarnOnMissing = true
```

### System info:

Telegraf 1.0.1
Windows 2012 R2

### Steps to reproduce:

1. configure telegraf with the above sample conf.
2. restart
3.- review path in graphite

### Expected behavior:

I expect 

```
sales.pre.cluster23.servernameXX.win_cpu_ext._Total.Percent_DPC_Time
``` 
### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/5883405/19274997/7398d2e0-8fd2-11e6-8fb6-702a0710e3ea.png)

And I got
```
sales.pre.cluster23.servernameXX.win_cpu_ext.SERVERNAMEXX._Total.Processor_Information.Percent_DPC_Time
```

SERVERNAMEXX appears after measurement but I've configured  template = "measurement.tags.field" , without hostname
Also "Processor_Information" appears when I've renamed to win_cpu_ext

**Comment by sparrc** [comment]
Hi @toni-moreno, "host" is a tag and thus it will be added when you use the `tags` keyword.

"Processor_Information" is the object name, which is also a tag.

If you want to exclude those tags, you can use the `tagexclude` configuration option.

**Comment by toni-moreno** [comment]
Ok thank you for your support.

But IMHO I think this is a unexpected behavior, what sense has  define host in the graphite template (template = "host.measurement.tags.field") if host is already taken as a tag ?  With default configuration hostname will be sent twice in the graphite style metric path.

by the way , what is the exact tag name of the object name , to try filter it ?

Thank you very much again.

**Comment by sparrc** [comment]
I'm not sure the exact tag names, the best way for you to figure it out is to run with the --test flag or to output your metrics to a file.

**Comment by toni-moreno** [comment]
Hi @sparrc I've tested the tagexclude after review the tag name  and added tagexclude array in the input as described in (https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) but still receiving tags on the graphite path as you can see in the screenshot ( hostname under win_cpu measurement name, and objectname="Processor").

This is my configuration sample.

```
[[inputs.win_perf_counters]]
 PrintValid=true
 tagexclude = ["host","objectname"]

  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["_Total"]
    Counters = ["% Processor Time" , "% User Time"]
    Measurement = "win_cpu"
    WarnOnMissing = true
```

![image](https://cloud.githubusercontent.com/assets/5883405/19353602/2c839a5a-9164-11e6-903f-e51534a366d8.png)

any idea on how to fix ?

**Comment by sparrc** [comment]
@toni-moreno We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

in general, I would say that using more concrete line-protocol examples are more helpful for debugging, rather than screenshots....I'm not exactly sure what I'm looking at here
