### ISSUE TITLE
TCP port monitoring of telegraf

### ISSUE THREAD

**Issue by lazywhite** [influxdata/telegraf#1887]
can telegraf monitor the tcp port ie 6379 of localhost ， then send metric to influxdb ?

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
