### ISSUE TITLE
[statsd input plugin] documentation seems wrong about default value of delete_timings

### ISSUE THREAD

**Issue by hchargois** [influxdata/telegraf#1893]
The doc says:

```
## Delete timings & histograms every interval (default=true)
delete_timings = true
```

But with no `delete_timings` option set, I was having timings not deleted, and sent at every interval. With the option set to `true`, the desired behavior is happening. I guess that it's only the documentation that got the default value wrong.

BTW, I wonder why those options are `false` by default, since this is a very weird default... I never used etsy's statsd, but if I'm not mistaken, the "delete" way is the canonical way. It is even weirder to have values increment in influxdata's implementation, because with InfluxDB as the storage, it is so easy to sum values, get their mean or whatever, and this is easier if the raw, "interval deleted" values are stored, not the incremented ones.

**Comment by halt-hammerzeit** [comment]
I don't even understand what `delete_timings` means and what it does.
No clarification in the docs on that topic.
Does it delete the metrics? What's the point of gathering the metrics then if it's immediately deleted afterwards?

**Comment by sparrc** [comment]
delete_timings deletes it from Telegraf's internal cache, it obviously does no modification on the output plugins. It's important to understand the concept behind `statsd` and then I think you will understand this option.

**Comment by halt-hammerzeit** [comment]
@sparrc Ok, it deletes it from cache when the value has been sent. Then why wouldn't it delete it then? What would be the reason behind non-deleting everything?

**Comment by sparrc** [comment]
I guess if you wanted the accumulated metrics in InfluxDB since runtime. I think I would also agree that the defaults should be `delete... = true`
