### ISSUE TITLE
[Windows] win_perf_counters/graphite: No "Network Interface" counters are saved in Graphite

### ISSUE THREAD

**Issue by o7g8** [influxdata/telegraf#1897]
### Relevant telegraf.conf:

I show only sections which I have changed in the default config:

```
[[outputs.graphite]]
  servers = ["XX.XX.XX.XX:2003"]
  prefix = "telegraf"
  template = "host.measurement.tags.field" # this one is changed
  timeout = 2

  # this one is straight from example on https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters
  [[inputs.win_perf_counters.object]]
    # more counters for the Network Interface Object can be found at
    # https://msdn.microsoft.com/en-us/library/ms803962.aspx
    ObjectName = "Network Interface"
    Counters = ["Bytes Received/sec","Bytes Sent/sec","Packets Received/sec","Packets Sent/sec"]
    Instances = ["*"] # Use 6 x - to remove the Instance bit from the query.
    Measurement = "win_net"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).
```
### System info:

Telegraf 1.0.1
Windows 10
### Steps to reproduce:

Start telegraf with my config and look into Graphite browser.
### Expected behavior:

The Graphite tree

telegraf.MYHOST.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection should have metrics Bytes_Received_sec, Bytes_Sent_sec, etc .
### Actual behavior:

The tree doesn't have no metrics at all.
### Additional info:

I have also tried to explicitly specify Instance in [[inputs.win_perf_counters.object]] as:

Instances = ["Intel[R] 82579LM Gigabit Network Connection"]

with no positive outcome.

I can see the counters in PerfMon without any issues.

The rest of Windows counters from "Processor", "Memory", "PhysicalDisk", "LogicalDisk" work well with telegraf.

**Comment by sparrc** [comment]
please provide the output of `telegraf --test`, also try redirecting your output to a file using 

```
[[outputs.file]]
  files = ["/tmp/foo"]
  data_format = "graphite"
  prefix = "telegraf"
  template = "host.measurement.tags.field"
```

**Comment by o7g8** [comment]
Hi Cameron,

Thank you for the quick response!

Here just in case is my inputs- and outputs- part of Telegraf config:

[[outputs.graphite]]
  servers = ["X.X.X.X:2003"]
  prefix = "telegraf"
  template = "host.measurement.tags.field"
  timeout = 2
  
[[outputs.file]]
  files = ["./telegraf_dump.log", "stdout"]
  data_format = "graphite"
  prefix = "telegraf"
  template = "host.measurement.tags.field"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = ["Bytes Total/sec", "Output Queue Length"]
    Measurement = "bottleneck_network"

Here is an excerpt of console output:

PS C:\local\telegraf> .\telegraf.exe --config .\telegraf.netdebug.conf
2016/10/14 10:35:40 Starting Telegraf (version 1.0.1)
2016/10/14 10:35:40 Loaded outputs: graphite file
2016/10/14 10:35:40 Loaded inputs: win_perf_counters
2016/10/14 10:35:40 Tags enabled: host=XXX
2016/10/14 10:35:40 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"XXX", Flush Interval:10s
2016/10/14 10:36:00 Output [file] buffer fullness: 9 / 1000 metrics. Total gathered metrics: 9. Total dropped metrics: 0.
telegraf.XXX.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection.Network_Interface.Output_Queue_Length 0 1476434150
telegraf.XXX.bottleneck_network.isatap_{255721DD-EDFA-4463-819E-59A123132376}.Network_Interface.Output_Queue_Length 0 1476434150
2016/10/14 10:36:00 Output [graphite] buffer fullness: 9 / 1000 metrics. Total gathered metrics: 9. Total dropped metrics: 0.
telegraf.XXX.bottleneck_network.isatap_{BE67E233-36B1-4D43-990F-7BCB495EEB17}.Network_Interface.Output_Queue_Length 0 1476434150
telegraf.XXX.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection.Network_Interface.Bytes_Total_persec 1518.9594 1476434160
2016/10/14 10:36:00 Output [graphite] wrote batch of 9 metrics in 0
telegraf.XXX.bottleneck_network.isatap_{255721DD-EDFA-4463-819E-59A123132376}.Network_Interface.Bytes_Total_persec 0 1476434160
telegraf.XXX.bottleneck_network.isatap_{BE67E233-36B1-4D43-990F-7BCB495EEB17}.Network_Interface.Bytes_Total_persec 0 1476434160
telegraf.XXX.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection.Network_Interface.Output_Queue_Length 0 1476434160
telegraf.XXX.bottleneck_network.isatap_{255721DD-EDFA-4463-819E-59A123132376}.Network_Interface.Output_Queue_Length 0 1476434160
telegraf.XXX.bottleneck_network.isatap_{BE67E233-36B1-4D43-990F-7BCB495EEB17}.Network_Interface.Output_Queue_Length 0 1476434160
2016/10/14 10:36:00 Output [file] wrote batch of 9 metrics in 2.0003ms
2016/10/14 10:36:10 Output [file] buffer fullness: 6 / 1000 metrics. Total gathered metrics: 15. Total dropped metrics: 0.

I have also attached the dump file produced by outputs.file:

[telegraf_dump.zip](https://github.com/influxdata/telegraf/files/529034/telegraf_dump.zip)

Both console output and file contain valid data, but graphite remains empty as it's shown in the attached screenshot: 
![graphite_empty](https://cloud.githubusercontent.com/assets/1987306/19381385/9ee2daa6-91fb-11e6-876f-5b3ca3f7074d.png)

I wonder if it can have something to do with length of the metrics' names or "special" characters "{[]}-" in their names?

**Comment by sparrc** [comment]
what is this screenshot indicating? To me it looks like the metrics are there, but they are all 0

**Comment by o7g8** [comment]
The screenshot shows, that the highlighted nodes don't have leaf nodes with names `Network_Interface.Bytes_Total_persec` and `Network_Interface.Output_Queue_Length`.
So basically the metrics are not properly recorded in Graphite.

As you can see in the attached telegraf_dump.zip a following metric is not zero:

`telegraf.XXX.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection.Network_Interface.Bytes_Total_persec 1518.9594 1476434160`

It seems that Graphite instead has recorded only this part:

`telegraf.XXX.bottleneck_network.Intel[R]_82579LM_Gigabit_Network_Connection`

without any value.

**Comment by 7yl4r** [comment]
It is possible this not specific to this input, but instead is a more general problem with the graphite output from telegraf. I am seeing a very similar issue using the puppetagent input (on centos) to graphite. Telegraf produces data with no issue, but the data never shows up in graphite. Meanwhile I have other metrics which are working well within this same configuration.

Perhaps there is some poorly documented configuration @o7g8 and I have both missed in order to get data out into graphite?

> I wonder if it can have something to do with length of the metrics' names or "special" characters "{[]}-" in their names?

This was my first instinct on this as well. 

Here's my config info in case it might help:

```
[root@computer ~]# telegraf --input-filter puppetagent --test
2017/05/22 20:45:59 I! Using config file: /etc/telegraf/telegraf.conf
* Plugin: inputs.puppetagent, Collection 1
> puppetagent,location=/opt/puppetlabs/puppet/cache/state/last_run_summary.yaml,host=computer resources_total=60i,events_total=1i,events_success=1i,resources_failedtorestart=0i,resources_outofsync=1i,version_puppet="4.10.0",time_schedule=0.000978364,time_sshauthorizedkey=0,time_cron=0,resources_failed=0i,changes_total=1i,time_total=5.350637644,events_failure=0i,time_file=0.2748350829999999,time_filebucket=0.000185433,time_service=0.124076721,version_configstring="1495485952",time_lastrun=1495485957i,resources_scheduled=0i,resources_changed=1i,resources_restarted=1i,time_user=0,time_anchor=0,time_configretrieval=2.740914358,resources_skipped=0i,time_exec=0.011328651,time_package=0.123722093 1495485960000000000

[root@manglillo ~]# cat /etc/telegraf/telegraf.conf 
# Telegraf Configuration
[global_tags]

[agent]
  hostname = "computer"
  omit_hostname = false
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false

# OUTPUTS:
[[outputs.graphite]]
  prefix = ""
  servers = ["mygraphiteserver:2003"]
  template = "host.tags.measurement.field"
  timeout = 10

# INPUTS:
[[inputs.puppetagent]]
  location = "/opt/puppetlabs/puppet/cache/state/last_run_summary.yaml"
# others inputs omitted here...
```

**Comment by danielnelson** [comment]
@7yl4r You could try enabling 2 file outputs: one using graphite data_format and one with influx data_format.  If they differ it should make the remaining debugging much easier.

**Comment by 7yl4r** [comment]
thanks for the suggestion @danielnelson . I added both and was surprised to find them both empty. 

Then I found this permission denied error:

```
[root@computer ~]# systemctl status -l telegraf 
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-05-23 16:12:05 UTC; 1min 47s ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 8015 (telegraf)
   CGroup: /system.slice/telegraf.service
           └─8015 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d 

May 23 16:12:20 computer.domain.com telegraf[8015]: 2017-05-23T16:12:20Z E! ERROR in input [inputs.puppetagent]: stat /opt/puppetlabs/puppet/cache/state/last_run_summary.yaml: permission denied
```

My error may not be as closely related to this issue as I originally thought. 

I'll take conversation regarding my issue elsewhere, but with regard to this issue: is it possible @o7g8 's console run works fine but the service is failing in a similar way to my experience?

**Comment by timbarker** [comment]
I fell over this issue with 1.4.5 but found upgrading to version 1.5.0 RC2 solved the issue. It looks like graphite metric key names are now having invalid characters correctly replaced with an _ character. See #3473.

Great Work.

**Comment by danielnelson** [comment]
Good to hear, I'm going to close this issue as fixed.
