### ISSUE TITLE
input hddtemp: Strange data? Why not just use value?

### ISSUE THREAD

**Issue by jonaz** [influxdata/telegraf#1904]
### Relevant telegraf.conf:

```
[[inputs.hddtemp]]
address = "127.0.0.1:7634"
devices = ["*"]
```
### System info:

Telegraf - version 1.0.1
ubuntu 14.04
### Steps to reproduce:
1. Just run hddtemp input
### Expected behavior:

The temperature should be in the value field and not a new field for each disk?
### Actual behavior:

![2016-10-16-110545_1229x455_scrot](https://cloud.githubusercontent.com/assets/1146389/19416438/8a1d425a-9390-11e6-9fe4-8e8d5fcc0d8a.png)

**Comment by jonaz** [comment]
cc @MendelGusmao

**Comment by MendelGusmao** [comment]
Sorry for not noticing this before. It was my first PR. hddtemp's plugin implementation was based off of sensors plugin.

I agree with the changes proposed by @jonaz and am willing to accept a PR at MendelGusmao/go-hddtemp.
