### ISSUE TITLE
support multiple [outputs.influxdb] or multiple database names in one [outputs.influxdb]

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#1918]
### Proposal:
support multiple [outputs.influxdb] or multiple databases in [outputs.influxdb] so that different input can write data to different database, for example, inputs.statsd can write data into statsd_db and inputs.docker can write data into database docker_db

### Current behavior:
no way to do it unless you run multiple telegraf instances

### Desired behavior:
one telegraf instance can inject data from different inputs into different databases in influxdb

### Use case: 
inputs.statsd supports template so user can name the measurement, if the measurement has the same name as other one created by different input then this measurement will be messy

**Comment by phemmer** [comment]
See #1778, which has a few suggestions of how you can accomplish this.

**Comment by sparrc** [comment]
@wei-hai if you put two brackets around it, multiple `[[outputs.influxdb]]` is already supported. see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#output-configuration-examples
