### ISSUE TITLE
Exec error: "no such file or directory for command" when no scripts match glob pattern

### ISSUE THREAD

**Issue by tobgu** [influxdata/telegraf#1920]
### Relevant telegraf.conf:

[[inputs.exec]]
  commands = ["/metrics/*_metrics.sh"]
  data_format = "influx"
### System info:

Telegraf - version 1.0.1, CoreOS stable (1068.8.0)
### Steps to reproduce:
1. Add definition to telegraf.conf as above
2. Don't put any files matching the pattern in /bin
### Expected behavior:

Nothing happens since there are no files matching the pattern.
### Actual behavior:

Telegraf logs an error because it is fallbacks to executing the provided command hoping that it is present on the command line.

`ERROR in input [exec]: Errors encountered: [exec: fork/exec /metrics/*_metrics.sh: no such file or directory for command '/metrics/*_metrics.sh']
`
### Additional info:

I'm setting up multiple hosts with different roles. Some will have metrics scripts while others won't. I would like to be able to use the same telegraf config on all of the hosts without errors being reported.

**Comment by sparrc** [comment]
I'd actually say this is intended behavior. The counterpoint is that a user who misspells or mistypes their glob pattern or filename _should_ see an error message come up.

You are basically giving telegraf an invalid config file and then asking us to ignore it, which isn't a good behavior IMHO.
