### ISSUE TITLE
ElasticSearch Cluster Stats Support 

### ISSUE THREAD

**Issue by ervansetiawan** [influxdata/telegraf#1921]
The cluster stats obtained by the elasticsearch input plugin is currently only getting metrics from the /_cluster/health endpoint.

We need the ability to also consume metrics from the /_cluster/stats endpoint.

https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1979

**Comment by animageofmine** [comment]
@sparrc I believe this milestone 1.2.0 is already released. Let me know if that's not the case.

**Comment by sparrc** [comment]
1.2 has not been released yet

**Comment by animageofmine** [comment]
so, cluster_stats are not available yet? 
What's ETA for 1.2?

**Comment by sparrc** [comment]
only if you build from source.

We don't have a public roadmap at the moment, but you'll see some release candidate builds available very soon :)

**Comment by animageofmine** [comment]
Thank you! Hopefully, its out in a week approximately. Would be very useful!
