### ISSUE TITLE
Haproxy basic auth documentation

### ISSUE THREAD

**Issue by alexbowers** [influxdata/telegraf#1922]
It is not currently documented how to access a basic auth protected stats page for haproxy. 

The test appears tocover this:

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/haproxy/haproxy_test.go#L61, so perhaps it should be documetned

**Comment by sparrc** [comment]
sure, if you could write that documentation then please submit a PR

**Comment by MhdAli** [comment]
I just PR regarding this #2258

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/2258
