### ISSUE TITLE
`-input-filter` option doesn't work

### ISSUE THREAD

**Issue by halt-hammerzeit** [influxdata/telegraf#1925]
The document says
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md

> To generate a file with specific inputs and outputs, you can use the -input-filter and -output-filter flags:
```
telegraf config -input-filter cpu:mem:net:swap -output-filter influxdb:kafka
```

But when I generate the config it contains all input filters so `-input-filter` option doesn't work.

**Comment by sparrc** [comment]
workaround is to use the `telegraf --sample-config` rather than `telegraf config`

**Comment by sparrc** [comment]
the problem here is actually the documentation, "arguments" need to come after flags in Go, so the command should look like this:

```
telegraf -input-filter cpu:mem:net:swap -output-filter influxdb:kafka config
```
