### ISSUE TITLE
[httpjson input plugin] Missing response_timeout field

### ISSUE THREAD

**Issue by wilk** [influxdata/telegraf#1928]
## Bug report

It seems the `response_timeout` property of the httpjson input plugin is missing.
What's wrong with it?

### Relevant telegraf.conf:

```
[[inputs.httpjson]]
response_timeout = "5s"
```

### System info:

Telegraf version: 1.0.1
OS: Mac OS X 10.11.6 El Capitan

### Unexpected Behaviour

```bash
Error parsing telegraf.conf, line 133: field corresponding to 'response_timeout' is not defined in '*httpjson.HttpJson'
```

### How to reproduce the bug

Launch Telegram with the config file listed below:

```bash
$ telegraf -config telegraf.conf
```

### Gist

https://gist.github.com/wilk/7a33afed9578bda4e66133892e54fc46

**Comment by sparrc** [comment]
that field was added for 1.1, and is not available yet

if you generate the config using `telegraf --sample-config` or `telegraf --usage httpjson` you will see that that field is not available.
