### ISSUE TITLE
Kuberentes plugin leaking connections

### ISSUE THREAD

**Issue by jchauncey** [influxdata/telegraf#1933]
## Bug report
The kubernetes plugin is leaking connections which is also leaking memory. 

[Include Telegraf version, operating system name, and other relevant details]
Version: master telegraf 
OS: ubuntu docker image

### Steps to reproduce:
Enable kubernetes plugin and wait

### Expected behavior:
Should close connections responsibly 

### Actual behavior:
Never closes opened connections

**Comment by jchauncey** [comment]
Im actively working on this issue now

**Comment by jchauncey** [comment]
Looks like the problem might be with keep alives. I foolishly set that to true and it seems like it works pretty well.  Soon as I am done testing this fix I'll submit a PR.

**Comment by sparrc** [comment]
I see what you mean, it appears there are quite a lot of custom defaults in the http Transport, do you think you could trim this:

```go
var rt http.RoundTripper = &http.Transport{
		Dial: (&net.Dialer{
			Timeout:   5 * time.Second,
			KeepAlive: 30 * time.Second,
		}).Dial,
		TLSHandshakeTimeout:   5 * time.Second,
		TLSClientConfig:       tlsCfg,
		ResponseHeaderTimeout: time.Duration(3 * time.Second),
		DisableKeepAlives:     false,
	}
```

to just this?:

```go
var rt http.RoundTripper = &http.Transport{
		TLSHandshakeTimeout:   5 * time.Second,
		TLSClientConfig:       tlsCfg,
		ResponseHeaderTimeout: 3 * time.Second,
}
```

**Comment by jchauncey** [comment]
Alright it was definitely the `DisableKeepAlives` you have to explicitly set that to true otherwise it will leak connections like crazy.

**Comment by sparrc** [comment]
@jchauncey Let's try to see if there is another solution, I'd prefer not to disable keep-alives as this is something typically only done in very resource-constrained environments.

Go says this about the round-tripper:

```
By default, Transport caches connections for future re-use. This may leave many open connections when accessing many hosts. This behavior can be managed using Transport's CloseIdleConnections method and the MaxIdleConnsPerHost and DisableKeepAlives fields.

Transports should be reused instead of created as needed. Transports are safe for concurrent use by multiple goroutines.
```

So we should probably only instantiate the round-tripper once, and reuse it on subsequent calls to Gather.

You should also try removing the custom Dialer, unless that has a specific purpose.

**Comment by jchauncey** [comment]
Yeah Im working on that now. We should change the other plugins that use the same pattern.

**Comment by jchauncey** [comment]
Yup will do.
