### ISSUE TITLE
telegraf on windows send data to graphite 

### ISSUE THREAD

**Issue by sorin2343** [influxdata/telegraf#1935]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. in conf
[[inputs.win_perf_counters]]

[[inputs.win_perf_counters.object]]
  ObjectName = "System"
  Counters = ["Context Switches/sec","System Calls/sec"]
  Instances = ["------"]
  Measurement = "win_system"
  #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

 and I got a error and metrics are rejected
"
2016/10/24 18:27:20 Input [win_perf_counters] gathered metrics, (10s interval) in 2.9799ms
2016/10/24 18:27:20 Output [graphite] buffer fullness: 4 / 1000 metrics. Total gathered metrics: 34. Total dropped metrics: 0.
2016/10/24 18:27:20 Output [graphite] wrote batch of 2 metrics in 447.3µs
2016/10/24 18:27:20 ERROR: write tcp 192.168.15.124:61545->192.168.1.195:2003: wsasend: An established connection was aborted by the software in your host machine.
2016/10/24 18:27:20 Error writing to output [graphite]: Could not write to any Graphite server in cluster
"

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
system info? what version of telegraf? are you able to send metrics from other plugins? can you provide any information that shows that your graphite server is connectable and writeable?

also, can you please clean up the issue templating that you're not using?

**Comment by sparrc** [comment]
closed for lack of info

**Comment by sorin2343** [comment]
Can you give me a config that should work ?
I tryied to send by telnet and It’s worked .

**Comment by sorin2343** [comment]
192.168.1.1             Telegraf  sender
192.168.1.195   graphite relay



From: Sorin Ispas | eMAG, Infrastructure
Sent: Monday, October 24, 2016 6:59 PM
To: 'influxdata/telegraf' <reply@reply.github.com>; influxdata/telegraf <telegraf@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [influxdata/telegraf] telegraf on windows send data to graphite (#1935)

Can you give me a config that should work ?
I tryied to send by telnet and It’s worked .

**Comment by sorin2343** [comment]
you requests :
sysinfo 
[systeminfo.txt](https://github.com/influxdata/telegraf/files/553183/systeminfo.txt)
telegraf is 1.0.1 from telegraf-1.0.1_windows_amd64.zip
the test I made is echo "Windows.QLIKVIEW5-2.HarddiskVolume1.LogicalDisk.Disk.Percent_Idle_Time 100 1477320460" > telnet 192.168.1.195 2003
