### ISSUE TITLE
Ceph input plugin config parse errors

### ISSUE THREAD

**Issue by moloney** [influxdata/telegraf#1938]
## Bug report

Trying to use documented config options for the Ceph input plugin results in parsing errors. In particular the following config options appear to cause parse errors:

 * gather_cluster_stats
 * ceph_user
 * gather_admin_socket_stats

In the logs I see errors like:

Error parsing /etc/telegraf/telegraf.conf, line 539: field corresponding to `gather_cluster_stats' is not defined in `*ceph.Ceph'

If I don't use the above config options then I can get the ceph plugin to work.

### Relevant telegraf.conf:

    [[inputs.ceph]]
      ## Reduced collection interval since it can take a while under load
      interval = '1m'
    
      ## All configuration values are optional, defaults are shown below
      ## location of ceph binary
      ceph_binary = "/usr/bin/ceph"
    
      ## directory in which to look for socket files
      socket_dir = "/var/run/ceph"
    
      ## prefix of MON and OSD socket files, used to determine socket type
      mon_prefix = "ceph-mon"
      osd_prefix = "ceph-osd"
    
      ## Whether to gather statistics via the admin socket
      gather_admin_socket_stats = true
    
      ## suffix used to identify socket files
      socket_suffix = "asok"
    
      ## The montior nodes also gather global cluster stats
      gather_cluster_stats = true
    
      ## Consult the ceph documentation for more detail on keyring generation.
      ceph_user = "client.admin"
    
      ## Ceph configuration to use to locate the cluster
      ceph_config = "/etc/ceph/ceph.conf"

### System info:

OS: Ubuntu 16.04
Telegraf: 1.0.1-1

### Steps to reproduce:

1. Use the above config for the ceph plugin
2. Try to start the telegraf service

### Expected behavior:

Telegraf service start successfully.

### Actual behavior:

Telegraf exits with a parsing error

**Comment by sparrc** [comment]
these options will not be available until 1.1, please use telegraf --usage ceph to see what's available in your version

**Comment by moloney** [comment]
Thanks for the clarification. Those options were included (although commented out) in the default config file included in the .deb so I was a bit confused.

**Comment by sparrc** [comment]
If you're using the official 1.0.1 .deb then those config options are definitely not there.

**Comment by RajibHossen** [comment]
`# Collects performance metrics from the MON and OSD nodes in a Ceph storage cluster.
[[inputs.ceph]]
  ## All configuration values are optional, defaults are shown below

  ## location of ceph binary
  ceph_binary = "/usr/bin/ceph"

  ## directory in which to look for socket files
  socket_dir = "/var/run/ceph"

  ## prefix of MON and OSD socket files, used to determine socket type
  mon_prefix = "ceph-mon"
  osd_prefix = "ceph-osd"

  ## suffix used to identify socket files
  socket_suffix = "asok"
`
so to use only ceph , I execute this command

> telegraf -sample-config -input-filter ceph -output-filter influxdb > influx-ceph.conf
> telegraf -config influx-ceph.conf


But, telegraf isn't gathering any metrics at all

> 016/10/30 02:21:16 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"client.ceph.com", Flush Interval:10s 
> 2016/10/30 02:21:30 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
> 2016/10/30 02:21:40 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.

I assume these options in configuration are not enough to get ceph cluster status. Any solution is highly appreciable
Thanks in advance.
