### ISSUE TITLE
inputs.postgresql doesn't collect metric from all databases by default

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#1939]
## Bug report
inputs.postgresql doesn't collect metric from all databases if not given database name.
### Relevant telegraf.conf:
[[inputs.postgresql]]
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf v1.0.1
### Steps to reproduce:

1. set address = "postgres://telegraf:password@localhost?sslmode=disable" or address = "host=localhost user=telegraf password=password sslmode=disable"
2. start telegraf

### Expected behavior:
Telegraf collects metric from all databases
### Actual behavior:
The plugin tries to connect to database "telegraf" instead of all existing databases.
### Additional info:
Error message in the log file:
```
2016/10/24 16:09:50 ERROR in input [postgresql]: pq: database "telegraf" does not exist
```
It looks like the plugin is trying to connect to database=USERNAME in the connection parameters instead of all existing databases.

[Include gist of relevant config, logs, etc.]
```
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics from one or many postgresql servers
[[inputs.postgresql]]
  ## specify address via a url matching:
  ##   postgres://[pqgotest[:password]]@localhost[/dbname]\
  ##       ?sslmode=[disable|verify-ca|verify-full]
  ## or a simple string:
  ##   host=localhost user=pqotest password=... sslmode=... dbname=app_production
  ##
  ## All connection parameters are optional.
  ##
  ## Without the dbname parameter, the driver will default to a database
  ## with the same name as the user. This dbname is just for instantiating a
  ## connection with the server and doesn't restrict the databases we are trying
  ## to grab metrics for.
  ##
  ##address = "host=localhost user=postgres sslmode=disable"
  
  ## address = "postgres://telegraf@localhost?sslmode=disable"
  address = "host=localhost user=telegraf sslmode=disable"

  ## A list of databases to pull metrics about. If not specified, metrics for all
  ## databases are gathered.
  # databases = ["app_production", "testing"]
```

**Comment by sparrc** [comment]
can you explain why you can't specify your database name(s)?

**Comment by wei-hai** [comment]
Is dbname required? I thought it was optional.

**Comment by beckettsean** [comment]
@wei-hai, 

@sparrc is not saying you must specify the databases to be sampled. Please see this section of the config comments you linked above:

```
 ## Without the dbname parameter, the driver will default to a database
  ## with the same name as the user. This dbname is just for instantiating a
  ## connection with the server and doesn't restrict the databases we are trying
  ## to grab metrics for.
```

As you mention, "It looks like the plugin is trying to connect to database=USERNAME in the connection parameters instead of all existing databases," and that is what is happening. Since `telegraf` isn't a valid database the connection fails.

I believe you need to configure an actual DB in the connection string for PostgreSQL.

**Comment by wei-hai** [comment]
got it, it might be better to set the default database to "postgres" instead of username.
