### ISSUE TITLE
[feature request] Graphite parser enhancement

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/telegraf#1940]
### Proposal:

Add support for the following graphite parsing patterns:

```
templates = [ 
    ".measurement.field.[tag_key]*',
    "measurement.[tag_key]*.field.field"
]
```
### Current behavior:

Currently the graphite parser does not allow a wildcard match for tags for the end of a graphite string:

```
# METRIC: ent-prod-5.cpu.cpu1.usage.user.127.0.0.1 10 TS
# Current Template to parse: 
[ "*.cpu.* hostname.measurement.cpu.field.field.ip.ip.ip.ip" ]
```

This makes it impossible to match a tag with an indeterminate number of sections at the end of a string. It is also not currently possible to match an indeterminate number of interior sections:

```
# METRIC cpu.ent.prod.5.ck.all.cpu.usage.user 10 TS
# Current template to parse:
[ "cpu.* measurement.host.host.host.host.host..field*" ]
```
### Desired behavior:

Matching the above examples with the proposed patterns:

```
# METRIC: ent-prod-5.cpu.cpu1.usage.user.127.0.0.1 10 TS
# Proposed Template to parse: 
[ "*.cpu.* hostname.measurement.cpu.field.field.ip*" ]
# METRIC cpu.ent.prod.5.ck.all.cpu.usage.user 10 TS
# Proposed template to parse:
[ "cpu.* measurement.host*..field.field" ]
```
### Use case:

In many legacy environments there are graphite sections that have indeterminate numbers of elements. These sections are not really possible to parse with the current system. There are 2 asks in the feature request:
1. Enable wildcard match of tag at the end of a string. This is shown in the first example above. 
2. Enable wildcard match of tag, field, or measurement in the middle of the string.

@wei-hai

**Comment by sparrc** [comment]
I'm not sure I fully understand what the ask is here. Can you explain more clearly for each case:

1. what is the graphite input?
2. what is the desired template that would match it?
3. what is the desired resulting influx line-protocol metric?

@wei-hai @codylewandowski

**Comment by wei-hai** [comment]
@jackzampolin

**Comment by jackzampolin** [comment]
@wei-hai do you have some example?

**Comment by sparrc** [comment]
Actually I understand now, sorry I must have been reading this without coffee and didn't see the "Use case" section at the end.

That being said, since this is two separate feature requests could you open two separate issues?
