### ISSUE TITLE
[feature request] Parallelize graphite parsing

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/telegraf#1941]
### Proposal:

Parallelize graphite parsing
### Current behavior:

Parsing is currently a serial operation.
### Desired behavior:

Spin off a configurable number of goroutines to parallelize parsing.
### Use case:

Prevents more than one CPU from being used on dedicated statsd servers. This forces users to run multiple telegraf instances to take full advantage of their compute. Making the option configurable allows users to constrain telegraf resources if this is undesirable.

**Comment by danielnelson** [comment]
I'm not against this if someone wants to implement it, however I think it is unlikely to be much faster due to the additional work that needs done.
