### ISSUE TITLE
error reading from socket '/var/run/ceph/ceph-osd.112.asok': error running ceph dump: exit status 22 - Telegraf

### ISSUE THREAD

**Issue by bennco1** [influxdata/telegraf#1960]
Hello can anyone advise how exactly to have telegraf run as root user or correct the problem reported? I am able to pull cpu, mem etc but nothing related to ceph.

Telegraf - version 1.0.1

2016/10/26 16:41:40 error reading from socket '/var/run/ceph/ceph-osd.112.asok': error running ceph dump: exit status 22
2016/10/26 16:41:40 error reading from socket '/var/run/ceph/ceph-osd.126.asok': error running ceph dump: exit status 22
2016/10/26 16:41:40 error reading from socket '/var/run/ceph/ceph-osd.141.asok': error running ceph dump: exit status 22
2016/10/26 16:41:40 error reading from socket '/var/run/ceph/ceph-osd.153.asok': error running ceph dump: exit status 22
2016/10/26 16:41:40 error reading from socket '/var/run/ceph/ceph-osd.211.asok': error running ceph dump: exit status 22

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
