### ISSUE TITLE
[Feature Request] Add logparser support for Lighttpd

### ISSUE THREAD

**Issue by SomKen** [influxdata/telegraf#1969]
### Use case: Lighttpd is a commonly used webserver and is server used for PFSense.

https://redmine.lighttpd.net/projects/1/wiki/Docs_ModAccesslog

**Comment by sparrc** [comment]
Could you give more details? what do you lighttpd logs look like? the link provided shows a spec for formatting logs but it would be more helpful if you could provide examples of what the default log lines look like, and maybe some common variations if they exist.

for dev reference, see https://github.com/garethr/logstash-patterns/pull/3/files

**Comment by SomKen** [comment]
http://pastebin.com/raw/eFcQu4Ha

**Comment by sparrc** [comment]
@SomKen isn't that the same as the "combined log format"?

**Comment by sparrc** [comment]
closing because this is the same format as the "COMBINED_LOG_FORMAT"
