### ISSUE TITLE
[feature request] buffer data when output (influxdb ..) not available

### ISSUE THREAD

**Issue by albundy83** [influxdata/telegraf#1976]
## Feature Request
Do you think it's possible to bufferize data until output is back again ?
### Proposal:
Write in log and replay content
### Current behavior:
Data are lost
### Desired behavior:
Don't loose data :)
### Use case:
For a production platform, it's very important that each component is able to handle issues.

**Comment by widdma** [comment]
The current behavior, as described in the default config, is:
```
[agent]
...
  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  metric_buffer_limit = 10000
```

Are you suggesting a different behavior? Perhaps storing the buffer on disk?

**Comment by albundy83** [comment]
No, sorry, I just did not read correctly the configuration parameters. 
That's perfect.
