### ISSUE TITLE
logparser grok should support add_field, add_tag config options

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#1984]
these should be supported in a way similar to logstash: https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#_synopsis_128

use-case from Google mailing list:

> eg: If I match a /var/log/messages line logged by the OOM killer I want logparser to output a line with the event timestamp and my own static string tag "event=oom".

**Comment by danielnelson** [comment]
I'm going to close in favor of #2564 since the bulk of the discussion is over there.
