### ISSUE TITLE
Telegraf seemingly undistributable due to license-less dependency

### ISSUE THREAD

**Issue by guillemj** [influxdata/telegraf#1985]
## Bug report

The current telegraf from git master (commit d6135f8c760cd0ad334b310a14fd8546b401acff) looks undistributable, as it depends on github.com/influxdata/config which has no license. This might not be a problem for Influxdata as the original copyright holder, but is should be for any third-party, including any attempt to package this for a distribution. Of course IANAL, etc.

The relevant bug in influxdata/config is https://github.com/influxdata/config/issues/6.

There is also a problem with the influxdata/toml fork with commits modifying generated files instead of their sources in https://github.com/influxdata/config/issues/7.

**Comment by sparrc** [comment]
I don't fully understand the problem with the latter, what do we need to do there to fix it exactly?

**Comment by guillemj** [comment]
The source for parse.peg.go is parse.peg, generated with https://github.com/pointlander/peg. Because there have been commits changing parse.peg.go but not the source, when building from source or when modifying the source those changes would get lost.

The naoina/toml didn't even build against latest pointlander/peg, but I've submitted a couple of issues/pulls for that:

  https://github.com/naoina/toml/issues/29
  https://github.com/naoina/toml/pull/31

Which is being used in Debian in the naoina/toml packages already. Hope this clarifies.

**Comment by sparrc** [comment]
thanks for the details @guillemj, I've noticed some activity on the latter two, are those solved? One problem may be that naoina hasn't merged any PRs in over a year and appears to have abandoned the project.

Is this related to debian packaging? Would it help if the dependencies were vendored in-repo?

**Comment by guillemj** [comment]
Hmm, vendoring would certainly make things even more difficult, as those would need to be unvendored before packaging, and it would still not solve the underlying bugs anyway. The influxdata/toml package is already in Debian (https://tracker.debian.org/pkg/golang-github-influxdata-toml).

These two bugs have some pull requests that somewhat fix the issues, the important one is already fixed in Debian's naoina/toml packages.

So, if naoina/toml is practically unmaintained, keeping the fork looks fine, although perhaps a better option to consider might be to switch to https://github.com/BurntSushi/toml, because it seemed to me that naoina/toml was just pulled for backwards compat, but maybe I didn't read thoroughly.

Otherwise if keeping the fork, ideally those other issues would get fixed in here. The main problem is that changing generated files is very confusing for people that might do drive-by patching/fixing, and might mean that those changes might get lost in the future even in the fork if someone does not happen to check if they have been modified. If going this way I can submit the pull requests for the fork if you want?

**Comment by sparrc** [comment]
We'll have to keep the fork for now, yes please send PRs to the fork for the time being.

**Comment by sparrc** [comment]
I believe this is now fixed as we no longer depend on github.com/influxdata/config

additionally, from what I understand the latest debian version of the toml package has this fixed.

Please advise if this is not the case...
