### ISSUE TITLE
Docker input plugin imagename/version split does not work if private registry with port in url is used

### ISSUE THREAD

**Issue by erSitzt** [influxdata/telegraf#1987]
## Bug report

The docker input plugin splits the image name and image version at the colon.

python:3

results in

container_image: python
container_version: 3

but the image name may contain a private registry url which contains a port, also with a colon for separation.

eg.

registry.domain.com:5000/monitoring/cadvisor:internal.0.23

This results in

container_image: registry.domain.com:
container_version: 5000/monitoring/cadvisor

### System info:

Telegraf Docker image telegraf:alpine

**Comment by alex-sherwin** [comment]
+1

**Comment by sachagear** [comment]
+1

**Comment by deric** [comment]
+1

**Comment by sparrc** [comment]
this is already slated for a release and there is a PR up to fix it, there's no need to "+1", thanks
