### ISSUE TITLE
Add "Questions" global status variable to mysql input plugin

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#1988]
## Enhancement Request

Currently the *Questions* global status variable is not gathered for MySQL.  This is different from the *Queries* variable especially for applications that make heavy use of prepared statements and stored procedures.  *Questions* delivers a more accurate measure of how the system is being used 
<http://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Questions>

Looking at the code this is a trivial enhancement to implement, and I would be happy to help if needed.

**Comment by sparrc** [comment]
sure, PRs appreciated

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/2004
