### ISSUE TITLE
Sample config should have all non-system plugins disabled by default

### ISSUE THREAD

**Issue by pauldix** [influxdata/telegraf#199]
For the generated sample config all plugins that aren't the system plugin should be disabled. It's painful for a new user setting up Telegraf initially to have to go through and disable all the plugins since they're most likely only going to have one or two they want to use.

**Comment by sparrc** [comment]
that's a good idea, I already did this for the .deb and .rpm package default config for the same reason

**Comment by sparrc** [comment]
@pauldix I came up with a different solution while I was working on a filtering change.

See PR #217, this will allow users to specify the plugins and outputs they want when they generate the config file, like:

`telegraf -sample-config -filter cpu:mem:swap -outputfilter influxdb`

Also, when installing from the deb/rpm package, only influxdb and a few of the system plugins are enabled by default

**Comment by sparrc** [comment]
closing this as fixed by the `-filter` and `-outputfilter` flags, these should now be used to create config files.

**Comment by pauldix** [comment]
Will it still output all the other plugin configs commented out or disabled? It's helpful for users to have that in there rather than having to know all of the plugin names that exist so that they can put them in the command line when generating the file.

**Comment by sparrc** [comment]
It won't, but maybe I could make an option to list them more succinctly? The reason I say that is because the default sample config is getting pretty huge, and is only going to get bigger

**Comment by pauldix** [comment]
That's fine if it's huge, it's just a text file.

Check the config for Redis: http://download.redis.io/redis-stable/redis.conf

That one is big too, but I think it's the gold standard for example config files. Tons of comments so that the user can just look at the config file without having to jump to documentation to figure out what to do.

Better to have everything there, rather than forcing the user to go to the documentation or generate another temp config to see how things are supposed to work.

**Comment by sparrc** [comment]
okay, re-opening

**Comment by rajanathan100** [comment]
procstat_lookup,dc=oh,deployment=dev,environment=assist-dev,exe=ConnectionProctorService,host=wfbmoh-cp,pid_finder=native,region=us-east-2,result=success,vpc=wfbmoh pid_count=0i,result_code=0i,running=0i 1641564534000000000
