### ISSUE TITLE
"mem" measurement should report more metrics

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1990]
### Proposal:
On Linux `/proc/meminfo` provides a ton of available metrics about host memory usage. Very few of these metrics are made available through the "mem" measurement.

Either the "mem" measurement should be extended to include these additional metrics, or a new measurement should be provided.

### Current behavior:
Only the following metrics are made available:
* active
* available
* buffered
* cached
* free
* inactive
* total
* used

### Desired behavior:
The following metrics from `/proc/meminfo` should be available (all of them):
* MemTotal
* MemFree
* MemAvailable
* Buffers
* Cached
* SwapCached
* Active
* Inactive
* Active(anon)
* Inactive(anon)
* Active(file)
* Inactive(file)
* Unevictable
* Mlocked
* SwapTotal
* SwapFree
* Dirty
* Writeback
* AnonPages
* Mapped
* Shmem
* Slab
* SReclaimable
* SUnreclaim
* KernelStack
* PageTables
* NFS_Unstable
* Bounce
* WritebackTmp
* CommitLimit
* Committed_AS
* VmallocTotal
* VmallocUsed
* VmallocChunk
* HardwareCorrupted
* AnonHugePages
* HugePages_Total
* HugePages_Free
* HugePages_Rsvd
* HugePages_Surp
* Hugepagesize
* DirectMap4k
* DirectMap2M

These measurements should not be hard coded. We should simply read `/proc/meminfo` and report everything we find. For the ones with parenthesis in the name, we can probably just drop the closing parenthesis (`)`), and replace `(` with `_`. So `Active(anon)` becomes `Active_anon`.

### Use case: [Why is this important (helps with prioritizing requests)]
Memory management on linux is not simple. The currently available metrics do not provide enough information for advanced monitoring, profiling, & debugging.

**Comment by sparrc** [comment]
might be worth writing a `meminfo` plugin only for linux that would read /proc/meminfo and create metrics for whatever lines it finds there (since they do seem to change fairly often between different kernel versions)

I can't decide though if that should be a separate plugin or a configurable extension of the regular `mem` plugin.

**Comment by sparrc** [comment]
might also close https://github.com/influxdata/telegraf/issues/1176

**Comment by sparrc** [comment]
I think it's probably better to have an option on the `mem` plugin, and just indicate in the doc that it only works on linux.

**Comment by phemmer** [comment]
on the mem plugin feels weird I think. If we just dump all the fields we find, the current fields become redundant. You could add `fielddrop`s for all of them, but that also feels bad. Unless you're proposing that the option to turn on the meminfo fields turns off the current ones. But that also feels weird, but less so than a bunch of `fielddrop`s. :-)

**Comment by sparrc** [comment]
another option could be to map the names of a few fields from /proc/meminfo that are known to represent the current fields. That way we wouldn't have the same metric twice and we also wouldn't drop the current metrics completely.

**Comment by phemmer** [comment]
The problem with that is that it would be a little confusing. For example the current mem plugin output has an `active` field. The `/proc/meminfo` has `Active(anon)` and `Active(file)`. While I haven't checked to see what the plugin is currently using for `active`, if it's the anon value, then it seems confusing to have a field called `active` and another called `active_file`. Plus for someone who is familiar with the /proc/meminfo fields, or even someone just looking at [the documentation for /proc/meminfo](http://man7.org/linux/man-pages/man5/proc.5.html), now they have to figure out what fields have been mapped to what.

**Comment by tuukkamustonen** [comment]
Definitively allow picking the metrics one wants, if you're going to add lots of new metrics. Not everyone is interested in all the metrics, so allowing to pick what to produce would be nice.

**Comment by danielnelson** [comment]
We generally try to use the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options for reducing the number of fields, and only add dedicated options to pluguins if there is a substantial difference in the cost of collection.

**Comment by tuukkamustonen** [comment]
I'm an utter noob to telegraf so I wasn't aware of that. I should just RTFM. Thanks for the pointer!

**Comment by danielnelson** [comment]
Closing, most of the new memory stats have been added.  For any that may be still missing, I'd like it if we could add them to gopsutil and then tie them in to the plugin, but let's open new issues for the ones we need.
