### ISSUE TITLE
Aggregator plugins: Support historical data

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#1992]
Currently aggregator plugins only support aggregating data with "current" timestamps.

We should try to support a single stream of historical data in the aggregator plugins, as this likely could be a common use-case when parsing a logfile.

see https://github.com/influxdata/telegraf/issues/1989

from that issue:

> One "easy" workaround might be to create a single "historical window" which would have it's period started on the timestamp of the first "historical" metric that arrives. This would cover your use-case where you have a single stream of historical and ordered metrics arriving (ordered is the crucial point). I imagine that when dealing with historical data, this would be the most common use-case, especially when dealing with logfile parsing.

**Comment by mujahideen555** [comment]
Is there [[aggregator.mean]] plugin available in telegraf ? I am searching through but couldn't find if there is any aggregator plugin other than [[aggregator.minmax]].

**Comment by danielnelson** [comment]
@ghost Not currently but there is one in the works for 1.3.0 #2167

**Comment by bolek2000** [comment]
we are testing log parsing with telegraf and plan to import older logfiles into the DB. It will be handy if we can use the aggregator for historical data too.

**Comment by kevin-cantwell** [comment]
Can this issue be closed now with the advent of https://github.com/influxdata/telegraf/pull/6049 ?

**Comment by ssoroka** [comment]
I think so. If the grace period doesn't meet your needs, you also have the ability to use the state variable in a [custom starlark script](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/compare_metrics.star) to write any sort of aggregation rules you would like, at least as far as available memory will allow.
