### ISSUE TITLE
[Feature Request] Jolokia: JMX-path should be configurable

### ISSUE THREAD

**Issue by KingCrunch** [influxdata/telegraf#2005]
### Feature Reqeust

With Jolokia in Proxy mode the JMX-Context is harcoded to `/jmxrmi`. Not every setup use this default.

### Proposal:

Make JMX-path configurable

### Current behavior:

Path not configurable. It is hardcoded top [`/jmxrmi`](https://github.com/influxdata/telegraf/blob/1271f9d/plugins/inputs/jolokia/jolokia.go#L168)

### Desired behavior:

When using jolokia in proxy-mode it should be possible use different jmx-paths than `/jmxrmi`

### Use case

Right now jolokia is not usable at all with setups, that use different jmx-path than `/jmxrmi`

**Comment by danielnelson** [comment]
I believe this has been fixed in #2278 which will be included in 1.5.0.
