### ISSUE TITLE
cgroups: Grafana issues with / in path tag

### ISSUE THREAD

**Issue by fsvehla** [influxdata/telegraf#2010]
### Relevant telegraf.conf:

```
[[inputs.cgroup]]

  files = ["memory.usage_in_bytes", "cpuacct.usage"]
  paths = ["/sys/fs/cgroup/memory/*/*", "/sys/fs/cgroup/cpu/*/*"]
```

### System info:

- Ubuntu 16.04.1 LTS
- 1.1 RC1
- Grafana 3.1.1

### Steps to reproduce:

1. Configure as above
2. Try to filter by group tag in Grafana

### Expected behavior:

Filtered by tag in Grafana

### Actual behavior:

Since the path contains `/`, Grafana breaks.

### Additional info:

Maybe rewrite slashes as dots for this input?

**Comment by sparrc** [comment]
shouldn't this be opened as a bug in grafana, not telegraf?

**Comment by sparrc** [comment]
I'm not going to replace every single `/` with a `.` in telegraf. There are a huge multitude of tags that validly use `/`, namely for paths and URLs.

**Comment by fsvehla** [comment]
@sparrc You did here: https://github.com/influxdata/telegraf/pull/1523 :)

**Comment by sparrc** [comment]
no, I didn't, that was a single instance of replacing ` /Sec` with `_persec` in the measurement name.  That was a space, capital letter, and slash, and it was the measurement name, not a tag.
