### ISSUE TITLE
Mesos plugin - slaves field not found

### ISSUE THREAD

**Issue by rub0** [influxdata/telegraf#2011]
## Relevant Telegraf.conf info

`[[inputs.mesos]]
  ## Timeout, in ms.
  timeout = 100
  masters = ["master:5050"]
  # Metrics groups to be collected, by default, all enabled.
  
  ## Master metrics groups to be collected, by default, all enabled.

  # master_collections = [
  #  "resources",
  #  "master",
  #  "system",
  #  "agents",
  #  "frameworks",
  #  "tasks",
  #  "messages",
  #  "evqueue",
  #  "registrar",
  # ]

  ## A list of Mesos slaves, default is []
  slaves = ["localhost:5051"]
  ## Slave metrics groups to be collected, by default, all enabled.
   slave_collections = [
     "resources",
     "agent",
     "system",
     "executors",
     "tasks",
     "messages",
   ]
  ## Include mesos tasks statistics, default is false
  # slave_tasks = true`

## System Info

CentOS linux x86_64, tried with telegraf-1.0.1.x86_64 and telegraf-1.1.0~rc1.x86_64

Expected behavior:

When i set my slaves info with slaves = [] array, it might actually read the array and get the slaves communication.
When I set up slave_collections = [] array, it might actually query  the information y put in this array and send out the metrics

## Actual behavior

Instead of reading these arrays, it sends me a parsing error: `Error parsing telegraf.conf, line 1044: field corresponding to 'slave' is not defined in '*mesos.Mesos'`

## Aditional info

I didn't do anything fancy, I just uncommented the default config and tried

**Comment by sparrc** [comment]
can't tell for certain since you didn't provide your version info, but it looks like your telegraf version doesn't support mesos slave stats. You can check with `telegraf --usage mesos`

Version 1.1 will be up on the downloads page soon
