### ISSUE TITLE
Discrepancy in the cassandra read requests count

### ISSUE THREAD

**Issue by jaibheem** [influxdata/telegraf#2015]
Hello,

I am using Telegraf with Jolokia to momnitor the cassandra metrics, however I am seeing some discrepancy in the metrics. Here is the example. please help me understand if I am missing something.

**Item1**. Getting Read Requests count for a given Table in all the keyspaces and one of the table has to 103 read requests here. 
```
Metric: /org.apache.cassandra.metrics:type=Table,keyspace=*,scope=*,name=ReadLatency
Output : 
curl -s http://localhost:8778/jolokia/read/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=token,name=ReadLatency | python -m json.tool | grep OneMinuteRate
<<truncated>>
            "OneMinuteRate": 103.75071877917739,
<<truncated>>
```

**Item2**. Getting the total read requests for a give node in the cluster

```
Metric: /org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency
Output:
curl -s http://localhost:8778/jolokia/read/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency | python -m json.tool | grep OneMinuteRate
        "OneMinuteRate": 62.837457844199434,
```

So the expected behaviour should be the total read requests in Item2 should be greater than or equal to Item1. But Item2 is less than Item1.

Is there some mean/average is calculated when requested for the entire cluster? Please help me understand this behaviour.

Jolokia version: 1.3.4
Telegraf version: Master

**Comment by sparrc** [comment]
telegraf just reports what Cassandra reports, you should ask Cassandra what their metrics mean, or consult their documentation.

If you find something that you think would be helpful for other users, please then consider contributing that to the plugin documentation.
