### ISSUE TITLE
Docker: Allow excluding tags

### ISSUE THREAD

**Issue by deric** [influxdata/telegraf#2025]
In our scenario Docker images are assigned names based on Mesos task ID which aren't important for monitoring
```
container_name=mesos-4df23d64-cdb6-4683-8a0a-89c6e476d757-S1.9470dcf6-8197-464e-b09c-964fcd059b13
```
each time container is restarted, it will get a new ID. This obviously leads to high number of series generated by Docker collector. Would it be possible to define which tags are collected by the plugin?

Either by blacklisting:
```
exclude = ["container_name", "container_id"]
```
or maybe even better, just whitelist desired tags:
```
report = ["container_image", "container_image_version", "host"]
```

**Comment by sparrc** [comment]
you can use the tagexclude config option: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering
