### ISSUE TITLE
Telegraf net input permission denied

### ISSUE THREAD

**Issue by Dienns** [influxdata/telegraf#2040]
On my newest server, Ubuntu 16.04 LTS, Telegraf is unable to receive it's own network status through `sudo service telegraf start`.

ERROR in input [netstat]: error getting net connections info: open /proc/net/tcp: permission denied

I cannot seem to find an answer to fixing this. I tried the some commands that I found about an issue that is similiar to this one, but nothing worked.

(Ubuntu 16.04 LTS, only running Telegraf, external InfluxDB database)

**Comment by sparrc** [comment]
I think the error message is clear. If you want telegraf to collect /proc/net/tcp then the telegraf user needs to have permission to access that file, which is doesn't have on your machine. There are many different solutions to this problem and it depends on how you want to setup your permissions.

**Comment by Dienns** [comment]
@sparrc I must have not made myself clear; I am not an expert on Linux, I don't know how to give permission to the telegraf user. Could you give me a few example commands, explaining what they do and which one would be bestt?

**Comment by corentingi** [comment]
@Dienns You may find this thread interesting: http://serverfault.com/questions/513144/proc-net-tcp-cannot-be-read
If you are using a dedicated server, the kernel could have been modified. I just ran into this issue
