### ISSUE TITLE
Docker input plugin incompatible with Docker Engine 1.13.0-rc1

### ISSUE THREAD

**Issue by ndegory** [influxdata/telegraf#2042]
### Relevant telegraf.conf:

See gist below

### System info:

Telegraf 1.1.0 (and 1.1.1), Docker image (official one and also on custom build [appcelerator/telegraf](https://github.com/appcelerator/docker-telegraf))

### Steps to reproduce:

1. Generate a configuration file: 
    docker run --rm telegraf -sample-config > telegraf.conf
    enable the inputs.docker plugin by uncommenting the lines, comment all other input plugins
    this is equivalent to the configuration file gist below
2. Write a docker-compose file with an influxdb service and a telegraf service. See the gist below
3. Run the telegraf service: ```docker-compose -f docker-compose-telegraf.yml run telegraf```

### Expected behavior:

Telegraf should gather Docker metrics without errors.
See gist below.

### Actual behavior:

Each time the input plugin tries to collect the metrics, an error occurs: ```Error reading remote info: json: cannot unmarshal object into Go value of type string```. Metrics seem to be gathered anyway.
See the gist below.

### Additional info:

1 [Telegraf configuration file](https://gist.github.com/ndegory/6590595a068c3458a367fd7970b2fe5a)
2. [Docker compose file](https://gist.github.com/ndegory/a70d4193121428b279edb62f62278a6a
) 
3. [Container Stdout with Docker 1.12.3](https://gist.github.com/ndegory/24f8f77cb72868f8e6806b2bfdf4da60)
4. [Container Stdout with Docker 1.13.0-rc1](https://gist.github.com/ndegory/9880edb46d2300fa4dd37f30a6b65746)

**Comment by ndegory** [comment]
related to #2071

**Comment by sparrc** [comment]
how do you know it's related to #2071? Have you confirmed that updating the library will fix the issue?

**Comment by ndegory** [comment]
Correct, I've tried a quick fix with the docker/docker api instead of docker/engine-api, it fixes this issue (tested with Docker 1.12.3 and 1.13.0-rc2).

Because  unlike docker/engine_api github.com/docker/docker is not a library, it's vendored, and there's types conflicts in the way it is used in the telegraf plugin. The tests should be refactored (the DockerClient interface can't be used like that anymore).

Because of that, I didn't submit a PR, but you can see the progress here: https://github.com/ndegory/telegraf/commit/9806cdadf07ed6946af3581416a8a2fef3cfd52b

**Comment by ndegory** [comment]
@sparrc please tell me if you're interested in a PR on that topic, I'll spend more time on the tests in this case.

**Comment by sparrc** [comment]
yes, I would appreciate a PR very much :)

**Comment by ndegory** [comment]
I've tested it again with Docker engine 1.13.0-rc2 and rc3, the issue is no more, so it's not related to the API, it was a bug in Docker. We can close this issue.

**Comment by sparrc** [comment]
OK, thanks very much for following up @ndegory
