### ISSUE TITLE
Needed more information about timestamp modifier for processing custom logstamps

### ISSUE THREAD

**Issue by dmitrysdm** [influxdata/telegraf#2044]
I have two documents with information about custom log processing
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser
https://www.influxdata.com/telegraf-correlate-log-metrics-data-performance-bottlenecks/

now i have two kind of timestamp:
2016-10-25 11:50:21 ( from gpuz utility )
and
11/13/2016 00:00:17 ( from powershell script )
but have not sufficient information, how to set timestamp modifier for process my custom timestamps :(

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

**Comment by dmitrysdm** [comment]
I ask about this question in influxdb slack group, but unsuccessfully.
Now exist situation, when functional ready, but without documentation, nobody can use it :(
Do you know contact, who responsible for logparser, i will ask him documentation.
Thanks.
