### ISSUE TITLE
readme download links..

### ISSUE THREAD

**Issue by steverweber** [influxdata/telegraf#2048]
please update the readme with new download links... or a direct link to something like https://www.influxdata.com/downloads/#influxdb

wget https://dl.influxdata.com/telegraf/releases/telegraf_1.1.1_amd64.deb
sudo dpkg -i telegraf_1.1.1_amd64.deb

wget https://dl.influxdata.com/telegraf/releases/telegraf-1.1.1_windows_amd64.zip
unzip telegraf-1.1.1_windows_amd64.zip

etc.

**Comment by sparrc** [comment]
will get to this eventually, you could submit a pr in the meantime if it's urgent
