### ISSUE TITLE
postgresql_extensible plugin does not properly format float results

### ISSUE THREAD

**Issue by khera** [influxdata/telegraf#2052]
## Bug report

When a custom query returns a floating point value, it is formatted as a string for influx line input rather than as a float. In contrast, integers are properly recognized and formatted. Therefore I consider it a bug that the floats are not.

### Relevant telegraf.conf:

Here is a complete config file to demonstrate the issue:

```
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]


[[inputs.postgresql_extensible]]
   address = "host=yertle user=vivek sslmode=disable dbname=postgres"
[[inputs.postgresql_extensible.query]]
   sqlquery="select 10.0 as myvalue"
   version=901
   withdbname=false
   tagvalue=""
   measurement="something"
[[inputs.postgresql_extensible.query]]
   sqlquery="select 10 as myvalue"
   version=901
   withdbname=false
   tagvalue=""
   measurement="whatever"
[[inputs.postgresql_extensible.query]]
   sqlquery="select 'ten' as myvalue"
   version=901
   withdbname=false
   tagvalue=""
   measurement="stringy"
```

### System info:

Telegraf version 1.0.1 running on FreeBSD 10.3, built with go 1.7

### Steps to reproduce:

save above config to test.conf and run `telegraf -config test.conf -test`

### Expected behavior:

In the first line, I expect `myvalue=10.0`

### Actual behavior:

In the first line it emits `myvalue="10.0"`

### Additional info:

This is the full output I see:
```
* Plugin: postgresql_extensible, Collection 1
> something,db=postgres,host=sandbox.int.kcilink.com,server=host\=yertle\ user\=vivek\ dbname\=postgres myvalue="10.0" 1479324564000000000
> whatever,db=postgres,host=sandbox.int.kcilink.com,server=host\=yertle\ user\=vivek\ dbname\=postgres myvalue=10i 1479324564000000000
> stringy,db=postgres,host=sandbox.int.kcilink.com,server=host\=yertle\ user\=vivek\ dbname\=postgres myvalue="ten" 1479324564000000000
```

Looking at the code, it appears that there is a switch statement to do the conditional formatting at around line 282 which needs to learn about float type.

**Comment by james-lawrence** [comment]
I'll happily pick this up sometime in the next few months (by end of july)

**Comment by james-lawrence** [comment]
@danielnelson I investigated this issue and summarized it in the additional tests PR.

basically comes down to the way the driver is returning the type. I suggest @khera open an issue with https://github.com/jackc/pgx regarding numeric types and their return as a string.

long story short the workaround is to cast computed values to ::float in the query. i.e.) `SELECT 10.0::float` until the driver fixes the result.

**Comment by james-lawrence** [comment]
more information can be found here: https://github.com/jackc/pgx/issues/112
