### ISSUE TITLE
Add support for docker events

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#2054]
Hi,

it would be super handy if the docker input plugin had support for docker events (https://docs.docker.com/engine/reference/commandline/events/).

This way, down the line, kapacitor could alert when a specific event triggers (e.g. container restart)

Not sure if this feature should be implemented in the existing docker plugin (since it runs at a given interval) or in a new one?

Cheers,
Matteo

**Comment by m4ce** [comment]
@sparcc, I would like to contribute here. However, I'd need some design advice before I commence the work there. Do you think it's a good idea to implement this in the existing docker input plugin?

**Comment by sparrc** [comment]
are these events in a log somewhere? almost looks more like something for the logparser plugin

**Comment by m4ce** [comment]
@sparcc, it depends on the log driver. If the log driver is set to journald or syslog, they will be available under the system's logs. However, if the log driver is set to gelf, fluentd etc., they won't be there.

I guess another option would be to send the logs/events to logstash or fluentd and then forward them to influxdb. However, I wanted to avoid adding other components and only rely on telegraf.

**Comment by m4ce** [comment]
Actually, my bad, the events are not dependent on the log driver at all. You really have to stream them via the dedicated API endpoint.

**Comment by joeris-CGM** [comment]
I guess that they are located in the logfile of the daemon, so they are independent of the log-driver settings. Running a simple test on my own. But the events are interleaved with other logwritings, so you need to filter them. That's the reason why I would prefer the support for the event-endpoint, too.

**Comment by sspaink** [comment]
It seems the plugin `docker_logs` https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker_log could solve this problem as well if the events are logged to it? You would still have to filter things, closing this as there hasn't been any activity in this PR for a long time but please re-open and provide a recent use-case/documentation if this is still a desired feature. Thanks!
