### ISSUE TITLE
Telegraf InfluxDB udp output does not set database properly

### ISSUE THREAD

**Issue by evanccnyc** [influxdata/telegraf#2055]
## Bug report
  On Telegraf 1.1.1 it appears that the database is not set properly in a UDP packet. Its set properly in HTTP.

### Relevant telegraf.conf:
```
...
[[outputs.influxdb]]
  ## The full HTTP or UDP endpoint URL for your InfluxDB instance.
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["udp://10.10.25.84:9096"] # required
  ## The target database for metrics (telegraf will create it if not exists).
  database = "abcdefg" # required
...
```
### System info:
Ubuntu 14.04
Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)

### Steps to reproduce:

1. Create InfluxDB output with UDP settings in telegraf.conf
2. Specify database in config
3. Restart Telegraf
4. Wait till data is sent, check influxdb, data points/database are not created properly

### Expected behavior:
Data & database created and data sent properly

### Actual behavior:
No data

### Additional info:

Here is the packet capture of one of the metrics being sent from Telegraf to influx:

```
19:42:00.327605 IP 10.10.22.26.52875 > 10.10.25.84.9096: UDP, length 199
	0x0000:  4500 00e3 4649 4000 4011 b03f 0a0a 161a  E...FI@.@..?....
	0x0010:  0a0a 1954 ce8b 2388 00cf d49c 7072 6f63  ...T..#.....proc
	0x0020:  6573 7365 732c 686f 7374 3d74 656c 6567  esses,host=teleg
	0x0030:  7261 6672 656c 6179 2d73 7461 672d 7573  rafrelay-stag-us
	0x0040:  2d65 6173 742d 3163 2d69 2d34 6139 3961  -east-1c-i-4axxa
	0x0050:  6262 xxxx xxxx xxxx xxxx xxxx 2e73 7461  bb2.xxx.sta
	0x0060:  6720 626c 6f63 6b65 643d 3069 2c70 6167  g.blocked=0i,pag
	0x0070:  696e 673d 3069 2c72 756e 6e69 6e67 3d30  ing=0i,running=0
	0x0080:  692c 736c 6565 7069 6e67 3d31 3239 692c  i,sleeping=129i,
	0x0090:  7374 6f70 7065 643d 3069 2c74 6f74 616c  stopped=0i,total
	0x00a0:  3d31 3239 692c 746f 7461 6c5f 7468 7265  =129i,total_thre
	0x00b0:  6164 733d 3136 3969 2c75 6e6b 6e6f 776e  ads=169i,unknown
	0x00c0:  3d30 692c 7a6f 6d62 6965 733d 3069 2031  =0i,zombies=0i.1
	0x00d0:  3437 3934 3131 3732 3030 3030 3030 3030  4794117200000000
	0x00e0:  3030 0a                                  00.
```

**Comment by sparrc** [comment]
Unfortunately it is not possible to set the database with udp packets. The UDP service on your influxdb instance is what sets the database.

There is a proposal for an updated & more refined line-protocol spec here: https://github.com/influxdata/influxdb/issues/6037. I believe this includes a way to specify the database on a per-metric level.

**Comment by evanccnyc** [comment]
Ah thanks the documentation was unclear about that.

**Comment by natejgardner** [comment]
Is it now possible to set the database name via UDP? Or, if not, is it possible to set multiple UDP endpoints in InfluxDB's config to correspond to each database?
