### ISSUE TITLE
First class Debian package support

### ISSUE THREAD

**Issue by mattyjones** [influxdata/telegraf#2057]
I was looking at creating first class support for both kapacitor and telegraf for Debain. Are there thoughts on this here? There is currently no official packages for Debian and I am running tlegraf on it, in a production capacity and would like support for it.

**Comment by phemmer** [comment]
What do you mean there are no official packages?

https://www.influxdata.com/downloads/

![image](https://cloud.githubusercontent.com/assets/1826947/20452339/58cd4010-add5-11e6-883d-e648440b9853.png)

**Comment by mattyjones** [comment]
I am referring to pure Debian packages, not third-party packages. I want to be able to `apt-get install telegraf` w/o have to adjust my sources.

**Comment by phemmer** [comment]
Oh, you mean you want to add the package to the official debian repo. Someone has already beaten you to it. An ITP was filed several months ago and appears to be well under way: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793749

**Comment by mattyjones** [comment]
I will reach out then and see if I can be of further help. Thanks!
