### ISSUE TITLE
docker input percpu_usage

### ISSUE THREAD

**Issue by rolele** [influxdata/telegraf#2059]
what is the telegraf equivalent of the docker engine metric percpu_usage?

```
PercpuUsage []uint64 `json:"percpu_usage"`
```

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
