### ISSUE TITLE
procstat plugin reports old pids

### ISSUE THREAD

**Issue by aeugenio** [influxdata/telegraf#2062]
## Bug report
i want procstat to track the current pid for a process and then have kapacitor alert if that process is no longer found or the pid changes.  using the pid_file and pattern inputs, i see old pid's reported by telegraf; they appear to be cached as restarting telegraf service stops the old pid's from being sent.

note that option 1 (pattern) will not report that the pid no longer exists; it reports the old one forever. in option 2, if the pidfile disappears, telegraf reports no pid, but then once the pidfile exists again, it reports old and current pids.

### Relevant telegraf.conf:
all defaults except for influxdb url and:

option 1)
[[inputs.procstat]]
  pattern="serviceName=solr"

option 2)
[[inputs.procstat]]
  pid_file= "{SOME_PATH}/var/solr/solr.pid"

### System info:

[Include Telegraf version, operating system name, and other relevant details]

telegraf -version
Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)

influx -version
InfluxDB shell version: 1.1.0

latest chronograf
sudo systemctl status chronograf
● chronograf.service - Open source monitoring and visualization UI for the entire TICK stack.
   Loaded: loaded (/lib/systemd/system/chronograf.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2016-11-19 22:17:08 UTC; 1 day 22h ago
     Docs: https://www.influxdata.com/time-series-platform/chronograf/
 Main PID: 14054 (chronograf)
    Tasks: 14
   Memory: 17.9M
      CPU: 25.647s
   CGroup: /system.slice/chronograf.service
           └─14054 /usr/bin/chronograf --host 0.0.0.0 --port 8888 -b /var/lib/chronograf/chronograf-v1.db -c /usr/share/chronograf/canned

### Steps to reproduce:
1) start telegraf
2) start solr
3) check chronograf and confirm 1 pid is reported
4) watch for a while
5) stop solr
6) chronograf continues to report old pid
7) a few minutes later, start solr
8) confirm chronograf shows old and new pids

### Expected behavior:
only active pid is reported by procstat

### Actual behavior:
multiple pid's (previous and current) for a single pidfile and/or pattern are reported

**Comment by phemmer** [comment]
Dup #1636?

**Comment by sparrc** [comment]
yep, dupe
