### ISSUE TITLE
[Feature request] Add support for linkerd and namerd

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#2063]
## Feature Request
Add support for linkerd and namerd

### Proposal:
There is no linkerd exporter for Prometheus thus telegraf's intput.prometheus cannot work with linkerd or namerd. An option is to make telegraf collect stats from linkerd and namerd directly.

### Current behavior:
No linkerd or namerd input plugin.

### Desired behavior:
Make an input plugin for linkerd and namerd.

**Comment by sparrc** [comment]
can you provide a link to documentation on their stats endpoint?

**Comment by wei-hai** [comment]
please check out this link https://linkerd.io/getting-started/admin/

**Comment by wei-hai** [comment]
it looks like the endpoint for influxdb has been supported since 2 months ago.
https://github.com/linkerd/linkerd-examples/tree/master/influxdb
