### ISSUE TITLE
Add support to parse nested JSON array

### ISSUE THREAD

**Issue by kevinjos** [influxdata/telegraf#2066]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Extended https://github.com/influxdata/telegraf/pull/1965 to support object specific tags in nested JSON arrays. Is there a small change to the JSON parser to accommodate this request without breaking existing functionality?

### Current behavior:

The HTTP JSON input plugin line protocol output for the following...

JSON response
```
{"service":"myservice",
  "metrics":[{"tagA":"ABC", "tagB":"XYZ", "value":1.0}, {"tagA":"DEF", "tagB":"UVW", "value":2.0}]
}
```

telegraf.conf
```
[[inputs.httpjson]]
  name = "mycollector"

  servers = [
    "http://my.service.com/_stats"
  ]

  method = "GET"

  response_timeout = "5s"

  tag_keys = ["service", "tagA", "tagB"]
```

Line Protocol
```
httpjson_mycollector,service=myservice,host=http://my.service.com/_stats metrics_0_value=1.0,metrics_1_value=2.0
```

### Desired behavior:

Line Protocol
```
httpjson_mycollector,service=myservice,host=http://my.service.com/_stats,tagA=ABC,tagB=XYZ metrics_value=1.0
httpjson_mycollector,service=myservice,host=http://my.service.com/_stats,tagA=DEF,tagB=UVW metrics_value=2.0
```

### Use case: 

Extends the functionality of the httpjson input plugin to support global and object specific tags

**Comment by sparrc** [comment]
there is already an issue open to support more generic JSON parsing, see #1363
