### ISSUE TITLE
Fully transferring all measurements/datapoints from one influxdb to the remote one.

### ISSUE THREAD

**Issue by joezhoujinjing** [influxdata/telegraf#2067]
## Feature Request
We gather metrics in the local database (with shorter retention policy) in case of data point dropped as described in #802, and transfer the local database to remote databases. 

However, there is no easy/efficient way to fully transfer one database to the other in telegraf, (not exactly synchronization, as there is only one-way communication.) The intputs.influxdb is for HTTP endpoints only.

Is there any build-in way to do it? or am I missing anything?
### Current behavior:
maybe using http endpoints?
### Desired behavior:
easily configurable

**Comment by sparrc** [comment]
this is not a feature for telegraf, maybe you meant to open this on the InfluxDB repo?
