### ISSUE TITLE
StatsD set doesn't accept a string

### ISSUE THREAD

**Issue by kureikain** [influxdata/telegraf#2068]
### System info:

```
telegraf --version
Telegraf - version 1.0.1

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

StatsD config:

```
# # Statsd Server
[[inputs.statsd]]
#   ## Address and port to host UDP listener on
   service_address = ":8125"
#   ## Delete gauges every interval (default=false)
#   delete_gauges = false
#   ## Delete counters every interval (default=false)
#   delete_counters = false
#   ## Delete sets every interval (default=false)
#   delete_sets = false
#   ## Delete timings & histograms every interval (default=true)
   delete_timings = true
#   ## Percentiles to calculate for timing & histogram stats
   percentiles = [90, 95, 99]
#
#   ## separator to use between elements of a statsd metric
   metric_separator = "_"
#
#   ## Parses tags in the datadog statsd format
#   ## http://docs.datadoghq.com/guides/dogstatsd/
   parse_data_dog_tags = true
#
#   ## Statsd data translation templates, more info can be read here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite
#   # templates = [
#   #     "cpu.* measurement*"
#   # ]
#
#   ## Number of UDP messages allowed to queue up, once filled,
#   ## the statsd server will start dropping packets
   allowed_pending_messages = 10000
#
#   ## Number of timing/histogram values to track per-measurement in the
#   ## calculation of percentiles. Raising this limit increases the accuracy
#   ## of percentiles but also increases the memory usage and cpu time.
#   percentile_limit = 1000
```

### Steps to reproduce:

1. Tail the log
1. Sending a SET like `test:a123b|s` 
2. Log show: ` Error: parsing value to int64: test:a123b|s`. No data is inserted into InfluxDB

### Expected behavior:

Data is flushed into InfluxDB. `test` should be create and increase value by 1

### Actual behavior:

No data is created. Log shows error.

### Additional info:

[Include gist of relevant config, logs, etc.]

### Use case: [Why is this important (helps with prioritizing requests)]

I want to count unique user id of a MongoDB instance. The ObjectID is string. Rightnow I have to convert MongoDB ObjectID into a number.

**Comment by sparrc** [comment]
can you provide and example of a common statsd server that accepts strings for sets?

**Comment by sparrc** [comment]
the "statsd spec" specifies values as only being integer or float: https://github.com/b/statsd_spec#metric-types--formats

**Comment by nmische** [comment]
We just ran up against this as well. Etsy's implementation accepts strings: https://github.com/etsy/statsd/blob/master/lib/set.js.

**Comment by kureikain** [comment]
@sparrc I haven't use any other StatsD except the one from `etsy`. When I use it last year, I have to use this https://github.com/bernd/statsd-influxdb-backend/commit/33a682cc8fdfafeebaa515b8caa71d2ab7c545b6 which is a StatsD plugin to flush metric to InfluxDB. It supports string.

I haven't used any other StatsD server except etsy statsd and telegraf. I found the need of counting string in a set is pretty reasonable. People use ElasticSearch or MongoDB as main storage usually will not have an integer id, but an UUID(which is a string) instead. We can try some tip to hash/encode the UUID into an integer but that's a hack and add confusing to the code.

I imagine it isn't that hard to support string. I can take a look and submit a PR if this is something can be consider a feature to be merged.

**Comment by sparrc** [comment]
I think the best way to do this would be to simply treat all "set" keys as strings, since the actual value doesn't matter, all that matters is it's uniqueness (ie, "1" == 1)

**Comment by nmische** [comment]
I think treating all set keys as strings is reasonable. The Etsy implementation is JavaScript where `"1" == 1` evaluates to true.
