### ISSUE TITLE
docker_container_net is missing

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#2069]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:
<pre>
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "5s"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "5s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default, precision will be set to the same timestamp order as the
  ## collection interval, with the maximum being 1s.
  ## Precision will NOT be used for service inputs, such as logparser and statsd.
  ## Valid values are "ns", "us" (or "µs"), "ms", "s".
  precision = ""
  ## Run telegraf in debug mode
  debug = false
  ## Run telegraf in quiet mode
  quiet = false
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] # required
  ## The target database for metrics (telegraf will create it if not exists).
  database = "telegraf1.0" # required

  ## Retention policy to write to. Empty string writes to the default rp.
  retention_policy = ""
  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
  write_consistency = "any"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  username = "root"
  password = "root"

# # Read metrics about docker containers
[[inputs.docker]]
 ## Docker Endpoint
 ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
 ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  ## Only collect metrics for these containers, collect all if empty
  container_names = []
  ## Timeout for docker list, info, and stats commands
  timeout = "5s"
  ## Whether to report for each container per-device blkio (8:0, 8:1...) and
  ## network (eth0, eth1, ...) stats or not
  perdevice = true
  ## Whether to report for each container total blkio and network stats or not
  total = false
</pre>

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf version 1.1.1
OS: Linux 3.10.0-327.28.3.el7.x86_64

### Actual behavior:
docker_container_net is missing. I printed out all the output, docker_container_net is missing. 

### Additional info:
I complied from the source code and printed out the stat.Networks in inputs/docker/docker.go. It is an empty map[].

The following is the original stat gotten from docker client.
<pre>
{{0 [] 0 0} 0 {0 0 0}} {{3138732304 [358627951 540228608 434828593 662039053 179236583 184191937 183274429 596305150] 1520000000 660000000} 285027640000000 {0 0 0}} {178151424 180244480 map[hierarchical_memory_l
imit:9223372036854771712 rss:149790720 rss_huge:144703488 total_cache:28360704 total_inactive_anon:24576 total_inactive_file:10240000 writeback:0 active_file:18034688 cache:28360704 pgpgin:12425 total_pgfault:8900 total_rss:149790720 unevictable:0 active
_anon:149852160 mapped_file:15982592 total_active_anon:149852160 total_dirty:0 dirty:0 total_pgmajfault:209 pgmajfault:209 total_mapped_file:15982592 total_pgpgin:12425 inactive_anon:24576 total_active_file:18034688 total_writeback:0 inactive_file:102400
00 pgfault:8900 pgpgout:13899 total_pgpgout:13899 total_rss_huge:144703488 total_unevictable:0] 0 16774057984} {[{8 0 Read 36876288} {8 0 Write 2170880} {8 0 Sync 2166784} {8 0 Async 36880384} {8 0 Total 39047168}] [{8 0 Read 852} {8 0 Write 15} {8 0 Syn
c 14} {8 0 Async 853} {8 0 Total 867}] [] [] [] [] [] []} {0}} map[]}
</pre>

### Question
I see in `src/github.com/docker/engine-api/types/stats.go`
<pre>
type StatsJSON struct {
	Stats

	// Networks request version >=1.21
	Networks map[string]NetworkStats `json:"networks,omitempty"`
}
</pre>

Must I have docker 1.21 to make it work?

**Comment by sparrc** [comment]
Thank you for the detailed debugging information, as far as I can tell your docker version does not support this metric. If there are no stats in stat.Networks then there isn't really anything we can do about it. If there should be stats there then this would be a bug in https://github.com/docker/engine-api
