### ISSUE TITLE
chrony leap_status should be a field?

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#2072]
Hi,

I'm working with the chrony input plugin and trying to set up some monitoring using kapacitor.

I have a feeling that the leap_status should be a field rather than a tag as it's something that one wants to monitor on.

It is a status field that one wants to use to monitor whether chrony is working or not as in synched with its time sources.

Let me know what you think and I can make the necessary changes and send a pull request.

Cheers,
Matteo

**Comment by sparrc** [comment]
sure, seems reasonable

**Comment by sspaink** [comment]
Closing as there is a viable alternative using the posted query.
