### ISSUE TITLE
issues compiling on alpine linux 3.4 ( use of internal package not allowed )

### ISSUE THREAD

**Issue by oxitech239** [influxdata/telegraf#2086]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
imports gopkg.in/mgo.v2/internal/scram: use of internal package not allowed
Makefile:18: recipe for target 'build' failed

### System info:

[Include Telegraf version, operating system name, and other relevant details]
telegraf1.1.1, go 1.6.3 linux/arm, alpine linux 3.4

### Steps to reproduce:
make

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
I'm sorry but I can't spend the time to help you debug Go build issues. I can assure you that this project builds if you get your environment setup properly.

**Comment by oxitech239** [comment]
earlier reports indicate this may be a bug with go, can you validate building against the reportd version of GO works ?

**Comment by oxitech239** [comment]
found 

export GOPATH="$pwd" 
works partially

this missing modules are under src/github.com/docker/docker/vendor/github.com/ but the make process looks under src/github.com/docker/docker/vendor/github.com/src/github.com

**Comment by oxitech239** [comment]
It is totally unclear how to set GOPATH to include these when it's looking under the wrong path (./src)

**Comment by sparrc** [comment]
like I said, I can't help you with Go build env problems, I'd reccomend the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
