### ISSUE TITLE
exec input should be able to handle long-running commands

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2087]
### Proposal:
The `exec` input should be able to handle commands which run, and then stream their output data.

### Current behavior:
Currently telegraf expects commands launched by the `exec` input to generate output and then exit. Thus telegraf buffers all the output until the command does exit.

### Desired behavior:
Telegraf should instead be able to launch the command and read the output as the command generates it.

### Use case: [Why is this important (helps with prioritizing requests)]
This is useful for plugins which stay running, generating statistics on their own interval. Currently the only way to get data from such inputs is through some sort of socket (tcp/udp), which is less than ideal.

In my specific use case, I am trying to launch a second telegraf inside a network namespace to collect statistics from that namespace. I have the second telegraf configured with the `file` output plugin writing to STDOUT.

**Comment by paulgear** [comment]
This would also help in porting/adapting input plugins from older systems like collectd.

**Comment by shish** [comment]
Looks like #4424 implements this, just waiting for it to be merged

**Comment by sspaink** [comment]
Resolved with https://github.com/influxdata/telegraf/pull/4424
