### ISSUE TITLE
Plugin suggestion: Kong

### ISSUE THREAD

**Issue by mytototo** [influxdata/telegraf#2093]
It would be nice to have an input plugin for the [Kong API gateway](https://getkong.org/). So, this way we'll be able to collect and report metrics of everything that happens on the gateway and all of our APIs.

**Comment by quanghiem** [comment]
I use the Kong StatsD plugin with the Telegraf StatsD input to get Kong stats.  The Kong StatsD plugin is nice since it breaks down all stats in to different buckets per API endpoint.

https://getkong.org/plugins/statsd/

**Comment by aaae** [comment]
<img width="567" alt="qq20170320-101416 2x" src="https://cloud.githubusercontent.com/assets/3000843/24087131/0682b5b6-0d56-11e7-9c75-70cc652ae814.png">
@quanghiem   tks

**Comment by sspaink** [comment]
Closing because there hasn't been any activity in this issue for a few years, looks like using the statsd plugin is a viable alternative. Although pull requests are welcome if anyone would like to work on this.
