### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by zrice57** [influxdata/telegraf#2102]
## Bug report
Telegraf crashes with error  **"fatal error: concurrent map writes"**

### Relevant telegraf.conf:
See gist.

### Relevant Input
I have two statsd inputs configured and a few other inputs. I've only included the statsd input config because it seems the most relevent. 

This has been happening on multiple servers regularly for at least a week. 

### System info:
* telegraf.x86_64  1.1.1-1  @influxdb
* CentOS 7
* Linux version 3.10.0-327.28.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Aug 3 11:11:39 UTC 2016

### Steps to reproduce:

1. Run telegraf
2. telegraf will run without issues for many hours
3. kapacitor will tell me one of my servers has stopped sending data
4. kapacitor will tell me "JK it's all good" about 30 seconds later
5. Check telegraf logs (in /varr/log/messages)
6. Learn that telegraf has crashed and there is a huge crash log

### Expected behavior:
Telegraf will run until the heat death of the universe.

### Actual behavior:
Telegraf runs for a few  hours.

### Additional info:
Here is the link to the crash log and configs: [Link](https://gist.github.com/zrice57/55fb0c9f4564f96a851a8bf334525e77)

I will provide anything else you need.
Thank you for your time!

**Comment by sparrc** [comment]
thanks for the crash log, might be related to this: https://github.com/influxdata/telegraf/issues/1975
