### ISSUE TITLE
net_reponse plugin not working for udp check

### ISSUE THREAD

**Issue by danyli78** [influxdata/telegraf#2103]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:
```
[[inputs.net_response]]
#  ## Protocol, must be "tcp" or "udp"
   protocol = "udp"
   address = "localhost:8092"
   timeout = "2s"

#  ## Optional string sent to the server
   send = "hello"
   expect = "hello"
   read_timeout = "1s"
```

### System info:

telegraf v1.1, centos 7.2

### Steps to reproduce:

Add the net_response plugin and restart service

### Expected behavior:

Should be the same behavior as the TCP port check

### Actual behavior:

If you leave the "send" / "expect" string empty or commented it out, you get this ERROR in the log:

2016/11/29 13:33:50 E! ERROR in input [inputs.net_response]: Expected string cannot be empty

If you just type anything in the "send"/"expect" string, the above error disappear but you get this:

2016/11/29 13:48:21 E! ERROR in input [inputs.net_response]: read udp 127.0.0.1:35100->127.0.0.1:8092: i/o timeout

**Comment by sparrc** [comment]
looks like for UDP the send/expected strings are required, it is just a doc issue

**Comment by danyli78** [comment]
if I want to check the Telegraf UDP port, what send string and expect string do I put?

**Comment by sparrc** [comment]
@danyli78 there are none, an application would have to be specifically configured to support this

**Comment by danyli78** [comment]
thanks, hopefully some telegraf health check is in the work....
