### ISSUE TITLE
Debian package: failed install when group exists

### ISSUE THREAD

**Issue by kali-brandwatch** [influxdata/telegraf#2106]
## Bug report

Installing debian official packages will fail in a system where the group `telegraf` already exists. This is due to the `post-install.sh` script and the way the user is added into the system.

### Relevant telegraf.conf:
This bug is cofniguration independent

### System info:
Reproduced in Debian 7-8 and Ubuntu 16 with Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)

### Steps to reproduce:

1. Manually create group `telegraf`
2. `apt-get install telegraf`

### Expected behavior:
Telegraf package is installed, user is created and added to the existing group

### Actual behavior:
Package fails to configure due to failed post-install:
```
Unpacking telegraf (1.1.1-1) over (1.1.1-1) ...
Setting up telegraf (1.1.1-1) ...
useradd: group telegraf exists - if you want to add this user to that group, use -g.
chown: invalid user: ‘telegraf:telegraf’
```

**Comment by kali-brandwatch** [comment]
Any thoughts on this issue? This bug makes the install fail and leaves the service unable to run, so it shuold be considered a little bit. Also, I have provided a fix as well.

**Comment by sparrc** [comment]
@kali-brandwatch we'll review it eventually, please be patient
