### ISSUE TITLE
[Feature request] add input plugin to tail systemd journal

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#2109]
### Proposal:
support tailing systemd journal
### Current behavior:
no such input plugin
### Desired behavior:
add it
### Use case: [Why is this important (helps with prioritizing requests)]
some service adds log via systemd journal instead of specific log file, it is better to support tailing the systemd journal as an option similar to input.tail and input.logparser

**Comment by phemmer** [comment]
I've completed work adding this. However creation of a PR is pending a bug fix on the journald package I'm using: https://github.com/coreos/go-systemd/pull/231

**Comment by phemmer** [comment]
PR up: #2569
