### ISSUE TITLE
Run telegraf inside docker, how to collect net, processors input in the host?

### ISSUE THREAD

**Issue by ckanner** [influxdata/telegraf#2112]
## description
Now telegraf is running inside docker.I set input config to collect net, processor measurements, but the net and processors measurements collected is the docker container's measurements which run telegraf. In fact, my mind is to collect that measurements on the host which the telegraf docker is running on.How can I fix it?

## my telegraf input conf

```
# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration


# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration


# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration


# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  interfaces = ["eth0", "eth1"]
```

**Comment by Sil5nc5** [comment]
Hi @ckanner,

you can install and configure the Telegraf agent on your docker host. You can enable the "inputs.net" to get the local network statistics (docker host itself) and use the docker plugin ([https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker]) to collect docker related statistics including your individual container network utilization. See the link for more information.

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

**Comment by rs-development** [comment]
I would guess this is a kinda bug, because it is possible to get DISKIO and DISKUSAGE inside the telegraf container from the host with this config:

    volumes:
      - ${VOLUME_BASE_PATH}/telegraf/etc:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_MOUNT=/host

I would expect something similar for the net and netstat plugins.

**Comment by b2ag** [comment]
https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container

**Comment by mleonhard** [comment]
NOTE: It doesn't work for netstat.  Telegraf's `inputs.netstat` plugin can report values only for the container.  It cannot report on the host.  It does not use the `HOST_PROC` environmnet variable.  This is because the plugin uses the gopsutil library which executes the `lsof` command:
https://github.com/shirou/gopsutil/blob/a3b23c5ccf4fb7b33d319fcaad53d7777907f4e1/internal/common/common_unix.go#L12
And `lsof` always opens `/proc`.  The string is hard-coded:
https://github.com/lsof-org/lsof/blob/e4bc415f0c4659af44ed4a2ef69f87e88a8c6a0a/dialects/linux/dproc.c#L297

Demonstration:
```
# netstat -an |grep ESTABLISHED |wc -l
3
# docker run --tty --interactive --rm --privileged \
--volume /root/telegraf.conf:/etc/telegraf/telegraf.conf \
--volume /:/hostfs:ro \
--volume /etc:/hostfs/etc:ro \
--volume /proc:/hostfs/proc:ro \
--volume /sys:/hostfs/sys:ro \
--volume /var:/hostfs/var:ro \
--volume /run:/hostfs/run:ro \
--env HOST_ETC=/hostfs/etc \
--env HOST_PROC=/hostfs/proc \
--env HOST_SYS=/hostfs/sys \
--env HOST_VAR=/hostfs/var \
--env HOST_RUN=/hostfs/run \
--env HOST_MOUNT_PREFIX=/hostfs \
telegraf@sha256:490e2976a5890ae6474fe36cb44764c81f17215396647c0ddae09b04e47a30b6 2>&1
2020-03-13T06:25:39Z I! Starting Telegraf 1.13.4
2020-03-13T06:25:39Z I! Using config file: /etc/telegraf/telegraf.conf
2020-03-13T06:25:39Z I! Loaded inputs: netstat
2020-03-13T06:25:39Z I! Loaded aggregators: 
2020-03-13T06:25:39Z I! Loaded processors: printer
2020-03-13T06:25:39Z I! Loaded outputs: discard
2020-03-13T06:25:39Z I! Tags enabled: host=6ffa2cb04dd3
2020-03-13T06:25:39Z I! [agent] Config: Interval:2s, Quiet:false, Hostname:"6ffa2cb04dd3", Flush Interval:10s
netstat,host=6ffa2cb04dd3 tcp_established=0i 1584080740000000000
netstat,host=6ffa2cb04dd3 tcp_established=0i 1584080742000000000
^C2020-03-13T06:25:42Z I! [agent] Hang on, flushing any cached metrics before shutdown
# cat /root/telegraf.conf 
[agent]
  interval = "2s"
  debug = false

[[outputs.discard]]

[[processors.printer]]

[[inputs.netstat]]
 fieldpass = ["tcp_established"]
```

**Comment by danielnelson** [comment]
@mleonhard I believe that only happens for Darwin or perhaps FreeBSD.  On Linux it reads the values from procfs: https://github.com/shirou/gopsutil/blob/a3b23c5ccf4fb7b33d319fcaad53d7777907f4e1/net/net_linux.go#L476

**Comment by elbowz** [comment]
Sorry, for understand, it's a bug, feature or I have made something wrong?

I run telegraf with this docker-compose config:

```yaml
 volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
```

telegraf.conf
```
[[inputs.net]]
   interfaces = ["eth*", "enp3s[0-1]"]
```

but still get stats from docker container instead of host

Thanks!

**Comment by UncleGravity** [comment]
bumping this, I have the same issue as above, running the net input plugin on a linux vm (parellels), with the same docker-compose file, only shows net info on the docker container, and not the host.

**Comment by powersj** [comment]
> bumping this,

Rather than "bumping" a closed issue, I would suggest opening a new issue or even better asking your questions on the [forums](https://community.influxdata.com/) or [slack](https://influxdata.com/slack).

Please see previous comments about this on https://github.com/influxdata/telegraf/issues/11215
