### ISSUE TITLE
Invalid column name 'Service broker' 

### ISSUE THREAD

**Issue by cankaya07** [influxdata/telegraf#2117]
I am using Windows version on Windows Server 2012 R2. SQL Server's default collation is TURKISH_CI_AS SQL Server 2014 SP2 (12.0.5000.0) Default language English

2016/12/02 14:20:00 Invalid column name 'Service broker'.
2016/12/02 14:20:00 Invalid column name 'Service broker'.
2016/12/02 14:20:00 Output [influxdb] wrote batch of 504 metrics in 93.7591ms
2016/12/02 14:20:00 Invalid column name 'Service broker'.
2016/12/02 14:20:00 Invalid column name 'Service broker'.
2016/12/02 14:20:01 Output [influxdb] wrote batch of 1000 metrics in 78.1338ms
2016/12/02 14:20:01 Output [influxdb] wrote batch of 1000 metrics in 62.5074ms
2016/12/02 14:20:10 Output [influxdb] buffer fullness: 942 / 1000 metrics. Total gathered metrics: 192747. Total dropped
 metrics: 0.
2016/12/02 14:20:10 Invalid column name 'Service broker'.
2016/12/02 14:20:10 Invalid column name 'Service broker'.
2016/12/02 14:20:10 Output [influxdb] wrote batch of 942 metrics in 93.7591ms
2016/12/02 14:20:10 Invalid column name 'Service broker'.
2016/12/02 14:20:10 Invalid column name 'Service broker'.
2016/12/02 14:20:11 Output [influxdb] wrote batch of 1000 metrics in 109.3852ms
2016/12/02 14:20:11 Output [influxdb] wrote batch of 1000 metrics in 78.1343ms
2016/12/02 14:20:20 Invalid column name 'Service broker'.
2016/12/02 14:20:20 Invalid column name 'Service broker'.
2016/12/02 14:20:20 Output [influxdb] buffer fullness: 737 / 1000 metrics. Total gathered metrics: 195484. Total dropped
 metrics: 0.

**Comment by sparrc** [comment]
We can't possibly support every single SQL server collation language, sorry. If you'd like you can make a note in the README that only English collation is supported.
