### ISSUE TITLE
Allow ignore failed metrics/hosts ( Feature request )

### ISSUE THREAD

**Issue by yellowmegaman** [influxdata/telegraf#2118]
## Bug report
Metrics are not sent when some hosts failing.

### Relevant telegraf.conf:
```
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false
##############################################################################
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] 
  database = "telegraf_som" 
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
##############################################################################
[[inputs.rabbitmq]]
  url = "http://rabbitmq:15672"
  username = "user"
  password = "pass"
  name_prefix = "som_"
[[inputs.couchbase]]
  servers = ["http://login:pass@couchbase:8091"]
  name_prefix = "som_"
[[inputs.cassandra]]
  name_prefix = "som_"
  context = "/jolokia/read"
  servers = ["loigin:pass@cassandra:8778"]
  metrics  = [
    "/java.lang:type=GarbageCollector,name=ConcurrentMarkSweep/CollectionTime"
  ]
```

### System info:

Ubuntu 16.04 Xenial
Telegraf docker image v1.1.1

### Steps to reproduce:

1. docker run -d --name=telegraf --net=container:influxdb -v telegraf.conf:/etc/telegraf/telegraf.conf telegraf (config above) 
2. Hosts rabbitmq couchbase and cassandra are consul services-dns names. ( but could be ordinary hosts)

### Expected behavior:
Metrics are collected and sent even if some hosts are down

### Actual behavior:
If cassandra is down, telegraf just reports errors and don't send any metrics at all.

### Additional info:
Even if collecting metrics from remote hosts isn't "best practice", i think this situation is all the same if metrics were collected on localhost.

## Feature Request
Please add "ignore" parameter to metrics collector.

### Proposal:
I monitor apps and cluster separately, no need to stop sending metrics if some service is down.

Thanks a lot in advance!

**Comment by sparrc** [comment]
something is not quite right, plugins run independently so one failing shouldnt affect another.

**Comment by yellowmegaman** [comment]
You're right, thank you. Just had to restart telegraf a couple of times, weird. Problem never occured after that.
