### ISSUE TITLE
Influxdb input plugin is missing field for GC pause times

### ISSUE THREAD

**Issue by tevjef** [influxdata/telegraf#2120]
## Feature Request

The Influxdb input plugin that reads json from the standard /debug/vars endpoint of a golang program is missing the `PauseNs` [memstat](https://golang.org/src/runtime/mstats.go?s=4222:6073#L106) field. That field has the value of the recent GC pause durations, with the most recent at [(NumGC+255)%256]

### Use case: 

It is useful when measuring GC pause durations in Go programs

**Comment by tevjef** [comment]
PR #2121

**Comment by danielnelson** [comment]
Closing, I think this was fixed in 1.2
