### ISSUE TITLE
Add tracing to the http_response plugin 

### ISSUE THREAD

**Issue by tevjef** [influxdata/telegraf#2128]
## Feature Request

Add http tracing to the htt_response plugin

### Proposal:

Golang 1.7 introduced the [net/http/httptrace](https://golang.org/pkg/net/http/httptrace/) which provides mechanisms to trace the events within HTTP client requests. This opens up the ability to get metrics for:
- dns lookup
- tcp connection
- tls handshake
- server processing
- content transfer

### Current behavior:

Current only retrieves information about total response time. 

### Desired behavior:

More fine grained metrics about a http request.

**Comment by powersj** [comment]
next steps: look into what this would require, great starter/first task
