### ISSUE TITLE
Field name from plugin can conflict with aggregator

### ISSUE THREAD

**Issue by Alan1810** [influxdata/telegraf#2130]
I'm using telegraf 1.1.1-1 (amd64) on ubuntu 14.04

haproxy metrics is enabled in telegraf configuration file :
_[[inputs.haproxy]]
servers = ["http://127.0.0.1:1936/haproxy?stats"]_

When telegraf is started, I have this error :
InfluxDB Output Error: {"error":"field type conflict: input field \"rate_max\" on measurement \"haproxy\" is type float, already exists as type integer"}

Can you help me to correct this error ?

**Comment by sparrc** [comment]
please provide more information. Did you recently upgrade telegraf? from what version? what version of influxdb are you using? did you recently upgrade influxdb? from what version?

**Comment by Alan1810** [comment]
I didn't made any upgrade. It was a fresh installation of telegraf and influxdb. The version of influxdb is 1.1.0-1 on ubuntu 16.04

**Comment by sparrc** [comment]
not really sure how that's possible, what does the data look like in influxdb?

**Comment by Alan1810** [comment]
This an export of haproxy series in json format.
[export_haproxy.json.zip](https://github.com/influxdata/telegraf/files/634310/export_haproxy.json.zip)

**Comment by sparrc** [comment]
why do you have so many `nil` fields in your measurements? are you sure that the data in influxdb is a "fresh" installation?

**Comment by Alan1810** [comment]
I've cleaned haproxy series before sending it to you. This is data from haproxy slave server. When haproxy metric is enabled, telegraf stop writing data to influxdb so i enable it, only for you.

This is new export with info from master and slave haproxy server.
[export_haproxy.json.zip](https://github.com/influxdata/telegraf/files/635878/export_haproxy.json.zip)

**Comment by sparrc** [comment]
@Alan1810 can you setup an `outputs.file` output printing to stdout? I need to see what the actual line-protocol is that telegraf is trying to send in order to debug.

**Comment by Alan1810** [comment]
This the log file.
[metrics.out.zip](https://github.com/influxdata/telegraf/files/636329/metrics.out.zip)

**Comment by sparrc** [comment]
@Alan1810 and at what point during this run did you get the error message? can you also provide your config file and the full error output from the telegraf logs?

**Comment by Alan1810** [comment]
I've tried to run each plugin one by one and I've found how to reproduce the error : when **aggregators.minmax** is enabled in telegraf.conf with **haproxy**, we have the error. When i disable aggregators.minmax but haproxy is enabled, everything is ok.
In zip file you will find telegraf.conf, telegraf.log and metrics.out
[telegraf.zip](https://github.com/influxdata/telegraf/files/636597/telegraf.zip)

**Comment by sparrc** [comment]
I think I see the issue. It is that the `haproxy` plugin already has both a `rate` and `rate_max` measurement. So then the aggregator attempts to create it's own `rate_max`, which is the max of the `rate` measurement.

TBH I'm not sure what the solution to this could be programatically. There are a few workarounds that I can think of:

1. you could add a prefix to all your aggregated measurements: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#aggregator-configuration
2. use the drop_original flag if you don't care about the original measurements
3. you can drop the `rate_max` field from `[[inputs.haproxy]]` (see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering)
4. you can drop the `rate` field from being aggregated (similar to (3))

**Comment by danielnelson** [comment]
I acknowledge that this is a gotcha but I don't think this is an issue we should attempt to fix in Telegraf.  I suggest using one of the workarounds in sparrc's comment.
