### ISSUE TITLE
Release 1.1.1 was re-tagged

### ISSUE THREAD

**Issue by woodruffw** [influxdata/telegraf#2140]
Could a maintainer at Telegraf confirm that the re-tag of `1.1.1` 24 days ago was intended? We package your program over at Homebrew, and the `sha256` of your tarball changed from `15b7a6ebb798b708f1d162f365f0347038db07b28661eb58817155251fb3e2e2` to `d6452e40ed78554499e9e423a11eadb51ed8c60568d82df114f346bb16f7cf4a`.

We (along with other package managers and mirrors) generally assume that versions are immutable once released, so please use a new minor number or some other indicator when a release goes wrong. 

Thanks!

**Comment by MikeMcQuaid** [comment]
> We (along with other package managers and mirrors) generally assume that versions are immutable once released, so please use a new minor number or some other indicator when a release goes wrong.

Additionally, Git also makes this assumption so `git fetch --tags` will refuse to overwrite existing tags.

**Comment by sparrc** [comment]
Not sure if this was intentional, but the current tag is what it should be

**Comment by MikeMcQuaid** [comment]
> Not sure if this was intentional, but the current tag is what it should be

@sparrc Could you elaborate a little on this? I'm probably being stupid but if you're unsure if a retag was intentional how can you be sure it is as intended? We (Homebrew) need to try and figure this out before we can fix our Telegraf package.

**Comment by sparrc** [comment]
IIRC I had to delete and re-tag as it was erroneously tagged by another developer trying to create a release via the UI.

Seems like someone updated the homebrew formula before we officially released 1.1.1. Guess there's nothing to stop someone doing that but we would prefer if people would wait for us to bless a tag before sending it out to the world. One of the drawbacks of OSS I guess...

**Comment by MikeMcQuaid** [comment]
Thanks @sparrc. How do we know when a tag is "blessed"?

**Comment by sparrc** [comment]
when it's up on https://influxdata.com/downloads, will try not to retag in the future

**Comment by MikeMcQuaid** [comment]
Thanks!
