### ISSUE TITLE
[Feature request] Add lock option to the IPtables input plugin

### ISSUE THREAD

**Issue by ldep30** [influxdata/telegraf#2144]
### Proposal:
Add an option allowing to pass the -w argument to the Iptables command called by the plugin

### Current behavior:
Iptables commands are launched without any lock argument

### Desired behavior:
Add an option like `use_lock = true|false` to the plugin configuration. If the option is set to true, then add `-w` to the Iptables arguments.

### Use case:
In our case, using multiple inputs.iptables plugins can lead to concurrent Iptables access resulting in "**ERROR in input [inputs.iptables]: exit status 4**" messages in telegraf.log and missing metrics. This can be partially fixed using collection_jitter = "3s" in the agent section of telegraf.conf, but this is not an ideal solution. The -w switch should solve the problem according to the Iptables man page :

> -w, --wait
>     Wait for the xtables lock. To prevent multiple instances of the program from running concurrently, an attempt will be made to obtain an exclusive lock at launch. By default, the program will exit if the lock cannot be obtained. This option will make the program wait until the exclusive lock can be obtained.

**Comment by sspaink** [comment]
Resolved by #2201
