### ISSUE TITLE
[Feature request] Add timestamps to webhooks github input plugin

### ISSUE THREAD

**Issue by sergiomss** [influxdata/telegraf#2148]
## Feature Request

Add time as a tag of the deployment and deployment status to the github webhooks input plugin.

### Proposal:

It would be useful to have the time we get in deployment and deployment_status event, to have the information about when the event happened rather than when we are getting the information from Github webhooks, as it may not be the same.

### Current behavior:

It get some of the fields we get from webhooks and add them to the output as tags and fields, but no timestamp.

### Desired behavior:

Using the deployment.created_at and deployment_status.created_at, we can get the information about when the deployment actually happened or the status changed. It could be added and sent as a tag to influxdb for example, or even replace the time column, as the time it was indexed may turn out to don't be of any use.

### Use case: 

To get more useful information out of Github webhooks, as it allows the possibility to calculate lead times for the deployments for example and get more information about when the events happened rather than when they were received.

**Comment by powersj** [comment]
Hi,

Sorry, no one has gotten back to you. 

Is this something still of interest to you? Do you have an example or know the name of the timestamp fields that you are looking for?

Thanks!
