### ISSUE TITLE
SNMP plugin behavior upon checksum error

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#2152]
**v:1.1.2**

Bad UDP checksums are a common case in the real networking world - either due to problematic NIC's or kernel bugs/cache failures.

I noticed the following behavior for the SNMP plugin in a network where bad UDP checksums occur:

```
SNMPget
    telegraf.49840 > active.hostname.snmp: [bad udp cksum 0xc05f -> 0xd256!]  { SNMPv2c C=omitted { GetRequest(28) R=1836986702  system.sysName.0 } } 

Telegraf
    telegraf.35467 > active.hostname.snmp: [bad udp cksum 0xc066 -> 0xc4a7!]  { SNMPv2c C=omitted { GetBulk(35) R=1206098808  N=0 M=5 E:1271.2.3.1.2.2.1.1.2 } }
```

The first line is the output of `snmpget -v2c -c omitted hostname .1.3.6.1.2.1.1.5.0`

The second line is Telegraf's actual snmp poll after encountering a UDP checksum error. Looks like it sends a GetBulk instead of GetRequest.

When the checksum is good:

```
SNMPget
    telegraf.net.35937 > remote.hostname.snmp:  { SNMPv2c C=omitted { GetRequest(28) R=1699114121  system.sysName.0 } } 

Telegraf
    telegraf.net.50535 > remote.hostname.snmp:  { SNMPv2c C=omitted { GetRequest(28) R=254610132  system.sysName.0 } } 
```

SNMP Config sample:

```
[[inputs.snmp]]
        interval = "30s"
        timeout = "10s"
        agents = [ "hostname" ]
        version = 2
        community = "omitted"
        max_repetitions = 5

name = "MyMeasurements"
[[inputs.snmp.field]]
  oid = ".1.3.6.1.2.1.1.5.0"
  name = "hostname"
  is_tag = true

[[inputs.snmp.field]]  
  oid = ".1.3.6.1.4.1.1271.2.1.5.1.2.1.4.5.1.4.1.31"
  name = "CPUUsedPercent_0"
```

1) I am not sure why Telegraf sends GetBulk in the case of bad UDP checksum, is this a bug?
2) It would be nice to support a configurable flag to ignore UDP checksum errors.

@phemmer thoughts?

**Comment by phemmer** [comment]
I'm not quite sure what you're reporting. The info you're providing seems to indicate you are seeing packets with an invalid checksum coming FROM telegraf. If the checksum is bad, that means either the checksum itself is corrupted, or the contents of the packet are corrupted. So the fact that whatever you're using to view the packet says it's a GetBulk request can't be trusted, as the packet is corrupt. If network is corrupting a packet that telegraf sends out, there's nothing telegraf can do here.

Am I misunderstanding something?

**Comment by kostasb** [comment]
@phemmer That is correct, the checksums coming FROM Telegraf have a bad checksum. So for datagrams with bad checksums, the snmp plugin fails with ` Error in plugin [inputs.snmp]: agent hostname: performing get: Request timeout (after 3 retries)` while the net-snmp `snmpget` tool succeeds. Additionally tcpdump shows the protocol code of GetBulk being used in the datagram, instead of GetRequest. It would be weird for the datagram to have everything in place other than the SNMP operation code which leads me to assume that a GetBulk is indeed being emitted instead of a GetRequest in this case. This is a potential bug in the soniah/gosnmp package rather than Telegraf's snmp plugin though, so I will close this issue and take it to that repo.
