### ISSUE TITLE
Provide docs on derivative items.

### ISSUE THREAD

**Issue by mabushey** [influxdata/telegraf#216]
Metrics like net_packets_sent and net_packets_recv look like a skateboard ramp. Figuring out how to graph this w/o docs is about as likely as winning the Lottery. Here is a query that actually appears works which I only obtained through Googling:

```
SELECT non_negative_derivative(first(value), 1s) FROM "net_packets_sent" WHERE "host" = 'server01' AND $timeFilter GROUP BY time($interval), "host" fill(none)
```

**Comment by sparrc** [comment]
:+1: I agree 100%, was actually planning on this being the topic of a blog post and doc page

**Comment by jhofeditz** [comment]
Thank you @mabushey! I had the derivative query close but the scale seemed off. Using your query made Grafana do exactly what I needed for counter based data from Telegraf.

Looking forward to seeing the proper query syntax for InfluxDB in the docs and Grafana supporting it in the editor.

**Comment by kokarn** [comment]
:+1: 
This would indeed be very helpful. 
I imagine bandwidth usage is a pretty common thing to display.

**Comment by sparrc** [comment]
closing this out because we will be able to support this sort of thing when we implement #380, and TBH there's no way I'm going to have time to get to this, as well as it probably being a bit out-of-scope from a telegraf perspective.
