### ISSUE TITLE
Zookeeper stats are not collected if first node fails

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2161]
## Bug report

If the first Zookeeper node in the service is down, no Zookeeper stats are collected.

### Relevant telegraf.conf:

[[inputs.zookeeper]]
    servers = ["server1", "server2", "server3"]

### System info:

* Telegraph 1.1.1-alpine container
* 3 node zookeeper cluster

### Steps to reproduce:

1. Start zookeeper cluster
2. Start telegraph and have output sent to <wherever>
3. Stop the first zookeeper node in the config.

### Expected behavior:

Metrics are still collected even though one of the nodes is down.

### Actual behavior:

No metrics are collected.

### Additional info:

Relevant log line:
E! ERROR in input [inputs.zookeeper]: dial tcp <ip_address>:2181 getsockopt: connection refused

**Comment by danielnelson** [comment]
This bug was fixed in #2372, included in Telegraf 1.3.0
