### ISSUE TITLE
HTTPJson GET fails if the response returns array of objects

### ISSUE THREAD

**Issue by sturakhia** [influxdata/telegraf#2162]
## Bug report
HTTPJson GET fails if the response returns array of objects with the error below 
"unable to parse out as JSON, json: cannot unmarshal array into Go value of type map[string]interface {}"

### Relevant telegraf.conf:
[[inputs.httpjson]]
  name = "mycollector"

  servers = [
    "http://myurl/get/metrics"
  ]

  # HTTP method to use (case-sensitive)
  method = "GET"

  # Set response_timeout (default 5 seconds)
  response_timeout = "5s"
[inputs.httpjson.headers]
    Authorization = "Basic something"

### System info:

Telegraf v1.1.1 

### Steps to reproduce:

1. Call any REST API with GET that returns array of objects

### Expected behavior:

Should be able to parse the JSON and let me access the objects by indices for instance [0].data 
or [0].data.metrics

### Actual behavior:
throws this exception "unable to parse out as JSON, json: cannot unmarshal array into Go value of type map[string]interface {}"

**Comment by sparrc** [comment]
version 1.2 will be able to parse arrays.

for more customization there's already an open issue: https://github.com/influxdata/telegraf/issues/1363
