### ISSUE TITLE
Cannot create database and write to it, even though i created it manually

### ISSUE THREAD

**Issue by critaL** [influxdata/telegraf#2164]
## Bug report
I am unable to send data collected from input.snmp to a influxdb database. Whenever i run the command "telegarf -config telegraf.conf" i get the following output:

_2016/12/14 21:04:01 E! Database creation failed: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value
2016/12/14 21:04:01 I! Starting Telegraf (version 1.1.1)
2016/12/14 21:04:01 I! Loaded outputs: influxdb
2016/12/14 21:04:01 I! Loaded inputs: inputs.diskio inputs.kernel inputs.mem inputs.processes inputs.swap inputs.system inputs.cpu inputs.disk
2016/12/14 21:04:01 I! Tags enabled: host=nuc.plex
2016/12/14 21:04:01 I! Agent Config: Interval:10s, Quiet:false, Hostname:"nuc.plex", Flush Interval:10s_

I have manually created the database telegraf using the admin page.
### Relevant telegraf.conf:
[[inputs.snmp]]
agents = [ "192.168.0.5:161" ]
timeout = "5s"
retries = 3
version = 2
community = "public"

[[inputs.snmp.field]]
name = "uptime"
oid = ".1.3.6.1.2.1.1.3.0"

[[outputs.influxdb]]
urls = ["http://localhost:8086"]
database = "telegraf"
retention_policy = "s"
write_concistency = "any"
timeout = "5s"

### System info:

OS: Ubuntu Server
Telegraf Version: 1.1.1
### Steps to reproduce:

1. Using the config above and running  the command "telegraf -config telegraf.conf" and using a influxdb database on port 8083 and 8086

### Expected behavior:

I expected it to write data to the database telegraf, pulling data from my ESXi server and input it into the database telegraf.

### Actual behavior:

The log is spewing out the above errors and the database telegraf does not receive any data.
### Additional info:

Collectd is able to send and collect data to influxdb succesfully. However, it should be noted that i am just getting started with using Grafana, influxdb and collectd/telegraf.

**Comment by sparrc** [comment]
I'm almost certain this is due to an incompatibility between your telegraf and InfluxDB version. What version of influxdb are you using?

**Comment by critaL** [comment]
Version 0.10.0

**Comment by sparrc** [comment]
in that case you need to upgrade influxdb or downgrade telegraf
