### ISSUE TITLE
No document for system-net plugin

### ISSUE THREAD

**Issue by aleung** [influxdata/telegraf#2166]
There is no readme file under https://github.com/influxdata/telegraf/tree/master/plugins/inputs/system to describe the net plugin.

**Comment by sparrc** [comment]
dupe, there's already an open issue to create READMEs for all plugins

**Comment by aleung** [comment]
Just find it #177

**Comment by danielnelson** [comment]
Reopening, I think individual tickets will be more less overwhelming at this time.
