### ISSUE TITLE
RabbitMQ connections causes cardinality explosion

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2168]
### Relevant telegraf.conf:
```
[[inputs.rabbitmq]]
  url = "http://localhost:15672"
```

### System info:

Telegraf master (17b307a)
CentOS/7

### Steps to reproduce:

1. Start telegraf

### Expected behavior:
Telegraf output should contain a relatively stable number of series.

### Actual behavior:
Telegraf outputs a new series every time a client connects to RabbitMQ because it has a tag called `connection` which contains the TCP tuple (client-ip + client-port + server-ip + server-port)

### Additional info:
Change introduced by #1908

**Comment by sparrc** [comment]
*sigh*, I'll revert #1908
