### ISSUE TITLE
Renaming field key using the tag value

### ISSUE THREAD

**Issue by sturakhia** [influxdata/telegraf#2173]
## Bug report
I have a use case where my REST API returns an array of objects. I want to rename the fields key by using the tag value.

### Relevant telegraf.conf:

```
[[inputs.httpjson]]

  fieldpass = ["data_0_value"]
  servers = [
    "http://something/api"
  ]

  # HTTP method to use (case-sensitive)
  method = "GET"
  tag_keys = ["name"]
  # Set response_timeout (default 5 seconds)
  response_timeout = "5s"
  
  [inputs.httpjson.headers]
    Authorization = "some key"
  [inputs.httpjson.tagpass]
    metricName = [ "age", "salary"] 
```

### System info:
Telegraf v1.1.1

[Include Telegraf version, operating system name, and other relevant details]
```json

[
{
"name": "age",
"data": [
{
"timestamp": 1481913358227,
"value": 15
},
"name": "salaray",
"data": [
{
"timestamp": 1481913358227,
"value": 15445
},
]
}
]
```
In this case both my metrics have same field names called data_0_value
{"fields":{"data_0_value":5},"name":"metrics_collector","tags":{"name":"age","node":"test-shweta","server":"http://ip/something"},"timestamp":1481916850}
{"fields":{"data_0_value":5},"name":"metrics_collector","tags":{"name":"salary","node":"test-shweta","server":"http://ip/something"},"timestamp":1481916850}

When I publish these metrics to cloud watch, it cannot differentiate between age and salary as both metrics are reported under data_0_value. 

### Steps to reproduce:

Call any REST API with GET that returns array of objects

### Expected behavior:
I should be able to set the fieldname according to the tag value
### Actual behavior:
Both the metrics are printed with same field name

**Comment by sparrc** [comment]
sorry but this use-case is too esoteric for general use. See #1363
