### ISSUE TITLE
Multiple SNMP hosts documentation

### ISSUE THREAD

**Issue by sbrooke** [influxdata/telegraf#2174]
The documentation for the SNMP plugin does not include references to configuring multiple hosts that use different SNMP versions or authentication methods.  Multiple hosts using the same configuration is referenced.

**Comment by sparrc** [comment]
you just need to create multiple [[inputs.snmp]] instances in your config file

**Comment by Jugulaire** [comment]
This is does not help us, can you please provide a example ? 
It's does not work on my telegraf with multiples inputs ...

**Comment by danielnelson** [comment]
@Jugulaire With any input plugin you can define it multiple times in the config file, here is an example using the cpu plugin: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#multiple-inputs-of-the-same-type
