### ISSUE TITLE
LogParser exclude

### ISSUE THREAD

**Issue by ibeals** [influxdata/telegraf#2176]
Grok pattern currently does not allow exclusions, or at least not documented.

### System info:
Telegraf version 1.1

### Relevant telegraf.conf:
Custom pattern

`%{SYSLOGTIMESTAMP:event_time}%{SPACE}%{PROG:source}%{SPACE}%{DATA:process}:%{SPACE}PHP%{SPACE}%{DATA:severity}:%{SPACE}%{DATA:problem}%{SPACE}in%{SPACE}%{UNIXPATH:context}%{SPACE}on%{SPACE}line%{SPACE}%{NUMBER:linenumber}`

### Desired behavior:
The pattern above is a way to gather PHP runtime errors from our log. There are some lines we would like to exclude. We want to write the log lines down but don't want Telegraf to off-site some of the log entries. If there is a work around for now, I'm open to trying.

**Comment by ibeals** [comment]
Any insights?

**Comment by sparrc** [comment]
unfortunately Golang's regex library doesn't support lookahead/lookbehind, which I believe is the problem here, see http://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions

can you provide your full regex pattern and an example log line that you want & don't want?

**Comment by danielnelson** [comment]
@ibeals Is this still an issue for you?

**Comment by zabudskyi** [comment]
So how can we exclude some logs from being parsed and recorded to influxdb? 
We can match undesirable strings with other pattern but then we can use drop option per field only. Or should I try to drop all fields? 

F.e. I don' want this log to be recorded to influxdb
2018-03-01 11:07:29 3 pdns[9475]: PowerDNS Security Update Mandatory: Upgrade now, see https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2017-04.html
My pattern 
```
%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint} %{SYSLOGPROG:logtag}: 
 %{GREEDYDATA:message}
```
```
LEVELINT [0-3]
```

**Comment by danielnelson** [comment]
How you decide that if is a line you don't want?  Is it based on logtag?

**Comment by zabudskyi** [comment]
It is based on message itself `Some powerdns message`

**Comment by danielnelson** [comment]
In this specific case I would probably move levelint and logtag to tags, and then do fielddrop on message, this would then be the only field so that should remove the metric:
```
%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint:tag} %{SYSLOGPROG:logtag:tag}: %{GREEDYDATA:message}
```

By moving the logtag to a tag, you could also tagdrop the entire metric fairly easy based on program, if that's something you end up needing later.

Let me know if this works for you.

**Comment by zabudskyi** [comment]
I tried both fielddrop and tagdrop (though I really need to drop logs based on the field message) but log still appears in influxdb
```
[[outputs.influxdb]]
.....
  [outputs.influxdb.tagdrop]
    program = ["pdns"]
```
```
[[inputs.logparser]]
  files = ["/var/log/syslog"]
  from_beginning = false
  fielddrop = ["Some powerdns message"]

  [inputs.logparser.grok]
   patterns = ['%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint:tag} %{SYSLOGPROG:logtag:tag}: %{GREEDYDATA:message}']
   measurement = "syslog"
   custom_patterns = '''
     LEVELINT [0-3]
   '''
```
Does `%{SYSLOGPROG:logtag:tag}` mean I have tags for `program` and `pid` as well?

I tried to place `fielddrop` inside `inputs.logparser.grok` but than I get `Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.`
Thanks in advance

**Comment by danielnelson** [comment]
> Does %{SYSLOGPROG:logtag:tag} mean I have tags for program and pid as well?

No, these are still fields, which explains why dropping the message would not be sufficient to remove the entire line.

Both fieldpass and fielddrop operate only the field key, so they cannot be used to filter out specific messages.  We don't currently have a way to filter based on field value, but we could create a feature request.

Looking closer at the output I would recommend removing the tag from `logtag`, it is going to create too many series due to the pid being part of it.

Instead it would be better to redefine [SYSLOGPROG](https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns#L83) to make `program` a tag and then your above tagdrop should work:
```
  [inputs.logparser.grok]
   patterns = ['%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint:tag} %{MYSYSLOGPROG:logtag}: %{GREEDYDATA:message}']
   measurement = "syslog"
   custom_patterns = '''
     LEVELINT [0-3]
     MYSYSLOGPROG %{PROG:program:tag}(?:\[%{POSINT:pid}\])?
'''
```

**Comment by zabudskyi** [comment]
It looks like I achieved what I wanted (drop not whole program logs but defined) with this configuration
```
  [inputs.logparser.grok]
   patterns = ['%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint:tag} %{PROG:program:tag}(?:\[%{POSINT:pid:drop}\])?: Some powerdns%{GREEDYDATA:message:drop}',
               '%{TIMESTAMP_ISO8601:ts:ts-"2006-01-02 15:04:05"} %{LEVELINT:levelint:tag} %{MYSYSLOGPROG:logtag}: %{GREEDYDATA:message}']
   measurement = "syslog"
   custom_patterns = '''
     LEVELINT [0-3]
     MYSYSLOGPROG %{PROG:program:tag}(?:\[%{POSINT:pid}\])?
   '''
```
So now in influxdb I get records with log messages `Pome powerdns message` but not with `Some powerdns message`. 
I had to add explicitly `%{PROG:program:tag}(?:\[%{POSINT:pid:drop}\])?` to pattern as it didn't drop log when I used something like `%{MYSYSLOGPROG:drop}` or adding `drop` to `pid` in `MYSYSLOGPROG` in custom patterns seciton. So now I can add more messages to filter in patterns list before "allow pattern".
Though filtering based on fielddrop looked better. Should I create feature request?

**Comment by danielnelson** [comment]
> Should I create feature request?

Yes, are you thinking about an option that removes a field based on value or an option that removes an entire metric based on a field value?  Either way or even both would be good.

**Comment by zabudskyi** [comment]
I added feature request. I notice dropping all fields causes error messages in telegraf.log file. So for my use case second option probably sounds better.
Thank in advance.
