### ISSUE TITLE
Is that possible to output an aggregator result to another aggregator?

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#2177]
The aggregator in the newest framework is very helpful for data cleaning.

Sometimes I need several levels of aggregators to clean the data. In this case, I do not push the data back and forth to Kafka. I want the output of an aggregator is just another aggregator.

Is that possible or is that under planning? If it is not, I would just suggest it.

**Comment by sparrc** [comment]
This is not possible at the moment and there are no plans to implement it. Aggregate metrics _do_ pass through processor plugins though.

Why not just do your multiple levels of aggregation within a single plugin?

**Comment by danielnelson** [comment]
Closing since we are not planning to implement this.
