### ISSUE TITLE
Client doesn't follow HTTP redirections

### ISSUE THREAD

**Issue by Appeltabak** [influxdata/telegraf#2191]
## Bug Report
(I'm not sure whether this issue is a bug or a feature, or a responsibility of Telegraf at all)

Currently, I have several Telegraf instances running that send their data to InfluxDB using plain HTTP. Now I want that on HTTPS, so I configured my web server to redirect HTTP requests to HTTPS. Unfortunately, Telegraf can't connect to InfluxDB and logs suggests that doesn't redirect the requests (see Additional Info).

Reconfiguring all Telegraf instances to use the HTTPS url would solve my insecure connection problem, but involves a lot of work as opposed to redirect the HTTP url.

### System info:
Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)
using official Docker image `telegraf:1.1`

### Steps to reproduce:
1. Run a web server that redirects a HTTP connection to a HTTPS connection.
2. Run InfluxDB behind the configured HTTPS connection.
3. Run Telegraf, configured to send the metrics to InfluxDB over HTTP

### Expected behavior:
Following the redirection so it's able to send the data InfluxDB

### Actual behavior:
Fail to connect and send to InfluxDB

### Additional info:
```
016/12/21 12:48:29 I! Using config file: /etc/telegraf/telegraf.conf
2016/12/21 12:48:29 E! Database creation failed: received status code 301 from server
2016/12/21 12:48:29 I! Starting Telegraf (version 1.1.1)
2016/12/21 12:48:29 I! Loaded outputs: influxdb
2016/12/21 12:48:29 I! Loaded inputs: inputs.system inputs.cpu inputs.disk inputs.diskio inputs.kernel inputs.mem inputs.processes inputs.swap
2016/12/21 12:48:29 I! Tags enabled: host=3fea1132ac56
2016/12/21 12:48:29 I! Agent Config: Interval:10s, Quiet:false, Hostname:"3fea1132ac56", Flush Interval:10s 
2016/12/21 12:48:40 I! Output [influxdb] buffer fullness: 45 / 10000 metrics. Total gathered metrics: 45. Total dropped metrics: 0.
2016/12/21 12:48:40 E! Database creation failed: received status code 301 from server
2016/12/21 12:48:40 E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
^C2016/12/21 12:48:42 I! Hang on, flushing any cached metrics before shutdown
2016/12/21 12:48:42 I! Output [influxdb] buffer fullness: 45 / 10000 metrics. Total gathered metrics: 45. Total dropped metrics: 0.
2016/12/21 12:48:42 E! Database creation failed: received status code 301 from server
2016/12/21 12:48:42 E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```

**Comment by lsmith-carecloud** [comment]
@ Appeltabak I'm still learning Go ( disclaimer) but I took a look at Telegraf and the InfluxDB client code, and they use net/http under the covers. Looking at things (https://tools.ietf.org/html/rfc7231#section-6.4.2)   I think you might be hitting "      Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.
"   I haven't had a chance to spin up anything and test or look more into how net/http handles it, but you might try changing your server to return a 307 or a 308 and see if that works.

**Comment by lrsmith** [comment]
@Appeltabak I've been looking into this and tracing through the code and RFCs. I think the root issues is that the HTTP calls are POST and the W3 standards do not recommend 'blind' redirects, for posts without informing the user. https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html, look at the '10.3.2 301 Moved Permanently'.  The underlying Influxdata code uses net/http and i've been going through the docs and testing. It looks like the net/http does not support the redirect for PUTs.  It would probably be better, from a security perspective, for the clients to get the error and the end-user have to update their config rather than redirect. I'm still learning Go and find this interesting so I'll see about writing an option to allow for detecting redirects and following it. The code change would be with the InfluxDB/Client/v2 code ( https://github.com/influxdata/influxdb/blob/master/client/v2/client.go) which looks to be used by Telegraf. If I do get it written i'll submit a PR but it might not get merged because it can be a security issue.

**Comment by lrsmith** [comment]
https://github.com/influxdata/influxdb/pull/7803 has updates to the influxDB client code to support the insecure behavior of following Redirects.  Once that has been approved and merged in https://github.com/influxdata/telegraf/pull/2239 can be pulled in for tests and then you would be able to specify the 'InsecureFollowRedirect' behavior which will use  a GET command to check for a redirect and follow and update the connection string. It will also log to the logs a warning that insecure behavior of following a redirect is being done.

**Comment by lrsmith** [comment]
The influxDB team has rejected the PR (influxdata/influxdb/pull/7803) that /influxdata/telegraf/pull/2239 depends on. I've closed PR 2239.  While it might be possible to put the logic into Telegraf, it really removes it from the connecting logic in the influxdb client and net/http. 

It would be better to just update the telegraf client with the correct server URL and not rely on the redirect for the puts/posts.

**Comment by sparrc** [comment]
I'd prefer that as well, closing this issue
