### ISSUE TITLE
Add custom unit information while publishing to cloud watch

### ISSUE THREAD

**Issue by sturakhia** [influxdata/telegraf#2194]
## Bug report

I am capturing metrics by calling a web service and I use the http json for input plugin and publish these metrics to cloud watch. The metrics is published fine but the unit information is missing. The REST API response doesnt have the unit information, but I can harcode the unit name in the input config if needed. Is there a way I can send the unit name through configuration ?

When I use the [[inputs.cpu]] cpu plugin, looks like it is somehow sending the unit information as cloud watch has the Unit as Percent.
 
### System info:

Telegraf v1.1.1

### Steps to reproduce:

Call a REST API that sends cpu and disk percentage but does not have unit information.

### Expected behavior:
If I can manually push the unit information

### Actual behavior:
Currently the unit is None

**Comment by sparrc** [comment]
I don't understand what you want to do. Is there a `unit` built-in to cloudwatch? can you link to documentation on that?

**Comment by sturakhia** [comment]
Cloudwatch supports different units http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html
So, when we publish the metrics, I was wondering if we have a way to specify that. In CPU plugin, it looks like we are sending the unit as Percent.

**Comment by sjwang90** [comment]
Closing this issue since it has been a few years and not much other interest. Feel free to re-open if this a feature you would still like. If so, we welcome a PR for the enhancement.
