### ISSUE TITLE
[Feature request] Override tags with http_listener

### ISSUE THREAD

**Issue by Lestat-GitHub** [influxdata/telegraf#2199]
Hi,

Is that possible to add an option to the http_listener plugin to override the tags with the ones from
the main configuration ?

For example, if I push data to the http_listener without a "host" tag, the one from the main configuration
will be taken and any other declared tags.

Adding an option to keep the current behavior or to override tags would be very useful.

Thanks.

**Comment by sparrc** [comment]
in the [agent] config section there is an option to omit the `host` tag, this would be your best option in this case.
