### ISSUE TITLE
[Feature request] ZFS ZIL stats

### ISSUE THREAD

**Issue by dkruyt** [influxdata/telegraf#2200]
**Feature Request:**

I am missing in the ZFS stats the zil part? Can this be added, should be simple enough.

cat /proc/spl/kstat/zfs/zil
7 1 0x01 13 624 8442537458 1281827806915735
name                            type data
zil_commit_count                4    1616838
zil_commit_writer_count         4    1615645
zil_itx_count                   4    12602884
zil_itx_indirect_count          4    456763
zil_itx_indirect_bytes          4    32162774452
zil_itx_copied_count            4    0
zil_itx_copied_bytes            4    0
zil_itx_needcopy_count          4    10925191
zil_itx_needcopy_bytes          4    99819412006
zil_itx_metaslab_normal_count   4    0
zil_itx_metaslab_normal_bytes   4    0
zil_itx_metaslab_slog_count     4    2243985
zil_itx_metaslab_slog_bytes     4    102213224336

**Comment by tomtastic** [comment]
I'll take a look at this.

**Comment by tomtastic** [comment]
This is ready to merge, enjoy.

**Comment by danielnelson** [comment]
I believe this feature was added in https://github.com/influxdata/telegraf/pull/3565
