### ISSUE TITLE
No output with rabbitmq plugin on Debian

### ISSUE THREAD

**Issue by xandreklein** [influxdata/telegraf#2202]
### Relevant telegraf.conf:
[global_tags]
[agent]
  interval = "300s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false 
  quiet = false
  hostname = "myhostr"
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  username = "influxdbmonitor"
  password = "toutoutou"
  database = "influx" # required
  precision = "ns"
  retention_policy = "one_year"
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.rabbitmq]]
  url = ["http://localhost:15672"]
  username = "guest"
  password = "guest"
### System info:
Linux FI012107 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux

Installed rabbitmq-server and enabled management plugin.

rabbitmqctl status
Status of node rabbit@FI012107 ...
[{pid,9483},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.3.5"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.3.5"},
      {webmachine,"webmachine","1.10.3-rmq3.3.5-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.3.5-git680dba8"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.3.5"},
      {rabbit,"RabbitMQ","3.3.5"},
      {os_mon,"CPO  CXC 138 46","2.3"},
      {inets,"INETS  CXC 138 49","5.10.3"},
      {mnesia,"MNESIA  CXC 138 12","4.12.3"},
      {amqp_client,"RabbitMQ AMQP Client","3.3.5"},
      {xmerl,"XML parser","1.3.7"},
      {sasl,"SASL  CXC 138 11","2.4.1"},
      {stdlib,"ERTS  CXC 138 10","2.2"},
      {kernel,"ERTS  CXC 138 10","3.0.3"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:8:8] [async-threads:30] [kernel-poll:true]\n"},
 {memory,
     [{total,41991592},
      {connection_procs,5408},
      {queue_procs,19360},
      {plugins,460032},
      {other_proc,13744960},
      {mnesia,62232},
      {mgmt_db,70320},
      {msg_index,34288},
      {other_ets,1087008},
      {binary,112416},
      {code,20367344},
      {atom,711569},
      {other_system,5316655}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,13366547251},
 {disk_free_limit,50000000},
 {disk_free,9059610624},
 {file_descriptors,
     [{total_limit,924},{total_used,3},{sockets_limit,829},{sockets_used,1}]},
 {processes,[{limit,1048576},{used,191}]},
 {run_queue,0},
 {uptime,2294}]
...done.

netstat on port 15672:
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      125        39489593    9483/beam.smp  

### Steps to reproduce:
telegraf --config /home/alex/telegraf/rabbitmq_telegraf.conf -test -input-filter rabbitmq

### Expected behavior:
Having telegraf metrics
### Actual behavior:
No output, even with the --debug param
I can acces the rabbitmq api with my browser or curl.

**Comment by sparrc** [comment]
using the --test flag specifically doesn't send data to outputs
