### ISSUE TITLE
[feature request] Include process uptime in procstat plugin output

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/telegraf#2203]
### Proposal

Have the `procstat` input plugin collect a process uptime integer field for each tracked process.

### Current behavior

Uptime is not included in the `procstat` plugin output.

### Desired behavior

Uptime is included in the `procstat` plugin output.

### Use case

This would be very helpful in determining how often a process is restarted, or how long a process has been running.

**Comment by MikeMcMahon** [comment]
are there any current workaround to this issue?

**Comment by voiprodrigo** [comment]
I may give this a try, I’m interested in having this metric in procstat

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielnelson** [comment]
Might be some overlap with https://github.com/influxdata/telegraf/pull/3895

**Comment by prashanthjbabu** [comment]
I've made a quick PR that specifically address this issue https://github.com/influxdata/telegraf/pull/7039 . Hopefully this can get in quick so we can leverage this!
