### ISSUE TITLE
 cannot use func literal as type inputs.Creator in argument to inputs.Add

### ISSUE THREAD

**Issue by irom77** [influxdata/telegraf#2207]
I forked telegraf and working on my Input plugin ['pan_qosthroughput'](https://github.com/IrekRomaniuk/telegraf/tree/master/plugins/inputs/pan_qosthroughput) , but getting error below, please advice

```
go test
# github.com/IrekRomaniuk/telegraf/plugins/inputs/pan_qosthroughput
.\pan_qosthroughput.go:104: cannot use func literal (type func() "github.com/irekromaniuk/telegraf".Input) as type inputs.Creator in argument to inputs.Add
```

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
