### ISSUE TITLE
MongoDB without SSL

### ISSUE THREAD

**Issue by gallart** [influxdata/telegraf#2209]
## Bug report

Mongodb telegraf input seems to require SSL. Could not find any documentation on how to disable SSL.

### Relevant telegraf.conf:

```
# MONGO
[[inputs.mongodb]]
  servers = ["mongodb://login:password@127.0.0.1:27017"]
  gather_perdb_stats = false
```

### System info:

- Gentoo Linux
- Telegraf 1.1.2
- Mongo 2.6.12

### Steps to reproduce:

1. `./telegraf -config telegraf.conf -test -input-filter mongodb`

### Expected behavior:

Result of mongodb stats.

### Actual behavior:

```
error dialing over ssl, server returned error on SASL authentication step: Authentication failed.
2016/12/29 14:40:22 Errors encountered: [Unable to connect to MongoDB, server returned error on SASL authentication step: Authentication failed.
```

Thanks,

Gaëtan

**Comment by sparrc** [comment]
your connection is failing because the user/password is wrong, it is not actually using SSL, the log message is simply wrong.

Fix for this is to delete the fmt.Printf here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb.go#L131-L133
