### ISSUE TITLE
WinPerf Input Plugin Problems with multiple process instances

### ISSUE THREAD

**Issue by githubmui** [influxdata/telegraf#2210]
Hi,

e.g. if Notepad is started three times, then the instances are name  "Notepad", "Notepad#1" and "Notepad#2" (Can be seen in PerfMon).
In this situation it seems not possible to get only the "Process" performance counters of instance "Notepad#2".

[[inputs.win_perf_counters]]
   [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = ["ID Process","% Processor Time","Handle Count","Thread Count"]
    Instances = ["Notepad#2"]
    Measurement = "win_proc"

-> QUESTION 1) Is there a way to overcome this problems?

Even when ' Instances=["*"] ' is configured the instances are listed but can not be identified anymore.
With configuration ' Instances=["*"] ' I got a further problem: hundreds of unnecessary process data where returned which repeatedly needed quite a lot of time.

-> QUESTION 2) Is there a possibility to get only Notepad instances e.g. with a filter like ' Instance = ["Notepad*"] '?

Thank you in advance for help.

**Comment by danielnelson** [comment]
@githubmui I believe this has been fixed by #1827.

**Comment by aventrax** [comment]
This is not working on 1.3.2 as detailed on #2879
