### ISSUE TITLE
snmp cant convert watts to int (snmp returns value with W string)

### ISSUE THREAD

**Issue by ppanula** [influxdata/telegraf#2211]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

conversion to convert returned SNMP value with W to integer.

my config:

```
[[inputs.snmp]]
  agents = [ "1.2.3.4" ]
  version = 1
  community = "public"
  interval = "60s"

  name = "bladecenter"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "pd1Power"
    oid = "BLADE-MIB::pd1ModuleAllocatedPowerCurrent.24"
    conversion = "int"

```
### Current behavior:

IBM BladeCenter H returns SNMP values as string and adds W to value. like:

```
snmpwalk -v1 -c community hostname pd1ModuleAllocatedPowerCurrent.24
BLADE-MIB::pd1ModuleAllocatedPowerCurrent.24 = STRING: "887W"
```

and conversion = int cant convert it to integer, it allways returns 0i.

### Desired behavior:
to get conversion to convert watts values to integer

### Use case: [Why is this important (helps with prioritizing requests)]
So we can get and analyse power usage from IBM BladeCenter H.

**Comment by toni-moreno** [comment]
Hi @ppanula for doing so you need to specify some kind of string parser and I think telegraf is not ready to do so.

Feel free to test the new snmpcollector which can do this and much more as you can see in this issue this  https://github.com/toni-moreno/snmpcollector/issues/51 you sould only define the metric as STRING EVAL and put the correct REGEXP to parse

![image](https://cloud.githubusercontent.com/assets/5883405/21566027/2a9c999e-ce9f-11e6-93be-5bd400859ee2.png)

Feel free to test it!

**Comment by danielnelson** [comment]
This can be done in Telegraf >=1.7 using the regex processor.
