### ISSUE TITLE
elasticsearch plugin:cluster_stats is not defined in `*elasticsearch.Elasticsearch'

### ISSUE THREAD

**Issue by hivefans** [influxdata/telegraf#2217]
my input plugin elasticsearch config is 
    [[inputs.elasticsearch]]
   servers = ["http://192.168.1.120:9200"]
   http_timeout = "10s"
   local = false
   cluster_health = true
   cluster_stats = true

telegraf could not start , error log message is

E! Error parsing telegraf.d/elasticsearch.conf, line 6: field corresponding to `cluster_stats' is not defined in `*elasticsearch.Elasticsearch'

**Comment by sparrc** [comment]
that option is not yet supported in whatever version of telegraf you're using, I believe it will be available in 1.2, see https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md
