### ISSUE TITLE
Ceph pgmap state should use tags, not field names

### ISSUE THREAD

**Issue by j-vizcaino** [influxdata/telegraf#2224]
## Bug report

Ceph input for Telegraf uses field names to count the number of PG statuses and this is really not practical. Building graphs is tedious as the user needs to create a line graph for every field name, instead of the group by tag traditional approach.

### System info:

Telegraf 1.1.1
Ceph 0.94 (Hammer)

### Steps to reproduce:

1. run telegraf with ceph input enabled and cluster stats enabled
2. inspect the contents of the `ceph_pgmap_state` serie

### Expected behavior:

Unique field name, with tag to differenciate the values

```
field_name      value       tag
count           123         state=active+clean
count           3           state=active+clean+scrubbing
```

### Actual behavior:

Multiple field names (one for each pgmap_state)

```
field_name               value
active+clean             123
active+clean+scrubbing   3
```

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/2229
