### ISSUE TITLE
Core Dump on ARM device running Cumulus Linux 3.2.0 ( Debian Jessie )

### ISSUE THREAD

**Issue by cookiesowns** [influxdata/telegraf#2226]
Getting a Core Dump with the following message
```
Core was generated by `telegraf'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00052c34 in runtime.check () at /usr/local/go/src/runtime/runtime1.go:152
152     /usr/local/go/src/runtime/runtime1.go: No such file or directory.
```

Device is a Edge-Core AS4610 running Cumulus Linux 3.2.0 which is based off debian jessie. CPU's are ARM Cortex A9's

Using the default apt-get repository for debian jessie from InfluxDB.

Go Runtime is not installed on this device, but I didn't seem to need to on other devices.

**Comment by sparrc** [comment]
sorry but I'm going to close this because there are no plans to support any more ARM devices than we already do
