### ISSUE TITLE
Don't create the Influx DB on start up.

### ISSUE THREAD

**Issue by jregovic** [influxdata/telegraf#2231]
## Feature Request

Opening a feature request kicks off a discussion.

Proposal: Add a configuration option on the InfluxDB output to NOT create the database

Current behavior: At start up, telegraf attempts to create the database, even if it exists

Desired behavior: Include a configuration option to skip this step.

**Comment by sparrc** [comment]
Why do you need this? What is the use case?

**Comment by sparrc** [comment]
closing for lack of updates
