### ISSUE TITLE
Jolokia Input plugin should be allowed to specify the name prefix

### ISSUE THREAD

**Issue by djjorjinho** [influxdata/telegraf#2241]
Right now the jolokia input plugin prefixes all metrics with a "jolokia" string.
I haven't seen anything in the config to change this, it's probably hardcoded in the code.

Is there any way we can change this and allow to configure the prefix to something else (i.e. an empty string)?

**Comment by sparrc** [comment]
you can use `name_override`, see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md

**Comment by djjorjinho** [comment]
I added the field as so

`
[[inputs.jolokia]]
  override_name = ""
  context = "/jolokia/read"
...
`

And I got the following error while testing

`
2017-01-09 10:14:49 daniellopes@ip-....:/etc/telegraf/telegraf.d$ telegraf --config-directory . --test --debug
2017/01/09 10:14:51 I! Using config file: /etc/telegraf/telegraf.conf
2017/01/09 10:14:51 E! Error parsing service_xyz.conf, line 18: field corresponding to 'override_name' is not defined in '*jolokia.Jolokia'
`

**Comment by sparrc** [comment]
spelling

**Comment by djjorjinho** [comment]
Thanks :P
