### ISSUE TITLE
Merge Cassandra plugin into jolokia

### ISSUE THREAD

**Issue by mainvoid** [influxdata/telegraf#2242]
## Feature Request

Merge Cassandra plugin into the jolokia input plugin.

### Proposal:

I would love to see the Cassandra plugin merge with the jolokia plugin, minus lines 270 to 280. Why would I love that then? Because, with the jolokia plugin one gets to create several sections for each metric to be gathered. It explodes the configuration file massively if one wants to gather more than a couple of metrics. Now, both the cassandra plugin and the jolokia plugin does the same thing, in a sense, as they both connect into the jolokia agent and grabs metrics from there. However, the jolokia plugin has one other drawback, which is to enforce a prefix of "jolokia" *unless* one overrides the metric name. I am not sure I understand the logic behind that. It is also a much more simplistic plugin which lacks features this plugin has, like field_drop, name_drop etc. etc. etc. As the Cassandra plugin does the same basic job, but in a much more flexible and user friendly manner. 

Only reason I can see it currently won't do anything else but Cassandra is what resides in the lines 270-280, where a metric has to match java.lang or org.apache.cassandra.metrics. If that restriction was removed, it would do exactly the same job, just in a more friendly manner. Adding in a few lines from the jolokia plugin, allowing reading of existing "inputs.jolokia" style configuration files would then allow a merge to happen and retaining existing configuration files.

### Current behavior:

See proposal.

### Desired behavior:

See proposal.

### Use case: [Why is this important (helps with prioritizing requests)]

Simplifies configuration. Makes configuration more flexible and accurate. Less code to maintain. One plugin to do the job of the current two. Less headaches for new adopters.

**Comment by sparrc** [comment]
what plugin are you talking about? was this supposed to be a PR?

**Comment by mainvoid** [comment]
DOH. I was on the C* plugin page when I wrote it, which made me miss out context in the feature request. Updated above.

**Comment by mainvoid** [comment]
From 2014:

> [[inputs.jolokia.metrics]]
  name = "handlers"
  mbean = "solr/*:id=org.apache.solr.handler.*,type=*"
  attribute = "requests"
[[inputs.jolokia.metrics]]
  name = "memory"
  mbean = "java.lang:type=MemoryPool,name=*"
  attribute = "Usage,UsageThreshold"

2 metrics... 8 lines

From my cassandra config:

>  8   metrics = [   "/java.lang:type=GarbageCollector,name=ConcurrentMarkSweep/CollectionTime",
  9         "/java.lang:type=GarbageCollector,name=ConcurrentMarkSweep/CollectionCount",
 10         "/java.lang:type=GarbageCollector,name=ParNew/CollectionTime",
 11         "/java.lang:type=GarbageCollector,name=ParNew/CollectionCount",
 12         "/java.lang:type=Memory/NonHeapMemoryUsage",
 13         "/java.lang:type=Memory/HeapMemoryUsage",
 14         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=TotalLatency",
 15         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=TotalLatency",
 16         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency",
 17         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency",
 18         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Timeouts",
 19         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Timeouts",
 20         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Unavailables",
 21         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Unavailables",
 22         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Failures",
 23         "/org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Failures",
 24         "/org.apache.cassandra.metrics:type=CommitLog,name=TotalCommitLogSize",
 25         "/org.apache.cassandra.metrics:type=Compaction,name=PendingTasks",
 26         "/org.apache.cassandra.metrics:type=Compaction,name=BytesCompacted",
 27         "/org.apache.cassandra.metrics:type=Storage,name=Exceptions",
 28         "/org.apache.cassandra.metrics:type=Connection,name=TotalTimeouts",
 29         "/org.apache.cassandra.metrics:type=Storage,name=Load"
 30         ]

22 lines, 21 metrics.

In the example of Jolokia plugin configuration syntax, the above would become 21*4 lines, not considering any other settings we may possibly want to have. For example, jolokia plugin adds a prefix to every metric, which has to be overridden for every single metric, making the above 21*5, or 105 lines of configuration, with no whitespacing between each section.

Add in that one may then also want to add tags to data points, adding another few lines, per metric.

It gets messy, exponentially messy. I'd be happy to share configuration files, or even create something for both plugins.

If we then continue and look at what appears to be features each plugin should have, such as whitelisting and blacklisting features. 

Dropping stuff is equally easy.
> fielddrop = ["*_RateUnit", "*_EventType", "*_LatencyUnit", "*DurationUnit"]

Done.

Our only problem with using this C* plugin with other metrics is contained in the lines 270 to 280, effectively limiting what metrics it'll gather and discards the rest. 

My proposal is simply to remove those lines and create a new plugin from the result, be it "jolokia2" or any other suitable name.

**Comment by sparrc** [comment]
@mainvoid what is C*?

**Comment by mainvoid** [comment]
Short for Cassandra. :)

**Comment by sparrc** [comment]
I'm going to close this because https://github.com/influxdata/telegraf/pull/2278 is superseding it.
