### ISSUE TITLE
Why telegraf sum history input-data which is following to statsd?

### ISSUE THREAD

**Issue by zh4af** [influxdata/telegraf#2243]
### Relevant telegraf.conf:
    205 # Statsd Server
    206 [[inputs.statsd]]
    207   ## Address and port to host UDP listener on
    208   service_address = ":8125"
    209   ## Delete gauges every interval (default=false)
    210   delete_gauges = false
    211   ## Delete counters every interval (default=false)
    212   delete_counters = false
    213   ## Delete sets every interval (default=false)
    214   delete_sets = false
    215   ## Delete timings & histograms every interval (default=true)
    216   delete_timings = true
    217   ## Percentiles to calculate for timing & histogram stats
    218   percentiles = [90]
    219 
    220   ## separator to use between elements of a statsd metric
    221   metric_separator = "_"
    222 
    223   ## Parses tags in the datadog statsd format
    224   ## http://docs.datadoghq.com/guides/dogstatsd/
    225   parse_data_dog_tags = false
    226 
    227   ## Statsd data translation templates, more info can be read here:
    228   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite
    229   # templates = [
    230   #     "cpu.* measurement*"
    231   # ]
    232 
    233   ## Number of UDP messages allowed to queue up, once filled,
    234   ## the statsd server will start dropping packets
    235   allowed_pending_messages = 10000
    236 
    237   ## Number of timing/histogram values to track per-measurement in the
    238   ## calculation of percentiles. Raising this limit increases the accuracy
    239   ## of percentiles but also increases the memory usage and cpu time.
    240   percentile_limit = 1000

### System info:
telegraf version: 1.1.1
influxdb version: 1.1.0
os: centos 6.3

### Architecture of system:

telegraf + influxdb + grafana

### Expected behavior:
It display the actual value of the metrics in time series;

### Actual behavior:
It display the sum of history data value, it growth higher and higher.
When I restart the telegraf service, the metrics value is down to 0. 
The display pic is below:

![image](https://cloud.githubusercontent.com/assets/16952722/21764921/a28e0d94-d6a0-11e6-96ee-2a4761bc4632.png)

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
