### ISSUE TITLE
Ability to run multiple agents on same host

### ISSUE THREAD

**Issue by sturakhia** [influxdata/telegraf#2247]
## Bug report
I have a usecase where I call the REST API lets say http://server1/getMetrics and push the metrics to the cloud watch with global_tags as site=server1 

My usecase is to use same agent or multiple agents on the same machine to call other servers and do the same thing
for eg http://server2/getMetrics and push the metrics to the cloud watch with global_tags as site=server2 

Is it possible ?

### Relevant telegraf.conf:
[global_tags]
  site = "server1"

[[inputs.httpjson]]
name = "mycollector"

servers = [
"http://server/getMetrics"
]
### System info:

Telegraf v1.1.1

### Expected behavior:

I should be able to call same API to get metrics from different hosts and publish it to cloudwatch with different tags.
Or I should be able to run multiple agents on the same machine with different input and output plugins

**Comment by sparrc** [comment]
yes I don't see any reason why not
