### ISSUE TITLE
Supress MongoDB "Not gathering replica set status, member not in replica set" message

### ISSUE THREAD

**Issue by bortek** [influxdata/telegraf#2248]
## Bug report
My telegraf log is filled with these messasges

2017/01/11 09:20:10 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:20:20 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:20:30 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:20:40 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:20:50 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:21:00 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:21:10 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:21:20 Not gathering replica set status, member not in replica set (not running with --replSet)
2017/01/11 09:21:30 Not gathering replica set status, member not in replica set (not running with --replSet)

which is due to I am not running replication in MongoDB that telegraf is polling. I am not planning to run replication at all. 

### Relevant telegraf.conf:
I have tried adding "gather_perdb_stats = false" to no avail which does something else.

### System info:
RHEL7.2, kernel 3.10.0-327.36.3.el7.x86_64
telegraf-1.0.1-1.x86_64

### Steps to reproduce:

1. Just add sugar like mongoDB plugin towards mongodb server in single mode without replication

### Expected behavior:
Silence

### Actual behavior:
Noise , see above

### Additional info:

Its this peace of the code from https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb_server.go
that write the warning message.

	}, result_repl)
	if err != nil {
		log.Println("E! Not gathering replica set status, member not in replica set (" + err.Error() + ")")
	}

### Proposal:
Therefore I would like to have a parameter to MongoDB plugin called ...

ignore_replica_set_status = false

... which would steer if replica status should be polled or not. 
Alternative a parameter called ...

supress_replica_set_warning = true

... which would just silence the warning message.

### Use case: [Why is this important (helps with prioritizing requests)]
Every sysadmin knows how bad is a flooded log file is.

**Comment by sparrc** [comment]
I think that log message can be removed entirely, do you mind submitting a PR?

**Comment by bortek** [comment]
How do i do it?

**Comment by bortek** [comment]
Sweet. Didn't have time to make a pull request during the day. 😐
