### ISSUE TITLE
Add service name as a tag in httpjson

### ISSUE THREAD

**Issue by misko321** [influxdata/telegraf#2249]
### Proposal:
**httpjson** plugin allows to have multiple *[[httpjson]]* entries for each queried service. The name of the service is configurable through the _name_ property. 
Consider adding the name as a tag and keep one *httpjson* measurement and not create separate measurement for each service listed.
### Current behavior:
If multiple *[[httpjson]]* entries are given, each service data is stored in a separate measurement. The *name* itself is not included as a tag.
### Desired behavior:
Store data for all services in one measurement (just *httpjson*) and make them distinguishable by adding a tag with the provided name.
### Use case: [Why is this important (helps with prioritizing requests)]
In our infrastructure we use [consul-template](https://github.com/hashicorp/consul-template) to read a list of services and each running instance of them. We can't differentiate between services based on the *server* tag (for instance using a regex) with address since at this level in the cluster we use IP addresses and not domain names. Collecting data with *httpjson* creates a separate measurement for each service. It's very inconvenient for templated queries (in Grafana) to have a dashboard with all services and it's impossible to even retrieve all services that have some data collected through `SHOW TAG VALUES` query in InfluxDB.

Adding *name* as a tag instead of new measurement would considerably simplify querying for the data of a particular service (for instance in Grafana), just by using `WHERE` clause with the tag specified. Moreover, having all services in one measurement allows to use InfluxDB's `SHOW TAG VALUES` query for templated dashboards and get a list of all running services.

**Comment by sparrc** [comment]
Thank you for the suggestion, but I think this is quite easy to workaround using the "name_" override flags and `tags` configuration options.

If that doesn't cover it for you, let us know why and we can re-open.

**Comment by misko321** [comment]
Oh, my bad. I didn't know about those general configuration options for Telegraf, it's nice you linked to it.

I made some tests with the settings you suggested and it seems to be working as I wanted. No need to reopen I guess.

Thanks for you help :+1:
