### ISSUE TITLE
ntpq reachability should be converted to a counter

### ISSUE THREAD

**Issue by paulgear** [influxdata/telegraf#2257]
## Bug report

The ntpq input plugin pulls in the reachability column from ntpq without treating it specially in any way.  

### System info:

n/a

### Steps to reproduce:

Read https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ntpq/ntpq.go#L44

### Expected behavior:

Convert the "reach" column from octal to a decimal count of the number of successful recent polls (out of a total possible 8): 377 -> 8, 177,277,376,etc. -> 7, 77 -> 6, and so on.

### Actual behavior:

Integers are shipped raw to their outputs.

### Use case: [Why is this important (helps with prioritizing requests)]

Because otherwise it's not possible to do anything useful with the reachability metric, and it doesn't accurately represent the state of the plugin's inputs.

**Comment by powersj** [comment]
Hi,

Sorry no one responded to you so far.

It looks like PR #7840 will make this change, and a number of others as well. If someone was interested in adding just the change for the reach value that would be great!

**Comment by reimda** [comment]
@srebhan is planning to take over #7840 which fixes this issue.
