### ISSUE TITLE
Change prefix strategy for input plugins

### ISSUE THREAD

**Issue by fabMrc** [influxdata/telegraf#2260]
Hi

Input plugins can add prefix before metrics name. 
The metrics format is transformed to prefix_name
When I override the prefix with an empty string with "name_prefix" the underscore is not deleted and the the metrics format become : _name
It is not very clean
Furthermore I am using dropwizard metrics and grafana, if I change my collect strategy from jolokia to metrics opentsdb exporter for exemple all my grafana templates are wrong because dropwizard metrics works only with dot.
It should be nice to align syntax and use only dot and not underscore

**Comment by sparrc** [comment]
Please only request a single feature in a single issue.

Also please use the template because I don't understand what you're asking for exactly otherwise.
