### ISSUE TITLE
Flush jitter causes input collection to freeze

### ISSUE THREAD

**Issue by lpic10** [influxdata/telegraf#2262]
During my tests it looks like flush_jitter causes input plugins to freeze the collection. 

To reproduce this quickly is rather easy:

1. Set interval to a small value, eg. 10s
2. Set flush_jitter to a bigger value than interval, eg. 20s
3. Set a frequent flush_interval, eg. 1s (so chances are higher of getting flush_jitter bigger than interval to be able to see the errors)

I could reproduce this on version 1.1.x and in the master branch.

### Actual behavior
Error messages like: 
` E! ERROR: input [inputs.cpu] took longer to collect than collection interval (10s)`

And debug messages like:
` D! Input [inputs.cpu] gathered metrics, (10s interval) in 33.689740435s`

### Expected behavior
Collection should work as usual, flush should be handled accordingly with the jitter delay

**Comment by sparrc** [comment]
it's not freezing collection, it's just taking that long because your jitter is very high

why would you need to do this?

**Comment by lpic10** [comment]
I don't really need to do this, but why would flush_jitter cause the inputs also to wait?

**Comment by sparrc** [comment]
oh, sorry I misread that, it shouldn't be happening that way

what do you have collection_jitter set to? can you provide a full config file so I can reproduce?

**Comment by lpic10** [comment]
I usually have collection_jitter set to 0.

I think any config file should work with the settings I described. 
I just tested this one:

```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "40s"
  debug = true
  quiet = false

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"
  write_consistency = "any"
  timeout = "5s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.netstat]]
[[inputs.mem]]
[[inputs.swap]]
[[inputs.net]]

```
