### ISSUE TITLE
Add Input Plugin for PF (BSD packet filter)

### ISSUE THREAD

**Issue by totkeks** [influxdata/telegraf#2263]
## Feature Request

I only found the iptables input plugin and thought more of those "firewall input plugins" would be handy. Here I suggest PF, but one could also think about adding IPF and others.

Starting point could be the information provided by `pfctl -s <category>` (see [manpage](http://www.unix.com/man-page/FreeBSD/8/pfctl/))
What might be a problem is, that you need root rights to access /dev/pf.

### Proposal:
Add an input plugin for pf, the BSD packet filter

### Current behavior:
No such plugin exists.

### Desired behavior:
Plugin is made available.

### Use case:
Monitor statistics from the firewall / packet filter to track activity or even alert in InfluxDB / Grafana later on.

**Comment by nferch** [comment]
Started some work on this at https://github.com/nferch/telegraf/commit/7c4f5c581233df61753bb2a043fb2fa018093ed6 . Only works with state table entries for now, what else would you want it to collect?

**Comment by kmcnicholas** [comment]
pfctl -ss 

The ability to separate the individual entries of the configuration by tag for at least state entries/usage of the rule.

**Comment by nferch** [comment]
@kmcnicholas Could you elaborate? Any thoughts on what the tags/fields schema would look like?

Have the `State Table` bit of `pfctl -s info` represented, would be fairly trivial to include interface stats and Counters, but not sure what to track on a rule basis.

**Comment by danielnelson** [comment]
closed in #3405

**Comment by Serandom** [comment]
pfctl -vs queue (bytes per queue)
