### ISSUE TITLE
[Feature Request] Add overwrite file to file output plugin

### ISSUE THREAD

**Issue by Woudan** [influxdata/telegraf#2264]
### Proposal:
It's only possible to append a file with the file output plugin. It would be nice if the file can be overwritten so after every run only the new metrics are placed in the output file.

### Current behavior:
It's only possible to append the output file.

### Desired behavior:
Overwrite the output file.

### Use case:
Place output file behind an existing proxy so it can be remotely scraped and the telegraf webservice is not needed.

**Comment by phemmer** [comment]
I'm not quite sure how you would be able to implement this. A major problem is that different inputs can run on different intervals. If input-foo runs every 30 seconds, but input-bar runs every 15 seconds, when are you going to truncate the file? If you do it every 30 seconds, that defeats the purpose as your no longer getting one run of input-bar. But if you do every 15 seconds, then some of the scrapes are going to be missing input-foo.
And then you've also got service inputs, where telegraf has no control over the interval at all.
You could leave it up to the user to make sure that all their inputs run at the same interval, but this feels like it'll result in lots of issues.

Any thoughts on how you'd like to handle this?

**Comment by Woudan** [comment]
I did not take in account that different plugins could have different intervals. I understand the issues were having than.

Now I'm thinking about it, it would be more an extension or different plugin. We need to pull/scrape our metrics. At the moment via prometheus. Hosting a static file behind a proxy would be less resource intensive. I'm going to fiddle around a bit and try it a different way. Issue can be closed.
