### ISSUE TITLE
Could not build master on Windows

### ISSUE THREAD

**Issue by kirillkovalenko** [influxdata/telegraf#2268]
### System info:

Windows 10 1607 x64
go version go1.7.3 windows/amd64
GNU Make 3.82.90 Built for i686-pc-mingw32

### Steps to reproduce:

Follow build instructions from README.md

1. Install Go
2. Setup your GOPATH
3. Run go get github.com/influxdata/telegraf
4. Run cd $GOPATH/src/github.com/influxdata/telegraf
5. Run make

### Expected behavior:

Build works.

### Actual behavior:

Get the following errors:

go install -ldflags \
        "-X main.version= -X main.commit= -X main.branch=" ./...
..\..\docker\go-connections\sockets\sockets_windows.go:7:2: cannot find package "github.com/Microsoft/go-winio" in any of:
        C:\Apps\Go\src\github.com\Microsoft\go-winio (from $GOROOT)
        X:\Workplace\telegraf\src\github.com\Microsoft\go-winio (from $GOPATH)
..\..\shirou\gopsutil\process\process_windows.go:13:2: cannot find package "github.com/StackExchange/wmi" in any of:
        C:\Apps\Go\src\github.com\StackExchange\wmi (from $GOROOT)
        X:\Workplace\telegraf\src\github.com\StackExchange\wmi (from $GOPATH)
..\..\shirou\gopsutil\process\process_windows.go:14:2: cannot find package "github.com/shirou/w32" in any of:
        C:\Apps\Go\src\github.com\shirou\w32 (from $GOROOT)
        X:\Workplace\telegraf\src\github.com\shirou\w32 (from $GOPATH)
..\..\kardianos\service\service_windows.go:15:2: cannot find package "golang.org/x/sys/windows/registry" in any of:
        C:\Apps\Go\src\golang.org\x\sys\windows\registry (from $GOROOT)
        X:\Workplace\telegraf\src\golang.org\x\sys\windows\registry (from $GOPATH)
..\..\kardianos\service\service_windows.go:16:2: cannot find package "golang.org/x/sys/windows/svc" in any of:
        C:\Apps\Go\src\golang.org\x\sys\windows\svc (from $GOROOT)
        X:\Workplace\telegraf\src\golang.org\x\sys\windows\svc (from $GOPATH)
..\..\kardianos\service\service_windows.go:17:2: cannot find package "golang.org/x/sys/windows/svc/eventlog" in any of:
        C:\Apps\Go\src\golang.org\x\sys\windows\svc\eventlog (from $GOROOT)
        X:\Workplace\telegraf\src\golang.org\x\sys\windows\svc\eventlog (from $GOPATH)
..\..\kardianos\service\service_windows.go:18:2: cannot find package "golang.org/x/sys/windows/svc/mgr" in any of:
        C:\Apps\Go\src\golang.org\x\sys\windows\svc\mgr (from $GOROOT)
        X:\Workplace\telegraf\src\golang.org\x\sys\windows\svc\mgr (from $GOPATH)
Makefile:18: recipe for target 'build' failed
mingw32-make: *** [build] Error 1

**Comment by sparrc** [comment]
you need to run `make windows`
