### ISSUE TITLE
[Feature request] Add tag name to output plugin and use it in input plugin

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#2272]
### Proposal:
Suppose I have two inputs `A` and `B`, input `A` sends metric beginning with prefix `service` and input `B` also sends metric beginning with prefix `service`, meanwhile, I have two outputs `C` and `D`, I would like to let traffic from `A` goes to `C`, and that from `B` goes to `D`, if `A` and `B` have different prefix names I can use `namepass` in `C` and `D` to recognize the source, however, when `A` and `B` share with the same prefix name it is impossible to make it. So I suggest adding tag name to output plugin and use it in input plugin, for example:
```
[input.statsd]
output_tags = ["influxdb_C","graphite_C"]

[input.consul]
output_tags = ["influxdb_D","graphite_D"]

[output.influxdb]
tag = "influxdb_C"
database = "statsd"
urls = ["http://localhost:8086"]

[output.influxdb]
tag = "influxdb_D"
database = "telegraf"
urls = ["http://localhost:8086"]

[output.graphite]
tag = "graphite_C"
database = "statsd"
urls = ["http://localhost:1234"]

[output.graphite]
tag = "graphite_D"
database = "telegraf"
urls = ["http://localhost:1234"]
```
With the tag added, traffic from different sources can easily find their destination.

### Current behavior:
There is no solution to send metric with identical prefix to different destinations.

### Desired behavior:
Make it possible to send metric with identical prefix to different destinations.

### Use case: [Why is this important (helps with prioritizing requests)]
Most of telegraf plugins generate distinct prefix for metric data, however, some plugin (`statsD`) accepts customized metric name, when the customized metric name is the same with those auto-generated ones (accidentally or on purpose), it is impossible to put them into different databases.

**Comment by sparrc** [comment]
this is already possible, see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-configuration

**Comment by wei-hai** [comment]
@sparrc We are not talking about the same `tag`, you can think of the `tag` I mentioned as an alias name of the output instead of index in the measurement.

**Comment by sparrc** [comment]
then it's a dupe of #1778,

though your particular use-case could be solved with tags and tag filters, please read the configuration doc carefully, especially see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering

**Comment by wei-hai** [comment]
@sparrc I know I can make it by adding name prefix, however, what if I want to keep the metric name intact?

**Comment by sparrc** [comment]
@wei-hai you'd need to use a tag to keep the name intact
