### ISSUE TITLE
Resource leaks for CPU, Memory, and Network

### ISSUE THREAD

**Issue by josegonzalez** [influxdata/telegraf#2274]
## Bug report

We're seeing issues in two telegraf relay nodes where CPU, Memory, and Network resources are being "leaked". On process restart, we see resource usage drop back down to initial levels, though they increase back to "alarming" levels over the course of several hours. Once we hit max CPU usage, we also start seeing metrics being dropped.

The strange thing is, I'm seeing the same resource increase pattern on our influx-relay boxes *and* influxdb itself - at least on network out - but I'm not sure *what* it's transmitting to, as it's a non-clustered setup.

### Relevant telegraf.conf:

```
[global_tags]

[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["udp://influxdb-relay.consul:9096"]
  database = "seatgeek"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"

[[inputs.statsd]]
  service_address = ":8125"
  delete_gauges = false
  delete_counters = true
  delete_sets = false
  delete_timings = true
  percentiles = [90]
  metric_separator = "."
  parse_data_dog_tags = false
  templates = [
       "/seatgeek.* .service.measurement*",
       "seatgeek.* .service.measurement*",
       "service.measurement*"
   ]

  allowed_pending_messages = 10000000
  percentile_limit = 1000

[[inputs.cloudwatch]]
  region = "us-east-1"
  period = "1m"
  delay = "1m"
  interval = "3m"
  namespace = "AWS/RDS"
  ratelimit = 10
```

### System info:

The following is our system setup (note: I highly recommend something like a `telegraf report` command that can be used to output some of this):

- Version: 1.1.2-1
- Install method: deb package
- Host OS: Ubuntu 14.04
- Provider: AWS
- Input/Output methods:  `[ outputs.influxdb, inputs.statsd, inputs.cloudwatch]`
- System Specs:
  - c4.large (2 cores, 3.7GB of ram)
  - c4.2xlarge (8 cores, 15GB of ram)

### Steps to reproduce:

1. Setup telegraf with the above config.
2. Ship metrics.
3. Wait a few hours until it slowly starts consuming all resources.

### Expected behavior:

Do not progressively consume resources.

### Actual behavior:

Eventually consumes all resources and starts dropping metrics until process restart.

### Additional info:

[Logs](https://gist.github.com/josegonzalez/95fabb9c706d3d37166a07bf065707da) from the box. One thing thats weird is that, over time, it seems we ship more and more metrics per collection cycle. It's almost as if the thing is re-shipping the same metrics upstream.

Graphs from smaller system (similar on larger node):

- CPU:
  ![https://cl.ly/472J1A05160H](https://cl.ly/472J1A05160H/Image%202017-01-16%20at%2012.24.11%20AM.png)
- Memory:
  ![https://cl.ly/2c0x2q0n2l3K](https://cl.ly/2c0x2q0n2l3K/Image%202017-01-16%20at%2012.23.38%20AM.png)
- Network I/O:
  ![https://cl.ly/22391p1y1c0p](https://cl.ly/22391p1y1c0p/Image%202017-01-16%20at%2012.21.51%20AM.png)
- Spiky Load Average:
  ![https://cl.ly/1Z1Z2V0v051T](https://cl.ly/1Z1Z2V0v051T/Image%202017-01-16%20at%2012.24.36%20AM.png)
- Telegraf being cray:
  ![https://cl.ly/2r1y0o3r411y](https://cl.ly/2r1y0o3r411y/Image%202017-01-16%20at%2012.25.18%20AM.png)
- Eth0 network interface:
  ![https://cl.ly/2U250n0J322H](https://cl.ly/2U250n0J322H/Image%202017-01-16%20at%2012.25.58%20AM.png)

**Comment by sparrc** [comment]
thanks for the detailed report @josegonzalez 

What are you seeing in the logs during this time? Any error messages? Also, would it be possible for you to run with only the StatsD plugin and only the cloudwatch plugin so we can determine which is causing issue?

**Comment by sparrc** [comment]
@josegonzalez 

actually these two settings are quite high:

```
allowed_pending_messages = 10000000
percentile_limit = 1000
```

percentile_limit is at the default, but that might also be overly high if you have a large cardinality in your metrics.

Do you mind adjusting these config options and seeing what affect they have on your memory & cpu usage as well?

Any details you could provide about the metrics you are sending would also help. I suspect that your metrics have a high level of unique-ness that is always increasing, which would explain the gradually increasing memory usage. Is this true?

**Comment by josegonzalez** [comment]
- The logs for telegraf were attached in the original issue, just above all the graphs.
- We only ever get error messages about dropping metrics once we hit max CPU, which I'd like to avoid.
- I can try that. I surmise it's just the statsd plugin, as we're also using it to send tags into telegraf.
- What do you recommend we set these settings to?
- That's a good question. Is there a way to retrieve that from influxdb? As far as I am aware, our developers are not sending metrics with IDs in them - I complained very loudly when I saw this in our old graphite installation - but I could be wrong and will check deploy logs for our services and review commits.

**Comment by josegonzalez** [comment]
Note: metrics are coming in from application using statsd - we're migrating from graphite+statsd to influx+telegraf at the moment - clients, with commas at the end of the metrics to allow for adding tags.

**Comment by josegonzalez** [comment]
My gut instinct is that as we send metrics, since we are not sending in the native telegraf format - whatever that is, I am unsure of it atm - it has to parse strings into a golang struct. This requires both parsing normal statsd metrics as well as splitting on commas for tags. It's probably a little slower than it needs to be as a result.

As it slows down, we also see an increase in internal queue length, resulting in increased memory usage as time goes on. Eventually, we fall behind on processing and then telegraf starts dropping metrics in order to not be oomkilled. I've seen similar issues in python-beaver, a log collection tool I wrote for the ELK stack.

Curiously, we're seeing the same increase in resource usage on our c4.2xlarge. It's 5:36 AM EST and both instances are seeing about half a gigabyte of memory usage, indicating to me that yes, there is a backup in metric collection somewhere. I wouldn't be shocked if it was the statsd input, as you mentioned. We are using that method to make it easier for devs to migrate existing applications to telegraf, as they can slowly opt-in to tagging features etc.

One thing that's pretty unclear is why network output continues to increase at such a rapid rate. It's almost as if it's resending all metrics it's received until then.

**Comment by sparrc** [comment]
@josegonzalez couple things on the network bandwidth:

These settings mean that gauges and sets are "persistent". So you will in fact see these increasing if you are sending additional stats.

```
  delete_gauges = false
  delete_sets = false
```

config settings depend on your environment, but the default settings are the closest thing I can give you to a recommendation. You've set your allowed pending messages 1000x higher than the default.

**Comment by sparrc** [comment]
> That's a good question. Is there a way to retrieve that from influxdb? As far as I am aware, our developers are not sending metrics with IDs in them - I complained very loudly when I saw this in our old graphite installation - but I could be wrong and will check deploy logs for our services and review commits.

show series should be useful for that, see https://docs.influxdata.com/influxdb/v1.1/query_language/schema_exploration/#show-series and https://groups.google.com/forum/#!topic/influxdb/5zXl8wI8B2k

**Comment by josegonzalez** [comment]
> Any details you could provide about the metrics you are sending would also help. I suspect that your metrics have a high level of unique-ness that is always increasing, which would explain the gradually increasing memory usage. Is this true?

The culprit was exactly this. An app team made a change that basically used database primary keys as tags, which caused influxdb's indexation to slow down - confirmed via slow loading dashboards. As they were counters, telegraf seemed to keep these in memory for reporting null values etc., causing increased memory usage, and eventually the box bombed out. Rolling back that change - and dropping the affected metrics - improved the situation.

Apologies for opening up the issue without first verifying that our InfluxDB were incorrect.
