### ISSUE TITLE
snmp: snmptable executable should not be required

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2276]
## Bug report

When using the snmp plugin with a table configured, and no `snmptable` binary present, the following error is given:

    initializing table cpmCPUTotalTable: getting table columns: exec: "snmptable": executable file not found in %PATH%

The `snmptable` binary should not be required for usage of the snmp plugin. It should only be a convenience to avoid having to manually configure the table.

Ref: https://github.com/influxdata/telegraf/pull/2008#issuecomment-272871154

**Comment by kirillkovalenko** [comment]
It could be a fault at my side. Here is my config, maybe I'm just missing something. There is a table and I basically want just one field from it. 

> [[inputs.snmp]]
  agents = [ "10.10.10.10:161" ]
  version = 2
  community = "public"
  name = "system"

> [[inputs.snmp.table]]
    name = "cpmCPUTotalTable"
    oid = ".1.3.6.1.4.1.9.9.109.1.1.1"

> [[inputs.snmp.table.field]]
      name = "cpmCPUTotal5sec"
      oid = ".1.3.6.1.4.1.9.9.109.1.1.1.1.3"

**Comment by lucevers** [comment]
For info :+1: 

[[inputs.snmp]]
agents = [ "10.10.10.10:161" ]
version = 2
community = "public"
name = "system"

Even without configuring snmp.table  we see in the logfiles that the error is produced: snmptranslate not found.
So snmp polling is not available in Telegraf, do you know when this bug will be solved?

**Comment by phemmer** [comment]
@lucevers `snmptranslate` is not required. However without seeing your whole config, we can't help. Also github issues isn't the right place for troubleshooting, especially when it's an issue for a different problem. If you want to post your full config, along with the output you are getting, to the [google group](https://groups.google.com/forum/#!forum/influxdb), I'll take a look for you.

**Comment by lucevers** [comment]
Thanks! I shall make tomorrow a request via the google group.

**Comment by kirillkovalenko** [comment]
Is there any ETA for this feature?

**Comment by Hipska** [comment]
`snmptable` is not required when you don't specify an `oid` for the `inputs.snmp.table` config.
