### ISSUE TITLE
POST request to http_listener fails with EOF 

### ISSUE THREAD

**Issue by salarali** [influxdata/telegraf#2280]
## Bug report
Intermittently the post request to the http_listener fails and I get the following error message:
`Post http://localhost:8186/write: EOF`

### Relevant telegraf.conf:

Vanilla conf. with http_listener enabled.

**Comment by sparrc** [comment]
what version are you using? do you have any steps to reproduce?

**Comment by salarali** [comment]
Sorry for the lack of information.

Telegraf version: 1.1.2

I am making the http post request from a golang program.
```
resp, err := http.Post(API_URL, "", bytes.NewBuffer([]byte(metricsString)))

if err != nil || resp.StatusCode != 204 {
	logger.Error("Telegraf push failed: ", err)
} else {
	defer resp.Body.Close()
}
```

metricsString looks like this:
```
test num_error_no_category=122 1484680136892545372
test num_error_http_setup=0 1484680136892545372
test num_active_go_routines=2045 1484680136892545372
test num_error=1803 1484680136892545372
test num_duplicate=760 1484680136892545372

```

And this is all the log that go provides to me. Is there a way I can get more information?

I have turned debug logging on for telegraf but I do not see any errors there.

**Comment by danielnelson** [comment]
@salarali Any chance you have found a way to reproduce this?

**Comment by ncode** [comment]
I am receiving the same error, but it only happens with 21+ Goroutines pushing metrics to telegraf. Also It never happens if you use the discard as output.

**Comment by danielnelson** [comment]
Possibly related to #2919?

**Comment by jpereira** [comment]
I am experiencing the same issue in my setup.

```
2017-09-29T17:53:01Z E! InfluxDB Output Error: Post https://metrics.internal.lan:443/write?db=telegraf&rp=default: EOF
```

**Comment by danielnelson** [comment]
@jpereira Just to clarify, is the error when you are sending to the http_listener in Telegraf, or when you are sending to InfluxDB?

**Comment by jpereira** [comment]
@danielegozzi  Sending to the InfluxDB Cluster.

**Comment by danielnelson** [comment]
Okay, this is a different issue.  It indicates that InfluxDB closed the connection, I would check the InfluxDB logs to see if anything is reported.

**Comment by jpereira** [comment]
@danielegozzi I am using the latest version 1.4.1

**Comment by ILoGM** [comment]
We figured out that we exceeded max_line_size. 
I set it as twice as default value and disconnects disappeared.
But still, I believe that such kind of situations must be mentioned in logs, at least at debug level.

**Comment by danielnelson** [comment]
Thanks for debugging this @ILoGM, I think we should return `413 Request Entity Too Large`.

**Comment by russorat** [comment]
let's look at a refactor of the entire http_listener code for the next release.
