### ISSUE TITLE
Telegraf won't start on Windows Server 2016 Datacenter Core

### ISSUE THREAD

**Issue by chooko** [influxdata/telegraf#2283]
### Relevant telegraf.conf:
Standard conf included with the latest Windows Binaries

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf Version 1.1.2
Windows Server 2016 Datacenter Core

### Steps to reproduce:

1. Download latest binaries, extract to folder
2. Configure telegraf.conf to point to my InfluxDB server
3. Run 

`telegraf.exe -config telegraf.conf`

### Expected behavior:
Telegraf launches, begins collecting data, and sends to InfluxDB

### Actual behavior:
Panics, and doesn't run 

### Additional info:
I realize this was supposedly fixed with issue:
Windows: win_perf_counters won't load on Server Core installations due to missing Windows API libraries #1763

and pushed in milestone 1.2, but it doesn't seem to be working. Maybe I'm doing something wrong?

Output after running:

`panic: The specified module could not be found.

goroutine 1 [running]:
panic(0xf0f260, 0xc04200b480)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/lxn/win.MustLoadLibrary(0x10481eb, 0xc, 0xc)
        /home/ubuntu/telegraf-build/src/github.com/lxn/win/win.go:48 +0x85
github.com/lxn/win.init.9()
        /home/ubuntu/telegraf-build/src/github.com/lxn/win/opengl32.go:117 +0x41
github.com/lxn/win.init()
        /home/ubuntu/telegraf-build/src/github.com/lxn/win/winspool.go:101 +0x67
github.com/influxdata/telegraf/plugins/inputs/win_perf_counters.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/win_perf_counters/win_perf_counters.go:333 +0x64
github.com/influxdata/telegraf/plugins/inputs/all.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/all/all.go:83 +0x188
main.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:345 +0x91`

## Feature Request
Telegraf functionality with Windows Server 2016 Core

### Proposal:
Repair for functionality with Server 2016 Core

### Current behavior:
Not working

### Desired behavior:
To run and report to InfluxDB

### Use case: [Why is this important (helps with prioritizing requests)]
Reporting to InfluxDB to monitor server with Grafana

**Comment by sparrc** [comment]
fixed in version 1.2 already

**Comment by chooko** [comment]
Oof! Sorry @sparrc, I had a brain fart. Didn't realize that 1.2 hasn't dropped yet. Got a bit too in my head last night. :)
