### ISSUE TITLE
[Feature Request] multiple varnish instance

### ISSUE THREAD

**Issue by jsaada** [influxdata/telegraf#2285]
## Feature Request
hello,
please, allow us to configure multiple instances of varnish as it is possible for haproxy plugin
we should be able to add an instance name to the config file:

varnishstat  -n /var/lib/varnish/static/ ( path to _.vsm ) 
by default we cannot change the default path ( /var/lib/varnish/$(uname -n )

thank you

**Comment by sparrc** [comment]
Not sure I understand the request, but I believe you can do this by setting up multiple instances of `[[inputs.varnish]]`

**Comment by jsaada** [comment]
on a console, if we have multiple instances, we should call 
varnishstat -n /var/lib/varnish/instanceX/ ( path to _.vsm )
varnishstat -n /var/lib/varnish/InstanceY/ ( path to _.vsm )
....
**but you cannot specified the instance for the varnishstats on the config file**

**Comment by sparrc** [comment]
OK, so it's just a feature request to add the `-n` option to the varnish plugin?

**Comment by jsaada** [comment]
yes

**Comment by danielmotaleite** [comment]
The documentation now reports this: 

# instance_name = instanceName

So i think this is already fixed and could be closed

**Comment by danielnelson** [comment]
Thanks @danielmotaleite, looks like it was added in Telegraf 1.5.0 (#3398)
