### ISSUE TITLE
Incorrect default rate limit on CloudWatch input

### ISSUE THREAD

**Issue by cosmopetrich** [influxdata/telegraf#2298]
## Bug report

The documentation for the CloudWatch input notes that:

>  Maximum requests per second. Note that the global default AWS rate limit is
> 10 reqs/sec, so if you define multiple namespaces, these should add up to a
> maximum of 10. Optional - default value is 10.

Is this actually correct? The [AWS service limits documentation](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_cloudwatch) describes the following limits.

> GetMetricStatistics - 400 transactions per second (TPS)
> ListMetrics - 25 transactions per second (TPS)

The page [linked in a comment](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go#L193-L195) shows the same limits. I can't find any information on a specific global rate other than a note that there's a [vague per-region rate](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate). Where did the figure of 10 come from? Is it possible that there was some confusion with the GetLogEvents limit, [which was 10 at the time the rate limit feature was added](https://web.archive.org/web/20160219003457/http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html)?

**Comment by sparrc** [comment]
that could be, it's possible that AWS increased their limits.

If you want to change this please just submit a PR
