### ISSUE TITLE
OpenTSDB output plugin broken when host is given without scheme

### ISSUE THREAD

**Issue by devkid** [influxdata/telegraf#2299]
In [this code line](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/opentsdb/opentsdb.go#L68), url.Parse is used to parse the given `host` string. If this string does not contain a scheme (e.g. `google.com` instead of `tcp://google.com`), `u.Host` is an empty string and the connect fails.

### Relevant telegraf.conf:

```
[[outputs.opentsdb]]
 prefix = "telegraf."
 host = "google.com"
 port = 4242
```

### System info:

* Telegraf version 1.1.2

### Steps to reproduce:

Provide a host without a scheme to the OpenTSDB output plugin.

### Expected behavior:

The plugin should be able connect to the host.

### Actual behavior:

The connection fails with: `Failed to connect to output opentsdb, retrying in 15s, error was 'OpenTSDB: Telnet connect fail'`

**Comment by phemmer** [comment]
On the larger scope of the issue, it would be really nice if telegraf were consistent in it's naming of such parameters. Right now it's all over the board. Some parameters are called "url" and take a host, some parameters are called "host" and take a url. Others are called "address" and take a url, or host, etc.

**Comment by sparrc** [comment]
@phemmer that would be better, but would also be a breaking change at this point :(

**Comment by devkid** [comment]
Also, the error message is not really helpful. Maybe the error returned from DialTCP can be returned instead of that generic error message?

**Comment by sparrc** [comment]
I will add the error message in as well
