### ISSUE TITLE
Error/Bug Haproxy plugin

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/telegraf#2307]
I'm using telegraf v1.1.2

## Bug report

When using haproxy plugin, I'm getting this error 

> Could not connect to socket '/var/lib/haproxy/stats': dial unix /var/lib/haproxy/stats: connect: permission denied

### Relevant telegraf.conf:

`[[inputs.haproxy]]`
`servers = ["/var/lib/haproxy/stats"]`

What the best practise from telegraf team for avoid it ?

**Comment by sparrc** [comment]
You need to give the telegraf user permission to access that file, specifics are up to you
