### ISSUE TITLE
Postgres Plugin Connection 

### ISSUE THREAD

**Issue by boazjohn** [influxdata/telegraf#2316]
## Postgres Plugin Connection Pooling?

Hi,

Wanted to know if the postgres plugin would create issues with the database connections. Would it create and keep connections or a new connection is created everytime? Would stale instances of connections exist?

Is there a way to give max number of connections or timeouts for the same?

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
