### ISSUE TITLE
Logparser - Fuzzy Match Exception class and Increment counter

### ISSUE THREAD

**Issue by djjorjinho** [influxdata/telegraf#2321]
Good evening,

I wanted to lookup a log file of a Java application and fuzzy match an Exception class name at any place in the log line, send it as a tag, as possibly send an arbitrary value as a field, i.e. count=1

Will I be able to do this with this configuration? How do I add the arbitrary field?

```
[[inputs.logparser]]
  files = ["/home/service_name/logs/application.log"]
  from_beginning = true
  [inputs.logparser.grok]
    measurement = "service_exceptions_total"
    patterns = ["%{CUSTOM_LOG}"]
    custom_patterns = '''
      EXCEPTION ([a-zA-Z0-9]+Exception)
      CUSTOM_LOG %{EXCEPTION:exception:tag}
    '''
  [inputs.logparser.tags]
    service = "service_name"
```

**Comment by sparrc** [comment]
this is not possible with the grok parser, you would need to write your own plugin to accomplish this

**Comment by djjorjinho** [comment]
Would it be possible if the logline started with a number, i.e. year? 

```
CUSTOM_LOG %{NUMBER:gauge:int}.*\b%{EXCEPTION:exception:tag}
```

**Comment by sparrc** [comment]
--test flag doesn't work reliably with service inputs
