### ISSUE TITLE
Is there a way to make metrics drop out

### ISSUE THREAD

**Issue by k-s-dean** [influxdata/telegraf#2329]
Hi is there anyway to make metrics drop out when, for example a container goes down and the CPU metric goes to zero? See photo. 

Im currently using telegraf 1.2.0 , i switched from cadvisor as its currently a mess. I was alerting when the CPU hit 0, but as the metric is persisting in the database for 12 minutes and flat lining that is no longer possible.

Any available solutions or is there an upcoming fix in the next release ?

### System info:
ubuntu 16.04

monitoring: prometheus
Graphing: grafana
Exporters: node & telegraf 1.2.0 ( telegraf > influxdb_exporter [to mitigate issues with telegraf prometheus client untill 1.3.0 release)

![docker](https://cloud.githubusercontent.com/assets/23525195/22371858/9c94abba-e491-11e6-8911-d008ee0ce687.png)

**Comment by sparrc** [comment]
nope, there isn't, could potentially be a processor plugin in the future though
