### ISSUE TITLE
SNMP data not writing to InfluxDB

### ISSUE THREAD

**Issue by zackman6240** [influxdata/telegraf#2331]
SNMP data does not write to Influx. SNMP plugin does not give any errors in the term. Collectors from host I.E. CPU, RAM, Swap write to Influx just fine.

snmpwalk  retrieves data and other SNMP testing programs can query the device and get the values

### Relevant telegraf.conf:

```
urls = ["http://localhost:8086"]
database = "telegraf"

[[inputs.snmp]]
  agents = [ "172.16.1.248" ]
  version = 2
  community = "public"
  name = "SonicWall"
  [[inputs.snmp.field]]
  name = "host"
  oid = ".1.3.6.1.4.1.8741.2.1.1.1.0"
  is_tag = true
  [[inputs.snmp.field]]
  name = "uptime"
  oid = ".1.3.6.1.2.1.1.3.0"
  is_tag = true
  [[inputs.snmp.field]]
  name = "cpu"
  oid = "1.3.6.1.4.1.8741.1.3.1.3.0"
  is_tag = true
  [[inputs.snmp.field]]
  name = "mem"
  oid = ".1.3.6.1.4.1.8741.1.3.1.4.0"
  is_tag = true
```

### System info:
Ubuntu 16.04
Telegraf v1.2.0
Influx 1.2.0

### Expected behavior:
Write values to Influx

### Actual behavior:
Does not write values to Influx. --Test does not show any errors. 
telegraf --config telegraf.conf does not show any errors

**Comment by phemmer** [comment]
You should be getting a config error. You have a typo in your config:

```
[[inputs.snmp.filed]]
```

`field`, not `filed`

**Comment by zackman6240** [comment]
Sorry that's a typo that is not in the actual config, i retyped all this by hand. That is correct in the actual config. Sorry!

**Comment by sparrc** [comment]
what does `telegraf ... --test` output?

**Comment by zackman6240** [comment]
Plugin: inputs.snmp Collection 1
Plugin: inputs.snmp Collection 1 SonicWall,host=NSA\ 3500,agent_host=172.16.1.248 uptime=32678468i,cpu=12i,mem=66i 1485539298000000000
Plugin: inputs.snmp Collection 1

**Comment by sparrc** [comment]
OK, if the plugin is collecting then it must be getting written to InfluxDB.

sorry I can't help you more than that but there must be something else wrong on your network or with permissions.

If you have a specific case that can be reproduced then I can look into it more, but unfortunately there's not much I can do in this case.

I can also recommend running with the --debug flag and see if you can gather any more information.

**Comment by techhelper1** [comment]
I sincerely apologize for bumping an old post, but I am currently experiencing this bug as well.

Influx will get the POST data for SNMP, acknowledge it with an HTTP response code 204, but not write it to disk, which results in Grafana not being able to show networking graphs, however my DNS and HTTP monitors work just fine.

My telegraf and influxdb are for the most part stock installs, with the only change to recently being a reboot of the server, and I'm puzzled on where to go on troubleshooting since strace on Influx forks off into oblivillian so I can't see where the problem is coming from.

CentOS 6
Grafana, Influx, and Telegraf were installed from their respective YUM repositories.

**Comment by zackman6240** [comment]
I was able to fix this issue kinda, I’m still having the issue though with some endpoints.

I think the issue is related to having a large number of hosts. I’m monitoring over 50 endpoints and over 750 individual data points.

I increased the collection time to double the default seconds I believe and also increased the timeout time to double the default. I increased the write block size that telegraf uses to write to influx to triple what the default is.

I think my problem was i wasn’t giving telegraf enough time to to collect, parse, and write the data to influx before the next collection cycle started.

Hope this helps.

**Comment by danielnelson** [comment]
> Influx will get the POST data for SNMP, acknowledge it with an HTTP response code 204, but not write it to disk, which results in Grafana not being able to show networking graphs, however my DNS and HTTP monitors work just fine.

I would make sure the data you think is being written actually is.  I usually setup a file output using `namepass` to output the measurements in question.  If that is not enough you can use tcpdump to capture the request to InfluxDB.

**Comment by sujayuid** [comment]
invalid configuration
