### ISSUE TITLE
telegraf filestat plugin - super-glob (**) not working

### ISSUE THREAD

**Issue by asangal** [influxdata/telegraf#2333]
### Relevant telegraf.conf:
Take the default one which comes out of the box. Apart from that, inside my /etc/telegraf/telegraf.d folder, I have an extra inputs plugin file (which contains `filestat` plugin).

### System info:
Ubuntu 14.04 / CentOS 6/7
 
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

2. ...`telegraf --config-directory=/etc/telegraf -test|grep filestat|grep enhanceio`

### Expected behavior:
It should catch all files under /proc if my filestat pattern is `/proc/**` or similar. This way, it'll be more scalable solution rather than me templating or hard coding `/proc/enhanceio/<someFolder>/*` in my extra inputs plugin file (Ansible Jinja template file for ex.)

### Actual behavior:
Doesn't catch anything if I use /proc/** or /proc/*/* or /proc/*/*/* or /proc/*/**/** or similar patterns.
PS: `<exact_path_leaf_level>/*` will work.

**Comment by sparrc** [comment]
@asangal I haven't been able to reproduce, I setup a nested directory:

```
% ls -R /tmp/test
/tmp/test:
enhance/  foo.log

/tmp/test/enhance:
bar.log  nested/

/tmp/test/enhance/nested:
foo.file
```

then with this config:

```
[[inputs.filestat]]
  files = ["/tmp/test/**.log", "/tmp/test/**.file"]
  ## If true, read the entire file and calculate an md5 checksum.
  md5 = false
```

I was able to find all files

```
% telegraf --config ~/gd/ws/telegraf.conf --input-filter filestat --output-filter discard --test
* Plugin: inputs.filestat, Collection 1
> filestat,file=/tmp/test/enhance/bar.log,host=tyrion size_bytes=4i,exists=1i 1485988684000000000
> filestat,file=/tmp/test/foo.log,host=tyrion size_bytes=0i,exists=1i 1485988684000000000
> filestat,file=/tmp/test/enhance/nested/foo.file,host=tyrion exists=1i,size_bytes=0i 1485988684000000000
```

**Comment by sparrc** [comment]
FWIW, `/proc` is a very special "filesystem" that is actually a "file" mapping to particular kernel parameters and metrics. Glob and path matching may not work in this area as you might expect.
