### ISSUE TITLE
telegraf swallowing panics

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2341]
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf current master (738cbbd)

### Relevant telegraf.conf:
```
[[outputs.file]]
files = ["stdout"]

[[inputs.cpu]]
```

### Steps to reproduce:
1. call `panic("foo")` from within a plugin's `Gather()`. For example the `Gather()` method on the system/cpu plugin
2. `telegraf -config /tmp/telegraf.conf -test`

### Expected behavior:
```
* Plugin: inputs.cpu, Collection 1
big nasty panic message here
```

### Actual behavior:
```
* Plugin: inputs.cpu, Collection 1
```

### Use case: [Why is this important (helps with prioritizing requests)]
I was trying to develop on a plugin, but whenever I ran telegraf, absolutely no output was produced. Eventually I figured out that my code was causing a panic, but it was rather difficult to figure out because my panic was being thrown away.

**Comment by phemmer** [comment]
I'm wondering if this has been the cause of some issue reports lately that claim no metrics are being written, but no error is being produced. Such as #2331

**Comment by sparrc** [comment]
AFAICT this issue only happens in --test mode
