### ISSUE TITLE
Riemann E! dial "": unsupported network ""

### ISSUE THREAD

**Issue by resyst-it** [influxdata/telegraf#2349]
Hello,

I activated the riemann plugins but i have this error : E! dial "": unsupported network ""

This is my configuration file 

```
[global_tags]

[agent]
  hostname = "web01"
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"

#
# OUTPUTS:
#
[[outputs.riemann]]
#  separator = "/"
  url = "tcp://riemann.resyst-it.com:5555"
  separator = "/"

#
# INPUTS:
#
[[inputs.cpu]]
  percpu = false
  totalcpu = true
```

I saw this issue : https://github.com/influxdata/telegraf/issues/1878

Do you have an idea ?

Thank you.

**Comment by sparrc** [comment]
version?

**Comment by resyst-it** [comment]
Telegraf v1.2.0 on ubuntu 16.04.1 LTS

**Comment by sparrc** [comment]
you probably need to specify the `transport` option, see `telegraf --usage riemann`

**Comment by sparrc** [comment]
that being said, it's probably best not to use the riemann output plugin at the moment, it's current form is being deprecated in version 1.3 because of it's many issues

**Comment by resyst-it** [comment]
Yes thank you. I don't know this command "telegraf --usage riemann"
It's ok now.

Yes i know but today i use riemann -> graphite. But now telegraf -> riemann -> graphite and i will change this to telegraf -> influxdb.
