### ISSUE TITLE
More system metrics

### ISSUE THREAD

**Issue by jhofeditz** [influxdata/telegraf#235]
We would like Telegraf to provide a few more system level metrics to fully replace our existing metrics collectors (Munin/Nagios/Collectd). It would be nice to see these added:

- total number of system processes/threads (by state - runnable,sleeping,zombie)
- interrupts and context switches
- netstat tcp metrics (established, reset, time wait, etc)
- NTP time offset
- more granular memory metrics (committed, active, cache/buffers, user/kernel)

**Comment by mabushey** [comment]
I would love:
* top 10 (or however many configured) list of system processes
* Running kernel (uname -r)

**Comment by sparrc** [comment]
These all sound like reasonable requests to me. Currently I am focusing on statsd support but should have time to work on this later this month.

**Comment by yankcrime** [comment]
+1 on this.  Would like to see more I/O-related stats using `iostat` perhaps, i.e queue depths.

**Comment by rudenkovk** [comment]
+1
We really need metrics: process count, threads count, threads per process

**Comment by rplessl** [comment]
+1, we will appreciate this too.

**Comment by titilambert** [comment]
+1 !
Which one should be the first ? 
Processes state count ? like https://collectd.org/wiki/index.php/Plugin:Processes

**Comment by sparrc** [comment]
closing this because processes, kernel, and ntpq plugins are now in master, and will be available in 0.11.0, which covers all metrics in the original request.

@mabushey you could get one-off string metrics like that currently by making a simple script like this and putting it in the exec plugin:

```sh
echo kernel_version value="`uname -r`"
```

I would like to also have a simple "value" be a parsable input format in general, so that you could do this:

```toml
[[inputs.exec]]
  commands = ["uname -r"]
  data_format = "value"
  data_type = "string"
```

and parse a simple string, float, or int from any command.

**Comment by sparrc** [comment]
see https://github.com/influxdata/telegraf/issues/849

**Comment by whitelynx** [comment]
@mabushey wrote:
> - Top 10 (or however many configured) list of system processes

@sparrc: Did support for this ever get implemented? I saw that #1932 was closed, but searching for `top processes` (or even just `top`) in the project hasn't shown me much other than that.

**Comment by douglasg14b** [comment]
How can we gather this information? I can't sort out if the top n feature was implemented somewhere?

**Comment by danielnelson** [comment]
@douglasg14b The top n feature was implemented as a processor, you can use it with the procstat input: https://github.com/influxdata/telegraf/tree/master/plugins/processors/topk
