### ISSUE TITLE
Impossible to launch Telegraf on Raspberry Pi 3

### ISSUE THREAD

**Issue by djibtgy** [influxdata/telegraf#2350]
I want to use the components of InfluxData's TICK (Telegraf, InfluxDB, Chronograf, Kapacitor) stack but I can't launch them except of InfluxDB. I chose Standalone Linux Binaries (ARM) for each one because of the architecture of the RPI3.
I downloaded from here the components, for example Telegraf [https://www.influxdata.com/downloads/#telegraf](url)
```
pi@dex:~ $ sudo service telegraf start
Failed to start telegraf.service: Unit telegraf.service failed to load: No such file or directory.
```

What is strange, I got no directories called Telegraf in etc/.
Meanwhile, it worked on Ubuntu 12.04 with Ubuntu & Debian [https://www.influxdata.com/downloads/#telegraf](url)

Morevover, I would like to know how to get to the page : http://localhost:8086 to see the interface of InfluxDB because of InfluxDB is working via HTPP API and via CLI (Command Line Interface)

**Comment by sparrc** [comment]
standalone binaries are not the same as debian packages, you shouldn't expect the download to install itself as a service

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
