### ISSUE TITLE
telegraf:alpine Docker container should pull in non-busybox ping (iputils)

### ISSUE THREAD

**Issue by Nemykal** [influxdata/telegraf#2351]
### Relevant telegraf.conf:
```
[[inputs.ping]]
 urls = [
   "8.8.8.8"
]
count = 1
```

### System info:

All versions. Using the telegraf:alpine container

### Steps to reproduce:

1. Run container that uses the telegraf ping plugin with a non-gnu 'ping', such as busybox's implementation

### Expected behavior:
Ping plugin works

### Actual behavior:
Telegraf errors with: 

```
/bin/ping: unrecognized option: i
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: ping [OPTIONS] HOST

Send ICMP ECHO_REQUEST packets to network hosts

        -4,-6           Force IP or IPv6 name resolution
        -c CNT          Send only CNT pings
        -s SIZE         Send SIZE data bytes in packets (default:56)
        -t TTL          Set TTL
        -I IFACE/IP     Use interface or IP address as source
        -W SEC          Seconds to wait for the first response (default:10)
                        (after all -c CNT packets are sent)
        -w SEC          Seconds until ping exits (default:infinite)
                        (can exit earlier with -c CNT)
        -q              Quiet, only display output at start
                        and when finished
        -p              Pattern to use for payload, exit status 1
Fatal error processing ping output
```

### Additional info:

See above. 

### Proposal:

Add 'iputils' to the Dockerfile for telegraf:alpine

**Comment by sparrc** [comment]
I think you should open this bug in the docker repo, cc @jsternberg

**Comment by Nemykal** [comment]
Ok, will do. I was looking at https://github.com/influxdata/official-images but it's not possible to open an issue there. I'll look for where the telegraf Dockerfiles actually are.

**Comment by Nemykal** [comment]
Raised it here: https://github.com/influxdata/influxdata-docker/issues/60
