### ISSUE TITLE
Telegraf inputs.http_listener ignores timestamp precision

### ISSUE THREAD

**Issue by Menthalion** [influxdata/telegraf#2359]
## Bug report

When Telegraf with http_listener is used as a proxy for InfluxDB, the http request parameter `precision=<unit>` is ignored, and times are passed through as nanoseconds even if they aren't.

### Relevant telegraf.conf:
Default inputs.http_listener and either http or udp outputs.influxdb
### System info:

Telegraf 1.1.2, InfluxDB 1.2 on Ubuntu 16.04

### Steps to reproduce:

1. Set up a Telegraf with inputs.http_listener that forwards it's data to Influxdb
2. Send a http request to Telegraf with precision=s and timestamps in seconds/epoch
3. Query InfluxDb to see the timestamp

### Expected behavior:

The timestamp in influxdb is registered in seconds / epoch, and corresponds with the time of the measuremt

### Actual behavior:

The timestamp is registered in nanoseconds / epoch, and correspond with a time in 1970

### Proposal:

Either have Telegraf cast the timestamp from the input precision to nanoseconds, or pass through both timestamp and precision to the outputs.

### Use case: 
Most metrics systems supporting InfluxDB only support HTTP requests, but a high load of HTTP requests cause performance problems by each causing a WAL sync.

So that's why we need either
 - Telegraf as HTTP->Telegraf->UDP->InfluxDB proxy, or
 - InfluxDB needs to be adjusted so HTTP requests will be buffered for an amount points before a write just like the  UDP / TCP / Graphite inputs do. This would mean the status returned on such a http request should be a 202 (Accepted). An additional parameter for guaranteed write could also be created.

**Comment by sparrc** [comment]
telegraf is not meant to be a proxy for InfluxDB, it accepts line-protocol which is defined as having nanosecond timestamps.
