### ISSUE TITLE
[Feature Request] MIPS64 builds

### ISSUE THREAD

**Issue by unixninja92** [influxdata/telegraf#2362]
I am currently running a Ubiquity router running EdgeOS (debian variant) and would love to install telegraf on it, but it's mips64. I tried compiling it myself a few months ago, but was unsuccessful. We are planning on buy more routers and switches from Ubiquity soon, and it would be really useful to be able to run telegraf on them as well.

**Comment by sparrc** [comment]
I'd be happy to accept a PR for this, but I'm going to close the issue because we don't have any plans or time to support this.
