### ISSUE TITLE
SNMP ifTable measurement value in single quotes not working

### ISSUE THREAD

**Issue by kylejvrsa** [influxdata/telegraf#2370]
OS: Debian Jessie
Influxdb 1.2
Telegraf 1.2

snmp.conf
```
[[inputs.snmp.table]]
     # For the below OID (ifTables) we're using the actual OID instead of the MIB.  
       oid = "1.3.6.1.2.1.2.2"
```

I am using telegraf to gather snmp data from a couple of routers. 
When I run the following directly on influxdb it gives no results:
```
select * from ifTable where agent_host = 'odin.piccing.office' and ifDescr = 'eth0.3' and "ifOperStatus" = '1' and time > now() - 30s;
```
But when I run this, it does give results:
```
select * from ifTable where agent_host = 'odin.piccing.office' and ifDescr = 'eth0.3' and "ifOperStatus" = 1 and time > now() - 30s;
```

I am not sure whether to create this issue here or on influxdb side but it seems I can only reproduce it with snmp ifTable.

**Comment by sparrc** [comment]
this is not an issue for influxdb or telegraf, you just need to put tag values in single quotes in your queries

**Comment by kylejvrsa** [comment]
@sparrc Sorry maybe I am not understanding here, but that was my point that when I put the tag value in single quotes it does not work or am I missing something?

**Comment by sparrc** [comment]
sorry I misread that, sounds like ifOperStatus is a field and not a tag

**Comment by kylejvrsa** [comment]
I am using the ifTable snmp table, any idea how I can make all the fields in the table tags? Because I am not specifying my own tables, but rather using the built-in snmp table reader for it.

**Comment by sparrc** [comment]
there's no way to do that as far as I'm aware, why would you want everything to be tag? you need to have at least 1 field in order to actually write the metrics anywhere

**Comment by kylejvrsa** [comment]
Ok So here is something interesting...if it is a field key with a field value that is an integer the select with quotes does not work, but if if it is a field key with the field value that is a string the select with quotes work.

SHOW TAG KEYS from ifTable
name: ifTable
tagKey
------
agent_host
ifIndex

> SHOW FIELD KEYS from ifTable
name: ifTable
fieldKey          fieldType
--------          ---------
ifAdminStatus     integer
ifDescr           string
ifInDiscards      integer
ifInErrors        integer
ifInNUcastPkts    integer
ifInOctets        integer
ifInUcastPkts     integer
ifInUnknownProtos integer
ifLastChange      integer
ifMtu             integer
ifOperStatus      integer
ifOutDiscards     integer
ifOutErrors       integer
ifOutNUcastPkts   integer
ifOutOctets       integer
ifOutQLen         integer
ifOutUcastPkts    integer
ifPhysAddress     string
ifSpecific        string
ifSpeed           integer
ifType            integer

Returns results(ifPhysAddress and ifDescr are strings)
select * from ifTable where "ifPhysAddress" = 'fe:81:9d:b0:f6:71'limit 10;
select * from ifTable where "ifDescr" = 'eth1'limit 10;

NO results (ifOperStatus is integer)
select * from ifTable where "ifOperStatus" = '1'limit 10;

Any ideas?
