### ISSUE TITLE
Input plugin for exim

### ISSUE THREAD

**Issue by fahimeh2010** [influxdata/telegraf#2374]
Hello all
First thank you for your open source project.
I need to monitor exim but I think there is no input plugin for exim. it will be so useful .
Thank you

**Comment by sparrc** [comment]
please open a new request and fill out the "feature request" template, linking to relevant documentation on how metrics can be collected if available

**Comment by adeverteuil** [comment]
Hi, sorry for necroposting, but I did a bit of research and development to achieve this and I have some recommendation for @fahimeh2010 and anyone Googling this.

Exim doesn't provide an interface for metrics collection. Instead, it produces very extensive and well documented logs. The logparser plugin is the best choice to get statistics from Exim.

Here is how I configured it:
https://github.com/adeverteuil/ansible-playbooks/blob/develop/roles/telegraf/templates/exim.conf.j2

It doesn't get much, just the message size for each received and sent messages. I just have a low-volume personnal mail server, so it's sufficient for me, but there is potential for lots more.

Unfortunately there isn't a _de facto_ log format standard like Apache's combined log, so anyone wishing to do something similar will need to learn the Logparser plugin configuration, the Grok language, and do testing and development for their own particular Exim log_selector configuration and desired metrics output.

See also my Exim `log_selector` configuration, for comparison with your own:
https://github.com/adeverteuil/ansible-playbooks/blob/develop/roles/mailserver/templates/exim4.conf.j2#L268

There are lots of references commented in my exim.conf file. Here they are for convenience:

 * [Telegraf Logparser plugin documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser)
 * [Grok reference](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html) in ElasticSearch guide
 * [Grok debugger](http://grokdebug.herokuapp.com/)
 * [Logstash Grok patterns](https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns) included with Telegraf
 * [Logstash Grok patterns for Exim](https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/exim) not included with Telegraf
 * [Telegraf Grok Influx patterns](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/logparser/grok/patterns/influx-patterns)
 * [Exim 4.84 log_selector](http://exim.org/exim-html-4.84/doc/html/spec_html/ch-log_files.html#SECTlogselector) in Exim documentation
 * [Oniguruma regular expressions](https://github.com/kkos/oniguruma/blob/master/doc/RE)
 * [Parsing Logs into InfluxDB using Telegraf’s logparser Plugin](https://www.influxdata.com/telegraf-correlate-log-metrics-data-performance-bottlenecks/) on InfluxDB blog
 * [Exim + Logstash](https://graemef.wordpress.com/tech-stuff/exim-logstash/), series of blog posts about parsing Exim logs with Grok

**Comment by danielnelson** [comment]
@adeverteuil Thanks for adding the information, if you are interested you could add a new section to the logparser README with a guide to setting it up to parse exim log files.  Also, any suggestions for improving the docs would be appreciated, since logparser is quite hard to get started with.
