### ISSUE TITLE
Logparser support for journald

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#2375]
Will be great to be able to use logparser to analyze logs send to journald.

Seems that it will be the standard, even InfluxDB and Telegraf are sending logs by default to journald.

I guess it should be able to filter, at least, by unit, and maybe also by priority and identifier.

Maybe using [this lib](https://github.com/coreos/go-systemd/tree/master/sdjournal
)?

**Comment by phemmer** [comment]
Dup #2109
