### ISSUE TITLE
Change log format to match InfluxDB

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#2376]
InfluxDB uses [Zap](http://go.uber.org/zap) for logging.
It will be much easier for operating InfluxDB and Telegraf to have a common format.

**Comment by sspaink** [comment]
Closing because this ticket has been open for a while without activity and I think moving to Zap is a neat idea but beside matching the InfluxDB project it doesn't offer much of an advantage to the current implementation.
