### ISSUE TITLE
SQL Server plugin crash

### ISSUE THREAD

**Issue by Tyonar** [influxdata/telegraf#2377]
## Bug report
Telegraf crash when inputs.sqlserver is uncommented
Output : 
2017/02/07 10:25:13 I! Using config file: /etc/telegraf/telegraf.conf
2017-02-07T15:25:13Z I! Starting Telegraf (version 1.2.0)
2017-02-07T15:25:13Z I! Loaded outputs: influxdb
2017-02-07T15:25:13Z I! Loaded inputs: inputs.dns_query inputs.influxdb inputs.net inputs.sqlserver inputs.cpu inputs.disk inputs.mem inputs.system inputs.diskio inputs.kernel inputs.processes inputs.swap
2017-02-07T15:25:13Z I! Tags enabled: host=monitoring.local.pingpow.ca
2017-02-07T15:25:13Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"monitoring.local.pingpow.ca", Flush Interval:10s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x654edb]

goroutine 115 [running]:
panic(0xf2a2e0, 0xc42000c100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/client/v2.(*client).Write(0xc4203220c0, 0x18fd660, 0xc4203c4840, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/influxdb/client/v2/client.go:354 +0xfb
github.com/influxdata/telegraf/plugins/outputs/influxdb.(*InfluxDB).Write(0xc42000a700, 0xc42072c000, 0x3e8, 0x3e8, 0xc42001fda0, 0x6b3911)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/outputs/influxdb/influxdb.go:202 +0x27b
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc4201781e0, 0xc42072c000, 0x3e8, 0x3e8, 0x3e8, 0x2)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:170 +0xa1
github.com/influxdata/telegraf/internal/models.(*RunningOutput).AddMetric(0xc4201781e0, 0x18ff3a0, 0xc4200bd380)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:112 +0x149
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0xc420794cd0, 0xc420054ea0, 0xc42074ad20, 0xc4200260a8)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:278 +0x1e7
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:286 +0xee

### Relevant telegraf.conf:

[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/758156/telegraf.conf.txt)

### System info:

CentOS7 with InfluxDB 1.2.0; telegraf 1.2.0; and general use packages (tmux, nano, mlocate)

### Steps to reproduce:

1. Add user to SQL Server following the plugin's documentation
2. Reproduce these settings on the inputs.sqlserver section of telegraf.conf
3. Execute "telegraf" in terminal

### Expected behavior:

The metrics are gathered and sent to InfluxDB, if the config is wrong on either the SQL Server's side or 
telegraf's side throw a proper error message

### Actual behavior:

Segmentation fault and crash.

### Additional info:

Config and logs are there, nothing to add.

### Use case: [Why is this important (helps with prioritizing requests)]

Enterprise environment, monitoring SQL servers.

**Comment by sparrc** [comment]
fixed in 1.2.1, see https://github.com/influxdata/telegraf/issues/2317
