### ISSUE TITLE
multiple filters (namepass/tagpass) breaks output

### ISSUE THREAD

**Issue by danyli78** [influxdata/telegraf#2381]
System Info: CentOS 7.2.1511 & 4 cores, 12GB RAM
Version: Telegraf v1.2.1
Conf:

```
```[[outputs.influxdb]]
  urls = ["http://relay001:9091"]
  database = "test"
  precision = "s"
  namepass = ["haproxy"]
  [outputs.influxdb.tagpass]
    collector = ["heapster"]```
```

Reproduce:

If I remove the "namepass" filter, i immediately get data from my heapster points.

**Comment by phemmer** [comment]
Can you provide sample points of what you expect to make it through?

The information you've provided doesn't add up. The `namepass` you have indicates you want to allow the `haproxy` measurement. The tagpass indicates you want to allow points with the tag `collector=heapster`. The haproxy input provides no tag called `collector`. Thus this is an impossible combination.

**Comment by sparrc** [comment]
as @phemmer suggested, you're specifying an impossible combination. `namepass` means that _only_ those points will pass through the plugin

**Comment by danyli78** [comment]
So one measurement call "haproxy" and 10 heapster measurements, I want all
haproxy points to be allowed to come in and i want all heapster measurement
points that have the collector = heapster tag key/value to be allow to come
in. How do i accomplish this in a single output?

Thanks,

Daniel

**Comment by hackery** [comment]
(for the benefit of anyone else finding this)
Probably easiest to create two output sections with one of the filter rules in each. For more complex situations, you can add processors (e.g. [override](https://github.com/influxdata/telegraf/tree/master/plugins/processors/override)) which add a common "send this to Influx" tag based on different rule sets (and the output plugin config can drop that marker tag).
