### ISSUE TITLE
Mongodb jumbo chunk count fails on mirrored config servers

### ISSUE THREAD

**Issue by yonido** [influxdata/telegraf#2389]
## Bug report
Due to https://jira.mongodb.org/browse/SERVER-27864 - on mirrored config servers, telegraf fails to fetch jumbo chunk stats, since it uses "secondary read preference" against the config dbs.
In addition, mongos' logs get this scary message every 10s:

query on admin.$cmd: { query: "1", help: 1 } failed to: in.dbcfg1.mydomain.com:27019 (10.0.97.139) exception: "query" had the wrong type. Expected Object, found String

### System info:

Telegraf 1.2.0

### Desired behavior:
Consider either making read preference controllable / query jumbo chunks using a different read pref / make jumbo chunks query optional.

**Comment by sparrc** [comment]
thank you for reporting. A PR would be highly appreciated if anyone has a reproducible setup.

**Comment by danielnelson** [comment]
@yonido Is this still an issue after MongoDB 3.2.13?
