### ISSUE TITLE
WINDOWS MSI file - Telegraf

### ISSUE THREAD

**Issue by Raamardhani** [influxdata/telegraf#2394]
Hi Team,

Can someone help me with an MSI file for windows installer? We wanted to deploy telegraf on more than 1000 servers using bigfix. Early responses are extremely appreciated. thanks.

**Comment by sparrc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
