### ISSUE TITLE
E! ERROR in input [inputs.passenger]: exit status 2

### ISSUE THREAD

**Issue by bwellsnc** [influxdata/telegraf#2398]
OS: CentOS 7
Telegraf: 1.2.1
Passenger/Nginx: nginx/1.10.0 Phusion_Passenger/5.0.28

I am running the version of Passenger/Nginx from Phusion Passenger, and I have found no way to run telegraf without running it as root because telegraf does not seem to read the output correctly.  My telegraf use can run sudo and run the passenger-status command but when called from telegraf I get:
E! ERROR in input [inputs.passenger]: exit status 2

I have seen that this is possibly how passenger-status outputs the data.  I am just needing a solution since I utilize telegraf for several of my Passenger instances.  Thanks!

**Comment by sparrc** [comment]
please reopen with the issue template and include your config file
