### ISSUE TITLE
Missing fields in procstat output

### ISSUE THREAD

**Issue by andrii-rymar** [influxdata/telegraf#2403]
## Bug report
It looks like the same problem as was mentioned in #1584 - IO and 2 other procstat metrics are missing in the resulting output. 
The full list: num_fds, involuntary_context_switches, read_count, write_count, read_bytes are write_bytes.

### Relevant telegraf.conf:
[[inputs.procstat]]
  pattern = "test"

### System info:
Checked with Telegraf 1.2.0-1 and 1.2.1-1 on CentOS 6.5/7 x64

### Steps to reproduce:

1. Setup procstat input in telegraf.conf
2. Start telegraf
3. Check DB for fields.

### Expected behavior:
Presence of all fields mentioned in the procstat readme.

### Actual behavior:
Several fields are missing:
- num_fds
- involuntary_context_switches
- read_count 
- write_count
- read_bytes
- write_bytes.

**Comment by sparrc** [comment]
this is probably a permissions issue, have you tried running telegraf as root or with sudo privileges? if you're running as a service then the telegraf user needs access to the entire procfs filesystem.

**Comment by sparrc** [comment]
see https://github.com/influxdata/telegraf/issues/1300

**Comment by andrii-rymar** [comment]
I see. And confirm that running telegraf as root solves the issue.
