### ISSUE TITLE
Need help for Windows IIS server log parser

### ISSUE THREAD

**Issue by Kamalkp1978** [influxdata/telegraf#2406]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:
telegraf 3.1.1
on Windows 2008 R2
IIS logs from Windows 2012 R2

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Using CUSTOM LOG parser
2. Below is the sample IIS server access log and grok parser but not working, need help to parse it

Sample IIS Logs
#Fields: date time s-sitename s-computername s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs-version cs(User-Agent) cs(Cookie) cs(Referer) cs-host sc-status sc-substatus sc-win32-status sc-bytes cs-bytes time-taken
2017-02-02 15:22:17 W3SVC1 abc-xyz-01 11.220.100.1 GET /news/news.asp id=106381 80 - 10.223.129.184 HTTP/1.1 Mozilla/5.0+(compatible;+Googlebot/2.1;++http://www.google.com/bot.html) - - www.abcd.co.uk:40004 404 0 2 1439 422 0

GROK PATTERN USED for above IIS server access logs

CUSTOM_LOG %{DATESTAMP:EventTime} %{WORD:sitename} %{HOSTNAME:computername} %{IP:hostip} %{URIPROTO:method} %{URIPATH:request} (?:%{NOTSPACE:queryparam}|-) %{NUMBER:port} (?:%{WORD:username}|-) %{IP:clientip} %{NOTSPACE:httpversion} %{NOTSPACE:user-agent} (?:%{NOTSPACE:cookie}|-) (?:%{NOTSPACE:referer}|-) (?:%{HOSTNAME:host}|-) %{NUMBER:status} %{NUMBER:sub-status} %{NUMBER:win32-status} %{NUMBER:bytes-received} %{NUMBER:bytes-sent} %{NUMBER:time-taken}

### Expected behavior:
parse each fields which it is not doing

### Actual behavior:
No error displayed

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
try using http://grokdebug.herokuapp.com/ to debug your logparsing problem. If that doesn't help then consider asking on the google groups list, slack, or stackoverflow

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).
