### ISSUE TITLE
Feature Request - Extend couchbase input plugin to collect more stats

### ISSUE THREAD

**Issue by iskrenpp** [influxdata/telegraf#2408]
## Feature Request
Hi,
I am trying to add simply more fields to the couchbase_bucket in plugins/inputs/couchbase/couchbase.go but it seems that even though build is successful and file size is larger I don't get any success in retrieveing addiitonal stats that I am interested in from couchbae via the client

I would like to have access to all stats for the bucket but right now this is the list that I have:

```
		fields["ep_dcp_total_queue"] = bs["epDcpTotalQueue"] //Items within the DCP Queue
		fields["vb_active_num"] = bs["vbActiveNum"]          //Active and Replica vBucket Count
		fields["vb_replica_num"] = bs["vb_ReplicaNum"]       //Active and Replica vBucket Count
		fields["curr_items"] = bs["currItems"]
		fields["ep_bg_fetched"] = bs["epBgFetched"]                             //Number of items fetched from disk (cache misses).
		fields["vb_active_perc_mem_resident"] = bs["vbActivePercMemResident"]   //Percent of active data in a vBucket that is memory resident.
		fields["vb_replica_perc_mem_resident"] = bs["vbReplicaPercMemResident"] //Percent of replica data in a vBucket that is memory resident
		fields["ep_tmp_oom_errors"] = bs["epTmpOomErrors"]                      //Number of times temporary OOMs were sent to a client.  Represents high transient memory pressure within the system.
		fields["ep_oom_errors"] = bs["epOomErrors"]                             //Number of times permanent OOMs were sent to a client.  Represents very high consistent memory pressure within the system.
		fields["ep_queue_size"] = bs["epQueueSize"]                             //The amount of data waiting to be written to disk.
		fields["ep_flusher_todo"] = bs["epFlusherTodo"]                         //The number of items currently being written to disk.
		fields["ep_io_num_read"] = bs["epIoNumRead"]                            //The number of read operations sent to disk.
		fields["ep_io_num_write"] = bs["epIoNumWrite"]                          //The number of write operations sent to disk.
		fields["ep_mem_high_wat "] = bs["epMemHighWatermark "]
		fields["cmd_get"] = bs["cmdGet"]
		fields["ep_kv_size"] = bs["epKvSize"]
```

I think extending the coucnbase input plugin will be usefull for anyone to get deeper inderstanding of Couchbase cluster health with monitring the stats above

Please provide some guidance as to what I may be missing in order to extend the plugin to support these extra stats

**Comment by sparrc** [comment]
I can help you with this but it would be much easier if you submit a PR rather than an issue

**Comment by iskrenpp** [comment]
thanks @sparrc  - silly question though - I am fairly new to github - for some reason I get 403 forbidden when trying to do "git push origin <my-branch>" to telegraf repo - do I need some rep or access tobe given or additional setup?

**Comment by sparrc** [comment]
you need to create a fork and push a branch there, then create a PR from that

**Comment by iskrenpp** [comment]
@sparrc PR submitted https://github.com/influxdata/telegraf/pull/2413
