### ISSUE TITLE
error getting disk usage info

### ISSUE THREAD

**Issue by pobearm** [influxdata/telegraf#2409]
We use centos 7 amd64,  install telegraf with rpm, we got error:
telegraf[54902]: 2017-02-15T08:18:20Z E! ERROR in input [inputs.disk]: error getting disk usage info: input/output error

I found this code in disk.go,  i am new to this project , maybe help.
```
        disks, partitions, err := s.ps.DiskUsage(s.MountPoints, s.IgnoreFS)
	if err != nil {
		return fmt.Errorf("error getting disk usage info: %s", err)
	}

```

**Comment by sparrc** [comment]
that usually means you have hardware issues or a full disk
