### ISSUE TITLE
Win_Perf: Unable to retrieve some metrics (CLR Memory for instance)

### ISSUE THREAD

**Issue by GBouBou** [influxdata/telegraf#2411]
## Bug report

I'm not able to retrieve .NET CLR Memory metrics !

Errors:
Performance Object '.NET CLR Memory' does not exist in query: \.NET CLR Memory(*
)\# Total Committed Bytes

I've got the same issue with ".NET CLR Locks Threads" "ASP.NET Apps v4.0.30319" "Web Service"

Other counters are working

## .NET CLR Memory
	[[inputs.win_perf_counters.object]]
     ObjectName = ".NET CLR Memory"
     Counters = ["# Total Committed Bytes", "# Total Reserved Bytes", "% Time in GC"]
	 Instances = ["*"] 
     Measurement = "win_clr_memory"
	 WarnOnMissing = true 

### System info:

Telegraf 1.2.1

**Comment by sparrc** [comment]
I'm sorry you've had this issue. Unfortunately I have absolutely no idea why you wouldn't be getting those metrics, and we don't have the resources to chase it down. Telegraf simply calls the windows libraries behind performance counters without modifying the input, so if it's not getting exposed to telegraf then telegraf can't access it.

You could try the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/) to get an answer.

**Comment by GBouBou** [comment]
We need to run Telegraf as Administrator

**Comment by lucadistefano** [comment]
in my experience telegraf requires a user in the "Performance Monitor Users" group.

on my win 2012R2 seems to work:

```
C:\Program Files\Telegraf>telegraf.exe --debug --config test-dotnet.conf --test
* Plugin: inputs.win_perf_counters, Collection 1
Valid: \.NET CLR Memory(*)\# Total Committed Bytes
Valid: \.NET CLR Memory(*)\# Total Reserved Bytes
Valid: \.NET CLR Memory(*)\% Time in GC
> win_clr_memory,instance=_Global_,objectname=.NET\ CLR\ Memory,host=WIN-MONTEST #_Total_Committed_Bytes=52613120 1490301926000000000
> win_clr_memory,objectname=.NET\ CLR\ Memory,host=WIN-MONTEST,instance=powershell_ise #_Total_Committed_Bytes=52613120 1490301926000000000
> win_clr_memory,host=WIN-MONTEST,instance=_Global_,objectname=.NET\ CLR\ Memory #_Total_Reserved_Bytes=402644992 1490301926000000000
> win_clr_memory,host=WIN-MONTEST,instance=powershell_ise,objectname=.NET\ CLR\ Memory #_Total_Reserved_Bytes=402644992 1490301926000000000
> win_clr_memory,instance=_Global_,objectname=.NET\ CLR\ Memory,host=WIN-MONTEST Percent_Time_in_GC=0.0015691155567765236 1490301926000000000
> win_clr_memory,instance=powershell_ise,objectname=.NET\ CLR\ Memory,host=WIN-MONTEST Percent_Time_in_GC=0.0015691200969740748 1490301926000000000
```
