### ISSUE TITLE
Still an issue Windows: win_perf_counters not gathering non-English metrics (was #1730)

### ISSUE THREAD

**Issue by tfrache** [influxdata/telegraf#2423]
Some of my french counters are not working even with use of PreVistaSupport = True
<img width="716" alt="erreur" src="https://cloud.githubusercontent.com/assets/25840977/23059334/48dd41b2-f4f9-11e6-855b-5f888fd3682f.png">

"Recherches Active Directory/s." and "Lectures Active Directory/s." are OK but not the one with É character: 	"Écritures Active Directory/s.". However, the counter seems to be valid from Telegraf.exe:

C:\Program Files\Telegraf>telegraf.exe -config telegraf.conf -test
* Plugin: inputs.win_perf_counters, Collection 1
Valid: \Processeur(*)\% temps processeur
Valid: \Processeur(*)\% temps utilisateur
Valid: \Processeur(*)\% temps privilégié
Valid: \Système\Longueur de la file du processeur
Valid: \Mémoire\Mégaoctets disponibles
Valid: \Disque logique(C:)\Mégaoctets libres
Valid: \Interface réseau(*)\Octets envoyés/s
Valid: \Interface réseau(*)\Octets reçus/s
Valid: \DirectoryServices(*)\Nb total d'octets DRA entrants/s.
Valid: \DirectoryServices(*)\Nb total d'octets DRA sortants/s.
Valid: \DirectoryServices(*)\Nb de synchronisations de réplication DRA en attente
Valid: \DirectoryServices(*)\Nb de threads Active Directory utilisés
Valid: \DirectoryServices(*)\Recherches Active Directory/s.
Valid: \DirectoryServices(*)\Lectures Active Directory/s.
**Valid: \DirectoryServices(*)\Écritures Active Directory/s.**
Valid: \DirectoryServices(*)\Durée de liaison LDAP
Valid: \DirectoryServices(*)\Sessions client LDAP

My telegraf.conf inputs :

[[inputs.win_perf_counters]]
	PrintValid = true
	**PreVistaSupport = true**
	[[inputs.win_perf_counters.object]]
    ObjectName = "Processeur"
    Instances = ["*"]
    Counters = [
		"% temps processeur",
		"% temps utilisateur",
		"% temps privilégié",
	]
    Measurement = "dc_win_cpu"
    #IncludeTotal=false

	[[inputs.win_perf_counters.object]]
    ObjectName = "Système"
    Counters = [
		"Longueur de la file du processeur",
    ]
    Instances = ["------"]
    Measurement = "dc_win_system"
	
	[[inputs.win_perf_counters.object]]
    ObjectName = "Mémoire"
    Counters = [
		"Pourcentage d'octets dédiés utilisés",
		"Mégaoctets disponibles",
    ]
    Instances = ["------"]
    Measurement = "dc_win_memory"
	IncludeTotal=false
	
	[[inputs.win_perf_counters.object]]
    ObjectName = "Disque logique"
    Counters = [
		"Mégaoctets libres",
    ]
    Instances = ["C:"] 
    Measurement = "dc_win_disk"
	IncludeTotal=false
	
	[[inputs.win_perf_counters.object]]
    ObjectName = "Interface réseau"
    Counters = [
	"Octets envoyés/s",
	"Octets reçus/s",
    ]
    Instances = ["*"]
	IncludeTotal=true
    Measurement = "dc_win_net"
	
	[[inputs.win_perf_counters.object]]
    ObjectName = "DirectoryServices"
    Instances = ["*"]
    Counters = [
	"Nb total d’octets DRA entrants/s.",
	"Nb total d’octets DRA sortants/s.",
	"Nb de synchronisations de réplication DRA en attente",
	"Nb de threads Active Directory utilisés",
	**"Recherches Active Directory/s.",
	"Lectures Active Directory/s.",
	"Écritures Active Directory/s.",**
	"Durée de liaison LDAP",
	"Sessions client LDAP",
	]
    Measurement = "dc_win_ntds"
    #IncludeTotal=false

Your help will be greatly appreciated!

**Comment by sparrc** [comment]
what version are you using? I believe @PierreF was able to get French counters working?

**Comment by tfrache** [comment]
I'm using the last release : 1.2.1.

**Comment by tfrache** [comment]
In fact I just discovered that it tooks time but values are well received. Please ignore ! Thank you.
