### ISSUE TITLE
Global Fields

### ISSUE THREAD

**Issue by JeffAshton** [influxdata/telegraf#2427]
It would be nice to be able to globally define fields for tag like data that has high-cardinality.

For example, in our environment we have lots of hosts, all short lived in our CD pipeline.  I have no used cases to filter or group by hostname, but it would be nice to be able to count distinct hosts during an interval in influxdb.

**Comment by sparrc** [comment]
you could do this with an `exec` plugin, something like 

```
# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
  ## Commands array
  commands = [
    "echo 'hosts hostA=1i'",
  ]

  ## Data format to consume.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
```

**Comment by JeffAshton** [comment]
@sparrc :  So I was hoping for this to work with existing input plugins like the windows performance counters.  Using [[inputs.exec]] would require me to have telegraf call to a shell script to call to another instance of telegraf.
