### ISSUE TITLE
Kubernetes input plugin

### ISSUE THREAD

**Issue by kotarusv** [influxdata/telegraf#2429]
Hi

We are evaluating using TICK stack in our platform. We're running multiple big clusters using Openshift . Openshift essentially use docker and Kubernetes to provide container platform. TICK is going to be our default metrics solution if it works as we expected or satisfy our needs. I'm interested to play around with kubernetes input plugin as it is very essential in our platform but documentation is not clear on how to use it. How to use this plugin? I'm already using telegraf in daemon sets mode and getting metrics for other services, including docker. 

Kubernetes is default standard for container orchestration and gaining lot of attention from small to large enterprises who want to use container platforms in their public/private/hybrid cloud environments. I was wondering why TICK is not supporting Kubernetes yet in full scale by default. Docker plug-in support is nice but we can't measure the health of kubernetes with just docker. 

Our case with Kubernetes or want to gather below Kubernetes metrics. I am sure these metrics would be useful for any customer who deployed Kubernetes

- How much Quota's being requested by clients
- How much quotas being currently used
- How to plan cluster capacity management
- Cluster nodes health
-  Cluster network performance and report any latency issues
- Storage volumes utilization and report failures

Above are just few examples

Prometheus has default support for Kubernetes. I was waiting or expecting similar kind of rich integration with Tick also. In particular, telegraf support for metrics gathering from kubernetes platform. 

Below link helps to understand how prometheus can be used to gather Kubernetes metrics. am expecting similar or more rich integration from telegraf. 

https://coreos.com/blog/monitoring-kubernetes-with-prometheus.html

Srinivas Kotaru

**Comment by sparrc** [comment]
there is already a kubernetes plugin: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/kubernetes

you can also use the prometheus input plugin to scrape kubernetes' prometheus endpoints.

Please let us know if there is something missing from these features that you need.
