### ISSUE TITLE
Add OpenStack plugin

### ISSUE THREAD

**Issue by yankcrime** [influxdata/telegraf#243]
A plugin which queries the various OpenStack APIs in order to obtain statistics about a given component, i.e number of running instances, vCPUs deployed, memory in use, and so on.  By way of comparison, there's a fairly comprehensive collectd plugin that's been written [here](https://github.com/rochaporto/collectd-openstack).

**Comment by sparrc** [comment]
Thanks for the suggestion @yankcrime. If anyone has time to work on this, please update the issue before you begin working so that your work is not duplicated :-)

**Comment by sfox-xmatters** [comment]
Hi

I'll be working on this plugin :)

**Comment by spjmurray** [comment]
Just a heads up that I'm taking this on as things have gone a bit stale in the last 7 months :)  This work is dependant on a few patch sets making it into gophercloud.  Will keep you updated.

**Comment by yankcrime** [comment]
@spjmurray My hero ❤️
