### ISSUE TITLE
CPU input not returning any metrics

### ISSUE THREAD

**Issue by dstaley** [influxdata/telegraf#2431]
## Bug report

I recently installed Telegraf, and while running the commands listed in the README, I noticed that it's not reporting any CPU metrics. The only reason I can think of that this might not be functioning is that I'm using a new Kaby Lake CPU, but I'm not sure if that'd impact Telegraf.

### Relevant telegraf.conf:

(Commented lines removed)
```[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
```

### System info:

Ubuntu 16.04.2 LTS, 4.8.0-36-generic
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
Intel(R) Pentium(R) CPU G4560 @ 3.50GHz

### Steps to reproduce:

1. `telegraf --input-filter cpu --output-filter influxdb config > telegraf-cpu.config`
2. `telegraf --config telegraf-cpu.config -test`

### Expected behavior:

Telegraf prints some CPU metrics.

### Actual behavior:

`* Plugin: inputs.cpu, Collection 1`

**Comment by sparrc** [comment]
--test output doesn't always report all metrics, because some metrics require multiple collections.

It will work if you actually run telegraf. There is a change in master to do 2 collections when in test mode.
