### ISSUE TITLE
[Feature Request] cpu_usage_percent / utili per process

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/telegraf#2433]
Hi

Ive seen a few closed issues/pr´s regarding getting % cpu utilization from processes (procstat etc).
(https://github.com/influxdata/telegraf/pull/1187)
Is there any plan for making this? The current cpu time is not really working for me.
I´ll have a naming standard for all running processes throughout the environment so not looking for catching all processes on every host rather the ones considered critical etc.

**Comment by sparrc** [comment]
this already exists, there is a "_usage" field available in the metrics

**Comment by discoduck2x** [comment]
thx @sparrc for takin your time to answere - i should have looked more closley.
however the -test switch doesnt seem to always show the correct info:

just shows collection 1 - no data, but when actually run the metrics are there...

![image](https://cloud.githubusercontent.com/assets/12600004/23205383/f2286a8c-f8e9-11e6-8f46-849cae34fbc1.png)

**Comment by sparrc** [comment]
CPU usage requires two "collections" to happen, which is why it doesn't show up in the 1st --test output, I can push a change for the procstat plugin to perform 2 collections in --test mode
