### ISSUE TITLE
Configuration flexibility in httpjson input plugin

### ISSUE THREAD

**Issue by nambissan** [influxdata/telegraf#2434]
Feature Request: [[inputs.httpjson]]

In the httpjson input plugin, is there a reason why strings and booleans are summarily rejected? It would have been nice for the choice to be optional and configurable.

For example in the output below, it would have been ideal to also have the option to:
1. save the metric 'hacurstate' 
2. convert and save the metrics 'hatotpktrx' and 'hatotpkttx' as numeric.

`
{
    "errorcode": 0,
    "message": "Done",
    "severity": "NONE",
    "hanode": {
        "hacurstatus": "YES",
        "hacurstate": "UP",
        "hacurmasterstate": "Primary",
        "transtime": "Tue Nov 22 19:05:54 2016",
        "hatotpktrx": "38329603",
        "hapktrxrate": 5,
        "hatotpkttx": "38316563",
        "hapkttxrate": 5,
    }
}
`

Desired Behavior:

[[inputs.httpjson]]
   save_string = [
       hacurstate
   ]
   convert_s2i = [
       hatotpktrx, hatotpkttx
   ]

**Comment by sparrc** [comment]
Might consider adding the ability to accept strings, but won't consider converting the types. You should fix whatever is sending the JSON to correctly format numbers.

**Comment by sparrc** [comment]
I'm going to close this because it would be fixed by #1363, and I prefer that issue because it is a more generic fix that would cover a larger range of features.
