### ISSUE TITLE
Feature: Exclude ObjectName from tags in Windows Perf Counters

### ISSUE THREAD

**Issue by JeffAshton** [influxdata/telegraf#2438]
There is a one-to-one correlation between ObjectName and Measurement.  Therefore unless you're trying to mix counters in a single measurement, storing the windows domain ObjectName is redundant.

Consider LogicalDisk example, "win_disk" is all "LogicalDisk" meansurements.

win_disk => LogicalDisk

```
  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "%% Idle Time", "%% Disk Time","%% Disk Read Time",
      "%% Disk Write Time", "%% User Time", "Current Disk Queue Length"
    ]
    Measurement = "win_disk"
```

**Comment by JeffAshton** [comment]
Provided 2 different versions, the first where the exclusion is done at the counter, and the second where it's done at the plugin.  I think I prefer option 2, as I don't see value in sending the ObjectName period.

**Comment by sparrc** [comment]
what exactly is the use-case for this? why do you need to exclude this tag? why can't you use [`tagexclude`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering)?

**Comment by JeffAshton** [comment]
Didn't realize tagexclude was there.  Thanks.
