### ISSUE TITLE
Collections took longer than interval

### ISSUE THREAD

**Issue by ciupade** [influxdata/telegraf#2451]
When i tried to collect metrics from larger amount of mssql databases (more than one), always i get an error:

Error in input [inputs.sqlserver]: driver: bad connection
Error: input [inputs.sqlserver] took longer to collect than collection interval (1m0s)

Even if i have 120 seconds interval the error appears.

If i have connected one sql server, on 60s interval its working, but when two or three sql servers are connected, errors appears.
 

 + Present config of telegraf agent:
interval = "60s"
metrics_buffer_size = 512
metric_buffer_size = 16384
metrics_buffer_limit = "10s"
collection_jitter = "10s"
flush_interval = "70s"
flush_jitter = "20s"

+ for influxdb output
timeout = "60s"

Version of telegraf 1.2.1
Version of influxdb 1.2.0

**Comment by sparrc** [comment]
This error message is indicating a problem with your connection to mssql. There is nothing telegraf can do if your servers are not responding to queries quickly enough. Since this is not a reproducible issue I'm going to close.
