### ISSUE TITLE
Plugin suggestion: Rancher

### ISSUE THREAD

**Issue by mytototo** [influxdata/telegraf#2453]
It would be nice to have an input plugin for Rancher server / OS. So, this way we'll be able to collect and report metrics of everything that happens on the server, agents and containers living inside the Rancher container itself.

**Comment by ahaynssen** [comment]
FYI you can get pretty close by running an agent on each host and collecting: inputs.cpu, inputs.mem, inputs.disk, and inputs.docker

We're doing this now and get a decent amount of metrics from our containers/Rancher Hosts.

**Comment by pythianarceri** [comment]
We feel the need for this, although getting generic system stats is fine, having the additional detail exposed by the Rancher API would be awesome.
The Prometheus community has a Rancher Exporter (https://github.com/infinityworksltd/prometheus-rancher-exporter) that exposes these stats to a Prometheus endpoint, i think some that code would be useful for someone willing to write a Rancher input for telegraf

**Comment by pythianarceri** [comment]
I worked around this by using the telegraf prometheus input with a container running the prometheus rancher-exporter
https://github.com/infinityworksltd/prometheus-rancher-exporter
If anyone is interested i can provide sample compose files

**Comment by sjwang90** [comment]
Looks like there's a solution for this but @garceri if you're interested in converting this into an external plugin we'd gladly add it to the list. You can find the docs on how how to convert it [here](https://github.com/influxdata/telegraf/tree/master/plugins/common/shim#telegraf-execd-go-shim), and once that's done please open a pull request to get it added to the [list of external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md).
