### ISSUE TITLE
[Feature Request] Append the container name as suffix to Docker Metric name 

### ISSUE THREAD

**Issue by kamalvpm777** [influxdata/telegraf#2464]
## Feature Request
[Feature Request] Append the container name as suffix to Docker Metric name 

###### Read metrics about docker containers######
[[inputs.docker]]
######suffix the metric name with container name######
   name_suffix = "_[container_names]"
######Docker Endpoint######
######To use TCP, set endpoint = "tcp://[ip]:[port]"######
######To use environment variables (ie, docker-machine), set endpoint = "ENV"######
  endpoint = "unix:///var/run/docker.sock"
######Only collect metrics for these containers, collect all if empty######
   container_names = []
######container_names = ["marathon"]######

###### Docker metrics that telegraf config file generates#####
docker_container_cpu,build-date=20150223,container_image=artifactory.us-east-1:1002/marathon-c7,container_name=marathon,cpu=cpu2,environment=devops,host=ip-00-00-00-00,license=v2,name=marathon,type=infra,vendor=CentOS container_id="gjreghrergeri234234lmddegrreg",usage_total=8113597990567i 

### Steps to reproduce:

1. Added "name_suffix" for docker and "_[container_name]" as a value to it
2. Still not able to retrieve the container name as a prefix appended to metric name

### Proposal:
Guidance on adding the docker container name as prefix to docker metric name

### Current behavior: 
docker_container_cpu[container_names]
(Not able to retrieve  the container name and print as suffix to metric name)

### Desired behavior:
docker_container_cpu_marathon
 (Assume "marathon" as container name, "docker_container_cpu" as metric name)

### Use case: [Why is this important (helps with prioritizing requests)]
In our production we are using telegraf to pull the docker metrics from "/var/run/docker.sh" and pushing the docker metrics to cloudwatch. So there are 10 dimensions sent for each container and dimension values are different for each container. So on plotting the dashboard in grafana with cloudwatch as datasource we are not able to use the single dashboard as dimension values are different for each container. 

So appending the container name as suffix to metric name we can apply the templating feature to pull the dimension values for all containers to plot  in single dashboard. Currently we are blocked on this , so any of the guidance and inputs will be greatly appreciated for us to move forward.

Hope the above info is clear , please let me know otherwise. 

Regards,
Kamal

**Comment by sparrc** [comment]
it's already a tag

**Comment by kamalvpm777** [comment]
Thanks for your response. Any inputs on how to pass the tags value to the "name_suffix" section

To be precise could you please look at below sample telegraf.conf and advise how to retrieve value of variable "[container_names]" within the name_suffix section. All am trying to achieve is retrieve value of container names and append that as suffix to metric name.

[[inputs.docker]]
  #suffix the metric name with container name
 name_suffix = "[container_names]"
 # Docker Endpoint
  #   To use TCP, set endpoint = "tcp://[ip]:[port]"
  #   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  # Only collect metrics for these containers, collect all if empty
    container_names = ["mesos-master"]

**Comment by danielnelson** [comment]
I don't think there is a way to do this since tags are much better, have you talked to the grafana project about how to display the data from their cloudwatch source?
