### ISSUE TITLE
[Feature Request] How to use taginclude for docker input to pull only CPU,Memory measurements and ignore all other docker metrics

### ISSUE THREAD

**Issue by kamalvpm777** [influxdata/telegraf#2465]
### Proposal: How do we pull only the CPU, Memory measurements of the docker container and ignore all other docker metrics. Can this be achieved through taginclude , any of the sample telegraf config with the example of taginclude for docker input would be really helpful.

#######telegraf.conf
[[inputs.docker]]
   taginclude = ["container_image","container_name","cpu"]
#######Docker Endpoint
#######To use TCP, set endpoint = "tcp://[ip]:[port]"
#######To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
#######Only collect metrics for these containers, collect all if empty
    container_names = []

### Current behavior: 
Even including the below taginclude still retrieves all the measurements  instead of pulling only CPU and memory metrics
taginclude = ["container_image","container_name","cpu","memory"]

### Desired behavior:
Expecting to see only CPU and memory measurements of docker

### Use case: [Why is this important (helps with prioritizing requests)]
For our production scenario usecases we would like to retrieve only the CPU and memory measurements for the docker, since docker input plugin retrieves all the metrics we are seeing some slowness , so trying to narron down to pull only CPU and memory metrics which is our interest at this time to ensure production stability. Kindly provide your thoughts as we would like to implement in our environment ASAP. Thanks for your help

**Comment by sparrc** [comment]
I think what you want is fielddrop & fieldpass, the metrics you are talking about are not tags

**Comment by mohamedhaleem** [comment]
@sparrc - could you post some examples of using fielddrop / fieldpass. I tried looking for documentation w/o success

**Comment by danielnelson** [comment]
We have some examples here: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-fieldpass-and-fielddrop
