### ISSUE TITLE
Add option to exclude per-backend stats for haproxy input

### ISSUE THREAD

**Issue by prburgu** [influxdata/telegraf#2470]
## Feature Request

Add option to exclude per-backend stats for haproxy input. Currently, haproxy input dumps everything from stats page. It contains stats for each backend in addition to aggregate "BACKEND". It would be nice to have an option to exclude per-backend stats to cut down the number of metrics that get sent to InfluxDB.

### Proposal:

Add option to exclude per-backend stats

### Current behavior:

No option to exclude per-backend stats

### Desired behavior:
Ability to exclude per-backend stats

### Use case: 
If there are backend nodes configured for haproxy and there are multiple processes configured for haproxy, the current behavior generates lot of data. The proposed solution helps cut down the generated data.

**Comment by phemmer** [comment]
Use the `tagdrop` option to accomplish this. https://docs.influxdata.com/telegraf/v1.2/administration/configuration/

**Comment by prburgu** [comment]
Thank you. tagdrop/tagpass solves my problem.
