### ISSUE TITLE
Script execution failing - only when telegraf is executed as systemctl service

### ISSUE THREAD

**Issue by TheReal1604** [influxdata/telegraf#2471]
## Bug report

Hi,

i try to execute a script which measures the hdd temp with "smartctl" (needs sudo rights). If i run the command "telegraf" from commandline all is fine. (as root) If i start the systemd service, the script execution fails. Maybe I miss something..

I tried the following things:

- give the telegraf user the appropriate rights:

/etc/sudoers:
```
## Next comes the main part: which users can run what software on
## which machines (the sudoers file can be shared between multiple
## systems).
## Syntax:
##
##      user    MACHINE=COMMANDS
##
## The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allow telegraf to run smartctl with sudo rights
telegraf ALL=NOPASSWD: /usr/sbin/smartctl

## Allows members of the 'sys' group to run networking, software,
## service management apps and more.
# %sys ALL = NETWORKING, SOFTWARE, SERVICES, STORAGE, DELEGATING, PROCESSES, LOCATE, DRIVERS

## Allows people in group wheel to run all commands
%wheel  ALL=(ALL)       ALL

## Same thing without a password
# %wheel        ALL=(ALL)       NOPASSWD: ALL

## Allows members of the users group to mount and unmount the
## cdrom as root
# %users  ALL=/sbin/mount /mnt/cdrom, /sbin/umount /mnt/cdrom

## Allows members of the users group to shutdown this system
# %users  localhost=/sbin/shutdown -h now

## Read drop-in files from /etc/sudoers.d (the # here does not mean a comment)
#includedir /etc/sudoers.d

```
- run systemd telegraf service as root:
/usr/lib/systemd/system/telegraf.service
```
[Unit]
Description=The plugin-driven server agent for reporting metrics into InfluxDB
Documentation=https://github.com/influxdata/telegraf
After=network.target

[Service]
EnvironmentFile=-/etc/default/telegraf
ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d ${TELEGRAF_OPTS}
User=root
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
KillMode=control-group

[Install]
WantedBy=multi-user.target
```

This seems to work - i get a telegraf  service executed from root:

```
root     13446 28464  0 08:19 pts/12   00:00:00 tail -f /var/log/telegraf/telegraf.log
root     14109     1  2 08:20 ?        00:00:00 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
root     14211  6329  0 08:20 pts/11   00:00:00 grep --color=auto telegraf
```
But the script fails again with the error below...

### Relevant telegraf.conf:
```
# # Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
   ## Commands array
   commands = [
     "/etc/telegraf/scripts/hddtemp.sh sda",
     "/etc/telegraf/scripts/hddtemp.sh sdb",
     "/etc/telegraf/scripts/hddtemp.sh sdd"
   ]
   ## Timeout for each command to complete.
   timeout = "5s"

   ## measurement name suffix (for separating different commands)
   name_suffix = "_hddtemp"

   ## Data format to consume.
   ## Each data format has it's own unique set of configuration options, read
   ## more about them here:
   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
   data_format = "influx"
```
### System info:
XenServer 7 (CentOS Based)
Telegraf Version: 1.2.1

### Steps to reproduce:

1. create script which executes a command with sudo rights:

Sample script:
```
#!/bin/bash

### Measure Temp and trim the output ###

echo "disktemp,name=$1,host=host1 temp=$(sudo smartctl --all /dev/$1 | grep Temperature_Celsius | cut -d '-' -f2| xargs)"i""
```

2. try to give your user the appropriate rights
3. "systemctl start telegraf"

### Expected behavior:
I should get readings from smartctl - this is also working if i execute telegraf as non service from shell.

### Actual behavior:
I get this in my telegraf logs:

`2017-02-27T07:24:20Z E! ERROR in input [inputs.exec]: Errors encountered: [ metric parsing error, reason: [invalid value], buffer: [disktemp,name=sdd,host=host1 temp=i], index: [44]], [ metric parsing error, reason: [invalid value], buffer: [disktemp,name=sda,host=maulwurfshuegel temp=i], index: [44]], [ metric parsing error, reason: [invalid value], buffer: [disktemp,name=sdb,host=maulwurfshuegel temp=i], index: [44]]`

The error message is ok - he is missing the output from the smartctl command. But i dont know why the output is missing :(.

### Use case: 

Measure the hdd-temp on linux based systems with only one command and without another plugin

**Comment by sparrc** [comment]
appears to be a permissions error, sorry we can't really help you to debug these issues. Could be that you need to specify the full path to smartctl. 

I would recommend logging into your machine as the telegraf user and trying out commands to get it right.

**Comment by ucycg** [comment]
Hey I encountered the exact same problem with a Python script that requires sudo rights. How do you got it working in the end? Is there really only the way of adding a wrapper script?

**Comment by t4ir1** [comment]
Hey guys, did you end up solving this?
In 2024 I am still having this issue and I found out that the best way to do it is just to force systemd to launch telegraf as root.
One can do this by modifying the unit file of telegraf: **sudo systemctl edit --full telegraf.service**

```
[Unit]
Description=Telegraf
Documentation=https://github.com/influxdata/telegraf
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
NotifyAccess=all
EnvironmentFile=-/etc/default/telegraf
**User=root
Group=root**
ImportCredential=telegraf.*
ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartForceExitStatus=SIGPIPE
KillMode=mixed
LimitMEMLOCK=8M:8M
PrivateMounts=true

[Install]
WantedBy=multi-user.target
```
