### ISSUE TITLE
Makefile Build Hangs

### ISSUE THREAD

**Issue by drasko** [influxdata/telegraf#2475]
## Bug report
Issuing `make` hangs while issuing commands by hand works.

### System info:
- Debian Sid
- `main.version=dev-65-g42a41d33, main.commit=42a41d33, main.branch=master`
- Go v1.8
```
drasko@Lenin:~/go/src/github.com/influxdata/telegraf$ go version
go version go1.8rc3 linux/amd64
```

**Comment by drasko** [comment]
Actually, looks like the issue is related to `go` command, that hangs when called from `make`...

**Comment by drasko** [comment]
Commenting out whole part that manipulates with `PATH` (https://github.com/influxdata/telegraf/blob/master/Makefile#L4-L8) actually resolves the issue.

**Comment by danielnelson** [comment]
Do you have GOBIN set?

**Comment by drasko** [comment]
Yep

**Comment by drasko** [comment]
Just tried unseting GOBIN - same story. Make hangs on `go get` (it hangs on `go install` also).

**Comment by danielnelson** [comment]
I can't reproduce this using the same version as above.  Take a look at what the PATH is changed to.

**Comment by drasko** [comment]
PATH changes from:
```
/usr/lib/go-1.8/bin:/home/drasko/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/drasko/android/adt-bundle-linux-x86_64/sdk/platform-tools:/home/drasko/android/adt-bundle-linux-x86_64/sdk/tools:/home/drasko/toolchain/mbed/gcc-arm-none-eabi/bin:/home/drasko/esp8266/esp-open-sdk/xtensa-lx106-elf/bin:/home/drasko/go/bin:/home/drasko/rebar3:/home/drasko/.local/bin
```
to 

```
/home/drasko/go/bin:/usr/lib/go-1.8/bin:/home/drasko/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/drasko/android/adt-bundle-linux-x86_64/sdk/platform-tools:/home/drasko/android/adt-bundle-linux-x86_64/sdk/tools:/home/drasko/toolchain/mbed/gcc-arm-none-eabi/bin:/home/drasko/esp8266/esp-open-sdk/xtensa-lx106-elf/bin:/home/drasko/go/bin:/home/drasko/rebar3:/home/drasko/.local/bin
```

This all looks normal to me - PATH is just prefixed with `/home/drasko/go/bin`, which is actually my `GOBIN`

**Comment by mark-rushakoff** [comment]
@drasko make sure there is not a file `/home/drasko/go/bin/go` that is overriding the real `go` binary.

**Comment by drasko** [comment]
@mark-rushakoff yep - that was the issue. Removed `/home/drasko/go/bin/go` - now everything works nicely.

Any idea where did it come from? I do not remember building the `go` tool and installing it manually - how did it land to my  `GOBIN`?

**Comment by mark-rushakoff** [comment]
If it was hanging when trying to run standard commands like `go install` or `go get` it was most likely not the "real" Go binary, but rather something that was installed inadvertently. If you previously ran `go install github.com/example/project/...` and there was a file `project/go/main.go` inside, it would have installed a binary named `go` to `$GOPATH/bin`.

The only thing we could do to prevent this would be to add `$GOPATH/bin` to the end of `$PATH` rather than the beginning. I'll leave that decision up to @danielnelson and @sparrc.

**Comment by sparrc** [comment]
the whole point of those lines is to give precedence to binaries that are in GOBIN, so it's working as intended AFAICT. I'm not sure where that broken `go` binary would have come from
