### ISSUE TITLE
LOGPARSER not waiting to write when reading file from beginning

### ISSUE THREAD

**Issue by manukgr** [influxdata/telegraf#2478]
Logparser plugin not considering flush interval even "flush_buffer_when_full = false" when "from beginning=true"
## Directions

I started parsing old logs to db, so logparser plugin was set to read from beginning. 
But the hero became greedy and started gathering and writing to db greedily and db got crashed

### Relevant telegraf.conf:
[agent]
    interval = "10s"
  round_interval = true
  metric_buffer_limit = 10
  flush_buffer_when_full = false
  collection_jitter = "1s"
  flush_interval = "10s"
  flush_jitter = "5s"
[[inputs.logparser]]
  files = ["path to file"]
  from_beginning = true
 patterns =[""]
 [[outputs.file]]
   files = ["stdout"]
### System info:
Windows
[Include Telegraf version, operating system name, and other relevant details]
Telegraf - version 1.0.1
### Steps to reproduce:

1. ... Use above config over big log file and set a pattern.
2. ...Telegraf will write to stdout or db greedily.

### Expected behavior:
It should wait for flush interval. 
### Actual behavior:
Acting greedy when "from_beginning = true"
### Logs of misbehaviour 

2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 154.3479ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 17.9767ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 17.5976ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 40.0832ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 18.5752ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 39.4783ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 28.3521ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 28.3519ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 30.6794ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 37.15ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 21.509ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 47.299ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 22.4855ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 22.4857ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 21.3095ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 34.2186ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 35.196ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 33.6131ms
2016/12/16 15:07:50 Output [influxdb] wrote batch of 1000 metrics in 25.4179ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 68.8091ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 37.1499ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 41.0601ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 26.0543ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 21.5078ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 19.5529ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 39.4798ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 46.9277ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 61.1391ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 19.3776ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 21.5095ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 119.6446ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 51.4907ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 19.2843ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 65.4994ms
2016/12/16 15:07:51 Output [influxdb] wrote batch of 1000 metrics in 16.8762ms
2016/12/16 15:07:52 Output [influxdb] wrote batch of 1000 metrics in 45.948ms
2016/12/16 15:07:52 Output [influxdb] wrote batch of 1000 metrics in 20.1943ms

## Feature Request
Should have functionality to skip few metrics while collecting.

### Proposal:
It should not read file greedily when "from_beginning=true"

### Use case: 
It can cause db crash, can consume more resources

**Comment by sparrc** [comment]
this is expected behavior, I don't know what you would expect it to do when from_beginning=true

**Comment by manukgr** [comment]
I want it to write after 10 seconds if from_beginning=true
