### ISSUE TITLE
Telegraf/Input/LogParser - Custom time stamp does not parse into InfluxDB time series

### ISSUE THREAD

**Issue by Kamalkp1978** [influxdata/telegraf#2484]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
Custom time stamp does not parse into InfluxDB time series

### Relevant telegraf.conf:

Using telegraf 1.2
```
# Configuration for telegraf agent
[agent]
## Default data collection interval for all inputs
  interval = "10s"
## Rounds collection interval to 'interval'
## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

## Telegraf will send metrics to outputs in batches of at most
## metric_batch_size metrics.
## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

## For failed writes, telegraf will cache metric_buffer_limit metrics for each
## output, and will flush this buffer on a successful write. Oldest metrics
## are dropped first when this buffer fills.
## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

## Collection jitter is used to jitter the collection by a random amount.
## Each plugin will sleep for a random time within jitter before collecting.
## This can be used to avoid many plugins querying things like sysfs at the
## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

## Default flushing interval for all outputs. You shouldn't set this below
## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"

## Jitter the flush interval by a random amount. This is primarily to avoid
## large write spikes for users running a large number of telegraf instances.
## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

## By default, precision will be set to the same timestamp order as the
## collection interval, with the maximum being 1s.
## Precision will NOT be used for service inputs, such as logparser and statsd.
## Valid values are "ns", "us" (or "µs"), "ms", "s".
  precision = "1s"

## Override default hostname, if empty use os.Hostname()
  hostname = ""
## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

# Stream and parse log file(s).
[[inputs.logparser]]
## Log files to parse.
## These accept standard unix glob matching rules, but with the addition of
## ** as a "super asterisk". ie:
## /var/log/**.log ->recursively find all .log files in /var/log
## /var/log/*/*.log ->find all .log files with a parent dir in /var/log
## /var/log/apache.log -> only tail the apache log file
   files = ["C:/Temp/TestSmall.log"]

## Read file from beginning.
   from_beginning = true

## Parse logstash-style "grok" patterns:
##   Telegraf built-in parsing patterns: https://goo.gl/dkay10
   [inputs.logparser.grok]
## This is a list of patterns to check the given log file(s) for.
## Note that adding patterns here increases processing time. The most
## efficient configuration is to have one pattern per logparser.
## Other common built-in patterns are:
##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
     patterns = ["%{CUSTOM_LOG}"]

## Name of the outputted measurement name.
     measurement = "IIS_Access_log"
## Full path(s) to custom pattern files.
## custom_pattern_files = []

## Custom patterns can also be defined here. Put one pattern per line.
     custom_patterns = '''
CUSTOM_LOG %{TIMESTAMP_ISO8601:time} %{WORD:sitename:tag} %{HOSTNAME:computername} %{IP:sip} %{URIPROTO:csmethod:tag} %{URIPATH:csstem} (?:%{NOTSPACE:csquery}|-) %{NUMBER:csport} (?:%{WORD:username}|-) %{IP:clientip} %{NOTSPACE:httpversion} %{NOTSPACE:useragent} (?:%{NOTSPACE:cookie}|-) (?:%{NOTSPACE:referer}|-) (?:%{HOSTNAME:host}:%{NUMBER:port}|%{HOSTNAME:host}|-) %{NUMBER:scstatus:int} %{NUMBER:scsubstatus:int} %{NUMBER:scwin32status:int} %{NUMBER:scbytes:int} %{NUMBER:csbytes:int} %{NUMBER:timetaken:int}
'''

################################################################
#                            OUTPUT PLUGINS                                   #
################################################################

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  ## The full HTTP or UDP endpoint URL for your InfluxDB instance.
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://localhost:8086"] # required
  ## The target database for metrics (telegraf will create it if not exists).
  database = "telegraf" # required

  ## Retention policy to write to. Empty string writes to the default rp.
  retention_policy = ""
  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
  write_consistency = "any"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
  ## Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  ## Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512
```
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf version 1.2
OS is Windows Server 2008 R2
Influx DB 1.2.0.1

### Steps to reproduce:

1. Need to parse IIS server access logs as per the sample below

#Fields: date time s-sitename s-computername s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs-version cs(User-Agent) cs(Cookie) cs(Referer) cs-host sc-status sc-substatus sc-win32-status sc-bytes cs-bytes time-taken
2017-02-03 17:18:17 W3SVC1 server1 101.123.112.50 GET /scripts/wiki.cgi - 80 - 10.223.1.124 HTTP/1.1 Mozilla/5.0+[en]+(X11,+U;+OpenVAS+8.0.8) - - serverat.amazonaws.com 404 0 2 1439 420 0

2. Using CUSTOM LOG pattern as per below
CUSTOM_LOG %{TIMESTAMP_ISO8601:timestamp} %{WORD:sitename:tag} %{HOSTNAME:computername} %{IP:sip} %{URIPROTO:csmethod:tag} %{URIPATH:csstem} (?:%{NOTSPACE:csquery}|-) %{NUMBER:csport} (?:%{WORD:username}|-) %{IP:clientip} %{NOTSPACE:httpversion} %{NOTSPACE:useragent} (?:%{NOTSPACE:cookie}|-) (?:%{NOTSPACE:referer}|-) (?:%{HOSTNAME:host}:%{NUMBER:port}|%{HOSTNAME:host}|-) %{NUMBER:scstatus:int} %{NUMBER:scsubstatus:int} %{NUMBER:scwin32status:int} %{NUMBER:scbytes:int} %{NUMBER:csbytes:int} %{NUMBER:timetaken:int}

3. When parsed, it does not convert the TIMESTAMP_ISO8601:timestamp to time series in INfluxDB and creating dashboard is difficult in such cases if the custom timestamps are not inserted into time series in influxdb

Looks like a bug to me in the Telegraf logparser

### Expected behavior:

The value in TIMESTAMP_ISO8601:timestamp or TIMESTAMP_ISO8601:time should be parsed and inserted into the time field of influxdb measurement

### Actual behavior:

After parsing I get additional filed as timestamp and if I use TIMESTAMP_ISO8601:time then it does not update the time series field in influxdb

### Additional info:
I get below errors if I use any of the timestamp modifiers like below

if I use ts-rfc3339 as timestamp modifier then output is below
2017/03/02 09:06:56 ERROR parsing 2017-02-21 11:34:47 to time layout [2006-01-02T15:04:05Z07:00]: parsing time "2017-02-21 11:34:47" as "2006-01-02T15:04:05Z07:00": cannot parse " 11:34:47" as "T"

if I use ts modifier then output is below
2017/03/02 09:04:39 ERROR parsing timestamp [2017-02-21 12:31:08], could not find any suitable time layouts.

[Include gist of relevant config, logs, etc.]

## Feature Request
Custom timestamp should be parsed to time series in INfluxDB

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment]
You need to use a timestamp modifier at the end of your pattern, see https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

**Comment by Kamalkp1978** [comment]
Hi Sparrc

Can you provide me an example please, I tried all the combinations but none work

**Comment by Kamalkp1978** [comment]
Tried custom as well like 

%{TIMESTAMP_ISO8601:timestamp:ts-"YYYY-MM-DD HH:MM:SS"}

got below error

2017/03/02 09:46:37 ERROR parsing 2017-02-21 15:45:35 to time layout [YYYY-MM-DD HH:MM:SS]: parsing time "2017-02-21 15:45:35" as "YYYY-MM-DD HH:MM:SS": cannot parse "2017-02-21 15:45:35" as "YYYY-MM-
DD HH:MM:SS"

**Comment by jpereira** [comment]
I have the same issue!

**Comment by danielnelson** [comment]
For your case you need a pattern like this:
```
patterns=['''%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02 15:04:05"}''']
```

What was happening is that while TIMESTAMP_ISO8601 parsed the datetime out of your logfile successfully, telegraf was unable to convert it internally into a timestamp for your metric.  As none of the timestamp modifiers match your date you must use a custom modifier.  From the plugin README if you follow the (link)[https://golang.org/pkg/time/#Parse) you will find the correct format for the modifier string:

>  Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be
> ```Mon Jan 2 15:04:05 -0700 MST 2006```
> would be interpreted if it were the value; it serves as an example of the input format. The same interpretation will then be made to the input string.

I will create a ticket to improve the documentation.

**Comment by Kamalkp1978** [comment]
Thank you, I did found this solution long back and realized that I should have posted it to this thread as well. Its resolved now, thanks for responding.


Thanks,
Kamal Padhiar

**Comment by Erando89** [comment]
> 
> 
> You need to use a timestamp modifier at the end of your pattern (ie, `%{TIMESTAMP_ISO8601:timestamp:ts-<insert here>}`), see https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser
> 
> We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list or the #influxdb channel on [Gopher Slack](https://www.influxdata.com/announcing-the-influxdb-slack-channel/).

The link you provided has become old as the content got overridden in time. This is the correct link now: https://github.com/influxdata/telegraf/tree/12db3b91208415364cc1649844e77143a1221a1f/plugins/inputs/logparser
