### ISSUE TITLE
Procstat plugin to get stats of all running process

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#2490]
Is it possible to get the procstat for all running processes instead of providing a list of pid or a pattern to match. Is it possible to define a pattern of * To watch for all running processes. Or any other means to get all processes list and their stats

**Comment by sparrc** [comment]
nope, this would create too high of cardinality in order to separate the measurements, and would also create significant system load just gathering the metrics

**Comment by sureshsubramaniam** [comment]
Say for example when a app performance is slow and if I wanted to get the detailed status of all running process at that time and their stats, the metricbeat provides a process plugin which can be inspired if we really wanted to port similar functions in telegraf. As of my initial comparison with metric beat this is one piece which was missing in telegraf

**Comment by sparrc** [comment]
OK, we can reconsider it if you link to documentation and provide a fuller explanation and feature request

**Comment by sureshsubramaniam** [comment]
Adding the links of meteicbeat document and code that can be used for consideration 
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-process.html
GitHub code of the process plugin in metricbeat
https://github.com/elastic/beats/tree/master/metricbeat/module/system/process

The reason for feature request is we are covering much more than metricbeat but during a application issue triage it would need the system statistics which can help to identify the root cause. The current implementation of procstat needs the list of process to be monitored but in a dynamic environment user may not have control of the known processes, it would be useful to add the entire list of processes in the machine which can also help solve an application issue upfront when a process peaks it's usage and will help the application team to look into scaling or fixing the application before the actual end user reports a issue,  this would help us to do a proactive monitoring rather than being reactive.
Happy to know that this will be reconsidered for feature request. Ready to do a beta test if this kicks off
