### ISSUE TITLE
Feature Request: Procstat plugin to get stats of all running process

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#2497]
## Feature Request

Adding the links of metricbeat document and code that can be used for consideration
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-process.html
GitHub code of the process plugin in metricbeat
https://github.com/elastic/beats/tree/master/metricbeat/module/system/process

The reason for feature request is we are covering much more than metricbeat but during a application issue triage it would need the system statistics which can help to identify the root cause. The current implementation of procstat needs the list of process to be monitored but in a dynamic environment user may not have control of the known processes, it would be useful to add the entire list of processes in the machine which can also help solve an application issue upfront when a process peaks it's usage and will help the application team to look into scaling or fixing the application before the actual end user reports a issue, this would help us to do a proactive monitoring rather than being reactive.
Happy to know that this will be reconsidered for feature request. Ready to do a beta test if this kicks off

### Proposal:
In corporate an option ofr collecting metrics of all running processes in linux/windows machines, leveraging some of the work that has already been done on the metricbeat

### Current behavior:
There is no option to list all metrics for all running process and the regex of .* does not match all processes

### Desired behavior:
Internal toggle for collecting all process metrics or just a specific process

### Use case: [Why is this important (helps with prioritizing requests)]
This is very much helpful in application troubleshooting issues and easy to nail down the root cause

**Comment by phemmer** [comment]
> the regex of .* does not match all processes

It does for me.

`telegraf.conf`:
```
[[outputs.file]]

[[inputs.procstat]]
	pattern = ".*"
```

```
# telegraf -config /tmp/telegraf.conf -test | grep '> procstat' | wc -l
177

# ps -e | wc -l
177
```

**Comment by danielnelson** [comment]
@sureshsubramaniam Can you check if the the above solution works for you?  Also, a warning, if you run this for extended periods of time you will have some real cardinality issues.

**Comment by sureshsubramaniam** [comment]
@danielnelson let me check on this and update you

**Comment by danielnelson** [comment]
Feel free to reopen if its not working.

**Comment by chezneUE** [comment]
this does not work, tried multiple options it shows each process but not duplicates.

Really the procstat is supposed to display all that is visible using the top command in linux, i run top and there are multiple python processes, yet telegraf [[inputs.procstat]] only showing one process with that name when in reality there are three processes with the exact name all with their separate CPU usage.

It shows up when i run top but not viewable from telegraf, also i allowed the pid to be passed in and the pid for the multiple processes with the same name the pid keeps changing, so it is only going off the unique name and not by pid.

Think this is a issue.

**Comment by chezneUE** [comment]
Ok nevermind above post, when running "service telegraf restart" to check configuration changes, the Telegraf software is not completely quitting and as a result the new config cannot be picked up.
