### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by loque1** [influxdata/telegraf#2502]
## Question/Feature

Currently the influxdb output for jolokia uses the name definition and adds it to the output

so if the name is defines as region.env.appname then in grafana we can create a template with the jolokia name. We currently have multiple environments with the same application deployed in multiple regions so we would like to create a template so the name portion could be split and create template variables for region, env, appname. Currently there is no way to define extra tag information apart form the name or pass a delimiter to them name portion to spit it up; unless I have missed something in the configuration.

The other point is that the output of the metrics in question when stored in influxdb is stored as the name+mbean+attribute. So for instance activemq ques all have names so I would prefer the output only have the name and the que name and the attributes so something like

que.DLQ_TST.MinEnqueueTime=0.  

The current output is

que.org.apache.activemq:brokerName=localhost,destinationName=DLQ_TST,destinationType=Queu,type=Broker.MinEnqueueTime=0,

which again makes it harder to template.

If there is an alternative on how we can do this I would really appreciate knowing how to do this.

**Comment by sparrc** [comment]
I think this will be fixed with https://github.com/influxdata/telegraf/pull/2278
