### ISSUE TITLE
Unable to read custom mibs with snmp module

### ISSUE THREAD

**Issue by Touchedegris** [influxdata/telegraf#2503]
I am trying to load custom mibs for snmp input, but I see a "Permission Denied" to the mibs directory.  However I can walk, translate or table my mibs within net-snmp commands.  My custom mib folder has the same rights as other working mib folders (root:root, 644).

System: Ubuntu 16.04
Telegraf: 1.2.1-1

Error message:
Mar  7 13:11:30 Grafana telegraf[852]: 2017-03-07T18:11:30Z E! ERROR in input [inputs.snmp]: initializing table chassis: translating: exit status 2: /usr/share/mibs/ALE//ALCATEL-IND1-TIMETRA-CHASSIS-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//ALCATEL-IND1-GVRP-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//ALCATEL-IND1-CONFIG-MGR-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//ALCATEL-IND1-PPPOE-IA-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//ALCATEL-IND1-VM-SNOOPING-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//IANA-ADDRESS-FAMILY-NUMBERS-MIB.mib: Permission denied
Mar  7 13:11:30 Grafana telegraf[852]: /usr/share/mibs/ALE//ALCATEL-IND1-GLOBALROUTETABLE-MIB.mib: Permission denied

MIB files located under /usr/share/mibs/ALE/

snmp.conf:
mibdirs /usr/share/mibs/ALE/:/usr/share/mibs/iana/:/usr/share/mibs/ietf/
mibs +ALL

sudo -u telegraf cat /usr/share/mibs/ALE/ALCATEL-IND1-CHASSIS-MIB.mib
cat: /usr/share/mibs/ALE/ALCATEL-IND1-CHASSIS-MIB.mib: Permission denied

I also tried to change ownership with chown -R telegraf:telegraf /usr/share/mibs/ALE and still unable to read the files.

**Comment by danielnelson** [comment]
This seems like a permission issue and not a telegraf issue, check that your directories are chmod 755 and the files are 644 or such.  Make sure you can read and list the mibs directory.
```
sudo -u telegraf ls /usr/share/mibs/ALE
sudo -u telegraf cat /usr/share/mibs/ALE/ALCATEL-IND1-CHASSIS-MIB.mib
```
