### ISSUE TITLE
win_perf_counter does not gather some metrics

### ISSUE THREAD

**Issue by janvh5** [influxdata/telegraf#2504]
Some metrics are gathered others are not. All metrics validates ok. Problem exist on both Windows Server 2016 as well as Windows 10 client. Windows installations are English US. Tested with PreVistaSupport= true - it does not help. Telegraf v 1.2.1
Output from telegraf --test:

C:\telegraf>telegraf --config telegraf.conf --test
* Plugin: inputs.win_perf_counters, Collection 1
Valid: \LogicalDisk(*)\% Idle Time
Valid: \LogicalDisk(*)\Avg. Disk sec/Read
Valid: \LogicalDisk(*)\Avg. Disk sec/Write
Valid: \LogicalDisk(*)\Current Disk Queue Length
> win_disk,instance=HarddiskVolume1,objectname=LogicalDisk,host=Dell_XPS13 Current_Disk_Queue_Length=0 1488910425000000000
> win_disk,instance=C:,objectname=LogicalDisk,host=Dell_XPS13 Current_Disk_Queue_Length=0 1488910425000000000

**Comment by matso42** [comment]
I see the same but on Processor and Memory classes.
On processor I get no data for  
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",

On Memory I get Available_Bytes, Pool_Nonpaged_Bytes, Pool_Paged_Bytes but not "Cache Faults/sec", "Demand Zero Faults/sec", "Page Faults/sec", "Pages/sec" or "Transition Faults/sec"

I'm using this config on Win7 64 bit Enterprise with telegraf 1.2.1

[[inputs.win_perf_counters]]
  PreVistaSupport = true
  PrintValid = true
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

[[inputs.win_perf_counters.object]]
    # Disk times and queues
    ObjectName = "LogicalDisk"
    Instances = ["C:"]
    Counters = ["Free Megabytes", "% Free Space"]
    Measurement = "win_disk"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*)

[[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back, such as from the Memory object.
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes"
    ]
    Instances = ["------"] # Use 6 x - to remove the Instance bit from the query.
    Measurement = "win_mem"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

**Comment by bullshit** [comment]
I had the same issues with .NET Clr Memory. I started telegraf from a admin cmd and it worked. Maybe there is a permission problem?

**Comment by matso42** [comment]
I have tried both with User and Administrator rights without success. 
It could be a permission problem still since my environment is rather GPO heavy but I don't think so. I did a powershell script reading the same data using get-counter and that collects the data without problem. The script did have the language problem though so I had to do some workarounds on that

**Comment by bullshit** [comment]
You should add a specific a processor instance identifier or an asterisk
for example
```
[[inputs.win_perf_counters]]
  PrintValid = true
[[inputs.win_perf_counters.object]]
  # Processor usage, alternative to native, reports on a per core.
  ObjectName = "Processor"
  Instances = ["*"]
  Counters = [
  "% Idle Time",
  "% Interrupt Time",
  "% Privileged Time",
  "% User Time",
  "% Processor Time",
  ]
  Measurement = "win_cpu"
  # Set to true to include _Total instance when querying for all ().
  #IncludeTotal=false
```
output:
```
2017-03-22T10:16:18Z D! Attempting connection to output: discard
2017-03-22T10:16:18Z D! Successfully connected to output: discard
2017-03-22T10:16:18Z I! Starting Telegraf (version 1.2.1)
2017-03-22T10:16:18Z I! Loaded outputs: discard
2017-03-22T10:16:18Z I! Loaded inputs: inputs.win_perf_counters
2017-03-22T10:16:18Z I! Tags enabled: host=winston-pc
2017-03-22T10:16:18Z I! Agent Config: Interval:1s, Quiet:false, Hostname:"winston-pc", Flush Interval:1s
Valid: \Processor(*)\% Idle Time
Valid: \Processor(*)\% Interrupt Time
Valid: \Processor(*)\% Privileged Time
Valid: \Processor(*)\% User Time
Valid: \Processor(*)\% Processor Time
win_cpu,instance=0,objectname=Processor,host=winston-pc Percent_Idle_Time=82.986083984375 1490177780000000000
win_cpu,objectname=Processor,host=winston-pc,instance=1 Percent_Idle_Time=84.28373718261719 1490177780000000000
win_cpu,instance=0,objectname=Processor,host=winston-pc Percent_Interrupt_Time=7.459342002868652 1490177780000000000
win_cpu,instance=1,objectname=Processor,host=winston-pc Percent_Interrupt_Time=0 1490177780000000000
win_cpu,instance=0,objectname=Processor,host=winston-pc Percent_Privileged_Time=11.17626953125 1490177780000000000
win_cpu,objectname=Processor,host=winston-pc,instance=1 Percent_Privileged_Time=9.313557624816895 1490177780000000000
win_cpu,objectname=Processor,host=winston-pc,instance=0 Percent_User_Time=5.594534397125244 1490177780000000000
win_cpu,instance=1,objectname=Processor,host=winston-pc Percent_User_Time=5.594534397125244 1490177780000000000
win_cpu,instance=0,objectname=Processor,host=winston-pc Percent_Processor_Time=17.94682502746582 1490177780000000000
win_cpu,instance=1,objectname=Processor,host=winston-pc Percent_Processor_Time=16.081979751586914 1490177780000000000
```

**Comment by aisog** [comment]
Hi Unfortunatelly the conf not work for win_cpu

[[inputs.win_perf_counters]]
  PrintValid = true
[[inputs.win_perf_counters.object]]
 # Processor usage, alternative to native, reports on a per core.
  ObjectName = "Processor"
  Instances = ["*"]
  Counters = [
  "% Idle Time",
  "% Interrupt Time",
  "% Privileged Time",
  "% User Time",
  "% Processor Time",
  ]
  Measurement = "win_cpu"
  # Set to true to include _Total instance when querying for all ().
  IncludeTotal=true
----------------------------------------------------------------------
PS C:\Program Files\Telegraf> C:\"Program Files"\Telegraf\telegraf.exe --config C:\"Program Files"\Telegraf\telegraf.conf --test
* Plugin: inputs.win_perf_counters, Collection 1
Valid: \Processor(*)\% Idle Time
Valid: \Processor(*)\% Interrupt Time
Valid: \Processor(*)\% Privileged Time
Valid: \Processor(*)\% User Time
Valid: \Processor(*)\% Processor Time
Valid: \LogicalDisk(*)\% Idle Time
Valid: \LogicalDisk(*)\% Disk Time
Valid: \LogicalDisk(*)\% Disk Read Time
Valid: \LogicalDisk(*)\% Disk Write Time
Valid: \LogicalDisk(*)\Current Disk Queue Length
Valid: \Memory\Available Bytes
Valid: \Memory\Cache Faults/sec
Valid: \Memory\Demand Zero Faults/sec
Valid: \Memory\Page Faults/sec
Valid: \Memory\Pages/sec
Valid: \Memory\Transition Faults/sec
Valid: \Memory\Pool Nonpaged Bytes
Valid: \Memory\Pool Paged Bytes
> win_disk,instance=HarddiskVolume2,objectname=LogicalDisk,host=WIN-6795JJ0CKH1 Current_Disk_Queue_Length=0 1491297806000000000
> win_disk,objectname=LogicalDisk,host=WIN-6795JJ0CKH1,instance=C: Current_Disk_Queue_Length=0 1491297806000000000
> win_disk,instance=HarddiskVolume60,objectname=LogicalDisk,host=WIN-6795JJ0CKH1 Current_Disk_Queue_Length=0 1491297806000000000
> win_disk,instance=HarddiskVolume64,objectname=LogicalDisk,host=WIN-6795JJ0CKH1 Current_Disk_Queue_Length=0 1491297806000000000
> win_mem,objectname=Memory,host=WIN-6795JJ0CKH1 Pool_Nonpaged_Bytes=274096128 1491297806000000000
> win_mem,objectname=Memory,host=WIN-6795JJ0CKH1 Available_Bytes=391342096384 1491297806000000000
> win_mem,objectname=Memory,host=WIN-6795JJ0CKH1 Pool_Paged_Bytes=457891840 1491297806000000000

**Comment by bullshit** [comment]
Please try it without the "--test" param. sometimes you have to wait for the second interval

**Comment by danielnelson** [comment]
@matso42 Any update after not using `--test`?

**Comment by aisog** [comment]
Hi It occurs that metrics was send by telegraf fine this was a issue in grafana query, the right query whhen you have more than one cpu is:
SELECT mean("Percent_Idle_Time") AS "% Idle Time", mean("Percent_Interrupt_Time") AS "% Interrupt Time", mean("Percent_Privileged_Time") AS "% Privileged Time", mean("Percent_Processor_Time") AS "% Processor Time", mean("Percent_User_Time") AS "% User Time" FROM "win_cpu" WHERE "instance" = '_Total' AND "host" =~ /^$server$/ AND $timeFilter GROUP BY time(10s) fill(null).
Thanks you can close the case
