### ISSUE TITLE
Feature request: Elasticsearch extensible for aggregation queries 

### ISSUE THREAD

**Issue by lpic10** [influxdata/telegraf#2506]
## Feature Request

Similar to postgresql_extensible, allow to define ES aggregation queries in that the results (aggregated data) can feed the different outputs.

It is usual in Elasticsearch, when used as log management tool, to limit the number of days of logs to keep in order to limit storage consumption. But there is sometimes relevant information in these logs that may be necessary for a longer period, eg. if that information is used in a set of graphs or the information is used for anomaly detection and other monitoring needs. This plugin could be used to extract/calculate some useful metrics from events, logs and documents indexed in ES and store these metrics into a TSDB such as InfluxDB. 

The idea here is to get some early feedback about interest/feature set/etc. I have something similar to this for my own needs and I may submit a PR when it is more "ready" (code a bit more clear and documented).

### Proposal:
Each aggregation query could be defined by the following parameters:

* name of the aggregation: string used for the measurement name
* query: a lucene query to filter the data before aggregation
* metrics aggregation function: one of the supported [functions ](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics.html) (it can be limited to few functions initially, as avg/sum/min/max/count)
* metric fields: list of the fields in a document to apply the metrics aggregation function
* tags: list of fields in a document to apply a "terms" aggregation (thus yielding results per tag, eg. per hostname and per FS path) 
* period: period of time of the aggregation (eg. "5m" will perform aggregation over last 5 minutes)
* datetime field: name of the datetime field in the ES document (eg. @timestamp)

### Use cases:

Calculate time-based metrics from events stored in ES, such as logs, events and metrics. 

* Count number of a particular log message per minute, aggregating per host or per instance
* Calculate the average response time and bytes from logs, per status code  
* Calculate the max value of a particular field seen in last 5 minutes, per use-case and per host

**Comment by sureshsubramaniam** [comment]
Would be interested to see this feature in telegraf

**Comment by sureshsubramaniam** [comment]
👍👍

**Comment by brice86** [comment]
+! This would be awesome!

**Comment by lpic10** [comment]
So, another unintended use-case of this plugin is to allow alarming over data stored in Elasticsearch (this is a paid feature of Elastic stack), we just figured this out using this internally for few use cases. 

For someone already using a monitoring stack, (eg. TICK),  it makes possible for telegraf to query & aggregate Elasticsearch data and output it to InfluxDB, where alarms could be built using Kapacitor.

Anyone interested in this could have a look or test #3536, I believe there are tons of improvements but it should work for most use-cases as it is.
