### ISSUE TITLE
The http_response plugin does not maintain headers when following redirects.

### ISSUE THREAD

**Issue by zrice57** [influxdata/telegraf#2507]
## Bug report
After following redirects, the http_response plugin uses the default user-agent of 
"Go-http-client/1.1".

### Relevant telegraf.conf:
I'm including the erb used to generate my config.
[[inputs.http_response]]
  address = "url"
  response_timeout = "10s"
  method = "GET"
  follow_redirects = true
  interval = "30s"

  [inputs.http_response.headers]
    User-Agent = "ServiceUptime"

### System info:
[Include Telegraf version, operating system name, and other relevant details]
Centos 7.3
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)

### Proposal:
Use the defined headers during redirect requests.

### Use case: [Why is this important (helps with prioritizing requests)]
It makes it difficult to properly filter the requests from analytics data.

**Comment by danielnelson** [comment]
I believe this was fixed by changes in go 1.8, which we are planning to use to build telegraf 1.3.
- https://github.com/golang/go/issues/4800
- https://beta.golang.org/doc/go1.8#net_http
