### ISSUE TITLE
Build instructions does not work on Windows

### ISSUE THREAD

**Issue by matso42** [influxdata/telegraf#2510]
The build instructions says

From Source:

Telegraf manages dependencies via gdm, which gets installed via the Makefile if you don't have it already. You also must build with golang version 1.8+.

Install Go
Setup your GOPATH
Run go get github.com/influxdata/telegraf
Run cd $GOPATH/src/github.com/influxdata/telegraf
Run make

Since Windows doesn't have a native make this needs an update for providing a working make on the windows plattform (would cygwin make work?)

**Comment by sparrc** [comment]
you can install make, or just run the commands therein

**Comment by brianbaker** [comment]
Also worth noting that on windows you'll need to run `make windows` and not just `make`.
