### ISSUE TITLE
Feature Request Elastic input namespace collision

### ISSUE THREAD

**Issue by DianaOlympos** [influxdata/telegraf#2511]
### Proposal:
Change the namespace of the local measurements outputed by the elastic input or the cluster health indices one because they collide. I would be happy to write a PR on it, but i am not sure if we would prefer to change the namespace of the local data or of the cluster wide one. 
Another possible problem is that by changing namespace, we would probably create a discontinuity of data due to measurements name changing...

### Current behavior:
Local tags generated here https://github.com/influxdata/telegraf/blob/master/plugins/inputs/elasticsearch/elasticsearch.go#L270
create a `elasticsearch_indices` measurement for local Node stats.

But here : https://github.com/influxdata/telegraf/blob/master/plugins/inputs/elasticsearch/elasticsearch.go#L312 we create another `elasticsearch_indices measurement` with different data. 

Which means that data can collide and do share a namespace.

### Desired behavior:
Different measurement name for these data. My first idea would be to rename the Node stats under `elasticsearch_local_` namespace. But we could also change the cluster wide one to something like `elasticsearch_cluster_indices`

I saw https://github.com/influxdata/telegraf/pull/2456 but it does not address that. 

### Use case:

When someone pull both local and cluster health data, the tow measurements clash, mixing up separated data. I ask here for two reasons : 

1. Which namespacing should we change
2. If we change that measurement name, we will break the continuity of data for people already using it.

**Comment by sparrc** [comment]
the measurements don't collide because the tags separate them into different series.

I'd prefer not to change this behavior unless you have a very compelling reason why you can't use  tags to separate these.
