### ISSUE TITLE
SQL Server Input: Connection reset by peer issue after upgrading to SQL server 2014 SP2

### ISSUE THREAD

**Issue by sagarshetty** [influxdata/telegraf#2524]
## Bug report
I had a Telegraf instance running  for the past week collecting metrics from 3 SQL Server 2014 instances that were part of the same AG and writing to influxDB. I upgraded all the servers from SQL server 2014 SP1 to SQL server 2014 SP2 and this started resulting in a "connection reset by peer" error message in the Telegraf logs.  I then pointed telegraf to  a SQL server 2014 SP1 instance  and it worked but its not working for SQL server 2014 SP2.

### Relevant telegraf.conf:
I am Using the SQL server input plugin as described here. https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver 

### System info:
Telegraf v1.2.1 on SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11

InfluxDB version 1.2

SQL server 2014 SP2. 

### Steps to reproduce:

1. Install Telegraf v1.2.1
2. create config file which writes to influxDB on local host and reads from a SQL Server 2014 instance on a remote server using the input plugin config example and login info as descried in the input plugin link https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver 

### Expected behavior:
Telegraf should be able to read metrics from a SQL server 2014 SP2 instance and flush it to influxDB with no issues as it did for SQL server 2014 SP1.

### Actual behavior:
Telegraf reports a connection reset by peer message and does not write anything to influx DB. Doing a profiler trace on the SQL server side shows the telegraf account login into the server then logging out. 

### Additional info:
I am using port 2747 on my sql server. I am using sql login exactly as defined in the input plugin article. I am able to manually connect to the server using the connection string and port that I put into my telegraf config and run queries on it. 

[Include gist of relevant config, logs, etc.]
XXXX 4:01pm usr/bin] telegraf -config telegraf_mssql.conf
2017-03-10T00:02:09Z I! Starting Telegraf (version 1.2.1)
2017-03-10T00:02:09Z I! Loaded outputs: influxdb
2017-03-10T00:02:09Z I! Loaded inputs: inputs.sqlserver
2017-03-10T00:02:09Z I! Tags enabled: host=XXXX
2017-03-10T00:02:09Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"XXXX", Flush Interval:10s
2017-03-10T00:02:10Z E! ERROR in input [inputs.sqlserver]: read tcp xx.xx.xx.x:49170->xx.xx.xxx.xxx:2747: read: connection reset by peer

**Comment by danielnelson** [comment]
Anything interesting in the SQL server logs?  This error indicates the other side has closed the connection, perhaps there is an authentication issue.

**Comment by sagarshetty** [comment]
I checked the SQL server logs and the windows event logs I did not find any errors in them related to connection failures. When I run the profiler I can see the login coming in and then getting logged out.

![image](https://cloud.githubusercontent.com/assets/18715766/23815127/74066938-059b-11e7-9d83-9c1502e75f8d.png)

**Comment by sagarshetty** [comment]
This is what I have found on further debug. SQL server input plugin opens 10 connection to SQL server simultaneously. All 10 are logged out immediately. I see the following issue when I query sys.dm_os_ring_buffers for the closed connections.

"A fatal error occurred while reading the input stream from the network. The session will be terminated"

error: 4014 state:13 severity:20 OS error:50.

Can someone confirm that the SQL server input plugin works with SQL server 2014 SP2. I know that the SP2 upgrade itroduced TSL 1.2 can that be causing some compatibility issues?

**Comment by rjtsdl** [comment]
I was facing a similar issue. My workaround is to set maxopenconns to unlimited. Hope it helps

**Comment by etangle** [comment]
I was getting similar error messages on sql server 2005, used encrypt=disable in connection string, and it worked...

**Comment by sagarshetty** [comment]
The maxopenconnections is set to max and I had already tried the encrypt = disable option that did not work.

**Comment by sheldonhull** [comment]
I had a similar issue with 2016. When I switched from Integrated Security to a SQL Login, I was able to proceed without error. Before this it failed. 
Did this resolve anyone else's issue?

**Comment by m82labs** [comment]
Does this issue still need work done on it?

**Comment by danielnelson** [comment]
@sagarshetty I'm going to close but if this is still an issue for you can you retest with 1.8.0-rc1 or newer?
