### ISSUE TITLE
Collecting host stats from within docker containers with Telegraf 1.1

### ISSUE THREAD

**Issue by garceri** [influxdata/telegraf#2527]
In version 0.1X of Telegraf the HOST_PROC/HOST_SYS/HOST_ETC environment variables could be used to override the mountpoint location of /sys /proc and /etc filesystem, this allowed collecting host metrics from within a docker container.Looks like this is no longer supported on 1.1
From looking at the /plugins/inputs/system/processes.go file i can see that the /proc location is hardcoded.
Would it be possible to enable a configuration option for the input plugins to allow specifying the alternate mountpoint ?
Something like:
```
sysfs_mount = /rootfs/sys
procfs_mount = /rootfs/proc

```

**Comment by danielnelson** [comment]
I believe this functionality is provided by gopsutil so it should work.  If it is not, can you provide the plugin you are using, the base image you are experiencing the problem in, and any other relevant information so it can be duplicated.

https://github.com/shirou/gopsutil#usage

**Comment by pythianarceri** [comment]
Yep, the issue seems to be related to the system/process input plugin
if you look at [this](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/processes.go#L134), you will noticed that /proc is hardcoded there, that makes impossible to get host process stats

**Comment by danielnelson** [comment]
Got it, we can do the proposed change.  Maybe named `proc_path`, `sys_path`.

**Comment by diegito** [comment]
I believe I have a related problem with my docker-telegraf  - with `net` plugin enabled - picking up only the interfaces from within the docker container (i.e. I can see only eth0 interface), and not the interfaces of the system.

**Comment by danielnelson** [comment]
@diegito Can you open a new issue your net problem?

**Comment by danielnelson** [comment]
`HOST_PROC` support has been added for the processes plugin, will be in 1.4.  Leaving this issue open to add config file support.

**Comment by danielnelson** [comment]
I created a new issue #4006 to track the remaining work.
