### ISSUE TITLE
Build failed in macOS 

### ISSUE THREAD

**Issue by jacktang** [influxdata/telegraf#2529]
## Bug report

```
> Restoring /Users/jacktang/gocodez/src/gopkg.in/fatih/pool.v2 to 6e328e67893eb46323ad06f0e92cb9536babbabc
> Restoring /Users/jacktang/gocodez/src/gopkg.in/mgo.v2 to 3f83fa5005286a7fe593b055f0d7771a7dce4655
> Restoring /Users/jacktang/gocodez/src/gopkg.in/yaml.v2 to 4c78c975fe7c825c6d1466c42be594d1d6f3aba6
go install -ldflags \
		"-X main.version=dev-85-g7a5d857 -X main.commit=7a5d857 -X main.branch=master" ./...
# github.com/influxdata/telegraf/plugins/outputs/prometheus_client
plugins/outputs/prometheus_client/prometheus_client.go:75: p.server.Shutdown undefined (type *http.Server has no field or method Shutdown)
make: *** [build] Error 2
```

### System info:

* OS: macOS Sierra 10.12.3
* go version: go1.7.5 darwin/amd64
* git show: commit 7a5d8578467ac6

### Steps to reproduce:

make

**Comment by mark-rushakoff** [comment]
As indicated in the "Building from source" section of the README:

> You also must build with golang version 1.8+.

I'm leaving this issue open for @danielnelson to decide if this failure mode is acceptable or if we should fail more loudly when the Go version is incorrect.

**Comment by jacktang** [comment]
sorry for my carelessness, passing build with go1.8 now.

**Comment by danielnelson** [comment]
I think this failure is acceptable, I don't want to add version checks to the Makefile and thats the only place we could do it.
