### ISSUE TITLE
Unable to build from master on OSX

### ISSUE THREAD

**Issue by imrichardcole** [influxdata/telegraf#2530]
## Directions

Checking out current master (commit - 7a5d857) I get the following:

```
mbp:telegraf user$ make
go get github.com/sparrc/gdm
gdm restore
make: gdm: No such file or directory
make: *** [prepare] Error 1
```

### System info:

go version - go1.8 darwin/amd64
OSX - 10.11.5

**Comment by imrichardcole** [comment]
Think this may be a gdm/environment issue?  Navigating to $GOPATH/src/github.com/sparrc/gdm and then running 'go build' produced a gdm executable I just had to manually copy it to /usr/local/bin for it to be picked up.  At that point running make seems to work.

My basic understanding of this line in the make file:

	go get github.com/sparrc/gdm

Made me think this would install gdm?

**Comment by danielnelson** [comment]
Yes, it should install gdm to your GOPATH or GOBIN directory.  What is your PATH and go related environment variables `env | grep GO` in the Makefile when running these commands?

**Comment by imrichardcole** [comment]
When you mean "in" the Makefile?

**Comment by danielnelson** [comment]
Temporarily print out the environment variables in the prepare target of the Makefile, something like this (make sure there is a tab before the commands):
```
 prepare:
        echo $$PATH
        env | grep GO
        go get github.com/sparrc/gdm
        gdm restore
```

**Comment by imrichardcole** [comment]
With you now.  So adding that in to my local MakeFile:

```
Richards-MBP:telegraf richard$ make
echo $PATH
/Users/richard/work/go/bin:/usr/local/git/bin:/usr/local/go/bin:/Users/richard/tools/gradle/latest/bin:/Users/richard/.rvm/gems/ruby-2.1.1/bin:/Users/richard/.rvm/gems/ruby-2.1.1@global/bin:/Users/richard/.rvm/rubies/ruby-2.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/richard/.rvm/bin
env | grep GO
GO_HOME=/usr/local/go
GOPATH=/Users/richard/work/go
go get github.com/sparrc/gdm
gdm restore
make: gdm: No such file or directory
make: *** [prepare] Error 1
Richards-MBP:telegraf richard$
```

Interestingly when I run this I do end up with a copy of gdm in my GOPATH/bin directory.

**Comment by danielnelson** [comment]
So `/Users/richard/work/go/bin/gdm` exists and `/Users/richard/work/go/bin` is in your path.  Are the file permissions correct? Is is executable?

**Comment by danielnelson** [comment]
Please reopen if you still need assistance.

**Comment by JonoB** [comment]
I know this is a closed issue, but I had the same problem as @imrichardcole  on Ubuntu 16.4, and his solution worked for me as well:

```
cd $GOPATH/src/github.com/sparrc/gdm 
go build
cp ./gdm /usr/local/bin
```
