### ISSUE TITLE
BUG:  High Cpu Usage [futex]

### ISSUE THREAD

**Issue by lin-credible** [influxdata/telegraf#2533]
OS: `CentOS` and `Ubuntu` (especially `Ubuntu` & `Debian`)
Telegraf: `Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)`

![default](https://cloud.githubusercontent.com/assets/3191641/23930222/cf7d8c38-0965-11e7-9618-b5048f7e2edf.png)

System calls of `telegraf`:
<img width="761" alt="screen shot 2017-03-15 at 09 55 29" src="https://cloud.githubusercontent.com/assets/3191641/23930246/02fe5cb8-0966-11e7-8ab3-94ec2e76f209.png">

If the cpu usage is so high, we can't use it in the product environment... What a pity!!!!!!!! 

Anybody can solve it?

**Comment by lin-credible** [comment]
My `telegraf.conf`:
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = true
  logfile = ""
  hostname = "_HOSTNAME_"
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://_INFLUXIP_:_INFLUXPORT_"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.netstat]]
```

**Comment by danielnelson** [comment]
@lin-credible Can you determine which plugin is causing the most cpu_usage?

**Comment by lin-credible** [comment]
@danielnelson I'm not sure which plugins cause the most cpu_usage. Do you have some advices how to collect those informations? As I know, what I used is very basic...

**Comment by danielnelson** [comment]
I would remove inputs one at a time until the problem goes away.

**Comment by lin-credible** [comment]
[collectd](https://github.com/collectd/collectd)'s system calls:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 95.77    0.011868        3956         3           nanosleep
  4.23    0.000524         524         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.012392                     4           total
```

Here is the difference.

**Comment by danielnelson** [comment]
> Anybody can solve it?

The best way we can solve it is by determining the plugin that is causing the most load, and then investigating how we can optimize it.  Likely, we will not be able to match collectd's performance but I'm sure there is room for improvement.  Are you able to investigate which plugin is causing the biggest problem?

**Comment by lin-credible** [comment]
I'm going to do it... Wait a while, maybe a few days... @danielnelson 😊

**Comment by AlbinOS** [comment]
Dear all,

Not sure if it's related but I found that the inputs.processes plugin is consuming 1-1.5% alone (using collection_jitter = "3s") more on a host using ZFS (which is the only difference between those two host, even the hardware is the same) :

![screen shot 2017-04-10 at 11 40 25](https://cloud.githubusercontent.com/assets/1978405/24855646/8ac06f8e-1de2-11e7-9b1c-b9482728ff3e.png)

![screen shot 2017-04-10 at 11 39 18](https://cloud.githubusercontent.com/assets/1978405/24855807/f9d2910e-1de2-11e7-96e2-0041c09c6f80.png)

The difference about the inputs.processes plugin is that on a ZFS host, the number of process is drastically higher : 

![screen shot 2017-04-10 at 11 49 30](https://cloud.githubusercontent.com/assets/1978405/24856089/ca9ed996-1de3-11e7-9a20-dc24c76b7d97.png)

![screen shot 2017-04-10 at 11 49 14](https://cloud.githubusercontent.com/assets/1978405/24856090/caa235dc-1de3-11e7-8d80-871c1e3a92ed.png)

Maybe having a look to the inputs.processes plugin is a good place to start.

Thanks a lot for the awesome work though !

**Comment by danielnelson** [comment]
@AlbinOS Will you open a new bug issue for this higher than expected cpu use in the processes input plugin?

The rest of this ticket is too general to be actionable, so I am closing it.
