### ISSUE TITLE
logparser not match

### ISSUE THREAD

**Issue by socol1** [influxdata/telegraf#2534]
the grok:

^#%{SPACE}Time:%{SPACE}%{NUMBER:YEAR}%{SPACE}%{TIME:time}(?m)\n#%{SPACE}User@Host:%{SPACE}%{WORD:user}\[%{WORD}\]%{SPACE}@%{SPACE}%{WORD:dbhost}?%{SPACE}\[%{IP:ip}\]%{SPACE}Id:%{SPACE}%{NUMBER:Id}(?m)\n#%{SPACE}Query_time:%{SPACE}%{NUMBER:duration:float}%{SPACE}Lock_time:%{SPACE}%{NUMBER:lock_wait:float}%{SPACE}Rows_sent:%{SPACE}%{NUMBER:results:int}%{SPACE}Rows_examined:%{SPACE}%{NUMBER:Rows_examined:int}(?m)\nSET%{SPACE}timestamp=%{NUMBER:timestamp};(?m)\n%{GREEDYDATA:sql}

Need match ：

Time: 161205 10:05:42
User@Host: xxxxx[xxxxxxx] @  [192.168.130.3]  Id: 914013274
Query_time: 0.004136  Lock_time: 0.000170 Rows_sent: 1  Rows_examined: 4090
SET timestamp=1480903542;
SELECT a.*,b.lon,b.lat,b.info,CONCAT(http://file.myrunners.com/,c.path,c.src) as avatar_src FROM run_group a LEFT JOIN run_grouddddp_positddddion b ON b.run_group_id=a.id LE
FT JOIN file c ON c.id=a.mark_id  WHERE ( a.id = 21 ) LIMIT 1;

test for http://grokdebug.herokuapp.com/ ：

![image](https://cloud.githubusercontent.com/assets/18021407/23931961/0bc9f14a-0970-11e7-9333-33335610268b.png)
![image](https://cloud.githubusercontent.com/assets/18021407/23931966/11b2ea94-0970-11e7-8569-ee04d889c623.png)
![image](https://cloud.githubusercontent.com/assets/18021407/23931968/16edb8f4-0970-11e7-97ee-ac49eee5ae02.png)
![image](https://cloud.githubusercontent.com/assets/18021407/23931970/1b6edd90-0970-11e7-9fe1-b11b1a6ce60b.png)
is OK , but influxdata no data:
SHOW MEASUREMENTS
![image](https://cloud.githubusercontent.com/assets/18021407/23931995/539f7fee-0970-11e7-8f16-6c4122f70494.png)

please help me !

telegraf-1.1.2-1.x86_64
influxdb-1.1.1-1.x86_64

config:

[[inputs.logparser]]
  files = ["/apps/mysql/data/mysql-slow.log"]
  from_beginning = false
  [inputs.logparser.grok]
     patterns = ["%{CUSTOM_LOG}"]
     custom_patterns = '''CUSTOM_LOG ^#%{SPACE}Time:%{SPACE}%{NUMBER:YEAR}%{SPACE}%{TIME:time}(?m)\n#%{SPACE}User@Host:%{SPACE}%{WORD:user}\[%{WORD}\]%{SPACE}@%{SPACE}%{WORD:dbhost}?%{SPACE}\[%{IP:ip}\]%{SPACE}Id:%{SPACE}%{NUMBER:Id}(?m)\n#%{SPACE}Query_time:%{SPACE}%{NUMBER:duration:float}%{SPACE}Lock_time:%{SPACE}%{NUMBER:lock_wait:float}%{SPACE}Rows_sent:%{SPACE}%{NUMBER:results:int}%{SPACE}Rows_examined:%{SPACE}%{NUMBER:Rows_examined:int}(?m)\nSET%{SPACE}timestamp=%{NUMBER:timestamp};(?m)\n%{GREEDYDATA:sql}'''
     measurement = "mysql_slow"

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by socol1** [comment]
I ask general questions at the InfluxData Community site.　but I can't reply ,why ? 
![image](https://cloud.githubusercontent.com/assets/18021407/24086948/3e2fd744-0d53-11e7-84a7-7c496ef50afa.png)
