### ISSUE TITLE
dns_query should not report 0ms query time on error

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2548]
### Relevant telegraf.conf:
```
[[inputs.dns_query]]
  servers = ["8.8.8.8"]
  record_type = "A"
  domains = ["google.com"]
  timeout = 10
```

### System info:

Telegraf 1.2.1

### Steps to reproduce:

1. Run telegraf
2. Interrupt resolution to cause an error, such as a timeout.

### Expected behavior:
One of:
1. `query_time_ms=10000`
2. null value

### Actual behavior:
`query_time_ms=0`

### Additional info:
This is highly problematic as the value indicates that the response came back immediately. However this is not the case. The response didn't come back at all. The result should somehow indicate this by either setting the value to the maximum (the timeout value), or not setting it at all, and providing some other field indicating an error occurred.

**Comment by danielnelson** [comment]
I think it makes sense to have field that is emitted only when a timeout occurs with the time waited: `query_timeout_ms=10000`.  I wonder if we should try to stick to the same units across fields, should timeouts always be reported in seconds?  Certainly this would be silly for some points so maybe not.

**Comment by discoduck2x** [comment]
@danielnelson -  any update on this? the dns query input is rather useless unfortunatley in its current state
