### ISSUE TITLE
Constant MQTT reconnects on Raspberry Pi

### ISSUE THREAD

**Issue by iqe** [influxdata/telegraf#2550]
## Bug report

I'm seeing constant MQTT reconnects with the mqtt_consumer in Telegraf 1.2.1. From systemd logs:

    Mar 14 22:15:35 raspberrypi telegraf[14086]: 2017-03-14T22:15:35Z E! MQTT Connection lost
    Mar 14 22:15:35 raspberrypi telegraf[14086]: error: pingresp not received, disconnecting
    Mar 14 22:15:35 raspberrypi telegraf[14086]: MQTT Client will try to reconnect
    Mar 14 22:15:35 raspberrypi telegraf[14086]: 2017-03-14T22:15:35Z I! MQTT Client Connected
    Mar 14 22:16:45 raspberrypi telegraf[14086]: 2017-03-14T22:16:45Z E! MQTT Connection lost
    Mar 14 22:16:45 raspberrypi telegraf[14086]: error: pingresp not received, disconnecting
    Mar 14 22:16:45 raspberrypi telegraf[14086]: MQTT Client will try to reconnect
    Mar 14 22:16:45 raspberrypi telegraf[14086]: 2017-03-14T22:16:45Z I! MQTT Client Connected
    Mar 14 22:17:55 raspberrypi telegraf[14086]: 2017-03-14T22:17:55Z E! MQTT Connection lost
    Mar 14 22:17:55 raspberrypi telegraf[14086]: error: pingresp not received, disconnecting
    Mar 14 22:17:55 raspberrypi telegraf[14086]: MQTT Client will try to reconnect
    Mar 14 22:17:55 raspberrypi telegraf[14086]: 2017-03-14T22:17:55Z I! MQTT Client Connected
    Mar 14 22:19:05 raspberrypi telegraf[14086]: 2017-03-14T22:19:05Z E! MQTT Connection lost
    Mar 14 22:19:05 raspberrypi telegraf[14086]: error: pingresp not received, disconnecting
    Mar 14 22:19:05 raspberrypi telegraf[14086]: MQTT Client will try to reconnect
    Mar 14 22:19:05 raspberrypi telegraf[14086]: 2017-03-14T22:19:05Z I! MQTT Client Connected

## Environment
Telegraf 1.2.1 on Raspberry Pi B, Raspbian Jessie, Mosquitto MQTT Broker on the Pi

## Cause
This seems to be a bug in the Eclipse Paho MQTT client, as described here:

https://github.com/eclipse/paho.mqtt.golang/issues/32
https://github.com/eclipse/paho.mqtt.golang/issues/50

I've rebuilt Telegraf 1.2.1 with `paho.mqtt.golang` master (dfe35ae8bd6ead198596c5e5f4af1f55914741cf) and the reconnecting has gone away. The MQTT connection works as expected.

### Proposal:

Please upgrade the MQTT client to the current version.

**Comment by danielnelson** [comment]
I believe this is fixed on the master branch.  Can you build with the version specified in the Godeps and retest?
