### ISSUE TITLE
Does not work inside Windows container, fails to start

### ISSUE THREAD

**Issue by pbering** [influxdata/telegraf#2559]
## Bug report

Using this docker file I try to start telegraf with the default config in the windows distribution:

````
FROM microsoft/windowsservercore

RUN powershell -Command \
	Invoke-WebRequest https://dl.influxdata.com/telegraf/releases/telegraf-1.2.1_windows_amd64.zip -OutFile 'C:/telegraf.zip';

RUN powershell -Command \
	Expand-Archive 'C:/telegraf.zip' 'C:/';

RUN C:\telegraf\telegraf.exe --config C:\telegraf\telegraf.conf --test
````

### System info:

Windows 10 AU, latest Docker for Windows (beta channel), latest microsoft/windowsservercore images

### Steps to reproduce:

1. docker build .

### Expected behavior:

telegraf is able to start

### Actual behavior:

```
Sending build context to Docker daemon  7.68 kB
Step 1/4 : FROM microsoft/windowsservercore
 ---> b4713e4d8bab
Step 2/4 : RUN powershell -Command      Invoke-WebRequest https://dl.influxdata.com/telegraf/releases/telegraf-1.2.1_windows_amd64.zip -OutFile 'C:/telegraf.zip';
 ---> Using cache
 ---> d52e7bd23ca1
Step 3/4 : RUN powershell -Command      Expand-Archive 'C:/telegraf.zip' 'C:/';
 ---> Using cache
 ---> c5175e0ccbce
Step 4/4 : RUN C:\telegraf\telegraf.exe --config C:\telegraf\telegraf.conf --test
 ---> Running in cb42de178056
2017/03/21 22:15:19 E! The service process could not connect to the service controller.
 ---> 4e3a761b4ff4
Removing intermediate container cb42de178056
Successfully built 4e3a761b4ff4
```

### Additional info:

It is the same behavior if I run the container and try from inside the running container

**Comment by JamisonWhite** [comment]
I'm getting the same error when running telegraf under nssm.  You can use sc.exe to register and start it as a service:

```
sc.exe create telegraf displayname="TICK Telegraf" start=auto binpath= "C:\opt\telegraf\telegraf.exe -config C:\opt\telegraf\telegraf.conf"
sc.exe failure telegraf reset=86400 actions=restart/1000/restart/10000
sc.exe start telegraf
```

**Comment by danielnelson** [comment]
Thanks for the update, it seems like this issue should be closed.

**Comment by gudipudipradeep** [comment]
This is the working Docker Steps for Telegraf with  proper log configuration for Kubernetes.
`
FROM mcr.microsoft.com/windows/servercore:1809
WORKDIR C:\\install
ADD https://dl.influxdata.com/telegraf/releases/telegraf-1.12.3_windows_amd64.zip C:\\install\\telegraf.zip
RUN powershell -Command Expand-Archive 'C:\\install\\telegraf.zip' 'C:\\install\\';
RUN Powershell.exe -Command New-LocalUser -Name telegraf -NoPassword -AccountNeverExpires ; \
                   Set-LocalUser telegraf -PasswordNeverExpires 1; \
                   Add-LocalGroupMember -Group "Administrators" -Member "telegraf";
USER telegraf
COPY telegraf.conf "c:\\install\\telegraf\\telegraf.conf"
ENTRYPOINT ["C:\\install\\telegraf\\telegraf.exe"]
CMD [" --config C:\\install\\telegraf\\telegraf.conf"]
`
