### ISSUE TITLE
Phusion Passenger plugin

### ISSUE THREAD

**Issue by kureikain** [influxdata/telegraf#256]
Hi @sparrc 

Not sure if anyone is working on Phusion Passenger. I run `PHP` at home and `Ruby` at work so would want to have telegraf support it. Gonna work on it if no one else that you know are working on it.

**Comment by sparrc** [comment]
@kureikain Not that I'm aware of, although this looks like a fairly small use-case and I'm not sure it's worth merging into the telegraf repository.

I could be wrong and people in the community can put a +1 here if they want it.

Otherwise, you could keep the plugin in a fork, or write an `exec` collector that could output the data into JSON and get picked up by telegraf.

**Comment by bmxpert1** [comment]
+1. Heavy user of passenger myself, so I think I'd make use of this plugin. What sort of metrics are available @kureikain ?

**Comment by gotyaoi** [comment]
As a note, passenger-status can output to xml with `passenger-status --show=xml`. Unfortunately it seems there are no plans for a json output: https://github.com/phusion/passenger/issues/1363. On the other hand, it's possible you could run the xml output through a dumb converter program and get json that could be used with the exec plugin. On the gripping hand, perhaps the exec plugin could support other common data formats besides json?

**Comment by sparrc** [comment]
My preference would be to have the exec plugin support XML, and then use that to parse the passenger status output

**Comment by kureikain** [comment]
Phusion Passenger is very popular in Ruby community though. It's considering the fastest Ruby app server and it can also serve NodeJS and Python.

Right now, `exec` plugin is quite limited because it doesn't know how to access JSON. It's simply grab the top level field. It also doesn't support `tag`.

I probably will keep it on my own fork, make it easier to parse and insert metric I think.

**Comment by kureikain** [comment]
@bmxpert1 It will included those metric:

- pool size
- Processes
- Requests in top-level queue

Below are tagged by Pid, App root

- Request in queue
- Session
- Mem
- CPU
- Processed

Will point your to my fork in a few day.

**Comment by bmxpert1** [comment]
@kureikain thank you!

**Comment by benweissmann** [comment]
Any update on this? I'd also love to use a Passenger plugin.

**Comment by sparrc** [comment]
@kureikain did you have a plugin for this in your fork?

If so, if you could rebase it off the 0.3.0 branch and send up a PR it would be much appreciated!

**Comment by kureikain** [comment]
@sparrc Yes, will send up a PR for this plugin. I have it in my fork. Will do when I'm home

**Comment by neckhair** [comment]
A huge :+1: from me!

**Comment by kureikain** [comment]
PR is open https://github.com/influxdata/telegraf/pull/522. Will add unit test and document

**Comment by kureikain** [comment]
Doc is added https://github.com/kureikain/telegraf/blob/2c7d7c15015699e28ec43b709183c8821f69d4e0/plugins/inputs/passenger/README.md

If anyone have feedback to improve doc please do.

**Comment by russorat** [comment]
code merged. resolving issue.
