### ISSUE TITLE
is there any consideration to use "_" when outputing to opentsdb?

### ISSUE THREAD

**Issue by skygragon** [influxdata/telegraf#2561]
since opentsdb format doesn't have "field" as influxdb, so telegraf will create a new name like "metric_fieldName" to fit this gap. My question is: can we use '.' instead of '_' here? You see most metric are named in this pattern "xxx.yyy.zzz", so maybe use '.' makes more sense?

**Comment by skygragon** [comment]
or can we use a pre-defined placeholder like: "some.metric,tag1=xxx _=123", then it will skip this "_" and use "some.metric" when outputing to opentsdb?

**Comment by danielnelson** [comment]
We would accept a PR that added an option in the output:  `separator="."` or such.

**Comment by danielnelson** [comment]
This feature has been added by @owlet123 and will be in the 1.5.0 release.
