### ISSUE TITLE
[Feature Request] Support index stats for elasticsearch plugin

### ISSUE THREAD

**Issue by xluffy** [influxdata/telegraf#2562]
## Feature Request

ElasticSearch plugin input supports index stats like [collectd](https://github.com/signalfx/collectd-elasticsearch)

- Transaction log (size, number of operations)
- Most of the common stats per index and per primary vs. total.

API ElasticSearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

### Use case:

Get more info of index, help monitor detail about the index.

**Comment by xluffy** [comment]
Have PRs, wait for reviewing code [2518](https://github.com/influxdata/telegraf/pull/2518) and [2456](https://github.com/influxdata/telegraf/pull/2456)

**Comment by blieberman** [comment]
Bump.

**Comment by danielnelson** [comment]
Latest work is over here now: https://github.com/influxdata/telegraf/pull/2872
