### ISSUE TITLE
Is there any way to point a pid file for telegraf so that process could be easily find and kill in cluster? 

### ISSUE THREAD

**Issue by visionarywind** [influxdata/telegraf#2566]
This may be a stupid question. But if there is a way to find process accurately, it would be a big convenience.

**Comment by danielnelson** [comment]
Are you asking if telegraf can create its own pidfile?  We don't do that in telegraf itself but the initscript does manage one.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by kaspergrubbe** [comment]
So if anyone else has been on the same goosechase as me I will now save you the time. 

Telegraf actually seems to support specifying a pidfile.

Not that `-h` will list it:

```
/usr/local/sbin/telegraf -h
Telegraf, The plugin-driven server agent for collecting and reporting metrics.

Usage:

  telegraf [commands|flags]

The commands & flags are:

  config              print out full sample configuration to stdout
  version             print the version to stdout

  --config <file>     configuration file to load
  --test              gather metrics once, print them to stdout, and exit
  --config-directory  directory containing additional *.conf files
  --input-filter      filter the input plugins to enable, separator is :
  --output-filter     filter the output plugins to enable, separator is :
  --usage             print usage for a plugin, ie, 'telegraf --usage mysql'
  --debug             print metrics as they're generated to stdout
  --pprof-addr        pprof address to listen on, format: localhost:6060 or :6060
  --quiet             run in quiet mode
```

But if you look closer, this init script is utilising it: https://github.com/influxdata/telegraf/blob/0759c8b22b922226fbe5cabf19896c4796babea5/scripts/init.sh#L145

And it seems to be parsed in here: https://github.com/influxdata/telegraf/blob/40fac0a9b48232794ca4d2bc3a4b5ccc71c03ba8/cmd/telegraf/telegraf.go#L41

And when I launch Telegraf with `-pidfile /home/deploy/test.pid` I can see that it actually does work:

```
~ $ cat /home/deploy/test.pid
26628
```

And it even cleans up after itself, after Telegraf is killed:

```
~ $ cat /home/deploy/test.pid
cat: /home/deploy/test.pid: No such file or directory
```
