### ISSUE TITLE
Support for cassandra mbean(/org.apache.cassandra.net:type=FailureDetector)

### ISSUE THREAD

**Issue by knight76** [influxdata/telegraf#2567]
## Bug report
If I added mbean(/org.apache.cassandra.net:type=FailureDetector) in telegraf configuration, so it print out, because it only support org.apache.cassandra.metrics mbean.

2017/03/24 17:51:00 I! Unsupported Cassandra metric [/org.apache.cassandra.net:type=FailureDetector], skipping

Then, could you support org.apache.cassandra.net mbean?

### Relevant telegraf.conf:

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cassandra/cassandra.go#L270-L280

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by knight76** [comment]
Also,  "/org.apache.cassandra.db:type=StorageService" is needed.
The mbean provide LiveNodes and LeavingNodes of Cassandra.

**Comment by danielnelson** [comment]
In the meantime, you should be able to use the jolokia input.

**Comment by mfossen** [comment]
Is that metric supported by jolokia? I get the error `E! Error in plugin [inputs.jolokia]: Not expected status value in response body (localhost:8080 mbean="org.apache.cassandra.net:type=FailureDetector" attribute="DownEndpointCount"): 404` using the below additions to my telegraf.conf. The Memory entry works as expected and jolokia is running properly and returning responses.


``` [[inputs.jolokia]]
  context = "/jolokia/"

  [[inputs.jolokia.servers]]
    name = "test-1"
    host = "localhost"
    port = "8080"

  [[inputs.jolokia.metrics]]
    name = "java_memory"
    mbean = "java.lang:type=Memory"
    attribute = "HeapMemoryUsage"

  [[inputs.jolokia.metrics]]
    name = "down_nodes"
    mbean = "org.apache.cassandra.net:type=FailureDetector"
    attribute = "DownEndpointCount" ```

**Comment by internaught** [comment]
So whats the story on this? I'm running into the same issue with org.apache.cassandra.db metrics...

**Comment by danielnelson** [comment]
I think this input should be deprecated in favor of the jolokia2 input.  I would also like to add an example configuration for Cassandra with the jolokia2 input, if someone can contribute one it would be appreciated.

**Comment by internaught** [comment]
Here is the config I'm using, but it's not working:

```[[inputs.jolokia2_agent]]
  urls = ["https://localhost:8778/jolokia"]


[[inputs.jolokia2_agent.metric]]
  name       = "jvm_garbage_collector"
  mbean      = "java.lang:name=*,type=GarbageCollector"
  tag_keys   = ["name"]

[[inputs.jolokia2_agent.metric]]
  name       = "jvm_memory"
  mbean      = "java.lang:name=*,type=Memory"
  tag_keys   = ["name"]

[[inputs.jolokia2_agent.metric]]
  name       = "cassandra_threadpool_metrics"
  mbean      = "org.apache.cassandra.metrics:name=*,type=ThreadPools"
  tag_keys   = ["name"]
```

I'm getting the error:

```
2018-03-13T02:07:00Z E! Error in plugin [inputs.jolokia2_agent]: took longer to collect than collection interval (1m0s)
```

**Comment by danielnelson** [comment]
How long does `curl https://localhost:8778/jolokia` take to run?

**Comment by internaught** [comment]
Sorry, it doesn't return at all. But changing from https to http does:

It's worth noting I'm not running a standalone jolokia agent but jolokia is running from within the cassandra JVM itself. Would this require using jolokia2_proxy? If so, what would the [[inputs.jolokia2_proxy.target]] url be set to?

```
$ time curl http://localhost:8778/jolokia
<h1>404 Not Found</h1>No context found for request
real    0m0.026s
user    0m0.004s
sys     0m0.020s
```

**Comment by internaught** [comment]
Furthermore, why are only two metric types supported?
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cassandra/cassandra.go#L275

I tried building the binary by hacking in another `else if` statement to include "/org.apache.cassandra.db:", but it didn't seem to take... Any chance we could just add more?

**Comment by danielnelson** [comment]
The agent jar and agent jolokia is ran from within the same JVM as Cassandra, so it sounds like you have the right combination.  The proxy variation is used when running the jolokia proxy as a separate process.

Once you have the jolokia agent running and that url responds, you will be able to read any of the values with the jolokia2 plugin.

**Comment by internaught** [comment]
When using the jolokia2 input, no errors are showing in the logs and no metrics are written to influxDB.

Running `curl http://localhost:8778/jolokia/` does respond successfully, yet the collector doesn't send metrics to influxDB when specifying the URL with or without the trailing slash.

**Comment by danielnelson** [comment]
If you attach a file with the output of `curl http://localhost:8778/jolokia/` and your jolokia2_agent config (if it's different from above) and I can take a look.

**Comment by internaught** [comment]
```
$ curl http://localhost:8778/jolokia/
{"timestamp":1520923822,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"maxDepth":"15","maxCollectionSize":"0","maxObjects":"0","discoveryEnabled":"true","agentContext":"\/jolokia","historyMaxEntries":"10","agentId":"172.20.55.37-12555-431d00cf-jvm","agentType":"jvm","debug":"false","debugMaxEntries":"100"},"agent":"1.3.5","info":{}}}
```
```
cat /etc/telegraf/telegraf.d/jolokia.conf

[[inputs.jolokia2_agent]]
  urls = ["http://localhost:8778/jolokia"]

        [[inputs.jolokia2_agent.metric]]
          name       = "jvm_garbage_collector"
          mbean      = "java.lang:name=*,type=GarbageCollector"
          paths      = ["CollectionTime", "CollectionCount"]
          tag_keys   = ["name"]

        [[inputs.jolokia2_agent.metric]]
          name       = "jvm_memory"
          mbean      = "java.lang:type=Memory"
          paths      = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]
          tag_keys = ["name"]

        [[inputs.jolokia2_agent.metric]]
          name       = "cassandra_cache_metrics"
          mbean      = "org.apache.cassandra.metrics:name=*,type=Cache"
          tag_keys   = ["name"]

        [[inputs.jolokia2_agent.metric]]
          name       = "cassandra_client_request_metrics"
          mbean      = "org.apache.cassandra.metrics:name=*,type=ClientRequest"
          tag_keys   = ["name"]
```

**Comment by danielnelson** [comment]
It looks like we actually need to figure out the POST data for a request to `/jolokia/read` in order to debug.  I will have to figure out the details in the morning, getting late here.  In the meantime, try removing `tag_keys`.

**Comment by danielnelson** [comment]
@internaught Everything is working alright then?

**Comment by internaught** [comment]
Yeah all good here, I've dropped the cassandra plugin in favor of jolokia2_agent

**Comment by danielnelson** [comment]
Okay, when I get a chance I am planning to mark the cassandra plugin deprecated and convert the metrics in the README to an example jolokia2 config.

**Comment by danielnelson** [comment]
Cassandra input was marked deprecated in 1.7.

**Comment by purushottambaghel** [comment]
> Also, "/org.apache.cassandra.db:type=StorageService" is needed. The mbean provide LiveNodes and LeavingNodes of Cassandra.

How to get these metrics in Jolokia_2?
