### ISSUE TITLE
[Feature request] Custom tags on CloudWatch metrics

### ISSUE THREAD

**Issue by jagregory** [influxdata/telegraf#2572]
Hey folks,

What do you think about allowing custom tags to be assigned to metrics which come from the CloudWatch input?

This feature would be most useful for metrics which have less-than-helpful dimensions associated with them, for example when your RDS database identifier is a random GUID it doesn't work very well in Dashboards where you want something a bit more user-friendly.

    # Cloudwatch: RDS metrics 
    [[inputs.cloudwatch]]
      namespace = "AWS/RDS"

      # test
      [[inputs.cloudwatch.metrics]]
        names = ["CPUUtilization", "MaximumUsedTransactionIDs", "DatabaseConnections"]

        [[inputs.cloudwatch.metrics.dimensions]]
          name = "DBInstanceIdentifier"
          value = "tf-00000000000000000000000000"

      # prod
      [[inputs.cloudwatch.metrics]]
        names = ["CPUUtilization", "MaximumUsedTransactionIDs", "DatabaseConnections"]

        [[inputs.cloudwatch.metrics.dimensions]]
          name = "DBInstanceIdentifier"
          value = "tf-111111111111111111111111"

It'd be great to add tags, something like:

    [[inputs.cloudwatch.metrics]]
       names = ["CPUUtilization", "MaximumUsedTransactionIDs", "DatabaseConnections"]
       [[inputs.cloudwatch.metrics.tags]]
         environment = Production

This would be similar to the `global_tags` option.

**Comment by jagregory** [comment]
To clarify why the `global_tags` option doesn't work for this scenario is I have a separate Telegraf instance which is responsible for collecting CloudWatch metrics (and a few other things), so it spans environments and can't really share their global tags.

**Comment by phemmer** [comment]
Just FYI, you can do this:

```
# Cloudwatch: RDS metrics 
[[inputs.cloudwatch]]
  namespace = "AWS/RDS"

  [[inputs.cloudwatch.tags]]
    environment = "test"

  [[inputs.cloudwatch.metrics]]
    names = ["CPUUtilization", "MaximumUsedTransactionIDs", "DatabaseConnections"]

    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DBInstanceIdentifier"
      value = "tf-00000000000000000000000000"

[[inputs.cloudwatch]]
  namespace = "AWS/RDS"

  [[inputs.cloudwatch.tags]]
    environment = "test"

  [[inputs.cloudwatch.metrics]]
    names = ["CPUUtilization", "MaximumUsedTransactionIDs", "DatabaseConnections"]

    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DBInstanceIdentifier"
      value = "tf-111111111111111111111111"
```

Not saying your request shouldn't be implemented, just proposing a workaround.

**Comment by jagregory** [comment]
Thanks, that's a good work around. It does make things quite verbose, unfortunately. Is anyone opposed to the feature request? I'd be interested in seeing if I can handle a PR for it.

**Comment by danielnelson** [comment]
We would accept a PR for this.

**Comment by danielnelson** [comment]
Doing input level tags is already working. If you wanted to add support for tags per individual metric within an input plugin that would be okay.

**Comment by danielnelson** [comment]
@jagregory Based on the discussion in the linked issues, I think your problem is solved and this can be closed.
