### ISSUE TITLE
Specified tags not preserved when output to Kafka

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2574]
## Bug report

I have an instance of Telegraf that I want to push metrics to and have them pushed into our pipeline.  Currently, that means that the metrics are pushed to Kafka.  However, when I push metrics using either the http_listener or tcp_listener, the tags are not preserved (JSON and InfluxDB formats).  I tried multiple fields as well (JSON) with no luck.

Not sure if Kafka is the key part of this.  I have not tested any other outputs.

### Relevant telegraf.conf:

JSON+TCP:

[[input.tcp_listener]]
    service_address = ":<port>"
    data_format = "json"
    name_override = "test"
    tag_keys = ["foo", "bar"]

Influx+TCP:

[[input.tcp_listener]]
    service_address = ":<port>"
    data_format = "influx"

Influx+HTTP:

[[input.http_listener]]
    service_address = ":<port>"
    read_timeout = "10s"
    write_timeout = "10s"

Kafka:

[[outputs.kafka]]
    brokers = <brokers>
    topic = "<topic>"
    data_format = "json"

### System info:

Telegraf 1.2.0

### Steps to reproduce:

1. Start telegraf using one of the input configs and the kafka output config.
2. Send data to telegraf
3. Check the output for all fields and tags.

### Expected behavior:

All fields and tags specified in the input are in the output.

### Actual behavior:

Tags and extra fields are missing.

### Additional info:

**Comment by danielnelson** [comment]
How are you verifying the data in Kafka?  Can you add an example of what data is outputted?

**Comment by sybrandy** [comment]
Closing.  The issue was on my side.  It just didn't occur to me until I read your reply and thought about it a second longer.
