### ISSUE TITLE
[Feature Request] diskio input for Darwin

### ISSUE THREAD

**Issue by brettinternet** [influxdata/telegraf#2575]
### Proposal:
Support for diskio input on Darwin

For community discussion, go here: https://community.influxdata.com/t/mac-diskio-input-error-not-implemented-yet/371

### Current behavior:
Leaving the default `telegraf.conf` configuration options on **macOS** installed with `homebrew` throws the following error in the log:

```
E! ERROR in input [inputs.diskio]: error getting disk io info: not implemented yet
```

### Desired behavior:
DiskIO input with Telegraf

### Use case:
System stats on a platform as prolific as macOS is essential. This includes an input as critical to Telegraf's purpose as disk IO stats.

Thanks to the InfluxData team, I appreciate all of your excellent support.

**Comment by nhaugo** [comment]
We get this from gopsutil, which does not provide the data for darwin.

**Comment by rburchell** [comment]
@nhaugo What are you still missing? I added IO counters for Darwin recently (hoping that telegraf would eventually pick this up)

See https://github.com/shirou/gopsutil/pull/336 for reference.

**Comment by danielnelson** [comment]
We don't compile with cgo.

**Comment by rburchell** [comment]
Ah, that's unfortunate. I don't think there's any alternative to get it unfortunately (I did a fair amount of research before settling on that).

**Comment by danielnelson** [comment]
What I said above is wrong, we don't build for Darwin, so the cgo stuff is up to you.  I'm going to update the version of gopsutil for #2649, can you test again after that gets merged?

**Comment by rburchell** [comment]
Ah, certainly. I guess @brettinternet might be keen to as well ;-). I remember that I installed from Homebrew originally now, I had just sort of forgotten that and thought it was some kind of "official" package.

**Comment by rburchell** [comment]
Seems to work fine, at least from my (admittedly limited) testing setup :)

![Disk metrics on Darwin](https://cloud.githubusercontent.com/assets/125863/24929872/d52e5a88-1f07-11e7-9352-0504c05f4b37.png)

**Comment by danielnelson** [comment]
For the record, I checked into this a bit more and the Homebrew package is official, and built with cgo.  Here is the [build script](https://github.com/Homebrew/homebrew-core/blob/master/Formula/telegraf.rb). Sorry for the misinformation.

So then it would seem we will have support for this in 1.3.0 and I'm going to close this issue.

**Comment by rburchell** [comment]
No problems, @danielnelson. Thanks for pulling in the update, I'm thrilled to have this working, and looking forward to 1.3.0 :-)

**Comment by rburchell** [comment]
@danielnelson Though this came in through an addition to third party code, is it worth adding it to CHANGELOG? I don't know how many there are like me using telegraf on Mac, but it seems reasonably noteworthy.

**Comment by danielnelson** [comment]
Yeah, probably a good idea, I have added this issue to the changelog.
