### ISSUE TITLE
Eleasticsearch output plugin not found on windows amd64

### ISSUE THREAD

**Issue by Simiil** [influxdata/telegraf#2578]
## Bug report

The elasticsearch output plugin seems to be missing:

    2017/03/28 09:36:08 E! Error parsing telegraf.conf, Undefined but requested output: elasticsearch

### Relevant telegraf.conf:

    [[outputs.elasticsearch]]
        urls = [ "http://localhost:9200" ]
        index_name = "telegraf-%Y"
        manage_template = true
        template_name = "telegraf"

### System info:

Telegraf 1.2.1 windows amd64 on a Windows Server 2008, with no connection to the internet.

### Steps to reproduce:

start with the default config, remove the `influxdb` output, add an `elasticsearch` output.

### Expected behavior:

the elasticsearch output plugin should load

### Actual behavior:

it does not load, see the error message above

**Comment by christrotter** [comment]
Also seeing this, pretty much same vesion/system set up except for 2012R2/has internet connection, and we are using different index names.

`
[outputs]
[[outputs.elasticsearch]]
  urls = [ "http://localhost:9200" ]
  index_name = "metrics-%Y.%m.%d"
  manage_template = false
  template_name = "metrics"
`

**Comment by christrotter** [comment]
For kicks, i tried 1.2.0 - same issue.  Tried 1.1.2 - same issue.

Maybe this is a config syntax issue?

**Comment by lpic10** [comment]
The output for Elasticsearch has been merged recently, it is still not present on telegraf 1.2.1

@danielnelson : I miss the information about the ES output feature being added in the changelog

**Comment by christrotter** [comment]
Thanks, we are going to try building from src until then.

**Comment by christrotter** [comment]
Quick update - we built locally, no longer getting that error.  \o/

**Comment by danielnelson** [comment]
I added ES to the changelog, will be available in the 1.3.0 release.
