### ISSUE TITLE
[Feature request] Drop certain special characters from Windows performance counter instance names

### ISSUE THREAD

**Issue by sofam** [influxdata/telegraf#2579]
### Proposal:
I'd like to be able to drop characters from a Windows performance counter instance name, for example "C:" I'd like to be able to rewrite to "C"
### Current behavior:
Current behavior is to keep the instance name as is "C:". 
### Desired behavior:
To be able to configure, per input, which characters to drop or replace with others.
### Use case: [Why is this important (helps with prioritizing requests)]
This is blocking me from exporting disk performance metrics to HostedGraphite.

**Comment by danielnelson** [comment]
Could you add your `[[inputs.win_perf_counters.object]]` for an affected metric, and an example of the metric produced in influxdb format (using --test)?

**Comment by nhaugo** [comment]
The output handler in this case should be responsible to ensure the names are valid for the output.

**Comment by danielnelson** [comment]
@sofam If the graphite output handler is not doing this correctly, please open an issue using the bug template.
