### ISSUE TITLE
[BUG] - plugin inputs.haproxy - active_servers

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/telegraf#2583]
### Relevant telegraf.conf:
```

[[inputs.haproxy]]
servers = ["/var/lib/haproxy/stats"]
```

### System info:

```
root@macgyver ~ # lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
root@cherrybomb ~ # telegraf --version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
```

### Steps to reproduce:

1. Haproxy pool config : 
```
backend pool-test
    balance     roundrobin
    option      httpchk GET /manage/alive
    http-check  expect string UP
    server  srv1 10.3.0.21:9580 check port 9581
    server  srv2 10.3.0.22:9580 check port 9581
```
2. When the httpchk endpoint return UP all servers are in pool and value of active_servers returned by inputs.haproxy is 2 (which is normal because both server are OK)
3. When the httpchk endpoint return DOWN all servers are out pool on haproxy **but** value of active_servers returned by inputs.haproxy is 1 (which should return 0)

### Expected behavior:

The output from `inputs.haproxy` for `active_servers` metric should return the right value from haproxy about number of server healthy in pool

### Actual behavior:

The output from `inputs.haproxy` for `active_servers` metric is returning always 1 when all servers from a pool are marked as DOWN on haproxy

**Comment by phemmer** [comment]
The statistic is reported by haproxy, telegraf just passes it through.
In this case, make sure you are looking at the backend (`sv=BACKEND`), and not the individual server. The server will always have `active_servers=1`, even if it's down.

**Comment by danielnelson** [comment]
That is somewhat confusing, I guess this is not an issue with Telegraf though so I'm going to close.

**Comment by JulienChampseix** [comment]
Thanks @phemmer, you're right ! With missing tags added in https://github.com/influxdata/telegraf/issues/2318 that will be easier to pinpoint the right infos (like status of pool).
