### ISSUE TITLE
Prometheus plugin to honour parsed timestamp 

### ISSUE THREAD

**Issue by djjorjinho** [influxdata/telegraf#2593]
Parser is gathering the metric timestamp here:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/parser.go#L89

But then it gets ignored and the current time is used instead:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L148

### Expected behavior:
When I expose a prometheus metric with a timestamp like the example:

```
# HELP test_metric Metric read from /tmp/node_exporter/textfile/test_metric.prom
# TYPE test_metric untyped
test_metric{label="value"} 1.0 1490802350
```

I expect the test output to be something like the example:
```
test_metric,label=value,url=http://localhost:3002/metrics value=1.0 1490802350000000000
```

### Actual behavior:
The output timestamp uses the current time

```
test_metric,label=value,url=http://localhost:3002/metrics value=1.0 1490809413000000000
```

**Comment by danielnelson** [comment]
@djjorjinho Should be an easy fix now that you have it all figured out, do you want to make up a PR?

**Comment by djjorjinho** [comment]
I do, but was not posting from my personal PC, like you said it's a quick
fix.

PR coming up.

On Wed, Mar 29, 2017, 9:21 PM Daniel Nelson <notifications@github.com>
wrote:

@djjorjinho <https://github.com/djjorjinho> Should be an easy fix now that
you have it all figured out, do you want to make up a PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/influxdata/telegraf/issues/2593#issuecomment-290213802>,
or mute the thread

**Comment by djjorjinho** [comment]
@danielnelson I've created https://github.com/influxdata/telegraf/pull/2596
