### ISSUE TITLE
Race condition in github.com/influxdata/telegraf/internal TestRunTimeout

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2599]
## Bug report

There is a race condition in TestRunTimeout.

### System info:
9495b615f55a937e0f1a79670451227d3df5166d

### Steps to reproduce:

1. Run unittests

### Expected behavior:

Tests Pass

### Actual behavior:

Tests Fail

### Additional info:
```
--- FAIL: TestRunTimeout (0.45s)
	Error Trace:	internal_test.go:56
	Error:      	Should be true
FAIL
FAIL	github.com/influxdata/telegraf/internal	0.609s
```

https://circleci.com/gh/influxdata/telegraf/6443

**Comment by ssoroka** [comment]
don't think this is relevant anymore
