### ISSUE TITLE
Graphite output plugin: Support TLS over TCP

### ISSUE THREAD

**Issue by dheerajdwivedi** [influxdata/telegraf#2600]
### Proposal:
We are looking to use hosted solution for graphite.
Since the communication is over internet it needs to be secure.
Hence the support for tls over tcp is required.

### Current behavior:
Insecure communication between telegraf client and server

### Desired behavior:
Secure the communication between client and server

### Use case:
Graphite hosted solutions where data flows over internet.
To avoid middleman attack, hence secure the auth credentials and metrics data between client and server

**Comment by danielnelson** [comment]
This would be great, is it something you would be interested in working on?
