### ISSUE TITLE
Fetch CPU frequency states

### ISSUE THREAD

**Issue by Finkregh** [influxdata/telegraf#2601]
### Proposal:
Fetch CPU frequency states, governor

### Current behavior:
```[[inputs.system]]```
does not show CPU frequency, sleep states etc.

### Desired behavior:
`inputs.system` should also fetch cpu frequency, sleep states etc.

### Use case: [Why is this important (helps with prioritizing requests)]
lower CPU frequencys might impact services; lower frequencies might be forced when the temperature is too high or there are problems with the PSU

**Comment by nhaugo** [comment]
I don't think we can get state from gopsutil, but we can look into getting the freq as a field
