### ISSUE TITLE
Feature: some way to limit size of inputs/outputs

### ISSUE THREAD

**Issue by nfirvine** [influxdata/telegraf#2606]
Sometimes a misbehaving client will post a huge measurement to a Telegraf input. It would be nice to have a feature to drop those inputs.

### Use case:

Johnny Appdeveloper writes an app that posts a measurement to Telegraf with a tag generated from the code. The tag happens to be 3 MB long, by accident.

Nick in Ops is running the metrics pipeline, and decides a 3 MB Telegraf measurement is never on purpose and can hurt other users of the service, so will drop the measurement, log it, and count it.

**Comment by danielnelson** [comment]
I agree there should be a limit.  Not sure if it needs to be user defined or not.   Exactly where to place this check is also debatable, some inputs already have limits (http_listener).

**Comment by danielnelson** [comment]
In InfluxDB, this key must be less than 32768 bytes long: `<measurement>,<tag1=value1>,<tagN=valueN>#!~#<field>`.

**Comment by nfirvine** [comment]
Which key? I'm not sure exactly what you mean... The series?

**Comment by danielnelson** [comment]
Sorry, didn't add enough context, the key is that string.  This is another limit we have in the TICK stack, and it would probably makes sense to limit Telegraf metrics to this size at most.

**Comment by nfirvine** [comment]
Is `<field>` the field key or `<fieldkey>=<fieldvalue>`?

**Comment by danielnelson** [comment]
Just the field name.  https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/writer.go#L98-L99

**Comment by danielnelson** [comment]
I can think of several ways this could be implemented, but they all have some drawbacks.  In some sense it should be the job of the input and output plugins to handle limits, but I see the draw of having a system wide limit.

The most straightforward place to limit metrics system wide would be when added to the accumulator, but we would want to ensure that we aren't creating a significant performance hit.

**Comment by nfirvine** [comment]
To scratch my particular itch, all I'd need it for is the `kafka_consumer` input. I took a quick peek at the code, and it seems like it could be pretty simple `if len(buf) > MAX_LEN then drop with error`. Not sure if this is the right approach though. If you think that's fine, I could probably find the time for a PR in the next couple of weeks.

**Comment by danielnelson** [comment]
I think that would be fine, what do you think `MAX_LEN` should be?

**Comment by danielnelson** [comment]
64 * 1024 bytes would probably be good if there is nothing more fitting for kafka.

**Comment by nfirvine** [comment]
I actually have very little data on how "wide" our metrics end up being, besides the ones that are very big and clearly pathological. May need to measure this. But yes, 64k's a good start.
