### ISSUE TITLE
Errors in log should be more explicit

### ISSUE THREAD

**Issue by yellowmegaman** [influxdata/telegraf#2607]
## Bug report
I'm using telegraf to gather metrics from cassandra via jolokia. When some metric is no longer available ( cassandra version change), all i get - `URL returned with status 404`

### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["http://influxdb.service:8086"]
  database = "telegraf_some"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cassandra]]
  name_prefix = "some_"
  context = "/jolokia/read"
  servers = ["some:some@localhost:8778"]
  metrics  = [
    ...
    "/org.apache.cassandra.metrics:type=ReadRepair,name=Attempted",
    "/org.apache.cassandra.metrics:type=ReadRepair,name=RepairedBackground",
    "/org.apache.cassandra.metrics:type=ReadRepair,name=RepairedBlocking"
    ...
```
### System info:
cassandra in docker container (1.13) on debian system (jessie)
Telegraf 1.2.1-1
### Steps to reproduce:

1. use config above
2. telegraf --debug -config /tmp/tele.conf
3. ReadRepair metrics are not available, and even in debug mode all i see is `URL returned with status 404`.

### Expected behavior:
`URL returned with status 404 - host:port/jolokia/link_that_failed`
### Actual behavior:
`URL returned with status 404`

## Feature Request
Please make 404 error more explicit

Thanks a lot in advance!

**Comment by danielnelson** [comment]
Will be included in 1.4 release.
