### ISSUE TITLE
Output from powershell with input.exec not picked up

### ISSUE THREAD

**Issue by tdekoning93** [influxdata/telegraf#2608]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
I'm trying to get stuff with powershell into Influx by using the input.exec from telegraph. This works for me on Linux with bash scripts, but I can't seem to get the output from the powershell script to Telegraf.
When I run it manually it returns the right values;
```
 PowerCLI C:\Scripts> C:\\Scripts\\production.ps1
    vsphere,host=vcenter.despite.nl,name=ESX vmcount=22
    vsphere,host=vcenter.despite.nl,name=esx1.despite.nl vmcount=16
    vsphere,host=vcenter.despite.nl,name=esx2.despite.nl vmcount=6
```

### Relevant telegraf.conf:

```
  [[inputs.exec]]
	commands = ["powershell C:\\Scripts\\production.ps1"]
	timeout = "10s"
	data_format = "influx"
```

### System info:
Telegraf 1.2.1
Windows 10 64-bit

### Steps to reproduce:

```
PowerCLI C:\> C:\"Program Files"\Telegraf\telegraf.exe --config C:\"Program Files"\Telegraf\telegraf.conf --test
* Plugin: inputs.exec, Collection 1
```

### Expected behavior:
Output from the script picked up by Telegraf

### Actual behavior:
Telegraf picks up nothing. It does run powershell, but does not get the output from the powershell script.
### Additional info:

I tried to use;
- Write-Output
- Write-Host,
- return $variable
- "string"

I couldn't get the output from powershell being picked up by Telegraf. On Ubuntu this worked fine with a bash script.

### Use case: [Why is this important (helps with prioritizing requests)]

It enables me to send data from powershell scripts to InfluxDB, which enables me to monitor a lot of stuff, including my VMware environment.

**Comment by tdekoning93** [comment]
Nevermind, had to use forward slashes.

**Comment by rameshs10** [comment]
if we  have to use forward slash in windows configuration to work this plugin

**Comment by rameshs10** [comment]
i tested and it is working fine with forward slash
