### ISSUE TITLE
Solace collector

### ISSUE THREAD

**Issue by madshall** [influxdata/telegraf#2614]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
It would be awesome to have an ability to collect stats from Solace VPNs and appliances

### Current behavior:
No collector available

### Desired behavior:
Solace collector is available

### Use case: [Why is this important (helps with prioritizing requests)]
Solace stats are important for message-driven systems. Having access to them allows catching issues with message protocols and flows.

**Comment by sharik79** [comment]
I started some project at my work place.
However I pushed directly data into InfluxDB, and not via telegraf agent protocols.

**Comment by danielnelson** [comment]
@sharik79 Can you link to any code or explain what APIs you used and what metrics you collected?

**Comment by sharik79** [comment]
@danielnelson  I used SEMP  which is a RESTful API for retrieving the stats info. I used the SEMP Legacy ,on solace version 7.1, while now they have SEMP v2 on Solace 8.2.
link to SEMP: https://docs.solace.com/SEMP/SEMP-Home.htm

they also have schema for describing all supported metrics, and how to query them (follow link https://docs.solace.com/SEMP/SEMP-API-Archit.htm#SEMP ) 

I will need to get some permission to upload the code into here.
will let you know in few days if I can do such.

**Comment by powersj** [comment]
Hi,

Thanks for taking the time to file this. However, it does not appear that this has had any progress or further interest in the last few years. I am going to go ahead and close this for now.

If someone wanted to continue to work on this, we could consider a PR or have someone create an external plugin for use. However, this plugin is not in our plans going forward.

Thanks!
