### ISSUE TITLE
Monitor process resource limits/usage

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2617]
### Proposal:
Telegraf should provide process resource limits & usage.
Linux provides `/proc/$pid/limits` for indicating the resource limits of a process. At a minimum the "soft" values should be provided. Thought it might also be beneficial to provide the "hard" values.

Additionally many of the resources indicated in this file are not currently reported by telegraf's `procstat` input, such as stack size, locked memory, etc. These numbers should be provided.
And while we're at it, many of these missing numbers come from `/proc/$pid/status`. If we're going to add the ones corresponding to the values in `/proc/$pid/limits`, it might be a good idea to just add all of them (all the ones that make sense anyway, meaning not stuff like "Groups" or "TracerPid").

### Current behavior:
Doesn't do the proposal.

### Desired behavior:
Do the proposal.

### Use case: [Why is this important (helps with prioritizing requests)]
Hitting these resource limits can cause applications to fail. Thus they should be monitored so that admins can be aware of resource usage, and take action to fix things before they fail.

**Comment by danielnelson** [comment]
Sure, is everything available from gopsutil?

**Comment by phemmer** [comment]
No. Looks like it'll need a PR to add some stuff.
