### ISSUE TITLE
http_response: return values in case of timeout

### ISSUE THREAD

**Issue by LeJav** [influxdata/telegraf#2624]
It would be nice if http_response could return values in case of timeout.
For instance, timeout value (or predefined value) for response_time and a predefined code (0 for instance) for http_response_code

Instead of having:

> 	if err != nil {
>		return err
>	}

Do something like:

>	if err != nil {
>		fields = make(map[string]interface{})
>		fields["response_time"] = h.ResponseTimeout.Duration.Seconds()
>		fields["http_response_code"] = 0
>		acc.AddFields("http_response", fields, tags)
>		return nil
>	}

The timeouts will then clearly appear in graphs

**Comment by phemmer** [comment]
We should probably come up with a standard behavior for all plugins which measure response times of something, and end up timing out. We have a similar issues over at #2548 for `dns_query` and #1654 for the `ping` plugin.

**Comment by danielnelson** [comment]
There is now a `result_type` field that will be set to `timeout` upon timeout.  The `http_response_code` will be unset.
