### ISSUE TITLE
Bug in custom_pattern %{URIPATH:request} on logparser

### ISSUE THREAD

**Issue by drcain1** [influxdata/telegraf#2625]
## Bug report

We're doing metrics collecting in regards to page speed, which is why we don't want to log the method of each page (excessive logging), and we also use GROUP BY searches (which get more annoying if you have "?methods").

When using %{URIPATH:request} as a Grok pattern to not get all the methods of requests in our logs. eg.

127.0.0.1 - - [03/Apr/2017:17:32:28 +0200] "GET /myapp/logon.do?some_method" 200 660 "https://example.com/" "Chrome/56.0.2924.87 Safari/537.36" 38894

Nothing gets parsed.
On the other hand "GET /myapp/logon.do" works.
While "GET /myapp/logon.do?method" does not work

### Relevant telegraf.conf:
custom_patterns = '''
      CUSTOM_LOG %{CLIENT:client_ip} %{NOTSPACE:ident:drop} %{NOTSPACE:auth:drop} \[%{HTTPDATE:ts:ts-httpd}\] "%{WORD:verb} %{URIPATH:request}" %{NUMBER:resp_code:tag} (?:%{NUMBER:resp_bytes:int}|-) %{QS:referrer:drop} %{QS:agent:drop} %{NUMBER:response_time_us:int}
      '''
### System info:

Tested both Telegraf 1.2.1 and latest version from Git.

### Steps to reproduce:

1. set up telegraf with output file and input inputs.logparser
2. set custom patterns to above.

### Expected behavior:

Queries should get logged without the "?method"

### Actual behavior:

Queries get dropped if they contain "?"

### Additional info:

I would settle with using %{URIPATHPARAM:request} if it got expanded into URIPATH and URIPARAM so I could set :drop on URIPARAM, however this does not happen.

**Comment by danielnelson** [comment]
Have you tried to make a custom pattern to replace URIPATHPARAM?

Here is the definition of this pattern: https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns#L47

You should be able to make a new pattern based on this and name the fields
```
CUSTOM_URIPATHPARAM %{URIPATH:uripath}(?:%{URIPARAM:uriparam})?
```

**Comment by drcain1** [comment]
Oh, that actually does work.
Thank you very much.

Not sure if this needs to be open any more then, maybe close it and update the documentation instead.

**Comment by danielnelson** [comment]
Good to hear, I'm planning some doc improvements in #2545
