### ISSUE TITLE
procstat cpu_usage is null if cpu not used

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2626]
### Relevant telegraf.conf:
```
[[inputs.procstat]]
pattern = "foo"
```

### System info:

Telegraf version: custom build based on 1.2.1 with some master & PR commits cherry-picked. https://github.com/phemmer/telegraf/commit/1c214d01a0e739ca40fc6ddaa20f2017430fc5d4
OS: Linux, CentOS/7

### Steps to reproduce:

1. Run telegraf with procstat input
2. Have a monitored process use no cpu between polling interval.

### Expected behavior:
Report a `0` value for `cpu_usage`.

### Actual behavior:
Reports a null value for `cpu_usage`.

### Additional info:
A `0` value cpu usage is not the same as a null value cpu usage. Null means we have no data. `0` means we have data, but it was 0. If you want to do something like calculate an average, you'll get incorrect results as it wont factor in the points where CPU usage was really 0.

I personally have no intention of using `cpu_usage`, as I much prefer to use the raw time metrics and calculate CPU usage myself. Just reporting as it is a bug as it will affect anyone using it.

**Comment by danielnelson** [comment]
I think I fixed this #2315
