### ISSUE TITLE
most procstat time fields useless

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2627]
### Relevant telegraf.conf:
```
[[inputs.procstat]]
pattern = "foo"
```

### System info:
Telegraf version: custom build based on 1.2.1 with some master & PR commits cherry-picked. https://github.com/phemmer/telegraf/commit/1c214d01a0e739ca40fc6ddaa20f2017430fc5d4
OS: Linux, CentOS/7

### Steps to reproduce:

1. run telegraf

### Expected behavior:
Receive meaningful fields

### Actual behavior:
Receive fields who's values are always `0`. Specifically: `cpu_time_guest`,`cpu_time_guest_nice`,`cpu_time_idle`,`cpu_time_iowait`,`cpu_time_irq`,`cpu_time_nice`,`cpu_time_soft_irq`,`cpu_time_steal`,`cpu_time_stolen`

### Additional info:
The library telegraf uses, gopsutil, does not put anything in these fields. Thus they are useless to output.

https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L844-L848
```
	cpuTimes := &cpu.TimesStat{
		CPU:    "cpu",
		User:   float64(utime / ClockTicks),
		System: float64(stime / ClockTicks),
	}
```

https://github.com/shirou/gopsutil/blob/master/process/process_darwin.go#L313-L317
```
	ret := &cpu.TimesStat{
		CPU:    "cpu",
		User:   utime,
		System: stime,
	}
```

https://github.com/shirou/gopsutil/blob/master/process/process_freebsd.go#L212-L216
```
	return &cpu.TimesStat{
		CPU:    "cpu",
		User:   float64(k.Rusage.Utime.Sec) + float64(k.Rusage.Utime.Usec)/1000000,
		System: float64(k.Rusage.Stime.Sec) + float64(k.Rusage.Stime.Usec)/1000000,
	}, nil
```

https://github.com/shirou/gopsutil/blob/master/process/process_openbsd.go#L202-L206
```
	return &cpu.TimesStat{
		CPU:    "cpu",
		User:   float64(k.Uutime_sec) + float64(k.Uutime_usec)/1000000,
		System: float64(k.Ustime_sec) + float64(k.Ustime_usec)/1000000,
	}, nil
```

**Comment by danielnelson** [comment]
Are these metrics event even applicable on a per process basis?  Perhaps only `cpu_time_guest`.

**Comment by phemmer** [comment]
On linux (and I suspect all OSs), no.
On linux you only get:
```
              (14) utime  %lu
                        Amount of time that this process has been scheduled
                        in user mode, measured in clock ticks (divide by
                        sysconf(_SC_CLK_TCK)).  This includes guest time,
                        guest_time (time spent running a virtual CPU, see
                        below), so that applications that are not aware of
                        the guest time field do not lose that time from
                        their calculations.

              (15) stime  %lu
                        Amount of time that this process has been scheduled
                        in kernel mode, measured in clock ticks (divide by
                        sysconf(_SC_CLK_TCK)).

              (16) cutime  %ld
                        Amount of time that this process's waited-for
                        children have been scheduled in user mode, measured
                        in clock ticks (divide by sysconf(_SC_CLK_TCK)).
                        (See also times(2).)  This includes guest time,
                        cguest_time (time spent running a virtual CPU, see
                        below).

              (17) cstime  %ld
                        Amount of time that this process's waited-for
                        children have been scheduled in kernel mode,
                        measured in clock ticks (divide by
                        sysconf(_SC_CLK_TCK)).
```

**Comment by danielnelson** [comment]
Okay, so for this issue we should remove all of these, Then open another issue to add `guest_time`, which would involve getting it into upstream.

**Comment by powersj** [comment]
next steps: review these fields across the supported OSes/platforms and determine where they could be ignored/removed. If not possible, otherwise document these fields as being useless.
