### ISSUE TITLE
Plugin request: Traefik

### ISSUE THREAD

**Issue by kszucs** [influxdata/telegraf#2634]
https://github.com/containous/traefik

There is a collectd plugin: https://github.com/acquia/collectd-traefik

**Comment by danielnelson** [comment]
:+1:

**Comment by mlabouardy** [comment]
@danielnelson @kszucs I just created a plugin for traefik https://github.com/influxdata/telegraf/pull/2668

**Comment by danielnelson** [comment]
@mlabouardy Can you split it out from the icinga2 plugin?

**Comment by mlabouardy** [comment]
@danielnelson done

**Comment by sjwang90** [comment]
Traefik now supports exporting data to InfluxDB directly, with many more stats, and we can pipe that through Telegraf using the `influxdb_listener` plugin.

Check out: https://github.com/influxdata/telegraf/wiki/Traefik

**Comment by kszucs** [comment]
Thanks @sjwang90!
