### ISSUE TITLE
Setting agent precision does nothing

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2638]
## Bug report

Setting the agent precision does not work, precision is always at 1s.

### Relevant telegraf.conf:
```
[agent]
  interval = "1s"
  round_interval = true
  collection_jitter = "0s"
  precision = "us"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false

```
### System info:

aa722fac9b6585069d405a9bc1772d4900d971b0

### Steps to reproduce:

1. `telegraf --config telegraf.conf --input-filter cpu --test`

### Expected behavior:

`cpu,cpu=cpu-total usage_system=0.5 1491611824476047000`

### Actual behavior:

`cpu,cpu=cpu-total usage_system=0.5 1491611931000000000`

### Additional info:

The units only cannot be parsed by `func (d *Duration) UnmarshalTOML(b []byte) error`, and no error is reported.

**Comment by phemmer** [comment]
You need `precision = "1us"`. Otherwise it's evaluated as `"0us"`, which is just `0`, which it then rounds to your `interval` value.
