### ISSUE TITLE
Add auth token to OpenTSDB

### ISSUE THREAD

**Issue by RemyTinco** [influxdata/telegraf#2640]
## Feature Request

Allow HTTP(S) basic auth in OpenTSDB connection.

### Current behavior:
```
[[outputs.opentsdb]]
        host = "http://opentsdb-gra1.tsaas.ovh.com"

```

### Desired behavior:

```
[[outputs.opentsdb]]
        host = "http://opentsdb-gra1.tsaas.ovh.com"
        tokenId = "foo",
        tokenKey = "bar"
```

### Use case: [Why is this important (helps with prioritizing requests)]
I'm using OVH PaaS for monitoring. We must use token ... 
Actually, you can find an example here : https://github.com/runabove/iot-push-examples/blob/master/Golang/go-client.go

**Comment by cambierr** [comment]
To get this more general I suggest using `username` instead of `tokenId` and `password` instead of `tokenKey`.

**Comment by mirath** [comment]
Doesn't https://github.com/influxdata/telegraf/pull/1913 closes this?

**Comment by danielnelson** [comment]
Thanks for pointing out this related issue @mirath.  It looks to me like that PR does not actually add basic auth support as titled, but instead allows passing through the userinfo section of the url.

**Comment by mirath** [comment]
I looked at the changes and it looks that, for an url formated as https://<user>:<pass>@example.com/, it passes <user>:<pass> as a string to whatever it creates the HTTP/HTTPS connection. If that is the case wouldn't that allow to connect to OpenTSDB using basic auth?

**Comment by danielnelson** [comment]
Basic auth uses the Authorization header and base64 encodes the user:password.

**Comment by reimda** [comment]
It looks like the opentsdb plugin code parses the url and ignores all of it but the host section. This means the user:password isn't passed on to connection so #1913 doesn't fix the problem.

**Comment by reimda** [comment]
Since the username and password is passed through to the connection, it appears that #1913 does fix this. Closing
