### ISSUE TITLE
Setting config [agent] debug = true causes crash

### ISSUE THREAD

**Issue by seprich** [influxdata/telegraf#2641]
### Relevant telegraf.conf:

[agent]

debug = true

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf version 1.2.1
Running in docker container:
FROM centos:7
COPY influxdb.repo /etc/yum.repos.d/influxdb.repo
RUN yum -y install telegraf

### Steps to reproduce:
Running the container with with a telegraf.conf with the aforementioned `debug` option on produces the following error to the log and crashes (container goes into reboot loop):
```
2017/04/10 12:48:08 I! Using config file: /etc/telegraf/telegraf.conf
2017/04/10 12:48:08 E! Could not parse [agent] config
2017/04/10 12:48:08 E! Error parsing /etc/telegraf/telegraf.conf, line 32: field corresponding to `MEtric_buffer_limit' is not defined in `*config.AgentConfig'
```
If I set `debug = false` telegraf runs without complaints.

**Comment by danielnelson** [comment]
Can you attach the full `[agent]` section?

**Comment by seprich** [comment]
must have been one of those accidentally inserted uncommon whitespace or imprintable characters in my configuration file because now I can't reproduce the problem which I reported.. (the value was edited in place within the container and since the container went to reboot loop I destroyed it).
