### ISSUE TITLE
Feature Request: GPU Metrics

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2642]
### Proposal:

Can we gather GPU metrics for the host system?

### Current behavior:

Currently, only the mesos pluging, AFAIK, has any method of reporting GPU utilization.

### Desired behavior:

Much like CPU and Memory utilization, it would be great to get host-level metric on how much a GPU is being utilized.

### Use case: [Why is this important (helps with prioritizing requests)]

Main use case from the person in charge of the hardware is to know if additional hardware is required in order for our software to run optimally.  Also, from a development standpoint, metrics gathered could be used by developers to better optimize their software.

**Comment by danielnelson** [comment]
:+1:

**Comment by sebito91** [comment]
Out of curiosity what kind of GPUs are you looking to query from? I've been working on something for nvidia-related setups, not sure how hard that would be to extend beyond that.

**Comment by sybrandy** [comment]
Currently looks like Nvidia.

**Comment by deric** [comment]
I'm afraid this will be vendor-specific. For nvidia you can use something like:
```
$ nvidia-smi --format=csv --query-gpu=power.draw,utilization.gpu,fan.speed,temperature.gpu
power.draw [W], utilization.gpu [%], fan.speed [%], temperature.gpu
11.04 W, 0 %, 33 %, 34
```
or without header and units:
```
nvidia-smi --format=csv,noheader,nounits --query-gpu=power.draw,utilization.gpu,fan.speed,temperature.gpu
10.80, 0, 33, 34
```
and just parse comma separated values.

**Comment by sachinrase** [comment]
can we still add it , even if its vendor specific

**Comment by danielnelson** [comment]
Vendor specific is not a problem.  BTW, for radeon cards some of this is in `/sys/class/drm/card0/device/` as well as through lm-sensors.

**Comment by timhallinflux** [comment]
Reference: http://xcat-docs.readthedocs.io/en/stable/advanced/gpu/nvidia/management.html

**Comment by samson-wang** [comment]
I use the `inputs.exec` to collect gpu metrics. And create a dashboard to display. However, it seems that the dashboard can't be displayed in the host page together with cpu, disk and other system metrics?

**Comment by danielnelson** [comment]
@samson-wang Can't help with the dashboard problem here, 
why don't you try asking over at the [InfluxData Community](https://community.influxdata.com) site.  Make sure to mention what application you are using to create your dashboards.

**Comment by samson-wang** [comment]
@danielnelson Thanks for your tip. It's my first day of using TICK STACK.
I use chronograf as my frontend. Will the gpu metrics be added to the default host view in `v1.4.0`? Or it's  all chronograf's decision?

**Comment by nhaugo** [comment]
@samson-wang you should drop a feature request in chronograf's github, the "default" host view is generated by existing measurements. So if you are collecting data on that host it will show up. So default views of the data need to be created, if you have some queries that work for you this would be super easy.

The docs are at https://github.com/influxdata/chronograf/blob/master/docs/LAYOUT.md

**Comment by timhallinflux** [comment]
@samson-wang -- also, it would be great to understand what stats you are gathering and using from the GPUs.  Can you share more details?  You are currently using a generic collection mechanism.  To render stats from a generic source is going to be tricky in Chronograf - but if we can get some additional inputs/insight and engagement that would help determine how best to proceed with building a more specific plug-in that could be easily rendered.  Thanks!

**Comment by samson-wang** [comment]
@nhaugo Thanks for your tip. I created the gpu pre-canned template. It works great.

@timhallinflux I would like to monitor gpu's memory usage and other stuffs.  Though not a final version, you can refer to https://gist.github.com/samson-wang/6de1f19c0bea3741c150a3b54fd97dd7

**Comment by jbboehr** [comment]
If you don't mind experimental native code, I've thrown this together: https://github.com/influxdata/telegraf/compare/master...jbboehr:nvml?expand=1

It requires being built with `-tags nvml` and uses my fork of https://github.com/davidr/go-nvml

We're in the process of switching from newrelic, where we previously used https://github.com/jbboehr/newrelic-nvidia-plugin, to signalfx.

**Comment by jimdowling** [comment]
This is a working plugin for nvidia-smi. Would be nice to see it merged:
https://github.com/datamachines/telegraf-nvidia-smi

**Comment by duffyjp** [comment]
I tried using the nvidia-smi on Windows 10 and didn't have any luck.  Is it included in the 1.6.4 download?

**Comment by timhallinflux** [comment]
@duffyjp  -- No.  It's in the 1.7rc's and soon 1.7 final.

**Comment by duffyjp** [comment]
@timhallinflux cool thanks.  Looking forward to it!

**Comment by timhallinflux** [comment]
1.7 is available now.
