### ISSUE TITLE
Track linux netfilter connection count

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2643]
### Proposal:
Telegraf should track the linux netfilter connection count & max. These are the values in `/proc/sys/net/netfilter/nf_conntrack_count` and `/proc/sys/net/netfilter/nf_conntrack_max`

### Current behavior:
Not tracked

### Desired behavior:
Track

### Use case: [Why is this important (helps with prioritizing requests)]
Once the `nf_conntrack_count` value reaches the `nf_conntrack_max` value, connections will start erroring out (packets dropped). Thus this is an important metric to monitor.

Now I'm not sure where we should put this. We already have numerous network measurements (`nstat`, `netstat`, & `net`), and this is just 2 fields, thus I'm not sure it warrants its own measurement. But if we do bundle it into one of those existing ones, I'm not sure which.

**Comment by danielnelson** [comment]
Probably a stupid suggestion but does it belong with iptables?

**Comment by phemmer** [comment]
We might be able to put it in the plugin, but it wouldn't be able to go in the measurements it generates.

**Comment by danielnelson** [comment]
Conceptually does it fit?

**Comment by phemmer** [comment]
As far as it's related to iptables sure. However one thing that I am uncertain about is whether it's also utilized by [nftables](https://www.netfilter.org/projects/nftables/). If it is, then I would say that it should not be in an iptables-specific plugin.

But that aside, you could also say that it's a kernel resource, therefor it belongs in the `system` plugin. Or that it's a network resource, and so belongs in `net`.

**Comment by rlex** [comment]
Correct me if i'm wrong, but there is "conntrack" input plugin, which does exactly that.

```
[[inputs.conntrack]]
    files = ["ip_conntrack_count","ip_conntrack_max", "nf_conntrack_count","nf_conntrack_max"]
    dirs = ["/proc/sys/net/ipv4/netfilter","/proc/sys/net/netfilter"]
```

Been using it for a long time.

**Comment by phemmer** [comment]
you look to be correct. not sure how I missed that.
I'll take a poke at it today just to make sure it satisfies the need. But I expect it will. Will close ticket once verified.

Thanks

**Comment by rithinnambiar1** [comment]
How i can increase and conntrack count  test it in the openstack enviornment

**Comment by powersj** [comment]
Hi,

It does look like the conntrack plugin will resolve this feature request. Closing out.
