### ISSUE TITLE
Make consul service_id a tag.

### ISSUE THREAD

**Issue by skygragon** [influxdata/telegraf#2646]
For example, the consul input will generate metric like:

> consul_health_checks,node=consul01,service_name=,check_id=serfHealth,host=consul01 check_name="Serf Health Status",service_id="",status="passing" 1491927292000000000 

Please note that those kvs like "check_name/service_id/status" will failed to send to openTSDB because it doesn't support string values....

**Comment by skygragon** [comment]
Btw, just wondering why we use "service_name" as a tag, but "service_id" as a key name? Can we make those strings always as tags(or part of metric name) and only expose number as the value? e.g. metric="consul_service_<service_name/id>", node=xxx,xxx=xxx status=1|0

**Comment by danielnelson** [comment]
I think it would make sense to make service_id a tag.  However, we shouldn't have empty tags or fields either, so we should also remove those tags.

**Comment by danielnelson** [comment]
On the status part, I don't want to do that because it will make the point worse for other outputs, as well as be a breaking change.  Perhaps the opentsdb output could handle it or a processor that converts types.

**Comment by danielnelson** [comment]
Also, making `service_id` a tag would be a breaking change, so we would need an option to opt-in.

**Comment by skygragon** [comment]
@danielnelson Yep, I agree. As a input plugin, it's not proper to make special changes for openTSDB only. So who is in charge of openTSDB plugin,  better to hear his thoughts as well.

**Comment by skygragon** [comment]
What about using separate metric for different service? put everything in the same metric "consul_health_checks" seems not necessary?

**Comment by danielnelson** [comment]
I think having them in a single metric with the `service_name` as a tag is the proper way to structure them for most outputs.  How does the data look that is being sent to OpenTSDB?
