### ISSUE TITLE
Monitor available kernel entropy

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2647]
### Proposal:
Telegraf should be able to monitor available kernel random entropy. On linux this is exposed through `/proc/sys/kernel/random/entropy_avail`. 

### Current behavior:
Telegraf cannot monitor available kernel random entropy.

### Desired behavior:
Monitor available kernel random entropy.

### Use case: [Why is this important (helps with prioritizing requests)]
For applications which utilize `/dev/random` a lot, the entropy pool can run out, and cause said applications to significantly slow down. Thus it is important to monitor for entropy pool exhaustion, and for an admin to intervene if the pool is frequently running low.

**Comment by phemmer** [comment]
One thing that might be useful for this, and other requests such as #2643, and #2609, would be a generic "sysctl" or "file" input. Most of the time the sysctl files just contain a single number. We could create an input plugin which behaves something like:

```
[[inputs.file]]
  [[inputs.file.file]]
    path = "/proc/sys/kernel/random/entropy_avail"
    field = "entropy_avail"
    data_format = "value"
  [[inputs.file.file]]
    path = "foo"
    field = "bar"
    data_format = "value"
```

We can make configuration simpler by defaulting `data_format` to `"value"` and `field` to the filename component of `path`.

The only thing this might not handle is things such as the formats handled by the [linux_sysctl_fs](https://github.com/influxdata/telegraf/pull/2609) input, which can be multiple fields in one file.
For these we can either support an array of fields, such as `fields = ["field1","field2","field3"]`, or use a grok pattern. If we want this input to be able to handle stuff other than `/proc/sys`, a grok pattern is really the only option, as space delimitation is too inflexible.

**Comment by danielnelson** [comment]
Yeah it is a good idea, could almost do it with tail, but not quite and also tail comes with problems.  I think grok should also probably become a data_format, though we do get a lot of support related questions when using it.

For this one in particular it's probably best to have it as a first class series.  What are you thinking for the measurement name?

**Comment by phemmer** [comment]
I dunno. I personally dislike having tons of itty bitty measurements. I would be more inclined to put this in with something else, such as `kernel` or `system`.
But if it is going to be a separate measurement, "kernel_entropy".

**Comment by danielnelson** [comment]
Reading over the `system` and `kernel` plugin READMEs it doesn't really match.  I think `system` is probably a bad name, maybe should have been `uptime`, but that ship has sailed.  Entropy is very kernel-y in nature, but currently `kernel` is basically /proc/stat.  What if we rewrite the README for kernel and make this optional with default being off?  That or the `kernel_entropy` idea.

**Comment by joelio** [comment]
Happy to help on this if a direction's been decided upon

**Comment by danielnelson** [comment]
I think we should just add this to the kernel plugin, I don't think we need an option but we will need to generalize the documentation a bit.
```
kernel entropy_avail=3334i
```
