### ISSUE TITLE
processes input means config is not cross-platform

### ISSUE THREAD

**Issue by rburchell** [influxdata/telegraf#2652]
### Relevant telegraf.conf:

```
 # Get the number of processes and group them by status
 #[[inputs.processes]]
 #  # no configuration
```

### System info:

1.2.1, macOS & Windows 10.

### Steps to reproduce:

I had a working telegraf config already, and attempted to run it on a Windows PC on my network to get additional "coverage".

### Expected behavior:

The same config works across multiple hosts.

### Actual behavior:

I was greeted by this:

> 2017/04/12 01:12:59 E! Error parsing E:\telegraf\telegraf.conf, Undefined but requested input: processes

### Additional info:

It was quite easy to get past (comment out the processes input plugin in the config), but it'd be nice if the same config worked without issues across platforms. Is this possible?

**Comment by danielnelson** [comment]
I think ideally it would warn but still start.

**Comment by frittefinans** [comment]
Hi, did you guys solve this?

**Comment by danielnelson** [comment]
Not yet, it is likely the fix will just be a better error message.  I don't think it is possible to have the config work across systems.

**Comment by ajayjawale** [comment]
hello there,

its seems like this error still exists...
I am using Windows 10 with telegraf 1.8.2 and while configuring basic configuration for [[inputs.processes]] as listed below, --test serving me error message "E! Error parsing E:\telegraf\telegraf.conf, Undefined but requested input: processes" 

 # Get the number of processes and group them by status
 #[[inputs.processes]]
 #  # no configuration

what can be done to overcome the same? 
any ideas, thoughts?

**Comment by barbaranelson** [comment]
The fix for this customer is to comment out the line [[inputs.processes]], i.e. change it to
#[[inputs.processes]]

The explanation is that the processes plugin doesn't work on Windows.  I'll follow up separately with the Chronograf team on whether this plugin should not be included by default.
