### ISSUE TITLE
"signal: killed" showed on Mac OS

### ISSUE THREAD

**Issue by hjf1223** [influxdata/telegraf#2656]
### Relevant telegraf.conf:

NONE

### System info:

commit id: 0193cbee513bbd66b61f36a533241b9b212758fb

MacOS 10.12.4 (16E195)

### Steps to reproduce:

1. go run telegraf.go

### Expected behavior:

```
E! No config file specified, and could not find one...
```

### Actual behavior:

```
signal: killed
```

### Additional info:

I try to remove the two lines in github.com/influxdata/telegraf/plugins/inputs/all:

```
_ "github.com/influxdata/telegraf/plugins/inputs/system"
_ "github.com/influxdata/telegraf/plugins/inputs/procstat"
```

then it works.

**Comment by danielnelson** [comment]
I had someone duplicate this, seems to be related to the the imports of one of these imports and having cgo enabled:
```
"github.com/shirou/gopsutil/cpu"
"github.com/shirou/gopsutil/process"
```
I don't actually have a Mac though, can you add these import in your all.go file and see which one is causing it?

**Comment by hjf1223** [comment]
Hi

I had tried it, both them will cause it.

**Comment by danielnelson** [comment]
Thanks for checking, I guess we should try to make a minimal case that would be suitable as a gopsutil issue.

**Comment by danielnelson** [comment]
@hjf1223 We were able to fix a very similar issue here by upgrading to go 1.8.1.  Can you check if this fixes your issue?

**Comment by hjf1223** [comment]
It seems fixed on go1.8.1 .

thanks
