### ISSUE TITLE
Getting metrics about usage by a user

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/telegraf#2657]
How can we get metrics about per user usage of the CPU, MEMORY, PROCESS, NET and SWAP ?
that which user is using how much resources.

Like this,

![whatsapp image 2017-04-12 at 16 24 34](https://cloud.githubusercontent.com/assets/23127804/24954403/de9e2126-1f9c-11e7-8119-dfc110961aa9.jpeg)

Is it possible or not in Telegraf ?

**Comment by danielnelson** [comment]
If you have the right cgroups setup you could do this with the cgroups plugin.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
