### ISSUE TITLE
Getting Table Name as tag value

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/telegraf#2675]
## Bug report
It is a question, if not solved already it could be an enhancement

### Relevant telegraf.conf:
link to telegraf.conf file -->  [file](https://bpaste.net/show/45465df56177)

### System info:
ubuntu 16.04

[Include Telegraf version, operating system name, and other relevant details]
current version

### Steps to reproduce:

1. Connect it to postgres, and use postgresql_extensible plugin to fetch data

### Expected behavior:
Expected table names to be stored as tags, like databases names can be stored

### Actual behavior:
Table names are stored as fields, not tags. So, can not use where clause on table names

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

### Use case: [Why is this important (helps with prioritizing requests)]
This is important as it will help optimize the monitoring

Firstly, please read it fully, I did not put it in the community as answers are obtained very late and sometimes answers are not obtained at all.

I am using the [postgres_extensible] plugin.

I wanted stats about particular databases and tables. So, I used `pg_stat_database` and `pg_stat_all_tables`.

What I wanted was to get results in grafana according to different database. So, the solution was to store database name as a tag, which we could do easily as defined in the conf file example. Here, 

`#   ## A list of databases to pull metrics about. If not specified, metrics for all`
`#   ## databases are gathered.`
`   databases = ["checkdb","testerdb"]`
`#   #`
`#   ## Define the toml config where the sql queries are stored`
`#   ## New queries can be added, if the withdbname is set to true and there is no`
`#   ## databases defined in the 'databases field', the sql query is ended by a`
`#   ## 'is not null' in order to make the query succeed.`
`#   ## Example :`
`#   ## The sqlquery : "SELECT * FROM pg_stat_database where datname" become`
`#   ## "SELECT * FROM pg_stat_database where datname IN ('postgres', 'pgbench')"`
`#   ## because the databases variable was set to ['postgres', 'pgbench' ] and the`
`#   ## withdbname was true. Be careful that if the withdbname is set to false you`
`#   ## don't have to define the where clause (aka with the dbname) the tagvalue`
`#   ## field is used to define custom tags (separated by commas)`
`#   ## The optional "measurement" value can be used to override the default`

Now, I can put a where clause on the database names defined in the `databases=["checkdb","testerdb"]` above. 

This is all good. But the problem is when I collect stats from the `pg_stat_all_tables`.

I want to create a where clause on the table name(relname), so that I can see data according to different tables(like I can do in the databases). But I can not do that as the relname is stored as a field and not as a tag.

Here take a look, pictures might clarify you more.

![screenshot from 2017-04-15 04-01-43](https://cloud.githubusercontent.com/assets/23127804/25057775/69db92c4-2190-11e7-81e6-8664ae1dda1b.png)

This is from the `pg_stat_database`, As you can see , I can easily put `WHERE db = testerdb`, just because the database name was stored as tag. 

Now take a look at the picture below,

![screenshot from 2017-04-15 04-02-12](https://cloud.githubusercontent.com/assets/23127804/25057780/6f4a4b60-2190-11e7-9a91-63a442050f9a.png)
 
This is from the `pg_stat_all_tables`, now see where my cursor is pointing, it is pointing at the `relname` field of the measurement. This means that I cannot have a query like `WHERE relname = bikes` as the relname is a field and not a tag.

Like we can give the databases to be monitored in the `databases=["checkdb","testerdb"]` , Can we give table names like this in some kind of list ?

AND

I would like to know how can I store this relname as a tag and not as a field ? Is it possible or not ? I really hope you get my question because i want to only monitor some tables and not all the tables.

**Comment by danielnelson** [comment]
Does it work if you add `relname` to the tagvalue option?
```
  [[inputs.postgresql_extensible.query]]
    sqlquery="SELECT * FROM pg_stat_all_tables"
    version=901
    withdbname=false
    tagvalue="relname"
    measurement="pg_stat_all_tables"
```

**Comment by sLuvpreet33** [comment]
If we wanted multiple values as tags,
How can we add multiple values to this tagvalue ? 

tagvalue="relname, relid" like this ?

**Comment by danielnelson** [comment]
I think you might need to remove the space.

**Comment by sLuvpreet33** [comment]
Grazie, It works.

Another question which is unanswered is stated below, Please readit,

Under the [inpus.logparser] plugin,

I give 2 files in the file list, 

` files = ["/var/log/nginx/kibana_access.log","/var/log/nginx/api_access.log"]`

but measurement name is only one, 

`   measurement = "nginx_access_log"`

This is not good as I cannot know which log file's data is being shown in grafana.

What if I wanted a different measurement for each file in the files list ?

**Comment by danielnelson** [comment]
To do this you need to use two inputs, one for each measurement name.

**Comment by sLuvpreet33** [comment]
means I should define 2 logparsers in the file ? Is not that against the rules, code repetition ?

**Comment by danielnelson** [comment]
All the inputs can be listed multiple times (this is why they have two brackets in the configuration `[[inputs.logparser]]`).  There are times that it does become quite repetitive, but it is rather flexible.
