### ISSUE TITLE
Redis plugin - Send maxmemory config value

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/telegraf#2681]
### Proposal:

I propose that in addition to the current data sent by the Redis plugin, the setting for maxmemory is sent. This can be retrieved with the following command

```
CONFIG GET maxmemory
```

### Current behavior:

maxmemory is not sent

### Desired behavior:

maxmemory is sent

### Use case:

It is useful to set up alerts in Kapacitor if the used memory gets dangerously close to the maxmemory setting. Without sending the maxmemory setting to InfluxDb, we need to statically set the alert threshold. If we send the maxmemory setting we can divide memory use by maxmemory setting and alert based on the percentage.

Another thought is that the redis telegraf configuration could take a comma separate field e.g.

```
config_values = ["maxmemory,other-config-im-interested-in"]
```

Then, the redis.go could try to `CONFIG GET` each of those and send a field such as 

```
config_maxmemory
config_other_config_im_interested_in
```

**Comment by danielnelson** [comment]
Definitely would be good to have maxmemory.

The config idea is good as well.  We should probably have a list for include and exclude like we have for tagpass/tagdrop.  One tricky bit is what should be default and how it is defined, maybe if both lists are undefined we use a default list with the current fields?

**Comment by mpchadwick** [comment]
Was just looking into implementing this and low and behold `maxmemory` was already being sent. [This](https://github.com/influxdata/telegraf/commit/41a5ee65713c644a2571267f5ee2a6c93926e3b0) change seems to have added it. I was looking at a server running and older version of Telegraf which is why I didn't see it there.
