### ISSUE TITLE
Connect to Redshift to extract custom data and build metrics to push to Influx

### ISSUE THREAD

**Issue by anilkulkarni87** [influxdata/telegraf#2683]
## Feature Request

The current postgesql_extensible doesnt have the ability to conect to redshift and transform query results to Line protocol to write to Influx.

### Proposal:
Create an input plugin to connect to redshift and execute queries and transform each row to Line protocol basedon the measurements and tags provided in the .conf file.

### Current behavior:
postgreaql_extensible plugin does nto connect to Redshift. While trying to use the same, it doesnt throw the right error. 
It displays the error as below for any query being run (eg. Select sysdate)
2017-04-18T20:38:00Z E! ERROR in input [inputs.postgresql_extensible]: sql: no rows in result set

### Desired behavior:
The below info can be provided the in the .conf file Note that there is 'version'. 
[[inputs.redshiftsql.query]]
    sqlquery="select sysdate"
    withdbname=false
    tagvalue=""
    measurement="" 

### Use case: 
This helps in building custom metric out of Redshift data. AWS doesnt provide the ability to monitor at a table a level on the console. This plugin can be used to monitor any custom metrics defined based on the data inside. 

Tried creating the below script which might have errors but i have not been able to build the telegraf binaries and do some tests. The below script has very minor changes compared to the postgresql_extensible plugin.

[redshift_sql.txt](https://github.com/influxdata/telegraf/files/931024/redshift_sql.txt)

**Comment by anilkulkarni87** [comment]
@danielnelson  Any luck on this?

**Comment by danielnelson** [comment]
I'm in favor of having Redshift support, but any plugin would have to be contributed by the community or through [sales](https://www.influxdata.com/contact-sales/).

**Comment by danielnelson** [comment]
https://github.com/jackc/pgx/issues/321

**Comment by tfoldi** [comment]
I think you can safely close this one: we are using telegraf with redshift in production since a while. 

So it does work with redshift.
