### ISSUE TITLE
Data type transformer process plugin

### ISSUE THREAD

**Issue by rijnhard** [influxdata/telegraf#2691]
## Feature Request

Sometimes it isn't easy to change the data type or the information being sent at its source, either because it's out of your control or a lack of priority, or you have information going to the same metrics from different systems.

### Proposal:
TBD

### Current behavior:
Errors on mixed data types, or not able to change data types.

### Desired behavior:
Allow casting of data types to single type. Ideally the behaviour of how it does this should be configurable, i.e. from float to int: ceil, floor, round, trunc.

### Use case: [Why is this important (helps with prioritizing requests)]
You may have an issue with different data types being mixed for a single metric:
```
E! Field type conflict, dropping conflicted points: {"error":"field type conflict: input field \"value\" on measurement \"campaign\" is type integer, already exists as type float dropped=6"}
```
So in order to cater for this telegraf could have a process plugin that allows data type casting or basic transformations.

**Comment by sjwang90** [comment]
Feel free to use the `processors.converter` to address this issue
