### ISSUE TITLE
Information about the collected stats from the System

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/telegraf#2692]
I am using latest version of Telegraf in ubuntu 16.04 Dell laptop.

I want to know about the stats Telegraf collects about the system. I searched for them on the input plugins page of Telegraf on github, but these were not definde there, but given in the conf file.

Firstly, 

about the net measurement that is created in the influxdb by `[inputs.net]` plugiin,

What is the unit(b/s, kb/s, mb/s) of bytes_recv and bytes_sent, packets_sent and packets_recv ? And Is this the current live value OR this is incrementing value ? Units are required as we have to see those things in grafana.

Secondly , I want to know about the Disk stats,

The units of  Memory and  Inodes .

Next is `diskio`plugin ,

Unit of 
1 - iotime
2 - read_time
3 -write-time
Also, the reads, writes, read_bytes, write_bytes are current values OR incrementing values ?

And the last I want to ask is the system input plugin, 
what is load1, load15 and load5 and there units?

**Comment by danielnelson** [comment]
There is an issue open for writing net plugin documentation: https://github.com/influxdata/telegraf/issues/2166

The disk and diskio plugins are documented under plugins/input/system, some of your questions are answered there [1].  The bytes values are all going to incrementing values.

You can reference the system docs [2], the load values are the standard unix load average numbers [3].

[1] https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/DISK_README.md
[2] https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/SYSTEM_README.md
[3] https://en.wikipedia.org/wiki/Load_(computing)#Unix-style_load_calculation

**Comment by sLuvpreet33** [comment]
Thank you, that helped. You said that documentation is being made for net plugin, but for the time being, Can you tell me from where the net plugin takes all it's data ?

**Comment by danielnelson** [comment]
On linux it uses `$ cat /proc/net/dev`.  The parsing of this file is over in gopsutil 
https://github.com/shirou/gopsutil/blob/master/net/net_linux.go#L30

**Comment by sLuvpreet33** [comment]
Hey @danielnelson  How can we get total keys in Redis ?

`alphauser@AlphaServer:~$ redis-cli`
`127.0.0.1:6379> info keyspace`
`# Keyspace`
`db0:keys=3,expires=0,avg_ttl=0`
`db1:keys=679,expires=679,avg_ttl=1525952129`

It gives this output per redis db, So how can we get total keys in each database ?

I am having a tough time figuring this out.

**Comment by danielnelson** [comment]
@sLuvpreet33 https://github.com/influxdata/telegraf/issues/2706
