### ISSUE TITLE
Httpjson: handle dots in JSON values

### ISSUE THREAD

**Issue by vania-pooh** [influxdata/telegraf#2693]
### Relevant telegraf.conf:
```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[aggregators.minmax]]
  period = "60s"
  drop_original = true
[[outputs.graphite]]
  servers = ["localhost:42000"]
  prefix = "one_min"
  template = "one_min.host.measurement.field"
  timeout = 5
[[inputs.httpjson]]
  name = "selenoid"
  servers = [
    "http://localhost:4444/status"
  ]
  response_timeout = "5s"
  method = "GET"
  [inputs.httpjson.parameters]
    event_type = "cpu_spike"
    threshold = "0.75"
```
### System info:
```
telegraf: 1.2.1-alpine in Docker container
Linux 4.2.0-41-generic #48~14.04.1-Ubuntu 
Ubuntu 14.04.5 LTS
```
### Steps to reproduce:

1. Having input JSON from HTTP service containing dots in key names (e.g. `56.0`, `57.0` and so on):
```
{"total":80,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"56.0":{},"57.0":{}}}}
```
2. Sending this data to Graphite where dot is metric delimiter.

### Expected behavior:
Dots in JSON input should be somehow "escaped" (e.g. replaced by underscores).
`one_min.hostname.httpjson_selenoid.browsers_chrome_56_0_unknown`

### Actual behavior:
The following metrics are sent: `one_min.hostname.httpjson_selenoid.browsers_chrome_56.0_unknown` In this metric name browsers_chrome_56.0_unknown will be split by Graphite into two values: `browsers_chrome_56` and `0_unknown`.

Not sure whether this should be fixed in some new escaping processor plugin or httpjson input plugin or graphite output plugin. However I consider such behavior a bug with value escaping.

**Comment by danielnelson** [comment]
Are you sure you are using 1.2.1?  I was looking at this plugin recently and updated the documentation because it appeared wrong to me.  Now that I'm looking closer I don't think we have supported fields on nested objects since e619493ece6b26078eac4fbebc9a948de9476af0.

For your JSON I only get:
```
one_min.hostname.httpjson_selenoid.queued 0 1492813582
one_min.hostname.httpjson_selenoid.pending 0 1492813582
one_min.hostname.httpjson_selenoid.response_time 0.005733943 1492813582
one_min.hostname.httpjson_selenoid.total 80 1492813582
one_min.hostname.httpjson_selenoid.used 0 1492813582
```

That said, if I use ```{"42.0": 3}``` I can see your issue and we should escape fields in the graphite serializer.
```
one_min.hostname.httpjson_selenoid.42.0 3 1492814012
```

**Comment by vania-pooh** [comment]
@danielnelson strange, notifications about your comment arrived only now. Will try again.

**Comment by vania-pooh** [comment]
Summon @fote.

**Comment by danielnelson** [comment]
Let me know if this needs reopened.
