### ISSUE TITLE
Support for Global Fields and preset Field values

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#2694]
Similar to the Global Tags configuration option (https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#global-tags) Telegraf should support a Global Fields option to add field key/value pairs to emitted points.

The configuration option would be set either under the generic/global agent config section or per output plugin.

This applies in use cases where points need to be marked with additional information but without affecting series cardinality (e.g. long strings)

**Comment by phemmer** [comment]
Duplicate of #2564

See https://github.com/influxdata/telegraf/issues/2564#issuecomment-290879432
