### ISSUE TITLE
Create/Document process for authenticating from telegraf to graphite

### ISSUE THREAD

**Issue by augray** [influxdata/telegraf#2695]
### Proposal:
If a user wants to send metrics from telegraf to graphite, it's not at all obvious how to do so when graphite has authentication turned on. Other plugins (ex, influxdb) allow you to specify a username/password for the destination being output to. The graphite output plugin should do the same, or document how to do the authentication if it actually is under the current setup.

**Note:** If there actually is a way to accomplish this currently, not only should it be documented, but it would also be nice to have the answer on [this SO question](https://stackoverflow.com/questions/43529941/how-to-setup-authentication-between-telegraf-graphite).

### Current behavior:
Attempting to write to graphite without authenticating while authentication is required produces `Could not write to any Graphite server in cluster`. There is no documentation/obvious way to get around this.

### Desired behavior:
Either (a) allow a username/password pair for the graphite plugin like is done for the influxdb one, or document how to securely transfer telegraf data to graphite when graphite has auth on.

### Use case: [Why is this important (helps with prioritizing requests)]
Graphite + telegraf is a very useful integration. However, some organizations might want their graphite instance open to the internet, but protected by authentication walls. Telegraf integration should still be possible in this situation.

**Comment by danielnelson** [comment]
I am not aware of a way to use username/password authentication currently.

Somewhat related is this pull request which looks like it adds support for client cert checking. #2602

**Comment by nwneisen** [comment]
@augray Can you provide more information about your current setup?  I've been looking through graphite's documentation and project and there doesn't seem to be a method to enable a username and password.  Suggestions from the maintainers seem to be to place graphite/carbon behind an Apache server.

**Comment by augray** [comment]
Sorry, I've long since moved away from this project, and don't recall the details of the set up.
