### ISSUE TITLE
Clarify intended usage of retention_policy property in telegraf.conf file. 

### ISSUE THREAD

**Issue by mottati** [influxdata/telegraf#2696]
## Bug report

The intended usage, and legal values for the **retention_policy** property in the telegraf.conf are not sufficiently documented to understand their usage. 

There is a longer thread on the Forum here: [How to override retention policy in telegraf.conf?](https://community.influxdata.com/t/how-to-override-retention-policy-in-telegraf-conf/676) 

At minimum, please provide some additional documentation describing the intended usage of this property. 

My hope, when I saw this property was that I could use it to set the retention policy of the DB that Telegraf would create for me when the service was started up.

### Relevant telegraf.conf:

> // Retention policy to write to. Empty string writes to the default rp.
> retention_policy = ""

### System info:
Telegraf v1.2.0 (git: release-1.2 b2c1d98cff5a58d5ded3e74741c6bc32d6e789ee)

### Use case: 

WIthout this feature working we have to do an extra post RPM install step of: 

> influx -execute 'alter retention policy "autogen" on "telegraf" duration 45d shard duration 1d'

In our specific use case an alternative work around would be if the influx.conf allowed specification of the autogen default to be something different than forever. If that were possible, we would simply make the change within the InflluxDB configuration and call it a day.

**Comment by danielnelson** [comment]
It seems that there are two pieces to this: a documentation improvement and feature request for setting telegraf to be able to setup the retention policy.

Can you suggest a rewording of the `retention_policy` documentation?

There has been some talk about allowing configuration of connection commands, so maybe we could have RP changes be part of that. #2496

**Comment by mottati** [comment]
I can't knowledgeably suggest a rewording because I don't understand what this property does. 

If the intent of this property is to act as a selector amongst a collection of _existing_ policies, than it would be good to note that requirement in the description. 

As currently documented, it is ambiguous. I interpreted the comment as a possibility to specify a custom retention policy.

**Comment by Febeoro** [comment]
Hello, I read your solution about it. Recently I meet a problem.
Now I use telegraf to recieve line protocol data and insert data into influxDB. However ,I don't find any solution to solve that different measurements use different retention policies. What can I do to achieve IT？

**Comment by danielnelson** [comment]
@Febeoro There was a good example of how to do this posted to the community site recently:

https://community.influxdata.com/t/converting-collecd-binary-stream-to-json-with-telegraf-or-collecd-forwarding/1067/9?u=daniel
