### ISSUE TITLE
Feature Request - flush_jitter - allow for variable precision

### ISSUE THREAD

**Issue by ianduncan** [influxdata/telegraf#2700]
### Proposal:
Allow for variable precision with the flush_jitter option.

### Current behavior:
Time shows the the correct precision, but the flush_jitter is rounded to seconds

I have tried to set the value to something that will provide more randomness:
  flush_jitter = "10000ns"
  precision = "ns"
But the time is rounded to seconds:

> select * from cpu order by time desc limit 10
name: cpu

time                cpu       dc  host                  ...           
1492843780000000000 cpu3      DFW redis2.dfw  ... 
...

### Desired behavior:
Apply the more precise flush_jitter to the time value being sent, so that the results are more random.

### Use case: 
We are running telegraf on almost 100 servers, and we're currently seeing many time collisions that prevent us from collecting consistent statistics.  We would benefit from more consistent results if the time was more random.

**Comment by phemmer** [comment]
You need to set a quantity on your precision. Meaning `precision = "1ns"`

**Comment by danielnelson** [comment]
I was confused by this too and attempted to clarify the docs a bit in https://github.com/influxdata/telegraf/pull/2655.

The `flush_jitter` doesn't affect any of the timestamps, it is only to avoid the thundering herd problem on each flush interval, so I'm going to close this request.  Let me know if you have additional questions or ask over on the [InfluxData Community](https://community.influxdata.com) site.
