### ISSUE TITLE
AWS cloudwatch metrics delay > 15min

### ISSUE THREAD

**Issue by rashmisy** [influxdata/telegraf#2704]
We are using Telegraf to fetch the cloudwatch metrics and charting it using Grafana. Our Cloudwatch config is as shown:

[[inputs.cloudwatch]]
  region = "us-east-1"
  access_key = "xxx"
  secret_key = "yyyy"
  period = "5m"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/EC2"

With this plugin config, we are able to fetch the metrics but as shown in the snapshot, there seems to be a delay of greater than 15m. Is this the norm? 

![image](https://cloud.githubusercontent.com/assets/11869123/25339981/3a65ea80-28fc-11e7-9ac0-5ac2a3214d4c.png)

We would like to get the metrics as close to real time as possible.  Any pointers/suggestions is much appreciated.

**Comment by danielnelson** [comment]
I would think the maximum delay would be 10m, delay + interval, and the minimum delay would be 5m.  However, I don't have an environment setup to test now.

@johnrengelman How much delay do you have?

**Comment by johnrengelman** [comment]
I would think it would be 10m as well, but in practice I've seen it be longer. I think it might be due to either a) data not being available in Cloudwatch yet or b) something to do with period boundaries. Not really sure. This has always been frustrating to me, but i haven't had time to dig into it (and won't in the foreseeable  future).

**Comment by danielnelson** [comment]
I wonder if we are missing one interval because we are expecting AWS to have data 5m back, when sometimes their metric latency is higher.  It might be possible to get better results by increasing the delay in that case.

**Comment by rashmisy** [comment]
Thank you for the suggestion. I do have a few follow up questions on this and your take on this will be much appreciated.

I was wondering, what exactly is the significance of delay? The comment says "Collection Delay (required - must account for metrics availability via CloudWatch API)" and I see in [https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go](cloudwatch code) that this value is subtracted from the time (both start & end) sent to GetMetricStatisticsInput. 

In that case, Increasing the delay , will only increase the gap between the current time and the last fetched datapoint.  We would like to get the data as close to real time as possible.

I tried using 1m delay (rest same config as above)  and it fetched datapoints withing 6m from the current time every 5m. so maximum delay was around 11m. 

min delay
![image](https://cloud.githubusercontent.com/assets/11869123/25661882/48d5e3e4-300a-11e7-8238-4d76ed71ea19.png)

max delay
![image](https://cloud.githubusercontent.com/assets/11869123/25662034/e83ebc26-300a-11e7-944e-cecfedd12073.png)

However, this may not always work [ Eg: if the server is restarted and data is not available for the new time window in Cloudwatch.] 

Wouldn't deducting the delay only from the start time help?

**Comment by danielnelson** [comment]
I think the risk is that if you are too aggressive with the delay you might request points before they are available from CloudWatch, which will result in them being missed.

**Comment by danielnelson** [comment]
I think your question is answered, so I'm going to close.
