### ISSUE TITLE
Telegraf doesn't start and `systemctl status` does not show why

### ISSUE THREAD

**Issue by hgfischer** [influxdata/telegraf#2709]
## Bug report

I found out that I had a broken Telegraf configuration after I've tried to manually run the command from inside the telegraf.service file.

`systemctl status telegraf` does not show the reasons and that's why telegraf could not log anything at all, since it could not read the config file.

I believe that if telegraf could log such configuration loading error to syslog, such kind of issue would be easier to detect.

### System info:

Telegraf 1.2.1-1
Ubuntu 16.04.2

**Comment by phemmer** [comment]
Where did you get your package from?
What does your service file look like? (`systemctl cat telegraf.service`)
What do you see in `systemctl status telegraf`?

**Comment by hgfischer** [comment]
Got it from https://repos.influxdata.com/ubuntu

Service:

```
# /run/systemd/generator.late/telegraf.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/telegraf
Description=LSB: Start telegraf at boot time
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target
Before=shutdown.target
Conflicts=shutdown.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/telegraf start
ExecStop=/etc/init.d/telegraf stop
```

Status:
```
● telegraf.service - LSB: Start telegraf at boot time
   Loaded: loaded (/etc/init.d/telegraf; bad; vendor preset: enabled)
   Active: active (exited) since Tue 2017-04-25 16:14:11 CEST; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3553 ExecStop=/etc/init.d/telegraf stop (code=exited, status=0/SUCCESS)
  Process: 3571 ExecStart=/etc/init.d/telegraf start (code=exited, status=0/SUCCESS)

Apr 25 16:14:11 lb01 systemd[1]: Starting LSB: Start telegraf at boot time...
Apr 25 16:14:11 lb01 telegraf[3571]: Starting the process telegraf [ OK ]
Apr 25 16:14:11 lb01 telegraf[3571]: telegraf process was started [ OK ]
Apr 25 16:14:11 lb01 systemd[1]: Started LSB: Start telegraf at boot time.
```

**Comment by phemmer** [comment]
```
ExecStart=/etc/init.d/telegraf start
```
^ That's why you're having the issue. This isn't the official service file provided by telegraf (which you can see [here](https://github.com/influxdata/telegraf/blob/master/scripts/telegraf.service)).

I have no idea what this "systemd-sysv-generator" thing is, but it looks like it generated that service file.

**Comment by aimdev** [comment]
Hi
Just a comment, I had this on system reboot, and it appears from the log that telegraf could not access rabbit-mq, as rabbit-mq was not available.
I was using the standard service file as shown in the link previously.
Adding rabbitmq-server.service on the After line appears to have fixed it, I assumed that the restart option would cover this situation, obviously not.

Hope this is helpful for others

Aimee

**Comment by danielnelson** [comment]
Thanks @aimdev, I'll think about if this can be fit in to the documentation somewhere.  There is also this issue to allow startup when Telegraf cannot connect.  https://github.com/influxdata/telegraf/issues/3723
