### ISSUE TITLE
Reintroduce CPU "usage_busy" field

### ISSUE THREAD

**Issue by simonklb** [influxdata/telegraf#2710]
When CPU usage percentage was first introduced into the system input plugin a "busy" field was included:
https://github.com/influxdata/telegraf/commit/1e742aec04d5758e529a9be1112d4c6e15b36348

To me that makes a lot of sense seeing that "total CPU busy usage" is very likely the most used CPU metric of them all.

It was eventually removed:
https://github.com/influxdata/telegraf/commit/10b04382014d0c80b194288170428bc1e02bf654

So this means, right now, we have to fall back on either creating a long query with additions or reverse the usage_idle value. Not nice.

Please reintroduce CPU busy usage as it's own field! I believe that this will not only give users a more convenient way of getting the total CPU usage but also eliminate a lot of incorrect queries by users not fully understanding what the differences are between all of the available CPU fields.

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/pull/2594

**Comment by danielnelson** [comment]
@bobmshannon  added `report_active = true` option in #2943 to provide this.
