### ISSUE TITLE
telegraf binary file is not formed in windows while installing it with source code.

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#2713]
hello
we installed go-1.8,git-2.1.2 and try to install telegraf in windows using git hub,
we followed the below procedure 
1.created work space in C:/workspace.
2.next we used below command 
go get github.com/influxdata/telegraf
3.we Run cd $GOPATH/src/github.com/influxdata/telegraf
4.after that we Run
 make windows
we got the following error as
        
C:\work\src\github.com\influxdata\telegraf>make windows
process_begin: CreateProcess(NULL, sh -c "git describe --always --tags", ...) failed.
process_begin: CreateProcess(NULL, sh -c "git rev-parse --abbrev-ref HEAD", ...) failed.
process_begin: CreateProcess(NULL, sh -c "git rev-parse --short HEAD", ...) failed.
go get github.com/sparrc/gdm
.....
after this we got bin folder in workspace in that we got gdm application file but we didn't get telegraf binary file.
thanks.

**Comment by danielnelson** [comment]
Can you include the full output of `make windows`?

**Comment by hemasalma** [comment]
Hello,

Sorry for late reply, as am busy with some other work i couldn't update you...

here is the error we got when we perform make command:

process_begin: CreateProcess(NULL, sh -c "git describe --always --tags", ...) failed.
process_begin: CreateProcess(NULL, sh -c "git rev-parse --abbrev-ref HEAD", ...) failed.
process_begin: CreateProcess(NULL, sh -c "git rev-parse --short HEAD", ...) failed.
go get github.com/sparrc/gdm
gdm restore
======= Go Dependency Manager =======
= working dir: C:\workspace\src\github.com\influxdata\telegraf
= GOPATH:      C:\workspace
=====================================
> Restoring C:\workspace\src\collectd.org to 2ce144541b8903101fb8f1483cc0497a68798122
> Restoring C:\workspace\src\github.com\Shopify\sarama to 574d3147eee384229bf96a5d12c207fe7b5234f3
> Restoring C:\workspace\src\github.com\Sirupsen\logrus to 61e43dc76f7ee59a82bdf3d71033dc12bea4c77d
> Restoring C:\workspace\src\github.com\aerospike\aerospike-client-go to 95e1ad7791bdbca44707fedbb29
be42024900d9c
> Restoring C:\workspace\src\github.com\amir\raidman to c74861fe6a7bb8ede0a010ce4485bdbb4fc4c985
> Restoring C:\workspace\src\github.com\aws\aws-sdk-go to 7524cb911daddd6e5c9195def8e59ae892bef8d9
> Restoring C:\workspace\src\github.com\beorn7\perks to 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9
> Restoring C:\workspace\src\github.com\cenkalti\backoff to b02f2bbce11d7ea6b97f282ef1771b0fe2f65ef3

> Restoring C:\workspace\src\github.com\couchbase\go-couchbase to bfe555a140d53dc1adf390f1a1d4b0fd4c
eadb28
> Restoring C:\workspace\src\github.com\couchbase\gomemcached to 4a25d2f4e1dea9ea7dd76dfd943407abf9b
07d29
> Restoring C:\workspace\src\github.com\couchbase\goutils to 5823a0cbaaa9008406021dc5daf80125ea30bba
6
> Restoring C:\workspace\src\github.com\davecgh\go-spew to 346938d642f2ec3594ed81d874461961cd0faa76
> Restoring C:\workspace\src\github.com\docker\docker to b89aff1afa1f61993ab2ba18fd62d9375a195f5d
> Restoring C:\workspace\src\github.com\eapache\go-resiliency to b86b1ec0dd4209a588dc1285cdd471e7352
5c0b3

new messages
[5:20] 
45be
> Restoring C:\workspace\src\gopkg.in\fatih\pool.v2 to 6e328e67893eb46323ad06f0e92cb9536babbabc
> Restoring C:\workspace\src\gopkg.in\mgo.v2 to 3f83fa5005286a7fe593b055f0d7771a7dce4655
> Restoring C:\workspace\src\gopkg.in\olivere\elastic.v5 to ee3ebceab960cf68ab9a89ee6d78c031ef5b4a4e

> Restoring C:\workspace\src\gopkg.in\yaml.v2 to 4c78c975fe7c825c6d1466c42be594d1d6f3aba6

ERROR restoring some imports:
-   Error checking out default branch (usually master) in repo C:\workspace\src\github.com\aws\aws-s
dk-go, exit status 128
-   Error checking out default branch (usually master) in repo C:\workspace\src\github.com\docker\do
cker, exit status 128
-   Error checking out default branch (usually master) in repo C:\workspace\src\github.com\hashicorp
\consul, exit status 128
-   Error checking out default branch (usually master) in repo C:\workspace\src\github.com\miekg\dns
, exit status 128
make: *** [prepare] Error 1

Thanks,
Hemasalma

**Comment by danielnelson** [comment]
You need to figure out why `gdm restore` has failed.  Try to install into a clean `GOPATH`. It also might help if you try to get one of the dependencies manually with `go get -v github.com/docker/docker`.
