### ISSUE TITLE
Add deployments and pod count fields to the Kubernetes input plugin

### ISSUE THREAD

**Issue by devth** [influxdata/telegraf#2715]
### Proposal:

The [Kubernetes input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kubernetes) should add more data about deployments and pod counts. Kubernetes deployments contain useful data about the number of desired, current, up-to-date, and available pods. Being able to graph these and alert on them would be tremendously useful.

### Current behavior:

Telegraf doesn't know about deployments or pod counts.

### Desired behavior:

Telegraf knows about deployments and pod counts and can graph and alert based off them.

### Use case:

- Graph desired vs curent vs up-to-date vs available pods for a given deployment over time.
- Alert when available < desired for more than 5 minutes
- Alert when available == 0 for any amount of time
- Alert when up-to-date < desired for more than 10 minutes

**Comment by jackzampolin** [comment]
I'll look into this. @devth Can you currently get this information from `prometheus`? If so I would suggest checking out the [`prometheus` telegraf plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus). It would also be nice to get counts for stuff like `configmaps` and `secrets` counted by `namespace`. Preserving tags from Kubernetes would be the ideal case.

**Comment by jackzampolin** [comment]
@devth I think this addon has what we are looking for. Pointing the telegraf prometheus collector at it would get you those metrics: https://github.com/kubernetes/kube-state-metrics

**Comment by devth** [comment]
I'm not running Prometheus currently but in the past I've been able to get pod count metrics with it. I'll try `kube-state-metrics` and the Telegraf prom collector and report back. Thanks!

**Comment by devth** [comment]
`kube-state-metrics` + Telegraf prom collector works!

**Comment by danielnelson** [comment]
@jackzampolin Even though we have found a solution, do you think this functionality should be part of the k8s plugin?

**Comment by jackzampolin** [comment]
@danielnelson I think we can scrub it.
