### ISSUE TITLE
Increase Output Frequency - CloudWatch

### ISSUE THREAD

**Issue by LewisLebentz** [influxdata/telegraf#2720]
## CloudWatch Output
When using CloudWatch as an output, graphs are a lot less accurate than when using other sources. Not sure if this is a limitation AWS' side, or if there's a way to increase the frequency it checks in to CloudWatch.

## Screenshot
![image](https://cloud.githubusercontent.com/assets/5428939/25429089/c0e7fcc8-2a6f-11e7-8c84-f35e850b1b0b.png)

In the screenshot above, you can see that the InfluxDB graph is much better than the CloudWatch one below, graphing the same stat.

Is there anything I can do about this?

**Comment by danielnelson** [comment]
I don't think it is possible.  The stats in your screenshot are in 1 minute resolution, which is the maximum Cloudwatch supports.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html
> Although you can publish data points with time stamps as granular as one-thousandth of a second, CloudWatch aggregates the data to a minimum granularity of one minute.
