### ISSUE TITLE
exec input documentation needs modernization

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2731]
## Bug report

The documentation for the exec should be updated:
- use the latest example template
- remove incorrect information about JSON format
- provide information about exit codes
- add hint about permissions #2718 
- signals?

### System info:

c66e2896c658cc2d3ccf9fdec3be8072e87162a2

**Comment by mjesse88** [comment]
Hi danielnelson,

About remove incorrect information about JSON format:
It whether that when the script output empty json?

In version V1.3.0,
sometime I don't need metrics write to influxdb, so my script output empty json,

the telegraf  write error to log file,see below my test script:
1. test.bat
@echo off
exit  /b 0 
E! Error in plugin [inputs.exec]: unable to parse out as JSON, unexpected end of JSON input

2.test.bat
@echo off
echo ""
exit /b 0
E! Error in plugin [inputs.exec]: unable to parse out as JSON, json: cannot unmarshal string into Go value of type map[string]interface {}

BTW
I Know the data format is influx. the warning or error is removed by devoloper.

thanks 
Jesse

**Comment by danielnelson** [comment]
@mjesse88 I opened #2887 for this.

**Comment by danielnelson** [comment]
Closed in ab8376de0395becfe7cd4029326d2d7731fb9de1
