### ISSUE TITLE
How to monitor docker service ?

### ISSUE THREAD

**Issue by kotarusv** [influxdata/telegraf#2735]
How to monitor these 2 things from docker plugin without writing a custom exec script?

1. Report if docker service is down 
2. Report if docker service is running of unhealthy due to various conditions 

I really don't want to write a script to check health of service by checking systemctl status docker or docker info commands

**Comment by danielnelson** [comment]
If you are running the docker input and docker is down, no points will be produced.  This would indicate the service is not running/healthy.

> running of unhealthy due to various conditions

Can you expand on this, what sort of conditions would you like to detect?

**Comment by kotarusv** [comment]
so you mean set up an alert and fire if no data received last few samples? and i can use any measurement/field to check data is not coming up ?

docker might be down for various reasons
- docker storage has issue
- docker network has issues
- docker socket is deleted 
- docker socket become folder instead of file
- docker socket permissions changed 

the reason my initial question was, I'm using grafana as my alert engine. I want to fire an alert in case docker service is down both hard down ( service stopped) or soft down ( service is up but technically down)

**Comment by danielnelson** [comment]
I know you can alert using Kapacitor on missing samples, but I've never tried Grafana alerts.

I'm sure you have looked at the docker input?  It should help with some of these items.  It would also be possible to use procstat to watch the docker service and file to watch the socket if you are so inclined.

**Comment by kotarusv** [comment]
Yes we are using telegraf, docker input plug-in as well as Influxdb. let me put an alert condition if data missing from docker input plugin.

**Comment by danielnelson** [comment]
If you need more help please ask over at the [InfluxData Community](https://community.influxdata.com) site.
