### ISSUE TITLE
Internal input should indicate when plugins do not complete within interval

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2736]
### Proposal:
Sometimes a plugin does not finish within the collection interval:
```
2017-04-28T18:56:52Z E! Error in plugin [inputs.httpjson]: took longer to collect than collection interval (1s)
```
When this happens the `internal` plugin should emit something.  I considered a new field `gather_timeout_ns` set to the length of interval but since no timeout actually occurs I think we just need to drop the `gather_time_ns` field.  Additionally I think we should add a field containing the interval length.

### Current behavior:

```
internal_gather,input=httpjson gather_time_ns=0i,metrics_gathered=0i 1493406535000000000
internal_gather,input=httpjson gather_time_ns=2008578934i,metrics_gathered=1i 1493406536000000000
```

### Desired behavior:

```
internal_gather,input=httpjson interval_time_ns=1000000000i,metrics_gathered=0i 1493406535000000000
internal_gather,input=httpjson interval_time_ns=1000000000i,gather_time_ns=2008578934i,metrics_gathered=1i 1493406536000000000
```

### Use case: [Why is this important (helps with prioritizing requests)]

Allows simpler and more direct monitoring of slow plugins.

**Comment by ssoroka** [comment]
seems like a lot of extra data that mostly won't change. I don't think it helps things much. going to close this as not required.
