### ISSUE TITLE
Windows Event log

### ISSUE THREAD

**Issue by iserialize** [influxdata/telegraf#2747]
I need to pull windows event logs so that reports like how many times a certain event took place can be reported on or if a certain event occurs, i can trigger off a notification. Have tried using the exec plugin to call a powershell script e.g Get-EventLog -LogName Application -Newest 10 | ConvertTo-Json -depth 3 but not all data gets written.

Please advise.

Thanks

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.  Make sure to include your the config for your exec plugin as well as the powershell script if possible.
