### ISSUE TITLE
SNMP NestedErrors are discarded in Table.Build

### ISSUE THREAD

**Issue by expbbc** [influxdata/telegraf#2752]
## Bug report

When building an SNMP Table (using `snmp.go Table.Build`) errors produced which match the `NestedError` type are errantly discarded.

### System info:

Linux Ubuntu Xenial, telegraf master (specifically `5c88965084176c95dd58f6bbbdac32a55feffb5d`)

### Steps to reproduce:

1. Build an SNMP table with a format conversion error. In this case the SQUID MIB specifies `cachePeerAddress` as type `InetAddress` yet the actual OID returned is 0x04, an `Octet String`
2. The function `fieldConvert` will produce an error: `converting "X.X.X.X" (OID .1.3.6.1.4.1.3495.1.5.2.2.2.X.X.X.X) for field cacheClientAddress: invalid length...` (IP address omitted)

### Expected behavior:

An error or warning should be produced, indicating this field has been omitted from the output

### Actual behavior:

The error is silently discarded internally and the field is omitted from the output without justification

### Additional info:

Errant code is specifically a missing branch in this conditional: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/snmp.go#L465 .. The error is indeed a NestedError, and so once the if condition exists, the err falls out of scope and is discarded.

**Comment by phemmer** [comment]
This is indeed a bug. Originally the only way [`gs.Walk()`](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/snmp.go#L443) would return a `NestedError` was from [line 445](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/snmp.go#L445), and was used as cheap way to break the loop.
I think the simplest way to fix this would be instead return a dedicated "EOF" type error.

**Comment by expbbc** [comment]
Thank you for the confirmation @phemmer

**Comment by Hipska** [comment]
Hi @expbbc @phemmer, does this still happen in latest versions of telegraf? I don't think so, but would like to have confirmation.

**Comment by MyaLongmire** [comment]
I am going to close this as `snmptraslate` is deprecated in telegraf and supported versions no longer use it due to performance issues and there has not been a response in a few years. If you are having issues with the recent `snmp` update, please open another ticket with all relevant information.
