### ISSUE TITLE
logparser support JSON log files

### ISSUE THREAD

**Issue by jumptrading-linux** [influxdata/telegraf#2755]
We are trying to solve a very specific problem, but I think this could be useful for others.

Some log files (for "reasons") do not have timestamps. The standard way to parse them is to just take the timestamp that you read them. From reading the docs, I dont think this is currently an option.

If we submitted code to support this (as a special time format, like the ones already hard coded, I suspect) would that work?

**Comment by danielnelson** [comment]
If you don't parse any fields using a timestamp modifier then it will use the parse time, is this what you need?

**Comment by alexdaviesjump** [comment]
Our files literally dont have timestamps, example file:

```
[root@host bin]# cat foo.txt
foo
foo2
foo3
```

If I configure thus, it just does nothing:

```
[root@host bin]# cat telegraf.conf
[[inputs.logparser]]
  ## files to tail.
  files = ["/root/telegraf/usr/bin/foo2.txt"]

  ## Read file from beginning.
  from_beginning = true

  ## Override the default measurement name, which would be "logparser_grok"
  name_override = "foo"

  ## For parsing logstash-style "grok" patterns:
  [inputs.logparser.grok]
    patterns = ["%{COMBINED_LOG_FORMAT}"]

[[outputs.file]]
  files = ["stdout"]

```

We have solved this problem in another way, but if it is possible to make this plugin work with files without timestamps (which would involve injecting the parse-time per line) it would be good to add how to configure it.

**Comment by danielnelson** [comment]
You must have at least one field, for example if pattern were `"%{WORD:value}"` then it should produce:
```
foo value="foo" <time-line-is-parsed>
foo value="foo2" <time-line-is-parsed>
foo value="foo3" <time-line-is-parsed>
```

[The timestamp is mentioned in the documentation](https://github.com/influxdata/telegraf/blame/master/plugins/inputs/logparser/README.md#L60).  Maybe we should add a sentence about needing at least one field?

**Comment by ushuz** [comment]
How's this issue related to "JSON log file"?

**Comment by danielnelson** [comment]
Title is probably related to 2756.  I updated the docs to mention the at least one field requirement 377547aa4cb0f0d64db42e52e5ca6e3d9a09fc4e
