### ISSUE TITLE
Apache TotalAccesses spikes in negative

### ISSUE THREAD

**Issue by Ulrar** [influxdata/telegraf#2757]
Hi,

We have a server that keeps stopping to answer requests, according to the apache logs it reaches it's MaxRequestWorkers. I bumped it by a huge factor, still the same so I installed telegraf on it to use with grafana.

Connections in the apache graphs are staying under 30 all the time, except at the time of the crash where it spikes like crazy : 
![apache](https://cloud.githubusercontent.com/assets/873423/25652369/c0ac2a52-2fdf-11e7-9216-68d92f0623be.jpg)

Any idea why it spikes in the negative ? Isn't that very weird ? In "normal" times the connections are on the positive side. I'm hoping that'll help me find out what the actual problem is

**Comment by danielnelson** [comment]
Can you show the query as InfluxQL?

**Comment by Ulrar** [comment]
Sure, here it is :

```
SELECT derivative(mean("TotalAccesses"), 1s) FROM "apache" WHERE $timeFilter GROUP BY time($interval) fill(null)
```

**Comment by danielnelson** [comment]
I think you could use non_negative_derivative here.  Since the service went down the rate of change did as well.

**Comment by danielnelson** [comment]
Please reopen if you need more help.
