### ISSUE TITLE
[Feature] allow monitoring influxdb without tls-certificate-check

### ISSUE THREAD

**Issue by Finkregh** [influxdata/telegraf#2758]
### Proposal:
allow disabling TLS-certificate checking when monitoring influxdb

### Current behavior:
1. configure influxdb with TLS
2. configure telegraf to monitor influxdb via a URI (`https://localhost/...`) that does not fit the TLS-certificate
3. `ERROR in input [inputs.influxdb]: [url=https://localhost:8086/debug/vars]: Get https://localhost:8086/debug/vars: x509: certificate is valid for something.example, not localhost`

### Desired behavior:

Telegraf optinoally does not do a cert-check and monitoring works

### Use case:
locally monitoring influxdb which is configured with a "proper" certificate for external access

**Comment by danielnelson** [comment]
I think you just need to set `insecure_skip_verify = true` in the influxdb plugin, can you verify?

**Comment by danielnelson** [comment]
Please reopen if this option does not solve your issue.
