### ISSUE TITLE
Telegraf unable to create log file

### ISSUE THREAD

**Issue by Alessar** [influxdata/telegraf#2760]
### Steps to reproduce:
Download telegraf. Unzip to folder. Run ```./telegraf.exe --config ./telegraf.conf --test```
### Actual behavior:
Error happend:  
```E! Unable to create /Program Files/Telegraf/telegraf.log (open /Program Files/Telegraf/telegraf.log: The system cannot find the path specified.), using stderr```
### Expected behavior:
No errors about directory 'Program files'.  
```telegraf.log``` file should be created in current directory in which telegraf.exe is situated.
### System info:
Telegraf v1.2.1, Windows 10

**Comment by danielnelson** [comment]
Does this directory exist?  I wonder if it is a permission problem.

IMO the default logfile should be placed somewhere in %APPDATA%.

**Comment by Alessar** [comment]
Directory `Program files/telegraf` does not exist. So If telegraf program is portable, I assume that I can run it in any directory. So IMHO logfile should be created OR in current directory OR in directory where telegraf.exe is situated.  
So `logfile = "./telegraf.log"` will be good, I assume.

**Comment by danielnelson** [comment]
These directories might not be writeable, which is why I would favor `%APPDATA%` or the likes.

**Comment by russorat** [comment]
@Alessar in my opinion, it's reasonable to expect telegraf to create the log file where you specify in the config (assuming the permissions are correct), but it is not reasonable to expect telegraf (or any app really) to create the directory for the log file if it doesn't exist.

I'll leave this open to facilitate discussion but at this point, it won't be prioritized.

**Comment by Alessar** [comment]
@russorat maybe I can agree with that any application should not create folder if it is not exist. But issue was that default place for log file is unexpected.
So I see two cases:
If log file was specified - `telegraf` try to create log file in that place and thats all.
If log file was not specified - it should be expected logical behavior. So `telegraf` can be setuped into some specific folder like "Program files" or can be runned in any unexpected places. In that case I will expect of next sequence of steps to recognize place to log file:
- `Telegraf` try to create log file in the folder where `telegraf.exe` is situated.
- (If previous step is unavailable due to some reason like small permissions or folder is situated on non-writable file system or some other reasons) `Telegraf` try to create log file in the current directory (If it is nor equal with the directory where `telegraf.exe` situated).
- (If previous step is unavailable due to some reason) `Telegraf` try to create log file in some specific place. (It cannot be "Program files" due to `Telegraf` is portable program. It can be `%APPDATA%` as somebody want or home `~` directory maybe only on unix or even `%TEMP%` folder. Maybe this directory should be elected in another discussion).
- (If previous step is unavailable) `Telegraf` send logs into console or stderr or should be stoped at all. (Maybe this behavior should be elected in another discussion too).
It is only IMHO. Discussion and other opinions are very welcome.

**Comment by powersj** [comment]
Hi,

Going through old bugs. The original issue here is as Daniel said, that Telegraf did not have access to the directory. The default Telegraf config on Windows has an empty logfile, which means logs are written to stderr. If a user is going to update this and set it to a specific directory, it needs to exist.

I am going to close this as I believe Telegraf is working as expected, and the behavior does not need changes.

**Comment by Alessar** [comment]
@powersj 
The issue is not related to the directory that does not exist.
The issue is related to an unexpected directory.
And the current behaviour can be changed to be more expected behaviour.
