### ISSUE TITLE
telegraf don't gave build.go file

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#2761]
Hello,

we have installed telegraf through source code from github we configured some code based on our requirement.

Requirement:
we need to make that source code telegraf as rpm, for that we need build.go file 
we don't file that file in telegraf source code
so can i know where can i find build.go file?

Thanks,
Hemasalma

**Comment by danielnelson** [comment]
We are using the `scripts/build.py` script to create our packages.  Check https://github.com/influxdata/telegraf/blob/master/scripts/circle-test.sh#L79 for how we start it.

**Comment by hemasalma** [comment]
Hello,

Can you provide us some brief steps to build a telegraf package?

Thanks,
Hemasalma

**Comment by danielnelson** [comment]
It is all in the script I linked to.  You need rpmbuild and fpm installed, then run `./scripts/build.py --release --package --platform=linux --arch=amd64`  After it completes the packages are in the `./build` directory.

**Comment by hemasalma** [comment]
Hello,

I executed the above command after installing fpm,rpmbuild. But, am getting the below error.

ERROR:
[root@pdc-prd-dbware019 scripts]# ./build.py --release --package --platform=linux --arch=amd64
[INFO] print_banner: 
 _____     _                       __
/__   \___| | ___  __ _ _ __ __ _ / _|
  / /\/ _ \ |/ _ \/ _` | '__/ _` | |_
 / / |  __/ |  __/ (_| | | | (_| |  _|
 \/   \___|_|\___|\__, |_|  \__,_|_|
                  |___/
 Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] go_get: Retrieving dependencies with `gdm`...
[ERROR] run: Command '/root/tele/src/bin/gdm restore -v -f Godeps_windows' failed with error: [Errno 2] No such file or directory

**Comment by danielnelson** [comment]
Try running the script from the repo root directory: `./scripts/build.py` instead of `./build.py`

**Comment by hemasalma** [comment]
yeah we got rpm,deb and tar.gz packages thanku..

**Comment by hemasalma** [comment]
Hello,

Can you also provide us some brief steps to build a telegraf package in windows?

Thanks,
Hemasalma

**Comment by danielnelson** [comment]
We cross compile it from linux, all you need to do is change platform to `windows`.

**Comment by hemasalma** [comment]
Hello,

we have changed the platform and executed the command, we successfully got zip file for windows installation.

but, that config file don't have the code modifications we done for linux config file i.e., having some extra features added based on our requirement to the source code.

even it didn't work properly when we installed in our windows machine i.e., telegraf is not running
