### ISSUE TITLE
telegarf data to elasticsearch when installed with rpm

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#2763]
Hello,

We have installed telegraf-1.2.1 rpm file. we need to send telegraf data to influxdb and elasticsearch at a time, but when i tried to do that elasticsearch ouput plugin throws some error.

Code added in telegraf file:
[[outputs.elasticsearch]]
  urls = [ "http://xxx.xxx.x.xx:9200" ] # required
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"
  username = "abc"
  password = "abc"
  index_name = "telegraf-17.04.26" # required.
  manage_template = true
  template_name = "telegraf"
  overwrite_template = false

Error:
E! Error parsing /etc/telegraf/telegraf.conf, Undefined but requested output: elasticsearch

as a result telegraf is not running

so can i know how to configure elasticsearch in order to send data to it.

Thanks,
HemaSalma

**Comment by lpic10** [comment]
Elasticsearch output is not available in the 1.2.1 release, it will be part of the 1.3 release. There is a RC available if you want to give a try.

**Comment by danielnelson** [comment]
Here is a link to the latest release candidate: https://community.influxdata.com/t/telegraf-1-3-0-rc2/799

**Comment by hemasalma** [comment]
Hello,

can i know do we have elasticsearch output supported for windows?

**Comment by danielnelson** [comment]
Yes, it is supported on Windows.

**Comment by hemasalma** [comment]
Hello,

we installed 1.3 zip file(from the link sent by you) on our windows  machine, in this also elasticsearch plugin is not supported.

we don't have default elasticsearch output plugin in conf file of windows

we added externally the code to file then the telegraf stopped working.

**Comment by danielnelson** [comment]
Can you include the configuration you added, and provide more details about what you mean by "telegraf stopped working"?

**Comment by hemasalma** [comment]
Hello,

this is the default file i got when i installed 1.3 telegraf on windows
[default Telegraf configuration file.docx](https://github.com/influxdata/telegraf/files/995734/default.Telegraf.configuration.file.docx)

i have added the below code in outputs block of conf file

[[outputs.elasticsearch]]
   urls = [ "http://xxx.xxx.xx.xx:9200" ] # required.
   timeout = "5s"
   enable_sniffer = false
   health_check_interval = "10s"
    username = "elastic"
    password = "access"
   index_name = "metrics-%Y.%m.%d" # required.
   manage_template = true
   template_name = "telegraf"
   overwrite_template = false

then  we started telegraf execution. but the telegraf didn't create any log file or didn't give any outputs.

**Comment by danielnelson** [comment]
How are you starting telegraf?  If you are running it in a terminal please add the command and output.

**Comment by danielnelson** [comment]
If you still need addition help please ask a question on the [InfluxData Community](https://community.influxdata.com) site.
