### ISSUE TITLE
[Feature Request] Add support s390x

### ISSUE THREAD

**Issue by photosojourn** [influxdata/telegraf#2766]
### Feature Request

__Proposal:__ 

Update the build.py script to support to support s390x architecture. Currently running Go Build and Go Install from the pkg root results in a working and valid telegraf binary.

__Current behavior:__ 

The build.py script does not support a value of s390x for the flag --arch while cross complication of C and Go to s390x is supported by the tooling.

__Desired behavior:__ 

Passing --arch s390x results in a s390 Go binary being produced. 

__Use case:__ 

Mainframes are still about and still running critical workloads on Linux so  it would be great to able to use Telegraf in the same manner as our x86_64 estate.

**Comment by danielnelson** [comment]
I'll add support to our build scripts.  Have you tested a build on s390x to see if it works?

**Comment by photosojourn** [comment]
We briefly tested version a while back (0.13.0 maybe) and all the basics e.g cpu memory etc worked. I can complete further testing when I'm back in Monday on 1.2.0, but the scope will be limited as we don't use most of the tech supported so will focus on CPU, memory, system, disk and network. 

That said Linux OS (RHEL, SLES and Ubuntu) on s390x are identical to there x86_64 excluding  underlying low level stuff (network devices for example) so if the Go code is using standard OS interfaces and libraries (Glibc et. el.) then there shouldn't be any reason for it all not to work.

So the question I guess becomes this; how much testing is enough?

**Comment by danielnelson** [comment]
If it builds that is enough for me to enable builds for it.  Support will have to be on best effort only though since I don't have any hardware available.  Hypothetically if it got in the way of other functionality we might have to pull it though.

**Comment by danielnelson** [comment]
The next nightly build should create these additional s390x builds (they will not exist for at least 12 more hours):

https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_s390x.deb
https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.s390x.rpm
https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_s390x.tar.gz

**Comment by photosojourn** [comment]
Ace I will grab and test them Monday and will raise an issue if I hit any issues. Re support I'm happy with the best endeavours approach given the hardware barrier.
