### ISSUE TITLE
Ubuntu telegraf.conf use enviornment variables

### ISSUE THREAD

**Issue by santhoshjoy** [influxdata/telegraf#2767]
This is same ticket https://github.com/influxdata/telegraf/issues/1800 which the solution is not provided. I explained further below,

I am running telegraf as a service and when I tried the command sudo -u telegraf printenv . It doesn't print the environment variables what I export.

But in the Configuration comments It says the one below,

Environment variables can be used anywhere in this config file, simply prepend
them with $. For strings the variable must be within quotes (ie, "$STR_VAR"),
for numbers and booleans they should be plain (ie, $INT_VAR, $BOOL_VAR)

Global tags can be specified here in key="value" format.
[global_tags]
dc = "us-east-1" # will tag all metrics with dc=us-east-1
rack = "1a"
Environment variables can be used as tags, and throughout the config file
user = "$USER"

**Comment by danielnelson** [comment]
The solution was adding the environment variables to `/etc/default/telegraf`.  This technique only works when using the initscripts or systemd.
