### ISSUE TITLE
httpjson & exec plugins should give special meaning to keys: "name" and "tags"

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#277]
The JSON parsing of the exec and httpjson plugins should accept some keys as instructions for naming/tagging.

For example, the following JSON

```
{
    tags: {
        path: "/Users/csparr"
    },
    hh:/Users/csparr/.influxdb/hh: {
        name: "hh",
        tags: {
            path: "/Users/csparr/.influxdb/hh"
        },
        values: {
            process_req: 168826
        }
},
    memstats: {
        Alloc: 3327960,
    }
}
```

currently would be parsed like this:

```
> httpjson_hh:/Users/csparr/.influxdb/hh_values_process_req  value=168826
> httpjson_memstats_Alloc  value=3327960
```

Instead, "name" should override the parent key name, and tags should add tags. Tags at lower levels in the tree should override top-level tags. So the above would look like this instead:

```
> httpjson_hh_values_process_req,path='/Users/csparr/.influxdb/hh'  value=168826
> httpjson_memstats_Alloc,path='/Users/csparr'  value=3327960
```

There could also be a confiurable blacklist of names to omit from the final measurement name. This way you could do `blacklist = ["values"]` and get:

```
> httpjson_hh_process_req,path='/Users/csparr/.influxdb/hh'  value=168826
```

Some other requirements:

1. This should be configurable with options: `parse_tags = true` and `parse_name = true`
2. A way to specify fields? I'm not sure if this is feasible.
3. There should be a `libraries` directory in the `plugins` directory for this code to live, that way the JSON parsing of `exec` and `httpjson` does not diverge.

**Comment by sparrc** [comment]
cc @otoolep @palkan @jpalay @alvaromorales

**Comment by otoolep** [comment]
Yeah, stuff like this would be handy.

**Comment by palkan** [comment]
## About tags and names

It looks a little bit complicated to me.

This features require command/service providers to _know_ that telegraph is using it. Smells like _high coupling_. 
Another argument: legacy systems.
I think that telegraph shouldn't add any new constraints to _systems_ being monitored.

For example, for tags I like the idea of providing _tag keys_ parameter (where to look for keys?), which I've already proposed [here](https://github.com/influxdb/telegraf/pull/275).

## Libraries

+1.
Maybe _codecs_ would be a better naming.

**Comment by sparrc** [comment]
@palkan The libraries folder would be for a general use-case, code for all plugins

re: high coupling. This is true, but there actually has been a request _for_ this feature, so that users can develop "telegraf-aware" JSON output. See https://github.com/influxdb/telegraf/issues/190

**Comment by abh** [comment]
The coupling seems pretty reasonable me. Without it, how do you use the tagging feature?

I don't know about the exact format without having tried developing for it, but if the experts says this would be good then it sounds good to me (as the requestor of #190).

**Comment by palkan** [comment]
@abh The idea of extracting tags from existing data (without modifying it) is explained (and implemented)  in #275.

@sparrc 
What about having  two possibilities: `parse_tags=true` (_telegraph-aware_) and `extract_tags=true` (#275)? This would make telegraph more flexible.

**Comment by otoolep** [comment]
I don't think telegraf should assume the names of the keys. Is should instead be told what the name is of the field to interpret as "name", same for tags (if any) and values. It just happens that "name" (the field) is the "name" in the InfluxDB measurement sense above.

**Comment by otoolep** [comment]
This would be done via config changes, just like the Graphite service on InfluxDB is configured for parsing.

**Comment by sparrc** [comment]
@palkan there's no reason we can't just do both, I don't see a good reason for having a option to deal with #275, you can just not use the feature by not specifying anything in the tag_keys list.

**Comment by samahee** [comment]
# ./telegraf -config telegraf.conf -test
2015/10/22 02:50:45 line 121: field corresponding to `tagdrop' is not defined in `*httpjson.Service'

# ./telegraf -config telegraf.conf
2015/10/22 02:35:19 line 130: field corresponding to `drop' is not defined in `*httpjson.Service'

can't use plugin options..

**Comment by sparrc** [comment]
@samahee irrelevant to this case, open a new one

**Comment by imcphillips** [comment]
So am I understanding the docs and this thread correctly, that there's currently no way to include tags with metrics gathered with this plugin? I see it was added to httpjson, but I'm not seeing a corresponding change in exec.

**Comment by sparrc** [comment]
@imcphillips That is correct, these two plugins really should be using the same common code, PRs accepted ;-)

**Comment by sparrc** [comment]
wont implement, now that we have an influxdb plugin, and tag keys for httpjson
