### ISSUE TITLE
Ceph Telegraf plugin not fill empty values

### ISSUE THREAD

**Issue by OrFriedmann** [influxdata/telegraf#2772]
Since InfluxDB don't support empty values and fill function not working when there is empty values in the query.
For Example: I want to use Kapacitor to monitor when some pgs are not in "active+clean" state so I want to use ceph_pgmap
When the pg state changing to "active+undersized+degraded" and all pgs not in "active+clean" the value is empty.
I think that we should fill those values to 0 and write it to the db.
Another example is that not all pg states appear at the beginning and the states showed up only when the state is happens.
I think that we should start fill with 0 values when we can(In most cases we can)

Thank You

**Comment by danielnelson** [comment]
This isn't something we want to do since, among other reasons, 0 is not equivalent to unset and many setups depend on this.  This is something Kapacitor can handle though, can you post a question and include your TICK script over on the [InfluxData Community](https://community.influxdata.com) site?
