### ISSUE TITLE
Add AWS Kinesis Consumer

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/telegraf#2775]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Telegraf currently has producer and consumer plugins for a number of different queueing solutions. Kinesis, a widely used event bus, is not currently supported.

### Use case:

Lots of sensor monitoring and other use cases utilize Kinesis for metrics shipping. Native hooks into that from telegraf would make it much easier to use with the InfluxDB ecosystem.

[Golang Bindings](https://docs.aws.amazon.com/sdk-for-go/api/service/kinesis/)

**Comment by danielnelson** [comment]
We have a producer output https://github.com/influxdata/telegraf/tree/master/plugins/outputs/kinesis
