### ISSUE TITLE
[feature-request] Google PubSub Producer/Consumer

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/telegraf#2776]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Telegraf currently has producer and consumer plugins for a number of different queueing solutions. Google PubSub, a widely used event bus, is not currently supported.

### Use case: 

Lots of sensor monitoring and other use cases utilize Google PubSub for metrics shipping. Native hooks into that from telegraf would make it much easier to use with the InfluxDB ecosystem.

[Golang Bindings](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/pubsub)

**Comment by gunnaraasen** [comment]
@danielnelson I think this can be closed now that both the input and output are merged.
