### ISSUE TITLE
Feature request: Additional ElasticSearch Cluster Health Stats

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2779]
### Proposal:

Due to some issues we're seeing, I was hoping to create some graphs for the number_of_pending_tasks and task_max_waiting_in_queue_millis metrics from the /_cluster/health endpoint, but I don't see these in Telegraf.

### Current behavior:

These, and at least one other metric, do not exist.

### Desired behavior:

Telegraf should report all values that are reported by the /_cluster/health endpoint in ElasticSearch.

### Use case: [Why is this important (helps with prioritizing requests)]

This can be used to help diagnose issues with the cluster as well as show trends over time.  Compared with other metrics that are being collected, we can attempt to, for example, narrow down the cause of the pending tasks by comparing to system load.

**Comment by danielnelson** [comment]
We should fix #2711 first.

**Comment by dupondje** [comment]
This is merged. Issue can be closed!

**Comment by danielnelson** [comment]
But I was having so much fun bumping the milestone!

Closed in #4167
