### ISSUE TITLE
Add Solr plugin

### ISSUE THREAD

**Issue by jrxFive** [influxdata/telegraf#278]
Seeing if anyone has the need or creating a solr plugin? I have it somewhat completed but have not figured out a good way to collect data from the following endpoint:

`/solr/{CORE_NAME}/admin/mbeans?stats=true&wt=json`

**Comment by sparrc** [comment]
why not just use the httpjson plugin? https://github.com/influxdb/telegraf/tree/master/plugins/httpjson

**Comment by jrxFive** [comment]
I wouldn't know the `coreName` value beforehand unless I used some type of config management/service discovery/scripting tool to generate a template that for the httpjson plugin request.

**Comment by sparrc** [comment]
So the plugin would need to discover `CORE_NAME`?

**Comment by jrxFive** [comment]
Yea it would use a different endpoint to extract all the cores ( plus some general information ), and then iterate over each `CORE_NAME` to get the mbean stats. At least I think thats how it would work, I have not seen a more dump worthy endpoint to get all the information at once.

`/solr/admin/cores?action=STATUS&wt=json`
