### ISSUE TITLE
Docker nfs volumes info

### ISSUE THREAD

**Issue by kotarusv** [influxdata/telegraf#2783]
Hi 

Is it possible to get NFS volumes mounted inside the docker container or POD? I'm interested about How much storage being used and what is the total capacity of the PV/NFS volume. This is very obvious in Kubernetes/Openshift based deployments or in general docker also. 

Srinivas Kotaru

**Comment by danielnelson** [comment]
We don't have anything NFS specific but look at the disk and diskio plugins.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
