### ISSUE TITLE
Add password option to redis plugin

### ISSUE THREAD

**Issue by x1e** [influxdata/telegraf#2786]
### Relevant telegraf.conf:
[[inputs.redis]]
    servers = ["tcp://123456$%^@localhost:6379"]
### System info:
debian 8.8
Telegraf  1.2.1

### Steps to reproduce:

telegraf -config /etc/telegraf/telegraf.conf -input-filter redis -test

### Expected behavior:
Can generate right redis info 

### Actual behavior:
* Plugin: inputs.redis, Collection 1
Unable to parse to address 'tcp://123456$%^@localhost:6379': parse tcp://123456$%^@localhost:6379: invalid URL escape "%^"

### Current behavior:
only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used for their reserved purposes may be used unencoded within a URL

### Desired behavior:
allow other character in password

### Use case: [Why is this important (helps with prioritizing requests)]
all password has this problem

**Comment by danielnelson** [comment]
Have you tried applying url escaping?  I believe it would be `tcp://123456$%25^@localhost:6379`.

We should change the input to have a password option instead of requiring it to be added to a url.

**Comment by JustTheSame** [comment]
how can i solve the problem?

**Comment by danielnelson** [comment]
I think we should rework this plugin to use gopkg.in/redis.v4

**Comment by h4ckroot** [comment]
I have the same issue, the plugin never works with any password !. Please help.

**Comment by danielnelson** [comment]
@h4ckroot Does it work with a weak password containing no symbols?

**Comment by h4ckroot** [comment]
Unfortunately, no !. I used the password: kool1, but that did not work !.

**Comment by glinton** [comment]
I wonder if the reason the non-special character password didn't work is because a bad url format, there should be a leading `:` that separates the empty username with the defined password. `tcp://:kool1@localhost:6379` 4669 resolves this in any case.
