### ISSUE TITLE
Customizing the interval of multiple scripts inside inputs.exec

### ISSUE THREAD

**Issue by mjesse88** [influxdata/telegraf#2789]
Hi,
if plugin exec run multiple scripts,
eg:
script 1: every 20 seconds,
script 2: every 5 minutes.

I can't configure it and can't find how to configure.
interval= 20s
It will all script run every 20 seconds.

What did I miss?

Thanks
Jesse

**Comment by goller** [comment]
Hey @mjesse88, let's figure it out.

Do you happen to have your config file ?

**Comment by mjesse88** [comment]
I find way how to configure, can use mutltiple [input.exec].
https://github.com/influxdata/telegraf/issues/809
Thanks
