### ISSUE TITLE
Clean up system unit tests

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#279]
`system_test.go` is a mess, and makes it difficult for contributors to add new unit tests. This file should be broken out into a test file for each plugin. ie, `cpu_test.go`, `mem_test.go`, etc.

**Comment by jrxFive** [comment]
would you want and additional tests for each plugin?

**Comment by sparrc** [comment]
additional tests are always good, where applicable

**Comment by sparrc** [comment]
this was done in 0.10.0
