### ISSUE TITLE
[bug] Elasticsearch, empty node_name tag

### ISSUE THREAD

**Issue by bluebob** [influxdata/telegraf#2790]
## Bug report
Elasticsearch plugin

### Relevant telegraf.conf:
[[inputs.elasticsearch]]
servers=["http://localhost:9200"]
http_timeout="5s"
local=false
cluster_health=true
cluster_stats=true

### System info:
telegraf-1.2.1-1.x86_64 on RHEL7

### Steps to reproduce:
Normal use

### Expected behavior:
Assign value to node_name tag or omit empty tag

### Actual behavior:
Output contains "node_name" tag which causes a Telegraf reader of that data to emit the message:
telegraf: error:  metric parsing error, reason: [missing tag value], buffer: [...

### Additional info:
Seems to be widespread with the elasticsearch_clusterstats_XX types, where XX=indices or nodes

Also have tried setting "local=true" but this does not fix the issue.

**Comment by danielnelson** [comment]
This should be fixed in 1.6.
