### ISSUE TITLE
[Feature request] InfluxDB output to report which database it's writing to

### ISSUE THREAD

**Issue by bluebob** [influxdata/telegraf#2792]
### Proposal:
For the "influxdb" output plugin, extend the current output - which reports number of metrics and commit time - to also indicate which database is being written to

### Current behavior:
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 7 metrics in 2.149706ms
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 160 metrics in 10.684382ms
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 5000 metrics in 100.919582ms
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 5000 metrics in 147.229169ms

### Desired behavior:
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 7 metrics in 2.149706ms to "consul"
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 160 metrics in 10.684382ms to "jmx"
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 5000 metrics in 100.919582ms to "applicationdb"
telegraf: 2017-05-12T10:57:40Z D! Output [influxdb] wrote batch of 5000 metrics in 147.229169ms to "osdb"

### Use case: [Why is this important (helps with prioritizing requests)]
When adding a new pipeline it would be very useful to know whether the new pipeline is committing in a timely fashion. Currently the only way to do this is to disable all other pipelines other than the new one. With this new feature, it'd be obvious how much data is being processed by the new pipeline and whether it's running slowly, (e.g. if there are network issues with a particular db host)

**Comment by danielnelson** [comment]
At the point where this log is generated we won't be able to log the database name, but I think the proposal in #1815 would solve your problem.  Essentially you would be able to name a plugin and that would be somehow surfaced in the output.

Would this solve your issue?

**Comment by bluebob** [comment]
Hello Daniel, I didn't spot 1815 in my search, but you're absolutely correct - that'd be an even better way to get that traceability we need here.
I'll close this FR and subscribe to 1815 instead. Many thanks.
