### ISSUE TITLE
Add ability to specify routing_key in amqp output

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#2797]
## Bug report
The routing_key doesn't seem to be making it to the AMQP packet and RabbitMQ doesn't see it.  I cannot load balance messages across queues without it.

### Relevant telegraf.conf:
```
[[outputs.amqp]]
    url = "amqp://xxx:xxx@rabbitmq:5672/"
    exchange = "exch.telegraf"
    routing_tag = "telegraf.1"
    data_format = "influx"
```
### System info:
Version: telegraf-1.2.1-1.x86_64
OS: Red Hat 6.9

### Steps to reproduce:

1. Load up the amqp output and insert a routing_tag
2. Sniff the traffic

### Expected behavior:
Routing tag gets set and RabbitMQ directs it to the correct queue

### Actual behavior:
Here's a tcpdump snippet of the relevant packet.  There's no routing tag.  Wireshark shows this better but here's the raw output.  The tag should be right before the exchange in the packet.

```
Flags [P.], cksum 0x0c87 (incorrect -> 0x5c39), seq 1857298238:1857298268, ack 4228138548, win 15544, options [nop,nop,TS val 3867885127 ecr 4267772162], length 30
	0x0000:  4500 0052 e018 4000 4006 4e4b 0a64 fb3d  E..R..@.@.NK.d.=
	0x0010:  0a64 fc3c a772 1628 6eb4 1f3e fc04 4634  .d.<.r.(n..>..F4
	0x0020:  8018 3cb8 0c87 0000 0101 080a e68b 3e47  ..<...........>G
	0x0030:  fe61 0902 0100 0100 0000 1600 3c00 2800  .a..........<.(.
	0x0040:  000d 6578 6368 2e74 656c 6567 7261 6600  ..exch.telegraf.
	0x0050:  00ce
```

**Comment by danielnelson** [comment]
The `routing_tag` is used to look up a tag on the metric, and only if a tag with this tagkey exists is it added as the routing key.

So if you have:
```
foo,host=howdy value=42 1234567890000000000
```
and the `routing_tag` is `host`, then the routing key will be `howdy`.  Any other value will result in no routing key because there are no other tags.

I think we should add support for manually setting the routing key, because sometimes it is needed to use a routing key that is not a tag.

**Comment by hanej** [comment]
I see.  I think being able to specify a static routing key would be great.  We're laying the config down with Ansible/Puppet so that's not a problem for us.

**Comment by danielnelson** [comment]
Added by @gentstr in #3994
