### ISSUE TITLE
Chrony input improvements

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2798]
### Proposal:

The chrony input should
* provide metrics on all sources, not just the currently active sync source
* `stratum` should not be a tag. A sync source's stratum can change. This should not result in a new series being created. It also prevents being able to query based on stratum (e.g. `select ... where stratum > 5`)
* `leap_status` should not be a tag. The leap status can change, and should not result in a new series being created. Already covered in #2072 though.
* The sync source's host name should be provided, not just its IP address.

**Comment by Gelob** [comment]
It would also be nice to be able to track clients if that option is turned on within chrony.

**Comment by reimda** [comment]
If we don't want to add a setting to opt in, we could make these changes during the next major release. #9478

**Comment by srebhan** [comment]
@phemmer the `stratum` and `leap_status` can be converted to fields using the [converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter). The IP can be converted to hostname using the [reverse_dns processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/reverse_dns).

Would that solve this issue?

**Comment by srebhan** [comment]
@phemmer, @Gelob or @dsvk I'm trying to tackle this issue (after soo long... sorry!) and reworked the plugin to get rid of the `chronyc` dependency and improve the testing capabilities. So far there is no feature enhancement but I need to make sure there is no regression with the change.

Can anyone please verify that the binary in PR #14629 (available as-soon-as CI finished the tests) works as before and produces sensible metrics!?!? Please let me know your findings!
