### ISSUE TITLE
Specify different exchange types for amqp

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#2801]
## Feature Request
Allow different types of exchanges to be used instead of just topic.

### Proposal:
We mainly use the x-consistent-hash exchange type to load balance between queues across a cluster.  It would be great if we could specify the exchange type in the config.

### Current behavior:
Topic is hardcoded in the plugin

### Desired behavior:
Configurable exchange type

### Use case: [Why is this important (helps with prioritizing requests)]
Using an exchange type like x-consistent-hash allows you to spread the messages out across all of the queues in the cluster evenly instead of having them all pinned to a single queue.

**Comment by danielnelson** [comment]
This would be a nice feature to have, the next step would be to design how the configuration would look.  Also, we should probably mirror support to the amqp input.

**Comment by danielnelson** [comment]
@hanej How do you choose the routing key for your x-consistent-hash exchanges?  Do we need the ability to generate random routing keys?

**Comment by hanej** [comment]
When using x-consistent-hash the routing key becomes irrelevant. When the message comes in, it gets load balanced evenly between all of the queues in the exchange.

**Comment by danielnelson** [comment]
I was reading [this](https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange#how-consistent-hashing-routing-works):
> In the case of Consistent Hashing as an exchange type, the hash is calculated from the hash of the routing key of each message received. Thus messages that have the same routing key will have the same hash computed, and thus will be routed to the same queue, assuming no bindings have changed.

Maybe there is some special processing for no key?

**Comment by danielnelson** [comment]
Any chance your exchange is setup to route on a message property like `timestamp`?

https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange#routing-on-a-message-property

**Comment by hanej** [comment]
Oh that’s right. We’re using the time stamp plugin to do that automatically. I suppose you could also use something like the hostname of the server.

**Comment by danielnelson** [comment]
You should be able use the `exchange_type` to create a x-consistent-hash exchange and `exchange_arguments` to setup routing on message properties.
