### ISSUE TITLE
InfluxDB Output: Support gzip payload

### ISSUE THREAD

**Issue by shanielh** [influxdata/telegraf#2802]
### Proposal:

InfluxDB Output via HTTP should Support compressing the payload via GZip as [InfluxDB Supports decompressing it](https://github.com/influxdata/influxdb/pull/2180).

### Current behavior:

There is no way to configure influxdb output to gzip the payload.

### Desired behavior:

There should be a way [to do](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/client/http.go#L80
) it.

### Use case: 

Compressing repeating textual data will do decrease the network usage of both the sender and the receiver drastically :smile:

**Comment by danielnelson** [comment]
Added for 1.4 thanks to @bobmshannon
