### ISSUE TITLE
[inputs.exec]: Errors encountered: 

### ISSUE THREAD

**Issue by khanga6tm** [influxdata/telegraf#2803]
Hi all,

To monitor Oracle database, I follow the guide line in https://bdrouvot.wordpress.com/2016/03/05/graphing-oracle-performance-metrics-with-telegraf-influxdb-and-grafana/

I run the test command: telegraf --config /etc/telegraf/telegraf.conf -test -input-filter exec => the result is ok, but Telegraf run that command with error: _E! ERROR in input [inputs.exec]: Errors encountered: [exec: exit status 1 for command_

Does anyone help me to fix it.

The config is: 
[[inputs.exec]]
  commands = ["/tmp/check_oracle.sh"]
  data_format = "influx"
  interval = "60s"

I could run the command: /tmp/check_oracle.sh under telegraf account (I changed from /bin/false -> /bin/bash)

**Comment by danielnelson** [comment]
What happens if you run
```
sudo -u telegraf /tmp/check_oracle.sh
echo $?
```

**Comment by khanga6tm** [comment]
Hi Daniel,

Thanks for your support! 

Command: sudo -u telegraf /tmp/check_oracle.sh => results is ok, it return the metrics with no error.

**Comment by danielnelson** [comment]
You will probably need to add echo statements that write to a file into the script to debug it then.  I would check that all the expected environment variables are set in the script first.

**Comment by danielnelson** [comment]
Might want to move your script too since many systems clear `/tmp` on shutdown.

**Comment by danielnelson** [comment]
Closing because no work to perform in telegraf.
