### ISSUE TITLE
Log Parser Input Plugin does not work on RHEL 5

### ISSUE THREAD

**Issue by sudharani-m** [influxdata/telegraf#2805]
Hello Team,

We are running telegraf version v1.2.1 in RHEL 5 server. We are using log parser plugin to send CPU info. However while running the telegraf agent we are getting following error message.
Telegraf.conf file 
[inputs.logparser.grok]
    patterns = ["%{DATA:host_name:tag} %{DATA:metric:tag} %{NUMBER:mft_value:float}"] 

Error:
2017-05-15T07:07:00Z I! Started TCP listener service on :8094
2017/05/15 02:07:00 Seeked /opt/mft/shared/logs/cpu.log - &{Offset:0 Whence:0}
2017/05/15 02:07:00 FATAL -- failed to create Watcher
goroutine 47 [running]: 

Do we have RHEL compatibility issue with this plugin?

**Comment by danielnelson** [comment]
Seems like a compatibility issue, can you add the output of `uname -a`.

If you are able can you `git clone https://github.com/fsnotify/fsnotify` and run `git test ./...`

**Comment by sudharani-m** [comment]
Linux *** 2.6.18-417.el5xen #1 SMP Sat Nov 19 14:57:52 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danielnelson** [comment]
To solve this we need someone to check if the fsnotify tests work on RHEL or Centos 5.  I'm assuming the tests will fail, and then we can open a ticket upstream.

**Comment by danielnelson** [comment]
In version 1.5 we are adding a `watch_method = "poll" option which I believe will be a workaround for this issue.

**Comment by danielnelson** [comment]
Closing, RHEL5 users should use the poll method.
