### ISSUE TITLE
testutil/accumulator.go: HasIntField and IntField inconsistency

### ISSUE THREAD

**Issue by froth** [influxdata/telegraf#2806]
## Bug report

testutil/accumulator.go:

The test functions HasIntField and IntField are inconsistent. HasIntField tries to convert the field to int64, IntField to int.
If HasIntField is changed to reflect the same behaviour as IntField, then the TestTimeout unit-test in http_response fails (and several other Tests as well). I believe it fails correctly and the test does not seem to really test the functionality correctly. (I am currently trying to improve error-handling for the http_response plugin)

I believe there should be 2 separate sets of functions. One testing the int and one testing the int64 fields. If somebody could give a second opinion if I am right, I would be willing to fix this (once by boss gives me the go to sign the contributor agreement).

### System info:

current master

**Comment by danielnelson** [comment]
Yes, I believe you are right.

**Comment by froth** [comment]
OK. I'm on it

**Comment by froth** [comment]
https://github.com/influxdata/telegraf/pull/2813 created pull request
