### ISSUE TITLE
influxdb input returns error "use of closed network connection (Client.Timeout exceeded while reading body)"

### ISSUE THREAD

**Issue by cobaugh** [influxdata/telegraf#2807]
## Bug report

telegraf fails to retrieve metrics from influxdb (enterprise).

### Relevant telegraf.conf:

telegraf.conf:
<pre>[tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false
[[inputs.statsd]]
  service_address = ":8125"
  allowed_pending_messages = 10000
  percentile_limit = 1000
  [inputs.statsd.tags]
    _influxdb_database = "telegraf_statsd"
[[outputs.influxdb]]
  precision = "s"
  write_consistency = "any"
  timeout = "5s"
  [outputs.influxdb.tagdrop]
[[outputs.influxdb]]
  precision = "s"
  write_consistency = "any"
  timeout = "5s"
  [outputs.influxdb.tagpass]
    _influxdb_database = ["telegraf_statsd"]
</pre>

telegraf.d/influxdb.conf:
<pre>[[inputs.influxdb]]
</pre>

### System info:
telegraf-1.2.1-1.x86_64
Scientific Linux release 6.9 (Carbon)
influxdb-data-1.2.4_c1.2.4-1.x86_64

### Steps to reproduce:

1. Install influxdb
2. Attempt to pull metrics out of it using telegraf

### Expected behavior:
telegraf is able to connect to the influxdb debug endpoint.

### Actual behavior:

In telegraf.conf every 10s:
<pre>2017-05-15T17:20:22Z I! Starting Telegraf (version 1.2.1)
2017-05-15T17:20:22Z I! Loaded outputs: influxdb influxdb
2017-05-15T17:20:22Z I! Loaded inputs: inputs.statsd inputs.influxdb inputs.diskio inputs.mem inputs.system inputs.kernel inputs.netstat inputs.net inputs.cpu inputs.disk
2017-05-15T17:20:22Z I! Tags enabled: host=influx-p01.ais.psu.edu
2017-05-15T17:20:22Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"influx-p01.ais.psu.edu", Flush Interval:10s 
2017-05-15T17:20:22Z I! Started the statsd service on :8125
2017-05-15T17:20:22Z I! Statsd listener listening on:  [::]:8125
2017-05-15T17:20:35Z E! ERROR in input [inputs.influxdb]: [url=http://localhost:8086/debug/vars]: read tcp [::1]:59196->[::1]:8086: use of closed network connection (Client.Timeout exceeded while reading body)</pre>

Every so often the error will be accompanied with:
<pre>2017-05-15T17:24:35Z E! ERROR in input [inputs.influxdb]: [url=http://localhost:8086/debug/vars]: net/http: request canceled (Client.Timeout exceeded while reading body)</pre>

Additionally, no points are written for most of the received measurements. I say most because some of the data is there, but things hh_processor metrics, for example, are missing.

### Additional info:

I've tried several different URLs (127.0.0.1:8086, influx-p01.ais.psu.edu:8086, etc) and all of them log those errors.

I can curl localhost:8086 just fine:
<pre># time curl -v http://localhost:8086/debug/vars > /dev/null
* About to connect() to localhost port 8086 (#0)
*   Trying ::1... connected
* Connected to localhost (::1) port 8086 (#0)
> GET /debug/vars HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8086
> Accept: */*
>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Influxdb-Version: 1.2.4-c1.2.4
< Date: Mon, 15 May 2017 17:31:28 GMT
< Transfer-Encoding: chunked
<
{ [data not shown]
100 15.7M    0 15.7M    0     0  14.8M      0 --:--:--  0:00:01 --:--:-- 14.8M* Connection #0 to host localhost left intact

* Closing connection #0

real    0m1.064s
user    0m0.048s
sys     0m0.080s
</pre>

**Comment by danielnelson** [comment]
15.7M is a pretty hefty response, I wonder if we are just timing out.  Do the errors go away if the timeout is increased:
```toml
[[inputs.influxdb]]
  interval = "20s"
  timeout = "15s"
```

**Comment by cobaugh** [comment]
It seems like the timeout needs to be at least 7s in my case. I know I tried earlier today and 10s wasn't enough then, but that may have been on a node with more data in the output. Is there anything we can do to improve the situation short of bumping up the timeouts?

**Comment by danielnelson** [comment]
We can do a performance review on this input.  If curl can get the data in 1s then it shouldn't take so long for Telegraf.  I do wonder if sometimes the time spikes though.

Is it possible to get a copy of the response?  I might be useful to have someone on the InfluxDB team take a look at it to make sure everything looks normal.

**Comment by cobaugh** [comment]
/debug/vars output can be found here:

http://personal.psu.edu/atc135/debug_vars.txt

**Comment by danielnelson** [comment]
If I serve this file from a local HTTP server, telegraf can run --test in about 1s and generates 32351 points, which is probably way more data than you want to be sending every interval.

I shared this file with @mark-rushakoff and an initial inspection lead him to believe that the retention policy has too short of a shard duration.  It would be best to reach out to support with this debug_vars.txt link for assistance in setting the shard duration.  I think this should solve the timeout issue.
