### ISSUE TITLE
[feature-request] support SNMP enum values

### ISSUE THREAD

**Issue by knackjax** [influxdata/telegraf#2809]
### Proposal:

Is there any way to get Telegraf SNMP plugin to collect the enum string value rather than the integer type?

### Current behavior:

For example, I'm collecting from IF-MIB::ifType and it has a bunch of values defined in an enum table. I would rather store that information in InfluxDB rather than the integer type.

### Desired behavior:

This could be added to the 'conversion' option, but basically instead of returning an integer for the enum, return the string

### Use case: [Why is this important (helps with prioritizing requests)]

The enum integer value is meaningless for those unfamilar with SNMP. Most users rather have the string value that the integer represents.

**Comment by Hipska** [comment]
Duplicated by #6330

Also see the mentioned workarounds in that issue.

**Comment by MyaLongmire** [comment]
Since this is a duplicate of #6330 I am going to close it. Please check #6330 for updates.

**Comment by Hipska** [comment]
Hi @knackjax, would you be able to test the artefacts from this PR #11872?
