### ISSUE TITLE
HOST_MOUNT_PREFIX not working as intended

### ISSUE THREAD

**Issue by chadnickbok** [influxdata/telegraf#2811]
## Bug report
HOST_MOUNT_PREFIX isn't behaving as intended.

This line is meant to make sure that only disk partitions starting with HOST_MOUNT_PREFIX are listed when the option is given, allowing telegraf to easily get disk stats from a host when running inside a docker container.

Unfortunately this behavior is currently broken, and only partitions with mount points that match exactly between host and container seem to be listed. The bug is caused by the output of this command: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/ps.go#L73

The code assumes that the partition `Mountpoints` will be returned as they're mounted on the _host_, but in fact they are returned as they are mounted inside the _container_.

This makes this line invalid: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/ps.go#L108

### Relevant telegraf.conf:
Disk usage input when running inside a docker container with the root volume mounted in a path in the container. The HOST_MOUNT_PREFIX is set to match the mount location in the container.

### System info:

Most latest telegraf, running inside a docker container, trying to get disk usage from the host.

### Steps to reproduce:

1. Run telegraf inside a docker container
2. On the _host_, mount a partition somewhere like `/data`
3. Expose the volume to the telegraf container using something like `-v "/:/rootfs:ro" -e HOST_MOUNT_PREFIX=/rootfs`
4. Observe that telegraf in the container does _not_ pick up usage of `/data`: `telegraf --config /etc/telegraf/telegraf.conf --input-filter disk --test`

### Expected behavior:

Disk usage from volumes on the host are exported by telegraf

### Actual behavior:

Disk usage is missing

### Additional info:

Proposed fix here: https://github.com/influxdata/telegraf/pull/2812

**Comment by danielnelson** [comment]
Related #1544

**Comment by m4ce** [comment]
The problem is related to telegraf reading /hostfs/etc/mtab that symlinks all the way to /proc/self/mounts rather than /hostfs/proc/mounts.

If you check my reply in https://github.com/influxdata/telegraf/issues/1544, I've worked around this by passing an additional volume to map the /proc/1/mounts of the host to something like /foo/etc/mtab and then change HOST_ETC to /foo/etc.

```
docker run --rm --privileged -v /:/hostfs:ro -e HOST_MOUNT_PREFIX=/hostfs -e HOST_ETC=/foo/etc -e HOST_PROC=/hostfs/proc -e HOST_SYS=/hostfs/sys -v /proc/1/mounts:/foo/etc/mtab -it telegraf:1.3.0 ..
```

This solves all the issues and I am able to get all the mount points from the host correctly.

**Comment by rdxmb** [comment]
@m4ce Workaround works for me. Thank you very much.
