### ISSUE TITLE
Consider reaping orphans if pid 1

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2820]
### Proposal:

We need to research reaping orphans when Telegraf is pid 1 in to handle the docker use case.

### Current behavior:

No reaping

### Desired behavior:

Unknown

### Use case: [Why is this important (helps with prioritizing requests)]

https://github.com/influxdata/influxdata-docker/issues/66

**Comment by phemmer** [comment]
See also #2476

**Comment by danielnelson** [comment]
Thanks, also https://github.com/influxdata/telegraf/issues/2526 :)

**Comment by phemmer** [comment]
Seems like we should be using [`tini`](https://github.com/krallin/tini), and not trying to turn telegraf into an init manager. Docker even comes bundled with tini, and uses it when you pass the `--init` flag: https://docs.docker.com/engine/reference/run/#specify-an-init-process

**Comment by danielnelson** [comment]
I agree, and considering this is built it now it doesn't make sense to add anything to telegraf.  Looks like it was added in 1.13.0.
