### ISSUE TITLE
About 32-bit binary for windows and freebsd

### ISSUE THREAD

**Issue by mjesse88** [influxdata/telegraf#2821]
Hi all,

I have see it in below url:
https://github.com/influxdata/telegraf/pull/2314

The new version has been released last night, but it also doesnot include 32-bit binaries for Windows.

Do we need to compile it ourselves?

thanks
jesse

**Comment by danielnelson** [comment]
We have it, but you must use the direct links: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.0_windows_i386.zip

**Comment by mjesse88** [comment]
Thanks,
It works for me.

**Comment by mopsld** [comment]
It does not works for me.
I ran Windows 7 SP1, Windows 8.1 and Windows 10.

**Comment by mjesse88** [comment]
@mopsld 
Is your system  x86?  if it is x64,you should download in below url:
https://dl.influxdata.com/telegraf/releases/telegraf-1.3.0_windows_amd64.zip

hope useful to you

**Comment by mopsld** [comment]
Thank you for your response.
I already installed on my windows x64 servers and it works very well.

Telegraf is the best monitor solution for me.

Just I want to monitor using telegraf for my x86 windows.

Thank you.

**Comment by danielnelson** [comment]
@mopsld You could open a new issue with details if the binary is not working for you.  Perhaps someone in the community will be able to fix your problem.

**Comment by mopsld** [comment]
Thank you for your response.

I will open new issue.
