### ISSUE TITLE
[statsd] timing sums

### ISSUE THREAD

**Issue by rijnhard** [influxdata/telegraf#2823]
## Feature Request
_I may have had a moment of idiocy, but I did dig and look repeatedly._
According to the [etsy statsd timing spec](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#timing) timers are supposed to have `sum` aggregates aswell, but telegraf does not seem create these when writing to influx.  

### Current behavior:
Telegraf creates `mean`, `upper`, `lower`, percentiles, `stddev` and `count` but not `sum` for timings.

### Desired behavior:
Create `<field>_sum` field to match etsy statsd spec

### Use case:
It simplifies queries, because now in order to get the sum I have to `<field>_mean * <field>_count` which isn't the end of the world, but not ideal as it requires subqueries pretty quickly when trying to doaggregations.

**Comment by danielnelson** [comment]
:+1:

**Comment by danielnelson** [comment]
Will be included in 1.5.0, thanks to @tpounds
