### ISSUE TITLE
Add configurable timeout to SQL Server input

### ISSUE THREAD

**Issue by jgerschk** [influxdata/telegraf#2824]
Per the conversations in #2051, we need to be able to have a timeout variable for this.  

There are situations which can cause this to take longer to complete than 1m, and having a hard-code timeout, does not seem to make sense.

@sparrc sorry it took so long to get this suggestion in per that thread.

**Comment by zensqlmonitor** [comment]
Longer than 1 minute, I have a doubt; all queries use light-weight DMV objects.
What are the characteristics of the server ?

**Comment by m82labs** [comment]
@jgerschk is this still something you are having trouble with?

**Comment by nwneisen** [comment]
I'd like to work on adding this.

I've found that this should already be possible by adding a timeout to the server string.
```
  # servers = [
  #  "Server=192.168.1.10;Port=1433;User Id=<user>;Password=<pw>;app name=telegraf;log=1;dial timeout=30",
  # ]
```
Adding this to the README would let users know that this option is available.  A convenience option could also be added to the telegraf config which could append a timeout to the server strings.

Another option, which is recommended by the `denisenkom/go-mssqldb` drive, is to pass a context with a timeout as a query argument.  This seems like the best way to go IMO.  

I'm looking into a way to force a timeout in sql server for testing but I can add whichever of these options sounds the best.

**Comment by danielnelson** [comment]
> Adding this to the README would let users know that this option is available.

:+1:

> A convenience option could also be added to the telegraf config which could append a timeout to the server strings.

I don't think we should modify the connection string, but I would like a timeout option that would apply across the entire `Gather` function.  This timeout would be different from the connection string as I assume the dial timeout only applies to setting up the connection.

> pass a context with a timeout as a query argument. This seems like the best way to go IMO.

Agreed, and sometime in the future we will add support for cancelling a Gather via a passed in Context.  For now, we can create a `context.Background()` for each call to Gather.

**Comment by nwneisen** [comment]
I didn't update the README since there was already a comment of where to learn more about the server strings.  I was able to cause timeouts by setting the value very low.

**Comment by reimda** [comment]
The workaround of adding a timeout to the connection string seems like it solves this problem. We should document that and close this issue.
