### ISSUE TITLE
Convert JSON Tags/Keys on Input

### ISSUE THREAD

**Issue by efaden** [influxdata/telegraf#2832]
I have a Kafka producer (Verizon vflow) which parses an ipfix stream and produces JSON output which I would like it to send to Telegraf via Kafka.  The ultimate destination of the data will be InfluxDB.  Right now the json looks like

{"AgentID":"192.168.21.15","Header":{"Version":10,"Length":420,"ExportTime":1483484642,"SequenceNo":1434533677,"DomainID":32771},"DataSets":[[{"I":8,"V":"192.16.28.217"},{"I":12,"V":"180.10.210.240"},{"I":5,"V":2},{"I":4,"V":6},{"I":7,"V":443},{"I":11,"V":64381},{"I":32,"V":0},{"I":10,"V":811},{"I":58,"V":0},{"I":9,"V":24},{"I":13,"V":20},{"I":16,"V":4200000000},{"I":17,"V":27747},{"I":15,"V":"180.105.10.210"},{"I":6,"V":"0x10"},{"I":14,"V":1113},{"I":1,"V":22500},{"I":2,"V":15},{"I":52,"V":63},{"I":53,"V":63},{"I":152,"V":1483484581770},{"I":153,"V":1483484622384},{"I":136,"V":2},{"I":243,"V":0},{"I":245,"V":0}]]}
Decoded sFlow data

Where the I numbers are the IPFix element IDs (http://www.iana.org/assignments/ipfix/ipfix.xhtml).

Is there a way to convert that JSON object into a flat JSON object which I could bring into influxDB?  

Ideally it would be flattened and the id the I value correlates to would be the key.  

So something like

src_address = value
dst_address = value

etc

**Comment by danielnelson** [comment]
There is the [JSON data format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json) that you can use in the `kafka_consumer`.
