### ISSUE TITLE
Ability to capture zone serial

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2834]
### Proposal:
It would be nice if there were a way to extract the serial number from a DNS SOA record.
This could fit into the existing `dns_query` plugin, and a config param could be used which would enable extracting the various components. When enabled, fields would be generated for the SOA's authoritative name server, admin email, serial, refresh, retry, expiration & max lifetime.

### Use case:
When running multiple DNS servers serving the same zone, one would want to monitor them to ensure that they are all serving the same version of a zone. The version is denoted by the SOA serial number.

I think this is a common enough use case to warrant inclusion into telegraf, but it is kinda getting into the edge case territory, so I could understand leaving it up to the user to create their own implementation. But in this case I would put forth that we need better external plugin support, as personally I'm not fond of any of the current solutions (I'm aware there are a few open discussions on the subject, but they haven't seen much movement lately).
There is however another argument for this, in that a solution could be implemented that would allow extracting fields from any DNS response. For example MX queries might extract the priority and host name. Though I think this might also be an edge case.

**Comment by danielnelson** [comment]
Maybe the fields created should depend on the `record_type` in the config?  With MX records it might be tricky since you likely have several hosts, so you would also need to add in some tags.

Another thing I would like to support is hostname.bind #2459

**Comment by phemmer** [comment]
> Maybe the fields created should depend on the record_type in the config? With MX records it might be tricky since you likely have several hosts, so you would also need to add in some tags.

I think we could add an "index" as a tag. For example take all the results, do a simple string sort on them, and then record them with their position in the sorted list as the tag. This will keep cardinality small, while allowing tracking multiple records.

**Comment by sspaink** [comment]
@phemmer are you still interested in seeing this feature implement?

**Comment by phemmer** [comment]
Not currently no. I no longer manage any DNS systems. If you're asking if you can close, go for it.

**Comment by sspaink** [comment]
Thanks for the quick response, you read my mind. Closing this issue in that case.
