### ISSUE TITLE
Gather duplicate mount points

### ISSUE THREAD

**Issue by lwhile** [influxdata/telegraf#2837]
### Relevant telegraf.conf:
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs","nfs"]

### System info:
OS: Centos 7
Telegraf version: 1.2.1 

df command output:

    /dev/sda1          104806400  67711336   37095064   65% /
    devtmpfs            32870072         0   32870072    0% /dev
    tmpfs               32879540        32   32879508    1% /dev/shm
    tmpfs               32879540   1451136   31428404    5% /run
    tmpfs               32879540         0   32879540    0% /sys/fs/cgroup
    /dev/sdb1          243542852  13290616  230252236    6% /opt/sunrun/ssd
    /dev/sda3         1813149700 571316500 1241833200   32% /opt/sunrun/date
    tmpfs                6575908         0    6575908    0% /run/user/0
    localhost:/vmpool 1572096000 571222016 1000873984   37% 
    /opt/sunrun/primarystorages/8252e5d4-
    44ed-4cb3-a9a6-6ef6742f2a3a
    tmpfs               32879540         0   32879540    0% /tmp`

### Steps to reproduce:
Telegraf will gather the mount point "/"  duplicately.

 I added a code to "telegraf/plugins/inputs/disk.go" to display info :

    func (s *DiskStats) Gather(acc telegraf.Accumulator) error {
            ......
             disks, partitions, err := s.ps.DiskUsage(s.MountPoints, s.IgnoreFS)
	     log.Println("disks:", disks)
            ......
    }

 `{"path":"/","fstype":"rootfs","total":107321753600,"free":37962964992,"used":69358788608,"usedPercent":64.62696171226185,"inodesTotal":104857600,"inodesUsed":74966,"inodesFree":104782634,"inodesUsedPercent":0.07149314880371094}`

`{"path":"/","fstype":"xfs","total":107321753600,"free":37962964992,"used":69358788608,"usedPercent":64.62696171226185,"inodesTotal":104857600,"inodesUsed":74966,"inodesFree":104782634,"inodesUsedPercent":0.07149314880371094}`

Except for fstype field other information is the same, and my purpose is to calculate my disk capacity.

**Comment by danielnelson** [comment]
It should be good because `fstype` is a tag, you can sum them with:
```
select sum(total) from disk where time > now() - 1m group by time(10s);
```

Does this solve your issue?

**Comment by lwhile** [comment]
@danielnelson thanks, it solve my prolem.
