### ISSUE TITLE
SQL Server input memory

### ISSUE THREAD

**Issue by cstovi** [influxdata/telegraf#2838]
Running Telegraf 1.2.1 with only the sql server input and influxdb output is using ever increasing memory.  Currently at 2.5GB.  I have 15 sql server instances configured.  I've tried it with less servers.

Default settings (from a fresh generated config) for 1.2.1 running 64 bit on Windows 2012 R2.

I had thought the most likely use of memory would be buffering failed writes but in debug mode there's nothing to suggest metric sending issues.  Changing metric buffer limit doesn't reduce memory growth.

**Comment by danielnelson** [comment]
Can you retest with 1.3.0?  If it is still a problem can you run telegraf with `--pprof-addr=:6060` and add the output of http://localhost:6060/debug/pprof/heap to this issue?

**Comment by cstovi** [comment]
Thanks, didn't realise 1.3.0 was out for Windows.  Will do that and post back here in a day or two.

**Comment by cstovi** [comment]
Unfortunately I can't retest on 1.3.0 yet as that has other problems.  outputs.influxdb no longer appears to accept a "-" in the database name which we are using on 1.2.1 e.g. "telegraf-mssql".

Also getting lots of 

"2017-05-24T09:58:20Z E! Error in plugin [inputs.sqlserver]: Login error: read tcp 144.32.14.171:58305->144.32.14.72:1433: wsarecv: An existing connection was forcibly closed by the remote host.
2017-05-24T09:58:20Z E! Error in plugin [inputs.sqlserver]: driver: bad connection"

Which was not occuring with 1.2.1.

**Comment by danielnelson** [comment]
Can you open new issues for both of those problems?  Make sure to add the version of sql server you are using.

**Comment by danielnelson** [comment]
I opened a ticket for the hyphen issue.  #2850

**Comment by cstovi** [comment]
Thanks.  I'll try the sqlserver connection issue with only particular sql server versions to see if I can narrow it down.  Hopefully I can get back to the memory issue once that's sorted.

**Comment by cstovi** [comment]
I've created an issue for the sql server connection problems on 1.3.0.
https://github.com/influxdata/telegraf/issues/2852

I can now leave telegraf running again working around these to see if the original memory growth issue still exists from 1.2.1

Thanks.

**Comment by cstovi** [comment]
Testing for a few hours it looks like the huge memory usage doesn't occur with 1.3.0.  It's sat at around 25 MB instead of 2.5GB 👍 

So if the other 1.3.0 issues are fixed all will be good.

**Comment by danielnelson** [comment]
Okay, so I'll close this issue as fixed in 1.3.0 and we can discuss the SQL issue on the new issue.
