### ISSUE TITLE
The win_perf_counters input does not close query handles

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2843]
## Bug report

Based on code inspection, the `win_perf_counters` input does not close its handle using `PdhCloseQuery`.  This will likely cause the handles to become lost if the Telegraf reloads the plugin.

### Relevant telegraf.conf:
N/A

### System info:
N/A

### Steps to reproduce:
May not currently be possible since I don't think you can trigger a reload of plugins in Windows.

### Expected behavior:
`win_perf_counters` should call `PdhCloseQuery` for every handle opened with `PdhOpenQuery`.

### Actual behavior:
`PdhCloseQuery` is never called

### Additional info:

Has not been verified.  Discovered in code review of #2800

**Comment by danielnelson** [comment]
@vlastahajek Can you take a look at this and let me know if we need to address?

**Comment by vlastahajek** [comment]
@danielnelson This is handled in #4189. 
I created reusable struct representing query, which closes previous query, during each open. Even it may not seems perfect from OOD perspective, I did it so to create simple GO mock-able abstraction with the least possible amount of business logic.
