### ISSUE TITLE
About exec plugin cannot add timestamp

### ISSUE THREAD

**Issue by mjesse88** [influxdata/telegraf#2844]
Hi All,

I write script that uses json format,
I find I can't add my timestamp to influxdb, the timestamp auto create by telegarf.
What is something I missed?

I visited below url, but can't get answer. 
Telegraf Input Data Formats:
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

Thanks
Jesse

**Comment by danielnelson** [comment]
The JSON data_format does not support setting a timestamp, maybe you can modify your script to output in `influx` format?

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
