### ISSUE TITLE
sqlserver input connection issues since 1.3.0

### ISSUE THREAD

**Issue by cstovi** [influxdata/telegraf#2852]
A quick test suggests Telegraf 1.3.0 on Windows 64bit no longer supports the sqlserver.input plugin when connecting to:

Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)

or if you use connection string which specifies the instance name e.g.

myserver.somwhere.com\\mysqlserver

The version issue results in an error:
E! Error in plugin [inputs.sqlserver]: Login error: read tcp wsarecv: An existing connection was forcibly closed by the remote host.

and the named instance format says:

E! Error in plugin [inputs.sqlserver]: driver: bad connection"

For the version issue patching is a reasonable fix, but the named instance connection string should still be supported and is useful in Telegraf 1.2.1

**Comment by danielnelson** [comment]
Can you add a config file example for both connection string types?

**Comment by cstovi** [comment]
"Server=mssqlinst1.its.york.ac.uk;Port=1433;User Id=telegraf;Password=mypassword;app name=telegraf;log=1;",

"Server=mssqlinst2.its.york.ac.uk\\namedinst;Port=1433;User Id=telegraf;Password=mypassword;app name=telegraf;log=1;",

I've realised however that we only do this for one or two nonstandard unusually configured multi instance servers so we can probably ignore it.  It did used to work though.

**Comment by danielnelson** [comment]
@cstovi Do you have Microsoft SQL Server 2008 Service Pack 3 and Cumulative update package 3 for SQL Server 2008 SP3? https://github.com/zensqlmonitor/go-mssqldb#known-issues

@zensqlmonitor Do you remember why we are using your fork of go-mssqldb instead of denisenkom/go-mssqldb?

**Comment by cstovi** [comment]
@danielnelson I can't look right now but very probably not.  We run lots of different instances at different versions/patch levels.  Thanks for your help.

**Comment by zensqlmonitor** [comment]
@danielnelson yes, I made a modification to accept T-SQL flags (SET ...).
The issue is solved [https://github.com/denisenkom/go-mssqldb/pull/145](url); the project can now reference to the denisenkom project.

**Comment by zensqlmonitor** [comment]
@cstovi some advices:
- SQL Server 2008 R2 is not supported anymore by MS, if possible try to upgrade
- Always change the default TCP/1433 port for an instance (security best practice)
- To connect to the default or to a named instance, only use the server name and the configured port 
   It is also a security best practice to not run the SQL Server Browser service by default.

**Comment by cstovi** [comment]
@zensqlmonitor thanks, although sound basic advice I'm just reporting changes in behaviour of telegraf in the new version, regardless of it you would want to or if it needs patched (which it does).   The docs for go-mssqldb say you can use named instances with hostname\\instancename

**Comment by m82labs** [comment]
@cstovi is this still an issue for you?

**Comment by cstovi** [comment]
It's not.  I don't know if it works now as we only have a handful of instances using this and they are not using the host/instance format.  We only had a couple which needed it back then.
