### ISSUE TITLE
docker input plugin parsing error

### ISSUE THREAD

**Issue by regevbr** [influxdata/telegraf#2859]
### Relevant telegraf.conf:

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []
  timeout = "5s"
  perdevice = true
  total = true

### System info:

Telegraf v1.3.0 
Ubuntu 14.04.4 LTS
Docker Client version: 1.6.2
Docker Client API version: 1.18

### Steps to reproduce:

1. run some docker image
2. run telegraf with the above configuration to monitor docker
3. get the following error:
 Error in plugin [inputs.docker]: Error reading remote info: json: cannot unmarshal number into Go struct field Info.Debug of type boo                                                                                l

### Expected behavior:

docker metrics should get collected

### Actual behavior:

no docker metrics are collected

**Comment by danielnelson** [comment]
Can you run `sudo curl --unix-socket /var/run/docker.sock http://localhost/info` and attach the output?  I believe you must use curl >= 7.5 for this to work.

**Comment by regevbr** [comment]
```json
{"Containers":1,"Debug":0,"DockerRootDir":"/var/lib/docker","Driver":"aufs","DriverStatus":[["Root Dir","/var/lib/docker/aufs"],["Backing Filesystem","extfs"],["Dirs","154"],["Dirperm1 Supported","true"]],"ExecutionDriver":"native-0.2","ID":"OHSD:PMZZ:DMZB:JJA2:PWRA:TXZ5:XD6K:EZQS:6V6A:JBBA:JKB3:4NEW","IPv4Forwarding":1,"Images":152,"IndexServerAddress":"https://index.docker.io/v1/","InitPath":"/usr/lib/docker.io/dockerinit","InitSha1":"22082e594df367c79a11672c59a9d5da15851227","KernelVersion":"3.19.0-58-generic","Labels":null,"MemTotal":1757966336,"MemoryLimit":1,"NCPU":1,"NEventsListener":0,"NFd":21,"NGoroutines":22,"Name":"westEuropeWebserver","OperatingSystem":"Ubuntu 14.04.4 LTS","RegistryConfig":{"IndexConfigs":{"docker.io":{"Mirrors":null,"Name":"docker.io","Official":true,"Secure":true}},"InsecureRegistryCIDRs":["127.0.0.0/8"]},"SwapLimit":0,"SystemTime":"2017-06-01T14:59:10.564352517Z"}
```

**Comment by regevbr** [comment]
I installed a new docker (17 CE) and it works perfectly. The issue was related to old docker versions.
We can either close the bug or put a fix to handle old dockers... what do you say?

**Comment by danielnelson** [comment]
I think I'll close here since any fix would have to go into the moby project.  You could ask the docker team if they are interested in fixing this issue.
