### ISSUE TITLE
sqlserver input plugin not working with Azure SQL

### ISSUE THREAD

**Issue by regevbr** [influxdata/telegraf#2861]
### Relevant telegraf.conf:
```
[[inputs.sqlserver]]
  servers = [
    "Server=<Server>;Port=1433;User Id=<user>;Password=<password>;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=False;Persist Security Info=False;",
  ]
```

### System info:

telegraf 1.3.0 and telegraf 1.2.1
Ubuntu 16
```
select @@Version
Microsoft SQL Azure (RTM) - 12.0.2000.8   Mar 21 2017 02:11:40   Copyright (C) 2016 Microsoft Corporation. All rights reserved. 
```
Azure firewall set up correctly

### Steps to reproduce:

use the provided conf in either version of telegraf along with azure sql server

### Expected behavior:

metrics get sent

### Actual behavior:

```
2017-05-28T21:44:00Z E! Error in plugin [inputs.sqlserver]: read tcp 10.0.0.8:59260-><ip>:11210: read: connection reset by peer
2017-05-28T21:44:00Z E! Error in plugin [inputs.sqlserver]: driver: bad connection
```

### Additional info:

Using the same connection string in a simple go progeam:
```
package main

import _ "github.com/zensqlmonitor/go-mssqldb"
import "database/sql"
import "log"
import "fmt"

var debug = true

func main() {

        connString :=  "Server=<Server>;Port=1433;User Id=<user>;Password=<password>;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=False;Persist Security Info=False;"
        if debug {
                fmt.Printf(" connString:%s\n", connString)
        }
        conn, err := sql.Open("mssql", connString)
        if err != nil {
                log.Fatal("Open connection failed:", err.Error())
        }
        defer conn.Close()

        stmt, err := conn.Prepare("select 1, 'abc'")
        if err != nil {
                log.Fatal("Prepare failed:", err.Error())
        }
        defer stmt.Close()

        row := stmt.QueryRow()
        var somenumber int64
        var somechars string
        err = row.Scan(&somenumber, &somechars)
        if err != nil {
                log.Fatal("Scan failed:", err.Error())
        }
        fmt.Printf("somenumber:%d\n", somenumber)
        fmt.Printf("somechars:%s\n", somechars)

        fmt.Printf("bye\n")

}
```
With either  github.com/zensqlmonitor/go-mssqldb or github.com/denisenkom/go-mssqldb doesn't create any issuess....

**Comment by regevbr** [comment]
When setting the log to 63 in the connection string, i see that it prepares the statements, so maybe running them cause the issue?

**Comment by regevbr** [comment]
It seems that the queries used in the plugin are using the following 3 system views that don't exist in azure...
```
sys.dm_os_sys_memory
sys.master_files
sys.dm_os_sys_info
```
Is there a way to get past that? maybe create another plugin just for azure?

**Comment by kardianos** [comment]
For above, probably just check if they exist before querying, rather then new plugin.

**Comment by regevbr** [comment]
Sounds good. I hope i will have time soon to create a pull request, or do you prefer to do it?

**Comment by deluxor** [comment]
I am currently experiencing the same problem, Is there any way to create those views? Or any fast workaround?

**Comment by kardianos** [comment]
You cannot create those views. What information do they provide to telegraf?

**Comment by regevbr** [comment]
Not sure yet but for now we can just skip them in case they are missing

**Comment by regevbr** [comment]
Managed to fix the queries for azure. When in azure the following metrics will not be present:
Available physical memory (bytes)
Page File Usage (%)
Rows max size (8KB pages)
Logs max size (8KB pages)
Volume total space (bytes)
Volume available space (bytes)
Volume used space (bytes)
Volume used space (%)

Which is acceptable considring the fact that you don't really own the physical machine the db is running on, nor you care about its stats

I will draft a pr right now

**Comment by regevbr** [comment]
PR is ready

**Comment by regevbr** [comment]
Even after compiling with log level 29 I see that there are rows effected, which means the queries are being ran, but I still get the connection reset by peer.... I'm out of ideas on how to solve it

**Comment by regevbr** [comment]
After adding some logging it seems that some of the queries succeed and some get timeout, still investigating

**Comment by regevbr** [comment]
according to https://azure.microsoft.com/en-us/blog/sql-azure-connectivity-troubleshooting-guide/
azure is performing DOS attacks prevention. I have managed to get my queries working by running the queries one by one and by sharing the same connection between the queries

**Comment by kardianos** [comment]
Just run one query that returns multiple result sets and use tsql if stmts to determine if views are supported.

**Comment by regevbr** [comment]
FIxed in PR by adding a new param - disable_parallel that will not cause DOS of azure to kick in (made a few other changes to fix the problem but that is what you need to do if you encounter the issue)

**Comment by m82labs** [comment]
v2 queries in the latest version now support Azure SQL DB.
