### ISSUE TITLE
Android has to close and reopen socket to send more than one udp packet

### ISSUE THREAD

**Issue by arnoid** [influxdata/telegraf#2863]
### Relevant telegraf.conf:
~~~~
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = ""
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] # required
  database = "telegraf" # required
  precision = "s"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.swap]]
[[inputs.net]]
[[inputs.statsd]]
  service_address = ":8125"
  delete_gauges = true
  delete_counters = true
  delete_sets = false
  delete_timings = true
  percentiles = [90]
  convert_names = false
  templates = [
    "* measurement.field"
  ]
  allowed_pending_messages = 10000
  percentile_limit = 1000
  udp_packet_size = 1500
~~~~

### System info:
- Telegraf version: 1.2-alpine
- runs in Docker

### Steps to reproduce:

1. have a telegraph running
2. use demo project from https://github.com/arnoid/telegraph-android-demo-issue
3. start sending values

### Expected behavior:
- all packets are received without socket closing/reopening

### Actual behavior:
- the first packet is received only. (All packets after the first one are ignored)

### Additional info:
- if the socket is closed and reopened then all packets are received.
- other UDP destinations are receiving packets through the same socket in the normal way.

### Use case: [Why is this important (helps with prioritizing requests)]
- We have a mobile Android(Java) client which emits metrics (sensordata) to different endpoints, including Telegraf via statsd
- It would be really nice if we could reuse same socket without expensive socket recreation actions.

**Comment by danielnelson** [comment]
Closing since no response, feel free to reopen though if you would like to continue discussing.
