### ISSUE TITLE
Add TLS/SSL encryption support to socket_writer and socket_listener

### ISSUE THREAD

**Issue by returntoreality** [influxdata/telegraf#2866]
### Proposal:
Add SSL encryption support to the socket_writer and socket_listener plugins with client certificate support.

### Current behavior:
socket_writer allows to send data over tcp or udp. socket_listener allows to receive data over tcp or udp. This data is transferred in cleartext over the connection.

### Desired behavior:
It should be possible to encrypt and authenticate the data transferred preferably using tls/ssl and authenticate the writer and listener using certificates.

### Use case:
I want to authenticate the data sent by the clients by using the cn field of a client certificate specific for each client. This would ensure that a compromised client cannot send measurements for other clients.

**Comment by phemmer** [comment]
I like the idea, and implementation should be simple.
It would be nice to support DTLS in the future as well. Unfortunately it seems the only functional DTLS library right now uses OpenSSL bindings, which may present an issue including into telegraf.
