### ISSUE TITLE
prometheus_client: Internal Server Error does not log anything

### ISSUE THREAD

**Issue by mmariani** [influxdata/telegraf#2868]
## Bug report

With the Prometheus_client plugin, I get 500 Internal Server Error for some reason.
I don't have any information to debug it (even with agent.debug = true).

### Relevant telegraf.conf:

[[outputs.prometheus_client]]
listen = ":9126"
expiration_interval = "60s"

### System info:

Telegraf 1.3.0, Linux

### Steps to reproduce:

wget http://localhost:9126/metrics
Connecting to localhost:9126 (127.0.0.1:9126)
wget: server returned error: HTTP/1.1 500 Internal Server Error

### Expected behavior:

See something in stderr

### Actual behavior:

Nothing gets logged

**Comment by danielnelson** [comment]
I wonder if it is caused by a particular input, can you try enabling only a single "system" input and see if you still receive a 500 error?

**Comment by mmariani** [comment]
It is indeed caused by docker input, but these metrics are exported to influxdb without issues.

**Comment by danielnelson** [comment]
This might be a duplicate of #2822, is there anything in the response body?

**Comment by mmariani** [comment]
Yes indeed. I saw no response body yesterday.
Now that I've left the stack running for a while, I get a lot of these "label dimensions inconsistent with previously collected metrics"

**Comment by mmariani** [comment]
Sorry I've been careless, I used wget at the beginning which did not print a response in case of error. With curl I had the complete response.

**Comment by danielnelson** [comment]
I'm going to close this one, will track over on the other issue.
