### ISSUE TITLE
CPU measurement fails after VM migrate between xen hosts

### ISSUE THREAD

**Issue by gallart** [influxdata/telegraf#2871]
### Relevant telegraf.conf:

```
[[inputs.cpu]]
  # Whether to report per-cpu stats or not
  percpu = true
  # Whether to report total system cpu stats or not
  totalcpu = true
  # Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]
```

### System info:

* Telegraf version : 1.3.0
* OS : Gentoo Linux
* Virtual env : XenServer

### Steps to reproduce:

1. Start telegraf on Linux guest host
2. Move host (live migration) from one hypervisor to another)

### Expected behavior:

CPU Measurement should continue without trouble.

### Actual behavior:

No more CPU measurements, with the following error :

```
* Plugin: inputs.cpu, Collection 1
* Plugin: inputs.cpu, Collection 2
2017-05-31T13:33:26Z E! Error: current total CPU time is less than previous total CPU time
```

### Additional info:

Rebooting host fixes the issue.

Thanks for your help !

**Comment by phemmer** [comment]
This is really interesting. Would you be able to provide the output of `grep '^cpu' /proc/stat` before the migration, after the migration, and then again a few seconds later?

**Comment by gallart** [comment]
Before migration :

```
cpu  8496572 305946 943142 328322278 3023148 0 63260 194028 0 0
cpu0 1760022 80046 233060 81701764 1393126 0 24800 58059 0 0
cpu1 2273818 72875 234925 82237240 526798 0 12985 32368 0 0
cpu2 2292952 72327 238975 82189843 543429 0 13002 32781 0 0
cpu3 2169779 80696 236181 82193430 559794 0 12472 70820 0 0
```

After migration :

```
cpu  8497805 305947 943369 328393621 3023475 0 63270 1750538050819 0 0
cpu0 1760294 80048 233098 81719428 1393368 0 24804 1825121610327 0 0
cpu1 2274094 72875 234959 82255199 526853 0 12988 1841457961672 0 0
cpu2 2293320 72327 239009 82207724 543447 0 13003 1839967821051 0 0
cpu3 2170096 80696 236302 82211269 559806 0 12473 1778013879880 0 0
```

**Comment by phemmer** [comment]
Can you also do again a few seconds later? The code in the plugin is such that even if the values do get screwed up once, subsequent gather intervals should work fine. But your report indicates this is not the case, so I want to see how the values are changing after the migration has completed.

**Comment by gallart** [comment]
Here is the new value (few minutes after) :

```
cpu  8497805 305947 943369 328628732 3024618 0 63270 540640815829 0 0
cpu0 1760294 80048 233098 81778381 1393541 0 24804 709390804805 0 0
cpu1 2274094 72875 234959 82313823 527160 0 12988 1037106086598 0 0
cpu2 2293320 72327 239009 82266574 543783 0 13003 670685834267 0 0
cpu3 2170096 80696 236302 82269952 560133 0 12473 1812806904899 0 0
```

I can reproduce issue with "few seconds" later

**Comment by phemmer** [comment]
"few minutes" is fine. Thanks :-)

**Comment by phemmer** [comment]
@danielnelson How do you want to handle this? This smells like a bug in the kernel. Those steal times don't make any sense. At first I thought it might be some weird integer overflow, but that doesn't even hold up as the values should all be changing at roughly the same rate, but they're all over the place:

```
540640815829 - 1750538050819 = -1209897234990
709390804805 - 1825121610327 = -1115730805522
1037106086598 - 1841457961672 = -804351875074
670685834267 - 1839967821051 = -1169281986784
1812806904899 - 1778013879880 = 34793025019
```

I googled around a little bit, but couldn't find any reported issues of screwed up CPU steal times on XEN after a migration.

**Comment by danielnelson** [comment]
You should probably ask the XenServer team if this is a bug.  I'm curious, how does the output of top or other cpu monitoring tools look?

**Comment by danielnelson** [comment]
I'm going to close this issue for now since I don't think we can fix this in Telegraf.  I hope you will keep us updated on this issue, feel free to comment here with any new information.
