### ISSUE TITLE
Lag in messages per follower replica is giving 404 

### ISSUE THREAD

**Issue by nivedithag13** [influxdata/telegraf#2873]
trying to fetch metrics for kafka 
One of the metrics as mentioned below
Lag in messages per follower replica

kafka.server:type=FetcherLagMetrics,name=ConsumerLag,clientId=([-.\w]+),topic=([-.\w]+),partition=([0-9]+)

is giving me following response when I run the telegraf.conf file
Error handling response: Not expected status value in response body: 404

Entry in the telegraf.conf file is as follows
[[inputs.jolokia.metrics]]
    name = "processor_avg_idle_percent"
    mbean  = "kafka.server:type={Produce|Fetch},user=([-.\w]+),client-id=([-.\w]+)"
    attribute = "byte-rate,throttle-time"

**Comment by danielnelson** [comment]
What is the expected result?

**Comment by nivedithag13** [comment]
expected result should give us the metrics

**Comment by nivedithag13** [comment]
can someone look into this or suggest how can I fetchlag metrics for Consumer w.r.to client and topics

**Comment by danielnelson** [comment]
@nivedithag13 In the 1.5 release, coming out in about a month there is a replacement plugin called jolokia2 with a different configuration format, you can try it out using the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds).

Can you try this out and let me know if you are able to get it working?

**Comment by danielnelson** [comment]
We can reopen if the `jolokia2` input does not solve the issue.  You can now use the latest release candidate.

https://github.com/influxdata/telegraf/releases

**Comment by danielnelson** [comment]
Perhaps this pull request would be of interest for the lag metrics: https://github.com/influxdata/telegraf/pull/3489
