### ISSUE TITLE
Support symlink for --config-directory

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#2876]
Currently, telegraf does not support the --config-directory argument to be a symlink, because it uses filespath.Walk(...) to get the files, and to avoid an infinite loop problem, filepath.Walk(...) does not resolve symlinks.  This makes sense from a golang perspective, but often the actual telegraf.d directory could be symlinked directory.  Should telegraf attempt to resolve the symlink before walking the path?  This is a trivial fix, in the LoadDirectory function of config.go:

`return filepath.Walk(filepath.EvalSymlinks(path), walkfn)`

I would happy to do this as a PR, but wanted to get a sense of first if this is a good practice (to have the telegraf.d directory be a symlink).

**Comment by phemmer** [comment]
Note you should be able to work around this very easily by adding a `/` to the end of the path (I haven't tested, but in theory it should work).
E.G.: `telegraf --config-directory /path/to/symlink/`

**Comment by puckpuck** [comment]
Trailing slash does indeed work. Thanks for the tip.

**Comment by phemmer** [comment]
Sorry, I wasn't saying you should close it, just proposing a workaround :-)
Up to the project owners whether an official solution should be implemented.

**Comment by puckpuck** [comment]
The workaround being so simple, doesn't warrant a fix IMO.
