### ISSUE TITLE
Create an APCUPCd Plug-in

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#2877]
## Feature Request
Create a native APCUPCd plug-in for Telegraf.
http://www.apcupsd.org/

### Current behavior:
You can leverage the exec plug-in to gather stats from APC/UPC today...and example of that can be found here:
https://rmoff.net/2016/07/18/configuring-ups-apcupsd/
https://bitbucket.org/snippets/wnasich/7Kg89/telegraf-input-for-apc-ups-status-using

### Desired behavior:
Create a native plug-in which allows for gathering of stats from the daemon.

### Use case: 
The large and growing distribution of uninterruptible power supplies having stats which monitor these devices is important.

**Comment by danielnelson** [comment]
#2552

**Comment by Aqualie** [comment]
Can we have this re-added as a milestone in the future. Would be a very useful plugin to have added as UPS monitoring in large (NUT) is utilized quite heavily for monitoring.

**Comment by danielnelson** [comment]
I think we are quite close to having this done, and it would make sense to finalize it up.  I'll add this to the next milestone, it does't guarantee we can get to it, but it will put it on our short(er) list of task items.
