### ISSUE TITLE
Telegraf agent opening & closing “su” sessions in Linux machines

### ISSUE THREAD

**Issue by dudusakharovich** [influxdata/telegraf#2884]
We are using Telegraf in our production servers (Linux & Windows OS) to collect metrics and send them to InfluxDB.
We are also monitoring our production servers for security breaches or any other suspicious activity.

We encountered a security issue in which the Telegraf user opened & closed an "su" session in a production server.
Is this behavior normal ? Why would the Telegraf user open & close these kind of sessions ?

More information would be grateful & helpful.

**Comment by danielnelson** [comment]
[Replied on community](https://community.influxdata.com/t/telegraf-agent-opening-closing-su-sessions-in-linux-machines/1166).
