### ISSUE TITLE
Allow empty JSON in exec plugin

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2887]
## Feature Request

As suggested by @mjesse88, when using json data_format the output should be optional, similar to how the influx data_format works.

### Current behavior:
test.bat
```
@echo off
exit /b 0
E! Error in plugin [inputs.exec]: unable to parse out as JSON, unexpected end of JSON input
```

2.test.bat
```
@echo off
echo ""
exit /b 0
E! Error in plugin [inputs.exec]: unable to parse out as JSON, json: cannot unmarshal string into Go value of type map[string]interface {}
```

### Desired behavior:
No error or metric produced.

### Use case: [Why is this important (helps with prioritizing requests)]

Sometime I don't need metrics write to influxdb, so my script output empty json,

**Comment by mjesse88** [comment]
Thanks for your attention

Jesse
