### ISSUE TITLE
inputs/mongodb not parsing configs

### ISSUE THREAD

**Issue by Jaff** [influxdata/telegraf#2888]
## Bug report
Up to 1.2.1 this was working; in 1.3.0 and 1.3.1, getting error reading config.

### Relevant telegraf.conf:
See https://gist.github.com/Jaff/3a2024afaf44b9b5a448090f46a94fc8

### System info:
telegraf 1.3.0, 1.3.1 on Ubuntu 14.04.4 (x86_64)
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. /etc/telegraf/telegraf.conf contains same data as we used in 1.2.1 version
2. /etc/telegraf/telegraf.d/monitor_mongodb.conf as used in 1.2.1 version

### Expected behavior:
telegraf will collect data from mongodb and output to graphite log

### Actual behavior:
telegraf unable to connect to mongodb
### Additional info:
logs contain:
2017-06-05T20:56:30Z E! Error in plugin [inputs.mongodb]: Unable to parse to address '127.0.0.1:27017': parse 127.0.0.1:27017: first path segment in URL cannot contain colon

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
Possible workaround is to use the mongodb:// uri scheme.

**Comment by Jaff** [comment]
I tried with same results

**Comment by Jaff** [comment]
And likewise with 1.3.1

**Comment by danielnelson** [comment]
I'm going to reopen since this should still be fixed.

**Comment by jackzampolin** [comment]
Should we fix this with documentation and reference the issue?

**Comment by danielnelson** [comment]
I did a combination of documentation and code.  The old method should still work for now but it prompts you to use a url with scheme.  For mongodb use `mongodb://127.0.0.1:27017` and for leofs use `udp://127.0.0.1:4020`.
