### ISSUE TITLE
postgresql sslmode error

### ISSUE THREAD

**Issue by zargex** [influxdata/telegraf#2889]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:
```
# Telegraf Configuration

[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["https://influx:8086"] # required
  database = "telegraf" # required
  precision = "s"
  retention_policy = "default"
  write_consistency = "any"
  timeout = "5s"
  ssl_ca = "/etc/telegraf/cacert.pem" 

 [[inputs.postgresql_extensible]]
   address = "host=postgresql user=telegraf sslmode=require password=PASSWORD dbname=mydb"
    databases = ["mydb"]

   [[inputs.postgresql_extensible.query]]
     sqlquery="SELECT c.usename,c.query,s.ssl,s.version FROM pg_stat_activity c, pg_stat_ssl s where s.pid = c.pid and c.usename = 'telegraf' "
     version=901
     withdbname=false
     tagvalue=""
     measurement="Postgres_ssl"
``` 
### System info:
```
Telegraf 1.3.1-1
Debian 8.3
``` 
### Steps to reproduce:

1. `telegraf --config /etc/telegraf/telegraf.conf -test -input-filter postgresql_extensible` 

### Expected behavior:
```
* Plugin: inputs.postgresql_extensible, Collection 1
> Postgres_ssl,server=host\=postgresql\ user\=telegraf\ dbname\=mydb,db=postgres,host=localhost ssl=true,version="TLSv1.2",usename="telegraf",query="SELECT c.usename,c.query,s.ssl,s.version FROM pg_stat_activity c, pg_stat_ssl s where s.pid = c.pid and c.usename = 'telegraf' " 1496711588000000000
```
### Actual behavior:
```
* Plugin: inputs.postgresql_extensible, Collection 1
2017-06-06T01:11:12Z E! x509: certificate is valid for ip-172-90-90-90.us-west-2.compute.internal, not postgresql
```
### Additional info:

If I change the `sslmode` to `prefer`instead of `require`, telegraf will connect. 

And in `Telegraf 1.2.1-1` the `sslmode=require` worked without problem. This problem happended today after upgraded it.

### Use case: [Why is this important (helps with prioritizing requests)]
Maybe is a bug .

**Comment by danielnelson** [comment]
This error indicates that you are connecting using a different hostname than the certificate is issued for.  When the cert was created it was set to `ip-172-90-90-90.us-west-2.compute.internal`, but you are connecting via the hostname `postgresql`.  You will either need to connect using the former hostname or reissue the certificate with a new common name.

I'm not sure why this would be triggered with 1.3 though, perhaps this is also when you changed the hostname?

**Comment by zargex** [comment]
hi @danielnelson , I understand the error but I don't understand why it happened now. 
Also I haven't changed the database hostname in the telegraf's configuration file. The only think I have changed is the `sslmode`.

About Postgres, it is using 
```
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'		# (change requires restart)
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'		# (change requires restart)
``` 
Also I tried with psql (only to see what happens)
`psql postgresql://telegraf@postgresql:5432/mydb?sslmode=require` 
and I got:
``` 
Password: 
psql (9.5.3, server 9.6.3)
WARNING: psql major version 9.5, server major version 9.6.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

mydb=> 
```

I could think that psql will complain too, but it didn't. (I know that psql and telegraf doesn't have to work in the same way but it is interesting for me).

**Comment by danielnelson** [comment]
I'm not sure then, can you check if reverting to 1.2.1 fixes the issue?  Also are you running telegraf and postgres on the same machine?

**Comment by zargex** [comment]
Not, I'm not running telegraf and postgres on the same machine.

Well, this is funny. I can't downgrade because the previous version of telegraf isn't in the repository and I removed it time ago to save space.

**Comment by zargex** [comment]
@danielnelson I got telegraf 1.2.1-1 from `https://dl.influxdata.com/telegraf/releases/telegraf_1.2.1_amd64.deb`. 

After installed it, I got this messages:
``` 
Jun 06 13:33:40 localhost telegraf[7160]: 2017-06-06T13:33:40Z E! ERROR in input [inputs.postgresql]: pq: unsupported sslmode "prefer"; only "require" (default), "verify-full", "verify-ca", and "disable" supported
Jun 06 13:33:40 localhost telegraf[7160]: 2017-06-06T13:33:40Z E! ERROR in input [inputs.postgresql_extensible]: pq: unsupported sslmode "prefer"; only "require" (default), "verify-full", "verify-ca", and "disable" supported
``` 

Runing the test again but with `sslmode=require` and I got: 
```
* Plugin: inputs.postgresql_extensible, Collection 1
> Postgres_ssl,server=host\=postgresql\ user\=telegraf\ dbname\=mydb,db=postgres,host=localhost query="SELECT c.usename,c.query,s.ssl,s.version FROM pg_stat_activity c, pg_stat_ssl s where s.pid = c.pid and c.usename = 'telegraf' ",ssl=true,version="TLSv1.2",usename="telegraf" 
1496756085000000000
```

Aptitude info:
```
aptitude show telegraf
Package: telegraf                        
New: yes
State: installed
Automatically installed: no
Version: 1.2.1-1
Priority: extra
Section: default
Maintainer: support@influxdb.com
Architecture: amd64
Uncompressed Size: 32.6 M
Description: Plugin-driven server agent for reporting metrics into InfluxDB.
 
Homepage: https://github.com/influxdata/telegraf
```

**Comment by james-lawrence** [comment]
i'll take a peek sometime in the next couple weeks. the driver change probably triggered this.

**Comment by danielnelson** [comment]
@zargex Even though this is technically a regression, it still looks to me that your certificate is bad.  Which would mean that the previous version of Telegraf had broken ssl validation.

I think we just need to double check that ssl is working, so there won't necessarily be any fix on this one. (unless something more is found of course)

**Comment by james-lawrence** [comment]
@danielnelson that is my guess as well.

[libpq](https://github.com/lib/pq/blob/a6140c91df5fb9306106d6de5f533783eacc1392/ssl.go#L20)
```
case "", "require":
		// We must skip TLS's own verification since it requires full
		// verification since Go 1.3.
tlsConf.InsecureSkipVerify = true
```

[pgx](https://github.com/jackc/pgx/blob/master/conn.go#L611):
```
case "require", "verify-ca", "verify-full":
	cc.TLSConfig = &tls.Config{
			ServerName: cc.Host,
	}
```

**Comment by danielnelson** [comment]
Yeah, I'd say that pretty much solves it right there, libpq is clearly allowing invalid certs.

**Comment by james-lawrence** [comment]
@zargex - using `prefer` would is the equivalent behaviour to what 1.2 use to do. so that is your work around as you already discovered.

**Comment by danielnelson** [comment]
@zargex I'm going to close.  Thanks for bringing this to our attention, it does help a lot for debugging.

**Comment by zargex** [comment]
@danielnelson @james-lawrence, I'm sorry but I didn't understand. 

`sslmode = require` must verify the certs ?.

Reading `https://www.postgresql.org/docs/current/static/libpq-ssl.html` I understood that it must not, `require` only enforce a SSL connection, it doesn't care about the veracity of the cert. 

Looking at libpq code above, it has to skip the verification to emulate the behavior explain in postgres' docs.

**Comment by james-lawrence** [comment]
@zargex I'm just pointing out why the change occurred.

you can file an issue with the [driver](https://github.com/jackc/pgx), and I'll be happy to update telegraf once its fixed there.

pgx calls out in its documentation that it currently doesn't follow the [libpq-ssl docs explicitly](https://github.com/jackc/pgx/blob/master/conn.go#L552) but leaves room to correct the behaviour in the future. So I suspect it'll be fairly easy to request the behaviour change to match libpq-ssl.

I'm personally not concerned enough about this particular regression to jump through hoops on telegraf's side to address it for the following reasons:
1) there is a workaround using prefer which is basically the same thing when the server supports ssl.
2) it doesn't compromise the security promises of the require setting.

**Comment by chamini2** [comment]
https://github.com/jackc/pgx/issues/282

**Comment by danielnelson** [comment]
When the next pgx version is released we can update to use it.

**Comment by danielnelson** [comment]
We have updated to a newer version of pgx that has the upstream fix.  Can someone verify the fix using one the nightly builds?

**Comment by danielnelson** [comment]
@zargex Please let me know if you are still having issues with 1.5.0-rc1 or newer.
