### ISSUE TITLE
 influxdb url have query does not work with telegraf anymore

### ISSUE THREAD

**Issue by gavinzhou** [influxdata/telegraf#2891]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
 influxdb url have query does not work with telegraf anymore

### Relevant telegraf.conf:
```
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  # user = "$USER"
# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  #quiet = false
  logfile = ""
  hostname = "tele13-verup"
  omit_hostname = false


# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  urls = ["http://127.0.0.1/?test=testtest"] # UDP endpoint example
  database = "test" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "_write"
  password = "_write"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```

### System info:

Telegraf 1.3.0-1, InfluxDB 1.2.4-1 , nginx 1.10.0

### Steps to reproduce:
- Install telegraf+influxdb+nginx
- make a simple reverse proxy ( location / { proxy_pass http://influxdb:8086; } )
- start pumping metrics from telegraf (telegraf -> nginx -> influxdb)
- From this point, influxdb will be filled with broken, unreadable metrics. They looks like partially--
- written metrics, something like ??????st=some.of.host.i.monitor, or ???sk=sda1.

#### nginx access log

remove query `?test=testtest`
```
127.0.0.1 - _write [06/Jun/2017:09:32:34 +0000] "POST /query?q=CREATE+DATABASE+test HTTP/1.1" 403 132 "-" "-" "-"
127.0.0.1 - _write [06/Jun/2017:09:32:50 +0000] "POST /write?consistency=any&db=test HTTP/1.1" 204 0 "-" "-" "-"
```

**Comment by danielnelson** [comment]
Duplicate #2854

**Comment by gavinzhou** [comment]
## 
telegraf1.3 -> nginx(http) -> influxdb with auth is working

Telegraf 1.3 will remove the query part of the output.influxdb URLs
`  http://127.0.0.1/?test=testtest ` -> `http://127.0.0.1/`

1.2 no problem

### nginx.conf
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
    index   index.html index.htm;
    upstream backend {
            server 127.0.0.1:8086 fail_timeout=0;
    }
    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  localhost;
        root         /usr/share/nginx/html;
        include /etc/nginx/default.d/*.conf;
        location / {
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_pass http://backend;
        }

    }
}
```

### telegraf.conf
```
[global_tags]

[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  logfile = ""
  hostname = "tele13-verup"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://127.0.0.1/?test=testtest"] # UDP endpoint example
  database = "test"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "_write"
  password = "_write"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```

**Comment by danielnelson** [comment]
I don't think we added this feature on purpose before.  Can I ask what you are using these query parameters for?

**Comment by gavinzhou** [comment]
I added a query authentication to Nginx reverse proxy.
ex)
telegraf -> nginx -> influxdb

`https://<influxdb-endpoint>/?jwt=test.testtest.test`

This is not a smart.
maybe telegraf support to add custom header is a better

@danielnelson

**Comment by danielnelson** [comment]
What about using a client cert?
```
  ## Optional SSL Config
  # ssl_ca = "/etc/telegraf/ca.pem"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false
```

**Comment by danielnelson** [comment]
One other thing, the influxdb output uses basic auth for sending the contents of the username and password options.  This could conflict with the normal way of sending JWT authentication: `Authorization: Bearer <token>`

**Comment by gavinzhou** [comment]
Yes, nice idea
I add jwt auth to header, it working with telegraf1.3

**Comment by danielnelson** [comment]
Glad you got it working

**Comment by dylanmei** [comment]
> I add jwt auth to header

@gavinzhou Please share how you solved this. I don't see an option to add headers to the HTTP requests this plugin makes.

**Comment by gavinzhou** [comment]
@dylanmei 
I add jwt header to my plugin
https://github.com/orangesys/telegraf-output-orangesys
