### ISSUE TITLE
Redis plugin doesn't get Commandstats

### ISSUE THREAD

**Issue by marek-knappe** [influxdata/telegraf#2894]
## Feature Request

redis plugin is just doing 'Info' instead of 'INFO ALL' Which doesn't get Commandstats.

### Proposal:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/redis/redis.go#L135

Change INFO to INFO ALL 

### Current behavior:
No commandstats
### Desired behavior:

 Commandstats
cmdstat_get:calls=18708243,usec=81317810,usec_per_call=4.35
cmdstat_setnx:calls=12,usec=53,usec_per_call=4.42
cmdstat_setex:calls=1342574,usec=6917848,usec_per_call=5.15
cmdstat_del:calls=28393,usec=224118,usec_per_call=7.89
cmdstat_mget:calls=3136449,usec=24200188,usec_per_call=7.72
cmdstat_mset:calls=118074,usec=830158,usec_per_call=7.03
cmdstat_select:calls=252265,usec=371753,usec_per_call=1.47
cmdstat_expire:calls=524193,usec=811227,usec_per_call=1.55
cmdstat_info:calls=7734,usec=1128518,usec_per_call=145.92

### Use case: [Why is this important (helps with prioritizing requests)]
Easy change, adding more data to info, didn't see any problems with performence.

**Comment by danielnelson** [comment]
Sounds good, can you open a PR?

**Comment by marek-knappe** [comment]
Done.

**Comment by danielnelson** [comment]
Added in #5926
