### ISSUE TITLE
Inputs.win_perf_counters.object sends one counter per interval

### ISSUE THREAD

**Issue by bj2001holt** [influxdata/telegraf#2895]
## Bug report
When using an "inputs.win_perf_counters.object" where you are collecting multiple counters you will only see a single counter collected at each interval. For example, the PhysicalDisk Object collects 8 counters, however it only collects one of them per interval. This removes the ability to correlate performance data.

### Relevant telegraf.conf:

[agent]
  interval = "5s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  flush_interval = "5s"
  flush_jitter = "0s"

[[outputs.influxdb]]
  precision = "s"

  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
    ]
    Measurement = "win_diskio"

### System info:

Influx and Grafana on CentOS 7, telegraf on Windows Server 2012. Tested with telegraf version 1.3.1 and 1.0.0 beta 3. 

### Steps to reproduce:

1. Install telegraf on windows system using default win_perf_counters 
2. From Influx query
SELECT Current_Disk_Queue_Length as "C: Current Queue Length", Disk_Reads_persec as "C: Read/Sec", Disk_Writes_persec as "C: Writes/Sec" FROM "win_diskio" WHERE "host" = '<removed>' AND "instance" = '0 C:'

### Expected behavior:
All counters should be collected with every interval

### Actual behavior:
One counter is collected in each interval

**Comment by danielnelson** [comment]
Thanks @cdjc, you will need to sign the CLA still, can you open this as a pull request as well?

**Comment by cdjc** [comment]
I can sign the CLA, but I've never done a pull request before, so I'll have to figure it out. I did briefly look at what was required for a pull request, but it just seemed so much more complicated than posting a diff.

**Comment by danielnelson** [comment]
I can create the PR if your not setup for it.  If you have git running though can you create the diff using: `git format-patch 7e3991d`, this way the change is properly attributed.

**Comment by cdjc** [comment]
I have the patch file. Should I attach it here, or wait until you have set up the pull request?

**Comment by danielnelson** [comment]
Attach it here please

**Comment by cdjc** [comment]
[0001-Fix-win_perf_counters-to-collect-counters-per-instan.zip](https://github.com/influxdata/telegraf/files/1922294/0001-Fix-win_perf_counters-to-collect-counters-per-instan.zip)

Here it is (zipped, as .patch aren't allowed to be uploaded).
