### ISSUE TITLE
telegraf v1.3.1  [inputs.procstat] exe Can you place only one software? Can you place two?

### ISSUE THREAD

**Issue by zhengheyi** [influxdata/telegraf#2898]
[[inputs.procstat]]
#   ## Must specify one of: pid_file, exe, or pattern
#   ## PID file to monitor process
#   pid_file = "/var/run/nginx.pid"
#   ## executable name (ie, pgrep <exe>)

This position exe place two or more  software
For example, like this

    exe = "nginx","influxd"

but error,How to place more software?

#   ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
#   # pattern = "nginx"
#   ## user as argument for pgrep (ie, pgrep -u <user>)
#   # user = "nginx"

**Comment by danielnelson** [comment]
You can have two plugins:
```toml
[[inputs.procstat]]
  exe = "nginx"

[[inputs.procstat]]
  exe = "influxd"
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by AlarkaSanyal** [comment]
This doesn't seem to work for me. Once I manually added multiple ones, only the last one gets selected. Any other solution?

**Comment by danielnelson** [comment]
Just double checked this with 1.8.1 and it is working as expected.  Can you open a new issue with your full config and the output of `telegraf --test`?
