### ISSUE TITLE
Feature Request: Prometheus input change to allow labels to be converted to fields instead of tags

### ISSUE THREAD

**Issue by nwest1** [influxdata/telegraf#2903]
### Proposal: 
Add some configurable parsing to the prometheus input to allow labels to be coerced into fields.

### Current behavior:
All existing labels are saved as tags.
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/parser.go#L65

### Desired behavior:
Provide a list of labels names that instead of being converted to a tag, would be converted to a field.

### Use case: 
Due to some limitations of influxdb querying, it would be helpful to force some tags to be emitted as fields. The current workaround for this is to emit a separate measurement for each desired field.

### My question: 
Is there an appetite for this behavior? I'd be happy to open a PR for this if it's acceptable/desirable. 

Thanks!

**Comment by danielnelson** [comment]
> Due to some limitations of influxdb querying, it would be helpful to force some tags to be emitted as fields.

Can you add some examples here so that we can document the rationale for this?

**Comment by nwest1** [comment]
Sure, however this is based on my fairly limited experience with influx.

When I emit a measurement with fields, I'm able to do something like this (forgive the grafana variables..):
```
SELECT ("satisfied" + "tolerated"/2) / ("satisfied" + "tolerated" + "frustrated") FROM 
  (
  SELECT non_negative_derivative(mean("upstream_response.satisfied"), 1s) as "satisfied", 
  non_negative_derivative(mean("upstream_response.tolerated"), 1s) as "tolerated", 
  non_negative_derivative(mean("upstream_response.frustrated"), 1s) as "frustrated"
  FROM "sla" WHERE "host" =~ /proxy-$app_env/ 
  AND $timeFilter 
  GROUP BY time($__interval),*
  )
```
upstream is the measurement, and the satisfied/tolerated/etc are fields.

This is the best I've been able to come up with, but it returns separate series for each `level` tag and there's not a way to do math amongst the series results.
```
SELECT mean("counter") 
FROM "sla" 
WHERE $timeFilter 
GROUP BY time(10s), "level"
```

Hopefully that makes some sense. 

_Or if there's a way to do this with tags, which is more of an influx question and someone might know 😄_

**Comment by nwest1** [comment]
Thanks for the response - 

Which part do you mean by the upstream target?

I like the idea of a processor plugin - that makes more sense here.

I've been able to prove out that Kapacitor would do this, but that's more of an internal struggle rather than a technical one :)

**Comment by danielnelson** [comment]
> Which part do you mean by the upstream target?

The server that we are scraping (I think prometheus calls these exporters).

**Comment by nwest1** [comment]
It doesn't seem that prometheus has a concept of fields in this case - only tags.

**Comment by danielnelson** [comment]
Fields are the values, so I guess you would need multiple metrics, and then again this doesn't really work for InfluxQL:
```
upstream_response_satisfied{host="foo"} 1
upstream_response_tolerated{host="foo"} 1
upstream_response_frustrated{host="foo"} 1
```

**Comment by nwest1** [comment]
Ahh yeah- Sorry for the confusion. They end up as the `counter` field.

**Comment by nwest1** [comment]
Thanks for the quick responses!  I'll work towards the processor plugin idea.

**Comment by danielnelson** [comment]
If at some point you do get Kapacitor running, check out the [prometheus_metric_normalizer](https://github.com/influxdata/prometheus_metric_normalizer) repo for some examples of "fixing" up the data format for use with InfluxQL.  In particular this template is used:
https://github.com/influxdata/prometheus_metric_normalizer/blob/master/normalize-prometheus.tmpl.tick
