### ISSUE TITLE
can monitor docker healthcheck?

### ISSUE THREAD

**Issue by kingsqv** [influxdata/telegraf#2909]
can monitor docker healthcheck status?

**Comment by danielnelson** [comment]
If you referring to this then the answer is no, currently we don't have a way to monitor this that I know of. https://docs.docker.com/engine/reference/builder/#healthcheck

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by hflamboauto1** [comment]
@danielnelson  Cool it does not. Why it does not?

**Comment by hflamboauto1** [comment]
https://github.com/danielnelson Why not?

**Comment by danielnelson** [comment]
There isn't a reason, it just wasn't added, but I'll keep in mind the interest.  Also, we have this related pull request https://github.com/influxdata/telegraf/pull/3493

**Comment by hflamboauto1** [comment]
Thank you! Very appreciated.
