### ISSUE TITLE
MariaDB user statistics are different from Percona version

### ISSUE THREAD

**Issue by akrus** [influxdata/telegraf#2910]
### System info:

Telegraf 1.3.1, MariaDB 10.1.24

### Steps to reproduce:

1. Configure Telegraf with MySQL input plugin
2. Turn on gather_user_statistics in Telegraf and userstat in MariaDB

### Expected behavior:
Information should be collected.

### Actual behavior:
Error in logs:
Jun 12 14:43:10 db1 telegraf[14838]: 2017-06-12T13:43:10Z E! MySQL Error gathering user stats: Error 1054: Unknown column 'rows_fetched' in 'field list'
Jun 12 14:43:10 db1 telegraf[14838]: 2017-06-12T13:43:10Z E! Error in plugin [inputs.mysql]: sql: expected 26 destination arguments in Scan, not 23

### Additional info:
                USER: stats
          TOTAL_CONNECTIONS: 83
     CONCURRENT_CONNECTIONS: 0
             CONNECTED_TIME: 55
                  BUSY_TIME: 1.2070639999999992
                   CPU_TIME: 1.1825710000000003
             BYTES_RECEIVED: 82791
                 BYTES_SENT: 1655069
       BINLOG_BYTES_WRITTEN: 0
                  ROWS_READ: 0
                  ROWS_SENT: 2264
               ROWS_DELETED: 0
              ROWS_INSERTED: 0
               ROWS_UPDATED: 0
            SELECT_COMMANDS: 443
            UPDATE_COMMANDS: 0
             OTHER_COMMANDS: 0
        COMMIT_TRANSACTIONS: 0
      ROLLBACK_TRANSACTIONS: 0
         DENIED_CONNECTIONS: 27
           LOST_CONNECTIONS: 0
              ACCESS_DENIED: 6
              EMPTY_QUERIES: 117
      TOTAL_SSL_CONNECTIONS: 0
       MAX_STATEMENT_TIME_EXCEEDED: 0

**Comment by danielnelson** [comment]
@gioxchopper Do you know what version of the database you used when you wrote this?

**Comment by danielnelson** [comment]
https://www.percona.com/doc/percona-server/5.7/diagnostics/user_stats.html#information-schema-tables

**Comment by rashidmahmood** [comment]
I am struggling with the same issue, any idea how o resolve it ?

**Comment by danielnelson** [comment]
We probably should have a fallback query: optimistically try with the existing percona query and if it fails then try a mysql specific one.

**Comment by koma85** [comment]
I'm having this problem too, i cannot monitor any of my mariadb servers sadly.

**Comment by etiennecarriere** [comment]
I had this issue too so I propose a PR with a logic based on @danielnelson  proposal

**Comment by rmacian** [comment]
I am in 1.8.0 and still the same error occurs

**Comment by danielnelson** [comment]
@rmacian What version of MariaDB?

**Comment by rmacian** [comment]
@danielnelson is version 5.5.52

**Comment by danielnelson** [comment]
Can you open it as a new issue?

**Comment by rdxmb** [comment]
something similar: https://github.com/influxdata/telegraf/issues/5418
