### ISSUE TITLE
Kinesis output plugin does not work in govcloud

### ISSUE THREAD

**Issue by skroll** [influxdata/telegraf#2911]
### Relevant telegraf.conf:

```
[[outputs.kinesis]]
  region = "us-gov-west-1"
  streamname = "my-metrics-stream"
  partitionkey = "public"
  use_random_partitionkey = false
  data_format = "influx"
  debug = false
```

### System info:

Telegraf v1.3.0
Amazon Linux

### Steps to reproduce:

1. Set an kinesis output to write telegraf metrics.
2. Start telegraf.

### Expected behavior:

Telegraf to start and write metrics to the stream.

### Actual behavior:

Telegraf fails to start, prints out that the 'Endpoint' configuration is required since it cannot resolve it automatically.

### Additional info:

```
2017-06-12T15:27:19Z E! kinesis: Error in ListSteams API call : MissingEndpoint: 'Endpoint' configuration is required for this service
2017-06-12T15:27:19Z E! kinesis : You have configured a StreamName my-metrics-stream which does not exist. exiting.
```

**Comment by danielnelson** [comment]
Do you know if it works outside of the govcloud?

**Comment by skroll** [comment]
Yes it works fine. It appears that the go AWS SDK can't resolve the endpoint correctly when it's in govcloud, since they do not obey the same naming convention for the URLs.

**Comment by danielnelson** [comment]
That looks good.

**Comment by skroll** [comment]
Ok, actually, it's due to the version of the aws-sdk-go dependency.

The commit listed in Godeps was before Kinesis was added to govcloud, so it doesn't have a resolver for kinesis when in us-gov-west-1.

Newer versions of the SDK resolve this endpoint automatically.

**Comment by danielnelson** [comment]
Thanks, I'll update the dependency.

**Comment by danielnelson** [comment]
I updated the dependency, give it a spin if you can.

**Comment by skroll** [comment]
I'll fire it up tomorrow and report back.

**Comment by skroll** [comment]
Confirming that this works now, with the exact same config file I was using before.
