### ISSUE TITLE
Support for files with windows line endings

### ISSUE THREAD

**Issue by mantzas** [influxdata/telegraf#2915]
A process is creating line protocol entries in a log file which get parsed by Telegraf.
The file is then picked up by Telegraf using the tail input.
Unfortunately Telegraf complains about the timestamp being not in a correct format. 
After a  [community post](https://community.influxdata.com/t/telegraf-tail-input-file-encoding/1244/6) i have tried converting the file with UNIX line endings and it worked.

[ConsoleApp4.zip](https://github.com/influxdata/telegraf/files/1071562/ConsoleApp4.zip)

The goal of the project is to write points to standard log files (with line protocol format) and have Telegraf send them to AWS Kinesis and from there to Influx.

**Comment by danielnelson** [comment]
I opened this, but its only part of the problem: https://github.com/hpcloud/tail/issues/121
