### ISSUE TITLE
Ubuntu Telegraf binary dont have ipmi_sensor timeout parameter

### ISSUE THREAD

**Issue by ridhoyp** [influxdata/telegraf#2921]
telegraf version : 1.3.1-1
ubuntu : 14.0.4

root@monitoring:/etc/telegraf#  telegraf --config telegraf.conf -test
2017/06/14 13:08:20 E! Error parsing telegraf.conf, line 1250: field corresponding to `timeout' is not defined in `*ipmi_sensor.Ipmi'

can i get the new telegraf ubuntu package? because compile is so hard for me.

Regards,
RidhoYP

**Comment by danielnelson** [comment]
There is a nightly build of the master branch here: https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb
