### ISSUE TITLE
1.3.x Unable to write to InfluxDB

### ISSUE THREAD

**Issue by caseyaedwards** [influxdata/telegraf#2922]
## Bug report
After upgrading to 1.3.x some instances of telegraf fail to write to the InfluxDB server.
1.2.1 works fine in all cases.
```
Jun 14 09:56:32 rno03p1ignwb17 telegraf[20561]: 2017-06-14T09:56:32Z D! Output [influxdb] buffer fullness: 342 / 10000 metrics.
Jun 14 09:56:32 rno03p1ignwb17 telegraf[20561]: 2017-06-14T09:56:32Z E! InfluxDB Output Error: Response Error: Status Code [503], expected [204], [<nil>]
Jun 14 09:56:32 rno03p1ignwb17 telegraf[20561]: 2017-06-14T09:56:32Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```
I have ~100 servers on 1.3.x that work fine, the only difference is the servers that aren't working are farther away from the InfluxDB server, adding only about 10ms of latency.  Doubt that should be an issue but it's the only thing I can think of right now.  They were all deployed in an identical way from the same VM image, the only difference is the datacenter they're located in.

I enabled debug in telegraf.conf but the only relevant output are the errors above.  I enabled http logging in influxdb and only saw the agent that's failing post this once, with no subsequent attempts showing up in the influxdb logs.
`   1293 Jun 14 09:54:25 sjc04p1ifxmn01 influxd[28948]: [httpd] 10.60.4.116 - sa_nikola_wo [14/Jun/2017:09:54:25 +0000] "POST /query?q=CREATE+DATABASE+%22mps_influxdb%22 HTTP/1.1" 403 145 "-" "telegraf" 72e33358-50e7-11e7-83df-000000000000 1052`

### Relevant telegraf.conf:

```
[global_tags]
<snip>

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "2s"

  debug = true
  quiet = false
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  urls = ["<snip>"]
  database = "<snip>" # required
  precision = "s"
  retention_policy = "rp_mps_24w"
  write_consistency = "any"

  timeout = "5s"
  username = "<snip>"
  password = "<snip>"
  user_agent = "telegraf"
  udp_payload = 512

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################


[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]


[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.diskio]]
  skip_serial_number = true

[[inputs.kernel]]


[[inputs.mem]]


[[inputs.processes]]


[[inputs.swap]]


[[inputs.system]]


[[inputs.net]]
  fielddrop = ["icmp_*", "icmpmsg_*", "ip_*", "tcp_*", "udp_*", "udplite_*"]

[[inputs.netstat]]


[[inputs.sysstat]]
  sadc_path = "/usr/lib/sysstat/sadc"
  activities = ["DISK"]
  group = true
  [inputs.sysstat.options]
    -B = "paging"
    -d = "disk"             # requires DISK activity

[[inputs.nginx]]
  urls = ["http://127.0.0.1/status"]


```
### System info:
```
cedwards@rno03p1ignwb17:~$ uname -a
Linux rno03p1ignwb17 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
cedwards@rno03p1ignwb17:~$ telegraf --version
Telegraf v1.3.1 (git: release-1.3 f93615672b02a41d9bc867bd92bf31c1d777989b)
```
### Steps to reproduce:

Still attempting to reproduce it from a different location, so far no luck.

**Comment by danielnelson** [comment]
503 is Service Unavailable, who is responding with this error code?  Maybe you have a proxy between Telegraf and InfluxDB?

The 403 is not necessarily a problem as we try to create the database but it is not an error if it ends up not being allowed.

**Comment by caseyaedwards** [comment]
Thanks for your assistance on this Daniel.

No proxies anywhere, direct from server running Telegraf to InfluxDB.  If I downgrade to 1.2.1 it starts working without an issue.  As soon as I upgrade back to 1.3.x it stops working.

netstat shows it trying to connect to InfluxDB and InfluxDB does show it trying to connect in the logs so I'm assuming it's InfluxDB kicking back the 503.  I will do a packet capture and analyze a bit more to confirm though.

```
sudo netstat -tunp | grep 8086
tcp        0  58617 10.60.4.86:57098        10.33.158.176:8086      LAST_ACK    -
tcp        0  18513 10.60.4.86:56442        10.33.158.176:8086      LAST_ACK    -
tcp        0  31897 10.60.4.86:56654        10.33.158.176:8086      LAST_ACK    -
tcp        0  25196 10.60.4.86:56552        10.33.158.176:8086      LAST_ACK    -
tcp        0  38600 10.60.4.86:56756        10.33.158.176:8086      LAST_ACK    -
tcp        0  51970 10.60.4.86:56976        10.33.158.176:8086      LAST_ACK    -
```

**Comment by caseyaedwards** [comment]
Closing this out, looks like it got flagged by a proxy that I didn't know we had.  Thanks!

**Comment by danielnelson** [comment]
@caseyaedwards Do you know why the proxy had the issue with Telegraf 1.3?  Just want to make sure we aren't doing anything wrong on our end.

**Comment by caseyaedwards** [comment]
@danielnelson Still investigating. I don't control the filter so I'm waiting on another team to advise. I'll reply back once I have more information.

**Comment by senjirui** [comment]
tcp        0      0 192.168.49.251:40180    192.168.49.228:8086     ESTABLISHED 12732/telegraf

**Comment by danielnelson** [comment]
@senjirui This looks like an error where InfluxDB ran out of memory.
