### ISSUE TITLE
Filter Docker Stats Fields

### ISSUE THREAD

**Issue by Claywd** [influxdata/telegraf#2925]
When pulling stats from docker everything works amazingly but too much data is gathered and I want to be more conservative with the metrics I consolidate in my influxDB with regards to CPU and MEM (Especially mem). So I looked at the API and it looks like their is a way to filter out what fields the Docker engine-api returns when queried. 

Is it possible I am overlooking the configuration portion in telegraf.conf? Where can I possibly edit the JSON request to prototype a solution?

Do I sound way off base here? I apologize if I do.

**Comment by danielnelson** [comment]
Take a look at the [measurement filters](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering), you probably want to add some to the docker input configuration.

The best place for general questions is at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by Claywd** [comment]
Okay. so I tried adding 'fielddrop =["cpu"]' to the docker input hoping it would ignore that field of data from docker but it is still populating the measurement docker_container_cpu with a cpu column which is cpu core # that the container id is using. I really don't care what cpu its running on which is why I wanted to drop it. 

Good resource though, trying a few others still but no joy yet.

**Comment by danielnelson** [comment]
I looks like cpu is actually a tag on this measurement, you can use tagexclude to remove the tag from the point.

**Comment by Claywd** [comment]
Beautiful. This worked perfectly.

**Comment by Claywd** [comment]
One last question. Docker allows you to tag containers but I don't see telegraf pulling that tag and associating it with the container ID. Any chance I am overlooking it?
