### ISSUE TITLE
how can I write regex in telegraf.conf

### ISSUE THREAD

**Issue by japanbhatt** [influxdata/telegraf#2926]
[[inputs.jolokia.metrics]]
  name = "consumer_lag"
    mbean  = "kafka.server:type=FetcherLagMetrics,name=ConsumerLag,**clientId=([-.\w]+),topic=([-.\w]+),partition=([0-9]+)"**
    attribute = "Value"

is the jolokia metrics i want to measure which as a regex in bold above. this gives me parsing error.
how can I escape the ootb keywords and use regex here?

**Comment by danielnelson** [comment]
Here is the documentation about how to encode strings in toml https://github.com/toml-lang/toml#string.  Basically, you will want to use single quotes I think.

**Comment by ankujuniyal** [comment]
@japanbhatt japanbhatt Have you found the solution. I have monitoring the kafka same way. Or if you have other solution please share.
