### ISSUE TITLE
Query string not escaped in http_response input.

### ISSUE THREAD

**Issue by kotarusv** [influxdata/telegraf#2930]
## Bug

inputs.httpjson plugin not parsing ":' in the column correctly.

Configuration

[[inputs.httpjson]]
   name = "slb_stats"
   method = "GET"
   servers = [
      "http://<removed>/nitro/v1/stat/hanode",
      "http://<removed>/nitro/v1/stat/hanode",
      "http://<removed>/nitro/v1/stat/ns?args=detail:true",
      "http://<removed>/nitro/v1/stat/ns?args=detail:true"
   ]
      [inputs.httpjson.headers]
        Authorization = "<removed>"

Current Behaviour:

telegraf logs showing below error 

017-06-15T23:03:30Z E! Error in plugin [inputs.httpjson]: Response from url "http://<removed> /nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)

Desired Behaviour 
It should work without throwing 503 error

PS: inputs.http_response not throwing any error for same url 

[[inputs.http_response]]
  method = "GET"
  response_timeout = "10s"
  address = "http://<removed>/nitro/v1/stat/ns?args=detail:true"
    [inputs.http_response.headers]
      Authorization = "<removed>"

**Comment by danielnelson** [comment]
I don't see any differences that would cause a difference, what is the `http_response_code` from http_response?  What does the 599 response code mean?

**Comment by kotarusv** [comment]
http_response_code is 200 always and not seeing any complaints in telegraf logs. logs only complaining about [inputs.httpjson] plug-in

**Comment by kotarusv** [comment]
599 Network Connect Timeout Error. This status code is not specified in any RFCs, but is used by some HTTP proxies to signal a network connect timeout behind the proxy to a client in front of the proxy.

**Comment by danielnelson** [comment]
Try enabling `follow_redirects = true` in http_response, this will make it follow redirects like httpjson does by default.

**Comment by kotarusv** [comment]
I think you are getting confused here. I am having issue with httpjson not http_response. http_response is working fine for same url but httpjson throwing the error.

**Comment by danielnelson** [comment]
The reason I think http_response works while httpjson does not is that http_response is not following redirects.  We can test this by enabling this option, which, if my guess is correct, will cause http_response to fail with the 599 error.  If it continues to work, then the httpjson problem must be something else.

**Comment by kotarusv** [comment]
added follow_redirects = true to http_response, still don't see any issues with http_response. 


[[inputs.http_response]]
  method = "GET"
  response_timeout = "10s"
  follow_redirects = true
  address = "http://xyz.com/nitro/v1/stat/ns?args=detail:true"
    [inputs.http_response.headers]
      Authorization = ""

[[inputs.http_response]]
  method = "GET"
  response_timeout = "10s"
  follow_redirects = true
  address = "http://xyz.com/nitro/v1/stat/ns?args=detail:true"
    [inputs.http_response.headers]
      Authorization = ""

oc logs -f network-telegraf-agent-1-fqyxh
2017/06/16 19:19:48 I! Using config file: /etc/telegraf/telegraf.conf
2017-06-16T19:19:48Z I! Starting Telegraf (version 1.3.0)
2017-06-16T19:19:48Z I! Loaded outputs: influxdb influxdb
2017-06-16T19:19:48Z I! Loaded inputs: inputs.ping inputs.http_response inputs.http_response inputs.http_response inputs.http_response inputs.httpjson
2017-06-16T19:19:48Z I! Tags enabled: datacenter=xyz team=network type=netscaler
2017-06-16T19:19:48Z I! Agent Config: Interval:30s, Quiet:false, Hostname:"", Flush Interval:30s
2017-06-16T19:20:00Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)
2017-06-16T19:20:00Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)
2017-06-16T19:20:30Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)
2017-06-16T19:20:30Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)
2017-06-16T19:21:00Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)
2017-06-16T19:21:00Z E! Error in plugin [inputs.httpjson]: Response from url "http://xyz.com/nitro/v1/stat/ns?args=detail%3Atrue" has status code 599 (), expected 200 (OK)

**Comment by kotarusv** [comment]
curl -I -u user:pass http://xyz.com/nitro/v1/stat/ns?args=detail:true
HTTP/1.1 200 OK
Date: Fri, 16 Jun 2017 20:00:00 GMT
Server: Apache
Content-Type: text/html

i don't see this url making any redirects

**Comment by danielnelson** [comment]
I'm not sure then, can you try to track down where the 599 is coming from?

**Comment by kotarusv** [comment]
@danielnelson 
can  I put debug in telegraf config and test ?

**Comment by danielnelson** [comment]
Not sure what you mean.

**Comment by kotarusv** [comment]
@danielnelson 

OK i used tcpdump on host where telegraf is running and able to capture the request and response headers

why telegraf http_json plugin not sending exact url mentioned in server section rather adding "%3A" instead of ":"

GET /nitro/v1/stat/ns?args=detail%3Atrue HTTP/1.1
Host: xyz.com
User-Agent: Go-http-client/1.1
Authorization: Basic xxxxxx
Accept-Encoding: gzip


HTTP/1.1 599 Netscaler specific error
Date: Fri, 16 Jun 2017 20:31:00 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 80
Content-Type: application/json; charset=utf-8

**Comment by danielnelson** [comment]
Go seems to percent escape ":" in the query string, though technically it looks like it is allowed https://tools.ietf.org/html/rfc3986#appendix-A.  Python does this as well so it seems common, and it should be considered equivalent by the remote server.  I'm pretty sure `http_response` does the same.

**Comment by kotarusv** [comment]
@danielnelson 

http_response is not doing the same. to prove it, i removed all the configuration except below and ran the same tcpdump command 

[[inputs.http_response]]
  method = "GET"
  response_timeout = "10s"
  follow_redirects = true
  address = "http://xyz.com/nitro/v1/stat/ns?args=detail:true"
    [inputs.http_response.headers]
      Authorization = "Basic xxxxx"

GET /nitro/v1/stat/ns?args=detail:true HTTP/1.1
Host: xyz.com
User-Agent: Go-http-client/1.1
Authorization: Basic xxxxxx
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Fri, 16 Jun 2017 21:51:00 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: 608
Content-Type: application/json; charset=utf-8

**Comment by kotarusv** [comment]
removed http_response and just added one http_json server

[[inputs.httpjson]]
   name = "slb_stats"
   method = "GET"
   servers = [
      "http://xyz.com/nitro/v1/stat/ns?args=detail:true"
   ]
      [inputs.httpjson.headers]
        Authorization = "Basic xxxxxxx"

GET /nitro/v1/stat/ns?args=detail%3Atrue HTTP/1.1
Host: xyz.com
User-Agent: Go-http-client/1.1
Authorization: Basic xxxxxxx
Accept-Encoding: gzip

HTTP/1.1 599 Netscaler specific error
Date: Fri, 16 Jun 2017 21:55:00 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 80
Content-Type: application/json; charset=utf-8

**Comment by danielnelson** [comment]
You are right, here is where we reencode the query to mix in items from the parameters option: https://github.com/influxdata/telegraf/blob/736322dfc98da1e85461a89e4e53629977664fa7/plugins/inputs/httpjson/httpjson.go#L227

So this seems like it is actually a bug in http_response, since we ought to be encoding the query string but it doesn't appear that we are.

**Comment by kotarusv** [comment]
so where we left? any fix i can proceed or struck at this point?

**Comment by danielnelson** [comment]
The fix for this issue should be ensuring that http_response only queries valid URLs/IRLs.  The 599 error in httpjson you will have to solve on your side.

**Comment by danielnelson** [comment]
Thanks for tracking this one down, saved me a bunch of time.

**Comment by danielnelson** [comment]
I've decided not to address this issue, while this means Telegraf could send a request with an invalid query string, such as `?a%GG`, blocking this would make it impossible to use a strictly invalid url which may be something a user wants to do http response.
