### ISSUE TITLE
input.procstat No information gathered about cnode_num_fds,cnode_read_bytes,cnode_write_bytes,cnode_read_count,cnode_write_count,Why?

### ISSUE THREAD

**Issue by zhengheyi** [influxdata/telegraf#2931]
My configuration
```
 [[inputs.procstat]]
#   ## Must specify one of: pid_file, exe, or pattern
#   ## PID file to monitor process
#   pid_file = "/var/run/nginx.pid"
#   ## executable name (ie, pgrep <exe>)
    exe = "cnode"
#   ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
#   # pattern = "nginx"
#   ## user as argument for pgrep (ie, pgrep -u <user>)
#   # user = "nginx"
#
#   ## override for process_name
#   ## This is optional; default is sourced from /proc/<pid>/status
#   # process_name = "bar"
#   ## Field name prefix
   prefix = "cnode"
#   ## comment this out if you want raw cpu_time stats
#   fielddrop = ["cpu_time_*"]
#   ## This is optional; moves pid into a tag instead of a field
#   pid_tag = false
```

my test ,but No information gathered about cnode_num_fds,cnode_read_bytes,cnode_write_bytes,cnode_read_count,cnode_write_count   why?
~$ telegraf  -config /etc/telegraf/telegraf.conf -input-filter procstat -test
* Plugin: inputs.procstat, Collection 1
> procstat,exe=cnode,process_name=ctp_trade_cnode,host=lknode52 cnode_num_threads=3i,cnode_memory_rss=37904384i,cnode_cpu_time_soft_irq=0,cnode_cpu_time_steal=0,cnode_cpu_time_stolen=0,cnode_memory_vms=196784128i,cnode_voluntary_context_switches=35606i,cnode_involuntary_context_switches=4i,cnode_cpu_time_nice=0,cnode_memory_swap=0i,cnode_cpu_time_system=4389.83,cnode_cpu_time_iowait=0,cnode_cpu_time_guest_nice=0,cnode_cpu_time_irq=0,cnode_cpu_time_guest=0,pid=28248i,cnode_cpu_time_user=2797.72,cnode_cpu_time_idle=0 1497603876000000000
* Plugin: inputs.procstat, Collection 2
> procstat,process_name=ctp_trade_cnode,host=lknode52,exe=cnode cnode_cpu_time_irq=0,cnode_memory_rss=37904384i,cnode_cpu_time_user=2797.73,cnode_cpu_time_nice=0,cnode_cpu_usage=3.935069813487539,cnode_cpu_time_system=4389.84,cnode_cpu_time_steal=0,cnode_cpu_time_soft_irq=0,cnode_cpu_time_stolen=0,cnode_cpu_time_guest=0,cnode_cpu_time_guest_nice=0,cnode_memory_vms=196784128i,cnode_memory_swap=0i,cnode_num_threads=3i,cnode_voluntary_context_switches=35606i,cnode_cpu_time_idle=0,cnode_cpu_time_iowait=0,pid=28248i,cnode_involuntary_context_switches=4i 1497603876000000000

**Comment by danielnelson** [comment]
This is very likely to be caused by insufficient permissions.  the read/write counts come from `/proc/$pid/io` and the num_fds comes from `/proc/$pid/fd`.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
