### ISSUE TITLE
Sporadic Telegraf Metrics in Graphite.

### ISSUE THREAD

**Issue by Pheels** [influxdata/telegraf#2941]
Firstly, I can not be 100% sure that this issue lies with Telegraf, however I feel I have exhausted my options regarding Graphite.

I am sending telegraf metrics from a host of machines across various datacentres located all over the world. These are not the only metrics I send, however they are the only metrics that appear "sporadic" (for lack of a better word). An example of what I mean can be seen below - these two servers are located in the same data centre, with the same telegraf config, same graphite storage retention, similar usage, same graphite machine etc. The interesting thing is that the majority of my machines are sending their metrics in this sporadic manor. The images are of a bad machine (there was a long period of empty metrics after this), and another, healthier machine during the same period.

![screen shot 2017-06-20 at 12 08 19](https://user-images.githubusercontent.com/9592949/27330414-337f07e2-55b1-11e7-9a29-cc2abc588504.png)

![screen shot 2017-06-20 at 12 10 31](https://user-images.githubusercontent.com/9592949/27330486-7df6943e-55b1-11e7-8e23-d18edf82d0aa.png)

I am at a loss as to what could be causing this now. We use Telegraf v1.2.1. We've had some issues in the past where two telegraf processes were running at once, although that's not the case here. Any suggestions would be great, thanks.

**Comment by danielnelson** [comment]
Can you ask for help over at the [InfluxData Community](https://community.influxdata.com) site?  You should also include the relevant parts of your configuration file.  Also, check to see if anything interesting is in your logfile.
