### ISSUE TITLE
master branch - git describe states 1.2.0-rc1-270-gdcdcb70

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#2942]
The master branch of the latest commits says the version as 1.2.0-rc1
My understanding was the master branch is the latest commit always and may have the version number that will be targeted for next release

**Comment by danielnelson** [comment]
Thanks for opening this ticket.  This is caused by having a tag on the master branch history, we should probably remove the autodetection of branch or just remove this field altogether.

**Comment by sureshsubramaniam** [comment]
makes sense +1 for having the unreleased version number in master branch
