### ISSUE TITLE
Input plugins errors are sent to output

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#2944]
### Proposal:
When input plugin encounters an error, the error is sent to output to be processed accordingly.

### Current behavior:
The errors are logged.
### Desired behavior:
The errors are sent to output.
### Use case: [Why is this important (helps with prioritizing requests)]
It will be easy to monitor without checking telegraf's log. It will simplify alerting.

**Comment by danielnelson** [comment]
Sorry about the slow response, this can somewhat be done by enabling the internal plugin.  Give it a shot and let me know if this is sufficient or how you think we could improve it.

**Comment by danielnelson** [comment]
Please reopen if internal plugin does not work for your use case.
