### ISSUE TITLE
Type loss and metric rename in prometheus input → prometheus output

### ISSUE THREAD

**Issue by zagy** [influxdata/telegraf#2950]
## Bug report

Loading the data with telegraf Prometheus input and exporting it with the prometheus output (e.g. haproxy-exporter --[prometheus protocol]--telegraf---[prometheus protocol]---…) yields

* Metric is being renamed to `*_<type>` (e.g. `haproxy_up` becomes `haproxy_up_gauge`)
* Type becomes `untyped`

### Relevant telegraf.conf:

```
[inputs.prometheus]
urls = ["http://localhost:9127/metrics"]

[outputs.prometheus_client]
listen = "172.22.49.216:9126"
```

### System info:

Tested in 

* 1.2.1 
* 1.3.0

### Steps to reproduce:

1. Setup https://github.com/prometheus/haproxy_exporter
2. Point telegraf to haproxy_export (prometheus input)
3. Setup telegraf output `prometheus_client`
4. See that metrics are renamed after they come out of telegraf.

### Expected behavior:

* No rename of metric 
* Keep type

### Actual behavior:

* Metric is being renamed to `*_<type>` (e.g. `haproxy_up` becomes `haproxy_up_gauge`)
* Type becomes `untyped`

haproxy exporter gives:

```
# HELP haproxy_up Was the last scrape of haproxy successful.
# TYPE haproxy_up gauge
haproxy_up 1
```

Telegraf exports:

```
# HELP haproxy_up_gauge Telegraf collected metric
# TYPE haproxy_up_gauge untyped
haproxy_up_gauge{host="hostname", url="http://localhost:9127/metrics"} 1
```

**Comment by spowser** [comment]
Can confirm this issue.  Any metrics that traverse through telegraf are losing their metric types.

**Comment by dzr0001** [comment]
I can confirm this is present in 1.4.1. I think the offending line is found [here](https://github.com/influxdata/telegraf/blob/cd1791494ae82c6c77255795a6bbf3e6d9d3802f/plugins/outputs/prometheus_client/prometheus_client.go#L245)

```			// Special handling of value field; supports passthrough from
			// the prometheus input.
			var mname string
			if fn == "value" {
				mname = sanitize(point.Name())
			} else {
				mname = sanitize(fmt.Sprintf("%s_%s", point.Name(), fn))
                        }
```

**Comment by dzr0001** [comment]
After thinking about this a little further, I think this would have to be addressed on the input and not the output. Trying to address this on the output would be difficult, as quantile types would have to construct new quantile labels and use the field names as the label value.

For any other single value metric, the field name should get used as the type.

**Comment by spowser** [comment]
Will this be added to the 1.5 milestone?

**Comment by jdoupe** [comment]
This is *mostly* addressed by https://github.com/influxdata/telegraf/pull/3337
