### ISSUE TITLE
Telegraf + prometheus-client ; no metrics created or scraped

### ISSUE THREAD

**Issue by nitin02** [influxdata/telegraf#2953]
I've set up the telegraf agent with the docker version,

`docker run -v /home/user/telegraf.conf:/etc/telegraf/telegraf.conf:ro -v /var/run/docker.sock:/var/run/docker.sock -v /var/run/utmp:/var/run/utmp telegraf:alpine`

It is ideally the default configuration available with the prometheus-client as output, listening on port 9126.

I've been using Prometheus for quite some time now and it works without any issues. However, with telegraf, I cannot find any of telegraf metrics created or being scraped.

Note that even Prometheus is running with the docker image available with configuration altered to scrape the instance telegraf in running in, on port 9126.

I cannot find any log errors on both the prometheus server and the telegraf agent.

Is there a  configuration I'm missing or some other issue with telegraf?

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

Please make sure to include your telegraf configuration as well as the output of the prometheus_client response.
