### ISSUE TITLE
More fine-grained example config

### ISSUE THREAD

**Issue by smyrman** [influxdata/telegraf#2955]
### Proposal:

I propose that there should be a way, e.g. via the `telegraf config` command, to get a shorter example config, only including example config for a sub-set of (input and output) plugins and/or other config sections.

There are probably multiple ways to do this, but the simplest might be let the `config` command respect and understand the existing `--input-filter` and `--output-filter` options. If any og these filters are given, the respective section should be filtered so that only the SampleConfig for those plugins are printed to stdout. This is also my preferred solution, aa this will give you a _complete_ example config.

Another alternative could be to allow one or more optional parameter to the `config` command, that limits the example to one or more section. E.g. `telegraf config agent` (only `[[agent]]` section),  `telegraf config inputs` (all innput plugins only) , `telgrad config inputs.webhooks` (only `[[inputs.webhooks]]` section), or optionally maybe a combination ala `telegraf config general agent inputs.webhooks outputs.influxdb`.

### Current behavior:

`telegraf config` prints a config to stdout containing (mostly commented out) example config for all supported plugins.

### Desired behavior:

`telegraf config` should support options to filter down the number of plugins and/or config sections that will be included in the example config printed to stdout.

### Use case: [Why is this important (helps with prioritizing requests)]

As more and more plugins have been added, the example config file is growing ever larger and harder to navigate. When maintaining multiple telegraf instances, e.g. via docker or in the cloud, having a faster way of generating a filtered-down example config would speed up the development process by reducing time spent on either scrolling or information lookup for a given version of telegraf.

 Since there are more input and output plugins than processor- and aggregate plugins, and since there are not to many options in the agent- and general config, only adding support to filter example config for the input- and output _plugins_ might give the highest value for effort.

**Comment by danielnelson** [comment]
I think your preferred solution is already available, if you run `telegraf --input-filter cpu --output-filter none config` you get the agent section with only the cpu input, keep in mind that the config coming at the end is important (which is a bug I think).

But I would also like to come up with a good way to get only a single input/output without the agent config, which would be useful for people using the `--config-directory`.  Maybe with just one of `agent`, `inputs`, `outputs`. For example, `telegraf --input-filter cpu config inputs`.

**Comment by smyrman** [comment]
You are right, it's even stated in the README 😳

I don't know how I missed this when I was running the command in the terminal... I guess maybe I did add the options at the end.

> But I would also like to come up with a good way to get only a single input/output without the agent config

It's not very important for me, or art least not her, but it sounds quite reasonable for the use-case you describe.

One implementation idea _could_ be to add a config command specific option "--sections", defaulting to "general:agent:inputs:outputs".

**Comment by danielnelson** [comment]
You can also use the `telegraf --usage cpu` to get a specific plugin, but it prints both plugins when there are inputs and outputs with the same name.

**Comment by ssoroka** [comment]
I think since the original request is handled, this is worth closing. @danielnelson can optionally open a new issue for his proposed solution.
I can still do `telegraf --input-filter cpu --output-filter none --processor-filter none --aggregator-filter none config` and get a pretty tidy config.

**Comment by danielnelson** [comment]
These days you can also combine these with `--section-filter` to generate only specific sections of the configuration:
```
  --section-filter               filter config sections to output, separator is :
                                 Valid values are 'agent', 'global_tags', 'outputs',
                                 'processors', 'aggregators' and 'inputs'
```
