### ISSUE TITLE
Jolokia plugin collects List<Map> metrics

### ISSUE THREAD

**Issue by 0x0010** [influxdata/telegraf#2956]
I have a jmx bean which exposes all connection pools stats, like this
````
"value":[{"idleConnections":"1","activeConnections":"0","totalConnections":"1","connPoolName":"group_1.inst2"},{"idleConnections":"1","activeConnections":"0","totalConnections":"1","connPoolName":"group_1.inst1"}]
````
Can jolokia plugin parse this result to two rows ?

**Comment by danielnelson** [comment]
I don't think the current jolokia plugin can parse these correctly.

@dylanmei Is this possible with the jolokia2 plugin?

**Comment by dylanmei** [comment]
Not today.
1. The array would need to be translated somehow. Maybe `value_0_idleConnections`
2. The field values would come out as strings -- probably not what you want. We can consider handling 1. but 2. leads me to think this bean needs some more consideration. Is this from open-source software?
