### ISSUE TITLE
elasticsearch plugin with prometheus_client output wont show cluster_health status

### ISSUE THREAD

**Issue by sbadia** [influxdata/telegraf#2957]
### Relevant telegraf.conf:
```
[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "influx"
[[outputs.prometheus_client]]
  listen = ":9126"
  expiration_interval = "60s"
[[inputs.elasticsearch]]
  servers = ["http://elastic:changeme@172.17.0.2:9200"]
  http_timeout = "5s"
  local = false
  cluster_health = true
  cluster_stats = false
```

### System info:

* `Telegraf v1.3.2 (git: release-1.3 0f419e9a0d294ab4d68bb7d1c6b28e60d362239b)`
* `Ubuntu 16.04 LTS`

### Steps to reproduce:

1. Setup a test elasticsearch host `docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.4.2`
2. Run telegaf with elasticsearch config `./telegraf --config telegraf.conf`
3. And take a look on prom output `curl -s http://localhost:9126/metrics | grep health`
```
elasticsearch_cluster_health_active_primary_shards{host="baloo",name="docker_cluster"} 6
elasticsearch_cluster_health_active_shards{host="baloo",name="docker_cluster"} 6
elasticsearch_cluster_health_initializing_shards{host="baloo",name="docker_cluster"} 0
elasticsearch_cluster_health_number_of_data_nodes{host="baloo",name="docker_cluster"} 1
elasticsearch_cluster_health_number_of_nodes{host="baloo",name="docker_cluster"} 1
elasticsearch_cluster_health_relocating_shards{host="baloo",name="docker_cluster"} 0
elasticsearch_cluster_health_unassigned_shards{host="baloo",name="docker_cluster"} 6
```
4. Versus influxdb file based output `cat /tmp/metrics.out | grep health`
```
elasticsearch_cluster_health,host=baloo,name=docker-cluster active_primary_shards=6i,active_shards=6i,timed_out=false,number_of_nodes=1i,relocating_shards=0i,initializing_shards=0i,unassigned_shards=6i,status="yellow",number_of_data_nodes=1i 1498217670000000000
elasticsearch_cluster_health,name=docker-cluster,host=baloo initializing_shards=0i,status="yellow",number_of_nodes=1i,number_of_data_nodes=1i,relocating_shards=0i,timed_out=false,active_primary_shards=6i,active_shards=6i,unassigned_shards=6i 1498217680000000000
```

### Expected behavior:

cluster status should be shown as tags or value ?

### Actual behavior:

cluster / indices status are not exported with prometheus output.

### Additional info:

* https://github.com/influxdata/telegraf/issues/2791
* https://github.com/influxdata/telegraf/issues/2928

**Comment by danielnelson** [comment]
As I'm sure you know from the linked issues, this is because status is a string value which we do not currently output in the prometheus_client output.

There are a couple things which I think will address this:
- Add a mapping processor as described in #2791 
- Add a processor that can promote fields to tags
- Add an option to the prometheus_client output to enable emitting string fields as labels.
