### ISSUE TITLE
Unable to connect Rethinkdb 2.3.5 for monitoring

### ISSUE THREAD

**Issue by vodolaz095** [influxdata/telegraf#2958]
### Relevant telegraf.conf:
```
[[inputs.rethinkdb]]
  servers = ["rethinkdb://rethinkdb_username1:rethinkdb_password1@127.0.0.1:28015"]
```
### System info:

Telegraf: telegraf-1.2.1.x86_64.rpm
Rethinkdb: 2.3.5
Operating system: Fedora 25 linux

### Steps to reproduce:
Tested on fedora 25 linux

1. Install rethinkdb of 2.3.5 version via RPM (https://rethinkdb.com/docs/install/fedora/)
2. Set authorization - username and password https://rethinkdb.com/docs/permissions-and-accounts/
3. Install telegraf with rethinkdb extraction config like i mentioned above
4. `systemctl start telegraf`
5. `# journalctl -u telegraf -e`

### Expected behavior:

Telegraf connects to rethinkdb and gets data

### Actual behavior:
Telegraf unable to connect to rethinkdb.
Telegraf sends this to `journalctl -u telegraf -e` and rethinkdb is not monitored

```
Jun 23 12:08:10 rethinkdb-cluster-1.localdomain telegraf[27886]: 2017-06-23T12:08:10Z E! ERROR in input [inputs.rethinkdb]: Unable to connect to RethinkDB, no connections were made when creating the session
Jun 23 12:08:10 rethinkdb-cluster-1.localdomain telegraf[27886]: time="2017-06-23T12:08:10Z" level=warning msg="Error creating connection: gorethink: Server dropped connection with message: \"ERROR: Incorrect authorization key.\""
```

### Additional info:
I have fixed it by this PR
https://github.com/influxdata/telegraf/pull/2959

## Feature Request
Please, help me monitor rethinkdb, fix the issue with connections!

### Proposal:
Use latest RethinkDB library with proper authorization

### Current behavior:
Fails to connect

### Desired behavior:
Connects and monitors

### Use case: 
I want to use your telegraf system to monitor our rethinkdb 2.3.5 cluster, but it simply don't works.

**Comment by vodolaz095** [comment]
I created this pr #2963

**Comment by danielnelson** [comment]
Will be in 1.4.0
