### ISSUE TITLE
unable to parse and store the json data Influxdb !

### ISSUE THREAD

**Issue by sivapavi** [influxdata/telegraf#2962]
My data is in JSON format which is being fetched using boomcatch unmapped mapper . I have to write that to influxdb. But telegraf throwing the below error.

> E! Error in plugin [inputs.tail]: E! Malformed log line in /var/log/boomcatch/boomcatch-data.json: [{"browser":{"name":"Chrome","version":"58"},"os":"Windows 7"}], Error:  metric parsing error, reason: [missing tag value], buffer: [{"browser":{"name":"Chrome","version":"58"},"os":"Windows 7"}], index: [43]

Please find my telegraf configuration file .
 Relevant telegraf.conf:

> [[outputs.influxdb]]
>  
>   urls = ["http://localhost:8086"] # required
>   database = "telegraf" 
>   precision = "s"
>    timeout = "10s"
> 

> [[inputs.tail]]
> files = ["/var/log/boomcatch/boomcatch-data.json"] 
>  from_beginning = true
>  pipe = false
>    data_format = "influx"
>    tag_keys = [
>    "browser",
>     "os"
>     ]

### System info:

> My telegraf version is -  Telegraf v1.3.1
> My Operating system is - ubuntu

###Sample JSON file which am using 
> {"browser":{"name":"Chrome","version":"58"},"os":"Windows 7"}

Please forgive me if i might have missed-out anything in telegraf conf.I wold like to hear from you guys about this issue .

Kindly help me to fix this !

Thanks
Siva.P

**Comment by danielnelson** [comment]
First, you will want to use `data_format = "json"` for parsing JSON files.   The other issue is that the [JSON input format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json) only converts numeric types to fields, and you must have at least one field.

For example, something like this would be acceptable:
```
{"browser":{"name":"Chrome","version":"58"},"os":"Windows 7", "value": 42}
```
and creates a point like:
```
tail,os=Windows\ 7,host=loaner value=42 1498501406636028237
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
