### ISSUE TITLE
logparser plugin stops parsing file that was rotated

### ISSUE THREAD

**Issue by dirkaholic** [influxdata/telegraf#2967]
## Bug report

I noticed that the logparser plugin stopped sending metrics a few times for me when my logs are rotated. I use the plugin for monitoring nginx logs. I have configured 2 files where nginx usually writes access logs (see config section). When these files are rotated usually the other file is used for wrtiting the logs. The test shows that logs written into the second file are still recognized but when you try to write into the re-created first file again no metrics are sent.

I opened a pull request with the test showing the issue here influxdata/telegraf#2965. The interesting part is that sometimes this test passes but currently on circleci it also shows the failure that I get most of the time.

### Relevant telegraf.conf:

```
# Stream and parse nginx log file(s).
[[inputs.logparser]]
  ## Log files to parse.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   /var/log/**.log     -> recursively find all .log files in /var/log
  ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
  ##   /var/log/apache.log -> only tail the apache log file
  files = ["/var/log/nginx/access.log", "/var/log/nginx/access.log.1"]
  ## Read file from beginning.
  from_beginning = false

  ## Parse logstash-style "grok" patterns:
  ##   Telegraf built-in parsing patterns: https://goo.gl/dkay10
  [inputs.logparser.grok]
    ## This is a list of patterns to check the given log file(s) for.
    ## Note that adding patterns here increases processing time. The most
    ## efficient configuration is to have one pattern per logparser.
    ## Other common built-in patterns are:
    ##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
    ##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
    patterns = ["%{CUSTOM_LOG}"]
    custom_patterns = '''
CUSTOM_LOG %{HOSTNAME:nginx_virtual_host:tag} %{COMBINED_LOG_FORMAT} %{NUMBER:request_time:float} %{NUMBER:upstream_response_time:float}
'''

    ## Name of the outputted measurement name.
    measurement = "nginx_access_log"
```

### System info:

telegraf 1.3.2
Ubuntu 14.04

### Steps to reproduce:

Run tests several times

### Expected behavior:

Tests pass.

### Actual behavior:

Tests fail.

**Comment by danielnelson** [comment]
Thanks for the testcase, do you think this is related to #2847 at all?

**Comment by dirkaholic** [comment]
Yes, I think it is related to influxdata/telegraf#2847

**Comment by danielnelson** [comment]
I'm going to merge these issues then.
