### ISSUE TITLE
Build on Windows: linux_sysctl_fs.go:87: undefined: GetHostProc

### ISSUE THREAD

**Issue by MichaelS11** [influxdata/telegraf#2971]
## Bug report

Build on Windows: linux_sysctl_fs.go:87: undefined: GetHostProc

### System info:

Pulling from master
Windows 10 64 bit
Eclipse Version: Neon.1 Release (4.6.1)

### Steps to reproduce:

1. Pull from master
2. Build on windows (not using make)

### Expected behavior:

Build without error

### Actual behavior:

Build error:
github.com\influxdata\telegraf\plugins\inputs\system\linux_sysctl_fs.go:87: undefined: GetHostProc

### Additional info:

Added 
// +build !windows
to the top of linux_sysctl_fs.go file and that seemed to fix the issue. Not sure if that is the correct solution.

**Comment by danielnelson** [comment]
Thanks for the report, it should build now
