### ISSUE TITLE
[Bug] Windows performance counter - Win process fails to retrieve multiple process with the same name

### ISSUE THREAD

**Issue by dudusakharovich** [influxdata/telegraf#2977]
### System info:

Telegraf version - 1.3.2
OS - Windows server 2012 R2

### Steps to reproduce:
I've added windows performance input of type windows process to the telegraf configuration.

### Expected behavior:
When trying to display stats for process of type "w3wp" I should see stats for 3 processes of "w3wp" kind.

### Actual behavior:
I can see stats only for 1 "w3wp" process instead of 3.

### Additional info:
This is the telegraf configuration input:
[[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set"]
    Instances = ["*"]
    Measurement = "win_proc"
    IncludeTotal=true #Set to true to include _Total instance when querying for all (*).

As seen in the screen shot there are 3 instances of "w3wp" process:

![image](https://user-images.githubusercontent.com/24862189/27769941-900666b8-5f3e-11e7-9837-56bd3cefcaee.png)

In grafana I can only see stats for only 1 "w3wp" process instead of 3:

![image](https://user-images.githubusercontent.com/24862189/27769963-f4ef45fe-5f3e-11e7-8cc2-9c80c708442f.png)

**Comment by willemdh** [comment]
Seems the same problem as https://github.com/influxdata/telegraf/issues/2879

I hope this gets fixed soon.

**Comment by danielnelson** [comment]
Closing in favor of #2879
