### ISSUE TITLE
Nightly builds are not working

### ISSUE THREAD

**Issue by garceri** [influxdata/telegraf#2979]
Where can i find the .deb package for the nightly builds, none of the "usual" locations seem to work..

**Comment by danielnelson** [comment]
Here is the nightly build link, however they are not currently working.  I'll update this issue when it is fixed.  https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb

**Comment by danielnelson** [comment]
Nightly builds are working again, I added a list of links to the README: https://github.com/influxdata/telegraf#nightly-builds
