### ISSUE TITLE
OpenTSDB Output Plugin "debug" only works when used with HTTP

### ISSUE THREAD

**Issue by marcphilipp** [influxdata/telegraf#2980]
### Relevant telegraf.conf:

```
[[outputs.opentsdb]]
  ## DNS name of the OpenTSDB server
  ## Using "opentsdb.example.com" or "tcp://opentsdb.example.com" will use the
  ## telnet API. "http://opentsdb.example.com" will use the Http API.
  host = "tcp://127.0.0.1"

  ## Port of the OpenTSDB server
  port = 4242

  ## Debug true - Prints OpenTSDB communication
  debug = true
```

### System info:

Telegraf 1.3.1 official Docker image

### Steps to reproduce:

1. Use the above config
2. Look at the log
3. No debug output from opentsdb

### Expected behavior:

Setting `debug` to `true` prints debug output regardless of whether the Telnet or HTTP API is used.

### Actual behavior:

Setting `debug` to `true` does not print debug output when used with a "tcp://..." URI.

**Comment by powersj** [comment]
Hi,

Sorry, no one has responded to this bug in the past. When you say you are not seeing debug output with TCP what messages are not appearing that you see with HTTP?

Thanks!

**Comment by marcphilipp** [comment]
@powersj Thanks for your response! It's been a while and I honestly don't remember.
