### ISSUE TITLE
[Bug] Plugin redis doesn't get field redis_version

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#2982]
Telegraf version: 1.3.3
```
Telegraf v1.3.3 (git: release-1.3 46db92aad3e68af04f1732598ac89f6b9b11daf8)
```
Redis version: 3.0.7
```
Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=49ffd7ce21c94625
```
### Expected behavior:
Plugin redis gets redis_version
### Actual behavior:
```
> select clients,redis_version from redis;
name: redis
time                clients redis_version
----                ------- -------------
1499214120000000000 10
1499214180000000000 10
```

redis.conf
```
[[inputs.redis]]
  servers = ["tcp://localhost:6379"]
```

Redis info:
```
telnet localhost 6379
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO
$2057
# Server
redis_version:3.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:49ffd7ce21c94625
redis_mode:standalone
os:Linux 3.2.0-29-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.6.3
process_id:5175
run_id:961003d4e75eabf5946f6fbb2f1a9cf8fe871a93
tcp_port:6379
uptime_in_seconds:73747
uptime_in_days:0
hz:10
lru_clock:6042297
config_file:/etc/redis/redis.conf
```

**Comment by danielnelson** [comment]
Only the `lru_clock` and `uptime_in_seconds` fields are collected within the Server section.  https://github.com/influxdata/telegraf/blob/master/plugins/inputs/redis/README.md#measurements--fields

This was added in https://github.com/influxdata/telegraf/pull/1689

Can you write a few sentences about why you need this field so that we will have rationale documented?

**Comment by wei-hai** [comment]
it used to have field `redis_version` before I upgraded redis from 2.x to 3.x, so I was wondering if it was a bug.

**Comment by danielnelson** [comment]
No, it is excluded on purpose as you can see here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/redis/redis.go#L186

**Comment by wei-hai** [comment]
then it might be a real bug, I am pretty sure with redis 2.x telegraf fetches `redis_version` otherwise I wouldn't have opened this ticket. Do you mind adding `redis_version` back?

**Comment by danielnelson** [comment]
Maybe with an older Telegraf version we had this field, I don't see any reason we shouldn't add it in though.
