### ISSUE TITLE
Two duplicate metrics values from a single aerospike node 

### ISSUE THREAD

**Issue by mrchang7** [influxdata/telegraf#2983]
I'm using the following versions on my RH7.2. 

telegraf-1.3.2-1.x86_64.rpm
aerospike-server-enterprise-3.10.1

In my environment, I installed telegraf on two aerospike nodes of a cluster. telegraf collects aerospike metrics and sends them via udp (with json format) to another node, where logstash parses the data using json codec. 

But I can see two duplicate json events (metrics) with all same values coming from each of the aerospike nodes except just a few metrics: e.g., having non-zero (same) value either for migrate_tx_partitions_initial or migrate_rx_partitions_initial for the two records from each node. Even if I stop telegraf on a node, I can see the duplicate events. Collection interval was tried with 1s and 5s. 

Is this a known issue and any resolutions? 

Thanks.

**Comment by mrchang7** [comment]
I found this only happens when you run two aerospike servers as a cluster with replication. I think the replicated parts generate the seemingly duplicate events. If I stop one of the servers I don't have the duplication. 

So, now the question is how would I interpret and use the two events (with same timestamp). Will they be always almost same like that? Do I need to aggregate them all in a way?

**Comment by danielnelson** [comment]
The aerospike input gathers metrics from every node in the cluster, so with your current setup each Telegraf reports for both nodes.

You could have a single Telegraf, either on a third machine or on one of your aerospike nodes, gather for the aerospike cluster, then you should no longer have duplicates.

I'm not sure I understand your last question.  With the standard configuration, there is a host tag added to all points with the hostname of the machine running Telegraf, does this work?

**Comment by mrchang7** [comment]
Thanks for the reply. This question is related to the issue: https://github.com/influxdata/telegraf/pull/2918
The aerospike guy just answered to how to get the node information. We need this node information to see this is local or not; otherwise if we get the node id (hostname or ip address) in order to distinguish where (which node) the metric streams come from.

**Comment by danielnelson** [comment]
It seems like between `aerospike_host`, `host`, and `node_name` tags you should have this information, so long as you connect to aerospike using the external addresses.

**Comment by mrchang7** [comment]
Unlikely. Currently when I run telegraf only on a node (aerospike1) of two-node cluster, I get two reports with the same values with different node_name's (as below example). Based on this information I cannot tell which is from local. One workaround is to query the servers having the MAC address (with conversion from node_name). Rather than the node_name as mac-address, I'd like to have hostname or ip address of the node.  Please correct me if I'm missing.
 
aerospike_namespace,aerospike_host=localhost:3000,namespace=test,host=aerospike1, node_name="BB9020011AC4202" 
aerospike_namespace,aerospike_host=localhost:3000,namespace=test,host=aerospike1, node_name="BB9AF20011AC4203"

**Comment by danielnelson** [comment]
Okay I see it now, you won't be able to tell which is the local node.

The main reason you want to know which one is local is so you can exclude the other?  If so, why not just run a single Telegraf instance?  There are some other ways I can think of to address this but they depend on using InfluxDB as the output, and I know you are outputting to elasticsearch.

**Comment by mrchang7** [comment]
Right. Even with a single telegraf I'd like to know which one is for which node by host id, not by MAC-based node_name. If we run a single telegraf, we will need to have a process for the failover cases.

**Comment by danielnelson** [comment]
With InfluxDB if you ensure the same series is created then the fields will be merged, creating a single point.  To do this here you would need to `tagexclude` host and potentially aerospike_host.  Not sure if this is something that can be done with elasticsearch.

I'll update the title to reflect what needs done, is it something you would have time to do?

**Comment by danielnelson** [comment]
Actually, I'm not 100% sure what we want to try, here are the two options:

- Add option to collect only local Aerospike node.
- Add tag with hostname of node.

**Comment by mrchang7** [comment]
Both would be useful. Either of them would suffice my need though. Many thanks.

**Comment by popov-ilya** [comment]
In my case i just use inputs.aerospike.tagpass with local node_name. As i use ansible for telegraf config deployment it is quite simple to find out local aerospike node_id.
The Node ID is constructed with the fabric port (port 3001 in hex) followed by the MAC address in reverse byte order.
