### ISSUE TITLE
chrony plugin does not track system time offset

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2988]
### Relevant telegraf.conf:

```
[[inputs.chrony]]
```

### System info:

[Include Telegraf version, operating system name, and other relevant details]
version: 1.3.0
os: linux

### Steps to reproduce:

1. run telegraf with chrony input enabled

### Expected behavior:
data to indicate system clock offset from ntp server

### Actual behavior:
no data indicates system clock offset from ntp server

### Additional info:
In the `chronyc tracking` output, the `System time` field provides the clock offset.
```
# chronyc tracking
Reference ID    : 10.0.99.22 (ntp2.chewy.local)
Stratum         : 4
Ref time (UTC)  : Wed Jul 05 17:08:51 2017
System time     : 7495.370605469 seconds slow of NTP time
Last offset     : +0.000008273 seconds
RMS offset      : 344.988952637 seconds
Frequency       : 33.131 ppm slow
Residual freq   : +0.004 ppm
Skew            : 0.069 ppm
Root delay      : 0.033780 seconds
Root dispersion : 0.003258 seconds
Update interval : 1.9 seconds
Leap status     : Normal
```

However due to bug in the code, it tries to filter out the `Ref time (UTC)` field by looking for `"time"`. This ends up filtering out the `System time` field as well.

**Comment by danielnelson** [comment]
Thanks @subfxnet
