### ISSUE TITLE
Bug/Feature Request: Incorrect Disk metrics with multiple mountpoints for the same device

### ISSUE THREAD

**Issue by garceri** [influxdata/telegraf#2991]
## Bug report
We use rancher for container management under AWS instances, we also make use of the rancher-ebs plugin with manages the container -> device mappings.
With this storage plugin, the same device ends up mounted several times, `df -h` shows the same device/mountpoint several times
```
[root@myrancherhost ~]# df -h |grep wal
/dev/xvdg               196.7G    313.4M    186.4G   0% /var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal
/dev/xvdg               196.7G    313.4M    186.4G   0% /var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal

```
When telegraf runs the system.disk input plugin into this server we different measurements for each device even when they are the same. 

Would it be possible to have a setting in telegraf to validate the UUID of each device and report it only once ?

### Relevant telegraf.conf:
```
         [agent]
            interval = "60s"
            round_interval = true
            metric_batch_size = 1000
            metric_buffer_limit = 10000
            collection_jitter = "0s"
            flush_interval = "10s"
            flush_jitter = "0s"
            precision = ""
            debug = false
            quiet = false
            hostname = ""
            omit_hostname = false
          [[outputs.influxdb]]
          urls = [ "http://influxdb:8086" ]
          database = "telegraf-dev"
          precision = "s"
          [[inputs.cpu]]
            percpu = true
            totalcpu = true
            fielddrop = ["time_*"]
          [[inputs.disk]]
            ignore_fs = ["tmpfs", "devtmpfs"]
          [[inputs.diskio]]
          [[inputs.kernel]]
          [[inputs.mem]]
          [[inputs.net]]
          [[inputs.netstat]]
          [[inputs.processes]]
          [[inputs.swap]]
          [[inputs.system]]
          [[inputs.docker]]
            timeout = "15s"
            endpoint = "unix:///var/run/docker.sock"
          [[inputs.net]]
            interfaces = ["eth0"]
          [[inputs.prometheus]]
            urls = ["http://rancher-prometheus-exporter:9173/metrics"]

```
### System info:
```
[root@myrancherserver ~]# cat /proc/mounts |grep wal
/dev/xvdg /var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal ext4 rw,relatime,data=ordered 0 0
/dev/xvdg /var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal ext4 rw,relatime,data=ordered 0 0
```

Telegraf built from master branch today (2017-07-06), Rancher OS 1.0.2

**Comment by danielnelson** [comment]
Can you run Telegraf with the `--input-filter disk --test` flags and add the output?

**Comment by garceri** [comment]
Here is the output (i grepped output  on ebs_influxdb-wal for simplicity sake)
```
root@rancher-telegraf-telegraf-1:/# telegraf --input-filter disk  --test --config /config/telegraf.toml |grep wal
> disk,fstype=ext4,host=rancher-telegraf-telegraf-1,path=/rootfs/var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal,device=xvdg total=211244736512i,free=200155070464i,used=335470592i,used_percent=0.16732489734081674,inodes_total=13107200i,inodes_free=13107069i,inodes_used=131i 1499376918000000000
> disk,device=xvdg,fstype=ext4,host=rancher-telegraf-telegraf-1,path=/rootfs/var/lib/rancher/volumes/rancher-ebs/ebs_influxdb-wal used_percent=0.16732489734081674,inodes_total=13107200i,inodes_free=13107069i,inodes_used=131i,total=211244736512i,free=200155070464i,used=335470592i 1499376918000000000
 
```

**Comment by danielnelson** [comment]
Thank you.  Just to clarify, the difference between samples is just due to the time between readings?  So this would be primarily a performance improvement if we called it once per path?

**Comment by garceri** [comment]
Not sure if i understood what you are asking, The provided output is from a single reading, as you can see the timestamps are the same.
I'm sure it will bring performance improvements under these conditions.

**Comment by danielnelson** [comment]
Sorry, I misread your initial comment about the multiple measurements.

What we could do is only report for each unique path.  It is not always the same as UUID but will be in your case.

**Comment by garceri** [comment]
I don't think you should use the path as the unique identifier, as you can have multiple devices mounted on the same path (not very useful but i have seen this happen), perhaps you should use the device name as the unique ID.

**Comment by danielnelson** [comment]
That's a good point, though I wonder if we need to do it on a combination of device and path since you can also easily mount a device in multiple locations.

**Comment by garceri** [comment]
I think that this should be implemented as a configuration option for the plugin something like
```
[inputs.disk]
filter_duplicates = [path|device|both|none]
```
It gets complicated because having multiple measurements for the same device (but on different paths) may be useful to some people, while being a nuisance to others (me!).

**Comment by danielnelson** [comment]
Can you elaborate on why this would be a nuisance?  If you currently have devices mounted on multiple paths that you can show as an example that would be good too.

I wonder if there are two devices on multiple paths, and we wanted to report only a single one, how we would choose which one to report.

**Comment by garceri** [comment]
Let's say we use grafana/InfluxDB to graph the disk space utilization across all the <devices|paths> on a given system, if we get mutlple measurements for the <device|path> grafana automatically adds them so if the <device|path> has 10 GB used, we get 20G instead,
