### ISSUE TITLE
system.disk plugin doesn't report infos about disk with no partitions

### ISSUE THREAD

**Issue by sbadia** [influxdata/telegraf#2992]
## Bug report

Hi, I'm not completely sure, but it seems that telegraf doesn't report any informations about disk without a extended partition (in my case `sdb`).

In some case I have a fs directly created on the bloc-device.

```
/dev/sda1       98884832 77365968  21502480  79% /
/dev/sdb       103081248 51764216  46561136  53% /opt/prometheus/var
```
### Relevant telegraf.conf:

```
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
```

### System info:

```
Telegraf v1.3.3 (git: release-1.3 46db92aad3e68af04f1732598ac89f6b9b11daf8)
Ubuntu 16.04.2 LTS
```

### Additional info:

https://github.com/influxdata/telegraf/blob/eb7ef5392e14b964877a2239976267d86dbd83c6/plugins/inputs/system/ps.go#L91
https://github.com/influxdata/telegraf/blob/dd537b33826d70ca0c9f34bddaa3736f916a83be/plugins/inputs/system/disk.go#L58

Thanks in advance!

**Comment by danielnelson** [comment]
I get results for a thumb drive with no partition:
```
disk,path=/media,device=sdb,fstype=ext4,host=loaner used=54550528i,used_percent=0.09163715649311663,inodes_total=3907584i,inodes_free=3907573i,inodes_used=11i,total=62746595328i,free=59474280448i 1499447505000000000
```

There are quite a few reasons it might be skipped, can you add your `/etc/mtab` file?

**Comment by sbadia** [comment]
Hi, @danielnelson, thanks!

In fact I just hit this issue https://github.com/influxdata/telegraf/issues/1544#issuecomment-278955406

Sorry, I close this duplicate issue.
