### ISSUE TITLE
jolokia for kafka mbean (Count,MeanRate) reports the values monotonically increasing 

### ISSUE THREAD

**Issue by mrchang7** [influxdata/telegraf#2993]
This is one of my jolokia metrics to receive the MessagesInPerSec. Based on its definition, it looks like I should have number of messages in (Count) and average rate (MeanRate) "per second". But in my receiving side (elasticsearch), I see the the values for MessagesPerSec_Count and MessagesPerSec_MeanRate are ever increasing like counter. The OneMinuteRate reports the rate. 

   [[inputs.jolokia.metrics]]
      name = "kafka.server.BrokerTopicMetrics.MessagesInPerSec"
      mbean = "kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec"
      attribute = "Count,MeanRate,OneMinuteRate"

FYI, I'm setting the telegraf interval to 1s. Is this correct behaviour? Then I will have to take rate on my own on the receiving side. 

For your reference: https://serverfault.com/questions/828511/what-do-mbean-parameters-mean-in-collectd/828591#828591

**Comment by danielnelson** [comment]
The jolokia plugin just reads the value, it doesn't have any logic to keep a running total, so it must be coming in like this.  With InfluxDB, you can easily get the rate using the derivative or non_negative_derivative functions, perhaps there is something like this for elasticsearch?

You can probably get better help for questions over at the [InfluxData Community](https://community.influxdata.com) site.
