### ISSUE TITLE
Parsing Array of json using Telegraf Input.exec pluging

### ISSUE THREAD

**Issue by senarha** [influxdata/telegraf#2996]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:
[inputs.exec]]
	commands=["go run MetricsReport.go -remoteAddr="myweb.com"]
	timeout="50s"
	data_format = "json"
	name_override = "MR_1"
	tag_keys = [ "PN","Server","Status"]

### System info:
OS : Windows / Linux, 
Telegraf Version : 1.2.1
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Running the go script (as mentioned in the telegraf conf file) generates the following output:
{"PN":"US1","Servers":[{"Server":"myweb.com","Status":true
,"TimeTaken":19}],"TimeStamp":1000}
2. However running them through telegraf only fetches the int values and PN values (which is string in this case)

### Expected behavior:
Ideally it should parse and fetch all the String and Boolean values whose keys are included in Tag_keys. 
THis works fine if I have those keys in the root level of the json.
### Actual behavior:
Not parsing those string and boolean values which are not at the root level of the json 

Output that I get from Telegraf:
CePO_Metrics,Pops_Name=US1,host=MYPC-1 TimeStamp=10 14996396450000000
(I dont see Server Name and Status)

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
I think this will need to be addressed as a new JSON parser, we have an issue to track this #1363.  For now, you will need to modify the output of the script in order to get these fields.
