### ISSUE TITLE
Absence of pgrep in Windows for procstat

### ISSUE THREAD

**Issue by 999chris** [influxdata/telegraf#2998]
exerpt of telegraf.conf:
**[[inputs.procstat]]
  exe = "node"**

### System info:

Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
Win 7 Enterprise SP 1

**Log:**
2017-07-10T11:32:23Z E! Error: procstat getting process, exe: [node] pidfile: [] pattern: [] user: [] Couldn't find pgrep binary: exec: "pgrep": executable file not found in %PATH%

Is there a pgrep for windows?? How can I get this working? Or is there an alternative plugin? Any help appreciated.

**Comment by danielnelson** [comment]
You can try using the win_perf_counters plugin instead.  You might be able to use pgrep from cygwin, msys, or the Windows subsystem for Linux but I have not heard any reports of if this will work or not.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by vrecan** [comment]
Couldn't we leverage something like this https://github.com/mitchellh/go-ps to be able to find processes on all platforms without pgrep?

**Comment by vrecan** [comment]
Looks like this would actually be better https://github.com/google/gops
