### ISSUE TITLE
Timezone does not work on logparser.grok

### ISSUE THREAD

**Issue by Findarato** [influxdata/telegraf#3000]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
1. Reference Timezone in inputs.logparser.grok
2. Crash

### Expected behavior:
Not crashing
### Actual behavior:
2017/07/10 14:46:18 E! Error parsing nvidia.test, line 14: field corresponding to `Timezone' is not defined in `*grok.Parser'

### Additional info:

[Include gist of relevant config, logs, etc.]

[[outputs.file]]
  files = ["stdout"]

[[inputs.logparser]]
   files = ["/opt/nvidia/nvidia_log.csv"]
   from_beginning = true
   [inputs.logparser.grok]
      patterns = ["%{GPU1}","%{GPU2}"]
      measurement = "gpu"
      custom_patterns = '''
       GPU1 %{DATA:timestamp:ts-"2006/01/02 15:04:05.000 -500"}, %{DATA:gpu_name:tag}, %{DATA:slot:tag}, %{NUMBER:driver:float}, P%{NUMBER:pstate:int}, %{NUMBER:temperature:int}, %{NUMBER:gpu_utilization:int} %, %{NUMBER:memory_utilization:int} %, %{NUMBER:memory_total:int} MiB, %{NUMBER:memory_free:int} MiB
       GPU2 %{DATA:timestamp:ts-"2006/01/02 15:04:05.000 -500"}, %{DATA:gpu_name:tag}, %{DATA:slot:tag}, %{NUMBER:driver:float}, P%{NUMBER:pstate:int}, %{NUMBER:temperature:int}, \[Not Supported\], \[Not Supported\], %{NUMBER:memory_total:int} MiB, %{NUMBER:memory_free:int} MiB, %{NUMBER:memory_used:int} MiB
      '''
      Timezone = "America/Chicago"

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
Timezone needs to be lowercase, does that fix it?

**Comment by danielnelson** [comment]
Please reopen if that does not help.

**Comment by Findarato** [comment]
In a further example that does the same thing
`# Stream and parse log file(s).
[[inputs.logparser]]
#   files = ["/var/lib/fahclient/log.txt","/var/lib/fahclient/logs/*"]
   files = ["/var/lib/fahclient/log.txt"]
   from_beginning = true
   [inputs.logparser.grok]
      patterns = ["%{FAH_POINTS}"]
#      patterns = ["%{FAH_WORKUNITS}","%{FAH_POINTS}"]
      measurement = "fah"
     custom_patterns = '''
#     FAH_WORKUNITS %{DATA:timestamp:ts-"2006-01-02:15:04:05"}\:WU%{NUMBER:workunit:tag}\:FS%{NUMBER:slot:string}\:%{DATA:core:string}\:Completed %{NUMBER:progress:int} out of %{NUMBER:total:$
     FAH_POINTS %{DATA:timestamp:ts-"2006-01-02:15:04:05"}\:WU%{NUMBER:workunit:tag}\:FS%{NUMBER:slot:string}\:Final credit estimate, %{NUMBER:points:float} points
     '''
     timezone = "America/Chicago"
`

I have tried with and with out an '=' I have tried both capital and lowercase. and Placing it in the custom_patterns.

**Comment by danielnelson** [comment]
What revision did you build with?  The timezone field is only on master (not released).

**Comment by Findarato** [comment]
Telegraf v1.2.1 

I did not know it was only on master. NM then.
