### ISSUE TITLE
Merge aerospike metrics (namespace and node)

### ISSUE THREAD

**Issue by mrchang7** [influxdata/telegraf#3002]
As long as the metrics in the two contexts (namespace, node) are exclusive, can we have an option to send the metrics in a merged "plugin: aerospike"? A separate context metric could be added to carry either 'namespace' or 'node' if we need it. That would much simplify our works on the receiver side working with logstash.

**Comment by danielnelson** [comment]
I think if you use `name_override = "aerospike"` on the aerospike input it will do what you want.

**Comment by mrchang7** [comment]
Great! Many thanks!
