### ISSUE TITLE
redis.input  There is no data?

### ISSUE THREAD

**Issue by hailin0** [influxdata/telegraf#3006]
config
--------------------------
Telegraf version: 1.3.3
Redis version: 2.8.23

[[inputs.redis]] 
   servers = ["tcp://:123456@10.0.0.1:16379"]

result 
-------------------------------
redis_redis,server=10.0.0.1,port=16379,host=555c3xx8e843,dc=docker-test keyspace_hitrate=0 1499774770000000000

There is no data!
**How is this to return a responsibility excuse me? Can you help me?**

**Comment by hailin0** [comment]
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/redis
--------------------------------
**Found a large number of missing data**

**Comment by danielnelson** [comment]
Based on a code inspection, this could happen if an error occurs running the INFO command.  Can you try running a command similar to this and reply with the output?
```
redis-cli -h 10.0.0.1 -p 16379 -a 123456 INFO
```

**Comment by hailin0** [comment]
10.0.0.1:0>INFO
"# Server
redis_version:2.8.23
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:64df67297f1ee6c5
redis_mode:standalone
os:Linux 3.16.0-30-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7
process_id:1
run_id:4fdffe6097e8bfb112fde7697b1dfcfee95550ba
tcp_port:6379
uptime_in_seconds:36157564
uptime_in_days:418
hz:10
lru_clock:6649489
config_file:

# Clients
connected_clients:1668
client_longest_output_list:0
client_biggest_input_buf:1310
blocked_clients:0

# Memory
used_memory:418646408
used_memory_human:399.25M
used_memory_rss:1075912704
used_memory_peak:3831605288
used_memory_peak_human:3.57G
used_memory_lua:66560
mem_fragmentation_ratio:2.57
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:295970166
rdb_bgsave_in_progress:0
rdb_last_save_time:1463664149
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:12528747
total_commands_processed:2865335255
instantaneous_ops_per_sec:91
total_net_input_bytes:176462145905
total_net_output_bytes:92519969383
instantaneous_input_kbps:2.75
instantaneous_output_kbps:1.32
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:26345835
evicted_keys:0
keyspace_hits:372571188
keyspace_misses:260014474
pubsub_channels:6
pubsub_patterns:0
latest_fork_usec:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:121659.62
used_cpu_user:59558.67
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Keyspace
db0:keys=105659,expires=91485,avg_ttl=381253165
db1:keys=9,expires=0,avg_ttl=0
db2:keys=446052,expires=446046,avg_ttl=658165343
db3:keys=51,expires=40,avg_ttl=4128642606
db4:keys=416,expires=416,avg_ttl=2432009630
db5:keys=46274,expires=46272,avg_ttl=9109023230
db6:keys=6,expires=6,avg_ttl=668757423800556
db7:keys=35,expires=35,avg_ttl=87515274
"

**Comment by hailin0** [comment]
**Would you please check**

**Comment by hailin0** [comment]
log errors
--------------------------------------------------------------
root@abc:/# tailf /var/log/telegraf/telegraf.log 
2017-07-12T01:14:50Z D! Output [file] buffer fullness: 45 / 1000 metrics. 
2017-07-12T01:14:50Z E! Error writing to output [file]: failed to write message: redis_redis,port=16379,dc=docker-test,host=555c3xx8e843,server=10.0.0.1 keyspace_hitrate=0 1499821650000000000
, invalid argument

**Comment by hailin0** [comment]
@danielnelson

**Comment by danielnelson** [comment]
Can you add the ``[[outputs.file]]`` section of your config and also what platform you are running telegraf on?

**Comment by hailin0** [comment]
-----------------------------------------------
[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "influx"



system: ubuntu14.04 + docker1.11.2

------------------------------------------------
Found a strange question

telegraf and redis installed in a container,  testing is successful!

telegraf and redis separated in different containers testing is error!

**Comment by danielnelson** [comment]
When you ran the INFO command earlier, were you in the different container?

**Comment by hailin0** [comment]
yes

**Comment by danielnelson** [comment]
Can you try to capture the network traffic?  Something like this on the Telegraf container while it is running but you will need to change the interface and port.
```
sudo tcpdump -A -s 0 'tcp port 6379' -i lo -v
```

**Comment by hailin0** [comment]
额

**Comment by hailin0** [comment]
I found no data output

--------------------------------------------
sudo tcpdump -A -s 0 'tcp port 16379' -i lo -v    ---> host machine
sudo tcpdump -A -s 0 'tcp port 6379' -i lo -v      ----> redis docker

**Comment by hailin0** [comment]
@danielnelson 

I think I found the problem. I found is password authentication error.
Cancel password successfully! 

Thank you for your help.
Looking forward to repair

**Comment by danielnelson** [comment]
I'm not sure I understand, the problem was only that the password was wrong?  I tested this and I get an error when the password is not accepted.  Also, why then does it work when in the same container?

**Comment by hailin0** [comment]
@danielnelson  Also, why then does it work when in the same container?
-------------------------------------------------------------------

sorry.   now found that don't work.......

**Comment by hailin0** [comment]
I'm sure my password is correct
But the telegraf thinks is wrong?

**Comment by hailin0** [comment]
redis config
requirepass 123456
-------------------------------------------

I use redis - cli validated my password is correct

**Comment by danielnelson** [comment]
Is it really this simple of a password?  Since the password is placed in the URI I have seen some issues with escaping.  For example, if it had an `@` in the password that would need escaped.

**Comment by hailin0** [comment]
I'm sorry the reason is the deployment of the environment
New environment is right...
Thank you for your help

**Comment by oguzhan10** [comment]
what was the solution how did you solve
