### ISSUE TITLE
insecure_skip_verify not supported for influxdb input plugin

### ISSUE THREAD

**Issue by kjschnei001** [influxdata/telegraf#3008]
## Bug report
Despite being *sort of* documented as part of the InfluxDB input plugin, https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb, the `insecure_skip_verify` option is not actually supported.  

### Relevant telegraf.conf:
```
[[inputs.influxdb]]
insecure_skip_verify = true
urls = ["https://127.0.0.1:8084/debug/vars"]
```

### System info:
Telegraf v1.3.3 (git: release-1.3 46db92aad3e68af04f1732598ac89f6b9b11daf8)
CentOS Linux release 7.2.1511 (Core)

### Steps to reproduce:

1. Configure the influxdb telegraf input plugin with `insecure_skip_verify`

### Expected behavior:
`insecure_skip_verify = true` will disable ssl verification of the influxdb certificate when the plugin connects to monitor it

### Actual behavior:
```
2017/07/11 21:09:05 E! Error parsing /etc/telegraf/telegraf.d/default_inputs.conf, line 10: field corresponding to `insecure_skip_verify' is not defined in `*influxdb.InfluxDB'
```

**Comment by danielnelson** [comment]
Support for this is only added in master, and will be in 1.4.0. #2773

If you are following links from https://docs.influxdata.com, note that they are linked to the master branch and are not specific to the version selected.  Sorry about this confusion.

**Comment by danielnelson** [comment]
I opened an issue about the links to the docs https://github.com/influxdata/docs.influxdata.com/issues/1195

**Comment by nickidw** [comment]
> Support for this is only added in master, and will be in 1.4.0. #2773
> 
> If you are following links from https://docs.influxdata.com, note that they are linked to the master branch and are not specific to the version selected. Sorry about this confusion.

I'm running 1.8.2 on Windows, and the error message indicates it's not yet supported.

`C:\Program Files\Telegraf>telegraf --console --test
2018/10/14 18:33:15 I! Using config file: C:\Program Files\Telegraf\telegraf.con
f
2018/10/14 18:33:15 E! Error parsing C:\Program Files\Telegraf\telegraf.conf, li
ne 79: field corresponding to `**insecure-skip-verify**' is not defined in `*influxd
b.InfluxDB'

C:\Program Files\Telegraf>`

**Comment by nickidw** [comment]
If I remove the option I get:
`2018-10-14T16:37:24Z W! [outputs.influxdb] when writing to [https://35.231.195.253:8086]: database "telegraf" creation failed: Post https://35.231.195.253:8086/query: x509: certificate signed by unknown authority
2018-10-14T16:37:24Z I! Starting Telegraf 1.8.1
2018-10-14T16:37:24Z I! Loaded inputs: inputs.win_perf_counters
2018-10-14T16:37:24Z I! Loaded aggregators: 
2018-10-14T16:37:24Z I! Loaded processors: `

**Comment by nickidw** [comment]
The option in the config file should actually be **InsecureSkipVerify = true**

I changed my config to the above and now it works.

**Comment by nickidw** [comment]
Apologies, seems I missed the trivial difference between underscore and dash. Thank you for the assistance.
