### ISSUE TITLE
rpm should not be starting service on installation or upgrade

### ISSUE THREAD

**Issue by blieberman** [influxdata/telegraf#3015]
### Relevant telegraf.conf:

Conf not relevant.

### System info:

Telegraf v1.3.4 (git: release-1.3 7bbd3daa98d5931c6e9025a98105092b0722de0d)
Amazon Linux latest

### Steps to reproduce:

1. Install or upgrade a telegraf rpm
2. Wait

### Expected behavior:

RPM to not automatically be switching on upon installation or upgrade, as it can break automated deploys or cases where the telegraf is being used under a non built in service manager i.e. supervisord.

Fedora suggest that you should not automatically switch on the service as this is insecure, instead you should rely on the init.d script via chkconfig to switch on the service. https://fedoraproject.org/wiki/EPEL:SysVInitScripts?rd=Packaging:SysVInitScript#Why_don.27t_we....

### Actual behavior:

Service is restarted.

### Additional info:

Problem appears to be in: https://github.com/influxdata/telegraf/blob/master/scripts/post-install.sh
I can submit a patch if you believe this is a legitimate bug.

**Comment by danielnelson** [comment]
Yeah we should change this, but we should make sure that in debian it does start the service automatically.

As an aside, at some point I would like to have separate maintainer scripts for each platform.

**Comment by blieberman** [comment]
Sounds good. Thanks for the quick response.
