### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by NitinKumar5** [influxdata/telegraf#3019]
Hi Team,
It`s really a good tool to play around and go important stuff too. Kudos to your team. But today i am facing an issue related to flashing data into influx database. below are the below details. hope details are sufficient to reproduce it.

### Relevant telegraf.conf:
[global_tags]
  ServerName="server_name"
  StackName="stack1"
  AppId="test"
  AppVersion="VERSION"

[agent]
  debug = true
  quiet = false

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""

[[inputs.jolokia]]
  context = "/jolokia/"

[[inputs.jolokia.servers]]
  host = "127.0.0.1"
  port = "8788"

[[inputs.jolokia.metrics]]
 name = "ReleaseCacheSize"
  mbean = "core.common.dataaccess.cache.consumer:name=core.release.cache.consumerCache,type=CacheConsumerImpl"
  attribute = "CacheSize"
 
[[inputs.jolokia.metrics]]
 name = "ConfigCacheSize"
  mbean = "core.common.dataaccess.cache.consumer:name=core.config.cache.consumerCache,type=CacheConsumerImpl"
  attribute = "CacheSize"

[[outputs.influxdb]]

  urls = ["$url"]
  database = "test_health"
  username = "XXXX"
  precision = "s"
  user_agent = "CacheSize"
  password = "XXXXX"
  timeout = "5s"

Version: 1.3
OS; Linux 2.6.32-696.1.1.el6.x86_64 x86_64

### Steps to reproduce:
We are not running telegraf as a service instead we are running through command.
telegraf --config=/etc/telegraf/telegraf.d/telegraf.conf

### Expected behavior:
It should write a data in influx database, as through window i am able to write data in influx db with same conf.
### Actual behavior:
2017-07-14T17:01:17Z D! Attempting connection to output: influxdb
2017-07-14T17:01:17Z D! Successfully connected to output: influxdb
2017-07-14T17:01:17Z I! Starting Telegraf (version 1.3.0)
2017-07-14T17:01:17Z I! Loaded outputs: influxdb
2017-07-14T17:01:17Z I! Loaded inputs: inputs.jolokia inputs.jolokia
...
2017-07-14T17:01:20Z E! Error in plugin [inputs.jolokia]: error performing request: Post http://localhost:8788/jolokia : dial tcp 127.0.0.1:8788: getsockopt: connection refused

### Additional info:
As security reason, we have removed the important info from conf , telegraf command and log snippet

### Desired behavior:
Telegraf should write a data into Influx db as it is doing correctly in Window OS.

### Use case: 
We need to monitor the in build cache in Grafana.

**Comment by danielnelson** [comment]
This looks to me like the jolokia server is just not listening at this host and port.

**Comment by danielnelson** [comment]
Please reopen if this does not end up being a connection issue.

**Comment by jheusser** [comment]
Noticed this behaviour as well, I was hoping that if a host is not available (e.g. the jvm is not running currently) then it either skips it, or has some form of up/down/health indication. I believe Prometheus reports a host not `up` if it can't be scraped but is configured to be scraped. In my use case it would have been nice if I can start telegraf even with jolokia hosts being not reachable.

**Comment by panand13** [comment]
@NitinKumar5  was this issue resolved at ur end ? if yes what did u do as a resolution

**Comment by panand13** [comment]
@danielnelson  i am still observing same issue at my end, any thoughts on this?

**Comment by glinton** [comment]
@panand13 It sounds like the jolokia server wasn't listening on the socket configured in `telegraf.conf`. If you have the following in your config, ensure your server is listening and accessible from telegraf:
```toml
[[inputs.jolokia.servers]]
  host = "127.0.0.1"
  port = "8788"
```

**Comment by panand13** [comment]
@glinton  i tried setting it and validated through browser but do not see  it working, any help how well i can troubleshoot this?

**Comment by panand13** [comment]
error as : Error in plugin [inputs.jolokia]: error performing request: Post http://127.0.0.1:8788/jolokia/: dial tcp 127.0.0.1:8788: connectex: No connection could be made because the target machine actively refused it.
2

**Comment by glinton** [comment]
Yes, ensure your jolokia server is running and listening on that socket (`127.0.0.1:8788`, note the localhost address; telegraf will need to be on the same host as jolokia) How are you running telegraf and jolokia?

**Comment by panand13** [comment]
do i need to run jolokia server as standalone?

**Comment by glinton** [comment]
You will need to run it so it is accessible by telegraf, whether that is "standalone" or not, i'm not certain. How are you currently running it?

**Comment by panand13** [comment]
m preety new to jolokia, how can i run jolokia as a service on windows any idea?..  currently i have just added  the below piece of code in my telegraf file.. from where i should download jolokia for windows and how should i run it as a service?


"[[inputs.jolokia.servers]]
#     name = "as-server-01"
#     host = "127.0.0.1"
#     port = "8080"
#     # username = "myuser"
#     # password = "mypassword"
#
#   ## List of metrics collected on above servers
#   ## Each metric consists in a name, a jmx path and either
#   ## a pass or drop slice attribute.
#   ## This collect all heap memory usage metrics.
#   [[inputs.jolokia.metrics]]
#     name = "heap_memory_usage"
#     mbean  = "java.lang:type=Memory"
#     attribute = "HeapMemoryUsage""

**Comment by glinton** [comment]
I don't know, so unfortunately all I can say is check their docs. According to your configuration though, it needs to be running and listening on port `8080` of the same host as the one you are running telegraf from.

**Comment by panand13** [comment]
m unable to figure out the way to install the service for jakolia, referring this article but unable to install the service yet https://jolokia.org/tutorial.html, any help will be appreciated

**Comment by danielnelson** [comment]
As a real quick overview there are 2 ways to run Jolokia:
- As an agent: with this method you download the jolokia agent jar and load it with the process you wish to monitor.  The Jolokia agent and the monitored Java process run together as one process.  With this method you should use the jolokia2_agent plugin.
- As a proxy: with this method you run a jolokia proxy service which communicates using JMX with the Java process you will monitor.  Use the jolokia2_proxy plugin with this.

I hope this is helpful but if you require more assistance then I recommend one of the support avenues on the Jolokia site: https://jolokia.org/support.html

Once you have Jolokia running and you can access it directly via `http://127.0.0.1:8080/jolokia/` if you still have questions you can ask at the [InfluxData Community](https://community.influxdata.com) site.
