### ISSUE TITLE
can't get the redis's replication_role

### ISSUE THREAD

**Issue by wyfaq** [influxdata/telegraf#3022]
In the grafana,I use the sql to query the redis's role for monitor,but I don't got it!

Telegraf version: 1.3.3
Redis version: 2.8.24

##Actual behavior:
### select aof_last_write_status,replication_role  from redis  limit 2

time | aof_last_write_status | replication_role
-- | -- | --
2017-07-17T03:07:00Z | "ok" | "slave"
2017-07-17T03:07:10Z | "ok" | "slave"

but I use this sql don't get any data...
### select replication_role  from redis  limit 2
Success! (no results to display)

**Comment by danielnelson** [comment]
I'm not sure what the problem is, this would be a good question to ask at the [InfluxData Community](https://community.influxdata.com) site.  I would also try connecting to InfluxDB using the influx command and running the queries there.
