### ISSUE TITLE
[Feature request] print details for inputs exec when encountering ERROR

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#3029]
I have multiple `inputs.exec` running in Telegraf config file and I don't know which one is causing error when I see the error message in log file:

```
2017/07/18 13:02:42 E! ERROR in input [inputs.exec]: Errors encountered: [unable to parse '400 Error': invalid field format], [unable to parse '400 Error': invalid field format], [unable to parse '400 Error': invalid field format]
```

I suggest adding more details when encountering error by printing the related command.

**Comment by danielnelson** [comment]
This is good idea, there is an existing issue open for this #1815
