### ISSUE TITLE
Add support for improved collectd parse format

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3034]
## Feature Request

InfluxDB recently improved the way they store collectd data.
https://github.com/influxdata/influxdb/issues/8426

This is described in more detail in the updated InfluxDB documentation:

> `parse-multivalue-plugin` was added with a default of `split`.  When set to `split`, multivalue plugin data (e.g. df free:5000,used:1000) will be split into separate measurements (e.g., (df_free, value=5000) (df_used, value=1000)).  When set to `join`, multivalue plugin will be stored as a single multi-value measurement (e.g., (df, free=5000,used=1000)).

Telegraf only supports the old format where a measurement would be made per collectd field.

### Proposal:

Implement the parse-multivalue-plugin option for the collectd parser.

### Current behavior:

df_free value=5000
df_used value=1000

### Desired behavior:

df free=5000 used=1000

### Use case: [Why is this important (helps with prioritizing requests)]

Enables feature parity with InfluxDB so a user can switch between input methods, as well as ability to perform calculations across fields, and follows best practice schema design.

**Comment by russorat** [comment]
closed by #4403
