### ISSUE TITLE
Building telegraf on freebsd requires gmake 

### ISSUE THREAD

**Issue by HristoMohamed** [influxdata/telegraf#3038]
**Bug report**
Building telegraf on freebsd requires gmake not the default make

 **Relevant** 

Building Telegraf from Source

**System info:**
On FreeBSD 11.0 the default make is not the GNU make, hence the instructions for building fail.
Please specify that gmake (the GNU make) must be used.

**Comment by danielnelson** [comment]
I added this to the README https://github.com/influxdata/telegraf/commit/4ee74ff54bf23c37b230b902bd7191cac3ea75c3
