### ISSUE TITLE
Enable High Resolution Metrics with the Cloudwatch output

### ISSUE THREAD

**Issue by devinsba** [influxdata/telegraf#3065]
## Feature Request

Per the recent blog post: https://aws.amazon.com/blogs/aws/new-high-resolution-custom-metrics-and-alarms-for-amazon-cloudwatch/

AWS now supports second resolution metrics when a `PutMetricData` request includes a new optional parameter `StorageResolution` set to `1`

### Proposal:

Add a config option to allow for writing data at this resolution

### Current behavior:

The client uses the standard behavior with 1 minute resolution metrics

### Desired behavior:

The metrics created and updated by telegraf will use high resolution when configured to

### Use case: [Why is this important (helps with prioritizing requests)]

Cloudwatch Alarms now support reacting in 10s when using 1s resolution metrics. This allows our infrastructure to be more reactive to change.

**Comment by radykal-com** [comment]
I'd like to take care of this as I need it :)
