### ISSUE TITLE
Trying to insert PowerShell command directly into Telegraf.conf

### ISSUE THREAD

**Issue by trap167** [influxdata/telegraf#3067]
Hi there,

I'm trying to collect Prometheus metrics on the size of a folder "C:\Users\bsmith\downloads" on one of our Windows machines.

I've written the following PowerShell script (LoggingTest.ps1) that works without issue to collect these metrics:

Get-ChildItem C:\Users\bsmith\downloads -recurse | Measure-Object length -sum | ConvertTo-Json -Compress | % {$_ -replace('Count','NumberOfFiles') -replace('Sum','SizeInBytes')}

This script executes exactly the way I want it to when telegraf.conf is configured as follows:

[[inputs.exec]]
commands = ["powershell C:/Scripts/LoggingTest.ps1"]
timeout = "5s"
data_format = "json"
name_suffix = "_Logging_Folder"

However, in order to be better prepared for scaling this script to several other Windows machines, I would like to have the script implemented in telegraf.conf as follows:

[[inputs.exec]]
commands = [
   "powershell Get-ChildItem C:\Users\bsmith\downloads -recurse | Measure-Object length -sum | 
   ConvertTo-Json -Compress | % {$_ -replace('Count','NumberOfFiles') -replace('Sum','SizeInBytes')}"
]
timeout = "5s"
data_format = "json"
name_suffix = "_Logging_Folder"

Can someone please look into this and offer some insights as to what I may be doing wrong?

**Comment by zensqlmonitor** [comment]
Just use:
powershell.exe –NoProfile –Command "Get-ChildItem C:\Users\bsmith\downloads -recurse | Measure-Object length -sum |
ConvertTo-Json -Compress | % {$_ -replace('Count','NumberOfFiles') -replace('Sum','SizeInBytes')}"

**Comment by danielnelson** [comment]
Also make sure you escape it properly for toml, since your string contains both single and double quotes you might want to use a multilne `'''` string.  https://github.com/toml-lang/toml#string

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by trap167** [comment]
Thanks for your reply mate. 

I've entered your exact command into my telegraf.conf file however I am still getting the same error when I try to start the Telegraf service:

![image](https://user-images.githubusercontent.com/29049306/28789392-2235caea-75da-11e7-8ed8-3463c3357f9f.png)

Do you have any further suggestions?

**Comment by danielnelson** [comment]
If the service will not even start then your config is probably not a valid toml file.  There should be more information in the logfile.

**Comment by trap167** [comment]
After escaping out (\) the original quotes and backslashes, the following script worked perfectly within telegraf.conf:

"powershell.exe -NoProfile -Command \"Get-ChildItem C:\\Users\\bsmith\\downloads -recurse | Measure-Object length -sum | ConvertTo-Json -Compress | ForEach-Object {$_ -replace('Count','NumberOfFiles') -replace('Sum','SizeInBytes')}\""
