### ISSUE TITLE
Allow wildcards in specification of mount_points (for disk input plugin)

### ISSUE THREAD

**Issue by rwarren** [influxdata/telegraf#3070]
### Current behaviour

Currently (v1.3.5), the disk input system plugin allows you to specify an explicit list of mountpoints to collect stats for.  For example:

    mount_points = ["/", "/data/images", "/data/images/img1", "/data/images/img2"]

### Desired behaviour

It would be great if simple wildcarding (eg: globbing) were supported here. In this case, the above `mount_points` could be specified as:

    mount_points = ["/", "/data/images", "/data/images/img*"]

### Use case

Modern systems often have a lot of mount points.  Masking off certain filesystem types (with `ignore_fs`) helps a lot, but there can still be a lot of mounts remaining for a given filesystem type. Allowing wildcards would help narrow this down.

A specific use case (driving this request) is on ZFS systems with a lot of zfs datasets, each of which show up as a mount point with fs type `zfs`. These dataset mountpoints are organized hierarchically. For example, we have `data/images` and `data/archives`.  We would like to only collect stats on those images in `data/images`.

**Comment by danielnelson** [comment]
This would be a good feature, and is similar to #2726

**Comment by sspaink** [comment]
The project now has an internal globbing function we can use to easily implement this feature request: (https://github.com/influxdata/telegraf/blob/master/internal/globpath/globpath.go). @rwarren I know it has been a very long time, but are you still interested in seeing this feature being implemented? Would it still be useful for you?
