### ISSUE TITLE
SNMP input not gathering field as expected

### ISSUE THREAD

**Issue by unnuetz** [influxdata/telegraf#3077]
hey, i am getting crazy now, because i think i am doing something wrong.

i wanna get a value from a checkpoint oid via snmp to my influxdb using telegraf.

in linux i can test 

snmpget -v2c -c public 172.23.1.1 .1.3.6.1.4.1.2620.500.9002.1.3.88.88.88.88.0

i get back "Counter32" Value 3 (ok so far)
iso.3.6.1.4.1.2620.500.9002.1.3.88.88.88.88.0 = Counter32: 3

now what i added to my telegraf.conf

[[inputs.snmp]]
agents = [ "172.23.1.1:161" ]
version = 2
community = "public"
name="system"
[[inputs.snmp.field]]
name = "VPN"
oid = ".1.3.6.1.4.1.2620.500.9002.1.3.88.88.88.88.0"

in my grafana query i did not get any entry or value for "VPN" in system.

can you help me?

**Comment by danielnelson** [comment]
Are there any errors if you run `telegraf --test`?

**Comment by unnuetz** [comment]
no, nothing just one line:

root@07163487677d:/# telegraf --input-filter snmp --test

2017/08/02 10:56:25 I! Using config file: /etc/telegraf/telegraf.conf
* Plugin: inputs.snmp, Collection 1

**Comment by danielnelson** [comment]
Perhaps we can figure out the problem with a packet capture:
```
sudo tcpdump -s 0 -i eth0 -w snmp.pcap host 172.23.1.1 and port 161
```
Can you edit the interface name if needed, run this command while running `--test`, and attach the output `snmp.pcap` to this issue?

**Comment by danielnelson** [comment]
Please reopen if you need more help troubleshooting.
