### ISSUE TITLE
Telegraf/InfluxDB ignoring nanosecond precision

### ISSUE THREAD

**Issue by MarioJelev** [influxdata/telegraf#3079]
Hi,

We are running into an issue with Telegraf where the nanosecond precision of our records is being ignored upon inserting the data into InfluxDB.

We have a shell script pulling data from an Oracle database and formatting it into the InfluxDB insertion syntax. These records contain a timestamp that is nanosecond-sensitive (an example of a timestamp for one of these records would be 1491728400000000056.) 

When we point the [[inputs.exec]] configuration option to our shell script and execute Telegraf, all of the correct tags and fields are being written to our InfluxDB instance, but the nanoseconds of our records' timestamps are being ignored. A record that has 1491728400000000056 would be inserted as 1491728400000000000 . This still happens after setting 'precision="ns"' under the [Agent] and [[outputs.influxdb]] configuration options.

Spooling the script output to a file and inserting it to InfluxDB via the InfluxDB HTTP API works perfectly, so the query is not the issue.

We are using Telegraf v1.3.5. 

Thank you!

**Comment by danielnelson** [comment]
I think you just need to change you config to `precision="1ns"`

**Comment by MarioJelev** [comment]
@danielnelson Thanks Daniel! This fixed the issue. I had been looking at the configuration file documentation (https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) and all of the examples just had the "s" precision, so I did not think to explicitly specify the number of seconds.

**Comment by danielnelson** [comment]
Sorry about that, I'll fix up the examples.
