### ISSUE TITLE
Curr_connections vs. client_connections

### ISSUE THREAD

**Issue by tonicava** [influxdata/telegraf#3087]
Hi,

It's actually a doubt regarding the exact meaning of curr_connections (number of open connections with regard to ...) and whether there is a direct relation to the number of client_connections for a given pool/server. The readme isn't quite informative in this aspect :-)

Thx!

**Comment by danielnelson** [comment]
I'm sorry I don't understand your question.  Can you add more information and ask at the [InfluxData Community](https://community.influxdata.com) site.
