### ISSUE TITLE
(Feature request) allow multiple [[inputs.cloudwatch]] -- multiple namespace's

### ISSUE THREAD

**Issue by KendallWeihe** [influxdata/telegraf#3088]
Is there a reason why the `inputs.cloudwatch` plugin requires only a single namespace be defined? I want to configure Telegraf to input (pretty much) all CloudWatch namespaces to my influxdb instance. Maybe there is a way and I am not aware of it. 

From [this](https://github.com/influxdata/telegraf/issues/1918) issue, I thought if I used double brackets like `[[inputs.cloudwatch]]` then I could do something like...

```
[[inputs.cloudwatch]]
  region = "us-east-1"

  access_key = ""
  secret_key = ""

  period = "5m"
  delay = "5m"
  interval = "5m"

  ## Metric Statistic Namespace (required)
  namespace = "AWS/S3"
  ratelimit = 10

[[inputs.cloudwatch]]
  region = "us-east-1"

  access_key = ""
  secret_key = ""

  period = "5m"
  delay = "5m"
  interval = "5m"

  ## Metric Statistic Namespace (required)
  namespace = "AWS/EC2"
  ratelimit = 10
```

But this just leads to the EC2 measurement overwriting the S3 measurement --  confirmed by only seeing this measurement (`cloudwatch_aws_ec2`) in influxdb...

```
> show measurements
name: measurements
name
----
cloudwatch_aws_ec2
cpu
disk
diskio
kernel
mem
mongodb
mongodb_db_stats
processes
swap
system
```

Is there any way I can configure/enable all namespaces to be polled by Telegraf?

**Comment by danielnelson** [comment]
What you are doing should work, and create a second cloudwatch_aws_s3 measurement.  Can you run Telegraf with `--input-filter cloudwatch --test` flags and add the output?

**Comment by KendallWeihe** [comment]
Sure, here it is (my IAM role has FullCloudWatchAccess -- and I took out some values for security purposes)...

```
kendall@kendall-Inspiron-5577:~$ telegraf --input-filter cloudwatch --test 
2017/08/03 09:02:30 I! Using config file: /etc/telegraf/telegraf.conf
* Plugin: inputs.cloudwatch, Collection 1
* Internal: 5m0s
* Plugin: inputs.cloudwatch, Collection 1
* Internal: 5m0s
> cloudwatch_aws_ec2,auto_scaling_group_name=<group_name>,host=kendall-Inspiron-5577,region=us-east-1,unit=count status_check_failed_average=0,status_check_failed_maximum=0,status_check_failed_minimum=0,status_check_failed_sample_count=20,status_check_failed_sum=0 1501764720000000000
> cloudwatch_aws_ec2,host=kendall-Inspiron-5577,region=us-east-1,unit=count,instance_id=<edited out for security> status_check_failed_sum=0,status_check_failed_average=0,status_check_failed_maximum=0,status_check_failed_minimum=0,status_check_failed_sample_count=5 1501764720000000000
> cloudwatch_aws_ec2,region=us-east-1,unit=bytes,instance_id=<edited out for security>,host=kendall-Inspiron-5577 disk_read_bytes_sample_count=5,disk_read_bytes_sum=0,disk_read_bytes_average=0,disk_read_bytes_maximum=0,disk_read_bytes_minimum=0 1501764720000000000
> cloudwatch_aws_ec2,region=us-east-1, ......
```

...both plugins seem to be recognized, but for some reason it is only collecting EC2 and no S3

Here is what my `/etc/telegraf/telegraf.conf` looks like (just the [[inputs.cloudwatch]] portions)...

```
[[inputs.cloudwatch]]
  region = "us-east-1"

  access_key = ""
  secret_key = ""

  period = "5m"
  delay = "5m"
  interval = "5m"

  ## Metric Statistic Namespace (required)
  namespace = "AWS/S3"
  ratelimit = 10

[[inputs.cloudwatch]]
  region = "us-east-1"

  access_key = ""
  secret_key = ""

  period = "5m"
  delay = "5m"
  interval = "5m"

  ## Metric Statistic Namespace (required)
  namespace = "AWS/EC2"
  ratelimit = 10
```

If I just run `telegraf`, I see both plugins being loaded, but data never collected...

```
kendall@kendall-Inspiron-5577:~/Development/influxdb$ telegraf
2017/08/03 10:03:43 I! Using config file: /etc/telegraf/telegraf.conf
E! Unable to append to /var/log/telegraf/telegraf.log (open /var/log/telegraf/telegraf.log: permission denied), using stderr
2017-08-03T14:03:43Z I! Starting Telegraf (version 1.3.5)
2017-08-03T14:03:43Z I! Loaded outputs: influxdb
2017-08-03T14:03:43Z I! Loaded inputs: inputs.statsd inputs.cloudwatch inputs.cloudwatch inputs.mongodb
2017-08-03T14:03:43Z I! Tags enabled: host=kendall-Inspiron-5577
2017-08-03T14:03:43Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"kendall-Inspiron-5577", Flush Interval:10s 
2017-08-03T14:03:43Z I! Started the statsd service on :8125
2017-08-03T14:03:43Z I! Statsd listener listening on:  [::]:8125
```

I waited for 15 minutes, so I know the 5 minute period was surpassed, and I didn't get any errors relating to time limits.

Bizarrare that it's not working. Here are some versions:
 
```
kendall@kendall-Inspiron-5577:~/Development/influxdb$ influx -version
InfluxDB shell version: 1.3.1
kendall@kendall-Inspiron-5577:~/Development/influxdb$ telegraf -version
Telegraf v1.3.5 (git: release-1.3 7192e68b2423997177692834f53cdf171aee1a88)
```

**Comment by KendallWeihe** [comment]
**UPDATE** -- something I noticed...

I don't know what a `Collection` is defined as, but if you notice the two cloudwatch plugins above are both `Collection 1`. I was skeptical about that so I ran a test of using two mongodb plugins (same way as the cloudwatch plugins aboe)... and they were given **different** collection numbers --> `Collection 1` and `Collection 2`.

```
kendall@kendall-Inspiron-5577:~/Development/influxdb$ telegraf --input-filter mongodb --test
2017/08/03 10:50:55 I! Using config file: /etc/telegraf/telegraf.conf
E! Unable to append to /var/log/telegraf/telegraf.log (open /var/log/telegraf/telegraf.log: permission denied), using stderr
* Plugin: inputs.mongodb, Collection 1
2017-08-03T14:50:55Z W! [inputs.mongodb] Using "mongodb://0.0.0.1:27001" as connection URL; please update your configuration to use an URL
* Plugin: inputs.mongodb, Collection 2
> mongodb,hostname=0.0.0.0,host=kendall-Inspiron-5577 repl_updates_per_sec=0i,repl_deletes_per_sec=0i,updates_per_sec=0i,ttl_passes_per_sec=0i,
```

For reference:
```
[[inputs.mongodb]]
  servers = ["0.0.0.1:27001"]
  gather_perdb_stats = true

[[inputs.mongodb]]
  servers = ["0.0.0.0"]
  gather_perdb_stats = true
```

**Comment by KendallWeihe** [comment]
I suspect this is actually caused by a configuration through AWS CloudWatch for S3. Not entirely sure what the real solution is, but I tried with two different services and it worked fine. 

Closing this issue.

**Comment by danielnelson** [comment]
@KendallWeihe I usually find missing metrics to be a mismatch between with the cloudwatch period.  You can see from the [Amazon S3 Metrics](https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html) that only daily metrics are enabled by default.  If you want to capture these you need to set the period to "24h".

If you enable the per minute metrics you would need a third cloudwatch input set to "1m".

Here is what I'm using https://github.com/influxdata/telegraf/issues/1907#issuecomment-300867109

**Comment by KendallWeihe** [comment]
Excellent sir thank you very much! I will keep this in mind for other services as well.
