### ISSUE TITLE
telegarf conf file code modifications

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3090]
Hello,

We have installed telegraf-1.3.5 on our environment, and able to collect metrics.

but, for our requirement we need to send data of each measurement....
ex: cpu, disk, system.... to seperate indices of elasticsearch ex: cpuindex, diskindex,....
 so.. can we add if conditions or any other code to make it possible......??

Thanks,

**Comment by danielnelson** [comment]
You could configure multiple elasticsearch outputs and use the various [filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options to include only the measurements you need.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
