### ISSUE TITLE
 InfluxDB Output Error: nunable to parse

### ISSUE THREAD

**Issue by JoaquinSV** [influxdata/telegraf#3091]
Hello,

I have an error trying to write data into InfluxDB. The problem is that influx can't pase a message and throws me this error:

`invalid tag format\nunable to parse`

This are some messages that cannot parse:

```
Storage,Disk=D:\\,agent_host=agent.host.1,host=telegraf.host,hostname=agent.host.1 StorageAllocationUnit=0i,StorageUsed=0i,TotalSize=0i 1501776243000000000
Storage,Disk=E:\\,agent_host=agent.host.1,host=telegraf.host,hostname=agent.host.2 StorageAllocationUnit=0i,StorageUsed=0i,TotalSize=0i 1501776298000000000
```
I think this is produced my the double backslash at the end of the tag `Disk` , because all the rejected messages has them, and none of the accepted has them.

So there is a way to replace the `\\` to `\`?

I'm usng snmp.input:
```
[[inputs.snmp.table]]
      name = "Storage"
      inherit_tags = [ "hostname" ]
      [[inputs.snmp.table.field]]
        name = "Disk"
        oid = "HOST-RESOURCES-MIB::hrStorageDescr"
        is_tag = true
      [[inputs.snmp.table.field]]
        name = "StorageAllocationUnit"
        oid = "HOST-RESOURCES-MIB::hrStorageAllocationUnits"
        is_tag = false
      [[inputs.snmp.table.field]]
        name = "TotalSize"
        oid = "HOST-RESOURCES-MIB::hrStorageSize"
        is_tag = false
      [[inputs.snmp.table.field]]
        name = "StorageUsed"
        oid = "HOST-RESOURCES-MIB::hrStorageUsed"
        is_tag = false

```
I'm using InfluxDB 1.2.2 and Telegraf 1.2.1

**Comment by danielnelson** [comment]
Line protocol has some unfortunate escaping rules: `\` can only be used to escape `,` or ` ` in the tag section and not `\`.  The consequence of this is that it is impossible to end a tag with a `\`.

I have seen a couple workarounds.  Some add a space after the tag: `Disk=\ ,agent_host=`, but personally I would change to forward slashes `Disk=/,agent_host=`.
