### ISSUE TITLE
Telegraf – is compression on the wire planned?

### ISSUE THREAD

**Issue by chiriaev** [influxdata/telegraf#3093]
My systems generate lots of metrics (millions per minute) and move them around geographies, between on premise and the public cloud. This makes me care about my bandwidth costs and want to keep them under control. 

I am asking you to consider an enhancement, which would allow real-time compression between my Telegraf-enabled end-point and the InfluxDB metric back-end.

Regards, Andrei

P.S.: doing it by peering two Telegraf instance is probably the most flexible way to achieve that... at the expense of increased latency.

**Comment by danielnelson** [comment]
I expect #2978 to be completed for the 1.4 release, which will add compression to the InfluxDB output when using http.  Would this solve you problem?

**Comment by chiriaev** [comment]
Hi, @danielnelson. Sounds good. Thanks for the prompt feedback. Regards, Andrei
