### ISSUE TITLE
Telemetry- statsd Consul doesn't send data upon container restarts !

### ISSUE THREAD

**Issue by srkurapa** [influxdata/telegraf#3094]
Is there any restart order or priority while using telegraf , Influxdb and grafana for monitoring consul ( Version 8 ) ?
Looks like the consul metrics are not being sent automatically to telegraf upon container restarts.
I would start seeing the cluster info only after a manual consul cluster restart.
( Using dogstatsd with port 8125 in consul configuration to send metrics to telegraf )

**Comment by danielnelson** [comment]
I would think that with the statsd input the order of restarts shouldn't normally matter since all data is transferred over udp.

The best place for a question like this is over at the [InfluxData Community](https://community.influxdata.com) site.
