### ISSUE TITLE
[inputs.http_response] Error in plugin if connection refused

### ISSUE THREAD

**Issue by SergeyCherepanov** [influxdata/telegraf#3095]
```
Aug 04 18:06:20 somehost telegraf[18239]: 2017-08-04T18:06:20Z E! Error in plugin [inputs.http_response]: Get https://xxx.xxx: dial tcp XX.XXX.XXX.53:443: getsockopt: connection refused
Aug 04 18:06:35 somehost telegraf[18239]: 2017-08-04T18:06:35Z E! Error in plugin [inputs.http_response]: Get https://xxx.xxx: dial tcp XX.XXX.XXX.53:443: getsockopt: connection refused
Aug 04 18:06:50 somehost telegraf[18239]: 2017-08-04T18:06:50Z E! Error in plugin [inputs.http_response]: Get https://xxx.xxx: dial tcp XX.XXX.XXX.53:443: getsockopt: connection refused
Aug 04 18:07:05 somehost telegraf[18239]: 2017-08-04T18:07:05Z E! Error in plugin [inputs.http_response]: Get https://xxx.xxx: dial tcp XX.XXX.XXX.53:443: getsockopt: connection refused
Aug 04 18:07:20 somehost telegraf[18239]: 2017-08-04T18:07:20Z E! Error in plugin [inputs.http_response]: Get https://xxx.xxx: dial tcp XX.XXX.XXX.53:443: getsockopt: connection refused
```

### Relevant telegraf.conf:

```
[[inputs.http_response]]
address = "https://xxx.xxx"
response_timeout = "5s"
method = "GET"
follow_redirects = false
response_string_match = "somestring"
interval = "15s"
[inputs.http_response.tags]
company = "sometag"
```

### System info:
```
Telegraf v1.3.5 (git: release-1.3 7192e68b2423997177692834f53cdf171aee1a88)
Ubuntu 16.04.2 LTS \n \l
```

**Comment by danielnelson** [comment]
Can you add a description of what you expect the behavior to be?

**Comment by SergeyCherepanov** [comment]
Hi @danielnelson 

Because plugin fails, it is not send a metrics in to influxdb, and I can't to catch service outage via kapacitor. I think the plugin should continue to send metrics marked as errored. May be with code 521 (cloudflare code for unreachable web-server).

**Comment by danielnelson** [comment]
We did add a result_type field to this plugin recently, should be in 1.4, I think it will solve you problem so I'm going to close this issue but feel free to reopen if I'm wrong.  https://github.com/influxdata/telegraf/pull/2814

In the meantime, you can configure Kapacitor to alert on missing metrics, it's probably worth setting this up anyway since this would alert in more error cases than we can trigger from Telegraf.

**Comment by danielnelson** [comment]
Here are the docs for how to setup the alert in Kapacitor https://docs.influxdata.com/kapacitor/v1.3/nodes/stream_node/#deadman

**Comment by SergeyCherepanov** [comment]
@danielnelson thanks, I can to wait 1.4. And I already thought about the "no data" alert.
