### ISSUE TITLE
Non-compilation issue with input zipkin plugin

### ISSUE THREAD

**Issue by Alessar** [influxdata/telegraf#3100]
There are several non-compilation errors in master branch:

```../../plugins/inputs/zipkin/handler.go:12:2: cannot find package "github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore"```

Related with https://github.com/openzipkin/zipkin-go-opentracing/commit/a3dd95664b8d598ddb25d23a1b9535206aef5d8d
And with https://github.com/influxdata/telegraf/commit/137b312fa9ebfbe8ec8f25e88b1b79cf35ef9975

**Comment by danielnelson** [comment]
Not that I'm against it, it seems like it would be good to be on the latest tag, but is there any particular reason you want to upgrade zipkin-go-opentracing library?

cc @goller

**Comment by danielnelson** [comment]
@Alessar I'm closing because I don't know the reason behind the issue, if you can provide more information then please reopen.

**Comment by Alessar** [comment]
Default `go get` behaviour is to download latest sources, so it is good that telegraf will use latest version of another libraries (I hope that another libraries will have the stable HEAD always).

**Comment by danielnelson** [comment]
Can you add the full command you are running to produce the error?

**Comment by danielnelson** [comment]
Thanks, I will get this fixed.  I recommend using the targets in the [Makefile](https://github.com/influxdata/telegraf#from-source) though in general since getting the HEAD of each dependency is bound to cause lots of problems.

**Comment by danielnelson** [comment]
After updating to the lastest zipkin-go-opentracing release version I get:
```
# github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
../../openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:333: cannot use scribeProcessorLog literal (type *scribeProcessorLog) as type thrift.TProcessorFunction in assignment:
        *scribeProcessorLog does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:341: too many arguments in call to processor.Process
        have (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
        want (int32, thrift.TProtocol, thrift.TProtocol)
```

I believe we need to wait for github.com/apache/thrift to release 0.11 in order to fix this issue, according to https://github.com/openzipkin/zipkin-go-opentracing/issues/68
