### ISSUE TITLE
taking long time to collect the data by telegraf

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3107]
Hello,

I have installed telegraf-1.3 in our environment and started collecting system metrics.. after running telegraf a day we are getting the following error.

**ERROR**
Aug 09 16:28:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T10:58:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:29:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T10:59:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:30:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:00:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:31:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:01:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:32:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:02:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:33:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:03:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:34:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:04:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:35:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:05:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:36:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:06:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)
Aug 09 16:37:00 elasticsearch_masternode telegraf[32051]: 2017-08-09T11:07:00Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (1m0s)

before i worked with telegraf-1.2.x and we got the same error to collect the metrics information.
so after going through issues i installed telegraf-1.3 even then the same issues raised.

so... can we have any solution for this........

Thanks,

**Comment by danielnelson** [comment]
What plugins do you have enabled?

**Comment by hemasalma** [comment]
cpu, disk, diskio ,system, process, mem, kernel, elasticsearch.

**Comment by danielnelson** [comment]
Can you run it until it gets stuck again and then kill it with SIGQUIT?  This should dump out all of the stack traces for the goroutines into the logs.  If you can then attach this section of the logfile I will take a look.  It would also be useful if you found the location in the logfile where Telegraf starts reporting this error and attach that section.

**Comment by hemasalma** [comment]
Hello,

sorry for the late reply....,Here is the log file of telegraf. Please take a look

[telegraf.txt](https://github.com/influxdata/telegraf/files/1222077/telegraf.txt)

**Comment by danielnelson** [comment]
From looking at that file it looks like your elasticsearch server is completely unreachable.  I think this is cascading and causing the issue with the disk input taking so long.
