### ISSUE TITLE
Telegraf input net_response plugin : no output field called "result_type"

### ISSUE THREAD

**Issue by gugansankar** [influxdata/telegraf#3111]
OS : Centos 7
Telegraf : 1.3.5

As per the docs "https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response#measurements--fields" , I would get "result_type" in the output field. But I don't get the value there. Is the value deprecated in the new version ?

Plugin Config:

```
 [[inputs.net_response]]
   protocol = "tcp"
   address = "10.11.12.169:444"
   read_timeout = "5s"
   timeout = "5s"
```

Test Output:
```
[root@localhost telegraf]# telegraf --config telegraf.conf --input-filter net_response --test
* Plugin: inputs.net_response, Collection 1
> net_response,server=10.11.12.169,port=444,protocol=tcp,host=localhost response_time=0.097724542 1502340268000000000
[root@localhost telegraf]#
```

**Comment by danielnelson** [comment]
This field is a new feature and will be in the upcoming 1.4 release.
