### ISSUE TITLE
inputs.procstat: num_fds by user seems wrong

### ISSUE THREAD

**Issue by Xat59** [influxdata/telegraf#3114]
## Bug report
I'm using inputs.procstat to count the number of file descriptor used by a specific user.
The value returned by inputs.procstat[_prefix]num_fds seems bad. 
Indeed, the returned value is not similary to this Linux shell command : 
```
lsof -u username|wc -l
```

### Relevant telegraf.conf:
[[inputs.procstat]]
  user = "myuser"
  prefix = "myprefix"

### System info:
Telegraf version : Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
OS : CentOS 6.9

### Steps to reproduce:

1. Use the input I've declared above using an existing user
2. Check the value returned by inputs.procstat
3. Compare with lsof command :
```
lsof -u username|wc -l
```

### Expected behavior:
Both values should be similar

### Actual behavior:
Values are significantly differents

Thank a lot guys!

**Comment by danielnelson** [comment]
The num_fds count here is taken from /proc/$pid/fd, which is different from lsof for a couple reasons.  The biggest is that lsof lists thinks like shared objects and the current working directory, but there are other differences that I won't pretend to understand and so I'll just say they measure different things.

I don't think there is any change to make but I hope this (somewhat) answers your question.
