### ISSUE TITLE
about Oracle database

### ISSUE THREAD

**Issue by huangpeizhi** [influxdata/telegraf#3116]
To collect the running status of the Oracle database, you need to run SQL to get the Oracle dependency library. How can this situation be integrated into the plug-in and form a whole?.

**Comment by danielnelson** [comment]
There is a pull request in progress that allows for loading database drivers https://github.com/influxdata/telegraf/pull/2785/files#diff-c9862cb8a6c0bb799256ffe4cb790095R15, take a look and see if it meets your needs.

**Comment by huangpeizhi** [comment]
thanks!
