### ISSUE TITLE
Gather raw metrics in MongoDB input

### ISSUE THREAD

**Issue by etlweather** [influxdata/telegraf#3121]
The MongoDB plugin records a few metrics in InfluxDB as "X per seconds" rather than storing the counter value. The metrics should be counters, not gauge and the "per seconds" should be measured at analysis time instead.

Having the counter, which is what the MongoDB `serverStatus` command returns for operations, queries, etc, is more flexible. If you miss a few records of data, you still have a correct value over time.

I really would like to see the counter values rather than the per-sec values.

**Comment by danielnelson** [comment]
I agree that it would be better to report the raw values.  We could change this but we need to do it while maintaining support for the old method, perhaps with an option to enable the new format defaulting to false.

**Comment by gaetanquentin** [comment]
i am using telegraf/influxdb/grafana  with interval configured for "2" seconds.

The (ops)_per_sec metrics are globaly false (select,insert,delete,updates,commands,getmore etc) :
 
- comparing offical mongostats metrics (every seconds) and telegraf metrics (interval: 2 secondes), it is impossible to have the sames values in grafana, even if doing math  /2 on metrics, or transforming them (difference, derivative). Differences are very big, and it is impossible to know why.

- more, even if math /2 would have worked, we would be obliged to keep telegraf interval at initial value (in my case 2 secondes), and never change it, or results will be worse.

So please, can you add the raw metrics ?

Regards.
