### ISSUE TITLE
Kubernetes ResourceQuota metrics from Openshift

### ISSUE THREAD

**Issue by jacksparrowrocker** [influxdata/telegraf#3122]
was wondering whether any one made a plugin for the ResourceQuota that can be extracted from the kubectl or from the oc or from API. Recently saw the kubernetes has a go-client. I am a newbie completly new to go and telegraf. Attaching a sample for the reference if any one is planning to implement a plugin for this json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test0",
                "selfLink": "/api/v1/namespaces/my-test0/resourcequotas/compute-resources",
                "uid": "a49f04d3-33d0-11e7-8865-0050569b580a",
                "resourceVersion": "23382501",
                "creationTimestamp": "2017-05-08T09:28:06Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test1",
                "selfLink": "/api/v1/namespaces/my-test1/resourcequotas/compute-resources",
                "uid": "30531678-b876-11e6-afab-0050569b580a",
                "resourceVersion": "38232441",
                "creationTimestamp": "2016-12-02T10:00:43Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "1",
                    "limits.memory": "1000Mi",
                    "pods": "2",
                    "requests.cpu": "200m",
                    "requests.memory": "1000Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test2",
                "selfLink": "/api/v1/namespaces/my-test2/resourcequotas/compute-resources",
                "uid": "29afcc8c-c609-11e6-bf2c-0050569b126b",
                "resourceVersion": "38265039",
                "creationTimestamp": "2016-12-19T16:35:33Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "1",
                    "limits.memory": "1000Mi",
                    "pods": "2",
                    "requests.cpu": "200m",
                    "requests.memory": "1000Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test3",
                "selfLink": "/api/v1/namespaces/my-test3/resourcequotas/compute-resources",
                "uid": "41836abb-b79a-11e6-afab-0050569b580a",
                "resourceVersion": "5308631",
                "creationTimestamp": "2016-12-01T07:46:23Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test4",
                "selfLink": "/api/v1/namespaces/my-test4/resourcequotas/compute-resources",
                "uid": "8b4088ed-a05f-11e6-9f19-0050569b678f",
                "resourceVersion": "38496038",
                "creationTimestamp": "2016-11-01T18:18:09Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "1500m",
                    "limits.memory": "2024Mi",
                    "pods": "3",
                    "requests.cpu": "300m",
                    "requests.memory": "2024Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test5",
                "selfLink": "/api/v1/namespaces/my-test5/resourcequotas/compute-resources",
                "uid": "906ab58e-c063-11e6-8b18-0050569b678f",
                "resourceVersion": "6510459",
                "creationTimestamp": "2016-12-12T12:07:33Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test6",
                "selfLink": "/api/v1/namespaces/my-test6/resourcequotas/compute-resources",
                "uid": "934c30b8-4f88-11e7-bb7a-0050569b580a",
                "resourceVersion": "38496058",
                "creationTimestamp": "2017-06-12T16:02:46Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "1500m",
                    "limits.memory": "1500Mi",
                    "pods": "3",
                    "requests.cpu": "300m",
                    "requests.memory": "1500Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test7",
                "selfLink": "/api/v1/namespaces/my-test7/resourcequotas/compute-resources",
                "uid": "e08d42d7-7d37-11e7-8b03-0050569b678f",
                "resourceVersion": "38441895",
                "creationTimestamp": "2017-08-09T19:21:00Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test8",
                "selfLink": "/api/v1/namespaces/my-test8/resourcequotas/compute-resources",
                "uid": "8c062344-1631-11e7-98f2-0050569b126b",
                "resourceVersion": "19107416",
                "creationTimestamp": "2017-03-31T16:46:11Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test9",
                "selfLink": "/api/v1/namespaces/my-test9/resourcequotas/compute-resources",
                "uid": "6d0f0acb-08ce-11e7-9ca2-0050569b580a",
                "resourceVersion": "38104626",
                "creationTimestamp": "2017-03-14T15:53:54Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "500m",
                    "limits.memory": "500Mi",
                    "pods": "1",
                    "requests.cpu": "100m",
                    "requests.memory": "500Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test10",
                "selfLink": "/api/v1/namespaces/my-test10/resourcequotas/compute-resources",
                "uid": "2385b0e1-e806-11e6-a504-0050569b126b",
                "resourceVersion": "12465650",
                "creationTimestamp": "2017-01-31T22:39:34Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test11",
                "selfLink": "/api/v1/namespaces/my-test11/resourcequotas/compute-resources",
                "uid": "1a33a161-e3e7-11e6-87b3-0050569b678f",
                "resourceVersion": "38496068",
                "creationTimestamp": "2017-01-26T16:47:19Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "2500m",
                    "limits.memory": "2500Mi",
                    "pods": "5",
                    "requests.cpu": "500m",
                    "requests.memory": "2500Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test12",
                "selfLink": "/api/v1/namespaces/my-test12/resourcequotas/compute-resources",
                "uid": "19a30cc0-f856-11e6-844a-0050569b126b",
                "resourceVersion": "14671211",
                "creationTimestamp": "2017-02-21T16:52:16Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test13",
                "selfLink": "/api/v1/namespaces/my-test13/resourcequotas/compute-resources",
                "uid": "c689677f-6555-11e7-8b03-0050569b678f",
                "resourceVersion": "38232474",
                "creationTimestamp": "2017-07-10T09:54:33Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "500m",
                    "limits.memory": "500Mi",
                    "pods": "1",
                    "requests.cpu": "100m",
                    "requests.memory": "500Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test14",
                "selfLink": "/api/v1/namespaces/my-test14/resourcequotas/compute-resources",
                "uid": "13b38275-b802-11e6-8cfa-0050569b126b",
                "resourceVersion": "15614466",
                "creationTimestamp": "2016-12-01T20:09:34Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test15",
                "selfLink": "/api/v1/namespaces/my-test15/resourcequotas/compute-resources",
                "uid": "7ec0e9c3-2a9f-11e7-98f2-0050569b126b",
                "resourceVersion": "22073857",
                "creationTimestamp": "2017-04-26T16:43:37Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "0",
                    "limits.memory": "0",
                    "pods": "0",
                    "requests.cpu": "0",
                    "requests.memory": "0"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test16",
                "selfLink": "/api/v1/namespaces/my-test16/resourcequotas/compute-resources",
                "uid": "00872825-f921-11e6-aef2-0050569b678f",
                "resourceVersion": "38496069",
                "creationTimestamp": "2017-02-22T17:04:41Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "80",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "80",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "1500m",
                    "limits.memory": "1500Mi",
                    "pods": "3",
                    "requests.cpu": "300m",
                    "requests.memory": "1500Mi"
                }
            }
        },
        {
            "kind": "ResourceQuota",
            "apiVersion": "v1",
            "metadata": {
                "name": "compute-resources",
                "namespace": "my-test17",
                "selfLink": "/api/v1/namespaces/my-test17/resourcequotas/compute-resources",
                "uid": "434cf123-0516-11e7-9ca2-0050569b580a",
                "resourceVersion": "38496072",
                "creationTimestamp": "2017-03-09T22:18:03Z"
            },
            "spec": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "scopes": [
                    "NotTerminating"
                ]
            },
            "status": {
                "hard": {
                    "limits.cpu": "12500m",
                    "limits.memory": "80Gi",
                    "pods": "10",
                    "requests.cpu": "12500m",
                    "requests.memory": "80Gi"
                },
                "used": {
                    "limits.cpu": "500m",
                    "limits.memory": "500Mi",
                    "pods": "1",
                    "requests.cpu": "100m",
                    "requests.memory": "500Mi"
                }
            }
        }
    ]
}

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
