### ISSUE TITLE
Extend cloudwatch input to allow extended statistics

### ISSUE THREAD

**Issue by paurullan** [influxdata/telegraf#3123]
## Feature Request

The Cloudwatch API allows to extract percentiles («extended statistics») but the plugin in its current form does not use it.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html

### Proposal:

Expand that configuration and plugin to be able to retrieve a percentile value.

### Current behavior:

The code directly asks for a getStatisticsInput and gets a cloudwatch.GetMetricStatistics
https://github.com/influxdata/telegraf/blob/release-1.3/plugins/inputs/cloudwatch/cloudwatch.go#L286

### Desired behavior:

The user may use the same --extended-statistic p95 that the CLI API allows.

### Use case: [Why is this important (helps with prioritizing requests)]

This would allow to fully recover the data from Cloudwatch, allowing to insert it into influx and make complex alarms.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you yet.

The cloudwatch plugin has seen numerous updates over the last few years and has talk about collecting metrics in the config now:

```toml
  #  ## Statistic filters for Metric.  These allow for retrieving specific
  #  ## statistics for an individual metric.
  #  # statistic_include = [ "average", "sum", "minimum", "maximum", sample_count" ]
  #  # statistic_exclude = []
  #
  #  ## Dimension filters for Metric.  All dimensions defined for the metric names
  #  ## must be specified in order to retrieve the metric statistics.
  #  ## 'value' has wildcard / 'glob' matching support such as 'p-*'.
  #  [[inputs.cloudwatch.metrics.dimensions]]
  #    name = "LoadBalancerName"
  #    value = "p-example"
```

Do using these settings resolve the original request?

Thanks
