### ISSUE TITLE
Feature Request: Add fields in docker input plugin to monitor swarm desired and running replicas

### ISSUE THREAD

**Issue by adityacs** [influxdata/telegraf#3125]
### Proposal:

Add a measurement with below fields in docker input plugin:
1. swarm serviceID
2. swarm taskID
3. swarm.service.desired.replicas
4. swarm.service.running.replicas
5. oomKilled(true/false)

### Use case

It will help to monitor if the cluster is maintaining expected number of replicas. Also, gives information on containers getting killed due to OOM.

**Comment by adityacs** [comment]
Important thing to consider here is that the above information(desired replicas, service ID, task ID) is available only form swarm manager. So, if we install telegraf agent in all swarm managers we will be getting duplicate data. 

Is there a way to handle this in telegraf?

**Comment by danielnelson** [comment]
Telegraf doesn't help with that.  It would be something the administrator would handle by giving each instance the appropriate configuration.  If this does become part of the docker input plugin, we will need to make sure there is a way to disable it.

**Comment by adityacs** [comment]
Hmm. Have to provide a parameter in config like "collect_swarm_metrics=false".

**Comment by adityacs** [comment]
@danielnelson Could you please review this PR #3141

**Comment by danielnelson** [comment]
Thanks @adityacs, will be in 1.5.0

**Comment by adityacs** [comment]
@danielnelson Thank you so much.
