### ISSUE TITLE
[windows] `content_encoding' is not defined in `*influxdb.InfluxDB'

### ISSUE THREAD

**Issue by kmonsoor** [influxdata/telegraf#3130]
### Relevant telegraf.conf:
[[outputs.influxdb]]
  . . .
  content_encoding = "gzip"

### System info:
* Windows 8.1
* Telegraf 1.3.5

### Steps to reproduce:

1. Download Telegraf for WIndows
2. Include `content_encoding = "gzip"` under [[outputs.influxdb]] section
3. run telegraf

### Expected behavior:
Telegraf start properly.

### Actual behavior:
Telegraf refuse to start with the error message:
```
E! Error parsing C:\\Program Files\\telegraf\\telegraf.conf, line 24: field corresponding to `content_encoding' is not defined in `*influxdb.InfluxDB'
```

### Additional info
N/A

**Comment by danielnelson** [comment]
This option is available only in the upcoming Telegraf 1.4
