### ISSUE TITLE
Ping Plugin add 0ms when host is not responding

### ISSUE THREAD

**Issue by gangsterrapper22** [influxdata/telegraf#3132]
I use telegraf to ping several hosts and sent the output to InfluxDB which will be pulled then by Grafana which works without problems. Can you please add in the ping plugin when an Host is not responding or offline that 0ms is written to the database that the graph in Grafana won't break if an Host isn't responding? The Graph will first continue when the Host is online again. 

Thank you

**Comment by danielnelson** [comment]
You can do this with the fill option on your query.  We can't do this on Telegraf because 0 is semantically different than an unset value, and many people use this to detect when a host is not responding.

**Comment by gangsterrapper22** [comment]
Sorry for open it again. I tested now a little bit and I have seen if the service telegraf is stopped for a longer time and the graph for average_response_time is not there anymore on the grafana graph, because no data are there and telegraf is started again and the host is still down, then I get only the graph for Package Loss and not for the response time anymore. Is it maybe possible, that you can add the 0ms value and create also an parameter for the telegraf.conf if this value is wanted or not, so that is optional?

Thanks.

**Comment by danielnelson** [comment]
Can you help me understand what the problem is with the graph not showing any data?

**Comment by gangsterrapper22** [comment]
I got it now to work when the host is down, that Grafana will add 0 Values and the graph doesn't break. Which you can see in the attached Screenshot grafana.png. 

When I stop the telegraf service and the host is still down and the telegraf service is started again and no values will be provied for the response time because the host is still down then no graph will be generated by grafana for the response time because no data ere there for this value. The graph will first continue when the host is back again. See also attached Screenshot grafana1.png.

I hope it is now clear what I mean.
![grafana](https://user-images.githubusercontent.com/26838368/29469385-44bbeea6-8448-11e7-9100-1e6fed54c1f1.png)
![grafana1](https://user-images.githubusercontent.com/26838368/29469384-44b5dbba-8448-11e7-94c5-0461d8984e5a.png)

**Comment by danielnelson** [comment]
The graph is empty, but what I don't understand is why this is a problem?

**Comment by gangsterrapper22** [comment]
The problem is when an Host is down and the telegraf service will be started and for example you do only display the response time, then you will get no data and then you have also no graph. If you will add then the 0ms that will be written the in the database then you will get also an graph drawn instead of no data.

I hope you understand what I mean.

**Comment by danielnelson** [comment]
I understand that there is no graph in this case, but what I don't understand is why you need a graph here.  What is wrong with no graph?  For instance, is it a problem for alerting?

**Comment by gangsterrapper22** [comment]
For example if I only want to display the average response time of an host which is currently not available for whatever reason then I get no data points anymore in Grafana because no value is provided there and it looks like for example that maybe the service isn't running or the config isn't correct or whatever.  See also attached Screenshot what I mean then if I only want to display the response time without packet loss or any other option which is provided by telegraf. It isn't an problem for reporting but maybe then an cosmetical change.

![grafana2](https://user-images.githubusercontent.com/26838368/29477627-6e5367c8-8469-11e7-8489-76c632b4c76b.png)

**Comment by danielnelson** [comment]
Okay, got it.  We still won't want to report 0 when we mean no value, but perhaps you can have your query also get one of the fields that does report when the host is down, such as `packets_received` or `percent_packet_loss`, this way your graph will still show something when the host is down.

**Comment by gangsterrapper22** [comment]
I have added now packets_received and this changes then to 0 if the host is down. Is there a way to combine this with the graph for average response or is this not possible or that the graph for packet_received is only shown when the value is 0?

Thanks.

**Comment by danielnelson** [comment]
I don't think so.  Maybe you could subtract the field from itself so its always 0?  `select packet_received - packet_received from ...`

**Comment by gangsterrapper22** [comment]
I will try that if I can get this to work. Thanks. Or can you maybe tell me what I have to modify that I can add the 0ms value in the source of the plugin that I have it available if you don't want to add it?

Thanks.

**Comment by danielnelson** [comment]
For non-Windows you just would need to remove these if statements: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ping/ping.go#L120

**Comment by gangsterrapper22** [comment]
Thanks for your tip to remove the if statements. I have done this now and I get now 0ms when the host is not there but I think I shouldn't have removed all if statements because the packet loss also show 0 instead of 100%.

**Comment by danielnelson** [comment]
Not sure, here is what I would expect your diff to be:
```diff
--- a/plugins/inputs/ping/ping.go
+++ b/plugins/inputs/ping/ping.go
@@ -117,18 +117,10 @@ func (p *Ping) Gather(acc telegraf.Accumulator) error {
                                "packets_received":    rec,
                                "percent_packet_loss": loss,
                        }
-                       if min > 0 {
-                               fields["minimum_response_ms"] = min
-                       }
-                       if avg > 0 {
-                               fields["average_response_ms"] = avg
-                       }
-                       if max > 0 {
-                               fields["maximum_response_ms"] = max
-                       }
-                       if stddev > 0 {
-                               fields["standard_deviation_ms"] = stddev
-                       }
+                       fields["minimum_response_ms"] = min
+                       fields["average_response_ms"] = avg
+                       fields["maximum_response_ms"] = max
+                       fields["standard_deviation_ms"] = stddev
                        acc.AddFields("ping", fields, tags)
                }(url)
        }
```

**Comment by gangsterrapper22** [comment]
I did also the same changes as you did, but I selected the wrong host in Grafana which had no package loss at the moment. If I take now my test host and set it down then I can see Response Time 0ms and Package Loss 100% in this case and if I take it online again then I see the normal response time and the package loss will switch 0% then. Thanks for your great help.
