### ISSUE TITLE
 field corresponding to 'report_active' is not defined in '*system.CPUStats'

### ISSUE THREAD

**Issue by cybershambles** [influxdata/telegraf#3134]
### Relevant telegraf.conf:
```
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = true
```

### System info:

[root@ip-172-31-34-65 ~]# telegraf --version
Telegraf v1.3.5 (git: release-1.3 7192e68b2423997177692834f53cdf171aee1a88)

[root@ip-172-31-34-65 ~]# uname -a
Linux ip-172-31-34-65.ap-southeast-2.compute.internal 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:

1. Add input cpu with report_active = true
2. run test/run service.

### Expected behavior:
cpu logs working as expected with active stats.

### Actual behavior:

[root@ip-172-31-34-65 ~]# telegraf --config /etc/telegraf/telegraf.conf --test
2017/08/18 10:18:18 E! Error parsing /etc/telegraf/telegraf.conf, line 34: field corresponding to `report_active' is not defined in `*system.CPUStats'

### Additional info:

Following doco - https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/MEM_README.md

Needs to be updated if this function was removed.

**Comment by danielnelson** [comment]
This option was recently added and will be available in the 1.4 release.  We have a release candidate available and if you able to test it would be helpful.  https://github.com/influxdata/telegraf/releases/tag/1.4.0-rc1
