### ISSUE TITLE
Not getting metrics for volumes mounted in sub directories

### ISSUE THREAD

**Issue by estvar19x84** [influxdata/telegraf#3139]
Hi all

I've the following setup in a couple of servers

/var <- regular ext4 fs
/var/data <- nfs 
/var/logs < - nfs

When I run a test like
telegraf -config /etc/telegraf/telegraf.conf -input-filter disk -test

I see that all the volumes are listed, but only /var is written to the influxdb backend.

Any ideas?

**Comment by estvar19x84** [comment]
I'm on CentOS 7 and it seems that the telegraf user cannot df the missing devices.

**Comment by danielnelson** [comment]
Can you add the output of `cat /etc/mtab`?

**Comment by danielnelson** [comment]
@estvar19x84 I may have misunderstood your last comment, are you saying that something like this does not show the device?
```
sudo -u telegraf df
```

**Comment by estvar19x84** [comment]
Hey sorry it took me so long to reply. When using sudo telegraf it is able to show the devices. Seems like the regular installation doesn’t run with sudo, so in the mean time I added a custom input.exec.

--
Esteban

**Comment by danielnelson** [comment]
My example is just running df as the telegraf user because of the `-u`.  So then you needed root in order to see the devices?

**Comment by estvar19x84** [comment]
Exactly I need root ☺

--
Esteban

**Comment by danielnelson** [comment]
Okay, I'm going to close this issue then.  I'm don't think there is a way we can do this via sudo unless we shell out to cat, and this would probably be unlikely to be accepted by gopsutil.  It might be possible to change how they are mounted in a way that it works but I'll leave that to you.

Perhaps in the future we will have a way to run plugins under sudo via grpc.
