### ISSUE TITLE
Gettin negative metrics from Cisco devices.

### ISSUE THREAD

**Issue by SkabarOne** [influxdata/telegraf#3143]
![sketch 6](https://user-images.githubusercontent.com/31215103/29525636-04ef6b94-869c-11e7-8a7a-157a191933a9.png)

Hi guys!  Gettin this metrics from cisco ASA. And this problem happends not only with this device. Metrics is fine, but allways in some time i gettin negative metric...

My **telegraf.conf** for this device:

`[[inputs.snmp]]
    agents = [ "10.254.254.254" ]
    version = 2
    community = "Mycom"

  [[inputs.snmp.field]]
      name = "CPUASAhostname"
      oid = "RFC1213-MIB::sysName.0"
      is_tag = true
[[inputs.snmp.field]]
      name = "CPUASAuptime"
      oid = "SNMPv2-MIB::sysUpTime.0"

  [[inputs.snmp.table]]
      name = "CPUASAinterface"
      inherit_tags = [ "CPUASAhostname" ]
      oid = "IF-MIB::ifTable"
   [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
 [[inputs.snmp.table]]
      name = "CPUASAinterface"
      inherit_tags = [ "CPUASAhostname" ]
      oid = "IF-MIB::ifXTable"
     [[inputs.snmp.table.field]]
         name = "ifDescr"
         oid = "IF-MIB::ifDescr"
         is_tag = true`

Somebody know how to solve this problem??

**Comment by SkabarOne** [comment]
PS:
Negative metrics data allways like  "-8" or "-16" gbps.

**Comment by danielnelson** [comment]
Can you show what has been saved into the database at these timestamps and also your graphs query?

**Comment by SkabarOne** [comment]
@danielnelson 
![sketch 7](https://user-images.githubusercontent.com/31215103/29558161-f4dae402-8733-11e7-9e73-87f52209ed6c.png)

My query.

**Comment by SkabarOne** [comment]
@danielnelson  how can i show u data from influxdb?

**Comment by SkabarOne** [comment]
@danielnelson 
 ![sketch 8](https://user-images.githubusercontent.com/31215103/29564855-2881ae18-874c-11e7-9164-56be44df2c64.png)

I think i found a problem. Need to set "non-negative-derivative". 

What do u think, man?

**Comment by danielnelson** [comment]
Yes, this is exactly what I would recommend.

**Comment by SkabarOne** [comment]
@danielnelson 
![sketch 9](https://user-images.githubusercontent.com/31215103/29610164-0bcc31b0-8802-11e7-8d07-7e56f9e446ab.png)

Now there is no data at all (not "0"), where before they were negative. And this gap in the data is long in 20 seconds, and occurs every 6 minutes. It only happens on some interfaces, not at all...

**Comment by danielnelson** [comment]
There are a couple things I would check:
- Are there any messages in your telegraf.log?
- Do you have other metrics you are collecting and do they also show these gaps?
