### ISSUE TITLE
Missing metrics from `serverstatus.wiredTiger.cache` in mongodb input plugin

### ISSUE THREAD

**Issue by phenomenes** [influxdata/telegraf#3146]
## Feature Request

Add missing `serverstatus.wiredTiger.cache` metrics to mongodb input plugin.

### Current behavior:

The mongodb input plugin only provides two metrics:
- tracked dirty bytes in the cache
- bytes currently in the cache

and they are not even raw metrics but percentages. The current plugin is not designed in such a way that can be easily extended to add the rest of the metrics (71 in total).

### Desired behavior:

I would like to have raw metrics of the 71 fields in `serverStatus.wiredTiger.cache`.

### Use case
For example, we would be able to have an overview of the IO activity, as expressed here:
https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.wiredTiger.cache

**Comment by danielnelson** [comment]
Added in #3281

**Comment by Veeresh-dot-Pattar** [comment]
Hi I am also not able to get wiredTiger info from db.serverStatus() and also some other metrics are missing . My mongo version 4.4.4 . and I am connecting to mongodb atlas. Please suggest if you have solution for this.
