### ISSUE TITLE
NSQ plugin not compatible with latest release 

### ISSUE THREAD

**Issue by Ashtonian** [influxdata/telegraf#3147]
## Bug report
The nsq input plugin uses the /stats http endpoint which has changed its format in March. 

### Relevant telegraf.conf:
Used the following to generate the config. 
```
./telegraf --output-filter nsq config
```
### System info:
Telegraf: latest, OSX
### Steps to reproduce:
1. Run local instance of NSQ - `docker run --name nsqd -p 4150:4150 -p 4151:4151 nsqio/nsq nsqd` More info:  http://nsq.io/overview/quick_start.html 
2. Publish test message with `curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'`
3. Verify `http://localhost:4151/stats?format=json` returns data. This is the endpoint telegraf uses. 
4. Run telegraf in test mode with generated config `./telegraf --config telegraf.conf --test`

### Expected behavior:
Telegraf to report Topic/Client/Channel stats
### Actual behavior:
Telegraf reports 0 topics. 
### Additional info:
This seems to have been caused by changes in the latest release -  https://github.com/nsqio/nsq/releases/tag/v1.0.0-compat

This will break functionality for nsq versions < 1.0.

**Comment by danielnelson** [comment]
#2672

**Comment by danielnelson** [comment]
Thanks for the fix @Ashtonian, this will be released in 1.4.0.
