### ISSUE TITLE
NTP plugin incorrectly parses shared memory remotes

### ISSUE THREAD

**Issue by jawi** [influxdata/telegraf#3162]
### Relevant telegraf.conf:

```
[[inputs.ntpq]]
   dns_lookup = false
```

### System info:

- Telegraf >= 1.3.5;
- Linux (version not relevant);
- latest [NTPsec](https://www.ntpsec.org/).

### Steps to reproduce:

1. use NTPsec instead of NTP as time daemon;
2. use the shared memory driver to use a local GPS+PPS reference;
3. observe that the output of `ntpq` is using aliases like `SHM(0)` & `SHM(1)` for the GPS/PPS remotes.

### Expected behaviour:

The measurements of both the `SHM(0)` and `SHM(1)` remotes to appear in Influx for my host.

### Actual behaviour:

Only the measurements of a (non-existing) remote `SHM` appears for my host. 

### Additional info:

The issue was introduced with the fix for #2386.

The output of ntpq:

```
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*SHM(1)          .PPS.            0 l    8   16  377    0.000    0.001   0.000
xSHM(0)          .GPS.            0 l    2    2  377    0.000  -116.97   1.414
```

**Comment by jawi** [comment]
Created a PR (#3163) that fixes this issue.

**Comment by danielnelson** [comment]
Thanks @jawi, this will be in 1.4.0
