### ISSUE TITLE
Issue with Multiple telegrafs on different machines inserting to a single measurement

### ISSUE THREAD

**Issue by taichatha** [influxdata/telegraf#3168]
### Relevant telegraf.conf:
```
[[inputs.exec]]
   commands = ["/etc/telegraf/test.sh"]
   timeout = "5s"
   data_format = "influx"
```

###Script
`
...
echo "file,host=$HOSTNAME,file="$file" size_bytes=$bytes,days=$days"
`

## Bug report
I have three, and will have more machines, that are running telegraf. I want to collect data from all these machines, and then insert them to a single measurement, `files`. 
_(I am aware of **filestat**, but I do need the days a file has been in a directory. And as of right now, I don't think I can make that calculation via a query)_

However it looks like one of the machines takes priority, and the other two machine's data doesn't get inserted. I can verify this because I have the hostname passed in, and only one of the machines end up in the measurement. 

When I give each machine it's own measurement, ie `file_on_a`, `file_on_b`, and `file_on_c`, the data gets added to their respective measurements.

machine 1 script
`echo "file_on_a,host=$HOSTNAME,file="$file" size_bytes=$bytes,days=$days"`

machine 2 script
`echo "file_on_b,host=$HOSTNAME,file="$file" size_bytes=$bytes,days=$days"`

machine 3 script
`echo "file_on_c,host=$HOSTNAME,file="$file" size_bytes=$bytes,days=$days"`

 So it's not an issue with multiple telegrafs speaking to a single influx database. I am assuming it has to do with sending data to a single measurement.

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf V: telegraf-1.3.5-1.x86_64.rpm 
OS: RedHat 7

### Expected behavior:
All data from all the machines are in the machine get inserted into a measurement.
### Actual behavior:
Only a single machine's data gets inserted into a measurement.

**Comment by danielnelson** [comment]
So long as the tags are not identical you can insert with the same measurement name.  Here is an example influx cli session:
```
$ influx
Connected to http://localhost:8086 version 1.3.4
InfluxDB shell version: 1.3.4
> use telegraf
Using database telegraf
> insert example,host=a value=1 1503600942595701108
> insert example,host=b value=1 1503600942595701108
> insert example,host=c value=1 1503600942595701108
> select * from example
name: example
time                host value
----                ---- -----
1503600942595701108 a    1
1503600942595701108 c    1
1503600942595701108 b    1
```

If the host were the same on all the points, then they would overwrite each other.

**Comment by taichatha** [comment]
@danielnelson 
Yeah they aren't identical inserts, they each have distinct host names. But only one of the three is getting added to the measurement.

Filestat also is exhibiting the same behaviour. It's only adding a single machine's data, not all three.

It's not an issue when I am in influxdb. The issue arises sending data from telegraf to influxdb. Maybe a socket issue? The messages might get dropped?

**Comment by danielnelson** [comment]
> Maybe a socket issue? The messages might get dropped?

It is possible if you are using UDP, otherwise if there is a communication problem you should see something in the logs for the affected Telegraf.

**Comment by taichatha** [comment]
My mistake. I think I've realized the problem.
Drop Measuremnt

...

10 seconds later...
name: file
time                 days  file                          host      size_bytes
----                 ----  ----                          ----      ----------
2017-08-24T20:07:10Z 90.07 ‘/health.xml’ a 42
2017-08-24T20:04:20Z 90.07 ‘/crap.xml’   a 42



10 seconds later...
time                 days  file                          host      size_bytes
----                 ----  ----                          ----      ----------
2017-08-24T20:07:20Z 90.07 ‘health.xml’ a 42
2017-08-24T20:07:10Z 90.07 ‘health.xml’ a 42
2017-08-24T20:04:30Z 90.07 ‘crap.xml’   b 42
2017-08-24T20:04:20Z 90.07 ‘crap.xml’   b 42


10 seconds later...
time                 days  file                          host      size_bytes
----                 ----  ----                          ----      ----------
2017-08-24T20:07:30Z 90.07 ‘health.xml’ a 42
2017-08-24T20:07:20Z 90.07 health.xml’ a 42
2017-08-24T20:07:10Z 90.07 ‘health.xml’ a 42
2017-08-24T20:04:40Z 90.07 ‘crap.xml’   b 42
2017-08-24T20:04:30Z 90.07 ‘crap.xml’   b 42
2017-08-24T20:04:20Z 90.07 ‘crap.xml’   b 42


Looks like it was getting added. I was just mis reading it because of the time! It seems machine a is 3 minutes ahead of machine b for some reason. I guess telegraf uses the time of the machine?

**Comment by danielnelson** [comment]
> I guess telegraf uses the time of the machine?

Yes, and Telegraf sends all metrics with an explicit time stamp.

Glad you have it figured out, I'm guess I can close this issue.

**Comment by taichatha** [comment]
Thanks for talking it out with me!

**Comment by taichatha** [comment]
@danielnelson Is there a way to turn off the explicit timestamp option?

**Comment by danielnelson** [comment]
No, there is no option for this.  I highly recommend using ntpd or some other time synchronization method.
