### ISSUE TITLE
Telegraf and hddtemp error

### ISSUE THREAD

**Issue by Lokotito** [influxdata/telegraf#3169]
I have a strange log output in telegraf, and seams hddtemp didn't pass values.

```
server telegraf[4482]: 2017-08-24T15:52:40Z E! Error in plugin [inputs.hddtemp]: dial tcp 127.0.0.1:7634: getsockopt: connection $
server influxd[694]: [httpd] ::1 - - [24/Aug/2017:11:52:40 -0400] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "-$
server telegraf[4482]: 2017-08-24T15:52:50Z E! Error in plugin [inputs.hddtemp]: dial tcp 127.0.0.1:7634: getsockopt: connection $
```

my telegraf config for hddtemp:

```
#Monitor disks' temperatures using hddtemp
[[inputs.hddtemp]]
#address = "127.0.0.1:7634"
devices = ["sdb", "sdc"]
```

in terminal "sudo hddtemp" gives correct values for this drives

runing in Debian Jessie (3.16.0-4-amd64) with Influxdb 1.3.4-1, telegraf 1.3.5

**Comment by Lokotito** [comment]
Sorry my bad, is not an issue; how to fix it:
$ sudo nano /etc/default/hddtemp
change -> RUN_DAEMON="true"

Restart services. Error gone.

**Comment by danielnelson** [comment]
Thanks for the update, glad you got it working.
