### ISSUE TITLE
Add 'FileVersion' property to Windows executable

### ISSUE THREAD

**Issue by absolutejam** [influxdata/telegraf#3171]
### Proposal:

Windows binaries should have their version number stored within the metadata that is accessible via the 'Details' tab.

I know this seems like a minuscule thing, but I have varying versions of the telegraf binary and I'm trying to audit them and ensure they're the right version. As 1.3 currently crashes when collecting Windows performance counters, I am having to downgrade the binary to an earlier version that I have saved to disk. I'm not sure what version it is and I can't seem to download old versions from the Releases page, so I'm just comparing file hashes at the minute and deploying the old one - It would be a lot better for visibility sake if the version number was recorded.

Apologies, but I don't know how you build the binaries, but I was hoping this could be a small extra in the build process?

### Use case: [Why is this important (helps with prioritizing requests)]

A more seamless upgrade experience and auditability.

**Comment by danielnelson** [comment]
Maybe this will be useful https://github.com/josephspurrier/goversioninfo
