### ISSUE TITLE
Consul input plugin does not include healthchecks for consul service itself

### ISSUE THREAD

**Issue by jeroenjacobs1205** [influxdata/telegraf#3172]
The Consul input plugin provides an empty service_name tag for Consul itself.

Example query:

`SELECT last("status") FROM "consul_health_checks" GROUP BY "service_name"`

Result:

```
name: consul_health_checks
tags: service_name=
time                last
----                ----
1503650070000000000 passing

name: consul_health_checks
tags: service_name=concourse
time                last
----                ----
1503650070000000000 passing

name: consul_health_checks
tags: service_name=influxdb
time                last
----                ----
1503650070000000000 passing

name: consul_health_checks
tags: service_name=sonarqube
time                last
----                ----
1503650070000000000 critical

name: consul_health_checks
tags: service_name=vault
time                last
----                ----
1503650070000000000 passing

```

I'm not seeing anything for the Consul service itself.

The first entry has an empty service_name tag, I guess this is the Consul serf health status, but it's not labeled correctly.

Would it be possible to add tag this with service_name "consul" or "serf_health" or something like that.

This discrepancy makes it hard to include it into our dashboards.

**Comment by danielnelson** [comment]
This value comes from https://www.consul.io/api/health.html#list-checks-in-state, and I prefer not to synthesize data that is not in line with it.  I'm not very familiar with Consul's data model, but would it be possible to use `check_id`?

**Comment by danielnelson** [comment]
It might be helpful to check out Chronograf's Consul dashboards as well: https://github.com/influxdata/chronograf/tree/master/canned

cc @goller

**Comment by danielnelson** [comment]
@jeroenjacobs1205 I'm going to close, let me know if the check_id does not work.
