### ISSUE TITLE
Telegraf Build Failure

### ISSUE THREAD

**Issue by deepujain** [influxdata/telegraf#3174]
>$ pwd
/Users/uId/Documents/ebay/krylov/newtelegraf/telegraf
$ echo $GOPATH
/Users/uId/Documents/ebay/godeps:/Users/uId/Documents/ebay/krylov/newtelegraf/telegraf
$ make

>/Library/Developer/CommandLineTools/usr/bin/make telegraf
go build -i -o telegraf -ldflags " -X main.commit=e400fcf5 -X main.branch=master" ./cmd/telegraf/telegraf.go
cmd/telegraf/telegraf.go:16:2: use of internal package not allowed
make[1]: *** [telegraf] Error 1
make: *** [all] Error 2

**Comment by goller** [comment]
Hey there @deepujain, which version of go are you using?

**Comment by deepujain** [comment]
>$ go version
go version go1.8.3 darwin/amd64
LM-SJL-11004865:telegraf dvasthimal$

**Comment by deepujain** [comment]
>/Library/Developer/CommandLineTools/usr/bin/make telegraf
go build -i -o telegraf -ldflags " -X main.commit=e400fcf5 -X main.branch=master" ./cmd/telegraf/telegraf.go
cmd/telegraf/telegraf.go:16:2: use of internal package not allowed
make[1]: *** [telegraf] Error 1
make: *** [all] Error 2
$ go version
go version go1.9 darwin/amd64
$ 

$ echo $GOPATH
/Users/UID/Documents/company/godeps:/Users/UID/Documents/company/krylov/newtelegraf/telegraf
$

**Comment by danielnelson** [comment]
I think this is caused by not having telegraf in the directory `src/github.com/influxdata/telegraf` inside your GOPATH.

**Comment by deepujain** [comment]
I have two paths in GOPATH. One is the external deps and other is the telegraf project itself. 
Once i started compilation of github, i noticed that src/github.com was created inside telegraf. That was strange. 

I copied telegraf from godeps and moved to influx/telegraf/src/github.com (BOth paths in GOPATH).

>$ echo $GOPATH
/Users/dvasthimal/Documents/ebay/krylov/godeps:/Users/dvasthimal/Documents/ebay/krylov/influx/telegraf
LM-SJL-11004865:telegraf dvasthimal$ ls -l /Users/dvasthimal/Documents/ebay/krylov/godeps/src/github.com/influxdata/
total 0
drwxr-xr-x  22 dvasthimal  110133969   748 Aug 25 14:41 tail
drwxr-xr-x  32 dvasthimal  110133969  1088 Aug 25 14:54 telegraf
drwxr-xr-x   8 dvasthimal  110133969   272 Aug 25 14:42 usage-client
LM-SJL-11004865:telegraf dvasthimal$ ls -l /Users/dvasthimal/Documents/ebay/krylov/influx/telegraf/src/github.com/influxdata/
total 0
drwxr-xr-x  22 dvasthimal  110133969  748 Aug 25 14:51 tail
drwxr-xr-x  20 dvasthimal  110133969  680 Aug 25 14:51 toml
drwxr-xr-x   6 dvasthimal  110133969  204 Aug 25 14:51 wlog
LM-SJL-11004865:telegraf dvasthimal$ ls -l /Users/dvasthimal/Documents/ebay/krylov/influx/telegraf/src/github.com/influxdata/
total 0
drwxr-xr-x  22 dvasthimal  110133969   748 Aug 25 14:51 tail
drwxr-xr-x  32 dvasthimal  110133969  1088 Aug 25 14:54 telegraf
drwxr-xr-x  20 dvasthimal  110133969   680 Aug 25 14:51 toml
drwxr-xr-x   6 dvasthimal  110133969   204 Aug 25 14:51 wlog
LM-SJL-11004865:telegraf dvasthimal$ make
/Library/Developer/CommandLineTools/usr/bin/make deps
go get github.com/sparrc/gdm
gdm restore
/Library/Developer/CommandLineTools/usr/bin/make telegraf
go build -i -o telegraf -ldflags " -X main.commit=8ecc5863 -X main.branch=master" ./cmd/telegraf/telegraf.go
cmd/telegraf/telegraf.go:16:2: use of internal package not allowed
make[1]: *** [telegraf] Error 1
make: *** [all] Error 2

**Comment by deepujain** [comment]
1. I am compiling telegraf, why should i have telegraf inside src/github.com via go get ?
2. If I have two paths in GOPATH, why is a new folder src/github.com is being created again inside telegraf directory ?

**Comment by danielnelson** [comment]
I'm not sure what the answer to your questions are, but my guess is that the compile error is related to there being two copies of telegraf in the GOPATH.  I would `git clone` telegraf in the path you want it, making sure you have just a single copy of it.  From there both `go get` and `gdm` should use the first path in your GOPATH.

**Comment by adityacs** [comment]
@deepujain Please check the answer here [https://stackoverflow.com/questions/41571946/internal-packages-in-go](url)

I am not sure if this is causing problem.

**Comment by danielnelson** [comment]
@deepujain Let me know if you need more help compiling.

**Comment by deepujain** [comment]
@danielnelson Above comment shows that i have only one version  one version of Telegraf (git cloned one)

>echo $GOPATH
/SOMEPATH/godeps:/SOMEPATH/influx/telegraf

, I did a simple git clone into PATH1 and started a build. Build process went ahead and downloaded a second version into PATH1/src/github.com

@adityacs I did read this before posting. https://stackoverflow.com/questions/41571946/internal-packages-in-go   The build error is in telegraf code itself

>./cmd/telegraf/telegraf.go
cmd/telegraf/telegraf.go:16:2: use of internal package not allowed
make[1]: *** [telegraf] Error 1

**Comment by deepujain** [comment]
I am on a MAC (OS-X) machine

**Comment by danielnelson** [comment]
> , I did a simple git clone into PATH1 and started a build. Build process went ahead and downloaded a second version into PATH1/src/github.com

When you do the first `git clone` it must be into `$PATH1/src/github.com/influxdata/telegraf`, this is required by Go.

**Comment by olegmayko** [comment]
What is the solution for that, i missed how the issue got resolved , could you please clarify?

**Comment by danielnelson** [comment]
@olegmayko Which error are you getting?  I would not have a second GOPATH that is located within your first path.

**Comment by olegmayko** [comment]
@danielnelson , thanks for answering ,
i am getting cmd/telegraf/telegraf.go:16:2: use of internal package not allowed, i've removed the 2nd GOPATH, so it looks like: 
GOPATH="/var/go/go"
so the location path to telegraf is 
/var/go/go/src/github.com/influxdata/telegraf
to the custom build - 
/var/go/go/src/telegate 
how can i fix that?

**Comment by danielnelson** [comment]
What is `/var/go/go/src/telegate`?

**Comment by olegmayko** [comment]
@danielnelson it's telegraf's fork. but so far i understood, it works i had to copy the modified sources into $GOPATH/src/github.com/influxdata/telegraf and then it goes. I am not new to Go, and i had to maintain it from now. i had to learn more about go packaging management and so on.  but thanks for your help.

**Comment by ckh0618** [comment]
The import path ( "github.com/influxdata/internal/config" ) should be changed if you forked this repository to yours.
