### ISSUE TITLE
After running for some time, telegraf finds that outputs.file has data, but outputs.prometheus_client does not have data 

### ISSUE THREAD

**Issue by zoujd-github** [influxdata/telegraf#3180]
After running for some time, telegraf finds that outputs.file has data, but outputs.prometheus_client does not have data 

# Configuration for telegraf agent
[agent]
  interval = "60s"
  round_interval = false
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "60s"
  debug = true
  quiet = false
  logfile = "/app/workdir/bin/telegraf.log"
  hostname = ""
  omit_hostname = false

[[outputs.prometheus_client]]
   listen = ":9126"

[[outputs.file]]
   files = ["telegraf.output"]

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/issues/3181#issue-253272556

**Comment by danielnelson** [comment]
@zoujd-github I'm not familiar with this input plugin, is it something you wrote?

**Comment by zoujd-github** [comment]
Yes, this input is written by me. Do you know why that's the case?

**Comment by danielnelson** [comment]
No, I haven't seen this issue before.  How long does it take to reproduce?  Can you reproduce it when only the cpu input plugin is enabled?

**Comment by zoujd-github** [comment]
for "# Telegraf error logs accumulated for a long time, the telegraf program will automatically withdraw #3181" question
    When telegraf connects to an exception remote service, the telegraf will frequently report errors. Is there a limit to the number of times this error is reported? Will and telegraf automatically quit?
For example: the teltegraf configuration monitors the plug-in for redis, but the redis server does not exist. Will the telegraf service quit after a long run?

**Comment by danielnelson** [comment]
No, once Telegraf has started it will retry indefinitely.

**Comment by zoujd-github** [comment]
Thank you. I'll keep on tracking. When the trouble happens again, I'll send you the details of the trouble, and then you can help me analyze it.

**Comment by danielnelson** [comment]
Sounds good.
