### ISSUE TITLE
Please add container uptime to docker input

### ISSUE THREAD

**Issue by jindov** [influxdata/telegraf#3184]
As cadvisor with prometheus, I hope docker input will have `container_uptime` metric. I really need to know when a container restart or how long it was started.
Thank dev team,
Jin

**Comment by jamesshannon** [comment]
Any movement on this? I'd really like to see this done as a way to catch errors that cause reboots. 

It's not clear to me which measurement this would go into. There are container-specific metrics for blockio, cpu, mem, and net. Would we need to create a new one for uptime? That seems wasteful (though technically-speaking it probably isn't).

**Comment by glinton** [comment]
@jamesshannon I'm not aware of anyone spending time on this yet. If you'd like to, you're more than welcome to open a pr for it. It looks like adding it as another metric like the blockio, cpu, etc... is the way to go.

**Comment by danielnelson** [comment]
In 1.8.0 we have added a new measurement:
```
- docker_container_status
  - tags:
    - engine_host
    - server_version
    - container_image
    - container_name
    - container_status
    - container_version
  - fields:
    - oomkilled (boolean)
    - pid (integer)
    - exitcode (integer)
    - started_at (integer)
    - finished_at (integer)
```

@jindov @jamesshannon Would this meet your requirements?

**Comment by danielnelson** [comment]
The containers monitored will be subject to the existing options, such as `container_name_include` and `container_state_include`.

To be honest, I was not even aware it was possible to have information about the last time a container died, and I'm not sure even what that means.  I was under the assumption that these would not be filled out until the container had stopped.  Once a container is stopped can it be restarted, I thought restarting it would mean creating a new container.

By the way, the details of this addition are in https://github.com/influxdata/telegraf/pull/4259

**Comment by danielnelson** [comment]
I don't think there would be a way to easily display uptime in Grafana or Chronograf with the start_time/end_time only.  You would probably only be able to do something interesting with custom code or use one of these tools to display the value in a table.

So it seems that we should add a new uptime field to the docker_container_status measurement based on started_at and time.Now().

**Comment by Bursade** [comment]
> I don't think there would be a way to easily display uptime in Grafana or Chronograf with the start_time/end_time only. You would probably only be able to do something interesting with custom code or use one of these tools to display the value in a table.
> 
> So it seems that we should add a new uptime field to the docker_container_status measurement based on started_at and time.Now().

Hi! Sorry to revive this, there's any plan to add this feature?

**Comment by danielnelson** [comment]
We would accept a pull request for this, it should probably be done as `uptime_ns`, since we are normalizing on nanosecond durations.  If the container has already stopped I'm not sure the best behavior, we could either cap the uptime end-start, or just stop reporting uptime.
