### ISSUE TITLE
require hostname to display in lowercase. hostname = "strings.Tolower("")" does not work in telegraf.conf file

### ISSUE THREAD

**Issue by git7020465** [influxdata/telegraf#3185]
### System info:
Telegraf version 1.3.5
OS version : server 2008R2/2012R2

## Feature Request
Some servers have upper case and some lower case as the hostnames, which is making the life difficult to view the hostnames in graphite.  I tried to edit the telegraf.conf file  in the hostname section as
hostname = "strings.Tolower("")" 
It didn't work. Please provide the way to edit the hostname in telegraf.conf file so that all servers irrespective of upper/lower case in their hostnames, display in lowercase in graphite.

**Comment by danielnelson** [comment]
This isn't something I would want to add as the complexity of doing this outweighs the benefits.

Maybe instead you can arrange for an environment variable containing the string you want to be set, then you can have a line like this in your config file:
```
  hostname = "$DISPLAY_HOST"
```

Another option would be to generate the config using a templating language.

More complicated but possible would be using Kapacitor you rewrite the hostnames.
