### ISSUE TITLE
Statsd plugin needs read_buffer_size setting.

### ISSUE THREAD

**Issue by kriptor** [influxdata/telegraf#3189]
It would really be useful if we had a way to set the read buffer size of the statsd input plugin by witch we would have more control over how many metrics per second can be successfully handled without making some obscene system settings of rmem_default. I'm not a GO programmer but it looks pretty straight forward to add this.

**Comment by SimonOlenik** [comment]
We need that ASAP!

**Comment by kriptor** [comment]
Thx @danielnelson
