### ISSUE TITLE
Telegraf data through UDP fail to parse

### ISSUE THREAD

**Issue by hcsaustrup** [influxdata/telegraf#3195]
Sorry - it's probably an InfluxDB issue, so I moved it here: https://github.com/influxdata/influxdb/issues/8785

**Comment by danielnelson** [comment]
This could be caused by #3187, even if not I think it is probably a Telegraf issue.  Can you test with 1.4.0-rc4 to see if it is resolved?

**Comment by hcsaustrup** [comment]
@danielnelson we're monitoring a boat load of servers, and I'm unable to update Telegraf on the last 5% or so, but I do think I see a significant reduction in errors. Looking at the few errors still there, they're either from servers running old versions of Telegraf or not identifiable:

``
Sep  7 14:19:36 Y33392 influxd: [I] 2017-09-07T12:19:36Z Failed to parse points: unable to parse '00000000000000000000000000000000000000000000000000000000000000000000000000000000000002964393875 1504786770000000000': invalid field format service=udp
``

If would be cool if this error also included client IP or hostname.

Anyway, I'm optimistic - looks like RC4 fixed the issue.

**Comment by danielnelson** [comment]
There should also be a corresponding log message on the Telegraf side, if you have a method to search the logs on all systems.
