### ISSUE TITLE
Document port specification in postgresql plugin

### ISSUE THREAD

**Issue by umataro** [influxdata/telegraf#3197]
## Feature Request

I would like to be able to specify a non-standard port for postgresql plugin to use. e.g.:

```
[[inputs.postgresql]]
    address = "host=localhost port=5433 user=postgres sslmode=disable"
```

### Proposal:

Currently, *port number* is appended to the *host* specified in config file. Instead of just slapping `:5432` at the end of my specified host, I'd like to be able to set the port manually.

### Current behavior:

Attempting to specify port number like this:

```
[[inputs.postgresql]]
    address = "host=localhost:5433 user=postgres sslmode=disable"
```

results in an error such as this one:

```
2017-09-04T15:10:20Z E! Error in plugin [inputs.postgresql]: dial tcp: address localhost:5433:5432: too many colons in address
```

### Desired behavior:

If a port is manually specified, do not append any default port to my hostname. 

### Use case:

Postgresql setup with pgpool (which runs on 5432) needs to run postgresql on a different port.

**Comment by danielnelson** [comment]
What error do you get when adding the port to the dsn?
```
[[inputs.postgresql]]
    address = "host=localhost port=5433 user=postgres sslmode=disable"
```

**Comment by umataro** [comment]
There is no error. I must have made a typo on my first try and assumed it wasn't supported (as it is not documented). I guess this ticket should change into "Can port specification be documented?".

**Comment by HarshitOnGitHub** [comment]
Have opened a PR for this: https://github.com/influxdata/telegraf/pull/7132
