### ISSUE TITLE
Using inputs sequentially for performance measurements

### ISSUE THREAD

**Issue by guitarzero** [influxdata/telegraf#3201]
Hi
Thank you for Telegraf : it is a great piece of work !

We would like to use native inputs (in particular http_response) of Telegraf in a sequential way to measure performances. Right now, as far as i know, all inputs measurements are made *almost* simultaneously (*almost thanks to jitter conf) making performance measurements arguable.

Is it possible to configure a parameter of Telegraf in order to define the number of workers that handle inputs ? In our case, this parameter would be set to 1 but making it possible to configure multiple workers could be interesting, for example to control load on the host running Telegraf.

Does that make sense ?

Thanks in advance

Gui

**Comment by danielnelson** [comment]
Makes sense, but one issue with this there will be cascading failures if all plugins do not complete within the interval.  I think it is probably not something we will likely want to include as an option due to difficulty troubleshooting and confusion around it.  Maybe a better approach would be looking at what is causing so much load within Telegraf, in order to make your benchmarks a little more reliable.

If you want to make this change in your own fork I can show you about where to make the change.

**Comment by guitarzero** [comment]
Hello Daniel
Thank you for your answer. 
I would be interested in having a closer look where it could be possible to deal with my requirement. I will watch at cascading failures (i need to think about it a bit more to better understand the consequences).

So yes, i would like to work on my own fork and your help will be greatly appreciated if you could show me where to start (my requirement is to make sequential calls of my plugins)

Thnaks again
Stephane

**Comment by danielnelson** [comment]
There is a goroutine running the [gatherer](https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L100) function for every input plugin.  I think the easiest way to serialize these is using the [semaphore pattern](http://www.golangpatterns.info/concurrency/semaphores) and adding it to the [Agent](https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L19) struct.  Then, I think it would be best to guard only [this anonymous goroutine](https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L153).

This is all untested but I think it should work.

**Comment by danielnelson** [comment]
I'm going to close this issue, but feel free to comment here if you need any more help.
