### ISSUE TITLE
Allow to customize timeouts on Kubernetes plugin

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#3203]
I'm using the kubernetes plugin to obtain metrics from OpenShift applications nodes.
The response time varies from 1.5s to 4s, so when it crosses the 3s barrier telegraf discard it because of timeout.

Could be possible to add some parameters to increase the timeout values?

@jchauncey ?

**Comment by danielnelson** [comment]
Yeah, I'll get it.

**Comment by jchauncey** [comment]
Ive got the work done for this. Just have to go through the channels at microsoft to submit the pr. Should have it up first this tomorrow.

**Comment by jchauncey** [comment]
So might just be easier for someone else do this or I can throw up the code somewhere that Ive got and someone else can submit it

**Comment by jchauncey** [comment]
Here is a gist with the changes - https://gist.github.com/jchauncey/325956b3d03db33fd1a3241ecf6b9e78
