### ISSUE TITLE
input plugin 'net' generates two events 

### ISSUE THREAD

**Issue by mrchang7** [influxdata/telegraf#3204]
Hi guys,

I'm using Telegraf v1.3.3 on RH7.2. As I inlcude "[[inputs.net]]" in the conf, it generates two events with the same timestamp (see below). The metrics are sent to logstash.  

Specifically, I'd like to generate only one or the one having the fields, 'bytes_recv, byetes_sent'. I don't know how to pick the event I need. 

Any help will be appreciated. Thanks!

{
  "_index": "vm-2017.09.06-18:49",
  "_type": "logs",
  "_id": "AV5YhtKG_A0TfCbJuiuH",
  "_version": 1,
  "_score": null,
  "_source": {
    "hostname": "node1",
    "@timestamp": "2017-09-06T18:49:44.000Z",
    "name": "net",
    "port": 35054,
    "hostip": "10.0.0.9",
    "@version": "1",
    "net": {
      "drop_out": 0,
      "packets_recv": 328785939,
      "packets_sent": 417937884,
      "err_out": 0,
      "bytes_recv": 192222682734,
      "err_in": 0,
      "bytes_sent": 356898597846,
      "drop_in": 0
    }
  },
  "fields": {
    "@timestamp": [
      1504723784000
    ]
  },
  "highlight": {
    "hostname": [
      "@kibana-highlighted-field@aspike1@/kibana-highlighted-field@"
    ],
    "plugin": [
      "@kibana-highlighted-field@net@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1504723784000
  ]
}

AND…

{
  "_index": "vm-2017.09.06-18:49",
  "_type": "logs",
  "_id": "AV5YhtKG_A0TfCbJuiuI",
  "_version": 1,
  "_score": null,
  "_source": {
    "hostname": "node1",
    "@timestamp": "2017-09-06T18:49:44.000Z",
    "name": "net",
    "port": 35054,
    "hostip": "10.0.0.9",
    "@version": "1",
    "net": {
      "icmp_outtimestamps": 0,
      "udp_incsumerrors": 0,
      "udplite_inerrors": 0,
      "icmp_inredirects": 0,
      "ip_inreceives": 1168924684,
      "icmp_outsrcquenchs": 0,
      "ip_reasmtimeout": 0,
      "udp_rcvbuferrors": 0,
      "icmp_intimestampreps": 0,
      "icmp_inechos": 33,
      "icmp_outredirects": 0,
      "udp_noports": 197752,
      "tcp_passiveopens": 24906336,
      "icmp_indestunreachs": 4478983,
      "ip_forwarding": 2,
      "icmp_outparmprobs": 0,
      "tcp_insegs": 1073173177,
      "icmp_outtimeexcds": 0,
      "tcp_rtomax": 120000,
      "udp_inerrors": 0,
      "icmp_outechoreps": 18,
      "ip_fragoks": 0,
      "udplite_outdatagrams": 0,
      "udplite_noports": 0,
      "icmp_inparmprobs": 0,
      "icmp_incsumerrors": 0,
      "tcp_attemptfails": 3162951,
      "tcp_retranssegs": 59222,
      "ip_inaddrerrors": 0,
      "tcp_rtomin": 200,
      "tcp_outsegs": 1059340051,
      "ip_reasmoks": 0,
      "icmp_inmsgs": 4479030,
      "icmp_outechos": 14,
      "icmpmsg_outtype8": 14,
      "tcp_currestab": 23,
      "udp_indatagrams": 84663930,
      "udplite_incsumerrors": 0,
      "icmp_outdestunreachs": 206669,
      "icmpmsg_outtype0": 18,
      "udplite_indatagrams": 0,
      "ip_fragfails": 0,
      "icmpmsg_outtype3": 206669,
      "ip_fragcreates": 0,
      "ip_indiscards": 0,
      "tcp_incsumerrors": 0,
      "icmp_inechoreps": 14,
      "icmp_intimeexcds": 0,
      "ip_reasmfails": 0,
      "icmp_insrcquenchs": 0,
      "ip_indelivers": 1161924429,
      "udplite_rcvbuferrors": 0,
      "icmp_inaddrmaskreps": 0,
      "tcp_rtoalgorithm": 1,
      "ip_reasmreqds": 0,
      "tcp_activeopens": 46065840,
      "tcp_estabresets": 408222,
      "udp_outdatagrams": 166197045,
      "icmp_intimestamps": 0,
      "ip_outnoroutes": 64,
      "icmpmsg_intype3": 4478983,
      "icmp_outerrors": 0,
      "icmpmsg_intype8": 33,
      "udp_sndbuferrors": 0,
      "icmp_inerrors": 6490,
      "icmp_outaddrmaskreps": 0,
      "tcp_outrsts": 4913945,
      "ip_defaultttl": 64,
      "icmpmsg_intype0": 14,
      "tcp_maxconn": -1,
      "tcp_inerrs": 5,
      "icmp_inaddrmasks": 0,
      "icmp_outaddrmasks": 0,
      "ip_forwdatagrams": 0,
      "udplite_sndbuferrors": 0,
      "ip_inhdrerrors": 0,
      "ip_inunknownprotos": 0,
      "icmp_outtimestampreps": 0,
      "ip_outrequests": 1213919581,
      "icmp_outmsgs": 206701,
      "ip_outdiscards": 4259098
    }
  },
  "fields": {
    "@timestamp": [
      1504723784000
    ]
  },
  "highlight": {
    "hostname": [
      "@kibana-highlighted-field@aspike1@/kibana-highlighted-field@"
    ],
    "plugin": [
      "@kibana-highlighted-field@net@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1504723784000
  ]
}

**Comment by danielnelson** [comment]
Can you run `telegraf --input-filter net --test` and paste the output?

**Comment by mrchang7** [comment]
* Plugin: inputs.net, Collection 1
> net,interface=eth0,host=db-1.pcrf.local packets_recv=84216041i,bytes_sent=65119669962i,bytes_recv=6811066419i,packets_sent=167045990i,err_in=0i,err_out=0i,drop_in=0i,drop_out=0i 1504736734000000000
> net,interface=eth1,host=db-1.pcrf.local bytes_sent=17258605641i,err_in=0i,err_out=0i,drop_out=0i,bytes_recv=17416411750i,packets_sent=171818714i,packets_recv=177835899i,drop_in=0i 1504736734000000000
> net,interface=all,host=db-1.pcrf.local ip_indelivers=415147945i,udplite_inerrors=0i,icmp_outtimeexcds=0i,icmp_outparmprobs=0i,tcp_currestab=45i,ip_forwdatagrams=0i,icmp_outaddrmaskreps=0i,tcp_maxconn=-1i,icmp_outsrcquenchs=0i,icmp_outtimestampreps=0i,icmpmsg_intype0=30i,udplite_sndbuferrors=0i,ip_inaddrerrors=0i,ip_defaultttl=64i,icmp_outredirects=0i,icmp_intimeexcds=49i,udplite_outdatagrams=0i,udplite_rcvbuferrors=0i,udplite_indatagrams=0i,ip_forwarding=2i,icmp_outechoreps=1i,ip_reasmfails=0i,ip_outrequests=484080706i,icmp_outtimestamps=0i,icmpmsg_intype3=996123i,tcp_passiveopens=16794087i,ip_outdiscards=18499i,ip_inhdrerrors=0i,icmp_intimestamps=0i,ip_reasmreqds=0i,icmp_outerrors=0i,icmp_insrcquenchs=0i,icmp_inechoreps=30i,icmp_incsumerrors=0i,udp_incsumerrors=0i,udp_indatagrams=23097755i,ip_fragoks=0i,ip_fragfails=0i,icmp_outdestunreachs=973532i,icmpmsg_intype8=1i,tcp_attemptfails=1375i,tcp_inerrs=232i,udp_sndbuferrors=0i,udplite_noports=0i,icmp_outechos=30i,icmp_indestunreachs=996123i,icmp_inmsgs=996203i,icmp_inredirects=0i,tcp_activeopens=16874708i,tcp_retranssegs=56125i,udp_rcvbuferrors=0i,ip_outnoroutes=0i,icmp_inaddrmaskreps=0i,icmpmsg_outtype0=1i,icmpmsg_outtype3=973532i,tcp_estabresets=1598i,tcp_rtomin=200i,udplite_incsumerrors=0i,tcp_rtomax=120000i,ip_fragcreates=0i,ip_indiscards=0i,ip_inunknownprotos=0i,icmp_inaddrmasks=0i,icmp_outaddrmasks=0i,icmpmsg_outtype8=30i,tcp_outrsts=58672i,tcp_insegs=421611244i,tcp_incsumerrors=0i,udp_noports=132i,ip_reasmtimeout=0i,icmp_inerrors=3899i,icmp_inechos=1i,icmp_outmsgs=973563i,icmp_intimestampreps=0i,icmp_inparmprobs=0i,tcp_outsegs=418491319i,ip_inreceives=415148093i,ip_reasmoks=0i,icmpmsg_intype11=49i,tcp_rtoalgorithm=1i,udp_outdatagrams=97580992i,udp_inerrors=0i 1504736734000000000

**Comment by danielnelson** [comment]
Yes, but you can filter out the interfaces you are not interested in and you can also remove fields you don't want using the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options.

**Comment by mrchang7** [comment]
Super. That will be very useful. Many thanks!
