### ISSUE TITLE
Telegraf: inputs.mqtt_consumer "name_override" overrides Line Protocol measurement name

### ISSUE THREAD

**Issue by DavidAntliff** [influxdata/telegraf#3205]
### Relevant telegraf.conf:

```
[[inputs.mqtt_consumer]]
  name_override = "foo"
  servers = ["mosquitto:1883"]
  qos = 0
  topics = [
    "test",
  ]
  data_format = "influx"
```

### System info:

* Raspbian Jessie (Raspberry Pi)
* Docker 17.05.0-ce
* Mosquitto 1.4.14
* Telegraf 1.3.5
* InfluxDB 1.3.3

Note: I expect this issue to appear on a non-Raspberry Pi system however I don't have one I can use at the moment. I do not have any reason to think it is Raspberry Pi specific - it's just the system that I have right now.

### Steps to reproduce:

1. Configure Mosquitto to provide MQTT broker services (no security).
2. Configure Telegraf with default configuration.
3. Add `inputs.mqtt_consumer` section as above, and set "servers" to the name of the Mosquitto service.
4. Start all the services.
5. Using an MQTT client (such as mqtt-spy) send the following string to the "test" topic:

    weather,location=us-midwest temperature=82 

### Expected behavior:

Given the measurement name "weather" in the Line Protocol I'd expect a new measurement called "weather" to be created in the telegraf.autogen database, with the tag location, tag value "us-midwest", and a field called "temperature" with the value 82.

If the "weather" measurement already exists, I'd expect the data point to be added to it.
 
### Actual behavior:

A measurement named "weather" is **not** created, or added to if it already exists.

Instead, specified tags and fields are added to the measurement named "foo" which is the name specified by the "name_override" directive. If it does not exist, it is created.

While I would expect the name_override to change the default name of the measurement when none is provided elsewhere, for example when using `data_format="value"`, I wouldn't expect it to override the measurement name for every Line Protocol message.

Line Protocol _requires_ that the measurement name be specified, so there's no need for a default measurement name in this case. If the intention is to direct all incoming LP data to a _single_ measurement regardless of the source's intention, perhaps there's a case for a new influx-format-only parameter called "redirect_measurement", "override_measurement", "merge" or some such?

The specific use case I have is that I have defined multiple `[[inputs.mqtt_consumer]]` instances, and have specified different names for each (using the same name for all of them seems unwise). However the side-effect of this is that it overrides the measurement name, meaning that I can't combine `name_override` with `data_format="influx"` and this limits my use of multiple instances.

### Additional info:

A docker-compose.yml to help reproduce this issue (Raspberry Pi only):

https://github.com/DavidAntliff/poolmon/tree/master/services

**Comment by danielnelson** [comment]
This is working as designed, the `name_override` parameter is most often used with input plugins that generate metrics and allows the measurement name to be changed.  I don't see it used very often with the queuing system consumers.  You should be able to just remove the option and I think everything will work as desired.

**Comment by DavidAntliff** [comment]
Ok, so there's no harm in having multiple MQTT input plugins (subscribed to different topics) all with the same default name of "mqtt_consumer"? I'll close this for now and confirm for myself. Thanks.
