### ISSUE TITLE
IPMI sensor status

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#3207]
At current, the IPMI plugin assumes that if the sensor is "ok", then the status field will be set to 1, else 0.

However, there are multiple sensor status available and it is very inconvenient not to be able to access the original value.

The list of available sensor status values are:

* ok - OK
* nr - Non Recoverable
* cr - Critical
* nc - Non Critical
* ns - Not Specified
* na - Not Available

Additionally, when the status happens to be either 'na' or 'ns', no reading is available then. As a result, the unit and value fields cannot be set.

I would then like to make the following changes to the plugin:

* set the status field to the original status value rather than converting it to a number
* if the status is either 'ns' or 'na', skip trying to figure out the value and unit fields since there's no reading available.

If the changes are okay, I will make a PR for this.

**Comment by danielnelson** [comment]
How about instead of changing the type of the status field we add a new field for the string codes, otherwise everyone will have to flush their databases.  Unfortunately the name won't be as nice, but perhaps `sensor_status` or `status_name`?

**Comment by m4ce** [comment]
@danielnelson - that makes sense. I will name it `status_name`.

**Comment by jhg03a** [comment]
If you refer to my comment on #3416, you can get the full description of the coded values.  This gives you even more information in the case of things like where it normally would have the code `ok` when you could be getting something like `Drive Present`.

**Comment by jhg03a** [comment]
You could also just like the above `sensor_status` & `sensor_name` fields, add `sensor_desc`.

**Comment by jhg03a** [comment]
Trying to convert arbitrary code values to something more human readable seems perilous to me because you will have to include some kind of catchall unknown name that will have to be maintained here apart from whatever version of ipmitool you're using.

**Comment by jhg03a** [comment]
Converting codes to integers has meaning.  In the current implementation it means potentially not fine.  It's similar to how you might write a Nagios check.

**Comment by sspaink** [comment]
If understand correctly, it seems https://github.com/influxdata/telegraf/pull/4450 addresses this problem by providing more information? Closing, but please re-open if I misunderstood.
