### ISSUE TITLE
Fluentd plugin sends float pointers instead of real values

### ISSUE THREAD

**Issue by pfriel-bcs** [influxdata/telegraf#3217]
## Bug report
When using the new fluentd plugin to send queue metrics to Influx the buffer_total_queued_size, buffer_queue_length and retry_count are sending the float pointer memory address like "0xc420045418" instead of the real underlying values like "12345".

### Relevant telegraf.conf:
```
[[inputs.fluentd]]
#   ## This plugin reads information exposed by fluentd (using /api/plugins.json endpoint).
#   ##
#   ## Endpoint:
#   ## - only one URI is allowed
#   ## - https is not supported
  endpoint = "http://localhost:24220/api/plugins.json"
#
#   ## Define which plugins have to be excluded (based on "type" field - e.g. monitor_agent)
#   exclude = [
#         "monitor_agent",
#         "dummy",
#   ]
  exclude = [
    "monitor_agent"
  ]
```

### System info:

Telegraf 1.4.0
OS: Ubuntu 16.04.2

### Steps to reproduce:

1. Enable the fluentd plugin
2. Start telegraf

### Expected behavior:
stdout results:
```
fluentd,plugin_type=secure_forward,plugin_id=object:15c28ac,plugin_category=output,retry_count=1,buffer_total_queued_size=9652,buffer_queue_length=0 1505163950000000000
```

### Actual behavior:
stdout results:
```
fluentd,plugin_type=secure_forward,plugin_id=object:15c28ac,plugin_category=output,buffer_queue_length="0xc4202a81a8",retry_count="0xc4202a81c8",buffer_total_queued_size="0xc4202a81b8" 1505165500000000000
```

### Additional info:

This code appears to fix the issue: https://github.com/BattleCry-Studios/telegraf/commit/debd4093758378a1032fa1b9613a7d9b9776cdab

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/commit/8a68e7424c48e8f28034855a239265ab52ba536d
