### ISSUE TITLE
monitor other server in telegraf

### ISSUE THREAD

**Issue by iebra** [influxdata/telegraf#3220]
i have a Telegraf in system 'A' and i have other system 'B' with PostgreSQL , so i monitor the PostgreSQL but i want monitor system 'B' also, how can i do it ?

**Comment by danielnelson** [comment]
It completely depends on the input plugins you are using, some input plugins can operate over the network but others require Telegraf to be running locally.   Many of us are running a Telegraf instance on most of our servers for this reason, if you do this you can collect all information locally on host 'B', both postgres and system, and then send the data out to InfluxDB.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
