### ISSUE TITLE
Support arbitrary tokens for Prometheus input

### ISSUE THREAD

**Issue by jonnyzzz** [influxdata/telegraf#3222]
## Bug report
Our application has a token file on the disk. It writes the value of `Authorization` header into the file. We cannot make the reporter work

### Relevant telegraf.conf:
```
[[inputs.prometheus]]
urls = [ <HOSTS> ]
bearer_token='/etc/telegraf/token'
response_timeout = "30s"
```
It could be nice to allow any Authorization header value being read from the file. In my case, we indeed have the file with just `Authorization` header value. So what I pass the file into `bearer_token` I have `Bearer " + <file content>` instead of just `<file content>` as the `Authorization` header value. 

It looks like the `bearer_token` feature can easily be expanded to support arbitrary header values, to include my case, and also Basic authorization as well. 

I've seen yet another approach to configure HTTP client in the `httpjson` import plugin. There it was allowed to specify any headers. But, it was not allowed to have those headers re-loaded from a file prior to every request.

**Comment by danielnelson** [comment]
The `bearer_token` in a file is a good idea, but I think it to specialized for inclusion, unless there is an established pattern that I'm unaware of.

We could definitely add a headers option like in `httpjson` though.

**Comment by jonnyzzz** [comment]
Thanks. In my case, I was looking for the way to pass `Authorization` header value entirely from a file (and reread it on every request)

**Comment by danielnelson** [comment]
I don't think we want to do this, but maybe you could use a proxy or some other method to add the authorization in.
