### ISSUE TITLE
Malformed measurements from telegraf to influxdb

### ISSUE THREAD

**Issue by viktorsmari** [influxdata/telegraf#3237]
I have telegraf running on multiple hosts which report to a influxdb (via https) running on Docker behind nginx proxy.

## Bug report
Measurements get a random gibberish text in front of their names.

Could this be related to telegraf on some of our host  trying to post to much data?

We are using the [[inputs.httpjson]] plugin on one host.

Can someone help me debug this further?

![2017-09-15_353x241](https://user-images.githubusercontent.com/1689020/30477639-26ba2144-9a0e-11e7-856e-a02910d512ba.png)

This affects Grafana for example:
![2017-09-15_464x355](https://user-images.githubusercontent.com/1689020/30477640-26bbb68a-9a0e-11e7-8f99-feb0abed98ba.png)

### System info:

Multiple telegraf versions.
Influxdb docker image, version 1.3.5 - influxb shell 0.10.0

### Expected behavior:
Don't prefix measurement names with some gibberish text

### Additional info:

telegraf.log example errors:

> 2017-09-15T09:59:30Z E! InfluxDB Output Error: Response Error: Status Code [400], expected [204], [partial write: unable to parse '_readings_good_this_week=84494,devices_readings_bad_today=58,devices_readings_bad_this_week=17409,devices_online_now=113,response_time=0.090892229,devices_total=2023,devices_online_all_time=1257,devices_online_this_month=131 1505469570000000000': invalid field format dropped=0]
2017-09-15T09:59:30Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2017-09-15T10:00:10Z E! InfluxDB Output Error: Response Error: Status Code [400], expected [204], [partial write: unable to parse 'vices_readings_bad_this_week=17409,users_total=5520,devices_readings_bad_today=58,devices_online_this_year=308 1505469610000000000': invalid field format dropped=0]

**Comment by bobmshannon** [comment]
Hey @viktorsmari,

I think this has been encountered before in #2854.

Since you have an reproduction, can you share your nginx config and also try adding the following to your location block and see if it helps?

```
chunked_transfer_encoding off;
gzip off;
proxy_set_header Content-Type "text/plain";
proxy_http_version 1.1;
```

**Comment by danielnelson** [comment]
I agree this is probably the same issue, we can discuss further over on #2854.

@viktorsmari If you could also try my suggestion in https://github.com/influxdata/telegraf/issues/2854#issuecomment-329876846 could you add a comment over on that issue to let people know you will test it.

**Comment by viktorsmari** [comment]
Confirming that adding the section above to nginx location fixes the issue!

Thank you!
