### ISSUE TITLE
Binary release for arm64 doesn't work when arm32 binary support isn't available

### ISSUE THREAD

**Issue by jqueuniet** [influxdata/telegraf#3242]
### System info:

telegraf v1.4.0
Tested on an ARM64-2GB virtual machine rented at Scaleway. Architecture is aarch64 and AFAIK their hardware is a Cavium ThunderX SoC running a KVM hypervisor.
Operating system is Debian 9.0

### Steps to reproduce:

1. Start a Scaleway ARM64 virtual machine running Debian 9
2. Install the telegraf arm64 debian package
3. Run telegraf

### Expected behavior:

telegraf runs

### Actual behavior:

The binary doesn't run, returns the following error.

```-bash: /usr/bin/telegraf: cannot execute binary file: Exec format error```

### Additional info:

```/usr/bin/telegraf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped```

The kernel is a Scaleway one and I don't get a choice on the matter as the bootloader is out of my hands, but apparently Cavium ThunderX doesn't provide support for 32-bit anyway.

Installing from source with Go 1.9 binary distribution produces a working binary, with the following spec.

```/root/go/bin/telegraf: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=95e2ee8cd6e51ce5aa7313e0057cd105c881720d, stripped```

**Comment by danielnelson** [comment]
The fix should be in 1.4.1, here is a link to the [deb package](https://8268-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.xEgxzbI/build/linux/arm64/telegraf_1.4.0%257E52cd381-0_arm64.deb) from CI if you would like to test it.

**Comment by jqueuniet** [comment]
It works perfectly, thank you.
