### ISSUE TITLE
Proxy agent to monitor remote systems 

### ISSUE THREAD

**Issue by n1sivakumar** [influxdata/telegraf#3249]
## Feature Request

Request for a proxy plugin for the win_perf_counters (Windows) where one agent in one server can monitor other servers within the same network (using WinRMI and authentication details in configuration). Another proxy for Linux 'system' plugin also, but using SSH.

### Proposal:
When the data is collected, it should have metrics along with the server name it corresponds too.

### Current behavior:
Telegraf agent is expected to be installed on ALL the machines that needs to be monitored for system performance.

### Desired behavior:

Install agent in one machine (Windows/Linux) and use it as proxy agent to monitor system metrics for remote systems (in same network).

### Use case: [Why is this important (helps with prioritizing requests)]
Telegraf agent is expected to be installed on ALL the machines that needs to be monitored for system performance. This may not be acceptable in some strict corporate environments. It can be made as a VM/appliance that can be deployed in one network and configured to monitor ALL machines/DBs/... from one place.

**Comment by danielnelson** [comment]
We have an issue open for WMI support https://github.com/influxdata/telegraf/issues/1857
