### ISSUE TITLE
Add plugin to telegraf.conf

### ISSUE THREAD

**Issue by Manikandan25** [influxdata/telegraf#3250]
I  would like to add plugin to my telegraf.conf. So, I run telegraf -usage apache in my terminal. Then I got the following:
#Read Apache status information (mod_status)
[[inputs.apache]]
  ##An array of URLs to gather from, must be directed at the machine
  ##readable version of the mod_status page including the auto query string.
  ##Default is "http://localhost/server-status?auto".
  urls = ["http://localhost/server-status?auto"]

  ##Credentials for basic HTTP authentication.
  #username = "myuser"
  #password = "mypassword"

  ##Maximum time to receive response.
  #response_timeout = "5s"

  ##Optional SSL Config
  #ssl_ca = "/etc/telegraf/ca.pem"
  #ssl_cert = "/etc/telegraf/cert.pem"
  #ssl_key = "/etc/telegraf/key.pem"
  ##Use SSL but skip chain & host verification
  #insecure_skip_verify = false

So, I opened telegraf.conf and modified as above. I've connected this telegraf with infuxdb. This apache measurements doesn't reflected in influx-->databas-->show measurements. Can anyone help me to resolve this?

**Comment by danielnelson** [comment]
Is there anything interesting in the logfile?  Make sure when you restart Telegraf the plugin is listed:
```
2017-09-19T17:52:40Z I! Loaded inputs: inputs.apache
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by Manikandan25** [comment]
Thanks for the reply Daniel. I found similar question in influx community
and now I can apache inputs loaded.. Thanks a lot

**Comment by umitdemirbaga1** [comment]
Hi @Manikandan25, 
I am trying to collect Hadoop metrics via Telegraf. I cannot find enough documentation about that. Could you please inform me about this?
