### ISSUE TITLE
Too many useless metrics

### ISSUE THREAD

**Issue by julienmary** [influxdata/telegraf#3251]
### Proposal:
Add granularity to the configuration enabling to select only the wished metrics in place of all the metrics in a given group.
### Current behavior:
We can select only whole groups, making wished measurements coming with a lot of noise.
### Desired behavior:
ability to select metrics precisely.
Example --
```
master_collections = [
    "resources/disk/total"
    ....
]
```
Would disable the whole group resources to provide only  the mentionned metric.
```
master_collections = [
    "resources/diskl"
    ....
]
```
Would display everything about disks

**Comment by danielnelson** [comment]
You can use the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options on inputs or outputs to whitelist.

**Comment by julienmary** [comment]
ok tks :-)
