### ISSUE TITLE
Add more metrics to RabbitMQ (mnesia, exchange, node_up)

### ISSUE THREAD

**Issue by jcmartins** [influxdata/telegraf#3252]
## Feature Request
See metrics below:

rabbitmq_node_up

rabbitmq_mnesia_table_read_only
rabbitmq_mnesia_table_disc_copies
rabbitmq_mnesia_table_disc_only_copies
rabbitmq_mnesia_table_local_content
rabbitmq_mnesia_table_majority_required
rabbitmq_mnesia_table_master_nodes
rabbitmq_mnesia_table_memory_bytes
rabbitmq_mnesia_table_ram_copies
rabbitmq_mnesia_table_records_count
rabbitmq_mnesia_table_disk_size_bytes

rabbitmq_exchange_messages_published_total
rabbitmq_exchange_messages_published_in_total
rabbitmq_exchange_messages_published_out_total
rabbitmq_exchange_messages_confirmed_total
rabbitmq_exchange_messages_delivered_total
rabbitmq_exchange_messages_delivered_no_ack_total
rabbitmq_exchange_messages_get_total
rabbitmq_exchange_messages_get_no_ack_total
rabbitmq_exchange_messages_deliver_get_total
rabbitmq_exchange_messages_redelivered_total
rabbitmq_exchange_messages_returned_total

**Comment by danielnelson** [comment]
Related to #874

**Comment by sjwang90** [comment]
@jcmartins is this feature request still relevant?
