### ISSUE TITLE
Error in plugin [inputs.cloudwatch]: RequestError: send request failed

### ISSUE THREAD

**Issue by druchoo** [influxdata/telegraf#3255]
## Bug report
CloudWatch input seems to leave many TIME_WAIT connections which eventually causes it to return too many open files error.

### Relevant telegraf.conf:
60 or so different cloudwatch configs (we use Puppet so the files are separated) for various namespaces (AWS/AutoScaling, AWS/ECS, AWS/RDS)
```
[[inputs.cloudwatch]]
  delay = "1m"
  interval = "1m"
  namespace = "AWS/RDS"
  period = "1m"
  profile = "my_profile"
  ratelimit = 25
  region = "us-east-1"
```

### System info:
telegraf-1.3.5-1.x86_64
CentOS Linux release 7.2.1511 (Core)

### Steps to reproduce:
Create telegraf config with many CloudWatch inputs. I have 60 configured.

### Expected behavior: 
TCP connections should be handled in a matter where TIME_WAITs don't linger (reused or closed faster perhaps).

### Actual behavior: 
TCP connections seem to be left open which causes TIME_WAITs and uses up open files. Telegraf log shows many lines like:

```
Sep 20 19:27:08 my_host telegraf[23200]: 2017-09-20T19:27:08Z E! Error in plugin [inputs.cloudwatch]: RequestError: send request failed
Sep 20 19:27:08 my_host telegraf[23200]: caused by: Post https://monitoring.us-east-1.amazonaws.com/: dial tcp xx.xx.xx.xx:443: socket: too many open files
```

### Additional info:
Past week of TCP connections. The drop is me experimenting with different kernel parameters.
![screenshot at sep 20 15-54-57](https://user-images.githubusercontent.com/2237523/30664957-7132fa76-9e1d-11e7-98c9-886d91a301fe.png)

I've tried tweaking network stack but didn't seem to help.

```
$ sysctl net.ipv4.tcp_fin_timeout net.ipv4.tcp_tw_recycle net.ipv4.tcp_tw_reuse fs.file-max
net.ipv4.tcp_fin_timeout = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 0
fs.file-max = 500000
```
These settings don't seem to be honored. Since this is systemd system adding `LimitNOFILE=65536` to the telegraf.service unit file works to increase open files. However, this requires a manual change to a file that in the telegraf package and doesn't really fix the TIME_WAIT issue. On a side, I see that `LimitNOFILE=65536` is in the influxdb.service unit file. Maybe it makes sense to add for telegraf too?

**Comment by danielnelson** [comment]
We should try initializing the cloudwatch.New with a custom transport and see if it helps out.  I think we will need to limit the concurrent requests with more than just a rate limit as well in order to set the proper max idle connections.

**Comment by druchoo** [comment]
Hi @danielnelson, Has there been any progress on this issue?

**Comment by danielnelson** [comment]
Sorry, no I haven't worked on this in some time.  Can you verify this is still an issue in 1.9.4, I assume it is but it would be good to double check.  I can try to take a second look for 1.11, though I'm not sure this is something we can fix.

**Comment by druchoo** [comment]
Yes, I'm seeing the same behavior with `1.9.4` unfortunately.
