### ISSUE TITLE
System input and Atoi problem for kernel_vmstat

### ISSUE THREAD

**Issue by joakimberglund** [influxdata/telegraf#3259]
1.4.0

 tail -1 telegraf.log
2017-09-22T13:16:50Z E! Error in plugin [inputs.kernel_vmstat]: strconv.Atoi: parsing "6690743595": value out of range
 cat /proc/vmstat | grep 66907
numa_hit 6690746819
numa_local 6690746819

**Comment by danielnelson** [comment]
What platform and arch is this on?

**Comment by joakimberglund** [comment]
CentOS 6.7 64bit

**Comment by danielnelson** [comment]
Interesting, I was pretty sure you were going to say 32-bit.  What is the output of the file command?
```
file /usr/bin/telegraf 
```

**Comment by joakimberglund** [comment]
wtf...

Okie, my bad!

file /usr/bin/telegraf
/usr/bin/telegraf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped

Looks like I installed the wrong version when I tried 1.4.0 on my test machine.
Real sorry for that.

**Comment by danielnelson** [comment]
No problem, this is a bug for the 32-bit builds so I appreciate the report.  I will include the fix in 1.4.2 and in the meantime you can grab the 64-bit version.
