### ISSUE TITLE
Add support for paths in output.influxdb

### ISSUE THREAD

**Issue by crenz** [influxdata/telegraf#3260]
### Proposal:

I propose to add support for InfluxDB URLs that contain paths. As of today, the configuration is an URL, which kind of suggests that paths are supported – when in reality they are not. Here is an example:

```
[[outputs.influxdb]]
  urls = ["http://influxdb.example.com/api"]
```

### Current behavior:

For the example above, telegraf will only extract the host name and port, and issue a request to e.g. `http://influxdb.example.com/query?…`

### Desired behavior:

telegraf should make use of the URI as well and issue a request to e.g. `http://influxdb.example.com/api/query?…`

### Use case: [Why is this important (helps with prioritizing requests)]

This feature will be very helpful for setups where InfluxDB resides behind a reverse proxy, such as nginx.

**Comment by danielnelson** [comment]
This was added in https://github.com/influxdata/telegraf/pull/3224, will be in 1.5.0
