### ISSUE TITLE
input plugin err

### ISSUE THREAD

**Issue by huyujie** [influxdata/telegraf#3264]
when I write a input plugin;the code is:

```func (s *SupervisorServices) Gather(acc telegraf.Accumulator) error {
	cmd := exec.Command("/bin/bash", "-c", "supervisorctl status | awk -F ' ' '{print $1,$2}'")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return err
	}
	lines := strings.Split(string(out), "\n")
	fields := make(map[string]interface{})
	for _, line := range lines {
		if line == "" {
			continue
		}
		field := strings.Fields(line)
		fields["Status"] = field[1]
		tags := map[string]string{
			"Service": field[0],
		}
		acc.AddFields("supervisor_services", fields, tags)
	}
	return nil
}```


when insert into influxdb,the data is:
`
> select * from supervisor_services limit 5
name: supervisor_services
time                Service Status host
----                ------- ------ ----
1506352830000000000 error:  <class webservice0
1506352840000000000 error:  <class webservice0
1506352850000000000 error:  <class webservice0
1506352860000000000 error:  <class webservice0
1506352870000000000 error:  <class webservice0
`
but if telegraf and influxdb in the same host,the data is normal:
`
> select * from supervisor_services where host = 'i-pia8sqdv' and time > now() - 20s
name: supervisor_services
time                Service   Status  host
----                -------   ------  ----
1506354110000000000 kapacitor BACKOFF i-pia8sqdv
1506354110000000000 telegraf  RUNNING i-pia8sqdv
1506354120000000000 kapacitor BACKOFF i-pia8sqdv
1506354120000000000 telegraf  RUNNING i-pia8sqdv
`

**Comment by danielnelson** [comment]
That's very strange, can you test with a file output enabled and report back with the line protocol?

Also, you might be interested in this pull request https://github.com/influxdata/telegraf/pull/2295

**Comment by huyujie** [comment]
@danielnelson Thanks for your help,pull request #2295 has resolved my problem.Later,I will tell you why the problem has happend for my code when I find out the answer.

**Comment by danielnelson** [comment]
Okay, I'm going to close the issue but just add the info here and I will see it.

**Comment by huyujie** [comment]
@danielnelson when I test output file,output is
''' supervisor_service,host=firstbox,Process=error: Status="<class",Process="error:" 1511185190000000000'''
but test with telegraf --input-filter supervisor_service --test,output is
* Plugin: inputs.supervisor_service, Collection 1
> supervisor_service,Process=libvirtd,host=firstbox Status="RUNNING",Process="libvirtd" 1511186041000000000
because for rpc,I must open 9001port in supervisor config file and will affect existing services

**Comment by huyujie** [comment]
@danielnelson this err is because in this code,
```cmd := exec.Command("/bin/bash", "-c", "supervisorctl status | awk -F ' ' '{print $1,$2}'")```
just set ```cmd := exec.Command("/bin/bash", "-c", "supervisorct")``` will return correct result,most of time using a pipe in exec.Command will cause unknown error.
