### ISSUE TITLE
Unable to strip BOM character from json. httpjson plugin

### ISSUE THREAD

**Issue by murray02** [influxdata/telegraf#3265]
### Relevant telegraf.conf:
[[inputs.httpjson]]
  name = "webserver_stats"
  servers = [ "http://localhost:1234/v2/json" ]
  response_timeout = "5s"
  method = "GET"
  tag_keys = [ "Meters" ]#

### System info:

C:\telegraf>telegraf.exe --version
Telegraf v1.3.5 (git: release-1.3 7192e68b2423997177692834f53cdf171aee1a88)

Windows Server 2012

### Steps to reproduce:

1. Metrics.net application writes to localhost:1234/vs/json with Json object including BOM character.

### Expected behavior:

httpjson plugin strips BOM character from the start of the json object

### Actual behavior:

2017-09-25T14:01:45Z E! Error in plugin [inputs.httpjson]: unable to parse out as JSON, invalid character 'ï' looking for beginning of value
2017-09-25T14:01:50Z E! Error in plugin [inputs.httpjson]: unable to parse out as JSON, invalid character 'ï' looking for beginning of value

### Use case: [Why is this important (helps with prioritizing requests)]

Any Metrics.Net application cannot pick up application metrics using telegraf.

**Comment by murray02** [comment]
Tracking this. Is there a way to build the source of this in windows. The details on the homepage only builds Linux. I can open a seperate ticket but just wanted to see if this is possible.

**Comment by danielnelson** [comment]
Yes, instructions are actually the same for Windows but if you don't want to install GNU make you can instead run the commands manually after you have Go installed and setup:
```
go get github.com/sparrc/gdm
gdm restore
go build -i -o telegraf.exe ./cmd/telegraf/telegraf.go
```

**Comment by murray02** [comment]
Just wanted to leave a thanks @danielnelson for this! You saved a deadline!
