### ISSUE TITLE
SNMP Table does not insert TAG

### ISSUE THREAD

**Issue by lchabert** [influxdata/telegraf#3270]
## Bug report

I try to monitor my cisco equipments with SNMP module provided by this repo. I have copy and paste example configuration (please find below my configuration), but when i try to query data, filtering on one interface, no data is reported. I seems that 'ifDescr' tag is not set.

### Relevant telegraf.conf:

```
[[inputs.snmp]]
  agents = [ "10.16.25.2:161" ]
  version = 2
  community = "public"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "EtherLike-MIB::dot3StatsTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
```

### System info:

I'm using Telegraf v1.3.3 (git: release-1.3 46db92aad3e68af04f1732598ac89f6b9b11daf8) on Centos.
InfluxDB used: InfluxDB shell version: 1.2.4

SNMP tools installed too.

### Steps to reproduce:

1. Copy and paste configuration from this repo.
2. Configure a influxdb to export data
3. Execute this query: SELECT ifHCOutOctets FROM "interface" WHERE ifDescr="Bundle-Ether2.1611" LIMIT 10

If i dont set a WHERE filter, some data has been returned.

```> SELECT ifHCOutOctets FROM "interface" LIMIT 10
name: interface
time                ifHCOutOctets
----                -------------
1506415955000000000 4662655502539
1506415955000000000 0
1506415955000000000 91552911080
1506415955000000000 4422751227
1506415955000000000 105215026809
1506415955000000000 32742388892
1506415955000000000 285160972
1506415955000000000 0
1506415955000000000 0
1506415955000000000 1122587167
```
If i set a TAG filter:

```
> SELECT ifHCOutOctets FROM "interface" WHERE ifDescr="Bundle-Ether2.1611" LIMIT 10
> ```

No data displayed.

Do you have any hints regarding this behaviour ?

Thanks in advance,
Regards.

**Comment by phemmer** [comment]
Not all devices capable of SNMP use the same OIDs. You need to tailor the config to your specific device you want to monitor.

**Comment by lchabert** [comment]
Same OID for ?

Do you mean the suffix OID used by IF-MIB::ifDescr is not the same on IF-MIB::ifDescr  and IF-MIB::ifXTable ?

**Comment by phemmer** [comment]
No, I'm saying whatever device you're querying might not have `RFC1213-MIB::sysName.0`.
You can use `snmpget -v 2c -c public 10.16.25.2 RFC1213-MIB::sysName.0` to find out. If you don't get anything back, then your device doesn't have it.

**Comment by lchabert** [comment]
Oh ok, i have understood. In MIB::IfXTable, there is no IF-MIB::ifDescr entry (on cisco equipment).
In ifXTable, interface name is "ifName" ...

Sorry for my misunderstanding, i close this issue.
