### ISSUE TITLE
Pruning packages from Debian repositories

### ISSUE THREAD

**Issue by envintus** [influxdata/telegraf#3272]
This issue has been reported before, but I cannot find the original issue. Anyways, it seems like every time there is a new stable release of Telegraf the entire repository is wiped and the only thing that is available is the latest, stable version. I'll call it inconvenient. Especially if we want to version pin instances or our configuration management has yet to be updated for the latest stable version, because we want to test and no there's no package to pull, which creates a failure state.

Is there any way that stable versions of packages can simply remain in the repository instead of only offering latest stable?

**Comment by danielnelson** [comment]
@envintus I looked into this a little bit today, and it doesn't seem possible for there to be more than one version of a package with the same distro name.  So we can't, for example, have both 1.4.1 and 1.3.5 in jessie.

Now, I'm not an expert on this, does anyone else know if this is possible?

**Comment by danielnelson** [comment]
This might just be a limitation of reprepro https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570623

**Comment by envintus** [comment]
Daniel, thanks for checking on providing that link. We're going to start installing latest to avoid any breakage with configuration management. I see you added the `area/packaging` label to the issue. Do you plan on keeping it open with the hope to eventually provide an archive of stable releases? If not this can be closed.

**Comment by danielnelson** [comment]
Okay, we can always reopen later if this is needed.
