### ISSUE TITLE
Telegraf not building due to: Error getting VCS info for collectd.org

### ISSUE THREAD

**Issue by ihr** [influxdata/telegraf#3273]
## Bug report
When building Telegraf (e.g. make), I got the following result:

```
go get github.com/sparrc/gdm
gdm restore
======= Go Dependency Manager =======
= working dir: /Users/tgdhriv1/Go/src/github.com/influxdata/telegraf
= GOPATH:      /Users/tgdhriv1/Go
=====================================
Error getting VCS info for collectd.org
make[1]: *** [deps] Error 1
make: *** [all] Error 2
```

### System info:

- MacOS Sierra 10.12.6
- Telegraf Master branch with b8a0b84 commit
- go version go1.9 darwin/amd64
- gdm - version
- make - GNU Make 3.81

### Steps to reproduce:

1. clone Telegraf repo
2. cd to Telegraf directory
3. make

### Proposal:

I was able to fix the problem by changing the first line of the Godeps file like this:
`github.com/collectd/go-collectd 2ce144541b8903101fb8f1483cc0497a68798122`
instead of:
`collectd.org 2ce144541b8903101fb8f1483cc0497a68798122`

**Comment by danielnelson** [comment]
I think this was a temporary with the collectd domain, as it is currently working for me.  Let me know if you have continuing problems but I don't think there is any change to make.

**Comment by crazy-canux** [comment]
I got the same problem.
How to fix it?

╰─ ./scripts/build.py                                                                                               05:56:51   01.03.18
[WARNING] run: Command 'git describe --exact-match --tags 2>/dev/null' failed with error:
[INFO] print_banner:
 _____     _                       __
/__   \___| | ___  __ _ _ __ __ _ / _|
  / /\/ _ \ |/ _ \/ _` | '__/ _` | |_
 / / |  __/ |  __/ (_| | | | (_| |  _|
 \/   \___|_|\___|\__, |_|  \__,_|_|
                  |___/
 Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] go_get: Downloading `gdm`...
[INFO] go_get: Retrieving dependencies with `gdm`...
[ERROR] run: Command '/home/canux/Src/go/bin/gdm restore -v' failed with error: ======= Go Dependency Manager =======
= working dir:  /home/canux/Src/go/src/telegraf
= checkout dir: /home/canux/Src/go/src
= GOPATH:       /home/canux/Src/go
=====================================
Error getting VCS info for collectd.org
