### ISSUE TITLE
Redis response time

### ISSUE THREAD

**Issue by lshahar** [influxdata/telegraf#3275]
### Proposal:
Adding Redis latency/response time  to metric collecting.

We would like to understand we the Redis is our bottleneck at system , this metrics can help us to understand the situation.

**Comment by danielnelson** [comment]
Would the design in #1027 meet your needs if it collected a response_time field?

**Comment by danielnelson** [comment]
If the linked suggestion would not be sufficient let me know and we can reopen.

**Comment by debu99** [comment]
but who would store the response time into that response_time field? how can telegraf do it?
