### ISSUE TITLE
Processor interface should contain `Initialize` function

### ISSUE THREAD

**Issue by Alessar** [influxdata/telegraf#3276]
## Feature Request
Processor interface has very limited number of a functions.
So it will be good if function `Initialize` appear at this interface.
That function should be invoked one time after creating plugin and before main processing.
(Like `Connect` in `Output` interface).

### Use case:
It should helps with making plugin initializing.
(If this function invoked in plugin during creating manually - (at first) none of configuration will be passed into that plugin, (at second) it will be invoked during `./telegraf config` and all configuration outputs will be damaged by output from manually invoked initialize function)

**Comment by danielnelson** [comment]
Yes, I think all of the plugins need a way to simply initialize themselves based on the config.  This is actually something that will be a part of the configuration plugin system in #272 

In the meantime the best way to deal with this is calling a guarded initialize function either using sync.Once or a boolean at the start of the Apply function.

**Comment by danielnelson** [comment]
This functionality was added several versions back, all plugins can implement this interface.
```go
// Initializer is an interface that all plugin types: Inputs, Outputs,
// Processors, and Aggregators can optionally implement to initialize the
// plugin.
type Initializer interface {
	// Init performs one time setup of the plugin and returns an error if the
	// configuration is invalid.
	Init() error
}
```
