### ISSUE TITLE
Outputs.influxdb sends incomplete or corrupted line protocol data to influxdb

### ISSUE THREAD

**Issue by scanterog** [influxdata/telegraf#3278]
## Bug report

Outputs.influxdb sends incomplete or corrupted line protocol data to influxdb in a non-reproducible way.

I'm using telegraf to parse `/var/log/syslog` with logparser. I define a set of custom grok patterns. I am sending the data to two outputs: (1) outputs.influxdb and (2) outputs.file. The last one just for testing.

### Relevant telegraf.conf:

```
[[outputs.influxdb]]
  urls = ["https://influxdb.domain.tld"]
  database = "syslog"
  timeout = "5s"
  username = "<myuser>"
  password = "<mypass>"

[[outputs.file]]
  files = ["/tmp/telegraf"]

[[inputs.logparser]]
  files = ["/var/log/syslog"]

  [inputs.logparser.grok]
    patterns = ["%{REST_API}", "%{REST_ES}"]
    measurement = "rest"
    custom_pattern_files = ["/etc/telegraf/grok_patterns"]

  [inputs.logparser.tags]
    cluster = "<cluster>"
    host = "<host>"
    service = "<service>"
```

### System info:

Telegraf v1.4.1 (git: release-1.4 2de7aa23d7d3c3bcf639d417129ab7c17d83399b)
Ubuntu 16.04.3 LTS 4.8.0-45-generic x86_64

### Steps to reproduce:

As I told before, I can't reproduce the error.

### Expected behavior:

Send correct Line Protocol data to influxDB after correct parsing.

### Actual behavior:

Send incomplete or corrupted Line Protocol data to influxDB.

### Additional info:

At first, I though it was parsing issue but I'm not sure because I can see correct line protocol in file output. Example:

**syslog line:**
```Sep 28 16:16:24 lb-test sh[29451] 16:16:01 rest.1 | INFO:elasticsearch:GET http://es.domain.tld:9200/lb-test/blogs/59985e2dfcfd6373249a742a [status:200 request:0.003s]```

**line protocol output (/tmp/telegraf):**
```rest,id=test,path=/var/log/syslog,host=fe1,service=lb,cluster=a ptype="rest.1",reqtime="16:16:01",path="http://es.domain.tld:9200/lb-test/blogs/59985e2dfcfd6373249a742a",timestamp="Sep 28 16:16:24",level="INFO",method="GET",resp_code=200,resp_time=0.003 1506608184791771531```

**telegraf error:**
```Sep 28 14:16:30 fe2 telegraf[59107]: 2017-09-28T14:16:30Z E! Parse error; dropping points: Response Error: Status Code [400], expected [204], [partial write: unable to parse 'rest,id=test,path=/var/log/syslog,host=fe1,service=lb,cluster=a ptype="rest.1",reqtime="16:16:01",path="http://es.domain.tld:9200/lb-test/blogs/59985e2dfcfd6373249a742a",timestamp="Sep 28 16:16:24",level="INFO",method="GET",resp_code=200,r': invalid field format dropped=0]```

As you can see, line protocol output is fine, but it looks like telegraf sent truncated data to influxDB. I have several cases like this, even mixed data like there were some corruption in memory. It happens sometimes, I can't find a pattern.

In previous example, looks like `esp_time=0.003 1506608184791771531` was not sent to influxDB, hence "invalid field format" error.

I have tested to send the previous line protocol data (shown in /tmp/telegraf) using curl directly and it works fine.
```curl -u <user>:<pass> -i -XPOST 'https://influxdb.domain.tld/write?db=syslog' --data-binary @/tmp/telegraf``` 

At start, our influxDB contains no corrupted data like these:

```
> select * from rest limit 1;
name: rest
time                cluster host id   method path path_1          ptype  reqtime  resp_code resp_size resp_time service    timestamp
----                ------- ---- --   ------ ---- ------          -----  -------  --------- --------- --------- -------    ---------
1506023246878155950 a   fe1  test GET    /api /var/log/syslog rest.1 19:33:02 200       5717      0         lb Sep 21 21:47:26
```

Over time, it gets corrupted:
```> select * from rest order by time desc limit 1;
name: rest
time                <;�ptype   �2�reqtime     �m+cluster   ۍ%�resp_code    cl cl759�uster   clust��)�er       cluster esp_code esp_time h hor�-�st     hosz�-7t   host huster i id      idrvice iduster ime imestamp irvice ist lr�Cevel   le�/�vel     leA�7vel   lel leme lepath level m/C%�ethod   m�          %ethod me      meqtime         metho?d methocode method              method�]� metresp_time p_code p_time          pa�Wth pa_time                                                  path            patesp_time rE?3esp_time     r��!wesp_time   rP�eqtime re                   re75�sp_code   req��time   reqti>�me   reqtib�%me reqtime                res�S3�p_code     res��p_code     resp_c�z2�ode     resp_co"�de   resp_coH�e resp_code     resp_codecode resp_size resp_time            resp_timeZ� resp_timeevel resp_timod       resp_tiresp_time rethod             se;�krvice seoFervice     serv�o�ice serviJf {ce        service              servicvice t&9.�imestamp tethod                 tim   timeP��stamp times              timesp          timest9Y5wamp timestamp timtamp type
```

Aside from that, inside database there are also many no desired new measurements like:

```
> use syslog
> show measurements
Ã���Erest
Ã���irest
Ã���p9rest
Ã����Arest
��=stuff
```
If this is just some parsing error (I mean wrong grok patterns), I wouldn't expect more measurements (just more tag/fields inside rest measurement). I honestly don't know how to debug this. For instance, I usually find telegraf errors with data belonging to one host inside another host, i.e, fe2 might contain line protocol data errors from fe1.

Thanks!

**Comment by danielnelson** [comment]
Do you happen to be using nginx as a proxy?

**Comment by scanterog** [comment]
yes, forgot to mention that. We're using nginx as a proxy. Our influxDB instance is running inside an LXD container. But it's just a quite simple configuration.

**Comment by danielnelson** [comment]
Okay, I think this is the same issue as https://github.com/influxdata/telegraf/issues/2854

Would you be able to add `content_encoding = "gzip"` to your influxdb output and see if it helps?

**Comment by scanterog** [comment]
Done! Thanks! I'll keep you updated.

**Comment by scanterog** [comment]
Hi @danielnelson! It's been a day and everything is fine so far :) usually it used to happen in some hours. I'll post update again on next week! Thanks!

**Comment by danielnelson** [comment]
That's great, I'm going to close this issue and if you see any problems then please comment over on #2854
