### ISSUE TITLE
ceph plugin should support new ceph version(luminous)

### ISSUE THREAD

**Issue by cloudislife** [influxdata/telegraf#3280]
As response data changed in ceph luminous ,the current ceph plugin could not work well.So,the plugin should be updated to support for ceph luminous.

**Comment by danielnelson** [comment]
What happens when you try to use the current plugin with Ceph Luminous?

**Comment by cloudislife** [comment]
Oh,sorry,it's my fault,I made a incorrect permission in my new ceph env. Thx i'll close this issues
