### ISSUE TITLE
telegraf doesn't play well with kapacitor.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/telegraf#3285]
telegraf's batching causes kapacitor to basically be non-functional.

time oriented nodes like derivative and window seems to fail miserably. Would adding a socket processor fix these issues?

**Comment by danielnelson** [comment]
I'm guessing you have a pipeline like: Telegraf -> Kapacitor -> InfluxDB?

What would the socket processor do?  Would it be like the socket_writer output so that points are sent immediately on collection?

**Comment by james-lawrence** [comment]
actually pipeline is using telegraf to push to a local kapacitor process and to a remote influxdb.
telegraf -> (kapacitor, influxdb).

and basically yes, socket_write but sent immediately.

we can also add alert nodes with statechangeonly to the list of things that fail miserably =/

**Comment by danielnelson** [comment]
Even with immediate send the gather is still on a periodic interval, so it seems that you could reduce latency but the fundamental problem would remain.

Can you show your TICK script and what plugins it is processing?

cc @desa

**Comment by james-lawrence** [comment]
I've burned all day trying to get this basic alert to work, this is the current version:

the log() node looks good. I see all the events I expect to see, what doesn't seem to be working with this script is the stateChangesOnly(3s). the alert triggers once and never again.
```
var data = stream
  |from()
    .database('application')
    .measurement('messages.dropped')
    .truncate(1s)

var alert = data
  |groupBy(*)
  |log()
  |alert()
    .id('dropped.messages')
    .warn(lambda: bool('true'))
    .message('{{.Level}}  {{index .Tags "instance_id" }} {{index .Tags "application"}} {{index .Tags "environment"}} {{.ID}}')
    .stateChangesOnly(3s)
    .slack().channel('#eng-alert-test')
```

by plugins do you mean telegraf's conf?

**Comment by danielnelson** [comment]
Yeah, probably don't need full config just which plugins you are using.  I'm mostly interested in if you are using both service inputs (immediate) and normal inputs (interval).

I'm really terrible with TICK scripts, but have you tried using a batch instead of a stream?

**Comment by desa** [comment]
@james-lawrence  Just took a look. I'm not totally sure what the issue is. Is it that the alert node isn't firing every 3s?

>telegraf's batching causes kapacitor to basically be non-functional.

> time oriented nodes like derivative and window seems to fail miserably. ...

Can you be more specific. What's the issue?

> the log() node looks good. I see all the events I expect to see, what doesn't seem to be working with this script is the stateChangesOnly(3s). the alert triggers once and never again.

This makes me think that it's definitely a Kapacitor issue and not a Telegraf issue.

**Comment by danielnelson** [comment]
@james-lawrence Let me know if you still need help with this.

**Comment by james-lawrence** [comment]
I do, but its work related and it keeps getting punted on the priority list, and I want a chance to dig further into the cause.

**Comment by danielnelson** [comment]
Okay, I know how that goes...  Just post here when you are working on it again.
