### ISSUE TITLE
MQTT Consumer still fails when set to 30s

### ISSUE THREAD

**Issue by tstaals** [influxdata/telegraf#3288]
After the first report #3284 all seem to work , but I think i made a mistake somewhere.

Telegraf still fails with msg 
MQTT Consumer, invalid connection_timeout value: {30000000000}
2017-09-30T12:16:02Z E! Service for input inputs.mqtt_consumer failed to start, exiting
MQTT Consumer, invalid connection_timeout value: {20000000000}

So It does not work with connection_timeout = "30s" or connection_timeout = "20s" but It does work when set to connection_timeout = "10s"

hope this will help in fixing this, but the problem seems to be deeper then mentioned in #3284

**Comment by danielnelson** [comment]
I think this also fixed now by cdca81c9999364cf6fb35f25fabdad31bb81a177, thank you for testing the original fix.
