### ISSUE TITLE
Windows Perfmon Counters Not Detected 

### ISSUE THREAD

**Issue by fenneh** [influxdata/telegraf#3293]
This isn't necessarily a bug - maybe an oversight. 

## Bug report

If Telegraf starts up before an application has started publishing its own performance counters then they are never detected and no metrics are sent. A restart of the Telegraf agent is then required.

### System info:

Windows Server 2008R2, 2012R2. Telegraf 1.4.0.

### Steps to reproduce:

1. Start Telegraf Agent
2. Start Windows App which publishes to perfmon
3. No perfmon capture

### Expected behavior:

Perfmon counters will be picked up and shipped

### Actual behavior:

No perfmon counters detected

## Feature Request

Either allow telegraf to reload it's config from disk on a set period or allow telegraf to re-evaluate its own config every X minutes

**Comment by andryua** [comment]
Same issue on Windows 10 x64

> c:\Program Files\telegraf>telegraf.exe -config telegraf.conf -test
> * Plugin: inputs.win_perf_counters, Collection 1
> Invalid query: '\Processor(*)\% Idle Time'. Error: No data to return.
> Invalid query: '\Processor(*)\% Interrupt Time'. Error: No data to return.
> Invalid query: '\Processor(*)\% Privileged Time'. Error: No data to return.
> Invalid query: '\Processor(*)\% User Time'. Error: No data to return.
> Invalid query: '\Processor(*)\% Processor Time'. Error: No data to return.
> Invalid query: '\Processor(*)\% DPC Time'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\% Idle Time'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\% Disk Time'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\% Disk Read Time'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\% Disk Write Time'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\Current Disk Queue Length'. Error: No data to re
> turn.
> Invalid query: '\LogicalDisk(*)\% Free Space'. Error: No data to return.
> Invalid query: '\LogicalDisk(*)\Free Megabytes'. Error: No data to return.
> Invalid query: '\PhysicalDisk(*)\Disk Read Bytes/sec'. Error: No data to return.
> 
> Invalid query: '\PhysicalDisk(*)\Disk Write Bytes/sec'. Error: No data to return
> .
> Invalid query: '\PhysicalDisk(*)\Current Disk Queue Length'. Error: No data to r
> eturn.
> Invalid query: '\PhysicalDisk(*)\Disk Reads/sec'. Error: No data to return.
> Invalid query: '\PhysicalDisk(*)\Disk Writes/sec'. Error: No data to return.
> Invalid query: '\PhysicalDisk(*)\% Disk Time'. Error: No data to return.
> Invalid query: '\PhysicalDisk(*)\% Disk Read Time'. Error: No data to return.
> Invalid query: '\PhysicalDisk(*)\% Disk Write Time'. Error: No data to return.
> Invalid query: '\Network Interface(*)\Bytes Received/sec'. Error: No data to ret
> urn.
> Invalid query: '\Network Interface(*)\Bytes Sent/sec'. Error: No data to return.
> 
> Invalid query: '\Network Interface(*)\Packets Received/sec'. Error: No data to r
> eturn.
> Invalid query: '\Network Interface(*)\Packets Sent/sec'. Error: No data to retur
> n.
> Invalid query: '\Network Interface(*)\Packets Received Discarded'. Error: No dat
> a to return.
> Invalid query: '\Network Interface(*)\Packets Outbound Discarded'. Error: No dat
> a to return.
> Invalid query: '\Network Interface(*)\Packets Received Errors'. Error: No data t
> o return.
> Invalid query: '\Network Interface(*)\Packets Outbound Errors'. Error: No data t
> o return.
> Invalid query: '\System\Context Switches/sec'. Error: No data to return.
> Invalid query: '\System\System Calls/sec'. Error: No data to return.
> Invalid query: '\System\Processor Queue Length'. Error: No data to return.
> Invalid query: '\System\System Up Time'. Error: No data to return.
> Invalid query: '\System\Threads'. Error: No data to return.
> Invalid query: '\System\Processes'. Error: No data to return.
> Invalid query: '\Memory\Available Bytes'. Error: No data to return.
> Invalid query: '\Memory\Cache Faults/sec'. Error: No data to return.
> Invalid query: '\Memory\Demand Zero Faults/sec'. Error: No data to return.
> Invalid query: '\Memory\Page Faults/sec'. Error: No data to return.
> Invalid query: '\Memory\Pages/sec'. Error: No data to return.
> Invalid query: '\Memory\Transition Faults/sec'. Error: No data to return.
> Invalid query: '\Memory\Pool Nonpaged Bytes'. Error: No data to return.
> Invalid query: '\Memory\Pool Paged Bytes'. Error: No data to return.
> Invalid query: '\Memory\Standby Cache Reserve Bytes'. Error: No data to return.
> Invalid query: '\Memory\Standby Cache Normal Priority Bytes'. Error: No data to
> return.
> Invalid query: '\Memory\Standby Cache Core Bytes'. Error: No data to return.
> Invalid query: '\Paging File(_Total)\% Usage'. Error: No data to return.
> Invalid query: '\Process(*)\% Processor Time'. Error: No data to return.
> Invalid query: '\Process(*)\Handle Count'. Error: No data to return.
> Invalid query: '\Process(*)\Private Bytes'. Error: No data to return.
> Invalid query: '\Process(*)\Thread Count'. Error: No data to return.
> Invalid query: '\Process(*)\Virtual Bytes'. Error: No data to return.
> Invalid query: '\Process(*)\Working Set'. Error: No data to return.
>

**Comment by danielnelson** [comment]
Related pull request: #2345

**Comment by andryua** [comment]
> KeepAlive = true 
doesn't support v 1.4.1 and nightly build too

**Comment by danielnelson** [comment]
@fenneh @andryua This may have been addressed by #4189, would it be possible for you to retest the issue using the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds)?

**Comment by fenneh** [comment]
Testing it out now @danielnelson - Will close the issue off if all is well.
