### ISSUE TITLE
Ping input is not compatible with GNU inetutils ping

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3295]
## Bug report

The GNU inetutils ping utility does not work with the ping input because the -W flag will not accept a float.  This version of ping is included in the official docker images:

```
$ /bin/ping -V
ping (GNU inetutils) 1.9.4
$ /bin/ping -c 1 -n -s 16 -W 1.0 8.8.8.8
ping: invalid value (`1.0' near `.0')
$ /bin/ping -c 1 -n -s 16 -W 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 16 data bytes
24 bytes from 8.8.8.8: icmp_seq=0 ttl=59 time=15.179 ms
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 15.179/15.179/15.179/0.000 ms
```

```
$ /bin/ping -V
ping utility, iputils-s20161105
$ /bin/ping -c 1 -n -s 16 -W 1.0 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 16(44) bytes of data.
24 bytes from 8.8.8.8: icmp_seq=1 ttl=59 time=25.8 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 25.819/25.819/25.819/0.000 ms
```

### Relevant telegraf.conf:
```toml
# Ping given url(s) and return statistics
[[inputs.ping]]
  urls = ["8.8.8.8"]
```

### System info:
```
Telegraf v1.5.0~ed6f438c (git: master ed6f438c)
```

### Steps to reproduce:

1. Install `inetutils-ping`
2. Run telegraf with ping input

### Expected behavior:
Ping metrics are created

### Actual behavior:
```
E! Error in plugin [inputs.ping]: Fatal error processing ping output: 8.8.8.8
```

**Comment by dexy31337** [comment]
you should add iputils-ping package to telegraf docker image to fix this

**Comment by ybizeul** [comment]
Confirmed, `ping` official docker image plugin doesn't work until you manually install `iputils-ping`

**Comment by pshima** [comment]
Slightly confused on this issue, as it appears it was fixed here: https://github.com/influxdata/influxdata-docker/issues/60

But today did run into this problem with the above fixing it.

The change here does seem to address it but apparently did not work for me: https://github.com/influxdata/influxdata-docker/pull/69/files

**Comment by danielnelson** [comment]
It looks like that code is not part of the latest Dockerfile.  To close this issue we should ensure the plugin works with `inetutils-ping`, but I'll update the Dockerfile in the meantime.

**Comment by ssoroka** [comment]
looks like this is resolved now and was never closed.
