### ISSUE TITLE
Telegraf fails starting with MQTT consumer is connection_timeout is not defined

### ISSUE THREAD

**Issue by dinacel** [influxdata/telegraf#3301]
### Relevant telegraf.conf:
```
[[inputs.mqtt_consumer]]

   ## Connection timeout for initial connection in seconds
   connection_timeout = "30s"
```

### System info:
Telegraf version 1.4.1-1

```
root@local:~# apt-cache policy telegraf
telegraf:
  Installed: 1.4.1-1
  Candidate: 1.4.1-1
  Version table:
 *** 1.4.1-1 0
        900 https://repos.influxdata.com/debian/ jessie/stable amd64 Packages
        100 /var/lib/dpkg/status
```

### Steps to reproduce:
1. Remove or comment "connection_timeout" parameter in the telegraf.conf (or upgrade telegraf from a previous version).
2. Restart telegraf.

### Expected behavior:
Telegraf start.

### Actual behavior:
Telegraf fails starting with a message in the logs :

```
MQTT Consumer, invalid connection_timeout value: {0}
```

**Comment by danielnelson** [comment]
Sorry about this regression, we have a fix for this in 1.4.2. https://github.com/influxdata/telegraf/issues/3284
