### ISSUE TITLE
Feature Request: Add more tags to "System" metrics for telegraf agent on EC2, GCE instances

### ISSUE THREAD

**Issue by adityacs** [influxdata/telegraf#3314]
## Feature Request

Add tags to "System"(cpu, memory, disk) metrics which would give more information other than "host".

### Proposal:

When we collect docker metrics we get labels from container and we add these as tags to cpu, mem, disk metrics. The labels would be **task.id, service_name** etc.. 

In the same way when we collect metrics from "system" we should be allowing to add more tags.

### Use case:
For example, When telegraf is installed in EC2, other than just tagging the host we should also be tagging **instance-id, instance_type, autoscaling_group_name** etc.. This would help better aggregation of metrics by better "group by".

**Comment by adityacs** [comment]
@danielnelson I am not sure if this feature already exists. Let me know your views on this.

**Comment by danielnelson** [comment]
I think the best way to do this now would be to add them as env vars, perhaps using `/etc/default/telegraf` and then add them to the global_tags section of the config.  Does that work for you?

**Comment by adityacs** [comment]
@danielnelson Makes sense.

**Comment by danielnelson** [comment]
If it doesn't work out we can reopen this issue.
