### ISSUE TITLE
cloudwatch output uses ListMetricData

### ISSUE THREAD

**Issue by adamchainz** [influxdata/telegraf#3319]
## Bug report

When starting the Cloudwatch output plugin, it tries to list some metrics, even though this isn't needed for normal operation: https://github.com/influxdata/telegraf/blob/ac1fa05672a3eb9342b23534f22cb5538576e759/plugins/outputs/cloudwatch/cloudwatch.go#L62 . Thus the AWS credentials in use need access to `ListMetricData` even though when in use the plugin only needs `PutMetricData`.

The required permissions aren't even documented for the plugin.

### Relevant telegraf.conf:

```ini
[[outputs.cloudwatch]]
region = "us-east-1"
namespace = "foo"
```

### System info:

Latest telegraf

### Steps to reproduce:

1. Create an AWS IAM user/role with only `PutMetricData` rights
2. Configure cloudwatch output in telegraf, start it

### Expected behavior:

Successful start

### Actual behavior:

It fails

### Additional info:

AWS STS GetSessionToken can be used to test connection without needing any specific permissions: https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.GetSessionToken

**Comment by danielnelson** [comment]
Thanks for the report, I agree on all points.  Is this something you would be able to work on?

**Comment by adamchainz** [comment]
Never used this language before but I’ll give it a... Go
