### ISSUE TITLE
http-ping plugin

### ISSUE THREAD

**Issue by kureikain** [influxdata/telegraf#332]
We have a `ping` plugin, if so, we probably should have a HTTP plugin that fetch the URL and record response time, which is an important metric for many people. 

Will this be considered? I know we can wrap some script to use `exec` plugin but by that logic probably everything is exec

**Comment by otoolep** [comment]
This isn't a bad idea, it would allow simple up/not-up checks of a website, for example.

**Comment by kokarn** [comment]
:+1: 
This would be very useful. 
Maybe even options to load all assets or not?

**Comment by kureikain** [comment]
sound like people like it. Let me whip up something and see

**Comment by sparrc** [comment]
@kureikain what about an "http" option to the `ping` plugin instead of a separate plugin? Or it could just take two url lists, `urls` and `http_ping_urls`

**Comment by otoolep** [comment]
@sparrc -- I would avoid that. We're using the word "ping" in a metaphorical sense, but I wouldn't actually add this functionality to the ping plugin.

**Comment by kokarn** [comment]
A friend threw together a go app that does exactly this except it takes a json list of urls as input.
Should require minimal effort to port to a plugin
https://github.com/gust1n/isitupandfast

**Comment by jlaffaye** [comment]
and https cert expiration date ;)

**Comment by kureikain** [comment]
I'm working on this plugin. Write in here to avoid wasting someone's time.

**Comment by Lswith** [comment]
I think I'll give implementing this a shot.
