### ISSUE TITLE
README claims there are hadoop plugins, but there are none.

### ISSUE THREAD

**Issue by Kranach** [influxdata/telegraf#3323]
Hey, maybe im missing something, but README for telegraf states there are plugins for Hadoop services. Yet I don't see anything that would collects basic metrics for HDFS, YARN or Spark which is what I would expect. (There is something only for Zookeper, but it's not that much useful).

## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
>  with a plugin system so that developers in the community can easily add support for collecting metrics from well known services (like Hadoop, or Postgres, or Redis)

Thanks for opening the issue, I agree that this line is somewhat confusing.  I think it means to say is that the plugin system *could* be used to support these services, and was written back when Telegraf had very few plugins as a suggestion of some services we would like to have added.

Anyway, I updated the readme to remove these examples.  c74c29b164ccb0facc7c24bcbcc78fc31e033eba
