### ISSUE TITLE
telegraf on windows output plugin elasticsearch

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3324]
Hello,

We have installed telegraf on our windows machine and we need to send data to elasticsearch 

for this we we have an option in linux..

do we have any other possiblity to send windows data to Elasticsearch

**Comment by danielnelson** [comment]
I believe this plugin will work if you add it your config, you can print out the default config using `telegraf --usage elasticsearch` and copy the elasticsearch output into your config file.

Let me know if it doesn't work and we can reopen the issue.

**Comment by hemasalma** [comment]
Hi...

Am able to use the elasticsearch output plugin but am not able to get the all the metrics:
metrics that are collected by win_perf_counters.object are not collected by this.
metrics like win_cpu, win_mem, win_sytem, win_disk....

am runnin the conf file using the command:
telegraf --config telegraf.conf

the error am getting is:

C:\telegraf>telegraf.exe --config telegraf.conf --test
* Plugin: inputs.win_perf_counters, Collection 1
> win_cpu,instance=0,objectname=Processor,host=sgpl007 Percent_Idle_Time=0 15078
00929000000000
unexpected fault address 0x5ce7e56f
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x5ce7e56f pc=0x46a559]

goroutine 20 [running]:
runtime.throw(0x1111e8a, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x7c fp=0x13681cbc sp=0x13681cb0

runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:164 +0xe2 fp=0x13681cd0 sp=0
x13681cbc
syscall.UTF16ToString(0x5ce7e56f, 0x20000000, 0x20000000, 0x17f0c00, 0x137386e0)

        /usr/local/go/src/syscall/syscall_windows.go:49 +0x29 fp=0x13681cec sp=0
x13681cd0
github.com/influxdata/telegraf/plugins/inputs/win_perf_counters.UTF16PtrToString
(0x5ce7e56f, 0x137cd347, 0x7)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/i
nputs/win_perf_counters/pdh.go:421 +0x35 fp=0x13681d04 sp=0x13681cec
github.com/influxdata/telegraf/plugins/inputs/win_perf_counters.(*Win_PerfCounte
rs).Gather(0x13af9920, 0x17eade0, 0x137c0960, 0x1, 0x1)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/i
nputs/win_perf_counters/win_perf_counters.go:211 +0x1db fp=0x13681d90 sp=0x13681
d04
github.com/influxdata/telegraf/agent.(*Agent).Test(0x138b6d50, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/age
nt.go:211 +0x3f4 fp=0x13681e44 sp=0x13681d90
main.reloadLoop(0x13a35800, 0x18daee0, 0x0, 0x0, 0x18daee0, 0x0, 0x0, 0x18daee0,
 0x0, 0x0, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/teleg
raf/telegraf.go:179 +0xae3 fp=0x13681f9c sp=0x13681e44
main.(*program).run(0x13a40120)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/teleg
raf/telegraf.go:262 +0xdc fp=0x13681fe8 sp=0x13681f9c
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1629 +0x1 fp=0x13681fec sp=0x13681fe
8
created by main.(*program).Start
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/teleg
raf/telegraf.go:251 +0x33

goroutine 1 [chan receive]:
github.com/kardianos/service.(*windowsService).Run(0x1391f780, 0x13a40120, 0x138
eda40)
        /home/ubuntu/telegraf-build/src/github.com/kardianos/service/service_win
dows.go:273 +0x127
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/teleg
raf/telegraf.go:398 +0x9a2

goroutine 17 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x14f
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select]:
github.com/influxdata/telegraf/agent.(*Agent).Test.func1(0x1366c880, 0x1366c840)

        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/age
nt.go:184 +0xa4
created by github.com/influxdata/telegraf/agent.(*Agent).Test
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/age
nt.go:191 +0xc6

**Comment by danielnelson** [comment]
This is a known issue with the 32-bit Windows build and the win_perf_counters plugin (https://github.com/influxdata/telegraf/issues/2468).  If you can switch to the 64-bit version that will fix it, otherwise I am hoping someone with a 32-bit Windows can fix and send a pull request.

**Comment by hemasalma** [comment]
Hi... 

ours is 64-bit windows

**Comment by danielnelson** [comment]
Are you positive you are using the [Windows 64-bit Telegraf](https://dl.influxdata.com/telegraf/releases/telegraf-1.4.2_windows_amd64.zip)?
