### ISSUE TITLE
[Feature Request] Input plugin for Grafana internal metrics

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#3330]
Collect Grafana internal metrics from endpoint `/api/metrics`
official doc:
http://docs.grafana.org/administration/metrics/

**Comment by danielnelson** [comment]
In the meantime, you could use a promentheus input or possible a socket_listener with the graphite parser.

I'll leave this open because I have an idea around having plugins instantiate another plugin.  Essentially this plugin would return a prometheus input correctly setup for grafana.

**Comment by fchiorascu** [comment]
Hi Daniel. Any news about Grafana internal metrics in a easy and nice view? :) :+1:

**Comment by danielnelson** [comment]
@fchiorascu Not yet, I've been occupied on other issues, I'll update this issue when I have news.

**Comment by jmorcar** [comment]
> In the meantime, you could use a promentheus input or possible a socket_listener with the graphite parser.
> 
> I'll leave this open because I have an idea around having plugins instantiate another plugin. Essentially this plugin would return a prometheus input correctly setup for grafana.

Could you indicate an example? If is OK then you could use output.influxdb to export metrics after in influxdb format, rigth?

**Comment by powersj** [comment]
Using the [prometheus input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) is right answer here, rather than creating a different plugin for every piece of software that offers prometehus based metrics. See the plugin readme I linked to above for an example.
