### ISSUE TITLE
Possibility to merge or override configs

### ISSUE THREAD

**Issue by muhahacz** [influxdata/telegraf#3338]
Is it not possible to merge or override config files just like in influxd?

For example:
`/opt/influxdb/influxd config -config /config/influxdb.custom.conf > /config/influxdb.conf`

Problem is that even if you starts telegraf with --config-directory /config/, it will double the configuration from both files. It makes dockerizing a lit a bit harder.

Thanks

**Comment by danielnelson** [comment]
Sorry, I don't understand your question.  Can you tell me what you tried, what you expected to happen, and what happened instead?
