### ISSUE TITLE
System Input Plugin should have also variable for determinate path to /hostfs/var

### ISSUE THREAD

**Issue by muhahacz** [influxdata/telegraf#3339]
## Bug report
System Input Plugin should have also variable for determinate path to /hostfs/var

Logs:
2017-10-13T04:52:40Z E! Error in plugin [inputs.system]: open /var/run/utmp: no such file or directory

HOST_VAR=/hostfs/var should be a solution, just like in HOST_ETC= case

### Relevant telegraf.conf:

 [inputs.system]

### System info:

Telegraph 1.4.2
Alpine 3.6

### Steps to reproduce:

docker run -d  --name telegraf --net host -v /:/hostfs:ro -e HOST_MOUNT_PREFIX=/hostfs -e HOST_ETC=/hostfs/etc mytelegraf

### Proposal:

docker run -d  --name telegraf -v /:/hostfs:ro -e HOST_MOUNT_PREFIX=/hostfs -e HOST_ETC=/hostfs/etc -e HOST_VAR=/hostfs/var mytelegraf 

or

docker run -d  --name telegraf -v /:/hostfs:ro -e HOST_MOUNT_PREFIX=/hostfs -e HOSTFS_PREFIX=/hostfs mytelegraf 

### Additional info:
There are no steps in docs to run telegraph in docker with host monitoring.

For example:
--net host ?
--cap_add ?
--priviledged ?

Thanks

**Comment by danielnelson** [comment]
@shirou Do you think we should add a `HOST_VAR` environment variable support to gopsutil?  I believe the relevant code is https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L135

**Comment by danielnelson** [comment]
@muhahacz I know some people have used the advice in this comment for setup: https://github.com/influxdata/telegraf/issues/1544#issuecomment-278955406.  I agree we need to do additional testing and add some setup advice to the documentation.

**Comment by shirou** [comment]
@danielnelson I agree to add environmental variable support to `host.Users`. Something like `HOST_VAR` as described proposal?

**Comment by danielnelson** [comment]
@shirou Yes, I think so.  I'll submit a PR later today.

**Comment by muhahacz** [comment]
Seems its fixed in gopsutil v2.17.10.
Will it be available in 1.4.4 ?
Thanks

**Comment by danielnelson** [comment]
Thanks for the update @muhahacz, this seems similar to the issues we had with `/etc/mtab` https://github.com/influxdata/telegraf/issues/1544#issuecomment-260694778

I'm not sure if there is a better way to address this than your workaround.
