### ISSUE TITLE
Logparser duplicates entries from rotated logs after path key was added

### ISSUE THREAD

**Issue by kylejvrsa** [influxdata/telegraf#3341]
We use the logparser to read our logs as well as our rotated logs what this means is that we have for example:
measurement.log which when rotated becomes
measurment.log.2017-08-02 and a new measurement.log is generated. We have telegraf reading measurement.log* which means it reads all the measurement.log files including the rotated ones. This gave us the buffer that if telegraf were to crash or were unable to read the logfile , we could simply fix the issue and start telegraf again and it would read all the logs that it missed since it crashed or were unable to read. It would then also be able to distinguish between the entries because they would be  the same so there would be no duplicates.

Since 1.4 and the addition of the path key it now sees the path as a different variable and imports duplicate entries because it will read in measurement.log and then read it in again when it gets rotated where as previously it would just see it as already imported.

Telegraf 1.4.1
Influxdb 1.3.5

Could we not have a config option that disables path or better have it match the first part of the path and anything after a certain point is seen as rotated logs or have a config option to say these are rotated logs?

Any ideas?

**Comment by danielnelson** [comment]
Thanks for letting me know about this, I did not anticipate this side effect.

I can think of a few possible solutions.  You could use tagexclude to remove the tag:
```toml
[[inputs.logparser]]
  tagexclude = ["path"]
```

You could also overwrite the tag with a static string:
```toml
[[inputs.logparser]]
  [inputs.logparser.tags]
    path = "measurement.log"
```

Let me know if one of these options works for you.

**Comment by kylejvrsa** [comment]
@danielnelson 

Thanks for the reply!

Ok I got tagexclude to work, but couldn't specify the tag using [inputs.logparser.tags]

[[inputs.logparser]]
     files = ["/path/to/metasurement.log*"]
     from_beginning = true

  [inputs.logparser.tags]
    path = "measurement.log"

  [inputs.logparser.grok]
     patterns = ["%{SOME_PATERN}"]
     measurement = "some_measurement"
     custom_patterns = '''
       SOME_PATERN
     '''
As far as I understand that is supposed to work right or could it be that the grok is interfering?

It would be very useful to have path going forward.

**Comment by danielnelson** [comment]
It looks like the tags added by the plugin have a higher precedence than the tags table, which in turn has higher precedence than global tags.  It seems like we should change this, but I am nervous about breaking configurations.  I opened #3362 to discuss this change.

In the meantime, I believe you will need to use tagexclude.

**Comment by kylejvrsa** [comment]
Thanks @danielnelson

**Comment by danielnelson** [comment]
I'm going to close this issue, keep an eye on #3362 to track the precedence change.
