### ISSUE TITLE
Haproxy : field corresponding to `servers' is not defined in `*system.SystemStats'

### ISSUE THREAD

**Issue by ghost** [influxdata/telegraf#3353]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by beforeborn** [comment]
how it get solved?

**Comment by ViliusKraujutis** [comment]
I got same issue too.

**Comment by ViliusKraujutis** [comment]
I had to uncomment a section "# [mqtt_consumer]" so then "servers" parameter would be picked up.
