### ISSUE TITLE
[httpjson] add option to silence complaints about null values

### ISSUE THREAD

**Issue by msoltyspl** [influxdata/telegraf#3357]
Currently, whenever an explicit null value is encountered by httpjson - it always informs about it in the logs and there seems to be no way to turn it off, e.g.:
```
json parser ignoring pipelines_.monitoring-logstash_events
json parser ignoring pipelines_.monitoring-logstash_reloads_last_success_timestamp
json parser ignoring pipelines_.monitoring-logstash_reloads_last_failure_timestamp
json parser ignoring pipelines_.monitoring-logstash_reloads_last_error
json parser ignoring pipelines_.monitoring-logstash_queue
json parser ignoring pipelines_main_reloads_last_error
json parser ignoring pipelines_main_reloads_last_success_timestamp
json parser ignoring pipelines_main_reloads_last_failure_timestamp
```

So far I've been reloading (logstash) once with failed config and once with correct config to silence some of those messages, but that's a bit crude workaround. Explicit nulls are not technically invalid - so an option to just ignore those silently would be really welcome.

**Comment by danielnelson** [comment]
I think we should just silence this without providing an option.  Here is some JSON input that will trigger this message: `{"x": null}`

**Comment by msoltyspl** [comment]
> I think we should just silence this without providing an option. Here is some JSON input that will trigger this message: {"x": null}

Even better =)

**Comment by Fyyre** [comment]
Michal, I apologize for writing this way - but I lost your contact.  Long time since last speak.  Can you please get in touch with me at fyyre @ fyyre.ru ?

Thanks =)
