### ISSUE TITLE
HAProxy - curconn

### ISSUE THREAD

**Issue by Ulrar** [influxdata/telegraf#3360]
Hi,

Just to confirm, is there no way currently to get the number of current connections in HAProxy ?
I see a "scur" field, but that's for sessions. We've just realized one of our haproxy was constantly at max conn and we apparently had no indication of that anywhere, which is a bit worrying.

Thanks

**Comment by danielnelson** [comment]
It looks that `conn_tot` should be collected if it is set:
>  79: conn_tot [.F..]: cumulative number of connections

**Comment by danielnelson** [comment]
Let me know if this is not being collected and we can debug it together.
