### ISSUE TITLE
Inputs.exec doesn't work well, command timeout

### ISSUE THREAD

**Issue by sonchu** [influxdata/telegraf#3367]
## Bug report
Inputs.exec doesn't work well with powershell script. Sometime I got command timeout. I have used this script to monitor iis pool on Nagios before and totally no error with scripting.

> E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test-demo

### Relevant telegraf.conf:
> [agent]
>   interval = "30s"
>   round_interval = true
>   metric_buffer_limit = 1000
>   flush_buffer_when_full = true
>   collection_jitter = "0s"
>   flush_interval = "30s"
>   flush_jitter = "0s"
>   debug = true
>   quiet = false
>   logfile = "C:/Program Files/Telegraf/telegraf.log"
>   hostname = "demo-test"
> [[inputs.exec]]
>   commands = ["powershell E:/Setup/custom_scripts/iis.ps1 test-demo","powershell E:/Setup/custom_scripts/iis.ps1 test1"]
>   timeout = "15s"
>   data_format = "influx"

### System info:
Telegraf version 1.4.2, Windows Server 2012 R2 64 bit

### Steps to reproduce:

1. Set telegraf run as server on Windows Server 2012
2. Config inputs.exec to run powershell script with 15s timeout
3. Let it run a while, sometime it throws command timeout

### Expected behavior:
Run normally without command timeout
### Actual behavior:
Sometime command timeout 

> 2017-10-20T02:09:30Z D! Output [influxdb] buffer fullness: 619 / 1000 metrics. 
> 2017-10-20T02:09:30Z D! Output [influxdb] wrote batch of 619 metrics in 8.9936ms
> 2017-10-20T02:09:45Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test-demo'
> 2017-10-20T02:09:45Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test1'

### Additional info:
Here is my powershell script:

```
# Check iis application pool resource usage
# Usage
# check_iis.ps1 pool-name
# ram unit = MB
# CPU unit = % 

param([string]$poolName)
$a = Get-Date
Add-Content 'E:\Setup\custom_scripts\script.log' "Start time:$a"
$truncpoolname = $poolName -replace "-", "";
$a = Get-Date
Add-Content 'E:\Setup\custom_scripts\script.log' "After truncate time:$a"
$poolName = $poolName -replace "-", " ";
$ret = Get-WmiObject Win32_Process -Filter "Name='w3wp.exe'" | Select-Object CommandLine, Handle | Select-String "$poolName"
$a = Get-Date
Add-Content 'E:\Setup\custom_scripts\script.log' "After get info time:$a"
if ($ret) {
    $r = $ret -split ";" -split "}"
    $tmp = $r.Item("1")
    $tmp = $tmp -split "="
    $handle = $tmp.Item("1")
    
    
    $CpuCores = (Get-WMIObject Win32_ComputerSystem).NumberOfLogicalProcessors
    $M1 = Get-WmiObject -Query "select * from Win32_PerfRawData_PerfProc_Process where IDProcess='$handle'"
    Start-Sleep -Seconds 1
    $M2 = Get-WmiObject -Query "select * from Win32_PerfRawData_PerfProc_Process where IDProcess='$handle'"
    $Load = [math]::Round((($M2.PercentProcessorTime - $M1.PercentProcessorTime)/($M2.Timestamp_Sys100NS - $M1.Timestamp_Sys100NS)) * 100,2)
    $Load = [Math]::Round($Load)
    $cpu = $Load / $CpuCores
    $cpu = [Math]::Round($cpu)
    

    $perf = Get-WmiObject -class Win32_PerfFormattedData_PerfProc_Process -filter "IDProcess=$handle" | Select-Object PercentProcessorTime, workingSetPrivate
    
    $workingSetPrivate = $perf.workingSetPrivate;
    $workingSetPrivate = [Math]::Round(($workingSetPrivate / 1mb),2);
    $workingSetPrivate = [Math]::Round($workingSetPrivate)  
  
	$time = [int](Get-Date -uformat %s)
	$output = "windows_metrics,app=iis,pool_name=$truncpoolname pool_cpu=$cpu,pool_memory=$workingSetPrivate"
	Add-Content 'E:\Setup\custom_scripts\script.log' $output
	write-host $output
	$a = Get-Date
	Add-Content 'E:\Setup\custom_scripts\script.log' "End time:$a"
	Add-Content 'E:\Setup\custom_scripts\script.log' ''
} else {
    $a = Get-Date
	Add-Content 'E:\Setup\custom_scripts\script.log' "Without ret time:$a"
	Add-Content 'E:\Setup\custom_scripts\script.log' ''
}
```

Here is the log when command timeout:

> 2017-10-20T03:16:30Z D! Output [influxdb] wrote batch of 589 metrics in 13.8448ms
> 2017-10-20T03:17:00Z D! Output [influxdb] buffer fullness: 589 / 1000 metrics. 
> 2017-10-20T03:17:00Z D! Output [influxdb] wrote batch of 589 metrics in 7.9958ms
> 2017-10-20T03:17:30Z D! Output [influxdb] buffer fullness: 622 / 1000 metrics. 
> 2017-10-20T03:17:30Z D! Output [influxdb] wrote batch of 622 metrics in 9.0049ms
> 2017-10-20T03:17:45Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test-demo'
> 2017-10-20T03:17:45Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test1'
> 2017-10-20T03:18:00Z D! Output [influxdb] buffer fullness: 642 / 1000 metrics. 
> 2017-10-20T03:18:00Z D! Output [influxdb] wrote batch of 642 metrics in 8.0455ms
> 2017-10-20T03:18:15Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test-demo'
> 2017-10-20T03:18:15Z E! Error in plugin [inputs.exec]: exec: Command timed out. for command 'powershell E:/Setup/custom_scripts/iis.ps1 test1'
> 2017-10-20T03:18:30Z D! Output [influxdb] buffer fullness: 582 / 1000 metrics. 
> 2017-10-20T03:18:30Z D! Output [influxdb] wrote batch of 582 metrics in 11.5442ms
> 2017-10-20T03:19:00Z D! Output [influxdb] buffer fullness: 677 / 1000 metrics. 
> 2017-10-20T03:19:00Z D! Output [influxdb] wrote batch of 677 metrics in 7.9907ms
> 2017-10-20T03:19:30Z D! Output [influxdb] buffer fullness: 677 / 1000 metrics. 

Please advise.

Thanks in advance.

**Comment by danielnelson** [comment]
I don't understand, isn't the command just not completing within the 15s timeout?

**Comment by sonchu** [comment]
Hi Danielnelson,

I don't think it is script problem because i run it normally and it always return the result within 3 seconds. So I tried to run telegraf in debug mode to see if I can get any more useful information but not much.

That why i think maybe it is telegraf issue because sometime the script timed out. I have tried to log script action to see what happen when script run and i noticed that for example i have 3 lines in script. And i echo time on each line as you can see in my script. But the log show that sometime it just run 1 line then the script is broken. Like telegraf run script and immediately stop script from running.

That why i would like to ask team for this issue and to see if there is any ways i can get more info when telegraf calls my custom script.

Please advise. 

Thanks in advanced.

**Comment by danielnelson** [comment]
It might be best to test with a very simple script that pauses for 5 seconds and then exits, just to see if the error is still reported.

**Comment by sonchu** [comment]
Ok, i will try with your advise and report back to you today. 

Thanks a lot.

**Comment by sonchu** [comment]
I am really sorry for wrong report. It must be powershell core issue which has timeout error when executing.

Thanks a lot for your support.
