### ISSUE TITLE
Telegraf not processing multiple conf files in output directory.

### ISSUE THREAD

**Issue by vinshas1** [influxdata/telegraf#3368]
I have 1 base config file and 3 role based config files copied to output-directory.

Basically I need to set for example Role = "SQL", "IIS" in the Global tags. Some servers in my environment has multiple roles so I have to measure the metrics based on its role. As I can not use a tag with multiple values such as Role = "SQL", "IIS" so I have created multiple conf files to set this. So please advise me if there is any alternate solution to it. I found we can use telegraf.service but not sure how to use it and if that solution works.

Telegraf Version: v1.3.0.
Operating System: Windows Server 2008 R2 Enterprise

## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
If I'm understanding correctly you would like to have a tag with multiple values and metrics are outputted with each tag value.

Then if a metric is created like:
```
foo,host=a value=42
```
The output would be multiple points:
```
foo,host=a,role=SQL value=42
foo,host=a,role=IIS value=42
```

If this is right, I can think of 2 ways to do this:
- Run multiple Telegraf instances with different config files, each config file uses a different value in the global tags. (this is what it sounds like you are doing now).
- Run a single Telegraf but list every input multiple times, on each input you would set the tag to a different value using the [tags input option]( https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-configuration).

Both of these options will result in the collection work being done multiple times.  Maybe you will be better off just coming up with a single name for the role group and using it?

**Comment by vinshas1** [comment]
Thanks for your quick response!! You understood it right.

I am OK with both options. Could you please explain more with an example how can I implement this.

-  How to run multiple instances with different config files.

- How to use tags options in input plugins.

Thanks,
Vinay.

**Comment by danielnelson** [comment]
To run multiple instances with different configs, just create a config for each role and specify which config with the `--config` flag.

If you want to run a single telegraf, [here is an example or adding tags to an input](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags).

And any input can be specified more than once with different settings:
```toml
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  [inputs.cpu.tags]
    role = "IIS"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  [inputs.cpu.tags]
    role = "SQL"
```

**Comment by vinshas1** [comment]
That's wonderful!! Thank you so much for helping me with the clear examples.

I really appreciate your support. You are the best!!

Thanks,
Vinay.

**Comment by vinshas1** [comment]
- To run multiple instances with different configs, just create a config for each role and specify which config with the --config flag.
I didn't quite get this statement.  I have 2 roles so I have created 2 config files and I want to use these 2 config files at the same time as I need the data from both roles at the same time.

Can you brief me with an example. sorry for bothering!!

**Comment by danielnelson** [comment]
In the multiple instance solution using global_tags you would simply be running Telegraf twice, one copy with each config file.  The config files would be independent.

**Comment by vinshas1** [comment]
unfortunately that didn’t work. The role is getting overwritten and finally processing just one role.

**Comment by danielnelson** [comment]
Any chance you can add your config files?
