### ISSUE TITLE
[bug] inconsistent os hostname

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#3370]
### System info:

[Include Telegraf version, operating system name, and other relevant details]
telegraf: 1.1
centos 7
google cloud and AWS

suppose in `etc/hosts` we have:
`1.2.3.4 ip-1-2-3-4.c.testing.internal ip-1-2-3-4`

sometimes the tag `hostname` is `ip-1-2-3-4` and sometimes it is `ip-1-2-3-4.c.testing.internal`

**Comment by danielnelson** [comment]
Are you referring to the `host` tag?  This tag does not use the `/etc/hosts` file at all, under the hood it is read from `/proc/sys/kernel/hostname`.  I believe on Centos you can set this by modifying `/etc/sysconfig/network`.
