### ISSUE TITLE
ability to re-write tags as fields

### ISSUE THREAD

**Issue by lqueryvg** [influxdata/telegraf#3372]
### System info:

Telegraf v1.3.4
Ubuntu 16.04

## Feature Request

Provide a way to re-write tags as fields.

Example line output (I've added spaces and newlines for readability):

```
docker_container_cpu,
container_version=3.0,
io.kubernetes.pod.terminationGracePeriod=30,
io.kubernetes.container.hash=d8dbe16c,
io.kubernetes.pod.namespace=default,
env=test,
container_image=gcr.io/google_containers/pause-amd64,
io.kubernetes.container.name=customer,
engine_host=kube-nodehost-78888485,
container_name=k8s_POD.d8dbe16c_customer-2889827281-c5hmv_default_9aa582d0-b279-11e7-b6c4-000d3a283041_e3091511,
io.kubernetes.container.restartCount=0,
io.kubernetes.pod.uid=9aa582d0-b279-11e7-b6c4-000d3a283041,
host=kube-nodehost-78888485,
io.kubernetes.pod.name=customer-2889827281-c5hmv,
cpu=cpu1 

usage_total=4536344i,
container_id="1faaef7d3afbd86f22af227f0ad11c088f743406e5240910a20a775c139e9d5b" 

1508577843000000000
```

In the above, everything except `usage_total` and `container_id` is a tag. Many of these tags should really be fields because:
- they vary so much that it makes no sense to index them
- the indexes consume a *lot* of memory on the influxdb server

For example all of the following should  be fields, not tags:

```
container_name
pod.name
io.kubernetes.container.restartCount
io.kubernetes.pod.uid
```

### Proposal:

Allow user to provide a list of tags in `telegraf.conf` which should be converted to fields.
E.g.
```
    tags_to_fields = [ "container_name", "io.kubernetes.container.restartCount", etc... ]
```

### Current behavior:

The user has no control over what is a tag and what is a field; it is dictated by the input plugin.

### Use case:
When monitoring Kubernetes, the prometheus and kubernetes input plugins can create a lot of tags depending on the use case, for example if you configure your pods via deployments, the pod name will be different every time the pod gets re-deployed. Hence the need to give the administrator the ability to decide what should be a tag or field.

**Comment by danielnelson** [comment]
I would like to support this, perhaps doing it as a processor plugin.

I think in your specific case though you may just want to consider excluding these tags.  I added a section to the docker readme about excluding [kubernetes labels]( https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker#kubernetes-labels) in the docker input.  On other plugins you may want to use the `tagexclude` option.

**Comment by lqueryvg** [comment]
Hi @danielnelson, thanks for your support.

FYI, I've already taken the approach of excluding certain tags, but in doing so I'm aware that I am throwing away some potentially useful information, for example `io.kubernetes.container.restartCount` can be a very useful metric. Hence this feature request.

**Comment by krisskross** [comment]
This would be awesome. Almost all elasticsearch input fields would be way easier to manage as tags with Grafana and OpenTSDB.
