### ISSUE TITLE
Make the proxy url for the inputs.http_response plugin configurable

### ISSUE THREAD

**Issue by winem** [influxdata/telegraf#3374]
## Feature Request
The plugin supports a http(s) proxy since #3302 

Now, it would be great if the proxy url is configurable. This is useful to test a connection through a specific proxy without having any impact to user or customer traffic.

### Proposal:
Add a config parameter like proxy_url.

### Current behavior:
Only the proxy set in the environment variables is used. It's not possible to set another proxy. 

### Desired behavior:
Set a specific proxy for the HTTP health checks. The HTTP proxy gathered from the environment variables should only be used if there is no proxy configured in the configuration file. 

### Use case: [Why is this important (helps with prioritizing requests)]
This would be really helpful and is important for providers of web proxies (as part of their firewall, security solution, marketing, etc...) who want to test a connection through a specific web proxy to check the service with a request similar to the customer traffic. 

Best regards,
Marcel

**Comment by winem** [comment]
We're working on a fix here and I'm currently in the testing phase.

**Comment by cpoule23** [comment]
Hello,

Could you provide us an update for this feature request please ?

If it's available, could you explain me how to configure it ?

Thanks in advance.

**Comment by winem** [comment]
Sorry, other, more pressing projects came up. I will test it tonight.

**Comment by winem** [comment]
@cpoule23 The configuration file will explain it. But, it's pretty simple and will probably look like this: 
`  ## Set proxy (telegraf uses the system wide proxy settings if proxy is not set)
  # proxy = "http://localhost:8888"
`

**Comment by cpoule23** [comment]
Hello winem,

Thanks a lot for your quick answers.

I have to monitor internal and public urls so i need too to set a no_proxy=x.x.x.x  configuration.

I suppose its already included in your dev, i just want to be sure of it :)

**Comment by cpoule23** [comment]
Hello Winem,

Do you have some news please ?

Cyril

**Comment by danielnelson** [comment]
The change that added proxy support caused this issue, so I will make sure a workaround is in the next patch release.

**Comment by winem** [comment]
@danielnelson I didn't know that it was already possible to configure a proxy in the telegraf configuration file. We have a solution that works for pure http traffic but it fails if we get a redirect to https. I'm investigating still investigating this.

Let me know how to proceed here. If you support a configurable proxy there is no need to proceed on this topic.

**Comment by winem** [comment]
The issue was on our proxy. I will wait for feedback from @danielnelson and create a merge request if this feature is still useful.

**Comment by danielnelson** [comment]
@winem It isn't currently possible to configure the proxy from the config file, only using environment variables.  I feel like #3302 was a change of behavior that turned out to be a problem for some, so we just need to add options that will override the environment variables.

**Comment by winem** [comment]
Ah ok, afaik #3302 is not an issue. I will create a merge request for a version that supports the proxy from the config file. 
Looking forward for your review.
