### ISSUE TITLE
How to config inputs.kubernetes.url for kubelet when running telegraf as Daemonset

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#3378]
As the title.
It is clear that `url = "http://0.0.0.0:10255"` works in bare-metal.
If I do not want to give the host network access to the container. How do I config the kubelet url?

The example at https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kubernetes does not work. The yaml is even not deploy-able because logger-redis-creds is not defined.

**Comment by danielnelson** [comment]
Regarding the kubelet url, I would try asking for advice at the [InfluxData Community](https://community.influxdata.com) site.

On the example yaml, the logger-redis-creds container doesn't seem required to me, does it work when we just remove it?
