### ISSUE TITLE
Logparser: github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc4203de980)

### ISSUE THREAD

**Issue by zoujd-github** [influxdata/telegraf#3380]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:
[[inputs.logparser]]
  files = ["/oracle/admin/kplwbak/bdump/alert_kplwbak.log"]
  [inputs.logparser.grok]
    measurement = "ora_log"
    patterns = ['ORA-%{INT:value:int}(:)?\s*%{GREEDYDATA:errinfo:tag}']

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Telegraf v1.4.0 
2. Red Hat 5.7

### Expected behavior:
telegraf  Start normal 
### Actual behavior:
telegraf  can't Start normal 

### Additional info:

[root@tdb bin]# ./telegraf -config /etc/telegraf/telegraf.conf 
2017/10/24 15:52:08 FATAL -- failed to create Watcher
goroutine 55 [running]:
runtime/debug.Stack(0xc4202907b0, 0x21, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/influxdata/tail/util.Fatal(0x14b3c20, 0x18, 0x0, 0x0, 0x0)
        /home/gciadm/workspace/src/github.com/influxdata/tail/util/util.go:22 +0xc7
github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc4203bc240)
        /home/gciadm/workspace/src/github.com/influxdata/tail/watch/inotify_tracker.go:219 +0x4fb
created by github.com/influxdata/tail/watch.glob..func1
        /home/gciadm/workspace/src/github.com/influxdata/tail/watch/inotify_tracker.go:54 +0x218

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
@zoujd-github Thanks for the bug report, we already have an issue open tracking this bug https://github.com/influxdata/telegraf/issues/2805
