### ISSUE TITLE
support swing door data compression plugin

### ISSUE THREAD

**Issue by baoyicai** [influxdata/telegraf#3388]
Hi,
I'm wondering if telegraf can support more data compression plugin, the one algorithm I'm particularly interested is the swing door algorithm, it is implemented by OSIsoft PI system, in their interface node, which is very similar to telegraf ( the interface implements data exception algorithm) and the its core database (implements data compression algorithm)

the two algorithms can greatly reduce the data size without loosing too much of its details, and it's configurable so that users can choose how detailed they want to data to be. 

See link below
https://livelibrary.osisoft.com/LiveLibrary/content/en/server-v5/GUID-3BEE22F8-D525-44C1-85DF-41443553E233

**Comment by danielnelson** [comment]
This is an interesting idea, something like this could be implemented as a processor.  One thing to note is that it seems that this could cause aggregation issues.

**Comment by danielnelson** [comment]
To answer you question though, Telegraf currently has no support for this style of compression algorithm.

**Comment by baoyicai** [comment]
Thanks for replying. I believe it will be a great feature for future development. It aims to reduce data size, which is the same as aggregation, but it keeps the details like the data spikes, which is important for analysis.
