### ISSUE TITLE
Bond Interface monitoring

### ISSUE THREAD

**Issue by ildarsv** [influxdata/telegraf#3390]
## Feature Request
Bond interface status monitoring
### Proposal:

There is no way to monitor bond interfaces status in the telegraf.
I'm starting develop the Bond input plugin. It will gather bond interfaces status from `/proc/net/bonding/*`.
Maybe somebody has an opinion regarding this approach?
### Current behavior:
There are no bond interface status metrics.
### Desired behavior:
To have some bond interface metrics.

**Comment by danielnelson** [comment]
What bond modes are you interested in?  I have only ever used active-backup, in which case it could be nice to monitor which interfaces are up and how many times they have failed.

**Comment by svetlovildar** [comment]
I am interested in active-backup and balance-rr. But anyway, I guess slave status and count of failures are good to monitor for every mode.

**Comment by svetlovildar** [comment]
#3424

**Comment by ildarsv** [comment]
Hello @danielnelson ! I've prepared pull request for this plugin, could you please take a look at this?
