### ISSUE TITLE
Building telegraf manipulates other repos on $GOPATH

### ISSUE THREAD

**Issue by brianm** [influxdata/telegraf#3394]
## Bug report

Building telegraf via the included `Makefile` uses [gdm](https://github.com/sparrc/gdm) to manage dependencies. Unfortunately, `gdm` behaves poorly in regards to the common practice of using a singular `GOPATH`. A well behaved build will not manipulate things outside of the project being worked on.

### Relevant telegraf.conf:

n/a

### System info:

n/a

### Steps to reproduce:

1. `make`

### Expected behavior:

Elements outside the checked `telegraf/...` directory are not changed by the build.

### Actual behavior:

Many things outside the checkoued `telegraf/...` directory are manipulated.

### Additional info:

Go has introduced the `vendor/` directory behavior and dependency metadata (Gopkg.toml) to olve this exact problem, and the [dep](https://github.com/golang/dep) tool to manage these. 

### Proposal:

Switch to using `dep` to manage dependencies.

**Comment by danielnelson** [comment]
We may do this in the future, but not until dep is a little more mature.  In the meantime you can use the `make telegraf` target to skip running gdm.

**Comment by goller** [comment]
Hi @brianm I made a PR to convert to dep here:  https://github.com/influxdata/telegraf/pull/3564

Would you have time to look at it and give feedback?

**Comment by james-lawrence** [comment]
as an aside, those of us who run gnome on linux get this wonderful error:
```
make
make deps
make[1]: Entering directory '/shared/james-lawrence/development/telegraf/src/github.com/influxdata/telegraf'
go get -u github.com/golang/lint/golint
go get github.com/sparrc/gdm
gdm restore
Only the root user can run GDM
```
