### ISSUE TITLE
Can't run --test non-interactively

### ISSUE THREAD

**Issue by absolutejam** [influxdata/telegraf#3395]
## Bug report

Running `'C:\\opt\\telegraf\\telegraf.exe --config C:\\opt\\telegraf\\telegraf.conf --config-directory C:\\opt\\telegraf\\conf.d --test` either within Powershell remoting or viia. SaltStack provides the following error: `2017/10/26 22:23:02 E! The service process could not connect to the service controller.` Running other flags, eg.  `--version` works.

### Relevant telegraf.conf:

Number of win_perf_counters

### System info:

Telegraf v1.4.1 (git: release-1.4 2de7aa23d7d3c3bcf639d417129ab7c17d83399b)
Windows

### Expected behavior:

Config is tested, printing to stdout.

### Actual behavior:

Error: `Telegraf v1.4.1 (git: release-1.4 2de7aa23d7d3c3bcf639d417129ab7c17d83399b)`

### Use case: [Why is this important (helps with prioritizing requests)]

Auto-validation with config-management.

**Comment by danielnelson** [comment]
I wonder if this would be fixed by https://github.com/influxdata/telegraf/pull/2754

**Comment by danielnelson** [comment]
@absolutejam I think this will be fixed in 1.6, can you retest with a nightly build: https://github.com/influxdata/telegraf#nightly-builds

**Comment by mahessub** [comment]
hi,
i'm seeing this issue on Windows Telegraf version 1.9.1.  
"C:\\Program Files\\Telegraf\\telegraf.exe --test" returns
"2018/12/17 00:32:39 E! The service process could not connect to the service controller."
while
"C:\\Program Files\\Telegraf\\telegraf.exe --version" 
works fine. 
Can you kindly let me know if this will be fixed?
Thank you!

**Comment by danielnelson** [comment]
@mahessub Try adding the `--console` flag: `telegraf.exe --console --test`.

**Comment by mahessub** [comment]
@danielnelson  works fine adding "--console" flag. Thanks a lot!

**Comment by Hipska** [comment]
@absolutejam have a look at https://github.com/influxdata/telegraf/pull/15732 where there is now an actual config check command..
