### ISSUE TITLE
Not getting data for rabbitmq_queue

### ISSUE THREAD

**Issue by santakd** [influxdata/telegraf#3403]
## Directions
When configured telegraf using the config file provided, we are not getting data for rabbitmq_queue
Data does shows up for rabbitmq_overview and rabbitmq_node

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf ver1.4
### Steps to reproduce:

1. Configured telegraf on three nodes of RabbitMQ 3.6.4
2. Not getting data for rabbitmq_queue in InfluxDB

### Expected behavior:
Expected data for rabbitmq_queue
### Actual behavior:
Not getting data for rabbitmq_queue 
Data shows up in InfluxDB for rabbitmq_overview and rabbitmq_node
### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by santakd** [comment]
Telegraf.conf
[[inputs.rabbitmq]]
  ## Management Plugin url. (default: http://localhost:15672)
  url = "http://localhost:15672"
  ## Tag added to rabbitmq_overview series; deprecated: use tags
  name = "PEG-RABBITMQ"
  ## Credentials
  username = "user"
  password = "xxxx"

  ## Optional SSL Config
  # ssl_ca = "/etc/telegraf/ca.pem"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false

  ## Optional request timeouts
  ##
  ## ResponseHeaderTimeout, if non-zero, specifies the amount of time to wait
  ## for a server's response headers after fully writing the request.
  # header_timeout = "3s"
  ##
  ## client_timeout specifies a time limit for requests made by this client.
  ## Includes connection time, any redirects, and reading the response body.
  # client_timeout = "4s"

  ## A list of nodes to gather as the rabbitmq_node measurement. If not
  ## specified, metrics for all nodes are gathered.
  # nodes = ["rabbit@node1", "rabbit@node2"]

  ## A list of queues to gather as the rabbitmq_queue measurement. If not
  ## specified, metrics for all queues are gathered.
  # queues = ["telegraf"]

**Comment by danielnelson** [comment]
Can you check the queues that rabbitmq reports:
```
curl -u user:xxxx http://localhost:15672/api/queues
```

**Comment by santakd** [comment]
Hi,
 Though there are queues on this windows server, it is just reporting this
>curl -u user:xxxx http://localhost:15672/api/queues
[]
>

The user has monitoring level of access and has access to the root and all the vhosts on the server

**Comment by danielnelson** [comment]
If you haven't already, take a look at these:
```
rabbitmqadmin list queues
rabbitmqadmin list permissions
```

You should also be able to browser to http://localhost:15672 and look around in the gui.

**Comment by santakd** [comment]
Hello,
 Yes, I did check in the gui and saw the queues are there
 Question: Do I have to  change anything in the config file?

Thanks
Santak

**Comment by santakd** [comment]
If I query on channels, connections and exchanges, I do get the data

- [ ] curl -u user:xxxx http://localhost:15672/api/channels
- [ ] curl -u user:xxxx http://localhost:15672/api/exchanges
- [ ] curl -u user:xxxx http://localhost:15672/api/connections

Not getting anything for queues

**Comment by santakd** [comment]
I got the queue information
Had to add the user to each of the vHosts and not just the root
Once I added the user to each of the vHosts, I started seeing information for queues
Please mark this as resolved

Thanks

**Comment by santakd** [comment]
- [ ] curl -u user:xxxx http://localhost:15672/api/channels
- [ ] curl -u user:xxxx http://localhost:15672/api/exchanges
- [ ] curl -u user:xxxx http://localhost:15672/api/connections
- [ ] curl -u user:xxxx http://localhost:15672/api/queues

**Comment by danielnelson** [comment]
Glad you got it working and thanks for the update.

**Comment by botzill** [comment]
@santakd can you explain in more details how you did that ? I have an admin user but seems to not see any queue info. Thx.

**Comment by santakd** [comment]
Hello,
 I had setup a monitoring user with access to the root
 This got me the overview\node information
 Had to add the user to each of the vHosts and not just the root
 Once I added the user to each of the vhost, I started getting information
for the queues

Thanks
Santak


 Santak Das, PMP, CSM

**Comment by botzill** [comment]
Thx @santakd I deleted my question because I found the issue :). The problem in my case what that I needed setup extra privileges for admin user so. I was using ansible for this and this can be achieved easily via:

```
- rabbitmq_user:
    user: admin
    password: admin
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: /vhost1
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
``` 

This solved my issues and now user ``admin`` does have access to all queues. 

Thx!
