### ISSUE TITLE
Postgresql output plugin (for using with timescaledb)

### ISSUE THREAD

**Issue by leiserfg** [influxdata/telegraf#3408]

**Comment by hlihhovac** [comment]
+1

**Comment by svenklemm** [comment]
I've written an output plugin for postgresql. Let me know if you need any other features.

PR #3428

**Comment by leiserfg** [comment]
It's, cool!. Can you add a more flexible way of creating the tables? For example: when creating the tables for using with timescaledb, after the table creation, but before the first insertion, you need to execute a command that create the table partition. By example:

```sql
CREATE TABLE conditions (
  time        TIMESTAMPTZ       NOT NULL,
  location    TEXT              NOT NULL,
  temperature DOUBLE PRECISION  NULL,
  humidity    DOUBLE PRECISION  NULL
);
SELECT create_hypertable('conditions', 'time');
```   
Another use case: using pg 10 and want to use a automatic partitioned table or citusdb with an sharded table.

I know that I can create the tables manually, but if I need a lot of metrics then it will imply a lot of repetitive sql writing.

**Comment by leiserfg** [comment]
Maybe a template parameter for table creation can solve this.

**Comment by svenklemm** [comment]
I guess a template is most flexible as a post_create_hook wouldnt help much with pg10 partitioning.

**Comment by danielnelson** [comment]
I like the template idea, and we won't want to add an output which is not generally usable in many use cases.  If you design a template configuration please post it here for comments.

**Comment by svenklemm** [comment]
I was thinking about having the following placeholders:
TABLE - tablename quoted as identifier
COLUMNS - comma separated list of columns with datatype
PK_COLUMNS - comma separated list of primary key columns (time+ all tags)
TABLENAME - tablename quoted as literal to use in function calls (required for timescale)

The template syntax is just a suggestion but curly braces shouldnt conflict with any SQL.

### Example Templates

```sql
-- Default Value
CREATE TABLE {TABLE}({COLUMNS},PRIMARY KEY({PK_COLUMNS}));

-- PostgreSQL 10 Partitioning by year and month
CREATE TABLE {TABLE}({COLUMNS}) PARTITION BY RANGE (EXTRACT(YEAR FROM time),EXTRACT(MONTH FROM time));

-- Timescale
CREATE TABLE {TABLE}({COLUMNS});
SELECT create_hypertable({TABLENAME}, 'time');
```

**Comment by danielnelson** [comment]
Would a user need to design tables for every input?

**Comment by leiserfg** [comment]
Awesome!

**Comment by svenklemm** [comment]
The metric name is used as table name so every input plugin gets its own table.

**Comment by danielnelson** [comment]
Would the user need to specify all the columns in order to create the table?

**Comment by svenklemm** [comment]
No the user wouldnt specify the columns, he would use the {COLUMNS} placeholder where he wants the columns to be in the statement. The plugin would replace {COLUMNS} with the actual columns used in the measurement.

**Comment by danielnelson** [comment]
What if the fields on the measurement are dynamic and new fields are added after the table is created?

**Comment by leiserfg** [comment]
I was reading the adaptor for prometheus from the same guys of timescaledb and there they use jsonb for the metrics. That way the metrics can be added dynamically.

**Comment by svenklemm** [comment]
I was thinking about having an option for jsonb tags and values, but otherwise new fields would have to result in an alter table statement and wouldnt use the template.

**Comment by danielnelson** [comment]
While some inputs create a static set of fields, quite a few of them create fields dynamically.

I would imagine the alter table design would be tricky to get right, we would need to load the current table schema on startup in order to know when to alter, and when you factor in many telegraf agents it gets harder.

You might also be interested in looking at the CrateDB output we recently added, it is almost compatible with postgres but has some differences.  https://github.com/influxdata/telegraf/pull/3210

**Comment by svenklemm** [comment]
Ok havnt used any plugins with dynamic fields so i thought all plugins would handle dynamic stuff with tags. Using jsonb fields for tags and values would solve the dynamic field problem. I've seen the cratedb plugin it uses the postgres protocol but has different datatypes from what i've seen. Using jsonb probably matches the cratedb types most closely.

**Comment by leiserfg** [comment]
I think that using jsonb for metrics is better, in the worst case it can be configurable too (dynamicFields: bool [true as default])

**Comment by svenklemm** [comment]
I have added support for jsonb tags and jsonb fields and made using jsonb the default.

**Comment by leiserfg** [comment]
hooray! Merge it!

**Comment by fouts-bnet** [comment]
Can someone please post a schema needed to get this up and running?

**Comment by srclosson** [comment]
I've made my own stab at this one as well, combining the two with some optimizations. The plugin tries to combine items with the same timestamp into the same table, but also asks that the table be created first. This is still a work in progress, that I don't know that I'll continue with because it served my purposes to find out timescale didn't have the performance that influxdb did. Comments are welcome.

https://github.com/srclosson/telegraf/tree/timescale/plugins/outputs

**Comment by leogaggl** [comment]
Any updates on this? Will the Postgres output plugin be included in the 1.7 release? Any idea on availability?

**Comment by mmariani** [comment]
I am currently using the version from https://github.com/svenklemm/telegraf/tree/postgres which has been recently updated.

**Comment by tscruggs** [comment]
@svenklemm Have you seen any issues with Telegraf storing the fields column as jsonb? Using your latest update here: https://github.com/svenklemm/telegraf/tree/postgres, I have a working configuration with metrics being output in individual columns successfully with jsonb = false. When enabled, the fields column is correctly initialized as jsonb, but all rows for fields and tags are null, only time is populated.

**Comment by rudigerlove** [comment]
Hi,
Does telegraf still stupport output to TimescaleDB?
What are your views on using Timescale instead of Influx pour certain data which needs "sql" like queries for data that is going to be a mix of relational and time series.
thx

**Comment by elizino6** [comment]
Hi 
Does telegraf still stupport output to TimescaleDB?
Regards,
IZ
