### ISSUE TITLE
[bug]  Wrong version from last git repo version 1.2.X instead of 1.4.3 ?

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#3410]
Hi @danielnelson just now I've compiled and got an erroneous version 1.2.X, but latest seems to be https://github.com/influxdata/telegraf/releases/tag/1.4.3 rigth now

#/src/gospace/src/github.com/influxdata/telegraf$ /home/developer/src/gospace/bin/telegraf -version
Telegraf v1.2.0-rc1-628-g777b84d (git: master 777b84d)

#/src/gospace/src/github.com/influxdata/telegraf$ git rev-parse --verify HEAD
777b84d1dca12bbe066303ee27d12cf0c9bdf764

#src/gospace/src/github.com/influxdata/telegraf$ git describe --always --tags
1.2.0-rc1-628-g777b84d

**Comment by danielnelson** [comment]
Here is what I get:
```
$ make telegraf
go build -i -o telegraf -ldflags " -X main.commit=777b84d1 -X main.branch=master" ./cmd/telegraf/telegraf.go
$ ./telegraf --version
Telegraf v1.5.0~777b84d1 (git: master 777b84d1)
```

**Comment by toni-moreno** [comment]
I've got source code with go tool 
````
$ go get github.com/influxdata/telegraf
$ git describe --always --tags
1.2.0-rc1-633-g9b0af44
$ make telegraf
go build -i -o telegraf -ldflags " -X main.commit=9b0af44 -X main.branch=master" ./cmd/telegraf/telegraf.go
$ ./telegraf --version
Telegraf v1.5.0~9b0af44 (git: master 9b0af44)
````
after updated the version seems to be ok, but `git describe --always --tags` still wrong ( last Makefile tooks version from here).
