### ISSUE TITLE
Strange behavior in SNMP plugin

### ISSUE THREAD

**Issue by lfdominguez** [influxdata/telegraf#3411]
Hello, i'm using telegraf to obtain information from my internet router with SNMP plugin, but i see this strange behavior ( I have a 2mbps/2mbps of internet, so the max has to be of 256 KBytes/s, but i see in this 400 Kbytes/s)

![image](https://user-images.githubusercontent.com/5604131/32238798-291b868a-be3f-11e7-90cc-9f16a5a756da.png)

My Configuration is

[[inputs.snmp]]
  agents = [ "190.6.71.161" ]
  version = 2
  community = "public"
  name = "router_internet"
  interval = "10s"

  [[inputs.snmp.field]]
    name = "rx"
    oid = "IF-MIB::ifInOctets.1286"
    
  [[inputs.snmp.field]]
    name = "tx"
    oid = "IF-MIB::ifOutOctets.1286"
    
  [[inputs.snmp.field]]
    name = "erx"
    oid = "IF-MIB::ifInErrors.1286"
    
  [[inputs.snmp.field]]
    name = "etx"
    oid = "IF-MIB::ifOutErrors.1286"

**Comment by danielnelson** [comment]
I think the value in non_negative_derivative is probably wrong, try setting it to the collection internal (probably 10s).

**Comment by lfdominguez** [comment]
uff if i change that i get the same graph but now with Mbps
![image](https://user-images.githubusercontent.com/5604131/32245981-f10cc6d6-be53-11e7-92d5-fc4072e33a4b.png)

**Comment by danielnelson** [comment]
I guess you should go back to 1s, I think this is right because you want bytes/sec.

I think this could just be caused by variations in how long it takes to collect the data, since we can't always poll exactly 10s apart.  Does it appear better when grouped by a larger interval?

**Comment by danielnelson** [comment]
I'm happy to continue trying to help figure this out here, but you might get better results at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by lfdominguez** [comment]
umm yeap, seems that, because the router is slow to respond to SNMP requests... but i solved that (before that I used InfluxDB with Telegraf) with a ruby script that catch the "uptime" of the router on response and make the math with this, not with the time configurated. Thanks.

**Comment by lfdominguez** [comment]
thanks... @danielnelson this is the new link 
https://community.influxdata.com/t/strange-behavior-in-telegraf-snmp-plugin/2937
