### ISSUE TITLE
add /monitor in mesos input plugin "feature request" 

### ISSUE THREAD

**Issue by jcmartins** [influxdata/telegraf#3412]
Please implement /monitor metrics.

I would like to have a memory and cpu consumer per app so I need see  mesos api:

/monitor/statistics
/slave(1)/monitor/statistics

tks
Joao

**Comment by danielnelson** [comment]
Do you have a link to the documentation for these APIs?

**Comment by jcmartins** [comment]
@danielnelson sorry by delay :-(

http://mesos.apache.org/documentation/latest/endpoints/slave/monitor/statistics.json/

**Comment by jcmartins** [comment]
I did the refactor and the PR to it
https://github.com/influxdata/telegraf/pull/3494
