### ISSUE TITLE
Influxdb: Connection refused after installing SSL

### ISSUE THREAD

**Issue by JerryPierre** [influxdata/telegraf#3417]
## Bug report
I have installed the Influxdb TICK stack on the same server, and all is working well. Now, I would like to add SSL for better security. I have gotten an official CA cert and followed the steps in this link https://docs.influxdata.com/influxdb/v1.3/administration/https_setup/2

Unfortunately, after a restart I get this error when I try to access the Influxdb CLI:

[user@nfluxdb ssl]$ influx -ssl -host domain-name
Failed to connect to https://domain-name:8086: Get https://domain-name:8086/ping: dial tcp IP:8086: getsockopt: connection refused
Please check your connection settings and ensure ‘influxd’ is running.

I have checked the logs but could not find any details as to what is causing the connection issue. It would also be very helpful if the logs can provide better details.

I have submitted to the community but no response. Here is the link: https://community.influxdata.com/t/influxdb-getting-connection-refused-after-installing-ssl/2908

The overall goal is to secure the TICK stack. 

### Relevant telegraf.conf:
[http]
enabled = false
bind-address = ":8086"
auth-enabled = true
log-enabled = true
write-tracing = true
pprof-enabled = true
https-enabled = true
https-certificate = "/etc/ssl/cert.pem"
https-private-key = “”
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Centos 7.4.1708: 
Linux verson 3.10.0-693.5.2.x86_64 | gcc version 4.8.5 20150623 

Influxdb version 1.3.5
Telegraf version 1.4.2
Chonograf verion 1.3.9.0
Kapacitor verion 1.3

### Steps to reproduce:

1. install the certificates
2. modify the influxdb.conf file
3. restart the influxdb service

### Expected behavior:
influxdb uses https.
### Actual behavior:
[user@nfluxdb ssl]$ influx -ssl -host domain-name
Failed to connect to https://domain-name:8086: Get https://domain-name:8086/ping: dial tcp IP:8086: getsockopt: connection refused
Please check your connection settings and ensure ‘influxd’ is running.
### Additional info:

[Include gist of relevant config, logs, etc.]

the logs states "Failed to connect to https://domain-name:8086: Get https://domain-name:8086/ping: dial tcp IP:8086: getsockopt: connection refused"

## Feature Request

Opening a feature request kicks off a discussion.

### Desired behavior:

When ssl is configured it should start using https without connection refused.
### Use case: [Why is this important (helps with prioritizing requests)]
In my organization, all servers, applications, and platforms must be secured to reduce hacking and exposing company data to unauthorized persons.

**Comment by danielnelson** [comment]
I answered over on the community site.

**Comment by GiuseppeColosi** [comment]
danielnelson, where you  answered over on the community site ?
please attach the url

**Comment by danielnelson** [comment]
https://community.influxdata.com/t/influxdb-getting-connection-refused-after-installing-ssl/2908
