### ISSUE TITLE
Conflicting tags

### ISSUE THREAD

**Issue by rvojcik** [influxdata/telegraf#3425]
Hi Guys, 
I think this is somehing wich was the case in #662
## Bug report
I tried add tags to second SNMP Instance with different value and I get this 
```
017/11/03 16:02:22 I! Using config file: /etc/telegraf/telegraf.conf
2017/11/03 16:02:22 E! Error parsing /etc/telegraf/telegraf.d/dc_doors.conf, toml: line 26: key `sensor' is in conflict with line 19

```

### Relevant telegraf.conf:
```
[[inputs.snmp]]
  agents = [ "212.158.128.154:40160" ]
  timeout = "5s"
  retries = 3
  version = 1
  community = "public"
  name = "Doors"

  [[inputs.snmp.field]]
    name = "value"
    oid = "SNMPv2-SMI::enterprises.21796.3.3.1.1.4.1"
    conversion = "int"
    [inputs.snmp.tags]
      sensor = "door_1"

  [[inputs.snmp.field]]
    name = "value"
    oid = "SNMPv2-SMI::enterprises.21796.3.3.1.1.4.2"
    conversion = "int"
    [inputs.snmp.tags]
      sensor = "door_2"

```

### System info:

Debian Wheezy
Telegraf version 1.4.3-1

### Expected behavior:
I was expected that I will have measurement called Doors with value and different tags. 
I have many of these sensors so it must be tagged to know which sensor is which.

**Comment by phemmer** [comment]
`[[inputs.snmp.field]]` adds a field. `[inputs.snmp.tags]` has to go in an `[[inputs.snmp]]` section. You can't apply a tag to a field.
If you want to create multiple series, your options are to either set up an SNMP table (using `[[inputs.snmp.table]]`, or define multiple `[[inputs.snmp]]` sections.

**Comment by rvojcik** [comment]
Thank you, I'd love to use snmp.table but sadly it's proprietary sensors solution and I cant use it. I define it separately. Thank you.
