### ISSUE TITLE
disk-diskio and mem-swap metrics are pushed into same index

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3429]
Hello,

We have installed teletgraf rpm build by us... in our lab.
for this I followed the below procedure

Install Go
Setup your GOPATH
Run go get -d github.com/influxdata/telegraf
Run cd $GOPATH/src/github.com/influxdata/telegraf
Run make

we need to send telegraf data to elasticsearch with different indexes...like cpu metrics to cpu index and memory metrics to mem index swap metrics to swap index...
when we try to do this we are able to poll memory metrics to mem index
we are getting combined metrics for both memory and swap
in the same way we tried to send disk metrics and diskio metrics to different indexes but we are getting both metrics in the same index 
we didn't change any code for this metrics
can i know why we are getting like this and suggest me any solution....

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
