### ISSUE TITLE
ceph influxdb output no ceph_pool_stat

### ISSUE THREAD

**Issue by yoke88** [influxdata/telegraf#3431]
## Directions
using telegraf Telegraf v1.4.3 (git: release-1.4 b473b6a6596078f142a623ca38ff7030b7acec8f) to monitor ceph,but can not see the measurement with name 'ceph_pool_stat'

### Relevant telegraf.conf:
 [[inputs.ceph]]
   interval = '1m'
   ceph_user = "client.admin"
   ceph_config = "/etc/ceph/ceph.conf"
   gather_admin_socket_stats = true
   gather_cluster_stats = true
### System info:

telegraf version: Telegraf v1.4.3 (git: release-1.4 b473b6a6596078f142a623ca38ff7030b7acec8f)
ceph version: ceph version 12.2.1 (3e7492b9ada8bdc9a5cd0feafd42fbca27f9c38e) luminous (stable)

### Steps to reproduce:

1. restart telegraf
2. influxdb
``` code
> use telegraf
> show measurements
name: measurements
name
----
ceph
ceph_osdmap
ceph_pgmap
ceph_pgmap_state
ceph_pool_usage
ceph_usage
cpu
disk
diskio
kernel
mem
processes
swap
system
```

### Expected behavior:
ceph_pool_stat measurement shoud be exist and has data while enable  gather_cluster_stats = true
### Actual behavior:
ceph_pool_stat measurement not exist

**Comment by danielnelson** [comment]
See also #3387

**Comment by jiribroulik** [comment]
this pkg should fix yout pool stats  https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb

**Comment by danielnelson** [comment]
This is interesting, we haven't changed ceph since 1.4.  I'm interested to hear more reports on if the pool stats are affected in the nightly.

**Comment by glinton** [comment]
@yoke88 if you have pools in the output of `ceph osd pool stats -f json`, do you see a measurement named `ceph_pool_stats` (plural)?

**Comment by danielnelson** [comment]
Closing based on reports that this is now working.
