### ISSUE TITLE
Logparser custom timestamp gives config parse error upon telegraf startup

### ISSUE THREAD

**Issue by droidnxs** [influxdata/telegraf#3432]
**Telegraf version**: 1.4.3

I'm trying to parse MongoDB's replica log file which has a timestamp as "2017-10-24T03:37:09.086+0000". My grok expression is:
>patterns = [%{TIMESTAMP_ISO8601:time} I %{WORD:type}%{SPACE}\[conn%{NUMBER}\] %{WORD:operation} %{NOTSPACE:ns} %{WORD:subop}: \{%{GREEDYDATA:query}\} %{NUMBER:responsetime}ms]

The above expression works right as it is and parses the file without any issues. However the timestamp is the parsed time and not the actual log time and I'm trying to replace the parse time that telegraf uses with the log timestamp by adding the custom modifier:
> patterns = ["%{TIMESTAMP_ISO8601:timestamp:ts-"2017-11-03T05:46:32.114-0500"} I %{WORD:type}%{SPACE}\\[conn%{NUMBER}\\] %{WORD:operation} %{
    NOTSPACE:ns} %{WORD:subop}: \\{%{GREEDYDATA:query}\\} %{NUMBER:responsetime}ms"]

I'm not sure if I've missed something, but telegraf doesn't start and produces the error: 
> 2017/11/06 04:14:48 E! Error parsing /etc/telegraf/telegraf.conf, toml: line 205: parse error

I also tried replacing the first and last double quotes with single quotes and that gives a regex error:

> 2017-11-06T09:28:21Z E! Error parsing log line: error parsing regexp: unexpected ): `((?P<timestamp>((\d\d){1,2})-((?:0?[1-9]|1[0-2]))-((?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]))[T ]((?:2[0123]|[01]?[0-9])):?((?:[0-5][0-9]))(?::?((?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)))?((?:Z|[+-]((?:2[0123]|[01]?[0-9]))(?::?((?:[0-5][0-9])))))?) I (?P<type>\b\w+\b)(\s*)\\[conn((?:(([+-]?(?:[0-9]+(?:\.[0-9]+)?)|\.[0-9]+))))\\] (?P<operation>\b\w+\b) (?P<ns>\S+) (?P<subop>\b\w+\b): \\{(?P<query>.*)\\} (?P<responsetime>(?:(([+-]?(?:[0-9]+(?:\.[0-9]+)?)|\.[0-9]+))))ms)`
2017-11-06T09:28:21Z E! Error parsing log line: error parsing regexp: unexpected ): `((?P<timestamp>((\d\d){1,2})-((?:0?[1-9]|1[0-2]))-((?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]))[T ]((?:2[0123]|[01]?[0-9])):?((?:[0-5][0-9]))(?::?((?:(?:[0-5]?[0-9]|60)(?^C

Greatly appreciate any help!

**Comment by danielnelson** [comment]
This part `"%{TIMESTAMP_ISO8601:timestamp:ts-"2017-11-03T05:46:32.114-0500"}` must use the "reference time", which is `Mon Jan 2 15:04:05 -0700 MST 2006`, although I think it should be a match for the built-in pattern `ts-rfc3339nano`.

**Comment by droidnxs** [comment]
Neither of them work :(. I think your first suggestion is right, but it's failing due to incorrect formatting. I still get the regex error regardless. This is my updated expression:

> patterns = ["%{TIMESTAMP_ISO8601:time:ts-"2006-01-02T15:04:04.000-0700"} I %{WORD:type}%{SPACE}\\[conn%{NUMBER}\\] %{WORD:operation} %{NOTSPACE:ns} %{WORD:subop}: \\{%{GREEDYDATA:query}\\} %{NUMBER:responsetime}ms"]

Are the quotations perhaps causing this?

**Comment by danielnelson** [comment]
Yes, they would be a problem.  I would use a toml literal strings with a single quote, and then you would convert your escaped regex syntax to a single backslash: `\\[` -> `\[`.

**Comment by droidnxs** [comment]
That  worked! Thanks Daniel! :)__
