### ISSUE TITLE
ES output plugin: Allow index_name to be determined with metric's fields and tags

### ISSUE THREAD

**Issue by mping** [influxdata/telegraf#3442]
## Feature Request

Currently, elastic search output plugin allows for the index name to be evaluated against the current time (in https://github.com/influxdata/telegraf/blob/master/plugins/outputs/elasticsearch/elasticsearch.go):

`
indexName := a.GetIndexName(a.IndexName, metric.Time())
`

What I would like is to determine the index name based on the metric's fields and tags.
I don't know `go` enough to submit a PR, but it should be a matter of passing more arguments to `GetIndexName` and defining some kind of pseudo-template to reference metrics and fields that don't collide with usual timestamp formatting fields.

### Proposal:
Allow the indexName to be determined using the metric's fields and tags, via some simple syntax.

### Current behavior:
Only the timestamp is used for determining the index name

### Desired behavior:
Use the current metric's fields and tags

### Use case: [Why is this important (helps with prioritizing requests)]
Will easily allow for separating indexes according to some simple user-defined logic (eg: we can tag each metric with a index prefix). This will allow better separation of metric concerns in ES.

**Comment by danielnelson** [comment]
@lpic10 Is this something that is needed?  I'm not very familiar with elasticsearch but maybe it's possible to just create another index on the data?

**Comment by lpic10** [comment]
If I understand well the idea is to have dynamic index names.

Not sure if it makes much sense to have it defined per measurement, I think for that you can have more control (as some input plugins generate several measurements) by using measurement filtering with several elasticsearch outputs configured with different index patterns: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering. 

But I see that it can be interesting to split data in different indexes by using a particular tag, eg. "host" or "namespace" or "project", etc. So indexes could have names such as "telegraf-<tag_project>-<date>". Obviously a default value in case the tag does not exist is needed.

In elasticsearch that can help with the indexes management (eg. different retention periods, access management) but it still allows querying all data at same time (eg. by querying "telegraf-*" )

**Comment by lpic10** [comment]
For instance, the elasticsearch output plugin in fluentd allows to use the tag/field data as part of the index name: https://github.com/uken/fluent-plugin-elasticsearch#dynamic-configuration

@mping : Could you give an example of what you want to use as part of the index name, or your use case?

**Comment by lpic10** [comment]
@mping : have a look at #3470 and let me know if this works for you

**Comment by mping** [comment]
@lpic10 yeap that works for me. Thanks! 👍
