### ISSUE TITLE
inputs.exce is error,missing field value

### ISSUE THREAD

**Issue by wangmin19861205** [influxdata/telegraf#3446]
i create a shell,run and show: classtable,mytag=tag1 class=14355,timtimt=110
i config telegraf.conf,no error
but run telegraf is error:ERROR in input [inputs.exec]: Errors encountered: [ metric parsing error, reason: [missing field value], buffer: [classtable,mytag=tag1 class=,timtimt=110], index: [27]]
this name class value is a variable,
sh is :echo $(echo "classtable,mytag=tag1 class=$CLASSDATA,timtimt=110")

**Comment by danielnelson** [comment]
It looks like your environment variable is not set.  Remember that when ran as a service Telegraf will be ran as the user telegraf and will not have your current shells environment variables.  You can set environment variables for the service in `/etc/default/telegraf`.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
