### ISSUE TITLE
InfluxDB output plugin should sort tags

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/telegraf#3452]
Sending unsorted tags to InfluxDB generates additional work, including allocating a new slice for each point that is parsed and subsequently sorting the tag key / values.

Benchmarks for parsing 5000 points with 10 sorted vs unsorted tags:

```
± go test -bench=_5000 -run=- ./models
goos: darwin
goarch: amd64
pkg: github.com/influxdata/influxdb/models
BenchmarkParsePointsTagsUnsorted10_5000-8   	     100	  10185633 ns/op	  70.69 MB/s	 1921936 B/op	   10001 allocs/op
BenchmarkParsePointsTagsSorted10_5000-8     	     200	   6268681 ns/op	 114.86 MB/s	 1281920 B/op	    5001 allocs/op
```

**Comment by oplehto** [comment]
+1 
We perform some filtering and routing of the line protocol data using regexp-based rules while en route to InfluxDB. Having a guaranteed ordering of the tags would make it much simpler and less costly to create rules based on multiple tags.
