### ISSUE TITLE
Metrics are split if they have a differing ValueType

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3456]
Hello, 

We have installed telegraf rpm built by us in our lab and sending data to elasticsearch

we are sending metrics data to different indexes of elasticsearch

their in net index we are able to see different events for i.e., for one time we are able to see some part of fileds and in other event we are able to see other some events.. we are able to see all the fields at a time

we have the same problem with system and swap metrics as well

can we know why the events are posted in such way...

**Comment by danielnelson** [comment]
I'm sorry but I cannot understand your question.  The best way to describe an issue is to explain what you did, what you expected to happen, and then what actually happened.

**Comment by hemasalma** [comment]
Firstly we have installed rpm of telegram built by us..in our lab and tried to get metrics data from installed system to elastic search

In telegraf conf file we gave configuration as
 input system metrics and output plugin as elasticsearch

Then in output elasticsearch plugin we gave options in such a way that each system metric should go into separate indices i.e., CPU metrics should go to CPU index...mem metrics should go into mem index ....and so on


Now in elasticsearch we are able to see metrics of each in a separate index as an event

But when coming to swap,system,net metrics
We are able to see only some metrics come once and some metrics come some other time I.e., 
For example: for 1min span swap.in and swap.out metrics come at once and other metrics of swap come at other min but they are not coming at once


We need to get all the metrics of swap come once i.e., ina 1min span all the swap metrics should be collected and sent as a single event to elasticsearch rather than coming each one as a different events

**Comment by puckpuck** [comment]
Trying to decipher your question:

You have swap metrics coming in for multiple systems at 1 minute intervals today.  You would rather combine these metrics into a single event, aggregating across multiple systems?

**Comment by hemasalma** [comment]
Step1:  Installed  telegraf rpm  built by us in our lab and tried to get system metrics data to elastic search.
Step2: In telegraf conf file we gave configuration as input system metrics and output Easticsearch.
Then in output elasticsearch plugin we gave options in such a way that each system metric should go into separate indices i.e., CPU metrics should go to CPU index...mem metrics should go into mem index ....and so on..
[[outputs.elasticsearch]]
   urls = [ "http://X.X.X.X:9233" ] # required.
    username = "xxxxxx"
    password = "xxxxxx"
   timeout = "5s"
   enable_sniffer = false
   health_check_interval = "10s"
   index_name = "system-%Y-%m-%d" # required.
   manage_template = false
   template_name = "telegraf"
   overwrite_template = true
   namepass = ["system*"]

[[outputs.elasticsearch]]
   urls = [ "http://X.X.X.X:9233" ] # required.
    username = "xxxxxx"
    password = "xxxxx"
   timeout = "5s"
   enable_sniffer = false
   health_check_interval = "10s"
   index_name = "swap-%Y-%m-%d" # required.
   manage_template = false
   template_name = "telegraf"
   overwrite_template = true
   namepass = ["swap*"]

Step3: In Elasticsearch we are able to see metrics of CPU,Memory,Disk,swap,Syste,,Net  measurements                
in a separate index.
Expected : 
For Swap measurement we need to get each and every event with below fields
{measurement_name, free, percent_availableswap, used_perceint , used_swap, in, out, total, used}
But we are Getting :
Event 1: {measurement_name, free, percent_availableswap, used_perceint, used_swap, }
Event 2: { in, out, total, used }
We are not getting total fields in a single event.
Example:
 Swap event1 in kibana .
 
![event1](https://user-images.githubusercontent.com/27216870/32765534-e2f698b4-c930-11e7-9c2f-6c2c604260cb.png)


Swap event2 in kibana.
 
![event2](https://user-images.githubusercontent.com/27216870/32765544-f19a1cf6-c930-11e7-9e58-9af18f838a03.png)

Both the events getting different fields I need to get all fields in single event.

**Comment by danielnelson** [comment]
This is an artifact of how we must add the metric value type in two steps, which separates the metrics.  I think a fix for this would probably need to be part of a major refactoring of the internal metrics class.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/memory.go#L59-L70

**Comment by powersj** [comment]
Hi,

A lot has changed since this was filed and the pointed-to memory.go file no longer exists. I am going to go ahead and close this, but if you can re-produce using the latest Telegraf, please provide the logs and we can re-review.

Thanks!
