### ISSUE TITLE
Consume AWS metrics (EC2, ELB)

### ISSUE THREAD

**Issue by panda87** [influxdata/telegraf#346]
It will be great to add plugin to consume metrics from AWS CloudWatch, mainly the ELB and EC2 metrics.

**Comment by sparrc** [comment]
:+1:

**Comment by JulienChampseix** [comment]
:+1:

**Comment by jcmartins** [comment]
:+1:

**Comment by sparrc** [comment]
Definitely looks possible, there's this library: https://github.com/goamz/goamz that appears to provide most capabilities

**Comment by panda87** [comment]
This is correct, but you don't prefer using this library: https://github.com/aws/aws-sdk-go?
I saw that this project: https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/aws.go implemented part of metrics with the library above.
What do you think?

**Comment by sparrc** [comment]
oops, that's the one I meant to link, thanks @panda87

**Comment by harpreet-sawhney** [comment]
Any progress on this? 

I happy to take this on.

**Comment by webratz** [comment]
:+1:

**Comment by dirkaholic** [comment]
Hi, I was thinking about this as well. Thought it would be a nice idea to implement a Kinesis connector similar to this one https://github.com/awslabs/cloudwatch-logs-subscription-consumer that is built in Java and has elasticsearch + kibana as target. It would have the huge advantage that you don't have to build a consumer for all the AWS services but you just need the Kinesis stream consumer and additionally you can already filter on AWS side which Cloudwatch logs you want to forward to this Kinesis stream using these subscription filters http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/Subscriptions.html. What do you think ?

**Comment by sparrc** [comment]
Kinesis consumer would also be good 👍

**Comment by webratz** [comment]
I guess this are two different tasks then: One would be the CloudWatch metrics consumer, one would be the Kinesis consumer

**Comment by sparrc** [comment]
closed by #935

**Comment by tdi** [comment]
For all of you still interested in it. Grafana can use AWS CloudWatch as a source.
