### ISSUE TITLE
jolokia - how to get output data in specific format when using wildcards

### ISSUE THREAD

**Issue by sameer2800** [influxdata/telegraf#3461]
### Relevant telegraf.conf:
[[inputs.jolokia.metrics]]
   name = "count"
   mbean  = "kafka.streams:type=kafka-metrics-count"
   attribute = "count"
   [[inputs.jolokia.metrics]]
   name = "records_lag_max1"
   mbean= "kafka.consumer:type=consumer-fetch-manager-metrics,client-id=consumer-*-StreamThread-1-consumer"
   attribute = "records-lag-max"

### Expected behavior:
jolokia,dc=cdc,count=308,records_lag_max1=12113 

### Actual behavior:
jolokia,dc=cdc,count=308,records_lag_max1_kafka.consumer:client-id\=consumer-db0cccd9-c8fd-48c9-97ec-bbb7e0c4e3d9-StreamThread-1-consumer\,type\=consumer-fetch-manager-metrics="map[records-lag-max:12113]"

when i remove wildcards from the conf, I can see the output in expected behavior.as Kafka streams generates random id in mbeans name, i cannot give entire mbean name.  so how to achieve this while using mbeans ?

**Comment by puckpuck** [comment]
You need to use jolokia2 for this.  I don't believe it is released yet, however it is part of the master branch, so if you don't mind living on the wild side, you can grab the latest binaries and go with that.  https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2

**Comment by sameer2800** [comment]
thanks for the info. i will look into this.

**Comment by danielnelson** [comment]
@sameer2800 I'm going to close this issue, but please let us know if you have any difficulties switching to the jolokia2 plugin.
