### ISSUE TITLE
Allow logging in local timezone

### ISSUE THREAD

**Issue by bortek** [influxdata/telegraf#3462]
For some reason the timestamp in the  "/var/log/telegraf.log" is UTC instead of my local timezone

2017-11-11T09:32:04Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2017-11-11T09:33:00Z E! InfluxDB Output Error: Post http://192.168.1.200:8086/write?consistency=any&db=telegraf: dial tcp 192.168.1.200:8086: getsockopt: connection ref
used

### Relevant telegraf.conf:
 
  debug = false
  quiet = false
  logfile = "/var/log/telegraf.log"

My /etc/localtime points to the right timezone file ... 

/etc/localtime -> /usr/share/zoneinfo/Europe/Stockholm

...so everytihng looks correct but something must be missing?

### System info:

uname -a
Linux kl_backside_2 4.4.50 #1 Sun Mar 26 05:10:49 EEST 2017 armv6l GNU/Linux

telegraf -version
Telegraf v1.4.3 (git: release-1.4 b473b6a6596078f142a623ca38ff7030b7acec8f)

date command output
Sat Nov 11 12:52:25 CET 2017

**Comment by danielnelson** [comment]
Currently Telegraf always logs with UTC timestamps, but we can keep this open as a feature request to add support.

**Comment by bortek** [comment]
Allright Daniel, that's explains it cause I am running older version of telegraf on other hosts and there it logs local time.

It can be set as an option in the config file.

**Comment by danielnelson** [comment]
I don't remember having support for this, what was the option called?

**Comment by bortek** [comment]
Sorry for confusion. There never was an option, your memory is correct. I meant by option that we **should** add an option to support a local time.

**Comment by bryanyork** [comment]
Any updates on this? This confuses me everytime I load the log file.

**Comment by danielnelson** [comment]
@bryanyork Sorry not yet.

**Comment by anthosz** [comment]
:+1:

**Comment by mapsacosta** [comment]
+1

**Comment by leonnipp** [comment]
+1

**Comment by yjkim0083** [comment]
+1

**Comment by redmoses** [comment]
It would be a great feature to have. +1

**Comment by tuhl65** [comment]
yes, would be nice to have +1

**Comment by schenkm** [comment]
+1

**Comment by sunpraveen** [comment]
Yes, this is very much needed +1

**Comment by TheGoblinHero** [comment]
+1

**Comment by ye-huanhuan** [comment]
+1

**Comment by anthosz** [comment]
+1

**Comment by mirceadamian** [comment]
+1

**Comment by alexeyantropov** [comment]
+1

**Comment by Valeriyy** [comment]
+1

**Comment by MonilCereBulb** [comment]
+1

**Comment by MonilCereBulb** [comment]
Has the feature of allowing logs in local timezone been implemented in the latest Telegraf version?

**Comment by sjwang90** [comment]
We'd gladly welcome a PR for this issue. 

We had someone submit PR #8450 for `inputs.gnmi` specifically but we'd like to implement local timestamping more generally throughout telegraf as it comes up often across different plugins. Per https://github.com/influxdata/telegraf/pull/8420#issuecomment-748208980 this could be done as a processor plugin.

**Comment by lordyavin** [comment]
+1

**Comment by jegj** [comment]
+1

**Comment by Victor-D** [comment]
Also you could specify in the documentation that telegraf logs are, for now, in UTC-0. As this request is closed I will open a PR for that.
