### ISSUE TITLE
Question regarding container CPU shares 

### ISSUE THREAD

**Issue by krishnaghatti** [influxdata/telegraf#3463]
I am running telegraf agent on mesos/marathon cluster. Each of the mesos-slave nodes runs docker engine. The container is allocated with CPU shares when creating an app from marathon.  
Which of the docker or mesos input metrics gives the shares allocated to the container? 
Thanks in advance.

**Comment by jcmartins** [comment]
@krishnaghatti See it...
[](https://github.com/influxdata/telegraf/issues/3412)

**Comment by krishnaghatti** [comment]
Thank you @jcmartins . I will follow the issue.
