### ISSUE TITLE
Collect zfs zfs zpool stats for size / free / health

### ISSUE THREAD

**Issue by krishnaghatti** [influxdata/telegraf#3464]
I am using the zfs input plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/zfs) on ubuntu 16.04 system. I have enabled the zfs_pool metrics in the configuration as blow: 
`[inputs.zfs]
poolMetrics = true`
In the readme markdown I see the that the stats such as free, size etc are only available for BSD bsd based systems. 
Is there any way I can get the same for linux system?

**Comment by danielnelson** [comment]
I'm not sure if it is available, the plugin uses procfs for gathering this information and in particular the files matching `/proc/spl/kstat/zfs/*/io`.  Would you be able to send me the contents of one of these files?

**Comment by krishnaghatti** [comment]
Below is the out put: 

`# cat /proc/spl/kstat/zfs/zpool-docker/io
20 3 0x00 1 80 6110017190 1315092523939
nread    nwritten reads    writes   wtime    wlentime wupdate  rtime    rlentime rupdate  wcnt     rcnt
526387712 896350208 47749    41015    26400350452 4200895256131 1315091395635 39489525805 4200895256131 1315091396091 851      1`

There are no details of the zpool health or the size info in that output though.

**Comment by danielnelson** [comment]
Can you check if it is available in a nearby file?

**Comment by krishnaghatti** [comment]
sorry for the delay in response. not finding the data in any files. only zpool command seems to return the data. 

`# zpool list
NAME           SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zpool-docker   496G  47.2G   449G         -     7%     9%  1.00x  ONLINE  -`

**Comment by danielnelson** [comment]
Maybe we can examine the source for `zpool list` to learn how it builds this information.  Worse case we could parse the output of this command but it would be more efficient if we can gather the information directly from a file.

**Comment by krishnaghatti** [comment]
> it would be more efficient if we can gather the information directly from a file.
I agree.
I will check the command and see if it stores the data in any file.

**Comment by danielnelson** [comment]
@krishnaghatti I think this is actually the same as #2616, I'm going to close but let me know if that issue does not meet your requirements.

**Comment by krishnaghatti** [comment]
@danielnelson Thank you. Yes the requirements in the other ticket are good. I will follow up that case.
