### ISSUE TITLE
Add "sum" to basicstats aggregator

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#3467]
### Proposal:
Add `sum` metric to basicstats.

### Current behavior:
`sum` is not a computed aggregate.

### Desired behavior:
`sum` would be part of computed aggregates in conjunction with `count`, `min`, etc.

### Use case: 
Although this can be computed (mean * count) it would be easier and consistent with many other metrics platforms if this was delivered out of the box.  I would be happy to do this myself as a PR, but wanted to see if there was any reason why it wasn't done initially.

**Comment by danielnelson** [comment]
I think it is probably something we can do, so long as we also do https://github.com/influxdata/telegraf/issues/3413.  I imagine there will be interest in other simple aggregations.

@toni-moreno Do you have any thoughts on this?

**Comment by danielnelson** [comment]
Implemented in #3797 and will be in 1.6, thanks @cpacey
