### ISSUE TITLE
Field/tag after greedy measurement in Graphite template mishandled

### ISSUE THREAD

**Issue by c2nes** [influxdata/telegraf#3468]
### Relevant telegraf.conf:

```
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.socket_listener]]
  service_address = "tcp://:2003"
  data_format = "graphite"
  templates = ["foo.bar.measurement*.field"]
```

### Steps to reproduce:

1. Start telegraf with the above configuration
2. Submit a measurement: `echo "biz.bang.a.b.c.m1_rate 100 $(date +%s)" | nc 127.0.0.1 2003`
3. Observe the Influx formatted line output by telegraf.

### Expected behavior:

Either the following (my preference),

```
a.b.c,bar=bang,foo=biz,host=my-host.mydomain.local m1_rate=100 1510605760000000000
```

or (possibly what is intended),

```
a.b.c.m1_rate,bar=bang,foo=biz,host=my-host.mydomain.local value=100 1510605760000000000
```

### Actual behavior:

"b" is captured both by `field` *and* by `measurement*`,

```
a.b.c.m1_rate,bar=bang,foo=biz,host=my-host.mydomain.local b=100 1510605760000000000
```

### Additional info:

This is a result of what appears to be an erroneous use of `break` in [`(t *template) Apply`](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/graphite/parser.go#L327). Based on the code the intention seems to be that anything after a greedy template component would be ignored.

However, I think there would be some value in allowing non-greedy components after a single greedy template component. I ran into this issue while attempting to integrate a Java application using  [Dropwizard Metrics](http://metrics.dropwizard.io/3.2.3/). The Dropwizard Metrics Graphite reporter will produce a number of values for most metrics (e.g. a Dropwizard "Meter" produces one, five and fifteen minute moving average rates and a "Histogram" will produce p50, p90, p99, etc values). These values are the last component of the reported metric name so I'd like to be able to extract this as the field name while capturing the remaining prefix as the measurement name.

**Comment by danielnelson** [comment]
I like this idea, though if we do this we should try to add it to InfluxDB as well since this is where we borrowed the template language from.

As a workaround, you should be able to get your preferred format using filters, though you might need to provide one for each length you are going to encounter:
```
  templates = ["*.*.*.*.*.* foo.bar.measurement.measurement.measurement.field"]
```
