### ISSUE TITLE
Telegraf/line protocol input/output

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/telegraf#349]
Telegraf should be able to output metrics to another Telegraf, which would aggregate the metrics before sending them onto another output. This could potentially be a plugin that could simply accepts line protocol metrics generated via Telegraf's InfluxDB output.

**Comment by sparrc** [comment]
One option would be to just have a udp input listener that would accept line-protocol, and same with the output

**Comment by sparrc** [comment]
closing, essentially the same as https://github.com/influxdata/telegraf/issues/481
