### ISSUE TITLE
Telegraf agent not polling the input as per the configured interval

### ISSUE THREAD

**Issue by shansudhakar** [influxdata/telegraf#3492]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Relevant telegraf.conf:

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""

 [[outputs.file]]
   files = ["stdout", "/tmp/metrics.out"]
   data_format = "influx"

 [[outputs.kafka]]
brokers = ["measure-kafka-tgt-ttc.target.com:9092"]
required_acks = 0
topic = "metric-influx-tgt-ttc-prod-platform-engineering-mft"  
# # Stream and parse log file(s).
[[inputs.logparser]]
  files = ["/apps/mft/shared/logs/MFT_CheckNode.log"]
  from_beginning = true

  [inputs.logparser.grok]
    patterns = ["%{LastHeartBeat}"]
    measurement = "mft_lastbeat_prod"
    custom_patterns = '''
     LastHeartBeat %{TIMESTAMP_ISO8601:timestamp}\|%{WORD:node:tag}.+\|%{BASE10NUM:cstatus1:int}.* %{BASE10NUM:cstatus2:int}.* %{BASE10NUM:cstatus3:int}
'''

### System info:

telegraf]# telegraf -version
Telegraf v1.4.3 (git: release-1.4 b473b6a6596078f142a623ca38ff7030b7acec8f)

telegraf]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)

### Steps to reproduce:

1. Provide input and write the output to log/kafka topic
2. Restart the telegraf agent 

### Expected behavior:
Poll every 60s of the input log provided

### Actual behavior:
Its reading the input only when telegraf agent restarted, that too with "from_beginning = true"

### Additional info:
"from_beginning = false" not at all working to get the delta from the input log file

[Include gist of relevant config, logs, etc.]
[<script src="https://gist.github.com/shansudhakar/c74bf66797d86cc83f4103033af9ada3.js"></script>]
[<script src="https://gist.github.com/shansudhakar/e3eacb043d5c50fe656effbe54b0ac36.js"></script>]
[<script src="https://gist.github.com/shansudhakar/9b93fc90ab0aba2952c97ac7251e4bdb.js"></script>]

## Feature Request

Opening a feature request kicks off a discussion.

### Use case: [Why is this important (helps with prioritizing requests)]

Read multiple logs at a frequency and display status of infra on grafana dashboard

**Comment by shansudhakar** [comment]
@danielnelson I understand the functionality of the logparser, however the issue is agent/plugin not reading the logfile whenever its appended with new entries. It reads only with "from_beginning = true" and agent is restarted. Our requirement is to have "from_beginning = false" and read/process the appended entries into the log file input.

**Comment by danielnelson** [comment]
If logparser is not picking up new lines, but they are parsed when starting up with `from_beginning = true` then it is a bug.  We do know of one bug with change detection https://github.com/influxdata/telegraf/issues/2847, maybe this is what you are seeing?

**Comment by shansudhakar** [comment]
@danielnelson #2847 seems to be a different issue with new file not detected after refresh/rotate.

**Comment by danielnelson** [comment]
Are you able to reliably reproduce this issue?  If so can you try to create a list of the smallest number of steps to reproduce?

BTW, when 1.5 is released or with the nightlies you can also use `method = "poll"` to poll the file for changes instead of using inotify.

**Comment by shansudhakar** [comment]
which is the correct config file to use:
/etc/telegraf/telegraf.d/default_outputs.conf or /etc/telegraf/telegraf.conf?

**Comment by danielnelson** [comment]
`/etc/telegraf/telegraf.conf` is the default config, the other one must be something custom to your site.  Don't forget that all files in `/etc/telegraf/telegraf.d` are loaded by default.

**Comment by danielnelson** [comment]
Closing as I don't think there is any action to take.
