### ISSUE TITLE
MySQL plugin is gathering global variables too often

### ISSUE THREAD

**Issue by lgosselin** [influxdata/telegraf#3507]
As far as I have gathered there is no boolean `gather_xxx` for collecting MySQL global variables in the plugin (`[[inputs.mysql]]`). It simply starts gathering when you set the parameter `interval_slow` to a value.

The plugin [README.md](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql) states:
```
## Some queries we may want to run less often (such as SHOW GLOBAL VARIABLES)
interval_slow                             = "30m"
```

Expected behavior:
The global variables are collected every 30m.

Actual behavior:
The global variables are collected every 10s. (data collection interval of telegraf)

Additional information:
#3500 solves this issue for me.

**Comment by danielnelson** [comment]
fixed in #3500
