### ISSUE TITLE
Can't parse line with tags containing colon in statsd input

### ISSUE THREAD

**Issue by sagydr** [influxdata/telegraf#3508]
## Bug report
In Increment line, in **parsePacketString**, tags can't contain colon (":")
because of:
```
	// Validate splitting the line on ":"
	bits := strings.Split(line, ":")
	if len(bits) < 2 {
		logger.Errorf("Error: splitting ':', Unable to parse metric: %s\n", line)
		return nil, errors.New("Error Parsing statsd line")
	}
```

The split is done upon the entire line, and hence ` len(bits) == 3`

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
1. define an increment line with tag containing colon, e.g: `line = 'mymteric,tag_name=aaa: bbb'`
2. try to send this line to client `STATSD.client.incr(line, count=1)`
3. see the ` E! Error: splitting '|', Unable to parse metric` in the telegraf log

### Expected behavior:
split should be from the LAST colon only, so split should always return array of size 2

### Actual behavior:
line is split into array of size 3

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sagydr** [comment]
note: i wrote a fix, but i can't create a PR.
how do i push my branch?

**Comment by danielnelson** [comment]
Create a fork of this repo and push the branch to your fork, then you can open the pull request from the github webpage.

**Comment by sagydr** [comment]
opened PR:
https://github.com/influxdata/telegraf/pull/3514

**Comment by danielnelson** [comment]
Closing this issue since I don't believe is is legal to do this in the statsd protocol, and the implementation would be difficult without causing slowdowns.
