### ISSUE TITLE
inputs.smart is not enabled 

### ISSUE THREAD

**Issue by aplsms** [influxdata/telegraf#3509]
## Bug report

After adding configuration options related to inputs.smart to the config I have an error starting telegraf

### Relevant telegraf.conf:

    # Read metrics from storage devices supporting S.M.A.R.T.
    [[inputs.smart]]
      ## Optionally specify the path to the smartctl executable
      path = "/usr/bin/smartctl"
      use_sudo = true
      nocheck = "standby"
      devices = [ "/dev/sda -d sat", "/dev/sdb -d sat", "/dev/sdc -d sat", "/dev/sdd -d sat", "/dev/sde -d sat", "/dev/sdf -d sat"]

### System info:

    apl@beta:~$ telegraf --version
    Telegraf v1.4.4 (git: release-1.4 ddcb93188f3fb5393d811cdd742bfe6ec799eba9)
    apl@beta:~$ uname -a
    Linux beta 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    apl@beta:~$ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

### Steps to reproduce:

1.  `wget https://dl.influxdata.com/telegraf/releases/telegraf_1.4.4-1_amd64.deb`
2.  install package `sudo dpkg -i telegraf_1.4.4-1_amd64.deb`
3. add config for influxdb
3. run `sudo service telegraf start`

### Expected behavior:

S.M.A.R.T. metrics will be transferred to influxdb

### Actual behavior:

Telegraf failed with messages in logs:

    Nov 27 04:55:46 beta systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
    Nov 27 04:55:46 beta telegraf[8236]: 2017/11/27 04:55:46 E! Error parsing /etc/telegraf/telegraf.d/smart.conf, Undefined but requested input: smart
    Nov 27 04:55:46 beta systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
    Nov 27 04:55:46 beta systemd[1]: telegraf.service: Unit entered failed state.
    Nov 27 04:55:46 beta systemd[1]: telegraf.service: Failed with result 'exit-code'.
    Nov 27 04:55:46 beta systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
    Nov 27 04:55:46 beta systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.

**Comment by danielnelson** [comment]
This plugin will be in version 1.5 of Telegraf.
