### ISSUE TITLE
Add slab memory consumption on Linux

### ISSUE THREAD

**Issue by lpic10** [influxdata/telegraf#3515]
## Feature request

On newer linux distros, `free` returns `cache` memory as a sum of `cached` and `slab`, as explained from `man free`:
`cache    Memory used by the page cache and slabs (Cached and Slab in /proc/meminfo)`

Telegraf currently ignores `slab` memory usage. 

Current workaround is to use `vmstat` plugin data, as:
`SELECT ((mean("nr_slab_reclaimable") + mean("nr_slab_unreclaimable")) * 4096) FROM "kernel_vmstat" `

Implementation is quite simple as `slab` is retrieved already by gopsutil

**Comment by lpic10** [comment]
I think it makes more sense to add an additional field for `slab` than a sum with `cache` (as free does), to not break compatibility.

**Comment by phemmer** [comment]
See also https://github.com/influxdata/telegraf/issues/1990

**Comment by lpic10** [comment]
@phemmer my idea is not to add all data in `/proc/meminfo`, but enough to at least match what `free` provides. I agree that all that data may be useful in some scenarios, perhaps that should be a dedicated plugin.
