### ISSUE TITLE
Restart telegraf service if it is already running and upgraded via RPM

### ISSUE THREAD

**Issue by druchoo** [influxdata/telegraf#3516]
## Feature Request
If RPM package is upgraded and the telegraf service is running have postscript restart service.

### Current behavior:
Service is not restarted if already running and upgraded via RPM

### Desired behavior:
Restart service if it is _already_ running and upgraded via RPM

### Use case: [Why is this important (helps with prioritizing requests)]
According to https://fedoraproject.org/wiki/Packaging:Scriptlets#Systemd
> On upgrade, a package may only restart a service if it is running; it may not start it if it is off.

I think restarts were removed from #3015? 

This behavior is probably a matter of preference but the reasoning is if you're upgrading telegraf it is intentional and you want to use the new version. Currently a manual restart is needed if the service is already running and an upgrade is performed.

**Comment by danielnelson** [comment]
Which distro and distro version are you using?

**Comment by druchoo** [comment]
CentOS Linux release 7.2.1511 (Core) and telegraf 1.4.x

**Comment by sparr** [comment]
There is a restart with the .deb package upgrade, so this is at best an inconsistency between different packagings of the same version.

**Comment by danielnelson** [comment]
I'm okay with the rpm and deb packages behaving differently, but they should follow guidelines from debian and redhat.  One example is that in debian a service is generally started on install, while on redhat you need to manually enable it.
