### ISSUE TITLE
Telegraf AMQP Output - Persistent messages

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#3526]
### Proposal:
Please allow the option to set messages to be persistent on the amqp output plugin.

### Current behavior:
Messages are not persistent and are lost when a broker restarts

### Desired behavior:
Messages are retained on the broker until they are processed

### Use case: [Why is this important (helps with prioritizing requests)]
When batch loading large amounts of messages (logparser messages to be precise), the messages are very large and take a while to process.  On occasion, the broker will run out of memory and crash.  All messages are lost and have to be reprocessed.

**Comment by danielnelson** [comment]
I might be wrong, but I think when you create the queue you need to make it durable.  This would be done outside of Telegraf.

**Comment by hanej** [comment]
Making the queue durable just means the queue itself survives a broker restart, not the messages.  Messages need to be put on the queue with a DeliveryMode of 2 to make them persistent.  Currently 1 is the default (transient).

https://github.com/streadway/amqp/blob/master/types.go#L104-L116
