### ISSUE TITLE
Telegraf not reporting network details for FreeBSD running VMWare Tools vmx driver

### ISSUE THREAD

**Issue by kris-anderson** [influxdata/telegraf#3532]
### Relevant telegraf.conf:
```
# # Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  interfaces = ["eth0", "igb0", "vmx0"]
```

### System info:

FreeBSD 11.1 running under VMware ESXi 6.5 with openvm-tools-nox11 installed
Telegraf version 1.3.0

### Steps to reproduce:

1. Open Grafana
2. Select `net` as the measurement
3. Add a where clause where where is my FreeBSD server
4. Go back to `net` and change to something else, such as `cpu`
4. Open the measurement dropdown again and now that the host is set to my freeBSD server, net is no longer showing as an option

### Expected behavior:
I expect `net` to show and I expect to be able to see the network interface of my vmx0 virtual NIC.

### Actual behavior:
`net` doesn't show, and I am not collecting network data that I can visualize using Grafana for my freeBSD machines.

### Additional info:
This one is interesting... but I also run pfSense which is built on freeBSD, and I installed the Telegraf package which is also version 1.3.0 and it's reporting the network metrics successfully. That isn't a virtual machine though under ESXi, and it uses `igb` as the network interfaces.

Telegraf seems to be reporting all the standard details such as system, cpu, memory, disk, etc. on both my freeBSD and Virtual machines. But on my virtual machines, it doesn't appear to be collecting the network details.

**Comment by danielnelson** [comment]
Can you try with the latest Telegraf release (1.4.4)?

**Comment by kris-anderson** [comment]
I switched one of my servers to the latest repo on freeBSD (instead of the default quarterly repo) and that brought me up to 1.4.4. With the latest version, vmx network stats are now being sent to influxdb! Thank you for the suggestion @danielnelson .
