### ISSUE TITLE
Request support for NTLMv2

### ISSUE THREAD

**Issue by cdcox87** [influxdata/telegraf#3534]
## Feature Request
Request MSSQL input plugin support NTLMv2 for authentication.
### Current behavior:
Currently it appears that the plugin for gathering Microsoft SQL metrics only supports NTLMv1 and Kerberos. 
### Desired behavior:
Support NTLMv2
### Use case: [Why is this important (helps with prioritizing requests)]
More and more businesses are dropping NTLMv1 due to security vulnerabilities. Logging in via Kerberos may not always be possible and NTLMv2 would be used. This is specifically a use case for logging in using the credentials in a service account and not putting them in the configuration file.

**Comment by danielnelson** [comment]
@vlastahajek Correct me if I'm wrong, still a little fuzzy on Windows authentication methods, this is supported now by your latest patch to go-mssqldb?

**Comment by vlastahajek** [comment]
@danielnelson, my patch didn't add any new authentication method.  The issue was in wrong handshake of authentication messages, not in unsupported authentication method. 
However, If needed I can look at this as well, I saw similar requests in go-mssqldb repo.

**Comment by sspaink** [comment]
@cdcox87 are you still interested in seeing this feature implemented?
