### ISSUE TITLE
jolokia2 plugin tag_key doesn't work on a key with slash on the string

### ISSUE THREAD

**Issue by srmunhoz** [influxdata/telegraf#3535]
### Relevant telegraf.conf:

   [[inputs.jolokia2_agent.metrics]]
     name = "jboss_datasource"
     mbean  = "jboss.as:subsystem=datasources,data-source=*"
     paths = ["connectionUrl", "driverName", "userName"]
     tag_keys = ["jndiName"]

### Steps to reproduce:
1. Declare a tag_key using a MBean attribute that has slash on the string (in this case it's a JNDI string, so is something like this "java:jboss/datasources/ExampleDS")

### Expected behavior:
Create a new tag key on the measurement.

### Actual behavior:
The measurement shows only the default tag keys

### Additional info:
Using InfluxDB v1.3.5

**Comment by danielnelson** [comment]
@dylanmei Can you take a look?

**Comment by dylanmei** [comment]
I am unable to reproduce this without more information.
@srmunhoz Your example uses a pattern-match on `data-source` object property key but attempts to capture `jndiName` as a tag. Do you mean to capture `data-source` as a tag?

**Comment by srmunhoz** [comment]
Hello @dylanmei, thanks for you reply. No, I want to capture the jndiName as a tag. Something similar works on the example below:
   [[inputs.jolokia2_agent.metrics]]
     name     = "jboss_memory_pool"
     mbean    = "java.lang:name=*,type=MemoryPool"
     paths    = ["Usage", "Type"]
     tag_keys = ["name"]

I'm using a Jboss 7 so, I cannot remove the "/" from the jndi. I'm suspecting this is the problem, because as said before, the example above works very well.

**Comment by dylanmei** [comment]
@srmunhoz the only possible tags to capture are the mbean property keys. In the ‘jboss_datasource’ example that is just  ‘subsystem’ and ‘datasource’. 

Is ‘jndiName’ ia field? If so, it cannot be transformed into a tag with this input plugin.

**Comment by srmunhoz** [comment]
@dylanmei jndiName is a field. Ok, so I understand wrongly how it works. I've tested here and worked fine. Sorry about the trouble. Thank you all.
