### ISSUE TITLE
Failed to send event to OpsGenie

### ISSUE THREAD

**Issue by marsn** [influxdata/telegraf#3538]
{"code":32,"error":"DeprecatedApiException[API v1 is deprecated. Please refer https://docs.opsgenie.com/docs/dashboard/rest-api for details of the new version]"}

**Comment by danielnelson** [comment]
How are you sending to OpsGenie?

**Comment by marsn** [comment]
is it capacitor issue then? I was making alerts rules in chronograf

**Comment by marsn** [comment]
moved to https://github.com/influxdata/kapacitor/issues/1708
