### ISSUE TITLE
telegraf logparser too slow

### ISSUE THREAD

**Issue by kingluo** [influxdata/telegraf#3539]
## Bug report

I use telegraf to collect nginx logs to kafka. But it's too slow, the kafka hosts are in the same data center with the telegraf host, but it has one to two hours delay according to the log timestamp!

### Relevant telegraf.conf:

```
[agent]
  interval=3
  flush_interval=3

[[inputs.logparser]]
  name_override = "foobar"
  files = ["/var/logs/foobar.service.foobar.com-access_log"]
  from_beginning = true
  [inputs.logparser.grok]
    patterns = ["%{IP:remote_addr}\t%{USER:remote_user}\t\\[%{HTTPDATE:time_local:ts-httpd}\\]\t\"%{WORD:method} %{NOTSPACE:url}(?: HTTP/%{NUMBER:httpversion})\"\t%{NUMBER:resp_code}\t(?:%{NUMBER:resp_bytes:int}|-)\t%{QS:referrer}\t%{QS:agent}\t(?:%{IP:client_ip}|-)\t%{HOSTNAME:http_host:tag}\t%{NUMBER:request_time}\t(?:%{IP:upstream_addr}|-)\t(?:%{NUMBER:upstream_status}|-)\t(?:%{NUMBER:upstream_response_time}|-)\t(?:%{NUMBER:upstream_response_length}|-)\t(?:%{QS:mid}|-)"]

[[outputs.kafka]]
  brokers = ["kafkahost1:9092", "kafkahost2:9092", "kafkahost3:9092"]
  topic = "test"
  routing_tag = "host"
  required_acks = -1
  max_retry = 3
  ## format
  data_format = "json"
  fieldpass = [ "client_ip", "mid", "url" ]
  taginclude = [ "host" ]
  [outputs.kafka.tagpass]
    http_host = [ "foobar.service.foobar.com" ]
```

### System info:

telegraf 1.4.5, centos 6.5

**Comment by danielnelson** [comment]
Can you try setting the interval and flush_interval to "10s"?

**Comment by kingluo** [comment]
I change the interval and flush_interval to "1s" (10s is slower).

And I found I set a wrong option:

```
from_beginning = true
```

It should be `false`.

But the collection is still slow, at least 3 mins.

**Comment by danielnelson** [comment]
Please try with 10s, this will introduce more latency but may help with throughput.  3 mins is not too long, does it fall further behind the longer it runs?

**Comment by kingluo** [comment]
> Please try with 10s, this will introduce more latency but may help with throughput. 3 mins is not too long, 

I tried, but it's slower!

> does it fall further behind the longer it runs?

yes.

**Comment by danielnelson** [comment]
Can you try replacing the `kafka` output with a `file` output and check if logparser still falls behind?

**Comment by kingluo** [comment]
Of course, I tried `file` and `influx` format, but it's still slow.

**Comment by danielnelson** [comment]
How many logfile lines are generated per minute?

**Comment by agnivade** [comment]
@kingluo - It looks like you are using a custom pattern. Can you post a few examples of your log line ? I would like to give this a shot.

**Comment by jberry-suse** [comment]
Can confirm, only able to parse at max 1000 entries per second. Easy to reproduce just create/copy apache access log with 100,000 entries and watch how slow it is parsed. With even a single threaded from scratch regex parsing I can achieve at least a million entries per second.

No need for custom log format, use standard format. Based on CPU usage one core is utilized and does not seem to be running at 100% almost as if telelgraf is throttling itself.

**Comment by jberry-suse** [comment]
I ended up [writing a simple tool](https://github.com/openSUSE/openSUSE-release-tools/pull/1578) which achieves ~500,000/s per core.

**Comment by russorat** [comment]
- [ ] check this against the `tail` plugin

**Comment by voiprodrigo** [comment]
This (subpar regex performance compared to some other current languages) seems to be a known “issue” with Go (https://github.com/golang/go/issues/11646). So trying to optimize the regex as much as possible seems to be all that one can do at the moment. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielnelson** [comment]
Just did a quick test with the latest commit on master, 4b3f04c63b, but unfortunately the performance is very similar.

**Comment by agnivade** [comment]
I see. Well, then I guess optimizing the regex seems to be the way to go.

**Comment by danielnelson** [comment]
I think the best/only resolution we can provide is some additional documentation.  I'm considering this addition to the [grok documentation](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok):

#### Performance

Performance depends heavily on the regular expressions, but there are a few
techniques that can help:

- Avoid using patterns such as `%{DATA}` that will always match.
- If possible, add `^` and `$` anchors to your pattern:
  ```
  [[inputs.file]]
    grok_patterns = ["^%{COMBINED_LOG_FORMAT}$"]
  ```
