### ISSUE TITLE
Remove "/dev/" prefix from smart device name tag

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#3541]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
The new `smart` input plugin should not prefix device names with `/dev`. This is so that the device name is consistent with other measurements, such as the `diskio` measurement which outputs device names without the `/dev/` prefix.

### Current behavior:
A device such as `/dev/sda` is written as `device=/dev/sda`.

### Desired behavior:
A device such as `/dev/sda` is written as `device=sda`.

### Use case: [Why is this important (helps with prioritizing requests)]
The consistency is important so that users who wish to use features such as Grafana's template variables can do so. If a user wishes to utilize both the `smart` and `diskio` measurements on a single dashboard which utilizes template variables to select the disk, it will be difficult because of the inconsistent naming.

**Comment by danielnelson** [comment]
I wonder if diskio should instead be changed to output `/dev/sda`?  Might look better in case you want to use the `/dev/disk/by-*` paths.

**Comment by danielnelson** [comment]
Of course it would be a pain to migrate, and we still have time to change smart around before its officially released.
