### ISSUE TITLE
telegraf fails to start if its wavefront output fails to connect

### ISSUE THREAD

**Issue by dimas** [influxdata/telegraf#3545]
### Relevant telegraf.conf:
```
[[outputs.wavefront]]
  host = "localhost"
  port = 2003
  prefix = "test."
```

### System info:
```
$ uname -a
Linux ip-10-0-154-148 3.13.0-132-generic #181-Ubuntu SMP Wed Sep 13 13:25:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ telegraf --version
Telegraf v1.5.0~rc1 (git: release-1.5 ca8911fe)
```

### Steps to reproduce:

1. Just start `telegraf` with nothing listening on port 2003

### Expected behavior:

`telegraf` should be retrying connecting to 2003 till the end. (Because what if it is not the localhost? what if it is some other server and it is an unfortunate moment when server process is down / being restarted)

### Actual behavior:
`telegraf` logs
```
2017-12-06T01:14:40Z E! Failed to connect to output wavefront, retrying in 15s, error was 'Wavefront: TCP connect fail dial tcp 127.0.0.1:2003: getsockopt: connection refused' 
2017-12-06T01:14:55Z E! Wavefront: TCP connect fail dial tcp 127.0.0.1:2003: getsockopt: connection refused
```
and the service process exits.

**Comment by puckpuck** [comment]
I will alter Wavefront output to log error and return nil in case of error in connect function.  I don't see this hurting anything, as it does reconnect on each write.
