### ISSUE TITLE
partial poll of snmp

### ISSUE THREAD

**Issue by r4yfx** [influxdata/telegraf#3552]
### Relevant telegraf.conf:
Extract from the .conf file
```
[[inputs.snmp]]
  agents = [ "host:161" ]
  version = 2
  community = "public"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "physical"
    oid = "SNMPv2-SMI::enterprises.674.10892.5.5.1.20.130"

  [[inputs.snmp.field]]
    name = "temp"
    oid = "SNMPv2-SMI::enterprises.674.10892.5.4.700.20"

  [[inputs.snmp.field]]
    name = "cooling"
    oid = "SNMPv2-SMI::enterprises.674.10892.5.4.700.12"

  [[inputs.snmp.field]]
    name = "batteries"
    oid = "SNMPv2-SMI::enterprises.674.10892.5.4.600.50"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "EtherLike-MIB::dot3StatsTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
```
### System info:

Telegraf v1.4.4 (git: release-1.4 ddcb93188f3fb5393d811cdd742bfe6ec799eba9)
CentOS 7
Influxdb

### Steps to reproduce:

1. Created .conf file with the above sample configuration
2. Tested telegraf.conf file and there is no errors. 
3. restarted telegraf
4. check influxdb and it appears to show interface data, but nothing else. 

### Expected behavior:
Expecting to see snmp fields data

### Actual behavior:
Only seeing interface data

### Additional info:
Nothing showing within the logs or debug that I can see

**Comment by danielnelson** [comment]
What is the output of 
```
snmpget -v2c -c public host:161 SNMPv2-SMI::enterprises.674.10892.5.5.1.20.130
```

**Comment by r4yfx** [comment]
SNMPv2-SMI::enterprises.674.10892.5.5.1.20.130 = No Such Object available on this agent at this OID


but when I walk it;
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1.1.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1.1.3 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1.1.4 = INTEGER: 1
...
..
.

I am assuming then that the daemon does a get instead of a walk? How can I ensure that the OID is correct for the get instead of a walk?

**Comment by danielnelson** [comment]
The fields not inside a table use get, and the tables use walk or bulkwalk.  You should be able to just use one of the OIDs returned by snmpwalk, or if you want to collect all of them you would need to use a table.

**Comment by r4yfx** [comment]
Could I push on your kindness by showing me an example please, so that I know what I am doing? I would prefer to use the snmpwalk part if at all possible to pull all the data.

**Comment by danielnelson** [comment]
Honestly I'm not great with snmp, but I think it should look something like this:
```
  [[inputs.snmp.table]]
    name = "temp"
    inherit_tags = [ "hostname" ]
    index_as_tag = true
    oid = "SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1.1"
```

It's possible that the OID needs trimmed, check the output with `telegraf --test` and if it is not working also try:
- SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.1
- SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1
- SNMPv2-SMI::enterprises.674.10892.5.4.700.20

**Comment by r4yfx** [comment]
Tried this but doesn't seem to pull the info either

[[inputs.snmp]]
  agents = [ "host:161" ]
  version = 2
  community = "public"

  # Check on IDrac
  [[inputs.snmp.table]]
    name = "idrac"
    inherit_tags = [ "hostname" ]
    oid = "SNMPv2-SMI::enterprises.674.10892"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "EtherLike-MIB::dot3StatsTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

**Comment by r4yfx** [comment]
It seems though that this configuration has also broken the pull from the interfaces. until this was removed

**Comment by phemmer** [comment]
When I do a lookup on `SNMPv2-SMI::enterprises.674.10892.5.5.1.20.130` (numeric `.1.3.6.1.4.1.674.10892.5.5.1.20.130`), I find: http://oidref.com/1.3.6.1.4.1.674.10892.5.5.1.20.130 . If this is indeed the MIB your device is using, the OID you're configuring isn't the right OID for the table, as there are several tables underneath that OID. Judging from the name you tried to give the table (`physical`), I'm going to assume you're after [`physicalDiskTable` (`1.3.6.1.4.1.674.10892.5.5.1.20.130.4`)](http://oidref.com/1.3.6.1.4.1.674.10892.5.5.1.20.130.4). However even once you have the table, you still need to define some fields to use within the table (and possibly some tags as well). Lets say you want to use [`physicalDiskName`](http://oidref.com/1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.2) as your tag, and [`physicalDiskUsedSpaceInMB`](http://oidref.com/1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.17) as a field, then you would define a configuration such as:

```
[[inputs.snmp.table]]
name = "physical_disk"
inherit_tags = ["hostname"]
oid = "1.3.6.1.4.1.674.10892.5.5.1.20.130.4" # can also use `IDRAC-MIB::physicalDiskTable` or `SNMPv2-SMI::enterprises.674.10892.5.5.1.20.130.4` if you have the MIB files on your system.

[[inputs.snmp.table.field]]
name = "disk_name"
oid = "1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.2"
is_tag = true

[[inputs.snmp.table.field]]
name = "space_used"
oid = "1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.17"
```

Unfortunately SNMP tables can a bit confusing because you're flattening a 2-d structure into 1-d. So I doing some quick research on how they work will help you configure them.

**Comment by danielnelson** [comment]
@r4yfx Does this help?
