### ISSUE TITLE
inputs.httpjson plugin tag_keys is not working correctrly

### ISSUE THREAD

**Issue by m3nthal** [influxdata/telegraf#3556]
## Bug report
`tag_keys` setting doesn't seem to filter the tags and send the correct metrics.
If I `tag_keys` setting is commented out, `spring_boot_metrics_uptime` is sent. 

### Relevant telegraf.conf:
```
[[inputs.httpjson]]
  name_override = "spring_boot_metrics"
  servers = ["{{ spring_boot_metrics_url }}"]
  response_timeout = "5s"
  method = "GET"
  tag_keys = ["uptime"]
```

### System info:
Telegraf v1.5.0~7442b56 (git: master 7442b56)

### Steps to reproduce:

Requirements:
1. Have a telegraf configuration with the relevant configuration
2. Have an endpoint that returns a json with "uptime" key

### Expected behavior:
Receive `spring_boot_metrics_uptime` metric with the value when `tag_keys = ["uptime"]` is present.

### Actual behavior:
`spring_boot_metrics_uptime` is not sent when `tag_keys = ["uptime"]` is present.
`spring_boot_metrics_uptime` is sent when `tag_keys` setting is not present.

### Use case: [Why is this important (helps with prioritizing requests)]
Spring Boot Metrics endpoint returns a big JSON and not all the keys are needed to be converted to metrics. `tag_keys` should solve the problem by only processing the keys that were specified.

**Comment by danielnelson** [comment]
Can you show some example JSON?

**Comment by m3nthal** [comment]
For example:
```json
{
   "mem":331463,
   "mem.free":86267,
   "processors":1,
   "instance.uptime":35479314,
   "uptime":35525878,
   "systemload.average":0.01,
   "heap.committed":204800,
   "heap.init":204800,
   "heap.used":118463,
   "heap":204800,
   "nonheap.committed":128728,
   "nonheap.init":2496,
   "nonheap.used":126663,
   "nonheap":0,
   "threads.peak":49,
   "threads.daemon":35,
   "threads.totalStarted":56,
   "threads":49,
   "classes":14131,
   "classes.loaded":14131,
   "classes.unloaded":0,
   "gc.g1_young_generation.count":90,
   "gc.g1_young_generation.time":3245,
   "gc.g1_old_generation.count":0,
   "gc.g1_old_generation.time":0,
   "cache.banners.size":0,
   "httpsessions.max":-1,
   "httpsessions.active":0,
   "gauge.response.alive":4.0,
   "gauge.response.metrics":1.0,
   "gauge.response.version":0.0,
   "gauge.response.unmapped":16.0,
   "gauge.response.jolokia.star-star":1.0,
   "counter.status.200.metrics":1182,
   "counter.status.200.alive":7095,
   "counter.status.200.jolokia.star-star":1182,
   "counter.status.200.version":1143,
   "counter.status.401.unmapped":1
}
```

**Comment by danielnelson** [comment]
So you would like the `uptime` to be set as both a field and a tag?

**Comment by m3nthal** [comment]
From the comment to the plugin
```
## Tags to extract from top-level of JSON server response.
  # tag_keys = [
  #   "my_tag_1",
  #   "my_tag_2"
  # ]
```
it was expected that `"uptime"` will be the only key extracted from the JSON response. I don't see much sense in tagging the `spring_boot_metric_uptime` with `uptime` since the metric name and value already contain that information. The reason is to limit the amount of metrics generated from JSON by specifying the ones that should be kept in `tag_keys` and dismissing the rest.

If `tag_keys` is **not specified**, the JSON and the settings mentioned before would generate these metrics:
- spring_boot_mem
- spring_boot_mem.free
- spring_boot_processors
- instance.uptime
... and so on.
If `tag_keys = ["mem"]` is present, it would only generate `spring_boot_mem` metric given the settings.

**Comment by danielnelson** [comment]
Let me know if you still think there is a bug.

**Comment by m3nthal** [comment]
@danielnelson that is what I was looking for. Thank you.
