### ISSUE TITLE
AMQP Body Compression

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#3557]
### Proposal:
When using input plugins, like the logparser, that can put a large amount of text in the body of an AMQ message (over 300K), it can take much longer for Telegraf to pull messages from the queue or for Rabbit to send them across federated links.  It would be great if the amqp output plugin could check the size of the message body and if it's over a configurable amount, gzip the body.  The amqp_consumer input plugin would then need to auto-detect the content type and unzip as necessary.

### Current behavior:
All messages are plain text without any compression.

### Desired behavior:
Add a compression option to the amqp_consumer input plugin and amqp output plugin to allow gzip body compression over a configurable amount.

### Use case: [Why is this important (helps with prioritizing requests)]
When Telegraf is configured with the logparser plugin and from_beginning set to true, it can dump a huge amount of very large messages onto the queue.  It then takes Telegraf a long time to pull those messages off of the queue.  With several thousand 300K+ messages load balanced across 3 queues on 3 different brokers I've only been able to hit 30 msg/s with 4 Telegraf consumers.  Once the backlog of logparser messages have been processed the throughput skyrockets to 1000 msg/s.

The logparser messages clog the queues and we lose access to real time stats for other metrics.

**Comment by danielnelson** [comment]
I would prefer an option to either always gzip or never instead of switching based on size.

Perhaps it would be helpful to set your `metric_batch_size` lower on systems outputting amqp.

**Comment by hanej** [comment]
Doing an all-or-nothing approach might be more resource intensive for a lot of small messages.  Also, if the message is less than 100 bytes or so the resulting content could be larger compressed than it would be raw.

**Comment by danielnelson** [comment]
The downside of switching would be you must detect if a body is compressed or not, and I think it wouldn't be a problem to compress small bodies, they are small after all and don't take many resources.  Additionally we will need to serialize the entire payload to memory to determine the length of the messages body.

**Comment by hanej** [comment]
That makes sense.  Thanks.
