### ISSUE TITLE
telegraf output plugin emqtt causes telegraf to stop collection of metrics

### ISSUE THREAD

**Issue by jvrahav** [influxdata/telegraf#3566]
## Bug report
Telegraf stops collecting and publishing metrics after some time of operation.
Logs report that mysql took longer to collect than collection interval.

Mysql is the only enabled input plugin.
EMQTT is the only enabled output plugin.

coredump is captured here 
https://community.influxdata.com/t/telegraf-stops-collecting-metrics-after-some-time-error-in-plugin-inputs-mysql-took-longer-to-collect-than-collection-interval-1m0s/3303/2

### System info:
telegraf - 1.4.4
OS - RHEL 7

### Steps to reproduce:

1. Configure telegraf to report mysql metrics.
2. Configure telegraf to publish data to emqtt
3. After hours of operation, metrics are no longer published to EMQTT
4. Error logs report that mysql is taking longer time to collect

### Actual behavior:
Metrics collection should not be affected even if the endpoint emqtt server is restarted.
Not sure, if that was the trigger. There are some instances where such restarts did not affect collection.
### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
I believe this has been fixed in 1.8.2.
