### ISSUE TITLE
installing telegraf specific version with source code

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3567]
Hello,

we are trying to build our own rpm by installing telegraf with source code 

for installing telegraf with source code we followed the below steps:

1.Install Go
2.Setup your GOPATH
3.Run go get -d github.com/influxdata/telegraf
4.Run cd $GOPATH/src/github.com/influxdata/telegraf
5.Run make

at step-3 we are getting version of telegraf as 1.2.0

but we need latest version to be installed using github

can i know the way to get latest version of telegraf to be installed with source code using github..?

Thanks,

**Comment by goller** [comment]
Hi @hemasalma , try this : `go get -d -u github.com/influxdata/telegraf`  

It's possible that you already have the 1.2.0 source.  

Also, we would love to create more official RPMs for telegraf.  If you have suggestions about how to do that, it would be really helpful!

**Comment by danielnelson** [comment]
You may also want to replace set 3 with `git clone` and `git checkout`, this will give you more control over the version you build:
```
git clone https://github.com/influxdata/telegraf.git "$GOPATH/src/github.com/influxdata/telegraf"
git checkout 1.4.5
```
