### ISSUE TITLE
How to specify multiple host address?

### ISSUE THREAD

**Issue by internetuser2008** [influxdata/telegraf#3569]
How can I add multiple IP?
would like to add 10.0.0.1 & 10.0.0.2

 [[inputs.postgresql]]
   address = "postgres://monitoring:monitoring@10.0.0.1/postgres"
   ignored_databases = ["template0", "template1"]

**Comment by danielnelson** [comment]
Define the plugin multiple times like so:
```
[[inputs.postgresql]]
address = "postgres://monitoring:monitoring@10.0.0.1/postgres"
ignored_databases = ["template0", "template1"]

[[inputs.postgresql]]
address = "postgres://monitoring:monitoring@10.0.0.2/postgres"
ignored_databases = ["template0", "template1"]
```
