### ISSUE TITLE
Telegraf > Procstat > E! Error in plugin [inputs.procstat]

### ISSUE THREAD

**Issue by fchiorascu** [influxdata/telegraf#3575]
==Configuration==

**OS:** 
- CentOS Linux release 7.4.1708 (Core)

**PKGs:**
- influxdb-1.3.7-1.x86_64
- grafana-4.6.2-1.x86_64
- telegraf-1.4.3-1.x86_64

==Telegraf Configuration== /etc/telegraf/telegraf.conf
[[inputs.procstat]]
  exe = "memcached"
  prefix = "memcached"
[[inputs.procstat]]
  exe = "ntpd"
  prefix = "ntpd"

==Telegraf Output==
* Plugin: inputs.procstat, Collection 1
2017-12-12T18:49:22Z E! Error in plugin [inputs.procstat]: E! Error: procstat getting process, exe: [ntpd] pidfile: [] pattern: [] user: [] Error running /bin/pgrep: exit status 1
* Plugin: inputs.procstat, Collection 1
2017-12-12T18:49:19Z E! Error in plugin [inputs.procstat]: E! Error: procstat getting process, exe: [memcached] pidfile: [] pattern: [] user: [] Error running /bin/pgrep: exit status 1

***I've tried also in /etc/telegraf/telegraf.conf to have the below config but no graphs in Grafana then.

[[inputs.procstat]]
  exe = "telegraf|.*"
  prefix = "pgrep_svcs_process"

VS

[[inputs.procstat]]
  exe = "telegraf|.*"
  prefix = "pgrep_serviceprocess"

!!!
The point is to modify the /etc/telegraf/telegraf.conf and to collect all information for all processes and after this to be able to have the metrics in Grafana.

*** pgrep ntpd**
*** pgrep memcached** 

doesn't return nothing and it's clear that is a normal behavior of telegraf if a process is not up.

***
What are your recommendation in order to not have multiple definitions in "/etc/telegraf/telegraf.conf" like below:
[[inputs.procstat]]
exe = "memcached"
prefix = “memcached”
[[inputs.procstat]]
exe = "ntpd"
prefix = “ntpd”
.
.
.
etc

---===---===---
could I use something else like below for all processes:
[[inputs.procstat]]
exe = "telegraf|.*"
prefix = ?

What to do for the processes where "pgrep process" will not reveal nothing like: pgrep kibana, pgrep elasticsearch?
If I'll try "pgrep -u root, kibana; pgrep -u root, elasticsearch" then will be output there for process.
All apps are installed under root permission...

**Comment by danielnelson** [comment]
See my answer on https://community.influxdata.com/t/telegraf-procstat-e-error-in-plugin-inputs-procstat/3385/1
