### ISSUE TITLE
need ip address of a server to be retrieved by Telegraf 

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3576]
Hello,

we need to get ip address to be retrieved by telegraf along with hostname of the server..

Do we have any possible ways to get a server ip address where telegraf is installed?

**Comment by danielnelson** [comment]
You could arrange for the ip address to be placed into a environment variable, and then add that to the global tags section in the configuration.

**Comment by hemasalma** [comment]
Hi,

we have added environment variable as 
export IP =xxxx.xxx.xx.xx

now in telegraf.conf file we gave in global_tags block as 
ip = "$IP"

but it is not working... telegraf is not getting started..

**Comment by danielnelson** [comment]
Are you using systemd to start Telegraf?  If so you should put the environment variable in `/etc/defaults/telegraf` like:
```
IP=xxx.xxx.xxx.xxx
```

**Comment by hemasalma** [comment]
Hi,

when we try to encrypt data from telegraf to kafka 
we have generated .pem files in telegraf server and copied the files to kafka server 
we used .pem format in SSL Certificate Generation
then we got an error saying kafka doesnot support .pem

later, we generated .jks certificate files and given the same in telegraf conf file
when we try to execute we are getting an error saying that telegraf doesnot find any inforamtion like .pem file

so can i know which encryption i need to use for data from telegraf to kafka

**Comment by danielnelson** [comment]
Telegraf needs the certificate to be PEM encoded.  You will need to consult the Kafka documentation for what formats they require, but you can generally convert between formats if needed.
