### ISSUE TITLE
add basic auth support to the haproxy input plugin

### ISSUE THREAD

**Issue by stevebanik-ndsc** [influxdata/telegraf#3585]
Requesting this feature.  Are there plans for such a thing?

**Comment by danielnelson** [comment]
Looks like you can actually do this by putting your credentials into the userinfo section of the url:
```
http://user:password@1.2.3.4/haproxy?stats
```

The credentials are pulled out of the url and passed in the Authorization header as basic auth, not sent in the request url.

**Comment by stevebanik-ndsc** [comment]
That worked perfectly.  Thanks.

**Comment by danielnelson** [comment]
I just updated the documentation a bit, actually it was in there before but hopefully the newer version will be more informative.  Would love to hear any feedback you have on the update https://github.com/influxdata/telegraf/commit/4537eb2c5d1e8387b54db9e28497e94dad125b08
