### ISSUE TITLE
inputs.kafka_consumer error Consumer Error: EOF

### ISSUE THREAD

**Issue by pczhangyu** [influxdata/telegraf#3589]
## myconfig
# # Read metrics from Kafka topic(s)
 [[inputs.kafka_consumer]]
   brokers = ["172.16.125.151:9093","172.16.125.156:9093","172.16.125.163:9093"]
   topics = ["Apache_AccessLog"]
   consumer_group = "telegraf_metrics_consumers"
   offset = "newest"
   data_format = "influx"

## Bug report
   E! Error in plugin [inputs.kafka_consumer]: Consumer Error: EOF
### Relevant telegraf.conf:

**Comment by pczhangyu** [comment]
What's the problem with EOF

**Comment by danielnelson** [comment]
What version of Telegraf are you experiencing this with?

I found these issues upstream, it sounds like it indicates that the connection was closed.
- https://github.com/Shopify/sarama/issues/913
- https://github.com/bsm/sarama-cluster/issues/171

**Comment by pczhangyu** [comment]
kafka version 0.8.2.1/ telegraf version 1.4.4-1

**Comment by danielnelson** [comment]
We updated our kafka client library in the latest release, can you try with 1.5.0?

**Comment by pczhangyu** [comment]
thank you @danielnelson  i will

**Comment by glinton** [comment]
@pczhangyu did a newer telegraf version work for you? I'm going to close this until i hear otherwise

**Comment by alanjcastonguay** [comment]
I am using Telegraf 1.10.4 with the `kafka_consumer` input with Azure EventHub with Kafka. Leaving the default `config.Version = sarama.V0_10_2_0` produces this EOF error. It looks like EventHub drops the connection when faced with a client presenting a _too-old_ version, but I haven't proven that.

```
2019-07-31T18:28:43Z E! [inputs.kafka_consumer]: Error in plugin: kafka: error while consuming topicname/0: EOF
```

Explicitly setting a higher version 1.0.0 successfully consumes messages from Azure EventHub.

```toml
[[inputs.kafka_consumer]]
  version = "1.0.0"
```

**Comment by danielnelson** [comment]
Thanks for the tip on setting the version. I thought the default version was 0.8.2.0?

Either way, I recently updated the sarama library to support the latest version of Kafka, and as part of this the lowest version we will support in 1.12 is 0.10.2.0.  We could potentially add a fallback path for older versions but I'm waiting to see if there is any demand for it.

**Comment by Yu-MR1019** [comment]
各位好，我将telegraf启动之后，查看meassage日志有以下错误：请各位大佬指点
Feb  7 17:49:08 hostname-60103 telegraf: 2021-02-07T09:49:08Z E! [inputs.kafka_consumer] Error in plugin: EOF
Feb  7 17:49:13 hostname-60103 telegraf: 2021-02-07T09:49:13Z E! [inputs.kafka_consumer] Error in plugin: EOF
Feb  7 17:49:18 hostname-60103 telegraf: 2021-02-07T09:49:18Z E! [inputs.kafka_consumer] Error in plugin: EOF
Feb  7 17:49:23 hostname-60103 telegraf: 2021-02-07T09:49:23Z E! [inputs.kafka_consumer] Error in plugin: EOF
Feb  7 17:49:28 hostname-60103 telegraf: 2021-02-07T09:49:28Z E! [inputs.kafka_consumer] Error in plugin: EOF
Feb  7 17:49:33 hostname-60103 telegraf: 2021-02-07T09:49:33Z E! [inputs.kafka_consumer] Error in plugin: EOF
