### ISSUE TITLE
Add "retry" parameter to exec input plugin

### ISSUE THREAD

**Issue by Punkoivan** [influxdata/telegraf#3590]
Hello!
I would like to suggest a feature request:
shall we add the retry parameter to exec input plugin?

something like this:
```
[[inputs.exec]]
  commands = ["/home/ubuntu/statistics.py"]
  timeout = "5s"
  data_format = "influx"
  retry = 3        <-------
```

That means:

1. Execute command /home/ubuntu/statistics.py
2. waiting 5 seconds for a output
3. If timeout is expired, retry 3 more times
4. If retrying is successful -> post data to DB

I am facing an issue when my check runs hourly and server returns no data for the first time but does for a next (immediately after first) and telegraf posts no data to a DB, due to a failure of first run.

Thanks,
Ivan Punko

**Comment by danielnelson** [comment]
I don't think we should do this.  Telegraf retry is normally handled by trying on the next interval, though obviously this is a problem if your interval is 1h.  You should be able to retry in your script if needed though.
