### ISSUE TITLE
Postfix plugin permissions

### ISSUE THREAD

**Issue by dynek** [influxdata/telegraf#3591]
Hello,

I'm running 1.5.0 and wanted to benefit from the Postfix plugin.
How did you guys (@phemmer ?) did it with telegraf running with telegraf user which doesn't have access to files owned by postfix in /var/spool/postfix?

Example:
Error in plugin [inputs.postfix]: error scanning queue active: open /var/spool/postfix/active: permission denied

Thanks

**Comment by danielnelson** [comment]
What is the owner/group for this directory?  Perhaps you can add the `telegraf` user to this group.

**Comment by dynek** [comment]
Well thing is Postfix is pretty picky about its friends and most directories/files are owned by himself, group(s) have no permissions.
See:
```
4 drwx------  2 postfix root     4096 Dec 16 00:20 active
4 drwx------  2 postfix root     4096 Nov 28 10:20 bounce
```

**Comment by danielnelson** [comment]
Hmm, might need to chgrp and add group permissions.  Once we determine the best way we should add some documentation.

**Comment by phemmer** [comment]
2 options I can see
1. Run telegraf as root. This is what we do as we have telegraf monitoring a bunch of stuff you need root perms for.
2. Set a filesystem ACL.
