### ISSUE TITLE
Type loss in inputs.statsd => outputs.prometheus_client

### ISSUE THREAD

**Issue by kockockockoc** [influxdata/telegraf#3602]
## Bug report

Loading the data with telegraf inputs.statsd and exporting it with the prometheus output 
* Type becomes untyped (# TYPE test_ccc untyped)

### Relevant telegraf.conf:
```
[[outputs.prometheus_client]]
  listen = "127.0.0.1:9126"

[[inputs.statsd]]
  protocol = "udp"
  service_address = "127.0.0.1:2005"
```

### System info:

Telegraf v1.5.0 (git: release-1.5 a1668bbf)
CentOS Linux release 7.2.1511 (Core)

### Steps to reproduce:

```
echo "test.ccc:5|c" | nc -u 127.0.0.1 2005
sleep 35
curl -s 127.0.0.1:9126/metrics | grep ccc
```

### Expected behavior:
```
# HELP test_ccc Telegraf collected metric
# TYPE test_ccc counter
test_ccc{host="test.example.com",metric_type="counter"} 5
```
### Actual behavior:
```
# HELP test_ccc Telegraf collected metric
# TYPE test_ccc untyped
test_ccc{host="test.example.com",metric_type="counter"} 5
```

**Comment by sspaink** [comment]
Closing seems to be resolved in https://github.com/influxdata/telegraf/issues/3888 (previous closure was an automation mistake 🤖)
