### ISSUE TITLE
Query process on Windoes10 machine by pattern

### ISSUE THREAD

**Issue by botzill** [influxdata/telegraf#3605]
Hi guys,

I'm trying to use `win_perf_counters` plugin to find if a process is running on Windows. Manually I can run the following command and get info about the process:

```
wmic Path win32_process Where "CommandLine Like '%-m probe.tasks%'"
```
Now, can how to use `win_perf_counters` to perform the same. It is possible?

Thx!

**Comment by danielnelson** [comment]
I don't think it is possible, but you could try asking on the [InfluxData Community](https://community.influxdata.com) site.
