### ISSUE TITLE
Telegraf connects but doesn't write to influxdb on some machines

### ISSUE THREAD

**Issue by mikelindsay** [influxdata/telegraf#3608]
## Bug report
Most machines connect and begin writing data to influxdb without problems however a few connect and only do the following -

Makes the CREATE DATABASE request, creates the database, and never actually write windows metrics i'm gathering. I've tried multiple databases, config files, and copied and pasted config files.. Nothing has seemed to resolve it for the machines (different and same models) affected. Firewall was off, not content inspection. Once the CREATE DATABASE is seen in influx, no more request showing as being made after until restarting the service which only yields another CREATE DATABASE to be sent

(192.168.1.195)
![image](https://user-images.githubusercontent.com/4461292/34222542-e85e1b0e-e589-11e7-8726-81a18c540a67.png)

### Relevant telegraf.conf:
N/A, have only changed dbname and url to point to the server. used configs that work on other machines

### System info:
Version: 1.5.0
OS: Windows 10, Windows 7

### Steps to reproduce:

1. Start influx
2. Start telegraf
3. Wait for CREATE DATABASE to show up in influx after a few seconds
4. Wait forever until nothing ever gets written

### Expected behavior:
Data gets written to the influxDB for the endpoint

### Actual behavior:
Data does not get written for this endpoint to influxdb
### Additional info:

**Comment by mikelindsay** [comment]
I was able to resolve this by repairing the performance counters on these machines.

1. Launch Command Prompt as Administrator (right click Runs As Administrator).
2. Drop into the C:\WINDOWS\System32 directory by typing CD\ then CD Windows\System32
3. To rebuild your resource counters type the following command:
lodctr /r
This will rebuild your counter values and may take a few moments so please be patient.

**Comment by danielnelson** [comment]
Thanks for the update, so is this an issue that may prevent the `win_perf_counters` input plugin from working?

**Comment by mikelindsay** [comment]
Correct, if the performance counters are broken it fails to report. I had a few in my environment that were broken so I just added this to the Telegraf deployment script to repair regardless.

**Comment by danielnelson** [comment]
I added the instructions to the win_perf_counter README: https://github.com/influxdata/telegraf/commit/339c5d0312b05d04461d27403b20de78e7ba6195
