### ISSUE TITLE
FEATURE: kafka broker jmx metric input

### ISSUE THREAD

**Issue by cl0udgeek** [influxdata/telegraf#3609]
## Feature Request

It'd be nice to have telegraf natively pull all kafka broker jmx metrics and write to inlfux

### Proposal:
include a telegraf kafka broker jmx input that natively pulls all kafka broker mbeans the writes them to influx

### Use case: [Why is this important (helps with prioritizing requests)]
monitor kafka brokers. Right now, we use logstash's jmx input to pull all the kafka metrics, write to another kafka cluster...then use logstash again to consume from kafka, parse the data in grok, and then write the data out to influx.....would be nice to eliminate all of that and just use telegraf.

**Comment by dylanmei** [comment]
The Jolokia2 input plugin can handle this. There is [an example conf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2/examples/kafka.conf) included in this project.

You can run Jolokia as [a Java agent](https://jolokia.org/reference/html/architecture.html#agent-mode) or you can run [the Jolokia Proxy](https://jolokia.org/reference/html/architecture.html#proxy-mode) alongside Kafka. The Telegraf Jolokia2 plugin queries the Jolokia API exposed by the agent or the proxy.

**Comment by voiprodrigo** [comment]
Another alternative, you can also do this with JMXtrans, which has an InfluxDB writer that you can use to push to a Telegraf HTTP listener

**Comment by superbool** [comment]
A direct JMX input in telegraf will be great. Jolokia2 work,but need run Jolokia agent or proxy,it's not convenient. JMXtrans may be a better plan,but the bad output write is very uncomfortable,each metric need config one outputWriters like this:
https://gist.github.com/jsvisa/605455199984af74060599731806387d

**Comment by YiGene** [comment]
should have a direct jmx input as 
1. we don't wat to run a agent (jolokia2)
2. jmx trans : that means we need  start another process
