### ISSUE TITLE
multiple apache monitor

### ISSUE THREAD

**Issue by xoroz** [influxdata/telegraf#3611]
Hello all,
This is a really cool project, I am learning how to make it work.

### Proposal:
Allow one server to monitor multiple apaches

### Current behavior:
if  I enter multiple apaches I dont find them on the DB as a different HOST

[[inputs.apache]]
urls = ["https://server01/server-status?auto"  "http://server02/server-status?auto"]
insecure_skip_verify = true

### Desired behavior:
if  I enter multiple apaches I would like to find them on the DB as a different HOSTs

It seems like I would have to install telegraf agent on 100 servers other then doing it remotely.

please help

**Comment by danielnelson** [comment]
The `host` tag contains the hostname of the system Telegraf is running on, which is sometimes not that interesting especially when monitoring remote services.  For any plugin that can monitor remote services, there should be tags that identifies the service, but the exact tag names are not as well standardized.  For the apache input there is a `server` and a `port` tag that should work though.

**Comment by xoroz** [comment]
sorry I am new to the product, but still I am unable to monitor multiple remote apaches. could you please post a sample config or point me to a solution. the tag, server and port does not help. since its only linked to the same url...

I tried in different ways but never got it to respect the tag options.

here are some tries:

``
[[inputs.apache]]
        [[inputs.apache.object]]
                urls = ["https://centreon.ba.com/server-status?auto"]
                response_timeout = "5s"
                insecure_skip_verify = true
                [[inputs.apache.tags]]
                        server = "TEST"
                        port = "443"

or

[[inputs.apache]]
                urls = ["https://centreon.ba.com/server-status?auto"]
                response_timeout = "5s"
                insecure_skip_verify = true
                [[inputs.apache.tags]]
                       server = "TEST"
                        port = "443"

or

[[inputs.apache]]
                urls = ["https://centreon.ba.com/server-status?auto"]
                response_timeout = "5s"
                insecure_skip_verify = true
                server = "TEST"
                port = "443"
``
sorry but I found no examples of using this anywhere. It seems to me a very important option for this plugin.
my background is over 10 year of nagios/centreon monitoring systems and I am finding some lack of flexbility working with the agent/plugins.

**Comment by danielnelson** [comment]
With only your original setup:
```
[[inputs.apache]]
urls = ["https://server01/server-status?auto", "http://server02/server-status?auto"]
insecure_skip_verify = true
```

Then the query to InfluxDB would use `group by server` so you can see the separate values for each server:
```
select * from apache group by server;
```
