### ISSUE TITLE
procstat plugin - systemd_unit may have MainPID=0

### ISSUE THREAD

**Issue by botzill** [influxdata/telegraf#3612]
Hi.

I was testing `procstat` plugin using `systemd_unit` option. It works OK for most of the units but I came across one scenario when it does not work. I have `postgresql.service` unit which I noticed did not work. After some investigation to see how telegraf reads status about such processes I saw that you are reading the pid file from `systemctl show postgresql.service`. So, here is what I get for `postgresql.service`:
```
systemctl show postgresql.service | grep MainPID
GuessMainPID=yes
MainPID=0
ExecMainPID=7262
``` 

Here is what I get for another service:
```
systemctl show rabbitmq-server.service | grep MainPID
GuessMainPID=yes
MainPID=19509
ExecMainPID=19509
```

Now, I'm not really into systemd details and I could not find what it means to have `MainPID=0` but shouldn't we as well consider `ExecMainPID` in case `MainPID=0` ? Because the even if `MainPID=0` the process is running OK, I restart it and all seems to work fine.

p.s: Some Debug info about such cases may be useful as I could not tell what is wrong by logs.

Thx.

**Comment by phemmer** [comment]
I'd be interested in seeing your `postgresql.service` unit file. It shouldn't be possible to have a `ExecMainPID` and not a `MainPID`. The other way around should be though (its feasible to have a `MainPID` and not a `ExecMainPID`). My postgres units don't behave this way either (using systemd unit from official postgres EL7 repo).

Basically the difference between `MainPID` and `ExecMainPID` is that the former contains the last known PID (such as if the process has exited), while the latter tracks the current PID (being empty if no current process exists). Thus I think it'd be reasonable, to change the code to look at `ExecMainPID` instead of `MainPID`. This would prevent potential issues as well if some other process ends up getting the PID of the service after it exits.

**Comment by phemmer** [comment]
*Ignore previous (now deleted) comment, I had the parameters backwards (the documentation on them is broken).*

`MainPID=0` means that the unit has no active process. `ExecMainPID` contains the last PID of the process when it was running. If you have `MainPID=0` but `ExecMainPID=7262`, and the service is running, this likely means your unit file is broken as it's not properly tracking the main process.

**Comment by botzill** [comment]
OK, here is what I have for `postgresql.service`

```
# systemd service for managing all PostgreSQL clusters on the system. This
# service is actually a systemd target, but we are using a service since
# targets cannot be reloaded.

[Unit]
Description=PostgreSQL RDBMS

[Service]
Type=oneshot
ExecStart=/bin/true
ExecReload=/bin/true
RemainAfterExit=on

[Install]
WantedBy=multi-user.target
```
which seems to be only a formal one so that systemd could find it. I also see `postgresql@.service` which actually does the work:

```
# systemd service template for PostgreSQL clusters. The actual instances will
# be called "postgresql@version-cluster", e.g. "postgresql@9.3-main". The
# variable %i expands to "version-cluster", %I expands to "version/cluster".
# (%I breaks for cluster names containing dashes.)

[Unit]
Description=PostgreSQL Cluster %i
ConditionPathExists=/etc/postgresql/%I/postgresql.conf
PartOf=postgresql.service
ReloadPropagatedFrom=postgresql.service
Before=postgresql.service

[Service]
Type=forking
# @: use "postgresql@%i" as process name
ExecStart=@/usr/bin/pg_ctlcluster postgresql@%i --skip-systemctl-redirect %i start
ExecStop=/usr/bin/pg_ctlcluster --skip-systemctl-redirect -m fast %i stop
ExecReload=/usr/bin/pg_ctlcluster --skip-systemctl-redirect %i reload
PIDFile=/var/run/postgresql/%i.pid
SyslogIdentifier=postgresql@%i
# prevent OOM killer from choosing the postmaster (individual backends will
# reset the score to 0)
OOMScoreAdjust=-900
# restarting automatically will prevent "pg_ctlcluster ... stop" from working,
# so we disable it here. Also, the postmaster will restart by itself on most
# problems anyway, so it is questionable if one wants to enable external
# automatic restarts.
#Restart=on-failure
# (This should make pg_ctlcluster stop work, but doesn't:)
#RestartPreventExitStatus=SIGINT SIGTERM

[Install]
WantedBy=multi-user.target
```

And stats of `systemctl show postgresql.service`

```
Type=oneshot
Restart=no
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=infinity
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
FailureAction=none
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=yes
GuessMainPID=yes
MainPID=0
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
UID=4294967295
GID=4294967295
ExecMainStartTimestamp=Thu 2017-12-21 14:25:26 CET
ExecMainStartTimestampMonotonic=24228945815
ExecMainExitTimestamp=Thu 2017-12-21 14:25:26 CET
ExecMainExitTimestampMonotonic=24228947465
ExecMainPID=18062
ExecMainCode=1
ExecMainStatus=0
ExecStart={ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReload={ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
ControlGroup=/system.slice/postgresql.service
MemoryCurrent=18446744073709551615
CPUUsageNSec=18446744073709551615
TasksCurrent=0
Delegate=no
CPUAccounting=no
CPUWeight=18446744073709551615
StartupCPUWeight=18446744073709551615
CPUShares=18446744073709551615
StartupCPUShares=18446744073709551615
CPUQuotaPerSecUSec=infinity
IOAccounting=no
IOWeight=18446744073709551615
StartupIOWeight=18446744073709551615
BlockIOAccounting=no
BlockIOWeight=18446744073709551615
StartupBlockIOWeight=18446744073709551615
MemoryAccounting=no
MemoryLow=0
MemoryHigh=18446744073709551615
MemoryMax=18446744073709551615
MemorySwapMax=18446744073709551615
MemoryLimit=18446744073709551615
DevicePolicy=auto
TasksAccounting=yes
TasksMax=4915
UMask=0022
LimitCPU=18446744073709551615
LimitCPUSoft=18446744073709551615
LimitFSIZE=18446744073709551615
LimitFSIZESoft=18446744073709551615
LimitDATA=18446744073709551615
LimitDATASoft=18446744073709551615
LimitSTACK=18446744073709551615
LimitSTACKSoft=8388608
LimitCORE=18446744073709551615
LimitCORESoft=0
LimitRSS=18446744073709551615
LimitRSSSoft=18446744073709551615
LimitNOFILE=4096
LimitNOFILESoft=1024
LimitAS=18446744073709551615
LimitASSoft=18446744073709551615
LimitNPROC=3898
LimitNPROCSoft=3898
LimitMEMLOCK=65536
LimitMEMLOCKSoft=65536
LimitLOCKS=18446744073709551615
LimitLOCKSSoft=18446744073709551615
LimitSIGPENDING=3898
LimitSIGPENDINGSoft=3898
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=18446744073709551615
LimitRTTIMESoft=18446744073709551615
OOMScoreAdjust=0
Nice=0
IOScheduling=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
SecureBits=0
CapabilityBoundingSet=18446744073709551615
AmbientCapabilities=0
DynamicUser=no
RemoveIPC=no
MountFlags=0
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
RuntimeDirectoryMode=0755
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictNamespace=2114060288
KillMode=control-group
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=postgresql.service
Names=postgresql.service
Requires=system.slice sysinit.target
Wants=postgresql@9.4-main.service
WantedBy=multi-user.target
ConsistsOf=postgresql@9.4-main.service
Conflicts=shutdown.target
Before=multi-user.target shutdown.target
After=sysinit.target system.slice basic.target postgresql@9.4-main.service systemd-journald.socket
PropagatesReloadTo=postgresql@9.4-main.service
Description=PostgreSQL RDBMS
LoadState=loaded
ActiveState=active
SubState=exited
FragmentPath=/lib/systemd/system/postgresql.service
UnitFileState=enabled
UnitFilePreset=enabled
StateChangeTimestamp=Thu 2017-12-21 14:25:26 CET
StateChangeTimestampMonotonic=24228947652
InactiveExitTimestamp=Thu 2017-12-21 14:25:26 CET
InactiveExitTimestampMonotonic=24228945858
ActiveEnterTimestamp=Thu 2017-12-21 14:25:26 CET
ActiveEnterTimestampMonotonic=24228947652
ActiveExitTimestamp=Thu 2017-12-21 14:25:23 CET
ActiveExitTimestampMonotonic=24225769080
InactiveEnterTimestamp=Thu 2017-12-21 14:25:23 CET
InactiveEnterTimestampMonotonic=24225769080
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Thu 2017-12-21 14:25:26 CET
ConditionTimestampMonotonic=24228945223
AssertTimestamp=Thu 2017-12-21 14:25:26 CET
AssertTimestampMonotonic=24228945224
Transient=no
Perpetual=no
StartLimitIntervalSec=10000000
StartLimitBurst=5
StartLimitAction=none
InvocationID=cda03047a1744041a47e66c55fb34c76
```

I see as well `ConsistsOf=postgresql@9.4-main.service` but seems that I don't have such file on my system.

**Comment by phemmer** [comment]
Yeah, so you want to tell telegraf to monitor the `postgresql@9.4-main.service` instead of `postgresql.service`.
The reason you don't find a file is because anything with a `@` in the name is known as an "instanced" unit. The actual file will be `postgreql@.service`. Though if you do `systemctl cat postgresql@9.4-main.service`, it shouldn't matter as `systemctl` will find the file whatever the name, and dump it.

**Comment by botzill** [comment]
Hm, I see. Would be really nice to somehow do it via `postgresql.service` as this will be global and does not take into account postgresql version. Next time we upgrade postgresql we need to update telegraf plugin as well.

Anyway, thx a lot @phemmer  for this solution it clearly works now.

**Comment by phemmer** [comment]
Well, I'm not sure where that `postgres.service` unit came from, but that's not the correct way to accomplish the goal. And it can't be accommodated either. I'm guessing the `postgresql@.service` has a `WantedBy=postgres.service` in its config. There is a huge list of reasons why this is a bad idea. What should be used to accomplish the goal is a [systemd unit alias](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Alias=)

**Comment by botzill** [comment]
As posted above `postgresql@.service` have this in config:

```
[Unit]
Description=PostgreSQL Cluster %i
ConditionPathExists=/etc/postgresql/%I/postgresql.conf
PartOf=postgresql.service
ReloadPropagatedFrom=postgresql.service
Before=postgresql.service
```

So, I guess here is made this link/alias. 

To be honest I'm not sure why it's done like this, it's the way https://github.com/ANXS/postgresql does it. Maybe we should warn them :).

**Comment by phemmer** [comment]
Ah, I missed that, sorry. Saw `postgresql.service`, but completely blanked on `postgresql@.service`. That is a little better than a vanilla `WantedBy=`, but still a hack :-)

**Comment by danielnelson** [comment]
Is there anything we can/should do to address this then?  It seems like we would have to load all systemd units to resolve this dependency?

**Comment by phemmer** [comment]
No, nothing telegraf can do here. Theses are 2 completely separate units that have different pids. The relationship is also one-to-many, so even if you wanted to do some sort of relationship chasing, it wouldn't be reliable as you could end up with multiple pids and you wouldn't know which is the right one. The only way is to use the right unit.

On December 27, 2017 7:28:34 PM EST, Daniel Nelson <notifications@github.com> wrote:
>Is there anything we can/should do to address this then?  It seems like
>we would have to load all systemd units to resolve this dependency?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/influxdata/telegraf/issues/3612#issuecomment-354203675

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
