### ISSUE TITLE
Processes plugin fails to parse output of /proc/[pid]/stat because it contains '|'

### ISSUE THREAD

**Issue by swbsf** [influxdata/telegraf#3617]
Hi, you had similar issue with different characters, now it's a pipe :)

- OS : Debian Jessie
- Kernel : 4.14.7-sunxi
- arch: ARM (Olimex Lime2)

Tested on 4.10.1-sunxi, and no issue.

`Dec 21 15:13:21 localhost telegraf[791]: 2017-12-21T15:13:21Z I! processes: Unknown state [ I ] in file /proc/1069/stat
`

`# cat /proc/99/stat
99 (ipv6_addrconf) I 2 0 0 0 -1 69238880 0 0 0 0 0 0 0 0 0 -20 1 0 382 0 0 4294967295 0 0 0 0 0 0 0 2147483647 0 1 0 0 17 1 0 0 0 0 0 0 0 0 0 0 0 0 0`

Probably specific to this kernel, still, that's weird.

**Comment by swbsf** [comment]
Just realized it's not a pipe but a big i : I

**Comment by phemmer** [comment]
See #3530

**Comment by swbsf** [comment]
Whoops, ok let's close that one then.
