### ISSUE TITLE
OpenLDAP LDAP Result Code 32 "No Such Object":

### ISSUE THREAD

**Issue by lucgovmw** [influxdata/telegraf#3620]
I am trying to monitor OpenLDAP but I have this error LDAP Result Code 32 "No Such Object" when I start the telegraf agent. Am I missing something ? 
THanks in advance !

**Comment by danielnelson** [comment]
Perhaps you don't have the cn=Monitor backend enabled?

**Comment by lucgovmw** [comment]
Sorry if it is a dumb question, but where can I enable it ? Thanks and happy new year !

**Comment by danielnelson** [comment]
We should add some links to the documentation.  Here is what I think are the official docs[1], but I think most people are using the OLC, which is documented in 18.1:

> 18.1. Monitor configuration via cn=config(5)
> This section has yet to be written.

Instead I followed these instructions[2] for my testing on a Debian Stretch system.  I only needed to modify the `slapdpasswd` command to `slappasswd`.

@acobaugh Do you have any advice around configuration documentation?

[1] https://www.openldap.org/devel/admin/monitoringslapd.html
[2] https://blog.kmp.or.at/monitoring-openldap/

**Comment by acobaugh** [comment]
OLC config is pretty straightforward. You can use slapd itself to take a slapd.conf style config and output the equivalent cn=config style config. I often times use that to bootstrap new installations.

cn=monitor would be configured with this single entry (with the access rule(s) tailored to your liking), which I can add to the plugin docs:
```
dn: olcdatabase=monitor,cn=config
objectclass: olcDatabaseConfig
olcDatabase: monitor
olcAccess: to dn.subtree=cn=monitor by * read
```

The exact details around configuring an openldap server is probably out-of-scope for telegraf, but I'd be happy to help out of band.

**Comment by danielnelson** [comment]
I think the details will probably depend on what distro package or install method was used, and so I'm not sure the extent of the details we want in the docs.  Unless you have a better link, I think I'll just put the openldap.org link in and be a little more explicit that you must enable monitoring.

**Comment by lucgovmw** [comment]
I really appreciate your help guys, but is not clear for me (Im not familiar with it). I have the telegraf.conf file, should I  to add some lines there ? I am using UBUNTU and i've installed OpenLDAP using Apt-Get .Thank you !

**Comment by danielnelson** [comment]
Everything discussed so far is OpenLDAP configuration.  I think you will need to brew a pot of coffee and dive in to [the admin guide](http://www.openldap.org/doc/admin24/).

**Comment by lucgovmw** [comment]
@danielnelson thanks. I followed all steps with success described here: https://blog.kmp.or.at/monitoring-openldap/ but I am still having the same error when I type service telegraf status:

Jan 03 06:31:57 openldap-01a systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 03 06:31:57 openldap-01a telegraf[2371]: 2018-01-03T14:31:57Z I! Starting Telegraf v1.4.0
Jan 03 06:31:57 openldap-01a telegraf[2371]: 2018-01-03T14:31:57Z I! Loaded outputs: wavefront
Jan 03 06:31:57 openldap-01a telegraf[2371]: 2018-01-03T14:31:57Z I! Loaded inputs: inputs.ping inputs.cpu inputs.disk inputs.kernel inputs.swap inputs.system inputs.net inputs.net_response inputs.mem inputs
Jan 03 06:31:57 openldap-01a telegraf[2371]: 2018-01-03T14:31:57Z I! Tags enabled: host=openldap-01a
Jan 03 06:31:57 openldap-01a telegraf[2371]: 2018-01-03T14:31:57Z I! Agent Config: Interval:1m0s, Quiet:false, Hostname:"openldap-01a", Flush Interval:1m0s
Jan 03 06:31:58 openldap-01a telegraf[2371]: 2018-01-03T14:31:58Z E! Error in plugin [inputs.openldap]: LDAP Result Code 32 "No Such Object":

**Comment by lucgovmw** [comment]
After following the second article that you provided: https://www.openldap.org/devel/admin/monitoringslapd.html  with success. I have this error 👍 
2018-01-03T15:00:19Z E! Error in plugin [inputs.openldap]: LDAP Result Code 49 "Invalid Credentials":. But I am able to log in with the user monitor and I can see the Monitor Context available (using PHPLDAPDMIN)

**Comment by lucgovmw** [comment]
Thank you !!! Looks like it is working now 👍 

root@openldap-01a:/tmp# telegraf -config /etc/telegraf/telegraf.conf -input-filter openldap -test --debug
* Plugin: inputs.openldap, Collection 1
> openldap,server=192.168.110.16,port=389,host=openldap-01a search_operations_initiated=20i,pdu_statistics=260i,referrals_statistics=0i,unbind_operations_completed=7i,modify_operations_completed=0i,modrdn_operations_completed=0i,current_connections=1i,bind_operations_initiated=149i,compare_operations_initiated=0i,abandon_operations_completed=0i,bind_operations_completed=149i,delete_operations_completed=0i,compare_operations_completed=0i,add_operations_initiated=0i,add_operations_completed=0i,abandon_operations_initiated=0i,entries_statistics=93i,delete_operations_initiated=0i,max_file_descriptors_connections=1024i,search_operations_completed=19i,extended_operations_completed=0i,bytes_statistics=39230i,read_waiters=1i,write_waiters=0i,total_connections=1150i,unbind_operations_initiated=7i,modify_operations_initiated=0i,modrdn_operations_initiated=0i,extended_operations_initiated=0i 1515000434000000000
root@openldap-01a:/tmp#

**Comment by danielnelson** [comment]
Made this documentation update 37757b7782390ca77354c1af9e7d98d3cb23afdd
