### ISSUE TITLE
input plugin/disk

### ISSUE THREAD

**Issue by huyujie** [influxdata/telegraf#3623]
Some times,if have many mount points and we just want to monitor  device hard driver,just like:
```
root@tr02n13:/run/udev# df -lh | egrep '^/dev'
/dev/sda1              46G  3.1G   41G   8% /
/dev/sda3             474G  179G  271G  40% /***
/dev/sdm1              20G  1.8G   17G  10% /***/mnt/redisa
/dev/sdx1              20G  1.1G   18G   6% /***/mnt/xenial2x64
/dev/sdg1              20G  1.5G   18G   8% /***/mnt/img-8iui2t6j
/dev/sds1              20G  1.9G   17G  11% /***/mnt/img-oqcyzy89
/dev/sdaf1             20G  1.4G   18G   8% /***/mnt/loadbalancerj
```
and mount point  add  continuously,so we can't pecified exclude which mount points.

**Comment by danielnelson** [comment]
Is this feature request what you are looking for? https://github.com/influxdata/telegraf/issues/3070

**Comment by danielnelson** [comment]
Closing due to no response, if that PR is what you need then just keep an eye on it for updates.
