### ISSUE TITLE
StatsD Multiple Database Support

### ISSUE THREAD

**Issue by rijnhard** [influxdata/telegraf#363]
Just putting this here for completeness. 

It would be useful to push different statsd series to different DB's. 

The use case is pushing application stats series to one DB so that clients can see and manipulate them in grafana, while server performance stats series go to another DB so that only we can see those. 

(depending on feedback this should probably be a separate feature request)
And just to make things complicated it could be beneficial to push one series to multiple Databases so that we can see stats aggregated across all clients (since influx itself doesnt support aggregating across DBs), the predefined host can be used to differentiate between sources from within one DB, so that part is already done.  

This is a pretty terrible example but illustrates the point
```
#e.g
stats.campaign.sms.bulk:3|c
server.cpu.cpu1.core3.usage:50|g

# templates
DB_client_x:  [
    stats.campaign.* measurement.measurement.category.type
]
DB_clients_all: [
    stats.campaign.* measurement.measurement.category.type
]
DB_systems: [
    server.cpu.* measurement.measurement.cpu.core.type
]
```

**Comment by ankanm** [comment]
+1 for adding the ability to send various metrics to different target dbs (on the same influxdb.)

Another way is to add a 3rd (optional) argument after the measurement that points to the db(s) to send the data to:
```
#templates = [
  "stats.campaign.* measurement.measurement.category.type stasd_db,campaign_metrics",
  "server.cpu.* measurement.measurement.cpu.core.type metrics_db"
]
```
And perhaps the current "database" entry becomes the default db to send metrics to if nothing is provided here.

**Comment by sparrc** [comment]
We now have the ability for users to specify multiple outputs of the same type in the config file, and in 0.2.4 we will have the ability to have pass/drop/tagpass/tagdrop parameters on outputs.

@WiR3D-kNiGhT @ankanm I'm wondering if this solves your use-case in a generic way, you could now setup something like this:

```
[outputs]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "metrics_db" # required
  # Precision of writes, valid values are n, u, ms, s, m, and h
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"
  # Only allow "server" metrics
  pass = ["statsd_server"]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "campaign_db" # required
  # Precision of writes, valid values are n, u, ms, s, m, and h
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"
  # Only allow "campaign" metrics
  pass = ["statsd_stats_campaign"]


[plugins]

# Statsd Server
[[plugins.statsd]]
  ...
```

Note that you can also use tags to filter the outputs, so if you have tags defined in your templates you can filter on those as well (see https://github.com/influxdb/telegraf#output-options for more examples)

**Comment by WiR3D-kNiGhT** [comment]
so basically this way means you will configure the inputs in one location (the statsd service plugin) for all metrics and how they must be passed. 

Then you would setup an output for each db want to target: 
* can target multiple db's on the same/or different host with different metrics
* and I am also assuming you can send the same metric/tag to multiple outputs. 

In which case it covers all use cases:
* allowing us to conglomerate all statistics in one db
* allowing us to send multiple statistics to different db

So yes then this can be closed

**Comment by WiR3D-kNiGhT** [comment]
Oh and also, thank you @sparcc

**Comment by ankanm** [comment]
That looks good. Thanks @sparrc!
