### ISSUE TITLE
Add support for elasticsearch 6 input

### ISSUE THREAD

**Issue by ajaybhatnagar** [influxdata/telegraf#3630]
## Feature Request

Support for Elasticsearch 6.x for input / output plugins.

### Current behavior:

Not available

### Desired behavior:

Support ES6.x release

### Use case: 

new version of ES 6.x does not support types in mapping any more and it affects monitoring.

**Comment by danielnelson** [comment]
What happens when you try to use the current plugins?

**Comment by ajaybhatnagar** [comment]
There are issues related to fields with data type string and text. It needs default mappings of extracted data to be in sync.

**Comment by bfgoodrich** [comment]
We updated to ES 6.x and all of our ES monitoring is now borked

**Comment by mping** [comment]
Isn't this a matter of changing the output plugin to use `import "gopkg.in/olivere/elastic.v6"`?

**Comment by danielnelson** [comment]
@mping Can you test this and let me know?

**Comment by mping** [comment]
@danielnelson I'll reach our devops to see how we can check that out

**Comment by matthenning** [comment]
@mping @danielnelson Are there any news on this issue? Is it worth testing Telegraf with ES 6.x or are there definitely breaking changes?

**Comment by danielnelson** [comment]
@matthenning I would expect breaking changes based on the above comments.

**Comment by voiprodrigo** [comment]
I'm getting mostly null values in in the fields of measurement elasticsearch_indices. Using ES 6.2.2.

**Comment by danielnelson** [comment]
@voiprodrigo Do you think you could create a list of the changes between v5 and v6?  Only with respect to the metrics we currently collect.  I think we will want to support both of these for a while more.

**Comment by russorat** [comment]
tracking the output plugin here: https://github.com/influxdata/telegraf/issues/4268

**Comment by kri5** [comment]
It seems that you can pass an argument `level` to the query `_nodes/stats` or `/_nodes/_local/stats` with the value `indices`, and you get a subfields `indices` , child of the regular `indices` field, where each key is the index `name`, and the value is an object with the stats corresponding to this index.

As an example you can try `/_nodes/_local/stats?level=indices&pretty'`, it works on ES 6.4, and should work on ES 6.x.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

I don't know how previous versions of elasticsearch behave, but it seems that the parameters didn't exist by then, and that the behaviour was to 

> returns high level aggregation and index level stats for all indices
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/indices-stats.html

Hope that can help.

**Comment by dupondje** [comment]
Its still not clear for me what is broken now since ES 6.

I tried the latest Telegraf on ES 6, and I get correct metrics. Compared some output to ES 5 output, and its 100% the same ...

Can somebody be clear please? Give me exact examples of missing metrics/tags.
Then I can have a look to fix this. But currently, I really don't see an issue.

@kri5 :
But more recent versions mention:

> By default, all stats are returned, returning only specific stats can be specified as well in the URI. Those stats can be any of:

So nothing needed to fix this ... It returns the indices stats already without adding 'level'

**Comment by matthenning** [comment]
I think the mentioned problems only manifest when using ES 7.
In ES 6 those issues only throw a deprecation notice.

**Comment by dupondje** [comment]
@matthenning: Just setup an ES 7.2 via docker. And seems to work fine on first check ...
Guess we still need a clear stat/call/whatever that doesn't work, cause its still not clear :(

**Comment by matthenning** [comment]
@dupondje My bad, I was thinking output plugins.

**Comment by danielnelson** [comment]
I think we should close this issue, in general this seems to be working and new issues can be created for any specific bugs that might remain.
