### ISSUE TITLE
Feature: Support "collection_jitter" on a per-input basis

### ISSUE THREAD

**Issue by jcmcken** [influxdata/telegraf#3634]
### Proposal:

Each input should be allowed to specify its own ``collection_jitter``. 

Some input collections happen less frequently and with greater expense than others. Having a single, global ``collection_jitter`` makes it hard for expensive, long-running collections to co-exist with cheap, short-running collections, and still allow appropriate randomization to avoid collection stampedes while maintaining collection SLAs.

### Current behavior:

The ``collection_jitter`` option is an agent configuration that applies equally to all inputs.

### Desired behavior:

The ``collection_jitter`` should additionally be configurable per input. If one input occurs once per hour, it should be allowed to jitter within a large period (e.g. 30min) that might not be appropriate for an input that occurs once per minute.

### Use case:

In my specific use-case, we have lots of agents distributed across many machines coordinating with a centralized service to create some statistics per machine. This collection happens once per hour. These agents need to be randomly distributed across the 1 hour period to lessen the load on that central service.

**Comment by cruscio** [comment]
+1  

Specifying an input-specific `collection_jitter` next to the input-specific `interval` would go a long way to smoothing traffic spikes. My inbound network traffic graph on Influx data nodes looks like an ECG.

**Comment by solarce** [comment]
This would be very useful
