### ISSUE TITLE
Trigger script /run command on input Value

### ISSUE THREAD

**Issue by pierrick-openIT** [influxdata/telegraf#3635]
Hi everyone,

is it possible to trigger a command on telegraf agent over a treshold or something else ?

regards

**Comment by danielnelson** [comment]
Sorry, I don't fully understand your question, but Telegraf inputs can be either polling interval triggered or event triggered.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
