### ISSUE TITLE
Telegraf software availability

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3639]
Hello,

Do we have telegraf agent software for Solaris?

 we need whether telegraf supports xenservers and ESXI servers or not?

and also do we have any plugin that support to collect Oracle metrics?

**Comment by danielnelson** [comment]
We don't release packages for Solaris, there is an issue open for this: https://github.com/influxdata/telegraf/issues/407.  I believe that one could build Telegraf on Solaris and it ought to work in some capacity, but I do not have a system available for testing at this time.

There is also a feature request open for ESX support https://github.com/influxdata/telegraf/issues/1420, and there is no plugin specifically for Xen.

Lastly, we only have a feature request issue for a Oracle plugin: https://github.com/influxdata/telegraf/issues/831
