### ISSUE TITLE
AWS EC2 instance profile not being used for Creds

### ISSUE THREAD

**Issue by frezbo** [influxdata/telegraf#3640]
As per this https://github.com/influxdata/telegraf/blob/master/internal/config/aws/credentials.go, I don't see a fallback to using the ENV creds or EC2 creds from instance metadata using instance profiles, As per this I don't see the fallback mechanism https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/
Correct me if I'm wrong.

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
Both the environment variable and instance profile seem to be working for me, can you fill out the bug report template with reproduction steps and the expected/actual behavior?

**Comment by frezbo** [comment]
@danielnelson  thanks for the help, the issue was due to an old release, hence closing this.
