### ISSUE TITLE
[diskio] Add in LVM LV/VG name to device mapper devices

### ISSUE THREAD

**Issue by daviesalex** [influxdata/telegraf#3641]
## Feature Request

The "diskio" plugin in system/ by default grabs every SCSI device on a system (sdX, mdX, dm-X, etc.)

For many modern Linux distros, LVM is extensively used. The default RHEL/CentOS installs have everything except /boot on LVM. diskio is not reporting data based on LVM devices, but on the dm-X device; this is not very useful for reporting (the dm-X number is entirely arbitary and will vary from system to system based on the order LVs were created).

In the case of snapshots, its not even possible to figure out what LV was what DM device back in history.

### Proposal:

For dm-X devices, include an additional field for both LV and VG name.

This can be retrieved like this:

```
[root@chl-mysql-admin ~]# dmsetup ls
vg01-root_lv    (253:0)
fast-mysql--snap        (253:8)
vg01-var_lv     (253:5)
vg01-home_lv    (253:3)
fast-mysql      (253:1)
vg01-tmp_lv     (253:4)
fast-mysql-real (253:6)
slow-backups    (253:2)
```

Or, in a way that is likely easier for us:

```
[root@chl-mysql-admin ~]# ls -l /dev/mapper
total 0
crw------- 1 root root 10, 236 Aug 16 05:14 control
lrwxrwxrwx 1 root root       7 Jan  5 05:50 fast-mysql -> ../dm-1
lrwxrwxrwx 1 root root       7 Jan  5 05:50 fast-mysql-real -> ../dm-6
lrwxrwxrwx 1 root root       7 Jan  5 05:50 fast-mysql--snap -> ../dm-8
lrwxrwxrwx 1 root root       7 Jan  5 05:50 fast-mysql--snap-cow -> ../dm-7
lrwxrwxrwx 1 root root       7 Aug 16 05:14 slow-backups -> ../dm-2
lrwxrwxrwx 1 root root       7 Aug 16 05:14 vg01-home_lv -> ../dm-3
lrwxrwxrwx 1 root root       7 Aug 16 05:14 vg01-root_lv -> ../dm-0
lrwxrwxrwx 1 root root       7 Aug 16 05:14 vg01-tmp_lv -> ../dm-4
lrwxrwxrwx 1 root root       7 Aug 16 05:14 vg01-var_lv -> ../dm-5
```

In the first set of output, the second volume is a snapshot, the first column are "normal" LVs. So dm-0 is LV root_lv VG vg01; dm-2 is vg SLOW lv Backups

Note that it converts dashes in a LV/VG name to double dashes and the uses a single dash to split between VG and LV.

### Current behavior:

dm-X devices are simply reported as that. It would be impossible to know that IO to dm-8 in the output above in fact came from a COW snapshot called mysql-snap in the VG fast. This makes the grafana dashboards and Kapacitor alerts not hugely useful as a human as to log in to figure this out (and in the case of historical dashboards, as noted above, this may not even be possible)

### Desired behavior:

dm-X devices gain lv=foo,vg=bar fields

### Use case: 

It is essential to know what logical volume is actually responsible for the IO.

**Comment by phemmer** [comment]
This is already supported. See https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L813-L828

**Comment by daviesalex** [comment]
@phemmer so it is - thank you! I did not realize you could get it that way, but this works:

```
[[inputs.diskio]]
  skip_serial_number = true
  device_tags = ["DM_LV_NAME", "DM_NAME"]
```
Results in these tags: 
`name=dm-3,DM_LV_NAME=home_lv,DM_NAME=vg01-home_lv`

Thank you!
