### ISSUE TITLE
Config file does not support valid comments within arrays

### ISSUE THREAD

**Issue by dimas** [influxdata/telegraf#3642]
Guys, I am Go-illiterate so I apologise in advance for the report which can be just "this is how it works in Go, deal with it".
But it feels a bit weird that you cannot comment properly in potentially long lists like `templates` of a `socket_listener`:
```
[[inputs.socket_listener]]
service_address = "tcp://:2003"
data_format = "graphite"
# The comment works here perfectly
templates = [
  # But this comment throws a "parse error"
  "aaa bbb"
]
```
telegraf 1.5.0

Interesting enough is the doc provides an example actually: https://github.com/influxdata/telegraf/blob/052e88ad5ea5fa5872fba8998f1bf819ce418acb/docs/DATA_FORMATS_INPUT.md

> Multiple templates can also be specified, but these should be differentiated using filters (see below for more details)
```
templates = [
    "*.*.* region.region.measurement", # <- all 3-part measurements will match this one.
    "*.*.*.* region.region.host.measurement", # <- all 4-part measurements will match this one.
]
```
which does not work either:
```
2018/01/05 13:24:53 E! Error parsing /etc/telegraf/telegraf.d/graphite_input.conf, toml: line 16: parse error
```
where line 16 is this:
```
"*.*.*.* region.region.host.measurement", # <- all 4-part measurements will match this one.
```
and removing a comment on previous line fixes it

**Comment by danielnelson** [comment]
The configuration file is a TOML file, you can find the specification here: https://github.com/toml-lang/toml

I believe these should be allowed by the TOML format, and is a bug in the library we are using to parse the config file.  I am planning to switch to the BurntSushi library soon which handles both of these examples correctly for #1598 #272

**Comment by clarsen** [comment]
still not working as of telegraf 1.14

**Comment by DavidAntliff** [comment]
Just encountered this myself in telegraf 1.19.3 - according to the TOML spec it should be allowed.

**Comment by sspaink** [comment]
Closing in favor of: https://github.com/influxdata/telegraf/issues/10534 to track this issue, although this is an older issue I think the information in #10534 will be useful to help resolve this.
