### ISSUE TITLE
httpjson: line 40: map[string]string.insecure_skip_verify: `bool' type is not assignable to `string' type

### ISSUE THREAD

**Issue by slinderud** [influxdata/telegraf#3644]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
Doesn't read insecure_skip_verify = false correctly

### Relevant telegraf.conf:
[[inputs.httpjson]]
  name_override = "Lol"

  servers = [
    "YYYYYYY"
  ]

  response_timeout = "5s"
  method = "GET"
   [inputs.httpjson.headers]
     Authorization = "xxxxxxxx"

   insecure_skip_verify = false

### System info:

Latest telegraf v1.5

### Expected behavior:
It parses the config correclty

### Actual behavior:
it doesn't

### Additional info:
telegraf -config test.conf -test
2018/01/06 19:28:37 E! Error parsing test.conf, line 40: map[string]string.insecure_skip_verify: `bool' type is not assignable to `string' type

**Comment by danielnelson** [comment]
This is because the ordering of the config causes `insecure_skip_verify` to fall under the `[inputs.httpjson.headers]` table.  If you move it above the headers table it should work:

```
[[inputs.httpjson]]
  name_override = "Lol"

  servers = [
  "YYYYYYY"
  ]

  response_timeout = "5s"
  method = "GET"
  insecure_skip_verify = false

  [inputs.httpjson.headers]
    Authorization = "xxxxxxxx"
```

More info about this is at https://github.com/toml-lang/toml#table, in particular this bit describes how the tables work (also the indention has no meaning in TOML):
> Under that, and until the next table or EOF are the key/values of that table.

I will update the example config ordering.

**Comment by slinderud** [comment]
ah.. works now! Thanks :)

**Comment by danielnelson** [comment]
I changed the config ordering in 9cfa3b292bbdffa4ecefd3062632eaef4dc68cb1
