### ISSUE TITLE
AMQP_Consumer Altering Exchanges

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#3646]
### Relevant telegraf.conf:
exchange config

### System info:
Telegraf 1.5.0

### Steps to reproduce:

1. Create a RabbitMQ topic
2. Create another RabbitMQ topic or x-consistent-hash bound to the first topic (due to issue #2801)
3. Bind your queues to the second topic or x-consistent-hash

Your architecture should look something like this:
exch.telegraf (topic) -> exch.telegraf.consumer (x-consistent-hash) -> q.telegraf.1

4. Configure Telegraf amqp_consumer to use exchange exch.telegraf and one of the queues

On startup, the architecture now looks like:
exch.telegraf (topic) -> q.telegraf.1 AND exch.telegraf.consumer (x-consistent-hash) -> q.telegraf.1

### Expected behavior:
Exchanges are not reconfigured on startup for consuming messages

### Actual behavior:
This results in duplicate messages being sent to each queue.  It's much worse when you have multiple queues.  To get around this problem I have to provide a bogus exchange to just to make Telegraf happy when it starts up and leaves the main exchange configuration alone.

### Additional info:
When consuming messages, the only thing the client needs to provide the broker is the queue name and the prefetch count.  You should be able to delete lines 183 through 217.

**Comment by danielnelson** [comment]
Let me know if you still feel like we need additional changes in addition to the new exchange options in #4228.
