### ISSUE TITLE
Telegraf no more working when changing ip adress in DNS name of InfluxDB server

### ISSUE THREAD

**Issue by sebastien-prudhomme** [influxdata/telegraf#3648]
### System info:

Telegraf v1.5.0 on CentOS 6.5

### Steps to reproduce:

1. Start Telegraf pointing to influxdb.example.com (a CNAME to gateway.example.com, which is a reverse-proxy to the real InfluxDB server)
2. Telegraf works fine.
3. Change IP address of gateway.example.com
4. Wait several minutes/hours so that DNS servers and DNS cache take into account the new IP address
5. curl -v http://influxdb.example.com/ping works fine on the server with the Telegraf agent
6. Telegraf does not work anymore except if you restart it

Seems that IP address of the InfluxDB server is cached by the Telegraf agent (or perhaps a Go library) and never updated.

**Comment by jesus-sayar** [comment]
I have the same problem!

**Comment by andor-pierdelacabeza** [comment]
Obey the TTL!

**Comment by danielnelson** [comment]
@andor-pierdelacabeza lol
