### ISSUE TITLE
Panic on too many open files

### ISSUE THREAD

**Issue by pperesbr** [influxdata/telegraf#3652]
Hello,

I have a problem with telegraf/influx.

When I test with two metrics and two for two hosts, everything works normally. However, when I set up a larger number of files and more metrics it does not work.

Equipment I am monitoring:

Hosts (agents): 150
Metrics: 20700 (collected via snmp)

I have several files and on them the equipment with the metrics I want to collect.

example:
`
[global_tags]

[agent]
  interval = "5m"

[[outputs.influxdb]]
  url = "http://localhost:8086"
  database = "bln3agg"

[[inputs.snmp]]
  agents = [
           "se-soo1a",
           "se-soo1b",
           "se-bsa1a",
           "se-vta2b",
           "se-grs1b",
           "se-bsa1b",
           "se-can1b",
           "se-rjo1a",
           "se-rjo1b",
           "se-bnu1b",
           "se-csc1b",
           "se-jve1b",
           "se-cta4a",
           "se-foz1b",
           "se-vta2a",
           "se-can1a",
           "se-pae1b",
           "se-cpe1b",
           "se-cpe1a",
           "se-cba1b",
           "se-cba1a",
           "se-csl1a",
           "se-csl1b",
           "se-lda1b",
           "se-lda1a",
           "se-csc1a",
           "se-sne1b",
           "se-jve1a",
           "se-rjo3a",
           "se-rjo3b",
           "se-cas1a",
           "se-cas1b",
           "se-grs1a",
           "se-bhe1a",
           "se-bhe1b",
           "se-pae1a",
           "se-foz1a",
           "se-fsa1a",
           "se-fsa1b",
           "se-pgo4a",
           "se-pgo4b",
           "se-cta4b",
           "se-cge1b",
           "se-cge1a",
           "se-bnu1a",
           "se-sne1a",
           "se-vrd1a",
           "se-vrd1b",
  ]
  version = 2
  community = "public@gvt"
  name = "profile_count"

  [inputs.snmp.tags]
    profile_name = "i51200e102400"
    upstream = "51200"
    downstream = "102400"
    perfil="Velocidade"

   [[inputs.snmp.field]]
     name = "total_subscribers"
     oid = "1.3.6.1.4.1.2352.2.27.1.2.4.1.2.105.53.49.50.48.48.101.49.48.50.52.48.48"
`
Setting up my virtual machine, 4GB RAM and CPU:

`
root@svuxplogap01:/app/telegraf/conf# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Westmere E56xx/L56xx/X56xx (Nehalem-C)
Stepping:              1
CPU MHz:               2499.998
BogoMIPS:              4999.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1
Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl eagerfpu pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm
root@svuxplogap01:/app/telegraf/conf#`

Error logs when application crashes:

`
2018-01-09T22:55:00Z E! ERROR in input [inputs.snmp]: initializing field total_subscribers: translating: pipe2: too many open files
2018-01-09T22:55:00Z E! ERROR in input [inputs.snmp]: initializing field total_subscribers: translating: pipe2: too many open files
2018-01-09T22:55:00Z E! ERROR in input [inputs.snmp]: initializing field total_subscribers: translating: pipe2: too many open files
panic: runtime error: index out of range

goroutine 19699 [running]:
panic(0xf2b720, 0xc4200120d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/shirou/gopsutil/cpu.parseStatLine(0x1076108, 0x0, 0x1, 0xc42f2c7650, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:201 +0x895
github.com/shirou/gopsutil/cpu.Times(0x1044300, 0x0, 0x0, 0x0, 0x19c6638, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:53 +0x287
github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).CPUTimes(0x19c6638, 0xc42d7c0101, 0x5eaa02, 0xc421fad9f0, 0x5ed9ed, 0xf21fa0, 0xc42d7cf438)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/ps.go:45 +0xad
github.com/influxdata/telegraf/plugins/inputs/system.(*CPUStats).Gather(0xc420100540, 0x18faca0, 0xc4229d5340, 0x0, 0x4376f8)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/cpu.go:46 +0x7d
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc421d66f60, 0xc4201bb140, 0xc4229d5340)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x49
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xef

[1]-  Exit 2                  telegraf --config-directory /app/telegraf/conf/
[2]+  Exit 2                  telegraf --config-directory /app/telegraf/conf/
`

I already researched but I did not find anything about it, does anyone know what could be happening?

**Comment by danielnelson** [comment]
We should improve the error messaging here, but ultimately you will need to increase your open file limit.  Here is a link for Debian:

https://serverfault.com/questions/610130/how-to-set-ulimit-value-permanently

**Comment by dobicz** [comment]
Daniel, thanks... I will increase open file limit..

**Comment by danielnelson** [comment]
Thanks for the bug report and let me know if you still have problems.

**Comment by dobicz** [comment]
Daniel,

Now everything is working ok.

Thanks!!!!!

**Comment by danielnelson** [comment]
Glad to hear, we will keep this issue open until the error handling is improved when we hit this limit.

**Comment by sspaink** [comment]
Closing as increasing file limit resolved the issue,
