### ISSUE TITLE
issue with input docker configuration

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3653]
Hello,

We have installed telegraf in our server and we have installed docker on the same server and then we configured input docker plugin in telegraf.conf file we are able to get metrics of docker without any probelm.

but, when we try to get docker metrics installed in other server where telegraf is not present it is showing error..

can we know whether we can get docker metrics without installing docker on ther server with telegraf?

if yes then how we need to give **endpoint** in the configuration of docker in telegraf.conf file

**Comment by danielnelson** [comment]
You can setup docker to listen on a tcp socket, and then setup your configuration like:
```
tcp://docker.example.org:2375
```

This link describes how to setup a tcp socket:
https://docs.docker.com/engine/reference/commandline/dockerd/#examples
