### ISSUE TITLE
resource temporarily unavailable

### ISSUE THREAD

**Issue by wangtao334** [influxdata/telegraf#3657]
Hello.
I have a problem with telegraf.
I want to use inputs.exec to collect info freely, so i wrote some sh.
and set conf as below

```
# Read metrics about disk usage by mount point
[[inputs.disk]]
  # By default, telegraf gather stats for all mountpoints.
  # Setting mountpoints will restrict the stats to the specified mountpoints.
  interval = "15s"

# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
  # Commands array
  commands = [
    "/shared/grafana/telegraf-with-business-data/telegraf/script/*.sh"
  ]
  # Timeout for each command to complete.
  timeout = "10s"
  interval = "15s"
  data_format = "influx"

[[inputs.exec]]
  # Commands array
  commands = [
    "/shared/grafana/telegraf-with-business-data/telegraf/script/heart_beat/*.sh"
  ]
  # Timeout for each command to complete.
  timeout = "10s"
  interval = "15s"
  data_format = "influx"
```

Some sh call java. I calculated LWP when all sh run at same time, less than 2000, and i set ulimit 4096.
but sometimes LWP's count more than 4000+, error happened.

**Comment by danielnelson** [comment]
What is the error?  Does it look like https://github.com/influxdata/telegraf/issues/3652?

**Comment by wangtao334** [comment]
@danielnelson 
Error is  hit system's max process limit.  if exec limux cmd, get message [resource temporarily unavailable]. telegraf has been running for a few days.  most of the time process count less than 2000, but occasionally over the limit and lasted two hours. i set my telegraf user [open files : 4096, max user process 4096].  i don't know why a sudden increase in a lot of threads?

**Comment by danielnelson** [comment]
Next time you have the issue kill Telegraf with SIGQUIT, which will cause it to print the stack of all goroutines.  Upload the output of this and also your config file (clean the config of any security sensitive data first).

**Comment by danielnelson** [comment]
@wangtao334 Were you able to determine where the unexpected processes were coming from?

**Comment by danielnelson** [comment]
Let me know if this is still an issue.
