### ISSUE TITLE
SNMP plugin not producing results

### ISSUE THREAD

**Issue by cdean00** [influxdata/telegraf#3659]
### Relevant telegraf.conf:
[[inputs.snmp]]
  agents = [ "switchname.example.com" ]
  version = 2
  community = "public"

  name = "snmp"
  [[inputs.snmp.field]]
  name = "sysName"
  oid = "1.3.6.1.2.1.1.5.0"
  is_tag = true

### System info:

Telegraf v1.5.0 (git: release-1.5 a1668bbf)
Red Hat Enterprise Linux Server release 7.4 (Maipo)
3.10.0-693.11.1.el7.x86_64

### Steps to reproduce:

1. sudo telegraf --test --config /etc/telegraf/telegraf.d/snmp_switchname.conf

### Expected behavior:
Output of results

### Actual behavior:
-bash-4.2$ sudo telegraf --test --config /etc/telegraf/telegraf.d/snmp_switchname.conf 
* Plugin: inputs.snmp, Collection 1

### Additional info:
I got a tcpdump and there are successful get and requests. I also saw multiple requests but I'm not sure if that was from the test or normal execution in the background.

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I think this is because you need at least one field that is not a tag, does it work if you add another field or even duplicate the current one without `is_tag`?

**Comment by cdean00** [comment]
You are 100% correct and I feel stupid now. Originally I had multiple fields in the config but I took them out when it originally stopped working. Just tested again and everything is working again. It must have been something screwy with my original config when it broke. Thanks!

**Comment by danielnelson** [comment]
No problem, maybe there should be a warning in the logfile?

**Comment by cdean00** [comment]
A warning in the logs might be helpful. I assumed something was wrong because I was not getting any output back, not even an error.
