### ISSUE TITLE
InfluxDB input plugin

### ISSUE THREAD

**Issue by insasho** [influxdata/telegraf#366]
influxdb can be a difficult thing to manage, but telegraf does not have a plugin to monitor influxdb. InfluxDB has server monitoring features built in (https://influxdb.com/docs/v0.9/administration/statistics.html) and it could be useful to use telegraf to consolidate influxdb metrics from many clusters into a single cluster.

Expected behavior: telegraf should have an influxdb input.

**Comment by otoolep** [comment]
I agree. PRs welcome. :-)

**Comment by sparrc** [comment]
closed by #449
