### ISSUE TITLE
Feature Request - Add wildcard support to "Windows Services" plugin

### ISSUE THREAD

**Issue by glcx** [influxdata/telegraf#3673]
### Proposal:

Add wildcard support to "Windows Services" plugin. e.g. [ "Win*", "net*"]

### Current behavior:

To add service monitoring we need to either add services one per one or check the status of all the services.

### Desired behavior:

As per proposal

### Use case: [Why is this important (helps with prioritizing requests)]

Wildcard could permit more "automation-ready" plugin, and so permit the autodiscovery of new services with a specific pattern e.g. "Win*".

That way it could remove Manual & Automated modification of the config file.

**Comment by dsvware** [comment]
@danielnelson do we have an ETA for this? Thanks in advance!

**Comment by danielnelson** [comment]
No current ETA, any chance you could tackle this one?

**Comment by dsvware** [comment]
Hi Daniel,

Sorry, I'm afraid I'm not a developer :(

**Comment by sspaink** [comment]
Merged a pull request that resolves this issue. Let us know if you have any problems with this change! thanks.
