### ISSUE TITLE
Aggregator Basicstats - Unable to configure which basic stats to push as fields

### ISSUE THREAD

**Issue by arti007** [influxdata/telegraf#3676]
Configurable Aggregator Basicstats seems to be already available as per the below links, but somehow didn’t work for me for Telegraf v1.5.0 (git: release-1.5 a1668bbf)
https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/basicstats
https://github.com/influxdata/telegraf/pull/3580

Also a new version of Telegraf released last week . But is not working with the new version as well.
https://community.influxdata.com/t/telegraf-v1-5-1/3670

getting this error - 
>telegraf -config telegraf.conf
2018/01/16 12:05:18 E! Error parsing telegraf.conf, line 153: field corresponding to `stats' is not defined in `*basicstats.BasicStats'

Here is the snippet of telegraf.conf -

 [[aggregators.basicstats]]
   period = "60s"
   drop_original = true
   stats = ["count","min","max"]

**Comment by danielnelson** [comment]
`stats` is only in 1.6, use the release-1.5 branch to get the docs for version 1.5.x:

https://github.com/influxdata/telegraf/tree/release-1.5/plugins/aggregators/basicstats
