### ISSUE TITLE
Telegraf Status check generated as a Event

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3678]
Hello,

Monitoring process health using Telegraf - examples: whether telegraf agent on a given box is running and if dead, send an event?

Is there a way to configure Telegraf to send heartbeat messages to ES or other sources -for ex: every 30 secs, Telegraf sends a synthetic message that it is alive..

Can we know do we have telegraf integration with zenoss..?

**Comment by danielnelson** [comment]
You can use the `internal` plugin for this.  There is no zenoss plugin, maybe you can monitor it with general purpose utilities but I have never looked at it.
