### ISSUE TITLE
I am trying to monitor JBoss EAP 7.1 with this error  WFLYPC0011: Process 'Server:server-one' finished with an exit status of 137

### ISSUE THREAD

**Issue by lucgovmw** [influxdata/telegraf#3686]
I just put the first block suggested on the configuration page in the telegraf.com and tried to start Telegraf agent. I have already jolokia deployed and working fine.

telegraf Process is not running [ FAILED ]
[root@util-01a telegraf]# 15:16:58,850 INFO  [org.jboss.as.process.Server:server-one.status] (reaper for Server:server-one) WFLYPC0011: Process 'Server:server-one' finished with an exit status of 137
[Host Controller] 15:17:00,698 INFO  [org.jboss.as.host.controller] (ProcessControllerConnection-thread - 2) WFLYHC0027: Unregistering server server-one
[Host Controller] 15:17:01,861 INFO  [org.jboss.as.host.controller] (management I/O-1) WFLYHC0027: Unregistering server server-one

**Comment by danielnelson** [comment]
Can you upload your config file and the output of running:
```
telegraf --input-filter jolokia2 --test
```

**Comment by lucgovmw** [comment]
[root@util-01a telegraf]# telegraf --input-filter jolokia2 --test
2018/01/16 16:32:43 I! Using config file: /etc/telegraf/telegraf.conf
2018/01/16 16:32:43 E! Error: no inputs found, did you provide a valid config file?
[root@util-01a telegraf]#

**Comment by danielnelson** [comment]
Can you try like this, modifying the path to your config file if needed:
```
telegraf --config telegraf.conf --input-filter jolokia2_agent --test
```

**Comment by lucgovmw** [comment]
Sure. See the results below:

root@util-01a telegraf]# telegraf --config telegraf.conf --input-filter jolokia2_agent --test
2018/01/17 11:30:38 E! Error parsing telegraf.conf, Undefined but requested input: jolokia2_agent

**Comment by danielnelson** [comment]
What version of Telegraf do you have?
```
telegraf --version
```

**Comment by lucgovmw** [comment]
[root@util-01a telegraf]# telegraf -version
Telegraf v1.4.0 (git: telegraf-1.4.0 34b7a4c3611d1ede908ef275401544c34a4a3ba3)

**Comment by danielnelson** [comment]
You will need version 1.5 for this plugin.

**Comment by lucgovmw** [comment]
Think You ! I Will upgrade The agent abs let You Know.

Em qua, 17 de jan de 2018 às 18:57, Daniel Nelson <notifications@github.com>
escreveu:

**Comment by lucgovmw** [comment]
You Rock ! you fixed my problem ! thank you again !!!
