### ISSUE TITLE
Add tags for http_response input

### ISSUE THREAD

**Issue by etlweather** [influxdata/telegraf#3695]
Would be very useful to be able to add tags to the `http_response` input. For example, if I want to check a few URLs like this:

 - sub1.example.com/health
 - sub2.example.com/health
 - sub3.example.com/internal/health

Right now, the tag `server` contains the full URL above, which is fine, but I would like a tag that has only the domain name (e.g. `sub1.example.com`).

If I could add a tag for each input, that would make it possible.

Right now what I have to do is put a global tag and run telegraf a hundred times, one for each site I want to check.

**Comment by danielnelson** [comment]
You can use the tags option on any input, here is an example: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags

Does this provide what you need?

**Comment by etlweather** [comment]
Yes, sorry, was just about to close this. I re-read the documentation and found that generic input tag.
