### ISSUE TITLE
IPMI Filter Sensors

### ISSUE THREAD

**Issue by jhg03a** [influxdata/telegraf#3700]
I'd like to see the ability for the IPMI sensor data to be able to be filtered to a configurable subset.  This would give the ability to collect and store different pieces of data on separate intervals or not at all.  For example, I shouldn't normally need to spend the storage budget to record my PCIe Slots are ok every 10 seconds.

This would require adding a new configuration option to supply to the parse function who can then simply check if it is present in the whitelist before adding it to the final output.

**Comment by danielnelson** [comment]
You can use the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options to trim down the list, will this work for you?  We usually only add additional filtering options if there is some performance benefit to be had, but with ipmi it is a single call that returns all of the sensors.

**Comment by jhg03a** [comment]
Ah, I'd missed that that was an option.  That should satisfy the objective.
