### ISSUE TITLE
Make rabbitmq_queue gathering be configurable

### ISSUE THREAD

**Issue by ildarsv** [influxdata/telegraf#3701]
## Feature Request

Some components can create a lot of temporary queues in RabbitMQ.
In RabbitMQ input plugin we have the `rabbitmq_queue` measurement with the `queue` tag. Gathering of the `rabbitmq_queue` metrics is not configurable in current implementation, we can only specify a list of queues to gather. In that case we might have a tons of tags for temporary queues.

### Proposal:

I propose to add `gather_queues` parameter into configuration, just to have possibility disable gathering for `rabbitmq_queue` measurement if needed.

### Current behavior:

`gather_queues` is gathered in any case.

### Desired behavior:

Disable `gather_queues` gathering.

### Use case:

I want to make my InfluxDB less stressed. For now we have 20+ new series for every temporary queue.

**Comment by kerams** [comment]
I use `queues = [ "-" ]` as a workaround.

**Comment by ildarsv** [comment]
Yes, I agree, but another side is `err := r.requestJSON("/api/queues", &queues)`. Telegraf makes request to RabbitMQ API every collection interval in any case.
But if you don't want gather `rabbitmq_queue` metrics, let's avoid these requests at all.

**Comment by kerams** [comment]
Yeah, I've seen it timeouting on that call alone. We have almost a thousand active queues.

**Comment by danielnelson** [comment]
Add for 1.6, thanks @ildarsv
