### ISSUE TITLE
Add caching to SNMP plugin

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#3704]
"With SNMP, doing a walk on a device (at least for some massive Telco size equipment) is actually very expensive and a walk is done every time. This could be avoided by adding a “cached=true” parameter to certain fields at the expense of memory utilization of course.

**Comment by phemmer** [comment]
To me this feels rather awkward. Why bother emitting the data if you already know it's not going to have changed? Seems like the right solution would be to reduce the polling interval. You can define multiple `[[inputs.snmp]]` sections with different polling intervals if you have different values you want probed at different rates.

**Comment by danielnelson** [comment]
There was some talk about supporting dependent queries that this suggestion would go along with, but it doesn't make sense on its own.
