### ISSUE TITLE
Network instance filter not working in win perf method

### ISSUE THREAD

**Issue by ashuw018** [influxdata/telegraf#3708]
## Directions

Network adapter instance filtering is not working with "inputs.win_perf_counters.object" Method.

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["ethname", "ethname2"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec",
      "Packets Received Discarded",
      "Packets Outbound Discarded",
      "Packets Received Errors",
      "Packets Outbound Errors",
    ]
    Measurement = "win_net" 

I have tried entering name of Ethernet, description of it. but it is not working. however interface filtering is working properly in WMI method. 

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

Windows 7 , 10. server 2012

Telegraf 1.5

**Comment by danielnelson** [comment]
Can you set `Instances = ["*"]` and attach the output using
```
telegraf --config <yourconfig> --input-filter win_perf_counters --test
```

This will hopefully allow us to see what the instance names are.

**Comment by ashuw018** [comment]
Hi,

After some tests i got this working in my test environment.
All i was doing was getting eth name from netsh command or from eth gui properties and it was not working.

Then i tried using powershell get-counter with * instance and it return all interfaces and i copied these instance names and it did work. 

Netsh shows different names and powershell shows different. 

Thanks.

**Comment by danielnelson** [comment]
Glad you got it working, thanks for the update and the debugging tips.
