### ISSUE TITLE
telegraf - influx output

### ISSUE THREAD

**Issue by r4yfx** [influxdata/telegraf#3714]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
When testing telegraf.conf  - it doesn't output data from script

### Relevant telegraf.conf:
```
 [[inputs.exec]]
  commands = ["powershell C:/restorepoints.ps1"]
  name_override = "veeamrestore"
  interval = "300s"
  timeout = "240s"
  data_format = "influx"
```
### System info:

telegraf 1.4.3
Windows 2012

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
Expecting to show output

### Actual behavior:
No output

### Additional info:

Assuming that this is a possible output issue. Could someone please advise as to how this should be laid out? 
```
Function RestorePointStats{
    $out = @()
    ForEach($backup in $backups){
        $restorePoint = Get-VBRRestorePoint -Backup $backup
        $out = $restorePoint | Select Name, ApproxSize
    
    foreach($o in $out)
	{
	$na = $o.name
	$as = $o.approxsize
	write-output "veeam-stats name=$na approxsize=$as"
	}
  }
}

asnp VeeamPSSnapin
$backups = Get-VBRBackup
RestorePointStats
```

**Comment by phlipse** [comment]
With *data_format = "influx"* in your telegraf.conf you specify you would use line protocol. I don't know your backup solution or what it is printing out, but your *write-output* call seems to be formatted wrong. First of all your measurement should be comma separated from your tag set and between the tag and the field set there should be a space. So try it with the following:
*write-output "veeam-stats,name=$na approxsize=$as"*
This assumes that *veeam-stats* is your measurement name, *name* is your tag and *approxsize* is your field. Also ensure that your variable *as* contains any value other then an empty string. 

But you should read up all the line protocol rules at [docs.influxdata.com](https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/) to get it working properly.

**Comment by r4yfx** [comment]
Thank you @phlipse - got the format sorted
