### ISSUE TITLE
Processor Configuration From File - Feature Request

### ISSUE THREAD

**Issue by Andy--Rose** [influxdata/telegraf#3715]
Proposal: In addition to defining a list of strings for processors (i.e. fielddrop, tagdrop, etc.) for each input/output directly in the configuration, provide the ability to define an array of file locations with the configuration for processors. 

Current behavior: Processors are defined in the input/output sections of the main configuration.

Desired behavior: Alternative option in the processor attributes to define processor configuration files instead.

Use Cases:
- Can change a file dynamically without effecting the rest of the configuration file (restart expected).
- Reduces the complexity/length of the configuration file
- Repeated processors can be used across input/output definitions (keeping things DRY)

**Comment by danielnelson** [comment]
You can split up your configuration into multiple files using the [`--config-directory`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#configuration-file-locations) option.  After modifying a file you can send a SIGHUP to telegraf to restart it.

Is this what you are hoping to achieve?
