### ISSUE TITLE
elasticsearch plugin not reporting 'status_code' field

### ISSUE THREAD

**Issue by lloydcotten** [influxdata/telegraf#3724]
## Bug report
My understanding from the documentation and the intention of the code is that a numeric `status_code` along side the string value `status` field.  However, the `status_code` field is missing while the `status` field is present.

### Expected behavior:
To get a `status_code` field out from the elasticsearch cluster_health.

### Actual behavior:
`status_code` field missing.

### Additional info:
Just a golang beginner, but I believe it needs to be added to this struct: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/elasticsearch/elasticsearch.go#L40

Can someone confirm?  I'd be glad to sign the CLA and open a PR for this - but wanted someone to quickly glance at it to make sure I'm not far off base before going to the trouble of all that.

Thanks!

**Comment by danielnelson** [comment]
This will only be available in the next version (1.6), are you testing with a nightly build or from the master branch?

**Comment by lloydcotten** [comment]
Ooh I see - I misread the blame on this and was thinking it was in for a previous version.  I was testing 1.5.1, sorry about that.
