### ISSUE TITLE
expose Telegraf's metric buffer size / depth

### ISSUE THREAD

**Issue by lukebigum** [influxdata/telegraf#3727]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

I'd like to be able to see the current size or depth of Telegraf's metric_buffers, so I could measure how much time until the buffers fill if an output is offline.

### Current behavior:

There does not appear to be any way to determine what the current size of the buffers are.

### Desired behavior:

A simple HTTP status thread that returns JSON would be enough:

`curl http://localhost:12345/`

### Use case: [Why is this important (helps with prioritizing requests)]

I send different metrics to different InfluxDB clusters, and some Telegraf instances collect more metrics than others. If a cluster goes offline, it would be helpful to know how much time there is before Telegraf starts dropping metrics to that output.  This information would also help me size the metric_buffer_limit setting appropriately (or lower the interval of some plugins).

**Comment by phemmer** [comment]
You could use the `internal` input to gather the data, and then combine with the `prometheus_client` output to provide the http server.

**Comment by lukebigum** [comment]
That should do exactly what I want, thank you - somehow I missed the `internal` input.

**Comment by danielnelson** [comment]
We should probably rename this plugin, perhaps to `telegraf`.

**Comment by christianTF** [comment]
I still like the proposal of @lukebigum of a direct way to query current and Max buffer size.

We‘re developing a data Import to Influx via Telegraf Unix socket and currently stuck how to slow down parallel import processes.
With the internal measure in 10 secs intervals, we already get data loss when parallel Imports start for 10 seconds to fill the socket.
With querying these measures on-the-fly we could pause the imports, without letting them run out of buffers in the next 10 seconds.

By the way, we generally were surprised about the Unix socket behavior of Telegraf:
Usually, if a receiver does not query the socket, the senders socket fills up until I get a send error. I would react to the send error by some delay and retry.

In the Influx case, the Unix socket seems to be fetched, therefore the client never gets a send error. On the other hand, Influx‘s internal buffers fill up and data are dropped.
I don’t know why Influx doesn’t delay to fetch the socket but instead drops fetched data.
