### ISSUE TITLE
Configure SMART attributes collected

### ISSUE THREAD

**Issue by bordershot** [influxdata/telegraf#3728]
## Feature Request
Collect all SMART metrics, or make collection metrics configurable.

### Proposal:
Add to the configuration an array of metrics to be collected, or just loop through all smart attributes returned and collect.  

Current array of collected fields:

> 	deviceFieldIds = map[string]string{
> 		"1":   "read_error_rate",
> 		"7":   "seek_error_rate",
> 		"194": "temp_c",
> 		"199": "udma_crc_errors",
> 	}
> 

On a random host, I have the following available:

> SMART Attributes Data Structure revision number: 16
> Vendor Specific SMART Attributes with Thresholds:
> ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
>   1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
>   2 Throughput_Performance  0x0005   135   135   054    Pre-fail  Offline      -       84
>   3 Spin_Up_Time            0x0007   131   131   024    Pre-fail  Always       -       456 (Average 496)
>   4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       43
>   5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
>   7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
>   8 Seek_Time_Performance   0x0005   124   124   020    Pre-fail  Offline      -       33
>   9 Power_On_Hours          0x0012   096   096   000    Old_age   Always       -       31089
>  10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
>  12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       43
> 192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       737
> 193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       737
> 194 Temperature_Celsius     0x0002   142   142   000    Old_age   Always       -       42 (Min/Max 23/61)
> 196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
> 197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
> 198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
> 199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0

Backblaze recommends:
https://www.backblaze.com/blog/hard-drive-smart-stats/
https://www.backblaze.com/blog/what-smart-stats-indicate-hard-drive-failures/
Attribute		Description
SMART 5		Reallocated Sectors Count
SMART 187		Reported Uncorrectable Errors
SMART 188		Command Timeout
SMART 197		Current Pending Sector Count
SMART 198		Uncorrectable Sector Count

### Current behavior:
Non-configurable list of SMART attributes.

### Desired behavior:
Configurable list, or just collect all metrics.

### Use case: [Why is this important (helps with prioritizing requests)]
See above, Backblaze has metrics they have found useful in HDD failure rates, but the current plugin does not collect them.

**Comment by danielnelson** [comment]
Can you upload the output of this command (replacing the device path):
```
sudo smartctl --info --health --attributes --tolerance=verypermissive -n standby --format=brief /dev/sda```

**Comment by bordershot** [comment]
`sudo smartctl --info --health --attributes --tolerance=verypermissive -n standby --format=brief /dev/sda
[sudo] password for : 
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-112-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     HGST Deskstar NAS
Device Model:     HGST HDN724030ALE640
Serial Number:    PK2234P8JZ6GPY
LU WWN Device Id: 5 000cca 22ce9ea71
Firmware Version: MJ8OA5E0
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Tue Jan 30 10:41:46 2018 PST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
Power mode is:    ACTIVE or IDLE

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     PO-R--   100   100   016    -    0
  2 Throughput_Performance  P-S---   135   135   054    -    84
  3 Spin_Up_Time            POS---   131   131   024    -    456 (Average 496)
  4 Start_Stop_Count        -O--C-   100   100   000    -    44
  5 Reallocated_Sector_Ct   PO--CK   100   100   005    -    0
  7 Seek_Error_Rate         PO-R--   100   100   067    -    0
  8 Seek_Time_Performance   P-S---   124   124   020    -    33
  9 Power_On_Hours          -O--C-   096   096   000    -    31135
 10 Spin_Retry_Count        PO--C-   100   100   060    -    0
 12 Power_Cycle_Count       -O--CK   100   100   000    -    44
192 Power-Off_Retract_Count -O--CK   100   100   000    -    738
193 Load_Cycle_Count        -O--C-   100   100   000    -    738
194 Temperature_Celsius     -O----   150   150   000    -    40 (Min/Max 23/61)
196 Reallocated_Event_Count -O--CK   100   100   000    -    0
197 Current_Pending_Sector  -O---K   100   100   000    -    0
198 Offline_Uncorrectable   ---R--   100   100   000    -    0
199 UDMA_CRC_Error_Count    -O-R--   200   200   000    -    0
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning`

**Comment by danielnelson** [comment]
It sounds like maybe you are looking at the `smart_device` measurement.  The attributes are saved in the `smart_attribute` measurement, and are tagged by name, since each one has its own values.

**Comment by bordershot** [comment]
Am I misconfigured?  I don't see smart_attribute in influxdb. I don't see it when I test.

sudo telegraf -config /etc/telegraf/telegraf.d/default_inputs.conf -test -input-filter smart
[sudo] password for : 
* Plugin: inputs.smart, Collection 1
> smart_device,device=sdd,model=HGST\ HDN728080ALE604,serial_no=xxx,wwn=xxx,capacity=8001563222016,enabled=Enabled,host=xxx read_error_rate=0i,seek_error_rate=0i,temp_c=38i,udma_crc_errors=0i,exit_status=0i,health_ok=true 1517418058000000000
...

dpkg -l | grep telegraf
ii  telegraf                                    1.5.1-1                                      amd64        Plugin-driven server agent for reporting metrics into InfluxDB.

**Comment by danielnelson** [comment]
I think it should work if you add `attributes = true` to your config.

**Comment by bordershot** [comment]
Thank you!  Maybe improve the readme, I still don't get what 'attributes' toggles, or why you would want it off.

**Comment by danielnelson** [comment]
@rickard-von-essen Enabling attributes doesn't significantly change the amount of work the plugin needs to perform, any reservations about me changing this option to default to true?

**Comment by rickard-von-essen** [comment]
@danielnelson no, feel free to change it. It's more reasonable default.
