### ISSUE TITLE
Use BurntSushi TOML parser instead of naoina

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#373]
the BurntSushi toml parser is much more commonly used and supported: https://github.com/BurntSushi/toml

We should use this instead of https://github.com/naoina/toml. This will be easier to maintain and also fix an issue where invalid types in the TOML config cause a panic, such as:

```
[tags]
names = ["foo", "bar"]
```

**Comment by ekini** [comment]
According to https://github.com/toml-lang/toml#user-content-implementations, BurntSushi's is only 0.2.0 compliant, but naoina's supports 0.4.0.

I've used both, and like the latter more. At least for auto recognising toml's "some_value' as SomeValue.

There's also https://github.com/pelletier/go-toml, which I've never tried.

**Comment by sparrc** [comment]
@ekini I didn't realize that, from what I could tell it seemed that the BurntSushi library has an easier interface for parsing arbitrary toml than naoina's, and it also won't panic when presented with the wrong type.

**Comment by sparrc** [comment]
closing, won't implement
