### ISSUE TITLE
No "Prefix" option when running multiple haproxy via nbproc

### ISSUE THREAD

**Issue by marzlarz** [influxdata/telegraf#3730]
## Directions

Hello,

We run HAProxy with multiple cores using nbproc, therefore we have separate stats interfaces. I.e. - 

127.0.0.1:9000/haproxy?stats
127.0.0.1:9001/haproxy?stats

Each Core has its own stats interface and are proxying different applications. The telegraf plugin for haproxy doesn't support the "prefix" option, which would allow me to differentiate between the two. I.e. - 

[[inputs.haproxy]]
  server = ["https://127.0.0.1:9000/haproxy?stats"]
  insecure_skip_verify = true
  prefix = "haproxy_9000_"

[[inputs.haproxy]]
  server = ["https://127.0.0.1:9001/haproxy?stats"]
  insecure_skip_verify = true
  prefix = "haproxy_9001_"

The problem this causes is that our graphs look odd because one poll cycle it will report the usage of 9000, and the next 9001 data, so very "spiky" graphs since the traffic volume is much different.

### System info:

Telegraf 1.5.0
CentOS 7.4

### Use case: [Why is this important (helps with prioritizing requests)]
Getting HAProxy stats data from each nbproc

**Comment by danielnelson** [comment]
There is a `server` tag, so if you `group by server` then you will be able to see the two series without overlap.  Let me know if you need more help.
