### ISSUE TITLE
Problem with use of OID in snmp input plugin 

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3732]
Hi,
I have installed telegraf version 1.2 and configured snmp input plugin to collect ESXI server metrics.
My conf file is like below
[[inputs.snmp]]
  agents = [ "192.168.X.X:161" ]
  timeout = "5s"
  retries = 3
  version = 2
  community = "public"
  max_repetitions = 10
  name = "snmp"
[[inputs.snmp.field]]
   name = "sysDescr"
  oid = ".1.3.6.1.2.1.1.1.0"
[[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
[[inputs.snmp.field]]
   name = "upTime"
    oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
    #oid = "HOST-RESOURCES-MIB::hrDeviceDescr.2"
[[inputs.snmp.field]]
  name = "hrMemorySize"
   oid = "HOST-RESOURCES-MIB::hrMemorySize.0"
[[inputs.snmp.field]]
  name = "hrCpuLoad"
 oid = "HOST-RESOURCES-MIB::hrProcessorLoad.5"
[[inputs.snmp.field]]
  name = "hrDiskStorageCapacity"
   oid = "HOST-RESOURCES-MIB::hrDiskStorageCapacity.12"

with the above configuration i am able to get overall ESXI server metrics like cpu,memory...
but i am unable to get the  individual VM details in that ESXI server like VM count, running VM's....
i tried to perform snmpwalk with the oid (1.3.6.1.4.1.6876.2.1) the output is

snmpwalk -v 2c -c public 192.168.X.X 1.3.6.1.4.1.6876.2.1

SNMPv2-SMI::enterprises.6876.2.1.1.6.14 = STRING: "powered on"
SNMPv2-SMI::enterprises.6876.2.1.1.6.16 = STRING: "powered on"
SNMPv2-SMI::enterprises.6876.2.1.1.6.21 = STRING: "powered on"
SNMPv2-SMI::enterprises.6876.2.1.1.6.23 = STRING: "powered on"
SNMPv2-SMI::enterprises.6876.2.1.1.6.25 = STRING: "powered on"
SNMPv2-SMI::enterprises.6876.2.1.1.8.14 = STRING: "not running"
SNMPv2-SMI::enterprises.6876.2.1.1.8.16 = STRING: "running"
SNMPv2-SMI::enterprises.6876.2.1.1.8.21 = STRING: "not running"
SNMPv2-SMI::enterprises.6876.2.1.1.8.23 = STRING: "running"
SNMPv2-SMI::enterprises.6876.2.1.1.8.25 = STRING: "not running"
SNMPv2-SMI::enterprises.6876.2.1.1.9.14 = INTEGER: 2
SNMPv2-SMI::enterprises.6876.2.1.1.9.16 = INTEGER: 1
SNMPv2-SMI::enterprises.6876.2.1.1.9.21 = INTEGER: 2
SNMPv2-SMI::enterprises.6876.2.1.1.9.23 = INTEGER: 2
SNMPv2-SMI::enterprises.6876.2.1.1.9.25 = INTEGER: 2
SNMPv2-SMI::enterprises.6876.2.1.1.10.14 = STRING: "564d802f-3af7-fa6d-0d25-61ef3003079f"
SNMPv2-SMI::enterprises.6876.2.1.1.10.16 = STRING: "564dc5fa-7202-4056-0f0e-7edd794244bc"
SNMPv2-SMI::enterprises.6876.2.1.1.10.21 = STRING: "564d401c-dcdd-c518-d2f9-c8cc3324901f"
SNMPv2-SMI::enterprises.6876.2.1.1.10.23 = STRING: "564dd9b0-c269-ce6f-6e76-b2f7f8c2e1d2"
SNMPv2-SMI::enterprises.6876.2.1.1.10.25 = STRING: "564dcd2c-8821-c501-7305-26d8076bb8ab"

if I placed the same oid in telegraf conf file like below
[[inputs.snmp.table]]
   name = "vmwVmTable"
 inherit_tags = [ "hostname" ]
   oid = "1.3.6.1.4.1.6876.2.1"
   [[inputs.snmp.table.field]]
    name = "Vmstate"
     oid = "1.3.6.1.4.1.6876.2.1.1.6"
the output is :

2018-01-30T08:23:26Z E! initializing table vmwVmTable: getting table columns: exit status 1: Was that a table? SNMPv2-SMI::enterprises.6876.2.1

can i know the procedure to resolve this error and how can i specify the vmwVmTable oid in telegraf conf file. (edited)

**Comment by danielnelson** [comment]
I think you need the MIB for this table available, there is a bit of info about this under [mib-lookups](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp#mib-lookups).

Ultimately you will need this command to return successfully:
```
snmptable -Ch -Cl -c public 127.0.0.1 SNMPv2-SMI::enterprises.6876.2.1
```

**Comment by phemmer** [comment]
maybe we could add some debug logging (which has to be explicitly enabled) to the plugin that would dump the commands being run.

In this case it's actually 2 commands that are failing. The first command is

    snmptranslate -Td -Ob -m all 1.3.6.1.4.1.6876.2.1

This is is being performed since a numeric OID was given, and it tries to resolve this to a textual OID for the call to `snmptable`.
The second command is the one already indicated where it uses the output of the first command as the OID argument:

    snmptable -Ch -Cl -c public 127.0.0.1 SNMPv2-SMI::enterprises.6876.2.1

The output message shows that it used `SNMPv2-SMI::enterprises.6876.2.1` in the call to `snmptable` meaning the first command couldn't resolve the actual MIB & name (which should be `VMWARE-VMINFO-MIB::vmwVmTable`).
The root of the issue is basically that the `VMWARE-VMINFO-MIB` MIB is not present on the system. As an alternative to installing the MIB, you can explicitly define the table structure, but you need some sort of key (tag) for the table (in this case, you likely want the `vmwVmDisplayName` OID) so you can identify what each row is. See this example in the [plugin documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp#mib-lookups):

```
  [[inputs.snmp.table]]
    name = "remote_servers"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "server"
      oid = ".1.0.0.0.1.1"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "connections"
      oid = ".1.0.0.0.1.2"
    [[inputs.snmp.table.field]]
      name = "latency"
      oid = ".1.0.0.0.1.3"
      conversion = "float"

```

**Comment by salmajohnysk** [comment]
I have executed the below command 
snmptable -Ch -Cl -c public 127.0.0.1 SNMPv2-SMI::enterprises.6876.2.1

the result is like 
Was that a table? SNMPv2-SMI::enterprises.6876.2.1

how can i enable  SNMPv2-SMI::enterprises.6876.2.1 to be a table in telegraf conf file to get the data.

**Comment by danielnelson** [comment]
@salmajohnysk Were you able to get your MIB installed?

**Comment by danielnelson** [comment]
I think this question was resolved.
