### ISSUE TITLE
Telegraf service stops by itself on windows server

### ISSUE THREAD

**Issue by Passpes** [influxdata/telegraf#3733]
I installed Telegraf on Windows Server 2012 R2, the service works for few days and then stops by itself, any clue how to fix/debug this issue?

**Comment by kerams** [comment]
Did the server restart during that time?

**Comment by Passpes** [comment]
No it didin't

**Comment by phlipse** [comment]
Could you see any issues in your logfile when it stops?

Configure logging:
```
debug = true
logfile = "<PATH_TO_LOGFILE>"
```
*Be sure you have an eye on your disk space because of high log volume.*

**Comment by kerams** [comment]
@santakd #3601

**Comment by danielnelson** [comment]
@Passpes Have you tried @phlipse's suggestion on the logfiles?  If you still can't see any problems let me know and we will reopen this issue.
