### ISSUE TITLE
pull windows host server metrics using Telegraf inside docker 

### ISSUE THREAD

**Issue by ywang412** [influxdata/telegraf#3735]
I found we can only use telegraf container to collect linux host metrics as follows. 
docker run \
  -v /sys:/rootfs/sys:ro \
  -v /proc:/rootfs/proc:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /var/run/utmp:/var/run/utmp:ro \
  telegraf

Can we do the same thing on windows host?

Thanks!

## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
@ywang412 Not sure, it would depend on what type of containers you are running (Windows or Linux) and what plugins you would like to work.  I suspect most of the Windows plugins such as win_perf_counters would not work using this method.

It would probably be best to ask over at the [InfluxData Community](https://community.influxdata.com) site.
