### ISSUE TITLE
SMART metrics not send to output plugins

### ISSUE THREAD

**Issue by deric** [influxdata/telegraf#3737]
Metrics from `smart` input are not being transfered to InfluxDB.

### Relevant telegraf.conf:

```
[[inputs.smart]] 
```

### System info:

```
Telegraf v1.5.1 (git: release-1.5 0605af7c)
```
Debian 9

### Steps to reproduce:
smart plugin collects data
```
telegraf -config /etc/telegraf/telegraf.conf -test -input-filter smart
* Plugin: inputs.smart, Collection 1
> smart_device,device=sdb,model=Crucial_CT275MX300SSD1,enabled=Enabled,host=m01,serial_no=16441482D936,wwn=500a07511482d936,capacity=275064201216 read_error_rate=0i,temp_c=35i,udma_crc_errors=0i,exit_status=0i,health_ok=true 1517414964000000000
> smart_device,model=Crucial_CT275MX300SSD1,enabled=Enabled,device=sda,wwn=500a0751148297cb,capacity=275064201216,host=m01,serial_no=1644148297CB exit_status=0i,health_ok=true,read_error_rate=0i,temp_c=36i,udma_crc_errors=0i 1517414964000000000
```
this appears to be ok.
Now when I'm greping data from network `ngrep -l -q "" -W byline tcp port 8086`:

```
smart_device,host=m01,device=sda exit_status=2i 1517415100000000000
smart_device,device=sdb,host=m01,role=master exit_status=2i 1517415100000000000
```
### Expected behavior:

I'd expect to see all attributes collected by smart plugin, like: 
```
temp_c=36i,udma_crc_errors=0i
```
### Actual behavior:

The only metric being reported to Influx is `exit_status`. No other SMART data.

**Comment by danielnelson** [comment]
It looks like `smartctl` is returning an error when Telegraf if ran as a service, since it works in interactive mode it is probably related to how the service runs as the `telegraf` user.  Make sure this user has permission to execute smartctl, perhaps you just need to add `use_sudo = true` and setup passwordless execution in your sudoers file?

**Comment by deric** [comment]
Right, I was running the config test as root. Mine fault, I should have checked telegraf logs first. Sorry to bother you with this.
