### ISSUE TITLE
Add capacity to force fathering of a metrix by sending a socket message to telegraf process

### ISSUE THREAD

**Issue by avermeer** [influxdata/telegraf#3749]
## Feature Request

Add capacity to force fathering of a metrix by sending a socket message to telegraf process

### Proposal: 

  Lots of monitoring system have a way to "force recheck" of a probe from their UI (think about the good old Centreon). To make telegraf compliant with this, my proposal is to allow sending a small message to the running telegraf process through the same socket which allows sending metrics using 'nc'. 
  This message must allow telling which metric(s) need to be immediately gathered. 
  The impact of this  action on involved metrics gathering could be: either we keep initially defined interval of gathering since telegraf startup, either we consider that subsequent checks time should be relative to forced gathering (either way would be ok for me).
  
### Current behavior:

With current telegraf behavior, the only way to 'force gathering' of a given metric is to restart telegraf process. However, restarting telegraf will for gathering not only of the desired metrics, but of *all* metrics configured for this telegraf process. This can be overkill when a telegraf process is configured to run some expensive gathering which are supposed to be called at long interval rate (think about some  expensive to collect usage metrics that should be collected only once per hour...)

### Desired behavior:

Telegraf should propose a way to force gathering of a given set of metrics.

### Use case: [Why is this important (helps with prioritizing requests)]

  Once telegraf process is started, the metrics are gathers at interval of times defined in the configuration. However, my experience of real-time supervision is that some metrics can be collected with relatively slow intervals (say 5 minutes) because the involved check is expensive.

  When an alert is triggered by such metric, the operator who fixed the issue usual wants to "force gathering of the metric" so as to quickly check that the alert is gone (think about an on-call at 3:00am: trust me in this case you want to go back to sleep ASAP, 5 minutes is *forever* ;)

  Without this feature, I think telegraf is OK for use in a pure metrics collecting solution for graphing or for usage metering, but it's not quite fit as metrics source for alerting purposes, which is too bad since it has nice plug-ins on system, database, etc.

**Comment by powersj** [comment]
Hi,

Sorry no one has commented on this before.

This is an interesting use case. Have you considered running SIGHUP against the telegraf processes to start things again? This would essentially do what you are asking for already. As you said, you may have some metrics that are expensive to collect and the SIGHUP option would still collect all of them. 

We have had discussions and some planning around adding an API to telegraf to allow users to make configuration changes and control telegraf. This request could fall in line with that solution, but that is a ways out.

Thoughts?

Thanks
