### ISSUE TITLE
[AMQP Consumer - Plugin] Allow to turn on exchange passive mode

### ISSUE THREAD

**Issue by mschnitzer** [influxdata/telegraf#3785]
## Feature Request

I'd like to see an option to turn on the `passive` mode for the RabbitMQ consumer exchange. I actually implemented it already for myself: https://github.com/mschnitzer/telegraf/commit/95fb3f32d0237a1d1725137089753162d43278e4

I grant you permission on this code and you can use it if you want, but I'm definitely not willing to sign that CA... That was the only reason why I didn't open a PR.

### Use case:

Some RabbitMQ Servers (like for example the openSUSE ones) require the passive mode to be set in order to consume messages.

**Comment by danielnelson** [comment]
We will add this as a feature request.

If you can elaborate on which parts of the CLA are problematic for you I can point our legal guys at this issue and perhaps we can address it.

**Comment by danielnelson** [comment]
Added for 1.7, thanks @gentstr #3995
