### ISSUE TITLE
Get total memory on Windows

### ISSUE THREAD

**Issue by emexelem** [influxdata/telegraf#3787]
I'm trying to figure out how we can get directly or compute the total memory available on a Windows system.
I'm using the [default configuration for Windows](https://github.com/influxdata/telegraf/blob/master/etc/telegraf_windows.conf) and enabled inputs.win_perf_counters.object.IncludeTotal but could not find how to get this information.

**Comment by kerams** [comment]
There does not appear to be a way to do that (https://serverfault.com/a/377941/188824).

Also, setting `IncludeTotal` to `true` has no effect here because none of the counters in the Memory category have any instances, let alone any called `_Total`.

**Comment by danielnelson** [comment]
Does the mem plugin do this correctly on Windows?
```toml
[[inputs.mem]]
  # no configuration
```

**Comment by kerams** [comment]
Hm, for some reason I thought `inputs.mem` did not work on Windows. You're right though, it does report the correct total.

**Comment by emexelem** [comment]
`inputs.mem` makes use of WMI, which has `wmic ComputerSystem get TotalPhysicalMemory` but according to the comments in the config file
`# Windows Performance Counters plugin.
# These are the recommended method of monitoring system metrics on windows,
# as the regular system plugins (inputs.cpu, inputs.mem, etc.) rely on WMI,
# which utilize more system resources.`

**Comment by danielnelson** [comment]
I think I will close this issue, we could open another if there is another option for getting this information.  I'd be interested to hear how well the plugin works in practice for you though.

**Comment by eclements** [comment]
@danielnelson I also came across this problem today for windows monitoring with Telegraf + perfmon collectors. I can only report "available memory" but not what the total memory on the server is, or what percentage of total memory is free. Any suggestions? I also can't seem to show accurately the total memory used... in my case I have 160GB ram, with 100GB of memory usage not showing, but I can see there is 60GB free in the graph but no way to show that 100GB is in use.

![image](https://user-images.githubusercontent.com/1571140/86605024-7369a080-bfa6-11ea-8302-d275d397773a.png)

**Comment by danielnelson** [comment]
Give the `mem` input a second try, it no longer uses WMI and should be more suitable for use.
