### ISSUE TITLE
allow case-insensitive boolean expressions

### ISSUE THREAD

**Issue by rdxmb** [influxdata/telegraf#3792]
This is a feature request.

input.plugins like http_response use boolean expressions like
```
follow_redirects = true
follow_redirects = false
```

When generating config from templates like [jinja](http://jinja.pocoo.org/) , the boolean variable is written with a capital letter
```
follow_redirects = True
follow_redirects = False
```

As this is not allowed in telegraf, an error occurs.
If 'True' and 'False' were also allowed, that would be great.

### System info:

telegraf 1.5

**Comment by danielnelson** [comment]
Unfortunately we can't do this, the config file is in TOML and it requires lowercase booleans: https://github.com/toml-lang/toml#boolean

**Comment by rdxmb** [comment]
ok, get fixed this with parsing the bool-variables with strings in my yaml/jinja-templates. Thanks for your response!
