### ISSUE TITLE
README.md : inputs.http_response : [inputs.http_response.tags] missing

### ISSUE THREAD

**Issue by rdxmb** [influxdata/telegraf#3793]
In https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_response/README.md the option for additional tags with

`[inputs.http_response.tags]`
is missing.

Could you please add it?

**Comment by danielnelson** [comment]
We don't usually specify the options that can be applied to all plugins in the README, but they are documented in https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-configuration

**Comment by rdxmb** [comment]
ok, thanks.
