### ISSUE TITLE
Single config file with selective execution of metrics collection

### ISSUE THREAD

**Issue by networkprogrammer** [influxdata/telegraf#3795]
Hello All,
I am looking for help with a Telegraf deployment that I am working on. We are looking to deploy a single config file that has different urls to collect ping/latency metrics. We will have our Telegraf instances in-house for internal metric collection and externally to collect metrics over the internet.

Part of the input plugin definition looks like this 

[[inputs.ping]]
  urls = ["8.8.8.8"]

[[inputs.ping]]
  urls = ["192.168.1.1"]

I am looking to see if there is a way to have everything in 1 config file, but prevent an external Telegraf instance from running pings to 192.168.1.1 since that is an internal IP and will fail.

Is this possible? If not, any other suggestions? My idea is to maintain multiple config files as adding a new url would mean updating multiple config files.

Thanks!

**Comment by danielnelson** [comment]
Hope you found a good solution, one idea I have is to put the external ping targets in `/etc/telegraf.d/external-ping.conf` but only on the external hosts.
