### ISSUE TITLE
http_response plugin: add option to add details of network errors

### ISSUE THREAD

**Issue by mirath** [influxdata/telegraf#3802]
## Feature Request
The `http_response` input plugin does not log any detail when a connectivity error occurs. If a network error takes place, the only two possible values are `timeout` for timeouts, and `connection_failed` in any other case. This makes understanding and debugging the monitored URL cumbersome if there is a DNS issue, routing error, etc, as the user has to do additional manual tests to determine the precise nature of the problem.

It would be nice if there was an option to add the error string (err.Error()) as a Tag/Field so a time series database and/or dashboard application can show complete information down the line.

### Proposal:
Add a binary option in the `http_response` plugin which, when turned on, would add a Tag/Field with the value of the error string (err.Error()) generated by the net/http client when a connectivity error ocurrs.

### Current behavior:
There is no way to pass the details of a network error to the outputs for further aggregation and debugging

### Desired behavior:
Have a way to pass the details of network errors to the outputs for further aggregation and debugging

### Use case: [Why is this important (helps with prioritizing requests)]
During an outage, having a useful hint of the nature of the network error (DNS, routing, timeout, no network configure) in the time series database and/or dashboard application can save precious minutes of debugging.

**Comment by mirath** [comment]
If possible, I'm willing to work on this feature

**Comment by danielnelson** [comment]
Instead of sending the raw error string, I think we should continue to detect specific error conditions, this will prevent high variability strings from being inserted into the database.  This could happen if an error message has an address in it.
