### ISSUE TITLE
Memory leak in postgresql_extensible

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#3807]
### Relevant telegraf.conf:
```
[[postgresql_extensible]]
[[inputs.postgresql_extensible.query]]
    sqlquery="SELECT 1"
```

### System info:
telegraf 1.5.2

### Steps to reproduce:

1. run telegraf
2. for a long time

### Expected behavior:
Memory usage to be stable

### Actual behavior:
Memory usage grows unbounded over time

### Additional info:
The issue is due to [line 186](https://github.com/influxdata/telegraf/blob/1.5.2/plugins/inputs/postgresql_extensible/postgresql_extensible.go#L186).
This has already been addressed by #2701, but since this change was a feature, and not targeted specifically at this issue, it will not be present until the next major release (1.6). I'm not sure what the timeframe is for 1.6, but if there are going to be any further 1.5 releases, I think a fix for this issue should be included. The fix is as simple as `p.AllColumns = nil` at the top of the `Gather()` func.

**Comment by danielnelson** [comment]
I added this, can you check it?  https://github.com/influxdata/telegraf/commit/8147d609730c0265be477c79d077e8ea05bc956b

I'm going to be out of office after wednesday for the next week so I will probably do 1.5.3 early March.

**Comment by phemmer** [comment]
I think you linked the wrong commit. d8dae1b looks to be the right one, and  yeah, that should do it. Thanks :-)
We put a cgroup memory limit on telegraf so it gets killed if it uses more than 128mb. Dirty, but will hold us over until the next release.

Thanks
