### ISSUE TITLE
procstat support for multiple users

### ISSUE THREAD

**Issue by ghost** [influxdata/telegraf#3815]
### Proposal:
Enhance the procstat plugin to accept multiple user IDs to use for process searches.

### Current behavior:
The user conf variable only accepts a single user name.

### Desired behavior:
The user conf could accept multiple user names e.g. a comma delimited list.

### Use case: [Why is this important (helps with prioritizing requests)]
This would allow for a more compact configuration for the procstat plugin, the current workaround involves specifying a procstat conf block for each desired user account.

**Comment by mcummingscb** [comment]
FWIW, this shouldn't be too hard to implement and I may go ahead and do it at some point, I just don't have the bandwidth to do it now.

**Comment by danielnelson** [comment]
You can actually do this like: `user = "telegraf,root"`, when using the default `pid_finder = "pgrep"`.  The values are passed directly to pgrep.

We should still add support for a list of users: `users = ["telegraf", "root"]`

**Comment by mcummingscb** [comment]
Nice, thanks @danielnelson!

**Comment by MyaLongmire** [comment]
Sorry, no one has gotten back to you.

Since there seems to be a workaround for this, I will go ahead and close it.
