### ISSUE TITLE
inputs.ping

### ISSUE THREAD

**Issue by doanerock** [influxdata/telegraf#3816]
Bug report

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf v1.5.2 (git: release-1.5 67440c95)
InfluxDB starting, version 1.4.2, branch 1.4
Red Hat Enterprise Linux Server release 7.4 (Maipo)

### Steps to reproduce:
1. put hosts in inputs,ping
1. have some of the hosts, time out and not respond.  
2. receive errors that are ambiguous.  

### Expected behavior:
2018-02-12T15:48:15Z E! Error in plugin [inputs.ping]: Command timed out. Host xxx, xyz, abc timed out

(eg list with hosts caused the inputs.ping plugin to error out)

### Actual behavior:
2018-02-12T15:48:15Z E! Error in plugin [inputs.ping]: Command timed out.

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

have the log give more details the inputs.ping plug which hosts are causing issues.  

### Proposal:
give more details about inputs.ping when there are issues, not just "Command timed out."

### Desired behavior:
more detail info about what the actual issue is.

### Use case: [Why is this important (helps with prioritizing requests)]
I can not make proper decisions when I am given bad data.and influxdb is all about good data.

really need to say which hosts are erroring out in the log and why.

**Comment by danielnelson** [comment]
Added to 1.6
