### ISSUE TITLE
Configuration for location of certs of postgres in ssl with CA mode 

### ISSUE THREAD

**Issue by nishanthmehta** [influxdata/telegraf#3817]
Hi Team

I am trying to configure my postgres in ssl mode with client authentication
But In the telegraf configuration I am unable to see any setting which specify the location of the client cert key
Does the plugin support postgres in ssl mode with client authentication

**Comment by suckatrash** [comment]
I'm looking for info on this too

**Comment by danielnelson** [comment]
I believe these options must be set via the connection string via the `address` option.  I have not tested it myself but the locations appear to be defined in https://www.postgresql.org/docs/9.4/libpq-connect.html#LIBPQ-PARAMKEYWORDS under `sslkey`, `sslcert`.

Telegraf's home directory may be different depending on the package you are using.  I don't recommend relying on it, and would instead use absolute paths to these files.  It should look something like this:
```
address = "host=localhost user=postgres sslmode=require sslkey=/etc/telegraf/postgresql.key sslcert=/etc/telegraf/postgresql.crt"
```

Make sure you have the correct permissions on these files, on Linux the `telegraf` user will need read access.

I haven't tested this myself though, could you let me know if that does the trick so we can add it to the plugin documentation?

**Comment by suckatrash** [comment]
Is it possible that the telegraf input isn't parsing the `sslcert` option correctly?

I get the same error with the psql client if I leave it out:

```
psql "host=pe-201813-master.puppetdebug.vlan user=telegraf dbname=pe-puppetdb sslmode=require sslkey=/etc/telegraf/grafana-server.platform9.puppet.net.private_key.pem sslrootcert=/etc/telegraf/ca.pem"
psql: FATAL:  connection requires a valid client certificate
```

**Comment by danielnelson** [comment]
It looks like we need to update pgx to 3.2.0 for this support  https://github.com/jackc/pgx/commit/8078930406ebb0b7f182df3c9c0dfa23d133812e

I can open a PR with the updated version for testing
