### ISSUE TITLE
Telegraf stopped after reboot Windows PC.

### ISSUE THREAD

**Issue by andryua** [influxdata/telegraf#3821]
Hi!
Telegraf (Telegraf 1.5.2 (Windows 64bit all version)) stopped after reboot Windows PC. Is it normal?

Service can't start if using net start (only on second time)!!!

How I can resolve this issue (or when You resolve this issue)?

**Comment by niphlod** [comment]
seems like a duplicate of https://github.com/influxdata/telegraf/issues/3601 . definitely something to look at a high prio for the new release
