### ISSUE TITLE
JSON serializer should include metric "type"

### ISSUE THREAD

**Issue by amoghe** [influxdata/telegraf#3827]
Currently various output plugins can choose `json` as their serializer to emit messages. However the output from the `json` serializer does not include the type information of the metric. It should be trivial to emit this information in the output.

If there is no objection, I'd be happy to open a PR for this.

**Comment by amoghe** [comment]
First pass: https://github.com/influxdata/telegraf/pull/3834

**Comment by sjwang90** [comment]
@amoghe Looks like this issue and PR have been pretty stale for awhile. Closing this for now, feel free to reopen if you'd like to continue to work on this.
