### ISSUE TITLE
Add Graphite Tag support

### ISSUE THREAD

**Issue by eMerzh** [influxdata/telegraf#3830]
## Feature Request

Since latest versions (1.1) graphite support tags , it would be cool if telegraf support them as they might be a good way to structure your metrics and it might be closer to what influx and friends are doing.

http://graphite.readthedocs.io/en/latest/tags.html

**Comment by 6d6178** [comment]
I would also love to see this implemented, especially because telegraf already has a tagging system in place.

**Comment by R4scal** [comment]
I was opened PR https://github.com/influxdata/telegraf/pull/4165. This is a concept that working for me. Any feedback is welcomed

**Comment by danielnelson** [comment]
Thanks @R4scal, support will be in 1.7.

**Comment by gena01** [comment]
Am i reading this wrong that this only adds support for the "output" side of Telegraf. Anyway to parse these on the input side?

**Comment by danielnelson** [comment]
@gena01 That's a good point, could you open a new feature request specifically for the graphite input data format?
