### ISSUE TITLE
Logparser reparses file from beginning if permissions are changed

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3831]
## Bug report

When a permission is changed on a logfile, the log parser plugin will reprocess the entire file.

### System info:

Telegraf 1.5.2

### Steps to reproduce:

1. start tailing a logfile
2. chmod +x logfile

### Expected behavior:

Nothing happens

### Actual behavior:

Entire input file is reparsed

**Comment by mbliznikova** [comment]
Hi everyone, 
I could reproduce the bug and will try to fix it.

**Comment by mbliznikova** [comment]
Pull request with fix: https://github.com/influxdata/tail/pull/5

**Comment by mbliznikova** [comment]
@danielnelson can you please review?

**Comment by danielnelson** [comment]
I have updated the tail with the fix for 1.6
