### ISSUE TITLE
Allow configuring TLS renegotiation in http_response input

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3832]
### Proposal:

Allow configuration of the TLS renegotiating support in the http_response plugin

### Current behavior:

Uses the default Go behavior which is:
```
// Renegotiation controls what types of renegotiation are supported.
// The default, none, is correct for the vast majority of applications.
Renegotiation RenegotiationSupport
```

### Desired behavior:

Allow enabling renegotiation when needed.

### Use case:

Systems that require renegotiation support cannot be used without changing this setting.

**Comment by powersj** [comment]
next steps: determine options for this configuration value and more use-cases

**Comment by shriramb380** [comment]
@powersj Orange has raised this and wanted to know if this can be prioritised in the coming releases. Let me know if you have any ETA. Thanks
https://influxdata.lightning.force.com/lightning/r/Case/5001S00001dETxEQAW/view
