### ISSUE TITLE
Telegraf dependency to shadow-utils not appropriate for Suse 12.3

### ISSUE THREAD

**Issue by ReinhardWalden** [influxdata/telegraf#3833]
## Bug report

The installation of telegraf  fails on Suse 12.3 (Enterprise) due to a dependency issue. Recent telegraf versions require shadow-utils, and this package does not exist in Suse 12.3.

The installation can be forced (rpm -i --nodeps telegraf-...), and then telegraf worked well for me. So I suspect that the dependency is not required for Suse12.3. I suspect that telegraf wants to ensure that useradd is available, and this in Suse12.3 is part of the shadow package.

So I think that the dependency list for Suse should be modified. For RHEL/CentOS it was OK for me. 

### Relevant telegraf.conf:
n/a

### System info:

Tested with telegraf-1.5.0-1.x86_64.rpm and telegraf-1.5.2-1.x86_64.rpm. Worked with CentOS/RHEL 7.4, but failed with SUSE Linux Enterprise Server 12 patchlevel 3. I did not test older Suse versions.
 

### Steps to reproduce:

suse1:/tmp # zypper install /tmp/telegraf-1.5.2-1.x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides shadow-utils needed by telegraf-1.5.2-1.x86_64
 Solution 1: do not install telegraf-1.5.2-1.x86_64
 Solution 2: break telegraf-1.5.2-1.x86_64 by ignoring some of its dependencies
...

### Expected behavior:

Clean installation not requiring to ignore a (false?) alarm about the dependency

### Actual behavior:

see above.

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by adrianlzt** [comment]
Related with PR https://github.com/influxdata/telegraf/pull/3505 and issue https://github.com/influxdata/telegraf/issues/3447

**Comment by adrianlzt** [comment]
Workaround:
```
github.com/influxdata/telegraf $ diff scripts/build.py scripts/build_suse.py
649c649
<                             fpm_command += "--depends coreutils --depends shadow-utils --rpm-posttrans {}".format(POSTINST_SCRIPT)
---
>                             fpm_command += "--depends coreutils --depends shadow --rpm-posttrans {}".format(POSTINST_SCRIPT)
```

**Comment by rjkrish** [comment]
Im having the same issue ( for influxdb and kapacitor as well ). Im installing on a custom distro and the shadow-utils dependency is getting in the way.

**Comment by danielnelson** [comment]
As a workaround you can install with no dependencies:
```
sudo rpm -i --nodeps telegraf-1.7.2-1.x86_64.rpm
```

**Comment by chrmeyer** [comment]
Same on Suse 15/SLE15

**Comment by alpi-ua** [comment]
Faced the same issue in Aug 2020 on Suse 42.2

This repo is fixing the issue https://software.opensuse.org//download.html?project=home%3ABerlinOnline%3Atelegraf&package=shadow-utils

**Comment by sjwang90** [comment]
@alpi-ua Is this fix dependent on https://software.opensuse.org//download.html?project=home%3ABerlinOnline%3Atelegraf&package=shadow-utils?

**Comment by srebhan** [comment]
@ReinhardWalden, @alpiua, @chrmeyer, @rjkrish, @adrianlzt is this still an issue?

**Comment by adrianlzt** [comment]
Yes, it is still an issue:
```
➜ podman run --rm -it docker.io/opensuse/leap:latest zypper in https://dl.influxdata.com/telegraf/releases/telegraf-1.27.0-1.x86_64.rpm
Retrieving repository 'Update repository of openSUSE Backports' metadata ...............................................................................................................[done]
Building repository 'Update repository of openSUSE Backports' cache ....................................................................................................................[done]
Retrieving repository 'Non-OSS Repository' metadata ....................................................................................................................................[done]
Building repository 'Non-OSS Repository' cache .........................................................................................................................................[done]
Retrieving repository 'Open H.264 Codec (openSUSE Leap)' metadata ......................................................................................................................[done]
Building repository 'Open H.264 Codec (openSUSE Leap)' cache ...........................................................................................................................[done]
Retrieving repository 'Main Repository' metadata .......................................................................................................................................[done]
Building repository 'Main Repository' cache ............................................................................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ..........................................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache ...............................................................................................[done]
Retrieving repository 'Main Update Repository' metadata ................................................................................................................................[done]
Building repository 'Main Update Repository' cache .....................................................................................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata ...........................................................................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'shadow-utils' needed by the to be installed telegraf-1.27.0-1.x86_64
 Solution 1: do not install telegraf-1.27.0-1.x86_64
 Solution 2: break telegraf-1.27.0-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):

```

**Comment by ReinhardWalden** [comment]
The issue persistent, but we have an easy workaround. Thus it is not worth
fixing.

Sven Rebhan ***@***.***> schrieb am Di. 20. Juni 2023 um
15:46:

**Comment by powersj** [comment]
> The issue persistent, but we have an easy workaround. 

What is the workaround you are using? I would like to be able to test SuSE in our [LXD package tests](https://github.com/influxdata/telegraf/blob/master/tools/package_lxd_test/main.go#L18-L19), but this issue is the blocker.
