### ISSUE TITLE
mem stats are of type counter (instead of gauge)

### ISSUE THREAD

**Issue by amoghe** [influxdata/telegraf#3835]
### Steps to reproduce:

1. Start telegraf with `[[inputs.mem]]`
2. Observe that mem stats like "total", "available", "used" are all added using  `AddCounter`

### Expected behavior:
I expected these to be Gauges, since they are absolute utilization numbers

Maybe I'm missing context on why these have the Counter type. I could work on adding a note to the README if needed to clarify this.

**Comment by amoghe** [comment]
@sparrc , looks like this was added in b18d375d6c . But the commit message doesn't indicate why a counter was chosen as the type for this (and other) metrics.

I notice that `swap` plugin differentiates between emitting its gauges and counters (emitting both, depending on the metric). Maybe thats the right approach for the `mem` plugin as well? (Unless I've misunderstood something)

**Comment by danielnelson** [comment]
Looks like a bug to me, we can change those fields to be Gauges.

**Comment by amoghe** [comment]
I can take a stab at this, if you'd like.

**Comment by danielnelson** [comment]
Sure, thanks
