### ISSUE TITLE
Add NATS Streaming Input

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#3842]
### Proposal:
Add the ability to read messages from the NATS streaming server. https://github.com/nats-io/go-nats-streaming

**Comment by russorat** [comment]
https://github.com/influxdata/telegraf/pull/3706

**Comment by danielnelson** [comment]
Just to clarify, 3706 is an output.

**Comment by powersj** [comment]
As the PR was closed a well, I am going to close this feature request for now. If anyone is interested in the future, please put up a PR and we can re-open this issue.

Thanks!
