### ISSUE TITLE
Telegraf allows precision per input rather than a global agent config

### ISSUE THREAD

**Issue by tokenrain** [influxdata/telegraf#3843]
## Feature Request

Telegraf allows precision per input rather than a global agent config

### Proposal:

Allow a precision config line in each input config. At a minimum allow the exec input plugin to set precision.

### Current behavior:

precision is set globally for the telgraf agent

### Desired behavior:

precision can set for each input individually or at a minimum for each exec input.

### Use case: 

I am using the telegraf exec input plugin to send some process list to influx and in order to keep the series number low I have a small tag set that initially was overwriting values where there were multiple process of the same name in a single ps listing. I got around that by changing the telegraf agent config to specify microsecond resolution and add 1 us to every point I write in the script that I us to report ps stats.

This is great expect for the fact that I am not using significantly more disk space because precision is global on telegraf and all my input agents have moved from 1s precision to 1us precision. I do not need more than 1s precision expect for this one case.

I think it would be very useful for telegraf to all the precision to be specified on a per input basis rather than a global telegraf basis such that we maximize the efficiency of disk space as we find more and more use cases for telegraf data that may have very different precision requirements.

https://community.influxdata.com/t/telegraph-precision-per-input/4105

**Comment by Alestrix** [comment]
So much this! Because of a single input I now need to increase the global precision setting, causing influxdb to eat up more disk space..

**Comment by danielnelson** [comment]
Closed in #7762
