### ISSUE TITLE
SQL Plugin: field corresponding to 'query_version' is not defined in '*sqlserver.SQLServer'

### ISSUE THREAD

**Issue by cofonseca** [influxdata/telegraf#3846]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
I'm monitoring a Microsoft SQL Server instance. I would like to use the new query version 2 to collect cleaner measurements, because version 1 is cluttered. If I add query_version = 2 to my config, I receive an error:

2018/02/28 13:19:37 E! Error parsing .\telegraf.conf, line 279: field corresponding to `query_version' is not defined in `*sqlserver.SQLServer'

### Relevant telegraf.conf:
[[inputs.sqlserver]]
  servers = ["Server=10.100.116.23;Port=1433;User Id=user;Password=password;log=1;"]
  query_version = 2

### System info:
Telegraf v1.5.2
Windows Server 2012 R2

### Steps to reproduce:

1. Add "query_version = 2" to your [[inputs.sqlserver]] config
2. Attempt to run Telegraf

### Expected behavior:
Telegraf should run, and collect data using the new query version.

### Actual behavior:
Telegraf errors out immediately, and does not start.

**Comment by kerams** [comment]
This is part of the yet unreleased 1.6.0. Download the nightly if you want to use query v2 right now.

**Comment by cofonseca** [comment]
@kerams ah, thank you. I didn't realize that. I did download the nightly and query v2 worked perfectly. Thank you for the reply!
