### ISSUE TITLE
Unable to override some settings in /etc/init.d/telegraf

### ISSUE THREAD

**Issue by bmailhe** [influxdata/telegraf#3849]
I override vars `config` and `configdir` in file `/etc/default/telegraf` but they're not taken into account when I restart the service.

### System info:
**version**: telegraf-1.5.2-1.x86_64
**OS** : CentOS release 6.9 

### Steps to reproduce:
Set a new value for var `configdir` in `/etc/default/telegraf` and restart, it is not used.

### Expected behavior:
Be able to override "config" and "configdir" in  `/etc/default/telegraf` 

### Actual behavior:
Only possible to override `TELEGRAF_OPTS`, `USER` and `GROUP` in  `/etc/default/telegraf` 

### Proposal:
Move the section sourcing  `/etc/default/telegraf`  after the variables declaration.

### Use case: 
I want to be able to move the configuration file and directory to another location without modifying the file `/etc/init.d/telegraf`

**Comment by danielnelson** [comment]
Can you add more details about why you want to change the configuration file and directory?

**Comment by danielnelson** [comment]
Closing due to lack of details.
