### ISSUE TITLE
Feature request for SSL 2 Way [[inputs.ssl]]

### ISSUE THREAD

**Issue by fchiorascu** [influxdata/telegraf#3854]
## Bug report
Feature request for [[inputs.ssl]]

### System info:
Centos 7.3
telegraf 1.5.2
influxdb 1.4.3

### Steps to reproduce:
1. ...
2. ...

### Expected behavior:
To monitor ssl **vs** ssl 2 way if possible when you have in a project two components that have certificates and needs to communicate each other.

### Actual behavior:
-
### Additional info:
-

## Feature Request

Kindly if possible to have an inputs for ssl vs ssl 2 way.

**Comment by danielnelson** [comment]
I don't understand what you would like this plugin to do, can you add more information?

**Comment by fchiorascu** [comment]
Hi Daniel,

The main scope in order to have this compared with Centreon, Nagios monitoring tools and others is the best way to have certificates details and to observe that the certificates applied as "ssl" or "ssl 2 way" are healthy from format point of view, they are not expired and most important in a platform where the communication between many components that have applied on their side a certificate ssl 2 way the communication works fine without loosing any pkt's between that components and in this way there is a need to have an [[inputs.ssl]] that will cover "ssl" certificates or "ssl 2 way" to have metrics that are ok as health, not expired, details about them self signed or not and other aspects if intermediate cert or additional infos, also to detect if they are working fine authorizing the communication proper if there could be implemented a way in telegraf to detect this.

Kind Regards,

**Comment by danielnelson** [comment]
Got it, by the way we have a couple pull requests right now that are similar, but they don't do 2-way validation, so we will have to make sure this functionality is added:
- https://github.com/influxdata/telegraf/pull/3829
- https://github.com/influxdata/telegraf/pull/3768

**Comment by fchiorascu** [comment]
Thank you Daniel.
Sounds great.

**Comment by fchiorascu** [comment]
Hi Daniel. Any news for this one? I'm very interested in having it. :)

**Comment by danielnelson** [comment]
Just keep an eye on those two PRs, I'm still hoping this feature will make sense as part of a general certificate plugin.

**Comment by fchiorascu** [comment]
Hi Daniel, for sure will make sense. Is widely used as ssl or ssl2way and the need for this plugin in any decent monitoring tool is huge base on the fact that you will use a certificate or multiple certificates in Production for sure.

Thank you.

**Comment by sjwang90** [comment]
Check out `inputs.x509_cert`. Closing issue.
