### ISSUE TITLE
How Can We build this project in China?

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#3860]
Just github is allowed in China.
But we use gdm.
And packages from google.org and gopkg.in.
It's every hard to make this package in China.

**Comment by danielnelson** [comment]
You might be able to gather the packages manually, all of these are available on github.  For example, collectd.org is a vanity url to https://github.com/collectd/go-collectd.  Other packages such as golang.org/crypto have mirrors that you can search for.  Put the files in the correct location so they can be imported and you should be able to build with `make telegraf` to skip any network steps.
