### ISSUE TITLE
While using the netstat plugin: Root dentry has weird name <>

### ISSUE THREAD

**Issue by jcberthon** [influxdata/telegraf#3865]
## Bug report

Every 10s, journald gets a Kernel error similar to this:

```
Mar 07 13:09:50 localhost kernel: ------------[ cut here ]------------
Mar 07 13:09:50 localhost kernel: WARNING: CPU: 3 PID: 116062 at fs/dcache.c:2852 prepend_path+0x25f/0x320
Mar 07 13:09:50 localhost kernel: Root dentry has weird name <>
Mar 07 13:09:50 localhost kernel: Modules linked in: macvlan dummy binfmt_misc cfg80211 rfkill veth xt_nat ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink xt_ad
Mar 07 13:09:50 localhost kernel:  crc32_pclmul ghash_clmulni_intel aesni_intel lrw gf128mul glue_helper ablk_helper cryptd iTCO_wdt iTCO_vendor_support mxm_wmi dcdbas pcs
Mar 07 13:09:50 localhost kernel: CPU: 3 PID: 116062 Comm: telegraf Tainted: G        W      ------------   3.10.0-693.17.1.el7.x86_64 #1
Mar 07 13:09:50 localhost kernel: Hardware name: unknown
Mar 07 13:09:50 localhost kernel: Call Trace:
Mar 07 13:09:50 localhost kernel:  [<ffffffff816a6071>] dump_stack+0x19/0x1b
Mar 07 13:09:50 localhost kernel:  [<ffffffff810895e8>] __warn+0xd8/0x100
Mar 07 13:09:50 localhost kernel:  [<ffffffff8108966f>] warn_slowpath_fmt+0x5f/0x80
Mar 07 13:09:50 localhost kernel:  [<ffffffff8121bacf>] prepend_path+0x25f/0x320
Mar 07 13:09:50 localhost kernel:  [<ffffffff8121bc75>] d_path+0xe5/0x150
Mar 07 13:09:50 localhost kernel:  [<ffffffff81274ae5>] proc_pid_readlink+0xa5/0x100
Mar 07 13:09:50 localhost kernel:  [<ffffffff81208dab>] SyS_readlinkat+0x10b/0x140
Mar 07 13:09:50 localhost kernel:  [<ffffffff816b89fd>] system_call_fastpath+0x16/0x1b
Mar 07 13:09:50 localhost kernel: ---[ end trace 42d068c5e2f279d7 ]---
```

It seems that telegraf tries to read a FS resource with a weird name. After some dychotomy process, I've managed to singleout the input plugins I was using which is causing these warning from the kernel. It's the `inputs.netstat` "plugin". If I deactivate it, I no longer have the above log message appearing in my system logs. As soon as I activate it, every 10s I get a new instance of this message.

The host system is CentOS 7.4, with all updates applied (as of 2018-03-02, so 5 days ago). I'm running Docker CE 17.12, and I'm using the official telegraf Docker image. The architecture is amd64.

### Relevant telegraf.conf:

```
# # Read TCP metrics such as established, time wait and sockets counts.
[[inputs.netstat]]
   # no configuration
```

### System info:

* CentOS 7.4 w/ Kernel 3.10.0-693.17.1.el7.x86_64
* Docker CE 17.12.0
* telegraf (official image) 1.5.2

### Steps to reproduce:

1. Install CentOS 7.4 + Docker CE stable
2. Create telegraf.conf file, only activate inputs.netstat
3. Run: `docker run -d -v telegraf.conf:/etc/telegraf.conf telegraf:1.5.2`
4. Wait 20 seconds
5. Open the journal: journalctl -rb

### Expected behavior:

No message (as given above as example) shall be printed in the system logs every 10s.

### Actual behavior:

A message is printed every 10s, which render log analysis difficult/noisy.

### Additional info:

Provided above. More can be provided on demand.

**Comment by danielnelson** [comment]
I found this issue: https://bugs.launchpad.net/fuel/+bug/1385755

**Comment by sejur1004** [comment]
i met same issue on my system. 
also system info is same.
i'm looking for solution or reason from this issue. 
i get a not solution now. but i found refer site "https://access.redhat.com/solutions/3356761#"  but it is not perfect solution and i can not understand.
if you have solution of this issue let me know plz

**Comment by danielnelson** [comment]
Thanks for the testing @jcberthon, Let's close this issue with the recommendation to update Centos.
