### ISSUE TITLE
Feature request - inputs.iperf

### ISSUE THREAD

**Issue by Touchedegris** [influxdata/telegraf#3866]
## Feature Request

Would like to see a inputs.iperf plugin to test bandwidth between nodes.

We are monitoring a network with a couple of telegraf probes and we would like to do scheduled speed tests between probes.

The following is inspired by the Iperf3 module written in python.  You can refer to https://iperf3-python.readthedocs.io/en/latest/modules.html

### Proposal:

Configuring Iperf3 client within inputs.iperf

[[inputs.iperf]]
  bandwidth = Target bandwidth in bits/sec
  blksize = The test blksize.
  duration = The test duration in seconds.
  num_streams = The number of streams to use.
  protocol = The iperf3 instance protocol. valid protocols are ‘tcp’ and ‘udp’
  reverse = Toggles direction of test
  server_hostname = The server hostname to connect to. Accepts DNS entries or IP addresses.
  zerocopy = Toggle zerocopy.

It could return values from:

TCP specific:
- retransmits 
- sent_bps
- received_bps

UDP specific:
- bytes
- bps
- jitter_ms
- packets
- lost_packets
- lost_percent
- seconds

### Use case: [Why is this important (helps with prioritizing requests)]

We are working on a network monitoring probe based on Telegraf to monitor device status through inputs.ping and device specific values with inputs.snmp.  We have wireless radio links on which we would like to run bandwidth test to get the real-feal of those links.  The probes would be deployed using Raspberry PI3 with Telegraf docker image to simplify the deployment and configuration.

**Comment by danielnelson** [comment]
Thanks for opening a feature request, I think this would be nice as well.  We may want to use https://godoc.org/github.com/google/gopacket for this type of functionality though, do you know how iperf3 compares to pcap?

This would require linking to a C library (so would gopacket), so we would need to improve the build system before this could be merged.

**Comment by Touchedegris** [comment]
By definition, pcap (packet capture) consists of an application programming interface (API) for capturing network traffic.  iPerf3 is a tool for active measurements of the maximum achievable bandwidth on IP networks.
I am not a programmer, but I am afraid that using the gopacket with packet forging would end up in building wether a telegraf client that forges packet and tune streams to fill the available bandwidth to another device, and a telegraf "server" that uses pcap to analyse the stream received.
Wouldn't it be simplier to link the go module to the iperf3 client installed location and use the iperf client to do this job and parse the results received?  This way you could set up any iperf servers anywhere and use the Telegraf "client" to stream to those servers and gather the results.

You can see below the output of an iperf udp test:

## Iperf3 UDP test
iperf3 -c iperf.he.net -u -b 1M -t 10 -i 1
Connecting to host iperf.he.net, port 5201
[  4] local 172.16.10.114 port 60326 connected to 216.218.227.10 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   120 KBytes   982 Kbits/sec  15
[  4]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   3.00-4.00   sec   112 KBytes   918 Kbits/sec  14
[  4]   4.00-5.00   sec   120 KBytes   983 Kbits/sec  15
[  4]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   6.00-7.00   sec   120 KBytes   982 Kbits/sec  15
[  4]   7.00-8.00   sec   120 KBytes   983 Kbits/sec  15
[  4]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   9.00-10.00  sec   120 KBytes   983 Kbits/sec  15
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec  1.20 MBytes  1.00 Mbits/sec  1.591 ms  0/152 (0%)
[  4] Sent 152 datagrams

iperf Done.

##Iperf3 TCP test
iperf3 -c iperf.he.net -t 10 -i 1 -R
Connecting to host iperf.he.net, port 5201
Reverse mode, remote host iperf.he.net is sending
[  4] local 172.16.10.114 port 40791 connected to 216.218.227.10 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  1.50 MBytes  12.6 Mbits/sec
[  4]   1.00-2.00   sec   803 KBytes  6.58 Mbits/sec
[  4]   2.00-3.00   sec  1.01 MBytes  8.49 Mbits/sec
[  4]   3.00-4.00   sec   569 KBytes  4.67 Mbits/sec
[  4]   4.00-5.00   sec   768 KBytes  6.29 Mbits/sec
[  4]   5.00-6.00   sec   624 KBytes  5.12 Mbits/sec
[  4]   6.00-7.00   sec   277 KBytes  2.27 Mbits/sec
[  4]   7.00-8.00   sec   473 KBytes  3.88 Mbits/sec
[  4]   8.00-9.00   sec   573 KBytes  4.69 Mbits/sec
[  4]   9.00-10.00  sec   610 KBytes  5.00 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  8.20 MBytes  6.88 Mbits/sec   98             sender
[  4]   0.00-10.00  sec  7.23 MBytes  6.06 Mbits/sec                  receiver

iperf Done.

**Comment by danielnelson** [comment]
Certainly would be easier to implement if we do it as fork/exec, somewhat less satisfying vs native code but I think this would be fine.

**Comment by rapport** [comment]
+1  We also have lots of nodes running iperf server and it would be super useful to have a telegraf input client to poll all this throughput and bandwidth information so we can view it as time-series

**Comment by jarossi** [comment]
+1 . as it is not clear above having multiple targets in the configuration would be nice, of course the tests to targets will have to perhaps run one after the other, to avoid link saturation and bad metrics

**Comment by andrey82k** [comment]
[[inputs.exec]]
      commands = [ "iperf3 -c example.com --json" ]
      interval = "30m"
      data_format = "json"
      json_query = "end"

**Comment by gallofeliz** [comment]
Hi,

In my projects (personal), I use telegraf as collector, not as metric generator. So, I refuse to install iperf3 in my telegraf docker image, and I created a service for that (I created services to read temperatures, weather, and others). I have no idea if it's a good idea to create a lot of plugins for telegraf : if the plugins are loaded only if used, it's okay for me (telegraf is small and can run in small raspberry pies).

For the people that can help, awaiting a native iperf3 telegraf plugin, please see https://github.com/gallofeliz/iperf3-service I created yesterday and I successfully installed on 2 raspberry servers and I collect.

Hope it helps you too. 
Regards
