### ISSUE TITLE
Unable to set read buffer on tcp socket in socket_listener

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3873]
### Relevant telegraf.conf:

```
[[inputs.socket_listener]]
  service_address = "tcp://:8094"
  read_buffer_size = 65535
```

### System info:

Telegraf 1.5.2

### Steps to reproduce:

1. Enable socket_listener as described above
2. Start Telegraf

### Expected behavior:

Read buffer size set

### Actual behavior:

```
2018-03-09T01:37:59Z W! Unable to set read buffer on a tcp socket
```

**Comment by danielnelson** [comment]
@phemmer I'm confused how this code works, it looks like we are attempting to call SetReadBuffer on a `Listener` type, which would never have this function, instead of on a `Conn` type.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/socket_listener/socket_listener.go#L234-L246

**Comment by phemmer** [comment]
You're right. Oops. I have no idea what I was thinking when I wrote that. That should be moved to after the accept.

**Comment by phemmer** [comment]
Trivial fix. You want me to do it, or are you getting it?

**Comment by danielnelson** [comment]
I'm always willing to let someone else do my work :)

**Comment by phemmer** [comment]
Well I kinda feel like I should clean up my own mess, so I'll do it now. Have a PR up in a few :-)
