### ISSUE TITLE
Logparser vs /proc files

### ISSUE THREAD

**Issue by mjf** [influxdata/telegraf#3878]
Hello.

I have a [set of Grok rules](https://gist.github.com/mjf/dd5eee89d59a13ac5e470e64b4092565) to parse `/proc/fs/xfs/stat` but obtain only one (the first collected?) serie after *Telegraf* restart. Sample configuration for *Telegraf*'s `logparser` plugin looks like the following:

    [[inputs.logparser]]

      files = ["/proc/fs/xfs/stat"]
      watch_method = "poll"
      from_beginning = true

      [inputs.logparser.grok]

        measurement = "xfs_stat"
        custom_pattern_files = ["/etc/telegraf/proc_fs_xfs_stat.grok"]
        patterns = ["%{XFS_STAT}"]

Of course I tried both `poll` and `inotify` methods but neither seem to be working. (May it be you simply can not "seek" on `/proc` files?)

The measurement `xfs_stat` gets created, as well as all the fields from the ruleset (such as `rw_read_calls`, `rw_write_calls` etc.) Still, I obtain only the first serie after the *Telegraf* restart.

I would expect the `poll` method together with the `from_beginning = true` to work but it's not.

**Comment by sebito91** [comment]
Wondering if this might be a useful standalone plugin? But not sure if you can get at this data from the integrated `[[inputs.disk]]` plugin?

http://xfs.org/index.php/Runtime_Stats

**Comment by danielnelson** [comment]
I don't think it will be possible to use logparser to monitor this file, as you found it doesn't start the file over unless it thinks it has been truncated.

Once #3479 is implemented though you could use your grok pattern with other inputs, so you could easily do this with the exec plugin or we probably need an input that just reads a file every interval and passes it to a parser.

I agree it would make sense for this to be a standalone plugin as well.

Would be nice if issues for these two items: file parser input or xfs input could be opened.

**Comment by mjf** [comment]
@danielnelson Well, there may be some `xfsstat` input, I agree, but only for performance reasons, right? (*Grok* might be expensive?)

But generally speaking I would like to collect many other interesting things from the `procfs` or even `sysfs`. So, if there was the `file` input with *Grok* capability, it would certainly helped too. I hoped the `logparser` could have been easily extended with a method to just "read a file every interval".

In fact, I am still not sure why the `logparser` is called `logparser` and not, for instance, `tailer` or something similar for you can use it on any file that matches it's methods' expected behaviour...

Why not to replace the `logparser` with one general plugin `reader` or `parser` with several methods of operation (even to read from i.e. *unix* sockets) and once maybe extensible with more parsers (who knows)? The name `logparser` is a bit misleading...

**Comment by mjf** [comment]
@sebito91 Nope. Or, at least, I do not see the statistics using the `inputs.disk` nor is there any option in configuration to switch it on, as far as I know... For now, I would be pretty happy if my *Grok*-parsed metrices worked. :-(

**Comment by danielnelson** [comment]
> Well, there may be some xfsstat input, I agree, but only for performance reasons, right? (Grok might be expensive?)

Performance and ease of use, plus there are some advantages to having unified naming for when sharing dashboards or queries.

> In fact, I am still not sure why the logparser is called logparser and not, for instance, tailer or something similar for you can use it on any file that matches it's methods' expected behaviour...

Completely agree, we also have a tail plugin that does essentially the same thing, but can work with any `Parser`.  Once we make grok a `Parser` in https://github.com/influxdata/telegraf/issues/3479, we can also remove the logparser input completely since it will be usable with the tail plugin.
