### ISSUE TITLE
Query fails if host contains char \

### ISSUE THREAD

**Issue by iatalay** [influxdata/telegraf#3881]
## Bug report
Query fails if host includes char \ using nightly build of telegraf for sqlserver.

Error:
found \I, expected identifier, string, number, bool at line 1, char 43

### Relevant telegraf.conf:
[[inputs.sqlserver]]
servers = [ "Server=sqlserverhost1;Port=1433;User Id=user;Password=pass;", ]
query_version = 2

### System info:
Telegraf v1.6.0
Windows Server 2008 R2

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Go to chronograf http://localhost:8888
2. Go to "Data Explorer"
3. Select "telegraf.autogen"
4. Select "sqlserver_database_io"
5. Select "host" tag and select one of your host that contains char \ (for example: sqlserverhost1\INST01)
6. Select field(s) from Fields part. 

Query will be;

SELECT mean("writes") AS "mean_writes" FROM "telegraf"."autogen"."sqlserver_database_io" WHERE time > now() - 1h AND "host"='sqlserverhost1\INST01' GROUP BY :interval: FILL(null)

### Expected behavior:

1- Query should run successfully.
or
2- Host tag should not contain instance name like \INST01

### Actual behavior:

Error:
found \I, expected identifier, string, number, bool at line 1, char 43

**Comment by danielnelson** [comment]
Where do you see this error message, is it in the Chronograf UI?  If so, can you open a [new issue](https://github.com/influxdata/chronograf/issues/new) on the Chronograf repo about the query error.

@m82labs It looks like we are setting the `host` tag with the new query_version, we should modify this to use a different name such as `server`.  Reason is that in Telegraf the host tag is standardized to always indicate the host Telegraf is running on, there is some desire for a standard tag that would always be the monitored host but that's another issue.

**Comment by m82labs** [comment]
I’ll look into this.

**Comment by iatalay** [comment]
Yes, it is in the Chronograf UI. 
Here is the secreen captures;
[data-explorer](https://pasteboard.co/HbOvbpb.png)
[host-list](https://pasteboard.co/HbOtVwo.png)

**Comment by danielnelson** [comment]
@iatalay Yes that part looks like a Chronograf issue, please report it to over on the issue tracker that that project if you haven't already.

**Comment by iatalay** [comment]
@danielnelson I've openned an issue at Chronograf section.

**Comment by danielnelson** [comment]
Host tag was removed in #3916, it is now part of `sql_instance`.

**Comment by iatalay** [comment]
@m82labs I realized that host tag in measurement "sqlserver_database_io" still like 'hostname\inst01' while other measurements' host tag is correct, like 'hostname'
Can you please check this one?
