### ISSUE TITLE
[[inputs.elasticsearch]] mis-spelled node stat name causes ES input error

### ISSUE THREAD

**Issue by grindthemall** [influxdata/telegraf#3896]
When using the inputs.elasticsearch setup, you can specify node_stats to narrow down what gets polled from elasticsearch.  

Current behavior:
When using this setup, if you use the keyword "breakers" as specified in the node_stats configuration, you will receive the following error:

**telegraf[40545]: 2018-03-16T14:15:00Z E! Error in plugin [inputs.elasticsearch]: elasticsearch: API responded with status-code 400, expected 200**

Desired behavior:
The proper entry should be "breaker" as shown below which pulls the proper stats from elasticsearch.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

```
 # Read stats from one or more Elasticsearch servers or clusters
 [[inputs.elasticsearch]]
   ## specify a list of one or more Elasticsearch servers
   servers = ["http://127.0.0.1:9200"]

   http_timeout = "10s"

   ## set local to false when you want to read the indices stats from all nodes
   ## within the cluster
   local = true

   ## set cluster_health to true when you want to also obtain cluster level stats
   cluster_health = true
   cluster_stats = true
   cluster_health_level = "indices"

   ## node_stats is a list of sub-stats that you want to have gathered. Valid options
   ## are "indices", "os", "process", "jvm", "thread_pool", "fs", "transport", "http",
   ## "breakers". Per default, all stats are gathered.
   node_stats = ["os", "process", "jvm", "thread_pool", "fs", "transport", "http", "breaker"]
```

**Comment by danielnelson** [comment]
Thanks for the report, I updated the comment in https://github.com/influxdata/telegraf/commit/76ce71f7fa0ef46a700be4e51826b6be66dd8edd and the change will be in 1.6.
