### ISSUE TITLE
Telegraf - Windows2008R2

### ISSUE THREAD

**Issue by r4yfx** [influxdata/telegraf#3898]
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be asked at the [InfluxData Community](https://community.influxdata.com) site.

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

telegraf-1.5.3
Windows 2008R2 

### Steps to reproduce:

1. Run installation command from cmd and it starts the service, instead of installing. 

### Expected behavior:
Installation of telegraf

### Actual behavior:
Runs service without installation

### Additional info:
I cannot seem to install telegraf.exe using the service install flag. This was attempted using run as administrator as well. 

Can someone please advise if this version is supported on windows 2008 r2 (yes, I know not ideal), and if not. Is there a version of telegraf which I should use and where I can download it?

**Comment by danielnelson** [comment]
Can you add a copy of the command you are running?

**Comment by r4yfx** [comment]
Problem appeared to be "get-executionpolicy" when this was set to unrestricted. It allowed the installation.
