### ISSUE TITLE
Missing metrics for inputs.sqlserver

### ISSUE THREAD

**Issue by iatalay** [influxdata/telegraf#3905]
## Bug report

Some sqlserver metrics are missing.
For example;

SQLServer:Workload Group Stats\Blocked tasks
SQLServer:Workload Group Stats\CPU usage %
SQLServer:Workload Group Stats\Queued requests
SQLServer:Workload Group Stats\Requests completed/sec

[see secreen capture](https://pasteboard.co/HcBpiEp.png)

### Relevant telegraf.conf:

[[inputs.sqlserver]]
servers = [ "Server=HOSTT3;Port=1433;User Id=user;Password=pass;", ]
query_version = 2

### System info:

Telegraf v1.6.0
Windows Server 2008 R2

### Steps to reproduce:

1. Go to chronograf data explorer

### Expected behavior:
Should collect metrics mentioned at [sqlserver version 2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver)

### Actual behavior:

[see secreen capture](https://pasteboard.co/HcBpiEp.png)

**Comment by danielnelson** [comment]
@m82labs Can you take a look at this one too?

**Comment by m82labs** [comment]
@iatalay those should all show under "sqlserver_performance". Do I need to maybe add to the documentation that the listed metrics in that section are all under "sqlserver_performance"?

**Comment by danielnelson** [comment]
Usually what we do is add the output `telegraf --input-filter sqlserver --test` to the docs, if you can run that I could add it in.

**Comment by m82labs** [comment]
I will include that in my next PR.

**Comment by iatalay** [comment]
@m82labs I couldn't find any metric related to cpu under "sqlserver_performance"
[img1](https://pasteboard.co/HcFlo46.png)
[img2](https://pasteboard.co/HcFlPaH.png)
[img3](https://pasteboard.co/HcFm4U8.png)
[img4](https://pasteboard.co/HcFmlMq.png)
[img5](https://pasteboard.co/HcFmAya.png)

**Comment by iatalay** [comment]
@danielnelson I ran the command _telegraf --input-filter sqlserver --test_ 
There isn't any metric related to cpu also
[output.txt](https://github.com/influxdata/telegraf/files/1826742/output.txt)

**Comment by m82labs** [comment]
@iatalay can you post the results of this query please: 

```
SELECT	*
FROM	sys.dm_os_performance_counters
WHERE	object_name = 'SQLServer:Workload Group Stats'
```

**Comment by danielnelson** [comment]
With respect to the docs, since we have so many metrics, we should probably just show a sample of the output, and moving in the direction of this style where possible: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/EXAMPLE_README.md

**Comment by iatalay** [comment]
@m82labs It seems it has a different object name in 2008 R2. 
[dm_os_performance_counters.txt](https://github.com/influxdata/telegraf/files/1828016/dm_os_performance_counters.txt)

**Comment by m82labs** [comment]
@iatalay ah, I see now. I forgot about named instances when I was working on this. 

Can you see if this query returns everything you would expect: 
```
DECLARE @PCounters TABLE
(
	object_name nvarchar(128),
	counter_name nvarchar(128),
	instance_name nvarchar(128),
	cntr_value bigint,
	cntr_type INT,
	Primary Key(object_name, counter_name, instance_name)
);

INSERT	INTO @PCounters
SELECT	DISTINCT
		RTrim(spi.object_name) object_name,
		RTrim(spi.counter_name) counter_name,
		RTrim(spi.instance_name) instance_name,
		spi.cntr_value,
		spi.cntr_type
FROM	sys.dm_os_performance_counters AS spi
WHERE	(
		counter_name IN (
			'SQL Compilations/sec',
			'SQL Re-Compilations/sec',
			'User Connections',
			'Batch Requests/sec',
			'Logouts/sec',
			'Logins/sec',
			'Processes blocked',
			'Latch Waits/sec',
			'Full Scans/sec',
			'Index Searches/sec',
			'Page Splits/sec',
			'Page Lookups/sec',
			'Page Reads/sec',
			'Page Writes/sec',
			'Readahead Pages/sec',
			'Lazy Writes/sec',
			'Checkpoint Pages/sec',
			'Page life expectancy',
			'Log File(s) Size (KB)',
			'Log File(s) Used Size (KB)',
			'Data File(s) Size (KB)',
			'Transactions/sec',
			'Write Transactions/sec',
			'Active Temp Tables',
			'Temp Tables Creation Rate',
			'Temp Tables For Destruction',
			'Free Space in tempdb (KB)',
			'Version Store Size (KB)',
			'Memory Grants Pending',
			'Free list stalls/sec',
			'Buffer cache hit ratio',
			'Buffer cache hit ratio base',
			'Backup/Restore Throughput/sec',
			'Total Server Memory (KB)',
			'Target Server Memory (KB)'
		)
		) OR (
			instance_name IN ('_Total','Column store object pool')
			AND counter_name IN (
				'Log Flushes/sec',
				'Log Flush Wait Time',
				'Lock Timeouts/sec',
				'Number of Deadlocks/sec',
				'Lock Waits/sec',
				'Latch Waits/sec',
				'Memory broker clerk size',
				'Log Bytes Flushed/sec',
				'Bytes Sent to Replica/sec',
				'Log Send Queue',
				'Bytes Sent to Transport/sec',
				'Sends to Replica/sec',
				'Bytes Sent to Transport/sec',
				'Sends to Transport/sec',
				'Bytes Received from Replica/sec',
				'Receives from Replica/sec',
				'Flow Control Time (ms/sec)',
				'Flow Control/sec',
				'Resent Messages/sec',
				'Redone Bytes/sec',
				'XTP Memory Used (KB)'
			) OR ( 
				counter_name IN (
					'Log Bytes Received/sec',
					'Log Apply Pending Queue',
					'Redone Bytes/sec',
					'Recovery Queue',
					'Log Apply Ready Queue'
				)
				AND instance_name = '_Total'
			)
		) OR (
			counter_name IN ('Transaction Delay')
		) OR (
			counter_name IN (
				'CPU usage %',
				'CPU usage % base',
				'Queued requests',
				'Requests completed/sec',
				'Blocked tasks'
			)
		) OR (
			counter_name IN (
				'Active memory grant amount (KB)',
				'Disk Read Bytes/sec',
				'Disk Read IO Throttled/sec',
				'Disk Read IO/sec',
				'Disk Write Bytes/sec',
				'Disk Write IO Throttled/sec',
				'Disk Write IO/sec',
				'Used memory (KB)'
			)
		) OR  (
			object_name LIKE '%User Settable%'
			object_name LIKE '%SQL Errors%'
		)

SELECT	'sqlserver_performance' AS [measurement],
		REPLACE(@@SERVERNAME,'\',':') AS [sql_instance],
		pc.object_name AS [object],
		pc.counter_name AS [counter],
		CASE pc.instance_name WHEN '_Total' THEN 'Total' ELSE ISNULL(pc.instance_name,'') END AS [instance],
		CASE WHEN pc.cntr_type = 537003264 AND pc1.cntr_value > 0 THEN (pc.cntr_value * 1.0) / (pc1.cntr_value * 1.0) * 100 ELSE pc.cntr_value END AS [value]
FROM	@PCounters AS pc
		LEFT OUTER JOIN @PCounters AS pc1
			ON (
				pc.counter_name = REPLACE(pc1.counter_name,' base','')
				OR pc.counter_name = REPLACE(pc1.counter_name,' base',' (ms)')
			)
			AND pc.object_name = pc1.object_name
			AND pc.instance_name = pc1.instance_name
			AND pc1.counter_name LIKE '%base'
WHERE	pc.counter_name NOT LIKE '% base'
UNION ALL
SELECT
'sqlserver_performance' As [measurement],
REPLACE(@@SERVERNAME,'\',':') AS [sql_instance],
'SQLServer:Workload Group Stats' AS object,
counter,
instance,
vs.value
FROM
(
    SELECT 
    rgwg.name AS instance,
    rgwg.total_request_count AS 'Request Count',
    rgwg.total_queued_request_count AS 'Queued Request Count',
    rgwg.total_cpu_limit_violation_count AS 'CPU Limit Violation Count',
    rgwg.total_cpu_usage_ms AS 'CPU Usage (time)',
    rgwg.total_cpu_usage_preemptive_ms AS 'Premptive CPU Usage (time)',
    rgwg.total_lock_wait_count AS 'Lock Wait Count',
    rgwg.total_lock_wait_time_ms AS 'Lock Wait Time',
    rgwg.total_reduced_memgrant_count AS 'Reduced Memory Grant Count'
    FROM sys.dm_resource_governor_workload_groups AS rgwg
    INNER JOIN sys.dm_resource_governor_resource_pools AS rgrp
    ON rgwg.pool_id = rgrp.pool_id
) AS rg
UNPIVOT (
    value FOR counter IN ( [Request Count], [Queued Request Count], [CPU Limit Violation Count], [CPU Usage (time)], [Premptive CPU Usage (time)], [Lock Wait Count], [Lock Wait Time], [Reduced Memory Grant Count] )
) AS vs
OPTION(RECOMPILE);
```

**Comment by iatalay** [comment]
@m82labs query seems ok but column "total_cpu_usage_preemptive_ms" does not exist in my environment.

Here are the columns for table "sys.dm_resource_governor_workload_groups"
_name
pool_id
statistics_start_time
total_request_count
total_queued_request_count
active_request_count
queued_request_count
total_cpu_limit_violation_count
total_cpu_usage_ms
max_request_cpu_time_ms
blocked_task_count
total_lock_wait_count
total_lock_wait_time_ms
total_query_optimization_count
total_suboptimal_plan_generation_count
total_reduced_memgrant_count
max_request_grant_memory_kb
active_parallel_thread_count
importance
request_max_memory_grant_percent
request_max_cpu_time_sec
request_memory_grant_timeout_sec
group_max_requests
max_dop_

**Comment by m82labs** [comment]
@iatalay just to keep big chunks of code out of this thread, can you try this modified version of the query: https://gist.github.com/m82labs/5abe0ece587f7090174ec76baab5448f

**Comment by iatalay** [comment]
@m82labs query is working.
When is release date of v1.6.0? I don't have go compiler in my envronment So I need compiled one :)

**Comment by m82labs** [comment]
@iatalayThanks!  Would you mind sending me your email address? I can send over TSQL changes in the future to avoid these issues before I submit a PR, I have no 2008 systems to test on. :) If you are interested you can email me at: mark at m82labs dot com.

**Comment by danielnelson** [comment]
It's great that we are getting this extra testing so the new query version will be a smooth rollout.  1.6 is currently planned for beginning of April, and to meet that data I'd like to get a release candidate out before the end of the month.  @m82labs I hope that will give you enough time to finish your latest patches.
