### ISSUE TITLE
Telegraf Input for LXC monitoring

### ISSUE THREAD

**Issue by pierrick-openIT** [influxdata/telegraf#3907]
Hi everyone,

here is an official input for monitor LXC container from inside him ?

regards

**Comment by danielnelson** [comment]
Nothing LXC specific, but you can use the same plugins you would use on a bare-metal system to monitor the container: `cpu`, `disk`, `mem`, etc.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
