### ISSUE TITLE
Kapacitor input plugin needs SSL section in config

### ISSUE THREAD

**Issue by dp1140a** [influxdata/telegraf#3917]
If you have Kapacitor setup under SSL with a self signed Cert it will throw an error.  
Please add the following options to the Kapacitor input plugin to match the influxdb plugin:

  ssl_ca = "/etc/telegraf/ca.pem"
  ssl_cert = "/etc/telegraf/cert.pem"
  ssl_key = "/etc/telegraf/key.pem"
  insecure_skip_verify = false

**Comment by danielnelson** [comment]
Should be easy, I'll get it in for 1.6.
