### ISSUE TITLE
[inputs.mongodb] page_fault_per_sec is available in mongos and config but not in mongod(replicaset) process

### ISSUE THREAD

**Issue by j3ffrw** [influxdata/telegraf#3920]
### Relevant telegraf.conf:
[[inputs.mongodb]]
  servers = ["mongodb://mongod:telegraf@127.0.0.1:27019/admin?authSource=admin", "mongodb://mongoc:telegraf@127.0.0.1:7777/admin?authSource=admin", "mongodb://mongos:telegraf@127.0.0.1:8888/admin?authSource=admin"]

### System info:

telegraf-1.5.2-1.x86_64
CentOS Linux release 7.0.1406 (Core) 
db version v3.2.10-3.0

### Steps to reproduce:

1. telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d/ -test --input-filter mongodb

### Expected behavior:

field page_fault_per_sec available on mongod(replicaset)

### Actual behavior:
> mongodb,hostname=127.0.0.1:8888,host=mongodb-1-zone-1.internal net_in_bytes=10177i,repl_deletes_per_sec=0i,repl_getmores_per_sec=0i,mapped_megabytes=-1i,flushes_per_sec=0i,updates_per_sec=24i,ttl_passes_per_sec=0i,commands_per_sec=27i,queued_reads=0i,repl_inserts_per_sec=0i,page_faults_per_sec=0i,active_writes=0i,ttl_deletes_per_sec=0i,repl_queries_per_sec=0i,repl_updates_per_sec=0i,open_connections=42i,getmores_per_sec=0i,non-mapped_megabytes=-1i,active_reads=0i,resident_megabytes=39i,member_status="RTR",queries_per_sec=24i,jumbo_chunks=0i,state="",inserts_per_sec=0i,queued_writes=0i,repl_lag=0i,deletes_per_sec=0i,vsize_megabytes=447i,repl_commands_per_sec=0i,net_out_bytes=231110i 1521701147000000000
> mongodb,host=mongodb-1-zone-1.internal,hostname=127.0.0.1:7777 commands_per_sec=3i,net_out_bytes=13105i,ttl_passes_per_sec=0i,queued_writes=0i,repl_deletes_per_sec=0i,repl_inserts_per_sec=0i,non-mapped_megabytes=520i,page_faults_per_sec=0i,member_status="PRI",state="",queued_reads=0i,getmores_per_sec=0i,ttl_deletes_per_sec=0i,repl_updates_per_sec=0i,repl_commands_per_sec=0i,open_connections=27i,repl_getmores_per_sec=0i,updates_per_sec=0i,active_reads=0i,repl_lag=0i,flushes_per_sec=0i,repl_queries_per_sec=0i,jumbo_chunks=0i,mapped_megabytes=96i,deletes_per_sec=0i,active_writes=0i,net_in_bytes=228i,inserts_per_sec=0i,queries_per_sec=0i,vsize_megabytes=616i,resident_megabytes=77i 1521701147000000000
> mongodb,host=mongodb-1-zone-1.internal,hostname=127.0.0.1:2701 ttl_passes_per_sec=0i,commands_per_sec=3i,vsize_megabytes=1032i,deletes_per_sec=0i,net_in_bytes=228i,open_connections=34i,ttl_deletes_per_sec=0i,resident_megabytes=138i,repl_updates_per_sec=0i,active_writes=0i,net_out_bytes=16584i,queued_writes=0i,repl_lag=0i,repl_deletes_per_sec=0i,queries_per_sec=0i,flushes_per_sec=0i,repl_commands_per_sec=0i,updates_per_sec=0i,active_reads=0i,repl_getmores_per_sec=0i,member_status="PRI",getmores_per_sec=0i,queued_reads=0i,repl_queries_per_sec=0i,repl_inserts_per_sec=0i,inserts_per_sec=0i,state="PRIMARY",jumbo_chunks=0i 1521701147000000000
### Additional info:

[Include gist of relevant config, logs, etc.]

### Use case: [Why is this important (helps with prioritizing requests)]

We would like to create alerts base on this field, but would not like to enable kernel_vmstat as were only interested on this field.

**Comment by danielnelson** [comment]
Can you run this command and attach the output on the mongod server without page faults:
```
db.adminCommand( { serverStatus : 1 },{ recordStats : 1} )
```

**Comment by j3ffrw** [comment]
[mongod_serverstatus.log](https://github.com/influxdata/telegraf/files/1839714/mongod_serverstatus.log)

**Comment by danielnelson** [comment]
I think it is not being added because the storage engine is `rocksdb`[1].  I'm not super familiar with how it the different storage engines interact, but I will add rocksdb if you can test out a build.

[1] https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb_data.go#L138-L139

**Comment by danielnelson** [comment]
@j3ffrw Can you check if this build fixes the problem? https://10245-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.5.0%7E7c6e5d62-0.x86_64.rpm
