### ISSUE TITLE
build failure  with the error: plugins\inputs\docker\client.go:38:25: undefined: client.ParseHost

### ISSUE THREAD

**Issue by szlanyou** [influxdata/telegraf#3921]
## Bug report
execute the script : make telegraf, but it failure with the error: plugins\inputs\docker\client.go:38:25: undefined: client.ParseHost
### Steps to reproduce:

1、do it failure :+1: go get github.com/docker/docker  
2、try another way: git clone  https://github.com/moby/moby.git docker
3、do it "make telegraf" again，but it failure with the error: plugins\inputs\docker\client.go:38:25: undefined: client.ParseHost

### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
Looks like they removed the `ParseHost` function https://github.com/moby/moby/commit/54242cd067c234960d1295a67271475f9d099f22

Make sure you are using the sha in the Godeps files, you can run `make` which runs `gdm restore` and checks out the appropriate versions.

We can update the docker the plugin and the docker/mobdy library in the 1.7 milestone.

**Comment by szlanyou** [comment]
@danielnelson  it success, thanks!
Yesterday，i feel it too  slow when gdm download "github.com/docker/docker"，i thought it cann't work mybey。So i add code annotation to "github.com/docker/docker f5ec1e2936dcbe7b5001c2b817188b095c700c27"， then git clone docker manually for asking for trouble
