### ISSUE TITLE
Feature Request: make publishing to a “topic” Exchange type in RabbitMQ optional

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/telegraf#3925]
Right now, Telegraf only allows us to publish to a “topic” Exchange type in RabbitMQ because it’s hard-coded in https://github.com/influxdata/telegraf/blob/master/plugins/outputs/amqp/amqp.go#L173 (https://github.com/influxdata/telegraf/blob/master/plugins/outputs/amqp/amqp.go#L173)

We can please make this optional so we can publish to fanout exchanges?

**Comment by russorat** [comment]
related to https://github.com/influxdata/telegraf/issues/2801
