### ISSUE TITLE
How to prefix a field and measurement name in telegraf

### ISSUE THREAD

**Issue by sureshsubramaniam** [influxdata/telegraf#3929]
is there any option to prefix all the field names and measurement name and tag names in telegraf

**Comment by danielnelson** [comment]
No, the closest you can achieve is to add `name_prefix = "foo_"` to all of your inputs.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
