### ISSUE TITLE
AMQP consumer should continue to reconnect to the broker

### ISSUE THREAD

**Issue by mr-f00** [influxdata/telegraf#3933]
Have searched open issues and [started a discussion](https://community.influxdata.com/t/telegraf-amqp-consumer-closing-after-a-few-minutes-on-docker/4311) before opening this issue.

## Bug report

Previously I was running telegraf 1.4.x just fine on windows. It was only collecting some windows metrics and an AMQP consumer and writing results just fine to an influx output plugin. I installed docker (Windows 10) and installed the telegraf container. I’ve tried versions 1.4.5 and #latest (1.5.2). Both had this same issue. AMQP broker is running on another host with versions RabbitMQ 3.6.6, Erlang 17.3.

telegraf will run for a few minutes just fine. It connects to the AMQP broker, collects metrics and stores them in influx per the config. However after a few minutes it will close the connection on an exception (501 Reason “EOF”), reconnect automatically and run for another couple minutes, and then close it again (this time no exception) and then never reconnect to the queue. At this point no metrics are no longer collected from the AMQP consumer plugin.

### Relevant telegraf.conf:

[telegraf-amqp.conf.txt](https://github.com/influxdata/telegraf/files/1844537/telegraf-amqp.conf.txt)

### System info:

Running telegraf as a docker container on Windows 10. Versions: telegraf 1.4.x and 1.5.2, Windows 10, connecting to RabbitMQ 3.6.6, Erlang 17.3.

### Steps to reproduce:

Launch telegraf container with attached config.

### Expected behavior:

telegraf AMQP consumer should not close the connection. And if the connection breaks, then it should re-connect.

### Actual behavior:

1. Observe telegraf connect and collect metrics from rabbitmq initially.
2. Observe telegraf log indicate AMQP connection is closed. Log from rabbitmq server (also attached) indicates the client closes the connection.
3. telegraf will re-connect to AMQP one time and successfully start processing metrics again.
4. telegraf appears to close connection again but does not attempt to re-connect to AMQP server.

### Additional info:

Below are log excerpts showing the behavior.

[telegraf.log](https://github.com/influxdata/telegraf/files/1844538/telegraf.log)

[rabbitmq-server.log](https://github.com/influxdata/telegraf/files/1844539/rabbitmq-server.log)

**Comment by mr-f00** [comment]
I think I found the cause which was an error in the config. My config inadvertently set both of the following incompatible settings:

> interval = "30s"
> flush_interval = "10s"

Per the config file, it states:

> You shouldn't set this [flush_interval] below interval.

When the "flush_interval" was less than the "interval" then the AMQP consumer plugin repeatedly closes the connection.

I wouldn't expect a bug for this behavior (or it would at least be low priority). HOWEVER, I think it revealed a bug in that the AMQP consumer only reconnects to the AMQP broker one time if the connection is closed for any reason. It seems like the AMQP consumer should continue to reconnect to the broker. For example: the AMQP broker restarts and then the client reconnects one time. Or if there is intermittent network connectivity then the connection might drop and require reconnecting. [As written](https://github.com/influxdata/telegraf/blob/9ce70aad77421f27ea2c82541a2198af935d1c6a/plugins/inputs/amqp_consumer/amqp_consumer.go#L132), it appears the AMQP consumer does not continue to try to reconnect.

**Comment by russorat** [comment]
@mr-f00 thanks for the report. We will look into improving this behavior. If you'd like to take a stab at fixing the broken behavior through a PR, that would be awesome!
