### ISSUE TITLE
Why my telegraf Invalid initial start，but restart once effective？

### ISSUE THREAD

**Issue by linglaiyao1314** [influxdata/telegraf#3935]
I use the supervisord run my telegraf， but first start， telegraf dont read my metrics.out file。
when i type the “supervisorctl restart telegraf”， the telegraf can normal work。

### Relevant telegraf.conf:
The main conf is ：
```
# # Stream a log file, like the tail -f command
[[inputs.tail]]
#   ## files to tail.
#   ## These accept standard unix glob matching rules, but with the addition of
#   ## ** as a "super asterisk". ie:
#   ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
#   ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
#   ##   "/var/log/apache.log" -> just tail the apache log file
#   ##
#   ## See https://github.com/gobwas/glob for more examples
#   ##
   files = ["/360-spider/logs/metrics.out"]
#   ## Read file from beginning.
   from_beginning = false
#   ## Whether file is a named pipe
   pipe = false
#
#   ## Data format to consume.
#   ## Each data format has it's own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
   data_format = "influx"
```
### Telegraf log info:
2018-03-26T03:15:32Z I! Starting Telegraf v1.5.2
2018-03-26T03:15:32Z I! Loaded outputs: influxdb
2018-03-26T03:15:32Z I! Loaded inputs: inputs.cpu inputs.disk inputs.mem inputs.swap inputs.tail
2018-03-26T03:15:32Z I! Tags enabled: host=ba911ad5be00
2018-03-26T03:15:32Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"ba911ad5be00", Flush Interval:10s
....................

**Comment by russorat** [comment]
@linglaiyao1314 thanks for the issue. Your config is set up to only read new lines added to the end of the file. if you'd like to read the entire file when you first start the plugin, set `from_beginning = true`.

Can you verify that when telegraf is running, that new lines are being appended to the end of the file and they are not showing up in your influxdb instance?

**Comment by linglaiyao1314** [comment]
@russorat  I set ```from_beginning = true```， but first time still not work, restart then work well.

**Comment by danielnelson** [comment]
@linglaiyao1314 Can you add your supervisord conf, your operating system details, and also attach the logfile from Telegraf show the initial startup as well as the restart?

**Comment by linglaiyao1314** [comment]
hi @danielnelson  this is a part of my supervisord conf:
```
[program:telegraf]
command=telegraf --config /360-spider/telegraf.conf
directory=/360-spider
numprocs=1
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/360-spider/logs/telegraf.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
loglevel=info
```
My services are run in docker. and my base image is Centos. 

when service startup， the telegraf.log show ：
```
2018-04-02T10:50:54Z I! Starting Telegraf v1.5.2
2018-04-02T10:50:54Z I! Loaded outputs: influxdb
2018-04-02T10:50:54Z I! Loaded inputs: inputs.cpu inputs.disk inputs.mem inputs.swap inputs.tail
2018-04-02T10:50:54Z I! Tags enabled: host=f62e21c126e2
2018-04-02T10:50:54Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"f62e21c126e2", Flush Interval:10s
```
but  it can't read data from my file:
```
files = ["/360-spider/logs/metrics.out"]
```
Then I type this command to restart：
```
 supervisorctl restart telegraf
```
the telegraf.log append:
```
2018-04-02T10:55:22Z I! Starting Telegraf v1.5.2
2018-04-02T10:55:22Z I! Loaded outputs: influxdb
2018-04-02T10:55:22Z I! Loaded inputs: inputs.disk inputs.mem inputs.swap inputs.tail inputs.cpu
2018-04-02T10:55:22Z I! Tags enabled: host=f62e21c126e2
2018-04-02T10:55:22Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"f62e21c126e2", Flush Interval:10s
```
and it can work well.

**Comment by danielnelson** [comment]
When is the file `"/360-spider/logs/metrics.out"` created?  Does it happen before Telegraf initially starts or afterwards?

Also can you try setting `watch_method = "poll"` in your tail configuration and see if that helps?

**Comment by danielnelson** [comment]
@linglaiyao1314 Have you solved this?
