### ISSUE TITLE
Used memory for linux hosts is incorrect due to a bug in gopsutil

### ISSUE THREAD

**Issue by dimrozakis** [influxdata/telegraf#3939]
Used memory for linux hosts with newer kernels (3.14+) is reported incorrectly. This is due to a bug in `gopsutil`. More information on the bug, together with a fix, can be found at https://github.com/shirou/gopsutil/pull/504. Telegraf will need to update the version of gopsutil it is using, once that PR has been merged.

**Comment by russorat** [comment]
we will update the version once it is fixed. if you'd like to submit a PR when gopsutil is updated, that would be awesome!

**Comment by dimrozakis** [comment]
will do!

**Comment by danielnelson** [comment]
I included the latest gopsutil, containing this fix, for 1.6.0.  Thanks @dimrozakis
