### ISSUE TITLE
Add REST API to the httpjson plugin

### ISSUE THREAD

**Issue by panda87** [influxdata/telegraf#394]
Hi

I found the httpjson plugin as a very good idea, but today as many of the API's are REST based, this will be very useful to add REST capabilities to this plugin.

Thanks
D.

**Comment by sparrc** [comment]
@panda87 could you be more specific? What features would you like to see?

**Comment by panda87** [comment]
Today, the plugin is good only for simple GET \ POST.
But, if I want to send more complicated POST as REST API like:
{"type":"test","host":"home"}
This are not possible, since instead of sending the the json request in the body (-d) you serialize it in the url request.

So POST request to REST API are not working as expected.

**Comment by miketonks** [comment]
Not sure I can see the use case here.

With a REST webservice, GET requests should fetch data and POST requests should (generally) send data to / modify data on the remote server.

This is an input plugin so we want to fetch data.  Where's the need to support POST?

**Comment by gabelev** [comment]
I agree with this feature request. I think this is a good idea to be able to fetch data also via a POST.

**Comment by panda87** [comment]
Thanks @gabelev
