### ISSUE TITLE
[[inputs.net]] I can not collect all interfaces info

### ISSUE THREAD

**Issue by lurenjia528** [influxdata/telegraf#3943]
when i write like this

[[inputs.net]]
   interfaces = ["eth0"]

I can collect the info about interface 'eth0'

but when i write like this
[[inputs.net]]
  # interfaces = ["eth0"]

I want to collect all interfaces info ,but  I can't collect them

why???

**Comment by danielnelson** [comment]
Can you run `telegraf --input-filter net --test` and paste the output?

**Comment by lurenjia528** [comment]
I am in China GMT+800
telegraf output 
![2018-03-29 09-21-56](https://user-images.githubusercontent.com/37833630/38064816-ac04019a-3332-11e8-8d56-cf6186d7e13f.png)

prometheus search 2018-03-29 09-24-25
![2018-03-29 09-24-25](https://user-images.githubusercontent.com/37833630/38064956-5179b94e-3333-11e8-8ff5-75fed0f70324.png)
prometheus search 2018-03-29 09-24-25
![2018-03-29 09-25-00](https://user-images.githubusercontent.com/37833630/38064957-51c6542a-3333-11e8-97ef-be9c83cb3617.png)

otherwise, I also have a problem,when I see from prometheus,I find the value not change,I restart the telegraf,the value still not change,when I reboot the server machine,telegraf can collect the interfaces info,but when the server machine and the telegraf run for one night,from prometheus to search the "net_bytes_recv{host=~"master2"}" and "net_bytes_recv{host=~"master2"}" ,the value no change

**Comment by danielnelson** [comment]
It looks like the data is being collected correctly based on the output of the `--test` command.  How are you sending the data to prometheus?  If you are using the prometheus output can you post the config?

**Comment by lurenjia528** [comment]
![dockererror](https://user-images.githubusercontent.com/37833630/38538354-f8f5c0aa-3cc5-11e8-8c1a-76ce66dded00.png)
![output prometheus](https://user-images.githubusercontent.com/37833630/38538355-f944e0cc-3cc5-11e8-9421-973d4c9276b8.png)


otherwise,my docker always "took longer to collect than collection interval (10s)"

**Comment by danielnelson** [comment]
On the prometheus_client output I would set the expiration_interval to no less than 2 times the agent interval.

Looks like the docker daemon is not running in the log messages, but if you get `docker always "took longer to collect than collection interval (10s)"` but eventually you get metrics from docker this probably means your docker cannot keep up.

I think you would get the best results if you ask for help over at the [InfluxData Community](https://community.influxdata.com) site.  That is the best place for general usage questions.
