### ISSUE TITLE
How to limit snmp to a number of interfaces?

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#3958]
I have a router with BRI, LAN1,2,3
then PP[1..100] and TUNNEL[1..100]

In short, 338 interfaces.
Of which all but LAN1, LAN3, PP1,2,3 and TUNNEL 1,2,3,4
are unused.

How do I configure telegraf to not scan three hundred unused interfaces?

**Comment by ivan98** [comment]
Take a look at [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering)

**Comment by danielnelson** [comment]
Using measurement filtering will allow you to remove the values after you collect them, but won't help to reduce the size of the queried data.  If you want to do this you may need to use top level fields, not a table, to select specific OIDs.   I think this is a snmp limitation that we can't improve upon.
