### ISSUE TITLE
[Feature Proposal] [Input: Unbound DNS] Use tag to identify thread of thread-specific metrics 

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/telegraf#3959]
### Proposal:

Create a separate unbound_threads measurement and place there all the thread-specific fields, tagged by the thread id. Probably as an option, as this would duplicate metrics in case of a configuration using a single thread.

### Current behavior:

A single "unbound" measurement line is exported with fields for all threads, for example:

[...]
thread8_requestslist_avg
thread9_requestslist_avg
[...]

### Desired behavior:

A separate measurement "unbound_threads" with the thread-specific values, with a tag "thread" identifying the thread id (thread0 -> threadX)

unbound_threads,thread=8 requestslist_avg=0,num_cachemiss=7 

### Use case:

This would allow queries grouped by thread, enabling easier visualizations on top of the thread specific values.

**Comment by russorat** [comment]
@voiprodrigo thanks for the issue! We will consider this for a future release. If you have any interest in tackling this and submitting a PR, we'd be happy to review.

**Comment by voiprodrigo** [comment]
@russorat I might, as initiation to Go, I have never touched it before. Glad to see the request validated, that was the first step. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by voiprodrigo** [comment]
Hello,

I think I've got this pretty much done, except the tests fail. Telegraf itself does work as expected, as far as I can tell. I'm probably misunderstanding the asserts.

Can someone take a look at https://github.com/voiprodrigo/telegraf/blob/FP-3959-Unbound/plugins/inputs/unbound/unbound_test.go ?

Thanks.

**Comment by voiprodrigo** [comment]
I was not passing a required boolean for the new test function.

I submitted PR #3969

**Comment by russorat** [comment]
@voiprodrigo thanks for submitting a PR. we will take a look.
