### ISSUE TITLE
Mongostat diff when counter goes back to 0

### ISSUE THREAD

**Issue by Clement87** [influxdata/telegraf#396]
Hi,
following this commit : https://github.com/influxdb/telegraf/commit/48d11f0a5c47417856d048e910cebeefb14fdb44#diff-0ddfbde05774dc69c98628f68f9dad7d
In case the counter goes back to 0, the result should be calculated like this : 
d = maxVal - oldVal + newVal
instead of d = newVal
Thanks

**Comment by sparrc** [comment]
@Clement87, can you submit a PR?

**Comment by sparrc** [comment]
@Clement87 could you explain more? What is `maxVal`?

**Comment by sparrc** [comment]
closing, feel free to open if you have more info
