### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by stonefury** [influxdata/telegraf#3963]
Is this the official repo for telegraf support for kubernetes? The doc on installing only mentions a daemon set, no further config information on setting it up.

thanks for any help. I already tried the influxdb forums,  but none of the posts are answered. :-/

**Comment by danielnelson** [comment]
Hey @stonefury, I replied to you on community just a few hours ago, so I hope you have seen that.

We don't maintain any kubernetes deployment files in this repo, just the Telegraf application itself.  I'll steer someone to reply to your issue on https://github.com/influxdata/tick-charts/issues/16.

**Comment by stonefury** [comment]
Oh thank you very much.
