### ISSUE TITLE
Does Telegraf have any Input plugin that can measure Bandwidth between two computers, Like wireshark 

### ISSUE THREAD

**Issue by srikanthvamaraju** [influxdata/telegraf#3967]
Posted this on Influx Community
[https://community.influxdata.com/t/does-telegraf-have-any-input-plugin-that-can-measure-bandwidth-between-two-computers-like-wireshark/4610?u=srikanthvamaraju]

Just wanted to know if i can get any help from here.
I am trying to measure the bandwidth in between two computers and trying to find if telegraf has any input plugins for that, Can you guys please help me if Telegraf has any input plugin already developed for that. Something which is similar to Wireshark.

**Comment by danielnelson** [comment]
No, there isn't a plugin that can do this.  You could look at this pull request and see if it meets your requirements though:  https://github.com/influxdata/telegraf/pull/3649
