### ISSUE TITLE
How to make input plugin collect data on each  :00:00, :05:00, :10:00, ... ?

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#3968]
### System info:

telegraf-1.5
influxdb-1.5
ubuntu16.04

### Steps to reproduce:

[agent]
  interval = "60s"
  round_interval = true

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"] # required
  database = "test" # required
  precision = "s"

 [[inputs.rabbitmq]]
    interval = "5m"
    url = "http://localhost:15672"
    username = "username"
    password = "password"

### Expected behavior:

time                 consumers messages messages_publish queue
----                 --------- -------- ---------------- -----
2018-04-04T05:**40**:00Z 0         0        0                report_queue

### Actual behavior:

time                 consumers messages messages_publish queue
----                 --------- -------- ---------------- -----
2018-04-04T05:**38**:00Z 0         0        0                report_queue

### Additional info:

How to make telegraf collect data on :05:00, :10:00, :15:00, ...

**Comment by danielnelson** [comment]
The agent currently aligns all inputs based on the agent interval, and then begins counting the plugin intervals.  We should fix this.
