### ISSUE TITLE
Add support for string field parsing to json parser data_format

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#3970]
I have the following json:
`{"usecase":"airsensor","temperature":25,"airpressure":1000,"humidity":66,"cellinfo":"none"}`

Which is grabbed by the mqtt plugin and sent over to Influx, however the cellinfo tag is missed and I can't get it saved to Influx, although there's no error message in the logs at all. 

Directly in influx it looks like this:

> select * from mqtt_consumer 
name: mqtt_consumer
time                airpressure host               humidity temperature topic          usecase
1522870357945900068 1000        srv-ubn-services-1 66       25          pycom1/sensors airsensor

For me it looks like, telegraf is somehow cutting the last json tag.

**Comment by danielnelson** [comment]
If you are using an input with `data_format = "json"` remember that only `tag_keys` are collected.

If that's not it can you add your configuration?

**Comment by darox** [comment]
@danielnelson Wow what a fast reply ;)
What do you mean by only tag_keys are collected? Currently only the usecase is set as key tag. In my grafana dashboard, I would also like to display the cellinfo.

**Comment by danielnelson** [comment]
The json format can only create tags, but not fields, from string values, if they are specified in tag_keys.  Otherwise string values are ignored.

We will probably [rewrite the json format soon](https://github.com/influxdata/telegraf/issues/1363) and we would like to [create a processor](https://github.com/influxdata/telegraf/issues/3372) that can promote/demote between tag and fields.

**Comment by darox** [comment]
@danielnelson Hmm, that sounds bad. Actually  that means, that I have to create a single mqtt topic for the cellinfo which is not in json format i order to get it up and working.

**Comment by darox** [comment]
@danielnelson Which options do I have, if the the string coming from mqtt looks like this:
['', '+VZWRSRP: 64,6300,-101.70', '', 'OK', ''] And should be send over to Influx?

**Comment by danielnelson** [comment]
Telegraf doesn't have anything that will parse that, even if it were a valid JSON array with double quotes.

If possible, your best bet is to try to use InfluxDB line protocol as much as you can, since this way you have full access to the InfluxDB data model.

**Comment by darox** [comment]
Ok, I think I found another issue

Now the mqtt message looks like this:
{"humidity": "33.24", "temperature": "24.83", "airpressure": 1008.975, "rsrp": 90}
But the data which is put into influx is just:
1522911631535330647 1005.526    srv-ubn-services-1          90               pycom1/sensors
1522911725524054015 1006.665    srv-ubn-services-1          90               pycom1/sensors
1522911798167292009 1008.975    srv-ubn-services-1          90               pycom1/sensors

Temperature and humidity are missing completely.

**Comment by danielnelson** [comment]
They are being ignored because they are strings

**Comment by darox** [comment]
Ou sorry, that was my fault... :( 

I could fix it.

**Comment by russorat** [comment]
closing this in favor of https://github.com/influxdata/telegraf/issues/1363 and https://github.com/influxdata/telegraf/issues/3372 referenced above
