### ISSUE TITLE
Undocumented features in --help

### ISSUE THREAD

**Issue by woockashek** [influxdata/telegraf#3979]
There are some useful options in telegraf on windows that are not exposed in telegraf --help:
- console
- service

I have found them inspecting the code while investigation why telegraf is not working when launched as subprocess of my service.

**Comment by danielnelson** [comment]
I'll add those to the usage message, you might also be interested in these docs:

https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md

I'm assuming you needed to add `--console` when you ran it as a subprocess?

**Comment by woockashek** [comment]
Yes, without `--console` I'm getting following error:

> 2018/04/09 15:32:34 E! The service process could not connect to the service controller.

Thanks for the link.
