### ISSUE TITLE
httpjson plugin can't parse input with strings

### ISSUE THREAD

**Issue by rullmann** [influxdata/telegraf#3982]
### Relevant telegraf.conf:

```
[[inputs.httpjson]]
  servers = [
    "https://api.coinmarketcap.com/v1/ticker/monero/?convert=EUR",
  ]

  name_prefix = "cmc_"
```

### System info:

* Fedora 27
* telegraf-1.5.3-1.x86_64 (InfluxData Repo)

### Steps to reproduce:

* Add the above config
* Run the test with `telegraf --config /etc/telegraf/telegraf.d/coinmarketcap.conf -test`

### Expected behavior:

* Some output like:

```
* Plugin: inputs.httpjson, Collection 1
> cmc_httpjson,server=https://api.coinmarketcap.com/v1/global/?convert\=EUR,host=localhost price_usd=163.056 ...
```

* Strings in the output should be ignored
* This behaviour should be documented
* `tag_keys` option should still work, to set this to `id` for example

### Actual behavior:

```
# telegraf --config /etc/telegraf/telegraf.d/coinmarketcap.conf -test
* Plugin: inputs.httpjson, Collection 1
```

### Additional info:

* Relates to #3599

**Comment by danielnelson** [comment]
The JSON data format is documented [here](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json), can you read it and let me know if it seems unclear?

I grabbed this url and got:
```
$ curl https://api.coinmarketcap.com/v1/ticker/monero/?convert=EUR
[
    {
        "id": "monero", 
        "name": "Monero", 
        "symbol": "XMR", 
        "rank": "11", 
        "price_usd": "163.314", 
        "price_btc": "0.024661", 
        "24h_volume_usd": "43177900.0", 
        "market_cap_usd": "2597424802.0", 
        "available_supply": "15904483.0", 
        "total_supply": "15904483.0", 
        "max_supply": null, 
        "percent_change_1h": "0.07", 
        "percent_change_24h": "-5.79", 
        "percent_change_7d": "-5.32", 
        "last_updated": "1523051942", 
        "price_eur": "133.039013994", 
        "24h_volume_eur": "35173624.0759", 
        "market_cap_eur": "2115916789.0"
    }
]
```

Since everything is a string, nothing is captured.  The reason why tag_keys can't help here is because there must be at least one field in Line Protocol.

You may also be interested in these issues:
- https://github.com/influxdata/telegraf/issues/1363
- https://github.com/influxdata/telegraf/issues/2835

**Comment by rullmann** [comment]
@danielnelson: Thanks for pointing this out. I have ignored the line stating that everything within quotes will be ignored.
Basically the API is sending a valid, but still in logical terms wrong object as all the int objects shouldn't be quoted.

**Comment by ahb-sjsu** [comment]
Hi Rico Ullman,

It's not clear why you closed this issue. Your response doesn't make any sense. 

"I have ignored the line stating that everything within quotes will be ignored." -- What does that mean?

"Basically the API is sending a valid, but still in logical terms wrong object as all the int objects shouldn't be quoted."

They are not "int objects".. 

Daniel included objects in the json that are NOT ints:

        "id": "monero", 
        "name": "Monero", 
        "symbol": "XMR", 

Please explain how to encode this in json data format so it can be accepted by telegraf and not give ERROR:

2018-08-23T22:34:21Z E! Error in plugin [inputs.exec]: unable to parse out as JSON Array, invalid character 'r' looking for beginning of value

Andrew.
