### ISSUE TITLE
HTTP status 406 returned on prometheus input plugin

### ISSUE THREAD

**Issue by KavyaKanupuru** [influxdata/telegraf#3986]
### Relevant telegraf.conf:

[[inputs.prometheus]]
  urls = ["http://localhost:8080/metrics"]

### System info:
Telegraf v1.4.2

### Steps to reproduce:

1. To config add the above configuration , mapping prometheus url (metrics in prometheus format)

### Expected behavior:
Metrics should be available on the outputs defined

### Actual behavior:
Error in plugin [inputs.prometheus]: http://localhost:8080/metrics returned HTTP status 406 

### Additional info:

Running the application on open stack server

**Comment by KavyaKanupuru** [comment]
@danielnelson The server is returning content-type= "text/plain; version=0.0.4;charset=utf-8"

**Comment by danielnelson** [comment]
Hmm, it seems like this should be acceptable.  Can you tell me a little about the service you are monitoring?  For instance, is it a particular application or a custom service?  If it is a custom service are you using the official prometheus client libraries and if so which language/version?

**Comment by danielnelson** [comment]
I think this is your issue: https://github.com/prometheus/client_java/issues/265

**Comment by danielnelson** [comment]
I wonder if adding a charset would work around this issue until you can update.  Would you be able to test using something like curl and see if sending the header like this helps:
```
Accept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;charset=utf-8;q=0.3
```

**Comment by KavyaKanupuru** [comment]
Hi Daniel, I tried to curl the url with 0.0.21 Prometheus version. Even the curl command was throwing 406 error.As suggested in the issues you redirected me,I have changed the version to 0.0.24 and after changing the version I could curl the url with header content type 'text/plain' without any error.

**Comment by danielnelson** [comment]
Okay, glad you have it working, I'm going to close this issue then since I don't think we can do anything here.
