### ISSUE TITLE
Add individual systemd unit id to procstat metrics

### ISSUE THREAD

**Issue by Eelis** [influxdata/telegraf#3988]
### Proposal:

Currently, if you configure the procstat input plugin with `systemd_unit = bla*`, and there are two units `blaa` and `blab`, then the metrics produced by procstat for both `blaa` and `blab` will have tag `systemd_unit=bla*` (with the asterisk). It would be useful to also have a tag that is set to `blaa` for `blaa`'s metrics and `blab` for `blab`'s metrics.

### Use case:

I use a wildcard like `systemd_unit = myapp*` to select units because I use systemd instantiated services which have unit IDs like `myapp@0.service`, `myapp@1.service`, etc.  In my dashboard I want to show resource usage for each service instance, and I want to label them with their individual unit ID.

**Comment by Eelis** [comment]
I suspect this might be easy to implement, because the code already calls "systemctl show <unit>", the output of which includes `Id=` fields.

**Comment by phemmer** [comment]
The request seems reasonable.

The code will need to be restructured quite a bit though. It wasn't actually designed to handle multiple units. That is does is more of an oversight when I was writing it :-).  
First the code doing PID extraction is going to need to understand how to extract multiple PIDs, as well as multiple unit IDs, and correlate the 2.  
Then the calling code (`updateProcesses` and `findPids`) is going to need to be rewritten a bit as it only handles a list of PIDs. It wasn't designed to handle different tags per PID.

**Comment by Eelis** [comment]
Cool, that makes a lot of sense, thanks!

**Comment by danielnelson** [comment]
The tags on this plugin behave in this way, they show the value searched for instead of the actual matched value.  For example if you have `user = "telegraf,root"` then the tag will be `user=telegraf\,root`.

I think we could change this behavior across the board to show the matched value without it causing problems for anyone.

**Comment by phemmer** [comment]
I don't know that we want to change the existing tag. Being able to group all units matching the tag you specified could be useful. I think in this case we want a new tag indicating which unit was matched.

**Comment by danielnelson** [comment]
If we were designing from scratch I would push heavily for only showing the matched value, if you want to group based on a config value you could add a tag statically in the configuration file.

But obviously we don't want to bust anyone's charts either, and the safest bet would be to add new tags.

**Comment by phemmer** [comment]
Another item for #2320 then?

**Comment by danielnelson** [comment]
Maybe we should introduce the new behavior only if an option is set.  I've been experimenting with this technique recently, and I think it is reasonable to do it one of two ways:
- Add an option called `metric_version = 2`; probably best for large changes
- Add a more targeted option like `tag_match_value = true`; which could be useful for small changes.

This way the change exists now, and when we decide to do a 2.0 we can just drop the old method.  If we provide at least one version where you can output in both formats then it will make migrating much easier.  This means pretty everything we want in 2.0 should probably be implemented now.

**Comment by Eelis** [comment]
@MyaLongmire Nah, I personally have no use for this change anymore. Feel free to close. Thanks.

**Comment by MyaLongmire** [comment]
@Eelis, thank you for getting back to me :) If you need this reopen in the future let me know
