### ISSUE TITLE
Add an input plugin for iBMC (Huawei Server)

### ISSUE THREAD

**Issue by vipsql** [influxdata/telegraf#3990]
not a bug issue!
consider support ibmc(huawei server) input plugins to collect the server sensors info and so on...?

**Comment by danielnelson** [comment]
@vipsql Do you have any ideas on what metrics we should collect?  If you have a link to some API documentation on metrics that would be ideal.

**Comment by vipsql** [comment]
it can gets the metric via RedFish REST-APIS

**Comment by sarvani95** [comment]
Hi @danielnelson  and @vipsql, I have written a go script to get the hardware metrics like temperature, fan speed, etc via Redfish REST-APIs. I would like to contribute the go script as telegraf plugin, it would be helpful for getting hardware metrics.

**Comment by danielnelson** [comment]
Can you open a pull request?

**Comment by sarvanikonda** [comment]
I have opened a pull request https://github.com/influxdata/telegraf/pull/7082

**Comment by sspaink** [comment]
Resolved by https://github.com/influxdata/telegraf/pull/7082
