### ISSUE TITLE
Add an input plugin for Hbase or Hadoop metric

### ISSUE THREAD

**Issue by vipsql** [influxdata/telegraf#3998]
Add an input plugin for collect Hbase or Hadoop metric

**Comment by arkady-emelyanov** [comment]
Please check https://docs.wavefront.com/hadoop-hdfs.html#step-3-configure-telegraf-jolokia-input-plugin

I belive `Jolokia2` plugin should do the trick for each Hadoop subsystem (HDFS, HBase, Yarn, etc..).

**Comment by danielnelson** [comment]
@puckpuck I'd love to add this to the [Jolokia example configurations](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2#example-configurations), is this something that you would be willing to add?

**Comment by puckpuck** [comment]
Yeah I can do that.  Will get submit a PR in the next day or so (crazy busy right now).  I can also scan our other Jolokia2 examples and will add any others I find useful as well.
