### ISSUE TITLE
Allow DSN in mysql input to use the default port

### ISSUE THREAD

**Issue by eohan01** [influxdata/telegraf#4007]
## Directions

when using telegraf to scrap MySQL/MariaDB you use the servername:port syntax and when the data arrives in InfluxDB the server name also has the :3306 port (or what ever port you use) in the server name in the influxDB database

### Relevant telegraf.conf:

[[inputs.mysql]]
servers = ["user:password@tcp(server.node.name.com:3306)/?tls=false"]

### System info:
Telegraf v1.5.3 (git: release-1.5 1e519698)

### Steps to reproduce:
1. configure any MYSQL server to be monitored by telegraf
2. look up the data in InfluxDB.  it will have the port number attached to the server.name

### Expected behavior:

to not have the port number as part of the server data tagged in influxdb
### Actual behavior:
server name data in influxdb appears as servername:port
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:
server name data in influxdb appears as servername:port
### Desired behavior:
to not have the port number be part of the server data tagged in influxdb so you can report on other data using the servername from other collectors without having to use a regex to get rid of the :portnumber from the server name

### Use case: [Why is this important (helps with prioritizing requests)]
see above desired behavior

**Comment by eohan01** [comment]
Yes.   That would be fine

Sent from my iPhone

On Apr 11, 2018, at 5:21 PM, Daniel Nelson <notifications@github.com<mailto:notifications@github.com>> wrote:


We could make it so that if the port is not specified: user:password@tcp(server.node.name.com<http://server.node.name.com>)/?tls=false it will use the default port and the port number will not be added to the tag. Would this work for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_influxdata_telegraf_issues_4007-23issuecomment-2D380599527&d=DwMFaQ&c=MtgQEAMQGqekjTjiAhkudQ&r=slHasr0SDOiMLOPGUL_Z0e7e8hftXf_O7q_0qmrLjaw&m=CcUl8f-XViGT1lOGllzRw4dw3Z7xbwgM0xDWF7ssJPk&s=Tr7qF5kuqW6mPWGFSAMvepyJ2WMUoOz3uNej7ro0Ovk&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae1gwsAwE6RDs-2DV5JorlOkbA13BUa4IIks5tnnPXgaJpZM4TQff9&d=DwMFaQ&c=MtgQEAMQGqekjTjiAhkudQ&r=slHasr0SDOiMLOPGUL_Z0e7e8hftXf_O7q_0qmrLjaw&m=CcUl8f-XViGT1lOGllzRw4dw3Z7xbwgM0xDWF7ssJPk&s=zo9J34ohj5oTYrOOkQ2NjdlmEC_DOaTFMQ6CTAD33RI&e=>.

________________________________

The information in this Internet Email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this Email by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. When addressed to our clients any opinions or advice contained in this Email are subject to the terms and conditions expressed in any applicable governing The Home Depot terms of business or client engagement letter. The Home Depot disclaims all responsibility and liability for the accuracy and content of this attachment and for any damages or losses arising from any inaccuracies, errors, viruses, e.g., worms, trojan horses, etc., or other items of a destructive nature, which may be contained in this attachment and shall not be liable for direct, indirect, consequential or special damages in connection with this e-mail message or its attachment.

**Comment by srebhan** [comment]
@eohan01 the same can be achieved by simple removing the port after the input plugin e.g. by
```toml
[[processors.regex]]
  namepass = ["mysql*"]
  [[processors.regex.tags]]
    key = "server"
    pattern = '^(.*):\d+$'
    replacement = "${1}"
```
Closing the issue as solved. Please reopen in case I'm missing something...
