### ISSUE TITLE
logparser can not handle  timestamp like 2018-04-11 10:04:20,859

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#4013]
### Relevant telegraf.conf:

patterns = ['''%{TIMESTAMP_ISO8601:asctime:ts-"2006-01-02 15:04:05,000"} \[%{DATA:name:string}\] %{LOGLEVEL_PYTHON:levelname:string}: %{GREEDYDATA:message:string}''']

custom_patterns =  '''
         LOGLEVEL_PYTHON (?:WARNING|ERROR|CRITICAL)
 '''

### System info:

telegraf-1.6.0

ubuntu14.04

### Steps to reproduce:

$ sudo service telegraf restart
$ echo 2018-04-11 10:04:20,859 [lib.test] ERROR: test test test >> test.log

### Expected behavior:

parse log into output plugin.

### Actual behavior:

2018-04-12T06:34:46Z E! Error parsing 2018-04-11 10:04:20,859 to time layout [2006-01-02 15:04:05]: parsing time "2018-04-11 10:04:20,859": extra text: ,859

2018-04-12T06:36:48Z E! Error parsing 2018-04-11 10:04:20,859 to time layout [2006-01-02 15:04:05,000]: parsing time "2018-04-11 10:04:20,859" as "2006-01-02 15:04:05,000": cannot parse "859" as ",000"

### Additional info:

[Include gist of relevant config, logs, etc.]

when I use string instead of ts, it works.
But, how to handle the  ",859" in telegraf?

**Comment by crazy-canux** [comment]
BTW,   tag didn't work here.
I want to make levelname as a tag. but it still a field.

patterns = ['''%{TIMESTAMP_ISO8601:asctime:string} \[%{DATA:name:string}\] %{LOGLEVEL_PYTHON:levelname:tag}: %{GREEDYDATA:message:string}''']

**Comment by danielnelson** [comment]
We have an issue open for this #3571, unfortunately there is not a known workaround at this time.
