### ISSUE TITLE
telegraf - fqdn issue

### ISSUE THREAD

**Issue by iatalay** [influxdata/telegraf#4014]
## Bug report
We have configured telegraf to send data to kafka. We used fully qualified domain name in conf file as following;
brokers = ["kafka1.mydomain:9092","kafka2.mydomain:9092","kafka3.mydomain:9092"]

However telegraf ignores domain (mydomain) and trying to connect hostname (kafka2) only and it couldn't solve hostname.
Using ip address is not a solution, telegraf still trying to connect using hostname even if we set ip address in conf file.

### Relevant telegraf.conf:
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  logfile = "/Program Files/Telegraf/telegraf.log"
  hostname = ""

[[outputs.kafka]]
  brokers = ["kafka1.mydomain:9092","kafka1.mydomain:9092","kafka1.mydomain:9092"]
  topic = "telegraf"
  routing_tag = "host"
  compression_codec = 0
  required_acks = -1
  max_retry = 3
  data_format = "influx"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "Current Disk Queue Length",
      "% Free Space",
      "Free Megabytes",
    ]
    Measurement = "win_disk"

  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
    ]
    Measurement = "win_diskio"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec",
      "Packets Received Discarded",
      "Packets Outbound Discarded",
      "Packets Received Errors",
      "Packets Outbound Errors",
    ]
    Measurement = "win_net"

  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "System Up Time",
    ]
    Instances = ["------"]
    Measurement = "win_system"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes",
    ]
    Instances = ["------"]
    Measurement = "win_mem"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Paging File"
    Counters = [
      "% Usage",
    ]
    Instances = ["_Total"]
    Measurement = "win_swap"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Sent/sec",
      "Bytes Received/sec",
      "Packets Sent/sec",
      "Packets Received/sec",
      "Packets Received Discarded",
      "Packets Received Errors",
      "Packets Outbound Discarded",
      "Packets Outbound Errors",
    ]

### System info:

Windows Server 2008 R2 Enterprise

Telegraf v1.6.0~rc3 (git: release-1.6 3c039921)

### Expected behavior:
Telegraf should be aware of domain (fully qualified hostname)

### Additional info:

2018-04-11T13:10:00Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp: lookup **kafka2**: no such host

2018-04-11T13:10:18Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp: lookup **kafka2**: no such host

2018-04-11T13:10:27Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp: lookup **kafka2**: no such host

**Comment by danielnelson** [comment]
I can't think of any reason why the full host wouldn't be used.  Can you add the full logs from startup?

**Comment by iatalay** [comment]
I realized that telegraf is able to establish connection with **one of our kafka** using fqdn. 
However, it is also trying to connect **another kafka** using hostname (without domain) somehow, so it cannot resolve.
Because of this, telegraf is not collecting data or send data to kafka.

*** telegraf.conf
brokers = ["klmetkfkt1.mydomain:9092","klmetkfkt2.mydomain:9092","klmetkfkt3.mydomain:9092"]

*** kafka ip's
klmetkfkt1.mydomain >> 10.yy.yy.154
klmetkfkt2.mydomain >> 10.yy.yy.156
klmetkfkt3.mydomain >> 10.yy.yy.159

*** after telegraf is started, it establishes connection with one of our kafka
C:\Windows\system32>netstat -an | findstr 9092
  TCP    10.xx.xx.xx:50118      **10.yy.yy.154**:9092     ESTABLISHED

*** ping with domain resolves ip address
C:\Windows\system32>ping KLMETKFKT1.mydomain
Pinging KLMETKFKT1.mydomain[10.yy.yy.154] with 32 bytes of data:
Reply from 10.yy.yy.154: bytes=32 time<1ms TTL=63
Reply from 10.yy.yy.154: bytes=32 time<1ms TTL=63

*** you cannot resolve without fqdn
C:\Windows\system32>ping KLMETKFKT1
Ping request could not find host KLMETKFKT1. Please check the name and try again.

*** I have attached log. In this case, agent connected to KLMETKFKT1.mydomain and trying to resolve KLMETKFKT2. It should use fqdn as KLMETKFKT2.mydomain to resolve host.

[telegraf.log](https://github.com/influxdata/telegraf/files/1918239/telegraf.log)

**Comment by danielnelson** [comment]
Is this something that is only happening on Windows or do you see it on your RHEL machines as well?

**Comment by iatalay** [comment]
Im my opinion, this is happening If kafka hosts and telegraf host are located on different domains.

**Comment by iatalay** [comment]
Yesterday, I tried running telegraf on Linux on different domain, yes, there is not any problem with Linux.
Issue is related to windows environment. Using ip adress did not solve the issue on windows. Updating hosts file solve problem but it is not allowed to change this file in my company.

**Comment by danielnelson** [comment]
> Using ip adress did not solve the issue on windows.

Can you show me the `brokers` line and what the log error was when you tried this?

**Comment by iatalay** [comment]
I tried again with ip a moment ago.

**CONFIG**
[[outputs.kafka]]
  ## URLs of kafka brokers
  brokers = ["10.xx.xx.154:9092","10.xx.xx.156:9092","10.xx.xx.159:9092"]
  ## Kafka topic for producer messages
  topic = "telegraf"

**LOG**
2018-04-19T08:42:11Z D! Attempting connection to output: kafka
2018-04-19T08:42:11Z D! Successfully connected to output: kafka
2018-04-19T08:42:11Z I! Starting Telegraf v1.6.0~rc3
2018-04-19T08:42:11Z I! Loaded outputs: kafka
2018-04-19T08:42:11Z I! Loaded inputs: inputs.win_perf_counters
2018-04-19T08:42:11Z I! Tags enabled: host=KWBFXMANT2
2018-04-19T08:42:11Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"KWBFXMANT2", Flush Interval:10s 
2018-04-19T08:42:30Z D! Output [kafka] buffer fullness: 196 / 1000 metrics. 
2018-04-19T08:42:40Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp: lookup KLMETKFKT2: no such host

2018-04-19T08:42:40Z D! Output [kafka] buffer fullness: 294 / 1000 metrics. 
2018-04-19T08:42:47Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp: lookup KLMETKFKT2: no such host

2018-04-19T08:42:50Z D! Output [kafka] buffer fullness: 392 / 1000 metrics.

**Comment by danielnelson** [comment]
What I'm confused about is if we are using IP addresses where is the host name coming from?  How do we even know about KLMETKFKT2?
```
lookup KLMETKFKT2: no such host
```

**Comment by iatalay** [comment]
I asked windows admins. They didn't have any idea about how/where telegraf finds the hostname.
What do you think? Is it a bug?

**Comment by danielnelson** [comment]
I have no idea, does your configuration contain the `KLMETKFKT2` string at all?  Or maybe, and I'm just making things up, there is a way in Kafka for them to share the hostname of other nodes?

**Comment by iatalay** [comment]
No, there isn't any string containing KLMETKFKT2. Telegraf finds the hostname itself. 
I am not sure about kafka's working style.

**Comment by iatalay** [comment]
@danielnelson 
finally we found the solution.
setting following properties with fqdn in server.properties files on kafka side solved the issue.

listeners = PLAINTEXT://KLMETKFKT2.mydomain:9092
advertised.listeners=PLAINTEXT://KLMETKFKT2.mydomain:9092

**Comment by danielnelson** [comment]
Cool, thanks for the update.
