### ISSUE TITLE
mongodb - missing metrics

### ISSUE THREAD

**Issue by iatalay** [influxdata/telegraf#4015]
## Bug report
Telegraf is not collecting some metrics for mongodb plugin.

### Relevant telegraf.conf:
[[inputs.mongodb]]
  servers = ["mongodb://usrtelegraf:teleusr@node11.mydomain:27018"]

### System info:

db.createUser( { "user" : "usrtelegraf", "pwd": "teleusr", roles: [ "root" ] } )

mongodb version 3.6
Telegraf v1.6.0~rc3 (git: release-1.6 3c039921)
Windows Server 2008 R2 Enterprise

### Expected behavior:
Telegraf has to collect metrics mentioned in the following link;
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mongodb

### Actual behavior:
mongodb_db_stats & mongodb_shard_stats meausurements are missing.
mongodb measurement has missing fields.

### Additional info:

C:\Program Files\Telegraf>telegraf --input-filter mongodb --test
2018/04/12 11:37:43 I! Using config file: C:\Program Files\Telegraf\telegraf.conf
* Plugin: inputs.mongodb, Collection 1
* Plugin: inputs.mongodb, Collection 2
> mongodb,host=node11,hostname=node11.mydomain:27018 flushes_per_sec=0i,total_created=0i,commands_per_sec=4i,queued_reads=0i,inserts_per_sec=0i,percent_cache_used=0,wtcache_server_evicting_pages=0i,wtcache_app_threads_page_read_count=11i,getmores_per_sec=0i,jumbo_chunks=0i,total_refreshing=0i,wtcache_worker_thread_evictingpages=0i,wtcache_current_bytes=73020i,queries_per_sec=0i,resident_megabytes=116i,open_connections=10i,wtcache_max_bytes_configured=8052015104i,wtcache_app_threads_page_write_count=20i,updates_per_sec=0i,wtcache_app_threads_page_read_time=0i,wtcache_bytes_written_from=90921i,net_in_bytes=296i,total_available=0i,wtcache_bytes_read_into=47312i,ttl_passes_per_sec=0i,queued_writes=0i,vsize_megabytes=939i,wtcache_pages_evicted_by_app_thread=0i,wtcache_tracked_dirty_bytes=0i,net_out_bytes=26989i,ttl_deletes_per_sec=0i,deletes_per_sec=0i,percent_cache_dirty=0,wtcache_pages_queued_for_eviction=0i,active_writes=0i,active_reads=1i,total_in_use=0i 1523522264000000000

**Comment by russorat** [comment]
@iatalay i believe this PR adds those metrics: https://github.com/influxdata/telegraf/pull/3819. It will be in the 1.7 release or the nightlies.

**Comment by danielnelson** [comment]
The `mongodb_db_stats` are in 1.6, but you need to have the setting: `gather_perdb_stats = true`.  The shard stats are indeed only in 1.7.
