### ISSUE TITLE
mqtt plugin documentation needs an update

### ISSUE THREAD

**Issue by cdjc** [influxdata/telegraf#4016]
In particular, "topic" is now "topic_prefix"

**Comment by danielnelson** [comment]
Thanks for the report, I just fixed this issue.  Is there any other issues you think should be improved?

**Comment by cdjc** [comment]
That's quick! Thanks!
I'll let you know if I find anything else.

**Comment by danielnelson** [comment]
I'm your man when it comes to typos :)
