### ISSUE TITLE
Update InfluxDB Input Plugin to capture AE stats being exposed with InfluxDB 1.6

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#4017]
## Feature Request

InfluxDB Enterprise 1.6 introduces a new service which reports on shard consistency.  Telegraf input plug-in should have an optional configuration setting to allow for collection of the shard consistency status and other details exposed.

### Proposal:
Create optional configuration setting to capture Anti Entropy (AE) service metrics as part of the shard consistency reports.  Ensure that the plugin, by default works with both OSS and Enterprise editions of the database.  Hence, this will require users to active that portion of the configuration when this input plugin is used with the Enterprise edition.

### Current behavior:
No AE stats are captured.

### Desired behavior:
Capture and report on AE shard consistency status, allowed for alerting and notifications to be setup, if shard inconsistencies are detected.  Also allows for timestamp to be captured indicating when these inconsistencies were detected.

**Comment by danielnelson** [comment]
@timhallinflux Can you add a link to the docs for the metrics in question?

**Comment by sjwang90** [comment]
@timhallinflux Can you provide a link to the Anti Entropy (AE) service metrics?

**Comment by timhallinflux** [comment]
I think this just happens... and we simply need to update the documentation in the README: https://github.com/influxdata/telegraf/blob/release-1.16/plugins/inputs/influxdb/README.md

you can see the list of all supported metrics (and cross check them to ensure they are up-to-date with the 1.8 release here: 

https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/

This includes which metrics are "enterprise only".
