### ISSUE TITLE
No relevant url or hostname information for remote phpfpm check

### ISSUE THREAD

**Issue by jcarnat** [influxdata/telegraf#4028]
Hi,

I'm using a telegraf container to check for various remote hosts and services and store data in influxdb.
When checking for remote php-fpm services, the stats gathering works but I "loose" the remote server name information. In influxdb, I can't filter on remote server name.

The "pool" tag is stored but not the "url" one.

### Relevant telegraf.conf:
[[inputs.phpfpm]]
	urls = ["http://remote_server/fpm-status?full"]

### System info:
telegraf:1.5.3-alpine

### Actual behavior:
select * from phpfpm where time > now() - 2m
name: phpfpm
time                 accepted_conn active_processes dc         host     idle_processes listen_queue listen_queue_len max_active_processes max_children_reached max_listen_queue pool slow_requests total_processes
----                 ------------- ---------------- --         ----     -------------- ------------ ---------------- -------------------- -------------------- ---------------- ---- ------------- ---------------
2018-04-17T08:55:00Z 962582        1                paris   Telegraf 0              0            0                7                    0                    0                www  0             1
2018-04-17T08:56:00Z 962587        1                paris   Telegraf 0              0            0                7                    0                    0                www  0             1

FYI, "Telegraf" is the container name.

**Comment by danielnelson** [comment]
Thanks for the report, I believe this was fixed/added in 1.6.0 (released yesterday).
