### ISSUE TITLE
Improve mysql plugin

### ISSUE THREAD

**Issue by daviesalex** [influxdata/telegraf#403]
The telegraf MySQL plugin is extremely simple (runs SHOW GLOBAL STATUS) and parses a small number of counters from it).

We propose to work on an improved plugin that mimics the functionality of the best open source plugin today (https://github.com/prometheus/mysqld_exporter). This includes data from the performance schema (if enabled), information schema, some replication commands and so on. We also intend to add monitoring of Galera statistics.

Filing this issue here before we commence work to get any feedback from the community; if not we will work on this and share early code/a PR.

**Comment by skynet** [comment]
:+1:

**Comment by miguel250** [comment]
@daviesalex any update on this?

**Comment by daviesalex** [comment]
@miguel250, not just yet, but we have started work on this and hope to have something to share in January.

**Comment by kureikain** [comment]
@daviesalex Are you working on this? I have an idea to report information of each table(records count, last write,..) and exec a configured MySQL query, then gather field to report to InfluxDB? Can I join your effort.

**Comment by Maksadbek** [comment]
Hi @kureikain, Currently I am working on it, almost finished. Only fixing metric names and tags is left.

**Comment by kureikain** [comment]
Thanks @Maksadbek So exicting :)
