### ISSUE TITLE
Whether the index name can be customized in the input of telegraf.

### ISSUE THREAD

**Issue by zy93xy** [influxdata/telegraf#4031]
Hello, may I ask "telegraf" to change the name of the metrics to a custom and then put it into the influxdb, so that different people can understand the meaning of these indicators?

**Comment by danielnelson** [comment]
I'm not sure I understand, but perhaps you are looking for the `name_override` option that can be added to any input?

[Here is an example in the documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-prefix-suffix-and-override)

**Comment by zy93xy** [comment]
yes, For example: change to "hello" short name, can telegraf and influxdb support conversion?
![image](https://user-images.githubusercontent.com/28784625/38904354-80317930-42dc-11e8-8e29-3aa2a1cdfd09.png)

**Comment by danielnelson** [comment]
I don't understand, can you try to explain in more depth and also let me know what inputs you are using.

**Comment by zy93xy** [comment]
![qq 20180418215143](https://user-images.githubusercontent.com/28784625/38940193-2c1b75d2-435c-11e8-872d-a8b1d4ca862c.png)
![qq 20180418221452](https://user-images.githubusercontent.com/28784625/38940194-2c767ae0-435c-11e8-92ba-52e2e445658b.png)


Sorry, for example, the following two pictures, I will "Data acquisition, the index of the metrics into influxdb, can see the Data is very long and it is not easy to know, before I want to put it into influxdb, replace, with brief to understand the name of the conversion can be realized name please?

**Comment by danielnelson** [comment]
I think you can do this with the `jolokia2` input, which you should try to move to as it replaces the old `jolokia` input.  You can use the [field_name](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2#jolokia-metric-configuration) option to replace the name, is this what you are looking for?

**Comment by zy93xy** [comment]
ok，Thank you very much
