### ISSUE TITLE
Telegraf check Output status before reading from Input

### ISSUE THREAD

**Issue by cyber035** [influxdata/telegraf#4032]
Hi,
Im using Telegraf Input as Kafka consumer and Output to InfluxDB.

My question is, is there a way for Telegraf to check first if there is a up and alive InfluxDB on output, before reading from Kafka input?

Situation:
If InfluxDB service is down, Telegraf will collect data from input (Kafka) and try and fail to send it to Influxdb.
This will cache data locally for output until InfluxDB gets back online.

This will read data from Kafa and commit it, but I want to leave data in Kafa queue until InfluxDB is up and alive.

Is there a way for Telegraf to check Output before reading from Input?

**Comment by danielnelson** [comment]
No, there isn't a way to do this currently.  This would be helped greatly by doing #3984, but I think it might still make sense to have some basic flow control for consumer inputs.

**Comment by danielnelson** [comment]
Closing since #3984 was completed, this should achieve the same results.  The new setting `max_undelivered_messages` controls how many queue messages are read before they are delivered.
