### ISSUE TITLE
Uptime missing when running in docker container

### ISSUE THREAD

**Issue by lpic10** [influxdata/telegraf#4037]
### System info:
telegraf 1.6 running inside docker  (CentOS Linux release 7.3.1611)
host: RHEL 7.4

Telegraf 1.6 is not retrieving the uptime information when running inside the container from some hosts.

Possibly related to issue https://github.com/shirou/gopsutil/issues/507 and recent gops update

**Comment by danielnelson** [comment]
Can you check if the upstream bugfix solves the issue?  I think this can probably wait for 1.7, which would be safer than pulling in a new release of gopsutil.

**Comment by lpic10** [comment]
Yes, it seems to do the trick. 
As telegraf is using gopsutils just one commit behind this one, I've opened a PR to update to it. So should be safe to apply to 1.6
