### ISSUE TITLE
Cannot establish connection with snmp agent

### ISSUE THREAD

**Issue by user9595** [influxdata/telegraf#4038]
Hello,
I am working on a project that involves getting snmp data from my routers which are situated in Gns3 to telegraf later on to influxDB and finally to grafana , however i can't seem to establish a connection between Gns3 and the telegraf file .
Thank you ,

**Comment by russorat** [comment]
@user9595 sorry i am having trouble understanding the question. Could you post the relevant parts of your telegraf config file?

**Comment by user9595** [comment]
Hello,
First of all thank you for taking interest to helping me with my issue.
Okay so basically I have an architecture on Gns3 that I would like to monitor using 'snmp walk '.
After following several tutorials I managed to install Telegraf , InfluxDB , Grafana (added influx as a data source) .
Now my problem is the connection between my architecture and telegraf  , due to telegraf being a conf file all you have to do is to add your requested Inputs and outputs , for this case my output is influxdb and my inputs should be (my snmp agent)???
I managed to add a cloud to my architecture and configure it also I installed snmpB and added a snmp agent but I'm not sure how to get my snmp data to from Gns3 to Telegraf .
I would be very grateful if someone could help me find a solution this project is very important to me !
Feel free to correct me if I have mistaken anything , but this is my first time working with such tools .

Bellow is my Telegraf.conf
![telegraf11](https://user-images.githubusercontent.com/38493300/39083930-f4106f66-4564-11e8-8c97-83e4bad3e1de.PNG)

My snmpB agent
![snmpb1](https://user-images.githubusercontent.com/38493300/39083932-f9212414-4564-11e8-9dd9-cfc62f15b05d.PNG)

this means that telegraf is collecting snmp data I guess ?
![collection1](https://user-images.githubusercontent.com/38493300/39083984-e4c1dd1e-4565-11e8-873a-5cee982a6530.PNG)


My Grafana dashboard that I want to create , I can't seem to find snmp from the measurements to select it 
![grafana11](https://user-images.githubusercontent.com/38493300/39083951-57ffde80-4565-11e8-98a7-8c3c3bdb7d0b.PNG)

**Comment by user9595** [comment]
Hello @danielnelson 
Thank you for responding.
I tried removing the tag field , but nothing has changed .
I don't really know how to work my way around this , I don't even know what's wrong as I said this is my first time working with such programs .
All I want is to is to get data by using snmpwalk such as the cpu and how much traffic the router is carrying and I'm not quit sure how to configure that or where do I get their OIDs if my snmp input format is correct then  all I have to do is get the oids of the fields .

bellow is my error log (telegraf)
![err](https://user-images.githubusercontent.com/38493300/39173464-b1f7970a-479c-11e8-8468-08a96e2cd63e.PNG)

**Comment by danielnelson** [comment]
I think it would be best to ensure snmp is working properly, can you install [net-snmp](http://www.net-snmp.org/) and run the command:
```
snmpget -v2c -c public 192.168.1.1 .1.3.6.1.2.1.1.5.0
```
