### ISSUE TITLE
Add Write Complete From Output Plugin Back to Input Plugin

### ISSUE THREAD

**Issue by dp1140a** [influxdata/telegraf#4058]
Currently there is no communication channel from output plugins to input plugins (only from Input plugins to Output plugins via the metrics channel).  Adding a channel for Output Plugins to communicate to the input plugins will allow for situations like write consistency checks or other scenarios.  This would be very helpful for allowing Telegraf to provide some measure of guaranteed (or close to a guarantee as we can get) delivery of data to the output plugin.

For example if I have a kafka consumer input plugin and a  influxdb output plugin (lets assume I have a write consistency of one).  In this case once InfluxDB acknowledges the that it has received and completed the write, the outpt plugin can notify the kafka_consumer input plugin which will then move the topic offset to get the next batch of points.   If the kafka_consumer input plugin does not receive a write complete it will not move the offset and attempt to re-write the previous batch.

**Comment by danielnelson** [comment]
There are a few issues open that already cover this:

- #4032
- #3984
