### ISSUE TITLE
Implement generic (libxo) JSON command stats collection

### ISSUE THREAD

**Issue by grimreaper** [influxdata/telegraf#4061]
### Proposal:

Implement libxo based JSON collection of stats

### Current behavior:

Most stats are not collectable from telgraf without doing per stat work.

### Desired behavior:

Have it be easy to collect stats, even as new ones come out.

### Use case: [Why is this important (helps with prioritizing requests)]

FreeBSD supports a nice method for stats collection programs such as telegraf to get consistent output from its monitoring tools. Most tools can be passed a `--libxo` parameter to change the output format. See the examples below

Rather than having to implement per-stat type plugins the majority of the work can be done by providing merely the binary name. telegraf can easily translate this into a statistic name.

An incomplete list of utilities that provide libxo support:
- ps
- w
- netstat
- sesutil
- iscsictl
- arp
- jls
- vmstat
- procstat

Examples:

```
∴vmstat --libxo json
{"__version": "1", "processes": {"runnable":1,"waiting":0,"swapped-out":0}
, "memory": {"available-memory":" 515G","free-memory":"  10G","total-page-faults":1448}
, "paging-rates": {"page-reactivated":0,"paged-in":1,"paged-out":0,"freed":1169,"scanned":38}
, "device": [{"name":"ad0","transfers":0}, {"name":"pa0","transfers":0}], "fault-rates": {"interrupts":2014,"system-calls":30452,"context-switches":6477}
, "cpu-statistics": {"user":" 0","system":" 0","idle":"99"}
}
∴sudo nfsstat --libxo json
Password:
{"__version": "1", "nfsstat": {"clientstats": {"operations": {"getattr":0,"setattr":0,"lookup":0,"readlink":0,"read":0,"write":0,"create":0,"remove":0,"rename":0,"link":0,"symlink":0,"mkdir":0,"rmdir":0,"readdir":0,"rdirplus":0,"access":0,"mknod":0,"fsstat":0,"fsinfo":0,"pathconf":0,"commit":0}, "rpcs": {"timedout":0,"invalid":0,"xreplies":0,"retries":0,"requests":0}, "cache": {"attrhits":0,"attrmisses":0,"lkuphits":0,"lkupmisses":0,"biorhits":0,"biormisses":0,"biowhits":0,"biowmisses":0,"biosrlhits":0,"biorlmisses":0,"biodhits":0,"biodmisses":0,"direhits":0,"diremisses":0,"accshits":0,"accsmisses":0}}, "serverstats": {"operations": {"getattr":0,"setattr":0,"lookup":0,"readlink":0,"read":0,"write":0,"create":0,"remove":0,"rename":0,"link":0,"symlink":0,"mkdir":0,"rmdir":0,"readdir":0,"rdirplus":0,"access":0,"mknod":0,"fsstat":0,"fsinfo":0,"pathconf":0,"commit":0}, "server": {"writeops":0,"writerpc":0,"opsaved":0}, "cache": {"inprog":0,"idem":0,"nonidem":0,"misses":0}}}
}
```

While this would not fully eliminate benefits of implementing per-stat plugin support  it would eliminate the need for the vast majority

**Comment by russorat** [comment]
@grimreaper is there a reason why you can't use the `exec` input with a `data_format` json as described here? https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json-configuration

**Comment by grimreaper** [comment]
hrm... I was unaware of that plugin. In particular I  was unaware of the `format` attribute. That does seem similar to what I want here. The main issue is, like my other request, the tags are not handled perfectly, but lets see how far this gets me.

**Comment by danielnelson** [comment]
Don't forget to try the `tag_keys` option for selecting which fields should be tags.  I'm interested in how well it ends up working, keep us updated.
