### ISSUE TITLE
[inputs.exec]: metric parse error: expected field at offset 110: 

### ISSUE THREAD

**Issue by timcooijmans** [influxdata/telegraf#4063]
Hi,

My previously working input.exec script suddenly doesn't work anymore since the update to Telegraf 1.6.0. 

I'm getting the following error:
`Error in plugin [inputs.exec]: metric parse error: expected field at offset 110: "energy,meter=main imported_1=23786.317,exported_1=469.162,imported_2=23870.795,exported_2=1060.053,l1_import=00.254,l1_export=00.000,l2_import=00.201,l2_export=00.000,l3_import=00.693,l3_export=00.000\n"`

Config:
```
[[inputs.exec]]
        commands = ["python /etc/telegraf/readmeter.py"]
        timeout = "20s"
        data_format = "influx"
```

Any idea what's going wrong?

**Comment by danielnelson** [comment]
We rewrote the line protocol parser in 1.6, I expect this is just a bug in the new parser.  Looks like it is caused by the double leading zero on floats: `00.693`, if you can change these to `0.693` it should pass in 1.60, but I'll fix it proper for 1.6.1.
