### ISSUE TITLE
Have an option to combine messages in emqtt plugin

### ISSUE THREAD

**Issue by jvrahav** [influxdata/telegraf#4071]
Hi,

Im using the emqtt output plugin to send data from telegraf to emqtt. The plugin posts multiple messages for the same plugin in a collection cycle. 

It would be great to combine multiple messages posted by a plugin into one message. This will help us reduce the number of messages that are being published to emqtt.

Thanks,
Rahav

**Comment by danielnelson** [comment]
I think this could be useful for all/most of the queue outputs, and potentially other outputs.  I haven't thought about it extensively but perhaps we could introduce per output batch sizes.

**Comment by jvrahav** [comment]
I have a change made for this w.r.t to emqtt plugin. I tried creating a branch and pushing my changes to the branch. I got a 403 error. Can you let me know what is the process to submit a change for review

**Comment by russorat** [comment]
@jvrahav please follow the instructions here: https://github.com/influxdata/telegraf/issues/2468#issuecomment-382482113 or in the CONTRIBUTING.md file

**Comment by jvrahav** [comment]
@russorat thanks for pointing that out the instructions

@danielnelson  i have raised a PR for this change, though this only impacts mqtt ouput writter as every output writer might have a different need related to batching messages

**Comment by jvrahav** [comment]
https://github.com/influxdata/telegraf/pull/4094

**Comment by danielnelson** [comment]
Fixed in 1.7.0
