### ISSUE TITLE
Output filtering not working on UDP

### ISSUE THREAD

**Issue by Menthalion** [influxdata/telegraf#4072]
## Bug report
Output filtering with namepass / namedrop does not seem to be working on two influxdb UDP output nodes pointing to the same influxdb instance. All measurements are routed to one and not the other. This could be intended under UDP (on HTTP it works as expected), but a specific mention of this behavior in CONFIGURATION.md#measurement-filtering would be appreciated.

### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["udp://influxdb:8089"]
  database = "prod"
  retention_policy = ""
  namedrop = ["high_freq"]

[[outputs.influxdb]]
  urls = ["udp://influxdb:8089"]
  database = "prod"
  retention_policy = "short-term"
  namepass = ["high_freq"]
```
The outputs could also point to two different databases on the same influxdb instance instead of two different retention policies within the same database, the behavior is the same.

### System info:
Telegraf 1.6.1

### Steps to reproduce:
Emit basic telegraf system measurements and a measurement named high-freq from telegraf.

### Expected behavior:
Measurements named high-freq  should end up in the short-term retention policy, the rest of the measurements in default.

### Actual behavior:
All measurements end up in the default retention policy.

### Proposal:
Add a mention of this behavior in the documentation, either in CONFIGURATION.md#measurement-filtering or the readme of outputs.influxd or both,

**Comment by danielnelson** [comment]
InfluxDB doesn't provide a way to specify the retention policy over UDP from the client, but you can set it in `/etc/influxdb/influxd.conf` and use a different port for each retention policy.  I'll add a note about this to the InfluxDB output's README file.

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/commit/abdff033cc011e37c4eda8b78cf8913eb77e125a
