### ISSUE TITLE
[[inputs.nginx]] Add support for PROXY protocol

### ISSUE THREAD

**Issue by mjf** [influxdata/telegraf#4073]
Hello.

There is no option to connect with [PROXY protocol] for ``[[inputs.nginx]]`` plugin yet, as far as I know.

It's very common to have a proxy such as [HAProxy] in front of *Nginx* configured so that the *Nginx* listens with the *PROXY protocol* and *HAProxy* proxies request to it using the *PROXY protocol*. If this is the case the ``[[inputs.nginx]]`` can not reach the *stub status* data and the *Nginx* status data can not be collected. Therefor I propose to add support for the *PROXY protocol* for ``[[inputs.nginx]]``, i.e.:

    [[inputs.nginx]]
        urls = [ "http://host1/status", "http://host2/status" ]
        pp_urls = [ "http://host3/status" ]

where the ``pp_`` prefix indicates the *PROXY protocol version 1* of the connection (the ``host3`` in the example above listens with it).

The second way how to do it would be to support alternative *URL* syntax, i.e.:

    [[inputs.nginx]]
        urls = [
            "http://host1/status", "http://host2/status",
            "pp://host3/status"
        ]

where the ``pp`` scheme used in the example indicates that the plugin will use the *PROXY protocol* for the connection to the host ``host3``. I would personally prefer this latter variant. The former variant using extra array(s) looks quite ugly to me but may be easier to implement.

All this also apply to other *Nginx*-related input plugins (and **MAY** be considered for all *HTTP* connecting plugins in general because of the fact that the *PROXY protocol* is so commonly used).

Also, whether to support both versions of the protocol (i.e.: ``pp://`` and ``pp2://`` schemes), or two additional arrays (prefixed ``pp_`` and ``pp2_`` or alike), or just the most commonly used *version 1* of the protocol is a question. I would personaly prefer to support the *PROXY protocol version 1* only, at least for now...

Unfortunately, there is no *net/proxy* **official** packages for *Golang* yet. And there is no *Golang* package for the *PROXY protocol version 2* at all (as far as I know). There is a third-party [implementation] of the *PROXY protocol version 1* for *Golang* found but I can not review the quality of the code myself.

OT: I also found some simplistic [client] written in *Python* that can be used to gather the *stub status* from *Nginx* listening with the *PROXY protocol version 1*.

[HAProxy]: <http://www.haproxy.org>
[PROXY protocol]: <http://git.haproxy.org/?p=haproxy-1.8.git;a=blob;f=doc/proxy-protocol.txt>
[implementation]: <https://godoc.org/github.com/armon/go-proxyproto>
[client]: <https://gist.githubusercontent.com/sbdelisle/a14f8da8eedf1d7a64ca/raw/c98ebcd897e501001495f416a15ae1cbc4d62e6a/ppurlcat.py>

**Comment by danielnelson** [comment]
Thanks for the detailed writeup, I have a few questions to make sure I am understanding correctly.

> If this is the case the [[inputs.nginx]] can not reach the stub status data and the Nginx status data can not be collected. 

This because Telegraf is talking directly to the nginx server which is only expecting PROXY?

If so, isn't it possible to also configure the nginx to listen on a normal HTTP connection for the stub_status page?

I think the linked Go library only handles TCP mode, I don't see anything about HTTP.  The python code looks straightforward but I'm not sure how we could fish this new line into the Go http client.

**Comment by mjf** [comment]
@danielnelson Yes, the *Nginx* MAY be listening with *PROXY protocol* only (which is definitely not *HTTP* but rather separate protocol on top of *TCP*). Because *Telegraf* does not know to connect with the *PROXY protocol* it can not gather the *stub status* data. You can not see anything about *HTTP* because it's not *HTTP*. And yes, you could, of course, setup another "virtualhost" just for the *stub status*, that's true. But that may not be acceptable in some specific deployments.
