### ISSUE TITLE
MQTT consumer: expected field

### ISSUE THREAD

**Issue by s0170071** [influxdata/telegraf#4074]
## Bug report

### System info:

Telegraf version 1.6.0
Raspbian stretch
Mosquitto 

### Steps to reproduce:

1. set up mosquitto server and push a bunch of messages to it, all starting with "vito/". e.g. "vito/temperature"
2. set up telegraf, configure the MQTT consumer. 
3. add topic "vito/#" in the config file and data format "influx"
3. set up influx db and configure output plugin

### Expected behavior:
all data from the MQTT broker is imported into the influx db

### Actual behavior:
Raspi CPU and disk usage is successfully added to the database, 
vito topics imported by the mqtt plugin are not read. 
CLI error message (using the -test flag) is 
`
metric  parse error expected field at offset 4`

 The error message has then the correct value of the mqtt message appended but obviously does not know about the field name under which it is to be written in the database.

**Comment by danielnelson** [comment]
Can you show me what the data you are adding to mqtt looks like?

**Comment by s0170071** [comment]
I think I made a mistake. I was adding a single value to a MQTT topic. Obviously that value can be a lot more like a json string or a struct of some sort, e.g. influx. I did not know that.
I changed my data format to value / float - that seems to do the trick.
