### ISSUE TITLE
Add secure configuration options to couchbase 

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4079]
the couchbase input plugin should support secure configuration options

**Comment by mihaitodor** [comment]
@russorat Are you considering switching from https://github.com/couchbase/go-couchbase to https://github.com/couchbase/gocb and using `CertAuthenticator` as described [here](https://godoc.org/github.com/couchbase/gocb#CertAuthenticator)?

**Comment by russorat** [comment]
@mihaitodor i would imagine we should migrate to the official go lib for couchbase. We'd just want to make sure the shape of the data is similar enough that there is a migration path when users upgrade. Is that something you're interested in tackling?

**Comment by danielnelson** [comment]
There was an attempt to move to gocb a few years ago, but I have not followed up on if the additional functionality was added: https://github.com/influxdata/telegraf/issues/2418

**Comment by mihaitodor** [comment]
@russorat I don't have much experience with couchbase, but it might be fun to see if I can implement this. I'll give it a shot next week, unless somebody else wants to take it.
