### ISSUE TITLE
Internal metrics don't reflect write buffer size with multiple InfluxDB outputs

### ISSUE THREAD

**Issue by lukebigum** [influxdata/telegraf#4084]
I believe there's an issue with the Internal metrics and the data it's getting for InfluxDB write buffers, when multiple exclusive InfluxDB outputs are being used.  I would expect that when I simulate a failure of one Influx server that the write buffer would begin to increase.  However it looks like if Telegraf is able to write to *any* InfluxDB server it resets / empties the buffer size.

### System info:

telegraf-1.6.1-1.x86_64 on CentOS 6

### Steps to reproduce:

1. Create two InfluxDB outputs, and several inputs to gather, and turn on the internal input
2. Firewall off one InfluxDB server:
`iptables -A OUTPUT -s 1.1.1.1/32 -j DROP`
3. Watch the internal write buffer size stats for influxdb:

```
[root@hostname telegraf.d]# while [ 1 ]; do /usr/bin/curl -s http://localhost:9273/metrics | grep -P '^internal_write_buffer_size' | grep influx; sleep 5; done
internal_write_buffer_size{host="hostname",output="influxdb"} 1004
internal_write_buffer_size{host="hostname",output="influxdb"} 41
internal_write_buffer_size{host="hostname",output="influxdb"} 41
internal_write_buffer_size{host="hostname",output="influxdb"} 1999
internal_write_buffer_size{host="hostname",output="influxdb"} 1999
internal_write_buffer_size{host="hostname",output="influxdb"} 1999
internal_write_buffer_size{host="hostname",output="influxdb"} 14
```

### Expected behavior:

The internal_write_buffer_size for influxdb should be increasing.

### Actual behavior:

Looks like something is resetting the key.  This could be a deficiency in the way the internal plugin records only a single data point for what is probably several influxdb write buffers into a single metric.

If it's even possible, internal metrics that contained the output URL, like the below, would be very helpful:

```
internal_write_buffer_size{host="hostname",output="influxdb", urls=['influxdb1']} 1004
internal_write_buffer_size{host="hostname",output="influxdb", urls=['influxdb1']} 65
```

**Comment by danielnelson** [comment]
This is caused by not having enough tags to uniquely identify the output, which every plugin is output last during a timestamp is that winning value and the order is undefined.

To fix this I believe we should do https://github.com/influxdata/telegraf/issues/1815

**Comment by lukebigum** [comment]
Thanks, that explains what I'm observing.  #1815 looks like it would help here.  What's your process regarding issues, should I close this pending #1815?

**Comment by russorat** [comment]
@lukebigum let's resolve this one in favor of #1815. Thanks!
