### ISSUE TITLE
[[outputs.influxdb]] Auto update http client certificates. Feature request.

### ISSUE THREAD

**Issue by sergeykhegay** [influxdata/telegraf#4086]
## Feature Request

Auto update http client certificates.

### Proposal:

InfluxDB Output should be able to update client certificates on the http client used to connect to InfluxDB Server.

### Current behavior:

The plugin reads the certificates only once and feeds them to the Go's http client.

If certificates are updated on the filesystem, the client will not notice any change.

### Desired behavior:

The plugin should hot-swap certificates on demand, for example when the first certificates are about to expire.

This ideally should be done without recreating `net.http.Client`, rather 
by substituting the transport layer with updated certificates if possible.

### Use case: [Why is this important (helps with prioritizing requests)]

In organizations with high security requirements, host (client) certificates are updated quite often and automatically. Services should be able to hot swap certificates automatically, without restarts.

**Comment by danielnelson** [comment]
How often are you changing client certificates?  When you update the client certificate you can send a SIGHUP to restart Telegraf.

**Comment by sergeykhegay** [comment]
@danielnelson, any update on this? If you have any sketch ideas, I can take the work.

**Comment by danielnelson** [comment]
I have been considering this but I don't think it is an option we will want to handle within Telegraf.  It will be better to work on adding the SIGHUP call when deploying new certificates, or perhaps you can use a cron task.

**Comment by manolama** [comment]
@danielnelson What are your thoughts? The issue is that some at large companies are protected by certificates that may rotate hourly or daily. If Telegraf maintains any information in memory then it's really ugly to require users to cron SIGHUPs. It's much, much cleaner to allow the process to simply watch a cert for updates and re-create the HTTP client when a new client is found.

**Comment by danielnelson** [comment]
The complexity of monitoring changes and recreating the HTTP client is not non-trivial, and I don't want to introduce this concern into plugins.  Additionally many users do not want this feature so we would need to provide a way to enable/disable it.  Sending a SIGHUP when files that the plugin depend on are updated is the cleanest way to handle this issue, why not just add it to the script that deploys the new certs?

**Comment by manolama** [comment]
Oh yeah, a config flag is definitely important for enabling this feature. You'd want it disabled by default. And you're right, the change isn't trivial, but it's also not too bad and we're willing to create a PR for it.

As for the SIGHUP.. what if a cert is deployed to a shared location and you have hundreds of K8's that need updating. Would you shell into every container that has Telegraf as a sidecar and SIGHUP it? Or if Telegraf is running as it's own container, do we restart them all? And if the SIGHUP runs every hour, do we just accept data loss if the run coincides with the emission of data points? Ugg.

**Comment by danielnelson** [comment]
How often are you issuing a new certs?

**Comment by danielnelson** [comment]
I am unaware of watching and updating certificates without reload being a common feature for a service to support, do you have any examples of this being done in other pieces of software?

Perhaps it would be more appropriate to use an authentication scheme such as JWT in conjunction with longer lasting certificates?

**Comment by danielnelson** [comment]
This sounds like a discussion on the k8s side around this problem: https://github.com/kubernetes/kubernetes/issues/24957

**Comment by manolama** [comment]
Yeah I'm not aware of any either. I'm used to Apache, Nginx methods of restarting biannually or once a year the same way you are. (Though I think it'd be nice for the servers to do the same, watch for file changes and update). 

For the scheme, yeah I'd prefer a JWT system too but we're stuck with plain old certs. If you're curious the scheme we're stuck with is https://github.com/yahoo/athenz.

**Comment by danielnelson** [comment]
Would it be possible to add a separate program to your Telegraf containers that sets up the inotify watch and sends SIGHUP on changes?

If you are concerned about missing intervals though this could also be an issue: https://github.com/influxdata/telegraf/issues/2679
