### ISSUE TITLE
datadog output plugin undeterminable type

### ISSUE THREAD

**Issue by tjend** [influxdata/telegraf#4090]
Telegraf version > 1.5.3 broke sending of several metrics to datadog.

### Relevant telegraf.conf:

debug = true
[[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.system]]
[[inputs.swap]]
[[outputs.datadog]]
    apikey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

### System info:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

$ cat /etc/apt/sources.list.d/influxdb.list 
deb https://repos.influxdata.com/ubuntu xenial stable

Problem telegraf version: 1.6.1-1
Working telegraf version: 1.5.3-1

### Steps to reproduce:

1. Upgrade telegraf from version 1.5.3-1 to 1.6.1-1

### Expected behavior:

Telegraf continues to send all my metrics to datadog.

### Actual behavior:

Only some metrics are sent to datadog.

Metrics for disk, diskio, mem, system and swap are not sent to datadog.

The log shows errors like this:
I! unable to build Metric for swap due to error 'unable to extract value from Fields total error undeterminable type', skipping
I! unable to build Metric for swap due to error 'unable to extract value from Fields in error undeterminable type', skipping
I! unable to build Metric for system due to error 'unable to extract value from Fields uptime error undeterminable type', skipping
I! unable to build Metric for mem due to error 'unable to extract value from Fields total error undeterminable type', skipping
I! unable to build Metric for disk due to error 'unable to extract value from Fields inodes_used error undeterminable type', skipping
I! unable to build Metric for diskio due to error 'unable to extract value from Fields read_bytes error undeterminable type', skipping
I! unable to build Metric for diskio due to error 'unable to extract value from Fields write_time error undeterminable type', skipping

### Additional info:

Same problem on Ubuntu 14.04. Same problem with telegraf 1.6.0-1.

**Comment by danielnelson** [comment]
Thanks for the report, I'll take a look.
