### ISSUE TITLE
Question: Can telegraf be setup on a single server to pull server health metrics of multiple servers?

### ISSUE THREAD

**Issue by v4vamsee** [influxdata/telegraf#4093]
Can telegraf be setup on a single server to pull server health metrics of multiple servers?

**Comment by danielnelson** [comment]
It depends on the input plugin, some plugins can gather over the network while other require Telegraf to be running on the machine.  You can specify any plugin multiple times if needed.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
