### ISSUE TITLE
E! Error in plugin [inputs.diskio]: error getting disk io info: open /proc/diskstats: no such file or directory

### ISSUE THREAD

**Issue by five-team** [influxdata/telegraf#4097]
Hey all, 

on all our systems we are using Cloudlinux (CentOS). 
On telegraf status I can see "E! Error in plugin [inputs.diskio]: error getting disk io info: open /proc/diskstats: no such file or directory"

If I check "cat /proc/diskstats" I got e "good" answer:
cat /proc/diskstats
   8      16 sdb 1795 7536 80512 1202 4058 13579 141096 6010 0 6265 7204
   8       0 sda 33109858 213782 2175577785 55084820 33074776 2384484 1676049991 940405330 0 40854636 995511731
   8       1 sda1 9582 0 1457484 9670 65 13 5616 12495 0 17846 22160
   8       2 sda2 33100215 213782 2174118453 55075124 33074711 2384471 1676044375 940392835 0 40846064 995479774
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
 253       0 dm-0 87 0 3160 5 0 0 0 0 0 5 5
   8      32 sdc 1798341 2959 406867228 2661563 578611 70687 535075216 204049733 0 3608028 206708037
   8      33 sdc1 1798227 2959 406859900 2661518 578607 70687 535075208 204049684 0 3607940 206707466

Is there any bug or mistake by me? 

I also got a 2nd error: 
E! Error in plugin [inputs.sysstat]: command /usr/bin/sadf -p -- -p -d /tmp/sysstat-1525341130 failed with exit status 1

sadf exists under /usr/bin/sadf

**Comment by danielnelson** [comment]
Perhaps this is a permissions issue, the service usually runs as the `telegraf` user.  Do you get an error if you run this?:
```
sudo -u telegraf cat /proc/diskstats
```

**Comment by five-team** [comment]
Hey @danielnelson , 

not a permission issue: 
sudo -u telegraf cat /proc/diskstats
cat: /proc/diskstats: **Datei oder Verzeichnis nicht gefunden**

Translated in englisch: File or directory not found. 
Is there any way to "add" for this user?

/etc/passwd:
telegraf:x:979:978::/etc/telegraf:/bin/false

**Comment by danielnelson** [comment]
This might be helpful: https://docs.cloudlinux.com/index.html?virtualized_proc_filesystem.html

I'm going to close this issue since I don't think there are any changes to make to Telegraf.
