### ISSUE TITLE
Error in log when start process.

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#4101]
### System info:

ubuntu14.04
teletraf-1.6.1

### Steps to reproduce:

sudo service telegraf restart 

### Expected behavior:

start succeed.

### Actual behavior:

found error in log file when start process.

tail -f /var/log/telegraf/telegraf.log

2018-09-11T02:25:41Z I! Hang on, flushing any cached metrics before shutdown
E! Unable to append to /var/log/telegraf/telegraf.log (open /var/log/telegraf/telegraf.log: permission denied), using stderr
2018-09-11T02:25:43Z I! Starting Telegraf v1.7.4

### Additional info:

ubuntu16.04 works fine.

**Comment by danielnelson** [comment]
I believe you can workaround this by clearing the agent logfile in your telegraf.conf:
```
[agent]
  logfile = ""
```

To fix this we should log to syslog when started from the sysv initscripts.

**Comment by sspaink** [comment]
Closing because Ubuntu 14 reached end of life "April 30th 2019", please open a new issue if this problem persists in new versions.
