### ISSUE TITLE
Can't run telegraf using `go run`

### ISSUE THREAD

**Issue by Braynid** [influxdata/telegraf#4103]
## Bug report
I can't run telegraf using `go run` after the latest update.

While developing plugins I run `make` once and then just build telegraf every time I need to test using 
```
go build -i -ldflags " -X main.commit=a3ebb606 -X main.branch=master" ./cmd/telegraf
```

As you can imagine the extra time required is bothersome. Is there any way to run telegraf as is?

### System info:

```
Telegraf v1.7.0~a3ebb606 (git: master a3ebb606)
go version go1.10.2 darwin/amd64
osx 10.13.4 (17E199)
```

### Steps to reproduce:
```
λ go run cmd/telegraf/telegraf.go --config config.conf
# command-line-arguments
cmd/telegraf/telegraf.go:195:14: undefined: usage
```

### Expected behavior:
Telegraf runs

### Actual behavior:
Throws the following error `cmd/telegraf/telegraf.go:195:14: undefined: usage`

**Comment by danielnelson** [comment]
Should be good now.  7c0754ebe5586a2c961bfc6ffa70f193fc328c1e
