### ISSUE TITLE
Compiling telegraf with go 1.10+

### ISSUE THREAD

**Issue by mattfung** [influxdata/telegraf#4105]
### System info:
Ubuntu 16.04 desktop x64
go version go1.10.1 linux/amd64 (installed from latest snap)

### Steps to reproduce:

1. clone current telegraf repo
2. run `make`

### Actual behavior:
make process return the following error
```
go build -i -ldflags " -X main.commit=fd63591 -X main.branch=master" ./cmd/telegraf
go build runtime/cgo: open /snap/go/1688/pkg/linux_amd64/runtime/cgo.a: read-only file system
Makefile:30: recipe for target 'telegraf' failed
make[1]: *** [telegraf] Error 1
```

### Additional info:

might be related to this issue [https://github.com/golang/go/issues/24674](https://github.com/golang/go/issues/24674)

I changed Makefile:30
`go build -i -ldflags "$(LDFLAGS)" ./cmd/telegraf` 
to
`go build -ldflags "$(LDFLAGS)" ./cmd/telegraf`
and compilation worked on my computer (thought I am not sure if this is backward compatible/safe)

Thx.

**Comment by danielnelson** [comment]
I will remove the `-i` flag from the Makefile, it isn't needed anymore with Go 1.10+ and the only downside of not having it in previous Go version is a slower build.  Additionally it will make cross compiling a bit easier, since we need to remove the flag in that case.

**Comment by danielnelson** [comment]
757e23a5f27ab578150bd07fd561fa76d42073b9
