### ISSUE TITLE
socket_writer can not reconnect

### ISSUE THREAD

**Issue by skycgz** [influxdata/telegraf#4108]
in my tcp listener service which using telegraf.socket_writer.tcp as client, when I restart force, telegraf can not reconnect my service, it wasn't help when I set or not set keep_alive_period, os net status keep CLOSE_WAIT and Send-Q keep raising a few minutes later

output setting:
[[outputs.socket_writer]]
  address = "tcp://192.168.31.34:15001"
  keep_alive_period = "1m"
  data_format = "json"

os keepalive setting:
[root@localhost ~]# cat /proc/sys/net/ipv4/tcp_keepalive_intvl 
10
[root@localhost ~]# cat /proc/sys/net/ipv4/tcp_keepalive_probes 
3
[root@localhost ~]# cat /proc/sys/net/ipv4/tcp_keepalive_time
60

**Comment by danielnelson** [comment]
I tried these steps:
1. Run netcat: `nc -l localhost 8094`
1. Start telegraf
1. Check that netcat is printing metrics
1. Kill and restart netcat
1. Check that netcat is printing metrics

After restarting netcat Telegraf is able to reconnect and continue sending metrics.  Can you provide modified steps that reproduce the issue?

**Comment by skycgz** [comment]
yes it's ok that using nc in centos, and my program running well also, but not in osx

**Comment by skycgz** [comment]
when I kill my program in osx(return Process finished with exit code 130 (interrupted by signal 2: SIGINT)), telegraf still outputing:
2018-05-14T08:50:35Z D! Output [socket_writer] buffer fullness: 8 / 100000 metrics. 
2018-05-14T08:50:35Z D! Output [socket_writer] wrote batch of 8 metrics in 2.562676ms

in centos, it returns :
2018-05-14T08:50:01Z E! Error writing to output [socket_writer]: dial tcp 192.168.78.128:15001: getsockopt: connection refused
2018-05-14T08:50:05Z D! Output [socket_writer] buffer fullness: 130 / 100000 metrics.

**Comment by danielnelson** [comment]
I'm still not able to reproduce on OSX using my steps above, are there any modifications needed to those steps?

**Comment by skycgz** [comment]
I guess it is that my virtual environment cause:
(cc-mbp: listener server,  localhost: telegraf client)

connected:
```
cc-mbp:~ # lsof -i:15001
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vmnet-nat 1996 root    6u  IPv4 0x64275c55e169e3d5      0t0  TCP 192.168.31.34:59023->192.168.31.34:15001 (CLOSED)
vmnet-nat 1996 root    9u  IPv4 0x64275c55e110d115      0t0  TCP 192.168.31.34:59826->192.168.31.34:15001 (ESTABLISHED)
main      2399 root    3u  IPv6 0x64275c55e466a0cd      0t0  TCP *:15001 (LISTEN)
main      2399 root    5u  IPv6 0x64275c55e466b20d      0t0  TCP 192.168.31.34:15001->192.168.31.34:59826 (ESTABLISHED)

[root@localhost ~]# netstat -anp|grep telegraf
tcp        0      0 192.168.78.128:59860    192.168.31.34:15001     ESTABLISHED 91199/telegraf      
unix  3      [ ]         STREAM     CONNECTED     4810875  91199/telegraf 
```
stop listener:
```
cc-mbp:~ # lsof -i:15001
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vmnet-nat 1996 root    6u  IPv4 0x64275c55e169e3d5      0t0  TCP 192.168.31.34:59023->192.168.31.34:15001 (CLOSED)
vmnet-nat 1996 root    9u  IPv4 0x64275c55e110d115      0t0  TCP 192.168.31.34:59826->192.168.31.34:15001 (CLOSED)

[root@localhost ~]# netstat -anp|grep telegraf
tcp        1      0 192.168.78.128:59860    192.168.31.34:15001     CLOSE_WAIT  91199/telegraf      
unix  3      [ ]         STREAM     CONNECTED     4810875  91199/telegraf 
```

start listener again:
```
cc-mbp:~ # lsof -i:15001
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vmnet-nat 1996 root    6u  IPv4 0x64275c55e169e3d5      0t0  TCP 192.168.31.34:59023->192.168.31.34:15001 (CLOSED)
vmnet-nat 1996 root    9u  IPv4 0x64275c55e110d115      0t0  TCP 192.168.31.34:59826->192.168.31.34:15001 (CLOSED)
main      2429 root    3u  IPv6 0x64275c55e466954d      0t0  TCP *:15001 (LISTEN)

[root@localhost ~]# netstat -anp|grep telegraf
tcp        1   4020 192.168.78.128:59860    192.168.31.34:15001     CLOSE_WAIT  91199/telegraf      
unix  3      [ ]         STREAM     CONNECTED     4810875  91199/telegraf    
```

**Comment by danielnelson** [comment]
Does that mean you have it figured out then?

**Comment by skycgz** [comment]
yes, thank you
