### ISSUE TITLE
Request - Inputs.ping (additional attribute

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#4115]
This is more a request or question than a issue report. 
I'm  pinging around 70 hosts with the inputs.ping plugin. For some reason I have to ping the hosts with the IP and not the FQDN. The data is sent do influxdb. From there I want the data to be queried from my own application. Now the question is, can I add some additional attributes to the measurement besides the attributes provided by the inputs.ping plug. I would like to have two additional attributes called alias and group. In the end I would like to query the alias, group and the result code of the ping. 

Is this somehow possible?

**Comment by danielnelson** [comment]
The closest thing I can think of is adding tags to the ping plugin, [here is an example](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags).  These tags cannot be set dynamically though so you would probably need to define the ping plugin for each host.

**Comment by relishcolouredhat** [comment]
@darox Can you poll the device on SNMP? I wrote a python script to poll hostname & build ping config blocks with a hostname tag if it's useful to you
