### ISSUE TITLE
nvidia-smi plugin failed when some metric is not supported

### ISSUE THREAD

**Issue by l1b0k** [influxdata/telegraf#4120]
### Relevant telegraf.conf:

```toml
[[inputs.nvidia_smi]]
```

### System info:

[Include Telegraf version, operating system name, and other relevant details]

```sh
[root@node ~]# ./telegraf version
Telegraf v1.6.0~e76e1222 (git: master e76e1222)
```

CentOS 7 + Tesla P4 (Driver Version: 384.11)

### Steps to reproduce:

1. start telegraf 

### Expected behavior:

Get metric and set unsupported metric to unknown.

### Actual behavior:

Failed to get metric.

```
2018-05-08T05:19:05Z E! Error in plugin [inputs.nvidia_smi]: strconv.ParseInt: parsing "[Not Supported]": invalid syntax
```

### Additional info:

fan.speed is not supported on my card. And parse this cause error.

```sh
[root@node ~]# nvidia-smi --format=noheader,nounits,csv --query-gpu=fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,compute_mode,utilization.gpu,utilization.memory,index
[Not Supported], 7606, 0, 7606, P0, 38, Tesla P4, GPU-xxx, Default, 0, 0, 0
[Not Supported], 7606, 0, 7606, P0, 37, Tesla P4, GPU-xxx, Default, 0, 0, 1
```

i think it is reasonable to set unsupported metric to unknown

**Comment by danielnelson** [comment]
Thanks for the report, in the linked pull request we will silently skip this field.

**Comment by dbienapfl-dataminr** [comment]
My pleasure - thanks for diving in and getting it fixed
