### ISSUE TITLE
disk metrics fail to collect after pc reboot

### ISSUE THREAD

**Issue by jjalexander1** [influxdata/telegraf#4121]
### Relevant telegraf.conf:
Input plugins: cpu, disk, mem, swap, system, net, sensors, netstat, processes, kernel, diskio, docker

disk plugin conf:
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "udev"]

### System info:
telegraf version: telegraf:1.5.2-alpine
OS: ubuntu 16.04
running on: Intel NUC7i3BNH

We're running telegraf in docker, version 17.09.1-ce
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

Reboot PC either physically or running reboot from terminal, then watch logs and it will start using the correct conf file and then fail to collect disk metrics because it's taking longer than collection interval

### Expected behavior:
Disk metrics collected

### Actual behavior:
Below message spammed in logs

host_telegraf_1  | 2018-05-08T09:54:59.482206000Z 2018-05-08T09:54:59Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (5m0s)
host_telegraf_1  | 2018-05-08T09:59:59.481293000Z 2018-05-08T09:59:59Z E! Error in plugin [inputs.disk]: took longer to collect than collection interval (5m0s)

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Is there an action you perform to get this error to clear?

Are the other input plugins working and is the output working while this occurs?

Can you run these commands and attach the output:
```
cat /proc/filesystems
cat /proc/self/mounts

# stat the various mountpoints that are not excluded in `ignore_fs`  don't attach the output 
# for these just make the command doesn't hang
stat /home
stat /
```

**Comment by danielnelson** [comment]
Closing since no update.
