### ISSUE TITLE
Failure scenarios in net_response dont get outputted in prometheus_client

### ISSUE THREAD

**Issue by jonathanhartley** [influxdata/telegraf#4122]
Telegraf v1.6
Running on Centos 7 
simple net_response from 3306 (MySQL) 
If you shutdown MySQL the metric disappears from the /metrics endpoint rather than coming up 
* result_type (string) # success, timeout, connection_failed
If you run the --test flag manually as the telegraf user it appears in the output
This is also true of http_response plugin so we assume its the output plugin ?

telegraf.conf
.....
[[inputs.net_response]]
  protocol = "tcp"
  address = ":3306"
  timeout = "1s"
.....

With MySQL running simple curl of localhost:9126/metrics | grep net_res provides you with output line
Shutdown MySQL and the output disappears 
The whole point of the check is to check if the port is open and so we can use it as an alert in Prometheus

**Comment by danielnelson** [comment]
Fix merged for 1.7

**Comment by jonathanhartley** [comment]
You can use prometheus to look for absent() however you would have to know in advance all host/port combinations to alert on has it has to uniquely locate the missing metric, that is not sustainable with the number of VMs we have and the rate of change
