### ISSUE TITLE
Create plugin to support cardinality metrics

### ISSUE THREAD

**Issue by stevebang** [influxdata/telegraf#4124]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

The SHOW SERIES CARDINALITY command only applies to a database, yet the overall series cardinality for a node/instance can be important to track and manage.

In a discussion with @danielnelson about series cardinality, Daniel suggested that to improve the ability to monitor and manage cardinality, it might make sense to create a plugin that could be used to monitor measurements related to cardinality. These measurements could be available in InfluxDB monitoring dashboards.

### Current behavior:

SHOW SERIES CARDINALITY only applies to the current (or a specified) database.

### Desired behavior:

@danielnelson suggested that we could capture the SHOW SERIES CARDINALITY output for each database in a cluster and then using SUM functions to provide aggregate cardinality measurements for the cluster or server.  In the context of a plugin, it would be a lot easier to create meaningful measurements, track them, and alert based on significant changes.

### Use case: [Why is this important (helps with prioritizing requests)]

Customers could use this information to: 

* track changes in cardinality values (over time) for their databases
* monitor and alert based on significant growth in cardinality for a database in the context of total cardinality
* monitor and manage cardinality and impacts on memory (RAM and disk)
* monitor the impact of switching between tags and fields on cardinality

**Comment by danielnelson** [comment]
I wonder if this could be implemented using continuous queries, but even if it can this would still be useful for sending metrics to a separate monitoring InfluxDB instance.

**Comment by russorat** [comment]
You can get close with multiple exec plugins. Assuming databases don't change names very often, you can get to a graph like this for cardinality with the attached config:

![image](https://user-images.githubusercontent.com/4805997/39789087-9bdb61d0-52e2-11e8-9a99-466817769446.png)

Just repeat this config for however many databases you have, replacing `<DATABASE_NAME>` with your database name.
```
[[inputs.exec]]
  commands = [
    "influx -format json --execute 'SHOW SERIES CARDINALITY on <DATABASE_NAME>'",
  ]
  timeout = "5s"
  name_override = "cardinality"
  [inputs.exec.tags]
    db='<DATABASE_NAME>'
  data_format = "json"
```

**Comment by reimda** [comment]
Since this issue was submitted, InfluxDB v2 also gained the ability to query cardinality through flux. It should be possible to do query and record its cardinality in a similar way.
https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/cardinality/
https://community.influxdata.com/t/show-series-cardinality-in-influxdb-v2/19554/5

Closing due to age and because there's a workaround using exec. We can reopen this if there is demand.
