### ISSUE TITLE
Remove the influx line protocol serializer's dependency on the rest of telegraf.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/telegraf#4125]
## Feature Request

Remove the influx line protocol serializer's dependency on the rest of telegraf.  The serializer could then be broken out.

### Proposal:

We should replace the serializers dependency on telegraf.Metric with an appropriate interface.  The dependency on []telegraf.Metric would be replaced with reflection or requiring some sort of wrapper type that implements something that walks the slice.

Another option would be for it to compose in an external serializer and wrap it.  This last option would keep it from breaking its public API.

### Current behavior:

Right now the influx line protocol serializer depends on telegraf.Metric

### Desired behavior:

Make the serializer not depend in influx.Metric so that its easier for others to import without having to depend on the entire rest of telegraf.

### Use case: [Why is this important (helps with prioritizing requests)]

This keeps serialization centralized and reduces code duplication across repos.

**Comment by danielnelson** [comment]
We can do this at the same time we break out the serializer.  I don't think you will need reflection since we can just use a slice of the new interface.  It's not critical for the new library to have an identical API since we can wrap calls to it, what's most important to me is that we can serialize without copying the metric type.

**Comment by MyaLongmire** [comment]
@docmerlin sorry no one has gotten back to you. Are you still interested in this?

**Comment by docmerlin** [comment]
@MyaLongmire gosh it's been 4 years. I can't remember.  I wonder if it's already been done?  There is a small chance I did it and didn't update the ticket?
