### ISSUE TITLE
[[inputs.exec]]  The test has data, but no data is collected.

### ISSUE THREAD

**Issue by sumiaoke** [influxdata/telegraf#4126]
Hi,

My previously working input.exec script suddenly doesn't work anymore since the update to Telegraf 1.5.2.

I'm getting the following error:
telegraf --config /etc/telegraf/telegraf.d/inputs_exec.conf --test
Data can be collected,but in fact, no data is collected.I doubt it is my telegraf user rights issue.My telegraf user is setting up /usr/sbin/nologin.

I don't want to change the situation of telegraf users.

Config:
[[inputs.exec]]
    commands = ["bash /tmp/traceroute.sh"]
    timeout = "10s"
    data_format = "influx"

**Comment by danielnelson** [comment]
What version did you upgrade from?

Can you run this and add the output?:
```
sudo -u telegraf telegraf --config /etc/telegraf/telegraf.d/inputs_exec.conf --input-filter exec --test
```

**Comment by danielnelson** [comment]
Did you type the password in?

**Comment by sumiaoke** [comment]
NO,Because I don't know the password, either.

**Comment by dangxiaojun** [comment]
version: 1.6.3 
Config:
[[inputs.exec]]
  commands = ["/tmp/test.py"]
  name_suffix = "_mycollector"
  data_format = "json"

and run command, I get this:
```
# sudo -u telegraf telegraf --config /etc/telegraf/telegraf.conf --input-filter exec --test
* Plugin: inputs.exec, Collection 1
```

/tmp/test.py can working, but no data is collected.

**Comment by danielnelson** [comment]
@dangxiaojun What do you get if you run:
```
sudo -u telegraf /tmp/test.py
```

**Comment by dangxiaojun** [comment]
@danielnelson 
Get this: 
{"Field2": "2", "Field3": "3", "Field1": "1"}

**Comment by danielnelson** [comment]
You will need to update the JSON to have at least one numeric field.  Strings are ignored unless they are listed in `tag_keys`, and you must have at least one field:
```
{"Field2": 2, "Field3": 3, "Field1": 1}
```

**Comment by dangxiaojun** [comment]
Yes, that's right. they are working now. Thx

**Comment by cfrelet** [comment]
Sorry to ask, but what do you run in your python script?
I mean if I just put:
`print({"Field2": 2, "Field3": 3, "Field1": 1})
`
It doesn't return me anything.

**Comment by bfontaine** [comment]
@cfrelet it must print JSON.

```python3
print({"Field2": 2, "Field3": 3, "Field1": 1})
# {'Field2': 2, 'Field3': 3, 'Field1': 1}

import json
print(json.dumps({"Field2": 2, "Field3": 3, "Field1": 1}))
# {"Field2": 2, "Field3": 3, "Field1": 1}
```
