### ISSUE TITLE
Can't seem to get a valid value with diskio_read_time and diskio_write_time

### ISSUE THREAD

**Issue by voodoodror** [influxdata/telegraf#4132]
### Relevant telegraf.conf:
Everything's default within [[inputs.diskio]]

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf 1.4.3
CentOS Linux release 7.4.1708 (Core)
Prometheus 1.7.1

### Steps to reproduce:

Trying to use the following metric query leads to value which is more than 100%:
`irate(diskio_read_time{host=~"$host", name!~"dm-.*"}[5m])/1000`
`irate(diskio_write_time{host=~"$host", name!~"dm-.*"}[5m])/1000`

What could possibly be wrong?

Thanks,
Dror.

**Comment by danielnelson** [comment]
Sorry, I'm not familiar with prometheus query language.  You could try asking over at the [InfluxData Community](https://community.influxdata.com) site, or if you can determine if the prometheus output is exposing incorrect data from its /metrics endpoint we could look into that.
