### ISSUE TITLE
Gather global bytes_received/sent in mysql input

### ISSUE THREAD

**Issue by nycterent** [influxdata/telegraf#4134]
5.7.21-20-log Percona Server
telegraf 1.6.2-1

### Expected behavior:

should fetch global stats

### Actual behavior:

fetches session stats

**Comment by danielnelson** [comment]
We could add this, do you know what query returns the global bytes_received/sent?

**Comment by nycterent** [comment]
this gives me expected output: 

show global status like 'Bytes%';

**Comment by sspaink** [comment]
It has been quite a while since this issue has seen activity, @nycterent are you still interested in seeing this feature implemented?

**Comment by nycterent** [comment]
uff.. long time :) we are not interested in this anymore right now. thank you

**Comment by sspaink** [comment]
Thank you for letting us know, closing this issue then.
