### ISSUE TITLE
Unable to parse non-interger JSON data using http plugin despite using tag_keys for non-integer values.

### ISSUE THREAD

**Issue by nwk2** [influxdata/telegraf#4139]
Hi all,

I am using telegraf to collect metrics from an API endpoint that returns JSON data as follows:

{
    "id": 12345,
    "memory": 6789,
    "status": "UP"
} 

**telegraf.conf**:
[[inputs.http]]  
  urls = ["<apiUrl>.../metrics"]
  name_override = "status"

  method = "GET"

  username = "username"
  password = "password"

  data_format = "json"

  tag_keys = [
    "status"
  ]

In my influxdb database, it only shows field keys "id" and "memory" which contains ONLY integer values. Am I missing something or how do I collect string(or non-integer) values? Thank you!

**Comment by danielnelson** [comment]
The JSON format only supports collecting strings as tags using the `tag_keys` method.  #2835

**Comment by nwk2** [comment]
Thank you for your reply. Yes I did use `tag_keys = [ "status" ]` however nothing is collected. Am I using tag_keys method wrongly? I've followed the example given in the docs. Thank you for your time

**Comment by danielnelson** [comment]
The status field should be added as a tag: `show tag keys from <measurement name>`

**Comment by zaaraameera2014** [comment]
Closed
