### ISSUE TITLE
cacti snmp error

### ISSUE THREAD

**Issue by user9595** [influxdata/telegraf#4140]
Hello ,
I am currently using Cacti to monitor some of my router which I have created on Gns3 software , however I am constantly getting an snmp error when I add my devices .

![help](https://user-images.githubusercontent.com/38493300/39936524-a13e2fc2-5544-11e8-8b79-59c2e5f3b0d0.png)

![snmpcactierr](https://user-images.githubusercontent.com/38493300/39936361-236014b2-5544-11e8-818c-c569f699588c.png)

After following several tutorials , where some suggested to test snmpwalk on cli I got this result 

![snmpwalk](https://user-images.githubusercontent.com/38493300/39936440-633f8b30-5544-11e8-9532-0c96b959512a.png)

![snmppp](https://user-images.githubusercontent.com/38493300/39936868-bfee5e3c-5545-11e8-88bc-ec53d7afbdb5.png)

You can obviously tell that something is wrong my with my snmp-agent which is why I continued to follow suggestions about changing my snmpd.conf by replacing the OID's "view   systemonly  included   .1.3.6.1.2.1.0" under ACCESS CONTROL in my snmd.conf file and then restarting the service but nothing helped 

I have also tried adding " rocommunity orange 81.52.186.222" but I still get SNMP error , and of course I have configured snmp on all of my routers .

bellow in my snmpd.conf 

[snmd.conf.txt](https://github.com/influxdata/telegraf/files/1996181/snmd.conf.txt)

I am quite new to SNMP and it's configurations.
So if anyone could provide  me with more information about this issue  I would be very grateful  and thank you .

**Comment by danielnelson** [comment]
Sorry, can't help, you should ask the net-snmp project if you are using their snmpd.

http://www.net-snmp.org/support/contacts.html
