### ISSUE TITLE
Librato output : disk input: Couldn't build gauge: unable to extract value from Fields, undeterminable type

### ISSUE THREAD

**Issue by wietseschmitt** [influxdata/telegraf#4149]
### Relevant telegraf.conf:
 [[outputs.librato]]
   api_user = "user@domain.com" # required.
   api_token = "myapicode" # required.
   template = "host"

[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

### System info:
core@docker ~/telegraf $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

2018-05-15T12:48:57Z I! Starting Telegraf v1.6.2

### Steps to reproduce:
using docker-compose file below with the telegraf.conf adjustments above:
version: '2'
services:
 telegraf:
  image: telegraf
  restart: always
  environment:
    HOST_PROC: /hostfs/proc
    HOST_MOUNT_PREFIX: /hostfs
  hostname: localhost
  network_mode: host
  volumes:
   - /:/hostfs:ro
   - /data/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

### Expected behavior:
disk metrics of the mount / being sent to librato

### Actual behavior:
receive an error : 
2018-05-15T12:48:00Z D! Output [librato] buffer fullness: 1 / 10000 metrics.
2018-05-15T12:48:00Z I! unable to build Gauge for disk, skipping
2018-05-15T12:48:00Z D! Couldn't build gauge: unable to extract value from Fields, undeterminable type 6520340480

2018-05-15T12:48:00Z D! Output [librato] wrote batch of 1 metrics in 94.728µs

### Additional info:
when i disable the librato output and enable file output everything works as expected. so that suggests the problem is in the librato output plugin

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Sorry about that, the fix will be in 1.6.3 early next week.  You can also try the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds), just give it until tomorrow to be incorporated.
