### ISSUE TITLE
Update InfluxDB Input plugin to match what is reported by _internal

### ISSUE THREAD

**Issue by dp1140a** [influxdata/telegraf#4153]
Currently what is reported by the InfluxDB input plugin is different form what is reported by the _internalDB.  The result of this is that things that can be monitored via _internal are not available using the InfluxDB plugin; even though the recommended best practice for monitoring production clusters is not use _internal and to use telegraf

**Comment by danielnelson** [comment]
Can you list what is not available?

**Comment by pshah** [comment]
memstats and n_shards

**Comment by danielnelson** [comment]
I'm getting those metrics
```
$ telegraf --input-filter influxdb  --test | grep 'n_shards\|memstats'
2018/05/16 13:55:36 I! Using config file: /home/dbn/.telegraf/telegraf.conf
> influxdb_memstats,url=http://localhost:8086/debug/vars alloc=40407928i,buck_hash_sys=1620298i,frees=161279264i,gc_sys=3854336i,gcc_pu_fraction=0.0000672115792764632,heap_alloc=40407928i,heap_idle=52256768i,heap_inuse=42016768i,heap_objects=931299i,heap_released=47300608i,heap_sys=94273536i,last_gc=1526504090612452940i,lookups=34595i,mallocs=162210563i,mcache_inuse=6944i,mcache_sys=16384i,mspan_inuse=454024i,mspan_sys=802816i,next_gc=65756800i,num_gc=3432i,other_sys=647086i,pause_ns=263119i,pause_total_ns=816177124i,stack_inuse=1146880i,stack_sys=1146880i,sys=102361336i,total_alloc=35802246752i 1526504137000000000
> influxdb n_shards=9i 1526504137000000000
```

**Comment by pshah** [comment]
right, they are reported by telegraf as a part of the influxdb plugin but missing when reported directly to _internal

**Comment by danielnelson** [comment]
Okay, that's the opposite of this issue.  The memstats are saved in a measurement named `runtime` but I'm not sure how to get the number of shards from the _internal database, you could ask over at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by danielnelson** [comment]
Closing, if we can add details about what is missing then we can reopen.
