### ISSUE TITLE
Support NVMe devices in smart input plugin

### ISSUE THREAD

**Issue by Lyncredible** [influxdata/telegraf#4169]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Support NVMe devices in smart input plugin. `smartmontools` produces a different format for NVMe devices than SATA devices. See https://www.smartmontools.org/wiki/NVMe_Support for sample output.

### Current behavior:
Currently the `smart` plugin does not work with NVMe devices.

### Desired behavior:
It should correctly parse output from `smartctl` with NVMe devices.

### Use case: [Why is this important (helps with prioritizing requests)]
NVMe devices will become more and more popular. It is important to see metrics for them.

**Comment by ValyaB** [comment]
NVME devices have supported if specify type during the scan:
smartclt --scan -d nvme 
Could you add an additional option for specifying device type during the scan

Currently: 
smartctl --scan
Desired:
smartctl --scan -d TYPE

**Comment by danielnelson** [comment]
You may be able to use the devices option as a workaround for now: `devices = ["/dev/foo -d nvme"]`

**Comment by ValyaB** [comment]
seems there is a different list of fields for NVME devices and only smartOverallHealth and serialInfo are exist
 smartctl --info --attributes --health  --format=brief /dev/nvme0

smartctl 6.5 2016-05-07 r4318 [x86_64-linux-4.1.27-gvt-yocto-standard] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       TS128GMTE850
Serial Number:                      D704940282?
Firmware Version:                   C2.3.13
PCI Vendor/Subsystem ID:            0x126f
IEEE OUI Identifier:                0x000000
Controller ID:                      1
Number of Namespaces:               1
Namespace 1 Size/Capacity:          128,035,676,160 [128 GB]
Namespace 1 Formatted LBA Size:     512
Local Time is:                      Fri Jun 15 11:41:35 2018 UTC

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02, NSID 0xffffffff)
Critical Warning:                   0x00
Temperature:                        38 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    16%
Data Units Read:                    11,836,935 [6.06 TB]
Data Units Written:                 62,288,091 [31.8 TB]
Host Read Commands:                 135,924,188
Host Write Commands:                7,715,573,429
Controller Busy Time:               4,042
Power Cycles:                       472
Power On Hours:                     6,038
Unsafe Shutdowns:                   355
Media and Data Integrity Errors:    0
Error Information Log Entries:      119,699
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0

**Comment by coccobill1** [comment]
The plugin still only seems to save smart_device data to influxdb for my 970 EVO NVME drive, not smart_attribute.

**Comment by danielnelson** [comment]
@coccobill1 Could you open a new issue with the output described [here](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/smart#troubleshooting)?

**Comment by coccobill1** [comment]
Sure, hope this helps: https://github.com/influxdata/telegraf/issues/6032
