### ISSUE TITLE
Telegraf Rate limiting feature - the ability to detect and reduce spikes in traffic automatically

### ISSUE THREAD

**Issue by edbernier** [influxdata/telegraf#4171]
## Feature Request

Requesting an ability to add rate limiting capability to Telegraf.  For example: If traffic increased more than x% for any series reduce the rate by randomizing the data by the same percentage increase to maintain a certain ingest rate.

### Proposal:

We need to have some kind of rate limiting features.  These are some of the things we are looking for…
 
a.	A simple % sampling based on TAG or MEASUREMENT criteria set
 
CRITERIA_SET_1:
    SAMPLE_RATE # i.e., 0.1 or 10%
CRITERIA_SET_2:
    SAMPLE_RATE
DEFAULT:
     SAMPLE_RATE
 
b.	Another thing we may want as an alternative to an explicit rate is a count over time parameter, possibly mixed and matched with sample rate…
 
CRITERIA_SET_1:
    SAMPLE_RATE
CRITERIA_SET_2:
    N PER TIME # i.e., 100000 PER 1h
DEFAULT:
     SAMPLE_RATE

**Comment by JimHagan** [comment]
Important complementary feature to https://github.com/influxdata/influxdb/issues/9878

**Comment by danielnelson** [comment]
Also see this feature request for a monitoring cardinality #4124

**Comment by danielnelson** [comment]
I think this would work well as a processor.  The processor can select metrics using [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) and skip every 1/factor metrics.

Example that skips half of the cpu measurements:
```
[[processors.sample]]
  namepass = ["cpu"]
  factor = 0.5
```

**Comment by timhallinflux** [comment]
is reducing the data collection rate a "simple" (i.e. no code) option?  Doesn't it achieve the same result??

**Comment by danielnelson** [comment]
For metrics produced by Telegraf via polling I would say yes, but if the metrics are produced by another application and sent to a service input it may be difficult to limit the amount of data.

In this case another solution might be to use an aggregator such as basicstats or histogram to report the aggregate metrics only.

**Comment by reimda** [comment]
Telegraf has changed a lot since this issue was filed. In some cases it can now use backpressure to stop gathering metrics when outputs can't keep up writing what is queued.

Since so much has changed since this was filed it makes sense to me to close this. If you have specific needs related to rate limiting please open a new issue and reference this one. Thanks!
