### ISSUE TITLE
Telegraf - Windows2008R2  & Windows 10 

### ISSUE THREAD

**Issue by esxi1979** [influxdata/telegraf#4172]
Hello i followed

https://docs.influxdata.com/telegraf/v1.6/administration/windows_service/

i see err

E! Error parsing C:\Program Files\Telegraf\telegraf.conf, Undefined but requested input: processes

Also  when  i tried to start it from Windows UI  i get 

System error 1067 has occurred.
The process terminated unexpectedly

Any suggestions  pls 
thanks 
.

**Comment by danielnelson** [comment]
The processes plugin is only available on unix systems, on Windows the win_perf_counters plugin is the closest replacement.

**Comment by danielnelson** [comment]
I'll open a new issue to document any plugin platform restrictions.

**Comment by esxi1979** [comment]
thanks, that was quick response & checked just now :( ,  for records, i did tried things in 

https://github.com/influxdata/telegraf/issues/3660

https://github.com/influxdata/telegraf/issues/860

both with no luck 

ie
stuff explained in https://www.ricardclau.com/2016/03/running-go-executables-consul-telegraf-as-windows-services/

in short 
nssm install Telegraf C:\telegraf\telegraf.exe -config C:\telegraf\telegraf.conf

...

**Comment by esxi1979** [comment]
@danielnelson  working well with win_perf_counters  , thanks
