### ISSUE TITLE
Document any plugin platform restrictions

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4173]
### Proposal:

Some plugins, such as the processes plugin, don't work on all platforms.  Document all platform restrictions on the plugins README

### Current behavior:

Not documented

### Desired behavior:

Documented

### Use case: [Why is this important (helps with prioritizing requests)]

Avoid confusion when plugin cannot be loaded: #4172

**Comment by sspaink** [comment]
Closing as this will probably need to be handled by a per-plugin bases, and windows restricted plugins are labeled with the appropriate build flag. We have a separate windows sample config being generated as well that shows the only available plugins for windows as well.
