### ISSUE TITLE
logparser not working before restart telegraf at first on ubuntu14.04

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#4192]
### System info:
ubuntu14.04
telegraf-1.6.1

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

Test on ubuntu14.04:
After install telegraf, the process is alive. But the logparser is not working.
But, after restart telegraf,  logparser start to work.

Test on ubuntu16.04:
After install telegraf, everything works fine.
No need to restart telegraf again.

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by crazy-canux** [comment]
I did the same thing on ubuntu14 and ubuntu16.
Here is the steps:
    1. install deb package
    2. stop telegraf process.
    3. copy my config to /etc/telegraf (enable logparser here).
    4. start telegraf process.
    5. But logparser not working on ubuntu14.04.
    6. restart telegraf on ubuntu14.04 and logparser back to work.

Don't know why.

**Comment by danielnelson** [comment]
Can you provide the config file you are using (remove any sensitive info first)?

**Comment by crazy-canux** [comment]
[[inputs.logparser]]
#   ## Log files to parse.
#   ## These accept standard unix glob matching rules, but with the addition of
#   ## ** as a "super asterisk". ie:
#   ##   /var/log/**.log     -> recursively find all .log files in /var/log
#   ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
#   ##   /var/log/apache.log -> only tail the apache log file
   files = ["/opt/sandboxav/logs/appliance.log"]
#
#   ## Read files that currently exist from the beginning. Files that are created
#   ## while telegraf is running (and that match the "files" globs) will always
#   ## be read from the beginning.
   from_beginning = false
#
#   ## Method used to watch for file updates.  Can be either "inotify" or "poll".
    watch_method = "poll"
#
#   ## Parse logstash-style "grok" patterns:
#   ##   Telegraf built-in parsing patterns: https://goo.gl/dkay10
   [inputs.logparser.grok]
#     ## This is a list of patterns to check the given log file(s) for.
#     ## Note that adding patterns here increases processing time. The most
#     ## efficient configuration is to have one pattern per logparser.
#     ## Other common built-in patterns are:
#     ##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
#     ##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
     patterns = ['''%{TIMESTAMP_ISO8601:asctime:string} \[%{DATA:name:string}\] %{LOGLEVEL_PYTHON:levelname:string}: %{GREEDY
DATA:message:string}''']
#
#     ## Name of the outputted measurement name.
     measurement = "sandboxav_log"
#
#     ## Full path(s) to custom pattern files.
#     custom_pattern_files = []
#
#     ## Custom patterns can also be defined here. Put one pattern per line.
     custom_patterns = '''LOGLEVEL_PYTHON (?:WARNING|ERROR|CRITICAL)'''

**Comment by sjwang90** [comment]
@crazy-canux `inputs.logparser` was deprecated in 1.15. Can you please check if this is still an issue with the [tail](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/taill) plugin along with the [`grok` data format](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok).

**Comment by crazy-canux** [comment]
Yes tail works fine!
Thanks!
