### ISSUE TITLE
Aerospike plugin memory leak

### ISSUE THREAD

**Issue by deric** [influxdata/telegraf#4195]
### Relevant telegraf.conf:

```
[[inputs.aerospike]]
  servers = ["localhost:3000"]
```

### System info:

* Debian GNU/Linux 8.10 (jessie)
* telegraf `1.6.3-1`

### Steps to reproduce:

1. Upgrade to `1.6.3`
2. Configure `aerospike` input

### Expected behavior:

Don't leak memory.

### Actual behavior:

Leaks memory. A lot. After 24h uptime telegraf occupies `10GB` RAM

### Additional info:

There was no problem with `1.6.2`, quite likely related to changes done in #4127.

cc @TheSAS

**Comment by TheSAS** [comment]
Sorry. 
Seems like it is true (((, i can confirm that memory leak also. Strange that it wasn't spotted while testing that change on test environment.
I'll try to do memory profile using pprof.

**Comment by shadowlord017** [comment]
Same thing. 1.6.3, aerospike plugin, Ubuntu 16.04

**Comment by danielnelson** [comment]
I'm planning to do the 1.6.4 release on Monday, it seems that we should revert back to the previous version for now due to the amount of memory being used.

**Comment by danielnelson** [comment]
I have reverted to the previous version, but lets keep this open until we are able to update.

**Comment by zaaraameera2014** [comment]
Tyxhshbjwj

**Comment by zaaraameera2014** [comment]
R58HC45JKVD

**Comment by deric** [comment]
@danielnelson Currently refactored [`Gopkg.toml`](https://github.com/influxdata/telegraf/blob/master/Gopkg.toml#L7) uses `version = "^1.33.0"` which is going to re-introduce this memory leak. 
I'd recommend using
```
`version = "<=1.27.0"`
```
until the issue in `aerospike-client-go` is resolved.

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/pull/4462
