### ISSUE TITLE
Support NVMe devices via NVME-CLI input plugin

### ISSUE THREAD

**Issue by digitalcryptor** [influxdata/telegraf#4197]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Currently we can add nvme-cli via an apk add but we need the data parsed via an input plugin.

Using nvme-cli, I can get these results from a Samsung 970 Pro with this command:

```
nvme smart-log /dev/nvme0n1

Smart Log for NVME device:nvme0n1 namespace-id:ffffffff
critical_warning                    : 0
temperature                         : 41 C
available_spare                     : 100%
available_spare_threshold           : 10%
percentage_used                     : 0%
data_units_read                     : 1593072
data_units_written                  : 1145633
host_read_commands                  : 1104069
host_write_commands                 : 1382225
controller_busy_time                : 16
power_cycles                        : 3
power_on_hours                      : 9
unsafe_shutdowns                    : 0
media_errors                        : 0
num_err_log_entries                 : 0
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Temperature Sensor 1                : 41 C
Temperature Sensor 2                : 50 C
```
### Current behavior:

Currently data on NVMe drives are not collected.

### Desired behavior:

It should parse output from nvme-cli with NVMe drives.

### Use case: [Why is this important (helps with prioritizing requests)]

NVMe drives!

**Comment by danielnelson** [comment]
This would be nice information, but we should investigate what methods are available to obtain this data.  For SMART data we may want to do this: https://github.com/influxdata/telegraf/issues/4169

For other information if there is a possibility to pull the data from `/proc` or `/sys` we should prefer this for performance.

**Comment by sspaink** [comment]
@digitalcryptor Now that https://github.com/influxdata/telegraf/pull/5765 has been merged, does using the SMART plugin solve this for you?
