### ISSUE TITLE
win_perf Process collecting % Processor Time in different interval

### ISSUE THREAD

**Issue by matthenning** [influxdata/telegraf#4198]
### Relevant telegraf.conf:

```
 [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set"]
    Instances = ["*"]
    Measurement = "win_proc"
```
### System info:

Telegraf v1.6.1
Windows Server 2012 R2

### Expected behavior:

All values are collected in the defined interval (1m)

### Actual behavior:

~% Processor Time is only collected once when starting telegraf.
In the following flush intervals I only receive data from the other counters.~
% Processor Time is collected in a completely different interval ranging from 6 to 12 minutes (for now).
There are no warnings or errors in the telegraf console.

**Comment by danielnelson** [comment]
We have made a fairly large update to this plugin for the next release 1.7, would it be possible for you to test with the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and check if you see the same behavior?

**Comment by matthenning** [comment]
It's working with the current nightly build.
InfluxDB now receives metrics every minute.

**Comment by danielnelson** [comment]
Good news, thank you for the update.
