### ISSUE TITLE
Telegraf logparser output prometheus_client help needed

### ISSUE THREAD

**Issue by IngussNeilands** [influxdata/telegraf#4199]
Hi, i am trying to count number of lines based on text string in them and send that info to prometheus_client.
My log file looks like this:

```
2018-05-25T11:09:59.084943+00:00 somehost-a0-2ut appname:  Use of uninitialized value in join or string at /usr/local/lib/...
2018-05-25T11:10:00.345101+00:00 somehost-c4-yac othername:  splice() offset past end of array at /usr/local/lib/...
2018-05-25T11:10:01.148878+00:00 somehost-a3-2ut somthing:  Retrying (403) https://s3-eu-west-1.amazonaws.com/something/...
```

Could you help me writing correct pattern?

```
[[inputs.logparser]]
  files = ["/var/log/some-file-*.log"]
  from_beginning = false
  [inputs.logparser.grok]
    pattern: "[.* ]%{C_TEXT:error_count}[ .*]"
    custom_patterns: [ "C_TEXT somehost-.*" ]
    measurement = "errors_count"
    timezone = "UTC"
```

I can see these lines in outputs.file, but not in prometheus_client...

**Comment by danielnelson** [comment]
> I can see these lines in outputs.file, but not in prometheus_client...

This probably means that you only have numeric types.  Prometheus only supports numeric values, any strings need to be tags.  To do this you need to use a ["modifier"](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser#grok-parser):

```
    pattern: "[.* ]%{C_TEXT:error_count:int}[ .*]"
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by IngussNeilands** [comment]
when i add :int i get: E! Error parsing log line: logparser_grok: must have one or more fields

also if i have multiple lines per second - will telegraf count them together? I would expect to tal value per period. Is that even possible?

**Comment by IngussNeilands** [comment]
moved to https://community.influxdata.com/t/telegraf-logparser-output-prometheus-client-help-needed/5338
