### ISSUE TITLE
procstat for telegraf capturing subcommands that are run

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4200]
### Relevant telegraf.conf:
```
[[inputs.procstat]] 
  exe = "^telegraf$"
```
### System info:

Telegraf v1.6.1 (git: release-1.6 bf0ab27f)
Ubuntu 14.04.5 LTS

### Steps to reproduce:

1. enable this along with the diskio plugin
2. notice that in addition to telegraf, other process_names are being gathered

### Expected behavior:
there should be a way to ensure that procstat is only capturing the main process, not the subcommands

### Actual behavior:
procstat captures additional processes

**Comment by danielnelson** [comment]
Possible workaround is to use the pid method to find telegraf.

**Comment by sspaink** [comment]
Closing given there is an alternative solution and there hasn't been activity/demand for this issue for a while.
