### ISSUE TITLE
telegraf not working on windows 7 32bit

### ISSUE THREAD

**Issue by mmhabd12** [influxdata/telegraf#4213]
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I am guessing you are experiencing https://github.com/influxdata/telegraf/issues/2468.  This issue is resolved in 1.7.0.
