### ISSUE TITLE
[Bug] http_listener plugin doesn't conform Influx Line Protocol specification

### ISSUE THREAD

**Issue by Fiery-Fenix** [influxdata/telegraf#4214]
### System info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
$ telegraf --version
Telegraf v1.6.3 (git: release-1.6 890f1d3a)
```

Sample config:
```
[agent]
flush_interval = "10s"
metric_batch_size = 1000
collection_jitter = "0s"
round_interval = false
debug = true
metric_buffer_limit = 10000
interval = "10s"
quiet = false
flush_jitter = "0s"

[[inputs.http_listener]]
service_address = "127.0.0.1:8086"
read_timeout = "10s"
write_timeout = "10s"
```

### Steps to reproduce:

```
curl -i -XPOST 'http://localhost:8086/write' --data-binary 'test,tag_test=test filed="some\value\with\slashes" 1527737416233113600'
```

### Expected behavior:
``HTTP/1.1 204 No Content`` as result

### Actual behavior:
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
X-Influxdb-Version: 1.0
Content-Length: 29
{"error":"http: bad request"}
```

### Additional info:
Documentation to [InfluxDB Line Protocol](https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_tutorial/) mentioned that:

> Line Protocol does not require users to escape the backslash character \ but will not complain if you do.

InfluxDB version 1.5.2, Telegraf version 1.5.x accepts field values with slashes without issues. Telegraf 1.6.x - throw error.

**Comment by danielnelson** [comment]
I acknowledge this is a difference, but for simplicity I decided not to support optionally escaped backslashes within string fields in the new parser.  You can send the same information if you always escape `"` and `\` inside string fields.
```
test,tag_test=test filed="some\\value\\with\\slashes"
```

There are also some situations where you must escape backslashes so it's not safe to skip escaping them:
```
test foo="trailing-slash\\"
```

You would also need to switch methods depending on the number of backslashes:
```
test foo="a\b" # one slash
test foo="a\\b" # one slash
test foo="a\\\b" # two slashes
test foo="a\\\\b" # two slashes
```

There is a request to get the documentation updated: https://github.com/influxdata/docs.influxdata.com/issues/1295
