### ISSUE TITLE
procstat collect the services releated processes

### ISSUE THREAD

**Issue by pytimer** [influxdata/telegraf#4217]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

I hope telegraf can auto collect the specified service processes. Includes Windows, Linux and other platforms.

When add a `inputs.procstat` configuration, telegraf can monitor match services and all processes of service.

This feature can monitor services and collect metrics easily, not care service process name.

I don't know if my idea correct?

### Current behavior:

- Linux use `system_unit` option only collect `MainPID` process metrics. If no `MainPID`, telegraf not collect it.

- Windows no option can do it currently.

### Desired behavior:

Hope telegraf can collect systemd cgroup all processes metrics, not only main pid. 

Add Windows option to do it.

### Use case: [Why is this important (helps with prioritizing requests)]

In my use case, a program create telegraf config file, when i add a systemd service, i will add a `inputs.procstat` and use `system_unit` option to collect this service processes metrics. like below:

```toml
[[inputs.procstat]]
        systemd_unit = "notify"
```

I don't know this service cgroup path and process releated information, so i only can config `system_unit` for procstat.

**Comment by freeseacher** [comment]
yep can't wait to see that in telegraf

**Comment by srebhan** [comment]
@pytimer and @freeseacher have you tried the `win_service` option? It reads like exactly what you are looking for!?

**Comment by freeseacher** [comment]
i do not use telegraf no more

**Comment by srebhan** [comment]
@freeseacher sad to hear this...

Closing this issue as I think `inputs.win_service` does exactly this. If this is not the case, please either reopen this issue or file a new one...
