### ISSUE TITLE
[[outputs.http]] does not honor data_format other than "influx"

### ISSUE THREAD

**Issue by GeckoZero** [influxdata/telegraf#4224]
### Intro:
Hi there,

I'm using telegraf for a longer time now, and I just wanted to try the http output plugin from the 1.7.x nightly build. It works as expected with one exception: There seems to be a bug with the data_format selector.

More info below...

Greetings
Gecko Zero

### Relevant telegraf.conf:
[[outputs.http]]
  url = "http://127.0.0.1:80/monitor/telegraf"
  ...
  data_format = "json"

### System info:

Debian 8.10 amd64 (3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux)

Nightly telegraf (b556eb8b)
Nigthly telegraf (5ae2b02f)

I can reproduce the problem in both nightly builds...

### Steps to reproduce:
1. Install debian package with: dpkg --install telegraf_nightly_amd64.deb
2. Choose whatever you want in the "data_format" setting of the telegraf http output plugin
3. Run telegraf either way. I started it with: telegraf --debug --config /etc/telegraf/telegraf.conf

### Expected behavior:
The telegraf http output plugin should honor the setting of "data_format" and support all available telegraf output data formats

### Actual behavior:
The telegraf http output plugin always sends data in "influx" data format, regardless of the "data_format" setting

### Additional info:
n/a

**Comment by Dark0096** [comment]
@GeckoZero When I checked the problem quickly, changing the order of the setting values would eliminate the problem first.

*Issue Config*
`[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://127.0.0.1:2002/metric"

  ## Timeout for HTTP message
  timeout = "5s"

  ## HTTP method, one of: "POST" or "PUT"
  method = "POST"

  ## HTTP Basic Auth credentials
  # username = "username"
  # password = "pa$$word"

  ## Additional HTTP headers
  [outputs.http.headers]
    # Should be set manually to "application/json" for json data_format
    Content-Type = "application/json; charset=utf-8"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Data format to output.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"`

*Resolved Config*
`[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://127.0.0.1:2002/metric"

  ## Timeout for HTTP message
  timeout = "5s"

  ## HTTP method, one of: "POST" or "PUT"
  method = "POST"

  ## HTTP Basic Auth credentials
  # username = "username"
  # password = "pa$$word"

  ## Data format to output.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"

  ## Additional HTTP headers
  [outputs.http.headers]
    # Should be set manually to "application/json" for json data_format
    Content-Type = "application/json; charset=utf-8"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false`

I think that after the [outputs.http.headers] statement at the top, it seems to be a setting of outputs.http.headers, not a configuration of outputs.http. I should look for a more accurate reason. First of all, it seems that you can use it without problems if you change the position as above.

**Comment by Dark0096** [comment]
I modified the code as shown below.
https://github.com/influxdata/telegraf/pull/4225

**Comment by GeckoZero** [comment]
@Dark0096
I can confirm that this did the trick. It works now as expected. Awesome, thx and closed... :)
