### ISSUE TITLE
freebsd ping is missing most features

### ISSUE THREAD

**Issue by nordic-style** [influxdata/telegraf#4227]
### Relevant telegraf.conf:
[[inputs.ping]]
  urls = ['heise.de','golem.de','8.8.8.8','computerbase.de']
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 10
### System info:
uname -a
FreeBSD xyz.de 11.1-RELEASE-p10 FreeBSD 11.1-RELEASE-p10  a6fa9599a(stable/18.1)  amd64

telegraf --version
Telegraf v1.7.0~b556eb8b (git: master b556eb8b)

(doesnt  work with 1.6.3, too)

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
1) create config file with configuration from above

2) check telegraf:
telegraf --config telegraf.conf --input-filter ping --test

### Expected behavior:
* Plugin: inputs.ping, Collection 1
> ping,host=xyz.de,url=8.8.8.8 percent_packet_loss=0,minimum_response_ms=9.026,average_response_ms=9.026,maximum_response_ms=9.026,standard_deviation_ms=0,result_code=0i,packets_transmitted=1i,packets_received=1i 1528065414000000000
> ping,host=xyz.de,url=heise.de packets_transmitted=1i,packets_received=1i,percent_packet_loss=0,minimum_response_ms=7.231,average_response_ms=7.231,maximum_response_ms=7.231,standard_deviation_ms=0,result_code=0i 1528065414000000000
> ping,host=xyz.de,url=computerbase.de packets_transmitted=1i,packets_received=1i,percent_packet_loss=0,minimum_response_ms=10.889,average_response_ms=10.889,maximum_response_ms=10.889,standard_deviation_ms=0,result_code=0i 1528065414000000000
> ping,host=xyz.de,url=golem.de percent_packet_loss=0,minimum_response_ms=17.839,average_response_ms=17.839,maximum_response_ms=17.839,standard_deviation_ms=0,result_code=0i,packets_transmitted=1i,packets_received=1i 1528065414000000000

### Actual behavior:
> ping,host=xyz.de,url=computerbase.de result_code=0i 1528064815000000000
> ping,host=xyz.de,url=8.8.8.8 result_code=0i 1528064815000000000
> ping,host=xyz.de,url=heise.de result_code=0i 1528064815000000000
> ping,host=xyz.de,url=golem.de result_code=0i 1528064815000000000

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I will include this in 1.7.0-rc2

**Comment by nordic-style** [comment]
Great! Working with nightly build 👍
