### ISSUE TITLE
Windows Perfomance Counter - problem with instance that have same name like chrome or svchost on windows os

### ISSUE THREAD

**Issue by runningAgain** [influxdata/telegraf#4233]
### Relevant telegraf.conf:
[global_tags]

[agent]
  interval = "15s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = true
  logfile = ""
  hostname = ""

[[outputs.influxdb]]
  urls = ["http://<DBHost>:8086"]
  database = "<DBName>"
  precision = "s"
  timeout = "5s"
  username = "<DBUser>"
  password = "<DBPassword>"
  user_agent = "win_telegraf"

[[inputs.win_perf_counters.object]]
  ObjectName = "Process"
  Instances = ["chro*"]
  Counters = [
    "Working Set",
  ]
  Measurement = "win_proc"
  IncludeTotal=true

### System info:
Windows 7 64 Bit
Telegraf v1.6.3 (git: release-1.6 890f1d3a)

### Steps to reproduce:

1. run config test like -> telegraf.exe --config "C:\Program Files\InfluxData\Telegraf\telegraf_win_proc.conf" --test

### Expected behavior:
* Plugin: inputs.win_perf_counters, Collection 1
> win_proc,host=DESKTOP1,instance=chrome_1,objectname=Process Working_Set=102146048 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_2,objectname=Process Working_Set=5832704 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_3,objectname=Process Working_Set=6238208 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_4,objectname=Process Working_Set=16982016 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_5,objectname=Process Working_Set=17108992 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_6,objectname=Process Working_Set=31399936 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_7,objectname=Process Working_Set=30978048 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_8,objectname=Process Working_Set=35090432 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_9,objectname=Process Working_Set=57180160 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_10,objectname=Process Working_Set=34856960 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_11,objectname=Process Working_Set=60882944 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome_12,objectname=Process Working_Set=10915840 1528195645000000000

### Actual behavior:
* Plugin: inputs.win_perf_counters, Collection 1
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=102146048 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=5832704 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=6238208 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=16982016 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=17108992 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=31399936 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=30978048 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=35090432 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=57180160 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=34856960 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=60882944 1528195645000000000
> win_proc,host=DESKTOP1,instance=chrome,objectname=Process Working_Set=10915840 1528195645000000000

### Additional info:
With process that have the same process name all metrics are stored under the same process name / instance (like chrome in this example). Later, when we want to make some dashboards with grafana, we can only select one instance (like chrome). When we need to calculate the sum of values of all chrome instances, there is actually no way to do this.
When we look into windows default procmon, add this counter, then we can select more crome instances. At our example chrome,chrome#1,chrome#2,chrome#3,chrome#4 ..... and so on.

[Include gist of relevant config, logs, etc.]

**Comment by runningAgain** [comment]
![image](https://user-images.githubusercontent.com/25197235/40972268-7828871a-68c0-11e8-8c43-72fd88d9dc86.png)
Example with perfmon.

**Comment by danielnelson** [comment]
I believe this is fixed in the upcoming 1.7 release.  There is a release candidate out now [1.7.0-rc1](https://github.com/influxdata/telegraf/releases/tag/1.7.0-rc1), could you try it out and let us know how it goes?

**Comment by runningAgain** [comment]
I've tested 1.7.0-rc1 and now all instances are available, see ...
![2018-06-06_09h24_54](https://user-images.githubusercontent.com/25197235/41023103-bb3646f4-696b-11e8-9e55-13fbc0f05ff5.jpg)
