### ISSUE TITLE
I am unable to run telegraf for Windows x86

### ISSUE THREAD

**Issue by itolevy** [influxdata/telegraf#4234]
### Relevant telegraf.conf:

I've changed nothing in the configuration file apart from logfile and urls for my InfluxDB

### System info:
Telegraf version: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.0_windows_i386.zip
OS Version: VM Windows 7 ultimate 32 bit

### Steps to reproduce:

I am running the following commands:

telegraf.exe --service install
net start telegraf

### Expected behavior:

I expect the telegraf service to run without issues

### Actual behavior:

I can see that the telegraf service had been installed but its not in "Started" state nor does it
report any data to my InfluxDB. When I try to run the service manually from services.msc, 
I see that it moves to "Started" state but when I refresh the screen the status changes to nothing again. 

There is nothing helpful in the logs, all I see is the following:

2018-06-04T15:27:47Z D! Attempting connection to output: influxdb
2018-06-04T15:27:47Z D! Successfully connected to output: influxdb
2018-06-04T15:27:47Z I! Starting Telegraf (version 1.3.0)
2018-06-04T15:27:47Z I! Loaded outputs: influxdb
2018-06-04T15:27:47Z I! Loaded inputs: inputs.win_perf_counters
2018-06-04T15:27:47Z I! Tags enabled: host=XXXXX
2018-06-04T15:27:47Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"XXXXX", Flush Interval:10s 

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
There is a [known issue](https://github.com/influxdata/telegraf/issues/2468) with 32-bit Windows and the win_perf_counters issue in the current release, but it should be fixed in the latest [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and the upcoming 1.7.
