### ISSUE TITLE
Ability to report own metrics

### ISSUE THREAD

**Issue by rbkasat** [influxdata/telegraf#4239]
## Feature Request
Telegraf needs to have a "telegraf" input plugin which can send "telegraf's" own monitoring metrics
eg:
number of events processed
events sent to
events dropped
current queue size
input error
output error

Opening a feature request kicks off a discussion.

### Proposal:
Telegraf should expose an api to fetch realitime metrics
New input plugin to fetch metrics from above api.

something similar to logstash monitoring api

### Current behavior:
No way to monitor stats

**Comment by danielnelson** [comment]
Take a look at the `internal` plugin and see if it has all the metrics you are looking for.  The name is somewhat poor, I agree it would be easier to find if we renamed it to `telegraf`.
