### ISSUE TITLE
Wavefront output replaces / with - in metrics

### ISSUE THREAD

**Issue by dimas** [influxdata/telegraf#4240]
### System info:

Ubuntu 14.04, telegrad 1.6.2

### Steps to reproduce:

1. First, as a proof that slashes are not lost by input, this config:
```
[[inputs.socket_listener]]
  service_address = "tcp://:8089"
  data_format = "influx"

[[outputs.socket_writer]]
  address = "tcp://localhost:7777"
  data_format = "influx"
```
then `nc -k -v -l 7777` in one terminal and `echo 'measurement.xxxxx/yyyyy.path value=100 1528225557' | nc -v localhost 8089` in another, make `nc` receive:
```
measurement.xxxxx/yyyyy.path,host=i-05e56b63573fd3a76 value=100 1528225557
```
So the slash was not lost
2. Now change output to
```
[[outputs.wavefront]]
  host = "localhost"
  port = 7777
  convert_paths = false
```
and then use the same set of commands to generate metric and receive it.

### Expected behavior:
The Wavefront docs https://docs.wavefront.com/wavefront_data_format.html says that 
> Valid characters are: a-z, A-Z, 0-9, hyphen ("-"), underscore ("_"), dot ("."). Forward slash ("/") and comma (",") are allowed if metricName is enclosed in double quotes.

So I would expect slash to be kept. Probably quoted.

### Actual behavior:
`nc` receives:
```
measurement.xxxxx-yyyyy.path 100.000000 1 source="i-05e56b63573fd3a76"
```
The slash was replaced with dash

### Additional info:

To be fair, `graphite` output does the same thing which may also be wrong. But I did not read Graphite protocol docs so I cannot be 100% sure if slash is allowed or not.

**Comment by danielnelson** [comment]
@puckpuck Can you take a look at this one?

**Comment by dimas** [comment]
@puckpuck , ours are Hystrix metrics. They look like `HystrixCommand.<commandKey>.rollingCountSuccess` and in our case the command key we giving to hystrix is kinda URL path-like string describing the operation so we end up with something like `HystrixCommand.entity/operations/update.rollingCountSuccess`

We used to send them directly to Wavefront and they work ok but if we change apps to send data via locally running telegraf, these metrics break. It is not the end of the world but will require updating lots of existing dashboards, alerts etc.

Maybe a new boolean configuration option that allows slashes ?

Cheers

**Comment by dimas** [comment]
@puckpuck hi, any update on this ?

**Comment by puckpuck** [comment]
We are going to add a new option to the Wavefront output plugin.  `use_strict` when true (default is false) will allow `/` and `,` to be accepted in metric names.
