### ISSUE TITLE
support for Proxy-Authorization for output.influxdb

### ISSUE THREAD

**Issue by nzin-appdirect** [influxdata/telegraf#4245]
## Feature Request

Hi, trying to using the Proxy setting for output.influxdb I faced an issue:  my proxy server requires authorization, aka "Proxy-Authorization" header. But it is not (yet) supported by output.influxdb

### Proposal:

I would like to contribute to add the support for proxy-authorization. It should be quite "easy": the Transport structure (https://github.com/influxdata/telegraf/blob/5f0cbd1255d8d0824469582b2d59fce40d8db0f0/plugins/outputs/influxdb/http.go#L178) has a ProxyConnectHeader field (cf https://golang.org/pkg/net/http/#Transport.ProxyConnectHeader)

My question is more: if I implement it, and submit it (as a PR), will you take it into consideration?

### Current behavior:

As stated above, there is not way to specify the "Proxy-Authorization" proxy header. i.e. the output.influxdb Headers are passed after the proxy handshake.

### Desired behavior:

I would like to have a way to pass a Proxy-Authorization value

**Comment by nzin-appdirect** [comment]
I think I found a way.
i.e.
```http_proxy = "https://<user>:<password>@proxy_server```

**Comment by danielnelson** [comment]
I think it would make sense to have a `proxy_username` and `proxy_password` options that could be encoded as HTTP Basic Auth and placed into the Proxy-Authorization header for the CONNECT method, or possibly something that works like the curl `--proxy-basic` option.

**Comment by nzin-appdirect** [comment]
@danielnelson in fact, looking how to implement, I saw that the feature is already there. Simply do something like:
```
[[outputs.influxdb]]
  urls = ["https://myendpoint"]
  http_proxy = "https://proxy_login_urlencode:proxy_password@myproxyserver"
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  ...
```
