### ISSUE TITLE
Unexpected list of default places of configuration file

### ISSUE THREAD

**Issue by Alessar** [influxdata/telegraf#4249]
Downloadng telegraf 1.7.0-rc1.
Extracting contents into _any_ folder.
There are two files: `telegraf.exe` and `telegraf.conf`
Executing telegraf.exe

### Expected behavior
Telegraf starts working...

### Actual behavior
Telegraf does not start working.
There is error in console:
`E! No config file specified, and could not find one in $TELEGRAF_CONFIG_PATH, /.telegraf/telegraf.conf, or C:\Program Files\Telegraf\telegraf.conf`

More over:
If `telegraf.conf` is been moved into subfolder `telegraf` or `.telegraf` the same error still happened.

### Suggestion
(Require add) Telegraf should check `telegraf.conf` in directory where `telegraf.exe` is situated.
(Maybe add) Telegraf should check `telegraf.conf` in current directory (where it was executed).
(Maybe remove) Telegraf do not need check configuration in subfolder like `/.telegraf/telegraf.conf`

**Comment by sspaink** [comment]
Closing because we won't be adding this new default location to Telegraf, its recommended to provide the config explicitly using `--config`.
