### ISSUE TITLE
1.7.0-rc1 PerfMon % Processor Time discrepancy

### ISSUE THREAD

**Issue by matthenning** [influxdata/telegraf#4250]
### Relevant telegraf.conf:

```
[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "***"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["https://***:8086"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "***"
  password = "***"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
    Measurement = "win_cpu"
    IncludeTotal=true
```

### System info:

Telegraf: 1.7.0-rc1
Windows: Server 2012 R2

### Steps to reproduce:

Compare % Process Time in Grafana (or the graphing tool of your choice) and perfmon

### Expected behavior:

The collected values are identical to the actual values on the system

### Actual behavior:

During the time span where CPU Load was at 100% in the following screenshot perfmon reported a steady load of 82-88% of the same exact counter, so 12-15% less than the collected value.
![grafik](https://user-images.githubusercontent.com/5699183/41091793-b397aee2-6a47-11e8-9c31-46f8017ce93b.png)

**Comment by danielnelson** [comment]
Thank you for the help testing.  I'm not sure what would cause the difference here, would it be possible to upload an image of your perfmon output against the raw data in influxdb using the `influx` command and running `select Percent_Processor_time from win_cpu where time > $starttime and time < $endtime` with the appropriate time bounds.

**Comment by matthenning** [comment]
For this test we reduced the interval from 60s to 10s:

Query output (all times without +02:00):
```
> SELECT "Percent_Processor_Time" FROM "win_cpu" WHERE "host" = '***' AND "instance" = '_Total' AND time > NOW()-2m
name: win_cpu
time                 Percent_Processor_Time
----                 ----------------------
2018-06-08T07:24:01Z 60.84709548950195
2018-06-08T07:24:25Z 77.2288589477539
2018-06-08T07:24:33Z 53.76494598388672
2018-06-08T07:24:41Z 49.0409049987793
2018-06-08T07:24:53Z 39.62447738647461
2018-06-08T07:25:04Z 52.0313606262207
2018-06-08T07:25:15Z 55.34902572631836
2018-06-08T07:25:25Z 64.83545684814453
2018-06-08T07:25:31Z 52.79405975341797
2018-06-08T07:25:43Z 65.84320068359375
```

PerfMon output with the original data in red and the influx query output approximately added in green:
![grafik](https://user-images.githubusercontent.com/5699183/41145097-442a2680-6aff-11e8-8ca5-af674e086aee.png)

**Comment by matthenning** [comment]
This is a multi processor system in case that's important.

**Comment by danielnelson** [comment]
I wonder if this could be because we are using the Telegraf time instead of the counter time.  @vlastahajek We should bring in the UsePerfCounterTime feature from #4076.

**Comment by matthenning** [comment]
I'm available for testing of required

**Comment by vlastahajek** [comment]
When using Telegraf 1.6, are the results  ok?

**Comment by matthenning** [comment]
In 1.6 there was a different issue with this counter: #4198

**Comment by matthenning** [comment]
Thank you for your effort folks.

**Comment by danielnelson** [comment]
@matthenning Would it be possible for you to test out the fix with a [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) to see if it helps with the accuracy?  The change was a little larger than I would normally backport for a patch release but if it solves the issue and is well tested we can consider it.

**Comment by matthenning** [comment]
I fear the problem isn't solved yet.

Perfmon:
![grafik](https://user-images.githubusercontent.com/5699183/42203421-ffa6e4ea-7e9e-11e8-9fba-60616bc0c3f6.png)

Grafana:
![grafik](https://user-images.githubusercontent.com/5699183/42203439-0ae6f2fa-7e9f-11e8-8af8-243309b12481.png)

Query:
```
SELECT 
	last("Percent_Processor_Time") 
FROM 
	"win_cpu" 
WHERE (
	"host" = '***' 
	AND "instance" = '_Total') 
	AND $timeFilter 
GROUP BY 
	time($__interval)
fill(linear)
```

Relevant Telegraf config:
```
[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "***"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["***"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "***"
  password = "***"
   

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true
  UsePerfCounterTime = true
  
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
    Measurement = "win_cpu"
    IncludeTotal=true
```

Telegraf v1.8.0~abfbf4f4 (git: master abfbf4f4)

**Comment by vlastahajek** [comment]
It seems that Perfmon uses different way of gathering data. On my laptop it even offers counters that are not available by Telegraf or Typeperf (MS command line tool for reading performance counters). E.g. \Battery Status

I did test over shorter period of time with 2s interval:

If I try Typeperf, which uses the same mechanism of accessing counters as Telegraf, it returns very similar data (it's hard to precisely synchronize points of measurements) :
 
![image](https://user-images.githubusercontent.com/29980246/42225673-6331a9f8-7edd-11e8-9293-c7c069bd1812.png)

Same measurement in perfmon:
![image](https://user-images.githubusercontent.com/29980246/42225862-d3a44538-7edd-11e8-9eaa-cf46e9704c0b.png)

To show even different values, see CPU activity progress from Taskmgr measured over the same period:
![image](https://user-images.githubusercontent.com/29980246/42226087-57920f4c-7ede-11e8-8e63-78b84ebdf167.png)

I will try longer test tomorrow.

**Comment by matthenning** [comment]
Taskmgr values almost match your typeperf data. 
Maybe perfmon is the problem and there is nothing to fix here?

**Comment by vlastahajek** [comment]
The main difference is that taskmgr shows even different scale of values. The values there reach 100%, which wasn't noted by any other method of measurement.

I didn't investigated the science behind CPU activity measurement, so it is hard to say what is wrong and what is right. For sure we can say that Telegraf provides good results with respect to the way how it collects data from performance counters.

Is there any other metrics you are interested in we can look at and compare?
