### ISSUE TITLE
[[inputs.mongodb]] adding querys for mongodb? 

### ISSUE THREAD

**Issue by fchiorascu** [influxdata/telegraf#4252]
### Proposal:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mongodb
Is there a possibility to have 1 or 2 queries or something optimized for future releases in order to query also inside MongoDB?

### Current behavior:
Nothing regarding queries in case of MongoDB.

### Desired behavior:
To have some queries like for mysql: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql

### Use case: [Why is this important (helps with prioritizing requests)]
Because MongoDB is a DB very used nowadays and it is very good to have this implemented to track some behaviors. In addition to this it will offer more visibility to the users.

**Comment by fchiorascu** [comment]
Hi Daniel,

What i would seek for this queries is related to a normal behavior of the database when is under Production with > nnn clients.
The main topics that I'm interested are some queries for:
- Add something recurrent in the database.
- Delete something from the database.
- Update something in the database;
- Search something or multiple things in database in order to track an action;
More or less to be able to have this type of queries that could be validated with an value or a tag: 0/ 1, success, not ok. Something like this in order to know that the action was ok.

Because on daily basis I track the performance of the database, but what is doing exactly and if is working ok for example for 1 client I don't have such a visibility, and if something is going wrog for a client then I could observe and check if is something general or isolated, single user case.
I'll start with this, they are very good things to have.

Kind Regards,

**Comment by fchiorascu** [comment]
Hi Daniel.

I think that is a very good idea to implement in case of MongoDB, I like the option and I found it very useful.
Thank you for understanding and support. I'll wait and I hope this will be implemented in the next 2 months. All the best wishes.

Kind Regards,

**Comment by lchunleo** [comment]
Hi

 i have quite a similar use where i actually store data in my mongodb. But i would like to use Telegraf to get the custom data out and put into influxdata to visualize and do time series related analysis.. Is this possible? thanks

**Comment by ssoroka** [comment]
So at this point we're looking for someone to contribute a custom plugin to do this, following the example of the postgres_extensible input plugin/

**Comment by reimda** [comment]
@fchiorascu It's been a long time since this was discussed. Do you still need this? There hasn't been much demand for it. Are you able to put together a PR to implement it? Thanks
