### ISSUE TITLE
Define custom name/display name when installing telegraf as a windows service

### ISSUE THREAD

**Issue by huangqiz** [influxdata/telegraf#4263]
## Feature Request

Define custom name/display name when installing telegraf as a windows service, such as
`telegraf.exe --service install --name "Telegraf custom"`
### Current behavior:
According to the following thread there's currently no way to define custom name and display name while installing telegraf as a service:
https://github.com/influxdata/telegraf/issues/860 
### Desired behavior:
Being able to define custom name/display name when installing telegraf as a windows service, with command like the following:
`telegraf.exe --service install --name "Telegraf custom"`

### Use case: [Why is this important (helps with prioritizing requests)]
Install multiple telegraf instances as service

**Comment by danielnelson** [comment]
I like this idea, lets call the option `--service-name` though.

**Comment by danielnelson** [comment]
@Jaeyo @huangqiz Can you tell me a little bit about why you want to run multiple Telegraf's on one system?  I'm happy to include it as an option but it seems like it shouldn't be needed.
