### ISSUE TITLE
Add support for elasticsearch 6 output

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4268]
Feature Request
Support for Elasticsearch 6.x for output plugins.

Current behavior:
Not available

Desired behavior:
Support ES6.x release

Use case:
new version of ES 6.x does not support types in mapping any more and it affects monitoring.

**Comment by lpic10** [comment]
FYI current output works on ES 6.x but with warnings on ES side like:

```
[WARN ][o.e.d.i.m.AllFieldMapper ] [_all] is deprecated in 6.0+ and will be removed in 7.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field.
```

As for the mapping type the current plugin uses a single type (which is still supported for indices created on 6.x), thus unless the indexes are shared with other applications it will work. 

Definitely the support for ES 6.x could be improved, and also to prepare for ES 7.0 breaking changes
