### ISSUE TITLE
inputs.cpu errors or return potential wrong values on Windows

### ISSUE THREAD

**Issue by back2root** [influxdata/telegraf#4269]
### Relevant telegraf.conf:
```
# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false
```

Not related to the error but only for ease of reproduction:
```
[[outputs.file]]
#   Write output to "stdout"
files = ["stdout"]
data_format = "influx"
```

### System info:

Affected operating System: **Windows**

Tested on:
- Telegraf 1.6.4
- Telegraf v1.8.0~87f711a1 (git: master 87f711a1)

### Steps to reproduce:

1. Download Telegraf
2. Ensure that inputs.cpu is enabled
3. I suggest to enable outputs.file with: _files = ["stdout"]_ as one and only output but the output shouldn't matter
3. Run Telegraf. E.g.: _telegraf -config telegraf.conf (--test)_

### Expected behavior:
Telegraf is running smothely and collecting every _interval_ seconds CPU metrics.

### Actual behavior:
From time to time Telegraf is throwing an error and isn't reporting CPU metrics for all CPU cores:

> E! Error: current total CPU time is less than previous total CPU time

The more cpu cores you have (+ percpu = true) the more likely it is that the error is thrown.

### Additional info:

Telegraf uses _[github.com/shirou/gopsutil/cpu](url)_ to gather cpu metrics and expects that the returned values are used cpu time. How ever for Windows Plattform the used library already returns percentage values that the library itself gatherd via WMI.
Thus later checks on the returned values fail as it is expected that the cpu time used may only rise on normal conditions. How ever the retruned cpu percent used will not follow this expectation. In addition later calculations of the cpu percent used makes no sence on percent values.

So for Windows plattform all the checks and calculation made by Telegraf using the variable lastStats are not needed/problematic.

**Comment by argerus** [comment]
Probably caused by this [bug](https://github.com/shirou/gopsutil/issues/420) in github.com/shirou/gopsutil/cpu

**Comment by zak-pawel** [comment]
I easily reproduced it using Telegraf 1.6.4.
I couldn't reproduce it using Telegraf 1.16.2 - seems that [mentioned bug](https://github.com/shirou/gopsutil/issues/420) in `github.com/shirou/gopsutil/cpu` was fixed [here](https://github.com/shirou/gopsutil/pull/611) in `v2.18.12` version. Currently Telegraf uses `v2.20.9`
