### ISSUE TITLE
Fibaro plugin: deviceID

### ISSUE THREAD

**Issue by mathiasahlen** [influxdata/telegraf#4274]
### Proposal:
Add devicesID as a key

### Desired behavior:
Pull/Get deviceID (number) from Fibaro API.

### Use case:
It would simplify the use of the collected data (and minimize the risk of mixing up devices).

**Comment by dynek** [comment]
Will work on this as soon as I'm able to build telegraf again :-/

**Comment by dynek** [comment]
I guess this can be closed "in favor" of the PR

**Comment by danielnelson** [comment]
Closed in #4343
