### ISSUE TITLE
make install fails: TELEGRAF undefined in Makefile

### ISSUE THREAD

**Issue by jamesbo13** [influxdata/telegraf#4278]
Building master (daddd8bb) from source. `make` works properly but `make install` reports error:
```
go build -ldflags " -X main.commit=daddd8bb -X main.branch=master" ./cmd/telegraf
mkdir -p /usr/local/bin/
cp  /usr/local/bin/
cp: missing destination file operand after '/usr/local/bin/'
Try 'cp --help' for more information.
Makefile:36: recipe for target 'install' failed
make: *** [install] Error 1
```
`make go-install` works ok.

### System info:
Telegraf master beanch
Linux (Ubuntu 17.10)

### Steps to reproduce:

1. make install
2. ...

### Expected behavior:
Install telegraf binary into /usr/local/bin

### Actual behavior:
Error reported above.

### Additional info:
It appears the Makefile variable TELEGRAF is no longer defined. Its definition was removed in commit (https://github.com/influxdata/telegraf/commit/627f0e5d9d961205c6d7b5247c0d3e2aca4c7b7b )

**Comment by danielnelson** [comment]
I decided just to hardcode the unix binary name here, since I think this target won't be of much interest on Windows.
