### ISSUE TITLE
diskio plugin runs udevadm every time

### ISSUE THREAD

**Issue by propertone** [influxdata/telegraf#4288]
In #3663, @danielnelson implied that the diskio plugin does NOT run udevadm directly, but it's actually running the udevadm command every interval for each device. We have a system with hundreds of disks/partitions and the diskio plugin takes several seconds to run because of this.

### Relevant telegraf.conf:
```
[[inputs.diskio]]
    # default configuration
```
### System info:

Telegraf: v1.6.1 (git: release-1.6 bf0ab27f)
Linux: RedHat 7.5
Kernel: 3.10.0-693.21.1.el7.x86_64

### Steps to reproduce:

1. Run telegraf with the diskio plugin using the default configuration
1. Use lastcomm to see that it's actually running udevadm every time

### Expected behavior:

udevadm is not run at all, or at least cached

### Actual behavior:

udevadm command is run every interval for each disk. Its output is not used as #3663 is still an issue.

**Comment by danielnelson** [comment]
I think I mentioned this behavior in [this comment](https://github.com/influxdata/telegraf/issues/3663#issuecomment-358181400):
> the function we call on each interval in gopsutil already runs this udevadm command for each device found without caching to get the serial number

The good news is this has already been addressed in gopsutil, which should improve the performance quite a bit.

**Comment by danielnelson** [comment]
The updated gopsutil release that does not run udevadm has been merged, so this change will be in 1.8.
