### ISSUE TITLE
no clear documentation on swap input plugin

### ISSUE THREAD

**Issue by randallt** [influxdata/telegraf#4290]
### Relevant telegraf.conf:

[[inputs.swap]]

### System info:

[Include Telegraf version, operating system name, and other relevant details]

Telegraf 1.6.4. CentOS 7.4

### Steps to reproduce:

1. Try to find clear documentation on the swap input plugin fields.
2. Fail

### Expected behavior:

I should be able to find clear documentation on what fields the swap input plugin produces, what they mean, and where they come from.

### Actual behavior:

I had to use guess and check mode and look at Go code.

**Comment by danielnelson** [comment]
We should move this plugin out into it's own file while we are at it, and create a new `SWAP_README.md`.  Longer term I would like to move all the "system" plugins out into the main plugins/inputs directory to increase uniformity.

**Comment by danielnelson** [comment]
Closed in #4342
