### ISSUE TITLE
Windows Perfomance Counter - problem with instance that have same name like chrome or svchost on windows os

### ISSUE THREAD

**Issue by runningAgain** [influxdata/telegraf#4295]
Issue like this -> https://github.com/influxdata/telegraf/issues/4233

### Relevant telegraf.conf:
[global_tags]

[agent]
interval = "15s"
round_interval = true
metric_buffer_limit = 1000
flush_buffer_when_full = true
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
debug = false
quiet = true
logfile = ""
hostname = ""

[[outputs.influxdb]]
urls = ["http://:8086"]
database = ""
precision = "s"
timeout = "5s"
username = ""
password = ""
user_agent = "win_telegraf"

[[inputs.win_perf_counters.object]]
ObjectName = "Process"
Instances = ["chro*"]
Counters = [
"Working Set",
]
Measurement = "win_proc"
IncludeTotal=true
### System info:
Windows 7 64 Bit
Telegraf v1.7.0 (Release)
### Steps to reproduce:
run config test like -> telegraf.exe --config "C:\Program Files\InfluxData\Telegraf\telegraf_win_proc.conf" --test
### Expected behavior:
C:\Program Files\InfluxData\Telegraf>telegraf.exe version
Telegraf v1.7.0~rc1 (git: release-1.7 27cd582f)

C:\Program Files\InfluxData\Telegraf>telegraf.exe --config .\telegraf_win_proc.conf --test
> win_proc,host=Desktop1,instance=chrome#6,objectname=Process Working_Set=55005184 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#2,objectname=Process Working_Set=6389760 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#1,objectname=Process Working_Set=5763072 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#3,objectname=Process Working_Set=75374592 1529065235000000000
> win_proc,host=Desktop1,instance=chrome,objectname=Process Working_Set=81219584 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#8,objectname=Process Working_Set=17788928 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#7,objectname=Process Working_Set=34930688 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#5,objectname=Process Working_Set=19202048 1529065235000000000
> win_proc,host=Desktop1,instance=chrome#4,objectname=Process Working_Set=31436800 1529065235000000000
### Actual behavior:
C:\Program Files\InfluxData\Telegraf>telegraf.exe version
Telegraf v1.7.0 (git: release-1.7 f4d22dd4)

C:\Program Files\InfluxData\Telegraf>telegraf.exe --config .\telegraf_win_proc.conf --test
> win_proc,host=Desktop1,instance=chrome,objectname=Process Working_Set=17797120 1529065614000000000

### Additional info:
This is boring because this Bug was fixed with 1.7 rc1 . Take a look at -> https://github.com/influxdata/telegraf/issues/4233
After this there came a new feature for language support -> https://github.com/influxdata/telegraf/issues/4243

In Final Release 1.7.0 the language fix is present but the instance fix is not present :-1:

**Comment by danielnelson** [comment]
I believe this is the same as #4280, the `UseWildcardsExpansion = true` option was meant to address this, but has the localization side effect.  Let's discuss further on #4280.
