### ISSUE TITLE
snmp input ignored, no debug response, no parser error, not executed

### ISSUE THREAD

**Issue by uclnj** [influxdata/telegraf#4298]
### Relevant telegraf.conf:

```
[agent]
  interval = "15s"
  debug = true
  log = "test.log"
  [...]
[[outputs.influxdb]]
  urls = ["http://192.168.5.116:8086"]
  database = "telegraf"
  [...]

**** this one is just ignored
[[inputs.snmp]]
 agents = [ "192.168.5.34:161" ]
 timeout = "5s"
 retries = 3
 version = 2
 community = "public"
[[inputs.snmp.field]]
 name = "ds416-disk-temps"
 oid = "iso.3.6.1.4.1.6574.2.1.1.6"

**** this works just fine
[[inputs.snmp]]
 agents = [ "192.168.5.1:161" ]
 timeout = "5s"
 retries = 3
 version = 2
 community = "public"
[[inputs.snmp.field]]
 name = "wg-connections"
 oid = "iso.3.6.1.4.1.3097.6.3.80.0"
[[inputs.snmp.field]]
 name = "wg-apr"
 oid = "iso.3.6.1.4.1.3097.4.2.2.1.18.30"
[[inputs.snmp.field]]
 name = "wg-https-proxy"
 oid = "iso.3.6.1.4.1.3097.4.2.2.1.18.13"

```
### System info:

Ubuntu 16.04 on physical hardware, Telegraf v1.7.0 (f4d22dd4)

### Steps to reproduce:

1. telegraf --config synology.conf --test

### Expected behavior:

snmpwalk with that OID will return the temperature of the four drives in the Synology unit. I would expect telegraf to do the same.

root@grafana:/etc/telegraf/telegraf.d# snmpwalk -c public -v 2c 192.168.5.34 iso.3.6.1.4.1.6574.2.1.1.6
iso.3.6.1.4.1.6574.2.1.1.6.0 = INTEGER: 35
iso.3.6.1.4.1.6574.2.1.1.6.1 = INTEGER: 37
iso.3.6.1.4.1.6574.2.1.1.6.2 = INTEGER: 37
iso.3.6.1.4.1.6574.2.1.1.6.3 = INTEGER: 38

### Actual behavior:

Telegraf test returns the SNMP poll for the WG firewall listed in the config below the Synology poll.  There are no errors, parser problems listed nor any log indicating why Telegraf ignores this request.

root@grafana:/etc/telegraf/telegraf.d# telegraf --config synology.conf --test
> snmp,agent_host=192.168.5.1,host=grafana wg-connections=458i,wg-https-proxy=0i,wg-apr=82i 1529072564000000000

### Additional info:

the log file test.log is created but is 0 bytes.

**Comment by ybinnenwegin2ip** [comment]
I seem to be having the same issue.

I'm running Debian Jessie with Telegraf 1.7.0 with the following config file:
```
[global_tags]

[agent]
   interval = "10s"

[[outputs.influxdb]]

[[inputs.snmp]]
   agents = [ "IP_ADDRESS:161" ]
   version = 2

   community = "COMMUNITY"

   [[inputs.snmp.field]]
     name = "hostname"
     oid = "RFC1213-MIB::sysName.0"
     is_tag = true
```
And I run telegraf with this command:
```bash
telegraf --config ./telegraf.conf --test
```

I get 0 output from it.

An snmpget which does the same does give me output though:
```bash
USERNAME@HOSTNAME:~$ snmpget -c COMMUNITY -v2c HOSTNAME RFC1213-MIB::sysName.0
SNMPv2-MIB::sysName.0 = STRING: HOSTNAME
```

**Comment by danielnelson** [comment]
The top level field (not in a table) are most similar to this command:
```
snmpget -c public -v 2c 192.168.5.34 iso.3.6.1.4.1.6574.2.1.1.6
```

Try creating a table like:
```
[[inputs.snmp]]
# ... snip ...
[[inputs.snmp.table]]
 name = "wg-connections"
 oid = "iso.3.6.1.4.1.3097.6.3.80.0"
```

**Comment by danielnelson** [comment]
@uclnj Let me know if you need more help.
