### ISSUE TITLE
mysql input sets innodb_buffer_pool_pages_misc to nothing if it is negative

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#4299]
Hi,

I am using 5.7.12 MySQL Community Server and telegraf 1.7.0

Telegraf is setting innodb_buffer_pool_pages_misc to nothing resulting in invalid json.

> mysql> SELECT NAME, COUNT FROM information_schema.INNODB_METRICS WHERE status='enabled';
> +---------------------------------+--------------+
> | NAME                            | COUNT        |
> +---------------------------------+--------------+
> | lock_deadlocks                  |            0 |
> | lock_timeouts                   |            0 |
> | lock_row_lock_current_waits     |            0 |
> | lock_row_lock_time              |          569 |
> | lock_row_lock_time_max          |          102 |
> | lock_row_lock_waits             |          560 |
> | lock_row_lock_time_avg          |            1 |
> | buffer_pool_size                |   2147483648 |
> | buffer_pool_reads               |      6265978 |
> | buffer_pool_read_requests       | 186809535044 |
> | buffer_pool_write_requests      |    574475832 |
> | buffer_pool_wait_free           |            0 |
> | buffer_pool_read_ahead          |       520086 |
> | buffer_pool_read_ahead_evicted  |            0 |
> | buffer_pool_pages_total         |       131056 |
> | buffer_pool_pages_misc          |        -1016 |
> | buffer_pool_pages_data          |       123880 |
> | buffer_pool_bytes_data          |   1982291968 |
> | buffer_pool_pages_dirty         |            0 |
> | buffer_pool_bytes_dirty         |            0 |
> | buffer_pool_pages_free          |         8192 |
> | buffer_pages_created            |        66118 |
> | buffer_pages_written            |     49984806 |
> | buffer_pages_read               |      6825538 |
> | buffer_data_reads               |  91833971200 |
> | buffer_data_written             | 876120691712 |
> | os_data_reads                   |      6827853 |
> | os_data_writes                  |     54450501 |
> | os_data_fsyncs                  |      6379020 |
> | os_log_bytes_written            |   3101039104 |
> | os_log_fsyncs                   |      2928367 |
> | os_log_pending_fsyncs           |            0 |
> | os_log_pending_writes           |            0 |
> | trx_rseg_history_len            |         1568 |
> | log_waits                       |            0 |
> | log_write_requests              |      2580200 |
> | log_writes                      |      2219939 |
> | log_padded                      |    707682816 |
> | adaptive_hash_searches          |  60413048148 |
> | adaptive_hash_searches_btree    |   1566207860 |
> | file_num_open_files             |         2500 |
> | ibuf_merges_insert              |       126887 |
> | ibuf_merges_delete_mark         |         8236 |
> | ibuf_merges_delete              |         3728 |
> | ibuf_merges_discard_insert      |            0 |
> | ibuf_merges_discard_delete_mark |            0 |
> | ibuf_merges_discard_delete      |            0 |
> | ibuf_merges                     |        41619 |
> | ibuf_size                       |            1 |
> | innodb_activity_count           |     13829248 |
> | innodb_dblwr_writes             |      1519446 |
> | innodb_dblwr_pages_written      |      3317954 |
> | innodb_page_size                |        16384 |
> | innodb_rwlock_s_spin_waits      |            0 |
> | innodb_rwlock_x_spin_waits      |            0 |
> | innodb_rwlock_sx_spin_waits     |         1169 |
> | innodb_rwlock_s_spin_rounds     |      5029118 |
> | innodb_rwlock_x_spin_rounds     |      1683661 |
> | innodb_rwlock_sx_spin_rounds    |        21698 |
> | innodb_rwlock_s_os_waits        |       893190 |
> | innodb_rwlock_x_os_waits        |       133346 |
> | innodb_rwlock_sx_os_waits       |          404 |
> | dml_inserts                     |    292240821 |
> | dml_deletes                     |       143479 |
> | dml_updates                     |       598040 |
> +---------------------------------+--------------+
> 65 rows in set (0.00 sec)
>

**Comment by danielnelson** [comment]
Thanks for the bug report, could you also run this command an add the output?
```
./telegraf --input-filter mysql --test
```

**Comment by arindamchoudhury** [comment]
It's random, i will try.

**Comment by glinton** [comment]
@arindamchoudhury are you using [compressed tables](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_compressed_table)? It seems you may be affected by [this bug](https://bugs.mysql.com/bug.php?id=59550) (which has a [duplicate](https://bugs.mysql.com/bug.php?id=72423).) I still have yet to reproduce a negative value for `buffer_pool_pages_misc`, do you have any way to reliably do so?

Also, regarding the invalid json, what are you using to parse it? Can you paste the `--test` output as well as the json data your python app is getting as input, please?

**Comment by arindamchoudhury** [comment]
this problem occurs randomly. I will try to give you requested data.

**Comment by arindamchoudhury** [comment]
this might be issue from python ujson library also.
