### ISSUE TITLE
Intermittent unittest failure in win_perf_counters

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4301]
We have been getting an intermittent unittest failure in the win_perf_counters tests after the recent changes.

### System info:

master 7781507c01dcb7fe2dd2ed14d58235d3b219afba

### Steps to reproduce:

1. On windows: `go test ./plugins/inputs/win_perf_counters/...`

### Expected behavior:

```
go test ./plugins/inputs/win_perf_counters/...
ok  	github.com/influxdata/telegraf/plugins/inputs/win_perf_counters	0.174s
```

### Actual behavior:

```
go test ./plugins/inputs/win_perf_counters/...
--- FAIL: TestWinPerformanceQueryImpl (2.27s)
	Error Trace:	win_perf_counters_integration_test.go:101
	Error:      	Received unexpected error:
	            	The returned data is not valid.
	Test:       	TestWinPerformanceQueryImpl
2018/06/15 10:38:02 Invalid counterPath: '\Processor InformationERROR(_Total)\% Processor Time'. Error: The specified object was not found on the computer.
2018/06/15 10:38:02 Invalid counterPath: '\Processor Information(_Total)\% Processor TimeERROR'. Error: The specified counter could not be found.
2018/06/15 10:38:09 Invalid counterPath: '\O(I1)\C1'. Error: AddEnglishCounterToQuery: invalid counter path: \O(I1)\C1
2018/06/15 10:38:09 Invalid counterPath: '\O(I1)\C1'. Error: AddEnglishCounterToQuery: invalid counter path: \O(I1)\C1
```

### Additional info:

https://ci.appveyor.com/project/influx/telegraf/build/3013

**Comment by danielnelson** [comment]
@vlastahajek Could you take a look?

**Comment by vlastahajek** [comment]
I've already fixed this as a part of PR #4267. Are going to merge it? 
(Current failures are no caused by my code. How to re-run the tests, without new commit? )

Or, do you want to create a separate PR with the test fix?

**Comment by danielnelson** [comment]
Fix this in that PR will be fine, no way to re-run tests without a commit unfortunately.  In a pinch you should be able to `git commit --allow-empty` though.

**Comment by danielnelson** [comment]
I'm hijacking this issue for another intermittent issue (previous issue seems to be fixed):
```
 go test -short ./plugins/inputs/procstat/...
[3744]
--- FAIL: TestGather_RealFullPattern (5.02s)
	require.go:794: 
			Error Trace:	native_finder_windows_test.go:26
			Error:      	Received unexpected error:
			            	could not get win32Proc: context deadline exceeded
			Test:       	TestGather_RealFullPattern
[2280 2556 2116 1816 3328 844 3424 3744]
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/procstat	11.862s
make: *** [test-windows] Error 1
```

@vlastahajek Do you have time to look at this?

**Comment by vlastahajek** [comment]
@danielnelson, I'm busy with sth else,  I can look at this in ~ 2 weeks

**Comment by vlastahajek** [comment]
Sorry for getting to this so late.
It looks it's already fixed, it works for me.
