### ISSUE TITLE
add an input plugin for collect meminfo data 

### ISSUE THREAD

**Issue by shrug42** [influxdata/telegraf#4305]
## Feature Request

Opening a feature request kicks off a discussion.
A plugin to parse /proc/meminfo and collect the data.
for the data collected, see https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-proc-meminfo.html

### Proposal:
PR https://github.com/influxdata/telegraf/pull/4304

### Current behavior:
new feature

**Comment by shrug42** [comment]
Let me know if you like it and if you have any question. I would be happy to help.

**Comment by phemmer** [comment]
Dup of #1990

**Comment by danielnelson** [comment]
Thanks for the heads up @phemmer, I'm reading through the comments over there now, do you still feel we should include the new values in a separate plugin instead of merging it into mem?

**Comment by phemmer** [comment]
Been so long, I had to re-read my arguments for that :-)
I think the argument still makes sense. But the argument is mostly about the confusion regarding field naming. If we can come up with names that are unambiguous, and aren't os-specific, then I don't see any reason not to.

**Comment by shrug42** [comment]
I used Centos doc to add the fields to gopsutils: https://www.centos.org/docs/5/html/5.1/Deployment_Guide/s2-proc-meminfo.html

Most of those fields were necessary for us to review our memory usage, so I went ahead and added them all.

I can get you a PR with the new fields snake_cased added in the memory plugin, if that suits you. I am working on it now

**Comment by shrug42** [comment]
please take a look at https://github.com/influxdata/telegraf/pull/4546.
