### ISSUE TITLE
mysql input plugin sets fields value to nothing if the value is =~ 18446744073709551615

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#4310]
Hi, 
MySQL input plugin sets field value to nothing if the value is 18446744073709551615 which results in an invalid json.

This happen in the mysql_variables measurement. 

for example, this is the output of one using --test,

mysql_variables,host=xxxxxxxxxx,innodb_version=5.6.32-78.1,server=127.0.0.1:3306 max_digest_length=1024,max_error_count=64,max_heap_table_size=33554432,max_insert_delayed_threads=20,max_join_size=18446744073709552000,max_length_for_sort_data=1024,max_prepared_stmt_count=16382,max_relay_log_size=0,max_seeks_for_key=18446744073709552000,max_slowlog_files=0,max_slowlog_size=0,max_sort_length=1024,max_sp_recursion_depth=0,max_statement_time=0,max_tmp_tables=32,max_user_connections=0,max_write_lock_count=18446744073709552000,metadata_locks_cache_size=1024,metadata_locks_hash_instances=8,min_examined_row_limit=0 1529333944000000000

I use a python client to forward it to influxdb. The python client complains that it received an invalid josn.

mysql> SHOW GLOBAL VARIABLES;
| max_join_size                                               | 18446744073709551615
| max_seeks_for_key                                      | 18446744073709551615

**Comment by glinton** [comment]
Thanks for another but report, can you also run this command and add the output?
```
./telegraf --input-filter mysql --test
```

Or add `--test` to whatever you are using to run telegraf, thanks!

**Comment by arindamchoudhury** [comment]
I have already given you a snippet.  It's a production server so It's a little complicated to give the full output.

**Comment by glinton** [comment]
Ok, thanks. I wonder if it's the way your python app is parsing the json. I am unable to replicate the behavior so far.

```py
import json

data = '{"fields":{"max_error_count":64,"max_execution_time":0,"max_heap_table_size":16777216,"max_insert_delayed_threads":20,"max_join_size":18446744073709552000,"max_length_for_sort_data":1024,"max_points_in_geometry":65536,"max_prepared_stmt_count":16382,"max_relay_log_size":0,"max_seeks_for_key":18446744073709552000,"max_sort_length":1024,"max_sp_recursion_depth":0,"max_tmp_tables":32,"max_user_connections":0,"max_write_lock_count":18446744073709552000,"metadata_locks_cache_size":1024,"metadata_locks_hash_instances":8,"min_examined_row_limit":0,"multi_range_count":256,"myisam_data_pointer_size":6},"name":"mysql_variables","tags":{"host":"3549010a79d2","innodb_version":"5.7.22","server":"mysql:3306"},"timestamp":1529535150}'

print json.loads(data)["fields"]["max_join_size"]
print json.dumps(data, sort_keys=True)
```
```
18446744073709552000
"{\"fields\":{\"max_error_count\":64,\"max_execution_time\":0,\"max_heap_table_size\":16777216,\"max_insert_delayed_threads\":20,\"max_join_size\":18446744073709552000,\"max_length_for_sort_data\":1024,\"max_points_in_geometry\":65536,\"max_prepared_stmt_count\":16382,\"max_relay_log_size\":0,\"max_seeks_for_key\":18446744073709552000,\"max_sort_length\":1024,\"max_sp_recursion_depth\":0,\"max_tmp_tables\":32,\"max_user_connections\":0,\"max_write_lock_count\":18446744073709552000,\"metadata_locks_cache_size\":1024,\"metadata_locks_hash_instances\":8,\"min_examined_row_limit\":0,\"multi_range_count\":256,\"myisam_data_pointer_size\":6},\"name\":\"mysql_variables\",\"tags\":{\"host\":\"3549010a79d2\",\"innodb_version\":\"5.7.22\",\"server\":\"mysql:3306\"},\"timestamp\":1529535150}"
```

**Comment by arindamchoudhury** [comment]
The json my python app is getting is like this:

```
{
		"fields": {
			"max_slowlog_files": 0,
			"max_relay_log_size": 0,
			"max_slowlog_size": 0,
			"max_sp_recursion_depth": 0,
			"max_heap_table_size": 33554432,
			"metadata_locks_cache_size": 1024,
			"max_write_lock_count": ,
			"max_tmp_tables": 32,
			"max_error_count": 64,
			"metadata_locks_hash_instances": 8,
			"max_prepared_stmt_count": 16382,
			"max_insert_delayed_threads": 20,
			"max_join_size": ,
			"max_user_connections": 0,
			"max_length_for_sort_data": 1024,
			"max_digest_length": 1024,
			"min_examined_row_limit": 0,
			"max_seeks_for_key": ,
			"max_statement_time": 0,
			"max_sort_length": 1024
		},
		"name": "mysql_variables",
		"timestamp": "2018-06-26T09:53:45+02:00",
		"tags": {
			"innodb_version": "5.6.32-78.1",
			"server": "127.0.0.1:3306"
		}
	},
```
max_write_lock_count has no value

**Comment by glinton** [comment]
Do you mind sharing how you gathered that json? I'm very curious as I have yet to see golang marshal json into a key with no value. (I've seen `0`, `""`, or no key if there is no value) I'd love to learn if it is something golang is doing or if something between what telegraf outputs and what your python app consumes is dropping the value. Thanks.

**Comment by arindamchoudhury** [comment]
I am really sory @glinton, it was a fault on my side. I was using ujson and it's the source of the problem.

**Comment by glinton** [comment]
No worries, I'm glad you were able to get it resolved :tada:
