### ISSUE TITLE
Concurrent requests with differing precision can result in incorrect timestamp in http_listener

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4316]
### Relevant telegraf.conf:
```toml
[[inputs.http_listener]]
```

### System info:

Telegraf 1.6

### Steps to reproduce:

1. Send line protocol with different precision values to http_listener concurrently.

### Expected behavior:

Input parsed correctly

### Actual behavior:

Timestamps are sometimes parsed with incorrect negative timestamps

**Comment by szibis** [comment]
Is there any timeline for that?

**Comment by danielnelson** [comment]
I will have a fix in for 1.7.1.
