### ISSUE TITLE
Support StatisticValues in Cloudwatch output plugin

### ISSUE THREAD

**Issue by david7482** [influxdata/telegraf#4318]
## Feature Request
Cloudwatch MericDatum has the StatisticValues field. We could utilize it with basicstats aggregator results so that we don't need to send raw metrics which could improve efficiency and save API cost.

### Proposal:
Cloudwatch output plugin could parse the field names from basicstats aggregator. If it found all required fields are available(min, max, sum, mean, count), it would use StatisticValues field to send this metric instead of sending them as separated values.

### Current behavior:
Cloudwatch output plugin does not use the StatisticValues field. It would send every field as separated cloudwatch.MericDatum. 

### Desired behavior:
Cloudwatch output plugin could utilize StatisticValues field if all required fields are available.

### Use case: [Why is this important (helps with prioritizing requests)]
If we have lots of matrics, it is much more efficient and also saves API cost.

**Comment by danielnelson** [comment]
Sounds good, is this something you could work on @david7482?
