### ISSUE TITLE
snmp bulk walk 

### ISSUE THREAD

**Issue by bajojoba** [influxdata/telegraf#4319]
### Relevant telegraf.conf:
```
[[inputs.snmp]]
  interval = "300s"
  agents = [ "10.111.111.2:161" ]
  version = 2
  community = "public"
  name = "cmts"

 [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.bluk]]
    name = "cmts"
    max_repetition = 127
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "ifAlias"
      oid = "IF-MIB::ifAlias"
      is_tag = true
```
### System info:

Centos 6.9, Telegraf v1.7.0

### Steps to reproduce:

1. telegraf --test --config cmts.conf
2018/06/19 12:50:37 E! Error parsing cmts.conf, line 13: field corresponding to `bluk' is not defined in `*snmp.Snmp'

### Expected behavior:
I would like to use snmpbulkwalk as there are too many interfaces on the CMTS and snmpwalk is inefficient and much slower. 

### Actual behavior:
Don't know how to enable bulk and if it actualy exsits? There is no information regarding this on: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp

Thanks.

**Comment by glinton** [comment]
Thanks for the report. Have you tried using `inputs.snmp.bulk` (as opposed to `bluk`)?

**Comment by danielnelson** [comment]
Should actually be `inputs.snmp.table` to use bulkwalk.  You will also need to remove `max_repetition` from the this section since this is only a valid option on `inputs.snmp`:
```
[[inputs.snmp]]
  interval = "300s"
  agents = [ "10.111.111.2:161" ]
  version = 2
  community = "public"
  name = "cmts"

 [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

 [[inputs.snmp.table]]
   name = "cmts"
   inherit_tags = [ "hostname" ]
   oid = "IF-MIB::ifXTable"

   [[inputs.snmp.table.field]]
     name = "ifName"
     oid = "IF-MIB::ifName"
     is_tag = true

   [[inputs.snmp.table.field]]
     name = "ifAlias"
     oid = "IF-MIB::ifAlias"
     is_tag = true
```

**Comment by bajojoba** [comment]
Thanks Danilel for the info, I didn't know that.
