### ISSUE TITLE
Be able to rename measurements with a kind of regexp on output plugins

### ISSUE THREAD

**Issue by thefab** [influxdata/telegraf#4325]
### Proposal:

Be able to rename measurements with a kind of regexp on output plugins (see use case at the end).

### Current behavior:

We can't rename measurements after an aggregator plugin. (Or we didn't succeed) 

### Desired behavior:

Be able to rename measurements with a kind of regexp on output plugins (see use case at the end).

### Use case: 

We use several aggregators with different periods for the same original measurements.

Example: 
```
[[aggregators.basicstats]]
  period = "10s"
  drop_original = true
  stats = ["min","max","mean","sum"]
  name_prefix = "fullres_"

[[aggregators.basicstats]]
  period = "60s"
  drop_original = true
  stats = ["min","max","mean","sum"]
  name_prefix = "medres_"
```

We want to route each aggregator result to a different output plugins.

We tried with tags but we got a kind of measurement collisions. So we added a "name_prefix" to clearly identify the aggregator source.

In output configuration, we use a "namepass" to filter measurements depending on the aggregator source. For example:

```
[[outputs.influxdb]]
  urls = ["http://server1"]
  database = "metrics"
  skip_database_creation = true
  namepass = ["medres_*"]

[[outputs.influxdb]]
  urls = ["http://server2"]
  database = "metrics"
  skip_database_creation = true
  namepass = ["fullres_*"]
```

It works :-) But we have this ugly routing "name_prefix" before each measurement name :-(

We are new to telegraf. Sorry if we missed something.

**Comment by danielnelson** [comment]
My instinct is to use tags for the routing, can you tell us a little bit more about the problem you ran into using them?

**Comment by thefab** [comment]
I'm terribly sorry but... it seems to work with tags !

I don't understand why it didn't work during our preliminary tests :-(

This issue can be closed. Sorry for noise.
