### ISSUE TITLE
Output plugin for Google Stackdriver

### ISSUE THREAD

**Issue by adrianlop** [influxdata/telegraf#4328]
### Feature request - Output plugin for Google Stackdriver

Same as the [output plugin for AWS Cloudwatch](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/cloudwatch), it would be nice to be able to send metrics to GCP Stackdriver, for those who are using Google Cloud.

**Comment by glinton** [comment]
Good idea. Some helpful resources for anyone who'd like to give it a shot:
 - [google cloud client library](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-go)
 - [go docs for client](https://godoc.org/cloud.google.com/go/logging)

**Comment by danielnelson** [comment]
We have this in progress: https://github.com/influxdata/telegraf/pull/3876

**Comment by adrianlop** [comment]
awesome, thanks guys

**Comment by russorat** [comment]
closed in #3876
