### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#4336]
Hi,

I have a dockerized  telegraf which is very high on cpu usage:

![screenshot from 2018-06-22 17-38-00](https://user-images.githubusercontent.com/1412069/41785735-cbb9b6de-7643-11e8-82e5-0ddf1ae6b8b4.png)

I am using go 1.10.3 and telegraf 1.7.0

Loaded inputs: inputs.disk inputs.kernel inputs.system inputs.processes inputs.net inputs.linux_sysctl_fs inputs.cpu inputs.conntrack inputs.diskio inputs.mem inputs.swap inputs.netstat inputs.http_listener inputs.influxdb inputs.mongodb inputs.redis inputs.docker inputs.postgresql

I enabled pprof:

go tool pprof http://localhost:6060/debug/pprof/profile?seconds=180

> (pprof) top50 -cum
> Showing nodes accounting for 1.61s, 30.04% of 5.36s total
> Dropped 199 nodes (cum <= 0.03s)
> Showing top 50 nodes out of 244
>       flat  flat%   sum%        cum   cum%
>          0     0%     0%      1.72s 32.09%  github.com/influxdata/telegraf/plugins/inputs/influxdb.(*InfluxDB).Gather.func1
>      0.01s  0.19%  0.19%      1.72s 32.09%  github.com/influxdata/telegraf/plugins/inputs/influxdb.(*InfluxDB).gatherURL
>      0.01s  0.19%  0.37%      1.35s 25.19%  encoding/json.(*Decoder).Decode
>          0     0%  0.37%      1.32s 24.63%  github.com/influxdata/telegraf/agent.gatherWithTimeout.func1
>          0     0%  0.37%      1.17s 21.83%  github.com/influxdata/telegraf/plugins/inputs/system.(*NetStats).Gather
>          0     0%  0.37%      1.17s 21.83%  github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).NetConnections
>          0     0%  0.37%      1.17s 21.83%  github.com/shirou/gopsutil/net.Connections
>          0     0%  0.37%      1.17s 21.83%  github.com/shirou/gopsutil/net.ConnectionsPid
>          0     0%  0.37%      1.17s 21.83%  github.com/shirou/gopsutil/net.ConnectionsPidWithContext
>          0     0%  0.37%      1.17s 21.83%  github.com/shirou/gopsutil/net.ConnectionsWithContext
>          0     0%  0.37%      1.14s 21.27%  github.com/influxdata/telegraf/agent.(*Agent).flush.func1
>          0     0%  0.37%      1.14s 21.27%  github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write
>          0     0%  0.37%      1.14s 21.27%  github.com/influxdata/telegraf/internal/models.(*RunningOutput).write
>          0     0%  0.37%      1.14s 21.27%  github.com/influxdata/telegraf/plugins/outputs/ecmanaged.(*Ecmanaged).Write
>      0.01s  0.19%  0.56%      1.08s 20.15%  encoding/json.(*decodeState).unmarshal
>          0     0%  0.56%      1.06s 19.78%  encoding/json.(*decodeState).value
>      0.07s  1.31%  1.87%      1.03s 19.22%  encoding/json.(*decodeState).object
>          0     0%  1.87%      0.96s 17.91%  encoding/json.(*arrayEncoder).(encoding/json.encode)-fm
>          0     0%  1.87%      0.96s 17.91%  encoding/json.(*arrayEncoder).encode
>          0     0%  1.87%      0.96s 17.91%  encoding/json.(*encodeState).marshal
>      0.01s  0.19%  2.05%      0.96s 17.91%  encoding/json.(*encodeState).reflectValue
>          0     0%  2.05%      0.96s 17.91%  encoding/json.(*mapEncoder).(encoding/json.encode)-fm
>      0.06s  1.12%  3.17%      0.96s 17.91%  encoding/json.(*mapEncoder).encode
>          0     0%  3.17%      0.96s 17.91%  encoding/json.(*sliceEncoder).(encoding/json.encode)-fm
>          0     0%  3.17%      0.96s 17.91%  encoding/json.(*sliceEncoder).encode
>          0     0%  3.17%      0.96s 17.91%  encoding/json.Marshal
>      0.01s  0.19%  3.36%      0.78s 14.55%  encoding/json.interfaceEncoder
>      0.37s  6.90% 10.26%      0.72s 13.43%  runtime.mallocgc
>          0     0% 10.26%      0.60s 11.19%  github.com/shirou/gopsutil/net.statsFromInodes
>      0.57s 10.63% 20.90%      0.59s 11.01%  syscall.Syscall6
>          0     0% 20.90%      0.57s 10.63%  github.com/shirou/gopsutil/net.getProcInodes
>          0     0% 20.90%      0.57s 10.63%  github.com/shirou/gopsutil/net.getProcInodesAll
>          0     0% 20.90%      0.53s  9.89%  runtime.systemstack
>          0     0% 20.90%      0.51s  9.51%  io/ioutil.ReadFile
>          0     0% 20.90%      0.48s  8.96%  runtime.mcall
>      0.01s  0.19% 21.08%      0.47s  8.77%  runtime.schedule
>      0.46s  8.58% 29.66%      0.47s  8.77%  syscall.Syscall
>          0     0% 29.66%      0.46s  8.58%  runtime.park_m
>          0     0% 29.66%      0.38s  7.09%  github.com/influxdata/telegraf/agent.(*accumulator).AddFields
>      0.01s  0.19% 29.85%      0.38s  7.09%  runtime.findrunnable
>          0     0% 29.85%      0.34s  6.34%  os.Open
>          0     0% 29.85%      0.34s  6.34%  os.OpenFile
>          0     0% 29.85%      0.34s  6.34%  os.openFileNolog
>      0.01s  0.19% 30.04%      0.33s  6.16%  os.Readlink
>          0     0% 30.04%      0.32s  5.97%  internal/poll.(*FD).Read
>          0     0% 30.04%      0.32s  5.97%  syscall.Read
>          0     0% 30.04%      0.32s  5.97%  syscall.Readlink
>          0     0% 30.04%      0.32s  5.97%  syscall.read
>          0     0% 30.04%      0.32s  5.97%  syscall.readlinkat
>          0     0% 30.04%      0.31s  5.78%  github.com/shirou/gopsutil/net.(*process).fillFromStatus
> 
>

**Comment by glinton** [comment]
What CPU resources are available to the container? In order to understand how CPU hungry it is for you, we'll need to have the container's CPU cap/limit.

**Comment by arindamchoudhury** [comment]
```
# docker inspect ecmanaged-agent
[
    {
        "Id": "ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0",
        "Created": "2018-06-28T11:39:14.763033253Z",
        "Path": "/root/entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 23101,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-06-28T11:39:14.994384381Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:f6974c98d3580735018fdc77c4ace9693ff9eadf8342138b557fe81571819e1d",
        "ResolvConfPath": "/var/lib/docker/containers/ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0/hostname",
        "HostsPath": "/var/lib/docker/containers/ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0/hosts",
        "LogPath": "/var/lib/docker/containers/ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0/ec217adbc61c3804954c0a1690e3edf4ea5551aa12613ad000109542fb3415e0-json.log",
        "Name": "/ecmanaged-agent",
        "RestartCount": 0,
        "Driver": "aufs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "9115050a5413a805b2af12f6fdfdbf18756d66eba440ed689e860330aeb8bccc"
        ],
        "HostConfig": {
            "Binds": [
                "/var/run/utmp:/var/run/utmp:ro",
                "/var/run/docker.sock:/var/run/docker.sock:ro",
                "/:/rootfs:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/",
                "Destination": "/rootfs",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rslave"
            },
            {
                "Type": "bind",
                "Source": "/var/run/utmp",
                "Destination": "/var/run/utmp",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "monitor-influxdb1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CONFIG=[[inputs.mongodb]]\n    servers = [\"mongodb://telegraf:iNte2rh6Oh6OrR2VqxhF2dAsqTh7fRrvDqxhF@127.0.0.1:27017\"]\n    gather_perdb_stats = false\n[[inputs.redis]]\n    servers = [\"tcp://localhost:6379\"]\n[[inputs.docker]]\n    endpoint = \"unix:///var/run/docker.sock\"\n[[inputs.postgresql]]\n    address = \"postgres://alerta:iNte2kAPiNte2rh6OrR2VqxhF2dTAsqTh7fRrvDqxhF@localhost:5432/alerta\"\n[[inputs.influxdb]]\n    urls = [\"http://localhost:8086/debug/vars\"]\n    timeout = \"15s\"\n",
                "API_KEY=61df9767b003e5ef78106e6e75831d29fa998678d3779654abf59c6a428f35b3",
                "HOST_PROC=/rootfs/proc",
                "ENV=prod",
                "TAGS={\"role\": \"influxdb\"}",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "INTERVAL=30s",
                "TIMEOUT=5s",
                "ADMIN_API=https://api.ecmanaged.com/v2",
                "API_COLLECTOR=https://metrics.ecmanaged.com/v1/telegraf"
            ],
            "Cmd": [
                "/root/entrypoint.sh"
            ],
            "ArgsEscaped": true,
            "Image": "ackstorm/ecmanaged-agent:latest",
            "Volumes": {
                "/rootfs": {},
                "/var/run/docker.sock": {},
                "/var/run/utmp": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "7f0b666b4febef5cd44bef80d8a3ef877eb66f3de123e533dcbc036636e61eb2",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "init",
                "com.docker.compose.service": "ecmanaged-agent",
                "com.docker.compose.version": "1.16.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c442f8ac926bb0392eb3ab6513a90e17119828d507e67d67387f81848e36c2e9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6db67d38ea0e97666e28d701d9e5897388b764430e5d2e9a5b2c0423057839f4",
                    "EndpointID": "9de45ab0a7ffa9eb47f2714e35e9de02e5069353bc0f5ed82d0293e4e949d9a8",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

**Comment by danielnelson** [comment]
I have seen some instances where the response body from InfluxDB `/debug/vars` is very large.  Can you check the size using commands similar to these:
```
curl http://localhost:8086/debug/vars -o output.txt
ls -lh output.txt
```

**Comment by danielnelson** [comment]
This could also potentially be caused by https://github.com/influxdata/telegraf/issues/4316.  If you are sometimes using the `precision` query parameter when sending to http_listener it could be creating shards for old timestamps, you can workaround this by always using the same precision.

**Comment by arindamchoudhury** [comment]
# curl http://localhost:8086/debug/vars -o output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3303k    0 3303k    0     0  4738k      0 --:--:-- --:--:-- --:--:-- 4733k

# ls -lh output.txt
-rw-r--r-- 1 root root 3.3M Jul  2 07:53 output.txt

**Comment by danielnelson** [comment]
That is on the larger side but not it's not way out of the ordinary for a larger server.  I notice that some other plugins that are usually not very expensive are also listed fairly high, and I don't think anything is out of the ordinary.  If you wish to lower the cpu usage without adding more resources, the easiest way is to reduce the interval for plugins that are high on this profiling list.
