### ISSUE TITLE
create table for every metric when using cratedb output

### ISSUE THREAD

**Issue by seanlook** [influxdata/telegraf#4340]
Now the output plugin `cratedb` create only one table `metrics` for all metrics reported.

create table for every metric seems more reasonable:
1. sometimes, I need join the two metric tables to show results. that's impossible in one table
2. reduce the record amount of the table
3. maybe I have different table definitions for different metric

**Comment by glinton** [comment]
I believe you can accomplish that with telegraf's [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering). You may or may not need to manually create each table, but that should the filtering should help accomplish your goal.

**Comment by sspaink** [comment]
Closing as this seems to be solvable with filtering.
