### ISSUE TITLE
Support OpenTSDB pre aggregated values

### ISSUE THREAD

**Issue by seanlook** [influxdata/telegraf#4341]
Now aggregator plugin `basicstats` is more like downsampling across time for **a single timeseries**. But sometimes we need to pre-aggregate to group by some of tags within a specific time or a range time. 

refer: http://opentsdb.net/docs/build/html/api_http/rollup.html

**Comment by glinton** [comment]
Is your use case to dump the `basicstats` output to TSDB's `/api/rollup`, or are you saying you'd like to see the "rollup" behavior mimicked?

**Comment by seanlook** [comment]
I mean data is rolled up in telegraf, and sent using normal `/api/put`. (OpenTSDB is not good at it, see [rolled-up-pre-aggregates](http://opentsdb.net/docs/build/html/user_guide/rollups.html#rolled-up-pre-aggregates)). Besides, many plugins do not use `/api/rollup` to save data

The ① is what `basicstas` does. The ② is what I mean:
![tim 20180705115841](https://user-images.githubusercontent.com/9251710/42301960-ce707dfc-804a-11e8-8945-a64dbfb3f279.png)

**Comment by danielnelson** [comment]
If I'm understanding correctly, we need to keep more metadata about the created aggregates internally, somewhat similar to what was discussed in https://github.com/influxdata/telegraf/issues/3670, and then the opentsdb output could use the `/api/rollup` endpoint for sending the aggregate data.

**Comment by danielnelson** [comment]
Currently the opentsdb output uses only the `/api/put` endpoint.

**Comment by glinton** [comment]
@seanlook, does #4347 provide what you need?
