### ISSUE TITLE
Wavefront output to support TLS

### ISSUE THREAD

**Issue by ayashjorden** [influxdata/telegraf#4346]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
As with any component transmitting data over the network, sometimes (most of the time) one would like to have a secure channel to use for that purpose.  
Also, TLS provides mutual-authentication with optional authorization.

### Current behavior:
No TLS config is available in the Wavefront output plugin. 
### Desired behavior:
Have the ability to configure TLS crt/key/CA to use
### Use case: [Why is this important (helps with prioritizing requests)]
In out environment, we have a standard of TLS1.2 for *all* components (Vault, ETCd, Cassandra, k8s).
WF shouldn't be different. even if we're running inside a "secure" location.

Thank you in advance,
Jorden

**Comment by ayashjorden** [comment]
It was brought to my knowledge that Telegraf (and many other collectors/shippers) don't keep and open connection with the output target.

Telegraf will open a new connection every `interval`/`flush_interval` and negotiate to get a secure connection.

I'll quote one of my colleagues:
```
Telegraf doesn’t stream.  Telegraf collects on an interval… and flushes metrics on another one as well.  During a flush is when we open a connection to Wavefront Proxy, send the metrics and close.  Our defaults are to set those intervals to 60s long.  If you look at your telegraf config, you will find `interval` and `flust_interval` properties which control that frequency
```

Just adding some, hopefully useful, information.
Yarden

**Comment by danielnelson** [comment]
This was briefly discussed when we added the Wavefront output https://github.com/influxdata/telegraf/pull/3160#discussion_r139573887.  If needed and when the Wavefront proxy is ready it could be changed to maintain a persistent connection between writes.

**Comment by ayashjorden** [comment]
I'll relay to my WF colleagues

Yarden

**Comment by puckpuck** [comment]
Wavefront proxy does not support TLS connections for incoming Wavefront data format.  Support needs to be there before it can be in Telegraf.

As for persistent connection, the plan is to roll that when the proxy supports http.  That still isn't out yet, but it is very soon.

**Comment by danielnelson** [comment]
Closing, we can reopen when this support is added to Wavefront.
