### ISSUE TITLE
inputs.snmp: Not check for match of quotes

### ISSUE THREAD

**Issue by denji** [influxdata/telegraf#4359]
`plugins/inputs/snmp` can refuse to parse the config and just stop its work on the input. There will be no errors, `inputs.snmp` will behave like an empty section.

**Tested on versions**: 1.5.3 - 1.7.0
The problem occurs because the number of quotes is not checked:

```diff
-    [inputs.snmp.tagpass]
+    [[inputs.snmp.tagpass]]
```

### An example of a config that will stop working:

```yaml
[[inputs.snmp]]
  # ...
  [[inputs.snmp.field]]
    # ...
  [[inputs.snmp.table]]
    # ...
    [inputs.snmp.tagpass] # ignore section [[inputs.snmp]]
      # ...
    [[inputs.snmp.table.field]]
      # ...
    [[inputs.snmp.table.field]]
      # ...
```

**Comment by danielnelson** [comment]
I don't completely follow, but I think this would be a valid config.  Tagpass should always be a non-array table like: `[inputs.snmp.tagpass]` but the bigger issue is that since you have tagpass in the middle of `[[inputs.snmp.table]]` and `[[inputs.snmp.table.field]]`, I believe the field gets it a new empty table implicitly as if you wrote:
```
[[inputs.snmp]]
  # ...
  [[inputs.snmp.field]]
    # ...
  [[inputs.snmp.table]]
    # ... this table has no field sub tables
    [inputs.snmp.tagpass]
      # ...
  [[inputs.snmp.table]]
    [[inputs.snmp.table.field]]
      # ...
```

**Comment by denji** [comment]
@danielnelson This only works on Telegraf-v1.2.1 https://github.com/Juniper/open-nti/blob/master/plugins/input-snmp/templates/telegraf.tmpl#L38
On versions v1.5.3 - v1.7.0 it behaves as a missing section `inputs.snmp`. Any idea how this could be solved differently?

**Comment by denji** [comment]
I understand the above version v1.3+, require an exact string match or regexp `["[g|x]e-*","ae*"]`?
Telegraf v1.2.1, the correspondence `["[g|x]e -","ae"]` as a substring worked.

**Comment by danielnelson** [comment]
Make sure to move tagpass to the bottom too:
```
[[inputs.snmp]]
  # ...
  [[inputs.snmp.field]]
    name = "hostname"
    # ...
  [[inputs.snmp.field]]
    name = "uptime"
    # ...
  [[inputs.snmp.field]]
    name = "sysObjectID"
    # ...
  [[inputs.snmp.table]]
    name = "interface_statistics"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = ".1.3.6.1.2.1.31.1.1.1.1"
      is_tag = true

  [inputs.snmp.tagpass]
    ifName = [ "[g|x]e-*", "ae*" ]
```

Tagpass actually uses a type of glob pattern, they are more fully documented
here: https://github.com/gobwas/glob#syntax
