### ISSUE TITLE
Bad link to "Hadoop-HDFS" example configuration

### ISSUE THREAD

**Issue by stevebang** [influxdata/telegraf#4361]
In the Jolokia2 README, the "Hadoop-HDFS" link in the [Example Configurations](https://github.com/influxdata/telegraf/tree/release-1.7/plugins/inputs/jolokia2#example-configurations) is the following correct link address:

https://github.com/influxdata/telegraf/blob/release-1.7/plugins/inputs/jolokia2/examples/hadoop-hdfs.conf
 
The file name has an extra "o" in it:

https://github.com/influxdata/telegraf/blob/release-1.7/plugins/inputs/jolokia2/examples/hadooop-hdfs.conf

**Comment by danielnelson** [comment]
Thanks, fixed in 8bf18d6ac7043e84805047f313724279fe665ee9 and ported to 1.7 branch
