### ISSUE TITLE
Add Graphite Tag parsing support on the input side

### ISSUE THREAD

**Issue by gena01** [influxdata/telegraf#4372]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Please add graphite tag parsing support for incoming graphite data.

This is a followup on #3830 
### Current behavior:

Currently the tags won't be parsed/stripped properly.

### Desired behavior:

Parse and extract tags from graphite input stream.

### Use case: [Why is this important (helps with prioritizing requests)]

Since some support is already in telegraf where we can generate the proper graphite format on the output side it would be nice to be able to parse the same format on the input side.

**Comment by endersonmaia** [comment]
How much for this functionality ?

**Support Graphite Line Protocol at Input/Parser**

`my.series;tag1=value1;tag2=value2 <value> <timestamp>\n`

See: 

- https://github.com/influxdata/telegraf/tree/master/plugins/parsers/graphite
- https://graphite.readthedocs.io/en/stable/tags.html

> Tag names must have a length >= 1 and may contain any ascii characters except ;!^=. Tag values must also have a length >= 1, they may contain any ascii characters except ; and the first character must not be ~. UTF-8 characters may work for names and values, but they are not well tested and it is not recommended to use non-ascii characters in metric names or tags. Metric names get indexed under the special tag name, if a metric name starts with one or multiple ~ they simply get removed from the derived tag value because the ~ character is not allowed to be in the first position of the tag value. If a metric name consists of no other characters than ~, then it is considered invalid and may get dropped.

**Comment by endersonmaia** [comment]
There's a PR for that https://github.com/influxdata/telegraf/pull/8564

**Comment by ssoroka** [comment]
resolved in https://github.com/influxdata/telegraf/pull/8564
