### ISSUE TITLE
Cloudwatch Input plugin returns no results

### ISSUE THREAD

**Issue by jake-bourke-simplisafe** [influxdata/telegraf#4384]
### Relevant telegraf.conf:
```
[global_tags]
  env = "prd"
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "3s"
  flush_interval = "30s"
  flush_jitter = "5s"
  precision = "s"
  debug = true
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.cloudwatch]]
  region = "us-east-1"
  period = "5m"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/EC2"
  ratelimit = 200
  [[inputs.cloudwatch.metrics]]
    names = ["CPUCreditBalance","StatusCheckFailed","StatusCheckFailed_System","StatusCheckFailed_Instance"]
```

### System info:
OS: Centos 7.2.1511
Telegraf: v1.7.0 (git: release-1.7 f4d22dd4)
Running in AWS

### Steps to reproduce:
1. Launch Centos 7 AWS instance, install telegraf
2. Attach role containing 'CloudwatchReadOnlyAccess' policy
3. Run telegraf with the above config MINUS the last 2 lines which specify fields to return
4. Results should be returned for every server with all fields
5. Restart telegraf with the full config listed above
6. No results return

### Expected behavior:
Metrics for the specified fields returned for all EC2 instances in the account.

### Actual behavior:
No metrics returned.

### Additional info:
As of version 1.2, the above config worked.  Starting in 1.3, it failed to return any results.  Latest version did not help.  The latest config and documentation have been examined to ensure all config options have been considered and we aren't suffering from old configs being copied into newer versions.

We didn't notice this issue for a while until we had an event that would have been discovered sooner if the StatusCheckFailed metric had been populated.  The post mortem revealed this data was missing, and troubleshooting the telegraf config yielded the above test.

**Comment by danielnelson** [comment]
Just to clarify, with the config above you get metrics but when the inputs.cloudwatch.metrics section is removed then nothing is returned?

The attached role should be sufficient, I am able to get metrics with this config in us-west-1 with only this policy.

If you can run the aws cli from this machine can you try:
```
aws cloudwatch list-metrics --namespace AWS/EC2 --region us-east-1 --metric-name CPUCreditBalance
```

Substitute a InstanceId from the last command and then run this:
```
aws cloudwatch get-metric-statistics --namespace AWS/EC2 --region us-east-1 --period 300 --start-time 2018-07-01T00:00:00Z --end-time 2018-07-01T00:15:00Z --statistics Average --metric-name CPUCreditBalance --dimensions Name=InstanceId,Value=i-deadbeef
```

**Comment by jake-bourke-simplisafe** [comment]
Thanks for getting back so quick!  My apologies, I was worried I wasn't totally clear in my original post, so hopefully I can remedy that.

With the config I posted, no results are returned.  If I REMOVE the inputs.cloudwatch.metrics section, then it returns data; an unfiltered and complete metric set for every server, every field, including the named fields I was trying to isolate.  The issue of 'no results' occurs only when I try to limit fields returned.

The config used in production actually contains over a dozen different cloudwatch inputs.  Those which invoke the inputs.cloudwatch.metrics section all fail to return results; EBS, EC2, Billing, Autoscaling...it's a pretty diverse group which return no data.

The cloudwatch inputs which do not use this field limiter section return data; ELB, Kinesis, ES, Lambda, NATGateway, NetworkELB, CloudFront, S3.  The only difference between the working inputs and those with no data is the inputs.cloudwatch.metrics section.  The config provided in this report was merely the simplest situation in which the problem could be demonstrated.

I have run the commands you provided so that a working role can be demonstrated on the server where this telegraf config runs.
```
# aws cloudwatch list-metrics --namespace AWS/EC2 --region us-east-1 --metric-name StatusCheckFailed | grep 'i-beeefalo'
DIMENSIONS	InstanceId	i-beeefalo

# aws cloudwatch get-metric-statistics --namespace AWS/EC2 --region us-east-1 --period 300 --start-time 2018-07-01T00:00:00Z --end-time 2018-07-01T00:15:00Z --statistics Average --metric-name StatusCheckFailed --dimensions Name=InstanceId,Value=i-beeefalo
StatusCheckFailed
DATAPOINTS	0.0	2018-07-01T00:10:00Z	Count
DATAPOINTS	0.0	2018-07-01T00:00:00Z	Count
DATAPOINTS	0.0	2018-07-01T00:05:00Z	Count
```

Again, thank you for your quick response.  I hope I have made the issue clearer and please let me know if you require any further data.

**Comment by danielnelson** [comment]
I thought that you must specify all dimensions when you specify a metric name limit, for instance this should not return anything:
```
aws cloudwatch get-metric-statistics --namespace AWS/EC2 --region us-east-1 --period 300 --start-time 2018-07-01T00:00:00Z --end-time 2018-07-01T00:15:00Z --statistics Average --metric-name StatusCheckFailed
```

Can you double check that this works in 1.2, I just tried and I did not collect any metrics.

**Comment by jake-bourke-simplisafe** [comment]
I do believe you have uncovered the problem.  This is not a bug but a misconfiguration.  Unfortunately this discovery is months late and in that time we have moved several telegraf versions as well as retiring the original data, leaving very little to piece this issue together with besides memory.

The discovery here is that named fields never worked without the dimension of InstanceID specified.  It was the original working "gather everything" data confusing the situation because "it had worked when 1.2 was installed".  Time has essentially made a fool of my memory and my misunderstanding of default values of dimensions meant my tests were in a rut that would not be able to find the solution.

My apologies for raising this as a bug, but thank you for helping resolve the matter.  For posterity, a working Cloudwatch input  EC2 config with named fields should look like this:

```
[[inputs.cloudwatch]]
  region = "us-east-1"
  period = "5m"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/EC2"
  ratelimit = 200
  [[inputs.cloudwatch.metrics]]
    names = ["CPUCreditBalance","StatusCheckFailed"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "InstanceId"
      value = "*"
```

**Comment by jake-bourke-simplisafe** [comment]
Some of my confusion came from the idea of inputs.cloudwatch.metrics.dimensions being optional if I intended to use a dimension value of '*', and I think this idea came from the original "(optional)" indicator in the docs.  

However, my understanding is that if you specify any field names[] under inputs.cloudwatch.metrics, you MUST then specify inputs.cloudwatch.metrics.dimensions sufficient for cloudwatch to return data.  Is there ever a case where you can use inputs.cloudwatch.metrics names[] and not specify dimensions?  If not, then I think that the "optional" mention is where the confusion came from, and that might need some adjustment.

I think the addition of the Troubleshooting sections is fantastic, and if when the dimensions section is truly optional can be clarified that should make things clear.

**Comment by danielnelson** [comment]
> I think this idea came from the original "(optional)" indicator in the docs.

I completely agree that this is misleading.  In the updated documentation I attempted to address this, here is the new comment:
```
## Dimension filters for Metric.  These are optional however all dimensions
## defined for the metric names must be specified in order to retrieve
## the metric statistics.
```

> Is there ever a case where you can use inputs.cloudwatch.metrics names[] and not specify dimensions?

I believe this is possible with custom metrics that do not have any dimensions, but I have not tested it.

**Comment by Bozz95** [comment]
FYI @danielnelson's  additional documentation about metrics filter was overwritten I think.

**Comment by bwesen** [comment]
FWIW I also had this problem (now), it's not apparent at all that you need to explicitly specify all dimensions. What is worse is that the error is completely silent, it just looks like nothing is logged, so you don't know where in the chain the error is.

The underlying issue is how CloudWatch works - it treats each metric name + dimensions tuple as a single metric ID both for its internal pushing and our fetching. Trying to fetch a metric with the right name but without all dimensions, is the same as trying to fetch a metric name that does not exist. 

The only reason I managed to solve it first was that I in desperation just tried adding more dimension specifiers to my plugin config. Then I've come to understand more on how CW works afterwards.
