### ISSUE TITLE
Aggregations can be dropped on startup

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4394]
### Relevant telegraf.conf:

```
[[inputs.tail]]
  files = ["test"]
  from_beginning = true
  data_format = "influx"

[[aggregators.basicstats]]
  period = "10s"
  drop_original = false
  stats = ["sum"]

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

Using any aggregator

### System info:

Telegraf 1.7

### Steps to reproduce:

```
cat - << EOF > test
foo value=1
foo value=2
foo value=3
foo value=4
foo value=5
foo value=6
foo value=7
EOF
```

1. Start Telegraf
2. Test increase odds of this occuring, sleep before the aggregators are run (`agg.Run(acc, shutdown)`) for several seconds.
3. Check for aggregate metric to be emitted and verify value
   ```
   foo,path=test value_sum=28
   ```

### Expected behavior:

All metrics are emitted

### Actual behavior:

Metrics collected immediately at startup MAY be dropped.

### Additional info:

- #4230
- #4395
-  #4393

**Comment by ssoroka** [comment]
not sure if this is still relevant. Haven't seen this happening and might be resolved now.
