### ISSUE TITLE
Tracked Forwarded Records/sec for SQL Server

### ISSUE THREAD

**Issue by tboggiano** [influxdata/telegraf#4398]
## Feature Request
Add the counter for Forwarded Records/sec to needed for version 2.  This is something that would be very simple to add and I could add have tested in a matter of minutes.
Opening a feature request kicks off a discussion.

### Proposal:
Add the counter for Forwarded Records/sec
### Current behavior:
Does not track
### Desired behavior:
Collect stat
### Use case: [Why is this important (helps with prioritizing requests)]
The overuse of heap tables can be a performance problem on tables and being able to forwarded records/sec can help you identify this.

**Comment by danielnelson** [comment]
@m82labs Could you review this issue, does it seem like a good idea and does it fit well with the existing philosophy of the new format?

**Comment by m82labs** [comment]
@danielnelson I think this is a good idea.

**Comment by danielnelson** [comment]
Closed in #4571
