### ISSUE TITLE
inputs logparser or tails dont generate a measurement with in influxdb

### ISSUE THREAD

**Issue by allamiro** [influxdata/telegraf#4399]
### Relevant telegraf.conf:

```
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  # urls = ["http://127.0.0.1:8086"]
 urls = ["http://x.x.x.x:8086"]
  ## The target database for metrics; will be created as needed.
   database = "xxxxx"

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
  # skip_database_creation = false

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
  # write_consistency = "any"

  ## Timeout for HTTP messages.
   timeout = "5s"

  ## HTTP Basic Auth
   username = "lcccccr"
   password = "ccccccc"


```
```


` [[inputs.logparser]]
#   ## Log files to parse.
#   ## These accept standard unix glob matching rules, but with the addition of
#   ## ** as a "super asterisk". ie:
#   ##   /var/log/**.log     -> recursively find all .log files in /var/log
#   ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
#   ##   /var/log/apache.log -> only tail the apache log file
   files = ["/var/log/httpd/access_log"]
#
#   ## Read files that currently exist from the beginning. Files that are created
#   ## while telegraf is running (and that match the "files" globs) will always
#   ## be read from the beginning.
   from_beginning = false
#
#   ## Method used to watch for file updates.  Can be either "inotify" or "poll".
    watch_method = "inotify"
#
#   ## Parse logstash-style "grok" patterns:
   [inputs.logparser.grok]
#     ## This is a list of patterns to check the given log file(s) for.
#     ## Note that adding patterns here increases processing time. The most
#     ## efficient configuration is to have one pattern per logparser.
#     ## Other common built-in patterns are:
#     ##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
#     ##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
     patterns = ["%{COMBINED_LOG_FORMAT}"]
#
#     ## Name of the outputted measurement name.
     measurement = "apache_access_log"
#
#     ## Full path(s) to custom pattern files.
     custom_pattern_files = []
`

![te](https://user-images.githubusercontent.com/279790/42419312-d6e8c922-82ba-11e8-9463-87c08e0a3265.PNG)

```
### System info:

[Include Telegraf version, operating system name, and other relevant details]

Telegraf v1.7.1
Operating System CentOS 7.5

### Steps to reproduce:

1. configure influxdb to accept all requests
2. installed telegraf and running installed webserver httpd and running 
3. configured logparser  section to send httpd access logs
4. opened influxdb from the command line  run use database x then show measurements only cpu  , disk and others are showing there no logparser or event tail  measurements 

### Expected behavior:
running show measurements under influxdb should show tail or logparser to query
### Actual behavior:
no indication that logparser or tail are sending data to influxdb
### Additional info:

[Include gist of relevant config, logs, etc.]
![te](https://user-images.githubusercontent.com/279790/42419316-eeb3cd7c-82ba-11e8-866e-040f8b50a4ff.PNG)

![httpd](https://user-images.githubusercontent.com/279790/42419329-3bf4a412-82bb-11e8-8194-bf23c94b4cbd.PNG)

```

> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
processes
swap
system
> exit

```

**Comment by danielnelson** [comment]
Usually this means the pattern did not match the logfile.  Can you show a few lines from `/var/log/httpd/access_log`?

**Comment by jilabaca** [comment]
Hello, I have the same problem with the log of my apache, they could help me.

These are sample lines from my log.

`
200.86.159.199 - - [22/Nov/2018:18:40:16 -0300] "GET /web/GST/template/html5/css/img/logoGstColor.png HTTP/1.1" 200 19345 

201.223.11.197 - - [22/Nov/2018:18:40:16 -0300] "GET /web/2017/sites/alumno-nuevo/js/main.js HTTP/1.1" 200 4350 

181.118.163.90 - - [22/Nov/2018:18:40:17 -0300] "GET /favicon.ico HTTP/1.1" 200 138 

10.58.33.221 - - [22/Nov/2018:18:40:17 -0300] "GET /web/acreditacion/logos/ip-transparente.png HTTP/1.1" 200 18487
`

**Comment by jilabaca** [comment]
Hello again, I managed to make it work, I made a custom patterns for my access_log.

I leave my example in case someone can help you.

patterns = ["%{CUSTOM_LOG}"]

custom_patterns = '''
        CUSTOM_LOG (?:%{IP:client}|-) - - \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{NOTSPACE:request_page} HTTP/%{NUMBER:http_version}" %{NUMBER:server_response} (?:%{NUMBER:bytes}|-)
        '''
