### ISSUE TITLE
MySQL Input - scanIntervalSlow breaks Prometheus

### ISSUE THREAD

**Issue by dupondje** [influxdata/telegraf#4401]
## Some queries we may want to run less often (such as SHOW GLOBAL VARIABLES)
  interval_slow                   = "30m"

### System info:
Valid for current Telegraf

### Steps to reproduce:
If you set the following in the MySQL input plugin:
 interval_slow                   = "30m"

And using the Prometheus exporter, then Telegraf will only ouput some details every 30 minutes on the /metrics page. 

### Expected behavior:
I would expect the details only be gathered every 30 minutes, but they should ALWAYS be exported/visible on the /metrics page.
This because if they are missing, you create gaps in the Prometheus graphs!

**Comment by danielnelson** [comment]
You can set the expiration interval higher on the prometheus output, this will instruct the plugin not to remove the metric for a longer period of time:
```
[[outputs.prometheus_client]]
  expiration_interval = "31m"
```
