### ISSUE TITLE
Unexpected output from the printer processor

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/telegraf#4416]
Running 1.7.0 on CentOS 7.

When I activate the printer processor, journalctl shows me lines like this:

Jul 12 16:50:06 xxxxx telegraf[25525]: [66 117 114 ... 10]

I doubt this is the expected behaviour.. 

Thanks.

**Comment by danielnelson** [comment]
Thanks for the report, as a workaround you can probably use the file output instead.

**Comment by voiprodrigo** [comment]
>Thanks for the report, as a workaround you can probably use the file output instead.

@danielnelson indeed, file served my purpose just fine, which was quick debug, and even better for not clogging service logs. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by voiprodrigo** [comment]
By the way, I noticed that using namepass defined with a simple string instead of array, caused some really weird behavior. I was using it with processor override + name_override and it renamed lots of measurements that it shouldn’t until I noticed the mistake. And shouldn’t the type of namepass be enforced? Is this known, or should I open a new issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielnelson** [comment]
Sounds similar to https://github.com/influxdata/telegraf/issues/3444, but can you open a new issue?
