### ISSUE TITLE
Flux Metrics Input

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4419]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
This plugin would consume the metrics exposed by the fluxd service

### Current behavior:
None

### Desired behavior:
Similar to the InfluxDB plugin, this would pull metrics from one or more fluxd services and push them to the db.

### Use case: [Why is this important (helps with prioritizing requests)]
This would allow users to monitor their fluxd service similar to how they monitor InfluxDB.

**Comment by sjwang90** [comment]
Going to close this based off the convo in this Flux Processor PR https://github.com/influxdata/telegraf/pull/6490

> Closing this as agreed on due to the vast amount of dependencies this would pull in. Please use the starlark processor instead. If you find use-cases where flux is a must please open an issue and reference this PR.
