### ISSUE TITLE
'make test' failures on Mac

### ISSUE THREAD

**Issue by PhoenixRion** [influxdata/telegraf#4420]
### Relevant telegraf.conf:
N/A
### System info:
Telegraf 1.7.1
Mac v10.13.2 (17C88)
go version go1.9.4 darwin/amd64

### Steps to reproduce:

1. git checkout 1.7.1
2. make test

### Expected behavior:
All test files are OK

### Actual behavior:
--- FAIL: Test_Gather (0.01s)
	fluentd_test.go:125: Start HTTP mock (http://localhost:8081) with sampleJSON
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x128acd2]

goroutine 6 [running]:
testing.tRunner.func1(0xc4201021e0)
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:711 +0x2d2
panic(0x12dfba0, 0x14d9b70)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
net/http/httptest.(*Server).Start(0xc4200fcee0)
	/usr/local/Cellar/go/1.9.4/libexec/src/net/http/httptest/server.go:107 +0x52
github.com/influxdata/telegraf/plugins/inputs/fluentd.Test_Gather(0xc4201021e0)
	/Users/rascheman/go/src/github.com/influxdata/telegraf/plugins/inputs/fluentd/fluentd_test.go:136 +0x2a7
testing.tRunner(0xc4201021e0, 0x13518d8)
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:789 +0x2de
FAIL	github.com/influxdata/telegraf/plugins/inputs/fluentd	0.038s
--- FAIL: TestNetworkErrors (20.09s)
        Error Trace:    http_response_test.go:50
	            	http_response_test.go:123
	            	http_response_test.go:687
	Error:      	Not equal:
	            	expected: "connection_failed"
	            	actual  : "timeout"
	Test:       	TestNetworkErrors
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/http_response	20.129s
--- FAIL: TestArgs (0.00s)
        Error Trace:    ping_test.go:120
	Error:      	Should be true
	Test:       	TestArgs
	Messages:   	Expected: [-I -c -n -s 16 2 eth0 www.google.com] Actual: [-S -c -n -s 16 2 eth0 www.google.com]
        Error Trace:    ping_test.go:147
	Error:      	Should be true
	Test:       	TestArgs
	Messages:   	Expected: [-I -W -c -n -s -t 12000.0 16 2 24 eth0 www.google.com] Actual: [-S -W -c -n -s -t 12000 16 2 24 eth0 www.google.com]
        Error Trace:    ping_test.go:162
	Error:      	Should be true
	Test:       	TestArgs
	Messages:   	Expected: [-I -W -c -i -n -s -t 1.2 12000.0 16 2 24 eth0 www.google.com] Actual: [-S -W -c -i -n -s -t 1.2 12000 16 2 24 eth0 www.google.com]
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/ping	0.475s
--- FAIL: TestSocketListener_unix_tls (0.00s)
        Error Trace:    socket_listener_test.go:66
	Error:      	Received unexpected error:
	            	listen unix /var/folders/63/xrd9gccj1fx2m2vtdyl9zqlcrgq1n5/T/telegraf620024366/socket_listener.TestSocketListener_unix_tls.sock: bind: invalid argument
	Test:       	TestSocketListener_unix_tls
--- FAIL: TestSocketListener_unix (0.00s)
        Error Trace:    socket_listener_test.go:130
	Error:      	Received unexpected error:
	            	listen unix /var/folders/63/xrd9gccj1fx2m2vtdyl9zqlcrgq1n5/T/telegraf998764469/socket_listener.TestSocketListener_unix.sock: bind: invalid argument
	Test:       	TestSocketListener_unix
--- FAIL: TestSocketListener_unixgram (0.00s)
        Error Trace:    socket_listener_test.go:154
	Error:      	Received unexpected error:
	            	listen unixgram /var/folders/63/xrd9gccj1fx2m2vtdyl9zqlcrgq1n5/T/telegraf105035152/socket_listener.TestSocketListener_unixgram.sock: bind: invalid argument
	Test:       	TestSocketListener_unixgram
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/socket_listener	0.043s
--- FAIL: TestBestEffort_unixgram (0.00s)
    --- FAIL: TestBestEffort_unixgram/max (0.00s)
        Error Trace:    rfc5426_test.go:242
    	Error:      	Expected nil, but got: &net.OpError{Op:"write", Net:"unixgram", Source:(*net.UnixAddr)(0xc4203ed340), Addr:(*net.UnixAddr)(0xc4203ed360), Err:(*os.SyscallError)(0xc4203ed380)}
    	Test:       	TestBestEffort_unixgram/max
--- FAIL: TestStrict_unixgram (0.00s)
    --- FAIL: TestStrict_unixgram/max (0.00s)
        Error Trace:    rfc5426_test.go:242
    	Error:      	Expected nil, but got: &net.OpError{Op:"write", Net:"unixgram", Source:(*net.UnixAddr)(0xc4203edd20), Addr:(*net.UnixAddr)(0xc4203edd40), Err:(*os.SyscallError)(0xc4203edd60)}
    	Test:       	TestStrict_unixgram/max
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/syslog	5.396s
--- FAIL: TestUDP_WriteWithRealConn (0.00s)
        Error Trace:    udp_test.go:206
	Error:      	Received unexpected error:
	            	listen udp 127.0.0.0:0: bind: can't assign requested address
	Test:       	TestUDP_WriteWithRealConn
FAIL
FAIL	github.com/influxdata/telegraf/plugins/outputs/influxdb	0.049s
--- FAIL: TestSocketWriter_unix (0.00s)
        Error Trace:    socket_writer_test.go:55
	Error:      	Received unexpected error:
	            	listen unix /var/folders/63/xrd9gccj1fx2m2vtdyl9zqlcrgq1n5/T/telegraf735911008/socket_writer.TestSocketWriter_unix.sock: bind: invalid argument
	Test:       	TestSocketWriter_unix
--- FAIL: TestSocketWriter_unixgram (0.00s)
        Error Trace:    socket_writer_test.go:76
	Error:      	Received unexpected error:
	            	listen unixgram /var/folders/63/xrd9gccj1fx2m2vtdyl9zqlcrgq1n5/T/telegraf431807039/socket_writer.TestSocketWriter_unixgram.sock: bind: invalid argument
	Test:       	TestSocketWriter_unixgram
FAIL
FAIL	github.com/influxdata/telegraf/plugins/outputs/socket_writer	0.034s

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Resolved by 96cb0aaea02d4647e684c34cdeebbc72636c270c
