### ISSUE TITLE
Kafka consumer tls not working

### ISSUE THREAD

**Issue by shane99a** [influxdata/telegraf#4421]
### Relevant telegraf.conf:
```
[agent]
  collection_jitter = "0s"
  debug = true
  flush_interval = "10s"
  flush_jitter = "0s"
  interval = "10s"
  logfile = ""
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true
  precision = ""
  quiet = false
  round_interval = true

[[outputs.influxdb]]
  database = "test"
  skip_database_creation = true
  urls = [
    "http://DOCKER_IP:8086"
  ]
[[inputs.kafka_consumer]]
  brokers = [
    "DOCKER_IP:9091"
  ]
  consumer_group = "telegraf_metrics_consumers"
  data_format = "influx"
  insecure_skip_verify = false
  offset = "oldest"
  tls_ca = "/etc/telegraf/ca.pem"
  tls_cert = "/etc/telegraf/cert.pem"
  tls_key = "/etc/telegraf/key.pem"
  topics = [
    "test"
  ]

```

### System info:
telegraf 1.7.0 docker image, running inside kubernetes as a pod. Kafka version is 1.1.0.

### Steps to reproduce:

1. Using this kafka docker image: https://github.com/wurstmeister/kafka-docker
2. Setup ssl for that kafka image on port 9091, and non secure port on 9092
3. I have verified that ssl works because I have used other software to connect to it securely. I even used openssl to confirm that it works
4. Connect to kafka consumer using tls on port 9091, and run telegraf

### Expected behavior:
Should connect to kafka

### Actual behavior:
```
2018/07/14 02:44:12 I! Using config file: /etc/telegraf/telegraf.conf
2018-07-14T02:44:12Z D! Attempting connection to output: influxdb
2018-07-14T02:44:12Z D! Successfully connected to output: influxdb
2018-07-14T02:44:12Z I! Starting Telegraf v1.7.0
2018-07-14T02:44:12Z I! Loaded inputs: inputs.kafka_consumer
2018-07-14T02:44:12Z I! Loaded aggregators:
2018-07-14T02:44:12Z I! Loaded processors:
2018-07-14T02:44:12Z I! Loaded outputs: influxdb
2018-07-14T02:44:12Z I! Tags enabled:
2018-07-14T02:44:12Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2018-07-14T02:44:12Z D! TLS Enabled
2018-07-14T02:44:13Z E! Error when creating Kafka Consumer, brokers: [DOCKER_IP:9091], topics: [test]
2018-07-14T02:44:13Z E! Service for input inputs.kafka_consumer failed to start, exiting
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

### Additional info:
When I use non secure port 9092, then it works fine. The error message is very unclear on what the issue is. Is there a way I can enable more verbose logging because I am all out ideas at this point. I would love some help on this

**Comment by thefunkjunky** [comment]
@shane99a, I'm experiencing similar issues with both telegraf and burrow on my kafka cluster.  May I ask how you fixed this, if you fixed this?

**Comment by shane99a** [comment]
> @shane99a, I'm experiencing similar issues with both telegraf and burrow on my kafka cluster. May I ask how you fixed this, if you fixed this?

Sorry I forgot what I did to fix it and this work was for a previous company.. It could be this part that was causing it: `insecure_skip_verify = false` or I had some environment issue with iptables, maybe try turning it off temporarily?
