### ISSUE TITLE
Pushed metrics wrong time-stamp (UTC timing rather than the local machine time)

### ISSUE THREAD

**Issue by hsafe** [influxdata/telegraf#4423]
### Relevant telegraf.conf:
No specific line of config

### System info:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

Telegraf v1.6.3 (git: release-1.6 890f1d3a)

### Steps to reproduce:
Once installing the tickstack standard server and configuring to receive the MYSQL; we see that the graphs we make are not the time-stamps of the agents but the tickstack server. As our monitoring server is in different continent it is completely off the right timing. Frankly I expected and know that the logs have the timestamp why in the graph we are shown the monitoring server 

### Expected behavior:
Wanted to see the graphs based on the time-stamped created messages at the host not the monitoring servers localtime that holds the DB. 
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by hsafe** [comment]
I just extracted some of the pushed metrics to the influxdb in the bash...after changing the Unix timing on them found out that the telegraf agent is pushing the data in UTC time frame:
elect * from cpu limit 10
```
name: cpu
time                cpu       host usage_guest usage_guest_nice usage_idle        usage_iowait         usage_irq usage_nice usage_softirq        usage_steal usage_system         usage_user
----                ---       ---- ----------- ---------------- ----------        ------------         --------- ---------- -------------        ----------- ------------         ----------
1528021270000000000 cpu-total Tick 0           0                99.74974974974884 0                    0         0          0.050050050050050046 0           0.20020020020020465  0
1528021270000000000 cpu0      Tick 0           0                99.79979979979997 0.1001001001001046   0         0          0                    0           0.10010010010010015  0
```
```
$ date --date @1531726541
Mon Jul 16 07:35:41 UTC 2018

```
So the unmatched data timestamp is shipped from the telegraf agent ...
Based on that how can I ask the telegraf agent to use the localhost time rather the defaulted UTC timing?
Can you please help?cause reading the telegraf conf file did not find any part related to this...

**Comment by hsafe** [comment]
Found this late:
https://github.com/influxdata/influxdb/issues/3211
Closing with despair...

**Comment by danielnelson** [comment]
@hsafe Sorry, as you have discovered we don't support this.  I find it is best to always store in UTC and then leave it to the visualization program to convert to local time.
