### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by mhf-ir** [influxdata/telegraf#4425]
Downloading the dot deb file with not static url is not DevOps friendly for using auto installation latest stable of version 1.x of telegraf.
Any documentation or method to add ppa of stable telegraf repo for auto installation on ubuntu or debian based OS

**Comment by danielnelson** [comment]
Have you tried this?  The repos.influxdata.com server always has the latest release:

https://docs.influxdata.com/telegraf/latest/introduction/installation/#installation
