### ISSUE TITLE
Add logfmt Parser Plugin

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4427]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
add a parser for `logfmt`

### Current behavior:
None

### Desired behavior:
the ability to parse logfmt log messages and specify the keys for timestamp (and format), tags, and fields

### Use case: [Why is this important (helps with prioritizing requests)]
this would be useful to ingesting influxdb log data

**Comment by danielnelson** [comment]
[logfmt spec](https://brandur.org/logfmt)
