### ISSUE TITLE
Error in ping plugin

### ISSUE THREAD

**Issue by ut0mt8** [influxdata/telegraf#443]
Hello,

The doc (and the code) mention : 

ping timeout, in s. 0 == no timeout (ping -t <TIMEOUT>)
  timeout = 0.0

That is absolutely not true, at least on debian linux ,
-t is the flag for specifie ttl, 
-W is the right option to use

Thks.

**Comment by sparrc** [comment]
thanks for the report

**Comment by xor-gate** [comment]
Below the hood is not so cross-platform to use the ping plugin because it exec's directly the system `/bin/ping`. See also https://github.com/influxdata/telegraf/issues/496

**Comment by sparrc** [comment]
closing in favor of #496

**Comment by HackedServer** [comment]
Since the ping plugin isn't going to be replaced with a Go ping plugin, this issue should be reopened and resolved.

**Comment by sparrc** [comment]
true, will do :+1:

**Comment by xor-gate** [comment]
@sparrc so as I can see the native golang ping implementation has issues with reporting the incorrect latency?

**Comment by sparrc** [comment]
@xor-gate, nope, Telegraf isn't using a native go implementation, there is just one user who seems to have reported differences between executing ping via bash vs. executing via Telegraf, which I still can't explain.
