### ISSUE TITLE
Not Glob isn't working - not filtering anything when using !

### ISSUE THREAD

**Issue by 1activegeek** [influxdata/telegraf#4432]
### Relevant telegraf.conf:
```
  [inputs.docker.tagdrop]
    network = [ "!total" ]
```
### System info:

Current version of influx data container from dockerhub

### Steps to reproduce:

1. Setup telegraf to monitor docker
2. Write glob to specify drop all values for the tag network, that do NOT match the given pattern
3. No change is being made at all

### Expected behavior:

Data entered should no longer have any values for the tag specified outside of the specified pattern.

### Actual behavior:

No filtering is happening at all.

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Thanks for the report, while it's in queue for resolution, could you use `tagpass` instead?

**Comment by 1activegeek** [comment]
I had a feeling someone would point that out. 😜 

As I understood the documentation, it would seem that tagpass will operate as a sort of filter for ALL points being passed by the input. So in this case if I use this and all points do not have one of the tags to match, the point won't be passed at all. While conversely if I was to use a tag that all lines have, then it wouldn't end up actually filtering out the ones I want to drop.

**Comment by glinton** [comment]
It turns out [the glob syntax](https://github.com/gobwas/glob#syntax) doesn't include a `!` for negative matching.
