### ISSUE TITLE
Help wanted: Parsing metrics in influxdb properly

### ISSUE THREAD

**Issue by phanohanover** [influxdata/telegraf#4444]
### Relevant telegraf.conf:
[[inputs.statsd]]
protocol = "udp"
max_tcp_connections = 250
service_address = ":8125"

### System info:
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final
Linux dvleslweb001.dev.cibc.mbs.lgs 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Telegraf v1.5.2 (git: release-1.5 67440c95)
Nom        : httpd
Architecture        : x86_64
Version     : 2.2.15
Révision     : 69.el6.centos

vhost config:
 <Location />
        Statsd On
        StatsdHost dev.server.com
        StatsdPort 8125
        StatsdStat Frontend-Web
        StatsdExclude .*
        StatsdPrefix Http-Code
 </Location>

All data is sent to influxdb...

### Steps to reproduce:
Obective: Collecting every http codes from apache and have a dashboard in grafana that shows how many 404, 302, 200, etc codes we got this week in a schema or graphic.

### Actual behavior:
The configuration works fine. 
However, inside influxdb, the metrics incoming from statsd generates a measurement for every code/get,post, head, deleted,etc
![image](https://user-images.githubusercontent.com/7452857/43006309-5b476614-8c03-11e8-8fde-77c04aab756f.png)

### Expected behavior:
In the exemple below, the metric called CPU is there only once and all affected hosts are listed below. In statsd-apache case herein, It creates too many measurements. I'd rather have one measurement called (ie:) Http-codes with all servers listed below then codes(200) and status(POST) listed in the fields along with the other apache metrics.

![image](https://user-images.githubusercontent.com/7452857/43006338-731aa0f8-8c03-11e8-8fd3-baaf67175661.png)

Anyone could help me with this?

**Comment by glinton** [comment]
You should be able to rename the tags with [a processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors), though i'm not sure if override or the regex one fits best here.

**Comment by danielnelson** [comment]
Start with the `template` option in the statsd input, I believe it would be similar to this (untested!):
```
templates = [
    "measurement.method.status"
]
```

You can read more about the template format in the [statsd input docs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd#statsd-bucket---influxdb-line-protocol-templates) or under the [graphite data format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite) (as it is the same template system).

Let us know if you need addition help.

**Comment by phanohanover** [comment]
Thanks for the quick response. I am trying to find the triggers "method", "Status", etc. It did change where metrics get in a single measurment ++AAA Thanks for that. However, I lost the codes and status. I tried to find what get's posted out from apache but cannot find it. Maybe you have an idea where I could find the field names? Once again, thank you very much for answering me. It is quite helpful. SP

**Comment by danielnelson** [comment]
With the template above, the method and status should become tags on the `Http-Code` measurement and it should look like this in line protocol:
```
Http-Code,method=POST,status=200,metric_type=counter value=42
```

If you still have trouble finding the method/status, perhaps you can capture the statsd output from Apache using netcat.  This will create a server listening to udp on port 8125:
```
nc -lu localhost 8125
```
