### ISSUE TITLE
Question: Reading interval from input plugin

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#4445]
Is there a way to programmatically read the collection interval from within an input plugin? I have an API call that can take a long time and I'd like to set the timeout to match the interval.

**Comment by glinton** [comment]
I don't believe this can be dynamically set (after telegraf starts), but you can set intervals and timeouts in the config file; some for [the agent](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent-configuration) others depending on which input you're using.

**Comment by prydin** [comment]
I'm not looking to set it. I just want to read it from the plugin (vsphere) I'm building. I tried by just making it a member of the plugin struct, but it doesn't seem to get picked up, even if I'm specifying it explicitly in the plugin config.

**Comment by glinton** [comment]
Ok, I think I see what you're asking now. I don't believe it is currently possible to get the config's [`Agent.Interval.Duration`](https://github.com/influxdata/telegraf/blob/master/cmd/telegraf/telegraf.go#L92-L101) without reading the config yourself. That's odd your plugin specific config didn't get picked up :thinking:

**Comment by glinton** [comment]
I wonder if it's not parsing strings like `20s` into a `time.Duration`, have you tried setting the type in your plugin struct to a string then parsing it to a Duration before using it?

**Comment by prydin** [comment]
It's a bit strange. If I explicitly set "interval" in the config of my plugin, it does get picked up by telegraf. In other words, my plugin will be executed every 20s (for example) even if the default interval is set to 60s. This works even if I don't declare Interval on my struct. I believe this is by design.

My assumption was that if I did declare Interval on my struct, it would pick up the value I'm specifying, but that doesn't seem to be the case. I guess Interval has some special hard-coded handling when the TOML file is loaded. 

Here's the code: https://github.com/prydin/telegraf/blob/collection-chunking/plugins/inputs/vsphere/vsphere.go

As you can see, I'm declaring "Interval" at line 18. But when I print it at line 221, it comes out as "0s". 

I guess I could solve it by having a separate setting for collection timeout, but that seems a bit redundant.

**Comment by prydin** [comment]
(And no, changing the declaration to internal.Interval didn't help. Just tried)

**Comment by glinton** [comment]
>I guess Interval has some special hard-coded handling
That sounds like what's happening to me, maybe @danielnelson can shed some more light

**Comment by prydin** [comment]
I'll have a peek in the code. I'm assuming it's in the internal/config neighborhood? It would be really neat to have the interval available so my code can be a bit better behaved and terminate queries that take longer than the collection interval.

**Comment by prydin** [comment]
Here's the "culprit" (or intentional behavior):

https://github.com/prydin/telegraf/blob/collection-chunking/internal/config/config.go#L1201

As you can see, "interval" and a bunch of other system attributes are explicitly deleted before they get sent down to the input plugin parser. If I comment out that line, "interval" gets propagated to my plugin. 

That's not fully solving the problem, though, since the field will be left blank if I don't explicitly specify a interval for my plugin.

One solution could be to check if the plugin struct declares Interval but nothing is defined in the plugin config. In those cases we could use reflection to populate the field with the global default value for the interval.

**Comment by prydin** [comment]
Here's a way to solve it. You may find it cludgy and you may argue that "interval" doesn't deserve that special treatment. But anyway, removing the delete statement discussed above and adding this to the end of addInput() in internal/config/config.go makes all input plugins aware of their interval. Just a suggestion...

```
	if err := toml.UnmarshalTable(table, input); err != nil {
		return err
	}

	// Propagate default interval to input if declared but not specified
	//
	if _, ok := table.Fields["interval"]; !ok {
		v := reflect.ValueOf(input)
		s := v.Elem()
		f := s.FieldByName("Interval")
		if f.IsValid() && f.CanSet() {
			i := c.Agent.Interval
			f.Set(reflect.ValueOf(i))
		}
	}

	rp := models.NewRunningInput(input, pluginConfig)
	c.Inputs = append(c.Inputs, rp)
	return nil
```

**Comment by danielnelson** [comment]
As you have discovered this was by design that we didn't expose the interval to the plugin.  If you would like to build a plugin with a dynamic interval you could use the `ServiceInput` interface instead.  It's not something that we would want to add to the official Telegraf repo, but it is an option that is available.

**Comment by danielnelson** [comment]
@crazy-canux We don't want plugins to take actions based on the interval, it shouldn't be something that is of interest to a correctly designed plugin.  However, we are always open to reconsidering and if you describe why you need this functionality we can discuss it.

**Comment by prydin** [comment]
@danielnelson There's one use case I can think of where it makes sense. I encountered this when I wrote the vSphere plugin.

The interval could be used as a deadline for contexts. Something like this:

```go
func (p *MyPlugin) Gather(acc Accumulator) {
   ctx, cancel := context.WithDeadLine(context.Background(), p.Interval)
   defer cancel()
   doThis(ctx)
   doThat(ctx)
   doTheOtherThing(ctx)
}
```

This would be kind of neat, since it would make sure any blocking functions were interrupted when the interval was over. 

But then again, one could argue that Gather() simply should take a Context as an argument and it would be up to Telegraf core to determine what the deadline is. Also, I think the semantics are that Gather() is allowed to finish even if it's taking too long...

**Comment by danielnelson** [comment]
I do want to change up the plugin interfaces to take a context but I've been thinking about doing this primarily for canceling the plugin in the case of Telegraf shutdown/reload.  I'm not sure if we necessarily want to push the notion that the plugin HAS to finish within its interval.  Then again, it's always optional to return when the context deadline completes.

**Comment by crazy-canux** [comment]
```
	if err := toml.UnmarshalTable(table, input); err != nil {
		return err
	}

	// Propagate default interval to input if declared but not specified
	//
	if _, ok := table.Fields["interval"]; !ok {
		v := reflect.ValueOf(input)
		s := v.Elem()
		f := s.FieldByName("Interval")
		if f.IsValid() && f.CanSet() {
			i := c.Agent.Interval
			f.Set(reflect.ValueOf(i))
		}
	}

	rp := models.NewRunningInput(input, pluginConfig)
	c.Inputs = append(c.Inputs, rp)
	return nil
```

@prydin this will only get agent interval. What I want is plugin interval.
Is there any way to do that?
eg:
         [[inputs.myplugin]]
                   interval = "10m"

I need this interval in my plugin to used for time range.

Thx!

**Comment by prydin** [comment]
No, there's no way of doing that. It seems this is a pretty strongly held design decision, so I don't think this is going to change anytime soon.

**Comment by crazy-canux** [comment]
Ok, thanks.
I have to add more attribution in configuration to workaround.
