### ISSUE TITLE
[input.syslog] Document pure ReinerScript equivalent to the common Rsyslog configuration

### ISSUE THREAD

**Issue by mjf** [influxdata/telegraf#4446]
Please, document that the equivalent of the common *Rsyslog* configuration line

    *.* @@(o)127.0.0.1:6514;RSYSLOG_SyslogProtocol23Format

reads in pure *ReinerScript* as follows:

    if prifilt("*.*") then {
        action(
            type = "omfwd"
            protocol = "tcp"
            tcp_framing = "octet-counted"
            target = "127.0.0.1"
            port = "6514"
            template = "RSYSLOG_SyslogProtocol23Format"
        )
    }

Thank you.

**Comment by glinton** [comment]
@mjf would you be willing to make a pr for this? It would only require an update to [readme.md](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/syslog/README.md)

**Comment by danielnelson** [comment]
@mjf When I try this the message comes through but I get a few error messages from rsyslog, do you know how to resolve these:
```
syslog,appname=dbn,facility=user,host=debian-stretch-syslog.virt,hostname=debian-stretch-syslog,severity=notice facility_code=1i,message=" test",severity_code=5i,timestamp=1538425816847206000i,version=1i 1538425816847762879
syslog,appname=liblogging-stdlog,facility=local7,host=debian-stretch-syslog.virt,hostname=debian-stretch-syslog,severity=info facility_code=23i,message=" action 'action 0' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]",severity_code=6i,timestamp=1538425816847711000i,version=1i 1538425816848138900
syslog,appname=liblogging-stdlog,facility=local7,host=debian-stretch-syslog.virt,hostname=debian-stretch-syslog,severity=info facility_code=23i,message=" action 'action 0' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]",severity_code=6i,timestamp=1538425816847906000i,version=1i 1538425816848156615
```

**Comment by danielnelson** [comment]
That seems to be a separate issue, I have added the RainerScript version to the docs.
