### ISSUE TITLE
Question: If telegraf cannot send data to influx (lets say it was misconfigured) then will it lose data?

### ISSUE THREAD

**Issue by shane99a** [influxdata/telegraf#4447]
I have a kafka input, and influx outout. I want to ensure that there is no data loss.  Lets say influx config was misconfigured then all the kafka data that telegraf was sending would not be saved in influx. When I fixed the issue and restarted telegraf, kafka input would not send those data anymore. So it looks like there is data loss.

Is this expected behaviour? Is there any settings to make it not ignore data that wasn't handled properly by the output plugin?

**Comment by glinton** [comment]
This almost sounds like #3984, but telegraf doesn't cache metrics locally, so even if that issue were resolved, as soon as you restart telegraf, current metrics collected/in queue would be lost. At least as far as I can tell.
