### ISSUE TITLE
Error parsing /etc/telegraf/telegraf.conf, Invalid data format: grok

### ISSUE THREAD

**Issue by APenketh** [influxdata/telegraf#4449]
### Relevant telegraf.conf:
```
[[inputs.tail]]
  name_override = "nginx_access"
  files = ["/var/log/nginx/access.log"]
  from_beginning = false
  watch_method = "inotify"
  pipe = false
  data_format = "grok"
  grok_patterns = ["%{COMMON_LOG_FORMAT}"]
```
### System info:

Telegraf v1.7.1 
OS: CentOS 7.5

### Steps to reproduce:

1. Add the configuration into the telegraf configuration file
2. Restart the telegraf service

### Expected behavior:

Service To Start Up Succesfully

### Actual behavior:

Get the following error:
```
Jul 21 13:32:44 telegraf: 2018/07/21 13:32:44 E! Error parsing /etc/telegraf/telegraf.conf, Invalid data format: grok
```

**Comment by danielnelson** [comment]
Actually this feature is in the development branch only, and will be in the 1.8 release.  You can use the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) to access this, or with the released version you would can use the logparser plugin.

**Comment by xor-gate** [comment]
I was also lost, found this issue. It works like a charm with build of develop! Thanks all.
