### ISSUE TITLE
Mesos input produces partial metric set if timeout reached

### ISSUE THREAD

**Issue by orientzc** [influxdata/telegraf#4454]
i used telegraf with version 1.7, inputs.mesos and outputs.prometheus_client.
the config of inputs.mesos:
![image](https://user-images.githubusercontent.com/17718632/43067609-66104694-8e9a-11e8-8e06-7dbc1efa4205.png)
and the mesos api: /metrics/snapshot
![image](https://user-images.githubusercontent.com/17718632/43067768-f09a571e-8e9a-11e8-8aca-b4bb0aa27a7f.png)

and the command
![image](https://user-images.githubusercontent.com/17718632/43067809-112f75a4-8e9b-11e8-8003-84f48d673327.png)
BUT, the telegraf metrics(prometheus_client):

it works but a part of metrics losted, such as mesos_master_cpus_total, mesos_master_tasks_running/killing,  and so on.
the logs:
![image](https://user-images.githubusercontent.com/17718632/43067970-9c41f64e-8e9b-11e8-8b59-cd4b9166e315.png)

And i run it with the "./telegraf -config /data/monitor/telegraf/telegraf.conf -input-filter mesos -test" on linux. there is also same problem, and the logs show right but the metrics is wrong.
the logs:
![image](https://user-images.githubusercontent.com/17718632/43068026-c19e1288-8e9b-11e8-9802-d81c43748cc1.png)

Thanks.

**Comment by glinton** [comment]
Thanks for submitting this. If you don't mind, could you paste the text in, instead of screenshots as it is easier to digest. Thanks.

**Comment by orientzc** [comment]
Thanks. and i hope it works, but i donnt know where is wrong. and i will pay attention to the text.
text:
the config of inputs.mesos:
[[inputs.mesos]]
  ## Timeout, in ms.
  timeout = 100
  ## A list of Mesos masters.
  masters = ["http://x.x.x.x:5050"]
  ## Master metrics groups to be collected, by default, all enabled.
  master_collections = [
    "resources",
    "master",
    "system",
    "agents",
    "frameworks",
    "tasks",
    "messages",
    "evqueue",
    "registrar",
  ]
  ## A list of Mesos slaves, default is []
  # slaves = []
  ## Slave metrics groups to be collected, by default, all enabled.
  # slave_collections = [
  #   "resources",
  #   "agent",
  #   "system",
  #   "executors",
  #   "tasks",
  #   "messages",
  # ]

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

the mesos api(/metrics/snapshot):
{"master\/elected":1.0,"allocator\/mesos\/allocation_run_ms\/p999":8.626003968,"allocator\/mesos\/allocation_run_ms\/p50":0.584576,"allocator\/mesos\/allocation_run_ms\/max":8.709888,"allocator\/mesos\/allocation_run_ms":0.59392,"master\/valid_executor_to_framework_messages":0.0,"allocator\/mesos\/resources\/mem\/total":5444171.0,"allocator\/event_queue_dispatches":0.0,"master\/slaves_active":28.0,"registrar\/state_store_ms\/p9999":81.1583030784,"registrar\/state_store_ms\/p95":80.7267072,"registrar\/state_store_ms\/p90":80.2942464,"master\/mem_total":5444171.0,"registrar\/state_store_ms":81.159168,"master\/tasks_starting":0.0,"master\/outstanding_offers":0.0,"registrar\/state_store_ms\/p999":81.150518784,"master\/mem_percent":0.282769038665391,"system\/cpus_total":32.0,"master\/task_killed\/source_slave\/reason_executor_unregistered":39.0,"master\/messages_reregister_slave":60.0,"master\/task_failed\/source_slave\/reason_container_limitation_memory":1.0,"overlay\/log\/recovered":1.0,"registrar\/queued_operations":0.0,"system\/load_1min":3.14,"master\/slaves_disconnected":0.0,"master\/slave_removals\/reason_registered":10.0,"master\/messages_suppress_offers":455261.0,"allocator\/mesos\/resources\/disk\/total":4150834.0,"master\/uptime_secs":26165600.8508022,"registrar\/state_store_ms\/p50":76.83456,"frameworks\/cassandra-external-principal\/messages_processed":2525.0,"master\/cpus_percent":0.297879464285714,"master\/messages_update_slave":95.0,"master\/event_queue_dispatches":23.0,"allocator\/mesos\/offer_filters\/roles\/kafka-role\/active":0.0,"registrar\/state_store_ms\/min":72.509952,"allocator\/mesos\/resources\/mem\/offered_or_allocated":1539443.0,"master\/messages_register_framework":13.0,"allocator\/mesos\/event_queue_dispatches":0.0,"master\/cpus_total":896.0,"master\/tasks_running":727.0,"registrar\/state_store_ms\/count":2.0,"master\/cpus_revocable_used":0.0,"system\/mem_total_bytes":134896713728.0,"master\/tasks_killing":0.0,"master\/tasks_staging":0.0,"master\/dropped_messages":7.0,"master\/messages_reregister_framework":100.0,"master\/mem_revocable_total":0.0,"master\/mem_revocable_percent":0.0,"master\/messages_executor_to_framework":0.0,"registrar\/log\/recovered":1.0,"allocator\/mesos\/roles\/cassandra-cms-role\/shares\/dominant":0.00740092232067098,"master\/disk_revocable_total":0.0,"frameworks\/cassandra-external-principal\/messages_received":2525.0,"frameworks\/kafka-principal\/messages_processed":93.0,"allocator\/mesos\/allocation_run_ms\/p95":5.1990144,"master\/messages_unregister_framework":0.0,"master\/slaves_connected":28.0,"master\/messages_status_update_acknowledgement":1013466.0,"frameworks\/cassandra-test-principal\/messages_received":1726.0,"master\/frameworks_connected":7.0,"master\/messages_deactivate_framework":2.0,"master\/messages_launch_tasks":503914.0,"master\/event_queue_http_requests":0.0,"allocator\/mesos\/roles\/cassandra-role\/shares\/dominant":0.00740092232067098,"master\/messages_decline_offers":8422795.0,"frameworks\/cassandra-test-principal\/messages_processed":1726.0,"frameworks\/cassandra-bcms-principal\/messages_processed":640.0,"master\/slaves_inactive":0.0,"allocator\/mesos\/offer_filters\/roles\/cassandra-external-role\/active":0.0,"master\/messages_resource_request":0.0,"registrar\/state_store_ms\/max":81.159168,"master\/disk_revocable_used":0.0,"master\/frameworks_disconnected":0.0,"master\/messages_authenticate":0.0,"master\/invalid_status_updates":35230.0,"master\/slave_shutdowns_completed":31.0,"allocator\/mesos\/offer_filters\/roles\/cassandra-cms-role\/active":0.0,"master\/messages_kill_task":66783.0,"master\/slave_shutdowns_canceled":0.0,"master\/slave_registrations":56.0,"allocator\/mesos\/roles\/*\/shares\/dominant":0.0,"master\/invalid_executor_to_framework_messages":0.0,"master\/slave_removals\/reason_unregistered":1.0,"allocator\/mesos\/allocation_run_ms\/p90":0.9636608,"master\/messages_register_slave":62.0,"master\/event_queue_messages":0.0,"allocator\/mesos\/roles\/cassandra-test-role\/shares\/dominant":0.00740092232067098,"master\/messages_reconcile_tasks":1473173.0,"master\/tasks_lost":759.0,"master\/cpus_used":266.9,"master\/valid_framework_to_executor_messages":0.0,"master\/slave_removals\/reason_unhealthy":31.0,"master\/task_failed\/source_slave\/reason_container_launch_failed":308.0,"master\/tasks_failed":7746.0,"master\/invalid_status_update_acknowledgements":0.0,"system\/load_5min":2.89,"master\/slave_reregistrations":14.0,"registrar\/state_fetch_ms":85.966848,"master\/gpus_used":0.0,"allocator\/mesos\/allocation_run_ms\/min":0.432128,"master\/disk_total":4150834.0,"master\/messages_unregister_slave":1.0,"master\/slave_shutdowns_scheduled":35.0,"frameworks\/dcos_marathon\/messages_processed":1935755.0,"allocator\/mesos\/roles\/cassandra-external-role\/shares\/dominant":0.00740092232067098,"registrar\/state_store_ms\/p99":81.07267584,"registrar\/registry_size_bytes":6245.0,"master\/messages_framework_to_executor":0.0,"master\/messages_status_update":1048701.0,"master\/slave_removals":42.0,"allocator\/mesos\/allocation_run_ms\/count":1000.0,"allocator\/mesos\/roles\/kafka-role\/shares\/dominant":0.00502232142857143,"master\/recovery_slave_removals":0.0,"allocator\/mesos\/offer_filters\/roles\/cassandra-test-role\/active":0.0,"frameworks\/cassandra-principal\/messages_received":1590.0,"master\/messages_exited_executor":90.0,"master\/mem_used":1539443.0,"allocator\/mesos\/allocation_runs":26618548.0,"master\/valid_status_update_acknowledgements":1013466.0,"master\/disk_used":140904.0,"master\/task_lost\/source_master\/reason_slave_removed":758.0,"master\/gpus_percent":0.0,"master\/mem_revocable_used":0.0,"master\/frameworks_active":7.0,"frameworks\/cassandra-cms-principal\/messages_processed":1387.0,"allocator\/mesos\/resources\/cpus\/offered_or_allocated":266.9,"master\/frameworks_inactive":0.0,"master\/tasks_finished":486660.0,"master\/tasks_killed":7092.0,"frameworks\/kafka-principal\/messages_received":93.0,"master\/cpus_revocable_percent":0.0,"frameworks\/cassandra-cms-principal\/messages_received":1387.0,"master\/gpus_revocable_percent":0.0,"frameworks\/cassandra-principal\/messages_processed":1590.0,"master\/disk_percent":0.0339459491755151,"allocator\/mesos\/allocation_run_ms\/p9999":8.70149959680001,"allocator\/mesos\/roles\/slave_public\/shares\/dominant":0.279464285714286,"master\/cpus_revocable_total":0.0,"master\/gpus_revocable_total":0.0,"allocator\/mesos\/allocation_run_ms\/p99":6.12036608,"frameworks\/cassandra-bcms-principal\/messages_received":640.0,"master\/gpus_total":0.0,"master\/task_failed\/source_slave\/reason_executor_terminated":56.0,"master\/disk_revocable_percent":0.0,"master\/gpus_revocable_used":0.0,"allocator\/mesos\/offer_filters\/roles\/cassandra-role\/active":0.0,"system\/load_15min":3.03,"master\/valid_status_updates":1013471.0,"allocator\/mesos\/offer_filters\/roles\/slave_public\/active":27.0,"master\/messages_revive_offers":492656.0,"allocator\/mesos\/resources\/cpus\/total":896.0,"master\/tasks_error":34.0,"master\/invalid_framework_to_executor_messages":0.0,"master\/task_lost\/source_slave\/reason_executor_reregistration_timeout":1.0,"allocator\/mesos\/offer_filters\/roles\/*\/active":18.0,"frameworks\/dcos_marathon\/messages_received":1935755.0,"allocator\/mesos\/resources\/disk\/offered_or_allocated":140904.0,"system\/mem_free_bytes":44155908096.0}

the command:
docker run --name=telegraf -v /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf -v /var/run:/var/run -p  9273:9273 telegraf:1.7

**Comment by orientzc** [comment]
the log from --test and the output from the mesos api match，but the metrics(prometheus_client) from --test and the output from mesos api not match.

**Comment by glinton** [comment]
Are you checking the same prometheus server that you have configured in your `telegraf.conf`?

**Comment by orientzc** [comment]
Sorry. i am sorry for late reply. i donnt know what can i do. i am sorry.
the prometheus_client in telegraf,conf:
[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  expiration_interval = "60s"
  string_as_label = true

and as is said above, the output from --test and the output from the mesos api match, but the /metrics and the output from --test/mesos api not match.
what can i do?Thanks.

**Comment by orientzc** [comment]
i storage the data in prometheus. and i find the losted metrics such as the mesos_master_cpus_total from the /metrics is shown at some time. so Most of the time, the losted metrics donnt appear. but once in a while, the losted metrics appear.
![image](https://user-images.githubusercontent.com/17718632/43571402-7460ecf8-966f-11e8-8098-eaa4e0f74210.png)

**Comment by orientzc** [comment]
@glinton Could you help me?

**Comment by danielnelson** [comment]
@orientzc Can you attach the output of the `--test` command and the the data on the prometheus endpoint `curl http://localhost:9273/metrics` as text files?

**Comment by orientzc** [comment]
@danielnelson Thanks very much.
the output of the --test command:
[test.txt](https://github.com/influxdata/telegraf/files/2272665/test.txt)
the data on the prometheus endpoint:
[metrics.txt](https://github.com/influxdata/telegraf/files/2272667/metrics.txt)

**Comment by danielnelson** [comment]
Just to make sure we are looking at the same issue can you confirm that this is an example of the issue from your test data:  in the prometheus output `mesos_master_cpus_total` has only two series and the expectation is that their should be a third?:
```
# HELP mesos_master_cpus_total Telegraf collected metric
# TYPE mesos_master_cpus_total untyped
mesos_master_cpus_total{host="dcos62",role="master",server="xx.xx.xx.xx",state="standby",url="http://xx.xx.xx.xx:5050"} 0
mesos_master_cpus_total{host="dcos62",role="master",server="xx.xx.xx.xx",state="standby",url="http://xx.xx.xx.xx:5050"} 0
```

**Comment by danielnelson** [comment]
What is your agent interval set to?
```
[agent]
  interval = "10s"
```

**Comment by orientzc** [comment]
my agent interval set to 60s:
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

**Comment by danielnelson** [comment]
I think it is possible that the metrics are expiring between collections.  Can you try doubling the expiration_interval:
```toml
[[outputs.prometheus_client]]
listen = ":9273"
path = "/metrics"
expiration_interval = "2m"
string_as_label = true
```

**Comment by orientzc** [comment]
if the solustion works, there will be other promblems. if 2m, the output of the other input plugins of telegraf will be wrong. for example, the input_plugins statsd is set to 1m, but the output_plugins prometheus_client is set to 2m. the data is wrong. Right?

**Comment by danielnelson** [comment]
The expiration_interval is the amount of time until non-updated metrics are removed from the prometheus output.  So if the statsd input stops updating a metric it will remain for 2 minutes with the last value before disappearing from the page, but if the metric is updated it will still update.

**Comment by orientzc** [comment]
sorry. i edit the expiration_interval = "2m", but the result is same. a part of metrics that is same as "60s" losted.

**Comment by danielnelson** [comment]
If setting `expiration_interval` higher did not help then I'm not sure what the cause is.  I'm also confused with the error message, this warning show only be shown if one of the masters values does not start with `http://` or `https://`, which your example does.  Can you upload your full config?

**Comment by orientzc** [comment]
my full config? my telegraf config?
[telegraf.txt](https://github.com/influxdata/telegraf/files/2300968/telegraf.txt)

**Comment by danielnelson** [comment]
Can you try setting timeout in the mesos plugin to `5000` and see if that has any effect?

**Comment by orientzc** [comment]
ok. yeah. it work. Thanks very much. 
and it because connect timeout? guess?

**Comment by danielnelson** [comment]
Interesting, the mesos input uses the [/metrics/snapshot](https://mesos.apache.org/documentation/latest/endpoints/metrics/snapshot/) endpoint and it says this about the timeout query parameter:

> The optional query parameter ‘timeout’ determines the maximum amount of time the endpoint will take to respond. If the timeout is exceeded, some metrics may not be included in the response.

It seems that this is a "soft" timeout that can cause the endpoint to return a partial payload.  We will investigate if there is a way we can detect if this has occurred and perhaps we can show some sort of warning.

**Comment by orientzc** [comment]
Thanks very much. and your attitude to warn encouraged me. Good Luck for us.
