### ISSUE TITLE
Support for parsing key-value pairs in logparser/tail input plugin (grok data format)

### ISSUE THREAD

**Issue by leonboot** [influxdata/telegraf#4466]
### Proposal:

I have a log file that I'm parsing using the logparser input plugin, which contains a number of key-value pairs. I'd like to use those pairs as tags for my influx message. As far as I know, it's not possible using just grok patterns to do this.

### Current behavior:

In this case, I'm trying to process log lines from the mail log. This log contains lines like these:

```
Jul 25 11:46:20 vps04 courier-imapd: LOGIN FAILED, method=PLAIN, ip=[::ffff:6.66.6.66]
Jul 25 11:46:24 vps04 courier-pop3d: LOGIN, user=user@domain.com, ip=[::ffff:11.22.33.44], port=[55000]
Jul 25 11:46:35 vps04 courier-imapd: LOGIN FAILED, method=PLAIN, ip=[::ffff:6.66.6.66]
Jul 25 11:46:36 vps04 courier-pop3d: LOGIN, user=user@someotherdomain.com, ip=[::ffff:22.33.44.55], port=[50000]
Jul 25 11:46:36 vps04 courier-pop3d: LOGIN, user=user@yetanotherdomain.com, ip=[::ffff:33.44.55.66], port=[50001]
Jul 25 11:46:51 vps04 courier-imapd: LOGIN FAILED, method=PLAIN, ip=[::ffff:6.66.6.66]
```

I'm matching these lines with the following grok pattern:
```grok
%{SYSLOGTIMESTAMP:timestamp:ts-syslog} %{HOSTNAME:host} courier-%{WORD:daemon}: %{DATA:action}, %{GREEDYDATA:kv_pairs}
```

So, the first line would have timestamp = `Jul 25 11:46:20`, host = `vps04`, daemon = `imapd`, action = `LOGIN FAILED` and kv_pairs = `method=PLAIN, ip=[::ffff:6.66.6.66]`.

### Desired behavior:

It'd be great if there was a sort of key-value modifier which would split up the string into an collection of tags. Logstash allows for this using filters: https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html

In the aforementioned example, I would like to end up with two tags, method = `PLAIN` and ip = `::ffff:6.66.6.66`.

**Comment by danielnelson** [comment]
I believe this would be covered by https://github.com/influxdata/telegraf/issues/4427 + https://github.com/influxdata/telegraf/issues/4428.  First you would collect the key/value pairs as a string field and then use the parser processor with the logfmt parser to expand the new fields.

**Comment by glinton** [comment]
Good catch, it seemed to sound familiar.
