### ISSUE TITLE
OAuth2 Authentication for HTTP Output plugin

### ISSUE THREAD

**Issue by vikrant6** [influxdata/telegraf#4468]
## Feature Request
OAuth2 Authentication for HTTP Output plugin
Opening a feature request kicks off a discussion.

### Proposal:
It will be useful to add OAuth2 support on the output plugin like http which can also reuse a token before the  expiry.
### Current behavior:
Only Basic authentication is supported.
### Desired behavior:
Support for OAuth2
### Use case: [Why is this important (helps with prioritizing requests)]
Most corporations already have OAuth2 ID providers in place and the security review boards wants to integrate the best authentication available.

**Comment by russorat** [comment]
@vikrant6 thanks for opening this issue. Is there a specific OAuth2 provider you are using?

**Comment by powersj** [comment]
Closing as a part of #9138
