### ISSUE TITLE
Ability to specify multiple certs for multiple urls in inputs.prometheus plugin?

### ISSUE THREAD

**Issue by Miheer-Bavare-ck** [influxdata/telegraf#4474]
In the inputs.prometheus plugin, is it possible to specify tls_ca, tls_cert, and tls_key for different url's? We need to scrape metrics from different url's that require different tls certs. Ideally, it would be nice to have an array of objects where it is something like [{url: <>, tls_ca: <>...}, {...} ].

**Comment by glinton** [comment]
Would you like to make a PR with this functionality?

**Comment by glinton** [comment]
Actually, a better solution is to configure one input for each host/cert combo, this will keep the config more simple and cleaner.
