### ISSUE TITLE
Performance Degradation for Wavefront output

### ISSUE THREAD

**Issue by PhoenixRion** [influxdata/telegraf#4478]
### Relevant telegraf.conf:
[[outputs.wavefront]]
host = "internal"
port = 2878
convert_paths = true
tagexclude = ["a", "b", "c", "c"]

### System info:
Telegraf > 1.5.3 (I tested 1.6.0, 1.6.4, 1.7.1 and 1.7.2 all comparable results)
Centos 7.3 
WF Proxy 4.27 (separate host)

### Steps to reproduce:
1. Install telegraf 1.5.3 with WF plugin to get baseline values for "internal.write.write.time.ns"
2. Install telegraf > 1.5.3
3. Observe values for "internal.write.write.time.ns" with no change to config

### Expected behavior:
Values should remain comparable across version upgrades (~10%)

### Actual behavior:
Values increased up to ~350%

**Comment by danielnelson** [comment]
Is there elevated CPU usage as well?

cc @puckpuck

**Comment by puckpuck** [comment]
@PhoenixRion I believe you are working with Wavefront customer support on this as well.  They have identified some irregularities with a greater # of metrics written, as well as some other potential networking issues on your side during your testing.  If you can ensure you have ironed out the networking issues, and can keep the # of metrics written consistent between telegraf versions and test again that would be great.

We have done some internal testing between versions on our own and have not noticed any longer write times with versions later than 1.5.3.

**Comment by danielnelson** [comment]
I'm going to close as it doesn't sound like this was an issue in the Wavefront output.
