### ISSUE TITLE
[Feature] - Plugin collect datas from mysql query

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/telegraf#448]
Hi Team,

An usefull feature will be to have a mysql_query plugin which will be able to run an provided mysql query (returning 1 field only) against one mysql database for store result in influxdb. 

See bellow an idea of the config of this plugin which could be present in telegraf.conf:

[mysql_query]
query=["mysqlhost;mysqluser;mysqlpwd;mysqlquery;measurementinfluxdb"]
query=["mysqlhost;mysqluser;mysqlpwd;mysqlquery;measurementinfluxdb"]

Requirement for this plugin : 
- have a mysql access to the database
- the query must return only 1 field for be able to post return to influxdb

The goal : 
- Able to get data metrics from mysql engine to be able to inject same on influxdb
- Able to set several query "subsection" inside this plugin
- Able to inject those datas into an defined measurement per query (using the database/user/pwd influxdb defined in the main telegraf section)
- Able to provide an mysql query having simple or double quote inside the query

Of course homemade script is doing well the job but if you would provided an centralised monitoring based on the TICK stack, i think this type of plugin will be usefull.

Wanted to share this idea and having discussion around it.

Thanks,
Julien.

**Comment by sparrc** [comment]
Sounds good, thanks for the detailed suggestions Julien, could you put this comment within the generic db query plugin case? (here: https://github.com/influxdb/telegraf/issues/352)

**Comment by sparrc** [comment]
closing in favor of #352

**Comment by tttMelody** [comment]
how is the progress?
