### ISSUE TITLE
[Bug] Win Perf metrics are not written with interval TS

### ISSUE THREAD

**Issue by sbengo** [influxdata/telegraf#4487]
Hi,

We have been testing Telegraf for retrieve metrics on Windows and we have seen that points on the DB are not written with the same difference time.

It seems to happen on all `win_perf` metrics

### Relevant telegraf.conf:

````
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = 'C:\Program Files\Telegraf\telegraf.log'
  omit_hostname = false
````

### System info:

Windows Server 2008 R2 Enterprise
Telegraf v1.7.0 (git: release-1.7 f4d22dd4)

### Expected behavior:

Points are written with a TS difference of 60 seconds and written on XX:00

### Actual behavior:

Points are written with a difference more and less than 60 seconds:

TS | Elapsed from before Point
-- | --
1532834460000000000,00 | 60
1532834520000000000,00 | 59
1532834579000000000,00 | 61
1532834640000000000,00 | 59
1532834699000000000,00 | 61
1532834760000000000,00 | 59
1532834819000000000,00 | 61

The following Graph shows the `internal - gather_time` and the `count of single field`, both metrics grouped by time (60s):

![image](https://user-images.githubusercontent.com/13196237/43388871-9aad09aa-93ea-11e8-85ca-cfca9e276f9f.png)

**Comment by danielnelson** [comment]
By default metrics are rounded to the nearest second, so it looks like sometimes the plugin is taking over .5 seconds and being rounded up one second.  You could consider using the `precision` option if you want to force the values into 10s multiples:
```
precision = "10s"
```
