### ISSUE TITLE
Elasticsearch 6 lost some attribute/tags in _nodes api

### ISSUE THREAD

**Issue by bbfoto** [influxdata/telegraf#4493]
We just noticed in our automated es dashboards, that our shiny new es6 cluster doesn't distinguish between data and master nodes.

traced it down to I suspect a breaking change on es side that affects the way es telegraf plugin is tagging metrics...
 
in line 30, `Attributes map[string]string `json:"attributes"`` seems to not work anymore.
I feel this kind of has a vague reference to it. 
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/breaking_50_settings_changes.html#_node_attribute_settings

Looking at es 1.x results vs 6.x results, I think the solution might be to instead of using 	
Attributes map[string]string `json:"attributes"`
to attributes or roles depending on es version...
in the es6 _nodes result I have the following for a master
```
    "roles" : [
        "master",
        "ingest"
      ],
```
and the following for a datanodes
 ```
    "roles" : [
        "data",
        "ingest"
      ],
```

there is no attributes{} section in my es6 _nodes result.

maybe also of interest. I find in both es1.x and es6.x clusters I do have the following subset of settings.cluster
```
        "node" : {
          "data" : "true",
          "name" : "<human_readable_hostname>",
          "master" : "false"
         },
```

I think either node or roles would work for the original intent of attributes.

**Comment by danielnelson** [comment]
related: #3630

**Comment by dupondje** [comment]
Which attribute/tags are lost?

I compares ES 5 and ES 6, but they seem both similar.

For the master vs data nodes:
https://github.com/dupondje/telegraf/commit/ae167922ed8542741616c9dde54f3de1c317b56e

I'll get this merged asap.

**Comment by glinton** [comment]
@bbfoto have you tried again with [a nightly build](https://github.com/influxdata/telegraf#nightly-builds) since #6064 was merged

**Comment by bbfoto** [comment]
will give it a try.

**Comment by sjwang90** [comment]
@bbfoto has this problem been fixed? please closed if so or provide what error you are still receiving.
