### ISSUE TITLE
StatsD input - Error: splitting ':', Unable to parse metric

### ISSUE THREAD

**Issue by waldauf** [influxdata/telegraf#4495]
### Relevant telegraf.conf:
```
cat etc/telegraf/telegraf.conf | grep -v "#\|^$"
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

 [[outputs.file]]
   files = ["stdout", "/tmp/metrics.out"]
    
 [[inputs.statsd]]
   protocol = "tcp"
   max_tcp_connections = 250
   tcp_keep_alive = false
   service_address = ":8125"

 [[inputs.statsd]]
   protocol = "udp"
   max_tcp_connections = 250
   tcp_keep_alive = false
   service_address = ":8125"
```

### System info:
```
$ uname -a
Linux vncub0625 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$ telegraf version
Telegraf v1.7.2 (git: release-1.7 c6feb056)
```

### Steps to reproduce:

1. Run telegraf daemon with above mentioned setting
2. Run `journalctl -fu telegraf`
3. Connect with `netcat` to telegraf and send some message `echo "process_cpu,host=hostname,tagkey=tagvalue field=0 1533040204" | netcat localhost 8125`

### Expected behavior:
Take new metric and record it to InfluxDB (in my case I just print it to stdout because tuning).

### Actual behavior:
I get this message:
```
Jul 31 15:02:56 vncub0625 telegraf[21662]: 2018-07-31T13:02:56Z E! Error: splitting ':', Unable to parse metric: process_cpu,host=hostname,tagkey=tagvalue field=0 1533040204
```
... I'm confused because I' still getting error message _Error: splitting ':'_ but in my metric is any colon.

Can I ask you for help, please?

**Comment by danielnelson** [comment]
It looks like you are sending InfluxDB line protocol to the statsd input, but this input accepts only statsd input: `<metricname>:<value>|<type>`.

Instead you can use the socket_listener input to write line protocol with the default `data_format = "influx"` option.

**Comment by waldauf** [comment]
Hmmm... now I'm feeling like Eeyore because I didn't realize that StatsD use another data format. Thx for your answer and tip.
