### ISSUE TITLE
Win_perf_counters plugin regex doesn't work for instances that have back slashes

### ISSUE THREAD

**Issue by jedthe3rd** [influxdata/telegraf#4499]
### Relevant telegraf.conf:
```
[[inputs.win_perf_counters]]
  UseWildcardsExpansion=true 
 [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Disk Read Time",
      "% Disk Write Time",
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "Current Disk Queue Length",
      "Avg. Disk sec/Read",
      "Avg. Disk sec/Write"
    ]
    Measurement = "win_disk"
    IncludeTotal=false
    WarnOnMissing=true
```
### System info:
Telegraf v1.7 - with changes (not affecting this problem)
Windows Server 2012 R2

### Steps to reproduce:

1. Get a system that has logicaldisk instances that are path names.
2. Run telegraf with the above config input.
3. Check output and you will see the instance and object for the path name instances are wrong.

### Expected behavior:
`\BOWSQLTST23A\LogicalDisk(E:\Data\Disk1)\Disk Reads/sec -> "instance":"E:\\Data\\Disk1" "objectname":"LogicalDisk"`

### Actual behavior:
`\BOWSQLTST23A\LogicalDisk(E:\Data\Disk1)\Disk Reads/sec -> "objectname":"Disk1)"`

### Additional info:
Here is the fix for this from my testing: https://gist.github.com/jedthe3rd/4a361cc19ac4cfd4ccf7bf7547107ead

Relevant regex tests:
https://regex101.com/r/GAnd0s/2
https://regex101.com/r/GAnd0s/3

**Comment by danielnelson** [comment]
cc @vlastahajek

**Comment by jedthe3rd** [comment]
Found another edge case introduced by my new regex. \BOWSQLTST23A\MSSQL$BOMSSTEST19A:Deprecated Features(sp_configure 'ft crawl bandwidth (max))\usage

`\\(.*)\\([^()]*)\((.*)\)` is the fixed regex

**Comment by vlastahajek** [comment]
Thanks for discovering this bug. It is always surpsing what kind of text instance name could be :-).
However, regexp matching is a bit complicated, because the instance part is optional. 

Even though playing with regexp if fun, regexp matching became too complex and slow, so I replaced it with a simple substring searching. Benchmark showed it is 40x faster than regexp.
