### ISSUE TITLE
[Feature Request] FreeBSD Port

### ISSUE THREAD

**Issue by ruudboon** [influxdata/telegraf#450]
Telegraf compiles nicely on FreeBSD now (#355)
Unfortunately there isn't a port available in the FreeBSD ports tree. Would be a great feature if a port with proper startup scripts etc comes available.
Unfortunately I don't have the skills (yet) to create a port but I if there's anything I can do to realise this please let me know.

**Comment by ruudboon** [comment]
Thumbs up for @cheffo https://github.com/cheffo/FreeBSD-Ports/tree/master/net-mgmt/telegraf

**Comment by sparrc** [comment]
cool! I'm going to close this as there are no plans for influx to maintain FreeBSD ports ourselves
