### ISSUE TITLE
Question about autoupdate feature for telegraf agent

### ISSUE THREAD

**Issue by santakd** [influxdata/telegraf#4500]
## Feature Request
Question about autoupdate feature for telegraf agent

### Proposal:
It will be very helpful if telegraf agent can autoupdate based on a feature flag or other criteria

### Current behavior:
All the servers have to be manually updated

### Desired behavior:
Based on the flag, agent can autoupdate 

### Use case: [Why is this important (helps with prioritizing requests)]
This will help with the maintenance and ensure that the agent is always updated.

**Comment by danielnelson** [comment]
Thanks for the suggestion @santakd, however I don't think this is a feature we would be very likely add into Telegraf.  I recommend using an separate administration tool, such as ansible, to update and deploy new versions to your servers.

**Comment by santakd** [comment]
Thank you @danielnelson
