### ISSUE TITLE
Telgegraf make fails

### ISSUE THREAD

**Issue by klashagel** [influxdata/telegraf#4504]
Not sure if this is a telegraf issue or a Golang issue, but for me its strange as it has worked perfectly before. I have scripted a fresh installation of Go, Influxdb and Telegraf on Ubuntu 18.04. Last in the script im trying to build Telegraf with my go plugin, but it fails with the message.

```
dep ensure -vendor-only
make[1]: dep: Command not found
Makefile:36: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2
```
I have also tried to build without the plugin , but still fails with same message.

Im Using 
`go version go1.10.1 linux/amd64`

Go env variables
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ge/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ge/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build847946735=/tmp/go-build -gno-record-gcc-switches"
```

Any ideas?

**Comment by glinton** [comment]
You will need to install dep 0.4.1 from [their release page](https://github.com/golang/dep/releases/tag/v0.4.1) and ensure it is on your PATH.

**Comment by klashagel** [comment]
Thanks for pointing me in the right direction. Installed dep from [Go dependency management tool](https://github.com/golang/dep) which also seems to be working
