### ISSUE TITLE
Monitoring host network does not work while the networking of container is not host

### ISSUE THREAD

**Issue by amiraliucsc** [influxdata/telegraf#4505]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
I am running Telegraf 1.7 as a docker container. I have a network defined which both telegraf and influx are using it. When I mount /proc/net/dev inside the container in /rootfs/proc/net/dev, that files only contains loopback and one more interface. But I need to pass all the information of the host. If I do cat /proc/net/dev in the host, I see all the interfaceses wherease if I cat /rootfs/proc/net/dev I see only one interface beside loopbak. 

### Desired behavior:

I would like to see all the interfaces in the docker container. 

### Use case: [Why is this important (helps with prioritizing requests)]

To run Telegraf as docker and be able to collect network metrics of the host

**Comment by glinton** [comment]
This is a network namespace limitation, you will need to use `--net=host` on your telegraf container in order to monitor host interfaces. [see here for similar question](https://github.com/moby/moby/issues/13398#issuecomment-104456833)
