### ISSUE TITLE
Telegraf RPM install script can't detect Suse 15/SLE 15

### ISSUE THREAD

**Issue by chrmeyer** [influxdata/telegraf#4507]
### Relevant telegraf.conf:
n/a
### System info:

Tested with telegraf-1.7.2-1.x86_64 on SLE15

### Steps to reproduce:

Install Telegraf RPM under SLE 15

### Expected behavior:
Telegraf service is available in systemd
### Actual behavior:
telegraf.service is not available in systemd
### Additional info:
It seems that the telegraf RPM install script only tests for the path "/etc/SuSE-release" to detect if it's on Suse OS. Under SLE15 the path do not longer exist. You should better aditional test for content in /etc/os-release.

**Comment by powersj** [comment]
Hi,

I have a PR up at https://github.com/influxdata/telegraf/pull/10570 with a change. I know there can still be an issue with the dependency but wanted to let you know this part is getting looked at.

Thanks!
