### ISSUE TITLE
 telegraf must not log haproxy password in /var/log/messages when unable to connect.

### ISSUE THREAD

**Issue by rohasharma** [influxdata/telegraf#4509]
### Relevant telegraf.conf:
In telegraf conf the connection is created using:
[[inputs.haproxy]]
servers = [ "http://haproxy:<Password>@<Node-IP>:<PORT>",]

### System info:
OS : Red Hat Enterprise Linux Server release 7.4 (Maipo)
Telegraf version  : Telegraf v1.6.0

### Steps to reproduce:

1. Change the HAPROXY Pasword (Invalid) in telegraf.conf and restart telegraf service.
2. View /var/log/messages and check for message stating "Unable to connect "URL:PASSWORD" where password is in clear string format.

### Expected behavior:
1. Password should not be visible in /var/log/messages

### Actual behavior:
1. Password in clear string is visible.

### Additional info:
# snippet from /var/log/messages

Jul 27 14:30:03 <Node Name> telegraf: 2018-07-27T21:30:03Z E! Error in plugin [inputs.haproxy]: Unable to connect to haproxy server 'http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv': Get http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv: dial tcp <IP>:<Port>: getsockopt: no route to host
Jul 27 14:30:13 <Node Name> telegraf: 2018-07-27T21:30:13Z E! Error in plugin [inputs.haproxy]: Unable to connect to haproxy server 'http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv': Get http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv: dial tcp <IP>:<Port>: getsockopt: no route to host
Jul 27 14:30:23 <Node Name> telegraf: 2018-07-27T21:30:23Z E! Error in plugin [inputs.haproxy]: Unable to connect to haproxy server 'http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv': Get http://haproxy:<Clear Text Password>@<IP>:<Port>/;csv: dial tcp <IP>:<Port>: getsockopt: no route to host

**Comment by danielnelson** [comment]
As an aside, is it a requirement for you to pass the credentials in the userinfo section of the URL?  Maybe we should add a username and password option that would use HTTP Basic Auth.
