### ISSUE TITLE
add cmdline as an process tag

### ISSUE THREAD

**Issue by yumaojun03** [influxdata/telegraf#4512]
## Feature Request

add cmdline as process tag, when grafana can use it like (tag(cmdline))

### Proposal:

the process cmdline information can find in proc's cmdline file, can extract it

### Current behavior:
I use pattern to match my java process,  here i have 5 java, use process_name can't distinguish them, but the procs has cmdline can. like

```sh
[root@event01 ~]# cat /proc/14441/cmdline
/root/software/jdk1.8.0_171/bin/java-jar/opt/jwb/iot-etl/iot-etl.jar
```

```sh
[root@event01 ~]# telegraf --config /etc/telegraf/telegraf.conf --input-filter procstat --test
> procstat,host=event01,pattern=iot,process_name=java ...
> procstat,host=event01,pattern=iot,process_name=java ...
> procstat,host=event01,pattern=iot,process_name=java ...
```

### Desired behavior:

I want to use cmdline as an tag to distinguish them

### Use case: [Why is this important (helps with prioritizing requests)]

if process use vm to run like (java, python, nodejs, ...) has this problem

**Comment by danielnelson** [comment]
Thanks for the feature request, we have an existing issue here: https://github.com/influxdata/telegraf/issues/1873.
