### ISSUE TITLE
CloudWatch Input external Id

### ISSUE THREAD

**Issue by kwanjack** [influxdata/telegraf#4518]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add external Id as a param to Cloudwatch input

### Current behavior:
Currently the existing options do not support role_arn that require an external Id.  External Id is an optional security field that aws supports. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

### Desired behavior:
Support external_id so a role_arn with an external id can still be authorized when assuming role.

### Use case: [Why is this important (helps with prioritizing requests)]

This is necessary for when one aws account user needs to pull cloudwatch metrics from another aws account in a secure manner. If the Cloudwatch owner decides to grant an arn_role with an external Id, currently telegraf has no way to reach out to it.

Example config:
[[inputs.cloudwatch]]
role_arn = "arn:aws:iam::XXXXXXXX:user"
external_id = "external_id_here"

Alternatively it can be supported by the shared_credentials file, which might look something like:
[default]
aws_access_key_id = XXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
aws_role_arn = arn:aws:iam::XXXXXXXX:user:user
aws_external_id = external_id_here

**Comment by sspaink** [comment]
The cloudwatch plugin has recently been updated to allow using a shared credentials file, it seems like this solves this request.
