### ISSUE TITLE
SQL Server, "awe_allocated_kb" not used from sys.dm_os_memory_clerks

### ISSUE THREAD

**Issue by weiln12** [influxdata/telegraf#4523]
### Relevant telegraf.conf:

[[inputs.sqlserver]]
 servers = [
   "Server=(sqlserverinstance);Port=1433;User Id=TelegrafUser;Password=TelegrafUser;app name=telegraf;log=1",
 ]
query_version = 2

### System info:

Telegraf for Windows and Linux, version 1.7.2 (git: release-1.7 c6feb056)

### Steps to reproduce:

1. Turn on SQL Server monitoring using queries v2

### Expected behavior:
The data point's for "sqlserver_memory_clerks" do not include the "awe_allocated_kb" value.

SQL Server uses AWE when "lock pages in memory" is used, which is a preferred setting for standalone SQL Server instances. Omitting the "awe_allocated_kb" from the result returns incorrect values. I specifically tested this for "Buffer Pool" results.

### Actual behavior:
The memory clerks should include "awe_allocated_kb" to account for instances utilizing "lock pages in memory".

### Additional info:

The following code will fix the issue. I have tested this on SQL Server versions 2008R2 through 2016 and verified the results are correct. The lines below should be used instead of lines 343-346 in the sqlserver.go file here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go

The changes are in bold, adding " **+ mc.awe_allocated_kb**".

IF CAST(LEFT(CAST(SERVERPROPERTY('productversion') as varchar), 2) AS INT) > 10 -- SQL Server 2008 Compat
    SET @SQL = REPLACE(REPLACE(@SQL,'{pages_kb}','mc.pages_kb **+ mc.awe_allocated_kb**'),'"','''')
ELSE
    SET @SQL = REPLACE(REPLACE(@SQL,'{pages_kb}','mc.single_pages_kb + mc.multi_pages_kb **+ mc.awe_allocated_kb**'),'"','''')

**Comment by danielnelson** [comment]
@m82labs Can you review this change?

**Comment by m82labs** [comment]
I think this looks like a good change. I would like to check it on Azure managed instances before making the change though.
