### ISSUE TITLE
Net plugin bytes sent/recieved resets to 0 if host reboots

### ISSUE THREAD

**Issue by douglasg14b** [influxdata/telegraf#4531]
## Bug? Maybe feature request?

On freebsd.

### Current behavior:

Collecting Net data `bytes_sent` and `bytes_recv` go sup over time, as expected. However when the host reboots these are set to 0 and go up again as data is sent/recieved.

### Desired behavior:

The `bytes_sent` and `bytes_recv` maintain their previous values and continue to go up.

### Use case:

When this reset to 0 is completely breaks any total bandwidth usage queries as it relies on the first vs last `bytes_sent` and `bytes_recv` for the timerange to get a total. 

Ie. start: 100 bytes, end: 4000 bytes. Total for range is 3900 bytes. If it was to reset to 0 in the middle of a daterange you get negative bandwith usage using this.

**Comment by voiprodrigo** [comment]
It’s the OS that resets the counter. Use negative difference or non negative derivative for calculations. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by douglasg14b** [comment]
@voiprodrigo Can you explain what you mean by a non-negative derivative to avoid something like this. Do you have an example? I've been struggling to figure this out for weeks, and have not been able to find an answer.... I'm pretty desperate at this point.


**Example (This uses derivative):**

![image](https://user-images.githubusercontent.com/1400380/43858460-f888a042-9b02-11e8-8c8c-31edb1363d9a.png)



**Queries:**

`SELECT derivative(mean("bytes_recv"), 1s)*8  FROM "net" WHERE ("interface" = 'em4') AND $timeFilter GROUP BY time($__interval) fill(null)`

`SELECT derivative(mean("bytes_sent"), 1s)*8 FROM "net" WHERE ("interface" = 'em4') AND $timeFilter GROUP BY time($__interval*2) fill(null)`

**Comment by douglasg14b** [comment]
Oh, nevermind `non_negative_derivative` was added here https://github.com/influxdata/influxdb/pull/2569

**Comment by douglasg14b** [comment]
Oh I see, I can use `SELECT non_negative_difference("bytes_recv") FROM "net" WHERE ("interface" = 'em4') AND $timeFilter` to get the difference. 

Though it does make sparklines look terrible. 
![image](https://user-images.githubusercontent.com/1400380/43859639-0f734c82-9b06-11e8-9237-92670d3ae697.png)

**Comment by voiprodrigo** [comment]
add a last() to bytes_recv within non_negative_difference() and group by time. The larger the time value, the less resolution you'll see in the lines.
