### ISSUE TITLE
Telegraf collects data before rounded interval time

### ISSUE THREAD

**Issue by martin2250** [influxdata/telegraf#4538]
### Relevant telegraf.conf:
```
[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  precision = "s"
[[inputs.http]]
  urls = [
    "http://192.168.2.82/metrics"
  ]
  interval = "10s"
```
### System info:
`Telegraf v1.6.4 (git: release-1.6 b24e8648)`
running on a raspberry pi with a up-to-date installation of `Raspbian GNU/Linux 9 (stretch)`
both InfluxDB and Telegraf are running in docker containers on the same system.
### Steps to reproduce:
1. run telegraf in a docker container with a rounded interval
2. run apt-get update && upgrade on the host and reboot

(I admit this issue is probably pretty hard to reproduce)
### Expected behavior:
(with the above config) data is written at the 10, 20, 30 second marks
### Actual behavior:
some points are written one second before the correct time, appearing as gaps when grouping by time(10s):
```
2018-08-09T20:46:10+02:00 49.984
2018-08-09T20:46:00+02:00 49.98
2018-08-09T20:45:50+02:00 49.98
2018-08-09T20:45:39+02:00 49.978
2018-08-09T20:45:29+02:00 49.973
2018-08-09T20:45:19+02:00 49.982
2018-08-09T20:45:10+02:00 49.989
2018-08-09T20:45:00+02:00 49.981
2018-08-09T20:44:50+02:00 49.974
```
### Additional info:
Input plugin is http, fetching metrics from a website hosted in the same network by a microcontroller (which is able to handle more than 20x the number of requests).
The error occurs about every three to five minutes in irregular intervals. The logs of influxdb and telegraf show no signs of errors. This was never an issue before, it only occured since I rebooted the system six days ago after a few updates. Those shouldn't affect telegraf though as it's running in a docker container. The docker container was restarted automatically (--restart=unless-stopped). I'll upgrade to 1.7.4 and test if this still is an issue.

**Comment by danielnelson** [comment]
Does it help if you use `precision = "2s"` in the agent?

**Comment by danielnelson** [comment]
Yeah it works, in fact you must specify a constant.  It turns out though that if the value is unreadable that the default is 1s when the interval is 10s.

With a one second precision the interval would need to be off by at least half a second for the timestamp to round down.  When this happens does it happen straightway after restart or do you think Telegraf needs to be running for a long time in order to drift away from the proper time?

**Comment by martin2250** [comment]
It happened immediately after restarting six days ago.

**Comment by sspaink** [comment]
There has been significant improvements to Telegraf since this issue was made, I will be closing this issue for now, but if you are still having this issue please re-open and we can re-investigate.
