### ISSUE TITLE
Please stop using lsof to get TCP state

### ISSUE THREAD

**Issue by seanlook** [influxdata/telegraf#455]
In my environment, I have lots of tcp connections to serve. Telegraf use `lsof` to collect tcp state (`NETSTAT_README.md`), and I saw the lsof process is **always** running because too slow to get the results. 100% CPU used by lsof:

    PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                              
     6227 root      20   0 19140  11m  720 R 99.8  0.0   0:25.94 /usr/sbin/lsof -a -n -P -i tcp

I think `ss` is a great alternative to `lsof`.

**Comment by sparrc** [comment]
@seanlook what is your OS?

**Comment by sparrc** [comment]
Also I would like to know if Telegraf is erroring at all when this is happening, @seanlook can you provide telegraf logs?

**Comment by zstyblik** [comment]
> 2015/12/19 21:46:10 Error in plugin [netstat]: error getting net connections info: exec: "lsof": executable file not found in $PATH

**Comment by sparrc** [comment]
@zstyblik ...I don't think these are related issues...? Please open a new case and provide more details

**Comment by zstyblik** [comment]
@sparrc sorry, I misunderstood your sentence about erroring. Moving on.

**Comment by seanlook** [comment]
@sparrc CentOS 6.6. There's no any errors or warnnings in Telegraf log. When my system load is up, `/usr/sbin/lsof -a -n -P -i tcp` is slow ( 2 to 5 seconds)

**Comment by seanlook** [comment]
As @zstyblik memtioned, `lsof` is not installed default in every system, but `ss` does. (`netstat` is also slow in lots of tcp connection server

**Comment by sparrc** [comment]
closing as a won't fix for this repo, it should be opened in https://github.com/shirou/gopsutil
