### ISSUE TITLE
Option to only gather performance counters with non-0 values

### ISSUE THREAD

**Issue by perzizzle** [influxdata/telegraf#4557]
## Feature Request

In our environment, we create performance counters that are not necessarily ever written to. With Instances[*], these performance counters are gathered and written to influx. At scale this amounts to millions of points per day with no analytical value.

### Proposal:
Provide configuration toggle to only write non-0 values to influx.
### Current behavior:
n/a
### Desired behavior:
n/a
### Use case: 
Provide ability to only write data of value to end user.

**Comment by danielnelson** [comment]
Can you add some additional information about why you are creating performance counters without writing to them?  Would it be possible to add a list of instances or use [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options to trim the output?

**Comment by perzizzle** [comment]
It is possible for us to use instance to limit what's written but will require a bit of manual work. The empty performance counters is in part an idiosyncrasy of our legacy environment. We have a pool of queue readers and create a set of performance counters for each queue that is read. Its easiest to just create all counters on all queue reader servers rather than just create the ones that are used on each server.

**Comment by reimda** [comment]
I don't think a new telegraf setting is the right way to go for this feature request because it is a very application specific need. It should also not be too difficult to write a starlark processor script that checks for fields with zero value and drops them.
