### ISSUE TITLE
Push Error event as metric field

### ISSUE THREAD

**Issue by azhurbilo** [influxdata/telegraf#4563]
## Feature Request

Add ability to send Error event (during failed input plugin gather attempt: timeout / down target monitored service) as field to timeseries db

### Current behavior:

If Input plugin can not gather metrics we send only notice about it `AddError()` in log file

### Desired behavior:

Have ability to turn on (or make it as default behaviour) to send Error event as metric field.

### Use case: [Why is this important (helps with prioritizing requests)]

it's needed to calculate availability (SLO) % = `success events / total events`

**Comment by danielnelson** [comment]
You can use the `internal` plugin to send metrics about performance and errors.  Each plugin can also add custom metrics to this plugin, a good example of a plugin using this is the `http_listener` plugin.
