### ISSUE TITLE
Kafka output and consumer should support Kerberos Authentication 

### ISSUE THREAD

**Issue by ono760** [influxdata/telegraf#4568]
## Feature Request

Kafka Plugin Support Kerberos Authentication of Kafka Brokers

To implement security on kafka environments, currently have two options for authentication:
SSL and Kerberos. 

With SSL, certs expire on a timely manner, therefore,  kerberos authentication seems like the best option.

**Comment by russorat** [comment]
The current library we are using doesn't support Kerberos: https://github.com/Shopify/sarama/issues/934

Also, the other Go libraried for Kafka doesn't support them either: https://github.com/segmentio/kafka-go/issues/109

So we will need to find a Go library that supports it or implement it ourselves with something like https://github.com/jcmturner/gokrb5

**Comment by mayank-mahajan-guavus** [comment]
Hello @russorat ,
were you able to implement kerberos support for Kafka?
If yes, it would be great if you can guide me to the correct path.

**Comment by russorat** [comment]
Looks like this go client might support Kerberos: https://github.com/confluentinc/confluent-kafka-go

**Comment by danielnelson** [comment]
This library uses CGO, I'm not totally against it, but we would need to ensure that Telegraf can be built without any external C libraries or headers and we might want to not build it into the official packages.

**Comment by psilvaro** [comment]
Is there any plans to have this feature requested implemented in the near future?
Thanks

**Comment by danielnelson** [comment]
I'm not planning to implement this soon, but if someone is able to contribute support upstream to https://github.com/Shopify/sarama then I'm sure they would appreciate and I believe we could then roll it out fairly quickly in Telegraf.

**Comment by est** [comment]
I need this feature as well. Especially how to use GSSAPI and keytab

**Comment by russorat** [comment]
So looks like the upstream lib added support and the config options are here: https://github.com/Shopify/sarama/pull/1366/files#diff-b4bda758a2aef091432646c354b4dc59R532

@danielnelson what changes would we have to make to add support for this?

**Comment by sjwang90** [comment]
@pierwill will provide documentation to support Kerberos setup. 
@andrew-influx can support testing environment.

**Comment by ssoroka** [comment]
It looks like support for this in Sarama is [not currently functional](https://github.com/Shopify/sarama/issues?utf8=✓&q=is%3Aissue+is%3Aopen+kerberos)

While confluent-kafka-go supports kafka, it doesn't appear to support Kerberos auth (GSSAPI) for SASL.

I also found [a ruby gem that has GSSAPI support](https://github.com/zenchild/gssapi), but it also uses C bindings, which means that if we followed the same approach we would not be able to build support directly into Telegraf.

I think the best bet is probably to wait until Sarama fixes the issue. If you're waiting for this, something that might help is to contribute a docker-compose.yml that sets up an environment adequately mirroring yours so the people working on Sarama (and us) can have something to test against to ensure it's working and resolve the outstanding bugs. (I gave it a shot, but I'm getting kafka errors, probably due to some misconfiguration. I'm happy to share what I have if it helps).

**Comment by sjwang90** [comment]
Un-milestoning this issue until we work out one of the above alternatives.

**Comment by bigdatasunil** [comment]
What is the telegraf configuration for KAFKA GSSAPI Kerberos ??

**Comment by danielnelson** [comment]
We don't yet have support for GSSAPI in the kafka_consumer plugin.

**Comment by ssoroka** [comment]
SASL and GSSAPI are both supported now. I think this issue can be closed. Please reach back out if this is still a problem for you.

**Comment by bigdatasunil** [comment]
Hello,

I am eagerly waiting for this, could you please share the configuration for
this?? and steps.

Thanks & Regards
Sunil

**Comment by bigdatasunil** [comment]
Hello Steven Soroka,

I need this bit of urgency. Could you please share the telegraf
configuration.

Thank you in advance

**Comment by sjwang90** [comment]
@bigdatasunil 

Please see the [`outputs.kafka` readme](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/kafka#configuration). 

``` ## Optional SASL:
  ## one of: OAUTHBEARER, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
  ## (defaults to PLAIN)
  # sasl_mechanism = ""

  ## used if sasl_mechanism is GSSAPI (experimental)
  # sasl_gssapi_service_name = ""
  # ## One of: KRB5_USER_AUTH and KRB5_KEYTAB_AUTH
  # sasl_gssapi_auth_type = "KRB5_USER_AUTH"
  # sasl_gssapi_kerberos_config_path = "/"
  # sasl_gssapi_realm = "realm"
  # sasl_gssapi_key_tab_path = ""
  # sasl_gssapi_disable_pafxfast = false

  ## used if sasl_mechanism is OAUTHBEARER (experimental)
  # sasl_access_token = ""

  ## SASL protocol version.  When connecting to Azure EventHub set to 0.
  # sasl_version = 1

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  # data_format = "influx"
```

**Comment by glacieruk** [comment]
> SASL and GSSAPI are both supported now. I think this issue can be closed. Please reach back out if this is still a problem for you.

The config says it's experimental. Is GSSAPI supported or not? We want to know if this can be used as we're having an issue connecting Telegraf to Kafaka using Kerberos.

**Comment by douglasawh** [comment]
@ssoroka what steps are needed to not mark this as experimental?
