### ISSUE TITLE
SQL Server input plugin: Data File(s) Used Size (KB)

### ISSUE THREAD

**Issue by hulkk** [influxdata/telegraf#4569]
### Proposal:
Collect "Data File(s) Used Size (KB)" metric from SQL Server databases.
### Current behavior:
Currently the SQL Server Telegraf plugin only collects "Data File(s) Size (KB)" metric.
### Desired behavior:
Collect how much of the configured data files is used. The same metric is currently collected from transaction log files - "Log File(s) Used Size (KB)".
### Use case:
Enables the ability to monitor data file usage. Adds more value and context to the Data file size -metric when you know how much of the files are in use.

**Comment by danielnelson** [comment]
cc @m82labs

**Comment by hulkk** [comment]
According to my research it seems that database's used size information is not available in the master database. That information needs to be collected inside each database's sys.database_files view.

I've tested following query example with SQL Server 2014 and 2016.
```
IF OBJECT_ID('tempdb..#db_size_metrics') IS NOT NULL DROP TABLE #db_size_metrics

DECLARE @sql_command VARCHAR(500)

CREATE TABLE #db_size_metrics (
    [db_name] NVARCHAR(128), 
    [filegroup_id] INT, 
    [filegroup_size_mb] INT, 
    [filegroup_used_size_mb] INT
) 

SELECT @sql_command =  
    'USE [?] INSERT INTO #db_size_metrics([db_name], [filegroup_id], [filegroup_size_mb], [filegroup_used_size_mb])  
 
    SELECT 
        DB_NAME() AS db_name, 
        data_space_id AS filegroup_id,
        SUM(size)/128 AS filegroup_size_mb,
        SUM(FILEPROPERTY(name, ''SpaceUsed''))/128 as filegroup_used_size_mb
    FROM 
        sys.database_files
    WHERE 
        type = 0 -- include only data files
    GROUP BY 
        data_space_id'

EXEC sp_MSforeachdb @sql_command 

select * from #db_size_metrics

IF OBJECT_ID('tempdb..#db_size_metrics') IS NOT NULL DROP TABLE #db_size_metrics
```
To be able to query the required view inside user databases there is one new grant required:
```
USE [master]
GRANT CONNECT ANY DATABASE TO telegraf
```
Only drawback with the grant is that it was announced in SQL Server 2014. Earlier versions would require creating a user for login in each database.
```
USE [my_database]
GO
CREATE USER [telegraf] FOR LOGIN [telegraf]
GO
```

**Comment by m82labs** [comment]
While I understand the desire for this, I think it's just too heavy. Some people capture metrics at very high granularity (10-15 seconds) and running this query on some of my biggest production instances (largest by database count) can take upwards of 8 seconds.

**Comment by sspaink** [comment]
Closing because it seems to slow to retrieve, please re-open if you are still interested in this feature and have a quicker approach.
