### ISSUE TITLE
configurable timeout for plugin execution/plugin execution should timeout

### ISSUE THREAD

**Issue by zstyblik** [influxdata/telegraf#457]
Hello,

this is based on https://github.com/influxdb/telegraf/issues/455. I believe plugin execution should timeout after N seconds or at least print a warning. Timeout should be configurable and may be even set to null, never timeout, by default. But the following situation doesn't look good to me. I know this is a deliberate setup, but as https://github.com/influxdb/telegraf/issues/455 shows, it may happen to any other plugin. What do you think?

I've setup exec plugin like so:
```
[[exec.commands]]
command = "/tmp/test.sh"
name = "mytest"
interval = 10
```

`test.sh` is deliberately set to take long time like so:
```
#!/bin/sh
sleep 30
printf '{"foo": 30}'
```

And then, actually, this happens `SELECT * FROM exec_mytest_foo`:
```
2015-12-21T07:59:30Z
2015-12-21T08:00:00Z
2015-12-21T08:00:30Z
2015-12-21T08:03:30Z
2015-12-21T08:05:00Z
2015-12-21T08:05:30Z
2015-12-21T08:06:00Z
2015-12-21T08:08:30Z
2015-12-21T08:09:00Z
```

And the Telegraf's log:
```
2015/12/21 09:11:30 Gathered metrics, ({10s} interval), from 11 plugins in 30.002308938s
2015/12/21 09:11:40 Flushed 477 metrics to output influxdb in 16.592926ms
2015/12/21 09:12:00 Gathered metrics, ({10s} interval), from 11 plugins in 30.007831174s
2015/12/21 09:12:10 Flushed 477 metrics to output influxdb in 29.805966ms
2015/12/21 09:12:30 Gathered metrics, ({10s} interval), from 11 plugins in 30.004251556s
2015/12/21 09:12:40 Flushed 477 metrics to output influxdb in 31.94616ms
```

No warning or error what so ever. Everything is a okay which isn't exactly the truth :\

**EDIT**: tested with **Telegraf 0.2.4**

**Comment by sparrc** [comment]
good idea, this should be globally and individually configurable

**Comment by rubycut** [comment]
+1

**Comment by rubycut** [comment]
This should be done before 1.0.0

**Comment by sparrc** [comment]
I am going to mark this as closed because we now _do_ print out a warning when plugin execution time goes beyond the `interval` setting (as of 0.13.1)

If there is a need to set an explicit timeout other than the configured `interval` I'd be open to hearing reasons for that and opening a new feature request for that.

**Comment by rubycut** [comment]
@sparrc , in 0.13.1 exec plugin still has hard timeout on 5 sec value. This is big problem.

**Comment by sparrc** [comment]
exec plugin has it's own timeout setting now. `timeout = "5s"` is just the default.

I'll push a change to the README for the exec plugin to document that. But you can also see this option available if you run `telegraf --sample-config`
