### ISSUE TITLE
Input Plugin for Windows Event Log

### ISSUE THREAD

**Issue by endersonmaia** [influxdata/telegraf#4570]
## Feature Request

Since Telegraf 1.7 and it's syslog input plugin, I think Telegraf should also have a solution for Windows Event Log.

### Proposal:

Implement a input plugin using the [Windows Event Collector](https://msdn.microsoft.com/pt-br/library/bb427443(v=vs.85).aspx) implementation. 

That way, the telegraf would remotely subscribe to Windows Events.

### Current behavior:

Telegraf doesn't have a native input plugin for Windows Event Log, and the users need to do a lot of work to get these logs like installing agents (like NXlog) that could forward do syslog input plugin or using exec input plugin and scripts.

### Desired behavior:

To have an input plugin to collect Windows Event Log that could use [Windows Event Collector](https://msdn.microsoft.com/pt-br/library/bb427443(v=vs.85).aspx) without the need to install any third-part service or application to the Windows system.

### Use case: 

Windows's sysadmins that are trying to centralize logging storage and analysis with the TICK stack and other compatible Telegraf solutions.

**Comment by iserialize** [comment]
Iam currently pushing the windows event log data via a Task Scheduler job which is triggered when an event gets written in the event log. The job sends the event log to a powershell script which then write the data to influxdb using the line protocol.  With 1.7, we could potentially use the same method but write to telegraf (localhost) which could then proxy the request to influxdb.

It would be ideal to have a native solution though as the event log on a windows server has a lot of application level data which at a glance can provide an indication of a problem.

**Comment by cruscio** [comment]
I opened a similar feature request in - Windows Event Log Analytics #4525

**Comment by danielnelson** [comment]
Merging issue with #4525
