### ISSUE TITLE
Gather Kibana health metrics

### ISSUE THREAD

**Issue by yuriy-slobodchikov** [influxdata/telegraf#4576]
## Feature Request
 Kibana health check plugin
( @danielnelson )

Opening a feature request kicks off a discussion.

### Proposal:
Adding  Kibana health check plugin

### Current behavior:
No Kibana health check via localhost:5601/api/status
https://www.elastic.co/guide/en/kibana/6.3/access.html#status

### Desired behavior:
To have ability to get metrics and plugin health checks from json localhost:5601/api/status
For "state" also should be created additional state_code    (sometimes it is more convenient to have numeric thresholds in grafana)
transformation from 
"green" - 0
"yellow" - 1
"red" - 2
any other - 3

{
  "name": "my-kibana",
  "uuid": "e279c9b7-2125-436b-822e-75e3c179a79f",
  "version": {
    "number": "6.3.0",
    "build_hash": "c360fcacca5594000a2f7c80fe2dcaad5c7ee52c",
    "build_number": 17230,
    "build_snapshot": false
  },
  "status": {
    "overall": {
      "state": "green",
      "title": "Green",
      "nickname": "Looking good",
      "icon": "success",
      "since": "2018-06-28T13:16:31.537Z"
    },
    "statuses": [
      {
        "id": "plugin:kibana@6.3.0",
        "state": "green",
        "icon": "success",
        "message": "Ready",
        "since": "2018-06-28T13:16:31.537Z"
      },
     ...
    ]
  },
  "metrics": {
    "last_updated": "2018-08-21T10:41:51.024Z",
    "collection_interval_in_millis": 5000,
    "uptime_in_millis": 4656520644,
    "process": {
      "mem": {
        "heap_max_in_bytes": 208896000,
        "heap_used_in_bytes": 161749976
      }
    },
    "os": {
      "cpu": {
        "load_average": {
          "1m": 0.0029296875,
          "5m": 0.0146484375,
          "15m": 0.04541015625
        }
      },
      "cgroup": {
        "cpuacct": {
          "control_group": "/system.slice/kibana.service",
          "usage_nanos": 14313207367574
        },
        "cpu": {
          "control_group": "/system.slice/kibana.service",
          "cfs_period_micros": 100000,
          "cfs_quota_micros": -1,
          "stat": {
            "number_of_elapsed_periods": 0,
            "number_of_times_throttled": 0,
            "time_throttled_nanos": 0
          }
        }
      }
    },
    "response_times": {
      "avg_in_millis": 1,
      "max_in_millis": 1
    },
    "requests": {
      "total": 1,
      "disconnects": 0,
      "status_codes": {
        "200": 1
      }
    },
    "concurrent_connections": 1
  }
}

### Use case: [Why is this important (helps with prioritizing requests)]
It is usefull to have metrics not only for Elastic but also for Kibana itself.

**Comment by lpic10** [comment]
That definitely could be useful, but as a separated kibana plugin

**Comment by lpic10** [comment]
Ok, so I worked on a simple standalone kibana input plugin, I should open a PR later today or tomorrow

**Comment by sspaink** [comment]
Resolved with https://github.com/influxdata/telegraf/pull/4585
