### ISSUE TITLE
inputs.exe json plugin can't parse input with strings

### ISSUE THREAD

**Issue by ahb-sjsu** [influxdata/telegraf#4589]
### Relevant telegraf.conf:
[[inputs.exec]]
#   ## Commands array
commands = [
"/etc/telegraf/wae-telegraf-input.sh"
]
#   ## Timeout for each command to complete.
timeout = "5s"
#
#   ## measurement name suffix (for separating different commands)
name_suffix = "_waecollector"
#
#   ## Data format to consume.
data_format = "json"

### System info:

[Include Telegraf version, operating system name, and other relevant details]
# telegraf -version
Telegraf v1.5.3 (git: release-1.5 1e519698)
# cat /etc/redhat-release
CentOS release 6.9 (Final)

### Steps to reproduce:
1 (Does not work using string)
Given the following script:

# cat wae-telegraf-input.sh
#!/bin/bash
cat << EOF
{"wae-web-server-status":"running","last-collection-status":"failed"}
EOF

That generates VALID json:
{"wae-web-server-status":"running","last-collection-status":"failed"}

Yet, gives ERROR:
# telegraf -config telegraf.conf -test |grep wae
2018-08-23T22:58:22Z E! Error in plugin [inputs.exec]: exec: must have one or more fields

2 (Works when using int).
If I change the script so that there is an int rather than a string:
# cat wae-telegraf-input.sh
#!/bin/bash
cat << EOF
{"wae-web-server-status":1,"last-collection-status":1}
EOF

# telegraf -config telegraf.conf -test |grep wae
> exec_waecollector,host=DUKENECWNC02.cox.net wae-web-server-status=1,last-collection-status=1 1535064665000000000
 

### Expected behavior:
Parse strings
### Actual behavior:
ERROR
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Currently the JSON parser will only parse strings to tags using the `tag_keys` option.  However, keep in mind that our data model requires at least one field, so your original example with only strings is impossible to parse to a metric.

In the next release, 1.8.0, you will be able to use the new `string_keys` option to whitelist strings and add them as fields.  This was implemented in #4351.
