### ISSUE TITLE
Docker metrics missing from Input Plugin

### ISSUE THREAD

**Issue by teresaibarra** [influxdata/telegraf#4591]
### Relevant files:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker#metrics

###  Behavior:
We noticed that some metrics in the Docker Input Plugin were missing. After further investigation, it seems that the plugin may not be up-to-date with the Docker API.

It seems that `pool_blocksize` is no longer returned by the Docker API.

The below metrics are noted as unstable in the Docker docs and was the source of some confusion.
- DOCKER_DATA: `available`, `total`, `used`
- DOCKER_METADATA: `available`, `total`, `used`

These metrics are not being reported, possibly due to changes in Docker's response structure.
- DOCKER_CONTAINER_HEALTH: `health_status`, `failing_streak`
- DOCKER_CONTAINER_STATUS: `oomkilled`, `pid`, `exitcode`, `started_at`, `finished_at`

**Comment by n1b0r** [comment]
I'm also looking for `docker_container_status` metric which does not seem to be exported.

Is there any workaround ?

**Comment by danielnelson** [comment]
The `pool_blocksize`, `docker_data` and `docker_metadata` metrics require using the [devicemapper](https://docs.docker.com/storage/storagedriver/device-mapper-driver/) storage driver.

To see the `docker_container_health` metrics you must have a HEALTHCHECK defined on your container.  I have been using the tips from this page to add fake health checks to my containers for testing: https://ryaneschinger.com/blog/using-docker-native-health-checks/

The `docker_container_status` metrics will only be in 1.8.

@teresaibarra Does this explain all of the missing data?  I will update the README for this plugin with information about these requirements.

**Comment by teresaibarra** [comment]
It does! I'm checking up on this information for CircleCI's documentation on metrics, and that'd be super helpful :-) Thanks so much!

**Comment by danielnelson** [comment]
Changes to readme: 61e5d500baeefc32c51e449969584d6581ee4e1e

**Comment by triethuynh92** [comment]
I also can not get field `health_status (string)` from `docker_container_health` to visualize on Grafana. I use Influxdb and telegraf to get this.
Version:
Docker version 19.03.1, build 74b1e89
Telegraf 1.11.4 (git: HEAD d9ca76e4)

My config into telegraf.conf:

# Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"

  ## Set to true to collect Swarm metrics(desired_replicas, running_replicas)
  ## Note: configure this in one of the manager nodes in a Swarm cluster.
  ## configuring in multiple Swarm managers results in duplication of metrics.
  gather_services = false

  ## Only collect metrics for these containers. Values will be appended to
  ## container_name_include.
  ## Deprecated (1.4.0), use container_name_include
  container_names = []

  ## Set the source tag for the metrics to the container ID hostname, eg first 12 chars
  source_tag = false

  ## Containers to include and exclude. Collect all if empty. Globs accepted.
  container_name_include = []
  container_name_exclude = []

  ## Container states to include and exclude. Globs accepted.
  ## When empty only containers in the "running" state will be captured.
  ## example: container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  ## example: container_state_exclude = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  # container_state_include = []
  # container_state_exclude = []

  ## Timeout for docker list, info, and stats commands
  timeout = "5s"

  ## Whether to report for each container per-device blkio (8:0, 8:1...) and
  ## network (eth0, eth1, ...) stats or not
  perdevice = true

  ## Whether to report for each container total blkio and network stats or not
  total = false

  ## docker labels to include and exclude as tags.  Globs accepted.
  ## Note that an empty array for both will include all labels as tags
  docker_label_include = []
  docker_label_exclude = []

  ## Which environment variables should we use as a tag
  tag_env = ["JAVA_HOME", "HEAP_SIZE"]

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

**Comment by danielnelson** [comment]
@teresaibarra I believe you container needs to have a HEALTHCHECK setup in the Dockerfile, if you have more questions ask on the [InfluxData Community](https://community.influxdata.com) site.

**Comment by triethuynh92** [comment]
> @triethuynh92 I believe you container needs to have a HEALTHCHECK setup in the Dockerfile, if you have more questions ask on the [InfluxData Community](https://community.influxdata.com) site.

Hi,
I configured healthcheck in docker-compose.yml and when I show `docker ps`, I can see `healthy` status. But, I can't get this field into influxdb

**Comment by danielnelson** [comment]
Let's make a new issue with information about your docker version as well as a docker compose file that sets up the healthcheck.
