### ISSUE TITLE
[Feature Request] - Elasticsearch metric format as DATA_OUTPUT_FORMAT option

### ISSUE THREAD

**Issue by BenjaminLSmith** [influxdata/telegraf#4595]
## Feature Request
Currently, the Elasticsearch Telegraf output uniquely formats messages like an Elastic message, produced by any Beat or Logstash  application. The downside is that this is only available if you use the Elasticsearch output plugin. As-is, the only available output formats are JSON, Influx, or Graphite. Creating a new Elasticsearch output format would allow us to send Telegraf metrics to Kafka, to then be later consumed/enriched by Logstash, and finally into Elasticsearch. This would also allow for a queueing pipeline for increased infrastructure stability

## Current behavior
Send Telegraf metrics data to Elasticsearch 5.x or 6.x (with minor warnings)

## Desired behavior
Send Telegraf metrics to Kafka in Elasticsearch format, to be later consumed & ingested into Elasticsearch.

**Comment by danielnelson** [comment]
@BenjaminLSmith What would you use to consume the data from Kafka?

**Comment by BenjaminLSmith** [comment]
@lpic10 That would also work, however doesn't it seem duplicative to use Telegraf twice in a data flow?
@danielnelson The idea is to use Logstash to do additional data enrichment to pull from Kafka and push to Elasticsearch. 

Overall, data is destined for an Elastic product, It just would be nice not have to do basic enrichment (like set @timestamp to be the event time) that the Elasticsearch output plugin would do by default, but not the JSON data format.

**Comment by danielnelson** [comment]
I don't see any issues with this as an idea, though from an implementation point of view it will be a lot easier once we have proper separation between serializers: #4330.
