### ISSUE TITLE
Add counter [SQLServer:Databases Percent Log Used] to enable monitoring for T-log utilization

### ISSUE THREAD

**Issue by varun-dhawan** [influxdata/telegraf#4597]
## Feature Request
Please add counter [SQLServer:Databases Percent Log Used] to enable monitoring for T-log utilization

Opening a feature request kicks off a discussion.

### Proposal:
Please add counter [SQLServer:Databases Percent Log Used] to enable monitoring for T-log utilization

### Current behavior:
Current dashboard monitors following counters
- SQLServer:Databases Log File(s) Size (KB)
- SQLServer:Databases Log File(s) Used Size (KB)

While these are good for getting trend of log usage, they aren't helpful in determining the % log used

### Desired behavior:
- Add counter [SQLServer:Databases Percent Log Used] that will easily expose the value of current T-log utilization and can be used to raise alwerts

### Use case: [Why is this important (helps with prioritizing requests)]
- Using Grafana dashboard for both monitoring (trending) and real-time alerting
- Right in absence of counter [SQLServer:Databases Percent Log Used], we are using a custom PowerShell script to fetch and alert on T-log utilization

**Comment by danielnelson** [comment]
Is it possible to compute the percentage at query time with `used_size/size`?
