### ISSUE TITLE
Telegraf 1.7.3 version is not support acvtivemq and acvtivemq congfig file loss 

### ISSUE THREAD

**Issue by pengliangcheng** [influxdata/telegraf#4602]
The activemq is not supported in telegraf 1.7.3, and the activemq configuration does not exist in telegraf.conf.
After adding "[[inputs.activemq]]", the error "Error parsing telegraf.conf, Undefined but requested input: activemq"

**Comment by danielnelson** [comment]
The new activemq plugin will be included in 1.8

**Comment by pengliangcheng** [comment]
thank you
