### ISSUE TITLE
Procstat/Processes Zombies monitor

### ISSUE THREAD

**Issue by gaizeror** [influxdata/telegraf#4604]
## Feature Request

We are using celery and gunicorn, which works with a "main process" and workers, which are forks of the "MainProcess".
Today we monitor with Nagios if any of the processes became Zombie process, but we can't do the same with Procstat/Processes because.

### Proposal:
Either add tags to the Zombies metric in "processes plugin" which indicates the process pid + process name (process name is not enough because forks has the same name but not the same PID), or add PPID to "procstat plugin", and it will be easy to indicate it.

### Current behavior:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/processes

### Desired behavior:
Additional tags in a single point which includes PID, Process name, is_zombie/PPID.
### Use case: [Why is this important (helps with prioritizing requests)]
Tons of use cases. every manager that uses forks and sub-processes. celery, gunicorn for example.

**Comment by sjwang90** [comment]
#8851
