### ISSUE TITLE
Authentication option for httpjson plugin

### ISSUE THREAD

**Issue by NRMK81** [influxdata/telegraf#461]
Can we add or send user credentials along with HTTP request?

**Comment by sparrc** [comment]
good idea, shouldn't be too difficult to add

**Comment by danielnelson** [comment]
@NRMK81 I noticed that the httpjson documents allow sending of headers and one could also send credentials in the url.  Is this issue already complete or can you clarify the what method of credentials you would like supported?

**Comment by aashley** [comment]
The one I'd like to see is Digest auth as it currently cant be done using the HTTP headers functionality.

**Comment by danielnelson** [comment]
This would be a good addition.

**Comment by crab86** [comment]
@danielnelson so would something like "http://user:password@www.example.com/test.json" work when using httpjson plugin? Or how can http basic auth be used currently? If basic auth is currently not supported i clearly give this request a +1.

**Comment by danielnelson** [comment]
I believe it should passthrough the userinfo section in your url.  Basic auth adds an Authorization header and sets it to `Basic base64(username:password)`.  You can do this currently although it requires you to compute the base64 value manually, so we should probably add a username, password option.

**Comment by jchristopher327** [comment]
I've been toying around with using the Authorization Basic header in the httpjson plugin but having some issues. I'm sure the syntax I'm using is at fault. Below is what I have configured when testing.


```
[inputs.httpjson.headers]
  X-Auth-Token = "Basic <token_pulled_from_postman>"
  apiVersion = "v1"
```
I've tried removing `Basic` and just leaving the token but both ways gives me an authentication failure.

**Comment by danielnelson** [comment]
I think you would want this for a standard http server using basic auth:
```
  [inputs.httpjson.headers]
    Authorization = "Basic aG93ZHk6ZG9vZHk="
```

The example base64 is the result of:
```
echo -ne howdy:doody | base64
```

**Comment by jchristopher327** [comment]
@danielnelson That is what I did shortly after commenting and it does work!

**Comment by marianob85** [comment]
What about Digest Authentication. Is it possible to use ? The curl command works: 
curl --user aaa:bbb "http://xxx.yyy" --digest -v
but how to use it in telegraf ?
` Authorization: Digest username="root", realm="Forbidden", nonce="04d5b48c5e6c8b9b3dd84af4ce6b7643", uri="/", cnonce="OTEyZTZkMTExZjk1NDAxM2EyMDdlMThlNDc4MTM4MGM=", nc=00000001, qop=auth, response="a2ac73d78e199580a2c8546ac4ba7229", opaque="7a6a2abf367f778892c5db364070449f", algorithm="MD5"`

**Comment by danielnelson** [comment]
@marianob85 No, we don't currently have support for this.

**Comment by spidie** [comment]
Shame we don't have digest - I am not much of a go programmer - but did have a look and doesn't look too much to add it. Anyway - I found a useful workaround for anyone still looking at this. Just use the exec plugin and curl:

```
[[inputs.exec]]
  commands = [
    "curl -m 10 --digest -u 'user:pass' http://myurl.com"
  ]
  timeout = "5s"

  data_format = "json"
  name_override = "myoverride"
```

**Comment by danielnelson** [comment]
I opened #4524 specifically for HTTP Digest Authentication.  Since the `httpjson` input is now deprecated we should add it to the `http` input.

For those looking for HTTP Basic Authentication, the `http` input currently supports this.
