### ISSUE TITLE
Logparser treats rotated log file as new file and re-imports everything

### ISSUE THREAD

**Issue by pprkut** [influxdata/telegraf#4614]
### Relevant telegraf.conf:

```
[[inputs.logparser]]
files          = [ "/var/log/nginx/*access.log", "/var/log/nginx/*access.log-????????" ]
from_beginning = true
name_override  = "nginx_access_log"
```

### System info:

Telegraf v1.7.2 (git: release-1.7 c6feb056)
CentOS Linux release 7.5.1804 (Core)

logrotate config:
```
/var/log/nginx/*.log {
        daily
        missingok
        rotate 52
        compress
        dateext
        delaycompress
        notifempty
        create 640 nginx adm
        sharedscripts
        postrotate
                if [ -f /var/run/nginx.pid ]; then
                        kill -USR1 `cat /var/run/nginx.pid`
                fi
        endscript
}
```

### Steps to reproduce:

I have logrotate configured for nginx access logs. The main log file (e.g. *access.log) and the first rotated file (e.g. *access.log-20180830) are uncompressed, while the earlier logs are compressed.
You want to parse both the main as well as the first rotated log file so you can make sure telegraf didn't miss any log entries because of the rotation. However, telegraf detects the rotated file as a new
file and parses all entries again, leading to the entries ending up duplicated in influxdb.

### Expected behavior:

Telegraf recognizes the new file was rotated and only parses the entries not yet parsed before rotation.

**Comment by danielnelson** [comment]
I believe this is the same issue as reported in https://github.com/influxdata/telegraf/issues/3522.  There isn't a known workaround, but it may be worth using the syslog input along with the parser processor when 1.8 is released.  It is definitely a little more setup but it sidesteps log rotation.
