### ISSUE TITLE
lumberjack protocol parser

### ISSUE THREAD

**Issue by pprkut** [influxdata/telegraf#4619]
## Feature Request

Lumberjack is the protocol used by filebeat when configured to send logs to logstash. It's a TCP connection, so conceptually one could then point filebeat's output to the tcp input of telegraf, parse the data using the lumberjack parser and process it with grok before sending it off to influxdb.

Filebeat could then do the heavy lifting of processing the log files, handling log rotation, detecting multiline log entries, etc. and leave only the parsing to telegraf.

There is a [lumberjack input plugin](https://github.com/logstash-plugins/logstash-input-lumberjack) for logstash which could be used as a reference.

**Comment by sspaink** [comment]
We won't be implementing this protocol parser at this time, but we would be happy to review a pull request for it.
