### ISSUE TITLE
Scraping for events for Azure hosted targets

### ISSUE THREAD

**Issue by simonboa** [influxdata/telegraf#4621]
### Proposal:
The ability to scrape Azure hosted targets for data, using Kapacitor.
### Current behavior:
Kapacitor doesn't appear to support this, though we have the following documentation - https://docs.influxdata.com/kapacitor/v1.5/working/scraping-and-discovery/
### Desired behavior:
Customers should be able to use this functionality & we should have detailed documentation to guide them.
### Use case: 
A number of customers have requested this functionality, Grafana offers this & at least one customer has switched from Chronograf to Grafana for this reason.

**Comment by danielnelson** [comment]
Couple follow up questions:
- Do you want to do this with Kapacitor or with Telegraf?
- What type of data are we talking about, is this prometheus endpoints?
- Can you link to the documentation of what Grafana is providing?

**Comment by simonboa** [comment]
Hi @danielnelson I filed this incorrectly under Telegraf issues, I've created https://github.com/influxdata/kapacitor/issues/2065 in it's place & linked to the Grafana offering.
