### ISSUE TITLE
jti_openconfig_telemetry unexpected behavior when str_as_tags = true

### ISSUE THREAD

**Issue by makzdot** [influxdata/telegraf#4626]
### Relevant telegraf.conf:
[[inputs.jti_openconfig_telemetry]]
  ## List of device addresses to collect telemetry from
  servers = ["myrouter:50051"]
  username = "blah"
  password = "blahblah"
  client_id = "gobbler"

  sample_frequency = "5000ms"

  sensors = [
   "jti_interfaces /interfaces",
   "10000ms jti_bgp /network-instances/network-instance/protocols/protocol/bgp",
   "300000ms jti_components /components",
   "300000ms jti_firewall /junos/system/linecard/firewall"
  ]

  retry_delay = "1000ms"
  str_as_tags = true

### System info:
[Include Telegraf version, operating system name, and other relevant details]
Telegraf v1.7.4 (git: release-1.7 578db7ef)
Ubuntu 18.04.1 LTS

### Steps to reproduce:
1. 
Configure the jti_openconfig_telemetry with **str_as_tags = true**
[[inputs.jti_openconfig_telemetry]]
  ## List of device addresses to collect telemetry from
  servers = ["myrouter:50051"]
  username = "blah"
  password = "blahblah"
  client_id = "gobbler"

  sample_frequency = "5000ms"

  sensors = [
   "jti_interfaces /interfaces",
   "10000ms jti_bgp /network-instances/network-instance/protocols/protocol/bgp",
   "300000ms jti_components /components",
   "300000ms jti_firewall /junos/system/linecard/firewall"
  ]
  retry_delay = "1000ms"
  str_as_tags = **true**

2. Explore the database:
`show tag values from "jti_interfaces" with key = "/interfaces/interface/state/description"`
This returns a list of tag values. This is al as expected.

When I want to search on these tag values only _timestamp, component_id and sequence is returned. I would expect that all counter values for interfaces with that description is returned.

### Expected behavior:

When setting str_as_tag to true I would expect (or want) all counter values for that tag to be somehow associated to it.  ie

SELECT "/interfaces/interface/state/counters/out-pkts" AS blah FROM "jti_interfaces" WHERE ("/interfaces/interface/state/description" = 'some description') AND time >= now() - 1m

This query should return all out-pkts for metrics with tag "some description" 

### Actual behavior:

Returns no values when searching for a tag

**Comment by danielnelson** [comment]
Can you enable a `file` output:
```toml
[[outputs.file]]
  files = ["stdout"]
```

And then run telegraf like this for one interval and paste the output:
```
telegraf --input-filter=jti_openconfig_telemetry --output-filter=file
```

**Comment by makzdot** [comment]
Hi @danielnelson 

Thank you for your reply. Attached a couple of seconds of output. 

Regards,
Max

[jti_output.txt](https://github.com/influxdata/telegraf/files/2357453/jti_output.txt)

**Comment by danielnelson** [comment]
@ajhai Do you have any suggestions on how we could improve the data schema here?

**Comment by ajhai** [comment]
We can probably explain str_as_tag option better. If the data type of incoming value is string, this flag will allow that value to be stored as a tag instead of trying to store it as a field value.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go#L159

Also, https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go#L109 explains how tags and fields are extracted from JTI kv pairs.

**Comment by danielnelson** [comment]
One observation I have is that we are creating multiple metrics with the same series:
```
jti_interfaces,/interfaces/interface/@name=xe-1/0/3,device=asd001a-jnx-01-tst.dcn.surf.net,host=librenms,path=sensor_1000_1_1:/junos/system/linecard/interface/:/interfaces/:PFE,system_id=asd001a-jnx-01-tst-re0 _timestamp=1536242460454i,_component_id=1i,_subcomponent_id=0i,/interfaces/interface/state/high-speed=10000i,/interfaces/interface/state/counters/in-multicast-pkts=779835i,/interfaces/interface/state/counters/carrier-transitions=27i,/interfaces/interface/init_time=1528363849i,_sequence=0i 1536242460060437223
jti_interfaces,/interfaces/interface/@name=xe-1/0/4,device=asd001a-jnx-01-tst.dcn.surf.net,host=librenms,path=sensor_1000_1_1:/junos/system/linecard/interface/:/interfaces/:PFE,system_id=asd001a-jnx-01-tst-re0 /interfaces/interface/state/high-speed=10000i,/interfaces/interface/state/counters/carrier-transitions=7i,/interfaces/interface/init_time=1528363849i,_sequence=0i,_timestamp=1536242460454i,_component_id=1i,_subcomponent_id=0i 1536242460060437223
```

If we were to combine these, into a single telegraf.Metric containing all the fields, then any string fields that are promoted to tags would be applied to all fields.

As an aside, do you know of a good resource to get a better overview of the concrete structure of the sensors?  Perhaps something like the [https://apps.juniper.net/mib-explorer/navigate.jsp](SNMP MIB Explorer) but for OpenConfig.

**Comment by makzdot** [comment]
@danielnelson I think your observation is correct and if those metrics would be combined (better/differently), that would solve my problem. 

I have not yet found a 'definitive' documentation on the JTI data structure for openconfig. I think it is still a little sparse at the moment. As it tends to be with new Juniper technology and features. But maybe @ajhai can shed some light on that.

**Comment by danielnelson** [comment]
I think the data must be spread across messages in the gRPC stream.  Since the data is streaming in there is no clear point where we can aggregate the data into a combined metric, that is we don't know how long to hold onto the metric in case another one comes in with the same tags.

We could potentially write an aggregator that just merges series, I'm unsure if it is the best solution though.

**Comment by ajhai** [comment]
@danielnelson This is flattened hierarchical data being emitted as key value pairs. So key here is essentially a path from root of the tree to that level. We are breaking this xpath key back into that hierarchy creating one field per key element at a level with keys at parent levels as tags.

In this
```
jti_interfaces,/interfaces/interface/@name=xe-1/0/3,device=asd001a-jnx-01-tst.dcn.surf.net,host=librenms,path=sensor_1000_1_1:/junos/system/linecard/interface/:/interfaces/:PFE,system_id=asd001a-jnx-01-tst-re0 _timestamp=1536242460454i,_component_id=1i,_subcomponent_id=0i,/interfaces/interface/state/high-speed=10000i,/interfaces/interface/state/counters/in-multicast-pkts=779835i,/interfaces/interface/state/counters/carrier-transitions=27i,/interfaces/interface/init_time=1528363849i,_sequence=0i 1536242460060437223
jti_interfaces,/interfaces/interface/@name=xe-1/0/4,device=asd001a-jnx-01-tst.dcn.surf.net,host=librenms,path=sensor_1000_1_1:/junos/system/linecard/interface/:/interfaces/:PFE,system_id=asd001a-jnx-01-tst-re0 /interfaces/interface/state/high-speed=10000i,/interfaces/interface/state/counters/carrier-transitions=7i,/interfaces/interface/init_time=1528363849i,_sequence=0i,_timestamp=1536242460454i,_component_id=1i,_subcomponent_id=0i 1536242460060437223
```
we have different values for /interfaces/interface/@name. 

https://www.juniper.net/documentation/en_US/junos/topics/concept/open-config-grpc-junos-telemetry-interface-understanding.html is the documentation that is currently available for JTI

**Comment by danielnelson** [comment]
Yeah, my example was not valid.

@makzdot Can you perform the same collection as above but with `str_as_tags = false`?  To aid with comparison can you also set `influx_sort_fields = true` in the file output?

**Comment by makzdot** [comment]
@danielnelson Sorry haven't gotten around to it yet. Hopefully next week.

**Comment by makzdot** [comment]
@danielnelson: Finally got around to it.

[jti_output.txt](https://github.com/influxdata/telegraf/files/2434685/jti_output.txt)

**Comment by makzdot** [comment]
@danielnelson I Finally got around to it.
[jti_output.txt](https://github.com/influxdata/telegraf/files/2434718/jti_output.txt)

**Comment by danielnelson** [comment]
Looked through the data, I don't think there is anything we will be able to do.  None of the items with a description could have a corresponding out-pkts unless you drop the `path` tag, and I think if you drop that then you will probably have bad results.

As an aside, I see quite a few fields with empty string values.  Do you think we should not add these @ajhai or does it make sense to keep them as an empty string?

**Comment by ajhai** [comment]
@danielnelson I think we should keep them given that the device is emitting them as empty strings and could signify things like missing component, unconfigured feature etc etc..

**Comment by danielnelson** [comment]
Closing, it doesn't look like we can/should take any action at this time.

**Comment by stefi994** [comment]
Hey, I also encountered this problem, just a converted the field "/interfaces/interface/subinterfaces/subinterface/state/description" as tag. I want to see the amount of traffic on a interface with description as the tag above, unfortunately I am not getting any result.

I do have them as tag keys in influx, I even dropped the whole measurement after I converted the tag but again no luck.

Can you please help me?

**Comment by stefi994** [comment]
@danielnelson @ajhai Hey guys , can you please take a look at this one? I am still struggling to get it to work.. is it in any way fixed? 
@makzdot Do you maybe find some workaround for this one ?
