### ISSUE TITLE
Issues building on Windows 10

### ISSUE THREAD

**Issue by m82labs** [influxdata/telegraf#4630]
### Relevant telegraf.conf:
N/A

### System info:
Fresh "go get" of telegraf
Windows 10
go 1.11
GNUWin32 Make 3.81

### Steps to reproduce:
I am running through the steps in the appveyor.yml file manually:
1.  `go get -d github.com/influxdata/telegraf`
2.   `go get -d github.com/golang/dep`
3.  `cd "%GOPATH%\src\github.com\golang\dep"`
4. `git checkout -q v0.5.0`
5.  `go install -ldflags="-X main.version=v0.5.0" ./cmd/dep`
6.  `cd "%GOPATH%\src\github.com\influxdata\telegraf"`
7.  `git config --system core.longpaths true`
8.  `cd "%GOPATH%\src\github.com\influxdata\telegraf"`
9.  `make`

### Expected behavior:
I expect telegraf to build

### Actual behavior:
I get this error:
```
C:\Users\mark.wilkinson\go\src\github.com\influxdata\telegraf>make
dep ensure -vendor-only
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/wvanbergen/kazoo-go: cannot stat C:\Users\mark.wilkinson\go\pkg\dep\sources\https---github.com-wvanbergen-kazoo--go\.git\index: FindFirstFile C:\Users\mark.wilkinson\go\pkg\dep\sources\https---github.com-wvanbergen-kazoo--go\.git\index: The system cannot find the file specified.
make[1]: *** [deps] Error 1
make: *** [all] Error 2
```
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I have never seen this error, can you try with Go 1.10.3?  Make sure to remove the [DEPCACHEDIR](https://golang.github.io/dep/docs/env-vars.html#depcachedir) and the vendor directory.

If that doesn't change anything I think we should report it to https://github.com/golang/dep

**Comment by m82labs** [comment]
Thanks @danielnelson I'll give it a try.

**Comment by m82labs** [comment]
Clearing the DEPCACHE fixed the issue. Thanks

**Comment by danielnelson** [comment]
Glad you got it working, mysterious.
