### ISSUE TITLE
Output value usage_iowait is always 0

### ISSUE THREAD

**Issue by hkraal** [influxdata/telegraf#4631]
### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]

[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
```

### System info:
* Debian GNU/Linux 7.6 (wheezy)
* Telegraf v1.7.4
* Kernel 4.4.150 with grsec

### Steps to reproduce

* Run Telegraf normally / test output
```
telegraf -config /etc/telegraf/telegraf.conf -test --input-filter cpu
> cpu,cpu=cpu-total,host=srv01.example.com,sla=true usage_guest=0,usage_guest_nice=0,usage_idle=83.97997496589534,usage_iowait=0.2503128909757588,usage_irq=0,usage_nice=0,usage_softirq=0.12515644554479396,usage_steal=0.2503128911123538,usage_system=1.627033792253065,usage_user=13.767209012044557 1536067967000000000
```

* Check the data being send to InfluxDB
```
tcpdump -i lo port 8086 -s 0 -A|grep cpu
cpu,cpu=cpu-total,host=srv01.example.com,sla=true usage_user=10.91774303201669,usage_iowait=0,usage_irq=0,usage_softirq=0,usage_guest=0,usage_guest_nice=0,usage_system=1.91706322230736,usage_idle=87.16519374579467,usage_nice=0,usage_steal=0 1536067790000000000
```

### Expected behavior:

* `usage_iowait` being higher than `0`

### Actual behavior:

* `usage_iowait` is always `0`

### Additional info:

An stack trace on the running proces seems to hint that the cpu values after user/nice/system/idle are in fact `0`. This seems to indicate that there is a difference in source between testing and running.

```
47327 read(6, "cpu  83198349 36 13355818 525391924 0 0 0 0 0 0\ncpu0 5615499 0 939593 30665701 0 0 0 0 0 0\ncpu1 5950753 2 673596 32223662 0 0 0 0 0 0\ncpu2 7135602 0 1129939 30536599 0 0 0 0 0 0\ncpu3 6576662 0 797597 31460108 0 0 0 0 0 0\ncpu4 6091538 2 1029397 31789139 0 0"..., 4096) = 4096
```

**Comment by danielnelson** [comment]
My guess is that /proc/stat appears different to the `telegraf` user than it does to your regular user.  Can you try running `cat /proc/stat` as the telegraf user and comparing to your normal account?

**Comment by hkraal** [comment]
@danielnelson your guess is spot on. The telegraf user wasn't part of the "proc" group in this specific case which was easily fixed, thank you for your time!
