### ISSUE TITLE
S.M.A.R.T. Input Plugin enhancements : convert health_ok to int and collect additional attributes

### ISSUE THREAD

**Issue by Daryes** [influxdata/telegraf#4632]
### 1 : Change the drive status (health_ok) from boolean to int.
Influxdb just doesn't play nice with boolean field, any aggregation done will be limited to a very few number of selectors, otherwise an error will be raised.

The caveat would be that the `smart_device.health_ok` field, if not the whole `smart_device` measurement would require to be dropped before. 
Maybe for this case using the `metric_version` setting like it was done for mysql.

### 2 : add attributes to the main measurement.
Same as #3728, it seems that as of today's version (1.7.4), the `attributes` setting is still set to `false` by default. I discovered this today, as the documentation isn't much clear. 
Something along this might be more understandable (or not) :
````
Gather all returned SMART Attribute metrics and their detailed information from each drives (i.e.: 12:Power_Cycle_Count, 173:Wear_Leveling_Count, ...).
Note: SMART information is separated between different measurements : smart_device is used for general information, while smart_attribute stores the detailed attributes information.
````
This aside, the telegraf plugin should register as a basis those 2 additional SMART attributes in the `smart_device` measurement :
187 Reported Uncorrectable Errors
197 Current Pending Sector Count

Blackblaze links in #3728 are already explicit, but [wikipedia ](https://en.wikipedia.org/wiki/S.M.A.R.T. ) might help to have a better understanding : 187 stands for any error not recovered by hardware, 197 stands for any unstable sector before a recovery is tried, which covers recovered sector and non-recovered.
In reality, attribute `197` seems to be sometimes missing, depending of the manufacturer, with only attribute `198 (Offline) Uncorrectable Sector Count` available, and vice-versa. So it might be better to collect both.
As the informations in `smart_device` are global, `187` and `197` should also be present to indicate when a drive needs surveillance and look at the more obscure informations in `smart_attribute`

**Comment by russorat** [comment]
for 1. you can use something like the following processor to convert the bool to an int:
```
[[processors.converter]]
  [processors.converter.fields]
    integer = ["health_ok"]
```

can you confirm that 2. is still an issue in telegraf 1.11?

**Comment by Daryes** [comment]
Just checked with `--test` on Telegraf 1.11.2 :
1) thanks for the converter example, 

2)  Yup, as the parameter `attributes ` is still set to false as the default value in 1.11.2. 
At least, the documentation should be updated for this setting, it isn't clear how much impact and detail it can bring on the output when activated

**Comment by russorat** [comment]
does https://github.com/influxdata/telegraf/pull/6192 satisfy 2 for you?

**Comment by Daryes** [comment]
That's good, thanks
