### ISSUE TITLE
ObjectName = "ASP.NET", does not dispaly any information

### ISSUE THREAD

**Issue by evollution** [influxdata/telegraf#4649]
### Relevant telegraf.conf:
  [[inputs.win_perf_counters.object]]
    # IIS, ASP.NET
    ObjectName = "ASP.NET"
    Counters = ["Application Restarts", "Request Wait Time","Requests Current","Requests Queued","Requests Rejected"]
    Instances = ["*"]
    Measurement = "win_aspnet"
    IncludeTotal=true #Set to true to include _Total instance when querying for all (*).

### System info:
Windows Server 2016 
[Include Telegraf version, operating system name, and other relevant details]
Latest

### Steps to reproduce:
Just running telegraf

### Actual behavior:
When i go to graphite, even if i can find other IIS performance metrics, this one ASP.net i am unable to find. There are no errors or anything.

All other IIS performance metrics seem to be working. Am I doing something wrong?

**Comment by danielnelson** [comment]
Can you see these performance counters in perfmon?

https://www.thewindowsclub.com/how-to-use-perfmon-performance-monitor-windows

**Comment by danielnelson** [comment]
Let us know if this still persists after checking perfmon.

**Comment by brettzink** [comment]
@evollution did you ever solve this? I'm having the same issue. The data exists in perfmon, but telegraf doesn't pick it up.
