### ISSUE TITLE
Windows : telegraf doesn't respect round_interval and collect data too soon

### ISSUE THREAD

**Issue by Daryes** [influxdata/telegraf#4652]
Might be related (or not) to #4487

### System info:
Telegraf-1.7.3 on Windows Server 2012

### Steps to reproduce:
use   `interval = "5m"` with `round_interval = true` in telegraf.conf
1. run telegraf and wait up to ~48h
2. query the windows measurements in Influxdb 

### Expected behavior:
query influxdb, returning the metrics with a timestamp at [0 or 5]:00 +jitter sec

### Actual behavior:
the metrics are returned with a timestamp that is not rounded, resulting in a real interval lower than the telegraf setting.

It's usually at [0 or 5]m00s +jitter sec, but it will also be at [9 or 4]m5?s +jitter sec

Influxdb query : 
(I used uptime, but it's the same for ALL windows metrics) 
````
Precision rfc3339
SELECT "System_Up_Time" FROM "win_system" WHERE "host" =~ /^XXXXX$/ AND time >= now() - 2d
2018-09-07T14:20:00Z 464354.03125       <= OK
2018-09-07T14:24:58Z 464652.0625        <= not rounded, should be at T14:25:00 +?s
2018-09-07T14:30:00Z 464954.03125       <= OK
2018-09-07T14:34:58Z 465252.5           <= not rounded, should be at T14:35:00 +?s
2018-09-07T14:39:58Z 465552.65625       <= ...
2018-09-07T14:44:59Z 465853.34375
2018-09-07T14:49:58Z 466152.8125
````
All data should be at [0 or 5]m00s +? sec, those at [4 or 9]m59s  are the anomaly. I had some up to :57s.

By the way, the influxdb log is consistent (mind the timezone), confirming it really comes from telegraf  : 
````
[xWINDOWS SERVER IPx] - telegraf [07/Sep/2018:16:34:59 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" 32f440cc-b2ab-11e8-bdf4-000000000000 57296
[xWINDOWS SERVER IPx] - telegraf [07/Sep/2018:16:39:59 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" e5a85994-b2ab-11e8-be12-000000000000 54763
````

### Additional info:
This doesn't happen immediately, the agent need to work for at least 24h to start exhibiting this behavior. Restarting the agent fixes the issue, but for some hours only.

I'm running the same agent configuration on Linux and Windows, with a global influxdb server, collecting both systems. 
The Linux servers don't and never have show this behavior, only the single existing Windows server does. All are VMware virtual machines, plugged on the same NTP server, and the Windows server shows the exact same time up to the second as the influxdb server.

The log is empty on the Windows server, no error is present.

It's worth noting that IIRC, this issue didn't appear before Telegraf v1.4 

### Relevant telegraf.conf:
````
# Telegraf configuration

# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.

# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.

# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.

# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
[ ... ]
  
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "5m"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

  ## Flush the buffer whenever full, regardless of flush_interval.
  flush_buffer_when_full = true

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "2s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "5s"

  ## By default, precision will be set to the same timestamp order as the
  ## collection interval, with the maximum being 1s.
  ## Precision will NOT be used for service inputs, such as logparser and statsd.
  ## Valid values are "ns", "us" (or "µs"), "ms", "s".
  precision = "s"
  
  ## Logging configuration:
  ## Run telegraf in debug mode
  debug = false
  ## Run telegraf in quiet mode
  quiet = true
  
  ## Specify the log file name. The empty string means to log to stdout.
  logfile = "C:/Server/Telegraf/log/telegraf.log"
  
  ## Override default hostname, if empty use os.Hostname()
  hostname = "XXXXXX"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################
````

**Comment by danielnelson** [comment]
I believe it could be because of the way time.Ticker works in Go.  The ticker goes off every interval, which could be subject to drift or system clock synchronization changes.  The times not being aligned can cause problems with certain aggregations.

As a limited workaround, you could consider setting precision higher, here is the most recent documentation along with how to set this value properly:
```toml
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = "5s"
```

**Comment by Daryes** [comment]
You might be right with the situation related to a drift with the system time.  I have already had problems with VM and time drifting before, until switching VM time sync directly to a NTP server instead of relying to the host physical clock (which itself was sync on a ntp server).

Just changed the precision parm, we'll see in some hours. 
But, unless I'm mistaken, the documentation you provided claims the maximum allowed is 1s, so using `= 5s` will be capped down to `1s`. Wouldn't it be the same a the `= s` value I'm currently using, and that telegraf still accept (at least without error) ?

**Comment by danielnelson** [comment]
I probably need to reword the documentation, but what it is meant to say is that the **default** value changes based on the interval and the highest default chosen is "1s".  If you do set the value though it is required to have a constant in addition to the units.  So it actually should be "1s" and not "s", otherwise the default is used.

**Comment by Daryes** [comment]
Back after having telegraf running until now : I though it was much better, as only the last few hours after 6 days were starting to show the wrong interval, and only a dot from time to time, not multiple block of hours like previously.  

That's only due to telegraf doing 2 POST to influxdb, because of `metric_batch_size` reverted to 1000 when I updated the precision to 5s, instead of 5000 like I had before only for Windows (forgot to reactivate the exception on Ansible).  

Influxdb logs : 
````
192.168.0.221 - telegraf [13/Sep/2018:04:54:58 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" 66804324-b700-11e8-bead-000000000000 59218
192.168.0.221 - telegraf [13/Sep/2018:04:55:09 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" 6d5bf75e-b700-11e8-beb4-000000000000 50896
192.168.0.221 - telegraf [13/Sep/2018:04:59:59 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" 1a0378d7-b701-11e8-becc-000000000000 54592
192.168.0.221 - telegraf [13/Sep/2018:05:00:11 +0200] "POST /write?consistency=any&db=telegraf HTTP/1.1" 204 0 "-" "telegraf-node" 21457aec-b701-11e8-bed7-000000000000 50923
````
First POST is at odd time, as usual, second POST is correct.  

By "chance", the first POST seems to contain mostly the "win_proc" measurement data, which is not closely monitored as the rest of the metrics, who are in the second POST. That's why the CPU, memory and other system metrics I checked had a valid time.

So, back to square one, with `precision = 5s` having no noticeable effect, at first glance.

**Comment by danielnelson** [comment]
I wouldn't pay much attention to the output POST times, all the timestamps are set when the metrics are created in the inputs.  The outputs will write when either `metric_batch_size` new metrics have been produced, or after every `flush_interval`, whichever comes first.

**Comment by Daryes** [comment]
Ok. This aside, it took 7 days, but now all the metrics are showing negative drifting in the interval time, for nearly 50% of the collected points.
The setting helped to increase the time before it appears, but didn't fix it.

**Comment by danielnelson** [comment]
Thanks for the update, so there must be a 2.5 second drift over only 7 days, much larger than I expected.  I think we will have to change the way we calculate the intervals to fix.

**Comment by Daryes** [comment]
Any progress on this ?
While I was able to reduce the amount of drifting data with the option `flush_buffer_when_full` set to false (default is true), it still occurs after a week like clockwork.

**Comment by danielnelson** [comment]
No, sorry this hasn't been worked on.  There are some changes to the interval rounding but we are still using a ticker and I believe it will still be subject to drift.

The `flush_buffer_when_full` setting actually needs removed from the Windows telegraf.conf file, it doesn't actually do anything and it is essentially always enabled.

**Comment by randallt** [comment]
I am hitting some drift too on Linux 1.8.1. My drift is several seconds early or late, though. Instead of reporting at :00 of each minute, they are reporting too early or too late, such that on some hosts I can't tell if the sample is early or late (close to the :30 mark). Restarting telegraf get's the sample back to :00 temporarily. The rate of drift is hard to tell, and may vary host to host. This is VMware VMs.

**Comment by danielnelson** [comment]
@randallt Thanks for the additional data point.  In 1.9, it should no longer be possible for inputs to block when adding new metrics.  It seems like you might be hitting this because instead of drift in only one direction your values are a mix of early and late.  Would be interested to hear when you update.

**Comment by randallt** [comment]
@danielnelson I have upgraded to 1.10.4-1 and after a couple weeks, my data points have drifted by almost a minute. Metrics that used to report right at :00 (1 min intervals) are now reporting at :54. Should I open a new issue for this? I have interval="60s" and round_interval=true.

**Comment by danielnelson** [comment]
Seems like a pretty severe drift, more than I've seen before.  I would expect socket_listener to not be affected, since it is event driven and doesn't operate on the interval, but vphere does use this interval. Which plugins are affected?

**Comment by randallt** [comment]
Let's talk about it under the new issue

https://github.com/influxdata/telegraf/issues/5937
