### ISSUE TITLE
Question: kafka_consumer plugin topic regex

### ISSUE THREAD

**Issue by infa-stopiwal** [influxdata/telegraf#4653]
Can the current kafka_consumer plugin use "*" as a regex for the topics key to specify all topics or topics matching a specific regex?

**Comment by danielnelson** [comment]
It is not possible currently.  For the updating reasons mentioned in this issue on sarama-cluster we probably will not attempt to add it externally, so it is unlikely we can add this anytime soon.

https://github.com/bsm/sarama-cluster/issues/36

**Comment by rodrigobrochado** [comment]
Hi @danielnelson 
Any news on this? Could you elaborate on the "updating reasons"? 
I imagined it could be done exposing two new parameters like `topics_glob` **and** `topics_period` for the pattern and the period for probing brokers, respectively. In this way, the topics update wouldn't necessarily be a problem, right? In my case, for example, it would be every 10 minutes or more.

I've seen some demand for this on the Sarama community in last years, as in Shopify/sarama#868, Shopify/sarama#1379 and Shopify/sarama#1382, but no changes. Following your comment at [#4568 ](https://github.com/influxdata/telegraf/issues/4568#issuecomment-495463152), would the best approach be somebody to propose the change directly at Sarama and them roll it on Telegraf?
