### ISSUE TITLE
Report interface speed in net module

### ISSUE THREAD

**Issue by smalenfant** [influxdata/telegraf#4658]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

It seems like there is no statistics on interface speed today available. 
Statistics available from /sys/class/net/<dev>/speed

### Current behavior:

N/A

### Desired behavior:

Get interface speed along with net statistics.

### Use case: [Why is this important (helps with prioritizing requests)]

Calculate percent utilization of an interface. Detect interface bond issues.

**Comment by glinton** [comment]
Thanks for the suggestion. If you'd like, you are more than welcome to add this functionality to telegraf.

**Comment by danielnelson** [comment]
We should consider if this would be a good fit in gopsutil as well.

**Comment by smalenfant** [comment]
Thanks!
