### ISSUE TITLE
Add stats reset as an option to the redis input plugin

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/telegraf#4668]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add an option to the redis plugin to enforce a stats reset. 

### Current behavior:

No reset is performed.

### Desired behavior:

Provide the option to send the CONFIG RESETSTAT command after the INFO command.

https://redis.io/commands/config-resetstat

### Use case: [Why is this important (helps with prioritizing requests)]

This makes it easier to alert on some metrics, such as, for example, rejected_connections.

**Comment by voiprodrigo** [comment]
Ok, understandable. No problem when doing regular queries to the database, but actually the use case  I had in mind when submitting this was streaming in kapacitor, where I just want to alert on every detected growth.

**Comment by danielnelson** [comment]
Do you have the processing flow lined up like:
```
telegraf -> influxdb -> kapacitor
```
or:
```
telegraf -> influxdb
         -> kapacitor
```

**Comment by voiprodrigo** [comment]
I guess I can use changeDetect|difference for that.

**Comment by danielnelson** [comment]
What about this node? https://docs.influxdata.com/kapacitor/v1.5/nodes/derivative_node/

**Comment by voiprodrigo** [comment]
>Do you have the processing flow lined up like: ...

@danielnelson it’s telegraf to influx then to influx, streaming via subscriptions.

**Comment by voiprodrigo** [comment]
>What about this node? https://docs.influxdata.com/kapacitor/v1.5/nodes/derivative_node/

@danielnelson a rate over 0 would provide the same indication, but from|difference seems more direct? Haven’t tested though, only tomorrow.

**Comment by danielnelson** [comment]
I think since you want to detect any rise either one will do the job.

I'm going to close this issue but let me know if you have trouble or aren't happy with the results when you test it out tomorrow.
