### ISSUE TITLE
statsd plugin: add option to disable replacing '.' with '_'

### ISSUE THREAD

**Issue by entertainyou** [influxdata/telegraf#467]
As title, it's the some configuration to disable this?

**Comment by sparrc** [comment]
There isn't, InfluxDB & Telegraf generally uses underscores as a convention, but it would be pretty simple to disable this.

**Comment by entertainyou** [comment]
@sparrc tested on 0.10.1, specify the option as false does not work. 

Maybe the configuration is not used?
