### ISSUE TITLE
input exec bug report

### ISSUE THREAD

**Issue by zhangjianweibj** [influxdata/telegraf#4671]
version:Telegraf v1.7.4 (git: release-1.7 578db7ef)
config the telegraf.conf input.exec then start telegraf ,log shows telegraf exec not support csv property.why?
my configuration below:
![image](https://user-images.githubusercontent.com/18585129/45342173-b12a5780-b5cf-11e8-85d4-0afa7da408ee.png)

error log:
![image](https://user-images.githubusercontent.com/18585129/45342068-5b55af80-b5cf-11e8-8fa8-b04d1deb91cf.png)

**Comment by danielnelson** [comment]
The csv option will only be available in 1.8.0, but you can test with one of the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and we should have a release candidate out later this week.
