### ISSUE TITLE
Linux Pool metrics needs "health" & "operations/bandwidth"

### ISSUE THREAD

**Issue by dearco** [influxdata/telegraf#4673]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
More and more people use zfs on ubuntu 16.04/18.04, we need more metrics for monitoring zpool status.

### Current behavior:
No metrics for linux zpool of "health" & "operations/bandwidth".

### Use case: [Why is this important (helps with prioritizing requests)]
help indicating the status of zpool on linux

**Comment by glinton** [comment]
Good idea, if you have time and would like to contribute, you can use [the freebsd](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/zfs/zfs_freebsd.go) version as a starting point.

**Comment by danielnelson** [comment]
Let's merge this issue with https://github.com/influxdata/telegraf/issues/2616

**Comment by danielnelson** [comment]
@dearco I don't think that other issue mentions operations/bandwidth, but it definitely discusses health.  Can you add a comment on the other issue along with how you normally view the info you are interested in manually.
