### ISSUE TITLE
docs: Link to InfluxDB line-protocol description

### ISSUE THREAD

**Issue by mvuets** [influxdata/telegraf#4677]
I work with a Telegraf plugin that has `data_format` configured to `influx`. As a brand new user of Telegraf I wonder what that is, so I go to the [documenation page](https://github.com/influxdata/telegraf/blob/e85a9e09565949c204ef522b4dc3f9a27bfc7a6d/docs/DATA_FORMATS_INPUT.md#influx) only to discover that it is a regular "InfluxDB line-protocol". Alas, that does not help (-:

Suggestion: turn "InfluxDB line-protocol" into a link to the description of the protocol. Something like https://github.com/influxdata/influxdb/blob/master/tsdb/README.md or maybe
https://docs.influxdata.com/influxdb/v1.6/write_protocols/line_protocol_reference/

**Comment by goller** [comment]
Hi @mvuets, good point.  Do you mind creating a PR for that?

**Comment by danielnelson** [comment]
I got it: fa1c572096376727ca46b7ae5620ee890af93c01
