### ISSUE TITLE
http input plugin does not honor tag_url option

### ISSUE THREAD

**Issue by chumbert2** [influxdata/telegraf#4678]
### Relevant telegraf.conf:

```
# Read formatted metrics from one or more HTTP endpoints
[[inputs.http]]
  ## One or more URLs from which to read formatted metrics
  urls = [
    "http://localhost:8080/metrics"
  ]

  ## HTTP method
  # method = "GET"

  ## Optional HTTP headers
  # headers = {"X-Special-Header" = "Special-Value"}

  ## Optional HTTP Basic Auth Credentials
  # username = "username"
  # password = "pa$$word"

  ## Tag all metrics with the url
  tag_url = false

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Amount of time allowed to complete the HTTP request
  # timeout = "5s"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  # data_format = "influx"
```

### System info:

`Telegraf v1.7.4 (git: release-1.7 578db7ef)` Linux.

### Steps to reproduce:

1. Generate a telegraf config file and enable HTTP input plugin.
2. In `[[inputs.http]]` section, set `tag_url = false`
3. Start Telegraf.
```
E! Error parsing /home/g179723/.telegraf/telegraf.conf, line 364: field corresponding to `tag_url' is not defined in `*http.HTTP'
```

### Expected behavior:

`tag_url` option is taken into account.

### Actual behavior:

Parsing error:
```
E! Error parsing /home/g179723/.telegraf/telegraf.conf, line 364: field corresponding to `tag_url' is not defined in `*http.HTTP'
```

### Additional info:

[0001-Honor-tag_url-option-for-http-input.txt](https://github.com/influxdata/telegraf/files/2371561/0001-Honor-tag_url-option-for-http-input.txt)

**Comment by danielnelson** [comment]
@chumbert2 I removed this option before the plugin was released, looks like I forgot to clean up the sample config.  The behavior now is to add the url tag if it is not already set by the input data, does this behavior work for you?

**Comment by chumbert2** [comment]
@danielnelson Ah OK. Actually, I do not want the `url` tag but this can be achieved too by adding `tagexclude = ["url"]` in the config file. Thus, the default behaviour is fine.

**Comment by danielnelson** [comment]
I removed the option from the sample config for now.  37fefa300b87d72e8d96028af3da0230b1093d36
