### ISSUE TITLE
inputs snmp ignores zero retries setting

### ISSUE THREAD

**Issue by aurimasplu** [influxdata/telegraf#4683]
### Relevant telegraf.conf:
[[inputs.snmp]]

agents = ["router.testdom.net"]

  interval = "60s"
  **timeout = "2s"**
  **retries = 0**
  version = 3
  max_repetitions = 30

  ## SNMPv3 auth parameters
  sec_name = "snmpuser"
  auth_protocol = "SHA"
  auth_password = "snmpapass"
  sec_level = "authPriv"
  context_name = ""
  priv_protocol = "AES"
  priv_password = "snmpppass"

  
    [[inputs.snmp.table]]
     name="interface"

     [[inputs.snmp.table.field]]
     name="ifName"
     oid="IF-MIB::ifName" 
     is_tag=true

     [[inputs.snmp.table.field]]
     name="ifAlias"
     oid="IF-MIB::ifAlias"
     is_tag=true

     [[inputs.snmp.table.field]]
     name="ifOperStatus"
     oid="IF-MIB::ifOperStatus"
     is_tag=true

     [[inputs.snmp.table.field]]
     name="ifHCInOctets"
     oid="IF-MIB::ifHCInOctets"

     [[inputs.snmp.table.field]]
     name="ifHCInUcastPkts"
     oid="IF-MIB::ifHCInUcastPkts"

     [[inputs.snmp.table.field]]
     name="ifHCOutUcastPkts"
     oid="IF-MIB::ifHCOutUcastPkts"

     [[inputs.snmp.table.field]]
     name="ifHCOutOctets"
     oid="IF-MIB::ifHCOutOctets"

     [[inputs.snmp.table.field]]
     name="ifInDiscards"
     oid="IF-MIB::ifInDiscards"

     [[inputs.snmp.table.field]]
     name="ifInErrors"
     oid="IF-MIB::ifInErrors"     

     [[inputs.snmp.table.field]]
     name="ifOutDiscards"  
     oid="IF-MIB::ifOutDiscards"  

     [[inputs.snmp.table.field]]  
     name="ifOutErrors" 
     oid="IF-MIB::ifOutErrors"

### System info:
Telegraf 1.7.4 (same issue in 1.7.2)
OS: Red Hat 7.5

### Steps to reproduce:

1. Set retries = 0 on any inputs.snmp instance
2. Wait till device do not respond to any poll
3. Capture issue with tcpdump
![packetdump](https://user-images.githubusercontent.com/33485896/45433579-24f26000-b6b5-11e8-9ebb-e7a0f7542637.png)
I have excluded responses with filter, but from screen shot you can clearly see when retry is made.

### Expected behavior:
When retries = 0 telegraf should not make any retries when device dos not respond to any poll and continue polling device with next metric in line.

### Actual behavior:
When device does not respond to any snmp field query, telegraf stops polling device for timeout period and when retry again. Sometimes, even though device responds, data does not get into database (Elasticsearch 6.1)
 
### Additional info:
I run more than thousand inputs.snmp instances with configs putted to telefraf.d directory. All instances run on 1 minute intervals. I do not mind that my devices sometimes does not respond, but I need clear timeouts or nulls in database.

**Comment by glinton** [comment]
I wonder if this is an error in the [underlying library](https://github.com/soniah/gosnmp), as it is what handles the retries.
