### ISSUE TITLE
On deleted Message event

### ISSUE THREAD

**Issue by pikilon** [influxdata/telegraf#4685]
## Feature Request

I want my bot to detect when a user deleted a message.
I am counting the words in the whole chat and I need to update my ddbb in order to delete this words.

### Proposal:
``` 
bot.on('deleted_message', ctx => {
  doSomething(ctx.message.id)
})
```
### Current behavior:
Nothing
### Desired behavior:
Returned the deleted message id and if possible the type

### Use case: [Why is this important (helps with prioritizing requests)]
For any bot that persist some message data it useful to update it properly.

**Comment by danielnelson** [comment]
I think you may be looking for the https://github.com/telegraf/telegraf project?
