### ISSUE TITLE
Plugin to query mongodb

### ISSUE THREAD

**Issue by k-xzc** [influxdata/telegraf#4693]
## Feature Request

I would like to query collection data in mongodb 
example : system.profile 
To find out which query make my mongodb slow 

### Proposal:

Add plugin to support query collection data in mongodb

### Current behavior:

Not support to query to mongodb collection like system.profile

### Desired behavior:

Support to query to mongodb collection

### Use case: [Why is this important (helps with prioritizing requests)]

We can monitoring deeply into mongodb behavior 
We can monitoring data of other collection behavior

**Comment by seuf** [comment]
+1 
I would like to query collections size to see how they evolute..

**Comment by debu99** [comment]
+1

**Comment by anandpathak** [comment]
+1

**Comment by sspaink** [comment]
@kantsuw or @seuf are you still interested in seeing this feature request implemented?

**Comment by seuf** [comment]
Not anymore.

**Comment by kantsuw** [comment]
For me it would be great

**Comment by sspaink** [comment]
@kantsuw according to the mongodb input plugin there some collection statistics are already collected (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mongodb). Could you provide more information what exactly you are looking for? Maybe an example of the query or some mongodb documentation?
