### ISSUE TITLE
Datadog Plugin Spikes CPU 

### ISSUE THREAD

**Issue by smicha** [influxdata/telegraf#4699]
When I enabled the datadog plugin  the cpus on our servers (windows ec2 ) went up from 6% to 35% . Is this normal or am I missing something .  I am running a binary that I built  with the below command 

 GOOS=windows GOARCH=amd64 make telegraf and Installed it .

**Comment by danielnelson** [comment]
@smicha I see that this plugin does a few operations that are somewhat expensive, in particular it calls `Metric.Fields()` and `Metric.Tags()` instead of `FieldList()` and `TagList()`.  We should update the output to use the more efficient methods.

**Comment by smicha** [comment]
Thanks . I will submit a PR for it tomorrow

**Comment by danielnelson** [comment]
Closed in #4803
