### ISSUE TITLE
Cannot use json_string_fields in mqtt_consumer

### ISSUE THREAD

**Issue by kurbeco** [influxdata/telegraf#4705]
### Relevant telegraf.conf:

    [[inputs.mqtt_consumer]]
    servers = ["tcp://localhost:1883"]
    qos = 0

    topics = [
      "dale",
      "chip/#",
    ]
    username = "user"
    password = "pass"

    data_format = "json"

    json_string_fields = [
      "battery"
    ]

### System info:

Initially seen in `Telegraf v1.7.3 (git: release-1.7 4dc29d0e)` updated to `1.8.0-rc1` to check if fix had been rolled in. 
Host OS is Ubuntu 16.04.5 LTS
mosquitto version 1.4.8 (build date Wed, 05 Sep 2018 15:51:27 -0300)
InfluxDB shell version: 1.6.1

### Steps to reproduce:

1. Push message containing quoted values via MQTT. Example `zigbee2mqtt:info 2018-9-16 17:33:17 MQTT publish, topic: 'chip/zoneTemp', payload: '{"temperature":19.43,"linkquality":57,"humidity":70.21,"pressure":1002,"battery":"100.00","voltage":3215}'`
2. Query field keys in InfluxDB

### Expected behavior:

Under mqtt_consumer there will be fieldKeys for temperature, linkquality, pressure, battery and voltage.

### Actual behavior:

There fieldKeys for temperature, linkquality, pressure and voltage but not battery.

### Additional info:

This appears to be because the value for battery is quoted, and so is treated like a string. It is ignored in the default behaviour. 
According to https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md the correct way to deal with this is to use `json_string_fields` or `tag_keys`. Neither of these work in the mqtt_consumer and result in errors seen in the log;

`E! Error parsing /etc/telegraf/telegraf.conf, line 3539: field corresponding to `json_string_fields' is not defined in `*mqtt_consumer.MQTTConsumer'`

I can see a commit that adds support for this, but it looks to have only touched the http post json plugin, and the test code for the mqtt_consumer.

**Comment by danielnelson** [comment]
These options will be available only in 1.8.0-rc1, can you make sure you are using this version?

**Comment by danielnelson** [comment]
Make sure you have the `s` on the end: `json_string_fields`

**Comment by kurbeco** [comment]
https://i.imgur.com/iWKad22.jpg

That was it, I can't believe did that. So sorry! I must've left it off when I swapped it from `tag_keys`.

Sorry for the noise!
