### ISSUE TITLE
Process start time in Procstat input plugin

### ISSUE THREAD

**Issue by nikolay-t** [influxdata/telegraf#4709]
## Feature Request

It will be good include process start time in Procstat input plugin.

### Proposal:

Add a new field for timestamp (i.e. Unix time stamp) for the time when reported process was started.

### Current behavior:

Not available.

### Use case: 

This information can be used to detect restarts of processes. PID can be used for the here as well, but what if PID gets the same as it was before after the restart.

**Comment by danielnelson** [comment]
I agree it would be a very useful feature.  We have another issue open for this, so lets merge these issues: #2203

**Comment by nikolay-t** [comment]
@danielnelson Thanks. I see there is completed PR for my request - https://github.com/influxdata/telegraf/pull/3895. It is in not-merged state for 6 months.  I don't see changes in it aside from procstat, so risks are minimal for the rest of Telegraf code. What is the point of keeping it not-merged?

**Comment by danielnelson** [comment]
This PR is still waiting for review, we need to look through all the fields that are being added as well as the methods that are used.  If we had a PR that only added the create time and left the other fields out we could probably get to it quicker.
