### ISSUE TITLE
SQL Server offline databases and Forwarded Records doesn't work

### ISSUE THREAD

**Issue by tboggiano** [influxdata/telegraf#4714]
### System info: SQL Server offline databases doesn't work

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
To report data back
### Actual behavior:
No data reported back
### Additional info:
Forwarded Records/sec is abbreviated and db_offline is looking at state 10 instead of state 6
[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
@tboggiano Can you provide more detail about how Forwarded Records/sec is abbreviated?  Perhaps an example of expected output vs actual output.

cc @m82labs

**Comment by m82labs** [comment]
It looks like there is a typo in the original PR that added this metric.
