### ISSUE TITLE
Telegraf cloudwatch plugin not working for AWS/Route53 name space

### ISSUE THREAD

**Issue by shreedhar22** [influxdata/telegraf#4715]
I am trying to use Telegraf cloudwatch plugin for retrieving AWS/Route53 metrics and the plugin doesn't seem to list any metrics for Route53. It works for SQS and RDS but not for Route53. The credentials and the other configs(I haven't listed them here are correct and they work for SQS and RDS namespace correctly). DNS records are already present in the route53 service in my AWS account. I am hoping to see HealthCheckStatus as listed here: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-health-checks.html

Here's the part where I have declared the plugin for route53 in telegraf.conf:

```
[[inputs.cloudwatch]]
  access_key = "xxxx"
  secret_key = "xxxx"
  region = "us-east-1"
  period = "5m"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/Route53"
  ratelimit = 200
```

System Info

- Telegraf version: Telegraf v1.6.0~04e0efb3 (git: revision1 04e0efb3)
- OS name/version: Ubuntu 14.04.5 LTS

**Comment by danielnelson** [comment]
@shreedhar22 Could you retest with Telegraf 1.12 and also with `period = "1m"` and let me know if you receive any results?
