### ISSUE TITLE
Make basicstats faster

### ISSUE THREAD

**Issue by markusr** [influxdata/telegraf#4723]
### Steps to reproduce:

1. Config basicstats to only do 
```
stats = ["count", "min" , "max" , "mean"]
```

### Expected behavior:
"mean" is calculated at the ```Push``` by dividing 
```
v.sum / v.count
```

### Actual behavior:
All values also variance are calculated on each ```Add```
https://github.com/influxdata/telegraf/blob/master/plugins/aggregators/basicstats/basicstats.go#L107

### Additional info:
I tested this on a raspberry pi 3. 

After removing the "online" calculation part the cpu usage dropped from 72% to 35%. (3000 metric per second input and 5s aggregation time).

Another idea would be to add  ```sum``` and ```mean``` to the ```minmax``` aggregator or a complete new aggregator.

**Comment by danielnelson** [comment]
@markusr I think we need the online mean for the online variance, but we should get a big performance gain by switching from `Fields()` to `FieldList()`.  I made this change in #4741, can you compare the performance with this code?

**Comment by markusr** [comment]
@danielnelson 
You are right. #4741 gives the same speed up. The CPU usage I measured was on the same level (35.41%) as my test before.  

It can be merged.
