### ISSUE TITLE
csv_delimiter works wrong in csv data format

### ISSUE THREAD

**Issue by WuBingzheng** [influxdata/telegraf#4725]
### Relevant telegraf.conf:

    [[inputs.tail]]
      files = ["/path/test.csv"]
      data_format = "csv"
      csv_column_names = ["ts","a","b"]
      #csv_delimiter = ","
      #csv_timestamp_column = "ts"
      #csv_timestamp_format = "2006-01-02T15:04:05.999-0700"

### System info:

Telegraf 1.8.0~rc2 (git: HEAD f54bbd6e)

Ubuntu

### Steps to reproduce:

1. It works fine with the above configure file.
2. However if `csv_delimiter = ","` is configure, telegraf does not split the text line.
3. If `csv_delimiter` is configured by other value, such as `";"`, telegraf will split the text line by a different char.

### Expected behavior:

Telegraf should behavior same whether `csv_delimiter = ","` is configured or not, because it's the default value.

Telegraf should also works if  `csv_delimiter` is configure with other value (such as `;`).

### Actual behavior:

1. If `csv_delimiter = ","` is configured, the text line is not be split by ',', while the whole line is taken as the first field.

2. If `csv_timestamp_column` is used too, the timestamp filed fails to be parsed: (the same reason with last case)

    ```
    E! Error in plugin [inputs.tail]: E! Malformed log line in /path/test.csv: [2018-09-20T12:13:32.750+0800,1,2], Error: parsing time "2018-09-20T12:13:32.750+0800,": extra text: ,
    ```

3. If `csv_delimiter` is configured with not the default value, such as `";"`, it seems that char `5` is used as the delimiter. The text line `2018-09-20T12:13:32.750+0800;1;3` is split into `["2018-09-20T12:13:32.7", "0+0800;1;3"]`. If `csv_timestamp_column` is used, it gives the error:

    ```
    E! Error in plugin [inputs.tail]: E! Malformed log line in /path/test.csv: [2018-09-20T12:13:32.750+0800;1;3], Error: parsing time "2018-09-20T12:13:32.7" as "2006-01-02T15:04:05.999-0700": cannot parse "" as "-0700"
   ```

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Thanks for the detailed report

**Comment by bbergshaven** [comment]
I found the reason and a solution.
Line 234 in plugins/parsers/registry.go should use "%c" instead of "%v"
`delimiter = fmt.Sprintf("%c", runeStr[0])`
Same for line 242
