### ISSUE TITLE
csv parser: `csv_trim_space' is not defined in `*file.File'

### ISSUE THREAD

**Issue by mvhconsult** [influxdata/telegraf#4727]
### Relevant telegraf.conf:
1.8 RC csv following the readme.md
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. create a conf file
2. run 1.8RC2

### Expected behavior:
No error
### Actual behavior:
telegraf errors out. Disabling the option completely in the config file makes telegraf work.
### Additional info:

[Include gist of relevant config, logs, etc.]
Error parsing /etc/telegraf/telegraf.d/csv.conf, line 39: field corresponding to `csv_trim_space' is not defined in `*file.File'

**Comment by danielnelson** [comment]
Thanks for the report, I fixed this in 1e3e28428d8c9cf00a6350fd381d938b2f90373c and we will include this in the next rc.
