### ISSUE TITLE
Optional argument to ignore bad configs

### ISSUE THREAD

**Issue by absolutejam** [influxdata/telegraf#4729]
### Proposal:

Argument to allow Telegraf to ignore bad config files instead of throwing a critical exception.

### Current behavior:

Currently, a bad telegraf config (Within `--config-directory`) will kill the Telegraf agent.

### Desired behavior:

Option to ignore bad config file and log an message instead.

### Use case: [Why is this important (helps with prioritizing requests)]

I didn't see a way to validate configs (Did I miss this), and at the moment, a badly rendered config file from SaltStack causes the entire service to fail. I'd like to ignore bad configs and allow metrics collection to continue instead of having a blackspot in our collection.

On a side note, is there a way to validate configs?

Cheers!

**Comment by absolutejam** [comment]
Actually, it looks like the `--test` param can validate the config, but I'd still like this option to be considered :smile:

**Comment by danielnelson** [comment]
I think this would be a good feature, maybe not for the agent section but at least for plugins, and I especially like the idea of an option to validate the config.

Here is a related issue about Telegraf not starting when an ouput connection cannot be made: #3723

**Comment by sspaink** [comment]
Closing in favor of: https://github.com/influxdata/telegraf/issues/5507
I think adding a way to validate configs is a good idea.
