### ISSUE TITLE
Add Jolokia proxy mode

### ISSUE THREAD

**Issue by panda87** [influxdata/telegraf#473]
Hi

The Jolokia plugin that @saiello wrote is very good, but for some cases is not help like the following,
Jolokia has 2 options agent and proxy modes. The current plugin is build for the agent mode, but for cases that I don't want to setup the agent as a dependency in my project or in case I have container that I dont want to add another articats inside, Jolokia is support the proxy mode.

For implementation design the only different is the proxy acting as POST request with body, like the example from the Jolokia documentation:
```
  {
    "type" : "read",
    "mbean" : "java.lang:type=Memory",
    "attribute" : "HeapMemoryUsage",
    "target" : { 
         "url" : "service:jmx:rmi:///jndi/rmi://targethost:9999/jmxrmi",
         "user" : "jolokia",
         "password" : "s!cr!t"
    } 
  }
```
@saiello can you pls try to add this to the current plugin or maybe someone else?

Thanks

**Comment by saiello** [comment]
Hi 
@panda87 's suggestion is right!

The plugin configuration could be something like

```
[jolokia]
mode = "proxy"  // default is 'agent'

// used only in proxy mode
[jolokia.proxy]
host = "jolokia.proxy.my-domain.org"
port = "8000"

[[jolokia.servers]]
  name = "as-service-1"
  host = "127.0.0.1"
  port = "8080"
// used only in proxy mode
  user = "jolokia"
  password = "s!cr!t"

[[jolokia.metrics]]
  name = "heap_memory_usage"
  mbean = "java.lang:type=Memory",
  attribute = "HeapMemoryUsage",
  pass = ["used", "max"]
```

I'll provide an implementation on my fork as soon as possible. @panda87, I'll notify you when ready.

**Comment by panda87** [comment]
Thanks @saiello this feature is super important for me and I believe for others that wan to use this plugin in their systems!
Thanks for the effort!

**Comment by saiello** [comment]
Hi,
I just complete a simple naive implementation of what we expect branching the 0.2.4 of this repo.

You could find the source code at: https://github.com/saiello/telegraf/tree/feature/jolokia-as-proxy-mode even though I need to improve and write some test as well.

@panda87 If you have some more suggestions or you figure out some issues...

**Comment by panda87** [comment]
Thanks @saiello, I'll do my best to try the new feature in day or two and keep you updated with my findings.

**Comment by sparrc** [comment]
@saiello please hold off on sending up a PR, I am trying to finish 0.3.0 (see #437), and will need the changes to be rebased off of 0.3.0 anyways

**Comment by panda87** [comment]
I made tests to the plugin and it looks very good.
I have only one issue that I want to check if this Jolokia or plugin issue.
The problem is when my mbean look like this:

```
  [[plugins.jolokia.metrics]]
    name = "LogEndOffset"
    mbean  = "kafka.log:type=Log,name=LogEndOffset,*"
    attribute = "Value"
```

The result is one big serializing json that instead of split it to many tags, im getting one long tag like this example: `kafka.log:name=LogEndOffset,partition=0,topic=Production,type=Log` and the value look like this: `map[Value:2]`

Do you think that you can make a change here or this related to the jolokia agent?

Thanks

**Comment by saiello** [comment]
@sparrc don't worry.

@panda87 Could you paste here the jolokia response you obtain calling the agent directly?

**Comment by sparrc** [comment]
@saiello 0.10.0 (prev 0.3.0) has been merged to master, so feel free to forge ahead

**Comment by darsh221** [comment]
I want to use Jolokia proxy mode but i think latest release http://get.influxdb.org/telegraf/telegraf_0.12.0-1_amd64.deb doesn't have these changes. Which branch i should to build telegraf so that i can get all latest changes up to 0.12.0 along with Jolokia proxy mode?

**Comment by sparrc** [comment]
@darsh221 there are no changes, that's why this is an open issue

**Comment by saiello** [comment]
Hi @sparrc @darsh221 I sent a PR https://github.com/influxdata/telegraf/pull/1031 for this right now.
