### ISSUE TITLE
telegraf stops sending data to influx

### ISSUE THREAD

**Issue by ElFishi** [influxdata/telegraf#4731]
I use telegraf to collect MQTT data and send the to Influx. 
In irregular intervals telegraf stops sending data. The instance is still there but seems to do nothing. When telegraf is restarted everything works again as expected. 

### System info:
Telegraf v1.7.4 (git: release-1.7 578db7ef)
Raspbian GNU/Linux 9 (stretch), Rpi 3
[trace.txt](https://github.com/influxdata/telegraf/files/2406120/trace.txt)

stack trace is attached.

**Comment by glinton** [comment]
How is your resource utilization at the time it stops reporting? I wonder if they get exhausted.

**Comment by ElFishi** [comment]
I monitor CPU loads and memory. Maximum load around the time the data flow stopped was 0.25, available memory around 700MB.  

Correct me if I'm wrong, but 4580 sounds as if there is no data flowing to Influx at all. My problem is that it all works and then stops at some random time. 
4594 is concerned with MQTT disconnects. I, too, have disconnects in my journal but according to the log telegraf always reconnects successfully. 
E.g. the lines before the SIGQUIT in my stack trace look like this:
```
Sep 18 17:30:25 Zorin telegraf[481]: 2018-09-18T15:30:25Z E! Error in plugin [inputs.mqtt_consumer]: E! MQTT Connection lost
Sep 18 17:30:25 Zorin telegraf[481]: error: pingresp not received, disconnecting
Sep 18 17:30:25 Zorin telegraf[481]: MQTT Client will try to reconnect
Sep 18 17:30:25 Zorin telegraf[481]: 2018-09-18T15:30:25Z I! MQTT Client Connected
Sep 18 20:52:35 Zorin telegraf[481]: 2018-09-18T18:52:35Z E! Error in plugin [inputs.mqtt_consumer]: E! MQTT Connection lost
Sep 18 20:52:35 Zorin telegraf[481]: error: pingresp not received, disconnecting
Sep 18 20:52:35 Zorin telegraf[481]: MQTT Client will try to reconnect
Sep 18 20:52:35 Zorin telegraf[481]: 2018-09-18T18:52:35Z I! MQTT Client Connected
Sep 18 21:12:45 Zorin telegraf[481]: 2018-09-18T19:12:45Z E! Error in plugin [inputs.mqtt_consumer]: E! MQTT Connection lost
Sep 18 21:12:45 Zorin telegraf[481]: error: pingresp not received, disconnecting
Sep 18 21:12:45 Zorin telegraf[481]: MQTT Client will try to reconnect
Sep 18 21:12:45 Zorin telegraf[481]: 2018-09-18T19:12:45Z I! MQTT Client Connected
Sep 20 22:41:54 Zorin telegraf[481]: SIGQUIT: quit
```

**Comment by danielnelson** [comment]
Can you test if this change helps: https://github.com/influxdata/telegraf/pull/4846#issuecomment-428762836
