### ISSUE TITLE
SHA256 of latest 1.8.0 release is incorrect

### ISSUE THREAD

**Issue by matt-smith** [influxdata/telegraf#4737]
looks as though the SHA256 of the latest 1.8.0 packages is incorrect - https://github.com/influxdata/telegraf/releases/tag/1.8.0

**Comment by danielnelson** [comment]
Thanks for the reporting this issue, luckily it looks like this was just a mistake in the release notes.

The releases are built on CircleCI and the uploaded packages were built from this tag build (under `make package-release`):
https://circleci.com/gh/influxdata/telegraf/19504

It looks like I have used the hashes from the branch build (under `make package`):
https://circleci.com/gh/influxdata/telegraf/19506

**Comment by danielnelson** [comment]
Github release page and [InfluxData downloads page](https://portal.influxdata.com/downloads) for 1.8.0-rc1, 1.8.0-rc2, and 1.8.0 have been updated with the hashes from the correct CircleCI build.

**Comment by matt-smith** [comment]
Thanks @danielnelson! really appreciate the quick response 👍
