### ISSUE TITLE
Telegraf fails with 'unable to parse' error on node, where cassandra was deployed

### ISSUE THREAD

**Issue by Selllavi** [influxdata/telegraf#4745]
### System info:

Telegraf - version 1.3.3

### Steps to reproduce:

1. deploy Cassandra on some nodes
2. deploy telegraf on the same nodes and turn on gathering docker metrics via adding in telegraf.conf

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  name_prefix = "t_"
  timeout = "10s"
  perdevice = true

### Expected behavior:
Telegraf will gather all metrics from all nodes, even if Cassandra was deployed on them.

### Actual behavior:
We have many errors like that

unable to parse ',io.kubernetes.pod.namespace=cassandra,name=CentOS\ Base\ Image,container_name=k8s_cassandra.23717d93_cassandra-0_cassandra_f6f2b905-bd9f-11e8-9803-fa163e8c6855_e1d77d2f io_service_bytes_recursive_sync=161698816i,io_serviced_recursive_write=10475i,io_serviced_recursive_sync=10463i,io_serviced_recursive_async=206i,container_id="ea92be60ba5987253898f5c4ee49066b1a1eb0a471718e280bbfa3ce97e3a336",io_service_bytes_recursive_read=3735552i,io_service_bytes_recursive_async=3878912i,io_service_bytes_recursive_total=165577728i,io_serviced_recursive_read=194i,io_serviced_recursive_total=10669i,io_service_bytes_recursive_write=161842176i 1537799640000000000': missing measurement dropped=0]

unable to parse 't_docker_container_blkio,io.kubernetes.container.restartCount=0,vendor=CentOS,io.kubernetes.pod.name=cassandra-0,device=252:0,io.kubernetes.pod.uid=f6f2b905-bd9f-11e8-9803-fa163e8c6855,container_image=<image>,host=ci-master-node-2-3,io.kubernetes.pod.terminationGracePeriod=10,io.kubernetes.container.terminationMessagePath=/dev/termination-log,io.kubernetes.container.preStopHandler={\"exec\":{\"command\":[\"/bin/sh\"\,\"-c\"\,\"nodetool\ drain\"]}},license=GPLv2,container_version=development_latest,io.kubernetes.container.name=cassandra,io.kubernetes.container.ports=[{\"name\":\"intra-node\"\,\"containerPort\":7000\,\"protocol\":\"TCP\"}\,{\"name\":\"tls-intra-node\"\,\"containerPort\":7001\,\"protocol\":\"TCP\"}\,{\"name\":\"jmx\"\,\"containerPort\":7199\,\"protocol\":\"TCP\"}\,{\"name\":\"cql\"\,\"containerPort\":9042\,\"protocol\":\"TCP\"}],engine_host=<engine_host>,build-date=20170911,io.kubernetes.container.hash=23717d93,io.kubernetes.pod.data={\"kind\":\"Pod\"\,\"apiVersion\":\"v1\"\,\"metadata\":{\"name\":\"cassandra-0\"\,\"generateName\":\"cassandra-\"\,\"namespace\":\"cassandra\"\,\"selfLink\":\"/api/v1/namespaces/cassandra/pods/cassandra-0\"\,\"uid\":\"f6f2b905-bd9f-11e8-9803-fa163e8c6855\"\,\"resourceVersion\":\"15673128\"\,\"creationTimestamp\":\"2018-09-21T13:12:17Z\"\,\"labels\":{\"app\":\"cassandra\"\,\"name\":\"cassandra\"}\,\"annotations\":{\"kubernetes.io/config.seen\":\"2018-09-21T13:12:18.600968045Z\"\,\"kubernetes.io/config.source\":\"api\"\,\"kubernetes.io/created-by\":\"{\\"kind\\":\\"SerializedReference\\"\,\\"apiVersion\\":\\"v1\\"\,\\"reference\\":{\\"kind\\":\\"StatefulSet\\"\,\\"namespace\\":\\"cassandra\\"\,\\"name\\":\\"cassandra\\"\,\\"uid\\":\\"f6e3420d-bd9f-11e8-816e-fa163ec72748\\"\,\\"apiVersion\\":\\"apps\\"\,\\"resourceVersion\\":\\"15673101\\"}}\n\"\,\"openshift.io/scc\":\"anyuid\"\,\"pod.beta.kubernetes.io/hostname\":\"cassandra-0\"\,\"pod.beta.kubernete

unable to parse ',vendor=CentOS,build-date=20170911,io.kubernetes.container.preStopHandler={\"exec\":{\"command\":[\"/bin/sh\"\,\"-c\"\,\"nodetool\ drain\"]}},io.kubernetes.pod.uid=f6f2b905-bd9f-11e8-9803-fa163e8c6855,container_image=<image>,io.kubernetes.container.name=cassandra,cpu=cpu1,host=ci-master-node-2-3,io.kubernetes.pod.namespace=cassandra usage_total=761797786281i,container_id="ea92be60ba5987253898f5c4ee49066b1a1eb0a471718e280bbfa3ce97e3a336" 1537799640000000000': missing measurement
Sep 24 14:41:27 ci-master-node-2-3<company> telegraf[123139]: "default\"\,\"serviceAccount\":\"default\"\,\"nodeName\":\"ci-master-node-2-3\"\,\"securityContext\":{\"seLinuxOptions\":{\"level\":\"s0:c17\,c4\"}}\,\"imagePullSecrets\":[{\"name\":\"default-dockercfg-m1p50\"}]}\,\"status\":{\"phase\":\"Pending\"\,\"conditions\":[{\"type\":\"PodScheduled\"\,\"status\":\"True\"\,\"lastProbeTime\":null\,\"lastTransitionTime\":\"2018-09-21T13:12:18Z\"}]}}': missing fields

and so on(There are many errors in logs). 

All nodes, on which Cassandra was deployed, (we have three of them) don't send any metrics.
(not only docker metrics, all metrics, even from another telegraf plugins like inputs.system, inputs.mem and etc. ).
But sometimes, approximately, once in ten minutes some metrics loaded from these nodes. 
All another nodes, without deployed Cassandra on them, send all metrics successfully continuously.

### Additional info:
Maybe we did something wrong and it is configuration issue, but i couldn't find any similar bug report on your bug tracker.
Also, we have the same 'unable to parse' error on node, where RabbitMQ was deployed, and this node also finished send any metrics after turn on 'docker.inputs'.
If we remove this plugin(inputs.docker) from telegraf.conf, telegraf will send metrics successfully from these nodes.

**Comment by danielnelson** [comment]
This has been fixed for quite some time now, can you update to a newer Telegraf?

**Comment by Selllavi** [comment]
Thank you for answer. 
In which version was it fixed?

**Comment by danielnelson** [comment]
I believe it was fixed in no later than 1.6.  I also recommend using the label options to control what docker labels are added to the docker metrics, as k8s adds a lot of large labels.  This *may* prevent the error from occurring even in 1.3:
```
  docker_label_exclude = ["annotation.kubernetes*"]
```
