### ISSUE TITLE
Per-directory file counts in the Filecount plugin

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#4749]
### Proposal:

Perhaps the `directory` section of the plugin config becomes a glob...similar to the `file` section?

### Current behavior:

Recursively totals the number of occurrences of certain types/names of files within a higher level directory

### Desired behavior:

I think it would benefit our users to see the file counts by name in each subdirectory of the top level directory you feed the config.

### Use case: [Why is this important (helps with prioritizing requests)]

The first use case I could think of for this was counting `tsm` and `tsi` files in an `influxdb/data` directory.  Getting the full count is fine for keeping track, at a high level, of how many data files you're generating.  However, for debugging purposes, it would be nice to know if certain shard directories are acting up (i.e., not compacting enough files, producing too many files, etc.).  The current behavior won't provide this information.

**Comment by danielnelson** [comment]
We could convert directory to a glob and all expansions would be tagged separately:
```
[[inputs.filecount]]
  directory = "/var/lib/influxdb/data/telegraf/autogen/*"
```

```
ls /var/lib/influxdb/data/telegraf/autogen
459  462
```

```
filecount,directory=/var/lib/influxdb/data/telegraf/autogen/459 count=42i
filecount,directory=/var/lib/influxdb/data/telegraf/autogen/462 count=42i
```

**Comment by Jaeyo** [comment]
how about use `directories` than `directory` like file input.
