### ISSUE TITLE
Support IPVS metrics

### ISSUE THREAD

**Issue by amoghe** [influxdata/telegraf#4757]
## Feature Request

I'd like to implement an input plugin for reporting IPVS metrics (for "virtual_server" and "real_server").

### Proposal:

Proposal is to add this in phases. 

## Phase 1 
Add metrics to track "virtual_services". They are namespaced under "virtual_server" so that we can disinguish between them and the "real_server" metrics (see phase 2). 

These are the readily available metrics:
- Connections (`virtual_server.connections`) 
- PacketsIn (`virtual_server.pkts_in`)
- PacketsOut (`virtual_server.pkts_out`)
- BytesIn (`virtual_server.bytes_in`)
- BytesOut  (`virtual_server.bytes_out`)
- CPS (`virtual_server.cps`)
- PPSIn (`virtual_server.pps_in`)
- PPSOut (`virtual_server.pps_out`)
- BPSIn (`virtual_server.bps_in`)
- BPSOut (`virtual_server.bps_out`)

Each metric has the following tags:
- `address`
- `protocol`
- `port`
- `fwmark` (if it is non zero)

## Phase 2
Add metrics to track each of the above metrics, except this time for each "real_server" that backs each of the above "virtual_server"

Each "destination"s metrics will need to contain an additional tag that indicates which "service" it was backing. For this we add
- `service` : concat(`protocol`, `address`, `port`, `fwmark`) with some separator (`-`)

### Use case: [Why is this important (helps with prioritizing requests)]

Help monitoring linux virtual servers.

**Comment by amoghe** [comment]
The terminology is different depending on where you look. The golang libraries call them "Services" and "Destinations" , however the IPVS terminology is "Virtual Server" and "Real Server".

A virtual server is configured to be backed by one or more real servers (that can actually handle the traffic). The virtual server is just a load balancer.

The virtual server can be configured to schedule connections based on proto/addr/port/fwmark (addr+port being commonly used).

These metrics are exposed via the kernel over a netlink interface. There is a pure-go library to deal with netlink sockets and parsing these messages here - github.com/mqliang/libipvs however I've forked it to add a `Close()` method (to allow for graceful error handling and reopen/retry). That is available here - https://github.com/amoghe/libipvs. There is a PR open to merge it back. Once that happens we can switch to that.

**Comment by amoghe** [comment]
I'll switch to using `virtual_server` and `real_server` in the code and documentation. I think it is better to align the terminology with IPVS one than the one used by the libraries.

**Comment by danielnelson** [comment]
Looks like libipvs uses github.com/hkwi/nlgo for netlink.  I know we have some other netlink work in progress, @fntlnz is this the same library your work is using?

In phase 2 the sum of the values for the real servers would be equal to the value for the virtual server?  Or perhaps only approximately due to network issues or unavailability?

**Comment by amoghe** [comment]
While there are other libraries that are available for manipulating `ipvs` from go - including one that ships in docker (`github.com/docker/libnetwork/ipvs`), this library (`libipvs`) is the only one that seems to handle deserialization of the stats block correctly (which is what we're interested in). The other libraries either dont support it , or dont handle it well.

Another promising one is github.com/google/seesaw/ipvs - but that uses a go interface to netlink that goes via the `C` interface (and needs `libnh` to be installed).

**Comment by amoghe** [comment]
> in phase 2 the sum of the values for the real servers would be equal to the value for the virtual server?

Yes, from my experimentation that seems to be the case but I wouldnt be surprised if it wasn't . They are being reported separately from the kernel.

**Comment by amoghe** [comment]
Updated the _Feature Request_ comment to reflect the updated proposal (naming scheme of the metrics).

**Comment by amoghe** [comment]
Here is a similar name scheme, but first some background...

Typically a single `virtual_server` is backed by several `real_servers`. So the output from `ipvsadm` can look like this:
```
TCP  172.18.64.234:9001             352665  3537412        0  936807K        0
  -> 172.18.64.201:9001              17839   179535        0 47392524        0
  -> 172.18.64.202:9001              18045   180643        0 47660176        0
  -> 172.18.64.203:9001              16910   170472        0 45050422        0
  -> 172.18.64.204:9001              17551   176566        0 46663660        0
  -> 172.18.64.205:9001              17113   172243        0 45421224        0
  -> 172.18.64.206:9001              17437   175234        0 46233126        0
  -> 172.18.64.207:9001              17752   179486        0 47390798        0
  -> 172.18.64.208:9001              17268   173417        0 45836000        0
```

Here, the first line (with the prefix *TCP*) indicates that this is a section for a virtual server, and the lines that follow are its real servers.

Now, a virtual server is defined by one of
- proto + ip + port
- fwmark

So in the above pasted output we can tell that the virtual server is using `proto + ip + port`. However, the following are also possible:

```
UDP  172.18.64.234:9003                  0        0        0        0        0
  -> 172.18.64.201:9003                  0        0        0        0        0
  -> 172.18.64.202:9003                  0        0        0        0        0
  -> 172.18.64.203:9003                  0        0        0        0        0
  -> 172.18.64.204:9003                  0        0        0        0        0
```
... or ...
```
FWM  47                                  0        0        0        0        0
  -> 172.18.64.201:9000                  0        0        0        0        0
  -> 172.18.64.202:9000                  0        0        0        0        0
  -> 172.18.64.203:9000                  0        0        0        0        0
  -> 172.18.64.204:9000                  0        0        0        0        0
  -> 172.18.64.205:9000                  0        0        0        0        0
```

In the example above, we see that `fwmark` is being used to determine what traffic gets forwarded to these real servers.

So, with this as background , a virtual servers metrics (when using `proto+ip+port`) maybe something like this:
```
ipvs.virtual_server.bytes_in,addr=10.1.2.3,port=443,proto=tcp value=42 
```
Or when using `fwmark`, they may be like this:
```
ipvs.virtual_server.bytes_in,fwmark=99 value=42
```
Since these 2 schemes are mutually exclusive, this plugin will emit one of the above.

Does this make sense?

**Comment by amoghe** [comment]
Yes, I think we're in agreement on the line protocol format.

As for using the `vishvananda/netlink` lib - let me poke around and see how easy it is to get IPVS support using that as the underlying netlink lib. I agree that using just one dependency is desirable, but I'd hate for that to be a gating factor. I'll update this thread with what I find.

On a related note, I docs to be lacking on the following topics:
1. explain how the `SampleConfig` gets translated to members on the struct (camel to snake case, who sets the members?). From the example in CONTRIBUTING.md it isn't clear (to me) how the config key/values get set on the struct that I instantiate in the `Creator`. 
2. some guidance on adding info/error/debug logs. I could look at how other plugins do it, but I think it should be captured somewhere in the CONTRIBUTING.md (under the input plugins guidelines section).

**Comment by danielnelson** [comment]
IPVS is becoming popular for use with kube proxy, so adding k8s tag.

**Comment by danielnelson** [comment]
I'll update the docs with answers to your questions, but the short answer is you should use a struct tag for each field instead of relying on the default camelcase conversion:
```
type struct IPVS {
	FooBar []string `toml:"foo_bar"`
}
```

For errors fatal to the gather attempt return an error out of Gather, if the gather should continue use:
```
log.Printf("E! Error in plugin [inputs.ipvs]: %v", err)
```

You can use `I!`, `D!`, `E!` for info, debug, error level.

**Comment by amoghe** [comment]
@danielnelson can we take on the lib change as a "Phase 3" item? I'd like to proceed using the existing library (which is pure-go, so not a burning issue, imo) . Later we can switch to using the `visvananda/netlink` lib once I contribute the code there.

**Comment by amoghe** [comment]
PR #4792

**Comment by danielnelson** [comment]
The items under phase 1 above are completed for 1.9.0.

**Comment by danielnelson** [comment]
Closing, all items completed.

**Comment by amoghe** [comment]
@danielnelson  are there specific tests to run for this plugin during the RC phase of `1.9` ?
