### ISSUE TITLE
Spurious leading space in syslog message

### ISSUE THREAD

**Issue by candlerb** [influxdata/telegraf#4761]
### Relevant telegraf.conf:

[Sample syslog config](https://github.com/influxdata/telegraf/tree/release-1.8/plugins/inputs/syslog#configuration) exactly as given
 
### System info:

Telegraf 1.8.0-1 installed from apt repo; Ubuntu 16.04.5 amd64

### Steps to reproduce:

1. Configure telegraf syslog receiver exactly as per sample configuration
2. Configure rsyslog to forward to telegraf exactly as per sample configuration
3. Run `tcpdump -i lo -nn -s0 -X tcp port 6514` to capture the incoming message
4. Submit a message using `logger foo`
5. Query influxdb to view the message

### Expected behavior:

The content of the message in influxdb is exactly `foo`

### Actual behavior:

The message in influxdb contains a leading space:

```
> select * from syslog where message = 'foo'
> select * from syslog where message = ' foo'
name: syslog
time                           appname facility facility_code host hostname message procid severity severity_code timestamp           version
----                           ------- -------- ------------- ---- -------- ------- ------ -------- ------------- ---------           -------
2018-09-27T10:27:39.865151471Z root    user     1             tick tick      foo           notice   5             1538044059862806000 1
```

In general, you'll see some messages with and without the leading space:

```
> select * from syslog where message =~ /^ /
> select * from syslog where message !~ /^ /
```

### Additional info:

tcpdump shows that there are in fact two spaces in the inbound message:

```
	0x0030:  2c7e 13bd 3630 203c 3133 3e31 2032 3031  ,~..60.<13>1.201
	0x0040:  382d 3039 2d32 3754 3130 3a32 373a 3339  8-09-27T10:27:39
	0x0050:  2e38 3632 3830 362b 3030 3a30 3020 7469  .862806+00:00.ti
	0x0060:  636b 2072 6f6f 7420 2d20 2d20 2d20 2066  ck.root.-.-.-..f
	0x0070:  6f6f 0a                                  oo.
```

However I believe this is required by the formatting in RFC 5424, separating the non-existent STRUCTURED-DATA section:

```
   SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]
```

I think that telegraf's syslog reader should parse this out properly.

**Comment by danielnelson** [comment]
@leodido Can you take a look and let us know if we should open an issue in https://github.com/influxdata/go-syslog?

**Comment by leodido** [comment]
Since there are two white spaces in the inbound message I think the parser is catching it correctly.

Ie.,
SP for the first white space, the second one is initial character of MSG.

Probably is rsyslog to add a space in front of "foo" message during forwarding.

We could provide an option to trim white spaces in syslog input plugin, maybe.

**Comment by candlerb** [comment]
> Since there are two white spaces in the inbound message I think the parser is catching it correctly.

I did a more careful examination of the BNF from RFC 5424, and I think you're right.

```
      SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]

      HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID
...
      STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT
...
      NILVALUE        = "-"
```

The sample log message is `<13>1 2018-09-27T10:27:39.862806+00:00 tick root - - - {spc}foo`

* HEADER
    * PRI: `<13>`
    * VERSION: `1`
    * TIMESTAMP: `2018-09-27T10:27:39.862806+00:00`
    * HOSTNAME: `tick`
    * APP-NAME: `root`
    * PROCID: `-`
    * MSGID: `-`
* STRUCTURED-DATA: `-`
* MSG: `{spc}foo`

**Comment by danielnelson** [comment]
You can use the `strings` processor to trim whitespace from fields:
```toml
[[processors.strings]]
  namepass = "syslog"
  [[processors.strings.trimleft]]
    field = "message"
```
