### ISSUE TITLE
MySQL plugin should continue collecting metrics even if some fail

### ISSUE THREAD

**Issue by Castaglia** [influxdata/telegraf#4770]
### Relevant telegraf.conf:

```
[global_tags]

[agent]
  hostname = "mysql.example.com"
  omit_hostname = false
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  logfile = "/var/log/telegraf/telegraf.log"
  debug = false
  quiet = false

#
# OUTPUTS:
#
[[outputs.influxdb]]
  database = "telegraf"
  urls = ["http://influxdb.example.com:8086"]
  write_consistency = "any"

#
# INPUTS:
#
[[inputs.cpu]]
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.mysql]]
  gather_binary_logs = true
  gather_event_waits = true
  gather_file_events_stats = true
  gather_index_io_waits = true
  gather_perf_events_statements = true
  gather_table_io_waits = true
  gather_table_lock_waits = true
  gather_info_schema_auto_inc = true
  servers = ["dbmon:...@tcp(127.0.0.1:3306)/"]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```
### System info:

Telegraf version:
```
$ telegraf --version
Telegraf v1.7.4 (git: release-1.7 578db7ef)
```
OS version:
```
$ uname -a
Linux mysql.example.com 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Platform version:
```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

### Expected behavior:

The MySQL plugin will attempt to collect all of the requested metrics, even if the gathering of some of those metrics fails due to _e.g._ database user permissions not being present.

### Actual behavior:

Our monitoring database user did not have sufficient permissions for the `gather_binary_logs` metrics.  And in particular, we were looking for the `gather_info_schema_auto_inc` metrics, and not seeing them.

We then started modifying our Telegraf configuration to enable the metrics, one by one -- and they all succeed.  _Until_ we enabled the `gather_binary_logs` -- and then we stopped seeing the other metrics.  We speculate that it was due to the permissions of the monitoring user not being able to gather the binary logs metrics.

### Additional info:

Relevant log message from `/var/log/telegraf/telegraf.log`:
```
2018-09-28T10:28:10Z E! Error in plugin [inputs.mysql]: Error 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation
```

In the MySQL plugin, we see the typical "return on error" behavior -- and that the `gather_binary_log` metrics is one of the _first_ operations attempted:

  https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mysql/mysql.go#L438

This means that the permissions issue (or any other error) for `gather_binary_logs` prevents the gathering of the _other_ metrics, which is unexpected and not desirable behavior.

Instead, we would expect that the plugin would log the failure to collect those metrics, and continue on to gathering the other configured metrics; ignoring failures and making a best effort to gather and emit as many metrics as it can, rather than erroring out early.

**Comment by dataviruset** [comment]
Not the same problem as this, but I had a similar issue where the MySQL input would delay collecting metrics from other servers if one of the servers had a slow response. I solved this by setting the readTimeout and writeTimeout options in the DSN as described here. The defaults are way too long.
https://github.com/go-sql-driver/mysql#connection-pool-and-timeouts
But I agree with the OP here that it would be nice to continue gathering other metrics even if some of them failed.

**Comment by danielnelson** [comment]
@dataviruset  If you want greater isolation with multiple servers you may want to define one server per plugin.  The configuration does end up with quite a bit of duplication this way but one MySQL server won't be able to stop another server from running; when they are all in a single plugin the gather must complete for all servers before the next can begin.
```
[[inputs.mysql]]
  servers = ["tcp(server1:3306)/"]
  # all the options

[[inputs.mysql]]
  servers = ["tcp(server2:3306)/"]
  # all the options again
```

This is really a general tip and it applies to any plugin that takes a list of addresses.

**Comment by dataviruset** [comment]
@danielnelson Even though it would add some duplicated configuration, that's a good workaround, thanks for the suggestion!

**Comment by sspaink** [comment]
It seems the proposed workaround to separate the configurations to multiple plugin sections worked, although adding duplication. Closing this issue as there hasn't been any activity on it for quite some time. If you are still interested in seeing this feature request implemented please leave a comment. Thank you!
