### ISSUE TITLE
Running as Windows Service ignored --config-directory option

### ISSUE THREAD

**Issue by dp1140a** [influxdata/telegraf#4771]
### Relevant telegraf.conf:
I just used a file output so I could see what was being output during test runs
<<telegraf.conf>>
[[inputs.win_perf_counters]]

    [[inputs.win_perf_counters.object]]
        ObjectName = "LogicalDisk"
        Instances = ["*"]
        Counters = ["% Disk Read Time", "% Disk Time", "% Disk Write Time", "% Free Space", "% Idle Time", "Disk Reads/sec", "Disk Writes/sec", "Free Megabytes"]
        Measurement = "win_logicaldisk"
        IncludeTotal=false

<<winperf.conf>>
[[inputs.win_perf_counters]]

    [[inputs.win_perf_counters.object]]
        ObjectName = "Memory"
        Counters = ["Available Bytes", "Cache Bytes"]
        Instances = ["------"]
        Measurement = "win_mem"
        IncludeTotal=false

### System info:
Running on Windows10 and Windows Server 2012

### Steps to reproduce:
1. Edit telegraf.conf
2. add winperf.conf file to telegraf.d folder
3. Create a Telegraf service on Windows
4. Edit Windows Service to manually add in the --config-directory option to the executable path
   >sc config telegraf binpath= "[path to telegraf] --config-directory [path to telegraf.d] --config [path to config]"
5. Start the service

### Expected behavior:
Output would include the win_mem measurement:
```
win_mem,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,objectname=Memory Available_Bytes=12410687488,Cache_Bytes=66146304 1537908121000000000
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=C:,objectname=LogicalDisk Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=71.6556625366211,Percent_Idle_Time=99.97417449951172,Disk_Reads_persec=0,Disk_Writes_persec=0,Free_Megabytes=163721,Percent_Disk_Read_Time=0 1537908121000000000
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=D:,objectname=LogicalDisk Free_Megabytes=1463633,Percent_Disk_Read_Time=0,Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=76.7220687866211,Percent_Idle_Time=99.97509765625,Disk_Reads_persec=0,Disk_Writes_persec=0 1537908121000000000
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=HarddiskVolume2,objectname=LogicalDisk Free_Megabytes=44,Percent_Disk_Read_Time=0,Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=9.799554824829102,Percent_Idle_Time=99.97465515136719,Disk_Reads_persec=0,Disk_Writes_persec=0 1537908121000000000
```

### Actual behavior:
Output does not include win_mem measurement
```
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=C:,objectname=LogicalDisk Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=71.6556625366211,Percent_Idle_Time=99.97417449951172,Disk_Reads_persec=0,Disk_Writes_persec=0,Free_Megabytes=163721,Percent_Disk_Read_Time=0 1537908121000000000
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=D:,objectname=LogicalDisk Free_Megabytes=1463633,Percent_Disk_Read_Time=0,Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=76.7220687866211,Percent_Idle_Time=99.97509765625,Disk_Reads_persec=0,Disk_Writes_persec=0 1537908121000000000
win_logicaldisk,Application=ISCC\ Infrastructure\ Monitoring\ -\ Windows\ -\ cld-sapp-3zsed,FunctionalGroup=GBS\ Tech,Group=AHS\ Windows\ Servers,OperatingSystem=Windows\ 2012,PhysicalLocation=AWS,host=Enki,instance=HarddiskVolume2,objectname=LogicalDisk Free_Megabytes=44,Percent_Disk_Read_Time=0,Percent_Disk_Time=0,Percent_Disk_Write_Time=0,Percent_Free_Space=9.799554824829102,Percent_Idle_Time=99.97465515136719,Disk_Reads_persec=0,Disk_Writes_persec=0 1537908121000000000
```

**Comment by danielnelson** [comment]
@dp1140a This is with Telegraf 1.8.0?

**Comment by dp1140a** [comment]
1.7.3 and 1.8.0

**Comment by brenwhyte** [comment]
I am not seeing this behaviour with 1.8.0 or 1.8.1 (only ones I've tested)

Sample working telegraf.d conf:

`[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    #Query for ASP.Net perfmon objects
    ObjectName = "ASP.Net"
    Counters = ["Requests Queued","Request Wait Time","Worker Process Restarts"]
    Instances = ["------"] # Use 6 x - to remove the Instance bit from the query.
    Measurement = "Counters"`

**Comment by danielnelson** [comment]
@dp1140a Let me know if the issue still persists after running those commands.
