### ISSUE TITLE
Telegraf stops sending data to influx

### ISSUE THREAD

**Issue by ErikAndren** [influxdata/telegraf#4777]
### Relevant telegraf.conf:
[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/2431951/telegraf.conf.txt)
[telegraf.log.txt](https://github.com/influxdata/telegraf/files/2431952/telegraf.log.txt)

### System info:
[Include Telegraf version, operating system name, and other relevant details]
1.8.0, Debian Raspbian Stretch, Raspberry pi model A i. e. Fairly resource constrained system.

### Steps to reproduce:
1. Start telegraf and influx
2. Wait

### Expected behavior:
A working solution

### Actual behavior:
After some time telegraf stops sending data to influx.
Restarting telegraf makes the solution work again.

### Additional info:
This worked before and is clearly a regression.
Worked with telegraf:armhf (1.7.4-1)

**Comment by glinton** [comment]
It sounds like telegraf is running out of resources and halting. How long does it generally take for things to stop for you?

**Comment by danielnelson** [comment]
I believe this is the same issue as https://github.com/influxdata/telegraf/issues/4594 because in the log file I see the MQTT input logging that it is connected twice.  I'm going to close as a duplicate and we can discuss on the other issue.
