### ISSUE TITLE
long polling bot requires certificate?

### ISSUE THREAD

**Issue by eugen35** [influxdata/telegraf#4779]
const Telegraf = require('telegraf')
const bot = new Telegraf('xxxxxxxxx')
bot.start((ctx) => ctx.reply('Welcome!'))
bot.help((ctx) => ctx.reply('Send me a sticker'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.hears(/buy/i, (ctx) => ctx.reply('Buy-buy'))
bot.startPolling()

gives error: "Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot...., reason: certifi
cate has expired"

What does go wrong ?

**Comment by glinton** [comment]
I believe you are looking for https://github.com/telegraf/telegraf
