### ISSUE TITLE
access global config in plugins

### ISSUE THREAD

**Issue by yuankui** [influxdata/telegraf#478]
Is any way to access global config like `interval` in plugins?

**Comment by sparrc** [comment]
yep: https://github.com/influxdata/telegraf#plugin-options

**Comment by zstyblik** [comment]
The way I understood the question is whether it's possible to access:

````
[agent]
  interval = 10s
```

from the plugin. Not whether it's possible to configure different interval per plugin.

**Comment by sparrc** [comment]
@zstyblik please read the link above, it describes how to set the interval per-plugin

**Comment by zstyblik** [comment]
@sparrc - I understand your reply. I know you can set interval per plugin. And I'm telling you that's not how I understood the question. But I'm not the one whom asked and perhaps it's me who misunderstood the question. Still, if you have time, please, read again what I've written, resp. compare the last sentence and your reply. :)

**Comment by sparrc** [comment]
I don't see any reason plugins need access to the global `interval` parameter. Asking for a feature without giving the use-case usually leads to confusion ;-)

**Comment by zstyblik** [comment]
Sure. Use-case that comes to my mind could be choosing retention policy, resp. embedding interval into metric name in order to choose retention policy later up in the chain. And what not. I don't know. Anyway ...

**Comment by sparrc** [comment]
Why not just add a tag then? This would be a pretty minor duplication...

```
[agent]
  interval = "10s"

[tags]
  interval = "10s"
```

**Comment by zstyblik** [comment]
@sparrc sure, that could work, although it's hard to say what @yuankui 's use case is. Such thing wouldn't work for me. I would need per plugin tag rather than a global one :)

**Comment by sparrc** [comment]
@zstyblik per-plugin tags are coming in 0.3.0, see https://github.com/influxdata/telegraf/pull/437

**Comment by yuankui** [comment]
thank @zstyblik for reply.
here is my use case.

I want to monitor the network(Bytes per second) of every network interface.

but the provided network provide only the accumulated network bytes.

It's suggested to use [derivative](https://docs.influxdata.com/influxdb/v0.9/query_language/functions/#derivative) in SQL, bug I failed to get it to work. (maybe there is some issue in the function)

So I decided to calculate my self.

so I need to get the current `bytes` and the `last updated bytes`, and calculate the data rate with

(now - last) / interval?

So I need to get the global interval setting.

Is the request reasonable?

Or is there any other elegant way?

**Comment by sparrc** [comment]
I wouldn't rely on interval for that, you should store the timestamp of the last gather.

**Comment by zstyblik** [comment]
@sparrc great!

@yuankui have you reported the bug with InfluxDB? As far as I can tell, the query works for me. Whether reported values are correct, that's another story(I haven't invested time into this). But I'd try to solve it outside of Telegraf.

> SELECT DERIVATIVE(value, 10s) FROM testdb2."1s".wave
