### ISSUE TITLE
Add measurement name to tail input

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#4780]
## Feature Request
Add the ability to name the measurement generated by the `tail` input plugin, similar to how `logparser` did.

**Add to struct**

https://github.com/influxdata/telegraf/blob/af0ef55c0281af67fe2db52d8c700fa8f636010e/plugins/inputs/logparser/logparser.go#L25

**Set name on `AddFields` call**

https://github.com/influxdata/telegraf/blob/af0ef55c0281af67fe2db52d8c700fa8f636010e/plugins/inputs/logparser/logparser.go#L263

Opening a feature request kicks off a discussion.

### Proposal:
Add `measurement` as optional config option to `tail` input plugin. If empty, use parsed measurement's `m.Name()` otherwise use the configured name on call to `AddFields`.

### Current behavior:
All metrics are named `tail`

### Desired behavior:
Configurable measurement name

**Comment by egegunes** [comment]
I will work on it. Happy Hacktoberfest!

**Comment by danielnelson** [comment]
You can use the `name_override` option on any input plugin specify the default measurement name.

**Comment by glinton** [comment]
Ah, I definitely missed that, sorry @egegunes, turns out this isn't needed.
