### ISSUE TITLE
Log more details in the event of an input collection failure

### ISSUE THREAD

**Issue by jcmcken** [influxdata/telegraf#4796]
### Proposal:

The Telegraf agent should print more details any time an input experiences a data collection failure.

For example, if collection takes longer than the collection interval, the agent should print not just the plugin where it originated, but specific details (e.g. the line number of the input in the config file, or the index of the input in the list of inputs -- something that a user can use to readily identify which specific input caused the failure).

### Current behavior:

To take the CloudWatch plugin as an example --

When collection takes longer than the collection interval, Telegraf [prints](https://github.com/influxdata/telegraf/blob/9e77bfc3edcedc67bbab7b66ed978ba9d085db08/agent/agent.go#L163) an unhelpful message:

```
telegraf[9998]: 2018-10-03T14:17:44Z E! Error in plugin [inputs.cloudwatch]: took longer to collect than collection interval (15m0s)
```

With multiple ``inputs.cloudwatch`` sections. this is not very useful information, and requires a lengthy process to reproduce the issue, tracing with tcpdump, strace, or running Telegraf in test mode to try and intuit where the failure is happening.

### Desired behavior:

The agent prints details about the input plugin that failed.

Briefly looking over the input setup code, there doesn't seem to be anything uniquely identifying that could be used in the log message except perhaps the config itself. I think the config sometimes contains sensitive data, so this is probably a bad idea.

One possibility is to attach the input's tags to the message, and then the user can add an ``id`` tag or something to uniquely identify the plugin. But this would also affect measurement data if the user forgets to strip the tag in the ``output``.

Another possibility is to add a new input setting, e.g. ``id``, that defaults to some randomized string, but could be set by the user.

I didn't see any easy way to pass in external metadata about the input like line number or index.

**Comment by danielnelson** [comment]
Let's merge this issue with https://github.com/influxdata/telegraf/issues/1815
