### ISSUE TITLE
httpjson - No metric output even with valid json responce

### ISSUE THREAD

**Issue by RyanMnM** [influxdata/telegraf#480]
Hi,

I'm trying to get the httpjson plugin to pull down JSON data from a New Relic instance we run so that we can collate it along with data from other sources and show it on one instance of grafana.

I've added a fix in for New Relic requiring a api key in the request header and i can see that data is being pulled down but the metric that httpjson returns seems to be blank.

I've tried dumping the json responce to make sure that a valid JSON document was being returned and from what i can see it is, but i have no way from what i can see to dig deeper and find out where the issue is.
``` JSON
{
  "metric_data": {
    "from": "2014-01-01T00:00:00+00:00",
    "to": "2014-01-02T00:00:00+00:00",
    "metrics": [
      {
        "name": "Apdex",
        "timeslices": [
          {
            "from": "2014-01-01T00:00:00+00:00",
            "to": "2014-01-02T00:00:00+00:00",
            "values": {
              "score": 1
            }
          }
        ]
      },
      {
        "name": "EndUser/Apdex",
        "timeslices": [
          {
            "from": "2014-01-01T00:00:00+00:00",
            "to": "2014-01-02T00:00:00+00:00",
            "values": {
              "score": 1
            }
          }
        ]
      }
    ]
  }
}
```

Is a return that ive dumped from the script just before its parsed by the plugins JSON parser so i can only guess that that is where the problem may lie.

Any ideas or is there something im missing here?

Sorry if this is a bit vague.
  Edit - i don't have access to it now but ill attach the relevant config when i can if that would be of help.
Thanks,
Ryan

**Comment by sparrc** [comment]
The httpjson plugin doesn't understand lists. It simply looks through dictionaries and flattens them into metrics. 

It would probably be better to develop a plugin specifically for New Relic, since this would be a generally useful plugin.
