### ISSUE TITLE
Test fails if the Local timezone is IST

### ISSUE THREAD

**Issue by mihaitodor** [influxdata/telegraf#4802]
Hang on to your chair. This is going to be a funny one :)

### System info:
- Telegraf version: master branch #b9c64df
- OS: OSX HighSierra
- Current timezone: Europe/Dublin

### Steps to reproduce:
- `cd plugins/parsers/grok`
- `go test -run TestTimezoneLocalCompileFileAndParse`

### Expected behavior:
```
PASS
ok  	github.com/influxdata/telegraf/plugins/parsers/grok	0.022s
```

### Actual behavior:
```
--- FAIL: TestTimezoneLocalCompileFileAndParse (0.01s)
	parser_test.go:894:
			Error Trace:	parser_test.go:894
			Error:      	Not equal:
			            	expected: 1465040505000000000
			            	actual  : 1465040505001000000
			Test:       	TestTimezoneLocalCompileFileAndParse
FAIL
exit status 1
FAIL	github.com/influxdata/telegraf/plugins/parsers/grok	0.024s
```

It looks like this test is going to annoy developers from Ireland :) One way to fix it is to add some conditional which checks the local timezone when constructing `metricA` [here](https://github.com/influxdata/telegraf/blob/8500d9345f02dc3c22cde726f24176ba9b75ff0e/plugins/parsers/grok/parser_test.go#L869) and make sure that a different one is used. Another option would be to refactor the code to allow mocking the system dependent calls in the unit tests. WDYT?

**Comment by danielnelson** [comment]
Hmm, some sort of leap millisecond issue perhaps... does this test work?:
```go
func TestTimezoneDublin(t *testing.T) {
	parse, err := time.ParseInLocation("02/01/2006--15:04:05", "04/06/2016--12:41:45", time.Local)
	require.NoError(t, err)
	date := time.Date(2016, time.June, 4, 12, 41, 45, 0, time.Local)
	require.Equal(t, parse, date)
}
```

**Comment by mihaitodor** [comment]
Output:
> ok  	command-line-arguments	0.019s

The issue is due to [tsMod](https://github.com/influxdata/telegraf/blob/e6c98e5ce047671c41775fb5710bb6ebc54640ad/plugins/parsers/grok/parser.go#L490) considering (rightly) that `"04/Jun/2016:12:41:45 +0100"` and `"04/06/2016--12:41:45"` are identical when `time.LoadLocation("Local")` resolves to `"Europe/Dublin"`.

Try running this code:

```
> go run date_tester.go
2016-06-04T12:41:45+01:00
2016-06-04T12:41:45+01:00
true
```

**Comment by danielnelson** [comment]
I see, this testcase is checking the conversion into local time from both a time with and without a timezone, and its not trying to test the timestamp fudging in tsMod.  I think then we should just pick a new time in the second metric that cannot conflict with the first metric.  I'll just add one second to the second metric: `04/06/2016--12:41:46`?

**Comment by mihaitodor** [comment]
That would definitely fix it, but I guess it would make the test slightly different. The original intent seems to have been to test that the timezone adjustment worked as intended. I'll let you decide, since I have little experience with this code.

**Comment by danielnelson** [comment]
I agree it is about timezone adjustment, ` +0100` vs `""` but I think the mistake we made was to not consider conflicts, likely we should also test tsMod with a timezone conversion but in the meantime I believe this brings us to the original intent of the tests: 4898edbb2d687b48ed87cae9233542854484b370

Can you double check that and let me know if it fails?

**Comment by mihaitodor** [comment]
All tests passed OK using 4898edb. Thank you very much!
