### ISSUE TITLE
Mysql plugin errors, requisites should be documented

### ISSUE THREAD

**Issue by rmacian** [influxdata/telegraf#4810]
### Relevant telegraf.conf:

default config with the mysql plugin

### System info:

Telegraf 1.8.0
MariaDB 5.5.60

### Steps to reproduce:

1. Enable the plugin
2. Check telegraf logs

### Expected behavior:

Collect metrics

### Actual behavior:

E! Error in plugin [inputs.mysql]: Error 1381: You are not using binary logging

After changing the config in my.cnf  I get

E! Error in plugin [inputs.mysql]: Error 1146: Table 'performance_schema.table_io_waits_summary_by_table' doesn't exist

### Additional info:

The plugin should document which configuration has to be enabled on mariadb to gather statistics:

log-bin=mysql-bin

I had to enable the binary login which is not enabled by default and I also figured that I have to enable the performance schema in my.cnf:

performance_schema=ON

but the same error occurs

E! Error in plugin [inputs.mysql]: Error 1146: Table 'performance_schema.table_io_waits_summary_by_table' doesn't exist

It looks that the schema must be set up with some caveats:

https://mariadb.com/kb/en/library/performance-schema-overview/

**Comment by glinton** [comment]
Thanks for this report
