### ISSUE TITLE
Plugin HTTP with cookies

### ISSUE THREAD

**Issue by Touchedegris** [influxdata/telegraf#4813]
## Feature Request

Some REST API environment uses authentication through GET request and generate a cookie to use for the next GET command.

### Proposal:

When the server return a cookie in the HTTP reply, store the cookie in a jar and use it for the next requests in the plugin.

### Current behavior:

No cookies are stored, so all the sessions are considered as a new session, so all the GET requests return a 401 error becaused session must authenticate first.
All the login event done with a GET request returns a 200 ok and create a login session in the remote server.

### Desired behavior:

When a cookie is received in a reply, store the cookie in a jar to reuse it on the next request.
Use the cookie received to identify the session used to get information from REST GET requests.
In the list of urls, the first entry is a login url, then the different urls to check, then the logout url.
empty the cookie jar after running the plugin.

### Use case: [Why is this important (helps with prioritizing requests)]

We can gather information from REST API when Authorization header is used, but not when the API uses cookies.  Since the authorisation part is not standardised, having this option would enlarge the number of APIs supported.

**Comment by glinton** [comment]
@Touchedegris is there a particular plugin you had in mind for this to apply to?

**Comment by Touchedegris** [comment]
Http

**Comment by mihaitodor** [comment]
Taking a stab at this. I think I can send a PR soonish.

**Comment by danielnelson** [comment]
Closing since we decided it would be too much to add support for a connection lifecycle with multiple URLs, see discussion in #4820.
