### ISSUE TITLE
[processors] Remove values and/or tags

### ISSUE THREAD

**Issue by otherpirate** [influxdata/telegraf#4829]
## Feature Request

I'm collecting data with MySQL input, but it's too much information, I not need all that information.

Exist a plugin that remove's some tags and/or some values?

### Proposal:  

Should be a nice feature to ANY input plugin, because each project/client has a diferent request

### Current behavior: 

I don't can filter any metric

### Desired behavior: 

I want to filter any metric from any input plugin

### Use case: 

MySQL input is a good example

**Comment by glinton** [comment]
This is possible with [measurement filtering](https://github.com/influxdata/telegraf/blob/1.8.1/docs/CONFIGURATION.md#measurement-filtering)
