### ISSUE TITLE
vSphere plugin: SOAP-layer timeout not honored

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#4830]
### Relevant telegraf.conf:
timeout = "1s"

### System info:
Telegraf 1.8.1. Any OS
 
### Steps to reproduce:

1. Set a short timeout (1s)
2. Run the collector.

### Expected behavior:
Some SOAP calls to vCenter should time out.

### Actual behavior:
Nothing times out.

### Additional info:
Looks like handling of this was never implemented.

**Comment by danielnelson** [comment]
Closed in #4840
