### ISSUE TITLE
docs: clarification on taginclude

### ISSUE THREAD

**Issue by randallt** [influxdata/telegraf#4843]
### Relevant telegraf.conf:
[global_tags]
  env = "myenv"
  dc = "mydc"

### System info:
[Include Telegraf version, operating system name, and other relevant details]
Telegraf v1.8.1, RHEL6

### Steps to reproduce:

1. Use a telegraf.conf file that declares global tags
2. Use the 'taginclude' filter in an input plugin, like:

[[inputs.procstat]]
  pattern = "my.*pattern"
  process_name = "myprocessname"
  namepass = ["procstat"]
  fieldpass = ["cpu_usage", "memory_rss", "num_threads" ]
  taginclude = ["process_name", "user"]

### Expected behavior:

I had expected only tags generated from this input plugin to be filtered (and host and global tags to be added to the point afterward).

The documentation was not explicit that even global tags, including the host tag (!!!), would be filtered out with the taginclude filter. This should be VERY clear in the docs. I don't want others wasting their time like I did trying to figure out why my whole measurement disappeared from my host when I added a taginclude clause.

We might want to re-evaluate this behavior. Our strategy is to have one main telegraf.conf file that is controlled by Chef that includes global tags that we don't want changed, and then allow teams to contribute telegraf.d fragment conf files for specific things. With this behavior, it is likely that teams will remove our global tags without realizing it. At the very least, the documentation should have a stern warning about the taginclude filter.

### Actual behavior:

All the tags other than those mentioned, including global and host tags (!!!), were removed from the points. This caused the point to effectively disappear from my host completely.

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I can see how this could cause confusion and it seems like one could want it to work either way.  Perhaps we should add an agent option to protect these tags.

One option that that you could explore using now is the override processor to add back the tags later in the processing:
```
[[processors.override]]
  order = 999999 # the last one
  [processors.override.tags]
    global1 = "howdy"
    global2 = "doody"
    host = "$HOST" # relies on the environment variable instead of `os.Hostname`
```

I made the quick documentation edit in #4847 to address this in the short term.
