### ISSUE TITLE
prometheus output plugin: support for multiple users (basic auth)

### ISSUE THREAD

**Issue by schnoddelbotz** [influxdata/telegraf#4853]
## Feature Request

We have a use-case where we'd like individual parties to access telegraf's prometheus output plugin. We'd like to not share the password between parties.

### Proposal:

Extend Prometheus Client Service Output Plugin configuration with ability to list multiple basic auth users/passwords.
I'd happily work on a PR including tests, but would like to clarify first whether such an PR would be accepted and how extension of configuration should look like.

### Current behavior:

Currently, only one user/password combination can be specified.
```toml
[[outputs.prometheus_client]]
  ## Use HTTP Basic Authentication.
  # basic_username = "Foo"
  # basic_password = "Bar"
```

### Desired behavior:

For us, it would be helpful if we could specify a list / map of users.

### Use case: [Why is this important (helps with prioritizing requests)]

Here, we consume telegraf data for our own monitoring server and we'd like to enable customers to also consume it from their own prometheus instance.

**Comment by danielnelson** [comment]
I think this is a more complicated configuration than we would like to support, as a workaround you could either use multiple prometheus_client outputs (would need to be on different ports and would be a bit more cpu/mem use by Telegraf), or you could use a more feature rich reverse proxy, such as nginx, in front of Telegraf.
