### ISSUE TITLE
Update vsphere input plugin to support configurable tags

### ISSUE THREAD

**Issue by perzizzle** [influxdata/telegraf#4867]
## Feature Request
Update vsphere input plugin to support configurable tags

### Proposal:
Create a configurable include/exclude option for tags.

### Current behavior:
Currently every tag is created in the vsphere measurements.

### Desired behavior:
Configurable include/exclude of tags.
host_tags_include = []
host_tags_exclude = ["uuid"] 

### Use case: [Why is this important (helps with prioritizing requests)]
We currently have thousands of unique source, uuid, vmname, name tags. I'm worried about the cardinality this will cause.

**Comment by prydin** [comment]
Thanks for the feedback! I'm wondering if you couldn't just use the built-in tagexclude setting? I tried this in my lab and it seemed to work.

```
tagexclude = [ "uuid", "moid" ]
```

**Comment by danielnelson** [comment]
As mentioned the [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) are the best way to deal with this, set them as part of the input plugin.  One word of warning, don't remove so many tags as to remove the uniqueness of the series or you may end up overwriting data.

**Comment by perzizzle** [comment]
Thanks a bunch, wasn't aware of this setting.
