### ISSUE TITLE
curl: (7) Failed to connect to ::1: No route to host

### ISSUE THREAD

**Issue by WeiWan-Reflektion** [influxdata/telegraf#4868]
To whom it may concern, 
I followed this step to install jolokia and make cassandra config changes and then restart cassandra 
sudo mkdir /opt/jolokia 
sudo cd /opt/jolokia 
sudo wget https://github.com/rhuss/jolokia/releases/download/v1.6.0/jolokia-1.6.0-bin.tar.gz
sudo tar -xf jolokia-1.6.0-bin.tar.gz 
sudo echo 'JVM_OPTS="$JVM_OPTS -javaagent:/opt/jolokia/jolokia-1.6.0/agents/jolokia-jvm.jar"' >>  /srv/cassandra/conf/cassandra-env.sh 

But when I run curl http://localhost:8778/jolokia/, 
it has this error, 
curl: (7) Failed to connect to ::1: No route to host 

The java version is 1.8.0_181 
The cassandra version 2.2.8 

Will the java version or cassandra version affect it? 

Thanks,

**Comment by danielnelson** [comment]
This error means your systems networking is not setup properly, you could try using `http://127.0.0.1:8778/jolokia` to for ipv4.  Please ask followup questions at the [InfluxData Community](https://community.influxdata.com) site.
