### ISSUE TITLE
Autogenerated telegraf.conf uses UCS-2 LE-BOM coding

### ISSUE THREAD

**Issue by antonkolb** [influxdata/telegraf#4880]
### Relevant telegraf.conf:

autogenerated content

### System info:

Windows 10 64-bit, x64 based processor

`.\telegraf.exe --version` shows
`Telegraf 1.8.2 (git: HEAD 996a91f2)`

### Steps to reproduce:

1. Navigate to folder containing telegraf.exe
2. execute `.\telegraf.exe config > telegraf.conf`
3. execute `.\telegraf.exe --config telegraf.conf`

### Expected behaviour:
No parsing error
### Actual behaviour:
`2018/10/18 15:32:31 E! Error parsing telegraf.conf, toml: line 1: parse error`
### Additional info:
Using PowerShell CLI

Opening file in Notepad++ and setting UTF-8 coding resolves the problem, as mentioned in issue #1378.

**Comment by antonkolb** [comment]
I tried this with MinGW64 (from Git Bash) and in this case the file is set to UTF-8 coding.

Sounds like a PowerShell issue.

Fun facts:
Size of the different files
![image](https://user-images.githubusercontent.com/15674392/47159151-7f529200-d2ed-11e8-80fc-9c31dd0541d1.png)

text-compare.com shows a change in line 1, some changes regarding µ sign (and spaces in the lines before the inputs.jolokia.metrics) and an additional line at the end.

[telegraf.zip](https://github.com/influxdata/telegraf/files/2492161/telegraf.zip)

**Comment by danielnelson** [comment]
This might occur on other platforms as well if the terminal is set to a different locale, the proper behavior is to output in the encoding of stdout.  I'm not sure if Go is handling this conversion or if Powershell did.

Separately it would be a nice touch to expand the file encodings we can read, not just with respect to the config file, but also reading text data formats.

**Comment by antonkolb** [comment]
Now I feel less silly reporting my issue. I assumed it is just PS bollocks and that I should have used something else in the first place.

**Comment by SMARoovers** [comment]
I implemented a workaround by catching the output in a variable and then out-file it with utf8 encoding.

```
$exe = "C:\Program Files\telegraf\telegraf.exe"
$telegrafConf = &$exe config
$telegrafConf | Out-File -FilePath "C:\Program Files\telegraf\telegraf.conf" -Encoding utf8
```
