### ISSUE TITLE
Need to delete a measurement or series before writing the data into influxdb

### ISSUE THREAD

**Issue by MohamedNazeer** [influxdata/telegraf#4884]
I want to delete some series or measurements before writing the data into influxdb. 

namedrop is dropping the measurement once after writing the data.

 Is there any way to define the write before/after parameter in config????

**Comment by MohamedNazeer** [comment]
Thanks for the quick reply!!!!!

My requirement is to overwrite some tag values in influxdb, which is not possible as of now. So  i decide to recreate (drop and create) the whole measurement. My input is a json file which having the time key in the file. Since we are using same time key value in the file there is no chance of data loss.  

Here i have mention the telegraf config for influxdb output. I am using only namedrop but namepass. 

[[outputs.influxdb]]
urls = ["http://<influxserverip>:8086"]
database = "mydatabasename"
namedrop = ["mymeasurementname"] # the measurement i want to delete everytime before flushing the data into influxdb

[[inputs.file]]
    files = ["/path/to/myfile/myfile.json"]   
    data_format = "json"   
    json_time_key = "timekey"    
    json_time_format = "unix_ms"    
    tag_keys = ["tagkey1","tagkey2"]
    json_string_fields = ["stringfield1","stringfield2"]
    json_name_key = "name"


By the above configuration the measurement i have mentioned in namedrop will be created from my input and dropped after wrote the measurements(so that the measurement will not be available in the influxdb database). But i want to drop the measurement before writing the data(which will recreate the measurement by the config)

**Comment by danielnelson** [comment]
Sorry I don't quite understand.  I recommend temporarily replacing the influxdb output with a file output for debugging.  If the input creates a measurement `mymeasurementname`, it will be not be written by the output.

If that doesn't help can you show me a few example lines of what could be in the input file and also what you would want it to output (preferable in line protocol) and I can show you how to set it up.

**Comment by danielnelson** [comment]
Telegraf cannot remove data from InfluxDB, it can only add data.

You could try this:
1. Export the data out of InfluxDB
2. Modify the data to the new format.
2. Delete the entire measurement from the database by hand (`drop series from mymeasurementname`) or part of the series (`drop series from mymeasurementname where tag1='tagvalue1'`)
3. Reinsert data to the database with Telegraf.

If you do this, you probably won't need the `namedrop` option because you will just insert all of the data back.

**Comment by MohamedNazeer** [comment]
ohh!! 

Thanks for the clarification. 

So namedrop will just skip that measurement to be pushed to database. Its not dropping the measurement from database.

Thanks
