### ISSUE TITLE
Wrong insert time from telegraf to influxdb

### ISSUE THREAD

**Issue by sonchu** [influxdata/telegraf#4897]
Hi there,

I am experiencing a strange issue with telegraf insert time.  (version 1.8.2)

192.168.1.3 - - [22/Oct/2018:20:35:04 +0700] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "telegraf" 4892e209-d5ff-11e8-8253-000000000000 15096
192.168.1.3 - - [22/Oct/2018:20:35:34 +0700] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "telegraf" 5a7494b2-d5ff-11e8-8274-000000000000 10037
192.168.1.3 - - [22/Oct/2018:20:36:04 +0700] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "telegraf" 6c57f65c-d5ff-11e8-828c-000000000000 10685
192.168.1.3 - - [22/Oct/2018:20:36:34 +0700] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "telegraf" 7e3906cf-d5ff-11e8-82aa-000000000000 13967

As you can see, the insert time in second was 04, 34, 04 ,34.  

Below is my telegraf configuration:

 

 

>  interval = "30s"
>   round_interval = true
>   metric_buffer_limit = 1000000
>   flush_buffer_when_full = true
>   collection_jitter = "0s"
>   flush_interval = "30s"
>   flush_jitter = "0s"
> 

Could you please advise where i was wrong with the insert time?

Thanks in advance.

Son

**Comment by glinton** [comment]
It looks fine to me as they are 30s apart as you configured, they were at:
- 35:04
- 35:34
- 36:04
- 36:34

**Comment by danielnelson** [comment]
@sonchu Make sure your systems both have synchronized clocks, this seems like the most likely reason why the requests aren't on even boundaries.  Also don't worry about it too much because the times are set when the input plugins run, not when the metrics are written to InfluxDB.  So long as the data is being written with the correct timestamps you should be fine.

**Comment by sonchu** [comment]
@danielnelson : But the issue is the Grafana is getting data at the interval 1m and they didn't see the data at the time they get. That's why i got a lot of nodata when having alert on some graphs. The difference between insert time and query time caused this issue. Am i correct or not?

Could you please advise?

Thanks in advance.

**Comment by danielnelson** [comment]
Check the conditions section of the alert, I have fields for `avg()` and `query(A, 5m, now)`.  My understanding is this means the alert query will average from 5m ago until now.  You would need to have no updates for 5m to get no-data.  Do you also have the alert query set to `query(A, 5m, now)`?

**Comment by sonchu** [comment]
My setting is (A, 1m, now) because I need to get alert asap when CPU go high in 1 minute. And a strange thing that I gave Grafana a restart and NODATA gone. I have also checked in influxdb and notice the insert time still is around 04, 34 but it is fine now. Weird!!!

Thank you very much for your support.
