### ISSUE TITLE
filestat plugin: clarify modification_time unit

### ISSUE THREAD

**Issue by mvuets** [influxdata/telegraf#4898]
[Documentation on the **filestat** input plugin](https://github.com/influxdata/telegraf/blob/ee056278f5e5860c252be4731280f75c91a40bc0/plugins/inputs/filestat/README.md#measurements--fields) reads that the **modification_time** measurement is in unixtime units. Usually that means seconds. However according to the [source code](https://github.com/influxdata/telegraf/blob/ee056278f5e5860c252be4731280f75c91a40bc0/plugins/inputs/filestat/filestat.go#L89) its actual unit is nanoseconds.

**Comment by danielnelson** [comment]
2f7450ec042f2c3379afefb7344f3e5b68c37575
