### ISSUE TITLE
Proposal to make telegraf work as syslog, not just accept data from existing syslog.

### ISSUE THREAD

**Issue by p-kraszewski** [influxdata/telegraf#4902]
### Proposal:

Make telegraf work **as** syslogd, not just accept data from *existing* syslogd.

I don't know if it was considered and abandoned (due to not enough workforce, problems with portability, lack of interest) or just nobody came with the idea.

I'd find it useful in my projects (FreeBSD & Linux) of embedded devices. Having `telegraf` directly pull messages from kernel/apps and push them further would make my designs simpler (no need to have a separate `syslogd` just short-circuiting data to `telegraf`).

I'm going to try programming it anyway (for FreeBSD first, then for Linux), but I wonder if there will be more public interest in it.

Blocked by #4593

**Comment by danielnelson** [comment]
This is something we are interested in.  I believe there would be two parts to this, correct me if I'm wrong @leodido.

First, we need to add old style BSD syslog message support #4593.  Second is just a matter of setting up the plugin correctly to listen at the desired socket and documenting how to do so.

**Comment by leodido** [comment]
It is a good idea and use case, for sure. No @danielnelson you are not wrong anyway :).

**Comment by powersj** [comment]
Hi,

It looks like the previous PR that was blocking this issue, #4593, was merged in. As a result a user can set up the plugin to listen on a local socket for the BSD style syslog messages.

I believe this resolves this request? Can someone confirm?

Thanks
