### ISSUE TITLE
Jti_openconfig_telemetry plugin possible issue with OC BGP sensor

### ISSUE THREAD

**Issue by psagrera** [influxdata/telegraf#4907]
I've been testing recently OC-BGP sensors (/bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/)). I realized when a key (i.e "adj-rib-in-pre/routes/route/prefix" ) can have more than one value, not all of them are returned (overwriting ? ), hence, influxdb doesn't contains reliable information.
 
    Example 1
     
    JUNOS Output (Junos: 18.3R1.4)
    ############
     
    lab@HL3-1-1> show route receive-protocol bgp 192.168.1.23  
     
    inet.0: 104 destinations, 159 routes (104 active, 0 holddown, 0 hidden)
      Prefix                    Nexthop                   MED     Lclpref    AS path
    * 80.29.115.0/25          192.168.0.11                 100        I
    * 213.98.232.0/22         192.168.0.11                 100        I
    * 213.115.0.0/23          192.168.0.12                 100        I
     
     
    TELEGRAF DEBUG
    ##############
     
     
      Data Received from the vMX seems to be complete (log.Printf("D! Received from %s: %v", grpcServer, r))
     
    ---- Output truncated/formatted for readibilty ------
     
    [...]
    2018-10-18T10:58:56Z D! Received from 10.49.225.200 (timestamp:1539860336951)
     
    kv:<key:"__prefix__" str_value:"/bgp-rib/afi-safis/afi-safi[afi-safi-name='IPV4_UNICAST']/ipv4-unicast/neighbors/neighbor[    neighbor-address='192.168.1.23']/" >
    [...]
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"80.29.115.0/25" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"213.98.232.0/22" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"213.115.0.0/23" >
    [...]
     
    2018-10-18T10:58:56Z D! Available collection for 10.49.225.200 (_timestamp:1539860336951)
    [...]
    /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/@neighbor-address:192.168.1.23]
    [...]
    /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/routes/route/prefix:213.115.0.0/23
     
     
    INFLUX
    ######
     
    name: /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/
    tags: /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/@neighbor-address=192.168.1.23
    time                Prefix
    ----                ------
    1539860336996572002 213.115.0.0/23
    1539860457013660580 213.115.0.0/23
    1539860577003184410 213.115.0.0/23
     
     
    Example 2
     
    JUNOS Output (Junos: 18.3R1.4)
    ############
     
    lab@HL3-1-1> show route receive-protocol bgp 192.168.1.3
     
    inet.0: 104 destinations, 161 routes (104 active, 0 holddown, 0 hidden)
      Prefix                    Nexthop                   MED     Lclpref    AS path
      192.168.0.1/32          192.168.1.3                  100        I
      192.168.0.2/32          192.168.1.3                  100        I
      192.168.0.3/32          192.168.1.3                  100        I
      192.168.0.5/32          192.168.1.3                  100        I
      192.168.0.6/32          192.168.1.3                  100        I
      192.168.0.9/32          192.168.1.3                  100        I
      192.168.0.10/32         192.168.1.3                  100        I
      192.168.0.13/32         192.168.1.3                  100        I
      192.168.0.14/32         192.168.1.3                  100        I
      192.168.0.19/32         192.168.1.3                  100        I
      192.168.0.21/32         192.168.1.3                  100        I
      192.168.0.22/32         192.168.1.3                  100        I
      192.168.0.23/32         192.168.1.3                  100        I
      192.168.0.24/32         192.168.1.3                  100        I
      192.168.0.25/32         192.168.1.3                  100        I
     
     
    TELEGRAF DEBUG
    ##############
     
     
      Data Received from the vMX seems to be complete (log.Printf("D! Received from %s: %v", grpcServer, r))
     
    ---- Output truncated/formatted for readibilty ------
     
    [...]
    2018-10-18T10:58:56Z D! Received from 10.49.225.200 (timestamp:1539860336839)
     
    kv:<key:"__prefix__" str_value:"/bgp-rib/afi-safis/afi-safi[afi-safi-name='IPV4_UNICAST']/ipv4-unicast/neighbors/neighbor[    neighbor-address='192.168.1.3']/" >
     
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.2/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.3/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.5/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.6/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.9/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.10/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.13/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.14/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.19/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.21/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.22/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.23/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.24/32" >
    kv:<key:"adj-rib-in-pre/routes/route/prefix" str_value:"192.168.0.25/32" >
     
     
    [...]
    2018-10-18T10:58:56Z D! Available collection for 10.49.225.200 (_timestamp:1539860336839)
    [...]
    /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/@neighbor-address:192.168.1.3
    [...]
     
    /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/routes/route/prefix:192.168.0.25/32
     
     
    INFLUX
    ######
     
    name: /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/
    tags: /bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/@neighbor-address=192.168.1.3
    time                Prefix
    ----                ------
    1539860336773449107 192.168.0.1/32
    1539860336928430972 192.168.0.25/32
    1539860456782707399 192.168.0.1/32

     TELEGRAF relevant configuration
     ##########################

     # Read OpenConfig Telemetry from listed sensors

     [[inputs.jti_openconfig_telemetry]]

       servers = ["10.49.225.200:50051"]

       ## Frequency to get data in millisecond
       sample_frequency = "60000ms"
       sensors = [ 
       "/bgp-rib/afi-safis/afi-safi/ipv4-unicast/neighbors/neighbor/adj-rib-in-pre/",
       ]

      str_as_tags = false

**Comment by danielnelson** [comment]
@ajhai Would you be able to take a look at into issue?

**Comment by ajhai** [comment]
@danielnelson I'd love to but unfortunately I'm not with Juniper anymore and don't have access to devices to test this. @nileshsimaria could you please have someone to take a look at this?

**Comment by sjwang90** [comment]
@psagrera It's been awhile and encountered this on my Juniper issues search. Is this still an issue for you? If so, I'll see if we can get someone from Juniper to help out.

**Comment by purifp** [comment]
hi @psagrera , Did you solve this issue? I have something similar with OC ISIS sensor.

**Comment by srebhan** [comment]
Does that issue still exist in the latest Telegraf version?
