### ISSUE TITLE
support multiple config files

### ISSUE THREAD

**Issue by yuankui** [influxdata/telegraf#491]
use case:

host1 contains: tomcat & nginx
host2 contains: tomcat & redis
host3 contains: redis & mysql

if there are more hosts, I need to maintain many configs.

if telegraf support multiple config files and merge the config at startup, then the tomcat/nginx/redis configuration can be shared between multi hosts

**Comment by sparrc** [comment]
We already support that via the `-configdirectory` option, you can specify a directory with multiple configuration files
