### ISSUE TITLE
Monitor metrics_buffer_limit

### ISSUE THREAD

**Issue by fabianutomi** [influxdata/telegraf#4919]
## Feature Request
Allow user to display how much of the metrics buffer limit is currently consumed. It can then allow us to determine how much buffer is used per hour based on data ingestion.

### Use case: [Why is this important (helps with prioritizing requests)]
It can then allow us to determine how much buffer is used per hour based on data ingestion.

**Comment by glinton** [comment]
I believe you can monitor this with the [internal plugin](https://github.com/influxdata/telegraf/tree/1.8.2/plugins/inputs/internal#measurements--fields)
