### ISSUE TITLE
Fine-grained disk usage reporting?

### ISSUE THREAD

**Issue by tjohnston-cd** [influxdata/telegraf#4932]
I'm new to the TICK stack, but I have already gained a lot of valuable insight into my infrastructure with it.

I'm interested in reporting on the usage breakdown of a large NFS share (e.g. who are the top 10 consumers) at regular intervals. Of course, each 'run' of this is going to be very slow, so it won't fit in my 10 second reporting intervals for cpu/memory/etc.

Is this a good use case for telegraf/influx, or no? If it is, are there appropriate plugins? Or should I write something custom using the `exec` input type, which uses `du` or [sn](https://github.com/vmchale/tin-summer) under the hood to gather usage data?

**Comment by tjohnston-cd** [comment]
Ah, I should clarify: not the top 10 largest _files_ but top 10 largest _directories_. 
There's probably still a way to do it that's very similar to this. I'll take a look and see what I can come up with.

`topk` will definitely be handy. Thanks!

**Comment by danielnelson** [comment]
We are adding size to filecount, once this is done if should be possible to get it working fairly easily:

https://github.com/influxdata/telegraf/pull/4778

**Comment by tjohnston-cd** [comment]
Even better! Thanks for pointing this out.
