### ISSUE TITLE
Add HTTP profiling in http_response plugin

### ISSUE THREAD

**Issue by becks** [influxdata/telegraf#4933]
## Feature Request

Add HTTP profiling in http_response plugin

### Proposal:

Add durations for DNS lookup/TCP connection/TLS handshake/Server processing/Content transfer

### Current behavior:

Only the response_time is returned

### Desired behavior:

add durations for DNS lookup/TCP connection/TLS handshake/Server processing/Content transfer

### Use case: [Why is this important (helps with prioritizing requests)]

https://medium.com/@deeeet/trancing-http-request-latency-in-golang-65b2463f548c
https://gist.github.com/bsergean/f32170785f7c64f22875

**Comment by powersj** [comment]
Hi,

Sorry no one has never gotten back to you. Seems this is a dup of #2128, so I am going to close it. I do think this would be nice to add though! 

Thanks!
