### ISSUE TITLE
custom config file path

### ISSUE THREAD

**Issue by robhalli** [influxdata/telegraf#4939]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Allow for the implementation of a specified custom config file path.

### Current behavior:

3 Current methods include these:
// Try to find a default config file at these locations (in order):
//   1. $TELEGRAF_CONFIG_PATH
//   2. $HOME/.telegraf/telegraf.conf
//   3. /etc/telegraf/telegraf.conf

### Desired behavior:
Allow user to define the path of the config file.

### Use case: [Why is this important (helps with prioritizing requests)]
This is important as in my case I'm wanting to store the config file in another location.

**Comment by glinton** [comment]
The `--config` option allows you to specify a config file, there is also a `--config-directory` option to specify a directory. For more options run `telegraf -h`
