### ISSUE TITLE
Rename index tag of SNMP Table when using index_as_tag

### ISSUE THREAD

**Issue by relishcolouredhat** [influxdata/telegraf#4941]
Good day!

Using [[inputs.snmp.table]], setting index_as_tag to true allows to use table indices as a tag, when another index is not available.

As far as I can find, the tag name can only be 'index'. 

While this is clear and useful, the ability to set the tag name would make this more flexible. 

In my use case, this has two major benefits:

1. Making the relevance of the index obvious to query writers, and 
2. Ability to store metrics in the same format as the scripts telegraf is replacing to prevent having to edit dashboards created before adopting telegraf.

**Comment by Hipska** [comment]
This will not be added in the snmp input. As Daniel said, you can use the rename processor to rename the index to the name you want.
