### ISSUE TITLE
Could you write cpu_total metric

### ISSUE THREAD

**Issue by vit1251** [influxdata/telegraf#4946]
Hello right now you write cpu_system and cpu_user separate metric can you write sum of that metric to optimization on request.

**Comment by danielnelson** [comment]
You can set `totalcpu` in the configuration for the cpu plugin:
```
[[inputs.cpu]]
  totalcpu = true
```

As an aside, if we were to recreate this plugin we would probably not provide this functionality anymore.  It's more flexible to just do this aggregation at query time.
