### ISSUE TITLE
Wrong input name in plugin documentation

### ISSUE THREAD

**Issue by nightbluepn** [influxdata/telegraf#4948]
At page https://github.com/influxdata/telegraf/tree/master/plugins/inputs/opensmtpd
line 2 of the configuration says
[[inputs.smtpctl]]
but should be
[[inputs.opensmtpd]]

**Comment by danielnelson** [comment]
Thanks, I corrected this in 2a9bef64ae369441fab8db8b122c3d3161a24da4
