### ISSUE TITLE
vSphere: Automatically detect maximum query size

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#4949]
## Feature Request

The maximum query size is dependent on the version of vCenter and/or a specific property setting on vCenter. Exceeding the maximum will cause data collection to fail. 

### Proposal:
If the user doesn't specify ```max_query_metrics``` in the telegraf config, the plugin should first check for the ```maxQueryMetrics``` setting in vCenter and use that. If the setting isn't present in vCenter, it should check the vCenter version. If version is <=6.0, the plugin should use the value 64, otherwise is should use 256.

### Current behavior:
```max_query_metrics``` defaults to 256 and has to be manually changed for older versions of vSphere.

### Desired behavior:
If not specified, the plugin should infer the value by looking at vCenter properties and version.

### Use case: 
We've seen several cases where data isn't being collected because this property wasn't set correctly. Automatically inferring it eliminate a lot of support cases.

**Comment by danielnelson** [comment]
:+1: Seems like the Connect function would be a good place to do this once on startup.

**Comment by prydin** [comment]
This was addressed in PR #4968 

Closing.
