### ISSUE TITLE
vSphere: Add vCenter custom attributes to metrics

### ISSUE THREAD

**Issue by GeckoZero** [influxdata/telegraf#4955]
### Proposal:

Wondering if it would be possible to include the custom attributes in a vCenter per datacenter/cluster/host/vm entitie if they exist. Clearly the best solution would be to have those custom attributes as tags in telegraf metrics.

### Current behavior:

Custom vCenter attributes are missing.

### Desired behavior:

Add custom vCenter attributes as tags to telegraf metrics.

### Use case:

Managing a medium sized installation with 1000+ VMs and a lot of structured meta data in custom attributes used for filtering/billing/classification. Additionally the vSphere plugin is MUCH cleaner and ways faster than the current solution based on home-grown scripts via the exec input plugin.
The plan is to completely throw away the script collection and use the vSphere plugin if we can get access to the custom attributes.

**Comment by prydin** [comment]
I'm not against this. In fact, it's something we've discussed internally. My concern is the cardinality explosion it could cause, but if this is something optional, I think we'd be fine.

**Comment by GeckoZero** [comment]
Well, I thought about the very same problem and came to the conclusion that the cardinality explosion can be a problem, but only with a higher amount of custom attributes. I'm facing 13 custom attributes per entity currently and that's not much of a problem so far.
There's a another thing that worries me even more and that indeed is the description field (which is also used for meta information) because the string length is not predictable. 

Your suggestion would match my idea for this problem. I would love to have something like the following config parameters:

\# list of custom attributes to additionally map as metric tags per entity
custom_attributes_include = [
    "aaa",
    "bbb",
    "ccc"
]

\# wether to include the description field as metric tag and limit the length
include_entity_description = <yes|no>
max_description_length = 255

I really wonder though if it would make much sense to include the description field because that's not a usual tag thing. So I would be very happy to have the custom attributes as tags... :)

**Comment by prydin** [comment]
@GeckoZero what's your take on collection frequency? I'm thinking it's enough to collect the tags during discovery and cache them in memory. Thoughts?

**Comment by GeckoZero** [comment]
@prydin those custom attributes are pretty static, so collecting them within the discovery intervall is more than enough and a good idea.

**Comment by GeckoZero** [comment]
Well, we just tried 1.12.1 and the custom attribute feature works as described. Great work, thx!

**Comment by danielnelson** [comment]
Closed in #5971
