### ISSUE TITLE
help needed to build the code

### ISSUE THREAD

**Issue by ramprasadgk** [influxdata/telegraf#4958]
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

happen to download latest telegraf code, installed go, now how do i build the code and test it? i need to make customized changes to some of the plugins and use it

thanks for the help
cheers

**Comment by prydin** [comment]
Hi! Below is the "building from source section" from the readme file. Let me know if you have any specific questions. You need to have the ```dep``` tool installed. What platform are you on?

Telegraf requires golang version 1.9 or newer, the Makefile requires GNU make.

1. [Install Go](https://golang.org/doc/install) >=1.9 (1.10 recommended)
2. [Install dep](https://golang.github.io/dep/docs/installation.html) ==v0.5.0
3. Download Telegraf source:
   ```
   go get -d github.com/influxdata/telegraf
   ```
4. Run make from the source directory
   ```
   cd "$HOME/go/src/github.com/influxdata/telegraf"
   make
   ```

**Comment by ramprasadgk** [comment]
thanks for the reply, i am on rhel7

**Comment by ramprasadgk** [comment]
hi,

unable to find right install for my linux version can you help

Linux <hostname> 3.8.13-118.24.2.el6uek.x86_64 #2 SMP Wed Sep 12 16:58:43 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ramprasadgk** [comment]
*unable to find right dep install

**Comment by prydin** [comment]
Here's what it looks like setting it up on a clean Linux machine with only go and git installed:

Create a Go environment
```
pontus@pontus-telegraf-01:~$ mkdir -p ~/go/src/github.com/influxdata
pontus@pontus-telegraf-01:~/go/src/github.com/influxdata/telegraf$ mkdir ~/go/bin
pontus@pontus-telegraf-01:~$ export GOPATH=~/go/src/github.com/influxdata
pontus@pontus-telegraf-01:~$ cd ~/go/src/github.com/influxdata
```

Get latest source from git
```
pontus@pontus-telegraf-01:~/go/src/github.com/influxdata$ git clone https://github.com/influxdata/telegraf.git
Cloning into 'telegraf'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 31080 (delta 2), reused 2 (delta 2), pack-reused 31076
Receiving objects: 100% (31080/31080), 20.27 MiB | 18.89 MiB/s, done.
Resolving deltas: 100% (17054/17054), done.
```

Install dep
```
pontus@pontus-telegraf-01:~/go/src/github.com/influxdata/telegraf$ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5110  100  5110    0     0  21291      0 --:--:-- --:--:-- --:--:-- 21291
ARCH = amd64
OS = linux
Will install into /home/pontus/go/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.0
Fetching https://github.com/golang/dep/releases/tag/v0.5.0..
Fetching https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64..
Setting executable permissions.
Moving executable to /home/pontus/go/bin/dep
```

Build the code
```
pontus@pontus-telegraf-01:~/go/src/github.com/influxdata/telegraf$ make
dep ensure -vendor-only
go build -ldflags " -X main.commit=19a338b9 -X main.branch=master" ./cmd/telegraf
```

Run it!
```
pontus@pontus-telegraf-01:~/go/src/github.com/influxdata/telegraf$ ./telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
2018-11-05T15:09:23Z I! Starting Telegraf 
2018-11-05T15:09:23Z I! Loaded inputs: inputs.cpu inputs.disk inputs.kernel inputs.mem inputs.processes inputs.swap inputs.system inputs.net inputs.vsphere inputs.vsphere inputs.vsphere inputs.vsphere inputs.internal
2018-11-05T15:09:23Z I! Loaded aggregators: 
2018-11-05T15:09:23Z I! Loaded processors: 
2018-11-05T15:09:23Z I! Loaded outputs: wavefront
2018-11-05T15:09:23Z I! Tags enabled: host=pontus-telegraf-0
```

**Comment by ramprasadgk** [comment]
looks like office VPN has blocked access  to git,will try it on another machine and revert, thanks for all the help.

is there any way i can install without directly connecting form github, i can copy code to the host but cannot directly connect to github

**Comment by prydin** [comment]
You could always run the procedure I just described on a machine outside the network, zip up the entire ```go``` directory and move it to the machine that can't access github.

**Comment by glinton** [comment]
thanks @prydin. closing as a full explanation has been provided and it is now only a network issue.
