### ISSUE TITLE
namepass/namedrop not filtering properly. metric measurement name accepted is the input name, not the whole metric name generated

### ISSUE THREAD

**Issue by marioanton** [influxdata/telegraf#4959]
### System info:

Centos 7 
Telegraf version .1
### Steps to reproduce:
1. Place config for input.file
[[inputs.file]]
  data_format = "json"
  files = ["/tmp/metrics.json"]
  namepass = ["file_jsonspecifickey_retrieved_from_json"]

2. Checking for other metrics exposed in prometheus client we can't find any.
3. Replace namepass with =  ["file"] and can see all file input exposed metrics including non expected ones obviously.

So the measurement name looks to be **file** instead of the one generated via the json key:
**file_values_metrics_http_apdex**

If i do set namepass = ["file_values_bede_metrics_http_apdex"] wil return 0 metrics

### Expected behavior:

Get specific metrics as stated via namepass

### Actual behavior:

Depending on the value of namepass, can get all or none but not filtering any specific one.

**Comment by marioanton** [comment]
Hi Daniel,

thanks for coming back.

telegraf --config telegraf.conf -input-filter=file --test
> file,appkey=app1 values_test.http.apdex=0.15 1541496170000000000
> file,appkey=app2 values_test1.http.apdex=0.15 1541496170000000000
> file,appkey=app3 values_test2.http.failures=0 1541496170000000000
> file,appkey=app4 values_test2.http.failures=0 1541496170000000000

So i get this which is right, name_override is right as well. However, in prometheus when exporting the file, i get a mesasurement name for the metric which is much longer than this. Indeed, the prometheus metric name is the one i want to use cause it is sepcific depending on the json hence i can use namedrop/namepass to drop metric at input side.

e.g  for the above data:
metric names in prom:
file_values_test.http.apdex
file_values_test.http.failures

Metric name in telegraf : file

[[inputs.file]]
data_format = "json"
files = ["/tmp/metrics.json"]
namepass = ["file"] -> works (but doesn't make sense cause is the only metric name i got here)
namepass = ["file_values_test.http.failures"] -> doesn't work obviously cause doesn't match at input

namedrop= ["file"] -> works (but doesn't make sense cause is the only metric name i got here)
namedrop = ["file_values_test.http.failures"] -> doesn't work obviously cause doesn't match at input


Maybe i am misunderstanding the purpose of this filter.
Perhaps i can use name_override to make it dynamic at input level... :(

Thanks in advance

**Comment by danielnelson** [comment]
The metric filtering options all use the Telegraf names.  If you are looking at a line like this from the output of `--test`:
```
file,appkey=app3 values_test2.http.failures=0 1541496170000000000
```

This is one metric with a measurement name `file`, one tag `appkey` and one field `values_test2.http.failures`.  So if I'm understanding correctly you would want to use this to only emit the single metric:
```
fieldpass = ["values_test2.http.failures"]
```

**Comment by marioanton** [comment]
facepalm! Thanks for the input Daniel!
