### ISSUE TITLE
Use go for the ping plugin

### ISSUE THREAD

**Issue by xor-gate** [influxdata/telegraf#496]
I'm running telegraf in a systemd container with debian jessie. It seems it calls exec directly on `/bin/ping`. Telegraf runs under the user `telegraf` so the suid bit needs to be set. Maybe it should check this before invoking ?. And maybe it would be much nicer if we can directly ICMP from golang instead of executing a binary?

```
Jan 08 12:24:00 dev03 telegraf[14763]: ping: icmp open socket: Operation not permitted, exit status 2
```

```
[INCORRECT]
ls -al /bin/ping
-rwxr-xr-x 1 root root 40760 May 20 2011 /bin/ping

[CORRECT]
[root@pccadmin ~]# chmod 4755 /bin/ping
[root@pccadmin ~]# ls -tlr /bin/ping
-rwsr-xr-x. 1 root root 40760 Jul 18 2011 /bin/ping
```

then it works:
```
Jan 08 12:27:10 dev03 telegraf[14763]: 2016/01/08 12:27:10 Flushed 460 metrics to output influxdb in 62.249947ms
Jan 08 12:27:13 dev03 telegraf[14763]: 2016/01/08 12:27:13 Error in plugin [ping]: PING psu.local (192.168.23.65) 56(84) bytes of data.
Jan 08 12:27:13 dev03 telegraf[14763]: From 192.168.22.180 icmp_seq=1 Destination Host Unreachable
Jan 08 12:27:13 dev03 telegraf[14763]: --- psu.local ping statistics ---
Jan 08 12:27:13 dev03 telegraf[14763]: 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms, exit status 1
```

**Comment by zstyblik** [comment]
> Maybe it should check this before invoking ?

Do you mean Telegraf should check every 10s? Also, this is imho Debian's problem and not the Telegraf's problem. Don't get me wrong. I had the same problem with Nagios checks and wasn't happy about it either.

> And maybe it would be much nicer if we can directly ICMP from golang instead of executing a binary?

That would be awesome.

**Comment by sparrc** [comment]
looks like we may be able to use this library: https://github.com/tatsushid/go-fastping, that would be a better solution than executing the ping binary

**Comment by zstyblik** [comment]
@xor-gate btw the correct solution is to use/set capabilities `%  setcap cap_net_raw+p /bin/ping`

**Comment by xor-gate** [comment]
@zstyblik, you are right i'm not very familiar with the capabilities under linux. It is good to mention because `setuid bit` is kind of evil.

**Comment by zstyblik** [comment]
@xor-gate no worries. It's not from my head either ;)

**Comment by sparrc** [comment]
Changing this case to just track using golang for the ping plugin, which is probably the only real solution to this issue

**Comment by sparrc** [comment]
I wrote up a library for pinging via Go: https://github.com/sparrc/go-ping

BUT unfortunately this doesn't help much at all. Pinging relies on the setuid (or set capabilities) bits to execute certain system calls with root permission. Unless you gave the entire telegraf binary this permission (very very bad idea), pinging from Go has even less capabilities than using the binary.

I'm going to close this case with #629, in which I'm also putting a note in the config that some users may need to set capabilities on their ping binary for this plugin to work.

**Comment by xor-gate** [comment]
@sparrc this looks good, and unfortunately we need to set the capabilities but it is much much better than the previous exec and should be more portable when running under BSDs.
