### ISSUE TITLE
Ensure buffer is written to Influx even when there's no network connection

### ISSUE THREAD

**Issue by natejgardner** [influxdata/telegraf#4963]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

For IOT and mobile devices, connectivity is not guaranteed to be consistent. It would be great if Telegraf could robustly handle sending events gathered while offline as soon as the connection is restored.

### Current behavior:

Telegraf only writes to InfluxDB if InfluxDB is reachable. Events gathered when InfluxDB is unreachable are discarded and not written to InfluxDB when the connection is restored.

### Desired behavior:

Telegraf holds all messages in the buffer while InfluxDB is not reachable and only removes them from the buffer when InfluxDB has responded that the writes were successful (as long as the buffer hasn't filled).

### Use case: [Why is this important (helps with prioritizing requests)]
IOT devices, mobile devices, and basically everything that uses wifi or mobile networks deal with inconsistent connectivity. It'd be nice if that didn't imply losing all the data from those moments when the client is disconnected-- especially when behavior while disconnected is what one is trying to analyze!

**Comment by danielnelson** [comment]
Metrics collected when Telegraf is offline are added to the metric buffer and sent when a connection is re-established, this is true in the current release, <=1.8.3, as well as the latest release candidate.

I assume this is not what you are seeing, can you please add reproduction steps and we can look into what might cause your problem?

**Comment by danielnelson** [comment]
Can you show your configuration file and let me know what version of Telegraf you are using, and then also run your repro steps with `debug = true` in the agent config and also attach the logfile from during the test.

Telegraf does keep all metrics in memory, it never saves them to disk, so it does use additional memory when the output can not send but only up the `metric_buffer_limit`.

**Comment by natejgardner** [comment]
What are the units of `metric_buffer_limit`? Is it number of individual records stored?

**Comment by danielnelson** [comment]
Yes, each record is called a `metric` in Telegraf and it is defined as a measurement name + set of tags + one or more fields.  It more or less corresponds to a single line of InfluxDB line protocol.

**Comment by natejgardner** [comment]
Got it. It's possible the buffer simply overflows too quickly for me to notice. I've set it pretty high (around 1 million) but still apparently missed all the data from the offline time window. I'll experiment with the buffer limit and confirm, while also running with the debug flag to generate the log. Will Telegraf gracefully flush the buffer if it runs out of memory?

**Comment by danielnelson** [comment]
> Will Telegraf gracefully flush the buffer if it runs out of memory?

No, either the oom_killer terminates the process, which cannot be handled by a process at all, or the process panics and exits.  We don't try to handle the panic as it is usually is impossible to write data without the ability to allocate memory.

**Comment by phgogo** [comment]
I would really aprreciate a feature that allows for longer Caching (on-Disk).

My current Workaround is using the "exec" output plugin with a custom python script that tries to transmit the data and caches it locally for the event of a connection loss.

**Comment by yonas124** [comment]
@natejgardner is the buffer working then?

**Comment by jrc** [comment]
Relating #802
