### ISSUE TITLE
[inputs.mysql]: Not Supported - 21 columns

### ISSUE THREAD

**Issue by chpiter** [influxdata/telegraf#4965]
I use telegraf to monitor RDS-MySQL on Aliyun
my conf file:
> [[inputs.mysql]]
>   servers = ["xxxx:HpgxxxxHn369@tcp(xxxx:3306)/xxxx?tls=false"]
>   perf_events_statements_digest_text_limit  = 120
>   perf_events_statements_limit              = 250
>   perf_events_statements_time_limit         = 86400
>   table_schema_databases                    = []
>   gather_table_schema                       = true
>   gather_process_list                       = true
>   gather_user_statistics                    = true
>   gather_info_schema_auto_inc               = false
>   gather_innodb_metrics                     = true
>   gather_slave_status                       = false
>   gather_binary_logs                        = false
>   gather_table_io_waits                     = false
>   gather_table_lock_waits                   = true
>   gather_index_io_waits                     = false
>   gather_event_waits                        = false
>   gather_file_events_stats                  = false
>   gather_perf_events_statements             = false
>   interval_slow                             = "30m"

got this error message:
> E! Error in plugin [inputs.mysql]: Not Supported - 21 columns

I want to know which metrics not supported on Aliyun Rds MySQL

**Comment by glinton** [comment]
Do you know what version of MySQL is being used? Also, can you paste the output of the following query? 
```sql
SELECT * FROM information_schema.user_statistics LIMIT 2
```

**Comment by chpiter** [comment]
> Do you know what version of MySQL is being used? Also, can you paste the output of the following query?
> 
> ```sql
> SELECT * FROM information_schema.user_statistics LIMIT 2
> ```

MySQL 5.5
output:
![image](https://user-images.githubusercontent.com/3320906/48105897-3a7aa500-e274-11e8-8ff2-aeb0bd36bdc8.png)

**Comment by glinton** [comment]
Thanks, can you paste the column names (not screenshot)?

**Comment by chpiter** [comment]
> Thanks, can you paste the column names (not screenshot)?

USER                   : root
TOTAL_CONNECTIONS      : 8507761
CONCURRENT_CONNECTIONS : 0
CONNECTED_TIME         : 36869661
BUSY_TIME              : 2577
CPU_TIME               : 2596
BYTES_RECEIVED         : 1862233492
BYTES_SENT             : 2147483647
BINLOG_BYTES_WRITTEN   : 0
ROWS_FETCHED           : 20064409
ROWS_UPDATED           : 0
TABLE_ROWS_READ        : 0
SELECT_COMMANDS        : 6746933
UPDATE_COMMANDS        : 0
OTHER_COMMANDS         : 27564730
COMMIT_TRANSACTIONS    : 0
ROLLBACK_TRANSACTIONS  : 0
DENIED_CONNECTIONS     : 0
LOST_CONNECTIONS       : 20
ACCESS_DENIED          : 0
EMPTY_QUERIES          : 141977
