### ISSUE TITLE
Add support for Dovecot v2.3 stats

### ISSUE THREAD

**Issue by genofire** [influxdata/telegraf#4971]
- [x] at first please fix documentation URL from http://wiki2.dovecot.org/Statistics to http://wiki2.dovecot.org/Statistics/Old.

- [ ] And support the "new" http://wiki2.dovecot.org/Statistics Format.

**Comment by danielnelson** [comment]
I updated the documentation: https://github.com/influxdata/telegraf/commit/fbd3e7887ae8400191f55862d90e2066847daecd

**Comment by genofire** [comment]
Oh Thankyou for the Tip with the `old_stats` and `doveadm oldstats` support ;)

**Comment by sjwang90** [comment]
Closed in https://github.com/influxdata/telegraf/commit/fbd3e7887ae8400191f55862d90e2066847daecd

**Comment by pablocarreraest** [comment]
hey @genofire can you guide me how enable stats on dovecot?

**Comment by genofire** [comment]
New Documentation:
- old: https://doc.dovecot.org/configuration_manual/stats/old_statistics/#old-statistics
- new: https://doc.dovecot.org/configuration_manual/stats/
  - I have no rule set
  - I have not tried, sorry could not help there, yet

**Comment by pablocarreraest** [comment]
> old: https://doc.dovecot.org/configuration_manual/stats/old_statistics/#old-statistics

Are you using the old_statistics and manage make it work with telegraf?
