### ISSUE TITLE
Telegraf on Windows fails to stop/start or restart after running for an hour+

### ISSUE THREAD

**Issue by xkilian** [influxdata/telegraf#4975]
### Relevant telegraf.conf:

Enable default windows metrics
Send metrics every 30 seconds to 2 Graphite servers carbon-relays
Windows services
Windows processes
5 minute aggregation

### System info:
Windows 2008 R2
Windows 2012 Datacenter
Telegraf 1.7.x, 1.8.x

This issue is the same as the closed issue: #3601.

### Steps to reproduce:

Start Telegraf, let it run for an hour or so.
Stop it.
Start it. It will fail to start.
Start it again. It will start.

This issue is observed very often, because Telegraf is not stable on Windows, so it will often fail and services.msc can try to restart the services, but it will not work, as the service must be started TWICE for it to start. Has to resort to running a batch file to start it twice if it is not running. Not a very professional solution on Windows. 

### Expected behavior:

To start the first time...

### Additional info:

This issue was observer in 1.6x and seemed to be better in 1.7 and the issue was closed. But this issue is still present in all Telegraf versions. Issue #3601 is the original. Should be re-opened as not fixed.

**Comment by xkilian** [comment]
Oups. 
Meant to say it was thought to be fixed in 1.6 but it is back in 1.7.x and 1.8.x.

**Comment by glinton** [comment]
Can you include logs from trying to start it? If you are unsure where to find them, try running telegraf in the terminal `telegraf.exe --debug --config \path\to\config\file`

**Comment by ssoroka** [comment]
looks like you never got back to us. Let us know if this is still an issue.
