### ISSUE TITLE
http.listener_v2 and JSON Strings

### ISSUE THREAD

**Issue by benjamingrogg** [influxdata/telegraf#4976]
## Feature Request

inputs.http_listener_v2 just accept JSON Values. Is it possible that http_listener_v2 process also Strings in a JSON.

### Proposal:
Process also Strings in a JSON

### Current behavior:
Values are processed but String in a JSON not (eg. {"id": 1, "MyTest": "Horray"} )

### Desired behavior:
Also processing Strings

**Comment by danielnelson** [comment]
You can use the `json_string_files` option to whitelist string fields.  The full documentation for all the JSON options is at [/plugins/parsers/json](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json).  We also have an issue open for adding a way to get all strings without knowing the names: https://github.com/influxdata/telegraf/issues/4912
