### ISSUE TITLE
[inputs/ipmi_sensor] add support for -E flag

### ISSUE THREAD

**Issue by ytzelf** [influxdata/telegraf#4978]
### Proposal:
Add -E flag support to allow for docker-compose password input (vs. telegraf.conf) as explained in https://linux.die.net/man/1/ipmitool
### Current behavior:
Only way to input password is through telegraf.conf
### Desired behavior:
Allow users to pass password through IPMI _PASSWORD environment variable 
### Use case: [Why is this important (helps with prioritizing requests)]
Allow among other things to delegate password input to docker-compose file

**Comment by danielnelson** [comment]
Let's add a `username` and `password` option to the plugin and then you can use the normal environment variable replacement that Telegraf supports:
```
[[inputs.ipmi_sensor]]
  username = "bob"
  password = "$IPMI_PASSWORD"
```
If there are multiple `servers` specified these credentials would take place for all of them.

**Comment by ytzelf** [comment]
That's absolutely fine with me although I don't see the use for a global username as there is no -E equivalent for username.

**Comment by sspaink** [comment]
@ytzelf it seems this hasn't been implemented yet, are you still interested in seeing this feature completed?

**Comment by ytzelf** [comment]
Hi and thanks for this. I'm not using IPMI for sensor data so no that's not if interest to me anymore.

Best

**Comment by sspaink** [comment]
Thank you for your quick response, in that case I will be closing this issue. cheers!
