### ISSUE TITLE
[LINUX] inputs.mem: available memory and free memory do not add up to total memory

### ISSUE THREAD

**Issue by nvinzens** [influxdata/telegraf#4980]
[telegraf 1.8.1, linux]

We calculate and graph our available/used memory by using the `mem_available` and `mem_used` fields. We were surprised to see that those 2 fields added up don't add up to whats reported in `mem_total`.
After some digging around we figured out that the missing memory can be found by adding up the `mem_mapped` and `mem_dirty` fields.

Our numbers:
`mem_available`: 2.584858624e+09
`mem_used`: 1.465454592e+09
`mem_total`: 4.144848896e+09
`mem_dirty`: 303104
`mem_mapped`: 9.4232576e+07

`mem_total` - (`mem_available` + `mem_used`) = 94535680
`mem_dirty` + `mem_mapped` = 94535680

Is that intended? And if so, whats the reasoning behind it?

**Comment by danielnelson** [comment]
These values are taken from `/proc/meminfo` and the actual formula used is:
```
used = mem_total - mem_free - buffers - cached
```

The details of virtual memory are complicated, so our main goal is to match standard reporting tools such as top.  Here is a post that describes how top defines free memory: https://web.archive.org/web/20110207101856/http://www.linuxforums.org/articles/using-top-more-efficiently_89.html
