### ISSUE TITLE
Proper way to deprecate a feature

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#4992]
The Wavefront output plugin supports the concept to take a string metric and convert it to a numeric representation.  This was done through the `string_to_number` map.  Now that Telegraf has the [enum](https://github.com/influxdata/telegraf/tree/master/plugins/processors/enum) processor plugin, with intentions to do exactly this, the feature in the Wavefront output plugin should be deprecated so its use is discouraged, and hopefully one day removed.

What is the proper way to deprecate something like this?

**Comment by danielnelson** [comment]
In the sample config, add a note like this one from `outputs/amqp/amqp.go`:
```
## Broker URL
##   deprecated in 1.7; use the brokers option
# url = "amqp://localhost:5672/influxdb"
```

In the output itself you can add an log message that is printed once if the option is used.  We haven't done a good job of this so far, but it is something I would like to start doing:
```
log.Print("W! [outputs.wavefront] The string_to_number option is deprecated; please use the enum processor instead")
```

In Telegraf 2.0 we can remove the option.
