### ISSUE TITLE
Inputs Jenkins plugin authorization

### ISSUE THREAD

**Issue by MrRobbi** [influxdata/telegraf#4995]
### Relevant telegraf.conf:

[[inputs.jenkins]]
  ## The Jenkins URL
  url = "http://myjenkins.mydomain.com:8080"
  username = "user"
  password = "password"

### System info:
Debian 8.6
Apache2 krb+proxy
Telegraf 1.10.0 (latest nightly build)
Jenkins 2.148

### Steps to reproduce:

1. telegraf --config telegraf.conf --input-filter jenkins --test

### Expected behavior:

Listed jobs in output

### Actual behavior:

Error in plugin: empty monitor data, please check your permission

### Additional info:
telegraf log:
[inputs.jenkins]: Error in plugin: [/api/json] 401 Unauthorized

I think its all about apache2 Kerberos + proxy pass, but I can't figure out how to fix it.
I tried to use url without port 8080 specified.
Result: Error running agent: [/api/json] 401 Unauthorized

**Comment by glinton** [comment]
Make sure your username and password match what you have configured on the server. If you need more assistance with your permissions issue, [head over to the community forums](https://community.influxdata.com/). I'm going to close this as it is a configuration issue.

As a note, we'll never request your credentials or access to your system to verify your login is working.
