### ISSUE TITLE
CSV parser not recognising column header names

### ISSUE THREAD

**Issue by JonathanBowker** [influxdata/telegraf#5001]
### Relevant telegraf.conf:
```
[[inputs.amqp_consumer]]
  ## AMQP url
  brokers = ["amqp://localhost:5672"]
  auth_method = "PLAIN"
  username = "influxdb"
  password = "influxdb"  
  ## AMQP exchange
  exchange = "lix.data"
  ## AMQP queue name
  queue = "FX"
  ## Binding Key
  binding_key = "#"
  data_format = "csv"

[[inputs.file]]

  files = ["example"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["CurrencyPair","QuoteType","Tenor","MidPrice"]
  csv_skip_rows = 0
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = ""
  csv_trim_space = false
  csv_tag_columns = ["CurrencyPair","QuoteType","Tenor"]
  csv_measurement_column = "Tenor"
  csv_timestamp_column = "ActivityDatetime"
  csv_timestamp_format = "2018-10-11T13:11:20.428Z"
```

### System info:

Telegraf 1.8.3 - Ubuntu 18.04 Bionic

### Steps to reproduce:

I run the  `- telegraf -config telegraf.d/telegraf-rmq.conf ` command

### Expected behavior:

Parse the incoming files into Influx format but I receive the following response even though the csv column names are defined as above 

### Actual behavior:

`2018/11/17 05:17:41 E! Error parsing telegraf.d/telegraf-rmq.conf, there must be a header if csv_column_names is not specified`

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Judging by your config file, the error is for the `amqp_consumer` input. You will need to add `csv_column_names` to that block as well. Let us know if you still experience troubles, I'm going to close this for now.
