### ISSUE TITLE
custom hostname in every conf file

### ISSUE THREAD

**Issue by pc10201** [influxdata/telegraf#5002]
I want to use one telegraf process to monitor current linux system and a lot of cloud mysql instance (like AWS RDS).

But I can not use hostname or host tag to diff cloud mysql instance.

Can I set hostname or host tag for every conf file of mysql conf?

**Comment by danielnelson** [comment]
On the `mysql` input the `server` tag contains the hostname that is being monitored, I recommend using this tag, as the `host` tag is used to indicates the Telegraf doing the reporting which can be useful for determining who reported the data.

However, to specifically answer your question, you can set the host tag, or another tag for any plugin like:
```
[[inputs.mysql]]
  servers = ["foo"]
  # all the normal options
  [inputs.mysql.tags]
    host = "foo"

[[inputs.mysql]]
  servers = ["bar"]
  # all the normal options again
  [inputs.mysql.tags]
    host = "bar"
```

You won't be able to use a single plugin definition for multiple mysql instances if you go this route, as the tags table is per-plugin.
