### ISSUE TITLE
namedrop, fielddrop, tagdrop, namepass, fieldpass, and tagpass generate an error when used with inputs.win_perf_counters.object

### ISSUE THREAD

**Issue by gregvolk** [influxdata/telegraf#5013]
When I attempt to use input filtering with a directive like namedrop = ["isatap*"] inside a [[inputs.win_perf_counters.object]] config block I get this error "line 73: field corresponding to 'namedrop' is not defined in '*win_perf_counters.perfobject'".
 
I have also noticed the same error when trying to use fielddrop, tagdrop, namepass, fieldpass, and tagpass with [[inputs.win_perf_counters.object]].
 
### Relevant telegraf.conf:
```
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = "c:\\Program Files\\telegraf\\telegraf.log"
  hostname = ""
  omit_hostname = false
 
# Output plugin
[[outputs.graphite]]
  servers = ["graphite:2003"]
  prefix = "hf5.telegraf"
 
# Network inteface metrics
[[inputs.win_perf_counters.object]]
  ObjectName = "Network Interface"
  Instances = ["*"]
  Counters = [
    "Packets Received Discarded",
    "Packets Received Errors",
    "Packets Outbound Discarded",
    "Packets Output Errors",
    "Bytes Received/sec",
    "Bytes Sent/sec",
    "Packets Received/sec",
    "Packets Sent/sec"
  ]
  Measurement = "win_net"
  namedrop = ["isatap*"]
```
 
### System info:
Win7 6.1.7601 Service Pack 1 Build 7601
I reproduced the problem with Telegraf 1.8.3 and 1.9.0_rc2.
 
 
### Steps to reproduce:
1. Add a namedrop directive like 'namepass = ["isatap*"]' to any inputs.win_perf_counters.object section of a telegraf config file.
2. Execute telegraf.exe with the config file and you'll get "field corresponding to 'namedrop' is not defined."
3. Remove the namedrop directive from the config file, execute telegraf again, and it runs without errors.
 
 
### Expected behavior:
I expect any network interfaces that begin with isatap to be filtered out and not sent to my metrics collector.
 
### Actual behavior:
Telegraf generates the following error:
2018/11/20 11:59:36 E! Error parsing telegraf.conf, line 73: field corresponding to 'namedrop' is not defined in `*win_perf_counters.perfobject'
 

### Additional info:
My goal here is to have telegraf skip sending metrics for inactive/useless network interfaces like isatap, teredo tunnels, etc. If there is a better way to do this I'm open to suggestions. I also attempted to do this with 'namedrop = ["isatap*"]' as an outputs.graphite filter but could not make that work but that did not generate an error, it just didn't work (maybe I'm doing something syntactically wrong there?).

**Comment by danielnelson** [comment]
Because of the way TOML is parsed, any options that are set on the plugin must be placed before any subtables.  If they are placed below the subtable then they become part of the subtable.

Here is an example of the right ordering, but I think the namedrop value is probably not what you want, because in this example the name is always "win_net".  If you show me the output of `telegraf --test` I could help more with the filtering.

```toml
[[inputs.win_perf_counters]]
  namedrop = ["isatap*"]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Packets Received Discarded",
      "Packets Received Errors",
      "Packets Outbound Discarded",
      "Packets Output Errors",
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec"
    ]
    Measurement = "win_net"
```

**Comment by gregvolk** [comment]
Thank you for the quick reply and assistance. 

Here is my telegraf --test output
```
telegraf.exe --config telegraf.conf --test
> win_net,host=testhost,instance=Intel[R]\ Centrino[R]\ Advanced-N\ 6205,objectname=Network\ Interface Bytes_Received_persec=0,Bytes_Sent_persec=0,Packets_Outbound_Discarded=0,Packets_Received_Discarded=0,Packets_Received_Errors=0,Packets_Received_persec=0,Packets_Sent_persec=0 1542823232000000000
> win_net,host=testhost,instance=Local\ Area\ Connection*\ 13,objectname=Network\ Interface Bytes_Received_persec=0,Bytes_Sent_persec=0,Packets_Outbound_Discarded=0,Packets_Received_Discarded=0,Packets_Received_Errors=0,Packets_Received_persec=0,Packets_Sent_persec=0 1542823232000000000
> win_net,host=testhost,instance=isatap.testdomain.com,objectname=Network\ Interface Bytes_Received_persec=0,Bytes_Sent_persec=0,Packets_Outbound_Discarded=0,Packets_Received_Discarded=0,Packets_Received_Errors=0,Packets_Received_persec=0,Packets_Sent_persec=0 1542823232000000000
> win_net,host=testhost,instance=Intel[R]\ 82579V\ Gigabit\ Network\ Connection,objectname=Network\ Interface Bytes_Received_persec=9075.0634765625,Bytes_Sent_persec=63.92296600341797,Packets_Outbound_Discarded=0,Packets_Received_Discarded=0,Packets_Received_Errors=0,Packets_Received_persec=26.967500686645508,Packets_Sent_persec=0.9987963438034058 1542823232000000000
```

I added 
```
[[inputs.win_perf_counters]]
  namedrop = ["isatap*"]
```
to my config file and it didn't error out this time but as you predicted, it did not work because the name begins with win_net and not isatap. I also tried 
```
namedrop = ["*isatap*"] 
```
with no luck. I guess the wildcarding doesn't work that way.

I will continue to experiment with tagdrop and fielddrop but if you are able to point me in the right direction for how to do this that would be great.

Thanks again.

**Comment by danielnelson** [comment]
I think you will need tagdrop:

```toml
[[inputs.win_perf_counters]]
  [inputs.win_perf_counters.tagdrop]
    instance = ["isatap*"]

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Packets Received Discarded",
      "Packets Received Errors",
      "Packets Outbound Discarded",
      "Packets Output Errors",
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec"
    ]
    Measurement = "win_net"
```

**Comment by gregvolk** [comment]
That works. The isatap interface data no longer gets sent. 

Thank you!

**Comment by hackery** [comment]
Because the "O" in TOML is a barefaced lie.
