### ISSUE TITLE
Flatbuffer output format supported in Telegraf

### ISSUE THREAD

**Issue by sanchitgupta3112** [influxdata/telegraf#5014]
### Proposal:

Add support for flatbuffer output format in addition to JSON and influxline protocol.

### Current behavior:

Supports multiple output formats including json, influx line protocol

### Desired behavior:

Support flat buffer output format in addition to existing ones.

### Use case: [Why is this important (helps with prioritizing requests)]

We are working on building a scalable monitoring platform and using Telegraf with Kafka (along with other components) for data collection / streaming. We would like to use flat buffer protocol for data transfer instead of JSON / Influx line protocol for performance reasons.

**Comment by srebhan** [comment]
@sanchitgupta3112 is this still a thing? Do you care to submit a PR?
