### ISSUE TITLE
add ability to get token and send request wtih token we get in http_response plugin

### ISSUE THREAD

**Issue by root-ali** [influxdata/telegraf#5015]
## Feature Request

In the scenario i work , i have to get token from an apiGW and send request with this token

**Comment by danielnelson** [comment]
We can probably add this if the server you are interacting with implements a standardized authentication method.  Do you know if this is the case and what the method is?  Or, if you are interacting with a publicly available software package can you let us know what it is?

**Comment by mapl** [comment]
I am adding myself to this Feature request, but for the http input plugin.

When using OAUTH2, you need to get token first via a HTTP POST Request , then you will able to send a GET Request using the retrieved token.

https://aaronparecki.com/oauth-2-simplified/

1. POST https://api.authorization-server.com/token
    grant_type=client_credentials&
    client_id=CLIENT_ID&
    client_secret=CLIENT_SECRET


2. curl -H "Authorization: Bearer RsT5OjbzRn430zqMLgV3Ia" \
https://api.authorization-server.com/1/me

**Comment by danielnelson** [comment]
@mapl Can you open a new feature request.  I'm going to close this issue since there is not enough information.

**Comment by mapl** [comment]
sure

**Comment by debu99** [comment]
any update? is this feature implemented?
