### ISSUE TITLE
MySQL input plugin: gather clients IP addresses metrics from INFORMATION_SCHEMA.PROCESSLIST

### ISSUE THREAD

**Issue by bengoa** [influxdata/telegraf#5016]
## Feature Request

In some circumstances, it's useful to have information about clients IP addresses connected to MySQL Servers (especially when you have many clients connecting to MySQL servers).

### Proposal:

I think we could extend current GatherProcessListStatuses function in order to be able to gather this additional metric.

### Current behavior:

Currently, the plugin is able to collect this information:

mysql> SELECT user, sum(1) AS connections FROM INFORMATION_SCHEMA.PROCESSLIST GROUP BY user;             +-------------+-------------+
| user        | connections |
+-------------+-------------+
| user_A    |        1844 |
| replicate   |           2 |
| root        |           2 |
| system user |           2 |
+-------------+-------------+
4 rows in set (0.01 sec)

### Desired behavior:

I'm proposing to also gather clients IP Addresses doing something like this:

mysql> SELECT tmp.ipAddress, COUNT( * ) AS ipAddressCount FROM (SELECT pl.id, pl.user, pl.host, pl.db, pl.command, pl.time, pl.state, pl.info, LEFT( pl.host, ( LOCATE( ':', pl.host ) - 1 ) ) AS ipAddress FROM INFORMATION_SCHEMA.PROCESSLIST pl) AS tmp GROUP BY tmp.ipAddress ORDER BY ipAddressCount DESC;
+--------------+----------------+
| ipAddress    | ipAddressCount |
+--------------+----------------+
| 192.168.56.34 |            505 |
| 192.168.56.42 |            175 |
| 192.168.56.40 |            154 |
| 192.168.56.28 |            142 |

This query was inspired by this blog post: https://www.bennadel.com/blog/3054-grouping-the-mysql-processlist-by-ip-address-to-view-connection-counts.htm

### Use case: [Why is this important (helps with prioritizing requests)]

These metrics are very handy when investigating high loads/spikes on database servers and also makes easier to identify patterns and unusual connections volumes. 

I can provide a patch to extend the function if you guys think it is the right way to do.

Cheers,

**Comment by danielnelson** [comment]
The general problem with collecting ip addresses is that the potential cardinality is the maximum 32-bit integer (although often much less if all connections from a /24 network):
```
mysql_connections,address=192.168.56.34 connections=505
mysql_connections,address=192.168.56.42 connections=175
```

Perhaps there is a way to get similar information without using the IP?  I wonder if it is possible for a client to provide a user-agent style name?

**Comment by bengoa** [comment]
Hello Daniel,

Thanks for your answer.

I agree with you that the cardinality is a downside of this approach. On the other hand, if the idea is to identify patterns and unusual traffic from each client, I'm not positive we'll be able to reduce the cardinality independent of the key (due to the relation 1-1).

The cardinality, in this case, will be limited to the number of clients, which I mean servers, not final users (despite the fact that there are potential use cases where final users connect directly to the Database Servers). For this use cases, we could advise Telegraf users that they should consider the cardinality before enabling the option.

What do you think about?

Cheers,

**Comment by danielnelson** [comment]
I'd prefer not to add a query that we need to warn about since it does make using the plugin more difficult and could be an issue for those who turn it on unknowingly.  As you know we do warn about this on some plugins like docker, dcos, mesos but these are allowed because the cardinality is inherent to the plugin.

I think this might be better left as a custom query for either a generic sql plugin or something similar to the `postgresql_extensible` plugin.  I know this feature is something that has been in the works for a very long time without much progress but I do feel that it would be a better fit there.
