### ISSUE TITLE
how to exclude Exclude unwanted hostnames or datastores in telegraf

### ISSUE THREAD

**Issue by koushiktadikonda** [influxdata/telegraf#5022]
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Have you taken a look at [metric filtering in the docs](https://github.com/influxdata/telegraf/blob/1.9.0/docs/CONFIGURATION.md#metric-filtering)? For general questions please use the community forum at https://community.influxdata.com/

**Comment by koushiktadikonda** [comment]
Thanks @glinton
