### ISSUE TITLE
json_time_format documentation needs to explicitly define the date to use in the "reference time"

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#5026]
### System info:

Ubuntu 18.10
Telegraf 1.9.0 (git: HEAD 2bf21c0d)

### Steps to reproduce:
Create test json file ("`telegraf-test.json`") with the following included in the content (note the date is in the format "YYYY-**MM-DD** HH-MM-SS.000+0800" not "YYYY-**DD-MM** HH-MM-SS.000+0800" (i.e. UK format rather than US format?) which the input parser seems to expect

```
...
"date" : "2016-11-18 12:00:00.000+0800",
...
```

Create following telegraf config file: `telegraf-test-json.conf`
```
[[inputs.file]]
  files = ["telegraf-test.json"]

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json"

  ## Query is a GJSON path that specifies a specific chunk of JSON to be
  ## parsed, if not specified the whole document will be parsed.
  ##
  ## GJSON query paths are described here:
  ##   https://github.com/tidwall/gjson#path-syntax
  json_query = "**JSON_QUERY**"

  ## Tag keys is an array of keys that should be added as tags.
  tag_keys = [ "test" ]

  ## String fields is an array of keys that should be added as string fields.
 #json_string_fields = []

  json_string_fields = [ "date" ]

  ## Name key is the key to use as the measurement name.
  json_name_key = "test"

  ## Time key is the key containing the time that should be used to create the
  ## metric.
  json_time_key = "date"


  ## Time format is the time layout that should be used to interprete the
  ## json_time_key.  The time must be `unix`, `unix_ms` or a time in the
  ## "reference time".
  ##   ex: json_time_format = "Mon Jan 2 15:04:05 -0700 MST 2006"
  ##       json_time_format = "2006-01-02T15:04:05Z07:00"
  ##       json_time_format = "unix"
  ##       json_time_format = "unix_ms"
  json_time_format = "2016-11-18 12:00:00.000+0800"

```

Run the telegraf test as:
`telegraf --config telegraf-test-json.conf`

The following error is returned:

```
USER@HOST:~/telegraf-tests/json-importer$ telegraf --config telegraf-test-json.conf
2018-11-23T08:17:10Z I! Starting Telegraf 1.9.0
2018-11-23T08:17:10Z E! [telegraf] Error running agent: parsing time "2016-11-18 12:00:00.000+0800": month out of range

```

### Expected behavior:
The date is parsed correctly as expected

### Actual behavior:
When parsing the date, the error is thrown "month out of range"

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
We'll need to update the documentation for `json_time_format` when you manually specify, you must use the date from the example `Mon Jan 2 15:04:05 -0700 MST 2006` as that is what [golang's time format](https://golang.org/pkg/time/#Time.Format) expects.

**Comment by n1nj4888** [comment]
Hi @glinton ...

Does this mean, I simply need to specify json_time_format = "Mon Jan 2 15:04:05 -0700 MST 2006" in the config and it will find the date in the json file the format "2016-11-18 12:00:00.000+0800" and magically convert it to the expected unix date/time stamp, or are you saying that I would need to manually update my json files (i.e. using sed) so that the date format in those files is "Mon Jan 2 15:04:05 -0700 MST 2006"?

Thanks!

**Comment by glinton** [comment]
Nope, you just need to translate that reference date to the format desired. Updating your `json_time_format` to `2006-01-01 15:04:05.000+0700` should parse your dates, even "2016-11-18 12:00:00.000+0800", correctly.

**Comment by n1nj4888** [comment]
Thanks! Works as expected now... just wasn’t clear from the documentation but I see you have made a note to update the documentation...

Thanks again!

**Comment by glinton** [comment]
Oops, I made a typo in that original `json_time_format` example, it should be `2006-01-02 15:04:05.000+0700`, otherwise it won't parse the days past the 12th because it thinks that is a month.

**Comment by n1nj4888** [comment]
Thanks @glinton,

I think it should actually be as follows (note the -0700 rather than +0700)?

json_time_format = "2006-01-02 15:04:05.000-0700"?
