### ISSUE TITLE
inputs.system: document /var/run/utmp no such file workaround

### ISSUE THREAD

**Issue by MicahZoltu** [influxdata/telegraf#5031]
### Relevant telegraf.conf:
```
[[inputs.system]]
```

### System info:
Ubuntu 18.04 docker host.
`telegraph:alpine` docker image (I believe it is `1.8.3-alpine`)

### Steps to reproduce:

1. Run the docker image with `[[inputs.system]]` config.

### Expected behavior:
No errors.

### Actual behavior:
Error repeated with every interval.
```
E! Error in plugin [inputs.system]: open /var/run/utmp: no such file or directory
```

### Additional info:
I attempted to set HOST_VAR environment variable, only to realize that my host also doesn't have a `/var/run/utmp`.  I'm not sure why telegraf is looking for this file, but it doesn't exist in the docker container or on my host, and I don't see a way to disable looking for this file.

**Comment by arindamchoudhury** [comment]
Hi,

Are you setting this:

> volumes:
>   - /var/run/utmp:/var/run/utmp:ro
>   - /:/rootfs:ro

**Comment by MicahZoltu** [comment]
I am using `--mount 'type=bind,source=/var,dst=/host/var' -e HOST_VAR=/host/var`, which I believe does the same thing.  However, my host OS does not have a `/var/run/utmp` so no matter how I mount the container won't find that file, and since the container _also_ doesn't have the file I'm not sure why telegraf is looking for it.

**Comment by glinton** [comment]
Telegraf is looking for [`utmp`](https://en.wikipedia.org/wiki/Utmp) because that is the file unix uses to track logins/outs. Is this running on a vanilla 18.04 install or a cloud image of some kind? `utmp` should exist at `/var/run/utmp` on 18.04

**Comment by MicahZoltu** [comment]
Ah, I see the problem.  `/var/run` is a symbolic link to `/run`.  `utmp` _actually_ lives in `/run/utmp`.  When I bind mount `/var/run` in docker, it brings in the symbolic link (it doesn't follow the link during mounting) but that link ends up linking to `/run` of the container, which is empty.

I was able to resolve my problem with the following:
```
--env HOST_VAR=/host/var --mount 'type=bind,source=/run/utmp,dst=/host/var/run/utmp'
```

**Comment by MicahZoltu** [comment]
It would be nice if this were in the readme/instructions for the docker image.  Ideally the Docker setup instructions would "just work" with an OS that is as common as Ubuntu LTS.

**Comment by digikin** [comment]
Just want to say this solved my issue.  Telegraf is awesome, keep up the good work.
