### ISSUE TITLE
enum processor should also support tags

### ISSUE THREAD

**Issue by robcowart** [influxdata/telegraf#5033]
## Feature Request
As documented in #4616 the enum processor should support both fields and tags.

### Proposal:
Support for tags should be added.

### Current behavior:
In its current v1.9.0 form it only supports fields, not tags.

### Desired behavior:
It should also support tags.

### Use case: [Why is this important (helps with prioritizing requests)]
Here is an example where the SNMP object `hrStorageType`, which has a value that is an OID, can be made more user-friendly.

```
[[processors.enum]]
  [[processors.enum.mapping]]
    tag = "hrStorageType"
    [processors.enum.mapping.value_mappings]
      ".1.3.6.1.2.1.25.2.1.1" = "Other"
      ".1.3.6.1.2.1.25.2.1.2" = "RAM"
      ".1.3.6.1.2.1.25.2.1.3" = "Virtual Memory"
      ".1.3.6.1.2.1.25.2.1.4" = "Fixed Disk"
      ".1.3.6.1.2.1.25.2.1.5" = "Removable Disk"
      ".1.3.6.1.2.1.25.2.1.6" = "Floppy Disk"
      ".1.3.6.1.2.1.25.2.1.7" = "Compact Disc"
      ".1.3.6.1.2.1.25.2.1.8" = "RAM Disk"
      ".1.3.6.1.2.1.25.2.1.9" = "Flash Memory"
      ".1.3.6.1.2.1.25.2.1.10" = "Network Disk"
```

**Comment by ferrerogg** [comment]
I have a similar problem with diskio plugin and this feature would be very useful

**Comment by morph027** [comment]
Same applies to disk input for me ;)

**Comment by glinton** [comment]
If anyone get's a chance and would like, this is a build  (64 bit) where tags are supported in the enum processor. We'd love feedback:
- [windows](https://32855-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.11.0~9850ef33_windows_amd64.zip)
- [linux](https://32855-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.11.0~9850ef33_linux_arm64.tar.gz)
- [freebsd](https://32855-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.11.0~9850ef33_freebsd_amd64.tar.gz)

**Comment by prandelicious** [comment]
Does this work if the target/destination is a tag instead of field? For example, I'm looking at mapping these to a host:

`    [processors.enum.mapping.value_mappings]
      "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:4091/jmxrmi" = "host01"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:5091/jmxrmi" = "host01"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:6091/jmxrmi" = "host01"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:6093/jmxrmi" = "host01"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:8091/jmxrmi" = "host01"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:5091/jmxrmi" = "host03"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:6091/jmxrmi" = "host03"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:6093/jmxrmi" = "host03"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:6095/jmxrmi" = "host03"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:6097/jmxrmi" = "host03"
      "service:jmx:rmi:///jndi/rmi://10.1.xx.yy:6099/jmxrmi" = "host03"`

**Comment by danielnelson** [comment]
#5855 keeps the tag/field status of the source key, but you can follow up the processor with the `converter` processor if you need to change it.
