### ISSUE TITLE
Description of processor / output plugins is swapped

### ISSUE THREAD

**Issue by mmariani** [influxdata/telegraf#5039]
### Steps to reproduce:

1. Go to https://docs.influxdata.com/telegraf/v1.9/plugins/

### Expected behavior:

The Telegraf processor plugins transform, decorate, and filter metrics.
The Telegraf output plugins write metrics to various destinations.

### Actual behavior:

The Telegraf output plugins transform, decorate, and filter metrics.
The Telegraf processor plugins write metrics to various destinations.

**Comment by glinton** [comment]
Thanks! Feel free to open a pull request with those changes.

**Comment by danielnelson** [comment]
@stevebang Can you take a look at this?

**Comment by stevebang** [comment]
The documentation descriptions described above are almost exact copies of descriptions from the [Telegraf README](https://github.com/influxdata/telegraf#telegraf--):

```
Telegraf is plugin-driven and has the concept of 4 distinct plugin types:
* Input Plugins collect metrics from the system, services, or 3rd party APIs
* Processor Plugins transform, decorate, and/or filter metrics
* Aggregator Plugins create aggregate metrics (e.g. mean, min, max, quantiles, etc.)
* Output Plugins write metrics to various destinations
```
If the docs are incorrect, then we need to fix the descriptions in the Telegraf repository too.  Daniel and I will review and revise the content for the repository and documentation to correct any errors and improve the descriptions.

**Comment by stevebang** [comment]
Fixed and changes have been published. Thanks, @mmariani, for catching that mistake.  Sorry for any confusion.
