### ISSUE TITLE
systemd requires /etc/defaults/telegraf

### ISSUE THREAD

**Issue by padcom** [influxdata/telegraf#504]
The package build using `package.sh` does not create the `/etc/defaults/telegraf` file required by `systemd` in `telegraf.service:7`. Without creating even an empty `/etc/defaults/telegraf` file the service won't start.

Tested under Raspbian (Debian Jessie) but should be the same since that is a systemd issue.

**Comment by sparrc** [comment]
@rossmcdonald has this been fixed with the new packaging scripts from #497?

**Comment by padcom** [comment]
Possibly

https://github.com/influxdata/telegraf/pull/497/files#diff-b6751345d3563056b97c219a56bddeb9R38 

This looks like what'd be needed. If I'd like to test which branch should I build?

**Comment by sparrc** [comment]
@padcom probably you'll want to use 0.10.0 (0.3.x is 0.10.x now, to coincide with releases of the other influx products)

**Comment by sparrc** [comment]
@padcom I just tested on ubuntu 15 and it is working, as well as creating an /etc/default file:

```
ubuntu-vivid-64:~$ ls /etc/default/telegraf
/etc/default/telegraf
```

please create a new issue if you notice any other problems.

**Comment by padcom** [comment]
I just finished my tests as well - works as it should. Thanks!

Any timeline for the 0.10.0 release?

**Comment by sparrc** [comment]
@padcom are you asking for the release date? or a list of upcoming features?

**Comment by padcom** [comment]
More like a release date...
