### ISSUE TITLE
Feature Request: Add nmap as supported input plugin

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#5042]
### Proposal:
Add nmap as supported input plugin for telegraf to gather details on the currently connected hosts on the network LAN including IP Address, Hostname, Latency, MAC Address, MAC Vendor etc...

### Current behavior:
There is currently no nmap plugin. This maybe possible with the Exec Plugin but not sure of how to parse and write to a table the example output from nmap below?

### Desired behavior:
namp is able to be configured as a telegraf input plugin. The plugin is able to run nmap (with configurable command switches), parse the output of the nmap application and then write the output to the desired telegraf output plugin (e.g. InfluxDB)... For example (note sudo is required for MAC ADDRESS / VENDOR, otherwise only IPs/Hostname output):

```
$ sudo nmap -sP -R --dns-servers <LOCAL DNS SERVER / ROUTER IP> NNN.NNN.NNN.0/24

Starting Nmap 7.60 ( https://nmap.org ) at 2018-11-27 09:58 +08
Nmap scan report for <HOSTNAME> (<HOST IP>)
Host is up (0.00076s latency).
MAC Address: XX:XX:XX:XX:XX:XX (<MAC VENDOR>)
...
...
...
...
Nmap scan report for <HOSTNAME> (<HOST IP>)
Host is up.
Nmap done: 256 IP addresses (NNN hosts up) scanned in 8.61 seconds
```

### Use case: [Why is this important (helps with prioritizing requests)]
The nmap plugin would be very useful in highlighting what devices were connected to the network and when, along with giving the IPs, hostnames, MAC Address/Vendors etc for a high level view of what is currently on the network and the latency to those devices... allowing the command to run as normal would give the IP/Hostname/Latency of all the network devices, but adding the ability to run as sudo also give the MAC Address and MAC Vendors which is also very useful in helping to identify the devices...

**Comment by danielnelson** [comment]
The output of nmap can vary a bit depending on the options, the example here is just doing a ping scan, but another way the nmap command could work is doing a portscan.  As these two functions are quite a bit different and have different outputs they should probably be considered separately instead of trying to support both in a single plugin.

If you want to set this up as a exec script, you would write a program that runs this command and then converts the output into one of the [input data formats](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md), I suggest outputting in influx, csv, logfmt, or json.  Something like this should get you started though you may want to switch to python or another language in order to combine the lines:

```
#!/bin/sh
nmap -sn -R --dns-servers 192.168.0.1 192.168.0.0/24 | grep 'Nmap scan report for' | sed -E 's/Nmap scan report for (.+) \((.+)\)/nmap,source=\1 address=\"\2\"/'
```

**Comment by n1nj4888** [comment]
Hi @danatinflux ,Thanks for this!

Would it be possible to have an option in an nmap plugin to either use a ping scan (as above) or a port scan where the actual namp commands being run for each are in a standard format and therefore the output is more determinable to telegraf? For example, if the nmap option was set to "ping-scan" it would run something like:

`sudo nmap -sn -R --dns-servers 192.168.0.1 192.168.0.0/24`

And expect the determinable output format to be:

`time,nmap,source="<HOSTNAME>" address="IP ADDRESS" latency=<LATENCY (s)> mac_address="<MAC ADDRESS>" mac_vendor="<MAC VENDOR>"`

Something similar for the port-scan option (i.e. without giving to many options to the user on the actual nmap command line switches which could change the determinable output format)?

In the meantime, I'll take a look at trying to use Python to read the multiple line output/device from nmap and format as per your example above!

**Comment by Hipska** [comment]
You can run nmap with the [inputs.exec](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec) plugin (add command line parameter `-oX -`) and parse the results with [parser.xpath](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath) (by setting `data_format = "xml"`).
