### ISSUE TITLE
[inputs.http_response] https with cipher suite TLS_DHE_RSA_WITH_AES_256_CBC_SHA

### ISSUE THREAD

**Issue by UweBeckert** [influxdata/telegraf#5044]
I'm sending soap requests via https by using inputs.http_response. But my soap server only supports 
* TLS_DHE_RSA_WITH_AES_256_CBC_SHA and
* TLS_DHE_RSA_WITH_AES_128_CBC_SHA

Those 2 cipher suites are not part of the TLS client hello.

I can't change the soap server to accept different cipher suites.

Is there a way to add additional cipher suites to the TLS client hello?

I get "remote error: tls: handshake failure" from http_response plugin. In tcpdump I see that no server hello is received. Because the client cipher suites are not accepted.

### System info:
telegraf 1.9
CentOS 7

**Comment by glinton** [comment]
This is because [golang](https://github.com/golang/go/issues/7758#issuecomment-274376902) (and apparently [several browsers](https://stackoverflow.com/a/43249703/9226947)) are not supporting those suites. I'm going to close this for now as it's not telegraf specific.
