### ISSUE TITLE
Link in Readme to version 0.10 .deb/.rpm results in 404

### ISSUE THREAD

**Issue by sofixa** [influxdata/telegraf#505]
Hello,

The links to the new versions of Telegraf, both in .rpm and .deb format, return in a 404 error:

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: telegraf/telegraf_linux_amd64_0.10.0.tar.gz
RequestId: E498FE9D7B26F637
HostId: e0tiX/wOG/B0IVay5jvHNlqzyyQt4g6d9PM51VWXXDmfPDJ2Jayvhi9ha3aD/yAJ3C/d5f7j/H0=
```
Could you please update them? And it'd be nice to have a tutorial (or at least a mention, i'd happily write a more detailed tutorial if needed) how to update from 0.2.4 to 0.10.0 :)

**Comment by jcmartins** [comment]
Where is the correct download to telegraf?
https://repos.influxdata.com 
or in the web
http://get.influxdb.org/telegraf/

**Comment by sparrc** [comment]
@jcmartins both, but repos should generally be used for automating yum/apt only

**Comment by sparrc** [comment]
@sofixa I seem to have something in the new build script wrong wrt AWS, working on a fix now

**Comment by sparrc** [comment]
should be fixed now, thanks for the report @sofixa!

There will be a blog post tomorrow about the 0.10.0 release, which will have additional information about migrating.
