### ISSUE TITLE
telegraf [[inputs.http_response]] :: always getting result_type="timeout"

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5050]
HI,

PFB configuration I am using to enable URL monitoring, 

 [[inputs.http_response]]
    address = "https://abc.xyz.com:12345"
    follow_redirects = false

Always  getting result_type="timeout" to monitor any "https" url, kindly correct me what i am missing.
Note: port(i.e 12345) is open from source IP(from where I am monitoring) to destination IP(i.e abc)

TIA

**Comment by glinton** [comment]
Thanks, can you provide a bit more info and more of your config. You can follow the [bugreport template](https://github.com/influxdata/telegraf/issues/new?template=Bug_report.md) as a starting point. It seems like you need to increase your `response_timeout` in the config.

**Comment by priyankamondalairtel** [comment]
Thanks, i have increased response_timeout = "120s" and it is working fine now.
