### ISSUE TITLE
[doc] Plugin influxdb_v2 listed as input plugin 

### ISSUE THREAD

**Issue by lpic10** [influxdata/telegraf#5051]
There is a small issue on the [README.md](https://github.com/influxdata/telegraf/blob/master/README.md#input-plugins), as the plugin influxdb_v2 is listed as input plugin instead of  output plugin. 

I only found that because I clicked on it by mistake and I got a 404. The commit that added this link is few months old, and no one noticed (or reported). 

I think adding a link checker, like https://github.com/dkhamsing/awesome_bot to the build process could help finding these issues and eventually finding also new broken links, like links to 3rd party documentation on the plugins docs.

**Comment by glinton** [comment]
There is both an input and output influxdb_v2 plugin, so we'll definitely have to check the links

**Comment by danielnelson** [comment]
https://github.com/influxdata/telegraf/commit/168c2b0ed15e358d0db510dd35e685dd2f6ea06b
