### ISSUE TITLE
Ping timetouts not respected on DNS lookups.

### ISSUE THREAD

**Issue by MicahZoltu** [influxdata/telegraf#5059]
### Relevant telegraf.conf:
```
[[inputs.ping]]
  interval = "2s"
  urls = ["bing.com","google.com"]
  count = 1
  timeout = 1.0
  deadline = 1
```

### System info:

Ubuntu 18.04
Telegraf 1.8.3

### Steps to reproduce:

1. Setup ping telegraf and ping plugin with short timeouts (e.g., 1s)
2. Ping a host that is not resolvable.

### Expected behavior:
An error is collected in under 1 second.

### Actual behavior:
An error is eventually collected, but long after the 1s timeout, resulting in missed batches due to collection taking too long.

### Additional info:
This issue was brought up in https://github.com/influxdata/telegraf/issues/3333, but it seems the issue got distracted with how to present DNS errors and the eventual "fix" for the issue didn't actually include addressing the ping timeout problem, though it did address the DNS lookup error problem.

Perhaps it is possible to have a global timeout for the ping operation in Go (both for the DNS lookup and the ping combined) and if the timeout is reached the goroutine is killed and an error is collected.  At the moment, there are a number of things that can timeout, but in many cases if it takes longer than some well known amount of time (e.g., 1 second) then from the user's point of view it is an error and should be reported as such, regardless of what specifically went wrong.  This would resolve the collection sometimes taking longer than interval, thus you would always get _something_ each collection period, even if it was just an error.

**Comment by danielnelson** [comment]
I think this is the right approach, adding an option `gather_timeout` option that applies to the full operation.  Then we just need to use a single context and the `LookupHost` method that takes a context as well as limit the run of the ping comment with the same context.
