### ISSUE TITLE
[[inputs.net_response]]:: getting "connection_failed" for tcp port monitoring

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5060]
HI,

getting result_type= "connection_failed", while this port connection has already established.

[[inputs.net_response]]
protocol = "tcp"
address = "localhost:7005"

can you suggest what I am missing here?

connection already established::
netstat -anp | grep 7005
.
.
.
tcp        0      0 xx.xx.xx.xx:7005        xx.xx.xx.xx:45556       ESTABLISHED 15725/java

**Comment by danielnelson** [comment]
This seems expected, net_response attempts to make a new connection but the port already has an active connection.  To connect you would need to contact a port that is marked LISTEN:
```
$ netstat -anp | grep 9999
tcp        0      0 0.0.0.0:9999 0.0.0.0:*  LISTEN      27407/python3.6
```
