### ISSUE TITLE
Override tag(or field) name when using `json` data format of `http` input plugin

### ISSUE THREAD

**Issue by rajalokan** [influxdata/telegraf#5062]
## Feature Request
* Override tag(or field) name when using `json` data format of `http` input plugin
* In same way alter data types of http response while parsing it using `http` input plugin

### Proposal:
I would like to have something like a label key which overrides tag or field name while parsing json response of an `http` input plugin. 

I will take below http response for example and show current as well as expected behaviour. 
```
{
    "foo": "FOO",
    "bar": "BAR",
    "entries": {
        "1": {
            "a": {
                "A": {
                    "Average": {
                        "description": "0"
                    },
                    "Current": {
                        "description": "0"
                    },
                }
            }
        },
        "2": {
            "b": {
                "B": {
                    "Average": {
                        "description": "0"
                    },
                    "Current": {
                        "description": "0"
                    },
            }
        },
        "3": {
            "c": {
                "C": {
                    "Average": {
                        "description": "0"
                    },
                    "Current": {
                        "description": "0"
                    },
                }
            }
        },
        "4": {
            "d": {
                "D": {
                    "Average": {
                        "description": "0"
                    },
                    "Current": {
                        "description": "0"
                    },
                }
            }
        }
    }
}
```
This above response can be simply parsed with http input plugin config as below
```
[[inputs.http]]
  urls = ["my_custom_url"]

  data_format = "json"
  tag_keys = ["1_a_A_Current_Description","2_b_B_Current_Description", ...]
  json_query = "entries"
```

### Current behavior:
With the above http input config, we get a  time series point with pretty weird field name like 1_a_A_Current_Description or 2_b_B_Current_Description. Like this **(http,1_a_A_Current_Description,2,b,B_Current_Description )**

Also if the returned value type is string, it is stored as it is.

### Desired behavior:
What I expect is to have a much cleaner label for tags (or field names) which could override the default `_` created name. Something like this
**(http,a,b)**

Also if we can have opportunity to convert the type of this data from string to int. That would be highly desirable. 

### Use case:
This way I can have a clean measurement tags and field name for cases when we have no control over the requesting API endpoint. Also gives us an another chance to give a more appropriate name for our measurement.

Please let me know if anything needs more clarification or my assumption is wrong anywhere or this is already present.

**Comment by danielnelson** [comment]
You can do this with the rename or regex processor:
```toml
[[processors.rename]]
  namepass = "http"
  [[processors.rename.replace]]
    tag = "1_a_A_Current_Description"
    dest = "a"
  [[processors.rename.replace]]
    tag = "2_b_B_Current_Description"
    dest = "b"
```

**Comment by rajalokan** [comment]
Wooohoo. Thanks for the quick response team. This is working. :+1:

**Comment by rajalokan** [comment]
One small gotcha though. At time even with converter processor ( to convert string value to int) I see values being stored as string. 

I even restarted influxdb ( to ensure no caching of data) and drop measurement but still now data is being stored as string only. But I clearly remember data type being converted to integer and everything working. Just that after a while ( while trying out another things), I see it always pushing string value. 

Let me know if I'm clear on my issue or if I need to open a new issue for this. Stuck on this so any help will be great. Thanks again @danielnelson
