### ISSUE TITLE
Push Telegraf 1.9.0 To Dockerhub

### ISSUE THREAD

**Issue by devnulled** [influxdata/telegraf#5065]
I see there has been a release created for Telegraf 1.9.0 but it doesn't seem to be in Dockerhub?

https://hub.docker.com/r/library/telegraf/tags/

**Comment by danielnelson** [comment]
The docker images are produced in https://github.com/influxdata/influxdata-docker/, I have a pull request open: https://github.com/influxdata/influxdata-docker/pull/270

**Comment by glinton** [comment]
Closed by https://github.com/influxdata/influxdata-docker/pull/270
