### ISSUE TITLE
SQL Server Metrics V2 Add ProductVersion

### ISSUE THREAD

**Issue by SteveKnowless** [influxdata/telegraf#5067]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add ProductVersion to V2 Metrics of SQL Input Plugin

### Current behavior:
Unable to view SQL ProductVersion with V2 Metrics of SQL Input Plugin

### Desired behavior:
View the ProductVersion

### Use case: [Why is this important (helps with prioritizing requests)]
I would like to display the ProductVersion in my Grafana Dashboards

**Comment by danielnelson** [comment]
cc @m82labs

**Comment by m82labs** [comment]
The version number is currently collected already, 14.0.3025.34 for
example.

Are you looking for something else?

**Comment by SteveKnowless** [comment]
I do not get that with V2 of the Metrics Plugin. What I get and see is the "Engine_Edition" which returns an integer based on the product edition (3 For Example). I was looking through the collection code of V2 and did not see anywhere for selecting the ProductVersion (14.0.3025.34) but I do see that in the V1 of the code. Did I maybe miss something? I also looked through my data and did not see anything similar to the ProductVersion being collected. Thanks for your help.

**Comment by m82labs** [comment]
I’ll look into this.

**Comment by m82labs** [comment]
This got removed accidentally. I am adding it back in a PR soon.

**Comment by SteveKnowless** [comment]
Awesome! Thanks a ton.

**Comment by m82labs** [comment]
I have a version built with these changes. I am going to eat lunch and let it collect data, make sure things look fine.

**Comment by danielnelson** [comment]
Closed by #5135
