### ISSUE TITLE
Can't rename inputs.file json output fields?

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#5070]
### System info:
**Telegraf Docker:** Telegraf 1.9.0 (git: HEAD 2bf21c0d)

### Steps to reproduce:
The following is currently output from my inputs.file json parser:
`> measurement,TAG1=TAG1_VALUE,host=HOST FIELD1=FIELD1_VALUE,FIELD2=FIELD2_VALUE, FIELD3=FIELD3_VALUE TIME`

If I add the following to the end of my [[inputs.file]] config, nothing is changed and the values output are the same as above?
```
  [[processors.rename]]
  ## Specify one sub-table per rename operation.
  [[processors.rename.replace]]
    field = "FIELD3"
    dest = "FIELD3-NEW-NAME"
```

Shouldnt this change the output to the following FIELD3 name to FIELD3-NEW-NAME?
`> measurement,TAG1=TAG1_VALUE,host=HOST FIELD1=FIELD1_VALUE,FIELD2=FIELD2_VALUE, FIELD3-NEW-NAME=FIELD3_VALUE TIME`

Thanks,

### Expected behavior:
Output field is renamed to the following:
`> measurement,TAG1=TAG1_VALUE,host=HOST FIELD1=FIELD1_VALUE,FIELD2=FIELD2_VALUE, FIELD3-NEW-NAME=FIELD3_VALUE TIME`

### Actual behavior:
Output field is not renamed at all and output i exactly the same whether or not the following is added to the end of the [[inputs.file]] section in the config file:

`> measurement,TAG1=TAG1_VALUE,host=HOST FIELD1=FIELD1_VALUE,FIELD2=FIELD2_VALUE, FIELD3=FIELD3_VALUE TIME`

**Comment by danielnelson** [comment]
This seems to work for me with this plugin configuration:

```toml
[[inputs.file]]
  files = ["foo"]
  data_format = "influx"

[[processors.rename]]
  [[processors.rename.replace]]
    field = "FIELD3"
    dest = "FIELD3-NEW-NAME"

[[outputs.file]]
  files = ["stdout"]
```

```
$ cat foo
measurement,TAG1=TAG1_VALUE,host=HOST FIELD1="FIELD1_VALUE",FIELD2="FIELD2_VALUE",FIELD3="FIELD3_VALUE" 1543605090000000000
```

```
$ telegraf
measurement,TAG1=TAG1_VALUE,host=HOST FIELD1="FIELD1_VALUE",FIELD2="FIELD2_VALUE",FIELD3-NEW-NAME="FIELD3_VALUE" 1543605090000000000
```

One gotcha, maybe this is what you are experiencing, is that processors don't currently run as part of `--test`, which is why I used the file output.  This will likely be changed in the future.

**Comment by Utopolis** [comment]
Hi I would like to know if it is possible to rename the measurment name.
Unstead having all the data send in the time series "file", having "new_name".
