### ISSUE TITLE
strconv.Atoi: parsing "???": invalid syntax

### ISSUE THREAD

**Issue by shinux** [influxdata/telegraf#5071]
### Relevant telegraf.conf:
    [[inputs.exec]]
        commands = ["bash /example.sh"]
        interval = "15s"
        data_format = "influx"

`example.sh`, just like README.md example described:

    #!/bin/sh
    echo 'example,tag1=a,tag2=b i=42i,j=43i,k=44i'

### System info:

Telegraf v1.7.0 (git: release-1.7 f4d22dd4)

NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
InfluxDB shell version: 1.5.2
InfluxDB v1.5.2 (git: 1.5 02d7d4f043b34ecb4e9b2dbec298c6f9450c2a32)

### Steps to reproduce:

1. write script
2. add inputs.exec in telegraf.conf
3. reproduce error below.

### Expected behavior:

insert into influx DB correctly

### Actual behavior:

`E! Error in plugin [inputs.exec]: strconv.Atoi: parsing "i=42i,j=43i,k=44i": invalid syntax`

### Additional info:

I'v tried directly to insert into influx cli with line protocol , and it worked.
unfortunately, telegraf failed to parse them ?

**Comment by danielnelson** [comment]
Everything looks right here, and I am unable to replicate the issue.  Here is what I tried, do you see anything we are doing differently?:

```sh
$ cat /etc/os-release  | grep VERSION
VERSION="14.04.5 LTS, Trusty Tahr"
VERSION_ID="14.04"
$ telegraf --version
Telegraf v1.7.0 (git: release-1.7 f4d22dd4)
$ cat telegraf.conf
[agent]
  interval = "10s"
[[inputs.exec]]
  commands = ["bash /example.sh"]
  timeout = "5s"
  data_format = "influx"
$ cat /example.sh
#!/bin/sh
echo 'example,tag1=a,tag2=b i=42i,j=43i,k=44i'
$ telegraf --config telegraf.conf --test
> example,host=ubuntu-trusty-repos.virt,tag1=a,tag2=b i=42i,j=43i,k=44i 1543601513000000000
```

**Comment by shinux** [comment]
After restart telegraf and I can't reproduce this error with same script.

(It seems when some error occurred, telegraf won't do auto-reload even error has been solved)
