### ISSUE TITLE
Filter some input only to the specific output

### ISSUE THREAD

**Issue by chpiter** [influxdata/telegraf#5072]
I defined many (200+) inputs file in '/etc/telegraf/telegraf.d' ,type of  inputs.mysql
and i defined output: influxdb and prometheus_client
I want to output mysql metrics only to prometheus_client, not to influxdb
How can I do it , thanks very much!

**Comment by danielnelson** [comment]
You can use namepass/namedrop like in this [example](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#output-configuration-examples).  Use namepass in the prometheus_client output and namedrop in the influxdb output.

Another popular method is by adding tags in the input and removing them at the output:
https://github.com/influxdata/telegraf/issues/1778#issuecomment-247605473

**Comment by ramyam07** [comment]
Hi Daniel 

My requirement to filter the logs by status code . We need filter out if the status code is 500

please provide an approach

**Comment by powersj** [comment]
@ramyam07 this is not the place to ask questions like that. Please check out our [Community Forum](https://community.influxdata.com) or ask on our [Community Slack](https://influxdata.com/slack). Folks on there will be more than happy to help you out!
