### ISSUE TITLE
Path to nvidia-smi on Windows breaks telegraf config parsing

### ISSUE THREAD

**Issue by aaronjwood** [influxdata/telegraf#5077]
Using the [nvidia-smi](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nvidia_smi) plugin on a [Windows](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nvidia_smi#windows) box throws an error if the path to the smi binary does not have double backslashes. For example:

```
# Pulls statistics from nvidia GPUs attached to the host
[[inputs.nvidia_smi]]
  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
  bin_path = "C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe"

  ## Optional: timeout for GPU polling
  # timeout = "5s"
```
fails with `2018-12-02T09:07:01Z E! [telegraf] Error running agent: Error parsing C:\Program Files\Telegraf\telegraf.conf, toml: line 157: parse error` but succeeds with

```
# Pulls statistics from nvidia GPUs attached to the host
[[inputs.nvidia_smi]]
  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
  bin_path = "C:\\Program Files\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe"

  ## Optional: timeout for GPU polling
  # timeout = "5s"
```

I'm guessing this is not isolated to the nvidia-smi plugin and applies to other Windows inputs...?

**Comment by glinton** [comment]
Thanks for this. It isn't quite a bug though, as any string in the config that doesn't have [escaped special characters](https://github.com/toml-lang/toml#string) would cause parse issues. Two of the most common are the backslash and double quote, they need to be inserted in a string in the config as follows `"\\"` and `"\"some quote\""`
