### ISSUE TITLE
Redis plugin: document 'password' option in README

### ISSUE THREAD

**Issue by matisssse** [influxdata/telegraf#5079]
Hello, i try to use telegraf with redis but i got error - [inputs.redis]: Error in plugin: NOAUTH Authentication required.
It is my config:
```
[[inputs.redis]]
  ## specify servers via a url matching:
  ##  [protocol://][:password]@address[:port]
  ##  e.g.
  ##    tcp://localhost:6379
  ##    tcp://:password@192.168.99.100
  ##
  ## If no servers are specified, then localhost is used as the host.
  ## If no port is specified, 6379 is used
  servers = ["tcp://localhost:6379"]
```
Should i use only with login/password?
Thank you.

**Comment by glinton** [comment]
You can either set the password in your `servers` option (`servers = ["tcp://:mypassword@localhost:6379"]`), or add the `password` option (`password = "mypassword"`) to your config file.
