### ISSUE TITLE
Parsing Netscaler json output for graphite

### ISSUE THREAD

**Issue by elcool0r** [influxdata/telegraf#5111]
Hey guys,
I'm wondering if my goal is even possible and as I could not figure it out myself I hope someone can help me here.
I want to get netscaler json stats into our graphite. The problem is that metrics (loadbalancer names) are including dots which graphite is using as a seperator.

So my question is if it is possible to rewrite data like this:
`telegraf.https:--loadbalancer-nitro-v1-stat-csvserver.test-website.search.preview.foo.bar.com-https.hitsrate 0 1544004798`
to
` telegraf.https:--loadbalancer-nitro-v1-stat-csvserver.test-website_search_preview_foo_bar_com-https.hitsrate 0 1544004798
`
I'm using the http input with this config:
```
[[inputs.http]]
urls = [
  "https://lloadbalancer/nitro/v1/stat/csvserver"
]

data_format = "json"
json_query = "csvserver"
json_name_key = "name"
```
I've tried around with the seperator but I could not figure it out.

**Comment by glinton** [comment]
You should be able to use the [regex processor](https://github.com/influxdata/telegraf/tree/1.9.0/plugins/processors/regex), I'll re-open if that doesn't work for you.
