### ISSUE TITLE
Wavefront data format rejects delta metrics

### ISSUE THREAD

**Issue by snltd** [influxdata/telegraf#5114]
### Relevant telegraf.conf:

```
[[inputs.socket_listener]]
  service_address = "unix:///tmp/telegraf.sock"
  data_format = "wavefront"
```
### System info:

Telegraf 1.9.0

### Steps to reproduce:

1. Start telegraf with above config
2. Send a delta metric via the Unix domain socket. Using the Wavefront CLI:

```
$ wf write point -i -u unix -S /tmp/telegraf.sock example.delta 1
```
### Expected behavior:

Delta metric is forwarded to Wavefront proxy and thence to Wavefront.

### Actual behavior:

Metric is not forwarded to proxy: this message in `telegraf.log`

```2018-12-05T18:09:36Z E! [inputs.socket_listener]: Error in plugin: unable to parse incoming line: invalid metric value ```

**Comment by glinton** [comment]
Can you retry with the metric name in double quotes as [their docs suggest](https://docs.wavefront.com/wavefront_data_format.html)?
`wf write point -i -u unix -S /tmp/telegraf.sock "example.delta" 1`
