### ISSUE TITLE
nvidia-smi plugin to include threads

### ISSUE THREAD

**Issue by DirtyCajunRice** [influxdata/telegraf#5119]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
add a count of threads running in nvidia-smi
### Current behavior:
Not a metric
### Desired behavior:
integer output `{ 'processes': <int> }`
### Use case: [Why is this important (helps with prioritizing requests)]
keeps an eye on consumer grade graphics cards having an encode/decode process cap of 2, as well as a metric for uncapped enterprise grade graphics cards.

nvidia-smi relevant output:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     20469      C   /usr/lib/plexmediaserver/Plex Transcoder     100MiB |
|    0     20779      C   /usr/lib/plexmediaserver/Plex Transcoder      96MiB |
+-----------------------------------------------------------------------------+
```
Im hackily pulling this currently with the xml output that gives all information in an xmltree through python. 

Current code for reference:
```py
import subprocess
import xml.etree.ElementTree as ET

sp = subprocess.Popen(['nvidia-smi', '-q', '-x'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output = sp.communicate()[0]
xmltree = ET.fromstring(output)
processes = xmltree.findall('./gpu/processes/process_info')

metric_to_send = {'processes': len(processes)}
```

**Comment by danielnelson** [comment]
Could you upload the output of `nvidia-smi -q -x`?

**Comment by DirtyCajunRice** [comment]
@danielnelson https://gist.github.com/DirtyCajunRice/3c0be00bd15e2af5c96508339b66e373
relevant line in that is 515-522
```
                <processes>
                        <process_info>
                                <pid>11678</pid>
                                <type>C</type>
                                <process_name>/usr/lib/plexmediaserver/Plex Transcoder</process_name>
                                <used_memory>62 MiB</used_memory>
                        </process_info>
                </processes>
```

**Comment by DirtyCajunRice** [comment]
I believe this is encompassed by https://github.com/influxdata/telegraf/pull/5885/commits/2325c9734d9e51047b98f91745b09618925b0de2 so i will close this out
