### ISSUE TITLE
Option to flush buffer on request

### ISSUE THREAD

**Issue by r0nald** [influxdata/telegraf#5120]
## Feature Request

To have an option to flush telegraf buffer on request. For example, telegraf could (attempt to) flush the buffer on, e.g. USR1 IPC signal.

### Use case:

There are monitoring scenarios where the desirable behavior would be to flush the buffered data based on time or size most of the time, but on rare occasions, on some event, flush it ASAP.

**Comment by glinton** [comment]
By flush, you mean to flush to the endpoint and not drop, correct?

**Comment by r0nald** [comment]
Yes. On request telegraf could try to flush buffered data to the endpoint (e.g. InfluxDB).

**Comment by voiprodrigo** [comment]
This already happens automatically with a graceful shutdown , right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielnelson** [comment]
Yes, during a normal shutdown where the output is able to write, the full metric buffer is written.
