### ISSUE TITLE
Telegraf repository does not have a release file  (Ubuntu 18.10 Cosmic)

### ISSUE THREAD

**Issue by douglasg14b** [influxdata/telegraf#5123]
When trying to install telegraf following the instructions here: https://docs.influxdata.com/telegraf/v1.9/introduction/installation/  the repository cannot be used due to the following error:

```
E: The repository 'https://repos.influxdata.com/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

This prevents the use of the repository to install telegraf.

It seems  there isn't a telegraf install for 18.10. Is there a way to force it?

**Comment by DirtyCajunRice** [comment]
you should be able to just add the bionic repo/release and it work @douglasg14b

**Comment by douglasg14b** [comment]
@DirtyCajunRice 

I'm a fairly new Linux user, so excuse my ignorance. Would you be able to show me the appropriate command(s) to achieve that? I'm sure someone will end up finding this thread on Google as well and it would be super handy.

**Comment by DirtyCajunRice** [comment]
@douglasg14b you just replace cosmic with bionic in your apt sources file

**Comment by danielnelson** [comment]
The upcoming 1.9.2 will add cosmic.
