### ISSUE TITLE
add supervisord program status plugins

### ISSUE THREAD

**Issue by vipsql** [influxdata/telegraf#5126]
## Feature Request

add supervisord program(pid) status plugins

Use case:  get pid status in graph and alert the error

**Comment by glinton** [comment]
Does procstat plugin not meet your needs for this?

**Comment by vipsql** [comment]
@glinton  it can not  relevance to supervisor;

**Comment by danielnelson** [comment]
#2295

**Comment by reimda** [comment]
It looks like #9015 will implement this. It's currently waiting for fixes from code review.

**Comment by sjwang90** [comment]
Closed in #9015
