### ISSUE TITLE
Incorrect disk usage stats

### ISSUE THREAD

**Issue by panda87** [influxdata/telegraf#513]
Today, the disk stats shows only the amount the space on the partitions, this will be great if this will show also the percentage, since I had a case that `df -h` shows 100%, but when I calculated that manually, the result was less than 100% (close to 90%).

So both of the stats are important and relevant.

Thanks
D.

**Comment by TheFlyingCorpse** [comment]
inodes as well perhaps?

**Comment by panda87** [comment]
inodes exists in ubuntu?

**Comment by sparrc** [comment]
@panda87 Are the disk stats incorrect? Why was it off by 10%?

**Comment by sparrc** [comment]
Can you explain the query you're using the calculate it?

when I do 

```
SELECT used/total FROM disk WHERE path='/'
```

I get the correct percentage

**Comment by TheFlyingCorpse** [comment]
@panda87  - yes, unles you are using XFS I think.
to get inodes: $ df -i

Ex from my puppet master test:
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/dm-0      3164112 129123 3034989    5% /
udev            124675    318  124357    1% /dev
tmpfs           126878    485  126393    1% /run
tmpfs           126878      1  126877    1% /dev/shm
tmpfs           126878      8  126870    1% /run/lock
tmpfs           126878     13  126865    1% /sys/fs/cgroup
/dev/sda2        62496    318   62178    1% /boot
/dev/sda1            0      0       0     - /boot/efi
tmpfs           126878      4  126874    1% /run/user/1000

**Comment by TheFlyingCorpse** [comment]
@sparrc, running "SELECT used/total FROM disk WHERE path='/'" on 0.9.6 via the influxdb simple website on :8083, it crashes parts of the influxdb daemon, like tsdb, is this intentional? 

From log:
Jan 16 12:48:50 ryglif11 systemd[1]: influxdb.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 16 12:48:50 ryglif11 systemd[1]: Unit influxdb.service entered failed state.

**Comment by sparrc** [comment]
@TheFlyingCorpse No, that is not intentional, I'm fairly sure that bugfix was the reason we released 0.9.6.1 (see https://github.com/influxdata/influxdb/pull/4984), so I'd suggest upgrading

**Comment by TheFlyingCorpse** [comment]
@sparrc, docs out of date then, it points to 0.9.5.1, meanwhile download page lists 0.9.6.1 and docs on github in raw format points to an actual repository. Ref: https://influxdb.com/docs/v0.9/introduction/installation.html

Sorry for posting about this in this ticket.

**Comment by sparrc** [comment]
looks like our old website isn't redirecting yet, see the new docs site: https://docs.influxdata.com/influxdb/v0.9/ and https://influxdata.com/downloads/

**Comment by sparrc** [comment]
@panda87 I think the real issue here is that your disk stats were incorrect in Telegraf, could you provide any more information on that?

**Comment by jmesserli** [comment]
I have the same Issue, all the disk stats except the "Used" one are correct.

![Imgur](http://i.imgur.com/AMB5RvU.png)

Output of "select used/total from disk where path = '/'":
![Imgur](http://i.imgur.com/aukamI9.png)

A Grafana graph:
![Imgur](http://i.imgur.com/bF3m2WP.png)

I am on Ubuntu 14.04.3 LTS, using InfluxDB 0.9.6.1 and Telegraf version 0.10.0.

Log output in /var/log/telegraf/telegraf.log:
```
2016/01/25 22:34:50 Gathered metrics, (10s interval), from 6 inputs in 13.485577ms
2016/01/25 22:34:50 Flushed 35 metrics to output influxdb in 34.031703ms
2016/01/25 22:35:00 Gathered metrics, (10s interval), from 6 inputs in 32.76878ms
2016/01/25 22:35:00 Flushed 35 metrics to output influxdb in 36.899986ms
2016/01/25 22:35:10 Gathered metrics, (10s interval), from 6 inputs in 20.181217ms
2016/01/25 22:35:10 Flushed 35 metrics to output influxdb in 6.2358ms
2016/01/25 22:35:20 Gathered metrics, (10s interval), from 6 inputs in 17.49836ms
2016/01/25 22:35:20 Flushed 35 metrics to output influxdb in 57.059811ms
```

Are there any other logfiles or informations I could provide?

**Comment by sparrc** [comment]
Interesting, this looks like it might be this problem: http://stackoverflow.com/questions/21693673/differ-in-output-of-df-and-statfs, since we're using gopsutil which makes the statfs call directly.

Thanks for the details @jmesserli, I should be able to get a fix for this going soon

**Comment by sparrc** [comment]
So this is due to a strange behavior of gopsutil (and the python psutil) to use bfree for `used` space, but bavail for `free` space.

@jmesserli Could you try this query and let me know if it's correct?

```
select (total-free)/total from disk where path='/'
```

**Comment by sparrc** [comment]
Actually looks like this could be two different problems.

@jmesserli I believe your stats are off because you are running `df` as root, and telegraf runs under the `telegraf` user. can you try running `sudo -u telegraf df -h /`?

**Comment by jmesserli** [comment]
@sparrc The stats are the same when running the command as user telegraf

```
root@helios:~# sudo -u telegraf df -h /
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/disk/by-uuid/9f8a5461-c328-43bb-8b75-c43182c1433a  960G  179G  733G  20% /
```

**Comment by sparrc** [comment]
Finally tracked this down, it looks like the `df` percentage is actually calculated as:

```
used / (free + used)
```

see here: https://en.wikipedia.org/wiki/Df_(Unix)

@jmesserli note that in your df example, used + free = 912gb, whereas total = 960gb

I'm not sure there is anything I can do about this, other than add a `used_percent` field to the disk plugin

**Comment by panda87** [comment]
Thanks @sparrc !

**Comment by jmesserli** [comment]
@sparrc Awesome! Thank you
