### ISSUE TITLE
telegraf on AIX

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5131]
We know that Telegraf officially doesn’t support AIX platform but we might be able to run by compiling with Gccgo.
Is there any document related to that? Or Can you please share the detail steps how to install?

**Comment by mark-rushakoff** [comment]
AIX support in Go is expected to land in Go 1.12, coming out in February. You can try [building Go from source](https://golang.org/doc/install/source), [or wait for the first Go 1.12 beta](https://groups.google.com/forum/?pli=1#!topic/golang-dev/Bw1KIxV0wHA), so that you can cross-compile telegraf for AIX. 

Once you have an installation of Go that supports AIX, I believe you would just run `GOOS=aix GOARCH=ppc64 go build ./cmd/telegraf` to produce a telegraf binary that can run on AIX.

**Comment by danielnelson** [comment]
Nobody has tried building with `gccgo`, and there isn't any documentation that is Telegraf specific.  

We can try building for AIX once Go 1.12 is released, but of course there may be compilation issues that need sorted out first and there will likely be reduced support for AIX in some plugins.  A simple example is that there won't be an implementation of `cpu` for AIX until one is added to gopsutil.

**Comment by danielnelson** [comment]
I'm going to reopen, since there is still demand for an AIX build.  Here is the current state of compilation with AIX/ppc64, looks like many of the same issues that we have with the Solaris builds.

```
$ GOOS=aix GOARCH=ppc64 make telegraf
go build -ldflags " -X main.commit=62ffd717 -X main.branch=master" ./cmd/telegraf
go build github.com/nats-io/gnatsd/server/pse: build constraints exclude all Go files in /home/dbn/src/influx/pkg/mod/github.com/nats-io/gnatsd@v1.2.0/server/pse
# github.com/influxdata/telegraf/plugins/inputs/system
plugins/inputs/system/ps.go:174:15: undefined: host.SensorsTemperatures
# github.com/docker/docker/client
../../../../pkg/mod/github.com/docker/docker@v1.4.2-0.20180327123150-ed7b6428c133/client/client.go:238:35: undefined: DefaultDockerHost
../../../../pkg/mod/github.com/docker/docker@v1.4.2-0.20180327123150-ed7b6428c133/client/client.go:243:12: undefined: DefaultDockerHost
../../../../pkg/mod/github.com/docker/docker@v1.4.2-0.20180327123150-ed7b6428c133/client/client.go:247:12: undefined: defaultProto
../../../../pkg/mod/github.com/docker/docker@v1.4.2-0.20180327123150-ed7b6428c133/client/client.go:248:12: undefined: defaultAddr
# github.com/influxdata/tail/watch
../../../../pkg/mod/github.com/influxdata/tail@v1.0.1-0.20180327235535-c43482518d41/watch/inotify_tracker.go:20:13: undefined: fsnotify.Watcher
# github.com/goburrow/serial
../../../../pkg/mod/github.com/goburrow/serial@v0.1.0/serial.go:61:6: undefined: New
```

For those who can compile from source, it ought to be possible to remove the offending plugins from the `plugins/inputs/all/all.go` list and successfully compile.

**Comment by raider111111** [comment]
Hi!
I have a customer that has AIX servers and wants to use Telegraf to monitor them.
Any update on this?

Thanks guys!

**Comment by doanerock** [comment]
I would also like to use telegraf on AIX.

**Comment by iatalay** [comment]
In my company, there is a huge demand to use telegraf agents on AIX. We are looking forward to see AIX support. :)

**Comment by sjwang90** [comment]
Telegraf on AIX is still an occasional request but currently a pretty low priority for the internal influx team. One of our big roadblocks is that we don't have internal systems to test the build. If we do decide to building Telegraf for AIX, we could help fix problems but would rely on AIX users to test and debug.

**Comment by raider111111** [comment]
Hi Samantha,

I can understand that, AIX is kind of obscure, and in some cases quite dated.
Feel free to reach out to me about testing this and if I have cycles I could compile and test on a QA box, assuming management doesn’t have a problem with it.

Thanks for getting back to me!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sjwang90** [comment]
Developer tools to test on AIX: https://developer.ibm.com/articles/accelerate-open-source-dev-with-access-to-power/

**Comment by powersj** [comment]
Hi,

While there are some AIX systems available via cloud providers now, this is not something we generally have available to us or our CI system.

I am going to close this issue for now as not planned. However, users are still fully able to cross-build or build Telegraf for AIX systems. If issues are found, we are happy to have issue reports and can work with you to resolve issues potentially.

Thanks
