### ISSUE TITLE
[inputs.sqlserver] database IO query question

### ISSUE THREAD

**Issue by niphlod** [influxdata/telegraf#5134]
### Relevant telegraf.conf:
[[inputs.sqlserver]]
servers = [
"Server=localhost;Port=1433;User Id=####;Password=####&;app name=telegraf;log=1;",
]
query_version = 2
### System info:

Windows, sql server version unrelated

### Steps to reproduce:
Try graphing out I/O from influxdb 

-----

Sorry, this is not a proper "bug" rather than trying to figure out a nice way to pass from query_version = 1 data to query_version = 2.
It's quite clear the reason behind passing to query_version = 2 but ATM I still not see any dashboard on grafana that can clarify the kind of aggregate to use when plotting sqlserver_database_io data.

Given one of the most compellent features of telegraf/influx is also being able to be rigged to a grafana frontend, can someone clarify if 

```
SELECT non_negative_derivative(mean("write_bytes"), 1s) 
FROM "sqlserver_database_io" 
WHERE ("sql_instance" = 'foo' AND "file_type" = 'DATA') 
AND time >= now() - 15m 
GROUP BY time(5s), "database_name" fill(null)
```
is the right way to render the data gathered from the input plugin in question ?

**Comment by m82labs** [comment]
@niphlod you would want to use `last` instead of `mean` in your aggregation. `write_bytes` is ever-increasing, so you always want to be working with the last value for the interval. 

Also, since this data is broken out by file, you would have to group by file as well (and wrap it in a second query if you are looking for per/database stats). So maybe something like this: 

```
SELECT
    non_negative_derivative(sum("read_bytes"),1s) AS "Reads",
    non_negative_derivative(sum("write_bytes"),1s) AS "Writes"
FROM (
    SELECT
        last("read_bytes") AS "read_bytes",
        last("write_bytes") AS "write_bytes"
    FROM
        "sqlserver_database_io"
    WHERE
        ("host" = 'foo' and "file_type" = 'DATA')
        AND $timeFilter
    GROUP BY
        time($__interval),
        "database_name",
        "physical_filename"
)
WHERE
    $timeFilter
GROUP BY
    "database_name",
    time($__interval)
```

I actually haven't done a lot with the IO stats in my environment, so this may take a litte tweaking.

**Comment by niphlod** [comment]
my point is mainly understanding if the math makes sense, post a dashboard on grafana.com and then wait for everybody to chime in with edits/corrections

**Comment by niphlod** [comment]
thanks for watching at this but even with this calculation it seems that data is "spikey" (see image) which doesn't align with what I "know" it's the normal usage

![image](https://user-images.githubusercontent.com/122119/49819473-d5840480-fd75-11e8-9469-6135b2acf7b4.png)

**Comment by m82labs** [comment]
In my environment, with that query, I am getting this (I altered it slightly to just display reads):
![image](https://user-images.githubusercontent.com/8697204/49820995-5a0b5e80-fd47-11e8-8527-7a25b53d42e4.png)

**Comment by danielnelson** [comment]
What about without the outer query, but moving the non_negative_derivative inside?

```
    SELECT
        non_negative_derivative(last("read_bytes"), 1s) AS "read_bytes",
        non_negative_derivative(last("write_bytes"), 1s) AS "write_bytes"
    FROM
        "sqlserver_database_io"
    WHERE
        ("host" = 'foo' and "file_type" = 'DATA')
        AND $timeFilter
    GROUP BY
        time($__interval),
        "database_name",
        "physical_filename"
```

**Comment by niphlod** [comment]
I get a jagged line with any of those, I feel something is wrong with the collection itself.

![image](https://user-images.githubusercontent.com/122119/49858326-e4f66280-fdf4-11e8-8ee4-df2880cd95ba.png)

At this point I wonder if all users are on query_version = 1  ....

**Comment by leepfrog-ger** [comment]
Working fine for me with above query and query_version 2:

![image](https://user-images.githubusercontent.com/10974885/49862180-e4ae9500-fdfd-11e8-956e-f9ecd4f06781.png)

**Comment by niphlod** [comment]
narrow it to maybe 2 hours interval ....

**Comment by abhi-dwivedi** [comment]
hi 

I cant find the sqlserver_database_io measurement in my influx db due to which my dashboard query give me no data
