### ISSUE TITLE
inputs.mqtt_consumer default config can't handle tcp://localhost

### ISSUE THREAD

**Issue by stundenblume** [influxdata/telegraf#5137]
The default config with `servers = ["tcp://localhost:1883"]` does not work, I have to use the IP.

**Comment by danielnelson** [comment]
Can you show an example of what you are using that works?

**Comment by stundenblume** [comment]
`servers = ["tcp://localhost:1883"]`
`servers = ["tcp://localhost:1883"]`

**Comment by stundenblume** [comment]
`servers = ["tcp://localhost:1883"]` does't work
`servers = ["tcp://127.0.0.1:1883"]` does't work
`servers = ["tcp://192.168.100.111:1883"]` works

**Comment by danielnelson** [comment]
I think maybe your mosquitto is not bound to the loopback address, or perhaps there is an issue with your loopback interface.  Can you try these commands:
```
$ sudo lsof -i TCP | grep mosquitto
mosquitto 369 mosquitto    4u  IPv4  11616      0t0  TCP *:1883 (LISTEN)
mosquitto 369 mosquitto    5u  IPv6  11617      0t0  TCP *:1883 (LISTEN)

$ ping localhost -c1
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.150 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.150/0.150/0.150/0.000 ms
```

**Comment by stundenblume** [comment]
`lsof` isn't installed in any of my containers or on the NAS itself.
`ping` isn't installed in any of my containers and is not allowed to use on the NAS.

Other programs can access Mosquitto via "localhost".

**Comment by danielnelson** [comment]
I'm not sure then, you may need to install these or other tools into the container in order to debug the issue.  This finding though tells me that either mosquitto is not bound to the expected interface or the networking is not setup in a way where Telegraf can reach it.
```
servers = ["tcp://127.0.0.1:1883"] does't work
servers = ["tcp://192.168.100.111:1883"] works
```

I don't think this is a Telegraf issue, I can connect to my mosquitto server using the loopback address outside of docker:
```
2018-12-18T20:19:37Z I! [inputs.mqtt_consumer] Connected [tcp://localhost:1883]
```

**Comment by michel-matsumoto** [comment]
@danielnelson 
I'm facing exactly the same issue as @stundenblume :

servers = ["tcp://127.0.0.1:1883"] doesn't work
servers = ["tcp://192.168.100.221:1883"] works

Mosquitto and Telegraf are running in Docker

As you, I don't think that it is a Telegraf issue but maybe related to my settings. But I cannot figure out what !

`pi@pi-home-test:~/docker $ sudo lsof -i TCP

COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
container   501 root   13u  IPv4  11645      0t0  TCP localhost:35953 (LISTEN)
sshd        513 root    3u  IPv4  11635      0t0  TCP *:ssh (LISTEN)
sshd        513 root    4u  IPv6  11637      0t0  TCP *:ssh (LISTEN)
sshd       1611 root    4u  IPv4  15809      0t0  TCP pi-home-test:ssh->michel-HP-EliteBook-840-G3:41478 (ESTABLISHED)
sshd       1767   pi    4u  IPv4  15809      0t0  TCP pi-home-test:ssh->michel-HP-EliteBook-840-G3:41478 (ESTABLISHED)
docker-pr  7815 root    3u  IPv4  42485      0t0  TCP pi-home-test:1883->172.18.0.3:43300 (ESTABLISHED)
docker-pr  7815 root    4u  IPv4  35102      0t0  TCP *:1883 (LISTEN)
docker-pr  7815 root    5u  IPv4  42487      0t0  TCP 172.17.0.1:42536->172.17.0.2:1883 (ESTABLISHED)
docker-pr 10146 root    4u  IPv4  37778      0t0  TCP *:8086 (LISTEN)
docker-pr 10997 root    4u  IPv4  43393      0t0  TCP *:3000 (LISTEN)`

and 

`pi@pi-home-test:~/docker $ ping localhost -c1
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.149 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.149/0.149/0.149/0.000 ms
`
