### ISSUE TITLE
Unable to run make file

### ISSUE THREAD

**Issue by sharanraj124** [influxdata/telegraf#5139]
Am unable to run make successfully using ubuntu machine. Appreciate advise on how to resolve it. Thank you.

Relevant telegraf.conf:
as per master

System info:
go version go1.10.2 ubuntu:16.04/amd64
GOPATH= Home/vagrant/code/go/

Steps to reproduce:
* go get -d github.com/influxdata/telegraf
* cd to Home/vagrant/code/go/src/github.com/influxdata/telegraf
* run make

Expected behavior:
*make successful

Actual behavior:
*Unable to make

Additional info:

vagrant@homestead:~/code/go/src/github.com/influxdata/telegraf$ make
dep ensure -vendor-only
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist
waiting for lockfile /home/vagrant/code/go/pkg/dep/sm.lock: Lockfile created, but doesn't exist

**Comment by danielnelson** [comment]
Maybe out of disk space?  It will be best to ask this type of question at the [InfluxData Community](https://community.influxdata.com) site or to the dep project.  You should be able to run `dep ensure -vendor-only` by hand with no errors.
