### ISSUE TITLE
Option to disable log messages

### ISSUE THREAD

**Issue by exzz** [influxdata/telegraf#514]
My log file is flooded by messages like these:
Jan 13 16:55:30 volta telegraf[3323]: 2016/01/13 16:55:30 Gathered metrics, (10s interval), from 10 inputs in 31.422957ms
Jan 13 16:55:30 volta telegraf[3323]: 2016/01/13 16:55:30 Flushed 58 metrics to output influxdb in 52.51005ms
Jan 13 16:55:40 volta telegraf[3323]: 2016/01/13 16:55:40 Gathered metrics, (10s interval), from 10 inputs in 30.624247ms
Jan 13 16:55:40 volta telegraf[3323]: 2016/01/13 16:55:40 Flushed 58 metrics to output influxdb in 53.596928ms
Jan 13 16:55:50 volta telegraf[3323]: 2016/01/13 16:55:50 Gathered metrics, (10s interval), from 10 inputs in 30.56989ms
Jan 13 16:55:50 volta telegraf[3323]: 2016/01/13 16:55:50 Flushed 58 metrics to output influxdb in 51.561143ms

It will be nice to have an option to disable these messages.

Thanks.

**Comment by sparrc** [comment]
Sounds reasonable, we could make a quiet mode config option

**Comment by dalu** [comment]
Is there a quiet mode option for influxdb?
journal is being spammed with for instance
`May 09 18:05:50 host.com influxd[2196]: [httpd] ::1 - - [09/May/2017:18:05:50 +0200] "POST /write?consistency=any&db=telegraf&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 5ef42975-34d1-11e7-9ec7-000000000000 65401`

**Comment by danielnelson** [comment]
@dalu We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
