### ISSUE TITLE
Allow grok to parse timestamps into metric fields

### ISSUE THREAD

**Issue by KPWhiver** [influxdata/telegraf#5140]
## Feature Request
To allow the grok parser to parse timestamps into metric fields (instead of just the timestamp of the metric itself).

### Desired behavior:
Using a grok pattern such as: %{TIMESTAMP_ISO8601:timestamp:ts-rfc3339}, results in a field called timestamp containing the time as an integer.

### Use case:
For me personally this would be useful to create a timestamp field for the chronograf log viewer. But I can also imagine this being useful when a metric contains multiple timestamps with different meanings.

**Comment by danielnelson** [comment]
This would be a useful feature, but we need a way to distinguish between named field times and times that go into the metric time.  Perhaps a named time could be `%{TIMESTAMP_ISO8601:fieldname_here:ts-rfc3339}` and the metric time could be set with `%{TIMESTAMP_ISO8601::ts-rfc3339}`?  I do think this will cause some confusion between the two formats, maybe there is a better way to extend the syntax?

Since this would be a breaking change, we will need to also add a switch to opt into the new behavior.

**Comment by GeorgeMac** [comment]
Am I right in thinking that this is only a problem for the field with name `timestamp`? As in the `semantic_name` when set to `timestamp` gets used at the metric timestamp. Where other field names here become fields (or tags with the tag modifier) even when the modifier is a `ts` prefix?

Would another option be to prefix all `ts` modifiers to circumvent this scenario? e.g. `field-ts-rfc3339`. This could avoid a breaking change.

**Comment by danielnelson** [comment]
I believe any field with a `ts-` "modifier" becomes the timestamp, regardless of what the "semantic_name" is.  So `%{TIMESTAMP:howdy:ts}` would still be the timestamp.

The `field-ts-rfc3339` idea ought to work.  Another possible way to solve this would be that if you specify a `grok_timestamp` option then it specifies a specific "semantic_name" for the timestamp, and other names would be just regular fields.  If the `grok_timestamp` is not set, you get today's behavior.

I don't care much for my original idea `%{TIMESTAMP_ISO8601::ts-rfc3339}`, it feels like we would need a switch style option to toggle old-behavior/new-behavior, while the newer ideas are additive to the API, there is no legacy behavior created with them.

**Comment by MyaLongmire** [comment]
@KPWhiver, is this still an issue for you?

**Comment by KPWhiver** [comment]
Not really, I have switched to using fluentbit instead of telegraf which allows me to work around this issue.

**Comment by MyaLongmire** [comment]
Thanks for getting back to us. I am going to close this for now but if this issue persists we can we open it
