### ISSUE TITLE
"memory" input plugin returns inaccurate "used" value

### ISSUE THREAD

**Issue by dennisjac** [influxdata/telegraf#5141]
The "memory" input plugin uses an incorrect calculation to determine the "used" value. It ignores the "slab" value which is memory that can also be allocated from (just like the cache) and as a result systems report a much higher "used" value than e.g. the top or free shell commands.
Right now it seems to use `used = total - (free + cached + buffers)` but the correct formula used by other tools is `used = total - (free + cached + buffers + slab)`.

In my case Telegraf reported 5GB of used memory when in reality the system used only 500MB which is a significant discrepancy.

**Comment by danielnelson** [comment]
Can you report this issue to gopsutil so that they can evaluate it?  It would be helpful if you could also link to the code in top or free that does this calculation, if possible.  Here is the calculation in gopsutil:

https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go#L103

**Comment by danielnelson** [comment]
Thanks for the heads up @pytimer, we will update the dependency on the next gopsutil release.
