### ISSUE TITLE
script build error

### ISSUE THREAD

**Issue by sharanraj124** [influxdata/telegraf#5142]
I build telegraf script I got this type of error. how to solve this? 
### Build Cmd
python ./scripts/build.py --package  --platform=linux --arch=arm64

[WARNING] run: Command 'git describe --exact-match --tags 2>/dev/null' failed with error:
[INFO] print_banner:
 _____     _                       __
/__   \___| | ___  __ _ _ __ __ _ / _|
  / /\/ _ \ |/ _ \/ _` | '__/ _` | |_
 / / |  __/ |  __/ (_| | | | (_| |  _|
 \/   \___|_|\___|\__, |_|  \__,_|_|
                  |___/
 Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] go_get: Retrieving dependencies with `dep`...
[INFO] build: Starting build for linux/arm64...
[INFO] build: Using Go version: 1.11.2
[INFO] build: Using git branch: master
[INFO] build: Using git commit: e2ccce9e447dc32215c6e8841b8089b0f2a73fbc
[INFO] build: Sending build output to: /Users/appleapple/go/src/github.com/influxdata/telegraf/build
[INFO] build: Using version 'None' for build.
[INFO] build: Building target: telegraf
[INFO] build: Building target: arm64
[INFO] build: Building target: arm64
[INFO] build: Time taken: 149.175462s
[INFO] package: Using temporary directory: /var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/telegraf-build.Y_nivg
[INFO] package: Creating packages for linux/arm64
[INFO] package_scripts: Copying scripts and configuration to build directory
[ERROR] run: Command 'fpm -f -s dir --log error  --vendor InfluxData  --url https://github.com/influxdata/telegraf  --license MIT  --maintainer support@influxdb.com  --config-files /etc/telegraf/telegraf.conf  --config-files /etc/logrotate.d/telegraf  --after-install scripts/post-install.sh  --before-install scripts/pre-install.sh  --after-remove scripts/post-remove.sh  --before-remove scripts/pre-remove.sh  --description "Plugin-driven server agent for reporting metrics into InfluxDB." --name telegraf -a arm64 -t deb --version 1.10.0~e2ccce9e --iteration 0 -C /var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/telegraf-build.Y_nivg/linux/arm64/telegraf -p /Users/appleapple/go/src/github.com/influxdata/telegraf/build ' failed with error: {:timestamp=>"2018-12-13T18:26:01.595962+0530", :message=>"Process failed: tar failed (exit code 1). Full command was:[\"tar\", \"-C\", \"/var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/package-deb-build-f2c3d7ce7858068aa89d6f7b931e25cf410365c0386a24648faf08db3f3c/control\", \"-zcf\", \"/var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/package-deb-build-f2c3d7ce7858068aa89d6f7b931e25cf410365c0386a24648faf08db3f3c/control.tar.gz\", \"--owner=0\", \"--group=0\", \"--numeric-owner\", \".\"]", :level=>:error}

**Comment by danielnelson** [comment]
Merging with duplicate issue #4586
