### ISSUE TITLE
jolokia2 should allow extract tags from attributes

### ISSUE THREAD

**Issue by seanlook** [influxdata/telegraf#5150]
### Proposal:
Right now only values from `mbean` with wildchar could be extracted to tags, but I have some tags should be extracted from attributes, just like `paths`

For example (hbase):
```
  [[inputs.jolokia2_agent.metric]]
    name = "region_wal"
    mbean = "Hadoop:service=HBase,name=RegionServer,sub=WAL"
    paths = ["SyncTime_max", "SyncTime_mean", "SyncTime_75th_percentile", "SyncTime_95th_percentile", "SyncTime_99th_percentile", "AppendTime_max", "AppendTime_mean", "AppendTime_75th_percentile", "AppendTime_95th_percentile", "AppendTime_99th_percentile"]
```

this is the jmx likes:
```
{
    "name" : "Hadoop:service=HBase,name=RegionServer,sub=WAL",
    "modelerType" : "RegionServer,sub=WAL",
    "tag.Context" : "regionserver",
    "tag.Hostname" : "hbase05",
    "AppendSize_num_ops" : 1461639,
    "AppendSize_min" : 42,
    "AppendSize_max" : 6495872,
    "AppendSize_mean" : 1103.4109893072093,
    "AppendSize_median" : 471.0,
    "AppendSize_75th_percentile" : 1005.0,
    "AppendSize_95th_percentile" : 2398.249999999999,
    "AppendSize_99th_percentile" : 14306.029999999806,
    "SyncTime_num_ops" : 810483,
    "SyncTime_min" : 0,
    "SyncTime_max" : 167,
    "SyncTime_mean" : 2.0137880745185277,
    "SyncTime_median" : 1.0,
    "SyncTime_75th_percentile" : 2.0,
    "SyncTime_95th_percentile" : 3.0,
    "SyncTime_99th_percentile" : 6.529999999999973
```

I want to tag `modelerType`, `tag.Hostname` as influxdb tags rather than fields. 

I'm not running telegraf agent for every host, so this hostname is important to me. Especially in hbase `Hadoop:service=HBase,name=RegionServer,sub=Server`, the `tag.clusterId` is the only information to identify my clusters. ([jmxtrans](https://github.com/jmxtrans/jmxtrans/wiki/InfluxDBWriter) has this feature with `resultTags`)

As issue #3845 mentioned, `inputs.jolokia2_agent.tags` does not fit my situation.

So offering an option like `tag_paths` seems good:
```
  [[inputs.jolokia2_agent.metric]]
    name = "region_wal"
    mbean = "Hadoop:service=HBase,name=RegionServer,sub=WAL"
    paths = ["SyncTime_max", "SyncTime_mean", 
    tag_paths = ["tag.Hostname", "modelerType"]
```

**Comment by danielnelson** [comment]
Can you use the `converter` processor to covert the fields to tags?

**Comment by seanlook** [comment]
Okay, this `converter` shall work for me. Thanks!

If I can set the tags in jolokia2, it will be more understandfull and no conflict with other metric tags(maybe has)
