### ISSUE TITLE
Not possible to specify new performance counter in a non english windows vista or younger

### ISSUE THREAD

**Issue by elbosso** [influxdata/telegraf#5156]
I try to use telegraf on a german Windows 10 Pro 64Bit

it works with the supplied config

i tried to add a few measurements but i quickly ran into basically issue 1730

I then did try all proposed steps from issue 1730 - but to no avail

So basically, version 1.9.1 of telegraf is back to the old problems: people without an english version of windows are unable to add new sensors because they do not know and have no means to ascertain the english names of the wanted performance counters.

**Comment by elbosso** [comment]
Maybe this posting might help (im blessed with absolutely no knowledge of go whatsoever - i even was unable to compile it in an ordinary way - lest to get a windows version out of it so I can not actively dabble). 

https://wojciechkulik.pl/csharp/get-a-performancecounter-using-english-name

(I always saw go as an aberration and a fad that is sure to go away if left alone for long enough so i had no chance or motivation to learn it yet. Maybe telegraf will be the reason for changing my views in this regard)

**Comment by elbosso** [comment]
Telegraf not being the only one solution getting bitten in the "§$§&/&§ by Windows - this is another - rather crude - way to go (I did not try it yet as something that desparate should really be ones last resort!!)
https://www.zabbix.com/forum/zabbix-cookbook/7524-how-to-force-perfmon-counters-description-to-be-in-english

**Comment by elbosso** [comment]
And another (powershell-y) way to help the poor devils with a non-english windows and a hankering for more performance indicators:
https://www.powershellmagazine.com/2013/07/19/querying-performance-counters-from-powershell/

**Comment by danielnelson** [comment]
Thanks for the links, I assume you have tried with `PreVistaSupport = true`?  Could you also add a example config snippet with the performance counter name you would like to use?

**Comment by elbosso** [comment]
Sorry for the delay  -  away for work.
Now - to business:
I had only one input configured:

[[inputs.win_perf_counters.object]]
ObjectName= "Arbeitsspeicher"
Counter = ["Verfügbare Bytes"]
Instances = ["------"]
Measurement = "win_mem"

In Powershell - this commando (german Windows 10 Pro 64 Bit ) gave:

Get-Counter "\Arbeitsspeicher\Verfügbare Bytes"

Timestamp                 CounterSamples
---------                 --------------
19.12.2018 19:03:17       \\luna\arbeitsspeicher\verfügbare bytes :
                          5542547456

So i expected to have the correct path  as seen in the input section above - however testing this i got nothing (again Powershell)

C:\"Program Files"\Telegraf\telegraf.exe -config C:\"Program Files"\Telegraf\telegraf.conf -test

2018-12-19T18:04:17Z I! Starting Telegraf 1.9.1

And that was it - no measurement recorded.

This was with both PreVistaSupport=true and PreVistaSupport=false

I hope that this information helps.

Regards, Juergen

**Comment by vlastahajek** [comment]
This a regression bug. Unfortunately, there is no workaround available.

**Comment by srebhan** [comment]
@vlastahajek and @elbosso does that issue still exist with  the latest version of Telegraf?
