### ISSUE TITLE
Syslog plugin not working

### ISSUE THREAD

**Issue by disha1104** [influxdata/telegraf#5172]
### Relevant telegraf.conf:

```
[[inputs.syslog]]
# ##Specify an ip or hostname with port - eg., tcp://localhost:6514, tcp://10.0.0.1:6514
# ##Protocol, address and port to host the syslog receiver.
# ##If no host is specified, then localhost is used.
# ##If no port is specified, 6514 is used (RFC5425#section-4.1).
   server = "tcp://localhost:6514"
```

### System info:
telegraf: 1.9.1
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
Install the latest Telegraf build

Followed the documentation

Restart Telegraf after editing the config and wait for the data, tail the telegraf logs
### Expected behavior:
https://www.influxdata.com/blog/get-your-syslog-on/
Influx should show "syslog" as the new measurement

### Actual behavior:

Nothing is getting updated in influx and no logs in chronograf
### Additional info:

I tried removing one of the plugin, but still influx was showing measurement for that. Am I missing something in the configuration.
Also, wanted to understand the communication between telegraf and influx.
[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
You will need to setup syslog delivery to Telegraf too, the most common way to do this is using [rsyslog](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog#rsyslog-integration), but I suggest [sending a message directly](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog#troubleshooting) first to verify the Telegraf plugin is setup correctly.

If you have further questions it would be best to ask over at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by disha1104** [comment]
I followed this documentation, but I am really not sure how to setup syslog delivery on K8s platform.
I am using the TICK stack with Kubernetes architecture. Is there any documentation around that?
