### ISSUE TITLE
inputs.disk gives inconsistent device name for partitions vs full disks

### ISSUE THREAD

**Issue by moloney** [influxdata/telegraf#5175]
### Relevant telegraf.conf:

Enable inputs.disk with defaults

### System info:

OS is Ubuntu 16.04, telegraf version 1.9.1

### Steps to reproduce:

On a system with both a mounted partition and a mounted full device:

$ telegraf --input-filter disk --test
2018-12-20T21:02:40Z I! Starting Telegraf 1.9.1
2018-12-20T21:02:40Z I! Using config file: /etc/telegraf/telegraf.conf
> disk,device=disk/by-path/virtio-pci-0000:00:07.0-part1,fstype=ext4,host=myserver,mode=rw,path=/ free=2443743232i,inodes_free=267712i,inodes_total=524288i,inodes_used=256576i,total=8318803968i,used=5428891648i,used_percent=68.95901728901214 1545339761000000000
> disk,device=vdb,fstype=ext4,host=myserver,mode=rw,path=/influx free=301852086272i,inodes_free=52428177i,inodes_total=52428800i,inodes_used=623i,total=845381279744i,used=500562743296i,used_percent=62.38204041735999 1545339761000000000

### Expected behavior:

The device tags are consistent. Preferrably "vda1" and "vdb" as the device, and maybe add a 'device_path' tag with the "disk/by-path" versions.

### Actual behavior:

Device names are "disk/by-path/virtio-pci-0000:00:07.0-part1" for the partition and "vdb" for the full device.

**Comment by moloney** [comment]
I just spent some time investigating. The device names do indeed match what is in `/proc/self/mounts`.

Whether or not there is a partition doens't actually make a difference, it just seems to be the root disk that shows up as `disk/by-path/...`.  Changing the way the devices are listed in fstab doesn't make any difference.

**Comment by moloney** [comment]
The "diskio" plugin always reports the short name ([sv]da, [sv]db, etc.) 

The lack of a "path" tag on the "diskio" measurements is actually what pushed me towards using the "device" tag on these "disk" measurements.  Having a "path" tag on "diskio" would actually be preferable for my situation. Should I open a separate issue?

**Comment by moloney** [comment]
Yes, looks like the root partition is different due to it being used during boot:

    $ cat /proc/cmdline 
    BOOT_IMAGE=/boot/vmlinuz-4.4.0-140-generic root=/dev/disk/by-path/virtio-pci-0000:00:07.0-part1 ro

The udevadm command does output the correct short name:

    $ udevadm info -q property -n /dev/vda | grep DEVNAME
    DEVNAME=/dev/vda

However, I am now recalling that these short device names aren't always reliably the same after a reboot (especially on our VMs).  We actually use the `disk/by-path/...` paths in our fstab files for this reason. 

So adding a "path" tag to diskio is still somewhat preferable for my situation, and/or providing both device names (short and by-path) as tags for both "disk" and "diskio" plugins.

**Comment by danielnelson** [comment]
If you add `device_tags = ["ID_PATH"]` to the diskio plugin, you should get something like:
```
> diskio,ID_PATH=pci-0000:00:05.0,host=debian-stretch-docker,name=vda io_time=4160i,iops_in_progress=0i,read_bytes=305312768i,read_time=10820i,reads=11737i,weighted_io_time=13436i,write_bytes=45215744i,write_time=2620i,writes=2918i 1545358719000000000
> diskio,ID_PATH=pci-0000:00:05.0,host=debian-stretch-docker,name=vda1 io_time=4128i,iops_in_progress=0i,read_bytes=304251904i,read_time=10816i,reads=11710i,weighted_io_time=13384i,write_bytes=45215744i,write_time=2572i,writes=2893i 1545358719000000000
> diskio,ID_PATH=pci-0000:00:07.0,host=debian-stretch-docker,name=vdb io_time=20i,iops_in_progress=0i,read_bytes=198144i,read_time=16i,reads=104i,weighted_io_time=20i,write_bytes=1024i,write_time=4i,writes=1i 1545358719000000000
> diskio,ID_PATH=pci-0000:00:07.0,host=debian-stretch-docker,name=vdb1 io_time=12i,iops_in_progress=0i,read_bytes=78848i,read_time=8i,reads=23i,weighted_io_time=12i,write_bytes=1024i,write_time=4i,writes=1i 1545358719000000000
```

**Comment by danielnelson** [comment]
Closing, but let me know if my last comment didn't work for you.
