### ISSUE TITLE
docs: Describe syntax for collection interval

### ISSUE THREAD

**Issue by woodsb02** [influxdata/telegraf#5185]
The telegraf docs mention the configuration setting "collection interval" in numerous places, but do not currently describe the appropriate syntax / values that can be used.

The places where this would be helpful:
- [concepts/glossary/#collection-interval](https://docs.influxdata.com/telegraf/latest/concepts/glossary/#collection-interval)
- [administration/configuration/#agent-configuration](https://docs.influxdata.com/telegraf/latest/administration/configuration/#agent-configuration)

The answer is that the syntax for collection interval is those values accepted by the golang function time.ParseDuration() described here: https://golang.org/pkg/time/#ParseDuration
> Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

One common mistake made by users (or at least myself) is trying to use days as the collection interval:
```
[agent]
  interval = "1d"
```

**Comment by glinton** [comment]
Thanks for pointing this out. Out of curiosity, what is it you are monitoring at daily intervals? Also, feel free to open a PR with those additions, we love contributions like that.

**Comment by woodsb02** [comment]
I am monitoring SSL certificate days until expiry - obviously this only needs to be monitored daily.

**Comment by danielnelson** [comment]
I documented the [interval][] format and linked to it in the [agent][] section, docs.influxdata.com should be based on this for the next release.

[interval]: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#intervals
[agent]: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent

**Comment by woodsb02** [comment]
Nice work - thank you!
