### ISSUE TITLE
Use snake_case in metrics from win_perf_counters

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#5196]
### Proposal:

Update the win_perf_counters plugin to output metrics in snake_case as is the style in the rest of Telegraf.

### Current behavior:

```
win_disk,instance=C:,objectname=LogicalDisk Avg._Disk_sec/Read=0,Avg._Disk_sec/Transfer=0.0017691525863483548 1545384198000000000
```

### Desired behavior:

```
win_disk,instance=C:,object_name=logical_disk avg_disk_sec_read=0,avg_disk_sec_transfer=0.0017691525863483548 1545384198000000000
```

**Comment by Erikov-K** [comment]
When i analyzed my instance objects during measuring "SMB Client Shares" and "SMB Server Shares" metrics, 
I viewed that they come to me in different text case styles:
Example:

> "\SERVERNAME.DOMAINNAME\SHARENAME"
> "\SERVERNAME.DOMAINNAME\ShareName"
> "\SERVERNAME.DomainName\SHARENAME"
> "\SERVERNAME.DomainName\ShareName"
> "\ServerName.DomainName\SHARENAME"
> "\SERVERNAME.DomainName\ShareName"
> 

and etc...

First, I normalized text of instance objects using

> [[processors.strings]]
>     namepass = ["smb_client_shares"]
>     
>     [[processors.strings.lowercase]]
>     tag = "instance"
> 

Telegraf (by default) replace . (dots) in FQDN on _ (bottom dash).

Also I wrote rename rules for each of perfcounters.
I needed it later to filter using keywords in grafana variables.
Example for Latency:

> [[processors.rename]]
>   namepass = ["smb_client_shares"]
>   
>   [[processors.rename.replace]]
>     field = "Avg._sec/Write"
>     dest = "Avg_sec_per_Write"
> 
>   [[processors.rename.replace]]
>     field = "Avg._sec/Read"
>     dest = "Avg_sec_per_Read"
> 
>   [[processors.rename.replace]]
>       field = "Avg._sec/Data_Request"
>       dest = "Avg_sec_per_Data_Request"
> 
> 

In my opinion, using snake_case everywhere not a good idea. :-)
But I also think having optional key for this feature in configuration file will one of the solution for this.

**Comment by powersj** [comment]
There appears to be some previous changing of keys in the windows perf counters plugin. Based on the lack of additional comments and the above comment I am going to close this for now.
