### ISSUE TITLE
Write a data exception to the graphite to cause a breakpoint

### ISSUE THREAD

**Issue by kolapapa** [influxdata/telegraf#5197]
### Relevant telegraf.conf:
```shell
[[outputs.graphite]]
 servers = ["graphite.com:2013"]
 prefix = "h."
 template = "host.measurement.tags.field"

 graphite_tag_support = false
 timeout = 2

```

### System info:

Telegraf unknown (git: master 8d0ec993)
Linux  3.10.0-862.11.6.el7.x86_64

### Actual behavior:
```log
2018-12-27T12:27:04Z I! Starting Telegraf
2018-12-27T12:27:04Z I! Loaded inputs: inputs.mem inputs.swap inputs.system inputs.nstat inputs.ping inputs.cpu inputs.disk inputs.diskio inputs.net inputs.netstat inputs.kernel inputs.processes inputs.internal
2018-12-27T12:27:04Z I! Loaded aggregators:
2018-12-27T12:27:04Z I! Loaded processors:
2018-12-27T12:27:04Z I! Loaded outputs: kafka graphite
2018-12-27T12:27:04Z I! Tags enabled: host=logstash3.logsystem.ops.bj1
2018-12-27T12:27:04Z I! Agent Config: Interval:1m0s, Quiet:false, Hostname:"logstash3.logsystem.ops.bj1", Flush Interval:1m0s
2018-12-27T12:29:00Z E! conn &{{%!s(*net.netFD=&{{{0 0 0} 6 {139696674757984} <nil> 0 0 true true false} 2 1 true tcp 0xc0003a40c0 0xc0003a40f0})}} checkEOF .conn.Read returned err != EOF, which is unexpected.  closing conn. error: read tcp 10.10.22.12:42328->10.253.40.108:2013: read: connection reset by peer
2018-12-27T12:29:00Z E! Graphite Error: write tcp 10.10.22.12:42328->10.253.40.108:2013: use of closed network connection
2018-12-27T12:29:00Z E! Graphite: Reconnecting and retrying:
```

This situation is sporadic, but it must happen by chance.

**Comment by glinton** [comment]
Are there any logs on your graphite server? It seems there may have been a network partition or perhaps the server restarted/closed the connection for another reason.

That first error log line (`E! conn...`) tells us the server closed the connection: 
`read: connection reset by peer`

**Comment by danielnelson** [comment]
Is the output plugin able to reconnect and continue sending metrics after this occurs?  If so, we might just want to clean up this logging output.

related: https://github.com/influxdata/telegraf/pull/3861

**Comment by kolapapa** [comment]
Our receiver is a graphite cluster with LVS for load balancing.We recently tracked this issue at tcpdump. There is a very interesting phenomenon. Some indicators will have breakpoints, but some indicators are good.


This picture is a chart of the last hour of the indicator.
`derivative(h.shop2_dev_ops_bj1.internal_agent.metrics_written)`
`h.shop2_dev_ops_bj1.cpu.cpu-total.usage_idle`
`h.shop2_dev_ops_bj1.swap.used_percent`
![image](https://user-images.githubusercontent.com/17918689/50582866-993d5300-0ea0-11e9-9e99-5e3a5af067d3.png)

**Comment by danielnelson** [comment]
On the second issue, it looks like the 12:30 data was rounded to a second earlier, Telegraf creates metrics with the timestamp of the actual collection which can vary from the scheduled times due to system load.

I do notice that in the Graphite output we are truncating the timestamp to seconds, we probably ought to round them to the closest second instead.

Can you show the [agent] section of your configuration?

**Comment by kolapapa** [comment]
```conf
# Configuration for telegraf agent
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = "test1.dev.ops.bj1"
  omit_hostname = false
```

**Comment by kolapapa** [comment]
Yesterday we had a problem, which caused the time stamp of telegraf reporting data to be more than 2 hours late.

![image](https://user-images.githubusercontent.com/17918689/50672165-73838b80-1011-11e9-93d2-2603561f9f53.png)

The right-most output is the current time, and the timestamp inside is the indicated time.


![image](https://user-images.githubusercontent.com/17918689/50672293-2bb13400-1012-11e9-9d1a-0fc65c9ae748.png)
（It's not a machine, it's a batch of machines.）

It looks like telegraf's clock is in a mess.Telegraf's log has nothing to do with it.
Yesterday's failure was about lvs, graphite load balancing.

**Comment by danielnelson** [comment]
This looks like it might be #5194

**Comment by danielnelson** [comment]
@kolapapa Can you retest this issue with 1.10.0?

**Comment by kolapapa** [comment]
@danielnelson ok, I'll let you know the result in a few days.

**Comment by danielnelson** [comment]
Closing, let me know if you are still having problems.
