### ISSUE TITLE
Feature request: Pivot aggregator

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#5203]
## Feature Request
Add a pivot aggregator for creating aggregated metrics based on a pivot field.

Opening a feature request kicks off a discussion.

### Proposal:
Assume you have a stream of metrics for hosts. Each host is part of a cluster, which is associated with the tag ```cluster```.  Furthermore, assume each host has a ```cpuload``` metric. I would like to synthesize a metrics for the ```cpuload``` per cluster with a max, min, average, etc. aggregation.

Contrary to other aggregators, this one would preserve timestamps, but average based on a pivot element, rather than a time period.

We are planning on writing this plugin, but wanted to file an issue for tracking and commenting purposes.

#### Example
Input:
```
host=foo cluster=prod load=1 1475583980000000000
host=bar cluster=prod load=1 1475583980000000000
host=monkey cluster=dev load=1 1475583980000000000
host=giraffe cluster=dev load=3 1475583980000000000
```

Output:
```
cluster=prod load_avg=1 1475583980000000000
cluster=dev load_avg=2 1475583980000000000
```

Notice that the plugin would have more aggregations than average, but these are omitted for brevity.

### Current behavior:
No pivot aggregator exists

### Desired behavior:
A pivot aggregator exists

### Use case: [Why is this important (helps with prioritizing requests)]
There are countless use cases for this. The one that's the most pressing for us right now is the ability to synthesize vSphere cluster metrics from hosts. But since pivoting is a very common statistics operator, I'm confident this plugin would find many other uses.

**Comment by prydin** [comment]
Thinking a little more about it, I'm not sure you always want to preserve the timestamps. Maybe we should make that an option. If you don't preserve the timestamp, the resulting value should be an average (or other operation) across all elements AND timestamps that share the same pivot element value.

We also need some missing value management. You would probably want an option to handle missing values by repeating the latest known value for a couple of cycles. That saves you from having skewed numbers because of occasional dropped samples.

**Comment by danielnelson** [comment]
Would this be similar to doing a tagexclude, using host in the above example, with the basicstats aggregator?  BTW, might be best to test with 1.8 until #5209 is fixed.

**Comment by prydin** [comment]
There was some extra functionality, such as metric name substitution etc. we needed, but the immediate need for this aggregator sort of went away, so I'm closing this for now.

**Comment by danielnelson** [comment]
It seems to me that `group_tags` would work the same as `taginclude`, I might be missing something so here is an example:

```toml
[[aggregators.basicstats]]
  period = "10s"
  drop_original = false
  stats = ["sum"]
  namepass = "foo"
  taginclude = ["workload", "system"]
```

```
# 2 lines of input
foo,host=alice,system=b,workload=y value=42 1548283697864704757
foo,host=bob,system=b,workload=y value=42 1548283698947241533
# output by aggregator
foo,system=b,workload=y value_sum=84 1548283706000000000
```

Even if this is the same, we should at least document this technique because it isn't very obvious.

**Comment by puckpuck** [comment]
Played with this some more, and it turns out that `taginclude` does produce what you are looking for.  

One side effect, though I'm not sure this is intentional is that I also happen to get a single metric from the aggregator which is an aggregation of all metrics that did not include the tags in my `taginclude` list.  This would be in a slight contradiction to what is stated in docs/AGGREGATORS_AND_PROCESSORS.md which mentions: 

```Use measurement filtering to control which metrics are passed through a processor or aggregator. If a metric is filtered out the metric bypasses the plugin and is passed downstream to the next plugin.```

In this case taginclude would mean those that don't have that tag shouldn't get included, and thus not even output by the aggregator.  One could even argue that if I have `drop_original = true`, it shouldn't be dropped either since the metric never qualified for the aggregator.

I'm happy to take a stab at cleaning up the doc mentioned above to showcase how taginclude can be leveraged to create dynamic groups with aggregator plugins.

**Comment by danielnelson** [comment]
Closing with the new documentation, also I have something different that we might want to use the pivot name for: #5629.
