### ISSUE TITLE
NSQLookupd support for nsq_consumer is broken in 1.9.0/1.9.1

### ISSUE THREAD

**Issue by ljagiello** [influxdata/telegraf#5208]
### Relevant telegraf.conf:
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "10s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

# Read NSQ topic for metrics.
[[inputs.nsq_consumer]]
  ## An string representing the NSQD TCP/NSQLookupd HTTP Endpoints
  nsqlookupd = ["nsqlookupd1.ops:4161","nsqlookupd2.ops:4161"]
  topic = "telegraf-dev"
  channel = "consumer"
  max_in_flight = 100

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
```

### System info:
Official docker image 1.9.0 / 1.9.1

### Steps to reproduce:

1. Run nsq_consumer with nsqlookupd (and multiple nsqd behind)
2. Telegraf will connect only to a single nsqd

### Expected behavior:
Telegraf should fetch messages from all nsqd behind nsqlookupd.

### Actual behavior:
Telegraf connects only to a single nsqd.

### Additional info:
The only change between working version and broken is: https://github.com/influxdata/telegraf/pull/4938

**Comment by ssoroka** [comment]
You don't happen to have a docker-compose environment I could test against, do you?

**Comment by sjwang90** [comment]
@ljagiello can you respond to the above comment or provide any updates to this issue? thanks!

**Comment by ljagiello** [comment]
Hi @sjwang90, I don't use telegraf anymore and I'm not sure how complicated would be to replicate this bug with docker-compose, but I can provide an update in few days.

**Comment by ljagiello** [comment]
@ssoroka @sjwang90 I've tried to replicate environment based on what I remember with docker composer but I was unable to generate the same issue. Because I don't use telegraf, I don't have access to that environment and I'm unable to replicate this issue I will close this ticket.

Thank you so much for checking here.
