### ISSUE TITLE
exec plugin ignores string values

### ISSUE THREAD

**Issue by kostasb** [influxdata/telegraf#521]
Telegraf - Version 0.10.0

Example json output from custom script which run as command in [[inputs.exec]]
```json
{
    "myint": 1,
    "myfloat": 1.5,
    "mystring": "test"
}
```
Telegraf only stores the int and float values in fields, ignoring the string value.

The result looks like:
```code
exec_myjson myfloat=1.5,myint=1 1452816051671736921
```

---

**Comment by ekini** [comment]
Well, according to documentation https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec, it's intended.

 >  *Exec Plugin*
 >   The exec plugin can execute arbitrary commands which output JSON. Then it flattens JSON and finds     all numeric values, treating them as floats.

**Comment by anlutro** [comment]
This applies to booleans as well. I'd really appreciate it if this triggered a warning or error in the log files, just for clarity's sake when debugging and learning by trial and error.

**Comment by sparrc** [comment]
But for users who are parsing large JSON blobs, logging every single string and/or boolean that is supposed to be ignored would be overkill. I think we can just put some documentation in the config file about this.

**Comment by sparrc** [comment]
I'm going to close this as "won't fix", I'll push a change to include a note about this in the httpjson and exec plugins
