### ISSUE TITLE
telegraf to monitor mssql database

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5222]
I have created telegraf user on master on the DB server:

USE master;
GO
CREATE LOGIN telegraf WITH PASSWORD = N'StrongPassword';
GO
GRANT VIEW SERVER STATE TO telegraf;
GO
GRANT VIEW ANY DEFINITION TO telegraf;
GO

and added below in telegraf.conf file:

[[inputs.sqlserver]]
 servers = [
   "Server="xx.xx.xx.xx";Port=1433;UserId=telegraf;Password='StrongPassword@123';app name=telegraf;log=1;"
   ]

sqlserver is listening on default port 1433, let me know what I am missing, as this configuration not working to report database detail.

**Comment by danielnelson** [comment]
Can you add information about the version of SQL Server you are connecting to, as well as any logs produced by Telegraf when connecting or any additional information about what happens when you run Telegraf.
