### ISSUE TITLE
JSON parsing on different levels with telemetry as nested JSON

### ISSUE THREAD

**Issue by GertjanvanhetHof** [influxdata/telegraf#5228]
## Feature Request
It is not possible to use fields in a JSON message which are on different levels when the telemetry is on the deepest level as a array (nested JSON).
The tags and some fields should come from the highest JSON level and the telemetry data (fields which are strings and floats) itself should come from the nested JSON.

A sample message:
```
{
	"app_id": "my-app-id", // Same as in the topic
	"dev_id": "my-dev-id", // Same as in the topic
	"payload_fields": { {
			"sensorType": "temperature",
			"value": 21.3
		}, {
			"sensorType": "humidity",
			"value": 30
		}, {
			"sensorType": "light",
			"value": 107
		}, {
			"sensorType": "motion",
			"value": 3
		}, {
			"sensorType": "vdd",
			"value": 3516
		}
	}, // Object containing the results from the payload functions
	"metadata": {
		"time": "1970-01-01T00:00:00Z", // Time when the server received the message
		"gateways": [{
				"gtw_id": "mygateway", // EUI of the gateway
				"time": "1970-01-01T00:00:00Z", // Time when the gateway received the message - left out when gateway does not have synchronized time
			},
			//...more if received by more gateways...
		],
		"latitude": 52.2345, // Latitude of the device
		"longitude": 6.2345, // Longitude of the device
		"altitude": 2 // Altitude of the device
	}
}
```

The tags should be: app_id and dev_id
The measurement doesn't matter but must be set to a custom value (telemetry for instance).
Timestamp of the message should come from metadata.time.

Opening a feature request kicks off a discussion.

### Proposal:
The way how JSON messages are processed should be adapted so all JSON elements including the nested are made flatten.

### Current behavior:
This is not possible at all.

### Desired behavior:
```
telemetry,app_id=<my_id>,dev_id=<my_id> payload_fields_0_sensorType='temperature',payload_fields_0_value=21.3,...<left empty to save space>...,payload_fields_4_sensorType='vdd',payload_fields_4_value=3516,metadata_gateway_0_gateways_gtw_id='mygateway', ....<left empty>...,metadata.altitude=2 259200000
```

### Use case: [Why is this important (helps with prioritizing requests)]

This use case is for receiving sensor data from The Things Network (TTN). The data is forwarded by a HTTP Integration of TTN to Telegraf which http_listener_v2 plugin configured. From there the data is send to influxdb.

**Comment by GertjanvanhetHof** [comment]
I found a solution. It is possible to do this as following:

```
  data_format = "json"
  tag_keys = ["dev_id","app_id"]
  json_string_fields = ["payload_fields_sensorData_0_sensorType",
                        "payload_fields_sensorData_1_sensorType",
                        "payload_fields_sensorData_2_sensorType",
                        "payload_fields_sensorData_3_sensorType",
                        "payload_fields_sensorData_4_sensorType"]
```

**Comment by danielnelson** [comment]
Let's merge this with #4912, this would allow you to specify this list of fields as a glob.  Another issue you may want to take a look over is #1363.
