### ISSUE TITLE
A time decay model to sampling statsd input?

### ISSUE THREAD

**Issue by j2gg0s** [influxdata/telegraf#5230]
### Proposal:
I want to add a time exponentially decay model, as an option, to sampling statsd input. 
As a newcomer, I am not sure if this is needed.

### Current behavior:
With default config, RunningStats will only keep 1000 timer values in one cycle(10s). This is too small and we lost too much early data.

### Desired behavior:
A time decay model, maybe like [this](https://github.com/dropwizard/metrics/blob/5.0-development/metrics-core/src/main/java/io/dropwizard/metrics5/ExponentiallyDecayingReservoir.java).

**Comment by danielnelson** [comment]
It might make sense for this to be created as a standalone Aggregator, since the statsd input is primarily meant to match existing statsd server implementations.  This would also be more flexible as it could be used by any input.

In order to use this over the statsd protocol without the built in aggregation we would need to move the statsd parser out into its own data_format, then it could be used with the socket_listener plugin.

One concern I would have with my idea is performance, as doing the aggregation in the statsd input directly reduces the amount of work Telegraf needs to perform.

**Comment by j2gg0s** [comment]
socket_listener support statsd protocol is a better choice, i agree that.
Is someone working for that?

About aggregation performance.
First, new aggregation will be optional.
And compare to statsd's `RunningStats`, forward exponentially decay model only need following extra work:
- calculate weight base on time when add metric, and a list to save
- sum weight when get percentile

**Comment by danielnelson** [comment]
> socket_listener support statsd protocol is a better choice, i agree that.
Is someone working for that?

No, if you want to give it a shot the logfmt parser is a good example to start with.

Performance wise, I imagine your aggregator itself would be pretty quick. The big difference would be that socket_listener w/statsd would need to create a telegraf.Metric for every statsd metric, compared with the statsd input with built in aggregation only needs to create one telegraf.Metric per aggregate.  Still, I feel it is probably worth doing as an aggregator as it will be much more flexible.

**Comment by j2gg0s** [comment]
> No, if you want to give it a shot the logfmt parser is a good example to start with.

@danielnelson need some help.
I'm trying to split `inputs.statsd` into one parser + one aggregator (like `inputs.statsd.aggregator`).
Method `ParseLine` of parser should return one metric, but statsd allow merge individual stats into a single line, like this `load.time:320|ms:200|ms`.
This parser's `ParseLine` may always return error?

**Comment by danielnelson** [comment]
I've been planning to remove this method from the Parser interface completely, but for now you can do what other plugins do and return only the first metric.  The code from the influx parser should work here too:

https://github.com/influxdata/telegraf/blob/361baaa4bbc7e854561815a89c8db5c451839e33/plugins/parsers/influx/parser.go#L86-L97

This method is still in use by the `tail` and `logparser` input, but all other plugins use `Parse`.
