### ISSUE TITLE
CloudWatch metrics filtering

### ISSUE THREAD

**Issue by denispesikov** [influxdata/telegraf#5233]
Hello guys!
Im trying to fetch RDS metrics from CW and put it to the InfluxDB using telegraf
here is my example config:
[[inputs.cloudwatch]]
  access_key = "mykey"
  secret_key = "myskey"
  period = "5m"
  delay = "1m"
  ratelimit = 50
  region = "eu-central-1"
  namespace = "AWS/RDS"
  [[inputs.cloudwatch.metrics]]
   names = ["DatabaseConnections"]
As you can see I want to fetch only 1 metric called `DatabaseConnections` , and I able to do so.
I got the metrics , but the issue that I have 2 RDS instances and I able to query only the total value of both DBs , when I trying to query the db with WHERE clause (select database_connections_sum from cloudwatch_aws_rds where db_instance_identifier = 'mydb' I got nothing.
Can you please point me what should I change in my config?

Thank you

**Comment by denispesikov** [comment]
Ok , 1 more update , I dropped the MEASUREMENT cloudwatch_aws_rds and restarted the telegraf.
I just not getting the db_instance_identifier field any more ,only host , region and unit

**Comment by danielnelson** [comment]
Can you run `telegraf --input-filter cloudwatch --test` and paste the output?

**Comment by denispesikov** [comment]
Hello Daniel, sure thing I attaching the output

> Can you run `telegraf --input-filter cloudwatch --test` and paste the output?

> > cloudwatch_aws_rds,host=telegraf-cw-dev,region=eu-central-1,source=telegraf,unit=count database_connections_average=126,database_connections_maximum=182,database_connections_minimum=70,database_connections_sample_count=10,database_connections_sum=1260 1546849500000000000

As I said , I have 2 RDS DBS and I'm not getting separate metrics per DB , but kinda accumulated metrics for both of them

Thank you!

**Comment by denispesikov** [comment]
Closing the issue , solved with following config

> [[inputs.cloudwatch]]
  access_key = "key"
  secret_key = "skey"
  period = "5m"
  delay = "5m"
  ratelimit = 50
  region = "eu-central-1"
  namespace = "AWS/RDS"

  [[inputs.cloudwatch.metrics]]
   names = ["DatabaseConnections"]

      [[inputs.cloudwatch.metrics.dimensions]]
        name = "DBInstanceIdentifier"
        value = "*"
