### ISSUE TITLE
Limit size of `BasicStats.cache`.

### ISSUE THREAD

**Issue by j2gg0s** [influxdata/telegraf#5252]
## Feature Request
TODO

### Proposal && Desired behavior
We should allow user limit size of `BasicStats.cache` by config.

**Comment by danielnelson** [comment]
It would be helpful if you could add some more information about the issue you are experiencing.  Maybe we can add some selfstats about the cache size for monitoring, as I'm not sure we can limit it without breaking the output.

Another idea for dealing with this would be with a rate limiting processor, that would drop series that have too many metrics.  I think this may require the addition of start/stop methods to the Processor interface.
