### ISSUE TITLE
SNMPv3 input does not gather data

### ISSUE THREAD

**Issue by pvandervelde** [influxdata/telegraf#5255]
Trying to get Telegraf to collect SNMP data from some Ubiquiti equipment (router, switches and access point) using the V3 protocol. 

The telegraf config looks like:

    [[inputs.snmp]]
      agents = [
        "192.168.1.4"
      ]
      auth_password = "MyPassword"
      auth_protocol = "SHA"
      name = "snmp.uap"
      priv_password = "MyPassword"
      priv_protocol = "AES"
      sec_level = "authPriv"
      sec_name = "MyUser"
      version = 3
      context_name = ""
      timeout = "5s"
      retries = 1

      ##
      ## Host Resources
      ##

      #  System uptime
      [[inputs.snmp.field]]
        name = "sysUpTime"
        oid = "RFC1213-MIB::sysUpTime.0"

      [inputs.snmp.tagpass]
        influxdb_database = "system"

### System info:

* Telegraf 1.9.0 (git: HEAD 2bf21c0d)
* Ubuntu 16.04.5

### Steps to reproduce:

Running 

    sudo telegraf --test --debug --config /etc/telegraf/telegraf.d/inputs_snmp_uap.conf

returns

    2019-01-05T23:40:28Z I! Starting Telegraf 1.9.0

while running

    snmpwalk -v3 -l 'authPriv' -a 'SHA' -A 'MyPassword' -u 'MyUser' -x 'AES' -X 'MyPassword' 192.168.1.4 RFC1213-MIB::sysUpTime.0

returns

    RFC1213-MIB::sysUpTime.0 = Timeticks: (151006) 0:25:10.06

Running with the debug flag doesn't provide any useful logs or output to the command line so I don't know why telegraf is failing. For the very least it would be nice if the logs could provide some information on what is going on.

Any suggestions as to why this isn't working?

**Comment by pvandervelde** [comment]
Apparently yes it does. That's odd because all my inputs have one of those tags. I use them to direct the metrics to the correct influx database. I can leave it out but then I'd have to figure out how to make the metrics go to the right database.

**Comment by danielnelson** [comment]
You probably only want the tagpass on outputs and a tags table on the inputs, check the very last example on this page [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md).
