### ISSUE TITLE
monitor SQL server versions 2008 through telegraf

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5258]
HI,

Is there any way to monitor SQL server versions 2008 through telegraf,
as the **sqlserver** plugin currently works with SQL2008+.

**Comment by danielnelson** [comment]
The only method we have is the sqlserver input plugin.  It should work with 2008, if you add your configuration and show the error you are receiving it might be possible to help.

**Comment by priyankamondalairtel** [comment]
sqlserver metric in configuration file:

[[inputs.sqlserver]]
 servers = [
   "Server=xxx.xxx.xxx.xxx;Port=1433;User Id=telegraf;Password=Password123;app name=telegraf;log=1;",
   ]
error log I am getting:

E! [inputs.sqlserver]: Error in plugin: Login error: read tcp xxx.xxx.xxx.xxx:51248->xxx.xxx.xxx.xxx:1433: wsarecv: An existing connection was forcibly closed by the remote host.

also have also added telegraf user in ssms:

USE master;
GO
CREATE LOGIN telegraf WITH PASSWORD = N'Password123';
GO
GRANT VIEW SERVER STATE TO telegraf;
GO
GRANT VIEW ANY DEFINITION TO telegraf;
GO

**Comment by priyankamondalairtel** [comment]
i am waiting for your answer, any luck?

**Comment by nicgrobler** [comment]
What's the "N" in front of the password in your CREATE command for?

**Comment by santakd** [comment]
Have similar error on a server with SQL Server 2008 SP1 but the same version\config works on a servers with SQL Server 2008 SP3. So I am trying to update to SP3 and will let you know.

**Comment by santakd** [comment]
refer https://github.com/influxdata/telegraf/issues/5311 for more updates on the above

**Comment by santakd** [comment]
Upgrading to SQL Server 2008 SP3 has resolved the connection reset issue
SP3 can be downloaded from https://support.microsoft.com/en-us/kb/2979597

Thank you

**Comment by danielnelson** [comment]
Thanks @santakd, I updated the documentation to reflect that you must have SP3. efbc83c8

**Comment by santakd** [comment]
You are welcome @danielnelson :-)
