### ISSUE TITLE
SNMP Table when using index_as_tag storing index as text 

### ISSUE THREAD

**Issue by lucasbritos** [influxdata/telegraf#5260]
## Feature Request
It would be nice to Telegraf snmp plugin store the index as text as snmptable does, instead of dotted numbers.
i.e
"ROSHN-CMTS01_190_2_98"  instead 21.82.79.83.72.78.45.67.77.84.83.48.49.95.49.57.48.95.50.95.57.56

Current Telegraf config

[[inputs.snmp]]
  agents = [ "X.X.X.X" ]
  version = 2
  community = "public"
  interval = "5m"
  timeout = "10s"
  retries = 3
  name = "cgnat"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "pool"
    inherit_tags = [ "hostname" ]
    oid = "JUNIPER-NAT-MIB::jnxNatPoolTable"
    index_as_tag = true

### Current behavior:

On InfluxDB i got:

SHOW TAG VALUES ON telegraf FROM "pool" WITH KEY = index
name: pool
key   value
index 21.82.79.83.72.78.45.67.77.84.83.48.49.95.49.57.48.95.50.95.57.56
index 22.82.79.83.72.67.45.67.77.84.83.48.49.95.49.57.48.95.50.95.49.49.49
index 22.82.79.83.72.67.45.67.77.84.83.48.50.95.49.57.48.95.50.95.49.49.50
index 22.82.79.83.72.78.45.67.77.84.83.48.49.95.50.48.48.95.51.95.50.50.50
index 22.82.79.83.72.79.45.67.77.84.83.48.49.95.49.57.48.95.50.95.49.48.56
index 22.82.79.83.72.83.45.67.77.84.83.48.49.95.49.57.48.95.50.95.49.48.48
index 22.82.79.83.72.83.45.67.77.84.83.48.49.95.49.57.48.95.50.95.49.48.51
index 24.82.79.83.72.67.45.67.77.84.83.48.49.95.49.56.49.95.49.57.57.95.49.52.52
index 24.82.79.83.72.67.45.67.77.84.83.48.49.95.49.56.49.95.49.57.57.95.49.52.53
index 24.82.79.83.72.67.45.67.77.84.83.48.50.95.49.57.48.95.49.53.49.95.49.54.48
index 24.82.79.83.72.67.45.67.77.84.83.48.50.95.49.57.48.95.49.53.49.95.49.54.56

### Desired behavior:
snmptable output example

root@monitor:/proj# snmptable -Ci -v 2c  -M /proj/monitor-portable/telegraf/mibs -c public X.X.X.X  JUNIPER-NAT-MIB::jnxNatPoolTable
SNMP table: JUNIPER-NAT-MIB::jnxNatPoolTable
This is:
                     index jnxNatPoolType jnxNatPoolTransHits
   "ROSHN-CMTS01_190_2_98"        napt-44          1256164494
  "ROSHC-CMTS01_190_2_111"        napt-44          2815909475
  "ROSHC-CMTS02_190_2_112"        napt-44          1836574965
  "ROSHN-CMTS01_200_3_222"        napt-44          1075879938
  "ROSHO-CMTS01_190_2_108"        napt-44          2194630530
  "ROSHS-CMTS01_190_2_100"        napt-44          4135211040
  "ROSHS-CMTS01_190_2_103"        napt-44           974266996
"ROSHC-CMTS01_181_199_144"        napt-44           574738574
"ROSHC-CMTS01_181_199_145"        napt-44          3522126621
"ROSHC-CMTS02_190_151_160"        napt-44          1415251436
"ROSHC-CMTS02_190_151_168"        napt-44          2629286335

### Use case: 

I know the data is there, but its not human readable and needs to be translated somehow

**Comment by danielnelson** [comment]
Does it help if you set the MIBDIRS environment variable?
```
export MIBDIRS=/proj/monitor-portable/telegraf/mibs
telegraf --input-filter snmp --test
```

**Comment by danielnelson** [comment]
Nevermind, that won't help.

**Comment by danielnelson** [comment]
Can you create a packet capture while running `telegraf --input-filter snmp --test`:
```
sudo tcpdump -s 0 -i eth0 -w foo.pcap host 203.50.251.17 and port 161
```

**Comment by lucasbritos** [comment]
Here you are !
[snmp1.zip](https://github.com/influxdata/telegraf/files/2735007/snmp1.zip)

**Comment by lucasbritos** [comment]
I did some research and looks like a limitation of snmp poller which this plugin is based on (github.com/soniah/gosnmp). Expected output is compared with snmpget -On option (Numeric output)

This is a major downside because this is a basic functionality of SNMP and in well-implemented SNMP agents architecture indexes are marked as "not-accessible". There is no way to do it but this.
So I DONT RECOMMEND using telegraf as a polling agent on infrastructure monitoring while this is issue isnt fixed.

As a workaround I implemented a clever trick for key/value replacement on grafana but it doesn't scale:
https://community.grafana.com/t/how-to-alias-a-template-variable-value/10929

**Comment by glinton** [comment]
Thanks, did you by chance open an issue upstream in gosnmp?

**Comment by lucasbritos** [comment]
glinton, looking in to the code i realized the table is created on the plugin and not in the gosnmp module.

I forked the repository and my fix/improvment it is working fine, just adding an option to convert the index format (integer array to ascii).

https://github.com/lucasbritos/telegraf

It is a minor change (just a few lines on snmp.go) and i would like to do a pull request but im stuck with unit testing (which is required). Also I updated plugin's README.

Im not familiarized with testing, mocking even with golang. Could you give me a hand with that ?

Thanks
Lucas

**Comment by danielnelson** [comment]
@lucasbritos Looked briefly at your patch, I think it should be possible to handle string indexes without adding a new option.  I'm not 100% sure, but I'd like to look into this since we can't take back new options easily.

**Comment by Hipska** [comment]
Is this still to be implemented? As I'm about to setup a huge environment and I know there are some cases of ascii indexes

**Comment by M0rdecay** [comment]
Are there any workarounds for this situation? I encountered a similar problem when the index is described in the Entry table, but is not published in the table itself as a dedicated column (note that hiding the fields that make up the index is the [right approach](http://net-snmp.sourceforge.net/wiki/index.php/TUT:snmptable#Table_Indexes)).
This is a critical bug in telegraf.

**Comment by Hipska** [comment]
Also, it seems that this bug/feature is being postponed every release. What is the reason for that?

**Comment by M0rdecay** [comment]
I add that simply converting ascii to text will not bring the desired result. If the index is composite, its elements are separated by a symbol with a code of 21, which should be interpreted as a dot symbol.  
Also, if one of the columns in the index is of type number, it is written as is: `INTEGER: 1 -> .1` etc.

It turns out not quite a trivial algorithm:
 - discard the first block from the index line (`2.` - text start character)
 - split the index line into parts through the symbol `.21`
 - for each block, based on its order, find the column name in `Entry -> INDEX {...}` of the table
 - climbing the MIB tree, determine the data type in this column
 - depending on the type of data, convert from ASCII to text

Further, at your discretion - you can combine the received lines into one through a dot and write to the `index` tag, or you can write each element as a separate tag - you already have a key and a value

**Comment by lucasbritos** [comment]
@M0rdecay, regarding the algorithm its not complex. I resolved as an extra option. As @danielnelson mentioned, should be a more robust way (as native snmptable does).

```
				if t.TagAsText {
					idxa := strings.Split(idx, ".")
					var idxw string = ""
	// Shitfs first element (usually name length) TODO: Make lenght prefix configurable
					for _,x := range idxa[1:] { 
						n,_ := strconv.Atoi(x)
						idxw += string(n)
					}
					rtr.Tags["index"] = idxw
				} else {
					rtr.Tags["index"] = idx
				}
```

**Comment by M0rdecay** [comment]
Also add: you can search for a column in the tree, starting from the current table, then going up to the parent of the table until you find all the columns.
Such a search can be performed using snmptranslate with the -Tp option

A slightly different option: run `snmptranslate -Tp -m all | grep '+ -. *%COLUMN_NAME%'`

You will find the data type for the desired column after the access mask and before the column name

@lucasbritos Try to decode such an index - `2.102.105.114.115.116.21.115.101.99.111.110.100.2`
You will see that the operation will return invalid characters, while snmptable will return this result:
`"first"."second".2` - [Golang playground](https://play.golang.org/p/O8IL6yLsbc_e)

This is an example of a three-part index, where the first two columns are `String` and the last is `Integer32`

**Comment by M0rdecay** [comment]
In the original snmptable, it looks like an index string is being formed, starting from here - https://github.com/haad/net-snmp/blob/c629882ba31aaf27c859de2d47a6401849661ccd/apps/snmptable.c#L700

The switch-case shows how, depending on the data type of the column, different values ​​are processed.
If, of course, I read the source code correctly.

**Comment by stephanie-engel** [comment]
This appears to be the same issue as https://github.com/influxdata/telegraf/issues/3256

**Comment by henriknoerr** [comment]
Sorry, is this one being handled or should we fork the solution by @lucasbritos - Not sure if this is feasable two years after, and still not resolved.

**Comment by MyaLongmire** [comment]
I am going to close this as `snmptraslate` is deprecated in telegraf and supported versions no longer use it due to performance issues. If you are having issues with the recent `snmp` update, please open another ticket with all relevant information.
