### ISSUE TITLE
Unable to exclude tags for Aerospike metrics

### ISSUE THREAD

**Issue by KannanAK** [influxdata/telegraf#5262]
Issue: Aerospike metrics tags are not getting excluded when using tagexclude option. 

Currently all the aerospike metrics are generated with lot of details and redundant tags. I'm trying to exclude the unwanted tags and keep only the aerospike_host, namespace, node_name in the metric details so that it would be easy to read, understand the metrics.

aerospike_namespace_effective_replication_factor{_zeocore__query_hist_track_thresholds="1,8,64",_zeocore__read_hist_track_thresholds="1,8,64",_zeocore__udf_hist_track_thresholds="1,8,64",_zeocore__write_hist_track_thresholds="1,8,64",aerospike_host="localhost:3000",conflict_resolution_policy="generation",index_type="undefined",namespace="zeocore",node_name="BB9XXXXXXXXX",read_consistency_level_override="off",storage_engine="device",storage_engine_device="/dev/nvme1n1",storage_engine_encryption_key_file="null",storage_engine_scheduler_mode="null",write_commit_level_override="off"} 1

### Relevant telegraf.conf:
[[inputs.aerospike]]
  servers = ["localhost:3000"]
  tagexclude = ["_zeocore__query_hist_track_thresholds", "_zeocore__read_hist_track_thresholds", "_zeocore__udf_hist_track_thresholds", "_zeocore__write_hist_track_thresholds", "storage_engine", "storage_engine_device","storage_engine_encryption_key_file", "storage_engine_scheduler_mode", "read_consistency_level_override", "index_type", "conflict_resolution_policy", "write_commit_level_override" ]

### System info:
Os: 4.14.67-66.56.amzn1.x86_64
Telegraf 1.9.1
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

If the tagexclude is successful, the metric would look like this.

aerospike_namespace_effective_replication_factor{aerospike_host="localhost:3000", namespace="zeocore",node_name="BB9XXXXXXXXX"}  1

### Actual behavior:
The tags are not getting excluded.

aerospike_namespace_effective_replication_factor{_zeocore__query_hist_track_thresholds="1,8,64",_zeocore__read_hist_track_thresholds="1,8,64",_zeocore__udf_hist_track_thresholds="1,8,64",_zeocore__write_hist_track_thresholds="1,8,64",aerospike_host="localhost:3000",conflict_resolution_policy="generation",index_type="undefined",namespace="zeocore",node_name="BB9XXXXXXXXX",read_consistency_level_override="off",storage_engine="device",storage_engine_device="/dev/nvme1n1",storage_engine_encryption_key_file="null",storage_engine_scheduler_mode="null",write_commit_level_override="off"} 1

### Additional info:
I was able to exclude tags from disk metrics using the below example.
[[inputs.disk]]
  tagexclude = ["fstype", "mode"]

Metrics Output:
disk_used_percent{device="xvda1",path="/"} 22.645098861304028

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I think these are fields which are being converted to labels in the prometheus_client output by the `string_as_label = true`.  Try changing the `tagexclude` to `fielddrop` or disabling this setting in the output.

If that doesn't work then run `telegraf --input-filter aerospike --test` and paste the output here.

**Comment by KannanAK** [comment]
Wow, that worked like a charm. Thank you for that suggestion.

I faced another issue with the aerospike metrics that the field
'batch_index_queue's value was changing every 1 minute and thus it caused
prometheus to store 5 different series (running 5 node aerospike cluster)
everytime the value changes.

After setting 'string_as_label' false, the batch_index_queue label is
automatically dropped and now I'm getting a clear, unique metrics.

Thanks again for your help.
