### ISSUE TITLE
Feature Request for apache qpid plugin

### ISSUE THREAD

**Issue by sri-05** [influxdata/telegraf#5268]
## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
It looks like the [Apache Qpid](https://qpid.apache.org/) project provides several brokers, is there a specific broker you are intested in or do you have any links to specific APIs to monitor?

**Comment by sri-05** [comment]
Hi,
Currently i am working on qpid-java-broker.. It will be helpful if we get input plugin for apache quid-java-broker.

**Comment by danielnelson** [comment]
I'm going to merge this with #5272
