### ISSUE TITLE
Feature request for Apache Qpid daemon plugin

### ISSUE THREAD

**Issue by kaushalshriyan** [influxdata/telegraf#5272]
## Feature Request

Metrics from one or many Apache QPID servers

### Proposal:

inputs.apacheqpiddaemon plugin needs to be incorporated.

### Current behavior:

No plugin for Aache qpid daemon (https://qpid.apache.org/)

### Desired behavior:

Similarly to the below RabbitMQ servers as an example 

```
# # Read metrics from one or many RabbitMQ servers via the management API
# [[inputs.rabbitmq]]
#   url = "http://localhost:15672" # required
#   # name = "rmq-server-1" # optional tag
#   # username = "guest"
#   # password = "guest"
#
#   ## A list of nodes to pull metrics about. If not specified, metrics for
#   ## all nodes are gathered.
#   # nodes = ["rabbit@node1", "rabbit@node2"]
```

### Use case: [Why is this important (helps with prioritizing requests)]

Apache QPID opensource is widely used for AMQP based messaging queuing system and support many languages like java, python and C which are the most popular programming languages and it also runs on various Linux distribution.

**Comment by kaushalshriyan** [comment]
@danielnelson Checking in if there is an update regarding the feature request? Thanks in Advance.

**Comment by danielnelson** [comment]
This will most likely need to be implemented by someone in the Telegraf community, to my knowledge no one is working on it currently.

**Comment by kaushalshriyan** [comment]
@danielnelson Thanks and can it be assigned to Telegraf community team?

**Comment by danielnelson** [comment]
If someone would like to work on this, or any other issue, it's helpful to comment on the issue so that there is no unneeded duplication of effort.

**Comment by kaushalshriyan** [comment]
Checking in anyone had a chance to work on this specific feature request? Thanks in Advance.

**Comment by kaushalshriyan** [comment]
Checking in if anyone had a chance to work on this specific feature request? Thanks in Advance.

**Comment by glinton** [comment]
@kaushalshriyan, looks like you'd be clear to implement this if you desire.

**Comment by kaushalshriyan** [comment]
@glinton Yeah i would like to implement. Please comment

**Comment by russorat** [comment]
It looks like https://qpid.apache.org/components/messaging-api/index.html uses AMQP versions - 1.0, 0-10 for their API. Would it be better to add 1.0 and 0-10 support to our existing AMQP consumer plugin?

**Comment by danielnelson** [comment]
> Would it be better to add 1.0 and 0-10 support to our existing AMQP consumer plugin?

Possibly, or 1.0 as another consumer plugin.  However, this issue is about monitoring the Qpid daemon itself.  The next step that needs taken here is to identify what the monitoring APIs are that we would be targetting.
