### ISSUE TITLE
md14454/gosensors

### ISSUE THREAD

**Issue by zensqlmonitor** [influxdata/telegraf#528]
When I try to do a make:
```
# make
go get ./...
# github.com/md14454/gosensors
../../md14454/gosensors/gosensors.go:6:30: fatal error: sensors/sensors.h: No such file or directory
 // #include <sensors/sensors.h>
                              ^
compilation terminated.
make: *** [prepare] Error 2
```

**Comment by sparrc** [comment]
errp, I didn't realize this was a requirement of that package, current workaround is to install the `lm-sensors` package

**Comment by zensqlmonitor** [comment]
Thanks.
I got it, it is called lm_sensors 
...but in CentOS 7, make still failed with the same error message.

**Comment by sparrc** [comment]
I'm going to add some build flags to the sensors plugin to only compile when a flag is passed to it, then you can ignore building it for most cases

**Comment by zensqlmonitor** [comment]
Ok, I resolve it by installing following package:
yum install lm_sensors-devel
