### ISSUE TITLE
inputs.ceph with ceph_user and key

### ISSUE THREAD

**Issue by Evai1iey** [influxdata/telegraf#5280]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
use ceph auth system to get access to ceph stats (username with key file).

### Current behavior:
not supported, there is a parameter ceph_user but without keyfile it is useless.

### Desired behavior:
easy access to all ceph related stats. 

### Use case: [Why is this important (helps with prioritizing requests)]

atm it is needed to run service telegraf as user ceph, to get access to ceph sockets and get access to any ceph stats. I would like run service telegraf as user telegraf
as user telegraf follow works fine, if you add user client.telegraf with needed permissions to ceph. 
`ceph -n client.telegraf --keyring=/etc/telegraf/ceph.client.telegraf.keyring health`

**Comment by danielnelson** [comment]
I think you can set the keyring location in the config file, or you can use the default keyring location, let me know if you can get it working.

http://docs.ceph.com/docs/mimic/rados/configuration/auth-config-ref/#keys

**Comment by danielnelson** [comment]
This would definitely work, but I think the socket allows read access for the `ceph` group.  It might be preferable to add the `telegraf` user to the `ceph` group:
```
usermod -aG ceph telegraf
```

**Comment by glinton** [comment]
@Evai1iey Did adding the `telegraf` user to the `ceph` group allow you to request performance data from the sockets?
