### ISSUE TITLE
Unable to use a Windows path in inputs.file

### ISSUE THREAD

**Issue by murray02** [influxdata/telegraf#5297]
This plugin does not support windows file paths:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/file

There is no useful information in Event Viewer and nothing in the logs that errors out.

**Comment by danielnelson** [comment]
Make sure to use proper escaping for any `\` in the path according to the [TOML spec](https://github.com/toml-lang/toml).  If it still not working please add your configuration file.

**Comment by murray02** [comment]
`
[[inputs.file]]
  files = ["C://version.info"]
  data_format = "json"

  tag_keys = [
    "version",
    "build"
  ]
`

Still not working. Not sure what it could be. I have tried a combination of `\/` and `/\` and `//` and `\\`

The contents of the file are as follows:
`
{
	"version": "1.2.3",
	"build": "605"
}
`
Running the command as a "test" gives this:
`
PS C:\telegraf> .\telegraf.exe -config .\telegraf.conf
2019-01-17T12:49:20Z I! Starting Telegraf 1.9.2
PS C:\telegraf>
`

**Comment by glinton** [comment]
There is no error then, the problem is with your data/configuration. To output in influx format, you need at least one field. The json parser only adds numeric values as fields by default. Update your config to include:
`json_string_fields = ["build"]`
