### ISSUE TITLE
Missing SSL metrics from x509_cert plugin if there is a failing URL in sources array

### ISSUE THREAD

**Issue by hristodragolovbede** [influxdata/telegraf#5304]
### Relevant telegraf.conf:

[[inputs.x509_cert]]
  sources = ["https://www.testsite.com:443","https://www.google.com:443"]

### System info:
- Telegraf 1.9.2
- centos7

### Expected behavior:
Telegraf exposes SSL metrics for **www.google.com**

### Actual behavior:
Because www.testsite.com doesn't exist the plugin reports a timeout error and doesn't continue checking the next URL in the sources array. No SSL metrics data is exposed for https://www.google.com

### Additional info
If you put another URL in front of www.testsite.com in the sources array, the plugin will expose SSL metrics for this URL. So to sum up .... everything before www.testsite.com in the sources array will have metrics exposed but everything after www.testsite.com will be missing.

**Comment by danielnelson** [comment]
Thanks for the report, a workaroundw ould be to split this into two plugin definitions:
```
[[inputs.x509_cert]]
  sources = ["https://www.testsite.com:443"]
[[inputs.x509_cert]]
  sources = ["https://www.google.com:443"]
```

**Comment by hristodragolovbede** [comment]
Thanks Daniel. This is what I have done as a workaround as well.
