### ISSUE TITLE
SQL plugin not reportring memory breakdown (prometheus output)

### ISSUE THREAD

**Issue by cblomart** [influxdata/telegraf#5305]
### Relevant telegraf.conf:

```ini
[[outputs.prometheus_client]]
  listen = ":9273"

# [...] default perf counters

[[inputs.sqlserver]]
  servers = [
    "Server=localhost;Port=1433;User Id=telegraf;Password=*****************;app name=telegraf;log=1;",
  ]

  query_version = 1
```

### System info:

Telegraf: 
```dos
C:\Program Files\telegraf>telegraf.exe --version
Telegraf 1.9.1 (git: HEAD 20636091)
```
OS version: Windows 2012 r2 
SQL version: 2008 r2 (10.50.6560)

plugins:
```
2019-01-17T11:46:51Z I! Loaded inputs: inputs.win_perf_counters inputs.sqlserver
[...]
2019-01-17T11:46:51Z I! Loaded outputs: prometheus_client
```

### Steps to reproduce:

System currently in test. Will reproduce in Q&A if required. (Would like to solve this before)

### Expected behavior:

Memory Breakdown or clerk present in prometheus output.

### Actual behavior:

No memory breakdown informations.

### Additional info:

Executed SQL query "sqlMemoryClerk" successfully as SQL admin and telegraf user.

**Comment by cblomart** [comment]
Further checked with ```telegraf --test```

```bash
>telegraf.exe --test | find /i "clerk"
2019-01-17T15:54:34Z I! Starting Telegraf 1.9.1
2019-01-17T15:54:34Z I! Using config file: C:\Program Files\Telegraf\telegraf.co
nf
2019-01-17T15:54:34Z E! Unable to append to /Program Files/Telegraf/telegraf.log
 (open /Program Files/Telegraf/telegraf.log: Access is denied.), using stderr
> Memory\ breakdown\ (%),farm=********,host=********,role=********,servername=********,service=********,type=Memory\ clerk,zone=******** Buffer\ pool="0.00",Cache\ (objects)="9.30",Cache\ (sql\ plans)="82.10",Other="8.70" 1547740475000000000
> Memory\ breakdown\ (bytes),farm=********,host=********,role=********,servername=********,service=********,type=Memory\ clerk,zone=******** Buffer\ pool="425984.00",Cache\ (objects)="541843456.00",Cache\ (sql\ plans)="4794433536.00",Other="504856576.00" 1547740475000000000
```

So it looks like the input plugin works properly. May it be that prometheus_client output loses some informations?

**Comment by danielnelson** [comment]
The prometheus output can only report numeric values.  It is likely that these fields should have been a numeric type but for `query_version=1` we won't be adjusting this.  However, you could probably use the converter processor as a workaround to correct this.

**Comment by cblomart** [comment]
For information, the issue seems resolved with:
```toml
[[processors.converter]]

  [processors.converter.fields]
    float = ["Buffer pool","Cache (objects)","Cache (sql plans)","Other"]
```
