### ISSUE TITLE
Add namespace configuration to Prometheus plugin

### ISSUE THREAD

**Issue by simoelmou** [influxdata/telegraf#5306]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add namespace configuration to Prometheus plugin

### Current behavior:
Currently, Prometheus input plugin allows retrieving metrics from the pods of all the namespaces in a cluster.

### Desired behavior:
There should be a configuration where you can specify the namespace(s) that you want to retrieve metrics from. This would allow deploying telegraf in the case where the permissions are limited to only some certain namespaces.

### Use case: [Why is this important (helps with prioritizing requests)]
This is a quick win because it's simple to implement and also allows to use Prometheus input plugin in a limited environment where it's usually the case in enterprises.

**Comment by goller** [comment]
@simoelmou I like that idea.  It also helps scale in a way as different telegrafs could be configured for different namespaces.

**Comment by danielnelson** [comment]
It may be possible to do this currently with a properly configured `kube_config` file, it looks like you will need to define a context and set the current-context option to select it.

**Comment by simoelmou** [comment]
@danielnelson In an Openshift environment that would be complicated to put in place, especially in a production cluster. At the moment I created a fork of the plugin that would only monitor the pods of the namespace where telegraf is deployed.

**Comment by danielnelson** [comment]
Closed in #5697

**Comment by guai** [comment]
Hi
Is there an option so telegraf watched only for the namespace it is deployed in?
