### ISSUE TITLE
Add OAUTH2 Support for HTTP Input Plugin

### ISSUE THREAD

**Issue by mapl** [influxdata/telegraf#5309]
## Feature Request
Add OAUTH2 Support for HTTP Input Plugin

### Proposal:

When using OAUTH2, you need to get token first via a HTTP POST Request , then you will able to send a succeeding GET Request using the previously retrieved token.

Ref.: https://aaronparecki.com/oauth-2-simplified/

Example: 

1. POST https://api.authorization-server.com/token
grant_type=client_credentials&client_id=CLIENT_ID&client_secret=CLIENT_SECRET

2. GET curl -H "Authorization: Bearer RsT5OjbzRn430zqMLgV3Ia" 
https://api.authorization-server.com/1/me

 
### Current behavior:
n/a

### Desired behavior:
OAUTH2 support

### Use case: [Why is this important (helps with prioritizing requests)]

modern authentication mechanisms like OAUTH2 are becoming more and more common

**Comment by danielnelson** [comment]
Related pull request where we added OAUTH2 support to the http output plugin: https://github.com/influxdata/telegraf/pull/4536

**Comment by danielloader** [comment]
Glad to see a ticket filed for this - in the mean time has anyone else come up with a solution? 
Is there a plugin that listens instead so I can write a small proxy script to poll an OAUTH2 secured endpoint, get the bearer token, then get the JSON object and forward it to telegraf somehow?

Thanks

**Comment by glinton** [comment]
I don't believe there has been any work to get oauth into the http input plugin.

Regarding the JSON -> InfluxDB Line Protocol, individual plugins (inputs/outputs) can have unique [data formats](https://docs.influxdata.com/telegraf/v1.9/data_formats/) which handle the translations.
