### ISSUE TITLE
Azure LogAnalytics Output Plugin

### ISSUE THREAD

**Issue by yshahin** [influxdata/telegraf#5317]
## Feature Request
Opening a feature request kicks off a discussion.

### Proposal:
Proposal for adding a new Output plugin for "Azure LogAnalytics" which will allow to send telegraph metrics over to Azure OMS portal.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api

### Use case: [Why is this important (helps with prioritizing requests)]
Not all users track metrics in AppInsights or AzureMonitor

**Comment by jmalette** [comment]
Any update on this?  I'd like this feature as well.

**Comment by bmcstuff** [comment]
+1 on this output plugin

**Comment by saikovvuri** [comment]
+1

**Comment by eehret** [comment]
Does anyone else know of another relatively easy way to push metrics to Azure log analytics that does NOT require OMS?  Our instances of OMS agent on linux have been plagued with problems, which has led me to try to find another redundant way to report metrics for our mission critical resources.

**Comment by yshahin** [comment]
Its been a year and a half now, are you going to merge this or should I just abandon the PR?

**Comment by mdowst** [comment]
@eehret I have found that keeping the Linux agents updated helps. There where a bunch of bugs and issues with earlier versions that have been fixed. https://github.com/microsoft/OMS-Agent-for-Linux/releases/

```
wget https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.12.15-0/omsagent-1.12.15-0.universal.x64.sh
sudo sh ./omsagent-1.12.15-0.universal.x64.sh --upgrade
```

**Comment by eehret** [comment]
@mdowst Thanks, but that's not the issue in our case.  We're running the latest version already.

**Comment by DStrand1** [comment]
Is anyone still interested in this potential new plugin?
