### ISSUE TITLE
input.mqtt_consumer metric parse error

### ISSUE THREAD

**Issue by yn1v** [influxdata/telegraf#5318]
### Relevant telegraf.conf:
[[inputs.mqtt_consumer]]
  servers = ["tcp://zancudo.sytes.net:1883"]
  qos = 0
  connection_timeout = "30s"
  topics = [
    "teodolinda/gerencia/temp",
    "teodolinda/gerencia/humidity",
    "teodolinda/recepcion/temp",
  ]
  persistent_session = false
  client_id = ""
  data_format = "influx"

### System info:
Fedora 29
telegraf-1.9.2-1.x86_64
influxdb-1.7.3-1.x86_64
kernel-4.18.16-300.fc29.x86_64

### Steps to reproduce:
systemctl start influxdb.service 
systemctl start telegraf.service
systemctl status telegraf.service

### Expected behavior:
messages get into influxdb

### Actual behavior:
Jan 19 23:51:33 localhost.localdomain telegraf[1814]: 2019-01-20T05:51:33Z I! [inputs.mqtt_consumer] Connected [tcp://zancudo.sytes.net:1883]
Jan 19 23:51:45 localhost.localdomain telegraf[1814]: 2019-01-20T05:51:45Z E! [inputs.mqtt_consumer]: Error in plugin: metric parse error: expected field at offset 9: "29.700001"
Jan 19 23:51:45 localhost.localdomain telegraf[1814]: 2019-01-20T05:51:45Z E! [inputs.mqtt_consumer]: Error in plugin: metric parse error: expected field at offset 9: "57.000000"
Jan 19 23:51:46 localhost.localdomain telegraf[1814]: 2019-01-20T05:51:46Z E! [inputs.mqtt_consumer]: Error in plugin: metric parse error: expected field at offset 6: "31.875"

### Additional info:
Telegraf is working as I can see data in Chronograf from the system (cpu, disk, mem).
I was looking if I needed some configuration for the values, but I find this "There are no additional configuration options for InfluxDB line protocol. The metrics are parsed directly into Telegraf metrics."
I saw issue #4463 that it is similar, but it was not  resolved.

**Comment by danielnelson** [comment]
It looks like the data in mqtt is not formatted as expected, when set to `data_format = "influx"` the plugin is expecting [line protocol](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/).

From the log message it looks like you have raw values.  Try using the `value` data_format by adding these lines instead of `data_format = "influx"`:
```
data_format = "value"
data_type = "float"
```

**Comment by yn1v** [comment]
It worked. Thanks

**Comment by mohanmaniramesh** [comment]
if i solve this telegraf error only ill get data in influxDB or what
