### ISSUE TITLE
inputs.diskio: get additional tags from external script

### ISSUE THREAD

**Issue by OlegKorchagin** [influxdata/telegraf#5319]
## Feature Request

A way to get additional tags from external script or file for inputs.diskio

### Proposal:

Allow users to add tags via external script. In a programming language that they know

### Current behavior:

Can get additional tags only from UDEV

### Desired behavior:

Get addtional tags from external script output or external file ( for example, json format )

- In case of external script, rarely run and cache result between runs
- In case of external file, drop external tags to "unknown" value if file is too old ( "expired" )

/etc/telegraf/telegraf.conf:
```
[[inputs.diskio]]
# external_script = "/usr/local/bin/persistant_disk_names.py"
# external_run_interval = 1h
# external_tags_set = [ "tag1", "tag2" ] # to sanitize script output - add tag ( with "unknown" value ) if not exists or remove if not in list
#   
# OR
#   
# external_file = "/tmp/persistant_names.json"
# external_file_max_age = "2h"  # after cache expired, add external_tags_set with value "unknown", "undefined" or something like this
# external_tags_set = [ "tag1", "tag2" ]
```

### Use case: [Why is this important (helps with prioritizing requests)]

1. common drive names ( like /dev/sda or /dev/dm-1 ) are not persistant ( depends on hardware discovery order, so it can be changed after reboot )
So i would like to be able to add permanent names
Yes, inputs.diskio can get additional tags from UDEV, but (2,3)

2. Different types of disks has different set of UDEV attributes. For example,

- all SCSI ( and SCSI emulated ) devices has ID_PATH
Depends of kernel version and physical bus, it may also have ID_VENDOR, ID_SCSI_SERIAL, ID_SERIAL
- virtio disks ( Nutanix and linux KVM ) has no such attributes and only identified by name ( permanent, in this case )
- LVM PV has DM_VG_NAME and DM_LV_NAME
- disk partitions ( GPT and MBR ), software raid ( mdadm ), any multipathing also has it's own attributes

Also, set of udev attributes may be uniq, and may be not ( in case if multipathing, for example )

3. Some of disk UDEV attributes may ( and should ) be converted to human readable format
- for FC SAN, ID_SERIAL is NAA name, so "VSP ( 097917 ) 00:06:E5" is much better than "60060e80167e7d0000017e7d000006e5"
- in ID_PATH only the last part is interesting ( "scsi-0:0:0:0" vs "pci-0000:03:00.0-scsi-0:0:0:0" )

and so on

4. But metric is influxdb should have fixed set of tags to visualize in graphana
So, maping unknown number of udev attributes to fixed set of influxdb tags is quite a challenge
IMHO, it's too complex task to be solved within a telegraf configuration file

5. Most of technicians know at least on high-level programming language ( python, ruby, nodejs etc )
The number of qualified golang programmers are somewhat less

So, it would be great to get additional tags from external script ( external command )
Or read from external file ( which will be maintained by external script from crontab, for example )

Since script performance will be less than golang code, it should be run less often ( i.e. every hour rather than every 10 seconds ). so script output will have to be cached
If external script failed, or external file is too old, additional tags values should be "unknown"

**Comment by danielnelson** [comment]
I would like to solve this use case by creating a processor plugin that runs a child process.  It will read metrics on stdin and can write them with modifications to stdout.  Since the process will not be restarted performance shouldn't be as much of a concern, and it will be possible for the process to cache what is needed.

This will be similar to https://github.com/influxdata/telegraf/pull/4424

**Comment by powersj** [comment]
The exec input plugin and the execd processor have since been added. These should help with this use case. Marking closed.
