### ISSUE TITLE
Missing Azure config credentials in azure_monitor plugin

### ISSUE THREAD

**Issue by mjiderhamn** [influxdata/telegraf#5342]
### Relevant telegraf.conf:
```
[[outputs.azure_monitor]]
  azure_tenant_id = "foo"
  azure_client_id = "bar"
  azure_client_secret = "baz"
```

### System info:

Telegraf 1.9.1

### Steps to reproduce:

1. Follow the [Azure Monitor output plugin README.md on Authentication](https://github.com/influxdata/telegraf/blob/release-1.9/plugins/outputs/azure_monitor/README.md#authentication) and opt for Client Credentials as Telegraf configuration variables
2. Insert relevant config as of above
3. Start Telegraf

### Expected behavior:
Telegraf authenticates with Azure and starts outputting data.

### Actual behavior:
Error message is shown
```
field corresponding to `azure_client_id' is not defined in `*azure_monitor.AzureMonitor'
```

### Additional info:
Primarily add support for configuring the credentials as per the documentation. Until that is implemented, please update the documentation to reflect actual behaviour.

Reference: https://github.com/MicrosoftDocs/azure-docs/issues/15703

**Comment by danielnelson** [comment]
Looks like these options are not implemented at all, contradicting the documentation, but the environment variables should work so you should be able to use those today as a workaround.  cc @brnleehng

**Comment by danielnelson** [comment]
@gunnaraasen It looks like these options were removed during code review in https://github.com/influxdata/telegraf/pull/4089/commits/92600fc6ac6b375ef76870939c25162386081fa1, is there any reason we shouldn't add these options back in?

It does seem like we would need to duplicate most of this code or request a public interface for similar behavior: https://github.com/Azure/go-autorest/blob/7324aa01f00acb1ae6e502ac06e0213cfdf09bdb/autorest/azure/auth/auth.go#L84-L135

**Comment by danielnelson** [comment]
Removed documentation in #5348.  Added #5376 to add support for these options to the plugin, as I think it is preferable to needing to set environment variables.
