### ISSUE TITLE
Add prometheus serializer

### ISSUE THREAD

**Issue by aixeshunter** [influxdata/telegraf#5350]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a serializer that support Prometheus text exposition format

### Current behavior:
No such serializer

### Desired behavior:
```bash
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "/tmp/metrics.out"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "prometheus"
```

### Use case: [Why is this important (helps with prioritizing requests)]
The `telegraf` was installed in VM, we hope  the metrics will be stored in  `prometheus`.  And we have a component to get `prometheus` from vm serial port not http.

**Comment by danielnelson** [comment]
We have an open issue for this #4414.

I do have some concerns around streaming prometheus format in this way, as it won't behave identically to the prometheus output with respect to timestamps and multiple values.  It may be preferable to send `data_format = "influx"` out of VM and convert to prometheus format outside using a second instance of Telegraf.

**Comment by aixeshunter** [comment]
@danielnelson Thanks for your answer.In my opinion, I installed the prometheus `node-exporter` in VM, `telegraf` which installed in vm got the metrics from `node-exporter` and output to file(vm virtual serial port). 
Then, the external component that in hypervisor listened the serial port(linux socket) and got the metrics.
