### ISSUE TITLE
Missing data from cloudwatch 

### ISSUE THREAD

**Issue by Voolkanus23** [influxdata/telegraf#5351]
### Relevant telegraf.conf:

```
[[inputs.cloudwatch]]
 access_key = "Key"
 secret_key = "Key"
 period = "1m"
 interval = "1m"
 ratelimit = 50
 region = "eu-central-1"
 namespace = "AWS/ES"
  [[inputs.cloudwatch.metrics]]
    names = ["CPUUtilization", "FreeStorageSpace", "JVMMemoryPressure" , "SearchLatency"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DomainName"
      value = "*"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "ClientId"
      value = "*"

```
### System info:
Telegraf varsion - 1.9.2
OS - Ubuntu 16.04.5 LTS

### Steps to reproduce:

1. Fetch CloudWatch Metrics from AWS using the plugin
2. Try to create an alert using the metrics from above
3. The alert can't evaluate a simple lambda value, due to missing data points

### Expected behavior:
An alert calculates the value and triggers as expected

### Actual behavior:
Receiving the following error message: "ERROR: failed to realize reduce context from fields"

### Additional info:
Tick Script that is being used:
```
var db = 'telegraf'

var rp = 'autogen'

var measurement = 'cloudwatch_aws_es'

var groupBy = ['domain_name']

var whereFilter = lambda: TRUE

var period = 1m

var every = 30s

var name = 'dev_es_jvm_memory_pressure'

var idVar = name

var message = 'DEV {{.Level}}: {{.ID}} is {{ index .Fields "free_memory" }} % on domain: {{ index .Tags "domain_name" }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 10.0

var warn = 20.0

var info = 30.0

stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |window()
        .period(period)
        .every(every)
        .align()
    |last('jvm_memory_pressure_average')
        .as('used_memory')
    |eval(lambda: int(100.0 - "used_memory"))
        .as('free_memory')
    |alert()
        .info(lambda: "free_memory" < info)
        .warn(lambda: "free_memory" < warn)
        .crit(lambda: "free_memory" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .stateChangesOnly()
        .opsGenie2()
    |log()

```
Using the log() function I can see that the error appears when the value is being evaluated. Due to how the fetch of metrics from AWS works, there is always a missing data point at a current time. I'm trying to set up the alert to trigger based on a real time data as close as possible, however, because there is a missing data point on the current time at all times, I just can't find a proper way to create this alert. Is it possible to specify at the TICK script level to collect data from a minute ago for a minute? Or perhaps to send AWS metrics more often to not have a gap at a current time? Also, if someone else ever had a similar issue, how did you solved it?

Thanks in advance! 
![screen shot 2019-01-28 at 10 19 50](https://user-images.githubusercontent.com/47102630/51826033-61320000-22e6-11e9-8d47-dca6777ae202.png)

**Comment by danielnelson** [comment]
Can you try setting `delay = "5m"`, this will introduce a fair bit of latency into the query, but ought to give all metrics time to be reported, let me know if this helps.

**Comment by Voolkanus23** [comment]
@danielnelson I tried that, with period = "1m" and period = "5m" and the results are the same. There is still a gap of data at a current time.

**Comment by Voolkanus23** [comment]
So, after adding the quiet option on the evaluation, I can actually see the value I'm looking for at the logs, however, the alert is refusing to trigger. I guess this is because there is still some error that I'm "quieting down". The new script looks like so:

```
var db = 'telegraf'

var rp = 'autogen'

var measurement = 'cloudwatch_aws_es'

var groupBy = ['domain_name']

var whereFilter = lambda: TRUE

var period = 1m

var every = 30s

var name = 'dev_es_jvm_memory_pressure'

var idVar = name

var message = 'DEV {{.Level}}: {{.ID}} is {{ index .Fields "free_memory" }} % on domain: {{ index .Tags "domain_name" }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 10.0

var warn = 20.0

var info = 90.0 #For testing purposes

stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
        .truncate(1m)
    |window()
        .period(period)
        .every(every)
        .align()
    |last('jvm_memory_pressure_average')
        .as('used_memory')
        .quiet()
    |eval(lambda: int(100.0 - "used_memory"))
        .as('free_memory')
    |log()
    |alert()
        .info(lambda: "free_memory" < info)
        .warn(lambda: "free_memory" < warn)
        .crit(lambda: "free_memory" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .stateChangesOnly()
        .opsGenie2()
```

I'm attaching a screenshot that shows that the value is calculated correctly. However, at any point the alert is not triggered.

![screen shot 2019-01-30 at 14 03 22](https://user-images.githubusercontent.com/47102630/51983392-d5140a00-2498-11e9-8695-b6c0d094840c.png)

**Comment by danielnelson** [comment]
We will probably need to get a Kapacitor developer for advice on the TICKscript, but can you add the output of `telegraf --input-filter cloudwatch --test`

**Comment by Voolkanus23** [comment]
@danielnelson Thank you for your help,  I solved this issue. The ".stateChangesOnly()" function apparently was already triggered, so no new alerts were generated. Closing the issue.
