### ISSUE TITLE
Telegraf Mqtt plugin

### ISSUE THREAD

**Issue by AniGunner** [influxdata/telegraf#5354]
### Relevant telegraf.conf:
servers = ["#########"]
qos = 0
connection_timeout = "30s"
topics = [
"#########",
]
username = "root"
password = "N#########n"
insecure_skip_verify = true
data_format = "influx"
### System info:
Telegraf Version:Telegraf 1.9.1 
Operating system name: Ubuntu 16.04
[Include Telegraf version, operating system name, and other relevant details]
### Steps to reproduce:
1. I am trying push the metricsData from python paho client and its working properly no issues in it.
2. But sometimes it throws an parser error and other times it works properly.How do i handle this.I am just gathering the metrics and then pushing the data,if it throws error for some metrics how do i capture it,so that i can resend the metric at that particular timestamp.Is there any way to handle this.
### Actual behavior:
AxisHealth,companyId=30fa279b-87a4-494f-9dd2-0e3a8f41c118,monitoringHost=10.193.26.223,monitoringPort=10000,partnerId=pro-vigil_my-netalytics_com,siteId=68c28358-6173-4f3d-bbe4-f8512be86e91 DisplayName=\"Cam 1 Storage\",MonitorStatus=2i,MonitoringPort=10000i,MonitoringUrl=\"10.193.26.223\",StatusCode=401i,error=\"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>401 Unauthorized</title>\\n</head><body>\\n<h1>Unauthorized</h1>\\n<p>This server could not verify that you\\nare authorized to access the document\\nrequested.  Either you supplied the wrong\\ncredentials (e.g., bad password), or your\\nbrowser doesn't understand how to supply\\nthe credentials required.</p>\\n</body></html>\\n\" 1548741494684871936\nAxisHealth,companyId=30fa279b-87a4-494f-9dd2-0e3a8f41c118,monitoringHost=68.25.171.167,monitoringPort=10000,partnerId=pro-vigil_my-netalytics_com,siteId=51aed478-a2e3-4506-b278-9a2f0438d942 DisplayName=\"Cam 1 Storage\",Full=\"no\",Locked=\"no\",MonitorStatus=1i,MonitoringPort=10000i,MonitoringUrl=\"68....
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Telegraf handles this for you automatically, if there is an error when sending from an output the metrics are saved in a per-output buffer and will be resent on the next flush.  The best way to have visibility into this buffer is to enable the [internal][] plugin and watch the fields on the `internal_agent` and `internal_write` measurements.  So long as `metrics_dropped` does not increment the metric was able to delivered on retry.

There have been some fixes to these metrics in 1.9.3, so I also recommend updating to have the most accurate values.

[internal]: https://github.com/influxdata/telegraf/tree/release-1.9/plugins/inputs/internal
