### ISSUE TITLE
Input: OS package manager status

### ISSUE THREAD

**Issue by tjohnston-cd** [influxdata/telegraf#5359]
## Feature Request

Some other monitoring systems can scrape the OS package manager status (e.g. from `apt-get`, `yum` and so on). See [here](https://www.monitoring-plugins.org/doc/man/check_apt.html) for an Icinga/Nagios example.

Typically, this lets you see how many security/regular/etc upgrades are available from the package sources on a machine.

### Proposal:

Would something like this be possible in telegraf? 
Has anyone attempted it?

I could write something custom using `exec`, but this seems like a natural use case for a new input plugin.

Not sure if it should be per package manager (`inputs/apt`, `inputs/zypper` etc) or one that groups several of them (`inputs/packages`).

### Use case: [Why is this important (helps with prioritizing requests)]
This can be used to assess how up-to-date systems are, plan maintenance windows and so on.

**Comment by danielnelson** [comment]
This is a great idea

> Not sure if it should be per package manager (inputs/apt, inputs/zypper etc) or one that groups several of them (inputs/packages).

This is always tricky to determine, the biggest factors are how similar the plugin configuration and metric schema can be.  It often makes sense to start with a plugin for a specific packaging manager and then attempt to combine them as more implementations are added.

**Comment by SMARoovers** [comment]
I was working in this earlier today and am now walking the exec path. But I would love to see this natively supported.

This is what I got so far.
```[[inputs.exec]]
  commands = [
    "/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1"
  ]
  timeout = "5s"
  name_override = "apt_regular_updates_pending"
  data_format = "value"
  data_type = "integer"

[[inputs.exec]]
  commands = [
    "/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2"
  ]
  timeout = "5s"
  name_override = "apt_security_updates_pending"
  data_format = "value"
  data_type = "integer"```

**Comment by juliansteenbakker** [comment]
> This is what i got so far.

Looks good! however when implementing i get the following error:
```
[inputs.exec] Error in plugin: exec: exit status 2 for command '/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1': Usage: apt-check [options]...
```

Any idea what this can be?

**Comment by cbos** [comment]
@juliansteenbakker 
I faced the same issue. I have solved it differently:

```
[[inputs.exec]]
  commands = [
    "/etc/telegraf/telegraf.d/updatecount.sh 1"
  ]
  timeout = "15s"
  interval = "5m"
  name_override = "apt_regular_updates_pending"
  data_format = "value"
  data_type = "integer"

[[inputs.exec]]
  commands = [
    "/etc/telegraf/telegraf.d/updatecount.sh 2"
  ]
  timeout = "15s"
  interval = "5m"
  name_override = "apt_security_updates_pending"
  data_format = "value"
  data_type = "integer"
```

Content of `updatecount.sh`
```
#!/bin/bash

COUNT=$(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f $1)
echo $COUNT
```
I did not got it to work with a single command with version 1.21.4.

**Comment by powersj** [comment]
For folks looking for an apt specific option, there is an external plugin for [apt here](https://github.com/x70b1/telegraf-apt). 

I do not see us creating one or more plugins for apt, yum/dnf, zypper, pacman, etc. As such I am going to close this and suggest as others have done in this thread to use the exec plugin to capture the output you want.

Thanks!
