### ISSUE TITLE
Elasticsearch stats for individual indices

### ISSUE THREAD

**Issue by ashleshmandke** [influxdata/telegraf#5360]
Hi,
Is it possible to plot panel in grafana statistics of a specific index with its memory allocation.please find below snapshot of elasticsearch query with its output. If it is possible please tell me the name of the measurement where I can get and be able to plot-
query on devtools : - GET _cat/indices/sampl*

Output
![image](https://user-images.githubusercontent.com/46951204/52113761-42a66e80-2630-11e9-953b-8ea5984a02bb.png)

Best Regards 
//Ashlesh

**Comment by danielnelson** [comment]
Check the `elasticsearch_indices` measurement,

https://github.com/influxdata/telegraf/tree/release-1.9/plugins/inputs/elasticsearch#measurements--fields
