### ISSUE TITLE
Support client credentials in azure_monitor output

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#5376]
## Feature Request

Add support for the following authentication options to the azure_monitor output:
```
[[outputs.azure_monitor]]
  azure_tenant_id = "foo"
  azure_client_id = "bar"
  azure_client_secret = "baz"
```

These options can be set as environment variables but not in the conf file.

See #5342

### Current behavior:

Options not supported

### Desired behavior:

Add supported

### Use case:

Configuration file should provide a method for plugin configuration without using environment variables.

**Comment by powersj** [comment]
Closing as this is now supported and documented in the output plugin readme.
