### ISSUE TITLE
Prometheus output expiration_interval

### ISSUE THREAD

**Issue by ldelossa** [influxdata/telegraf#5390]
Hello,

I'm trying to understand if expiration_interval occurs asychronously from the agent's poll interval. For example could the following error happen:

Telegraf is set to poll its inputs ever 5 seconds. 
Prometheus output expiration_interval is set to 10s 
Telegraf begins it's second poll at +10 seconds into our scenario
Prometheus output non-deterministically runs it's expiration of metrics just after the second poll and expire metrics until +15 seconds (telegraf does it's next input poll)

**Comment by danielnelson** [comment]
Items are expired before preparing each response, so it is possible to miss data if you have this setting set too low.  I recommend setting it at least several times larger than your client poll interval.
