### ISSUE TITLE
kube_inventory input plug-in missing in build 1.9.4-1

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5393]
### Relevant telegraf.conf:

kube_inventory plug in missing in 1.9.4-1. Was is ever added? why is it showing up in the list of i/p plugins?

**Comment by danielnelson** [comment]
It will be included 1.10.0, we only do bug fixes in the patch releases.  When you read documentation directly from github make sure to switch to the release branch you are using, in your current case check `release-1.9`.

If you would like to take it for a test drive sooner, you can use the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds), would be great to hear your feedback.
