### ISSUE TITLE
[inputs.swap]: Error in plugin: error getting swap memory info: xswdev version mismatch

### ISSUE THREAD

**Issue by nbari** [influxdata/telegraf#5395]
### Relevant telegraf.conf:

    [[inputs.swap]]

### System info:

    Telegraf 1.9.3
    FreeBSD 12.0-STABLE r343881 amd64

### Steps to reproduce:

use swap on ZFS only:

    zfs create -V 64G -o org.freebsd:swap=on -o checksum=off -o compression=off -o dedup=off -o sync=disabled -o primarycache=none tank/swap

Output of `swapinfo`:

```
# swapinfo -h
Device          1K-blocks     Used    Avail Capacity
/dev/zvol/tank/swap  67108864       0B      64G     0%

```

### Expected behavior:

 Get metrics/status from swap

### Actual behavior:

    E! [inputs.swap]: Error in plugin: error getting swap memory info: xswdev version mismatch

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Would it be possible to run this Go program?  Place the following code in a file `main.go`:
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/mem"
)

func main() {
	res, err := mem.SwapMemory()
	if err != nil {
		fmt.Println(err)
		return
	} else {
		fmt.Println(res)
	}
}
```

To run it you will need Go 1.9 or later:
```
go get -d github.com/shirou/gopsutil/mem # downloads to ~/go
go run main.go
```

Can you also run `freebsd-version -k -r -u` and `uname -a`?

**Comment by nbari** [comment]
Hi @danielnelson, this is the output of thecode:

    xswdev version mismatch

The out put of `freebsd-version -k -r -u`:
```
> freebsd-version -k -r -u
12.0-STABLE
12.0-STABLE
12.0-STABLE
```
and `uname -a`:

    FreeBSD dev 12.0-STABLE FreeBSD 12.0-STABLE r343685 DL360  amd64

**Comment by danielnelson** [comment]
I opened an issue with gopsutil, if you could subscribe to that issue I'm sure there will be some follow up questions.

**Comment by nbari** [comment]
Is this fixed in latest version `1.10.0` ?

**Comment by danielnelson** [comment]
Unfortunately no, we need to update gopsutil to v2.19.02.  We don't normally update gopsutil on patch releases unless something major comes up, because it often causes other issues, so this will likely need to wait for 1.11.  I will update master now though, are you using our official packages?

**Comment by nbari** [comment]
I use the port: https://www.freshports.org/net-mgmt/telegraf/

**Comment by danielnelson** [comment]
cc @girgen @W0CHP
