### ISSUE TITLE
kube_inventory input plugin - Missing kubernetes_daemonset measurements

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5399]
Build - https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb (as of 2/10/2018 4:00 pm PST)

I dont see any measurement 'kubernetes_daemonset'. (no measurement, no tags, no fields, nothing).
No exclusions/inclusions. I tried explicitly including them, but of no difference.

**Comment by glinton** [comment]
Do you have any daemonsets in the namespace you've configured? Verify as follows:
```
curl --header "Authorization: Bearer $TOKEN" --insecure https://$K8sAPI/apis/apps/v1beta2/namespaces/$CONFIGURED_NAMESPACE/daemonsets
```

**Comment by vishiy** [comment]
ah ok. I dont have daemon sets by not in the default namespace (since i did not configure ns, i guess itd 'defaut' by default) This goes back to my other issue that got closed. I dont expect to edit telegraf & redeploy whenever they create a namespace. Is there a way to specify 'all' namespaces ?

**Comment by glinton** [comment]
As mentioned in #5400, use `namespace=""`

**Comment by vishiy** [comment]
Thanks @glinton . will try tonight and postback.
