### ISSUE TITLE
kube_inventory input plugin supports only 1 hardcoded namespace

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5400]
Looks this plugin is supported only for 'default' namespace by default (or any other hard coded 1 namespace in the config). This is not a ideal scenario to expect people to have only 1 namespace or automate changing the config to specify a new namespace or redeploy telegraf.

**Comment by gunnaraasen** [comment]
Telegraf allows multiple blocks of the same plugin to be specified. In this case, setting up multiple kube-inventory inputs in the config would cover multiple namespaces.

```
[[inputs.kube_inventory]]
  url = "https://127.0.0.1"
  namespace = "default"
[[inputs.kube_inventory]]
  url = "https://127.0.0.1"
  namespace = "production"
[[inputs.kube_inventory]]
  url = "https://127.0.0.1"
  namespace = "staging"
```

**Comment by glinton** [comment]
gunnaraasen is correct, use multiple input blocks if you desire to collect object stats for multiple namespaces. You may want to add a `resource_exclude` to the others for resources that are not namespaced such as `nodes` and `persistentvolumes` to prevent duplicates.

**Comment by vishiy** [comment]
@gunnaraasen @glinton 

I dont expect to edit telegraf & redeploy whenever they create a namespace. Is there a way to specify 'all' namespaces ?

**Comment by glinton** [comment]
Try `namespace=""`

**Comment by vishiy** [comment]
@glinton - will try tonight and post back.
