### ISSUE TITLE
kube_inventory input plugin - kubernetes_node allocatable_cpu_cores is always 0

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5401]
This measurement seems to be always zero.

kube_inventory input plugin - kubernetes_node allocatable_cpu_cores is always 0

**Comment by glinton** [comment]
Can you verify you have that set in your nodes, check the `.items[].status.allocatable.cpu` field of the node.

Run the following:
```
curl --header "Authorization: Bearer $TOKEN" --insecure https://$K8sAPI/api/nodes
```

Pipe it to [`jq`](https://stedolan.github.io/jq/) if you have it `| jq .items[].status.allocatable.cpu` and paste the results

**Comment by vishiy** [comment]
all our nodes have allocatable. @glinton 

 "status": {
        "capacity": {
          "alpha.kubernetes.io/nvidia-gpu": "0",
          "cpu": "2",
          "memory": "7124892Ki",
          "pods": "110"
        },
        "allocatable": {
          "alpha.kubernetes.io/nvidia-gpu": "0",
          "cpu": "2",
          "memory": "7022492Ki",
          "pods": "110"
        }

**Comment by glinton** [comment]
Thanks, what version of kubernetes are you running?

**Comment by vishiy** [comment]
Thanks. @glinton 1.12.4

**Comment by glinton** [comment]
@vishiy I've still been unable to reproduce this. Can you try again with [this build from our CI](https://28325-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.10.0~11d02039-0_amd64.deb) and paste the output?
If you need a different package, this one is a linux amd64 `.deb`, let me know.

**Comment by vishiy** [comment]
@glinton i will try and let you know.

**Comment by danielnelson** [comment]
@vishiy Did you get this working?

**Comment by vishiy** [comment]
@danielnelson - Works for me in the later builds. Thanks.
