### ISSUE TITLE
[inputs/nstat] error on snmp6 when ipv6 is disabled

### ISSUE THREAD

**Issue by deric** [influxdata/telegraf#5403]
### Relevant telegraf.conf:

```
[[inputs.nstat]]
```
### System info:

Debian 4.9.110-3+deb9u4 (2018-08-21), Telegraf 1.9.4

### Steps to reproduce:

1. Linux kernel without IPv6 support ` ipv6.disable=1`

### Expected behavior:

Silently ignore missing `/proc/net/snmp6`.

### Workaround

~~redirect `snmp6` to `snmp` and then ignore it.~~

~~`[[inputs.nstat]]`~~
~~`  proc_net_snmp6 = "/proc/net/snmp"`~~
~~`  namedrop = "snmp6"`~~

Not a good idea. Incorrectly parsed `snmp6` fields with enormous cardinality:

```
> SHOW FIELD KEY CARDINALITY FROM nstat
name: nstat
count
-----
389040
```

### Actual behavior:

```
E! [inputs.nstat]: Error in plugin: open /proc/net/snmp6: no such file or directory
```

**Comment by danielnelson** [comment]
As a workaround you can add this option:
```
[[inputs.nstat]]
  proc_net_snmp6 = "/dev/null"
```

**Comment by deric** [comment]
@danielnelson Right, that's much better solution. 

Just curious, `nstat` offers JSON output, why not use that?
```
nstat -a --json
```
It gives pretty much the same output, except all metrics are merged into single category (no `snmp`, `snmp6` or `nestat` namespace) and you don't have to parse 3 files from disk.

Is a PR witch such change acceptable for `telegraf`? Or would  you prefer keeping names of metrics the same way?

**Comment by danielnelson** [comment]
It is faster to read 3 files than to exec a binary, and then of course using it would add a dependency on the nstat binary.  If you strace nstat you can see it opens these 3 files as well.

On naming, we try to keep everything backwards compatible so as to not break any dashboard or alerts.

**Comment by deric** [comment]
Sure, makes sense. Thanks for explanation!
