### ISSUE TITLE
Proxmox VE 5 input support

### ISSUE THREAD

**Issue by jhoustek23** [influxdata/telegraf#5405]
## Feature Request
Proxmox VE support

### Proposal:
Similiar to VMware stats

### Current behavior:
Currently I am using UDP or collectd influxdb support in Proxmox, but I'd like to have telegraf just like on rest of my infrastructure (systems, ceph, k8s, etc.) 

### Desired behavior:
I'd like to have overall cluster status, hosts stats and VM stats.

### Use case: [Why is this important (helps with prioritizing requests)]
We are now  running multiple instruments to collect metrics from our infrastructure (prometheus, collectd, udp, telegraf) to influxdb and trying to make it simplier to manage.

**Comment by victorhooi** [comment]
+1 to this for me!

**Comment by sjwang90** [comment]
The [Proxmox plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/proxmox) was added recently. Please re-open if it does not fit your needs.
