### ISSUE TITLE
Agent ignoring collection interval/precision MS

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#5410]
[agent]
  ## Default data collection interval for all inputs
  interval = "10000ms"
  ## Rounds collection interval to 'interval'

precision not set and when starting agent,  log indicates Interval=10s and epoch timestamp is 10 digits (seconds) and not 13 digits (ms). Trying to get MS in output timestamp. Tried precision="1ms" but no luck?

**Comment by glinton** [comment]
I'm not sure what you are expecting here, 10000ms is 10s so the collection interval is correct. What is your configured output where you are seeing 10 digits, when using the `[[outputs.file]]`, I see a timestamp like `1549993906501000000`.

You can read more about the agent configuration [here](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent)
