### ISSUE TITLE
Add Modbus Input Plugin

### ISSUE THREAD

**Issue by meowcat** [influxdata/telegraf#5412]
## Feature Request

Modbus plugin

### Proposal:

Is there a timeline to get fdamador's Modbus plugin #4623 fixed and integrated, or any other Modbus plugin in development? It would be very useful.

### Current behavior:

There is no Modbus plugin. An existing plugin was attempted to be merged, but showed issues in CircleCI (that I am not in a position to understand or fix).

### Desired behavior:

There is a Modbus plugin

### Use case: 

To get Modbus data from my PLC into InfluxDB, I currently run ioBroker, which is huge and a pain to configure. It kinda goes around three corners to just send my values to InfluxDB, since I don't need any of its other features. I think the task I want to solve is rather simple, and I can't quite see why there is no plugin for such an incredibly widespread protocol. 

Other options I have found to get Modbus data into a TSDB are: 
* using https://github.com/GridProtectionAlliance/openHistorian which is running SNAPDB in the background, but the package is a ton of overhead, intended specifically for electrical grids, and I couldn't get the Modbus driver to work.
* not using Modbus, but sending out my data via MQTT, which is an annoyance to do on the PLC

**Comment by glinton** [comment]
Have you considered forking his work and finishing it up? We are just waiting for the feedback items to be addressed so tests pass before reviewing it and moving forward. Also, because of no other interest expressed in it (no +1 reactions on the original pr comment), it is a lower priority for us to push forward.

**Comment by meowcat** [comment]
> Have you considered forking his work and finishing it up?

I understand that Go is just another programming language and probably even a useful one to know, but I feel it would be a bit of overhead to jump into learning Go and its associated build systems etc, just for this.

**Comment by meowcat** [comment]
To me it seems like it's just missing the goburrow/modbus dependency somehow...?

**Comment by garciaolais** [comment]
@meowcat   I agree with you but I think that the modbus plugin needs to fix some things  .

you can check my comments  https://github.com/influxdata/telegraf/pull/4623#issuecomment-465679775

**Comment by fdamador** [comment]
Gents.  I've updated the plugin to address @garciaolais inputs.  If you are still having issues, perhaps we can troubleshoot together for the best outcome.  Once this plugin is fixed, then the same code can be used for the Modbus Output plugin.

**Comment by Pradeep-raj544** [comment]
@garciaolais @danielnelson 
i got plugin only for tcp and rtu ,
any one developed modbus input plugin for RTU over TCP if any please could you share with me.
thank you
