### ISSUE TITLE
The error message is truncated

### ISSUE THREAD

**Issue by masterofcloud1** [influxdata/telegraf#5415]
### Relevant telegraf.conf:
N/A

### System info:

Telegraf v1.6.2 on ubuntu xenial

### Steps to reproduce:

N/A

### Expected behavior:
See all the error message 
### Actual behavior:
See a truncated error message
### Additional info:

I've written my own inputs.exec plugin, and sometimes I'm getting the following error:
E! Error in plugin [inputs.exec] : metric parse error: expected field at offset X: _data_ ...
I know i have a bug, but I can't check what it is because X is very large, way larger than the message itself. The message is truncated by ... and I can't see what the error is.

**Comment by glinton** [comment]
Can you add the exec portion of your config file, specific command isn't as important as the data_format. Also, if it's not sensitive, can you paste an example input line that is produced by your command. I'd like to reproduce and debug this.

**Comment by danielnelson** [comment]
This should be improved by the upcoming fix for #4743, let's merge these two issues.

**Comment by masterofcloud1** [comment]
@glinton  Well, sometimes you want to create a massive number of metrics, and sometimes - you didn't create one correctly according to the line protocol. To debug this, I need to see that metric. But when the message is truncated it is impossible...

**Comment by glinton** [comment]
masterofcloud1, rather than print the entire message, would it suffice to print the message at the offset with some amount of contextual buffer?

Eg:
```
E! failed to parse. something broke. offset 12345. ...asdf=1,sdfg=2• 123456789000000000
```

**Comment by masterofcloud1** [comment]
That would be great @glinton !
