### ISSUE TITLE
Customize the makefile

### ISSUE THREAD

**Issue by littlespace** [influxdata/telegraf#5419]
Hi,

Is it possible to just build telegraf with couple of plugins that i need? I do not wanna compile all plugins that i am not going to use.

Thanks

**Comment by glinton** [comment]
There currently isn't an automated way to accomplish this, you'll have to manually modify [plugins/inputs/all/all.go](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/all/all.go), removing all plugins you don't want, then build. More discussion on a similar though in #1717

**Comment by littlespace** [comment]
Thanks, that works for me.
