### ISSUE TITLE
Key conflict when routing to different outputs using tagpass

### ISSUE THREAD

**Issue by pvnick** [influxdata/telegraf#5426]
### Relevant telegraf.conf:

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "server_stats"
  [ouputs.influxdb.tagpass]
    job_name = ["server_stats"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "tsm_stats"
  [ouputs.influxdb.tagpass]
    job_name = ["tsm_stats"]

### System info:

Telegraf 1.9.4 (running in docker)

### Steps to reproduce:
Launch with attached config; i.e. multiple influxdb outputs routed using different values of the same tagname

### Expected behavior:

Should route to expected output based on the value of the job_name tag

### Actual behavior:

I get the following error:

[telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, toml: line 96: key `job_name' is in conflict with line 90

**Comment by danielnelson** [comment]
I believe it is because of this typo:
```diff
- [ouputs.influxdb.tagpass]
+ [outputs.influxdb.tagpass]
```

**Comment by pvnick** [comment]
Doh! Thanks so much for checking and finding that.
