### ISSUE TITLE
how to set precision for influx using telegraf

### ISSUE THREAD

**Issue by sanx84** [influxdata/telegraf#5430]
I am inserting data to influxdb using telegraf with data_type="influx". The problem I am having in inserting time format. It default inserts time till "ns" and i want my time in YYYY-MM-DD HHMMSS format.
I set precision="s" but it didn't make any difference.
Can you please tell me how to define time format in telegraf.

**Comment by danielnelson** [comment]
This isn't something Telegraf is involved in, time in InfluxDB is always in nanosecond resolution and you can change the way it is displayed when using the `influx` cli utility:

https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#how-do-i-make-influxdb-s-cli-return-human-readable-timestamps

The `precision` option for the Telegraf agent control rounding of data, if you would like to use it then don't forget to include a value as well: `precision = "1s"`
