### ISSUE TITLE
[Feature Request] Provide plugin to consume Cloud Foundry metrics into Telegraf via the Loggregator API

### ISSUE THREAD

**Issue by trevorwhitney** [influxdata/telegraf#5432]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

We are proposing a plugin that will allow Telegraf to consume metrics from the Cloud Foundry platform. Cloud Foundry uses an open source API for Metrics and Logs known as "Loggregator". In more recent versions of the Cloud Foundry platform, a new pattern has been introduced known as the [Loggregator Forwarder Agent](https://github.com/cloudfoundry/loggregator-agent-release). This architecture allows logs and metrics coming off a single VM to be multiplexed to N number of downstream consumers who implement the Loggregator API. By developing a plugin for Telegraf that implements this API, we hope to enable Cloud Foundry operators to deploy a Telegraf process to each of their Cloud Foundry VMs, thus allowing them to harness the power of Telegraf and output their metrics to any of the many support Telegraf outputs.

### Current behavior:

This plugin does not currently exist.

### Desired behavior:

This plugin exists and can be turned on for anyone using Telegraf.

### Use case: [Why is this important (helps with prioritizing requests)]

A Cloud Foundry operators can deploy a Telegraf process to each of their Cloud Foundry VMs and export metrics to any of the Telegraf outputs.

**Comment by trevorwhitney** [comment]
We are currently working on a PR to add this functionality.

**Comment by powersj** [comment]
PRs were closed, and will close this issue as well. If this is something that wants to be revisited in the future, someone can add a comment detailing why and re-post one of the PRs.
