### ISSUE TITLE
[Feature Request] Add histogram aggregator compatible with Prometheus

### ISSUE THREAD

**Issue by kitemongerer** [influxdata/telegraf#5435]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

We are proposing a new aggregator plugin that will aggregate gauge metrics into Prometheus histograms. This will allow the aggregation of asynchronous metrics from any input into Prometheus compatible histograms (that can be used with any output but are designed specifically for the Prometheus output).

### Current behavior:

This plugin doesn't currently exist. The existing histogram aggregator does not output `Histogram` type metrics. It also doesn't keep track of sum or count.

### Desired behavior:

A histogram aggregator that can build Prometheus compatible histograms based on gauge metrics. 

### Use case:

Aggregate asynchronous gauge metrics to reduce output size and avoid earlier values being overwritten. Example: an app emits a gauge metric for request duration each time a request is made to its API. Using an output like the Prometheus output where only the last gauge value received is report, there will be a large amount of metric loss. Additionally, if the app is used heavily, there could be a huge number of these metrics making aggregation important.

**Comment by danielnelson** [comment]
Instead of a new plugin, what about just adding a `count` and `sum` field to the existing histogram aggregator and setting the ValueType to Histogram?

**Comment by kitemongerer** [comment]
@danielnelson That's the approach we tried to take at first but the way the current histogram is implemented makes it a little painful to add sum. So we ended up changing quite a bit of code. I'd be happy to replace the current histogram aggregator instead of adding a new one. We just weren't sure if these changes would break the existing use cases surrounding the histogram aggregator.

**Comment by danielnelson** [comment]
It would be better to update the current plugin.  Preferably the changeset would be small, since that makes it easier to review, but if the changes are required then we can make them.

**Comment by trevorwhitney** [comment]
@danielnelson just to clarify, is it ok to make a breaking change to the existing histogram aggregator? We're happy to adapt our changes to the existing aggregator, but out aggregator stores values using a different field structure. Our aggregator uses the "le" value as the field name, which is the structure that the `prometheus_client` output plugin is looking for. The existing plugin uses the "le" value as a tag. The existing plugin also stores values in a field called "field_name_bucket", which is not how the `prometheus_client` output is configured to look for histogram. Our understanding was that the output plugin appends "_bucket" itself for metrics of type histogram (with the expected field format). These seem like big enough changes that they would break anyone relying on the current behavior of the existing aggregator.

**Comment by danielnelson** [comment]
No, we wouldn't be able to make these kind of changes without adding backwards compatibility options.

It seems the real cause of problems is less the aggregator and more the prometheus_client output's transformations.  I'd like to rework this, along with the prometheus input, I've put one of my ideas in #4415, but I have other changes I would like to make to both input and output transformations.  I'll update this issue later this week and then we can discuss the details.

**Comment by trevorwhitney** [comment]
@danielnelson it does seem like there is a lack of a cohesive opinion around how histograms should be stored in the Telegraf accumulator. I like your idea of working on coalescing around a single strategy, but that also seems like it will require a much larger set of changes, which means a longer development time. Do you think we could add this as a separate aggregator in the meantime, and remove it when a long term strategy has been decided on?

**Comment by danielnelson** [comment]
No this isn't something we would do.  I haven't fully researched this, but what if we add sum + count now, which I think would be pretty quick, and leave the TYPE handling until later.  I believe if we did this the current histogram aggregator would output histograms in the correct format (`le` being a tag is correct since it will then become a label in the prometheus output) but as TYPE untyped.  My understanding is that the TYPE doesn't impact promql queries, though I'm no expert, so this aspect seems less urgent.

**Comment by robertjsullivan** [comment]
I chatted with @trevorwhitney and I think we're going to wait for https://github.com/influxdata/telegraf/issues/4415 to be completed.  We'll keep an eye out for the updates and re-evaluate the prometheus histogram capability then.

**Comment by danielnelson** [comment]
#4415 is closed now, but we should check again once #6703 is merged, it should make the existing histogram aggregator compatible with the prometheus output.

**Comment by danielnelson** [comment]
Please try out histogram aggregator along with `metric_version = 2` in the prometheus input/output, and  if we need any changes we will reopen this issue.
