### ISSUE TITLE
Add exec plugin as output

### ISSUE THREAD

**Issue by gena01** [influxdata/telegraf#544]
Would be nice to be able to execute a script that would take json metrics content and would send it to where it needs to go. (Most of these would help with various http/https api integrations)

**Comment by sparrc** [comment]
@gena01 were you thinking via stdin?

**Comment by gena01** [comment]
Precisely. This could work nicely to proxy metrics to a system currently not supported via native output plugin. This way an external script can reformat and forward these metrics where it needs to go.

**Comment by sparrc** [comment]
@gena01 Would line-protocol work? Otherwise we would need to convert metrics back to JSON from line-protocol, which wouldn't be a huge deal either.

**Comment by gena01** [comment]
Sure. Might even be better in some use cases (easier to parse?).

**Comment by danielnelson** [comment]
Added in #6267
