### ISSUE TITLE
telegraf cannot send docker‘s data to influxdb

### ISSUE THREAD

**Issue by lovexiongmao** [influxdata/telegraf#5443]
### Relevant telegraf.conf:
 [[outputs.influxdb]]
     urls = ["http://192.168.1.105:8086"]
     database = "telegraf"
     retention_policy = ""
     write_consistency = "any"
     timeout = "5s"

[[inputs.docker]]
     endpoint = "unix:///var/run/docker.sock"
     gather_services = false
     container_names = []
     container_name_include = []
     container_name_exclude = []
     timeout = "5s"
     perdevice = true
     total = false
     tag_env = ["JAVA_HOME", "HEAP_SIZE"]
     docker_label_include = []
     docker_label_exclude = []

### System info:
telegraf version: 1.9.4
OS: centos7.6

### Steps to reproduce:
1.  I installed telegraf and influxdb 
2. I configured telegraf. conf to gather the OS data and docker data

### Expected behavior:
It should be possible to query the docker data in influxdb, but in fact, there is no docker data in the influxdb

### Additional info:
It has system data in the influxdb database, but it does not have docker data
my influxdb version is v1.7.4
I exec “telegraf -config /etc/telegraf/telegraf.conf -input-filter docker -test” in the command line. And there is some docker data returned. such as:
> docker_container_blkio,annotation.io.kubernetes.container.hash=c42fdbe,annotation.io.kubernetes.container.restartCount=9,annotation.io.kubernetes.container.terminationMessagePath=/dev/....

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
If Telegraf is collecting docker metrics in the container and is also sending other metrics successfully it is very unlikely that it would skip the docker metrics.  Consider turning on a `file` output to see what is being written when running normally and the `internal` input to see per plugin metric counts.

It will be best to ask over at the [InfluxData Community](https://community.influxdata.com) site for further help troubleshooting.

**Comment by lovexiongmao** [comment]
> If Telegraf is collecting docker metrics in the container and is also sending other metrics successfully it is very unlikely that it would skip the docker metrics. Consider turning on a `file` output to see what is being written when running normally and the `internal` input to see per plugin metric counts.
> 
> It will be best to ask over at the [InfluxData Community](https://community.influxdata.com) site for further help troubleshooting.

I've done what you said. i turn on file output and in the output file, still no docker metrics, only the system metrics have be written.

**Comment by danielnelson** [comment]
Have you checked the logs?  Make sure there are no errors and that the docker plugin is loading when Telegraf first starts.

**Comment by lovexiongmao** [comment]
> Have you checked the logs? Make sure there are no errors and that the docker plugin is loading when Telegraf first starts.

I have configured the conf file like below

>[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = ture
  quiet = false
  logfile = "cyktelegraf.log"
  hostname = ""
  omit_hostname = false
>

And i restart the telegraf.  this is no cyktelegraf.log generated.  and this is no any log file under the /var/log/telegraf directory. i very sure my docker is loading when telegraf is starting. my docker version is 18.06.1-ce.  Does this have anything to do with my docker version?

**Comment by danielnelson** [comment]
Try using a full path: `logfile = "/var/log/telegraf/telegraf.log"`, or when this option is unset the logs should be sent to `/var/log/syslog` on Centos 7 (sorry about the confusing /var/log/telegraf, this isn't used with systemd).

**Comment by lovexiongmao** [comment]
> Try using a full path: `logfile = "/var/log/telegraf/telegraf.log"`, or when this option is unset the logs should be sent to `/var/log/syslog` on Centos 7 (sorry about the confusing /var/log/telegraf, this isn't used with systemd).

Very thank you for help ,I checked every log file In the '/var/log/' directory
 and finally get the problem that is about the Permission from the 'messages' log file.  then i  add `telegraf` user to `docker` group, as explained here

```
$ sudo usermod -aG docker telegraf
``` 
Finally it works。thank you again。
