### ISSUE TITLE
Haproxy SLI for request error rate

### ISSUE THREAD

**Issue by kshnsink** [influxdata/telegraf#5445]
### Proposal:
Currently, Haproxy input plugin sends metrics for different http response status codes seperately. Although, since there's lack of ability to actually divide 2 series in InfluxDB, having seperate count for 2xx and 5xx cannot be used as it is to calculate SLIs like request error ratio in Grafana.

### Current behavior:
No aggregate value for `request error ratio = ( 1 - (http_response.5xx / http_response.total) ) * 100`

### Desired behavior:
Add a field in http input plugin with key as `request_error_rate` that does `(http_response.5xx) / (http_response.2xx + http_response.3xx + http_response.4xx + http_response.5xx)`

### Use case:

In a SOA, it is very important to measure service's key SLI one of them being error rate. This feature will allow users who use HAproxy as load-balancer for their services to track this metric. [Service Level Objective](https://landing.google.com/sre/sre-book/chapters/service-level-objectives/#indicators)

**Comment by danielnelson** [comment]
These composite values can be calculated at query time, though in Grafana you will need to switch to the text query builder and granted it is quite painful.  I hope this can be improve on the display side, but we are also looking to add processors and aggregators that can do ad-hoc calculations in Telegraf before writing to InfluxDB.

Another option you could explore is to use a continuous query to compute the value.
