### ISSUE TITLE
Filecount: directory permission denied blocks input regardless of recurse parameter

### ISSUE THREAD

**Issue by jnguiot** [influxdata/telegraf#5449]
### Relevant telegraf.conf:
> [[inputs.filecount]]
>    directory = "/tmp/foo/"
>    name = "aaa"
>    recursive = false

### System info:
Telegraf 1.9.4 (git: HEAD 4da8d0a4)
Ubuntu 16.04

### Steps to reproduce:
1. create this architecture in /tmp:
> foo
> |-- [-rw-rw-r--]  aaa
> `-- [d---------]  bar

   `foo` and `bar` are directories
   `aaa` is a regular file
   `bar` cannot be read by telegraf user (here, it is simulated by a 000 chmod)
2. Create the file `/tmp/aaa.conf` with this content:
> [[inputs.filecount]]
>   directory = "/tmp/foo/"
>   name = "aaa"
>   recursive = false
3. execute config file: `telegraf --config /tmp/aaa.conf --test`

### Expected behavior:
Telegraf process should return: 
    > filecount,directory=/tmp/foo/,host=computer count=1i 1550582182000000000

### Actual behavior:
Telegraf process returns:
2019-02-19T13:17:01Z E! [inputs.filecount]: Error in plugin: open /tmp/foo/bar: permission denied

### Additional info:
Since recurse is set to false, telegraf should not care about subdirectories, especially, it should not go into error. 
I am still looking for a workaround.

**Comment by glinton** [comment]
A workaround is to use the nightly as this has been resolved for 1.10

**Comment by jnguiot** [comment]
Ok. Thank you for the quick bugfix!
