### ISSUE TITLE
Extend MySQL plugin for table metric, query result metric

### ISSUE THREAD

**Issue by kureikain** [influxdata/telegraf#545]
Hi,

Is it possible to extend functionality of MySQL to report more detail metric on table level, thing like:

- record counts
- last write

Or even run a sql query and record value (yes, sound like an use case for `exec` plugin)

This use case is special for me because I have those kind of checks in our system like 'check query that runs longer than 2 minutes', find table that have no write in 15 minutes...

Because it's special for me I'm not sure if only me needs it or community may need it, if that's the case, and people like it, we may discuss something.

**Comment by sparrc** [comment]
dupe, see #403
