### ISSUE TITLE
restart needed for system.ncpus to update

### ISSUE THREAD

**Issue by caapos** [influxdata/telegraf#5451]
This https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/system.go#L37 calls a GO system function https://golang.org/pkg/runtime/#NumCPU, which has undesired bahaviour. To force the system.ncpus metric to update in dashboard after change in OS, it is needed to restart telegraf process.

**Comment by danielnelson** [comment]
We should probably start using gopsutil for this, but they are currently getting cpu count in the same way.

https://github.com/shirou/gopsutil/blob/9294781cc96294e42b8cb19de82a0ff3b19bb056/cpu/cpu.go#L70-L72

Can you describe what type of system you have that has changes to the cpu count, so we can make a good argument for the necessity of this code, and then I'll open an issue on gopsutil.

**Comment by caapos** [comment]
We are running our monitored environments on CentOS virtual machines, ufortunately I do not have enough information about the underlying system configuration, but the parameters like te number of CPUs or RAM of individual VMs can be changed without the need to restart the VM. If you need more information, please give me a specific question and I will try to answer.

**Comment by danielnelson** [comment]
Do you know what the hypervisor is?

**Comment by caapos** [comment]
I will find out and send it to you, but the bug would reproduce on ANY hypervisor, because of the nature of the code for checking the number of CPUs.

**Comment by danielnelson** [comment]
True, I'm just trying to make the use case a little more concrete with a specific example.  I just looked up how to do this with kvm + libvirt and was able to do this in a test VM, so I think this will be a good enough example and also helpful for testing.

**Comment by caapos** [comment]
Thanks a lot, I will give you specific information about the hypervisor when the rest of our team is awake :)

**Comment by danielnelson** [comment]
Support for updating the number of CPUs dynamically has been added, though we only have Linux support for now.

**Comment by Lomanic** [comment]
> we only have Linux support for now

FYI [darwin](https://github.com/shirou/gopsutil/blob/58dc3b28aaabbc5d4fdd09a8146279276305aa10/cpu/cpu_darwin.go#L89-L103) and [windows](https://github.com/shirou/gopsutil/blob/58dc3b28aaabbc5d4fdd09a8146279276305aa10/cpu/cpu_windows.go#L226-L255) are now also supported in gopsutil.

**Comment by danielnelson** [comment]
Awesome job @Lomanic, Telegraf really couldn't exist without you and @shirou's hard work on gopsutil.

So, if I'm reading this correctly, in Telegraf 1.12.0 (coming soon) we will be using gopsutil v2.19.7 and that should give us Linux/Darwin support but Windows will need to wait for 1.13.

**Comment by Lomanic** [comment]
Thanks for the kind words, appreciated.

Indeed you're right, gopsutil v2.19.7 includes support for both linux and darwin but only v2.19.8+ will include the windows implementation.
