### ISSUE TITLE
inputs.pgbouncer  Error in plugin: ERROR: unsupported pkt type: 80 (SQLSTATE 08P01)

### ISSUE THREAD

**Issue by urusha** [influxdata/telegraf#5455]
### Relevant telegraf.conf:
```
[[inputs.pgbouncer]]
    address = "postgres://telegraf:telegraf@localhost:6432/pgbouncer"
```

### System info:
debian 9 amd64, telegraf 1.9.1
tested with 
https://dl.influxdata.com/telegraf/releases/telegraf_1.9.1-1_amd64.deb
https://dl.influxdata.com/telegraf/releases/telegraf_1.9.4-1_amd64.deb

### Steps to reproduce:

1. Use https://dl.influxdata.com/telegraf/releases/telegraf_1.9.0-1_amd64.deb with above pgbouncer input. No errors.
2. Upgrade to https://dl.influxdata.com/telegraf/releases/telegraf_1.9.1-1_amd64.deb . See errors

### Expected behavior:
no errors

### Actual behavior:
errors in log:
```
E! [inputs.pgbouncer]: Error in plugin: ERROR: unsupported pkt type: 80 (SQLSTATE 08P01)
E! [inputs.pgbouncer]: Error in plugin: EOF
```
### Additional info:
pgbouncer log:
```
ERROR unsupported pkt type: 80
WARNING C-0x7f3e81e60438: pgbouncer/telegraf@127.0.0.1:39156 Pooler Error: unsupported pkt type: 80
WARNING C-0x7f3e81e60438: pgbouncer/telegraf@127.0.0.1:39156 Pooler Error: bad pkt
```

**Comment by danielnelson** [comment]
This appears to have happened when we updated pgx to add TLS support, I opened this issue upstream:

https://github.com/jackc/pgx/issues/512

**Comment by vauboy** [comment]
Seems lika already fixed in https://github.com/influxdata/telegraf/issues/3253

**Comment by danielnelson** [comment]
This has broken since that issue was originally done.  A fix has been applied upstream but is not yet part of a released version.

**Comment by ricky-ticky** [comment]
telegraf_1.10.2-1_amd64.deb  pgbouncer plugin still broken

**Comment by glinton** [comment]
ricky-ticky, that's correct. As daniel pointed out, the upstream fix hasn't been included in a [released version](https://github.com/jackc/pgx/releases) yet.

**Comment by jfduque** [comment]
Still broken in telegraf_1.10.3-1_amd64.deb
