### ISSUE TITLE
Ping plugin on large number of hosts fails with "too many open files"

### ISSUE THREAD

**Issue by eimamagi** [influxdata/telegraf#5459]
### Relevant telegraf.conf:

**cat /etc/telegraf/telegraf.d/ping.conf**
[[inputs.ping]]
urls = ["host1"]
ping_interval = 60.0
...
[[inputs.ping]]
urls = ["host1000"]
ping_interval = 60.0

same result with:
**cat /etc/telegraf/telegraf.d/ping.conf**
[[inputs.ping]]
urls = ["host1",...,"host1000"]
ping_interval = 60.0

### System info:

**cat /etc/redhat-release**
CentOS Linux release 7.5.1804 (Core)
**uname -a**
Linux mon 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**rpm -q telegraf**
telegraf-1.2.1-1.x86_64

We generously increased number of open files for telegraf user:
**cat /etc/security/limits.d/30-telegraf.conf**
telegraf               soft    nofile          1000000
telegraf               hard    nofile          1000000

### Steps to reproduce:

1. systemctl start telegraf
2. syslog is full of messages such as:
Feb 20 23:48:20 mon telegraf: 2019-02-20T22:48:20Z E! ERROR in input [inputs.ping]: , open /dev/null: too many open files
Feb 20 23:48:20 mon telegraf: Fatal error processing ping output
Feb 20 23:48:20 mon telegraf: 2019-02-20T22:48:20Z E! ERROR in input [inputs.ping]: , pipe2: too many open files
Feb 20 23:48:20 mon telegraf: Fatal error processing ping output

### Expected behavior:

Ping plugin documentation doesn't have any limits defined so we expected that pinging 1000 or so addresses from one host shouldn't be a problem.

### Actual behavior:

Ping plugin is unable to ping all defined urls with defined interval of 60s due to "too many open files" error. We didn't investigate further why limit of 1000000 is not sufficient for pinging 1000 hosts. When we lowered number of urls to 250 telegraf didn't raise error anymore and performed monitoring successfully.

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
This issue will need to be solved by https://github.com/influxdata/telegraf/issues/2833.

So far as the limit not being enough, I think with systemd the `/etc/security/limits.d` method does not work to increase the file limit, and instead a line `LimitNOFILE=10000` needs to be added to the service file `/usr/lib/systemd/system/telegraf.service` under `[Service]`.  Let me know if this helps and we can add it to the README

**Comment by eimamagi** [comment]
works like a charm, thanks for a quick response

**Comment by danielnelson** [comment]
I added this note to the ping README: f8cc9719a237ab221594a7ac2c42c4cc18d1859a

BTW, if I recall correctly this version of Telegraf sometimes crashes when exec'ing many child processes, I think it was a bug in the version of Go it was compiled with, if you run into this you will want to upgrade to a newer version.
