### ISSUE TITLE
The JSON Parser Should Support Configuring a Timezone

### ISSUE THREAD

**Issue by ddrinka** [influxdata/telegraf#5463]
## Feature Request
I have a data source that logs JSON data in local time, with no timezone indicator in the log.  The data is parseable by the JSON Parser, but the timestamps are written to the database as UTC rather than as local timestamps.

### Proposal:
The [Grok Parser](https://github.com/influxdata/telegraf/blob/f8cc9719a237ab221594a7ac2c42c4cc18d1859a/plugins/parsers/grok/parser.go) is a useful prototype of how I expect to be able to configure a timezone.

I'd like to add a clone of [internal.ParseTimestamp](https://github.com/influxdata/telegraf/blob/f8cc9719a237ab221594a7ac2c42c4cc18d1859a/internal/internal.go#L342) to accept a timezone string as well as a time format, and use the new function with an optional configuration parameter in the JSON Parser.

I plan to contribute a PR for this functionality.

**Comment by danielnelson** [comment]
Are these unix epoch timestamps like `1550794308` or human readable timestamps more like `Feb 21 11:27:02`?

**Comment by ddrinka** [comment]
Human readable. Unix epoch timestamps should by definition be UTC.

**Comment by danielnelson** [comment]
Yes agreed.  This sounds great, just call the new option `json_timezone`?

**Comment by ddrinka** [comment]
@danielnelson Great, this is working fine in production for me.  Attached is the PR.
