### ISSUE TITLE
Parsing `ENV` config vars delivered in `json` block (running on Cloud Foundry)

### ISSUE THREAD

**Issue by aegershman** [influxdata/telegraf#5469]
I am trying to run the telegraf binary on [Cloud Foundry (or Heroku, etc.). I am investigating how configuration credentials could be passed into the `telegraf.conf`](https://docs.cloudfoundry.org/devguide/services/application-binding.html) using service bindings. This will let me pass credentials to the `telegraf` app as

As the telegraf documentation states, [I can reference env vars `"$LIKE_THIS"`, which works as expected.](http://docs.influxdata.com/telegraf/v1.9/administration/configuration/#environment-variables)

However, I'm trying to parse [environment variables delivered in a JSON block, with the key `VCAP_SERVICES`. I've got an example linked here.](https://github.com/aegershman/telegraf-on-cloudfoundry/blob/master/telegraf/telegraf-env-in-user-provided-service.conf#L20-L41).

If you were to `ssh` onto the container `telegraf` is running on and ran `env`, you'd see this:

```
VCAP_SERVICES={"user-provided":[{
   "label": "user-provided",
   "name": "user-provided",
   "tags": [
   ],
   "instance_name": "user-provided",
   "binding_name": null,
   "credentials": {
     "telegraf_ping_target": "amazon.com"
   },
   "syslog_drain_url": "",
   "volume_mounts": [
   ]
}]}
```

In my `telegraf.conf`, I'd like to reference the `telegraf_ping_target` like so:

```
  ## List of urls to ping
  urls = [
    "$VCAP_SERVICES.user-provided[0].credentials.telegraf_ping_target"
    ]
```

This is a long-shot, but is the ability to reference this possible without using a third-party binary like `jq`?

Any thoughts?

**Comment by danielnelson** [comment]
No sorry, this isn't possible and I don't think we would add it either.  You will need to run a script before starting Telegraf to expand the data out into individual environment variables.

**Comment by aegershman** [comment]
Gotcha, thanks for the fast response and straight-forwardness.

**Comment by aegershman** [comment]
For any future interested parties, I did find a way to make this work incredibly well using [`vcap_squash`](https://github.com/cloudfoundry-community/vcap-squash)

Demos and examples:

https://github.com/aegershman/telegraf-on-cloudfoundry
