### ISSUE TITLE
Statsd input can not process metric names with a colon in it

### ISSUE THREAD

**Issue by entertainyou** [influxdata/telegraf#547]
An example `foo,url=http://www.google.com:10|ms`, I found no restriction on metric name in https://github.com/b/statsd_spec, and my output backend is influxdb, which can accept colon in metric name.

It would be great if `telegraf` can support colon in metric name

**Comment by sparrc** [comment]
good point, shouldn't be a hard fix

**Comment by sparrc** [comment]
actually this isn't trivial because of #354, will have to do some checking on each ":" split if the resulting string looks like a statsd metric.

**Comment by dgassaway** [comment]
Colons are not really valid in statsd format.  The spec page says (although it's not a very tight definition):

> Metrics are generally of the form metric_name:value|type

Metric names with colons will also be considered malformed input and dropped in the reference https://github.com/etsy/statsd server

**Comment by danielnelson** [comment]
I think it is illegal as well, when this is resolved we can reconsider https://github.com/etsy/statsd/issues/585
