### ISSUE TITLE
Minecraft Input Plugin broken for 1.13 based servers

### ISSUE THREAD

**Issue by jhg03a** [influxdata/telegraf#5477]
### Relevant telegraf.conf:
Any stock Minecraft input plugin config pointing to a valid Minecraft 1.13 based server.

### System info:
Found with telegraf 1.9, but should affect all prior versions as well.

### Steps to reproduce:

1. Create a Minecraft 1.13 server
2. Connect telegraf via the Minecraft input plugin to it

### Expected behavior:
Some data as configured in the Minecraft scoreboard settings

### Actual behavior:
No data

### Additional info:
The input plugin is broken as a result of a [change/bug in the RCON api](https://bugs.mojang.com/browse/MC-136858).  The plugin could be updated to instead of relying on a single RCON call for all the data to instead make <players>+1 RCON calls to fetch player stats individually which does still work.

The plugin does still work for servers prior to the 1.13 update I believe.

**Comment by danielnelson** [comment]
Might be some time before Mojang gets to this, so the workaround might be the way to go.  Do you know the command to list all players?

**Comment by jhg03a** [comment]
`/scoreboard players list *` would be replaced with a combination of `/scoreboard players list` and `/scoreboard players list <playername>` I believe.

**Comment by paulkramme** [comment]
Anything I can do to help.

**Comment by danielnelson** [comment]
I worked on this a bit last night but I still have a few hours of work.  Turns out the response text changed as well so it has been a bit more work than expected, but I should have something ready for testing soon.

**Comment by danielnelson** [comment]
Moving to 1.11, the changes are a bit too large for a patch release.  Should have a build for testing this evening.

**Comment by paulkramme** [comment]
This is great, thank you for keeping us in the loop.
