### ISSUE TITLE
[Feature Request] procstat to provide cpu_time_total

### ISSUE THREAD

**Issue by klyinliu** [influxdata/telegraf#548]
cpu_time_total will be the sum up of all cpu_time used by the process.

So basically, what I need is the total CPU percentage.
If I can get the cpu_time_total, then I can use the derivative function in influxdb to get the percentage.
However, now all cpu_time are separate and derivative function in influxdb doesn't support math function of multi fields. Thus, I have to create an extra Continuous Query to get it work.

But the sum up should be really simple in the plugin level.

Can you add it in please? Thanks.

**Comment by sparrc** [comment]
Would it be enough to just have the usage percentages? see https://github.com/influxdata/telegraf/issues/484

**Comment by klyinliu** [comment]
Yes, that will be even better.

**Comment by sparrc** [comment]
okay, closing in favor of #484
