### ISSUE TITLE
Is it possible to collect VSphere VMs disk usage

### ISSUE THREAD

**Issue by dkutetsky** [influxdata/telegraf#5480]
Is there any way to collect disk metrics of VMs - used/free space in GB or %?
There are only available disk read/write/average latency metrics, but it's not useful and not suitable for our needs.
 
Metrics should have the same numbers as `df -h` output in Linux.

Did not find this is in available [VMs metrics](https://github.com/influxdata/telegraf/blob/release-1.9/plugins/inputs/vsphere/METRICS.md)

There is few available solutions - [1](https://communities.vmware.com/thread/477833), [2](http://vmware1345.rssing.com/chan-14972843/all_p126.html) on Powershell/PowerCLI that are using VSphere API to retrieve following attributes: FreeSpaceGB, CapacityGB. 
So, I believe the same property should be available to collecting by Telegraf.

**Comment by Prajan87** [comment]
I am facing the same issue. Did you find the solution, if there is? thanks

**Comment by dkutetsky** [comment]
> I am facing the same issue. Did you find the solution, if there is? thanks

Hi @Prajan87! 
We didn't find solution, it is on hold now.

**Comment by Prajan87** [comment]
Thanks @dkutetsky for quick response. Probably should look for other options then.

**Comment by kmsj13** [comment]
Any update on this feature?

**Comment by Prajan87** [comment]
@kmsj13  I couldn't figure out the solution. So, moved on to prometheus node exporter.

**Comment by fbraiek** [comment]
@Prajan87  can you please help me how to use prometheus node exporter

**Comment by danielnelson** [comment]
We would only add support for this to the vSphere input if it is something that can be retrieved over the vSphere APIs.  I think it is likely that vSphere wouldn't be able generally tell from the outside what the disk usage is. @prydin Can you confirm if this is or is not possible?

What I would suggest instead is to run Telegraf in each VMs with the disk input enabled.  You can forward the metrics to InfluxDB directly or to another Telegraf instance using the `influxdb` output to send and the `influxdb_listener` input to receive.

**Comment by prydin** [comment]
Generally, vSphere doesn't see what's going on inside the VM and its OS. As @danielnelson suggests, you'll get the highest level of in-guest metrics by deploying Telegraf inside the VM and enabling regular OS metrics collection.

**Comment by vterdunov** [comment]
Some metrics can be collected if a VM has vmware tools installed.
Also `vm.summary.storage` would be useful too.
