### ISSUE TITLE
 Cannot parse unix_ms timestamp in csv parser

### ISSUE THREAD

**Issue by bderf** [influxdata/telegraf#5485]
### Relevant telegraf.conf:
[[inputs.file]]
files = [“results.csv”]
data_format = “csv”
csv_header_row_count = 1
csv_delimiter = “,”
csv_timestamp_column = “timeStamp”
csv_timestamp_format = “unix_ms”

### System info:
[Include Telegraf version, operating system name, and other relevant details]
Telegraf 1.9.4
CentOS 7

### Steps to reproduce:
Input csv file:
timeStamp,elapsed
1550530705935,7720

### Actual behavior:
[inputs.file]: Error in plugin: parsing time “1550530705935” as “unix_ms”: cannot parse “1550530705935” as “unix_ms”

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
The `unix_ms` format is not yet available in a released version, but you can try the 
[nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and stay tuned for 1.10-rc1 which should be out very soon.

**Comment by sslupsky** [comment]
Hi @danielnelson 

I think you should consider reopening this issue.  The "unix" format does not work either.  Here is the error:

Error: parsing time "1524449392" as "unix": cannot parse "1524449392" as "unix"

and the telegraf.conf input:

[[inputs.tail]]
  files = ["/motescan/scannet03/plotmote/l00010000167A2E17_154.csv_channel_batt.csv"]
  from_beginning = true
  pipe = false
  watch_method = "inotify"
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["timestamp", "batt"]
  csv_column_types = ["string", "float"]
  csv_skip_rows = 0
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = ""
  csv_trim_space = false
  csv_tag_columns = []
  csv_measurement_column = ""
  csv_timestamp_column = "timestamp"
  csv_timestamp_format = "unix"
  [inputs.tail.tags]
    applicationName = "telegraf-test"

**Comment by danielnelson** [comment]
The `unix*` options were added after the 1.9 release on this parser, and we don't normally backport features.  The good news is it already working for 1.10.  When reading the documentation on Github, make sure to select the branch for the release you are using, i.e.:`release-1.9`.

**Comment by sslupsky** [comment]
Ahh, i see what you mean ... the doc for 1.9.4 doesn't show the "unix" type.  Ok, thanks for letting me know, I'll use a grok parser instead.

**Comment by glinton** [comment]
sslupsky, if you'd like to use that feature now, feel free to use a [nightly build](https://github.com/influxdata/telegraf#nightly-builds)
