### ISSUE TITLE
redis plugin sentinel support

### ISSUE THREAD

**Issue by ceastman-ibm** [influxdata/telegraf#5487]
## Feature Request
Have the redis input plugin support redis sentinels

Opening a feature request kicks off a discussion.

### Proposal:
Have the redis input plugin optional connect to the redis sentinel port (default 26379) to find where the current redis master is and then connect to that to gather the "info" statistics

### Current behavior:
In kubernetes we have three redis servers, 1 master and 2 slaves. The redis service in kubernetes doesn't know which redis server is the master so it connects 6379 to any of the 3 redis instances. Sometimes it connects to the master other times its one of the slaves.

connecting to the redis slave doesn't have all the info statistics that the master does, for instance on the slave the connected_slaves statistic is 0.

### Desired behavior:
Have the redis input plugin determine if its connected to the master and if not query the sentinel to find out who the master is and then connect to that for the "info" statistics

### Use case: [Why is this important (helps with prioritizing requests)]
The use case is for people that have deployed redis in a master slave configuration in a kubernetes cluster.

**Comment by sjwang90** [comment]
@adamflott is no longer working on PR #5978. If anyone wants to take this one over please feel free.

**Comment by spideyfusion** [comment]
Here's the PR: https://github.com/influxdata/telegraf/pull/10042
