### ISSUE TITLE
inputs-vsphere: The request refers to an unexpected or unknown type

### ISSUE THREAD

**Issue by MartVisser** [influxdata/telegraf#5492]
I updated to the nightly build (because of https://github.com/influxdata/telegraf/issues/5296) and now I got some strange failed tasks in my vCenter (6.5u1), see screenshots:

![screenshot 2019-02-22 at 09 56 41](https://user-images.githubusercontent.com/1586297/53479100-9ca42380-3a78-11e9-8123-0e0c996f8cf2.png)
![screenshot 2019-02-22 at 09 56 24](https://user-images.githubusercontent.com/1586297/53479101-9d3cba00-3a78-11e9-805d-24d13a72fa30.png)

**Comment by prydin** [comment]
This is luckily a benign bug that occurs when we're trying to destroy a resource that doesn't support being destroyed. But it's a bit unsightly in the logs for sure. Will fix immediately.

**Comment by ChrisU-bckspc** [comment]
I can confirm the same error.  It appears in my fresh installation, too.

**Comment by prydin** [comment]
Running the fix in a test lab right now. Will push today so it should be available in the next bug fix release.

**Comment by junior466** [comment]
I can also confirm the same error. I also noticed that it shows every 5 minutes, the same refresh interval for my Grafana dashboard. Safe to assume its going to appear as long as Grafana is open?

**Comment by prydin** [comment]
This will be fixed un the next maintenance release. Luckily, is doesn't affect functionality or performance.

**Comment by danielnelson** [comment]
Closed in #5557
