### ISSUE TITLE
MongoDB input plugin: Adding per Collection stats

### ISSUE THREAD

**Issue by carlo4002** [influxdata/telegraf#5496]
## Feature Request

Since https://github.com/influxdata/telegraf/pull/1466 we got the option to gather metrics for every database. Isn't it useful to have metrics per collection? 
### Proposal:
add the option `gather_percollection_stats`
### Current behavior:
The metrics are collected at database level.
### Desired behavior:
Have a better granularity to collect metrics by database and collection 
### Use case: [Why is this important (helps with prioritizing requests)]
Different collections are dedicated to different services therefore it is important to know which collection grows faster for example

**Comment by scottprichard** [comment]
We are using the mongo_db stats and would love this per collection metric!

**Comment by danielnelson** [comment]
Closed in #6137
