### ISSUE TITLE
in procstat input plugin, `process_name` tag should be tagged not only `procstat` measurement but `procstat_lookup` measurement.

### ISSUE THREAD

**Issue by Jaeyo** [influxdata/telegraf#5498]
## Feature Request

in procstat input plugin, `process_name` tag also tagged in `procstat_lookup` measurement.

### Current behavior:

procstat input plugin produce two measurement: `procstat`, `procstat_lookup`.
and `process_name` tag only tagged with `procstat` measurement.

```
# tag list
- procstat measurement
  - host
  - pattern
  - process_name
  - user
- procstat_lookup measurement
  - host
  - pattern
```

### Desired behavior:

`process_name` should be tagged with `procstat_lookup` measurement also.

### Use case: [Why is this important (helps with prioritizing requests)]

i'm checking specific processes aliveness with `procstat_lookup` measurement with `pid_count` field. if `process_name` tagged with `procstat_lookup` measurement, i think i can check it more clearly.

**Comment by danielnelson** [comment]
During the lookup we don't know the process name yet, and the lookup may return multiple processes with differing names.  One exception to this might be if it is set statically with the `process_name` option, though I'd like to do #3362 and then deprecate this option.

If you are setting the `process_name`, or even if not but you have a good idea of what it should be statically then you can use the tags option:
```toml
[[inputs.procstat]]
  [inputs.procstat.tags]
    process_name = "foo"
```

**Comment by tushar2013** [comment]
this does not override the process_name tag of procstat measurement.
so if procstat if getting a name "foo" from /proc/<pid>/status and then you do above to set process_name as "my_foo"
then procstat_lookup will definitely have a tag as "process_name=my_foo" but procstat will still have "process_name=foo"
