### ISSUE TITLE
Cache remote config localy and use it if remote server not working

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#5501]
## Feature Request

We need a robust system ready to all possible contingencies.

### Proposal:

On each telegraf remote config downloaded with the following command

````
telegraf -config http://myconfigserver.9999/xxxxxxx/config.toml
````
Telegraf should store locally the config file by example on  /etc/telegraf/cached/config.toml.<date>

If remote server were  down  , telegraf -config http://myconfigserver.9999/xxxxxxx/config.toml will fail with timeout and then telegraf will read last stored config file from /etc/telegraf/cached/config.toml.<last>

### Current behavior:

````
[myserver].root:~ > /usr/bin/telegraf -config http://localhost:9999/notworking.toml
2019-02-28T13:40:36Z I! Starting Telegraf 1.9.5
2019-02-28T13:40:36Z E! [telegraf] Error running agent: Error loading http://localhost:9999/notworking.toml, Get http://localhost:9999/notworking.toml: dial tcp 127.0.0.1:9999: connect: connection refused
````
In this point Telegraf will not  work

### Desired behavior:
````
[myserver].root:~ > /usr/bin/telegraf -config http://localhost:9999/notworking.toml
2019-02-28T13:40:36Z I! Starting Telegraf 1.9.5
2019-02-28T13:40:36Z W! [telegraf] Error running agent: Error loading http://localhost:9999/notworking.toml, Get http://localhost:9999/notworking.toml: dial tcp 127.0.0.1:9999: connect: connection refused
2019-02-28T13:40:36Z I! Loading last cached  config in /etc/telegraf/cached/cached.conf.XXXXXXX 
````

At this point with the config server is down the telegraf will continue working and sending data with last known

### Use case: [Why is this important (helps with prioritising requests)]

The config server could be the same InfluxDB2.0 or perhaps a proxy server ( needed for security reasons) in this scenario the telegraf gathering process depends on the proxy server availability

**Comment by schmorgs** [comment]
+1 on this
As well as using a cached config if the endpoint is down, the agent should support a retry on the http endpoint if there is no cache available so that it doesn't simply exit, but keeps retrying until it's available, possibly using a switch to determine how often to retry and max attempts before giving up.
Have raised separate enhancement for the retry option https://github.com/influxdata/telegraf/issues/7338

**Comment by sspaink** [comment]
Caching the config seems related to the state persistence work: https://github.com/influxdata/telegraf/pull/9476, although that PR is focused on adding it to plugins maybe it could be reused for the remote config flag as well.
