### ISSUE TITLE
Telegraf should check by itself if remote config has changed to reload the agent

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#5502]
### Proposal:
We need a telegraf system ready to apply changes by itself,  we like to propose a new parameter -reload_period with the time period to check for new changes

On each telegraf remote config downloaded with the following command

```
telegraf -config http://myconfigserver.9999/xxxxxxx/config.toml -reload_period 1h
```
The way to do this could be done by cache first last know configuration file. as in  #5501 , and then with an easy checksum could detect config changes, when detected the telegraf agent should gracefully restart with the new configuration file.

### Current behavior:

now reload process should be done by external processes like (cron / systemd), in this process we can lost some points of data  

### Desired behavior:

Reload config only when config changes avoiding data lost

### Use case: [Why is this important (helps with prioritizing requests)]

This behavior will help admin systems in the provisioning and centralised config system process in  a distributed unassisted system with minimal impact

**Comment by danielnelson** [comment]
Thanks for the feedback, we have some plans to allow event triggered updates based on this prototype I worked on some time back: https://github.com/danielnelson/tgconfig.  For now though I don't want to add any new cli options since I don't want to commit to keeping support for them.

**Comment by schmorgs** [comment]
+1 on this.  
Having a central config server is perfect in a large estate, and simplifies making changes to an agent config.  So having the ability for the agent to poll for new config on a predefined interval would close the automation loop here and remove the need to kick off an agent restart on what could be thousands of nodes in such cases.

**Comment by schmorgs** [comment]
I have a workaround for this but it only works on Linux, and does not check if the config is newer than existing or not.  

Basically, use the exec input plugin to kill -SIGHUP the telegraf process forcing it to reload config.
Make sure your grep matches the correct process of course.

`
[[inputs.exec]]
  interval = "1h"
  commands = [
    "sh -c \"ps -ef | grep 'telegraf --config' | grep -v grep | awk '{print \\$2}' | xargs kill -SIGHUP\""

  ]
`

**Comment by sjwang90** [comment]
Didn't realize an issue on this topic was open. I'm going to close this and keep #8730 since it includes conversation with @schmorgs 

@toni-moreno Please provide any additional comments on #8730
