### ISSUE TITLE
Use the enum processor to remap to string data types and operate on tags

### ISSUE THREAD

**Issue by sslupsky** [influxdata/telegraf#5506]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Use the enum processor to remap fields and tags to string data types

### Current behavior:
The enum processor allows remap of fields with string types to numeric or bool types.

### Desired behavior:
Allow the enum processor to remap a field or tag to a string type.

### Use case: [Why is this important (helps with prioritizing requests)]
Extracting and reorganizing metadata where the input stream cannot be changed.

**Comment by morph027** [comment]
Similar to #5033

**Comment by glinton** [comment]
Closing in favor of #5033
