### ISSUE TITLE
Add ability to validate configuration file without starting

### ISSUE THREAD

**Issue by littlespace** [influxdata/telegraf#5507]
Hi, 

Is there a way that we can check the telegraf config and make sure the config is good before starting the telegraf service? 

Thanks

**Comment by danielnelson** [comment]
I think the closest thing is running `telegraf --test`, this should catch most errors.

**Comment by Karsonito** [comment]
Hi! Any news about implementing a-la `--configtest` just for syntactical check?

**Comment by powersj** [comment]
This has come up from time to time, but the answer remains to use either the `--test` or `--once` options. These would confirm that the plugins are successfully loaded and can even operate successfully.

**Comment by Hipska** [comment]
@littlespace Check out v1.32.0 which now has a command to actually check the config. See https://github.com/influxdata/telegraf/pull/15732
