### ISSUE TITLE
How to parse Json from jsonstring in Json object

### ISSUE THREAD

**Issue by GESTAR** [influxdata/telegraf#5521]
## Feature Request
add a option in json input data format.(eg. json_string_parse)what can convert jsonstring to json object.
my json data:
`
{"action":"message_publish","device_id":"02189V049","username":"client","payload":"{\"did\":\"02189V049\",\"v\":\"1.0.1\",\"hw\":\"0.4.0\",\"t\":1551659411,\"temp\":0,\"vol\":220,\"rssi\":1,\"en\":2000}"}
`
i want parse "payload" parse to json. how? thanks.

**Comment by glinton** [comment]
You can use the parser processor for this https://github.com/influxdata/telegraf/tree/release-1.9/plugins/processors/parser
