### ISSUE TITLE
Some Ceph cluster stats not reported for Hammer

### ISSUE THREAD

**Issue by moorglade** [influxdata/telegraf#5523]
### Relevant telegraf.conf:
```
[[inputs.ceph]]
  ceph_user = "client.admin"
  ceph_config = "/etc/ceph/ceph.conf"
  gather_admin_socket_stats = false
  gather_cluster_stats = true
```

### System info:
Telegraf 1.9.5 (executed in a Docker container)
Ceph 0.94.5 (Hammer)
CentOS 7.5.1804

### Steps to reproduce:
1. Add Ceph input with `gather_cluster_stats = true` to Telegraf configuration.

### Expected behavior:
All cluster stats described in the [README](https://github.com/influxdata/telegraf/tree/1.9.5/plugins/inputs/ceph) are reported.

### Actual behavior:
Some cluster stats are not reported at all, i.e.:
* `ceph_usage.total_bytes`
* `ceph_usage.total_used_bytes`
* `ceph_usage.total_avail_bytes`
* `ceph_pool_usage.max_avail`

(There may be more, I haven't checked all the metrics.)

### Additional info:
1. Everything works fine with Telegraf 1.8.3.
1. This issue seem to be related to https://github.com/influxdata/telegraf/issues/5277, but instead of zeroes, I don't get any values at all.
1. Output returned by `ceph df` seems to be partially consistent with what I can see in the [tests](https://github.com/influxdata/telegraf/blob/1.9.5/plugins/inputs/ceph/ceph_test.go#L912), i.e.

    ```
    $ ceph --conf /etc/ceph/ceph.conf --format json-pretty df
    {
        "stats": {
            "total_bytes": 56719207284736,
            "total_used_bytes": 26185807761408,
            "total_avail_bytes": 30533399523328
        },
        "pools": [
            {
                "name": "rbd",
                "id": 0,
                "stats": {
                    "kb_used": 1172409821,
                    "bytes_used": 1200547656115,
                    "max_avail": 13376747995136,
                    "objects": 294000
                }
            },
    ...
    ```

**Comment by moorglade** [comment]
May I ask which release is this fix planned for? I see it's been marked for milestone 1.10.0, but I still don't see it in the 1.10.1 release.

**Comment by danielnelson** [comment]
It looks like I forgot to include it into the release branch, I will put it in for 1.10.2.

**Comment by moorglade** [comment]
Thanks!
