### ISSUE TITLE
 Error in plugin [inputs.netstat]  on windows

### ISSUE THREAD

**Issue by llmuculusll** [influxdata/telegraf#5526]
### System info:
Telegraf Version 1.9.3
Windows 2016 Server

### Steps to reproduce:

1. adding [[inputs.netstat]] to telegraf.conf
2. starting Telegraf service

### Expected behavior:
Collecting Data from netstat input plugin

### Actual behavior:
This Error has Occurred:
`2019-03-04T21:00:20Z E! [inputs.netstat]: Error in plugin: error getting net connections info: not implemented yet`

**Comment by glinton** [comment]
The library we were using to gather these statistics has been updated for the telegraf 1.10 release.

Closed by #5288
