### ISSUE TITLE
Allow using floating point numbers in statsd percentiles

### ISSUE THREAD

**Issue by Pitxyoki** [influxdata/telegraf#5527]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
We should be able to define percentiles with decimal places when using statsd as the source of input.

### Current behavior:
If we try to define a percentile array with floating point numbers, for example: `[99.0, 99.9, 99.99, 100.0]`, Telegraf won't even start and will stop with the following error:

> 2019-03-04T21:04:26Z I! Starting Telegraf 1.9.2
> 2019-03-04T21:04:26Z I! Using config file: /etc/telegraf/telegraf.conf
> 2019-03-04T21:04:26Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 1579: statsd.Statsd.Percentiles: `int' is not float32 or float64

### Desired behavior:
We should be able to define more fine-grained percentiles. 

### Use case:
After getting more than 100 data points per submission interval, it becomes important to see percentiles between 99.0 and 100.0.

**Comment by danielnelson** [comment]
Closed in #5572
