### ISSUE TITLE
nvidia_smi should collect metrics about the decoder and encoder =

### ISSUE THREAD

**Issue by alex131290** [influxdata/telegraf#5532]
## Feature Request
The nvidia_smi input plugin should collect data about the Utilization of the Decoder and Encoder as well. Currently, it collects data only about the GPU and Memory.
Opening a feature request kicks off a discussion.

### Use case: [Why is this important (helps with prioritizing requests)]

**Comment by danielnelson** [comment]
Can you recommend what command to run and show the output on your system?

**Comment by sturgeo** [comment]
Hi, i would also like to collect data on decoder/encoder utilization.

The command is `nvidia-smi dmon -s u`

Output is:

# gpu    sm   mem   enc   dec
# Idx     %     %     %     %
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0
    0     0     0     0     0

Last 2 fields are the ones of interest.

Thanks

**Comment by chenseanxy** [comment]
Previously this wasn't available due to `--query-gpu` don't support it.

Now that the plugin switched to XML parsing, this should be pretty easy as they are presented in utilization > encoder_util & decoder_util.

**Comment by danielnelson** [comment]
Added these new fields in #7646, thanks @chenseanxy:

- utilization_encoder
- utilization_decoder
- fbc_stats_session_count
- fbc_stats_average_fps
- fbc_stats_average_latency
