### ISSUE TITLE
Create AppDynamics Custom Metric Plug-in

### ISSUE THREAD

**Issue by jmalette** [influxdata/telegraf#5535]
## Feature Request

Would like the ability for Telegraf to output metrics to AppDynamics per any of the supported options - https://docs.appdynamics.com/display/PRO45/Extensions+and+Custom+Metrics

### Proposal:
Configure Telegraf output to send logs to Machine Agent http collector or java collector.
### Current behavior:
Might be able to do this with http output but wondering if there is a better collector
### Desired behavior:
Influx approved output to submit data to common APM platform
### Use case: [Why is this important (helps with prioritizing requests)]
All customers would like to reduce their agent count so ideally if I can output directly to AppD that would be ideal if not, I'd like to be able to use the agent to send to their Machine agent.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you on this.

It does not look like there was much desire to have this plugin and we haven't heard of other requests, so I am going to go ahead and close this.

Thanks

**Comment by remiego** [comment]
Picked a bad time to come looking for this capability.
