### ISSUE TITLE
Get TTL from ping

### ISSUE THREAD

**Issue by CWempe** [influxdata/telegraf#5537]
## Feature Request

It would be nice to get the TTL of a ping response.

> ping www.google.com (173.194.115.84): 56 data bytes
> 64 bytes from 173.194.115.84: icmp_seq=0 ttl=54 time=52.172 ms
> 64 bytes from 173.194.115.84: icmp_seq=1 ttl=54 time=34.843 ms

### Proposal:

I think it would not be easy or make sense to generate the **average** of the TTLs if you executed >1 pings.
But the TTL during one ping command would be the same in most cases^, anyway.
So the last (or first) TTL of the output would be sufficient.

### Current behavior:

TTL is not returned by the ping plugin.

### Desired behavior:

Output the TTL from the ping.

### Use case:

When you have a diagram with the TTL to a remote host you can see if and how the routing between local and remote host has changed during the time. Useful for monitoring WAN-Connections.

**Comment by dheerajdwivedi** [comment]
I am picking this up.
Any suggestions on what should be the TTL value
1. First TTL
2. Last TTL
3. List of unique TTL

**Comment by CWempe** [comment]
More suggestions:

4. Min TTL
5. Max TTL
6. Most occurred TTL

Maybe all options (4-6) and the user can decide.

Sorry, I am not helping to find a decision. 🙈

**Comment by dheerajdwivedi** [comment]
Fluctuating TTL in a single ping is not a normal behaviour, unless DHCP server permits two machines with the same ip address.
@CWempe What is the use case you are using the plugin for ?

**Comment by CWempe** [comment]
Use case is monitoring WAN connections to other branches and see if there is any strange behavior.

But you are right. One value should be enough

**Comment by danielnelson** [comment]
Closed in #5556
