### ISSUE TITLE
input.kibana connection error reporting

### ISSUE THREAD

**Issue by jsearles57** [influxdata/telegraf#5538]
## Feature Request

Update input.kibana plugin to output a bad or unknown state when it can not resolve/connect to a kibana host.

### Current behavior:
Currently when input.kibana plugin can not connect or kibana host can not resolve a domain, it will out put an error log.
### Desired behavior:
When the input.kibana plugin can not connect or cant not resolve kibana host it should create a new metric with status of red/unknown and note the problem.
### Use case: [Why is this important (helps with prioritizing requests)]
This is important so that I do not need a second monitor of the telegraf log files to note when telegraf has a problem connecting to a kibana host to check its health.

**Comment by danielnelson** [comment]
We could add this to the `internal` plugin.  Currently it will be counted in `internal_agent gather_errors`, but it would be good to count these errors per plugin in the `internal_gather` metric as well.  Here is how the output looks now:
```
internal_gather,input=kibana metrics_gathered=0i,gather_time_ns=412380i
internal_agent metrics_written=30i,metrics_dropped=0i,metrics_gathered=37i,gather_errors=2i
```

So we could just make gather_errors per plugin:
```
internal_gather,input=kibana metrics_gathered=0i,gather_time_ns=412380i,gather_errors=2i
internal_agent metrics_written=30i,metrics_dropped=0i,metrics_gathered=37i,gather_errors=2i
```

In the meantime, I do suggest turning this plugin on and watching the `internal_agent gather_errors`

**Comment by powersj** [comment]
Hi,

If the current internal metrics are not sufficient, please do let us know with a new issue and explain what should be added. For now I'll be closing this.

Thanks!
