### ISSUE TITLE
Support output to Amazon Timestream

### ISSUE THREAD

**Issue by shatil** [influxdata/telegraf#5539]
## Feature Request
Requesting output plugin to write to Amazon Timestream time series database: https://aws.amazon.com/timestream/

### Proposal:
Proposing that Amazon Timestream become a supported output plugin.

### Current behavior:
Amazon Timestream is not a supported output plugin.

### Desired behavior:
Amazon Timestream is a supported output plugin, like InfluxDB.

### Use case: [Why is this important (helps with prioritizing requests)]
Timestream is a managed time series database by AWS, a major cloud resources provider, and could greatly simplify setup for housing data that Telegraf collects.

**Comment by ssoroka** [comment]
PR https://github.com/influxdata/telegraf/pull/8211

**Comment by shatil** [comment]
OMG so excited. Thanks @ssoroka!

**Comment by sjwang90** [comment]
Merged in #8239
