### ISSUE TITLE
[inputs.kube_inventory]: Error in plugin: decode error status 404: decode json: invalid character 'p' after top-level value

### ISSUE THREAD

**Issue by ceastman-ibm** [influxdata/telegraf#5551]
### Relevant telegraf.conf:

[[inputs.kube_inventory]]
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  insecure_skip_verify = true
  url = "https://$HOSTNAME:10250"

### System info:
telegraf 1.10.0
IBM Cloud kubernetes
Kubernetes version 1.11.7
using slightly modified helm chart from https://github.com/helm/charts/tree/master/stable/telegraf

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
Install telegraf 1.10.0 in IBM cloud kubernetes clusters
1. ...
2. ...

### Expected behavior:
To not receive an error in the kubectl logs

### Actual behavior:
I am getting the following in the logs from the daemonset pods:
[inputs.kube_inventory]: Error in plugin: decode error status 404: decode json: invalid character 'p' after top-level value

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by samhld** [comment]
Hi @ceastman-ibm, you're using the kubelet api endpoint in the URL field in the config.  That endpoint is good for the [[inputs.kubernetes]] input plugin.  This one is different.

You need to replace that url with the server address found in the output of `kubectl cluster-info`.

**Comment by ceastman-ibm** [comment]
@samhld ah thank you, i will try that and update this issue.

**Comment by ceastman-ibm** [comment]
@samhld that fixed the issue, thank you.
