### ISSUE TITLE
Extend nowmetric serializer to include tags

### ISSUE THREAD

**Issue by hwaastad** [influxdata/telegraf#5554]
## Feature Request

Incude tags in ci2metric_id

### Proposal:
Since ci2metric_id from ServiceNow is by spec a key-value list it should be possible to add multiple tags

### Current behavior:
Only host tag is added as node in both node attribute and ci2metric_id.node attribute

### Desired behavior:
I would propose an alternativ to add all tags to ci2metric_id

### Use case: [Why is this important (helps with prioritizing requests)]
By implementing this, the identification process in ServiceNow can be extended to match on multiple fields (i.e interface index -> Switchport CI field binding, Cisco WLC -> AccessPoint -> metric)
Currently the resource attribute can be used to filter, but I feel its more appropriate to use ci2metric_id since resource binding in ServiceNow >=Madrid can be used to monitor an entity that is not a CI,

**Comment by danielnelson** [comment]
This makes sense to me, otherwise most of the tag info is lost. @JefMuller what do you think?

**Comment by JefMuller** [comment]
Yep make sense. Will apply the change.
