### ISSUE TITLE
Error with `fieldexclude` directive in net_response input

### ISSUE THREAD

**Issue by klesher** [influxdata/telegraf#5560]
### System Info
Amazon Linux AMI release 2018.03
Telegraf v1.10.0

### Issue
When uncommenting the `fieldexclude` line under a `[[inputs.net_response]] configuration (as suggested for new deploys), Telegraf is unable to start with the following error in `/etc/telegraf/telegraf.log`:

```
2019-03-08T20:25:44Z I! Starting Telegraf 1.10.0
2019-03-08T20:25:44Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.d/net_response.conf, line 40: field corresponding to `fieldexclude' is not defined in `*net_response.NetResponse'
```
Commenting this back out allows Telegraf to start again successfully.

### Relevant Telegraf.conf:
```
[[inputs.net_response]]
  interval = "60s"

  ## Protocol, must be "tcp" or "udp"
  ## NOTE: because the "udp" protocol does not respond to requests, it requires
  ## a send/expect string pair (see below).
  protocol = "tcp"
  ## Server address (default localhost)
  address = "localhost:80"

  ## Uncomment to remove deprecated fields; recommended for new deploys
  fieldexclude = ["result_type", "string_found"]
```

### Expected Behavior
Telegraf successfully starts with this line uncommented, and suppresses deprecated `result_type` and `string_found` metrics as noted in the current [version of the net_response README](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response).

### Additional Info:
Happy to provide any additional info if needed!  Thanks for all the great work so far!

**Comment by danielnelson** [comment]
Docs are incorrect, I'll update them but it should be fielddrop instead of fieldexclude:
```
fielddrop = ["result_type", "string_found"]
```

**Comment by danielnelson** [comment]
Closed in 7da57fe5f5ab019b59db74945276b8c604b73ba7

**Comment by klesher** [comment]
Perfect, thanks for the quick response & fix!

**Comment by klesher** [comment]
I also did a quick repo search for `fieldexclude`.  There's one other instance remaining in the sample telegraf.conf under the net_response section:

https://github.com/influxdata/telegraf/search?q=fieldexclude&unscoped_q=fieldexclude

**Comment by danielnelson** [comment]
Thanks, 2566210df1e1ffba552b3379a09b443f3ddc3e3f
