### ISSUE TITLE
Support insecure_skip_verify in input.phpfpm

### ISSUE THREAD

**Issue by LeoVerto** [influxdata/telegraf#5561]
## Feature Request
Support insecure_skip_verify in input.phpfpm

### Proposal:
input.phpfpm should allow skipping TLS certificate verification by having an `insecure_skip_verify = true|false` configuration option.

### Current behavior:
input.phpfpm always fails when trying to access a php_fpm status page reverse-proxied using a self-signed certificate.

### Desired behavior:
Users should be able to skip certificate verification for self-signed certs in known safe environments.

### Use case:
A lot of other plugins already have this feature. Users may want to gather statistics on php-fpm instances running behind reverse proxies that use self-signed certificates for internal connections.

**Comment by danielnelson** [comment]
We should also add the usual TLS options while doing this:

```
  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false
```
