### ISSUE TITLE
vsphere input field type conflict since telegraf version 1.10

### ISSUE THREAD

**Issue by jstiops** [influxdata/telegraf#5565]
### Relevant telegraf.conf:

```

#realtime stats
 [[inputs.vsphere]]
   ## List of vCenter URLs to be monitored. These three lines must be uncommented
   ## and edited for the plugin to work.
   vcenters = [ "https://redacted/sdk" ]
   username = "redacted"
   password = "redacted"


interval = "60s"
  insecure_skip_verify = true
  force_discover_on_init = true

  # Exclude all historical metrics
  datastore_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]

  collect_concurrency = 1
  discover_concurrency = 1

  ## timeout applies to any of the api request made to vcenter
  timeout = "10s"
   
#historical stats
 [[inputs.vsphere]]
   vcenters = [ "https://redacted/sdk" ]
   username = "redacted"
   password = "redacted"

  interval = "300s"
  insecure_skip_verify = true
  force_discover_on_init = true
  ## the interval before (re)discovering objects subject to metrics collection (default: 300s)
  object_discovery_interval = "600s"
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics
  cluster_metric_exclude = ["*"] # Exclude cluster metrics
  datacenter_metric_exclude = ["*"] # Exclude datacenter metrics

  #max_query_metrics = 256
  collect_concurrency = 1

  ## timeout applies to any of the api request made to vcenter
  timeout = "120s"  
```
### System info:

telegraf 1.10 on Windows Server 2016
vSphere 6.7 update1
InfluxDB 1.7.4

### Steps to reproduce:

upgraded telegraf.exe on windows from 1.9.4 tot 1.10.

### Expected behavior:
no change in behavior.
### Actual behavior:
seeing following entries in telegraf.log, alot of them for alot of metrics

```
2019-03-10T16:33:03Z E! [outputs.influxdb]: when writing to [https://redacted:8086]: received error partial write: field type conflict: input field "used_summation" on measurement "vsphere_vm_cpu" is type float, already exists as type integer dropped=921; discarding points
2019-03-10T16:34:02Z E! [outputs.influxdb]: when writing to [https://redacted:8086]: received error partial write: field type conflict: input field "datastoreWriteOIO_latest" on measurement "vsphere_host_datastore" is type float, already exists as type integer dropped=872; discarding points
2019-03-10T16:34:02Z E! [outputs.influxdb]: when writing to [https://redacted:8086]: received error partial write: field type conflict: input field "maxlimited_summation" on measurement "vsphere_vm_cpu" is type float, already exists as type integer dropped=948; discarding points
```
### Additional info:
had to revert back to 1.9.4 to get my metrics back.

**Comment by jstiops** [comment]
Ah, probably related issues and PR described in #5563

**Comment by einhirn** [comment]
Had the same problem, added "converter" module to just make everyting a "float" and move the data to a new DB because InfluxDB always reverted to the old schema even though I deleted the measurement...

**Comment by einhirn** [comment]
> Had the same problem, added "converter" module to just make everyting a "float" and move the data to a new DB because InfluxDB always reverted to the old schema even though I deleted the measurement...

Offtopic: how would I go on and try to change influxdb schema when no longer using the said workaround?

**Comment by danielnelson** [comment]
In 1.10.1, we will restore the integer types which will provide compatibility with earlier releases.  If you have already moved your InfluxDB schema to floats you will need to set `use_int_samples = false` to stick with 1.10 style.

Closed in #5563

**Comment by danielnelson** [comment]
@einhirn I wrote up [a method for migrating](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql#metric-version) between schema's using Kapacitor when we needed to change the mysql plugin, I think the same method could be used here.

**Comment by danielnelson** [comment]
@jstiops @einhirn Would you be able to help test the fix?  Here are some builds:

- [telegraf_1.10.0~5970053b-0_amd64.deb](https://29342-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.10.0~5970053b-0_amd64.deb)
- [telegraf-1.10.0~5970053b-0.x86_64.rpm](https://29342-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.10.0~5970053b-0.x86_64.rpm)
- [telegraf-1.10.0~5970053b_windows_amd64.zip](https://29342-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.10.0~5970053b_windows_amd64.zip)

**Comment by jstiops** [comment]
i've tested with the latest windows_am64 nightly (as i write this) instead of linked builds, seems to run ok!
