### ISSUE TITLE
Burrow plugin error

### ISSUE THREAD

**Issue by lmallonee** [influxdata/telegraf#5570]
Hi,

I'm able to get this plugin to pull all the values I need from burrow; however, my error log is being filled with: 

`E! Error in plugin [inputs.burrow]: wrong response: 404`

When I debug it, it shows no additional information as to why this is acting this way. I have only defined the burrow server in inputs.burrow, and there seems to only be ~7 errors for each 10 second interval (There are about 30-40 active topic/consumer pairs with upwards to 100 partitions per pair).

**Comment by lmallonee** [comment]
Update:
Whenever I curl the topics, there are 7 topics that are in brackets; however, Telegraf still manages to read them and get their offsets from Burrow. The results still show up in Influxdb

**Comment by glinton** [comment]
Can you post your relevant config file along with version/system info and how we can reproduce this? Consider using the bug report template when [filing bugs](https://github.com/influxdata/telegraf/issues/new?template=Bug_report.md):
```md
### Relevant telegraf.conf:

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

### Actual behavior:

### Additional info:
```

**Comment by lmallonee** [comment]
So it turned out that there are some topics in prod that were created incorrectly, so they cannot be called when calling the topics through burrow HTTP. I had to blacklist those topics, and it's working as intended now!
