### ISSUE TITLE
Telegraf requires config even when using a config-directory

### ISSUE THREAD

**Issue by stevebang** [influxdata/telegraf#5571]
_From @bmagistro on April 26, 2018 17:44_

I was referencing #486 for information about using telegraf.d, specifically 

> Number (1) is probably a bug, if there is a valid file in telegraf.d we should be able to start Telegraf without specifying a singular .conf file.

While this setup may be "non-standard", we have shifted all configuration items to be loaded from files in telegraf.d.  When initially tried, I had omitted /etc/telegraf/telegraf.conf and that will cause telegraf to fail to start.  To solve this, adding an empty telegraf.conf file allows everything to work and all config files to live in telegraf.d.

From looking at this further the source comes from the telegraf.service file specifying --config and --config-dir.

_Copied from original issue: influxdata/docs.influxdata.com#1589_

**Comment by glinton** [comment]
According to #5703, this has been ["put it on ice until we have time to revamp the config loading in depth."](https://github.com/influxdata/telegraf/pull/5703#discussion_r276448439)
