### ISSUE TITLE
Get aggregate and output distinct values

### ISSUE THREAD

**Issue by mrtrock** [influxdata/telegraf#5576]
Hi Community, 

Ran across Telegraf yesterday. Its an awesome project but can't seem to find a solution to my problem. If you could offer any suggestion I would greatly appreciate it!

I will have multiple json objects sent to telegraf that look like

`{"id": "1", "app" : "web"},{"id":"1","app":"web"},{"id": "2","app":"web"}`

I am trying to get a value of distinct "id" and get an output that looks like 

`web=app, count="2"` 

Is this possible with the current plugins or will I need to create my own?

Thanks for your help!

**Comment by glinton** [comment]
I don't believe there is a way to count `distinct` values, but it may be possible to add it to the [valuecounter aggregator](https://github.com/influxdata/telegraf/tree/release-1.10/plugins/aggregators/valuecounter) as an option. Though it may be better off as it's own.

Also, for general discussion/questions like this, we prefer users post them on our [community forums](https://community.influxdata.com/), thanks.

**Comment by mrtrock** [comment]
okay thanks will use the community forum!

**Comment by danielnelson** [comment]
This would be a good addition, having an aggregator like this would allow some live monitoring of cardinality changes.  This is loosely related to #4124.

It should be possible to query this from InfluxDB with the raw values inserted:
```
select count(distinct(id)) from web where time > now() - 5m
```

**Comment by reimda** [comment]
I think the new JSONata serializer feature in #11251 can be used to merge multiple objects and keep track of a count. Could you give it a try?

I'm closing this due to age, but if the serializer doesn't do what you need, please ask for help again on the community forums or slack. Thanks!
