### ISSUE TITLE
open tomcat monitoring cause telegraf unable start

### ISSUE THREAD

**Issue by yewuxue** [influxdata/telegraf#5580]
![image](https://user-images.githubusercontent.com/37978945/54268471-365deb80-45b6-11e9-8576-a6183e2f1154.png)
![image](https://user-images.githubusercontent.com/37978945/54268493-44ac0780-45b6-11e9-9b98-895cd832f87a.png)

**Comment by glinton** [comment]
I'm not sure what the specific problem is. Can you follow the bug report template to provide more information (use text rather than screenshots please)? If your config has telegraf logging to a file, it would be useful to see it's logs as well to see what is causing it to fail to start up.

```
### Relevant telegraf.conf:

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

### Actual behavior:

### Additional info:

[Include gist of relevant config, logs, etc.]
```
