### ISSUE TITLE
Please change the behaviour of config generation

### ISSUE THREAD

**Issue by dhoppe** [influxdata/telegraf#5584]
## Feature Request
The file ```/etc/telegraf/telegraf.conf``` contains more than 5,000 lines and is therefore not maintainable after a minor or major release. 

### Current behavior:
The command ```telegraf --input-filter cpu --output-filter influxdb config``` creates a configuration containing the selected input/output plugins. 

### Desired behavior:
The command ```telegraf --input-filter cpu config``` should only create the configuration for the selected input plugin. 

### Use case: 
I want to use the command ```telegraf --input-filter cpu config``` to store the configuration in the file ```/etc/telegraf/telegraf.d/cpu.conf```. Then I am able to manipulate the plugin parameters with a config management tool like Puppet.

**Comment by glinton** [comment]
There is already the ability to do part of what you're describing, but I agree it would be nice to be able to omit the `agent` and `global` bits for cases like yours.

```
$ telegraf --output-filter none --processor-filter none --aggregator-filter none --input-filter cpu config
```
Already minimizes the config output, but maybe adding a `--header none` flag as well (still defaulting to `global_tags` and `agent`) would be acceptable.

**Comment by dhoppe** [comment]
@glinton Sounds great. Thanks a lot for your pull request.

**Comment by danielnelson** [comment]
You can use `telegraf --usage cpu` currently, but it has some shortcomings.  You aren't able to specify the plugin type which will cause, for example, `telegraf --usage influxdb` to print both input and output.  It also isn't possible to have it print the sample config for processors/aggregators.

**Comment by dhoppe** [comment]
@danielnelson Thank you very much for the Info. Somehow I missed this parameter. 

Nevertheless, I still have a few problems with multiline parameters. For example:
* https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L1778-L1779

Is this file generated automatically, should I crate a pull request or ist there a policy for automatic line breaks after x characters?

**Comment by danielnelson** [comment]
The file is generated automatically from the contents of the plugins [SampleConfig()](https://github.com/influxdata/telegraf/blob/5d9b8297760dd02cd5410e320e934368e4d9a260/plugins/inputs/conntrack/conntrack.go#L53-L70), but I think these two examples are valid.  What error are you getting?

**Comment by dhoppe** [comment]
@danielnelson I know that the syntax is correct and do not get any errors. But it is difficult to tell a config management system that it should modify multiline parameters. For that reason I was asking if it is possible to change these to a singleline parameter.

**Comment by danielnelson** [comment]
Got it.  On the influxdb input I could be persuaded but I think we need to try to keep these arrays under 80 chars.  Out of curiousity, what system you are using for this?

**Comment by dhoppe** [comment]
@danielnelson That is what I was afraid of (80 chars). 

I use Puppet 5.x and there is a requirement to use puppetlabs/inifile instead of toml-rb. Unfortunately puppetlabs/inifile is not aware of multiline parameters. :(
