### ISSUE TITLE
[parsers.nagios] Fails to parse extended Nagios output

### ISSUE THREAD

**Issue by sergeykhegay** [influxdata/telegraf#5591]
### Relevant telegraf.conf:

```
[[inputs.exec]]
  commands = ["/bin/bash ./nagios.sh"]

  data_format = "nagios"
```

`nagios.sh`
``` 
#! /bin/bash

# Taken from https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html
msg="DISK OK - free space: / 3326 MB (56%); | /=2643MB;5948;5958;0;5968
/ 15272 MB (77%);
/boot 68 MB (69%);
/home 69357 MB (27%);
/var/log 819 MB (84%); | /boot=68MB;88;93;0;98
/home=69357MB;253404;253409;0;253414
/var/log=818MB;970;975;0;980"

echo "$msg"
```

### System info:

telegraf 1.10.0

### Steps to reproduce:

1. Create the config and the script files.
2. Run `telegraf --config ./inputs.exec.conf --test`

### Expected behavior:
> nagios_state,host=localhost state=0i 1552677172000000000
> nagios,host=localhost,perfdata=/,unit=MB critical_gt=5958,critical_lt=0,max=5968,min=0,value=2643,warning_gt=5948,warning_lt=0 1552677172000000000
> nagios,host=localhost,perfdata=/boot,unit=MB critical_gt=93,critical_lt=0,max=98,min=0,value=68,warning_gt=88,warning_lt=0 1552677172000000000
> nagios,host=localhost,perfdata=/home,unit=MB critical_gt=253409,critical_lt=0,max=253414,min=0,value=69357,warning_gt=253404,warning_lt=0 1552677172000000000
nagios,host=localhost,perfdata=/var/log,unit=MB critical_gt=975,critical_lt=0,max=253414,min=0,value=980,warning_gt=970,warning_lt=0 1552677172000000000

### Actual behavior:
> nagios_state,host=localhost state=0i 1552677172000000000
> nagios,host=localhost,perfdata=/,unit=MB critical_gt=5958,critical_lt=0,max=5968,min=0,value=2643,warning_gt=5948,warning_lt=0 1552677172000000000
> nagios,host=localhost,perfdata=/boot,unit=MB critical_gt=93,critical_lt=0,max=98,min=0,value=68,warning_gt=88,warning_lt=0 1552677172000000000

### Additional info
- The plugin doesn't parse extended Nagios format properly.
- I would like to have a message reported with the state as well. Shourt message and the long message too.

**Comment by sergeykhegay** [comment]
Do you mind if I take a stab at this?

- Proper parsing is an easy fix.
- Extended status will require me to pass the status code to the parser (probably just an extra byte to the parser).

**Comment by glinton** [comment]
> Do you mind if I take a stab at this?

Absolutely! Consider it yours, we'll keep an eye out for a PR :slightly_smiling_face:
