### ISSUE TITLE
Telegraf 1.10 Windows 2012 R2  - Logparser input hanging in time

### ISSUE THREAD

**Issue by idMaxCZ** [influxdata/telegraf#5597]
### Relevant telegraf.conf:

> [agent]
>   interval = "1m"
>   round_interval = true
>   metric_batch_size = 1000
>   metric_buffer_limit = 10000
>   collection_jitter = "0s"
>   flush_interval = "1m"
>   flush_jitter = "0s"
>   precision = ""
> 
>   debug = true
>   quiet = false
>   logfile = "D:/Logs/telegraf.log"
>   hostname = ""
>   omit_hostname = false
> 
> [[outputs.influxdb]]
>   urls = ["http://somewhere:8086"]
>   database = "telegraf"
>   skip_database_creation = true
>   timeout = "5s"
>   username = "servers"
>   password = ""
> 
> [[inputs.logparser]]
>   files = ["D:/Logs/access.*.log"]
>   from_beginning = false
>   watch_method = "poll"
>   [inputs.logparser.grok]
>     measurement = "logs2"
>     patterns = ["%{COMMON_LOG_FORMAT}"]  

### System info:
Windows Server 2012 R2
Telegraf 1.10 x64 Windows
Logs from Apache 

### Steps to reproduce:

1. Telegraf running as service with described configuration
2. After processing few thousend lines from access log telegraph stop reading source log:

> 2019-03-18T11:26:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:27:00Z D! [outputs.influxdb] wrote batch of 126 metrics in 46.7772ms
> 2019-03-18T11:27:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:28:00Z D! [outputs.influxdb] wrote batch of 250 metrics in 48.9416ms
> 2019-03-18T11:28:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:29:00Z D! [outputs.influxdb] wrote batch of 177 metrics in 48.9762ms
> 2019-03-18T11:29:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:30:00Z D! [outputs.influxdb] wrote batch of 74 metrics in 32.6759ms
> 2019-03-18T11:30:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:31:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:32:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:33:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:34:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:35:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:36:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
> 2019-03-18T11:37:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 

3. Telegraf service is still alive, memory and cpu is normal 
Access log continuously growing each minute (30-1000 entries per minute)

**Comment by glinton** [comment]
Do you know if the original access logfile got rotated out, truncated, or deleted?

**Comment by idMaxCZ** [comment]
Original file is rotated just over midnight  (Apache default component rotatelog.exe). But this behavior is happen randomly. Log is never deleted or truncated.

**Comment by idMaxCZ** [comment]
One more clue from log:
When I stop Win service Telegraf, this is included in log:

`2019-03-22T09:15:51Z D! [agent] Stopping service inputs
2019-03-22T09:15:51Z D! tail dropped for file: D:\Logs\access.2019.03.22.log
2019-03-22T09:15:51Z E! **Error stopping tail** on file D:\Logs\access.2019.03.22.log`

**Comment by danielnelson** [comment]
Would you be willing to try out a experimental branch that uses a different library for following the logfiles?  It is built off the code in #5347:

- [telegraf-1.11.0~42936e1e_windows_amd64.zip](https://30038-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.11.0~42936e1e_windows_amd64.zip)

The configuration file would need to be changed like so:
```toml
[[inputs.tail2]]
  files = ["D:/Logs/access.*.log"]
  from_beginning = false
  watch_method = "poll"
  name_override = "logs2"
  grok_patterns = ["%{COMMON_LOG_FORMAT}"]
```

**Comment by idMaxCZ** [comment]
@danielnelson Thank you very much for your help. Tail2 plugin working fine. I hope will be soon merged to master :)
