### ISSUE TITLE
Prometheus unexpected counter resets (1.9.3 -> 1.10.0)

### ISSUE THREAD

**Issue by leehuk** [influxdata/telegraf#5598]
### Relevant telegraf.conf:

/etc/telegraf/telegraf.conf
```
[agent]
flush_interval = "10s"
flush_jitter = "5s"
hostname = "gueagamgisspinmon02"
interval = "10s"
round_interval = true
[tags]
```

/etc/telegraf/telegraf.d/default_outputs.conf
```
[outputs.prometheus_client]
listen = ":9126"
```

### System info:

CentOS7
telegraf-1.10.0 (rpm)

### Steps to reproduce:

As per #5431 we are seeing counter resets for the prometheus plugin which started in telegraf-1.9.3.  This was closed and believed resolved within telegraf-1.10.0 due to #5534 -- however we are still seeing the issue.

### Expected behavior:

There are no counter resets in the output for prometheus.

### Actual behavior:

There are unexpected counter resets being provided to prometheus.

### Additional info:

The output below is from a tcpdump capturing prometheus http requests to telegraf (with the date being the http response header and also the metric name redacted). 
```
Date: Mon, 18 Mar 2019 15:32:21 GMT
...
redacted_metric{url="http://localhost:8080/metrics"} 3.5575724e+07

Date: Mon, 18 Mar 2019 15:32:31 GMT
...
redacted_metric{url="http://localhost:8080/metrics"} 3.5575925e+07

Date: Mon, 18 Mar 2019 15:32:41 GMT
...
redacted_metric{url="http://localhost:8080/metrics"} 3.557582e+07
```

The metrics telegraf sent at 15:32:41 were lower than at 15:32:31 which triggered a counter reset within prometheus -- although there was no actual counter reset in the data telegraf had obtained itself.

**Comment by sspaink** [comment]
Closing as there have been a lot of changes to the Prometheus plugin since this issue was opened, please try the latest version and if you are having the same issue please re-open so we can investigate.
