### ISSUE TITLE
win_perf_counters "SMB Server Shares" and "SMB Client Shares".

### ISSUE THREAD

**Issue by Erikov-K** [influxdata/telegraf#5599]
Hello!

I have some troubles with "**win_perf_counters**" input plugin.
I want to collect data from "**SMB Server Shares**" and "**SMB Client Shares**".
Instance objects of this counters contain \ (backslash)  in their names.

Example: 
Show all available counters from measurement "SMB Client Shares":
> typeperf -q "SMB Client Shares"
> \SMB Client Shares(\*)\Credit Stalls/sec
> \SMB Client Shares(\*)\Metadata Requests/sec
> \SMB Client Shares(\*)\Avg. Data Queue Length
> \SMB Client Shares(\*)\Avg. Write Queue Length
> \SMB Client Shares(\*)\Avg. Read Queue Length
> \SMB Client Shares(\*)\Current Data Queue Length
> \SMB Client Shares(\*)\Avg. sec/Data Request
> \SMB Client Shares(\*)\Avg. Data Bytes/Request
> \SMB Client Shares(\*)\Data Requests/sec
> \SMB Client Shares(\*)\Data Bytes/sec
> \SMB Client Shares(\*)\Avg. sec/Write
> \SMB Client Shares(\*)\Avg. sec/Read
> \SMB Client Shares(\*)\Avg. Bytes/Write
> \SMB Client Shares(\*)\Avg. Bytes/Read
> \SMB Client Shares(\*)\Write Requests/sec
> \SMB Client Shares(\*)\Read Requests/sec
> \SMB Client Shares(\*)\Write Bytes/sec
> \SMB Client Shares(\*)\Read Bytes/sec
> Exiting, please wait...
> The command completed successfully.

Show all available counters from measurement "SMB Client Shares" with all instances objects:
> typeperf -qx "SMB Client Shares"

So, command for measure specific share with specific counter instance object looks like:
> typeperf "\SMB Client Shares(\ServerName.DomainName\ShareName)\Avg. Data Bytes/Request"

And here are my problem!
Input plugin "**win_perf_counters.go**" has this code:
> var sanitizedChars = strings.NewReplacer("/sec", "_persec", "/Sec", "_persec",	" ", "_", "%", "Percent", `\`, "")

… which removes backslash from instance name!

So I finally have instance looks like "**ServerName.DomainNameShareName**" instead of "**\ServerName.DomainName\ShareName**"

May be it will be more correct don't remove characters such as \ (backslash) ?
For example: replace them by - (dash) or _ (bottom dash) ?
Also, "/sec" replaced with "_persec" automatically.
But what about "/Request", "/Write" or "/Read" ?

For each of this counters I need to use "processors.rename.replace"
Also there are counters which ends with dot (Example: "Avg. *").
What about them?

Thank you!

**Comment by Erikov-K** [comment]
I solved my problem by adding **processors.strings.replace** to config file.
After processing the instance objects looks like **"ShareName"**
> [[processors.strings.replace]]
>       tag = "instance"
>       old = "ServerName"
>       new = ""
> 
> [[processors.strings.replace]]
>       tag = "instance"
>       old = "ServerName.DomainName"
>       new = ""

I think, it will be a good idea to correctly processing \ (backslash) in future telegraf builds! :-)

**Comment by Erikov-K** [comment]
I solved my problem by adding **processors.strings.replace** to config file.
After processing the instance objects looks like "ShareName".

> [[processors.strings]]
>     namepass = ["smb_client_shares"]
>     
>     [[processors.strings.replace]]
>       tag = "instance"
>       old = "ServerName.DomainName"
>       new = ""
> 
>     [[processors.strings.replace]]
>       tag = "instance"
>       old = "ServerName"
>       new = ""
> 

I think, it will be a good idea to correctly processing \ (backslash) in future telegraf builds! :-)

**Comment by danielnelson** [comment]
I agree it would be better to convert `\` -> `_` and we should this for 1.11.0.

Bigger picture, maybe we should just stop processing the instance altogether other than perhaps trimming surrounding whitespace.  I don't see a reason to modify it since it is just being used as a tag **value** and not as a tag **key**.  For the measurement and field keys I'd like to be even more aggressive moving to `[a-z_]`.  I have an issue open in #5196 and I'd love to get your input.

**Comment by abedfarvardin** [comment]
I configured samba in this way and it worked well for me
# SMB / File Server 
[[inputs.win_perf_counters]]
    [[inputs.win_perf_counters.object]]
	  ObjectName = "SMB Client Shares"
	  Counters = ["Write Bytes/sec","Read Bytes/sec","Current Data Queue Length","Metadata Requests/sec"]
	  Instances = ["*"]
	  Measurement = "win_smb"

**Comment by sjwang90** [comment]
Closing issue - please comment any breaking changes in regards to win_per_counters configs at #5196
