### ISSUE TITLE
internal plugin : metrics count wrong from 1.10 on

### ISSUE THREAD

**Issue by bolek2000** [influxdata/telegraf#5604]
### Relevant telegraf.conf:
2019-03-19T06:40:07Z I! Starting Telegraf 1.10.0
2019-03-19T06:40:07Z I! Loaded inputs: diskio kernel mem processes swap netstat nginx disk system internal net procstat cpu memcached mysql httpjson phpfpm tail
2019-03-19T06:40:07Z I! Loaded aggregators: 
2019-03-19T06:40:07Z I! Loaded processors: regex regex regex
2019-03-19T06:40:07Z I! Loaded outputs: influxdb

### System info:

Telegraf 1.10, Ubuntu 14.04

### Steps to reproduce:

1. Install version prior to 1.10
2. Send thousands of metrics via tail plugin regularly
3. Graph metrics from internal_agent ->  metrics_written (counter with non-negative-derivative)
4. Upgrade telegraf to 1.10 

### Expected behavior:
Constant stream of metrics visible in graph

### Actual behavior:

number of metrics_witten drops after upgrade 

### Additional info:

![image](https://user-images.githubusercontent.com/29039424/54598617-2b351080-4a39-11e9-9430-525d01925d40.png)

We need to restart telegraf every 10 minutes to have a stable logparsing with the tail plugin. We ingest 10 minutes of preprocessed nginx access.logs per interval. The behavior of telegraf with logparsing changes from release to release, so I need to investigate this with 1.10 again with multiple machines in a another issue.

**Comment by danielnelson** [comment]
I'm not seeing this behavior myself, though I'm not using tail in this way.  What version of Telegraf are you coming from and can you reduce the reproduction steps to a simpler setup?  Do you still see this behavior without the tail plugin?

**Comment by bolek2000** [comment]
I realized that this happens also on other machines, where I changed from regular reload to restart of the agent every 10 minutes (where I parse logs with tail_plugin). So the counters are getting reset every 10 minutes. On machines where the counters are not reset all the time I don't see this. When I look into the DB directly the amount of metrics_witten seems normal (in all cases), so this seems to be a presentation problem rather than a metrics problem.

**Comment by danielnelson** [comment]
Closing, but can you remind me again why you are restarting every 10 minutes?

**Comment by danielnelson** [comment]
@bolek2000 Would you be able to test out a new experimental implementation of the tail plugin based on #5347?

- [telegraf_1.11.0~42936e1e-0_amd64.deb](https://30038-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.11.0~42936e1e-0_amd64.deb)

You will need to use `tail2` as the plugin name, but the other options are the same.

**Comment by bolek2000** [comment]
Hi Daniel, these 10 minute reload/restarts come from working around several problems with logparser/tail:
1. plugins not beeing able to handle unchronologic buffered logs (thats why we preprocess/sort the logs)
2. different bugs with recreating logfiles / tail not realizing that files were overwritten etc. This is still happening in 1.10. So I need to restart/reload telegraf every time I recreate the logfile to get a stable flow of data

**Comment by bolek2000** [comment]
I tested the 1.11 build, but can not get it running with my config and tail2:
```
[[inputs.tail2]]
    tagexclude = ["path"]
    name_override = "wp_access_log"
   files = ["/var/log/nginx/wp_access.log.sorted.10min"]
   from_beginning = true
   watch_method = "inotify"
   pipe =  false      
  data_format = "grok"
  grok_patterns = ['''
%{CLIENT:client_ip:tag} %{NOTSPACE:ident:drop} %{NOTSPACE:auth:drop} \[%{HTTPDATE:ts:ts-httpd}\] \"%{WORD:http_method:drop} %{DATA:pathlevel1:tag} HTTP\/%{NUMBER:http_version:drop}\" %{RESPONSE_CODE} (?:%{NUMBER:resp_bytes:int}|-) \"%{DATA:referer:drop}\" \"%{DATA:user_agent:drop}\" +(?:%{NUMBER:request_time:float}|-) %{LOAD_BALANCING_TIMES:lb_times:drop}(?:%{NUMBER:upstream_time:float}|-) %{GREEDYDATA:pipe:drop}+ \"%{GREEDYDATA:gzip_ratio:drop}\" \"%{DATA:domain:tag}~%{DATA:mobile:tag} %{DATA:bot:tag} %{DATA:cache_status:tag}\"
        ''']
        grok_custom_patterns = '''
        PATHLEVEL1 \/([^ "/?]+)?
        LOAD_BALANCING_TIMES (((\d+\.\d+),\s)+)?
        '''
  [inputs.tail2.tags]
    path_group = "various"
```

```
2019-03-27T08:40:06Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.d/wp_access_
logparser.conf, line 21: field corresponding to `pipe' is not defined in `*tail2.Tail'
```

I commented out the `pipe` config option, but after that I am not able to start telegraf successfully. The process is stale while loading the inputs and I need to kill it (normal restart doesn't work)

```
2019-03-27T08:41:16Z I! Starting Telegraf 
2019-03-27T08:41:16Z I! Loaded inputs: net netstat nginx procstat disk mem swap system internal cpu diskio kernel processes memcached mysql httpjson phpfpm tail2
2019-03-27T08:41:16Z I! Loaded aggregators: 
2019-03-27T08:41:16Z I! Loaded processors: regex regex regex
2019-03-27T08:41:16Z I! Loaded outputs: influxdb
2019-03-27T08:41:16Z I! Tags enabled: dc=dc-example host=hostname
2019-03-27T08:41:16Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"hostname", Flush Interval:10s
2019-03-27T08:41:16Z D! [agent] Connecting outputs
2019-03-27T08:41:16Z D! [agent] Attempting connection to output: influxdb
2019-03-27T08:41:16Z D! [agent] Successfully connected to output: influxdb
2019-03-27T08:41:16Z D! [agent] Starting service inputs
```

**Comment by danielnelson** [comment]
Thanks for testing, this is too bad but I know it is still being worked on.

cc @sgtsquiggs

**Comment by sgtsquiggs** [comment]
Can you give some detail on the log file? Is it being regularly truncated and rewritten?

**Comment by bolek2000** [comment]
Yes, the logfile is overwritten every 10 minutes with a bash script that outputs the new lines with `>` to the logfile. It is not explicitely truncated before.
