### ISSUE TITLE
Disable uptime_format in the system plugin

### ISSUE THREAD

**Issue by jregovic** [influxdata/telegraf#5606]
## Feature Request

The field uptime_format is the string representation of asystem's uptime. As this can easily be calculated by a number of tools, there appears to be little utility in having the plugin output a string by default.

### Proposal:
Disable uptime_format in the system plugin

### Current behavior:
The field is included in output:
system,host=host.local uptime_format="1 day,  1:18" 553008764000000000
### Desired behavior:
Do not send the string
### Use case: [Why is this important (helps with prioritizing requests)]
Storing strings is more costly than storing integer data and a system's uptime can easily be calculated by the integer field "uptime". Grafana can do this simply as a single-stat function.
The use of uptime as a string serves no purpose for alerting and is just storing redundant data in a less efficient way.

**Comment by sslupsky** [comment]
Can you use fielddrop to drop it?

**Comment by jregovic** [comment]
You can use fielddrop, my my point is that there is essentially no reason to even send the string at all.

If I want to detect a drop in uptime, it is easier to look for a negative derivative from "uptime".

If I want to display the uptime as a number of days, hours, minutes, and seconds, I can can convert that from "uptime". Sending the string is just redundant.

**Comment by danielnelson** [comment]
We can deprecate this field and remove it in Telegraf 2.0, but for now you will need to use fielddrop.
