### ISSUE TITLE
Cloudwatch Input: min/max/average/sum etc selective statistics

### ISSUE THREAD

**Issue by CpuID** [influxdata/telegraf#5609]
## Feature Request

It would be beneficial (for AWS costs) to be able to select specific "statistics" only for the given metrics/dimensions, so when pulling a high volume of metrics from Cloudwatch you can keep costs under control.

### Proposal:

Eg. you may only care about `average` and `max`, but not `min` or `sum`. This would halve the % of retrievals involved.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html seems to provide the ability to specify, there also seems to be some on https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html

### Current behavior:

Retrieves all "statistics" for a given metric / dimension, which is somewhere around 6~ each.

### Desired behavior:

Selectively pull the ones you want.

### Use case: [Why is this important (helps with prioritizing requests)]

End user cost, plus this will have a rate limit benefit also (efficiency).

**Comment by CpuID** [comment]
Example from another project's implementation: https://github.com/crccheck/cloudwatch-to-graphite/blob/master/sample_templates/ec2.yml.j2#L9-L11

**Comment by CpuID** [comment]
Related: https://github.com/influxdata/telegraf/issues/5420 (same goal of optimizing traffic to Cloudwatch, different approach). Both probably complement eachother tbh.

**Comment by danielnelson** [comment]
I think this should be fairly easy to do, we should try to add this in while doing the #5420 improvement.

**Comment by CpuID** [comment]
@glinton ping for visibility, as per @danielnelson 's suggestion. Feel free to get the core functionality of https://github.com/influxdata/telegraf/issues/5420 working first, if you think you can sneak this into your improvements it would be awesome :)

lmk if you become time constrained for any reason, and I can see if I can find time to collaborate and get it over the line

**Comment by CpuID** [comment]
I'm inclined to say, if @glinton has time constraints and can't get it in, get https://github.com/influxdata/telegraf/issues/5420 out of the way first to avoid having to refactor this feature request twice.

**Comment by glinton** [comment]
I've started on implementing this, hoping to have a testable build for you by EOD Monday. Glad it was brought up when it was though, thanks!
