### ISSUE TITLE
Cannot sent metrics to KairosDB over http using opentsdb output plugin

### ISSUE THREAD

**Issue by raffraffraff** [influxdata/telegraf#5614]
### Relevant telegraf.conf:
```
[[outputs.opentsdb]]
  host = "http://opentsdb.example.com"
  port = 8080
  prefix = "my_metrics."
  http_batch_size = 5000
  http_path = "api/v1/datapoints"
  debug = true
  separator = "_"
```
### System info:
Telegraf 1.10 (reproducible on all recent versions)
CentOS 7.6 (reproducible on any)
KairosDB 1.2.2, KairosDB 1.1.2

### Steps to reproduce:
Configure telegraf to use the OpenTSDB output plugin to send metrics via http to a KairosDB server.

### Expected behavior:
Telegraf should be able to send metrics to KairosDB over https using the opentsdb output plugin. KairosDB is a rewrite of OpenTSDB that uses Cassandra instead of HBase.

### Actual behavior:
Metrics do not appear in KairosDB if they are sent over https using the opentsdb output plugin.

### Additional info:
While KairosDB is a rewrite of OpenTSDB, its REST API is not 100% compatible. Key differences include:
* The JSON structure: the metric name key in OpenTSDB is 'metric', while in KairosDB it is 'name'
* The timestamp - OpenTSDB accepts epoc timestamp in seconds, but KairosDB requires it to be in milliseconds
* Using http gzip compression does not work in KairosDB by via `Content-Type: application/json` and `Content-Encoding: gzip`. Instead, KairosDB requires `Content-Type: application/gzip`

I have forked the repo, copied the existing opentsdb output plugin and modified fixed the relevant sections. I'll send a pull request.

**Comment by danielnelson** [comment]
There is some existing work on this, check out https://github.com/influxdata/telegraf/pull/3615

**Comment by raffraffraff** [comment]
Cool, thanks.  Checking it out.

**Comment by sspaink** [comment]
The pull request to implement this https://github.com/influxdata/telegraf/pull/3615 was superseded by https://github.com/influxdata/telegraf/pull/5827, unfortunately https://github.com/influxdata/telegraf/pull/5827 was closed due to inactivity. I am going to close this issue as well, but if anyone is still interested in this feature request we can reopen it and look into reviving the pull request.
