### ISSUE TITLE
Remove duplicate devices in disk plugin to match df

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5615]
### Relevant telegraf.conf:
[[inputs.disk]]
 
   ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

### System info:

telegraf version : 1.10.1(running inside container)
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
### Steps to reproduce:

1. Telegraf running inside a docker container to collect docker host metrics
2. The following ENV vars are from with-in the container (/ mounted as /hostfs)
HOST_VAR=/hostfs/var
HOST_MOUNT_PREFIX=/hostfs
HOST_PROC=/hostfs/proc
HOST_SYS=/hostfs/sys
HOST_ETC=/hostfs/etc

### Expected behavior:
Collect mountpoints as shown by df (on the host)
Not collect mount points not shown by df on the host (ex;- /etc/hostname; etc/resolv.conf; /etc/hosts ...)

### Actual behavior:
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/ free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet/pods/6ddea913-4417-11e9-8568-328ff15fbde2/volume-subpaths/azureproxy-nginx/azureproxy/0 free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sdb1,nodeName=aks-agentpool-28302676-0,path=/mnt free=13856145408i,used=36687872i,used_percent=0.26407768135255416 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet/pods/6ddea913-4417-11e9-8568-328ff15fbde2/volume-subpaths/azureproxy-nginx/azureproxy/0 free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/var/log free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/dev/termination-log free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/etc/resolv.conf free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/etc/hostname free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/etc/hosts free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000
> disk,device=sda1,nodeName=aks-agentpool-28302676-0,path=/var/lib/docker/containers free=21503504384i,used=9638653952i,used_percent=30.95050075850979 1553133297000000000

### Additional info:
Below is the df -h output from the same node (host)

Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           697M  1.5M  696M   1% /run
/dev/sda1        30G  9.0G   21G  31% /
tmpfs           3.5G     0  3.5G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.5G     0  3.5G   0% /sys/fs/cgroup
/dev/sdb1        14G   35M   13G   1% /mnt
tmpfs           697M     0  697M   0% /run/user/1001

**Comment by vishiy** [comment]
Looks it also gets mounts as seen by container as well ? How will one exclude it ?

**Comment by danielnelson** [comment]
Can you help me debug this?  I have a few questions that would help me to have a better understanding of what is going on:

- It looks like you are filtering some tags from the example output, can you show this with the full set of output?
- Ubuntu 16.04.5 LTS is the Docker engine host?
- What version of Docker are you using? Can you run `docker version`
- Is the docker image you are using publicly available, if not can you let me know what the base image is for it?

**Comment by vishiy** [comment]
@danielnelson 
1) below --

> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=ro,nodeName=aks-agentpool-28302676-0,path=/ free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet/pods/6ddea913-4417-11e9-8568-328ff15fbde2/volume-subpaths/azureproxy-nginx/azureproxy/0 free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sdb1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/mnt free=13856145408i,inodes_free=917492i,inodes_total=917504i,inodes_used=12i,total=14661173248i,used=36687872i,used_percent=0.26407768135255416 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/var/lib/kubelet/pods/6ddea913-4417-11e9-8568-328ff15fbde2/volume-subpaths/azureproxy-nginx/azureproxy/0 free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/var/log free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/dev/termination-log free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/etc/resolv.conf free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/etc/hostname free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/etc/hosts free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000
> disk,AKS_RESOURCE_ID=/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourcegroups/acitest/providers/Microsoft.ContainerService/managedClusters/vishwatelegrafTCP,AgentVersion=ciprod01092019,ClusterName=$AKS_CLUSTER_NAME,ClusterType=AKS,Computer=aks-agentpool-28302676-0,ControllerType=DaemonSet,Region=westeurope,device=sda1,fstype=ext4,mode=rw,nodeName=aks-agentpool-28302676-0,path=/var/lib/docker/containers free=21495963648i,inodes_free=3630345i,inodes_total=3840000i,inodes_used=209655i,total=31158935552i,used=9646194688i,used_percent=30.97471467431691 1553141270000000000

2) 16.04.5 LTS is docker engine host
3) azureuser@aks-agentpool-28302676-0:~$ docker version
Client:
 Version:           3.0.3
 API version:       1.40
 Go version:        go1.11.4
 Git commit:        48bd4c6d
 Built:             Wed Jan 23 16:17:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Fri Jan 25 01:45:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
4) Base image of the container is microsoft/oms:ciprod0312201
base image for the above docker image 
Ubuntu 16.04.5 LTS

**Comment by vishiy** [comment]
@danielnelson - To workaround this as you invetigate this, should i just manully drop these metrics based on tag values ? How do i do that ? Thank you.

**Comment by danielnelson** [comment]
Yes, I suggest using tagpass or tagdrop, whichever is more convenient.  The first example here is pretty close to what you need: 
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#filtering-examples

**Comment by vishiy** [comment]
@danielnelson Thank you! Will try that today.

**Comment by vishiy** [comment]
@danielnelson , exclusion worked. Please let me know when u have a fix and i can validate (even nightly builds should be fine).

**Comment by vvershkov** [comment]
I have a kind of similar issue, but I am thinking about mountpoints whitelist instead.
But as I can it doesn't support regexp or masks or something like that. Am I right or maybe I am missing something?

**Comment by danielnelson** [comment]
The `mount_points` option only supports exact values, no glob/regex support.  You could open a new issue for this.

**Comment by danielnelson** [comment]
Just a quick update: It appears`df` strips devices that appear more than once from its output, unless you use the `-a` option.  I tried to duplicate this behavior in the disk plugin but it is proving difficult to do this with the information we currently collect.

**Comment by powersj** [comment]
Hi,

Looks like some workarounds and alternatives were offered here. Changing up the `disk` plugin to match `df` is not something we are going to further look into at this time. If there is some larger issue at hand please feel free to file a new bug using the latest telegraf and steps to reproduce.

Thanks
