### ISSUE TITLE
Add support for nginx-sts module

### ISSUE THREAD

**Issue by Freakin** [influxdata/telegraf#5620]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Currently there is a Telegraf `nginx_vts` input plugin, which collects metrics from `nginx-module-vts`.  The VTS module collects and provides metrics on nginx vhosts.

There is a `nginx-module-sts`, which provides metrics on UDP/TCP streams instead of HTTP vHosts.  There is no corresponding Telegraf input plugin.

Proposing development of an input plugin to support the nginx-module-sts (https://github.com/vozlt/nginx-module-sts).

### Current behavior:
Currently the Plugin for nginx-sts does not exist, only plugin for nginx-vts

### Desired behavior:
Plugin exists

### Use case: [Why is this important (helps with prioritizing requests)]
nginx is a popular choice for load balancing tcp/udp streams not associated with HTTP.  The nginx module to provide metrics already exists, and the JSON body returned back by the sts module is very similar to the body returned back by the already instruments vts module.  This leads to a lower level of effort than developing from scratch.

**Comment by danielnelson** [comment]
This would be a nice addition.  In the meantime, you may be able to use the the `http` input with the `/status/format/json` resource or the `prometheus` input with `/status/format/prometheus` to collect the stats.

**Comment by zdmytriv** [comment]
once that PR is merged, dashoard like this https://grafana.com/grafana/dashboards/11967 can be setup
