### ISSUE TITLE
varnish plugin should cleanup backend metric name

### ISSUE THREAD

**Issue by danielmotaleite** [influxdata/telegraf#5622]
## Feature Request
Varnish plugin dumps the backend list as metric names, making this fields mostly useless for query. We need a common name for the metric and the backend names and profiles should be pushed to labels

### Proposal:
Either parse the varnish VBE metrics and extract the labels for the backends instead of dumping then in the metric name OR rename varnish VBE metric to a more friendly name like varnish_vbe_* , so we can try to fix this outside by renaming the metrics (at least prometheus can do this, do not know about other tools)

### Current behavior:
right now if we request the varnish plugin to gather backend metrics, we get this:

![image](https://user-images.githubusercontent.com/11890049/54840202-5aab7d80-4cc4-11e9-82b1-0f6bd8c0862c.png)

I can't even try to rename/relabel this in prometheus, as it's directly a varnish_*, so i can't create a rule to parse this as it would also parse all other metrics. There is no common anchor for all backend metrics names, in my example, the boot is the profile name, loading more profiles i can get any name (eg: profile named cache), so it can collide with existent metrics

### Desired behavior:
The current setup is good for all metrics except VBE, with it, its mostly useless, i can't use those names in anything as it would require me to know the profile, backend name and ip. instead it should take the VBE metric as a special metric and extract the labels from the name and create the varnish_vbe_{comm,happy,req,etc}

### Use case: [Why is this important (helps with prioritizing requests)]
Getting backend metrics and health status in varnish is important information, but the plugin takes the VBE metric as a normal metric and it should be special as it can have random info. Current setup can overload any system with useless metric names, making everything slow

**Comment by danielnelson** [comment]
Could you attach the output of `varnishstat -1`or, if you are using an instance_name, `varnishstat -1 -n INSTANCE_NAME`?

As a possible workaround you ought to be able to create a wrapper for the varnishstat command that strips out the unwanted cause of the metrics.

**Comment by danielmotaleite** [comment]
Here is a sample:
[varnishstat.txt](https://github.com/influxdata/telegraf/files/3039271/varnishstat.txt)

So for 
VBE.vcl_ceb2d057-acd8-4061-9f03-803f6b693363.thumbor(172.26.57.82).req                            2         0.00 Backend requests sent  

instead of 

              varnish_vcl_ceb2d057-acd8-4061-9f03-803f6b693363_thumbor_172_26_57_82__req

it should be 

              varnish_vbe_req{profile="vcl_ceb2d057-acd8-4061-9f03-803f6b693363", backend="thumbor",address="172.26.57.82"}

As the profile name can't include dots, i think its safe to break those fields on the dot

As for the workaround, it could work, but knowing what backend or profile is used is really useful, that would only workaround half of the problem :)
but thanks anyway for the idea! i will be trying to workaround this in my setup with the prometheus metric_relabel... when i have some more free time :)

**Comment by danielnelson** [comment]
Thank you for adding the sample input.  This definitely looks tricky to parse in a well structured way, and I wonder if the `-j` option to output in JSON would simplify things.

**Comment by danielmotaleite** [comment]
just testes and the `-j` show the same info, except it is now in a json instead of a white-space table, the name of the backends is exactly the same

from what i can see, varnishstat use `.` and  `( )` symbols as separators, trying to use then in the vcl name makes varnish abort the vcl loading, so looks like its save to use then 
So this regex looks like it works

        VBE.([^.]+).([^.(]+)\(([0-9.]*)\).(.*)

where $1 is the profile, $2 is the backend name, $3 is the ip of the backend, $4 is the type of metric
so the output would be `varnish_vbe_$4(profile=$1,backend=$2,backend_address=$3)`

**Comment by ismaelpuerto** [comment]
I did fork with fix this issue, it is a WIP: https://github.com/ismaelpuerto/telegraf/tree/master/plugins/inputs/varnish

```
# /home/vagrant/telegraf --config telegraf.conf --input-filter varnish --test 
2019-12-05T15:03:18Z I! Starting Telegraf 
> varnish,host=agent,section=MAIN,vcl=reload_20191205_113452_5035 backend_busy=0i,backend_conn=0i,backend_fail=0i,backend_recycle=0i,backend_req=0i,backend_retry=0i,backend_reuse=0i,backend_unhealthy=0i,bans=1i,bans_added=1i,bans_completed
=1i,bans_deleted=0i,bans_dups=0i,bans_lurker_contention=0i,bans_lurker_obj_killed=0i,bans_lurker_obj_killed_cutoff=0i,bans_lurker_tested=0i,bans_lurker_tests_tested=0i,bans_obj=0i,bans_obj_killed=0i,bans_req=0i,bans_tested=0i,bans_tests_te
sted=0i,busy_killed=0i,busy_sleep=0i,busy_wakeup=0i,cache_hit=0i,cache_hit_grace=0i,cache_hitmiss=0i,cache_hitpass=0i,cache_miss=0i,client_req=0i,client_req_400=0i,client_req_417=0i,client_resp_500=0i,esi_errors=0i,esi_maxdepth=0i,esi_warn
ings=0i,exp_mailed=0i,exp_received=0i,fetch_1xx=0i,fetch_204=0i,fetch_304=0i,fetch_bad=0i,fetch_chunked=0i,fetch_eof=0i,fetch_failed=0i,fetch_fast304=0i,fetch_head=0i,fetch_length=0i,fetch_no_thread=0i,fetch_none=0i,goto_dns_cache_hits=0i,
goto_dns_lookup_fails=0i,goto_dns_lookups=2278i,hcb_insert=0i,hcb_lock=0i,hcb_nolock=0i,losthdr=0i,n_backend=4i,n_expired=0i,n_gunzip=0i,n_gzip=0i,n_lru_limited=0i,n_lru_moved=0i,n_lru_nuked=0i,n_obj_purged=0i,n_object=0i,n_objectcore=0i,n
_objecthead=0i,n_purges=0i,n_test_gunzip=0i,n_vampireobject=0i,n_vcl=2i,n_vcl_avail=2i,n_vcl_discard=0i,pools=2i,req_dropped=0i,s_fetch=0i,s_pass=0i,s_pipe=0i,s_pipe_hdrbytes=0i,s_pipe_in=0i,s_pipe_out=0i,s_req_bodybytes=0i,s_req_hdrbytes=
0i,s_resp_bodybytes=0i,s_resp_hdrbytes=0i,s_sess=0i,s_synth=0i,sc_overload=0i,sc_pipe_overflow=0i,sc_range_short=0i,sc_rem_close=0i,sc_req_close=0i,sc_req_http10=0i,sc_req_http20=0i,sc_resp_close=0i,sc_rx_bad=0i,sc_rx_body=0i,sc_rx_junk=0i
,sc_rx_overflow=0i,sc_rx_timeout=0i,sc_stream_failure=0i,sc_tx_eof=0i,sc_tx_error=0i,sc_tx_pipe=0i,sc_vcl_failure=0i,sc_vdp_error=0i,sess_closed=0i,sess_closed_err=0i,sess_conn=0i,sess_drop=0i,sess_dropped=0i,sess_fail=0i,sess_fail_ebadf=0
i,sess_fail_econnaborted=0i,sess_fail_eintr=0i,sess_fail_emfile=0i,sess_fail_enomem=0i,sess_fail_other=0i,sess_herd=0i,sess_queued=0i,sess_readahead=0i,shm_cont=1i,shm_cycles=0i,shm_flushes=0i,shm_records=21607i,shm_writes=21607i,summs=910
8i,thread_queue_len=0i,threads=200i,threads_created=200i,threads_destroyed=0i,threads_failed=0i,threads_limited=0i,uptime=22030i,vcl_fail=0i,vmods=5i,ws_backend_overflow=0i,ws_client_overflow=0i,ws_session_overflow=0i,ws_thread_overflow=0i
 1575558199000000000
> varnish,host=agent,section=VBE,vcl=reload_20191205_113452_5035 default.bereq_bodybytes=0i,default.bereq_hdrbytes=0i,default.beresp_bodybytes=0i,default.beresp_hdrbytes=0i,default.busy=0i,default.conn=0i,default.fail=0i,default.fail_eacce
s=0i,default.fail_eaddrnotavail=0i,default.fail_econnrefused=2501i,default.fail_enetunreach=0i,default.fail_etimedout=0i,default.fail_other=0i,default.happy=0i,default.helddown=0i,default.pipe_hdrbytes=0i,default.pipe_in=0i,default.pipe_ou
t=0i,default.req=0i,default.unhealthy=0i 1575558199000000000
```
