### ISSUE TITLE
SNMP not working, timeout

### ISSUE THREAD

**Issue by DB-Vincent** [influxdata/telegraf#5634]
### Relevant telegraf.conf:
```
[agent] 
  interval="60s"   
  metric_batch_size = 1000
  metric_buffer_limit = 10000                            

# OUTPUT  
[[outputs.influxdb]]  
  urls = ["http://127.0.0.1:8086"]  
  database = "network"
 
# INPUT
[[inputs.snmp]]
  agents = [ "192.168.1.4:162" ] 
  version = 1
  community = "public" 
  timeout = "10s"   
  retries = 3 

  [[inputs.snmp.field]]
    name = "snmp"
    oid = "IF-MIB::ifXTable"
```
### System info:

Using Debian 9.8, Telegraf 1.10.1, InfluxDB 1.7.4, SNMPv1

### Steps to reproduce:

1. Setup HP v1910 switch to output SNMP to 192.168.1.13 (Telegraf and InfluxDB server)
2. Configure telegraf
3. Start telegraf

### Expected behavior:

Telegraf collecting the data the switch is outputting (I checked with SNMPWalk and got results) and sending it to InfluxDB.

### Actual behavior:

No data being collected, telegraf times out.
```
vincent@vdbdeb002:~$ telegraf
Starting Telegraf 1.10.1
Using config file: /etc/telegraf/telegraf.conf
Loaded inputs: snmp
Loaded aggregators:
Loaded processors:
Loaded outputs: influxdb
Tags enabled: host=vdbdeb002
[agent] Config: Interval:1m0s, Quiet:false, Hostname:"vdbdeb002", Flush Interval:10s
[inputs.snmp]: Error in plugin: agent 192.168.1.4:162: performing get on field snmp: Request timeout (after 3 retries)
```

### Additional info:

N/A

**Comment by Gelob** [comment]
Are you sure your agent shouldn't be using port 161? 162 is usually for SNMP traps. What is your snmpwalk cmd look like?

  agents = [ "192.168.1.4:161" ]

**Comment by DB-Vincent** [comment]
Oh dear, I feel stupid right now. That was indeed the issue. Thanks a lot!
