### ISSUE TITLE
Tags Leaking while batching

### ISSUE THREAD

**Issue by rbkasat** [influxdata/telegraf#5636]
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

Although Its very hard to reproduce but we are seeing a bug in telegraf. We currently write batches to influxdb while reading data from kafka.
Sometimes the tags are spilled from one measurement into others and causing a bunch of unrelated tags to appear in different measurements.
We read a huge amount of data from kafka and push to influx , reading is in line protocol as well as writing inline protocol. Approximated 5 Million points per minute are processed.

### Expected behavior:
No Tag Spill
### Actual behavior:
Tags are mixed  up
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Thanks for the report, just to clarify, you are using the `kafka_consumer` input and the `influxdb` output?

To work on this, it would be very helpful if you can find a way to minimally reproduce the issue, perhaps with a fixed data set and then attempting to isolate the issue to either the input or the output by replacing them with the `file` input or output.

**Comment by rbkasat** [comment]
Thanks for the quick reply, I am using Kafka Consumer and influxdb output. points that are published to the kafka topics are from java influxdb library. 
I am trying my best to reproduce this with the dataset but since we process billions of points and this occurs suddenly from certain topic and it is hard to reproduce, but it is a big issue since once the tag is spilled it stays until next retention and increases cardinality.

**Comment by danielnelson** [comment]
Closed in #5650
