### ISSUE TITLE
Hostname override no longer works in 0.10?

### ISSUE THREAD

**Issue by anlutro** [influxdata/telegraf#565]
In my configuration, I have

```
[agent]
  hostname = "foo.bar.baz"
```

However, in InfluxDB, the machine's regular hostname is still being used.

I'm not 100% sure this was working in v0.2, but I think it was.

**Comment by jcmartins** [comment]
It's work ok for me in telegraf 0.3beta and 0.10.

**Comment by sparrc** [comment]
should be `host = "foo.bar.baz"`, not `hostname`

**Comment by anlutro** [comment]
Aha. I'm pretty sure the 0.10 generated sample config contains `hostname = ""`, though.

**Comment by sparrc** [comment]
@anlutro, oops, you're right, but I just tested and the hostname is getting overidden, are you using or editing the correct config file?

**Comment by anlutro** [comment]
Definitely, other configuration changes I make are correctly reflected. Actually when I think about it, it might be my mistake, having the wrong hostname for my local VMs. I'll double check tomorrow.
