### ISSUE TITLE
zabbix input plugin

### ISSUE THREAD

**Issue by ghost** [influxdata/telegraf#5652]
It would be very useful to have an input plugin for Zabbix directly in Telegraf.

link to official docs of Zabbix API -> https://www.zabbix.com/documentation/3.4/manual/api

At the moment for Zabbix2Influx integration there are some custom solutions mentioned here: https://www.zabbix.com/integrations/influxdb

**Comment by ru87** [comment]
Any updates on this request?

**Comment by adrianlzt** [comment]
An input plugin to get what?

**Comment by ru87** [comment]
zabbix input plugin would get metrics via api from zabbix. in zabbix you have metrics metadata in items table and effective monitoring data in history tables.

**Comment by adrianlzt** [comment]
Interesting.

Another, more complex, way could be to use the postgres input plugin and create the appropriate query.

**Comment by ru87** [comment]
Yes, this could be a solution. But you are supposing that postgres is the backend DB; in effect you can choose mysql or elasticsearch too. 

With a telegraf input plugin directly to zabbix api you are decoupling the tecnologies

**Comment by adrianlzt** [comment]
Another source of data to be queried: https://www.zabbix.com/documentation/4.0/manual/appendix/items/remote_stats

**Comment by kaisersosset** [comment]
Please , I am looking for the way to install telegraf agent to send info to zabbix, but I don´t get the way to do it. I have found this url, but I don´t find the way to use outputs.zabbix and aggregators.zabbix_lld. When I try to do it it gives me error. 

I would appreciete any help you could give me,

Regards

**Comment by adrianlzt** [comment]
Output plugin and aggregator are not yet merged upstream.
You have to compile this branch to be able to use it.

**Comment by kaisersosset** [comment]
Hello Adrian, thanks for answering. Please can you tell me where can I find those branch? I am looking for it but I can´t find.

Sorry for wasting your time. I am new on this.

Regards!

**Comment by powersj** [comment]
Hi,

I have not seen many updates on this feature request or folks showing much interest in it. I am also not clear on what metrics would be important to end-users to justify a new plugin. While there does appear to be an API endpoint with some remote metrics, which of these are actually interesting or important?

Thanks!
