### ISSUE TITLE
Telegraf SNMP Trap receiver

### ISSUE THREAD

**Issue by js-mode** [influxdata/telegraf#5655]
## Feature Request
Need a way for Telegraf to receive SNMP Traps.  Would be great to have a plugin like [[inputs.snmp.traps]] where you can  point a network switch (agent) to the Telegraf server since it is already being used to monitor SNMP metrics. 

### Proposal:
Utilize the existing [[inputs.snmp]] agent section that is already being used to authenticate using snmpv3 and add an additional section for snmp.traps that are triggered by the network switch. 

There would need to be a separate outputs plug in since this would be an event that is fired off to either a webhook, or a separate URL that is either connected to PagerDuty or SMTPserver for email. 

### Current behavior:
Telegraf monitors the switches for snmp metrics based on specific MIB/OIDs, but would be great to also be able to utilize this service to receive SNMP Traps as well. 

### Desired behavior:
Telegraf to receive snmp traps from network switch and have the ability to fire an event or send it to a special webhook (like for Slack integration) so that there is instant notification of an event that is triggered by the network device. 

### Use case: [Why is this important (helps with prioritizing requests)]
Monitoring with Telegraf is extremely important to be able to see that your environment is functioning properly, but when it is not functioning properly, that is when it is really important to know what happened or what went down.  Instead of having to look through all of the metrics that Telegraf is receiving, it would also be better to be able to receive snmp traps for this purpose.

**Comment by goller** [comment]
@js-mode thanks for writing in about this.  I'm keenly interested in more SNMP work as well.

**Comment by danielnelson** [comment]
This would be a great addition, I think we would probably set it up as a standalone plugin since it would be event-driven instead of polling.  We have an existing issue open with some discussion #4377 though so I'm going to close this issue.
