### ISSUE TITLE
Metric filtering is not working

### ISSUE THREAD

**Issue by akagalkararkin** [influxdata/telegraf#5658]
### Relevant telegraf.conf:
[[inputs.http]]

  urls = ["http://host/api/measures/component?additionalFields=periods&componentKey=vrni-ui-ut&metricKeys=line_coverage,lines"]

  ## HTTP method to use: GET or POST (case-sensitive)
  method = "GET"
  data_format = "json"
  name_prefix = "coco_java_"
  tag_keys = ["value"]
  #json_string_fields = ["value"]
  json_query = "component.measures"
  json_name_key = "metric"
  tagexclude = ["url"]
  #fielddrop = ["periods_0_index"]
  #tagexclude = ["periods_0_index"]
  #tagexclude = ["periods*"]
  #taginclude = ["value", "host"]
  #tagpass = ["value"]

[[outputs.wavefront]]
    # prefix = "telegraf."
      host = "ip_address"
      port = 2878
      metric_separator = "."
      source_override = ["hostname", "agent_host", "node_host"]
      convert_paths = true
      use_regex = false

### System info:
Linux 
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. telegraf -config http.conf -test -debug
2019-03-30T22:02:33Z I! Starting Telegraf 1.10.0
> coco_vrni_java_line_coverage,host=hostname,value=39.4 periods_0_index=1 1553983354000000000
> coco_vrni_java_lines,host=hostname,value=39984 periods_0_index=1 1553983354000000000

2.  

### Expected behavior:
Using metric filtering from https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md 
I am trying to remove -  periods_0_index.
I tried all combinations of namepass, namedrop, tagpass, tagdrop as well as modifiers fieldpass, fielddrop, taginclude, tagexclude

But couln't remove  periods_0_index
### Actual behavior:
Need correct way to remove  periods_0_index
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
Might be able to give more direct advice if you show the source JSON, but it is required to have at least one field.  If you remove it, then the entire line would be removed.  The `value` ought to be a field as well, not a tag, since it is what is being measured and you wouldn't want it to be indexed as that would give you very high cardinality.
```
[[inputs.http]]
  urls = ["http://host/api/measures/component?additionalFields=periods&componentKey=vrni-ui-ut&metricKeys=line_coverage,lines"]
  method = "GET"
  data_format = "json"
  name_prefix = "coco_java_"
  json_string_fields = ["value"]
  json_query = "component.measures"
  json_name_key = "metric"
  tagexclude = ["url"]
```

Is `value` a string in the source JSON?  If so, you might want to use the converter processor to change it to a float.  Otherwise, remove the `json_string_fields` option.

**Comment by akagalkararkin** [comment]
Thanks a lot Daniel for quick response. 

Here is the Source Rest - 
{"component":{"id":"someid","key":"ui-ut","name":"ui-ut","qualifier":"TRK","measures":[{"metric":"line_coverage","value":"39.4","periods":[{"index":1,"value":"0.0"}]},{"metric":"lines","value":"39984","periods":[{"index":1,"value":"0"}]}]},"periods":[{"index":1,"mode":"previous_version","date":"2019-03-03T09:59:53-0800"}]}

Following is my conf. I have json_string_fields commented, and I am using tag_keys -
```
[[inputs.http]]

  urls = ["http://hostname:9000/api/measures/component?additionalFields=periods&componentKey=ui-ut&metricKeys=line_coverage,lines"]
  ## Set response_timeout (default 5 seconds)
  #response_timeout = "5s"

  ## HTTP method to use: GET or POST (case-sensitive)
  method = "GET"
  data_format = "json"
  name_prefix = "coco_java_"
  tag_keys = ["value"]
  #json_string_fields = ["value"]
  json_query = "component.measures"
  json_name_key = "metric"
  tagexclude = ["url"]
  #fielddrop = ["periods_0_index"]
  #tagexclude = ["periods_0_index"]
  #tagexclude = ["periods*"]
  taginclude = ["value", "host"]
  #tagpass = ["value"]
```




Conf file without comment 
```
[[inputs.http]]

  urls = ["http://hostname:9000/api/measures/component?additionalFields=periods&componentKey=ui-ut&metricKeys=line_coverage,lines"]

  ## HTTP method to use: GET or POST (case-sensitive)
  method = "GET"
  data_format = "json"
  name_prefix = "coco_java_"
  tag_keys = ["value"]

  json_query = "component.measures"
  json_name_key = "metric"
  tagexclude = ["url"]
  taginclude = ["value", "host"]
```
This give me out as 
```
> coco_java_lines,host=webserver,value=39984 periods_0_index=1 1554146908000000000
> coco_java_line_coverage,host=webserver,value=39.4 periods_0_index=1 1554146908000000000

```


Here I need to help the above out put in one of the following format (Remove Period) - 

```
> coco_java_lines,host=webserver,value=39984 1554146908000000000
> coco_java_line_coverage,host=webserver,value=39.4 1554146908000000000

```
or remove period and add value as a metric instead of field or tag 

```
> coco_java_lines,39984 host=webserver 1554146908000000000
> coco_java_line_coverage,39.4 host=webserver 1554146908000000000

```

I used processor converters but could not achieve this. May be I am missing something. Telegraf is a great program, and instead of writing executable having this conversion done using Telegraf will be a great fun.

**Comment by danielnelson** [comment]
Here is what I suggest:

```toml
[[inputs.http]]
  urls = ["http://hostname:9000/api/measures/component?additionalFields=periods&componentKey=ui-ut&metricKeys=line_coverage,lines"]
  method = "GET"
  name_prefix = "coco_java_"
  data_format = "json"
  json_string_fields = ["value"]
  json_query = "component.measures"
  json_name_key = "metric"
  tagexclude = ["url"]
  fielddrop = ["periods*"]

[[processors.converter]]
  namepass = ["coco_java_*"]
  [processors.converter.fields]
    float = ["value"]
```

The output will look like:
```
coco_java_lines,host=foobar value=39984 1554144360000000000
coco_java_line_coverage,host=foobar value=39.4 1554144360000000000
```

If you are using the `--test` flag to test, keep in mind that the processors do not run as part of this command, so they type of the `value` field will be appear as a string.

**Comment by akagalkararkin** [comment]
Thanks a lot for help!!! Let me try this and share a good news.

**Comment by akagalkararkin** [comment]
Great!!! This worked!!!
