### ISSUE TITLE
Timeout option for inputs.smart plugin

### ISSUE THREAD

**Issue by rumato163** [influxdata/telegraf#5659]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
SMART metrics are really static ones. And there is no need to get them as offten as general interval for all linputs.
### Current behavior:
There is no "timeout" option for inputs.smart plugin
### Desired behavior:
Get configurable option
timeout="XXXs"
for inputs.smart plugin to be able not to execute smartctl command too often

### Use case: [Why is this important (helps with prioritizing requests)]
Because of nature of data from smartctl these ones is not so dramatically dinamic.

Almost all parameters of smart devices are slowly changing dimensions. And it is really unnecessary to get them very offten like a CPU Load or RAM state for example.
And it will be very usefull if it becomes possible to execute it once an hour (for example)
 but keep current metric's value output till next retry

**Comment by danielnelson** [comment]
If I'm understanding correctly, I believe you are looking for the `interval` option. This can be set on any input plugin:
```toml
[[inputs.smart]]
  interval = "60m"
```

https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins
