### ISSUE TITLE
inputs.exec fails silently if json values have wrong types

### ISSUE THREAD

**Issue by anlutro** [influxdata/telegraf#566]
I had a script that was basically returning `{"something": true}`. This didn't write anything to InfluxDB, but didn't generate any errors in the InfluxDB or Telegraf logs.

Changing it to an integer instead of a boolean made it work.

**Comment by sparrc** [comment]
closing as dupe of https://github.com/influxdata/telegraf/issues/521

This really is by design, the plugin is meant to be able to deal with a wide range of different JSON blobs and extract the numeric data out.

I suppose it could support booleans by converting to 0/1 though

**Comment by anlutro** [comment]
Gotcha! I'll comment on the other issue.
