### ISSUE TITLE
Logfmt throws error when using default configuration

### ISSUE THREAD

**Issue by sawo1337** [influxdata/telegraf#5668]
### Relevant telegraf.conf:
```toml
[[inputs.file]]
  files = ["/var/log/test.log"]
  data_format = "logfmt"
  metric_name = "logfmt"
```
### System info:

Ubuntu 18.04, Telegraf 1.10.0 and Telegraf 1.10.1 (Windows 10)

### Steps to reproduce:

1. include the default config as described in https://docs.influxdata.com/telegraf/v1.10/data_formats/input/logfmt/
2. Run Telegraph

### Expected behavior:
Data collection without errors

### Actual behavior:
An error is thrown:
```
E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 1915: field corresponding to `metric_name' is not defined in `*file.File'
```

### Additional info:
When metric_name is skipped, it is supposed to create a default one, but nothing happens, no logs are parsed.
Sample test.log file including the following is not being logged:
```
method=GET host=example.org ts=2018-07-24T19:43:40.275Z connect=4ms service=8ms status=200 bytes=1653
```
No error is returned even in debug mode, but the file is not actually parsed

**Comment by glinton** [comment]
Use `name_override` in place of `metric_name`. `metric_name` looks for the defined key to rename the metric, since you have no keys in your input named `logfmt`, it will fail.

Read more about `name_override` [here](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins).

**Comment by danielnelson** [comment]
It sounds like we need to update the README?

**Comment by sawo1337** [comment]
Agree. My config was as per the readme, couldn't find other example.

**Comment by glinton** [comment]
Oh whoops, looking at the code, it does duplicate the name_override behavior. My bad, I just assumed it acted like `json_name_key`. It appears that `metric_name` hasn't fully been wired in.
