### ISSUE TITLE
[[inputs.http_response]] not able to monitor https url

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5673]
HI,  I want to monitor https URL from different server (IP: 10.5.yy.yy).
below is the configuraion file of the server, from where I want to monitor:

[[inputs.http_response]]
address = "https://10.5.xx.xx:8443/login.action"
method = "GET"
response_timeout = "300s"
**Note**
I able to telnet from 10.5.yy.yy to 10.5.xx.xx on 8443 port.
 
I am always getting connection failed even after increasing the value of response_timeout
can you help me solve this problem?

**Comment by danielnelson** [comment]
Does it work with curl? `curl https://10.5.xx.xx:8443/login.action`

Try this out and if its still not working, ask for help over at the [InfluxData Community](https://community.influxdata.com) site.
