### ISSUE TITLE
kubernetes and kube_inventory use the same metric names

### ISSUE THREAD

**Issue by ceastman-ibm** [influxdata/telegraf#5678]
### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
Can one of these two inputs use a different metric naming convention?

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by glinton** [comment]
Which metrics are the same? It may be possible to add a prefix or similar to one.

**Comment by danielnelson** [comment]
This was actually done on purpose, the idea is that the plugins enabling one or both of the plugins would work and add additional information to the metric.

It is kind of new idea, so maybe it wasn't a good one.  Can you explain what problem it is causing?

**Comment by ceastman-ibm** [comment]
i was thinking there was a conflict with the metric: kubernetes_pod_container
im not seeing the fields from kube_inventory showing up
but i see some other metrics from kube_inventory.

<img width="481" alt="Screen Shot 2019-04-04 at 4 32 07 PM" src="https://user-images.githubusercontent.com/25593207/55589939-3a81b280-56f7-11e9-82fc-bf6c796ec296.png">

<img width="269" alt="Screen Shot 2019-04-04 at 4 32 51 PM" src="https://user-images.githubusercontent.com/25593207/55589976-508f7300-56f7-11e9-8161-de6361b9acd8.png">

**Comment by danielnelson** [comment]
If the expected fields aren't showing I would start by checking the log file for anything relevant.

**Comment by danielnelson** [comment]
@ceastman-ibm Where you able to get this working as expected?

**Comment by ceastman-ibm** [comment]
@danielnelson i got side tracked by another project but im back to working on telegraf and the kube inputs. i can let you know in a couple of days.

**Comment by ceastman-ibm** [comment]
I think i was running into this bug: https://github.com/influxdata/telegraf/issues/6033 i added namespace = "" and now i am seeing restarts as i was expecting.

[[inputs.kube_inventory]]
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  insecure_skip_verify = true
  namespace = ""
  url = "https://kube master:28942"
