### ISSUE TITLE
Keep older versions of Telegraf available in the apt repository

### ISSUE THREAD

**Issue by dj-wasabi** [influxdata/telegraf#5685]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Keep older versions of Telegraf available in the apt repository.

### Current behavior:
Every time a new Telegraf release is available, this new release is available in the apt repository, but the previous version(s) are not available anymore. People have to update the configuration of the Ansible role to update property to later version.

### Desired behavior:
Keep older versions available in the apt repository.

### Use case: [Why is this important (helps with prioritizing requests)]
People using my Ansible role (https://github.com/dj-wasabi/ansible-telegraf) for installing and configuring Telegraf on Debian/Ubuntu hosts have issues when a new version of Telegraf is released by InfluxDB.

Within the Ansible role, we have a property `telegraf_agent_version: 1.10.0`. This would mean that people have to update this property every time and always needs to use the latest available version. There can be reasons to not install/upgrade Telegraf with the latest version on a host, like that all hosts in their environment should have the same version.

**Comment by danielnelson** [comment]
This is a limitation of `reprepro`, when we last looked it was only possible to have one version per distribution.  I think the next step is for someone to look into alternative ways we could layout the repos, or alternative tooling we could use.

Perhaps we could have one dist per minor version:
```
deb https://repos.influxdata.com/debian wheezy telegraf-1.9
deb https://repos.influxdata.com/debian wheezy telegraf-1.10
```

The above this plan wouldn't allow for multiple patch versions: 1.10.0, 1.10.1 1.10.2.

Old issue on this problem #1776

**Comment by powersj** [comment]
As mentioned above this is a limitation of the reprepro tool that is in use as well as a general setup of debian repos generally don't keep every single version every published either. We are looking at other tooling to host the repos, but so far they would fall under this same limitation. Suggestions are welcome. 

That said I am going to go ahead and close this issue as folks can use the downloads on [influxdata](https://dl.influxdata.com/) or the releases page to get older versions as a workaround.
