### ISSUE TITLE
GPFS Statistics Input

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5687]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a new input for gathering GPFS Statistics (available with GPFS’s mmpmon) including read/write throughput, read/write operations (IOps), read/write latency, and GPFS Waiters.

https://www.ibm.com/support/knowledgecenter/en/STXKQY_5.0.2/com.ibm.spectrum.scale.v5r02.doc/bl1adv_mmpmonch.htm

### Current behavior:
No plugin exists

### Desired behavior:
Plugin exists to pull the metrics mentioned above

### Use case: [Why is this important (helps with prioritizing requests)]
user would like to gather GPFS Statistics for the purpose of monitoring and alerting

**Comment by powersj** [comment]
Hi,

Have not seen any recent requests for this going to close for now and can revisit if a strong desire to shown.

Thanks
