### ISSUE TITLE
WekaIO Statistics

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5688]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
A new plugin for gathering WekaIO Statistics (available with WekaIO/s weka cmd) including read/write throughput, read/write Operations (IOps), and read/write latency.
https://docs.weka.io/usage/statistics

### Current behavior:
No plugin exists.

### Desired behavior:
A plugin exists to gather the metrics mentioned above

### Use case: [Why is this important (helps with prioritizing requests)]
user would like to monitor machines and alert on issues

**Comment by powersj** [comment]
Hi,

Have not seen any recent requests for this going to close for now and can revisit if a strong desire to shown.

Thanks
