### ISSUE TITLE
Prometheus Input plugin - field name = 'gauge' 

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5689]
I have been playing with prometheus input plug-in and i see the conversion is weird.
Gauge metrics have fieldName = 'gauge' and summary has filedName as number !
Why can't we just keep the timeseries as is and have prometheus tags/buckets as tags?

\# TYPE cpu_usage_user gauge
cpu_usage_user{cpu="cpu0"} 1.4112903225816156

### Expected behavior:
prometheus,cpu=cpu0,url=blah cpu_usage_user=1.4112903225816156 1505776751000000000
### Actual behavior:
cpu_usage_user,cpu=cpu0,url=blah gauge=1.4112903225816156 1505776751000000000

**Comment by danielnelson** [comment]
I agree, I had a slightly different layout that I wrote down in #4415, but after more thought I want to go with this method.  Let's continue discussion on #4415.

**Comment by vishiy** [comment]
@danielnelson thank you. I see the other item (#4415) active for quite some time 10 months or so. Any thing on the works for this issue ?

**Comment by danielnelson** [comment]
No, I have no code yet.
