### ISSUE TITLE
Add goweight to the CI

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#5690]
## Feature Request

Could be nice to add [gowieght](https://github.com/jondot/goweight) to the build pipeline in the CI to be able to track the size of the telegraf binary over versions and know where is going the space.

**Comment by danielnelson** [comment]
Seems like this will be a helpful tool, though I feel that adding it to CI alone won't do too much for us unless we have a way to be notified when it changes.  Any ideas on how we could do this?

I'll definitely use it interactively though, here is the current output:
```
$ goweight ./cmd/telegraf/telegraf.go  | head
   28 MB github.com/influxdata/telegraf/vendor/github.com/vmware/govmomi/vim25/types
  9.4 MB github.com/influxdata/telegraf/vendor/gopkg.in/olivere/elastic.v5
  6.5 MB github.com/influxdata/telegraf/vendor/github.com/ericchiang/k8s/apis/core/v1
  5.3 MB github.com/influxdata/telegraf/vendor/github.com/aerospike/aerospike-client-go
  4.5 MB github.com/influxdata/telegraf/vendor/github.com/google/go-github/github
  4.3 MB github.com/influxdata/telegraf/vendor/github.com/vmware/govmomi/vim25/methods
  3.8 MB github.com/influxdata/telegraf/vendor/github.com/vmware/govmomi/object
  3.5 MB github.com/influxdata/telegraf/vendor/github.com/go-redis/redis
  3.4 MB net/http
  3.0 MB runtime
```

**Comment by adrianlzt** [comment]
The output could be in JSON.
Maybe another test to be run by the CI that compares latest data with new executions and complain if the difference is too big.
The problem is where to store that previous info. The git repo don't seem a good option.

**Comment by danielnelson** [comment]
I wonder if we could store it in one of CircleCI's caches.  I also wouldn't just want the test to fail, rather some sort of warning, like a comment added to the PR.  I suppose a failure could be okay so long as it is in a separate step of the build so we can see it failed the size check.

**Comment by sspaink** [comment]
Closing because we have added a feature to tiger bot to report the size difference each pull request introduces, goweight is a cool tool but I'm not convinced the detailed breakdown is useful for each CI.
