### ISSUE TITLE
Error in inputs.syslog after upgrade to 1.10.2

### ISSUE THREAD

**Issue by bporima** [influxdata/telegraf#5696]
### Relevant telegraf.conf:

[[inputs.syslog]]
  server = "udp://0.0.0.0:6514"

### System info:

Ubuntu 18.04.2 LTS
Telegraf 1.10.2 (git: HEAD 3303f5c3)

### Steps to reproduce:

1. Have a working inputs.syslog configuration with version 1.10.1
2. Upgrade to 1.10.2

(Actually, inputs.syslog stopped working after upgrade to 1.10.2)

### Expected behavior:

To work as in 1.10.1

### Actual behavior:

Error message as recorded in /var/log/telegraf/telegraf.log:

2019-04-08T18:28:17Z E! [inputs.syslog]: Error in plugin: expecting a version value in the range 1-999 [col 4]

### Additional info:

Syslog-messages are received by rsyslog.d (see below) and transformed to RFC5424. They are piped simultaneously to telegraf (listening on udp port 6514) and to /var/log/syslog on the same host. These are two sample lines from /var/log/syslog:

<30>1 2019-04-08T20:45:30+02:00 <host> chronograf 758 - -  time="2019-04-08T20:45:30+02:00" level=info msg="Response: OK" component=server method=GET remote_addr="192.168.23.5:49570" response_time="73.683µs" status=200

<86>1 2019-04-08T20:45:01+02:00 <host> CRON 33721 - -  pam_unix(cron:session): session closed for user root

(as mentioned, telegraf could handle these messages while on version 1.10.1)

Here are some more infos on rsyslog:

rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

Happy to provide more info!

**Comment by danielnelson** [comment]
This looks like Telegraf is receiving untransformed messages in RFC3164 format.  Additionally we haven't made any changes in this area of the code so it is surprising that it would be broken.

Does reverting back to 1.10.1 fix the issue?

**Comment by bporima** [comment]
Hi Daniel,

thanks for the swift reply!

- reverting versions
I'll test that, is there a .deb file available anywhere for 1.10.1? The repository seems to not have it.

- additional testing
i have another site where i did not yet upgrade to 1.10.2. I'll pipe all my syslog files over to that location and see what happens. If that works, it will come back via output.influxdb to the telegraf on the system where i have the problems and go from there into the influxdb. However that would mean that there is a problem with 1.10.2 (at least with my installation). But lets see what happens, i'll report back.

Many thanks for the support!

**Comment by bporima** [comment]
OK, same error message on the other system as well, something is definitely fishy with my own installation/configuration.

So i can confirm that the observed problem does *not* result from telegraf 1.10.2, but something else broke on my system.

Sorry for taking your time! I'll close this issue

**Comment by danielnelson** [comment]
No problem, if you need them in the future the best place to grab older releases is probably here: https://github.com/influxdata/telegraf/releases

**Comment by mapl** [comment]
> This looks like Telegraf is receiving untransformed messages in RFC3164 format. Additionally we haven't made any changes in this area of the code so it is surprising that it would be broken.
> 
> Does reverting back to 1.10.1 fix the issue?

Are RFC3164 Syslog messages support planned in the near future?

**Comment by danielnelson** [comment]
I am hoping, but no promises, that we will be able to work on in the 1.12 release cycle.  Keep an eye on #4593 for updates.  Perhaps you can use the rsyslog workaround described on that issue.
