### ISSUE TITLE
Telegraf debian package fails to install in chroot

### ISSUE THREAD

**Issue by vmwalex** [influxdata/telegraf#5698]
Telegraf postinstall script incorrectly detects chroot environment as systemd-based system. Please consider adding check for systemctl being present when deciding to install systemd init scripts

System info: Ubuntu 14.04 chroot (debootstrap) on Ubuntu 16.04 host

```
--- telegraf/scripts/post-install.sh.orig       2019-04-08 14:42:15.953420800 -0700
+++ telegraf/scripts/post-install.sh    2019-04-08 15:13:45.612287700 -0700
@@ -58,7 +58,7 @@
 # Distribution-specific logic
 if [[ -f /etc/redhat-release ]] || [[ -f /etc/SuSE-release ]]; then
     # RHEL-variant logic
-    if [[ "$(readlink /proc/1/exe)" == */systemd ]]; then
+    if [[ "$(readlink /proc/1/exe)" == */systemd ]] && type -P systemctl &>/dev/null; then
         install_systemd /usr/lib/systemd/system/telegraf.service
     else
         # Assuming SysVinit
@@ -72,7 +72,7 @@
     fi
 elif [[ -f /etc/debian_version ]]; then
     # Debian/Ubuntu logic
-    if [[ "$(readlink /proc/1/exe)" == */systemd ]]; then
+    if [[ "$(readlink /proc/1/exe)" == */systemd ]] && type -P systemctl &>/dev/null; then
         install_systemd /lib/systemd/system/telegraf.service
         deb-systemd-invoke restart telegraf.service || echo "WARNING: systemd not running."
     else
```

**Comment by danielnelson** [comment]
I'm assuming this causes the script to fail because the directory doesn't exist?  Can you paste in any error shown.

**Comment by vmwalex** [comment]
deboostrap is a common way to build Debian system images: https://wiki.debian.org/Debootstrap 
As part of the process, it is usually required to install packages inside chroot

Let's say Ubuntu 14.04 system is being bootstrapped on Ubuntu 16.04 host. chroot and host share /proc filesystem. /proc/1/exe is actually from chroot host system (16.04) instead of chroot itself which is 14.04. Telegraf installer runs in the context of 14.04 (in chroot) but detects systemd and installs incorrect scripts.  

It should be fairly safe to check for presence of systemctl because postinstall script calls it anyway inside install_systemd function.

**Comment by danielnelson** [comment]
I think that installing the systemd service files is not a problem in and of itself, in fact I believe this is what official debian packages do.  But I can imagine other issues stemming from the attempt at auto detection.

Is the problem then that you want the sysv init script in the chroot and its not installing it because of this, or is it purely that you don't want the systemd service file?  What init system, if any, do you want to run Telegraf?

**Comment by vmwalex** [comment]
There is no foolproof method to detect systemd unfortunately. /proc/1/exe method does not work in all scenarios. Since Telegraf project is using fpm for packaging, perhaps using FPM method will make sense?

https://github.com/jordansissel/fpm/blob/master/docs/source/pleaserun.rst

or you can borrow detection scripts from it: https://github.com/jordansissel/fpm/blob/master/templates/pleaserun/install.sh
