### ISSUE TITLE
Telegraf jolokia not reading data

### ISSUE THREAD

**Issue by cuthbe** [influxdata/telegraf#5700]
Centos 7

telegraf-1.10.2-1.x86_64

Config file:
[[inputs.jolokia2_agent]]
  urls = ["http://localhost:7777/jolokia"]

 [[inputs.jolokia2_agent.metric]]
     name  = "CelerBaseServerApiSessions"
     mbean = "com.tech:from=*,to=Api,type=ApiSessions"
     paths = ["Status","FromDisplayName","ToDisplayName","Username"]

[[inputs.jolokia2_agent.metric]]
    name  = "MarketDataDestinations"
    mbean = "com.tech:name=Sessions,session=*,type=MarketDataModule"
    paths = ["Status","TotalError","TotalSent","TotalReceived"]
    tag_keys = ["session"]

The first metic will not read but the second will. If I read them from the jolokia frontend using

http://localhost:7777/jolokia/read/com.tech:from=*,to=BaseServerApi,type=ApiSessions

That will show data. How do we debug telegraf to see what the issue is?

**Comment by cuthbe** [comment]
I think the issue might be that the metric has not metric as I am trying to read a status. Where the bottom one has a value i.e 0 1 2 3 4 but the top only has String values

**Comment by cuthbe** [comment]
How can I change a boolean value to an integer to solve this?

**Comment by danielnelson** [comment]
Can you run this command and paste the response from the jolokia server:
```
curl http://localhost:7777/jolokia/read -H Content-Type:application/json --data-binary '[{"type":"read","mbean":"com.tech:name=Sessions,session=*,type=MarketDataModule","attribute":["Status","TotalError","TotalReceived","TotalSent"]}]'
```

**Comment by cuthbe** [comment]
So when running this

curl http://localhost:7777/jolokia/read -H Content-Type:application/json --data-binary '[{"type":"read","mbean":"com.tech:from=*,type=ApiSessions,*","attribute":["Status","Username""]}]'

I see this

{"stacktrace":"java.lang.IllegalArgumentException: Invalid JSON request java.io.InputStreamReader@229c8691\n\tat org.jolokia.http.HttpRequestHandler.extractJsonRequest(HttpRequestHandler.java:181)\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:121)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:290)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:236)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)\n\tat sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: Unexpected token END OF FILE at position 102.\n\tat org.json.simple.parser.JSONParser.parse(JSONParser.java:257)\n\tat org.json.simple.parser.JSONParser.parse(JSONParser.java:92)\n\tat org.jolokia.http.HttpRequestHandler.extractJsonRequest(HttpRequestHandler.java:179)\n\t... 13 more\n","error_type":"java.lang.IllegalArgumentException","error":"java.lang.IllegalArgumentException : Invalid JSON r

but using the web fontend

http://localhost:7777/jolokia/read/com.tech:from=*,type=ApiSessions,*

it prints perfectly.

**Comment by danielnelson** [comment]
Sorry about showing the POST data for the wrong item before, try this command instead:
```
curl http://localhost:7777/jolokia/read -H Content-Type:application/json --data-binary '[{"type":"read","mbean":"com.tech:from=*,to=Api,type=ApiSessions","attribute":["FromDisplayName","Status","ToDisplayName","Username"]}]'

**Comment by cuthbe** [comment]
so the stack trace is

"stacktrace":"javax.management.InstanceNotFoundException: No MBean with pattern com.celertech:from=*,to=Api,type=ApiSessions found for reading attributes\n\tat org.jolokia.handler.ReadHandler.searchMBeans(ReadHandler.java:160)\n\tat org.jolokia.handler.ReadHandler.fetchAttributesForMBeanPattern(ReadHandler.java:126)\n\tat org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:116)\n\tat org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:37)\n\tat org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:161)\n\tat org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:156)\n\tat org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)\n\tat org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:428)\n\tat org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)\n\tat org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:131)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:290)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:236)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)\n\tat sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n","error_type":"javax.management.InstanceNotFoundException","error":"javax.management.InstanceNotFoundException : No MBean with pattern com.celertech:from=*,to=Api,type=ApiSessions found for reading attributes","status":404}]

**Comment by cuthbe** [comment]
When looking at the data on the jolokia web frontend it looks like

"request": {
"mbean": "com.tech:from=*,type=ApiSessions,*",
"type": "read"
},
"value": {
"com.tech:from=OrderRoutingModule,to=StaticDataApi,type=ApiSessions": {
"Status": "LOGGED_IN",
"ObjectNameDefinition": {
"objectName": "com.tech:from=OrderRoutingModule,to=StaticDataApi,type=ApiSessions"
},
"ConnectionConfiguredAsEnabled": true,
"Username": "orderrouting_staticdata",
"ConnectionUri": "bin://localhost:15000",
"FromDisplayName": "OrderRoutingModule",
"ToDisplayName": "StaticDataApi"
},

**Comment by cuthbe** [comment]
if I change the mbean

"request": {
"mbean": "com.celertech:from=*,to=MarketMerchantModule,type=ApiSessions",
"type": "read"
},
"value": {
"com.celertech:from=MarketMerchantMarketDataDestination(PRICE_ENGINE),to=MarketMerchantModule,type=ApiSessions": {
"Status": "LOGGED_IN",
"ObjectNameDefinition": {
"objectName": "com.celertech:from=MarketMerchantMarketDataDestination(PRICE_ENGINE),to=MarketMerchantModule,type=ApiSessions"
},
"ConnectionConfiguredAsEnabled": true,
"Username": "marketdata_marketmerchant",
"ConnectionUri": "bin://localhost:16001",
"FromDisplayName": "MarketMerchantMarketDataDestination(PRICE_ENGINE)",
"ToDisplayName": "MarketMerchantModule"
}


I get

{"stacktrace":"java.lang.IllegalArgumentException: Invalid object name. Invalid character ':' in key part of property\n\tat org.jolokia.request.JmxRequestFactory.createPostRequest(JmxRequestFactory.java:119)\n\tat org.jolokia.request.JmxRequestFactory.createPostRequests(JmxRequestFactory.java:137)\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:123)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:290)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:236)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)\n\tat sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)\n\tat sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: javax.management.MalformedObjectNameException: Invalid character ':' in key part of property\n\tat javax.management.ObjectName.construct(ObjectName.java:551)\n\tat javax.management.ObjectName.<init>(ObjectName.java:1382)\n\tat org.jolokia.request.JmxObjectNameRequest.initObjectName(JmxObjectNameRequest.java:130)\n\tat org.jolokia.request.JmxObjectNameRequest.<init>(JmxObjectNameRequest.java:65)\n\tat org.jolokia.request.JmxReadRequest.<init>(JmxReadRequest.java:68)\n\tat org.jolokia.request.JmxReadRequest$1.create(JmxReadRequest.java:164)\n\tat org.jolokia.request.JmxReadRequest$1.create(JmxReadRequest.java:151)\n\tat org.jolokia.request.JmxRequestFactory.createPostRequest(JmxRequestFactory.java:117)\n\t... 14 more\n","error_type":"java.lang.IllegalArgumentException","error":"java.lang.IllegalArgumentException : Invalid object name. Invalid character ':' in key part of property","status":400}

**Comment by cuthbe** [comment]
So this

curl http://localhost:7777/jolokia/read -H Content-Type:application/json --data-binary '[{"type":"read","mbean":"com.tech:from=*,to=*,type=ApiSessions","attribute":["Status","Port"]}]'

Returns valid data in an array. 

[{"request":{"mbean":"com.tech:from=*,to=*,type=ApiSessions","attribute":["Status","Username"],"type":"read"},"value":{"com.celertech:from=OrderRoutingModule,to=StaticDataApi,type=ApiSessions":{"Status":"LOGGED_IN","Username":"orderrouting_staticdata"}]

But then you go to the metrics frontend for telegraf

http://localhost:9273/metrics

You don't see the data showing up.

**Comment by cuthbe** [comment]
My thought is, does that metric frontend require some sort of integer value on one of the metics.

**Comment by danielnelson** [comment]
Prometheus, and the `prometheus_client` output by extension, only supports numerical values.  Maybe we can push it into a tag, how does the output look when you run `telegraf --input-filter=jolokia2_agent --test`
