### ISSUE TITLE
influxdb v2 plugin organization rename to org

### ISSUE THREAD

**Issue by kelwang** [influxdata/telegraf#5702]
part of https://github.com/influxdata/influxdb/issues/13148

## Feature Request

To make influxdbv2 api consistent, we would like to rename organization to org. 

### Proposal:
Maybe have to backward compatible mode to accept both organization or org

**Comment by danielnelson** [comment]
Just to clarify, are you talking about renaming this option in the configuration for the output plugin?
```
  ## Organization is the name of the organization you wish to write to; must exist.
  organization = ""
```

@stevebang Are we going to refer to this as `org` or `organization` from within the InfluxDB documentation?

**Comment by stevebang** [comment]
In the docs, we refer to "organization" or "organizations" unless it is code. If its the organization property, I might say "...the organization (`org`) property, which is ...".

**Comment by kelwang** [comment]
> Just to clarify, are you talking about renaming this option in the configuration for the output plugin?
> 
> ```
>   ## Organization is the name of the organization you wish to write to; must exist.
>   organization = ""
> ```

Correct

**Comment by danielnelson** [comment]
I don't think we should do this.  It is not a goal of Telegraf to sync variable naming style with the InfluxDB api, the current naming isn't going to cause any confusion and this change is disruptive without any payoff.
