### ISSUE TITLE
Can i use Telegraf along with InfluxDB and Grafana on windows OS?

### ISSUE THREAD

**Issue by shoabshah** [influxdata/telegraf#5712]
## Feature Request

Opening a feature request kicks off a discussion.

**Comment by danielnelson** [comment]
You can run Telegraf on Windows, I would say our primary focus is on Linux but many are successfully using Telegraf of Windows.

In the future, the best place to ask general questions is at the [InfluxData Community](https://community.influxdata.com) site.
