### ISSUE TITLE
Add FreeBSD ARM binaries for Telegraf

### ISSUE THREAD

**Issue by victorhooi** [influxdata/telegraf#5714]
This is related to https://github.com/influxdata/telegraf/issues/5665

Currently, FreeBSD binaries are only provided for x64. However, there are no ARM builds.

Is it possible to add ARM builds for FreeBSD please?

Netgate makes several pfSense-based firewalls based on ARM (e.g. SG-1100, SG-3100 etc.), which would benefit from these binaries as well, for testing newer releases.

**Comment by victorhooi** [comment]
Is there any update on this please?

**Comment by danielnelson** [comment]
I highly recommend using @girgen's packages on [freshports](https://www.freshports.org/net-mgmt/telegraf/).  Even after we add an official arm package it will make sense to continue to use that package, though I still want to add one primarily to ensure that we don't break the build.

**Comment by victorhooi** [comment]
Is there any chance there might be ARM binaries for FreeBSD anytime soon? =)

(https://forum.netgate.com/topic/142836/telegraf-for-arm-systems-e-g-netgate-sg-3100/ - The Netgate folks seem to be having a lot of trouble compiling it successfully for the Netgate SG-3100, which is ARMv6).

**Comment by danielnelson** [comment]
Can you verify this is working?
- [telegraf-1.15.0~0827cb57_freebsd_armhf.tar.gz](https://55940-33258973-gh.circle-artifacts.com/0/build/freebsd/armhf/telegraf-1.15.0~0827cb57_freebsd_armhf.tar.gz)

**Comment by victorhooi** [comment]
I just tried uploading that tarball to my SG-3100 device, and running telegraf/usr/bin/telegraf:
```
[2.5.0-DEVELOPMENT][root@grandstandparade.localdomain]/root/telegraf/usr/bin: ./telegraf
runtime: this system has multiple CPUs and must use
atomic synchronization instructions. Recompile using GOARM=7.
```

Does that help?

**Comment by girgen** [comment]
Hi!

As said above, the standard FreeBSD ports/packages have support for arm6 and arm7. Could you please explain if there are any problems using the package?

just run
`pkg add telegraf`

Palle

**Comment by victorhooi** [comment]
This is for deploying on pfSense appliances, like the Netgate SG-3100.

There's a discussions here - https://forum.netgate.com/topic/142836/telegraf-for-arm-systems-e-g-netgate-sg-3100/2 - where the team talks about the issues they've had getting Telegraf to compile.

AFAIK, it's not supported to install FreeBSD packages directly onto pfSense (They pull from Freshports).

However, if there's a place I can get the vanilla FreeBSD telegraf package for arm7, I'd be happy to try it, to at least see if the binary runs.

I'm using pfSense 2.5, which I believe is based on FreeBSD 12.1

I looked in the below directories, and couldn't find a telegraf package:

http://pkg.freebsd.org/FreeBSD:12:armv7/release_1/All/
http://pkg.freebsd.org/FreeBSD:12:armv7/quarterly/All/

@girgen Do you know where I can download the arm7 telegraf binary for FreeBSD 12.1, to try out please?

**Comment by girgen** [comment]
I have no first hand experience with pfSense, I’ll have to check how they handle packages. 

Is this documentation relevant? 

https://docs.netgate.com/pfsense/en/latest/packages/installing-freebsd-packages.html

Palle

**Comment by victorhooi** [comment]
Right, but you need to point it at full URL for a package - and as mentioned, I can't see a telegraf package in:

* http://pkg.freebsd.org/FreeBSD:12:armv7/release_1/All/
* http://pkg.freebsd.org/FreeBSD:12:armv7/quarterly/All/

Is that by intention, or am I looking into the wrong place?

**Comment by victorhooi** [comment]
@girgen Per earlier message - there doesn't actually appear to be armv7 packages for Telegraf?

* http://pkg.freebsd.org/FreeBSD:12:armv7/release_1/All/
* http://pkg.freebsd.org/FreeBSD:12:armv7/quarterly/All/

Is this an error, or is this by design?

**Comment by cslansing** [comment]
Has anyone been able to look into this more?

**Comment by SomKen** [comment]
> 
> I have no first hand experience with pfSense, I’ll have to check how they handle packages. Is this documentation relevant? https://docs.netgate.com/pfsense/en/latest/packages/installing-freebsd-packages.html Palle
> […](#)
> 2 juni 2020 kl. 18:31 skrev Victor Hooi ***@***.***>: ﻿ This is for deploying on pfSense appliances, like the Netgate SG-3100. There's a discussions here - https://forum.netgate.com/topic/142836/telegraf-for-arm-systems-e-g-netgate-sg-3100/2 - where the team talks about the issues they've had getting Telegraf to compile. AFAIK, it's not supported to install FreeBSD packages directly onto pfSense (They pull from Freshports). However, if there's a place I can get the vanilla FreeBSD telegraf package for arm7, I'd be happy to try it, to at least see if the binary runs. I'm using pfSense 2.5, which I believe is based on FreeBSD 12.1 I looked in the below directories, and couldn't find a telegraf package: http://pkg.freebsd.org/FreeBSD:12:armv7/release_1/All/ http://pkg.freebsd.org/FreeBSD:12:armv7/quarterly/All/ @girgen Do you know where I can download the arm7 telegraf binary for FreeBSD 12.1, to try out please? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

PFSense is Freebsd but with magic and a web ui for PF.

**Comment by SomKen** [comment]
https://github.com/W0CHP/FreeBSD-ARM/tree/master/net-mgmt/telegraf

When this was initially asked about on the Freebsd side, someone was able to hack together version 1.9.0 of telegraf to work on pfsense. Since then, I have been using this package on every vertion of pfsense that's come out for my [Netgate SG-3100](https://store.netgate.com/SG-3100.aspx)

If I can offer my router as sacrifice to Influx I'd be more than happy.

**Comment by sjwang90** [comment]
Closed in https://github.com/influxdata/telegraf/pull/9200
