### ISSUE TITLE
input "inputs.mysql" did not complete within its interval

### ISSUE THREAD

**Issue by matthias-mo** [influxdata/telegraf#5715]
### Relevant telegraf.conf:

* tried it with everything commented out (= default settings) except `servers` and `metric_version`
* tried it with everything set to false and `table_schema_databases` set to one
[inputs.mysql.txt](https://github.com/influxdata/telegraf/files/3072663/inputs.mysql.txt)

 low activity/low volumne database

### System info:

[Include Telegraf version, operating system name, and other relevant details]
Debian Gnu Linux, stable (stretch)
telegraf 1.10.0-1
mariadb 10.1.37-0+deb9u1

### Steps to reproduce:

* set `inputs.mysql` to one of the above settings
* get `input "inputs.mysql" did not complete within its interval` immediately after starting telegraf

### Expected behavior:

telegraf producing at least some mysql statistics

### Actual behavior:

telegraf is not reporting any mysql stats

**Comment by matthias-mo** [comment]
inputs config files:

[inputs.mysql.txt](https://github.com/influxdata/telegraf/files/3072667/inputs.mysql.txt)

**Comment by glinton** [comment]
What is your interval configured to, and how long did you wait before determining that stats weren't reported? (Though, to the last question, it's unlikely that it took an extremely long time to collect that data, unless mysql was on an overutilized  server.)
Is there anything noteworthy in the mysql logs when this happens?
Are there any additional telegraf logs when you run it with `--debug`?
Can the machine where telegraf is running communicate to the udp socket where mysql is listening?

**Comment by matthias-mo** [comment]
First, apologies for my late response (was on vacation).
The interval was set to `10s`. I retested with an interval of `60s` and got the same result.

Will now turn on debug logging and report back later.

**Comment by matthias-mo** [comment]
Forgot to mention: telegraf is running on the same machine where the MariaDB is running.

When running telegraf on the console with `--debug --test` flags set all input tests report their results except the mysql input test. The command just hangs and never finishes.

Will now try to figure out whether there is a connection problem with the unix socket.

**Comment by danielnelson** [comment]
Thanks for the update, it should be possible to get this working with unix domain sockets but I haven't tried.  If I recall correctly, by default Debian only listens on a unix socket, so I think it would be very valuable for us to sort this out and add documentation.

> a user 'telegraf'@'127.0.0.1' would not be able to connect

This is strange, what is your setting for `skip-name-resolve       = 1`?  https://stackoverflow.com/questions/47242111/mysql-able-to-connect-to-localhost-but-not-to-127-0-0-1

Agree about documenting the permissions, will take a look into these issues and update the documentation.

**Comment by matthias-mo** [comment]
> This is strange, what is your setting for skip-name-resolve = 1? https://stackoverflow.com/questions/47242111/mysql-able-to-connect-to-localhost-but-not-to-127-0-0-1

I checked it again and I can't reproduce it. `telegraf` now happily connects with a `telegraf@127.0.0.1` user. Don't know what happened.

**Comment by danielnelson** [comment]
Hate it when that happens.  I'm going to keep this issue open and we will figure out the unix domain socket connection and double check the grants on a fresh Debian/Ubuntu/Centos system with mariadb and update the documention.

**Comment by matthias-mo** [comment]
Thanks, appreciated!

**Comment by powersj** [comment]
Closing as it seems the original issue was resolved. As far as using unix domain sockets, if you are still interested in this, please file a new issue.

Thanks!
