### ISSUE TITLE
How to fetch the folder details?

### ISSUE THREAD

**Issue by Siddhu1096** [influxdata/telegraf#5717]
Hi team,

I am using latest version of InfluxDB, Telegraf and Grafana. I am using Grafana as InfluxDB as the data source and I use telegraf to fetch the data. My requirement is to fetch the folder details which resides in a specific location say, /var/lib/details. I need to show the folders inside this location in Grafana. What should I do? Thanks in advance.

Best,
Siddharth

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
