### ISSUE TITLE
Telegraf send multiple Json objects to the InfluxDB

### ISSUE THREAD

**Issue by OlegSavchuk** [influxdata/telegraf#5718]
Hello,

I want to send information about the SSL certificates to the Influx DB from the Windows machine. 

In the telegraf.config I have this configuration:

```
  [[inputs.exec]]
    commands = ["powershell C:/Scripts/ssl.ps1"]
    timeout = "5s"
    data_format = "json"
    json_string_fields= ["DomainName"]
    name_suffix = "_SSL_Cert" 
```

PS script returns data like this: 
**PS C:\Scripts> C:\Scripts\ssl.ps1**
```
[
    {
        "DomainName":  "*.google.net",
        "Expires In (Days)":  308
    },
    {
        "DomainName":  "google12.com",
        "Expires In (Days)":  631
    },
    {
        "DomainName":  "google1.com",
        "Expires In (Days)":  -9
    }
]

```
When I'm testing telegraf, I'm receiving this data in the testing block.
**telegraf --config telegraf.conf --test**

```
> exec_SSL_Cert,dc=B-02,host=B2,user=$USER DomainName="*.google.net",Expires\ In\ (Days)=308 1555085233000000000
> exec_SSL_Cert,dc=B-02,host=B2,user=$USER DomainName="*google12.com",Expires\ In\ (Days)=631 1555085233000000000
> exec_SSL_Cert,dc=B-02,host=B2,user=$USER DomainName="*google1.com",Expires\ In\ (Days)=-9 1555085233000000000
```

But in the Influx DB I have only first record with ### 308 days.

What I'm doing wrong?

**Comment by danielnelson** [comment]
Each point in InfluxDB with the same measurement+tagset:
```
exec_SSL_Cert,dc=B-02,host=B2,user=$USER
```

Can have one value for a field at any give timestamp.  If you write to the measurement+tagset+field+timestamp again it will override the previous value.

Usually the solution is to for the tagset to uniquely identify the item.  I would probably make DomainName a tag by adding it to `tag_keys`, but it depends, this might be bad advice if there will be >1k possible values for the domain.

**Comment by OlegSavchuk** [comment]
> Каждая точка в InfluxDB с одинаковыми измерениями + tagset:
> 
> ```
> exec_SSL_Cert,dc=B-02,host=B2,user=$USER
> ```
> Может иметь одно значение для поля при любой временной отметке. Если вы снова запишете в измерение + tagset + field + timestamp, это заменит предыдущее значение.
> 
> Обычно решение состоит в том, чтобы набор тегов уникально идентифицировал элемент. Я бы, вероятно, сделал бы DomainName тегом, добавив его в `tag_keys`, но это зависит, это может быть плохим советом, если будет> 1k возможных значений для домена.

Thank you! I will think about another solution, because I have +-300 Domain names
