### ISSUE TITLE
How to fetch folder details?

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#5722]
@Siddhu1096 commented on [Fri Apr 12 2019](https://github.com/influxdata/influxdb/issues/13352)

Hi Team,

I am using Grafana as InfluxDB as the data source and I use telegraf to fetch the data. My requirement is to fetch the folder details which resides in a specific location say, /var/lib/details. I need to show the folders inside this location in Grafana. What should I do? Thanks in advance.

Best,
Siddharth

**Comment by danielnelson** [comment]
duplicate #5712

Let's bring this up on the Community site.

**Comment by Siddhu1096** [comment]
Hey, It's very urgent.

**Comment by danielnelson** [comment]
@Siddhu1096 Did you open a thread on the [community site](https://community.influxdata.com) like I asked?  On the Github issue tracker we try to focus on issues with the code and future development and we answer questions about usage on the community site.
