### ISSUE TITLE
List of files in directory 

### ISSUE THREAD

**Issue by Siddhu1096** [influxdata/telegraf#5729]
I want to list the files in the directory.
This is the way I tried.

[[inputs.exec]]
 commands = [ "/etc/telegraf/scripts/du.sh" ]
  timeout = "5s"
  data_format = "influx"

This is my content inside du.sh
#! /bin/bash
ls -lrth /mnt/new/

And then I ran this command
telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter exec --test

And I'm getting this error  Error in plugin: metric parse error: expected field at 1:10: "total 73M"

Please help and mark it as a bug and urgent 
Thanks in advance
Best,
Siddharth

**Comment by danielnelson** [comment]
The script needs to output [InfluxDB Line Protocol][] as determined by the `data_format` option.

You may want to consider using the filestat input plugin instead, as it does something quite similar:
```
[[inputs.filestat]]
  files = ["/mnt/new/*"]
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

[influxdb line protocol]: https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/
