### ISSUE TITLE
Add the ability to specify org id and bucket id in influxdb v2 output

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5732]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
names for orgs and buckets can change in 2.0. I'd like the ability to use the ID in the config instead of name so that if someone changes the name, the telegraf config is not impacted

### Current behavior:
only names are allowed

### Desired behavior:
add an option to specify the id for org and bucket. if both are specified, throw an error.

### Use case: 
 if someone changes the name of an org or bucket, the telegraf config should not need to be updated

**Comment by danielnelson** [comment]
Can't you already just put the bucket id in the bucket option?

**Comment by danielnelson** [comment]
Reopen if this is not the case.
