### ISSUE TITLE
IBM Middleware/websphere monitoring

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5738]
is this possible to monitor IBM Middleware/websphere through telegraf?

**Comment by toni-moreno** [comment]
We use [cellhealth-ng](https://github.com/toni-moreno/cellhealth-ng) to get data from Websphere PMI counters before into Graphite and now also can send data to influxDB

**Comment by danielnelson** [comment]
We don't have anything for Websphere today in Telegraf, but give @toni-moreno's utility a shot and send to InfluxDB or to the `influxdb_listener` input.

@priyankamondalairtel Is the PMI data what you want to collect?  Would you be able to add some links to documentation on how to access this data?
