### ISSUE TITLE
Update Kibana input plugin with support Kibana 6.6.x, 6.7.x and 7.0.x

### ISSUE THREAD

**Issue by yuriy-slobodchikov** [influxdata/telegraf#5744]
## Feature Request
Update Kibana input plugin with support Kibana 6.6.x, 6.7.x and 7.0.x

### Proposal:
Add configuration to point version of kibana to use - like string constants for example
kibana_version = "6.3.x"  "6.6.x" "6.7.x" "7.0.x"
for each version implement its own json mapping and parsing response.

### Current behavior:
Looks like in Kibana 6.6.x version json of /api/status was changed
and now kibana plugin cannot parse response for Kibana 6.6.x, 6.7.x and 7.0.x

### Desired behavior:
In configurstion of plugin there should be some field pointing version.
Kibana plugin should support Kibana 6.6.x, 6.7.x and 7.0.x

### Use case: 
After upgrading from 6.3 to 6.7.1 kibana plugin fail to parse new format of response.

**Comment by yuriy-slobodchikov** [comment]
Hello @lpic10 
Please look into this ticket, may be you have some time to implement it.

**Comment by vikkyomkar** [comment]
@yuriy-slobodchikov / @danielnelson I have raised a PR to address this issue
