### ISSUE TITLE
Embedded/'Include' config sections & dynamic config reload

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5753]
## Feature Request

I was wondering if its possible to have embedded/included config files in telegraf config.
Ex;- telegraf.conf (main config file) , can have as many 'include' sections that can have 'cub' configs in them. Also dynamic config reload is supported today ? I tested and it looks like env vars are evaluated at the start time.

**Comment by danielnelson** [comment]
The only mechanism for splitting configs is using the `--config-directory`, which requires you to define full plugins, not snippets.  I think it probably doesn't make sense to integrate advanced templating into Telegraf itself, but you could use an external template tool to generate the config files before starting Telegraf.  For example, you could use [templates][] in ansible to create the config with the full power of Jinja2 templates

[templates]: https://docs.ansible.com/ansible/latest/modules/template_module.html

On dynamic reload, you can change the plugins and reload, but there are very few differences between this and restarting with the current implementation.  In particular it requires the metric buffer to be flushed before reloading, and all plugins close and reopen files and network connections.

Environment variables can only be changed by the process itself, not by another process, so it wouldn't be helpful to try to reread them.
