### ISSUE TITLE
Ability to use wilcards in win_services plugin

### ISSUE THREAD

**Issue by shawn3231** [influxdata/telegraf#5756]
## Feature Request
I would like to have the ability to use wilcards (*) to find multiple  service names at once instead of needing to define every service name to monitor the status of. This would likely be similar to the way win_perf_counters does its "usewildcardexpansion"

### Proposal:
In our environment we have anywhere from 5-15 services that all start the same and it would make it easier to only need to put "abc-*" in the config instead of abc-123, abc-a23, abc-34d, etc... additionally. We also have system that run multiple instances of SQL server (and some other sql components), so instead of the default MSSQLSERVER service name, it shows up as MSSQL${db-instance-name}.

### Current behavior:
If I put in a star in the service-name (ex. "MSSQL*"), it just errors out with "[inputs.win_services]: Error in plugin: could not open service: 'MSSQL*': The specified service does not exist as an installed service."

### Desired behavior:
I would like it to report back on the status of all service-name occurrences of ex. MSSQLxxx

**Comment by danielnelson** [comment]
related #4522

**Comment by sspaink** [comment]
Resolved in: https://github.com/influxdata/telegraf/pull/8575
