### ISSUE TITLE
disk plugin : FSType ext* with bad values and non coherent data

### ISSUE THREAD

**Issue by osd42** [influxdata/telegraf#5761]
### Relevant telegraf.conf:

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
```

### System info:

CentOS Linux release 7.6.1810 (Core)

### Steps to reproduce:

1. create ext2 or ext4 FS partition
2. check coherence (total = used+free) : 
select fstype,host, path, total - used - free as "zero" from disk WHERE fstype =~ /^ext/ group by host,path ORDER BY time desc LIMIT 1 ;

### Expected behavior:
Column "zero" should be zero everywhere

### Actual behavior:

When FS is ext* it always returns 553648128 or 338898944.
Other issues : when trying to sum disk capacities, erratic results with total and free fields.

Used seems to be good

### Additional info:

I figured it out with grafana : 
select sum(free) as free, sum(used) as used, sum(total) as total, mean(used_percent) as "%" from (select free, used,total,used_percent FROM disk WHERE device !~ /^sd|^rootfs/ GROUP BY host,path,device  LIMIT 1) 

i have something like : 
free       used          total      %
2.68 TB  132.48GB   2.84TB  5.11% 

but in fact 2To is my full proxmox size, each of 9 VMs is between 55g and 95g, the total should be 1.275 TB

**Comment by osd42** [comment]
Better than my poor english : image from grafana with query and different results according to wfs/ext4  : 
![2019-04-24 16_51_00-Grafana - STACK _ disks](https://user-images.githubusercontent.com/49947845/56669343-4981d200-66b1-11e9-9a67-3a5ffaa0a76e.png)

**Comment by danielnelson** [comment]
The `stat -f` command is similar to what the disk plugin uses:
```
$ stat -f /var/lib/mpd/
  File: "/var/lib/mpd/"
    ID: d16e5122649e2a4b Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 15449035   Free: 749954     Available: 6617
Inodes: Total: 3932160    Free: 3923610
```

Reading `man statfs` total, free and available are defined:
```
               fsblkcnt_t f_blocks;  /* Total data blocks in filesystem */
               fsblkcnt_t f_bfree;   /* Free blocks in filesystem */
               fsblkcnt_t f_bavail;  /* Free blocks available to unprivileged user */
```

The plugin reports total, used, and free.  On Linux, these correspond to total, total-free, and available respectively.  When checking the results remember to multiple by the block size:
```
>>> 15449035 * 4096
63279247360
>>> 63279247360 - 3071811584
60207435776
>>> 6617 * 4096
27103232
```

This matches up for me:
```
$ telegraf --test | grep mpd
disk,device=mapper/xyzzy-mpd,fstype=ext4,mode=rw,path=/var/lib/mpd free=27103232i,inodes_free=3923610i,inodes_total=3932160i,inodes_used=8550i,total=63279247360i,used=60207435776i,used_percent=99.9550038359281 1556149480000000000
```

I hope this is helpful to explain the output.

**Comment by osd42** [comment]
Hello @danielnelson and thanks a lot for your answer !

Thanks a lot ! I checked you are right. Telegraf "disk input" manual says that "free, used and total" are in bytes unit and does not mention we have to adjust with the block size only for extX FS.

Is it the expected behaviour or a known bug ? 

Best regards

**Comment by osd42** [comment]
Oh sorry I answered too quickly as you answer is very good...

So metrics really are in bytes and I confirmed grafana does not need block size conversion. So the only thing I don't understand is the difference between collected metrics with my zerocolumn.

used = ( total*4096 - free*4096)
but 
(used + free) is different from total ?

With your example :

total = used + free
63279247360 should be equal to (60 207 435 776 + 27 103 232)
but it results : 60 207 435 776 + 27 103 232 

but there is a 3 044 708 352 difference. I guess this is the 5% reserved for system. This 5% also exist for xfs. How can i get the same type of results no matter the FS ? Or must I consider this is a bug from the disk plugin ?

Best regards

**Comment by danielnelson** [comment]
> In my opinion, we prefer to monitor available/free disk space by ignoring system constraints. These 5% should be counted in "used". What do you think about this idea ?

To get this I believe you can query `total - free`.  In the Linux domain this corresponds to `total - available`, and wow is this confusing due to the naming difference.

> How can i get the same type of results no matter the FS ? Or must I consider this is a bug from the disk plugin ?

I think it's not a bug, just a difference in how filesystems work.  The filesystems where `total-used-free == 0` are the ones with no unavailable system blocks.  This calculation, while it seems very intuitive, just isn't valid on all filesystems.
