### ISSUE TITLE
Support for setting an array in configuration using an environment variable

### ISSUE THREAD

**Issue by chadshowalter** [influxdata/telegraf#5762]
### Proposal:
Support setting array values in configuration using environment variables where the number of elements in the array may vary.

### Current behavior:
I can specify array members in configuration using a separate variable for each array member; I cannot specify all array members as a single environment variable.  In general, I'm not aware of a way to use the same configuration file in multiple environments where the number of elements in an array may vary between environments.

### Desired behavior:
I would like to be able to specify array members in configuration using an environment variable where the number of elements in the array may vary in different deployments using the same configuration file.
### Use case: 
My use case is like this.  Using configuration like I show in the snippet below
```
# Read metrics from one or many MongoDB servers
[[inputs.mongodb]]
  ## An array of URI to gather stats about. Specify an ip or hostname
  ## with optional port add password. ie,
  ##   mongodb://user:auth_key@10.10.3.30:27017,
  ##   mongodb://10.10.3.33:18832,
  ##   10.0.0.1:10000, etc.
  servers = [
    "$MONGO_PRIMARY",
    "$MONGO_SECONDARY"
  ]
```
I could use two environment variables to specify two mongodb servers.  This works just fine, so long as  ``$MONGO_PRIMARY`` and ``$MONGO_SECONDARY`` are both defined.  However, if ``$MONGO_SECONDARY`` is undefined, the mongo plugin throws an exception when attempting to process the empty variable.  It appears that the only supported approach requires that I have a deterministic number of array members, and an environment variable for each.  I cannot, for example, do this:
```
export ARRAY_MEMBERS="host1,host2,host3"
...

servers = [
    "$ARRAY_MEMBERS"
]
```
or this:
```
export ARRAY_MEMBERS="[\"host1\",\"host2\",\"host3\"]"
...
servers = "$ARRAY_MEMBERS"
```
I'm open to different solutions.  Or if there's already a way to accomplish this, I'd be glad to know about it.

**Comment by danielnelson** [comment]
It's not currently possible.  The trick to implementing this is to get escaping correct, we either need to know the type the variable is being expanded into or remove all escaping (which would not be backwards compatible).  Another option I think could be okay is to introduce new bash array inspired syntax.

I'll keep this open, but overall I highly recommend you use a separate template language to generate the telegraf.conf if you require anything remotely advanced.  For example, I use ansible's built in support with Jinja2 templates.

**Comment by chadshowalter** [comment]
Thanks much for the clarification.  In our case, we're deploying telegraf in a docker container, and so far have been using environment variables in our docker-compose.yml file to configure a container built from the same telegraf docker image for different deployments.  We could, of course, use a different docker image (with the appropriate configuration baked in) for each deployment environment.  Or we could mount a volume with a different telegraf config file in each environment.  Neither of these seems as straightforward as the environment variable approach would be, though.

**Comment by codeperfector** [comment]
I am running into this exact problem where I also deploy telegraf in a docker container and use environment variables in a docker-compose.yml file. It would be good have a solution that doesn't rely on ansible or jinja2 templating.

**Comment by srebhan** [comment]
This should work via
```
export ARRAY_MEMBERS='"host1","host2","host3"'
```
and
```toml
servers = [
    $ARRAY_MEMBERS
]
```
