### ISSUE TITLE
gatherCommandstatsLine

### ISSUE THREAD

**Issue by lingfan** [influxdata/telegraf#5774]
## Feature Request

Opening a feature request kicks off a discussion.

### Desired behavior:

```
func gatherCommandstatsLine(
	name string,
	line string,
	acc telegraf.Accumulator,
	global_tags map[string]string,
) {
	if strings.Contains(line, "calls=") {
		fields := make(map[string]interface{})
		tags := make(map[string]string)
		for k, v := range global_tags {
			tags[k] = v
		}
		tags["key_name"] = name
		dbparts := strings.Split(line, ",")
		for _, dbp := range dbparts {
			kv := strings.Split(dbp, "=")
			ival, err := strconv.ParseInt(kv[1], 10, 64)
			if err == nil {
				fields[kv[0]] = ival
			}
		}
		acc.AddFields("commandstats", fields, tags)
	}
}
```

**Comment by danielnelson** [comment]
Link to upstream documentation: https://redis.io/commands/info

> The commandstats section provides statistics based on the command type, including the number of calls, the total CPU time consumed by these commands, and the average CPU consumed per command execution.
> 
> For each command type, the following line is added:
> 
> - cmdstat_XXX: calls=XXX,usec=XXX,usec_per_call=XXX
>
> The cluster section currently only contains a unique field:
> 
> - cluster_enabled: Indicate Redis cluster is enabled
>
> The keyspace section provides statistics on the main dictionary of each database. The statistics are the number of keys, and the number of keys with an expiration.
> 
> For each database, the following line is added:
> 
> - dbXXX: keys=XXX,expires=XXX

**Comment by wingyplus** [comment]
I start prototyping gathering `commandstats` from info [here](https://github.com/influxdata/telegraf/commit/7a63cb37b5c6923eaba8d5f50025f9beb1093a86).

<img width="1680" alt="Screen Shot 2562-05-14 at 21 49 41" src="https://user-images.githubusercontent.com/484530/57712360-a2ce9700-769a-11e9-9bbf-711e452a8bb1.png">

Good to see your feedback. :)

**Comment by glinton** [comment]
Awesome, feel free to [open a pull request from your branch](https://github.com/influxdata/telegraf/compare/master...wingyplus:redis-cmd-stats?expand=1)

**Comment by wingyplus** [comment]
@lingfan @glinton @danielnelson pull request opened. Suggestion are welcome. :)

**Comment by danielnelson** [comment]
Added in #5926
