### ISSUE TITLE
Lustre2 input not working

### ISSUE THREAD

**Issue by santos-lucas** [influxdata/telegraf#5787]
I'm using telegraf with lustre2 input, and it is working in one environment e not in other duplicated environment.. i know that should be some error at my environment, i just want someway to debug de plugin execution, there is somehow?

the plugin is ative on the configuration file, but i get no output, like this:

[root@localhost ~]# telegraf --input-filter lustre2 --test
2019-04-30T18:16:35Z I! Starting Telegraf 1.9.1
2019-04-30T18:16:35Z I! Using config file: /etc/telegraf/telegraf.conf
[root@localhost ~]#

But the plugin is active:

[root@localhost ~]# cat /etc/telegraf/telegraf.conf | grep lustre2 -B1 -A1
\# Read metrics from local Lustre service on OST, MDS
[[inputs.lustre2]]
\#   \## An array of /proc globs to search for Lustre stats

There is some better way to debug what is happening?

Thanks a lot.
Lucas Santos

**Comment by danielnelson** [comment]
What does this command return?
```
ls /proc/fs/lustre/obdfilter/*/stats /proc/fs/lustre/osd-ldiskfs/*/stats /proc/fs/lustre/obdfilter/*/job_stats /proc/fs/lustre/mdt/*/md_stats /proc/fs/lustre/mdt/*/job_stats
```

**Comment by santos-lucas** [comment]
[root@localhost ~]# ls /proc/fs/lustre/obdfilter/*/stats /proc/fs/lustre/osd-ldiskfs/*/stats /proc/fs/lustre/obdfilter/*/job_stats /proc/fs/lustre/mdt/*/md_stats /proc/fs/lustre/mdt/*/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST0008/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST0008/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST0009/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST0009/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000a/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000a/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000b/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000b/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000c/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000c/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000d/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000d/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000e/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000e/stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000f/job_stats
/proc/fs/lustre/obdfilter/fpetrobr-OST000f/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST0008/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST0009/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000a/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000b/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000c/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000d/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000e/stats
/proc/fs/lustre/osd-ldiskfs/fpetrobr-OST000f/stats

**Comment by santos-lucas** [comment]
[root@localhost ~]# ls /proc/fs/lustre/obdfilter/*/stats /proc/fs/lustre/osd-ldiskfs/*/stats /proc/fs/lustre/obdfilter/*/job_stats /proc/fs/lustre/mdt/*/md_stats /proc/fs/lustre/mdt/*/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST0008/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST0008/stats
/proc/fs/lustre/obdfilter/lustrefs-OST0009/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST0009/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000a/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000a/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000b/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000b/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000c/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000c/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000d/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000d/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000e/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000e/stats
/proc/fs/lustre/obdfilter/lustrefs-OST000f/job_stats
/proc/fs/lustre/obdfilter/lustrefs-OST000f/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST0008/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST0009/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000a/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000b/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000c/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000d/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000e/stats
/proc/fs/lustre/osd-ldiskfs/lustrefs-OST000f/stats

**Comment by danielnelson** [comment]
This looks normal, what about the output of
```
cat /proc/fs/lustre/obdfilter/lustrefs-OST0008/stats
```

**Comment by santos-lucas** [comment]
[root@localhost ~]# cat /proc/fs/lustre/obdfilter/lustrefs-OST0008/stats
snapshot_time             1556655370.123137081 secs.nsecs
create                    16 samples [reqs]
statfs                    2488137 samples [reqs]
get_info                  1 samples [reqs]
connect                   27 samples [reqs]
reconnect                 17 samples [reqs]
disconnect                25 samples [reqs]
ping                      323420 samples [reqs]

**Comment by danielnelson** [comment]
The plugin looks for and only processes a few specific metrics in this file, none of which are present:
```
- write_bytes
- write_bytes
- read_bytes
- read_bytes
- cache_hit
- cache_miss
- cache_access
```

It might be that we just don't yet have support for this version of Lustre.  Can check the version of Lustre on the working and the non-working system?

**Comment by santos-lucas** [comment]
It was one of the first things i did.. Both system are with the same Lustre version: lustre 2.10

**Comment by danielnelson** [comment]
I don't have any direct experience with Lustre, but I notice there are no matches for `/proc/fs/lustre/mdt/*/md_stats`, is this something you expect?

**Comment by danielnelson** [comment]
@santos-lucas Any chance you were you able to get the plugin working?
