### ISSUE TITLE
init script not installed on Amazon Linux

### ISSUE THREAD

**Issue by jschnare** [influxdata/telegraf#579]
The logic in `scripts/post-install.sh` checks for either /etc/redhat-release or /etc/debian_version, neither of which exist on Amazon Linux.  There is no fallback, so the init script is not installed.

On AL the script should run `install_init` and `install_chkconfig`, just like RHEL.

I don't know the best way to check for AL, but an else statement which calls `install_init` is probably safe & sufficient.

**Comment by rossmcdonald** [comment]
@jschnare Thanks for letting us know. I'm spinning up an Amazon Linux box to test on now, so I should have a fix for this shortly.
