### ISSUE TITLE
Telegraf agent not running tail command in Exec input

### ISSUE THREAD

**Issue by chetandev** [influxdata/telegraf#5801]
I am trying to record log history of a VM using telegraf [[inputs.exec]]. I have added exec input as follows

```
[[inputs.exec]]
 commands = ["sh /etc/telegraf/commands.sh"]
 data_format = "influx"
 data_type = "string"
```
command.sh file is as follows
```
#!/bin/sh
telgu="$(id -u telegraf )"
log="$(tail -n 10 /var/log/auth.log | grep --line-buffered snoopy | grep -v $telgu)"
base="$(echo  $log |openssl base64)"
echo commands,tag=commands log="\"${base}\""
```
when running script manually it works file , however when executed with telegraf no data is received, i am getting following data

```commands,host=localhost,serverid=08d9ea88-16ba-414f-88d68b6f110035c7,tag=commands log="Cg==" 1556957280000000000 ```

**Comment by danielnelson** [comment]
This is very likely a permissions issue, when ran as a service Telegraf runs as the `telegraf` user on most systems, including with the official rpm and deb packages.
