### ISSUE TITLE
HTTP Output Plugin does not honor custom Host header

### ISSUE THREAD

**Issue by niftyhoot** [influxdata/telegraf#5803]
### Relevant telegraf.conf:

```
[[outputs.http]]
  url = "http://192.168.2.53/collector"
  [outputs.http.headers]
    Host = "ingest.example.com"
    Hostess = "ingest.example.com"
```

### Steps to reproduce:

1. Define custom http headers as shown above
2. Check tcpdump output

### Expected behavior:
The custom string of Host header should have been used while sending the POST requests out.

### Actual behavior:
The "Host" header remains the 192.168.2.53. The other header "Hostess" for example, gets properly updated.

**Comment by glinton** [comment]
Go discussion here - https://github.com/golang/go/issues/7682
