### ISSUE TITLE
CPU Arch Support in Telegraf 

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/telegraf#5805]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 
It would be good to have the architecture of the CPU as part of the tags in CPU plugin. 

### Current behavior:
CPU Arch metric isn't being sent by any of the telegraf plugins
### Desired behavior:
Send CPU Arch value via the CPU plugin
### Use case: 
The CPU architecture will help in various filters and queries to differentiate hosts. Just like how total RAM,total disk,number of cores etc describes the host , the CPU arch value will further help describe the host . Examples of CPU Arch : amd64,arm etc

**Comment by prashanthjbabu** [comment]
https://github.com/influxdata/telegraf/pull/5806 addresses this

**Comment by danielnelson** [comment]
Let's merge discussion with #4256
