### ISSUE TITLE
Diskio plugin: make devices glob also match devlinks

### ISSUE THREAD

**Issue by omgold** [influxdata/telegraf#5815]
### Proposal:

Extend/modify the diskio plugin to to also consider aliases of device names when filtering for a subset of disk devices. I implemented the feature (roughly, without tests and such), as a basis for discussion:

https://github.com/omgold/telegraf/commit/267c1bcc4ac06f851c765600db68ba817cb814ac

### Current behavior:

Filtering using the 'devices' options glob-matches only against actual devnode path (udev attribute DEVNAME)

### Desired behavior:

Matching should also be done against components of DEVLINKS.

### Use case: 

I don't consider matching only the real devnodes (directly in /dev) particularly useful, as these are likely to not be consistent between reboots. Symlinks/aliases on the contrary are mostly persistent (or at least such can be created by custom udev rules).

**Comment by danielnelson** [comment]
I think this would be a nice feature, one thing we will want to make sure of is that we only call `diskInfo` once.  Could you open a PR?

**Comment by omgold** [comment]
PR is #5817. 

Remark: I didn't add any extra calls to diskInfo, as the lookup of the devlinks is added to diskName(). But there are already 2 calls, one in diskName() and one in diskTags()

**Comment by danielnelson** [comment]
Closed in #5817
