### ISSUE TITLE
[Feature Request] Custom application metrics

### ISSUE THREAD

**Issue by AlexKapustin** [influxdata/telegraf#582]
Hello!

Please let us know, are you planning to add possibility to send custom metrics from application to telegraf ?

Ideally it would be:

tcp/udb server socket (depends on config) which accepts metrics in JSON format, gather it, aggregate (?) and flush into db each N seconds (depends on config)

Thanks,
Have a great day! :)

**Comment by sparrc** [comment]
yes, dupe of https://github.com/influxdata/telegraf/issues/481

**Comment by AlexKapustin** [comment]
Thank you for your response!
