### ISSUE TITLE
Add watchdog capability to the telegraf daemon

### ISSUE THREAD

**Issue by soumya92** [influxdata/telegraf#5825]
### Proposal:
Add the ability for telegraf to signal the systemd watchdog

### Current behavior:
Sometimes telegraf deadlocks. Restarting the systemd unit (or sending SIGKILL and letting system restart the process) fixes the issue.

### Desired behavior:
Allow systemd to automatically restart the daemon when this happens by using the systemd watchdog facility.

### Use case: 
Reduce manual intervention on long running servers.

Anecdotally, out of ~10 servers, I usually need to restart telegraf on one every two days.

**Comment by danielnelson** [comment]
Certainly would not be opposed to supporting the systemd watchdog system but it's very possible we won't be able to detect deadlock and would just keep signalling that all is fine.

Let's look into why your Telegraf is locking up, next time it happens can you stop Telegraf by sending SIGQUIT, this will trigger a stack dump to be logged.  Can you grab that and open a separate issue?

**Comment by soumya92** [comment]
Sure, will do.

That's a good point re: detecting the deadlock. I was hopeful that the deadlock would be detectable since telegraf stops responding to sigquit when it happens. So maybe if watchdog was on the same goroutine as the signal handler, but I'm not sure how feasible that is.

**Comment by soumya92** [comment]
Opened #5839 for the unresponsiveness. However, while collecting relevant information for the report, I discovered that the SIGQUIT handling is actually different in the two cases. Given the fact that when telegraf deadlocks, not even SIGQUIT does anything useful, makes me think that watchdog might be more feasible, since it seems that even the core goroutines responsible for stack trace dumps are frozen.

**Comment by danielnelson** [comment]
It seems possible systemd's watchdog feature without modification to Telegraf:

Add an override unit file with the watchdog settings:
```
$ cat /etc/systemd/system/telegraf.service.d/custom.conf
[Service]
NotifyAccess=all
Restart=on-failure
RestartSec=10
WatchdogSec=5
```

Don't forget to reload:
```
$ sudo systemctl daemon-reload
```

In your Telegraf configurations files, enable an exec input, make sure the interval is less than the WatchdogSec:
```
[[inputs.exec]]
  interval = "1s"
  commands = ["/bin/systemd-notify WATCHDOG=1"]
  timeout = "1s"
  data_format = "influx"
```

If the exec plugin does not run for WatchdogSec, systems should restart the service, and while is a bit of a misuse of the exec plugin, since systemd-notify does not produce any output it should be happy to run this every interval.

Give it a shot and let me know how it goes.

**Comment by soumya92** [comment]
Oh that's a very creative solution :laughing: 
I'll give it a shot and see how it works out. Thanks!

**Comment by soumya92** [comment]
It seems work. Telegraf has been automatically restarted thrice so far on the one host where I deployed this, so I will now use this configuration on all others. Leaving it up to you to decide whether (ab)using the exec plugin in this manner is sufficient, or building in systemd watchdog support directly into telegraf is a better long term solution.

**Comment by danielnelson** [comment]
Let's leave this open for now for searchability.  I don't think anyone at Influxdata will have time to work on this, but if someone would like to work on adding first class support for this feature please comment and we can go over design.

**Comment by powersj** [comment]
I'm closing this, as it will still be searchable. Not something we plan to implement or have heard any further requests for. Free to look at pull requests.
