### ISSUE TITLE
Make the http_response plugin support arrays of adresses

### ISSUE THREAD

**Issue by mikkeschiren** [influxdata/telegraf#5828]
## Feature Request

It would be nice if the http_response plugin would have a array of addresses instead of one single. With an array of addresses you could build a simple pingdom like dashboard for a range of sites.

### Proposal:
Make address become an array field instead of string.

### Current behavior:
Addresss field is a string.

### Desired behavior:
Address field shoud be an array - and also support arrays in the code.

### Use case:
Build a pingdom like dashboard for a range of sites. Simpler handling of alerts if sites are down.

**Comment by danielnelson** [comment]
You can, of course, specify the plugin multiple times, but I think this would be worth doing to ease the configuration burden.
