### ISSUE TITLE
Some inputs panic will lead to the telegraf exit

### ISSUE THREAD

**Issue by wutaizeng** [influxdata/telegraf#584]
I expect only those inputs exit, instead of the telegraf exit.

**Comment by zstyblik** [comment]
@wutaizeng dealing with errors is rather difficult eg. closing connections, stopping threads, rollbacks etc. aka cleaning up, so when something goes wrong, crashing loud actually is the best way to go.
Also, it might serve as a motivation to actually fix things.

My $0.02USD.

**Comment by tripledes** [comment]
@zstyblik I agree on the fixing/improving stuff, on the other hand Go offers the `recover()` function which @wutaizeng uses on his #585 which is supposed to be used in such cases, I would rather have telegraf running and logging errors (which might just be temporary issues) than aborting execution.
