### ISSUE TITLE
Precision timestamp for jti_openconfig_telemetry input plugin

### ISSUE THREAD

**Issue by door7302** [influxdata/telegraf#5853]
## Feature Request

Allow to set the precision of timestamp set by the input jti_openconfig_telemetry. 
Currently timestamp precision is in ns. It could be interesting to have precision in second to avoid ms jitter between sensor paths. 

Opening a feature request kicks off a discussion.

### Proposal:

Allow to set :

precision: "s | ms | us | ns" 

### Current behavior:

Send ns timestamp

### Desired behavior:

Still sending ns timestamp (epoch) but with less precision that a ns. Ex. 

Before you have timestamp like that : 

1557755590589715534

With precision="s" you should have something like :

1557755590000000000

### Use case: 

If I request to Junos from telegraf the sensor : /interfaces/interface 

I could receive from the network equipment : 

/interfaces/interface/state/counters/xxxx with timestamp 1557755590589715534
/interfaces/interface/state/cdescription with timestamp 1557755590685780881

To aggregate (merge) those 2 values in a third one on influxdb based on time it's more difficult. 
It could help to have at the output of telegraf : 

/interfaces/interface/state/counters/xxxx with timestamp 1557755590000000000
/interfaces/interface/state/cdescription with timestamp 1557755590000000000

**Comment by danielnelson** [comment]
It may be worth adding a precision option for all input/aggregator plugins that would override the global agent precision.  Unlike the agent precision it would apply to both "service inputs", like jti_openconfig_telemetry, and regular polling inputs.
