### ISSUE TITLE
/etc/default/telegraf script not executed with systemd

### ISSUE THREAD

**Issue by zerog2k** [influxdata/telegraf#5854]
when dynamic scripted actions are specified in `/etc/default/telegraf`, when using systemd, they are parsed statically rather than evaluated dynamically.

it seems there are two possibly competing evaluations of `/etc/default/telegraf`:
1. the telegraf init sources this file (which implies that it's evaluated dynamically):
https://github.com/influxdata/telegraf/blob/master/scripts/init.sh#L34-L40
(is this for non systemd, e.g. sysv initscripts?)

2. systemd service unit file tries to load it as `EnvironmentFile` (which I believe parses it statically/literally?):
https://github.com/influxdata/telegraf/blob/master/scripts/telegraf.service#L7

the result is that when adding dynamic stuff into /etc/default/telegraf, it is not evaluated on systemd (no subshell expansion, etc), but literally captured environment variables

~issue seems like same as #2471 but was not resolved~ (sorry disregard this, not related)

So question is, what is the expected behavior of `/etc/default/telegraf`? 
Is it unintended that in non-systemd systems, that it's being evaluated (`source /etc/default/telegraf`)?

**Comment by danielnelson** [comment]
Your analysis is correct but this is expected behavior for these different init systems.

Someone with more systemd knowledge can correct me if there is a better way, but I think if you want to run code before starting Telegraf in systemd you will need to write a wrapper script.

Does this answer your question?
