### ISSUE TITLE
Don't return error from telegraf/metric.New

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#5859]
### Proposal:
There is no way it can error and currently the only `return` always returns `nil`. Remove the added complexity by not returning the nil error.
[Function is here](https://github.com/influxdata/telegraf/blob/release-1.10/metric/metric.go#L22-L63)

**Comment by danielnelson** [comment]
Go for it

**Comment by powersj** [comment]
Appears to be done :) closing
