### ISSUE TITLE
Inputs.tail Unable to read file information in docker

### ISSUE THREAD

**Issue by chkch** [influxdata/telegraf#5860]
talegraf 1.10.4-1 在centos7的docker镜像中安装，配置如下：

**Comment by danielnelson** [comment]
Maybe you are looking for this info?

https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container

If not, can you ask over on the [InfluxData Community](https://community.influxdata.com) site.
