### ISSUE TITLE
Use timestamp from snmp query for all metrics in the gather

### ISSUE THREAD

**Issue by fwclements** [influxdata/telegraf#5861]
## Feature Request

Pass a timestamp from an input plugin to an output plugin (such as Influx in my case) that will be used as the timestamp for the measurement.

### Proposal:
Some devices collect their own timestamps.  It would be beneficial to be able to take that timestamp, format it into nano timestamp and send that between input and output plugins.  Via a configuration flag on the output plugin, one could specify whether to use the Telegraf timestamp (default) or use the inputted timestamp.

### Current behavior:
Specifically with the influx output plugin, the time that Telegraf wraps up is used as the measurement timestamp.

### Desired behavior:
Allow remote agents to define the measurement timestamp via Telegraf input plugin.

### Use case:
The use case, in my instance, is that I have nearly half a million SNMP devices that are regularly gathering internal metrics which are queried using Telegraf at some interval.  These snmp agents provide the timestamp of the task which is then later used to correlate events to measured results from the agents view point.  

In order for these measurements to be meaningful from the agent perspective, Telegraf should provide a way to communicate a timestamp from an input plugin (snmp) to an output plugin (influx) that leverages this.

**Comment by danielnelson** [comment]
Telegraf currently uses the timestamp set by the input, no matter when the metric is actually sent out on the output side.  Sometimes though inputs have the choice between reporting a time sent by a remote source and the timestamp that the item is collected, but I don't think this is generally the case in the snmp input.

Are you thinking to allow the input to take the timestamp from a specific snmp query and then apply that to all the metrics it creates for that Gather cycle?

**Comment by fwclements** [comment]
> Are you thinking to allow the input to take the timestamp from a specific snmp query and then apply that to all the metrics it creates for that Gather cycle?

That is exactly what I'm thinking.  Here's a copy of the table I'm querying:

```
ACD-TWAMP-GEN-MIB::acdTwampGenResultInstName.1 = STRING: Reflector
ACD-TWAMP-GEN-MIB::acdTwampGenResultPeriodNb.1 = Gauge32: 677
ACD-TWAMP-GEN-MIB::acdTwampGenResultPeriodTime.1 = STRING: 2019-5-15,15:30:0.0,-4:0
ACD-TWAMP-GEN-MIB::acdTwampGenResultCurrTxPacketCount.1 = Counter64: 8
ACD-TWAMP-GEN-MIB::acdTwampGenResultCurrRxPacketCount.1 = Counter64: 8
ACD-TWAMP-GEN-MIB::acdTwampGenResultTwoWayDelayValid.1 = INTEGER: true(1)
ACD-TWAMP-GEN-MIB::acdTwampGenResultTwoWayDelayInstValue.1 = INTEGER: 1182
ACD-TWAMP-GEN-MIB::acdTwampGenResultTwoWayDelayCurrSamples.1 = Gauge32: 7

--- snip ---
```

Notice specifically:
```ACD-TWAMP-GEN-MIB::acdTwampGenResultPeriodTime.1 = STRING: 2019-5-15,15:30:0.0,-4:0```

This is the timestamp when the TWAMP process last ran.  Any of the measured values are at that timeframe.  For SLA reporting, it's important that the measurements line up with actual runtime.

In an ideal situation that field could be flagged somehow in the snmp plugin config to have it used as the overall timestamp for the Gather cycle.

**Comment by Hipska** [comment]
It would be remotely possible to implement if that value would be a `TimeTicks` type, but parsing such a custom timestamp string will not make it.
