### ISSUE TITLE
Add Ethtool Input Plugin

### ISSUE THREAD

**Issue by philippreston** [influxdata/telegraf#5864]
## Feature Request

Feature is to add a new input plugin that will use ethtool to pull statistics from ethernet devices on linux machines.  This is particularly important for monitoring high end NIC cards such as SolarFlare, where key performance metrics are only available through this interface.

### Proposal:

Is to add a new plugin, which will be specifically for linux.  It will allow selection of interfaces to pull metrics from and allow filtering of what fields are written.  This filter feature is important as the metrics can differ across devices / drivers, so having control over what is written is important

### Current behavior:

There is no plugin accessing this interface

### Desired behavior:

Have a new plugin 

### Use case: 

This is important for performance monitoring and trending for low-latency Network Interface Cards such as SolarFlare, which is particularly important in the financial services space for front office trading, but also for packet capture solutions built on these technologies.

We have this coded up and will open a pull request for review

**Comment by philippreston** [comment]
Opened in #5865

**Comment by philippreston** [comment]
Hey 

Just wanted to check if you had any feedback or any view on whether this is likely to be accepted?

Many thanks

**Comment by danielnelson** [comment]
Thanks for the PR, it seems very useful and we'd definitely like to add it, unfortunately we are quite a bit behind on review (to put it nicely) so it might be a while before we can take a proper look.

**Comment by philippreston** [comment]
Thanks for the update.
