### ISSUE TITLE
Influx DB connection not being read in via env variable

### ISSUE THREAD

**Issue by jordanpurinton** [influxdata/telegraf#5866]
### Relevant telegraf.conf:
```
[agent]
  debug = true
  quiet = false

# OUTPUTS
[[outputs.influxdb]]
  url = "${INFLUX_DB_CONNECTION}" 
  database = "redacted"
  tagexclude = ["redacted"]

# INPUTS
# Read metrics from Kafka topic(s)
[[inputs.kafka_consumer]]
  ## topic(s) to consume
  topics = ["redacted"]
  brokers = ["redacted"]
  consumer_group = "redacted"
  offset = "newest"
  max_undelivered_messages = 40000
  data_format = "influx"
```

### System info:
1. Alpine Linux 3.8
2. Telegraf 1.10.4

### Expected behavior:
For the influx db url to be read in via  `url = "${INFLUX_DB_CONNECTION}"`

### Actual behavior:
```
[agent] Attempting connection to output: influxdb
[agent] Failed to connect to output influxdb, retrying in 15s, error was 'unsupported scheme ["${INFLUX_DB_CONNECTION}"]: ""'
[telegraf] Error running agent: unsupported scheme ["${INFLUX_DB_CONNECTION}"]: ""`
```
Process exits after this

**Comment by danielnelson** [comment]
The config looks fine, how are you setting the environment variable and how are you launching Telegraf.  Most likely the variable it is not set properly in the Telegraf environment.

You can check the actual environment with `cat /proc/${telegraf_pid}/environ`

**Comment by vjanssens** [comment]
@danielnelson I'm having the same issue as @jordanpurinton describes.

I'm running Telegraf with InfluxDB inside Docker containers, passing environment variables in through `docker-compose.yml`. 

`docker-compose.yml`
```
telegraf:
    image: telegraf:1.10.4
    env_file:
      - ./.env
```

`telegraf.conf`
```
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] 
  username = "${INFLUXDB_ADMIN_USER}"
  password = "<working_password_redacted>"
```

There are two ways I tested to see if the environment variables are correctly passed to the container:
```
docker exec -it <container_name> bash
echo $INFLUXDB_ADMIN_USER
> outputs correct variable definition
xargs -0 -L1 -a /proc/1/environ
> also outputs the same variable definition
```

> Telegraf runs on pid 1

In the output of telegraf, I observe the following:

> 401 Unauthorized: authorization failed

When replacing `${INFLUXDB_ADMIN_USER}` in `telegraf.conf` with the working password, telegraf works as expected and is able to push data to InfluxDB.
