### ISSUE TITLE
Docker plugin - 'container_id' is coming as field rather than tag

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5867]
`docker_container_cpu,container_image=telegraf,container_name=zen_ritchie,container_status=running,container_version=unknown,cpu=cpu0,engine_host=debian-stretch-docker,server_version=17.09.0-ce container_id="adc4ba9593871bf2ab95f3ffde70d1b638b897bb225d21c2c9c84226a10a8cf4",usage_total=20825265i 1524002042000000000
docker_container_cpu,container_image=telegraf,container_name=zen_ritchie,container_status=running,container_version=unknown,cpu=cpu1,engine_host=debian-stretch-docker,server_version=17.09.0-ce container_id="adc4ba9593871bf2ab95f3ffde70d1b638b897bb225d21c2c9c84226a10a8cf4",usage_total=96493803i 1524002042000000000`

**Comment by danielnelson** [comment]
This was done on purpose some time ago to reduce series cardinality.  You can use the `converter` processor to switch it to a tag if you like, just make sure to have the right retention policy in place.

**Comment by vishiy** [comment]
@danielnelson - thought so for cardinality reasons. thanks.

**Comment by danielnelson** [comment]
I think I will close this issue, in the future I hope to add support for processors being attached directly to inputs, and something like this should help to reduce the configuration complexity without requiring the plugin to manage multiple data models.
