### ISSUE TITLE
Telegraf strings processor trim to length

### ISSUE THREAD

**Issue by raffraffraff** [influxdata/telegraf#5877]
## Feature Request
It should be possible to use the strings processor to trim values based on length. In some cases (eg: docker container IDs) a 12 character value is perfectly acceptable, but there is no way to do this with trim_right, as there isn't a specific delimiter that can be used

### Proposal:
Add an additional optional flag to the configuration that performs simple substring using numerical position (eg: `container_id[:12]`)
### Current behavior:
You can only truncate on spaces or delimiters
### Desired behavior:
You can truncate on position
### Use case: 
With docker in particular, there are image IDs and container IDs which are perfectly acceptable at a 12 character length (the default chosen by the docker cli). Across a large fleet this reduction could have a performance increase.

**Comment by danielnelson** [comment]
Seems useful, maybe we call it left (name inspired by postgres function):
```toml
[[processors.strings]]
  [[processors.strings.left]]
    field = "container_id"
    width = 12
```
