### ISSUE TITLE
Add name to each plugin

### ISSUE THREAD

**Issue by rbkasat** [influxdata/telegraf#5878]
## Feature Request
Opening a feature request kicks off a discussion.

### Proposal: 
Need telegraf internal metrics to contain plugin name in them. Suppose I have a confi file with 3 influxdb output plugins, I should be able to name each plugin and get the internal metrics based on the name. 

### Current behavior:
internal metrics export the generic data with just a plugin type. 

### Use case: 
there is no way to see which ouput plugin is having issue's

**Comment by danielnelson** [comment]
Agreed this needs to be fixed, we have existing issue open for this #1815
