### ISSUE TITLE
Disable [[outputs.influxdb]] in default telegraf.conf

### ISSUE THREAD

**Issue by beiermi** [influxdata/telegraf#5887]
I'd expect telegraf to be completely configurable without modifying /etc/telegraf/telegraf.conf provided by vendor / rpm package and only adding custom configuration files in /etc/telegraf/telegraf.d.
But the /etc/telegraf/telegraf.conf defines an influxdb output without setting any further options. This results in telegraf trying to contact http://localhost:8086/write?db=telegraf every 10s.
Adding a custom configuration file in /etc/telegraf/telegraf.d, which defines an own influxdb output url, does not change this behaviour.
To change this behaviour and prevent telegraf from useless http requests to localhost:8086, I'd propose disabling/commenting the following line in telegraf.conf:
```[[outputs.influxdb]]```

**Comment by danielnelson** [comment]
Thanks for opening the issue.  I don't necessarily agree with your expectation that it should be possible to configure Telegraf without modifying the default configuration file, this is not generally how config file plus directory works.  For example compare with `/etc/apt/sources.list` vs `/etc/apt/sources.list.d` on a Debian system.

That said, I think it would be reasonable to move the default plugin configuration into the telegraf.d directory to ease merging on updates #4966.  This would make it easier to remove the default configuration.  If that seems reasonable to you then I will close this issue and we can follow #4966.

**Comment by beiermi** [comment]
I agree, that your sources.list example is similar - but though there are some differences.
Telegraf tries to contact http://localhost:8086/write?db=telegraf every 10s, what is producing unnecessary errors telegraf.log. Only very few users will run influxdb on localhost, most of them have to change the configuration. Another aspect of this issue is, that the default configuration of telegraf is not working for most users and even produces a huge amount of error logs. Moving the [[outputs.influxdb]] into a separate configuration file in /etc/telegraf/telegraf.d will only move this issue, but not fix it.
A default configuration should make sense and not lead to errors.

**Comment by danielnelson** [comment]
For many users getting started, it is nice to start everything with `apt-get install telegraf influxdb`, this is the main reason behind the current configuration.  In the future this will probably not work with InfluxDB v2, as it requires configuration, so that does open us up to make changes.

I don't think the logs are a big deal, if my math is correct it only comes out to about 2MB a day, and most systems rotate and compress the logs after that.  They also nudge the user in the right direction of what needs done.

It's also not currently possible to start Telegraf without an output defined, something that I think is generally a good thing since running without an output is almost always an error.   I have seen some packages, shorewall comes to mind, that refuse to start until configured.

This isn't something I would consider changing until 2.0, but do you think we should refuse to start until an output is configured?

**Comment by dukz** [comment]
I do agree in removing the default influxdb output configuration.

Every time I upgrade the telegraf package, it ends up having a config overwrite with the package manager, and I have to do it by hand to disable that all over again. 

I've made it a practice to just put everything under the telegraf.d folder, so configs are consistent even after the telegraf package is updated.

**Comment by arvenil** [comment]
I think everyone who want's to follow .d folder pattern will fall into this surprise. This means we can't really use telegraf.d folder as anyway we need to overwrite telegraf.conf. I don't understand why `[[outputs.influxdb]]` is not commented out. Put it into telegraf.d as localhost.conf and comment it out. Point users to the file and ask to uncomment the line if they want localhost.

**Comment by arvenil** [comment]
Everyone who want's to follow `.d` folder pattern will fall into this issue. I can't really use telegraf.d folder as I need to overwrite telegraf.conf anyway. I don't understand why `[[outputs.influxdb]]` is not commented out. Put it into telegraf.d as localhost.conf and comment it out. Point users to the file and ask to uncomment the line if they want localhost.

**Comment by sseypt** [comment]
@beiermi Thanks you for opening this issue 👍

Don't know how long it would have taken me to realize that these authorization errors in the influx log came from a missing `#` 🙈

In my opinion there shouldn't be a default output which can't be disabled throug `/etc/telegraf/telegraf.d/`

Since there is `[[outputs.influxdb_v2]]` already, i'd also like this issue to be fixed.

**Comment by Luis-3M** [comment]
@arvenil 
Thanks 👍 
Your sed command didn't work on my side (Amazon Linux 2) - had to change it slightly:

`sed -i '/^\[\[outputs.influxdb\]\]/ s/./# &/' /etc/telegraf/telegraf.conf`

**Comment by toastbrotch** [comment]
we're suffering from the same problem, as it breaks our automation on packet-upgrades as it often comes with a changed /etc/telegraf/telegraf.conf

we have our custom /etc/telegraf/telegraf.d/foo.conf with everything we need, and it seems our config and the default create 2 different agents or at least targets to send logs to, as our target gets the metrics. so what i don't understand is why our config does simply not overwrite that default. so we need to comment out that line in the /etc/telegraf/telegraf.conf to get rid of this second agent/target. .... i don't understand why we have that /etc/telegraf/telegraf.d when overwriting the default does not work. so something is rather broken here... 

regards,ivo

**Comment by toastbrotch** [comment]
@danielnelson this is not a feature request, this is a rather annoying bug! thanx for changing tags and correctly priorizing

**Comment by aewtemp** [comment]
Hello guys.

I do have the same Problem as described here.
I am running Telegraf in Version 1.34.0.
There is no reference to the old outputs plugin of influxdb. All I have is an outputs plugin for influxdb_v2.
Yet still the journalctl shows the following:
`Mar 19 16:18:46 lef401 telegraf[83590]: 2025-03-19T15:18:46Z W! [outputs.influxdb] When writing to [http://localhost:8086]: database "telegraf" creation failed: 401 Unauthorized`

The Configuration is as follows:
`
[global_tags]
[agent]
  debug = true
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"

[[inputs.vsphere]]
  interval = "20s"
  vcenters = [ "https://vcenter-address1/sdk", "https://vcenter-address2/sdk" ]
  username = "vcsa-user"
  password = "vcenter-pw"

  vm_metric_include = []
  host_metric_include = []
  datastore_metric_exclude = ["*"]

  max_query_metrics = 256
  timeout = "60s"
  insecure_skip_verify = true
  [[inputs.vsphere.tags]]
    influxdb_database = "dc"

[[inputs.vsphere]]
  interval = "300s"
  vcenters = [ "https://vcenter-address1/sdk", "https://vcenter-address1/sdk" ]
  username = "vcsa-user"
  password = "vcenter-pw"

  datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest" ]
  cluster_metric_include = []
  datacenter_metric_include = []
  insecure_skip_verify = true
  force_discover_on_init = true
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  max_query_metrics = 256
  collect_concurrency = 3
  [[inputs.vsphere.tags]]
    influxdb_database = "dc"

[[outputs.influxdb_v2]]
  urls = ["https://influx-address"]
  token = "very_secure_token"
  organization = "Datacenter"
  bucket = "vsphere"
  [outputs.influxdb.tagpass]
    influxdb_database = ["dc"]
`

Can anybody help me?
