### ISSUE TITLE
How to calculate queue depth for diskio ?

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5888]
I am looking at the diskio readme and see below -

Calculate average queue depth:
iops_in_progress will give you an instantaneous value. This will give you the average between polling intervals.

But, if i see iops_in_progess definition it says below (saying items in the queue not included) -

iops_in_progress:
This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver.

I am looking for a metric will tell me the queue depth (requests waiting in the queue)

**Comment by danielnelson** [comment]
I don't have a straightforward answer for you, as fully understanding some of the values is quite complicated, but let me give a bit more information.  The diskio plugin uses `/proc/diskstats`, so it might be helpful to see what `Documentation/iostats.txt` says in addition to the other linked documents:
```
Field  9 -- # of I/Os currently in progress
    The only field that should go to zero. Incremented as requests are
    given to appropriate struct request_queue and decremented as they finish.

... snip ...

Field 11 -- weighted # of milliseconds spent doing I/Os
    This field is incremented at each I/O start, I/O completion, I/O
    merge, or read of these stats by the number of I/Os in progress
    (field 9) times the number of milliseconds spent doing I/O since the
    last update of this field.  This can provide an easy measure of both
    I/O completion time and the backlog that may be accumulating.
```

It may be that you need to look into `/sys/block/<dev>/queue` for this information, this is not exposed in any plugin currently, but the `multifile` plugin would probably be the way to go about collecting from sysfs.
