### ISSUE TITLE
Couchbase plugin enhancement - add timeout parameter

### ISSUE THREAD

**Issue by abbasalizaidi** [influxdata/telegraf#5889]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a request timeout parameter for couchbase plugin
### Current behavior:
Requests from couchbase plugin are getting timed out in case the server is loaded.

### Desired behavior:
There should be a way to tweak the timeout period for couchbase plugin. Similar to what we have in exec plugin.

### Use case: 
In case the server is loaded and requests get timed out, we will not be able to receive data and observability of couchbase cluster gets hampered.

**Comment by abbasalizaidi** [comment]
I am getting this message in telegraf logs
`2019-05-22T06:56:00Z E! Error in plugin [inputs.couchbase]: took longer to collect than collection interval (10s)`

**Comment by powersj** [comment]
next steps: look to adding a parameter to set the HTTP client timeout, similar to how other plugins do this.

**Comment by sspaink** [comment]
@abbasalizaidi are you still interested in seeing this feature request implemented? It seems like multiple other plugins (e.g. https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tomcat) have this already implemented so it shouldn't be too difficult.
