### ISSUE TITLE
inputs.cloudwatch fails when using statistic_include filter

### ISSUE THREAD

**Issue by alternativc** [influxdata/telegraf#5893]
### Relevant telegraf.conf:
```
198 [[inputs.cloudwatch]]
199    region = "eu-central-1"
200    period = "5m"
201    delay = "5m"
202    interval = "5m"
203    namespace = "AWS/EC2"
204    ratelimit = 10
205    statistic_include = [ "average" ]
```

### System info:
Centos7, Telegraf 1.10.4
### Steps to reproduce:

1. Use `statistic_include` as namespace or metric wide filter
2. Run telegraf

### Expected behavior:
Should filter metrics
### Actual behavior:
Fails when run (with or without --test flag)
### Additional info:
```
[root@telegraf1 telegraf]# /bin/telegraf --config telegraf.conf --input-filter cloudwatch --test
2019-05-22T12:20:49Z I! Starting Telegraf 1.10.4
2019-05-22T12:20:49Z E! [telegraf] Error running agent: Error parsing telegraf.conf, line 205: field corresponding to `statistic_include' is not defined in `*cloudwatch.CloudWatch'
```

**Comment by danielnelson** [comment]
This option is new for 1.11, you can try the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) or expect a release candidate next week.  When browsing the github docs, make sure you select the release branch for the version you are using, for example `release-1.10`.
