### ISSUE TITLE
Reuse connections from connection pool in sqlserver input

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#5898]
### Proposal:

The sqlserver input should reuse connections from the connection pool.

### Current behavior:

New connection pool is created every interval.

### Desired behavior:

Hang on to the connection pool and reuse.

### Use case: 

Should be a lighter resource load on Telegraf and the server.

See also https://github.com/influxdata/telegraf/issues/3485#issuecomment-494887920

**Comment by nwneisen** [comment]
I would like to take a look at making this change.

From what I can tell from looking at the PostgresSql plugin, the initialization and stop code for SqlServer should be moved into a service plugin.  The service plugin will setup the connection pool to be used by the regular input plugin.  When telegraf is terminated, the service plugin will be responsible for cleaning up the connection pool.  This should also cleanup the structure of the SqlServer plugin as it currently has a number of checks to make sure everything is initialized.

I think I've got everything I need to start on this but wanted to lay out the plan in case someone sees something I'm missing.

**Comment by mjiderhamn** [comment]
> New connection pool is created every interval.

AFAI can tell, a new pool is even created _for every query_ at every interval.
