### ISSUE TITLE
Add additional metrics to the `internal` plugin

### ISSUE THREAD

**Issue by zoonage** [influxdata/telegraf#5900]
## Feature Request

Whilst troubleshooting a Telegraf issue earlier I realised it would have been nice to know how many goroutines were running at a given point in time. This can be found by `runtime.NumGoroutine()`. I wanted to kickstart a discussion about other metrics that people might want to add to the internal plugin.

### Proposal:
Add a metric from `runtime.NumGoroutine()` to the `internal` plugin.

### Current behavior:
Telegraf does not currently support this metric

### Desired behavior:
To be able to see the number of goroutines that Telegraf is using

### Use case: 
Helps troubleshoot issues with Telegraf

**Comment by danielnelson** [comment]
Seems like a good idea, can you open a pull request?

**Comment by russorat** [comment]
Which measurement would you put numgoroutine in? it doesn't seem to fit well into any of the existing ones. maybe adding an internal_runtime measurement?

Other things that might be useful to have (from: https://github.com/influxdata/influxdb/blob/master/prometheus/influx.go#L27):
- "version":    build.Version,
- "commit":     build.Commit,
- "build_date": build.Date,
- "os":         runtime.GOOS,
- "arch":       runtime.GOARCH,
- "cpus":       strconv.Itoa(runtime.NumCPU()),

**Comment by zoonage** [comment]
The number of CPUs is already reported via the `n_cpus` field on the `system` measurement

**Comment by danielnelson** [comment]
We can add `num_goroutine` to `internal_agent`.  Let's skip build date and commit for now, they impose requirements on the build.  Things like number os and arch would make more sense to me to add them to the `system` plugin potentially with additional platform information.
