### ISSUE TITLE
postgresql_extensible interval per query

### ISSUE THREAD

**Issue by AgDude** [influxdata/telegraf#5903]
### Proposal:
within each `[[inputs.postgresql_extensible.query]]` block in config I would like to be able to define an interval, to supersede the plugin interval. 

### Current behavior:

Interval can be defined only at the agent or plugin level.

### Use case: 

Some monitoring queries are fast/cheap, and high resolution is important. Others cause more load, but do not require high resolution.  This plugin opens the possibility to query complex application specific metrics, but without a longer interval (sometimes hourly or daily is enough) some of those queries are prohibitively expensive.

**Comment by danielnelson** [comment]
You can specify multiple input plugins, one for each interval duration:
```
[[inputs.postgresql_extensible]]
  interval = 10s
  address = "foo"
  [[inputs.postgresql_extensible.query]]
    sqlquery = "select 1"

[[inputs.postgresql_extensible]]
  interval = 30s
  address = "foo"
  [[inputs.postgresql_extensible.query]]
    sqlquery = "select 1"
```

I know this produces a bit of duplication in the config but we don't like to have more than one interval per plugin instance, as it complicates things quite a bit.

**Comment by AgDude** [comment]
Thanks for the pointer. I am not sure how I missed that plugins can be duplicated!
