### ISSUE TITLE
running on FreeBSD issues

### ISSUE THREAD

**Issue by cheffo** [influxdata/telegraf#591]
Hi,

I'm trying to create a port of Telegraf for FreeBSD ports system, but the are two issues - first is mongodb input:

```
package github.com/influxdb/telegraf/plugins/inputs/mongodb
        imports gopkg.in/mgo.v2
        imports gopkg.in/mgo.v2-unstable/internal/scram: use of internal package not allowed
```

And second problem is with diskio input - it does not read properly disk names (in linux we have sda, sdb in FreeBSD naming convention is different).

Exact error is:
```
* Plugin: diskio, Collection 1
2016/01/27 14:30:26 error getting disk io info: no such file or directory
```

Snippet from my config file:

```
[[inputs.diskio]]
  # By default, telegraf will gather stats for all devices including
  # disk partitions.
  # Setting devices will restrict the stats to the specified devices.
  Devices=["ada0","ada1"]
  # Uncomment the following line if you do not need disk serial numbers.
  # SkipSerialNumber = true
```

**Comment by sparrc** [comment]
@cheffo How are you getting dependencies, are you using https://github.com/sparrc/gdm? If you use that there shouldn't be any import of mgo.v2-unstable.

I'm not sure about the diskio error, looks like it's coming from `gopsutil`. What is your exact OS and architecture? And do you get any errors if you comment out the `Devices` line?

**Comment by cheffo** [comment]
@sparrc I'm fetching the dependencies using the FreeBSD ports system framework to fetch dependencies. It's similar of fetching them manually then puting them all in the "src" folder.

Looks like I got the wrong revision numbers for mgo.v2 and reverting to the proper branch it's building as expected. (I do fetch it from here - https://github.com/go-mgo/mgo/tree/v2) as there is no support for gopkg.in in the ports system right now.

Have in mind that for working port I need to fetch all dependencies in advance (and specify checksums and sizes), because during the build process due to security requirements the system does not have access to internet.
Anyway the mongodb issue is now resolved as it looks like a mistake on my side.

Regarding diskio - I do get the same error with and without commenting the Device line.
Today I have tried with Latest commit (61dd483) of gopsutil and I still get the same error message. It's strange because I see they do have support for FreeBSD.

I'm doing all this on FreeBSD 10.2-RELEASE-p7 amd64

**Comment by cheffo** [comment]
@sparrc here is the port itself - https://github.com/cheffo/FreeBSD-Ports/tree/master/net-mgmt/telegraf

**Comment by sparrc** [comment]
@cheffo I can't quite reproduce this, I'm running a FreeBSD 10.1 VM and it collects diskio just fine: 

```
[vagrant@vagrant-freebsd-101-amd64 ~]$ /vagrant/telegraf -config t.conf -input-filter diskio -test
* Plugin: diskio, Collection 1
> diskio,name=cd0,serial=unknown io_time=0i,read_bytes=32i,read_time=0i,reads=4i,write_bytes=0i,write_time=0i,writes=0i 1454089022990332297
> diskio,name=pass0,serial=unknown io_time=0i,read_bytes=0i,read_time=0i,reads=0i,write_bytes=0i,write_time=0i,writes=0i 1454089022990387859
> diskio,name=pass1,serial=unknown io_time=0i,read_bytes=0i,read_time=0i,reads=0i,write_bytes=0i,write_time=0i,writes=0i 1454089022990422049
> diskio,name=da0,serial=unknown io_time=0i,read_bytes=19657216i,read_time=0i,reads=1106i,write_bytes=4739584i,write_time=0i,writes=216i 1454089022990450764
```

can you provide some guidance on how I can install the port directly to reproduce? I'm not very familiar with the FreeBSD ports system

**Comment by cheffo** [comment]
@sparrc All you need is to have a FreeBSD with ports installed in it (normaly in /usr/ports/)

Then just download my port, copy the folder in /usr/ports/net-mgmt/telegraf, cd there and run "make install clean" - this will download, build and install telegraf on your VM.

**Comment by cheffo** [comment]
@sparrc I'm using 0.10.0 release - I just saw that 0.10.1 is available and will update and report.

**Comment by vat9** [comment]
A few of the inputs will likely need to be modified to support FreeBSD as gopsutil doesn't support everything on BSD yet.  In particular the netstat and zfs inputs won't provide information.  Netstat may eventually be included in gopsutil, but I'm not sure if it's important to that project.  As for zfs, it will need a zfs_freebsd.go implementation that wraps sysctl to produce the same data as the zfs_linux.go (current zfs.go) that uses /proc.

**Comment by cheffo** [comment]
@sparrc This is how-to-repeat without sing ports system:

export GOPATH=/home/path/to/influxdata

go get -u -t github.com/influxdata/telegraf
 cd src/github.com/influxdata/telegraf
 go get -u -t ./...
 go install ./...
 ../../../../bin/telegraf -sample-config > /tmp/telegraf.conf
 ../../../../bin/telegraf -config /tmp/telegraf.conf -input-filter diskio -test

 * Plugin: diskio, Collection 1
2016/02/02 18:22:20 error getting disk io info: no such file or directory

Am I doing soemthing wrong?

P.S. From config file:

# Read metrics about disk IO by device
[[inputs.diskio]]
  # By default, telegraf will gather stats for all devices including
  # disk partitions.
  # Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  # Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true

**Comment by cactus** [comment]
I ran into this on a FreeBSD-10.2-RELEASE-p12 system. Seems like the magic sysctl mib changed for kern.devstat.all. After much banging around (I'm not super familiar with cgo), I managed to get something working and opened a [pull req](https://github.com/shirou/gopsutil/pull/145) on the gopsutil project.

Not sure as to the fitness of the pull req yet though.

**Comment by sparrc** [comment]
Thanks @cactus, that looks to be the problem, looks like it was introduced in 10.2 because 10.1 works fine

**Comment by cactus** [comment]
Fix was merged upstream in gopsutil.

**Comment by cheffo** [comment]
I can confirm that updating telgraf to 0.10.2 and all dependencies fix the issue!
I'm closing this now.
