### ISSUE TITLE
A better way of excluding everything by default.

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#5918]
## Feature Request

Using the standard include/exclude logic, it is awkward to exclude everything by default.

### Proposal:

We need to find a better way of handling include/exclude when everything should be excluded by default. My initialization code looks as follows:

```
type VSphere struct {
...
   CustomAttributeInclude:  []string{},
   CustomAttributeExclude:  []string{"*"},
}
```

The standard behavior is (?) that in order to disable something, you'd have to set it to exclude everything, since an empty set in the include setting defaults to including everything. 

However, if I simply set up my config file as follows, it will still exclude everything:

```
custom_attribute_include = ["*"]
custom_attribute_exclude = []
```

This is because an empty exclude clause is interpreted as "use the default" as per the struct above. Therefore, it will revert back to ```custom_attribute_exclude = ["*"]```

The only way to make it ignore the exclude clause seems to put a dummy value in it like this:

```
custom_attribute_include = ["*"]
custom_attribute_exclude = ["nothing"]
```

This works, but is extremely kludgy. 

Is there a better way of handling this that I have somehow missed?

**Comment by prydin** [comment]
It seems like this works too. Is this the recommended way of doing this? Still a bit kludgy IMHO. 

```
custom_attribute_include = ["*"]
custom_attribute_exclude = ["nothing"]
```

**Comment by danielnelson** [comment]
> However, if I simply set up my config file as follows, it will still exclude everything:
> ```
> custom_attribute_include = ["*"]
> custom_attribute_exclude = []
> ```

This should set these two values, overwriting the default values... it should work without the workaround.  However, it wouldn't work if it were commented out.

**Comment by prydin** [comment]
It seems to default to ```custom_attribute_exclude = ["*"]``` if I give it an empty array. Could be something in my code. I'll check it. But I *think* the code in telegraf core treats empty arrays the same as nil.

**Comment by prydin** [comment]
Looks like we have a problem. If I set ```custom_attribute_exclude = []``` and run the code, I get this:

![image](https://user-images.githubusercontent.com/5239535/58520236-d7574e00-8184-11e9-8349-aa47697d99e5.png)

The empty array is now replaced with ```["*"]```

Unless this is how it's supposed to work.

**Comment by prydin** [comment]
https://github.com/influxdata/toml/blob/2a2e3012f7cfbef64091cc79776311e65dfa211b/decode.go#L334

**Comment by danielnelson** [comment]
I think this might be changed in master, I tried to duplicate the issue and I don't see it.  We are now using the "telegraf" branch of the repo, code is quite different.

**Comment by prydin** [comment]
This issue disappeared after merging with latest upstream.
