### ISSUE TITLE
Allow to customize (or tag) inputs.net interface names (map eth0, enp0s3, xn0, ether1 etc. to LAN, WAN, OPT)

### ISSUE THREAD

**Issue by lmojzis** [influxdata/telegraf#5919]
As the title says. I would like to allow passing of customized interface names based on dev name (or, if anyone else is interested, some other attribute.)

WHY:
I'm currently monitoring the network in Grafana. I have custom dashboards that show downloads and uploads based on bytes received on interface != /0$/ and upload as bytes sent on interface ~= /0$/
(my naming convention is eth0 is supposed to always be LAN and eth1/eth2 etc is supposed to be WAN1/WAN2/OPT)

the problem is othen it's not ALWAYS eth0 because someone else set it up as eth1 or the name simply doesn't follow the eth0, eth1 naming and uses the enp0s1 scheme. Or even worse, it's en0 and re0. Now what?

PROPOSAL:
I believe it would be beneficial to be able to go with either allowing interface name tags based on either custom name tag (WAN%d/uplink%d/etc) or remapping the output name entirely.
I believe this should be implemented to allow cross-platform or cross/vendor data integrity.

Other possibility is to add a flag based on whether or not the interface is present in the routing table.
    `netstat -nr | grep **re0** | awk '{print $1}' | grep default`

Please give me your constructive feedback. I'm not saying this is how it's supposed to be, just pointing out there might be something missing in the current implementation. I did read the docs but am unsure how to accomplish the same with the current implementation.

**Comment by danielnelson** [comment]
> I believe it would be beneficial to be able to go with either allowing interface name tags based on either custom name tag (WAN%d/uplink%d/etc) or remapping the output name entirely.

Could you use the regex processor as is to do this remapping of the tag?

> Other possibility is to add a flag based on whether or not the interface is present in the routing table.
netstat -nr | grep **re0** | awk '{print $1}' | grep default

Something like this could be implemented with a new processor that would decorate the net metrics with additional tags.

---

I agree that it seems like what we would really like to do is query by network, and not by interface name.   One issue here is that an interface can be connected to many networks:
```
0.0.0.0         10.79.40.1      0.0.0.0         UG    6      0        0 bond0
10.79.40.0      0.0.0.0         255.255.255.0   U     6      0        0 bond0
```

I have a dream where you can have multiple values for a tag at once, but unfortunately its just a dream and is not valid:

```
# illegal
net,device=eth0,network=0.0.0.0,network=10.79.40.0 bytes_sent=42i
```

So in general you would need to duplicate the data:
```
net,device=eth0,network=0.0.0.0 bytes_sent=42i
net,device=eth0,network=10.79.40.0 bytes_sent=42i
```

However, I think in many cases with the duplicate data, you could use a filter to only output specific networks:
```
# imaginary processor that adds route info
[[processors.route]]
  tag = "device"

# must filter on output, because processors cannot filter their own output :(
[[outputs.influxdb]]
  [outputs.influxdb.tagdrop]
    # this is also messy, we want only to drop "net" measurements with non "0.0.0.0" as the network
    network = ["10.*"]
```
