### ISSUE TITLE
doc: configuration for tags

### ISSUE THREAD

**Issue by steverweber** [influxdata/telegraf#592]
please give an example of a "normal map"
```
# Tags can also be specified via a normal map, but only one form at a time:
[tags]
  # dc = "us-east-1"
```

also `CONFIGURATION.md` seems to be missing docs for `[tag]`

**Comment by sparrc** [comment]
That is a bit vague, I'm actually not sure what that means either :sweat_smile:.

I'll rewrite that bit and put a section in the config readme. For now just know that you can simply specify tags there as key="value" pairs,

```
# Global tags can be specified here in key="value" format
[tags]
  dc = "us-east-1" # will tag all metrics with dc=us-east-1
  mytag = "myvalue"
```

make sense?

**Comment by steverweber** [comment]
> make sense
yes

Still a little interested what the normal map might look like...

best not to support two formats, so im happy with your edit.

**Comment by sparrc** [comment]
I think he probably meant like this: https://github.com/toml-lang/toml#inline-table

so we support that too since it's valid toml, but you can only use one or the other.

**Comment by steverweber** [comment]
ah ic thanks.

`tags = { first = "Tom", last = "Preston-Werner" }`
