### ISSUE TITLE
Add additional metrics about indices statistics like docs count to the `elasticsearch` plugin 

### ISSUE THREAD

**Issue by rangwea** [influxdata/telegraf#5925]
## Feature Request

I wanted to collect the metrics about elasticsearch. So that I can better observe elasticsearch state. But I find Telegraf does not support the metrics about elasticsearch indices statistics.I think it is very useful, so I implemented this feature.

### Proposal:

Add additional metrics about indices statistics like docs count to the `elasticsearch` plugin.

### Current behavior:

Telegraf does not currently support this metric.

### Desired behavior:

To be able to see the metrics about elasticsearch indices statistics. 

### Use case: 

Users often care the metric about elasticsearch indices statistics.

**Comment by glinton** [comment]
[In the documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/elasticsearch#measurements--fields), it appears to be a field (`docs_count value=29652`). It also appears to be added as a field [in the code](https://github.com/influxdata/telegraf/blob/release-1.10/plugins/inputs/elasticsearch/elasticsearch.go#L296-L320)

Can you paste your config as well as the output of `telegraf --config /path/to/your/config.conf --filter-input elasticsearch --test `
