### ISSUE TITLE
Support strings processor operating on tag/field keys

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#5928]
I may simply not be understanding but i am collection win perf counters Avg._Disk_Bytes/Write
I want to replace the / with _ in the resultant field name in influxdb
i have the following config but it is still coming as Avg._Disk_Bytes/Write and not Avg._Disk_Bytes_Write

[[processors.strings.replace]]
    field = ""
	old = "/"
	new = "_"

**Comment by danielarkins** [comment]
i believe i found my (suspected this) answer here https://github.com/influxdata/telegraf/issues/5173

does anyone know of any enhancements that may achieve the above?

**Comment by danielnelson** [comment]
The only method currently for doing this I'm aware of is the one listed in #5173.

**Comment by stagedataloss** [comment]
test123HelloWorldtest123

**Comment by DenKn** [comment]
I ran into the same problem.
#5173 is very uncomfortable, unfortunately.

I need substring replacement for tag and field keys.
