### ISSUE TITLE
cpu plugin reports negative values

### ISSUE THREAD

**Issue by llitz** [influxdata/telegraf#5931]
Not sure how to reproduce this one, but I am frequently receiving negative stats in the cpu module.

Most times the usage_user matches usage_guest, but that is not always the case. I have seen the negative issue showing up on usage_system and usage_iowait too.

stats are collected every 1s

This happens with telegraf 1.10.1 (compiled on gentoo) and telegraf 1.10.4 running on docker in different hosts.

```
2019-05-31T06:04:42Z I! Using config file: /etc/telegraf/telegraf.conf
> cpu,cpu=cpu4,host=nas usage_guest=1.9607843142709773,usage_guest_nice=0,usage_idle=96.07843136717807,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=1.9607843149843065,usage_user=-0.0000000007133291781737506 1559282683000000000
> cpu,cpu=cpu5,host=nas usage_guest=1.9999999985448085,usage_guest_nice=0,usage_idle=97.99999995343387,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=-0.0000000007275957607407162 1559282683000000000
> cpu,cpu=cpu14,host=nas usage_guest=1.9999999981810106,usage_guest_nice=0,usage_idle=97.99999995343387,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=-0.0000000003637978803703581 1559282683000000000
2019-05-31T06:04:45Z I! Using config file: /etc/telegraf/telegraf.conf
> cpu,cpu=cpu8,host=nas usage_guest=1.9607843146276418,usage_guest_nice=0,usage_idle=98.0392157292421,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=1.9607843149843065,usage_user=-1.9607843146276418 1559282686000000000
> cpu,cpu=cpu13,host=nas usage_guest=1.9999999999527063,usage_guest_nice=0,usage_idle=100,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=-1.9999999999527063 1559282686000000000
> cpu,cpu=cpu14,host=nas usage_guest=2.0000000000436557,usage_guest_nice=0,usage_idle=100,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=-2.0000000000436557 1559282686000000000
> cpu,cpu=cpu-total,host=nas usage_guest=0.3749999999854481,usage_guest_nice=0,usage_idle=99.3750000372529,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0.25000000023283064,usage_user=-0.0000000003637978807091713 1559282686000000000

2019-05-31T06:04:50Z I! Using config file: /etc/telegraf/telegraf.conf
> cpu,cpu=cpu14,host=nas usage_guest=2.0000000000436557,usage_guest_nice=0,usage_idle=97.99999995157123,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0,usage_user=-0.0000000003637978807091713 1559282691000000000

2019-05-31T06:04:51Z I! Using config file: /etc/telegraf/telegraf.conf
> cpu,cpu=cpu4,host=nas usage_guest=2.0408163260154466,usage_guest_nice=0,usage_idle=97.95918362498321,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=2.040816325273002,usage_user=-2.0408163260154466 1559282692000000000
```

**Comment by danielnelson** [comment]
I've seen this before on AWS EC2 and in LXC, it every case so far it was tracked back to the values in `/proc/stat` decreasing, which should never happen, but you know how that goes sometimes.

Is there anything notable about the system hardware?  Are you using a cloud provider or another virtualization for the Host (outside of docker)?  Running a cutting edge kernel or new hardware?  How many systems have you seen it on?

**Comment by llitz** [comment]
Both servers are bare metal in my home. One is an AMD Ryzen 2700x and the
other a ThreadRipper 2950x

I specifically did a loop with:

while :; cat /proc/stat; done | less

and, in another windows, run a similar command testing the cpu input plugin
from telegraf.

I couldn't see the values in /proc/stat decresing, they were constant every
time I checked (I may write a different script to validate that based on
your information).
Digging into the code into the code I saw that usage_user is subtracted by
the usage_guest value, which prompted me to do usage_user + usage_guest so
it would zero, but that is not working well either: usage_user should be
-50 to match +50 on guest and it is only -1 or -2, making the graphics
funny all around.

**Comment by danielnelson** [comment]
Might be helpful to enable `collect_cpu_time` to get the save the raw jiffies.  Since this is usually happening on usage_guest and usage_user, are these systems both qemu hosts?

FWIW I'm not seeing anything similar on my Ryzen 1700.

**Comment by aaronjwood** [comment]
I see this behavior on a qemu host (proxmox). Sometimes the userspace execution metric goes to -.10 or -.11. @danielnelson shall I enable `collect_cpu_time` and post the results here?

**Comment by powersj** [comment]
next steps: review this one and come to a conclusion as to the values we return. We, telegraf, are currently doing the math ourselves that create the very small negative value. If we decide to continue to do this, then we need to document this as it has come up before.

**Comment by srebhan** [comment]
@aaronjwood or @llitz can you please collect some logs with `collect_cpu_time = true` and post them here!? We need at least the latest metrics (with the negative values) **and** one or two metrics before that line...
