### ISSUE TITLE
input http_response cookies and sessions

### ISSUE THREAD

**Issue by osd42** [influxdata/telegraf#5932]
## Feature Request

In http_response input, can you add the ability to retrieve cookie headers and reuse them ?
1) option to auth on a specific url (different than url to query for the test)
2) option to choose cookies mandatory variables to validate the auth state

idea found on https://community.influxdata.com/t/can-you-use-cookies-with-the-http-response-plugin-in-telegraf/3825 

In my case, there are php sessions cookies and others cookies crafted with javascript so I will have to write my own curl script or ask my developpers to give me a real URL for a checktest using telegraf http_response input.

**Comment by jh125486** [comment]
With the recent Tesla Powerwall update, the only way to authenticate and pull API data is using an `/auth` endpoint and storing those cookies in a jar to reuse for subsequent calls.

I'm decently versed in Go if the maintainers are willing to accept a PR.

**Comment by widdakay** [comment]
I am having the same issue and would also be happy to contribute where possible (though I have less Go experience).

**Comment by jh125486** [comment]
@osd42 , I've finally got around to working on this.
Do these config values make sense for your use case?:

```toml
## Cookie-based authentication
# cookie_auth_url = "https://localhost/authMe"
# cookie_auth_method = "POST" [default: POST]
# cookie_auth_body = {"username": "user", "password": "pa$$word", "authenticate": "me"}
# cookie_auth_renewal = 8h [default: 5m]
```

It will use the `username`/`password` HTTP Basic auth if it's defined in the config, and will use all the cookies returned from cookie auth for subsequent calls.

**Comment by tekkamanendless** [comment]
Now that `1.20.0` is out, I can confirm that this works perfectly with my Telsa energy gateway.  This is so much more convenient than hand-hacking the `Cookie` header every couple of weeks.

Thank you!

Relevant config for Tesla:

```
cookie_auth_url = "https://YOUR_ENERGY_GATEWAY/api/login/Basic"
cookie_auth_method = "POST"
cookie_auth_body = '{"username": "customer", "email": "YOUR_EMAIL", "password": "YOUR_PASSWORD"}'
# Renew the cookies every week.
cookie_auth_renewal = "168h"
```
