### ISSUE TITLE
reporting interval drift over time

### ISSUE THREAD

**Issue by randallt** [influxdata/telegraf#5937]
### Relevant telegraf.conf:

```
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "60s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Logging configuration:
  ## Run telegraf with debug log messages.
  debug = false
  ## Run telegraf in quiet mode (error log messages only).
  quiet = false
  ## Specify the log file name. The empty string means to log to stderr.
  logfile = "/var/log/telegraf/telegraf.log"

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.wavefront]]
  host = "CHEF_REPLACE_WAVEFRONT_HOST"
  port = 5879
  metric_separator = "."
  #source_override = ["source", "hostname", "snmp_host", "node_host"]
  convert_paths = true

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = false
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = true
  fieldpass = ["usage_active","usage_user","usage_system","usage_idle","usage_iowait"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]
  interval = "30m"
  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "rootfs"]
  fieldpass = [ "total", "free" ]

# Read metrics about disk IO by device
[[inputs.diskio]]
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  interval = "2m"
  devices = ["sd?", "hd?"]
  fieldpass = [ "read_time", "write_time", "read_bytes", "write_bytes" ]

# manually get cpu_speed
[[inputs.exec]]
  interval = "30m"
  commands = ['''sh -c "echo \"cpu speed=$(cat /proc/cpuinfo | grep 'cpu MHz' | head -n 1 | awk '{print $4;}')\""''']
  timeout = "5s"
  data_format = "influx"

# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  fieldpass = [ "context_switches", "entropy_avail" ]

# Read metrics about memory usage
[[inputs.mem]]
  fieldpass = [ "available" ]  

# Read metrics about memory usage
[[inputs.mem]]
  interval = "30m"
  fieldpass = [ "total" ]  

# # Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  # interfaces = ["eth0"]
  ##
  ## On linux systems telegraf also collects protocol stats.
  ## Setting ignore_protocol_stats to true will skip reporting of protocol metrics.
  ##
  ignore_protocol_stats = true
  fieldpass = [ "bytes_sent", "bytes_recv", "packets_sent", "packets_recv" ]

# # Read TCP metrics such as established, time wait and sockets counts.
[[inputs.netstat]]
  fieldpass = [ "tcp_established", "tcp_time_wait", "tcp_close_wait", "tcp_listen" ]

# Get the number of processes and group them by status
[[inputs.processes]]
  fieldpass = [ "running", "total" ]

# Read metrics about swap memory usage
[[inputs.swap]]
  interval = "30m"
  fieldpass = [ "total" ]

# Read metrics about swap memory usage
[[inputs.swap]]
  fieldpass = [ "free", "in" ]
  
# Read metrics about system load & uptime
[[inputs.system]]
  fieldpass = [ "load1","load5","load15" ]

# Read metrics about system load & uptime
[[inputs.system]]
  interval = "30m"
  fieldpass = [ "uptime" ]

# manually get cpu count due to https://github.com/influxdata/telegraf/issues/5451
[[inputs.exec]]
  interval = "30m"
  commands = ['''sh -c "echo \"system n_cpus=$(cat /proc/cpuinfo | grep 'physical id' | wc -l)\""''']
  timeout = "5s"
  data_format = "influx"

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################


# # Generic socket listener capable of handling multiple socket types.
[[inputs.socket_listener]]
  ## run more often to empty the read buffer
  interval = "5s"

  ## URL to listen on
  service_address = "tcp://localhost:5883"

  ## Maximum number of concurrent connections.
  ## Only applies to stream sockets (e.g. TCP).
  ## 0 (default) is unlimited.
  max_connections = 1024

  ## Read timeout.
  ## Only applies to stream sockets (e.g. TCP).
  ## 0 (default) is unlimited.
  read_timeout = "30s"

  ## Maximum socket buffer size in bytes.
  ## For stream sockets, once the buffer fills up, the sender will start backing up.
  ## For datagram sockets, once the buffer fills up, metrics will start dropping.
  ## Defaults to the OS default.
  read_buffer_size = 8388608

  ## Period between keep alive probes.
  ## Only applies to TCP sockets.
  ## 0 disables keep alive probes.
  ## Defaults to the OS configuration.
  keep_alive_period = "5m"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"

```

### System info:

Telegraf version 1-6.1 through 1.10.4-1.
CentOS 6 and 7.

### Steps to reproduce:

1. Start telegraf with round_interval=true
2. Confirm metrics received at desired interval and timestamps
3. Wait a few days to a few weeks
4. Notice drift in the timestamps of reported metrics, e.g. 54 seconds over a few weeks in my case.

### Expected behavior:
Even after several weeks, metrics continue to be reported at the rounded interval timestamps, e.g. at the top of each minute.

### Actual behavior:
After several weeks, the timestamps of the metrics drift, meaning that slightly more time has elapsed between metric points than the indicated interval.
### Additional info:
This seems to affect all the plugins I am using, regardless of their interval, except the metrics reported by the vsphere plugin, although the internal vsphere metrics are also affected (enabled by the 'internal' plugin). The vsphere plugin is defined in a separate file on only a couple of hosts, and I don't see any change in the agent settings as defined above.

**Comment by randallt** [comment]
I first mentioned this issue under
https://github.com/influxdata/telegraf/issues/4652

**Comment by randallt** [comment]
I have the flush interval low to reduce latency for metrics received through the socket_listener. Could it be that, or the Wavefront output plugin causing the issue?

**Comment by danielnelson** [comment]
No, all metrics receive a timestamp on creation in the inputs, and the outputs just report what they are set to.  I believe vSphere is using timestamps from the server instead of using the current time of collection, which probably is the reason for its non-drifting times.

**Comment by Daryes** [comment]
It might be possible it's related to the fact time on VM will drift, due to the variable clock speed (check Intel Speedstep) on the host and the guest not able to cope correctly.
The usual best practice is to disable the VM automatic time sync from the host, and using instead a NTP client (timesyncd or others). This will reduce it to a nearly transparent level, but it will still exists.  

Currently, I've seen latest Telegraf releases still drifting on a Windows VM, and something new, even on Linux VM but only at boot time. A process restart fixes this for both.

The drift on Linux VM at boot make me think Telegraf doesn't compare its own timer and the current server time after launch, as the NTP client can sometimes take some seconds to adjust the time.

**Comment by randallt** [comment]
I have not seen any noticeable time drift on our VMs--I think we are already setup with an NTP client sync. Also, the fact that metrics coming in on the socket_listener (only coming from the local host) do not drift seems to say it isn't a problem with the system time.

**Comment by randallt** [comment]
I have little experience with Go, but looking at the code, it seems pretty obvious that there will be drift--the input sleeps never take the current time into account that I can see. The duration of the SleepContext is always the same, instead of getting a new 'time.Now' value it uses the startTime each time.

I looked at 

- agent.runInputs
- internal.SleepContext
- internal.AlignDuration
- internal.AlignTime

Am I missing something?

**Comment by randallt** [comment]
The ticker seems to have the same issue--it doesn't take processing time in telegraf code into account and just waits the interval time inbetween gathers each time.

The algorithm should be something like (Java code):
```
		long now = System.currentTimeMillis();
		long sampleIntervalMillis = Config.getSampleInterval() * 1000;
		long toSleep = sampleIntervalMillis - now % sampleIntervalMillis;
		try {
			log.info("Sleeping to preserve sampling cadence: " + toSleep + " ms");
			Thread.sleep(toSleep);
		} catch (InterruptedException ie) {
			Thread.currentThread().interrupt();
			throw new RuntimeException(ie);
		}
```

I understand that with small intervals you might not want to do something like this for every interval, but having a time drift cleanup every once in a while might be an approach...

**Comment by danielnelson** [comment]
It's not quite as bad as you think. The Ticker in `gatherOnInterval` is the primary ticker for the plugin gather interval, it will tick every `interval` regardless of how long the plugin takes, and it doesn't wait for the plugin to complete before rescheduling: the tick is continual and independent.

The reason drift is still expected is that the way the ticker works by sleeping for the same duration over and over, instead of calculating the amount of time it should sleep (until the next now % interval) each interval.

**Comment by randallt** [comment]
Is it an option to fix this so that no drift is expected? It doesn't seem like a technical limitation.

**Comment by danielnelson** [comment]
Yes, should just be a matter of moving away from using the Ticker type to something more like your code.

**Comment by randallt** [comment]
Cool. Any idea which release you might be able to squeeze this in?

**Comment by prydin** [comment]
Indeed, the vSphere plugin uses the timestamps it obtains from the server. This is by design, since this is the true collection time. This is especially important in this plugin, since vCenter can delay samples under load.

vSphere realtime data is made available available every 20s. Let's say the clocks of your telegraf server and the vCenter host are perfectly in sync when you start telegraf. Let's also assume you collect data every 60 seconds, rounding to the collect at the top of every minute. You should now see samples. that are dated mm:00 (where mm is the minute). Now let's assume the clock on your telegraf server is just slightly faster than the clock on vCenter. Each collection will now happen a couple of seconds before the top of the minute, as measured by the vCenter server's clock. This means that the mm:00 sample isn't available yet, so you will get the (mm-1):40 sample instead. 

I think this would be pretty difficult to get around. If I knew what the rounded time was supposed to be, I could pass that down to vCenter and ask for that sample specifically, but since it's not passed to the Collect() function, it's almost impossible to do. 

Since you're viewing the data in Wavefront, you could always add align(1m, ts(bla.bla)) to your queries. That will ensure that the data is arranged in 1 minute buckets starting at mm:00.

**Comment by danielnelson** [comment]
@randallt We could work on this in 1.12.

However, I'm not 100% sure this is the cause of your problems; hopefully it will take care of it but I'm unsure.  Generally the Ticker has been much more precise than this, I have some systems at home that have been running without restart for months and I don't even see a full second of drift.  One thing I notice from your configuration is that you have quite a few inputs set to 30m interval, and maybe this has something to do with it, as my intervals are all much smaller.  That's just a long way of saying we will fix it and then let's retest and hopefully it will all be nice ;)

**Comment by prydin** [comment]
@danielnelson I agree. Slight drift between the Telegraf server and the vCenter server is a much more likely culprit. I guess we could introduce a flag for letting Telegraf set the timestamp instead of using the one that comes from vCenter, but we'd be lying, since the one from vCenter is the *true* timestamp.

**Comment by randallt** [comment]
@prydin, my issue with drift here is independent of the vsphere plugin. The only reference to the vsphere plugin here is that samples from it did NOT drift (which is preferable). So I don't think a change should be considered in the vsphere plugin to match the drifting timestamps of the other input plugins.

**Comment by randallt** [comment]
Since 1.12 is already released, when can this be included?

**Comment by danielnelson** [comment]
Sorry was not able to finish this in time for 1.12, so it will have to be for 1.13.  However, I am working on this right now so I might have something ready for test soon.

**Comment by randallt** [comment]
Is this still on track to get into 1.13? I was hoping to test something for you.

**Comment by randallt** [comment]
What are the chances that this doesn't get pushed out again to 1.15.0? When is 1.14.0 expected to be released? I was waiting on this to update telegraf across my infrastructure.

**Comment by danielnelson** [comment]
@randallt I know you have been waiting on this one for some time, but unfortunately I needed to put it on the back burner in order to work on more pressing issues.  I'm still planning to get back on this one soon.

> I was waiting on this to update telegraf across my infrastructure.

Is there a version that this does work with?  I was under the impression that this has always been an issue.

**Comment by randallt** [comment]
I do not know a version that this isn't a problem. However, updating telegraf versions takes some effort, and I was holding off on that for this.

**Comment by randallt** [comment]
This has been pushed back several times. Candidly, what are the chances of a fix getting into telegraf?

**Comment by danielnelson** [comment]
@randallt Sorry about how long this has taken and thanks for your patience.  Making these changes has been a bit more challenging than I anticipated, and I'm still working on it, but I do have some code that is ready for testing.

If you are able to check if this build solves the drift problem it would very helpful, and also if you could keep an eye out for any other issues or increased resource use.  Let me know if you need a different package and I can provide a link.

- [telegraf-1.15.0~b80069a4-0.x86_64.rpm](https://53182-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.15.0~b80069a4-0.x86_64.rpm)

**Comment by randallt** [comment]
I have started an experiment with the test version and another system that is running v1.10.4-1 as a control. They have identical conf files (except for a single tag value).

I did notice that installing this RPM overwrote my telegraf.conf file, which wasn't too nice:
```
Running transaction
  Updating   : telegraf-1.15.0~b80069a4-0.x86_64                                                                                                                          1/2
  Cleanup    : telegraf-1.10.4-1.x86_64                                                                                                                                   2/2
warning: /etc/telegraf/telegraf.conf saved as /etc/telegraf/telegraf.conf.rpmsave
  Verifying  : telegraf-1.15.0~b80069a4-0.x86_64                                                                                                                          1/2
  Verifying  : telegraf-1.10.4-1.x86_64                                                                                                                                   2/2

Updated:
  telegraf.x86_64 0:1.15.0~b80069a4-0
```

**Comment by danielnelson** [comment]
Uh oh, probably related to #7250.

**Comment by Daryes** [comment]
Do you also have a Windows build, per chance ? 
It usually take a week to occurs, but I could speed it up when activating the monitoring for all active process

**Comment by randallt** [comment]
I can report that CPU utilization is lower for this test version than for version 1.10.4, but maybe that doesn't help as much. I'll download a more recent version as the control.

**Comment by randallt** [comment]
The CPU and memory comparison above is also valid for the control system at telegraf 1.14.1.

On systems where telegraf isn't doing much (< 60 metrics every min), I don't think I can detect the drift because the systems get rebooted periodically for patching.

However, I am seeing the issue on instances where I run the vcenter plugin, which is very active and pulling several thousand metrics per minute. Even though I have 
```
round_interval = true
interval = "60s" 
```
in telegraf.conf, on telegraf v1.14.1, metrics show up with timestamps that are not on the :00 second. This looks like it is NOT happening with the test build '1.15.0~b80069a4-0.x86_64'. I'm not sure this is the "drift" issue I reported in this issue, but it is goodness still.

**Comment by danielnelson** [comment]
That's good news, appreciate the testing.  I do have some minor changes on the #7390 pull request but it's overall the same, hope to have it in master in the next few days.

Here are the latest builds including for Windows:

- [telegraf-1.15.0~f7baa21e-0.x86_64.rpm](https://53491-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.15.0~f7baa21e-0.x86_64.rpm)
- [telegraf_1.15.0~f7baa21e-0_amd64.deb](https://53491-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.15.0~f7baa21e-0_amd64.deb)
- [telegraf-1.15.0~f7baa21e_windows_amd64.zip](https://53491-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.15.0~f7baa21e_windows_amd64.zip)

**Comment by Daryes** [comment]
For the record, I tested the v1.15 windows build, and it doesn't exhibit the problematic behavior, as opposed to others servers with the exact same configuration but a 1.14.x version.
So it seems good for me too.
