### ISSUE TITLE
Connections not closed on reload

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#5938]
### Relevant telegraf.conf:

Any plugins using a http.Client

### System info:

Any

### Steps to reproduce:

1. Start Telegraf
2. Send SIGHUP
3. Check `lsof -p $(pgrep telegraf)`

### Expected behavior:

Old connections from previous instance of the plugin are closed

### Actual behavior:

Connections still open from previous transport

### Additional info:

Same issue as in https://github.com/influxdata/telegraf/issues/5891 but needs to be fixed in any plugin creating a http.Transport.

Could potentially be fixed by setting IdleConnTimeout, but probably best to just call `internal.CloseIdleConnections(client)`.  However, this will require a shutdown signal so it may be worth making the Stop() function optional.

**Comment by sjwang90** [comment]
We welcome any PRs from the community that would address a bug fix for this issue. 

Thanks!
