### ISSUE TITLE
Add Grafana Loki logging output for telegraf.

### ISSUE THREAD

**Issue by devopstales** [influxdata/telegraf#5939]
## Feature Request
`Submission of telegraf output plugin for Grafana Loki`

### Proposal:
`Create telegraf output plugin to push data to  Grafana Loki`

### Current behavior:
 `No plugin exists`

### Desired behavior:
` Ability to configure output plugin for Grafana Loki`
### Use case: 
`I can use telegraf to get megrics for Prometheus. Loki is a Prometheus-inspired logging service so it would be nice, if I could send the logs of the application to Loki with telegraf.`

**Comment by rdxmb** [comment]
telegraf sends metrics, not logs. Have you tried out promtail for loki?

**Comment by danielnelson** [comment]
We do logs too, metrics/logs are basically treated the same for Telegraf.  For example we are adding a syslog output in the next release that can send metrics as logs, as well as log style data from the syslog, tail, and docker_log (coming soon) plugins.  So as long as we can come up with a way to encode metrics as logs, maybe logfmt or the serializers, it could work.

**Comment by cricket007** [comment]
@rdxmb 

> telegraf sends metrics, not logs

Refer - https://github.com/influxdata/telegraf/tree/master/plugins/outputs/syslog

**Comment by rdxmb** [comment]
Oh, I've just learned something new. Thanks!

**Comment by kOstovic** [comment]
Any status on this one?
