### ISSUE TITLE
Telegraf suddenly stopped writing to influx db using jolokia2_agent while it is forming json upon testing.

### ISSUE THREAD

**Issue by Veenumittal** [influxdata/telegraf#5947]
# Telegraf Configuration

[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
   username = "admin"
   password = "admin"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]

[[inputs.system]]

 [[inputs.jolokia2_agent]]
   urls = [
                "http://IP_ADDRESS:port/jolokia/"
          ]
   #response timeout is in nanoseconds 200000000 = 0.2 sec
   response_timeout = 200000000

  [[inputs.jolokia2_agent.metric]]
  name = "JDBC_POOL"
  mbean  = "com.bea:ServerRuntime=*,Name=*,Type=JDBCDataSourceRuntime"
  paths  = ["ActiveConnectionsCurrentCount","FailedReserveRequestCount","HighestNumAvailable","PrepStmtCacheCurrentSize","LeakedConnectionCount","PrepStmtCacheAccessCount","PrepStmtCacheAddCount","ActiveConnectionsHighCount","NumAvailable","PrepStmtCacheHitCount","ActiveConnectionsAverageCount","Name","PrepStmtCacheDeleteCount","FailuresToReconnectCount","WaitingForConnectionHighCount","PrepStmtCacheMissCount","CurrCapacity"]
  tag_keys = ["Name","ServerRuntime"]

     [[inputs.jolokia2_agent.metric]]
    name = "Memory"
    mbean  = "java.lang:type=Memory"
    paths  = ["HeapMemoryUsage/max","HeapMemoryUsage/used","NonHeapMemoryUsage/max","NonHeapMemoryUsage/used"]

    [[inputs.jolokia2_agent.metric]]
    name = "MemoryPool"
    mbean  = "java.lang:name=*,type=MemoryPool"
    paths  = ["Usage", "PeakUsage", "CollectionUsage"]
    tag_keys = ["name"]

    [[inputs.jolokia2_agent.metric]]
    name = "WorkManagerRuntime"
    mbean  = "com.bea:Name=*,ServerRuntime=*,Type=WorkManagerRuntime"
    paths  = ["CompletedRequests","PendingRequests","HealthState","StuckThreadCount"]
    tag_keys = ["Name","ServerRuntime"]

[[inputs.jolokia.metric]]
    name = "UserLockoutManagerRuntime"
    mbean  = "com.bea:Name=UserLockoutManager,RealmRuntime=*,ServerRuntime=*,ServerSecurityRuntime=*,Type=UserLockoutManagerRuntime"
    paths  = ["LockedUsersCurrentCount","UserLockoutTotalCount","InvalidLoginAttemptsTotalCount","LoginAttemptsWhileLockedTotalCount","InvalidLoginUsersHighCount","UnlockedUsersTotalCount"]
    tag_keys = ["Name","ServerRuntime","RealmRuntime"]

   [[inputs.jolokia2_agent.metric]]
  name     = "jvm_garbage_collector"
  mbean    = "java.lang:name=*,type=GarbageCollector"
  paths    = ["CollectionTime", "CollectionCount"]
  tag_keys = ["name"]

    [[inputs.jolokia2_agent.metric]]
    name = "WebAppComponentRuntime"
    mbean  = "com.bea:ApplicationRuntime=*,Name=*,ServerRuntime=*,Type=WebAppComponentRuntime"
    paths  = ["OpenSessionsCurrentCount","Status","SessionsOpenedTotalCount","OpenSessionsHighCount","ComponentName"]
    tag_keys = ["Name","ServerRuntime","ComponentName","ApplicationRuntime"]

  [[inputs.jolokia2_agent.metric]]
    name = "OperatingSystem"
    mbean  = "java.lang:type=OperatingSystem"
    paths  = ["CommittedVirtualMemorySize","FreePhysicalMemorySize","FreeSwapSpaceSize","TotalPhysicalMemorySize","TotalSwapSpaceSize","OpenFileDescriptorCount","SystemLoadAverage","ProcessCpuLoad","MaxFileDescriptorCount","SystemCpuLoad"]

  [[inputs.jolokia2_agent.metric]]
    name = "Thread_count1"
    mbean  = "com.bea:ServerRuntime=*,Name=ThreadPoolRuntime,Type=ThreadPoolRuntime"
    paths  = ["PendingUserRequestCount","CompletedRequestCount","HoggingThreadCount","StandbyThreadCount","Throughput","ExecuteThreadTotalCount","PendingUserRequestCount"]
    tag_keys = ["ServerRuntime"]

  [[inputs.jolokia2_agent.metric]]
    name = "JVMRUNtime1"
    mbean  = "com.bea:ServerRuntime=*,Name=*,Type=JVMRuntime"
    paths  = ["HeapFreePercent","HeapFreeCurrent","Name","HeapSizeMax","HeapSizeCurrent"]
    tag_keys = ["ServerRuntime"]

  [[inputs.jolokia2_agent.metric]]
    name = "SocketInfo"
    mbean  = "com.bea:Name=*,Type=ServerRuntime"
    paths  = ["SocketsOpenedTotalCount","OpenSocketsCurrentCount","OverallHealthStateJMX","State","ServerStartupTime"]
    tag_keys = ["Name"]

  [[inputs.jolokia2_agent.metric]]
    name = "JTARuntime1"
    mbean  = "com.bea:ServerRuntime=*,Name=JTARuntime,Type=JTARuntime"
    paths  = ["ActiveTransactionsTotalCount","TransactionCommittedTotalCount","TransactionRolledBackSystemTotalCount","TransactionTotalCount","TransactionHeuristicsTotalCount","SecondsActiveTotalCount"]
    tag_keys = ["ServerRuntime"]

**Comment by danielnelson** [comment]
This doesn't necessarily look like a bug, try to reduce the config plugin to the smallest example that can reproduce the problem and ask over at the [InfluxData Community](https://community.influxdata.com) site for help.
