### ISSUE TITLE
pull metrics for physical cpu but not cores

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#5949]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:
percpu returns cores as reported by OS

### Desired behavior:
only pull metrics for physical cpus  (ie for a box with 48 cores and 4 cpus, i would like to only get 5 metrics (4 physical + total)

**Comment by danielnelson** [comment]
Perhaps we can add a tag with the physical cpu id, then you could either group at query time or with an aggregator.

**Comment by danielnelson** [comment]
related https://github.com/influxdata/telegraf/issues/4256
