### ISSUE TITLE
telegraf should be able to report its version

### ISSUE THREAD

**Issue by nisley** [influxdata/telegraf#5958]
## Feature Request

As an operator, I should be able to check InfluxDB (or the backend datastore) to query/understand how many of each version of telegraf agents are reporting in.

### Use case: 
If I have 4,000 telegraf agents on 1.X and I'm performing an upgrade to 1.Y, I would like to ask/use InfluxDB to understand if all 4,000 agents are running 1.Y.  If they are not all 1.Y, how many and which are still 1.X.

**Comment by poulhs** [comment]
It could be achieved with a tag, that is "hard-coded" in the configuration (that would obviously be a tag, and that feels wrong - it would depend on the configuration that may not be changed when upgrading the telegraf). One could also implement it with an exec plugin, parsing the output from telegraf --version... _argh..._

This would fit nicely in the [[inputs.internal]] ?

**Comment by danielnelson** [comment]
Yeah, I'm thinking we add it as a tag to the `internal_agent` measurement:
```
internal_agent,host=example.org,version=1.10.4 gather_errors=0i,metrics_dropped=0i,metrics_gathered=1i,metrics_written=0i 1559775442000000000
```

Probably the best way to get this info today for most is by looking at the User-Agent header from the InfluxDB output.

**Comment by Esity** [comment]
@danielnelson Can we add a flag for this one inside the config?

```
[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  # collect_memstats = true
  ## If true, collect telegraf version number as a tag
  # collect_version = true
```

**Comment by poulhs** [comment]
It would be preferred to have the version as a fieldvalue, that way one can compare...
(so tag would be sufficient if it is possible to do "SELECT host,version WHERE version < "7.9.13" to get a report of all versions before a given version)

**Comment by Esity** [comment]
Are you trying to report on this? If so, get a CMDB tool to do that. If you want to show internal metrics for telegraf and group by the version, then the tag makes perfect sense

**Comment by danielnelson** [comment]
> Can we add a flag for this one inside the config? 

I wasn't thinking to add a flag, usually I only add one if it will reduce the collection time significantly.  If you want to exclude it then you could just use `tagexclude`.

> version < "7.9.13"

This would be nice, especially if it could handle semantic versions correctly.  I don't think we can even do lexical string comparisons with InfluxQL, but you can use a regular expression with a tag:
```
select * from internal_agent where version =~ /^7\..*/
```

**Comment by poulhs** [comment]
Afaik, the (so called) "regular expression"  do expand the expression to a list of possible combinations and is de facto a version = 7.0 OR version = 7.0.1  OR and so forth.

And one have to select fieldvalues, but I don't need any of the other fieldvalues to determine which versions are out their (if version is a tag, one can't do "SELECT version FROM internal_agent")

And yes, we do use CMDB that tells us the most, but there are still too many corner cases...

But now the developers has got my input, and I don't feel like starting a flame war here, so I let them decide and will be happy with a tag if that is what they think is best.

happy denugging ;-)

**Comment by nicgrobler** [comment]
I wrote a plug-in that simply exports the version to an ENV on startup...then sends influx this info as a tag...only on startup (not per collection interval). This way you can see when the agent was started, and it’s version.
never bothered submitting a PR as didn’t think anyone else needed this...

Also wasn’t sure that my ‘solution’ was acceptable.

If you think it is worth it, I can open a PR for this?

**Comment by danielnelson** [comment]
@nicgrobler Sure, would be helpful to take a look at.  I do think if we go the route of having Telegraf report state change events we should probably add a few more events like reload and shutdown and possible some addition information.  We should probably think a bit more about what that might look like.

**Comment by CHANDU677493** [comment]
Hi Nisely and all,

How can I get the telegraf version Number from our existing domain servers where telegraf already installed..? can you please provide a quick solution here.

**Comment by poulhs** [comment]
Some configuration like this:
```
[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  collect_memstats = true
  interval = "120s"
```
or `telegraf --version`
should do the trick.
I think the configuration is supoorted from `telegraf >= 1.12`

**Comment by CHANDU677493** [comment]
Can I have the perfect configuration file to get the telegraf version ?

**Comment by poulhs** [comment]
> Can I have the perfect configuration file to get the telegraf version ?

Well, your _perfect_ may differ from my _perfect_ (mine may even differ between the servers I configure...)
But iin my _perfect_ world, we use:  `/etc/telegraf/telegraf.d/inputs_internal.cfg` which telegraf includes:
```[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  collect_memstats = true
  interval = "120s"
```

**Comment by CHANDU677493** [comment]
Thanks, please don’t mine…I am new to this telegraf

can you please explain the process and where to change the config file to hard code and get the versions list..?

How to modify the below configuration file w.r.to the telegraf version ?


## If true, collect telegraf memory stats.

  collect_memstats = true

  interval = "120s"

Also, please let me know if there is any easy way to get the telegraf version list for entire domain.

**Comment by poulhs** [comment]
https://docs.influxdata.com/telegraf/v1.16/ to get a better understanding of telegraf
and https://docs.influxdata.com/telegraf/v1.16/administration/configuration/ to understand how to configure telegraf...

**Comment by CHANDU677493** [comment]
I have these docs, But, I need to understand that what configuration needs to change to get the telegraf version list..?
what command (configuration file to hard code) needs to use ?

**Comment by poulhs** [comment]
OK, then you can tell me where you have your telegraf configuration from your existing domain servers where telegraf is already installed.

Or just login to all the servers and issue `telegraf --version`

**Comment by poulhs** [comment]
To enable the input plugin `internal`
find the lines ```# # Collect statistics about itself
# [[inputs.internal]]
#   ## If true, collect telegraf memory stats.
#   # collect_memstats = true
```
and change them to:
```# # Collect statistics about itself
[[inputs.internal]]
#   ## If true, collect telegraf memory stats.
#   # collect_memstats = true
```
yes, that was "remove the `# ` comment"
and restart telegraf

**Comment by CHANDU677493** [comment]
Hi

I am receiving the below error while running telegraf --version

[cid:image001.png@01D6D591.19B69A60]


Also, is the below for memory stats or to get an version.?


[[inputs.internal]]

#   ## If true, collect telegraf memory stats.

#   # collect_memstats = true
yes, that was "remove the # comment"

**Comment by poulhs** [comment]
You failed to post an image, so I don't even know your operating system (although it sounds like a non-unix like variant).
I am not trying to be rude, so please don't be offended by the next questions, it is the kind of questions I got asked in the past and still ask myself whenever I come around similar problems:
I tried to guide you as far as I can - Do you know where the configuration files are located on your systems? Do you know if they are controlled by any kind of configuration management tools? Have your read any of the documentation on telegraf configuration? I suggest that you try _influxdb community_  on slack - there is a good _telegraf_ channel.

To get the telegraf version, just supply the  `version` option on the `telegraf` command in a text-based shell.
You may also gather the version (and other stuff) as metrics (passed on to your influxdb (or whatever your are using)) by enabling the `inputs.internal` in the usual way (similar to how you would do any configuration changes to telegraf).
