### ISSUE TITLE
Telegraf executable size when building private

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#5961]
deb package.
When i install from official package, i see the telegraf executable around ~60M in file size. When i build/make myself i see it almost double ~110M. How do i build with a smaller size? optimiaztions enabled ? Can someone tell me how ?

**Comment by danielnelson** [comment]
Add `-w -s` to the ldflags which strip some debugging information:
```diff
- go build -ldflags " -X main.commit=f22e7a14 -X main.branch=master" ./cmd/telegraf
+ go build -ldflags "-w -s -X main.commit=f22e7a14 -X main.branch=master" ./cmd/telegraf
```

BTW, If you want even smaller, you can comment out unused plugins in the all.go files:
- /plugins/inputs/all/all.go 
- /plugins/outputs/all/all.go

**Comment by vishiy** [comment]
thank you @danielnelson
