### ISSUE TITLE
tagdrop on prometheus input doesn't work if statsd input with data dog tags support is also used

### ISSUE THREAD

**Issue by raffraffraff** [influxdata/telegraf#5962]
### Relevant telegraf.conf:
```
[agent]
  interval = "30s"
  flush_interval = "30s"
  debug = true
  logfile = "/var/log/telegraf/telegraf.log"

[[outputs.prometheus_client]]
  expiration_interval = "60s"
  listen = ":9000"
  path = "/v1/metrics"
  string_as_label = false

[[inputs.prometheus]]
  urls = ["http://localhost:9090/prometheus"]
  [inputs.prometheus.tagdrop]
    uri = ["/metrics"]

[[inputs.statsd]]
  metric_separator = "_"
  parse_data_dog_tags = true
  service_address = ":8125"
```

### System info:
CentOS 7, Kernel 3.10.0-957
Telegraf 1.10.4 (git: HEAD 3548ce47)

### Steps to reproduce:
1. Expose Prometheus metrics endpoint port localhost port 9090
2. Configure Telegraf as above, with a valid tagdrop configuration
3. Start telegraf and wait for it to scrape the Prometheus endpoint
4. Curl the Telegraf prometheus endpoint on port 9000 and grep for the dropped tag
`curl -s http://localhost:9000/v1/metrics | grep ^http | grep "[PATTERN]"`

### Expected behavior:
Metrics with the tags specified in the tagdrop configuration should be dropped.
### Actual behavior:
Metrics with the specified tags are not dropped when the statsd input is also enabled. They are only dropped if the statsd input is taken out of the telegraf configuration file.

### Additional info:
Telegraf Logs:
```
2019-06-06T13:46:49Z I! Loaded processors: 
2019-06-06T13:46:49Z I! Loaded outputs: prometheus_client
2019-06-06T13:46:49Z I! Tags enabled: host=testhost
2019-06-06T13:46:49Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"testhost", Flush Interval:30s
2019-06-06T13:46:49Z D! [agent] Connecting outputs
2019-06-06T13:46:49Z D! [agent] Attempting connection to output: prometheus_client
2019-06-06T13:46:49Z D! [agent] Successfully connected to output: prometheus_client
2019-06-06T13:46:49Z D! [agent] Starting service inputs
2019-06-06T13:46:49Z I! Statsd UDP listener listening on:  [::]:8125
2019-06-06T13:46:49Z I! Started the statsd service on :8125
2019-06-06T13:47:30Z D! [outputs.prometheus_client] wrote batch of 488 metrics in 8.935594ms
2019-06-06T13:47:30Z D! [outputs.prometheus_client] buffer fullness: 344 / 10000 metrics. 
```

**Comment by raffraffraff** [comment]
OK, so I've narrowed it down to this part of the statsd input plugin configuration: `parse_data_dog_tags = true`

**Comment by raffraffraff** [comment]
No. Way.
```
## deprecated in 1.10; use datadog_extensions option instead
--
```

That didn't even show up in the debug logs. I stumbled upon it in the code. I'm gonna test this out to see if it fixes the issue.

**Comment by raffraffraff** [comment]
Unlikely. For a start, the code clearly enables datadog_extensions if you enable `parse_data_dog_tags`. But switching to datadog_extensions cause it to fail on startup
```
2019-06-06T15:27:51Z I! Starting Telegraf 1.10.4
2019-06-06T15:27:51Z E! Could not parse tags for input cpu
2019-06-06T15:27:51Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 85: field corresponding to `datadog_extensions' is not defined in `*statsd.Statsd'
```

**Comment by raffraffraff** [comment]
I've just tested this with Telegraf 1.9.5, and `parse_data_dog_tags = true` affects the ability to use tagdrop.

**Comment by raffraffraff** [comment]
I just tried dropping metrics in another input, to see if this affected all inputs. It does not:
```
[[inputs.diskio]]
  skip_serial_number = true
  [inputs.diskio.tagdrop]
  name = ["vda1","vda2","vda3"]
```
This continued to work with `parse_data_dog_tags = true` while prometheus input tagdrop failed to work.

**Comment by danielnelson** [comment]
> ## deprecated in 1.10; use datadog_extensions option instead

This should actually read "deprecated in 1.11" and this is why you can't set the new option yet.  Don't worry though the old option still works.  I'll take care of this.

This bug is very strange, I'm not sure how it could occur.  Could you paste an example of a metric from the prometheus input that should be filtered but is not?

**Comment by raffraffraff** [comment]
Well, there were _lots of them_ but the general format was:
```
http_server_requests_count{applicationId="mobile",dc="beta",host="webserver4",method="GET",metric_type="timing",outcome="SUCCESS",status="200",uri="/metrics"} 1
```

**Comment by danielnelson** [comment]
I'm not able to reproduce this, here is what I did:

Setup a fake prometheus endpoint with the metric:
```
$ http localhost:9090/prometheus
HTTP/1.1 200 OK
Content-Length: 165
Content-Type: text/plain; charset=utf-8
Date: Thu, 06 Jun 2019 19:20:04 GMT
Server: Python/3.6 aiohttp/2.2.5

http_server_requests_count{applicationId="mobile",dc="beta",host="webserver4",method="GET",metric_type="timing",outcome="SUCCESS",status="200",uri="/metrics"} 1
```

With the config above:
```
$ curl -s localhost:9000/v1/metrics | grep ^http
```

If I remove the tagdrop from the config I get:
```
$ curl -s localhost:9000/v1/metrics | grep ^http
http_server_requests_count{applicationId="mobile",dc="beta",host="webserver4",method="GET",metric_type="timing",outcome="SUCCESS",status="200",uri="/metrics",url="http://localhost:9999/prometheus"} 1
```

I'm not sending any data on the statsd plugin, but it is running.

**Comment by raffraffraff** [comment]
Not sure if it made any difference that there was data coming to the statsd input. I'll see if I can reproduce on another host that isn't receiving statsd metrics.

**Comment by raffraffraff** [comment]
OK, so the issue only appears when Telegraf is actually receiving statsd metrics. I just recreated it quite simply. This gist demonstrates it:

https://gist.github.com/raffraffraff/af9c6bf09899ffe58a914313e5375bd2#file-telegraf_prometheus_dog_statsd_bug-sh

**Comment by danielnelson** [comment]
Here is the output when I run the script, but it looks correct to me.

I'm expecting the statsd items with `interface=all` to be emitted because only the prometheus input has the tagdrop, and all the `interface=all` from the prometheus input are not present.

```
net_bytes_recv{dc="alpha",host="server1",interface="docker0",url="http://localhost:9090/metrics"} 1.26742965e+08
net_bytes_recv{dc="alpha",host="server1",interface="eth0",url="http://localhost:9090/metrics"} 8.40904966256
net_bytes_sent{dc="alpha",host="server1",interface="docker0",url="http://localhost:9090/metrics"} 5.7160501e+07
net_bytes_sent{dc="alpha",host="server1",interface="eth0",url="http://localhost:9090/metrics"} 3.46307013621e+11
net_drop_in{dc="alpha",host="server1",interface="eth0",url="http://localhost:9090/metrics"} 5
statsd_net_bytes_recv{dc="alpha",host="server1",interface="docker0",metric_type="gauge"} 1.26742965e+08
statsd_net_bytes_recv{dc="alpha",host="server1",interface="eth0",metric_type="gauge"} 8.40904966256
statsd_net_bytes_sent{dc="alpha",host="server1",interface="docker0",metric_type="gauge"} 5.7160501e+07
statsd_net_bytes_sent{dc="alpha",host="server1",interface="eth0",metric_type="gauge"} 3.46307013621e+11
statsd_net_drop_in{dc="alpha",host="server1",interface="eth0",metric_type="gauge"} 5
statsd_net_icmp_inaddrmasks{dc="alpha",host="server1",interface="all",metric_type="gauge"} 48
statsd_net_icmp_indestunreachs{dc="alpha",host="server1",interface="all",metric_type="gauge"} 203406
statsd_net_icmp_inechoreps{dc="alpha",host="server1",interface="all",metric_type="gauge"} 690894
statsd_net_icmp_inechos{dc="alpha",host="server1",interface="all",metric_type="gauge"} 43144
statsd_net_icmp_inerrors{dc="alpha",host="server1",interface="all",metric_type="gauge"} 14187
statsd_net_icmp_inmsgs{dc="alpha",host="server1",interface="all",metric_type="gauge"} 1.770706e+06
statsd_net_icmp_intimeexcds{dc="alpha",host="server1",interface="all",metric_type="gauge"} 833117
statsd_net_icmp_intimestampreps{dc="alpha",host="server1",interface="all",metric_type="gauge"} 1
statsd_net_icmp_intimestamps{dc="alpha",host="server1",interface="all",metric_type="gauge"} 96
```

**Comment by raffraffraff** [comment]
That does muddy the water a bit, I'll eliminate those from the statsd input.

**Comment by raffraffraff** [comment]
So I *was* stupidly missing the statsd_ prefix on my test and posted without being thorough. But what is super frustrating is that I just went back to the failing example that our developer brought to me originally (to see if they were duplicating their prometheus metrics into statsd) ...it's _working_ now. It's definitely the same telegraf config, and I can directly curl the prometheus metrics and see that they're the same. The only thing I don't know is whether or not they've changed their statsd metrics. I'll dig further, but either way, I'm closing this issue.
