### ISSUE TITLE
inputs.win_services Error Handling for services that do not exist

### ISSUE THREAD

**Issue by sheldonhull** [influxdata/telegraf#5964]
### Relevant telegraf.conf:

```toml
[[inputs.win_services]]
  interval = "60s"
  ## Names of the services to monitor. Leave empty to monitor all the available services on the host
  service_names = [
    "MSSQLSERVER",
    "ReportServer",
    "SQLSERVERAGENT",
    "sumologic",
    "codedeployagent",
    "AmazonSSMAgent",
    "telegraf",
    "com.docker.service"
]
```

### System info:

- Telegraf 1.10
- Windows 10 x64

### Steps to reproduce:

1. Start telegraf with win_services being configured for various services to monitor.
2. Error is thrown with entry each time the interval is populated with the following result: `2019-06-05T21:51:00Z E! [inputs.win_services]: Error in plugin: could not open service: 'ReportServer': The specified service does not exist as an installed service.`

### Expected behavior:

If the service doesn't exist, I'd expect it to flag the issue on the first stdout as not existing and then refrain from logging as error each time. 

### Actual behavior:
Every single iteration, currently set to `60s` outputs errors for service's that don't exist. 

### Additional info:
If an installation happens then of course periodically checking for the new service existing makes sense, however as it stands, the current check constantly throws errors. I'd expect it to less verbose in it being an error, so that I can deploy the same configuration to a variety of machines and report back on the services that might actually exist there.

**Comment by glinton** [comment]
This could be a relatively quick fix if somebody wants to pick it up. With the new `Init()` function that got put in in #5899. I suspect one could loop through the list and drop any that don't exist.

Whether or not that is the desired behavior is another question though as automagic isn't always friendly. I don't believe the original ask was for telegraf to error and fail to start if a service couldn't be found either.

**Comment by danielnelson** [comment]
I agree this could be confusing, imagine the case where you type the name of the service wrong, and instead of a warning the plugin just doesn't collect anything.  I would be okay with a one time logging of the error, but would do it in the Gather function as Init() isn't meant only for config file checks.  In the more distant future when we have per plugin log levels it could be handled this way as well.

In general, we don't aim for having a single telegraf.conf work across all systems.  It may be helpful to use the `--config-directory` option and a multiple file config to manage multiple plugin configurations.

**Comment by sheldonhull** [comment]
I'm doing the config directory. However list of services should minimize errors for each loop if service in list doesn't exist. That's what I was primarily focused on.

**Comment by R-Studio** [comment]
Any news on this?
Log once or a setting to define an erroraction in the config of the input plugin "win_services" would be perfect.

examples of erroractions/loglevel:
- ignore services that does not exists
- write a warning
- write an error

**Comment by sjwang90** [comment]
If anyone is interested in taking over PR #6166 that addresses this issue

**Comment by sjwang90** [comment]
Closed PR #6166 due to inactivity. If this is still something someone wants to pick up please feel free to do so.

**Comment by rehanpfmr** [comment]
Can this be assigned to me?

**Comment by powersj** [comment]
> Can this be assigned to me?

Sure

**Comment by srebhan** [comment]
@rehanpfmr any update on the matter? @sheldonhull does this issue still exist with the latest version of Telegraf?
