### ISSUE TITLE
Extend the vSphere plugin for vSAN.

### ISSUE THREAD

**Issue by YuxinZhou** [influxdata/telegraf#5966]
### Proposal:

VMware vSAN is a software-defined storage solution which aggregates local or direct-attached data storage devices to create a single storage pool shared across all hosts in the vSAN cluster. vSAN is a distributed layer of software included in the ESXi hypervisor, and it is fully integrated with VMware vSphere.

I would like to extend the vSphere plugin for vSAN, so that vSAN users could be able to collect performance data, configuration metrics and some, similar to what vSphere plugin collects. This would be hugely helpful for whoever want to track, virtualize, or analyze vSAN metrics.

### Current behavior:

Nothing like this is currently written or available

### Desired behavior:

Should be able to collect vSAN data.
Metrics to collect should be configurable.

### Use case: 
By collecting and sending metrics to virtualizing tools, e.g., Wavefront, Grafana, Chronograf  (We are currently creating dashboards for theses platforms), it would be a big help for the following tasks: 
- Detect vSAN health and performance issue 
- Understand of current vSAN capacity, recync status, etc

**Comment by bogski87** [comment]
Have you tried this one?
[VSAN Metrics](https://github.com/equelin/vsanmetrics)

Run it using the exec plugin. Works great - Although expanding the Telegraf plugin to get this data anyway would be cool. The above VSAN one works

**Comment by YuxinZhou** [comment]
@bogski87 Thank you for sharing this. Looks cool!

**Comment by iammathh** [comment]
Hello folks, 

In case you're still looking for a telegraf plugin for vSAN [Telegraf vSAN - Pre release - from wavefrontHQ](https://github.com/wavefrontHQ/telegraf/releases/tag/VSAN-PRE1)
