### ISSUE TITLE
Getting timeouts when exporting metrics to prometheus

### ISSUE THREAD

**Issue by vibhavachar** [influxdata/telegraf#5973]
root@mesos-master2:/etc/telegraf/telegraf.d# /usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
2019-06-10T07:00:32Z I! Starting Telegraf 1.10.4
2019-06-10T07:00:32Z I! Loaded inputs: mesos mesos
2019-06-10T07:00:32Z I! Loaded aggregators: 
2019-06-10T07:00:32Z I! Loaded processors: 
2019-06-10T07:00:32Z I! Loaded outputs: prometheus_client
2019-06-10T07:00:32Z I! Tags enabled: host=mesos-master2.stage-ola-azure.az.olacabs.net
2019-06-10T07:00:32Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"mesos-master2.stage-ola-azure.az.olacabs.net", Flush Interval:5m0s
2019-06-10T07:00:32Z E! [agent] Failed to connect to output prometheus_client, retrying in 15s, error was 'listen tcp :9273: bind: address already in use' 
^C2019-06-10T07:00:37Z E! [telegraf] Error running agent: context canceled
root@mesos-master2:/etc/telegraf/telegraf.d# tail -f /var/log/syslog | grep telegraf
Jun 10 07:00:44 mesos-master2 telegraf[108348]: 2019-06-10T07:00:44Z E! [inputs.mesos]: Error in plugin: Get http://x.x.x.x:5050/metrics/snapshot?timeout=10000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jun 10 07:00:44 mesos-master2 telegraf[108348]: 2019-06-10T07:00:44Z E! [inputs.mesos]: Error in plugin: Get http://localhost:5050/metrics/snapshot?timeout=5000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jun 10 07:00:54 mesos-master2 telegraf[108348]: 2019-06-10T07:00:54Z E! [inputs.mesos]: Error in plugin: Get http://localhost:5050/metrics/snapshot?timeout=5000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jun 10 07:00:54 mesos-master2 telegraf[108348]: 2019-06-10T07:00:54Z E! [inputs.mesos]: Error in plugin: Get http://x.x.x.x:5050/metrics/snapshot?timeout=10000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

[agent]
debug = false
flush_interval = "300s"
flush_jitter = "5s"
interval = "10s"
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
quiet = false
round_interval = true
[tags]

[[inputs.mesos]]
  ## Timeout, in ms.
  timeout = 10000
  ## A list of Mesos masters.
  masters = ["http://10.209.0.15:5050"]
  ## Master metrics groups to be collected, by default, all enabled.
  master_collections = [
    "resources",
    "master",
    "system",
    "agents",
    "frameworks",
    "framework_offers",
    "tasks",
    "messages",
    "evqueue",
    "registrar",
    "allocator",
  ]

[outputs.prometheus_client]
expiration_interval = "60s"
listen = ":9273"
string_as_label = true
path = "/metrics"

root@mesos-master2:/etc/telegraf/telegraf.d# telegraf --version
Telegraf 1.10.4 (git: HEAD 3548ce47)

Any help?

**Comment by danielnelson** [comment]
You won't be able to run Telegraf in the foreground unless you stop the background daemon, this is why you are receiving this error when running:
```
2019-06-10T07:00:32Z E! [agent] Failed to connect to output prometheus_client, retrying in 15s, error was 'listen tcp :9273: bind: address already in use'
```

These errors indicates that Telegraf did not receive a response from the mesos server, not even a port closed error.  This could be caused by many things, possibly a firewall, you will need to debug it on your end.  Make sure the system running Telegraf can connect to `http://x.x.x.x:5050/metrics/snapshot?timeout=10000ms`.
```
Jun 10 07:00:44 mesos-master2 telegraf[108348]: 2019-06-10T07:00:44Z E! [inputs.mesos]: Error in plugin: Get http://x.x.x.x:5050/metrics/snapshot?timeout=10000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
