### ISSUE TITLE
Failed to find Premain-Class manifest attribute in /tools/jolokia/jolokia.war | weblogic 12c

### ISSUE THREAD

**Issue by Veenumittal** [influxdata/telegraf#5974]
I am using jolokia.war and jolokia2_agent to get the weblogic metrices but upon restarting the domain, I am getting below error:

blogic1221/wlserver_12.2.1/installation/wlserver/server/native/linux/x86_64 -javaagent:/XPISTORAGEMPS/HPD/JavaAgent/DiagnosticsAgent/lib/probeagent.jar -Dprobe.id=Server_0_1 -Dprobe.group
=PROD -XX:+UnlockDiagnosticVMOptions -XX:+UnsyncloadClass -javaagent:/tools/jolokia/jolokia.war weblogic.Server >
<Jun 5, 2019 1:29:39 PM IST> <INFO> <NodeManager> <Working directory is '/users/Product/WLS/Domain'>
<Jun 5, 2019 1:29:39 PM IST> <INFO> <NodeManager> <Server output log file is '/users/Product/WLS/Domain/servers/Server_0_1/logs/Server_0_1.out'>
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=484m; support was removed in 8.0
Failed to find Premain-Class manifest attribute in /tools/jolokia/jolokia.war

**Comment by danielnelson** [comment]
This doesn't look like a Telegraf issue, can you open it with the Jolokia team?

**Comment by Veenumittal** [comment]
Please guide me, Where to open it with Jolokia team?

**Comment by danielnelson** [comment]
https://jolokia.org/support.html
