### ISSUE TITLE
unable to build 0.4.10.1 from source with go 1.12

### ISSUE THREAD

**Issue by williamh** [influxdata/telegraf#5977]
GDM is dying because it seems to have an issue importing one of the dependencies; this happens whether I run "gdm restore" or "gdm vendor".

[gdm.log](https://github.com/influxdata/telegraf/files/3278781/gdm.log)

**Comment by danielnelson** [comment]
Try making this change:
```diff
-git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git 17c801af238c3af2d9e72c5d4a0f02edad03ce5
+github.com/eclipse/paho.mqtt.golang 617c801af238c3af2d9e72c5d4a0f02edad03ce5
```

This version is ancient Telegraf history, time to upgrade!
