### ISSUE TITLE
Cannot set mount_points option in disk input

### ISSUE THREAD

**Issue by shr00mie** [influxdata/telegraf#5980]
### Relevant telegraf.conf:
```toml
[[inputs.disk]]
  mount_points = ["/"]
  fielddrop = [ "inodes*" ]
```

### System info:

Telegraf 1.11.0 (git: HEAD c9d8f7b0)
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
(same results on 18.04LTS as well.)

### Steps to reproduce:

1. got the same issue on all my ubuntu systems after the update. seems to be pertaining to the inputs.disk section. commenting out mount_points line and restarting the service seems to work.

### Expected behavior:
the service running normally as it had before.

### Actual behavior:
had to comment out mount_points on all ubuntu telegraf.conf configs and restart service.

### Additional info:

```
Jun 11 17:59:31 us1604 telegraf[1897]: 2019-06-12T00:59:31Z I! Starting Telegraf 1.11.0
Jun 11 17:59:31 us1604 telegraf[1897]: 2019-06-12T00:59:31Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 21: field corresponding to `mount_points' in disk.DiskStats cannot be set through TOML
Jun 11 17:59:31 us1604 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
```
on the bright side, now the grafana output looks like a modern art piece...
![image](https://user-images.githubusercontent.com/7096317/59316982-eb677900-8c75-11e9-9124-dcd5c179bb93.png)

**Comment by saintunix** [comment]
Agree, have the same error. It has started to work after removing the line.
  mount_points = ["/", "/vz", "/vz1" ]

**Comment by Ulrar** [comment]
We're having the same issue on all the servers that updated last night

**Comment by danielnelson** [comment]
Sorry all, must have been introduced when we updated the toml library.  Fix is easy though, we just need to add struct tags for these fields, will definitely make it in the next release.

**Comment by Ulrar** [comment]
Any idea on when that might be ? Just to know if we can wait for it or if we should plan to remove the field everywhere in the meantime somehow

**Comment by danielnelson** [comment]
Currently the plan is to release 1.11.1 on the 25th, depending on if other important bugs are found, in the meantime here are some builds of 1.11.0 including this patch:

- [telegraf-1.11.0~b1154378-0.x86_64.rpm](https://34562-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.11.0~b1154378-0.x86_64.rpm)
- [telegraf_1.11.0~b1154378-0_amd64.deb](https://34562-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.11.0~b1154378-0_amd64.deb)
- [telegraf-1.11.0~b1154378_windows_amd64.zip](https://34562-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.11.0~b1154378_windows_amd64.zip)

**Comment by Ulrar** [comment]
Alright those packages do work fine, that'll do in the meantime, thanks !

**Comment by GainfulShrimp** [comment]
In case it helps others (perhaps using armhf architecture like me, so they can't use the temporary packages posted by Daniel above), you can 'hold back' the old version of Telegraf so it won't get upgraded by a `sudo apt-get update && sudo apt-get upgrade`:
```
sudo apt-mark hold telegraf
```
You can then update the rest of your system without upgrading telegraf. :)

Once the new version (hopefully with working mount_points option) is released, you can use:
```
sudo apt-mark unhold telegraf
```
... after that, new telegraf releases will be considered when do a update & upgrade with aptitude, as usual.
