### ISSUE TITLE
[[inputs.ping]] 

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#5988]
HI,

I am monitoring few server through [[inputs.ping]] with all default configuration, by which I am getting multiple ping failed error.
To reduce it, i want to generate alert on 3 consecutive ping failed for a url. also want to increase poll interval. how to achieve this?
My current cofuguration:
telegraf version: telegraf-1.9.0-1.x86_64
telegraf configuration file:
[agent]
  interval = "120s"
[[outputs.influxdb]]
 urls = ["http://127.0.0.1:8086"]
 database = "telegraf"
[[inputs.ping]]
  ## List of urls to ping
  #urls = ["example.org"]
  urls = ["10.12.148.120",
"10.12.148.50",
"10.12.148.51",
"172.36.144.93"]
  ## Number of pings to send per collection (ping -c <COUNT>)
  # count = 1

  ## Interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
  ## Not available in Windows.
  # ping_interval = 1.0

  ## Per-ping timeout, in s. 0 == no timeout (ping -W <TIMEOUT>)
  # timeout = 1.0

  ## Total-ping deadline, in s. 0 == no deadline (ping -w <DEADLINE>)
  # deadline = 10

  ## Interface or source address to send ping from (ping -I <INTERFACE/SRC_ADDR>)
  ## on Darwin and Freebsd only source address possible: (ping -S <SRC_ADDR>)
  # interface = ""

  ## Specify the ping executable binary, default is "ping"
  # binary = "ping"

  ## Arguments for ping command
  ## when arguments is not empty, other options (ping_interval, timeout, etc) will be ignored
  # arguments = ["-c", "3"]

Regards,
Priyanka

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
