### ISSUE TITLE
Datadog plugin tags not working

### ISSUE THREAD

**Issue by wryun** [influxdata/telegraf#599]
https://github.com/influxdata/telegraf/commit/ec39d106951a7af09591b4a9f8abaa599e2666d5#diff-1be6997ca515c6fc8b54466206d89067

Seems to have removed tags support for datadog accidentally. Looks like an easy fix, but I don't want to set up a build environment to test :)

Also, when I push things through statsd I'm getting 'value' added to the end (e.g. push page.views, get page.viewsvalue). Not sure what's going on there; maybe related.

**Comment by sparrc** [comment]
@wryun can you open a separate case about the statsd plugin, and include your config and version?

**Comment by wryun** [comment]
Thanks for fast response! That commit changed omitempty to omitemmy... (search/replace).
