### ISSUE TITLE
Can't find Telegraf executable version on Windows

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#5994]
### Relevant telegraf.conf:

```toml
N/A
```

### System info:

Windows
### Steps to reproduce:

1. Download the latest version of Telegraf  ...
2. Open the properties/details pane to see the version ...

### Expected behavior:
Display the version number in "Product version"
### Actual behavior:
Version is blank

**Comment by danielnelson** [comment]
You can run `telegraf version`, closing since this is a duplicate of #3171
