### ISSUE TITLE
error scanning /var/spool/postfix/active: lstat /var/spool/postfix/active: permission denied

### ISSUE THREAD

**Issue by alpern95** [influxdata/telegraf#6002]
### Error
error scanning /var/spool/postfix/active: lstat /var/spool/postfix/active: permission denied

doing setfacl -Rdm g:telegraf:rX /var/spool/postfix/{active,hold,incoming,deferred,maildrop}

### Relevant telegraf.conf:
```
# # Measure postfix queue statistics
 [[inputs.postfix]]
#   ## Postfix queue directory. If not provided, telegraf will try to use
#   ## 'postconf -h queue_directory' to determine it.
    queue_directory = "/var/spool/postfix"
```toml

```

### System info:
```
[root@myserver ~]# telegraf version
Telegraf 1.11.0 (git: HEAD c9d8f7b0)

[root@myserver ~]# uname -a
Linux myserver.douane 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@myserver ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

[root@myserver ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

[root@myserver ~]# ls -lia /var/spool/postfix
total 4
      64 drwxr-x---. 16 postfix root      201  4 avril  2017 .
 6291527 drwxr-xr-x. 14 root    root      167 26 juin   2018 ..
25165952 drwxr-s---+  2 postfix telegraf   26 18 juin  08:35 active
      67 drwx------.  2 postfix root        6 18 juin  08:33 bounce
 8388736 drwx------.  2 postfix root        6 26 janv.  2014 corrupt
16797824 drwx------. 18 postfix root      150 12 nov.   2018 defer
25165953 drwxr-s---+ 18 postfix telegraf  150 12 nov.   2018 deferred
      68 drwx------.  2 postfix root       41 18 oct.   2018 flush
 8388737 drwxr-s---+  2 postfix telegraf    6 26 janv.  2014 hold
16797825 drwxr-s---+  2 postfix telegraf   26 18 juin  08:35 incoming
25165954 drwxrwx---+  2 postfix postdrop    6 18 juin  03:45 maildrop
      69 drwxr-xr-x.  2 postfix root      223 18 juin  03:44 pid
 8388738 drwx------.  2 postfix root     4096 18 juin  03:44 private
16797826 drwx--x---.  2 postfix postdrop   73 18 juin  03:44 public
25165955 drwx------.  2 postfix root        6 26 janv.  2014 saved
      71 drwx------.  2 postfix root        6 13 déc.   2018



### Additional info:

<!-- [Include gist of relevant config, logs, etc.] -->
```

**Comment by danielnelson** [comment]
Check `getfacl /var/spool/postfix/active` to make sure the posix acl's are set correctly.  After that, how are you launching telegraf?  I assume it is working when ran as root?

**Comment by alpern95** [comment]
Hello,
here is the getfacl, and yes it is working as root.

## getfacl
[root@myserver ~]# getfacl /var/spool/postfix/active
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/spool/postfix/active
# owner: postfix
# group: telegraf
# flags: -s-
user::rwx
group::rwx
other::rwx
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

2- telegraf is installed with a redhat rpm
[root@myserver ~]# systemctl status telegraf.service
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
   Active: active (running) since lun. 2019-06-17 16:21:32 CEST; 1 day 15h ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 46989 (telegraf)
   CGroup: /system.slice/telegraf.service
           └─46989 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

**Comment by danielnelson** [comment]
How about
```
sudo -u telegraf stat /var/spool/postfix/active
sudo -u telegraf stat /var/spool/postfix
```

**Comment by alpern95** [comment]
hello,

[root@myserver ~]# sudo -u telegraf stat /var/spool/postfix/active
stat: impossible d'évaluer « /var/spool/postfix/active »: Permission non accordée
[root@myserver ~]#
[root@myserver ~]#
[root@myserver ~]# sudo -u telegraf stat /var/spool/postfix
  Fichier : « /var/spool/postfix »
   Taille : 201         Blocs : 0          Blocs d'E/S : 4096   répertoire
Périphérique : fd02h/64770d     Inœud : 64          Liens : 16
Accès : (0750/drwxr-x---)  UID : (   89/ postfix)   GID : (    0/    root)
Contexte : system_u:object_r:unlabeled_t:s0
 Accès : 2019-06-20 08:11:30.849643931 +0200
Modif. : 2018-10-30 16:42:45.085908383 +0100
Changt : 2018-11-14 15:58:30.020083008 +0100
  Créé : -
[root@myserver ~]#

**Comment by danielnelson** [comment]
I think you need to run this, it is the original command without `-d`.  My understanding of this is that when you run with `-d` it sets the permissions as the default acl for the directory, which causes new child directories to have the acl, but it doesn't actually set the acl for the directory.
```
setfacl -Rm g:telegraf:rX /var/spool/postfix/{active,hold,incoming,deferred,maildrop}
```

**Comment by alpern95** [comment]
Hello
i do this but allway permission denied with telegraf user.
Information: I have a linux logical volume mount on /var/spool/postfix/  

###############
[root@myserver ~]# setfacl -Rm g:telegraf:rX /var/spool/postfix/{active,hold,incoming,deferred,maildrop}

[root@myserver ~]# sudo -u telegraf stat /var/spool/postfix/active
stat: impossible d'évaluer « /var/spool/postfix/active »: Permission non accordée

[root@myserver ~]# getfacl /var/spool/postfix/active
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/spool/postfix/active
# owner: postfix
# group: telegraf
# flags: -s-
user::rwx
group::rwx
group:telegraf:r-x
mask::rwx
other::rwx
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

[root@myserver ~]#

**Comment by danielnelson** [comment]
Can you try setting this ACL on the postfix directory too?
```
setfacl -Rm g:telegraf:rX /var/spool/postfix
```

**Comment by alpern95** [comment]
hello Daniel,
Thank for your help, i do the setfacl for the postfix directory, and it's working now.

see below, the getfcl for the directory postfix and the sub-directory active.

##################################
[root@myserver ~]# getfacl /var/spool/postfix
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/spool/postfix
# owner: postfix
# group: root
user::rwx
group::r-x
group:telegraf:r-x
mask::r-x
other::---

[root@myserver ~]# getfacl /var/spool/postfix/active/
getfacl : suppression du premier « / » des noms de chemins absolus
# file: var/spool/postfix/active/
# owner: postfix
# group: telegraf
# flags: -s-
user::rwx
group::r-x
group:telegraf:r-x
mask::r-x
other::---
default:user::rwx
default:group::r-x
default:group:telegraf:r-x
default:mask::r-x
default:other::---

**Comment by danielnelson** [comment]
Nice, I'll update the docs with this new information.

BTW, quick github markdown tip, you can use 4-space indent or triple backticks to do a code block:

    ```
    [root@myserver ~]# getfacl /var/spool/postfix
    ```

**Comment by danielnelson** [comment]
6738d566

**Comment by nomad-007** [comment]
I fixed by
sudo setfacl -m u:telegraf:rx /var/spool/postfix
sudo setfacl -m u:telegraf:rx /var/spool

**Comment by SupRavII** [comment]
[inputs.postfix] Error in plugin: error scanning /var/spool/postfix/deferred: open /var/spool/postfix/deferred/0: permission denied
[inputs.postfix] Error in plugin: error scanning /var/spool/postfix/deferred: open /var/spool/postfix/deferred/4: permission denied

**Set Good ACL:**

setfacl -Rm g:telegraf:rX /var/spool/postfix/{,active,hold,incoming,deferred,maildrop}

Control:

# file: var/spool/postfix/
# owner: root
# group: root
user::rwx
group::r-x
group:telegraf:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:telegraf:r-x
default:mask::r-x
default:other::r-x

# file: var/spool/postfix/active
# owner: postfix
# group: root
user::rwx
group::---
group:telegraf:r-x
mask::r-x
other::---
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

# file: var/spool/postfix/hold
# owner: postfix
# group: root
user::rwx
group::---
group:telegraf:r-x
mask::r-x
other::---
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

# file: var/spool/postfix/incoming
# owner: postfix
# group: root
user::rwx
group::---
group:telegraf:r-x
mask::r-x
other::---
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

# file: var/spool/postfix/deferred
# owner: postfix
# group: root
user::rwx
group::---
group:telegraf:r-x
mask::r-x
other::---
default:user::rwx
default:group::---
default:group:telegraf:r-x
default:mask::r-x
default:other::---

# file: var/spool/postfix/maildrop
# owner: postfix
# group: postdrop
# flags: --t
user::rwx
group::-wx
group:telegraf:r-x
mask::rwx
other::---
default:user::rwx
default:group::-wx
default:group:telegraf:r-x
default:mask::rwx
default:other::---
