### ISSUE TITLE
Ability to add some info in header which identifies type of input plugin when using http output plugin

### ISSUE THREAD

**Issue by adityask2** [influxdata/telegraf#6003]
## Feature Request

Ability to add some info in header which identifies type of input plugin when using http output plugin. For ex when using cpu input plugin, we can send the metric with header plugin=cpu

### Current behavior:
Current behavior of telegraf doesn't support different headers for different plugins. May be this is due to all the metrics are sent in one single http message. However, if the user wants multiple message (1 message per plugin), we can have it. 
### Desired behavior:
Have one message per plugin having plugin type info in header. 

### Use case: 
it would definitely help at the server which is parsing the message at high load from endpoints.

**Comment by danielnelson** [comment]
I don't think we would do this, because as you note, the output is often mixed and conceptually the outputs are disjoint from the inputs.  The best way to handle this is to have the server receiving the metrics check their measurement, which is generally based on the plugin.

**Comment by adityask2** [comment]
I would like to know why there is difference in behaviour in case of mqtt plugin where each plugin send data in different topic.

**Comment by danielnelson** [comment]
If you can explain the full setup in more detail I might be able to help.  You could also try using tags to track plugin source:
```
[[inputs.cpu]]
  # all the normal settings first
  [inputs.cpu.tags]
    plugin = "cpu"
```
