### ISSUE TITLE
old linux server [Red Hat Enterprise Linux ES release 4 (Nahant Update 9)] monitoring 

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6009]
can you please provide a solution to monitor Linux server of version: **"Red Hat Enterprise Linux ES release 4 (Nahant Update 9)"**

**Comment by danielnelson** [comment]
You can try compiling Telegraf with an older Go version.  I know you must compile with no later than 1.9 in order for the binary to work on RHEL5, but never tried with RHEL4.  Here are instructions on how to do this but it is not something we are going to provide officially.

https://github.com/influxdata/telegraf/wiki/Packaging#package-using-docker
