### ISSUE TITLE
win_disk :: getting HardDiskVolume## value

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6010]
HI,
I am using telegraf agent to monitor windows server.
telegraf version:  1.9.0
windows version: windows2012
telegraf is showing HadrDiskVolume## data, which is actually not any drive on a device.
for example, it is collecting data named HardDiskVolume100 for some time, after that there is no value for that drive.
and sometimes disk utilization of this HardDiskVolume goes into negative value.

can you please confirm, from where telegraf is collecting HardDiskVolume data?

**Comment by danielnelson** [comment]
In the default Windows config file, the win_disk measurement is based on the information provided by the Windows [performance counters](https://docs.microsoft.com/en-us/windows/desktop/perfctrs/performance-counters-portal).

A good way to investigate the performance counters is with the typeperf command:
```
typeperf "LogicalDisk(*)"
```

You can also use the `perfmon` GUI, both of these commands come packaged with Windows.
