### ISSUE TITLE
Telegraf - how to ignore config error(s)

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#6014]
We are using telegraf to collect a few prometheus metrics out of the box. Now we want to extend the configurability of telegraf to our customers, so that they can bring-in their own scrape endpoints & services (as part of prometheus input plugin).
How do we do config isolation in this case, so that the customer's config does not bring down telegraf instance we are running for collecting a few other prom metrics by default.

1) I understand i can run multiple instances of prom input plugin (one for us, and one for our customer's custom config). If i do it, how do i seperate config. I see i can use multiple config files, but i rewally need to restrict them to provide only config relevant to prom input plugin.
2) If customers provide invalid config, i would like to just ignore just that input plugin and continue to run the other plugins. Is that an option for the agent that is configurable ?
3) Instead of seperate config files, can i embed a file reference in TOML to point to another file?

ex:- something like below.
[[inputs.prometheus]]
   @/opt/customers_prom_input_config_filoe.conf

Looking for guidances as i want to stay away from running multiple instances of telegraf in the same node for different configurations for the purposes of config isolation isolation, as we are running in a container and very resource sensitive to run another instance of telegraf.

**Comment by danielnelson** [comment]
I suggest not allowing access to the `/etc/telegraf/telegraf.d` directory directly, and requiring the configuration to be added by running a small custom program that does some config verification first.

These sort of questions would be best asked at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by vishiy** [comment]
Thanks. Let me post it there.

**Comment by vishiy** [comment]
I posted. Also wanted to ask - 
Is there any API/packages to validate config per plugin ?

**Comment by danielnelson** [comment]
No, not currently, I'm pretty sure we have an issue open for it though.  You can get some validation by running `telegraf --config partial_or_full_config.conf --test` and checking the result code.
