### ISSUE TITLE
telegraf installation steps for 32bits Linux server

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6020]
please update telegraf installation steps for 32bit Linux server.

**Comment by danielnelson** [comment]
Can you add a link to the steps are you following?  What was the result of following the steps?

**Comment by priyankamondalairtel** [comment]
used below package to install:

wget https://dl.influxdata.com/telegraf/releases/telegraf-1.11.0_linux_i386.tar.gz
tar xf telegraf-1.11.0_linux_i386.tar.gz
 
after that didn't find any configuration steps to follow.

**Comment by danielnelson** [comment]
You probably want to use either the .rpm or the .deb.  Give these instructions a shot, choose either "Ubuntu & Debian" or "Redhat & Centos":

https://docs.influxdata.com/telegraf/v1.11/introduction/installation/#installation
