### ISSUE TITLE
Enhance pgbouncer with SHOW CLIENTS and SHOW SERVERS queries

### ISSUE THREAD

**Issue by johnatannvmd** [influxdata/telegraf#6021]
## Feature Request

I want to gather `SHOW CLIENTS` and `SHOW SERVERS` metrics but, currently, I limited with only `SHOW POOLS` and `SHOW STATS` info.

### Proposal:

If we enhance Postgres service with additional data types(https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql/service.go#L120) that can allow using postgresql_extensible input plugin with any query that we want on the pgbouncer backend.

Enhancing is safe for regular queries on Postgres because of standard types OID begins with 1000, and pgbouncer uses from 0 to 29.

Also, we can remove the pgbouncer plugin and make the code a bit cleaner because we remove IsPgBouncer from Service interface.

### Current behavior:

Got error:
ERROR: unsupported pkt type: 80 (SQLSTATE 08P01)

### Desired behavior:

Retrieve metrics from pgbouncer.

### Use case:

To add `SHOW CLIENTS` and `SHOW SERVERS` queries I should rewrite pgbouncer plugin. Also, the usage of this plugin makes an additional load to the pgbouncer because it makes 2 queries every time and generates 2 series even if we need only one

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you.

First, thanks for putting up a PR! It does look like your PR was reviewed and had some comments added to it. Do you plan to make the proposed changes?

Thanks!

**Comment by johnatannvmd** [comment]
Looks like this is not applicable since the telegraf migrated to the new version of the PGX. New PGX version does not support OID injection anymore.
