### ISSUE TITLE
Smart_attributes not written to influxdb on NVME drive

### ISSUE THREAD

**Issue by coccobill1** [influxdata/telegraf#6032]
### Relevant telegraf.conf:

```
[[outputs.influxdb]]

[[inputs.smart]]
  attributes = true
```

### System info:

telegraf-1.11.0_windows_amd64
Windows 10 Pro
Smartmontools 7.0-1.win32
Samsung 970 EVO NVME drive

### Steps to reproduce:

1. Set up telegraf to output smart data to influxdb

### Expected behavior:
Smart_attribute data is written to influxdb.

### Actual behavior:
It is not. :)
Smart_device data however is written as expected.

### Additional info:

C:\Program Files\smartmontools\bin>smartctl --scan
/dev/sda -d ata # /dev/sda, ATA device
/dev/sdb -d ata # /dev/sdb, ATA device
/dev/sdc -d ata # /dev/sdc, ATA device
/dev/sdd -d ata # /dev/sdd, ATA device
/dev/sde -d nvme # /dev/sde, NVMe device
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device

C:\Program Files\smartmontools\bin>smartctl --info --health --attributes --tolerance=verypermissive --nocheck never --format=brief -d nvme /dev/sde
smartctl 7.0 2018-12-30 r4883 [x86_64-w64-mingw32-w10-1803] (sf-7.0-1)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Samsung SSD 970 EVO 500GB
Serial Number:                      S466NX0KA31720Y
Firmware Version:                   2B2QEXE7
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 500 107 862 016 [500 GB]
Unallocated NVM Capacity:           0
Controller ID:                      4
Number of Namespaces:               1
Namespace 1 Size/Capacity:          500 107 862 016 [500 GB]
Namespace 1 Utilization:            295 934 984 192 [295 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            002538 5a81b10565
Local Time is:                      Sat Jun 22 02:41:21 2019 FLEDT

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        56 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    21 774 922 [11,1 TB]
Data Units Written:                 15 592 894 [7,98 TB]
Host Read Commands:                 183 297 031
Host Write Commands:                251 173 273
Controller Busy Time:               1 054
Power Cycles:                       5
Power On Hours:                     3 824
Unsafe Shutdowns:                   2
Media and Data Integrity Errors:    0
Error Information Log Entries:      22
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               56 Celsius
Temperature Sensor 2:               69 Celsius

**Comment by danielnelson** [comment]
Thanks @coccobill1, could you also add the output of `telegraf --input-filter=smart --test`?

**Comment by coccobill1** [comment]
C:\Users\tommi\Downloads\telegraf-1.11.0_windows_amd64\telegraf>telegraf --config telegraf.conf --input-filter=smart --test
2019-06-22T00:18:46Z I! Starting Telegraf 1.11.0
> smart_attribute,host=CHRONUS,id=194,name=Temperature_Celsius raw_value=54i 1561162727000000000
> smart_attribute,host=CHRONUS,id=12,name=Power_Cycle_Count raw_value=5i 1561162727000000000
> smart_device,device=nvme0,host=CHRONUS,model=Samsung\ SSD\ 970\ EVO\ 500GB,serial_no=S466NX0KA31720Y exit_status=0i,health_ok=true,temp_c=54i 1561162727000000000
> smart_attribute,host=CHRONUS,id=194,name=Temperature_Celsius raw_value=54i 1561162727000000000
> smart_attribute,host=CHRONUS,id=12,name=Power_Cycle_Count raw_value=5i 1561162727000000000
> smart_device,device=sde,host=CHRONUS,model=Samsung\ SSD\ 970\ EVO\ 500GB,serial_no=S466NX0KA31720Y exit_status=0i,health_ok=true,temp_c=54i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=PO--CK,host=CHRONUS,id=5,name=Reallocated_Sector_Ct,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=9,name=Power_On_Hours,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=15440i,threshold=0i,value=96i,worst=96i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=12,name=Power_Cycle_Count,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=44i,threshold=0i,value=99i,worst=99i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=PO--C-,host=CHRONUS,id=177,name=Wear_Leveling_Count,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=55i,threshold=0i,value=97i,worst=97i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=PO--C-,host=CHRONUS,id=179,name=Used_Rsvd_Blk_Cnt_Tot,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=181,name=Program_Fail_Cnt_Total,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=182,name=Erase_Fail_Count_Total,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=PO--C-,host=CHRONUS,id=183,name=Runtime_Bad_Block,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=187,name=Uncorrectable_Error_Cnt,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=190,name=Airflow_Temperature_Cel,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=42i,threshold=0i,value=58i,worst=41i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O-RC-,host=CHRONUS,id=195,name=ECC_Error_Rate,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=0i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=POSR--,host=CHRONUS,id=1,name=Raw_Read_Error_Rate,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=51i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-OSRCK,host=CHRONUS,id=199,name=CRC_Error_Count,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=POS---,host=CHRONUS,id=3,name=Spin_Up_Time,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=5130i,threshold=11i,value=86i,worst=86i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--C-,host=CHRONUS,id=235,name=POR_Recovery_Count,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=20i,threshold=0i,value=99i,worst=99i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=4,name=Start_Stop_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=4841i,threshold=0i,value=95i,worst=95i 1561162727000000000
> smart_attribute,device=sda,fail=-,flags=-O--CK,host=CHRONUS,id=241,name=Total_LBAs_Written,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,raw_value=60542166535i,threshold=0i,value=99i,worst=99i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=PO--CK,host=CHRONUS,id=5,name=Reallocated_Sector_Ct,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=1i,threshold=10i,value=100i,worst=100i 1561162727000000000
> smart_device,device=sda,enabled=Enabled,host=CHRONUS,model=Samsung\ SSD\ 850\ EVO\ 500GB,serial_no=S2RBNX0J407800R,wwn=5002538d41ead9eb exit_status=0i,health_ok=true,temp_c=42i,udma_crc_errors=0i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=POSR--,host=CHRONUS,id=7,name=Seek_Error_Rate,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=51i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=P-S--K,host=CHRONUS,id=8,name=Seek_Time_Performance,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=15i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=9,name=Power_On_Hours,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=88169i,threshold=0i,value=83i,worst=83i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=PO--CK,host=CHRONUS,id=10,name=Spin_Retry_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=51i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--C-,host=CHRONUS,id=11,name=Calibration_Retry_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=1i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=12,name=Power_Cycle_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=231i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-OSR--,host=CHRONUS,id=13,name=Read_Soft_Error_Rate,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=183,name=Runtime_Bad_Block,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=PO--CK,host=CHRONUS,id=184,name=End-to-End_Error,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=99i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=187,name=Reported_Uncorrect,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=188,name=Command_Timeout,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O---K,host=CHRONUS,id=190,name=Airflow_Temperature_Cel,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=43i,threshold=0i,value=57i,worst=54i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O---K,host=CHRONUS,id=194,name=Temperature_Celsius,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=43i,threshold=0i,value=57i,worst=53i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O-RC-,host=CHRONUS,id=195,name=Hardware_ECC_Recovered,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=135648795i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=POSR--,host=CHRONUS,id=1,name=Raw_Read_Error_Rate,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=50i,value=95i,worst=95i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--CK,host=CHRONUS,id=196,name=Reallocated_Event_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=PO--CK,host=CHRONUS,id=5,name=Retired_Block_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=3i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O--C-,host=CHRONUS,id=197,name=Current_Pending_Sector,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=9,name=Power_On_Hours_and_Msec,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=214824410i,threshold=0i,value=32i,worst=32i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=----CK,host=CHRONUS,id=198,name=Offline_Uncorrectable,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=12,name=Power_Cycle_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=140i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-OSRCK,host=CHRONUS,id=199,name=UDMA_CRC_Error_Count,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=171,name=Program_Fail_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O-R--,host=CHRONUS,id=200,name=Multi_Zone_Error_Rate,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=172,name=Erase_Fail_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdd,fail=-,flags=-O-R--,host=CHRONUS,id=201,name=Soft_Read_Error_Rate,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=POSR-K,host=CHRONUS,id=1,name=Raw_Read_Error_Rate,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=51i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=----CK,host=CHRONUS,id=174,name=Unexpect_Power_Loss_Ct,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=20i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_device,device=sdd,enabled=Enabled,host=CHRONUS,model=SAMSUNG\ HD642JJ,serial_no=S1AFJ1CQ605315,wwn=50000f0008063551 exit_status=0i,health_ok=true,read_error_rate=0i,seek_error_rate=0i,temp_c=43i,udma_crc_errors=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=POS--K,host=CHRONUS,id=3,name=Spin_Up_Time,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=5966i,threshold=21i,value=180i,worst=175i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=------,host=CHRONUS,id=177,name=Wear_Range_Delta,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=11i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=4,name=Start_Stop_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=1657i,threshold=0i,value=99i,worst=99i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=181,name=Program_Fail_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=PO--CK,host=CHRONUS,id=5,name=Reallocated_Sector_Ct,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=140i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=182,name=Erase_Fail_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-OSR-K,host=CHRONUS,id=7,name=Seek_Error_Rate,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=253i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=187,name=Reported_Uncorrect,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=9,name=Power_On_Hours,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=33828i,threshold=0i,value=54i,worst=54i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O---K,host=CHRONUS,id=194,name=Temperature_Celsius,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=39i,threshold=0i,value=39i,worst=50i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=10,name=Spin_Retry_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=--SRC-,host=CHRONUS,id=195,name=ECC_Uncorr_Error_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=120i,worst=120i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=11,name=Calibration_Retry_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=253i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=PO--CK,host=CHRONUS,id=196,name=Reallocated_Event_Count,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=3i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=12,name=Power_Cycle_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=72i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=--SRC-,host=CHRONUS,id=201,name=Unc_Soft_Read_Err_Rate,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=120i,worst=120i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=192,name=Power-Off_Retract_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=37i,threshold=0i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=--SRC-,host=CHRONUS,id=204,name=Soft_ECC_Correct_Rate,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=0i,value=120i,worst=120i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=193,name=Load_Cycle_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=64852i,threshold=0i,value=179i,worst=179i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=PO--C-,host=CHRONUS,id=230,name=Life_Curve_Status,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=100i,threshold=0i,value=100i,worst=100i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O---K,host=CHRONUS,id=194,name=Temperature_Celsius,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=47i,threshold=0i,value=103i,worst=95i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=PO--C-,host=CHRONUS,id=231,name=SSD_Life_Left,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=0i,threshold=10i,value=71i,worst=71i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=196,name=Reallocated_Event_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=------,host=CHRONUS,id=233,name=SandForce_Internal,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=197996i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=197,name=Current_Pending_Sector,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=234,name=SandForce_Internal,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=66293i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=----CK,host=CHRONUS,id=198,name=Offline_Uncorrectable,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=253i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=241,name=Lifetime_Writes_GiB,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=66293i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=-O--CK,host=CHRONUS,id=199,name=UDMA_CRC_Error_Count,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=200i,worst=200i 1561162727000000000
> smart_attribute,device=sdb,fail=-,flags=-O--CK,host=CHRONUS,id=242,name=Lifetime_Reads_GiB,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,raw_value=116770i,threshold=0i,value=0i,worst=0i 1561162727000000000
> smart_attribute,device=sdc,fail=-,flags=---R--,host=CHRONUS,id=200,name=Multi_Zone_Error_Rate,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,raw_value=0i,threshold=0i,value=100i,worst=253i 1561162727000000000
> smart_device,device=sdb,enabled=Enabled,host=CHRONUS,model=KINGSTON\ SH100S3120G,serial_no=50026B721B040192,wwn=50026b721b040192 exit_status=0i,health_ok=true,read_error_rate=0i,temp_c=39i 1561162727000000000
> smart_device,device=sdc,enabled=Enabled,host=CHRONUS,model=WDC\ WD30EFRX-68EUZN0,serial_no=WD-WCC4N0DVV1VH,wwn=50014ee261227356 exit_status=0i,health_ok=true,read_error_rate=0i,seek_error_rate=0i,temp_c=47i,udma_crc_errors=0i 1561162727000000000

**Comment by danielnelson** [comment]
Looks like we are not setting tags correctly on the nvme device, for example this metric should have the `device` and `serial_no` tags like in the associated `smart_device`:
```
smart_attribute,host=CHRONUS,id=194,name=Temperature_Celsius raw_value=54i 1561162727000000000
```

**Comment by coccobill1** [comment]
Yeah, also any idea why it only lists 4 attributes when there should be, um, 14?

**Comment by coccobill1** [comment]
Or actually just 2 attributes twice (PoH and temp), for /dev/sde and /dev/nvme0.

**Comment by danielnelson** [comment]
We have limited support for info in the NVMe log as it's not formatted in the same way as the normal attribute table, which look more like this:
```
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  5 Reallocated_Sector_Ct   -O--CK   100   100   ---    -    0
  9 Power_On_Hours          -O--CK   100   100   ---    -    6383
 12 Power_Cycle_Count       -O--CK   100   100   ---    -    19
165 Unknown_Attribute       -O--CK   100   100   ---    -    59310806
```

I assume `/dev/sde` and `/dev/nvme0` are actually the same devices?  Gathering both just follows from the output of `smartctl --scan` listed both variations, but you could work around this by either listing the devices manually in the `devices` setting of the plugin, or by using `tagdrop` to remove one of them after it has been collected.

**Comment by coccobill1** [comment]
They are the same device yes, but yeah that's not an issue at all. Just really a shame if the only smart_attributes parsed are temperature (which already comes with the smart_device data) and power cycle count. Should I make a separate feature request for some key pre-fail attributes? I'd like to be able to pull at least "Media and Data Integrity Errors" and "Power On Hours". Sadly the drive doesn't report reallocated sectors, wear leveling count or uncorrectable errors for some reason.

**Comment by danielnelson** [comment]
Yeah, could you open a new issue?
