### ISSUE TITLE
logparser unable to parse ISO 8601 timestamp

### ISSUE THREAD

**Issue by nsupathy** [influxdata/telegraf#6034]
## Feature Request
logparser input plugin is unable to parse timestamp in ISO 8601 format.
Please refer to https://en.wikipedia.org/wiki/ISO_8601
I am using the timestamp format 2019-06-23T14:26:34+00:00
Lot of applications/services use this timestamp format.  It will be easier to roll out logparser instead of writing custom scripts to extract information from these applications.

### Proposal:
Please add options to parse timestamp in ISO 8610 format to Timestamp modifiers:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser

### Current behavior:
logparser plugin refuses to parse a timestamp in ISO 8601 format.

### Desired behavior:
logparser input plugin should support timestamp in ISO 8601 format out of the box.

### Use case: 
ISO 8601 is one of the most used timestamp formats by a lot of services.  
Here, I am trying to parse metrics out of **Java G1 Garbage collector** logs which uses this timestamp as below.
`[2019-04-29T16:06:30.296+0100][229283315ms][27977][debug][gc,plab              ] GC(527) Young PLAB allocation: allocated: 26416552B, wasted: 130480B, unused: 2026576B, used: 24259496B, undo waste: 0B,
`

**Comment by danielnelson** [comment]
You can almost use `ts-rfc3339nano` for your format, but need a colon in the timezone offset: `+01:00` vs `+0100`, so instead you will need to use a custom format for this case.

If you want to parse a log file like this:
```
[2019-04-29T16:06:30.296+0100] 42
```

You can use this slightly modified pattern:
```
patterns = ['\[%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.999999999Z0700"}\] %{NUMBER:value:float}']
```
