### ISSUE TITLE
Question: glide vs godeps

### ISSUE THREAD

**Issue by jchauncey** [influxdata/telegraf#605]
Have you guys thought about using Glide instead of godeps?

**Comment by sparrc** [comment]
I wanted something more simple, why?

**Comment by jchauncey** [comment]
hand editing the godeps file with merge conflicts is awful. Unless I'm doing it wrong.

**Comment by sparrc** [comment]
how would that be any different with Glide? isn't there still a dependency file?

**Comment by jchauncey** [comment]
The problem I just had was that I added new deps to the file and then rebased against master which added more dependencies and changed the shas on others. I'm not sure glide would actually fix this now that I think about it. We use it internally for our go projects (since one of our devs wrote it) and it works well but I haven't had a large merge conflict like this before. Anyways I'll close the issue since I dont think it would help.

Thanks

**Comment by sparrc** [comment]
I guess I'm not sure either because I haven't used Glide, but you shouldn't need to edit the file manually, you can use https://github.com/sparrc/gdm to manage it (or https://github.com/robfig/glock, but change the file name)

**Comment by jchauncey** [comment]
The one thing it would do is allow you to install the deps into a vendor directory that is managed by glide. This means when we run `glide install` we aren't munging with stuff in the gopath.
