### ISSUE TITLE
Regex with named field access, creates new field with full String

### ISSUE THREAD

**Issue by DButter** [influxdata/telegraf#6057]
### Relevant telegraf.conf:
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = "kitchen"
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":5665"
  expiration_interval = "60s"

[[inputs.exec]]
  commands = ["/usr/lib/telegraf/scripts/check_ipa_sync_date.sh"]
  timeout = "5s"
  name_override="check_ipa_sync_date"
  data_format = "value"
  data_type = "string"

[[processors.regex]]
 namepass = ["check_ipa_sync_date"]
 order = 1
 [[processors.regex.fields]]
  key = "value"
    pattern = ".*(?:nsds5replicaLastUpdateEnd: )(?P<Date>\\d*)Z"
  replacement = "${Date}"
  result_key = "sync_date"

[[processors.converter]]
 order = 2
 namepass = ["check_ipa_sync_date"]
  [processors.converter.fields]
  float = ["sync_date"]

[[processors.rename]]
  order = 3
  namepass = ["check_ipa_sync_date"]
  [[processors.rename.replace]]
  measurement = "check_ipa_sync_date"
  dest = "ipa_sync_date"

[[outputs.file]]
 files = ["/var/log/telegraf/outputLog.log"]
 data_format = "influx"
```

##check_ipa_sync_date.sh
'''
echo "version: 1

dn: cn=meToipa02.test.me,cn=replica,cn=dc\3Drcrs\2Cdc\3Dme,cn=mapping tree,cn=
 config
nsds5replicaLastUpdateEnd: 20190627132140Z"
'''

### System info:

Telegraf 1.8.3 (git: HEAD f2979106)
Red Hat Enterprise Linux Server 7.5 (Maipo)

### Steps to reproduce:

run telegraf with config and shell script

### Expected behavior:

/var/log/telegraf/outputLog.log should contain 
check_ipa_sync_date,sometags sync_date=20190627132140 someTimeStamp

or

a parser error message of some kind

### Actual behavior:

/var/log/telegraf/outputLog.log did not contain the line mentioned above, instead it contained:

"version: 1\n\ndn: cn=meToipa02.rcrs.me,cn=replica,cn=dc\\3Drcrs\\2Cdc\\3Dme,cn=mapping tree,cn=\n config\nnsds5replicaLastUpdateEnd: 20190627132140Z"

which is basically the unchanged input string

log contained:

"2019-07-01T15:41:50Z D! [processors.converter] error converting to integer [string]: version: 1

dn: cn=meToipa02.rcrs.me,cn=replica,cn=dc\3Drcrs\2Cdc\3Dme,cn=mapping tree,cn=
 config
20190627132140"

my best guess is that the "sync_date" field contained the whole string when it came to the parse step

### Additional info:
tested regex and string with golang code snippet:

'''
package main

import "fmt"
import "regexp"

func main() {
	pattern := ".*(?:nsds5replicaLastUpdateEnd: )(?P<Date>\\d*)Z"
	src := "version: 1\n\ndn: cn=meToipa02.rcrs.me,cn=replica,cn=dc\\3Drcrs\\2Cdc\\3Dme,cn=mapping tree,cn=\n config\nnsds5replicaLastUpdateEnd: 20190627132140Z"
	replacement := "${Date}"
	
	regex := regexp.MustCompile(pattern)
    value := regex.ReplaceAllString(src, replacement)
	fmt.Println(value)
}
'''

value printed was "20190627132140" so i guess it should work in principle

**Comment by danielnelson** [comment]
You will need to set the `s` flag so that your regexp matches newlines, otherwise only the last line of the input is modified:
```
pattern = "(?s).*(?:nsds5replicaLastUpdateEnd: )(?P<Date>\\d*)Z"
```

**Comment by DButter** [comment]
@danielnelson hey, i tried your solution and you are completely right about the cause of the non match, but i would have expected the regex filter to not create a "sync_date" field at all when the regex fails. Especially if I use named fields to fill it.

Is that assumption wrong?

**Comment by danielnelson** [comment]
I believe this is how it works, but in this particular case the regular expression matched.
