### ISSUE TITLE
Input: Bind - strconv.ParseInt : value out of range

### ISSUE THREAD

**Issue by valcryst** [influxdata/telegraf#6059]
### Relevant telegraf.conf:
```[[inputs.bind]]
  interval = "30s"
  urls = ["http://localhost:8053/xml/v3"]
  gather_memory_contexts = false
  gather_views = false

```

### System info:

Telegraf 1.11.1-1 i386
Ubuntu 16.04.06 LTS i386
Bind 9.10.3

### Expected behavior:

Parse value

### Actual behavior:

[inputs.bind]: Error in plugin: Unable to decode XML document: strconv.ParseInt: parsing "2389951589": value out of range

**Comment by danielnelson** [comment]
@valcryst I think this will solve the issue, could you test out this build?

- [telegraf_1.12.0~75e2f82c-0_i386.deb](https://35858-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.12.0~75e2f82c-0_i386.deb)

**Comment by rumanmaharjan** [comment]
same error on telegraf v1.31.2
