### ISSUE TITLE
Telegraf build that can run on android

### ISSUE THREAD

**Issue by Piyaphong** [influxdata/telegraf#6065]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
build package that can run on android
### Current behavior:
do not have package apk for android
### Desired behavior:
run
### Use case: 
too few opensource application can monitor android on large scale

**Comment by goller** [comment]
@Piyaphong Are you thinking telegraf could be an SDK or a full application?

difference is highlighted here: https://github.com/golang/go/wiki/Mobile

**Comment by markusressel** [comment]
I'm also interested in this. There would need to be a way to configure telegraf but from my point of view a predefined file path located on the local android storage would be sufficient for that so afaik it could be a native application. An automatically build release artifact for android with some minor adjustments to the `AndroidManifest.xml` for storage access would a good start. Although it might be necessary for users to manually allow the storage permission on devices requiring android runtime permissions.

**Comment by danielnelson** [comment]
Would be great if someone could try to build Telegraf using gomobile as an application, and document how to setup the environment and the compile results.  Once the environment is setup it should be something along the lines of this in place of `make telegraf` in the current build steps:
```
gomobile build -target=android github.com/influxdata/telegraf
```

https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-android

**Comment by denzuko** [comment]
Outside of relying on termux; I'd expect most users would prefer an app that can display logs, configure, and start/stop an Android Background Service for telegraf. Orbot would be a good example.

**Comment by srebhan** [comment]
It's currently not planned to provide official builds for Android. If you do have a working setup to build Telegraf for Android, please provide a PR documenting on how to do it and/or contact us for a blog post. Closing this issue.

**Comment by markusressel** [comment]
For anyone interested, the Home Assistant Android companion App can track a huge variety of properties:
https://github.com/home-assistant/android
It's not really a replacement for telegraf, but might be sufficient depending on your needs.
