### ISSUE TITLE
x509_cert: Error when site SSL is not valid

### ISSUE THREAD

**Issue by Jokuh** [influxdata/telegraf#6066]
Relevant telegraf.conf:
[[inputs.x509_cert]]
sources = ["https://www.testsite.com:443""]

Additional info: 
The SSL of the site is currently expired, and I am trying to set up monitoring for that URL.

Expected behavior:
Telegraf exposes SSL metrics for www.google.com, and indicated that it is expired (i.e. expiry as a negative value). That way alerts can be set up for certificates that are already expired, and no monitored sites are lost out of sight when the dashboard time frame moves.  

Actual behavior:
Because www.testsite.com is expired, the pluging throws an error "[inputs.x509_cert]: Error in plugin: cannot get SSL cert 'https://testsite.com:443': x509: certificate has expired or is not yet valid"

**Comment by danielnelson** [comment]
I think you must set `insecure_skip_verify = true` in order to check a potentially invalid certificate, can you give this a shot?

**Comment by Jokuh** [comment]
I think that was enabled, but unfortunately we have renewed the certificate so I cannot test anymore. I'll keep an eye on it.

**Comment by danielnelson** [comment]
Will keep open until we can test this behavior.  It seems like if we need `insecure_skip_verify` for invalid certs the documentation needs updated.

**Comment by glinton** [comment]
Closed by #6143 

Note, `insecure_skip_verify` is deprecated. Config won't complain, it just doesn't get used anymore.
