### ISSUE TITLE
procstat - Collecting processes directly by providing PIDs in config file

### ISSUE THREAD

**Issue by burakyuksel0** [influxdata/telegraf#6067]
## Feature Request

I could not find if there is a way to do that but I think it would be better if we were able to collect processes by providing their PIDs in config file, maybe as an array.

### Desired behavior:

- Being able to specify processes to monitor by their PIDs

### Use case: 

It makes the plugin more customizable and prevents collecting unwanted processes.

**Comment by danielnelson** [comment]
It wouldn't be hard to do, but it seems to me that it wouldn't work very well either.  Anytime you restart the program you would need to modify the configuration and reload Telegraf.  The only situation I can see this is monitoring pid 1, can you tell me more about your use case?

**Comment by burakyuksel0** [comment]
You are right. 
In my case the programs, I wanted to monitor, didn't have pidfile. I needed either to create pidfiles manually, or to make procstat_lookup collect all running programs and select programs from Chronograf manually.

**Comment by danielnelson** [comment]
Have you tried using one of the other matching options: `exe`, `pattern`, `user`, etc?  How do you usually lookup the process manually to create the pidfile, maybe you can use a similar method.

**Comment by burakyuksel0** [comment]
I was searching processes by using `ps` and `grep` commands. Looks like `pattern` option would mostly do my job. I used telegraf for a short period of time and I just wanted to be able to pick exact processes but as you said it may not be handy for generic use cases.
We can close the issue and thanks a lot for your attention.
