### ISSUE TITLE
Json field in datadog mis-generated

### ISSUE THREAD

**Issue by wryun** [influxdata/telegraf#607]
Bad search replace in:

https://github.com/influxdata/telegraf/commit/c549ab907ab567a3a1cfb10039d5fa32d2e16100

Caused 'points' to be renamed to 'metrics', and 'omitemmy' to be specified on the json field. See comments on commit.

**Comment by sparrc** [comment]
thanks for keeping me honest @wryun, wish there was a better way for me to test this output plugin

**Comment by wryun** [comment]
Could add some testing ;) (thinking about a PR, I promise)
