### ISSUE TITLE
Telegraf still set _type field metrics for ES 7.x ?

### ISSUE THREAD

**Issue by Theoooooo** [influxdata/telegraf#6071]
### Relevant telegraf.conf:
```
[agent]
        interval                =       "15s"
        flush_interval          =       "15s"
        hostname                =       "ModSecurity"
        round_interval          =       true

[[inputs.cpu]]
        percpu                  =       true
        totalcpu                =       true

[[inputs.disk]]
        ignore_fs               =       ["tmpfs","udev","devtmpfs"]

[[inputs.mem]]

[[inputs.system]]

[[inputs.net]]
        interfaces              =       ["ens*"]

[[outputs.elasticsearch]]
        urls                    =       ["http://x.x.x.x:9200"]
        timeout                 =       "30s"
        health_check_interval   =       "30s"
        index_name              =       "local_modsecurity-%Y-%m-%d"
        manage_template         =       true
        template_name           =       "local_modsecurity-*"
        overwrite_template      =       true
```

### System info:

Telegraf v1.11.1
Elasticsearch v7.2.0
CentOS7 Minimal 1807

### Steps to reproduce:
Install telegraf
Install ElasticSearch
Add configuration to Telegraf
Start both service
Can't input data to ElasticSearch due to mapping issue 

### Actual behavior:
ElasticSearch create the default mapping with doc _type and not metrics. Because of this, i can't modify the existing mapping neither telegraf itself with the proper options. It still output the Elasticsearch error about the _type not being the same

According to this post #6053 it should be removed but somehow Telegraf still use it on my ES 7.2.0 instance.
And because of this issue many fields are not set to the correct type like system.load1 is
 set to long instead of float.

**Comment by danielnelson** [comment]
Can you try with one of the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds)?  #6053 will be included in the 1.12 release.

**Comment by Theoooooo** [comment]
Sorry i was not available to do this test, i was in school.
I will test this today and give you a feedback @danielnelson

**Comment by Theoooooo** [comment]
I can confirm that the nightly build you send me works correctly and set _doc for the _type.

**Comment by danielnelson** [comment]
Great, appreciate the testing and workaround.
