### ISSUE TITLE
Cisco MDT Input Plugin Not Binding

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#6078]
### Relevant telegraf.conf:
[[inputs.cisco_telemetry_mdt]]
 ## Telemetry transport can be "tcp" or "grpc".  TLS is only supported when
 ## using the grpc transport.
 transport = "grpc"

 ## Address and port to host telemetry listener
 service_address = "1.1.1.1:50051"

 ## Enable TLS; grpc transport only.
 # tls_cert = "/etc/telegraf/cert.pem"
 # tls_key = "/etc/telegraf/key.pem"

 ## Enable TLS client authentication and define allowed CA certificates; grpc
 ##  transport only.
 tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]

 ## Define aliases to map telemetry encoding paths to simple measurement names
 [inputs.cisco_telemetry_mdt.aliases]
   ifstats = "ietf-interfaces:interfaces-state/interface/statistics"

##Output to file##
[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "json"
  json_timestamp_units = "1ns"

### System info:

Telegraf v1.11
CentOS 7
Docker 18.05.0-ce, build f150324

### Steps to reproduce:

1. Build telegraf container using the Dockerfile provided in the repo.
2. Create a docker-compose.yml file with parameters appropriate parameters.
3. Run docker-compose up to start the container.

### Expected behavior:
Expecting to see streaming telemetry data write to the screen.

### Actual behavior:
Creating network "111_default" with the default driver
Creating telegraf-1.11 ... done
Attaching to telegraf-1.11
telegraf-1.11      | 2019-07-06T10:43:11Z I! Starting Telegraf 1.11.1
telegraf-1.11      | 2019-07-06T10:43:11Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf-1.11      | 2019-07-06T10:43:11Z I! Loaded inputs: cisco_telemetry_mdt
telegraf-1.11      | 2019-07-06T10:43:11Z I! Loaded aggregators: 
telegraf-1.11      | 2019-07-06T10:43:11Z I! Loaded processors: 
telegraf-1.11      | 2019-07-06T10:43:11Z I! Loaded outputs: file
telegraf-1.11      | 2019-07-06T10:43:11Z I! Tags enabled: host=c235df6eca17
telegraf-1.11      | 2019-07-06T10:43:11Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"c235df6eca17", Flush Interval:10s
telegraf-1.11      | 2019-07-06T10:43:11Z E! [agent] Service for input inputs.cisco_telemetry_mdt failed to start: listen tcp 1.1.1.1:50051: bind: cannot assign requested address
telegraf-1.11      | 2019-07-06T10:43:11Z E! [telegraf] Error running agent: listen tcp 1.1.1.1:50051: bind: cannot assign requested address

### Additional info:
Router is configured with Telemetry to stream off port 50051.
When I locally compiled telegraf from (https://github.com/ios-xr/telegraf-plugin/tree/master/plugins/inputs/cisco_telemetry_mdt) it works fine.

Also, wanted to point out that when I try to assign a username and password in the telegraf.conf file I get an error message stating that 'username' is undefined:

Attaching to telegraf-alpine-1.11
telegraf-alpine-1.11 | 2019-07-05T23:45:07Z I! Starting Telegraf 1.11.1
telegraf-alpine-1.11 | 2019-07-05T23:45:07Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf-alpine-1.11 | 2019-07-05T23:45:07Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 19: field corresponding to `username' is not defined in cisco_telemetry_mdt.CiscoTelemetryMDT

**Comment by danielnelson** [comment]
This plugin listens on the service address, so it needs to be given an IP address assigned to one of the systems interfaces.  

The code linked is indeed different from what is included in Telegraf, the largest difference is that the plugin included in Telegraf does not support grpc dialin, and is only tcp and grpc dialout.  This is why the `username` option is not available.

Let me know if you still have questions.
