### ISSUE TITLE
AMQP output plugin direct queue support

### ISSUE THREAD

**Issue by Esity** [influxdata/telegraf#6095]
## Feature Request

The AMQP output plugin should support writing directly to a queue. Currently you can only write to an exchange

### Use case: 
Some times there isn't a need for an exchange. This will allow people to skip the exchange side of things

**Comment by danielnelson** [comment]
I think this can be done by sending to the default exchange:
```
exchange = ""
routing_key = "mytopic"
```

**Comment by Esity** [comment]
Per the RMQ documentation at [amqp-concepts](https://www.rabbitmq.com/tutorials/amqp-concepts.html)

> The default exchange is a direct exchange with no name (empty string) pre-declared by the broker. It has one special property that makes it very useful for simple applications: every queue that is created is automatically bound to it with a routing key which is the same as the queue name.

Closing this issue
