### ISSUE TITLE
jti_openconfig_telemetry component_id as tag

### ISSUE THREAD

**Issue by AlexSnarf** [influxdata/telegraf#6096]
## Feature Request

Hi, 
First thank you for your job!
I've been playing with Telegraf/influxdb along with some Juniper routers for some time now and it works pretty well.
Nonetheless I am facing a frustrating issue when I'm working with Firewall counters. Those counters are identified by a Firewall name, a counter Name and also by a component_id. The problem is that this component_id is created as a field and not as a tag, preventing us from using it in `group by` statement in influxdb.

I don't know if it's a desired behavior neither if we get some benefits to get this as a field instead of a tag.

### Proposal:
Add a configuration statement to treat component_id (and subcomponent_id) as tag instead of field.

### Current behavior:
component_id is a field

### Desired behavior:
component_id is a tag
### Use case:
When working with Firewall counters it can be usefull to make some `group by _component_id`.

**Comment by glinton** [comment]
Have you considered [the converter processor](https://github.com/influxdata/telegraf/tree/1.11.1/plugins/processors/converter) to convert from a field to a tag?

**Comment by danielnelson** [comment]
@AlexSnarf Could you also add a few examples of the metrics Telegraf is collecting?

**Comment by AlexSnarf** [comment]
> Have you considered [the converter processor](https://github.com/influxdata/telegraf/tree/1.11.1/plugins/processors/converter) to convert from a field to a tag?

I'll check this! I thought this plugin could only work on the type (str, int, etc...) but you are right, the documentation says it can also convert field to tag. I'll give it a try.

Here are some of the data I'm collecting, this is the data as they are stored in influxdb:
```
name: /junos/system/linecard/firewall
time                /junos/firewall/@name /junos/firewall/state/counter/@name /junos/firewall/state/counter/bytes /junos/firewall/state/counter/packets /junos/firewall/state/memory-usage/@name /junos/firewall/state/memory-usage/allocated /junos/firewall/state/policer/@name /junos/firewall/state/policer/out-of-spec-bytes /junos/firewall/state/policer/out-of-spec-packets /junos/firewall/state/timestamp __timestamp__ _component_id _sequence _subcomponent_id _timestamp    device   host     path                                                                              system_id
----                --------------------- ----------------------------------- ----------------------------------- ------------------------------------- ---------------------------------------- -------------------------------------------- ----------------------------------- ----------------------------------------------- ------------------------------------------------- ------------------------------- ------------- ------------- --------- ---------------- ----------    ------   ----     ----                                                                              ---------
1562742436051509711 HACK-OUT-ae41.0-o     HACK-NTP-ae41.0-o                   311850916782                        3281238103                                                                                                                                                                                                                                                                                                      3             1873      0                1562742435939 device01 MUZTC840 sensor_1001:/junos/system/linecard/firewall/:/junos/system/linecard/firewall/:PFE device01
1562742436115694585 HACK-OUT-ae41.0-o     HACK-NTP-ae41.0-o                   295781984939                        3192954148                                                                                                                                                                                                                                                                                                      5             1873      0                1562742436006 device01 MUZTC840 sensor_1001:/junos/system/linecard/firewall/:/junos/system/linecard/firewall/:PFE device01
1562742466155292067 HACK-OUT-ae41.0-o     HACK-NTP-ae41.0-o                   311851319618                        3281243397                                                                                                                                                                                                                                                                                                      3             1874      0                1562742466062 device01 MUZTC840 sensor_1001:/junos/system/linecard/firewall/:/junos/system/linecard/firewall/:PFE device01
1562742466249748231 HACK-OUT-ae41.0-o     HACK-NTP-ae41.0-o                   295782381313                        3192959353                                                                                                                                                                                                                                                                                                      5             1874      0                1562742466122 device01 MUZTC840 sensor_1001:/junos/system/linecard/firewall/:/junos/system/linecard/firewall/:PFE device01
```

We have filter on lag interfaces which can rely on physical interfaces located on different boards. Let me know if this is enough or if you want raw data from the router.

I'll give a feedback on glinton solution as soon as I can.

Thanks.

**Comment by AlexSnarf** [comment]
The converter processor does the job! I'm a bit confused I did not see that before hand...
Anyway don't you think these information should be processed the same way the system_id is? These information share the same purpose, locating where the measure comes from :) and are not variant accross time.
I can be wrong, I'm kind of new in the telemetry world!

**Comment by danielnelson** [comment]
@littlespace Would love to get your opinion on the component_id, do we need it as a tag to provide uniqueness?

**Comment by littlespace** [comment]
@danielnelson, I wrote my own serializer in Telegraf and I am creating a new metric per fields (bytes/ packets for the firewall counters) and add tags to it. I am not using the component_id or subcomponent_id at the moment as a tag because Of the number of tags limitation on opentsdb. @AlexSnarf can you let us know why do you need that? Do you have an use case for it?

**Comment by AlexSnarf** [comment]
> @AlexSnarf can you let us know why do you need that? Do you have an use case for it?

Sure, I want to graph Firewall counters and policer bandwitdh. Those firewalls fiters are applied to lag interfaces based on physical interfaces located on different linecard.
Junos does send the counters per linecard, meaning that if the interfaces in the lag are spread among 2 linecards then I will get 2 counters.
I need to sum the two counters before applying a derivative function to get the bandwidth, the problem is that it can give bad result in influxdb resulting in huge spikes. This is caused by the influxdb `group by time function`  which sometime does not include a value because outside of the timespan.
Here is a sample influxdb request:
```
select non_negative_derivative(sum("/junos/firewall/state/counter/bytes"),1s)*8 from "/junos/system/linecard/firewall" where  ("device"=~/^$device$/) AND ("/junos/firewall/@name" =~ /^$filter_name$/)  and ("/junos/firewall/state/counter/@name" =~ /.*$counter_name.*/) and $timeFilter group by time(30s)
```

The idea is to compute the bandwidth per linecard counter beforehand, but this cannot be done until the component_id is a tag. This way I can get very accurate information per linecard using this request:

```
select non_negative_derivative("/junos/firewall/state/counter/bytes",1s)*8 from "/junos/system/linecard/firewall" where  ("device"=~/^$device$/) AND ("/junos/firewall/@name" =~ /^$filter_name$/)  and ("/junos/firewall/state/counter/@name" =~ /.*$counter_name.*/) and $timeFilter group by "_component_id"
```
I can then sum the results if I want to get the global bandwidth.

I hope it is understandable :)

**Comment by danielnelson** [comment]
At a high level, because unfortunately I don't understand the OpenConfig model well enough, each logical object should form a series: with unique and normally unchanging measurement and tags.

What I see in the data above, unless I'm misreading which is quite possible, is that there are multiple firewall rules but they are all being sent with same measurement/tags.  This means that with InfluxDB they would overwrite each other if not for the fact that the timestamps are slightly different, which is mostly by chance.

Now, component ID isn't really a great tag, because it doesn't seem to carry much meaning and it probably is only important in a few cases, names are often much better, but we do need to find a way to have the tags for the identity for the item.  Is it possible to add a name to the firewall rule that could be used instead?  What does component ID mean in general, is this just an incrementing value for the child number?

Any chance someone has a link to the models for these items?  I'd be interested in digging a bit deeper and trying to understand exactly how the data is structured.

**Comment by AlexSnarf** [comment]
Actually, both values come from the exact same Firewall Filter.
But the equipement send 1 value per physical card.
On router we are using (MX2020) there are 20 linecards. A firewall rule can be applied to a logical interface that relies on physical interfaces located on different linecards. Each line card send the number of packets or bytes that matches the Firewall rule on its own physical interfaces.
For example:
I have a logical interface ae1, this logical interface is made of two physical interfaces : et-1/1 et et-2/1 (first digit is the linecard slot and the last one is the physical interface number on this linecard).
I apply a firewall filter on this logical, for instance that matches ICMP packets.
Linecard 1 will send the number of ICMP packets that passes through et-1/1 and will set the component_id to 1.
Linecard 2 will send the number of ICMP packets that passes through et-1/2 and will set the component_id to 2.

To know how many ICMP packets passes through my logical interface ae1, I need to sum both.

I hope it is clearer, sorry I'm not a native english speaker.

**Comment by stefi994** [comment]
hey @AlexSnarf did you get this to work with the converter processor I am struggling with similar issue and so far can't get this to work.

**Comment by littlespace** [comment]
@danielnelson the component_id is important at least for the firewall and Interface data and I am adding it as a tag for those sensors. I did it on the jti_openconfig_telemetry plugin itself to do this only for specific sensors not all of them.

@stefi994 I think you can do it by:

[[processors.converter]]
[processors.converter.fields]
    tag = ["_component_id"]

**Comment by stefi994** [comment]
@littlespace my problem is for the field: /interfaces/interface/subinterfaces/subinterface/state/description. I tried the above config just with 
tag = ["/interfaces/interface/subinterfaces/subinterface/state/description"] but when I ran the output.file as a test the field was not converted as a tag.

I also tried with str_as_tags=true, but here I can see the field as tag but with not values:
> select "/interfaces/interface/subinterfaces/subinterface/state/counters/out-octets" from "/interfaces/" where "/interfaces/interface/subinterfaces/subinterface/state/description" =~ /^.*/ group by "/interfaces/interface/subinterfaces/subinterface/state/description" limit 10
name: /interfaces/
tags: /interfaces/interface/subinterfaces/subinterface/state/description=
time                /interfaces/interface/subinterfaces/subinterface/state/counters/out-octets
----                --------------------------------------------------------------------------
1605800962062258022 6104849979674134
1605800962062258022 280231971
1605800962062258022 512803304624
1605800962062258022 15339811
1605800962062258022 170802261
1605800962062258022 7641070810
1605800962071695701 13594642094449
1605800962071695701 562035574929
1605800962071695701 3562
1605800962071695701 38487969616933

You can notice at the tag place the value is empty. Can you please let to solve this? Please note that after every change I drop the measurement and restarted the telegraf servise.
The main thing that I want to achieve is to group interface by their description.

**Comment by littlespace** [comment]
@stefi994 I just did a quick test:

[[processors.converter]]
  [processors.converter.fields]
    tag = ["/interfaces/interface/state/description"]

and worked fine. Please note if your interface does not have a description set, then the tag will be null or empty.

**Comment by stefi994** [comment]
@littlespace Do you know if I should restart influxdb, telegraf, drop measurement, or something and by which order? Cause I did try the converter with no success... but I can give it another try tomorrow.

**Comment by stefi994** [comment]
I am now back to this problem again, this convertor does convert the tag into the field. But now is not taking any values from the other fields in order to group by the description

**Comment by powersj** [comment]
@stefi994,

Going through old issues. It looks like the converter gets you what you needed, but you followed up with a question about other fields? Are you trying to combine multiple fields?
