### ISSUE TITLE
[linux] inputs.mem: SlabReclaimable and SlabUnreclaim 

### ISSUE THREAD

**Issue by antitbone** [influxdata/telegraf#6103]
## Feature Request

On linux slab is subdivided into two: SReclaimable and SUnreclaim.
It is interesting to know these two values.

### Proposal:

Add SReclaimable and SUnreclaim values in addition to Slab to inputs.mem

### Use case:
SReclaimable can be freed with /proc/sys/vm/drop_caches.

**Comment by danielnelson** [comment]
@antibone I think the SUnreclaim value ought to be added to gopsutil, do you think you could open an issue upstream?

**Comment by antitbone** [comment]
@danielnelson issue opened on the upstream
https://github.com/shirou/gopsutil/issues/719

**Comment by antitbone** [comment]
https://github.com/shirou/gopsutil/pull/725

**Comment by danielnelson** [comment]
Nice job, I'm anticipating a new gopsutil release in the next few days, since they generally do a release each month.  Once it is out, we can update the dependencies and make the tie in to the mem plugin.

**Comment by adrianlzt** [comment]
I think this issue should be reopenned, because SReclaimable and SUnreclaim values are not added to inputs.mem

**Comment by danielnelson** [comment]
Added these new fields (for real this time) for 1.13.0.
