### ISSUE TITLE
Setup for Type1 and Type 2 hypervisor

### ISSUE THREAD

**Issue by mahima2112** [influxdata/telegraf#6112]
Can telegraf, influxdb and grafana used together to get the metrics from both type1 and type2 hypervisor machines? I have got the metrics for type1 using vmware. how can we do it for stand alone machines?
the telegraf.conf file had some lines about bare metal, but the entire thing didnt work. Also it had some content about about using SNMP which gave no response from server.

OS: Ubuntu 18.04

**Comment by Hipska** [comment]
Hi @mahima2112 could you give some more context? Are you using the vmware api within Telegraf to gather metrics. I'm not sure what you are trying to achieve.

**Comment by Hipska** [comment]
Hi @mahima2112 if you don't provide any more feedback, we cannot help and will need to close the issue.
