### ISSUE TITLE
Input plugin to subscribe to SQS for metrics

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#6115]
## Feature Request

Similar to the GCP pub/sub plugin that can receive metrics, a similar plugin for AWS SQS.  It should be able to work with any of the Telegraf input data formats.

**Comment by nod** [comment]
I'll second this request.

**Comment by jaecktec** [comment]
hey, I implemented an sqs input plugin this weekend as I saw this feature request.
https://github.com/jaecktec/telegraf

I just need to refactor a bit, write a README.md and wait till the contribution license has been accepted. 
But feel free to give me feedback already on my approach :)

**Comment by nod** [comment]
Oops!  I did the same thing a couple of weeks ago but have been so busy I haven't submitted it upstream yet.  :)

https://github.com/nod/telegraf/tree/nod-sqs/plugins/inputs/sqs_consumer

**Comment by jaecktec** [comment]
Ohh :( well OK was a nice distraction though

**Comment by nod** [comment]
@jaecktec hey go ahead and finish it out.  I obviously don't have time to do the glue work. :)

**Comment by jaecktec** [comment]
I've developed it TDD style so every line should be tested. I've also run it locally and I think it works.

Im just not satisfied with the code style, looks so javaish.

**Comment by gordonbondon** [comment]
Looks like this is really in demand, I've been working on a PR for SQS consumer too :) https://github.com/gordonbondon/telegraf/commit/85164fcb1836352ea2b719f28876a7b36ce1af18

**Comment by nod** [comment]
I have a pretty simple tool I use to get items into SQS that might be useful. 

https://github.com/nod/squat

It reads from stdin and each line gets sent to SQS.  There's no batching at the moment but I've been using it in some toy-production projects for a couple of months and it has worked well.

**Comment by jaecktec** [comment]
would be really nice if you could test my pr and give me some feedback :)

I changed my first approach to rely fully on the aws sdk, instead of using the rest api.

**Comment by gordonbondon** [comment]
I wonder what is a better approach to creating queue consumer plugins: a simple gather plugin or service plugin?

Using gather looks much more elegant and allows to shift all complicated goroutine logic to core telegraf implementation. But all other existing consumer plugins were created as service plugins, that's why I've created my PR in the same way. 

I'll give your PR a try.

**Comment by jaecktec** [comment]
Let me check if I can create something elegant regarding the service implementation, didn't know it exists. I just followed the contribution.md. Shouldn't be too difficult to build something testable.

**Comment by MyaLongmire** [comment]
@jacksgt are you interested in reopening your pr or giving this another go?

**Comment by srebhan** [comment]
Is there still interest in this?

**Comment by estigma88** [comment]
Any progress on this? we are searching for a SQS plugin for Telegraf, any clue if there is something out there maintained by someone else we can use?
