### ISSUE TITLE
Windows - Log file on a drive other than C:

### ISSUE THREAD

**Issue by dsvemp** [influxdata/telegraf#6120]
### Proposal:
Hello, on Windows I haven't found a way to make telegraf save its log to a D: drive

### Current behavior:
Log file can be customised (ie "/program files/folder") via the logfile parameter in a configuration file, but only for the C: drive. I'm running it as a Windows Service and it might be due to the context of the console session where the service runs in?

### Desired behavior:
Being able to store the log in other drive letters. IE: //D/Logs/Telegraf.log.txt 

### Use case: 
Although now we can rotate logs with Telegraf, being able to save logs on a different drive might help complying with company standards/policies.

**Comment by danielnelson** [comment]
This should work in the agent section of the configuration, note the single quotes to avoid needing to escape backslashes:
```
[agent]
  logfile = 'D:\Logs\Telegraf.log.txt'
```

**Comment by dsvemp** [comment]
Thanks! Can I suggest you document this somewhere? Thanks again
