### ISSUE TITLE
External plugin interface

### ISSUE THREAD

**Issue by wgrcunha** [influxdata/telegraf#613]
Is there any way to implement external plugin?  Now we can use the exec but is very limited, i want to report fields and tags from the custom plugin.

Maybe implement something like Kapacitor custom functions: https://influxdata.com/blog/announcing-kapacitor-v0-10-udfs/

**Comment by sparrc** [comment]
@wgrcunha What if exec could read line-protocol metrics? https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/

I've been wanting to support this anyways, and it shouldn't be difficult

**Comment by wgrcunha** [comment]
@sparrc Perfect :)
