### ISSUE TITLE
input.kubernetes: kubernetes.cpu.limits & kubernetes.memory.limits

### ISSUE THREAD

**Issue by DavidVog** [influxdata/telegraf#6133]
## Feature Request
Adding kubernetes.cpu.limits & kubernetes.memory.limits for kubernetes_pod_container in the kubernetes input plugin.

### Proposal:
Adding two fields in kubernetes.go:
fields["cpu_usage_limit_nanocores"]
fields["memory_usage_limit_nanocores"]

### Current behavior:
Those two metrics are lacking.

### Desired behavior:
Getting the cpu en memory limit of each pod 

### Use case: 
These two metrics would allow the user to get the percentage of CPU Usage and Memory Usage which would be really usefull when monitoring kubernetes pods

**Comment by glinton** [comment]
@DavidVog where do you acquire those measurements? I checked `/stats/summary` on a kubelet and didn't see any reference to limits on cpu/memory. Do the pods need to be configured with limits for it to show? If you have output from `/stats/summary` that includes these limits, please paste it here and we should be able to get that in, thanks.

**Comment by Disturbing** [comment]
FYI -> you can get this information with kube_invetory: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kube_inventory

**Comment by DavidVog** [comment]
Hi Disturbing,
I know I should have but I didn't reply to my own ticket to say that the kube_inventory plugin gather the data I was looking for.
Thanks for you answer.
