### ISSUE TITLE
Telegraf pushes to Prometheus?

### ISSUE THREAD

**Issue by brightzheng100** [influxdata/telegraf#6147]
## Feature Request

Prometheus follows pull model but it provides PushGateway. While looking through the output plugins, I'm not sure which one is suitable to make it push-able from Telegraf output to Prometheus (through PushGateway)?
Maybe just need some more docs or a new feature request for that?

### Proposal:

Telegraf output plugin -> Prometheus PushGateway?

### Current behavior:

Currently, it's very convenient to use `prometheus client` output plugin to expose `/metrics` endpoint(s) for Prometheus Server to pull.
But exposing endpoints may not always be valid and push model might be more feasible, in some cases (e.g. in NAT topology).

### Desired behavior:

We can simply enable an output plugin to push to PushGateway

### Use case: 

In NAT topology, using SNAT to access external world, including the independent multi-cluster Monitoring Control Plane is common. So we need to aggregate metrics by exposing one single entry point which, in Prometheus world, might be PushGateway.

**Comment by danielnelson** [comment]
I think this issue would be addressed by adding the Prometheus serializer and pairing it with the http output.  I'm going to close this issue and we have an issue open for the serializer in https://github.com/influxdata/telegraf/issues/4414.
