### ISSUE TITLE
Allow Github Enterprise repos

### ISSUE THREAD

**Issue by Esity** [influxdata/telegraf#6162]
## Feature Request
Allow Telegraf to poll Github Enterprise repos. Currently it would appear from the documentation you can only enter repos from github.com

### Proposal:
Add URL variable for the github input plugin so you grab metrics from on prem github

Input Plugin [github](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/github)

**Comment by shanempope** [comment]
@Esity something like this: https://github.com/influxdata/telegraf/pull/6194

**Comment by danielnelson** [comment]
Closed in #6194
