### ISSUE TITLE
Feature request: AMD GPU Metrics Support

### ISSUE THREAD

**Issue by douglasg14b** [influxdata/telegraf#6170]
### Proposal:

Plugin with AMD GPU support.

### Use case:

Same as nvidia-smi use cases, but for AMD GPUs

### More Info

A few libraries that seem to pull metrics from AMD GPUs that might help in the development of a plugin:

* https://github.com/clbr/radeontop
* https://github.com/marazmista/radeon-profile
* https://github.com/GPUOpen-Tools/Radeon-GPUProfiler
* https://github.com/Ricks-Lab/amdgpu-utils

**Comment by mspencerl87** [comment]
would be awesome, if we can do this. I can already monitor everything else. All that's missing is AMD GPUs.

**Comment by leonv024** [comment]
+1

**Comment by zeus86** [comment]
is there currently any real work ongoing on this topic?

**Comment by powersj** [comment]
The [AMD ROCm SMI](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/amd_rocm_smi) plugin I believe covers this request. I am going to close this, but if it is missing support, or something else, please do feel free to open a bug with additional details as to what is missing.

Thanks!
