### ISSUE TITLE
Strait forward way to get the latest release

### ISSUE THREAD

**Issue by hryamzik** [influxdata/telegraf#618]
Can we get any simple way to get the latest stable release (and betas too)? If it already exists please let me know. =)

The common way on github is to put files in releases but these two links are useless:
https://api.github.com/repos/influxdata/telegraf/releases
https://api.github.com/repos/influxdata/telegraf/release/latest

[Tags](https://api.github.com/repos/influxdata/telegraf/tags) have some info:

```json
  {
    "name": "v0.10.1",
    "zipball_url": "https://api.github.com/repos/influxdata/telegraf/zipball/v0.10.1",
    "tarball_url": "https://api.github.com/repos/influxdata/telegraf/tarball/v0.10.1",
    "commit": {
      "sha": "3a64a01f919233ffca85a5941940f0d4a3826ba3",
      "url": "https://api.github.com/repos/influxdata/telegraf/commits/3a64a01f919233ffca85a5941940f0d4a3826ba3"
    }
  }
```

But the real deb url is http://get.influxdb.org/telegraf/telegraf_0.10.1-1_amd64.deb. It's the same for rpm.

**Comment by sparrc** [comment]
@hryamzik In general we just use Amazon S3 to store our releases, I haven't done any investigation into using github for it but it would require us to modify the build process across the InfluxData products. Could you explain why the s3 links (get.influxdb.org) don't work for you?

cc @rossmcdonald

**Comment by hryamzik** [comment]
@sparrc they do work but how can I get the latest one? Is there any listing available?

To be clear: we use ansible for deployments and our roles are used to install the latest software. So I like to put some version and url defining logic inside.

**Comment by sparrc** [comment]
so you are looking for something like: http://get.influxdb.org/telegraf/telegraf_latest_amd64.deb that always has the latest version?

**Comment by rossmcdonald** [comment]
@hryamzik The best way to get the latest stable releases would be to use the [InfluxData repository](https://docs.influxdata.com/influxdb/v0.9/introduction/installation/#installation). You would just run `apt-get install telegraf`/`yum install telegraf` instead of `influxdb`.

I actually have a Telegraf Ansible role [here](https://github.com/rossmcdonald/telegraf) that you can use for reference.

**Comment by hryamzik** [comment]
@rossmcdonald yep, repository is a perfect solution, thank you! I didn't find any information about it in readme.

**Comment by sparrc** [comment]
I'll put a link to the install doc on the README

**Comment by hryamzik** [comment]
@sparrc can you also point to an ansible role, please?
