### ISSUE TITLE
Solr 8 measurements are not saved though they pass the tests

### ISSUE THREAD

**Issue by leonardor** [influxdata/telegraf#6196]
## Feature Request

I have installed Solr 8.1 and Telegraf 1.11.3. The telegraf agent seems too parse/collect the data but they are not shown in the Chronograf dashboard.

### Proposal:

Add a feature to collect and save properly the Solr 8.1 measurements

### Current behavior:

The telegraf agent doesn't collect Solr 8.1 measurements.

### Desired behavior:

The telegraf agent collects Solr 8.1 measurements properly.

### Use case: 

This is the output from the tests:

> solr_admin,core=mycore,host=myhost deleted_docs=24i,max_docs=3821i,num_docs=3797i,size_in_bytes=2770038i 1564727524000000000
> solr_core,core=mycore,handler=searcher,host=myhost deleted_docs=0i,max_docs=0i,num_docs=0i 1564727524000000000
> solr_core,core=mycore,handler=core,host=myhost  deleted_docs=0i,max_docs=0i,num_docs=0i 1564727524000000000
> solr_cache,core=mycore,handler=queryResultCache,host=myhost  cumulative_evictions=0i,cumulative_hitratio=0.25,cumulative_hits=1i,cumulative_inserts=3i,cumulative_lookups=4i,evictions=0i,hitratio=0.25,hits=1i,inserts=3i,lookups=4i,size=3i,warmup_time=0i 1564727524000000000
> solr_cache,core=mycore,handler=fieldValueCache,host=myhost  cumulative_evictions=0i,cumulative_hitratio=0,cumulative_hits=0i,cumulative_inserts=0i,cumulative_lookups=0i,evictions=0i,hitratio=0,hits=0i,inserts=0i,lookups=0i,size=0i,warmup_time=0i 1564727524000000000
> solr_cache,core=mycore,handler=filterCache,host=myhost  cumulative_evictions=0i,cumulative_hitratio=0.62,cumulative_hits=8i,cumulative_inserts=5i,cumulative_lookups=13i,evictions=0i,hitratio=0.62,hits=8i,inserts=5i,lookups=13i,size=5i,warmup_time=0i 1564727524000000000
> solr_cache,core=mycore,handler=documentCache,host=myhost  cumulative_evictions=0i,cumulative_hitratio=0.5,cumulative_hits=32i,cumulative_inserts=32i,cumulative_lookups=64i,evictions=0i,hitratio=0.5,hits=32i,inserts=32i,lookups=64i,size=32i,warmup_time=0i 1564727524000000000

**Comment by danielnelson** [comment]
We should check if the data was written to InfluxDB.  First take a look at the Telegraf logs for any errors.  If you are using systemd on Linux something like this should work:
```
sudo journalctl -e -u telegraf
```

If you don't see any errors then I usually connect to InfluxDB using the `influx` cli tool and poke around a bit:
```
$ influx
> use telegraf
> select * from solr_admin where time > now() - 10m
```

**Comment by leonardor** [comment]
This is the result:

`> use telegraf
Using database telegraf
> select * from solr_admin where time > now() - 10m
name: solr_admin
time | core | deleted_docs | host | max_docs | num_docs | size_in_bytes
=============================================
1564809900000000000 mycore 55                       myhost 3852           3797           2699223
1564809930000000000 mycore 55                       myhost 3852           3797           2699223
1564809960000000000 mycore 55                       myhost 3852           3797           2699223
1564809990000000000 mycore 55                       myhost 3852           3797           2699223
1564810020000000000 mycore 55                       myhost 3852           3797           2699223
1564810050000000000 mycore 55                       myhost 3852           3797           2699223
1564810080000000000 mycore 55                       myhost 3852           3797           2699223
1564810110000000000 mycore 55                       myhost 3852           3797           2699223
1564810140000000000 mycore 55                       myhost 3852           3797           2699223
1564810170000000000 mycore 55                       myhost 3852           3797           2699223
1564810200000000000 mycore 55                       myhost 3852           3797           2699223
1564810230000000000 mycore 55                       myhost 3852           3797           2699223
1564810260000000000 mycore 55                       myhost 3852           3797           2699223
1564810290000000000 mycore 55                       myhost 3852           3797           2699223`

**Comment by glinton** [comment]
What dashboard are you using? Can you show the queries it's running?

**Comment by leonardor** [comment]
I use Chronograf 1.7.10 but as I poke inside it I noticed that it cannot list Solr as a monitored service because it doesn't apparently have a specialized dashboard for Solr to begin with.

**Comment by danielnelson** [comment]
Ahh that makes sense, you will need to make a user defined dashboard in Chronograf to use it with this plugin.
