### ISSUE TITLE
answerInlineQuery doesn't respond neither answer nor any error

### ISSUE THREAD

**Issue by andrey-furman** [influxdata/telegraf#6215]
node v12.6.0
"telegraf": "^3.30.1",

**This code doesn't respond anything:**
* I've read recommendations with an object with `results` property where should be put a collection of results;
* JSON.stringify around the same collection of results also doesn't work.
I've tried both of these cases in different modifications - no avail.

await ctx.answerInlineQuery(ctx.inlineQuery.id, [
      { type: 'article', id: '1', title: 'RESULT 1', input_message_content: 'TEXT 1' },
      { type: 'article', id: '2', title: 'RESULT 2', input_message_content: 'TEXT 2' },
    ])

**Comment by danielnelson** [comment]
I believe you're looking for https://github.com/telegraf/telegraf

**Comment by andrey-furman** [comment]
Of course, I did. These both sources:
http://joxi.ru/p27vP69cKYGGom
http://joxi.ru/Q2KGQDYHLEYYB2
Haven't been sufficient.
await ctx.answerInlineQuery(
      ctx.inlineQuery.id,
      JSON.stringify([
        { type: 'article', id: '1', title: 'RESULT 1', input_message_content: 'TEXT 1' },
        { type: 'article', id: '2', title: 'RESULT 2', input_message_content: 'TEXT 2' },
      ]),
    )
Also doesn't work.
Provide me a sample code with the right data structure.
