### ISSUE TITLE
 to get the tcpdump source and destination ip on influx DB

### ISSUE THREAD

**Issue by Aathi87** [influxdata/telegraf#6222]
Hi Team,

 is there any way  to get the tcpdump source and destination ip at interface level.We have to get the source and destination ip on influx DB.Kindly advise on this.

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
