### ISSUE TITLE
"reply" isn't available for "chosen_inline_result::

### ISSUE THREAD

**Issue by andrey-furman** [influxdata/telegraf#6223]
```javascript
bot.on('chosen_inline_result', async ctx => {
  await ctx.reply('hello, world')
})
```
I receive such error:
Telegraf: "reply" isn't available for "chosen_inline_result::

I want to send a response to the user with the message and a photo. What's causing such weird behaviour? And how to manage it?

**Comment by danielnelson** [comment]
Sorry, this is not the correct Telegraf project, you want https://github.com/telegraf/telegraf.

**Comment by andrey-furman** [comment]
ok, sorry.
