### ISSUE TITLE
Add WhaTap output for application and server monitoring

### ISSUE THREAD

**Issue by whatapdev** [influxdata/telegraf#6228]
### Proposal:
I want to add output plugin.
WhaTap that provides application and server monitoring.
Output plugin for delivering telegraf's collected data to WhaTap server.

https://www.whatap.io

API documentation
https://docs.whatap.io/kr/agent_telegraf/api.html

### Current behavior:
I am developing and testing WhaTap oupt plugin.
Similar to socket_writer. it's pass information to WhaTap over TCP.

### Desired behavior:
pull request. 

### Use case: 
We want to provide people using WhaTap service with various information that can be collected by Telegraf.

**Comment by danielnelson** [comment]
Can you add a link to the API documentation you will be using?

**Comment by whatapdev** [comment]
It does not provide an open api.
Telegraph metrics are converted to bytes and sent over TCP. 
Do I must to provide an API documentation?

**Comment by danielnelson** [comment]
Before we can add a plugin to this repo we will need to be sure that we can maintain the plugin, even if the contributer is no longer available.  So we need documentation available about how the protocol works.

**Comment by whatapdev** [comment]
I have added link to the API documentaion. 

https://docs.whatap.io/kr/agent_telegraf/api.html

**Comment by danielnelson** [comment]
Looks good, I suggest first trying to think about what the configuration would look like in Telegraf, perhaps this is a good starting point:
```toml
[[outputs.whatap]]
  address = "tcp://example.org:1234"
  project_code = "foo"
  license = "abcdef"
```

**Comment by whatapdev** [comment]
whatap's sample config tries to do this.

## You can create a project on the WhaTap site(https://www.whatap.io) 
  ## to get license, project code and server IP information.

  ## WhaTap license. Required
  #license = "xxxx-xxxx-xxxx"

  ## WhaTap project code. Required
  #pcode = 1111

  ## WhaTap server IP. Required
  # Put multiple IPs with / as delimiters. e.g. "1.1.1.1/2.2.2.2"
  #server = "1.1.1.1/2.2.2.2"

  # WhaTap base port 
  # port = 6600

  ## Connection timeout.
  # timeout = "60s"

**Comment by whatapdev** [comment]
Okay. Let's apply the settings that way. Thank you.

**Comment by whatapdev** [comment]
I changed the servers setting.
The link below is the source under test.
https://github.com/whatap/telegraf/tree/master/plugins/outputs/whatap

**Comment by glinton** [comment]
If you open a pull request against us with that branch, linked to this issue, we can review it as well.

**Comment by Jaeyo** [comment]
+1

**Comment by sjwang90** [comment]
Appreciate all the feedback on the interest for this plugin but the Telegraf team has decided to not include this in the internal binary. Please see more info: https://github.com/influxdata/telegraf/pull/6369#issuecomment-1082270441
