### ISSUE TITLE
PowerDNS Recursor: bind: permission denied

### ISSUE THREAD

**Issue by ercpe** [influxdata/telegraf#6229]
### Relevant telegraf.conf:

```
# Read metrics from one or many PowerDNS Recursor servers
[[inputs.powerdns_recursor]]
  ## An array of sockets to gather stats about.
  ## Specify a path to unix socket.
  unix_sockets = ["/var/run/pdns_recursor.controlsocket"]

  ## Socket for Receive
  #socket_dir = "/var/run/"
  ## Socket permissions
  #socket_mode = "0666"
```

### System info:

```Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

```Telegraf 1.11.3 (git: HEAD d6024fd2)```

### Steps to reproduce:

1. Install PowerDNS Recusor
2. Use default config for the Telegraf powerdns_recursor plugin

### Expected behavior:
Should be able to connect to pdns-recursor

### Actual behavior:

The plugin fails with 
```E! [inputs.powerdns_recursor]: Error in plugin: dial unixgram /var/run/pdns_recursor_telegraf7824375062676721865->/var/run/pdns_recursor.controlsocket: bind: permission denied```

no matter which values for

- `socket-group`
- `socket-owner`
- `socket-mode`

in `recursor.conf` or 

- `socket_dir`
- `socket_mode`

in telegraf input configuration. Even 0777 on both sockets don't work.

**Comment by danielnelson** [comment]
I have written updated documention for how to setup this plugin in #6231.  ([rendered version](https://github.com/influxdata/telegraf/blob/75584f537d36a4593eb4ddc7e17e271732f60be4/plugins/inputs/powerdns_recursor/README.md))

Can you test out these instructions and let me know if you have any feedback or still run into problems?

**Comment by ercpe** [comment]
Strange. I'm pretty sure I tried setting `socket_dir` to somewhere else yesterday. Anyway, with `/var/run/pdns` telegraf is able to gather the values and send them off.

Maybe you could add a link to the README in the config snippet generated by `telegraf config` so that other users don't run into the same problem?

**Comment by danielnelson** [comment]
I'll add something directing the user to the documentation, but I'm trying to avoid links in the config.  I know the config is already littered with them, but the problem is they need to point to the master branch and this can cause confusion when using an older Telegraf version.  They really need to point to the release branch but that makes updates a headache.  The solution I'd really like is to have manpages for the plugins.
