### ISSUE TITLE
[Feature Request] Load Average per cpu cores in System Input Plugin

### ISSUE THREAD

**Issue by beliys** [influxdata/telegraf#6233]
## Feature Request

Create additional variables in the System Input Plugin:
load1_percpu = load1 / n_cpus
load5_percpu = load5 / n_cpus
load15_percpu = load15 / n_cpus

### Proposal/Use case:

All servers and virtual machines can have a different number of processor cores and when creating triggers you need to consider this number, but triggers are created immediately for a group of servers and many metric collectors use a metric that contains the result of the calculation `<Load Average> / <N_cores>`.
For example, for zabbix this parameter is called `system.cpu.load [percpu, avg1]` for Diamond - `loadavg.01_normalized`.
It would be nice to have an analogue in telegraf, especially since adding it is not difficult.
As practice shows, storing a little more metrics is cheaper in resources than counting dynamically for each node.

**Comment by danielnelson** [comment]
Thanks for opening a feature request, however I don't think this is a feature we would add.  A few reasons come to mind:
- load average isn't just related to number of cpus, and involves non-cpu tasks.
- we don't tend to send computed stats, and instead leave these for query side.

It should be possible to set this up in Grafana/Chronograf though fairly easily, you may need to switch away from the graphical query builders though.  In the future, we will implement some capability to do this via a processor (likely using the flux language).

**Comment by beliys** [comment]
However, I don't see any reason why you can't add this metric and make it optional - who needs to include it, who doesn't need it - is not will use.
About "load average isn't just related to number of cpus, and involves non-cpu tasks."then Yes it is, but at the same time it is it will allow you to create a universal trigger for all nodes, because LA = 20 for a server with 2 cores and a server with 40 are completely different things. What I'm suggesting is a common practice to smooth out this with 1 trigger to check all the nodes.
About "we don't tend to send calculated stats, and instead leave these for query side.", I already wrote above that in some cases it is more profitable to duplicate metrics (especially if used by clickhouse) than constantly calculate values for a large number of nodes(if you calculate a value for example every 10 seconds for all nodes - this will greatly increase the load on the cpu). 
Adding metric data and making it optional will not be difficult, but it will allow you to use telegraf for more tasks without compromising for current users.

**Comment by danielnelson** [comment]
I agree with you that we should have a solution to calculate this before insertion, I think we should consider a new processor as the right solution to this though.

I'm not sure about Clickhouse specifically, but most of the time series databases we support have a way to perform these types ofcalculations on the database once saving the computation.  For example, with InfluxDB you can use a continuous query.

Adding optional convenience calculations seems like a small change, but when done across the board it doesn't result in a very nice design.

**Comment by beliys** [comment]
Well, I understand you, but could you answer a few questions?
1) How do you now create triggers for monitoring load average on a large number of different servers, if not secret?
2) When is it planned to add a processor to be able to solve this problem?
3) Is there a compromise in the form of temporarily adding this metric as an option until the processor you talked about is implemented? After adding the processor, you can remove the option. It will not take much time to implement, but it will allow you to use telegraf now, but how it will not affect the final design, since in the future you can remove the option (as soon as the processor is implemented). I would be very grateful if possible.

**Comment by danielnelson** [comment]
1. I'm not sure if I'm understanding correctly, but it should be possible to setup a [Continuous Query](https://docs.influxdata.com/influxdb/v1.7/query_language/continuous_queries/).  The runs periodically, runs the calculation, and writes it back to the database.
2. We don't have a concrete date right now, so it could be some time.
3. I could help you make the modification locally and get started building and packaging a custom version of Telegraf, it's pretty easy and then you can make any customization you need.

**Comment by beliys** [comment]
Thank you very much for your answer. I would also like to comment on your answers:
1) we use clickhouse in the `graphite` stack (carbon-c-relay, carbon-clickhouse, clickhouse, graphite-clickhouse, carbonapi, grafana, moira) which has no alternative to `Continuous Query`, also I would like to consider it on the side of the aggregator metrics that would not create additional load on the database.
2) Well, I'll have to wait then
3) I know how you can add this functionality and build a package, but I don’t like the option to create and maintain a fork - we have a fairly small team for this. As a temporary solution we have implemented this via `input.exec`
