### ISSUE TITLE
Regression - Increased CPU usage of telegraf

### ISSUE THREAD

**Issue by cwegener** [influxdata/telegraf#624]
@sparrc After commits 38c4111e6cb2a045d17e4333377b0d56812d3a9c and b97027ac9a87a7c4db5d7341b5c8554aa2a47e93, the CPU utilization of telegraf.exe on Windows has gone up significantly. On my test rig, before this commit CPU utilization of telegraf.exe was at ~0.3% avg. After this commit, CPU utilization went up to ~1.6% avg

The attached screenshot shows the comparison when running telegraf.exe with and without commits 38c4111e6cb2a045d17e4333377b0d56812d3a9c and b97027ac9a87a7c4db5d7341b5c8554aa2a47e93

I haven't tested this on *nix yet.

If somebody has time to look into this for me that would be great, I'm not sure how much time I will be able to spend on telegraf development in the next few days.

![screenshot 2016-01-31 at 8 05 06 pm](https://cloud.githubusercontent.com/assets/2950544/12701202/fc0e584c-c855-11e5-9452-5c2b635ac0d9.png)

**Comment by sparrc** [comment]
I don't understand how these changes could have affected CPU usage, are you sure there isn't another source of the cpu usage on your system?

What is your config? Because that commit only affects the `exec` plugin. And if you're using JSON as the format it shouldn't have any affect at all

**Comment by cwegener** [comment]
I agree. It's definitely a bit strange. Not sure if it is something with my build environment. conf file is attached. I'm running telegraf.exe -config telegraf.conf
(No input or output filters)
Maybe you can try a repro.

[telegraf_conf.txt](https://github.com/influxdata/telegraf/files/111471/telegraf_conf.txt)

**Comment by cwegener** [comment]
I did another test: I built the exact same branch (with the 2 commits reverted) twice in a row. The first build works fine (no elevated CPU usage). The second build has the problem again.
Very weird.

**Comment by cwegener** [comment]
This is pretty strange. Here's the result of another test:
1. check out master in influxdata/telegraf
2. build telegraf.exe 3 consecutive times
== first result: all three builds show the same high CPU usage for telegraf.exe process (number 0 in below screenshot)
3. in inflxudata/telegraf, create a new branch locally (i called it cpu-issue-2)
4. revert commit 38c4111e6cb2a045d17e4333377b0d56812d3a9c
5. build telegraf.exe 4 consecutive times
= second result: all 4 builds of telegraf.exe each show their own unique CPU usage patterns (numbers 1-4 in below screenshot) except the 2nd and 4th build, they show exactly similar CPU usage patterns.

I'm a bit baffled.

Notes: in between each go build, I perform 'go clean -r' and 'gdm restore -f Godeps_Windows'

![screenshot 2016-02-01 at 1 14 05 pm](https://cloud.githubusercontent.com/assets/2950544/12707296/779daf86-c8e6-11e5-9feb-a30bd6fe0bff.png)

**Comment by cwegener** [comment]
@TheFlyingCorpse *ping*. Since you have a Windows build environment too, I was wondering if you can see a similar issue.

**Comment by cwegener** [comment]
Problem solved by deleting all content in the telegraf GOPATH and then cloning master from github.com

Seems that go build doesn't compile consistent binaries when working with multiple branches of telegraf ...
