### ISSUE TITLE
Add Modbus RTUoverTcp input plugin 

### ISSUE THREAD

**Issue by Pradeep-raj544** [influxdata/telegraf#6247]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior: As of now  i can partially find modbus input plugin for Rtu and Tcp here(https://github.com/influxdata/telegraf/pull/6154) 
i think we can develop RtuoverTcp input plugin by refereeing  this code link (https://github.com/goburrow/modbus/pull/42/commits/143d9017f8a269793ca94c876dad48bbe88e4c38) as he implemented RtuoverTcp

### Use case: 
@danielnelson @garciaolais @glinton

**Comment by ssoroka** [comment]
the modbus plugins have been merged since this was opened. Is this still an issue?
