### ISSUE TITLE
FIlestat plugin and super asterisks not working on windows?

### ISSUE THREAD

**Issue by dsvemp** [influxdata/telegraf#6248]
Hello, when trying to use the filestat plugin on windows with the following config, I'm unable to make super asterisks work.

```
[[inputs.filestat]]
  ## Files to gather stats about.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". See https://github.com/gobwas/glob.
  files = ['E:\data\Databases\**wololo_0']
  ## If true, read the entire file and calculate an md5 checksum.
  md5 = false
```
It takes 'E:\data\Databases\**wololo_0' as a literal path, instead of trying to do a recurse search for wololo_0 files. I've tried using double quotes and it didn't help.

Are filestat and super asterisks supported on windows?

Thanks

**Comment by danielnelson** [comment]
They should work, which version of Telegraf are you using?

**Comment by dsvemp** [comment]
Hello,

I've tested it with 1.11.2 and 1.11.4

**Comment by zak-pawel** [comment]
Super asterisk still doesn't work for Windows in Telegraf 1.16.2.

One file in `C:\Temp`
`dir /B C:\Temp`:
```
test.log
```

**Config:**
```
[[inputs.filestat]]
  files = ['C:\temp\**.log']
```

**Output:**
```
2020-11-21T22:07:51Z I! Starting Telegraf
2020-11-21T22:07:51Z I! Loaded inputs: filestat
2020-11-21T22:07:51Z I! Loaded aggregators:
2020-11-21T22:07:51Z I! Loaded processors:
2020-11-21T22:07:51Z I! Loaded outputs: file
2020-11-21T22:07:51Z I! Tags enabled: host=pc
2020-11-21T22:07:51Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"pc", Flush Interval:10s
filestat,file=C:\temp\**.log,host=pc exists=0i 1605996480000000000
filestat,file=C:\temp\**.log,host=pc exists=0i 1605996490000000000
```

**Config with single asterisk:**
```
[[inputs.filestat]]
  files = ['C:\temp\*.log']
```

**Single asterisk works:**
```
2020-11-21T22:12:14Z I! Starting Telegraf
2020-11-21T22:12:14Z I! Loaded inputs: filestat
2020-11-21T22:12:14Z I! Loaded aggregators:
2020-11-21T22:12:14Z I! Loaded processors:
2020-11-21T22:12:14Z I! Loaded outputs: file
2020-11-21T22:12:14Z I! Tags enabled: host=pc
2020-11-21T22:12:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"pc", Flush Interval:10s
filestat,file=C:\temp\test.log,host=pc size_bytes=0i,modification_time=1605996248206700000i,exists=1i 1605996740000000000
```

I believe it is not a problem in `filestat` plugin itself but in `internal/globpath/globpath.go`
I adjusted `internal/globpath/globpath_test.go` to Windows here https://github.com/influxdata/telegraf/pull/8414/commits/0fc291df7c32bfd537033917c8a0ff53c2017a3b and they fail when super asterisk is used.

**Probably super asterisk doesn't work in Windows for all plugins using `internal/globpath/globpath_test.go`:**
- **file**
- **filecount**
- **filestat**
- **logparser**
- **phpfpm**
- **tail**

**Comment by zak-pawel** [comment]
Also, it doesn't work with shashes in config:
```
[[inputs.filestat]]
  files = ['C:/temp/**.log']
```

**Comment by srebhan** [comment]
Works for me with current master and
```toml
[[inputs.filestat]]
  files = ['C:/Windows/Temp/**.log']
```
