### ISSUE TITLE
Processor to create a new metric using other collected metrics

### ISSUE THREAD

**Issue by beliys** [influxdata/telegraf#6254]
## Feature Request
In addition to discussion https://github.com/influxdata/telegraf/issues/6233 create a new Feature Request based on the vision of one of contributors project

### Use case:
All servers and virtual machines can have a different number of processor cores and when creating triggers you need to consider this number, but triggers are created immediately for a group of servers and many metric collectors use a metric that contains the result of the calculation `<Load Average> / <N_cores>`.
For example, for zabbix this parameter is called `system.cpu.load [percpu, avg1]` for Diamond - `loadavg.01_normalized`.
In some cases it is more profitable to duplicate metrics than constantly calculate values for a large number of nodes(if you calculate a value for example every 10 seconds for all nodes - this will greatly increase the load on the cpu).
Personally, I prefer the option with an optional metric in the System Input Plugin(as in request https://github.com/influxdata/telegraf/issues/6233), as it was done in competing solutions, but if it really is bad, it will suit an alternative option in the form of a processor to create a new metric based on the collected metrics on the telegraf side before sending metrics in the database.

**Comment by danielnelson** [comment]
related #3709

**Comment by reimda** [comment]
This issue was opened before the starlark processor was added. It should be possible to do the kinds of things this issue describes in a short starlark script.
