### ISSUE TITLE
TLS support for sqlserver

### ISSUE THREAD

**Issue by GeorgeJahad** [influxdata/telegraf#6260]
## Feature Request
Add TLS support for connecting to sqlserver to the sqlserver input plugin
### Proposal:
The other sql plugins, mysql, and postregres allow this.  Is there any reason why it wasn't added to the sqlserver input plugin?

### Use case: 
Securing the connection to sqlserver.

**Comment by danielnelson** [comment]
I believe this can be done using the connection string in the `address` option.  Here are the [options](https://github.com/denisenkom/go-mssqldb#common-parameters) supported by the driver, could you try the `encrypt` option?  Other related options you might need are `certificate`, `TrustServerCertificate`, and `hostNameInCertificate`.  It does not appear to be possible to set a client certificate for mutual authentication.

It would be nice if we could an an example to the documentation that utilizes this option, please let me know if it works okay so we can do so.

**Comment by GeorgeJahad** [comment]
Thanks very much for the tip.  I'll let you know what we discover.

**Comment by GeorgeJahad** [comment]
it does work; i've created a small documenation pr here: https://github.com/influxdata/telegraf/pull/6409

thanks much!

**Comment by glinton** [comment]
Closed by #6409
