### ISSUE TITLE
No integer and float fields added

### ISSUE THREAD

**Issue by fritzkoelle** [influxdata/telegraf#6264]
### Relevant telegraf.conf:

```
# # Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  ## MQTT broker URLs to be used. The format should be scheme://host:port,
  ## schema can be tcp, ssl, or ws.
  servers = ["tcp://localhost:1883"]
   ## QoS policy for messages
   ##   0 = at most once
   ##   1 = at least once
   ##   2 = exactly once
   ##
   ## When using a QoS of 1 or 2, you should enable persistent_session to allow
   ## resuming unacknowledged messages.
   qos = 0

   ## Connection timeout for initial connection in seconds
   connection_timeout = "30s"

   ## Maximum messages to read from the broker that have not been written by an
   ## output.  For best throughput set based on the number of metrics within
   ## each message and the size of the output's metric_batch_size.
   ##
   ## For example, if each message from the queue contains 10 metrics and the
   ## output metric_batch_size is 1000, setting this to 100 will ensure that a
   ## full batch is collected and the write is triggered immediately without
   ## waiting until the next flush_interval.
   # max_undelivered_messages = 1000

   ## Topics to subscribe to
   topics = [
     	"wr/state"
   ]

   # if true, messages that can't be delivered while the subscriber is offline
   # will be delivered when it comes back (such as on service restart).
   # NOTE: if true, client_id MUST be set
   persistent_session = true
   # If empty, a random client ID will be generated.
   client_id = "telegraf"

   ## username and password to connect MQTT server.
   # username = "telegraf"
   # password = "metricsmetricsmetricsmetrics"

   ## Optional TLS Config
   # tls_ca = "/etc/telegraf/ca.pem"
   # tls_cert = "/etc/telegraf/cert.pem"
   # tls_key = "/etc/telegraf/key.pem"
   ## Use TLS but skip chain & host verification
   # insecure_skip_verify = false

   ## Data format to consume.
   ## Each data format has its own unique set of configuration options, read
   ## more about them here:
   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
#  data_format = "influx"
#  data_format = "value"
#  data_type = "integer"
   data_format = "json"
   #tag_keys = []
  # json_string_fields = [
#	"field1",
#	"field2"
#]

```

### Steps to reproduce:

1. Send JSON message via mqtt to topic "wr/state"
JSON message consists of multiple integer and float fields but NO String fields

### Expected behavior:
Telegraf creates measurement mqtt_consumer
Telegraf writes field keys from mqtt message in measurement
Datatypes of field keys are integer or float

### Actual behavior:
Telegraf does not create the measurement and telegraf does not write any data to the database. But telegraf writes something to the log. See below..
If I uncomment the "json_string_fields" part in the config telegraf creates the measurement and writes the fields into the db. But then the datatype of the fields is string and not integer or float
### Additional info:

2019-08-15T12:14:00Z D! [outputs.influxdb] wrote batch of 16 metrics in 26.218979ms
2019-08-15T12:14:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics.
2019-08-15T12:14:10Z D! [outputs.influxdb] wrote batch of 18 metrics in 19.124126ms
2019-08-15T12:14:10Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics.
2019-08-15T12:14:20Z D! [outputs.influxdb] wrote batch of 18 metrics in 21.001509ms
2019-08-15T12:14:20Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics.

**Comment by danielnelson** [comment]
Can you add an example payload?

**Comment by fritzkoelle** [comment]
msg={"date":"2019:01:28-02:00:40","field1":"0","field2":"6"}

**Comment by fritzkoelle** [comment]
Wrong data type in message. Must look like:
msg={"date":"2019:01:28-02:00:40","field1":0,"field2":6}
