### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [influxdata/telegraf#6271]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by danielnelson** [comment]
I like the idea of this, especially fuzzing our parsers, but the details matter.  Does this introduce a dependency on clang/gcc?  Where does the fuzzing process run, would it be on our CI system or on Fuzzit?  What integrations would need to be added to this repo?

**Comment by yevgenypats** [comment]
@danielnelson good questions. so go-fuzz can run into modes "native"/libFuzzer.
* Currently we best support when the fuzzers are compiled with libFuzzer which means clang needs to be installed (this is just for the compilation of the fuzzers).
* The fuzzing itself is a long term process so it is running on Fuzzit servers without blocking your ci. New fuzzers are built in CircleCI every time new code is pushed to master and the are pushed to Fuzzit servers via our [CLI](https://github.com/fuzzitdev/fuzzit)
* On every PR the fuzzers are built as well in the CI and then we run a quick regression using our CLI and the built fuzzers that runs them locally through all the generated corpus and fixed crashes in the previous step. This should help prevent new/old bugs from making their way to master.

**Comment by yevgenypats** [comment]
@danielnelson friendly ping:) would love to know the status on that and if this is something worth working on.

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab
