### ISSUE TITLE
SNMP input is overwriting instead of append when using oid_index_length field parameters. 

### ISSUE THREAD

**Issue by gcezaralmeida** [influxdata/telegraf#6275]
### Relevant telegraf.conf:
```toml
[[inputs.snmp]]
  agents = ["ip"]
  version = 2
  community = "storage-r"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "1.3.6.1.6.3.10.2.1.3.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "serialNumber"
    oid = "ENTITY-MIB::entPhysicalSerialNum.10"

  [[inputs.snmp.table]]
    name = "flogi"
    inherit_tags = [ "hostname"]
    index_as_tag = true

    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "portName"
      oid = "1.3.6.1.4.1.9.9.289.1.1.5.1.3"
      conversion = "hwaddr"
      oid_index_length = 1
```

### System info:

TELEGRAF_VERSION=1.11.3
DockerVersion: 18.06.1-ce
Pulling Cisco Nexus Switches 

### Steps to reproduce:

1. Start telegraf with "telegraf --config /etc/telegraf/telegraf.conf --test | grep -i flogi"

### Expected behavior:
Should return 85 entries that I can confirm with switch commands. But is returning only 61. 

### Actual behavior:
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/46,index=22728704 portName="10:00:00:00:c9:f4:74:fe" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/1,index=22544384 portName="10:00:00:00:c9:f4:72:5a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/45,index=22200320 portName="10:00:00:00:c9:f4:71:90" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/27,index=18456576 portName="10:00:00:00:c9:f4:72:c2" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/25,index=17924096 portName="21:00:00:24:ff:33:20:1c" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/15,index=22077440 portName="10:00:00:00:c9:d9:33:f4" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/26,index=23171072 portName="10:00:00:00:c9:d9:30:d0" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/1,index=18350080 portName="10:00:00:00:c9:cc:5b:b8" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/2,index=17829888 portName="10:00:00:00:c9:cc:6c:ea" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc6/25,index=19496960 portName="21:00:00:24:ff:33:20:fc" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/43,index=22192128 portName="20:03:00:11:0a:02:76:fe" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/27,index=23175168 portName="10:00:00:00:c9:d9:01:fa" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/1,index=18874368 portName="21:00:00:24:ff:4d:68:79" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/14,index=22597632 portName="10:00:00:00:c9:d9:31:38" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/26,index=18976768 portName="10:00:00:00:c9:f4:72:2f" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/27,index=17932288 portName="10:00:00:00:c9:f4:79:06" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/1,index=17825792 portName="10:00:00:00:c9:d2:43:a0" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/14,index=23121920 portName="10:00:00:00:c9:d9:36:3e" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/15,index=23126016 portName="10:00:00:00:c9:d9:36:90" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/13,index=18923520 portName="21:00:00:24:ff:33:21:06" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/13,index=23117824 portName="10:00:00:00:c9:d9:31:f2" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/2,index=18354176 portName="10:00:00:00:c9:d3:14:d2" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/41,index=23232512 portName="20:02:00:11:0a:02:76:fe" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/46,index=22204416 portName="10:00:00:00:c9:f4:72:a0" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/28,index=22130688 portName="10:00:00:00:c9:d2:2a:b6" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/17,index=22609920 portName="10:00:00:00:c9:ae:9c:a4" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/26,index=18452480 portName="10:00:00:00:c9:f4:74:37" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/5,index=22036480 portName="10:00:00:00:c9:d7:77:5a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/7,index=22044672 portName="10:00:00:00:c9:d7:79:1f" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/1,index=22020096 portName="10:00:00:00:c9:f4:70:d0" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc10/13,index=21544960 portName="21:00:00:24:ff:33:1e:f0" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/15,index=22601728 portName="10:00:00:00:c9:d9:33:e2" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc6/13,index=19447808 portName="10:00:00:00:c9:d9:30:2c" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/27,index=22126592 portName="10:00:00:00:c9:d2:2a:36" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/13,index=18399232 portName="21:00:00:24:ff:27:ea:92" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/28,index=17936384 portName="10:00:00:00:c9:f4:72:42" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/46,index=19058688 portName="10:00:00:00:c9:f4:72:8e" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/16,index=22081536 portName="10:00:00:00:c9:d9:36:36" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/15,index=18931712 portName="10:00:00:00:c9:c4:53:3c" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/5,index=23085056 portName="10:00:00:00:c9:fa:37:e4" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc3/13,index=17874944 portName="21:00:00:24:ff:27:ed:4a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/25,index=22118400 portName="10:00:00:00:c9:d2:2a:42" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc6/1,index=19398656 portName="10:00:00:00:c9:f8:ca:35" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc9/16,index=21032960 portName="10:00:00:00:c9:d9:38:a2" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/17,index=22085632 portName="10:00:00:00:c9:a1:bf:e6" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/13,index=22069248 portName="10:00:00:00:c9:d9:33:b6" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc5/16,index=18935808 portName="10:00:00:00:c9:c4:56:42" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/5,index=22560768 portName="10:00:00:00:c9:d7:79:4f" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/16,index=22605824 portName="10:00:00:00:c9:d9:36:f6" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc9/13,index=21020672 portName="10:00:00:00:c9:d9:36:aa" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/26,index=22122496 portName="10:00:00:00:c9:d9:37:6a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc4/28,index=18460672 portName="10:00:00:00:c9:f4:77:2a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/45,index=22724608 portName="10:00:00:00:c9:f4:71:42" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/28,index=22654976 portName="10:00:00:00:c9:d9:38:2a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/16,index=23130112 portName="10:00:00:00:c9:d2:2a:3e" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/14,index=22073344 portName="10:00:00:00:c9:d4:f0:7a" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/1,index=23068672 portName="10:00:00:00:c9:f4:72:60" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc11/47,index=22208512 portName="10:00:00:00:c9:c0:d6:14" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc13/25,index=23166976 portName="10:00:00:00:c9:d9:37:aa" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/27,index=22650880 portName="10:00:00:00:c9:d9:32:e4" 1565962741000000000
> flogi,agent_host=switch01,host=host1,hostname=switch01,ifDescr=fc12/25,index=22642688 portName="10:00:00:00:c9:d9:38:a4" 1565962741000000000
### Additional info:

When I remove "oid_index_length" I can get all 85 entries. But if I do that I can't match index with IF-MIB::ifDescr. What I could check is that telegraf is overwriting data if same index when using oid_index_length. 
Example:
I Hide oid_index_length in telegraf.conf file to get all 85 entries. We could check that index number is bigger.

> flogi,agent_host=switch1,host=host1,index=18350080.811.7537729 portName="10:00:00:00:c9:cc:5b:b8" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23166976.811.7537569 portName="10:00:00:00:c9:d9:37:aa" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22650880.811.7537536 portName="10:00:00:00:c9:d9:32:e4" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22200320.801.7536672 portName="10:00:00:00:c9:f4:71:90" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22073344.811.7536928 portName="10:00:00:00:c9:d4:f0:7a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22560768.801.7536992 portName="10:00:00:00:c9:d7:79:4f" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18460672.807.7536768 portName="10:00:00:00:c9:f4:77:2a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.24315077 portName="21:00:00:24:ff:33:21:06" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22654976.811.7537505 portName="10:00:00:00:c9:d9:38:2a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23130112.811.7537312 portName="10:00:00:00:c9:d2:2a:3e" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.24314337 portName="21:00:00:24:ff:27:ed:04" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22208512.801.7536832 portName="10:00:00:00:c9:c0:d6:14" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22601728.811.7537088 portName="10:00:00:00:c9:d9:33:e2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.24315076 portName="21:00:00:24:ff:27:e9:be" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.24315106 portName="21:00:00:24:ff:33:20:f6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22192128.807.7537536 portName="20:03:00:11:0a:02:76:fe" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22081536.811.7536961 portName="10:00:00:00:c9:d9:36:36" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.24315074 portName="21:00:00:24:ff:27:e9:d6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18874368.811.7536641 portName="21:00:00:24:ff:4d:68:79" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22122496.811.7537281 portName="10:00:00:00:c9:d9:37:6a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17874944.811.24315042 portName="21:00:00:24:ff:33:21:32" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17825792.811.7537792 portName="10:00:00:00:c9:d2:43:a0" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22204416.801.7536704 portName="10:00:00:00:c9:f4:72:a0" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.24314343 portName="21:00:00:24:ff:27:ea:94" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.24314346 portName="21:00:00:24:ff:27:ea:92" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18935808.801.7537120 portName="10:00:00:00:c9:c4:56:42" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314339 portName="21:00:00:24:ff:33:21:00" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18354176.811.7537760 portName="10:00:00:00:c9:d3:14:d2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18452480.807.7536801 portName="10:00:00:00:c9:f4:74:37" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22126592.811.7537344 portName="10:00:00:00:c9:d2:2a:36" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22642688.811.7537408 portName="10:00:00:00:c9:d9:38:a4" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23175168.811.7537665 portName="10:00:00:00:c9:d9:01:fa" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314340 portName="21:00:00:24:ff:27:ea:9a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22044672.801.7536960 portName="10:00:00:00:c9:d7:79:1f" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=21544960.811.24314849 portName="21:00:00:24:ff:33:1e:f0" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19447808.805.7537184 portName="10:00:00:00:c9:d9:30:2c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314342 portName="21:00:00:24:ff:27:ed:5c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22036480.801.7536928 portName="10:00:00:00:c9:d7:77:5a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314344 portName="21:00:00:24:ff:33:20:1c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22724608.801.7536736 portName="10:00:00:00:c9:f4:71:42" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.7537888 portName="20:15:00:05:33:8e:39:18" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.7537120 portName="20:11:00:05:33:74:eb:d6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22544384.811.7536768 portName="10:00:00:00:c9:f4:72:5a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.24315105 portName="21:00:00:24:ff:33:21:12" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22605824.811.7537057 portName="10:00:00:00:c9:d9:36:f6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22020096.811.7536736 portName="10:00:00:00:c9:f4:70:d0" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17874944.811.24315041 portName="21:00:00:24:ff:33:21:20" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18931712.801.7536865 portName="10:00:00:00:c9:c4:53:3c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23171072.811.7537600 portName="10:00:00:00:c9:d9:30:d0" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.24314345 portName="21:00:00:24:ff:27:ec:1e" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23085056.801.7537024 portName="10:00:00:00:c9:fa:37:e4" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.7537856 portName="20:11:00:05:33:8e:39:18" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23121920.811.7537184 portName="10:00:00:00:c9:d9:36:3e" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18976768.807.7536832 portName="10:00:00:00:c9:f4:72:2f" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22085632.807.7537600 portName="10:00:00:00:c9:a1:bf:e6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19398656.807.7537664 portName="10:00:00:00:c9:f8:ca:35" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19058688.801.7536800 portName="10:00:00:00:c9:f4:72:8e" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17874944.811.7537824 portName="20:11:00:05:33:8e:27:35" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=21544960.811.7537632 portName="20:15:00:05:33:8e:27:35" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22609920.807.7537632 portName="10:00:00:00:c9:ae:9c:a4" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.7537376 portName="20:15:00:05:33:74:eb:d6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22597632.811.7537025 portName="10:00:00:00:c9:d9:31:38" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=21020672.805.7537216 portName="10:00:00:00:c9:d9:36:aa" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18456576.807.7536704 portName="10:00:00:00:c9:f4:72:c2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22069248.811.7536832 portName="10:00:00:00:c9:d9:33:b6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.24315108 portName="21:00:00:24:ff:27:eb:f6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22077440.811.7536864 portName="10:00:00:00:c9:d9:33:f4" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.24315073 portName="21:00:00:24:ff:33:21:ac" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314341 portName="21:00:00:24:ff:27:ed:28" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17936384.807.7536736 portName="10:00:00:00:c9:f4:72:42" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23232512.801.7537088 portName="20:02:00:11:0a:02:76:fe" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17874944.811.24315043 portName="21:00:00:24:ff:27:ed:4a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23117824.811.7537153 portName="10:00:00:00:c9:d9:31:f2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23068672.811.7536800 portName="10:00:00:00:c9:f4:72:60" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18399232.811.24314338 portName="21:00:00:24:ff:27:e9:dc" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=23126016.811.7537217 portName="10:00:00:00:c9:d9:36:90" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.24315109 portName="21:00:00:24:ff:33:20:fc" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=18923520.811.24315075 portName="21:00:00:24:ff:33:20:e2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=19496960.811.24315107 portName="21:00:00:24:ff:33:20:f2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17932288.807.7536672 portName="10:00:00:00:c9:f4:79:06" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22118400.811.7537249 portName="10:00:00:00:c9:d2:2a:42" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22728704.801.7536768 portName="10:00:00:00:c9:f4:74:fe" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17829888.811.7537696 portName="10:00:00:00:c9:cc:6c:ea" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=21032960.811.7537920 portName="10:00:00:00:c9:d9:38:a2" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=22130688.811.7537441 portName="10:00:00:00:c9:d2:2a:b6" 1565964930000000000

Index 17924096 is port fc3/25 in my switch and have these 6 entries. 

root@93bf45b1c16c:/# telegraf --config /etc/telegraf/telegraf.conf --test | grep -i 17924096
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314339 portName="21:00:00:24:ff:33:21:00" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314340 portName="21:00:00:24:ff:27:ea:9a" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314342 portName="21:00:00:24:ff:27:ed:5c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314344 portName="21:00:00:24:ff:33:20:1c" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.7537376 portName="20:15:00:05:33:74:eb:d6" 1565964930000000000
> flogi,agent_host=switch1,host=host1,index=17924096.811.24314341 portName="21:00:00:24:ff:27:ed:28" 1565964930000000000

But if I include  "oid_index_length = 1" and restart telegraf I will get only one entry. 

root@93bf45b1c16c:/# telegraf --config /etc/telegraf/telegraf.conf --test | grep -i 17924096
> flogi,agent_host=switch1,host=host1,index=17924096 portName="21:00:00:24:ff:33:20:1c" 1565965408000000000

**Comment by danielnelson** [comment]
It seems like you really want here is to join two tables, something we don't currently support (#3076).  The best you could probably do is to collect the two tables separately:
```
  [[inputs.snmp.table]]
    name = "flogi"
    inherit_tags = [ "hostname"]
    index_as_tag = true
    oid = "IF-MIB::ifTable

  [[inputs.snmp.table]]
    name = "flogi"
    inherit_tags = [ "hostname"]
    index_as_tag = true
    oid = "1.3.6.1.4.1.9.9.289.1.1.5"
```

Still I'm not sure the right information would even be available since I don't have this device.  If you collect the two tables separately what column would you "join" on?

**Comment by gcezaralmeida** [comment]
I guess that I couldn't explain well what I want. The Problem is when I use "oid_index_length = 1" to "cut" the index. Telegraf is overwriting instead of append. Example:

When I comment "#oid_index_length = 1" in Telegraf.conf all data came, look at index Number 17924096. 
index=17924096.811.24314339 field1=value1 1565964930000000000
index=17924096.811.24314340 field1=value2 1565964930000000000
index=17924096.811.24314342 field1=value3 1565964930000000000
index=17924096.811.24314344 field1=value4 1565964930000000000
index=17924096.811.7537376 field1=value5 1565964930000000000
index=17924096.811.24314341 field1=value6 1565964930000000000

When I use "oid_index_length = 1" in Telegraf.conf I get only this result. 
index=17924096 field1=value6 1565964930000000000

The index is in the way that I need but the others values are gone. I get only the last one. So I'm supposing that they are being overwriting.

**Comment by gcezaralmeida** [comment]
Forget about the ifDescr Field table. Could "oid_index_length = 1" result like this?
index=17924096 field1=value1 1565964930000000000
index=17924096 field1=value2 1565964930000000000
index=17924096 field1=value3 1565964930000000000
index=17924096 field1=value4 1565964930000000000
index=17924096 field1=value5 1565964930000000000
index=17924096 field1=value6 1565964930000000000

**Comment by danielnelson** [comment]
> The index is in the way that I need but the others values are gone. I get
> only the last one. So I'm supposing that they are being overwriting.

Yes I believe they are being overwritten. InfluxDB allows a single value per measurement + tagset + field name + timestamp.  When it is written to the database they will collapse onto each other.

Telegraf doesn't have any restrictions here, and you should see all entries when you run with `--test`.

> Could "oid_index_length = 1" result like this?
> index=17924096 field1=value1 1565964930000000000
> index=17924096 field1=value2 1565964930000000000
> index=17924096 field1=value3 1565964930000000000
> index=17924096 field1=value4 1565964930000000000
> index=17924096 field1=value5 1565964930000000000
> index=17924096 field1=value6 1565964930000000000

I'm still a bit confused, isn't this what it's doing now?

**Comment by danielnelson** [comment]
Let me know if you need more help.
