### ISSUE TITLE
SQL Server Input Plugin - Add replication related performance counters 

### ISSUE THREAD

**Issue by biohazardxxx** [influxdata/telegraf#6281]
## Feature Request
To monitor the performance of database replication it would be good to add replication related performance counters to be collected by the SQL Server Input Plugin.

### Proposal:
Add counters from objects
SQLServer:Replication Agents
SQLServer:Replication Dist.
SQLServer:Replication Logreader
SQLServer:Replication Snapshot
from sys.dm_os_performance_counters
query:
```
SELECT	DISTINCT
		RTrim(spi.object_name) object_name,
		RTrim(spi.counter_name) counter_name,
		RTrim(spi.instance_name) instance_name,
		spi.cntr_value,
		spi.cntr_type
FROM	sys.dm_os_performance_counters AS spi
WHERE	(
		object_name like 'SQLServer:Replication%'
		or 
		object_name like 'Snapshot:%'
		)
```
### Current behavior:
Counters of this objects are not collected.
### Desired behavior:
This counters will be added.
### Use case:
Currently replication status and performance counters can't be included via telegraf and additional tools or workarounds are necessary.

**Comment by danielnelson** [comment]
@denzilribeiro @m82labs Would you be able to evaluate this feature request?

**Comment by denzilribeiro** [comment]
Would have to do a PR with the change as that would be a part of the larger query containing perf counters as proposed counter is a subset of the larger query. I have to make another change will do both perhaps within next week.

**Comment by denzilribeiro** [comment]
@biohazardxxx  - do you monitor snapshot often given it is just sporadic one time repl initialization? I get the replication counters( Log reader / Distribution agent / Merge Agent) - more curious as it is a line between bloating collection for every capture v/s actual need.

**Comment by sjwang90** [comment]
@denzilribeiro Is this feature something the SQL Server team is interested in implementing with the plugin? We have had another user also recently ask for this feature for additional replication metrics to be collected by the plugin.
