### ISSUE TITLE
Collecting logs from Beginning when ever the new logs are inserting.

### ISSUE THREAD

**Issue by cvijaykumarreddy463** [influxdata/telegraf#6282]
![image](https://user-images.githubusercontent.com/52567633/63329593-18c04b00-c2e7-11e9-9b90-619dbac2e94e.png)

 System info:

Telegraf v1.10.3, windows Server 2016, InfluxDB v1.7.6

 Steps to reproduce:

1. Setup the telegraf config file(Contains Tail Plugin).
2. Give the path of the log file.
3. Insert any log and check in influx.exe whether the measurement is creating or not and the logs are inserting or not.
4. Measurement is created and Logs data also inserted(expected)
5. Again If we insert a log then telegraf is recollecting all the previous logs(unexpected).

 Expected behavior:
If we insert any number of new logs telegraf need to collect only one time each log.
 Actual behavior:
It is recollecting the logs data when ever the new log is generate.
 Additional info:
Log file like this:

![image](https://user-images.githubusercontent.com/52567633/63330945-866d7680-c2e9-11e9-95e1-38162e501b3d.png)

Please suggest me the better solution.

Thanks and Regards
Vijay

**Comment by danielnelson** [comment]
Can you tell me a bit about how you are inserting new logs?  Also, can you show me the recollected data in InfluxDB using the influx.exe command?

Also if you are running Telegraf on Windows you should set `watch_method = "poll"`.  Not related to this issue but
