### ISSUE TITLE
[INPUT][COUCHBASE] Additional fields required

### ISSUE THREAD

**Issue by Moep90** [influxdata/telegraf#6292]
## Feature Request
Extend fields for Couchbase Input.

### Proposal:
Based on the blogpost by Couchbase for monitoring nodes/clusters: https://blog.couchbase.com/monitoring-couchbase-cluster/
I would like to ask if we could extend the fields to what couchbsae recommends to be monitoried.

### Current behavior:
just a few fields are available currently:
```
memory_free
memory_total
quota_percent_used
ops_per_sec
disk_fetches
item_count
disk_used
data_used
mem_used
```
### Desired behavior:
Recommended to monitor by Couchbase
```
current:
memory_free
memory_total
quota_percent_used
ops_per_sec
disk_fetches
item_count
disk_used
data_used
mem_used

+ Extensions:
couch_docs_actual_disk_size
ep_cache_miss_rate
couch_docs_fragmentation
ep_bg_fetched
vb_active_resident_items_ratio
ep_queue_size
vb_num_eject_replicas
ep_warmup_value_count
vb_active_curr_items
ep_cache_miss_rate
couch_docs_fragmentation
ep_queue_size
vb_active_resident_items_ratio
curr_connections
curr_items_tot
ep_bg_fetched
ep_diskqueue_drain
ep_diskqueue_fill
vb_replica_eject
ep_oom_errors
ep_queue_size
ep_tmp_oom_errors
[etc...]
```

### Use case:
1. Running applications which required a couchbase to run. Especially on migration we are in need to monitor all of these statistics on a central dashboard.

**Comment by danielnelson** [comment]
It would be good to have these added, there is an existing issue open with some of these already, #4152, could you comment on this issue and we can track any work over there.
