### ISSUE TITLE
vSphere Plugin: vSphere version 4.1.0

### ISSUE THREAD

**Issue by xiongmao71** [influxdata/telegraf#6305]
### Relevant telegraf.conf:

```toml
[[inputs.vsphere]]
   vcenters = [ "https://<vSphereIP>/sdk" ]
   username = "username"
   password = "password"
   vm_metric_include = [
     "cpu.demand.average",
     "cpu.idle.summation",
     "cpu.latency.average",
     "cpu.readiness.average",
     "cpu.ready.summation",
     "cpu.run.summation",
     "cpu.usagemhz.average",
     "cpu.used.summation",
     "cpu.wait.summation",
     "mem.active.average",
     "mem.granted.average",
     "mem.latency.average",
     "mem.swapin.average",
     "mem.swapinRate.average",
     "mem.swapout.average",
     "mem.swapoutRate.average",
     "mem.usage.average",
     "mem.vmmemctl.average",
     "net.bytesRx.average",
     "net.bytesTx.average",
     "net.droppedRx.summation",
     "net.droppedTx.summation",
     "net.usage.average",
     "power.power.average",
     "virtualDisk.numberReadAveraged.average",
     "virtualDisk.numberWriteAveraged.average",
     "virtualDisk.read.average",
     "virtualDisk.readOIO.latest",
     "virtualDisk.throughput.usage.average",
     "virtualDisk.totalReadLatency.average",
     "virtualDisk.totalWriteLatency.average",
     "virtualDisk.write.average",
     "virtualDisk.writeOIO.latest",
     "sys.uptime.latest",
   ]
   host_metric_include = [
     "cpu.coreUtilization.average",
     "cpu.costop.summation",
     "cpu.demand.average",
     "cpu.idle.summation",
     "cpu.latency.average",
     "cpu.readiness.average",
     "cpu.ready.summation",
     "cpu.swapwait.summation",
     "cpu.usage.average",
     "cpu.usagemhz.average",
     "cpu.used.summation",
     "cpu.utilization.average",
     "cpu.wait.summation",
     "disk.deviceReadLatency.average",
     "disk.deviceWriteLatency.average",
     "disk.kernelReadLatency.average",
     "disk.kernelWriteLatency.average",
     "disk.numberReadAveraged.average",
     "disk.numberWriteAveraged.average",
     "disk.read.average",
     "disk.totalReadLatency.average",
     "disk.totalWriteLatency.average",
     "disk.write.average",
     "mem.active.average",
     "mem.latency.average",
     "mem.state.latest",
     "mem.swapin.average",
     "mem.swapinRate.average",
     "mem.swapout.average",
     "mem.swapoutRate.average",
     "mem.totalCapacity.average",
     "mem.usage.average",
     "mem.vmmemctl.average",
     "net.bytesRx.average",
     "net.bytesTx.average",
     "net.droppedRx.summation",
     "net.droppedTx.summation",
     "net.errorsRx.summation",
     "net.errorsTx.summation",
     "net.usage.average",
     "power.power.average",
     "storageAdapter.numberReadAveraged.average",
     "storageAdapter.numberWriteAveraged.average",
     "storageAdapter.read.average",
     "storageAdapter.write.average",
     "sys.uptime.latest",
   ]
cluster_metric_include = [] ## if omitted or empty, all metrics are collected
datastore_metric_include = [] ## if omitted or empty, all metrics are collected
datacenter_metric_include = [] ## if omitted or empty, all metrics are collected
max_query_objects = 64
max_query_metrics = 64
force_discover_on_init = true
use_int_samples = true
insecure_skip_verify = true
```

### System info:

Telegraf version 1.11.4 (git: HEAD d9ca76e4)
vSphere 4.1.0 build 9225676
Windows 2008 R2 build 7601 (updated)
### Steps to reproduce:

1. Checked if connection from Telegraf server to vSphere sdk is working
2. Configured vSphere plugin as per configuration enclosed (I have ommitted commented lines)
3. Restarted Telegraf service
4. Checked logs for errors

### Expected behavior:
Logs don't contain relevant errors and data is retrieved from vSphere sdk
### Actual behavior:
vSphere data is not retrieved and following errors are logged in the systems (both telegraf and vSphere I put just a sample because the errors are repeated indefinitely):

telegraf logs
2019-08-22T08:12:50Z D! [inputs.vsphere]: Creating client: vim
2019-08-22T08:12:50Z D! [outputs.influxdb] wrote batch of 21 metrics in 16.967733ms
2019-08-22T08:12:50Z D! [outputs.influxdb] buffer fullness: 22 / 10000 metrics. 
2019-08-22T08:12:50Z E! [inputs.vsphere]: Error in plugin: 400 Bad Request
2019-08-22T08:12:50Z E! [inputs.vsphere]: Error in plugin: 400 Bad Request

vSphere logs
[2019-08-22 08:12:50.216 00972 error 'SoapAdapter'] Client sent us an invalid SOAP request: at line number 1, no element found
[2019-08-22 08:12:50.280 03024 error 'SoapAdapter'] Client sent us an invalid SOAP request: at line number 1, no element found
### Additional info:
Sometimes the "400 Bad Request" in telegraf logs is followed by a "Error in plugin: Post https://<vSphereIP>/sdk: EOF" and only a couple of times this morning I've seen a "Error in plugin: Post https://<vSphereIP>/sdk: net/http: HTTP/1.x transport connection broken: write tcp <TelegrafIP>:41900-><vSphereIP>:443: write: broken pipe".

**Comment by prydin** [comment]
vSphere 4.1 is not supported as its official end of support life was in May 2014. Please refer to this EOL announcement: https://kb.vmware.com/s/article/2039567#targetText=The%20End%20of%20Availability%20of,Guidance%20remains%20May%2021%2C%202016.
