### ISSUE TITLE
Log Warning or Error in Influxdb?

### ISSUE THREAD

**Issue by qindj** [influxdata/telegraf#631]
Dears:

Does `telegraf` have the ability to write plugins' errors in influxdb?

For example, i'm using SNMP input plugin ,when a host is offline, it shows me "Error in input [snmp]: Error reading from UDP xxxxx" , can this error message be wrote into influxdb?

thanks and regards!

**Comment by sparrc** [comment]
It could be, why do you want it?

**Comment by qindj** [comment]
With that function, I can wrote errors into influxdb for example "error_logs", and use kapacitor to catch and alert

**Comment by sparrc** [comment]
I think this would be better as a use-case for a logstreamer input plugin #102
