### ISSUE TITLE
dpkg: error processing package telegraf

### ISSUE THREAD

**Issue by sourceindex** [influxdata/telegraf#632]
Hi,

im using the infruxdb debian repository on jessie, installed telegraph some versions ago and using it for a while now. 

Now im trying to upgrade the package and getting following error:

    Need to get 0 B/8,260 kB of archives. After unpacking 31.0 MB will be used.
    Selecting previously unselected package telegraf.
    (Reading database ... 74106 files and directories currently installed.)
    Preparing to unpack .../telegraf_0.10.1-1_amd64.deb ...
    Unpacking telegraf (0.10.1-1) ...
    Setting up telegraf (0.10.1-1) ...
    Failed to execute operation: File exists
    dpkg: error processing package telegraf (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     telegraf
    E: Sub-process /usr/bin/dpkg returned an error code (1)
    Failed to perform requested operation on package.  Trying to recover:
    Setting up telegraf (0.10.1-1) ...
    Failed to execute operation: File exists
    dpkg: error processing package telegraf (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     telegraf

    D000100: filesavespackage ... also in adwaita-icon-theme:all
    D000100: filesavespackage ... also in libgnome2-common:all
    D000100: filesavespackage ...  is 3rd package
    D000100: filesavespackage ...  taken -- no save
    D000100: filesavespackage file '/usr/share/locale/fy' package adwaita-icon-theme:all
    D000100: filesavespackage ... also in adwaita-icon-theme:all
    D000100: filesavespackage ... not taken -- save !
    D000010: process_archive looking for overwriting '/usr/lib/telegraf'
    D000010: process_archive looking for overwriting '/usr/lib/telegraf/scripts'
    D000010: process_archive looking for overwriting '/usr/lib/telegraf/scripts/init.sh'
    D000010: process_archive looking for overwriting '/usr/lib/telegraf/scripts/telegraf.service'
    D000010: process_archive looking for overwriting '/usr/bin/telegraf'
    D000010: process_archive looking for overwriting '/usr/share/doc/telegraf'
    D000010: process_archive looking for overwriting '/usr/share/doc/telegraf/changelog.Debian.gz'
    D000010: process_archive looking for overwriting '/etc/logrotate.d/telegraf'
    D000010: process_archive looking for overwriting '/etc/telegraf/telegraf.conf'
    D000010: process_archive looking for overwriting '/var/log/telegraf'
    D000010: ensure_pathname_nonexisting '/usr.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/lib.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/lib/telegraf.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/lib/telegraf/scripts.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/lib/telegraf/scripts/init.sh.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/lib/telegraf/scripts/telegraf.service.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/bin.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/bin/telegraf.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/share.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/share/doc.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/share/doc/telegraf.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/usr/share/doc/telegraf/changelog.Debian.gz.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/etc.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/etc/logrotate.d.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/etc/telegraf.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/var.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/var/log.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/var/log/telegraf.dpkg-tmp'
    D000010: ensure_pathname_nonexisting '/var/lib/dpkg/tmp.ci'
    D000010: ensure_pathname_nonexisting running rm -rf '/var/lib/dpkg/tmp.ci'
    D000010: ensure_pathname_nonexisting '/var/lib/dpkg/reassemble.deb'
    D000001: process queue pkg telegraf:amd64 queue.len 0 progress 1, try 1
    D000040: checking dependencies of telegraf:amd64 (- <none>)
    D000040: ok 2 msgs >><<
    D000040:     checking Breaks
    Setting up telegraf (0.10.1-1) ...
    D000001: deferred_configure updating conffiles
    D000200: conffderef in='/etc/logrotate.d/telegraf' current working='/etc/logrotate.d/telegraf'
    D000200: conffderef nonexistent
    D000020: deferred_configure '/etc/logrotate.d/telegraf' (= '/etc/logrotate.d/telegraf') useredited=-1 distedited=-1 what=24
    D000200: conffderef in='/etc/telegraf/telegraf.conf' current working='/etc/telegraf/telegraf.conf'
    D000200: conffderef nonexistent
    D000020: deferred_configure '/etc/telegraf/telegraf.conf' (= '/etc/telegraf/telegraf.conf') useredited=-1 distedited=-1 what=24
    D000002: fork/exec /var/lib/dpkg/info/telegraf.postinst ( configure  )
    Failed to execute operation: File exists
    dpkg: error processing package telegraf (--install):
     subprocess installed post-installation script returned error exit status 1
    D000001: ensure_diversions: same, skipping
    Errors were encountered while processing:
     telegraf

I think something might be wrong in the package definitions?!

Greetings.

**Comment by rossmcdonald** [comment]
@sourceindex Thanks for reporting. Can't say I've ever seen that error before, but it looks like something went wrong in the postinst script:

```
D000002: fork/exec /var/lib/dpkg/info/telegraf.postinst ( configure  )
Failed to execute operation: File exists
dpkg: error processing package telegraf (--install):
 subprocess installed post-installation script returned error exit status 1
```

I'll spin up a Jessie box and see if I can reproduce. What version of Telegraf were you upgrading from?

**Comment by sourceindex** [comment]
Hi Ross,

thanks for the hint. I had a look at the postscript and the latest changes and systemd came to my mind. After there wasn't  a systemd configfile povidet with the last package, i put my own, what wasn't a problem. 

Running the postfile pointed directly to the problem: 
```
root@xxxxxxxx:~# bash -x  /var/lib/dpkg/info/telegraf.postinst 
+ BIN_DIR=/usr/bin
+ LOG_DIR=/var/log/telegraf
+ SCRIPT_DIR=/usr/lib/telegraf/scripts
+ LOGROTATE_DIR=/etc/logrotate.d
+ id telegraf
+ [[ 0 -ne 0 ]]
+ chown -R -L telegraf:telegraf /var/log/telegraf
+ [[ -L /etc/init.d/telegraf ]]
+ [[ ! -f /etc/default/telegraf ]]
+ [[ ! -d /etc/telegraf/telegraf.d ]]
+ [[ -f /etc/redhat-release ]]
+ [[ -f /etc/debian_version ]]
+ which systemctl
+ [[ 0 -eq 0 ]]
+ install_systemd
+ cp -f /usr/lib/telegraf/scripts/telegraf.service /lib/systemd/system/telegraf.service
+ systemctl enable telegraf
Failed to execute operation: File exists
```
checking again:

```
root@xxxxxxxx:~# systemctl enable telegraf
Failed to execute operation: File exists
```

disable

```
root@xxxxxxxx:~# systemctl disable telegraf
Removed symlink /etc/systemd/system/multi-user.target.wants/telegraf.service.
Removed symlink /etc/systemd/system/telegraf.service.
```
and re enable again

```
root@xxxxxxxx:~# systemctl enable telegraf
Created symlink from /etc/systemd/system/telegraf.service to /lib/systemd/system/telegraf.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/telegraf.service to /lib/systemd/system/telegraf.service.
root@xxxxxxxx:~# echo $?
0
```
Im not shure how to handle such a mix of layer8 stuff.

Thanks for the help and great work u do!!!

Greetings,
Sebastian
