### ISSUE TITLE
GJSON Syntax still using #[…] because Go < v1.3.0

### ISSUE THREAD

**Issue by jlsam** [influxdata/telegraf#6327]
### Relevant telegraf.conf:

```toml
##   https://github.com/tidwall/gjson#path-syntax
  json_query = 'result.#[ipfsId="foobar"]'
```

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
GJSON within Telegraf use the new notation #(...)
### Actual behavior:
GJSON within Telegraf still uses the  notation #[...]
### Additional info:
Go or GJSON version needs to be updated to at least 1.3.0
See https://github.com/tidwall/gjson#path-syntax

**Comment by danielnelson** [comment]
This has been done in [1.12.0-rc1](https://github.com/influxdata/telegraf/releases/tag/1.12.0-rc1), can you try it out and let us know how it goes?  I'll update the link to a specific tag version.

**Comment by danielnelson** [comment]
- master gjson 1.3.0 558c8254786d625807cd2dc19db3db0604b9d673
- release-1.12 gjson 1.3.0 dbf7c7354c4126c4354ad0ab89d9d7e10cf33877
- release-1.11 gjson 1.1.2 747b136466cfe31084ef0ec5fc24ffb2aabba8c9
