### ISSUE TITLE
Database creation failed, too many open files

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#6338]
```
Sep 03 16:43:10 node2 telegraf[20859]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:148 +0x145
Sep 03 16:43:10 node2 telegraf[20859]: github.com/influxdata/telegraf/agent.(*Agent).Run(0xc820020090, 0xc82016c0c0, 0x0, 0x0)
Sep 03 16:43:10 node2 telegraf[20859]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:376 +0xa84
Sep 03 16:43:10 node2 telegraf[20859]: main.main()
Sep 03 16:43:10 node2 telegraf[20859]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:269 +0x25f2
Sep 03 16:43:10 node2 telegraf[20859]: goroutine 17 [syscall, 312 minutes, locke
Sep 03 16:43:10 node2 telegraf[20859]: 2019/09/03 16:43:10 PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
Sep 03 16:43:10 node2 telegraf[20859]: 2019/09/03 16:43:10 Gathered metrics, (10s interval), from 8 inputs in 26.281929ms
Sep 03 16:43:10 node2 telegraf[20859]: 2019/09/03 16:43:10 Database creation failed: Get http://localhost:8086/query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+telegraf: dial tcp [::1]:8086: socket: too many open files
Sep 03 16:43:10 node2 telegraf[20859]: 2019/09/03 16:43:10 Error writing to output [influxdb]: Could not write to any InfluxDB serv
```

**Comment by danielnelson** [comment]
The "too many open files" error could potentially be a legitimate error depending on the configuration and system setup.  However, the stack trace is definitely an issue, can you get the rest of the stack trace from higher above in the logfile?

**Comment by fcddk** [comment]
Sep 04 18:09:50 node2 telegraf[55626]: 2019/09/04 18:09:50 Gathered metrics, (10s interval), from 8 inputs in 445.158µs
Sep 04 18:09:50 node2 telegraf[55626]: 2019/09/04 18:09:50 FATAL: Input [cpu] panicked: runtime error: index out of range, Stack:
Sep 04 18:09:50 node2 telegraf[55626]: goroutine 101335 [running]:
Sep 04 18:09:50 node2 telegraf[55626]: github.com/influxdata/telegraf/agent.panicRecover(0xc8200cbef0)
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:94 +0xa9
Sep 04 18:09:50 node2 telegraf[55626]: github.com/shirou/gopsutil/cpu.parseStatLine(0x106e880, 0x0, 0x1, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:169 +0x9df
Sep 04 18:09:50 node2 telegraf[55626]: github.com/shirou/gopsutil/cpu.CPUTimes(0x101ef00, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:49 +0x2e3
Sep 04 18:09:50 node2 telegraf[55626]: github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).CPUTimes(0x17da928, 0x101, 
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/ps.go:4
Sep 04 18:09:50 node2 telegraf[55626]: github.com/influxdata/telegraf/plugins/inputs/system.(*CPUStats).Gather(0xc8200cbe90, 0x7f20
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/cpu.go:
Sep 04 18:09:50 node2 telegraf[55626]: github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc820c2fad0, 0xc82016a84
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:137 +0x432
Sep 04 18:09:50 node2 telegraf[55626]: created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
Sep 04 18:09:50 node2 telegraf[55626]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:141 +0x442
Sep 04 18:09:50 node2 telegraf[55626]: goroutine 1 [runnable]:
Sep 04 18:09:50 node2 telegraf[55626]: syscall.Syscall(0x1, 0x2, 0xc820087600, 0x52, 0x52, 0x52, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Sep 04 18:09:50 node2 telegraf[55626]: syscall.write(0x2, 0xc820087600, 0x52, 0x900, 0x5, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x5f
Sep 04 18:09:50 node2 telegraf[55626]: syscall.Write(0x2, 0xc820087600, 0x52, 0x900, 0x9, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/syscall/syscall_unix.go:176 +0x4d
Sep 04 18:09:50 node2 telegraf[55626]: os.(*File).write(0xc820020018, 0xc820087600, 0x52, 0x900, 0x0, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/os/file_unix.go:232 +0xaa
Sep 04 18:09:50 node2 telegraf[55626]: os.(*File).Write(0xc820020018, 0xc820087600, 0x52, 0x900, 0x17b3b20, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/os/file.go:139 +0x8a
Sep 04 18:09:50 node2 telegraf[55626]: log.(*Logger).Output(0xc82005a0a0, 0x2, 0xc8212d6ec0, 0x3e, 0x0, 0x0)
Sep 04 18:09:50 node2 telegraf[55626]: /usr/local/go/src/log/log.go
Sep 04 18:09:50 node2 telegraf[55626]: 2019/09/04 18:09:50 PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and 
Sep 04 18:09:50 node2 telegraf[55626]: 2019/09/04 18:09:50 Database creation failed: Get http://localhost:8086/query?db=&q=CREATE+D
Sep 04 18:09:50 node2 telegraf[55626]: 2019/09/04 18:09:50 Error writing to output [influxdb]: Could not write to any InfluxDB serv

**Comment by danielnelson** [comment]
This looks like a quite old version of Telegraf, does this error still occur if you update to either 1.11.5 or newer?
