### ISSUE TITLE
RabbitMQ: collect local node only

### ISSUE THREAD

**Issue by puckpuck** [influxdata/telegraf#6340]
## Feature Request

Have RabbitMQ input plugin only collect stats from local node.

### Current behavior:

Currently to limit the node to collect from you must specify the node name(s) as part of the config.  If no node is specified stats for all nodes are collected.  In a multi-node environment, where collection is setup for each node you will end up with the same stats collected N times (N = number of nodes)

### Desired behavior:

Include an option to limit collection to the local node only.

### Use case: 

In a multi-node HA environment where some nodes can be re-created dynamically, Telegraf will be setup to collect metrics from each node in order to ensure data is collected.  In this scenario it is desirable to have collection only for local node and limit duplication of metrics.

**Comment by danielnelson** [comment]
Is there a way to know which node is the one we are talking to?  I don't think the node name necessarily is the same as the host connected to.
