### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by reuvygroovy** [influxdata/telegraf#6341]
Hi
When trying to import this grafana dashboard
https://grafana.com/grafana/dashboards/409

it doesn't seem to reference any of the data from the collector. Could it be the dashboard is working on the version 1 metrics? Or is there a new dashboard version and/or other dashboards that reference this collector's data?

**Comment by danielnelson** [comment]
That one does work with the version 1 metrics.  I suggest trying the dashboards here: https://github.com/tboggiano/grafana
