### ISSUE TITLE
Add the ability to include AWS instance name as a tag to cloudwatch data

### ISSUE THREAD

**Issue by baruchih-amdocs** [influxdata/telegraf#6343]
on EC2 service we are not getting the Instance name , 
We get instance ID which is making it hard to represent in a graph since the viewers will not be able to understand it clearly.
Is there an option to config the plugin to get the instance name?

**Comment by danielnelson** [comment]
I agree this would be very useful.  It looks that implementing it would require reading the instance tags and unfortunately this functionality is not provided by the Cloudwatch API, and cannot be done generally across all types of metrics.

I think the right way to approach this is with the processors in https://github.com/influxdata/telegraf/pull/4710, however we need to sort out a solution for allowing processors to work asyncronously without blocking the internal metric flow before we can add these.

**Comment by baruchih-amdocs** [comment]
Totally agree,
Will u put on backlog issues?

**Comment by danielnelson** [comment]
Yes

**Comment by sspaink** [comment]
Looks like https://github.com/influxdata/telegraf/pull/8707 might have addressed this, @baruchih-amdocs does the AWS instance name get added now?
