### ISSUE TITLE
telegraf 1.12 debian wheezy package : depend on GLIBC_2.14

### ISSUE THREAD

**Issue by aderumier** [influxdata/telegraf#6344]
Hi,

last telegraf 1.12 debian wheezy package seem to have been build with GLIBC_2.14

`/usr/bin/telegraf: /lib/x86_64-linux-gnu/libc.so.6: version` GLIBC_2.14' not found (required by /usr/bin/telegraf)`

debian wheeze libc6 package is 2.13

It's working fine with previous version.

**Comment by jwaversveld** [comment]
I'm experiencing the same problem on systems with CentOS 6.

**Comment by danielnelson** [comment]
Here are builds with the fix from #6349:

- [telegraf-1.12.0~8838f6fd-0.x86_64.rpm](https://40086-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0~8838f6fd-0.x86_64.rpm)
- [telegraf-1.12.0~8838f6fd_linux_amd64.tar.gz](https://40086-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0~8838f6fd_linux_amd64.tar.gz)
- [telegraf_1.12.0~8838f6fd-0_amd64.deb](https://40086-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.12.0~8838f6fd-0_amd64.deb)
- [telegraf-1.12.0~8838f6fd-static_linux_amd64.tar.gz](https://40086-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.12.0~8838f6fd-static_linux_amd64.tar.gz)
