### ISSUE TITLE
Not able to collect a few metrics from vsphere.

### ISSUE THREAD

**Issue by anrav** [influxdata/telegraf#6352]
### Relevant telegraf.conf:

```toml

```

### Steps to reproduce:

1. Enable following metrics in toml file.
config.hardware.thin.Enabled
config.hardware.disk.Space 
hardware.cpuinfo.num.CpuCores 
 mem.host.provisioned 
mem.guest.provisioned 
mem.guest.usage 
net.transmit.demand.average 
net.receive.demand.average 
net.demand is unknown.
net.PacketsPerSec 

2. ...

### Expected behavior:

All metrics needs to be collected.

### Actual behavior:

Metric name config.hardware.num.Cpu is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name config.hardware.thin.Enabled is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name config.hardware.disk.Space is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name hardware.cpuinfo.num.CpuCores is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.host.provisioned is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.guest.provisioned is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.guest.usage is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.guest.demand is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.balloonPct is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.host.active is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.reservation.used is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.effective.limit is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.host.usage is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.host.demand is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.host.demand.reservation is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.reservation.used is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name mem.effective.limit is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name net.transmit.demand.average is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name net.receive.demand.average is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name net.demand is unknown. Will not be collected
2019-09-04T14:59:30Z W! [inputs.vsphere] Metric name net.PacketsPerSec is unknown. Will not be collected

### Additional info:

Telegraf - 1.11.4
vsphere version - 6.0
Enabled - Stats level 3 on vsphere.

**Comment by anrav** [comment]
Telegraf.conf:


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "300s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000
 ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 20000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.

  urls = ["http://a.b.c.d:8086"]

  ## The target database for metrics; will be created as needed.
  ## For UDP url endpoint database needs to be configured on server side.
  database = "telegraf_vsphere"

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
  # skip_database_creation = false

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""


[[inputs.vsphere]]
vcenters = ["abc"] # required
username = "xyz"  # required
password =  "Xyz*()"  # required

#timeout = "60s"

## Plugin Settings
### separator character to use for measurement and field names (default: "_")
## separator = "_"
#
### number of objects to retreive per query for realtime resources (vms and hosts)
### set to 64 for vCenter 5.5 and 6.0 (default: 256)
max_query_objects = 64
#
### number of metrics to retreive per query for non-realtime resources (clusters and datastores)
### set to 64 for vCenter 5.5 and 6.0 (default: 256)
max_query_metrics = 64
#
### number of go routines to use for collection and discovery of objects and metrics, must not greater than 8
collect_concurrency = 5
#
discover_concurrency = 5
#
### whether or not to force discovery of new objects on initial gather call before collecting metrics
### when true for large environments this may cause errors for time elapsed while collecting metrics
### when false (default) the first collection cycle may result in no or limited metrics while objects are discovered
##force_discover_on_init = false
insecure_skip_verify = true


System info: 

Centos 7.

**Comment by danielnelson** [comment]
Is this your full vsphere configuration?  You mentioned enabling metrics in the TOML config, are you still doing this?

**Comment by anrav** [comment]
Yes, We are using toml. Remaining metrics are being collected except the above. Toml holds the following.

vm_include = [ "/*/vm/**"]
   vm_metric_include = [
     "cpu.demand.average",
     "cpu.idle.summation",
     "cpu.latency.average",
     "cpu.readiness.average",
     "cpu.ready.summation",
     "cpu.run.summation",
     "cpu.usagemhz.average",
     "cpu.used.summation",
     "cpu.wait.summation",
     "config.hardware.num.Cpu",
     "config.hardware.thin.Enabled",
     "config.hardware.disk.Space",
     "hardware.cpuinfo.num.CpuCores",
     "mem.host.provisioned",
     "mem.guest.provisioned",
     "mem.guest.usage",
     "mem.guest.demand",
     "mem.balloonPct",
     "mem.host.active",
     "mem.reservation.used",
     "mem.effective.limit",
     "mem.granted.average",
     "mem.latency.average",
     "mem.swapin.average",
     "mem.swapinRate.average",
     "mem.swapout.average",
     "mem.swapoutRate.average",
     "mem.usage.average",
     "mem.vmmemctl.average",
     "mem.vmmemctltarget.average",
     "mem.host.usage",
     "mem.host.demand",
     "mem.host.demand.reservation",
     "mem.granted.average",
     "mem.reservation.used",
     "mem.effective.limit",
     "net.bytesRx.average",
     "net.bytesTx.average",
     "net.droppedRx.summation",
     "net.droppedTx.summation",
     "net.usage.average",
     "net.transmit.demand.average",
     "net.receive.demand.average",
     "net.demand",
     "net.usage.average",
     "net.transmitted.average",
     "net.received.average",
     "net.PacketsPerSec",
     "power.power.average",

**Comment by anrav** [comment]
Closed by accident. Remaing metics.

"virtualDisk.numberReadAveraged.average",
     "virtualDisk.numberWriteAveraged.average",
     "virtualDisk.read.average",
     "virtualDisk.readOIO.latest",
     "virtualDisk.throughput.usage.average",
     "virtualDisk.totalReadLatency.average",
     "virtualDisk.totalWriteLatency.average",
     "virtualDisk.write.average",
     "virtualDisk.writeOIO.latest",
     "sys.uptime.latest",
   ]
   # vm_metric_exclude = [] ## Nothing is excluded by default
    vm_instances = true ## true by default
 ## Hosts
   ## Typical host metrics (if omitted or empty, all metrics are collected)

host_include = [ "/*/host/**"]

host_metric_include = [
     "cpu.coreUtilization.average",
     "cpu.costop.summation",
     "cpu.demand.average",
     "cpu.idle.summation",
     "cpu.latency.average",
     "cpu.readiness.average",
     "cpu.ready.summation",
     "cpu.swapwait.summation",
     "cpu.usage.average",
     "cpu.usagemhz.average",
     "cpu.used.summation",
     "cpu.utilization.average",
     "cpu.wait.summation",
     "disk.deviceReadLatency.average",
     "disk.deviceWriteLatency.average",
     "disk.kernelReadLatency.average",
     "disk.kernelWriteLatency.average",
     "disk.numberReadAveraged.average",
     "disk.numberWriteAveraged.average",
     "disk.read.average",
     "disk.totalReadLatency.average",
     "disk.totalWriteLatency.average",
     "disk.write.average",
     "datastore.read.average",
     "datastore.totalReadLatency.average",
     "mem.reservation.used",
     "mem.effective.limit",
     "mem.granted.average",
     "mem.active.average",
     "mem.latency.average",
     "mem.state.latest",
     "mem.swapin.average",
     "mem.swapinRate.average",
     "mem.swapout.average",
     "mem.swapoutRate.average",
     "mem.totalCapacity.average",
     "mem.usage.average",
     "mem.vmmemctl.average",
     "net.bytesRx.average",
     "net.bytesTx.average",
     "net.droppedRx.summation",
     "net.droppedTx.summation",
     "net.errorsRx.summation",
     "net.errorsTx.summation",
     "net.usage.average",
     "power.power.average",
     "storageAdapter.numberReadAveraged.average",
     "storageAdapter.numberWriteAveraged.average",


etc..

**Comment by danielnelson** [comment]
This means that some of these metrics specified do not exist on the server:
```
W! [inputs.vsphere] Metric name hardware.cpuinfo.num.CpuCores is unknown. Will not be collected
```

How did you decide to add this metric?  I don't find relevant results when I enter it into a search engine.  Take a look at this document for a way to get a list of available [metrics](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md), or just update to use only the listed metrics.

**Comment by anrav** [comment]
Added this metrics based on documentation.
https://docs.vmware.com/en/vRealize-Operations-Manager/6.7/com.vmware.vcom.metrics.doc/GUID-1322F5A4-DA1D-481F-BBEA-99B228E96AF2.html.

Under VirtualMachine we do have these metrics. So, thought that these should be available in telegraf as well.

**Comment by danielnelson** [comment]
I can see how that would be confusing, but it doesn't look like they will work.  Stick to the list of metrics for now or if you really want to look closely use the `govc` command to get the most detailed values.

**Comment by anrav** [comment]
Thank you.
