### ISSUE TITLE
Solr Core monitoring

### ISSUE THREAD

**Issue by dream4r1** [influxdata/telegraf#6355]
Hello,

Is it possible to configure solr core monitoring with wild card ?. Quick test did not work let us know if there is an feature available or will this has to be an enhancement request

``` 
### Configs
[[inputs.solr]]
  servers = ["http://localhost:8983"]
   cores = ["aaaa_*"]

 ### Testing
 telegraf -config solr.conf -test
2019-09-05T20:45:39Z E! Error in plugin [inputs.solr]: solr: API responded with status-code 500, expected 200, url http://localhost:8983/solr/aaaa_*/admin/mbeans?stats=true&wt=json&cat=CORE&cat=QUERYHANDLER&cat=UPDATEHANDLER&cat=CACHE
2019-09-05T20:45:39Z E! Error in plugin [inputs.solr]: no core metric data to unmarshall
2019-09-05T20:45:39Z E! Error in plugin [inputs.solr]: no query handler metric data to unmarshall
2019-09-05T20:45:39Z E! Error in plugin [inputs.solr]: no update handler metric data to unmarshall
2019-09-05T20:45:39Z E! Error in plugin [inputs.solr]: no cache metric data to unmarshall

```

**Comment by ilyam8** [comment]
@dream4r1 it looks like no

> Use cores from configuration if exists, else use cores from server

https://github.com/influxdata/telegraf/blob/be7c71a39bd07a97303daf52a4abb5c9529f3d27/plugins/inputs/solr/solr.go#L189-L195

**Comment by dream4r1** [comment]
Thanks for the quick reply. Do you mean I should set something up on `/etc/default/telegraf` file and  define variable in "telegraf.conf to retrieve from there ?. So the issue is we create new cores every month and we want telegraf to dynamically pick that up as we do not require monitoring on older cores.

**Comment by ilyam8** [comment]
> or will this has to be an enhancement request

This. From what i see it is very easy to implement.

**Comment by dream4r1** [comment]
Hmm could you provide an guidance on how this could be dynamically update cores or have something like ```cores = ["aaaa_`date +%b_%Y`"]```

**Comment by danielnelson** [comment]
Keeping in line with how we do this on other plugins we could setup pair of a include/exclude lists:
```
cores_include = ["aaaa_*"]
cores_exclude = ["aaaa_not_this_one"]
```

This wouldn't allow you to filter based on date though, for this we would normally require an outside tool to update the configuration and send a SIGHUP.

**Comment by dream4r1** [comment]
Thanks for the follow-up. We are not using Solr anymore so fine with closing unless if someone else requested similar.
