### ISSUE TITLE
500 Internal Server from influx when pushing mysql stats

### ISSUE THREAD

**Issue by ralidousti** [influxdata/telegraf#636]
I have:

telegraf-0.10.0-1
galera-3-3.11 (mysql)
influxdb-0.9.6.1

When telegraf is pushing the mysql stats into influx I receive 500 internal server errors (see below). When this happens I get to see the following in influx logs. Not sure if this is an influx or telegraf problem. If I misplaced the issue, my apologies.

INFLUX LOG
`
[write] 2016/02/02 17:59:20 write failed for shard 228 on node 1: field overflow

[write] 2016/02/02 17:59:20 write failed for shard 228 on node 2: error code 1: write shard 228: field overflow

[write] 2016/02/02 17:59:20 write failed for shard 228 on node 3: error code 1: write shard 228: field overflow

[http] 2016/02/02 17:59:20 127.0.0.1 - USERXYZ [02/Feb/2016:17:59:20 -0500] POST /write?consistency=&db=monitoring&precision=s&rp= HTTP/1.1 500 65 - InfluxDBClient 9856ba6a-ca00-11e5-b81e-000000000000 7.221882ms
`

HTTP TRAFFIC:
`
mysql,dc=BRN,host=db1-lgsqbrn1,server=127.0.0.1:3306 aborted_clients=289i,aborted_connects=17720i,bytes_received=6998410010i,bytes_sent=35366903507i,commands_admin_commands=0i,commands_alter_db=0i,commands_alter_db_upgrade=0i,commands_alter_event=0i,commands_alter_function=0i,commands_alter_procedure=0i,commands_alter_server=0i,commands_alter_table=85i,commands_alter_tablespace=0i,commands_alter_user=0i,commands_analyze=0i,commands_assign_to_keycache=0i,commands_begin=1339i,commands_binlog=0i,commands_call_procedure=0i,commands_change_db=21i,commands_change_master=0i,commands_check=0i,commands_checksum=0i,commands_commit=0i,commands_create_db=8i,commands_create_event=0i,commands_create_function=0i,commands_create_index=0i,commands_create_procedure=0i,commands_create_server=0i,commands_create_table=48i,commands_create_trigger=0i,commands_create_udf=0i,commands_create_user=3i,commands_create_view=0i,commands_dealloc_sql=0i,commands_delete=9987601i,commands_delete_multi=0i,commands_do=0i,commands_drop_db=3i,commands_drop_event=0i,commands_drop_function=0i,commands_drop_index=0i,commands_drop_procedure=0i,commands_drop_server=0i,commands_drop_table=46i,commands_drop_trigger=0i,commands_drop_user=0i,commands_drop_view=0i,commands_empty_query=0i,commands_execute_sql=0i,commands_flush=6i,commands_get_diagnostics=0i,commands_grant=9i,commands_ha_close=0i,commands_ha_open=0i,commands_ha_read=0i,commands_help=0i,commands_insert=10074682i,commands_insert_select=0i,commands_install_plugin=0i,commands_kill=0i,commands_load=0i,commands_lock_binlog_for_backup=0i,commands_lock_tables=43i,commands_lock_tables_for_backup=0i,commands_optimize=0i,commands_preload_keys=0i,commands_prepare_sql=0i,commands_purge=0i,commands_purge_archived=0i,commands_purge_archived_before_date=0i,commands_purge_before_date=0i,commands_release_savepoint=0i,commands_rename_table=0i,commands_rename_user=0i,commands_repair=0i,commands_replace=0i,commands_replace_select=0i,commands_reset=0i,commands_resignal=0i,commands_revoke=0i,commands_revoke_all=0i,commands_rollback=0i,commands_rollback_to_savepoint=0i,commands_savepoint=0i,commands_select=52610378i,commands_set_option=11787489i,commands_show_binlog_events=0i,commands_show_binlogs=0i,commands_show_charsets=0i,commands_show_client_statistics=0i,commands_show_collations=0i,commands_show_create_db=0i,commands_show_create_event=0i,commands_show_create_func=0i,commands_show_create_proc=0i,commands_show_create_table=9i,commands_show_create_trigger=0i,commands_show_databases=14i,commands_show_engine_logs=0i,commands_show_engine_mutex=0i,commands_show_engine_status=0i,commands_show_errors=0i,commands_show_events=0i,commands_show_fields=69i,commands_show_function_code=0i,commands_show_function_status=0i,commands_show_grants=9i,commands_show_index_statistics=0i,commands_show_keys=0i,commands_show_master_status=0i,commands_show_open_tables=0i,commands_show_plugins=0i,commands_show_privileges=0i,commands_show_procedure_code=0i,commands_show_procedure_status=0i,commands_show_processlist=0i,commands_show_profile=0i,commands_show_profiles=0i,commands_show_relaylog_events=0i,commands_show_slave_hosts=0i,commands_show_slave_status=0i,commands_show_slave_status_nolock=0i,commands_show_status=11672018i,commands_show_storage_engines=0i,commands_show_table_statistics=0i,commands_show_table_status=9i,commands_show_tables=26i,commands_show_thread_statistics=0i,commands_show_triggers=9i,commands_show_user_statistics=0i,commands_show_variables=2i,commands_show_warnings=0i,commands_signal=0i,commands_slave_start=0i,commands_slave_stop=0i,commands_stmt_close=53533i,commands_stmt_execute=25546768i,commands_stmt_fetch=0i,commands_stmt_prepare=15596357i,commands_stmt_reprepare=18i,commands_stmt_reset=0i,commands_stmt_send_long_data=0i,commands_truncate=0i,commands_uninstall_plugin=0i,commands_unlock_binlog=0i,commands_unlock_tables=43i,commands_update=6i,commands_update_multi=0i,commands_xa_commit=0i,commands_xa_end=0i,commands_xa_prepare=0i,commands_xa_recover=0i,commands_xa_rollback=0i,commands_xa_start=0i,created_tmp_disk_tables=224i,created_tmp_files=8i,created_tmp_tables=11672501i,handler_commit=71158658i,handler_delete=9987601i,handler_discover=0i,handler_external_lock=51099394i,handler_mrr_init=0i,handler_prepare=60183630i,handler_read_first=46i,handler_read_key=15480201i,handler_read_last=0i,handler_read_next=0i,handler_read_prev=0i,handler_read_rnd=1152i,handler_read_rnd_next=688782430i,handler_rollback=2670i,handler_savepoint=0i,handler_savepoint_rollback=0i,handler_update=4721i,handler_write=687228392i,innodb_available_undo_logs=128i,innodb_background_log_sync=7352610i,innodb_buffer_pool_bytes_data=39174144i,innodb_buffer_pool_bytes_dirty=0i,innodb_buffer_pool_dump_status=0i,innodb_buffer_pool_load_status=0i,innodb_buffer_pool_pages_LRU_flushed=0i,innodb_buffer_pool_pages_data=2391i,innodb_buffer_pool_pages_dirty=0i,innodb_buffer_pool_pages_flushed=37477881i,innodb_buffer_pool_pages_free=5774i,innodb_buffer_pool_pages_made_not_young=0i,innodb_buffer_pool_pages_made_young=0i,innodb_buffer_pool_pages_misc=26i,innodb_buffer_pool_pages_old=862i,innodb_buffer_pool_pages_total=8191i,innodb_buffer_pool_read_ahead=0i,innodb_buffer_pool_read_ahead_evicted=0i,innodb_buffer_pool_read_ahead_rnd=0i,innodb_buffer_pool_read_requests=1907158159i,innodb_buffer_pool_reads=170i,innodb_buffer_pool_wait_free=0i,innodb_buffer_pool_write_requests=163651564i,innodb_checkpoint_age=7438i,innodb_checkpoint_max_age=80826164i,innodb_current_row_locks=0i,innodb_data_fsyncs=51601426i,innodb_data_pending_fsyncs=0i,innodb_data_pending_reads=0i,innodb_data_pending_writes=0i,innodb_data_read=2887680i,innodb_data_reads=187i,innodb_data_writes=85323415i,innodb_data_written=1263249102336i,innodb_dblwr_pages_written=37477881i,innodb_dblwr_writes=1564135i,innodb_deadlocks=0i,innodb_descriptors_memory=8000i,innodb_have_atomic_builtins=0i,innodb_history_list_length=3629i,innodb_ibuf_discarded_delete_marks=0i,innodb_ibuf_discarded_deletes=0i,innodb_ibuf_discarded_inserts=0i,innodb_ibuf_free_list=0i,innodb_ibuf_merged_delete_marks=0i,innodb_ibuf_merged_deletes=0i,innodb_ibuf_merged_inserts=0i,innodb_ibuf_merges=0i,innodb_ibuf_segment_size=2i,innodb_ibuf_size=1i,innodb_log_waits=0i,innodb_log_write_requests=22773042i,innodb_log_writes=44850984i,innodb_lsn_current=11493249826i,innodb_lsn_flushed=11493249826i,innodb_lsn_last_checkpoint=11493242388i,innodb_master_thread_active_loops=4332458i,innodb_master_thread_idle_loops=3020153i,innodb_max_trx_id=36956792i,innodb_mem_adaptive_hash=2643552i,innodb_mem_dictionary=725367i,innodb_mem_total=137363456i,innodb_mutex_os_waits=1690632i,innodb_mutex_spin_rounds=80338944i,innodb_mutex_spin_waits=7470341i,innodb_num_open_files=27i,innodb_oldest_view_low_limit_trx_id=0i,innodb_os_log_fsyncs=46264559i,innodb_os_log_pending_fsyncs=0i,innodb_os_log_pending_writes=0i,innodb_os_log_written=34455210496i,innodb_page_size=16384i,innodb_pages_created=2222i,innodb_pages_read=169i,innodb_pages_written=37477881i,innodb_purge_trx_id=36956792i,innodb_purge_undo_no=0i,innodb_read_views_memory=272i,innodb_row_lock_current_waits=0i,innodb_row_lock_time=0i,innodb_row_lock_time_avg=0i,innodb_row_lock_time_max=0i,innodb_row_lock_waits=0i,innodb_rows_deleted=9987601i,innodb_rows_inserted=10164170i,innodb_rows_read=15520533i,innodb_rows_updated=2i,innodb_s_lock_os_waits=1757449i,innodb_s_lock_spin_rounds=53181331i,innodb_s_lock_spin_waits=1803477i,innodb_truncated_status_writes=0i,innodb_x_lock_os_waits=59321i,innodb_x_lock_spin_rounds=6789764i,innodb_x_lock_spin_waits=310844i,key_blocks_not_flushed=0i,key_blocks_unused=6694i,key_blocks_used=4i,key_read_requests=65i,key_reads=9i,key_write_requests=17i,key_writes=17i,open_files=46i,open_streams=0i,open_table_definitions=38i,open_tables=56i,opened_files=1324i,opened_table_definitions=204i,opened_tables=178i,qcache_free_blocks=0i,qcache_free_memory=0i,qcache_hits=0i,qcache_inserts=0i,qcache_lowmem_prunes=0i,qcache_not_cached=0i,qcache_queries_in_cache=0i,qcache_total_blocks=0i,queries=124265913i,slow_queries=3i,table_locks_immediate=25549696i,table_locks_waited=0i,table_open_cache_hits=41145976i,table_open_cache_misses=177i,table_open_cache_overflows=0i,threads_cached=7i,threads_connected=40i,threads_created=259140i,threads_running=1i 1454454451

HTTP/1.1 500 Internal Server Error.
Date: Tue, 02 Feb 2016 23:07:52 GMT
Content-Type: application/json
Content-Length: 65
Connection: keep-alive
Content-Encoding: gzip
Request-Id: ad2d6be6-ca01-11e5-84d9-000000000000
X-Influxdb-Version: 0.9.6.1

**Comment by sparrc** [comment]
You'll need to downgrade Telegraf to 0.2.X or upgrade InfluxDB to 0.10.X, influxdb 0.9.x has a limit on the number of fields in a measurement.

Another option would be to filter some of the measurements that you don't care about using the `drop` configuration parameter (https://github.com/influxdata/telegraf/blob/master/CONFIGURATION.md#input-filters)

**Comment by ralidousti** [comment]
appreciate the answer. pass/drop solved the problem.
