### ISSUE TITLE
Output Plugin with virtual socket support

### ISSUE THREAD

**Issue by ke55ler** [influxdata/telegraf#6382]
## Feature Request
Adds an output plugin that allows telegraf (running in a guest environment) to write to a virtual socket on the host. The benefit compared to the socket_writer plugin is, that the no network configuration is required.
I reused a lot of codelines from the original socket_writer package. May one could also extend this package instead of writing a new one.

I am still trying to test the vsocket_writer on my local machine. But running into some problems. 

- [x]  Signed CLA. 
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

**Comment by glinton** [comment]
It sounds like you are working on implementing this, would you like me to assign you to this so the work isn't doubled?

**Comment by alrob9894** [comment]
Yes. I've already worked on the code. My problem is to test it. When I run `make` in `$GOPATH/src/github.com/influxdata/telegraf`, I dont get any executable in `$GOPATH/bin`
Who can I contact to get some help with that? I watched also this vidoe from your hompage 
> write-your-own-telegraf-plugin <
There is an email >noah@influxdata.com< should I contact her?

**Comment by glinton** [comment]
To get it installed into your gopath, use `make go-install`.  `make telegraf` produces a `telegraf` binary in the current directory that you can invoke by referencing directly `./telegraf --config ...` if you are inside the directory still or `$GOPATH/src/github.com/influxdata/telegraf/telegraf` elsewhere.

**Comment by alrob9894** [comment]
`./telegraf --config ...` this one worked quite well! Thanks. 
The code is running. And I get the metrics with stdout on my host, when I am listening on the virtual socket (see picture).

![Screenshot from 2019-09-11 19-12-30](https://user-images.githubusercontent.com/48691478/64719240-28871580-d4c8-11e9-9e46-bae2d5161dda.png)

Is there a way to collect this metrics with influxdb? I would like to monitore them. What would approach would you take? 

Thanks for your support!

**Comment by glinton** [comment]
Sure, you add an [influxdb output ](https://github.com/influxdata/telegraf/tree/release-1.12/plugins/outputs/influxdb) in your config file.

**Comment by alrob9894** [comment]
May I should explain my setup. Telegraf is running in a virtual machine, but the influxdb is placed on the host. To send the metrics from the guest environment to the host I don't want to use networking, because it has to be configured on the guest and host and virtual sockets works on the fly. 
So when I get it right the influxdb plugin only supports:
  `urls = ["unix:///var/run/influxdb.sock"]`
  `urls = ["udp://127.0.0.1:8089"]`
  `urls = ["http://127.0.0.1:8086"]`

Am I on the wrong way? Hope you could understand my problem.

**Comment by danielnelson** [comment]
I think you will need Telegraf running a `socket_listener` input with AF_VSOCK support on the host, and it would write to InfluxDB via the regular `influxdb` output plugin.

**Comment by alrob9894** [comment]
Exactly I am using that. 
`conn.RemoteAddr()` ... I will try this out. 
> I'd like the vsock support added in the socket_writer and socket_listener directly

... sounds good. I just wrote it into an own package actually, as I thought it might be easier for testing and experimenting with it for the beginning. But yeah, it makes more sense in the end to add it to the `socekt_writer` / `socket_listener`
I keep you updated and will post here when I did some progress on hte socket_listener.

**Comment by alrob9894** [comment]
Am I right when I think that I've got to use a service_input plugin? Or is it possible with a normal input plugin as well? The service_input plugin seemes to be very complicated. Actually I don't understand how the `socker_listener` stops, which I have taken as a pattern. I can't stop the process with `ctrl + c` in the terminal and when I close the window of the process in the terminal, the port stays open and when I try to reuse it i get `address already in use`.

**Comment by danielnelson** [comment]
Yes you would need to use the ServiceInput interface, it is a bit more complicated.  If your Stop() function is not being called when you interrupt Telegraf then most likely your plugin doesn't match the interface exactly.

You could use an "interface assertion" and the compiler will tell you why the type doesn't match the interface.
```
var _ telegraf.ServiceInput = (*MyPlugin)(nil)
```

**Comment by reimda** [comment]
Hi @alrob9894 were you able to find a solution to the problem? Did you end up modifying an existing telegraf plugin to get what you need?

**Comment by reimda** [comment]
If you would submit a PR with your changes we'd be happy to review it. Thanks!

**Comment by alrob9894** [comment]
Do you want to have this beeing integrated to the socket_writer/socket_listener plugins or as a standalone plugin?

**Comment by powersj** [comment]
Hi,

> Do you want to have this beeing integrated to the socket_writer/socket_listener plugins or as a standalone plugin?

Skimming quickly through this feature request, it sounds like this would be good to the extend to the existing socket_listener input plugin and socket_writer output plugin.

**Comment by alrob9894** [comment]
Hi, quick question regarding how you want the URL for the vsock connection to be represented in the _sample.conf_, my suggestion would be this:

#address = "vsock://cid:port"

as it follows the represenation of TCP, UDP and so on. 

 # address = "tcp://127.0.0.1:8094"
 # address = "udp://127.0.0.1:8094"

**Comment by powersj** [comment]
@alrob9894 I think that is worth putting up a PR with. Thanks!

**Comment by jeffrey4l** [comment]
hey guys, i add a patch to support vsock in prometheus_client output plugin  #14108

**Comment by powersj** [comment]
Going to close this now as both #14108 (prometheus_client) and #14172 (socket listener) PRs have landed.
