### ISSUE TITLE
input.exec - Input JSON contains two properties, Telegraf only outputs one

### ISSUE THREAD

**Issue by dsvemp** [influxdata/telegraf#6383]
Hello,

With the following config:

```
[[inputs.exec]]
	commands = ["powershell -command \"get-childitem -Path E:/SomeDir/Databases -File -Recurse -Filter 'wololo_0' | select-object -Property fullname,length | convertto-json\" "]
	timeout = "5s"
	data_format = "json"
	name_suffix = "_wololo_files"
```

I get the following output

`exec_wololo_files,host=wololo_server Length=4194304 1568214598000000000
`

If I run the above command directly in powershell, I get the following:

```
[
    {
        "FullName":  "E:\\SomeDir\\Databases\\subdir\\subsubdir\\1\\subsubsubdir\\wololo_0",
        "Length":  4194304 
    }
]
```

As you can see, in the output from telegraf I'm missing the "FullName" property

Any idea why? I thought it could be the telegraf json parser not liking backslashes, so I tried replacing them with forward slashes so the json would not have dounble backslashes, but no luck.

Thanks!

**Comment by danielnelson** [comment]
The `json` input data format ignores string values by default, and only adds numeric values.  I think in this case you would want this value to be a tag, so you would list it in `tag_keys`, but if you wanted it to be a string field then use `json_string_fields` instead.

**Comment by dsvemp** [comment]
thanks!
