### ISSUE TITLE
Telegraf logparser - parsing own telegraf.log fails

### ISSUE THREAD

**Issue by phgogo** [influxdata/telegraf#6385]
### Relevant telegraf.conf:
```
[agent]
        interval = "5s"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        flush_interval = "10s"
        flush_jitter = "5s"
        debug = false
        quiet = false
        omit_hostname = false
        logfile = "/var/log/telegraf/telegraf.log"

[[outputs.influxdb]]
        urls = ["https://XXXX:8086"]
        skip_database_creation = true
        timeout = "5s"
        database= "Test"
        insecure_skip_verify = true
        username = "XXX"
        password = "XXX"

        [[inputs.cpu]]
                percpu = true
                totalcpu = true

        [[inputs.logparser]]
                files = ["/var/log/telegraf/telegraf.log"]
                [inputs.logparser.grok]
                  patterns = ['%{ts-rfc3339:timestamp} %{GREEDYDATA:log_type}! \[%{GREEDYDATA:subprogramm}\] %{GREEDYDATA:msg}']
                  measurement = "telegraf_log"
```

### System info:

```Red Hat Enterprise Linux Server release 7.7 (Maipo)```
```Telegraf 1.11.5 (git: HEAD 0ea49ea9)```
```InfluxDB shell version: 1.7.8```

### Steps to reproduce:

1. Attach a Telegraf client to an InfluxDB using the above mentioned config

### Expected behavior:
The Log should be parsed and send to InfluxDB. The above mentioned config works for other logfiles. I see no logical reason, why it should not work for it's own logfile
### Actual behavior:
Telegraf refuses to start and ignores the log configuration. Logs can instead be found in /var/log/meassages:
```
Sep 11 20:12:19 l00157 daemon:info telegraf: 2019-09-11T18:12:19Z I! Starting Telegraf 1.11.5
Sep 11 20:12:19 l00157 daemon:notice systemd: telegraf.service: main process exited, code=exited, status=1/FAILURE
Sep 11 20:12:19 l00157 daemon:notice systemd: Unit telegraf.service entered failed state.
```

**Comment by kalampakas** [comment]
I'm having the same issue and we've ruled out a permissions problem or an SELinux problem ( permissive, no warnings in sealert ) - we can write to /var/log/telegraf/telegraf.log but we're not able to gather the metrics from a working grok parser ( the example mentioned in the grok parser README at https://github.com/influxdata/telegraf/tree/release-1.13/plugins/inputs/logparser - logparser works fine with other files ).

This only works when running telegraf with -test, where the writes happen to the stdout file descriptor - doing strace shows reading the /var/log/telegraf/telegraf.log normally , for instance:

26703 read(13, "2020-01-14T12:44:21Z D! [inputs."..., 4096) = 513

For the particular case of running as root with --test:

12 is the fd for the telegraf.log : 
27387 openat(AT_FDCWD, "/var/log/telegraf/telegraf.log", O_RDWR|O_CREAT|O_APPEND|O_CLOEXEC, 0644) = 5

that's for RW the output of telegraf itself and then there's 

27387 openat(AT_FDCWD, "/var/log/telegraf/telegraf.log", O_RDONLY|O_CLOEXEC <unfinished ...>
27391 <... lseek resumed> )             = 134186
27387 <... openat resumed> )            = 12

for reading we get 

27393 read(12, "2020-01-14T12:56:26Z D! [inputs."..., 4096) = 99
27385 pipe2( <unfinished ...>
27383 <... nanosleep resumed> NULL)     = 0
27393 lseek(12, 0, SEEK_CUR <unfinished ...>
27383 nanosleep({0, 20000},  <unfinished ...>
27385 <... pipe2 resumed> [17, 18], O_CLOEXEC) = 0
27393 <... lseek resumed> )             = 430969
27385 epoll_ctl(4, EPOLL_CTL_ADD, 17, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=113511480, u64=140196435987512}} <unfinished ...>
27393 read(12,  <unfinished ...>
27385 <... epoll_ctl resumed> )         = 0
27393 <... read resumed> "", 4096)      = 0
27385 fcntl(17, F_GETFL <unfinished ...>
27393 write(1, "> net,host=xxxx,interf"..., 1697 <unfinished ...>
27385 <... fcntl resumed> )             = 0 (flags O_RDONLY)
27383 <... nanosleep resumed> NULL)     = 0
27385 fcntl(17, F_SETFL, O_RDONLY|O_NONBLOCK <unfinished ...>
27383 nanosleep({0, 20000},  <unfinished ...>
27385 <... fcntl resumed> )             = 0
27385 epoll_ctl(4, EPOLL_CTL_ADD, 18, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=113511272, u64=140196435987304}} <unfinished ...>
27393 <... write resumed> )             = 1697
27393 write(1, "> telegraf_log,host=xxxx"..., 180) = 180

So it doesn't look like we have a problem reading or writing to a file but we do have a problem writing the output of this particular log to the prometheus output. 

Which specific calls could we try and grab to see why that metric is not really output to the prometheus_client ( other logparsers are )?

**Comment by danielnelson** [comment]
Try setting up a debugging file output with `data_format = "influx"`, so you can view the data in another format.  My guess is that you have string fields which prometheus format does not support, you could try setting `string_as_label = true` in the prometheus output but with log data this is going to have very high cardinality.

If you need more help please post at the [InfluxData Community](https://community.influxdata.com) site.
