### ISSUE TITLE
mysql plugin: mariadb should use show all slaves status

### ISSUE THREAD

**Issue by danielmotaleite** [influxdata/telegraf#6395]
### Proposal:
Right now, the mysql plugin show the slave status when replicating all the databases. But both mysql and mariadb allow one to replicate different databases and currently the plugin do not show any slave status for that.

In mariadb we can use `show all slaves status;`
https://mariadb.com/kb/en/library/show-slave-status/

For mysql, it seems it output multiple rows for `show slave status;`
https://github.com/netdata/netdata/issues/6353#issuecomment-507095714

### Current behavior:
Right now, at least in mariadb, no slave status is returned  when multi-database replication is used, `show slave status;` return empty and require the `show all slaves status;`

i have no mysql setup to see the status in there, so do not know if this request is just for mariadb or also for mysql

### Desired behavior:
the mysql plugin should  execute the `show all slaves status` and output a metric with the label taken from `Connection_name` (in mariadb) for each replication status

For mysql (if not already doing) it should execute the `show slave status` and output a metric with the label `Channel_Name` for each row output

It could also be enabled by a extra option or auto detected

### Use case: 
While not common, multi-database replication allow one to merge multiple replicas for read-only access in just one or a few and save resources. But of course, being able to monitor the replicas is a must have for this setup.

**Comment by utking** [comment]
A PR has been prepared in https://github.com/influxdata/telegraf/pull/5517

**Comment by powersj** [comment]
Looks like the PR was merged, as such I am going to close this issue.
Thanks!
