### ISSUE TITLE
Error in plugin elasticsearch Get 127.0.0.1:9200/_nodes/_local/stats: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by shaharharap** [influxdata/telegraf#640]
hello 
when upgrade to telegraf 0.10.1-1
we got error in elasticsearch plugin
elasticsearch version 2.1.1

2016/02/03 05:00:00 Error in input [elasticsearch]: Get 127.0.0.1:9200/_nodes/_local/stats: unsupported protocol scheme ""
Error in plugin [elasticsearch]: elasticsearch: got unexpected type <nil> with value <nil> (network)

the config file is like the defult:
[[inputs.elasticsearch]]
  # specify a list of one or more Elasticsearch servers
  servers = ["127.0.0.1:9200"]
  # set local to false when you want to read the indices stats from all nodes
  # within the cluster
  local = true
  # set to true when you want to obtain cluster level stats
  cluster_health = true
  # set the interval to 1 minute
  interval = "60s"

**Comment by sparrc** [comment]
try adding `http://` the the url

**Comment by shaharharap** [comment]
thx 
but change it to 
servers = ["http://127.0.0.1:9200"]
restart the service 

and still got this:
Error in plugin [elasticsearch]: elasticsearch: got unexpected type <nil> with value <nil> (network)

**Comment by sparrc** [comment]
this was supposed to be fixed by #454. There is no codepath for a "network" field anymore in telegraf 0.10.1, so I'm not sure how this error is happening. Are you 100% sure you are using the 0.10.1 version? Note that we have changed the path as of 0.10.0. (it's now in /usr/bin)
