### ISSUE TITLE
Telegraf docker images for 1.12, 1.12.1 and latest are broken (go panic)

### ISSUE THREAD

**Issue by jaapz** [influxdata/telegraf#6407]
### Relevant telegraf.conf:
Not relevant, panics with default config too.

### System info:
Docker 19.03.0
Telegraf "latest" docker image (1.12, 1.12.1 as well)

### Steps to reproduce:
Pull latest image, start container.

### Expected behavior:
Working container

### Actual behavior:
Panicking telegraf in my container:

```bash
telegraf_1  | goroutine 4 [syscall]:
telegraf_1  | os/signal.signal_recv(0x0)
telegraf_1  | 	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
telegraf_1  | os/signal.loop()
telegraf_1  | 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
telegraf_1  | created by os/signal.init.0
telegraf_1  | 	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
telegraf_1  | unexpected fault address 0x0
telegraf_1  | fatal error: fault
telegraf_1  | [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x1729710]
telegraf_1  |
telegraf_1  | goroutine 1 [running, locked to thread]:
telegraf_1  | runtime.throw(0x3af7af8, 0x5)
telegraf_1  | 	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0000d5ee0 sp=0xc0000d5eb0 pc=0x1748f62
telegraf_1  | runtime.sigpanic()
telegraf_1  | 	/usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0000d5f10 sp=0xc0000d5ee0 pc=0x175f681
telegraf_1  | runtime.mapassign(0x31ced90, 0x0, 0xc000000000, 0x0)
telegraf_1  | 	/usr/local/go/src/runtime/map.go:621 +0x3e0 fp=0xc0000d5f98 sp=0xc0000d5f10 pc=0x1729710
telegraf_1  | runtime.main()
telegraf_1  | 	/usr/local/go/src/runtime/proc.go:188 +0x1c8 fp=0xc0000d5fe0 sp=0xc0000d5f98 pc=0x174b5e8
telegraf_1  | runtime.goexit()
telegraf_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000d5fe8 sp=0xc0000d5fe0 pc=0x17795b1
telegraf_1  |
telegraf_1  | goroutine 6 [syscall]:
telegraf_1  | os/signal.signal_recv(0x0)
telegraf_1  | 	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
telegraf_1  | os/signal.loop()
telegraf_1  | 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
telegraf_1  | created by os/signal.init.0
telegraf_1  | 	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

**Comment by jaapz** [comment]
Reverting to 1.11.x works for us for now

**Comment by glinton** [comment]
Can you post your config and how you are starting your container, as well as your OS?
I tried using `docker 19.03.2` with `telegraf:1.12.1` and wasn't able to see same thing. Did you happen to send a `SIGQUIT` to the telegraf process inside the container at any time?

**Comment by jaapz** [comment]
I now can't reproduce this on my own workstation anymore, has anything been rebuilt? We had the problem on a computer that we use "in the field", so I'll have to get access to that computer first to make sure it doesn't happen there either anymore. Will report back.

**Comment by jaapz** [comment]
I've been unable to reproduce this, so I guess it must have been something on our machine, sorry for wasting your time!

**Comment by danielnelson** [comment]
No problem, thanks for the report and glad you were able to get it working.
