### ISSUE TITLE
Multiple config files with tags results in only one tag in db

### ISSUE THREAD

**Issue by swartzd** [influxdata/telegraf#641]
Since snmp plugin doesn't yet support per-host tags or hostnames, I created multiple config files (say, A1.conf, A2.conf, and so on) with a tag in each (rack = A1, A2 ...). Data is collected properly from each config file, however all data uses just one tag value (appears to be from the last file parsed).

**Comment by sparrc** [comment]
individual config files are aggregated and treated as one. you can create per-plugin tags like this: https://github.com/influxdata/telegraf/blob/master/CONFIGURATION.md#input-config-tags

**Comment by swartzd** [comment]
Indeed, I tried this first. I get this error "field corresponding to `tag' is not defined in `*snmp.Host'" when attempting to use it.

**Comment by sparrc** [comment]
I would guess your config syntax is a little off, if you paste it in I can take a look

**Comment by swartzd** [comment]
Cheers!

  [[inputs.snmp.host]]
    address = "x.x.x.x:161"
    community = "public"
    version = 1
    timeout = 2.0
    retries = 2
    collect = ["temperature"]
    get_oids = []
   [inputs.snmp.host.tags]
    rack = "B1"

**Comment by sparrc** [comment]
Ah, I see, you are trying to apply tags to a single "snmp host". We only support tags for an entire plugin, like this:

```
[[inputs.snmp]]
  [inputs.snmp.tags]
    rack = "B1"
  [[inputs.snmp.host]]
    address = "x.x.x.x:161"
    community = "public"
    version = 1
    timeout = 2.0
    retries = 2
    collect = ["temperature"]
    get_oids = []
```

Then if you want to separate tags between different hosts, you can define multiple `[[inputs.snmp]]` structs
