### ISSUE TITLE
procstat input plugin: cpu_usage artificially capped at 100

### ISSUE THREAD

**Issue by sajoupa** [influxdata/telegraf#6421]
### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
  exe = "qemu"
  pid_tag = true
```

### System info:

```
$ telegraf version
Telegraf 1.12.1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

### Steps to reproduce:

1. On a machine where some processes use more than 100% CPU (a hypervisor running qemu in my example)
2. Activate the procstat plugin, with adequate filters to match these processes
3. Compare cpu usage from top, and from telegraf measurements:
```
$ top -b -n 1 | egrep 'CPU|^17177' ; echo ; curl -s localhost:9103/metrics | egrep 'cpu_usage.*17177'
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17177 libvirt+  20   0 9481628 3.794g   4608 R 250.0  4.0   6816:34 qemu-system-x86

procstat_cpu_usage{exe="qemu",pid="17177",process_name="qemu-system-x86_64",user="libvirt-qemu"} 100
```

### Expected behavior:

procstat_cpu_usage giving CPU usage in percent of 1 core (in the example above, 250).

### Additional info:

This is due to https://github.com/shirou/gopsutil/issues/755. I'm filing this issue here for other travellers, and track the fix release in telegraf after it's (hopefully) done in gopsutil.

**Comment by glinton** [comment]
That "artificial cap" is definitely new as #2020 is a request to essentially use the number of cpus when reporting cpu usage, rather than the [irix mode](http://logic.edchen.org/irix-mode-vs-solaris-mode-in-top-command/) that `top` uses by default in your example.
