### ISSUE TITLE
Digital Signed Executable for Windows x64

### ISSUE THREAD

**Issue by shawn3231** [influxdata/telegraf#6423]
## Feature Request

We use a security program which checks for digital signed certificates on executables, scripts, dlls, etc... and has flagged telegraf.exe as having no  digital signatures (signing certificates) attached to the executable.

### Proposal: 

We would like for future builds to have a digital signed certificate attached to it.

**Comment by pierwill** [comment]
Hi @shawn3231! If you have a GPG client available on Windows, you should be able to verify the Windows binary by following these instructions: https://docs.influxdata.com/telegraf/v1.14/introduction/installation/#verify-the-authenticity-of-downloaded-binary-optional.

**Comment by shawn3231** [comment]
Sorry, I just went back to look this up issue and for some reason never received an email that you were reaching out to me for feedback. I don't think the GPG is going to work, It needs a certificate attached to the executable. I am showing the 14.4 version of telegraf with a version of microsoft edge executable. If the executable is digitally signed, then the properties will show a 6th tab with a list of attached signatures. The digital signatures certificates are the easiest way to setup exemptions for the program to allow the executable to run.
 
![image](https://user-images.githubusercontent.com/49657262/86133542-ac38df80-baa5-11ea-84b9-eb6979f458a7.png)
![image](https://user-images.githubusercontent.com/49657262/86133611-c4a8fa00-baa5-11ea-8b32-43aacfe01180.png)
![image](https://user-images.githubusercontent.com/49657262/86133666-d8546080-baa5-11ea-898d-a4c46d136111.png)

Let me know if you have anymore questions. -Shawn

**Comment by sjwang90** [comment]
@shawn3231 we've talked about this with our security team and are currently working out the details. We'll reach out to you if there are any questions and let you know when this is completed.

**Comment by sjwang90** [comment]
1. Determine which code signing certificate from a public source (Linux) to use @darinfisher
   - Signcode - https://linux.die.net/man/1/signcode
1. Determine who will own on the influxdata side will own code signing certificate. 
1. Incorporate it into Telegraf build process @ssoroka

**Comment by darinfisher** [comment]
Looks like we are stuck with `signcode`.  I could not find any support for [MS Authenticode](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/authenticode) with the other suggestions.
Minisign with libsodium looks great, just doesn't support Authenticode.

Fortunately `signcode`, as part of the [mono project](https://github.com/mono/mono), is well maintained, has broad support, and should work well for our needs.
