### ISSUE TITLE
requirement for windows monitoring

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6424]
Hi Team,

We have two requirement for Windows server monitoring 

* can we monitor Event log ID in Windows through telegraf agent.
*  can we monitor windows processes through telegraf agent.

**Comment by danielnelson** [comment]
> can we monitor Event log ID in Windows through telegraf agent.

This is not currently supported, but there is an open issue: #4525

> can we monitor windows processes through telegraf agent.

This can be done with the `win_perf_counters` or `procstat` plugins.  I suggest starting with the `win_perf_counters` plugin.
