### ISSUE TITLE
telegraf error

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6425]
ONe telegraf agent is not able to connect InfluxDB, but telnet is working.

Telegraf version : Telegraf 1.11.1 (git: HEAD f91de60d)
OS version :   Windows server 2012 R2 standard

[telegraf.log](https://github.com/influxdata/telegraf/files/3635740/telegraf.log)

**Comment by danielnelson** [comment]
This error indicates that the connection was accepted and then closed by the remote destination.  There isn't anyway to know why the server is closing the connection, likely you are not connecting to InfluxDB's HTTP service.

You can try sending some HTTP traffic to the server:
```
curl -XPOST 'http://10.14.153.4:8086/write?db=telegraf' -d 'test value=42'
```

If you have follow up questions the best place to ask for help would be at the [InfluxData Community](https://community.influxdata.com) site.
