### ISSUE TITLE
Build failure on Ubuntu 18.04 

### ISSUE THREAD

**Issue by AngleNet** [influxdata/telegraf#6430]
### Relevant telegraf.conf:

None

### System info:

Ubuntu 18.04 
golang 1.13

### Steps to reproduce:

1. go get -d github.com/influxdata/telegraf
2. cd $GOPATH/src/github.com/influxdata/telegraf
3. make

### Expected behavior:
Build fluently

### Actual behavior:
  ✗ unable to deduce repository and source type for "golang.org/x/sys": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys?go-get=1": Get http://golang.org/x/sys?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "golang.org/x/sync": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sync?go-get=1": Get http://golang.org/x/sync?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "google.golang.org/genproto": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/genproto?go-get=1": Get http://google.golang.org/genproto?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "golang.org/x/oauth2": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/oauth2?go-get=1": Get http://golang.org/x/oauth2?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/grpc?go-get=1": Get http://google.golang.org/grpc?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/crypto?go-get=1": Get http://golang.org/x/crypto?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "golang.org/x/text": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text?go-get=1": Get http://golang.org/x/text?go-get=1: context canceled
  ✗ unable to deduce repository and source type for "golang.org/x/net": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/net?go-get=1": Get http://golang.org/x/net?go-get=1: context canceled

**Comment by AngleNet** [comment]
:fire: :fire: Seems to be problem of GFW. Any idea to workaround this?

**Comment by danielnelson** [comment]
Is this a persistent error, or does it clear up on retry?  It looks like an intermittent network issue.

**Comment by AngleNet** [comment]
Yes, It’s just a network problem due to GFW

**Comment by danielnelson** [comment]
Okay, I'm going to close then.  BTW what is GFW?

**Comment by AngleNet** [comment]
GFW, aka Great Firewall of China.
