### ISSUE TITLE
add ability to combine multiple columns into a timestamp for CSV

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#6435]
### Proposal:
The CSV parser has a config option for setting the column for the timestamp `csv_timestamp_column`. The issue is that there is a lot of data out there where the timestamp is broken out into multiple columns such as `year, month, day, hour, min, sec`. It would be handy to be able to create a timestamp by combining these columns to create the timestamp.

### Current behavior:
only a single column can be used as a timestamp

### Desired behavior:
add the ability to combine multiple columns into a timestamp. There would need to be a way to define the template and the columns to substitute into the template, so you could do something like `{year_col}-{month_col}-{day_col}T{hour_col:24}:{minute_col}:00` 

### Use case: 
This would save users from having to reformat the csv before bringing it into telegraf.

**Comment by sspaink** [comment]
Closing because there hasn't been any recent requests related to this issue and it seems like a special use case.

**Comment by WoeMat** [comment]
I would nee the exact same thing in order to ingest old log files. Is there any way to do that nowadays?

**Comment by maufc** [comment]
It is still a valid request.

**Comment by larmeh** [comment]
Same thing needed here, as well.

**Comment by mhinterdorfergh** [comment]
Me too

**Comment by powersj** [comment]
You can combine various columns using the starlark processor and then use the [timestamp](https://github.com/influxdata/telegraf/tree/master/plugins/processors/timestamp) processor, in v1.31 or later, to parse the combined timestamp and set the metric time.
