### ISSUE TITLE
 postgresql_extensible is not giving same result

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6438]
Hi,

PFB telegraf configuration, where the connection has established successfully:

**[[inputs.postgresql_extensible]]
address = "host=N1PBBL-EXPA0113 port=5678 user=telegraf password=ABCD123 sslmode=disable dbname=postgres"
name_suffix = "_extensible"**

below is the query running:
**[[inputs.postgresql_extensible.query]]
 sqlquery="select pid,usename,datname,client_addr,client_port,application_name,backend_start,query,query_start,state as \"status\",state_change from pg_stat_activity where state='active';"
 withdbname=false
 tagvalue="usename"**

output of below query:

**[root@N1PBBL-EXPA0113 ~]# telegraf --config /etc/telegraf/telegraf.conf --test | grep -i postgres | grep -i status
2019-09-24T11:15:43Z I! Starting Telegraf 1.12.0
> postgresql_extensible,IP=10.222.166.38,LOB=ABGB,application=uccmonitor,db=postgres,host=N1PBBL-EXPA0113,server=host\=N1PBBL-EXPA0113\ port\=5678\ user\=telegraf\ dbname\=postgres,usename=replication application_name="walreceiver",client_addr="10.222.164.63",client_port=49508i,pid=8210i,query="",status="active" 1569323743000000000
> postgresql_extensible,IP=10.222.166.38,LOB=ABGB,application=uccmonitor,db=postgres,host=N1PBBL-EXPA0113,server=host\=N1PBBL-EXPA0113\ port\=5678\ user\=telegraf\ dbname\=postgres,usename=telegraf application_name="",client_addr="10.222.166.38",client_port=41308i,datname="postgres",pid=17622i,query="select pid,usename,datname,client_addr,client_port,application_name,backend_start,query,query_start,state as \"status\",state_change from pg_stat_activity where state='active';",status="active" 1569323743000000000
[root@N1PBBL-EXPA0113 ~]#**

But In Influxdb only repuring one value which one row is coming first.
Note: even if the query returns 100 of rows infuxdb is showing only the first row fetched by telegraf agent.
influxdb query:
SELECT * FROM "postgresql_extensible" WHERE "status"='active'

can you check what I am missing?

**Comment by danielnelson** [comment]
Recall that in InfluxDB that you can have one value for each measurement+tagset+timestamp+field.  You will want to set another tag to uniquely identify the series, perhaps `pid` could work though be aware that the potential series cardinality could be relatively high (65k).
