### ISSUE TITLE
What should I do if I want to get local ip as my influx tag?

### ISSUE THREAD

**Issue by JinxLbj** [influxdata/telegraf#6442]

**Comment by danielnelson** [comment]
Sorry I don't understand.  Do you want your ip address added to all metrics as a global tag perhaps?  You would need to enter it manually or generate your configuration file.
```
[global_tags]
  ip = "192.168.0.1"
```

For questions about usage of Telegraf please ask over at the [InfluxData Community](https://community.influxdata.com) site.
