### ISSUE TITLE
Telegraf logging to two different outputs

### ISSUE THREAD

**Issue by deepaksood619** [influxdata/telegraf#6449]
How can we use inputs.docker_log plugin and send access log of `2019-09-25 20:07:14+0530 [-] "xx.xx.xx.xx" - - [25/Sep/2019:14:37:14 +0000] "POST /add/xxxxxxxxx HTTP/1.1" 200 - "-" "-"` this type as metrics to `influxdb` and other logs to `elasticsearch` for a specific container. There are multiple containers but i want to do this for a specific container if it’s present, and if not then ignore.

**Comment by danielnelson** [comment]
Use the container tags along with [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) to control output routing.

Please ask usage questions at the [InfluxData Community](https://community.influxdata.com) site.
