### ISSUE TITLE
Problem on Windows Hyper-V 2012 R2 Host with Win Perf Counter for dik IO

### ISSUE THREAD

**Issue by jasgggit** [influxdata/telegraf#6451]
Hi, I'm building some dashboard using the Telegraf+InfluxDB+Graphana
Gathering some from Influx dashboard download site, but on a server is giving me some different results for the same telegraf.conf file.
4 Windows Servers using it:
1 Windows 2019 VM
1 Windows 2008 R2 SQL VM
1 Windows 2012 R2 Hyper-V core
1 Windows 2016 Hyper-V core

On the Windows 2012 R2 Hyper-V doesn't report the instances for physical disk correctly and I cannot find the reason.

telegraf.con section common on all:

  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
	  "Avg. Disk Queue Length",
      "Avg. Disk sec/Read",
      "Avg. Disk sec/Write",
      "Split IO/sec",
    ]
    Measurement = "win_diskio"

---------------
Data on influxDB:

root@dash:~# influx -database telegraf -execute 'SHOW SERIES FROM "win_diskio"' -precision rfc3339
key
---
win_diskio,host=win2019,instance=0\ C:,objectname=PhysicalDisk
win_diskio,host=win2019,instance=1\ D:,objectname=PhysicalDisk
win_diskio,host=win2008,instance=0\ C:,objectname=PhysicalDisk
win_diskio,host=win2008,instance=1\ D:,objectname=PhysicalDisk
win_diskio,host=win2008,instance=2\ E:,objectname=PhysicalDisk
win_diskio,host=win2016hypv,instance=0\ C:,objectname=PhysicalDisk
win_diskio,host=win2016hypv,instance=1\ D:,objectname=PhysicalDisk
win_diskio,host=win2012r2hypv,instance=0\ C:\ D:,objectname=PhysicalDisk

As we can see the win2012r2 is not reporting the disks correctly.
What can I do to correct this? as this is preventing me from displaying data correctly on the dashboard correctly, and couldn't find a good answer on G.
Thanks in advance for the help.
JG

**Comment by danielnelson** [comment]
This is probably just a quirk of Windows 2012, but you can try to see a list of the instances and counters with:
```
typeperf -qx PhysicalDisk
```

This might be something where we need to do some special tag cleanup in a processor, would it work if we just renamed this tag to `instance=0\ C:`?

**Comment by jasgggit** [comment]
Hi Daniel and thank you for your reply.

> This is probably just a quirk of Windows 2012, but you can try to see a list of the instances and counters with:
> 
> ```
> typeperf -qx PhysicalDisk
> ```
> 
About being a 'quirk', this is the queries I've run on that machine:

PS C:\Program Files\telegraf> Get-Counter -ListSet *physical* | select -ExpandProperty counter
\Physical Network Interface Card Activity(*)\Low Power Transitions (Lifetime)
\Physical Network Interface Card Activity(*)\% Time Suspended (Lifetime)
\Physical Network Interface Card Activity(*)\% Time Suspended (Instantaneous)
\Physical Network Interface Card Activity(*)\Device Power State
\PhysicalDisk(*)\Current Disk Queue Length
\PhysicalDisk(*)\% Disk Time
\PhysicalDisk(*)\Avg. Disk Queue Length
\PhysicalDisk(*)\% Disk Read Time
\PhysicalDisk(*)\Avg. Disk Read Queue Length
\PhysicalDisk(*)\% Disk Write Time
\PhysicalDisk(*)\Avg. Disk Write Queue Length
\PhysicalDisk(*)\Avg. Disk sec/Transfer
\PhysicalDisk(*)\Avg. Disk sec/Read
\PhysicalDisk(*)\Avg. Disk sec/Write
\PhysicalDisk(*)\Disk Transfers/sec
\PhysicalDisk(*)\Disk Reads/sec
\PhysicalDisk(*)\Disk Writes/sec
\PhysicalDisk(*)\Disk Bytes/sec
\PhysicalDisk(*)\Disk Read Bytes/sec
\PhysicalDisk(*)\Disk Write Bytes/sec
\PhysicalDisk(*)\Avg. Disk Bytes/Transfer
\PhysicalDisk(*)\Avg. Disk Bytes/Read
\PhysicalDisk(*)\Avg. Disk Bytes/Write
\PhysicalDisk(*)\% Idle Time
\PhysicalDisk(*)\Split IO/Sec

And

PS C:\Program Files\telegraf> typeperf -qx PhysicalDisk
\PhysicalDisk(0 C: D:)\Current Disk Queue Length
\PhysicalDisk(_Total)\Current Disk Queue Length
\PhysicalDisk(0 C: D:)\% Disk Time
\PhysicalDisk(_Total)\% Disk Time
\PhysicalDisk(0 C: D:)\Avg. Disk Queue Length
\PhysicalDisk(_Total)\Avg. Disk Queue Length
\PhysicalDisk(0 C: D:)\% Disk Read Time
\PhysicalDisk(_Total)\% Disk Read Time
\PhysicalDisk(0 C: D:)\Avg. Disk Read Queue Length
\PhysicalDisk(_Total)\Avg. Disk Read Queue Length
\PhysicalDisk(0 C: D:)\% Disk Write Time
\PhysicalDisk(_Total)\% Disk Write Time
\PhysicalDisk(0 C: D:)\Avg. Disk Write Queue Length
\PhysicalDisk(_Total)\Avg. Disk Write Queue Length
\PhysicalDisk(0 C: D:)\Avg. Disk sec/Transfer
\PhysicalDisk(_Total)\Avg. Disk sec/Transfer
\PhysicalDisk(0 C: D:)\Avg. Disk sec/Read
\PhysicalDisk(_Total)\Avg. Disk sec/Read
\PhysicalDisk(0 C: D:)\Avg. Disk sec/Write
\PhysicalDisk(_Total)\Avg. Disk sec/Write
\PhysicalDisk(0 C: D:)\Disk Transfers/sec
\PhysicalDisk(_Total)\Disk Transfers/sec
\PhysicalDisk(0 C: D:)\Disk Reads/sec
\PhysicalDisk(_Total)\Disk Reads/sec
\PhysicalDisk(0 C: D:)\Disk Writes/sec
\PhysicalDisk(_Total)\Disk Writes/sec
\PhysicalDisk(0 C: D:)\Disk Bytes/sec
\PhysicalDisk(_Total)\Disk Bytes/sec
\PhysicalDisk(0 C: D:)\Disk Read Bytes/sec
\PhysicalDisk(_Total)\Disk Read Bytes/sec
\PhysicalDisk(0 C: D:)\Disk Write Bytes/sec
\PhysicalDisk(_Total)\Disk Write Bytes/sec
\PhysicalDisk(0 C: D:)\Avg. Disk Bytes/Transfer
\PhysicalDisk(_Total)\Avg. Disk Bytes/Transfer
\PhysicalDisk(0 C: D:)\Avg. Disk Bytes/Read
\PhysicalDisk(_Total)\Avg. Disk Bytes/Read
\PhysicalDisk(0 C: D:)\Avg. Disk Bytes/Write
\PhysicalDisk(_Total)\Avg. Disk Bytes/Write
\PhysicalDisk(0 C: D:)\% Idle Time
\PhysicalDisk(_Total)\% Idle Time
\PhysicalDisk(0 C: D:)\Split IO/Sec
\PhysicalDisk(_Total)\Split IO/Sec


> This might be something where we need to do some special tag cleanup in a processor, would it work if we just renamed this tag to `instance=0\ C:`?
>
And I know nothing about that ... sadly. Can you point me in some direction, as I'm still learning this. 
Also, the server has 2 Partitions on a RAID 5 disk array, and I'm trying to gather some performance info about that RAID 5, I think there is something wrong about it, too slow.

Regards.
JG

**Comment by jasgggit** [comment]
And after reading what I've written above, some 'light' come upon me...
I'm taking the 'PhysicalDisk(0 C: D:)' as something wrong, but as I said above too, this is a RAID5 disk, with 2 partitions, maybe that's what the 'Perf' is telling me? That is one Physical DIsk with 2 partitions inside? If so, for some strange reason that didn't come up to me before and I apologize for taking your time, but nevertheless thank you for your time.
Regards.
JG

PS - If I may ... can you provide a quick panel JSON code for reading the average latency on these disks. The one I have is giving me some wrong(?) stats.

This is the one I found on the 'Net':

```
{
  "columns": [
    {
      "text": "Current",
      "value": "current"
    },
    {
      "text": "Min",
      "value": "min"
    },
    {
      "text": "Max",
      "value": "max"
    },
    {
      "text": "Avg",
      "value": "avg"
    }
  ],
  "fontSize": "100%",
  "gridPos": {
    "h": 9,
    "w": 8,
    "x": 0,
    "y": 8
  },
  "id": 18,
  "links": [],
  "options": {},
  "pageSize": null,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 4,
    "desc": true
  },
  "styles": [
    {
      "alias": "",
      "colorMode": "cell",
      "colors": [
        "rgba(50, 172, 45, 0.97)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(245, 54, 54, 0.9)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 3,
      "pattern": "/.*/",
      "thresholds": [
        "0.015",
        "0.025"
      ],
      "type": "number",
      "unit": "s"
    }
  ],
  "targets": [
    {
      "alias": "$tag_instance",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "instance"
          ],
          "type": "tag"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "measurement": "cluster_csv_filesystem",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Write_Latency"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/^$hostname$/"
        }
      ]
    }
  ],
  "title": "Storage Latency",
  "transform": "timeseries_aggregations",
  "type": "table"
}
```
