### ISSUE TITLE
RHEL 8 Packages

### ISSUE THREAD

**Issue by schlitzered** [influxdata/telegraf#6457]
## Feature Request

Please create packages for RHEL 8 compatible systems

### Proposal:
make packages for current RHEL 8 available.

### Current behavior:
no RHEL 8 packages

### Desired behavior:
has RHEL 8 packlages

### Use case: 
using influx applications on RHEL 8 compatible systems

**Comment by danielnelson** [comment]
@schlitzered I have added an rpm to a new Centos/RHEL 8 yum repository, but I've only tested on Centos.  Would you be able to verify that it is working with RHEL8?
