### ISSUE TITLE
error in telegraf instance 

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6458]
Hi, 

we have created one more telegraf conf file and while running one more telegraf instance, we are getting connectivity issue.

But there is no error for main configuration file.

file creation command :- telegraf -sample-config -input-filter ping -output-filter influxdb > telegraf_ping.conf

telegraf version :-  telegraf-1.12.2-1.x86_64
OS version :- Red Hat Enterprise Linux Server release 7.6 (Maipo)
InfluxDB :-  influxdb-1.7.6-1.x86_64 

Error:-   W! [outputs.influxdb] when writing to [http://10.5.112.174:8086]: database "telegraf" creation failed: Post http://10.5.112.174:8086/query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Telegraf and Influx is running on same server and connectivity is ok.

**Comment by danielnelson** [comment]
> Post http://10.5.112.174:8086/query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

This is a network timeout writing to InfluxDB, Telegraf sent the data but no reply was received before the timeout time.  It didn't get a connection refused or host unreachable error so you might want to check if you have a firewall blocking the connection, but it could have other causes.

**Comment by rguptarg** [comment]
Firewall is OK, because normal Telegraf process is running fine and connected with Influx. also Influx and Telegraf both are on same server.

can you please suggest what else I can troubleshoot at my end.

**Comment by rguptarg** [comment]
I have tried on one more server, previously telegraf version was telegraf-1.10.3-1.x86_64
and telegraf multiple instances was running fine. but after upgradtion telegraf, I am getting same error.

Is it specific version issue ?

**Comment by danielnelson** [comment]
> also Influx and Telegraf both are on same server

It appears though that you are talking over the external interface, so it's more likely the system firewall could be in play.

> Is it specific version issue ?

I'm not aware of any bugs we have had around this, you could try reverting and see if it helps.

**Comment by rguptarg** [comment]
I have check with telegraf 10.X and 11.X version and it's working fine

Can you please check with telegraf 12.X in your LAB. if multiple telegraf instance are working or not

**Comment by danielnelson** [comment]
I am able to run multiple Telegraf instances simultaneously on a single system without issue.  Does it help if you connect to InfluxDB over the 127.0.0.1 loopback address?

**Comment by danielnelson** [comment]
Your examples work, you can also use the `--section-filter` to avoid adding the commented out processors and aggregators.
```
telegraf --section-filter agent:inputs:outputs --input-filter ping --output-filter influxdb config > /etc/telegraf/telegraf_ping.conf
telegraf --config /etc/telegraf/telegraf_ping.conf
```

Maybe I should mention that even though you can run Telegraf multiple times on one system, there is almost never a need to.  You ought to be able to run a single Telegraf and use the [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) to run multiple "pipelines" at once.
