### ISSUE TITLE
E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp 10.21.0.1:9092: connectex: A socket operation was attempted to an unreachable network.

### ISSUE THREAD

**Issue by Weelki** [influxdata/telegraf#6459]
### Relevant telegraf.conf:

On my Windows Server 2016 Cassandra1 server (IP address: 10.21.3.10) telegraf.conf:
```
[[outputs.kafka]]
  brokers = ["10.21.3.1:9092","10.21.3.2:9092","10.21.3.3:9092"]
  topic = "telegraf"
  compression_codec = 0
	required_acks = 0
	max_retry = 3
  data_format = "influx"
```

### System info:

- Telegraf v1.5.0
- Windows Server 2016
- 3 x monitoring servers on CentOS and dockerised containers:

**Monitoring1 (interfaces 10.21.0.1 | 10.21.3.1) containers**:
fluentd:1.0.1
kafka:4.0.0
zookeeper:3.4.10
kibana:6.4.1
grafana:4.6.3

**Monitoring2 (interfaces 10.21.0.2 | 10.21.3.2) containers**:
fluentd:1.0.1
jmxtrans:1.2
kafka_influxdb:0.9.3
kafka:4.0.0
zookeeper:3.4.10

**Monitoring3 (interfaces 10.21.0.3 | 10.21.3.3) containers**:
telegraf:1.7.0-alpine
fluentd:1.0.1
kafka_elasticsearch:1.2
kafka:4.0.0
zookeeper:3.4.10
influxdb:1.4.2

### Steps to reproduce:

1. Telegraf.exe installed as a service on Cassandra1 server
2. Start service
3. Open log file and see following messages... the error lines continuously repeat:
```2019-09-25T17:02:08Z I! Hang on, flushing any cached metrics before shutdown
2019-09-25T17:02:10Z D! Attempting connection to output: kafka
2019-09-25T17:02:52Z D! Successfully connected to output: kafka
2019-09-25T17:02:52Z I! Starting Telegraf v1.5.0
2019-09-25T17:02:52Z I! Loaded outputs: kafka
2019-09-25T17:02:52Z I! Loaded inputs: inputs.exec inputs.win_perf_counters
2019-09-25T17:02:52Z I! Tags enabled: host=Cassandra1
2019-09-25T17:02:52Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"Cassandra1", Flush Interval:10s 
2019-09-25T17:03:10Z D! Output [kafka] buffer fullness: 1101 / 1000 metrics. 
2019-09-25T17:03:10Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp 10.21.0.1:9092: connectex: A socket operation was attempted to an unreachable network.

2019-09-25T17:03:20Z D! Output [kafka] buffer fullness: 1609 / 1000 metrics. 
2019-09-25T17:03:20Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp 10.21.0.2:9092: connectex: A socket operation was attempted to an unreachable network.

2019-09-25T17:03:30Z D! Output [kafka] buffer fullness: 1531 / 1000 metrics. 
2019-09-25T17:03:30Z E! Error writing to output [kafka]: FAILED to send kafka message: dial tcp 10.21.0.3:9092: connectex: A socket operation was attempted to an unreachable network.
```

Even though connection says successful. If I use Kafka Tool I am unable to connect to my Kafka cluster successfully. It initially connects, but then times out trying to browse Telegraf.

### Expected behavior:
No error messages in log file and successful connection to Kafka cluster via Kafka Tool

### Actual behavior:
Unable to connect to Kafka cluster via Kafka Tool
Metrics from Cassandra server are not passed to Kafka, and subsequently into InfluxDB.
No metrics appear in Grafana for this server

### Additional info:
1) There are other servers in my network. They are IP'd up for the 10.21.0.x/24 subnet and can successfully connect to Kafka on the monitoring platform.

2) I have 3 x Cassandra servers who are on 10.21.3.x/24 subnet. And a couple of other servers on this subnet and none of them can connect to Kafka successfully. They all exhibit the error message listed above.

3) As stated above, the Monitoring servers, have dual interfaces with connections to both subnets.

4) Kafka on the monitoring server(s) is configured under the NetworkMode section as follows:
```
"NetworkMode": "default",
            "PortBindings": {
                "9092/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9092"
                    }
                ],
                "9099/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9099"
                    }
                ]
            },
```
So if my understanding is correct should not be agnostic to the incoming subnet connection?

5) Why for the errors listed above, if the server is configured for the 10.21.3.x subnet are the errors reported back for the 10.21.0.x subnet?

6) My Network Systems Administrator assures me routing/firewalls are setup correctly. Could there be anything that is the cause of this error?

**Comment by danielnelson** [comment]
I looked at the `Connect()` function for the Kafka output, and it doesn't actually establish the connection until the first write occurs.  This is pretty typical behavior for an output plugin, but don't read to much into the `Successfully connected to output` message.

> connectex: A socket operation was attempted to an unreachable network.

I'm not very familiar with Windows error messages, but this sounds like a routing issue to me.  If you can't connect via Kafka Tool from this system, I would work on that first.

You also might want to look into updating to a newer Telegraf version if you can.  I don't think this will solve this particular issue but there has been some improvements to networking in newer versions of Go and we have updated our Kafka library to support some newer features of Kafka.
