### ISSUE TITLE
neo4j input plugin

### ISSUE THREAD

**Issue by Hokutosei** [influxdata/telegraf#646]
Greetings,

it would be nice to have an agent for the worlds famous graph database, neo4j.

deployed few telegraf agents into my dev instances, and I really like it. installed telegraf, influxdb, and chronograf. I missed just once database, which is a critical part, neo4j..

**Comment by sparrc** [comment]
do you mean via these metrics?: http://neo4j.com/docs/stable/metrics-extension.html, doesn't look like there's an API but we could probably parse the CSV file.

looks like you can configure it to send graphite data, are you aware that you can setup influxdb with a graphite listener? https://docs.influxdata.com/influxdb/v0.9/write_protocols/graphite/

**Comment by Hokutosei** [comment]
Hey! Haven't see that, will check on it! I'm not familiar how monitoring is done with neo4j but I heard it uses jmx. 

Hopefully, like mongodb(we're using this too) we can use to collect data from neo4j...

**Comment by sjwang90** [comment]
Closing due to lack of interest and discussion. Feel free to reopen if desired.

**Comment by pcgeek86** [comment]
I'd love to see a Neo4j input plugin for Telegraf. If you could run arbitrary Cypher queries to ingest metrics, that would be awesome.
