### ISSUE TITLE
input.smart - error counter log

### ISSUE THREAD

**Issue by gregorybrzeski** [influxdata/telegraf#6461]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Additional measurement `smart_error_counter_log` which would include data parsed from smartctl "Error Counter Log".

* smart_error_counter_log
    * tags
        * capacity
        * device
        * enabled
        * model
        * serial_no
        * wwn
        * page_name - read, write, verify

    * fields
        * errors_corrected_by_eccfast
        * errors_corrected_by_eccdelayed
        * errors_corrected_by_rereads_rewrites
        * total_errors_corrected
        * correction_algorithm_invocations
        * gigabytes_processed
        * total_uncorrected_errors

For devices attached using scsi protocol (including SAS drives) smartctl prints error counter log if it is supported.

HGST ssd sas drives do not return much information in attributes:

```
$ smartctl --attributes --format=brief /dev/sdi 
smartctl 6.5 2016-05-07 r4318 [x86_64-w64-mingw32-2016] (sf-6.5-1)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     26 C
Drive Trip Temperature:        70 C

Manufactured in week 32 of year 2016
Specified cycle count over device lifetime:  0
Accumulated start-stop cycles:  0
Specified load-unload count over device lifetime:  0
Accumulated load-unload cycles:  0
defect list format 6 unknown
Elements in grown defect list: 0

Vendor (Seagate) cache information
  Blocks sent to initiator = 4200776633156356
``` 

Most of the important information is included in the Error Counter Log:

```
$ smartctl --log error --format=brief /dev/sdi
smartctl 6.5 2016-05-07 r4318 [x86_64-w64-mingw32-2016] (sf-6.5-1)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        0         0         0          0       4797.541           0
write:         0        0         0         0          0       8932.303           0
verify:        0        0         0         0          0          5.713           0

Non-medium error count:        0
```

Smartctl print code for the Error Counter Log:
https://github.com/smartmontools/smartmontools/blob/8a1ee9fa8b4ad842ffec33a1649db55d26b13acb/smartmontools/scsiprint.cpp#L805

### Current behavior:

Error counter log information is not parsed and collected.

### Desired behavior:

Parsing of error counter log and adding parsed data to additional measurement: smart_error_counter_log

### Use case:

Allows to monitor wider range of popular drives which do not provide much information in attributes, instead include counters in error counter log.

**Comment by danielnelson** [comment]
Sounds good, lets double check which smartctl version the option was added in, or that it exists at least back to 5.41.

One minor tweaks to the strings, I'd like to use more underscores in the measurement name `smart_error_counter_log` and it also might be nicer if we can parse the Gigabytes processed as an integer in bytes `processed_bytes=4797541000000i`.

**Comment by gregorybrzeski** [comment]
Error Counter Log support exists in 5.41 and seems that it was added long time ago in version 5.1.10 (14.04.2003). Output format seems unchanged since as well.

https://github.com/smartmontools/smartmontools/commit/4feb5a201fbdc6ad30aa464fb0b9add1ce25ef04

**Comment by gregorybrzeski** [comment]
@danielnelson updated proposal documented with your suggestions and added a PR for this suggested new enhancement.

**Comment by powersj** [comment]
Thanks for the issue and fo the PR. It looks like it was nearly complete. However, it looks like it was closed and I have not seen any additional desire to land this, so I am going to close this feature request. If you change your mind or wish to continue working on it, please do let us know and we can re-open both.

Thanks again!
