### ISSUE TITLE
vsphere input - summation counters interval

### ISSUE THREAD

**Issue by jstiops** [influxdata/telegraf#6463]
sorry to create an issue for this, but i think i can get the best help here. 
simple question i think: 
i collect the vsphere realtime stats for VMs and hosts. My collection interval is 60s.
If i want to convert counters of the "summation" type to percentage, i have to calculate the percentage. Im not sure about the calculation.
Realtime stats are updated every 20 seconds. So when looking at vCenter graphs, i would divide by 20000 (milliseconds) * 100 to get the percentage value out of a summation counter.
Would i need to do the same when telegraf has a collection interval of 60s?  or do i divide by 60000 in that case?

If i had to guess/assume, i would say telegraf just retrieves the counter at 60s interval, but the value returned is based on a 20s update cycle. So i'd have to divide by 20000 within, for example, grafana?

**Comment by danielnelson** [comment]
I might be wrong but I believe that vSphere resets this value every 20s, and so no matter the Telegraf interval the you would divide by 20000.  Would be helpful if you could cross reference this with esxtop to verify.

**Comment by jstiops** [comment]
that's what i'd thought, but im not sure. 
with cross reference with esxtop, do you mean to check if esxtop updates (for example) %rdy values more often than 20s ? because it does. It updates every second actually.

**Comment by danielnelson** [comment]
I think we just want to make sure we are in the right range, even with different update intervals it seems like it ought to be possible to take a virtual machine with a relatively steady cpu usage and compare it between the two tools.

**Comment by prydin** [comment]
"Summation" refers to the sum over the sampling period for the metric. For realtime metrics (VM and host) it's 20s. For everything else (datacenters, clusters and data sources) it's 5m. At some point in time, we'd like to support custom intervals as well, but for now, these two are what you get.

**Comment by prydin** [comment]
...so the idea of dividing by 20,000 is correct.
