### ISSUE TITLE
add ovs_events and osv_stats plug-in

### ISSUE THREAD

**Issue by celiawong-influxdb** [influxdata/telegraf#6466]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

I would like to also see if we can get the following into Telegraf:
**[ovs_events](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_ovs_events)**
- The ovs_events plugin monitors the link status of Open vSwitch (OVS) connected interfaces, dispatches the values to collectd and sends the notification whenever the link state change occurs. This plugin uses OVS database to get a link state change notification.

Synopsis:
 <Plugin "ovs_events">
   Port 6640
   Address "127.0.0.1"
   Socket "/var/run/openvswitch/db.sock"
   Interfaces "br0" "veth0"
   SendNotification true
   DispatchValues false
 </Plugin>
 
2. [ovs_stats](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_ovs_stats)
- The ovs_stats plugin collects statistics of OVS connected interfaces. This plugin uses OVSDB management protocol (RFC7047) monitor mechanism to get statistics from OVSDB

Synopsis:
 <Plugin "ovs_stats">
   Port 6640
   Address "127.0.0.1"
   Socket "/var/run/openvswitch/db.sock"
   Bridges "br0" "br_ext"
 </Plugin>
The plugin provides the following configuration option

### Use case:  Will add more details here.

**Comment by powersj** [comment]
Hi,

Due to lack of interest, I am going to close this. However, if it is something you want to circle back on at some point please let us know!

Thanks!
