### ISSUE TITLE
Remove logrotate in favour of native log rotation

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#6475]
### Proposal:
PR #5778 adds native log rotation which does not work nicely togheter with logrotate.

I suggest to remove the logrotate file from the builds ([#100](https://github.com/influxdata/telegraf/pull/100)).

### Current behavior:
Logrotate is installed by default in .deb and .rpm files.

### Desired behavior:
Remove /etc/logrotate.d/telegraf from .deb and .rpm files.

### Use case: 
Native log rotation allow a better control for log files growing too fast and same config could be reused in different OS.

**Comment by powersj** [comment]
Hi,

Going through old packaging bugs, so wanted to ensure I understand this one.

Is there a reason or example you can give where this is an issue? The default setting for `logfile_rotation_interval` and `logfile_rotation_max_size` will not rotate based on size or any interval as long as those options are not set. I believe this means users of the deb/rpm could set the logfile to `/var/log/telegraf/telegraf.log` and let logrotate manage the files.

I would prefer to keep our deb/rpm builds following distro standards. Namely, the Debian package manual in [10.8 Log files](https://www.debian.org/doc/debian-policy/ch-files.html#log-files) specifies the use of logroate configuration files. Similarly the Fedora packaging guidelines under [Log FIles](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_log_files) state that a package must include a logrotate configuration file unless the software itself will rotate its own logs.

Thanks!
