### ISSUE TITLE
Cloudwatch input i/o timeout fail

### ISSUE THREAD

**Issue by ariyu08** [influxdata/telegraf#6477]
### Telegraf Config
```
[[inputs.cloudwatch]]
  region = "eu-west-2"
  period = "5m"
  delay = "1m"
  interval = "5m"
  namespace = "AWS/EC2"
```
### System Info
Centos7, Telegraf 1.12.2

### Expected Behavior
Return metrics from AWS.

### Actual Behavior
Returning no metrics and logging an I/o timeout error. 

### Additional Info
I am able to get a response when manually triggering telegraf with the command below.
`telegraf --config /etc/telegraf/telegraf.conf --input-filter cloudwatch --test`

However when running telegraf normally, it is logging the error below.
`2019-10-03T11:02:00Z E! [inputs.cloudwatch] Error in plugin: RequestError: send request failed
caused by: Post https://monitoring.eu-west-2.amazonaws.com/: dial tcp: i/o timeout`

**Comment by danielnelson** [comment]
It's not immediately clear from the code what the current timeout is, but I think the next step to fix this is to update the cloudwatch plugin to use a per plugin http.Client and Transport and expose a `timeout` option.

**Comment by goller** [comment]
branch:  https://github.com/influxdata/telegraf/tree/bugfix/6477

**Comment by glinton** [comment]
@ariyu08 do you think you can test with whichever build suits you, setting the `timeout` config setting:

<ul>
  <li><details><summary>darwin/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/darwin/amd64/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/darwin/amd64/telegraf-1.13.0%7Efda86c7a_darwin_amd64.tar.gz">telegraf-1.13.0~fda86c7a_darwin_amd64.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>freebsd/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.13.0%7Efda86c7a_freebsd_amd64.tar.gz">telegraf-1.13.0~fda86c7a_freebsd_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.13.0%7Efda86c7a_freebsd_i386.tar.gz">telegraf-1.13.0~fda86c7a_freebsd_i386.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>linux/</summary><ul>
    <li><details><summary>s390x</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Efda86c7a-0.s390x.rpm">telegraf-1.13.0~fda86c7a-0.s390x.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Efda86c7a_linux_s390x.tar.gz">telegraf-1.13.0~fda86c7a_linux_s390x.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.13.0%7Efda86c7a-0_s390x.deb">telegraf_1.13.0~fda86c7a-0_s390x.deb</a></li>
    </li></ul></details>
    <li><details><summary>static_amd64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.13.0%7Efda86c7a-static_linux_amd64.tar.gz">telegraf-1.13.0~fda86c7a-static_linux_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>armel</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Efda86c7a-0.armel.rpm">telegraf-1.13.0~fda86c7a-0.armel.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Efda86c7a_linux_armel.tar.gz">telegraf-1.13.0~fda86c7a_linux_armel.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.13.0%7Efda86c7a-0_armel.deb">telegraf_1.13.0~fda86c7a-0_armel.deb</a></li>
    </li></ul></details>
    <li><details><summary>armhf</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Efda86c7a-0.armv6hl.rpm">telegraf-1.13.0~fda86c7a-0.armv6hl.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Efda86c7a_linux_armhf.tar.gz">telegraf-1.13.0~fda86c7a_linux_armhf.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.13.0%7Efda86c7a-0_armhf.deb">telegraf_1.13.0~fda86c7a-0_armhf.deb</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Efda86c7a-0.i386.rpm">telegraf-1.13.0~fda86c7a-0.i386.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Efda86c7a_linux_i386.tar.gz">telegraf-1.13.0~fda86c7a_linux_i386.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.13.0%7Efda86c7a-0_i386.deb">telegraf_1.13.0~fda86c7a-0_i386.deb</a></li>
    </li></ul></details>
    <li><details><summary>mipsel</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf-1.13.0%7Efda86c7a_linux_mipsel.tar.gz">telegraf-1.13.0~fda86c7a_linux_mipsel.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf_1.13.0%7Efda86c7a-0_mipsel.deb">telegraf_1.13.0~fda86c7a-0_mipsel.deb</a></li>
    </li></ul></details>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Efda86c7a-0.x86_64.rpm">telegraf-1.13.0~fda86c7a-0.x86_64.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Efda86c7a_linux_amd64.tar.gz">telegraf-1.13.0~fda86c7a_linux_amd64.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0%7Efda86c7a-0_amd64.deb">telegraf_1.13.0~fda86c7a-0_amd64.deb</a></li>
    </li></ul></details>
    <li><details><summary>arm64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Efda86c7a-0.arm64.rpm">telegraf-1.13.0~fda86c7a-0.arm64.rpm</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Efda86c7a_linux_arm64.tar.gz">telegraf-1.13.0~fda86c7a_linux_arm64.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.13.0%7Efda86c7a-0_arm64.deb">telegraf_1.13.0~fda86c7a-0_arm64.deb</a></li>
    </li></ul></details>
    <li><details><summary>mips</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf">telegraf</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf-1.13.0%7Efda86c7a_linux_mips.tar.gz">telegraf-1.13.0~fda86c7a_linux_mips.tar.gz</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf_1.13.0%7Efda86c7a-0_mips.deb">telegraf_1.13.0~fda86c7a-0_mips.deb</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>windows/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.13.0%7Efda86c7a_windows_amd64.zip">telegraf-1.13.0~fda86c7a_windows_amd64.zip</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.13.0%7Efda86c7a_windows_i386.zip">telegraf-1.13.0~fda86c7a_windows_i386.zip</a></li>
      <li><a href="https://42291-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
  </li></ul></details>

</ul>
