### ISSUE TITLE
Telegraf SNMP prepend "::" to the OID

### ISSUE THREAD

**Issue by lvrfrc87** [influxdata/telegraf#6478]
### Relevant telegraf.conf:
```
[[inputs.snmp]]
  agents = [ "x.x.x.x" ]
  version = 2
  community = "public"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = ".1.3.6.1.2.1.1.3.0"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = ".1.3.6.1.2.1.2.2"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = ".1.3.6.1.2.1.2.2.1.2"
      is_tag = true

```

### System info:

https://github.com/influxdata/sandbox

### Steps to reproduce:

Hi everybody,

I am doing some test with SNMP on TICK stack running on sandbox. I have configured the SNMP plugin using the OIDs as in config above

However when I run it, seems that telegraf prepend “::” in front of the OID like is expecting a MIB. 

```   telegraf_1 | ::.1.3.6.1.2.1.2.2: Unknown Object Identifier ```

**Comment by danielnelson** [comment]
This is a bug, I'll need to dig in deeper but I believe this error is being triggered because the `snmptranslate` and `snmptable` commands are not installed in the sandbox environment.

**Comment by MyaLongmire** [comment]
I am going to close this as `snmp` went through a major rewrite due to performance issues. If you are having issues with recent `snmp` update, please open another ticket with all relevant information.

**Comment by MWP** [comment]
This appears to still be an issue?

`  [[inputs.snmp.table]]
    oid = ".1.3.6.1.2.1.2.2"
    name = "interface"
    inherit_tags = ["sys_name"]
`

results in:
`
stats_telegraf | 2024-03-25T02:04:24Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing table interface: getting table columns: MIB search path: "/usr/share/snmp/mibs"
stats_telegraf | Cannot find module: At line 0 in (none)
stats_telegraf | ::.1.3.6.1.2.1.2.2: Unknown Object Identifier: exit status 1
`
