### ISSUE TITLE
Telegraf not working with a load balancer in front of ElasticSearch

### ISSUE THREAD

**Issue by Theoooooo** [influxdata/telegraf#6482]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "15s"
  flush_interval = "15s"
  hostname = "my-hostname"
  round_interval = true
[[inputs.cpu]]
  percpu = true
  totalcpu = true
[[inputs.disk]]
  ignore_fs = ["devtmpfs","tmpfs"]
[[inputs.diskio]]
  devices = ["sda","sdb"]
[[inputs.mem]]
[[inputs.system]]
[[inputs.net]]
  interfaces = ["ens*"]
[[outputs.elasticsearch]]
  urls = ["http://<my-loadbalancer-ip>:9200"]
  timeout = "15s"
  health_check_interval = "15s"
  index_name = "local_telegraf_my-hostname-%Y-%m-%d"
  username = "my-user"
  password = "my-password"
```

### System info:
CentOS 7 1804
Telegraf Version 1.12.2
HAProxy Version 1.8.20

### Steps to reproduce:

1. Create a simple load balancer (HAProxy for me) with one frontend and 2 backend corresponding at 2 ElasticSearch instances.
2. Configure your telegraf instance with the IP pointed at the load balancer IP.
3. Restart telegraf to make it reload the configuration file
4. Getting ``` telegraf[10980]: 2019-10-04T12:11:32Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'health check timeout: no Elasticsearch node available'```

### Expected behavior:
I was waiting for telegraf to send data to the ElasticSearch load balancer and then display them on a dashboard

### Actual behavior:
It seems telegraf can't rely on the load balancer IP and may expect a specific answer from the load balancer.

### Additional info:
Quick schema :
![image](https://user-images.githubusercontent.com/33425208/66207530-4acd1700-e6b3-11e9-9bbd-e76597e2269f.png).

I'm also using this LB to query Kibana, Grafana and other tools metrics to write data over here. I got some wazuh managers in a cluster who wrote data to the same LB soo it may be not related to the LB i'm using but rather from telegraf where how it handles communications with ElasticSearch

haproxy config :
```
global
  user haproxy
  group haproxy
defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5s
  timeout client 60s
  timeout server 60s

frontend Frontend_HTTP_9200
  bind LB_IP:9200
  use_backend ELASTIC_HTTP_9200

backend ELASTIC_HTTP_9200
  server host01a ip_1:9200 check inter 1000 rise 5 fall 1
  server host01b ip_2:9200 check inter 1000 rise 5 fall 1

```

Telegraf log :
``` 
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Starting Telegraf 1.12.2
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Loaded inputs: cpu disk diskio mem system net
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Loaded aggregators:
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Loaded processors:
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Loaded outputs: elasticsearch
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! Tags enabled: host=my-hostname
Oct 04 14:11:27 my-hostname telegraf[10980]: 2019-10-04T12:11:27Z I! [agent] Config: Interval:15s, Quiet:false, Hostname:"my-hostname", Flush Interval:15s
Oct 04 14:11:32 my-hostname telegraf[10980]: 2019-10-04T12:11:32Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'health check timeout: no Elasticsearch node available'
-- Subject: Unit telegraf.service has begun shutting down
-- Unit telegraf.service has begun shutting down.

```

**Comment by danielnelson** [comment]
In general this means that the connection to Elasticsearch was not successful.  You could try using curl to duplicate the health check request from the same host as Telegraf, it should just be something like:
```
curl -X HEAD -v http://<my-loadbalancer-ip>:9200"
```

**Comment by Theoooooo** [comment]
@danielnelson Hum that could be weird i'm already doing POST and GET requests with Application/Json in the header from what i said above.

The request is also working properly here :
```
curl -X HEAD -v http://xxx.xxx.xxx.58:9200 -u elastic:my-pasword
* About to connect() to xxx.xxx.xxx.58 port 9200 (#0)
*   Trying xxx.xxx.xxx.58...
* Connected to xxx.xxx.xxx.58 (xxx.xxx.xxx.58) port 9200 (#0)
* Server auth using Basic with user 'elastic'
> HEAD / HTTP/1.1
> Authorization: Basic ZWxhc3RpYzpqbHRMajJWVTVmMF9QX1N5a050bQ==
> User-Agent: curl/7.29.0
> Host: xxx.xxx.xxx.58:9200
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 541
<
```
I don't really know where the issue can occur

**Comment by danielnelson** [comment]
If you set the `health_check_interval = "0s"` does it then fail on the first write?

**Comment by Theoooooo** [comment]
I'm getting another error because Telegraf is not able to retreive the ElasticSearch version of the nodes behind the LB. Normally, Telegraf retreive the ElasticSearch version and display it in the journalctl or in the service status command.

But i'm not getting any version numbers here with ``` health_check_interval = "0s" ```

Log :
```
Oct 07 09:25:34 my-hostname systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Starting Telegraf 1.12.2
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Loaded inputs: disk diskio mem system net cpu
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Loaded aggregators:
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Loaded processors:
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Loaded outputs: elasticsearch
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! Tags enabled: host=my-hostname
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z I! [agent] Config: Interval:15s, Quiet:false, Hostname:"my-hostname", Flush Interval:15s
Oct 07 09:25:34 my-hostname telegraf[26203]: 2019-10-07T07:25:34Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'Elasticsearch version not supported: '

```

**Comment by danielnelson** [comment]
I'm really not sure then, if it is working with a direct connection then I think it must be an issue with the HAProxy setup.  It might be worth using tcpdump/Wireshark to compare the connection to HAProxy with those from a direct connection.

**Comment by lpic10** [comment]
> Which query telegraf use to retreive informations about the cluster ?

https://github.com/olivere/elastic/blob/ca187de54e8160a36bd3e2a85cd30447d83b80ed/client.go#L1786
https://github.com/olivere/elastic/blob/release-branch.v5/ping.go

As I understand it is only doing a GET on the url defined.

**Comment by Theoooooo** [comment]
The weird thing is, the LB is not working only for Telegraf. If i'm doing manual curl or queries from other services like Kibana or Grafana it's working properly.

Dunno what's going on here. i'm gonna try to investigate a bit and mess with my HAProxy config

**Comment by glinton** [comment]
> I'm gonna try to investigate a bit

I would start with what Daniel suggested above and do a packet capture so you can verify each request going from telegraf to the LB before changing settings, but you might get lucky and change the right thing first :wink:

**Comment by Theoooooo** [comment]
Just as a reminder i didn't have the time i want to properly test this out. When i got free time i will investigate this issue :/

**Comment by danielnelson** [comment]
Closing, but let us know if we need to reopen.
