### ISSUE TITLE
Specify individual Linux flavor input plugin counters

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#6485]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Specify specific performance metrics instead of all of what is collected by the input plugin.
### Current behavior:
As an example the Telegraf config file with a input plugin `inputs.disk` will collect the fields:
```
free (integer, bytes)
total (integer, bytes)
used (integer, bytes)
used_percent (float, percent)
inodes_free (integer, files)
inodes_total (integer, files)
inodes_used (integer, files)
```
### Desired behavior:
Be able to specify which metrics I want to be collected such as:
```
used_percent (float, percent)
inodes_free (integer, files)
```
Similar to how the `inputs.win_perf_counters` can specify specific counters:
```
   [[inputs.win_perf_counters.object]]
     # Disk times and queues
     ObjectName = "LogicalDisk"
     Instances = ["*"]
     Counters = [
       "% Disk Time","% Disk Read Time","% Free Space",
       "% Disk Write Time", "Current Disk Queue Length", "Disk Transfers/sec",
       "Disk Bytes/sec","Disk Read Bytes/sec", "Disk Write Bytes/sec", "Avg. Disk sec/Read","Avg. Disk sec/Write",
       "Disk Reads/Sec","Disk Writes/sec"
     ]
     Measurement = "win_disk"
```
### Use case: 
Only collect specific Linux metrics we care about similar to how the Windows input plugin does. 

We are attempting to make the Windows and Linux Telegraf config files as similar as possible and so we want to be surgical with what metrics are being gathered by the Linux input plugins.

**Comment by danielnelson** [comment]
What we suggest for this is to use the `fieldpass` and `fielddrop` [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) options to whitelist/blacklist the fields that you don't want.
