### ISSUE TITLE
proxysql input-plugin

### ISSUE THREAD

**Issue by hsafe** [influxdata/telegraf#6487]
## Feature Request
Hi there,
Was wondering while implementations like Aerospike exist, why there is no input plugin for proxysql? 

### Proposal:
As the solutions like clusterControl limits you for proxysql monitoring and leave it to the paid version and nothing really is out there as alternative; I just can't imagine how useful the plugin will be.

**Comment by danielnelson** [comment]
We have a few proposed plugins, but as of yet haven't had the time to review.  I'm going to close this issue since we already have #6030.

https://github.com/influxdata/telegraf/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+proxysql+
