### ISSUE TITLE
It should be possible to collect WMI indicators remotely from a telegraf.

### ISSUE THREAD

**Issue by yunsou** [influxdata/telegraf#6489]
## Feature Request

Telegraf can only collect window metrics from the local server.
However, if data is collected remotely, Telegraf can be installed only on the collection server, thus enabling simple infrastructure operation.
WMI is support to collect to remote window server metric, and logstash has a wmi input plugin.
I expect remote collect to be supported in Telegraf.

### Proposal:
I propose that the configuration for remote host access will be added to the win_perf_counters plugin.

### Current behavior:
Current win_perf_counters is like this

```
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    IncludeTotal=true
```
### Desired behavior:
Suggestion is like this
```
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    Host:"Hostname" 
    User:"Username" 
    Password:"Password"
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    IncludeTotal=true
```

### Use case: 
In multiple server infra, engineers do not need to install telegraf on every server.
Only several collection servers need to be managed.

**Comment by danielnelson** [comment]
This was part of #4076, although without username/password support, but the work ended up being split and the remote feature has not made it in yet.  Without username/password support it would be quite straightforward to add, but I'm not sure how username and password can be sent, are you using another tool that allows this and can you show how it is used?

**Comment by yunsou** [comment]
@danielnelson  thanks for reply.
When using remote wmi, client should be send username/password for connecting remote window server.

In linux, you can use wmic util ([https://www.krenger.ch/blog/wmi-commands-from-linux/])
And In Logstash wmi input, has username/password.([https://www.elastic.co/guide/en/logstash/current/plugins-inputs-wmi.html])

**Comment by danielnelson** [comment]
This plugin is actually not using WMI, instead it loads pdh.dll directly.  A WMI plugin is in the backlog though (#1857) and it would be interesting to research the pros and cons of getting performance counters over WMI.

@vlastahajek Do you know what would be required to add remote support with/without username and password?

**Comment by yunsou** [comment]
@danielnelson  I was mistaken that telegraf win_perf used wmi. Telegraf seems to collect metrics in a similar way to metricbeat's system module.

**Comment by danielnelson** [comment]
If possible, I think we will want to keep remote authentication outside of Telegraf.  This seems like it would be more flexible with respect to different authentication methods and, of course, easier to maintain.

It appears we have an issue open for this #1899, so I'm going to close this one.  Let's do the basic remote collection first, and we can discuss adding how to best handle authentication in a dedicated issue.
