### ISSUE TITLE
'sensors' input unavailable for telegraf-0.10.2-1.x86_64 RPM

### ISSUE THREAD

**Issue by dvusboy** [influxdata/telegraf#649]
It appears the `telegraf` executable in the official RPM, specifically, `telegraf-0.10.2-1.x86_64.rpm`, does not support the `sensors` input:

```
# telegraf -usage sensors
2016/02/04 17:10:53 Input sensors not found and Output sensors not found
```

**Comment by dvusboy** [comment]
It looks like there is no provision in the `Makefile` or `build.py` to set the build-tag `sensors` when the `libsensors` library and header are available.

**Comment by sparrc** [comment]
Yes, this is true, setting that build flag slipped my mind. I'll make sure this is fixed for the next release.

**Comment by dvusboy** [comment]
@sparrc, thank you. On a slightly related note, it'd be nice to unify the `Makefile` with `build.py` so there's no chance they'd diverge, especially on the specifics of the build.

**Comment by sparrc** [comment]
@dvusboy this is actually going to be more difficult than I realized. As far as I can tell we would need to build directly on 32-bit and ARM to support those platforms (and we would have to statically link in the libraries in all cases). I think for the time being I'm going to have to say that the sensors plugin is only available for those building from source.

**Comment by dvusboy** [comment]
This is [the patch](https://gist.github.com/dvusboy/184118bc7b450fd9dcfb) I ended up using to make it work for x86_64. I definitely haven't explored other platforms.

**Comment by sparrc** [comment]
That is what I tried as well, but I found that the resulting build won't work on a box that doesn't have `lm-sensors` & `libsensors4-dev` installed, which makes me think that statically linking the C library would be best.

**Comment by leucos** [comment]
It seems that sensors input is still not present in 0.13 ?

```
# telegraf --version
Telegraf - version 0.13.0
# telegraf -usage sensors
2016/05/24 12:08:49 Input sensors not found and Output sensors not found
# apt-cache show telegraf
Package: telegraf
Version: 0.13.0-1
License: MIT
Vendor: InfluxData
Architecture: amd64
Maintainer: support@influxdb.com
Installed-Size: 32711
Homepage: https://github.com/influxdata/telegraf
Priority: extra
Section: default
Filename: pool/stable/t/telegraf/telegraf_0.13.0-1_amd64.deb
Size: 8996262
SHA256: 66ad4562846475694b59bb28631ab42e5349f0aca726508068294d642d935479
SHA1: 9497412af716dcf43ed83132423d21be5ccd4821
MD5sum: f5d7979a1918242a1677add1d94f0d68
Description: Plugin-driven server agent for reporting metrics into InfluxDB.
Description-md5: d2895f6fb51f407b1ee4231b2cf7a956
```

**Comment by sparrc** [comment]
> I think for the time being I'm going to have to say that the sensors plugin is only available for those building from source.

**Comment by dvusboy** [comment]
I do have one more comment on this issue: Is there a reason why `github.com/md14454/gosensors` is not in the `Godeps` file? Building from source breaks because that dependency is not pulled by `gdm`.

**Comment by sparrc** [comment]
@dvusboy because `gdm save` would need the `sensors` flag turned on in order to see that dependency. This is not hard to workaround, just run `go get ./...` after `gdm restore`

**Comment by zbindenren** [comment]
Another solution would be to invoke the sensors command from the lm_sensors package.

**Comment by sparrc** [comment]
correct, I think that is a much simpler solution. Requires forking a process off but it might be worth it. Telegraf isn't a C project and it needs to be able to be cross-compiled, so I doubt there will ever be a pre-built solution for the sensors plugin in it's current form.

**Comment by zbindenren** [comment]
if you want I can write a plugin with exec...

**Comment by sparrc** [comment]
that would be great, but I would prefer if you just modify the existing sensors plugin

**Comment by dvusboy** [comment]
Thanks. I'm not a big fan of having to fork a process to do this, as in the IPMI plugin. But it is what it is to avoid a build-time dependency.
