### ISSUE TITLE
Github Plugin Could Support More Useful Queries

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/telegraf#6497]
## Feature Request

Collect more detailed Github data to allow for more detailed queries.

### Proposal:
I would like to be able to use InfluxDB 2.0 Cloud to run queries like:
 * How many issues are open for a repo? (already supported)
 * What is the current mean time for an issue to move between states?
 * How many issue comments were added?
 * What is the current mean time for a pull request to get reviewed?
 * What percentage of pull requests pass?
 * etc...

### Current behavior:
The current plugin reports counts of Forks, Open Issues, Stars, etc...

### Desired behavior:
Logging of issues as they occur so that more complex queries and dashboards can be created.

### Use case: 
Allows Project Managers to use Github in meaningful ways to help manage their projects and teams.

**Comment by glinton** [comment]
The current github plugin is a polling based plugin (it reaches out at specified intervals and fetches data from github). I think you might want to look at the [github webhook](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/webhooks/github) input plugin. I [imagine](https://developer.github.com/webhooks/) you can get the streaming data you are looking for from that.

**Comment by rickspencer3** [comment]
Yes, this looks like exactly what I wanted. Thanks.
