### ISSUE TITLE
Support for libvirt/kvm

### ISSUE THREAD

**Issue by thecodeassassin** [influxdata/telegraf#65]
Are there plans to support polling metrics from libvirt/kvm ?

**Comment by sparrc** [comment]
@thecodeassassin Yes! There are plans to support libvirt performance metrics

**Comment by neckhair** [comment]
Pull-Request for this is #357

**Comment by danielnelson** [comment]
I'm going to close this issue in favor of #690 which has more discussion but is otherwise a duplicate.
