### ISSUE TITLE
Needed help in exec module of telegraf

### ISSUE THREAD

**Issue by suraganijanakiram** [influxdata/telegraf#6500]
I have a test script like below

# cat test.sh
```sh
#!/bin/bash
cat /etc/redhat-release|awk -F " " '{ print substr($0, index($0,$1)) }'
sudo /usr/sbin/dmidecode -t 4 | grep Version | head -1 | awk -F " " '{ print substr($0, index($0,$2)) }'
sudo /usr/sbin/dmidecode -t 1 | grep Product |awk -F ":" {'print $2'}| awk -F " " '{ print substr($0, index($0,$1)) }'
```

the above will give output like below in the server.

# ./test.sh
```
Red Hat Enterprise Linux Server release 7 (Maipo)
Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
ProLiant DL360 Gen9
```

the problem is when i get the data in grafana it was like in a same line like below.

```
Red Hat Enterprise Linux Server release 7 (Maipo) Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz ProLiant DL360 Gen9
```

but want to get the data like i get in the server like below

```
Red Hat Enterprise Linux Server release 7 (Maipo)
Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
ProLiant DL360 Gen9
```

can you please let me know how i should configure the exec module in telegraf to get the expected output.

my present exec module in telegraf (/etc/telegraf/telegraf.conf) configuration is like below.

```toml
[[inputs.exec]]
  commands = ["/tmp/test.sh"]
  name_suffix = "cpumodel"
  data_format = "value"
  data_type = "string"
```

Thanks in advance.

**Comment by reimda** [comment]
I suspect your telegraf output has the newlines like you expect and the newlines are being converted to spaces somewhere later, possibly in grafana.  You can verify this by running telegraf with `--test` which will output to stdout.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
