### ISSUE TITLE
(vSphere) Are "active" or "real time" values possible?

### ISSUE THREAD

**Issue by junior466** [influxdata/telegraf#6506]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Active values (Active memory consumptions instead of average).
### Current behavior:
Value is average.
### Desired behavior:
Real time values
### Use case: 

I believe this to be a limitation by vSphere but I'd thought I'd ask it here since I don't know where else to research this. 

I am using vSphere plugin to monitor my VMware enviroment using Grafana and I noticed that most of the values are shown as "average" and even though I select the "last" option while configuring a graph in Grafana, I still only receive average values. 

Here's an example: 

A Virtual Machine that is currently being monitored. When I log in though SSH, it shows 70% memory usage.

![Screen Shot 2019-10-09 at 4 42 36 PM](https://user-images.githubusercontent.com/22748735/66526152-a9d0c880-eac5-11e9-98d1-e9564772c99d.png)

Here's my Grafana graph:

![Screen Shot 2019-10-09 at 7 09 52 PM](https://user-images.githubusercontent.com/22748735/66526978-66c42480-eac8-11e9-83a2-70a8cb84daf3.png)

As you can see, it appears that the first image shows real time values but in Grafana, I only see what appears to be "average" values. 

Simply the way vSphere works?

**Comment by prydin** [comment]
The "average" value is an average over the last 20 seconds. Also, memory usage as seen from within the guest is different from what vSphere reports, which is from the perspective of the hypervisor. 20 second intervals is as "real time" as you will get from vCenter.

**Comment by reimda** [comment]
If you'd like to see the memory usage from the guest OS perspective (70% in your example), you could install telegraf on the guest OS.

Looks like the question is answered and there's no change to be made in the vSphere plugin.  Closing the FR.  We can reopen if there's more information.
