### ISSUE TITLE
ipvs: Failed to list IPVS services

### ISSUE THREAD

**Issue by deric** [influxdata/telegraf#6510]
### Relevant telegraf.conf:

```toml
[[inputs.ipvs]]
```

### System info:

 * Telegraf 1.12.3
 * Debian 9

### Steps to reproduce:

1. Enable ipvs plugin
2. Restart telegraf

### Expected behavior:

```
telegraf -config /etc/telegraf/telegraf.conf -test -input-filter ipvs 
2019-10-10T12:04:28Z I! Starting Telegraf 1.12.3
> ipvs_virtual_server,address=11.17.135.123,address_family=inet,host=f03,netmask=32,port=5500,protocol=tcp,role=frontend,sched=wlc,zone=ca bytes_in=0i,bytes_out=0i,connections=0i,cps=0i,pkts_in=0i,pkts_out=0i,pps_in=0i,pps_out=0i 1570709068000000000
> ipvs_real_server,address=192.168.0.34,address_family=inet,host=f03,port=16612,role=frontend,virtual_address=11.17.135.123,virtual_port=5500,virtual_protocol=tcp,zone=ca active_connections=0i,bytes_in=0i,bytes_out=0i,connections=0i,cps=0i,inactive_connections=0i,pkts_in=0i,pkts_out=0i,pps_in=0i,pps_out=0i 1570709068000000000
> ipvs_virtual_server,address=11.17.135.123,address_family=inet,host=f03,netmask=32,port=5501,protocol=tcp,role=frontend,sched=wlc,zone=ca bytes_in=0i,bytes_out=0i,connections=0i,cps=0i,pkts_in=0i,pkts_out=0i,pps_in=0i,pps_out=0i 1570709068000000000
```

### Actual behavior:

```
Oct 10 12:02:10 f03 telegraf[26140]: 2019-10-10T12:02:10Z E! [inputs.ipvs] Error in plugin: Failed to list IPVS services
Oct 10 12:02:20 f03 telegraf[26140]: 2019-10-10T12:02:20Z E! [inputs.ipvs] Error in plugin: Failed to list IPVS services
Oct 10 12:02:30 f03 telegraf[26140]: 2019-10-10T12:02:30Z E! [inputs.ipvs] Error in plugin: Failed to list IPVS services
Oct 10 12:02:40 f03 telegraf[26140]: 2019-10-10T12:02:40Z E! [inputs.ipvs] Error in plugin: Failed to list IPVS services
```

### Additional info:
In test mode plugin seems to be collecting expected data, but during actual run each time an error is logged: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ipvs/ipvs.go#L47

**Comment by glinton** [comment]
This sounds like the error is permissions related. Have you verified you have granted sufficient permissions for the user that the telegraf is running as. [link to docs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ipvs#permissions)

**Comment by deric** [comment]
@glinton Thanks! Could we make the error message a bit more helpful? Either print error messages from `github.com/docker/libnetwork/ipvs` or suggest to check `CAP_NET_ADMIN` and `CAP_NET_RAW` permissions?

Running the test as `telegraf` helps, it shows the WARN message that is not forwarded to journal log.
```
su - telegraf -s /bin/sh -c "telegraf -config /etc/telegraf/telegraf.conf -test -input-filter ipvs"
2019-10-14T08:40:56Z I! Starting Telegraf 1.12.3
WARN[0000] Running modprobe ip_vs failed with message: ``, error: exec: "modprobe": executable file not found in $PATH 
2019-10-14T08:40:56Z E! [inputs.ipvs] Error in plugin: Failed to list IPVS services
2019-10-14T08:40:56Z E! [telegraf] Error running agent: One or more input plugins had an error
```

**Comment by deric** [comment]
Just for reference. On Debian based system you'll need `libcap2-bin` package. Capabilities can be set using:
```
setcap cap_net_admin,cap_net_raw+ep /usr/bin/telegraf
```
and check capabilities for `telegraf` binary:
```
getcap /usr/bin/telegraf
/usr/bin/telegraf = cap_net_admin,cap_net_raw+ep
```
The modprobe error is another issue, telegraf doesn't have permissions to use `modprobe` (which is probably ok).
```
su - telegraf -s /bin/sh -c "telegraf -config /etc/telegraf/telegraf.conf -test -input-filter ipvs"
2019-10-14T09:07:30Z I! Starting Telegraf 1.12.3
WARN[0000] Running modprobe ip_vs failed with message: ``, error: exec: "modprobe": executable file not found in $PATH
```

**Comment by danielnelson** [comment]
I've included the libnetwork messages in our error messages to aid with debugging, and I also routed the log modprobe messages which were being written directly by the library through the Telegraf logger, you won't see them anymore unless you enable `--debug`.

I don't have an IPVS server setup right now, do you think you could test out the changes and let me know how it looks on your end?

- [telegraf_1.13.0~feff5408-0_amd64.deb](https://41976-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0~feff5408-0_amd64.deb)

**Comment by deric** [comment]
@danielnelson Thanks! Looks good:
```
# su - telegraf -s /bin/sh -c "telegraf -config /etc/telegraf/telegraf.conf -test -input-filter ipvs"
2019-10-16T13:32:08Z I! Starting Telegraf 
2019-10-16T13:32:08Z E! [inputs.ipvs] Error in plugin: failed to list IPVS services: operation not permitted
2019-10-16T13:32:08Z E! [telegraf] Error running agent: One or more input plugins had an error
```
with `-debug`:
```
su - telegraf -s /bin/sh -c "telegraf -config /etc/telegraf/telegraf.conf -test -debug -input-filter ipvs"
2019-10-16T13:33:27Z I! Starting Telegraf 
2019-10-16T13:33:27Z D! [agent] Initializing plugins
2019-10-16T13:33:27Z D! [logrus] Running modprobe ip_vs failed with message: ``, error: exec: "modprobe": executable file not found in $PATH
2019-10-16T13:33:27Z E! [inputs.ipvs] Error in plugin: failed to list IPVS services: operation not permitted
2019-10-16T13:33:27Z E! [telegraf] Error running agent: One or more input plugins had an error
```

**Comment by danielnelson** [comment]
@deric Thanks for the help testing.  BTW on the modprobe thing I'd prefer if libnetwork didn't attempt module insertion at all, or at least if it were an optional attempt, but right now the library always tries.  Maybe someone could open a PR against libnetwork?
