### ISSUE TITLE
Include netcat in Docker image

### ISSUE THREAD

**Issue by Sarke** [influxdata/telegraf#6517]
## Feature Request

Include netcat `nc` in Docker image.

### Proposal:

As suggested by https://docs.influxdata.com/telegraf/v1.12/administration/troubleshooting/#capture-output the use of `nc` can be useful.

### Current behavior:

Following the advice of the link above requires `apt update`, `apt install netcat`.

### Desired behavior:

That I can attach to the container and use `nc` without having to install it.

### Use case:

To use the troubleshooting advice in docker more easily.

Also, the command should be `nc -lup 8089` not `nc -lu 8089`.

**Comment by danielnelson** [comment]
Unfortunately, the list of things that could be useful is just too large to include them all.  For troubleshooting it makes sense to use the solution with `apt` you mentioned.  For plugins like `snmp`, `smart`, etc my recommendation is to build a derivative image.

How to do this isn't documented right now as far as I know, so let's make sure that gets done before closing this issue.

The port issue looks like a difference between the `netcat` package and `netcat-openbsd`, but the `-p` works in either case so I'll pass along the suggestion to add it as well.

**Comment by danielnelson** [comment]
https://github.com/docker-library/docs/pull/1588

**Comment by danielnelson** [comment]
Update to Docker Hub documentation has been merged with instructions on creating a derived image.
