### ISSUE TITLE
[inputs.tail] Add flag to ignore files if not found and not give error

### ISSUE THREAD

**Issue by deepaksood619** [influxdata/telegraf#6518]
## Feature Request
a flag to ignore if file not present, and not throw error in telegraf logs

### Current behavior:
Throws error for file not present

### Desired behavior:
Does not throw error and fail silently

### Use case: 
I don't want to create different configuration for each server because we are using ansible to deploy everything to servers
And I don't want to clutter Elasticsearch with error logs that are not needed

**Comment by danielnelson** [comment]
Closed by #6540
