### ISSUE TITLE
Bot not working in group chat, 

### ISSUE THREAD

**Issue by RodionCoach** [influxdata/telegraf#6519]
### Relevant telegraf.conf:

```toml
```

### System info:

Telegraf version - 3.32.0; OS Window 10; Node.js engine 10.16.3

### Expected behavior:
The bot should be working not only in private chat (like just I and bot),  and in group chat too.
### Actual behavior:
I have some problem with bot after integrating telegraf with koa, he can`t working in group chat, when I run it locally it`s work ok in long poll mode.
I`ve deploy my app on heroku, here below in attachments you can find screenshot of heroku log, When Im sending some command to bot in privat chat I`ve normally behavior (answer with code 200) but when Im sending some command to bot in group chat Im became trouble (answer with code 404) .
I guess this problem is due '/secret-path' - I do not understand how to work with him.
I`ve used this example:
https://github.com/telegraf/telegraf/blob/develop/docs/examples/koa-webhook-bot.js
Please, give me some solution. Thanks!
### Additional info:

![photo_2019-10-13_14-53-28](https://user-images.githubusercontent.com/25160654/66715262-c58be580-edc9-11e9-95fe-4b8ccf8bb102.jpg)
![2](https://user-images.githubusercontent.com/25160654/66715325-c1ac9300-edca-11e9-911a-bb9f9e8e40ff.PNG)

**Comment by glinton** [comment]
I believe you have the wrong repo, this telegraf is the plugin-driven server agent for collecting and reporting metrics. You are likely looking for https://github.com/telegraf/telegraf
