### ISSUE TITLE
Result code is not set correctly with ping and method = "native"

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6521]
Hi,
telegraf version: telegraf-1.12.2

I am monitoring 3000 IPs from a single telegraf config file, using method "native". PFB telegraf configuration for ping:
[agent]
  interval = "120s"

[[inputs.ping]]
urls = ["**********","*****", "10.10.10.10"]
method = "native"
count = 3
timeout = 10.0

below is the output of this configuration:
[root@N1VL-PA-INFL01 ~]# telegraf --config /etc/telegraf/telegraf.conf --test | grep -i 10.10.10.10
2019-10-14T08:00:23Z I! Starting Telegraf 1.12.2
> ping,IP=10.14.124.23,host=N1VL-PA-INFL01,url=10.10.10.10 average_response_ms=1.437718,maximum_response_ms=2.466695,minimum_response_ms=0.660697,packets_received=3i,packets_transmitted=3i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.758515,ttl=63i 1571040027000000000

where this IP does not exist, and result_code should not be 0:

[root@N1VL-PA-INFL01 ~]# ping -c 3 -W 10 10.10.10.10
PING 10.10.10.10 (10.10.10.10) 56(84) bytes of data.

--- 10.10.10.10 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

[root@N1VL-PA-INFL01 ~]#

there is few IPs which are individually getting pinged from source server but in telegraf result_code is showing '2'.
Can you please help to rectify this error?

**Comment by glinton** [comment]
Can you try with the following build (whichever suits your environment) and get back to us:
<ul>

  <li><details><summary>freebsd/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.13.0%7Ebe03a7e8_freebsd_amd64.tar.gz">telegraf-1.13.0~be03a7e8_freebsd_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.13.0%7Ebe03a7e8_freebsd_i386.tar.gz">telegraf-1.13.0~be03a7e8_freebsd_i386.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>linux/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Ebe03a7e8-0.x86_64.rpm">telegraf-1.13.0~be03a7e8-0.x86_64.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Ebe03a7e8_linux_amd64.tar.gz">telegraf-1.13.0~be03a7e8_linux_amd64.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0%7Ebe03a7e8-0_amd64.deb">telegraf_1.13.0~be03a7e8-0_amd64.deb</a></li>
    </li></ul></details>
    <li><details><summary>armhf</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Ebe03a7e8-0.armv6hl.rpm">telegraf-1.13.0~be03a7e8-0.armv6hl.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Ebe03a7e8_linux_armhf.tar.gz">telegraf-1.13.0~be03a7e8_linux_armhf.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.13.0%7Ebe03a7e8-0_armhf.deb">telegraf_1.13.0~be03a7e8-0_armhf.deb</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Ebe03a7e8-0.i386.rpm">telegraf-1.13.0~be03a7e8-0.i386.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Ebe03a7e8_linux_i386.tar.gz">telegraf-1.13.0~be03a7e8_linux_i386.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.13.0%7Ebe03a7e8-0_i386.deb">telegraf_1.13.0~be03a7e8-0_i386.deb</a></li>
    </li></ul></details>
    <li><details><summary>s390x</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Ebe03a7e8-0.s390x.rpm">telegraf-1.13.0~be03a7e8-0.s390x.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Ebe03a7e8_linux_s390x.tar.gz">telegraf-1.13.0~be03a7e8_linux_s390x.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.13.0%7Ebe03a7e8-0_s390x.deb">telegraf_1.13.0~be03a7e8-0_s390x.deb</a></li>
    </li></ul></details>
    <li><details><summary>static_amd64</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.13.0%7Ebe03a7e8-static_linux_amd64.tar.gz">telegraf-1.13.0~be03a7e8-static_linux_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>arm64</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Ebe03a7e8-0.arm64.rpm">telegraf-1.13.0~be03a7e8-0.arm64.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Ebe03a7e8_linux_arm64.tar.gz">telegraf-1.13.0~be03a7e8_linux_arm64.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.13.0%7Ebe03a7e8-0_arm64.deb">telegraf_1.13.0~be03a7e8-0_arm64.deb</a></li>
    </li></ul></details>
    <li><details><summary>armel</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Ebe03a7e8-0.armel.rpm">telegraf-1.13.0~be03a7e8-0.armel.rpm</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Ebe03a7e8_linux_armel.tar.gz">telegraf-1.13.0~be03a7e8_linux_armel.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.13.0%7Ebe03a7e8-0_armel.deb">telegraf_1.13.0~be03a7e8-0_armel.deb</a></li>
    </li></ul></details>
    <li><details><summary>mips</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf-1.13.0%7Ebe03a7e8_linux_mips.tar.gz">telegraf-1.13.0~be03a7e8_linux_mips.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf_1.13.0%7Ebe03a7e8-0_mips.deb">telegraf_1.13.0~be03a7e8-0_mips.deb</a></li>
    </li></ul></details>
    <li><details><summary>mipsel</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf">telegraf</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf-1.13.0%7Ebe03a7e8_linux_mipsel.tar.gz">telegraf-1.13.0~be03a7e8_linux_mipsel.tar.gz</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf_1.13.0%7Ebe03a7e8-0_mipsel.deb">telegraf_1.13.0~be03a7e8-0_mipsel.deb</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>windows/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.13.0%7Ebe03a7e8_windows_amd64.zip">telegraf-1.13.0~be03a7e8_windows_amd64.zip</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.13.0%7Ebe03a7e8_windows_i386.zip">telegraf-1.13.0~be03a7e8_windows_i386.zip</a></li>
      <li><a href="https://41927-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
  </li></ul></details>

</ul>

**Comment by priyankamondalairtel** [comment]
Upgraded telegraf agent with the rpm version provided below:

[root@N1VL-PA-INFL01 ~]# rpm -qa | grep -i telegraf
telegraf-1.13.0~be03a7e8-0.x86_64
[root@N1VL-PA-INFL01 ~]#


Still getting same error that getting result_code as 0, where this IP is actually not exist.

[root@N1VL-PA-INFL01 ~]# telegraf --config /etc/telegraf/telegraf.conf --test | grep -i 10.10.10.10
2019-10-15T05:05:16Z I! Starting Telegraf
> ping,IP=10.14.124.23,host=N1VL-PA-INFL01,url=10.10.10.10 average_response_ms=6.369094,maximum_response_ms=13.092524,minimum_response_ms=0.02276,packets_received=3i,packets_transmitted=3i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=5.342367,ttl=60i 1571115919000000000
[root@N1VL-PA-INFL01 ~]# ping -c 3 -W 10 10.10.10.10
PING 10.10.10.10 (10.10.10.10) 56(84) bytes of data.

--- 10.10.10.10 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

[root@N1VL-PA-INFL01 ~]#

Regards,
Priyanka
+91 9899848737

**Comment by priyankamondalairtel** [comment]
can you please suggest if [[inputs.ping]] will work for 3000 IPs from a single config file using method 'exec'?

**Comment by danielnelson** [comment]
> Still getting same error that getting result_code as 0, where this IP is actually not exist.

Does this happen only when running with many IPs, or can you reproduce it with only the single address listed?

> 3000 IPs from a single config file using method 'exec'?

I think that would be too much, since it needs to fork a process for each IP.

**Comment by rguptarg** [comment]
For Native method, it is giving same result (result_code=0) either I am using single url/IP.

But for exe method , it is working properly but I can't use multiple url /IP under exe method.

**Comment by danielnelson** [comment]
@glinton Can you check the output below, I think we shouldn't emit any errors and only the last summary metric but with `result_code=2i`.

```toml
[[inputs.ping]]
  urls = ["10.10.10.10"]
  count = 3
  timeout = 1.0
  method = "native"
```

```
2019-10-17T19:44:13Z E! [inputs.ping] Error in plugin: context deadline exceeded
> ping,url=10.10.10.10 result_code=2i 1571341454000000000
2019-10-17T19:44:14Z E! [inputs.ping] Error in plugin: context deadline exceeded
> ping,url=10.10.10.10 result_code=2i 1571341455000000000
2019-10-17T19:44:15Z E! [inputs.ping] Error in plugin: context deadline exceeded
> ping,url=10.10.10.10 result_code=2i 1571341456000000000
> ping,url=10.10.10.10 packets_received=0i,packets_transmitted=3i,percent_packet_loss=100,result_code=0i 1571341456000000000
```

**Comment by priyankamondalairtel** [comment]
This output I am getting If there is only one IP. If there is more than one IP in [[inputs.ping]] metric, error is same.

**Comment by goller** [comment]
- [ ] Check what the result_code of ping exe is when the IP address is not reachable.
- [ ] Check what the result_code of ping exe is when the executable is not available.

> ping,IP=10.14.124.23,host=N1VL-PA-INFL01,url=10.10.10.10 average_response_ms=1.437718,maximum_response_ms=2.466695,minimum_response_ms=0.660697,packets_received=3i,packets_transmitted=3i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.758515,ttl=63i 1571040027000000000

Find root cause of ^^

**Comment by rguptarg** [comment]
Hi 

Please let me know if any output required from my end
