### ISSUE TITLE
Certificate plugin

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6524]
HI Team,

We are using [[inputs.x509_cert]] plugin and it's working fine but problem in read data properly(Human understandable) on Dashboard.

how can I convert date startdate/enddate (int, seconds) in IST (Indian Time) ?

**Comment by danielnelson** [comment]
This is a question about the dashboarding software (Grafana/Chronograf) you are using.  You can ask over at the [InfluxData Community](https://community.influxdata.com) site.
