### ISSUE TITLE
can't change port for postgresql_extensible plugin

### ISSUE THREAD

**Issue by mfy2a** [influxdata/telegraf#6527]
Hi,

i have 2 instances of postgres on same host, one on 5432 port, the other on 5433.

i can't get any point for 5433.
here is my conf:

```
[[inputs.postgresql_extensible]]
    address = "host=localhost port=5433 user=postgres sslmode=disable password=toto"
    databases = ["db2"]
    [[inputs.postgresql_extensible.query]]
      sqlquery="select count(*) as running_jobs from jobs where status=3;"
      version=901
      withdbname=false
      tagvalue="running_jobs"

[[inputs.postgresql_extensible]]
    address = "host=localhost user=postgres sslmode=disable password=toto"
    databases = ["db1"]
    [[inputs.postgresql_extensible.query]]
      sqlquery="SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()));"
      version=901
      withdbname=false
      tagvalue="replication"
```

when i run : 
```
 telegraf --input-filter postgresql_extensible --test --debug
2019-10-15T12:07:28Z I! Starting Telegraf 1.12.3
2019-10-15T12:07:28Z I! Using config file: /etc/telegraf/telegraf.conf
2019-10-15T12:07:28Z D! [agent] Initializing plugins
2019-10-15T12:07:28Z D! [agent] Starting service inputs
2019-10-15T12:07:28Z D! postgresql_extensible: column: date_part = float64: 0.416824
2019-10-15T12:07:28Z D! [agent] Waiting for service inputs
2019-10-15T12:07:28Z D! [agent] Stopping service inputs
> postgresql,db=postgres,host=myHost,server=host\=localhost\ user\=postgres\  date_part=0.416824 1571141249000000000```
i get info only for the second postgresql_extensible value.

i use telegraf --version
Telegraf 1.12.3 (git: HEAD 16784bca) (on centos7)

**Comment by danielnelson** [comment]
```
    [[inputs.postgresql_extensible.query]]
      sqlquery="select count(*) as running_jobs from jobs where status=3;"
      version=901
      withdbname=false
      tagvalue="running_jobs"
```

I think this may be because you are selecting a single column and then assigning it as a tag.  Telegraf filters out any metrics without fields, at least one is required for most time series databases.  Does it help if you remove the `tagvalue` option?

**Comment by mfy2a** [comment]
Hi,
thanks you for your answer, but it didn't change anything.

if i set port=5433 i got an error :

> 2019-10-31T09:04:35Z E! [inputs.postgresql_extensible] Error in plugin: ERROR: relation "jobs" does not exist (SQLSTATE 42P01)

by the way, if i querry the db2 manually, it works:
`psql -d job -p 5433 -U postgres -c "select count(*) as running_jobs from jobs where status=3;"
 running_jobs
--------------
          305`

if i try host=localhost:5433, i get no error, but when i run : 
`telegraf --input-filter postgresql_extensible --test --debug`
i get the value from db1 only 


the port 5433 is totally ignored, and i don't know how to set it "in the good way"

**Comment by danielnelson** [comment]
How about if you add `dbname=job` to the connection string?

**Comment by mfy2a** [comment]
You my hero !
i don't understand why i have to set twice my db name (in connection string and databases string) but it works great.
many thanks

**Comment by danielnelson** [comment]
The `databases` option works a bit differently, it is a bit confusing in my opinion.  If set it adds `IN ("db1", "db2")` to the end of the query, but only when the query has `withdbname = true.
