### ISSUE TITLE
TICKScript on x509_cert

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6528]
Hi,

x509_cert metric enabled to monitor certificates, but expiry field giving value in int format.
How can I enable alert in kapacitor to monitor if certificate expires in 15 days?

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests, so in the future please ask general usage questions at the [InfluxData Community](https://community.influxdata.com) site.  I expect that would just want to alert if the value is less than 15 * 86400.
