### ISSUE TITLE
Default values for Empty tags in SQL Server Performance counters

### ISSUE THREAD

**Issue by manojbadam** [influxdata/telegraf#6531]
## Feature Request

Need a default value for Empty tag values of SQLServer Performance Counters. Right now, there are few performance counters have empty `instance` tag Ex - 
```
sqlserver_performance,counter=Forwarded\ Records/sec,database_name=test,host=windev,object=SQLServer:Access\ Methods,sql_instance=localhost value=720873280 1571189520000000000
sqlserver_performance,counter=Buffer\ cache\ hit\ ratio,database_name=test,host=windev,object=SQLServer:Buffer\ Manager,sql_instance=localhost value=100 1571189520000000000
....
```
where as other Performance counters has the instance tag, Ex - 
```
sqlserver_performance,counter=Queued\ Request\ Count,database_name=test,host=windev,instance=internal,object=SQLServer:Workload\ Group\ Stats,sql_instance=localhost value=0 1571189050000000000
sqlserver_performance,counter=Request\ Count,database_name=test,host=windev,instance=default,object=SQLServer:Workload\ Group\ Stats,sql_instance=localhost value=1420706816 1571189050000000000
.....
```
Out of 250 sqlserver performance counters, 31 of them are having the instance tags as empty.

https://pasteboard.co/ICg1co0.png

### Proposal:

Update the Query to Add default value for "Empty" Instance value `CASE pc.instance_name WHEN '_Total' THEN 'Total' WHEN '' THEN 'NA' ELSE ISNULL(pc.instance_name,'defaultvalue') END AS [instance]`

Complete Query - 

```
select * from @PCounters order by counter_name 
SELECT	'sqlserver_performance' AS [measurement],
		REPLACE(@@SERVERNAME,'\',':') AS [sql_instance],
		DB_NAME() as [database_name],
		pc.object_name AS [object],
		pc.counter_name AS [counter],
		CASE pc.instance_name WHEN '_Total' THEN 'Total' WHEN '' THEN 'NA' ELSE ISNULL(pc.instance_name,'defaultvalue') END AS [instance],
		CAST(CASE WHEN pc.cntr_type = 537003264 AND pc1.cntr_value > 0 THEN (pc.cntr_value * 1.0) / (pc1.cntr_value * 1.0) * 100 ELSE pc.cntr_value END AS float(10)) AS [value]
FROM	@PCounters AS pc
		LEFT OUTER JOIN @PCounters AS pc1
			ON (
				pc.counter_name = REPLACE(pc1.counter_name,' base','')
				OR pc.counter_name = REPLACE(pc1.counter_name,' base',' (ms)')
			)
			AND pc.object_name = pc1.object_name
			AND pc.instance_name = pc1.instance_name
			AND pc1.counter_name LIKE '%base'
WHERE	pc.counter_name NOT LIKE '% base'
OPTION(RECOMPILE);
```
Happy to send the pull request

### Current behavior:

We have a custom wavefront rule to reject any metrics with empty tag values. Which is dropping these metrics. For now, came up with this work around to do tagexclude and push it. 

```
[[inputs.sqlserver]]
  # QA1 DB 
  servers = [
    "Server=localhost;Port=1433;User Id=sa;Password=myp@ssw0rd;"
  ]
  query_version = 2
  name_override = "sqlserver_perf_override"
  namepass = ["sqlserver_performance"]
  tagexclude = ["instance"]
  [inputs.sqlserver.tagpass]
  	instance = [""]
```

### Desired behavior:

With Default configuration, dont see any empty values

```
[[inputs.sqlserver]]
  # QA1 DB 
  servers = [
    "Server=localhost;Port=1433;User Id=sa;Password=myp@ssw0rd;"
  ]
  query_version = 2
```

### Use case: 

With various types of output plugins, leaving the empty tag values can always be under risk of missing metrics.

**Comment by danielnelson** [comment]
I'm not entirely sure I'm understanding correctly, for `sqlserver_performance` measurements without an instance tag you would like to add the tag with a default value?

> We have a custom wavefront rule to reject any metrics with empty tag values.

Again to clarify, since some of the `sqlserver_performance` measurements have the instance tag, this requires all `sqlserver_performance` to have this tag?

**Comment by manojbadam** [comment]
@danielnelson -
> I'm not entirely sure I'm understanding correctly, for sqlserver_performance measurements without an instance tag you would like to add the tag with a default value?

No, I would like to add a default value when the value is empty, rn few counters of `sqlserer_performance` metrics  have empty values for `instance` tag.

When i ran the `terraform --config mssql-metrics.conf --test` with default configuration i don't see the `instance` tag at all for these counters. Although its value is empty, the tag is completely missing here (which is still good). 

But when we send these metrics to our custom output plugin, i can see that tag with empty value `instance=''` and causing trouble to parse it. 

I initially thought the tag and empty string is introduced by our custom output plugin, but when i modified the input plugin and added filters to display only empty values. It filtered out those counters. And these are getting passed from telegraf agent and [SQL query](https://github.com/influxdata/telegraf/blob/c8f4215ac5f9b4d17d36545cea0ac6f2abfb2002/plugins/inputs/sqlserver/sqlserver.go#L643-L659). 

#### With Default configuration
```
[[inputs.sqlserver]]
  # QA1 DB 
  servers = [
    "Server=localhost;Port=1433;User Id=sa;Password=myp@ssw0rd;"
  ]
  query_version = 2
```

Metrics we see with `telegraf --config mssql-metrics.conf --test`
```
....
sqlserver_performance,counter=Forwarded\ Records/sec,database_name=test,host=windev,object=SQLServer:Access\ Methods,sql_instance=localhost value=720873280 1571189520000000000
sqlserver_performance,counter=Buffer\ cache\ hit\ ratio,database_name=test,host=windev,object=SQLServer:Buffer\ Manager,sql_instance=localhost value=100 1571189520000000000
.....
```
Note - There is no `instance` tag here 

#### With Empty value Filters configuration
```
[[inputs.sqlserver]]
  # QA1 DB 
  servers = [
    "Server=localhost;Port=1433;User Id=sa;Password=myp@ssw0rd;"
  ]
  query_version = 2
  namepass = ["sqlserver_performance"]
  tagexclude = ["instance"]
  [inputs.sqlserver.tagpass]
  	instance = [""]
```

Metrics we see with `telegraf --config mssql-metrics.conf --test`
```
sqlserver_performance,counter=Forwarded\ Records/sec,database_name=test,host=windev,object=SQLServer:Access\ Methods,sql_instance=localhost value=720873280 1571189520000000000
sqlserver_performance,counter=Buffer\ cache\ hit\ ratio,database_name=test,host=windev,object=SQLServer:Buffer\ Manager,sql_instance=localhost value=100 1571189520000000000
.....30 more metrics
```
Here, when i filter it with empty `instance` tag value, i see only these metrics. 

So if we can add a default value in `SQL Query` we can not have empty tags

**Comment by danielnelson** [comment]
> But when we send these metrics to our custom output plugin, i can see that tag with empty value instance='' and causing trouble to parse it.

In general Telegraf does allow for empty tag values, though many output and serializer plugins will remove these tags.  This is why when you run with `--test` the `instance` tag is not shown, the influx data format doesn't allow for it and it is removed.

I'm pretty sure the `wavefront` output does this as well, based on a quick code inspection, but if you are using a custom output you should handle empty tag values there.  There could very well be other input plugins that create tags with empty values.

We wouldn't want to add a default tag value though, this isn't a pattern we generally use, and it would likely require the addition of a new option to control it's behavior.

Overall the best solution would be to have the output plugin strip these tags, outside of that the best no code solution would be with the `override` processor.  This conf will only add the tag value when it is not already set, and not interfere with any other metrics:
```toml
[[processors.override]]
  namepass = ["sqlserver_performance"]

  [processors.override.tagpass]
    instance = [""]

  [processors.override.tags]
    instance = "unknown"
```

Closing the issue but let me know if you have any follow up questions.
