### ISSUE TITLE
Field names are being stored with the prefix of the input plugin name in Elasticsearch using elasticsearch output plugin

### ISSUE THREAD

**Issue by Lakshmi914** [influxdata/telegraf#6535]
In telegraf config file I am using using kafka consumer input plugin and elastic search output plugin.
So the field names i.e the column names of the index in elastic search are getting created as kafka_consumer.field_name1,kafka_consumer.field_name2, where as we want the field names just as field_name1, field_namw2.
Please let me know how to resolve this issue.
Thanks in advance.

**Comment by danielnelson** [comment]
It isn't possible to change this in the output, the fields are always nested under the measurement name like in these examples:

https://github.com/influxdata/telegraf/tree/master/plugins/outputs/elasticsearch#example-events

It is possible to change the measurement name to something more descriptive for the data though, just use `name_override = "mymetric"`.

**Comment by Lakshmi914** [comment]
Thanks @danielnelson... where do i need add name_override, please let me know.

**Comment by danielnelson** [comment]
You can set it on any input plugin:
```
[[inputs.kafka_consumer]]
  name_override = "mymetric"
  ## ... other options
```

**Comment by Lakshmi914** [comment]
I have tried with the above fix but it has not fulfilled our requirement.
How telegraf is putting field names in elasticsearch is kafka_consumer.field_name
What my requirement is just field_name in elasticsearch through telegraf

If there is any way to do this please let me know.
TIA

**Comment by danielnelson** [comment]
You could use the `exec` output with a custom script.
