### ISSUE TITLE
Add configuration option for acceptable http response code to http input plugin

### ISSUE THREAD

**Issue by perzizzle** [influxdata/telegraf#6538]
## Feature Request
Add support to the http input plugin for an acceptable range of http response codes. Currently, only http 200 responses are accepted, all others return an error message. 

### Proposal:
Add a configuration value for expected http status codes.
http_status_codes: [200, 400, 500]

Update https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http/http.go#L174 to validate against this configuration value rather than assume only 200s.

### Current behavior:
> telegraf --config ./health_response.conf --test
2019-10-17T13:44:40Z I! Starting Telegraf 1.9.3
2019-10-17T13:44:41Z E! [inputs.http]: Error in plugin: [url=http://localhost:8080/application/health]: Received status code 429 (Too Many Requests), expected 200 (OK)

### Desired behavior:
Parse http response if http response is in acceptable ranged.

### Use case: 
We are using this plugin to gather the response to our consul health checks (http 200, 429, 503) signifying the health of the service. It is useful for troubleshooting flapping services as well trending changes over time. The consul input plugin only gathers status, doesn't return the body of the health check.

**Comment by danielnelson** [comment]
I agree this would be a good feature, let's call the option `success_status_codes`?

**Comment by dheerajdwivedi** [comment]
Picking this up.
