### ISSUE TITLE
Internal metrics have alias tag set to the empty string when unset

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#6541]
### Relevant telegraf.conf:

```toml
[[inputs.internal]]

[[outputs.prometheus_client]]
  # ...
```

### System info:

Telegraf 1.12.3

### Steps to reproduce:

1. Enable internal output and prometheus_client output
2. Check metrics

### Expected behavior:

Since no alias is set the tag shouldn't be added.
```
internal_gather_errors{input="internal",version="1.12.3"} 0
```

### Actual behavior:
```
internal_gather_errors{alias="",input="internal",version="1.12.3"} 0
```

**Comment by TRSridhar** [comment]
Is this up for grabs? What does the ready label mean?

**Comment by danielnelson** [comment]
@TRSridhar Yes it is up for grabs, would you be able to take a look at it?

The ready label is an internal tag we are experimenting with for planning, it's meaning and use will probably evolve a bit so I wouldn't pay it much attention.
