### ISSUE TITLE
[Question] iptables plugin when telegraf is running as a container

### ISSUE THREAD

**Issue by dgkanatsios** [influxdata/telegraf#6547]
Hey there,
How should I configure telegraf iptables input plugin when running in a container? Do I need to do any special volume mounting?

pinging @danielnelson who seems to have committed to the iptables plugin.

Thanks!

**Comment by danielnelson** [comment]
I'm not sure how, or if, this is possible.  If you can figure out I would be happy to add it to the plugins documentation though.

This plugin uses the `iptables` command, so it depends on how this command is implemented.  The basic idea would be to provide the hosts information to the command.  I suggest running `iptables -L -n -v` without worrying about Telegraf until you have it working.  These are just some ideas but it might help to use `--cap-add=NET_ADMIN` when starting the container and perhaps `-network host`.

That said, this isn't the right spot to ask questions, so I am going to close this issue.  We are only tracking bugs and feature requests here on GitHub.   You can ask general questions over at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by dgkanatsios** [comment]
ah, wasnt't aware of the Community site, apologies. Will take a look at your recommendations and post there if I have any more questions.
Thanks!
