### ISSUE TITLE
telegraf to read json file

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/telegraf#6550]
I have an influxdb, telegraf and Chronograf stack running. The data comes in JSON format and looks similar to this:

{{
    "msgid": "id1",
    "senderid": "id2",
    "measures": [
        {
            "type": "O",
            "value": "value1"
        },
        {
            "type": "CO2",
            "value": "value2"
        }
    ]
}

To be able to analyze the different values I need telegraf to load the type and value strings. I have defined the json_string_fields like this:

**json_string_fields = ["msgid","senderid","measures_0_type","measures_1_type","measures_0_value","measures_1_value"]**

Is there any way to define all the occurrences of the array? Some kind of wildcard? I have tried “measures_*_type” but it did not work.

**Comment by danielnelson** [comment]
The wildcard you are using should work in Telegraf 1.12.0 and later.

**Comment by priyankamondalairtel** [comment]
thanks, it is working!!
