### ISSUE TITLE
telegraf :: read json file

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6552]
HI,
I am using telegraf as data collector agent. and want to read a json file. it looks like below:

[
   {
      "user_id":"operator",
      "buckets":[
         {
            "bucket":"airtel-btfly",
            "tenant":"",
            "num_objects":1097884,
            "num_shards":16,
            "objects_per_shard":68617,
            "fill_status":"OK"
         },
         {
            "bucket":"airtel-club75",
            "tenant":"",
            "num_objects":51,
            "num_shards":0,
            "objects_per_shard":51,
            "fill_status":"OK"
         }
      ]
   },
   {
      "user_id":"mycloud",
      "buckets":[
         {
            "bucket":"mycloud-test1",
            "tenant":"",
            "num_objects":11,
            "num_shards":0,
            "objects_per_shard":11,
            "fill_status":"OK"
         }
      ]
   }
]

Nw I want telegraf to collect data as per "bucket" name, and user_id as tag_key. My telegraf configuration looks like:

[[inputs.exec]]
   commands = [ "cat /etc/telegraf/bucket.json" ]
tag_keys = ["user_id"]
##tag_keys = ["user_id","buckets_1_bucket","buckets_0_bucket"]
json_string_fields = ["bucket"]
json_query = "*.buckets"

How can I set "json_query" field in telegraf config to fulfill my requirement?

**Comment by danielnelson** [comment]
Unfortunately, this is not possible with the JSON parser currently.  I believe this is the same issue as in #6437.   Until this is possible, as you are using exec I suggest writing a wrapper script that transforms the data into a format that Telegraf can deal with.
