### ISSUE TITLE
Support for Telegraf on Solaris

### ISSUE THREAD

**Issue by adityask2** [influxdata/telegraf#6556]
## Feature Request
Support for Telegraf on Solaris. As of now, in order to support telegraf on Solaris, there is a lot of hassle in building the code base. 

### Use case: 
There are many environments which run Solaris. Providing monitoring for those machines would be definitely useful.

**Comment by danielnelson** [comment]
We have another issue open for Solaris support #407.  If you have been able to get the build working on Solaris could you write down manual steps on that issue and perhaps we can get something automated.  Let's continue on #407.
