### ISSUE TITLE
input plugin statsd supports admin interface to show and delete active metrics

### ISSUE THREAD

**Issue by zyf0330** [influxdata/telegraf#6568]
## Feature Request

Old statsd server supports admin interface to manage active metrics, can this plugin do the same thing?

### Proposal:
support delete metrics manually
### Current behavior:
cannot list and delete active metric manually
### Desired behavior:
can list and delete active metric manually
### Use case: 
I want to delete outdate gauge manually. The `delete_gauges` option is not proper for my situation and I set it as false.

**Comment by danielnelson** [comment]
It's not something that is supported now, but it would be a nice feature to add.

https://github.com/statsd/statsd/blob/master/docs/admin_interface.md

**Comment by powersj** [comment]
Hi @zyf0330,

Are you still interested in this feature? It looks like we would need to expose the `delgauges` command. Is it something you would be willing to try or test?

Thanks!
