### ISSUE TITLE
[0.10.2] statsd plugin error - type m unsupported

### ISSUE THREAD

**Issue by ljagiello** [influxdata/telegraf#657]
After upgrade from 0.10.1 -> 0.10.2 I have such error:
```
2016/02/06 06:31:46 Error: splitting ':', Unable to parse metric: 1|123
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: splitting ':', Unable to parse metric: 1|116
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: splitting ':', Unable to parse metric: 1|148
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
2016/02/06 06:31:46 Error: Statsd Metric type m unsupported
```

Statsd stream looks like:
```
~# ngrep -W byline -q port 9466 -d any
interface: any
filter: (ip or ip6) and ( port 9466 )
[…]
U 127.0.0.1:36404 -> 127.0.0.1:9466
1|148
bifrost.application.allRequests:1|m
bifrost.chef-s3.allRequests:1|m
bifrost.application.byRequestType.bifrost_wm_acl_member_resource.object.GET:1|m
```

**Comment by sparrc** [comment]
type `m` is not supported, I don't think that ever changed between versions, isn't that supposed to be `ms`?

**Comment by sparrc** [comment]
I did change the logging of statsd though, so it's possible that those metrics were just gettting sinlently dropped before?

BTW, what statsd client are you using that is sending `m` type metrics? I've never seen that type documented anywhere.

**Comment by sparrc** [comment]
closing as "won't fix" unless you can show me a legit statsd client that sends type `m`

**Comment by ljagiello** [comment]
@sparrc It's part of chef-server module stats_hero - https://github.com/chef/stats_hero#metrics-reported-to-estatsd

**Comment by sparrc** [comment]
fair enough, thx for the report

**Comment by ljagiello** [comment]
Fix: https://github.com/influxdata/telegraf/pull/661

**Comment by ljagiello** [comment]
It's possible to switch estatsd -> statsd format (https://docs.chef.io/config_rb_server_optional_settings.html#estatsd) closing this ticket.

**Comment by aep-sunlife** [comment]
> closing as "won't fix" unless you can show me a legit statsd client that sends type m

nc
