### ISSUE TITLE
Alter SqlServer Input to Report User Readable Database Names in Azure Managed Instance

### ISSUE THREAD

**Issue by leemicw** [influxdata/telegraf#6570]
## Feature Request

We would like the queries that use `sys.dm_os_performance_counters.instance_name` to join to the `sys.databases` view to resolve the instance name to a physical database name. From our testing this is only an issue is Azure Managed Instance.  Our Sql Server installed on a Virtual Machine seems to work correctly with the current code. 

### Proposal:

For the query starting in file `/plugins/inputs/sqlserver/sqlserver.go` on line 507.  Add a left outer join to the `sys.databases` view

    FROM	sys.dm_os_performance_counters AS spi
    LEFT OUTER JOIN sys.databases AS d ON spi.instance_name = d.physical_database_name

And alter the select statement to 

    RTrim(ISNULL(d.name,spi.instance_name)) instance_name,

### Current behavior:

The query returns a guid/identifier that had to be translated to a user readable value

### Desired behavior:

Return the user readable name of the database

### Use case: 

This change will make identification of the databases much easier

**Comment by danielnelson** [comment]
I wonder if we want both values saved as separate tags, this could potentially help ease the transition.

@denzilribeiro @m82labs Can you approve/reject?
