### ISSUE TITLE
Telegraf - NVidia SMI plugin not working on Windows client

### ISSUE THREAD

**Issue by dbu748** [influxdata/telegraf#6573]
Hi, 

I'm trying to monitor NVidia GPU on Windows client machines but it prevents Telegraf from running. 

When I run it manually using the plugin troubleshooting command (adapted for powershell) 

`.\nvidia-smi.exe --format="noheader,nounits,csv" --query-gpu="fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,compute_mode,utilization.gpu,utilization.memory,index,power.draw,pcie.link.gen.current,pcie.link.width.current,encoder.stats.sessionCount,encoder.stats.averageFps,encoder.stats.averageLatency,clocks.current.graphics,clocks.current.sm,clocks.current.memory,clocks.current.video"`

I get the error 

> Field “encoder.stats.sessionCount” is not a valid field to query.

All three encoder stats (sessionCount, averageFps, averageLatency) are in fact "not valid". Once they are removed, the command output a result.

OS: Windows 7
Telegraf: 1.12.3
nvidia-smi: 376.33
GPU: Quadro 4000

**Comment by danielnelson** [comment]
Can you run these commands and attach the output:
```
nvidia-smi.exe --format="csv"
nvidia-smi.exe -q -u -x
```

**Comment by dbu748** [comment]
Yes of course...

```
PS C:\Program Files\NVIDIA Corporation\NVSMI> .\nvidia-smi.exe --format="csv"
Invalid combination of input arguments. Please run 'nvidia-smi -h' for help.
```

From the help, selective queries (using format) must have one of `--query-xyz=`.
If you were looking for the full output 

```
PS C:\Program Files\NVIDIA Corporation\NVSMI> .\nvidia-smi -q

==============NVSMI LOG==============

Timestamp                           : Fri Oct 25 09:22:24 2019
Driver Version                      : 376.33

Attached GPUs                       : 1
GPU 0000:05:00.0
    Product Name                    : Quadro 4000
    Product Brand                   : Quadro
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : N/A
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : WDDM
        Pending                     : WDDM
    Serial Number                   : N/A
    GPU UUID                        : GPU-795b0a66-e968-2870-0c63-69189e2df04e
    Minor Number                    : N/A
    VBIOS Version                   : 70.00.67.00.02
    MultiGPU Board                  : No
    Board ID                        : 0x500
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x05
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x06DD10DE
        Bus Id                      : 0000:05:00.0
        Sub System Id               : 0x078010DE
        GPU Link Info
            PCIe Generation
                Max                 : 2
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : N/A
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : 37 %
    Performance State               : P1
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 2048 MiB
        Used                        : 228 MiB
        Free                        : 1820 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 1 %
        Encoder                     : N/A
        Decoder                     : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 71 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 405 MHz
        SM                          : 810 MHz
        Memory                      : 1404 MHz
        Video                       : 405 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 475 MHz
        SM                          : 950 MHz
        Memory                      : 1404 MHz
        Video                       : 540 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 5378
            Type                    : G
            Name                    : C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 6332
            Type                    : G
            Name                    : C:\Windows\system32\Dwm.exe
            Used GPU Memory         : Not available in WDDM driver model

```

Finally the unit

```
PS C:\Program Files\NVIDIA Corporation\NVSMI> .\nvidia-smi -q -u -x
<?xml version="1.0" ?>
<!DOCTYPE nvidia_smi_log SYSTEM "nvsmi_unit_v8.dtd">
<nvidia_smi_log>
        <timestamp>Fri Oct 25 09:12:34 2019</timestamp>
        <driver_version>376.33</driver_version>
        <hic_info>
        </hic_info>
        <attached_units>0</attached_units>
</nvidia_smi_log>
```

I hope it helps.

**Comment by glinton** [comment]
It seems like one solution could be to refactor the nvidia-smi plugin to parse the xml output and query `nvidia-smi -q -x`
@dbu748 I'm imagining it's not in the list, but can you check the output of `nvidia-smi.exe --help-query-gpu`? It prints a list of available to query gpu bits as i understand.

**Comment by dbu748** [comment]
No, you're right it's not in the list generated by ```nvidia-smi.exe --help-query-gpu```. Unless you need it, I won't copy the whole output. It really seems to be the explanation of all the metrics that are output by ```nvidia-smi.exe -q``` (shown in my last post).

I imagined at some point that having a white/black list of the metrics in the plugin config could do it but obviously your solution will probably be the more flexible and broadly supported !

**Comment by glinton** [comment]
@dbu748 the following build should work for you. You can try it out and verify that it collects all the data you expect.

<ul>
  <li><details><summary>darwin/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/darwin/amd64/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/darwin/amd64/telegraf-1.13.0%7Ec15d4756_darwin_amd64.tar.gz">telegraf-1.13.0~c15d4756_darwin_amd64.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>freebsd/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.13.0%7Ec15d4756_freebsd_amd64.tar.gz">telegraf-1.13.0~c15d4756_freebsd_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.13.0%7Ec15d4756_freebsd_i386.tar.gz">telegraf-1.13.0~c15d4756_freebsd_i386.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>linux/</summary><ul>
    <li><details><summary>mips</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf-1.13.0%7Ec15d4756_linux_mips.tar.gz">telegraf-1.13.0~c15d4756_linux_mips.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf_1.13.0%7Ec15d4756-0_mips.deb">telegraf_1.13.0~c15d4756-0_mips.deb</a></li>
    </li></ul></details>
    <li><details><summary>mipsel</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf-1.13.0%7Ec15d4756_linux_mipsel.tar.gz">telegraf-1.13.0~c15d4756_linux_mipsel.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf_1.13.0%7Ec15d4756-0_mipsel.deb">telegraf_1.13.0~c15d4756-0_mipsel.deb</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Ec15d4756-0.i386.rpm">telegraf-1.13.0~c15d4756-0.i386.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.13.0%7Ec15d4756_linux_i386.tar.gz">telegraf-1.13.0~c15d4756_linux_i386.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.13.0%7Ec15d4756-0_i386.deb">telegraf_1.13.0~c15d4756-0_i386.deb</a></li>
    </li></ul></details>
    <li><details><summary>arm64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Ec15d4756-0.arm64.rpm">telegraf-1.13.0~c15d4756-0.arm64.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.13.0%7Ec15d4756_linux_arm64.tar.gz">telegraf-1.13.0~c15d4756_linux_arm64.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.13.0%7Ec15d4756-0_arm64.deb">telegraf_1.13.0~c15d4756-0_arm64.deb</a></li>
    </li></ul></details>
    <li><details><summary>armel</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Ec15d4756-0.armel.rpm">telegraf-1.13.0~c15d4756-0.armel.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.13.0%7Ec15d4756_linux_armel.tar.gz">telegraf-1.13.0~c15d4756_linux_armel.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.13.0%7Ec15d4756-0_armel.deb">telegraf_1.13.0~c15d4756-0_armel.deb</a></li>
    </li></ul></details>
    <li><details><summary>armhf</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Ec15d4756-0.armv6hl.rpm">telegraf-1.13.0~c15d4756-0.armv6hl.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.13.0%7Ec15d4756_linux_armhf.tar.gz">telegraf-1.13.0~c15d4756_linux_armhf.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.13.0%7Ec15d4756-0_armhf.deb">telegraf_1.13.0~c15d4756-0_armhf.deb</a></li>
    </li></ul></details>
    <li><details><summary>s390x</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Ec15d4756-0.s390x.rpm">telegraf-1.13.0~c15d4756-0.s390x.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.13.0%7Ec15d4756_linux_s390x.tar.gz">telegraf-1.13.0~c15d4756_linux_s390x.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.13.0%7Ec15d4756-0_s390x.deb">telegraf_1.13.0~c15d4756-0_s390x.deb</a></li>
    </li></ul></details>
    <li><details><summary>static_amd64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.13.0%7Ec15d4756-static_linux_amd64.tar.gz">telegraf-1.13.0~c15d4756-static_linux_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Ec15d4756-0.x86_64.rpm">telegraf-1.13.0~c15d4756-0.x86_64.rpm</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0%7Ec15d4756_linux_amd64.tar.gz">telegraf-1.13.0~c15d4756_linux_amd64.tar.gz</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0%7Ec15d4756-0_amd64.deb">telegraf_1.13.0~c15d4756-0_amd64.deb</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>windows/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.13.0%7Ec15d4756_windows_amd64.zip">telegraf-1.13.0~c15d4756_windows_amd64.zip</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.13.0%7Ec15d4756_windows_i386.zip">telegraf-1.13.0~c15d4756_windows_i386.zip</a></li>
      <li><a href="https://43366-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
  </li></ul></details>

</ul>

**Comment by dbu748** [comment]
@glinton: Thank you Greg, it seems to work great!
