### ISSUE TITLE
Datastore metric disappears after a couple hours - Grafana Dashboard

### ISSUE THREAD

**Issue by gokou340** [influxdata/telegraf#6580]
### Relevant telegraf.conf:
Attached telegraf.conf to the case
[telegraf.txt](https://github.com/influxdata/telegraf/files/3772641/telegraf.txt)

### System info:
Ubuntu Server V16.04
Telegraf 1.12.4
Latest Grafana

### Steps to reproduce:

1. Start with no existing Telegraf Database
2. Start Telegraf
3. Import/Create Dashboard
4. Datastore metric works for a while
5. Refresh after a couple hours and the metric shows "No Data"

### Expected behavior:

Datastore metric should show.

### Actual behavior:

No Datastore Metric

### Additional info:
Grafana query for metric
SELECT mean("used_latest") * (100 / mean("capacity_latest"))  FROM "vsphere_datastore_disk" WHERE ("source" =~ /^$datastore$/) AND $timeFilter GROUP BY time($__interval) , "source"  fill(none)

Attached vsphere config
[vsphere config.txt](https://github.com/influxdata/telegraf/files/3772631/vsphere.config.txt)

**Comment by super911** [comment]
I've got the same issue as well.  Works fine for a couple hours and then data no longer appears
Using this Dashboard (VMware vSphere - Datastore)
 Total/Free and capacity summary show no Data
https://grafana.com/grafana/dashboards/8162

This Dashboard (VMware vSphere - Overview)
Datastores - Usage Capacity and Datastore Status show no data.
https://grafana.com/grafana/dashboards/8159

**Comment by gokou340** [comment]
> I've got the same issue as well. Works fine for a couple hours and then data no longer appears
> Using this Dashboard (VMware vSphere - Datastore)
> Total/Free and capacity summary show no Data
> https://grafana.com/grafana/dashboards/8162
> 
> This Dashboard (VMware vSphere - Overview)
> Datastores - Usage Capacity and Datastore Status show no data.
> https://grafana.com/grafana/dashboards/8159
> 
> These queries seem to be affected
> SELECT mean("used_latest") * (100 / mean("capacity_latest")) FROM "vsphere_datastore_disk" WHERE ("source" =~ /^$datastore$/) AND $timeFilter GROUP BY time($__interval) , "source" fill(none)
> 
> SELECT mean("capacity_latest") - mean("used_latest") FROM "vsphere_datastore_disk" WHERE ("source" =~ /^$datastore$/) AND $timeFilter GROUP BY time($__interval), "source" fill(null)

So, I made this change to the vsphere-stats.conf, I added specific metrics for the datastore to pull, instead of it pulling everything, so I added this:
`datastore_metric_include = [
  "disk.capacity.latest",
  "disk.used.latest",
   ]`

I deleted the influx database and let it recreate, not sure if that needed to be done, but I did it for mine, and it has been working for 24 hours so far without issue.

**Comment by super911** [comment]
Thanks, I'll give that a try and report back.

**Comment by super911** [comment]
gokou340, thanks for the info!! That fixed it for me as well. I also deleted the database and had it recreate. Going strong for a day...before it wasnt working for more than an hour or two. Thanks again.

**Comment by gokou340** [comment]
> gokou340, thanks for the info!! That fixed it for me as well. I also deleted the database and had it recreate. Going strong for a day...before it wasnt working for more than an hour or two. Thanks again.

Glad to help, just frustrating that it is a weird bu.. I'm still going strong since making the change.

**Comment by glinton** [comment]
Seems related to #6180

**Comment by danielnelson** [comment]
Closing, but let us know if it continues to happen.  First make sure you aren't overloading the vSphere server by reducing the number of metrics gathered.

**Comment by HalissonHalisson** [comment]
Hello
To solve the problem, I just added the line -> datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", without recreating the bank, it's been running for over 100 hours.
Thanks for the help

**Comment by eldhose19** [comment]
while telegraf collects metrics from vsphere it shows the datastore size (value) different from actual value in vsphere
what can be done to get the actual value of datastore from vsphere using telegraf
