### ISSUE TITLE
CIM input plugin

### ISSUE THREAD

**Issue by poulhs** [influxdata/telegraf#6582]
## Feature Request

Telegraf ought to have a CIM input plugin. 

### Proposal:

It is proposed to implement a telegraf input plugin for CIM/WBEM.

### Current behavior:
telegra
none - have to investigate and parse self.

### Desired behavior:

Support for CIM/WBEM with (some) best practices.

### Use case:

- CIM is a well-known, wide-spread standard that ought to be supported by telegraf.
- We need to monitor Horizon DaaS, supporting CIM is a first step to do this.

**Comment by AlexHeylin** [comment]
Agree on this, and it needs to allow for a certain level of SQL-like query.  As a workaround I have PoSh read the data via exec which works OK, but does add load due to repeatedly starting and stopping 
PowerShell. @poulhs - if you want a copy of that code, drop me a message.

**Comment by powersj** [comment]
Hi,

Thanks for the feature request. I am not intimately familiar with CIM or WBEM. What would a Telegraf input plugin look like that talks to these devices and what metrics would be captured?

Thanks!
