### ISSUE TITLE
Select the current database in InfluxDB

### ISSUE THREAD

**Issue by surajitkundu29** [influxdata/telegraf#6586]
## Feature Request

Is it possible to select the current database I am in?

**Comment by sjwang90** [comment]
If you're looking for something in InfluxQL you can refer to the SELECT statement information in [InfluxData's docs](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-basic-select-statement) page: 

Also other questions like this can be quickly addressed at our community page: https://community.influxdata.com/

**Comment by surajitkundu29** [comment]
Do you have any such function or way to return the current database ?

**Comment by fchikwekwe** [comment]
@surajitkundu29 I'm not aware of any query that allows a user to see the current database that they are using. The community page might be a better place to start discussions around topics like this and find help from other InfluxQL users.
