### ISSUE TITLE
InfluxDB 1.7.9 authentication setting for /debug/vars access

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#6588]
## Feature Request

Need new, optional settings for InfluxDB v1 plugin to allow for authenticated access to /debug/vars.
username/password must be supplied if the the InfluxDB config `pprof-auth-enabled = true` is set.

### Proposal:
Please add this support to the InfluxDB v1 plugin.

**Comment by glinton** [comment]
Reproducing/testing notes: In order for `pprof-auth-enabled` to be enabled, `auth-enabled` and `pprof-enabled` must also be set to true.
```toml
  auth-enabled = true
  pprof-enabled = true
  pprof-auth-enabled = true
```



The requested functionality is already supported by including the username/password into the url in the config (must use this method as a separately defined username and password may not apply to every url defined in the list.
```toml
urls = ["http://user:pass@localhost:8086/debug/vars"]
```

I'm leaving this open so we can sanitize the logs.

**Comment by danielnelson** [comment]
I assume that this endpoint supports HTTP Basic Auth.  If so we should add a `username` and `password` option for this and not use or recommend the userinfo section of the URL, as its use was deprecated long ago.
