### ISSUE TITLE
Customizing JSON Parser

### ISSUE THREAD

**Issue by demon-xxi** [influxdata/telegraf#659]
Separating parser plugins from input plugins was a great start. 
The new JSON Parser looks good and has flexibility to specify Tags keys. 
However during my integration of DeviceHive json messages I found that more options are needed: 

- [ ] Ability to extract MetricName from json message
- [ ] Ability to extract Timestamp from json message
- [ ] Choose json object containing metric values

To be clear, here's example of the json message produced by DeviceHive: 
```json
{
		"deviceGuid":"device_xyz",
		"notification":"ambient_stats",
		"timestamp":"2016-01-01T12:00:00Z",
		"parameters": {
                        "temperature": 100.0,
                        "humidity" : 0.76 
		} 
}
```

You can also see my `patch` on a previous version of kafka plugin to handle this format here: [0120940b27a26f59c6005acf8cb329422d912879](https://github.com/demon-xxi/telegraf/commit/0120940b27a26f59c6005acf8cb329422d912879)

Let me know if there is anything I missed in existing parser that would cover that. And if these features would make sense in the overall picture of telegraf. 
Another way to handle these kind of issues could be introduction of transformers that would allow to shape/strip data. Kind of how logstash does it.

**Comment by sparrc** [comment]
closing in favor of https://github.com/influxdata/telegraf/issues/1363
