### ISSUE TITLE
Bug while using name_overhide ?

### ISSUE THREAD

**Issue by munhozdiego** [influxdata/telegraf#6596]
__Steps to reproduce:__
 
Change [[inputs.mem]] section in the config file to include: name_override = "SOMETHING.Series"

__Expected behavior:__
Change name in the database and keeps data collection normally.

__Actual behavior:__
I does change name in the database, but data collection for MEMORY property becomes bugged.

As you can see below in the image below, the yellow line is what happens when using name_overhide. If I flip back to standard and remove name_overhide, the behaviour goes back to normal blue line.

![image](https://user-images.githubusercontent.com/2623885/67857475-4991dd00-faed-11e9-8ed0-8fbf912ef633.png)

__Environment info:__

* System info: Linux 3.10.105 x86_64
* InfluxDB version: 
* Telegraf version: Telegraf 1.12.2 (git: HEAD 8b4c9a0e)
* Other relevant environment details: Both Telegraf and influx are running from a container.

__Config:__
[global_tags]

[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = "Something"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

[[outputs.influxdb]]

urls = ["http://172.17.0.1:8086"]

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  name_override = "Something.Local.CPUS"
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false

# Read metrics about disk usage by mount point
[[inputs.disk]]
  name_override = "Something.Local.DISKS"

  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.diskio]]
  name_override = "Something.Local.DISKS"

[[inputs.kernel]]
  name_override = "Something.Local.System"

[[inputs.mem]]
  name_override = "Something.Local.System"

[[inputs.processes]]
  name_override = "Something.Local.System"

[[inputs.swap]]
  name_override = "Something.Local.System"

[[inputs.system]]
  name_override = "Something.Local.System"

[[inputs.docker]]
  name_override = "Something.Local.Docker"

  endpoint = "unix:///var/run/docker.sock"

  container_names = []

  timeout = "5s"

#DISKS
[[inputs.snmp]]
  agents = [ "XXX.XXX.XXX.XXX:161" ]
  version = 2
  community = "public"
  name = "Something.Remote.Disks"
  interval = "30s"
  timeout = "10s"
  retries = 3

[[inputs.snmp.table]]
	name = "Something.Remote.Disks"
	oid = "SYNOLOGY-DISK-MIB::diskTable"

	[[inputs.snmp.table.field]]
			name = "diskID"
			oid = "SYNOLOGY-DISK-MIB::diskID"
			is_tag = true	
	[[inputs.snmp.table.field]]
			name = "diskModel"
			oid = "SYNOLOGY-DISK-MIB::diskModel"			
	[[inputs.snmp.table.field]]
			name = "diskType"
			oid = "SYNOLOGY-DISK-MIB::diskType"
			is_tag = true
#	[[inputs.snmp.table.field]]
#			name = "diskStatus"
#			oid = "SYNOLOGY-DISK-MIB::diskStatus"			
	[[inputs.snmp.table.field]]
			name = "diskTemperature"
			oid = "SYNOLOGY-DISK-MIB::diskTemperature"					

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus0"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus1"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.1"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus2"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.2"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus3"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.3"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus4"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.4"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus5"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.5"

	[[inputs.snmp.field]]
		name = "SomethingDiskStatus6"
		oid = "SYNOLOGY-DISK-MIB::diskStatus.6"

	[[inputs.snmp.field]]
		name = "SomethingVolLoadRT"
		oid = "SYNOLOGY-SPACEIO-MIB::spaceIOLA.1"

	[[inputs.snmp.field]]
		name = "SomethingVolLoad5Min"
		oid = "SYNOLOGY-SPACEIO-MIB::spaceIOLA5.1"

	[[inputs.snmp.field]]
		name = "SomethingVolLoad15Min"
		oid = "SYNOLOGY-SPACEIO-MIB::spaceIOLA15.1"

	[[inputs.snmp.field]]
		name = "SomethingRaidStatus"
		oid = "SYNOLOGY-RAID-MIB::raidStatus.0"		

	[[inputs.snmp.table]]
	name = "Something.Remote.Disks.Smart"
	oid = "SYNOLOGY-SMART-MIB::diskSMARTTable"

	[[inputs.snmp.table.field]]
			name = "diskSMARTInfoDevName"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTInfoDevName"
			is_tag = true	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrName"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrName"	
			is_tag = true	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrId"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrId"	
			is_tag = true	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrCurrent"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrCurrent"	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrWorst"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrWorst"	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrThreshold"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrThreshold"	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrRaw"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrRaw"	
	[[inputs.snmp.table.field]]
			name = "diskSMARTAttrStatus"
			oid = "SYNOLOGY-SMART-MIB::diskSMARTAttrStatus"	

	[[inputs.snmp.table]]
	name = "Something.Remote.Disks.IOPS"
	oid = "SYNOLOGY-STORAGEIO-MIB::storageIOTable"

	[[inputs.snmp.table.field]]
			name = "storageIODevice"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIODevice"
			is_tag = true	
	[[inputs.snmp.table.field]]
			name = "storageIONRead"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIONRead"
	[[inputs.snmp.table.field]]
			name = "storageIONWritten"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIONWritten"
	[[inputs.snmp.table.field]]
			name = "storageIOReads"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOReads"
	[[inputs.snmp.table.field]]
			name = "storageIOWrites"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOWrites"
	[[inputs.snmp.table.field]]
			name = "storageIOLA"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOLA"
	[[inputs.snmp.table.field]]
			name = "storageIOLA1"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOLA1"
	[[inputs.snmp.table.field]]
			name = "storageIOLA5"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOLA5"
	[[inputs.snmp.table.field]]
			name = "storageIOLA5"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOLA5"
	[[inputs.snmp.table.field]]
			name = "storageIOLA15"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIOLA15"
	[[inputs.snmp.table.field]]
			name = "storageIONReadX"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIONReadX"
	[[inputs.snmp.table.field]]
			name = "storageIONWrittenX"
			oid = "SYNOLOGY-STORAGEIO-MIB::storageIONWrittenX"		

#SYSTEM & Network
[[inputs.snmp]]
  agents = [ "XXX.XXX.XXX.XXX:161" ]
  version = 2
  community = "public"
  name = "Something.Remote.System"
  interval = "30s"
  timeout = "10s"
  retries = 3

    [[inputs.snmp.table]]
		name = "Something.Remote.Network.NICS"
		#inherit_tags = [ "hostname" ]
		oid = "IF-MIB::ifXTable"
		
	[[inputs.snmp.table.field]]
		name = "ifName"
		oid = "IF-MIB::ifName"
		is_tag = true	

   	[[inputs.snmp.table.field]]
		name = "ifOperStatus"
		oid = "IF-MIB::ifOperStatus"
		is_tag = true 

    [[inputs.snmp.field]]
		name = "hostname"
		oid = "SNMPv2-MIB::sysName.0"
		is_tag = true	
	
	[[inputs.snmp.field]]
		name = "SomethingUpTime"
		oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"

	[[inputs.snmp.field]]
		name = "SomethingHostTemperature"
		oid = "SYNOLOGY-SYSTEM-MIB::temperature.0"

	[[inputs.snmp.field]]
		name = "SomethingHostFanStatus"
		oid = "SYNOLOGY-SYSTEM-MIB::systemFanStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingCpuFanStatus"
		oid = "SYNOLOGY-SYSTEM-MIB::cpuFanStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingOsVersion"
		oid = "SYNOLOGY-SYSTEM-MIB::version.0"

	[[inputs.snmp.field]]
		name = "SomethingOsUpdateStatus"
		oid = "SYNOLOGY-SYSTEM-MIB::upgradeAvailable.0"

	[[inputs.snmp.field]]
		name = "SomethingCpuFanStatus"
		oid = "SYNOLOGY-SYSTEM-MIB::cpuFanStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingPowerSupply"
		oid = "SYNOLOGY-SYSTEM-MIB::powerStatus.0"
		

	#Something Service Info
	[[inputs.snmp.field]]
		name = "SomethingServiceStatusAFP"
		oid = "SYNOLOGY-SERVICES-MIB::serviceUsers.2"

	[[inputs.snmp.field]]
		name = "SomethingServiceStatusCifs"
		oid = "SYNOLOGY-SERVICES-MIB::serviceUsers.1"

	[[inputs.snmp.field]]
		name = "SomethingServiceStatusFTP"
		oid = "SYNOLOGY-SERVICES-MIB::serviceUsers.4"

	[[inputs.snmp.field]]
		name = "SomethingServiceStatusHttp"
		oid = "SYNOLOGY-SERVICES-MIB::serviceUsers.6"

	[[inputs.snmp.field]]
		name = "SomethingServiceStatusSSH"
		oid = "SYNOLOGY-SERVICES-MIB::serviceUsers.8"

	[[inputs.snmp.field]]
		name = "SomethingUPSModel"
		oid = "SYNOLOGY-UPS-MIB::upsDeviceModel.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSStatus"
		oid = "SYNOLOGY-UPS-MIB::upsInfoStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSLoad"
		oid = "SYNOLOGY-UPS-MIB::upsInfoLoadValue.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSBeeperStatus"
		oid = "SYNOLOGY-UPS-MIB::upsInfoBeeperStatus.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSBatteryLevelPercentage"
		oid = "SYNOLOGY-UPS-MIB::upsBatteryChargeValue.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSVoltage"
		oid = "SYNOLOGY-UPS-MIB::upsInputVoltageValue.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSVoltageNominal"
		oid = "SYNOLOGY-UPS-MIB::upsInputVoltageNominal.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSInputSensivity"
		oid = "SYNOLOGY-UPS-MIB::upsInputSensitivity.0"

	[[inputs.snmp.field]]
		name = "SomethingUPSTransferReason"
		oid = "SYNOLOGY-UPS-MIB::upsInputTransferReason.0"
		
	[[inputs.snmp.field]]
		name = "SomethingUPSBatteryDuration"
		oid = "SYNOLOGY-UPS-MIB::upsBatteryRuntimeValue.00"

#Router
[[inputs.snmp]]
  agents = [ "XXX.XXX.XXX.XXX:161" ]
  version = 2
  community = "public"
  name = "Something.Remote.Network"
  interval = "30s"  
  timeout = "10s"
  retries = 3

    [[inputs.snmp.field]]
		name = "hostname"
		oid = "SNMPv2-MIB::sysName.0"
		is_tag = true	
	
		[[inputs.snmp.table]]
			name = "Something.Remote.Network"
			#inherit_tags = [ "hostname" ]
			oid = "IF-MIB::ifXTable"
		
		[[inputs.snmp.table.field]]
			name = "ifName"
			oid = "IF-MIB::ifName"
			is_tag = true	

   	[[inputs.snmp.table.field]]
			name = "ifOperStatus"
			oid = "IF-MIB::ifOperStatus"
			is_tag = true

**Comment by glinton** [comment]
I'm not certain what you are trying to accomplish, but I assume you want [`name_prefix`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins) instead of `override`. It looks like you are setting several of your plugins to the same name. This likely created a new metric in your db that contains an aggregate of all the tags/fields from each of those individual plugins, assuming the tagsets/timestamps didn't match.

If those docs don't help, ask future config related questions on the [InfluxData Community forum](https://community.influxdata.com).
