### ISSUE TITLE
Add flag to validate config file[s]

### ISSUE THREAD

**Issue by Benjamintf1** [influxdata/telegraf#6597]
### Relevant telegraf.conf:

```
[[inputs.exec]]
    commands = ["non-existent-command"]
```

### System info:

telegraf 1.11.4 -> telegraf 1.11.5 running on linux. 

### Steps to reproduce:

1. Create telegraf config that is structurally valid but has runtime issues. For example
```
[[inputs.exec]]
    commands = ["non-existent-command"]
```
or 
```
[[inputs.http]]
    url = "non-existent-url"
```
2. run `telegraf --config config.conf --test` fail in telegraf 1.11.5 and all telegraf 1.12

### Expected behavior:

--test only fails if static config fails in 1.11 line and there exists a similar command in later minors(such as --test-static). 
### Actual behavior:

it returns a non-zero exit code. 
### Additional info:

https://github.com/influxdata/telegraf/pull/6279
https://influxcommunity.slack.com/archives/CH99HUH8V/p1572472044002200
@rawkode

**Comment by glinton** [comment]
This does seem like a useful feature, especially if it printed out the toml parsing errors. I wouldn't classify it as a regression though because the `--test` flag wasn't meant to validate configuration. At best this could be planned for 1.13, but wouldn't likely be backported into 1.12.

**Comment by Benjamintf1** [comment]
That's not exactly what a regression means.

**Comment by Benjamintf1** [comment]
Something in 1.13 would be nice, I think we'd then be stuck using 1.11 until then(It might be nice to get a 1.11.6 with a reversion though)

**Comment by glinton** [comment]
Bringing over an idea from 6594, when implementing this, it may be nice to return an error, rather than simply logging it, when incorrect configuration is defined.
Eg: https://github.com/influxdata/telegraf/blob/b3f20f69f55e4034cd0bf1dd094ea4a46040ced0/internal/config/config.go#L1382-L1384

**Comment by danielnelson** [comment]
We can add a new operation, `check-config` or such, that doesn't run the inputs.  Later when we rework config loading we can improve the error handling too.

Let's merge this with duplicate issue ￼#5507

**Comment by Hipska** [comment]
@Benjamintf1 Check out v1.32.0 which now has a command to actually check the config. See https://github.com/influxdata/telegraf/pull/15732
