### ISSUE TITLE
openweathermap in other database config

### ISSUE THREAD

**Issue by vincent1890** [influxdata/telegraf#6599]
Hello

I want to use the [openweathermap](https://openweathermap.org/) api so I followed this [dashboard](https://grafana.com/grafana/dashboards/9710) 
this works perfectly the data is sent in the database by default but I would like to specify a database example
database = "influx_db_meteo" other than the one indicated in the current top file but only for inputs.http

French edition :+1: 
Je souhaite utiliser l'api [openweathermap](https://openweathermap.org/) j'ai donc suivi ce [dashboard](https://grafana.com/grafana/dashboards/9710) 
cela fonctionne parfaitement les données sont envoyées dans la database par défaut mais je voudrait spécifier une database exemple
`database = "influx_db_meteo"` autre que celle indiquée dans le fichier en haut actuelle mais seulement pour **inputs.http**

```
# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  urls = ["http://192.168.10.106:8086"]
  database = "influx_db_telegraf"
```
```
[[inputs.http]]

database = "influx_db_meteo"

urls = ["https://api.openweathermap.org/data/2.5/weather?id=6094817&units=metric&appid=b6907d289e10d714a6e88b30761fae22"]
data_format = "json"
tag_keys = ["coord_lon", "coord_lat", "sys_country", "id", "name"]
json_string_fields = ["weather_0_main", "weather_0_description"]
json_time_key = "dt"
json_time_format = "unix"
name_override = "openweathermap"
```

System info:
Influxdb version: 1.7.6
Telegraf version: 1.10.4
OS: Ubuntu 18.04.02

**Comment by glinton** [comment]
I'm not 100% certain I understand what you're wanting to do, but I'll address what I think you're looking for. If you want to send the metrics to a different influxdb database, you simply modify the `database` config option in the `outputs.influxdb` section of your config.
```toml
[[outputs.influxdb]]
  database = "another_db"
```

If this isn't what you are looking for, comment again or post on the [InfluxData Community](https://community.influxdata.com) site, they're generally great with config related questions.

Also, if you aren't aware, there is an [openweathermap](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/openweathermap) input plugin. I see you have different tags, if you have any thoughts on how to improve the openweathermap plugin, open a feature request [here](https://github.com/influxdata/telegraf/issues/new?template=Feature_request.md).
