### ISSUE TITLE
Nginx request extremely slow 

### ISSUE THREAD

**Issue by ruudboon** [influxdata/telegraf#660]
I have 2 urls defined for the nginx plugin. urls = ["http://localhost.fqdn/nginx_status", "http://internalhost/nginx_status/"]

The first Nginx host is taking more then 2 minutes to complete. When completed it contains the correct data. When doing curl http://localhost.fqdn/nginx_status I get a direct response.

Running telegraf 10.2 under Freebsd 10.2

**Comment by sparrc** [comment]
I don't know how to explain that, we're making a fairly simple GET request via net/http. It sounds like a bug with the Golang net/http package?

@ruudboon I'm not going to be able to reproduce this, could you provide more details? Does it happen when you only use a single url? Are you able to isolate the part of the request that is taking a long time?

**Comment by ruudboon** [comment]
@sparrc Can't really pinpoint the issue. Other server running freebsd 10.2 is working fine with 3 nginx hosts. If a request using curl is working fine it should be something in the go package. I'll try to dig in a bit more. Any tips on how to investigate this are more then welcome.

**Comment by sparrc** [comment]
@ruudboon any ideas/updates?

**Comment by ruudboon** [comment]
@sparrc Sorry, didn't had time to investigate this yet. I'll look at it tomorrow. Now that I think of it again it could be related to ipv6. It's the only difference with the other systems.

**Comment by sparrc** [comment]
that could be, what happens if you enclose the address in brackets? `http://[localhost.fqdn]/nginx_status`

**Comment by sparrc** [comment]
could you also provide your /etc/hosts file?

**Comment by sparrc** [comment]
closing for lack of updates/info, please feel free to re-open if you have more information
