### ISSUE TITLE
telegraf output influxDB ERROR

### ISSUE THREAD

**Issue by wuguanyu** [influxdata/telegraf#6604]
[agent] Error writing to output [influxdb]: could not write any address
Who encounter this issue?

**Comment by glinton** [comment]
Double check that the `outputs.influxdb` section of your config file has a listening influxdb server listed in the `urls` option.

We try to reserve GitHub Issues for actionable bug reports or feature requests. In the future, please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
