### ISSUE TITLE
plugins/inputus/docker CPU stats should respect perdevice

### ISSUE THREAD

**Issue by jamesshannon** [influxdata/telegraf#6609]
## Feature Request

docker has a config setting called perdevice:

```
## Whether to report for each container per-device blkio (8:0, 8:1...) and
## network (eth0, eth1, ...) stats or not
perdevice = true
```

While it applies to blkio and network, it does not apply to CPU. So I get 5 CPU values, one for each CPU.

The spirit of `perdevice` is clearly "Don't overload my network and my influxdb database with per-device metrics that I don't care about. 

### Proposal:

The same sentiment should apply to CPU metrics. Either `perdevice` value should be used, or a new `percpu` config param should be added.

### Use case:

Important to cut down bytes transferred for IOT devices on 3G networks.

**Comment by danielnelson** [comment]
I think having `perdevice` apply to the cpu metrics makes good sense.

As a workaround for now you could use `tagdrop`, using `?` to get any single/double digit cpu while still allowing `cpu-total` to passthrough:
```toml
[[inputs.docker]]
  # all the other options
  [inputs.docker.tagdrop]
    cpu = ["cpu?", "cpu??"]
```

**Comment by danielnelson** [comment]
After more thought I'd like to remove the aggregation in plugin, and rely instead on the basicstats aggregator.  For more info see discussion here: https://github.com/influxdata/telegraf/pull/7312#issuecomment-622516113
