### ISSUE TITLE
Output Plugin for AppDynamics

### ISSUE THREAD

**Issue by kyle-lt** [influxdata/telegraf#6616]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Output Plugin to send data to AppDynamics.

### Current behavior:

Metrics collected with Telegraf cannot be natively (i.e., via Telegraf Output Plugin) consumed by AppDynamics.

### Desired behavior:

Telegraf metrics can be natively consumed, via Telegraf Output Plugin (through the AppDynamics Machine Agent) and utilized within the AppDynamics platform.

### Use case: 

The existing ecosystem of Telegraf Input Plugins are a rich source of metric data that could be utilized within AppDynamics, specifically to take advantage of AppDynamics' dynamic baselining technology, in order to reduce mean-time-to-detect anomalous metric patterns.

### Next Steps:

I'll shortly be opening a new pull request to submit the code supporting the above.

**Comment by kyle-lt** [comment]
I have submitted the [Pull Request](https://github.com/influxdata/telegraf/pull/6618).

**Comment by powersj** [comment]
I am going to close this as the PR was closed. The plugin does sound like a good candidate for an external plugin.
