### ISSUE TITLE
could not serialize metric, Need more space

### ISSUE THREAD

**Issue by spuny** [influxdata/telegraf#6622]
### Relevant telegraf.conf:

```toml

```

### System info:

lxc container - OS debina buster
telegraf version - Telegraf 1.12.4 (git: HEAD 9a4f08e9)

### Steps to reproduce:

1. installed telegraf v 1.10. 
error:
Nov 06 10:59:12 sql telegraf[8200]: 2019-11-06T10:59:12Z E! [outputs.influxdb] when writing to [udp://<server>:<port>] could not serialize metric: "mysql_variables,datacenter=spdc,f0607645b6451af6afc0ca5a1b7a02dd=a0cbecde334cfd6caa6da7094d4d3770,host=my.host.cz,in_predicate_conversion_threshold=1000,innodb_version=10.3.18,protocol_version=10,rack=1a,server=127.0.0.1:3306,system_versioning_alter_history=ERROR,system_versioning_asof=DEFAULT,version=10.3.18-MariaDB-1:10.3.18+maria~buster-log,version_comment=mariadb.org
\\ binary\\ distribution,version_compile_machine=x86_64,version_compile_os=debian-linux-gnu,version_malloc_library=system,version_source_revision=604f80e77c054758aa449064cdc29dfa13a71922,version_ssl_library=OpenSSL\\ 1.1.1d\\ \\ 10\\ Sep\\ 2019": need more space

2. installed git latest debian version 1.12.4
same error

### Expected behavior:

log metrics

### Actual behavior:

metrics are not logged in

**Comment by danielnelson** [comment]
This metric line can't fit in a payload.  You can try to increase to the `udp_payload` size on the InfluxDB output depending on your network MTU, switch to HTTP, or filter the metric or at least some of the tags from it to decrease the size.

I wonder if it might be possible, though I haven't researched it, to use fragemented UDP packets in the output for these cases.

**Comment by spuny** [comment]
Hi,
thanks for answering. This one solves it:

In telegraf.conf increase payload value to 1024 as you suggested. Now everything is ok. Closing this one. Thanks for your quick response ;)
