### ISSUE TITLE
[inputs.ecs]: Error in plugin: json: cannot unmarshal string into Go value of type map[string]types.StatsJSON

### ISSUE THREAD

**Issue by HIMADRI518** [influxdata/telegraf#6623]
Its unable to parse, not sure why? 

### Relevant telegraf.conf:

```[[inputs.ecs]]
  ## ECS metadata url
    endpoint_url = "http://169.254.170.2"

  ## Containers to include and exclude. Globs accepted.
  ## Note that an empty array for both will include all containers
   container_name_include = []
  # container_name_exclude = []

  ## Container states to include and exclude. Globs accepted.
  ## When empty only containers in the "RUNNING" state will be captured.
  ## Possible values are "NONE", "PULLED", "CREATED", "RUNNING",
  ## "RESOURCES_PROVISIONED", "STOPPED".
     container_status_include = []
  # container_status_exclude = []

  ## ecs labels to include and exclude as tags.  Globs accepted.
  ## Note that an empty array for both will include all labels as tags
  #ecs_label_include = [ "com.amazonaws.ecs.*" ]
  #ecs_label_exclude = []


```

**Comment by danielnelson** [comment]
Let's try to check the underlying query, from the same system that Telegraf is running on can you run these queries:
```
curl http://169.254.170.2/v2/metadata
curl http://169.254.170.2/v2/tasks
```

**Comment by HIMADRI518** [comment]
```[ec2-user@ip-10-147-0-174 ~]$ curl http://169.254.170.2/v2/metadata
"Unable to get task arn from request: unable to associate '10.147.0.174' with task"[ec2-user@ip-10-147-0-174 ~]$ curl http://169.254.170.2/v2/tasks
404 page not found``` I do have IAM role attached to this instance to access ecs services. 
```[ec2-user@ip-10-147-0-174 ~]$ curl -s http://localhost:51678/v1/metadata | python -mjson.tool
{
    "Cluster": "default",
    "ContainerInstanceArn": "arn:aws:ecs:us-west-2:814043572243:container-instance/4271d0c2-1e46-448d-9128-3a386a00c70b",
    "Version": "Amazon ECS Agent - v1.32.0 (a7f81040)"
}```

**Comment by danielnelson** [comment]
Might be permission related, what ECS policies does your IAM role have?  I wonder if it might be useful to use the awscli to help troubleshoot.  Whats the output of this command?
```
aws ecs list-tasks
```

**Comment by HIMADRI518** [comment]
I am running this from ec2 instance outside the ecs cluster. Could that be why?

**Comment by danielnelson** [comment]
Could be, I think you need the ECS Agent installed, do you have that? https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html

**Comment by HIMADRI518** [comment]
Yes, I have the agent. I think it needs to be in docker network to make a pull stats from the api.

**Comment by danielnelson** [comment]
Maybe this page can help, the "Important" section at the time seems especially relevant.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html

**Comment by HIMADRI518** [comment]
Turns out this only works if you run telegraf along with the cluster service as a sidecar.

**Comment by danielnelson** [comment]
Do you mean that you think the agent, and this plugin, can only be used from within the ECS cluster?

**Comment by HIMADRI518** [comment]
Yes and in fact within the task. It would really help users on setting things up. In order to make it work, its a lot more than just changing configurations on ecs task level. The telegraf container has dependencies and cloud environment setup would need better deployments like cf or terraform than manually changing config files on 10s of task containers. There is not much documentation out there to help new folks, especially cloud customers. Just a suggestion.

**Comment by danielnelson** [comment]
I'd love to have some more documentation on setup, if we had a more in depth guide/tutorial for setup with CF or Terraform we could link to them from the plugin README.  We have a few places we have put info like this before, such as the [InfluxData blog](https://www.influxdata.com/blog/) or [InfluxData Community](https://community.influxdata.com) site.  We could link to another blog site, or we could even put it on this repos wiki.  I'd love to get help on this from you and the rest of the community.

On closing this particular issue, I think we got to the root of the problem and we just need to improve the error message.

**Comment by reimda** [comment]
It looks like this was resolved and the error messages were improved. Closing.
