### ISSUE TITLE
InfluxDB v2.0 support for inputs.influxdb_listener plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#6626]
### Proposal:
Requesting v2 support for `influxdb_listener` input plugin

### Current behavior:
`influxdb_listener` plugin currently only supports InfluxDB v1

### Desired behavior:
`influxdb_listener` capable of listening to both InfluxDB v1 AND v2. Ideally one plugin can support both versions.  

### Use case: 
Help with growth and utilization of Influx2.0

**Comment by danielnelson** [comment]
> influxdb_listener capable of listening to both InfluxDB v1 AND v2. Ideally one plugin can support both versions.

I think we may want to do this as a separate plugin, in order to support the query parameters without causing confusion in the configuration (database_tag vs bucket_tag/organization_tag).  There are few key implementation differences between the two write endpoints that likely mean we need separate code anyway.

**Comment by gustavooferreira** [comment]
Hi, is anyone aware of any input plugin with this support, I can't seem to find anything that supports v2 input for telegraf.

**Comment by danielnelson** [comment]
Depending on your requirements, you may be able to use `http_listener_v2` with `data_format = "influx"`.  The bucket, org, token will just be ignored.  You will want to set up the plugin to use POST and `path = "/api/v2/write"`

**Comment by magichair** [comment]
I've opened #7828 which ports the `influxdb_listener` to support the InfluxDB 1.8 / 2.x `/api/v2/write` endpoint and authentication scheme.
