### ISSUE TITLE
Support Environment Variables in the config file

### ISSUE THREAD

**Issue by hrzbrg** [influxdata/telegraf#663]
Hi,

we are currently testing Telegraf in a large AWS ECS deployment with a lot of microservices.
We use collectd to get metrics from the Docker socket. The collectd metrics include a servicename that is read from an environment variable of the container. This is mostly because the container name is often appended with version strings or commit hashes. 

It would be awesome if the Telegraf Docker plugin would support something like this as an extra tag for every container. It seems useful and flexible for many deployments. 

Reference: https://github.com/bobrik/collectd-docker

**Comment by sparrc** [comment]
Do you happen to know what the env variable is? or is it configurable?

**Comment by hrzbrg** [comment]
That does not matter, but it could be something like "TELEGRAF_APP_ENV" and if I set that to "myservice" in my docker container, telegraf would tag the measurements appropriately with "myservice".

**Comment by gena01** [comment]
Actually i was thinking of something similar, not even specific to docker. We tend to tag some things with roles, env, etc.. via ENV variables. Would be nice to be able to provide a list of env variables and their values would be pulled in as tags?

**Comment by kri5** [comment]
:+1:

**Comment by nileshd** [comment]
This would be an awesome feature to have. We have an elastic setup for a set of micro services app that can scale on demand. Some of these microservices have an instance of telegraf running locally. Would be great if I can tag which instance and app, that telegraf instance is sending data from. These two pieces of data is available from the environment variables. 

If the telegraf config allowed to add a tag value from these env vars, that'll allow us to use telegraf in an elastic setup and identify from which nodes data come from.

**Comment by sparrc** [comment]
I updated the issue title to reflect that this is just a request for the config file to support environment variables.

**Comment by sparrc** [comment]
For those interested, I have a PR up to solve this (#951)

the regex it will use to match is: `\$\w+`, so basically any word (alphanumeric characters and underscores) preceded by a `$` is matched, does this seem good to everyone? Do we need to include dashes too?

**Comment by sparrc** [comment]
Actually I think I've answered my own question, dashes are not allowed in environment variable names
