### ISSUE TITLE
Stackdriver input does not collect summary statistics for distributions

### ISSUE THREAD

**Issue by sciurus** [influxdata/telegraf#6637]
According to the Stackdriver documentation, a [Distribution](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#distribution) "contains summary statistics for a population of values. It optionally contains a histogram representing the distribution of those values across a set of buckets. The summary statistics are the count, mean, sum of the squared deviation from the mean, the minimum, and the maximum of the set of population of values. The histogram is based on a sequence of buckets and gives a count of values that fall into each bucket. The boundaries of the buckets are given either explicitly or by formulas for buckets of fixed or exponentially increasing widths."

The stackdriver input plugin has an option, `gather_raw_distribution_buckets` to skip gathering the histogram bucket counts and instead use one or more [aligners](https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.v3#aligner) (of which I think the valid choices are ALIGN_SUM and the misc ALIGN_PERCENTILE_ options) specified in `distribution_aggregation_aligners` .

When I configure the stackdriver input to use aligners instead of fetching the bucket counts, I still expect it to gather the summary statistics of count, mean, sum of the squared deviation from the mean, minimum maximum. Instead, I only get values for the aligners I enabled.

I am experiencing this on telegraf 1.12.2.

**Comment by sspaink** [comment]
Sorry to see you never got a response, are you still using this plugin and would like this change to be implemented so you can use aligners but still get summary statistics?
