### ISSUE TITLE
Support ZFS plugin on FreeBSD

### ISSUE THREAD

**Issue by vat9** [influxdata/telegraf#664]
The ZFS plugin is only configured for use on Linux at this time.  FreeBSD can synthesize the same input values though the plugin would need to use sysctl instead of /proc/spl/kstat/zfs.

Sysctl can provide kstat.zfs.misc.arcstats, kstat.zfs.misc.zfetchstats, and kstat.zfs.misc.vdev_cache_stats.  Pool metrics could be provided with other zpool metrics.

**Comment by sparrc** [comment]
sure, PRs welcome :-)

**Comment by titilambert** [comment]
+1
If I have time, I can try to do it and test it on Freenas :)

**Comment by alexal12** [comment]
+1 :)

**Comment by rickard-von-essen** [comment]
+1 @titilambert Did you start on this? I'll might have a look.

**Comment by titilambert** [comment]
@rickard-von-essen unfortunately not. I'm too loaded for several months...

**Comment by rickard-von-essen** [comment]
@titilambert to late I already made a PR :wink:
