### ISSUE TITLE
Add the ability to use filename as a tag in files plugin

### ISSUE THREAD

**Issue by amarco2** [influxdata/telegraf#6644]
## Feature Request

I'm new to influxdb and I was using telegraf plugin to get data stored into several csv files. I tried to include the name of the file as another field of data, but din't find the way to do it through the configuration, and I ended up including the filename as an additional column when generating the file.

### Proposal:
Allow using current filename where the data is readed from to be used as a tag (or a field) when importing data to influxdb with the telegraf plugin files

### Current behavior:
It's not possible 

### Desired behavior:
Define whether to use the filename as tag or not in the configuration of the plugin
```
[[inputs.file]]
  ## Files to parse each interval.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   /var/log/**.log     -> recursively find all .log files in /var/log
  ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
  ##   /var/log/apache.log -> only read the apache log file
  files = ["/var/log/apache/access.log"]

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "csv"

  ## Include filename as custom tag.
  ## Define a tag name to be filled with the source filename, or leave blank to not include it.
  input_filename_custom_tag = "session"

```

### Use case: 
Collecting data from several csv files in a directory, where the csv filename denotes a particular characteristic of the data, like a session name or a particular datasource. Allowing including filename as a tag will allow filtering out data coming from every single file.

**Comment by nwneisen** [comment]
This looks like a case where a `source` tag could be used.  The tag would need to be updated as a new file is opened and processed.  

I'm interested in working on this if it makes sense.

**Comment by danielnelson** [comment]
The `source` tag is specifically only for the hostname, so in this case it would be `os.Hostname()`, same as the `host` tag.  It is still unresolved if we should add `source` to all metrics even when it matches the `host` tag, for now I think we should leave them off but I will nudge a few internal of my colleagues for input.

On plugins like this that use the `data_format` option, my current thinking is that they shouldn't add tags automatically: this way it is possible to feed line protocol in and get the exact output you desire and also helps to avoid conflicts.  Instead we should follow the suggested fix here and use an option where the tag can be specified:
```toml
[[inputs.file]]
  file_tag = "file"
```

This is similar to newer changes to some of the queuing inputs like `kafka_consumer` for adding the queue name to the metrics.

As a workaround, if you are only reading a single file you can add a static tag:
```toml
[[inputs.file]]
  files = ["foo"]
  [inputs.file.tags]
    file = "foo"
```

**Comment by nwneisen** [comment]
I was thinking of the source tag too generically.

Making sure I have the right idea, setting `file_tag = "file"` should tell the plugin to pull the file's name for the file tag.  Would it make more sense here to use `"name"` or `"filename"` rather than `"file"`?

This setting could potentially have more options added later on.  For instance, if someone was running multiple file inputs and wanted to track the file types, they might be interested in an option to set `file_tag = "format"`.

**Comment by nwneisen** [comment]
I reread the comments and realized I had the wrong idea for this.  My PR should have the desired changes.
