### ISSUE TITLE
Build of Telegraf for ppc64le Architecture

### ISSUE THREAD

**Issue by nickmy9729** [influxdata/telegraf#6651]
## Feature Request

PPC64LE build of Telegraf

Please build a ppc64le version of telegraf for linux OS

GOARCH=ppc64le GOOS=linux

**Comment by danielnelson** [comment]
Can you test these packages?
- [telegraf-1.13.0~cd5fb00d-0.ppc64le.rpm](https://43737-33258973-gh.circle-artifacts.com/0/build/linux/ppc64el/telegraf-1.13.0~cd5fb00d-0.ppc64le.rpm)
- [telegraf-1.13.0~cd5fb00d_linux_ppc64el.tar.gz](https://43737-33258973-gh.circle-artifacts.com/0/build/linux/ppc64el/telegraf-1.13.0~cd5fb00d_linux_ppc64el.tar.gz)
- [telegraf_1.13.0~cd5fb00d-0_ppc64el.deb](https://43737-33258973-gh.circle-artifacts.com/0/build/linux/ppc64el/telegraf_1.13.0~cd5fb00d-0_ppc64el.deb)

**Comment by nickmy9729** [comment]
Yes I will test them this week and get back to you.

**Comment by sspaink** [comment]
Resolved by https://github.com/influxdata/telegraf/pull/8432
