### ISSUE TITLE
Enable input/nats under FreeBSD

### ISSUE THREAD

**Issue by abishai** [influxdata/telegraf#6657]
I run both nats and telegraf under FreeBSD and interested to get nats data, however input/nats is disabled : https://github.com/influxdata/telegraf/commit/1b0a4e49cdf30cd0ae4984253549c443520c11ca

I made a search and found that cgo works under FreeBSD (or at least there are not known problems with it). Can you enable the plugin ? I can test it.
Thanks.

**Comment by danielnelson** [comment]
We can update this to only build on FreeBSD if CGO is enabled, but you will need to build yourself until we have a way to build the official packages in this way.

**Comment by danielnelson** [comment]
I would expect the [freshports](https://www.freshports.org/net-mgmt/telegraf/) build have CGO enabled, and I'd recommend these builds over the official packages anyway.
