### ISSUE TITLE
Inputs.dns no such host

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#6661]
I have recently set up the inputs.dns plugin with the following configuration:

`[[inputs.dns_query]]
    servers = ["dnsbnndns1.sharedtcs.net, dnsbnndns2.sharedtcs.net"]
    network = "udp"       
    domains = ["prodinfluxwwlab.sharedtcs"]
    record_type = "A"
    port = 53
    timeout = 5         
    interval = "60s"`

The telegraf.log shows:
`2019-11-15T06:56:06Z E! [inputs.dns_query] Error in plugin: dial udp: lookup dnsbnndns1.sharedtcs.net, dnsbnndns2.sharedtcs.net: no such host`

However, the command:
`dario@mbue02-e2e-radio-check:~$ host dnsbnndns2.sharedtcs.net
dnsbnndns2.sharedtcs.net has address 138.187.111.116`
Works on the machine. 

Telegraf version is 1.12.5-1 on:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by danielnelson** [comment]
I think you just need to make this config change:
```diff
- servers = ["dnsbnndns1.sharedtcs.net, dnsbnndns2.sharedtcs.net"] 
+ servers = ["dnsbnndns1.sharedtcs.net", "dnsbnndns2.sharedtcs.net"] 
```

**Comment by darox** [comment]
Ah sorry, my mistake. Thank you very much!
