### ISSUE TITLE
Multiple instance on windows server

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6670]
Hi Team,

Can you please suggest, how can I run multiple telegraf config file on windows servers?

on Linux server we are using below commands :-
telegraf --config /etc/telegraf/telegraf_ping.conf

**Comment by danielnelson** [comment]
You can do the same on Windows.  If you are registering Telegraf as a service make sure to give each instance its own name.

https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md#install-multiple-services

**Comment by rguptarg** [comment]
Hi Daniel,

Thanks for replying 

we are getting below error :- 

C:\Program Files\telegraf>telegraf.exe --service install --service-name telegraf-1 --config "C:\Program Files\Telegraf\telegraf.conf"

C:\Program Files\telegraf>telegraf.exe --service install --service-name telegraf-2 --config "C:\Program Files\Telegraf\telegraf_ping.conf"
2019-11-19T06:41:38Z E! Failed to install Telegraf Data Collector Service: The name is already in use as either a service name or a service display name.

C:\Program Files\telegraf>telegraf.exe -version
Telegraf 1.12.5 (git: HEAD f09d4023)

**Comment by danielnelson** [comment]
Try adding a display name `--service-display-name "Telegraf Ping"`:

```
C:\Program Files\telegraf>telegraf.exe --service install --service-name telegraf-2 --service-display-name "Telegraf Ping" --config "C:\Program Files\Telegraf\telegraf_ping.conf"
```

I'lll reopen to see if we need to add this to the Windows service documentation.

**Comment by rguptarg** [comment]
Thanks!!!!!!!!

Now it's working fine.

**Comment by danielnelson** [comment]
Added to docs: 05cefe61bd6bd183369dc36c5cc649083c6570cb
