### ISSUE TITLE
System Requirements and dependencies for Telegraf

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#6674]
## Feature Request
System Requirements and dependencies for Telegraf

Opening a feature request kicks off a discussion.

### Proposal:
Include the Windows/Linux system/OS requirements for Telegraf
### Current behavior:
The requirements don't appear to be available
### Desired behavior:
System/OS requirements for Windows and Linux displayed in the GitHub ReadME
### Use case: 
So we know that the systems we are deploying to will have no problem accepting a Telegraf install.

**Comment by danielnelson** [comment]
We should add this to the README, but the quick answer is that the minimum requirments are those of the Go language used to build Telegraf.  Telegraf 1.12 is built with Go 1.12, the versions matching is just a coincidence.

This means the minimum are:
> Windows Server 2008R2 and higher or Windows 7 and higher.
> Kernel version 2.6.23 or later.

https://github.com/golang/go/wiki/MinimumRequirements

**Comment by raider111111** [comment]
Thanks!

**Comment by danielnelson** [comment]
1f5be2bac7b895867411406b2eeac892b9ff9258
