### ISSUE TITLE
Plugin: Cisco MDT

### ISSUE THREAD

**Issue by mmihir82** [influxdata/telegraf#6676]
#### Relevant telegraf.conf:

```
[inputs.cisco_telemetry_mdt]: No measurement alias for encoding path: show interface
```

### System info:
Telegraf: 1.12.5-1

### Steps to reproduce:
NXOS Switch version: `9.3(1)`

```
telemetry
  destination-profile
    use-vrf default
  destination-group 1
    ip address 192.168.11 port 57000 protocol gRPC encoding GPB
  sensor-group 1
    data-source NX-API
    path "show interface" depth 0
  subscription 1
    dst-grp 1
    snsr-grp 1 sample-interval 10000
```
Same configure on different switch `NXOS: version 7.0(3)I7(6)`
#### Errors
```
[11/18/19 20:48:01.009 UTC ec5417 823] [3940157440][tm_dm.c:1360] TM_DM: fd:116 registered with main xdm successfully!
[11/18/19 20:48:01.009 UTC ec5418 823] [3940157440][tm_ec_dme_web_sock.c:247] TM_EC: Cancelling libwebsocket context 0x11ca0680
[11/18/19 20:48:06.030 UTC ec5419 823] [3940157440][tm_ec_dme_auth.c:32] TM_EC: Authenticated.
[11/18/19 20:48:06.030 UTC ec541a 823] [3940157440][tm_ec_dme_web_sock.c:156] TM_EC: Destroying libwebsocket context 0x11ca0680 to open new
[11/18/19 20:48:06.036 UTC ec541b 823] [3940157440][tm_ec_dme_web_sock.c:209] TM_EC: Created libwebsocket context 0x11ca0680
```
Which database is using, where to define the DB name? 
I see the data is being sent to influxdb, but I only see one entry from the `show interface` I have done tcpdump and I see raw data with all the interface? Why does influxdb only save one entry, does it over rights the index?

**Comment by danielnelson** [comment]
I am unable to verify the device setup, I don't know enough to say however I was expecting a path of the form `ietf-interfaces:interfaces-state/interface/statistics`.  @sbyx Do you have a link that describes the device setup, maybe we can link from the README?

> Which database is using, where to define the DB name?

You would define this in the `influxdb` output plugin of `telegraf.conf`.

> No measurement alias for encoding path: show interface

This is a debug message indicating that no alias was set for this measurement.  I would not worry about it at this stage as not having an alias shouldn't affect if data is inserted, only the formatting of the data.

As mentioned before, I'm not familiar with the device, but the log messages from the device do not look related as MDT does not use a websocket transport.

For debugging, I often define a `file` output plugin so I can easily see all metrics that are produced.

**Comment by sbyx** [comment]
I think the main issue here is that the NX-OS support was added for 1.13.x and @mmihir82 is using 1.12.x while there you will get some results with earlier versions they are not really meaningful.
I would suggest trying again with a nightly build.

Configwise at least on device-side it looks okay.

**Comment by danielnelson** [comment]
@mmihir82 Here are the links to the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds), could you give them a shot?

**Comment by mmihir82** [comment]
It works, I was able to parse the data using nightly builds, thank you
