### ISSUE TITLE
success_status_codes not allowed

### ISSUE THREAD

**Issue by sojwil** [influxdata/telegraf#6681]
### Relevant telegraf.conf:
[[inputs.http]]
data_format="json"
urls = [
    "http://url1",
    "http://url2"
  ]
timeout = "5s"

name_override = "Healthchecks"
json_query = "results"
json_name_key = "assemblyname"
tag_keys = ["status", "name"]
json_string_fields = ["results_description"]
success_status_codes = [200,503]

### System info:
version -> Telegraf 1.12.5 (git: HEAD f09d4023)
docker -> telegraf:latest

### Steps to reproduce:
Add success_status_codes = [200,503] to telegraf.conf file in a [[inputs.http]] section
Start telegraf

### Expected behavior:
Telegraf starts and polls the urls located in the "urls" section.
The reponses are parsed when either the http reponse code is 200 or 503

### Actual behavior:
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Starting Telegraf 1.12.5
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Loaded inputs: logparser http
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Loaded aggregators: valuecounter
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Loaded processors: regex
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Loaded outputs: prometheus_client
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! Tags enabled:
11/19/2019 8:59:58 AM2019-11-19T07:59:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"c61718c9cc32", Flush Interval:10s
11/19/2019 10:50:30 AM2019-11-19T09:50:30Z I! [agent] Hang on, flushing any cached metrics before shutdown
11/19/2019 10:50:35 AM2019-11-19T09:50:35Z I! Starting Telegraf 1.12.5
11/19/2019 10:50:35 AM2019-11-19T09:50:35Z E! [telegraf] Error running agent: Error parsing /configs/telegraf/telegraf.conf, line 217: field corresponding to `success_status_codes' is not defined in http.HTTP

### Additional info:
Even when only using [200], like in the default telegraf.conf file, telegraf will not start.
When removing the success_status_codes entry, telegraf start and does what it should do.

**Comment by danielnelson** [comment]
This feature will be available in the 1.13.0 release.  When browsing the repo for documentation, make sure to select the appropriate release-1.X branch from the dropdown in the upper left area, this way you will see the correct documentation for the version you are using.
