### ISSUE TITLE
Telegraf Failed to start

### ISSUE THREAD

**Issue by Hoffman23** [influxdata/telegraf#6682]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:
root@grafana-red01:~# systemctl status telegraf.service
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-11-19 13:51:52 CET; 3min 8s ago
     Docs: https://github.com/influxdata/telegraf
  Process: 1230 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=exited, status=1/FAILURE)
 Main PID: 1230 (code=exited, status=1/FAILURE)

nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Unit entered failed state.
nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Failed with result 'exit-code'.
nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
nov 19 13:51:52 grafana-red01 systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Start request repeated too quickly.
nov 19 13:51:52 grafana-red01 systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Unit entered failed state.
nov 19 13:51:52 grafana-red01 systemd[1]: telegraf.service: Failed with result 'exit-code'.

### Desired behavior:
root@grafana-red01:~# systemctl status telegraf.service
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-11-19 13:51:51 CET; 47ms ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 1219 (telegraf)
    Tasks: 8 (limit: 19660)
   CGroup: /system.slice/telegraf.service
           └─1219 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

**Comment by danielnelson** [comment]
Check the log file, usually `/var/log/syslog` or use `sudo journalctl -eu telegraf`, for details about why Telegraf didn't start. 

We try to use this issue tracker for bugs and feature requests, so if you run into more usage issues, please direct them over to the [InfluxData Community](https://community.influxdata.com) site.
