### ISSUE TITLE
short_message field in graylog output hard set to "telegraf"

### ISSUE THREAD

**Issue by dutchman80** [influxdata/telegraf#6683]
The graylog output plugin is hard setting the required "short_message" field in the GELF message to the string "telegraf".  This is happening on line 217 of the output plugin.

It should be setting it to whatever the "short_message" (or "message") field is in the input metric.  The way it works now, the actual log messages from the logparser input are not actually passed to Graylog properly.

I don't know 'go' at all or I would have done a pull request with proper error handling.

### System info:

telegraf-1.12.5-1

### Expected behavior:
Something like...
`m["short_message"] = metric.Fields()["short_message"]
`
### Actual behavior:

`m["short_message"] = "telegraf"
`

**Comment by danielnelson** [comment]
This plugin could definitely use some updates, but we need to be mindful about backwards compatibility.  I think it would make sense to add an option to control how the field is set:
```toml
[[outputs.graylog]]
  short_message_field = "message"
```

If the metric doesn't have this field set, or if the option is unset, then we would fall back to the static "telegraf" string.  What do you think?

**Comment by dutchman80** [comment]
I think that would work great!

**Comment by danielnelson** [comment]
@dutchman80 Are you able to test out one of these builds: https://github.com/influxdata/telegraf/pull/6700#issuecomment-557326223?
