### ISSUE TITLE
E! [inputs.postgresql] Error in plugin: EOF

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#6691]
Hi,
I am running Telegraf 1.12.6

While monitoring PostgreSQL 10.10 slaves I am getting  
E! [inputs.postgresql] Error in plugin: EOF

**Comment by sjwang90** [comment]
Apologies as this has been awhile. @arindamchoudhury Can you test this with the latest PostgreSQL and Telegraf and share a sample of the config for troubleshooting?
