### ISSUE TITLE
Kafka output with Timestamp

### ISSUE THREAD

**Issue by johnatannvmd** [influxdata/telegraf#6696]
## Feature Request

Telegraf should add a timestamp to the Kafka Message. I suggest to add in the next order: "Metric's timestamp" if empty than "Current timestamp". This behavior is the same as we configure Kafka to automatically set Message Timestamp when it stored by a Kafka Worker.

Initially, that feature was implemented here: https://github.com/influxdata/telegraf/commit/74b330922527510c209645474b7ac664c1b2b9d9 on Sep 23, 2015. But then after refactoring was removed https://github.com/influxdata/telegraf/commit/c26ce9c4fe4a1ece56473e2122e6e4157319f187 on Oct 17, 2015. I guess by a mistake

### Current behavior:

Telegraf skip adding a timestamp.

### Desired behavior:

Telegraf should add a timestamp.

### Use case:

It is a good thing to know what is the timestamp of the tail or the head message on the topic.

**Comment by danielnelson** [comment]
What `data_format` are you using?  The timestamp is added in the message body according to the `data_format`.

**Comment by johnatannvmd** [comment]
I use `influx` `data_format` which is coming from other telegrafs.

According to these lines of code I do not see where the timestamp can be added to the `sarama.ProducerMessage` before it passed to the `k.producer.SendMessages`
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/kafka/kafka.go#L323

So in the Kafka I see timestamps with `-1` value, instead of right ones.

**Comment by johnatannvmd** [comment]
I mean not the messages it self, but the `sarama.ProducerMessage` have the property `Timestamp` and that property have value `-1` now. I suppose that this value should have same values as in line protocol value, in my case, or current timestamp if it empty in `metric` struct.

**Comment by danielnelson** [comment]
What does this field do on the broker side?  Is it only informational or does it affect the way/order the messages are consumed?

**Comment by johnatannvmd** [comment]
There are several good use cases for having timestamps on the Kafka level:

1. I can replay the topic from a timestamp. https://medium.com/@werneckpaiva/how-to-seek-kafka-consumer-offsets-by-timestamp-de351ba35c61 - for example;
1. I can use some streaming processing tools and timestamps will be useful;
1. Internal analytics - diff between head and tail to measure topic capacity;
1. And as the [KIP-32](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message) says "for proper replica functioning".

As far as I can see it can be a one-line fix. Please correct me if I wrong.
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/kafka/kafka.go#L325
```go
m := &sarama.ProducerMessage{
	Topic: k.GetTopicName(metric),
	Value: sarama.ByteEncoder(buf),
	Timestamp: metric.Time(), // <- here
}
```

I quickly list some of the input plugins and accumulator code and almost all of them use the same logic `"Metric's timestamp" if empty then "Current timestamp"`

For example:
https://github.com/influxdata/telegraf/blob/master/agent/accumulator.go#L121
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/parser.go#L81

**Comment by danielnelson** [comment]
Thanks for the links, after reading KIP-32 it looks to me that most of the time the best solution is to set `message.timestamp.type=LogAppendTime` on the topic.  This will ensure all messages have a timestamp and allow you to do all the listed operations.

The time that `message.timestamp.type=CreateTime` is helpful is when you want batch rejection if `max.message.time.difference.ms` is exceeded.

That raises the need to decide what we will do if the broker rejects a write due to the `max.message.time.difference.ms`.  Since the timestamp would never change we can assume that retrying wouldn't be helpful, so perhaps we should delete the message with a warning?  This would mark the message as delivered if reading from another queue.

> I quickly list some of the input plugins and accumulator code and almost all of them use the same logic "Metric's timestamp" if empty then "Current timestamp"

All Telegraf metrics have a timestamp, this happens during creation on the input side so no worries here.

**Comment by johnatannvmd** [comment]
`message.timestamp.type=LogAppendTime` - is not really the correct time, because it is time when the broker appended a message to the topic's partition, and not the time when the metrics were created. The time difference between these two timestamps may differ.

According the [Documentation](https://kafka.apache.org/documentation/) this configuration parameter `log.message.timestamp.difference.max.ms` have default value `9223372036854775807` ms, it's about 292,471,205 years. So, if you intentionally change this value you should expect that your metrics may be dropped. This brings us to the next point.

>  Since the timestamp would never change we can assume that retrying wouldn't be helpful, so perhaps we should delete the message with a warning?

I think this error can be handled here:
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/kafka/kafka.go#L344
like:
```golang
if prodErr.Err == sarama.ErrInvalidTimestamp {
	log.Printf("E! Error writing to output [kafka]: The timestamp of the message is out of acceptable range, consider increase message.timestamp.difference.max.ms; dropping batch")
	return nil
}
```

`ErrInvalidTimestamp` is equals to the `INVALID_TIMESTAMP` from [here](https://kafka.apache.org/protocol#protocol_error_codes)

**Comment by johnatannvmd** [comment]
Today I came up with the idea to make this behavior optional and add a parameter that set `message.timestamp.type` for topics. Default is current behavior, do not set it explicitly. `LogAppendTime` just add this to the topic options. `CreateTime` add this parameter to the topic options and add `Timestamp` to the metric. Also, I think, we should add a disclaimer about `INVALID_TIMESTAMP` error.

**Comment by danielnelson** [comment]
I'm not sure that we need an option, like you said this would only cause an error if one had already modified the `max.message.time.difference.ms`, and if you want to use LogAppendTime just setting it seems that it will override the CreateTime method.  A disclaimer about the error never hurts though.

Can you review my pull request #6746, it's basically what we had above.
