### ISSUE TITLE
Set types for stats produced by BasicStats aggregator

### ISSUE THREAD

**Issue by kadaan** [influxdata/telegraf#6701]
### Proposal:
Configure the types for the stats produced by the BasicStats aggregator

### Current behavior:
Currently all stats produced by the BasicStats aggregator are Untyped.

### Desired behavior:
The stats produced by the BasicStats aggregator should be typed as Counter or Gauge where applicable.  Initially, we could go with Counter for the `count` stat and Gauge for the rest.

### Use case: 
It is helpful with a prometheus output to indicate the type of the metrics.

**Comment by powersj** [comment]
Hi,

Looks like you had some back and forth on the PR in the past. I know there was a concern about memory usage, but I want to backup. What is the use-case for adding this information to metrics? It sort of sounds like you want to add Prometheus-based metric types to the stats that are generated by BasicStats?

Thanks
