### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#6704]
I'm not really sure, if such a config of inputs.exec should work or not:
`[[inputs.exec]]
   commands = [
     "cd /home/dario/Development/python/check_ip_routes && source bin/activate && python run_telegraf.py",
   ]
   interval = "60s"
   timeout = "60s"
   data_format = "json"
   name_suffix = "_ip_routes"
`
If the script is executed, it gives the following output:
`{"10.21.217.00/25": 1, "169.254.0.00/16": 0, "172.16.179.00/24": 0, "172.17.0.00/16": 0, "172.18.0.00/24": 0, "192.168.10.00/24": 1}`

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
