### ISSUE TITLE
inputs.tail when file on NFS does not detect changes

### ISSUE THREAD

**Issue by nikstr** [influxdata/telegraf#6706]
### Relevant telegraf.conf:

```
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
[[inputs.tail]]
  files = ["/opt/nfs/tail_test_input"]
  from_beginning = false
  pipe = false
  data_format = "influx"
```

### System info:
Telegraf 1.12.5 (git: HEAD f09d4023)
Redhat7, NFSv3 (/opt/nfs/)

### Steps to reproduce:
1. Start telegraf on host1
2. Add data to /opt/nfs/tail_test_input from host2

### Expected behavior:

Telegraf should detect the new data in /opt/nfs/tail_test_input and print it to stdout.

### Actual behavior:

No output from telegraf.

### Additional info:

When data is written to the file from the same host as telegraf is running on, then telegraf detects the change and prints all the new data.
Tailing the file with the OS's tail command successfully detects new data even when written from other hosts.
So it seems telegraf's tail plugin fails to detect remote changes on NFS volumes.

**Comment by danielnelson** [comment]
The default method used by this plugin to monitor changes is inotify, and I don't believe it can work over NFS.  I think your issue will be solved by adding `watch_method = "poll"` to the tail plugin instead, let me know if it doesn't work.

**Comment by nikstr** [comment]
I see, thanks for the suggestion. Using poll worked.
