### ISSUE TITLE
vSphere Metrics units documentation

### ISSUE THREAD

**Issue by Hobadee** [influxdata/telegraf#6709]
## Feature Request

The vSphere plugin should list what unit the data is stored in for the METRICS.md file.  If that isn't practical, a link should exist to where more information on vSphere metrics exist.  (Despite extensive Googling, I can't find any information regarding the units data is stored as.)

If someone has a source of the data, I can make a PR.

### Use case: 

Currently when pulling vSphere data out of Telegraf, it's a guessing game as to the units the data is stored as.  In some cases, the units are easily guessable, but in other cases (KB vs KiB) it's a complete tossup.  These units need to be documented somewhere, or a link should exist to a 3rd party (VMWare?) where they are documented.

**Comment by Hobadee** [comment]
This site appears to have units, although I'm not sure where they came from or if they are accurate.  I cannot find sourcing on this site.

https://www.virten.net/2015/05/vsphere-6-0-performance-counter-description/

**Comment by goejja** [comment]
You can find metrics information on vmware website:
https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.PerformanceManager.html

**Comment by danielnelson** [comment]
I'd be happy to link to more information, but I don't think we should document the metrics ourselves.   @prydin Are you able to recommend a link?

**Comment by Hobadee** [comment]
@danielnelson That link that @goejja provided appears to have what is needed.  (Not on that specific page, but one link down when you click on the section of metrics you need.)

**Comment by prydin** [comment]
@danielnelson @Hobadee The set of metrics available is constantly growing and is (as @danielnelson points out) best documented by VMware and not by the Telegraf team. https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.PerformanceManager.html is indeed the definitive reference documentation.

**Comment by Hobadee** [comment]
@prydin Thanks!  I'll work on a PR which references that inside the METRICS.md file.
