### ISSUE TITLE
Interface field missing when using Grafana

### ISSUE THREAD

**Issue by mmihir82** [influxdata/telegraf#6710]
### Relevant telegraf.conf:

```
[[inputs.cisco_telemetry_mdt]]
transport = "grpc"
 service_address = ":57000"
 [inputs.cisco_telemetry_mdt.aliases]
   ifstats = "ietf-interfaces:interfaces-state/interface/statistics"

```

### NXOS Config info:
OS: 7.x
```
telemetry
  destination-profile
    use-vrf management
  destination-group 1
    ip address [TELEGRAF_IP] port 50007 protocol gRPC encoding GPB
  sensor-group 2
    data-source NX-API
    path "show interface"
  subscription 900
    dst-grp 1
    snsr-grp 2 sample-interval 5000
```

1. Unable to see the field `interface` in Grafana, but see the `interface` in Chronograf
2. In Grafana: field is being replace with `parent_interface` 
3. In Chronograf: there is no `parent_inteface` but it has `interface`

**Comment by danielnelson** [comment]
I can't think of why they would show different fields, how does the data in InfluxDB look using the CLI:
```
$ influx
> use telegraf
> show field keys from mymeasurement
```

If that's not helpful, can you attach some screenshots?

**Comment by mmihir82** [comment]
Actually, I did the debug, and found out the it show up in the tags
dictionary, as TABLE_interface. So I had to do groupby to filter to
populate.

Thanks for the help. You can close it.
