### ISSUE TITLE
[Question] vsphere datastore and host from guest os

### ISSUE THREAD

**Issue by mertbakir** [influxdata/telegraf#6721]
Hello,

I'm using influxdb and grafana with vsphere plugin and I want to get host and datastore metrics from guest os. host and datastore is variable and dynamic based on selected vm.

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
