### ISSUE TITLE
[Question] Can someone please explain the measuring unit of usage_total for cpu in docker input plugin

### ISSUE THREAD

**Issue by anil10032** [influxdata/telegraf#6722]
## Feature Request

Opening a feature request kicks off a discussion.

### Use case: 
Helps in better understanding the metrics from docker plugin

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
