### ISSUE TITLE
Trying to write data retrieved from inputs.httpjson to influxdb via telegraf, but don't want the default fields.

### ISSUE THREAD

**Issue by Avil172** [influxdata/telegraf#6723]
Hi. I am using telegraf 1.2.1 with inputs.httpjson and outputs.influxdb plugins.

The goal is to write the data to influxdb, and I am able to do it successfully. However, I am seeing additional fields in the measurement, eg- response_time, server , etc, which I don't want.

fielddrop doesn't seem to be working for those fields.

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
