### ISSUE TITLE
Support opLatencies in mongodb input plugin

### ISSUE THREAD

**Issue by rlodge** [influxdata/telegraf#6725]
## Feature Request

The mongodb input plugin should read the opLatencies field of the serverStatus output and report those metrics.

### Proposal:

Add DefaultLatencyStats to mongodb_data.go, and add LatencyStats and OpLatenciesStats structures go mongostat.go, and populate them if the data read from serverStatus contains the appropriate fields.

### Current behavior:

No latency stats are reported.

### Desired behavior:

Latency stats should be reported so that the plugin can more fully support monitoring mongo.

### Use case:

We are replacing a proprietary monitoring system with one based on InfluxDB, and the one piece of data we use a lot in the existing system that the plugin doesn't support is the opLatencies values

**Comment by powersj** [comment]
Fixed in #6725. Closing.
