### ISSUE TITLE
Memory leak of processes

### ISSUE THREAD

**Issue by sam4u3** [influxdata/telegraf#6727]
## Feature Request

Just wanted to know how we can capture memory leaks information.

### Proposal:
Is there any input plugin to capture memory leaks and heap data of processes.

### Current behavior:

Unable to get memory leaks details from mem input

### Desired behavior:

Need to capture memory leaks,OOM data in graph

### Use case: 

Gives the better idea of process performance and issue observed

**Comment by danielnelson** [comment]
You can use the procstat input to monitor the memory usage of a process.  For OOM, maybe an attempt can be made to parse syslog.  It would be better to discuss this further on the [InfluxData Community](https://community.influxdata.com) site.
