### ISSUE TITLE
JSON parser silently fails if tag_keys contains 6 keys

### ISSUE THREAD

**Issue by tiger-seo** [influxdata/telegraf#6738]
### Relevant telegraf.conf:
working conf:
```toml
[[inputs.file]]
  name_override = "json_issue"
  files = ["/etc/telegraf/telegraf.d/test.json"]
  interval = "1s"
  data_format = "json"

  tag_keys = [
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
  ]

  json_string_fields = [
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
    "field6"
  ]

  json_time_key = "datetime"
  json_time_format = "2006-01-02T15:04:05.000"

[[processors.printer]]
  namepass = ["json_issue"]
```

not working conf:
```toml
[[inputs.file]]
  name_override = "json_issue"
  files = ["/etc/telegraf/telegraf.d/test.json"]
  interval = "1s"
  data_format = "json"

  tag_keys = [
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
    "field6",
  ]

  json_string_fields = [
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
    "field6"
  ]

  json_time_key = "datetime"
  json_time_format = "2006-01-02T15:04:05.000"

[[processors.printer]]
  namepass = ["json_issue"]
```

#### test.json
```json
{"field1":"5f2339ce-b3db-4195-9a19-24085c22fd99","field2":"SEARCH","field3":"JSON","field4":"XY","field5":"XX","field6":"SUCCESS","datetime":"2019-12-02T18:15:58.710"}
```

### System info:

- Telegraf 1.12.6 runnning in Docker (image: 1.12.6-alpine)
- Host OS: Ubuntu 16.04.4 LTS

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

json produces metrics in same manner as it does when `tag_keys` contains 5 keys

### Actual behavior:

if `tag_keys` contains 6 keys json parser doesn't produce metrics and no errors printed

**Comment by danielnelson** [comment]
Interesting example, what appears to be happening is that the json parser doesn't allow for a field to be both a tag and a field, preferring tags.  Telegraf metrics must have at least one field and once they all fields are converted into tags the metric is removed, this requirement is based on how the bulk of the outputs work.

Usually you wouldn't want a value as both a tag and a field, so I don't think we should make any change here.

**Comment by tiger-seo** [comment]
@danielnelson please, suggest how to how a field both string and a tag without declaring it in both of tag_keys and json_string_fields ?  also, i suggest to mention about this in the documentation

**Comment by danielnelson** [comment]
I don't believe it is possible to do this with the JSON parser.  It's not something you would normally want though anyway, can you tell me more about why you want the tags also as fields?

I added a note about this behavior: 48f9f22f33b35139433e5ebd2008244c6c929616
