### ISSUE TITLE
prometheus metrics version 2 is not allow colon

### ISSUE THREAD

**Issue by JoveYu** [influxdata/telegraf#6748]
prometheus output metrics version 2 is not allow colon in metric name 

the `:` is replaced by `_`

```
xxx::xxx{label="xxx"}

xxx__xxx{label="xxx"}
```

**Comment by danielnelson** [comment]
Thanks, really appreciate the testing, this should be fixed in [1.13.0-rc1](https://github.com/influxdata/telegraf/releases/tag/1.13.0-rc1).
