### ISSUE TITLE
[[inputs.win_services]] details

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6755]
Hi Team, 

We are using "[[inputs.win_services]]" for windows services monitoring. so is there any features in telegraf to monitor multiple services in one keyword with start (*) 

[[inputs.win_services]]
service_names = ["ABC*"]

suppose 10 services are running with ABC_1, ABC_2 and so on.

**Comment by danielnelson** [comment]
It isn't possible to use globs today, but we have an issue open for it: #5756
