### ISSUE TITLE
Plugin uwsgi returns "dial unix: missing address" error when using sockets

### ISSUE THREAD

**Issue by hkraal** [influxdata/telegraf#6763]
### Relevant telegraf.conf:
```toml
[[inputs.uwsgi]]
  servers = ["unix:///tmp/stats-test.sock"]
```

### System info:
* Telegraf 1.12.6 (git: HEAD 6c7f2d62)
* Debian GNU/Linux 9.11 (stretch)
* uWSGI 2.0.18

### Steps to reproduce:

1. Start uWSGI process with `uwsgi -s /tmp/test.sock --stats /tmp/stats-test.sock`
2. Add the needed telegraf input to the config (see Relevant telegraf.conf).
3. Run telegraf with `telegraf --config telegraf.conf --input-filter uwsgi --test`

### Expected behavior:

I would expect the output as documented. 

### Actual behavior:

The following output is given:
```
2019-12-06T12:59:04Z I! Starting Telegraf 1.12.6
2019-12-06T12:59:04Z E! [inputs.uwsgi] Error in plugin: dial unix: missing address
2019-12-06T12:59:04Z E! [telegraf] Error running agent: One or more input plugins had an error
```

### Additional info:

I tried the TCP socket as well (`uwsgi -s /tmp/test.sock --stats :1337` + `servers = ["tcp://localhost:1337"]`) and this works correctly.

**Comment by danielnelson** [comment]
Would you be able to test this fixed version?

- [telegraf_1.14.0~a3ae3297-0_amd64.deb](https://44971-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.14.0~a3ae3297-0_amd64.deb)

**Comment by hkraal** [comment]
Yes will do!

**Comment by hkraal** [comment]
@danielnelson looking good, thank you for the quick patch!
