### ISSUE TITLE
Add stastd output format

### ISSUE THREAD

**Issue by ruowan** [influxdata/telegraf#6774]
## Feature Request

My collection service only support stastd UDP protocol. I use Kubernetes input plugin, but its output data format is influx. How can I transform influx line protocol to stastd data format?

### Current behavior:

I can't find any plugin supported this transform.

**Comment by danielnelson** [comment]
Can I ask what tool are you sending data to?

**Comment by ruowan** [comment]
> Can I ask what tool are you sending data to?

I used geneva MDM it seems Microsoft internal. My collection service only support stastd UDP protocol.

**Comment by ruowan** [comment]
I find a solution. We can create a new serializer called stastd which is responsible for translating telegraf metric to stastd format. And we can use data-format stastd in udp_sockerwriter. 

I am interested in this feature.  Can I create a  PR for it?

**Comment by danielnelson** [comment]
That sounds good, what is your plan for translating the `telegraf.Metric` into a statsd metric name?  Take a look at the Graphite serializer for ideas.
