### ISSUE TITLE
Parameter logfile_rotation_max_size does not work as expected

### ISSUE THREAD

**Issue by Lars-Diehl** [influxdata/telegraf#6776]
I evaluated log file rotation based on file size (Parameter logfile_rotation_max_size ) with telegraf 1.12.6 under Windows.

After some Research it looks like the current implementration uses the  number of bytes written to the log file by the program instead of using the actual file size of the logfile.

So the log file is not switched when a certain file size is reached but when a certain number of bytes have been written to the log after the program has been started. 

Either the documentation or the implemtation needs to be changed. I would vote for the latter.

**Comment by danielnelson** [comment]
Agreed, this is a bug and the implementation should be fixed.

**Comment by HarshitOnGitHub** [comment]
Have opened a PR for this: #7133.
