### ISSUE TITLE
Telegraf Exec Plugin - not logging/showing errors (Win + Powershell)

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#6777]
I posted this question in the community but had no answers, so here I am with an issue.

I’m using Telegraf to gather some data using a Powershell script which errors are not logged by telegraf, simply nothing happens, the telegraf process runs like if everything is ok.

I'm not sure if this a telegraf problem, but it's surely related to the use of a script file as command, in fact, if the same command is executed without using a script file telegraf throws an exception.

### Relevant telegraf.conf:
```
[agent]
  ## Log
  debug = true
  quiet = false

  ##  empty string means to log to stderr.
  #logfile = ""

[[inputs.exec]]
  ## Commands array
  commands = [
    'powershell.exe "C:\Monitoring\telegraf\myScript.ps1"'
  ]
```

### System info:

- Windows Server 2019 Standard (v1809), Windows 10 (v1903)
- Telegraf 1.12.5

### Steps to reproduce:

1. Create a script file (myScript.ps1):
```
Get-CimInstance CIM_LogicalDisk -ComputerName _RemoteHost_
Note: in the full script the data gets formatted in influx line format, but to show the problem that’s not needed since it explodes at the first command)
```
2. Run myScript.ps1 from Powershell or cmd (with a user that does **not** have the permission to use "Get-CimInstance" command on the remote host, or use a host that does not exists)
```
#Powershell
.\myScript.ps1
#cmd
Powershell.exe -Command "C:\Monitoring\telegraf\myScript.ps1"

# you get the following error:
Get-CimInstance : Access is denied.
```
**So far everything is ok.**

3. run the same command through telegraf
```
.\telegraf.exe --config .\test.conf --test

#Output
2019-12-06T14:05:17Z I! Starting Telegraf 1.12.5
2019-12-06T14:05:17Z D! [agent] Initializing plugins
#and that's it no errors, just nothing
```

### Expected behavior:

- telegraf logs/shows the error 
**or** 
- telegraf throws an exception "Error running agent: One or more input plugins had an error" and does not run at all
(to the second behavior, instead of executing a script file just execute
```
 # execute the command without using a script file (config file)
commands = [
    'powershell -Command "Get-CimInstance CIM_LogicalDisk -ComputerName _RemoteHost_"'
  ]

# the same can be achieved by creating an exception on the fly
commands = [
  'powershell -Command "Write-error aaa"'
 ]
```

### Actual behavior:

No error is displayed and the process/service run as if everything is ok

### Additional info:

The full powershell script can be found in [this comment](https://github.com/influxdata/telegraf/issues/6762#issuecomment-562566016) in another github issue

**Comment by danielnelson** [comment]
I suspect this means the script is not exiting with a non-zero status code, which is how Telegraf detects command failure.  I know essentially nothing about powershell, but try ending the script with `exit 1`.

[reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-6#exit)

Let me know if that works.

**Comment by Trovalo** [comment]
That's it.
I did more tests in order to manage errors and propagate them correctly to the cmd (and therefore to telegraf), here is what I found out:

sample "error.ps1" file
```
Get-CimInstance CIM_LogicalDisk -ComputerName _NotExistingPc_
Exit 111
```

1. Always specify an exit code in the Powershell in case of error script ( 0 = ok,  >0 = not ok ), otherwise the exit code will be 0
2. The returned exit code depends on the option used in the "powershell" command:
⋅⋅2a. The "-File" option will return the exit code specified in the file
```
powershell -File .\error.ps1
echo %errorlevel%
```
⋅⋅2b. The "-Command" option will return a more generic exit code (0 or 1), 0 when 0 or not specified and 1 when  != 0
```
powershell -Command .\error.ps1
echo %errorlevel%
```

If the exit code is managed in this way telegraf will correctly return the error:
_Error in plugin: exec: exit status 1 for command {...}_

**Summarizing**
Not specifying an exit code in the Powershell file will cause the exit code to be 0, regardless of the success|failure of the script itself.

**Comment by evolart** [comment]
I am running into telegraf flooding my logs with this error for a Powershell script as well. I have modified the script it's running to test with an exit code of both 0 and 1 and I continually see an error showing "Error in plugin: exec: exit status 1 for command". I don't understand the cause though as the output from the script is showing in telegraf?
