### ISSUE TITLE
SNMP Trap Hex-STRING translation disable option

### ISSUE THREAD

**Issue by AlexTargo** [influxdata/telegraf#6778]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add an option to disable the translation of Hex-STRING translation.

### Current behavior:

When an Hex-STRING is sended to the SNMP-Trap plugin, the Hex is automatically converted to text.

### Desired behavior:

Have the option the disable the Hex tranlation and let Telegraf write the raw result in the output.

### Use case: 

We are developing our own management system for OLT and gpon ONU. Telegraf and Influxdb is helping us centralizing monitoring but some SNMP Trap return are Translated when written to the DB and it alter the information.

I added a Pcap and the output of Telegraf to help find the issue location.
[snmptrap.zip](https://github.com/influxdata/telegraf/files/3940640/snmptrap.zip)
> snmp_trap,host=TelegrafSNMPTrap,mib=GPON-AUTO-AUTH-RULE-MIB,name=rcGponSystem.4.1,oid=.1.3.6.1.4.1.8886.18.3.1.4.1,source=172.17.1.2,version=2c rcGponSystem.3.1.1.1.293666817=293666817i,**rcGponSystem.3.1.1.2.293666817="RCMG▒**}",rcGponSystem.3.1.1.3.293666817="",rcGponSystem.3.1.1.4.293666817="",rcGponSystem.3.1.1.5.293666817="",sysUpTime.0=17935744i 1575906472304319958

**Comment by MyaLongmire** [comment]
I am going to close this as `snmpt_trap` has gone through a major rework. If you are having issues with the recent `snmp_trap` update, please open another ticket with all relevant information. Sorry for the inconvenience.
