### ISSUE TITLE
Add ResourcePool metrics collector for Vsphere plugin

### ISSUE THREAD

**Issue by Neferites** [influxdata/telegraf#6782]
## Feature Request
Opening a feature request kicks off a discussion.

### Proposal:Feature Request
Currently there is a Telegraf vsphere input plugin, which collects metrics from vsphere. The module collects and provides metrics on vmware hosts clusters datastore and virtual machines.

There is no metrics for Resource Pool, to see CPU contention.

Proposing development of an input plugin to support Resource Pool metrics collect.

Current behavior:
Currently the Plugin for vsphere does not collect ResourcePool metrics

Desired behavior:
Plugin can collect.

Use case: [Why is this important (helps with prioritizing requests)]
ResourcePool can be used to manage VM classes. If a resource Pool isn't big enouth, max limited can appear on VM, implying CPU contention. It can be usefull to monitor all vm on a RP at once.

**Comment by Neferites** [comment]
i just read that telegraf use govc.
is it possible to create a pool_metric_include based on : 

```
govc pool.info "/Path/to/Resources/*"
Name:               *****
  Path:             /Path/to/Resources/*
  CPU Usage:        38502MHz (19.1%)
  CPU Shares:       custom (240000)
  CPU Reservation:  0MHz (expandable=true)
  CPU Limit:        201800MHz
  Mem Usage:        894283MB (23.5%)
  Mem Shares:       custom (4000000)
  Mem Reservation:  0MB (expandable=true)
  Mem Limit:        -1MB
```
Or is it possible to use a generic include as optional_metric_include and start collecting them ?
exemple
```
optional_metric_include[
  "pool.cpu.usage.average",
  "pool.cpu.usage.limit",
   "pool.mem.usage.average"
]
```

Best regards

**Comment by prydin** [comment]
I'm currently looking into this. I will give you an idea of the level of effort to implement this shortly.

**Comment by Neferites** [comment]
@prydin thanks a lot. And really nice work on telegraf team !!!

**Comment by mikkoss** [comment]
This would be nice addition to collection as most people do use resource pools for isolating loads. Collecting statistics for them would be very useful. 

Hopefully this gets some attention.

**Comment by evelinabut** [comment]
Are there any updates on this topic?
I am also interested in this feature and it would be nice collecting metric of Resouce Pool using the telegraf vsphere plugin.
Thanks and best regards
