### ISSUE TITLE
Gateway ID missing from MQTT (The Things Network)

### ISSUE THREAD

**Issue by sjj698** [influxdata/telegraf#6783]
TTN provides lots of metadata, it would appear that some of it is NOT imported into Influx.
For example:
on the root of the JSON 
{...
"data_rate": "SF10BW125",
…}

The one I am after is the gateway ID

 "gateways": [
    {
      **"gtw_id": "eui-b827ebfffee36ef8",**
      "timestamp": 1882453772,
      "time": "2019-12-10T13:30:01.247168Z",
      "channel": 1,
      "rssi": -107,
      "snr": 2,
      "rf_chain": 1,
      "latitude": 50.93682,
      "longitude": -1.40454,
      "altitude": 85
    },

Is this an issue with strings, are only int/float converted ? If so how can I go about changing this. 

### Relevant telegraf.conf:

```toml
#Using the example config , data type json
[[inputs.mqtt_consumer]]
```

### Steps to reproduce:
Stock config and any TTN

### Expected behavior:
I expect a field
gateways_0_gtw_id 
### Actual behavior:
No fields with strings are output

**Comment by timhallinflux** [comment]
@davidgs -- FYI

**Comment by danielnelson** [comment]
> Is this an issue with strings, are only int/float converted ? If so how can I go about changing this.

When using `data_format = "json"` by default strings are ignored.  You can add strings to the `tag_keys` option to create a tag, or `json_string_fields` option to add as a field.
