### ISSUE TITLE
MySQL Input Plugin should have config option to disable collecting global vars

### ISSUE THREAD

**Issue by benhymans** [influxdata/telegraf#6789]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 
There should be a config value that allows for enabling/disabling collection of global variables.

### Current behavior: 
Global Variables are always collected if the input plugin is active

### Desired behavior: 
Setting a config value to false would prevent global variables from being collected

### Use case: 

Global Variables could contain sensitive information, and depending on the permissions policy in influx, and the downstream systems (grafana, etc), this could pose a security risk. The data is useful though, so I propose allowing the engineer configuring the input plugin the option to enable/disable collecting this data.

I intend to submit a PR to enable  this functionality.

**Comment by Esity** [comment]
@danielnelson @glinton This can be closed with the successful merge of #6790
