### ISSUE TITLE
Using group by of 10 seconds causes the group windows to be at the 00,10,20,30,40,50 second time stamps

### ISSUE THREAD

**Issue by Supagoat** [influxdata/telegraf#6791]
For the most part our data collection from telegraf looks good, but exactly every 5 minutes/300 seconds we have 2 sets of measures, one of which just has all 0s for the values. 
Our telegraf conf is barely modified from default... Here's the agent section:
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

### System info:

telegraf 1.12.1 sending data to influxdb 1.7.8 and we're using chronograf 1.7.14
centos 7 kernel 3.10.0-327.el7.x86_64
We have telegraf installed on 125 machines, a combination of virtual and physical and this can be observed in the data from all of them.

### Steps to reproduce:
Once telegraf/influxdb/chronograf 
Export the data for a time period greater than 5 minutes and scroll through it. until you find a timestamp that has double the number of records of all the other timestamps, and half of the records discovered for that timestamp are 0 for all measures

An example of such a timestamp is 1575403650

### Expected behavior:

I would expect to see only the single set of data for 1575403650 with actual values

### Actual behavior:

Every host has 2 records for 1575403650, and one of those records contains 0s for all measures

**Comment by danielnelson** [comment]
Can you add how are you exporting the data and show an example of the unexpected data?

**Comment by Supagoat** [comment]
Sorry it took so long, I'm doing a little more investigation into whether our export method could be contributing.

I'm exporting using python, 

One thing I was able to confirm just now is that it's not related to the data in Influxdb. I performed 2 exports of the same data, but the second with a time window offset by 1 minute from the first and what I see is that the 0s appear after 5 minutes in both exports.  So in export 1 which started at 2020-01-02T01:01:01.000Z I see the 0s at 1577945160 (01:06) but in export 2 which started at 2020-01-02T01:02:01.000Z the 0s are at timestamp 1577945220 (01:07).  I'll spend some more time looking at whether the script could be impacting this and write with an update.

**Comment by Supagoat** [comment]
@danielnelson I tracked down the cause and am able to reproduce it both from my python program and from queries written in Chronograf.  InfluxDB is returning all 0s at the end of a time period, and the way my python script works is that it executes multiple 5-minute time window queries as part of a large export.  

So for example: 

_SELECT mean("value") AS "value" FROM "hvmetrics"."autogen"."cpu0-C1" where time >= '2020-01-02T01:02:01.000000Z' and time <  '2020-01-02T01:07:01.000000Z' GROUP BY time(10000ms), "host" FILL(0)_

Will return the expected values at every 10 second slice, but then for the timestamp 01:07:01:00.000 it returns the value of 0 for every host.  If I then run:

_SELECT mean("value") AS "value" FROM "hvmetrics"."autogen"."cpu0-C1" where time >= '2020-01-02T01:07:01.000000Z' and time <  '2020-01-02T01:12:01.000000Z' GROUP BY time(10000ms), "host" FILL(0)_

I get actual values with a timestamp of 01:07:00.  

However, if I change my query to have 00 seconds, so for example from 2020-01-02T01:07:00.000000Z to 2020-01-02T01:12:00.000000Z I can no longer reproduce the problem.

I'm guessing here, but it looks like what's happening is that the group by time isn't working the way I expected...    It looks like that group by 10000ms statement is causing the query to use 00, 10, 20, 30, 40, 50 seconds on the clock as the time window that it collects data from, but I'm guessing there was no data in influxdb timestamped between 01:07:00 and 01:07:01 so it reports all 0s using the fill value and treating that 1 second time period as if it were 10 seconds.

What I expected this query to do was to base its 10 second grouping off of the start time in the query, so I would expect the times in the resultset to be 01:01:01, 01:01:11, 01:01:21, etc but instead it returns timestamps of 01:01:00, 01:01:10, 01:01:20, etc.

**Comment by danielnelson** [comment]
I think I understand, since `group by` returns aligned windows I would think you definitely want to query over evenly divisible windows.  There is more control for windowing built into the InfluxDB 2.0 [window][] function, I can't speak for the database team but I suspect this would be the ultimate fix if you aren't about to query the aligned windows.

I'm going to close since this isn't a Telegraf issue.

[window]: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/window/
