### ISSUE TITLE
Telegraf is unable start when using uwsgi in on-demand mode

### ISSUE THREAD

**Issue by hkraal** [influxdata/telegraf#6795]
I was not sure if this should be a bug or feature request, if this should be a feature request my apologies.

The problem is that after starting uWSGI in on-demand mode not all stat ports are actually available. There needs to be a request first to activate the vassal after which you can see something actually listening on port 9191.

Telegraf however will not start if any stat socket is unreachable.

### Relevant telegraf.conf:
```toml
[[inputs.uwsgi]]
  servers = ["tcp://localhost:9191"]
```

### System info:
* Telegraf 1.12.6 (git: HEAD 6c7f2d62)
* Debian GNU/Linux 9.11 (stretch)
* uWSGI 2.0.18

### Steps to reproduce:

In any directory of your choosing;
1. Create the needed directories
`mkdir vassals sockets`

2. Start uWSGI in emperor mode with ondemand
```
uwsgi --master --thunder-lock --emperor vassals/ --emperor-on-demand-directory sockets/ --emperor-on-demand-extension socket
```

3. Create an example vassal
```
cat <<EOF > vassals/example.ini
[uwsgi]
socket = 127.0.0.1:3031
chdir = /tmp/uwsgi
wsgi-file = myproject/wsgi.py
processes = 4
threads = 2
stats = 127.0.0.1:9191

EOF
```

4. Try to start Telegraf

### Expected behavior:

I would hope to see telegraf actually starting, and gathering statistics when the vassal is activated. 

### Actual behavior:

Telegraf is unable to start;
```
2019-12-12T13:59:21Z E! [telegraf] Error running agent: One or more input plugins had an error
```

### Additional info:

The stats socket (tcp or unix) is being created when the first requests comes in when running uwsgi in emperor mode with on-demand. Existing stats sockets could also disappear after being initially activated when `--idle` and `--die-on-idle` are set.

Not much unlike with phpfpm althought the same socket is used for requests and stats alike.

**Comment by powersj** [comment]
Hi,

Going through old issues and feature requests and seeing what folks still are interested in. Is this something you have worked around or are still interested in?

Thanks!

**Comment by hkraal** [comment]
I worked around it with a modified build. I would feel better if Telegraf could handle it gracefully on the regular release though.

**Comment by powersj** [comment]
Thinking "out-loud" here...

I fully understand and agree that the initial PR to add skip_errors is not the solution we will want. One option might be to add a configuration for a startup mode. You could put in a value like "emperor" which would maybe hit the socket a couple of times before erroring out? That way this behavior is opt-in and still has an exit path.

Thoughts?

**Comment by hkraal** [comment]
I think that retrying the connection before erroring out is the most optimal solution. When having several dev projects (or just very low traffic sites) with emperor mode enabled it's plausible that some instances won't start for weeks at the time. Wouldn't that problem still exists in your train of thoughts?

**Comment by powersj** [comment]
The way it sounded like Telegraf's first request would fail, but that demand would start the socket. Then the second attempt would sucessed. However, your last response makes me doubt that and think that it is not Telegraf that is causing the demand but your other applications?

**Comment by hkraal** [comment]
Yes, if I recall correctly; the stats socket won't be there until an actual request has been made to the application.

The main culprit is that Telegraf needs the sockets to exist when it starts. If a defined socket isn't actually there yet starting telegraf is impossible.

If you start Telegraf however when all sockets exists initially it will remain to function properly even when the sockets are removed (reaped) and spawned when requests are made.

**Comment by powersj** [comment]
Thank you for the clarification.

As a team, we have further discussed having retry mechanisms for when an input or an output is unavailable. We understand that network blips or systems go down for a period of time. However, I do not think we would cover the use-case you are after where we re-try when something is down for hours/days/weeks. 

Ultimately, for your scenario, I believe using a custom script + the exec/execd plugins is going to be the best solution here. As such I am inclined to close this issue.

**Comment by hkraal** [comment]
If the team feels it that way I can only support that.

One slight, but I think important detail, is that the uwsgi plugin already handles the absence of stats sockets correctly when Telegraf is up and running.

It's just that on startup is seems to require all sockets to be present and working.

**Comment by powersj** [comment]
ok thanks for the understanding and jumping back on the old issue, I do appreciate the back and forth and again sorry no one worked through this with you previously.
