### ISSUE TITLE
Binary data parser feature request

### ISSUE THREAD

**Issue by yolkhovyy** [influxdata/telegraf#6804]
## Feature Request

Binary Parser similar to the existing Value Parser with a possibility of parsing binary-encoded data (records) with multiple fields.

### Proposal:

Implement a Binary Parser able to parse binary-encoded data (records) containing multiple fields.

A working prototype for raw binary records is here: https://github.com/yolkhovyy/telegraf/tree/develop/plugins/parsers/bindata. At the end the Binary Parser will also support other binary data encoding protocols such as Protobuf or CBOR.

The binary data (record)  parser configuration is shown below, where record's fields are specified by name, type, offset and optional size. Also common parameters such as endianess, binary protocol and time field format are specified:
```toml
[[inputs.mqtt_consumer]]
  name_override = "drone_status"

  ...

  data_format = "bindata"
  bindata_protocol = "raw"
  bindata_endiannes = "be"
  bindata_time_format = "unix"
  bindata_fields = [
    {name="version",type="uint16",offset=0},
    {name="time",type="int32",offset=2},
    {name="location_latitude",type="float64",offset=6},
    {name="location_longitude",type="float64",offset=14},
    {name="location_altitude",type="float32",offset=22},
    {name="orientation_heading",type="float32",offset=26},
    {name="orientation_elevation",type="float32",offset=30},
    {name="orientation_bank",type="float32",offset=34},
    {name="speed_ground",type="float32",offset=38},
    {name="speed_air",type="float32",offset=42,size=4},
    {name="status",type="string",offset=46,size=10},
  ]
```
### Current behavior:

Only a single scalar value parsing is supported - by the Value Parser.

### Desired behavior:

Be able to parse binary records, raw and in the future - Protobuf, CBOR. 

### Use case: 

Parsing binary-encoded data from IoT and other domains.

**Comment by danielnelson** [comment]
I think this looks good overall, here are few ideas:

With `bindata_protocol = "raw"`, the idea is that alternates would be protobuf or CBOR?  I think we shouldn't worry about these formats here, we can add specialized parsers for these.

For `type="string"`, let's be specific with the string encoding: `type="utf-8"`.

We could specify the fields without the offset if we introduced a padding type, the padding type would just be discarded.  I feel like this would be easier to work with:
```
    {name="version",type="uint16"},
    {type="padding",size=2},
    {name="location_latitude",type="float64"},
    {name="location_longitude",type="float64"},
```

**Comment by yolkhovyy** [comment]
I agree that Protobuf and CBOR deserve dedicated parsers.

Regarding UTF-8 for `type="string"` - my idea for `type` was to use Go type names, for strings that would be `type="string"` but youare right - what ab out other encodings? Maybe an `encoding` property in string fields? With default UTF-8:
    {name="status",type="string"}
and explicit:
    {name="status,type="string",encoding="ASCII"}

Padding would do the work of skipping fields then offset is not needed, agree with that too.
