### ISSUE TITLE
Feature request: Cassandra input plugin

### ISSUE THREAD

**Issue by mpmlj** [influxdata/telegraf#681]
Hi,
Is it possible to provide Cassandra input plugin for Telegraf?

Here's an example, but using a different agent: http://www.pythian.com/blog/monitoring-cassandra-grafana-influx-db/

Thank you
D.

**Comment by tripledes** [comment]
I'd be interested on working on this input plugin but I'd need some help here as I don't have any experience with Cassandra.

@mpmlj I've checked the link you've provided and the first problem is that it uses a JAR to push the metrics and we'd need to pull. Are you aware of any way to query the metrics? The only way I found so far is to query JMX.

**Comment by tripledes** [comment]
@mpmlj BTW, have u thought about using jolokia plugin ? https://medium.com/@mlowicki/monitoring-cassandra-a7fde5b2de9c#.qpt4783ra
