### ISSUE TITLE
Add "strcase" conversions to Strings Processor Plugin

### ISSUE THREAD

**Issue by druchoo** [influxdata/telegraf#6811]
## Feature Request
My current need is to convert fields from CamelCase to snake_case. Although this is preference, I think if something like [strcase](https://github.com/iancoleman/strcase) was used, it would be very flexible.

### Proposal:
Implement functions from [strcase](https://github.com/iancoleman/strcase) in [Strings Processor Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/processors/strings).

### Current behavior:
Strings Processor Plugin already implements some very useful functions.

### Desired behavior:
Implement useful case conversion functions.

### Use case: 
Using http plugin to consume API that returns data with keys using CamelCase. I'd like to convert the keys to snake_case.

**Comment by danielnelson** [comment]
I like this idea but have some concerns about the apparent number of allocations in the strcase library.  Writing some simple benchmarks would be a good start.

**Comment by powersj** [comment]
Hi,

It doesn't seem like we have had much interest in this feature for now. Using starlark to convert from CamelCase to snake_case is an option for now. I am going to close this feature request for now.

Thanks
