### ISSUE TITLE
Detect when bot was removed from the room?

### ISSUE THREAD

**Issue by hems** [influxdata/telegraf#6828]
## Feature Request

I would like to know when my bot was removed from a group chat

### Proposal:

We should have an event just like `new_chat_members ` and `left_chat_member` ? 

### Current behavior:

Currently i can check for "new_chat_members" and see if the `id` is the same id from the bot, but using the botInfo property.

But when the bot is removed i'm not receiving a `left_chat_member` event?

### Desired behavior:

`left_chat_member` to be executed when the bot is removed from the room

### Use case: 

We're creating a bot that can be added and removed to groups, would be good to monitor how many groups the bot is currently active.

Of course, other features could be created on top of this little feature, but currently our only requirement is to monitor which rooms the bot is participating.

**Comment by danielnelson** [comment]
I think you meant to open this issue with https://github.com/telegraf/telegraf

**Comment by hems** [comment]
> I think you meant to open this issue with https://github.com/telegraf/telegraf

yes, apologies about that
