### ISSUE TITLE
Plugin: file input, feature to delete file

### ISSUE THREAD

**Issue by tylersiemers** [influxdata/telegraf#6837]
## Feature Request

Add option to have the file input delete the data metric after it outputs it

### Proposal:

Add the following options to the file plugin conf:

file_delete = bool
file_base = string (/path/to/files/)

### Current behavior:

Currently, after specifying a directory to read files from you have to manually clean up the files using a cron job or other methods.

### Desired behavior:

If file_delete is set to true the plugin would delete the file after it outputs the data.

### Use case: 

We have two situations that involve a server that is only capable of exporting in .csv format. We SFTP those files over to the telegraf box, use the file input. Then run a cron job that deletes ever X mins. Would be nice to do it straight from the plugin. After successfully reading the metrics and output, delete file.

I have started this on my fork in GitHub. Currently, it works but needs more checks and balances.

https://github.com/tylersiemers/telegraf/tree/master/plugins/inputs/file

**Comment by danielnelson** [comment]
I see this as being a new plugin, not part of the file input, which implements a filesystem based messaging/queue system.  Ideally, it would be able to watch a directory with the methods from https://github.com/fsnotify/fsnotify and add tracking metrics, the file would be deleted when all metrics are delivered.

**Comment by tylersiemers** [comment]
fsnotify looks interesting. This is a better route, it would be nice to only delete after the metrics are successful. Currently, the method I have blindly deletes the file with no confirmation it was actually output. I would assume you would be using some kind of api call to influxdb to check if the metrics was successful or where would the tracking metric be implemented?

**Comment by danielnelson** [comment]
We have a mechanism for being notified when a metric is written successfully: https://github.com/influxdata/telegraf/blob/master/docs/INPUTS.md#metric-tracking

**Comment by powersj** [comment]
Hi,

If someone is still interested in something similar, I would suggest looking at the Directory Monitor plugin. Users can specify a directory to watch and Telegraf will read files as they come in. The user can also specify a directory to move the files into after they are read.

The user can then periodically delete the files in the successfully read directory.

I am going to close this issue. Thanks!
