### ISSUE TITLE
httpjson service plugin

### ISSUE THREAD

**Issue by brettdh** [influxdata/telegraf#684]
I would essentially like an equivalent to Fluentd's [http input plugin](http://docs.fluentd.org/articles/in_http), which listens for incoming connections and expects to receive HTTP POST requests (JSON by default, but format is configurable). Telegraf's httpjson input plugin (like all of them, I gather) instead makes requests to retrieve data from a remote endpoint; I _think_ Telegraf uses the "service plugin" term to distinguish these two classes of data sources.

**Comment by ddes** [comment]
Nice idea, I'm also looking for something like this.

**Comment by francois2metz** [comment]
I'll try to implement that as a sub-webhook plugin.

**Comment by danielnelson** [comment]
There is now the http_listener input plugin, which I believe is meant to be general purpose but currently lacks anything other than influxdb line protocol.  On the other hand, I believe webhooks should be used only for supporting specific services.

Maybe we should add full parser support to the http_listener?
