### ISSUE TITLE
Kubernetes (EKS) Monitoring master nodes `etcd` 

### ISSUE THREAD

**Issue by sudhishkasabaramesh** [influxdata/telegraf#6840]
## Feature Request

Opening to discuss if `inputs` (`kubernetes` & `kube_inventory`) can accomodate `etcd` metrics

### Proposal:
From my quick 1hr experimentation, I have realized that `kube_inventory` pulls metrics from Kubernetes Master APIs. If that is correct can we pull `etcd` metrics as well.

### Current behavior:
It pulls persistent volumes, statefulsets and other required items. But getting visibility into the control plane will be helpful.

### Use case: 
EKS visibility into master nodes is not great at the moment.

I am open to other suggestions around this as well. For the moment I have `kubernetes` & `kube_inventory` inputs working & configured correctly using `helm`.

**Comment by danielnelson** [comment]
Are you referring to the `/metrics` endpoint on the etcd servers?  These can be collected using the `prometheus` input plugin.

**Comment by sudhishkasabaramesh** [comment]
@danielnelson - you are correct. I realized this an hour after i filed the issue, and I never got back to updating it & closing it.

This is already solved, and I was not looking correctly. Thanks for updating the case.
