### ISSUE TITLE
Include "busyExecutors" field in jenkins input plugin metircs

### ISSUE THREAD

**Issue by vikkyomkar** [influxdata/telegraf#6843]
## Feature Request

Opening a feature request kicks off a discussion.

**Comment by vikkyomkar** [comment]
i would like to contribute for this feature

**Comment by danielnelson** [comment]
Thanks for offering to help.  Since this is a stat that isn't attached to a particular node maybe we should add a new `jenkins` measurement that contains these top level fields:
```
jenkins,source=example.org,port=443 busy_executors=42i,total_executors=42i
```

**Comment by tfoldi** [comment]
Basically we need something similar. The number of queued builds and currently running builds. I am also happy to contribute. Top level measurement looks good.
