### ISSUE TITLE
inputs.cisco_telemetry_gnmi crashes when request a specific field

### ISSUE THREAD

**Issue by door7302** [influxdata/telegraf#6847]
Hello 

when we request a specific field (full path) the plugin crashes and stops 

Sample config : 
```
[[inputs.cisco_telemetry_gnmi]]

  addresses = [
        "xxxxxx:57400"
        ]
  encoding = "json"
  redial = "30s"

  [[inputs.cisco_telemetry_gnmi.subscription]]
    name = "PHY_COUNTERS"
    path = "/state/port[port-id=*]/ethernet/oper-speed"
    subscription_mode = "sample"
    sample_interval = "30s"
```
And the crash info : 
```
2020-01-02T14:48:23Z I! Starting Telegraf
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/influxdata/telegraf/plugins/inputs/cisco_telemetry_gnmi.(*CiscoTelemetryGNMI).handleSubscribeResponse(0xc00068f1e0, 0xc000059941, 0xe, 0xc0001d0be0)
        /opt/src/github.com/influxdata/telegraf/plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go:285 
```
Actually in this case at line 285 of the cisco_telemetry_gnmi.go the aliasPath == key therefor key[len(aliasPath)+1:] failed. 

if len(aliasPath) > 0 {
   key = key[len(aliasPath)+1:]
}

To avoid that I added a second check like that : 

if len(aliasPath) > 0 && len(key) != len(aliasPath) {
   key = key[len(aliasPath)+1:]
}

Could you add this fix ??? 

BR
David

**Comment by danielnelson** [comment]
If the path is fully specified maybe we should use the last component as the field key, in this case `oper_speed`.  I think this gives a better progression as you increase the length of the path:
- path: /state
  - key: port/ethernet/oper_speed
- path: /state/port[port-id=*]
  - key: ethernet/oper_speed
- path: /state/port[port-id=*]/ethernet
  - key: oper_speed
- path: /state/port[port-id=*]/ethernet/oper-speed
  - key: oper_speed

I created #6848 with this strategy (and some test changes), what do you think about this method?

cc @sbyx

**Comment by door7302** [comment]
Hello,

Cool. Your solution is better. 

Thanks. 
David
