### ISSUE TITLE
iDRAC 9 hex encryption Key input location

### ISSUE THREAD

**Issue by safadig** [influxdata/telegraf#6858]
## Feature Request

Dell iDRAC 9 requires Encryption Key entry besides user and password for impi_sensor over LAN. Current plugin documentation only shows user and password? 

### Current behavior:
only user name and password entry example for ipmi_sensor output
### Desired behavior:
include entry example for encryption key
### Use case: 
working command for ipmitools requires -y for the encryption key, for example:
sudo ipmitool -I lanplus -H 192.168.1.1 -U User -P Password -y 000000000000000000000000000000000000000 sdr -v

**Comment by Raynok** [comment]
@danielnelson, also need this feature. I believe it can be a set variable that can be commented or uncommented in the config file (similar to the privilege level variable)

encryption Key = "number"

**Comment by sixxar** [comment]
> @danielnelson, also need this feature. I believe it can be a set variable that can be commented or uncommented in the config file (similar to the privilege level variable)
> 
> encryption Key = "number"

Not working for me in iDrac8
