### ISSUE TITLE
[inputs.vsphere] Deprecate force_discover_on_init

### ISSUE THREAD

**Issue by prydin** [influxdata/telegraf#6860]
### Relevant telegraf.conf:
```toml
force_discover_on_init = false
```

### System info:

Every version to date, every platform

### Steps to reproduce:

1. Set ```force_discover_on_init = false``` in the config file. 

### Expected behavior:

The intended behavior was that a partial metric collection was going to start prior to the first discovery completed.

### Actual behavior:

Several unintended and unpredictable effects. Most of all, the flag was kind of useless, since no metric collection could take place before the first discovery was completed even if it ran in the background. Furthermore, the ```-test``` flag didn't work with the ```force_discover_on_init``` was set to false.

**Comment by danielnelson** [comment]
The plugin may now produce some `did not complete within its interval` warnings on startup, but I plan to have parallel plugin startup implemented before the 1.14 release which will resolve this.
