### ISSUE TITLE
Invitation to the Community: Participate in Telegraf User Research

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/telegraf#6864]
## Research Request

I’m an InfluxData product designer.

I want to personally invite the community to participate in an upcoming user research session about new Telegraf interfaces in [InfluxDB Cloud](https://www.influxdata.com/products/influxdb-cloud/).

As a thank you, we’ll send you a $25 Amazon gift card (or a local option if not available in your country.)

### Schedule your session here

You can see available times a self-select what works for you:
https://calendly.com/influxdata-research/cloud 

Dates & Time: Sessions available January 6-9, 06:00-20:00 PST

### What to expect

- 1 hour Zoom call to walk through design prototypes
- You can ask your questions directly to an engineer and designer
- Get early preview of new features

Looking forward to hearing from you.

**Comment by danielnelson** [comment]
@mnorriswalker Please post this at the [InfluxData Community](https://community.influxdata.com) site, this is where we handle all non bug and feature request discussion.
