### ISSUE TITLE
amqp_consumer, add queue arguments for rabbitmq

### ISSUE THREAD

**Issue by NowWithMarshmallows** [influxdata/telegraf#6866]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add queue_arguments to the queue declarations in the amqp input and output plugins in a similar fashion to exchange_arguments. 

### Current behavior:
There is no option to specify arguments when declaring a queue.

### Desired behavior:
Add the configuration option  queue_arguments = {"key" = "value"}

### Use case: 
RabbitMQ has quite a few options when declaring a queue, including Message TTL, Max Length, Auto-Delete, etc.  I'd like to use the Auto-Delete feature.

**Comment by powersj** [comment]
next steps: look into how to add these arguments to the code and add some tests to this plugin as there are currently zero!

**Comment by massimogallina** [comment]
Hi,
are there any update on this Feature Request? We would need to specify the queue arguments on the amqp_consumer input plugin.
Do we need to build our custom telegraf or this feature will be implemented?

**Comment by massimogallina** [comment]
@srebhan it should be already addressed by this PR: https://github.com/influxdata/telegraf/pull/13496

**Comment by powersj** [comment]
Closing as fixed by #13496. Thanks!
