### ISSUE TITLE
Should allow for different win perf counter intervals

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#6868]
### Proposal:
Should allow for different Windows perf counter input plugin object intervals so we can only send metrics at the velocity we want.
Example: 
```
  [[inputs.win_perf_counters.object]]
    interval= "1m"
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Sent/sec","Bytes Received/sec","Bytes Total/sec","Packets Outbound Errors","Packets Received Errors","Output Queue Length","Current Bandwidth"
    ]
```
### Current behavior:
The Telegraf service fails to start with the error "Windows could not start the Telegraf Data Collector Service service on Local Computer."
### Desired behavior:
Use different intervals for each win perf counter so we don't send more metrics than what we want.
### Use case: 
Say we're collecting 100 counters during each interval.
We probably need CPU metrics more than we need disk space.
So we would want to send CPU metrics every minute and Disk every 15 minutes.

Note: This seems to work on the Linux side when using the standard input plugins, but not with Windows counter objects. 

Thanks in advance!!

**Comment by danielnelson** [comment]
All you need to do is put the `interval` option on the parent table:

```
[[inputs.win_perf_counters]]
  interval = "1m"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Sent/sec"
    ]

[[inputs.win_perf_counters]]
  interval = "20s"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Sent/sec"
    ]
```

Let me know if you need more help.

**Comment by raider111111** [comment]
Hi Daniel,

Thanks for the info! I will go ahead and make the necessary adjustments.
I appreciate your willingness to help!

Have a great day!
