### ISSUE TITLE
input/diskio: merge operations and average time for i/o

### ISSUE THREAD

**Issue by victornet** [influxdata/telegraf#6870]
## Feature Request

I would like to discuss, if there is a way to get any of my changes from https://github.com/influxdata/telegraf/pull/6865 merged.

At first, counters concerning the merge_operations are not existing yet. How about to make these metrics optional available?

Next, regarding read|write_time_avg. First, I totally agree with you @danielnelson .

Under normal circumstances I would use a query, but our tsdb-backend doesn't have this functionality. Furthermore, these metrics are really important for us, to help us analysing and monitoring system and storage performance for our linux servers.

Before I started, I had a look at some other plugins, so aggregated metrics are used in other plugins too, like percentage values in the cpu plugin.

I can understand your concern about storage space. So maybe it would be possible, to make this feature optional too?

Maybe there are other options, but i can't figure out a feasible alternative at this time.
I've checked https://github.com/influxdata/telegraf/issues/6254 or https://github.com/influxdata/telegraf/issues/3709, which is not usable at this time.
Other ideas, like an external helper agent or preprocessing metrics are only bad workarounds for us.

### Proposal:

* Provide counter for merged i/o operations
* Provide calculated metrics for the duration of i/o operations in ms.

### Current behavior:

* Merge operations will not be gathered
* Duration of i/o operations can only be calculated, if the backend supports it.

**Comment by danielnelson** [comment]
Sorry, I overlooked the merged read and merged write counts.  If you will open a pull request for these it shouldn't be a problem to add.

For the calculations, we will want to work them into a processor or aggregator plugin or plugins.  There are a couple ways we could approach this, but the one I'm thinking may be best is a [starlark][] processor I have been experimenting with.  The way this would work is that you would write the calculation as a python function which takes a metric type, and the function would executed in a virtual machine; there would be no shelling out to a python interpreter.  Let me know if this idea seems promising to you.

[starlark]: https://github.com/google/starlark-go/

**Comment by victornet** [comment]
Nevermind, maybe it's my fault. I should have created an issue before my pr as described in CONTRIBUTING.md.

Calculations based on a plugin sounds great. Some open issues are even on my todo list (averaged read time, cpu load / number of cores). Is there anything that i can do to get this on the way?

**Comment by danielnelson** [comment]
The biggest thing I could use help with is answering questions on the [InfluxData Community](https://community.influxdata.com) site and evaluating reported bugs.  In particular, I need to resolve the issues on this list before I can spend much time on features.

- [Bug Short List](https://github.com/influxdata/telegraf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aready+no%3Aassignee+label%3Abug)

If you would like to work on one of these please comment on them so that others know you are looking into them.

I'll let you know when we have something ready on the starlark processor, it would be useful to get some feedback with some real world cases.

**Comment by danielnelson** [comment]
I opened an issue to track the Starlark processor #7194.  I'm going to close this issue since we have merged #6935.
