### ISSUE TITLE
Support non utf-8 encodings in the file input

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#6876]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

The file input should allow processing text files that are not utf-8 encoded.

### Current behavior:

Files with alternative encodings either cannot be parsed or is not encoded properly.

### Desired behavior:

Be able to select a text encoding in the input file, if selected the data will be converted internally to utf-8.
```
[[inputs.file]]
  encoding = "ISO-8859"
```

### Use case: 

https://community.influxdata.com/t/unable-to-rename-fieldname-containing-unicode-character/12293/5

**Comment by kOstovic** [comment]
Having similar issues, my use case is that I need UTF-16

**Comment by danielnelson** [comment]
@kOstovic If I add this for the grok, logfmt, and csv data_format is that sufficient for your use?

**Comment by kOstovic** [comment]
Hi,

We would also like it for json if it is not a problem.
