### ISSUE TITLE
RabbitMQ flow state metric

### ISSUE THREAD

**Issue by oleg-filiutsich** [influxdata/telegraf#6878]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add in rabbitmq metrics for detect [flow state](https://www.rabbitmq.com/flow-control.html) in connections and Queues

### Current behavior:
No the metric

### Desired behavior:
the metric exist

### Use case: 
Need detect it cause the metrics show that rabbit freeze or have bottle necks

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you in the past.

It looks like individual connections, channels, and queues can all be reported to be in a "flow" state based on the link you provided. It does not appear that this is a single metric, but rather a state of various parts and pieces of rabbitmq. Based on the [API docs](https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.9.13/deps/rabbitmq_management/priv/www/api/index.html) I do not see a "flow" or "state" value.

Do you know what other item we should be looking at?

Thanks
