### ISSUE TITLE
Particle.io webhook plugin wrong measurement name 

### ISSUE THREAD

**Issue by pepisp** [influxdata/telegraf#6879]
IMHO webhook plugin writes data to wrong measurement in InfluxDb. Adding 
`{
    "measurement": "your_measurement_name"
}`
have no effect since in plugin code measurement string from json is written to event.database (but what for?):

> type event struct {
> 	Name        string `json:"event"`
> 	Data        data   `json:"data"`
> 	TTL         int    `json:"ttl"`
> 	PublishedAt string `json:"published_at"`
> 	Database    string `json:"measurement"`
> }

After that when submitting data to telegraf with eventHandler () as a measurement name there's event.name which is name of the event which triggered webhook.

As a solution I propose:

> type event struct {
> 	Name        string `json:"event"`
> 	Data        data   `json:"data"`
> 	TTL         int    `json:"ttl"`
> 	PublishedAt string `json:"published_at"`
> 	Measurement    string `json:"measurement"`
> }

and in eventHandler () (line 62): 

> 	rb.acc.AddFields(e.Measurement, e.Data.Fields, e.Data.Tags, pTime)

**Comment by danielnelson** [comment]
Agreed, this behavior is a bit odd and unexpected.  How about we use the measurement name from `measurement` in the JSON, and if that is not set then fall back to the `event`.  I believe this will be backwards compatible enough.

**Comment by pepisp** [comment]
You're right there should be some fallback in case there is no 'measurement' in JSON.
