### ISSUE TITLE
Disk utilisation under a directory plugin

### ISSUE THREAD

**Issue by zoonage** [influxdata/telegraf#6880]
## Feature Request
To be able to record the total size of files under a directory. A single 

### Proposal:
Given a glob path do the following;

1. Parse the output of the `du`
2. Write an equivalent walking through the filesystem and tally up the file sizes

Emit the total size as a metric with a tag for the directory 

### Current behavior:
the filestat plugin can do this for a single file, however not all the files in a directory

### Desired behavior:
Create metrics for the total sizes of the contents of a directory.

### Use case:
Consider a service that spawns processes that each have their own directory, this input would help identify which process was using the most disk space.

**Comment by danielnelson** [comment]
I believe the `filecount` input plugin will do what you want, check it out and let me know if it's not what you had in mind.
