### ISSUE TITLE
Multiple processes with the same name, add counter as tag in win_perf_counters

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#6881]
Hi,
I use Telegraf on Windows, and it appears that multiple instances of Java.exe are only shown as a single java instance despite perfmon having 11 instances of java.exe.  I cannot confirm if that single displayed instance is an average of all the instances or not, but I wondered if you could confirm if you can reproduce this behaviour, and if indeed, it exists in the linux implementation too ?

Thank you for your time and effort on this application, I appreciate it.

**Comment by SimonMcN** [comment]
seems to be a dupe of #1827 is this fixed ?

**Comment by SimonMcN** [comment]
config is 
  [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    IncludeTotal=false

**Comment by SimonMcN** [comment]
Looks like usewildcardexpansion for perfmon counters should be set to true by default but has some unwanted side effects

**Comment by SimonMcN** [comment]
Last point on this, I guess is that if I have 3 instances of something and I close one, and open another, then the instance data could be shuffled around.  Is there anyway to key this to the processID as that will always be unique ?

**Comment by SimonMcN** [comment]
As an aside, is there a reason why the default configuration is not to use wildcard expansion ?  I would have thought logic would be to have it enabled unless you disable it given the standard config of * for instances

**Comment by danielnelson** [comment]
> is there a reason why the default configuration is not to use wildcard expansion

If I recall correctly, primarily to maintain backwards compatibility with respect to counter localization.

> I guess is that if I have 3 instances of something and I close one, and open another, then the instance data could be shuffled around.

If you collect a counter that is unique to the process, in this case you will want `ID Process`, then you can use the converter processor to convert the field to a tag:
```toml
[[processors.converter]]
  namepass = ["win_proc"]
  [processors.converter.fields]
    tag = ["ID_Process"]
```
 
You can group by this tag to see each process independently and this PID will remain constant.

This should work, but it all seems like to much effort to me.  I'd like to keep this issue open and provide a built in method to the plugin for collecting counters as tags.

**Comment by SimonMcN** [comment]
thanks for the response @danielnelson .  I agree with your point.  The ID would be necessary to ensure that the java#3 is the same java#3 that it was before (PID 1001) as opposed to java#3 PID=1003, otherwise the data could easily be polluted making it a liability rather than an asset.  I am a newb so apologies for the abstract nature of my speech but it's almost as if the PID should be the key for the data if such a thing exists within Telegraf.  i.e  we want to search for java#3 where it is PID 1003, not the java#3 where it is pid 1001. 

I appreciate this is a can of worms, and thoroughly horrible but I think we all want our data to have integrity.  Do you think the issue applies to linux proc collection, and if not is there some way to collect the data from windows including the pid but assimilate it using the linux code ?

**Comment by SimonMcN** [comment]
> > is 
> If I recall correctly, primarily to maintain backwards compatibility with respect to counter 
> localization.

Sorry to be a pedant about this but what is more important counter localisation or gathering process data ?  For example if I have 5 copies of chrome running I only get visability of one of them.  Surely this makes the whole process of dubious benefit ? Not only that but svchost, a core part of windows services...

**Comment by danielnelson** [comment]
I don't disagree with your analysis of importance, however we must ensure that when one upgrades Telegraf that the naming doesn't change, as this could break all dashboards and alerting for the user.  Right now we don't have an agreed upon mechanism for making these types of breaking changes short of creating a new plugin, which is something we might do, but would want to include a number of other breaking changes at the same time.  Hope that sheds some light on the current situation.

**Comment by simonmurdock** [comment]
This is also an issue for me where I'm trying to capture details of many w3wp processes on windows and keep them grouped separately by "ID Process"

**Comment by argonym** [comment]
> Last point on this, I guess is that if I have 3 instances of something and I close one, and open another, then the instance data could be shuffled around. Is there anyway to key this to the processID as that will always be unique ?
> ... but it's almost as if the PID should be the key for the data if such a thing exists within Telegraf. i.e we want to search for java#3 where it is PID 1003, not the java#3 where it is pid 1001.

You might want to configure the `ProcessNameFormat` Windows Registry setting so that the PID is included in the instance name:
https://weblogs.asp.net/owscott/registry-change-for-perfmon-and-pid-data
https://blogs.technet.microsoft.com/askperf/2010/03/29/perfmon-identifying-processes-by-pid-instead-of-instance/

**Comment by sspaink** [comment]
Closing as there hasn't been any activity for quiet sometime since the workaround was posted, if this doesn't work for you please comment or reopen so we can discuss another solution.
