### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#6888]
Hi, This is more of a question than a bug.  I think it's a bug but probably a question of perspective.  Your input would be appreciated.

Relevant telegraf.conf:
logfile_rotation_interval = "1d"
logfile_rotation_max_size = "10MB"

Expected behavior:
Logfile would be rotated in the following situations: 
:1 day has elapsed since the file has been modified
:logfile is over 10MB

Actual behavior:
-Logfile grows until 10MB

Cheers
Simon

**Comment by SimonMcN** [comment]
similar to #6183

**Comment by danielnelson** [comment]
This should work like you expect, the first of the two conditions should trigger the rotation, though we still only rotate when the log file is written to as found in #6183.

Is this also due to no writes to the log file, like in #6183, or is the interval based log rotation not working at all?

**Comment by danielnelson** [comment]
Closing but let me know if this is an issue distinct from #6183 and we'll reopen.

**Comment by donalod** [comment]
This is still the case with Telegraf 1.17.2 on OSX. The logfile is currently 3 MB, constantly being written to, and is five days old but only 1 file exists still. The time dimension is not being honored.

```
  logfile_rotation_interval = "1d"
  logfile_rotation_max_size = "10MB"
  logfile_rotation_max_archives = 7
```

# du -h telegraf.log
3.0M	telegraf.log

# GetFileInfo -d telegraf.log
04/14/2021 14:28:44

# date
Mon 19 Apr 2021 22:55:17 IST

# ls -al
total 6216
drwxr-xr-x   6 laptop  staff      192 14 Apr 14:28 .
drwx------+ 18 laptop  staff      576 19 Apr 21:22 ..
-rw-------   1 laptop  staff  2392858 19 Apr 22:55 telegraf.log
