### ISSUE TITLE
Exec input truncated at 80 characters on Windows

### ISSUE THREAD

**Issue by NikolayPolyagoshko** [influxdata/telegraf#6889]
Hi,
I've setup Telegraf to run powershell script, which returns relatively long string in Influx line format. Problem is that exec input gets truncated at 80 chars. I tried to call powershell script from batch file, result is the same.

Running Telegraf 1.13.1 on Windows 7 SP1 32-bit

Here is how it can be reproduced
**Test.ps1**:
```
$TgMsg = "TestReport,Tag1=Tag1Value,Tag2=Tag2Value Measurement1=1i,Measurement2=2i,Measurement3=3i,Measurement4=4i,Measurement5=5i,Measurement6=6i,Measurement7=7i,Measurement8=8i"
$TgMsg
```

**telegraf.conf**:
```
[[inputs.exec]]
  interval="1m"
  
  commands = [
    'powershell -ExecutionPolicy Bypass C:/telegraf/Test.ps1',
  ]
  
  data_format="influx"
```

Error message:
**2020-01-10T11:19:00Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:80: "TestReport,Tag1=Tag1Value,Tag2=Tag2Value Measurement1=1i,Measurement2=2i,Measur"**

**Comment by NikolayPolyagoshko** [comment]
Found a workaround for this. Call Powershell script from inside batch file, and set console buffer width enough to fit string data with **mode** command.
Example batch file:
```
@echo off
mode 1000, 50 > nul
powershell -ExecutionPolicy Bypass C:\telegraf\Test.ps1
```

Could it be integrated into exec input module?

**Comment by danielnelson** [comment]
> Could it be integrated into exec input module?

I don't think we can as the plugin needs to work without cmd or powershell at all.

I read about  this [solution][] that doesn't require using cmd.exe, can you try setting this at the top of your script?
```
$host.UI.RawUI.BufferSize = new-object System.Management.Automation.Host.Size(1024,50)
```

[solution]: https://weblogs.asp.net/soever/powershell-output-capturing-and-text-wrapping-strange-quirks-solved

**Comment by NikolayPolyagoshko** [comment]
Yep, this works as well

**Comment by danielnelson** [comment]
I'm going to document this workaround but not planning any code changes, can you double check #6910 looks okay?
