### ISSUE TITLE
Database for Envrionment

### ISSUE THREAD

**Issue by ajurquhart** [influxdata/telegraf#6892]
I created 3 Databases, DEV, QA and PROD.
I modified outputs.influxdb on a few systems to use the database QA.
After which the Hosts went red from Chronograf and stopped displaying that input was being received.

Service restarts without issue, but hosts are not reporting.

**Comment by danielnelson** [comment]
The best place to ask for troubleshooting help is on the [InfluxData Community](https://community.influxdata.com) site, ask over there and make sure to include your Telegraf configuration.
