### ISSUE TITLE
[[inputs.kibana]] cannot get the correct metrics

### ISSUE THREAD

**Issue by congwensheng** [influxdata/telegraf#6894]
hi, i am use the kibana inputs plugin,this is my configuration:
[[inputs.kibana]]
  servers = ["http://localhost:5601"]
  timeout = "5s"

then,i get the metrics like this:
HELP kibana_concurrent_connections Telegraf collected metric
TYPE kibana_concurrent_connections untyped
kibana_concurrent_connections{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 0
 HELP kibana_heap_max_bytes Telegraf collected metric
 TYPE kibana_heap_max_bytes untyped
kibana_heap_max_bytes{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 0
HELP kibana_heap_used_bytes Telegraf collected metric
TYPE kibana_heap_used_bytes untyped
kibana_heap_used_bytes{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 0
HELP kibana_requests_per_sec Telegraf collected metric
TYPE kibana_requests_per_sec untyped
kibana_requests_per_sec{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 0.2
HELP kibana_response_time_avg_ms Telegraf collected metric
 TYPE kibana_response_time_avg_ms untyped
kibana_response_time_avg_ms{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 2
HELP kibana_response_time_max_ms Telegraf collected metric
TYPE kibana_response_time_max_ms untyped
kibana_response_time_max_ms{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 2
HELP kibana_status_code Telegraf collected metric
TYPE kibana_status_code untyped
kibana_status_code{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 1
HELP kibana_uptime_ms Telegraf collected metric
TYPE kibana_uptime_ms untyped
kibana_uptime_ms{host="mgt01",name="kibana",source="10.150.83.158:5601",status="green",version="6.5.4"} 0

kibana_uptime_ms is always 0,it obvious wrong,kibana_status_code is always 1 even i make the kinana dose not work, another merics like kibana_concurrent_connections,kibana_heap_max_bytes,kibana_heap_used_bytes is always 0, i do not know if it's my probelm ,please to solve the problem.

**Comment by danielnelson** [comment]
Can you attach the output of this command?
```
curl http://localhost:5601/api/status
```

**Comment by congwensheng** [comment]
root@mgt01:~# curl 10.150.83.158:5601/api/status
{"name":"kibana","uuid":"1ac9871a-9c08-46d0-a161-9e9d1f329ab3","version":{"number":"6.5.4","build_hash":"2d4c9c3fd9afd81ded3ac2e686bc1f7204078f14","build_number":18878,"build_snapshot":false},"status":{"overall":{"state":"green","title":"Green","nickname":"Looking good","icon":"success","uiColor":"secondary","since":"2020-01-14T02:12:35.467Z"},"statuses":[{"id":"plugin:kibana@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.467Z"},{"id":"plugin:elasticsearch@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.262Z"},{"id":"plugin:xpack_main@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.301Z"},{"id":"plugin:searchprofiler@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.301Z"},{"id":"plugin:tilemap@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.301Z"},{"id":"plugin:license_management@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.515Z"},{"id":"plugin:index_management@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.302Z"},{"id":"plugin:rollup@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.302Z"},{"id":"plugin:timelion@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.631Z"},{"id":"plugin:graph@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.302Z"},{"id":"plugin:monitoring@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.643Z"},{"id":"plugin:spaces@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:38.067Z"},{"id":"plugin:grokdebugger@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.310Z"},{"id":"plugin:dashboard_mode@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.653Z"},{"id":"plugin:logstash@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.310Z"},{"id":"plugin:beats_management@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.310Z"},{"id":"plugin:console@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.675Z"},{"id":"plugin:console_extensions@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.676Z"},{"id":"plugin:notifications@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.679Z"},{"id":"plugin:metrics@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:35.682Z"},{"id":"plugin:reporting@6.5.4","state":"green","icon":"success","message":"Ready","uiColor":"secondary","since":"2020-01-14T02:12:36.310Z"}]},"metrics":{"last_updated":"2020-01-15T09:40:17.733Z","collection_interval_in_millis":5000,"process":{"memory":{"heap":{"total_in_bytes":181587968,"used_in_bytes":161009032,"size_limit":1501560832},"resident_set_size_in_bytes":286650368},"event_loop_delay":0.5314235687255859,"pid":6,"uptime_in_millis":113273716},"os":{"load":{"1m":2.66015625,"5m":2.8173828125,"15m":2.51025390625},"memory":{"total_in_bytes":404355756032,"free_in_bytes":294494244864,"used_in_bytes":109861511168},"uptime_in_millis":8220745000,"cgroup":{"cpuacct":{"control_group":"/","usage_nanos":1086527218898},"cpu":{"control_group":"/","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}}},"response_times":{"avg_in_millis":103.625,"max_in_millis":693},"requests":{"total":8,"disconnects":0,"status_codes":{"200":7,"304":1}},"concurrent_connections":0}}

**Comment by vikkyomkar** [comment]
@congwensheng / @danielnelson I have raised a PR to address this issue
