### ISSUE TITLE
[[inputs.consul]] the inputs configuration is not right

### ISSUE THREAD

**Issue by congwensheng** [influxdata/telegraf#6895]
hi, i find the configuration of the consul inputs plugin have some problems,
here is the configuration :
[[inputs.consul]]
 address = "localhost"

in fact, it should add the endpoint,like this
[[inputs.consul]]
 address = "localhost:8500"  (or other endpoint)

so that, it can works.

**Comment by danielnelson** [comment]
Fixed in 0693748c35ba33dee3a7154c355de5477a16ac14
