### ISSUE TITLE
metric collection between times

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#6897]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
It would be nice to be able to specify that an input metric should only operate between certain hours or days or combination of the two (ie trading hours).

### Current behavior:
Does not exist
### Desired behavior:
some form of Cron type expression to define start time, end time, and perhaps interval if this is not consistent with existing formatting as an override behaviour ?
ie
cron = */15    07-19        *     * *     /path/script

### Use case: 
eg, collecting stats on metrics that have relevance during trading hours, but outside trading hours you don't want the processor load, or the probability that files could get locked by scripts and not be rotated.

**Comment by Hipska** [comment]
Best solution for this would be to schedule telegraf runs for these inputs by using cron: `*/15 07-19 * * * /bin/telegraf --once --config /etc/telegraf/trading_hours.conf`

Something that might be relevant for this as well is #10545.

**Comment by powersj** [comment]
I'm going to close as 1) cron would be good for this and 2) the collection offset may also aid here.

Thanks!
