### ISSUE TITLE
Reload configuration without downtime

### ISSUE THREAD

**Issue by alvaromorales** [influxdata/telegraf#69]
Are you planning on supporting config reloading? `nginx -s reload` comes to mind.

I'm thinking of a use case where telegraf is monitoring a cluster of servers. Some nodes fail and new ones are added -- the config needs to be updated.

A reload command would happen within the gather interval so metrics would not be dropped.

**Comment by sparrc** [comment]
sounds like a good idea, but not a quick fix!

**Comment by sparrc** [comment]
this is now supported by sending a SIGHUP to the telegraf process

**Comment by chbrown** [comment]
I tried this and `telegraf` dropped/purged/truncated its output buffer. Is there a way to avoid that?

Logs below (obviously, `example.org` wasn't actually what I was using):

    2017/01/08 20:59:20 E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
    2017/01/08 20:59:30 I! Output [influxdb] buffer fullness: 5169 / 10000 metrics. Total gathered metrics: 144342. Total dropped metrics: 9008.
    2017/01/08 20:59:30 E! InfluxDB Output Error: Post https://example.org/write?consistency=&db=telegraf&precision=ns&rp=: dial tcp: lookup example.org: no such host
    2017/01/08 20:59:30 E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster

Then, around here: `pkill -1 telegraf`

    2017/01/08 20:59:32 I! Reloading Telegraf config
    2017/01/08 20:59:32 I! Hang on, flushing any cached metrics before shutdown
    2017/01/08 20:59:32 I! Output [influxdb] buffer fullness: 5169 / 10000 metrics. Total gathered metrics: 144342. Total dropped metrics: 9008.
    2017/01/08 20:59:32 E! InfluxDB Output Error: Post https://example.org/write?consistency=&db=telegraf&precision=ns&rp=: dial tcp: lookup example.org: no such host
    2017/01/08 20:59:32 E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
    2017/01/08 20:59:32 I! Starting Telegraf (version 1.1.2)
    2017/01/08 20:59:32 I! Loaded outputs: influxdb
    2017/01/08 20:59:32 I! Loaded inputs: inputs.system inputs.net inputs.cpu inputs.kernel inputs.processes inputs.disk inputs.mem
    2017/01/08 20:59:32 I! Tags enabled: host=localdev
    2017/01/08 20:59:32 I! Agent Config: Interval:10s, Quiet:false, Hostname:"localdev", Flush Interval:10s
    2017/01/08 20:59:50 I! Output [influxdb] buffer fullness: 63 / 10000 metrics. Total gathered metrics: 63. Total dropped metrics: 0.
    2017/01/08 20:59:50 I! Output [influxdb] wrote batch of 63 metrics in 163.124035ms

Okay, fixed, but... you forgot something, telegraf!

**Comment by danielnelson** [comment]
@chbrown Thats not good, can you open this as a new bug?
