### ISSUE TITLE
Cloudwatch input with AWS/RDS namespace

### ISSUE THREAD

**Issue by s009255** [influxdata/telegraf#6911]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
cloudwatch input with AWS/RDS namspaces, can't collect  **VolumeBytesUsed, VolumeReadIOPs, VolumeWriteIOPs**

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Monitoring.html
As you can see at the URL above, they exist.
Please check this.

### Current behavior:
can't collect VolumeBytesUsed, VolumeReadIOPs, VolumeWriteIOPs

### Desired behavior:
collect olumeBytesUsed, VolumeReadIOPs, VolumeWriteIOPs

**Comment by danielnelson** [comment]
Can you add your configuration for the plugin and run this command using the awscli, making sure to adjust the region:
```
aws cloudwatch list-metrics --namespace AWS/RDS --region us-east-1 --metric-name  VolumeBytesUsed                                                                                                                                                                                                                                                                           
```

**Comment by s009255** [comment]
I can get VolumeBytesUsed with that command.
and i found those metrics are collected 5 minutes interval in cloudwatch.
So, i change my period 1m to 10m and i can collect them.
I'm sorry to bother you, but thank you for your help.
