### ISSUE TITLE
[ethtool] Error - ethtool currently doesn't support more than 1000 entries, received 2479

### ISSUE THREAD

**Issue by mkrug1981** [influxdata/telegraf#6913]
### Relevant telegraf.conf:

```
[[inputs.ethtool]]
#   ## List of interfaces to pull metrics for
interface_include = ["eno1","ens3"]
#
#   ## List of interfaces to ignore when pulling metrics.
#interface_exclude = ["eth1"]
```

### System info:

- Telegraf 1.13.1 (git: HEAD 0c175724)
- CentOS Linux release 7.6.1810 (Core) 
- Network Card "Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]"

### Steps to reproduce:

1. Just enable input plugin "ethtool" on a Mellanox 100Gbps NIC

### Expected behavior:

The ethtool input plugin should be able to cope with the amount of values from a Mellanox NIC 

### Actual behavior:

Telegraf input plugin ethtool is not able to read all values from a Mellanox 100Gbps NIC. It looks like the Cards has 2480 values but plugin has a max value of 1000 entries. See Error below

### Additional info:

```
$ telegraf --config telegraf.conf --input-filter ethtool --test
2020-01-16T10:54:44Z I! Starting Telegraf 1.13.1
2020-01-16T10:54:44Z D! [agent] Initializing plugins
2020-01-16T10:54:44Z E! [inputs.ethtool] Error in plugin: ens3 stats: ethtool currently doesn't support more than 1000 entries, received 2479
```
Count the NIC values provided from ethtool
```
ethtool -S ens3 | wc -l
2480
```

**Comment by danielnelson** [comment]
I opened https://github.com/safchain/ethtool/issues/29 upstream.

**Comment by ykuksenko** [comment]
This was bumped to 4096 in https://github.com/safchain/ethtool/pull/28 - though someone also wanted this to go to 8192.

**Comment by danielnelson** [comment]
Thanks for the update @ykuksenko, I'm going to schedule this for 1.13.3 and I'll merge the latest ethtool once we get a bit closer to the date, in case we get another update.

**Comment by ykuksenko** [comment]
This is now 8192 in https://github.com/safchain/ethtool/pull/30.

**Comment by danielnelson** [comment]
@ykuksenko Added your update to safchain/ethtool for 1.13.4, thanks.
