### ISSUE TITLE
Need "Retention Policy" config for InfluxDb Output

### ISSUE THREAD

**Issue by qindj** [influxdata/telegraf#692]
Dear All

Is there a way to specify RP for InfluxDb output plugin?

I want to use "tagpass" to route some records to specific db and rp.

I knew Kapacitor can achieve it, just wondering if there is a direct way or not.

Thanks & Regards!

**Comment by zstyblik** [comment]
@qindj, I believe this is currently not possible. If I'm not mistaken, writes from all plugins will go to the same InfluxDB DB and default RP for given DB.

**Comment by s1m0** [comment]
+1 Need to be able to specify or override the influx db & rp. In my case, I would like to use exec inputs that would write to different databases with retention policies other than 'default'.
