### ISSUE TITLE
Adds support for zipkin V2

### ISSUE THREAD

**Issue by jcchavezs** [influxdata/telegraf#6924]
## Feature Request

Adds support for ingesting zipkin v2 data

### Proposal:

Adds support for zipkin v2 format and deprecate thrift and json v1 as they are deprecated in zipkin ecosystem (remember, this plugin marks zipkin plugin as experimental)

### Current behavior:

Currently zipkin plugin only supports v1 and thrift, both which are not supported anymore by zipkin community and also the base library does not support them either (see https://github.com/openzipkin-contrib/zipkin-go-opentracing/releases/tag/v0.4.0).

### Use case: 

I want to report zipkin v2 data into telegram, go and PHP instrumentation only supports zipkin v2.

**Comment by jcchavezs** [comment]
I can start on this.

**Comment by danielnelson** [comment]
Thanks, look forward to the update.

cc @jacobmarble

**Comment by alllexandrz** [comment]
Hey Team. Any updates here?

**Comment by sjwang90** [comment]
@jcchavezs Still interested in submitting a PR?
