### ISSUE TITLE
Persist Telegraf Metric Buffer to filesystem

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/telegraf#6925]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
It would be great if we could have the option to persist the metric buffer of telegraf to filesystem instead of memory ( this could be an additional option like a flag or a config) . 
### Current behavior:
Telegraf only stores the metric buffer in memory
### Desired behavior:
Store telegraf metric buffer in filesystem
### Use case: 
This feature would be highly useful for devices which run telegraf which could lose power or crash (and hence reboot) for whatever reason . This will help us to get some vital metrics about the system which would otherwise be lost if stored only in memory. Once the devices comes back up , it can fetch the buffered metrics from file and send it back to the cloud.

**Comment by PWSys** [comment]
+1 This would be great.

**Comment by danielnelson** [comment]
Duplicate #802
