### ISSUE TITLE
ValueCounter description incompatible with COMMON_LOG_FORMAT

### ISSUE THREAD

**Issue by hackery** [influxdata/telegraf#6931]
https://docs.influxdata.com/telegraf/v1.13/plugins/plugin-list/#valuecounter
Telegraf 1.12, InfluxDB 1.7.7

The ValueCounter documentation describes a use case of counting HTTP status code values - but it can't do that using the standard grok patterns like `COMMON_LOG_FORMAT` as they transform `resp_code` (and `verb`) into tags, and ValueCounter can only operate on fields.

**Comment by powersj** [comment]
next steps: the docs linked above need to get updated as tagged values are not going to work with the ValueCounter aggregator.

**Comment by powersj** [comment]
I've filed https://github.com/influxdata/docs-v2/pull/5093 with the docs team to update those notes. Closing this issue.
