### ISSUE TITLE
Document how to read the output value of 'es_cluster_status' metric

### ISSUE THREAD

**Issue by milonjames** [influxdata/telegraf#6933]
We are getting an output of the Elasticsearch cluster health metric as a number, with no labels having key 'color'. In this situation, we are trying to understand how this number output maps to the well-known ES color codes which indicate the cluster health. Pasting below how we are getting the metric displayed in '/metrics' endpoint

\###################################
\# HELP es_cluster_status Cluster status
\# TYPE es_cluster_status gauge
es_cluster_status{cluster="dummy-cluster",} 0.0
\###################################

**Comment by danielnelson** [comment]
The `elasticsearch` plugin prefixes all measurements with `elasticsearch_`, not `es_`, is this metric originating from an external source?

**Comment by milonjames** [comment]
Sorry, I opened this issue by mistake here. This was intended to be on a different repo. I am closing this.
