### ISSUE TITLE
BIND input plugin returns "bind_counter" metrics as Untyped instead of Counter

### ISSUE THREAD

**Issue by kilbasar** [influxdata/telegraf#6934]
### Relevant telegraf.conf:

```toml
[[inputs.bind]]
# list of BIND statistics channels
urls = ["http://localhost:8053/xml/v3"]
```

### System info:
Telegraf built from commit 0732b41b4bbbb883b63ef004d43f627b8689a405
Red Hat 7.6

### Steps to reproduce:
1. Configure the bind input plugin to collect XML v3 metrics from BIND
2. Examine the "bind_counter" metrics which are output from Telegraf

### Expected behavior:
The "bind_counter" metrics provided to the output plugins are of type Counter

### Actual behavior:
The "bind_counter" metrics provided to the output plugins are of type Untyped

### Additional info:
The "bind_memory" metrics are correctly output as Gauges. This is because (in xml_stats_v3.go) they are added using Accumulator.AddGauge(). However, the "bind_counter" metrics are added via a different method, instead using metric.NewSeriesGrouper() to first create a group, and then adding the metrics with Accumulator.AddMetric(). The result is that all "bind_counter" metrics are Untyped.

I tested a modification to the code to not use metric.NewSeriesGrouper() at all, and instead add the "bind_counter" metrics directly using Accumulator.AddCounter(). This resulted in the metrics correctly coming out of Telegraf as Counters. However I'm not sure this is the correct way to fix this problem, as there may be other reasons metric.NewSeriesGrouper() is being used that I am not aware of (performance?). It may also be possible to set a metric type using metric.NewSeriesGrouper(), but I do not see how.

Thanks! Happy to work on a PR once the right implementation strategy has been determined.

**Comment by danielnelson** [comment]
Telegraf doesn't really have metric types outside of some basic support for doing passthrough on Prometheus metrics: prometheus input -> prometheus_client output.  Switching to AddCounter directly will have the side effect of splitting the metric into one field per metric.  In the future, we will likely add per field types, and a more robust set of types, but this is a larger issue due to the increase it would have in memory usage.  For now, expect all metrics produced by Telegraf to be Untyped.

**Comment by kilbasar** [comment]
Thanks for the explanation! For now I'll probably locally fork and modify the BIND input plugin, as our metric collection system cares a lot about the metric type and requires counters to be type Counter in order to fully utilize them.
