### ISSUE TITLE
Allow exclusion of specific annotations and labels from pods in prometheus input plugin

### ISSUE THREAD

**Issue by mchandramouli** [influxdata/telegraf#6938]
### Proposal:
Prometheus input plugin adds all annotations and labels in the pod being scraped to metric tags. It will be nice to allow configuration entries to exclude specific annotations or lables if given. 

Proposal is to add two configuration entries to `[[inputs.prometheus]]` that allows exclusion of specific annotations or tags from the pods being scraped.

```
monitor_kubernetes_pods_exclude_labels: ["some-label-to-exclude"]
monitor_kubernetes_pods_exclude_annotations: ["test.io/some-annotation-to-exclude"]
```

### Current behavior:

All annotations and labels are added as metric tags

### Desired behavior:

Add all annotations and labels as metric tags unless the annotations and label are in an exclusion list

### Use case: 

Custom annotations or labels added (say with high cardinality) are sent to metric store and it causes an explosion of tags. It will be useful to remove them before the metric is processed and sent to the output.

**Comment by mchandramouli** [comment]
Changes are in this fork : https://github.com/influxdata/telegraf/compare/master...mchandramouli:master

**Comment by danielnelson** [comment]
We have a general solution for this, check out the [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) options, in particular the tagpass/tagdrop options.  Closing, but let me know if this doesn't work for you.
