### ISSUE TITLE
Invalid Windows 32bit Installation

### ISSUE THREAD

**Issue by iiidddaaannn102** [influxdata/telegraf#6944]
Hi,

When i Try to Install 32bit telegraf for windows in The Version 13.1 I am Getting an Error That It's an Invalid 32bit Application.
And When i Try 12.1 I can Get it Start on 32bit Simply.

Why this can happen?

Thanks

**Comment by danielnelson** [comment]
Thanks for opening an issue.  I'll need to check this out next week, since I'm out of town and don't have access to a Windows machine.

**Comment by iiidddaaannn102** [comment]
Hi..you can check it please? Its very important to me

**Comment by danielnelson** [comment]
I think this might be #6954, which version of Windows are you running?

**Comment by wnasich** [comment]
Telegraf 1.12.6 is the last version that runs on Windows XP i386
