### ISSUE TITLE
Add Generic Field names to snmp_trap plugin

### ISSUE THREAD

**Issue by iiidddaaannn102** [influxdata/telegraf#6945]
## Feature Request

Add Generic Field names to snmp_trap plugin

I suggest to add an boolean parameter to snmp_trap plugin config or some other idea that makes field names generic, for situations that i didnt know for what field name i expect. 
At my Situations, trap fields are changed from one to other.
For Example:  var1="server",var2="test",var3"="critical"

Thank

**Comment by danielnelson** [comment]
Thanks for opening the issue, but I'm having a hard time understand exactly what is requested.  Can you help by giving an example of the input data, what Telegraf does today, and what you would wish it would do?

**Comment by iiidddaaannn102** [comment]
First of all, thanks for the quick reply.

Today's input in influxdb line protocol:  

snmp_trap,mib=SNMPv2-MIB,name=coldStart,oid=.1.3.6.1.6.3.1.1.5.1,source=192.168.122.102,version=2c **snmpTrapEnterprise.0**="linux"**,sysUpTimeInstance**=1i 1574109187723429814

And I Want This input:
snmp_trap,mib=SNMPv2-MIB,name=coldStart,oid=.1.3.6.1.6.3.1.1.5.1,source=192.168.122.102,version=2c **var1**="linux"**,var2**=1i 1574109187723429814

And You can Configure it:
[[inputs.snmp_trap]]
  ## Transport, local address, and port to listen on.  Transport must
  ## be "udp://".  Omit local address to listen on all interfaces.
  ##   example: "udp://127.0.0.1:1234"
  ##
  ## Special permissions may be required to listen on a port less than
  ## 1024.  See README.md for details
  ##
  # service_address = "udp://:162"
  ## Timeout running snmptranslate command
  # timeout = "5s"
     **generic_field_names = true**

And That Because The plugin Generates From Every Trap a different fields, if i have script that use the data, i don't know what fields i have in influxdb to query it.

Thanks!

**Comment by danielnelson** [comment]
I understand now, but it isn't something we would add since it doesn't match our best practices for schema design and additionally you would have issues with type conflicts when inserting into InfluxDB.

One solution your could look into is using [Flux](https://docs.influxdata.com/flux/v0.50/) to query, it will pull down the field name and the field value as separate columns, which can be easier to work with generically.
