### ISSUE TITLE
Update README.md with processor and aggregator filter options

### ISSUE THREAD

**Issue by R290** [influxdata/telegraf#6947]
### Proposal:

Update README.md so the generated config only has the selected plugins and actually is compact.

#### Generate config with only cpu input & influxdb output plugins defined:

```
telegraf --input-filter cpu --output-filter influxdb config
```

#### Generate config with only cpu input & influxdb output plugins defined:

```
telegraf --input-filter cpu --output-filter influxdb --processor-filter none --aggregator-filter none config
```

### Use case: 

Do not overwhelm new users?

**Comment by danielnelson** [comment]
Thanks for the suggestion, I updated the command with a slightly different form:
```
telegraf --section-filter agent:inputs:outputs --input-filter cpu --output-filter influxdb config
```

8792a5fd5ebe7f8e48d9f8cc1ce4a95a67a12314
