### ISSUE TITLE
Prometheus scrape metrics from pods on same node 

### ISSUE THREAD

**Issue by mg03** [influxdata/telegraf#6950]
## Feature Request

Currently, when we deploy telegraf as a daemonset in kubernetes, each telegraf pod scrapes metrics from all target pods on all nodes. 
Issue/s arising with this:
1) it creates duplicate metrics 

### Proposal:
Create a config parameter called 'kubernetes_node', the existence of which will trigger a filter based on the pods Spec.NodeName. If the pods Spec.NodeName matched the config parameter, then registerPod for scraping else disregard the pod.

### Current behavior:
Telegraf pod scrapes all pods and creates duplicate metrics if more than one telegraf pod id deployed.
### Desired behavior:
When the proposed/new config parameter (kubernetes_node) is provided, Telegraf pod should only concern itself with scraping metrics from pods on the same node that it is situated on.
I have this working and can submit a PR, let me know.

### Use case: 
Currently, when we deploy telegraf as a daemonset in kubernetes, each telegraf pod scrapes metrics from all target pods on all nodes. If we can go ahead with this proposal then we can de-duplicate metrics at source and reduce burden on infrastructure.

**Comment by russorat** [comment]
@mg03 thanks for opening this and for the PR!

Usually, we see the prometheus input used when there is a single instance of Telegraf running in a cluster which handles the scraping. When running telegraf as a daemonset, we usually see people use the Kubernetes input to get pod level stats. 

Is there a specific reason you don't want to run a single telegraf to handle the scraping?  

@rawkode do you have any thoughts here?

**Comment by bamvenkatesh** [comment]
@mg03 - Hi, I was just curious why choose DaemonSet instead of a deployment for Telegraf. 

Like @russorat asked, Is there a specific reason you don't want to run a single telegraf to handle the scraping?

**Comment by russorat** [comment]
I recommend you take a look at the telegraf operator https://github.com/influxdata/telegraf-operator as well as the helm charts for deploying telegraf: https://github.com/influxdata/helm-charts
