### ISSUE TITLE
 [inputs.sysstat] Failed to remove tmp file after ... ON CENTOS 7

### ISSUE THREAD

**Issue by tlsalex** [influxdata/telegraf#6953]
I saw similar problem in history issues ,which just require to add 
  sadc_path = "/usr/lib/sa/sadc" # required but not fix my case

### Relevant telegraf.conf:
[[inputs.sysstat]]
  sadc_path = "/usr/lib64/sa/sadc" # required
  activities = ["DISK", "SNMP", "INT"]
  group = true
  [inputs.sysstat.options]
	-C = "cpu"
	-B = "paging"
	-b = "io"
	-d = "disk"             # requires DISK activity
	-H = "hugepages"
	"-I ALL" = "interrupts" # requires INT activity
	"-n ALL" = "network"
	"-P ALL" = "per_cpu"
	-q = "queue"
	-R = "mem"
	"-r ALL" = "mem_util"
	-S = "swap_util"
	-u = "cpu_util"
	-v = "inode"
	-W = "swap"
	-w = "task"
  [[inputs.sysstat.device_tags.sda]]
    vg = "rootvg"
```toml

```

### System info:

[root@hob telegraf]# rpm -q telegraf
telegraf-1.13.2-1.x86_64
[root@hob telegraf]# uname -r
3.10.0-957.el7.x86_64
[root@hob telegraf]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

### Steps to reproduce:

1. ...telegraf -config telegraf.conf -test
2. ...telegraf --config telegraf.conf --input-filter sysstat --test 

### Expected behavior:

$ telegraf --config telegraf.conf --input-filter sysstat --test
* Plugin: sysstat, Collection 1
> cpu_util,device=all pct_idle=98.85,pct_iowait=0,pct_nice=0.38,pct_steal=0,pct_system=0.64,pct_user=0.13 1459255626657883725
> swap pswpin_per_s=0,pswpout_per_s=0 1459255626658387650
........
### Actual behavior:

[root@hob telegraf]# telegraf -config telegraf.conf -test
2020-01-29T23:03:31Z I! Starting Telegraf 1.13.2
2020-01-29T23:03:31Z E! [inputs.sysstat] Failed to remove tmp file after "/usr/lib64/sa/sadc -S DISK -S SNMP -S INT 1 2 /tmp/sysstat-1580339011" command: remove /tmp/sysstat-1580339011: no such file or directory
2020-01-29T23:03:31Z E! [inputs.sysstat] Error in plugin: failed to run command /usr/lib64/sa/sadc -S DISK -S SNMP -S INT 1 2 /tmp/sysstat-1580339011: fork/exec /usr/lib64/sa/sadc: no such file or directory -
2020-01-29T23:03:31Z E! [telegraf] Error running agent: One or more input plugins had an error

**Comment by tlsalex** [comment]
Sorry ,I made a mistake ,the path of sadc should be : /usr/local/lib64/sa/sadc 
in centos.
But I still met problem when running a test.
error code :
2020-01-31T15:49:24Z E! [inputs.sysstat] Error in plugin: command /usr/local/bin/sadf -p -- -p -R /tmp/sysstat-1580485763 failed with exit status 1

Parameter is not correct ? I did not find -R in sadc or sar

**Comment by tlsalex** [comment]
OK ,I solve it by remove -R option

**Comment by FlorentLM** [comment]
Having the exact same problem on Debian (with the correct sadc path), can't seem to find a fix.

**Comment by danielnelson** [comment]
related #7701

**Comment by Dhongwei** [comment]
> Having the exact same problem on Debian (with the correct sadc path), can't seem to find a fix.

Brother, has the problem been solved
