### ISSUE TITLE
not a valid 32 bit application

### ISSUE THREAD

**Issue by pgferro** [influxdata/telegraf#6954]
### System info:
Windows Server 2008 Enterprise x86
Telegraf x86 13.2

### Steps to reproduce:
run telegraf.exe --service install as powershell admin
run telegraf.exe --config telegraf.conf as powershell admin

### Actual behavior:
![Cattura](https://user-images.githubusercontent.com/14185233/73419742-40551e00-4331-11ea-8da0-290fb27b1dd7.PNG)

**Comment by danielnelson** [comment]
It seems that the Go compiler dropped support for Windows Server 2008 (based on Vista) in Go 1.11.  This would make Telegraf 1.8 the last version that can be ran from the official binary packages.  It should be possible to compile using Go 1.10 from the Telegraf `1.12.6` tag.

**Comment by danielnelson** [comment]
It may be possible to use Telegraf 1.12 on Windows 2008.  That version was compiled with Go 1.12 and without CGO.

https://golang.org/doc/go1.13#windows
