### ISSUE TITLE
personalice tag in ipmi_sensor plugin

### ISSUE THREAD

**Issue by ragonlan** [influxdata/telegraf#6956]
## Feature Request in ipmi_sensor plugin

It would be nice this plugin could add extra tags to ipmi_sensor metric like location or host alias when you add several ipmi servers.

### Proposal:
It could be something like:
tag.floor = 1
tag.rack = 23
tag.alias = "pocoyo"

**Comment by russorat** [comment]
@ragonlan thanks for opening this! is this something you could use the `tags` option for on the input plugins? https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins
