### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ronnocol** [influxdata/telegraf#6958]
It's been a while since I tried to build telegraf, so I pulled latest master... but I can not get it to build on my Linux box. 

loconnor@tarpon:~/projects/go/src/github.com/influxdata/telegraf$ echo $GOPATH 
/home/loconnor/projects/go
loconnor@tarpon:~/projects/go/src/github.com/influxdata/telegraf$ make
go mod download
warning: pattern "all" matched no module dependencies
go build -ldflags " -X main.commit=ede9bc52 -X main.branch=master" ./cmd/telegraf
plugins/inputs/infiniband/infiniband_linux.go:7:2: cannot find package "github.com/Mellanox/rdmamap" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/Mellanox/rdmamap (vendor tree)
        /usr/lib/go-1.12/src/github.com/Mellanox/rdmamap (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/Mellanox/rdmamap (from $GOPATH)
plugins/inputs/modbus/modbus.go:11:2: cannot find package "github.com/goburrow/modbus" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/goburrow/modbus (vendor tree)
        /usr/lib/go-1.12/src/github.com/goburrow/modbus (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/goburrow/modbus (from $GOPATH)
plugins/inputs/syslog/syslog.go:15:2: cannot find package "github.com/influxdata/go-syslog/v2" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/go-syslog/v2 (vendor tree)
        /usr/lib/go-1.12/src/github.com/influxdata/go-syslog/v2 (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/influxdata/go-syslog/v2 (from $GOPATH)
plugins/inputs/syslog/syslog.go:16:2: cannot find package "github.com/influxdata/go-syslog/v2/nontransparent" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/go-syslog/v2/nontransparent (vendor tree)
        /usr/lib/go-1.12/src/github.com/influxdata/go-syslog/v2/nontransparent (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/influxdata/go-syslog/v2/nontransparent (from $GOPATH)
plugins/inputs/syslog/syslog.go:17:2: cannot find package "github.com/influxdata/go-syslog/v2/octetcounting" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/go-syslog/v2/octetcounting (vendor tree)
        /usr/lib/go-1.12/src/github.com/influxdata/go-syslog/v2/octetcounting (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/influxdata/go-syslog/v2/octetcounting (from $GOPATH)
plugins/inputs/syslog/syslog.go:18:2: cannot find package "github.com/influxdata/go-syslog/v2/rfc5424" in any of:
        /home/loconnor/projects/go/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/go-syslog/v2/rfc5424 (vendor tree)
        /usr/lib/go-1.12/src/github.com/influxdata/go-syslog/v2/rfc5424 (from $GOROOT)
        /home/loconnor/projects/go/src/github.com/influxdata/go-syslog/v2/rfc5424 (from $GOPATH)
make[1]: *** [Makefile:39: telegraf] Error 1
make: *** [Makefile:31: all] Error 2
loconnor@tarpon:~/projects/go/src/github.com/influxdata/telegraf$

**Comment by danielnelson** [comment]
If you are building with Go 1.12 (not 1.13) and you are building in the GOPATH, you need to set this environment variable:
```
export GO111MODULE=on
```

Probably what you will want to do when you have time is to move away from building inside the GOPATH, maybe cloning the telegraf repo to `~/projects/telegraf`.
