### ISSUE TITLE
Can't get inputs.disk data with linux debian grsec kernel

### ISSUE THREAD

**Issue by Sejong42** [influxdata/telegraf#6962]
I'm wondering which solution would be the best to resolve this issue. The inputs.disk plugin doesn't give me any data because the telegraf user is blocked by grsec :

E! [inputs.disk] Error in plugin: error getting disk usage info: readlink /sys/dev/block/8:1: permission denied

Running telegraf as root would be a solution but it's clearly not recommended. And I can't change the kernel on that dedicated server.
How can I solve this issue elegantly ?

**Comment by danielnelson** [comment]
Does anyone besides root have permission to read these links?  Can you show the output of
```
ls -l /sys/dev/block/
```

**Comment by Sejong42** [comment]
# ls -l /sys/dev/block
total 0
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:0 -> ../../devices/virtual/block/ram0
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:1 -> ../../devices/virtual/block/ram1
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:10 -> ../../devices/virtual/block/ram10
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:11 -> ../../devices/virtual/block/ram11
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:12 -> ../../devices/virtual/block/ram12
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:13 -> ../../devices/virtual/block/ram13
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:14 -> ../../devices/virtual/block/ram14
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:15 -> ../../devices/virtual/block/ram15
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:2 -> ../../devices/virtual/block/ram2
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:3 -> ../../devices/virtual/block/ram3
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:4 -> ../../devices/virtual/block/ram4
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:5 -> ../../devices/virtual/block/ram5
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:6 -> ../../devices/virtual/block/ram6
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:7 -> ../../devices/virtual/block/ram7
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:8 -> ../../devices/virtual/block/ram8
lrwxrwxrwx 1 root root 0 Jan 31 22:12 1:9 -> ../../devices/virtual/block/ram9
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:0 -> ../../devices/virtual/block/nbd0
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:1 -> ../../devices/virtual/block/nbd1
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:10 -> ../../devices/virtual/block/nbd10
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:11 -> ../../devices/virtual/block/nbd11
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:12 -> ../../devices/virtual/block/nbd12
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:13 -> ../../devices/virtual/block/nbd13
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:14 -> ../../devices/virtual/block/nbd14
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:15 -> ../../devices/virtual/block/nbd15
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:2 -> ../../devices/virtual/block/nbd2
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:3 -> ../../devices/virtual/block/nbd3
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:4 -> ../../devices/virtual/block/nbd4
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:5 -> ../../devices/virtual/block/nbd5
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:6 -> ../../devices/virtual/block/nbd6
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:7 -> ../../devices/virtual/block/nbd7
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:8 -> ../../devices/virtual/block/nbd8
lrwxrwxrwx 1 root root 0 Jan 31 22:12 43:9 -> ../../devices/virtual/block/nbd9
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:0 -> ../../devices/virtual/block/loop0
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:1 -> ../../devices/virtual/block/loop1
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:2 -> ../../devices/virtual/block/loop2
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:3 -> ../../devices/virtual/block/loop3
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:4 -> ../../devices/virtual/block/loop4
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:5 -> ../../devices/virtual/block/loop5
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:6 -> ../../devices/virtual/block/loop6
lrwxrwxrwx 1 root root 0 Jan 31 22:12 7:7 -> ../../devices/virtual/block/loop7
lrwxrwxrwx 1 root root 0 Jan 31 22:12 8:0 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx 1 root root 0 Jan 31 15:29 8:1 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
lrwxrwxrwx 1 root root 0 Jan 31 22:12 8:2 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda2
lrwxrwxrwx 1 root root 0 Jan 31 22:12 8:3 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda3
lrwxrwxrwx 1 root root 0 Jan 31 22:12 9:0 -> ../../devices/virtual/block/md0


I was also thinking of creating a specific group for those file, but because of the nature of those files, I'm not sure if it's a good idea.

**Comment by danielnelson** [comment]
I don't know much about grsec, but I believe you need to modify or add an ACL to give the `telegraf` binary access to this location.
