### ISSUE TITLE
Add new metrics for RabbitMQ plugin

### ISSUE THREAD

**Issue by byjg** [influxdata/telegraf#6963]
## Feature Request

I would like to add new metrics for RabbitMQ plugin

### Proposal:

Add the metrics 
* slave_nodes_len
* synchronised_slave_nodes_len

These metrics by default return a string list with the name of the nodes, however we can extract the length of these list and push it. 

### Current behavior:

The metrics proposed don't exist. 

### Desired behavior:

Return these metrics as the number of items in the list. 

### Use case: 

When a message is out of sync we get the value "NaN" in the metric "messages" from the rabbitmq api. However it is not handled well in telegraf. The idea here is know that a queue is out of sync by analyzing the values returned by the proposed metrics: `slave_nodes_len` and `synchronised_slave_nodes_len`

If the idea makes sense for telegraf I already implemented it and I can open a PR.

**Comment by danielnelson** [comment]
Yes, would love to see a pull request.  I to fit in best we would probably leave the _len suffix off: `slave_nodes=42i` or `slave_node_count=42i`

**Comment by byjg** [comment]
Thank you :)
