### ISSUE TITLE
Jenkins plugin doesn't collect all builds for a job

### ISSUE THREAD

**Issue by mildebrandt** [influxdata/telegraf#6966]
The plugin only collects the metrics of builds that have finished. That's fine, but it also only collects the metrics of the last build to run within a job. So if there is a new build that starts before the previous has finished, the metrics of the previous build will not be collected.

### System info:
telegraf 1.13.2 Docker image

### Steps to reproduce:
1. Configure Jenkins plugin
2. Run two concurrent builds in Jenkins

### Expected behavior:
Both builds will be recorded. Even better, I want all builds within the `max_build_age` setting of the conf file to be recorded.

### Actual behavior:
Only the last build to finish will be recorded.

**Comment by russorat** [comment]
@mildebrandt thanks for the issue and the pr! We will review and consider it for a future release. In the meantime, it would be great of some other jenkins users could test it out and make sure it works for them.
