### ISSUE TITLE
XML parser

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#6968]
## Feature Request
I would like to contribute to the Telegraf as an xml parser for input plugins.
Please rate the [proposed solution](https://github.com/M0rdecay/telegraf/tree/xml_parser/plugins/parsers/xml) and let it know if it suits you.
If you make a positive decision, I will prepare unit tests for this plugin.

This should close issue [1758](https://github.com/influxdata/telegraf/issues/1758)

Waiting for your feedback!

**Comment by M0rdecay** [comment]
Friends, do I expect an answer from you?

**Comment by danielnelson** [comment]
@M0rdecay Thanks for the link, unfortunately due to time constraints I don't have time to evaluate the parser right now, I'll have to take a look later.

**Comment by M0rdecay** [comment]
Thanks for the answer! Of course, I will wait for your decision. If you find the code inappropriate, please indicate the shortcomings.

**Comment by M0rdecay** [comment]
@danielnelson, hello! Have you already seen the proposed solution? We waiting for your decision.

**Comment by M0rdecay** [comment]
@danielnelson? :(

If in the current state the parser looks poorly written or poorly functional, please let us know what you would like to see in the solution.

I will explain why this is important for us - in the current form, the parser covers our needs, but we are not ready to use it in a productive environment so as not to branch off from you. We would prefer to improve the proposed solution to meet the required level.

**Comment by sjwang90** [comment]
Hi @M0rdecay, sorry for the delay but we're  pretty backlogged with the new features for the upcoming Telegraf release.  We'll definitely take a look at your proposed solution soon.

**Comment by cmakaloclifford** [comment]
All respect for you guys being backed up with lots of other stuff to do.
Just wanted to add a vote for this feature. We would really like to have a plugin for parsing XML outputs from our Wowza servers, so I hope we could see that implemented some time soon. :)

**Comment by M0rdecay** [comment]
Comrades, we are waiting for your assessment.
It seems that this functionality can be useful not only to me, but also to other users.

**Comment by yurividal** [comment]
Any updates on this? I really need this feature.

**Comment by M0rdecay** [comment]
@yurividal hello!

I need your vote here - https://github.com/influxdata/telegraf/pull/8121/ and here - https://influxcommunity.slack.com/archives/CH99HUH8V/p1601645481073800

We want to show that people need an XML parser.

**Comment by sjwang90** [comment]
@M0rdecay Would it be possible to close this issue in preference for #1758? Unless there's anything different in this issue, there's more historical conversation in the other issue and I don't want your PRs to get missed in this newer issue.

**Comment by M0rdecay** [comment]
@sjwang90 Yes, let's close this one. Thanks for the help!
