### ISSUE TITLE
Set the measurement name to a tag value

### ISSUE THREAD

**Issue by JollyJosy** [influxdata/telegraf#6970]
## Feature Request

telegraf to set the measurement name equal to the filename if file input is used

### Proposal:

it would be helpful if the input parameter "name_override" have a "filename" argument.
Similar to the "file_tag"parameter of the file input plugin.

### Current behavior:

The "name_override" allows to override the measurement name with a static name.

### Desired behavior:

The "name_override" allows to override the measurement name with the filename of the file used as the input.

### Use case: 

I have multiple servers producing measurements. Each type of measurement (including different fields) is having it's own filename.
When the filename can be used as measurement name it would allow for a single input section per server using the wildcard for the filenames.

**Comment by danielnelson** [comment]
Usually the data is more flexibly queried if you use fewer measurement name, so I do recommend using the tag to store the file name, and setting the measurement to a value that describes the particular shape of data.  Generally this means that each plugin definition has a single name which works out with `name_override`.

However, we could add the ability for the `converter` processor to convert a tag/field value to the measurement name.

**Comment by mvgoylen** [comment]
Having this possibility in the converter processor would be also a good solution for the problem . 
thanks already for this fast feedback.

**Comment by DiddleDaddle** [comment]
Any idea when this could be added to the converter processor? This would really be a big help and avoid using external scripting to treat the files.

**Comment by danielnelson** [comment]
@JollyJosy Will be in the upcoming 1.14 release and the next nightly build.
