### ISSUE TITLE
Include Lock:Timeout (timeout > 0) Event Class in sqlserver input

### ISSUE THREAD

**Issue by sawo1337** [influxdata/telegraf#6978]
## Feature Request

The current metric only shows Lock Timeouts/sec, which includes internal lock probes that may not be a problem at all. In a live environment, you may get 100s of lock timeouts/sec, but actually no lock timeouts that are longer than 0.

### Proposal:
Add Lock Timeouts (timeout > 0)/sec to the sqlserver_performance metric
### Current behavior:
Only Lock Timeouts/sec is being gathered
### Desired behavior:
Add Lock Timeouts (timeout > 0)/sec to the sqlserver_performance metric
### Use case: 
If you want to only see locks that are actually causing issues, it is better to skip locks where the timeout is 0. From MSDN:
![image](https://user-images.githubusercontent.com/31248804/73749105-616ba380-4763-11ea-818f-b6ef6851d520.png)
[MSDN Article](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/lock-timeout-timeout-0-event-class?redirectedfrom=MSDN&view=sql-server-ver15)

**Comment by danielnelson** [comment]
Seems like a good idea to me, what do you think @denzilribeiro?

**Comment by denzilribeiro** [comment]
What we have is just a perf counter in which Lock timeout/sec is a rate counter you cannot just ignore /exclude values. Look at the cntr_type  column in sys.dm_os_performance_counters
To use waitstats analysis or waits on LCK to troubleshoot any lock related issue/s. I am not totally sure if you are proposing adding XEvent class? that is more tracing not monitoring.

**Comment by sawo1337** [comment]
There is a separate counter that is actually named "Lock Timeouts (timeout > 0)/sec" - it is available by default, it is just a matter of including it as it gives much more realistic values.

**Comment by denzilribeiro** [comment]
That is totally fine to replace this one with that .

**Comment by sawo1337** [comment]
Exactly, here is an output from production server with pretty light load:
![image](https://user-images.githubusercontent.com/31248804/73786666-6a2f9a00-47a2-11ea-903d-2853e1f2daff.png)

Lock timeouts is giving pretty crazy values due to internal locks, but the actual locks with wait over 0 is giving some reasonable output. This is why Microsoft suggests watching Lock Timeouts (timeout > 0)/sec instead.

**Comment by sawo1337** [comment]
Proposed change in sqlserver.go:
line 639:
`'Lock Timeouts/sec',`
becomes:
`'Lock Timeouts (timeout > 0)/sec,`
Or add this as an additional counter on line 640 and keep the existing counter at line 639

**Comment by danielnelson** [comment]
@sawo1337 Can you open a pull request with both counters?
