### ISSUE TITLE
sqlserver input exclude_query config option may be confusing

### ISSUE THREAD

**Issue by TiagoMHCSantana** [influxdata/telegraf#6979]
## Feature Request
Excluding what you do not want instead of including what you do want to monitor may get confusing, specially when you just need a few measurements.

### Proposal:
Deprecate exclude_query configuration option and include a new one to indicate which query metrics one wants to run.

### Current behavior:
It is necessary to explicitly state which queries one does not want to be executed when the sqlserver plugin is enabled.

### Desired behavior:
None query is executed unless explicitly stated to do so in the config file.

### Use case: 
Supose that I only want to keep track of database IO every 30s and wait stats every 60s. The config file would look something like this:

> [[inputs.sqlserver]]
  interval = "30s"
  servers = [
	"Server=server;Port=port;User Id=telegraf;Password=password;app name=telegraf;log=1;",
  ]
>  \#
>  \## Optional parameter, setting this to two will use a new version
>  \## of the collection queries that break compatibility with the original
>  \## dashboards. 
>  query_version = 2
>  \## If you are using AzureDB, setting this to True will gather resource utilization metrics
>  \# azuredb = False
>  \## If you would like to exclude some of the metrics queries, list them here
>  \## Possible choices:
>  \## - PerformanceCounters
>  \## - WaitStatsCategorized
>  \## - DatabaseIO
>  \## - DatabaseProperties
>  \## - CPUHistory
>  \## - DatabaseSize
>  \## - DatabaseStats
>  \## - MemoryClerk
>  \## - VolumeSpace
>  \## - Schedulers
>  \## - AzureDBResourceStats
>  \## - AzureDBResourceGovernance
>  \## - SqlRequests
>  \## - ServerProperties
>  **exclude_query = [ 'PerformanceCounters', 'WaitStatsCategorized', 'DatabaseProperties', 'CPUHistory', 'DatabaseSize', 'DatabaseStats', 'MemoryClerk', 'VolumeSpace', 'VolumeSpace', 'Schedulers', 'AzureDBResourceStats', 'AzureDBResourceGovernance', 'SqlRequests', 'ServerProperties' ]**
>  [[inputs.sqlserver]]
  interval = "60s"
  servers = [
	"Server=server;Port=port;User Id=telegraf;Password=password;app name=telegraf;log=1;",
  ]
>  \#
>  \## Optional parameter, setting this to two will use a new version
>  \## of the collection queries that break compatibility with the original
>  \## dashboards. 
>  query_version = 2
>  \## If you are using AzureDB, setting this to True will gather resource utilization metrics
>  \# azuredb = False
>  \## If you would like to exclude some of the metrics queries, list them here
>  \## Possible choices:
>  \## - PerformanceCounters
>  \## - WaitStatsCategorized
>  \## - DatabaseIO
>  \## - DatabaseProperties
>  \## - CPUHistory
>  \## - DatabaseSize
>  \## - DatabaseStats
>  \## - MemoryClerk
>  \## - VolumeSpace
>  \## - Schedulers
>  \## - AzureDBResourceStats
>  \## - AzureDBResourceGovernance
>  \## - SqlRequests
>  \## - ServerProperties
>  **exclude_query = [ 'PerformanceCounters', 'DatabaseIO', 'DatabaseProperties', 'CPUHistory', 'DatabaseSize', 'DatabaseStats', 'MemoryClerk', 'VolumeSpace', 'VolumeSpace', 'Schedulers', 'AzureDBResourceStats', 'AzureDBResourceGovernance', 'SqlRequests', 'ServerProperties' ]**

It is not clear what I wanted to monitor at all. Instead, it would be a lot clearer if the config file read like this: 

>  [[inputs.sqlserver]]
  interval = "30s"
  servers = [
	"Server=server;Port=port;User Id=telegraf;Password=password;app name=telegraf;log=1;",
  ]
>  \#
>  \## Optional parameter, setting this to two will use a new version
>  \## of the collection queries that break compatibility with the original
>  \## dashboards. 
>  query_version = 2
>  \## If you are using AzureDB, setting this to True will gather resource utilization metrics
>  \# azuredb = False
>  \## Metrics queries
>  \## Possible choices:
>  \## - PerformanceCounters
>  \## - WaitStatsCategorized
>  \## - DatabaseIO
>  \## - DatabaseProperties
>  \## - CPUHistory
>  \## - DatabaseSize
>  \## - DatabaseStats
>  \## - MemoryClerk
>  \## - VolumeSpace
>  \## - Schedulers
>  \## - AzureDBResourceStats
>  \## - AzureDBResourceGovernance
>  \## - SqlRequests
>  \## - ServerProperties
>  **metrics_queries = [ 'DatabaseIO' ]**
>  [[inputs.sqlserver]]
  interval = "60s"
  servers = [
	"Server=server;Port=port;User Id=telegraf;Password=password;app name=telegraf;log=1;",
  ]
>  \#
>  \## Optional parameter, setting this to two will use a new version
>  \## of the collection queries that break compatibility with the original
>  \## dashboards. 
>  query_version = 2
>  \## If you are using AzureDB, setting this to True will gather resource utilization metrics
>  \# azuredb = False
>  \## Metrics queries
>  \## Possible choices:
>  \## - PerformanceCounters
>  \## - WaitStatsCategorized
>  \## - DatabaseIO
>  \## - DatabaseProperties
>  \## - CPUHistory
>  \## - DatabaseSize
>  \## - DatabaseStats
>  \## - MemoryClerk
>  \## - VolumeSpace
>  \## - Schedulers
>  \## - AzureDBResourceStats
>  \## - AzureDBResourceGovernance
>  \## - SqlRequests
>  \## - ServerProperties
>  **metrics_queries = [ 'WaitStatsCategorized' ]**

**Comment by danielnelson** [comment]
Agreed, but I think what would be most expected in Telegraf would be a include/exclude option pair, similar to the namepass/namedrop or as seen in vSphere, Docker, etc plugins.
```toml
query_include = ["WaitStatsCategorized"]
query_exclude = []
```

**Comment by TiagoMHCSantana** [comment]
It sounds even better. I went to check it out and it really makes more sense. I think the logic should be exactly the same as namepass/namedrop: first process query_include, if it exists, and then filter the metrics using query_exclude. What do you think @danielnelson ?

**Comment by HarshitOnGitHub** [comment]
@danielnelson @TiagoMHCSantana  I would like to pick this up, if it is available.
The approach I am thinking of taking is:
* Introduce a new config parameter `include_query`.
* If `include_query` is not specified then the behavior would be to include all the queries like before to maintain backward compatibility.
* The behavior of `exclude_query` will act as the final exclusion filter just like before.

**Comment by HarshitOnGitHub** [comment]
Have opened a PR for this: https://github.com/influxdata/telegraf/pull/7150
