### ISSUE TITLE
Add support to telegraf collector

### ISSUE THREAD

**Issue by menardorama** [influxdata/telegraf#698]
Hi,

In a case of a segmented network it could be great to permit telegraf to act as collector.

Instead of deploying a big machine gun with an MQ could it be possible to have an input plugin that accept telegraf traffic and just route it to influxdb ?

**Comment by sparrc** [comment]
do you mean support for telegraf to act as a tcp or udp listenter? see #638

**Comment by menardorama** [comment]
The thing is that i don't want to alter the hostname, tags.... does this will work line that ?

**Comment by sparrc** [comment]
You mean line protocol? You just want it to directly parse it, correct?

**Comment by menardorama** [comment]
Basically it's to replace a ganglia that offer a collector feature on gmond. So i would say that one telegraf node receive metrics from others telegraf host (trough tcp I guess) and just route it without any modification to the rught output (in my case influxdb). If the tcp input plugin does the job it's jist perfect.

**Comment by sparrc** [comment]
yes, this is the purpose of the tcp/udp listener PR, I believe the author of that PR is on vacation for the Chinese New Year, but when he's back I will work to get that merged

**Comment by menardorama** [comment]
Excellent news thanks.
