### ISSUE TITLE
NFS mount point details are showing wrong 

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6989]
HI Team,

telegraf showing wrong data for NFS mountpoint, so please let me know telegraf support NFS mount point ?

Filesystem                         Size  Used Avail Use% Mounted on
@@@@@@@@tempdir_wes   513G  384K  513G   1% /tempdir_west
@@@@@@@@west_hub1      3.9T  352K  3.8T   1% /west_hub1
@@@@@@@@_west_hub2      6.4T  352K  6.3T   1% /west_hub2

> disk,IP=10.5.131.75,LOB=Archival-Prepaid,application_name=Archival-Prepaid,device=10.5.75.16:/prepaid_tempdir_west,fstype=nfs,host=CNDAARCPAPZT06,mode=rw,path=/tempdir_west free=550829162496i,inodes_free=15969387i,inodes_total=15969483i,inodes_used=96i,total=550829555712i,used=393216i,used_percent=0.00007138614766081871 1580985013000000000
> disk,IP=10.5.131.75,LOB=Archival-Prepaid,application_name=Archival-Prepaid,device=10.5.75.16:/prepaid_west_hub1,fstype=nfs,host=CNDAARCPAPZT06,mode=rw,path=/west_hub1 free=4178143838208i,inodes_free=21251030i,inodes_total=21251126i,inodes_used=96i,total=4178144198656i,used=360448i,used_percent=0.000008626988032532402 1580985013000000000
> disk,IP=10.5.131.75,LOB=Archival-Prepaid,application_name=Archival-Prepaid,device=10.5.75.16:/prepaid_west_hub2,fstype=nfs,host=CNDAARCPAPZT06,mode=rw,path=/west_hub2 free=6926922907648i,inodes_free=21251030i,inodes_total=21251126i,inodes_used=96i,total=6926923268096i,used=360448i,used_percent=0.000005203580089592593 1580985013000000000

**Comment by russorat** [comment]
@rguptarg thanks for the issue. Could you post the config you are using as well as information about the environment you are running on to help us track down the issue?
