### ISSUE TITLE
Why does Telegraf deep copy metrics for each output plugin?

### ISSUE THREAD

**Issue by AtakanColak** [influxdata/telegraf#6996]
Hello, I was looking at agent.go to get a more in-depth understanding of output plugins. I observed that runOutputs() function has a metric.Copy() which is said to pass a deep copy of the metric to output plugins because output.AddMetric() 'consumes' it. May I ask why don't Telegraf output plugins just share the metrics? 

Thank you.

**Comment by danielnelson** [comment]
This is done, only when there is more than one output, because output plugins may modify the metric differently using taginclude/tagexclude and fieldpass/fielddrop.  (It would be possible to remove this copy, but a bit more complex to implement)
