### ISSUE TITLE
amqp_consumer should handle gzip and non-gzipped messages

### ISSUE THREAD

**Issue by hanej** [influxdata/telegraf#6998]
## Feature Request

We have some applications which send directly to RabbitMQ in plain text but we want to move to using compressed messages to speed up the transfer between data centers.  The issue is the amqp_consumer plugin requires all messages to either be compressed or uncompressed.  There isn't a way for the plugin to handle both at the same time.

### Proposal:

If `content_encoding` is set to gzip, allow it to attempt to uncompress messages and if that is not successful, try reading it as plain text.

### Current behavior:

All messages have to either be compressed or uncompressed.  If the `content_encoding` is set to gzip, and messages come through that are not compressed, the plugin drops it with this error message.

`2020-02-07T21:46:49Z E! [inputs.amqp_consumer] Error in plugin: gzip: invalid header`

### Desired behavior:

Allow some flexibility in some messages not being compressed.

### Use case: 

This allows applications to continue to send uncompressed messages without a lot of code changes.  Also, it doesn't require your entire infrastructure to switch to compressed messages all at the same time without the loss of messages.

**Comment by danielnelson** [comment]
Maybe it would be best to add a new encoding type, this could avoid reduction in the quality of error messages:
```
content_encoding = "auto"
```

**Comment by hanej** [comment]
That would be perfect

**Comment by hanej** [comment]
Is this feature still planned?

**Comment by sspaink** [comment]
@hanej sorry you haven't had a response in a while, looks like this feature hasn't been implemented yet. Are you still interested in being able to handle both gzip and non-gzipped message for the plugin amqp_consumer?

**Comment by hanej** [comment]
Yes, this would still be very beneficial for us if this were implemented.
