### ISSUE TITLE
Aggregator for Percentiles

### ISSUE THREAD

**Issue by TheGreatYamcha** [influxdata/telegraf#6999]
## Feature Request

I want to calculate Percentiles (p50, p99, etc) in telegraf before sending it to influx. Currently there's no aggregator that does this.

### Proposal:
I wanted to create my own aggregator that does this, but I don't know if this is even possible. 
For percentiles, you need the entire dataset of that period (e.g. 30 sec). I wonder if I can add the value to an array in:
`func (b *BasicStats) Add(in telegraf.Metric)`
but not sure where to go from there.

### Current behavior:
Can't do percentiles.
### Desired behavior:
Do percentiles.
### Use case: 
The current aggregations (max/min/mean) don't give us a full picture.

**Comment by danielnelson** [comment]
The tdigest aggregator in #6887 will allow for quantile calculation once merged, I'd also like to add other methods similar to what is available in [Flux](https://docs.influxdata.com/flux/v0.50/stdlib/built-in/transformations/aggregates/quantile/).

**Comment by TheGreatYamcha** [comment]
@danielnelson when do you expect that to be merged?

**Comment by danielnelson** [comment]
Hoping to have tdigest in for 1.14.0

**Comment by TheGreatYamcha** [comment]
And when is that expected?

**Comment by danielnelson** [comment]
Tentative dates can be found on https://github.com/influxdata/telegraf/milestones.
