### ISSUE TITLE
Create a debian/rpm package with a telegraf version that has plugin support

### ISSUE THREAD

**Issue by mildebrandt** [influxdata/telegraf#7003]
## Feature Request

Create an installable package of telegraf that has plugin support. Enabling plugin support is outlined here: https://github.com/influxdata/telegraf/pull/6393

### Use case

The plugin support in telegraf lets us include plugins without needing to compile our own version of telegraf. However, since a version of telegraf with plugin support isn't built as part of the official release process, we need to compile our own version of telegraf. 

What we'd like to do is, create a docker container with an officially released telegraf build and package our plugins and conf files along side.

**Comment by mildebrandt** [comment]
I'm beginning to think there's no good way to support this with Go's limitations right now.

https://github.com/golang/go/issues/27751

https://github.com/golang/go/issues/26759

https://www.reddit.com/r/golang/comments/b6h8qq/is_anyone_actually_using_go_plugins/ejkxd2k/

**Comment by danielnelson** [comment]
Thanks for looking into this, I think for now let's close this issue and we can reevaluate if there are improvements to the plugin package in the future.
