### ISSUE TITLE
memory input makes disco

### ISSUE THREAD

**Issue by wuast94** [influxdata/telegraf#7006]
in the picture the problem should get clear

every 60s i get the right value and all values between are way to low
my telegraf interval is set to 10s 
no events in my log 
running in a docker container and i just restarted it, beside that i didnt shange anything and befor that it was working as it should

![image](https://user-images.githubusercontent.com/16965460/74189416-a191c100-4c50-11ea-8f3f-a4970039de8c.png)

**Comment by danielnelson** [comment]
Try removing the `distinct()` function, I think a more appropriate aggregation would be `max()` or `last()`.

If that doesn't help, can you ask for assistance over at the [InfluxData Community](https://community.influxdata.com) site.
