### ISSUE TITLE
win_perf_counters > 100% x CPU count

### ISSUE THREAD

**Issue by ZHumphries** [influxdata/telegraf#7007]
### Relevant telegraf.conf:

```toml
  [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
```

### System info:

Telegraf 1.13.2
Windows Server 2016 & Windows 10 1803 (2 or 4 core systems) - Showing on 3 separate 2016 servers and 15 windows 10 installations

### Steps to reproduce:

Run telegraf on windows system and collect process data

### Expected behavior:

Windows processes to report correct value for Percent_Processor_Time

### Actual behavior:

Telegraf process data for individual processes is greater than 100% x CPU count, in some cases over 30000% (on a dual core system)

### Additional info:d

Raw data from telegraf --test
win_proc,host=<servername>,instance=WmiPrvSE,objectname=Process Percent_Processor_Time=75542.765625,Handle_Count=157,Private_Bytes=2789376,Thread_Count=7,Virtual_Bytes=2199062839296,Working_Set=3911680 1581413520000000000

 typeperf.exe "\process(WmiPrvSE)\% Processor Time"
"(PDH-CSV 4.0)","\\<servername>\process(WmiPrvSE)\% Processor Time"
"02/11/2020 09:31:50.875","0.000000"
"02/11/2020 09:31:51.878","0.000000"
"02/11/2020 09:31:52.878","0.000000"
"02/11/2020 09:31:53.889","0.000000"
"02/11/2020 09:31:54.897","0.000000"
"02/11/2020 09:31:55.903","0.000000"
"02/11/2020 09:31:56.915","1.542427"
"02/11/2020 09:31:57.919","0.000000"
"02/11/2020 09:31:58.928","0.000000"
"02/11/2020 09:31:59.935","0.000000"
"02/11/2020 09:32:00.936","0.000000"
"02/11/2020 09:32:01.950","0.000000"
"02/11/2020 09:32:02.956","0.000000"
"02/11/2020 09:32:03.958","0.000000"
"02/11/2020 09:32:04.972","0.000000"
"02/11/2020 09:32:05.981","0.000000"
"02/11/2020 09:32:06.992","0.000000"
"02/11/2020 09:32:08.003","0.000000"
"02/11/2020 09:32:09.010","0.000000"
"02/11/2020 09:32:10.013","0.000000"

**Comment by danielnelson** [comment]
Thanks for opening the issue, unfortunately I'm not able to replicate.  Here is what I'm trying:

```
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Instances = ["telegraf"]
    Counters = [
      "% Processor Time",
    ]
    Measurement = "win_cpu"
```

```
$ telegraf.exe --config telegraf.conf
2020-02-11T19:21:45Z I! Starting Telegraf 1.13.3
2020-02-11T19:21:45Z I! Loaded inputs: win_perf_counters
2020-02-11T19:21:45Z I! Loaded aggregators:
2020-02-11T19:21:45Z I! Loaded processors:
2020-02-11T19:21:45Z I! Loaded outputs: file
2020-02-11T19:21:45Z I! Tags enabled: host=windows-10
2020-02-11T19:21:45Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"windows-10", Flush Interval:10s
win_cpu,host=windows-10,instance=telegraf,objectname=Process Percent_Processor_Time=1.5505390167236328 1581448911000000000
win_cpu,host=windows-10,instance=telegraf,objectname=Process Percent_Processor_Time=0 1581448920000000000
win_cpu,host=windows-10,instance=telegraf,objectname=Process Percent_Processor_Time=0.15621648728847504 1581448930000000000
win_cpu,host=windows-10,instance=telegraf,objectname=Process Percent_Processor_Time=0.15630848705768585 1581448940000000000
```

**Comment by TiagoMHCSantana** [comment]
I had the same issue, mainly with SQL Server processes. I was wondering if it is because the processes have the same name, but different PIDs.

@danielnelson maybe it's worth trying with Instances = ["*"], once not all processes exhibit that behavior.

**Comment by ZHumphries** [comment]
@danielnelson So what is needed from my side to help progress this further?

**Comment by danielnelson** [comment]
Can you check with my configurations above and see if the values are still off?

**Comment by ZHumphries** [comment]
Not all processes exhibit this behaviour. telegraf.exe is one that returns normal results. There are 4 that seem to be returning the most skewed data (although it makes me doubt all of the process data)

win_proc.max {instance: svchost} | 204.53 K
win_proc.max {instance: WmiPrvSE} | 189.84 K
win_proc.max {instance: csrss} | 5.50 K
win_proc.max {instance: mmc} | 5.22 K

Most of the other processes look have reasonable values.

**Comment by vlastahajek** [comment]
@ZHumphries, could you, please, include complete [[inputs.win_perf_counters]] config?

**Comment by vlastahajek** [comment]
This seem to be the same issue as it is in #6448.

**Comment by danielnelson** [comment]
The workaround on that issue was to set `UseWildcardsExpansion=true`, @ZHumphries does that help out here as well?

**Comment by ZHumphries** [comment]
Yes that works. Thanks for the assist

**Comment by davidgarciaMontreal** [comment]
Can anyone provide an example where to apply the work around? I'm having the same problem in my window machines..
UseWildcardsExpansion

**Comment by vlastahajek** [comment]
@davidgarciaMontreal, add it as a global param in the plugin config. It looks you have a config without commented default parameters. There is another related option that can be added, `CountersRefreshInterval`:

```toml
[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true
  CountersRefreshInterval="1m"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
    Measurement = "win_cpu"
    IncludeTotal=true
```
