### ISSUE TITLE
CPU input reports incorrect values

### ISSUE THREAD

**Issue by PhillWide** [influxdata/telegraf#7008]
### Relevant telegraf.conf:

```toml
  [[inputs.cpu]]
    percpu = true
    totalcpu = true
    fielddrop = ["time_*"]
    collect_cpu_time = true
```

### System info:

telegraf 1.13.2, debian 10.3, virtualbox 6.0.16

### Steps to reproduce:

1. setup virtual box and telegraf on the host
2. create a cpu load on the host

### Expected behavior:

htop reports correctly one CPU core being used to 100%

### Actual behavior:

Telegraf reports under 15% overall load as system usage. Nothing else. 

### Additional info:

I think it might be the /proc/stat doesnt have correct values. So Im not sure if there is something to fix with the plugin it self (would be nice to have an alternative that works in that case)
There is the content of /proc/stat during load:
```
cpu  1298503 1808 5669882 945466270 321522 0 360471 0 0 0
cpu0 148889 205 631010 118326724 42091 0 209151 0 0 0
cpu1 163827 230 859708 118086958 26050 0 71360 0 0 0
cpu2 164932 106 645701 118343971 30337 0 31723 0 0 0
cpu3 164107 372 706023 118295773 28229 0 8697 0 0 0
cpu4 149010 295 988372 117850977 80588 0 10923 0 0 0
cpu5 179047 80 746297 118227496 42600 0 4225 0 0 0
cpu6 157470 281 480751 118145761 35243 0 12306 0 0 0
cpu7 171218 237 612019 118188607 36380 0 12082 0 0 0
intr 513409292 42 0 0 0 2192 0 0 0 1 2385284 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 21330112 4952946 5530424 1793751 9393794 993508 2406416 2392921 63892528 57 1 15962025 911906 879925 643232 923096 4520733 707886 834785 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 1039315405
btime 1580221535
processes 97004
procs_running 2
procs_blocked 0
softirq 745521246 1 238021197 5738159 79654504 0 0 2018759 240048371 1060 180039195
```

**Comment by danielnelson** [comment]
Try enabling `report_active = true` and check `usage_active` to get a value similar to htop, does that give you the expected values?

**Comment by PhillWide** [comment]
Thank you for you response. I'm not sure. Within this option I get 12.5. I'm not sure what it should represent. The cpu usage is over 100% going to +-120 at times. Does that mean 125% of CPU usage?

**Comment by danielnelson** [comment]
Since you have `percpu = true` you should get one value for each cpu plus a total value `totalcpu = true`, when you query the database you will want to `group by cpu`.  We define active as user + system + nice + iowait + irq + softirq + steal.

The `usage_active` value shouldn't go over 100% on Linux, make sure you aren't applying any aggregations in the query, or check what Telegraf would report with `telegraf --input-filter cpu --test`

**Comment by PhillWide** [comment]
Oh, I get it now (Did not realize there was usage_active even for each CPU)

So I figured out where I was wrong. With my previous setups I was looking on per CPU user usage, but with virtualbox the benchmark load was under system.

Thanks for the help.
