### ISSUE TITLE
Support scaling modbus values to a range

### ISSUE THREAD

**Issue by fbergroth** [influxdata/telegraf#7009]
## Feature Request

Opening a feature request kicks off a discussion. Ref: https://github.com/influxdata/telegraf/pull/6154#issuecomment-584408373

### Proposal:

Support scaling modbus values to a range.

### Current behavior:

Currently you can only scale a value by a factor.

### Desired behavior:

Ideally I'd like to specify the bounds of the range (min and max), but an offset and scale would work as well. For a 16 bit value, it would be scaled to `(max - min) * value / 2**16 + min`.

### Use case: 

For some sensors you want to scale it to a certain range. For example, a resistance thermometer may need to be linearly scaled to [-50, 150] °C.

**Comment by sensor-freak** [comment]
Shouldn't this be done with a processor plugin? Isn't there a transformation plugin?

**Comment by sjwang90** [comment]
These types of calculations can be done with the [Starlark Processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark). Please check out the [examples](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark#examples) and how you can perform a mathematical function.
