### ISSUE TITLE
"Wrote XXX metrics to output" prints in quiet mode 

### ISSUE THREAD

**Issue by jpkorva** [influxdata/telegraf#701]
I'm running 0.10.2 with -quiet option on Centos 7. Syslog contains still a fair amount of "Wrote 130 metrics to output kafka in 84.823933ms" and they do not seem really useful. Would it be possible to suppress these prints as well?

**Comment by sparrc** [comment]
sure, I think this was supposed to be suppressed in quiet mode

**Comment by playqdrew** [comment]
I am seeing this behavior in 1.1.1
