### ISSUE TITLE
The --test parameter should consider metric conversion settings

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#7011]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
The `--test` parameter should consider metric conversion settings.

### Current behavior:
When the agent starts with the `--test` parameter, the agent returns metrics in the form in which the collectors return them. Conversion settings are ignored.

### Desired behavior:
When starting an agent with the `--test` parameter, the agent will return data, as it would when starting without `--test`, using `processors`.

### Use case:
Now, in order to understand in what form the metrics will be written to the repository, you must delete the outputs to the databases and write the output to `stdout` through the `outputs.file` plugin. This approach is inconvenient when debugging working configurations.

The described behavior is seen in version 1.12.x and 1.13.0. 
Probably, newer releases behave in a similar way.

**Comment by danielnelson** [comment]
Merging with #6190
