### ISSUE TITLE
x509_cert plugin - add tag to identify cert as intermediate or end

### ISSUE THREAD

**Issue by poodad** [influxdata/telegraf#7012]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a tag to identify if the recorded cert information is an intermediate cert or end cert
### Current behavior:
No way to easily ignore intermediate certs when checking expiry of a cert chain
### Desired behavior:
Add tag that distinguishes intermediate certs from end certs
### Use case: 
Trying to do a grafana panel showing the expiry of certs for ssl web sites is made more difficult because unless you somehow filter out intermediate certs, the expiry times of the end cert and intermediate get muddled.

**Comment by powersj** [comment]
next step: determine the programmatic way to determine if the issuer is the same as the subject, which means it is a root CA (this assumption needs to be checked as well, as well as the possible security/spoofing implication to ensure we are doing the right thing).

**Comment by srebhan** [comment]
@poodad can you please check if the binary in #12656 (once CI finished building) fixes the issue for you!?

**Comment by poodad** [comment]
Yes, it appears to work. Thanks!
