### ISSUE TITLE
Add support for JKS files to x509_cert plugin

### ISSUE THREAD

**Issue by elizabetht** [influxdata/telegraf#7013]
### Relevant telegraf.conf:

```toml
[[inputs.x509_cert]]
  sources = ["/etc/path-to-jks/server.jks"]
```

### System info:
telegraf-1.13.2-1.x86_64 is included in the package 

### Steps to reproduce:

1. Update the above telegraf config and reload telegraf-client
2. Errors appear in the telegraf-client logs 
```E! [inputs.x509_cert] Error in plugin: cannot get SSL cert '/etc/path-to-jks/server.jks': failed to parse certificate PEM```

### Expected behavior:

x509_cert plugin to parse JKS certificate files

### Actual behavior:
Getting errors in the telegraf-client logs
```
 E! [inputs.x509_cert] Error in plugin: cannot get SSL cert '/etc/corona/server.jks': failed to parse certificate PEM
```

**Comment by elizabetht** [comment]
Is JKS file supposed to be supported by this plugin? or can it be supported?

**Comment by danielnelson** [comment]
Unfortunately the plugin does not support JKS format, we only have support for PEM encoded certs.  We are interested in adding support for additional formats though, I'll mark this as a feature request.

**Comment by elizabetht** [comment]
Thanks @danielnelson. Looking forward to this feature getting implemented.

**Comment by Nurlan199206** [comment]
@elizabetht you can use input.exec plugin with bash scripts.


![Снимок экрана 2020-07-03 в 22 55 05](https://user-images.githubusercontent.com/22808731/86487580-49cf3000-bd80-11ea-8b4e-c54f8d90a852.png)

**Comment by gilgameshfreedom** [comment]
+1 for this feature. Currently we have to deploy java jetty server which reads and used jks certs and envoy monitors jks certs through jetty (as common pem). But this approach is lightly awkward.

**Comment by sspaink** [comment]
Looking for a Go solution to parse the JKS format I found this: https://github.com/pavlo-v-chernykh/keystore-go which seems like the most mature solution. Although the problem I am seeing is it doesn't provide an exact match to the existing fields and tags the plugin outputs. I am not too familiar with the JKS format if this is a limitation of the package or the format, curious if anyone interested in this feature could share what fields and tags they would be interested in getting if the plugin could parse JKS?

**Comment by Illutax** [comment]
It's odd that you *have to* work with the jks and doesn't have the certificates laying around. But you might create your own Telegraf plugin consisting of a bash script, which extracts the p12 from the keystore using openssl and then writing the metric.

For reference here is a full tutorial: https://songrgg.github.io/operation/how-to-check-and-monitor-tls-jks-certificates-with-telegraf/
