### ISSUE TITLE
postgresql_extensible: remove "select version" every interval

### ISSUE THREAD

**Issue by florianwgnr** [influxdata/telegraf#7015]
### telegraf conf
- interval: 1s
- postgresql_extensible plugin enabled (default config)

### System info:

Telegraf v.: 1.11.4

checked plugin code in github: 12.02.2020

### Steps to reproduce:

1. enable postgresql_extensible plugin
2. check Postgres-Log (with debug level so queries are shown)

### Actual behavior:

3. The following querie is executed every time

`2020-02-12 10:00:01 CET LOG:  duration: 212.000 ms  execute <unnamed>: SELECT setting::integer / 100 AS version FROM pg_settings WHERE name = 'server_version_num'
2020-02-12 10:00:02 CET LOG:  duration: 201.000 ms  execute <unnamed>: SELECT setting::integer / 100 AS version FROM pg_settings WHERE name = 'server_version_num'
2020-02-12 10:00:03 CET LOG:  duration: 201.000 ms  execute <unnamed>: SELECT setting::integer / 100 AS version FROM pg_settings WHERE name = 'server_version_num'
`

I searched for the problem and found it in the postgresql_extensible plug-in. Each time this happens, the query listed above is executed (see also Code Snipped). 

The execution times are between 150ms and 350ms.

![grafik](https://user-images.githubusercontent.com/39341393/74325285-9c379200-4d88-11ea-9bd6-39ff5de3fbd5.png)

### Expected behavior:

Since the telegraph is set to 1 second, the code is executed every second. Is it possible to save the version so that a permanent execution of unnecessary queries is avoided?
Furthermore, we do not use the version check at all. Maybe another option would be a variable to disable this function in the go code.

**Comment by danielnelson** [comment]
Thanks for the report, we're planning to revamp this plugin soon and will likely drop the version check as part of it.  In the meantime, I would merge a pull request where if no query version options were set, we skipped the the version query.

**Comment by powersj** [comment]
It does appear that this query happens at each gather. However, the results are used for checking against the query versions specified by the user. However, this probably is safe to not run every single time.

next steps: move query to init and out of gather

**Comment by redbaron** [comment]
>  However, this probably is safe to not run every single time.

Database can be  upgraded independently from Telegraf instance restarts/reloads, then version check will break. PostgreSQL already reports it's version to every connection and no query required to look it up, see: 

https://github.com/jackc/pgx/blob/038fc448c1cc91b9372a6a0d151789f41536f033/pgxtest/pgxtest.go#L158-L159

Having said that, query as is touches no data and takes than 1ms on the server, any delay on top of it must be coming from latency between telegraf and PostgreSQL server. With up to 350ms latency it is unrealistic to collect stats every second.

**Comment by powersj** [comment]
Thanks for the analysis. Based on that, I don't think it makes sense to even do this feature request and instead close this. Thoughts?

**Comment by redbaron** [comment]
I agree
