### ISSUE TITLE
telegraf log files

### ISSUE THREAD

**Issue by timwellman** [influxdata/telegraf#7017]
I am looking to create log files for telegraf under /var/log/telegraf

I have multiple telegraf containers running, using the same telegraf.conf file.   I would like the log files to have the container name in the file.

ex.
/var/log/telegraf/"container_name"_01.log
/var/log/telegraf/"container_name"_02.log

Is there a way to do this in the telegraf.conf file with a variable?

Thanks

**Comment by M0rdecay** [comment]
You can try to make the [configuration](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent) of the log file name 
```
[agent]
  logfile = "/var/log/telegraf/container_name.log"
```
in [separate directories](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#configuration-loading) and specify the private key` --config-directory` for each agent.
We use this approach to separate agent configurations on the same host that collect different data.

**Comment by danielnelson** [comment]
Another option you can use, separately or combined with @M0rdecay suggestions, might be using an environment variable to set the logfile name.

```toml
[agent]
  logfile = "/var/log/telegraf/${HOSTNAME}.log"
```

We generally try to handle usage questions at the [InfluxData Community](https://community.influxdata.com) site, if you have any follow up questions it would be best to open a topic there.
