### ISSUE TITLE
Update syslog input plugin

### ISSUE THREAD

**Issue by leodido** [influxdata/telegraf#7023]
## Feature Request

Hello folks! 🤗 

I'm opening this issue to notify y'all that some days ago I finally completed a (first, initial) parser for BSD-syslog messages (see [rfc3164](https://github.com/influxdata/go-syslog/tree/develop/rfc3164)). My friend @goller then released [v3](https://github.com/influxdata/go-syslog/releases/tag/v3.0.0) for [go-syslog](https://github.com/influxdata/go-syslog) to include it.

This issue is to request that the syslog input plugin gets updated to go-syslog v3.

### Proposal:

1. Updating the go-syslog version being used to v3
2. Adapting the current syslog input plugin to the new interfaces
3. Adapt plugin configuration to support RFC3164 parsing
    3.1 Take into account the various parsing [options](https://github.com/influxdata/go-syslog/blob/develop/rfc3164/options.go) it provides

### Current behavior:

Depending on go-syslog v2.

Supporting RFC5424 parsing, with octect-counting or with non-transparent framing technique.

### Desired behavior:

Depending on go-syslog v3.

Supporting RFC3164 parsing (with tunable options), too.

### Use case: 

Should unblock (at least, partially, depending on the "kind" of BSD-syslog messages people wants to parse) issue https://github.com/influxdata/telegraf/issues/4593 - Blocking #4593 

Also refs to https://github.com/influxdata/telegraf/issues/4902

**Comment by danielnelson** [comment]
Thanks Leo!  Is this update you would like to work on or would you rather we handle it?

**Comment by leodido** [comment]
Hey @danielnelson! At the moment, I don't think to have time to handle it so it depends on you folks!

**Comment by patn03** [comment]
Is there a work around to this? I'm assuming this would be why my network gear and Solarwinds Log Forwarders for windows are failing? Anything using Rsyslog is working correctly but all items using Syslog clients directly to the Telegraf Instance are getting the errors below.

UDP Client
`[inputs.syslog] Error in plugin: expecting a version value in the range 1-999 [col X]`
and TCP Client
`[inputs.syslog] Error in plugin: found ILLEGAL(<), expecting a MSGLEN`

**Comment by danielnelson** [comment]
The best workaround is to use rsyslog to convert to the RFC5424 format.  If you are feeling adventurous you should be able to send RFC3164 directly to the `socket_listener` and parse with `data_format = "grok"` as well.

**Comment by sjwang90** [comment]
@leodido Now that we have BSD syslog message support - is there anything else you're looking for in this issue?

**Comment by leodido** [comment]
Nope :)

Ty!
