### ISSUE TITLE
Dumb question: Can I rename the hostname on a specific input plugin?

### ISSUE THREAD

**Issue by FlorentLM** [influxdata/telegraf#7025]
I am grabbing some info from a machine which I have no access to other than through a vendor API.

For that, I'm using the http input plugin with json parsing, it works fine but these measurements are obviously marked with the hostname of the machine **which launches the queries**. I would like to replace the hostname on these in order to make them look like they originate from the second machine (i.e. the one I have no access to other than through the API).

Is it possible?

Thanks!

**Comment by danielnelson** [comment]
Yes, you can set a static tag on any input plugin:
```toml
[[inputs.http]]
  [inputs.http.tags]
    host = "foo"
```

On many newer plugins, we have started using a tag called `source` to indicate the hostname the metrics are about, as opposed to the `host` tag which is the system reporting.  Sometimes it is helpful to have both, so consider using this tag instead.

BTW, in the future the best place to ask usage questions is on the [InfluxData Community](https://community.influxdata.com) site.
