### ISSUE TITLE
CrateDB Output to replace dots in tags with custom separator

### ISSUE THREAD

**Issue by h4xmd** [influxdata/telegraf#7026]
### Proposal:

When using the CrateDB output plugin with the Docker plugin enabled, some measurements fail to get inserted into CrateDB because they have a dot in their tag name.

### Current behavior:

Feb 14 03:50:21 agent-1 telegraf[1345]: 2020-02-14T03:50:21Z E! [agent] Error writing to output [cratedb]: ERROR: "io.k8s.description" contains a dot (SQLSTATE XX000)
Feb 14 03:50:31 agent-1 telegraf[1345]: 2020-02-14T03:50:31Z E! [agent] Error writing to output [cratedb]: ERROR: "dockerImage.teamcity.buildNumber" contains a dot (SQLSTATE XX000)

### Desired behavior:

The measurements should have the dots replaced with something valid for CrateDB such as underscores or be able to be configurable.

### Use case: 

Currently finding it difficult for Telegraf to send all metrics into CrateDB

**Comment by pavan-kalyan** [comment]
would it make sense to write a cleanMetrics function in [cratedb.go](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/cratedb/cratedb.go) to be called in the Write method which would convert dots to a specific configurable char ?

Or perhaps something smilar to the escapeValue() (escapeTags() ?)

**Comment by danielnelson** [comment]
First thing I'd like to check is if dots really cannot be used in column names, perhaps we just aren't escaping the SQL correctly.  If we do need to remove them I'm not sure it needs to be configurable, if there isn't a strong requirement for configurability I suggest we just use `_`.

**Comment by pavan-kalyan** [comment]
[cratedb naming restrictions](https://crate.io/docs/crate/reference/en/latest/general/ddl/create-table.html#naming-restrictions).
seems like cratedb doesn't allow  dots in column names.
Replacing with `_` seems like a good idea.
