### ISSUE TITLE
apcupsd plugin is missing some data

### ISSUE THREAD

**Issue by donvipre** [influxdata/telegraf#7028]
## Feature Request

The apcupsd plugin is missing Firmware / Model / Nominal Power, and a lot of other settings that might be helpful for advanced graphs.

### Proposal:
add all metrics collected from here:
https://github.com/mdlayher/apcupsd/blob/master/status.go

### Current behavior:
only some metrics are available
### Desired behavior:
all metrics from the above linked sourcecode are collected and forwarded by telegraf

### Use case: 

Nominal power would be very helpful to determine the load percentage for different types of PSUs.

**Comment by danielnelson** [comment]
Thank you!
