### ISSUE TITLE
Telegraf 0.10.2 & InfluxDB 0.10.0 Field overflow

### ISSUE THREAD

**Issue by zorel** [influxdata/telegraf#703]
After the upgrade from Telegraf 0.2 => 0.10.2 and InfluxDB 0.9.6 => 0.10.0, I hit this error:

Telegraf side: ERROR: {"error":"write failed: field overflow"}
Influxdb side: 
   write failed for shard 64 on node 1: field overflow
   POST /write?consistency=&db=avaas&precision=s&rp= HTTP/1.1 500 65 - InfluxDBClient a1c2e0b6-d4c2-11e5-8377-000000000000 1.729674011s

I use a httpjson service for Mesos which answer a quite large payload.

**Comment by sparrc** [comment]
can you show me debug output? InfluxDB 0.10.x isn't supposed to have field overflows. @pauldix

**Comment by zorel** [comment]
I delete the old data (the database created by influxdb 0.9.6), and now it works, and I won't have the time to test again soon.

However, the data fetched from Mesos is quite large (1Mo of json), it does not seems really suitable or usable for me.

Thanks.

**Comment by sparrc** [comment]
There will be a mesos-specific input plugin available soon that should provide easier-to-use data #682
