### ISSUE TITLE
Enable non-cumulative values in histogram aggregator

### ISSUE THREAD

**Issue by fxedel** [influxdata/telegraf#7034]
## Feature Request

![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Cumulative_vs_normal_histogram.svg/1920px-Cumulative_vs_normal_histogram.svg.png)

*Histogram plugin currently only creates cumulative histograms; proposal is to add an option for ordinary histograms.*

### Proposal:

The [histogram aggregator plugin](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/histogram) should be able put values in buckets without cumulating smaller values.

### Current behavior:

> The histogram aggregator plugin creates histograms containing the counts of field values within a range.
>
> Values added to a bucket are also added to the larger buckets in the distribution. This creates a cumulative histogram.

For example with buckets `[0.0, 10.0, 100.0]` and values `0, 1, 15, 20`, following metrics are generated:

```
measurement,le=0.0 field_bucket=1i
measurement,le=10.0 field_bucket=3i
measurement,le=100.0 field_bucket=4i
measurement,le=+Inf field_bucket=4i
```

### Desired behavior:

There should be a configuration option `cumulative` (boolean, defaults to true) that defines whether values added to a bucket are also added to the larger buckets.

With `cumulative = false` and the same buckets `[0.0, 10.0, 100.0]` and values `0, 1, 15, 20`, following metrics should be generated:

```
measurement,le=0.0 field_bucket=1i
measurement,le=10.0 field_bucket=1i
measurement,le=100.0 field_bucket=2i
measurement,le=+Inf field_bucket=0i
```

It may also be considered adding a `gt` (greater than) tag:

```
measurement,gt=-Inf,le=0.0 field_bucket=1i
measurement,gt=0.0,le=10.0 field_bucket=1i
measurement,gt=10.0,le=100.0 field_bucket=2i
measurement,gt=100.0,le=+Inf field_bucket=0i
```

### Use case:

Grafana's [Heatmap panel](https://grafana.com/docs/grafana/latest/features/panels/heatmap/) works with [pre-bucketed data](https://grafana.com/docs/grafana/latest/features/panels/heatmap/#pre-bucketed-data), but it requires the data to be non-cumulative.

Example with buckets `[0.0, 10.0, 100.0, 1000.0]` and non-cumulative bucketing (note that I've used the `le` tag and renamed `+Inf` to `>1000` as Grafana reads the tag values as numbers. A `gt` tag would be much better here):

```
time                 le    response_time_ms_bucket
----                 --    -----------------------
2020-02-17T08:40:20Z 0     1
2020-02-17T08:40:20Z 10    2
2020-02-17T08:40:20Z 100   1
2020-02-17T08:40:20Z 1000  2
2020-02-17T08:40:20Z >1000 0
...
2020-02-17T08:41:00Z 0     0
2020-02-17T08:41:00Z 10    2
2020-02-17T08:41:00Z 100   1
2020-02-17T08:41:00Z 1000  2
2020-02-17T08:41:00Z >1000 0
...
2020-02-17T08:41:30Z 0     0
2020-02-17T08:41:30Z 10    1
2020-02-17T08:41:30Z 100   0
2020-02-17T08:41:30Z 1000  4
2020-02-17T08:41:30Z >1000 0
```

![grafik](https://user-images.githubusercontent.com/7782229/74638135-a0d6be80-516b-11ea-8211-38b70fe73a05.png)

![grafik](https://user-images.githubusercontent.com/7782229/74638182-afbd7100-516b-11ea-8c72-06722adb7375.png)

**Comment by danielnelson** [comment]
Makes sense to have this configurable to me, though I'm surprised that this Grafana panel doesn't support cumulative histograms as I thought all Prometheus histograms were cumulative.

**Comment by jd79** [comment]
thank you for this feature. I also think that the cumulative histogram isn't informative enough for the most cases.

**Comment by frag-seb** [comment]
+1 for this, I do need it too.
