### ISSUE TITLE
Input SQL Server - error max key length exceeded, discarding points

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7037]
The issue is about the current output of the SQL Server plugin, which can cause errors when using the "SqlRequests" measurement due to the column "statement_text" being a tag ,saving it as a field should solve the issue

### Relevant telegraf.conf:
No relevant conf needed, just use the Sql Server input plugin without excluding "SqlRequests"
```
[[inputs.sqlserver]]
  # servers = [
  #  "Server=192.168.1.10;Port=1433;User Id=<user>;Password=<pw>;app name=telegraf;log=1;",
  # ]

  query_version = 2
  # Note that 'SqlRequests' is not excluded
  exclude_query = [ 'Schedulers']
```

### System info:
Telegraf:
1.13.3
OS: 
Windows Server 2016 Standard

I've several telegraf instances, in total, I monitor 25 instances with ~470 databases

### Steps to reproduce:

Input a Line Protoco String which is bigger than 64kb (I cannot share the string itself), this will cause will raise the following error:
> 2020-02-17T11:49:00Z E! [outputs.influxdb] When writing to [http://127.0.0.1:8086]: received error partial write: \_HugeLineProtocolString\_  : max key length exceeded: 85962 > 65535 dropped=0; discarding points

The huge value, in the above example, is caused by the column "Statement_text" (which alone weights 84,17kb encoded in UTF8) being a tag, and therefore part of the key.

### Expected behavior:

Being able to write the value

### Actual behavior:

The point gets discarded due to "max key length exceeded"

**Comment by danielnelson** [comment]
related #6976

**Comment by Trovalo** [comment]
For anyone who encounter this kind of problem, a temporary workaround can be to use the telegraf processor to convert the "column" from tag to field.
Just use the "converter" processor in your telegraf configuration.
```
[[processors.converter]]
  [processors.converter.tags]
    string = ["statement_text"]
```

**Comment by sspaink** [comment]
@Trovalo are you still having this problem? Or was the workaround sufficient?

**Comment by Trovalo** [comment]
The issue can be closed.

The workaround works, also it makes sense to store that string (a query text) as a field for several reasons:
- the length can be huge (leading to the error)
- saved as a tag it's unreadable because the escape sequences are kept as-is (full of `\n \t` etc), as a field it's readable
- I don't think it's worth indexing, it will also take lots of space

I thought about turning it into a field by default, but it'll be an exception to the current general logic of the plugin (which is: string values → tags, numeric values → fields), also the query is disabled by default.
