### ISSUE TITLE
regexp "\..*" makes telegraf crash

### ISSUE THREAD

**Issue by adam0war** [influxdata/telegraf#7045]
# Relevant telegraf.conf:

[[inputs.ping]]
  urls = ["host1.example.domain.net", "host2.next.domain.com"]  
  method = "native"
  count = 1
[[processors.regex]]
  [[processors.regex.tags]]
    key = "url" 
    **pattern = "\\..\*\$"**
    result_key = "host"

### System info:

Telegraf 1.13.2 (git: HEAD 6dad859d)
centos 8 3.10.0-1062.12.1.el7.x86_64

### Steps to reproduce:

use "\\..\*\$" regexp

### Expected behavior:

new tag named host with just a host name, without FQDN:

ping_average_response_ms{host="host1",instance="telegraf:9090",job="telegraf",url="host1.example.domain.net"}
ping_average_response_ms{host="host1",instance="telegraf:9090",job="telegraf",url="host2.next.domain.com"}

### Actual behavior:

Error running agent: Error parsing /etc/telegraf/telegraf.conf, line **x**: invalid TOML syntax

### Additional info:

I'm trying to get rid of FQND from host name located in tag "url" by removing everything after first "." with regexp "\\..\**\$". It makes telegraf crash.
As a  workaround I am using regexp "[^a-z0-9].*" witch gives me desired result.
I was trying different regexps but it seems like everything with \\. at the beginning of regexp makes telegraf crash.

**Comment by M0rdecay** [comment]
You should either wrap your pattern in single quotes - '\..*$'
Or escape the slash in regular expression - "\\..*$"

What you encounter is a nuance of the TOML parser, not the agent itself.

**Comment by danielnelson** [comment]
For more information about string formats allowed in the configuration file you can also reference https://github.com/toml-lang/toml#string.

**Comment by adam0war** [comment]
thanks, that was it
