### ISSUE TITLE
modbus input plugin does not scale INT32 values

### ISSUE THREAD

**Issue by mkaranki** [influxdata/telegraf#7047]
### Relevant telegraf.conf:

```toml
holding_registers = [
  { name = "test", byte_order = "ABCD",   data_type = "INT32", scale=10.0,  address = [46,47]},
]

```

### System info:
```shell
~$ telegraf --version
Telegraf unknown (git: master 3f7198fc)
```

### Steps to reproduce:

1. Scaling INT32 register values does not work. scale parameter has no effect. This is the test output with the configuration shown above where scale=10.0:
```shell
~$ telegraf --config telegraf.conf --test
2020-02-19T16:29:03Z I! Starting Telegraf 
> modbus,host=testhost,name=testDevice,type=holding_register test=14155996i 1582129743000000000
```
The value is not scaled. This is with the same config but with 1.0 scale this time:
```shell
$ telegraf --config telegraf.conf --test
2020-02-19T16:29:18Z I! Starting Telegraf 
> modbus,host=testhost,name=testDevice,type=holding_register test=14155996i 1582129759000000000
```

### Expected behavior:

The scaling would happen regardless of the data type. If there are justified exceptions to this, then they should be documented.

### Actual behavior:

Scaling does not happen.

### Additional info:

The root cause is likely that  convertDataType function is not scaling the INT32 (or FLOAT32-IEEE) data types, here: https://github.com/influxdata/telegraf/blob/3f7198fca5a063610c293ca26128c243a17d7ba1/plugins/inputs/modbus/modbus.go#L483

It probably should do that?

**Comment by ssoroka** [comment]
What do you expect the behavior to be when the scaled value overflows the size of the int32? 
eg: 2,000,000 * 10 > 2^32

**Comment by mkaranki** [comment]
That's a valid  concern.

If the output is forwarded to e.g. InfluxDB that can support larger datatypes, I would not like to see the overflow to happen at all at least if the results fits into 64 bits. Or then I could also want it to be presented as a floating point number, only loosing precision if the result is too large to fit into the type. Or in some cases I could just know that the overflow can't happen and not to worry about it at all. So I'd say the best would be that the behavior is configurable.

Related, I feel the data_type configuration parameter to be little bit limited and confusing. Currently it seems to define both the datatype of the Modbus register that is read and the output value datatype. But, for example, if I want to read a 16 bit fixed point number that's having one decimal, and forward it as a floating point number, currently I can't do that. Using data_type=FLOAT32 with two bytes (and single register value) in the configuration almost works, but that fails with negative values. Using INT16 with scale=0.1 forwards only an integer, cutting the decimal, thus being not good if that decimal matters.

If there would be configuration options for both input and output data types, then one could define that the input data_type=INT16, scaling=0.1 and output_data_type=FLOAT32 to forward the scaled value using the floating point format.

What is comes to overflows in such case, for instance, if the configuration would define the input data_type to be UINT32, scaling to be 10 and output data type to UINT32, it is somewhat clear the the overflow could happen if the register value is large enough. If the user want's to avoid the possibility of an overflow, then he'd configure the output data type to be a floating point number or UINT64.

The overflow case could be defined to be an error, or then just forward the overflown result. I don't know which option would be better...

**Comment by danielnelson** [comment]
With respect to overflow, I suggest we just stick to Go behavior: integers wrap around and floats eventually become +Inf/-Inf/0.  Integer wrap around can be dealt with on the query side, floats are a bit more complicated as InfluxDB does no support +Inf/-Inf and the values are dropped.

I think we could just encode more types as the data_type, for example we could have a fixed point type where scale configures the decimal point and converts to a float64.  I'd rather avoid doing generic conversions between all data types in this plugin. 

As an aside, Telegraf has only int64, uint64, float64, bool, and string types.  It is possible in the future we could add more types, but that's a larger conversation and ultimately it would require a conversion in the output plugins to the types supported by each database.  With InfluxDB it would be these same types, minus uint64 in most cases.

**Comment by ssoroka** [comment]
@mkaranki I've merged a fix for this. I'd be interested in your feedback once you try it out.

Thanks!
