### ISSUE TITLE
internal_gather - include errors field

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/telegraf#7057]
Is it possible to have gather errors tagged by input?
This would be handy.

**Comment by danielnelson** [comment]
I think this is only a documentation bug, the `internal_gather` measurement should have an `errors` field:
```
internal_gather,input=http,version=unknown errors=0i,gather_time_ns=0i,metrics_gathered=0i 1582242300000000000
```

**Comment by voiprodrigo** [comment]
Indeed. However something is not quite right. I'm having some problems with the iptables plugin, due to locking. There's some other agents on my systems that a few times a day call iptables without -n to avoid DNS reverse resolution. On systems with very large rule sets, this is an issue, because iptables -L can take minutes to finish. If I have the plugin running every 60 seconds, it will fail while that other agent is doing that. Of course that's not the plugin fault, but I would expect to see errors > 0 for the iptables input on those occasions, but no, it's always 0. However, the errors counts is updated in internal_gather.gather_errors for the affected hosts. Using 13.3.

**Comment by ssoroka** [comment]
> There's some other agents on my systems that a few times a day call iptables without -n to avoid DNS reverse resolution

Don't you want to call iptables _with_ `-n` to avoid dns resolution? Seems like that's why it's taking minutes to complete.

In the mean time, I'll dig into the errors issue.

**Comment by voiprodrigo** [comment]
@ssoroka it’s not that I don’t want to use -n (which I do use), but that particular agent is a “blackbox” agent mandated by corporate policy. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
