### ISSUE TITLE
Filtering out specific tags

### ISSUE THREAD

**Issue by gena01** [influxdata/telegraf#706]
I am unable to filter specific tags out from the output. One example is stripping "cont_id" tag from the docker input plugin. 

P.S. "tagdrop" seems to filter all related metrics based on the matching criteria. I just want to strip tags from the output stream.

Am I missing something simple?

**Comment by sparrc** [comment]
nope, there is not currently any way to do that

**Comment by gena01** [comment]
can we make this a feature request?

**Comment by sparrc** [comment]
yep, no problem :+1:
