### ISSUE TITLE
Modbus input: multiple controllers per input

### ISSUE THREAD

**Issue by serrj-sv** [influxdata/telegraf#7066]
## Feature Request

Possibility to specify array of "controllers" per input

### Current behavior:

Currently you can only specify one controller per input:

controller = "tcp://localhost:502"

### Desired behavior:

Possibility to specify array of "controllers" per input:

controller = [ 
  "tcp://192.168.1.2:502",
  "tcp://192.168.2.5:502",
  ...
  ]

Also add controller hostname as "agent_host" tag to measurement

### Use case: 

Useful if you have many similar controllers

**Comment by sjwang90** [comment]
Closing in favor of #7523
