### ISSUE TITLE
Multiple CA file support

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#7067]
## Feature Request

Enable Telegraf to support multiple CA files.

### Proposal:
Enable Telegraf to support the use of multiple CA files.

### Current behavior:
I have two separate ca.pem files that I want to use inside of Telegraf. One is for Cisco-MDT input plugin for Cisco routers and the other is for Kafka output plugin. When I configure each plugin to point to their respective CA files, my Input plugin always fails and cannot validate the CA but output plugin works and is able to validate the CA. If I disable TLS in my output plugin then my input plugin starts working correctly and is able to validate the CA, but of course, I cannot connect to my Kafka cluster any longer since I disabled TLS.

### Desired behavior:
I would like to be able to specify more than one CA file in my Telegraf conf file.

### Use case: 
I cannot collect data if I cannot use separate CA files simultaneously.

**Comment by danielnelson** [comment]
This should already be working, can you share your configuration file?

**Comment by mohsin106** [comment]
Config is below. Not sure if this might be related to this issue but I
recompiled Telegraf using the MDT plugging from here
<https://github.com/ios-xr/telegraf-plugin/tree/master/plugins/inputs/cisco_telemetry_mdt>
since
this version supports dial-in and the one that currently ships with
Telegraf does not. So I'm not sure if the issue lies in the older version
of the Cisco MDT plugin which I'm using or Telegraf.

[global_tags]
[agent]
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_interval = "1m"
  flush_jitter = "5s"
  debug = false
  quiet = false
  hostname = "hub-gain-telegraf-agent"
  omit_hostname = false


[[inputs.cisco_telemetry_mdt]]
  ## Telemetry transport (one of: tcp-dialout, grpc-dialout, grpc-dialin)
  transport = "grpc-dialin"
  service_address = "ROUTER01.mgt.net:50051"
  username = "$routeruser"
  password = "$routerpass"
  subscription = "Interfaces"
  redial = "10s"
  tls = true
  tls_ca = "/etc/telegraf/ca.pem"
  insecure_skip_verify = false

[[inputs.cisco_telemetry_mdt]]
  ## Telemetry transport (one of: tcp-dialout, grpc-dialout, grpc-dialin)
  transport = "grpc-dialin"
  service_address = "ROUTER02.mgt.net:50051"
  username = "$routeruser"
  password = "$routerpass"
  subscription = "Interfaces"
  redial = "10s"
  tls = true
  tls_ca = "/etc/telegraf/ca.pem"
  insecure_skip_verify = false

[[outputs.kafka]]
  brokers = ["dukebdpc3501.corp.cox.com:9093", "
dukebdpc3502.corp.cox.com:9093", "dukebdpc3503.corp.cox.com:9093", "
dukebdpc3504.corp.cox.com:9093", "dukebdpc3505.corp.cox.com:9093"]
  topic = "hub-clean-json-interfaces-test"
  compression_codec = 1
  required_acks = 1
  data_format = "json"
  max_retry = 3
  enable_tls = true
  tls_ca = "/etc/telegraf/ca.pem"
  tls_cert = "/etc/telegraf/user.cer"
  tls_key = "/etc/telegraf/user-priv.key"
  insecure_skip_verify = false

[[outputs.kafka]]
  brokers = ["dukebdpc3501.corp.cox.com:9093", "
dukebdpc3502.corp.cox.com:9093", "dukebdpc3503.corp.cox.com:9093", "
dukebdpc3504.corp.cox.com:9093", "dukebdpc3505.corp.cox.com:9093"]
  topic = "hub-clean-influx-interfaces-test"
  compression_codec = 1
  required_acks = 1
  data_format = "influx"
  max_retry = 3
  enable_tls = true
  tls_ca = "/etc/telegraf/ca.pem"
  tls_cert = "/etc/telegraf/user.cer"
  tls_key = "/etc/telegraf/user-priv.key"
  insecure_skip_verify = false

**Comment by danielnelson** [comment]
I may have misunderstood, I thought you had two different `ca.pem` files for the input and output, but the plugins are both referencing the same file:

```toml
[[inputs.cisco_telemetry_mdt]]
  tls = true
  tls_ca = "/etc/telegraf/ca.pem"
  insecure_skip_verify = false

[[outputs.kafka]]
  tls_ca = "/etc/telegraf/ca.pem"
  tls_cert = "/etc/telegraf/user.cer"
  tls_key = "/etc/telegraf/user-priv.key"
  insecure_skip_verify = false
```

**Comment by mohsin106** [comment]
Actually, after testing a bit further I realized that I miss
interpreted the error message Telegraf was throwing. Currently, it appears
I have an issue with the CA being used on my Cisco Router. This request can
be closed.

Thank you,
Mo
