### ISSUE TITLE
Folder/File Age Plugin

### ISSUE THREAD

**Issue by iiidddaaannn102** [influxdata/telegraf#7075]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Linux + Windows Folders\Files(Path) Age in Days,Hours,Minutes, And Seconds.

### Current behavior:
There is filestat plugin but it gives the datetime that the folder was changed.

### Desired behavior:
Adding New Plugin or Add Field To filestat plugins that give the age of the folder or file in Days,Hours,Minutes and seconds

### Use case: 
its important for monitoring Folders and files Age, if They are updated.

example:
path_age,days=1.3,hours=28.4,minutes=1590,seconds=131344535.13 path="/var/log/dir"
path_age,days=1.3,hours=28.4,minutes=1590,seconds=131344535.13 path="/var/log/dir/xxx.file"

**Comment by danielnelson** [comment]
We would accept a pull request to add the birth time to the filestat plugin as a integer time field, like: `birth_time=1507152973123456789i`.

This won't be entirely trivial, for unix we would probably need to call [statx](https://godoc.org/golang.org/x/sys/unix#Statx), and keep in mind that many filesystems to not store birth time at all, it doesn't appear to be set with ext4.  I'm unsure what would need to be done on Windows.

**Comment by steverweber** [comment]
yes the filestat Input plugin could use something like:

```
fields["modification_time"] = fileInfo.ModTime().UnixNano()
fields["modification_time_delta_seconds"] = datetime.now().Unix() - fileInfo.ModTime().Unix()
```

untill then.. i'll just hack something together in the shell and use the exec plugin
```
echo "modification_time_delta=$(($(date +%s) - $(date +%s -r /some/file.txt)))"

```

**Comment by srebhan** [comment]
@iiidddaaannn102 and @steverweber I would expect this to be done in the query, however getting the delta is already possible using the [starlark processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark):

```toml
[[inputs.filestat]]
  files = ["telegraf"]

[[processors.starlark]]
  namepass = ["filestat"]
  source = '''
def apply(metric):
  metric.fields["last_modified_ns"] = metric.time - metric.fields["modification_time"]
  return metric
'''
```
producing
```text
> filestat,file=telegraf,host=Hugin exists=1i,last_modified_ns=577784114335i,modification_time=1714743115215885665i,size_bytes=329055915i 1714743693000000000
```

Closing this issue as the above works. Feel free to reopen or open a new issue if this is not what you intended!
