### ISSUE TITLE
External plugins fail to compile on InfluxDB dependency

### ISSUE THREAD

**Issue by veorlo** [influxdata/telegraf#7076]
### System info:
CentOS Linux release 7.7.1908 (Core)
Golang version 1.13
Telegraf version latest

### Steps to reproduce:
1. Create a basic output plugin [as outlined in the documentation](https://github.com/influxdata/telegraf/blob/master/docs/OUTPUTS.md) called "foobar.go", ensuring the required imports from telegraf are included.
2. Attempt to compile the file as a Go plugin by running `go build -buildmode=plugin foobar.go`

### Expected behavior:
The code should compile to a Go plugin in .so format, successfully importing from telegraf and telegraf/outputs as is needed.

### Actual behavior:
Compiling the code leads to [the error mentioned here](https://github.com/influxdata/influxdb/issues/16901) when Telegraf attempts to import influxdb assets during the build process and fails due InfluxDB v1.7.10 requiring the wrong version of go-github.

### Additional information:
Perhaps I've misunderstood the development specs for the `--external-plugins` feature and there's a better way that I've not yet found. If not, this issue would likely break the ability to compile plugins for use by the feature.

**Comment by danielnelson** [comment]
The go-plugins support is somewhat experimental, and we are limited in what support we can provide here with respect to compile errors.  Check https://github.com/influxdata/telegraf/issues/7027 for some recent discussion, tips, and things to look out for.
