### ISSUE TITLE
openshift Monitoring 

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7080]
Hi Team,

Is there any plugin to monitor Openshift containerization

**Comment by danielnelson** [comment]
We don't have any OpenShift specific plugins, but you may be able to use the `kubernetes`, `kube_inventory`, and `prometheus` plugins within OpenShift.  It would be really interesting to hear about any setups or strategies the community has around OpenShift monitoring.  
We try to reserve GitHub Issues for actionable bug reports or feature requests, perhaps you could ask at the [InfluxData Community](https://community.influxdata.com) site.

I'd like to keep the issue tracker more focused on specific work tasks so I'm going to close this issue.

@russorat @sjwang90 I think this would be an interesting topic of research.
