### ISSUE TITLE
how to send something in case of timeout

### ISSUE THREAD

**Issue by Bandudu** [influxdata/telegraf#7081]
Hi all,

I'm trying to save a value in case of timeout. 

I mean, i have configured this input
 ```
[[inputs.http]]
#   ## One or more URLs from which to read formatted metrics
   urls = [
   "http://localhost:8080"
]
    interval= "30s"
#   ## HTTP method
    method = "GET"

 timeout = "5s"

```

In case of my webserver is shutdown, i cannot see anything in my dashboard, and i would like to see a value (whatever) in order to know that is a timeout. 

Is it possible?

**Comment by M0rdecay** [comment]
You can try to use [http_response plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response).

**Comment by danielnelson** [comment]
Another option is to enable the `internal` input, this will report per plugin errors like:
```
internal_gather,host=loaner,input=http,version=1.13.4 errors=2i,gather_time_ns=482516i,metrics_gathered=0i 1582658560000000000
```

We fixed an issue with the internal plugin today, if you use this method you will want to grab 1.13.4 once it is released.
