### ISSUE TITLE
internal gather does not work

### ISSUE THREAD

**Issue by rlex** [influxdata/telegraf#7083]
### Relevant telegraf.conf:
N/A, internal metric

### System info:

Debian 10, Telegraf 1.13.2 (git: HEAD 6dad859d)

### Steps to reproduce:

Break any plugin (ie run systemd_units on system w/o systemd)

### Expected behavior:

SELECT mean("errors") FROM "internal_gather" WHERE ("input" = 'systemd_units') AND $timeFilter GROUP BY time($__interval) fill(null) should return value > 0

### Actual behavior:

SELECT mean("errors") FROM "internal_gather" WHERE ("input" = 'systemd_units') AND $timeFilter GROUP BY time($__interval) fill(null) always return 0

### Additional info:

internal_agent gather_errors works and shows gather errors, but per-plugin internal_gather do not.

**Comment by ssoroka** [comment]
Thanks for the bug report!

gather_errors is a global metric that's collected across all inputs. 

I've tested locally with this config and I do get input-specific errors from internal_gather. Here's an example: 
```
internal_gather,host=me.local,input=procstat,version=unknown errors=20i,metrics_gathered=20i,gather_time_ns=96471i 1582646190000000000
```

I'd need to see your specific config for systemd_units to know if the input name in your query is correct. Let me know what you think.

Thanks

**Comment by M0rdecay** [comment]
You can try to use [http_response plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response).

**Comment by ssoroka** [comment]
Thanks! We've managed to reproduce the problem locally and I've committed a fix for this (https://github.com/influxdata/telegraf/pull/7077). 

It will be in the 1.13.4 release. 

Thanks!
