### ISSUE TITLE
Option to Push last/first series or last/first two series of data.

### ISSUE THREAD

**Issue by anrav** [influxdata/telegraf#7092]
## Feature Request
Option to Push last/first series or last/first two series of data.

### Proposal:
We are collecting real time metrics(20s) for vsphere.
Data is only needed for 5th minute real time metric. 
300 sec data pushed to database and ignore remaining all data collected. 

### Current behavior:
All collected data is being pushed.

### Desired behavior:
Push only 1 or 2 series based on configurable option

### Use case: 

Real time metrics reflect in UI.
Not able to view them with historic metrics.
If we collect and hold data, DB is getting piled up quickly.

**Comment by danielnelson** [comment]
You can use the `interval` option to control how frequently the plugin will collect data:
```toml
[[inputs.vsphere]]
  interval = "300s"
```
