### ISSUE TITLE
Cisco mdt input plugin does not export all data received by gRPC

### ISSUE THREAD

**Issue by tcellier** [influxdata/telegraf#7093]
Hello Telegraf folks,

I recently encountered an issue with the Telegraf input cisco-mdt-input plugin. 
Telegraf receives informations but only push some parts of it into it's outputs.

I'am trying to implement the Telemetry feature on Cisco routers and switchs. I stream data with gRPC encoding GPB to port 50003 of my collector.
The collection stack is made of Telegraf, InfluxDB and Grafana.

### Relevant telegraf.conf:
```
[[inputs.cisco_telemetry_mdt]]
 transport = "grpc"
 service_address = ":50003"

embedded_tags = ["Cisco-NX-OS-device:System/procsys-items/sysload-items/name", "Cisco-NX-OS-device:System/procsys_items/sysmem_items/sysmemfree_items/name","Cisco-NX-OS-device:System/intf-items/phys-items"]

[[outputs.influxdb]]
database = "telemetry"
urls = [ "http://127.0.0.1:8086" ]
username = "admin"
password = "*********"

[[outputs.file]]
  files = ["/tmp/metrics.out"]
  data_format = "json"
```

Cisco Telemetry Configuration :
```
version 9.3(3) Bios:version 05.39
feature telemetry

telemetry
  destination-profile
    use-vrf management
  destination-group 100
    ip address 10.204.5.42 port 50003 protocol gRPC encoding GPB
    ip address 10.204.5.55 port 5443 protocol HTTP encoding JSON
  sensor-group 100
    data-source YANG
    path Cisco-NX-OS-device:System/intf-items
    path Cisco-NX-OS-device:System/intfTable-items/intf-items
    path openconfig-interfaces:interfaces/interface
  subscription 100
    dst-grp 100
    snsr-grp 100 sample-interval 1000
```

### System info:

OS : Ubuntu 18.04
Telegraf Version : 13.4.1

### Steps to reproduce:

1. Configure a Cisco NX-OS (maybe it occures on XR devices too) to stream telemetry (especially interfaces data) directly on telegraf's input plugin. 
2. Configure Telegraf's intput and ouput to extract received data into a JSON file.
3. Read the output file.

### Expected behavior:

We are expecting to find the data of **each** Cisco IOS's interfaces. We should have a JSON file full of data concerning each nics, like they're "name", "vlan" or "speed" for exemple.

### Actual behavior:

When I take a look at the JSON output file to check what Telegraf just received, I can only find data concerning "mgmt0" nic.  No other interfaces can be found on json output file.
All interfaces are exported from the nexus device into one grpc batch request.
After opening a case to Cisco's TAC support, we find out that all metrics were exported by the network device, but Telegraf only process the last occurence of the data (Cisco Tac guy affirmation). Maybe it's related to a loop erasing the previous data. My golang skills are very limited so i can't undestand the real problem by myself.

### Additional info:

Cisco IOS version used :
IOS NX-OS 9.3.3

**Comment by Jay-T** [comment]
I am the "Cisco Tac guy" :) Have similar behavior in similar deployment also. In GPB sent by device I can see all interfaces with metrics inside (checking in Wireshark output). Ready for co-operate.

**Comment by danielnelson** [comment]
Is it possible to upload the wireshark captures?

cc @sbyx

**Comment by Jay-T** [comment]
Here couple of gRPC messages.
Only Xpath that is configured on device: openconfig-interfaces:interfaces/interface.
[telemetry.pcap.zip](https://github.com/influxdata/telegraf/files/4270043/telemetry.pcap.zip)

**Comment by sbyx** [comment]
The issue comes from the fact that the device does not declare the interface ID as a tag, and therefore the plugin cannot know what is actually a unique measurement and what is not. The plugin does not know the structure of the data model and which fields in there are supposed to be keys because it cannot know all possible data models of all platforms, OSes, OS versions etc.

So what happens is that all measurements are merged into one another due to the missing distinction by a key / tag. Thus you have to work-around by using the embedded_tags option.

**Note: there was a bug in embedded_tags feature which I recently submitted a fix for so please try the solution below with a nightly build of Telegraf.**

Now there seems to be another catch related to NX-OS here in that even though it declares the measurement coming with e.g. "Cisco-NX-OS-device:System/intf-items" it nevertheless repeats the "System/intf-items" part in the data. I did a quick test with this sensor path and it seems one field to distinguish the measurements by interface could be: "System/intf_items/phys_items/PhysIf_list/id" since it seems to contain the interface name. Thus for the sensor path above and a config containing:

"Cisco-NX-OS-device:System/intf-items/System/intf_items/phys_items/PhysIf_list/id"
If I do this I am getting the measurements split-up by interface as expected. Note that I did not check if there could be other hidden keys further down below in the data tree.

Note that there is special handling code for NX-API and DME type sensor groups from NX-OS in the plugin which should detect keys based on some indications in the data structure so using one of the two could be a work-around if you do not want to cook embedded_tags for your use case.

**Comment by tcellier** [comment]
Hello @sbyx, thanks for your reply.

I tried your solution, without any effect. The add of the path into the embedded_tags files doesnt works. The "id" is still unrecognize as tag.


```
 ## Define (for certain nested telemetry measurements with embedded tags) which fields are tags
 embedded_tags = [
        "Cisco-NX-OS-device:System/procsys-items/sysload-items/name",
        "Cisco-NX-OS-device:System/procsys_items/sysmem_items/sysmemfree_items/name",
        "Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/id",
]
```
Telegraf only export "mgmt0" and "eth1/24".

To be sure, i verified the path into the officiel YANG file for NX-OS 9.3.3, but this issue doesn't come from any syntax error.

Since this morning, telegraf runs with the last nightly telegraf version.

Note : Already tried DME, but it doesn't suit our needs.

Here is an extract from the telegraf output :
(I cut a lot of useless infos in order for it to be more readable )

```
{
  "fields": { 
    "System/intf_items/phys_items/PhysIf_list/duplex": "auto",
    "System/intf_items/phys_items/PhysIf_list/eeep_items/eeeLat": "variable",
    "System/intf_items/phys_items/PhysIf_list/eeep_items/eeeLpi": "aggressive",
    "System/intf_items/phys_items/PhysIf_list/eeep_items/eeeState": "not-applicable",
    "System/intf_items/phys_items/PhysIf_list/hwifdetails_items/sPort": 59,
    "System/intf_items/phys_items/PhysIf_list/hwifdetails_items/slice": 0,
    "System/intf_items/phys_items/PhysIf_list/hwifdetails_items/vif": 93,
    "System/intf_items/phys_items/PhysIf_list/id": "eth1/24",
    "System/intf_items/phys_items/PhysIf_list/inhBw": 4294967295,
    "System/intf_items/phys_items/PhysIf_list/layer": "Layer3",
    "System/intf_items/phys_items/PhysIf_list/linkDebounce": 100,
    "System/intf_items/phys_items/PhysIf_list/linkDebounceLinkUp": 0,
    "System/intf_items/phys_items/PhysIf_list/linkLog": "default",
},
  "name": "Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list",
  "tags": {
    "Cisco_NX_OS_device:System/intf_items/phys_items/PhysIf_list": "Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list",
    "host": "telemetrycollector",
    "path": "Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list",
    "source": "ls01.mar02.lab",
    "subscription": "100"
  },
  "timestamp": 1583158929
```

**Comment by sbyx** [comment]
Hi @tcellier please note that embedded_tag must be formed by the measurement "name" followed by a "/" followed by the field name as given in fields, so I would advise to retry with:

**Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/System/intf_items/phys_items/PhysIf_list/id**

This is a quirk that I mentioned above that NX-OS (in contrast to IOS XR and XE) repeats the full path inside the field names again.

**Comment by Jay-T** [comment]
embedded_tags = ["openconfig-interfaces:interfaces/interface/interfaces/interface/name"] 
That is how it works for me. Now I can see all interfaces parsed from incoming gRPC data. This is really weird. Thanks for the information. Will try to play with IOS-XE device with same YANG model.

**Comment by tcellier** [comment]
Thanks guys for your help. Here is the configuration we applied :

```
[[inputs.cisco_telemetry_mdt]]
 transport = "grpc"
 service_address = ":50003"
 embedded_tags = ["Cisco-NX-OS-device:System/procsys-items/sysload-items/name", "Cisco-NX-OS-device:System/procsys_items/sysmem_items/sysmemfree_items/name", "openconfig-interfaces:interfaces/interface/interfaces/interface/name"]
 [inputs.cisco_telemetry_mdt.aliases]
   ifstats = "openconfig-interfaces:interfaces/interface"

[[outputs.influxdb]]
database = "telemetry"
urls = [ "http://127.0.0.1:8086" ]
username = "admin"
password = "********"
 ```
For the embedded_tags, the paths are built from the measurements path followed by the field name :

embedded_tags = ["Cisco-NX-OS-device:<measurement_path>/<field_name>"]

The last issue encountered came from the aliases setup part (which was missing ) :
```
 [inputs.cisco_telemetry_mdt.aliases]
   ifstats = "openconfig-interfaces:interfaces/interface"
```
Concerning NX-OS, Telemetry is configured as followed :
```
ls01.mar02.lab# show run tel

!Command: show running-config telemetry
!Running configuration last done at: Tue Mar  3 08:52:26 2020
!Time: Tue Mar  3 09:38:08 2020

version 9.3(3) Bios:version 05.39
feature telemetry

telemetry
  destination-profile
    use-vrf management
  destination-group 100
    ip address 10.204.5.42 port 50003 protocol gRPC encoding GPB
  sensor-group 100
    data-source YANG
    path openconfig-interfaces:interfaces/interface
  subscription 100
    dst-grp 100
    snsr-grp 100 sample-interval 1000
```
It works fine now. Just need to apply the same method to the others unrecognized tags !
