### ISSUE TITLE
Allow Grouping by tag(s)

### ISSUE THREAD

**Issue by TheGreatYamcha** [influxdata/telegraf#7096]
## Feature Request
I'd like to group by tag(s) before performing aggregation functions (like max, mean)
I don't know before hand what the value(s) of the tags can be, so metric filtering won't work.
### Proposal:
Either create a processor that does grouping or support grouping by tag(s) in the BasicStats aggregator.

### Use case: 
We use telegraf in front of influx to aggregate data from millions of clients before sending data to influx (otherwise, there'd be too many writes for influx to handle). In the current setup, we can't group by any tags, so all tags are lost (meaningless) when using the BasicStats aggregator.

**Comment by danielnelson** [comment]
I find the `group by` terminology to be a little confusing, but the `basicstats` aggregator actually does a `group by *` tags by default.  It looks to help at an example:

If you send it data like:
```
net,host=a recv_byte=42i
net,host=a recv_byte=42i
net,host=b recv_byte=42i
net,host=b recv_byte=42i
```

Then you use the sum aggregation, you will get:
```
net,host=a recv_byte=84i
net,host=b recv_byte=84i
```

The two hosts haven't been combined, each series is in it's own group.

Often, it would be helpful to ungroup though, and you can do this by removing the tag with `tagexclude`.  If you remove the host tag in the example above the aggregator will see data like:
```
net recv_byte=42i
net recv_byte=42i
net recv_byte=42i
net recv_byte=42i
```

Then when you aggregate you will get:
```
net recv_byte=168i
```

Let me know if this helps, or if I've missed your point then perhaps you can show me an example to clarify.

**Comment by TheGreatYamcha** [comment]
This helps. Although it'd be a lot simpler if the aggregator had a configuration for array of tags to group by.
