### ISSUE TITLE
MySQL doc should also list MariaDB

### ISSUE THREAD

**Issue by alsargent** [influxdata/telegraf#7099]
_Describe the issue here._

The doc/github page https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql doesn't have any mention that this plugin works for MariaDB. It does work (@ssoroka tested it last night), so please say so on this page.

##### Relevant URLs
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql

**Comment by danielnelson** [comment]
I'd like to start recording information about the supported versions of services in the README similar to what we recently did in the Kibana input: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kibana

We should add this recommendation to the example readme https://github.com/influxdata/telegraf/blob/master/plugins/inputs/EXAMPLE_README.md

**Comment by sjwang90** [comment]
@alsargent Going to add the MariaDB & Percona support into our docs page under the MySQL plugin.  MySQL input README is pretty metrics focused
