### ISSUE TITLE
system/net plugin counters wrap

### ISSUE THREAD

**Issue by lassizci** [influxdata/telegraf#710]
system/net plugin seems to rely on 32 bit byte counter on bytes_sent/bytes_recv. I'm trying to draw a graph with Grafana using derivative function, but with high speeds the counter wraps quite often. Is there a way to deal with that?

**Comment by sparrc** [comment]
according to gopsutil it's 64-bit: https://github.com/shirou/gopsutil/blob/master/net/net.go

they even use uint64, although that's not supported in influx

**Comment by sparrc** [comment]
@lassizci what value is it wrapping at? Should be at 2^63 == 9223372036854775807

**Comment by lassizci** [comment]
I came to conclusion as I got negative values from derivative. But now looking at the actual values from influxdb, they indeed are bigger than 32 bit, so I made a hasty judgement here.

**Comment by sparrc** [comment]
oh, maybe you want to use the [non negative derivative function?](https://docs.influxdata.com/influxdb/v0.10/query_language/functions/#non-negative-derivative)

**Comment by lassizci** [comment]
Not entirely sure it gives correct results either when trying to get a single value for total data rate of multiple hosts. Would need something like sum of derivatives, but until that's supported, I think it would be possible to create continuous queries to calclulate the derivatives and take a sum out of those.
