### ISSUE TITLE
Telegraf frequently goes in Panic mode due to - fatal error: concurrent map writes 

### ISSUE THREAD

**Issue by sakshi-bansal** [influxdata/telegraf#7101]
### Relevant telegraf.conf:
[inputs.ntpq]

### System info:
Telegraf version: 1.13.4
Go Version: 1.13.8

### Steps to reproduce:

1. Install telegraf 
2. Start the service

### Expected behavior:
Continuous working of telegraf

### Actual behavior:
Telegraf goes in panic state and stops 

fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 3184 [running]:
runtime.throw(0x27d9597, 0x15)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00053dc90 sp=0xc00053dc60 pc=0x4313e2
runtime.mapassign_faststr(0x22108a0, 0xc0001035c0, 0x27ac8f4, 0x6, 0xc00002a748)
        /usr/local/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc00053dcf8 sp=0xc00053dc90 pc=0x4152de
github.com/influxdata/telegraf/plugins/inputs/ntpq.(*NTPQ).Gather(0xc00054b450, 0x2ca8f00, 0xc0003e4200, 0x34, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ntpq/ntpq.go:104 +0x1244 fp=0xc00053df18 sp=0xc00053dcf8 pc=0x162e9f4
github.com/influxdata/telegraf/internal/models.(*RunningInput).Gather(0xc000362c80, 0x2ca8f00, 0xc0003e4200, 0x97d1000, 0x0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_input.go:115 +0x6d fp=0xc00053df78 sp=0xc00053df18 pc=0x7e69ad
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc000434240, 0xc000362c80, 0x2ca8f00, 0xc0003e4200)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:336 +0x3f fp=0xc00053dfc0 sp=0xc00053df78 pc=0x98e90f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00053dfc8 sp=0xc00053dfc0 pc=0x4615c1
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /go/src/github.com/influxdata/telegraf/agent/agent.go:335 +0xf5

### Additional info:
Possible issue with Golang https://github.com/golang/go/issues/35317

**Comment by ssoroka** [comment]
Thanks for the bug report! This is a bug in the ntpq implementation. It should not be sharing state. I can patch this up for you.
