### ISSUE TITLE
Telegraf excluding global tags when using tagsinclude

### ISSUE THREAD

**Issue by Dileep-Dora** [influxdata/telegraf#7102]
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md
Refer tagsinclude

```
[global_tags]
  dc = "us-east-1" # will tag all metrics with dc=us-east-1
  rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  user = "$USER"


[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  taginclude = ["cpu"]
  report_active = false
```

### System info:

Telegraf version 1.13.2, for other versions, also happening the same

### Steps to reproduce:

1. Set some global tags
2. Add tagsinclude option in a specific input
3. Start telegraf service
4. Check in influxdb for tags

### Expected behavior:

Expected that it should merge the `global_tags` and `tagsinclude`.

### Actual behavior:

Its ignoring global tags.

### Additional info:

For the above config when I checked in the console it's showing only tags from tagsinclude specified in the input plugin.
```> show tag keys from cpu
name: cpu
tagKey
------
cpu
```

**Comment by danielnelson** [comment]
We probably wouldn't adjust this due to the disruption it would cause, but you could use the override processor to add the tags instead of global tags:
```toml
[[processors.override]]
  [processors.override.tags]
    dc = "us-east-1"
    rack = "1a"
    user = "$USER"
```
