### ISSUE TITLE
Ability to set http header values in the http_listener_v2 as tags

### ISSUE THREAD

**Issue by dneray** [influxdata/telegraf#7105]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
I would like to be able to use http headers in the http_listener_v2 as tags in the metric data.

### Desired behavior:
Something like this would work for me:

http_header_tags = {"SOME_HTTP_HEADER" = "MEASUREMENT_TAG_NAME"}

### Use case: 
I have a system where edge devices are communicating with a reverse proxy that handles authentication and the traffic is being forwarded to telegraf. 

Device ----> Reverse Proxy ----> Telegraf ----> Influxdb

For my use case, I would like to pass an identifier for the device from the reverse proxy. It's difficult to perform this kind of transformation in the reverse proxy through modifying the payload but it's easy to pass an http header so it would be convenient if I could do this transformation in telegraf.

**Comment by danielnelson** [comment]
I think this would be a good addition, we are about to make a fairly large update to this plugin in #6974 but after that pr is merged would you be able to work on it?

**Comment by dneray** [comment]
Yes, I have implemented it locally and will push after I finish testing but I will wait to open a PR until after #6974 is finished so that I can handle the conflicts myself.

Thanks!

**Comment by dneray** [comment]
Have implemented my change here https://github.com/dneray/telegraf now just waiting for #6974 to open the pr
