### ISSUE TITLE
Huawei Routers Telemetry Input Plugin

### ISSUE THREAD

**Issue by DamRCorba** [influxdata/telegraf#7107]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
I want to capture Huawei Routers Telemetry interface

### Current behavior:
Not exist
### Use case: 
There is no input Plugin for Huawei Routers Telemetry

**Comment by DamRCorba** [comment]
I have already done and test the plugin. I want to push it but i have no rights. Any help?

**Comment by danielnelson** [comment]
You will want to create a fork, push the branch to your fork, and open the PR from there.

**Comment by DamRCorba** [comment]
Done

**Comment by DamRCorba** [comment]
something goes wrong. 

#!/bin/bash -eo pipefail
make tidy

go mod verify
all modules verified
go mod tidy
go: finding github.com/DamRCorba/huawei_telemetry_sensors latest
go: downloading github.com/DamRCorba/huawei_telemetry_sensors v0.0.0-20200303204802-9d9cdfdbfa02

Exited with code exit status 2
go: extracting github.com/DamRCorba/huawei_telemetry_sensors v0.0.0-20200303204802-9d9cdfdbfa02
please run go mod tidy and check in changes
make: *** [Makefile:90: tidy] Error 1

**Comment by DamRCorba** [comment]
I have some problems with the test script. I have the plugin running localy and it works fine. but when i try to run the test it saids: 
```
    accumulator.go:365: 
        	Error Trace:	accumulator.go:365
        	            				huawei_routers_telemetry_test.go:28
        	Error:      	unknown measurement huawei-devm:devm/cpuInfos/cpuInfo with tags map[path:huawei-devm:devm/cpuInfos/cpuInfo position:"9" source:HuaweiTest1 subscription:ProbandoTelemetriaSubscripcion]
        	Test:       	TestHandleTelemetryHuawei
```
and in my local influx
```
SHOW MEASUREMENTS
name: measurements
name
----
huawei-devm:devm/cpuInfos/cpuInfo

```

And if i print the metric i have
```
huawei-devm:devm/cpuInfos/cpuInfo map[path:huawei-devm:devm/cpuInfos/cpuInfo position:"8" source:HuaweiTest1 subscription:ProbandoTelemetriaSubscripcion] map[entIndex:17301505 interval:8 ovloadThreshold:90 systemCpuUsage:16 unovloadThreshold:75] 1583353977163000000
```

i dont know what i missing.

**Comment by DamRCorba** [comment]
I put a println of the metric in the test execution and this happens.

```
ok  	github.com/influxdata/telegraf/plugins/inputs/httpjson	0.011s
2020/03/04 21:23:29 I! [] Listening on udp://[::]:5600
huawei-devm:devm/cpuInfos/cpuInfo map[path:huawei-devm:devm/cpuInfos/cpuInfo position:"9" source:HuaweiTest1 subscription:ProbandoTelemetriaSubscripcion] map[entIndex:17367041 interval:8 ovloadThreshold:90 systemCpuUsage:10 unovloadThreshold:75]
--- FAIL: TestHandleTelemetryHuawei (0.00s)
    accumulator.go:365: 
        	Error Trace:	accumulator.go:365
        	            				huawei_routers_telemetry_test.go:32
        	Error:      	unknown measurement huawei-devm:devm/cpuInfos/cpuInfo with tags map[path:huawei-devm:devm/cpuInfos/cpuInfo position:"9" source:HuaweiTest1 subscription:ProbandoTelemetriaSubscripcion]
        	Test:       	TestHandleTelemetryHuawei
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/huawei_routers_telemetry	0.009s
```
Any clue?

**Comment by DamRCorba** [comment]
this is my test code
```golang
func TestHandleTelemetryHuawei(t *testing.T) {
	h := &HuaweiRoutersTelemetry{Log: testutil.Logger{}, ServicePort: "5600"}
	acc := &testutil.Accumulator{}
	err := h.Start(acc)
	if err != nil {
		require.Error(t, err)
	}

	packet := []byte{0x00, 0x00, 0x01, 0xe2, 0x5e, 0x44, 0x60, 0x80, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x0b, 0x48, 0x75, 0x61, 0x77, 0x65, 0x69, 0x54, 0x65, 0x73, 0x74, 0x31, 0x12, 0x1e, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x61, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x1a, 0x21, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x2d, 0x64, 0x65, 0x76, 0x6d, 0x3a, 0x64, 0x65, 0x76, 0x6d, 0x2f, 0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x2f, 0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x20, 0xe9, 0xcf, 0x02, 0x28, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x30, 0xbf, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x3a, 0xda, 0x02, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x39, 0x08, 0x81, 0x80, 0xa4, 0x08, 0x28, 0x0a, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1e, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x15, 0x2a, 0x13, 0x0a, 0x11, 0x22, 0x02, 0x31, 0x30, 0x08, 0x81, 0x80, 0xa8, 0x08, 0x28, 0x06, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1e, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x15, 0x2a, 0x13, 0x0a, 0x11, 0x22, 0x02, 0x31, 0x31, 0x08, 0x81, 0x80, 0xac, 0x08, 0x28, 0x03, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1e, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x15, 0x2a, 0x13, 0x0a, 0x11, 0x22, 0x02, 0x31, 0x32, 0x08, 0x81, 0x80, 0xb0, 0x08, 0x28, 0x02, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1e, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x15, 0x2a, 0x13, 0x0a, 0x11, 0x22, 0x02, 0x31, 0x33, 0x08, 0x81, 0x80, 0xb4, 0x08, 0x28, 0x03, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1e, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x15, 0x2a, 0x13, 0x0a, 0x11, 0x22, 0x02, 0x31, 0x34, 0x08, 0x81, 0x80, 0xb8, 0x08, 0x28, 0x03, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x35, 0x08, 0x81, 0x80, 0x94, 0x08, 0x28, 0x12, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x34, 0x08, 0x81, 0x80, 0x90, 0x08, 0x28, 0x10, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x31, 0x08, 0x81, 0x80, 0x84, 0x08, 0x28, 0x2a, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x37, 0x08, 0x81, 0x80, 0x9c, 0x08, 0x28, 0x29, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x0a, 0x1d, 0x08, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x5a, 0x14, 0x2a, 0x12, 0x0a, 0x10, 0x22, 0x01, 0x38, 0x08, 0x81, 0x80, 0xa0, 0x08, 0x28, 0x0e, 0x18, 0x5a, 0x30, 0x4b, 0x10, 0x08, 0x40, 0x87, 0xab, 0xa2, 0xd9, 0x83, 0x2e, 0x48, 0x90, 0x4e, 0x52, 0x02, 0x4f, 0x4b, 0x5a, 0x05, 0x4e, 0x45, 0x34, 0x30, 0x45, 0x60, 0x00}

	grouper := HuaweiTelemetryDecoder(packet)
	acc.AddMetric(grouper.Metrics()[0])

	cosa, valida := acc.Get("huawei-devm:devm/cpuInfos/cpuInfo")
	if valida == true {
		fmt.Println(cosa)
	}

	require.Empty(t, acc.Errors)

	tags := map[string]string{"path": "huawei-devm:devm/cpuInfos/cpuInfo", "position": "\"9\"", "source": "HuaweiTest1", "subscription": "ProbandoTelemetriaSubscripcion"}
	fields := map[string]interface{}{"entIndex": uint32(17367041), "interval": uint32(8), "ovloadThreshold": uint32(90), "systemCpuUsage": uint32(10), "unovloadThreshold": uint32(75)}
	acc.AssertContainsTaggedFields(t, "huawei-devm:devm/cpuInfos/cpuInfo", fields, tags)
}
```

the println prints the acc saved, i think. But the assert function fails.

**Comment by danielnelson** [comment]
Instead of using acc.AssertContainsTaggedFields use `testutil.RequireMetricsEqual(`, it has somewhat better error messages.

**Comment by DamRCorba** [comment]
thanks. it finaly work

**Comment by rudigerlove** [comment]
Hi, 
is this plugin finally on the main thread?
thanks

**Comment by vijayahire07** [comment]
waiting for it :-) 👍

**Comment by sspaink** [comment]
Looks like the plugin pull request was closed to due lack of activity: https://github.com/influxdata/telegraf/pull/7112

@rudigerlove or @vijayahire07 would one of you perhaps be interested in taking this pull request over to help get it merged?

**Comment by DamRCorba** [comment]
Hi, I stoped working in this pull request because the Huawei telemetry change a lot between router software Versions.

In the very begining, this pluging was for V8R1, and it works fine, it only needs the test units and an update.
I am working on V8R21 plugin right now, the sensors changes a lot. The Telemetry feature is very unstable in huawei routers, many of the sensors not even work. 

In my research, i found in a documentation, a plugin made by Huawei Itself. So i decided to stop coding and wait for a software patch for telemetry issues or/and the plugin publish by Huawei.

**Comment by sspaink** [comment]
@DamRCorba thank you for the update and the work on this issue so far! Do you perhaps have any idea what the timeline could be for Huawei to create a plugin or resolve the telemetry issues?

I am wondering if maybe this plugin would work better as an external plugin seeing there could be such big changes between router versions the Telegraf maintainer team will have a problem keeping it updated.

**Comment by DamRCorba** [comment]
Huawei is working in software patches right now. I hope six month to be running ok.

I am using a JS script that i made to test and store data in Influx because is easier to change the objects. 
May be its easier do a parser instead of a full plugin. I will wait for huawei to fix the routers issues to rewrite the plugin.

**Comment by potato-chip** [comment]
> Hi, I stoped working in this pull request because the Huawei telemetry change a lot between router software Versions.
> 
> In the very begining, this pluging was for V8R1, and it works fine, it only needs the test units and an update. I am working on V8R21 plugin right now, the sensors changes a lot. The Telemetry feature is very unstable in huawei routers, many of the sensors not even work.
> 
> In my research, i found in a documentation, a plugin made by Huawei Itself. So i decided to stop coding and wait for a software patch for telemetry issues or/and the plugin publish by Huawei.

hi, can you  share the document or link obout huawei device?  now i also capture huawei telemetry

**Comment by srebhan** [comment]
Is anyone still interested in this? PR #7112 was abandoned unfortunately...
