### ISSUE TITLE
Make StatsD Plugin Parser Concurrency Level Configurable

### ISSUE THREAD

**Issue by josephpeacock** [influxdata/telegraf#7109]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add a new configuration item for the StatsD input plugin to specify the number of goroutines used.

### Current behavior:

It's hardcoded to 5 goroutines as a constant: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L35

### Desired behavior:

Make this configurable, allowing users to specify their preferred level of concurrency.

### Use case: 

Our team is running telegraf clusters (4 ec2 instances per AWS region) to handle statsD metrics. They are consistently seeing message drops due to a full message queue, logging:

```Error: statsd message queue full. We have dropped 158400000 messages so far. You may want to increase allowed_pending_messages in the config```

with n consistently increasing over the life of the application. Increasing the size of allowed_pending_messages doesn't help, as this is a problem of data inflow outweighing the processing speed of the plugin. 

Due to the fact that our telegraf isn't running alongside our app, we would like run the parser at a higher level of concurrency than is probably common, because we're less sensitive to high CPU/memory consumption. We recognize that this probably isn't a generic enough setup to be worth simply increasing the goroutine constant for everybody. 

We had PR #6922 merged recently, but 5 goroutines are few for our specific use case. Thus we're opening this issue for discussing specifically making this field configurable.

**Comment by ssoroka** [comment]
This sounds reasonable. I'd support that PR. it might also be useful to do some profiling to identify any other bottlenecks. 

There are some instructions here: https://github.com/influxdata/telegraf/wiki/Profiling
I'd be interested to hear what you find.

**Comment by danielnelson** [comment]
Related discussion: https://github.com/influxdata/telegraf/pull/6922

**Comment by sspaink** [comment]
@josephpeacock sorry you haven't had any response in a while, are you still interested in seeing this configuration option added?
