### ISSUE TITLE
Is the "Cisco GNMI Telemetry" plugin Cisco-specific?

### ISSUE THREAD

**Issue by colinmcintosh** [influxdata/telegraf#7114]
### Relevant telegraf.conf:
Not applicable.

### System info:
Not applicable.

### Steps to reproduce:
Not applicable.

### Expected behavior:
Not applicable.

### Actual behavior:
Not applicable.

### Additional info:
I'm reading through the plugins available for gNMI and OpenConfig telemetry and it looks like there is a plugin available called "Cisco GNMI Telemetry". Looking through the code I don't see anything specific to Cisco products and the plugin uses the vendor-agnostic https://github.com/openconfig/gnmi packages.

Is there supposed to be anything specific to Cisco products in this plugin that would prevent supporting other platforms or non-Cisco software? If not I'd like to propose changing the name of this plugin to "GNMI Telemetry" as it would be more clear what the plugin is intended to be used for.

**Comment by russorat** [comment]
@colinmcintosh thanks for bringing this up. Looks like you might be right, but we aren't the experts on gnmi. Have you tried this against another product that uses the gnmi spec? What are the results?

**Comment by colinmcintosh** [comment]
I just tested this out against an Arista router that supports gNMI and I was successfully able to produce metrics using the example configuration in the plugin README. As far as I can see this plugin should support any platform that supports the gNMI spec.

```
2020-03-04T20:52:05Z I! Starting Telegraf
2020-03-04T20:52:05Z I! Loaded inputs: cisco_telemetry_gnmi
2020-03-04T20:52:05Z I! Loaded aggregators:
2020-03-04T20:52:05Z I! Loaded processors:
2020-03-04T20:52:05Z I! Loaded outputs: file
2020-03-04T20:52:05Z I! Tags enabled: host=cm-dev-bionic
2020-03-04T20:52:05Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"cm-dev-bionic", Flush Interval:10s
ifcounters,host=cm-dev-bionic,name=Management1/1,source=<redacted> in_broadcast_pkts=24395358i 1583355129542804010
ifcounters,host=cm-dev-bionic,name=Management1/1,source=<redacted> in_octets=8828149348i 1583355129542791752
ifcounters,host=cm-dev-bionic,name=Ethernet4/16/2,source=<redacted> in_octets=9042186238132521i 158335512891884894
```

**Comment by ryanmerolle** [comment]
I think this should get renamed.  I too agree with @colinmcintosh

**Comment by TechDawg** [comment]
Telegraf is fully working with Nokia SR routers...

**Comment by noredistribution** [comment]
this works fine with any vendor that supports gNMI, gNMI is open-source and plugins shouldn't be named after vendors

**Comment by perimore** [comment]
I agree, this should be renamed in the spirit of openconfig

**Comment by ksator** [comment]
This plugin works with Arista EOS devices (swicthes, containers, ...).

**Comment by dbassani** [comment]
gNMi and Openconfig are the OPEN Networking foundation

**Comment by carlbuchmann** [comment]
+ 1, I agree as well

**Comment by burnyd** [comment]
Should rename as this is a gNMI interface.

**Comment by dbassani** [comment]
Sorry Daniel but I don’t get the point, what should I rename?

—

Davide Bassani
Systems Engineer - EMEA

Arista Networks
Mobile:  +39 342 1531607
Email:   davide@arista.com
Web:     www.arista.com


On 13 Jun 2020, at 18:05, Daniel Hertzberg <notifications@github.com> wrote:

﻿
Should rename as this is a gNMI interface.

**Comment by krikoon73** [comment]
It has to be renamed as a standard gnmi interface because it could be used with all compatible gnmi "streamer" of the market.

**Comment by mpergament** [comment]
+1 it should be renamed to have vendor-agnostic name

**Comment by jorisc90** [comment]
Per their website OpenConfig are a " informal working group of network operators " - reflecting the Telegraf plugin name to reflect this would make perfect sense - +1

**Comment by colinmacgiolla** [comment]
+1 for a rename to gNMI

**Comment by TechDawg** [comment]
+1 for rename to gNMI Interface!

**Comment by fredhsu** [comment]
+1 for renaming to gNMI

**Comment by sjwang90** [comment]
We will work on changing this plugin name to `gnmi_telemetry`
