### ISSUE TITLE
procstat_running can not get the metrics correctly

### ISSUE THREAD

**Issue by congwensheng** [influxdata/telegraf#7116]
the inputs plugin procstat collect the process status metrics. i find the procstat_running use the pidfinder to find the pid of the process.  i find some problem of this. for example, there are two process named etcd and etcd-check, the pidfinder seems treat the etcd-check as the etcd. when i killed the etcd service,the procstat_running{exe= etcd}  is still 1, when i both killed the etcd and etcd-check,the procstat_running{exe= etcd}  is becoming 0. I suspect the use of splits or wildcards in pidfinder is causing this problem. Please check if this problem exists

**Comment by danielnelson** [comment]
The `exe` option in procstat works in the same way as `pgrep etcd`. Since this argument is a regular expression try using `exe = "^etcd$"`.
