### ISSUE TITLE
telegraf monitoring disk abnormal

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#7121]
We monitored the mount disk of ceph rbd through telegraf, causing the ceph rbd umount to be abnormal. Finally, after the delete telegraf pod, the ceph rbd umount was normal.

version:1.9.1

**Comment by danielnelson** [comment]
@fcddk Can you update to the latest Telegraf and retest?  If you are still having problems with it then can you reopen a bug issue and make sure to fill out all the sections.

**Comment by fcddk** [comment]
Telegraf monitoring rbd disk used in k8s cluster found that there are such problems:
When telegraf is occupying and reading the monitoring information of an rbd device, the rbd will be migrated and an unmap operation needs to be performed. At this time, telegraf occupancy will cause rbd to be unable to unmap normally.
