### ISSUE TITLE
fieldpass does not work as expected in clone processor plugin

### ISSUE THREAD

**Issue by ix-dev** [influxdata/telegraf#7122]
The filter used in the clone processor plugin should not modify the original measurement. In the following example the field "foobar" is dropped from both the original and the cloned measurement. The expected behaviour would be that the fieldpass filter only affects the cloned measurement.

### Relevant telegraf.conf:

```toml
[[processors.clone]]
    namepass = ["test_measurement"]
    fieldpass = ["value"]
    name_override = "test_measurement_clone"
```

### System info:

telegraf --version
Telegraf 1.13.4 (git: HEAD ffabd6b5)

### Steps to reproduce:

1. Start Telegraf with config above
2. Write data using the InfluxDB API
```
curl -i -XPOST 'http://localhost:8186/write?db=icinga2' --data-binary 'test_measurement,label=l1,metric=m1 value=1 0'
curl -i -XPOST 'http://localhost:8186/write?db=icinga2' --data-binary 'test_measurement,label=l2,metric=m2 value=2 0'
curl -i -XPOST 'http://localhost:8186/write?db=icinga2' --data-binary 'test_measurement,label=l2,metric=m2 foobar=2 0'
curl -i -XPOST 'http://localhost:8186/write?db=icinga2' --data-binary 'test_measurement,label=l3,metric=m3 value=3 0'
```
3. Query data via InfluxDB shell from both measurements

### Expected behavior:

```
> SELECT * FROM test_measurement
name: test_measurement
time                 host              label metric value foobar
----                 ----              ----- ------ ----- ------
1970-01-01T00:00:00Z ubuntu-VirtualBox l1    m1     1
1970-01-01T00:00:00Z ubuntu-VirtualBox l2    m2     2     2
1970-01-01T00:00:00Z ubuntu-VirtualBox l3    m3     3


> SELECT * FROM test_measurement_clone
name: test_measurement_clone
time                 host              label metric value
----                 ----              ----- ------ -----
1970-01-01T00:00:00Z ubuntu-VirtualBox l1    m1     1
1970-01-01T00:00:00Z ubuntu-VirtualBox l2    m2     2
1970-01-01T00:00:00Z ubuntu-VirtualBox l3    m3     3
```

### Actual behavior:

```
> SELECT * FROM test_measurement
name: test_measurement
time                 host              label metric value
----                 ----              ----- ------ -----
1970-01-01T00:00:00Z ubuntu-VirtualBox l1    m1     1
1970-01-01T00:00:00Z ubuntu-VirtualBox l2    m2     2
1970-01-01T00:00:00Z ubuntu-VirtualBox l3    m3     3


> SELECT * FROM test_measurement_clone
name: test_measurement_clone
time                 host              label metric value
----                 ----              ----- ------ -----
1970-01-01T00:00:00Z ubuntu-VirtualBox l1    m1     1
1970-01-01T00:00:00Z ubuntu-VirtualBox l2    m2     2
1970-01-01T00:00:00Z ubuntu-VirtualBox l3    m3     3
```

**Comment by danielnelson** [comment]
Thanks for the feedback.  This is similar to the issue described in #4075.

It ought to be possible to work around using additional processor steps (untested):
```toml
# clone and add clone=true tag
[[processors.clone]]
  order = 1
  namepass = ["test_measurement"]
  [processors.clone.tags]
    clone = "true"

# remove all fields other than "value" from metrics with the clone tag, and remove the clone tag.
[[processors.clone]]
  order = 2
  namepass = ["test_measurement"]
  fieldpass = ["value"]
  tagexclude = ["clone"]
  [processors.clone.tagpass]
    clone = ["true"]
```

**Comment by ix-dev** [comment]
I've found a similar workaround and apply the fieldpass filter in the pivot processor plugin which I use in order to further process the data.
```
[[processors.clone]]
    order = 1
    namepass = ["test_measurement"]
    name_override = "test_measurement_clone"

[[processors.pivot]]
    order = 2
    namepass = ["test_measurement_clone"]
    fieldpass = ["value"]
    ## Tag to use for naming the new field.
    tag_key = "metric"
    ## Field to use as the value of the new field.
    value_key = "value"
```
However, it would be much better to have a working fieldpass filter in the clone processor plugin instead of cloning all the fields and throwing away all unneeded fields in the next processing step.

**Comment by iot-monitor-net** [comment]
I hit the same problem, while I tried to scale specific fields with the starlark plugin, while leaving others untouched. However fieldpass filters on the complete stream and not only the processor plugin (at least for the variants I tested). To me this seems to apply to all processor plugins. 
Especially with the great added capabilities of starlark it would be easiest to have the fieldpass filter working as expected. For now I guess the workaround is to filter within starlark script.

**Comment by srebhan** [comment]
@ix-dev and @iot-monitor-net metric-filters and metric-selectors **always** effect **all** metrics. What you are trying to do can be done using the [split processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/split) like

```toml
[[processors.split]]
   namepass = ["test_measurement"]

  [[processors.split.template]]
    name = "test_measurement_clone"
    tags = ["*"]
    fields = ["value"]
```
