### ISSUE TITLE
[kubernetes plugin] Volume are not filtered by storage type

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/telegraf#7124]
### Relevant telegraf.conf:

Default configuraiton of the `telegraf-ds` chart except for outputs which targets my 1.x and 2.x influxdb instances.

cf https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-ds/templates/configmap.yaml#L18-L40

### System info:

Telegraf 1.13.4
Kubernetes 1.17.0 @ OVH Managed K8S Service

### Steps to reproduce:

1. Deply telegraf-ds chart
2. Explore data to see the issue

### Expected behavior:

See only volumes  from PVC and not configmaps or secrets.

### Actual behavior:

See all volumes mounted in pods : configmaps, volumes, secrets

Also, for secrets and configmaps, the capacity_bytes match the total capacity bytes on the local node.

### Additional info:

To see all volumes, do a flux function as:

```
from(bucket: "crntk8s")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "kubernetes_pod_volume")
  |> filter(fn: (r) => r._field == "used_bytes" or r._field == "capacity_bytes")
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group(columns: [])
```

You will see all mounted volumes and the wrong capacity bytes for configmaps and secrets.

**Comment by nsteinmetz** [comment]
I'm not a go dev but seems the code is there and I don't see any filtering.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/kubernetes/kubernetes.go#L280-L292

**Comment by nsteinmetz** [comment]
Seems PVC are no longer in kubelet since 1.12 - cf https://github.com/kubernetes/kubernetes/issues/68522

**Comment by nsteinmetz** [comment]
Ok and seems csi-cinder driver does not report metrics yet :'(

Will try on gke then for further tests.

**Comment by MyaLongmire** [comment]
Did you make any headway on this @nsteinmetz?

Is there a pattern (like volume names or mount option) that we can ignore?

**Comment by nsteinmetz** [comment]
Hello @MyaLongmire,

Currently I no longer use kubernetes for my current project so no idea if anything changed since but I didn't progress on this on my side.

**Comment by MyaLongmire** [comment]
@nsteinmetz Thanks for getting back to us! I am going to close this for now then. If anyone needs it reopened, let me know :)

**Comment by dsvk** [comment]
@MyaLongmire I would indeed appreciate a way to predictably filter out all non-PVC entries - which IMHO could even be the _default_ plugin behavior (similar to how `disk` excludes some less relevant filesystems by default) but I'm fine with a non-default option or a `type`-style tag to make reliable filtering/tagdrop feasible too.

As for _how_ to get the data to differentiate these volume types I'm not sure. `kube_inventory` plugin queries the apiserver to get the list of PVCs so either kubelet also provides that data somewhere (not familiar with it enough to tell) or the plugin might need to query both API endpoints and combine the data to extend the current measurement. 

Volume _names_ are user-defined for both PVCs and configmaps/secrets so I don't think any pattern filtering is feasible there.

For additional context, https://github.com/influxdata/telegraf/issues/8546 and https://github.com/influxdata/telegraf/issues/8565 are another issues that somewhat similarly suffer from the current two-plugin split and trying to combine `kubernetes` metrics with `kube_inventory` metadata, also https://github.com/influxdata/telegraf/issues/9451 (conflicting measurement name). Merging both plugins was [already proposed earlier](https://github.com/influxdata/telegraf/issues/9451#issuecomment-1085037602) but that's apparently unlikely to happen anytime soon (<2.x), if at all.
