### ISSUE TITLE
input plugin bind - inconsistent use of tags

### ISSUE THREAD

**Issue by gerhard-tinned** [influxdata/telegraf#7126]
### Relevant telegraf.d/bind.conf :

```toml
[bind]
  urls = ['http://127.0.0.1:8008/xml/v2']
  gather_memory_contexts = false
  gather_views = true
```

### System info:

* telegraf 1.14 + kairosdb
  * bind 9.9.4
  * XML Statistics Channel v2
  * RHEL 7
* telegraf 1.13.4 + influxdb
  * bind 9.11.4
  * XML Statistics Chanel v3
  * CentOS 7

### Steps to reproduce:

1. Use the bind input plugin configuration stated above.
1.1. Enable the "bind" input plugin
1.2. Enable "gather_views" of the bind input plugin
2. "telegraf --config /etc/telegraf/telegraf.d/bind.conf --input-filter bind --test"

```
2020-03-06T10:30:46Z I! Starting Telegraf
> bind_counter,host=host.name.tld,port=8008,source=127.0.0.1,type=opcode,url=127.0.0.1:8008 IQUERY=5i,NOTIFY=82i,QUERY=299664951i,STATUS=65i,UPDATE=349i 1583490646000000000
> bind_counter,host=host.name.tld,port=8008,source=127.0.0.1,type=qtype,url=127.0.0.1:8008 A=210675640i,A6=107540i,AAAA=54763703i,...,WKS=1263i 1583490646000000000
> bind_counter,host=host.name.tld,port=8008,source=127.0.0.1,type=nsstat,url=127.0.0.1:8008 AuthQryRej=9188862i,...,XfrReqDone=3i 1583490646000000000
> bind_counter,host=host.name.tld,port=8008,source=127.0.0.1,type=zonestat,url=127.0.0.1:8008 AXFRReqv4=0i,...,XfrSuccess=68i 1583490646000000000
> bind_counter,host=host.name.tld,port=8008,source=127.0.0.1,type=sockstat,url=127.0.0.1:8008 FDWatchClose=0i,...,UnixSendErr=0i 1583490646000000000
> bind_memory, host=host.name.tld,port=8008,source=127.0.0.1,url=127.0.0.1:8008 block_size=249036800i,...,lost=0i,total_use=155255965863i 1583490646000000000
> bind_counter,host=host.name.tld,type=qtype,url=127.0.0.1:8008,view=_default A=97197480i,AAAA=9643699i,...,WKS=1255i 1583490646000000000
> bind_counter,host=host.name.tld,type=resstats,url=127.0.0.1:8008,view=_default EDNS0Fail=16523i,...,ValOk=83535284i 1583490646000000000
> bind_counter,host=host.name.tld,type=resstats,url=127.0.0.1:8008,view=_bind EDNS0Fail=0i,...,ValOk=0i 1583490646000000000

```

### Expected behavior:

All metrics with the same metric name should have the same tags set. This would mean, when this feature is enabled (gather_views = true) ALL bind_counter metrics should have the same set of tags (including the "view" tag) assigned. The tag values will differ, but the tag must exist to allow filtering for the specific data.

### Actual behavior:

The plugin generates metric mane + field (example: metric "bind_counter" and field "A") with the tag "view" and without "view" tag. This results in metric data in the backend database (influxdb, kairosdb, ...) which can not be accessed properly. (Query of data where "view" tag is not set seems not possible. 

In the above output, only the last 3 bind_counter metrics have the view tag.

**Comment by danielnelson** [comment]
> All metrics with the same metric name should have the same tags set.

This isn't something we normally require and I'm not aware of any issues querying data like this in InfluxDB.  Can you show me the InfluxQL/Flux queries you are using?

**Comment by gerhard-tinned** [comment]
Executed telegraf with the bind config (shown above) returns the following values:

```
telegraf --config /etc/telegraf/telegraf.d/bind.conf --test | grep DNSKEY
2020-03-09T16:16:49Z I! Starting Telegraf
> bind_counter,host=HOSTNAME,port=8008,source=127.0.0.1,type=qtype,url=127.0.0.1:8008 A=199666027i,A6=98603i,AAAA=52213216i,AFSDB=110i,ANY=292941i,AXFR=1782i,CERT=48i,CNAME=2020052i,DLV=41i,DNAME=85i,DNSKEY=140100i,DS=34576i,EID=225i,HINFO=1910i,ISDN=4i,KEY=39i,LOC=2805i,MAILB=3i,MB=41i,MINFO=13i,MR=39i,MX=6293533i,NAPTR=11413i,NS=3787848i,NSEC=188i,NSEC3PARAM=163i,NULL=32i,Others=67965i,PTR=4611304i,PX=2i,RESERVED0=26i,RP=38i,RRSIG=2247i,SIG=11i,SOA=1703266i,SPF=306840i,SRV=9360564i,SSHFP=74i,TLSA=5199i,TXT=4533509i,TYPE59=5014i,TYPE60=3494i,WKS=1308i 1583770609000000000
> bind_counter,host=HOSTNAME,type=qtype,url=127.0.0.1:8008,view=_default A=90980800i,AAAA=8988119i,ANY=772i,CNAME=340244i,DLV=41060i,DNSKEY=676065i,DS=8338967i,HINFO=1311i,MX=69993i,NAPTR=6413i,NS=204356i,NULL=35i,Others=1i,PTR=158927i,RESERVED0=6i,SOA=89802i,SRV=265463i,TXT=159814i,WKS=1301i 1583770609000000000
```

In particular, the DNSKEY metric will be used to show the issue. 

bind_counter without any view tag shows a value of 147 ("DNSKEY=147i") while the configured view "999_external-in" shows for the DNSKEY query type 45 ("DNSKEY=45i"). 

The shown timestamp in the test run represents "Mon, 09 Mar 2020 16:16:49 GMT" to gather data collected around that time from telegraf, the timespan of "09 Mar 2020 15:49:40 GMT" to "09 Mar 2020 15:50:00 GMT" is used.

The query in grafana against the KairosDB looks like this (output from the query inspector): 

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "data": {
      "cache_time": 0,
      "start_absolute": 1583766995000,
      "end_absolute": 1583767015000,
      "metrics": [
        {
          "limit": 0,
          "name": "linux.bind_counter_DNSKEY",
          "tags": {
            "host": [
              "HOSTNAME"
            ],
            "type": [
              "qtype"
            ]
          },
          "aggregators": [],
          "group_by": []
        }
      ]
    },
    "url": "api/datasources/proxy/1/api/v1/datapoints/query"
  },
  "response": {
    "queries": [
      {
        "sample_size": 2,
        "results": [
          {
            "name": "linux.bind_counter_DNSKEY",
            "group_by": [
              {
                "name": "type",
                "type": "number"
              }
            ],
            "tags": {
              "host": [
                "HOSTNAME"
              ],
              "port": [
                "8008"
              ],
              "source": [
                "127.0.0.1"
              ],
              "type": [
                "qtype"
              ],
              "url": [
                "127.0.0.1_8008"
              ],
              "view": [
                "_default"
              ]
            },
            "values": [
              [
                140051,
                1583767000000
              ],
              [
                675626,
                1583767000000
              ]
            ]
          }
        ]
      }
    ]
  }
}
```

As there is no way to generate a query that allows to set a filter for "all values where there is no 'view' tag set", it is impossible to seperate the data without a view tag assigned.

**Comment by danielnelson** [comment]
I'm really not very familiar with KairosDB, but is it possible to add "view" to the group by?

**Comment by gerhard-tinned** [comment]
Hi, 

Well, the problem is not related to the backend DB used but the general way data can be queried. 

To your question: Yes, when you add a view tag to the query, you get all the data related to that view. But now the question, .... how would you query the data without the view tag?

how to query let's say in any value for a tag without the view tag?

You build a query with host, type=qtype and ... how to find metrics without the view tag (not empty). Maybe I just dont know how. I did not manage that in influxdb or in KairosDB. 

The goal is to have a graph/table with the metric that was reported with this line from telegraf (and only this data). 

```
> bind_counter,host=HOSTNAME,port=8008,source=127.0.0.1,type=qtype,url=127.0.0.1:8008 A=199666027i,A6=98603i,AAAA=52213216i,AFSDB=110i,ANY=292941i,AXFR=1782i,CERT=48i,CNAME=2020052i,DLV=41i,DNAME=85i,DNSKEY=140100i,DS=34576i,EID=225i,HINFO=1910i,ISDN=4i,KEY=39i,LOC=2805i,MAILB=3i,MB=41i,MINFO=13i,MR=39i,MX=6293533i,NAPTR=11413i,NS=3787848i,NSEC=188i,NSEC3PARAM=163i,NULL=32i,Others=67965i,PTR=4611304i,PX=2i,RESERVED0=26i,RP=38i,RRSIG=2247i,SIG=11i,SOA=1703266i,SPF=306840i,SRV=9360564i,SSHFP=74i,TLSA=5199i,TXT=4533509i,TYPE59=5014i,TYPE60=3494i,WKS=1308i 1583770609000000000
```

**Comment by danielnelson** [comment]
With InfluxDB you can exclude items with an empty string as the view tag:

Setup:
```
$ influx
Connected to http://localhost:8086 version 1.7.9
InfluxDB shell version: 1.7.9
> use telegraf
Using database telegraf
> insert bind_counter,view=a value=42
> insert bind_counter value=43
```

Normally query shows both series:
```
> select * from bind_counter group by view;
name: bind_counter
tags: view=
time                value
----                -----
1583866017652211466 43

name: bind_counter
tags: view=a
time                value
----                -----
1583866012931954568 42
```

Exclude items without a view:
```
> select * from bind_counter where view != '' group by view;
name: bind_counter
tags: view=a
time                value
----                -----
1583866012931954568 42
```

Maybe something similar exists for KairosDB?

**Comment by gerhard-tinned** [comment]
No, that does not work with KairosDB.

**Comment by danielnelson** [comment]
That's unfortunate but I don't think we will address it.  Perhaps you could open a feature request with KairosDB to improve there handling of unset tags.
