### ISSUE TITLE
Configurable WMI query timeout for procstat's Windows native pid_finder 

### ISSUE THREAD

**Issue by kstennis** [influxdata/telegraf#7129]
### Proposal: 
Allow users to specify a custom timeout period in telegraf.conf for procstat entries that make use of the Windows native pid_finder. 

### Current behavior:
In [native_finder_windows.go](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/native_finder_windows.go), the WMI query timeout is hard-coded as `var Timeout = 5 * time.Second`

In certain situations, a WMI query may take longer than the timeout to respond, resulting in the procstat plugin erroring out with:
> [inputs.procstat]: Error in plugin: could not get win32Proc: context deadline exceeded

### Desired behavior:
Being able to specify a custom timeout period for WMI queries in each procstat entry would be helpful. For example:
```
[[inputs.procstat]]
   interval = "3m"
   process_name = "MyProcess"
   pid_finder = "native"
   timeout = "1m"
   fieldpass = [ "cpu_usage", "memory_rss" ]
```
### Use case: 
In our current environment, we have servers that are under a high load frequently. Whenever WMI queries time out on these machines, we end up with chunks of missing data in our graphs. These chunks of missing data could result in Grafana not triggering alarms despite something being wrong. 
![missingdata](https://user-images.githubusercontent.com/61889848/76126382-2bb51700-5fbc-11ea-9c0e-6fb1b630e35e.png)

**Comment by sjwang90** [comment]
Closed in PR #7641
