### ISSUE TITLE
SNMP Trap Inform 

### ISSUE THREAD

**Issue by neeles83** [influxdata/telegraf#7130]
## Feature Request
As requested in #6918 an additional Feature request to start the discussion on SNMP Inform traps.

In SNMPv2 and SNMPv3 the InformRequest was added, this to send a reply once a SNMP Trap is received. The reply is sent as an acknowledgement of the received trap, to stop traps from being sent.

### Proposal:
Add inform support to SNMP-Traps
http://www.net-snmp.org/tutorial/tutorial-5/commands/snmptrap-v3.html

### Current behavior:
In our capture of traffic we see the traffic arriving but the inform is not presented in the exposed metrics of telegraf,

# Below an SNMP traps without and with inform request:
07:49:44.829779 IP nlrott99-gm5120.testlab.net.43613 > rott99-app2002.snmptrap: C="xxxxxxxx" V2Trap(173) system.sysUpTime.0=9528 S:1.1.4.1.0=E:26866.1.1.11 E:26866.1.2.17="GigaVUE-OS" E:26866.1.2.1=3 E:26866.1.2.2="Fan Status Change" E:26866.1.2.19="1" E:26866.1.2.20=1

# This below inform trap is received but dropped by the collector and no response is sent
07:49:17.911719 IP nlrott99-bs2010.testlab.net.32795 > rott99-app2002.snmptrap: C="xxxxxxx" Inform(57) system.sysUpTime.0=120308 S:1.1.4.1.0=E:15694.2.8.6

### Desired behavior:
SNMP Inform should be accepted and sent a reply message, this to not get overloaded by inform traps. 

### Use case: 
Traps of devices ares now not processed, in addition we want to use SNMPv3 because of security requirements.

**Comment by kauppine** [comment]
The upstream snmp library has not implemented SNMP informs yet. However, there is a pull request that should add the missing feature to it: https://github.com/soniah/gosnmp/pull/202

**Comment by neeles83** [comment]
Good to hear thanks for the referral.

**Comment by neeles83** [comment]
@danielnelson Now that the upstream snmp library has been updated, should this also work for the new builds from Telegraf?

**Comment by danielnelson** [comment]
We will need to merge #7836 first but it looks like the tests are failing with the new version.

**Comment by RemcoAA** [comment]
Hi,

what is the status of this request?
We noticed that the INFORM traps are now getting processed by Telegraf, but there is no reply sent to the sender so the sender is still sending traps multiple times.

**Comment by ahmednawazkhan** [comment]
Hi. Is this request complete?

**Comment by waqaskhan137** [comment]
> We will need to merge #7836 first but it looks like the tests are failing with the new version.

@danielnelson can you please update if we have this feature available now?

**Comment by Hipska** [comment]
It seems like support for INFORM will come with #9203
