### ISSUE TITLE
Cisco MDT Plugin Working on fresh install of 1.12.6, but not fresh install of 13.4

### ISSUE THREAD

**Issue by mprintz** [influxdata/telegraf#7137]
Enabling and configuring the Cisco MDT plugin is not receiving metrics on a fresh

### Relevant telegraf.conf:

```toml

```

### System info:

Telegraf Version 1.12.6 and 1.13.4
RHEL7 Linux

### Steps to reproduce:

1. Install a fresh telegraf 1.13.4
2. Enable the Cisco MDT plugin
3. Enable Exec Print or other method to save output to file
4. Verify no Cisco data coming in
5. Downgrade to 1.12.6
6. Ensure Cisco MDT plugin enabled, debugging output setup
7. Metrics now coming through
8. Upgrade to 1.13.4
9. Metrics still coming through.

### Expected behavior:

Cisco Router stats coming through after being enabled on the latest telegraf agent pulled from repo.

### Actual behavior:

Cisco Router data is not coming through, and downgrade required to get up to plug in working. What is weird is that once it is working, we can then upgrade and plugin keeps working.

### Additional info:

![image](https://user-images.githubusercontent.com/9125473/76218632-8def6100-61e2-11ea-97dd-1b7a73e6392d.png)

**Comment by ssoroka** [comment]
It seems unlikely that downgrading and upgrading again would resolve anything. Are you able to run it in `--test` mode to confirm if the metrics are being collected properly on a fresh install?

**Comment by sjwang90** [comment]
@mprintz This issue came up in a recent search. Is this still a problem?

**Comment by ssoroka** [comment]
Seems like a debugging oddity or other issue. Telegraf has no state between upgrades and downgrades.
