### ISSUE TITLE
[http_listener_v2] store source ip and user as tag

### ISSUE THREAD

**Issue by farmio** [influxdata/telegraf#7145]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add an option to use the requesting host (ip) and/or user (if BasicAuth can be used with multiple users) in a tag.

### Current behavior:
This option is not available.
### Use case: 
I have 2 Fronius PV Inverters. They send metrics to the telegraf http endpoint. As these devices are identical there is no way to distinguish between them.

**Comment by danielnelson** [comment]
We added the ability to create a tag with  any header in #7223, perhaps this could be used?  Otherwise I suggest we go for extracting the basic auth user, using the `src_ip` could be high cardinality for some usage patterns.

**Comment by farmio** [comment]
Thank you for looking into this!

Unfortunately the only Headers sent by these Inverters are 
> 'Host': '10.1.1.9:8705', 'Accept': '*/*', 'Content-Length': '783', 'Content-Type': 'application/x-www-form-urlencoded'

Would it be possible to define multiple basic auth users? Otherwise both devices would still generate the same tag.

**Comment by danielnelson** [comment]
Hmm, good point.  I'm happy with either/both solutions, though certainly it would be easiest to do just the source ip over switching to multiple passwords.  We could have options `source_ip_tag = ""` and `basic_user_tag = ""`, if either of these are set we the named tag with the value.

In the future we are planning to create a processor that can do a reverse ip lookup, it would be possible to use this to switch from the ip to the remote host name.

**Comment by sspaink** [comment]
@farmio does the reverse dns processor solve your problem? https://github.com/influxdata/telegraf/tree/master/plugins/processors/reverse_dns

**Comment by farmio** [comment]
I guess 👍, but I shifted to polling instead of having the inverters push their data so I currently don't have a usecase for it anymore.
