### ISSUE TITLE
[http_listener_v2] multiple paths with different configurations

### ISSUE THREAD

**Issue by farmio** [influxdata/telegraf#7146]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add the ability to listen on multiple `path` each with different data_format and tags.

### Current behavior:
This is currently not possible. It can be achieved by using multiple instances of inputs.http_listener_v2 but each would need to open a new port.

### Desired behavior:
Not needing to open multiple ports for different data_formats or fieldpass.

**Comment by danielnelson** [comment]
I'd be up for allowing multiple paths if they share the same `data_format`.  Supporting multiple data_format per plugin would be a larger undertaking.  Would it still be helpful to you with this limitation?

**Comment by farmio** [comment]
Thank you for your considerations!

I think if the data_format has to be the same there would be no real benefit of using multiple paths - at least for my application. 

It could be a possible solution for #7145 but I think solving this by distinction through IP Address would be cleaner.

**Comment by danielnelson** [comment]
I'm going to close this issue then, I don't think we would be ready to introduce any new concepts to support this feature, at least for now.

Obviously it would be more work than having it built in, but you could install a reverse proxy, such as nginx, in front of Telegraf.
