### ISSUE TITLE
Is there a python script or module to monitor "Healthchecks" for Filebeat with telegraf?

### ISSUE THREAD

**Issue by lmakonem** [influxdata/telegraf#7155]
## Feature Request

I know we can use metricbeat to monitor other beats but i need to monitor the health of a Filebeat docker container using telegraf, is there an easier way to accomplish this?

Maybe a python script?

Opening a feature request kicks off a discussion.

### Use case: 
To monitor the health status of Filebeat docker container.

**Comment by danielnelson** [comment]
This isn't merged yet, but is something like #6653 what you have in mind?

**Comment by sjwang90** [comment]
Closed by #6653
