### ISSUE TITLE
CSV input ability to skip specific (named?) columns

### ISSUE THREAD

**Issue by anthonysomerset** [influxdata/telegraf#7159]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

To allow the ignoring of columns by a named, or numbered array rather than just skip first <n> columns

### Current behavior:

right now you can only skip the leading columns of a csv, this also means that your csv_column_names and csv_column_types must also "skip" those skipped collumns. you cannot skip a column at the end or in the middle of a row

### Desired behavior:

to be able to apply an array of column names or numbers which will be ignored in the csv_skip_columns variable
e.g.

for a CSV with:

`csv_column_names = ["RecordType", "RecordNumber", "RecordStatus", "StartTime", "EndTime", "AcctSessionId", "SubscriberId", "FramedIp", "ServiceId", "TotalBytes", "RxBytes", "TxBytes", "TimeUsed"]`

one could apply the config 

`csv_skip_columns = ["RecordType", "RecordNumber", "RecordStatus", "StartTime",  "AcctSessionId",  "FramedIp", "TimeUsed"]`
or
`csv_skip_columns = [1, 2, 3, 4, 6, 8, 13]`

to totally drop those columns either by name reference or column position so they are not even processed further

if a single integer is provided then the old behaviour can remain active e.g.

```
csv_column_names = ["EndTime", "AcctSessionId", "SubscriberId", "FramedIp", "ServiceId", "TotalBytes", "RxBytes", "TxBytes", "TimeUsed"]
csv_column_types = ["string", "string", "string", "string", "int", "int", "int", "int", "int"]
csv_skip_columns = 4
```

### Use case: 

Not all CSV's are well ordered for ingest into systems like influxdb or they may add extraneous data fields which bloat the data and/or cause performance issues for the underlying storage DB

This would allow one to simply throw away the data more granularly that they don't want or need in time storage db's and thus realise less performance impacts by doing so

**Comment by danielnelson** [comment]
You should be able to the `fielddrop` [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) option to remove the unwanted column.  If you parse it as type `string` it should avoid any conversion errors.

```
fielddrop = ["RecordType", "RecordNumber", "RecordStatus", "StartTime", "AcctSessionId", "FramedIp", "TimeUsed"]
```

Let me know if it works for you.

**Comment by anthonysomerset** [comment]
wow this works exactly as required thanks - can't believe i did not see this

it makes sense to close this but do wonder if it would be nice for a reference to this from the csv parser docs?

**Comment by danielnelson** [comment]
I added a note in d8b66b69d5e68f2d7cabeb9630f4a1528aa80789
