### ISSUE TITLE
Jenkins input plugin not url encoding job names resulting in 404s

### ISSUE THREAD

**Issue by perzizzle** [influxdata/telegraf#7165]
### Relevant telegraf.conf:

```toml
[[inputs.jenkins]]
  name_prefix="infra_"
  url = "http://localhost:8080"

  response_timeout = "5s"
```

### System info:

telegraf --version
Telegraf 1.13.0 (git: HEAD 773e4ca5)

### Steps to reproduce:

1. Create a Jenkins job with spaces
2. 
```
> telegraf --config jenkins.conf --test
infra_jenkins_job,host=jenkinsMaster,name=name,parents=parent,result=FAILURE duration=106285i,result_code=1i 1583529206000000000
2020-03-06T21:21:56Z E! [inputs.jenkins] Error in plugin: [/job/foo bar/job/application - job/feature%2branch/api/json] 404 Not Found
```

### Expected behavior:

We successfully pull job data for every job that doesn't include spaces, if you copy the uri (/job/foo bar/job/application - job/feature%2branch/api/json) into a browser it correctly changes the spaces to %20 and the json blob is returned.

### Actual behavior:
We get a 404 for jobs that contain spaces.

**Comment by jgibbarduk** [comment]
I have the same issue. Please can someone take a look? Thanks

**Comment by jgibbarduk** [comment]
Any update on this?

**Comment by HarshitOnGitHub** [comment]
Picking up this! :)
