### ISSUE TITLE
[Input plugin: Postgresql] Add databases and table sizes as metrics

### ISSUE THREAD

**Issue by Arnoways** [influxdata/telegraf#7166]
## Feature Request
Add databases size, table sizes and each table's number of rows as metrics inside the input plugin.

### Proposal:
Instead of writing a custom script to get the information with the [exec] plugin, I was wondering if we could add this feature in the postgresql input plugin.

### Use case: 
Hi folks,

My team and I are currently using telegraf at work to get some informations about our PG clusters. We recently had a demand from our developers to retrieve databases' size, tables' size and the number of rows they are containing.
I was wondering if we could add this feature to the input plugin instead of just writing a custom script?

Cheers!

**Comment by danielnelson** [comment]
I think the best option would be to use the `postgresql_extensible` plugin for this.  We want to keep the built in database queries lightweight and only add the most essential pieces.  Closing, but let me know if you run into any issues.
