### ISSUE TITLE
Unable to enable AWS Go SDK's debug logging for Cloudwatch input plugin

### ISSUE THREAD

**Issue by fmr-ap** [influxdata/telegraf#7168]
We are trying to measure the amount of ListMetrics & GetMetricData calls issued by a fleet of Telegraf containers. Since ListMetrics calls cannot be throttled it is really important that we can see how many are issued in a second and how long the response times are. I looked into enabling the AWS Go SDK's debug logging by modifying the input plugin and setting loglevel := aws.LogDebug. However, even with debug logging enabled, Telegraf does not seem to emit any of the AWS Go SDK's log messages in its log. What am I missing here?

**Comment by danielnelson** [comment]
Not sure, seems like the default logger in the aws.Config should go to stdout.  Another way you could count these calls is to add selfstat aka internal metrics to the plugin similar to those in influxdb_listener.

**Comment by fmr-ap** [comment]
Thanks @danielnelson. Adding this to the plugin using selfstat is beyond my Go skills and understanding of how this works. I thought it would log to stdout and end up in telegraf's debug log. Any reason it may not? Anyone who can test this and confirm that I am not doing something wrong on my end?

**Comment by sspaink** [comment]
@fmr-ap sorry you haven't had a reply in a while, are you still interested in measuring the amount of calls to "ListMetrics & GetMetricData" ?
