### ISSUE TITLE
mntr is not executed because it is not in the whitelist.

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#7169]
telegraf: version 1.9.1
zookeeper: version 3.5.7

log: 
2020-03-13T02:03:38Z E! [inputs.zookeeper]: Error in plugin: unexpected line in mntr response: "mntr is not executed because it is not in the whitelist."

**Comment by danielnelson** [comment]
You need to add mntr to the whitelist, from the [zookeeper docs](https://zookeeper.apache.org/doc/current/zookeeperAdmin.html):

> New in 3.5.3: Four Letter Words need to be explicitly white listed before using. Please refer 4lw.commands.whitelist described in cluster configuration section for details.

> 4lw.commands.whitelist : (Java system property: zookeeper.4lw.commands.whitelist) New in 3.5.3: A list of comma separated Four Letter Words commands that user wants to use. A valid Four Letter Words command must be put in this list else ZooKeeper server will not enable the command. By default the whitelist only contains "srvr" command which zkServer.sh uses. The rest of four letter word commands are disabled by default.
