### ISSUE TITLE
input plugin support independent output source

### ISSUE THREAD

**Issue by huyujie** [influxdata/telegraf#7175]
@danielnelson 
 for some input plugin，like snmp_trap，we want export to several output(just like influxdb and http)，but for other plugins, only need to export to influxdb.

**Comment by danielnelson** [comment]
You can use either of the last two examples in this section of the configuration docs to achieve this:
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#filtering-examples

duplicate #1778
