### ISSUE TITLE
support lxc monitor

### ISSUE THREAD

**Issue by zhangjianpinghik** [influxdata/telegraf#7183]

**Comment by danielnelson** [comment]
Can you show some example output from lxc-monitor?

**Comment by sjwang90** [comment]
@zhangjianpinghik Can you please provide more information on lxc-monitor and your use case for getting it supported?

**Comment by sjwang90** [comment]
Closing issue due to lack of information. Feel free to open if this is something you'd still like to see supported in Telegraf.
