### ISSUE TITLE
SQL Server - PerfCounter Over 100% - limit counter value

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7186]
## Feature Request

The idea is to set a limit on the percentage counters of SQL Server, in fact, sometimes they go over 100%, it's not a problem when the value is like 102-103, but when you get something like "Cpu Usage %" = 3770 or 6700, then something is not right, and averages and other calculation go way off the scale.

The limit can be implemented in the query itself. 
Something like this at the end of the query might work, but it requires more thinking and checks:
```SQL
{...}
SELECT
    measurement,
    sql_instance,
    database_name,
    object,
    counter,
    value = CASE WHEN counter LIKE '%[%]%' AND value > 100 THEN 100 ELSE value END
FROM measurement_data
```

I'm aware of some counters which values can be above 100% (and that's right), so a more restrictive condition might be better to avoid issues in other and future counters.

### Notes (When does it happen)
We encountered this issue on a test server (SQL 2012) that is always on heavy load, when the CPU Usage gets to 100%, for a minute or so the values are still ok (around 100, 105 maybe), but afterward, the values go crazy to the thousands unit. 
We think this is caused by the heavy load on the server, which does not allow SQL Server to correctly align the values behind the calculation (the value is obtained in by dividing 2 values)

### Proposal:
Set a limit for some counters regarding the SQL Server Performance, and limit them to a max of 100%. 

### Current behavior:
There is no fixed limit for percentage counters
### Desired behavior:
There is an upper limit for percentage counters (when appropriate)

### Use case:
No particular use case, it just helps to avoid somehow wrong data (caused by SQL Server on heavy load)

**Comment by Trovalo** [comment]
@denzilribeiro I would like to know your opinion on this. Have you ever had this problem?

**Comment by denzilribeiro** [comment]
@Trovalo  I would not change this in the query if it is a bug with counter value need to file against SQL. Starting all logic in the collector to compenstate isn't right thing. was there a specific countner?
I have not seen this before. Is this specifically workload group CPU? What is the specific counter?

**Comment by Trovalo** [comment]
The counter is "CPU Usage %", object = "Resource Pool Stats" and "Workload Group Stat), instance = "default".
I still need to check if other % counters had similar issues.

I know it's somehow dirty to put something like that in the collector, but at the same time, I see no other place to solve it. Also, this is an old instance (SQL 2012), but I want to check if the same applies to more recent versions

**Comment by danielnelson** [comment]
I think this should probably be done in a processor plugin.  We are planning to add a processor that allows running a starlark script over metrics, I think it would be a good fit.

**Comment by denzilribeiro** [comment]
This part may need a rewrite ( existed before I changed anything)
- This counter is s simulated counter it appears from DMVs
- Ideally we should use the Perfmon counter itself rather than actually crea
[WorkloadGroup Perfmon counter ](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-workload-group-stats-object?view=sql-server-ver15 )

"SQLServer:Workload Group Stats" AS object,
counter,
instance,
CAST(vs.value AS BIGINT) AS value,
1
FROM
(
    SELECT
    rgwg.name AS instance,
    rgwg.total_request_count AS "Request Count",
    rgwg.total_queued_request_count AS "Queued Request Count",
    rgwg.total_cpu_limit_violation_count AS "CPU Limit Violation Count",
    rgwg.total_cpu_usage_ms AS "CPU Usage (time)",
    ' + CASE WHEN SERVERPROPERTY('ProductMajorVersion') > 10 THEN 'rgwg.total_cpu_usage_preemptive_ms AS "Premptive CPU Usage (time)",' ELSE '' END + '
    rgwg.total_lock_wait_count AS "Lock Wait Count",
    rgwg.total_lock_wait_time_ms AS "Lock Wait Time",
    rgwg.total_reduced_memgrant_count AS "Reduced Memory Grant Count"
    FROM sys.dm_resource_governor_workload_groups AS rgwg
    INNER JOIN sys.dm_resource_governor_resource_pools AS rgrp
    ON rgwg.pool_id = rgrp.pool_id
) AS rg
UNPIVOT (
    value FOR counter IN ( [Request Count], [Queued Request Count], [CPU Limit Violation Count], [CPU Usage (time)], ' + CASE WHEN SERVERPROPERTY('ProductMajorVersion') > 10 THEN '[Premptive CPU Usage (time)], ' ELSE '' END + '[Lock Wait Count], [Lock Wait Time], [Reduced Memory Grant Count] )
) AS vs'
,'"','''')

**Comment by denzilribeiro** [comment]
Actually I correct myself was wrong does come from perfmon itself :). I agree with @danielnelson  better handled outside the collector.

**Comment by Trovalo** [comment]
If that's an option I will gladly use it. @danielnelson any idea about when this processor will come out?

**Comment by Trovalo** [comment]
Once that processor becomes available I will give it a try

**Comment by danielnelson** [comment]
I opened an issue for the starlark processor: #7194.  We are planning for a 1.15 release, but I expect to have it added to master within the next few weeks.
