### ISSUE TITLE
Telegraf watch and restart with new configuration file

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/telegraf#7187]
## Feature Request

Telegraf should watch and restart with new configuration file

### Proposal:

Telegraf watch and restart with new configuration file

### Current behavior:
If a new config file is placed in the same place where telegraf is running, the only way of picking up the changes is either to restart the process or sending SIGHUP signal

### Desired behavior:

Telegraf making a md5 checksum of the whole config file once it's fully templated out and then trying to template it out every 10/30/60 seconds to see if something changed. If the md5 checksum has changed, then trigger a restart 

### Use case: 

This would be very useful in a container environment because config files can be updated very often and it would be. and it's very easy to run hundreds/thousands of telegraf so the more automation we have the better

**Comment by ssoroka** [comment]
I'm not sure that we will bring this functionality into the app natively, but we're definitely planning to expose some of the config to make this sort of thing easier to do. As of today you could build this yourself without changes to Telegraf by watching for file changes, then signaling Telegraf with with SIGHUP to reload the config.

**Comment by ssoroka** [comment]
Note that you can already do this with --config-directory, as watching for file changes and reloading configuration is the default behavior for that.

**Comment by ssoroka** [comment]
I seem to be mistaken. Reopening this.
