### ISSUE TITLE
[DOC] Wrong key/values for datastores?

### ISSUE THREAD

**Issue by SebastianThorn** [influxdata/telegraf#7191]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/README.md
row 141 and 142 are the same as 134 and 135, feels like they should say:
datastore_include
datastore_exclude

**Comment by SebastianThorn** [comment]
wanted to do a RP but my fork did not look like the one i see on master, not sure why,
so i just made this Issue instead

**Comment by danielnelson** [comment]
Thanks for the heads up, let us know if you spot any other issues.  I synced the plugin and README documentation in 6a2d3595
