### ISSUE TITLE
Exposing Kafka producer metrics for Kafka plugin

### ISSUE THREAD

**Issue by anuprout** [influxdata/telegraf#7215]
## Feature Request

Hi, I am looking for any metrics that Telegraf exposes for Kafka producers such as producer request rate, avg request size, avg request latency etc.

### Proposal:
Expose the custom metrics using expvar via HTTP 

### Current behavior:
not sure if Telegraf has already has this feature.

### Desired behavior:

It should expose the relevant metrics for Kafka producers via some api.

**Comment by danielnelson** [comment]
What we can do is expose some information via the [internal](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal) plugin.  We have an issue open for this, #6965, so let's continue over there.
