### ISSUE TITLE
undefined but requested input "modbus" on telegraf 1.13.4

### ISSUE THREAD

**Issue by c3rebro** [influxdata/telegraf#7219]
### Relevant telegraf.conf:

```
[[inputs.modbus]]
  # TCP
  type = "TCP"
  controller="1.2.3.4"
  port = 1502

  slaveId = 71
  timeout = 5

  [[inputs.modbus.Registers.HoldingRegisters.Tags]]
    name = "Total DC power"
    order ="CDAB"
    datatype = "FLOAT32-IEEE"
    scale = ""
    address = [
    100, 101
    ]

t.b.c.

```

### System info:

**_Telegraf 1.13.4
OS: Rasbpian 10 (buster)_**

### Docker

_**installed by:**_

```
wget https://dl.influxdata.com/telegraf/releases/telegraf_1.13.4-1_armhf.deb
dpkg -i telegraf*
```

### Steps to reproduce:

1. install telegraf from https://dl.influxdata.com/telegraf/releases/telegraf_1.13.4-1_armhf.deb
2. service telegraf start
3. tail -5 /var/log/daemon.log

### Expected behavior:

**_telegraf starts to read the modbus holdingregisters and writes the values to influxdb_**

### Actual behavior:

**_see err msg above_**

### Additional info:

**_didn't found any armhf release by default. So i just changed the suffix of the telegraf***amd64.deb to telegraf***armhf.deb by hand._**

**Comment by danielnelson** [comment]
This plugin will be included in 1.14.0, you can try with the latest release candidate: [1.14.0-rc1](https://github.com/influxdata/telegraf/releases/tag/v1.14.0-rc1)
