### ISSUE TITLE
Does the SQL Server Input Plugin Support Windows Authentication

### ISSUE THREAD

**Issue by dbuehler77** [influxdata/telegraf#7221]
This is a question I couldn't find the answer to in the documentation.

I was able to get telegraf to collect metrics for MS SQL by creating a telegraf user that logs-in via SQL Server Authentication, per the documentation (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver); however, I haven't been able to get telegraf to authenticate using Windows Authentication. I have some MS SQL servers that only support Windows Auth and I may not be permitted to change this.

Can telegraf be configured to authenticate using Windows Auth?

**Comment by danielnelson** [comment]
I do have reports from the community that this works, I believe you need to leave the `user id` off. 
 Here is an connection string that was used in the past:
```
Server=localhost;Port=1433;Database=master;Integrated Security=SSPI;log=1;
```

Addtional connection string documentation: https://github.com/denisenkom/go-mssqldb#connection-parameters-and-dsn

**Comment by dbuehler77** [comment]
Awesome, thanks for the help.

For those still looking for a solution, this is what worked for me:

`Server=localhost;Port=1433;app name=telegraf;log=1;`

A little intrigued as to how this works. I have telegraf running as Local System, so I'm assuming that account is what telegraf is using to authenticate and Local System high enough privileges to log into MS SQL.
