### ISSUE TITLE
Help Required: procstat.input - monitor Ubuntu host processes from inside docker container

### ISSUE THREAD

**Issue by sirockin** [influxdata/telegraf#7226]
I have an instance of telegraf running in a docker container, to monitor system performance on my Ubuntu host.

I would like to use [[inputs.procstat]] to get stats for individual processes, but currently (using `pattern=".*"` it is producing stats for the only process within the container (telegraf) rather than those on the host. How can I configure the instance to display stats from the host?

Thanks!

**Comment by danielnelson** [comment]
This is the same issue as #6813.  There has been progress on this for 1.14.0, it should be possible to do this today with [1.14.0-rc1][] if you use `pid_finder = "native"` and [start the container with these options](https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container).


[1.14.0-rc1]: https://github.com/influxdata/telegraf/releases/tag/v1.14.0-rc1

**Comment by sirockin** [comment]
Thanks @danielnelson.
1. The official hub.docker telegraf repo does not have a tag for this version. Do you have a separate registry where you push release candidates? If not, please could you point me to a docker file to do my own build?
2. Do you know when this version is likely to be fully released?

Thanks

**Comment by danielnelson** [comment]
We just released the final version, but it will take a bit before the new images will be up on Docker Hub.

In the meantime, here is where we keep the official Dockerfile:

https://github.com/influxdata/influxdata-docker/tree/master/telegraf/1.14
