### ISSUE TITLE
Error while reading multiple holding registers on modbus input plugin

### ISSUE THREAD

**Issue by gianniforesi** [influxdata/telegraf#7227]
### Relevant telegraf.conf:

```toml
holding_registers = [
	{ name = "MW0", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [0]},
	{ name = "MW1", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [1]},
	{ name = "MW2", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [2]},
	{ name = "MW3", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [3]},
... all registers up to the last one ...
	{ name = "MW345", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [345]},
	{ name = "MW346", byte_order = "AB", data_type = "UINT16", scale=1.0,  address = [346]},
 ]

```

### Expected behavior:
I expect to read all register listed in the configuration file.

### Actual behavior:
Error on telegraf log appears:
"quantity 346 must be between 1 and 125".

### Additional info:
If I delete register 100, 200 and 300 from register list, plugin work correct and i can read the olding registers (except fo the ones deleted).

**Comment by garciaolais** [comment]
Hello @gianniforesi 

Today I tested read 1000 registers and I don't see any error 😕 

![image](https://user-images.githubusercontent.com/14133711/81487675-1dd27b00-9225-11ea-9674-5865032cbdea.png)

I attached my config file
[telegraf.txt](https://github.com/influxdata/telegraf/files/4604901/telegraf.txt)

**Comment by garciaolais** [comment]
@gianniforesi 

I sended a PR to fix this issue 

[7488](https://github.com/influxdata/telegraf/pull/7488)

**Comment by helenosheaa** [comment]
@garciaolais @gianniforesi is this issue now closed with the closed above PR?

**Comment by garciaolais** [comment]
@helenosheaa 

https://github.com/influxdata/telegraf/pull/7488 tried solved two issues this one https://github.com/influxdata/telegraf/issues/7227 and https://github.com/influxdata/telegraf/issues/7317.

But https://github.com/influxdata/telegraf/pull/7869 solved https://github.com/influxdata/telegraf/issues/7317 first, for this reason I closed https://github.com/influxdata/telegraf/pull/7488.

Today I downloaded the last version of telegraf and seems that this issue persist, we need to create a new PR.

**Comment by helenosheaa** [comment]
@garciaolais 

Understood, would you be willing to cherry pick from your previous pr?

**Comment by garciaolais** [comment]
> Understood, would you be willing to cherry pick from your previous pr?
Yes, I will cherry picks and test it 🔬 with the last version
