### ISSUE TITLE
Additional internal metrics for influxdb_listener

### ISSUE THREAD

**Issue by pberlowski** [influxdata/telegraf#7230]
## Feature Request

While working on flushing high volume metrics from an application, we've realized that we're lacking the visibility into how long the agent takes to serve a `/write` request to the influxdb_listener. We also noticed that we don't have a good way to understand what is the lag on the points submitted to the  input.

### Proposal:

Introduce additional metrics:
* `internal.http_listener.request_time_ns` - how long does the agent  take to serve a request (per endpont)
* `internal.http_listener.max_age` - what is the max age of measurement submitted in a POST request

This proposal is supported by #7229 

### Current behavior:
The internal metrics are not emitted.

### Desired behavior:
The internal metrics are emitted.

### Use case: 
We're currently working with an application that emits ~6M points/minute. We're tuning the behavior of the agent and of the sending library. The data points provided by these internal metrics are crucial.

**Comment by pberlowski** [comment]
@danielnelson what is needed to push this discussion ahead?

**Comment by powersj** [comment]
next steps: pick this one back up, look at #7229 as inspiration or drive it to completion
