### ISSUE TITLE
inputs.netstat plugin causes high cpu utilization.

### ISSUE THREAD

**Issue by Kedesai** [influxdata/telegraf#7232]
### Relevant telegraf.conf:

```toml
# # Read TCP metrics such as established, time wait and sockets counts.
 [[inputs.netstat]]
   # no configuration

```

### System info:

Red Hat Enterprise Linux Server release 7.3 (Maipo) 36 GB 4 x Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz.
### Steps to reproduce:

We have a problem with netstat plugin which gets all the netstat info to Influxdb. There are some servers which have high wait times  and only on those servers this plugin causes cpu jump to 100% off an on. The CPU usage looks higher all the time.
netstat -an |grep WAIT |wc -l
 6294. 

netstat -an |grep EST |wc -l
135353

This issue happens only on a certain set of servers which have higher WAIT and EST nos.

1. install telegraf default install with Netstat plugin
2. start telegraf.
3. run top on the server.

### Additional info: I got the netstat commands above.

N/A

Kindly let me know if there is a work around or I have to shut off this plugin.

**Comment by danielnelson** [comment]
I believe this is the same issue as #6559, let's continue discussion on that issue.
