### ISSUE TITLE
SqlServer: collect query duration of metric queries

### ISSUE THREAD

**Issue by leepfrog-ger** [influxdata/telegraf#7237]
## Feature Request

For each class of data that is collected the duration of the query that collects the data should be logged to easily allow detection of significant performance changes (e.g. due to updates).

### Use case: 

For me it has happened several times that a new version of the Sqlserver input plugin contained changes that had unexpected impacts on the performance underlying queries that collect the metrics from the SQL server.

If the plugin would collect the duration of its own queries then it would be possible to set thresholds and alerting to easily spot new issues.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you yet. 

The SQL server input plugin is focused around collecting metrics from the server itself. Collecting metrics about the metric collecting itself is a bit out of scope for what the plugin does currently. This really is a monitoring and performance question that could be done with a script + exec input plugin.
