### ISSUE TITLE
ES Input Plugin Should Support Index Tags

### ISSUE THREAD

**Issue by msugas19** [influxdata/telegraf#7238]
## Feature Request
The [Elasticsearch input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/elasticsearch) provides a lot of capabilities for monitoring clusters and provides useful tags for grouping in visualizations. For index-level stats, tags are not exposed with the index name and this prevents micro-level visualizations of how individual indices are performing.

This change has already been made in my private fork and deployed to a test environment, but I wanted to submit this feature request to get any feedback from the community before raising the PR like mentioned in the contributing guidelines

### Proposal:

The ES input plugin should be modified during its collection gathering stage to add additional tags for fine-grained aggregations and querying on a per-index basis. The current example of this is the elasticsearch_clusterhealth_indices metric which supports the index tag

### Current behavior:

elasticsearch_indices tags:

- cluster_name
- node_attribute_ml.enabled
- node_attribute_ml.machine_memory
- node_attribute_ml.max_open_jobs
- node_attribute_xpack.installed
- node_host
- node_id
- node_name

### Desired behavior:

elasticsearch_indices tags:

- cluster_name
- **index**
- node_attribute_ml.enabled
- node_attribute_ml.machine_memory
- node_attribute_ml.max_open_jobs
- node_attribute_xpack.installed
- node_host
- node_id
- node_name

### Use case: 
Support fine-grained visualizations and grouping based on tag which allows to create visualizations with index groupings such as the following:

![es_indices_group_by_index](https://user-images.githubusercontent.com/29410254/77676737-f6ad3c00-6f4b-11ea-9abc-d43330bf528f.png)

**Comment by powersj** [comment]
Hi @msugas19,

It sounds like you had a branch with this change. Given you are adding a single tag I think we would be inclined to accept something like that, but I would reserve judgment till we see the actual PR. Would you be willing to rebase your fork on master and submit your PR?

Thanks!
