### ISSUE TITLE
Is it possible to configure different timeframe for multiple exec to run ?

### ISSUE THREAD

**Issue by mkkhedawat** [influxdata/telegraf#7248]
I have two script execs. one I want to run every 30 sec, another one at 11:30 AM daily.
Telegraf is running as a service.

**Comment by danielnelson** [comment]
We don't have support for running a plugin at an absolute time (but see #1319), the closest would be to have a plugin run "every 24h".  It would look something like this:
```
[[inputs.exec]]
  interval = "30s"
[[inputs.exec]]
  interval = "24h"
```
