### ISSUE TITLE
Question: are metric tags, as consumed by output plugins, guaranteed to be sorted?

### ISSUE THREAD

**Issue by jdef** [influxdata/telegraf#7251]
It looks like the code in the metric/ package make an effort to keep tags sorted. I'm wondering if I can depend on this invariant in my output plugin - that if I iterate over TagList the keys will be in sort-order.

**Comment by danielnelson** [comment]
Yes, you can count on this ordering (lexical bytewise ascending), at least to the degree we discussed in #7202.  Which is to say that we would update any plugins included in the Telegraf repo if we changed this.  I also think if we were to change this, we would rename the method or add a new interface as well.

I will open a PR that adds this as a comment to the Metric interface.

BTW, I have no thoughts to change the ordering, but I have been thinking that we might want to move to an interface more like:
```go
type Metric interface {
    Tags() TagIterator
}

type TagIterator struct {
    Next() Tag
}
```

This would give us better encapsulation, no risk of interface users messing the order up.  It would be a bit slower to iterate over, but we could avoid some full metric copies which would make up for it.

**Comment by jdef** [comment]
Should deprecation docs follow this style?
https://github.com/golang/go/wiki/Deprecated
