### ISSUE TITLE
Stackdriver-output sends everything as Custom metrics, should reuse "standard" agent ones

### ISSUE THREAD

**Issue by bipthelin** [influxdata/telegraf#7259]
Stackdriver-output sends everything as Custom metrics, should reuse "standard" agent ones.

Instead of naively sending everything as Custom Metrics, the Stackdriver-ouput should ideally reuse the "standard" agent ones (https://cloud.google.com/monitoring/api/metrics_agent) for common plugins, such as (Nginx, mem, net, kafka, etc)

Right now the Stackdriver-output is (while technically working well) really unusable due to the fact that Google has a limit on `500` Custom Metrics. Just using some standard plugins, `mem`, `network`, `cpu`, `io`, `kernel`, `processes`, etc. easily get's you passed that limit. We've been in the process for two weeks now getting Google to raise this limit for us and we're currently at `1500` and still hitting the limit and they basically don't want to raise it further.

Here's the error output from Telegraf:
```bash
Mar 31 10:59:00 xxx telegraf[20697]: 2020-03-31T08:59:00Z E! [agent] Error writing to outputs.stackdriver: rpc error: code = ResourceExhausted desc = Your metric descriptor quota has been exhausted.
Mar 31 10:59:30 xxx telegraf[20697]: 2020-03-31T08:59:30Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = ResourceExhausted desc = Your metric descriptor quota has been exhausted
```

**Comment by danielnelson** [comment]
Actually, I didn't know this it possible to write outside of the custom descriptor.  If this is possible it seems like this would be fine but somewhat laborious to manage the mapping and ensure the data is the same format.  After all, our cpu input doesn't create the same metrics as the stackdriver agent.

I also wonder about the external descriptor namespace https://cloud.google.com/monitoring/api/metrics_other, it seems that there are higher descriptor limits for Prometheus metrics, perhaps we could have a `external.googleapis.com/telegraf/` prefix?

**Comment by bipthelin** [comment]
> Actually, I didn't know this it possible to write outside of the custom descriptor. If this is possible it seems like this would be fine but somewhat laborious to manage the mapping and ensure the data is the same format. After all, our cpu input doesn't create the same metrics as the stackdriver agent.
> 
> I also wonder about the external descriptor namespace https://cloud.google.com/monitoring/api/metrics_other, it seems that there are higher descriptor limits for Prometheus metrics, perhaps we could have a `external.googleapis.com/telegraf/` prefix?



> Actually, I didn't know this it possible to write outside of the custom descriptor. If this is possible it seems like this would be fine but somewhat laborious to manage the mapping and ensure the data is the same format. After all, our cpu input doesn't create the same metrics as the stackdriver agent.
> 
> I also wonder about the external descriptor namespace https://cloud.google.com/monitoring/api/metrics_other, it seems that there are higher descriptor limits for Prometheus metrics, perhaps we could have a `external.googleapis.com/telegraf/` prefix?

I think getting your own descriptor domain such as `external.googleapis.com/telegraf/` seems like probably the best way forward. Which unfortunately mean that Google is setting the time table for when this can become useful

**Comment by awolde** [comment]
Getting the same issue here, were you able to resolve your issue? A brand new project and I'm already reached my limit. @bipthelin

**Comment by bipthelin** [comment]
> Getting the same issue here, were you able to resolve your issue? A brand new project and I'm already reached my limit. @bipthelin

No unfortunately. I had a open support ticket with Google and they raised the thresholds but they refused to go above `1500`. Maybe we could've done some stuff in the  metrics but at the end of the day we gave up on it.

I think if we are to try it again we'd use the "standard" collector from Google (which seems to be a fork of Collectd)

**Comment by powersj** [comment]
Hi,

Getting our own external descriptor namespace does not seem like something in plan for now. I have not seen many additional comments or questions regarding this topic, so I am going to close this for now. 

Thanks
