### ISSUE TITLE
Add units of measurement for registers to modbus input plugin

### ISSUE THREAD

**Issue by orbweaver** [influxdata/telegraf#7260]
## Feature Request
Add units of measure to modbus input plugin
Opening a feature request kicks off a discussion.

### Proposal:
Would love to be able to specify units of measurement (i.e. Pressure, Hz, Temperature, etc) modbus registers
### Current behavior:
no input for "units" field
### Desired behavior:
add a field called "units" or something similar for each register that gets passed through verbatim.  this could allow for any unit to be specified and help with future processing.  

### Use case: 
output processing may need to know what units are being measured for reporting, conversion or scaling.

**Comment by danielnelson** [comment]
The most common way we model this is by suffixing the field key: `used_bytes`, `temp_celsius`.  I don't recommend having a dedicated `unit` field, because that presupposes that you will have only a single value containing field.

**Comment by orbweaver** [comment]
Thanks for the prompt response.  That makes sense.   I'll use the suffix on the field key that you described.
