### ISSUE TITLE
The initilization of mqq.ClientOptions in mqtt_consumer.go

### ISSUE THREAD

**Issue by eyauwag** [influxdata/telegraf#7261]
In the init fuction of mqtt_consumer.go, New() function needs ClientFactory parameters. The ClientFactory is one function type func(o *mqtt.ClientOptions) Client. The implementation passed the func  to it indeed. But how  does the paramer mqtt.ClientOptions passed?
I know that function Init() will get one ClientOptions by mqtt.NewClientOptions(). But what's the relationship between this ClientOptions with the New() function.

func init() {
	inputs.Add("mqtt_consumer", func() telegraf.Input {
		return New(func(o *mqtt.ClientOptions) Client {
			return mqtt.NewClient(o)
		})
	})
}

**Comment by danielnelson** [comment]
The options themselves are built in the `func (m *MQTTConsumer) Init() error` function and more specifically `func (m *MQTTConsumer) createOpts() (*mqtt.ClientOptions, error)`.  This function doesn't get called until much later as part of the plugins Start method.

I'm not sure that answers your question, what are you trying to accomplish?

**Comment by eyauwag** [comment]
I have understood the design. Thank you.
