### ISSUE TITLE
input solr 8 support

### ISSUE THREAD

**Issue by BenjaminLeibinger** [influxdata/telegraf#7264]
## Feature Request

Currently the solr plugin only supports solr 3.5 to 7. But the latest stable release of solr is 8.5. 

### Current behavior:

The plugin reads stats for core and admin but the update and request handler does not work. 

The stats are still available: 
https://lucene.apache.org/solr/guide/8_2/performance-statistics-reference.html

### Use case:

Support solr 8.* monitoring.

**Comment by danielnelson** [comment]
Thanks for opening the issue, looks like this plugin needs redone to support the new metrics api.

I wonder if you might be able to get the current plugin to work if you enable JMX and the [mbean request handler](https://lucene.apache.org/solr/guide/8_2/mbean-request-handler.html).

**Comment by vikkyomkar** [comment]
I will give it a try and raise PR ASAP

**Comment by anthosz** [comment]
Hi,

Probably related to #6355

@vikkyomkar did you have time to raise a PR?

Best regards,

**Comment by srebhan** [comment]
@BenjaminLeibinger please test the binary in PR #13699 which adds support for Solr version 7 and newer. Let me know if this fixes the issue!
