### ISSUE TITLE
Inserting UTF-8 characters fails

### ISSUE THREAD

**Issue by burton666** [influxdata/telegraf#7270]
I have tried inserting data using telegraf and powershell but all text containing nordic characters (åäöÅÄÖ) gets replaced with a black box with an questionmark when stored in influxdb.

When I just use write-data in powershell it displays fine. I tried both posting directly to influxdb and using write-host in the powershell that is specified in the telefgraf.config.

```
$data="test`,host=$env:computername name=""Ölburk"""
Invoke-WebRequest -Uri "http://<InfluxDB>:8086/write?db=telegraf" -Method POST -Body $data

#Write-Host $data
```

**Comment by R-Studio** [comment]
What is the encoding of your script? (with BOM or without?)

_PS: Maybe this is a solution for you: https://github.com/markwragg/PowerShell-Influx_

**Comment by burton666** [comment]
The encoding is UTF-8 with BOM

**Comment by danielnelson** [comment]
> I have tried inserting data using telegraf and powershell but all text containing nordic characters (åäöÅÄÖ) gets replaced with a black box with an questionmark when stored in influxdb.

How are you inserting data into Telegraf?  Are you using the `exec` input?

**Comment by R-Studio** [comment]
@burton666 then change your encoding to UTF-8 without BOM and test it again.

**Workaround (but not recommended) **
_But notice this is beta. _

https://wiki.webperfect.ch/index.php?title=GitLab:_Runner_(Windows)#Encoding_Issue_in_GitLab

**Comment by burton666** [comment]
> > I have tried inserting data using telegraf and powershell but all text containing nordic characters (åäöÅÄÖ) gets replaced with a black box with an questionmark when stored in influxdb.
> 
> How are you inserting data into Telegraf? Are you using the `exec` input?

Yes, that is correct

**Comment by burton666** [comment]
> @burton666 then change your encoding to UTF-8 without BOM and test it again.
> 
> **Workaround (but not recommended)**
> _But notice this is beta._
> 
> https://wiki.webperfect.ch/index.php?title=GitLab:_Runner_(Windows)#Encoding_Issue_in_GitLab

I have tested that too and the only change is that I get two questionmarks in that case.

**Comment by R-Studio** [comment]
hmmm ok, then the last idea that I have is add following parameters to your webrequest:
`-ContentType  'application/json; charset=utf-8`

**Comment by burton666** [comment]
Ahh, Just before seeing your post I tried with "-ContentType 'text/html; charset=UTF-8" and now the characters are inserted correctly.
Is there some way to configure this in the telegraf.conf?

**Comment by R-Studio** [comment]
unfortunately I am very using telegraf, so I don't know. :(

**Comment by burton666** [comment]
I do not know how to fix this but I solved it by using Invoke-Webrequest in the script to post the data to therver instead of using Write-Host

**Comment by danielnelson** [comment]
I wouldn't suggest writing directly to InfluxDB from an `exec` input, although this might be a good tip with the `exec` output.  Doing this bypasses the normal processors -> aggregators -> outputs flow and you wouldn't have write batching or retries.

I think adding the first line here should set the console encoding to utf-8.  Let me know if it works and we can add it to the README:
```
[Console]::OutputEncoding = New-Object -typename System.Text.UTF8Encoding
$data="test,host=$env:computername name=""Ölburk"""
Write-Host $data
```

**Comment by burton666** [comment]
Thanks, but I get a error saying that there is something wrong with the reference handle:

```
Exception setting "OutputEncoding": "Referensen (handle) är felaktig.
"
At C:\Program Files\Telegraf\Scripts\Office_lookup.ps1:24 char:1
+ [Console]::OutputEncoding = New-Object -TypeName System.Text.UTF8Enco ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

**Comment by burton666** [comment]
Ah, Sorry even tho I get an error-message it still works.
