### ISSUE TITLE
Input-Plugin Disk: cannot collect information about windows mountpoints (CSV)

### ISSUE THREAD

**Issue by R-Studio** [influxdata/telegraf#7272]
### Relevant telegraf.conf:
```
[[inputs.disk]]
```

### System info:
I use Hyper-V on Windows Server 2016 Core and I will monitor our Cluster Shared Volumes (CSV), but the input-plugin "disk" cannot collect the metrics from Windows Mountpoints.
**For example:** I have a Disk/Volume mounted on "C:\ClusterStorage\CSV01". 

**Tested**
Telegraf Version: 1.12.6 & 1.14.0
Windows Server 2016 Core
Filesystem of the CSVs: CSVFS (its the same as NTFS but for "sharing")

### Steps to reproduce:
1. Create a Failover Cluster
2. Create a CSV
3. Use the input plugin "disk" with no exclusions

### Expected behavior:
In Influx I can see the mountpoints in the measurement "disk" -> "paths" with the path "C:\ClusterStorage\CSV01" and in "device" as "CSV01" (this is the volume name).

### Actual behavior:
I can't see these CSV-Disks, I only see my volumes C: and D:.

### Additional Informations:
- Maybe because the plugin collects no volumes with the fstype "CSVFS" and you can use the same way to collect the data as with a NTFS volume.
- Maybe the "disk" plugin does not support windows mountpoints.

_Maybe this is a feature request instead of a bug._

**Comment by R-Studio** [comment]
_Perhabs this is also a solution for the following closed request #6010:_

**Comment by danielnelson** [comment]
Could you run this executable and add the output: [7272.zip](https://github.com/influxdata/telegraf/files/4424639/7272.zip)

Or, if you prefer, here is the Go source so you can compile and run it with `go run main.go`:
```go
package main

import (
        "fmt"

        "github.com/shirou/gopsutil/disk"
)

func main() {
        fmt.Println(disk.Partitions(true))
}
```

**Comment by R-Studio** [comment]
> Could you run this executable and add the output: [7272.zip](https://github.com/influxdata/telegraf/files/4424639/7272.zip)
> 
> Or, if you prefer, here is the Go source so you can compile and run it with `go run main.go`:
> 
> ```go
> package main
> 
> import (
>         "fmt"
> 
>         "github.com/shirou/gopsutil/disk"
> )
> 
> func main() {
>         fmt.Println(disk.Partitions(true))
> }
> ```

this is the output from the main.exe:
`[{"device":"C:","mountpoint":"C:","fstype":"NTFS","opts":"rw.compress"} {"device":"D:","mountpoint":"D:","fstype":"NTFS","opts":"rw.compress"}] <nil>`


_PS: thanks for any help_

**Comment by R-Studio** [comment]
any news?

**Comment by R-Studio** [comment]
@danielnelson any news about this?

**Comment by powersj** [comment]
@R-Studio,

In your post with the code which imports gopsutil, it only showed the C and D drivers as well. That means that gopsutil itself is not picking up the CSVFS devices.

If you are still interested in this, the next step would be for you to file an upstream issue with gopsutil asking for support of the CSVFS devices.

Thanks!

**Comment by R-Studio** [comment]
@powersj thanks for your help. 👍
In the meanwhile I changed my employer and I am working on other stuff so this is not ungent for me or my employer. That's the reason why I close this Issue.
