### ISSUE TITLE
monit - adding socket support

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#7273]
Hello

## Feature Request
Adding socket support for monit input if we don't use http(s) listener

### Proposal:
Adding socket support for monit input

### Current behavior:
Only http & https are supported
If we try to use unix socket:
2020-04-02T15:47:29Z E! [inputs.monit] Error in plugin: Get unix:///blah/foo/bar/monit.sock/_status?format=xml: unsupported protocol scheme "unix"

### Desired behavior:
Adding support of unix socket

### Use case: 
Allow to connect to monit without http/https protocol enabled

cc @SirishaGopigiri @danielnelson

**Comment by danielnelson** [comment]
Would be happy to merge a pull request for this feature.

**Comment by anthosz** [comment]
All instances moved from sockets to https, feature not needed anymore.

Closed
