### ISSUE TITLE
Code signing for binaries

### ISSUE THREAD

**Issue by mihaiturcu** [influxdata/telegraf#7274]
## Feature Request
Code sign telegraf binaries to allow tighter controls for enterprises regarding applications that run inside their environment

### Proposal:
Buy a code signing cert and sign all binaries you release.

### Current behavior:
Binaries are not code signed.

### Desired behavior:
Binares are code signed.

### Use case: 
Enterprise AV software solutions commonly have the option of whitelisting via file hash and/code signing certificate trust. This would help enterprises with tighter access control requirements leverage telegraf.

Thanks

**Comment by danielnelson** [comment]
We do have GPG signatures for all releases.  Using the download links and add `.asc` to the package you want:
```
https://dl.influxdata.com/telegraf/releases/telegraf_1.14.0-1_amd64.deb
https://dl.influxdata.com/telegraf/releases/telegraf_1.14.0-1_amd64.deb.asc
```

The public key for these is at `https://repos.influxdata.com/influxdb.key`

There are quite a few other ways to sign packages, depending on the platform and distribution method.  What platforms and packages are you most interested in?

**Comment by mihaiturcu** [comment]
Windows platforms mostly.

**Comment by danielnelson** [comment]
Let's merge this issue with #6423
