### ISSUE TITLE
InfluxDB v1.x Output Plugin and socket

### ISSUE THREAD

**Issue by dgkanatsios** [influxdata/telegraf#7279]
Tried to use [InfluxDB v1.x Output Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb) to write influx data to domain socket, since this is mentioned in the default conf

```
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
```

However, it seemed that the plugin sends HTTP requests. Does  InfluxDB v1.x Output Plugin support socket or we should use [socket_writer](https://github.com/influxdata/telegraf/blob/release-1.14/plugins/outputs/socket_writer/README.md)?

Thank you!

**Comment by danielnelson** [comment]
The InfluxDB output supports HTTP over IP/Unix stream sockets or UDP over an IP socket.  I don't think there is a way to directly write to a Unix socket, if I'm wrong can you link the docs?

**Comment by dgkanatsios** [comment]
Gotcha, thanks @danielnelson. So the socket_writer output plugin shouldn't work?

**Comment by danielnelson** [comment]
No, I don't think so.  I believe the only way to write over an Unix socket is with HTTP.
