### ISSUE TITLE
Question: does an Output plugin's Write() need to be goroutine-safe?

### ISSUE THREAD

**Issue by jdef** [influxdata/telegraf#7280]
I was reviewing `agent` internals and noticed that calls to the output model (which invokes an Output plugin) are executed in a goroutine:

https://github.com/influxdata/telegraf/blob/6445e775cfb7f11954cadae12e0b082959d2e295/agent/agent.go#L607

.. and that neither the `agent` or output model actually wait for a stalled invocation of an Output plugin's Write() func. The agent logs a warning that a flush took longer than expected. But it appears feasible (and likely to happen at some point) that multiple calls to an Output plugin's Write() func could end up executing concurrently.

Can someone please confirm (or deny) this?

**Comment by danielnelson** [comment]
The Write method does not need to be thread safe, it will never be called concurrently.  This is actually true for all methods on the plugin interfaces, the only reason to lock is for goroutines started within the plugin itself.

**Comment by sjwang90** [comment]
@jdef Feel free to re-opn if this still needs to be addressed.
