### ISSUE TITLE
[logparser] Allow optional removal of full path for path` field

### ISSUE THREAD

**Issue by kir4h** [influxdata/telegraf#7290]
### Proposal:

Add an optional setting to the logparser input plugin so that the `path` contains the basename for the log file instead of the full path.

### Current behavior:

Given a file `/var/log/myfolder/mycustomjob.log` 

The tag `path=/var/log/myfolder/mycustomjob.log` will be added to the measurement

### Desired behavior:

Given the same file, with this new boolean enabled, the resulting tag would be:

`path=mycustomjob`

### Use case

Having this shorter version of the `path` tag results in a much more friendly visualization, since we are not usually that interested in the base folder or the file extension but rather the file name itself which should give us some context of what the log file is about. (there are cases where this might not be true or suitable, hence my proposal of making this optional)

I know this can already be achieved by the usage of a `regex` process filter, but this sounds like a common use case so I was thinking it would be nice to have.

This could also be implemented by adding a new `tag` (`path_basename` or similar) instead of changing the content of `path` tag.

I can work on this issue if you think it's worth it.

**Comment by ssoroka** [comment]
You said you would implement this with a path_basename tag, but I imagined instead that this would be a setting, and that you would strip the path_basename from the start of the path tag. Is that the plan?

**Comment by kir4h** [comment]
I was thinking of 2 possible approaches:
1. New setting that enables this behavior, defaulting to `false` for backwards compatibility
2. New tag (`path_basename` or whatever name we agree on)

Personally, I would go for `1`

**Comment by kir4h** [comment]
Thanks for your comments @ssoroka!

If we go with a `strip_path_prefix` we are giving flexibility but handling subfolders would be a little more tricky since we need to handle glob patterns and `super asterisk`:

Given this configuration

```
files = ["/var/log/**.log"]
```
And a file `/var/log/myfolder/asubfolder/mylog.log`. 

We should have `strip_path_prefix=/var/log/**/` (as a way of telling I want to strip the folder) and then for each file find the common path between the file and the prefix to strip it.

Also, a new second variable (either `strip_path_extension=true`  or `strip_path_suffix=".log"`) should be added if we want to get rid of the extension.

My initial approach was to have a simple variable for a specific use case that might be common (remove folder plus extension).  I guess it's a matter of flexibility vs. complexity (from my little knowledge of `telegraf` so far I have the impression flexibility falls more in the processor side).

Anyway if you think `strip_path_prefix` is a better approach for this scenario I'm also happy to go this way.

**Comment by ssoroka** [comment]
hmm. I was hoping to keep it simple, but I think if you want total flexibility you're back to the regex pattern. 

If we want to try to keep it simple, I think these are all good options, and you could maybe support all of them without much effort:
strip_path_preffix = "/path"
strip_path_suffix = ".log"
strip_path = false
strip_extension = false

**Comment by kir4h** [comment]
Just to ensure we are on the same page

```
# Will remove a static prefix from path
strip_path_prefix = "/path"
# Will remove a static extension from path (if we have 'a.log' and 'b.txt' only 'a.log' will be affected
strip_path_suffix = ".log"
# Will remove the folder, leaving only the file name. Overrides strip_path_prefix.
strip_path_folder = false
# Will remove the file extension. Overrides strip_path_suffix
strip_path_file_extension = false
``` 

With the "overrides" statement I mean to simplify the logic (either we use one or the other) to avoid having a file `a.log.txt` (weird I know, just for demonstration) and expecting it to become `a` just because we configured `strip_path_suffix=".log"` and `strip_path_file_extension=true`.  (in such scenario if strip extension is not exclusive with strip_suffix the order in which they are applied matters, adding unneeded complexity imo)

**Comment by ssoroka** [comment]
looks good, we're on the same page. I wouldn't worry too much about the edge cases of .log.txt. I agree if they've used one of the boolean options you don't need to check the others.

Do you want to take a shot at implementing it?

**Comment by kir4h** [comment]
> Do you want to take a shot at implementing it?

Sure, I will give it a try over the week end

**Comment by kir4h** [comment]
Closing this issue, the functionality will be provided through a dedicated filepath processor (see https://github.com/influxdata/telegraf/issues/7342)
