### ISSUE TITLE
Syslog plugin does not accept messages from rsyslog in UDP

### ISSUE THREAD

**Issue by FrankyBoy** [influxdata/telegraf#7291]
Reference: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog

> Syslog messages should be formatted according to RFC 5424.
> 
>     # uncomment to use udp according to RFC 5424
>     #*.* @127.0.0.1:6514;RSYSLOG_SyslogProtocol23Format

telegraf config:
```
[[inputs.syslog]]
    server = "udp://0.0.0.0:6514"
```

rsyslog config:
```
if $syslogfacility-text != "daemon" and $programname !='influxd' then {
    *.* @127.0.0.1:6514;RSYSLOG_SyslogProtocol23Format
}
```

resulting output in telegraf logs:
```
E! [inputs.syslog] Error in plugin: expecting a structured data parameter (`key="value"`, both part from 1 to max 32 US-ASCII characters; key cannot contain `=`, ` `, `]`, and `"`, while value cannot contain `]`, backslash, and `"` unless escaped) [col 365]
```

**Comment by ssoroka** [comment]
Do you get any different results with `framing = "non-transparent"` ?

Any chance you can capture one of the UDP packets to see what we're trying to parse?

**Comment by FrankyBoy** [comment]
I assume that should go into the telegraf-config? I'll try it out tomorrow (close to midnight here). Not sure if I'll manage to capture any packages, am a huge linux noob (sorry).

**Comment by FrankyBoy** [comment]
Ok so running UDP dumps was incredibly helpful (and way less effort than I thought). I've learned that ... 
* messages from gunicorn on test (old syslog format) -> rsyslog -> telegraf actually seem to work fine in my testing, but get logged on ip and not hostname, which is why they never showed up in the filter (because old format does not include hostname -> incoming ip is used).
* surprising enough I don't see messages from the prod system at the same time (but I do see packages arriving from nginx on the same machine directly to telegraf ... yep ...) ... guess this is one for the IT-Admin to figure out at some later point.
* source of original errors must be something else (I'm thinking it could be the postgres load reports but I need to dig deeper / do more correlations)

Honestly, if I can somehow help it, I'm thinking of ditching rsyslog, and somehow forcing gunicorn (just uses pythons own SysLogHandler anyway) to write proper RFC5424 messages directly into telegraf. There seem to be a bunch of codebases that do this, and it would get rid of some headaches in the transition.

**Comment by ssoroka** [comment]
Sounds good. It sounds like the original issue is resolved, so I'm going to close this ticket, but feel free to open another if you need anything. If all else fails, you could always write your own input, which with the new [execd input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd), can be in any language and runs as a separate process.

**Comment by FrankyBoy** [comment]
Finally got it to work (mainly because no time yesterday ;) ) ... the setup that I've ended up with:
* ditch rsyslog ... I'll try to do that everywhere as far as possible as it just seems to cause greef
* in python use the [rfc5424-logging-handler](https://pypi.org/project/rfc5424-logging-handler/), which works like a charm out of the box
* from my app, target the _local_ telegraf installation (got that anyhow because metrics) via UDP instead of the one on the logging server (should have worked, listened publicly, but somehow it didn't ... oh well, nothing lost).
