### ISSUE TITLE
Sql Server - Support for SQL Server 2008

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7292]
## Feature Request

Edit the v2 queries to make them compatible with older editions of SQL server, like SQL 2008 and 2008 R2.
Some queries are already compatible with SQL Server 2008 R2.

Of course, it's not possible to achieve full compatibility and some fields will be missing but lots of information can be gathered.

**Edit:**
The initial idea was to make retro compatibility up to SQL Server 2005, which is doable for the queries themselves, but it's not for the plugin, in fact the "go-mssqldb" library has some limitations.
It supports:
- SQL Server 2008 SP3 with CU pack 3 (and later, latest version is SQL 2008 SP4)
- SQL Server 2008 R2 SP2
Any previous version will return an error when trying to connect.

### Proposal:
Make the queries more compatible
### Current behavior:
Most query won't run on version pre SQL 2008 R2
### Desired behavior:
being able to monitor SQL Server 2008 and 2008 R2
### Use case: 
Monitor the older version of SQL Server, because you can't just throw old instances in the garbage.
Even if you won't have the same data a SQL 2012+ can offer, something is better than nothing.

**Comment by Trovalo** [comment]
After making some tests I've found out that even if the queries can be edited to be compatible with older versions, there is an issue in the "go-mssqldb" library used by the plugin, which won't allow you to connect to the database.
it is a known issue:
> SQL Server 2008 and 2008 R2 engine cannot handle login records when SSL encryption is not disabled. To fix SQL Server 2008 R2 issue, install SQL Server 2008 R2 Service Pack 2. To fix SQL Server 2008 issue, install Microsoft SQL Server 2008 Service Pack 3 and Cumulative update package 3 for SQL Server 2008 SP3.

**Comment by danielnelson** [comment]
Thanks for researching this, so long as it doesn't introduce too much more complexity I think it would be good to support what we are able to.
