### ISSUE TITLE
filecount on nfs mount

### ISSUE THREAD

**Issue by cs35-owncloud** [influxdata/telegraf#7295]
Hello everyone,

I'm trying to use the [filecount plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filecount) on an NFS mount, but it does not seem to count anything.

### Relevant telegraf.conf:

```toml
[[inputs.filecount]]
  directories = [
    '/etc/telegraf/',
    '/var/owncloud/data/*/files_trashbin/'
   ]
```
The directory **/var/owncloud/data/*/files_trashbin/** here is an NFS mount.

### System info:

* Debian 9
* Telegraf 1.14

### Steps to reproduce:

1. Mount an NFS share on your machine
2. Configure /etc/telegraf/telegraf.d/inputs_filecount.conf with two **directories**, an NFS mount and the **/etc/telegraf** directory as a control.
3. Run this command:

```
# sudo -u telegraf telegraf --config-directory=/etc/telegraf --test --input-filter=filecount
2020-04-08T06:41:19Z I! Starting Telegraf 1.14.0
2020-04-08T06:41:19Z I! Using config file: /etc/telegraf/telegraf.conf
> filecount,directory=/etc/telegraf,host=xxx count=14i,size_bytes=1629i 1586328079000000000
```

### Expected behavior:

The files in the NFS mount should be counted, I guess ?

### Actual behavior:

Only the **/etc/telegraf** directory gets its files counted.

I don't know if it's a bug of if I should simply do this on the NFS server, but I'd rather do this on the clients. If you need more information, let me know :)
Thanks for your help.

**Comment by ssoroka** [comment]
Some thoughts:
- check permissions
- try running with --debug for more info
- try turning on the follow_symlinks option.

Let us know if that sheds any more light on the problem

**Comment by cs35-owncloud** [comment]
Hello,

thanks for your suggestions !
Running with --debug does not give much more information:

```
sudo -u telegraf telegraf --debug --config-directory=/etc/telegraf --test --input-filter=filecount

2020-04-08T16:26:43Z I! Starting Telegraf 1.14.0
2020-04-08T16:26:43Z I! Using config file: /etc/telegraf/telegraf.conf
2020-04-08T16:26:43Z D! [agent] Initializing plugins
> filecount,directory=/etc/telegraf,host=demo-infra count=13i,size_bytes=1476i 1586363204000000000
```

The follow_symlinks is not better.

But you're right about the permissions, I have something weird with the NFS group permissions, I forgot about it, I'm that dumb :S
Thanks for your help and sorry for bothering !
Cheers.

**Comment by cs35-owncloud** [comment]
Hello,

I thought I'd give the solution I'm using, it could help someone someday. First it's not telegraf related.
So my problem was that I couldn't cross a directory on an NFS mount. UIDS and GIDS were the same both on the server and the client. Permissions were 750, and the user I wanted to go in that directory was in the group. I didn't have more than 16 groups which is a known NFS problem. The problem was clearly NFS related and can be solved by editing on the NFS server the file **/etc/default/nfs-kernel-server** and removing the option **--manage-gids**. Then restart the NFS server, a reload is not sufficient.
Cheers  :)

**Comment by ssoroka** [comment]
Thanks @cs35-owncloud, appreciate the update!
