### ISSUE TITLE
modbus scaling for FLOAT32-IEEE data_type doesn't scale

### ISSUE THREAD

**Issue by orbweaver** [influxdata/telegraf#7297]
### Relevant telegraf.conf:

```toml
{ name = "Air Temp Celsius", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=0.001, address = [64,65]},
```

### System info:
Centos 8 x86_64

### Steps to reproduce:

1. edit modbus.conf to include line:
{ name = "Air Temp Celsius", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=0.001, address = [64,65]},
changing the scale from "1.0" to "0.001"
2. run: telegraf --config modbus.conf --test

### Expected behavior:
value from PLC should have decimal moved three digits to left, i.e. "13987" would be "13.987"

### Actual behavior:

output when scale=1.0
modbus, host=scata.ent.net,name=egx150.ent.net,type=input_register Air\ Temp\ Celsius=13957.5419971875 1586365902000000000

output when scale is 0.001
modbus, host=scata.ent.net,name=egx150.ent.net,type=input_register Air\ Temp\ Celsius=13957.5634765625 1586365980000000000

**Comment by garciaolais** [comment]
Hello @orbweaver 

to get 13.987 value in FLOAT32-IEEE with your actual configuration you must need to have two values in your PLC.

![image](https://user-images.githubusercontent.com/14133711/81486765-bf090380-921c-11ea-97a6-2b901e8e4516.png)

but if in your PLC you have _13987_, you need this configuration

![image](https://user-images.githubusercontent.com/14133711/81486840-4f474880-921d-11ea-95e9-ee161799b6e0.png)

**{ 
    name = "Air Temp Celsius-Float32",
    byte_order = "CDAB",
    data_type = "FLOAT32",
    scale=0.001, 
    address = [64,65]
},**

I hope this information help you

**Comment by orbweaver** [comment]
Thanks, this is close but not exactly my situation.  When I ask for FLOAT32-IEEE from the PLC I receive something like 13907.5419971875, which I need to scale down in order to get the accurate reading.  If I ask for FLOAT32, it's a number that doesn't make any sense.  I wish I had control over the PLC program then I could do the math and store the correct number in a register.

**Comment by garciaolais** [comment]
Can you share with us the register value for Register 64 and Register 65 and the value that you expected?

**Comment by orbweaver** [comment]
The values are correct in the PLC.  That number is what the PLC programmer wants to use. I talked with the PLC vendor and they are asking me to scale the large (i.e. 13907.5419971875) number after receiving it from the PLC.  when I attempt to use "scale=0.001" it doesn't move the decimal point.

**Comment by orbweaver** [comment]
Just ran a quick test to get the individual registers for comparison.  I'm not sure what I'm looking for but hope this helps....
Registers [64,65] as FLOAT32-IEEE:  16668.46875
Register [64] as INT16:  14576
Register [65] as INT16:  18050

the expected value is the 16668.46875 found in registers [64,65].  When I try to set scale to 0.001, it still returns 16668.46875.

**Comment by sjwang90** [comment]
@garciaolais Do you have any insight?

**Comment by garciaolais** [comment]
@sjwang90 

Sorry for the delay, Well I think that conversion it's not ok

Register [64] as INT16: 14576 = 0x38F0
Register [65] as INT16: 18050 = 0x4682
 0x38F04682 to  FLOAT32-IEEE it's not 16668.46875, must  be 0.00011457224900368601

https://babbage.cs.qc.cuny.edu/IEEE-754.old/32bit.html
![image](https://user-images.githubusercontent.com/14133711/108617058-dcd4dd00-73d8-11eb-975b-2938bd35efa5.png)

https://www.h-schmidt.net/FloatConverter/IEEE754.html
![image](https://user-images.githubusercontent.com/14133711/108617067-e78f7200-73d8-11eb-9179-810578b30572.png)

I added to my test all these cases🔬

```
{
			name:      "register64_register65_abcd_float32_ieee_scaled-x1",
			address:   []uint16{64, 65},
			quantity:  2,
			byteOrder: "ABCD",
			dataType:  "FLOAT32-IEEE",
			scale:     1,
			write:     []byte{0x38, 0xF0, 0x46, 0x82},
			read:      float32(0.00011457224900368601),
		},
		{
			name:      "register64_register65_abcd_float32_ieee_scaled-x.1",
			address:   []uint16{64, 65},
			quantity:  2,
			byteOrder: "ABCD",
			dataType:  "FLOAT32-IEEE",
			scale:     .1,
			write:     []byte{0x38, 0xF0, 0x46, 0x82},
			read:      float32(1.14572249003686e-05),
		},
		{
			name:      "register64_register65_abcd_float32_ieee_scaled-x.01",
			address:   []uint16{64, 65},
			quantity:  2,
			byteOrder: "ABCD",
			dataType:  "FLOAT32-IEEE",
			scale:     .01,
			write:     []byte{0x38, 0xF0, 0x46, 0x82},
			read:      float32(1.14572249003686e-06),
		},
		{
			name:      "register64_register65_abcd_float32_ieee_scaled-x.001",
			address:   []uint16{64, 65},
			quantity:  2,
			byteOrder: "ABCD",
			dataType:  "FLOAT32-IEEE",
			scale:     .001,
			write:     []byte{0x38, 0xF0, 0x46, 0x82},
			read:      float32(1.14572249003686e-07),
		},
		{
			name:      "register64_register65_abcd_float32_ieee_scaled-x10",
			address:   []uint16{64, 65},
			quantity:  2,
			byteOrder: "ABCD",
			dataType:  "FLOAT32-IEEE",
			scale:     10,
			write:     []byte{0x38, 0xF0, 0x46, 0x82},
			read:      float32(0.00114572249003686),
		},
```

and all the test passed ✔✔

![image](https://user-images.githubusercontent.com/14133711/108617262-6fc24700-73da-11eb-92a1-bab5517b6c10.png)

**Comment by sjwang90** [comment]
Thanks @garciaolais for your tests. Let's close this for now. @orbweaver if you're still running into issues please post your questions in the #telegraf channel in our [Community Slack](influxdata.com/slack).
