### ISSUE TITLE
Support non utf-8 encodings in the tail input 

### ISSUE THREAD

**Issue by kOstovic** [influxdata/telegraf#7299]
## Feature Request

Proposal:
The tail input should allow processing text files that are not utf-8 encoded.

Current behavior:
Files with alternative encodings either cannot be parsed or are not encoded properly.

Desired behavior:
Be able to select a text encoding in the input file, if selected the data will be converted internally to utf-8.

[[inputs.tail]]
  encoding = "UTF-16"

Same to this feature request for file plugin, but new one is for tail input plugin

https://github.com/influxdata/telegraf/issues/6876

**Comment by danielnelson** [comment]
@kOstovic Would you be able to test this functionality in the latest 1.15.0 [release candidate](https://github.com/influxdata/telegraf/releases/tag/v1.15.0-rc2) to make sure it is working as needed?  In order to allow resuming in the middle/end of the file it is required to specify little or big endian with utf-16.

```toml
  ## Character encoding to use when interpreting the file contents.  Invalid
  ## characters are replaced using the unicode replacement character.  When set
  ## to the empty string the data is not decoded to text.
  ##   ex: character_encoding = "utf-8"
  ##       character_encoding = "utf-16le"
  ##       character_encoding = "utf-16be"
  ##       character_encoding = ""
  # character_encoding = ""
```

**Comment by kOstovic** [comment]
Hi, it has been put to backlog with high priority, but it may take some
time to test it, feel free to release it if there is some hurry

**Comment by kOstovic** [comment]
Hello, we have tried and it works for all of our usecases, thank you
