### ISSUE TITLE
 Add the ability to specify a file with token for the HTTP input plugin.

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#7303]
### Proposal:
Add the ability to specify a file with token for the HTTP input plugin like in kubernetes plugins.

### Current behavior:
At the moment, it is not possible to set the authorization header without specifying the token explicitly in the configuration file. The use of environment variables for this task is also not suitable, since for this we must already have a token.

### Desired behavior:
The bearer_token parameter for the plugin, indicating the file from which to read the authorization token, which will then be added to the headers. This will allow delivering the agent to a protected environment when we should not see the token, but only indicate where to look for it.

### Use case:
This request is related to issue #7184. We put an agent that collects data from the Kubernetes API directly into the cluster, but we do not have the ability to access the token file.

**Comment by M0rdecay** [comment]
@ssoroka hello! Have you made any decision? This functionality is now very lacking for us.

**Comment by ssoroka** [comment]
I think we're good with this. I'm just waiting on another review to merge. I'll poke one of the team. 👍
