### ISSUE TITLE
SQL server instance status

### ISSUE THREAD

**Issue by sgrajan1** [influxdata/telegraf#7313]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
If instance is down or port not reachable it should report paramete rsql_instanace_status=0
### Current behavior:
If instance not reachable its not getting value
### Desired behavior:
change value sql_instance_status=

**Comment by danielnelson** [comment]
If you enable the `internal` input plugin, I expect that this will increment the error field for this plugin.  This is our general pattern for collection errors within the plugin, but I also recommend setting up a dead-man alert in case Telegraf can't report for some reason.  We have found that this is a more robust reporting method compared to attempting to positively assert a failure.
