### ISSUE TITLE
[inputs.nginx] Error in plugin: EOF

### ISSUE THREAD

**Issue by ichasco** [influxdata/telegraf#7314]
### Relevant telegraf.conf:

```
[[inputs.nginx]]
  urls = ["http://${NGINX_HOST}:9080/nginx_status"]
  response_timeout = "5s"

[[inputs.nginx_vts]]
# https://github.com/influxdata/telegraf/blob/release-1.14/plugins/inputs/nginx_vts/README.md
  urls = ["http://${NGINX_HOST}:9080/nginx_status"]

```

### System info:

Telegraf 1.14.0 (git: HEAD fefd7ff1)

### Docker

Docker version 19.03.5, build 633a0ea838

### Nginx

nginx version: nginx/1.17.9

status.conf

```
server {
    listen 9080;
    set $request_start_time '$time_iso8601';
    location /nginx_status {
        stub_status     on;
        access_log      off;
        auth_basic      off;
        vhost_traffic_status_display;
        vhost_traffic_status_display_format json;
    }
}
```

### Steps to reproduce:

1. Configure Nginx with status conf
2. Configure Telegraf with nginx plugins
3. Start both containers

### Expected behavior:

Get nginx status metrics 

### Actual behavior:
Nginx VTS plugin works well but Nginx plugin doesn't work. It gives errors:

```
[inputs.nginx] Error in plugin: EOF
```

**Comment by mmukundram** [comment]
Did you find a solution to this?
I face the same issue with `inputs.exec` plugin.

**Comment by theodiefenthal** [comment]
Same for me, with Telegraf 1.14.0,  I use "http_response" Plugin on the same URL which works fine 

```
time                 content_length http_response_code method response_time result  result_code result_type server                                                         status_code
		----                 -------------- ------------------ ------ ------------- ------  ----------- ----------- ------                                                         -----------
		2020-05-26T16:03:40Z 6014           200                GET    0.056656315   success 0           success     https://myhost/server_status 200
```

but the same URL with inputs.nginx will result in `Error in plugin: EOF` using latest nginx:stable-alpine.

**Comment by Ghustavh97** [comment]
Did anyone ever find a fix for this?

**Comment by Ghustavh97** [comment]
Ok, so I had set nginx to `location /server_status` but made the mistake and typed the wrong endpoint for the plugin.

```
[[inputs.nginx]]
  ## An array of Nginx stub_status URI to gather stats.
  urls = ["http://localhost/status_server"]
```
`status_server !== server_status`

**Comment by sspaink** [comment]
It seems this issue could simply be using the wrong endpoint, thank you @Ghustavh97 for posting your solution it is appreciated.

Closing as there hasn't been any activity in a while, but if anyone is still having this problem and has checked if the correct endpoint is being used, please comment with as much info as you can and we can look into this issue more. It does seem this plugin could benefit from an integration test that could help recreate any problems.
