### ISSUE TITLE
ZeroMQ Plugin

### ISSUE THREAD

**Issue by indradhanush** [influxdata/telegraf#732]
An input/output plugin that reads/writes to a zeromq socket respectively.

I'd be happy to send a patch for this, if someone could please help me out in getting started.

**Comment by sparrc** [comment]
not sure what sort of help you're looking for, but the output plugin should be very similar to the mqtt and nsq outputs (see https://github.com/influxdata/telegraf/tree/master/plugins/outputs)

For input, would likewise be similar to the mqtt_consumer and nsq_consumer inputs (https://github.com/influxdata/telegraf/tree/master/plugins/inputs).

The input will be quite a bit more complicated so I would recommend starting with the output.

**Comment by indradhanush** [comment]
@sparrc Thanks. I'll get started on this. :)

**Comment by sparrc** [comment]
great! :+1:

**Comment by jamescarr** [comment]
@indradhanush Did you have any luck on this one? I'm a bit interested in this as well.

**Comment by indradhanush** [comment]
@jamescarr Yeah. I wrote the output plugin last weekend and a test case, but I need to work on a docker container that will serve a zeromq server for the test case.

**Comment by jamescarr** [comment]
Cool let me know if you need a hand. I'm interesting in exposing similar functionality. :-D

**Comment by indradhanush** [comment]
@jamescarr I'll create a PR for the existing work and reference it here so you can also take a look at it.

**Comment by widdma** [comment]
AFAIK, there is no native Go library for ZeroMQ.  There is a few Go bindings, but I believe they all use cgo and including a cgo package in Telegraf would not be ideal. See [Dave Cheney's post](https://dave.cheney.net/2016/01/18/cgo-is-not-go) on why cgo is not go. A big drawback for Telegraf is that it will complicate builds, including breaking cross-compiling. While cgo has it's place, I'm not sure it is in Telegraf — at least the main branch.

Nanomsg, the ZeroMQ alternative started by one of the original ZMQ authors, has a native go implementation [mangos](https://github.com/go-mangos/mangos). However, this is not compatible with ZeroMQ.

**Comment by sideshowdave7** [comment]
There is a native Go implementation of ZeroMQ here https://github.com/zeromq/gomq although it looks young.  I've written an input plugin for a ZeroMQ project i've worked on, but used cgo bindings, but I'd be happy to see if the native implementation works.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
I would also be very interested in 0MQ support.

**Comment by M0rdecay** [comment]
Is there any news on this? This feature would be useful.

**Comment by TannerW** [comment]
Is there any update on this effort or does it need to be rebooted? It seems like there is still interest, but we haven't seen an update in 3 or so years. I could maybe find the time to lend a hand to the request if no one is actively working on this. This feature is a *big* want for me right now so I am happy to assist in any way possible.

**Comment by sjwang90** [comment]
@TannerW There's no one currently working on this right now so we welcome anything you would like to work on.

Please check out writing this as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf. Any plugin could be used sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Feel free to respond with any questions you may have.

**Comment by TannerW** [comment]
Thank you for the tips on getting started @sjwang90! I will start spinning something up this weekend and won’t hesitate with my questions. I will post an update to this thread ASAP.

**Comment by powersj** [comment]
Hi,

Currently, there are the following libraries to interface with zeromq:

- https://github.com/pebbe/zmq4: requires C bindings via libzmq
- https://github.com/zeromq/goczmq: requires C bindings via libsodium, libzmq, and czmq
- https://github.com/go-zeromq/zmq4: is maintainer-less

Revisiting this feature request, I think given the above information, we will close this for now as not in-plan. If any of the above libraries change, we could revisit and would be happy to review a PR.

Thanks!
