### ISSUE TITLE
Use new AWS Cloudwatch GetMetricData metric limit of 500 metrics per call (was 100)

### ISSUE THREAD

**Issue by fmr-ap** [influxdata/telegraf#7322]
## Feature Request

Please change the Cloudwatch API plugin to batch requests using the new 500 metrics per call limit (https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-cloudwatch-now-provides-more-metric-data-faster-with-getmetricdata-quota-increase/). This should significantly reduce the load and the runtimes (and potentially cost?) when polling the Cloudwatch API.

We are struggling with scaling Telegraf to our needs due to latency and API request volume and heavily rely on this improvement.

FYI we have also filed a PFR with AWS to allow the ListMetrics API call to restrict the time period for which it returns resources & their metrics which will reduce the amount of API calls required for this single threaded (pagination) call. 

### Proposal:

Adopt GetMetricData to use new limit of 500 metrics per call instead of 100.

### Current behavior:

Batches of 100 metrics per call are used.

### Desired behavior:

Each GetMetricData call should request a batch of 500 metrics instead of the current 100.

### Use case: 

We are trying to scale Telegraf to collect metrics from various regions around the world and for  hundreds of thousands of instances and metrics. We run into constraints of the API calls taking too long due to latency & volume for some accounts. When rate limiting GetMetricData calls we run the risk of not finishing the metric collection within our period we use to provide the business the granularity they require. When increasing the rate limit we hit account's API call limits due to multiple namespaces we collect from. This is a very undesirable situation and won't work as our accounts grow.

**Comment by danielnelson** [comment]
I added some builds with the higher limit to the #7335 pull request, would you be able to try one of them out to validate the change and check the performance?  BTW, I expect it won't help with pricing since these endpoints are per metric requested.

**Comment by Josh-Bonello** [comment]
@danielnelson I have tested the windows build and see performance as expected with 500 metric data queries.

**Comment by fmr-ap** [comment]
Thanks Josh!

**Comment by danielnelson** [comment]
Do you know if this will work in all regions today?  My only concern with putting this in 1.14.2 would be that it doesn't work everywhere yet.

**Comment by fmr-ap** [comment]
@danielnelson: Josh and I work together and can ask the AWS CloudWatch service team for confirmation.

**Comment by Josh-Bonello** [comment]
The [public documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) does not give any regional restrictions, 

"You can use the GetMetricData API to retrieve as many as 500 different metrics in a single request, with a total of as many as 100,800 data points. " 

I've confirmed with AWS Support + Service teams that this is available in all regions today.
