### ISSUE TITLE
/proc/net/sockstat

### ISSUE THREAD

**Issue by rafipiccolo** [influxdata/telegraf#7329]
## Feature Request

I would like to have an input plugin to track data from this file /proc/net/sockstat
there is also /proc/net/sockstat6 and possibly more, but i particularly would like to track the tcp socket number : the "alloc (\d+)" in the sample below.
it will help tracking socket leaking.

### Proposal:

read the file
use a regexp to parse 
enjoy

```
#> cat /proc/net/sockstat
sockets: used 3535
TCP: inuse 2650 orphan 0 tw 473 alloc 2739 mem 14538
UDP: inuse 6 mem 11
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

javascript sample code :
```
var fs = require('fs');
var util = require('util');
var readFile = util.promisify(fs.readFile);

module.exports = async function procsock(procdir) {
    var content = await readFile('/proc/net/sockstat');
    var str = content.toString('utf8');

    var m = str.match(/sockets: used (\d+)\nTCP: inuse (\d+) orphan (\d+) tw (\d+) alloc (\d+) mem (\d+)\nUDP: inuse (\d+) mem (\d+)\nUDPLITE: inuse (\d+)\nRAW: inuse (\d+)\nFRAG: inuse (\d+) memory (\d+)/);

    if (!m) return null;

    return {
        sockets: m[1],
        tcp_inuse: m[2],
        tcp_orphan: m[3],
        tcp_tw: m[4],
        tcp_alloc: m[5],
        tcp_mem: m[6],
        udp_inuse: m[7],
        udp_mem: m[8],
        udplite_inuse: m[9],
        raw_inuse: m[10],
        frag_inuse: m[11],
        frag_mem: m[12],
    }
}
```

### Current behavior:

i couldnt find an appropriate input providing this information

### Desired behavior:

have an input plugin exposing all this data to my influxdb for monitoring

### Use case: 

helps to deal with socket leaking and bad programming.
Like a server never closing its sockets or whatever similar.

**Comment by danielnelson** [comment]
You can get most of this info from the [netstat](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NETSTAT_README.md) input plugin, here is how it looks on my system:
```
netstat tcp_close=0i,tcp_close_wait=0i,tcp_closing=0i,tcp_established=17i,tcp_fin_wait1=0i,tcp_fin_wait2=0i,tcp_last_ack=0i,tcp_listen=10i,tcp_none=29i,tcp_syn_recv=0i,tcp_syn_sent=0i,tcp_time_wait=0i,udp_socket=14i 1586914875000000000
```

This plugin actually uses the procfs on Linux these days, not lsof as the README incorrectly states.

Another option would be to use your Javascript code with the `exec` input, if you decide to go this route let me know and we can add your script to the [wiki tips](https://github.com/influxdata/telegraf/wiki/Users#tips).

Let me know if it seems like one of these solutions would work for you.

**Comment by rafipiccolo** [comment]
Hello, Thanks for your answer, netstat plugin gives tcp counters, but a module scanning this file would still be useful to have stats about orphan connections, udp, etc. I'll go with exec module as you suggested until there is a native module.

thanks
