### ISSUE TITLE
diskio : /proc/diskstats: no such file or directory on debian 7.9

### ISSUE THREAD

**Issue by sbouchex** [influxdata/telegraf#733]
Just installed telegraph 0.10.3 on debian 7.9 (virtualized) and I'm getting the following error:

2016/02/21 22:28:30 Error in input [diskio]: error getting disk io info: open /proc/diskstats: no such file or directory

**Comment by sparrc** [comment]
Why is there no /proc/diskstats...? Did you confirm that it doesn't exist anymore?

**Comment by sparrc** [comment]
Something might have gone badly with your upgrade, just spun up a VM with deb 7.9 and it looks OK:

```
$ lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy
vagrant@debian-wheezy:~$ cat /proc/diskstats
   8       0 sda 4964 369 260782 3088 1201 1380 176144 13104 0 2920 16148
   8       1 sda1 4473 338 256618 3028 1175 1380 176144 13084 0 2844 16068
   8       2 sda2 2 0 4 0 0 0 0 0 0 0 0
   8       5 sda5 322 31 2824 32 0 0 0 0 0 32 32
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by sparrc** [comment]
closing as won't fix, diskio plugin won't work on linux without /proc/diskstats

**Comment by sbouchex** [comment]
VM is created under OpenVZ by OVH (Largest hosting company in Europe) and that's not a bug as OpenVZ is not exposing all (/proc) counters.

**Comment by sparrc** [comment]
If the proc counters aren't exposed then we can't get those stats.
