### ISSUE TITLE
Telegraf logparser - parsing owlog localhost_access_log  fails 

### ISSUE THREAD

**Issue by BEN-59** [influxdata/telegraf#7330]

**Comment by saidbenh** [comment]
Error log telegraf :
telegraf -config /etc/telegraf/telegraf.conf -input-filter logparser.grock --test
2020-04-14T09:52:18Z I! Starting Telegraf 1.11.0
2020-04-14T09:52:18Z E! [telegraf] Error running agent: Error: no inputs found, did you provide a valid config file?

My config

# Stream and parse log file(s).
[[inputs.logparser]]

files = ["/u00/ekip360/tomcat7/CPA/logs/localhost_access_log.*"]
from_beginning = false

[inputs.logparser.grok]
    patterns = ["%{combined_log_format}"]
    measurement = "localhost_access_log"

**Comment by danielnelson** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by BEN-59** [comment]
Ok sorry


Le mar. 14 avr. 2020 à 21:49, Daniel Nelson <notifications@github.com> a
écrit :
