### ISSUE TITLE
Same alert is triggering multiple times

### ISSUE THREAD

**Issue by susil81** [influxdata/telegraf#7334]
Hi All,
Here my issue is if new log is coming and that log file triggered the alert again and again but in influxdb only one alert it there
Here is my tick script file.
// This Script will trigger alert for Oracle log level ORA-.
var ErrorMessageToBeIgnored1 = 'This is an example Error message to be ignore for the alert.'

// We can declare 'n' number of variables to be ignored while alerting for ORA-<Error Number> level.
var db = 'server_logs'

var rp = 'autogen'

var measurement = 'oracle_logs'

var groupBy = ['host', 'alert']

var whereFilter = lambda: TRUE

var name = 'Oracle_ServerLog-Linux-Threshold-LogLevel'

var idVar = name

var message = 'FTAIM: Oracle Server Level alert reports {{.Level}} with value: {{ index .Fields "value" }} on host: {{index .Tags "host"}}.'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'alerting'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 'ORA-'

// Below we are implemented that body text of Email, which is adopted by .details() method at trigger in alert node.
var emailbody = '''{{ if eq .Level "CRITICAL" }} 
                                                 <div>Dear Administration Team,<div><br><div>
                                                 FT Application Infrastructure Monitoring has detected an issue on a monitored system.<br> 
                                                 Please open the <a href="https://DATAVIEW_SERVER:8443/AnalyticsDataView/">Dataview Application</a> to diagnose the issue.<br> 
                                                 Error message: {{ index .Fields "value" }}  {{ index .Fields "alertmessage" }} <br>
                                                 Host:{{ index .Tags "host" }}<br><br>
                                                 Please take required actions immediately.<br><br> This email was automatically sent by FT Application Infrastructure Monitoring.</div>  
              {{end}} '''

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    // Below we are providing the alias names to adopt in this script.
    // Example Inside the HTML Tags at Error message place & Host place.
    |eval(lambda: "alert", lambda: "alertdescription")
        .as('value', 'alertmessage')
        .keep()
        .quiet()
    |log()

var trigger = data
    // Below we are implementing the DefaultErrorList of messages to be Ignored while alerting.
    |where(lambda: !strContains("alertmessage", ErrorMessageToBeIgnored1))
    |where(lambda: strContains("value", crit))
    |alert()
        // Below .crit() we are declaring ORA-<Error Number> as a CRITICAL to alert.
        .crit(lambda: TRUE)
        .message(message)
        .details(emailbody)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        // .topic('database_group')
        .email()
        .to('SKumarB@ra.rockwell.com')
        .to('SS4@ra.rockwell.com')
    |log()

trigger
    |eval(lambda: strContains("value", crit))
        .as('value')
        .keep()
        .quiet()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

**Comment by danielnelson** [comment]
The best place to get help with a Kapacitor script is at the [InfluxData Community](https://community.influxdata.com) site or the [Community Slack](https://www.influxdata.com/slack).
