### ISSUE TITLE
Agent won't start if remote HTTP config endpoint is down

### ISSUE THREAD

**Issue by schmorgs** [influxdata/telegraf#7338]
## Feature Request
A useful feature of Telegraf is to pull config from a remote HTTP server, thus centralising agent configuration.  However, if the HTTP endpoint is unavailable when the agent is started, the agent throws an error and dies.  

### Proposal:
Have the agent retry the endpoint periodically if unavailable, and when online, pull the config and start as normal.

### Current behavior:
Agent will not start.

### Desired behavior:
Agent re-attempts to get the configuration, ideally driven by startup switches to control retry-interval and max retry-attempts

### Use case: 
In a large environment, it is entirely possible that the HTTP endpoint could go offline (e.g. planned or unplanned outage).  Any agents that get restarted during this interval (e.g. reboot, agent installation) would simply die, meaning some recovery process is needed to bring them back online.  
Having this retry ability in the agent would provide a more reliable solution and self-recovery.

**Comment by schmorgs** [comment]
Pull request https://github.com/influxdata/telegraf/pull/7349 submitted to support this with a new CLI flag to control how ofter to retry the polling interval

**Comment by sjwang90** [comment]
Adding some notes on if we implement this some behavior we would want to go about it:
- By default, set the retries to 0 - to preserve the current behavior
- Log attempts and the specific failure response codes.

**Comment by sjwang90** [comment]
Related #3723

**Comment by schmorgs** [comment]
Hi, I see this has been closed with a fixed retry of 3 times, but this doesn't really help much for my use case.  Basically, the agent has 30 seconds to get the config from the remote server or it dies and we need some level of recovery to get it back online which isn't great across 1000's servers.

So unfortunately, not a fix for me.

**Comment by ssoroka** [comment]
Hey Schmorgs. I'd like to hear more about your use case. I am a bit concerned about Telegraf failing quietly where everything looks okay, because it's not loudly failing, but in reality it might never come up (say url was wrong or dns issue).
How do you manage your servers? doesn't Telegraf restart if it's not available? Why isn't the config mostly available? This seems like it should be a really rare problem. Is this an IoT situation where the devices are frequently offline?

I'm not against reopening the issue, though we may want to rename it to be more specific about your needs.

**Comment by sjwang90** [comment]
Opened #8854 to cover the configuring behavior settings portion of this issue.

**Comment by schmorgs** [comment]
Hi, thanks @sjwang90 for opening the new issue.

@ssoroka, we're planning to use Telegraf in production across a large number of servers across the globe, and there are many points where breakages could happen, especially in countries where there is very low bandwidth and old infrastructure.  Along with that comes many standards and versions of OS, etc, hence our approach to manage config centrally so that we don't have to navigate the variety of ways of reaching an endpoint.

So if Telegraf starts up and there happened to be a breakage somewhere (NW connectivity, Web Server down, etc), the agent will die.  On RHEL7/8 and Windows, we can utilise systemd/SCM to configure infinite retries on the agent so that even if it does die, it will be restarted.  
But RHEL6 doesn't have systemd and so we would end up writing some sort of watcher daemon as well which seems a bit overkill if the agent could handle (at least) this condition.

The reason for the importance is this will be our primary monitoring agent and so want to make this as available and robust as possible.  We would still implement external controls such as systemd restarts to provide an extra layer of resilience, but the more the agent can do to in this area makes just adds to this.

In some cases, the situation where the agent was unable to get config would be fairly small as the agent only pulls config on startup.  But we want the agent to periodically pull it's config down so that it can be configured centrally and automatically pulled by the agent.  I understand this is part of a longer term strategy for Telegraf, but in the meantime, we HUP the agent periodically as a workaround, and so now the agent has constant reliability on the HTTP endpoint and therefore, more likelihood of encountering a problem.

Whether a switch, environment variable, config file on the server, etc, I'm happy to see whichever approach works best.
