### ISSUE TITLE
[processor] New processor: filepath

### ISSUE THREAD

**Issue by kir4h** [influxdata/telegraf#7342]
## Feature Request

This issue proposes a new `filepath` processor plugin, that will handle transformations to file paths strings by exposing some of the functions implemented in https://golang.org/pkg/path/filepath/

### Proposal:

This proposal has its roots in https://github.com/influxdata/telegraf/issues/7290, while looking for an easy way to manipulat the `path` created by `logparser` input plugin.  In its related PR (https://github.com/influxdata/telegraf/pull/7301), @danielnelson suggested to migrate this functionality to a dedicated processor where more alike functions could be added (and also so that other plugins, for instance `tail` plugin, could also benefit from it.

The proposal is described by Daniel in https://github.com/influxdata/telegraf/pull/7301#issuecomment-614216516 : 

>  If we use the Go filepath package we can support these operations in a way that should work on Windows as well. I think it would be good to use some of the typical unix terminology for these operations:
```yaml
[[processors.filepath]]
  [[processors.filepath.basename]]
    tag = "path"
  [[processors.filepath.dirname]]
    tag = "path"
  [[processors.filepath.stem]] # name taken from python, removes one extension `foo.txt` -> `foo`
    tag = "path"
```
>There are other functions in the filepath package that might be helpful, but don't need to be added initially, such as Clean, Rel, ToSlash, VolumneName.

I am happy to work on this issue, will use this thread to discuss/agree on details and namings (for instance I guess we should apply this to either `tags` or `fields`; or maybe we should accept a list of tags, but I don´t see a strong use case for it so I wouldn´t go for it)

**Comment by kir4h** [comment]
As a first approach I am thinking of:
1. Having `tag` and `field` as the components that can be affected by the manipulation
2. For each function (`basename`, `dirname`, `stem`...), a list of paths and tags can be specified (instead of a single `tag` and `field`)
```yaml
  # [[processors.filepath]]
    ## Returns the last element of a path 
    # [[processors.filepath.basename]]
    #   tags = ["path"]
```
3. Each function should be defined once (`[[processor.filepath.basename]]` should be defined once, including as parameters all the tags and fields to be considered by the `basename` function)
4. If a field is in configured for one of the actions, it is converted to a string (not sure if it should be ignored instead)
5. Order not configurable (`stem` is applied before `basename` or `dirname` for instance). Not sure I should add some complexity by allowing an order (but then it might make sense not to allow tag or field lists as argument but just a tag or a field).

@danielnelson does it make sense? I am lacking some high level visibility about scenarios and use cases so that the implemented configuration makes sense overall

**Comment by danielnelson** [comment]
1. Great

2. One result of having a list of tags/fields for each function is you wouldn't be able to direct the output to a different tag/field like you can with the `dest` option in the strings processor.

3. Recall that double bracket tables ``[[processor.filepath.basename]]`` is an array of tables in TOML.  If you want a single table you would use single brackets: `[processor.filepath.basename]`.  But we still may want to specify multiple times in order in order to allow for settings the `dest` option.

4. I would just ignore non-strings.  If someone has a path that isn't a string they could convert it beforehand in the converter processor, but I think it would be rare.

5. I'm not sure order matters here, these operations seem to be commutative.  However, is it possible that maybe in the future a function would be added that isn't?  We could define order then so I guess either way is fine by me.

**Comment by kir4h** [comment]
> 2. One result of having a list of tags/fields for each function is you wouldn't be able to direct the output to a different tag/field like you can with the `dest` option in the strings processor.

Didn´t think we wanted that for the `filepath` processor, but I will add the option and then remove the array from `tag` and `field` parameters.
`strings`  processor has also the special convention `*` that makes it apply to every tag or field, ignoring in this case the `dest` option. Do we want also this behaviour (can't think of a use case at the moment, but just wondering)

> 3. Recall that double bracket tables `[[processor.filepath.basename]]` is an array of tables in TOML.  If you want a single table you would use single brackets: `[processor.filepath.basename]`.  But we still may want to specify multiple times in order in order to allow for settings the `dest` option.

Thanks! Totally slipped my mind. As part of introducing the `dest` I will add an array of tables instead.

> 4. I would just ignore non-strings.  If someone has a path that isn't a string they could convert it beforehand in the converter processor, but I think it would be rare.

ok

> 5. I'm not sure order matters here, these operations seem to be commutative.  However, is it possible that maybe in the future a function would be added that isn't?  We could define order then so I guess either way is fine by me.

There are some scenarios where the order would matter. Let's say I have `/var/log/myfolder/myfile.txt` and that I configure the `basename` and `dirname` options for the tag.
`basename` first and `dirname` after returns `.`
`dirname` first and `basename` after returns myfolder

This example is kind of edge unrealistic example, but gith the `relpath` function this scenario becomes more likely.

Personally, I wouldn't overcomplicate this introducing order, but rather state in the documentation in which order the functions will be applied to a tag. 

In any case, this order would only affect functions within the same `[[processors.filepath]]` stanza right? In below example `basename` will be executed before `dirname` independently of my code because it is on a `processor.filepath` parent that comes first, is my understanding correct?)

```toml
[[processor.filepath]]
  [[processor.filepath.basename]]
   tag = "path"

[[processor.filepath]]
 [[processor.filepath.dirname]]
   tag = "path"
```

**Comment by danielnelson** [comment]
> strings processor has also the special convention * that makes it apply to every tag or field, ignoring in this case the dest option. Do we want also this behaviour (can't think of a use case at the moment, but just wondering)

I don't imagine `*` would be useful here.

> Personally, I wouldn't overcomplicate this introducing order, but rather state in the documentation in which order the functions will be applied to a tag.

:+1:

> In any case, this order would only affect functions within the same [[processors.filepath]] stanza right? In below example basename will be executed before dirname independently of my code because it is on a processor.filepath parent that comes first, is my understanding correct?)

Technically the ordering of processors is undefined unless you set the `order` option:
```toml
[[processor.filepath]]
  order = 1
  [[processor.filepath.basename]]
   tag = "path"

[[processor.filepath]]
 order = 2
 [[processor.filepath.dirname]]
   tag = "path"
```
