### ISSUE TITLE
uptime (and uptime_format) from system-plugin always suppressed when dedup active

### ISSUE THREAD

**Issue by BertGr** [influxdata/telegraf#7343]
### Relevant telegraf.conf: 

```
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
[[processors.dedup]]
  ## Maximum time to suppress output
  dedup_interval = "600s"
```

### Steps to reproduce:

1.  Activate/inactivate dedup-section (new since 1.14.0)

### Expected behavior:

Also with active dedup-section uptime-metric from system-plugin should be send to influx-db (can't imagine duplicates on uptime ;-)

### Actual behavior:

With active dedup-section uptime-metric is not send to influx-db

### Additional info:

Other metrics from system (load, cpu, users) are ok.

**Comment by danielnelson** [comment]
It appears this would affect any metrics with the same measurement+tagset but with a differing field set.
