### ISSUE TITLE
Add percentiles to ping plugin

### ISSUE THREAD

**Issue by fhriley** [influxdata/telegraf#7344]
## Feature Request

When measuring response times, percentiles are typically more useful than averages and standard deviations. Since the ping plugin has a native method and can get all times, percentiles can be calculated.

**Comment by sjwang90** [comment]
Is there any reason for doing this locally versus during query? Can do a percentile really easily with [Flux](https://v2.docs.influxdata.com/v2.0/query-data/flux/percentile-quantile/)

**Comment by fhriley** [comment]
You'd be doing the percentiles over an averaged response time. That's not the same thing.

**Comment by psarossy** [comment]
Was this change actually released?

The documentation is updated, stating that as of 1.7.0 the percentiles are available, but when running the 1.7.2 docker image I get:
```
│ 2021/02/17 18:52:12 E! Error parsing /etc/telegraf/telegraf.conf, line 25: field corresponding to `percentiles' is not defined in `*ping.Ping'                                                                                               │
```

**Comment by 0x0a11c0de** [comment]
Is that a typo? `1.17.2` is the latest version.

**Comment by psarossy** [comment]
@0x0a11c0de yep, apparently my copy paste got mangled at some point and did not notice the missing '1'... 
Gonna go ahead and delete my comment to keep the noise down on the comments.

**Comment by sjwang90** [comment]
Closed in https://github.com/influxdata/telegraf/pull/7345
