### ISSUE TITLE
vCenter Data Store Metrics Present, but not Disk

### ISSUE THREAD

**Issue by briandm81** [influxdata/telegraf#7346]
## Datastores 
datastore_metric_include = [
"datastore.numberReadAveraged.average",
"datastore.throughput.contention.average",
"datastore.throughput.usage.average",
"datastore.write.average",
"datastore.read.average",
"datastore.numberWriteAveraged.average",
"disk.used.latest",
"disk.provisioned.latest",
"disk.capacity.latest",
"disk.capacity.contention.average",
"disk.capacity.provisioned.average",
"disk.capacity.usage.average",
] ## if omitted or empty, all metrics are collected
# datastore_metric_exclude = [] ## Nothing excluded by default
# datastore_instances = false ## false by default for Datastores only

### System info:

Telegraf 1.14 connecting to vCenter 6.5 via Debian Stretch

### Steps to reproduce:

I get these metrics back:

"datastore.numberReadAveraged.average",
"datastore.throughput.contention.average",
"datastore.throughput.usage.average",
"datastore.write.average",
"datastore.read.average",
"datastore.numberWriteAveraged.average",

But I don't get anything for these:
"disk.used.latest",
"disk.provisioned.latest",
"disk.capacity.latest",
"disk.capacity.contention.average",
"disk.capacity.provisioned.average",
"disk.capacity.usage.average",

I used to..but for some reason it just randomly stopped working.  I've tried restarting Telegraf and vCenter with no impact.  I've run the test command and I surely do get the datastore metrics, but nothing disk related.

### Additional info:
Here's the log file with debug = true:
2020-04-16T02:45:04Z D! [inputs.vsphere] Query for datastore returned metrics for 6 objects
2020-04-16T02:45:04Z D! [inputs.vsphere] CollectChunk for datastore returned 36 metrics
2020-04-16T02:45:04Z D! [inputs.vsphere] Latest sample for datastore set to 2020-04-16 02:45:00 +0000 UTC

As you can see, it just get the 6 metrics instead of the full 12 that I have in the config.  I've tried it with nothing in the config so that it just includes all metrics...nothing.  But oddly, no errors either.  I'm at a loss here.

**Comment by briandm81** [comment]
So I set up a whole new Linux box with 1.14 Telegraf and 1.18 InfluxDB.  I even set up a fresh vCenter 7 box since it just came out.  It works initially, and then never again...

**Comment by notlimahrelyt** [comment]
I am also experiencing this, but i'm not sure how to troubleshoot.

I load up a fresh TIG stack and Datastore metrics are pulled in, but when check Grafana the following day, all of the metrics disappear and only one of the Datastores persist.

If i restart the stack, it does not resolve, but if I remove the Telegraf volume and rebuild it, it's able to pull in all the metrics again.

**Comment by netbix** [comment]
Hello, i have same problema with telegraf 1.14.1  -  1.14.2  and 1.14.3
I have re-install telegraf 1.13.4 and work well !!!

**Comment by sspaink** [comment]
Closing as there hasn't been any activity in this issue for a long time, but if this is still a bug in the latest version of Telegraf please reopen so we can investigate. Thanks!
