### ISSUE TITLE
Use maximum gzip compression

### ISSUE THREAD

**Issue by jftuga** [influxdata/telegraf#7347]
Would you accept a PR that changes instances of:

    gzip.NewWriter(something)

to:

    gzip.NewWriter(something, gzip.BestCompression)

These are the files it would change (on master):

- internal/content_coding.go
- internal/internal.go
- plugins/outputs/azure_monitor/azure_monitor.go
- plugins/outputs/opentsdb/opentsdb_http.go

If so, which branch should I fork from?

**Comment by danielnelson** [comment]
I feel like by default we should use the default compression level, as best compression takes additional CPU.  Potentially we could introduce additional levels of configurability.

I think the first step we should take is to collect some data around how helpful this would be.  Do you think you could collect a full 1000 metric batch and compare the output size and compression time at the various levels.  I'd probably just do this as a temporary Go test Benchmark.

**Comment by jftuga** [comment]
Daniel,

That's a good point about taking additional CPU and I honestly don't have the time to run extensive testing.  I'll defer to your opinion and this idea can be disregarded.

**Comment by danielnelson** [comment]
Quick size test with 1000 metrics from the plugins enabled by default, using `gzip` with the `--best` and `--fast` args:
```
-rw-r--r-- 1 dbn dbn 32K Apr 16 12:21 best.gz
-rw-r--r-- 1 dbn dbn 34K Apr 16 12:21 default.gz
-rw-r--r-- 1 dbn dbn 51K Apr 16 12:21 fast.gz
```

Assuming this holds up in Go, I think it's a pretty minor difference and considering that it would be a fair bit more work to make this configurable let's shelf this idea for now?

**Comment by jftuga** [comment]
I agree with shelving this idea.  Thanks for testing.
