### ISSUE TITLE
Add ContentEncoder to socket_writer output plugin for UDP connections

### ISSUE THREAD

**Issue by quikkian** [influxdata/telegraf#7354]
## Feature Request

Add `ContentEncoder` to `socket_writer` output plugin for UDP connections

### Proposal:

Add `ContentEncoder` to `socket_writer` output plugin for UDP connections. This can then be paired with the `socket_listener` configured to listen for a UDP connection with compressed payloads to write gzip compressed packets between Telegraf instances

### Current behavior:

`socket_writer` plugin does not take advantage of existing `ContentEncoder` functionality

### Desired behavior:

`socket_writer` plugin extended to utilize `ContentEncoder` to be able to optionally write packets compressed with gzip for UDP connections

### Use case: 
In edge and IoT deployment scenarios where network capacity is at a premium, it's desirable to reduce network load by compressing outbound UDP packets.

**Comment by danielnelson** [comment]
My concern with this is that since we don't have clear message framing on the tcp output, it won't be possible to know where to start/stop reading the compressed message.

**Comment by quikkian** [comment]
> My concern with this is that since we don't have clear message framing on the tcp output, it won't be possible to know where to start/stop reading the compressed message.

Good catch, the change on the linked PR does _not_ "just work" with a `socket_listener` listening on a TCP socket with a `content_encoding` of `gzip`. However, since `socket_listener` can be configured as such in the first place, as a user I would expect that listener to work; I'll open a bug to track/prioritize that effort separately.

I'll abandon the existing PR and tweak this feature request to be specifically for UDP `socket_writer` connections and change the proposed implementation accordingly. May not have an updated PR this week though

**Comment by quikkian** [comment]
Note: Connecting an `influxdb` output with a `content_encoding = "gzip"` and a UDP URL to a `socket_listener` UDP listener doesn't "just work" (get errors of `Unable to decode incoming packet: gzip: invalid header`); at first glance, network payload looks the same as extended `socket_writer` from initial abandoned PR, so worth investigating

**Comment by danielnelson** [comment]
The content encoding only appears to be implemented in the InfluxDB output for HTTP writes.  We could extend this to UDP quite easily, though you get a lot less out of compression at this level since would be per line.

**Comment by quikkian** [comment]
>The content encoding only appears to be implemented in the InfluxDB output for HTTP writes

The comment for `content_encoding` makes this clear, I missed it. Since InfluxDB does not have the functionality to _listen_ for GZIP encoded UDP packets, it probably doesn't make sense for the InfluxBD output plugin to be able to write such packets.
