### ISSUE TITLE
input.ecs Metadata v4 support

### ISSUE THREAD

**Issue by snemetz** [influxdata/telegraf#7357]
## Feature Request

Support for ECS Metadata v4
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

**Comment by ssoroka** [comment]
is this still an issue after https://github.com/influxdata/telegraf/pull/8707 ?

**Comment by snemetz** [comment]
Does IMDS even work with fargate?
#8707 says it is focused on EC2 not ECS

**Comment by pgeler** [comment]
it does not work with ECS and using EC2 endpoint instead of ECS endpoint https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html
