### ISSUE TITLE
linux total memory issue

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7362]
HI Team,

can you please let me know, how telegraf capture Total memory data in linux server.

In my Virtual machine, total memory is showing wrong.

Telegraf version :- telegraf-1.12.2-1.x86_64
Linux:- Red Hat Enterprise Linux Server release 7.6 (Maipo)
Virtual machine
free -h
                    total        used        free      shared  buff/cache   available
Mem:            62G         10G         18G        3.1G         33G         48G
Swap:          3.9G        913M        3.0G

cat /proc/meminfo
MemTotal:       65789932 kB
MemFree:        19243196 kB
MemAvailable:   50676248 kB
Buffers:               0 kB
Cached:         33741712 kB
SwapCached:       225672 kB
Active:         27659048 kB
Inactive:       16677972 kB
Active(anon):   11614860 kB
Inactive(anon):  2266884 kB
Active(file):   16044188 kB
Inactive(file): 14411088 kB

telegraf outout:-

> mem,IP=10.5.112.173,application_name=uccmonitor,host=N2VL-PA-INFL02,owner_name=MyCloudTools_Airtel active=28334407680i,available=51882971136i,available_percent=77.01324877490373,buffered=0i,cached=36104089600i,commit_limit=37878743040i,committed_as=40292519936i,dirty=53248i,free=19688755200i,high_free=0i,high_total=0i,huge_page_size=2097152i,huge_pages_free=0i,huge_pages_total=0i,inactive=17084317696i,low_free=0i,low_total=0i,mapped=977162240i,page_tables=144793600i,shared=3365302272i,slab=1636638720i,swap_cached=231088128i,swap_free=3236261888i,swap_total=4194299904i,total=67368890368i,used=11576045568i,used_percent=17.1830729358407,vmalloc_chunk=35183933779968i,vmalloc_total=35184372087808i,vmalloc_used=299855872i,wired=0i,write_back=0i,write_back_tmp=0i 1587121039000000000

**Comment by danielnelson** [comment]
From `/proc/meminfo`, the `total` field comes from `MemTotal` but is multiplied by 1024 to report in bytes.
```
65789932 kB * 1024 = 67368890368 bytes
```

I think this looks correct, but you didn't specify what are you expecting to see so I'm not sure.  Let me know if my above explanation didn't clear it up.
