### ISSUE TITLE
Add integer support to processors.enum

### ISSUE THREAD

**Issue by tackittj** [influxdata/telegraf#7364]
### Proposal:
Add integer->string mapping support.

### Current behavior:
The [Enum Processor Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/processors/enum) currently only maps a string to an integer.  When asked to map an integer to a string it simply ignores the request.  There is no error or other output.

`green = 1`

### Desired behavior:
The `[processors.enum.mapping.value_mappings]` configuration should allow an integer to e mapped to a string.
`1 = green`

Perhaps it should even allow either string or integer on either or both sides of the mapping, though this is beyond my own immediate need.
`green = Passed`

Or perhaps an error could be generated when the enum processor is misconfigured to process a non-string.

### Use case:

This would prevent the need to first use the `[[processors.converter]]` to convert the int to a string.

**Comment by HarshitOnGitHub** [comment]
I am willing to pick this up if it is available. :)

**Comment by danielnelson** [comment]
Yes it is all yours, thanks!

**Comment by HarshitOnGitHub** [comment]
Thanks @danielnelson! Have opened a PR here: https://github.com/influxdata/telegraf/pull/7483
