### ISSUE TITLE
instance-total metrics without per cpu metrics

### ISSUE THREAD

**Issue by collinkinchen** [influxdata/telegraf#7365]
at the host level, Is there a way for telegraf to only pull the "instance-total" statistics from vsphere without outputting metrics from each cpu on the host as well?

For Example:
vsphere_host_cpu_coreUtilization_average will output 100+ stats for the same host, 1 per cpu. It will also out put a "instance-total" metric which is the aggregate of each cpu metric. 

Is it possible to get one without the other? im trying to reduce the amount output.

**Comment by danielnelson** [comment]
Does it help if you set `host_instances = false`?

**Comment by collinkinchen** [comment]
That is exactly what i was looking for. Not sure how i missed that one. Thank you very much for your help!

**Comment by nookseal** [comment]
@collinkinchen  where to put `host_instances = false` ? in telegraf plugin conf file?
