### ISSUE TITLE
redis input - type confusion float vs string

### ISSUE THREAD

**Issue by drahnr** [influxdata/telegraf#7375]
```toml
[[inputs.redis]]
servers = ["tcp://1.1.2.3:5"]
```

### System info:

Influxdb: 1.7.10-1
telegraf: Telegraf 1.14.0 (git: HEAD fefd7ff1)
redis: redis_version="5.0.8"
os: fedora 31 x86_64

### Steps to reproduce:

1. enable redis
2. utilize redis a bit
3. restart both telegraf and redis (order doesn't matter)

### Expected behavior:

Telegraf reports proper redis metrics

### Actual behavior:

telegraf log chunk:
```
field type conflict: input field "mem_fragmentation_ratio" on measurement "redis" is type float, already exists as type string dropped=1; discarding poin..
```

### Additional information:

Ref #5957

**Comment by ssoroka** [comment]
This test replicates the problem, if anyone's eager to patch it:
```
 func TestRedis_ParseFloatOnInts(t *testing.T) {
     var acc testutil.Accumulator
     tags := map[string]string{"host": "redis.net"}
     rdr := bufio.NewReader(strings.NewReader(strings.Replace(testOutput, "mem_fragmentation_ratio:0.81", "mem_fragmentation_ratio:1", 1)))
     err := gatherInfoOutput(rdr, &acc, tags)
     require.NoError(t, err)
     var m *testutil.Metric
     for i := range acc.Metrics {
             if _, ok := acc.Metrics[i].Fields["mem_fragmentation_ratio"]; ok {
                     m = acc.Metrics[i]
                     break
             }
     }
     require.NotNil(t, m)
     fragRatio, ok := m.Fields["mem_fragmentation_ratio"]
     require.True(t, ok)
     require.IsType(t, float64(0.0), fragRatio)
 }
```

**Comment by alexfouche** [comment]
For information, i have this one also because Telegraf queries both a Redis 3 instance and a Redis 6 instance and sends both metrics to the same InfluxDB timeseries measurement
