### ISSUE TITLE
Non cumulative internal stats

### ISSUE THREAD

**Issue by BenoistM** [influxdata/telegraf#7376]
## Feature Request
Add an option to enable/disable cumulative stats from internal input

### Current behavior:
When I try to get the metrics from internal input, they are (most of them) cumulative.

### Desired behavior:
enable/disable cumulative stats from internal input

### Use case:
I would like to have the written_metrics since the last data collection to monitor the data_collection. Maybe it is already possible but i did not find the trick to do it...

**Comment by ssoroka** [comment]
You might be able to do this by taking the non-negative derivative of the written_metrics. I do something similar in the [Telegraf template](https://github.com/influxdata/community-templates/tree/master/telegraf). I use both the [non-negative derivative](https://github.com/influxdata/community-templates/blob/master/telegraf/manifest.yml#L80-L86) and [aggregate.rate()](https://github.com/influxdata/community-templates/blob/master/telegraf/manifest.yml#L46-L51), which is similar, in Flux queries. 

Let me know what you think.

**Comment by BenoistM** [comment]
Yes, it could be a solution but how implement this with telegraf? Your template is for draw graph isnt it? I would like to have the "derivative" value directly into influxdb and not after a request... I don't know if it's possible according to [#2987](#2987) but the topic is quite old...

**Comment by ssoroka** [comment]
The problem with that is that both _derivative_ and _rate_ functions are comparing multiple records to get the change in value over time, but Telegraf deals with discrete packets of data, so it wouldn't be a great fit for Telegraf to compute the derivative. Usually computing this in InfluxDB is the right answer.

Maybe @danielnelson can weigh in here on some ideas/thoughts.

**Comment by BenoistM** [comment]
Yes, I understand your reflexion. However, when I print the telegraf logs, I can have this value:
`Apr 20 18:09:10 xxxxx telegraf[23803]: 2020-04-20T16:09:10Z D! [outputs.influxdb] Wrote batch of 3 metrics in 27.488569ms`
Maybe it is possible to get easily this value?

**Comment by danielnelson** [comment]
I'd like to resolve this with a difference/derivative aggregator (#3762)

**Comment by BenoistM** [comment]
Thank you for you help. I note that this aggregator is not merged with the official telegraf repo, does it produce any troubles on updates? And is there a way to rename fields generated by the aggregators (after the processors)?

**Comment by danielnelson** [comment]
> I note that this aggregator is not merged with the official telegraf repo, does it produce any troubles on updates?

It may, unfortunately we haven't been able to look at it yet at all.

> And is there a way to rename fields generated by the aggregators (after the processors)?

Yes, check out the discussion on #7379

**Comment by BenoistM** [comment]
Oh nice, thank you for your help!
