### ISSUE TITLE
Processor after Aggregator

### ISSUE THREAD

**Issue by rparvizian-rbx** [influxdata/telegraf#7379]
## Feature Request

Be able to run a processor after an aggregator.

### Use case: 
I'm using the `basicstats` aggregator to sum up a field that acts like a counter (the input line protocol would be:
 `measurement=foo,tag=bar counter1=1,counter2=1`
so in the aggregator config, I've only configured sum:
 `stats = ["sum"]`
problem is, the output is `counter1_sum`, `counter2_sum`. I'd rather the output just be `counter1` and `counter2`.
If I could run a processor like the `strings` processor after this aggregator, I could remove the `_sum` suffix.

**Comment by danielnelson** [comment]
You should be able to do this, the output of the aggregators is sent through the processors.  This is lesser known and not as well tested as other code paths, let me know if you run into any issues.

**Comment by rparvizian-rbx** [comment]
I'm a bit confused. How would I configure it so the processor plugin runs after the aggregator instead of before it? do I use the `order` to achieve this?

**Comment by danielnelson** [comment]
Here is a simplified diagram of the metric flow.  After the metrics from the inputs are added to the aggregators the metrics continue on to the outputs, but any new metrics produced by the aggregators run through the processors.

These processors are the same ones that handle the metrics from the inputs.  The same order is applied, and the same metric filtering rules are run.  You don't need to do anything special to have them run, its automatic.

```
I ┐        ┌─> P ─┐ ┌─> O
I ┼─> P ─> A ─────┴─┼─> O
I ┘                 └─>	O
```

**Comment by rparvizian-rbx** [comment]
This worked. I could be wrong, but I think specifying `tagpass` on the processor breaks it.

**Comment by danielnelson** [comment]
I'd be surprised if `tagpass` didn't work, but one gotcha is a known bug with our TOML parsing library where there is no error if you specify tags as a string instead of an array of strings.  Probably a stretch, but maybe this is what you are running into?

Bad, but no error!:
```toml
[[processors.printer]]
  [processors.printer.tagpass]
    foo = "bar"
```

Good:
```toml
[[processors.printer]]
  [processors.printer.tagpass]
    foo = ["bar"]
```

**Comment by qqiu-rbx** [comment]
> Here is a simplified diagram of the metric flow. After the metrics from the inputs are added to the aggregators the metrics continue on to the outputs, but any new metrics produced by the aggregators run through the processors.
> 
> These processors are the same ones that handle the metrics from the inputs. The same order is applied, and the same metric filtering rules are run. You don't need to do anything special to have them run, its automatic.
> 
> ```
> I ┐        ┌─> P ─┐ ┌─> O
> I ┼─> P ─> A ─────┴─┼─> O
> I ┘                 └─>	O
> ```

Is it possible to opt out of the P(the one above A) after the Aggregated metrics has been produced?
