### ISSUE TITLE
ERR: write message type: use of closed network connection

### ISSUE THREAD

**Issue by wgrcunha** [influxdata/telegraf#738]
Hello,

I have a cluster with 3 servers and everything working fine, i added a new server and when i try to do queries on that server i receive this error:

SHOW TAG KEYS FROM DATABASE."default".MEASUREMENT

ERR: write message type: use of closed network connection

The command: show measurements works fine.

The version is the 0.10 stable.

Thanks

**Comment by sparrc** [comment]
I think you meant to open this in influxdata/influxdb?

**Comment by wgrcunha** [comment]
@sparrc My bad :(

Closing!
