### ISSUE TITLE
MSMQ -Input plugin

### ISSUE THREAD

**Issue by sk78v** [influxdata/telegraf#7383]
Is there a roadmap to develop the input plugin for reading the messages from the MSMQ.
Please let me know if I can contribute for this plugin development.

**Comment by danielnelson** [comment]
No current plans, but we can keep this issue open for now as a feature request.  We probably wouldn't integrate this directly into Telegraf unless we see a lot demand, so I think its best to start any work as a program for the `execd` input.

**Comment by sspaink** [comment]
@sk78v are you still interested in this feature?
