### ISSUE TITLE
The getConnection function of inputs.snmp unable to check if the agents which we fill in are right

### ISSUE THREAD

**Issue by asdLingDe** [influxdata/telegraf#7385]
for i, agent := range s.Agents {
		wg.Add(1)
		go func(i int, agent string) {
			defer wg.Done()
			gs, err := s.getConnection(i)
			if err != nil {
				acc.AddError(Errorf(err, "agent %s", agent))
				acc.AddFields("snmp", map[string]interface{}{"up": 0}, map[string]string{"agent": agent, "version":string(versionInt), "community": s.Community})
				return
			}else {
				acc.AddFields("snmp", map[string]interface{}{"up": 1}, map[string]string{"agent": agent, "version":string(versionInt), "community": s.Community})
			}

  We have tried to add a metric which called "snmp_up",to make a judgment if the agents which we fill in is correct，but when we have a test，the wrong agent (eg: 10.10.10.10) showed the metrics ,it was the same when we write nothing("").We think there is something wrong with the logic of the function "getConnection"

  Here are the configs and the outputs of test：

[[inputs.snmp]]
  agents = ["10.248.131.252", "10.248.131.253", "10.248.128.9", "10.248.128.10", "10.248.128.40", "10.248.128.41", "10.248.128.36", "10.248.128.14","10.10.10.10","","a.b.c.d"," "]
  version = 2
  community = "xxxxxx"
  interval = "30s"
  timeout = "10s"
  name = "common"

2020-04-22T10:54:45Z I! Starting Telegraf 
> snmp,agent=10.10.10.10,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.131.253,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.41,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.14,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.36,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.10,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.40,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.131.252,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
> snmp,agent=10.248.128.9,community=InspurComm,host=mgt01,name=common,version=2 up=1i 1587552886000000000
2020-04-22T10:54:45Z E! [inputs.snmp]: Error in plugin: agent  : setting up connection: error establishing connection to host: dial udp: lookup  : no such host
> snmp,agent=\ ,community=InspurComm,host=mgt01,name=common,version=2 up=0i 1587552886000000000
2020-04-22T10:54:55Z E! [inputs.snmp]: Error in plugin: agent a.b.c.d: setting up connection: error establishing connection to host: dial udp: i/o timeout
> snmp,agent=a.b.c.d,community=InspurComm,host=mgt01,name=common,version=2 up=0i 1587552896000000000

**Comment by danielnelson** [comment]
So you are expecting that the incorrent agent IPs will have `up=0`?

**Comment by asdLingDe** [comment]
yeah,we expect it retuens "up=0" when the agent IPs are Incorrect,so that we can make sure if the IPs we filled in are the right IPs belong to our devices,and judge if we have established the connection with devices successfully.We thought the function "getConnection" could achieve this,but we failed in test.

**Comment by danielnelson** [comment]
Since SNMP typically uses UDP there isn't a tradition connection that can be tested for, so this function has a bit of misleading name.  The function will only return an error in cases where the connection was misconfigured, and not if the agent cannot be contacted.

I recommend enabling the `internal` plugin which will report the number of errors per plugin, although not per agent.  This can be convenient for watching for errors when there are no monitoring issues, but there are a variety of things that could go wrong that would prevent Telegraf from reporting too.  So additionally I recommend creating deadman alerts to go off if a high level SNMP variable such as `RFC1213-MIB::sysUpTime.0` is not being reported.
