### ISSUE TITLE
Telegraf log gets spammed/flooded if Elasticsearch receiver is in read-only state

### ISSUE THREAD

**Issue by cmakaloclifford** [influxdata/telegraf#7393]
### Relevant telegraf.conf:
```toml
# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  logtarget = "file"
  logfile = "/dev/null" # (Temporary fix for infinity loop of logs when Elasticsearch is in read only mode.)
  #logfile_rotation_interval = "1d"
  #logfile_rotation_max_archives = 7
  hostname = ""
  omit_hostname = false

[[outputs.elasticsearch]]
  urls = [ "https://***:9200" ] # required.
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"
  username = "***"
  password = "***"
  index_name = "***-%Y.%m.%d" # required.
  tls_ca = "/etc/telegraf/***-x509.pem"
  tls_cert = "/etc/telegraf/***-x509.pem"
  tls_key = "/etc/telegraf/***.key.pem"
  manage_template = true
  template_name = "edge"
  overwrite_template = false

# Telegraf logs
[[inputs.tail]]
  files = ["/var/log/telegraf/telegraf.log"]
  from_beginning = false
  pipe = false
  data_format = "value"
  data_type = "string"
  name_override = "log"

  [inputs.tail.tags]
     metric_type = "logs"
     log_source = "telegraf"
```

### System info:

Telegraf version: 1.14.1 (installed via Apt/Deb package)
OS version: Ubuntu 18.04

### Docker

No Docker instance is being used

### Steps to reproduce:

1. Wait for Elasticsearch server to reach 95% used storage and automatically go into read-only mode.
2. Tail telegraf.log and see that every 10 second, the buffer (1000 lines) gets written with an error that Elasticsearch is in read-only mode.
3. I we also have the Tail input activated on Telegrafs log file, then this happens about 4 times every second, resulting in about 4000 lines get written every second.

Please note that right now we have set the logging to /dev/null just to save us from getting our disks full each and every day. ;)

### Expected behavior:

It seams reasonable that either these lines where deduplicated in the log or it did not try all writes at all if the first write against the server fails.
We would like to see the same behaviour as if the Elasticsearch server did respond at all, like the read-only state would trigger the same kind of behaviour in Telegraf, as if it didn't respond at all. 
Because when the Elasticsearch server disk gets totally full, then it just stops responding overall, and then we only get 4 messages every ten seconds in the log saying that Elasticsearch cannot be reached (or something like that.

Also wondering about best practise if we want to ship our telegraf logs from all servers to Elasticsearch for central logging, are we doing it wrong? 

### Actual behavior:

If Elasticsearch is up (accepting connections) but does not accept writes (in read-only mode), which happens when the servers hits 95% used storage (Elasticsearch disk watermark threshold). 1000 lines like the following are logged every 10 seconds. To be precise the number of metrics waiting to be written to Elasticsearch or 1000 lines wichever is smaller.

If we also have turned on shipping of telegraf's own logs (via input.tail and send them to Elasticsearch for central storage of all logs), then it gets crazy and starts to loop over these 1000 lines and do it several times a second, instead of every 10 seconds, which results in several thousand lines of log getting written every second.

### Additional info:

Output from telegraf.log
```toml
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 992, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 993, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 994, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 995, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 996, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 997, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 998, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
2020-04-17T21:02:59Z E! Elasticsearch indexing failure, id: 999, error: index [telegraf-2020.04.17] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, caused by: %!s(<nil>), %!s(<nil>)
```

**Comment by ssoroka** [comment]
So if I understand this correctly, you're recursively ingesting Telegraf's log file back into Telegraf. This means that any error is going to generate more log entries, and any error in the elastic output that is going to generate more errors in a feedback loop. This is expected behavior. I can't think of a good way to avoid this problem once you've fed Telegraf's output back into Telegraf.

One way you could solve this is to remove the circular data feed: 
1. add a new Telegraf instance that reads the log file output
2. send it to elastic search
3. don't consume it's output.

**Comment by cmakaloclifford** [comment]
Hi!

No,  this actually happens even if we have internal logging turned off, as described above. I only added that additional information that if we also turn on internal logging from the Telegraf itself, it goes crazy, and was asking. for best practise if we wanted to gather all the Telegraf logs also into Elasticsearch.

But the main. issue still remains. 

**Actual behavior:**
If Elasticsearch is up (accepting connections) but does not accept writes (in read-only mode), which happens when the servers hits 95% used storage (Elasticsearch disk watermark threshold). 1000 lines like the following are logged every 10 seconds. To be precise the number of metrics waiting to be written to Elasticsearch or 1000 lines wichever is smaller.

**Expected behavior:**
It seams reasonable that either these lines where deduplicated in the log or it did not try all writes at all if the first write against the server fails.
We would like to see the same behaviour as if the Elasticsearch server did respond at all, like the read-only state would trigger the same kind of behaviour in Telegraf, as if it didn't respond at all.
Because when the Elasticsearch server disk gets totally full, then it just stops responding overall, and then we only get 4 messages every ten seconds in the log saying that Elasticsearch cannot be reached (or something like that.

This is without internal logging of the Telegraf.
I should have maybe left that part out since it seems it was only confusing. That was more of a bonus information, and followed by a question on how to best centralize the Telegraf's own logs.

**Comment by ssoroka** [comment]
@cmakaloclifford thanks for your patience, we've merged a fix to only report the first such error per post, and we'll see if we can further improve this to show only unique errors like you suggested.

Thanks for this!
