### ISSUE TITLE
[packaging] directory within Telegraf.zip file for Windows needs a version

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#7396]
## Feature Request
Currently, each release of telegraf is packaged into a ZIP file for Windows users.  The directory name used within the ZIP file is simply `telegraf`.  For other TICK stack component, the directory name containing the executable and associated configuration files always includes the version number. (e.g. chronograf-1.8.2-1, kapacitor-1.5.5-1)

This allows the user to cleanly unpack the executable and configuration into a new location with each release and then selectively deal with migrating the configuration, updating the windows service executable and more.  

Because Telegraf does not include the version name in the directory structure contained within the ZIP, the user can inadvertently overwrite both the existing executable AND configuration when unpacking the new version.

**Comment by danielnelson** [comment]
It would be best if we could omit the trailing -1: `telegraf-1.15.0`.  The -1 suffix is an artifact of deb/rpm packaging.

**Comment by timhallinflux** [comment]
I think that's fine. So long as a version is there when we unpack the ZIP...that's fine.  Makes it so much easier to handle this as a user.

**Comment by timhallinflux** [comment]
If we remove the -1 suffix, we should probably do this for the other TICK components as well. I'll file that issue.
