### ISSUE TITLE
Add nsd support

### ISSUE THREAD

**Issue by htj** [influxdata/telegraf#7401]
## Feature Request

nsd is a authoritative-only DNS server:
https://www.nlnetlabs.nl/projects/nsd/about/

It already has support for exporting metrics via the nsd-control cli utility.
Adding support for this should relatively straightforward.

Currently, we using the exec input with a custom script to support this:

```
#!/bin/sh
MEASUREMENT=nsd
# the time measurements are in float so we sort that out
measurements=$(sudo nsd-control stats_noreset | grep -v ^time | perl -p -e 's/\n/i,/' | sed s/,$// )
echo "$MEASUREMENT $measurements"
```

It sorts out the float values (as we don't really need them), and is a bit fast and dirty, but it works.

It relies on the following sudo entry:

```
telegraf ALL=(ALL) NOPASSWD: /usr/sbin/nsd-control stats_noreset
```

telegraf.conf entry:
```
[inputs.exec]
commands = ["/usr/local/bin/nsd-stats"]
data_format = "influx"
```

### Proposal:

Add input specifically for nsd.

### Use case:

Mostly looking at request / sec to track usage.

**Comment by sjwang90** [comment]
NSD Input Plugin added #7822
