### ISSUE TITLE
Add NETCONF input plugin for MDT Dial-in with Cisco IOS XE

### ISSUE THREAD

**Issue by cprecup** [influxdata/telegraf#7404]
## Feature Request

Support for a NETCONF input plugin would allow ingestion of data from Cisco IOS XE devices, Cisco NSO, and other NETCONF-compliant servers.

Solution addressed in PR https://github.com/influxdata/telegraf/pull/7392.

### Proposal:

Provide three kinds of operations in NETCONF:
- Subscription-based, periodic model-driven telemetry streaming through ietf-yang-push notifications (see [draft-ietf-netconf-yang-push-25](https://tools.ietf.org/html/draft-ietf-netconf-yang-push-25))
- Subscription-based, event notification streaming through notifications (see [RFC5277](https://tools.ietf.org/html/rfc5277#page-9))
- Periodic polling with <get> requests (see [rfc6241 - Network Configuration Protocol (NETCONF), section 7.7](https://tools.ietf.org/html/rfc6241))

Use the [netgonf](https://github.com/cisco-ie/netgonf) library that implements NETCONF in golang.

### Current behavior:
N/A

### Desired behavior:
N/A

### Use case: 

It fills the gap for model-driven telemetry streaming over a different protocol (NETCONF). It also gives a way for network elements to transfer data over NETCONF using notifications or polling.

**Comment by powersj** [comment]
Hi,

Thanks for putting up a PR and sorry no one has gotten back to you in a while. We currently have an existing Cisco MDT plugin. Would it be possible to get merge this into the existing plugin as another transport option? If not, I think this would be better served as an external plugin for users to pull in.

Thanks

**Comment by jeremycohoe** [comment]
Hi, for each of the telemtry interfaces there is a plugin:

For gNMI: https://github.com/influxdata/telegraf/tree/release-1.14/plugins/inputs/cisco_telemetry_gnmi
For gRPC: https://github.com/influxdata/telegraf/tree/release-1.14/plugins/inputs/cisco_telemetry_mdt

So now there is another one for NETCONF please

**Comment by cprecup** [comment]
Hello,

@powersj  - as mentioned by @jeremycohoe, the naming followed the convention of separating the plugins per protocol. For example, the cisco_telemetry_mdt covers the gRPC transport method, and the cisco_telemetry_gnmi covered gNMI.

This plugin for which the pull request was made covers another protocol, NETCONF.

Could we keep it as a separate plugin?

**Comment by jeremycohoe** [comment]
Is anything needed from our end ?

**Comment by carlosabalde** [comment]
Is this NETCONF input plugin implementation available as a external plugin somewhere? I've checking the PR #7392 and I don't really understand why it was never merged. There are a bunch of relevant features not available using gNMI or gRPC that a plugin like this would solve.

**Comment by srebhan** [comment]
@carlosabalde the plugin was never merged because the review comments were never addressed. If someone wants to pick this up and implement a _true_ netconf input plugin (not tailored to only CISCO) this would be much appreciated!

**Comment by jeremycohoe** [comment]
Why we can't have the one that works for the cisco ? we need to maintain separate fork for it ? It's strange because the gNMI plugin used to work with the Cisco but then another vendor broke it to only work with their product. Hrmm.... thanks for listening.

**Comment by srebhan** [comment]
@jeremycohoe not sure I get what you want to say in your comment, so let me ask... So you are saying that gNMI worked before for CISCO but now doesn't? If so, I'm more than willing to fix this situation but unfortunately I don't have access to CISCO devices... Please open a new issue with a description of the malfunction and let me know the issue number!

**Comment by cprecup** [comment]
Hello! This effort has been stopped. I welcome another author with more resources that could adopt this plugin.
