### ISSUE TITLE
Multiple Interface Support

### ISSUE THREAD

**Issue by mjlyon** [influxdata/telegraf#741]
I must be missing in the configuration file how to specify multiple network interfaces and have their data graphed and reported individually.

**Comment by sparrc** [comment]
which version? which plugin? current data? expected data?

**Comment by mjlyon** [comment]
0.10.3
inputs.net

[[inputs.net]]
   # interfaces = ["eth1", "eth0"]

It is commnted out as you can see, but I did not see an option when I was tyring to create a graph to specify an interface instance 

InfluxDB 0.9.5

**Comment by sparrc** [comment]
There is a tag called `interface` which is added to each measurement, I can't really help you with much more than that. This is probably not the place to be asking for help making grafana dashboards, you could contact support or ask on grafana forums.

**Comment by mjlyon** [comment]
That's what I was looking for, thanks
