### ISSUE TITLE
Redis - support of Redis 6 new AUTH

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#7410]
### Proposal:
Adding the support of ACL for Redis 6 (will be available in stable version in next days)

### Current behavior:
Telegraf support only password:
AUTH <password> via [protocol://][:password]@address[:port]

### Desired behavior:
Telegraf support both behaviours:
-> Old version (always supported by Redis 6): [protocol://][:password]@address[:port]
-> New version: [protocol://][user][:password]@address[:port]

### Use case: 
Adding this feature can allow to create by example a new user "monitoring" with only "read" (based on commands allowed for this user) access on the informations that we want

More informations concerning Redis ACL available on https://redis.io/topics/acl

**Comment by jrtaisto** [comment]
This would be a nice to have so that admins can lock down the default user.
