### ISSUE TITLE
Ability to set error length

### ISSUE THREAD

**Issue by SebastianThorn** [influxdata/telegraf#7413]
## Feature Request

Add a variable in the configuration to set how long error messages should be logged to the log-file.

### Current behavior:
The log only contains some the output that can not be parsed, and therefore might not log the actual error or problem causing the parsing to fail.

### Desired behavior:
A variable in the telegraf, allowing me to set the number of lines or chars to be logged.

### Use case:
I have a script that writes influx-metrics that is collected by telegraf, the script sometimes gives bad data to telegraf that telegraf can't parse,

The output in the log may look something like this
```
2020-04-27T02:15:00Z E! Error in plugin [inputs.exec]: metric parse error: expected field at offset 16415: "
remote_status,platform=some,src=prd,dst=cla code=200i,ok=1i,response_microsec=42083i
remote_status,platform=some,env=prd,dst=clb code=200i,ok=1i,response_microsec=32012i
remote_status,platform=some,env=prd,dst=clf code=200i,ok=1i,response_microsec=55500i
remote_status,platform=some,env=prd,dst=cljh code=200i,ok=1i,response_microsec=45909i
remote_status,platform=some,env=prd,dst=clai code=200i,ok=1i,response_microsec=47212i
remote_status,platform=some,env=prd,dst=clarr code=200i,ok=1i,response_microsec=58038i
remote_status,platform=some,env=prd,dst=claff code=200i,ok=1i,response_microsec=59834i
remote_status,plat..."
```

The script ready a couple of dynamic files, and decides what to do from these, so the script only gives bad output a couple of times a day.
If i run the script manually it is not certain that the bad output will occur.
Telegraf knows where the error is (offset 16415), i would like to set if so that telegraf can log the entire output.

I do understand that telegraf does nothing wrong here and my script's output is to blame,
but if this is an easy thing to add I thought it might help others aswell.

The script currently echos out about 132 lines and 16671 chars.

Br Sebastian Thörn

**Comment by ssoroka** [comment]
What might be more useful is outputting ~100 characters before and after the mentioned offset, and then it would always do the right thing regardless of the size.

**Comment by SebastianThorn** [comment]
yes, that would be even better!

**Comment by ssoroka** [comment]
Hey Sebastian, What version of Telegraf are you using? Looks like the latest version trims down to the line responsible. I've opened a PR for potentially trimming long lines as well, but you will probably be ok with the latest Telegraf. Let me know if you have any other thoughts here.

**Comment by SebastianThorn** [comment]
Okay, we compile our own version, I can try to get a new version out in the lab during next week.

**Comment by ssoroka** [comment]
ok @SebastianThorn, let me know how it goes. I'm going to close this issue for now but feel free to keep the conversation going if you like.
