### ISSUE TITLE
Get just one value from JSON object 

### ISSUE THREAD

**Issue by Kostell0** [influxdata/telegraf#7414]
I want to write a config file to get just one integer value from JSON object with Telegraf and write it into Influxdb. Is there any way to do this without getting another values into Influx? 

For example, is this here possible to take just "age" = 37 and ignore "friends" list completely with all values ? 
{
    "obj": {
        "name": {"first": "Tom", "last": "Anderson"},
        "age":37,
        "children": ["Sara","Alex","Jack"],
        "fav.movie": "Deer Hunter",
        "friends": [
            {"first": "Dale", "last": "Murphy", "age": 44},
            {"first": "Roger", "last": "Craig", "age": 68},
            {"first": "Jane", "last": "Murphy", "age": 47}
        ]
    }
}

**Comment by danielnelson** [comment]
Yes, you can use the [multipaths syntax](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipaths) of gjson along with the `json_query` option:

```toml
[[inputs.file]]
  files = ["example"]
  json_query = "{obj.age}"
  data_format = "json"
```
