### ISSUE TITLE
support starting as a daemon process 

### ISSUE THREAD

**Issue by panzhengyu** [influxdata/telegraf#7416]
## Feature Request

telegraf start as a daemoon process
### Proposal:
support a parameter to start as a daemon process. For example, the parameter -d
### Current behavior:
telegraf start as a oreground process
### Desired behavior:
telegraf -config config_file -d
### Use case: 
In some specific agent, start process not block agent.

**Comment by powersj** [comment]
Hi,

Sorry, no one has gotten back to you yet. I think a better option is for users to use our provided DEB or RPM packages for Linux-based systems or to set up Telegraf as a service on Windows.

Is there a use-case that you have that is outside those options?

Thanks
