### ISSUE TITLE
Installation on latest LTS Ubuntu (20.04 Focal Fossa) not working. Repository not available.

### ISSUE THREAD

**Issue by Xyaren** [influxdata/telegraf#7422]
### System info:
Ubuntu 20.04 LTS (focal Fossa)

### Steps to reproduce:

Install repository like in documentation.
run `apt update`

### Actual behavior:
```
E: The repository 'https://repos.influxdata.com/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Additional Information:
https://docs.influxdata.com/telegraf/v1.14/introduction/installation/

Documentation does not specify supported versions of Ubuntu. Therefore all versions are expected to work.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
```
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by danielnelson** [comment]
This should be active now with the new 1.14.2 release, can you give it a shot?

**Comment by mwThinks** [comment]
Somehow I had similar problems following the installation guide [here](https://docs.influxdata.com/telegraf/v1.14/introduction/installation/)

```bash
$ echo ${DISTRIB_ID,,}
```
gives a bad substitution error and 
```bash
echo ${DISTRIB_ID,,}
```
gives `Ubuntu` with a upper-case U.

Only when adding the repo with 
```bash
$  echo "deb https://repos.influxdata.com/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```
by "hand" did 
```bash
$ sudo apt-get update && sudo apt-get install telegraf
```
run without errors. 

I see how this is a minor thing but as a not so experienced Linux user this took me a bit to solve.

**Comment by danielnelson** [comment]
@mwThinks Could you be open this as a new issue at https://github.com/influxdata/docs.influxdata.com?

**Comment by mwThinks** [comment]
Sure thing, I opened this new one https://github.com/influxdata/docs.influxdata.com/issues/2883
