### ISSUE TITLE
Aggregating based on matching Regex group

### ISSUE THREAD

**Issue by R-Studio** [influxdata/telegraf#7432]
## Feature Request
Aggregating based on matching Regex group of the tag value.

### Proposal:
For example, we have following metrics:
VM_vCPU,instance=**VM01**_vCPU1 Percent_Total_Run_Time=30%
VM_vCPU,instance=**VM01**_vCPU2 Percent_Total_Run_Time=20%
VM_vCPU,instance=**VM01**_vCPU3 Percent_Total_Run_Time=40%
VM_vCPU,instance=**VM02**_vCPU1 Percent_Total_Run_Time=50%

Regex (groups all the tag values that belongs to the same VM, **bold=the regex group**):
`(VM.*)\_`

Desired behavior: After aggregating the "average/mean" following should be the output (an aggregated output for each VM/matching tag value). _New Measurement = "VM_vCPU_avg"_:
VM_vCPU_avg,instance=**VM01** Percent_Total_Run_Time=30%
VM_vCPU_avg,instance=**VM02** Percent_Total_Run_Time=50%

### Current behavior:
Real life example: I have the following Windows Perfmon input/configuration to monitoring the load of the VMs for each virtual CPU (vCPU):
```
[[inputs.win_perf_counters.object]]
ObjectName = "Hyper-V Hypervisor Virtual Processor"
Instances = ["*"]
Measurement = "hyperv_processor"
Counters = [
  "% Total Run Time",
]
```
But we also need the **average load for each VM** and not for each vCPU of a VM. 
_(A VM can have multiple vCPU, but we are interessted of the total load in the VM.)_

Assumption/Example:
- I have two VMs ("TestRHE01" and "TestRHE02")
- The VM "TestRHE01" has four vCPU
- The VM "TestRHE01" has two vCPU

With the win_perf configuration, showing above, the tag "instance" has the following value:
`"<VMName>:Hv VP <CoreNumber>"`

That means we have following metrics:
hyperv_processor,instance="**TestRHE01**:Hv VP 01" Percent_Total_Run_Time=10%
hyperv_processor,instance="**TestRHE01**:Hv VP 02" Percent_Total_Run_Time=30%
hyperv_processor,instance="**TestRHE01**:Hv VP 03" Percent_Total_Run_Time=20%
hyperv_processor,instance="**TestRHE01**:Hv VP 04" Percent_Total_Run_Time=20%
hyperv_processor,instance="**TestRHE02**:Hv VP 01" Percent_Total_Run_Time=10%
hyperv_processor,instance="**TestRHE02**:Hv VP 02" Percent_Total_Run_Time=70%

Example Regex that groups the VMs:
`(.*)\:`

### Desired behavior:
With the matching of the regex group, the following is the desired output:
hyperv_processor_avg,instance="**TestRHE01**" Percent_Total_Run_Time=20%
hyperv_processor_avg,instance="**TestRHE02**" Percent_Total_Run_Time=40%

Desired aggreagtor configuration (a new parameter "**tags_regex**"):
```
[[aggregators.basicstats]]
  period = "30s"
  drop_original = false
  stats = ["mean"]
  tags_regex ["(.*)\:"]
```

### Use case: 
We build a capacity-management monitoring and we have to deside in the next 4 weeks if we can build that with Telegraf and Influx or we build that with Zabbix.

_Excuse me I use telegraf not for a long time and maybe there is already a solution for my use case._

**Comment by danielnelson** [comment]
Since aggregators work by combining the values with the same measurement+tagset, the general technique is to bring the values into this form.

Let's say you have multiple cpu instances that you want to aggregate
```
cpu,cpu=cpu0 time_idle=1
cpu,cpu=cpu1 time_idle=1
cpu,cpu=cpu2 time_idle=1
```

If you remove the cpu tag, they will all have the same measurement+tagset and will aggregate together.
```
cpu time_idle=1
cpu time_idle=1
cpu time_idle=1
```

But looking at your example, you need a partial aggregation.  One way to do this would be to split the `instance` tag into two values: `vmhost=TestRHE02` and `vmcpu=Hv VP 02`.  You can do this with the regex processor using two rules, one for each tag.  Then, when adding the metrics to the aggregator, you can use `tagexclude` to remove the vmcpu tag causing all cpu's to be aggregated together.

Let me know if that makes sense and solves your issue.

**Comment by R-Studio** [comment]
> Since aggregators work by combining the values with the same measurement+tagset, the general technique is to bring the values into this form.
> 
> Let's say you have multiple cpu instances that you want to aggregate
> 
> ```
> cpu,cpu=cpu0 time_idle=1
> cpu,cpu=cpu1 time_idle=1
> cpu,cpu=cpu2 time_idle=1
> ```
> 
> If you remove the cpu tag, they will all have the same measurement+tagset and will aggregate together.
> 
> ```
> cpu time_idle=1
> cpu time_idle=1
> cpu time_idle=1
> ```
> 
> But looking at your example, you need a partial aggregation. One way to do this would be to split the `instance` tag into two values: `vmhost=TestRHE02` and `vmcpu=Hv VP 02`. You can do this with the regex processor using two rules, one for each tag. Then, when adding the metrics to the aggregator, you can use `tagexclude` to remove the vmcpu tag causing all cpu's to be aggregated together.
> 
> Let me know if that makes sense and solves your issue.

Thanks for your answer. I will check that next week and give you a feedback if this works.

**Comment by R-Studio** [comment]
@danielnelson, thanks for your help, that works perfectly for me. This is really a great help, but in the documentation there are some lacks. For example in Windows you have to define the pattern value between singlequotes instead of doubleqoutes.

To completion, this is my telegraf processor configuration:
```
[[processors.regex]]
  namepass = ["hyperv_processor"]
  
  [[processors.regex.tags]]
    key = "instance"
    pattern = '^(?P<VMName>.+)\:.+$'
    replacement = "${VMName}"
    result_key = "VMName"
```

_The tool is better than the documentation about it._ ;-)
