### ISSUE TITLE
Cisco GNMI Telemetry - "ONCE" Subscription mode feature request. 

### ISSUE THREAD

**Issue by TechDawg** [influxdata/telegraf#7436]
Support for GNMI "ONCE" subscription mode within telegraf's input plugin: Cisco GNMI Telemetry 

Proposal: Implement support for "ONCE" subscription mode. 

Current behavior: Supports subscription types: Sample mode, Target Defined, On Change. No support for "ONCE".

Desired behavior: Support for subscription mode "ONCE" when specifying subscription parameters within configuration files. Subscriptions operating in the "ONCE" mode acts as a single request/response channel. The target creates the relevant update messages, transmits them, and subsequently closes the RPC.  In order to create a one-off subscription, a client sends a SubscribeRequest message to the target. This would be done through the Cisco GNMI input configuration file consequently specifying the subscribe field within the subscription request, setting the mode field set to "ONCE".

Use case: Pre/post router migration checks, router health checks, getting a specified set of data only once. 

NOTE: If this has not been implemented for a specific reason (I.E plugin is designed to work with ongoing streams) please let me know :)

**Comment by sbyx** [comment]
I guess you could actually specify "once" in the config as mode (haven't tried, but doesn't seem to be filtered out). However since Telegraf and the plugins are not really designed in a way to close themselves I assume it may get you the data but keep the grpc channel open until you close Telegraf manually.

**Comment by danielnelson** [comment]
Normally plugins run continually, one time collection isn't generally done.  The exception would be when running Telegraf with the `--test` option, maybe it would make sense there.
