### ISSUE TITLE
Configuration & Design Advice

### ISSUE THREAD

**Issue by smogsy** [influxdata/telegraf#7440]
Hi,
I have been trying to create a new process of logging SNMP traffic using influxdb & telegraf snmp plugin.

However, I have hit an area where I need Advice
We have hundreds of switches to monitor across multiple sites, (1 per rack) so our plan was as follows:
Influxdb - database name [Site_room]
Time series - Rack Tile/Name

The issue: 
Read through your documentation, it does not seem clear how I should go about doing the configuration.

Currently, I have the 

- SNMP V3 security information & influxdb database secruity details in telegraf.conf 
- a single telegraf_snmp.conf containing at the moment just sysuptime
- however, we want to be pulling around 25 data points

My Question:
- how do I write the correct rack to the correct time series?
- what is the best way to approach multiple devices?
- Should I be creating a config per rack with all 25 datapoints inside telegraf_snmp_rack.conf

thankyou :)

**Comment by kiler129** [comment]
You may be interested in #7433 where we're actually discussing a similar problem.

Regarding the database you're probably better off tagging rather than using a separate table for each site.
