### ISSUE TITLE
Kubernetes Monitoring

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7441]
Hi Team,

I am looking Kubernetes monitoring through telegraf agent, As i can see telegraf have two plugin for this (inputs.kubernetes  and inputs.kube_inventory) 

I have one confusion, Currently I have installed telegraf on Host machine(rpm -ivh telegraf.rpm_name)
 So Can I monitor Kubernetes with this telegraf.conf, because I have no idea for daemonset 

If Yes, what are the permission required and possible please share any steps.

**Comment by danielnelson** [comment]
You will want to focus on the `kube_inventory` plugin, the API that the `kubernetes` plugin uses has been deprecated in newer Kubernetes versions.

It might also be useful to consider using these https://github.com/influxdata/helm-charts

Overall, the best place to ask for advice on Kubernetes monitoring would be over at the [InfluxData Community](https://community.influxdata.com) site.
