### ISSUE TITLE
prometheus

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7442]
Hi,

is there any way, telegraf can read promethus data and forward to influxDB ?

We can't use promethus read/write

**Comment by danielnelson** [comment]
Have you tried the [prometheus](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) input?

**Comment by rguptarg** [comment]
Hi,

I have tried prometheus input plugin, 

Whenever I have used below config, it's working fine and sending all system related data to InfluxDB.
[[inputs.prometheus]]
   urls = ["http://localhost:9101/metrics"]

But with below configuration, it's given error, so please help to fix this problem : 

[[inputs.prometheus]]
  kubernetes_services = ["http://node-exporter.openshift-monitoring:9100/metrics"]
  monitor_kubernetes_pods = true

Error
May 04 18:41:44 xxx-xx-master01 systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.

**Comment by danielnelson** [comment]
You should check the logs from Telegraf for clues, on most systems these get sent to `/var/log/syslog`.
