### ISSUE TITLE
[Wavefront Output Plugin] Allow option to truncate tag value if it is too long

### ISSUE THREAD

**Issue by jhua-vmware** [influxdata/telegraf#7447]
## Feature Request
Allow option to truncate tag value if it is too long. So that points won't be blocked by wavefront proxy.

### Proposal:
introduce a new configurable allow_truncate_tag_value (true/false)

### Current behavior:
We are using [[inputs.procstat]] with cmdline_tag = true

Currently, the points with very long cmdline tag will be blocked by wavefront proxy. According to https://docs.wavefront.com/wavefront_data_format.html on pointTags, the max len(key) + len(value) is 254.

### Desired behavior:
Introduce a configurable plugin parameter allow_truncate_tag_value (false by default), when it is set to true, the warefront output plugin can truncate value as:
                 if w.AllowTruncateTagValue && len(key)+len(val) > 254 {
			val = val[:254-len(key)]
		}

### Use case: 
We need to use cmdline tag to identify the application processes for procstat meters, and many meters are blocked due to long cmdline without this feature.

**Comment by danielnelson** [comment]
You can do this with the `strings` processor and it's "left" operation as a workaround, but we should update the wavefront output to do this automatically.

cc @prydin

**Comment by jhua-vmware** [comment]
@danielnelson Thanks for the workaround. We are able to move forward, and at mean time, we can wait for the plugin fix in the future release.

**Comment by prydin** [comment]
@danielnelson Can you assign this to me? I'll have a look at it.
