### ISSUE TITLE
[Splunkmetric Serializer Plugin] Unnecessary fields generated: "config:hecRouting" and "config:multiMetric"

### ISSUE THREAD

**Issue by zszia** [influxdata/telegraf#7448]
### Actual behavior:
Splunkmetic serializer plugin generates two unnecessary fields for each event: "config:hecRouting" and "config:multiMetric". 
These are indexed in Splunk but not really needed.

Interestingly in the output example the fields are output with underscore prefix:
https://github.com/influxdata/telegraf/tree/master/plugins/serializers/splunkmetric

```
{
  "time": 1572469920,
  "event": "metric",
  "host": "mono.local",
  "fields": {
    "_config_hecRouting": false,
    "_config_multiMetric": true,
    "class": "osx",
    "cpu": "cpu0",
    "metric_name:telegraf.cpu.usage_guest": 0,
    "metric_name:telegraf.cpu.usage_guest_nice": 0,
  ...
  }
}
```

That would be ok, because fields with underscore prefix are not indexed in Splunk. 
https://docs.splunk.com/Documentation/Splunk/8.0.3/Metrics/BestPractices
"...start with an underscore ( _ ). Such dimensions will not be indexed."
Still, the data has to be written and trasferred to Splunk, only to be removed by the indexer engine. 

Unfortunately the fields are being written to output without underscore (tested with file output, _config_hecRouting=false and _config_multiMetric=true).

In splunkmetric.go I simply commented out the following two lines and now it works correctly:

```
//commonObj["config:hecRouting"] = s.HecRouting
//commonObj["config:multiMetric"] = s.SplunkmetricMultiMetric
```

### Expected behavior:
The fields are omitted in the events or are written with underscore prefix.

**Comment by danielnelson** [comment]
@ronnocol Do you remember what these fields are used for?

**Comment by ronnocol** [comment]
I added them when I added the multiMetric support as dimensions/tags. It was intended as an easy flag to indicate what path(s) were used to get the data to the indexer. I agree that they're likely not as useful to some people and should be able to be disabled, or removed.

**Comment by danielnelson** [comment]
I guess since it is primarily debug data we should remove them, I'll create a pull request.

**Comment by ronnocol** [comment]
Thanks. Looks good to me. Since Splunk doesn't charge for indexing dimensions/tags, I didn't see a problem with leaving config breadcrumbs in the data. If people relied on them... then they can add them back in as tags.

**Comment by zszia** [comment]
Wow, that was fast. Thank you very much!
Regarding "Since Splunk doesn't charge for indexing dimensions/tags, I didn't see a problem with leaving config breadcrumbs in the data." - yes, you are right. 
But there are other costs: disk space (with millions of events times about 50 bytes per event), network (the data must be transferred), performance (process the data at index time and each splunk query must read more data from the disk), etc. 
But maybe I'm totally wrong here and Splunk optimizes this internally and reduces the amount of data stored.
