### ISSUE TITLE
Date Processor - Insertion of timestamp as a field

### ISSUE THREAD

**Issue by richjyoung** [influxdata/telegraf#7449]
## Feature Request

Insertion of timestamp as a numeric field using date processor, in addition to the current string-based formats.

### Proposal:

Add the ability for the date processor to include the current point timestamp as a field, in nanoseconds, millis and unix formats.

### Current behavior:

Only string-based formats can be added as a tag, using the standard Go reference time syntax.

### Desired behavior:

Ability to insert a numeric field with the point timestamp, in millis, nanoseconds or unix format.

### Use case:

Based on [Writing Logs Directly to InfluxDB](https://www.influxdata.com/blog/writing-logs-directly-to-influxdb/), the Chronograf Log Viewer expects a timestamp field in the measurement as well as an individual point timestamp, as the log source may report a different time. This is fine if the log source has the ability to output influx format directly, but does not work when using grok to parse formatted log lines. Grok patterns and modifiers allow the point timestamp to be set, but do not offer a way to retain this as a numeric field, resulting in the Chronograf Log Viewer showing all the log entries in the correct order, but with a timestamp of 01/01/1970.

Happy to submit a PR if this is something that would be suitable to merge, but would like some discussion of how the configuration settings should be named

**Comment by danielnelson** [comment]
Thanks for offering to help with this, you could add some new sentinel values to the `date_format` option, these are the same strings we use in the csv parser:
```
date_format = "unix"
date_format = "unix_ms"
date_format = "unix_us"
date_format = "unix_ns"
```

We probably want to add a `field_key` option as well, if both `tag_key` and `field_key` is set it would have to be an error in the Init() function.

> Grok patterns and modifiers allow the point timestamp to be set, but do not offer a way to retain this as a numeric field, resulting in the Chronograf Log Viewer showing all the log entries in the correct order, but with a timestamp of 01/01/1970.

Can you also open an issue with Chronograf, if no timestamp field is set the log viewer ought to fallback to the timestamp of the event.

**Comment by richjyoung** [comment]
Raised the issue with Chronograf here: https://github.com/influxdata/chronograf/issues/5472

Pull request has also been submitted.

**Comment by powersj** [comment]
Hi @richjyoung,

I see the Chronograf issue was resolved and released. Do you still need something from Telegraf anymore?

Thanks!
