### ISSUE TITLE
SNMP input does not report common errors

### ISSUE THREAD

**Issue by smogsy** [influxdata/telegraf#7450]
as discussed with @danielnelson 
Error messages seem to be broken or non-existent for the following areas:
-     Error when no fields/tables are defined intelegraf.conf

-     Error if only tags are defined, (you need at least 1 check that is not tagged)
we may not be able to detect this in all cases at startup so this may need to be a runtime error.

-     Error if version=3 snmp is not fully configured.
- OID not valid - spell an OID incorrectly does not produce error on --test cli. it stops all checks..
example i did 
                [[inputs.snmp.table.field]]
                name = "octets_sent"
                 oid = "IF-MIB::ifHCoutOctet
instead of
                [[inputs.snmp.table.field]]
                name = "octets_sent"
                 oid = "IF-MIB::ifHCOutOctet

**Comment by MyaLongmire** [comment]
I am going to close this as `snmptraslate` is deprecated in telegraf and supported versions no longer use it due to performance issues. If you are having issues with recent `snmp` update, please open another ticket with all relevant information.

**Comment by Hipska** [comment]
This has nothing to do with snmptranslate. This is about checking the config
