### ISSUE TITLE
Add sonic_telemetry input plugin

### ISSUE THREAD

**Issue by wililupy** [influxdata/telegraf#7472]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Software for Open Networking in the Cloud (SONiC) is an open source networking operating system. SONiC using gNMI for streaming telemetry, and we created an input plugin so that Telegraf could leverage this for streaming telemetry to InfluxDB. By adding this plugin to Telegraf natively, users using SONiC can use Telegraf to gather telemetry data from their network switches.
We also added an FRR plugin specific to SONiC to be able to gather BGP information (neighbors, statistics, etc.) extended that functionality of the sonic_telemetry plugin to get more insights into a switch running SONiC.

### Current behavior:
Does not current exist in Telegraf

### Desired behavior:
sonic_telegraf input plugin uses gNMI and FRR to pull telemetry data from switches running SONiC.

### Use case: 
Currently there is no mechanism in place to gather telemetry data from switches running SONiC. This PR implements the required plugin to work with SONiC.

**Comment by bewing** [comment]
Is there a large difference between the existing gNMI plugin and this code?  Is it possible to just have one gNMI plugin instead of maintaining multiple per vendor? (I know the existing `cisco_telemetry_gnmi` input plugin works against Arista devices for openconfig statistics).  That way it is easier to add common features to all vendor platforms that support gNMI streaming

**Comment by wililupy** [comment]
We did initial testing with the cisco_telemetry_gnmi plugin, and found we had to make some changes to it for it to work with SONiC's gNMI. Since we didn't want to make changes to the existing Cisco telemetry gNMI plugin, we branched from it and added FRR so that we could get full telemetry from SONiC in a SONiC specific telemetry.

**Comment by skg-net** [comment]
@danielnelson @wililupy @bewing @evanphx @ibspoof This PR is sitting for more than 6 months. Can we get this merged? Whom we need to follow up with?

**Comment by evanphx** [comment]
@skg-net tagging random people is super rude. Do not do it.

**Comment by skg-net** [comment]
@evanphx  Those are the options provide by Github, I guess those are the people either commented on the issue or the PR. Apologies If I have offended anyone.

**Comment by yitongtse** [comment]
Is SONiC telemetry supported by Telegraf yet?

**Comment by wililupy** [comment]
It looks like the changes the to gNMI plugin have been made and it can be used in SONiC. This issue can be closed.
