### ISSUE TITLE
AMQP output with dynamic headers

### ISSUE THREAD

**Issue by gboor** [influxdata/telegraf#7475]
## Feature Request

AMQP output with dynamic headers

### Proposal:

Setting dynamic headers on AMQP messages would allow us to make use of RabbitMQ plugins like https://github.com/noxdafox/rabbitmq-message-deduplication - which relies on headers to deduplicate messages. We are currently pushing data from 2 local systems (for failover reasons) through Telegraf into RabbitMQ and cannot deduplicate this data unless we manually post-process.

I propsose using a new config variable and go templates to achieve this. Along the lines of;

```
dynamic_headers = {"x-deduplication-header" = "{{.name}}-{{.timestamp}}"}
```

using the payload as JSON as the template input.

### Current behavior:

Dynamic headers do not exist.

### Desired behavior:

Headers to be generated dynamically based on payload.

### Use case: 

My main use case is the ability to leverage RabbitMQ plugins that rely on dynamic headers, for deduplication primarily.

**Comment by danielnelson** [comment]
The way we would probably want to enable this is to allow writing a tag value as the header, this would allow using processors such as the template processor to customize the tag without putting the responsibility of templating into the output plugin:
```
header_tags = {"x-deduplication-header" = "id"}
```

**Comment by Caedin** [comment]
Was this ever integrated? I need to push messages to event hub for my current project using telegraf.

**Comment by gboor** [comment]
No, I've not used telegraf for years now, so it's no longer useful to me.

**Comment by srebhan** [comment]
Feel free to reopen the issue or open a new one if you or anyone else need this feature!
