### ISSUE TITLE
Jolokia2 plugin to apply lowercase to all Tags and Fields

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#7480]
## Feature Request

Currently, when using a config like the below, the default metric output includes mostly capitalized keys.  This isn't really that bad of a thing but, in the interest of keeping things uniform, would it make sense to apply lowercase enforcement to this input?  Otherwise, this plugin would be complemented with `[[processors.strings]]`:
```
[[inputs.jolokia2_agent]]
  default_tag_prefix = ""
  default_field_prefix = ""
  default_field_separator = "."
  urls = ["http://localhost:8778/jolokia"]

  [[inputs.jolokia2_agent.metric]]
  name         = "kafka_replica_manager"
  mbean        = "kafka.server:name=*,type=ReplicaManager"
  field_prefix = "$1."
```

Output of this looks like:
```
kafka_replica_manager,host=<host>,jolokia_agent_url=http://localhost:8778/jolokia FailedIsrUpdatesPerSec.Count=0,FailedIsrUpdatesPerSec.EventType="failedUpdates",FailedIsrUpdatesPerSec.FifteenMinuteRate=0,FailedIsrUpdatesPerSec.FiveMinuteRate=0,FailedIsrUpdatesPerSec.MeanRate=0,FailedIsrUpdatesPerSec.OneMinuteRate=0,FailedIsrUpdatesPerSec.RateUnit="SECONDS",IsrExpandsPerSec.Count=0,IsrExpandsPerSec.EventType="expands",IsrExpandsPerSec.FifteenMinuteRate=0,IsrExpandsPerSec.FiveMinuteRate=0,IsrExpandsPerSec.MeanRate=0,IsrExpandsPerSec.OneMinuteRate=0,IsrExpandsPerSec.RateUnit="SECONDS",IsrShrinksPerSec.Count=0,IsrShrinksPerSec.EventType="shrinks",IsrShrinksPerSec.FifteenMinuteRate=0,IsrShrinksPerSec.FiveMinuteRate=0,IsrShrinksPerSec.MeanRate=0,IsrShrinksPerSec.OneMinuteRate=0,IsrShrinksPerSec.RateUnit="SECONDS",LeaderCount.Value=13,OfflineReplicaCount.Value=0,PartitionCount.Value=13,UnderMinIsrPartitionCount.Value=0,UnderReplicatedPartitions.Value=0 1588882540000000000
```

Notice that Fields are written like: `FailedIsrUpdatesPerSec.Count`

Obviously, simply apply lowercasing to these Fields would probably require tracking and prepending each letter affected with a `_`....or something like that, as otherwise they'd be virtually impossible to read.

**Comment by danielnelson** [comment]
I'd like to have a snake_case function added to the string processor.  I don't think we should consider renaming the fields unless we do a major makeover to this plugin, its not worth the disruption.  Even then it may make sense to stick with CamelCase since this is such a part of Java code.

**Comment by samhld** [comment]
@danielnelson ok that's fair.  By "renaming", you mean bringing it lower case and snake_casing it?  If that's what you mean and it doesn't make sense to do that, we can close this out.  Part of me also thought there was a deeper TICK-related functional reason that Telegraf followed that format.  If not, this would be purely cosmetic.

**Comment by helenosheaa** [comment]
I'm going to close this out as I think it makes sense to stick with CamelCase for the jolokia2 plugin. If you think it would be worth adding a snake case option to the existing strings processor as a config option for people feel free to reopen!
