### ISSUE TITLE
Notify systemd about readiness instead of asynchronous startup

### ISSUE THREAD

**Issue by gsauthof** [influxdata/telegraf#7485]
### Relevant telegraf.conf:

```toml
# minimal config that contains a syntax error
```

### System info:

Telegraf 1.14.2, CentOS 7

### Steps to reproduce:

1. `systemctl stop telegraf`
2. introduce a small syntax error into `/etc/telegraf/telegraf.conf` such as an accidentally commented section header
3. `systemctl start telegraf`
4. `echo $?`
5. `sleep 3`
6. `systemctl status telegraf`

### Expected behavior:

I expect that the `systemctl start telegraf` fails because the configuration is erroneous, i.e. that it's exit code is unequal zero.

Also, the `systemctl status telegraf` command should reliably report that the service isn't running.

### Actual behavior:

`systemctl start telegraf` doesn't fail, i.e. its exit status is `0`. `systemctl status telegraf` does report a failure status - however, this only works reliably if you add a sleep before it.

### Additional info:

This is caused by the current `telegraf.service

https://github.com/influxdata/telegraf/blob/48b8357f016e39724bff00899276199cd6d3f643/scripts/telegraf.service#L1

It doesn't specify the service type and thus it default to `Type=simple` which means that

> [..] the service manager will consider the unit started immediately after the main service  process has been forked off. 

([systemd.service(5) f31 man page](https://manpath.be/f31/systemd/243.5-1.fc31.x86_64/5/systemd.service#L100))

Meaning that at the time telegraf parses its config `systemctl start telegraf` already finished.

The standard solution to this is to switch the service to `Type=notify` and signal readiness back to systemd (i.e. after config files are read).

See also:

- https://github.com/coreos/go-systemd/
- an [example that uses go-systemd](https://vincent.bernat.ch/en/blog/2017-systemd-golang#readiness)

**Comment by isodude** [comment]
I will check if this is easy to implement.

This is so annoying.
