### ISSUE TITLE
Windows: Unsupported logtarget: eventlog, using stderr

### ISSUE THREAD

**Issue by AlexHeylin** [influxdata/telegraf#7487]
When running from console, this erroneous message is output during startup if using eventlog as logtarget.

### Relevant telegraf.conf:
```toml
[agent]
logtarget = "eventlog"
```

### System info:
Telegraf 1.13.3
OS: All Windows Server 2012 R2, 2016, 2019
Bittiness: 64

### Steps to reproduce:

1.  Set logtarget = "eventlog" in config file
2. Start telegraf from command line (either using config from service, or for example with --test)

### Expected behavior:
Not to see this message.

### Actual behavior:
See this message logged to stdout / stderr (not sure which) 

### Additional info:
This is generated in logger.go lines 106 - 122 due to missing case to handle eventlog.

I've never written Go before, so while I think I could add the case - I can't work out the impact given Windows logging seems to override what's set in logger.go anyway.   Hence not sending PR, but opening issue so someone with better knowledge can assess. 

This message confused me a lot when I first started using Telegraf, until I learned to ignore it.

**Comment by KirkGitHub** [comment]
I'm also having this problem. I can't seem to get my Telegraf to create and write to a log file within windows.

**Comment by Jagularr** [comment]
For what it might be worth, telegraf seems to support eventlog currently if it's ran as a windows service. This functionality is missing otherwise, but hopefully will be fixed with the above pull request.
