### ISSUE TITLE
Add MACHBASE Input Plugin

### ISSUE THREAD

**Issue by MACHBASE** [influxdata/telegraf#7493]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

A plugin to fetch information from MACHBASE Database

### Current behavior:

Does not current exist in Telegraf

### Desired behavior:

MACHBASE input plugin uses API to pull telemetry data from running MACHBASE Database.

### Use case:

This plugin will be used to check the status of MACHBASE DB by collecting and monitoring system information related to DB and Session or Statement information.

**Comment by powersj** [comment]
Closing this as the PR was closed due to inactivity.
