### ISSUE TITLE
Is Shared Subscription Feature Available in Telegraf MQTT Consumer Plugin?

### ISSUE THREAD

**Issue by guzelcihad** [influxdata/telegraf#7494]
Hi,

I've 2 telegraf agent and I don't want to fetch duplicate data from mqtt broker. So, this is done with shared subcription feature implemented in MQTT 5. 

I want to learn that is it implemented in Telegraf Mqtt Consumer Plugin?

Thanks.

**Comment by danielnelson** [comment]
I believe this is supported, but I have not tested personally.  You should only need to use the `$share/GROUPID/TOPIC` topic syntax.  Telegraf 1.14 is using the [1.2.0](https://github.com/eclipse/paho.mqtt.golang/releases/tag/v1.2.0) release of the paho client.

**Comment by ssoroka** [comment]
We're using the github.com/eclipse/paho.mqtt.golang ([docs](https://godoc.org/github.com/eclipse/paho.mqtt.golang)) library. It doesn't seem to support this feature. We do have support for filtering by topic, if that's helpful for you.

Let me know what you think,
Cheers.
