### ISSUE TITLE
vsphere plugin failure causing telegraf service to fail

### ISSUE THREAD

**Issue by baruchih10** [influxdata/telegraf#7500]
The problem is: vsphere failed due to incorrect login details causing telegraf service to fail.
Expectations: 
1. vsphere plugin will stop to work and the rest of plugins will continue to work
2. telegraf service will continue to process other plugins.

Here is from /var/log/messages:
May 12 17:44:33 ilgss0396 telegraf: 2020-05-12T14:44:33Z E! [agent] Service for [inputs.vsphere] failed to start: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
May 12 17:44:33 ilgss0396 telegraf: 2020-05-12T14:44:33Z E! [telegraf] Error running agent: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
May 12 17:44:33 ilgss0396 systemd: telegraf.service: main process exited, code=exited, status=1/FAILURE
May 12 17:44:33 ilgss0396 systemd: Unit telegraf.service entered failed state.
May 12 17:44:33 ilgss0396 systemd: telegraf.service failed.
May 12 17:44:34 ilgss0396 systemd: telegraf.service holdoff time over, scheduling restart.
May 12 17:44:34 ilgss0396 systemd: Started The plugin-driven server agent for reporting metrics into InfluxDB.

**Comment by danielnelson** [comment]
Telegraf requires the connection to work initially on startup, this is nice because it alerts you to errors in the configuration immediately.  There is an existing feature request to allow startup even if the inputs/outputs are not operational initially: https://github.com/influxdata/telegraf/issues/3723
