### ISSUE TITLE
Support merging configs

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#7501]
## Feature Request

Explicitly around the case of supporting multiple disparate Telegraf configurations, which comes in from 1. cloud, 2. community template, and 3. Telegraf configuration service, we need the ability to take multiple desired Telegraf configs merge them into a single Telegraf configuration that Telegraf can run.

An acceptable solution to this could be an external project or library, but that is not necessarily a requirement.

This is important because community template users currently need to manually merge configs. If we don't do this project, it will encourage template authors to work around the issue by merging separate templates into "template stacks" to make template installation easier, at a high cost to flexibility and an explosion in variants (vs what would be small composable templates if we had this).

### Use cases:

1. Installing multiple community templates installs multiple Telegraf configurations. It's not unusual for a single server to be collecting data for multiple templates, eg, redis, system, internal, kafka, or any stack you can imagine.
2. This avoids you having to predefine Telegraf "roles" where a role is a set of plugins to use. You could generate the "role" config on the fly from known configurations.

### Requirements/Nice-to-Haves: 

- [R] Take two configs and produce a single config from it
- [R] Combine multiple outputs pointing to the same destination, respecting buckets
- [N] Generate a default output (eg, for cloud), when none is defined (when desired)
- [N] auto pipelining/namespacing, (or tagpassing?) to ensure configs don't have unintended behavior when merged

### Unresolved issues:

- There will be issues around merging multiple configurations with complex workflows, eg, a lot of processors/aggregators, especially with ones using generic field names. Stand-alone configs can get away with not checking metric names, but can cause issues when merged. Config pipelining/namespacing could be a solution here.

### Proposal:

- Create a new library that knows how to understand/merge multiple configs, smart enough to remove duplicate configs, with idempotent merge behavior.
- [option 1] extend Telegraf to accept multiple --config arguments
- [option 2] create a stand-alone binary that can merge config files.

**Comment by danielnelson** [comment]
My initial reaction is that InfluxDB Templates should make use of the `--config-directory` to add configuration, which in effect merges it.  Can you expand on why this functionality is needed?

**Comment by M0rdecay** [comment]
Is it possible to extend the functionality of the `--config-directory` key so that several directories can be specified?

Usage example - we store agent configurations in directories with the names of the applications to which they relate. The scheme is approximately as follows:
```
.
├── bin
│   └── telegraf
├── conf
│   ├── telegraf.conf
│   ├── base.d
│   ├── app_1.d
│   ├── app_2.d
│   ├── app_3.d
.....
```
Now we have to combine the directories during the deployment to separate the general configuration in `telegraf.conf`, which contains the parameters of the agent and outputs, and the configurations associated with applications or host monitoring.
This step creates some inconvenience - in particular, after the deployment it is impossible to understand which applications a particular agent is responsible for, just by looking in the `conf` directory.

The ability to list several directories with configurations would be convenient.
Now, if you try to specify: `--config-directory dir1 --config-directory dir2` only files from `dir2` will be processed.
And if so: `--config-directory dir1 dir2`, then from `dir1`.

**Comment by mhall119** [comment]
> My initial reaction is that InfluxDB Templates should make use of the `--config-directory` to add configuration, which in effect merges it. Can you expand on why this functionality is needed?

So that you can refer to multiple remote configs via URL. If you install multiple InfluxDB Templates into your server, say Linux host monitoring, MySQL monitoring and Apache monitoring, you will have multiple Telegraf configs available to run, and ideally you'd like to run them both from a single instance of the Telegraf binary without having to download them manually.

**Comment by danielnelson** [comment]
@M0rdecay Don't do any code yet.  It is less about supporting multiple directories than the semantics of what it would mean.  I'm not sure I fully understand your example, but have you tried creating one file in the config-directory per application?

@mhall119 I'm good with adding a way to get multiple configurations remotely, but I think Cloud needs to support configuration snippets.  These are what is generally placed in the config-directory and it makes more sense for templates to use these as the basic unit.  It doesn't, in my opinion, make sense for templates to provide their own output and agent configurations.

**Comment by M0rdecay** [comment]
@danielnelson, don’t quite understand what you are talking about in this part:
> but have you tried creating one file in the config-directory per application?

I’ll try to describe the case in more detail.
In the repository we hold many configurations for monitoring various applications, both public and our internal. Each group of configurations is located in a directory called by the pattern **PRODUCT_NAME.d**, plus **base.d** with configurations for host monitoring.
Inside each directory there are sets of configurations - one for each application from the product, plus sets of processors and aggregators:
```
KAFKA.d
  ├── kafka_consumer.conf
  ├── kafka_cousumer_processors.conf
SOME_APP.d
  ├── _processors_common.conf
  ├── component1.conf
  ├── component1_processors.conf
  ├── component1_aggregators.conf
....
  ├── componentN.conf
ONE_MORE_APP.d
....
```
There are many products that are monitored, and there can be more than 20 configurations within the product directory. In this form, it is convenient to conduct development - separately configure inputs, separately configure processors and aggregators.

When deploying via Ansible, depending on the configuration of the stand, only the necessary directories with the necessary templates are delivered to the host (there is a two-stage selection by pattern - first the directory is selected, then its contents are selected). Only the **base.d** directory with the configuration for host monitoring is always delivered.
The result is the directory structure that I described above.

Then, we have two ways, and we have not yet decided what we should do:
 - or we create one instance of systemd-unit for each directory, for each we specify the personal parameter `--config-directory`; but in this case several agents are running on the host where more than one application is installed
 - or we merge all the directories with the configurations into one; but in this case we lose visibility

Both of these options follow from the fact that only one directory can be specified in the `--config-directory` argument.
If we had the opportunity to specify many directories from which to read the configurations, this would allow us to save one unit per host and leave a convenient directory structure.

What I suggested earlier means the following - telegraf will not read configurations from one directory, but from all those listed through the `:` character, as if all these configuration files were in the same directory.

I hope I managed to explain the case.

**Comment by danielnelson** [comment]
I had to check, but it appears the config-directory is searched recursively.  Could you just install these into subdirectories?

**Comment by M0rdecay** [comment]
I will definitely check and report the result, thanks!

**Comment by M0rdecay** [comment]
> config-directory is searched recursively

Yes, this works, but telegraf always requires the use of `--config`. It was expected that only `--config-directory` would be sufficient.

**Comment by danielnelson** [comment]
That's a known bug: #5571, I believe it is possible for the `--config` to just be an empty file though.

**Comment by M0rdecay** [comment]
Yes, I pointed to an empty file, this is a suitable solution, thanks.

**Comment by samhld** [comment]
@danielnelson Question about that idea: how does `--config-directory` deal with configs of the same name? Is there a merging of those or are they instantiated separately?  If the latter, would Telegraf not be doing unnecessary work by pulling essentially (perhaps exactly) the same metrics from the same place from multiple plugins?
