### ISSUE TITLE
nginx plugin doesn't work on 0.10.3

### ISSUE THREAD

**Issue by idestis** [influxdata/telegraf#751]
hello, i wanna raise an issue about nginx plugin
after update from 0.2.4 to 0.10.0-0.10.3 telegraf can't write into the database any output from nginx plugin

`[http] 2016/02/24 08:44:44  - telegraf [24/Feb/2016:08:44:43 +0000] POST /write?consistency=&db=telegraf&precision=s&rp= HTTP/1.1 204 0 - InfluxDBClient d9f67a36-dad2-11e5-8f93-000000000000 83.717439ms`

```
2016/02/24 08:45:20 Gathered metrics, (10s interval), from 7 inputs in 4.532714ms
2016/02/24 08:45:20 Flushed 26 metrics to output influxdb in 3.102005ms
```

Telegraf config test shows me

```
* Plugin: nginx, Collection 1
> nginx,port=80,server=localhost accepts=649150i,active=7i,handled=649150i,reading=0i,requests=6079394i,waiting=6i,writing=1i 1456303574161092635
```

**Comment by sparrc** [comment]
The test output looks good, are you aware that the measurement name(s) have changed in Telegraf 0.10? Do you not have an `nginx` measurement in the db?

**Comment by idestis** [comment]
Thx. 
You merged all measurements in one.... ;)

**Comment by sparrc** [comment]
yep, that was a major change going from 0.2.x -> 0.10.x, I tried to put a warning in here: https://github.com/influxdata/telegraf#installation about it :)
