### ISSUE TITLE
Docker input plugin - Unix CPU usage_percent is inaccurate due to incomplete sampling of CPU usage data

### ISSUE THREAD

**Issue by gnjack** [influxdata/telegraf#7520]
The docker input plugin misses some consumed CPU cycles from its sampled data, causing inaccurate `usage_percent` calculations. This is particularly bad when a container has very spiky CPU usage.

### Steps to reproduce:

1. Create a container that has brief spikes in CPU but is otherwise idle
2. The `usage_percent` metric for that container will miss most of the CPU spikes.

### Actual behavior:

Here is an example with a container that spikes from 0% to ~7% every 30 seconds.
When calculating the CPU usage percent manually using `usage_total difference / usage_system difference * CPU cores` we see these regular spikes as expected (green line). However the `usage_percent` metric (yellow line) may show either a very low or very high percentage depending on when telegraf sampled the data:
![image](https://user-images.githubusercontent.com/5956751/82061286-6b853280-96c0-11ea-9223-221dad3dab74.png)

This becomes even more misleading when zooming out and averaging. As telegraf's sampling is slightly out of phase with the CPU spikes, `usage_percent` will fluctuate between 0% and 10% over the course of several hours, despite the actual CPU usage remaining constant (on average).
![image](https://user-images.githubusercontent.com/5956751/82061276-688a4200-96c0-11ea-9e1e-6ee4104af39b.png)

If we look at the same graphs and time periods for a container with much less spiky CPU usage, both lines match much closer:
![image](https://user-images.githubusercontent.com/5956751/82062199-ab004e80-96c1-11ea-8fba-8ad7c5572850.png)
![image](https://user-images.githubusercontent.com/5956751/82062206-ad62a880-96c1-11ea-9325-cd0ed599640e.png)
Although the `usage_percent` metric may slightly under or over estimate CPU usage.

### Expected behavior:

The plugin should calculate the change in `usage_total` and `usage_system` **since the previous time the telegraf plugin collected data** and use this to calulate the `usage_percent`.

Currently, it  calculates the change in `usage_total` and `usage_system` **since the previous time docker collected data**. This means it misses any CPU cycles between the previous telegraf gather and the previous docker stats calculation, which is likely to be far more often than telegraf is gathering data.

This is due to it getting the previous CPU stats from the docker API, instead of the plugins own state from the last telegraf gather:
https://github.com/influxdata/telegraf/blob/f74824eecb9f593c4190ae0f07f7e4983f158c04/plugins/inputs/docker/docker.go#L660-L661

I made a quick timeline diagram to show what I think is happening. Not sure if it helps or is just confusing!
![image](https://user-images.githubusercontent.com/5956751/82066618-8f984200-96c7-11ea-83b9-fe90b9831842.png)

**Comment by danielnelson** [comment]
Thanks for taking the time to write such a detailed bug report.

I'm struggling with why the proposed change of behavior would be more correct though.  It seems that either method is equally accurate, but if we calculate over the previous Telegraf interval then the usage is averaged over a longer interval.  The usage will appear less spiky, but it will also be less immediate.

I do like the idea of the usage matching the input's interval.

As a downside, it seems the usage wouldn't match up with the `docker stats` command.  Also we would need to make two collections before we can report usage, this is primarily an issue when running with `--test`.

Could be helpful to get a copy of your queries for experimentation.

**Comment by gnjack** [comment]
>It seems that either method is equally accurate, but if we calculate over the previous Telegraf interval then the usage is averaged over a longer interval. The usage will appear less spiky, but it will also be less immediate.

Technically correct, but you could argue that for everything that calculates CPU usage every X interval. To take the `docker stats` command as an example, it refreshes the CPU usage once every second. It calculates the % shown as an average since the last refresh. The same applies for both the [telegraf cpu input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cpu#troubleshooting):
> On Linux systems the /proc/stat file is used to gather CPU times. Percentages are based on the last 2 samples.

and [the Unix `top` command](http://man7.org/linux/man-pages/man1/top.1.html#3._FIELDS_/_Columns):
> The task's share of the elapsed CPU time since the last screen update, expressed as a percentage of total CPU time.

All of which could be more "immediate" by only calculating the CPU usage in the last few milliseconds, that would be a very "immediate" value, but also very misleading.

    

> As a downside, it seems the usage wouldn't match up with the docker stats command.

Correct, a minor downside. It would become an average of the values shown by `docker stats` command over the collection interval. If the telegraf collection interval was 1s, I believe they would be equal most of the time, but it could not be guaranteed.

> Also we would need to make two collections before we can report usage

On the first collection, you could get the previous values from the docker API, as is currently done on all collections.

**Comment by gnjack** [comment]
Unfortunately it looks like I closed the tab with my InfluxDB queries without saving over the weekend 🤦 Happy to write them again, if needed.

**Comment by crunchy-vonage** [comment]
I think by the very nature of the an average I would expect it to be averaged the whole of the  (telegraf) reporting interval.

I would never have an expectation that the reporting intervals align with docker or other measures. It is a nice have that the statistic is from the same source (using same metric and calculation).

Having an average that skips over periods of time, could be considered accurate by some definitions I guess but is very misleading.  It feels analogous to when teams average their percentiles; it show's something but I know not what!

This does raise the question of what you can do with the cpu_average, you are probably going to want to aggregate or sample it for reporting and alerting. Aggregating an aggregate is problematic  (meaning is unclear) and sampling the value again leads to skipped periods of time.

**Comment by danielnelson** [comment]
On the queries, I'm mostly interested in the usage percent calculation from raw values with usage_system and usage_total.  It seems this is the best method to use, since you can get the aggregate over any time period, but I'm unsure if we can query this with InfluxQL alone.

At any rate, I'd support your proposed changes: calculate using the values of the previous query and use the previous values from the API.

**Comment by reimda** [comment]
Came across this while looking through inactive issues.

@gnjack is this still a problem for you? Are you able to submit a PR to make the change you and Daniel discussed?
