### ISSUE TITLE
SNMP Table index not matching properly:

### ISSUE THREAD

**Issue by neeles83** [influxdata/telegraf#7522]
## Feature Request
When SNMP Tables are resolved they have an index. But the index is compost out off multiple depths. Depending on the table requested. 

I hope I can make this clear in below example

The metric retrieved:
CISCO-BGP4-MIB::cbgpPeerAddrFamilyPrefixTable

The BGP neighbor stats, holds the advertised prefixes and if we open the CISCO-BGP4-MIB it dictates that it the cbgpPeerAddrFamilyPrefixTable has the following indexes: 
BGP4-MIB::bgpPeerRemoteAddr
CISCO-BGP4-MIB::cbgpPeerAddrFamilyAfi
CISCO-BGP4-MIB::cbgpPeerAddrFamilySafi

With the option: index_as_tag = true

The metric looks as follwoing:
cisco_BGP_Stats_cbgpPeerAcceptedPrefixes{agent_host="10.120.x.x",host="e955e22xxxx",index="10.120.2.2.1.1",instance="10.2.2.2:9126",job="telegraf",sysName="devices-name"}

As you can see the index is "10.120.2.2.1.1" where the first four numbers represent the BGP4-MIB::bgpPeerRemoteAddr the fith octet the CISCO-BGP4-MIB::cbgpPeerAddrFamilyAfi and the the sixt octect CISCO-BGP4-MIB::cbgpPeerAddrFamilySafi.

### Proposal:
Use two additional parameter to one to determine the order of the tags and the second to determine the index. 

Another option is if there are multiple walks possible to drop/ignore an X number of trailing OID numbers in the path. In this example you would ignore the last two the Safi and Afi. The result is that the index should match the bgpPeerRemoteAddr. These 3 options would make it more flexible. 

Further more with QoS these tables are in multiple tables with multiple depts.

### Current behavior:
The SNMP table is returned but the tags aren't applied and the index is not deciphered.

### Desired behavior:
The SNMP table is returned and in addition the tags and index is added to the metric to properly identify and match the metric to it's underlying structure in according to the MIB mapping. 

### Use case: 
Now the entries are hard to relate to their original base metric. 
We could do this with a processor. But I'm pretty sure that that would not work for all SNMP Tables.

**Comment by neeles83** [comment]
Sorry just reading the documentation of the SNMP Plugin and found the "oid_index_suffix = """ and "oid_index_length = 0". 

I expect that this would fix it. But still adding a field to also map the other identifiers would and sequence them would completely match the index. But maybe I'm reading it wrong. Now you are only able to strip of the trailing part and thus match the other identifiers. 

In the example you still miss the mapping to Afi or Safi id's.

**Comment by sjwang90** [comment]
Hey @neeles83, is still still an issue you're running into? Please provide any updates.

**Comment by Hipska** [comment]
You can solve this by using processors to parse and split the index.

**Comment by sjwang90** [comment]
Thanks @Hipska! Closing this issue
