### ISSUE TITLE
vCenter 7 support

### ISSUE THREAD

**Issue by IrishMLK** [influxdata/telegraf#7527]
I am having a hard time getting data into the Chronograf dashboards and then realized the plugin only supports up to 6.7.  I recently upgraded to vCenter 7 in my lab and am testing the TICK stack against that.

Is there a timeline for vSphere 7 support?

**Comment by Aqualie** [comment]
Looking for this one as well.

**Comment by danielnelson** [comment]
@prydin Would this only require us to update govmomi, or would it be more involved than that?

**Comment by prydin** [comment]
I have the plugin running against vSphere 7. Could you please point out what the issues are? Are you looking for support for some new functionality in vSphere 7 or do you have concerns about forward compatibility with vSphere 7 in general?

**Comment by chench00** [comment]
Just wanted to report that while mostly everything works fine, I can no longer see my cluster information even though nothing has changed. I have restarted both telegraf and influx.

**Comment by DonGiotto** [comment]
Same like @chench00 - everything looks fine, but I've got no cluster informations/names.
telegraf 1.15.2
Debian 10
