### ISSUE TITLE
some of input.mysql plugin should be reported as type Counter

### ISSUE THREAD

**Issue by camaeel** [influxdata/telegraf#7528]
Some mysql metrics (for example: com-select, com-update, com-insert, com-delete, connections, querries, questions, slow queries) contain cumulative values. But they are treated as Gauge and sent to stackdriver (and maybe other outputs) as gauges: 
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/stackdriver/stackdriver.go

Stackdriver automatically creates configuration for metrics based on reported MetricKind. 

Mysql input plugin should explicitly define some metrics as Counters to send them to outputs correctly.

**Comment by danielnelson** [comment]
Before we can do further type classification we need to implement a method for passing the type without splitting the metric.

related: #3670

**Comment by powersj** [comment]
Going through old issues and came across this one. This change would require a large overhaul to how metrics are handled in Telegraf. I do not think this is something we would take on currently or have in plan.

**Comment by powersj** [comment]
Stackdriver output now has the ability to define specific types like counters or gauges. Allowing the user to override the settings of input plugins.
