### ISSUE TITLE
Telegraf Windows 7 and  Modbus RTU plugin

### ISSUE THREAD

**Issue by modzia** [influxdata/telegraf#7535]
I have a question .
How to configure a Modbus RTU Controller in a  Telegraph Windows System ?
I use a USB RS-485 converter and the system sees it as USB2.
I tried different options, but unsuccessfully.

**Comment by danielnelson** [comment]
I don't have means to test this, but from [this site][] the format for USB to serial converters should be something like:
```
controller = '\\.\COM24' # make sure to use single quotes!
```

Let me know how this goes and if you still have an error, include it in your comment.

[this site]: https://www.xanthium.in/Serial-Port-Programming-using-Win32-API

**Comment by danielnelson** [comment]
As noted by @D4V1D-G in https://github.com/influxdata/telegraf/pull/4623#issuecomment-644298685, the plugin currently will not accept this format.

**Comment by sjwang90** [comment]
Closed in https://github.com/influxdata/telegraf/pull/9570

**Comment by sjwang90** [comment]
@d4v1d-G @modzia @garciaolais The latest Telegraf RC includes support for RTU/ASCII over TCP in the Modbus input plugin. If you can test the release candidate that would be great: https://github.com/influxdata/telegraf/releases/tag/v1.20.0-rc0

**Comment by TimurDela** [comment]
Hello, 
using telegraf 1.21.4 on a Windows 10 Pro, I am not able to use access my serial port with
```[TOML]
controller = '\\.\COM1'
```
In debg mode, telegraf returns
```
initializing client failed: invalid controller "\\\\.\\COM1"
```
