### ISSUE TITLE
Add plugin that implements a simple file based queue system

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7548]
### Proposal:

Many teams are using files and directories to implement ETL jobs.

It would be useful to have a plugin that parses a file once and when it reaches the EOF moves the file to a target success or failure directory.

Like the `tail` plugin, this plugin would process the file once and would support durable delivery with tracking metrics.  Unlike `tail` it would stop processing when reaching EOF.

The plugin should support transparent handling of gzipped files, which would great to support in both `file` and `tail` as well.

The plugin should contain `internal` metrics for the number of files processed.

### Current behavior:

This cannot be accomplished reliable, but some aspects can be faked by using a outside process to stage and move files.

### Use case: 

See https://github.com/influxdata/telegraf/issues/5781

**Comment by sjwang90** [comment]
This is a common use case for major Industrial IoT setups that have decides that collect data in remote areas with poor connectivity and end up backlogging a lot of data and transmitting in compressed formats (gzip)

**Comment by SimonMcN** [comment]
proposal:
add flag rename_after_process = 'true'
add flag rename_prefix = 'processed'
add flag rename_suffix = ''
then after the file is read, if  rename_after_process == 'true' then rename according to rename_prefix and rename_suffix

Would that work ?

**Comment by sjwang90** [comment]
Requirements for large scale IIoT environments: @boris377 @suseelapattamatta
- Translation of the file lines into line protocol (our origin file doesn’t match line protocol).
- Potential large batches of incoming files of 1000+ (not uncommon)
- Continuous processing (directory monitoring portion) – We get 1-3 files per minute per asset except when the above happens
- Data integrity (no lost metrics)
