### ISSUE TITLE
Embed zoneinfo into Windows builds of Telegraf

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7549]
### Proposal:

When Go 1.15 is released we can use the technique described here to embed the zoneinfo into the Windows build of Telegraf.

https://tip.golang.org/doc/go1.15#time/tzdata

### Current behavior:

Must include zoneinfo.zip separately.

### Desired behavior:

Just works even on Windows.

**Comment by powersj** [comment]
Fixed in https://github.com/influxdata/telegraf/pull/10377
