### ISSUE TITLE
Boomerang service input plugin

### ISSUE THREAD

**Issue by tuupola** [influxdata/telegraf#755]
I am currently running [Boomcatch](http://cruft.io/posts/introducing-boomcatch/) which receives input from [Boomerang](https://github.com/lognormal/boomerang) and converts it to statsd protocol which in turn is fed to Telegraf.  Having a dedicated Boomerang service input plugin would be great. Less moving parts.

This actually can be just general query string / `application/x-www-form-urlencoded` endpoint which answers to `GET` and `POST` requests.

**Comment by rschoessler** [comment]
@tuupola I am trying to accomplish the same thing you are/were doing with this post:

`boomerang` -> `boomcatch (statsd)` -> `telegraf` -> `influxdb`

However, I'm having issues getting telegraf to receive/send anything other than `rt` (roundtrip) timings to influxdb.  However, I know that `boomcatch` is receiving and sending them.

My `boomcatch` command is simple:

`c:\>boomcatch --host localhost --port 8080 --maxSize 2048 --mapper statsd`

My telegraf config is also vanilla.

Any chance this jogs your memory and you have an idea on what I am missing?  Thanks in advance!

**Comment by tuupola** [comment]
@rschoessler It has been a while. I must honestly tell I do not remember anymore.

**Comment by sjwang90** [comment]
Due to the low requests and priority for a Boomerang input plugin I'm going to close this issue. 

If you would still like this plugin, please submit it as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf.
