### ISSUE TITLE
inputs.consul: established connections to consul HTTP endpoint keep piling up

### ISSUE THREAD

**Issue by kosfar** [influxdata/telegraf#7554]
### Relevant telegraf.conf:
```
[[inputs.consul]]
  address = "localhost:7500"
  scheme  = "http"
  [inputs.consul.tags]
    process_name = "consul_server_vault"
```

### System info:

Telegraf 1.11.1
Debian 9.11

### Steps to reproduce:
Enable the plugin. After some time, depending on your telegraf interval frequency, telegraf can no longer connect to consul HTTP port. Same stands for cli commands too:
```
# consul operator raft list-peers -http-addr 10.1.2.3:7500
Error getting peers: Failed to retrieve raft configuration: Get http://10.1.2.3:7500/v1/operator/raft/configuration: EOF
```

### Expected behavior:

Telegraf plugin is expected to keep working. 

### Actual behavior:

Telegraf plugin can no longer fetch metrics from Consul HTTP port and starts emitting EOF errors like above.

### Additional info:

I realized that telegraf was keeping connections open to HTTP consul endpoint and not closing them:
```
# ss -ntp | grep ":7500" | grep telegraf | wc -l
203
```

Consul has a limit on max http connections per client, and that can explain the EOFs.
https://www.consul.io/docs/agent/options.html#http_max_conns_per_client

After restarting telegraf, no more EOFs and consul HTTP socket gets responsive again.

A similar issue has been reported in https://github.com/hashicorp/consul/issues/2852

**Comment by danielnelson** [comment]
Are you using the reload functionality of Telegraf via SIGHUP?  If so, the fix would be to close the transport on plugin shutdown.

**Comment by kosfar** [comment]
Not sure I'm following, do you suggest adding some scheduled job that will reload telegraf every once in a while? What about defaulting to `DefaultNonPooledConfig` for client config as others have suggested? It seems to make more sense for cases like a telegraf plugin.

**Comment by danielnelson** [comment]
I'm wondering if we are leaking connections when Telegraf is reloaded using SIGHUP.  We aren't actually using the Consul library with `DefaultNonPooledConfig`, we are making HTTP requests directly.

I can put together a PR that closes the pool connections on reload, it is probably just best to do this and check if it solves the issue.

**Comment by kosfar** [comment]
Thanks, got it know, I don't think that it's Telegraf reload leaking connections though, for this issue at least. In my case, no SIGHUP was sent during the time that it takes Telegraf connections to reach consul's max HTTP connections limit.

**Comment by akrantz01** [comment]
This appears to have been fixed after one of the updates to the Consul library as I cannot reproduce it in 1.19.
