### ISSUE TITLE
JSON input losing precision on 64bit integers

### ISSUE THREAD

**Issue by nathanpegram** [influxdata/telegraf#7555]
### Relevant telegraf.conf:

```toml
   data_format = "json"
   tag_keys = ["DEVICEID"]
   json_time_key = "measuredDtm"
   json_time_format = "2006-01-02T15:04:05+00:00"

```

### System info:

telegraf 1.14 on ubuntu18.04

### Steps to reproduce:

I am using telegraf to consume json input format. I have a tag key set to transform DEVICEID into an influxdb tag. The problem is that the tag ends up with truncated precision before is becomes a string.

### Expected behavior:

source json which contains: `...,"DEVICEID":2882429806056571124,...` should yield a metric with tag of DEVICEID=2882429806056571124.

### Actual behavior:

source json which contains: `...,"DEVICEID":2882429806056571124,...`  actually yields a tag of DEVICEID=2882429806056571000. Note the zeroes in the least significant digits.

**Comment by nathanpegram** [comment]
It looks like the problem is in the go encoding/json library, json.unmarshal. I think all json numbers are parsed into float64.

**Comment by danielnelson** [comment]
It is possible to optionally parse them as a json.Number, but it isn't a type we support in the Telegraf metric.  It's possible we could expose an option to select if the value should be converted to an int64, uint64, float64.

**Comment by nathanpegram** [comment]
Because I am using it as a tag, I ultimately want it parsed into a string.

**Comment by nathanpegram** [comment]
But in general, I could see wanting to parse signed 64 bit integers as well since they are supported by influx. I think it would make sense to use whatever options are available in the json decoding to preserve information and then parse into influx compatible formats within parsers/json/parser.go. This would allow for placing priority on parsing to string without loss for keys that have been flagged as tags or string_fields.

**Comment by atxviking** [comment]
Wondering if this is causing a loss of precision regarding timestamps as well?
Ran a local test and noticed the millisecond precision was dropped. Might not be related, and is very probable I've missed something. 

Tested via the following command:
`./telegraf --config jsonfile.conf --test`

jsonfile.conf:

```toml
# Reload and gather from file[s] on telegraf's interval.
[[inputs.file]]
  files = ["output.json"]

  data_format = "json"
  json_strict = true
  tag_keys = ["Path", "TimeStamp"]
  json_name_key = "Path"
  json_time_key = "TimeStamp"
  json_time_format = "unix_ms"
```

output.json:

```json
[
    {
        "TimeStamp": "1590009582002",
        "Path": "processor_time",
        "Value": 10.656527371660751
    },
    {
        "TimeStamp": "1590009582002",
        "Path": "memory_committed_bytes",
        "Value": 79.157851910953838
    }
]
```

Results (truncated slightly to highlight the timestamp value):

```sh
Starting Telegraf 
> processor_time,Value=10.65652737166075 1590009582000000000
> memory_committed_bytes,Value=79.15785191095384 1590009582000000000
```

The timestamp that was expected:  `1590009582002000000`

**Comment by danielnelson** [comment]
That is probably rounded due to the agent `precision` setting:
```toml
[agent]
  precision = "1s"
```

**Comment by danielnelson** [comment]
BTW, you can check if that is the case by setting `precision = "1ms" in the agent.  This takes effect across all of Telegraf but I'm planning to make it configurable per plugin in 1.15.

**Comment by atxviking** [comment]
That was the issue, aka my fault. Thanks for the quick response, and that would be a really nice addition to 1.15

**Comment by nathanpegram** [comment]
@danielnelson is there any fix for this on the horizon? Alternatively can you recommend a workaround or a strategy that I could pursue for implementing a fix in a fork? I'm happy to work on the implementation, particularly if the direction has some endorsement and potential to make it's way back into the main line.

**Comment by sjwang90** [comment]
@nathanpegram Could you try seeing if setting your `"DEVICEID"`  as a `json_string_fields` doesn't lose the precision? Then converting it to a tag if is reported out as a field. 

The problem looks to be that it's being converted to a float64 and losing precision. As long as you skip the float step, this shouldn't be a problem. `json -> int64 -> string` or `json -> string`, just _not_ json -> float64 -> string

A valuable bug fix would possibly be around int64 and possibly adding a `json_int64_fields = []`. There might be further work we could do with the JSON parser for tags. 

@reimda @ssoroka

**Comment by danberg13** [comment]
Hey together, I'm having the same problem. 

Is there any bug fix or maybe somebody found by time a good workaround?

@sjwang90 How yo you suppose to skip the float step? Doesn't convert the JSON Plugin automatically the JSON Numbers to float fields?

Thanks for the help!

**Comment by sjwang90** [comment]
Would anyone be willing to see if the new [`json_v2` parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2) to see if you still lose granularity.

**Comment by danberg13** [comment]
Im suppose the new json_v2 doesn't lose granularity.  
Unfornutaly, I'm using docker compose where the newest version of telegraf (1.19) is still no aviable. 
With 1.18.3 im determined to use the old json input right? 
Thank you!

**Comment by sjwang90** [comment]
@danberg13 The 1.19 release came out today with the [new JSON_v2 parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2). 

I am trying with @nathanpegram above and altering the type and am not getting necessarily what you'd expect. Try it out and if this issue still exists we can figure out how to address it in this new parser. 

```toml
        [[inputs.file.json_v2.field]]
            path = "fields.json.#.DEVICEID"
            rename = "DEVICEID"
            type = "int"
```

`type = "int"`
Input: `"DEVICEID": 2882429806056571124`
Output: `DEVICEID=2882429806056570880i`

`type = "float"`
Input: `"DEVICEID": 2882429806056571124`
Output: `DEVICEID=2882429806056571000`

`type = "string"`
Input: `"DEVICEID": 2882429806056571124`
Output: `DEVICEID="2.882429806056571e+18"`

**Comment by danberg13** [comment]
@sjwang90 @nathanpegram I tried the new JSON_v2 Parser out with the new dockerimage (version 1.19.0-alpine).

My telegraf.conf file:
```
> [[inputs.mqtt_consumer]]
> data_format = "json_v2"
> [[inputs.mqtt_consumer.json_v2]]
>  [[inputs.mqtt_consumer.json_v2.field]]
>    path = "bsEui"
>    rename = "bsEui"
>    type = "uint"
> 
```

Type: `"float"`
Input: For example `8121069193333309404 `or `8121069193333309389 `etc.. (last 4 numbers are changing)
Output:  `8121069193333309000`

Type: `"int"/"uint"`
Input: For example `8121069193333309404` or `8121069193333309389` etc.. (last 4 numbers are changing)
Output: `8121069193333309440`

Seems to be kind of weird. May you have a idea where is the problem. Thank you!

**Comment by akrantz01** [comment]
It seems that deserializing anything greater than `2^53 - 1` can cause precision to be lost since that is the max significant digits a `float64` can store. Go defaults to using a `float64` when deserializing into an interface, which is why this appears in `json` and `json_v2`. 

According to golang/go#12409, the recommended way to deserialize larger numbers from JSON is to go directly into an `int64` or use [`json.Number`](https://pkg.go.dev/encoding/json#Number).

https://play.golang.org/p/5wlIRHJvRcA

**Comment by danberg13** [comment]
Thanks @akrantz01.
After a few tests with the new JSON_v2 Parser i still get the same results as @sjwang90:
`type = "float"`
Input: `8141069193333309389 `
Output: `8141069193333309000`

`type = "uint"`
Input: `8141069193333309389 `
Output: `8141069193333309440` -> maybe a rounding Problem? 

`type = "string"`
Input: `8141069193333309389 `
Output: `8.121069193333309e+18` 

The last thee bytes aren't correct i think.  Isn't `type = "uint"` direcctly using int64 ? For me as Telegraf user what is the strategy to solve this problem? I'm using telegraf with influxdb and grafana and need the exact numbers. Thanks!

**Comment by danberg13** [comment]
Hey, is there any fix for this on the horizon? I could open a new issue for this problem. Thanks for alle the work!

**Comment by sjwang90** [comment]
@danberg13 No need to open another issue, this one has been fine. We'll add this to our backlog to work on.
