### ISSUE TITLE
Tag value cannot end with \

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7558]
This can be tried just by using Chronograf or any other means to write points (so is probably related to InfluxDB and not with telegraf)

### System info:
OS: Windows 10
InfluxDB: 1.8

### Steps to reproduce:
Just try to write the following points
```
#this does not work (ends with backslash)
Test, Tag1=C:\\,Tag2=Something Field1=10
#this works (ends with space)
Test,Tag1=C:\\\ ,Tag2=Something Field1=10
```

### Expected behavior:

being able to write tags that end with "\\"

### Actual behavior:

A point with a tag that ends with "\\" cannot be written (a path could end with the backslash in windows), but other escaped chars are valid (ie: space).
The error is: _invalid tag format_

### Additional info:
I'm not sure this is a telegraf related problem, it might be related to InfluxDB itself

**Comment by danielnelson** [comment]
This is a known limitation of InfluxDB Line Protocol: https://github.com/influxdata/influxdb/issues/6154.  I'm not sure when it will be addressed, but probably not in the near term.

It may be best to run paths through the `strings` or the upcoming `filepath` converter and switch to forward slash.

**Comment by Trovalo** [comment]
thanks, that looks like a nice workaround, I was thinking about appending a space the end of the string in order to keep the path as is and also have valid line protocol value

**Comment by danielnelson** [comment]
Maybe it would make sense to apply one of these workarounds automatically.  Perhaps, stripping trailing slashes would look better? `C:\` -> `C:`?

Adding a space works as well, I just wonder if it will cause confusion since it is difficult to notice the space.

**Comment by Trovalo** [comment]
I did something like that in the SQL Server input plugin (for the new queries), but it's not that easy to remove all the trailing "\\" (at least using TSQL) and as of now only the last one is removed (I see no way for a path to end with a double backslash... but you never know)  therefore it's probably easier and also safer to just add a space as trailing char if the string end with "\\". 

This of course is just one case, in general it might just be better to remove the trailing char

**Comment by danielnelson** [comment]
I think if we add a space it might be confusing, you might not notice it exists and once you do you need to figure out how to escape it in queries.  So I think we should either strip the `\` or replace it with an underscore.

**Comment by Trovalo** [comment]
As of now, in the SQL Server plugin, the trailing ```\``` will be removed from the string

**Comment by danielnelson** [comment]
I ended up stripping the trailing `\` in #7652.
