### ISSUE TITLE
Output Connection retries

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#756]
Telegraf may want to continue retrying to connect to unreachable output endpoints on startup.
This timeout should at least be extended, and it may even be better to simply continuously retry.

**Comment by zstyblik** [comment]
@sparrc is this going to be true for all outputs, resp. including Kafka output?

**Comment by sparrc** [comment]
yes, any change would have to be true for all outputs

**Comment by zstyblik** [comment]
Cool. Thanks.

**Comment by sparrc** [comment]
this is already done
