### ISSUE TITLE
Feature request: new input to monitor SaltStack 

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#7560]
### Proposal:
Adding an input to monitor SaltStack (master and minion) 

### Current behavior:
No existing input

### Desired behavior:
Add the monitoring of SaltStack via test.ping and test.version in a first step to allow monitoring of minions status and version. 

### Use case: 
- Allow to have the status of all salt minions (up or down)
- Allow to monitor the versions of all minion to keep them updated

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you yet. It does not look like we have had much interest in adding this over the last couple of years. I am going to go ahead and close this, but if you or others who come across this want to contribute please feel free to do so.

Thanks!
