### ISSUE TITLE
Filling Sparse Metrics

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#757]
This would likely be a feature of a generic TCP & UDP listener input plugin.

Sparse Metrics are a common use case where bandwidth or power (or both) are at a premium. In an effort to reduce the transmit power needs, or to reduce traffic over the wire, devices only report metrics when the value changes. For example, imagine a sensor that monitors whether a door is open. We open the door at noon and it stays open until 1:15 p.m., when the door is closed again. The sensor reports every 10 minutes. 

InfluxDB assumes the series would look like this (pseudo-line protocol):

door status=closed 11:50
door status=open 12:00
door status=open 12:10
door status=open 12:20
door status=open 12:30
door status=open 12:40
door status=open 12:50
door status=open 13:00
door status=open 13:10
door status=closed 13:20

When the customer actually wants the points to be like this:

door status=closed 11:50
door status=open 12:00
door status=closed 13:20

**Comment by danielnelson** [comment]
Merging with #3388
