### ISSUE TITLE
Telegraf service crush after installing Windows updates

### ISSUE THREAD

**Issue by anikas95** [influxdata/telegraf#7577]
### Relevant telegraf.conf:
Telegraf ver. 1.12, 1.14

### System info:
Target OS: Windows Server 2012 R2

### Steps to reproduce:
1. The following updates have been installed: KB2461484 (Version 1.315.1172, 1.315.1124, 1.315.1197, 1.315.1216, 1.315.1277). KB4556798, KB4556946, KB45556405, KB890830
2. After reboot of the server, main application is work, but service won't start

### Expected behavior:

Service started after server reboot

### Actual behavior:
Service doesn't start. At the same time, the program itself continues to work if you run the .exe file.
When trying to start the service itself, it instantly goes into "Stopped" mode.

### Additional info:
To fix this problem, the following steps were taken:

- Client upgrade from version 1.12 to 1.14
- Starting a service from a local administrator account
- Checking endpoint in the configuration file

The result is same. I would be grateful for a hint in a possible solution to the problem. Thanks!

**Comment by pcaifi** [comment]
There are these lines:
https://github.com/influxdata/telegraf/blob/f91d0833fb0c9240ec0d0049625f7ab7d27d7376/etc/telegraf_windows.conf#L67
https://github.com/influxdata/telegraf/blob/f91d0833fb0c9240ec0d0049625f7ab7d27d7376/etc/telegraf_windows.conf#L74
https://github.com/influxdata/telegraf/blob/f91d0833fb0c9240ec0d0049625f7ab7d27d7376/etc/telegraf_windows.conf#L78

Will it help to see what is going on?

**Comment by pcaifi** [comment]
Also some info you can find in events

**Comment by sjwang90** [comment]
@anikas95  have you had a chance to take a look at @ghost's suggestions?
