### ISSUE TITLE
Add sequence tag to Kapacitor node measurement fields 

### ISSUE THREAD

**Issue by MaksimPuzyrkov** [influxdata/telegraf#7580]
## Feature Request
It is difficult to display Kapacitor task nodes on dashboard in the ordering that will follow node position in the TICKscript. Node name includes numeric value indicating position, but with most dashboarding solutions it is not possible to correctly sort by this field at all or without implementing overhead queries and/or regex extractors.

### Proposal:
Add additional tag to kapacitor_nodes measurement to indicate a node position in a sequence. This can be achieved by extracting node position from node name and store as sequence tag.
This will help to display nodes health information in a table or create diagram following node positions in a Kapacitor tasks.

### Current behavior:
Kapacitor input plugin provides nodes measurement with default tags:
- host=hostname.local
- task=sys-stats
- type=stream
- kind=http_out
- node=http_out3

### Desired behavior:
Include `sequence` tag to plugin output:
- host=hostname.local
- task=sys-stats
- type=stream
- kind=http_out
- node=http_out3
- *sequence=3*

### Use case: 
Display node health information on dashboards for TICKscript development and quick analysis.
- List nodes in a table sorted in a same order as nodes executed
- Filter and display only entry and out points to help to identify inbound and outbound problems
- Show data flow diagrams as a diagram where all nodes connected in correct order

**Comment by danielnelson** [comment]
I think this would be best done in Kapacitor, so that we can utilize an already split value in Telegraf:
```diff
  {
      "067d801e-48de-4fec-98fe-d6691d3db1fe": {
          "name": "nodes",
          "tags": {
              "cluster_id": "aaa1cb78-8277-4886-a8ea-4706bca20842",
              "host": "localhost",
              "kind": "sum",
              "node": "sum5",
+             "sequence": "5",
              "server_id": "81e38258-5f18-4201-8d47-db603bfceeff",
              "task": "derivative-test",
              "type": "stream"
          },
          "values": {
              "avg_exec_time_ns": "0s"
          }
      },
  }
```

If you agree, can you open an issue on the Kapacitor issue tracker?

As a workaround you should be able to do this with the `regex` processor.  Untested, but should look something like:
```toml
[[processors.regex]]
  namepass = ["kapacitor"]

  [[processors.regex.tags]]
    key = "node"
    pattern = "^\\w+(\\d+)$"
    replacement = "${1}"
    result_key = "sequence"
```

**Comment by MaksimPuzyrkov** [comment]
> I think this would be best done in Kapacitor, so that we can utilize an already split value in Telegraf:
> <...>
> If you agree, can you open an issue on the Kapacitor issue tracker?

influxdata/kapacitor#2348

> As a workaround you should be able to do this with the `regex` processor. Untested, but should look something like:

Thank you for the suggestion @danielnelson 
Only small change needed in `namepass` to make it woking:
```diff
[[processors.regex]]
-  namepass = ["kapacitor"]
+  namepass = ["kapacitor_nodes"]

  [[processors.regex.tags]]
    key = "node"
    pattern = "^\\w+(\\d+)$"
    replacement = "${1}"
    result_key = "sequence"
```
