### ISSUE TITLE
fatal error: concurrent map writes with MQTT plugin

### ISSUE THREAD

**Issue by phoenix147** [influxdata/telegraf#7581]
Hi!

I'm using testing Telegraf with the mqtt plugin and the latest InfluxDB 2.0 beta.
It works fine for several ours, but after that it crashes with "fatal error: concurrent map writes"
It seems related to the MQTT Plugin and also occurs often after it has some timeouts writing to influxdb, but not always

### Relevant telegraf.conf:
```
[agent]
  omit_hostname = true

[[outputs.influxdb_v2]]
  urls = ["http://localhost:9999"]

  ## Token for authentication.
  token = "token omitted"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "development"

  ## Destination bucket to write into.
  bucket = "stations"

[[processors.regex]]
  namepass = ["mqtt_consumer"]

  [[processors.regex.tags]]
    key = "topic"
    pattern = '^(\d+)\/(\d+)\/(\w+)$'
    replacement = "${1}"
    result_key = "station"
  [[processors.regex.tags]]
    key = "topic"
    pattern = '^(\d+)\/(\d+)\/(\w+)$'
    replacement = "${2}"
    result_key = "sensor"
  [[processors.regex.tags]]
    key = "topic"
    pattern = '^(\d+)\/(\d+)\/(\w+)$'
    replacement = "${3}"
    result_key = "measurement"
# station topic
  [[processors.regex.tags]]
    key = "topic"
    pattern = '^(\d+)\/(\w+)$'
    replacement = "${1}"
    result_key = "station"
  [[processors.regex.tags]]
    key = "topic"
    pattern = '^(\d+)\/(\w+)$'
    replacement = "${2}"
    result_key = "measurement"

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]

  ## Topics that will be subscribed to.
  topics = [
    "#",
  ]
  topic_tag = "topic"
  data_format = "json"
  json_time_key = "ts"
  json_time_format = "2006-01-02T15:04:05Z07:00"

```

### System info:

Telegraf Version: 1.14.3
InfluxDB Version: 2.0beta 10
OS: Ubuntu 18.04.3

### Steps to reproduce:

1. Start InfluxDB and Telegraf
2. Wait for several hours

### Expected behavior:

Telegraf runs until stopped

### Actual behavior:

Telegraf crashes (see log)

### Additional info:
[telegraf.log](https://github.com/influxdata/telegraf/files/4681064/telegraf.log)

**Comment by danielnelson** [comment]
@phoenix147 I'm having a hard time figuring out why this is occuring, would you be able to run Telegraf with `debug` enabled in the agent config and attaching an updated logfile around the point in time that the crash occurs?
```
[agent]
  debug = true
```

**Comment by phoenix147** [comment]
@danielnelson 
I've started telegraf with debugging enabled. Lets see when the crash occurs..

An easy fix would be to wrap the messages map with a mutex at https://github.com/influxdata/telegraf/blob/063c61f7aa9ff9b98b451868fb8ed6dc28650e39/plugins/inputs/mqtt_consumer/mqtt_consumer.go#L267 and https://github.com/influxdata/telegraf/blob/063c61f7aa9ff9b98b451868fb8ed6dc28650e39/plugins/inputs/mqtt_consumer/mqtt_consumer.go#L293
but i'm not sure if the performance penalty wouldn't be too high

**Comment by danielnelson** [comment]
Thanks, slapping a mutex in is a possibility but I'd like to understand how it is running concurrently as there might be other issues.

**Comment by phoenix147** [comment]
I've attached the log file of the last crash.
I've noticed, that the influxdb crashed and there was no connection for several hours (i still have to investigate this issue, but since influxdb 2.0 is still in beta it is to be expected), however, the buffer had 1000 messages in it.
After i started influxdb again and the data was written in the db, the concurrent map writes occured, so i expect this has something to do with large writes from the buffer

[telegraf.log](https://github.com/influxdata/telegraf/files/4856130/telegraf.log)

**Comment by onlypankajsharma** [comment]
@phoenix147 I am also facing almost same issue.  
Issue #7860.
How did you log fatal error in telegraf.log? 
Even after adding "[agent]   debug = true" I am not able to write fatal error.

**Comment by phoenix147** [comment]
@onlypankajsharma 
Maybe you're face a different error, i got the fatal error even without debugging enabled

you should provide a log around the time this is happening

**Comment by onlypankajsharma** [comment]
@phoenix147 Last message I got in logs: 
"2020-07-16T18:05:41Z D! [outputs.influxdb] Wrote batch of 1000 metrics in 84.0037ms"
After that Telegraf is shutting down abruptly. I am not able to write fatal error in logs. Somehow I managed to capture error from CLI.
![FatalErr](https://user-images.githubusercontent.com/68557605/87973152-b4ed6600-cae5-11ea-9c3f-8a1de5c71377.jpg)

**Comment by ssoroka** [comment]
Looking at the plugin from the perspective of #7860, it seems like it might be related to reconnects. It seems problematic that the m.messages map is recreated on reconnect, _while_ it's potentially in use. moving that to an Init function might be enough to resolve the problem, but I'd need further testing on that.
