### ISSUE TITLE
Delay processing input

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#7582]
## Feature Request

In the k8s cluster environment, deploy telegraf to monitor the service target program through the sidecar method. When the target service (such as rabbitmq, kibana) is not ready, we do not want telegraf to access and affect it. Given that this scenario requires telegraf delay Take a period of time to collect monitoring data.

### Current behavior:
In a k8s cluster environment, deploying telegraf in sidecar mode to monitor the service target program. When the target service (such as rabbitmq, kibana) is not ready, telegraf accessing the service to obtain monitoring data often affects the start of the program.

### Desired behavior:
Delay a period of time before performing the acquisition task

**Comment by danielnelson** [comment]
If we implemented https://github.com/influxdata/telegraf/issues/3723 would it be enough to solve your issue?  Perhaps it could be combined with starting the container with a sleep before launching Telegraf.

**Comment by fcddk** [comment]
It only delays the execution of runinput func, and does not affect other parts of the function (such as output only has no monitoring data during this time)

**Comment by fcddk** [comment]
https://github.com/fcddk/telegraf/commit/010d438e20e164eb3ec3df10537992f2d33d430f

**Comment by fcddk** [comment]
I found this to be beneficial during the practice test. If you do n’t want such a function, ignoring the delay will not affect the functions already available in telegraf itself.

**Comment by danielnelson** [comment]
I don't think we would want to add this functionality in Telegraf, better to delay before starting the process than add in any new configuration.
