### ISSUE TITLE
InfluxDB input to Prometheus summary aggregator

### ISSUE THREAD

**Issue by leetreveil** [influxdata/telegraf#7586]
## Feature Request

There's currently no good way to aggregate input from influx, and generate a proper OpenMetrics [summary](https://www.robustperception.io/how-does-a-prometheus-summary-work) type with the prometheus output.

You can get there somewhat with the [basicstats](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/basicstats) aggregator using `count` & `sum` however the counter does not accumulate across resets making it inappropriate for something that should [monotonically increase](https://prometheus.io/docs/concepts/metric_types/#counter).

It looks like the [histogram](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/histogram) aggregator supports cumulative histograms so maybe we could get something like that for summaries too?

### Proposal:

Build a new aggregator that supports proper prometheus summaries from arbitrary inputs (influx etc).

**Comment by danielnelson** [comment]
related #6440

**Comment by powersj** [comment]
@leetreveil is this something you are still interested in?
