### ISSUE TITLE
Add 'FileVersion' property to Windows executable

### ISSUE THREAD

**Issue by MartynKeigher** [influxdata/telegraf#7587]
## Feature Request

I would like the FileVersion property to be populated, in the Windows agent.

### Current behavior:
When I run the following from Powershell, I get a lot of info about the telegraf.exe file, but NOT the version.
`Get-Item -Path 'C:\Program Files\Telegraf\telegraf.exe' | Select-Object *`

### Desired behavior:
`(Get-Item -Path 'C:\Program Files\Telegraf\telegraf.exe').FileVersion` (or simlar), retrieves the version number.

### Use case: 
Currently looking to build out automation to install and upgrade 100's of Telegraf agents across my environments, and if I can obtain the file version, I can then compare it to the current available version to then either exit, OR...  kick off an upgrade process.

Check for current available version:
`(((iwr -uri 'https://api.github.com/repos/influxdata/telegraf/releases/latest').Content | ConvertFrom-Json).tag_name).substring(1);`

Check for currently installed version of Telegraf:
`(Get-Item -Path 'C:\Program Files\Telegraf\telegraf.exe').FileVersion`

Thanks! 

://mk

**Comment by danielnelson** [comment]
Let's merge this issue with #3171
