### ISSUE TITLE
The default conf "[[outputs.influxdb]]" confuse

### ISSUE THREAD

**Issue by chpiter** [influxdata/telegraf#7589]
### Default /etc/telegraf/telegraf.conf :

```toml
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  # urls = ["http://127.0.0.1:8086"]
```

### Telegraf info:
telegraf-1.14.3-1.x86_64 on CentOS Linux release 7.4.1708
Then I write my nginx.conf in /etc/telegraf/telegraf.d
```toml
[[outputs.influxdb]]
  urls = ["http://10.173.34.200:8086"]
  database = "telegraf"
```
and I restart telegraf 
```bash
systemctl restart telegraf.service
systemctl status telegraf.service
```
I got the error
```
[outputs.influxdb] When writing to [http://localhost:8086]: Post http://localhost:8086/write?db=telegraf: dial tcp [::1]:8086: connect: connection refused
```

So, I have to notes the  [[outputs.influxdb]] in /etc/telegraf/telegraf.conf like thie 
```toml
# [[outputs.influxdb]]
```

**Comment by danielnelson** [comment]
This is working as intended, but you may be interested in watching #5887

**Comment by toastbrotch** [comment]
hm. if this is "working as intended" then its broken by design! it seems to be impossible to override that default of telegraf.conf. so that telegraf.d is not working as it implies.
