### ISSUE TITLE
Input Internal fo the SQL Server Input Plugin 

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7590]
## Feature Request

Add the internal input to the SQL Server plugin.
This is implemented in other plugins like the [github](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/github) and [influxdb_listener](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/influxdb_listener/influxdb_listener.go) input plugins. (I found also other by searching for "selfstat.Register" in the input folder)

note that I still have no clue if what I'm proposing is actually possible
### Proposal:
The idea is to have a higher level monitoring of the plugin itself by gathering the following data for each SQL instance and query (in this case query == measurement)
- Query duration
- Num of points gathered
- {probaly there are other useful data but I don't even know what's available/possible}

This will provide additional information about how the plugin is performing and allows for some fine-tuning of the telegraf configuration (maybe by running a query with a lower frequency)

I imagine the output as something like:
| measurement        | sql_instance   | telegraf_query      | query_duration_ms | gathered_rows |
|--------------------|----------------|---------------------|-------------------|---------------|
| internal_sqlserver | QDLP03\SQL2017 | PerformanceCounters | 94                | 247           |
| internal_sqlserver | QDLP03\SQL2017 | DatabaseIO          | 20                | 10            |
| internal_sqlserver | QDLP03\SQL2012 | PerformanceCounters | 89                | 219           |

### Current behavior:
There is no internal plugin for sqlserver input

### Desired behavior:
having some data about how the plugin itself is performing

### Use case: 
Monitoring the Sql Server Input itself

Any help/suggestion is appreciated

**Comment by danielnelson** [comment]
Makes sense to me, @denzilribeiro any thoughts?

**Comment by denzilribeiro** [comment]
Is a good idea but have to think through implementation not sure if it is same like the other plugins you mentioned.
What you are proposing is capturing  capture duration for each query run - that could be embedded but should be under a debug flag/option, I wouldn't want additional overhead by default - then questionis whether you capture it on the client ( telegraf) or when running the query on the DB itself. I would say in the client telegraf code as ideally would have to store it as a different measure .

**Comment by Trovalo** [comment]
The [Input internal](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal) is a separate input plugin. When enabled it stores data about other inputs/outputs, only if it has been implemented in the inputs/outputs themselves. (so far few plugins have an implementation of it)

Therefore the calculation will be made by telegraf itself, without querying the database, and as a standard, a new measurement called internal_<InputName> is created

**Comment by denzilribeiro** [comment]
That would be cool :) @danielnelson  will know more about that than I do

**Comment by danielnelson** [comment]
Yeah, we wouldn't modify any queries in the sqlserver input, and in fact we can't determine if the internal plugin is enabled or not from there.

**Comment by Trovalo** [comment]
Strictly speaking, it's not the same but I'd consider this one closed by PR #8544 which addressed the most important point, which is monitoring if the data gathering is going smoothly.
Also from the conversation in that PR looks like some of the ideas I proposed here are not possible to implement with the internal plugin (like fetching data by single connection/query).

Thanks @coquagli for implement the sqlserver_telegraf_health metrics
