### ISSUE TITLE
execd input - GO related error on Windows

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7591]
### Relevant telegraf.conf:
```toml
[[inputs.execd]]
  command = ['C:\Users\gluisotto\Desktop\test Telegraf\StartPrintrandom.bat']
  signal = "none"
  restart_delay = "10s"
  data_format = "influx"

[[outputs.file]]
  files = ['C:\Users\gluisotto\Desktop\test Telegraf\execd_output.out']
  data_format = "influx"
```

file: StartPrintrandom.bat
```cmd
Powershell.exe -File "C:\Users\gluisotto\Desktop\test Telegraf\PrintRandom.ps1"
```

file: PrintRandom.ps1
```Powershell
$i = 0

DO {

	$a = Get-Random -Minimum 4 -Maximum 12
	Write-Host "execd_test,tag_1=testing wait_time_s=$a,loop_num=$i"

	$i++
	
	Start-Sleep -s $a

} While ($i –le 200)

```

### System info:
OS: Windows 10
Telegraf: custom build (last commit of master: f91d0833fb0c9240ec0d0049625f7ab7d27d7376)

### Steps to reproduce:
1. Create the needed scripts with the code above
- StartPrintrandom.bat → It's only purpose is to run the actual code
- PrintRandom.ps1 → generates some random data to test the execd input
2. let it run, from time to time it will give should give you an error

### Expected behavior:
it should work

### Actual behavior:
it gives the following error from time to time, the error looks GO related
```
2020-05-27T15:22:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2020-05-27T15:22:03Z I! Process [C:\Users\gluisotto\Desktop\test Telegraf\StartPrintrandom.bat] terminated: %!s(<nil>)
2020-05-27T15:22:03Z I! Restarting in 10s...
2020-05-27T15:22:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2020-05-27T15:22:13Z I! Starting process: [C:\Users\gluisotto\Desktop\test Telegraf\StartPrintrandom.bat]
2020-05-27T15:22:13Z E! [inputs.execd] Error in plugin: metric parse error: expected field at 2:56: "C:\\Users\\gluisotto\\Desktop\\test Telegraf>Powershell.exe"
2020-05-27T15:22:22Z D! [outputs.file] Wrote batch of 1 metrics in 0s
2020-05-27T15:22:22Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
```

### Additional info:

- The log is already with debug enabled
- a bat file is used to start the PowerShell script because passing the cmd command itself generates an error (path not found)

**Comment by danielnelson** [comment]
Do you need `@echo off` in the batch file?

**Comment by Trovalo** [comment]
I've found exactly when the issue happens.

adding ```@echo off``` solves the error just after the start of the script
> 2020-05-27T15:22:13Z E! [inputs.execd] Error in plugin: metric parse error: expected field at 2:56: "C:\\Users\\gluisotto\\Desktop\\test Telegraf>Powershell.exe"

The other error still occurs once the counter reaches its maximum and the script exits.
To check double check this I've edited the PS script as follows:
```Powershell
$i = 0
DO {
	$a = Get-Random -Minimum 4 -Maximum 12
	$outString= "execd_test,tag_1=testing wait_time_s=$a,loop_num=$i"

	Add-Content -Path "C:\Users\gluisotto\Desktop\test Telegraf\ps_output.txt" -Value $outString
	Write-Host $outString

	$i++
	Start-Sleep -s $a
} While ($i –le 10)
```
Note that the script itself appends the data to a file, this is useful to double-check data (PowerShell written file and telegraf file output).

The error occurs every x record, where x is the condition set in the _While loop_, therefore once the script exits telegraf throws the following error.
```
2020-05-28T08:40:17Z I! Process [C:\Users\gluisotto\Desktop\test Telegraf\StartPrintrandom.bat] terminated: %!s(<nil>)
2020-05-28T08:40:17Z I! Restarting in 10s...
```
I'm just not sure about the last part of the error ```!Process [C:\Users\gluisotto\Desktop\test Telegraf\StartPrintrandom.bat] terminated:``` so far it's clear, then there is ```%!s(<nil>)``` which tells me that a null object has been passed to a function which was not expected or something like that.

@danielnelson If all this makes sense to you the issue can be closed.

_PS:
In the future, I will prevent myself from opening (inexistent) issues at the end of the workday_

**Comment by danielnelson** [comment]
The execd input is expecting the subprocess to run forever, so we do want it to log if the process exits unexpectedly.  The error ought to be improved though, and we should never log Go values like nil.  There is a pull request open around this and I'll comment over there (#7424).

One thing I'm curious about though, why use the batch file at all instead of just calling powershell.exe directly?

**Comment by Trovalo** [comment]
I had to use a batch file to avoid a "path not found error", to me it looked like as if the whole command was passed as the path.

```Powershell.exe -File "C:\Users\gluisotto\Desktop\test Telegraf\PrintRandom.ps1"```

The error reported the above string, just toml escaped, I've tried to used both single and double quotes to specify the path but the error was the same.

I will edit this tomorrow with the actual "path not found" error
