### ISSUE TITLE
Be able to add the body's content as field with http_response

### ISSUE THREAD

**Issue by essobedo** [influxdata/telegraf#7595]
### Proposal:

The idea is to have a way to get the content of the body as field, this feature could be disabled by default to remain backward compatible.

### Current behavior:

There is no way to get the content of the body with the plugin http_response.

### Desired behavior:

Have the ability to get the content of the body by enabling the feature by configuration.

### Use case:

If you access to an http endpoint and the server return an error, it could be interesting to have more details about the failure to eventually troubleshoot. Knowing that generally speaking, those details are available from the body of the response, it could be very helpful to provide a way to get also the body of the response.

**Comment by essobedo** [comment]
Potential fix #7596

**Comment by essobedo** [comment]
@danielnelson Hi, could you please at least tell me if this feature request and the corresponding PR make sense to you or not? Thanks in advance

**Comment by danielnelson** [comment]
Commented on the PR
