### ISSUE TITLE
mongo metrics

### ISSUE THREAD

**Issue by idestis** [influxdata/telegraf#760]
`2016/02/26 12:54:57 not authorized on admin to execute command { serverStatus: 1, recordStats: 0 }`
mongodb plugin supports all versions of Mongo?

> Changed in version 3.0: serverStatus no longer outputs the workingSet, indexCounters, and recordStats sections.

**Comment by sparrc** [comment]
I'm not sure, @jipperinbham do you know about the supported version(s) of the mongodb plugin?

**Comment by sparrc** [comment]
fwiw, that error message doesn't sound like a version support issue, it sounds like your mongo admin user doesn't have proper authorizations?

**Comment by jipperinbham** [comment]
@sparrc is correct in that it is a user authorization issue. 

User roles have certainly changed between MongoDB versions, so for 3.0+, a good role for the user is [clusterMonitor](https://docs.mongodb.org/manual/reference/built-in-roles/#clusterMonitor).

**Comment by idestis** [comment]
yes, this role giving for us ability to use "serverStatus" command, but what about command "recordStats"?

**Comment by jipperinbham** [comment]
`recordStats` is a field that was part of the `serverStatus` result prior to 3.0.

**Comment by sparrc** [comment]
So what exactly needs to be fixed here? recordStats should be removed from the 3.0+ stats query?

**Comment by idestis** [comment]
I think yes. With mongo 3.0 or later i can't get metrics, because getting the error, error code you can look earlier, i've mentioned it in first post.

another way add switch between versions.

**Comment by sparrc** [comment]
grrrr seems like Mongo should have maintained backwards compatibility by just ignoring the recordStats field in 3.0 :see_no_evil:. I'm not sure the best solution yet, we probably need to add a version switch, unless we can query mongo for it's version.

**Comment by jipperinbham** [comment]
I'll see what changes if any have been made to [stat_types](https://github.com/mongodb/mongo-tools/blob/master/mongostat/stat_types.go) since last I worked on the plugin. They _usually_ try and account for deprecated fields but if not I'll see what can be done and offer up some possibilities.

**Comment by jipperinbham** [comment]
@idestis I'm not seeing anything that needs to be changed. I'm able to run telegraf against a 3.0.6 MongoDB without any issue. I also manually ran the below command without any issue:

```
set-561d99ee7572ff9045000084:PRIMARY> use admin
switched to db admin
set-561d99ee7572ff9045000084:PRIMARY> db.runCommand({"serverStatus": 1, "recordStats": 0})
```

**Comment by sparrc** [comment]
@idestis do you have anything else to add? I'm thinking of closing the issue because I'm not sure there is anything here for us to fix

**Comment by sparrc** [comment]
closing, please feel free to re-open in case there is still an issue here
