### ISSUE TITLE
vSphere CPU data out of order after upgrade

### ISSUE THREAD

**Issue by chench00** [influxdata/telegraf#7600]
### System info:

Telegraf v1.14.3
Ubuntu 18.04

### Steps to reproduce:

1. ...Upgrade CPU
2. ...Visualize data in Grafana
3. ...Drop measurement vsphere_host_cpu from influxdb
4. ...Restart telegraf and Influxdb

### Expected behavior:

Incoming CPU core count data to be in the correct order

### Actual behavior:

Incoming CPU core count data is out of order
### Additional info:

I am using Influxdb along with Telegraf and the vSphere Input Plugin to visualize data in Grafana and one of my graph keeps track of my CPU utilization. Recently I upgraded my host’s CPU to one with a bigger core count but now the legend is out of order:

![82820244-d4fb0300-9e6f-11ea-9782-9563b34bae08](https://user-images.githubusercontent.com/63960113/83311560-98b40380-a1dd-11ea-9c49-b09da2e3919e.png)

I have tried dropping the measurement responsible from the database (vsphere_host_cpu) and restarting both Influx and Telegraf but it still comes back unordered.

I opened an issue at Grafana but was told this was a database issue so I opened an issue with Influxdb but was told data is coming in unordered and there's nothing I can do. Perhaps someone here can help?

**Comment by danielnelson** [comment]
I believe this is: https://github.com/influxdata/influxdb/issues/3954.  Based on the final comment on that issue, you would need to use Flux to query the database.
