### ISSUE TITLE
Extend ntpq input plugin to retreive statistics from remote ntp servers

### ISSUE THREAD

**Issue by dimdin** [influxdata/telegraf#7606]
### Proposal:
Extend ntpq plugin to query a list of servers.
### Current behavior:
Currently, ntpq queries only the local host.
### Desired behavior:
Ntpq configuration must have a ntp server list.
The plugin must get statistics from all servers by calling "ntpq -p server" or "ntpq -pn server".
If there is no server list, it can use the current behavior i.e. call "ntpq -p"
### Use case: 
I have a lot of embedded devices that run ntp daemon but currently it is not practical or feasible to run telegraf on these devices.

**Comment by powersj** [comment]
next step: look at the open PR, take ownership and drive to merge
