### ISSUE TITLE
 [inputs.sflow] failed to start: unsupported network type:

### ISSUE THREAD

**Issue by operations999** [influxdata/telegraf#7607]
Hi,
I upgraded to latest version Starting Telegraf 1.14.3
But when I try to restart with tag and port 6343 i get this
2020-05-31T08:23:24Z E! [agent] Service for [inputs.sflow] failed to start: unsupported network type:
2020-05-31T08:23:24Z E! [telegraf] Error running agent: unsupported network type:

This tag is not supported?

**Comment by danielnelson** [comment]
It sounds like the `service_address` option is not in the expected format.  Can you show the configuration from your sflow plugin?

**Comment by operations999** [comment]
Tried all these three options one by one and it crash telegraf.

service_address = "udp://:6343"
service_address = "udp4://:6343"
service_address = "udp://127.0.0.1:6343"

**Comment by danielnelson** [comment]
I'm not able to reproduce:
```
$ cat telegraf.conf
[[inputs.sflow]]
  service_address = "udp://:6343"

[[outputs.file]]
$ ./telegraf --config telegraf.conf
2020-06-01T19:23:27Z I! Starting Telegraf v1.14.3
2020-06-01T19:23:27Z I! Loaded inputs: sflow
2020-06-01T19:23:27Z I! Loaded aggregators:
2020-06-01T19:23:27Z I! Loaded processors:
2020-06-01T19:23:27Z I! Loaded outputs: file
2020-06-01T19:23:27Z I! Tags enabled: host=loaner
2020-06-01T19:23:27Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"loaner", Flush Interval:10s
2020-06-01T19:23:27Z I! [inputs.sflow] Listening on udp://0.0.0.0:6343
```

Can you attach your actual configuration as a file?

**Comment by operations999** [comment]
Hello,
config file attached.
No matter which port i put it shows error 

[telegraf] Error running agent: listen udp :6343: bind: address already in use

netstat -tulnp
udp        0      0 0.0.0.0:6343            0.0.0.0:*                           21029/telegraf
Port is actually used by telegraf and it dont start.

**Comment by danielnelson** [comment]
Maybe the plugin is defined twice or Telegraf is running twice?  I don't see the sflow plugin enabled in your configuration at all.

**Comment by operations999** [comment]
Sorry I commented that to start telegraf or it will not start at all.
So my actual config is like this but telegraf do not start. But when I enable inputs.sflow


[[inputs.sflow]]
  ## Address to listen for sFlow packets.
  ##   example: service_address = "udp://:6343"
  ##            service_address = "udp4://:6343"
  ##            service_address = "udp6://:6343"
service_address = "udp4://:6343"

[root]#telegraf

2020-06-06T09:07:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
2020-06-06T09:07:14Z E! [agent] Service for [inputs.sflow] failed to start: listen udp4 :6343: bind: address already in use
2020-06-06T09:07:14Z E! [telegraf] Error running agent: listen udp4 :6343: bind: address already in use


There is only one service running and port is used by telegraf
tcp6       0      0 :::80                   :::*                    LISTEN      679/httpd
tcp6       0      0 :::8086                 :::*                    LISTEN      961/influxd
tcp6       0      0 :::22                   :::*                    LISTEN      678/sshd
tcp6       0      0 :::8888                 :::*                    LISTEN      680/chronograf
tcp6       0      0 :::3000                 :::*                    LISTEN      681/grafana-server
udp        0      0 0.0.0.0:6343            0.0.0.0:*                           14140/telegraf

[root]# ps aux | grep telegraf
telegraf 14140  2.1  0.5 603728 30204 ?        Ssl  11:04   0:00 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
root     14170  0.0  0.0   9092   672 pts/0    S+   11:04   0:00 grep --color=auto telegraf


[root]# telegraf -version
Telegraf 1.14.3 (git: HEAD 1b35d6c2)

Thanks
