### ISSUE TITLE
Can I rename the output measurment in influxb when using inputs.file json ?

### ISSUE THREAD

**Issue by Utopolis** [influxdata/telegraf#7609]
Hi, I would like to know if it is possible to rename the measurment name.
Unstead having all the data send in the time series "file", having "new_name".

Unstead
file,TAG1=TAG1_VALUE,FIELD1=FIELD1_VALUE
having
new_name,TAG1=TAG1_VALUE,FIELD1=FIELD1_VALUE

Thanks for the help !

**Comment by danielnelson** [comment]
You can use the `name_override` option on any input to change the measurement name:
```
[[inputs.file]]
  name_override = "new_name"
```
