### ISSUE TITLE
Telegraf Writes to InfluxDb have '1' timestamps

### ISSUE THREAD

**Issue by s1m0** [influxdata/telegraf#761]
telegraf v 0.10.4.1
InfluxDB v 0.9.6.1

Using the exec inputs, I send InfluxDB formatted data to telegraf to upload but it's taking out my timestamps and inserting '1'

[[inputs.exec]]
  command = "/usr/local/bin/IFDBServMon_lineoutput.sh"
  data_format = "influx"
  interval = "30s"

$>  telegraf -config /etc/telegraf/telegraf.conf -debug

<snip>
> Services,ServiceName=TA-1G,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.05,Rate=475.35,ResponseTime=1.08,ServiceTime=1.03 1456532100
> Services,ServiceName=TA-1V,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.02,Rate=74.7,ResponseTime=1.52,ServiceTime=1.5 1456532100
> Services,ServiceName=TC-EB,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.06,Rate=1607.417,ResponseTime=0.17,ServiceTime=0.11 1456532100
2016/02/27 00:16:10 Gathered metrics, (separate 30s interval), from exec in 166.706667ms
2016/02/27 00:16:10 Wrote 47 metrics to output influxdb in 5.355219ms

InfluxDB log with write tracing enabled:-

<snip>
>Services,ServiceName=TA-1G,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.05,Rate=475.35,ResponseTime=1.08,ServiceTime=1.03 1
Services,ServiceName=TA-1V,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.02,Rate=74.7,ResponseTime=1.52,ServiceTime=1.5 1
Services,ServiceName=TC-EB,host=vhlgnnfut001.wspan.net Failures=0,GapTime=0.06,Rate=1607.417,ResponseTime=0.17,ServiceTime=0.11 1
[http] 2016/02/27 00:16:10 127.0.0.1 - - [27/Feb/2016:00:16:10 +0000] POST /write?consistency=&db=telegraf&precision=s&rp= HTTP/1.1 204 0 - telegraf 4d97b9d9-dce7-11e5-814e-000000000000 4.714883ms

from influx shell:-
> select * from Services
name: Services
time            Failures        GapTime Rate            ResponseTime    ServiceName     ServiceTime     host
1000000000      0.02            0       97.767          0               C1-EB           0               vhlgnnfut001.wspan.net
1000000000      4.08            0       27.367          0.53            A3-1G           0.53            vhlgnnfut001.wspan.net
1000000000      0               0.06    1490.367        0.16            TC-EB           0.11            vhlgnnfut001.wspan.net
1000000000      0               0.02    464.933         0.98            TA-1G           0.96            vhlgnnfut001.wspan.net
1000000000      0               0.02    101.267         4.26            SP-1P           4.24            vhlgnnfut001.wspan.net
<snip>

**Comment by sparrc** [comment]
your timestamps need to be in nanoseconds, not seconds

**Comment by s1m0** [comment]
Configuration for the influxdb outputter specifies precision is seconds.

[[outputs.influxdb]]
  # The full HTTP or UDP endpoint URL for your InfluxDB instance.
  # Multiple urls can be specified but it is assumed that they are part of the same
  # cluster, this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://localhost:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "telegraf" # required
  # Precision of writes, valid values are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
  # Set the user agent for HTTP POSTs (can be useful for log differentiation)
  user_agent = "telegraf"
  # Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512

**Comment by sparrc** [comment]
That's precision of the stored data and for http writes. The data in your points needs to be in nanoseconds, just add 9 zeros on the end.
