### ISSUE TITLE
Field string concatenation

### ISSUE THREAD

**Issue by e0101528** [influxdata/telegraf#7610]
### Proposal: 
That a simple binary operator to conjoin fields by a simple string-like concatenation be implemented. Or that a simple concat() function be available.  

### Current behavior: 
No (apparent) mechanism for conjoining fields through simple string concatenation aggregation. 

### Desired behavior: 
E.g. 
select (a _ b ) as c    
OR 
Select concat(a,b) as c

### Use case: 
Merging fields into single fields to be handled by Grafana Logs panel would be useful. 
Simplifying data for presentation in table panels would also be helpful.

**Comment by danielnelson** [comment]
You should be able to use the `template` processor to concat fields to a tag, afterwards use the converter processor to convert back to field:
```
[[processors.template]]
  order = 1
  tag = "c"
  template = '{{ .Field "a" }}.{{ .Field "b" }}'

[[processors.converter]]
  order = 2
  [processors.converter.tags]
    string = ["c"]
```

In the future, another option will be #7194.
