### ISSUE TITLE
ip resolving in snmptrap input plugin

### ISSUE THREAD

**Issue by iiidddaaannn102** [influxdata/telegraf#7611]
Hello,
My Monitored Network has about 100 components or more that sends traps.
i exports the data from influxdb and send it to self service alert tool, that depends on component names.
Because it, I suggest to add an option that resolving the source ip address to dns name on the snmptrap input plugin.
just if the resolving is failed, it implement an ip address
thank you

**Comment by danielnelson** [comment]
We are working on a processor that can do this #7245.  Pull request is #7504
