### ISSUE TITLE
How To Add Global Tag Dynamically

### ISSUE THREAD

**Issue by SaranrajG01** [influxdata/telegraf#7612]
Hi,

We have installed Telegraf in our Servers across different environment like Prod/Non Prod/Testing etc., Each environment will have its own multiple tags. Currently we are looking on the option of utilizing Global Tags, but configuring Global Tags in each machine Configuration File will be a difficult step.

Instead is there a way whenever a data comes in from Telegraf to Influx DB, can we get the Hostname, we can update the Tags which we have from different DB Tables or from other source dynamically.

**Comment by danielnelson** [comment]
One common way to do this is to use [environment variables when setting the global tags]( https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#environment-variables), when you deploy the server you can add the variables to `/etc/default/telegraf`.  This will allow you to use the same configuration file across environments.

There isn't currently a way to lookup tags from a database in Telegraf.

You could potentially store the info in InfluxDB and do a join with Flux, though I'm not aware of anyone doing this.

**Comment by mertbakir** [comment]
I'm also interested in this. I've tried to seperate config files try to create common configs like Env: Prod, Env: Test, Env: Dev makes 3 different configs. Then, I tried to manage host~config relation using nodered and n8n.io. It wasn't an easy task and I felt like I'm overengineering.

If anyone has an elegant way to do this, please share.

**Comment by SaranrajG01** [comment]
Hi Daniel,

Thanks for your response, could you please share some reference URL for below option,

You could potentially store the info in InfluxDB and do a join with Flux, though I'm not aware of anyone doing this.

Variables can be used while provisioning new servers, however the current difficulty is updating tags on already installed Servers which is ~4K count with multiple environment tags and other tags which we need to update.

**Comment by danielnelson** [comment]
I think what would probably be the closest to what you are imagining is a new processor that does lookups and appends the tags to the metrics.  Something like this would be fairly straightforward now that we have added better support for async operation in the processors.  If we were going to work on something like this which source do you think would be the best to start with?  Perhaps postgres?

The Flux idea is something I haven't done myself, it is a bit of an exercise and I can't vouch for the results, but you would want to get started [here](https://docs.influxdata.com/flux/v0.65/introduction/).  You could also try the InfluxDBv2 beta.  I expect you would store a time series in InfluxDB that contains the host and what group it belongs to `hosts,host=example.org env="prod"`, and then use Flux to join the environment using the host tag.

**Comment by sasimohan** [comment]
@danielnelson  What do you mean by new processor? Could you please elaborate or share some document related to it. Up to my understanding new processor is some script where we assign some custom tags for each host and that processor will lookup those host and update the given tag adjacent to it when ever telegraf pushes the measurements to influxdb. Is my understanding right?

As you said Flux idea is something that you haven't tried also its a beta version. **Will it be advisable to try that approach in production setup?**

**Comment by danielnelson** [comment]
When I say "new processor" I mean we would need to write a new [processor plugin](https://github.com/influxdata/telegraf/blob/master/docs/AGGREGATORS_AND_PROCESSORS.md#processor) to handle this.  We don't have a ton of documentation on processor plugins, but essentially they run after the input plugins and can modify any metrics.  This hypothetical new plugin could lookup data in a database and add additional tags to metrics dynamically.

> As you said Flux idea is something that you haven't tried also its a beta version. Will it be advisable to try that approach in production setup?

I don't think it's high risk to try, but probably a better idea to try it out with a development server.  I think this is somewhat of an advanced task, so if its your first exposure to Flux it might be best to stick to the road more traveled (and tested).

**Comment by rvdheij** [comment]
I think it would really be very helpful when Telegraf could at least run a bash script during startup to set environment, similar to the EnvironmentFile that it reads from /etc/default/telegraf
But since we move running hosts from one system to the other, it would be even better when Telegraf would run something to gather the current global tags for each monitoring interval.

**Comment by srebhan** [comment]
PR #12809 adds a processor that can add tags from file(s). Does that solve your problem?
