### ISSUE TITLE
Prometheus plugin log

### ISSUE THREAD

**Issue by Lyr** [influxdata/telegraf#7623]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Without "int" type on data flow, the prometheus_client return no data, without any log, I guess it could be very usefull to have some trace about this behavior.

### Current behavior:

An input conf like this : 
```
[[inputs.tail]]
  files = ["./data.sample"]
  data_format = "grok"
  grok_patterns = ['^%{LOGLEVEL:logLevel}\s*%{DATE:date} %{TIME:time}\s*%{NOTSPACE:fieldName}\s*Value = %{INT:value}$']
 
```
With output like this :
```
[[outputs.prometheus_client]]
  listen = ":9273"
```

Grok pattern match with lines in file, but no data are provided on page http://loclahost:9273/metrics and no log about what and why happens

### Desired behavior:

In the same configuration seen before, just one log line could be very usefull, something like :

`
2020-06-03T05:05:00Z D! [outputs.prometheus_client] No integer in the data
`
### Use case: 

Debuging this situation/configuration, burns couple of hours, but with this logs, I spend a couple of minutes I guess.

**Comment by danielnelson** [comment]
Sorry about the confusion debugging. I think that we should avoid a log message here as it is usually desired behavior to have the string fields dropped with this output. I've adding some better documentation about this behavior that I hope will improve the situation.  Can you take a look at #7644?

**Comment by Lyr** [comment]
Thanks for your feedback. Yes #7644 will be a good solution.

**Comment by Lyr** [comment]
I close this.
