### ISSUE TITLE
cannot set config file permissions, owner, group

### ISSUE THREAD

**Issue by stderr-to-devnull** [influxdata/telegraf#7628]
Can't use `File` resource referencing the same file name because I get a "Duplicate declaration" error in Puppet.
Can't specify `owner`, `group` and `mode` within this plugin's configuration.

**Comment by danielnelson** [comment]
Sorry, I don't understand.  Fill out the bug issue template all sections and I'll see if I can help, or ask over at the [InfluxData Community](https://community.influxdata.com) site.
