### ISSUE TITLE
add tomcat Plugin

### ISSUE THREAD

**Issue by arthtux** [influxdata/telegraf#763]
Plugin to collect datas /manager/status

**Comment by haowells** [comment]
need jmx plugin also

**Comment by sparrc** [comment]
@haowells we have the jolokia plugin: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia/jolokia.go which is the only way to access jmx in a non-Java environment, afaik

**Comment by arthtux** [comment]
@haowells example of /manager/status?XML=true
<img width="882" alt="tomcat-manager status xml true" src="https://cloud.githubusercontent.com/assets/5318898/13482600/23cdc858-e0bc-11e5-9054-e49ee866c11d.png">

**Comment by puckpuck** [comment]
A little late, but these metrics are all available via the jolokia agent deployed to Tomcat.

Once deployed, this URL: `http://<myserver>/jolokia/read/java.lang:name=*,type=MemoryPool/Usage`

will return what all the memory pool information above.  Thread and request info is also available.  `http://<myserver>/jolokia/list` will return all available metrics in JSON format.  This list can be quite large even on simple websites.

**Comment by xulz** [comment]
Fetch the Tomcat ThreadPool information in following way did not work, any ideas?

update with below config in telegraf.conf
`
[[inputs.jolokia]]
# other metrics works
  [[inputs.jolokia.metrics]]
    name = "threadpool_usage"
    mbean  = "Catalina:type=ThreadPool,name=%22http-bio-8080%22"
    attribute = "currentThreadCount,currentThreadsBusy,maxThreads"
`
and access web also works by http://127.0.0.1:8080/jolokia/read/Catalina:type=ThreadPool,name=%22http-nio-8080%22/currentThreadCount

So how to get the threadpool infomation?
Thanks

**Comment by xulz** [comment]
I have found the root cause:
The double quote should be escaped in way of:
_mbean = "Catalina:type=ThreadPool,name=\**"**http-bio-8080\**"**"_

Then it works.

**Comment by danielnelson** [comment]
Tomcat input plugin is merged for 1.4, thanks to @mlindes
