### ISSUE TITLE
IPMI_Sensor Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by deefdragon** [influxdata/telegraf#7636]
### Relevant telegraf.conf:

```toml
[[inputs.ipmi_sensor]]
servers = ["<user>@<password>@lanplus(<ip>)"]
```

### System info:
Running in docker on Pop_OS 20.04
tried in both 1.14.3 and 1.14.3-Alpine
### Docker

from telegraf:alpine
RUN apk add --no-cache --virtual build-dependencies ipmitool

### Steps to reproduce:
Start the container with the settings above.
### Expected behavior:
Data is piped to influx (or insert output here)
### Actual behavior:
On first poll, the following stack trace is produced
```
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.NewConnection(0xc0001f21b1, 0x29, 0x0, 0x0, 0xc000111950)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/connection.go:34 +0x3bd
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).parse(0xc000110730, 0x2ebdee0, 0xc00017e460, 0xc0001f21b1, 0x29, 0xc00017ea00, 0xc00017ea40)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:113 +0x72f
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather.func1(0xc0004a0af0, 0xc000110730, 0x2ebdee0, 0xc00017e460, 0xc0001f21b1, 0x29)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:92 +0x9d
created by github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:90 +0x116

```
### Additional info:
I don't appear to be the only one who has run into this. Someone else posted in issue #4922 , a different index out of bounds report, that they encountered a similar stack trace. (The most recent post is me being a tired idiot)

**Comment by deef0000dragon1** [comment]
I am an idiot and just noticed that I used `user@password` instead of `user:password` 
Still, I dont think telegraph should crash on a failed servers string, so I think the bug is still valid.

**Comment by danielnelson** [comment]
Thanks, that narrows it down.  Definitely still a valid bug, Telegraf should never panic like this.
