### ISSUE TITLE
tail plugin overwrites adds "path" tag

### ISSUE THREAD

**Issue by piotrp** [influxdata/telegraf#7649]
### Expected behavior:

I can configure Telegraf to pass metrics from named pipe into InfluxDB, without loss of data. This worked fine with Telegraf 1.2 (I know, that's ancient).

Writing of this tag should be configurable.

### Actual behavior:

tail input overwrites `path` tag: https://github.com/influxdata/telegraf/blob/release-1.14/plugins/inputs/tail/tail.go#L231 , breaking any `path` tag that can come from tailed file.

**Comment by vizcay** [comment]
I have the exact same problem.. my json path key is lost because of this.

@Crack have you found any workaround around this other than renaming at the datasource?

**Comment by vizcay** [comment]
Also looks like

```
 fielddrop = ["path"]
```

is not working with the Tail plugin.

**Comment by Crack** [comment]
@vizcay I no longer use tail plugin. I had a setup that used a newer Telegraf to collect data and 1.2 to sent to InfluxDB, and they were connected via pipe. I got rid of this and now use only one instance, using a recent version of Telegraf for both input and output.
