### ISSUE TITLE
make path regex configurable

### ISSUE THREAD

**Issue by tallexer** [influxdata/telegraf#7655]
Certain Juniper sensors does not comply with Open Config naming guidelines so they end up using underscore as part of the tag/field name. Because of this, Telegraf is not able to correctly identify these tags:

https://github.com/influxdata/telegraf/blob/2c202c9966360afc2c42783cd1174a60eed40678/plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go#L45

# juniper optical sensor
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_bias_current                float
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_bias_current_high_alarm     boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_bias_current_high_warning   boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_bias_current_low_alarm      boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_bias_current_low_warning    boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_output_power_dbm            float
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_output_power_high_alarm     boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_output_power_high_warning   boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_output_power_low_alarm      boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_output_power_low_warning    boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_receiver_power_dbm          float
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_receiver_power_high_alarm   boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_receiver_power_high_warning boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_receiver_power_low_alarm    boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_receiver_power_low_warning  boolean
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_laser_temperature                 float
/interfaces/interface/optics/lanediags/lane[lane_number='0']/lane_number                            integer

Ideally Juniper should fix their stuff and comply with the Open Config guidelines but there are concerns for backward compatibility. I was thinking if we can expose the path regex or the "acceptable" delimiters in the plugin configuration. 

Thanks

**Comment by powersj** [comment]
next steps: look into adding a config option that will let users set this regex

**Comment by sspaink** [comment]
@tallexer Are you still interested in this feature? Would you perhaps be interested in submitting a pull request to implement it? If not we could help as well, if you could help test the artifacts that would be great.
