### ISSUE TITLE
nvidia_smi plugin fails with certain output from /usr/bin/nvidia-smi

### ISSUE THREAD

**Issue by hawson** [influxdata/telegraf#7659]
### Relevant telegraf.conf:

```toml
[[inputs.nvidia_smi]]
  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
  # bin_path = "/usr/bin/nvidia-smi"

  ## Optional: timeout for GPU polling
  # timeout = "5s"

```

### System info:

* Centos 7.8
* telegraf 1.12.1
* NVIDIA System Management Interface -- v440.64.00
* Nvidia Tesla V100-SXM2-32GB

### Steps to reproduce:
1. Add input plugin as pasted above.
2. Get output errors:
```
Jun 09 17:04:40 gpuhost telegraf[96243]: 2020-06-09T21:04:40Z E! [inputs.nvidia_smi] Error in plugin: strconv.ParseInt: parsing "[N/A]": invalid syntax
```

### Expected behavior:
Properly handled "N/A" values, either by dropping them, forcing them to `0`, or anything that doens't involve failing.

### Actual behavior:
```
Jun 09 17:04:40 gpuhost telegraf[96243]: 2020-06-09T21:04:40Z E! [inputs.nvidia_smi] Error in plugin: strconv.ParseInt: parsing "[N/A]": invalid syntax
```
This can be traced to bad output from `nvidia-smi`:
```
[root@biogpu21 telegraf]# /usr/bin/nvidia-smi --format=noheader,nounits,csv --query-gpu=fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,utilization.gpu,utilization.memory,index --id=3
[N/A], 32510, 0, 32510, P0, 35, Tesla V100-SXM2-32GB, GPU-124-124-1241-241241241242341, 0, 0, 3
```

That first "[N/A]" confuses things, and causes the parser to fail.

**Comment by danielnelson** [comment]
This plugin has been updated to use the XML output instead, can you retest with Telegraf 1.14 and check if it is still an issue?

**Comment by chenseanxy** [comment]
According to the nvidia-smi docs:
```
Return Code 9 - NVIDIA driver is not loaded
```

**Comment by hawson** [comment]
See my original post:
```
Jun 09 17:04:40 gpuhost telegraf[96243]: 2020-06-09T21:04:40Z E! [inputs.nvidia_smi] Error in plugin: strconv.ParseInt: parsing "[N/A]": invalid syntax
```

I agree that error code 9 is unrelated; this box may have some hardware issues that were causing that particular problem, and that got conflated with this parsing problem.

That said, it appears that 1.14.4 fixes the issue.  Thanks.
