### ISSUE TITLE
Which application is suitable to batch data and periodically send it to influxdb?

### ISSUE THREAD

**Issue by markg85** [influxdata/telegraf#7665]
Hi,

First of all, sorry if this is the wrong place to ask!
I'm kinda swamped by the different names in the TICK stack and "think" i'm in the right place with telegraf, but i might we wrong still.

My case is as follows. I'm building a data logger to get data from my smart energy meter.
That data flows into a simple raspberry pi.
The pi is, through wifi, connected to a local server.
Now here are a few very important things to know
1. I need to log data, even when i flip off the main switch. The PI is powered with a lite APC to allow it to keep logging data for days without mains power if needed.
2. The wifi connection "can" be there. It's obviously not there if the mains power is off but it might also not find a connection due to it being placed in a corner of the house with poor connectivity. It needs to send the data as soon as it has connectivity.
3. I need to send the metrics, as they flow in from the meter, to telegraf (or influxdb?) as opposed to let telegraf poll for metrics.

Now i do recall there being some queue mechanism for either influxdb or telegraf that was designed for exactly this purpose! That would allow me to send the data as soon as it has a working wifi connection. But i can't find anything on what that thing is called. It might be an entirely different application, it might be a plugin.. I just don't know and google isn't helping me much either.

I hope you folks can point me into the right direction? :smiley: 

Cheers,
Mark

**Comment by danielnelson** [comment]
You could run Telegraf on the Raspberry Pi and it will buffer the data and send it on to InfluxDB when a connection available.

Some things to know about Telegraf is that it buffers only in memory, depending on how much data is produced and how much memory can be made available to Telegraf, this may or may not be a good fit for this use case.  When the buffer space is filled, the oldest data will be dropped.  If the Pi loses power all data will be lost.  Some users are pairing Telegraf with a durable message queue to work allow for longer buffering on disk.

Telegraf is primarily designed around being mostly online, so the outputs don't retry when the connection is up but instead periodic retries occur.  I'd love to have better support for offline mode in the future with less logging and retries that won't succeed.

Streaming the metrics into Telegraf isn't a problem, there are many plugins that work in this fashion.  What ways and formats can the meter send data in?

**Comment by markg85** [comment]
Hi Daniel,

The data format is nothing like JSON or even CSV.
An example:
```
1-0:72.36.0(00000)
0-
0:96.13.0(303132333435363738393A3B3C3D3E3F303132333435363738393A3B3C3D3E3F303132333435363738393A3B3C
3D3E3F303132333435363738393A3B3C3D3E3F303132333435363738393A3B3C3D3E3F)
```

But the format isn't an issue. There are [parsers](https://github.com/ndokter/dsmr_parser) for that.

After my initial post i watched some videos about telegraf and it's capabilities.
From what i get i should make (or use) a plugin that does push (instead of pull). That has a couple of learning curves as i don't know Go :)

Another approach seems to be to directly inject it in influxdb.

I don't know what the right approach is, yet.

**Comment by danielnelson** [comment]
Since DSMR isn't a format that is built into Telegraf and since this library is in Python, I think the way you would want to integrate with Telegraf is to have a script for the [execd](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) input plugin.  This script can be written in any language, it should run until manually terminated and would read the DSMR data in and write one of the [input data formats](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md) to stdout.

Since you need to write a custom script anyway, the advantages you would get using Telegraf over writing to InfluxDB directly are:
- maybe be somewhat easier to write the script, no need to make http calls, Telegraf will start and restart process.
- buffering and retries if InfluxDB is down
- flexibility of having proxy point
- availability other Telegraf plugins

I'll leave it to you to decide if these are helpful enough in your case to justify the extra piece.

**Comment by markg85** [comment]
Hi Daniel,

Thank you for the elaborate explanation!
I think i want to go that route, for stability, eventually.

Right now i picked a python project that can write directly to influxdb which is working in my case :)
Had to downgrade that DSMR parser to a previous version though..

It's definitely not the way i like to keep it running as i now have 2 influxdb instances in my network... Seems wrong imho. The way to go is with telegraf i think. Thank you for the execd pointer, that really helps in figuring out how to handle this!

It can use some more work to get it properly setup, but i'm happy with the graphs i get from it thus far :)

Thank you again!

Cheers,
Mark

**Comment by danielnelson** [comment]
Sounds like you have an idea how to proceed, so I'm going to go ahead and close this issue.
