### ISSUE TITLE
Question: how to address right timescaledb database ?

### ISSUE THREAD

**Issue by lblabr** [influxdata/telegraf#7666]
i use telegraf to stream data to influx and/or timescaledb.
at the moment the influx.listener plugin is used to retrieve data and store to influx and timescaledb.
in output.influx you may reuse the database provided with the write query, is there also a way ot use the database_tag in timescaledb/postgres output plugin ?

thanks in advance

Lars

**Comment by danielnelson** [comment]
We don't currently have an output plugin for TimescaleDB or Postgres, maybe in the future.
