### ISSUE TITLE
Docker input: add container state metrics

### ISSUE THREAD

**Issue by stanch** [influxdata/telegraf#767]
Would be nice to have state metrics for each container, as exemplified by this JSON:

``` json
{
  "Running": 1,
  "Paused": 0,
  "Restarting": 0,
  "OOMKilled": 0,
  "Dead": 0
}
```

This information is available through `docker inspect <container>` (and I imagine through the API as well). 
## 

For the record, here's an abomination I'm using right now:

```
[[inputs.exec]]
  commands = [
    "sh -c \"docker inspect container1 | jq 'def b2i: if . then 1 else 0 end; .[] | { name: .Name, running: .State.Running | b2i, paused: .State.Paused | b2i, restarting: .State.Restarting | b2i }'\""
  ]

  data_format = "json"

  # measurement name suffix (for separating different commands)
  name_suffix = "_container1"
```

**Comment by jeromegn** [comment]
This would also make it possible to get display better charts for setups that don't cleanup dead containers so often.

**Comment by stanch** [comment]
Hi, I don’t think the issue should be closed. The merged commit only adds global container state metrics (see https://github.com/influxdata/telegraf/pull/1791/files#diff-691fdaed73e36497110e1ea47c1498f5R157), while the issue was about per-container metrics.

**Comment by prashanthjbabu** [comment]
Hi,I'd like to know if per container state metrics is supported now by any chance or if there's any plan to support it ?

**Comment by prashanthjbabu** [comment]
I've attempted to implement this in the following pull request https://github.com/influxdata/telegraf/pull/4259 . I hope this helps!

**Comment by GeorgeMac** [comment]
Delivered in https://github.com/influxdata/telegraf/pull/4259
