### ISSUE TITLE
[QUESTION] telemetry server using udp for transport

### ISSUE THREAD

**Issue by nskalis** [influxdata/telegraf#7670]
Hi,

when having a look at 

- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_gnmi
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_mdt

all of the transports are based on tcp (grpc=http2+gpb)

but 

- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry

has as an option to use udp as a transport method

https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/junos-telemetry-interface-configuring.html

Do you support dup-based telemetry ?

**Comment by danielnelson** [comment]
No, only gRPC.
