### ISSUE TITLE
Modbus input : Default data collection interval has issue

### ISSUE THREAD

**Issue by krishnacy** [influxdata/telegraf#7673]
### Relevant telegraf.conf:

```[agent]
  interval = "60s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.  round_interval = true
```
### Expected behavior:

The data collection should be in 60 sec interval.

### Actual behavior:

Random timestamp data logging is observed

![image](https://user-images.githubusercontent.com/53948376/84533925-af427a80-ad06-11ea-93b4-d5aad88e9eb1.png)

**Comment by danielnelson** [comment]
Make sure `round_interval = true` is on it's own line, it looks like it may have been joined with the comment above it.

**Comment by krishnacy** [comment]
hi, 

```
[agent]
  ## Default data collection interval for all inputs
  interval = "60s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true
```

Seems like my original post has format issues. Yes, `  round_interval = true` is already set

**Comment by danielnelson** [comment]
Looking at the screen shot, it seems that the timestamps are always on an even minute.  Can you describe in more detail what you are expecting to see vs what you see in actuality?

**Comment by krishnacy** [comment]
Expected result : 1- minute/60 sec data logging  

![expected timestamp](https://user-images.githubusercontent.com/53948376/85217558-e6242a80-b3af-11ea-8843-e0ab138a527d.PNG)

Actual result : Random timestamp data logging 

![timestamp](https://user-images.githubusercontent.com/53948376/85217569-03f18f80-b3b0-11ea-99d8-3b69d291fcb2.PNG)

The data is logging in random timestamps (not even timestamps as you can see from the above picture). Only 1 minute data is to be logged, but there are multiple instances where within a minute data is logged.

**Comment by danielnelson** [comment]
Can you try with one of the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and see if it helps?  It looks like we have switched to setting the timestamp when the queries begin to when it ends.

One thing to keep in mind with interval/round_interval: it only controls when the plugin begins working and the timestamps are generally set when the data is collected (depends on the plugin actually).  So it's not a guarantee that the timestamps will be exactly at the 60s alignment.  After the timestamp is determined the `precision` setting is applied to optionally round the timestamp.
