### ISSUE TITLE
Modbus input data writing Field Vs Tags issue

### ISSUE THREAD

**Issue by krishnacy** [influxdata/telegraf#7674]
I could be wrong here, but getting it clarified!!

### Relevant telegraf.conf:

```
 ## Device name
 name = "B01_INV1"
## address    - variable address
holding_registers = [
    { name = "AC Volatge_1",  byte_order = "AB",  data_type = "INT16",  scale=1.0,  address = [103]},
	{ name = "AC Volatge_2",  byte_order = "AB",  data_type = "INT16",  scale=1.0,  address = [104]},
	{ name = "AC Volatge_3",  byte_order = "AB",  data_type = "INT16",  scale=1.0,  address = [105]},
]
```
### Expected behavior:
The device name should be considered as [fields](https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/#field-key) and the variables should be considered as [tags](https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/#tag-key)

### Actual behavior:

As per my understanding, the input plugin is writing the device name in tags and variables into field values.  This should be other way around!.

### Additional info:

![image](https://user-images.githubusercontent.com/53948376/84535049-a783d580-ad08-11ea-9b92-888b08320cd3.png)

![image](https://user-images.githubusercontent.com/53948376/84535098-bd919600-ad08-11ea-92c9-edb2788a6c80.png)

**Comment by krishnacy** [comment]
Hi, 

Can someone please look into this !!

**Comment by danielnelson** [comment]
The way it is setup now is correct, the variables are the field values, `AC Voltage_1` is the field key and the device name is a tag.  Tags are indexed, you wouldn't wan to store a changing value as their value as it would result in massive cardinality.
