### ISSUE TITLE
Httpjson input: Allow specifying POST JSON body

### ISSUE THREAD

**Issue by stanch** [influxdata/telegraf#768]
It would be convenient to be able to specify JSON body for POST requests. I guess just providing JSON as a string works, but if it is to be separated by keys, non-string values should be supported (unlike with the GET parameters).

**Comment by sparrc** [comment]
sure, could you separate this into two separate issues though?

**Comment by stanch** [comment]
Done!

**Comment by guige** [comment]
How can input body for http request. I had input body from readme example, but return error.

**Comment by danielnelson** [comment]
@guige We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by guige** [comment]
@danielnelson I resove it use httpjson, because i use httprespose.😭

**Comment by nmjensen** [comment]
This feature would be very useful. I've currently worked around it by calling curl from the exec plugin, but as I'm running Telegraf in the alpine based docker image - it doesn't include curl so I need to install it using apk whenever it's updated.
