### ISSUE TITLE
telegraf jolokia2 agent authentication

### ISSUE THREAD

**Issue by sri-05** [influxdata/telegraf#7681]
Hi,

I have enabled the authentication for jolokia2 agent but unfortunately, authentication is not working. I can able to fetch the metrics without credentials in the curl call.
below are the configuration and error details.

```
 [[inputs.jolokia2_agent]]
#   # default_tag_prefix      = ""
#   # default_field_prefix    = ""
#   # default_field_separator = "."
#
#   # Add agents URLs to query
   urls = ["http://<IP>:8778/jolokia"]
    username = "testuser"
    password = "testuser"
#   # response_timeout = "5s"
#
#   ## Optional TLS config
#   # tls_ca   = "/var/private/ca.pem"
#   # tls_cert = "/var/private/client.pem"
#   # tls_key  = "/var/private/client-key.pem"
#   # insecure_skip_verify = false
#
#   ## Add metrics to read
  [[inputs.jolokia2_agent.metric]]
     name  = "java_runtime"
     mbean = "java.lang:type=Runtime"
     paths = ["Uptime"]
     field_prefix = "$1_"
```

`curl http://<IP>:8778/jolokia/read/java.lang:type=Memory/HeapMemoryUsage`

The above curl call giving a success response.
`{"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":2025848832,"committed":2004877312,"max":2004877312,"used":609503496},"timestamp":1592200280,"status":200}`

Telegraf version 
```
telegraf-1.14.4-1.x86_64
```
Jolokia agent Version
```
"agent":"1.3.5"
```

**Comment by danielnelson** [comment]
Sorry, I don't understand the issue, can you explain the error/results you are seeing and also what error/results you are expecting to see?

**Comment by sjwang90** [comment]
@sri-05 If you are still experiencing this issue, please open this back up and provide the error in further detail. Thanks.
