### ISSUE TITLE
[agent] Error writing to outputs.influxdb: could not write any address

### ISSUE THREAD

**Issue by Daly123456** [influxdata/telegraf#7683]
After setting up telegraf and working for a periode i suddenly got this error :
juin 15 10:52:10 haproxy telegraf[12700]: 2020-06-15T09:52:10Z E! [outputs.influxdb] When writing to [http://grafana.s.com:8086]: Post http://grafana.s.com:8086/write?db=infra-sft: dial tcp: lookup grafana.s.com on 172.16.0.198:53: read udp 192.168.1.181:58494->172.16.0.198:53: i/o timeout
juin 15 10:52:10 haproxy telegraf[12700]: 2020-06-15T09:52:10Z E! [agent] Error writing to outputs.influxdb: could not write any address
Some help please

**Comment by ssoroka** [comment]
This error would be normal if grafana.s.com was temporarily unavailable. Telegraf will reconnect and will not drop any messages if the destination server comes back up in a reasonable time. You'll be notified in the logs if it has to drop messages while waiting for the server to come back up. If you have not seen other errors, you can ignore this.

**Comment by danielnelson** [comment]
@Daly123456 To clarify the error message, while looking up the ip address of `grafana.s.com` your DNS server did not reply.  This could mean your DNS is down, firewalled, or otherwise misconfigured.

**Comment by Commander-Crash** [comment]
Any one fixed this? This error makes this completely useless to use.
