### ISSUE TITLE
FlushBufferWhenFull

### ISSUE THREAD

**Issue by NealsJoe** [influxdata/telegraf#7688]
With commit ee468be6962165b0a9ec0b672dc0b1eb95fd2ffb (Flush based on buffer size rather than time; 16 Feb 2016) there has been introduced the config option"flush_buffer_when_full" (etc/telegraf.conf) and the variable "FlushBufferWhenFull" (internal/config/config.go).

Nowerdays in the master branch I only find "FlushBufferWhenFull" in the "config/config.go". But it seems not handled or used anymore.

Is this option and a procedure like "flush buffer when full" nowerdays default and so the variable obsolete?

**Comment by danielnelson** [comment]
Yes this behavior is automatic, a flush is always triggered once the buffer is full.

This option was deprecated in 0.13, it only exists to prevent configuration errors: https://github.com/influxdata/telegraf/pull/1096/files, I'll add a note to to the comment.
