### ISSUE TITLE
Implementing log parsing for errors - input plugin

### ISSUE THREAD

**Issue by wdoogz** [influxdata/telegraf#7703]
## Feature Proposal

Implementing log parsing for errors - input plugin

### Proposal: 

I have started developing an input plugin on my own time that will parse 1 to many log files for Errors. This will also support a user to bring their own regex to conform to many different applications (Trafficserver, OpenStack, mcelog, etc.). Before I put any more work into this to meet the open-source standards I would like to know if I should continue.

### Use case: 

Coming from a site reliability stand point we care about errors in logs, but to an extent. The ability to know exactly how many errors, failures, aborts, etc. are in a log file and graph them out I think holds some value. I also think many will value such a simple plugin.

Thanks!
Wesley

**Comment by danielnelson** [comment]
So if I'm understanding correctly the plugin would parse log files and then generate summary statistics about number of errors, failures,aborts that were found in it?

**Comment by wdoogz** [comment]
Yup you got it. It will offer the ability to bring your own regex, as I know some log files have different syntax. So giving the user the option to search any log for any string as well is nice.

**Comment by danielnelson** [comment]
This would be fairly similar to the `tail` plugin with `data_format = "grok"`, combined with an aggregator like `valuecounter`.  Have you tried using these plugins and if so, what sort of limitations did you run into?

**Comment by Rylon** [comment]
@danielnelson I don't support you have any concrete examples of how those three plugins would fit together do you? I'm scratching my head trying to figure out how to solve this same problem.

Essentially I want to tail an error log, use a regex or Grok pattern to look for specific text in each line, and then count how many times those messages occurred, and send that count to InfluxDB, so we can visualise the quantity of those errors in Grafana, and alert on them.

I feel like this should be possible with the combination of plugins you mentioned, but I just can't get it to play ball.

When using a working Grok pattern, I get the following error:

```
error parsing regexp: invalid or unsupported Perl syntax: `(?<`
```

Trying a variety of other patterns I just end up with no matches.

An example of how this works in a similar tool, CollectD:

```
<Plugin tail>
  <File "/var/log/error.log">
    Instance "errorlogs"
    <Match>
      Regex "^.*This is a bit of text in the error.*$"
      DSType "CounterInc"
      Type "counter"
      Instance "my-error"
    </Match>
  </File>
</Plugin
```
