### ISSUE TITLE
Update mongodb input to use maintained library

### ISSUE THREAD

**Issue by florianrusch** [influxdata/telegraf#7706]
As far as I could see, the MongoDB input plugin uses `gopkg.in/mgo.v2` as Mongo Driver, which seems to be unmaintained: https://github.com/go-mgo/mgo/blob/v2-unstable/README.md

There exists a MongoDB Go Driver directly from MongoDB: https://docs.mongodb.com/drivers/go

Is there any reason, why the plugin still uses the old unmaintained driver?

**Comment by danielnelson** [comment]
We are looking for something to update the plugin either to https://github.com/globalsign/mgo or, probably more work, to https://github.com/mongodb/mongo-go-driver.  Is this something you would be interested in working on?

related #5795

**Comment by florianrusch** [comment]
@danielnelson sorry, I'm currently writing my master thesis and have no time to dig into this. But the plan sounds good!
