### ISSUE TITLE
Extend ntpq/openntpd input plugins to use golang ntp client instead of using ntpq or ntpctl

### ISSUE THREAD

**Issue by veera-chenna** [influxdata/telegraf#7707]
### Proposal:
Extend either ntpq or openntpd input plugins to use golang ntp client such as github.com/beevik/ntp.

### Current behavior:
"ntpq" or "openntpd" input plugins have a pre-requisite of installing either "ntpq" or "ntpctl" utilities.

### Desired behavior:
Use a golang client such as github.com/beevik/ntp to query an ntp server

### Use case: 
In the case of Kubernetes if I want to use "ntpq" or "openntpd" plugins, I need to add these pre-requisites in the docker image. Instead of using other tools such as ntpq or ntpctl, if we use a golang client, it will remove the need to install other utilities on the image.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you yet.

While this might make things easier I think we would pass on embedding this into Telegraf. There are a number of prerequisites for many other plugins and users need to include whatever they need on their system. I also want to be aware of the binary size. While the suggested client looks to be small it is easy to keep adding these sorts of things one by one.

Thanks
