### ISSUE TITLE
[Logging] Sort the loaded inputs, aggregators, processors, and outputs 

### ISSUE THREAD

**Issue by FixTestRepeat** [influxdata/telegraf#7710]
## Feature Request

telegraf (v1.14.3) currently doesn't sort the various loaded inputs, aggregators, processors, and outputs.  This makes troubleshooting more onerous.

### Proposal:
When Telegraf starts, the modules loaded should be logged in a sorted fashion. 

This should be applied to all loads:

- inputs
- aggregators
- outputs
- inputs

### Current behavior:
5 successive reloads of the telegraf service yield different order of the loaded modules:

> for i in `seq 1 5` ; do sudo systemctl restart telegraf.service ; sleep 2 ; systemctl status telegraf.service | grep Loaded ; done
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded inputs: cpu disk diskio mem net socket_listener processes swap system
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded aggregators:
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded processors:
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded inputs: **diskio mem net system socket_listener cpu disk processes swap**
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded aggregators:
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded processors:
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded inputs: **disk diskio mem net processes cpu swap system socket_listener**
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded aggregators:
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded processors:
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded inputs: **system socket_listener mem swap diskio net processes cpu disk**
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded aggregators:
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded processors:
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! **Loaded inputs: disk mem net processes swap socket_listener cpu system diskio**
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded aggregators:
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded processors:
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded outputs: influxdb_v2

### Desired behavior:

> for i in `seq 1 5` ; do sudo systemctl restart telegraf.service ; sleep 2 ; systemctl status telegraf.service | grep Loaded ; done
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded inputs: **cpu disk diskio mem net processes socket_listener swap system**
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded aggregators:
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded processors:
Jun 21 12:36:34 raspiM telegraf[25946]: 2020-06-21T02:36:34Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded inputs: **cpu disk diskio mem net processes socket_listener swap system**
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded aggregators:
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded processors:
Jun 21 12:36:36 raspiM telegraf[25973]: 2020-06-21T02:36:36Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded inputs: **cpu disk diskio mem net processes socket_listener swap system**
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded aggregators:
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded processors:
Jun 21 12:36:39 raspiM telegraf[25999]: 2020-06-21T02:36:39Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded inputs: **cpu disk diskio mem net processes socket_listener swap system**
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded aggregators:
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded processors:
Jun 21 12:36:41 raspiM telegraf[26026]: 2020-06-21T02:36:41Z I! Loaded outputs: influxdb_v2
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded inputs: **cpu disk diskio mem net processes socket_listener swap system**
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded aggregators:
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded processors:
Jun 21 12:36:43 raspiM telegraf[26053]: 2020-06-21T02:36:43Z I! Loaded outputs: influxdb_v2

### Use case: 

Simplify troubleshooting when dealing with larger and larger numbers of modules.

**Comment by FixTestRepeat** [comment]
Might be possible to re-use some of the code used here in PR #6810 for usage help info.

**Comment by jonathanlloyd** [comment]
I've taken a crack at this in #8218 
Happy Hacktoberfest! :jack_o_lantern:

**Comment by ssoroka** [comment]
I believe this is closed in https://github.com/influxdata/telegraf/pull/8127
