### ISSUE TITLE
Telegraf fails to start when using [agent] logfile

### ISSUE THREAD

**Issue by mdevy-influxdata** [influxdata/telegraf#7714]
Issue was noticed when telegraf start up process did not produce the expected output, of the plugins loaded, etc.  The output instead looked like the following.

```# telegraf -config telegraf.conf
2020-06-22T16:46:56Z I! Starting Telegraf 1.14.4
^C
```

### Relevant telegraf.conf:

```toml
[agent]
   ....
  logfile = "/tmp/telegraf"
....
```
Any file specified in the logfile creates this failure.  Even if the file is completely open and owned by telegraf user.

### Steps to reproduce:

1. Verify telegraf process starts normally using a standard config.  
2. Modify the 'logfile' parameter within the [agent] 
3. Restart process with logfile parameter set in config.
4. Observe differences between two startups.

### Expected behavior:
```
# telegraf -config telegraf.conf
2020-06-22T16:47:11Z I! Starting Telegraf 1.14.4
2020-06-22T16:47:11Z I! Loaded inputs: disk diskio kernel mem processes swap system cpu
2020-06-22T16:47:11Z I! Loaded aggregators:
2020-06-22T16:47:11Z I! Loaded processors:
2020-06-22T16:47:11Z I! Loaded outputs: influxdb
2020-06-22T16:47:11Z I! Tags enabled: host=host
2020-06-22T16:47:11Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"host", Flush Interval:10s
^C2020-06-22T16:47:12Z I! [agent] Hang on, flushing any cached metrics before shutdown
```
### Actual behavior:

```# telegraf -config telegraf.conf
2020-06-22T16:46:56Z I! Starting Telegraf 1.14.4
^C
```

**Comment by danielnelson** [comment]
I can't reproduce this using the .deb package, can you attach your full configuration?

**Comment by mdevy-influxdata** [comment]
Configuration attached.

To be safe, I re-created the conf file with the following command:
```
telegraf -sample-config -input-filter cpu:mem -output-filter influxdb > telegraf-default.conf
cp telegraf-default.conf telegraf-modified.conf
```

Then modified only the 'logfile' parameter on line 78 in the 'telegraf-modified.conf' file.
```
diff telegraf-*
78c78
<   # logfile = ""
---
>   logfile = "/tmp/telegraf"
```

Same result
```
# telegraf -config telegraf-modified.conf
2020-06-22T18:58:55Z I! Starting Telegraf 1.14.4
```

Host OS is Ubuntu 18.04.1 LTS

**Comment by mdevy-influxdata** [comment]
Apologies, renamed extension to .txt.

[Uploading telegraf-modified.conf.txt…]()

**Comment by danielnelson** [comment]
Seems to be working fine for me, all output after the `Starting Telegraf 1.14.4` line goes to `/tmp/telegraf` so you won't see all the logging lines from the expected section of the original comment.

**Comment by mdevy-influxdata** [comment]
That makes sense.  
Thanks for the quick resolution on this issue.
