### ISSUE TITLE
Net input not scaling with the number of interfaces

### ISSUE THREAD

**Issue by dvenza** [influxdata/telegraf#772]
I'm running telegraf on linux.
I have a Docker Swarm cluster and on each box I run docker with the new overlay network. I use a lot of them, so I have a lot of virtual interfaces on each host. At this time I have about 300.
The net plugin is adding about 10 seconds to the loop time of telegram (as seen by the logs).
Is there a way to limit the interfaces the plugin reads the data about (like read only eth? or ignore veth*) ?

**Comment by zstyblik** [comment]
@dvenza, yes, it should be possible - https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/net.go#L23

**Comment by dvenza** [comment]
Oh, yes, I didn't notice it is reported in the sample config file.

Thanks!
