### ISSUE TITLE
[QUESTION] will gRPC connection be dropped after config change ?

### ISSUE THREAD

**Issue by nskalis** [influxdata/telegraf#7720]
Hi,

when having a look at

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_gnmi
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_mdt

all of the transports are based on tcp (grpc=http2+gpb).

What I would like to ask you is: 

if I wish to re-configure the telegraf config (.toml) in order to change its settings
or add more routers to establish a persistent connection with them,

how the new settings will be considered? Does it require a restart/reload, will it drop the previous (established)
connections with the routers?

**Comment by danielnelson** [comment]
Currently if you restart or reload add connections are closed and recreated, and you could potentially miss data during this period.  It's possible this will be improved in the future, probably the first thing we would tackle would be that unchanged plugins do not get restarted when a reload occurs.

**Comment by ssoroka** [comment]
FYI, you can signal config reload with a SIGHUP. It will stop previous outputs and start new ones with the new config like daniel mentioned.
