### ISSUE TITLE
Error in plugin: While collecting cluster: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'.

### ISSUE THREAD

**Issue by kkruzich** [influxdata/telegraf#7721]
### Relevant telegraf.conf:

```
vsphere.historical.conf:

[[inputs.vsphere]]
  vcenters = [ "https://vc1.com/sdk", "https://vc2.com/sdk" ]
  username = "${VSPHERE_USERNAME}"
  password = "${VSPHERE_PASSWORD}"
  interval = "300s"
  vm_metric_exclude = [ "*" ]
  host_metric_exclude = [ "*" ]
  datastore_metric_exclude = [ "*" ]
  datacenter_metric_exclude = [ "*" ]
  cluster_metric_include = [ "*" ]
  collect_concurrency = 5
  force_discover_on_init = true
  timeout = "240s"
  insecure_skip_verify = true

vsphere.realtime.conf: 

[[inputs.vsphere]]
  vcenters = [ "https://vc1.com/sdk", "https://vc2.com/sdk" ]
  username = "${VSPHERE_USERNAME}"
  password = "${VSPHERE_PASSWORD}"
  interval = "60s"
  vm_metric_exclude = [ "*" ]
  datastore_metric_exclude = [ "*" ]
  cluster_metric_exclude = [ "*" ]
  datacenter_metric_exclude = [ "*" ]
  host_metric_include = [ "*" ]
  collect_concurrency = 7
  discover_concurrency = 7
  force_discover_on_init = true
  timeout = "240s"
  insecure_skip_verify = true

```

### System info:

telegraf-1.12.1-1.x86_64

### Steps to reproduce:

I've been using inputs.vsphere for over a year. I'm successfully collecting metrics against a large environment. In the past couple of months, maybe shortly after updating to 6.7.u3, I've been seeing this in the logs. 

```
2020-06-23T21:30:26Z E! [inputs.vsphere] Error in plugin: While collecting cluster: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.
2020-06-23T21:31:21Z W! [agent] [inputs.vsphere] did not complete within its interval
2020-06-23T21:31:23Z E! [inputs.vsphere] Error in plugin: While collecting host: Post https://mygroovyvcenter.com/sdk: context deadline exceeded
```
What concerns me is I worked through issues with 'maxQueryMetrics' in the past. I would query with the below command, get a value and adjust if necessary. Now it's returning this error: 

```
govc option.ls config.vpxd.stats.maxQueryMetrics
govc: ServerFaultCode: 'config.vpxd.stats.maxQueryMetrics' is invalid or exceeds the maximum number of characters permitted.
```

What should I be looking at to resolve these errors I see in the logs? 

### Expected behavior:

No E! errors in my logs.

**Comment by danielnelson** [comment]
@prydin is this a known issue?

**Comment by prydin** [comment]
This is a bit strange... The message is coming from the vCenter server when we try to get the max query limit. Can you tell me what it's set to? Almost sounds like the value has gotten corrupted on the vCenter side.

**Comment by prydin** [comment]
Looks like our brethren at Zabbix ran into the same issue. Apparently, 6.7 no longer supports a ```maxQueryMetric``` setting of -1 to indicate infinity. I would say this is a regression on vCenter. Try setting the parameter to a really large value, like 10000, instead.

https://support.zabbix.com/browse/ZBX-14858

**Comment by kkruzich** [comment]
Thank you for the comments. I've noted your recommendation on what to use for the values but I'd like to try my previously used values to see if that has a positive effect. Also, I was able to use -1. Anyhow, the summary here is although I'm unable to initially GET the value ```govc option.ls``` I can SET and then GET: 

```
# govc option.ls config.vpxd.stats.maxQueryMetrics
govc: ServerFaultCode: 'config.vpxd.stats.maxQueryMetrics' is invalid or exceeds the maximum number of characters permitted.
# govc option.set config.vpxd.stats.maxQueryMetrics -1
# govc option.ls config.vpxd.stats.maxQueryMetrics
config.vpxd.stats.maxQueryMetrics:  -1
```

```
# govc option.ls config.vpxd.stats.maxQueryMetrics
govc: ServerFaultCode: 'config.vpxd.stats.maxQueryMetrics' is invalid or exceeds the maximum number of characters permitted.
# govc option.set config.vpxd.stats.maxQueryMetrics 2100
# govc option.ls config.vpxd.stats.maxQueryMetrics
config.vpxd.stats.maxQueryMetrics:  2100
```

Now that I'm able to change the values, I'll see if there's a change to the 'Error in plugin' log entries.

**Comment by prydin** [comment]
@ssoroka This is caused by a misconfiguration of vCenter. Can we please close this?

**Comment by kkruzich** [comment]
I will close this. Thank you!
