### ISSUE TITLE
Sql Server - remove tag "database_name" is some collectors

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7724]
## Feature Request

In most collectors the "database_name" tag is useless (at least when obtained using DB_NAME() ), since the queries are instance wide and do not use a database scope, so in general it will just return a fixed value, probably "master". 

Those are the queries in which the tag looks useless to me.
- PerformanceCounters
- WaitStatsCategorized
- ServerProperties
- MemoryClerk
- Schedulers
- SqlRequests (here the useful tag is called "session_db_name")

### Proposal:
Remove the tag "database_name" when not useful

**Comment by denzilribeiro** [comment]
This was added primarily for the Azure SQL DB case as a logical server isn't a n instance in Azure and there is no way to correlate DB's otherwise. Once we split things up  per # 7713 will be much easier to remove for on-prem. Right now some of the collectors are shared.

**Comment by Trovalo** [comment]
THis has been done in the query splitting and also in the later query refactoring
