### ISSUE TITLE
Processor_Queue_Length for Linux

### ISSUE THREAD

**Issue by callahan22** [influxdata/telegraf#7727]
Not a bug, possibly a Feature Request unless it exists already and I've just not found it....

I'm currently using win_Processor_Queue_Length to gauge the number of waiting jobs for the CPUs. This works fine for Windows but we have over half our estate as Linux boxes so I'd like to find the equivalent. So far, the closest I have come is the `[[inputs.sysstat]]` but that needs me to enable systat on the target server:

-  sudo nano /etc/default/sysstat
- Change to Enable, 
- Save and restart service.
- Then run -q on target server which gives:

```

Linux 4.15.0-106-generic (linux_server)        06/24/2020      _x86_64_        (2 CPU)

12:54:52     LINUX RESTART      (2 CPU)

12:55:01 PM   runq-sz  plist-sz   ldavg-1   ldavg-5  ldavg-15   blocked
01:05:01 PM         0       186      0.00      0.00      0.00         1
01:15:01 PM         0       186      0.02      0.02      0.00         1
01:25:01 PM         0       186      0.00      0.00      0.00         1
Average:            0       186      0.01      0.01      0.00         1
```
From that, I'm guessing the "Average" for blocked ports is what we would need to get the average processor queue length.
Ideally, I would like to get this metric by just adding the [[input.X]] to the config file but that doesn't seem like it's possible. Can anyone confirm if this is the only way I can get the processor queue lengh on Linux boxes? Will I therefore have to ensure that part of my deployment of the telegraf client to the Linux boxes includes the enabling of sysstat?

Thanks.

**Comment by danielnelson** [comment]
How using `/proc/schedstat` is the way to go, its [not the top answer but described here](https://stackoverflow.com/questions/440756/how-to-find-the-processor-queue-length-in-linux).  The output of this file is a bit nonstandard, but you could grab it using the exec/execd input and a script.

**Comment by sjwang90** [comment]
@callahan22 Wanted to check in to see if this was resolved?
