### ISSUE TITLE
S7comm external, input plugin

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#7728]
## Feature Request
Add an external, input plug for [s7comm](https://wiki.wireshark.org/S7comm)

### Proposal:
Key protocol for SCADA PLC devices from Siemens.

**Comment by timhallinflux** [comment]
Golang implementation of S7comm is here: https://github.com/robinson/gos7 BSD-3 license.

**Comment by nicolasme** [comment]
I'm currently writing an external plugin using gos7. It's functionnal but still under development. You can take a look here https://github.com/nicolasme/s7comm. It's my first time contributing to a project. I don't really know how it works ...
