### ISSUE TITLE
Document what happens with execd input's underlying process's stderr

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/telegraf#7739]
It looks like it gets repeated to telegraf's logs, which presumably go to stderr: https://github.com/influxdata/telegraf/blob/c06eef47e710fa4efefbcfcb6469b9f96eaab407/plugins/inputs/execd/execd.go#L248-L258

The execd README makes no mention of stderr, but it should explain what happens.

**Comment by ssoroka** [comment]
👍 
quick answer: it's logged to stderr with the rest of Telegraf's log output.

**Comment by ssoroka** [comment]
Looks like this is already done. https://github.com/influxdata/telegraf/blame/master/plugins/inputs/execd/README.md#L12
