### ISSUE TITLE
stackdriver output plugin sends CUMULATIVE metrics incorrect

### ISSUE THREAD

**Issue by camaeel** [influxdata/telegraf#7758]
1. Telegraf 1.14 with input plugins diskio end net gathers Counter type metrics (for example net/bytes_sent)
2. Stackdriver output plugin sends these metrics to google cloud's Stackdriver

But stackdriver shows these metrics as flatline without value changes: 

![image](https://user-images.githubusercontent.com/12999736/86008124-a77a1a00-ba18-11ea-916f-2ad537729d9d.png)

When I try to get metrics timeSeries details:
`https://content-monitoring.googleapis.com/v3/projects/XXXX/timeSeries?filter=metric.type%20%3D%20%22custom.googleapis.com%2Fk3s-ns%2Fdiskio%2Fread_bytes%22&interval.startTime=2020-06-28T00%3A00%3A00Z&interval.endTime=2020-06-29T00%3A00%3A00Z&key=YYYYY`

I get response:
`{
  "unit": "{not_a_unit}"
}`

Sending same metrics to InfluxDB works correctly and values are written correctly. I assume that this is some issue with stackdriver output plugin and wrong usage of Google's API.

**Comment by n-oden** [comment]
@camaeel @danielnelson I'm curious if you ever found a solution or workaround to this issue; I'm running into exactly this with both 1.18.3 (from alpine) and 1.20.3.

@akrantz01 your basicstats stanza there means that the original counter metric never gets exported to stackdriver, and all of the aggregate sub-metrics are GAUGE not CUMULATIVE.

I've checked the outputs via the influxdb udp output, and confirmed that they at least _appear_ correct, e.g.:

```
# grep 'pgpool2_pool_backend_stats_select_cnt,host=pgpool-5fff99ccdd-wzj4b,hostname=10.0.4.15,port=5432,role=standby,url=http:
//localhost:9719/metrics' telegraf_dump.txt
pgpool2_pool_backend_stats_select_cnt,host=pgpool-5fff99ccdd-wzj4b,hostname=10.0.4.15,port=5432,role=standby,url=http://localhost:9719/metrics counter=0 1636580520000000000
pgpool2_pool_backend_stats_select_cnt,host=pgpool-5fff99ccdd-wzj4b,hostname=10.0.4.15,port=5432,role=standby,url=http://localhost:9719/metrics counter=749 1636580580000000000
pgpool2_pool_backend_stats_select_cnt,host=pgpool-5fff99ccdd-wzj4b,hostname=10.0.4.15,port=5432,role=standby,url=http://localhost:9719/metrics counter=2122 1636580640000000000
pgpool2_pool_backend_stats_select_cnt,host=pgpool-5fff99ccdd-wzj4b,hostname=10.0.4.15,port=5432,role=standby,url=http://localhost:9719/metrics counter=4511 1636580700000000000
```

Unfortunately Google Cloud Monitoring nee Stackdriver is not exactly blessed with robust web or cli tools to debug things on their side; I'll spend tomorrow writing some tools and will update this issue.

**Comment by camaeel** [comment]
I found a solution - I dropped Stackdriver and moved to New Relic.

**Comment by n-oden** [comment]
Oh boy, this was fun: https://github.com/influxdata/telegraf/pull/10097

As far as I can tell, if telegraf publishing of counter/cumulative metrics to stackdriver ever worked at all, it was entirely accidental and due to extremely generous behavior on google's part.  But most likely it simply never worked.
