### ISSUE TITLE
[QUESTION] sensors allow/deny-list feature?

### ISSUE THREAD

**Issue by nskalis** [influxdata/telegraf#7765]
Hi,

when having a look at

- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_gnmi
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_mdt

What I would like to ask you is:

if I wish to collect the `interfaces` and `cpu` metrics and this works well for `router-1`, but, let's say on `router-2`
I would like to remove the `interfaces` metric (for privacy reasons or it can be misbehaving, etc.) is there any kind of allow/deny-list of sensors that can be applied? Or, that necessitates to bring up a different process (on another port)?

Can you please advise?

```
[[inputs.jti_openconfig_telemetry]]
        servers = ["router-1:57400", "router-2:57400"]
        sensors = [
                "interfaces /interfaces/",
                "cpu /junos/system/cpu/memory/",
        ]
```

**Comment by ssoroka** [comment]
You should be able to drop specific fields with [modifiers](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#modifiers) on the input, a new processor (eg processors.override), or the output. See fielddrop or tagexclude.

**Comment by nskalis** [comment]
thanks @ssoroka, assuming that we filter everything out by using a wildcard `*`, will Telegraf initiate the request on (the problematic) `router-2` in our scenario? 

In other words, I don't understand this part
>  If all fields are removed the metric is removed.

the metric (of a sensor x) is removed from processing that or from requesting that?

**Comment by danielnelson** [comment]
When you use the metric filtering options the data retrieved from the device is not modified, the metric filtering happens later.  This might be okay if the changes are minor but for the best performance you should define multiple plugin instances, one per device configuration.  If the plugin is a listening plugin (only cisco_telemetry_mdt) this does mean another listening port.

**Comment by nskalis** [comment]
thank you!
