### ISSUE TITLE
x509 Cert Plugin

### ISSUE THREAD

**Issue by Nurlan199206** [influxdata/telegraf#7769]
Hi.

i am absolutely newbie in influxDB...

help me pls properly to calculate certificate date expiration in grafana.

its show 1970 year.

![Снимок экрана 2020-07-01 в 20 05 21](https://user-images.githubusercontent.com/22808731/86253439-5e6fc480-bbd6-11ea-8c57-f16e9743bade.png)

**Comment by sjwang90** [comment]
Hi @Nurlan199206! Do you think you could post this question on our [Community Page](https://community.influxdata.com/) or our [Community Slack](https://influxcommunity.slack.com/).  This issues repo is to address Telegraf bugs and/or feature requests.
