### ISSUE TITLE
http plugin fail - when response body message from url 404 error and not json format.

### ISSUE THREAD

**Issue by kai00000** [influxdata/telegraf#7771]
Hey Guys,
i'm experiencing issues when trying to parse url with a response body message not json in my case 404 error page not found.
How do you process this type of issues for input_http?

### Relevant telegraf.conf:
```
[[[inputs.http]]
  urls = ["http://localhost:9101/test/status/","http://localhost:9102/test/status/"]
    method = "GET"
    json_string_fields = ["station","status","message","version","build_timestamp"]
    data_format = "json"
```

### System info:

Telegraf 1.13.3

### Steps to reproduce:
1. Edit config  and add Url links and some which gives error 404 or some other error.
2. restart service
3. telegraf --config /bigdisk0/telegraf/etc/telegraf.conf -test

### Expected behavior:

All running fine, no plugin errors, influexdb data updated.

### Actual behavior:

2020-07-01T14:28:44Z E! [inputs.http] Error in plugin: [url=http://localhost:9102/test/status/]: received status code 404 (Not Found), expected any value out of [200]

2020-07-01T14:28:44Z E! [telegraf] Error running agent: One or more input plugins had an error

### Additional info:
How do you ignore such kind of errors and guarantee all data is updated at influexdb?

**Comment by danielnelson** [comment]
You can add the status code to the list of success status codes: `success_status_codes = [200, 404]`, if you do this then you will need to parse the body of the of the 404 response using the `data_format`.

**Comment by kai00000** [comment]
@danielnelson 
i have tried but not sure how to parse it because it is not json response anymore.
```
2020-07-02T08:13:16Z E! [inputs.http] Error in plugin: [url=http://localhost:9102/test/status/]: invalid character '<' looking for beginning of value

2020-07-02T08:13:16Z E! [telegraf] Error running agent: One or more input plugins had an error
```

```curl http://localhost:9102/test/status/
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><
```
Do you know how can i parse something like above lines.. it is not json?

**Comment by danielnelson** [comment]
Can you elaborate on what your desired behavior would be?  No logging and just ignore the data?  Some way to parse the error response body using a secondary parser?  Some other method?

**Comment by kai00000** [comment]
Yes, i'm trying to parse response body but as you can see if it is not json format it has been failing and breaking telegraf plugin work.

**Comment by sjwang90** [comment]
@kai00000 have you been able to resolve this issue?

**Comment by stephanie-engel** [comment]
@kai00000 
I was able to get 404 responses into InfluxDB via the[ http_response plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_response/README.md) (not the `http` plugin).

For example, with this relevant `telegraf.conf`:
```
[[inputs.http_response]]
  urls = ["https://github.com/badpath"]
    method = "GET"
```
When I select my specific bucket, I can eventually filter down to the `result` `GET` for `https://github.com/badpath`:

![Screen Shot 2020-10-26 at 12 55 37 PM](https://user-images.githubusercontent.com/22456349/97209630-95bc3f80-178a-11eb-8717-fe4a07ac41c7.png)


I'm going to close this issue, but please feel free to reach back out if you have any other questions!
