### ISSUE TITLE
[System Input Plugin] Name + Tags not distinct for system metrics

### ISSUE THREAD

**Issue by proddata** [influxdata/telegraf#7772]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
According to the documentation, a metric should be able to be identified by the tags
> Tags: Key/Value string pairs and usually used to identify the metric.

### Current behavior:
Right now the system plugin (input) produces 3 different metrics with the same **name** + **tag** combination

```
> system,host=tyrion load1=3.72,load5=2.4,load15=2.1,n_users=3i,n_cpus=4i 1483964144000000000
> system,host=tyrion uptime=1249632i 1483964144000000000
> system,host=tyrion uptime_format="14 days, 11:07" 1483964144000000000
```

### Desired behavior:
Publish all metrics at once, or provide a tag to differentiate between metrics
```
> system,host=tyrion,info=load load1=3.72,load5=2.4,load15=2.1,n_users=3i,n_cpus=4i,uptime=1249632i, uptime_format="14 days, 11:07" 1483964144000000000
```
or

```
> system,host=tyrion,type=load load1=3.72,load5=2.4,load15=2.1,n_users=3i,n_cpus=4i 1483964144000000000
> system,host=tyrion,type=uptime uptime=1249632i 1483964144000000000
> system,host=tyrion,type=uptime_format uptime_format="14 days, 11:07" 1483964144000000000
```

### Use case: 
Otherwise name+tags+timestamp are not unique, which makes further processing cumbersome

**Comment by danielnelson** [comment]
We should probably reword these docs to indicate that the tags usually identify the resource that the metric is about.  However, the tags are not meant to be fully unique, you should also use the field key to identify the individual samples.  Once it hits the database this data will be merged, and can be used as if it were never separate.

However, I am aware that it causes difficulties processing the data in Telegraf and we are looking to eventually merge these three lines, the split is an artifact of the way Telegraf currently stores type metadata about the different fields.

related: #5684 #7528 #5701

**Comment by proddata** [comment]
Hi @sspaink 

Thanks for coming back :) I recently looked into this also for other cases and think we gonna implement an object merge https://github.com/crate/crate/issues/12979 soon, which would allow to also input the above mention data as is, with a little adjustment in the output plugin.  However I still think this would be nice, as it minimizes the number of writes.

**Comment by sspaink** [comment]
@proddata I've created a pull request with a possible solution: https://github.com/influxdata/telegraf/pull/12045

Mind looking it over to make sure its what you had in mind? You can test it out by using the artifacts posted by the Tiger Bot

**Comment by sspaink** [comment]
@proddata it was pointed out to me we do have the merge aggregator plugin that could solve this without code changes: https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge

Does that work for you?
