### ISSUE TITLE
Fatek PLC Modbus not reading all coils status

### ISSUE THREAD

**Issue by TomGdy** [influxdata/telegraf#7774]
Good morning,
I have some issue to report that not sure if it related to telegraf or limitation is on my plc or modbus itself.
I am trying to read about 40 coils from my plc with the below configuration:
```
[[inputs.modbus]]
name = "Device"
slave_id = 5
timeout = "2s"
# busy_retries = 2
# busy_retries_wait = "100ms"
controller = "tcp://192.168.1.60:502"
 coils = [
........
```
When running 
telegraf -config telegraf.conf -input-filter modbus -test
I can read all coils status but half coils remains 0 all the time even if in PLC they are 1. Other half is reading correct.
Any suggestion please?

**Comment by ssoroka** [comment]
Just a guess, but your timeout might be too short?

**Comment by TomGdy** [comment]
Hi Steven and thcx for feedback, I have played with timeout, increased up to 20 sec but still the same. in addition played with metric settings in general telegraf settings but no sucess at all :-(

**Comment by ssoroka** [comment]
start with a 5m timeout and work down from there if it works, or start from a couple of coils and work up until you find a max. Also is it possible there's one bad entry in the list? You should be able to find this with a manual binary search through the list.

**Comment by TomGdy** [comment]
Hi and thanks for your feedback,
so far have tried with 5m and down to 1 m with no difference.
max i can read is 16 coils. there is nothing wrong with  my list as i can read them individualy.

**Comment by sjwang90** [comment]
Hi @TomGdy, does this bug still exist?
