### ISSUE TITLE
use HOST_MOUNT_PREFIX in other plugins than `disk`

### ISSUE THREAD

**Issue by rdxmb** [influxdata/telegraf#7776]
### Proposal:

It would be great to use `HOST_MOUNT_PREFIX` in other plugins than `disk`, e.g. in x509_cert or just everywhere, where paths are defined.

### Current behavior:

`sources = ["/host/etc/kubernetes/pki/ca.crt","/host/etc/kubernetes/pki/apiserver-etcd-client.crt","/host/etc/kubernetes/pki/apiserver-kubelet-client.crt","/host/etc/kubernetes/pki/apiserver.crt","/host/etc/kubernetes/pki/front-proxy-ca.crt","/host/etc/kubernetes/pki/front-proxy-client.crt","/host/etc/kubernetes/pki/etcd/ca.crt","/host/etc/kubernetes/pki/etcd/healthcheck-client.crt","/host/etc/kubernetes/pki/etcd/peer.crt","/host/etc/kubernetes/pki/etcd/server.crt"]`

`HOST_MOUNT_PREFIX=/host`

results in:

`telegraf --config /etc/telegraf/telegraf.conf --input-filter x509_cert --test `

> x509_cert,common_name=eins@1572455793,issuer_common_name=eins-ca@1572455792,public_key_algorithm=RSA,san=eins,serial_number=2,signature_algorithm=SHA256-RSA,source=/host/var/lib/kubelet/pki/kubelet.crt,type=docker,verification=invalid age=21247722i,enddate=1603988192i,expiry=10288277i,startdate=1572452192i,verification_code=1i,verification_error="x509: certificate signed by unknown authority" 1593699915000000000

### Desired behavior:

The `/host` of the path should be stripped, like it is done in https://github.com/influxdata/telegraf/blob/release-1.14/plugins/inputs/disk/README.md#docker-container

> x509_cert,common_name=eins@1572455793,issuer_common_name=eins-ca@1572455792,public_key_algorithm=RSA,san=eins,serial_number=2,signature_algorithm=SHA256-RSA,source=/var/lib/kubelet/pki/kubelet.crt,type=docker,verification=invalid age=21247722i,enddate=1603988192i,expiry=10288277i,startdate=1572452192i,verification_code=1i,verification_error="x509: certificate signed by unknown authority" 1593699915000000000

### Use case: 

This would help to have the absolute paths in GUI and/or alerting without stripping the prefix at an external place.

**Comment by danielnelson** [comment]
In 1.15.0, we will be adding the [filepath][] processor that I think will be helpful for this.  Can you try out one of the 
[nightly builds](https://github.com/influxdata/telegraf#nightly-builds) and see if it will meet your needs?

[filepath]: https://github.com/influxdata/telegraf/tree/master/plugins/processors/filepath#filepath-processor-plugin

**Comment by rdxmb** [comment]
sounds good! Are there also docker images with the nightly builds?

**Comment by rdxmb** [comment]
As a workaround, I `/etc/kubernetes` and `/var/lib/kubelet` with 1:1 naming into the docker container.
