### ISSUE TITLE
Add support for kubernetes jobs

### ISSUE THREAD

**Issue by carlosv-ukg** [influxdata/telegraf#7779]
## kubernetes Jobs

Opening a feature request kicks off a discussion.

### Proposal:

Add functionality to generate metrics derived from the state of the [job](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#job-v1-batch) resource to the [kube_inventory input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kube_inventory). This could be a new metrics like:
- kubernetes_job
   - tags:
      - job_name
      - namespace
      - selector (*varies)
   - fields
      - started
      - completed
      - failed
      - succeeded

### Current behavior:

Job metrics are not currently ingested.

### Desired behavior:

Ingest job metrics.

### Use case

By bringing in job metrics into influx, a user can:
1. Set up alerting when jobs start failing which allows users know about issues as soon as possible without having to monitor jobs.
2. See the health of jobs over time and see if there is an issue with applications or infrastructure.

**Comment by carlosv-usg** [comment]
I believe this will also require a change to ericchiang/k8s. I've created ericchiang/k8s/#126.

**Comment by ssoroka** [comment]
I really like this. I'd love to see it.

**Comment by pspgit** [comment]
I can't find it in the latest release. Was it ever merged?
