### ISSUE TITLE
cisco_telemetry_gnmi fails intermitently

### ISSUE THREAD

**Issue by sergiodj** [influxdata/telegraf#7781]
### System info:

Telegraf 1.14.4
Ubuntu Groovy
go 2:1.14~2

### Steps to reproduce:

1. Run `go test -short`
2. See `cisco_telemetry_gnmi` test fail

### Expected behavior:

Test passes.

### Actual behavior:

Test fails with:

```--- FAIL: TestWaitError (0.01s)
    cisco_telemetry_gnmi_test.go:100: 
        	Error Trace:	cisco_telemetry_gnmi_test.go:100
        	Error:      	"[failed to send subscription request: EOF]" does not contain "aborted GNMI subscription: rpc error: code = Unknown desc = testerror"
        	Test:       	TestWaitError
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:35271 established
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:35271 closed
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:44458 established
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:44458 closed
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:35777 established
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:35777 closed
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:45262 established
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:45262 closed
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:45262 established
2020/07/02 21:16:10 D! [] Connection to GNMI device 127.0.0.1:45262 closed
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/cisco_telemetry_gnmi	0.085s
```

### Additional info:

The failure doesn't happen every time.  I also noticed that it usually happens on ARM (armhf, aarch64) architectures; I don't remember if this ever happened on amd64.

In order to use telegraf, I'm bundling everything into the directory (with `go mod vendor`), and then I'm running the test with `go test -mod=vendor -short`).

Unfortunately, I haven't been able to reproduce this locally yet, only on a remote build system.  For that reason, I don't have access to the full logs and such.  Also, as I said, this is a racy failure, so it's not every time that I can reproduce it.  Having said that, I'll be happy to help you diagnose it.  Thanks!

**Comment by sergiodj** [comment]
The problem also manifests on s390x, btw.

**Comment by sjwang90** [comment]
@sergiodj Are you still seeing this bug?

**Comment by sergiodj** [comment]
I don't remember seeing this bug lately, but then again it's been a while since I've reported it.  I will keep an eye on future builds and see if this is still an issue.
