### ISSUE TITLE
Global tags not been attached to all measurement rows

### ISSUE THREAD

**Issue by santos-lucas** [influxdata/telegraf#7785]
### Relevant telegraf.conf:

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  test = "change"
  jobid = "${jobid}"
  username = "${username}"
```
(vm) [root@c-1 ~]$ cat /etc/default/telegraf
jobid=null
account=null
username=null
uid=null
state=null

### System info:
(vm) [root@c-1 ~]$ telegraf --version
Telegraf 1.11.4 (git: HEAD d9ca76e4)

### Expected behavior:
The expected behavior was that all the values got the tags like the highlited one on the actual behavior.

### Actual behavior:
```
> SELECT * FROM cpu GROUP BY * ORDER BY DESC LIMIT 1
name: cpu
tags: cpu=cpu0, host=mngt0-1, jobid=, test=, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- ------------- ----------- ------------        ----------
1593795240000000000 0           0                99.68186638389352 0            0         0          0             0           0.10604453870625272 0.2120890774125431

name: cpu
**tags: cpu=cpu0, host=c-1, jobid=null, test=change, username=null**
time                usage_guest usage_guest_nice usage_idle usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system usage_user
----                ----------- ---------------- ---------- ------------ --------- ---------- ------------- ----------- ------------ ----------
1593795240000000000 0           0                100        0            0         0          0             0           0            0

name: cpu
tags: cpu=cpu0, host=c-1, jobid=, test=hello, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq       usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- -------------       ----------- ------------        ----------
1593800480000000000 0           0                99.59959959923566 0            0         0          0.10010010009776941 0           0.30030030029330823 0

name: cpu
tags: cpu=cpu0, host=c-1, jobid=, test=, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- ------------- ----------- ------------        ----------
1593634290000000000 0           0                99.59636730538192 0            0         0          0             0           0.40363269424179776 0

name: cpu
tags: cpu=cpu-total, host=mngt0-1, jobid=, test=, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- ------------- ----------- ------------        ----------
1593795240000000000 0           0                99.68186638389352 0            0         0          0             0           0.10604453870625272 0.2120890774125431

name: cpu
tags: cpu=cpu-total, host=c-1, jobid=null, test=change, username=null
time                usage_guest usage_guest_nice usage_idle usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system usage_user
----                ----------- ---------------- ---------- ------------ --------- ---------- ------------- ----------- ------------ ----------
1593795240000000000 0           0                100        0            0         0          0             0           0            0

name: cpu
tags: cpu=cpu-total, host=c-1, jobid=, test=hello, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq       usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- -------------       ----------- ------------        ----------
1593800480000000000 0           0                99.59959959923566 0            0         0          0.10010010009776941 0           0.30030030029330823 0

name: cpu
tags: cpu=cpu-total, host=c-1, jobid=, test=, username=
time                usage_guest usage_guest_nice usage_idle        usage_iowait usage_irq usage_nice usage_softirq usage_steal usage_system        usage_user
----                ----------- ---------------- ----------        ------------ --------- ---------- ------------- ----------- ------------        ----------
1593634290000000000 0           0                99.59636730538192 0            0         0          0             0           0.40363269424179776 0
```
Am I missing something, or that is really a bug?

**Comment by danielnelson** [comment]
Is there any chance you have two Telegraf instances reporting for host=c-1, or even two hosts named `c-1`?  

I would try adding a `file` output logging only the `cpu` measurement and monitor this for a bit, does it occur in the output from this plugin?
```
[[outputs.file]]
  files = ["/tmp/telegraf-cpu.txt"]
  namepass = ["cpu"]
```

**Comment by santos-lucas** [comment]
No, I don't have two instances or two hosts with the same name.

I did add the file output, and in there all the lines had the correct parameters, just don't know where rows on influxdb whithout the flags are comming from.

**Comment by santos-lucas** [comment]
And, I did some more tests and I think that what I was trying will not work on this way. There is an way to setup Global tags dinamically?

**Comment by danielnelson** [comment]
Take a look at the [execd processor][execd] and the [starlark processor][starlark], both of which will be part of the 1.15.0 release.  Would also be interested to hear more about your use case and any ideas for how it might be implemented.

[execd]: https://github.com/influxdata/telegraf/tree/master/plugins/processors/execd
[starlark]: https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark

**Comment by santos-lucas** [comment]
Sure, My use case is to add job metadata to the metrics. so I can associate the metrics with running jobs. So, before release 1.15.0 there is no other way to do it?  the execd seems good if I can turn some return to a global tag.

I was seem about processors.converter, but I did not see a way to turn my measurement fields into global tags.

**Comment by danielnelson** [comment]
Where is the job metadata retrieved from?

**Comment by santos-lucas** [comment]
From a bash script, I can use this as an inputs.exec to get it as a measurement, but I`m trying to make the fields as global tags.

**Comment by danielnelson** [comment]
I think you will want the execd processor, you would add the new tags to each metric as they pass though.  Since every metric will pass though the processor they function the same as global tags.

If you wanted to do this in 1.14 or older, you would need to run your script outside of Telegraf and have it generate a toml configuration file with the global tags section.  Then, if the tags change, you would need to have the script send a SIGHUP to Telegraf to get it to reload the configuration files.

**Comment by santos-lucas** [comment]
If you wanted to do this in 1.14 or older, you would need to run your script outside of Telegraf and have it generate a toml configuration file with the global tags section. Then, if the tags change, you would need to have the script send a SIGHUP to Telegraf to get it to reload the configuration files.

Yes, I was thinking in something like this as well, reload the deamon when the variables change. and just put this on /etc/default/telegraf how I was trying to do in the first place. Was trying to avoid this reload.

But, I think I will do this until the 1.15 be available. Thanks a lot for the help @danielnelson
