### ISSUE TITLE
Implement tag injector processor plugin

### ISSUE THREAD

**Issue by yolkhovyy** [influxdata/telegraf#7788]
## Feature Request

Implement a tag injector processor plugin which would inject extra tags based on the existing tag. 

Working prototype is here: https://github.com/yolkhovyy/telegraf/tree/feature/taginjector-processor/plugins/processors/tag_injector

### Proposal:

The tag injector processor plugin would inject extra tags based on the existing tags. 

Consider the following IoT case:

- Incoming metric has a tag identifying the source device, say it's a mac address: temperature,**device_id=01:23:45:67:89:ab** 1593876341000000000 22.0
- The device_id tag might be used for binding metrics metadata, e.g. measurements units, or device serial number, location
- This looks fine but might result in rather complicated maintenance scenarios when the device is replaced, and the tag changes
- Tag injection might help to solve this problem - we could inject a tag which identifies the device independently of its physical properties (the mac address), e.g.
temperature,**device_id=01:23:45:67:89:ab**,**idevice_id=9972e89b-7880-4b84-bb0a-7a7a8a5d3ae3** 1593876341000000000 22.0
- After replacing the device and updating the tag injector database the metric would still have the same idevice_id:
temperature,**device_id=12:34:56:78:9a:bc**,**idevice_id=9972e89b-7880-4b84-bb0a-7a7a8a5d3ae3** 1593876341000000000 22.0
- The **idevice_id** would still identify the same metric although the physical device is replaced 

The tag injector plugin prototype mentioned above injects tags by 1-to-many principle and relies on the following database:

CREATE TABLE in_tags
(
    id INT(11) NOT NULL AUTO_INCREMENT,
    tag_name VARCHAR(255) NOT NULL,
    tag_value VARCHAR(255) NOT NULL,
    CONSTRAINT in_tags_pk PRIMARY KEY (id)
);

CREATE TABLE out_tags
(
    id INT(11) NOT NULL AUTO_INCREMENT,
    in_tag_id INT(11) NOT NULL REFERENCES in_tags(id),
    tag_name VARCHAR(255) NOT NULL,
    tag_value VARCHAR(255) NOT NULL,
    CONSTRAINT out_tags_pk PRIMARY KEY (id)
);

The plugin configuration in its simplest from:

[[processors.tag_injector]]
  order = 2
  driver_name = "mysql"
  data_source_name = "user:password@/tag_injector?charset=utf8mb4&collation=utf8mb4_unicode_ci"

Actual in-out tag mapping would defined by the application, and stored in the database.

### Current behavior:

No tag injection possible

### Desired behavior:

Tag injector processor plugin that would inject extra tags based on the existing tags

### Use case:

IoT scenarios:
- Device replacement
- Metric enrichment with metadata independent of physical device properties such as mac addresses
- Metric aggregation based on the injected tags, e.g. inject a location tag which might group multiple metrics

**Comment by ssoroka** [comment]
This looks a little too custom to be a plugin, but we've recently added a lot of flexibility to customize how processors work. You can now create your own plugin in any language (with any dependencies) using [processors.execd](https://github.com/influxdata/telegraf/tree/master/plugins/processors/execd). This seems like exactly what you want here.

**Comment by yolkhovyy** [comment]
> This looks a little too custom to be a plugin, but we've recently added a lot of flexibility to customize how processors work. You can now create your own plugin in any language (with any dependencies) using [processors.execd](https://github.com/influxdata/telegraf/tree/master/plugins/processors/execd). This seems like exactly what you want here.

It's a nice approach indeed - is it not possible to avoid starting the process every time a metric arrives? How would the execd be used in a containerized environment?

**Comment by ssoroka** [comment]
execd starts the process and leaves it running. In the case of processors.execd, it streams record to the process's stdin and reads them back from the process's stdout. Because Telegraf/execd handles starting the process for you, all you need for a containerized environment is the binary available on the filesystem, and Telegraf needs to know the path to it.

**Comment by ssoroka** [comment]
Going to close the issue, but feel free to ask more questions.

**Comment by yolkhovyy** [comment]
Thinking containers - what about making the process listen/publish on a port iso stdin/stdout?

**Comment by ssoroka** [comment]
That would be significantly more complicated. Keep in mind process pipes are first-class and closing a pipe causes the correct process to finish reading the buffer and close appropriately. You get really nice behavior from this, and obvious ways to signal shutdown without creating a new arbitrary protocol.
