### ISSUE TITLE
Starlark Processor: Access to previous metrics, store variables

### ISSUE THREAD

**Issue by victornet** [influxdata/telegraf#7793]
## Feature Request

Hi,

this is regarding the new starlark processor plugin, https://github.com/influxdata/telegraf/issues/7194

I would like to calculate the difference between two metrics (previous and current), see https://github.com/influxdata/telegraf/issues/6870

In the readme is mentioned, that the global context is frozen, fileio etc is not possible. 

So, is there a possibility to store variables not using the global context? Or read previous values?

### Proposal:

Store last value in variable to get difference of metric, detect overflows in values, calculate e.g. response time for disk io, based on timing and number of operations.

### Current behavior:

Not possible, global context is frozen.

### Desired behavior:

Read/write variables in global context or store previous metric. 

### Use case:

Gather disk response times for read and write operations.

**Comment by danielnelson** [comment]
It is not possible right now, but we might allow it in the future after we gain a bit more experience with Starlark.  You will be able to use the `execd` processor, also new in 1.15, to do this.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/influxdata/telegraf/pull/8447

**Comment by ssoroka** [comment]
merged in https://github.com/influxdata/telegraf/pull/8447
