### ISSUE TITLE
HA SQL server services

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7794]
Hi, 

We are looking for monitoring for HA SQL server services, please let me know if it is possible through telegraf.

SQL service are running on 2 server (Primary & Backup), and Have one virtual IP. So If SQL service goes down on both server, then only alert will generate.

**Comment by adrianlzt** [comment]
One simple solution is to check from both servers the VIP.

**Comment by danielnelson** [comment]
@rguptarg If you have follow up questions can you post over at the [InfluxData Community](https://community.influxdata.com) site.
