### ISSUE TITLE
Behaviour for double data point updating through UDP listener

### ISSUE THREAD

**Issue by sg-jorrit** [influxdata/telegraf#7802]
Hello there. Hope someone can help me with this question.

We're using Telegraf's UDP listener input to receive metrics from OpenResty Lua in Influx lineproto format and send this to an InfluxDB output. We leverage the natural de-doubling done by Influx if all tags and timestamp match to update certain measurement fields, but noticed that sometimes updates done within the same batch of measurements get lost, leaving only the first version of the same metric.

I suppose my question is what the actual behaviour would be using the UDP listener input plugin, how it deals with double data points within the same batch, and whether it would be possible to control this behaviour; e.g. is it possible to set it to fifo or lifo according to place in the buffer, or maybe even use processors to make sure the datapoint that is written is actually containing the last updated values?

**Comment by danielnelson** [comment]
I think you are running into this issue #5633, the batches we are writing are in descending order causing the earlier point to override the later.  Let's merge this issue with #5633.
