### ISSUE TITLE
MongoDB, add "pages written from cache"

### ISSUE THREAD

**Issue by GeeBee93** [influxdata/telegraf#7803]
### Proposal:
Currently the mongodb input supports already a lot of different statistics about the performance of an instance. However, the attribute "pages written from cache" is not implemented. Even mongodb says in their documentation (see: https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.wiredTiger.cache.pages-written-from-cache):     Number of pages written from the cache. wiredTiger.cache.pages written from cache with the wiredTiger.cache.pages read into cache can provide an overview of the I/O activity.

### Current behavior:
"wiredTiger.cache.pages written from cache" is not gathered at all.

### Desired behavior:
"wiredTiger.cache.pages written from cache" would be available for further database performance analysis.

### Use case: 
As already stated in the documentation it would be great to have that attribute to get a better overview of I/O activity of a mongodb instance.

Thank you! :-)

**Comment by GeeBee93** [comment]
If somebody is interested, I forked telegraf and implemented the feature: https://github.com/GeeBee93/telegraf/commit/db1b20b3d6a1cfcef2446e05fe943c52efa991c9

I would like to create a PR, but I am in the final steps of my master theses and really busy. However, just feel free and use my repo. 

Awesome work telegraf - thank you so much!

**Comment by vikkyomkar** [comment]
I will look into this issue

**Comment by reimda** [comment]
Looks like #7870 added this but didn't automatically close it.
