### ISSUE TITLE
Mention in the docs that JSON plugin will not be able to parse anything other than number and strings

### ISSUE THREAD

**Issue by vivektiwary** [influxdata/telegraf#7807]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: Add in the docs stating that if the response is of format
```
 { "details": {"desc": "moved"}, "status" : "up"}
```
and if `tag_keys` and `json_string_fields` is blank, then JSON plugin will not able to parse it and it will error out.

### Current behavior:
It says could not resolve headers in specified time.
### Desired behavior:
It should say that it was not able to parse the response as it did not contain any numerical field and other fields have not been mentioned using `tag_keys` or `json_string_fields`.
### Use case: 
It really helps in debugging, specially for people new to influx and telegraf.

**Comment by danielnelson** [comment]
This JSON document should parse with no parser settting, if you fix the issue of `status` not being quoted.  The only item collected will be the 301 code.

> It says could not resolve headers in specified time.

I think this might be a timeout in the input plugin, are you using the http input?

**Comment by vivektiwary** [comment]
Status is in quotes, it was a mistake while writing it. I have updated the issue with exact response. Now there is no numeric field. What should telegraf do.

>I think this might be a timeout in the input plugin, are you using the http input?

Yes, I am using it.

**Comment by danielnelson** [comment]
In this case Telegraf will not produce any data since the JSON parser does not collect strings by default.  If you set `json_string_fields = ["*"]` then you should get:
```
http details_desc="moved",status="up"
```

**Comment by danielnelson** [comment]
Let me know if you still are having issues.
