### ISSUE TITLE
[QUESTION] backpressure mechanism

### ISSUE THREAD

**Issue by nskalis** [influxdata/telegraf#7809]
Hi,

when having a look at

- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_gnmi
- https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_mdt

What I would like to ask you is:

In a scenario that we set the interval to `interval=10s` and the list of sensors take `15s` to be gathered for reason x, y, z.
So, 
at `t1`, a bundle of sensors are requested from device `router-1`,
at `t1+interval` will there be another request for the same bundle of sensors?

What will actually happen? What are the option to workaround such a scenario?

**Comment by ssoroka** [comment]
collection `t1+interval` will be skipped and a log message will be written to the logs that collection tool longer than the collection interval, which is just informational. The next collection will be `t1+2*interval`. In this specific case, you could consider splitting the sensors across multiple inputs, or increasing the interval.

**Comment by nskalis** [comment]
thank you

**Comment by ssoroka** [comment]
actually these plugins act a little differently, I'm going to have to check that and get back to you.

**Comment by nskalis** [comment]
@ssoroka , please excuse my ignorance about the go lang, would you be so kind to advise/describe how these plugins behave in the above scenario?

**Comment by ssoroka** [comment]
So these plugins don't do anything on the collection interval, they ignore it completely, and instead subscribe to the data stream, passing metrics on as soon as they're available. The sender service will experience back-pressure when Telegraf reaches the maximum speed at which it can ingest the subscribed-to metrics.
