### ISSUE TITLE
[Bug report] I am getting 400 error from "inputs.jolokia2_agent" during fetching connectors_http from undertow subsystems through Telegraf agent

### ISSUE THREAD

**Issue by razzrsi** [influxdata/telegraf#7812]
### Relevant telegraf.conf:
here below the jolokia configuration mentioned in telegraf agent config file:

```
# # Read JMX metrics from a Jolokia REST agent endpoint
 [[inputs.jolokia2_agent]]
#   # default_tag_prefix      = ""
#   # default_field_prefix    = ""
#   # default_field_separator = "."
#
#   # Add agents URLs to query
   urls = ["http://10.67.192.44:8778/jolokia"]

    # name_prefix = "jboss."
#   # username = ""
#   # password = ""
#   # response_timeout = "5s"
#
#   ## Optional TLS config
 #tls_ca   = "/var/private/ca.pem"
 #tls_cert = "/var/private/client.pem"
 #tls_key  = "/var/private/client-key.pem"
#   # insecure_skip_verify = false
#
#   ## Add metrics to read
   [[inputs.jolokia2_agent.metric]]
     name  = "java_runtime"
     mbean = "java.lang:type=Runtime"
     paths = ["Uptime"]

[[inputs.jolokia2_agent.metric]]
    name  = "jvm_memory"
    mbean = "java.lang:type=Memory"
    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

  [[inputs.jolokia2_agent.metric]]
    name     = "jvm_garbage_collector"
    mbean    = "java.lang:name=*,type=GarbageCollector"
    paths    = ["CollectionTime", "CollectionCount"]
    tag_keys = ["name"]

  [[inputs.jolokia2_agent.metric]]
    name       = "jvm_memory_pool"
    mbean      = "java.lang:name=*,type=MemoryPool"
    paths      = ["Usage", "PeakUsage", "CollectionUsage"]
    tag_keys   = ["name"]
    tag_prefix = "pool_"

 [[inputs.jolokia2_agent.metric]]
    name  = "java_threading"
    mbean = "java.lang:type=Threading"
    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]

 [[inputs.jolokia2_agent.metric]]
    name = "java_last_garbage_collection"
    mbean = "java.lang:name=*,type=GarbageCollector"
    paths = ["LastGcInfo"]
    tag_keys = ["name"]

 [[inputs.jolokia2_agent.metric]]
   name = "java_class_loading"
   mbean = "java.lang:type=ClassLoading"
   paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]

 [[inputs.jolokia2_agent.metric]]
   name     = "connectors_http"
   mbean    = "jboss.as:https-listener=*,server=*,subsystem=undertow"
   paths    = ["bytesReceived","bytesSent","errorCount","requestCount"]
  tag_keys = ["server","https-listener"]


[[inputs.jolokia2_agent.metric]]
   name     = "connectors_http"
   mbean    = "jboss.as:http-listener=*,server=*,subsystem=undertow"
   paths    = ["bytesReceived","bytesSent","errorCount","requestCount"]
   tag_keys = ["server","http-listener"]


 [[inputs.jolokia2_agent.metric]]
    name     = "datasource_jdbc"
    mbean    = "jboss.as:data-source=*,statistics=jdbc,subsystem=datasources"
    paths    = ["PreparedStatementCacheAccessCount","PreparedStatementCacheHitCount","PreparedStatementCacheMissCount"]
    tag_keys = ["data-source"]


 [[inputs.jolokia2_agent.metric]]
    name     = "datasource_pool"
    mbean    = "jboss.as:data-source=*,statistics=pool,subsystem=datasources"
    paths    = ["AvailableCount","ActiveCount","MaxUsedCount"]
    tag_keys = ["data-source"]
```
### System info:

Telegraf Version: 1.14.3
Jolokia agent version : 1.6.0
O.S ; Redhat 7

### Expected behavior:

Data should gather and stored at Influxdb with respective collection name.

### Actual behavior:

Always getting error :  E! [inputs.jolokia2_agent] Error in plugin: Unexpected status in response from target : 400

### Additional info:

**Note : All key are working fine except undertow details. Means gathered matrices and stored in influxdb **

**Comment by ssoroka** [comment]
If you curl `http://10.67.192.44:8778/jolokia` directly from the command line on the target machine, what kind of response do you get?

**Comment by razzrsi** [comment]
> If you curl `http://10.67.192.44:8778/jolokia` directly from the command line on the target machine, what kind of response do you get?

Hi,

I am getting below response. Please have a look and suggest me :

curl http://10.67.192.44:8778/jolokia/

{"request":{"type":"version"},"value":{"agent":"1.6.0","protocol":"7.2","config":{"listenForHttpService":"true","maxCollectionSize":"0","authIgnoreCerts":"false","agentId":"10.67.192.44-19057-45ee12a7-jvm","debug":"false","agentType":"jvm","policyLocation":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","serializeException":"false","mimeType":"text\/plain","maxDepth":"15","authMode":"basic","discoveryEnabled":"true","streaming":"true","canonicalNaming":"true","historyMaxEntries":"10","allowErrorDetails":"true","allowDnsReverseLookup":"true","realm":"jolokia","includeStackTrace":"true","maxObjects":"0","useRestrictorService":"false","debugMaxEntries":"100"},"info":{"product":"jboss","vendor":"RedHat","version":"8.2.1.Final"}},"timestamp":1594616638,"status":200}

**Comment by razzrsi** [comment]
Hi @ssoroka ,

Any update on my above comments ??? Please help me out.

**Comment by ssoroka** [comment]
That sounds like a really broken web server. the trailing `/` should not make any difference. If you can't get the response with curl, the problem is with the Jolokia server, not within Telegraf.

**Comment by razzrsi** [comment]
Ok thanks for guiding me. If trailing / is culprit, then how other jolokia inputs are working fine, means able to get response from target server. Only issue with Undertow subsystems for **"connectors_http"**. I had also checked with trailing / on  **urls = ["http://10.67.192.44:8778/jolokia/"]** on telegraf config but output is same. Even also I have contacted with Jolokia team, there is no issue on jolokia side as confirmed by them.

Please suggest......eagerly waiting for your support.

**Comment by ssoroka** [comment]
So all this message is saying is that one of your requests is bad. I suggest commenting out all your `inputs.jolokia2_agent.metric` sections and adding them back in one at a time until you find the offending one. I don't believe this is a bug in Telegraf, as it's just relaying your request as is.

**Comment by ssoroka** [comment]
I added some more debug context to the nightly build that will help you debug this, but it will just point to the offending input metric, which you could also find by enabling one config input metric at a time.

**Comment by himuura** [comment]
Think i might have found the bug. Notice the * on the server= and http(s)-listener:
[[inputs.jolokia2_agent.metric]]
name = "connectors_http"
mbean = "jboss.as:https-listener=,server=,subsystem=undertow"
paths = ["bytesReceived","bytesSent","errorCount","requestCount"]
tag_keys = ["server","https-listener"]

[[inputs.jolokia2_agent.metric]]
name = "connectors_http"
mbean = "jboss.as:http-listener=,server=,subsystem=undertow"
paths = ["bytesReceived","bytesSent","errorCount","requestCount"]
tag_keys = ["server","http-listener"]

In my case, adding the * started pouring data onto my grafana dashboard. I can now see connection statistics on Grafana.
