### ISSUE TITLE
elasticsearch output plugin

### ISSUE THREAD

**Issue by lmx1989219** [influxdata/telegraf#782]
recently,i use telegraf collect metrics of ngx/redis/mysql to influx.
but i want if should be write to elasticsearch directly

**Comment by sparrc** [comment]
So is this a feature request for an elasticsearch output plugin?

**Comment by lmx1989219** [comment]
yes

**Comment by berglh** [comment]
I'd love to have this option as well

**Comment by menardorama** [comment]
+1

**Comment by ndopicokeedio** [comment]
+1

**Comment by rvrignaud** [comment]
+1

**Comment by menardorama** [comment]
Does the recent json serializer help to produce an elasticsearch output plugin ?

**Comment by rvrignaud** [comment]
+1

**Comment by atlante77** [comment]
+1

**Comment by elvarb** [comment]
Doing this through Logstash would simplify things

https://github.com/influxdata/telegraf/issues/328

**Comment by rikatz** [comment]
This is happening in PR #1875  ! Let's follow there :) :+1:

**Comment by eduardohl** [comment]
+1

**Comment by kkgace** [comment]
+1

**Comment by qrpike** [comment]
+1

**Comment by qli-aa** [comment]
+1

**Comment by lpic10** [comment]
Follow #2332

**Comment by taishan69** [comment]
+1

**Comment by danielnelson** [comment]
#2332 has been merged, many thanks to @lpic10
