### ISSUE TITLE
execd and process that taking time to provide information

### ISSUE THREAD

**Issue by nvitaly** [influxdata/telegraf#7821]
I have execd input process that triggers by STDIN, gather information and spill it out to STDOUT.

it works most of the time, but in one case, my process taking almost 1 min to prepare data for total about 100 items.

In this case telefraf reports error:

2020-07-10T21:24:29Z E! [inputs.execd] Error in plugin: E! [inputs.execd] Error reading stdout: bufio.Scanner: token too long

and gave up on this input, my process waiting for signal but it never comes.

### Relevant telegraf.conf:
[[inputs.execd]]
  command = [ "xxx.py"]
  signal = "STDIN"
  restart_delay = "60s"
  interval = "180s"
  tag_keys      = ["device", "context", "resource", "interface", "direction"]
  json_name_key = "measurement"
  data_format = "json"

### System info:

Package: telegraf
Version: 1.14.4-1

### Docker

none

### Steps to reproduce:

execd input, process with either too many items or that take long time to prepare or output.

### Expected behavior:

it should wait for process to output all data

### Actual behavior:

telegraf write error message to the log and GAVE UP on this input.

### Additional info:

I think we should have some control or documented limits here. exec input has timeout option, would be nice to have it for execd

**Comment by ssoroka** [comment]
This error is because you read more than 4 billion bytes in a single line without finding a metric. That should never happen. Are you writing newlines `\n` between the JSON metrics?

**Comment by nvitaly** [comment]
That was it!

I was collecting items to list() in my script and then printed them with print(json.dumps( )) at the end, I changed it to separate prints for each item and it works now!!!

Thank you

PS: I went different route:

    scanner := bufio.NewScanner(out)
    buf := make([]byte, 10*64*1024)
    scanner.Buffer(buf, 10*64*1024)

It did work but, it is, of course, bad idea.

Vitaly

**Comment by ssoroka** [comment]
Ok, great. Sounds like this is resolved now, so I'll close it out.
