### ISSUE TITLE
Feature Request: Timestamp Floor Processor

### ISSUE THREAD

**Issue by Jaeyo** [influxdata/telegraf#7826]
## Feature Request

I need some features like rounding timestamp value.

### Proposal:

The logic is deadly simple. Get a `period` value (which is `time.Duration` type) through plugin config, and just round a timestamp downward to nearest multiple of `period`.   

### Current behavior:

There's no processor plugin like this.

### Desired behavior:

If `period=15s`,
"2020-07-13T00:00:`17`Z" -> "2020-07-13T00:00:`15`Z"
"2020-07-13T00:00:`29`Z" -> "2020-07-13T00:00:`15`Z"
"2020-07-13T00:00:`31`Z" -> "2020-07-13T00:00:`30`Z"

### Use case: 

Some of metrics should stored with regular intervals. In this case, it's more important to stored with regular interval, rather than to stored with accurate timestamp.

**Comment by Jaeyo** [comment]
@danielnelson consider this plz. I already have some code that I've use to solve my case. So if it's acceptable, PR would be submited immediately.

**Comment by ssoroka** [comment]
Have you considered
```
[agent]
  round_interval = true
```
?

**Comment by Jaeyo** [comment]
@ssoroka Thanks for feedback. I missed that option.
