### ISSUE TITLE
a bug for retention policy

### ISSUE THREAD

**Issue by lmx1989219** [influxdata/telegraf#783]
when i need a retention policy to management the series data.
and i found if i do not specified the retentionPolicy = "default" in 
![image](https://cloud.githubusercontent.com/assets/9464485/13486490/993eb38c-e14c-11e5-88ad-2c9aade454bb.png)
  and the influx not execute

**Comment by sparrc** [comment]
this feature will not be available until 0.10.5

**Comment by lmx1989219** [comment]
thanks,i see
