### ISSUE TITLE
Error in plugin cloudwatch

### ISSUE THREAD

**Issue by jvs87** [influxdata/telegraf#7835]
From 1 hour ago, cloudwatch plugin has started to fail, i dont have changed config since 1 month ago, I have been receiving metrics correctly until this moment.
Logs show the next message : E! [inputs.cloudwatch]: Error in plugin: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp 52.94.241.129:443: i/o timeout

Telegraf vesion : telegraf:1.9.3-alpine

Thanks.

**Comment by ssoroka** [comment]
Hey @jvs87,

It sounds like perhaps the DNS changed and the plugin isn't redoing the DNS lookup, but seems more likely that STS had a temporary service outage.

If restarting it resolves it, it was probably the DNS change. Either way, you might want to update to the latest version of Telegraf. Your version is over 1.5 years old now.

**Comment by sjwang90** [comment]
Closing this for now per changes above.  @jvs87 feel free to open up if your issues still persist.
