### ISSUE TITLE
Command outputs duplicated loaded plugin names

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#7839]
https://github.com/influxdata/telegraf/blob/9a5fd6588c75095f032881b4b168dc4d346a60ae/config/config.go#L177-L212

List of loaded inputs, outputs, processors and aggregators contains duplicate names. This is used here:

https://github.com/influxdata/telegraf/blob/9a5fd6588c75095f032881b4b168dc4d346a60ae/cmd/telegraf/telegraf.go#L183-L186

If you have multiple definitions for a particular plugin, then these list might become long and that seems unneeded?

**Comment by ssoroka** [comment]
Hmm. I think we could probably improve this by looping over the names and counting them. eg "33 x snmp". We would probably still want to preserve order, because I think they're listed in load and running order (or should be)

**Comment by Hipska** [comment]
Yes, they are indeed ordered.

I have a config file for every polled device and see the following after the plugins for Telegraf host itself:
> ping snmp ping snmp ping snmp …

**Comment by jsvisa** [comment]
IMO, if a plugin has `Alias` field, should we use that `Alias` instead of `Name`?

**Comment by Hipska** [comment]
I don't think so, as this is only used to specify which plugins are being loaded for this Telegraf instance.

**Comment by Hipska** [comment]
@ssoroka what do you think of https://play.golang.org/p/ZdS-CsLMXPm as implementation for `config.InputNamecounts()`?

**Comment by ssoroka** [comment]
@Hipska that approach loses information in the cases of debugging processor plugin ordering issues, which is primarily where this ordering matters. It'd be fine for inputs or outputs, which don't really have an order.

**Comment by Hipska** [comment]
Then the leading text is misleading. It states that these are the loaded plugins, which strangely contains duplicates. It should say that it is the load order then?

**Comment by danielnelson** [comment]
I don't think we should worry about the processor order in this log line, it can be determined from the full configuration file.

**Comment by Hipska** [comment]
Okay, and is the number of instances for each plugin relevant here? Or only the names?

**Comment by danielnelson** [comment]
I don't think we need to be super strict here since it is just a log message, and I've never considered these to be a stable interface, so we should do whatever looks best and is the most useful.

Overall, I think the number would be nice to have.
