### ISSUE TITLE
snmp_trap plugin options seems missing

### ISSUE THREAD

**Issue by jehutyy** [influxdata/telegraf#7841]
I'm trying to set up snmp_trap plugin according to this [page](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp_trap#prerequisites). 

I get this error:
```
Error running agent: Error parsing /root/telegraf.conf, line 33 field corresponding to 'version' is not defined in snmp_trap.SnmpTrap
```
In fact everytime I run `telegraf` I get a different error saying that none of declared option exist.

You can take a look at the source code [here](https://github.com/influxdata/telegraf/blob/release-1.14/plugins/inputs/snmp_trap/snmp_trap.go) and specifically SnmpTrap structure line 31:
```
type SnmpTrap struct {
	ServiceAddress string            `toml:"service_address"`
	Timeout        internal.Duration `toml:"timeout"`

	acc      telegraf.Accumulator
	listener *gosnmp.TrapListener
	timeFunc func() time.Time
	errCh    chan error

	makeHandlerWrapper func(handler) handler

	Log telegraf.Logger `toml:"-"`

	cacheLock sync.Mutex
	cache     map[string]mibEntry

	execCmd execer
}
```

It appears that either documentation hasn't been updated or it describes something not fully merged yet.

**Comment by danielnelson** [comment]
Can you add your configuration, with any sensitive data removed, and also let us know which version of Telegraf you are using?

**Comment by jehutyy** [comment]
My bad I thought I already did, here it is : 
```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.file]]
  files = ["stdout"]
[[inputs.snmp_trap]]
  service_address = "udp://:162"
  version = "3"
  sec_name = "bar"
  auth_protocol = "SHA"
  auth_password = "foo"
  sec_level = "authPriv"
  priv_protocol = "AES"
  priv_password = "foo"
```

**Comment by reimda** [comment]
The difference between the code and docs you linked is because the code is from the 1.14 release and the docs are from master and not yet released.  SNMP version 3 trap support will be in 1.15 which is expected to be out very soon.

Could you download a newer build and retry?  The 1.15 release candidates (https://github.com/influxdata/telegraf/releases/tag/v1.15.0-rc4) or a nightly build should work.

**Comment by jehutyy** [comment]
Thanks for your answer, you just confirmed what I thought.
I'll have a try with the 1.15 rc 4 and get back to you, thank you very much.
