### ISSUE TITLE
inputs suricata not working on freebsd (SOLVED)

### ISSUE THREAD

**Issue by kiokoman** [influxdata/telegraf#7843]
### Relevant telegraf.conf:

```
[[inputs.suricata]]
  source = "/var/run/suricata-stats.sock"
  delimiter= "_"
```

### System info:

Telegraf 1.13.4 FreeBSD 12.1-STABLE tested also with Telegraf 1.15.x

### Steps to reproduce:

suricata (Suricata 5.0.3) is sending stats data to /var/run/suricata-stats.sock but telegraf does not grab/send it

### Expected behavior:

data should be sent to influxdb

### Actual behavior:

it's not working as expected, the unix socket is created by telegraf, data is sent by suricata but nothing is sent from telegraf to influxdb 

### Additional info:
nothing from debug 
```
2020-07-15T14:03:13Z I! Starting Telegraf 1.13.4
2020-07-15T14:03:13Z I! Loaded inputs: suricata
2020-07-15T14:03:13Z I! Loaded aggregators:
2020-07-15T14:03:13Z I! Loaded processors:
2020-07-15T14:03:13Z I! Loaded outputs: influxdb
2020-07-15T14:03:13Z I! Tags enabled: host=.....
2020-07-15T14:03:13Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:".....", Flush Interval:10s
2020-07-15T14:03:13Z D! [agent] Initializing plugins
2020-07-15T14:03:13Z D! [agent] Connecting outputs
2020-07-15T14:03:13Z D! [agent] Attempting connection to [outputs.influxdb]
2020-07-15T14:03:13Z D! [agent] Successfully connected to outputs.influxdb
2020-07-15T14:03:13Z D! [agent] Starting service inputs
2020-07-15T14:03:30Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
```

truss

```
_umtx_op(0x45d94f8,UMTX_OP_WAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
compat11.kevent(3,0x0,0,{ 9,EVFILT_READ,EV_CLEAR,0,0x2000,0x82b10ce90 },64,{ 4.958977535 }) = 1 (0x1)
_umtx_op(0x45d95f8,UMTX_OP_WAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x45d95f8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0xc000079e48) = 0 (0x0)
read(9,"{"timestamp":"2020-07-15T18:40:1"...,10420224) = 8192 (0x2000)  <--- it seems some data coming from suricata
nanosleep({ 0.000020000 })                       = 0 (0x0)
nanosleep({ 0.000020000 })                       = 0 (0x0)
read(9,0xc00095a000,10412032)                    ERR#35 'Resource temporarily unavailable'
nanosleep({ 0.000020000 })                       = 0 (0x0)
nanosleep({ 0.000020000 })                       = 0 (0x0)
compat11.kevent(3,0x0,0,{ },64,{ 0.000000000 })  = 0 (0x0)
```

**Comment by ssoroka** [comment]
If you're willing to try a custom build of Telegraf, I might have a fix for this. Reading over the code, it's a bit suspicious that the `readInput` function exits without parsing anything on `io.EOF`; if the metric came in without a carriage return at the end, it would have the symptoms you describe. Here's a patched function to try.

plugins/inputs/suricata/suricata.go line 91:
```
func (s *Suricata) readInput(ctx context.Context, acc telegraf.Accumulator, conn net.Conn) error {
	reader := bufio.NewReaderSize(conn, InBufSize)
	for {
		select {
		case <-ctx.Done():
			return nil
		default:
			line, rerr := reader.ReadBytes('\n')
			if rerr != nil && rerr != io.EOF {
				return rerr
			} 
			if len(line) > 0 {
				s.parse(acc, line)
			}
			if rerr == io.EOF {
				return nil
			}
		}
	}
}
```

**Comment by kiokoman** [comment]
thanks for the fast response, but it does not work, no difference
root@freebsd:~/telegraf # ./telegraf --version
Telegraf unknown (git: master 7af3792b)

**Comment by kiokoman** [comment]
thanks for the fast reply,
i have this on the log now
2020-07-16T18:41:00Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2020-07-16T18:41:34Z E! [inputs.suricata] Error in plugin: invalid character '{' looking for beginning of object key string

**Comment by kiokoman** [comment]
maybe it's suricata or the unix socket this is what i found 

example coming from unix socket

{"timestamp":"2020-07-17T10:08:18.856758+0200" ......."invalid_checksum":0,"no_flow":0,"syn":1044,"synack":454,"r <- alway end like this

example coming from eve.json

{"timestamp":"2020-07-17T10:35:00.974605+0200".......<{"expectations":0},"flow":{"memuse":8443384}}}}}  <--- good output

**Comment by kiokoman** [comment]
sorry, it was a problem on my side, i need to increse this value on freebsd

sysctl -w net.local.stream.recvspace=16384
sysctl -w net.local.stream.sendspace=16384

**Comment by danielnelson** [comment]
Interesting findings, do you think you could update the suricata README.md to describe the potential problem and your solution?

**Comment by kiokoman** [comment]
PR https://github.com/influxdata/telegraf/pull/7856

**Comment by ssoroka** [comment]
merged. closing
