### ISSUE TITLE
Multiple MQTT_Consumers?

### ISSUE THREAD

**Issue by kallisti5** [influxdata/telegraf#7844]
It currently doesn't seem possible to consume topics from multiple MQTT servers?

Server A:   127.0.0.1  access  password
Server B:    us-west.thethings.network    tx-sensor-network   otherpassword

* You can't specify multiple servers to the mqtt_consumer plugin since the users/passwords differ
* You can't specify the plugin more than once

So, how do you instruct telegraf to consume data from multiple MQTT servers?

telegraf-1.12.2

**Comment by danielnelson** [comment]
Specifying multiple servers in the plugin is connecting to clustered MQTT brokers, you won't want that.  However, you should be able to specify this or any other plugin more than once, if you are still having issue with it add your configuration file and any error message you are getting.

**Comment by kallisti5** [comment]
You're correct!  In the past (maybe on a much older version) this was tried and I was getting errors about conflicting fields between the two plugin instances listed. I just tried again on 1.12.2, and it's seemingly working.

I also setup mosquitto bridging to "Bring the data to the same mqtt server"

```
# Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = [
    "openevse-XXX/amp",
    "openevse-XXX/temp1",
    "openevse-XXX/state",
    "openevse-XXX/wh",
  ]
  qos = 0
  username = "XXX"
  password = "XXX"
  data_format = "value"
  data_type = "float"

# Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = [
    "external/ttn/thing",
    "external/ttn/thing",
  ]
  qos = 0
  username = "XXX"
  password = "XXX"
  data_format = "json"
```

**Comment by kallisti5** [comment]
Actually, I closed this one a bit too early.
The settings of the first mqtt_consumer **do** overwrite the settings of the second one... so the second one never gets processed / used.

**Comment by danielnelson** [comment]
What do you see that indicates the second plugin isn't being processed?  It looks like its working for me:
```
$ ./telegraf --config telegraf2.conf --debug
2020-07-16T21:40:14Z I! Starting Telegraf 
2020-07-16T21:40:14Z I! Loaded inputs: mqtt_consumer mqtt_consumer
2020-07-16T21:40:14Z I! Loaded aggregators: 
2020-07-16T21:40:14Z I! Loaded processors: 
2020-07-16T21:40:14Z I! Loaded outputs: file
2020-07-16T21:40:14Z I! Tags enabled: host=loaner
2020-07-16T21:40:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"loaner", Flush Interval:10s
2020-07-16T21:40:14Z D! [agent] Initializing plugins
2020-07-16T21:40:14Z D! [agent] Connecting outputs
2020-07-16T21:40:14Z D! [agent] Attempting connection to [outputs.file]
2020-07-16T21:40:14Z D! [agent] Successfully connected to outputs.file
2020-07-16T21:40:14Z D! [agent] Starting service inputs
2020-07-16T21:40:14Z I! [inputs.mqtt_consumer] Connected [tcp://debian-stretch-mqtt:1883]
2020-07-16T21:40:14Z I! [inputs.mqtt_consumer] Connected [tcp://debian-stretch-mqtt:1883]
```

**Comment by kallisti5** [comment]
```
Jul 16 16:02:50 servername telegraf[1736442]: 2020-07-16T16:02:50Z I! [inputs.mqtt_consumer] Connected [tcp://127.0.0.1:1883]
Jul 16 16:03:48 servername telegraf[1736442]: 2020-07-16T16:03:48Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
```

**Comment by kallisti5** [comment]
ack. Just saw this:

  https://github.com/influxdata/telegraf/issues/6447#issuecomment-535278284

Showing two "Connected" now after setting two different client id's.  I do wish the logs had a bit clearer data in them, but back to working assumed working :-)
