### ISSUE TITLE
Telegraf Error with graphite_separator

### ISSUE THREAD

**Issue by manmohan1391** [influxdata/telegraf#7855]
Getting below error while configuring telegraf.conf

`[telegraf] Error running agent: Error parsing /var/vcap/jobs/telegraf/config/telegraf.conf, line 73: field corresponding to 'graphite_separator' is not defined in graphite.Graphite.`

```
  telegraf.agent.outputs.graphite.separator:
    description: "Configure graphite separator"
    default: "."
```

Please help

**Comment by sjwang90** [comment]
Hi @manmohan1391, we reserve Github issues specifically for bugs. If you have a question, please direct it to the [InfluxData Community Site](https://community.influxdata.com/). 

If you believe the issue you're running into is a bug, please provide the following:
- Relevant telegraf.conf
- System info
- Steps to reproduce

**Comment by ssoroka** [comment]
I tested this and could not reproduce any problem.

You at a minimum need to provide:
- What version of Telegraf you're testing with
- your Telegraf .conf file
