### ISSUE TITLE
Telegraf is shutting down abruptly due to - fatal error: concurrent map writes

### ISSUE THREAD

**Issue by onlypankajsharma** [influxdata/telegraf#7860]
Telegraf is shutting down abruptly due to - fatal error: concurrent map writes:

Input plugin: inputs.mqtt_consumer

Steps to reprduce:
 1. Configure 2 InfluxDB. 
 2. Publish more than 500 tags in milliseconds using MQTT
 3. Stop DB 1 for 15 min 
 4. Restart DB 1
 5 In few seconds Telegraf will shutdown abruptly.

Last message in logs:
2020-07-16T18:05:41Z D! [outputs.influxdb] Wrote batch of 1000 metrics in 84.0037ms

**Comment by danielnelson** [comment]
I believe this is the same issue as #7581
