### ISSUE TITLE
Implement AWS CloudWatch Input Plugin ListMetrics API calls to use Active Metric Filter

### ISSUE THREAD

**Issue by Josh-Bonello** [influxdata/telegraf#7863]
## Feature Request

Opening a feature request kicks off a discussion.

### Use case: 

- For global scale requests, round-trip time spent per sequential API call can jeopardize the capability of returning all data from the CloudWatch APIs within a given interval of Telegraf. 
- For AWS use cases that have a dense amount of data to query from, minimizing API calls with throw-away data presents cost savings (https://aws.amazon.com/cloudwatch/pricing/)
- For AWS use cases which have to share the ListMetric API with other services, this will reduce the usage and minimize footprint on the API throttling limits. ( https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html)

This new feature is scheduled for Go-Live July 24th 2020. Documents to the new API changes to be posted at go-live.

**Comment by sjwang90** [comment]
@Josh-Bonello this looks really valuable for cloudwatch users.  Feel free to open a PR when you're ready and we can get it reviewed and prioritized.

**Comment by Josh-Bonello** [comment]
PR submitted @sjwang90. Is there anyway I can get you (or a delegate) to look at it today?

**Comment by Nuatu** [comment]
@sjwang90 Any insight you can share in terms of when this PR will be reviewed/accepted?

This addition will have a big impact on several systems that I work with an especially large impact to efficiency, reliability, and cost.

**Comment by reimda** [comment]
merged #7894
