### ISSUE TITLE
SNMP input - force IPv4/IPv6

### ISSUE THREAD

**Issue by jacobreid** [influxdata/telegraf#7879]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add an option for the SNMP input to be configured to use/prefer IPv4 or v6

### Current behavior:

(telegraf 1.14.5) SNMP input seems to prefer IPv6 over IPv4 where there are both A and AAAA records for a hostname, and will not fall back to IPv4 if attempting to gather data via IPv6 fails.

### Desired behavior:

Something in the config like `ipv6 = [true, false, auto]` where true uses ipv6 only if available (ignoring ipv4 if existing), false uses ipv4 only, and auto will try one and then the other if it fails (and ideally, remember which one worked for next run?) - in particular, trying IPv4 if an AAAA record is found but an attempt to gather data from the IPv6 address fails. True would be backwards compatible with current behaviour (fall back to IPv4 if no AAAA record, use only IPv6 and don't try v4 if there is an AAAA record) so probably the default setting.

### Use case: 
I have some network equipment with both A and AAAA records for its hostname that has a bug where SNMP only works over IPv4 but telegraf only attempts to reach it over IPv6.

It can be worked around by either pointing the SNMP input to the IPv4 address, or creating another hostname with only an A record, but it would be nice to use the canonical hostname instead.

**Comment by synfinatic** [comment]
sadly, poor support for IPv6 is really common for a lot of vendors.  While ideally, they would all fix it it's unlikely that will happen in the near future.

**Comment by jaydizz** [comment]
I can only second this. 
What comes to mind is specifying the transport protocol. 
GoSNMP aallows the following transport-protocols when setting up a connection:
```// connect to address addr on the given network
//
// https://golang.org/pkg/net/#Dial gives acceptable network values as:
//   "tcp", "tcp4" (IPv4-only), "tcp6" (IPv6-only), "udp", "udp4" (IPv4-only),"udp6" (IPv6-only), "ip",
//   "ip4" (IPv4-only), "ip6" (IPv6-only), "unix", "unixgram" and "unixpacket"```

Why is this not exposed in the configuration files?
This way we could easily specify `udp4://` or `udp6://` for the different agend_hosts.

**Comment by jaydizz** [comment]
I created a PR (https://github.com/influxdata/telegraf/pull/8804)  that enables one to pass the connection-scheme to Gosnmp through the GosnmpWrapper.
It works perfectly in my test-setup.

**Comment by Hipska** [comment]
Strange thing is that current telegraph, does not throw the following error when you configure an agent as `udp4://localhost:161` 🤔 https://github.com/influxdata/telegraf/blob/3b8df55b9c8c15353b8778ab3a19f0b1a5021d29/internal/snmp/wrapper.go#L173

@jaydizz You have an idea why?

**Comment by jaydizz** [comment]
I noticed that behaviour as well. 
When using a specific scheme, it does seem as if telegraf just assumes udp when presented with a "wrong" scheme. 

Sadly, I am not really proficient in Go, but I will have a look into it.
