### ISSUE TITLE
Procstat plugin increases cpu usage to over 100% in 15.1 telegraf version on web servers

### ISSUE THREAD

**Issue by Kedesai** [influxdata/telegraf#7883]
### Relevant telegraf.conf:

```# # Monitor process cpu and memory usage
# [[inputs.procstat]]
#   ## PID file to monitor process
#   pid_file = "/var/run/nginx.pid"
#   ## executable name (ie, pgrep <exe>)
#   # exe = "nginx"
#   ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
     pattern = ".*"
#   ## user as argument for pgrep (ie, pgrep -u <user>)
#   # user = "nginx"
#   ## Systemd unit name
#   # systemd_unit = "nginx.service"
#   ## CGroup name or path
#   # cgroup = "systemd/system.slice/nginx.service"
#
#   ## Windows service name
#   # win_service = ""
#
#   ## override for process_name
#   ## This is optional; default is sourced from /proc/<pid>/status
#   # process_name = "bar"
#
#   ## Field name prefix
#   # prefix = ""
#
#   ## When true add the full cmdline as a tag.
#   # cmdline_tag = false
#
#   ## Add PID as a tag instead of a field; useful to differentiate between
#   ## processes whose tags are otherwise the same.  Can create a large number
#   ## of series, use judiciously.
#   # pid_tag = false
#
#   ## Method to use when finding process IDs.  Can be one of 'pgrep', or
#   ## 'native'.  The pgrep finder calls the pgrep executable in the PATH while
#   ## the native finder performs the search directly in a manor dependent on the
#   ## platform.  Default is 'pgrep'
#   # pid_finder = "pgrep"
```

### Steps to reproduce:

1. enable procstat plugin on web server
2. start telegraf
3. run top

**Comment by danielnelson** [comment]
I know there was a performance regression on this plugin in 1.14.x, have you compared the performance of this plugin against any previous Telegraf releases?

**Comment by Kedesai** [comment]
on 14.14-4 If I have both logparser and procstat enabled the cpu jumps to
29600 telegraf 20 0 1406324 67704 19468 S 121.5 0.4 0:10.84 telegraf

When I have procstats enabled but log parser disabled:
24897 telegraf 20 0 1406580 57956 19000 S 39.3 0.4 0:08.24 telegraf

When I have procstats disabled and only logparser enabled here is the top output:
31033 telegraf 20 0 1002596 69788 18716 S 111.9 0.4 0:06.35 telegraf

When I install telegraf-1.15.1-1.x86_64.rpm and enable procstat look at the cpu jump. The log parser plugin is disabled at this time:

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
22195 telegraf 20 0 1482836 52504 19500 S 125.2 0.3 0:22.87 telegraf

Now with only logparser enabled but procstat disabled:
30903 telegraf 20 0 1431440 77736 19644 S 116.5 0.5 14:12.95 telegraf

In summary both version 14 and 15 have issues. I think I had another ticket for netstat and I will update that separately.

**Comment by Kedesai** [comment]
I have a previous version I think 1.11.2 I will try that one and let you know.

**Comment by Kedesai** [comment]
@danielnelson  any updates?
