### ISSUE TITLE
[mongodb plugin] Add metrics about files currently open and active data handle

### ISSUE THREAD

**Issue by DrissTM** [influxdata/telegraf#7895]
## Feature Request

Right now, the mongodb plugin doesn't gather metrics exposed by `db.serverStatus()["wiredTiger"]["connection"]["files currently open"]` and `db.serverStatus()["wiredTiger"]["data-handle"]["connection data handles currently active"]`

The number of active data-handles grows with the number of active collections/indexes and can cause the checkpoints performed every 60 seconds to hold the schemaLock longer than desired which result in global database locks.

Here are some related issues reported on mongodb's JIRA:
- https://jira.mongodb.org/browse/SERVER-31704
- https://jira.mongodb.org/browse/WT-5479
- https://jira.mongodb.org/browse/WT-6421 (more in-depth explanation on the checkpoint mechanism)

### Proposal:

I'd like to create a PR to gather and store the `files currently open` and `connection data handles currently active` metrics

### Current behavior:

Metrics related to `files currently open` and `connection data handles currently active` are not gathered

### Desired behavior:

Both aforementioned metrics are gathered

### Use case:

We have a mongo replica set that has a pretty high number of collections/indexes and we experience these locks regularly. It would be interesting to expose these metrics to be able to distinguish database locks caused by long write/update queries from the one caused by the schemaLock held by the checkpoints.

**Comment by powersj** [comment]
next steps: look at recently updated #7895
