### ISSUE TITLE
Cloudwatch metrics received within a delay of 3 and more minutes

### ISSUE THREAD

**Issue by avneradania** [influxdata/telegraf#7898]
Cloudwatch telegraf plugin received metrics from AWS Cloudwatch within a delay of 3 or more minutes. Means, graphs in Grafana are cut at the end of it. Usually it's cut 3 minutes before end of graph, sometimes more than it. 

### telegraf.conf:

```
[global_tags]

[agent]
  hostname = "cloudwatch-001"
  omit_hostname = false
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "2s"
  flush_interval = "60s"
  flush_jitter = "1000ms"
  precision = "100ms"
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
```

### input_cloudwatch_web-15.conf:

```
[[inputs.cloudwatch]]
region = "eu-west-1"
access_key = "###############"
secret_key = "######################"

period = "1m"
delay = "1m"
interval = "1m"

ratelimit = 25
namespace = "AWS/ELB"

[[inputs.cloudwatch.metrics]]
    names = ['HTTPCode_Backend_5XX','Latency','HTTPCode_Backend_4XX','HTTPCode_ELB_4XX','RequestCount','HealthyHostCount','UnHealthyHostCount','HTTPCode_ELB_5XX']
[[inputs.cloudwatch.metrics.dimensions]]
    name = "LoadBalancerName"
    value = "web-15"
```
### output_kafka.conf:

```
[[outputs.kafka]]
  brokers = ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]
  topic = "telegraf_metrics"
  client_id = "cloudwatch-001"
  version = "2.1.1"
  compression_codec = 0
  required_acks = 0
  max_retry = 3
  data_format = "influx"
```

### System info:

telegraf version: Telegraf 1.13.4 (git: HEAD ffabd6b5)
OS: Ubuntu 14.04

### Additional info:

Below is a graph that shows one metric incoming from two data sources in Grafana, Cloudwatch and Telegraf(graphite):

![Screen Shot 2020-07-26 at 9 42 40](https://user-images.githubusercontent.com/15194484/88473335-15850480-cf25-11ea-85be-1558d1af479b.png)

I would like to know if this is a known issue and if it is, how can this be fixed?

**Comment by avneradania** [comment]
Any news about this one? Are you guys familiar with it? Is that a known issue?

**Comment by Josh-Bonello** [comment]
I would contact AWS Support and confirm the verbose details of how [Timestamps](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataResult.html) are generated from the GetMetricData API call. You are purposefully lagging by 1 minute by setting the delay setting, which explains 1 of the 2 minutes of lag that you're reporting using your screenshot. The other minute could be explained by how the CW API returns data related to [StartTime and EndTime](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html), considering they are only 1 minute apart in this use case.
