### ISSUE TITLE
RHEL 7.7: repomd.xml not found

### ISSUE THREAD

**Issue by onionhead0708** [influxdata/telegraf#7899]
### System info:
RHEL 7.7

### Steps to reproduce:
1. Follow the steps in https://docs.influxdata.com/telegraf/v1.15/introduction/installation/ to create the yum repository for RedHat/CentOS installation:
```
cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
EOF
```
2. Run the install command 
```
sudo yum install telegraf
```

### Expected behavior:
telegraf can be installed successfully

### Actual behavior:
Error saying that repodata/repomd.xml cannot found
```
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
https://repos.influxdata.com/rhel/7.7/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.
...

failure: repodata/repomd.xml from influxdb: [Errno 256] No more mirrors to try.
https://repos.influxdata.com/rhel/7.7/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

### Workaround
As a workaround, value of baseurl in the /etc/yum.repos.d/influxdb.repo has been updated as followings to fix the issue:
Before:
```
baseurl = https://repos.influxdata.com/rhel/$releasever/$basearch/stable
```
After:
```
baseurl = https://repos.influxdata.com/rhel/7/$basearch/stable
```

**Comment by powersj** [comment]
Hi,

As you have discovered we do not update the repo with every single new distribution or release. We are currently working on a more generic solution for our RPM and DEB repo. This will not involve needing to know specific releases or distribution names.

Your workaround is what I would suggest using for now.

Thanks
