### ISSUE TITLE
telegraf cloudwatch input plugin missing few metrics

### ISSUE THREAD

**Issue by sivatarunp** [influxdata/telegraf#7900]
Hi,
 Recently we observed an issue with telegraf cloudwatch input plugin. We are pulling the AWS RDS metrics every 5 min, and observed that measurement `cloudwatch_aws_rds` is not having a field `burst_balance_average` for few of the RDS instances. It's strange that other metrics/fields for the same instance in the same measurement are available. Here is our sample configuration
```
[[inputs.cloudwatch]]
  region = "${AWS_REGION}"
  period = "1m"
  delay = "1m"
  interval = "4m"
  namespace = "AWS/RDS"
  ratelimit = 25
  statistic_include = [ "average", "sum", "minimum", "maximum", "sample_count" ]
  statistic_exclude = []
```
We tried gathering metrics using cloudwatch get-metric-data api which could pull the burst_balance_average metric correctly.
We also checked telegraf internal plugin metrics for finding any gather errors/ drop errors, but there were no drops as well.
Can you help us to identify the reason behind it?
**Telegraf version: 1.13**

**Comment by sjwang90** [comment]
Hey @sivatarunp. Can I confirm that when you run these [troubleshooting](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch#troubleshooting) steps that it's in your available metrics?

**Comment by sivatarunp** [comment]
Yes @sjwang90 We got the data in list-metrics api.

**Comment by powersj** [comment]
Hi,

Sorry no one has commented on this in a while.

The cloudwatch plugin has had some improvements made over the past couple years. Are you able to reproduce on the latest version of Telegraf?

Thanks
