### ISSUE TITLE
[Feature] Support modpagespeed

### ISSUE THREAD

**Issue by mhf-ir** [influxdata/telegraf#7901]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add pagespeed to input:
More info
https://www.modpagespeed.com/doc/admin

### Current behavior:

Not supported

### Desired behavior:

Support officially by telegraf

### Use case: 

Extension is popular and metrics is ready.

**Comment by powersj** [comment]
Hi,

Thanks for taking the time to file a feature request. We are not currently planning to implement this new plugin. However, if someone did work on one they are welcome to submit a PR where we can review and evaluate for inclusion into Telegraf or as a possible external plugin.

Thanks!
