### ISSUE TITLE
Can we output both the header and body of the listened http input based on the http listen_v2 plugin?

### ISSUE THREAD

**Issue by Jaymmyin** [influxdata/telegraf#7907]
## Feature Request
Want to out both the header and body of http listen_v2 input plugin.
Opening a feature request kicks off a discussion.

### Current behavior:
I can't output the header of listened http request
### Desired behavior:
I can choose which kind of of key/value header to output

**Comment by ssoroka** [comment]
It'd be good to hear more about your use case. It looks like we already support setting tags on metrics from HTTP headers:

```
  http_header_tags = {"HTTP_HEADER" = "TAG_NAME"}
```

**Comment by Jaymmyin** [comment]
Thanks for your replying. However, I fail to do this. I am not sure whether I correctly used this. Let me post more details here. 

In the client side, I  use a log collector to collect logs and then send through to telegraf through http. The following figure is what I captured with wireshark.

<img width="413" alt="Capture" src="https://user-images.githubusercontent.com/11677437/88884700-02f02100-d1ec-11ea-807f-bc4f3ac313a1.PNG">

In the server side, I use http_listener_v2 as input plugin and also set the http_header_tags. Following is my config file
'''
[tags]
    dc = "us-east-1"

[[inputs.http_listener_v2]]
  service_address = ":8080"
  path = "/telegraf"
  data_source   = "header"
  data_format   = "value"
  data_type    = "string"
  json_name_key = "log"
  http_header_tags = {"fac_remote_sync" = "CONVERT_TAG"}
  #http_header_tags = {"from_fluent-bit" = "to_kafka"}

[[outputs.file]]
  files = ["stdout"]
  data_format   = "json"
'''

Like what I post above. I output the result on my screen. After doing this, I got this result:

{"fields":{{\"date\":1596086875.423149,\"log\":\"2020-06-11_23:28:43--INFO--20200611231507--{'username': 'remoteuser_112315', 'action': 'sync', 'host': '192.168.100.87', 'type': 'slave_2', 'result': 'success', 'time': 12.39}\"}]"},"name":"http_listener_v2","tags":{"dc":"us-east-1","host":"root"},"timestamp":1596086880}

So, I didn't find the http header tag in tags. Am I correctly use this plugin ?

**Comment by Jaymmyin** [comment]
> It'd be good to hear more about your use case. It looks like we already support setting tags on metrics from HTTP headers:
> 
> ```
>   http_header_tags = {"HTTP_HEADER" = "TAG_NAME"}
> ```

Thanks for your replying. However, I fail to do this. I am not sure whether I correctly used this. Let me post more details here.

In the client side, I use a log collector to collect logs and then send through to telegraf through http. The following figure is what I captured with wireshark.

Capture

In the server side, I use http_listener_v2 as input plugin and also set the http_header_tags. Following is my config file
'''
[tags]
dc = "us-east-1"

[[inputs.http_listener_v2]]
service_address = ":8080"
path = "/telegraf"
data_source = "header"
data_format = "value"
data_type = "string"
json_name_key = "log"
http_header_tags = {"fac_remote_sync" = "CONVERT_TAG"}
#http_header_tags = {"from_fluent-bit" = "to_kafka"}

[[outputs.file]]
files = ["stdout"]
data_format = "json"
'''

Like what I post above. I output the result on my screen. After doing this, I got this result:

{"fields":{{"date":1596086875.423149,"log":"2020-06-11_23:28:43--INFO--20200611231507--{'username': 'remoteuser_112315', 'action': 'sync', 'host': '192.168.100.87', 'type': 'slave_2', 'result': 'success', 'time': 12.39}"}]"},"name":"http_listener_v2","tags":{"dc":"us-east-1","host":"root"},"timestamp":1596086880}

So, I didn't find the http header tag in tags. Am I correctly use this plugin ?

**Comment by ssoroka** [comment]
part of the problem here is that the http header tag is normalized, so it's not going to match the case you've supplied. I've submitted a patch to make this case insensitive, so your above code will work with the nightly build once it's merged.

In the mean time, you'll want to adjust the http header tag. I believe the right formatting is: `http_header_tags = {"Fac_remote_sync" = "CONVERT_TAG"}`
