### ISSUE TITLE
multiple plugin instances

### ISSUE THREAD

**Issue by rubycut** [influxdata/telegraf#791]
Hi, I am maintaining kubernetes cluster with multiple instances of rabbitmq, one for staging, one for production, etc.

I would like to be able to enter multiple rabbitmq plugin instances in telegraf config file.

I would be logical to gather statistics from the server on which rabbitmq instance is running, but in kubernetes, those rabbitmq instances can jump from one server to another. So, I would like to have something like:

[rabbitmq.0]
  url = "http://8.8.8.8:30690" # required
  name = "rabbitmq-staging" # optional tag

[rabbitmq.1]
  url = "http://9.9.9.9:30690" # required
  name = "rabbitmq-production" # optional tag

**Comment by sparrc** [comment]
this is already possible if you're using a 0.10.x version,

```
[[inputs.redis]]
  ...

[[inputs.redis]]
  ...
```
