### ISSUE TITLE
InfluxDB 2.x Flux query plugin

### ISSUE THREAD

**Issue by darinfisher** [influxdata/telegraf#7910]
## Feature Request
Pull data from an InfluxDB v2 database with a flux query.

### Proposal:
Add an input plugin that is able to connect to a InfluxDB v2.x instance, OSS or Cloud, and run a flux query to acquire data.  This will utilize the current [InfluxDB Go client](https://github.com/influxdata/influxdb-client-go).

### Current behavior:
Should be possible via the [HTTP Response plugin](https://github.com/influxdata/telegraf/blob/release-1.15/plugins/inputs/http_response/README.md).   But does not have the built-in buffering and batching capabilities of the go client.

### Desired behavior:
Ability to pull data from an InfluxDB v2.x instance

### Use case:
Moving buckets to other instances
Reprocessing of metrics

**Comment by Anaisdg** [comment]
I see a lot community members asking for this functionality to be able to write metrics from an edge device to cloud.

**Comment by mhall119** [comment]
The easiest way to write this plugin would be using the [Go client library](https://github.com/influxdata/influxdb-client-go). However, the current `influxdb_v2` output plugin doesn't use this, so it would result in a new dependency (I'm not sure how large).

Alternately it could do what the `influxdb_v2` output plugin does and make HTTP calls directly to the InfluxDB API endpoints.

Another consideration is how to convert data you get from a Flux query into something that Telegraf can use. These queries return columnar (usually) [Annotate CSV](https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/) so we couldn't simply use the existing `data_format='csv'` option. We would need to decide whether to read columnar data as InfluxDB returns by default, or require that the Flux query call `schema.fieldsAsCols` to pivot the data into row-based CSV

**Comment by powersj** [comment]
Give the new iox-based products having support for SQL, and our own SQL input already supporting flightsql, I am going to close this. If we hear that having this sort of plugin would help migrations it is something we could revisit.
