### ISSUE TITLE
github.com/couchbase/goutils has a non-free license

### ISSUE THREAD

**Issue by sergiodj** [influxdata/telegraf#7914]
The plugin `github.com/couchbase/goutils` in its version that is being imported by Telegraf (`v0.0.0-20180530154633-e865a1461c8a`) has a non-free license.  This was probably a mistake by upstream, and the issue has since been fixed in their repository (see https://github.com/couchbase/goutils/commit/b49639060d85b267c5bdb7d4e3246d4ccca94e79).  Telegraf should depend on a newer version of the package.

**Comment by sjwang90** [comment]
Thanks for opening this. Feel free to open a PR with a fix otherwise our team will take a look 😊

**Comment by sergiodj** [comment]
Thanks.  I checked and upgrading the dependency to `v0.0.0-20191018232750-b49639060d85` (which is the latest version) will solve this problem and doesn't introduce any regressions on the testsuite.  I can happily provide a simple one-line patch, as long as it's fine to do that without a CLA signature.  Thanks!

**Comment by sjwang90** [comment]
@sergiodj We do not accept PRs without users signing the CLA. If you are able to sign the CLA then please open a PR. Otherwise we can get this fixed on our end.
