### ISSUE TITLE
Output filenames based on input file name

### ISSUE THREAD

**Issue by slowbreathing** [influxdata/telegraf#7916]
## Feature Request

Output filenames based on input file name

### Current behavior:
Tailing a set of files with the pattern of cpu0,cpu1,...,cpun goes to a single file.

### Desired behavior:
the output go into seperate files cpuoutput0,cpuoutput1,...,cpuoutputn

### Use case: 
These are big files and merging them does not make sense in some cases. Ill have to filter them anyways because these cpu events make sense only for that particular cpu.

**Comment by sjwang90** [comment]
Hi @slowbreathing, can you please provide more detailed examples on this.

**Comment by MyaLongmire** [comment]
Due to lack of activity, I am going to go ahead and close this. Feel free to ping me if it needs to be reopened.
