### ISSUE TITLE
extract a custom internal input telegraf plugin with Telegraf Execd Go Shim on Windows

### ISSUE THREAD

**Issue by ashishkaransingh** [influxdata/telegraf#7919]
Hi,

Have a custom plugin which works well as a part of telegraf binary, i am trying to extract it as a standalone .exe so we can do our development independently but will be be to use it from telegraf **inputs.execd** 

OS: Windows 10

https://github.com/influxdata/telegraf/tree/master/plugins/common/shim

Build it using the following:

`go build -o mssql_1.exe plugins/inputs/sqlserver/mssqllib/mssqllib.go`

Config under telegraf.conf

```
[[inputs.execd]]
  command = ["C:\\Users\\test_user\\Downloads\\standlone_plugin\\mssql_1.exe", "-config", "C:\\Users\\test_user\\Downloads\\standlone_plugin\\telegraf_pam_sql.conf"]
  signal = "none"
```
  

Executed 
  
```
C:\Users\test_user\Downloads\telegraf-master\telegraf-master>telegraf.exe --config telegraf.conf -test
2020-07-29T12:22:15Z I! Starting Telegraf
2020-07-29T12:22:15Z I! [inputs.execd] Starting process: C:\Users\test_user\Downloads\standlone_plugin\mssql_1.exe [-config telegraf_pam_sql.conf]
2020-07-29T12:22:15Z E! [agent] Starting input inputs.execd: failed to start process [C:\Users\test_user\Downloads\standlone_plugin\mssql_1.exe -config telegraf_pam_sql.conf]: error starting process: fork/exec C:\Users\test_user\Downloads\standlone_plugin\mssql_1.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

Running it from standalone directory

![image](https://user-images.githubusercontent.com/29729110/88800661-230ce980-d1c6-11ea-879e-df5bdece4e20.png)

If successful this will help all the users who would want this for MSSQL or with Windows.

Thanks

**Comment by ssoroka** [comment]
For debugging, take Telegraf out of the loop and try to run the `mssql_1.exe` app directly and see what happens. It sounds like maybe the GOARCH environment setting isn't set correctly?  You can see the settings with `go env`. I would expect you might have to do `set GOARCH=amd64` first if you're building on a 386 machine and deploying to an amd64 machine.

Out of curiosity, is it being built and run on the same machine?

**Comment by ashishkaransingh** [comment]
Mine is a **64 bit architecture**

take Telegraf out of the loop and try to run the mssql_1.exe app directly and see what happens.
**Answer:** Yes, I did and the screenshot with the error is the result, where it yells about 16 Bit Application

Out of curiosity, is it being built and run on the same machine?
**Answer:** Yes, built and run on the same machine.

I had a similar issue when i built telegraf using just "make" on my machine, then shared the telegraf.exe with a developer to run it on a remote server and it was complaining about the architecture not supported finally it got fixed when compiled with "make telegraf"

**Comment by ashishkaransingh** [comment]
Any idea?

**Comment by ashishkaransingh** [comment]
@ssoroka do we need to build this differently for windows like using make etc...?

**Comment by ssoroka** [comment]
Hey, sorry I'm a bit behind on responding. 

If you're building and running on the same machine, go _should_ know how to build its own binaries properly, so that part is a bit confusing. If you run `go env` go will spit out all the environment variables it's using to build with. You might need to `set` or `setx` the correct GOOS and GOARCH env variables to get the build to make the right kind of binary. 
so probably something like ... 
```
setx GOOS windows
setx GOARCH amd64
go build -o mssql_1.exe plugins/inputs/sqlserver/mssqllib/mssqllib.go
```

**Comment by ssoroka** [comment]
@ashishkaransingh let me know if this resolves your problem or not. Happy to work through it with you.

**Comment by ashishkaransingh** [comment]
@ssoroka Thank a lot for you response!
I recently suffered a great loss of lost my maternal grandmother. I resumed working on it and will let you know.

**Comment by ashishkaransingh** [comment]
Hi @ssoroka 

I am little perplexed.

If I build plugin as: go build -o standlone_plugin.exe cmd/main.go
then on execution i get error: 
E! [inputs.execd] stderr: "Err loading input: Near line 0 (last key parsed ''): bare keys cannot contain '\\ufeff'"

If i build as the following:
go build -o standlone_plugin.exe go build -o standlone_plugin_3.exe plugins/inputs/pam_sqlserver/mssqllib/mssqllib.go

Then i get the same error i reported before:
https://user-images.githubusercontent.com/29729110/88800661-230ce980-d1c6-11ea-879e-df5bdece4e20.png

Thanks

**Comment by ashishkaransingh** [comment]
Also updated on slack channel telegraf
https://app.slack.com/client/TH8RGQX5Z/C019JDRJAE7/thread/C019JDRJAE7-1598534795.021500

**Comment by ssoroka** [comment]
So sorry to hear about your grandmother, @ashishkaransingh 

I'll assist you on Slack as this will require some back and forth and doesn't appear to be a bug in Telegraf. I've messaged you there.

Cheers

**Comment by ashishkaransingh** [comment]
Thank you so much @ssoroka

**Comment by ssoroka** [comment]
Going to close this as the original issue is solved. Still working on the other issue we uncovered.

**Comment by ashishkaransingh** [comment]
Thank you Steven!
