### ISSUE TITLE
add regex functionality for the processors plugin rename

### ISSUE THREAD

**Issue by SaschaP95** [influxdata/telegraf#7923]
## Feature Request

Processor plugin rename with regex

### Proposal:

extension of the existing plugin with regex functionality

### Current behavior:

the processor plugin rename does not support rename per regex 
for example:
`[[processors.rename]]
 [[processors.rename.replace]]
   field = "alarm_data_cpu"
   dest = "cpu"`

### Desired behavior:

that you can search with regex for a field and replace them with a match
`[[processors.rename]]
[[processors.rename.replace]]
  field = "alarm_data_(\w+)"
  dest = "${1}"`

### Use case:

we get data from Kafka and they always have a prefix. We would like to remove the prefix. It is not possible to change it to Kafka so it has to be done by telegraf.

Currently we have the prefix in the fields which have to be removed permanently

**Comment by ssoroka** [comment]
I believe this is covered by the [regex processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex). Have a check and let me know if it doesn't meet your needs.

**Comment by SaschaP95** [comment]
good morning @ssoroka 
i tried the regex processor but they cant do it.
`  [[processors.regex]]
    namepass = ["XXXX"]
  [[processors.regex.fields]]
    ## Field to change
    key = "*"
    pattern = "^alarmrawdata_data_(\\w+)$"
    replacement = "${1}"
`

also tested with different variations of key and it dont work for me.
for example ( key = "alarmrawdata_data_cpu_idle" )
I want to change the name of a field (in influxdb when you type "show field keys")

have someone any ideas?

**Comment by ssoroka** [comment]
Oh, I see. You can actually do something like this with the starlark processor. here's an example:
```
[[processors.starlark]]
  source = '''
prefix = "alarmrawdata_data_"
def apply(metric):
    for k, v in metric.fields.items():
        if k.startswith(prefix):
            metric.fields[k[len(prefix):]] = v
            metric.fields.pop(k)
    return metric
'''
```
