### ISSUE TITLE
Input Plugin for Azure Monitor

### ISSUE THREAD

**Issue by vipinvkmenon** [influxdata/telegraf#7930]
## Feature Request

Currently, there is support for Stackdriver and Amazon Cloudwatch to pull IaaS metrics. Another major IaaS provider in the scene is Microsoft Azure. With the concept of "Multi-Cloud" becoming a norm day by day, this integration of Azure Monitor

### Proposal:
An input plugin that is able to pull metrics from Azure Monitors just like Cloudwatch and Stackdriver plugins that are now present.

### Use case: 
Telegraf is one of the most important and got-to metrics collection agents. And currently when it comes to being able to pull metrics out of Azure Monitors is not out of the box. A plugin for the same would be great.

**Comment by minz1027** [comment]
+1. In need for this too

**Comment by mjiderhamn** [comment]
We have a Telegraf plugin for pulling Azure Monitor data implemented and put in production use. I hope to cut through the red tape of CLAs so that I can share it with you.

**Comment by amitschwartz76** [comment]
+1. Mattias, I hope you will be able to share it soon.

**Comment by adhiraj-g** [comment]
Hello @mjiderhamn ,

Does the Telegraf input plugin support fetching metrics from a Multiple AD Setup as well?
Would it also be able to fetch out Azure Cost Data via Consumption APIs?

Hope to hear back from you soon.

**Comment by mjiderhamn** [comment]
Hi @adhiraj-g .

Authentication against Azure in the plugin is done using the [`azure-sdk-for-go`](https://github.com/Azure/azure-sdk-for-go) authentication mechanism. See [`azure-sdk-for-go` documentation](https://github.com/Azure/azure-sdk-for-go#authentication) if you can find out yourself if multiple AD is supported.

No, `costmanagement` API is not included in this plugin. Sounds to me that should be a separate plugin.

**Comment by andrewbierbaum** [comment]
@mjiderhamn 

Were you able to make progress on sharing you input plugin? We are running into the same interest in exporting azure data. 

Thanks
