### ISSUE TITLE
Write documentation on how to log custom debug messages from newly authored plugins

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#7936]
## Feature Request

I built a new Telegraf output plugin but for debug reasons I need to be able to write data to the log file.
I don't see any infromation on how I can write debug information to the log.
Example:
My plugin is supposed to reach out to google to perform a handshake and return a token to make an http request.
I’ve added the plugin to the source code, compiled it, and can see it available telegraf, but it looks like I’m not getting a token and want to log that the handshake is successful and/or what the token is.

`2020-08-03T17:03:06Z E! [agent] Error writing to outputs.cloudrun: Post https://RESTURL: net/http: invalid header field name "Authorization ="`

How would I add this functionality to my code?
### Proposal:
Write documentation on how to log custom debug messages from newly authored plugins
### Current behavior:
Not aware of any information that is available on how to write to the log file from inside the code.
### Desired behavior:
Be able to write to the log file so I can debug my code by viewing what's happening while the agent is running using something like:
`fmt.Printf("This is my current token: %s\n", accessToken)`
Example:
```
2020-08-03T17:03:06Z I! [agent] This is my current token: $TOKEN_VALUE
```
### Use case: 
Without a way to log from my plugin it severely degrades being able to troubleshoot and then submit it.

**Comment by ssoroka** [comment]
This is a great question, thanks! 

Add `Log telegraf.Logger `toml:"-"`` to your plugin struct, and a logger will be set automatically for it when it's registered.

in your tests, you'll have to set this yourself to the test logger, eg:
```
myplugin := &MyPlugin{}
myplugin.Log = testutil.Logger{}
```

Using the logger is easy, it implements the [telegraf.Logger interface](https://github.com/influxdata/telegraf/blob/5c8d0e3ac9d888ef2851406db72c014d9cbbe974/plugin.go#L13-L30)

Now that that's said, we should get that into the docs somewhere.

**Comment by raider111111** [comment]
Alright, thanks @ssoroka!
I will take a look!

**Comment by raider111111** [comment]
@ssoroka 

How would I use this information to log messages from std out, such as something from `fmt.Printf` to log to the log file?

**Comment by ssoroka** [comment]
I've updated the example above for example usage

**Comment by raider111111** [comment]
Oh, ok. 
Simple enough!
Thanks!
