### ISSUE TITLE
Document authentication for http_response input plugin

### ISSUE THREAD

**Issue by tesibelda** [influxdata/telegraf#7942]
## Feature Request

HTTP Basic authentication for http_response input plugin was introduced in https://github.com/influxdata/telegraf/pull/7491, but it is not documented in its README.md file. username and password configuration variables shoud be included in this file for reference.

### Proposal:
Sample configuration is included in line 86 of https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_response/http_response.go, but it was not included in the README.md file:
  \#\# Optional HTTP Basic Auth Credentials
  \# username = "username"
  \# password = "pa$$word"

### Use case:
Improve telegraf documentation.

**Comment by sjwang90** [comment]
Thanks for the PR @vikkyomkar!
