### ISSUE TITLE
Documentation for adding data format serializer packages 

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#7943]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Documentation for adding data format serializer packages 
### Current behavior:
Not aware of documentation steps for adding serializer packages like available for output and input plugins. 
### Desired behavior:
Add documentation for adding my own custom serializer for custom data formats.
### Use case: 
Example:
When sending to Wavefront using direct ingestion the wavefront serializer replaces underscore charecters with periods which is against our naming convention. I went in a modified the code but would prefer to create a new serializer specific for our needs instead of modifying an existing package. To do that I need documentation on what best practices are.

**Comment by ssoroka** [comment]
Just curious if you're running (or planning to run) a custom build of Telegraf to support this, or what your thoughts are about next steps after you have something written.

**Comment by raider111111** [comment]
Hi @ssoroka !

Yes, I took the `outputs.http`, copied it into a new output plugin called `outputs.cloudrun`, modified it to support additional code that enables it to dynamically update the HTTP token needed to communicate with GCP's CloudRun service that I could then use to send metrics into the Wavefront proxy that resides there.

I found however that the Wavefront serializer has a line of code that replaces underscores with periods which causes issues with our naming convention. The Wavefront output plugin actually accounts for this with the `convert_paths` option. To fix this I edited the code to not replace the characters. That said, I think it would be best to leave the Wavefront serializer as is and make a copy that supports not replacing instead. Why I was asking for documentation so I know to do it correctly.

**Comment by ssoroka** [comment]
If you look at plugins/serializers/wavefront/wavefront_test.go, you could probably copy one of the tests and update it for your purposes. I assume you're using that one because it creates a metric per field?

I think the process is mostly pretty easy, but perhaps not all that well documented. You are welcome to copy the serializers/wavefront folder with a new name and replace everything in it to suit your needs. .. I can maybe write up more details on how to fully integrate it. 

Question, why would GCP CloudRun use the wavefront serializer? are the two formats that similar?

**Comment by raider111111** [comment]
Hi!
I will take a look at that, I just wasn’t sure how to call the serializer, could I just use the folder name (example, data_format=cloudwavefront)?

The reason I use the Wavefront serializer is because there is a Wavefront proxy container being managed by the GCP CloudRun service. Once the data is allowed to pass into the container it needs to conform to the Wavefront Data Format or it will be rejected.

Thanks!

**Comment by ssoroka** [comment]
Okay, maybe it makes sense to extend the existing wavefront serializer to expose an option to set the separator, then? If the format is really attempting to support wavefront and this is just a slight variation, that makes more sense than duplicating the serializer.

**Comment by raider111111** [comment]
Hi,

Yeah, I thought about that but wasn’t sure how to connect the ouputs.cloudrun plugin into the wavefront serializer other than the data_format option.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ssoroka** [comment]
yeah, just edit the serializer. I'd edit the wavefront serializer to add an option to specify the separator, and default it to `.` (so it's backwards compatible), insert it into wavefront's `pathReplacer`, and add a test to make sure your feature works and hasn't broken anything. That should be the whole process. I also recommend the [community slack](https://www.influxdata.com/slack) #telegraf channel for support as you're going through it.

**Comment by raider111111** [comment]
Hi,
I’ve been working on a different Telegraf config lately (gnmi) and had to stop development of the outputs.cloudrun/wavefront sterilizer plugin, but expect to get back to that in a month or so.

When I get back to it I will for sure look at this, and would like to submit it with a pull request so if you guys want you can chew on it and decide if you want it to add it as a community plugin.

Thanks!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
