### ISSUE TITLE
Need to list InfluxDB 2.0 output in CONFIGURATION.md

### ISSUE THREAD

**Issue by alsargent** [influxdata/telegraf#7952]
### Steps to reproduce:

This is a documentation issue, not a software bug:

1. Go to https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md
2. There are numerous references to how to connect to InfluxDB v1.x, using the influxdb output plugin and port 8086. But no references to how to connect to InfluxDB v2, using the influxdb_v2 plugin and port 9999 (running locally) or cloud URLs. 
3. Users will fail to successfully connect Telegraf to InfluxDB 2.0 and give up.

### Expected behavior:

On CONFIGURATION.md, we should list both the v1.x and v2 configuration options, with comments that explain which version the config applies to.

I've put proposed changes into this PR:
https://github.com/influxdata/telegraf/pull/7953

**Comment by ssoroka** [comment]
merged
