### ISSUE TITLE
Field corresponding to `servers' is not defined in system.SystemStats

### ISSUE THREAD

**Issue by gregoinc** [influxdata/telegraf#7955]
Hello,

Attempting to configure Telegraf to utilise inputs.ipmi_sensor but I am getting this error...

/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
2020-08-07T11:09:17Z I! Starting Telegraf 1.15.2
2020-08-07T11:09:17Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: Error parsing system, line 3297: field corresponding to `servers' is not defined in system.SystemStats

Really new to Telegraf (first time installing) so after searching I was unable to find a solution? The line 3297 refers to this line...

`servers = ["USERID:PASSW0RD@lan(192.168.1.1)"]`

Not sure what I have done that has upset things? Any help appreciated.

Thanks, Mark

**Comment by ssoroka** [comment]
Can you supply more of the config? It looks like it's thinking servers is attached to `[[inputs.system]]`. TOML is not indent sensitive, and anything after a heading belongs to that heading, so maybe that's part of the issue? Anyway if you could supply more of, or your whole config, we can help pinpoint the problem for you.

Cheers

**Comment by gregoinc** [comment]
Hi Folks,

Apology, it was a newbie mistake, I failed to un-comment one of the options in the config file. All solved and running now.

Thanks, Mark
