### ISSUE TITLE
Telegraf to Graphite picking up SNMP collector hostname

### ISSUE THREAD

**Issue by ekolseth** [influxdata/telegraf#7956]
### Relevant telegraf.conf:

```  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
##  omit_hostname = true


[[outputs.graphite]]
  servers = ["xx.xx.xx.xxx:2003"]
  prefix = "stats.infrastructure.test2.OS"
  template = "host.tags.field"
  namepass = ["cert_expiry*","cpu","uptime","Uptime","sys*","interface","if*","mem","*IO*","snmp"]


```

### System info:

telegraf-1.14.4-1.x86_64 on Linux RHEL 7.6

### Expected behavior:

Pulling SNMP stats from AWS EC2 instances into Telegraf on a collector and output to Graphite. The Graphite tree structure is incorrect and I believe the issue lies w/i the telegraf.conf file. The expected tree path should be:

infrastructure.test2.OS.<EC2_instance_hostname>..stat

### Actual behavior:

Pulling SNMP stats from AWS EC2 instances into Telegraf on a collector and output to Graphite. The Graphite tree is including the collector's hostname in the path and the EC2 instance twice. For instance the path currently is:

infrastructure.test2.OS.<collector_hostname>.<EC2_instance_hostname>.<EC2_instance_hostname>.stat

I have tried editing the template and the omit_hostname setting (above) to no avail.

**Comment by Hipska** [comment]
In your `template` you set that it should include the collector hostname, so it does that. Then you add all the tags, could it be that instance name is in there twice? Could you give a line of snmp output when you run the config with `--test`?

**Comment by Hipska** [comment]
@ekolseth could you give feedback please?
