### ISSUE TITLE
How to set tag by using influxdb

### ISSUE THREAD

**Issue by yuanbwhub** [influxdata/telegraf#7957]
Excuse me, I want to ask how to set the metrics as TAG by using GROK in influxDB？
I look forward to your reply! thanks

**Comment by sjwang90** [comment]
Can you ask this question at our [Community Page](https://community.influxdata.com/)? We reserve GitHub issues for bugs and feature requests.  Feel free to tag me (`@sjwang90`) on the community page and I can help you get an answer there.
