### ISSUE TITLE
lsof performance issues

### ISSUE THREAD

**Issue by hworld** [influxdata/telegraf#796]
I don't have much info for this yet, but I've been noticing high CPU usage spikes with lsof in the process list periodically. I've noticed it most on a nodejs chat server we have running. Periodically the server's load spikes and the chat service becomes unresponsive and when I look in the process list is seems that lsof has high CPU usage.

I'm not sure if the lsof calls are the culprit, or a byproduct of something else. Does is make sense that this could be an issue? I'm not really sure how to debug this to see if lsof is really causing it or not? Is there a way to just turn that check off to see if stability returns? It seems to happen during high CPU usage times (like weekends), so it doesn't happen too often.

**Comment by sparrc** [comment]
this is a won't fix for telegraf, we won't need lsof as soon as gopsutil doesn't need lsof (see https://github.com/shirou/gopsutil/issues/164)

**Comment by hworld** [comment]
Good to know. Thanks!

**Comment by sparrc** [comment]
no prob, hopefully we can get that in soon, if it helps, lsof currently gets called by the `netstat` plugin, disabling that plugin would disable lsof calls

**Comment by hworld** [comment]
Was wondering which plugin spawned it. Will probably disable that until the changes get merged in.
