### ISSUE TITLE
Does default `host` tag enabled is ok?

### ISSUE THREAD

**Issue by coanor** [influxdata/telegraf#7961]
I'm using telegraf to fetch metrics from redis/mysql/elasticsearch, by default, telegraf will add a default tag `host=<telegraf-running-hostname>` for every metric, I have to turn it off, or there will be a `host=<telegraf-running-host>` tag and a `server=<the-real-redis-server>` tag for **all** redis metrics, it's confusing. 

I think it's not so common to enable `host` tag globally for these remote metrics.

I prefer to enable the `host=<telegraf-running-host>` on specific inputs, such as CPU/mem/disk/..., and the tags should embedded in the config-sample like this:

```
[[inputs.cpu]]
  [inputs.cpu.tags]]
    host = '{{.Hostname}}'  # pretent there was a Hostname field in telegraf global config
```

**Comment by ssoroka** [comment]
You can turn this off globally in the config:
```
[agent]
  omit_hostname = true
```

**Comment by coanor** [comment]
> You can turn this off globally in the config:
> 
> ```
> [agent]
>   omit_hostname = true
> ```

I prefer the default behavior is `omit_hostname`, not `add-host-tag-automatically`. By the way, I also prefer to default enable `add-host-tag-automatically` on part of the inputs, such as CPU/mem/disk...
