### ISSUE TITLE
test-wait parameter not respected

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#7969]
```
  --test-wait                    wait up to this many seconds for service
                                 inputs to complete in test or once mode
```
If setting this to a low value, Telegraf still does a complete polling and only then shuts down.

### System info:

Telegraf 1.15.2

### Steps to reproduce:

1. run `time telegraf --test-wait 5 --config ...` on a config that takes more than 5 seconds (snmp, or other external inputs)

### Expected behavior:

Telegraf stops after 5 seconds.

### Actual behavior:

Telegraf stops after the complete (snmp) poll has finished:

```
real	1m55.866s
user	0m1.595s
sys	0m0.770s
```

### Additional info:

@ssoroka pointed out on Slack that the problem might be here:
https://github.com/influxdata/telegraf/blob/a6c8f5be13e17e6a62fd2b2b274879cdc1bf76cc/agent/agent.go#L429-L431
The agent seems to wait on a full poll and then it does the wait.

**Comment by ssoroka** [comment]
Yeah. I think it's somewhat problematic. So after the sleep it calls `stopServiceInputs`, which is going to call Stop() on all the input plugins, but it's generally understood that this is not going to be called during a Gather() call, so this --test-wait feature is weird anyway. If the expectation is that test-wait is going to kill the Gather function execution, I'm not really sure what the mechanism is to do this. Gather doesn't even receive a context to pay attention to and abort execution, and even if it did, it'd be up to every plugin author to implement it properly.

I kind of think this feature is falsely advertising as doing something that is going to be really difficult to support without breaking a lot of other things. You'll notice it doesn't even get to SleepContext until after `wg.Wait()`, that is, after every Gather function has already stopped. This means it's not really possible for the timeout to do anything useful. I also think SleepContext isn't doing anything useful either.

That leaves you with hard-exiting at this timeout, which is not ideal. I wonder if we should just remove this flag.

**Comment by Hipska** [comment]
Maybe the flag is relevant if you (only) have input plugins that wait for an incoming connection? If that is the case, it should be better explained in the documentation of this flag.

**Comment by Hipska** [comment]
@ssoroka Do you think if #6613 is implemented, it will solve this issue?

**Comment by Hipska** [comment]
Came back to this one, and now I immediately found the description good enough.. I'm not sure if this needs to stay open..
