### ISSUE TITLE
MQTT Consumer: persistent session is not working because of random clientId

### ISSUE THREAD

**Issue by noonowl71** [influxdata/telegraf#797]
I'm trying to set up a MQTT subscription with QOS 2 (mosquitto broker), which means the broker should keep messages when subscriber is offline, and send all stored messages when the subscriber becomes online.

Well, this is not working  because Telegraf uses a random clientId to connect to the broker, and this causes that the persistent session is different every time it connects. From the mosquitto docs:

> Badly designed clients may set clean session to false whilst using a randomly generated client id.

I think the best is to create a config option to override the clientId

**Comment by sparrc** [comment]
yep, that's a bug, thanks for the report

**Comment by sparrc** [comment]
it's worth noting that we're also setting clean session to true currently, so they wouldn't be delivered anyways.

We probably need to provide an option to set clean option to false _and_ specify the client ID. (if clean option is set to false user *must* specify a client ID)

**Comment by noonowl71** [comment]
That should do it, thanks!
