### ISSUE TITLE
Potential import collision: import path should be "k8s.io/apimachinery", not "github.com/kubernetes/apimachinery"

### ISSUE THREAD

**Issue by KateGo520** [influxdata/telegraf#7978]
## Background
I find that `k8s.io/apimachinery` and `github.com/kubernetes/apimachinery` coexist in this repo：
https://github.com/influxdata/telegraf/blob/master/go.mod （Line 85 & 153）
```
github.com/kubernetes/apimachinery v0.0.0-20190119020841-d41becfba9ee 
k8s.io/apimachinery v0.17.1 // indirect 
```
That’s because the `apimachinery` has already renamed it’s import path from "github.com/kubernetes/apimachinery" to "k8s.io/apimachinery"，in this version. When you use the old path "github.com/kubernetes/apimachinery" to import the `apimachinery`, will reintroduces `apimachinery` through the import statements "import k8s.io/apimachinery" in the go source file of `apimachinery`.

https://github.com/kubernetes/apimachinery/blob/d41becfba9ee9bf8e55cec1dd3934cd7cfc04b99/pkg/api/resource/quantity_example_test.go
```
package resource_test
import (
	"fmt"
	"k8s.io/apimachinery/pkg/api/resource"
)
```

"k8s.io/apimachinery" and "github.com/kubernetes/apimachinery" are the same repos. This will work in isolation, bring about potential risks and problems.

## Solution
Replace all the old import paths, change `"github.com/kubernetes/apimachinery"` to `"k8s.io/apimachinery"`.

Where did you import it: https://github.com/influxdata/telegraf/search?q=github.com%2Fkubernetes%2Fapimachinery&unscoped_q=github.com%2Fkubernetes%2Fapimachinery

**Comment by KateGo520** [comment]
@danielnelson @ssoroka  Could you help me review this issue? Thx :p

**Comment by ssoroka** [comment]
Sounds reasonable. I'd be in support of this change.

**Comment by KateGo520** [comment]
Same condition here.https://github.com/influxdata/telegraf/blob/master/go.mod（Line 66 & 151）
```
github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
gotest.tools v2.2.0+incompatible // indirect 
```
"github.com/gotestyourself/gotestyourself" and "gotest.tools" are the same repos.
You can solve the problem through this way:
Add replace statement in the go.mod file:
```
replace github.com/gotestyourself/gotestyourself => gotest.tools v2.2.0
```
Then clean the go.mod.

**Comment by ssoroka** [comment]
that doesn't seem to work

$ go mod tidy
go: gotest.tools@v2.2.0+incompatible used for two different module paths (github.com/gotestyourself/gotestyourself and gotest.tools)

**Comment by KateGo520** [comment]
You can try this：
`replace github.com/gotestyourself/gotestyourself => gotest.tools v2.3.0+incompatible`

**Comment by sjwang90** [comment]
@KateGo520 Would you be willing to open a PR with these changes?

**Comment by powersj** [comment]
Go.mod file uses k8s.io, so closing as fixed.
