### ISSUE TITLE
Windows Event Log input plugin

### ISSUE THREAD

**Issue by ofcoursedude** [influxdata/telegraf#7989]
## Feature Request

It would be beneficial to be able to gather windows event logs in a similar fashion as collecting syslog

### Proposal:

I am currently developing an input plugin with this functionality for my own personal use and would like to contribute. In the simplest form, I simply provide a []string with the event log names I wish to subscribe to. It implements the ServiceInput interface for an ongoing collection.

### Use case: 
Monitoring and alerting of Windows computers

**Comment by ofcoursedude** [comment]
Initial working version can be found at ofcoursedude/telegraf@be0de681c68a719f59cf76f115333154e895906d

**Comment by simnv** [comment]
@ofcoursedude check pr #8000

**Comment by sjwang90** [comment]
Thanks for your interest on building this plugin.  We already have a larger Windows Event Log input plugin issue at #4525. 

We would love your feedback on PR #8000 if there are any additional enhancements you'd like to see.
