### ISSUE TITLE
systemd_units plugin reports errors for "not-found" units

### ISSUE THREAD

**Issue by squidpickles** [influxdata/telegraf#7990]
SystemD's output when listing units changed in v245. When units are in `not-found` state, they include a `●` glyph in front. Previously, using `--no-legend` disabled output of this glyph, but now it's included regardless of that setting.

Related bug report: https://github.com/systemd/systemd/issues/15077

It appears the fix was merged, but I have encountered several systems running v246 (latest release) that still have this problem.

Adding `--plain` to the command invocation works across the old (pre-v245) and newer versions.

**Comment by srebhan** [comment]
Similar fix for the problem is in #8381.

**Comment by srebhan** [comment]
@squidpickles can you please test with current master after PR #7991 was merged!?

**Comment by squidpickles** [comment]
@srebhan It works! Fantastic, thanks.
