### ISSUE TITLE
[SNMP Input] Loops forever requesting Snmp table mapping 

### ISSUE THREAD

**Issue by sl1pm4t** [influxdata/telegraf#800]
I'm trying out the new snmp tables feature and find the SNMP Input loops forever requesting the table mapping OID from the server if the table has more than 32 entries. 

It's looping forever on this loop `for need_more_requests {` [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/snmp/snmp.go#L471).

The table I'm trying to query has 43 entries, and if I bump `maxRepetition` to 44 it no longer spins.

I'm submitting a PR shortly with a potential fix.

**Comment by titilambert** [comment]
@sl1pm4t THANKS for report and patch :)
