### ISSUE TITLE
Kafka sasl scram support

### ISSUE THREAD

**Issue by ajm-dev** [influxdata/telegraf#8003]
Hi there

Will it be possible to add sasl scram support to the telegraf kafka plugins.
We get the below error on the kafka cluster when trying to consume topics.

Kafka Log:
Unsupported SASL mechanism PLAIN

Telegraf Debug Output:
2020-08-19T05:49:41Z I! Starting Telegraf 1.15.2
2020-08-19T05:49:43Z E! [telegraf] Error running agent: starting input inputs.kafka_consumer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by AtakanColak** [comment]
As someone who added SASL_SCRAM to Telegraf output plugin in my local experiment area, this [link](https://github.com/Shopify/sarama/blob/master/examples/sasl_scram_client/main.go) gave me the example I needed to implement it. 

SASL_SCRAM was a pain which was quickly reverted to SASL_PLAINTEXT though. It caused problems with zookeeper and the rest of the kafka stack.

**Comment by tosheer** [comment]
Do you guys have any update on this i need it for consuming data from AWS MSK which now also support SASL/SCRAM

**Comment by luisgf** [comment]
Ping? Any news about that? I’m really interested

**Comment by ssoroka** [comment]
This should be supported now as of influxdata/telegraf#8318.
