### ISSUE TITLE
telegraf should support to set whether to use remote time

### ISSUE THREAD

**Issue by ciys** [influxdata/telegraf#8017]
## Feature Request

telegraf should support to set whether to use remote time.If set true,the data from telegraf has no timestamp,default use ouput endpoint time.
For example,current version telegraf send a metric to influxdb use telegraf time,not influxdb time.If every telegraf client time is not same,the time of data in influxdb are not same too.eventhough they are sendend in the same time.

**Comment by ssoroka** [comment]
How much is it off by? If you're talking about seconds or so, you could try using the agent setting `round_interval`. If you're talking more than that, isn't that the job of ntpd?

Using the timestamp of the output is likely to cause more problems than it solves.

**Comment by sjwang90** [comment]
Closing this issue since this isn't something we would resolve in Telegraf since as ssoroka mentioned, it will cause more problems.

If you are having any issues with your time stamps it best be resolved in query.
