### ISSUE TITLE
Error parsing /etc/telegraf/telegraf.conf, Undefined but requested output

### ISSUE THREAD

**Issue by win32nipuh** [influxdata/telegraf#8022]
I try to run the Telegraf Docker image connecting to Postgresql.
When I run Telegraf as a standalone app with the same config file it starts and works.
But When I run it in Docker i receive the error:
Error parsing /etc/telegraf/telegraf.conf, Undefined but requested output: postgresql

That is my telegraf.config
```
# Global tags can be specified here in key="value" format.
[global_tags]
  user = "$USER"
  location="Buenos"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Send metrics to PostgreSQL
[[outputs.postgresql]]
  connection = "host=localhost:5542 user=postgres password=postgres"
  table_template="CREATE TABLE IF NOT EXISTS {TABLE}({COLUMNS}); SELECT create_hypertable({TABLELITERAL},'time',chunk_time_interval := INTERVAL '1 week',if_not_exists := true);"


```
, what is wrong?

**Comment by sjwang90** [comment]
We don't have a PostgreSQL output plugin in Telegraf quite yet.  A PR #3428 is being worked on so unless you are testing it with that build it won't run with the latest download of Telegraf. 

Closing this for now as our issues are reserved for reproducible bugs/features.  Feel free to ask any further questions you may have on our [Community Slack](influxdata.com/slack) and you'll usually get a pretty fast response.

**Comment by win32nipuh** [comment]
Thanx!

**Comment by win32nipuh** [comment]
> We don't have a PostgreSQL output plugin in Telegraf quite yet. A PR #3428 is being worked on so unless you are testing it with that build it won't run with the latest download of Telegraf.
> 
> Closing this for now as our issues are reserved for reproducible bugs/features. Feel free to ask any further questions you may have on our [Community Slack](influxdata.com/slack) and you'll usually get a pretty fast response.

But this standalone version works with the same Telegraf.config (postgresql output) 
https://telegrafreleases.blob.core.windows.net/windows/telegraf.exe

Does it mean the PostgresSQL output plugin implemented?

**Comment by db-brasil** [comment]
Hello, how are you ?
I have been trying to record metrics on postgresql-timescaleb for a long time with telegraph, but without success!
You did it ?
