### ISSUE TITLE
Path is not open config compliant with the GNMI input

### ISSUE THREAD

**Issue by tallexer** [influxdata/telegraf#8024]
It seems the path/fields are being processed and all "-" are replaced with "_". I guess this is because of the following logic:
https://github.com/influxdata/telegraf/blob/bf0b376fc760b23d09d9d1f0864e32f30ff05bcf/plugins/inputs/gnmi/gnmi.go#L355

This is the result from a gNMI enabled router with the original code:
> interfaces,name=xe-0/0/0:0,path=/interfaces/interface,source=router01.xyz carrier_transitions=17i,in_multicast_pkts=476231i,in_octets=39526933i,in_pkts=476231i,out_multicast_pkts=784332i,out_octets=198832524i,out_pkts=784332i 1598279207752000000

For testing purposes I just recompiled with that logic turned to noop and it looks better:
> interfaces,name=et-1/1/11,path=/interfaces/interface,source=router01.xyz carrier-transitions=141i,in-broadcast-pkts=5714i,in-multicast-pkts=17645498i,in-octets=2405978182i,in-pkts=20963208i,in-unicast-pkts=3312034i,out-broadcast-pkts=5692i,out-multicast-pkts=17646688i,out-octets=780558506i,out-pkts=7989750i,out-unicast-pkts=4456128i 1598278853313000000

I have seen this logic on path/keys as well so I would assume it produces the same problem.

**Comment by tallexer** [comment]
```diff --git a/plugins/inputs/gnmi/gnmi.go b/plugins/inputs/gnmi/gnmi.go
index 3c5826b..4a9f380 100644
--- a/plugins/inputs/gnmi/gnmi.go
+++ b/plugins/inputs/gnmi/gnmi.go
@@ -352,7 +352,7 @@ func (c *GNMI) handleTelemetryField(update *gnmi.Update, tags map[string]string,
                jsondata = val.JsonVal
        }
 
-       name := strings.Replace(path, "-", "_", -1)
+       name := strings.Replace(path, "_", "-", -1)
        fields := make(map[string]interface{})
        if value != nil {
                fields[name] = value
@@ -392,7 +392,7 @@ func (c *GNMI) handlePath(path *gnmi.Path, tags map[string]string, prefix string
 
                if tags != nil {
                        for key, val := range elem.Key {
-                               key = strings.Replace(key, "-", "_", -1)
+                               key = strings.Replace(key, "_", "-", -1)
 
                                // Use short-form of key if possible
                                if _, exists := tags[key]; exists {
```

**Comment by sjwang90** [comment]
@sbyx do you have any input on this?

**Comment by sbyx** [comment]
That conversion is there because you guys asked me to add it.

**Comment by sspaink** [comment]
@tallexer mind linking to the documentation stating why using underscores is not open config compliant? I don't have any experience in open config so I couldn't find it myself but I am probably not looking in the right spot.

If it was a mistake using underscores we can definitely fix this, we would need to hide this change behind a configuration option to stay backwards compatible.
