### ISSUE TITLE
mongodb input plugin outputting +Inf metrics

### ISSUE THREAD

**Issue by prune998** [influxdata/telegraf#803]
Here is the exact error in the logs : 

2016/03/05 16:41:30 KAFKA PARSE ERROR
message: mongodb,datacenter_location=clichy,datacenter_rack=1,dc=axa,host=helene,host_type=vm,hostname=127.0.0.1:28017,state=PRI active_reads=0i,active_writes=0i,commands_per_sec=2i,deletes_per_sec=0i,flushes_per_sec=0i,getmores_per_sec=0i,inserts_per_sec=0i,member_status="PRI",net_in_bytes=493i,net_out_bytes=3123i,open_connections=28i,percent_cache_dirty=+Inf,percent_cache_used=+Inf,queries_per_sec=0i,queued_reads=0i,queued_writes=0i,repl_commands_per_sec=0i,repl_deletes_per_sec=0i,repl_getmores_per_sec=0i,repl_inserts_per_sec=0i,repl_queries_per_sec=0i,repl_updates_per_sec=0i,resident_megabytes=105i,updates_per_sec=0i,vsize_megabytes=818i 1457192490010009416
error: unable to parse 'mongodb,datacenter_location=clichy,datacenter_rack=1,dc=axa,host=helene,host_type=vm,hostname=127.0.0.1:28017,state=PRI active_reads=0i,active_writes=0i,commands_per_sec=2i,deletes_per_sec=0i,flushes_per_sec=0i,getmores_per_sec=0i,inserts_per_sec=0i,member_status="PRI",net_in_bytes=493i,net_out_bytes=3123i,open_connections=28i,percent_cache_dirty=+Inf,percent_cache_used=+Inf,queries_per_sec=0i,queued_reads=0i,queued_writes=0i,repl_commands_per_sec=0i,repl_deletes_per_sec=0i,repl_getmores_per_sec=0i,repl_inserts_per_sec=0i,repl_queries_per_sec=0i,repl_updates_per_sec=0i,resident_megabytes=105i,updates_per_sec=0i,vsize_megabytes=818i 1457192490010009416': invalid boolean

Issue is that there is no (or at least I can't see it) BOOLEAN in this log...

**Comment by sparrc** [comment]
these seem wrong:

```
percent_cache_dirty=+Inf,percent_cache_used=+Inf
```

where are those coming from? is telegraf generating those?

**Comment by prune998** [comment]
yes, this seems to be writen by the mongo input plugin...
Whatever, those values, set to +Inf, are not booleans :)
