### ISSUE TITLE
Error during Docker build

### ISSUE THREAD

**Issue by win32nipuh** [influxdata/telegraf#8036]
I tried to build Docker using \scripts\stretch.docker. Later I'd like to add output.postrgesql plugin/
But now it completed with errors. What I do wrong? 

PS D:\TGRF\telegraf-master> docker build -f .\scripts\stretch.docker .
Sending build context to Docker daemon  11.01MB
Step 1/11 : FROM golang:1.13.13 as builder
1.13.13: Pulling from library/golang
e9afc4f90ab0: Pull complete
989e6b19a265: Pull complete
af14b6c2f878: Pull complete
5573c4b30949: Pull complete
d4020e2aa747: Pull complete
bf29e9fce905: Pull complete
22d7a6be306c: Pull complete
Digest: sha256:68874af4f0135e3b57fb80ad8a80cdbad6af0b35033a130a3554b91712672ff4
Status: Downloaded newer image for golang:1.13.13
 ---> f4d61fed49ec
Step 2/11 : WORKDIR /go/src/github.com/influxdata/telegraf
 ---> Running in 9b9cff721329
Removing intermediate container 9b9cff721329
 ---> 1790cfeae0bd
Step 3/11 : COPY . /go/src/github.com/influxdata/telegraf
 ---> d97b7aff242e
Step 4/11 : RUN make go-install
 ---> Running in 18c320c11e2d
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
make: *** No rule to make target 'go-install'.  Stop.
The command '/bin/sh -c make go-install' returned a non-zero code: 2

**Comment by ssoroka** [comment]
This should be fixed in 1.16.0. Let us know if you're still having problems.
