### ISSUE TITLE
Error in plugin: exec: exit status 1 for command vsanmetrics.py

### ISSUE THREAD

**Issue by somersbd** [influxdata/telegraf#8040]
I'm trying to add VSAN metrics using the python scripts in vmwares sdk. Command runs from cli without error but has this errors when running as command in the telegraf config. Upgraded to nightly build 1.16.0 trying to get vsan metrics.

 Error in plugin: exec: exit status 1 for command vsanmetrics.py

**Comment by sjwang90** [comment]
Can you provide your config?

**Comment by somersbd** [comment]
This is one of the command lines inside the telegraf.conf, I changed the vcenter login info to generic. I left the cluster info because it does have a space in the name and needs the ' ' . Will this help?

[[inputs.exec]]

   interval = "60s"
   commands = [
       "python3 /etc/vsan/vsanmetrics.py -s virtual.center.fqdn -o 443 -u telegraf-readonly@vsphere.local -p secret -c 'DMZ Cluster' --performance",
   ]
   timeout = "120s"
   data_format = "influx"

**Comment by somersbd** [comment]
This is the full config

[telegraf-upload.txt](https://github.com/influxdata/telegraf/files/5138731/telegraf-upload.txt)

**Comment by powersj** [comment]
Hi!

Sorry no one has commented in a while. Were you able to resolve the issue?

Based on the error status, were you able to run the command outside of telegraf? If so, could you provide some example output? The exec plugin is expecting line protocol formatted data as well.

Thanks!
