### ISSUE TITLE
CloudWatch input: Support both GetMetricData (1.12+) and GetMetricStatistics (1.11 and earlier) via options

### ISSUE THREAD

**Issue by jcmcken** [influxdata/telegraf#8041]
### Proposal:

Allow Telegraf user option to configure either the ``GetMetricData`` API (Telegraf 1.12+) or the ``GetMetricStatistics`` API (Telegraf 1.11 and earlier) in the CloudWatch input. E.g. as a boolean -- ``use_get_metrics_statistics_api = true`` or an enum -- ``api = "get_metrics_statistics"``

The switch to this newer API, which changed the shape of the metrics, seems out of place considering it was only a minor release of Telegraf. 

### Current behavior:

The input is hard-coded to use ``GetMetricData``

### Desired behavior:

Allow the user to configure the input to use ``GetMetricStatistics`` if desired (even though this may be more costly) so that unit information is retained in the metrics.

### Use case:

The ``GetMetricData`` API, which the CloudWatch input switched to in Telegraf v1.12, does not include the units of the metrics being ingested. This makes it difficult to display metrics to users (e.g. in Grafana), since they now have to look up what units each metric takes. That, or it requires hard-coding units into dashboards -- but with hundreds of CloudWatch metrics, this becomes operational burdensome to say the least.

**Comment by powersj** [comment]
Hi,

Sorry no one ever got back to you.

It does sound like this change was a regression in how metrics were shaped. Is this still something that makes sense? A brief search does show that the `GetMetricStatistics` still exists.

Thanks!
