### ISSUE TITLE
Add Headers map to inputs.prometheus

### ISSUE THREAD

**Issue by rnsc** [influxdata/telegraf#8058]
## Feature Request

I'd be interested in having the possibility to add specific headers to the GET request done by the inputs.prometheus plugin.

### Proposal:

As it was mentioned [here](https://github.com/influxdata/telegraf/issues/3222#issuecomment-329026043), maybe we can just add the same headers map[string]string that exists for other inputs plugin like httpjson.

We would then have:

```
[[inputs.prometheus]]
  urls = ["http://localhost:9100/metrics"]
  [inputs.prometheus.headers]
    X-Auth-Token = "123"
    Another-Header = "MyCustomerHeader"
```

### Use case: 
I have a use case where the application requires a specific header to be set.

I'm willing to help with the PR if needed, but I'm opening this feature request first to see if it's accepted or not.

**Comment by rnsc** [comment]
I already created the changes in a personal fork:
https://github.com/rnsc/telegraf/commits/feature/inputs-prometheus-headers

**Comment by 00Asgaroth00** [comment]
I would be interested in this functionality too.

As an example, an application like PowerDNS's DNSDist has a web server that exposes its metrics in prometheus format (see [here](https://dnsdist.org/guides/webserver.html#get--metrics)), however, this requires that the X-API-Key header is set to authorise the request (see [here](https://dnsdist.org/guides/webserver.html#dnsdist-api))

Adding this functionality would allow me to query DNSDist directly for its prometheus metrics

**Comment by rnsc** [comment]
Hello,

Can this be looked at?
Thanks,

**Comment by rnsc** [comment]
Hello @ssoroka @sjwang90 ,

Can you have a look at this Feature request and the PR I made?
Do you think it can be merged?
Or is it not a desired feature?

Thanks,

**Comment by vjanssens** [comment]
Agree, this is something we need as well. Our endpoint exposes Prometheus metrics but needs a specific HTTP authentication header which `bearer_token_string` does not provide.
