### ISSUE TITLE
Collect Wireguard metrics over ssh (edgerouter ERX)

### ISSUE THREAD

**Issue by spcqike** [influxdata/telegraf#8059]
Hi all,

i recently switched from wireguard on my raspberry to an ERX.
of course, telegrafs wireguard input can't handle a remote wireguard instance, but i would like to get the metrics per peer. via SNMP i can grab the overall wg0 traffic, but not per single peer.

so, is it somehow possible to collect metrics over ssh?
my raspberry can ssh to the ERX with key authentification, so it can execute "ssh ubnt@<ip> "sudo wg"" and it will see the output. 

>pi@raspi:~ $ ssh ubnt@IP "sudo wg"
>Welcome to EdgeOS
>
>By logging in, accessing, or using the Ubiquiti product, you
>acknowledge that you have read and understood the Ubiquiti
>License Agreement (available in the Web UI at, by default,
>http://IP) and agree to be bound by its terms.
>
>interface: wg0
>  public key: pubKey
>  private key: (hidden)
>  listening port: 51877
>
>peer: pubkey1
>  endpoint: IP:Port
>  allowed ips: IPs
>  latest handshake: 1 second ago
>  transfer: 2.24 GiB received, 55.17 GiB sent
>
>peer: pubkey2
>  endpoint: IP:Port
>  allowed ips: IPs
>  latest handshake: 1 minute, 27 seconds ago
>  transfer: 15.29 GiB received, 16.33 GiB sent

thanks in advance :)

**Comment by sjwang90** [comment]
Hi @spcqike, we reserve Telegraf issues for bug or reproducible problems.  Feel free to drop into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this answered quicker.
