### ISSUE TITLE
Enable Authorization basic auth header pass-through when using influxdb_listener input 

### ISSUE THREAD

**Issue by thechile** [influxdata/telegraf#8063]
## Feature Request

I have some devices configured to send metrics to influx but a recent bug added a field called 'status' which collides with a tag of the same name. I can't easily correct all their configurations so i wanted to place telegraf in front of influx as a proxy to drop the 'status' field. 

This is the config i came up with, both telegraf and influx are deployed on same server. 

```
[[inputs.influxdb_listener]]
  service_address = "10.137.109.138:8086"

  tls_cert = "/etc/pki/tls/certs/telegraf.pem"
  tls_key = "/etc/pki/tls/private/telegraf.key"

  fielddrop = ["status"]

[outputs.influxdb]]
 urls = ["http://10.137.109.138:8087"]

```

### Current behavior:

The problem i have is the target database needs a username and password, and different devices use different databases and credentials. So one example of a source devices telegraf configuration is this:

```
[[outputs.influxdb]]
  urls = ["https://influx.aaa.bbb.com:28086"]
  database = "host_metrics"
  username = "telegraf_user"
  password = "xxxxxxxxxxxxx"
  insecure_skip_verify = false
```
When the `influxdb_listener` receives events it can't be told to proxy the basic auth `Authorization:` header on to the output.

### Desired behaviour:

I would like to use `influxdb_listener` to received events and mutate the data such as drop fields or tags, then proxy onward to the output but include the original `Authorization:` header.

**Comment by thechile** [comment]
I had a look as well at `http_listener_v2`, i thought i could use the `http_header_tags` feature to capture the `Authorization` header e.g. `  # http_header_tags = {"Authorization" = "Authorization"}`  to later use it in the `outputs.influxdb` e.g. 

```
http_headers = {"Authorization" = tag['Authorization'] }
```

But i don't think you can reference tags like that so the above won't work either.

**Comment by ssoroka** [comment]
I think you're on the right track with http_listener_v2

`http_header_tags = {"Authorization" = "authorization_header"}`

will put the Authorization header into a tag named `authorization_header`

You might just be able to have multiple outputs and route to the one you want. There should be enough processors to rename or manipulate the metrics in pretty much any possible way, and to figure out which output they go to using [selectors](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#selectors).

**Comment by powersj** [comment]
@thechile,

Were you able to get what you needed using the `http_header_tags` option?
