### ISSUE TITLE
inputs.kafka_consumer can't set topic name as tag using topic_tag = ""

### ISSUE THREAD

**Issue by sgreszcz** [influxdata/telegraf#8067]
### Relevant telegraf.conf:
```
[[inputs.kafka_consumer]]
  ## Kafka brokers.
  brokers = [{{ sa_kafka_brokers }}]
  ## Topics to consume.
  topics = [{{ kafka_topics_ucv }}]
  ## When set this tag will be added to all metrics with the topic as the value.
  topic_tag = ""
```

### Steps to reproduce:

Added the topic_tag = "" line as per the inputs.kafka_consumer documentation.  See above.

### Expected behavior:

I would expect the topic name to be written as a tag to the metric.  I'm consuming from two different topics contained in the kafka_topics_ucv variable.

### Actual behavior:

I get all the metrics into my elasticsearch index using the outputs.elasticsearch configuration, but there is no tag with the kafka topic name.

**Comment by M0rdecay** [comment]
You need to set a value for this parameter:
```
topic_tag = "topic_name"
```
Then the tag `topic_name` with the topic name as a value will be added to each metric - https://github.com/influxdata/telegraf/blob/master/plugins/inputs/kafka_consumer/kafka_consumer.go#L402

**Comment by sgreszcz** [comment]
OK, I misunderstood the documentation.  I thought that if you put a string inside the "" it would use that as the topic_tag.  This worked.  Thank you!
