### ISSUE TITLE
Able to see the "user connections" metrics per database rather than per instance

### ISSUE THREAD

**Issue by sunilgks** [influxdata/telegraf#8070]
## Feature Request
Able to gather  "user connections" metrics per database rather than per instance
Opening a feature request kicks off a discussion.

### Proposal:
Request  for "user connections" metrics to be reported per database
### Current behavior:
 "user connections" metrics reported instance
### Desired behavior:
Request  for "user connections" metrics to be reported per database
### Use case: 
On an instance we usually have multiple databases

**Comment by reimda** [comment]
Which plugin are you referring to?

**Comment by sunilgks** [comment]
MS SQL Server plugin

**Comment by sspaink** [comment]
@sunilgks are you still interested in seeing this feature request implemented?
