### ISSUE TITLE
Telegraf not pulling in all Solr MBean metrics

### ISSUE THREAD

**Issue by sjmaret** [influxdata/telegraf#8074]
Hello,

I'm unable to access your Slack channel due to our company's firewall rules so am taking this route for assistance.

We are working on setting up Solr metrics to be viewable via Grafana using InfluxDB datasource.

I have created the solr_inputs.conf file with the following details:

========

![image](https://user-images.githubusercontent.com/4137748/92031068-9d80da00-ed2d-11ea-9209-7f6141e80565.png)

============
Executed a test > telegraf --config /etc/telegraf/telegraf.d/solr_inputs.conf --test

But the test is returning back only a subset of the metrics (solr_admin, solr_cache & solr_core) compared to what is returned when i call the http://<hostname>:8983/solr/core0/admin/mbeans?stats=true&wt=xml.  

![image](https://user-images.githubusercontent.com/4137748/92030997-80e4a200-ed2d-11ea-970d-195c3aa59bc7.png)

============

Are there any other configurations that need to be applied?  

Any assistance is greatly appreciated

Thanks
===========

Solr 7.5
Telegraf 1.9.4

**Comment by sjmaret** [comment]
I've intentionally changed our hostname to <hostname> for security reasons.

**Comment by reimda** [comment]
It looks like telegraf's solr input is hard coded to restrict to a few categories.  The query you mentioned doesn't restrict by category.  The query telegraf uses is here:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/solr/solr.go#L18

Adding other categories for telegraf monitor would require a code change.

Your version of telegraf (1.9.4) is relatively old- Feb 2019.  Newer versions added HTTP basic auth for solr.

**Comment by sjmaret** [comment]
I also found that line of code post sending the support request.  Looks like the latest version also has the same URL string hard-coded.  

I also found that there is work being done on a new solrmetric plugin that will use the Metrics API but not sure when it will be available.
https://github.com/influxdata/telegraf/pull/5908

Thank you for the response. Much appreciated.
