### ISSUE TITLE
InfluxDB v2 default port changing from 9999 to 8086 for the next release

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#8080]
we will need to update the influxdb_v2 output plugin docs and defaults.

pr for the change to influxdb: https://github.com/influxdata/influxdb/pull/19494

**Comment by sjwang90** [comment]
@ssoroka suggested to time this update simultaneously with the next OSS release. I think we'll target the 1.16 release around OSS RC or GA.

When implement port change, add warning message of port mismatch and try new 8086 port.
