### ISSUE TITLE
Bad Request: message is too long

### ISSUE THREAD

**Issue by xcage7** [influxdata/telegraf#8088]
i am trying to send a long message but it says message is too long.

```
code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: message is too long'
  },
  description: 'Bad Request: message is too long'
```

any fix?

**Comment by ssoroka** [comment]
can you provide some more context? What was your Telegraf config? where did you get this message? Any log output? 

If it's from InfluxDB, it could be that your batch size is too large.

**Comment by stephanie-engel** [comment]
Closing this issue because we don't have enough information to make an actionable decision.

**Comment by xcage7** [comment]
What more do you need?

**Comment by stephanie-engel** [comment]
Hi @xcage7,

We would need answers to the questions that @ssoroka asked:
> can you provide some more context? What was your Telegraf config? where did you get this message? Any log output?
> 
> If it's from InfluxDB, it could be that your batch size is too large.

If it helps, if you click **New Issue** > **Bug Report**, then we have a bug report template that you can use to answer all of the necessary questions so we can help you solve this problem.
