### ISSUE TITLE
Grafana vsphere Dashboard - Using grafana,telegraf and influxdb. Does this affect the vsphere environment performance like the read/write IOPs,bandwidth of host/datastore?

### ISSUE THREAD

**Issue by Jen-apjen** [influxdata/telegraf#8090]

**Comment by sjwang90** [comment]
Hey @Jen-apjen, we reserve GitHub issues for reproducible bugs.  Please ask this question in our [Community Slack](www.influxdata.com/slack) with some more detail and someone will get it answered.
