### ISSUE TITLE
Redfish plugin error parsing input: invalid character ‘<’

### ISSUE THREAD

**Issue by naorw** [influxdata/telegraf#8093]
**System info:**

HP iLO 4 ProLiant
Firmware Version 2.73
Telegraf 1.15.2 (git: HEAD cd037b49) on CentOS 7

**Steps to reproduce:**

1. Following documentation, configure Redfish plugin with HP iLO details.
Skipping chain & host verification:
 insecure_skip_verify = true
Setting system id:
computer_system_id="1"

2. Running Telegraf in test mode:
telegraf --debug --test

**Expected behavior:**

connection and redfish data collection.

**Actual behavior:**

[inputs.redfish] Error in plugin: error parsing input: invalid character '<' looking for beginning of value

**Additional info:**

Looks like json.Unmarshal is failing to parse the response.
running curl with same url: https://serverIP/redfish/v1/systems/1 -i --insecure -u user:"pass" -L 
generates response starting with 
{"@odata.context":"/redfish/v1/$metadata#Systems/Members/$entity","@odata.id":"/redfish/v1/Systems/1/",
preceded by metadata.

**Comment by ssoroka** [comment]
Thanks for the bug report!

cc @sarvanikonda

**Comment by smizach** [comment]
I also had this problem in my environment and tracked it down to ilo4 not being fully redfish compliant unless the client sets an optional data-versioning header to explicitly require redfish formatting. I've opened a PR that adds sending that header.
