### ISSUE TITLE
execd processor does not handle newline characters in strings

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#8095]
### Actual behavior:
If the external processor returns data in the `influxdb` format in several lines, a parsing error occurs:
```
2020-09-08T12:00:39Z E! [processors.execd] Parse error: metric parse error: expected tag at 1:65: "some data here"
```

### Additional info:
The situation is well described here - https://github.com/influxdata/telegraf/issues/7461
But now it occurs in the execd processor

**Comment by ssoroka** [comment]
Should be easy enough to resolve. Will take a look at it
