### ISSUE TITLE
Update prometheus common module version to fix "reading text format failed" 

### ISSUE THREAD

**Issue by superbool** [influxdata/telegraf#8098]
Here is a prometheus metrics output:
```
# HELP pulsar_function_received_total_1min Total number of messages received from source in the last 1 minute.
# TYPE pulsar_function_received_total_1min counter
pulsar_function_received_total_1min{tenant="kop",namespace="kop/functions",name="myTestFunction02",instance_id="0",cluster="pulsar-cluster-1",fqfn="kop/functions/myTestFunction02",} 0.0
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_102-b14",vendor="Oracle Corporation",runtime="Java(TM) SE Runtime Environment",} 1.0
```
The newest version of telegraf get an error:
```
[inputs.prometheus] Error in plugin: error reading metrics for http://localhost:8080/metrics/: reading text format failed: text format parsing error in line 2552: second TYPE line for metric name "jvm_info", or TYPE reported after samples
```

I guess need to update (prometheus common module)[https://github.com/prometheus/common]  new version to fix the problem.

**Comment by hammacktony** [comment]
I am getting the same error. Any update on this?

**Comment by Jagularr** [comment]
Hi, using your prometheus output I'm able to process it through the plugin without issue. However, if I add a second #TYPE jvm_info (or just duplicate the output) and process it, it seems to have the same error. Is this the entire output or could there perhaps be some other output stream example that perhaps has duplicate TYPEs or HELPs? Also want to add that using the updated prometheus module here doesn't seem to affect the outcome.

**Comment by ssoroka** [comment]
we're going to address this

**Comment by ssoroka** [comment]
We've looked into this, and it seems like the prometheus input and parser are doing the right thing, and that the duplicate type info is coming from the service being queried. Are you querying prometheus, or a custom server that's generating Prometheus-compatible metrics?

**Comment by ssoroka** [comment]
According to https://github.com/prometheus/common/issues/265, prometheus line protocol should not have duplicate types in it, and it would seem the service you're using to generate the metrics is incorrectly encoding them.

Going to close for now, let us know if there's anything more you have to add. 

Cheers.
