### ISSUE TITLE
Net monitoring occupies cpu resources too high,I recommend adding ignore configuration

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#8099]
## Feature Request

Net monitoring occupies cpu resources too high,I recommend adding ignore configuration
### Proposal:
When there are hundreds of interfaces or even more on a node, it is found that the telegraf monitoring net occupies too high CPU resources, takes a long time, and often has many interfaces that can be ignored. In the course of practice, I found that the parameter ‘interfaces’ (input.net) is not very friendly. Often we can’t control what we want, and more clearly what we can ignore.
By adding ignore_interfaces configuration, avoid unnecessary resource consumption.

### Current behavior:
interface number:
      cat /proc/net/dev |wc
      400
time log:  gather finish time consume:16.355331743s
 cpu: 71.3

### Desired behavior:
      add config ignore_interfaces, Skip the check and ignore the interface to reduce CPU resource occupation

**Comment by powersj** [comment]
Hi,

If you are using `inputs.net`, that input already has an option to specify the specific interfaces that you are interested in:

```
interfaces = ["eth*", "enp0s[0-1]", "lo"]
```

Could you use this to filter on the specific ones you are after?

Thanks!
