### ISSUE TITLE
net interface status 'up/down' monitoring

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#8100]

**Comment by sjwang90** [comment]
Hi @fcddk, it is not clear what you are asking. In addition, we reserve Telegraf issues for bug or reproducible problems.  Feel free to drop into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can help you with your Telegraf questions.

**Comment by ssoroka** [comment]
You could potentially do this with an exec script. see inputs.exec

**Comment by fcddk** [comment]
Can it be judged by net.Flags?
