### ISSUE TITLE
http plug-in support webservice body parameters as xml format 

### ISSUE THREAD

**Issue by vicochan** [influxdata/telegraf#8101]
I need to use telegraf's http plugin to collector http api status.
The problem is that:The api input parameter is XML format, and its output is JSON format.
Does HTTP plug-in support? How to do it？

example:
[[inputs.http]]
  urls = ["http://127.0.0.1:3000/WebService/example.asmx?op=RegionZlVaryRealtime"]
  method = "POST"
  headers = {"Content-Type"="text/xml"}
  body = {'<?xml version="1.0" encoding="utf-8"?>
	<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"		xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
	<soap12:Body>
		<RegionZlVaryRealtime xmlns="http://tempuri.org/">
		 <fnameid>AG5330</fnameid>
		<impregionid></impregionid>
	</RegionZlVaryRealtime>
	</soap12:Body>
	/soap12:Envelope>'}
  data_format = "json"
  json_strict = true
  json_query = "data.@reverse.0"

**Comment by sjwang90** [comment]
If the output is in JSON format, you should be able to use the [JSON parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json).  Do you mind dropping this question into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/)? We reserve Telegraf issues for bug or reproducible problems. Please provide your config and a sample that your HTTP is outputting.

**Comment by vicochan** [comment]
yes ,sure
confing :
[[inputs.http]]
  urls = ["http://127.0.0.1:3000/WebService/example.asmx?op=RegionZlVaryRealtime"]
  method = "POST"
  headers = {"Content-Type"="text/xml"}
  body = '<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <RegionZlVaryRealtime xmlns="http://tempuri.org/">
      <fnameid>AG5330</fnameid>
      <impregionid></impregionid>
    </RegionZlVaryRealtime>
  </soap12:Body>
</soap12:Envelope>'
  data_format = "json"
  json_strict = true
  json_query = "data.Crowds1"

telegraf test results:
![image](https://user-images.githubusercontent.com/20240490/92668542-b26af800-f341-11ea-8f59-014d9691cbb3.png)

webservice api outputting:
{
    "status": 200,
    "statustext": "success",
    "data": {
        "Crowds1": 4013,
        "Crowds1_Rate": -10.26,
        "Crowds_Add": 230,
        "V_Crowds_Add_Rate": -161.17,
        "Region_Id": "AG5330",
        "Impregionid": "0Z0VW3SN6YXW",
        "Snaptime": "2020-09-07 15:05:00",
        "Crowds": 8177,
        "V_Crowds_Speed": -152,
        "Crowds_Rate": 0.62,
        "V_Crowds_Rate": 0,
        "V_Crowds_Speed_Rate": 76.74,
        "Avg_Ntime": 2.2078,
        "Avg_Prate": -1.9
    }
}

**Comment by sjwang90** [comment]
What is at line 3198?

**Comment by vicochan** [comment]
![image](https://user-images.githubusercontent.com/20240490/92940417-af772100-f481-11ea-884f-419e3c632597.png)

**Comment by sjwang90** [comment]
Try removing the `body` from your config. Do you think you could find me in the [community slack](influxdata.com/slack)? May be easier to troubleshoot there.
