### ISSUE TITLE
Make Kubernetes pod discovery engine available to any input plugin

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#8105]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Make the Kubernetes pod discovery engine available to any input plugin.
This will allow conveniently collect metrics from pods that have not only `prometheus` endpoints

### Current behavior:
Now collection of metrics in k8s with a convenient pod detection mechanism is available only for prometheus input.

### Desired behavior:
Ability to set pod discovery parameters in any input plugin. Something like:
```toml
[[inputs.jolokia2_agent]]
  kubernetes_discovery = true
....

```

### Use case: 
Unfortunately, not always all applications located in k8s are able to provide a prometheus endpoint. Sometimes it can be jolokia endpoints/own endpoints, metrics from which can be collected via http.

At the moment, collecting metrics from such applications is possible only after the application itself is improved (which, sometimes, can be laborious). 
Another option is to deploy a telegraf sidecar that collects metrics and provides an endpoint in the right format. This solution entails risks - in the event of problems with the sidecar (for example, memory problems), the entire pod can be restarted or rescheduled, even if the main application works correctly.

For example, we can specify the endpoint and port in the same labels as for prometheus, and on the plugin side, specify selectors to filter the list of served pods.
In this case, the formation of the final `url` for collecting metrics will not differ from what is being performed now in the prometheus input.

It will also become easier to do after transferring the Prometheus parser to parsers - https://github.com/influxdata/telegraf/pull/7778.

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you yet.

I do think that your suggestion about telegraf sidecar is the right direction to go here, rather than something directly in Telegraf. There are a number of helm charts like the [telegraf operator](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-operator) which would be a better fit for this type of request.

I hope that or the other sidecar helm chart work for your scenario.
