### ISSUE TITLE
DATA: read latency graph

### ISSUE THREAD

**Issue by Aynury** [influxdata/telegraf#8106]
Hello,

Values in the DATA : read latency values seem wrong in our systems. When I get actual values from the system I see the latency about 1 or 2 ms. The graphic shows me about 100 ms latency. How can we fix this ?

**Comment by Aynury** [comment]
Hi,
Actually, the DMV that the values are taken shows the cumulative values. Maybe, It would be better to calculate the latency by divisioning the io_stall values to number of executions.

For example; overall read latency can taken by the query below.  
[ReadLatency] =
        CASE WHEN [num_of_reads] = 0
            THEN 0 ELSE ([io_stall_read_ms] / [num_of_reads]) END,

**Comment by Aynury** [comment]
Hello,

Could you have chance to check th queries for data latency ? 

Thanks

**Comment by ssoroka** [comment]
Which plugin are you talking about here?

**Comment by sjwang90** [comment]
Hi @Aynury, can you let us know what plugin you're running into these read data latency mismatches?

**Comment by powersj** [comment]
I'm going to close this based on the need more info label and no additional updates.

If you do have time and are still seeing this can you please provide the requested info.

Thanks!
