### ISSUE TITLE
Community Questions 9/11

### ISSUE THREAD

**Issue by mhall119** [influxdata/telegraf#8116]
Can someone help answer the following questions from the community forums?

- [Parsing error in Redfish plugin, getting '<' instead of JSON](https://community.influxdata.com/t/redfish-error-parsing-input-invalid-character/15866)
- [Bad Request: Message too long error](https://community.influxdata.com/t/telegraf-bad-request-message-is-too-long/15871)
- [Trying to use tagpass on only a subset of measurements from an input](https://community.influxdata.com/t/metrics-filtering-combine-namepass-and-tagpass/15852/2)
- [Trying to write logstash geoip data to InfluxDB but getting a boolean conversion error](https://community.influxdata.com/t/logstash-influxdb-output-with-geoip-feature/15881/2)
- [Question about the inputs.gmni plugin vs the inputs.cisco_telemetry_mdt plugin](https://community.influxdata.com/t/telegraf-gnmi-input-plugin/15795)
- [Error trying to configure TLS with inputs.cisco_telemetry_gnmi plugin](https://community.influxdata.com/t/does-telegrafs-cisco-gnmi-input-plugin-support-advanced-tls-configuration/15914)
- [Garbage values for a datetime field in the snmp plugin](https://community.influxdata.com/t/include-date-and-time/15387/2')
- [Looking for basic guide to running Telegraf with Docker](https://community.influxdata.com/t/telegraf-in-docker-basic-guide/15932)
- [Looking for an input plugin to get network connection usage metrics from a Linux host](https://community.influxdata.com/t/telegraf-input-plugin-for-bandwidh/15942)

Thanks!

**Comment by ssoroka** [comment]
- `Bad Request: Message too long error` this is still a support issue. No information to go off of, and likely user error.
- `logstash geoip data to InfluxDB but getting a boolean conversion error` seems like you're on the right track. Line protocol supports bools fine.
- `Looking for basic guide to running Telegraf with Docker` not sure what to do here. Seems like a support issue.
