### ISSUE TITLE
example of telegraf continious query

### ISSUE THREAD

**Issue by keith6014** [influxdata/telegraf#8128]
Looking for an example of continious query with telegraf + influxdb. I want to downsample all data 2 weeks prior Hopefully its simple but online I couldn't find a good example.

**Comment by ssoroka** [comment]
InfluxDB does this for you. check out the downsampling documentation. 
InfluxDB 2.x https://docs.influxdata.com/influxdb/v2.0/process-data/common-tasks/downsample-data/
InfluxDB 1.x https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/
