### ISSUE TITLE
[inputs/statsd] Add support for Distribution metrics for compatibility with DataDog (DogStatsD)

### ISSUE THREAD

**Issue by gerilya** [influxdata/telegraf#8134]
## Feature Request

telegraf's statsd input plugin supports datadog statsd format with `parse_data_dog_tags=true` flag.
This is a great feature which allows using telegraf as a drop-in replacement for DataDog's agent.
Unfortunately, it does not support [Distributions](https://docs.datadoghq.com/metrics/distributions/#counting-distribution-metrics) metric type.

### Proposal:

Add support for distributions type of metrics to provide full compatibility with DataDog's statsd (DogStatsD).

### Current behavior:

When sending distributions metrics to telegraf, the metrics are dropped generating the following error in the logs:

```
Aug 10 08:55:44 mytest-i-02d65c1fc7f587007.sonic-us telegraf[3719]: 2020-08-10T08:55:44Z E! [inputs.statsd] Metric type "d" unsupported
```

### Desired behavior:
Same behaviour as in DogStatsD, ideally implemented the same way to provide identical behaviour. That is, send all raw data collected during the flush interval to the output like DogStatsD does.

### Use case: 

Seamless migration from DataDog.

**Comment by sjwang90** [comment]
If anyone is interested and submitting a PR for adding Distribution metrics this seems like a nice feature to get in for `inputs.statsd`

**Comment by ppsreejith** [comment]
@sjwang90 I've raised a PR to add support for this 😄. Let me know of any changes required to merge this 👍

**Comment by gerilya** [comment]
@sjwang90 as v1.16 went out approx one month ago, I am wondering whether you have an ETA for merging this nice feature into the master branch. Thank you

**Comment by sjwang90** [comment]
There hasn't been any reviews on the PR yet, so we'll get someone to take a look. 

@gerilya Can you confirm you've tested the PR and haven't run into any problems? Feedback from interested users helps expedite the PR process.

**Comment by gerilya** [comment]
@sjwang90 yes, I can confirm we are using this in production since Nov 25.
Our custom telegraf version is basically telegraf v1.16.2 + PR https://github.com/influxdata/telegraf/pull/8179/files for distribution metrics support.

This is a killing feature for everyone looking to migrate from DataDog.  Big thanks to @ppsreejith !
