### ISSUE TITLE
[inputs/infiniband] Plugin should not fail when iwarp driver is loaded

### ISSUE THREAD

**Issue by jose-d** [influxdata/telegraf#8135]
### Relevant telegraf.conf:

```toml

# Gets counters from all InfiniBand cards and ports installed
[[inputs.infiniband]]
  # no configuration

```

### System info:

**Telegraf**: telegraf-1.15.3-1.x86_64
**OS**: CentOS Linux release 8.2.2004 (Core)
**Linux**: 4.18.0-193.14.2.el8_2.x86_64

##### ethernet:

```
# lspci | egrep -i 'network|ethernet'
3d:00.0 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GBASE-T (rev 09)
3d:00.1 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GBASE-T (rev 09)
#
```
##### Infiniband:

```
# lspci | egrep -i 'infiniband'
af:00.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4]
#
```
### Steps to reproduce:

1. install latest (8.2 ATM) centos8 with `@infiniband` software selection [[link](https://docs.centos.org/en-US/centos/install-guide/SoftwareSpoke-x86/)]
2. install latest Telegraf (1.15.3-1 ATM)
3. enable Infiniband plugin

### Expected behavior:

Infiniband plugin will collect available counters from available Infiniband interfaces and push them to configured _outputs_. Possibly, device-whitelist could be an option how to avoid parsing broken/not supported network devices.

### Actual behavior:

Infiniband plugin assumes that everything in `/sys/class/infiniband/` is actually real infiniband device. But having EG Intel x722 Ethernet card means that we do have directories also pro iWARP[[link](https://en.wikipedia.org/wiki/IWARP)]:

```
# ls -1 /sys/class/infiniband/
i40iw0
i40iw1
mlx5_0
#
```
Directories i40iwX have unexpected file structure which is not being correctly parsed by Telegraf infiniband plugin:

```
# journalctl --output=short-iso -xe | tail -n 5
2020-09-16T11:48:20+0200 n3 telegraf[1403359]: 2020-09-16T09:48:20Z E! [inputs.infiniband] Error in plugin: open /sys/class/infiniband/i40iw1/ports/1/counters: no such file or directory
2020-09-16T11:48:30+0200 n3 telegraf[1403359]: 2020-09-16T09:48:30Z E! [inputs.infiniband] Error in plugin: open /sys/class/infiniband/i40iw1/ports/1/counters: no such file or directory
2020-09-16T11:48:40+0200 n3 telegraf[1403359]: 2020-09-16T09:48:40Z E! [inputs.infiniband] Error in plugin: open /sys/class/infiniband/i40iw1/ports/1/counters: no such file or directory
2020-09-16T11:48:50+0200 n3 telegraf[1403359]: 2020-09-16T09:48:50Z E! [inputs.infiniband] Error in plugin: open /sys/class/infiniband/i40iw1/ports/1/counters: no such file or directory
2020-09-16T11:49:00+0200 n3 telegraf[1403359]: 2020-09-16T09:49:00Z E! [inputs.infiniband] Error in plugin: open /sys/class/infiniband/i40iw1/ports/1/counters: no such file or directory
#
```

**Comment by jose-d** [comment]
isn't it @willfurnell who might know how to fix this?

**Comment by willfurnell** [comment]
@jose-d I think you'll need to raise an issue with the upstream library actually used to get the stats here: https://github.com/Mellanox/rdmamap

The code that I have written just uses that library to get the stats.

**Comment by jose-d** [comment]
> @jose-d I think you'll need to raise an issue with the upstream library actually used to get the stats here: https://github.com/Mellanox/rdmamap
> 
> The code that I have written just uses that library to get the stats.

yup, I already took quick look into plugin code and I'm thinking what to do/ how to fix/improve this particular behavior _correctly_..

What rdmamap devs say at readme: 

> This is golang package that provides map of rdma device with its character and network devices.

so they do not promise to return Infiniband-only devices, they return list of RDMA devices.. This brings the idea to do some filtering/preprocessing in `inputs/infiniband`..

Possible improvement could be
1. if expected files (`*/ports/1/counters`) are not found, throw warning and ignore the device - I think easy to implement
2. introduce some configuration option, similar to the one in inputs/net:

```
# cat inputs_net.conf 
# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  interfaces = ["eno1"]
  ##
  ## On linux systems telegraf also collects protocol stats.
  ## Setting ignore_protocol_stats to true will skip reporting of protocol metrics.
  ##
  # ignore_protocol_stats = false

[root@n3 telegraf.d]#
```


what do you think?

**Comment by willfurnell** [comment]
Honestly I'm not sure, that might be something for InfluxData to decide.

**Comment by abrekhov** [comment]
Same issue on Omni-Path and IB network.

**Comment by jose-d** [comment]
> Same issue on Omni-Path and IB network.

yes, it's conceptual problem of this plugin and there is no obvious workaround.

**Comment by jose-d** [comment]
As the issue is still reproducible, here is workaround - instead of using this plugin, failing to recognize Infiniband devices, use this combination of `inputs.file` and processor plugin. The output is almost identical.

```
[[inputs.file]]

  files = ["/sys/class/infiniband/mlx5_0/ports/1/counters/*"]
  data_format = "value"
  file_tag = "metric"

  [inputs.file.tags]
    device = "mlx5_0"
    port = '1'

[[processors.pivot]]

  tag_key = "metric"
  value_key = "value"

```
