### ISSUE TITLE
[docs] Link telegraf CONFIGURATION.md file from Influx site

### ISSUE THREAD

**Issue by s1m0** [influxdata/telegraf#814]
Make it easier to find the detailed configuration guide by linking it from the InfluxData site
[https://docs.influxdata.com/telegraf/v0.10/introduction/configuration/](url)
Preferably incorporate the GitHub-hosted .md files into the InfluxData web site instead of having to flip back and forth between the 2 sites but I appreciate that the telegraf docs are changing rapidly at the moment and this might not be feasible.

**Comment by sparrc** [comment]
please open this issue on https://github.com/influxdata/docs.influxdata.com

cc @rkuchan

**Comment by s1m0** [comment]
OK, will do.
meantime, some of the examples in CONFIGURATION.md use "drop" instead of "fielddrop" which is confusing.

**Comment by sparrc** [comment]
fixed!
