### ISSUE TITLE
Use MQTT Topic names as database names

### ISSUE THREAD

**Issue by Aritra666B** [influxdata/telegraf#8141]
Hi,
Am using telegraf.conf file to connect to 2-3 MQTT topics at a time. How can I use those topic names as my Measurement names in the database when sending data in json format?
I tried using if-else in the conf file but am getting error.

[[inputs.mqtt_consumer]]
servers = [“localhost:1883”]
##servers = [“10.255.201.118:1883”]

MQTT QoS, must be 0, 1, or 2
qos = 0

Topics to subscribe to
topics = [
“Lenze”,
“DIAG”,
“ASSET”,
“EVENT”,
“PROCESS”,
“CONNECT”
]

if [[topics=~“Lenze”]]; then
name_override = “Lenze”
fi
if [[topics=~“DIAG”]]; then
name_override = “DIAG”
fi

**Comment by ssoroka** [comment]
use processors.converter to convert the topic tag to a measurement name. If you need to use more than one processor, specify the order attribute.
something like
```
[[processors.converter]]
  [processors.converter.tags]
    measurement = ["topic"]
```

**Comment by Aritra666B** [comment]
> use processors.converter to convert the topic tag to a measurement name. If you need to use more than one processor, specify the order attribute.
> something like
> 
> ```
> [[processors.converter]]
>   [processors.converter.tags]
>     measurement = ["topic"]
> ```

Hi, I have used your suggestion in the following way but am always getting error in the [inputs.mqtt_consumer] plugin: metric parse error. Ho can I solve this?


[[processors.converter]]
  [processors.converter.tags]
    measurement = ["topic"]

# Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  servers = ["localhost:1883"]
#  servers = ["10.255.201.118:1883"]
  ## MQTT QoS, must be 0, 1, or 2
  qos = 0


  ## Topics to subscribe to
  topics = [
    "LACC",
    "DIAG"
  ]


  # if true, messages that can't be delivered while the subscriber is offline
  # will be delivered when it comes back (such as on service restart).
  # NOTE: if true, client_id MUST be set
  persistent_session = false
  # If empty, a random client ID will be generated.
  client_id = ""


  data_format = "json"
