### ISSUE TITLE
[[inputs.diskio]]  reporting serial numbers as unknown. 

### ISSUE THREAD

**Issue by JaseNZC** [influxdata/telegraf#8147]
While trying to pull serial numbers from the drives with [[inputs.diskio]] all I get is unknown

Config is 
 [[inputs.diskio]]
 skip_serial_number = false

Resulting output though passes an unknown value for all drives. I have 10 and all are reported as unknown

`> diskio,host=box,name=sdc1,serial=unknown`
Is there anyway to get it to report the serial number properly ??

**Comment by sjwang90** [comment]
What operating system is this?

**Comment by JaseNZC** [comment]
Sorry this is running in a docker on an unraid system 6.9.0-beta25

It reports everything else fine but just serial is reported as unknown.

**Comment by JaseNZC** [comment]
Sorted this out , was a setting I had to pass through to the docker that caused the issue. This can be closed now please.

**Comment by rgronberg** [comment]
I am having this same issue in unraid as well. @JaseNZC, what was the extra needed config?
