### ISSUE TITLE
In RDS environment does telegraf support application monitoring per session per user 

### ISSUE THREAD

**Issue by aks-sri** [influxdata/telegraf#8149]
### Relevant telegraf.conf:

```toml

```

### System info:

Telegraf : 1.15.3
Windows server 2016
### Steps to reproduce:

Remote Desktop Session Host (RDSH) is a role in Remote Desktop Services (RDS). RDSH can host Windows session-based applications and desktops that can be shared with users remotely. RDS provides the functionality for upto 150 users to login and access the same application across different sessions. In such scenarios, session-based (per user) monitoring becomes of paramount importance. 

### Expected behavior:

Telegraf should be able to get the session-specific application details per user logged into rds
### Actual behavior:

I couldn't find any way in which telegraf can help us find per user per session info like what application is running by each user in rds

**Comment by aks-sri** [comment]
Any update on this?

**Comment by reimda** [comment]
Telegraf has a few inputs that get process information: processes, procstat, and win_perf_counters. The processes plugin is not supported on windows. Procstat may be worth a try but it recommends win_perf_counters. Win_perf_counters gathers information using windows' PDH API so it should act similarly to perfmon. Could you give win_perf_counters a try and report back?
