### ISSUE TITLE
MODBUS input : some values are not correctly read from Eastron SDM630

### ISSUE THREAD

**Issue by zombiemann1** [influxdata/telegraf#8151]
Using Telegraf 1.15.3 in docker container on Raspberry Pi.

Modbus device to be read : Eastron SDM630 - http://bg-etech.de/download/manual/SDM630Register.pdf

The main part of my telegraf.conf :

input_registers = [
   { name = "Phase 1 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [1,2]},
   { name = "Phase 2 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [3,4]},
   { name = **"Phase 3 line to neutral volts"**, byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [5,6]},
   { name = **"Phase 1 current"**,               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [7,8]},
   { name = **"Phase 2 current"**,               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [9,10]},
   { name = "Phase 3 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [11,12]},
   { name = "Phase 1 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [13,14]},
   { name = "Phase 2 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [15,16]},
   { name = "Phase 3 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [17,18]},
  ]

This config is working except for the 3 parameters in bold.  For these parameters I just receive 0, 1 or 2 as value.

With another tool, I can read these values :

2020/09/18 20:57:46 device SDM1.1 **L1**: 226V **0.8A** 137W 0.77cos | **L2**: 232V **1.0A** 189W 0.83cos | **L3: 229V** 0.7A 142W 0.83cos | 50Hz

What am I doing wrong?

Joris

**Comment by zombiemann1** [comment]
![Screenshot from 2020-09-18 23-34-41](https://user-images.githubusercontent.com/71529255/93646994-a9e08480-fa07-11ea-90b8-5ec50d4a02c3.png)
![Screenshot from 2020-09-18 23-34-35](https://user-images.githubusercontent.com/71529255/93646996-aa791b00-fa07-11ea-9712-35bb5069fb5a.png)
![Screenshot from 2020-09-18 23-34-18](https://user-images.githubusercontent.com/71529255/93646997-ab11b180-fa07-11ea-8ba7-46c527bbdafd.png)

**Comment by srebhan** [comment]
Hey @zombiemann1,

I'm a bit confused about your config... The registers you put are 1-18, but in the documentation the registers you want to read are 30001 - 30023 (first column)!? Do you know which registers the other tool reads or could you do a small tcpdump to check?

**Comment by zombiemann1** [comment]
Hi @srebhan ,

Thank you for your response.  I did already some trial and error last week, but I tried again, you never know...

My updated conf :

`
input_registers = [
   { name = "Phase 1 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30001,30002]},
   { name = "Phase 2 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30003,30004]},
   { name = "Phase 3 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30005,30006]},
   { name = "Phase 1 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30007,30008]},
   { name = "Phase 2 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30009,30010]},
   { name = "Phase 3 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30011,30012]},
   { name = "Phase 1 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30013,30014]},
   { name = "Phase 2 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30015,30016]},
   { name = "Phase 3 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [30017,30018]},
  ]
`

But when I look into grafana, I only see 0 values.  I did a manual query on the influxdb :

`
curl -G -u sdm630:xxx 'http://localhost:8086/query?pretty=true' --data-urlencode "db=sdm630" --data-urlencode "q=SELECT mean(\"Phase 3 current\") FROM "modbus" WHERE time >= now() - 10s GROUP BY time(2s)"
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "modbus",
                    "columns": [
                        "time",
                        "mean"
                    ],
                    "values": [
                        [
                            "2020-09-21T19:18:28Z",
                            null
                        ],
                        [
                            "2020-09-21T19:18:30Z",
                            0
                        ],
                        [
                            "2020-09-21T19:18:32Z",
                            0
                        ],
                        [
                            "2020-09-21T19:18:34Z",
                            0
                        ],
                        [
                            "2020-09-21T19:18:36Z",
                            0
                        ],
                        [
                            "2020-09-21T19:18:38Z",
                            0
                        ]
                    ]
                }
            ]
        }
    ]
}
`

In the console of my docker environment I see :

telegraf_1  | 2020-09-21T19:10:58Z I! Starting Telegraf 1.15.3
telegraf_1  | 2020-09-21T19:10:58Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf_1  | 2020-09-21T19:10:58Z I! Loaded inputs: modbus
telegraf_1  | 2020-09-21T19:10:58Z I! Loaded aggregators: 
telegraf_1  | 2020-09-21T19:10:58Z I! Loaded processors: 
telegraf_1  | 2020-09-21T19:10:58Z I! Loaded outputs: influxdb
telegraf_1  | 2020-09-21T19:10:58Z I! Tags enabled: host=028cedfb3f63
telegraf_1  | 2020-09-21T19:10:58Z I! [agent] Config: Interval:2s, Quiet:false, Hostname:"028cedfb3f63", Flush Interval:2s
telegraf_1  | 2020-09-21T19:10:58Z D! [agent] Initializing plugins
telegraf_1  | 2020-09-21T19:10:58Z D! [agent] Connecting outputs
telegraf_1  | 2020-09-21T19:10:58Z D! [agent] Attempting connection to [outputs.influxdb]
telegraf_1  | 2020-09-21T19:10:58Z D! [agent] Successfully connected to outputs.influxdb
telegraf_1  | 2020-09-21T19:10:58Z D! [agent] Starting service inputs

influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:24 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3884ef40-fc3f-11ea-80e0-0242ac140003 5919
telegraf_1  | 2020-09-21T19:18:24Z D! [outputs.influxdb] Wrote batch of 1 metrics in 7.483785ms
telegraf_1  | 2020-09-21T19:18:24Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
telegraf_1  | 2020-09-21T19:18:26Z D! [outputs.influxdb] Wrote batch of 1 metrics in 10.470705ms
telegraf_1  | 2020-09-21T19:18:26Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:26 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 39b63788-fc3f-11ea-80e1-0242ac140003 8300
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:28 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3ae78c9b-fc3f-11ea-80e2-0242ac140003 10259
telegraf_1  | 2020-09-21T19:18:28Z D! [outputs.influxdb] Wrote batch of 1 metrics in 13.339031ms
telegraf_1  | 2020-09-21T19:18:28Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:30 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3c188e4a-fc3f-11ea-80e3-0242ac140003 12747
telegraf_1  | 2020-09-21T19:18:30Z D! [outputs.influxdb] Wrote batch of 1 metrics in 14.425487ms
telegraf_1  | 2020-09-21T19:18:30Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:32 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3d49e0bd-fc3f-11ea-80e4-0242ac140003 7751
telegraf_1  | 2020-09-21T19:18:32Z D! [outputs.influxdb] Wrote batch of 1 metrics in 10.298934ms
telegraf_1  | 2020-09-21T19:18:32Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:34 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3e7b3859-fc3f-11ea-80e5-0242ac140003 7664
telegraf_1  | 2020-09-21T19:18:34Z D! [outputs.influxdb] Wrote batch of 1 metrics in 11.144453ms
telegraf_1  | 2020-09-21T19:18:34Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:36 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 3fac4760-fc3f-11ea-80e6-0242ac140003 8071
telegraf_1  | 2020-09-21T19:18:36Z D! [outputs.influxdb] Wrote batch of 1 metrics in 10.672111ms
telegraf_1  | 2020-09-21T19:18:36Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
influxdb    | [httpd] 172.20.0.4 - sdm630 [21/Sep/2020:19:18:38 +0000] "POST /write?db=sdm630 HTTP/1.1" 204 0 "-" "Telegraf/1.15.3 Go/1.14.5" 40dd7ca7-fc3f-11ea-80e7-0242ac140003 6983
telegraf_1  | 2020-09-21T19:18:38Z D! [outputs.influxdb] Wrote batch of 1 metrics in 9.583155ms
telegraf_1  | 2020-09-21T19:18:38Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics

The other tool that I used is mbmd.  The register addresses this tool reads are defined in : https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/sdm.go

So I thought that the telegraf "Input register" configuration looks into an address space of "30001 – 39999" and that we have to define the offset in the config file.

Should I use hex format like "0x0000" for the telegraf configuration?

Kind regards,

Joris

**Comment by srebhan** [comment]
Could you please post the command-line you use for the _mbmd_ tool. Additionally, please also attach your telegraf.config file.

**Comment by zombiemann1** [comment]
Hi @srebhan 

Please have a look at my telegraf config file with the settings I've used the last time :
[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/5264145/telegraf.conf.txt)

This is the mbmd config file I use in my docker environment :
[mbmd.yaml.txt](https://github.com/influxdata/telegraf/files/5264146/mbmd.yaml.txt)

But also the normal mbmd command version is working without any issues : sudo ./mbmd run -a /dev/ttyUSB0 -d sdm:1 -v

Do you any suggestion what I've to change in my telegraf config to make it work well?

Kind regards,

Joris

**Comment by srebhan** [comment]
Hey @zombiemann1,

while having a quick look at the mbmd code I realized that indeed they read the registers 1-18 instead of 30001-30018. Furthermore I found that they interpret the values as big-endian, most significant word first (i.e. ABCD) instead of the word order you specified (i.e. CDAB).. Their interpretation is also according to the documentation...

Please try the attached config [telegraf.conf.txt](https://github.com/influxdata/telegraf/files/5266597/telegraf.conf.txt).
It will output the read values on stdout, to rule out any visualization issue with influxdb/grafana whatsoever. You can run it once using `telegraf --config telegraf.conf.txt --test`. If the output seems wrong, please try to comment "_Variant 1_" and uncomment "_Variant 2_" in the config (reading the 300xx registers).

Hope this helps!?

    Sven

**Comment by zombiemann1** [comment]
Hi @srebhan ,

I've executed both variants like you said, but they look very bad.  I've also added a third variant :

`
## Variant 3
  input_registers = [
     { name = "Phase 1 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [1,2]},
     { name = "Phase 2 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [3,4]},
     { name = "Phase 3 line to neutral volts", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [5,6]},
     { name = "Phase 1 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [7,8]},
     { name = "Phase 2 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [9,10]},
     { name = "Phase 3 current",               byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [11,12]},
     { name = "Phase 1 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [13,14]},
     { name = "Phase 2 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [15,16]},
     { name = "Phase 3 power",                 byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [17,18]},
  ]
`

These are all results :

variant 1 :

root@1dc966867ba9:/home# telegraf --config telegraf.conf --test
2020-09-23T19:13:42Z I! Starting Telegraf 1.15.3
> modbus,host=1dc966867ba9,name=SDM630,type=input_register 
Phase\ 1\ current=-0.00000000000000000000000000000000000011552801160069549,
Phase\ 1\ line\ to\ neutral\ volts=-8.453956604003906,
Phase\ 1\ power=-0.000012413484910211992,
Phase\ 2\ current=-0.0000000000000016601089789278862,
Phase\ 2\ line\ to\ neutral\ volts=-62347698176,
Phase\ 2\ power=3417481423411319000000,
Phase\ 3\ current=-3423964731125488000000000,
Phase\ 3\ line\ to\ neutral\ volts=0.0000000000000024875697476282183,
Phase\ 3\ power=69035577739051010 1600888423000000000

variant 2 :

root@1dc966867ba9:/home# telegraf --config telegraf.conf --test
2020-09-23T19:16:25Z I! Starting Telegraf 1.15.3
> modbus,host=1dc966867ba9,name=SDM630,type=input_register 
Phase\ 1\ current=0,Phase\ 1\ line\ to\ neutral\ volts=0,
Phase\ 1\ power=0,Phase\ 2\ current=0,
Phase\ 2\ line\ to\ neutral\ volts=0,
Phase\ 2\ power=0,Phase\ 3\ current=0,
Phase\ 3\ line\ to\ neutral\ volts=0,
Phase\ 3\ power=0 1600888586000000000

variant 3 (2x) :

root@1dc966867ba9:/home# telegraf --config telegraf.conf --test
2020-09-23T19:19:35Z I! Starting Telegraf 1.15.3
> modbus,host=1dc966867ba9,name=SDM630,type=input_register 
Phase\ 1\ current=1.2755111455917358,
Phase\ 1\ line\ to\ neutral\ volts=230.45167541503906,
Phase\ 1\ power=260.30291748046875,
Phase\ 2\ current=0.7585499882698059,
Phase\ 2\ line\ to\ neutral\ volts=229.19464111328125,
Phase\ 2\ power=159.4833984375,
**Phase\ 3\ current=180.0697021484375,
Phase\ 3\ line\ to\ neutral\ volts=0.9836075901985168,**
Phase\ 3\ power=219.98757934570312 1600888776000000000

root@1dc966867ba9:/home# telegraf --config telegraf.conf --test
2020-09-23T19:34:20Z I! Starting Telegraf 1.15.3
> modbus,host=1dc966867ba9,name=SDM630,type=input_register
Phase\ 1\ current=1.439251184463501,
Phase\ 1\ line\ to\ neutral\ volts=231.09930419921875,
Phase\ 1\ power=291.8713073730469,
Phase\ 2\ current=0.7510622143745422,
Phase\ 2\ line\ to\ neutral\ volts=231.279052734375,
Phase\ 2\ power=159.88186645507812,
**Phase\ 3\ current=179.13589477539062,
Phase\ 3\ line\ to\ neutral\ volts=0.9788687825202942,**
Phase\ 3\ power=221.37704467773438 1600889661000000000

The first and second variants look very bad...
The third one looks better, but "Phase\ 3\ current" and "Phase\ 3\ line\ to\ neutral\ volts" are not normal values.

Do you have any idea where these strange values are coming from?

Greetz, Joris

**Comment by srebhan** [comment]
To be honest I don't know where the strange values are coming from... In [mbmd SDM code](https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/sdm.go) in line 76ff the value transformation is set to _RTUIee754ToFloat64_ which is implemented in [mbmd](https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/transform.go) as:
```
func RTUIeee754ToFloat64(b []byte) float64 {
	bits := binary.BigEndian.Uint32(b)
	f := math.Float32frombits(bits)
	return float64(f)
}
```
This is code-equivalent to telegraf config ` byte_order = "ABCD", data_type = "FLOAT32-IEEE"`. So either the registers are wrong or the transformation or something else is done in _mbmd_.
As the registers seem to be 1-18, according to _mbmd_ and the data from the variant tests. So this should be a safe assumption. This leaves us with the transformation... According to [documentation](https://github.com/volkszaehler/mbmd/blob/master/docs/mbmd.md) it is possible to dump the raw register readings from _mbmd_ using the `--raw` option. Could you please do this and additionally change the `data_type="FLOAT32-IEEE"` to `data_type="UINT32"` in telegraf. Then run telegraf printing to _stdout_ with `--test`. Afterwards run _mbmd_ with the additional `--raw` option. We can then compare the bits and see if we get similar values.
Can you please post the two value sets of the above command!?

**Just to be sure**: You are not running multiple programs to query the SDM630 meters **simultaniously** I guess!?!?!? This might be a source of trouble over a serial line...

**Comment by srebhan** [comment]
Ok **now** I see what is wrong... A typical off-by-one... :-) The registers in [mbmd SDM implementation](https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/sdm.go) start at **ZERO** not **ONE** as in your config. Try the [attached config](https://github.com/influxdata/telegraf/files/5277281/telegraf.conf.txt) and hope for the best... ;-)

**Comment by zombiemann1** [comment]
Hi @srebhan ,

The result of my new trial :

root@732b77795356:/home# telegraf --config telegraf.conf --test
2020-09-24T17:18:53Z I! Starting Telegraf 1.15.3
> modbus,host=732b77795356,name=SDM630,type=input_register 
Phase\ 1\ current=0.0000000000000000000000000000000000020482644679967767,
Phase\ 1\ line\ to\ neutral\ volts=-0.0076374271884560585,
Phase\ 1\ power=0.00000000021396948102214708,
Phase\ 2\ current=0.0000000000000000000001292458726170305,
Phase\ 2\ line\ to\ neutral\ volts=0.012589311227202415,
Phase\ 2\ power=-20646490807912630000,
Phase\ 3\ current=-338424.46875,
Phase\ 3\ line\ to\ neutral\ volts=-0.0000000000000000006751301852086967,
Phase\ 3\ power=-0.000000000000000016399801938484534 1600967933000000000

So it looks very weird... Do you have more suggestions which I can try?

Greetz, Joris

**Comment by srebhan** [comment]
Now try `byte_order="ABCD"`...

**Comment by zombiemann1** [comment]
Hi @srebhan ,

Yeah, it looks better now...

root@30cb980bb4ce:/home# telegraf --config telegraf.conf --test
2020-09-25T07:09:46Z I! Starting Telegraf 1.15.3
> modbus,host=30cb980bb4ce,name=SDM630,type=input_register 
Phase\ 1\ current=0.5455840826034546,
Phase\ 1\ line\ to\ neutral\ volts=230.16403198242188,
Phase\ 1\ power=70.41720581054688,
Phase\ 2\ current=0.9848227500915527,
Phase\ 2\ line\ to\ neutral\ volts=232.7792510986328,
Phase\ 2\ power=195.43792724609375,
Phase\ 3\ current=0.21057727932929993,
Phase\ 3\ line\ to\ neutral\ volts=232.51409912109375,
Phase\ 3\ power=43.79153823852539 1601017786000000000

I thought I have tested all possible "byte_order" and "address" combinations, but this one I didn't test...

Thank you so much to have a look at my issue!

Now I can configure all the other parameters... But one last question, the document tells me :

"The SDM630Modbus can transfer a maximum of 40 values in a single transaction; therefore
the maximum number of registers requestable is 80. Exceeding this limit prompts the
SDM630Modbus to generate an exception response."

If I need more than 40 values (I'm not sure, but I still have to make a list of them which I want to use), is that possible in telegraf?  Of should I stay with that maximum?

Kind regards,

Joris

**Comment by srebhan** [comment]
Hey Joris,

good that you have that working! :-) Let me first explain why I think your initial config gave you some sensible values...
When you use the off-by-one addresses you always read the low-word of the metric you wanted and the high-word of the next metric. So for `V_phase1` you read `V_phase1_low` and `V_phase2_high`. Using the `CDAB` byte_order you get `[V_phase2_high, V_phase1_low]` which will give you some wrong value but a value in the usual voltage range... However for `V_phase3` you will read `V_phase3_low` and `I_phase1_high` (as it is the metric after the voltages) which will completely mess up the values.
Nice combination of errors isn't it? ;-)

For your question regarding the query limit:
The 40 values limitation is a limitation of the sensors, not one of telegraf! I don't have a SDM630, so I cannot say what will happen if you read more, however other sensors simply drop you an error or just don't answer.
For querying more than 40 values with telegraf (do you really need to?) you have two possibilities:

1. If there is a gap in the registers (like you have 0-17 and 20-37) telegraf will issue two sequential requests (as it groups registers that are consecutive). So if you have two batches of 40 values each you will not exceed the limit... However, this will only work if you have gaps between the register-addresses you read.
2. In case 1 doesn't work for you, you could instantiate the modbus plugin twice and tune the timing of the requests such that they are sequential. However, as you are using a serial line, this will only work if the underlying modbus library is hanging-up the connection after each request, i.e. it does not keep the serial port open.

If both does not work, then please open a new issue and state that you need a config-option to limit the maximum number of registers per query. If you mention me in that issue, I will try to figure out if that can be done in the plugin...

**Comment by srebhan** [comment]
@zombiemann1: If this issue is solved, please close it!

For completeness and documentation, here is the finally working config: [telegraf.conf.txt](https://github.com/influxdata/telegraf/files/5281276/telegraf.conf.txt)
