### ISSUE TITLE
Telegraf

### ISSUE THREAD

**Issue by Lathem2** [influxdata/telegraf#8152]
Hi Installed telegraf in one instance. And tried to write that metrics to influxDB that presents on defferent instance, its throwing error like database creation failed. can you please tell me wat might be the issue? I even tried with with the manual  database creation.
 W! [outputs.influxdb] when writing to [http://Influxdb:8086]: database "demo" creation failed: Post http://influxDB:8086/query: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

& am trying to collect windows metrics

Please help me on this.

**Comment by sjwang90** [comment]
Hi @Lathem2, we reserve Telegraf issues for bug or reproducible problems. Can you please post in our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) with your full config file and output error message? We can help you better there.
