### ISSUE TITLE
Asterisk VoIP Software Integration

### ISSUE THREAD

**Issue by mafairnet** [influxdata/telegraf#8156]
## Asterisk VoIP Software Integration

Opening a feature request kicks off a discussion.

**Comment by mafairnet** [comment]
Added temporary base code on https://github.com/mafairnet/asterisk-telegraf-integration
I have to write the tests and the other requirements to integrate in the main branch.

**Comment by sjwang90** [comment]
Hey @mafairnet.  Thanks for the contribution! This actually looks like something that would be great as an external plugin.  Check out the [docs here](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md), and once submitted people can start using it quickly.
