### ISSUE TITLE
Add flag to use "short" name or FQDN for ESX hosts

### ISSUE THREAD

**Issue by sumptersmartt** [influxdata/telegraf#8166]
## Feature Request
Allow user to choose FQDN or short name as value for esxhostname tag

### Proposal:
Provide a flag in the inputs.vsphere plugin to configure if a FQDN or short name is used in the esxhostname tag.
### Current behavior:
Telegraf uses whatever is returned by vCenter
### Desired behavior:
Make this a configurable option-- if the host is configured with a FQDN in vCenter, leave it that way by default, but give user the option to truncate everything including and after the first '.' that is returned by vSphere.
### Use case: 
In vCenter we use FQDNs when adding hosts. This is desirable in vCenter. However, some of these FQDNs are very long. **esxhostname01.infrastructure.example-longdomain.com** instead of just **esxhostname01** takes up a lot of real estate on a dashboard but doesn't add much value. By making 'use short name' a configurable option, disabled by default (or the reverse -- 'use FQDN' enabled by default), the current behavior would not be changed for users who don't want it to change but adds more flexibility for those who want more concise tags.

**Comment by M0rdecay** [comment]
Try truncating the tag data with the [regex processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex).

**Comment by sumptersmartt** [comment]
Thanks, that does exactly what I need! I was unaware of the processor plugins.

**Comment by reimda** [comment]
It sounds like the regex processor will work for you so I'm closing the issue.

**Comment by theotherguy2175** [comment]
Are you able to give an example if you were able to get it working

**Comment by sumptersmartt** [comment]
> Are you able to give an example if you were able to get it working

Sure thing. There may be a more efficient way to do this, but this works fine for me!

```
[[processors.rename]]
  order = 1
  [[processors.rename.replace]]
    tag = "esxhostname"
    dest = "esxhostfullname"


[[processors.regex]]
  order = 2
  [[processors.regex.tags]]
    ## Tag to change
    key = "esxhostfullname"
    ## Regular expression to match on a tag value
   pattern = "\\.\\w*" # n.b. backslash must be escaped with another backslash
    ## Matches of the pattern will be replaced with this string.  Use ${1}
    ## notation to use the text of the first submatch.
    replacement = "${1}"
    result_key = "esxhostname"

```
