### ISSUE TITLE
Telegraf can't connect to an existing queue with error x-message-ttl

### ISSUE THREAD

**Issue by mesutmutlu** [influxdata/telegraf#8180]
Hello,

While trying to consume an existing queue from Rabbit I'm getting the error below. But if i change the queue name a new channel on the declared exchange is successfully created. But what i want is to consume an already existed queue.

[telegraf] Error running agent: starting input inputs.amqp_consumer: Error declaring queue: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'Edge_AccessLogs' in vhost '/influxdb': received none but current is the value '600000' of type 'long'"

In telegraf.conf i have

[[inputs.amqp_consumer]]
  url = "amqp://a.b.c.d:5672//influxdb"
  username = "usr"
  password = "pwd"
  queue = "Edge_AccessLogs"
  exchange = "edge"
  data_format = "json"

Has anyone ever came on this case?

Thanks

**Comment by rajiv-k** [comment]
@mesutmutlu Looks like you might have created the queue with the `x-message-ttl` argument. Try connecting to a queue without the `x-message-ttl` argument. I am not sure if arguments are already supported in the `amqp_consumer` plugin.

@danielnelson Worth supporting the "arguments" in the amqp_consumer plugin while connecting to a queue?
