### ISSUE TITLE
Input Cisco MDT gRPC healthcheck

### ISSUE THREAD

**Issue by andreavivaldi** [influxdata/telegraf#8194]
Hi,
I was wondering if is there any method to check if the gRPC server, coming from Cisco MDT input plugin, is working properly... something like an healthcheck probe.
I'm not a gRPC expert, but I found that, generally speaking, a gRPC server can beh monitored using the gPRC Health Checking Protocol (https://github.com/grpc/grpc/blob/master/doc/health-checking.md). This is not implemented  in the plugin. What can I use alternatively?

**Comment by reimda** [comment]
Telegraf doesn't have a generic gRPC health checker.  Telegraf's http_response input plugin uses golang's HTTP client which supports HTTP/2.  gRPC is built on HTTP/2.  You might be able to use the http_response with a canned or fake or empty request body to at least know if the connection failed or if there was a timeout or dns error.  It wouldn't be a full gRPC health check, but might be better than nothing.
