### ISSUE TITLE
Some troubles with plaintext transfer

### ISSUE THREAD

**Issue by VorobevPavel-dev** [influxdata/telegraf#8195]
Good day to you!

Some time ago i had to work with socket_listener to get metrics from another computer gathered with telegraf. It works preety well BUT there are some troubles: if i collect data in grpahite format on server#1, send it to telegraf on server#2 and from there send in Kafka i will not get correct result.
For example:
I collect metrics at server#1:
cpu.usage_idle;cpu=cpu0;dc=test;host=test (no problem here)
Successfully send it to telegraf on server#2 with
data_format="graphite" in inputs and
graphite_tag_support="true" in outputs
After all i get string like
cpu.usage_idle_cpu=cpu0_dc=test_host=test;<tags specified in telegraf including host, interval>

Steps to reproduce:

Get file metrics_in.txt in graphite-tagged format and some metrics in it like
internal_agent.gather_errors;go_version=1.14.5;host=test;interval=10s;version=1.15.3 0 1601399210
Add to your conf:
[[inputs.file]]
data_format="graphite"
files = ["./metrics_in.txt"]
[[outputs.file]]
data_format="graphite"
graphite_tag_support=true
files = ["./metrics_out.txt"]
Expected result:
Same stirngs and values but with global tags from telegraf on server#2

Actual result:
internal_agent.gather_errors_go_version=1.14.5_host=test_interval=10s_version=1.15.3 0 1601399210

It works well if i send metrics from host in for example json, get it on second server and transform it in graphite. Maybe there are some ways to get and send plaintext?

**Comment by VorobevPavel-dev** [comment]
Good day to you!

Some time ago i had to work with socket_listener to get metrics from another computer gathered with telegraf. It works preety well  BUT there are some troubles: if i collect data in grpahite format on server#1, send it to telegraf on server#2 and from there send in Kafka i will not get correct result.
For example:
  I collect metrics at server#1:
     cpu.usage_idle;cpu=cpu0;dc=test;host=test <value> <timestamp> (no problem here)
  Successfully send it to telegraf on server#2 with 
        data_format="graphite" in inputs and 
        graphite_tag_support="true" in outputs
  After all i get string like  
    cpu.usage_idle_cpu=cpu0_dc=test_host=test;<tags specified in telegraf including host, interval> <value> <timestamp>

Steps to reproduce:
  - Get file metrics_in.txt in graphite-tagged format and some metrics in it like
        internal_agent.gather_errors;go_version=1.14.5;host=test;interval=10s;version=1.15.3 0 1601399210
  - Add to your conf:
  [[inputs.file]]
    data_format="graphite"
    files = ["./metrics_in.txt"]
  [[outputs.file]]
    data_format="graphite"
    graphite_tag_support=true
    files = ["./metrics_out.txt"]

Expected result:
  Same stirngs and values but with global tags from telegraf on server#2

Actual result:
 internal_agent.gather_errors_go_version=1.14.5_host=test_interval=10s_version=1.15.3 0 1601399210

It works well if i send metrics from host in for example json, get it on second server and transform it in graphite. Maybe there are some ways to get and send plaintext?

**Comment by sjwang90** [comment]
Hi @VorobevPavel-dev, sorry for the delay but we reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
