### ISSUE TITLE
Problem to visualize the correct information in influxdb

### ISSUE THREAD

**Issue by gringnel** [influxdata/telegraf#8197]
`<!--`
I am facing for a problem to visualize the same information in my file than in database.

about log:
[linuxserver]$ cat 'file' | grep -ia '|value|' | wc -l
**8281**

Database:
select COUNT(event_type) from MEASUREMENT where error_code='value' AND time >= now() - 16h
time                           count
2020-09-29T02:59:59.258928349Z **3073**

Note: Same date time

**Config:**
[[inputs.logparser]]
files = ["/opt/log_me/**.txt"]
from_beginning = false
[inputs.logparser.grok]
patterns = ['Mygrok']
measurement = "measurementname"
custom_patterns = '''
        MY_TIME %{HOUR}:%{MINUTE}
        MYTIMESTAMP (?:\d{2}.\d{2}.\d{4} \d{2}:\d{2}:\d{2})

[agent]
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s

Where i can check if information are sent correct?

Thanks for help!
-->

**Comment by gringnel** [comment]
Any idea?!

**Comment by sjwang90** [comment]
What is your output plugin configuration? you can run `-test` after your `telegraf -config` command to see the data that will output based off your configuration file.

We reserve GitHub issues for reproducible bugs. Feel free to drop into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this answered quicker.
