### ISSUE TITLE
apache input plugin not handling non-standard ports 

### ISSUE THREAD

**Issue by dakotacody** [influxdata/telegraf#8206]
### Relevant telegraf.conf:
```
# Read Apache status information (mod_status)
[[inputs.apache]]
  ## An array of URLs to gather from, must be directed at the machine
  ## readable version of the mod_status page including the auto query string.
  ## Default is "http://localhost/server-status?auto".
  urls = ["http://localhost:61666/server-status?auto"]

  ## Credentials for basic HTTP authentication.
  # username = "myuser"
  # password = "mypassword"

  ## Maximum time to receive response.
  # response_timeout = "5s"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false
  response_timeout = "5s"
  tagexclude = ["port","server"]
  [inputs.apache.tags]
    metrictype = "applicationlevel"


```

### System info:
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
 Telegraf 1.15.3

### Steps to reproduce:
1. We have apache server-status  configured to listen on a non-standard port.  As you can see we have the apache input plugin configured to hit this port.

 
2.  This is odd because it appears the plugin _is_ hitting the correct URL and port and publishing the metrics.  However, we are still getting an error for the redirect in the log.  I've looked at the code for this plugin and cannot see where it would do this.  

Additionally , I see it is setting the tags incorrectly in this portion of the code

```func getTags(addr *url.URL) map[string]string {
	h := addr.Host
	host, port, err := net.SplitHostPort(h)
	if err != nil {
		host = addr.Host
		if addr.Scheme == "http" {
			port = "80"
		} else if addr.Scheme == "https" {
			port = "443"
		} else {
			port = ""
		}
	}
	return map[string]string{"server": host, "port": port}
}
```

### Expected behavior:

It should only hit the configured URL on the correct port, also the port tag should be set to what the URL specifies not based off of whether it is http or https. 

### Actual behavior:
The correct URL is hit but apparently so is the default URL.  The port tag is also set incorrectly.

### Additional info:
I get this error in the log despite the URL list not having that URL set. 
```2020-09-30T20:39:08Z E! [inputs.apache] Error in plugin: error on request to http://localhost/server-status?auto : Get "https://redacted.com/server-status?auto": context deadline exceeded (Client.Timeout exceeded while awaiting headers)```

**Comment by dakotacody** [comment]
I was just reviewing.. I see that the port is only overwritten if there is an error returned from SplitHostPort, so you can probably ignore that part.  I still don't see how this plugin would ever make a call to the default server-status URL though and that is the behaviour we're seeing.

**Comment by dakotacody** [comment]
Another update.. running with the posted config.

```root@redacted:/etc/telegraf# telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --input-filter apache --test --debug                     
2020-09-30T21:25:36Z I! Starting Telegraf 1.15.3
> apache,dc=us-east-1,group=unclassified,host=redacted,metrictype=applicationlevel,rack=6,row=H BusyWorkers=830,BytesPerReq=5418.02,BytesPerSec=2676070,CPUChildrenSystem=0,CPUChildrenUser=0,CPULoad=169.863,CPUSystem=1211.33,CPUUser=12022.7,CacheCurrentEntries=2208,CacheDiscardCount=77524,CacheExpireCount=0,CacheIndexesPerSubcaches=88,CacheRemoveHitCount=0,CacheRemoveMissCount=0,CacheReplaceCount=0,CacheRetrieveHitCount=11,CacheRetrieveMissCount=13698,CacheSharedMemory=512000,CacheStoreCount=79732,CacheSubcaches=32,CacheTimeLeftOldestAvg=198,CacheTimeLeftOldestMax=223,CacheTimeLeftOldestMin=167,IdleWorkers=227,Load1=8.24,Load15=7.61,Load5=7.46,ParentServerConfigGeneration=2,ParentServerMPMGeneration=1,ReqPerSec=493.92,ServerUptimeSeconds=7791,TotalAccesses=3848132,TotalkBytes=20360599,Uptime=7791,scboard_closing=9,scboard_dnslookup=0,scboard_finishing=0,scboard_idle_cleanup=0,scboard_keepalive=781,scboard_logging=1,scboard_open=6443,scboard_reading=18,scboard_sending=21,scboard_starting=0,scboard_waiting=227 1601501137000000000```

 and checking the exit status of that command 

```
root@redacted:/etc/telegraf# echo $?
1
```
however .. if I change the config to not exclude the port tag
```  
 tagexclude = ["server"]
```

Then the result is a very fast
```
root@redacted:/etc/telegraf# echo $? 
0
```

**Comment by powersj** [comment]
Hi,

I set up Apache in a container with the following config:

```xml
        Listen 8080
        ExtendedStatus On
        <VirtualHost *:8080>
        <Location /server-status>
                SetHandler server-status
                Allow from all
                Order allow,deny
        </Location>
        </VirtualHost>
```

Using the following telegraf config:

```toml
[[inputs.apache]]
  urls = ["http://192.168.100.90:8080/server-status?auto"]

[[outputs.file]]
```

I see the following:

```s
./telegraf --config ./config.toml --input-filter apache --test --debug
2022-11-03T15:28:33Z I! Starting Telegraf 1.25.0-497297a9
2022-11-03T15:28:33Z I! Available plugins: 226 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs
2022-11-03T15:28:33Z I! Loaded inputs: apache
2022-11-03T15:28:33Z I! Loaded aggregators: 
2022-11-03T15:28:33Z I! Loaded processors: 
2022-11-03T15:28:33Z W! Outputs are not used in testing mode!
2022-11-03T15:28:33Z I! Tags enabled: host=ryzen
2022-11-03T15:28:33Z D! [agent] Initializing plugins
2022-11-03T15:28:33Z D! [agent] Starting service inputs
2022-11-03T15:28:33Z D! [agent] Stopping service inputs
2022-11-03T15:28:33Z D! [agent] Input channel closed
2022-11-03T15:28:33Z D! [agent] Stopped Successfully
> apache,host=ryzen,port=8080,server=192.168.100.90 BusyWorkers=1,BytesPerReq=1024,BytesPerSec=62.439,CPUChildrenSystem=0,CPUChildrenUser=0,CPUSystem=0,CPUUser=0,ConnsAsyncClosing=0,ConnsAsyncKeepAlive=0,ConnsAsyncWriting=0,ConnsTotal=0,DurationPerReq=0,IdleWorkers=49,Load1=0.2,Load15=0.4,Load5=0.33,ParentServerConfigGeneration=1,ParentServerMPMGeneration=0,Processes=2,ReqPerSec=0.0609756,ServerUptimeSeconds=82,Stopping=0,TotalAccesses=5,TotalDuration=0,TotalkBytes=5,Uptime=82,scboard_closing=0,scboard_dnslookup=0,scboard_finishing=0,scboard_idle_cleanup=0,scboard_keepalive=0,scboard_logging=0,scboard_open=100,scboard_reading=0,scboard_sending=1,scboard_starting=0,scboard_waiting=49 1667489314000000000
```

> It should only hit the configured URL on the correct port, also the port tag should be set to what the URL specifies not based off of whether it is http or https.

As you mentioned in your 2nd comment, the port is correctly set. The hard-coded HTTP and HTTPS ports are only in the event of an error parsing that URL. If that URL fails to parse, I don't think you would be getting this far in the first place.

> we are still getting an error for the redirect in the log

Can you share your apache config? you mentioned a redirect, so I'm curious if there is something I am missing beyond the special port.

**Comment by dakotacody** [comment]
I'm not sure if this issue is even occurring anymore.. we include a ports.conf file.   

So the apache conf looks like this: 
`
# Security
ServerTokens prod
ServerSignature Off
TraceEnable On

ServerName "<redacted>"
ServerRoot "/etc/apache2"
PidFile ${APACHE_PID_FILE}
Timeout 60
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 15
LimitRequestFieldSize 8190
LimitRequestFields 100


User www-data
Group www-data

AccessFileName .htaccess
<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>

<Directory />
  Options FollowSymLinks
  AllowOverride None
</Directory>


HostnameLookups Off
ErrorLog "/var/log/apache2/error.log"
LogLevel warn
EnableSendfile On

#Listen 80


Include "/etc/apache2/mods-enabled/*.load"
Include "/etc/apache2/mods-enabled/*.conf"
Include "/etc/apache2/ports.conf"

LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%a %l %u %t \"%r\" %>s %b" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\"" forwarded

IncludeOptional "/etc/apache2/conf.d/*.conf"
IncludeOptional "/etc/apache2/sites-enabled/*"
`

And the ports.conf looks like this

`Listen 443
Listen 61666
Listen 80
`

I didn't see any redirect errors.. and it seems we are running Telegraf 1.21.4  whereas you tested on Telegraf 1.25.0-497297a9

This is perhaps fixed in that new version, but I provided the above in case you were curious.  I'd say close this issue and if we experience it again in the future I can always submit another bug.

**Comment by powersj** [comment]
> This is perhaps fixed in that new version, but I provided the above in case you were curious.

Thanks - that all looks pretty standard

> I'd say close this issue and if we experience it again in the future I can always submit another bug.

sounds, please do!
