### ISSUE TITLE
logic in metric selection snmp-trap plugin

### ISSUE THREAD

**Issue by RemcoAA** [influxdata/telegraf#8213]
## Feature Request

Plugin SNMP-TRAP is not predictable in which metric is used when exposing the received trap. Which is having impact on number of metrics in the database. It looks like the last label with an integer value is being used.

### Current behavior:
this trap:
`snmp_trap,agent_address=10.1.2.3,host=43272d544c2d,mib=CISCO-BGP4-MIB,name=cbgpFsmStateChange,oid=.1.3.6.1.4.1.9.9.187.0.1,source=10.1.2.3,version=1 bgpPeerState.10.215.200.2=1i,cbgpPeerLastErrorTxt.10.215.200.2="hold time expired",cbgpPeerPrevState.10.215.200.2=3i,sysUpTimeInstance=2851507592i,bgpPeerLastError.10.215.200.2="" 1601636174602963062`

is presented in /metric as: snmp_trap_sysUpTimeInstance

While this trap:
`snmp_trap,agent_address=10.1.2.3,host=43272d544c2d,mib=CISCO-BGP4-MIB,name=cbgpFsmStateChange,oid=.1.3.6.1.4.1.9.9.187.0.1,source=10.1.2.3,version=1 sysUpTimeInstance=2851504592i,bgpPeerLastError.10.215.156.3="",bgpPeerState.10.215.156.3=3i,cbgpPeerLastErrorTxt.10.215.156.3="hold time expired",cbgpPeerPrevState.10.215.156.3=1i 1601636143342215217`

is presented in /metric as: snmp_trap_cbgpPeerPrevState_10_215_156_3

### Desired behavior:

Have the plugin present the received trap always with the same metric.

### Use case: 

We now get a lot of different metrics in our database for example for the BGP neighbor state changed alerts.

**Comment by neeles83** [comment]
Making the behavior configurable would be nice, thus static predefine vs static configurable vs select label xyz.

**Comment by RemcoAA** [comment]
We solved our problems for now by using the starlak processor plug-in to modify the fields and tag.

```
def apply(metric):
    # loop all fields
    for k, v in metric.fields.items():
        if "." in k:
            # copy fields to tags if field key has dot
            tmp = k.split(".", 1)
            metric.tags[tmp[0]] = str(v)
            # for bgp peer addr
            if tmp[0] == "cbgpPeerLastErrorTxt":
                metric.tags["bgpPeerRemoteAddr"] = tmp[1]
        elif k == "sysUpTimeInstance":
            # create a new field based on tag value
            metric.fields[metric.tags.get("squad")] = metric.fields["sysUpTimeInstance"]
        else:
            metric.tags[k] = v
        # remove all existing fields
        metric.fields.pop(k)
    return metric
```

**Comment by Hipska** [comment]
I guess this is when using prometheus output?
It seems to me that that second trap would also be available as `snmp_trap_sysUpTimeInstance`, since it will create a prometheus metric for every numeric field in the telegraf metric.

**Comment by MyaLongmire** [comment]
This has not gotten a response in over a year so I am closing this ticket. If you are still having issues please open another ticket with all the relevant information. Thank you!
