### ISSUE TITLE
Telegraf cloudwatch inputs plugin failed to assume role and connect to cloudwatch when role_arn is used

### ISSUE THREAD

**Issue by tmiroslav** [influxdata/telegraf#8221]
### Relevant telegraf.conf:
```
[[inputs.cloudwatch]]
region = "us-east-1"
role_arn = "arn:aws:iam::xxxxxxxxx:role/FrameTick"
period = '1m'
delay = '5m'
interval = '5m'
namespace = 'AWS/RDS'
```

### System info:
Telegraf 1.13.2, CentOS Linux release 7.8.2003 (Core)

### Steps to reproduce:
Configure inputs.cloudwatch plugin in Telegraf in AWS EC2. Create IAM role and assign it to Telegraf EC2. Create IMA policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:GetMetricData",
                "cloudwatch:ListMetrics"
            ],
            "Resource": "*"
        }
    ]
}
```
and attach to previously created IAM role. 

### Expected behavior:

Start receiving cloudwatch metrics in influxdb. 

### Actual behavior:

Facing telegraf error:
`Error in plugin: AccessDenied: User: arn:aws:sts::xxxxxx:assumed-role/FrameTick/instanceid is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxx:role/FrameTick
`
### Additional info:

When I attach Admin policy to telegraf EC2:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```
Everything works fine. 
Why Telegraf is failing to assume role if it does not have Admin policy attached? What privilege it needs so  it can assume role properly?

**Comment by apoorv-garg** [comment]
You need `sts:AssumeRole` https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_permissions-to-switch.html#roles-usingrole-createpolicy

**Comment by tmiroslav** [comment]
This is correct.
But, while creating my role I defined assume_role_policy like:
  assume_role_policy = <<EOF
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
So, this role is, through IAM profile assigned to ec2 where telegraf is running. Shouldn't this be enough for telegraf to assume  role properly? (This is how we usually do with our services built inhouse). Why it is needed to define 'sts:AssumeRole' privilege in separate IAM policy which is being attached to role? Assume role privilege was granted when role is defined, and I do  not understand why telegraf is unable to use it? But needs this privilege additionally attached through separate IMA policy?

**Comment by apoorv-garg** [comment]
Well, then in that case you don't need to specify the `role_arn` in the telegraf config, and it will pick the role passed via instance profile.

**Comment by tmiroslav** [comment]
This is also correct, I have just tested. I was confused about this all how needs to be setup.
Thanx!
