### ISSUE TITLE
RHEL7: GLIBC_2.28 not found 

### ISSUE THREAD

**Issue by poulhs** [influxdata/telegraf#8222]
I am testing the nightly build and gets the following error:
`/usr/bin/telegraf: /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by /usr/bin/telegraf)`

Telegraf nighly was fine 
`2020-10-02T05:51:01 CET    Telegraf unknown (git: master 4fa620fd)`

but failed the day after.

https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.x86_64.rpm

### System info:

`ls -l /usr/lib/.build-id/9b/460736248d88ad84c0bbcd2d305a46ccc1f336`
`lrwxrwxrwx. 1 root root 28 Oct  4 20:02 /usr/lib/.build-id/9b/460736248d88ad84c0bbcd2d305a46ccc1f336 -> ../../../../usr/bin/telegraf`

`uname -srvmpio`
`Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`

`strings /lib64/libc.so.6` gives 
 
- GLIBC_2.2.5
- GLIBC_2.2.6
- GLIBC_2.3
- GLIBC_2.3.2
- GLIBC_2.3.3
- GLIBC_2.3.4
- GLIBC_2.4
- GLIBC_2.5
- GLIBC_2.6
- GLIBC_2.7
- GLIBC_2.8
- GLIBC_2.9
- GLIBC_2.10
- GLIBC_2.11
- GLIBC_2.12
- GLIBC_2.13
- GLIBC_2.14
- GLIBC_2.15
- GLIBC_2.16
- GLIBC_2.17
- GLIBC_PRIVATE

### Steps to reproduce:

1. download https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.x86_64.rpm
2. yum localinstall
3. /usr/bin/telegraf

### Expected behavior:

Something like:
`2020-10-04T18:23:08Z I! Starting Telegraf 1.15.3`
`2020-10-04T18:23:08Z I! Using config file: /etc/telegraf/telegraf.conf`
`2020-10-04T18:23:08Z E! [telegraf] Error running agent: Error: no outputs found, did you provide a valid config file?`

### Actual behavior:

`/usr/bin/telegraf: /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by /usr/bin/telegraf)`

## Additional info:

`rpm -qa --last |head -1`
`telegraf-1.16.0-0.x86_64                      Sun 04 Oct 2020 08:02:33 PM CEST`

**Comment by reimda** [comment]
It looks like #8114 added this new dependency on glibc 2.28.  It uses go-sqlite3 which adds a dynamic library dependency on fcntl64 which was added in glibc 2.28.

**Comment by p-zak** [comment]
@poulhs @reimda 
Hi, I've started to investigate this.

**Comment by p-zak** [comment]
@poulhs @reimda 
My team has already started working on fix, we hope to deliver it in next week.

**Comment by reimda** [comment]
We temporarily reverted #8114 in master and release-1.16 to remove the glibc dependency.  @poulhs would you test 1.16.0-rc2 and/or future nightly builds?

We also added a build check in #8278 hopefully to prevent requiring a glibc newer than we expect.

**Comment by reimda** [comment]
This has been fixed since 1.16.0-rc2.  RAS was readded in 1.16.0 with the glibc dependency removed.  @poulhs, If it isn't working for you please reopen

**Comment by Tocard** [comment]
Looks like this problem is still persistent on 1.17.3
