### ISSUE TITLE
[input.snmp] feature request change snmp walk to snmp bulk walk

### ISSUE THREAD

**Issue by depfryer** [influxdata/telegraf#8235]
## Feature Request

Opening a feature request kicks off a discussion.
### Proposal:

change SNMP walk to snmp Bulk in the SNMP input

### Current behavior:
```
$ time snmpwalk -v 2c -c FAKE IP  OID | wc -l
610

real    0m7,926s
user    0m0,208s
sys     0m0,181s

```
### Desired behavior:
```
$ time snmpbulkwalk -v 2c -c FAKE IP  OID | wc -l
610

real    0m1,458s
user    0m0,191s
sys     0m0,118s
```
### Use case: 
it optimise use of SNMP 
screen of gosnmp doc :
![image](https://user-images.githubusercontent.com/17575141/95356770-51462e00-08c7-11eb-9ab5-6283d1954e44.png)

**Comment by depfryer** [comment]
another much more extreme example : 

```
$ time snmpwalk |wc -l
973

real    1m43,460s
user    0m0,290s
sys     0m0,258s

$ time snmpbulkwalk |wc -l
973

real    0m2,635s
user    0m0,192s
sys     0m0,185s
```

**Comment by Hipska** [comment]
AFAIK telegraf is already using GETBULK, you can configure it by using the `max_repetitions` config setting (defaults to 10).

**Comment by depfryer** [comment]
hi sorry for my long time to respond

yes 
```
  ## The GETBULK max-repetitions parameter.
  # max_repetitions = 10
``` 
is really helpful for understand and when i look in plugin snmp max_repetitions only appear once, in sample config.....
so where it is used ? (or it is used in legacy mode)

also i see GETBULK only in legacy mode. in new SNMP plugin, where is a trully fonctionnal gs.getbulk (or gosnmp.getbulk, i con"t find it)

thank you for  the help

**Comment by Hipska** [comment]
See https://github.com/influxdata/telegraf/blob/9ee6e034fb6149d78515511ba4b841db8ac9bdc4/internal/snmp/wrapper.go#L88

And then later on this gets used by https://github.com/influxdata/telegraf/blob/9ee6e034fb6149d78515511ba4b841db8ac9bdc4/internal/snmp/wrapper.go#L30-L34

**Comment by depfryer** [comment]
because when i looking in "telegraf / plugins / inputs / snmp / snmp.go", we only see reference to walk (only one to bulk and it's a comment)
also i missed the line "telegraf / internal / snmp" and didn't read it...
also because telegraf work like 7 min to query the list of router but with my bashscript it's  way faster

**Comment by Hipska** [comment]
Did you do an actual tcpdump to verify telegraf sends out WALK instead of BULKWALK requests? As you see in the code, it will use BULKWALK when snmp version is not v1.

**Comment by depfryer** [comment]
i use snmp version  2 
and no i don't try a tcpdump

**Comment by Hipska** [comment]
Thanks, I will now close this issue since Telegraf already supports BULKWALK.
