### ISSUE TITLE
inconsistent GROK results

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#8236]
Hi getting wierd grok results as follows

conf file is:
[[inputs.exec]]
  ## Commands array
  commands = [
    'E:\\test\\shared\\jdk\\oracle-jdk-8-win64\\1.8\\bin\\java -jar c:\\telegraf\\bin\\JMXMonitor.jar -classpath c:\\telegraf\\bin\\monitoring.properties'
  ]

  ## Timeout for each command to complete.
  timeout = "10s"
  interval = "10m"

  ## measurement name suffix (for separating different commands)
  name_override = "test_JMX"
  
  data_format = "grok"
  grok_patterns = ["%{WORD:Document_Type:tag}=%{WORD:State}"]

[[inputs.exec]]
  ## Commands array
  commands = [
    'E:\\test\\shared\\jdk\\oracle-jdk-8-win64\\1.8\\bin\\java -jar c:\\telegraf\\bin\\JMXMonitor.jar -classpath c:\\telegraf\\bin\\monitoring.properties'
  ]

  ## Timeout for each command to complete.
  timeout = "10s"
  interval = "10m"

  ## measurement name suffix (for separating different commands)
  name_override = "test_JMX"
  
  data_format = "grok"
  grok_patterns = ["%{WORD:Document_Type:tag}=%{NUMBER:Value:int}"]

result of the exec on stdout is:

STDout echos similar to the following:

Service_DocumentProcessor_Status=RUNNING
Service_IndexUpdateScheduler_Status=RUNNING
Service_SequenceNumberStatusClientMonitor_Status=RUNNING
Queue_BackOfficeTP_Failed=0
Queue_BackOfficeTP_Processed=0
Service_XMLFileImporter_Status=RUNNING
Queue_BackOfficeTP_Pending=0
Service_DiaryEntryRunner_Status=RUNNING
Service_DownloadProxy_Status=RUNNING
TomcaDatabase_NumActive=8
Service_UpdateService_Status=RUNNING
Queue_BackOfficeTP_Retry=0
Service_RMIProcessServiceManager_Status=RUNNING
Service_ServerQueueConnector_Status=RUNNING
TomcaDatabase_NumIdle=6
Queue_BackOfficeTransactionsOut=0

stdout from telegraf with --test

2020-10-07T16:07:47Z I! Starting Telegraf 1.15.2
2020-10-07T16:07:47Z E! Unable to open c:/Telegraf/telegraf.log (open c:/Telegraf/telegraf.log: Access is denied.), using stderr
2020-10-07T16:07:47Z D! [agent] Initializing plugins
2020-10-07T16:07:47Z D! [agent] Starting service inputs
2020-10-07T16:07:48Z D! Grok no match found for: "Service_DocumentProcessor_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_IndexUpdateScheduler_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_SequenceNumberStatusClientMonitor_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_XMLFileImporter_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_DiaryEntryRunner_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_DownloadProxy_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_UpdateService_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_RMIProcessServiceManager_Status=RUNNING"
2020-10-07T16:07:48Z D! Grok no match found for: "Service_ServerQueueConnector_Status=RUNNING"
 test_JMX,Document_Type=Queue_BackOfficeTP_Failed,ENV=NONPROD,host=DLS0180eps-PP Value=0i 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Processed,ENV=NONPROD,host=DLS0180eps-PP Value=0i 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Pending,ENV=NONPROD,host=DLS0180eps-PP Value=0i 1602086868000000000
 test_JMX,Document_Type=TomcaDatabase_NumActive,ENV=NONPROD,host=DLS0180eps-PP Value=7i 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Retry,ENV=NONPROD,host=DLS0180eps-PP Value=0i 1602086868000000000
 test_JMX,Document_Type=TomcaDatabase_NumIdle,ENV=NONPROD,host=DLS0180eps-PP Value=7i 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTransactionsOut,ENV=NONPROD,host=DLS0180eps-PP Value=0i 1602086868000000000
2020-10-07T16:07:48Z D! [agent] Stopping service inputs
2020-10-07T16:07:48Z D! [agent] Input channel closed
2020-10-07T16:07:48Z D! [agent] Stopped Successfully
 test_JMX,Document_Type=Service_DocumentProcessor_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Service_IndexUpdateScheduler_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Service_SequenceNumberStatusClientMonitor_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Failed,ENV=NONPROD,host=DLS0180eps-PP State="0" 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Processed,ENV=NONPROD,host=DLS0180eps-PP State="0" 1602086868000000000
 test_JMX,Document_Type=Service_XMLFileImporter_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Pending,ENV=NONPROD,host=DLS0180eps-PP State="0" 1602086868000000000
 test_JMX,Document_Type=Service_DiaryEntryRunner_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Service_DownloadProxy_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=TomcaDatabase_NumActive,ENV=NONPROD,host=DLS0180eps-PP State="7" 1602086868000000000
 test_JMX,Document_Type=Service_UpdateService_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTP_Retry,ENV=NONPROD,host=DLS0180eps-PP State="0" 1602086868000000000
 test_JMX,Document_Type=Service_RMIProcessServiceManager_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=Service_ServerQueueConnector_Status,ENV=NONPROD,host=DLS0180eps-PP State="RUNNING" 1602086868000000000
 test_JMX,Document_Type=TomcaDatabase_NumIdle,ENV=NONPROD,host=DLS0180eps-PP State="6" 1602086868000000000
 test_JMX,Document_Type=Queue_BackOfficeTransactionsOut,ENV=NONPROD,host=DLS0180eps-PP State="0" 1602086868000000000

Is it working, or not ?

Cheers
Simon

**Comment by SimonMcN** [comment]
Have just tried this too

[[inputs.exec]]
  ## Commands array
  commands = [
    'E:\\Enactor\\shared\\jdk\\oracle-jdk-8-win64\\1.8\\bin\\java -jar c:\\telegraf\\bin\\JMXMonitor.jar -classpath c:\\telegraf\\bin\\monitoring.properties'
  ]

  ## Timeout for each command to complete.
  timeout = "10s"
  interval = "10m"

  ## measurement name suffix (for separating different commands)
  name_override = "Enactor_JMX"
  
  data_format = "grok"
  grok_patterns = ["%{WORD:Numerical:tag}=%{NUMBER:Value:int}","%{WORD:textual:tag}=%{WORD:State}"]

**Comment by sspaink** [comment]
@SimonMcN sorry you haven't had a response in a long time, are you still having this issue?
