### ISSUE TITLE
Modbus output plugin

### ISSUE THREAD

**Issue by mateuszz-sudo** [influxdata/telegraf#8244]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
What do you think about implementing of modbus output plugin? This feature could be used to control devices connected to telegraf via Modbus TCP or RTU, based on collected data. 

### Use case:
My use case is running telegraf on GSM embedded device to read data on modbus tcp, and send further to cloud using MQTT. But in many cases like this, the ability to communicate in both directions would be very useful:
* to make some changes in parameters of device connected to telegraf,
* to reset some errors,
* to trigger some actions on device, etc. 

Of course this feature could be worked around now (i.e. using exec plugin and some Python script), but using built in plugin would be much easier, what is your opinion about this idea?

**Comment by shnabin** [comment]
Hi @mateuszz-sudo : Do you mean to say, the request is to write_registers (coil, input, discrete, holding) to the devices connected to telegraf.

**Comment by mateuszz-sudo** [comment]
Hi,

Yes @shnabin - this is exactly what I'm thinking about. Inputs like MQTT or HTTP requests (or any inputs avaliable for now) could be used to trigger changes in values on modbus device registers / coils (i. e. in PLC controller connected to working telegraf instance). 

Of course the most important would be covering to write holding registers and coils (Function codes 5,6 for single write or 15,16 for multiple coil/register write). 

My use case is to run telegraf on embedded device like below (except it has Ethernet interface, not RS232) together with PLC controller: 
![image](https://user-images.githubusercontent.com/65446967/95784377-fef47b00-0cd3-11eb-861b-bd1bc7fec276.png)
GSM router runs telegraf, which reads data on modbus (TCP) and send it to SCADA system using MQTT protocol. But as I wrote before  - bidirectional communication would allow not only to read data from multiple PLC controllers, but also to remotely control those devices - in secure way (protocols like MQTT could be encrypted in oposite to Modbus).

**Comment by srebhan** [comment]
@mateuszz-sudo I think that is not what telegraf is made for. Telegraf is a _metric_ **acquisition** software and IMO we should not make it a _doeverythingyoucouldeverimagine_ software. But I'm not the one making such decisions. :-)

That being said, you could write the _actuator_ reading from MQTT and writing to modbus yourself and install on the GSM router. You could even do it in golang and use the same library as telegraf does. The only prerequisite is that your modbus device accepts two simultaneous connections (or we need to disconnect telegraf after each read).

**Comment by mateuszz-sudo** [comment]
Thank you for feedback @srebhan - that is why I've started this topic :) 

But in one thing I can't agree with you - IMO telegraf would be only **metric acquisition** software if it has only one output - influxdb :) Because we have avaliable so much different output protocols, from my point of view it is more like software multigateway/protocol converter, which can be used in both directions. And based on my knowledge - there are no other software in industry, which can be used so easily as IIoT gateway. Of course this is only my opinion, and I could be wrong (or my use case is not as popular as I think) :) 

And of course, as I wrote at starting point, and you confirmed - this use case could be worked around using existing plugins (exec), and I'm totaly aware of it (and probably I would implement it in Python anyway, because I simply need this functionality now). But anyways - If you consider  to implement such plugin in the future it would be nice step, and I'm seeing very useful use cases for it in industry applications, where it's needed to collect large amount of data, and to control devices remotely at the same time.

**Comment by mmichelli** [comment]
This is exactly our use case as well.

**Comment by sci-c0** [comment]
Any work going on regarding this plugin? This would be very helpful for my usecase too.

**Comment by srebhan** [comment]
Could you guys outline your use-cases a bit more?

@mateuszz-sudo, currently telegraf _acquires_ **metrics** on the _input_ side and then sends those **metrics** to _all_ (one or more) configured data-sinks. So there is a clear information flow (data-sources --> telegraf (metric) --> data-sinks) and a clear _data format_. So I wonder how a _general_ format would look like for your use case which I understand as: "some command source" --> telegraf (format?)  --> "one specific command sink". This opens up all kind of issues, like solving the routing on which command should be sent to which command-sink, handling fundamentally different command formats etc. So you cannot solve this with a "simple" output plugin, but you need a new class (maybe `cmd_output`?) of plugins, provide the routing infrastructure etc...

**Comment by srebhan** [comment]
Similar to #7195, I suggest to implement this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md). Please submit a PR to link to this plugin once it is ready.

**Comment by patfrench** [comment]
Hello,

I have the same use case: I monitor the status of modbus devices.

![image](https://user-images.githubusercontent.com/44723412/196656971-b718949c-b2a7-46db-a605-40cf4b4ea956.png)

And I would like to be able to interact with my devices from the dashboard (maintenance, acknowledgement, test)
Are the writing functions : 3-4 and 6-16 in the roadmap ? 

I can contribute by testing on real hardware because I am not good enough in programming

Thanks in advance
