### ISSUE TITLE
HTTP Output compression not working

### ISSUE THREAD

**Issue by buzzsumit** [influxdata/telegraf#8248]
I have enabled http compression for output plugin but the request payload(Data to be sent to HTTP end point) is NOT getting compressed.

I am getting the response/behaviour pre 1.9 in which uncompressed body was the only option

See details of the fixes here [https://github.com/influxdata/telegraf/issues/4472]( https://github.com/influxdata/telegraf/issues/4472
)
```
### Relevant telegraf.conf:
[[outputs.http]]
 url = "https://xx.xxxxxxxx.com/api/v0.1/data"
 data_format = "json"
 timeout = "60s"
[outputs.http.headers]
 authorization = "Basic xxxxxxxxxxxxxxxxxxxxxxxxx"
 Content-Type = "application/json"
 content_encoding = "gzip" (edited) 
```

### System info:

telegraf version 1.10.4
Ubuntu 18.04.2 LTS

### Steps to reproduce:

1. Configure output plugin as above.
2. Take Tcpdump of data on http endpoint or telegraf client.
3. Request content length of the HTTP request is equal to uncompressed payload.
4. tcpdump shows the body is NOT compressed.

**Comment by ssoroka** [comment]
Looks like you have the configuration wrong. In TOML, once you start the `headers` section, you can't go back to the `http` section, so the content_encoding needs to be above the headers.

```
### Relevant telegraf.conf:
[[outputs.http]]
 url = "https://xx.xxxxxxxx.com/api/v0.1/data"
 data_format = "json"
 timeout = "60s"
 content_encoding = "gzip"
[outputs.http.headers]
 authorization = "Basic xxxxxxxxxxxxxxxxxxxxxxxxx"
 Content-Type = "application/json"

```
