### ISSUE TITLE
Add "embedded_tags" in GNMI Plugin

### ISSUE THREAD

**Issue by purifp** [influxdata/telegraf#8250]
## Feature Request

Add "embedded_tags" in GNMI Plugin

### Proposal:

We need add for GNMI the feature "embedded_tags" like the plugin "cisco_telemetry_mdt" has:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cisco_telemetry_mdt

Define (for certain nested telemetry measurements with embedded tags) which fields are tags
 embedded_tags = ["Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics/class-stats/class-name"]

### Current behavior:
In some yang models (iosxr  telemetry) there are certain fields that are defined like a fields but really they are tags, for example this measure 
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics/class-stats/class-name"
 
IOSXR Routers send "source","interface-name","service-policy-name" like tags but can be more than one "class-name" in one "service-policy-name". In our case, we have  7 different "class-name" with statistics of each class-name in a service-policy and telegraf only sent to the output the last one because we can not change this field to tag in the input plugin

### Desired behavior:

To define some fields like tags in input.

### Use case: 

IOSXR Telemetry

**Comment by kb70** [comment]
Hi,
isn't that very similar to issue #7462 ?

**Comment by patrikh-dev** [comment]
this was fixed in `cisco_telemetry_mdt` plugin by @sbyx https://github.com/influxdata/telegraf/issues/6322 but unfortunately still missing in `gnmi`

**Comment by bofh16** [comment]
Hello, have you already undestanding of the eventual deployment path for this feature, please?

**Comment by bofh16** [comment]
Hello,
It doesn't seem to work.

$ telegraf --config telegraf_1.conf
2022-03-08T11:48:05Z E! [telegraf] Error running agent: Error loading config file telegraf_1.conf: plugin inputs.gnmi: line 57: configuration specified the fields ["embedded_tags"], but they weren't used
$ telegraf --version
Telegraf 1.22.0-2c2fcc46 (git: master 2c2fcc46)
