### ISSUE TITLE
 [inputs.exec] Error in plugin: metric parse error: expected field at 1:30

### ISSUE THREAD

**Issue by EdBab** [influxdata/telegraf#8255]
### System info:

telegraf --version
Telegraf 1.15.3 (git: HEAD fac81815)

Red Hat Enterprise Linux Server 7.6 (Maipo)

### Steps to reproduce:
Using the exec plugin, simple bash script printing output in line protocol format

Couldn't get it to work using my real script, so I ran a simple script printing:
`weather,location=This alert will trigger if stuff happens temperature=82`

Tried again with quotes:
`weather,location="This alert will trigger if stuff happens" temperature=82`

Neither works, both throw the same error. 

The only thing I can think is that there is some sort of character limit for a tag value's output

### Expected behavior:

I expect no errors and for this data to be sent to influxdb

### Actual behavior:

The error is thrown, no data is sent

**Comment by M0rdecay** [comment]
Spaces in tag values should be escaped - https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#special-characters
Try to do this:
```
weather,location=This\ alert\ will\ trigger\ if\ stuff\ happens temperature=82
```

**Comment by reimda** [comment]
Also in the doc M0rdecay linked, "Do not double or single quote measurement names, tag keys, tag values, and field keys".

Using double quotes is correct around string fields though.
