### ISSUE TITLE
Telegraf SNMP connect two or more tables

### ISSUE THREAD

**Issue by aramaki87** [influxdata/telegraf#8260]
I don't know how to connect two SNMP tables for further usage in grafana.
I would like to do queries like: show me connected users for every SSID where SSID is WIFI1 BUT the two tables are not connected. How do I tell telegraf / grafana / influxdb that wifi1 has 1 user and wifi2 has 0 user correlating the other table? This is just an example config... I would also like to see the IP/MAC and so on in other SNMP OIDs.

Background info:
SNMP using Cisco WLC devices

Lets say I have some SSIDs
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.1 = STRING: "WIFI1"
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.2 = STRING: "WIFI2"
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.3 = STRING: "WIFI3"
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.4 = STRING: "WIFI4"

and I have the connected users here
SNMPv2-SMI::enterprises.14179.2.1.1.1.38.1 = Counter32: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.38.2 = Counter32: 0
SNMPv2-SMI::enterprises.14179.2.1.1.1.38.3 = Counter32: 6
SNMPv2-SMI::enterprises.14179.2.1.1.1.38.4 = Counter32: 0

My (working) but not connected telegraf config so far:
`[[inputs.snmp]]
  agents = [ "10.x.x.x:161"]
  version = 2
  community = "whatEver"
  name = "WLC"

[[inputs.snmp.table]]
  name = "WLAN"

  [[inputs.snmp.table.field]]
    name = "ssid_name"
    oid = "SNMPv2-SMI::enterprises.14179.2.1.1.1.2"
    is_tag = true

  [[inputs.snmp.table.field]]
    name = "user_count"
    oid = "SNMPv2-SMI::enterprises.14179.2.1.1.1.38"`

**Comment by sjwang90** [comment]
Hi @aramaki87, we reserve Telegraf issues for bug or reproducible problems.  Can you please post this into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this answered quickly?

**Comment by aramaki87** [comment]
> 
> 
> Hi @aramaki87, we reserve Telegraf issues for bug or reproducible problems. Can you please post this into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this answered quickly?

Very nice community here. Your links are broken at least the slack link. Community page is nice but my account is temporarily on hold since 10 days.

**Comment by sjwang90** [comment]
Apologies, the community slack link is www.influxdata.com/slack. If you prefer to get your question addressed here you can re-open the issue.

You may just get a faster response on our community slack.

**Comment by aramaki87** [comment]
I figuered it out myself.
