### ISSUE TITLE
[inputs.postfix] Error in plugin: error scanning /opt/zimbra/data/postfix/spool/deferred: lstat /opt/zimbra/data/postfix/spool/deferred/F: permission denied

### ISSUE THREAD

**Issue by Daly123456** [influxdata/telegraf#8264]
i have installed telegraf on my zimbra server and i got that error with {inputs.postfix]
i think it's a permission problem so i changed my autorisation from :
drwx------.  2 root root    6 14 oct.  12:24 active
drwx------.  2 root root    6 30 juil. 03:07 bounce
drwx------.  2 root root    6 29 juil. 19:18 corrupt
drwx------. 18 root root  150 20 août  09:41 defer
drwxr--r--. 18 root root  150 20 août  09:41 deferred
drwx------.  2 root root    6 29 juil. 19:18 flush
drwx------.  2 root root    6 29 juil. 19:18 hold
drwx------.  2 root root    6 14 oct.  12:24 incoming
drwx-wx---.  2 root root    6 29 juil. 19:18 maildrop
drwxr-xr-x.  2 root root  287 21 sept. 17:06 pid
drwx------.  2 root root 4096 14 oct.  09:45 private
drwx--x---.  2 root root   73 14 oct.  09:45 public
drwx------.  2 root root    6 29 juil. 19:18 saved
drwx------.  2 root root    6 14 oct.  11:00 trace

to: 
drwx------.  2 postfix postfix    6 14 oct.  12:24 active
drwx------.  2 postfix postfix    6 30 juil. 03:07 bounce
drwx------.  2 postfix postfix    6 29 juil. 19:18 corrupt
drwx------. 18 postfix postfix  150 20 août  09:41 defer
drwxr--r--. 18 postfix postfix  150 20 août  09:41 deferred
drwx------.  2 postfix postfix    6 29 juil. 19:18 flush
drwx------.  2 postfix postfix    6 29 juil. 19:18 hold
drwx------.  2 postfix postfix    6 14 oct.  12:24 incoming
drwx-wx---.  2 postfix postfix    6 29 juil. 19:18 maildrop
drwxr-xr-x.  2 postfix postfix  287 21 sept. 17:06 pid
drwx------.  2 postfix postfix 4096 14 oct.  09:45 private
drwx--x---.  2 postfix postfix   73 14 oct.  09:45 public
drwx------.  2 postfix postfix    6 29 juil. 19:18 saved
drwx------.  2 postfix postfix    6 14 oct.  11:00 trace

but i still get the same error !!!
i followed this '''postfix permission denied #3752''
but i couldn't find nothing

**Comment by sjwang90** [comment]
Hi @Daly123456. We reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
