### ISSUE TITLE
External processor plugin - configuration not applied

### ISSUE THREAD

**Issue by a-bali** [influxdata/telegraf#8272]
This is a reopen of #8153 with some more details. Applies to current version as of today.

I have written a simple external processor plugin, see source code [here](https://github.com/a-bali/telegraf-geoip), following the instructions [here](https://github.com/influxdata/telegraf/blob/master/plugins/common/shim/README.md).

The plugin is invoked with execd as follows:

    [[processors.execd]]
    command = ["/home/bali/geoip", "-config", "/home/bali/plugin.conf"]

And the problem is that the contents of the specified configuration file are read but not applied to the plugin.

I have also found out that it works properly in case the external processor plugin is a StreamingProcessor instead of a standard Processor, therefore the problem appears to be when [a Processor is converted to a StreamingProcessor](https://github.com/influxdata/telegraf/blob/d5f0a120d86d320c51f9bdf091e1db59ef97240f/plugins/common/shim/processor.go#L16), the configuration settings are not applied.

**Comment by ssoroka** [comment]
ah, yes, I think you're on to something there. I'll check out your example code and figure out what's going on.

**Comment by ssoroka** [comment]
Thanks for the detailed bug report. That made it easy to track down. It's patched now, and will be in the nightly release tomorrow, and will be in 1.16.0-rc2 and 1.15.4 when they come out.
