### ISSUE TITLE
Net response plugin overwrites the host tag

### ISSUE THREAD

**Issue by tuupola** [influxdata/telegraf#828]
Net response plugin overrides the host tag with the target host. Offending line is most likely [#L172](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net_response/net_response.go#L172)

**Comment by titilambert** [comment]
@tuupola good point !
What about something like:
```
net_response,src=myhostname,host=myswitch,port=22,protocol=tcp response_time=0.18070360500000002,string_found=true 1454785464182527094
```
where `src` is the host from where the request is done and `host` is the targeted host ?

**Comment by sparrc** [comment]
target host tag should be changed to something like "server"
