### ISSUE TITLE
Yandex.Cloud monitoring output plugin

### ISSUE THREAD

**Issue by peter-volkov** [influxdata/telegraf#8295]
I'm here to contribute an output plugin to send metrics to
https://cloud.yandex.com/services/monitoring

During the initial stage I plan only to support basic scenario, 
where Telegraf service is being run in Compute instance and takes credentials from instance metadata.

Later on we will add full possibilities for configuration.

This issue is for questions from maintainers and discussions.

**Comment by sjwang90** [comment]
Closed in PR #8296. Thanks for the plugin @peter-volkov!

**Comment by peter-volkov** [comment]
@ssoroka and will this plugin be included in some release?
I see at least two releases were published since this PR was merged
