### ISSUE TITLE
input/tail/multiline plugin: the newline symbol is missing in the output

### ISSUE THREAD

**Issue by agvol** [influxdata/telegraf#8303]
```
> telegraf --version
Telegraf 1.16.0 (git: HEAD c2a53d0f)
```

Howto reproduce:

config:
```
   [inputs.tail.multiline]
     pattern = '^\s'
     match_which_line = "previous"
```

Try to parse this example:

```
first
 second
 third
```
output is:
`"first second third"`

output must be
```
first
 second
 third
```

**Comment by MyaLongmire** [comment]
Thank you for opening this bug, I'm sorry no one has gotten back to you.

I have a few questions:
1) How are you paring the input? What are your settings for data_format and data_type?
2) What are you outputting too? What is your end goal?

Thanks :)
