### ISSUE TITLE
2 [[inputs.http]] with 2 different database

### ISSUE THREAD

**Issue by olegsidokhmetov** [influxdata/telegraf#8305]
Hello!

I have a question.

I have 2 [[inputs.http]] and 2  [[outputs.influxdb]] with 2 different database.

- **/etc/telegraf/telegraf.d# file1.conf** 

###############################################################################
                                  INPUTS  
###############################################################################
[[inputs.http]]
    name_override = "jitsi_stats"
    urls = [
      "https://address.com/colibri/stats"
    ]

    data_format = "json"
###############################################################################
                                  OUTPUTS                                    
###############################################################################
[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    **database = "jitsi"**
    timeout = "0s"
    retention_policy = ""

- **/etc/telegraf/telegraf.d# file2.conf** 

###############################################################################
                                  INPUTS                                     
###############################################################################
[[inputs.http]]
    name_override = "jitsi_CM"
    urls = [
      "https://address.net/HfKrhKf8939lolsaln"
    ]

    data_format = "json"
###############################################################################
                                  OUTPUTS                                   
###############################################################################
[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = **"jitsi_cm"**
    timeout = "0s"
    retention_policy = ""

- **File of configuration /etc/telegraf# telegraf.conf**

[global_tags]
###############################################################################
                                  GLOBAL                                     
###############################################################################
[agent]
    interval = "10s"
    debug = false
    hostname = "jitsi_cm"
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = "/var/log/telegraf/jitsi.log"
    omit_hostname = true

I need, that all metrics from each different database will be save in database with the same name.
So, what I have now?! In each database I have MEASUREMENT from 2 different databases

Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
- show databases
name: databases
name
---
telegraf
__internal
**jitsi
jitsi_cm**
* use jitsi
Using database jitsi
* show measurements
name: measurements
name
---
cpu
**jitsi_cm
jitsi_stats**
mem
* use jitsi_cm
Using database jitsi_cm
*show measurements
name: measurements
name
---
cpu
**jitsi_cm
jitsi_stats**
mem

How I can separate this DB that this measurement will be in the ONLY own DB? After that I want to see this separated measurement in Grafana.

**Comment by srebhan** [comment]
Hey @olegsidokhmetov, you can use [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) to do that. In your configuration you can use `namepass` as follows:
`file1.conf`:
```
[[inputs.http]]
    name_override = "jitsi_stats"
    urls = ["https://address.com/colibri/stats"]
    data_format = "json"

[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = "jitsi"
    timeout = "0s"
    retention_policy = ""
    namepass = ["jitsi_stats"]
```
and `file2.conf`:
```
[[inputs.http]]
    name_override = "jitsi_CM"
    urls = ["https://address.net/HfKrhKf8939lolsaln"]
    data_format = "json"

[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = "jitsi_cm"
    timeout = "0s"
    retention_policy = ""
    namepass = ["jitsi_CM"]
```

Let me add a general comment:
You might get a quicker answer when joining [Slack](https://influxcommunity.slack.com/) or the [community forum](https://community.influxdata.com/) and ask there.

**Comment by olegsidokhmetov** [comment]
> 
> 
> Hey @olegsidokhmetov, you can use [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) to do that. In your configuration you can use `namepass` as follows:
> `file1.conf`:
> 
> ```
> [[inputs.http]]
>     name_override = "jitsi_stats"
>     urls = ["https://address.com/colibri/stats"]
>     data_format = "json"
> 
> [[outputs.influxdb]]
>     urls = ["http://localhost:8086"]
>     database = "jitsi"
>     timeout = "0s"
>     retention_policy = ""
>     namepass = ["jitsi_stats"]
> ```
> 
> and `file2.conf`:
> 
> ```
> [[inputs.http]]
>     name_override = "jitsi_CM"
>     urls = ["https://address.net/HfKrhKf8939lolsaln"]
>     data_format = "json"
> 
> [[outputs.influxdb]]
>     urls = ["http://localhost:8086"]
>     database = "jitsi_cm"
>     timeout = "0s"
>     retention_policy = ""
>     namepass = ["jitsi_CM"]
> ```
> 
> Let me add a general comment:
> You might get a quicker answer when joining [Slack](https://influxcommunity.slack.com/) or the [community forum](https://community.influxdata.com/) and ask there.

Thank you very much for your advice.

I added this line in my file1.conf and file2.conf , then restart telegraf, but I am still have measurements in each database

InfluxDB shell version: 1.8.3
> show databases
name: databases
name
----
telegraf
_internal
jitsi
jitsi_cm
> use jitsi
Using database jitsi
> show measurements
name: measurements
name
----
cpu
jitsi_cm
jitsi_stats
mem
> use jitsi_cm
Using database jitsi_cm
> show measurements
name: measurements
name
----
cpu
jitsi_cm
jitsi_stats
mem
>

**Comment by srebhan** [comment]
Ummm did you clear the database? Otherwise the old data will still be there of course. :-)

**Comment by olegsidokhmetov** [comment]
> 
> 
> Ummm did you clear the database? Otherwise the old data will still be there of course. :-)

ok! Thank you! I will try to clear DB!

One more things, how I can add host name in my file1.conf and file2.conf that  I can select this host from my Grafana?

P.S. I have line hostname = "" in /etc/telegraf/telegraf.conf but I see only host where my telegraf installed :(

**Comment by srebhan** [comment]
Please take a look at the [input plugins configuration documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins)! You can add tags as e.g.:
```
[[inputs.http]]
    name_override = "jitsi_stats"
    urls = ["https://address.com/colibri/stats"]
    data_format = "json"

    [inputs.http.tags]
        hostname = "address.com"
        anothertagname = "anothertagvalue"

```

**Comment by srebhan** [comment]
Oh and btw: Please close the issue if your question is resolved! :-)

**Comment by olegsidokhmetov** [comment]
Hello again :)

I try to do all correct, but I think I have the same problems.
So, I did all as you wrote, I added all options in my config file, But... When i use "influx" to see what happened in DB I see this
```
Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> show databases
name: databases
name
----
telegraf
_internal
jitsi
jitsi_cm
> use jitsi
Using database jitsi
> show measurements
name: measurements
name
----
cpu
jitsi_cm
jitsi_stats
mem
```

The same situation, in DB "jitsi" i have metrisc from "jitsi_cm" and "jitsi_stats"

and 
```
> use jitsi_cm
Using database jitsi_cm
> show measurements
name: measurements
name
----
cpu
jitsi_cm
jitsi_stats
mem
```

 in DB "jitsi_cm" I have metric from "jitsi_cm" and "jitsi_stats"
 
 IF I understand correct, in each database should be only metric with name which we set in config file? Or no? 
 
FILE1.conf
```
#                                  INPUTS                                     #

[[inputs.http]]
    name_override = "jitsi_stats"
    urls = ["https://js.name.com/colibri/stats"]
    data_format = "json"

    [inputs.http.tags]
        hostname = "name_com"

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = "jitsi"
    timeout = "0s"
    retention_policy = ""
    namepass = ["jitsi_stats"]
```

FILE2.conf
```
###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.http]]
    name_override = "jitsi_cm"
    insecure_skip_verify = true
    urls = ["https://js.name1.net/Awaalljksaln"]
    data_format = "json"

    [inputs.http.tags]
        hostname = "name1_net"

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = "jitsi_cm"
    timeout = "0s"
    retention_policy = ""
    namepass = ["jitsi_cm"]
```
In DB "jitsi" should be only metrics with "jitsi_stats", and in Grafana I can choose name "name_com" to see metrics from name_com https://js.name.com/colibri/stats

Bu also know I have the same metric in Grafana in two DB, does not matter if I choose DB "jitsi" or "jitsi_cm", I do not why.

What I should to do that separate all this DB, and use one of them in separate Dashboards in Grafana?

**Comment by srebhan** [comment]
Are you really sure you started with a clean database? Please check the latest entries for all measurement in both databases to see if they are getting fresh data. Maybe something like `SELECT LAST(*) FROM...`.
If both are really getting fresh data, please double check if there is no other config also defining outputs to the influxdb _without_ the filters... If nothing helps, I will have to setup your config here and check, but it is unlikely (not impossible) that `namepass` fails.
