### ISSUE TITLE
Oracle input plugin for database performance

### ISSUE THREAD

**Issue by abarban** [influxdata/telegraf#831]
I'm looking for the ability to have statistical data / performace by Oracle.

I am analyzing two solutions:

A. Go live using driver as:
- https://github.com/rana/ora
- https://github.com/mattn/go-oci8

B. by a demon read in Java that expose the data in JSON

Both have positive and negative sides, the A may have a long latency due to the connection to be restored each time, the B would be an external object to Telegraf.

As always willing to test and development.

**Comment by sparrc** [comment]
From the Telegraf point of view, A would be the way to go

**Comment by menardorama** [comment]
By an Oracle Point of view, having frequent connection/disconnection is a bad practice for the listener.

**Comment by abarban** [comment]
The reason that move me to try a little demon with java, single connection and light SQL!
there is a project like https://sourceforge.net/projects/ashv/ that can be a start point.
But I think that can be so useful try both solutions.

how can I be most useful?

**Comment by menardorama** [comment]
If you want to try the A solution, you can have a look at what I did on Postgres #792 

Moving it to Oracle wouldn't be a big deal

I guess that you are trying to build a dashboard based on ASH ?

**Comment by abarban** [comment]
First milestone is to have a dashboard with Top Activity graphs on multiple Oracle instance, without detail on sessions and query.

I'm thinking about live monitoring with a way to build dashboard for applications stack (accelerator, application, db).

**Comment by sparrc** [comment]
going with A, why would it have to do frequent connect/disconnect? couldn't the plugin just cache and hold onto a connection?

**Comment by abarban** [comment]
Sure! I must try how it could work on Go! ;) I'm a junior on it.

**Comment by menardorama** [comment]
Didn't know it was possible.

Is it just by not closing the connection and add a defer close ?

**Comment by sparrc** [comment]
just making the connection a field on the plugin struct

**Comment by menardorama** [comment]
ok it's a bit out of the subject of the issue, but  do you have a link of an example ?

**Comment by bbczeuz** [comment]
I started writing a universal DB Query plugin. Just to avoid duplication: Has anybody else started working on such a plugin?

It's based on golang database/sql, so Oracle, Postgres, Mysql should be supported (tested: Oracle XE 12.1 via go-oci8). It supports dynamic tagging based on column names, multiple queries.
But it's my first golang project, so the design might not be very advanced (I'm a c++ guy). It's very alpha now, but it works for my case. I'll test larger datasets in the next weeks.

**Comment by sparrc** [comment]
thanks @bbczeuz, you can also ask in the issue for a generic db query plugin: https://github.com/influxdata/telegraf/issues/352

**Comment by StianOvrevage** [comment]
@abarban You might get some inspiration from scollectors oracle collector: https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/oracle.go . Haven't used it myself (yet) so I have no idea how applicable it is.

**Comment by desa** [comment]
@sparrc what the status of this?

**Comment by sparrc** [comment]
not planned for any upcoming release

**Comment by desa** [comment]
Been getting a bunch of interest in it here today at capital one.

**Comment by bbczeuz** [comment]
I have some running code in my fork (zseng_dev_sqlquery branch), but plan on changing the config architecture to something like the snmp plugin's. There are some non public commits in my internal repo that fix null handling.
One thing I didn't yet find a clean solution: Integrating the Oracle client, so no manual installation is needed or dynamically load some driver for Oracle DB.

**Comment by danielnelson** [comment]
#2785

**Comment by OlegKorchagin** [comment]
As a workaround, you can use the "inputs.prometheus" plugin to work with prometheus "oracle DB exporter"

This is not very convenient (and in fact rather inconvenient), but it's acceptable as a temporary solution.

1) install oracle instant client ( or full client )
2) get exporter from github page
https://prometheus.io/docs/instrumenting/exporters/
https://github.com/iamseth/oracledb_exporter/releases
3) create config for telegraf plugin ( inputs.prometheus )
```
[[inputs.prometheus]]
  urls = ["http://localhost:9161/metrics"]
  response_timeout = "3s"
  [inputs.prometheus.tags]
    db="DBNAME"
```
4) create wrapper for exporter

there must be a credentials, connection string and LD_LIBRARY_PATH
```
cd /opt/prometheus_oracle_exporter
sudo cp /usr/lib/oracle/12.2/client64/lib/libclntsh.so.12.1 libclntsh.so.18.1
vim wrapper_oracledb_exporter.sh
```

```
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$SCRIPT_DIR"

ORA_CLIENT="/usr/lib/oracle/12.2/client64"
export LD_LIBRARY_PATH="$ORA_CLIENT/lib:$SCRIPT_DIR"
export DATA_SOURCE_NAME='db_login:db_password@ORACLE_CONNECTION_STRING'
./oracledb_exporter
```
5) start wrapper, restart telegraf

6) unfortunately, almost all performance metrics go to separate influxdb measure

in some case it may be changed by replace "fieldtoappend" to "labels " in default-metrics.toml, but not all ....

**Comment by OlegKorchagin** [comment]
Also, I am not an expert in license compatibility, but it could be possible to borrow the code of this project ( also golang, MIT license ) for the plugin being created

https://github.com/iamseth/oracledb_exporter

**Comment by OlegKorchagin** [comment]
also, google suggest to create external script to get metrics from oracle

https://bdrouvot.wordpress.com/2016/03/05/graphing-oracle-performance-metrics-with-telegraf-influxdb-and-grafana/

**Comment by toni-moreno** [comment]
Hi @OlegKorchagin , have you tested this one ? It seems a good starting point to get Oracle Performace metrics into influxdb.
  
https://github.com/rsolorzano2410/sqlcollector

**Comment by reimda** [comment]
We have heard reports of people successfully using https://github.com/bonitoo-io/telegraf-input-oracle to collect oracle performance data. It is listed in the external plugins doc. https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md#inputs

The dev team doesn't have plans to implement this as an internal plugin because many oracle go drivers require cgo or don't have acceptable licensing. There is also an external workaround so I'm closing this issue.

If anyone has a way around the licensing and gco problems and wants to implement an internal oracle plugin to improve usability or functionality over the external plugin, please submit a PR and we would be happy to review it.
