### ISSUE TITLE
Define per Output plugin which input plugin is used

### ISSUE THREAD

**Issue by menardorama** [influxdata/telegraf#833]
Hi,

I wonder if it would be possible to implement for each output plugin which input is being used.

For example, lets say that you have some inputs with mostly metrics (numerics), it fit well in influxdb;
now lets say that you want also to process your apache or postgres logs and send it to a repository capable of doing full text search.

I don't want to waste space in influxdb in storing log lines and I don't want too to have numeric kpi in my fullt text search engine.

Basically we could have that :

`[[outputs.influxdb]]
  # The full HTTP or UDP endpoint URL for your InfluxDB instance.
  # Multiple urls can be specified but it is assumed that they are part of the same
  # cluster, this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://localhost:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "rulzdb" # required
  # Precision of writes, valid values are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
  # Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  # Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512
  inputs= [ system disk diskio ]

`

Or do the contrary and put some excludes; it will require less configuration.

Thanks

**Comment by sparrc** [comment]
you can already do with with namedrop/tagdrop parameters, which are available to output plugins https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tagpass-and-tagdrop

**Comment by menardorama** [comment]
Excellent thanks
