### ISSUE TITLE
outputs.socket_writer does not re-evaluate the DNS - to IP address mapping periodically

### ISSUE THREAD

**Issue by PatrickKutch** [influxdata/telegraf#8338]
Running in bare metal, using output.socket_write as so:
[[outputs.socket_writer]]
   address = "udp://my-computer.my.domain.com:50002"
   data_format = "json"

This works great, unless I reboot the target computer and it gets a new IP address.  I suggest that the socket_writer code do a dns lookup periodically to address this, I am guessing it does so during init, and then caches the IP address.

**Comment by powersj** [comment]
Hi,

Sorry, no one has gotten back to you.

Looking at the code if a connection fails and the socket was closed, Telegraf will attempt to re-run the connect command. I would expect to look up the DNS address again.

Could you provide some logs of what you are seeing, please?

Thanks!
