### ISSUE TITLE
Netstat plugin spikes cpu to close to 10%

### ISSUE THREAD

**Issue by Kedesai** [influxdata/telegraf#8345]
### Relevant telegraf.conf:

```toml

```

### Steps to reproduce:

1. ...enable the netstat plugin
2. ...make sure that the server has apache and tomcat installed.

**Comment by Kedesai** [comment]
This has not been fixed since I reported with release 14.x. Can you make sure that I test it before closing the ticket?

**Comment by Esity** [comment]
Honestly, this issue is terrible. I run the netstat input plugin on thousands of servers and don't see this behavior. Please add more details if you expect anyone to look at it

**Comment by Kedesai** [comment]
I was hoping that the old ticket was open. All you need is a web server and tomcat installed on the server. Then enable netstat plugin you can see that the telegraf process takes close to 8% cpu. There needs to be some load on the server. The servers in our Test environment have no issues. They have less impact than our bigger environments. Let me know what all details you need. I can capture a before and after if you want of enabling netstat plugin and disabling netstat plugin and capturing telegraf cpu usage in both cases. It will be good to keep the old tickets open before the fix is verified. so there is a reference point.

**Comment by Kedesai** [comment]
This is the history on the nestat plugin which has not been fixed since 1.14x The plugin is still broken since the fix put in place. This was the original ticket. https://github.com/influxdata/telegraf/issues/8345#issuecomment-720463460. You can reference for more information.
