### ISSUE TITLE
telegraf input filter kube_inventory has bug

### ISSUE THREAD

**Issue by wuguanyu** [influxdata/telegraf#8347]
func (ki *KubernetesInventory) gatherPod(p v1.Pod, acc telegraf.Accumulator) error {
	if p.Metadata.CreationTimestamp.GetSeconds() == 0 && p.Metadata.CreationTimestamp.GetNanos() == 0 {
		return nil
	}

	for i, cs := range p.Status.ContainerStatuses {
		c := p.Spec.Containers[i]
		gatherPodContainer(*p.Spec.NodeName, ki, p, *cs, *c, acc)
	}

	return nil
}

**Comment by wuguanyu** [comment]
If I have two container, p.Status.ContainerStatuses(type array) and p.Spec.Containers (type array) doesn't all match

**Comment by ssoroka** [comment]
makes sense
