### ISSUE TITLE
Add persistent state feature to Telegraf plugins (bookmarking)

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8352]
### Proposal:
Add bookmarking/persistent state feature to Telegraf plugins - when Telegraf restarts, it would remember where it left off. Feature would be implemented agent-wide but Telegraf plugins would individually need to opt in. 

### Current behavior:
When Telegraf restarts, it goes back to the beginning to start reading metrics. 

### Desired behavior:
When Telegraf restarts, it would pick up reading metrics from where it left off. 

### Use case: 
Especially important for Logging use case: Customer is currently using [NXLog](https://nxlog.co/) (logging agent) in addition to Telegraf. Would like Telegraf agent to remember its position when it restarts as it does in NXLog so it can use only one agent for all its data ingestion.  
- Customer only needs `inputs.win_eventlog`(#8281) & `inputs.tail` for now

**Comment by sjwang90** [comment]
@ssoroka @DarrenMendalka

**Comment by sjwang90** [comment]
@reimda I added the customer's reasoning for wanting this feature to the "Use Case" section of the issue. What is outlined in this issue of Telegraf remembering its position when it restarts specifically for inputs.win_eventlog and inputs.tail.

**Comment by jhychan** [comment]
Any movement on this feature? Would love to have this, I also use telegraf to ingest logs on windows (win_eventlog and tail as well).

**Comment by srebhan** [comment]
@jhychan can you please open an issue for the `win_eventlog` part so we can work on this? Would you be willing to test the code?

**Comment by jhychan** [comment]
> @jhychan can you please open an issue for the `win_eventlog` part so we can work on this? Would you be willing to test the code?

sorry bit slow to reply - yes willing to help test! I see you've opened an issue for this thanks @srebhan !

**Comment by powersj** [comment]
@jhychan - PR #12790 is up and there are artifacts that you can download from that. Can you please download the artifact for windows, enable it in the config, and give that a try? 

Thanks!
