### ISSUE TITLE
Add FLOAT64-IEEE support to inputs.modbus

### ISSUE THREAD

**Issue by Nemecsek** [influxdata/telegraf#8361]
### Proposal:
Add FLOAT64-IEEE Modbus registers support. 
INT64, UINT64, FLOAT32-IEEE are already available. 
FLOT64-IEEE is used natively at least in some [Janitza devices](https://www.janitza.com/energy-and-power-quality-measurement-products.html) or can be added to some of them through Jasic code. 

### Current behavior:
A 32-bit float has about 7 digits of precision and a 64-bit double has about 16 digits of precision.
Some counter registers are read and a delta is calculated after a period in time. If the counter is big enough, the lack of precision given by a float32 register is enough to lose changes. 

### Desired behavior:
Adding FLOAT64-IEEE support to inputs.modbus solves the problem. 

### Use case: 
In a Janitza UMG604 an Energy counter is read every 15 minutes. Natively UMG604 exposes only float32 Modbus registers while internal calculations are float64. 

When the counter is low (i.e. below 1.000.000) the number of meaningful digits is enough to detect unitary changes in the counter during this interval. As soon as the counter is bigger than maximum precision (about 7 digits), less significant digits are lost and little changes in the counter are no more detected. 
UMG604 can be extended by using Jasic code: I exposed the internal float64 registers adding some new Modbus registers to the standard ones. Alas **inputs.modbus plugin does not support FLOAT64-IEEE registers** to read them back.

For this reason **I implemented for personal use and tested this FLOAT64-IEEE extension in `modbus.go`**
I can commit the change if somebody thinks it is worth. I am not a go developer but the change was very easy using the template provided by the other data formats.

It has been tested on the real devices and verified thoroughly.

**Comment by ssoroka** [comment]
@Nemecsek please do feel free to make a PR with the changes

**Comment by Nemecsek** [comment]
Thank you. 
No way to push it. I never had any problem before.
I have been trying for hours, following a number of tutorials. 
I always get `ERROR: Permission to influxdata/telegraf.git denied to Nemecsek.` 
`fatal: Could not read from remote repository.`

`ssh -vT git@github.com` authenticate me correctly.

I will try again when I am not so pressed by other job related tasks...

**Comment by youcann** [comment]
Also interested (For a Siemens PAC2200)

**Comment by Nemecsek** [comment]
@youcann, sorry but I continuously get a `permission denied` to push the modified `telegraf/plugins/inputs/modbus.go`.
I leave you the file in attachment. I renamed it to `.go.txt` because `.go` files cannot be attached to this comment.

[modbus.go.txt](https://github.com/influxdata/telegraf/files/5589459/modbus.go.txt)

**Comment by youcann** [comment]
Thanks alot!
Regarding your permission error: I'm not sure what exactly you did, bur standard procedure is to open a pull request for the maintainer of the original repo to suggest him to merge your work.

**Comment by Nemecsek** [comment]
@youcann, I cannot push my branch to github, that's the problem. So no PR. 
I tried a number of solutions I found online but at no avail. I forked it and cloned it multiple times to fix this issue, even after reinstalling my Ubuntu machine.

Credentials have been reset:
`git credential reject / git credential fill`

HTTPS URL has been tried with both formats: 
```
remote.origin.url=https://github.com/influxdata/telegraf.git
remote.origin.url=https://nemecsek@github.com/influxdata/telegraf.git
```
It should be straightforward, but actually it isn't. 

I don't want to fill this thread with unrelated stuff. If you can push it using your account and PR, it would be great.

**Comment by soerman** [comment]
Created a PR for this: #8474

**Comment by srebhan** [comment]
@Nemecsek you cannot push to Telegraf directly. You should fork the repository, push your changes there to a branch and then create a pull-request (PR). You can find information [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests). Pull-requests ensure that code gets reviewed to find issues and guaranteeing quality *before* code hits people (at least in theory ;-)).

**Comment by ssoroka** [comment]
merged in https://github.com/influxdata/telegraf/pull/8474
