### ISSUE TITLE
Starlark Processor: Return multiple metrics from plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8371]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 
Return multiple metrics from Starlark processor plugin

### Current behavior:
Currently can only return (create) one metric from the Starlark

### Desired behavior:
- Return multiple metrics.
- Approaches:
  1. Add a new function `add()` to add new metrics in the starlark processor. _Use case: parse an array of json items and add one metric per item in the array_
  2. Return an array or a tuple in the apply function. Currently we return the metric if we want to keep it.  If we want to make multiple metrics from one, more natural to return multiple metrics rather than call an `add()` function

### Use case: 
- Parse an array of json items and add one metric per item in the array

**Comment by srebhan** [comment]
Hey @sjwang90, back when I discussed the starlark processor, @danielnelson was against handling multiple metrics as once (basically enabling aggregation etc.). I don't remember the reasoning.
Do you want multiple in, multiple out or single in multiple out?

**Comment by ssoroka** [comment]
always single in, 0 or more out.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/influxdata/telegraf/pull/8423 that shows how to do it

**Comment by ssoroka** [comment]
fixed in https://github.com/influxdata/telegraf/pull/8423
