### ISSUE TITLE
ECS input uses task.PullStoppedAt as a measurement timestamp for ecs_task

### ISSUE THREAD

**Issue by vmiliantsei** [influxdata/telegraf#8375]
### Relevant telegraf.conf:
```toml
[[inputs.ecs]]
```

### System info:
Telegraf version: 1.15.3

### Expected behavior:
Have constant flow of ecs_task measurements in InfluxDB.

### Actual behavior:
ecs_task measurements are added into InfluxDB only during ECS deployments.

### Additional info:
I believe it's because of this line:
https://github.com/influxdata/telegraf/blob/d369003912e6568aeb43c8d56207e407550afa01/plugins/inputs/ecs/ecs.go#L176

It uses the wrong field as a timestamp:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html
> PullStoppedAt
> The timestamp for when the last container image pull finished.

**Comment by powersj** [comment]
Hi,

Sorry, no one has gotten back to you.

I am not sure I follow what the expected behavior is. Are you thinking the timestamp field should include the time when the measurement is made? And not use the API's `task.PullStoppedAt`?

Thanks!

**Comment by vmiliantsei** [comment]
Hey there Joshua,
Yes, `task.PullStoppedAt` is `The timestamp for when the last container image pull finished`: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html.
It's not the current timestamp. That's why the metrics basically stop once the image is pulled.

**Comment by powersj** [comment]
Ah right since tags aren't changing and timestamp isn't changing users are only ever getting a single data point.

I have put up a [PR with a fix here](https://github.com/influxdata/telegraf/pull/10636). Once tests pass artifacts will get added on to the PR. Would you be able to test out the PR and let us know if you are getting additional data points?

Thanks!

**Comment by vmiliantsei** [comment]
Hey Joshua,
Just tried it out - works as expected.
Thank you for the fix.
