### ISSUE TITLE
[Cloudwatch Output Plugin] Allow user to hide metric name in metric_version = 2

### ISSUE THREAD

**Issue by ssgao** [influxdata/telegraf#8376]
### Proposal:

With `metric_version = 2`, Telegraf inject the name of the input plugin as the metric name: 
https://github.com/influxdata/telegraf/blob/d369003912e6568aeb43c8d56207e407550afa01/plugins/inputs/prometheus/parser.go#L86

This results in full output metric name to be something like `prometheus_my_metric` in Cloudwatch:
https://github.com/influxdata/telegraf/blob/d369003912e6568aeb43c8d56207e407550afa01/plugins/outputs/cloudwatch/cloudwatch.go#L77

User would like to be able to change this behavior by asking (via configuration) cloudwatch output plugin to skip metric name prefixing, so the resulting metric full name would be the same as `metric_version = 1`.

### Current behavior:
Cloudwatch metric name becomes `prometheus_my_metric` with `metric_version = 2`.

### Desired behavior:
Cloudwatch metric name remains `my_metric` (v1 behavior) with `metric_version = 1`.

### Use case: 
We have integration that is based on metric name, having this extra token (prometheus or other input source) breaks the integration.

**Comment by ssgao** [comment]
Some additional details:
I've tried setting an override to be empty string, but it doesn't work due to this logic:
https://github.com/influxdata/telegraf/blob/d369003912e6568aeb43c8d56207e407550afa01/plugins/processors/override/override.go#L36-L38

**Comment by powersj** [comment]
Hi,

The different metrics versions serve very different purposes. In your use-case why would you not continue to use version 1?

Thanks

**Comment by dgtm** [comment]
@powersj Im facing a similar issue with the stasd plugin as an input connected to cloudwatch output plugin

The file output show this output:
```
somekey,metric_type=counter value=100i 1699442415000000000
```

However, the cloudwatch metric name becomes `somekey_value`

I was thinking if we hook onto the size of the fields slice and only do the appending with the suffix if the size of the fields is more than 1 but that will have its caeveats as well
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/cloudwatch/cloudwatch.go#L247
