### ISSUE TITLE
Connection Refused Error, when outputs.Dynatrace plugin run in OneAgent mode.

### ISSUE THREAD

**Issue by PavanVasist** [influxdata/telegraf#8377]
### Relevant telegraf.conf:

```
 [agent]
      collection_jitter = "0s"
      debug = true
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "30s"
      logfile = ""
      metric_batch_size = 10000
      metric_buffer_limit = 20000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
    [[outputs.dynatrace]]
      insecure_skip_verify = true
      prefix = "prefix1."
      url = "<empty>"

    [[outputs.health]]
      service_address = "http://:8888"
      [[outputs.health.compares]]
        field = "buffer_size"
        lt = 5000.0
      [[outputs.health.contains]]
        field = "buffer_size"
    [[inputs.prometheus]]
      urls = [
        "http://istiod.istio-system.svc.cluster.local:15014/metrics",
        "http://prometheus-server.monitoring.svc.cluster.local:80/metrics"
      ]
    [[inputs.postgresql]]
      address = "postgres://<username>:<password>@postgres.postgres.svc.cluster.local:5432/postgresdb"
```

### System info: Using https://github.com/influxdata/telegraf/releases/tag/v1.16.0
 - DT Cluster running with version 1.202.
 - One agent running with 1.201.

### Steps to reproduce:

1. Configure one of the input plugin - prometheus.
2. In the outputs, setup  DT cluster environment with empty URL parameter to enable One Agent mode.
3. Deploy the configuration to a K8s cluster using helm chart
4. The values.yaml file used for deploying, PFB -

```
image:
  repo: "pavanvasisht/telegraf"
  tag: "1.16.1"
  pullPolicy: Always
resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1024Mi
    cpu: 1000m
config:
  agent:
    interval: "30s"
    round_interval: true
    metric_batch_size: 10000
    metric_buffer_limit: 20000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: true
    quiet: false
    logfile: ""
    hostname: "$HOSTNAME"
    omit_hostname: false
  outputs:
    - dynatrace:
        url: "<empty-URL>"
        prefix: "prefix1."
        insecure_skip_verify: true
  inputs:
    - prometheus:
        urls: 
          - "http://istiod.istio-system.svc.cluster.local:15014/metrics" 
          - "http://prometheus-server.monitoring.svc.cluster.local:80/metrics"     
        metric_version: 2
    - postgresql:
        address: "postgres://<username>:<password>@postgres.postgres.svc.cluster.local:5432/postgresdb"
```

### Expected behavior:

The metrics scraped from different input plugins needs to be pushed to DT cluster securely via OneAgent using port 14499.

### Actual behavior:

While trying to push it to the endpoint - `http://127.0.0.1:14499/metrics/ingest` we get the below error -
```
2020-10-28T08:38:30Z E! [agent] Error writing to outputs.dynatrace: Dynatrace error while sending HTTP request:, Post "http://127.0.0.1:14499/metrics/ingest": dial tcp 127.0.0.1:14499: connect: connection refused
```

### Additional info:

- As part of Early Adopter, have enabled Extension Execution Controller (EEC) so that OneAgent can push metrics through a secure channel to DT environment.
- OneAgent is running as Daemon set within K8s cluster.
- Cross-verified by trying to push a metric via OneAgent pod within same node where the telegraf pod has been deployed. The port 14499 is open and metrics are being pushed via OneAgent pod. When Telegraf tries to push, error is thrown.

@thschue @wolfgangB33r Can you please help me as to what configurations am i missing.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you before.

The error message you provided seems to indicate that Telegraf is not able to connect to the given service:

```
connect: connection refused
```

This generally means that the server has refused our connection attempt. This would be a setting on the service itself or whatever is hosting the service and not something in Telegraf itself.

Given I do not believe this to be a bug in Telegraf I am going to close this. However, if you think otherwise, please do try again on the latest version and provide some logs when trying to connect.

Thanks!
