### ISSUE TITLE
Add ignore_missing option to conntrack plugin

### ISSUE THREAD

**Issue by danielmotaleite** [influxdata/telegraf#8378]
## Feature Request
Add a ignore_missing option to the conntrack plugin, to disable the message " Conntrack input failed to collect metrics. Is the conntrack kernel module loaded?"

### Proposal:
Trying to log the conntrack in all telegraf will generate a never ending error message in the log 
As the module may later be loaded (desired or by accident), simply removing the plugin is not a good option, but having all hosts logging this every scrape interval may generate many useless messages and slowly eat the SSD writes limits and fill up any central logging service with useless data

Instead of disable, we could also configure how many errors to return in X time, but that sounds more complex, where disable the log is just one more plugin option and one if in the code.

### Current behavior:
system outputs every 10s this error:
2020-11-09T13:07:10Z E! [inputs.conntrack] Error in plugin: Conntrack input failed to collect metrics. Is the conntrack kernel module loaded?

### Desired behavior:
no log if the user decides that if is useless

### Use case:
While not critical, this is a very simple option that may help all SSD systems and reduce useless messages that may hide other more important messages.
This plugin is kind of special, as the conntrack module can be loaded in the future and it is a important metric to check as it may affect server network availability

**Comment by powersj** [comment]
Hi,

Sorry, no one has not gotten back to you in the past.

After talking about this with the team, we are not inclined to make this change. Currently in Telegraf if a plugin cannot be started it should prevent Telegraf from starting in the first place. However, it seems the current behavior with conntrack is there is no pre-check to ensure the module is loaded like there should be. Even behind an option, we also do not want to prevent the legitament error message from printing out as it can and will cause confusion with newer users.

Thanks

**Comment by danielmotaleite** [comment]
@powersj notice that i do not want to totally suppress the error message, it is useful... but on servers without conntrack locked, it keeps logging the same message day after day
what i'm requesting is maybe a way to limit this error, either exponential backoff or simply disable it via a special option (say conntrack_missing=once). This option would need to be directly set, so not confusion to new users, more like a  "shut up" for already existent setups... warns the first time and them silence the alert... if you prefer, warn only every hour... 24 warnings per node is much better than thousands of alerts per node

this way we can have this enabled in every node, if conntack is ever loaded, it will start to output metrics, but if not loaded, no need to keep output the same error every few minutes on every node

So please reconsider this
