### ISSUE TITLE
What type of telegraf errors are collected with internal plugin "intenal_gather.errors" metrics? 

### ISSUE THREAD

**Issue by sunghyebae** [influxdata/telegraf#8380]
Hello. 

I am setting dashboard for telegraf agent itself via using internal input plugin. 
When I block outbound of my host (telegraf installed), telegraf can not send data to influx db(influxdb is installed on the another host). 
I expected to receive the error count on the Dashboard, but the data did not come in. (No DATA). 
So I have a question about intenal_gather.errors metric.
 
What type of errors are counted with internal_gahter.errors?

Let me know and have aㅜ efficient dashboard for telegraf agent. 
Thanks.

**Comment by sjwang90** [comment]
This is the data that comes from the `internal_agent` measurement. With `gather_errors=0i` noting that there are no gather errors
`> internal_agent,go_version=1.15.3,host=MBP15-SWANG.local,version=1.16.0 gather_errors=0i,metrics_dropped=0i,metrics_gathered=1i,metrics_written=0i 1605026482000000000`

Please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and I can help you if your question is still not resolved as it'll be much faster. If you reach out to me on the Community Slack I can also help you get set up with our Telegraf InfluxDB Template that should help you easily set up a dashboard monitoring [internal Telegraf metrics](https://www.influxdata.com/influxdb-templates/telegraf-monitor/).

**Comment by sunghyebae** [comment]
Thanks for your answer. 

I understood the gather_errors is "0" when there is no gather errors. 
And then, When the gather_errors has number? How can I check it from the telegraf log file?
Simply, it counts the "E!" logs?
What errors are collected by gather_errors?

**Comment by sjwang90** [comment]
`gather_error` counts the gather errors in all the input plugins that telegraf is running. If you set `debug = true` in your agent you will be able to log at the debug level.

**Comment by sunghyebae** [comment]
Thanks!!
