### ISSUE TITLE
After field converted to tag, no result on the queries

### ISSUE THREAD

**Issue by stefi994** [influxdata/telegraf#8384]
Hey, I am using Telegraf with Telemetry, I want to see traffic level on interface based on their description, "/interfaces/interface/subinterfaces/subinterface/state/description". Unfortunately the interface description was as field key, which I converted using the processors.converter. Since I needed to rewrite the data after this, I just dropped the whole measurement so the new tag can take place.

I do see the descriptions as tag fields and I do see the interface description as a tag key.

Unfortunately I am still getting blank results on any query when I try with querying by interface description. 

### Relevant telegraf.conf:
 # Convert values to another metric value type
[[processors.converter]]
# Fields to convert
[processors.converter.fields]
tag = ["/interfaces/interface/subinterfaces/subinterface/state/description"]

### System info:

Telegraf 1.14.5
Debian

### Steps to reproduce:

> select "/interfaces/interface/subinterfaces/subinterface/state/description" from "/interfaces/"
(empty result) this is expected since now its a tag

> show tag keys
name: /interfaces/
tagKey
------
/interfaces/interface/subinterfaces/subinterface/state/description

> show tag values with key = "/interfaces/interface/subinterfaces/subinterface/state/description"
(gives all descriptions)

> SELECT "/interfaces/interface/subinterfaces/subinterface/state/counters/out-pkts" from /interfaces/ where "/interfaces/interface/subinterfaces/subinterface/state/description" = 'some_description'
(empty result)

### Expected behavior:

SELECT "/interfaces/interface/subinterfaces/subinterface/state/counters/out-pkts" from /interfaces/ where "/interfaces/interface/subinterfaces/subinterface/state/description" = 'some_description'

to give some a result for the interface with that description

### Actual behavior:
SELECT "/interfaces/interface/subinterfaces/subinterface/state/counters/out-pkts" from /interfaces/ where "/interfaces/interface/subinterfaces/subinterface/state/description" = 'some_description'
(is not returning any result)

### Additional information
I am also using Chronograph which gives no results too.

**Comment by sjwang90** [comment]
@stefi994 can you share your Telegraf config?

**Comment by stefi994** [comment]
[relevant config.txt](https://github.com/influxdata/telegraf/files/5523455/relevant.config.txt)

Here are the parts that are active in the config.

**Comment by sjwang90** [comment]
Can you provide a sample output without the processor? Do you think you could actually reach out to me on our [Community Slack](influxdata.com/slack). It's easier to help with questions that way.
