### ISSUE TITLE
RPM packaging includes telegraf.conf

### ISSUE THREAD

**Issue by LloydW93** [influxdata/telegraf#8386]
### Relevant telegraf.conf:

N/A

### System info:
Telegraf 1.160, CentOS Linux release 7.8.2003 (Core).>

### Steps to reproduce:

```
$ wget https://dl.influxdata.com/telegraf/releases/telegraf-1.16.0-1.x86_64.rpm
2020-11-10 17:02:13 (3.56 MB/s) - 'telegraf-1.16.0-1.x86_64.rpm' saved [21550117/21550117]
$ rpm -qlp telegraf-1.16.0-1.x86_64.rpm
/etc/logrotate.d/telegraf
/etc/telegraf/telegraf.conf
/etc/telegraf/telegraf.d
/usr/bin/telegraf
/usr/lib/.build-id
/usr/lib/.build-id/fc
/usr/lib/.build-id/fc/dfa2ee4b2948df5375847ecb2ff3163fa3ac09
/usr/lib/telegraf/scripts/init.sh
/usr/lib/telegraf/scripts/telegraf.service
/var/log/telegraf
```

### Expected behavior:

As per #7250, `/etc/telegraf/telegraf.conf.sample` should be provided.

### Actual behavior:

`/etc/telegraf/telegraf.conf` is provided.

### Additional info:

I can't obviously from a quick look see how this is happening (but I also haven't found a spec file or similar yet). The specific issue I'm encountering is #5887, where I currently in a service that adds content to `/etc/telegraf/conf.d/` also need to run `sudo sed -i "s/^\[\[outputs.influxdb\]\]/# [[outputs.influxdb]]/" /etc/telegraf/telegraf.conf` in order to remove the unwanted default InfluxDB output so I can add a correctly configured InfluxDB output in conf.d.

**Comment by DavidBuettner** [comment]
Hi
we have the same problem in automated builds where we want to configure the outputs via config files in `/etc/telegraf/telegraf.d/`. The "sed" step described above is unnecessary and an empty (not configured) [[outputs.influxdb]] section doesn't really help. 

It would be great if you could comment out that line, then it is still there as reference/example for users, but not in the way for automation...

**Comment by powersj** [comment]
The empty influxdb output was removed, closing this.
