### ISSUE TITLE
tail multi line panic

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#8390]
Maybe I'm doing something wrong, but I'd hope not to get a panic.  Maybe too complex or negative lookahead ?  With config file:

  [inputs.tail.multiline]
   pattern = '^((?!^\d{4}).)*$'

caused below panic.  

2020-11-11T11:50:08Z I! Starting Telegraf 1.16.1
panic: assignment to entry in nil map

goroutine 86 [running]:
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles(0xc00063e0f0, 0x34fff01, 0x1, 0xc001a47700)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:278 +0x6b5
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).Gather(0xc00063e0f0, 0x3dbb560, 0xc001a47700, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:160 +0x37
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc000091570, 0xc0000067d8, 0xc0013862a0, 0xc000e49c40, 0xc00007a0a0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:424 +0x237
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs
        /go/src/github.com/influxdata/telegraf/agent/agent.go:393 +0x112

**Comment by ssoroka** [comment]
I agree you shouldn't be able to make it panic with odd configuration. Can you run it with `--debug` and include the full output?

v1.16.1 doesn't panic for me with this configuration, instead, I get: 

```
2020-11-12T18:57:15Z E! [telegraf] Error running agent: starting input inputs.tail: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

**Comment by SimonMcN** [comment]
PS C:\Windows\system32> c:\telegraf\telegraf.exe --config c:\telegraf\Config\ENV_NonProd.conf --config-directory c:\telegraf\conf.d --service-name telegraf --once --debug
2020-11-13T15:41:50Z I! Starting Telegraf 1.16.1
panic: assignment to entry in nil map

goroutine 96 [running]:
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles(0xc0002b2e10, 0x37eff01, 0x2d305b28287c2901, 0xc000f44fe0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:278 +0x6b5
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).Gather(0xc0002b2e10, 0x40ab560, 0xc000f44fe0, 0x462d41392d305b3a, 0x342c317b5d662d61)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:160 +0x37
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc0004c4ab0, 0xc0000061b0, 0xc0014a6a80, 0xc000f02820, 0xc0004d71d0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:424 +0x237
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs
        /go/src/github.com/influxdata/telegraf/agent/agent.go:393 +0x112
PS C:\Windows\system32>

**Comment by SimonMcN** [comment]
Literally, if I just change the pattern it doesn't occur so it's definitely that.  Maybe a windoze thing ?

**Comment by SimonMcN** [comment]
This doesn't error, but in theory it shouldn't work ?

     pattern = '^?!\d{4}.*$'

**Comment by powersj** [comment]
Looks like this crash was fixed. I tried on Win 11 with 1.25 and the following config:

```
[[outputs.file]]

[[inputs.tail]]
  files = ["myfile.csv"]
  from_beginning = true
  watch_method = "poll"
  [inputs.tail.multiline]
    pattern = '^?!\d{4}.*$'
```
