### ISSUE TITLE
inputs.procstat  get the wrong running process num

### ISSUE THREAD

**Issue by mlbzssk** [influxdata/telegraf#8394]
telegraf versision:
Telegraf 1.10.4 (git: HEAD 3548ce47)

this is my config:
`[[inputs.procstat]]
  pattern = "org.apache.hadoop.hbase.regionserver.HRegionServer"
  pid_tag = true
  user="hbase"
  pid_finder = "native"

[[inputs.procstat]]
  pattern = "org.apache.hadoop.hdfs.server.datanode.DataNode"
  pid_tag = true

[[inputs.procstat]]
  pattern = "org.apache.zookeeper.server.quorum.QuorumPeerMain"
  pid_tag = true

[[inputs.procstat]]
  pattern = "org.apache.hadoop.hbase.master.HMaster"
  pid_tag = true

[[inputs.procstat]]
  pattern = "org.apache.hadoop.hdfs.server.namenode.NameNode"
  pid_tag = true

[[inputs.procstat]]
  pattern = "org.apache.hadoop.hdfs.tools.DFSZKFailoverController"
  pid_tag = true`

And when my machine has no progress whick pattern is "org.apache.hadoop.hbase.regionserver.HRegionServer", I get a 
result of running=1i.
![image](https://user-images.githubusercontent.com/31941943/98915655-2625ae80-2505-11eb-8766-172b65dbb6df.png)

![image](https://user-images.githubusercontent.com/31941943/98915768-4f463f00-2505-11eb-8567-5848c91b36e1.png)

I am so confused, Can someone be so kind to help me. Thanks!

**Comment by mlbzssk** [comment]
Can someone help me？

**Comment by Aigoss** [comment]
Is this problem solved? I have the same situation at telegraf-1.23.2

**Comment by powersj** [comment]
> And when my machine has no progress whick pattern is "org.apache.hadoop.hbase.regionserver.HRegionServer", I get a
result of running=1i.

What was the expected value? GIven the `ps` output I see 1 process, so would expect 1 as well.

> Is this problem solved? I have the same situation at telegraf-1.23.2

Not sure I see what the issue is based on the original report.

**Comment by Aigoss** [comment]
> > And when my machine has no progress whick pattern is "org.apache.hadoop.hbase.regionserver.HRegionServer", I get a
> > result of running=1i.
> 
> What was the expected value? GIven the `ps` output I see 1 process, so would expect 1 as well.
> 
![image](https://user-images.githubusercontent.com/108331985/184565931-cfc44031-667f-4cf5-a3df-ed65224c3e60.png)
This is the result of grep，HRegionServer is not running，The correct result should be running=0i


> > Is this problem solved? I have the same situation at telegraf-1.23.2
> 
> Not sure I see what the issue is based on the original report.
configuration file：
![image](https://user-images.githubusercontent.com/108331985/184567246-9de33e3b-01db-4ee5-be0c-672820bec718.png)

Result after running pgrep:“api”  is not running
![image](https://user-images.githubusercontent.com/108331985/184567478-198d38b5-d591-48a1-aabc-a8920026e150.png)


the result of telegraf --test :
![image](https://user-images.githubusercontent.com/108331985/184567663-bee9c82f-e0b3-4d06-bcec-efb545e59710.png)
![image](https://user-images.githubusercontent.com/108331985/184567671-a979cc39-fd25-4f45-b1c3-9486fe75f8af.png)

why pattern=api , procstat_lookup         =>    result=success,result_code=0i,running=0i  ?? 

@powersj

**Comment by powersj** [comment]
> why pattern=api , procstat_lookup => result=success,result_code=0i,running=0i ??

Your own pgrep command returned 0. What were you expecting?

**Comment by Aigoss** [comment]
> > why pattern=api , procstat_lookup => result=success,result_code=0i,running=0i ??
> 
> Your own pgrep command returned 0. What were you expecting?

“api” is not running，I thought result=fail,result_code=1i,running=0i...

It seems that this result expresses only the working state of the inputs.procstat, not the state of the process

**Comment by powersj** [comment]
> It seems that this result expresses only the working state of the inputs.procstat, not the state of the process

That is correct. This returns the result of pgrep, not the process. If you were monitoring this process, you would alert on the running field being 0.
