### ISSUE TITLE
support logging in starlark

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#8402]
I was thinking there should be some logging primitives, too, to tie into the Telegraf logger. something like log.info, log.warn, log.error, and log.debug, so you can customize what to log around error conditions.

**Comment by essobedo** [comment]
@ssoroka I could not figure out a better way to do it, so here a potential fix for it https://github.com/influxdata/telegraf/pull/8408 hoping that it was what you had in mind

**Comment by ssoroka** [comment]
resolved in https://github.com/influxdata/telegraf/pull/8408
