### ISSUE TITLE
support returning a custom error in starlark

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#8403]
the custom error should get logged. It'd also be great if the starlark processor had a configurable option to say whether the original metric should be dropped if the processor errors.

**Comment by essobedo** [comment]
@ssoroka I can check this one if you want. If so, could you clarify a little bit about what you expect exactly? I'm mean we can already create a custom error with the built-in function `fail(message)` unless I misunderstand what you want to do?

**Comment by essobedo** [comment]
The corresponding PR https://github.com/influxdata/telegraf/pull/8439

**Comment by essobedo** [comment]
@ssoroka I guess you can close this one since the PR has been merged

**Comment by sjwang90** [comment]
Closed #8439
