### ISSUE TITLE
[inputs.ping] Previous collection has not completed; scheduled collection skipped

### ISSUE THREAD

**Issue by dvk1302dvk** [influxdata/telegraf#8409]
Hello.
I cant resolve this issue.
Reload config, restart telegraf service, stop and start : don't helped
Before I had next error:
[inputs.ping] Collection took longer than expected; not complete after interval of 3s
My system Debian 10 x64.

[[inputs.ping]]
interval = "60s"
urls = ["8.8.8.8"]
count = 3
ping_interval = 1.0
timeout = 10.0
deadline = 30

**Comment by ssoroka** [comment]
try setting `method = "native"`
