### ISSUE TITLE
[inputs.disk] not working on RPI4 w/Raspbian

### ISSUE THREAD

**Issue by jacob-swanson** [influxdata/telegraf#8410]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
    urls = ["http://192.168.1.2:8086"]
# other inputs omitted
[[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
```

### System info:

Telegraf running on a Raspberry Pi 4 with Raspbian in Docker via docker-compose.

### Docker

```yaml
version: "3.6"
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /run/udev:/run/udev:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/proc
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
```

### Steps to reproduce:

1. Start Telegraf
2. Observe error in log

### Expected behavior:

Disk input is works.

### Actual behavior:

Error is logged and disk metrics are not collected.

### Additional info:

Log:
```
2020-11-15T16:28:28Z I! Starting Telegraf 1.16.2
2020-11-15T16:28:28Z I! Using config file: /etc/telegraf/telegraf.conf
2020-11-15T16:28:28Z I! Loaded inputs: cpu disk diskio docker mem net processes swap system
2020-11-15T16:28:28Z I! Loaded aggregators: 
2020-11-15T16:28:28Z I! Loaded processors: 
2020-11-15T16:28:28Z I! Loaded outputs: influxdb
2020-11-15T16:28:28Z I! Tags enabled: host=pi3
2020-11-15T16:28:28Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"pi3", Flush Interval:10s
2020-11-15T16:28:30Z E! [inputs.disk] Error in plugin: error getting disk usage info: readlink /hostfs/proc/dev/block/179:2: no such file or directory
```
The `/proc/dev` directory doesn't exist.
`/dev/block/179:2` does exist.

**Comment by SimonMcN** [comment]
Did you go through the troubleshooting steps ??

Troubleshooting
On Linux, the list of disks is taken from the /proc/self/mounts file and a statfs call is made on the second column. If any expected filesystems are missing ensure that the telegraf user can read these files:

$ sudo -u telegraf cat /proc/self/mounts | grep sda2
/dev/sda2 /home ext4 rw,relatime,data=ordered 0 0
$ sudo -u telegraf stat /home
It may be desired to use POSIX ACLs to provide additional access:

sudo setfacl -R -m u:telegraf:X /var/lib/docker/volumes/

**Comment by SimonMcN** [comment]
might also be worth sharing the result of the mount command too

**Comment by reimda** [comment]
Double check your docker-compose config.  I think HOST_SYS is misconfigured

```
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/proc

```
Shouldn't it be
```
      - HOST_SYS=/hostfs/sys
```

**Comment by reimda** [comment]
HOST_SYS pointing to the proc dir explains the error you're getting so I'm closing the issue.  Feel free to reopen if correcting it doesn't fix the problem.

**Comment by jacob-swanson** [comment]
Thanks, @reimda. It's working. Seems so obvious now.
