### ISSUE TITLE
collector-local timestamps for gnmi plugin

### ISSUE THREAD

**Issue by rski** [influxdata/telegraf#8411]
### Proposal:

Timestamp gnmi updates using the collector's local time instead of using the timestamp field of the notification.

### Current behavior:

Updates received over gnmi are always timestamped using the Timestamp field which comes fro mthe device.
### Desired behavior:

Make it possible to use the collector's time when the update was received to timestamp updates.

### Use case: 

Depending on the device that sends gnmi updates, the timestamp semantics can be different. According to the spec, the process that streams gnmi notifications should use the time the modification happened, not the time it was seen by the process. For example, when the hardware counters change, the time when those counters changed is to be used.

 This differs between implementations. Some devices stream a fresh timestamp every time they send an update to a client that is subscribed to a counter path, some use a fixed timestamp of the time the value came to be.

This results in two kinds of collected datum; One is a time series, where each timestamp from the update means counter was X at time T, with multiple values of T even if X did not change. In this case, you can find the current value by looking at the last update for the path which is at most the sample frequency. Looking at a window of  T to T+(sample frequency) shows all the information about a device.
 In the other, the timestamps could be at any point in the past, since they are the time at which a value was established. Looking at a window of T to T+(sample frequence) shows only the values that changed within that window.

Certain orgs prefer the first, spec breaking behaviour. This can be implemented on the collector in a device agnostic way by ignoring the timestamp provided by the device and recording the time an update was received.

I already have the code for this change, it's pretty simple to make it possible and configurable, but I thought I'd open an issue first to gauge the interest on this.

**Comment by ssoroka** [comment]
I think we're fine with this change as long as it's a configuration option that needs to be enabled to take effect. If you'd like to open a PR we'd be happy to take a look at it

**Comment by flyerhawk** [comment]
Was this implemented?   Is there documentation?   Sorry if this is a dumb question but I'm a Github noob networking engineer.

**Comment by ksator** [comment]
@flyerhawk there is this pending pull request https://github.com/influxdata/telegraf/pull/8420

**Comment by sjwang90** [comment]
Hello! We found that having your timestamps set locally would be very useful across a lot of Telegraf plugins, not just gnmi. Instead of building this enhancement for gnmi specifically we created an issue to create a global tag setting to set your local timestamp #8689.

We'd welcome any PRs for #8689. 

If you are looking to use this immediately for gnmi, please use the list of builds from @rski's PR https://github.com/influxdata/telegraf/pull/8420#issuecomment-759650256. Otherwise the global tag feature will be on our roadmap to add soon.

**Comment by sjwang90** [comment]
The solution for this will be to utilize the [Starlark processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark). There is this [example script](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/time_set_timestamp.star) that can be added to use the current/local timestamp over the field device's timestamp.

**Comment by rski** [comment]
wow that's pretty awesome
