### ISSUE TITLE
Google Cloud Storage Input Plugin

### ISSUE THREAD

**Issue by gkatzioura** [influxdata/telegraf#8412]
## Feature Request

Google Cloud Storage (GCS) is a RESTful online file storage web service. Similar like the file Plugin the proposal is to use the Cloud Storage as an Input.

### Proposal:

Google Cloud Storage has the ability to list the files in lexicographic order. This helps alot when logs files are stored with a date prefix, or their lexicographic order is based on the time the files were created . Also batching is encouraged since you can list the files on GCS by specifying an offset. By manipulating the offset and the lexicographic order listing of the Items on GCS it is possible to create a crawler that list the files on GCS in order parse them and submit them to an output. After every Gather execution the last file processed will be stored on GCS as an offset. The next Gather command will continue from that offset.

### Desired behavior:

* Entries on GCS are stored with a name that represents the time they got created ie. 1604148850991 or 2020-01-10T05:45:01
* Telegraf input plugin is configured to crawl data on a GCS bucket with a specified prefix.
* Input plugin can use an offset to list the data after that offset
* On every Gather() execution the Input plugin will save the last file it processed on GCS. The purpose is to use this file in order to retrieve the offset and to use it for the next iteration
* The files on GCS should contain measurements so that telegraph can parse them
* Due to a page of items fetched from GCS can be bigger than what Telegraph can process in one Gather() action user can specify a limit of files processed

### Use case: 

Google Cloud Storage provides at least 99.99% availability. One of its usages os to store log files that might have been generated by various servers. Also It is a solution that multiple client can read the data and populate various datasources.

**Comment by powersj** [comment]
next steps: wait for PR to be updated and review

**Comment by sjwang90** [comment]
closed in #8413
