### ISSUE TITLE
SNMP agent cannot accept link-local IPv6 addresses for agent

### ISSUE THREAD

**Issue by falconkirtaran** [influxdata/telegraf#8415]
### Relevant telegraf.conf:

```toml
[[inputs.snmp]]
  agents = ["[fe80::1234:56ff:fe78:9abc%eth0]:161"]
  version = 3
  sec_name = "xxxx"
  auth_protocol = "SHA"
  auth_password = "xxxx"
  sec_level = "authPriv"
  priv_protocol = "AES"
  priv_password = "xxxx"

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"
```

### System info:

Ubuntu 20.10, telegraf version 1.15.2+ds1-0ubuntu1

### Steps to reproduce:

```
# telegraf --test --config /etc/telegraf/telegraf.d/snmp.conf
2020-11-16T01:43:00Z I! Starting Telegraf 1.15.2+ds1-0ubuntu1
2020-11-16T01:43:01Z E! [inputs.snmp] Error in plugin: agent [fe80::1234:56ff:fe78:9abc%eth0]:161: performing get on field uptime: Error reading from socket: read udp 127.0.0.1:51499->:0: read: connection refused
2020-11-16T01:43:01Z E! [inputs.snmp] Error in plugin: agent [fe80::1234:56ff:fe78:9abc%eth0]:161: gathering table interface: performing bulk walk for field ifName: Error reading from socket: read udp 127.0.0.1:55832->:0: read: connection refused
2020-11-16T01:43:01Z E! [telegraf] Error running agent: input plugins recorded 2 errors
```

### Expected behavior:

Telegraf should connect to `[fe80::1234:56ff:fe78:9abc%eth0]:161`.

This is the normal way to specify an IPv6 address - without the %eth0 scope, the address is ambiguous because the same subnet exists on all interfaces, so the system will not connect to it without.  For example, if we set up a /etc/hosts entry "router" with the address `fe80::1234:56ff:fe78:9abc`, and try to connect to it, we will get `error establishing connection to host: dial udp [fe80::1234:56ff:fe78:9abc]:161: connect: invalid argument`.  But we cannot add the scope in /etc/hosts on Linux.

The format of scoped addresses is specified at https://tools.ietf.org/html/rfc4007#section-11.1.

### Actual behavior:

It tries to connect to 0 with an IPv4 socket, and fails:

```
E! [inputs.snmp] Error in plugin: agent [fe80::1234:56ff:fe78:9abc%eth0]:161: performing get on field uptime: Error reading from socket: read udp 127.0.0.1:51499->:0: read: connection refused
```

So probably it is not parsing the address as an address.

**Comment by MyaLongmire** [comment]
I am going to close this as `snmptraslate` is deprecated in telegraf and supported versions no longer use it due to performance issues. If you are having issues with recent `snmp` update, please open another ticket with all relevant information.
