### ISSUE TITLE
would like -config-directory to operate like -config http://endpoint

### ISSUE THREAD

**Issue by minjaeapa** [influxdata/telegraf#8416]
## Feature Request

I like the fact that you can centrally store and load config files with the -config http://endpoint syntax.  It would be nice to be able to use the same syntax to read multiple config files from a web directory with -config-directory http://endpoint/d/.  Im not expecting this to be a part of the Influxdb 2 API, as I can see the complications with providing keys to access those individual configs in a directory.  The main reason for requesting this is when you have ping scripts, or snmp queries telegraf configs.  its easier to maintain many targets with the individual files, and be able to "disable" them by commenting out the individual files and reloading that process.  

### Proposal:
allow -config-directory http://endpoint/directory/ or -config-directory scp://endpoint/directory/ or -config-directory sftp://endpoint/directory/

### Current behavior:
 /usr/bin/telegraf -version
Telegraf 1.16.2 (git: release-1.16 962082f6)

created apache instance, and made a directory listable
verified access to directory list and individual files in directory via wget (not shown here)

main telegraf.conf file is located at http://localhost:8099/telegraf/telegraf01/telegraf.conf.
additional config file is located at -config-directory http://localhost:8099/telegraf/telegraf01/d/

running /usr/bin/telegraf -config http://localhost:8099/telegraf/telegraf01/telegraf.conf -config-directory http://localhost:8099/telegraf/telegraf01/d/ 
gets
2020-11-16T14:11:47Z I! Starting Telegraf 1.16.2
2020-11-16T14:11:47Z W! Telegraf is not permitted to read http://localhost:8099/telegraf/telegraf01/d/
2020-11-16T14:11:47Z I! Loaded inputs: cpu disk diskio kernel mem net processes swap system

this only loads the inputs from the main telegraf.conf file

running
/usr/bin/telegraf -config http://localhost:8099/telegraf/telegraf01/telegraf.conf -config-directory /etc/telegraf/telegraf.d
gets the additional ping config file
2020-11-16T14:30:45Z I! Starting Telegraf 1.16.2
2020-11-16T14:30:45Z I! Loaded inputs: cpu disk diskio kernel mem net ping processes swap system

### Desired behavior:
to use -config-directory from a centralized location

### Use case: 
keep configs centralized still, with potential use of content versioning systems.  Keep configs modular rather than monolithic

**Comment by ssoroka** [comment]
I don't think what you're asking is possible. --config-directory _watches the filesystem_ for new files and collects them all. This is not possible over HTTP. 
Instead do you want the ability to load multiple configs from URLs?

**Comment by minjaeapa** [comment]
Im thinking it would be unruly unless you were able to pass a file that contained the list of URLS... but that would probably be useful

**Comment by vincent-gou** [comment]
I don't know if this solution may be applicable in your setup but dynamic telegraf.conf may do the job.

I've successfully used node-red setup with telegraf like explained here: [Influxdata Blog Post](https://www.influxdata.com/blog/continuous-deployment-of-telegraf-configurations/) to maintain different telegraf configs for my clients.

For example i use these kind of url to pass parameters and generate telegraf.conf by client or config type:
/usr/bin/telegraf -config "https://xxxx.yyyyyy.com/telegraf?client=565f6cb2-54da-436e-97ae-43057aaaaaaa&application=app1&os=linux&host=host-111&editor=name&app_component=nginx"

**Comment by minjaeapa** [comment]
I did look at your blog post actually, and I do have a lot of similar design requirements that you laid out in your post, and i found the node-red system compelling, but, since Influxdb2 is now official, and there looked like there was some direction to create telegraf configs via an API, and launch telegraf via a web request, this feature request was also an attempt to gain more insight into the direction the both were going.  No insult to you or your solution, but if there was an intermediate step that can be taken, I was looking for it, rather than taking on another learning curve

**Comment by powersj** [comment]
Hi,

As stated above, this is not something interested in doing. Instead, the user would need to use multiple `--config` options.

Thanks
