### ISSUE TITLE
Redfish plugin error parsing input: json:

### ISSUE THREAD

**Issue by phil-or** [influxdata/telegraf#8418]
### System info:

Telegraf Version 1.16.2
OS: CentOS7
Management Type: CIMC4.0(2g)

### Steps to reproduce:

Use the Redfish Input-Plugin with CIMC4.0

### Expected behavior:

Parse correct results

### Actual behavior:

Today I discovered the Redfish-Plugin. Great that there is such a plugin to write thermal and power metrics to influx and visualize them with Grafana.
I tested it out with HP ILO5 servers and the plugin works.
Then I tried it on a Cisco CIMC 4.0 server and got errors:

`I! Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>`
`E! [inputs.redfish] Error in plugin: error parsing input: json: cannot unmarshal string into Go struct field .Links.Chassis of type struct { Ref string "json:\"@odata.id\"" }`

**Comment by sjwang90** [comment]
@phil-or Can you please provide a sample of a config and possibly a sample of the Redfish JSON metrics you're reading?

**Comment by phil-or** [comment]
Sure, my config is very simple and it works on a CentOS7 server with ILO 5, but it doesn't work on a CentOS7 with CIMC 4.x
```[[inputs.redfish]]
  interval = "60s"
  address = "https://127.0.0.1"
  username = "user"
  password = "password"
  computer_system_id="1"
  insecure_skip_verify = true
```
I would like to read the basic metrics like temperatures, fan-speed and power consumption, but I know it's difficult to read out all fields with one tool because every Management Type (ILO4|ILO5|CIMC3|CIMC4|...) has a slightly different JSON-structure.

At the moment I use my own script to read out the perfdata from https://127.0.0.1/redfish/v1/Chassis/1/Thermal & https://127.0.0.1/redfish/v1/Chassis/1/Power, but maybe the redfish-plugin could replace that.

**Comment by sjwang90** [comment]
@sarvanikonda would have any feedback on why it works on a CentOS7 server with ILO 5, but it doesn't work on a CentOS7 with CIMC 4.x?

**Comment by sarvanikonda** [comment]
@sjwang90 I have used the standard DMTF redfish JSON structures for the redfish API calls, the reason why the plugin does not work with CIMC 4.x might be because it has the different JSON structure than standard DMTF redfish.

**Comment by powersj** [comment]
Hi,

Sorry, no one has commented on this in a while.

It does seem that there are [reports](https://github.com/bb-Ricardo/check_redfish/issues/12) of the Cisco CIMC server not having standard redfish responses. From the sound of that other link, it is due to the power supplies not reporting health status.

I realize this is up to the mfg, but I don't think we want to start going through and special casing various models. I'm going to close as not planned.
