### ISSUE TITLE
Retention policy per input

### ISSUE THREAD

**Issue by smalenfant** [influxdata/telegraf#842]
I have some specific "exec" input which I run hourly. I'd like to have those put in my "monthly" RP instead of my default "daily" RP.

How would I acheive this? Using multiple output to same database with tag/name pass/drop?

**Comment by sparrc** [comment]
yep, as you described

**Comment by s1m0** [comment]
I couldn't get it to recognize the retention_policy setting and the InfluxDB output doesn't honor the precision setting (see #809 and #761).

**Comment by sparrc** [comment]
Retention policy will be available in 0.11, released next week

**Comment by munnathampi** [comment]
@s1m0  hi simon can you share your telegraf.conf  [[output.influxdb]] and the telegraf.d conf [[inputs.exec]] section. i have the same requirement.
i am getting error while trying to write to multiple databases in infulxdb.
