### ISSUE TITLE
inputs.kafka_consumer plugin not receiving any data

### ISSUE THREAD

**Issue by jutkarsh079** [influxdata/telegraf#8421]
Telegraf service is up and running without any errors but I can not see any data being consumed by telegraf from kafka.

**Telegraf config file:**

 `   

     [[outputs.influxdb]]
      database = "snbb_network_kafka"
      urls = [ "http://192.168.100.102:8086","http://192.168.101.103:8086" ]

     [[inputs.kafka_consumer]]
       brokers = ["192.168.101.100:9092","192.168.100.100:9092"]
       topics = ["tp_snbb_network"]
       max_message_len = 1000000
       offset = "oldest"
       balance_strategy = "roundrobin"
       data_format = "influx"
  `

**System info:**
Telegraf = 1.15.3

Telegraf service is up and running.

  `
      
      [ansible-rw@sn-sintp1-a28t1 telegraf.d]$ sudo -u telegraf telegraf -test -config read_snbb_etwork.conf

      2020-11-17T15:32:54Z I! Starting Telegraf 1.15.3
  `

**Comment by CarlosEssun** [comment]
i have same issue
