### ISSUE TITLE
certificates on the Windows server

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#8422]
I want to monitor certificates on the Windows server

I can see "https://github.com/influxdata/telegraf/tree/master/plugins/inputs/x509_cert" but how can I do it on Windows server

**Comment by SimonMcN** [comment]
You would have to do this by extracting the certs from the windows cert store to the file system, then reading them.  It doesn't look like the plugin supports reading them from the registry, which is where some certs are located.  This plug in will tell you details:
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores

They can be exported using certutil
