### ISSUE TITLE
Escaped double-quote appended on exec influx input

### ISSUE THREAD

**Issue by marknmel** [influxdata/telegraf#843]
Hi,
I've got a script that barfs out some details for a small wireless network. Somehow an extra escaped double-quote appears in influx, but the origin of the escaped seems to be telegraf/exec/influx plugin.

```
# /etc/telegraf/exec/wireless-client.sh 
wireless,host=Marknmel-WAP-01,interface=wl0.1 client="B8:17:C2:DB:CF:16"
wireless,host=Marknmel-WAP-01,interface=wl0.2 client="94:EB:CD:14:A0:14"
wireless,host=Marknmel-WAP-01,interface=wl0.2 client="14:7D:C5:89:BF:F1"
wireless,host=Marknmel-WAP-01,interface=wl0.2 client="94:4A:0C:09:4D:3E"
wireless,host=Marknmel-WAP-02,interface=wl0.2 client="94:EB:CD:14:A0:14"
wireless,host=Marknmel-WAP-02,interface=wl0.2 client="E0:06:E6:F0:3E:87"
wireless,host=Marknmel-WAP-02,interface=wl0.2 client="48:9D:24:17:BE:AF"
wireless,host=Marknmel-WAP-02,interface=wl0.2 client="70:D4:F2:5F:B6:8F"
wireless,host=Marknmel-WAP-02,interface=wl0.2 client="14:74:11:E6:F5:08"

```

I'm calling this from telegraf:
```
[[inputs.exec]]
  ## Wireless Client Stats
  commands = ["/etc/telegraf/exec/wireless-client.sh"]
  data_format = "influx"

```
And it works - sort-of.

```
# telegraf -config /etc/telegraf/telegraf.conf -test | grep -i wireless
> wireless,host=Marknmel-WAP-01,interface=wl0.1 client="B8:17:C2:DB:CF:16\"" 1457875933462999091
> wireless,host=Marknmel-WAP-01,interface=wl0.2 client="94:EB:CD:14:A0:14\"" 1457875933462999091
> wireless,host=Marknmel-WAP-01,interface=wl0.2 client="14:7D:C5:89:BF:F1\"" 1457875933462999091
> wireless,host=Marknmel-WAP-01,interface=wl0.2 client="94:4A:0C:09:4D:3E\"" 1457875933462999091
> wireless,host=Marknmel-WAP-02,interface=wl0.2 client="94:EB:CD:14:A0:14\"" 1457875933462999091
> wireless,host=Marknmel-WAP-02,interface=wl0.2 client="E0:06:E6:F0:3E:87\"" 1457875933462999091
> wireless,host=Marknmel-WAP-02,interface=wl0.2 client="48:9D:24:17:BE:AF\"" 1457875933462999091
> wireless,host=Marknmel-WAP-02,interface=wl0.2 client="70:D4:F2:5F:B6:8F\"" 1457875933462999091
> wireless,host=Marknmel-WAP-02,interface=wl0.2 client="14:74:11:E6:F5:08\"" 1457875933462999091
```

This shows up in Influx as well. That's where I noticed it.

Where is the extra quote coming from? I'm confused!  Am I missing something obvious or have I stumbled on something?

I'm on Influx 10.3 and Telegraf 10.4 - Centos 7.2 x86_64

I'm happy to provide any other info needed to resolve! 

Thanks
/Mark

**Comment by sparrc** [comment]
@marknmel I can't reproduce...I wrote up a shell script like this:

```sh
#!/bin/sh

echo wireless,host=Marknmel-WAP-01,interface=wl0.1 client=\"B8:17:C2:DB:CF:16\"
```

executing I get:

```
% /tmp/843.sh
wireless,host=Marknmel-WAP-01,interface=wl0.1 client="B8:17:C2:DB:CF:16"
```

And influx output:

```
% telegraf -config ~/ws/telegraf.conf -input-filter exec -test
* Plugin: exec, Collection 1
> wireless,host=Marknmel-WAP-01,interface=wl0.1 client="B8:17:C2:DB:CF:16" 1457952336804573676
```

Any thoughts on how to reproduce?

**Comment by marknmel** [comment]
Hi @sparrc 

Thanks for having a look.  I know why this is an issue now.  

The influx line protocol says: 

> Multiple lines must be separated by the newline character \n

My Bad! - The exec script returns data that has CRLF.   By cleaning up the output with `sed 's/^M$//'` resolves the issue.

I'm not sure that the plugin should do anything different than it already does.  Should this be documented within the Exec Input Plugin Readme?  

That Readme is kinda vague - If you want - I could take this...

**Comment by sparrc** [comment]
that would be great if you could clean it up, thanks @marknmel!

**Comment by sparrc** [comment]
this is done I believe, thanks @marknmel

**Comment by simonprev** [comment]
Hi sorry to reopen an old thread but I have the same behavior after updating from telegraf 1.2 to 1.3 and node from 6 to 8 but I can’t reproduce the working behavior.

My NodeJS script output the right data without escaping the double quote:

```
rawdata,ewonid=324071,tagname=M2_Status,shift="night",sku="0" value=3 1510274398000000000
```

but when I run the script inside `telegraf` `inputs.exec`

```
[[inputs.exec]]
  commands = ["npm run telegraf --silent"]
```

The quote are escaped in my output files `[[outputs.file]]`

```
rawdata,ewonid=324071,tagname=M2_Status,shift=\"night\",sku=\"0\" value=3 1510274398000000000
```

Does it looked like you issue @marknmel ?

**Comment by sparrc** [comment]
@simonprev tags do not need (and might not support) quotes around them, the correct line-protocol would be:

```
rawdata,ewonid=324071,tagname=M2_Status,shift=night,sku=0 value=3 1510274398000000000
```

**Comment by simonprev** [comment]
Yeah I know that it should look like this, but I’m dealing with an old system that seems to be inserting with wrapping double quotes.

```
> select * from rawdata where time <= now() order by time desc limit 1
name: rawdata
time                 ewonid shift sku tagname            value
----                 ------ ----- --- -------            -----
2017-11-16T20:35:19Z 57373  "day" ""  (c)Red-light-1     0
```

And when I do queries, I need to wrap the value in quotes:

```javascript
`AND sku = '"${recipe.name}"'`
```

Is it still possible to do that in telegraf, or what version could enable me to do this?

**Comment by simonprev** [comment]
Or even better, a way to rewrite all datapoints to remove the double quotes 😄

**Comment by danielnelson** [comment]
I think you would need to do this manually with a script that reads from InfluxDB and writes back the modified data.  If you are still ingesting in this format you could send the data through Kapacitor to modify the data before insertion.

**Comment by sgorbunov** [comment]
Same issue here, I'm trying to give my field a name like "Some Nice Name", this is a supported name format in Influx, but Telegraf does not format double quotes in a proper way...  :(

when the bash script is run quotes are printed as they should:

`[root@e29fole1 telegraf]# ./axx_disk_latency.sh 
axx_metrics_data,device=vdb axx_bbx_disk_read_latency=0.43
axx_metrics_data,device=vdb axx_bbx_disk_read_latency=0.43
axx_metrics_data,device=vdb "Read IOPS All"=14.55
`
but the the script is executed by telegraf:

`2018-07-18T08:02:40Z E! Error in plugin [inputs.exec]: metric parse error: expected field at offset 151: "axx_metrics_data,device=vdb axx_bbx_disk_read_latency=0.43\naxx_metrics_data,device=vdb axx_bbx_disk_read_latency=0.43\naxx_metrics_data,device=vdb \"Read IOPS All\"=14.55\n"`

That's a bit strange behavior.

**Comment by sgorbunov** [comment]
ok and here is the solution to insert spaces into the field name
  `echo "axx_metrics_data,device=$device,host=FarSync Read\\ IOPS\\ All=$r_iops"`
