### ISSUE TITLE
Multiple processes with same name not tracked in Windows

### ISSUE THREAD

**Issue by rgroenewoudt** [influxdata/telegraf#8433]
I have multiple processes with the same name, for example w3wp.exe. I would expect all of them are tracked but I only see 1 process in InfluxDB.

### Relevant telegraf.conf:

```toml
  interval = "30s"
[[inputs.win_perf_counters.object]]
	    ObjectName = "Process"
	    Counters = [
	      "ID Process",
	      "% Processor Time",
	      "Handle Count",
	      "Thread Count",
	      "Working Set - Private"
	    ]
	    Instances = ["*"]
		WarnOnMissing = true
	    Measurement = "win_proc"
```

### System info:
Windows Server 2019 Datacenter 1809
Telegraf 1.15.4
InfluxDB 1.8.3-1

### Expected behavior:
Task Managed shows multiple w3wp.exe processes.
![image](https://user-images.githubusercontent.com/39033010/99520786-d5460800-2993-11eb-9a81-9b9a445c306c.png)

My expectation is that InfluxDB contains a record for every process.
```
SELECT time, ID_Process, instance FROM "win_proc" WHERE ("host" = 'SEQTESTWEB02' AND "instance" = 'w3wp') ORDER BY DESC LIMIT 20
```

### Actual behavior:
However, only 1 Process ID is present in the data.
```
> SELECT time, ID_Process, instance FROM "win_proc" WHERE ("host" = 'SEQTESTWEB02' AND "instance" = 'w3wp') ORDER BY DESC LIMIT 20
name: win_proc
time                 ID_Process instance
----                 ---------- --------
2020-11-18T10:50:30Z 7388       w3wp
2020-11-18T10:50:01Z 7388       w3wp
2020-11-18T10:49:30Z 7388       w3wp
2020-11-18T10:49:00Z 7388       w3wp
2020-11-18T10:48:31Z 7388       w3wp
2020-11-18T10:48:00Z 7388       w3wp
2020-11-18T10:47:30Z 7388       w3wp
2020-11-18T10:47:01Z 7388       w3wp
2020-11-18T10:46:30Z 7388       w3wp
2020-11-18T10:46:00Z 7388       w3wp
2020-11-18T10:45:31Z 7388       w3wp
2020-11-18T10:45:00Z 7388       w3wp
2020-11-18T10:44:30Z 7388       w3wp
2020-11-18T10:44:01Z 7388       w3wp
2020-11-18T10:43:30Z 7388       w3wp
2020-11-18T10:43:00Z 7388       w3wp
2020-11-18T10:42:31Z 7388       w3wp
2020-11-18T10:42:00Z 7388       w3wp
2020-11-18T10:41:30Z 7388       w3wp
2020-11-18T10:41:01Z 7388       w3wp
```

**Comment by SimonMcN** [comment]
This requires 	UseWildcardsExpansion = true
:-)

**Comment by SimonMcN** [comment]
I have suggested that this be default many times before but I don't remember why it wasn't changed.

**Comment by rgroenewoudt** [comment]
I don't see any difference with UseWildcardsExpansion = true

**Comment by rgroenewoudt** [comment]
I have no experience with Go so code is difficult to read but I don't know how PdhExpandWildCardPath() exactly works.
If you give the counter path "\Process(conhost)\% Processor Time", do you get a list of the following?
```
\Process(conhost#1)\% Processor Time
\Process(conhost#2)\% Processor Time
\Process(conhost#3)\% Processor Time
````

**Comment by rgroenewoudt** [comment]
Ah, my bad. UseWildcardsExpansion = true works, the instance name has a suffix #xx, just like in Windows Performance Monitor.
