### ISSUE TITLE
data_format like https://bigeasy.github.io/packet/

### ISSUE THREAD

**Issue by vinnitu** [influxdata/telegraf#8434]
Hello.

Nice have https://bigeasy.github.io/packet/ data_format type to parse binary input data

BTW how to add custom data_format for all type input sources?

**Comment by reimda** [comment]
Packet is a javascript library so it can't be used in telegraf.  There is a good amount of user demand for a binary data_format, but we will need to find an appropriate golang library that is expressive enough to describe arbitrary formats 

This is related to #6804
