### ISSUE TITLE
Add configurable timeout to bind input plugin http call

### ISSUE THREAD

**Issue by afletch** [influxdata/telegraf#8443]
### Proposal:

Add configurable timeout value to bind input plugin for the http request to bind

### Current behavior:
The http request currently has a static 4 second timeout value defined:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/bind/bind.go#L29
On loaded bind instances, or those with many zones, the http response time can often exceed this value.

### Desired behavior:
`http_timeout` parameter specified within plugin configuration is applied to the http connection

### Use case:
Allow tuning for different workloads/responses sizes.

**Comment by ssoroka** [comment]
This sounds great. Are you comfortable making the change? There's a `config.Duration` field type that's perfect for this.

**Comment by afletch** [comment]
@ssoroka Go isn't really my thing and it looks like @stephanie-engel has taken this, but happy to help where I can.

**Comment by stephanie-engel** [comment]
@afletch This feature is now merged into `master`. The param is called `timeout`. To use it, simply add the following to the bind input plugin (for example, when adding a 15 second timeout):

```
[[inputs.bind]]
  timeout = "15s"
```
 Please feel free to reach out if you have any other questions!

**Comment by afletch** [comment]
@stephanie-engel fantastic, thank you for this.
