### ISSUE TITLE
OPC UA Array off value

### ISSUE THREAD

**Issue by vttland** [influxdata/telegraf#8452]
Hello Im using op.ua is working well  and make great job but i have little issu i have a variable with  array i could correctly visualize it in my client but after telegraf in my influxdb V2 this variable is copied six time ( number of field)  whith the first value of array.
Have a special setting ?

**Comment by sjwang90** [comment]
We reserve Telegraf issues for bugs for reproducible problems.  Please feel free to reach out to us (can DM me) in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
