### ISSUE TITLE
Tomcat plugin does not respect name_override

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#8456]
config:
# Gather metrics from the Tomcat server status page.
[[inputs.tomcat]]
name_override = "Mytest_Tomcat"
  ## URL of the Tomcat server status
  url = "http://127.0.0.1:39834/manager/status/all?XML=true"

Plug in does not respect name_override  as it adds hardcoded fields

		acc.AddFields("tomcat_connector", tccFields, tccTags)
		acc.AddFields("tomcat_jvm_memorypool", tcmpFields, tcmpTags)
	        acc.AddFields("tomcat_jvm_memory", tcm, nil)

**Comment by SimonMcN** [comment]
It appears name_prefix will achieve this.  Will request a documentation update

**Comment by srebhan** [comment]
I'm pretty sure `name_override` also works. The overriding is done _before_ outputting the metric from the input plugin. Check `models/running_output.go` line 156.
