### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by SimonMcN** [influxdata/telegraf#8457]
Please can you clarify in the documentation that name_prefix should be preferred to name_override in case people add hard coded fields in plugins.  i.e. the solr and tomcat plugins

It appears that name_override requires that you look in the plugin code and see if it adds fields.  Otherwise the behaviour is unpredictable.  It makes me wonder if name_override is fit for purpose as you cannot use it without investigating code.

**Comment by srebhan** [comment]
I think you misunderstood the concept of `name_override`! [The documentation ](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins) clearly states: 

> name_override: Override the base name of the measurement. (Default is the name of the input).

So `name_override` has nothing to do with fields... What are you trying to achieve?

**Comment by SimonMcN** [comment]
Both the solr and tomcat plugins create measurements which do not obey name_override.  What, for instance, if I wanted to override solr_core in the solr plugin?  I can't as it's hard coded.  I understand thst name_override only applies to the base metric name, but in that case you there shouldn't be a way to add hard coded metric names in the plug ins.  If you understand me ?

**Comment by SimonMcN** [comment]
What I'm getting at is that override_name works if there is a single measurement.  Prefix and suffix work to prepend/append the name to all additional measurements nested within the plug in .  The problem is that really it seems as if plug plugins shouldn't be able to add measurements which can't have their base name overridden (i don't even know how you'd design that)

**Comment by helenosheaa** [comment]
@SimonMcN name_override would work to override the measurement name solr_core, I'm going to close this out. If this is still an issue feel free to reopen and please provide your telegraf config and the output vs your desired output so we can help debug.
