### ISSUE TITLE
no datacenter metrics from vsphere plugin

### ISSUE THREAD

**Issue by somersbd** [influxdata/telegraf#8467]
Hello,
I'm not sure this is a bug or maybe a feature request. It appears that the telegraf vsphere plugin does not write any datacenter information and just wondering why? I get the  warning below on every pass that it finds datacenter objects but has no parent and when i look in influx i see no information for datacenters. If this is a config problem on my side I can't seem to find where it is but when using something like graphite that data shows up.

2020-11-24T16:34:52Z D! [inputs.vsphere] Find(Datacenter, /*) returned 3 objects
2020-11-24T16:34:52Z D! [inputs.vsphere] No parent found for Folder:group-d1 (ascending from Folder:group-d1)

**Comment by sjwang90** [comment]
Can you please provide a sample of your configuration?

**Comment by somersbd** [comment]
Sure, this is it.
## Realtime instance
[[inputs.vsphere]]
## List of vCenter URLs to be monitored. These three lines must be uncommented
## and edited for the plugin to work.
interval = "20s"
vcenters = [ "https://192.168.1.251/sdk" ]
username = "telegraf-user@vsphere.local"
password = "secret!"

vm_metric_include = ["*"]
host_metric_include = ["*"]
cluster_metric_include = ["*"]
cluster_instances = true ## false by default
#datastore_metric_exclude = ["*"]
datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest"]

max_query_metrics = 256
timeout = "60s"
insecure_skip_verify = true

## Historical instance
[[inputs.vsphere]]
interval = "300s"
vcenters = [ "https://192.168.1.251/sdk" ]
username = "telegraf-user@vsphere.local"
password = "secret!"

datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest"]
cluster_metric_include = [ "cpu.usage.average", "cpu.usage.minimum", "cpu.usage.maximum", "mem.usage.average", "mem.usage.minimum", "mem.usage.maximum"]
insecure_skip_verify = true
force_discover_on_init = true
host_metric_exclude = ["*"] # Exclude realtime metrics
vm_metric_exclude = ["*"] # Exclude realtime metrics

max_query_metrics = 256
collect_concurrency = 3

**Comment by prydin** [comment]
My initial guess is that this is a permission problem. Can you try with a vCenter account that has readonly access to the entire inventory tree?

**Comment by somersbd** [comment]
The account I'm using is read-only at the global access level. I also tried the Administrator@vsphere.local which has full rights and get the same "No parent found for Folder:group-d1 (ascending from Folder:group-d1)" after the Find(Datacenter, /*) says it returns objects.

**Comment by prydin** [comment]
@somersbd The error message is benign. Are you still not seeing any datacenter metrics?
