### ISSUE TITLE
inputs.opcua multiple nodes in one database entry

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/telegraf#8471]
## Feature Request

```
[[inputs.opcua]]
   name = "someexample"
   endpoint = "opc.tcp://1.2.3.4:4321/"
   connect_timeout = "10s"
   request_timeout = "5s"
   interval = "1s"
   security_policy = "None"
   security_mode = "None"
   auth_method = "Anonymous"
   nodes = [
     {name="value1", namespace="1", identifier_type="s", identifier="Input1", data_type="float", description="Input 1"},
     {name="value2", namespace="1", identifier_type="s", identifier="Input2", data_type="float", description="Input 2"},
   ]
```

### Proposal:

Add multiple fields in one entry and strip out the quality tag. In case quality is not good, leave the corresponding field empty with no data.

measurement: timestamp, tagA, tagB, tagC, value1, value2
measurement: now(), sometagA, sometagB, sometagC, 10, 12

(keep as a reference the example in the current behavior)

### Current behavior:

When multiple nodes are defined in the same metric, this is what happens: in the same timestamp there are 2 entries with different fields
measurement: timestamp, quality, host, is, name, value1, value2
measurement: now(), OK, somequality, someid, value1, 10, //
measurement: now(), OK, somequality, someid, value2, //, 12

like in the picture
![image](https://user-images.githubusercontent.com/34926125/100203755-4b51ee00-2f03-11eb-9f92-23ac2041acd6.png)

### Desired behavior:

In my opinion there should be a way to handle this with one entry and multiple fields, like it can be done with the mqtt consumer, where the user defines the tag list and everything else is a field.

### Use case: 

Imagine a pipe where a fluid is flowing and you are recording input and output temperature: those can go in the same measurement called "pipe" with 2 fields (in and out temp) and the same set of tags.

That is what we currently do with the MQTT input plugin and it will speed up the possibility to merge the information from different input protocols using the same data structure and thus dashboards, ...

**Comment by mirkocomparetti-synesis** [comment]
Looking back at this, it can be achieved by using a combination of processors plugin and the aggregators.merge.
I think this can be closed.

Best

**Comment by acejacek** [comment]
In simple cases - yes, it can. However, aggregator [merge](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge) works as last step (after processors), so if you tag your nodes in different way, merge will fail. In some cases it's useful to employee processor to change selected fields to tags, then merge fails too.

Have a look at this example:
```
[[inputs.opcua]]
  name = "opcua"
  interval = "1m"
  endpoint = "opc.tcp://1.2.3.4:4840"
  connect_timeout = "30s"
  security_policy = "None"
  security_mode = "None"
  auth_method = "Anonymous"
nodes = [
  {name="Product", namespace="3", identifier_type="s", identifier="ArtNr", data_type="string"},
  {name="SerialNumber", namespace="3", identifier_type="s", identifier="SerNr", data_type="string"},
]​

# strip unneded tags
tagexclude = ["id", "name"]
fielddrop = ["Quality"]

# convert tag from field - I need Product to be a tag
# this step ruins [[aggregators.merge]]
[[processors.converter]]
  order = 1
​  [processors.converter.tags]
    string = ["Product"]​
```
To solve this issue I pulled out all tricks I could think off, and eventually drop opcua plugin and switch to Node-RED, for now.

**Comment by mirkocomparetti-synesis** [comment]
Yes, there are limitations, I know. But if I decide to tag stuff differently, maybe I do not want to merge them, otherwise the tags would be coherent, which is the baseline to have them all in one entry.

We are coming from nodered, but I do really prefer the telegraf approach and I was long waiting for this plugin to come out!

**Comment by acejacek** [comment]
maybe #8475 will solve this issue. In OPC-UA the nodes tree looks like this:
```
Product ---------> ArtNr
           |
           ------> SerNr
```
If I'll query OPC-UA on Product level instead on leaves, maybe it will produce correct, array result. Now it breaks with unknow data format.

**Comment by zwl-sun** [comment]
Hello! Please What OPC server do you use?

**Comment by zwl-sun** [comment]
I can't collect identifier

**Comment by werbungvonmir** [comment]
Hi! I am trying to import arrays and am wondering if there is a solution available that I have not stumpled across so far. I have not been successfull in importing arrays as of now.

If you have any advice that can help me I would be delighted!

**Comment by spkis** [comment]
> maybe #8475 will solve this issue. In OPC-UA the nodes tree looks like this:
> 
> ```
> Product ---------> ArtNr
>            |
>            ------> SerNr
> ```
> 
> If I'll query OPC-UA on Product level instead on leaves, maybe it will produce correct, array result. Now it breaks with unknow data format.

Hello,
The ticket #8475 was closed and linked to this issue here. 

@sjwang90 would it be possible to re-evaulate implementing OPC-UA arrays in Telegraf? 

@AlexTymoshenko this is of interest for you as well.
