### ISSUE TITLE
Docker input - max cpus and disable per-cpu stats

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#8480]
## Feature Request

Couple of new features. It would be nice to have in `docker_container_cpu` the cpu limits (CpuShares?), just like `docker_container_mem`.`max_limit` provides the container max memory.

The `usage_percent` is computed on a single CPU. However, in our monitoring system, we would like to take into consideration how many cpus are allocated to the container. For instance, say the `usage_percent` is 100% and the container has 2 cpus. That means that we are only using half of the CPU resources assigned to the container. If it was 200%, then we would be using 100% of the CPU resources we have.

Additionally, it would be good to have a knob to disable per-cpu statistics, just like the `cpu` input plugin?

### Proposal:

For the first request, I think just exposing `CpuShares` would provide the missing piece of information.

For the second request, I guess something like it's done in the cpu plugin would work and it'd be quite consistent?

```  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total container cpu stats or not
  totalcpu = true
```

### Current behavior:

Currently, the docker input plugin doesn't provide the cpu limits configured in the container. Also, it doesn't allow enabling/disabling per-cpu statistics. One has to use tagdrop to get rid of the metrics, sucks a bit.

### Desired behavior:

Have cpu max limits and ability to disable per-cpu statistics.

**Comment by sjwang90** [comment]
Thanks for the feature request. If you would like to open a PR to add these features that would be great!

**Comment by powersj** [comment]
Closing via #7312, which seems to have added the total and per <item> values.
