### ISSUE TITLE
New Intel PowerStat input plugin

### ISSUE THREAD

**Issue by p-zak** [influxdata/telegraf#8485]
## Feature Request
We have created a Telegraf PowerStat input plugin which enables monitoring of platform metrics (power, TDP) and per-CPU metrics like temperature, power and utilization.

Intel PowerStat plugin supports _Intel_ based platforms and assumes presence of _Linux_ based OS.

#### In the near future we will propose PR which adds new plugin we have created. It will be able to provide following metrics:
**Platform metrics:**
- thermal_design_power (Maximum Thermal Design Power (TDP) available for processor package [Watts])
- current_power_consumption (Current power consumption of processor package [Watts])
- current_dram_power_consumption (Current power consumption of processor package DRAM subsystem [Watts])

**Per-CPU metrics:**
- cpu_frequency (Current operational frequency of CPU Core [MHz])
- cpu_temperature (Current temperature of CPU Core [Celsius degrees])
- cpu_busy_cycles (CPU Core Busy cycles as a ratio of Cycles spent in C0 state residency to all cycles executed by CPU Core [%])
- cpu_c6_state_residency (Percentage of time that CPU Core spent in C6 Core residency state [%])
- cpu_c1_state_residency (Percentage of time that CPU Core spent in C1 Core residency state [%])
- cpu_busy_frequency (CPU Core Busy Frequency measured as frequency adjusted to CPU Core busy cycles [MHz])

### Use case:
Key source of platform telemetry is power domain that is beneficial for MANO/Monitoring&Analytics systems to take preventive/corrective actions based on platform busyness, CPU temperature, actual CPU utilization and power statistics. 
Main use cases are power saving and workload migration.

**Comment by Leynakindle** [comment]
@p-zak Hello Zak, I encountered an issue while using the powerstat plugin. 
Specifically, when I run Telegraf with Docker Compose, I receive an error about loading MSR. However, I do not encounter this issue when running it directly on the host machine. Do you have any suggestions on how to resolve this? 
Attached is my compose.yaml file for reference. Host OS is CentOS Stream 9.
`services:
    telegraf:
        image: telegraf:1.26.2
        container_name: telegraf
        hostname: intel-101
        restart: always
        privileged: true
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /sys/devices/virtual/powercap/intel-rapl:/sys/devices/virtual/powercap/intel-rapl:ro
            - /sys/devices/system/cpu:/sys/devices/system/cpu:ro
            - /dev/cpu:/dev/cpu:ro
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "100"`

**Comment by pcgeek86** [comment]
It would be really nice if this plugin worked on AMD Ryzen CPUs, on the Windows 11 platform.

Other tools like [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) and HWMonitor are able to pull CPU voltage, wattage, and temperature. I think Libre Hardware Monitor has a .NET client library that could be used to retrieve this data.

![image](https://github.com/user-attachments/assets/f53bec9f-3ff5-416e-b396-e20c5a57c9b5)
