### ISSUE TITLE
How to rename key's name with regex

### ISSUE THREAD

**Issue by xiaopeng163** [influxdata/telegraf#8486]
hi team

we received some metrics like(through prometheus output plugin)

```
 snmp_trap_sysUpTimeInstance{ciscoMgmt_276_1_1_2_1_3_68="down"", environment="acc", host="telegraf", ifDescr_68="TenGigE0/0/0/0",  version="2c"}
```

and is there a way to repleace `ifDescr_68` to `ifDescr`

```
[[processors.rename.replace]]
    tag = "ifDescr_68"
    dest = "ifDescr"
```

But here `68` is not a **fixed number**, it could be any numbers.  

so basically we want to replace  `ifDescr_{some number}`  to `ifDescr`

thanks

**Comment by ssoroka** [comment]
Check out the [regex processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex), which does this.
