### ISSUE TITLE
CF RabbitMQ Metrics missing/unavailable via Telegraf OneAgent plugin

### ISSUE THREAD

**Issue by vust1001** [influxdata/telegraf#8491]
Hello,

I am opening this issue to report that there are CF RabbitMQ metrics missing via the Telegraf Dynatrace plugin. As noted here in the InfluxData post: https://community.influxdata.com/t/cf-rabbitmq-metrics-missing-unavailable-via-telegraf-oneagent-plugin/16862

These are essential RabbitMQ metrics that we are interested in. Please let me know if it would be possible to add these and when that can be done.

Thank you!

**Comment by vust1001** [comment]
Hello,

Anyone have any updates or feedback?

**Comment by sjwang90** [comment]
If anyone would like to open a pull-request with the changes that would be great. Per @ssoroka, if you want to take a look at that, the relevant code seems to be around here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/rabbitmq/rabbitmq.go#L477

**Comment by sspaink** [comment]
@vust1001 sorry you haven't had a response for so long, are you still interested in seeing this feature request implemented?
