### ISSUE TITLE
problem with Cisco telemetry MDT 

### ISSUE THREAD

**Issue by depfryer** [influxdata/telegraf#8493]
hi
i use Cisco telemetry MDT and i want to know how can i automatically add the remote address into influx (like agent_host in SNMP)

thanks

**Comment by nradonicich** [comment]
This shows up as tag "source" which comes from the "node_id_str" field in the original data.

You can then use a field transformation to change this to whatever you want.

```
[[processors.rename]]
  namepass = ["Cisco*", "ietf-interfaces*"]
  [[processors.rename.replace]]
    tag = "source"
    dest = "host"
```

**Comment by depfryer** [comment]
"source" is the name of the router not the IP address 
![image](https://user-images.githubusercontent.com/17575141/100896293-c2b4ee00-34be-11eb-92ce-3756d8e0d511.png)

**Comment by nradonicich** [comment]
I see, so you more closely want something like the `source` tag from snmp_trap input which tells you the source IP address of the data coming in, the `agent_host` tag in snmp input is what you entered into the config being DNS address or IP address?

**Comment by depfryer** [comment]
I use the subscription
so Telegraf does not receive without asking

yes i want to make like `source` from snmp_trap
(this is a better example of the desired result....)

the `agent_host` is just IP address
