### ISSUE TITLE
input.modbus Handle 3 words length

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/telegraf#8497]
### Proposal:

Handle a configuration like
{ name = "Somename", byte_order = "ABCDEF", data_type = "<somefloat>", scale=0.000001,  address = [0,1,2]},

### Current behavior:

Only support for max 2 words

### Use case: 

We use a [energy meter](https://www.seneca.it/en/linee-di-prodotto/energia-e-misure-elettriche/contatori-di-energia-serie-s500/s504c-80/) device which outputs some values in 3 words (floats, see S1 on page 11, regset 0 [here](https://www.seneca.it/media/6847994/mi003837-e.pdf)) which cannot be interpreted right now, so we have no option to let them in.

**Comment by Nemecsek** [comment]
Without changing the plugin, in your device I would switch to *RegSet1* that uses easier even-size registers.
After setting `REGSET 0538 = 1`, you can later use the common `INT64` and `FLOAT64-IEEE` (the latter has just been introduced: remember to checkout the last Telegraf release)

**Comment by mirkocomparetti-synesis** [comment]
> Without changing the plugin, in your **S504C-80** (or similar) I would switch to _RegSet1_ that uses easier even-size registers.
> After setting `REGSET 0538 = 1`, you can later use the common `INT64` and `FLOAT64-IEEE` (the latter has just been introduced: remember to checkout the last Telegraf release)

Thanks!
Actually we started using the IEEE registers that are available in that device, so we worked around this in that way, using FLOAT32-IEEE. Pretty similar to what you suggested.
Anyway, this works because the device exposes the data also in those registers (and regset 1 as you mentioned), but this is not valid in general devices, so expanding the plugin might make sense.

**Comment by sjwang90** [comment]
@mirkocomparetti-synesis If you are interested in a submitting a PR for this at all that would be great.
