### ISSUE TITLE
Telegraf fails to start when custom tags are added in the input_internal plugin configs

### ISSUE THREAD

**Issue by niftyhoot** [influxdata/telegraf#8504]
### Relevant telegraf.conf:

```
[[inputs.internal]]
  collect_memstats = false
  tagexclude = ["go_version", "version"]
  [inputs.internal.tags]
    "cfgver" = "12-02-2020-v1"


```

### System info:
Telegraf version 16.2
Ubuntu 20.04

1. Add a custom tag section in the input_internal plugin in

### Expected behavior:
Telegraf should send the said tag for internal stats.

### Actual behavior:
Telegraf fails to start
This used to work til 14.2 but seems to be broken in newer version

### Additional info:
2020-12-03T01:59:41Z I! Starting Telegraf 1.16.2
2020-12-03T01:59:41Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/conf.d/input_internal.conf: Error parsing internal, could not parse tags for input internal

**Comment by ssoroka** [comment]
While it should probably work, you might want to set that as a global tag instead, rather than setting it on each plugin.

**Comment by niftyhoot** [comment]
Thanks @ssoroka for looking into this. 
Basically, I was using this special set of metrics to capture the config version I was using (might not have been the bestpossible approach but it has worked well for me for a long time now and have other instrumentation and automation that depends on this tag now).  So, My use case did not permit global tag as we often change telegraf configs and keep updating this tag for every config change. Adding this tag in global tag set would mean we have the risk of unnecessary cardinality change of significant size.

**Comment by AkaiNoCat** [comment]
hello, I am also facing this problem, when I want to use the plugin tags for multiple inputs to route to the specified output with tagpass set, my telegraf 1.18 version also came out with the problem of configuration parsing failure

**Comment by Eraser3** [comment]
I am new to telegraf but I also seem to face this issue. I wanted to add a specific tag to my inputs.http plugin so that I could use a custom retention policy in my influx database. My plugin starts with this part:

```
[[inputs.http]]
  name_override = "HighPrecisionUsage"
  interval = "1s"
  
  [inputs.http.tags]
    "tagretention" = "7days"
```

My output looks like this:

```
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "telegraf"
  timeout = "5s"

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  retention_policy = ""
  
  ## The value of this tag will be used to determine the retention policy.  If this
  ## tag is not set the 'retention_policy' option is used as the default.
  retention_policy_tag = "tagretention"
```

But with this configuration telegraf fails to start with the error:  

> E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: error parsing http, could not parse tags for input httd

When I comment out the `[inputs.http.tags]` part it starts just fine. I also tried writing the tag name `"tagretention"` without quotes, so like `tagretention`, but it fails with the same message.

**Comment by niftyhoot** [comment]
@ssoroka  @danielnelson 
I think this is a side effect of  PR 7751 https://github.com/influxdata/telegraf/pull/7751
The issue does not show up in releases older than 1.14.5
I am happy to propose a change that reverts 7751 you agree and would like me to

**Comment by akrantz01** [comment]
@niftyhoot @Eraser3 @AkaiNoCat Could you try using the [latest release](https://github.com/influxdata/telegraf/releases/latest)? It appears to have been fixed somewhere along the line.

**Comment by sjwang90** [comment]
Closing issue as this seems to have been address. Please re-open if it's not the case.
