### ISSUE TITLE
Invalid data format; Prometheus

### ISSUE THREAD

**Issue by BlueskyFR** [influxdata/telegraf#8513]
Using the docker image `telegraf:alpine` (1.16.3), using the following config throws an error:

```yaml
[[inputs.http_listener_v2]]
  service_address = ":4002"
  data_format = "prometheus"
```
```
I! Using config file: /etc/telegraf/telegraf.conf
E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: Error parsing http_listener_v2, Invalid data format: prometheus
```

It obviously shouldn't happen since #7778 was merged.

**Comment by srebhan** [comment]
Well I think the "prometheus" parser didn't make it to 1.16.3. Correct me @reimda if I'm wrong here.

So you have two options, either waiting for the next release that might include "prometheus" OR you build telegraf from source. Building is as difficult as setting up golang, clone the repo and hit `make`... :-)

**Comment by BlueskyFR** [comment]
Oh it seems that you're right, I pretty sure it made it to 1.16.3...
I was already building it manually before, I guess I will continue until the next version come out :)

**Comment by srebhan** [comment]
Then could you please close the issue!? Thanks!
