### ISSUE TITLE
Dynamically collect metrics base of a set condition

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8518]
## Feature Request

**Conditional metric collection:**
Allow feedback loops in the processing of data. For example, one may want to detect some condition dynamically and at that point change filtering to collect more detailed data from the source.

Should be able to be done with `processors.starlark`

**Comment by sjwang90** [comment]
@essobedo If you're interested trying this at all!

**Comment by essobedo** [comment]
@sjwang90 Thx for proposing, I'm already on another ticket. I can have a look to this one after it.

**Comment by crflanigan** [comment]
Yes! I would be awesome to be able to change collection aggressiveness based on a condition being met.
Thanks!

**Comment by ssoroka** [comment]
Nothing needs to be done for this. You can do this today with the existing state support in the starlark plugin.
