### ISSUE TITLE
Build Telegraf for FIPS

### ISSUE THREAD

**Issue by pthirumalachar** [influxdata/telegraf#8527]
## Feature Request

We use Telegraf in our project and as a policy we build Telegraf from source.
However, as we are now going for FIPS certification, we need Telegraf to be FIPS certified.
So wanted to know if Telegraf is FIPS certified.

### Proposal:
If we build Telegraf from source using Boring Crypto GO, can we say that Telegraf if FIPS compliant.?
Are there any other flows, issues that might get surfaced?
Could Telegraf team kindly suggest.

**Comment by sjwang90** [comment]
Please see: https://github.com/influxdata/telegraf/issues/8363

We currently do not have plans to make Telegraf FIPS compliant
