### ISSUE TITLE
Input Plugin: SNMP - Version 3 does not support AES<blocksize>

### ISSUE THREAD

**Issue by dapryor** [influxdata/telegraf#8530]
### Proposal:

Support `AES<blocksize>` for the privProtocol in the SNMP input plugin settings.  These protocols are already supported in the underlying gosnmp module.

```go
	case NoPriv:
		sb.WriteString(",priv=NoPriv")
	case DES:
		sb.WriteString(",priv=DES")
	case AES:
		sb.WriteString(",priv=AES")
	case AES192:
		sb.WriteString(",priv=AES192")
	case AES256:
		sb.WriteString(",priv=AES256")
	case AES192C:
		sb.WriteString(",priv=AES192C")
	case AES256C:
		sb.WriteString(",priv=AES256C")
	}
```

`telegraf/internal/snmp/wrapper.go`
```
		switch strings.ToLower(s.PrivProtocol) {
		case "des":
			sp.PrivacyProtocol = gosnmp.DES
		case "aes":
			sp.PrivacyProtocol = gosnmp.AES
		case "":
			sp.PrivacyProtocol = gosnmp.NoPriv
		default:
			return GosnmpWrapper{}, fmt.Errorf("invalid privProtocol")
		}
```

### Current behavior:

Only `DES, AES, and ""` are accepted for privProtocol.
The system I am polling uses AES256 and drops the poll connection.

`Dropping SNMP request from x.x.x.x/62440 to INSIDE:x.x.x.x/snmp because: error decrypting request for user: readonly`

This behavior is not seen when using identical settings with DES set up as the privProtocol.

### Desired behavior:

I would like the full list of privProtocols supported as they are in the snmp_trap input plugin.  It seems this would be a matter of expanding the list of privProtocols in internal/snmp/wrapper.go

### Use case: 
I cannot poll devices in our environment. Security restrictions keep us from using anything but AES256 as the privProtocol

**Comment by dapryor** [comment]
Relevant PR:
When SNMPv3 support was added to snmp_trap plugin, only AES was immediately supported. gosnmp then expanded their support to `aes<blocksize>`and the PR updated to include those ciphers.
@

**Comment by dapryor** [comment]
Working on a PR

**Comment by dapryor** [comment]
Update: 
So this issue is not as easy as allowing the other options to be set.

Only net-snmp 5.8+ (the last two versions) allows AES192/256/192c/256c and at least in 5.8, it requires special configuration options to enable the algorithms.

**I'd like your opinions on how to continue on with this.** 

In the meantime, I am going to try to enable the algorithms on my machine and build a docker image with the modified telegraf.

**Comment by dapryor** [comment]
Update:
I have gotten net-snmp tools compiled with `--enable-blumenthal-aes`
The snmp tools now support 256 and 256C (256C is not documented in the `--help` but it still works)

Still trying having some issues with my MIBs not linking together properly.  

Once I figure that out, I will try to get telegraf working

**Comment by dapryor** [comment]
Update 3:

Telegraf is now successfully pulling SNMPv3 data with AES256C.

I can push the changes to the code go in a PR, **BUT** this change will require users to have the properly compiled net-snmp tools.

This change would also need an update for net-snmp in the telegraf docker container to properly support the protocols.
This would require adding a manual net-snmp build process in the container build pipeline.

**Comment by dapryor** [comment]
I have tested the manual net-snmp build into a telegraf container and it is working as expected.
This was the command used for my sanity test:

```
RUN apt update -y && apt upgrade -y \
    && apt install -y file libperl-dev \
    && wget http://sourceforge.net/projects/net-snmp/files/net-snmp/5.9/net-snmp-5.9.tar.gz \
    && tar xzvf net-snmp-5.9.tar.gz \
    && cd net-snmp-5.9 \
    && CC=gcc ./configure  --disable-debugging  --disable-manuals  --enable-shared  --enable-ipv6  --without-rpm  --enable-blumenthal-aes  --with-default-snmp-version="3"  --with-security-modules="usm"  --with-sys-location="Unknown" --with-gnu-ld --prefix=/usr --with-logfile="/var/log/snmpd" --with-sys-contact="@@no.where" --with-persistent-directory="/var/net-snmp" \
    && make && make install \
    && cd .. \
    && rm -rf net-snmp-5.9 \
    && rm -f net-snmp-5.9.tar.gz \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by reimda** [comment]
I don't see a problem with a PR to update the telegraf binary to support the newer privacy protocols if gosnmp has been updated to support them.  We don't need to update the official docker container in the same PR.  Let's get the binary updated as the first step, then look into updating the docker container.

If you have code ready that updates telegraf to add the privacy protocols, open an PR and I'd be happy to review it.

**Comment by dapryor** [comment]
Thanks for the reply @reimda.

I have linked the PR.
One circleci build failed, but the code that failed was something isolated from the changes I implemented.  Could you force a rebuild?

**Comment by dapryor** [comment]
I have opened an issue on the influxdata-docker repo requesting the team provide the net-snmp tools required to fully support snmpv3.

https://github.com/influxdata/influxdata-docker/issues/430
