### ISSUE TITLE
Nvidia-smi is too slow

### ISSUE THREAD

**Issue by BlueskyFR** [influxdata/telegraf#8534]
### Current behavior:

The Nvidia-smi plugin is too slow: it takes about 0.6 sec each time it is ran to complete:
*(on a 8 GPUs machine)*
```bash
❯ time nvidia-smi -q -x > /dev/null
nvidia-smi -q -x > /dev/null  0.01s user 0.09s system 17% cpu 0.588 total
```

### Proposal:

If we want to be able to go down to an interval of 10 ms for example, we definitely have to do something.
The current `nvidia-smi -q -x` command is taking too much time to complete because of 3 main factors:

1. The output is too big
2. There is useless information written to stdin
3. The command is executed each time

The goal is to reduce those factors as much as possible.

First, it is possible to filter which information is displayed using `nvidia-smi --query-gpu=timestamp,index,temperature.gpu,utilization.gpu,utilization.memory,memory.used,power.draw --format=csv`:
*(on a 8 GPUs machine)*
```bash
❯ time nvidia-smi --query-gpu=timestamp,index,temperature.gpu,utilization.gpu,utilization.memory,memory.used,power.draw --format=csv > /dev/null
nvidia-smi  --format=csv > /dev/null  0.00s user 0.03s system 42% cpu 0.071 total
```

Using this command, we already have a 0.588 / 0.071 = **828% performance boost**, because we selected what we wanted to display (I did not check if the selected stats are the same as the plugin yet though).

Another thing is to use the `-lms` option, which makes the command stay running by setting an interval in milliseconds. Using this parameter, we can reduce the scraping time to 10 ms:
*(on a 8 GPUs machine; I also added the `noheader` and `nounits` options to reduce the output size and thus improve performances)*
```bash
❯ time nvidia-smi --query-gpu=timestamp,index,temperature.gpu,utilization.gpu,utilization.memory,memory.used,power.draw --format=csv,noheader,nounits -lms 10
2020/12/10 11:23:47.896, 0, 24, 0, 0, 0, 41.00
2020/12/10 11:23:47.898, 1, 26, 0, 0, 0, 41.46
2020/12/10 11:23:47.899, 2, 23, 0, 0, 0, 41.00
2020/12/10 11:23:47.901, 3, 26, 0, 0, 0, 41.48
2020/12/10 11:23:47.903, 4, 24, 0, 0, 0, 41.48
2020/12/10 11:23:47.904, 5, 25, 0, 0, 0, 41.48
2020/12/10 11:23:47.906, 6, 24, 0, 0, 0, 41.00
2020/12/10 11:23:47.909, 7, 28, 0, 0, 0, 42.95
```
As you can see, the 8 GPUs statistics are gathered in 13 ms here, which gives us a total 0.588 / 0.013 = **4523% performance boost!**

I think we can definitely improve the Nvidia-smi input plugin's performances here, do you agree?

The only problem I see so far is that it would require a command that is always running, and find a way to dynamically read its output.

**Comment by BlueskyFR** [comment]
Can anything be done about this?

**Comment by powersj** [comment]
Hi,

The change in the nvidia_smi plugin to parse XML was done to collect additional metrics including things like driver and cuda version, fan speed, etc. Your first comparison excludes a number of these fields, so I do not believe the 828% performance number is truly accurate in terms of maintaining the currently collected metrics.

If you can find flags for all the current options and there is still a large performance improvement, then I think this is definitely something that would be nice to obtain. Is this something you are interested in looking into?

In terms of your second option, if a user needs to collect data at a high degree of precision, I would suggest running your proposed CLI in a script, combined with the exec input plugins.

Thanks!

**Comment by BlueskyFR** [comment]
@powersj ok I see the point you are making. The problem is that the current metric collection method is extremely slow, litterally not allowing sub-second mesurements, which is a problem for a lightweight metrics collector such as Telegraf IMO.

The best idea would be to drop some metrics while going for the high performance approach, and add a configuration flag allowing collection of more metrics at the cost of performances, since many of them are already visible in the high performance approach.

In the meantime, I made myself a script ran through exec, thus having a huge performance + CPU time boost
