### ISSUE TITLE
Error writing to outputs.influxdb: could not write any address / Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by zumodevidrio** [influxdata/telegraf#8537]
Randomly I receive the following error in logs:

```
E! [agent] Error writing to outputs.influxdb: could not write any address
E! [outputs.influxdb] When writing to [https://url:8086]: Post "https://url:8086/write?db=influx_db": dial tcp <influxdbserver>:8086: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

However I don't find any interruption in grafana or in the database.

In the logs of the InfluxDB server I don't receive any relevant information at the same time.

**Versions:**
Telegraf 1.16.3 
influxdb-1.8.2
InfluxDB server: CentOS Linux release 7.7.1908
Telegraf client: Ubuntu 16.04.7 LTS

**Client configuration:**

**telegraf.conf**

```
[global_tags]
  plateforme="platform"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

```

**telegraf.d/outputs.influxdb:**

```
[global_tags]
  plateforme = "platform"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["https://url:8086"]
  database = "db"
  username = "user"
  password = "pass"
  insecure_skip_verify = false
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.netstat]]
[[inputs.fail2ban]]
  use_sudo = true
[[inputs.postfix]]
  queue_directory = "/var/spool/postfix"
```

**Comment by zumodevidrio** [comment]
UPDATE: The recurrence of the message has been drastically reduced after increasing the ressources (CPU) of the InfluxDB server

**Comment by powersj** [comment]
Thanks for the update and sorry no one ever got back to you.

> Client.Timeout exceeded while awaiting headers

This message is usually due to a lack of resources, networking/dns issues or something else. As you have discovered, increasing some resources on the database helped.

I think I am going to close this, but if you are still running into issues, please do let us know.

Thanks!
