### ISSUE TITLE
[ethtool] ethtool input plugin to include speed and duplex

### ISSUE THREAD

**Issue by hloeung** [influxdata/telegraf#8547]
## Feature Request

Any chance of including speed and duplex settings with metrics exported by the ethtool plugin?

### Proposal:

e.g. (speed=1000,duplex=full)

### Use case: 

It's useful for when issues with cables, connectors, connections, or even incorrect switch port configs. We'll be able to identify and alert on when speed or duplex has changed.

**Comment by AnastasiosDados** [comment]
Any update on that?
