### ISSUE TITLE
Telegraf Processors :: handle bitwise data

### ISSUE THREAD

**Issue by sndstar** [influxdata/telegraf#8550]
Hello

I hope I am at the right place to solve a problem I have with extracting bitwise data from a field value with the Telegraf Processor facilities.

I have a field value containing an integer-encoded number, which I need to dissect into its individual bits. So far I have failed to find a combination of processors that would allow me to do that.

Desired result: derive n datapoints with field value type boolean from a singular datapoint with a field value type integer, the booleans in the former being the bits in the latter.

What I have tried: I looked at clone, enum, converter, and regex, but couldn’t find a combination that works.

Background: data comes from Modbus input, the device being polled packs its status bits into an integer that can be read from a single input register. Unfortunately, this behaviour cannot be changed. In order to know the status, the bits need to be recovered and stored in individual datapoints. Data goes to influxdb2.

I really appreciate your input / clever ideas towards solving this!

Regards
Andy

**Comment by sndstar** [comment]
Hello,

Update on this one, I managed to cludge together a workaround by using clone (to clone as many points as bits required), and enum. Enum is used as a lookup table for integer combinations belonging to a single bit. As you can imagine, it scales really bad and I can only use it because it’s only 6 bits that are not completely independent. You also have to rename the field names of all cloned points. It’s ugly.

I think bitwise operations, or math ops in general, would be a good addition to processors. Think it should be a feature request, but I am somehow to stupid to add a tag to this.

Cheers
Andy

**Comment by ssoroka** [comment]
take a look at the Starlark processor, it should have everything you need to do arbitrary operations on fields and store them back to the metric in any way you like.

**Comment by sndstar** [comment]
I'm a bit sad that I overlooked this, seems to be just the solution I need.

Thank you!
