### ISSUE TITLE
Input plugin for AWS S3 

### ISSUE THREAD

**Issue by KalyaniDar** [influxdata/telegraf#8553]
I am new to telegraf and I am trying to use Telegraf cloudwatch plugin for retrieving AWS/S3 metrics and the plugin doesn't seem to list any metrics for S3. It works for EC2  but not for S3. Buckets are already present for the credentials I used.

 [[inputs.cloudwatch]]

   region = 'ap-east-1'
   namespace = "AWS/S3"

Kindly help in resolving this issue

**Comment by sjwang90** [comment]
Please check out to see if this helps: https://github.com/influxdata/telegraf/issues/1907#issuecomment-300867109

We reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and someone will assist you.

**Comment by ssoroka** [comment]
FYI see https://github.com/influxdata/telegraf/issues/6617 for the request for an S3 input plugin request (re topic)
