### ISSUE TITLE
Telegraf Input plugins needed for ScaleIO , IBM Cleversafe and NetApp

### ISSUE THREAD

**Issue by KalyaniDar** [influxdata/telegraf#8554]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: I want to read the scaleIO metrics using telegraf. I would be great, if you can develop the Input plugins for the same.
Similarly for IBM Cleversafe and NetApp storage systems

**Comment by powersj** [comment]
Hi,

Without a use-case and additional community interest, we will not be working on these new plugins at this time. If a community member ever decides to work on this we would be happy to review and consider a PR for inclusion.

Thanks!
