### ISSUE TITLE
[procstat] memory_usage are always 0i on linux

### ISSUE THREAD

**Issue by Karmenzind** [influxdata/telegraf#8557]
Here are the latest master code.

![image](https://user-images.githubusercontent.com/17923071/102057965-bf5c2380-3e29-11eb-8f20-471aefb6a36f.png)

As you can see, the method `fillFromStatmWithContext` didn't collect the Swap value so it will always be 0.

I read https://github.com/shirou/gopsutil/issues/620 and it seems an upstream bug. But gopsutil provides another method (https://github.com/shirou/gopsutil/blob/5084874a4c559ab9141f1645e3d3e7e89ce11fcf/process/process_linux.go#L561) which returns the Swap value that comes from `/proc/<pid>/smaps` . Maybe you should consider using this method to fix the issue because this upstream bug exists from a long time ago.

**Comment by powersj** [comment]
Hi,

Sorry, no one has gotten back to you. Thanks for taking the time to file an upstream bug as well!

It looks like we could make this change and do have test coverage of the area that would be affected. I'll mark this as help wanted for now.

Thanks
