### ISSUE TITLE
input.snmp - v3 unknown user name - still creates records with tags as integer

### ISSUE THREAD

**Issue by henriknoerr** [influxdata/telegraf#8558]
I have issues with telegraf output being sent to influx even when failing snmp credentials. Tags and values are somehow random integers - sorry I don't know the markup codes here to makes this look remotely nice 🥇 

`snmpwalk -v 3 -u user -a sha -A password -x aes -X password -l AuthPriv ipaddress CHECKPOINT-MIB::fwFrag-fragments -n ctxname_vsid10
snmpwalk: Unknown user name`

but the value from telegraf query:
`# telegraf --test --config testvs.conf --debug
2020-12-14T12:52:41Z I! Starting Telegraf 1.16.3
2020-12-14T12:52:41Z D! [agent] Initializing plugins
2020-12-14T12:52:41Z D! [agent] Starting service inputs
2020-12-14T12:52:41Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysName.0"
2020-12-14T12:52:41Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "CHECKPOINT-MIB::fwFrag-fragments.0"
 snmp,agent_host=agent_ip,host=telegraf_hostname,hostname=1348648 fwFrag-fragments=1348649i 1607950361000000000
2020-12-14T12:52:41Z D! [agent] Stopping service inputs
2020-12-14T12:52:41Z D! [agent] Input channel closed
2020-12-14T12:52:41Z D! [agent] Stopped Successfully
 snmp,agent_host=agent_ip,host=telegraf_hostname,hostname=915631 fwFrag-fragments=915632i 1607950361000000000`

content of testvs.conf
[[inputs.snmp]]
   agents = [
"agent_ip",
"agent_ip"
]

   timeout = "60s"
   interval = "60s"
   retries = 3
   version = 3

   sec_name = "user"
   auth_protocol = "sha"      # Values: "MD5", "SHA", ""
   auth_password = "password"
   sec_level = "authPriv"     # Values: "noAuthNoPriv", "authNoPriv", "authPriv"
   context_name = "ctxname_vsid10"
   priv_protocol = "AES"         # Values: "DES", "AES", ""
   priv_password = "password"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

[[inputs.snmp.field]]
    name = "fwFrag-fragments"
    oid = "CHECKPOINT-MIB::fwFrag-fragments.0"

Am I hitting a bug? I have of cource checked that credentials matches in the two outputs, and regardless the hostname should not be an integer

Regards,
Henrik

**Comment by henriknoerr** [comment]
Telegraf 1.16.3 (git: HEAD c7f21728)

**Comment by henriknoerr** [comment]
the above issue means that if a user enters wrong credentials to the device / telegraf config the influxdb is still being flooded with millions of unique tags which destroys series

**Comment by henriknoerr** [comment]
ok - I think someone smarter than me described the issue here: https://github.com/influxdata/telegraf/issues/8242

**Comment by Hipska** [comment]
Duplicates #7929
