### ISSUE TITLE
Parsers :: Add OpenTSDB data format support

### ISSUE THREAD

**Issue by sk4mi** [influxdata/telegraf#8559]
### Proposal:

Add  new parser to supports OpenTSDB for input data format. 

http://opentsdb.net/docs/build/html/user_guide/writing/index.html

### Current behavior:

Actually not supported.

### Desired behavior:

Be able to handle pushed OpenTSDB metrics from an app to telegraf input.

### Use case: 

I cannot get metrics with Telegraf from my apps environment who is pushing metrics in OpenTSDB format.
These apps cannot be easily modified so it's for me a better in short term to be able to support this format with Telegraf.

**Comment by powersj** [comment]
next steps: #9690 was nearly complete, looking for someone to pick this back up
