### ISSUE TITLE
SNMP: v3 compatibility

### ISSUE THREAD

**Issue by bobbynaylor** [influxdata/telegraf#856]
Hi,

When will v3 authentication for SNMP be introduced?
The only thing holding me back from trying this tool is the fact it does not currently support v3. So I'm stuck with collectd.

**Comment by titilambert** [comment]
@bobbynaylor Good question !
I don't have any stuff which support snmpv3 (no needs, so hard to justify such development :/)
But, I can try to do it on my spare time... This means I can't give you any ETA :/

**Comment by phemmer** [comment]
The new SNMP plugin (#1389) supports SNMP v3

**Comment by sparrc** [comment]
this is now available in 1.0 RC 1 with the new SNMP plugin, please see here to download the latest version: https://github.com/influxdata/telegraf#linux-deb-and-rpm-packages, and [the changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md) for details on the new SNMP plugin.
