### ISSUE TITLE
Mysql input plugin needs tests

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#8561]
### Current behavior:
The mysql plugin has very few tests.  The existing unit tests cover only narrow parsing tasks.  There are a couple integration tests related to connecting.  There are no tests related to gathering metrics.

related: #6132 

### Desired behavior:
Unit tests covering the functionality of the plugin.  Include mocking the response from mysql so tests can cover metric generation.

We also need integration tests that check the names and types of values received from mysql.  This plugin's fields and field types depend on what it receives from mysql.  There have been multiple bugs in telegraf related to the types changing between mysql versions (#5529 #5055).  The integration test should check the names and types of fields so we can know when a field type has changed before a user files a bug.

**Comment by powersj** [comment]
next steps: wait for #10036 to land.
