### ISSUE TITLE
Grok parser unit test is failing intermittently

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#8563]
The unit test TestAdvanceFieldName in plugins/parsers/grok is failing intermittently.  Since the tests are run during CI on every PR, the failing unit test often prevents the other CI steps from running.

Example test failure:

https://app.circleci.com/pipelines/github/influxdata/telegraf/2530/workflows/6b057500-1fd0-4bca-95dc-642c29827c13/jobs/71550

**Comment by sspaink** [comment]
Looks like this was resolved by: https://github.com/influxdata/telegraf/commit/717d329af8f4ad55fc7f0a8bbb917e6c50d26323 ? I'm guessing this was a direct commit, didn't see a PR associated with it. The CI test insights also haven't reported this as flaky in the past few months, closing.
