### ISSUE TITLE
Add cmdline as a field in procstat plugin

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/telegraf#8566]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
    Adding `cmdline` as a field in procstat plugin
### Current behavior:
 `cmdline` can only be added as a tag
### Desired behavior:
 option to add `cmdline` as a field or tag
### Use case: 
Adding `cmdline` as a tag can introduce a very high cardinality in databases like influxdb because if you're running 5-10 shell scripts or java programs which show as `shell` or `java` as`process_name` you are bound to need `cmdline` as mentioned here https://github.com/influxdata/telegraf/issues/1873 but it comes with a cost . Therefore just like `pid` there should be an option to allow `cmdline` as a field as well . So if we use `pattern` as a way to get all java programs in a system we can identify them in `cmdline` as a field without having to bear the cost of high cardinality by having `cmdline` as a tag . I'm talking about a case where there are tens of thousands of hosts .

**Comment by reimda** [comment]
Closing in favor of using the converter plugin.  See https://github.com/influxdata/telegraf/pull/8567#issuecomment-763227148
