### ISSUE TITLE
v0.11.0 "service telegraf version" not working

### ISSUE THREAD

**Issue by s1m0** [influxdata/telegraf#857]
The init.d script has a small bug in the version case.
Currently it is missing the '-' in front of the version option:-
```
    version)
        $daemon version
        ;;
```
It should be 
```
    version)
        $daemon -version
        ;;
```
which produces the correct output
```
$ service telegraf version
Telegraf - Version 0.11.0
```

**Comment by sparrc** [comment]
thanks @s1m0 for letting us know!
