### ISSUE TITLE
Telegraf for macOS should be signed

### ISSUE THREAD

**Issue by patgmac** [influxdata/telegraf#8580]
### Proposal:

Apple has a hard requirement in current versions of macOS for binaries to be signed and notarized. This FR is to start signing the telegraf binary with a valid Apple certificate and notarize as needed. Here is some documentation from Apple on this topic: [https://developer.apple.com/support/code-signing/](url). 

This would ideally mean someone at a company level obtaining an company developer account from developer.apple.com, which is $300/year. Personal accounts could be used at $99/year but the signing would appear in that persons name. 

### Current behavior:
When running telegraf on macOS Big Sur, the following error messages appear: 

<img width="372" alt="Screen Shot 2020-12-16 at 3 54 12 PM" src="https://user-images.githubusercontent.com/614564/102405888-c6b13780-3fb7-11eb-8fe1-aa01cf00b4d0.png">

<img width="328" alt="Screen Shot 2020-12-16 at 3 54 34 PM" src="https://user-images.githubusercontent.com/614564/102405901-cb75eb80-3fb7-11eb-8157-1c46ec106c96.png">

### Desired behavior:

telegraf should run without error. 

### Use case: 

For continued use of telegraf on the macOS platform, it will need to be signed and notarized.

**Comment by sjwang90** [comment]
@darinfisher Can you provide any feedback for this? See if there's any overlap with the discussions you're having with the Windows signature stuff?

**Comment by patgmac** [comment]
So what are the chances of this happening?

**Comment by sjwang90** [comment]
@patgmac We actually have just purchased the certs for this and are just starting to work on getting this implemented in the Telegraf build.

**Comment by patgmac** [comment]
> @patgmac We actually have just purchased the certs for this and are just starting to work on getting this implemented in the Telegraf build.

Great news. I hope by "purchased the certs" that means a "paid Apple developer account" which is required for singing apps, not like a regular cert purchased elsewhere. And being that this would require building on Apple hardware, would this also help with #4801 ?

**Comment by darinfisher** [comment]
@patgmac Yes, the certificates are from our Apple developer account.
