### ISSUE TITLE
redis5.0.8  NOAUTH Authentication required

### ISSUE THREAD

**Issue by zhanghongxia4725** [influxdata/telegraf#8582]
servers = ["tcp://XXX.XXX.XX.XXX:6379"]
#
#   ## Optional. Specify redis commands to retrieve values
#   # [[inputs.redis.commands]]
#   # command = ["get", "sample-key"]
#   # field = "sample-key-value"
#   # type = "string"
#
#   ## specify server password
 password = "XX"
执行 telegraf -config redis.conf --input-filter redis --output-filter opentsdb:influxdb -test
报错
2020-12-17T09:07:22Z I! Starting Telegraf 1.17.0
2020-12-17T09:07:22Z E! [inputs.redis] Error in plugin: NOAUTH Authentication required.
2020-12-17T09:07:22Z E! [telegraf] Error running agent: input plugins recorded 1 errors
[root@test5-centos7 telegraf.d]# telegraf -config redis.conf --input-filter redis --output-filter opentsdb:influxdb -test
2020-12-17T09:11:04Z I! Starting Telegraf 1.17.0
2020-12-17T09:11:04Z E! [inputs.redis] Error in plugin: NOAUTH Authentication required.
section if available.

https://docs.influxdata.com/telegraf
https://github.com/influxdata/telegraf/tree/master/docs

-->

**Comment by helenosheaa** [comment]
It looks like you may not have provided the correct authentication details / password for redis in your telegraf.conf

For support questions we encourage you to use our [Community Page](https://community.influxdata.com/) or our [Community Slack Channel](https://influxcommunity.slack.com/archives/CH99HUH8V)
