### ISSUE TITLE
telegraf should be able to report its existing version

### ISSUE THREAD

**Issue by CHANDU677493** [influxdata/telegraf#8595]
As an operator, I should be able to check to query/understand how many of each version of telegraf agents are reporting in.

Proposal:
Current behavior:
Desired behavior:
Use case:
If I have 4,000 telegraf agents on 1.X and I'm performing an upgrade to 1.Y, I would like to ask/use InfluxDB to understand if all 4,000 agents are running 1.Y. If they are not all 1.Y, how many, and which are still 1.X.

Can I have a quick solution or suggestion here to get the existing version of domain servers?

**Comment by jimmyseto** [comment]
@CHANDU677493 - can you extract the version from the User-Agent header?

https://github.com/influxdata/telegraf/blob/0731585d614e3463f30fd217978e543704eeae07/plugins/outputs/influxdb/http.go#L142
