### ISSUE TITLE
gNMI for Nokia and Huawei devices

### ISSUE THREAD

**Issue by dobicz** [influxdata/telegraf#8597]
Hi,

gNMI supported only Cisco devices?

I need to use for a Nokia SR-7750 and Huawei devices.

Tks,

Paulo

**Comment by kb70** [comment]
Hi,

don't know about Huawei devices, but GNMI subscription to Nokia SR devices works without problems.
What's missing are embedded/dynamic tags, but that's something which is already worked on, see https://github.com/influxdata/telegraf/pull/8344 or https://github.com/influxdata/telegraf/pull/7484

br,
Kurt
