### ISSUE TITLE
Add missing RabbitMQ queue metrics

### ISSUE THREAD

**Issue by philomory** [influxdata/telegraf#8599]
### Proposal:

The `rabbitmq_queue` measurement should have the following additional fields added:

* `messages_deliver_no_ack`
* `messages_deliver_no_ack_rate`
* `messages_get`
* `messages_get_rate`
* `messages_get_no_ack`
* `messages_get_no_ack_rate`

We already have `messages_deliver` and `messages_deliver_get`, but, `messages_deliver_get` is defined as `messages_deliver + messages_deliver_no_ack + messages_get + messages_get_no_ack`. It's weird to expose one of the subset metrics but not the others.

### Current behavior:

Only `messages_deliver` and `messages_deliver_get` (and corresponding `*_rate` metrics) are exposed

### Desired behavior:

All four "subordinate" metrics (and corresponding `*_rate` metrics) are exposed.

### Use case:

Among other things, you need this to get an accurate view of message rejection rates: `messages_ack` includes only messages that were _explicitly_ acknowledged, not messages that were auto-acknowledged due to being consumed in no-ack mode. RabbitMQ doesn't expose a metric for message rejection, but you can calculate it as `(messages_deliver + messages_get) - (messages_ack + messages_unack)`.

Plus it's just silly to expose an aggregate metric alongside only one of the four metrics it's aggregated from.

**Comment by powersj** [comment]
next steps: look to add the requested fields

**Comment by sspaink** [comment]
@philomory are you still interested in seeing this feature request implemented?
