### ISSUE TITLE
Add timestamp option to postgres_extensible to handle log like queries.

### ISSUE THREAD

**Issue by tfoldi** [influxdata/telegraf#8601]
## Feature Request

Add `timestamp` option to `postgres_extensible` to handle log like queries.

_I am about to send a PR, so you do not have to implement it - just don't hate that much_

### Proposal:

add `timestamp` option for `query` configuration such as:

```
  ## Structure :
  ## [[inputs.postgresql_extensible.query]]
  ##   sqlquery string
  ##   version string
  ##   withdbname boolean
  ##   tagvalue string (comma separated)
  ##   measurement string
  ##   timestamp string
```

in case timestamp column is defined, then the data point's timestamp will be parsed from that database column. If not specified, it will be as of today, using the current time.

### Current behavior:

The data point's timestamp is always the current time.

### Desired behavior:

Give users the possibility to decide if the timestamp can be retrieved from a column (just as you can do it for tag_set). 

### Use case: 

Many apps log their actions into databases. In that case, each log line will be associated with the log insertion time instead of query execution time.

Simple use case, I want to quantify my Redshift Spectrum unload executions. The table definition is: https://docs.aws.amazon.com/redshift/latest/dg/r_STL_UNLOAD_LOG.html . If I want to check how many rows were inserted at what time, I need `end_time` as `timestamp` in my data point.

**Comment by sjwang90** [comment]
Closed in #8602
