### ISSUE TITLE
input.swap in/out empty - Docker container

### ISSUE THREAD

**Issue by bugsyb** [influxdata/telegraf#8603]
Swap in/out reports zeros (always):
 in=0i,out=0i
Even if swap gets usage reported correctly bytes/percentage free/used.
Can't find how the in/out is collected (swapstats?) and if it is a missing mount/command or maybe a limitation how it works => gets info of swap in/out only at the time of running telegraf.

Expectation is that between runs of telegraf we would find out how much more swap in/out has been done to properly record it in InfluxDB.

It is Telegraf 1.16.3 (git: HEAD c7f21728) in docker container with mounts as below:
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_MOUNT_PREFIX: /hostfs

    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
    - /:/hostfs:ro

Suspicion is that it might be somehow related to container, but /sys/proc are properly mounted and ENV settings passed.

Not sure how to troubleshoot if further (strace?).

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you yet. If you run this without docker are you still seeing the issues? I'm curious if the `pswpin` and `pswpout` fields are in your `/proc/vmstat` file.

Thanks!
