### ISSUE TITLE
Telegraf + vSphere. VMs vs Datastores

### ISSUE THREAD

**Issue by Jasomeca** [influxdata/telegraf#8606]
I have Telegraf v1.16. With TIG last versions (Dec/2020)

I use Telegraf to **capture data from Vsphere**, and it works fine.

I can know in an ESXi server, which are the VMs that are running.

But I can't know in a DataStore, which VMs are the ones that are hosted.

Would it be easy to fix or add this?

Thank you

**Comment by jorgedlcruz** [comment]
Hello,
There is nothing at the moment that relates a VM with a Datastore, you can bind a VM to a Host, cluster, or vcenter, but not to a datastore. It is not a bug but maybe more a feature request?

**Comment by sspaink** [comment]
@Jasomeca are you still interested in seeing this feature request implemented?
