### ISSUE TITLE
Internal plugin not increasing errors values, it stops gathering metrics instead. 

### ISSUE THREAD

**Issue by adam0war** [influxdata/telegraf#8608]
### Relevant telegraf.conf:

```toml
[[processors.converter]]
  [processors.converter.tags]
    integer = ["fieldX_*"]
```
### System info:
 - Centos 8
 -  Linux centos8 4.18.0-80.11.2.el8_0.x86_64
 - Telegraf 1.16.3

### Steps to reproduce:
1. Use converter plugin to convert field type from string to int.
2. Type string value instead integer.

### Expected behavior:
Telegraf drops problematic metrics,increase value of errors accordingly to number metrics dropped and keeps gathering all other metrics. 
> internal_process,alias=conv,domain_name=host.name,host=host.name,processor=converter,errors=**X**i 1608555986000000000

### Actual behavior:
telegraf --test gives error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f9332a]

goroutine 10 [running]:
github.com/influxdata/telegraf/plugins/processors/converter.(*Converter).convertTags(0xc0001a3800, 0x2f59ae0, 0xc0001f0690)
	/go/src/github.com/influxdata/telegraf/plugins/processors/converter/converter.go:179 +0xa2a
github.com/influxdata/telegraf/plugins/processors/converter.(*Converter).Apply(0xc0001a3800, 0xc00030e420, 0x1, 0x1, 0xc0000a3260, 0x1, 0xc000272c00)
	/go/src/github.com/influxdata/telegraf/plugins/processors/converter/converter.go:85 +0x7a
github.com/influxdata/telegraf/plugins/processors.(*streamingProcessor).Add(0xc0002863e0, 0x2f59ae0, 0xc0001f0690, 0x2f4aa80, 0xc00000eee0, 0x1, 0x101)
	/go/src/github.com/influxdata/telegraf/plugins/processors/streamingprocessor.go:35 +0x81
github.com/influxdata/telegraf/models.(*RunningProcessor).Add(0xc0001a3980, 0x2f59ae0, 0xc0001f0690, 0x2f4aa80, 0xc00000eee0, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/models/running_processor.go:95 +0x106
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc0001ea2f0, 0xc000286880)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:559 +0x156
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors
	/go/src/github.com/influxdata/telegraf/agent/agent.go:554 +0x90`

Telegraf not getting any metrics despite working telegraf.service with error log message:  
2020-12-21T13:00:01Z E! [agent] Error writing to outputs.http:: Post "https://host.address:9443/": EOF

**Comment by ssoroka** [comment]
This sounds like an issue we had in 1.15, which is fixed in 1.16.0 and 1.15.4. I'm not able to replicate it with 1.16.3, or the latest 1.17. Seems like your best course is to upgrade to the latest and make sure you're not on a version before 1.15.4
