### ISSUE TITLE
aws ec2 instance scheduled maintenance 

### ISSUE THREAD

**Issue by danielmotaleite** [influxdata/telegraf#8611]
## Feature Request
I'm looking for a metric that reports ec2 instance scheduled maintenance on ondemand instances. 

### Proposal:
A new metric for ec2_scheduled_maintenance_seconds , taken from the aws meta-data info

$ curl   http://169.254.169.254/latest/meta-data/events/maintenance/scheduled 
[ {
  "NotBefore" : "1 Jan 2021 02:00:00 GMT",
  "Code" : "instance-stop",
  "Description" : "The instance is running on degraded hardware",
  "EventId" : "instance-event-07a1c1c08b77d4bf1",
  "State" : "active"
} ]

more info in 
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/monitoring-instances-status-check_sched.html#viewing_scheduled_events

### Use case:
Anyone that used aws EC2 instances had times where the underlying host had problems and managing this via the aws email notifications is troublesome, it is hard to know exactly what instances have problems, until when they need to be replaced, if they were already replaced. Having a metric we can setup proper alerts and have then closed when resolved

**Comment by ssoroka** [comment]
Is this something you could do through CloudWatch? We already have an input plugin for that.
