### ISSUE TITLE
 Telnet Input plugin

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#8619]
## Feature Request

Opening a feature request kicks off a discussion.

### Use case:
Receiving data via telnet would be useful for polling equipment or applications for which SNMP/HTTP has an undesirable effect on performance.
Another situation is when work is carried out in a high load network, where priority is given to simpler protocols.
Metrics can be obtained from the response using a combination of a parser and processors.

In my case, this is software that provides real-time billing data processing.

**Comment by Hipska** [comment]
Hi @M0rdecay, I understand your concerns and have faced the same issues as you.

But it would be very difficult to make a generic Telnet plugin as each type of device will have different commands and output to process.

Solution could be to create an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) specific for this use-case or use the [exec](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec) plugin. What do you think?
