### ISSUE TITLE
Google BigQuery Output Plugin

### ISSUE THREAD

**Issue by gkatzioura** [influxdata/telegraf#8630]
## Feature Request

BigQuery is a serverless, highly scalable, and cost-effective data warehouse designed to help you turn big data into informed business decisions

### Proposal:

Implementation of a BigQuery plugin for output.

### Desired behavior:

The telegraph metrics will get mapped to a corresponding table in a BigQuery Dataset. The fields and tags would be fields in a BigQuery table with the corresponding data types. Timestamp should be a mandatory field.

### Use case: 

BigQuery can be used as a data warehouse. Can be handy for data that get in silo status or for processing vast amounts of data. Also is very well integrated with the GCP ecosystem.

**Comment by helenosheaa** [comment]
Closing from pr #8634
