### ISSUE TITLE
telegraf run a period with  skip_database_creation = true, error as follows

### ISSUE THREAD

**Issue by zhanghongxia4725** [influxdata/telegraf#8631]
2020-12-31T01:05:00Z W! DEPRECATED: the jolokia plugin has been deprecated in favor of the jolokia2 plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2)
2020-12-31T01:14:09Z W! [inputs.ÿÿÿÿem] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [agent] ["outputs.influxdb"] did not complete within its flush interval
2020-12-31T01:14:42Z W! [inputs.ÿÿÿÿem] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.redis] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.ÿÿÿ] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.gbase] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.diskio] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.ÿÿÿÿel] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.ÿÿÿÿbase] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z W! [inputs.ÿÿÿÿesses] Collection took longer than expected; not complete after interval of 20s
2020-12-31T01:14:42Z E! [ÿÿÿÿuts.influxdb] When writing to [http://0.0.0.0:8086]: failed doing req: Post "http://0.0.0.0:8086/write?db=telegraf": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020-12-31T01:14:42Z E! [agent] Error writing to outputs.influxdb: could not write any address
fatal error: stack size not a power of 2

runtime stack:
runtime.throw(0x2c87563, 0x1b)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.stackalloc(0x80038400, 0x0, 0x0)
	/usr/local/go/src/runtime/stack.go:336 +0x35e
runtime.copystack(0xc0002f0000, 0x7fffffff80038400)
	/usr/local/go/src/runtime/stack.go:851 +0x7c
runtime.shrinkstack(0xc0002f0000)
	/usr/local/go/src/runtime/stack.go:1178 +0x13d
runtime.scanstack(0xc0002f0000, 0xc000067e98)
	/usr/local/go/src/runtime/mgcmark.go:815 +0x56e
runtime.markroot.func1()
	/usr/local/go/src/runtime/mgcmark.go:245 +0xc6
runtime.markroot(0xc000067e98, 0x1425)
	/usr/local/go/src/runtime/mgcmark.go:218 +0x310
runtime.gcDrain(0xc000067e98, 0xb)
	/usr/local/go/src/runtime/mgcmark.go:1109 +0x118
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1979 +0x191
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1116

goroutine 7 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc00006ef60 sp=0xc00006ef58 pc=0x4722c0
runtime.gcBgMarkWorker(0xc000066800)
	/usr/local/go/src/runtime/mgc.go:1945 +0x1be fp=0xc00006efd8 sp=0xc00006ef60 pc=0x420e1e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00006efe0 sp=0xc00006efd8 pc=0x4740a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1839 +0x77

goroutine 1 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc0002ee028)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0002ee020)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc000010160, 0x317e580, 0xc00018f140, 0x1, 0x1)
	/root/go-odbc/telegraf/agent/agent.go:198 +0x5c5
main.runAgent(0x317e580, 0xc00018f140, 0x46364d0, 0x0, 0x0, 0x46364d0, 0x0, 0x0, 0x0, 0x0)
	/root/go-odbc/telegraf/cmd/telegraf/telegraf.go:207 +0x706
main.reloadLoop(0x46364d0, 0x0, 0x0, 0x46364d0, 0x0, 0x0, 0xc000305d08, 0x0, 0x0, 0xc000305d08, ...)
	/root/go-odbc/telegraf/cmd/telegraf/telegraf.go:110 +0x267
main.run(...)
	/root/go-odbc/telegraf/cmd/telegraf/telegraf_posix.go:7
main.main()
	/root/go-odbc/telegraf/cmd/telegraf/telegraf.go:361 +0x71e

goroutine 18 [runnable]:
go.opencensus.io/stats/view.(*worker).start(0xc000194410)
	/root/go-odbc/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
	/root/go-odbc/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 10 [syscall, 10 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 23 [select, 10 minutes]:
main.reloadLoop.func1(0xc000186360, 0xc000540000, 0xc0001591f0)
	/root/go-odbc/telegraf/cmd/telegraf/telegraf.go:97 +0xae
created by main.reloadLoop
	/root/go-odbc/telegraf/cmd/telegraf/telegraf.go:96 +0x1fe

goroutine 11 [chan receive]:
github.com/influxdata/telegraf/agent.(*Agent).runOutputs(0xc000010160, 0xc000208a20, 0x0, 0x0)
	/root/go-odbc/telegraf/agent/agent.go:774 +0x2b9
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc0002ee020, 0xc000010160, 0xc000208a20)
	/root/go-odbc/telegraf/agent/agent.go:152 +0x65
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/root/go-odbc/telegraf/agent/agent.go:150 +0x4f3

goroutine 12 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc0002ee038)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0002ee030)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/influxdata/telegraf/agent.(*Agent).runInputs(0xc000010160, 0x317e580, 0xc00018f140, 0xbff366cccf845348, 0x499fa56, 0x45f9100, 0xc000208a40, 0x0, 0x0)
	/root/go-odbc/telegraf/agent/agent.go:330 +0x39f
github.com/influxdata/telegraf/agent.(*Agent).Run.func5(0xc0002ee020, 0xc000010160, 0x317e580, 0xc00018f140, 0xbff366cccf845348, 0x499fa56, 0x45f9100, 0xc000208a40)
	/root/go-odbc/telegraf/agent/agent.go:192 +0xab
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/root/go-odbc/telegraf/agent/agent.go:190 +0x5b4

goroutine 24 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flushLoop(0xc000010160, 0x317e580, 0xc000268000, 0xc000190180, 0x314bdc0, 0xc00055a000)
	/root/go-odbc/telegraf/agent/agent.go:818 +0x20e
github.com/influxdata/telegraf/agent.(*Agent).runOutputs.func1(0xc000558000, 0x4a817c800, 0x0, 0xc000010160, 0x317e580, 0xc000268000, 0xc000190180)
	/root/go-odbc/telegraf/agent/agent.go:770 +0xe5
created by github.com/influxdata/telegraf/agent.(*Agent).runOutputs
	/root/go-odbc/telegraf/agent/agent.go:764 +0x1a5

goroutine 25 [select]:
github.com/influxdata/telegraf/agent.(*RollingTicker).run(0xc00055a000, 0x317e580, 0xc000268040, 0xc0001940f0)
	/root/go-odbc/telegraf/agent/tick.go:252 +0x128
github.com/influxdata/telegraf/agent.newRollingTicker.func1(0xc00055a000, 0x317e580, 0xc000268040, 0xc0001940f0)
	/root/go-odbc/telegraf/agent/tick.go:240 +0x76
created by github.com/influxdata/telegraf/agent.newRollingTicker
	/root/go-odbc/telegraf/agent/tick.go:238 +0x165

goroutine 13 [runnable (scan)]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017c980, 0x317e580, 0xc00017c940, 0xc0000a7b80)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017c980, 0x317e580, 0xc00017c940, 0xc0000a7b80)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 14 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208b20, 0xc0000a72c0, 0x314bd80, 0xc00017c980, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:462 +0x125
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208b20, 0x314bd80, 0xc00017c980, 0x4a817c800, 0xc0000a72c0)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 15 [runnable]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017ca00, 0x317e580, 0xc00017c9c0, 0xc0000a7c70)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017ca00, 0x317e580, 0xc00017c9c0, 0xc0000a7c70)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 16 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208b80, 0xc0000a7450, 0x314bd80, 0xc00017ca00, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:462 +0x125
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208b80, 0x314bd80, 0xc00017ca00, 0x4a817c800, 0xc0000a7450)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 34 [runnable]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017ca80, 0x317e580, 0xc00017ca40, 0xc0000a7d60)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017ca80, 0x317e580, 0xc00017ca40, 0xc0000a7d60)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 35 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208be0, 0xc0000a7540, 0x314bd80, 0xc00017ca80, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:462 +0x125
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208be0, 0x314bd80, 0xc00017ca80, 0x4a817c800, 0xc0000a7540)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 36 [select]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017cb80, 0x317e580, 0xc00017cb00, 0xc0000a7e50)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017cb80, 0x317e580, 0xc00017cb00, 0xc0000a7e50)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 37 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce(0xc000010160, 0x319bc80, 0xc000208c40, 0xc0000a75e0, 0x314bd80, 0xc00017cb80, 0x4a817c800, 0x0, 0x0)
	/root/go-odbc/telegraf/agent/agent.go:494 +0x1e5
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208c40, 0xc0000a75e0, 0x314bd80, 0xc00017cb80, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:464 +0x192
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208c40, 0x314bd80, 0xc00017cb80, 0x4a817c800, 0xc0000a75e0)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 38 [select]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017cc00, 0x317e580, 0xc00017cbc0, 0xc0000a7f40)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017cc00, 0x317e580, 0xc00017cbc0, 0xc0000a7f40)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 39 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce(0xc000010160, 0x319bc80, 0xc000208ca0, 0xc0000a7680, 0x314bd80, 0xc00017cc00, 0x4a817c800, 0x0, 0x0)
	/root/go-odbc/telegraf/agent/agent.go:494 +0x1e5
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208ca0, 0xc0000a7680, 0x314bd80, 0xc00017cc00, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:464 +0x192
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208ca0, 0x314bd80, 0xc00017cc00, 0x4a817c800, 0xc0000a7680)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 40 [runnable]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017cc80, 0x317e580, 0xc00017cc40, 0xc0002fa050)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017cc80, 0x317e580, 0xc00017cc40, 0xc0002fa050)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 41 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208d00, 0xc0000a7720, 0x314bd80, 0xc00017cc80, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:462 +0x125
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208d00, 0x314bd80, 0xc00017cc80, 0x4a817c800, 0xc0000a7720)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

goroutine 42 [runnable]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc00017cd00, 0x317e580, 0xc00017ccc0, 0xc0002fa140)
	/root/go-odbc/telegraf/agent/tick.go:85 +0x134
github.com/influxdata/telegraf/agent.newAlignedTicker.func1(0xc00017cd00, 0x317e580, 0xc00017ccc0, 0xc0002fa140)
	/root/go-odbc/telegraf/agent/tick.go:62 +0x76
created by github.com/influxdata/telegraf/agent.newAlignedTicker
	/root/go-odbc/telegraf/agent/tick.go:60 +0x1a7

goroutine 43 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208d60, 0xc0000a77c0, 0x314bd80, 0xc00017cd00, 0x4a817c800)
	/root/go-odbc/telegraf/agent/agent.go:462 +0x125
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0xc0002ee030, 0xc000010160, 0x317e580, 0xc00018f140, 0x319bc80, 0xc000208d60, 0x314bd80, 0xc00017cd00, 0x4a817c800, 0xc0000a77c0)
	/root/go-odbc/telegraf/agent/agent.go:326 +0xbf
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs
	/root/go-odbc/telegraf/agent/agent.go:324 +0x14a

**Comment by Jagularr** [comment]
Hi, so with your config it seems to work for me. Have you tried manually running a write command to your influxdb api and seeing if it has an error (without telegraf)?

**Comment by ssoroka** [comment]
Haven't heard back from you on this. It's not clear what the problem is as you haven't provided the OS, Telegraf version, or Go version being used. If you'd like us to look into it further, please feel free to open a new issue with these additional details. 

Thanks!
