### ISSUE TITLE
OPC UA input plugin stops Telegraf if OPC server not found

### ISSUE THREAD

**Issue by zeldalegends** [influxdata/telegraf#8632]
If the plugin does not find the OPC server, e.g., in case of temporary unavailability of the PLC running it, instead of just warning inside the console and continuing monitoring the other input plugins (as it happens, e.g., for Modbus, MQTT, etc., which just warn the user and let the application run), it causes the entire Telegraf application to stop.  The console shows a message like this, end exit:

2020-12-31T02:53:31Z I! dial tcp 192.168.***.***:4840: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

It would be desirable that the plugin just send this message and Telegraf continues run, to let it monitor all the other plugins, waiting for the OPC server possible reconnection, instead of closing the application and interrupting the whole monitoring.

**Comment by sjwang90** [comment]
@zeldalegends Can you please provide the relevant portion of your Telegraf config?

Please check out if it's also related to #3723

**Comment by zeldalegends** [comment]
Hi, yes, it happened with a BR Automation PLC, the list of OPC nodes id very long, but I can reduce it here:

[[inputs.opcua]]
  name = "ec"
  endpoint = "opc.tcp://192.168.***.***:4840"
  security_policy = "None"
  security_mode = "None"
  nodes = [
    {name="gBMS1.batteryPackVoltage", namespace="6", identifier_type="s", identifier="::AsGlobalPV:gBMS1.batteryPackVoltage", data_type="float", description="Measured battery pack voltage (V)"},
    ...
]

If the PLC is not connected, after few seconds telegraf exits with that error in OP. I am investigating if it is connected with #3723 but I am not sure. Thanks for your reply.

**Comment by sjwang90** [comment]
Thanks for the information. Let's close this for now as it does relate to the general issue of the agent not starting if the input/output cannot be connected to. I've linked this issue to #3723.
