### ISSUE TITLE
MODBUS Input UINT64 Stops Telegraf in Windows

### ISSUE THREAD

**Issue by yonas124** [influxdata/telegraf#8633]
Telegraf immediately closes if configured with UINT64 data type holding register in modbus input.

Is it because it's currently not supported?

**Comment by Jagularr** [comment]
Would you be able to provide the config you're experiencing this with as well as any logging telegraf outputs before the error?

**Comment by yonas124** [comment]
If line 3992 is commented out, it works right away. If don't, telegraf immediately closes without any visible log.

`{ measurement ="SDM",	name = "E",      byte_order = "ABCD",   data_type = "UINT64", scale=1.0,  address = [30513,30514,30515,30516]},
 `

Below is the .conf file
[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/5758638/telegraf.conf.txt)

**Comment by Jagularr** [comment]
So after running it with that config it appears that your line in question has a byte_order length of 4 and an address length of 4. The logic in the init for this plugin errors out when the length of the byte_order isn't exactly twice the length of the address array. This appears to be what's shutting your telegraf instance down.

`invalid byte order 'ABCD' and address '[30513 30514 30515 30516]'  in 'holding_register' - 'E'`

**Comment by yonas124** [comment]
So I should write ABCDABCD?

It makes sense a little bit because each register in the array is 2 bytes, so 8 bytes in total. But usually other application just use ABCD because it is unlikely that consecutive bytes have different order.

**Comment by srebhan** [comment]
@yonas it should be `ABCDEFGH` actually, but with the latest master you can also set `ABCD` (and friends) for all register-length IIRC. Does that help?

**Comment by yonas** [comment]
@yonas124 An @mention meant for you was sent to me in #8633
