### ISSUE TITLE
Example of querying data collected by Telegraf Openweathermap plugin

### ISSUE THREAD

**Issue by linucks** [influxdata/telegraf#8642]
## Feature Request

Examples of queries using InfluxQL to extract forecasts from the data collected by the Telegraf Openweathermap plugin to be added to the [README.md](https://github.com/influxdata/telegraf/blob/master/README.md)

### Proposal:
Examples of queries using InfluxQL to extract forecasts from the data collected by the Telegraf Openweathermap plugin to be added to the [README.md](https://github.com/influxdata/telegraf/blob/master/README.md)

### Current behavior:
From what I can work out, the Telegraf plugin runs periodically (10 minutes by default) and collects the weather forecasts for up to 120 hours in the future in 3 hour increments. It assigns each forecast a "forecast" variable, which is the number of hours in advance of when the forecast was made that it is valid. As the plugin runs periodically, the same time period will have multiple forecasts applied to it, from 120 hours in the future, down to 3 hours in the future.

As such, a single timestamp could have up to 40 forecasts assigned to it. I'd like to get the most recent forecast from now going forward so that I can display them in Grafana. I've tried grouping the forecasts by timestamp using the following query:

``` 
influx -precision rfc3339  -database "telegraf" -execute "select * from weather where time > now() group by time(1ms)"
```

but this generates the error:
```
ERR: GROUP BY requires at least one aggregate function
GROUP BY requires at least one aggregate function
```
Beyond that, it's not clear to me how to extract the forecasts.

### Desired behavior:
Better documentation and example FluxQL queries.

### Use case: 
Currently it's difficult to use the plugin as it's not clear how to use the data, and every tutorial I've seen on InfluxQL and Openweathermap doesn't use the supported plugin, which seems a shame. If the plugin had standardised use cases, it would facilitate use by more people.

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you yet.

Going forward I would suggest users take a look at Flux over InfluxQL. Previous users of InlfuxQL can check out a [comparison here](https://docs.influxdata.com/influxdb/cloud/reference/syntax/flux/flux-vs-influxql/) and new uses of Flux can look at this [getting started](https://docs.influxdata.com/flux/v0.x/get-started/) docs.

I don't see us including any flux or influxql specific docs in the Telegraf repo itself, so I am going to close this.
