### ISSUE TITLE
Include metrics from golang's new runtime/metrics package in telegraf's internal plugin

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#8645]
The golang 1.16 release will include support for new metrics exported by the go runtime.  Currently telegraf's internal plugin uses runtime.ReadMemStats().  The new package supersedes ReadMemStats and adds new metrics.  Telegraf should consider switching to the new package once the build uses golang 1.16.

https://tip.golang.org/pkg/runtime/metrics/

**Comment by powersj** [comment]
next steps: look into add this as we are now on 1.17 and soon to be 1.18
