### ISSUE TITLE
Update gosnmp in snmp_legacy and snmp_trap plugins

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#8660]
The snmp_trap plugin was recently updated to use a new version of gosnmp.  The snmp and snmp_legacy plugins need to be updated too.

**Comment by Hipska** [comment]
I think you read that wrong, #8588 updated the library for `snmp` plugin. What still needs to be done is updating it for `snmp_trap`.

Should `snmp_legacy` still be considered since it will be removed in 2.0? (see #2320)

**Comment by reimda** [comment]
Oops, my mistake.  I updated the issue title to reflect that we need to update snmp_trap still.  snmp_legacy isn't as important because it's deprecated, but until it's removed it's probably worth updating.

**Comment by Hipska** [comment]
The only problem is that `snmp_legacy` doesn't have any tests. So how to deal with that?

**Comment by Hipska** [comment]
Seems like @sspaink will fix this in #9203
