### ISSUE TITLE
AggregatingOutput not accept or reject the  metrics

### ISSUE THREAD

**Issue by cao2358** [influxdata/telegraf#8666]
AggregatingOutput must use metric.Accept() or metric.Reject() when Add() func is calling，because the kafka_consumer use the trackMetric to confirm every metric is complete resolve
so can add accept func when to Add, like this

```
if output, ok := ro.Output.(telegraf.AggregatingOutput); ok {
		ro.aggMutex.Lock()
		output.Add(metric) 
		metric.Accept() //this is recommend, mostly can judge to use Accept() or Reject() by the Add() func return value with a bool 
		ro.aggMutex.Unlock()
		return
	}
```

or resolve in every AggregatingOutput Add() func by yourself

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you in a while.

I am not sure I understand what the issue or feature you are proposing here. If you could provide a bit of context as to what you are trying to do and the problem you are trying to solve that would be great.

Thanks!
