### ISSUE TITLE
inputs.bind with bind 9.16+ not collecting "malloced" and uptime.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#8667]
### Current behavior:
Under "bind_memory" only "total_use", "in_use", "context_size", "block_size", "lost" are available.
Additionally, there is no "version" or "uptime"

### Desired behavior:
New in 9.16 is "Malloced" which is how much memory is actually being used.
Also, it would be nice to know what version of bind was being used and when it was
last booted / reconfigured / et cetera.

e.g from
urls = ["http://localhost:8053/json/v1"]
gather_memory_contexts = false
gather_views = true

{
  "json-stats-version":"1.5",
  "boot-time":"2021-01-07T07:33:35.511Z",
  "config-time":"2021-01-07T07:33:35.547Z",
  "current-time":"2021-01-10T06:55:17.124Z",
  "version":"9.16.10",

....
  "memory":{
    "TotalUse":8399929638,   <--- This is more like "total mallocs and monotonically increases.
    "InUse":36667632,
    "Malloced":178297664,
    "BlockSize":112459776,
    "ContextSize":40260024,
    "Lost":0,

...

**Comment by powersj** [comment]
next steps: look into adding the requested metrics during collection if they exist.

**Comment by powersj** [comment]
Hi,

I have put up PR #12165, which adds the malloced and version tag. If you could give that PR a shot and let me know I would appreciate it. Test artifacts should be uploaded in 20-30mins. Also where is the uptime field? I am only making these changes to the JSON-based stats given they are supported on newer versions as well.

Thanks!
