### ISSUE TITLE
inputs.opcua: Add metric for datatype

### ISSUE THREAD

**Issue by aaashishbakshi** [influxdata/telegraf#8669]
## Feature Request
Multiple attributes to pass from opcua-input plugin 

### Proposal:
I'm new to Telegraf, So, Using opcua-input plugin, I only get 1 value from the identitfier which is its main value but I also want to monitor other attributes like its datatype with it

### Current behavior:
opcua,host=sysadmin-Virtual-Machine Tartget_Production_Achieved=true,Quality="OK (0x0)" 1610354410000000000
opcua,host=sysadmin-Virtual-Machine Tartget_Production_Count=0i,Quality="OK (0x0)" 1610354410000000000

### Desired behavior:
opcua,host=sysadmin-Virtual-Machine Tartget_Production_Achieved=true, datatype=boolean, Quality="OK (0x0)" 1610354410000000000
opcua,host=sysadmin-Virtual-Machine Tartget_Production_Count=0i, datatype=int16, Quality="OK (0x0)" 1610354410000000000

### Use case: 
I want to monitor multiple device and handling the data can be easier if I know what datatype it is.

**Comment by sjwang90** [comment]
This issue is still important to get in Telegraf and if anyone in the community is interested in working on this please feel free to open a PR and we can get it review and merged. Thanks 😄

**Comment by sjwang90** [comment]
@aaashishbakshi Just trying to understand your use case better for prioritization. Can you share what other attributes besides datatype you'd would like to read in? How would having the datatype be beneficial, when the data is read into InfluxDB it stores the data type.

**Comment by caallinson** [comment]
I'm willing to work on this
