### ISSUE TITLE
Custom time interval for metrics

### ISSUE THREAD

**Issue by rohit482** [influxdata/telegraf#8670]
We are using Telegraf to take metrics data into Splunk , we want to fetch the metric data for different metrices in different intervals. 
i.e. For telegraf.disk --30 sec for telegraf.system --120 sec . As of now  we found that we can only setup single interval for all the metrics , Do we have any feature available in telegraf where we can make changes based on our requirements and collect the metrics in different time intervals.

we are using  TA-telegraf-amd64  to pull data in our Setup , Below the git url:

https://github.com/guilhemmarchand/TA-telegraf-amd64

**Comment by Hipska** [comment]
You can have different interval for each configured plugin..
