### ISSUE TITLE
Modbus Serial RTU: support multiple slaves on the same bus

### ISSUE THREAD

**Issue by ict-one-nl** [influxdata/telegraf#8676]
## Feature Request

Support multiple slaves (with independent register configurations) for Modbus RTU over serial.

### Current behavior:

Only one slave can be used.

### Desired behavior:

Multiple slaves can be used.

### Use case: 

Almost every bus has more than one slave on it, in my case it's a set of 7 Eastron SDM energy meters and a SmartEVSE car charger.

**Comment by sjwang90** [comment]
Closing in favor of #7523
