### ISSUE TITLE
Implement httpxml plugin alongside httpjson

### ISSUE THREAD

**Issue by neographikal** [influxdata/telegraf#8677]
## Feature Request

There is the https://github.com/influxdata/telegraf/tree/master/plugins/inputs/httpjson plugin
Really useful, but my data is in XML format. Can this plugin be adapted to parse xml and do exactly the same

### Proposal:
Implement httpxml plugin

### Current behavior:
-

### Desired behavior:
Same as httpjson but for xml

### Use case: 
Monitoring API's that give numbers of results for a query and to monitor that.

**Comment by sjwang90** [comment]
Closing this as we're already following issue #1758 and have an XML parser PR that you can use with `inputs.http`.

Also we have deprecated the httpjson plugin and you should use `inputs.http` with `data_format = "http"` if you're going to parse JSON - which you'll eventually set the data format to `xml` when the parser is completed.

**Comment by neographikal** [comment]
Thank you, didn't notice that! Will look into it
