### ISSUE TITLE
Add Prometheus Remote Write Parser

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8682]
### Proposal:
Add prometheus remote write parser to use a `data_format` for input plugins
### Current behavior:
None - only [Prometheus remote write serializer](https://github.com/influxdata/telegraf/tree/master/plugins/serializers/prometheusremotewrite)

### Desired behavior:
Add prometheus remote write parser where users can read in data with setting `data_format = "prometheusremotewrite"` in their input plugin configuration.

### Use case: 
Allows users to parse prometheus remote_write format with Telegraf and output to InfluxDB. 

There are currently no capabilities in InfluxDB 2.x for prometheus remote_write. With an Telegraf parser, users could transform their prometheus remote_write data into line protocol with Telegraf and send it into InfluxDB 2.x.  This would be a key enhancement for users being able to migrate from InfluxDB 1.x to 2.x. See https://github.com/influxdata/influxdb/issues/17958

**Comment by aleksey-novikov** [comment]
Basic implementation: [https://github.com/influxdata/telegraf/pull/8702]
