### ISSUE TITLE
Jti_openconfig_telemetry aggregate interface monitoring network traffic 

### ISSUE THREAD

**Issue by stefi994** [influxdata/telegraf#8686]
Is there a way to graph the interface traffic of ae interface? 

I am not finding any way, since I guess the data collected with the plugin is not corelated with the aggregate interface, only with the physical interfaces.

**Comment by powersj** [comment]
Hi,

Sorry no one has gotten back to you. Can you give an example of this `ae` interface, your telegraf config, and the logs you are seeing?

Thanks!
