### ISSUE TITLE
docs: Add context to broker list selection in Kafka output plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8687]
Need clearer context on how the selection is made of which broker to connect to when a list of brokers is configured. And details on the behavior when that broker becomes unavailable.

Need clarity from question opened: https://github.com/Shopify/sarama/issues/1872

**Comment by powersj** [comment]
next steps: follow up on the upstream bug and get clarity on what the behavior is. Then add this to the docs for the kafka output.

**Comment by powersj** [comment]
For the docs: 

sarama reads in the metadata it was provided by brokers for further operations it sticks to whatever the cluster leader is
