### ISSUE TITLE
inputs: intel onboard gpu metrics counters

### ISSUE THREAD

**Issue by testarch-aurk** [influxdata/telegraf#8688]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
It will help if intel onboard GPU metrics can be listed in 
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters
or 
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/intel_powerstat
Please let me know if it is already available in any other inputs.

### Current behavior:
We can see intel gpu metrics on windows performance monitor

### Desired behavior:
It will help if we can pull them to influx and create grafana dashboard for GPU utilization
![IntelGPUwindowsPerfCounters](https://user-images.githubusercontent.com/77410303/104499235-cdc56880-55aa-11eb-9468-0af2e877f727.JPG)

**Comment by testarch-aurk** [comment]
https://software.intel.com/content/www/us/en/develop/documentation/vtune-help/top/analyze-performance/code-profiling-scenarios/gpu-application-analysis.html

**Comment by powersj** [comment]
> https://software.intel.com/content/www/us/en/develop/documentation/vtune-help/top/analyze-performance/code-profiling-scenarios/gpu-application-analysis.html

This is a very involved tool from Intel that lets a user collect and analyze or send the data for analysis. Not something I see us interfacing with via Telegraf.

> We can see intel gpu metrics on windows performance monitor

This is the method I would go down as well. Are you getting metrics?
