### ISSUE TITLE
inputs nginx_vts json error parser

### ISSUE THREAD

**Issue by myc547** [influxdata/telegraf#8691]
env: linux，telegraf:1.17
description：
nginx json format：
{
    "hostName": "test.example.com",
    "nginxVersion": "1.12.2",
    "loadMsec": 1518180328331,
    "nowMsec": 1518256058416,
    "connections": {
        "active": 111,
        "reading": 222,
        "writing": 333,
        "waiting": 444,
        "accepted": 555,
        "handled": 666,
        "requests": 777
    },
"serverZones": {
  "NO~^(new|oms)?(.{4})(.{2})(.+)\w*-*dcloud\.(shop\d+)": {
            "requestCounter": 505,
            "inBytes": 171388,
            "outBytes": 1273382,
            "responses": {
                "1xx": 101,
                "2xx": 201,
                "3xx": 301,
                "4xx": 401,
                "5xx": 501,
                "miss": 22,
                "bypass": 23,
                "expired": 24,
                "stale": 25,
                "updating": 26,
                "revalidated": 27,
                "hit": 28,
                "scarce": 29
            },
            "requestMsec": 12
        }
  }
}
the "NO~^(new|oms)?(.{4})(.{2})(.+)\w*-*dcloud\.(shop\d+)" is a regex , json parser error

**Comment by myc547** [comment]
> @sjwang90 my telegraf.conf 
 [[inputs.nginx_vts]]
#   ## An array of ngx_http_status_module or status URI to gather stats.
   urls = ["http://localhost:80/status/format/json"]

**Comment by sjwang90** [comment]
Can you try whatever your URL pathname as 

`urls = ["http://localhost:80/status"]`

If this still does not resolve the issue please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly. We reserve Telegraf issues for bugs for reproducible problems.

**Comment by feiniao886** [comment]
Encountered the same problem

2022-03-23T15:03:50Z I! Starting Telegraf 1.21.4
2022-03-23T15:03:50Z I! Loaded inputs: nginx_vts
2022-03-23T15:03:50Z I! Loaded aggregators: 
2022-03-23T15:03:50Z I! Loaded processors: 
2022-03-23T15:03:50Z W! Outputs are not used in testing mode!
2022-03-23T15:03:50Z I! Tags enabled: dc=ksord-dc host=10-19-17-43
2022-03-23T15:03:50Z E! [inputs.nginx_vts] Error in plugin: http://localhost:18080/status returned unexpected content type 
2022-03-23T15:03:50Z E! [telegraf] Error running agent: input plugins recorded 1 errors


[[inputs.nginx_vts]]
  ## An array of ngx_http_status_module or status URI to gather stats.
  urls = ["http://localhost:18080/status"]
  ## HTTP response timeout (default: 5s)
  response_timeout = "5s"
