### ISSUE TITLE
Have ARM64 Mac OS X release package

### ISSUE THREAD

**Issue by R-Rudolf** [influxdata/telegraf#8693]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
In the coming releases, have a new row for the new platform/architecture: https://github.com/influxdata/telegraf/releases/tag/v1.17.0

### Current behavior:
Only AMD64 CPU architecture is supported for the Mac OS X Platform.

### Desired behavior:
I can download and easily install/deploy/use the released official binaries, without fuss to compile it.

### Use case: 

To support new&future apple M1 based machines.
Our software needs to be tested on such platforms, to ensure support for the end users.
In our CI we try to monitor all hardware, to early detect issues and help later investigations.
Currently our new hardwares are functioning, and we want to receive telegraf metrics from it.
Our inly option is currently to try to compile it. It is an extra effort, if successful at all.

**Comment by hjuutilainen** [comment]
I would very much like to see a native arm64 telegraf for macOS. Has there been any further development for this?

**Comment by hjuutilainen** [comment]
Now that v1.18.0-rc1 is out and there's support for Go version 1.16, would it be possible to get builds with `GOOS=darwin` and `GOARCH=arm64`?

**Comment by popey** [comment]
Not sure if it's useful, but apparently AWS now have M1 macs in "preview". https://aws.amazon.com/blogs/aws/use-amazon-ec2-m1-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/

**Comment by popey** [comment]
Not sure if it's useful, but apparently AWS now have M1 macs in "preview". https://aws.amazon.com/blogs/aws/use-amazon-ec2-m1-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/
