### ISSUE TITLE
[0.11.0] URL parse for mysql connection string fails with special characters in password

### ISSUE THREAD

**Issue by burdandrei** [influxdata/telegraf#870]
I got "%j+" sequence in my mysql password, and now because url.Parse it fails:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mysql/mysql.go#L225

Per original Package documentation special characters  supported in password and should not be escaped:
https://github.com/go-sql-driver/mysql/blob/master/README.md#password

There is ParseDSN method in package:
https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L245

**Comment by lnkisi** [comment]
Same issue.

**Comment by Maksadbek** [comment]
@burdandrei @lnkisi Thanks for reporting this bug, I will fix it soon.

**Comment by Maksadbek** [comment]
@burdandrei @lnkisi 
Can you provide sample DSN that reproduces this bug ? A password with ```%j+``` sequence works fine for me.

**Comment by burdandrei** [comment]
@Maksadbek well this is strange,
I just tried this ```   servers = ['ttt:1%j+2@tcp(production.db.com:3306)/'] ``` and this worked for me in 1.0 
@lnkisi can you please share your DSN?

**Comment by sparrc** [comment]
see also https://github.com/influxdata/telegraf/issues/1842

**Comment by adityask2** [comment]
Has this issue been fixed? I'm using v1.2.1. Seems like this issue still exists

**Comment by danielnelson** [comment]
@adityask2 The fix above should be in 1.2.1, can you open a new issue and include a sample connection string that replicates your issue.
