### ISSUE TITLE
Percentage used endurance indicator wasn't sent even smart attributes enabled

### ISSUE THREAD

**Issue by Badb0yBadb0y** [influxdata/telegraf#8701]
### Proposal:
The smartctl command like this smartctl -a /dev/sde gives you back many information about the ssd and what I'm interested in is the "Percentage used endurance indicator: 0%".
If you want to take this information in a short output can query like this also:
smartctl -l ssd /dev/sde

### Current behavior:
Even with the smart attributes enables in the config, this indicator hasn't been sent as a metric.
### Desired behavior:
Would be good to have this indicator sent if the smart attributes enabled.

### Use case: 
We are using a storage system with many ssds and it is quite critical to be able to plan when we need to replace the ssds so we can have a rough timeline that we need to order.

**Comment by powersj** [comment]
next steps: look to add this field to the smart plugin

It would be really helpful to see output of the smartctl command with this field.
