### ISSUE TITLE
[inputs.ping] Error in plugin: , exit status 3221225794: X.X.X.X

### ISSUE THREAD

**Issue by redrumdk** [influxdata/telegraf#8704]
Hi All, 

im having this issue with using input ping on windows, using latest build of telegraf, and any version prior. 

We are pinging 201 ip's at an interval of 60 seconds, 
And don't have anything special in the config.

[[inputs.ping]]
## List of urls to ping
urls = [
"X.X.X.X",
"X.X.X.X"  (we have 201 ip's in this list)
] # required
count = 3
timeout = 2.0
method = "exec"
We are running telegraf on an Windows 2016 server, AV disabled, DEP Disabled, FW Disabled, just updated to latest telegraf,

**Comment by redrumdk** [comment]
i found the error, seems when on windows you can't use the Count parameter (ping -c)

**Comment by srebhan** [comment]
@redrumdk can you please post the error you get for the `native` setting!?

**Comment by redrumdk** [comment]
> @redrumdk can you please post the error you get for the `native` setting!?

Using latest nightly with native, with mentioned Merged code.
I get no error in the debug log, but the data saved in the influxdb looks like this

https://ibb.co/kQk8RCm

When I ping a IP which is permanently down, it stille shows as up, and various pack losses.
If you check the screenshot.

**Comment by NZSmartie** [comment]
I have the following config `/etc/telegraf/telegraf.d/inputs.ping.conf`

```toml
[[inputs.ping]]
  ## List of URLs to ping
  urls = ["125.236.192.9", "8.8.8.8", "1.1.1.1"]
```

and `journalctl -u telegraf.service` shows
```
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Starting Telegraf 1.17.1
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Loaded inputs: cpu disk diskio kernel mem ping processes swap system
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Loaded aggregators:
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Loaded processors:
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Loaded outputs: influxdb_v2
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! Tags enabled: host=jump
Jan 28 15:40:10 jump telegraf[1635586]: 2021-01-28T02:40:10Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"jump", Flush Interval:10s
Jan 28 15:40:20 jump telegraf[1635586]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 28 15:40:20 jump telegraf[1635586]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2542a]
Jan 28 15:40:20 jump telegraf[1635586]: goroutine 49 [running]:
Jan 28 15:40:20 jump telegraf[1635586]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc000178460, 0xc000475fc1, 0xd, 0x34ae180, 0>
Jan 28 15:40:20 jump telegraf[1635586]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x18a
Jan 28 15:40:20 jump telegraf[1635586]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc000178460, 0x34ae180, 0xc00000f3a0, 0xc>
Jan 28 15:40:20 jump telegraf[1635586]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x9b
Jan 28 15:40:20 jump telegraf[1635586]: created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
Jan 28 15:40:20 jump telegraf[1635586]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0xd2
```

telegraf keeps crashing constantly until I comment out the `urls = [...` line

**Comment by redrumdk** [comment]
just tried the latest pull request version.
Running telegraf-1.18.0_8b6a3bce_windows_amd64 on Windows 2019

With config

[[inputs.ping]]

List of urls to ping
urls = [
"X.X.X.X", (114 IP's in this list)
]
method = "exec"
count = 4

and still get the "Error in plugin: , exit status 3221225794: X.X.X.X"

**Comment by redrumdk** [comment]
Heeeey, my man. :)
How is it closed, i still get the error using tonight's build  XD

**Comment by redrumdk** [comment]
Still the same error in version 17.3

**Comment by redrumdk** [comment]
same error in v1.18.1

**Comment by toomuchio** [comment]
If you're running this as the SYSTEM user this could be why seems like a common issue with Windows:

Reason:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4017

And the fix:
https://stackoverflow.com/questions/25153262/getting-the-the-application-failed-to-initialize-properly-3221225794-error-exe

**Comment by redrumdk** [comment]
> If you're running this as the SYSTEM user this could be why seems like a common issue with Windows:
> 
> Reason:
> https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4017
> 
> And the fix:
> https://stackoverflow.com/questions/25153262/getting-the-the-application-failed-to-initialize-properly-3221225794-error-exe

it's not an issue on low volume, i have tested using 10 20, 50, 60, 100, for me it starts happening around 105 ip's to ping. 
then it starts to fail with that same error message in bulk.

**Comment by srebhan** [comment]
@redrumdk did you try the suggestion with running it as `local admin` instead of `SYSTEM` user? The two sources mention the limited capacity of heap which might explain why it works with "low volume" but not with a higher number of IPs.

**Comment by DStrand1** [comment]
@redrumdk Is this still an issue on the latest version of Telegraf?
