### ISSUE TITLE
add inputs.snmp.table but telegraf can't work "table is not defined in*snmp.Snmp"

### ISSUE THREAD

**Issue by juri1987** [influxdata/telegraf#871]
config file:
#####################
  [[inputs.snmp.table]]
    name = "sysGlobalHostCpuUsageRatio"
    oid = [".1.3.6.1.4.1.3375.2.1.7.5.2.1.4"]
    sub_table = [".1.3.6.1.4.1.3375.2.1.7.5.2.1.4.1.48"]
#####################

 field corresponding to `table' is not defined in `*snmp.Snmp'

**Comment by titilambert** [comment]
Helli ! Which versiin do you use ?

**Comment by sparrc** [comment]
@juri1987 you need to upgrade your telegraf version
