### ISSUE TITLE
systemctl reload telegraf is not doing hot config and its restarting the Telegraf 

### ISSUE THREAD

**Issue by 02219290** [influxdata/telegraf#8728]
Team,

We are working on Telegraf Ping Plugin and we are in a situation it is not doing hot reload config and loosing the data collection .

We are using "systemctl reload telegraf" but its stopping the data collection, below is from logs:

2021-01-20T13:08:02Z I! Reloading Telegraf config
2021-01-20T13:08:02Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-01-20T13:08:03Z I! Starting Telegraf 1.14.0
**2021-01-20T13:08:03Z I! [**outputs.prometheus_client**] Listening on http://0.0.0.0:9273/metrics**
2021-01-20T13:10:00Z E! [inputs.ping] Error in plugin: lookup vc2coma2519368n.fmr.com on 10.95.161.250:53: no such host

Data collection is happening only after next interval that we have defined in config **(interval=5m)**

Also we have SIGHUP as below in services:
**ExecReload=/bin/kill -HUP $MAINPID**

We have tried this on Docker container as well. But the auto reload is not happening.

Any help with this is much appreciated

**Comment by ssoroka** [comment]
That looks like it's handling it correctly. The interval starts over on reload. What behavior are you expecting?

**Comment by ssoroka** [comment]
If there was something like SIGUSR2 hander to trigger immediate data collection, would that help solve the problem?

**Comment by 02219290** [comment]
> 
> 
> If there was something like SIGUSR2 hander to trigger immediate data collection, would that help solve the problem?

We have the set of servers to monitor Ping check in API end point along with Telegraf config and Telegraf is configured to call the API (remote URL) to get the metrics of those servers and exposing to Prometheus on port 9273.

On normal Telegraf installation on VM we are using below in telegraf.service

**ExecStart=/usr/bin/telegraf -config <URL which have full telegraf config> $TELEGRAF_OPTS
ExecReload=/bin/kill -HUP $MAINPID**

We want Telegraf to perform hot reload config without restarting service or losing data collection regularly, API End point will be keep changing frequently as the servers will be decommissioning or commissioning newly. We don't want to restart the Telegraf service frequently which will loose the data collection

**Comment by 02219290** [comment]
> would that help

Can you please provide more information on SIGUSR2 handler?
