### ISSUE TITLE
Win_services: add exclude filter

### ISSUE THREAD

**Issue by let-thomas** [influxdata/telegraf#8733]
## Feature Request
We would like to monitor all services that should run, i.e. are automatic but down. Developers are adding new services quite often, this means maintaining white-list of services is not easy task. Therefore we would like to monitor all (automatic) services and setup alert when some automatic service is down. Create black-list, i.e. list of services we are not interested in is much more easier.

### Proposal:
[[inputs.win_services]]
  ## Names of the services to exclude from monitoring
  exclude = [
     'cloud-init',
     'WbioSrvc'
  ]
  

### Current behavior:

List of services to monitor. Btw there is bug with listed services and related error when service is not installed. When you are monitoring more same HA cluster with (relatively) dynamic distribution of services -> not manageable task.

### Desired behavior:

List of all service not specified in exclude list.

Might be also interesting to specify services with desired startup mode:
 startup_mode = automatic, automatic_delayed

### Use case: 
(copy from above)
Developers are adding new services quite often, this means maintaining white-list of services is not easy task. Therefore we would like to monitor all (automatic) services and setup alert when some automatic service is down. Create black-list, i.e. list of services we are not interested in is much more easier.

**Comment by sspaink** [comment]
In 1.17.0 the input plugin win_services was updated to support globbing in the service name, maybe that would help clean up the include list until this feature is resolved?

Adding an exclude list could still be a good idea and I think allowing filtering based on "startup_mode" should also be possible.

Could you provide more detail on the bug you mentioned. An error is thrown when you have a service in the include list but it isn't actually running on the system? Wouldn't this be the desired behavior?

**Comment by let-thomas** [comment]
Yes, not really bug but Error in log saying there is no such service.
Globing in our case would not (unfortunately) help. 'Cause '*' will be the mask.

**Comment by syunusic** [comment]
Is there any update on this? I'd love to have an option to include only services that have "startup_mode" equals to 0,1,2,3 (not 4), or exclude if "startup_mode" = 4.

**Comment by sspaink** [comment]
@syunusic there is a open pull request to implement this feature made by @let-thomas, to help get it merged I moved it and you can find it here: #10144. Filtering services by `startup_modes` seems out of scope of this change and should probably be a separate issue and pull request because it will need more design discussion.
