### ISSUE TITLE
Filter/Drop metrics based on tag key

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8739]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Filter and drop metrics/entire series based off a tag key not just tag value. Similar to [measurement filtering](https://docs.influxdata.com/telegraf/v1.17/administration/configuration/#measurement-filtering) like `tagdrop`

### Current behavior:
Could use input plugin + value parser then create a starlark script to filter results from name

### Desired behavior:
add a configuration tag such as `tagkeydrop = "name"`

### Use case: 
For tail plugin: Don't want to store all the log data in InfluxDB, only when line matches certain criteria. Want to be able to "filter" log entries and store data in fields and tags that only match specific log lines.

**Comment by ssoroka** [comment]
This should already be supported by using a wildcard with tagdrop. Even if there is some issue with that, custom logic is supported with starlark, and would be the right way to get custom behavior. Going to close this out.
