### ISSUE TITLE
Rounding the floats (network bandwidth consumers)

### ISSUE THREAD

**Issue by jburdy** [influxdata/telegraf#8740]
## Feature Request
For all my metrics I don't need to have real like 2.35732532342432. The value of 2.36 is very good enough for me and would be minus 4 less long. As far as transport is concerned, it's text that I know, no typed variable. Whether in json, influx line proto etc...

### Proposal:
Have a way (a processor?) to adjust the accuracy by type. Just like we can do for time (ms, s, ...) but for floats.

### Current behavior:
No rounding.

### Desired behavior:
Adjustable roundness.

### Use case:
This is a way to divide the network bandwidth level several times. To know our percentages of disk used, our CPU loads, etc... We don't need to be at the micron level.

Today I do it via the spark language, but it's not nice (and I haven't even found out how to access a real rounding function).

**Comment by powersj** [comment]
Hi,

If you would like to process your data before it leaves Telegraf, my suggestion is to use the starlark processor. With this, you can use a python-like script to change the data including rounding it. As Starlark can fulfill this request, I am going to close this for now.

Thanks
