### ISSUE TITLE
output prometheus_client can not receive prometheus input

### ISSUE THREAD

**Issue by debu99** [influxdata/telegraf#8742]
i have some application listen to 127.0.0.1 only with prometheus metrics endpoint, i want to export the metrics with other system metrics via telegraf, but i can't use prometheus_client output to export the prometheus format metrics, below is my config file
```
[[inputs.prometheus]]
  urls = ["http://127.0.0.1:8080/metrics"]
  metric_version = 2
[[inputs.prometheus]]
  urls = ["http://127.0.0.1:8081/metrics"]
  metric_version = 2
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  collectors_exclude = ["gocollector", "process"]
  export_timestamp = true
```

is this a bug or something i set wrongly?

**Comment by debu99** [comment]
curl -i http://localhost:9273/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Sun, 24 Jan 2021 05:08:08 GMT
Content-Length: 0

**Comment by debu99** [comment]
telegraf 1.16.3 is working, 1.17 not working

**Comment by juddgaddie** [comment]
This appears to be the same as #8719
