### ISSUE TITLE
RPM install on docker centos 7 picks wrong service

### ISSUE THREAD

**Issue by TechnicalMercenary** [influxdata/telegraf#8752]
### System info:

Telegraph Version is the latest.
RPM is `https://repos.influxdata.com/rhel/7/x86_64/stable/telegraf-1.17.0-1.x86_64.rpm`

Using docker and installing telegraf the posttrans scriptlet picks initd and not systemd.  The docker image I'm using is `docker.io/pycontribs/centos:7`

In the script the  test `[[ "$(readlink /proc/1/exe)" == */systemd ]]` doesn't produce the correct value and therefore initd is where telegraf is installed.

### Steps to reproduce:

Follow the Centos Instructions at https://docs.influxdata.com/telegraf/v1.17/introduction/installation/

### Expected behavior:

I would expect that telegraf.service is copied to systemd

### Actual behavior:

telegraf.service is copied to initd

**Comment by powersj** [comment]
next step: determine proper way to check for systemd in a container for rpms. I started to clean up the RPM logic in #10570, but that would still run across this

**Comment by powersj** [comment]
Hi,

I have a PR up to clean up our install logic for the RPM https://github.com/influxdata/telegraf/pull/10570

When you run your container and install telegraf, does it have the directory `/run/systemd/system`? This seems to be the [canonical check for systemd](https://www.freedesktop.org/software/systemd/man/sd_booted.html).
