### ISSUE TITLE
Telegraf does not check if configuration file is valid

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#8753]
Is a little bit silly, but maybe some checks in this direction could be useful.

### Steps to reproduce:

```
./telegraf --test -config telegraf
```
### Expected behavior:

Detect an incorrect config file, output an error and exit.

### Actual behavior:

Telegraf starts normally and consume one CPU.

**Comment by sjwang90** [comment]
@adrianlzt Are you speaking specifically for the `-test` flag? Just want clarification around the feature request.

**Comment by adrianlzt** [comment]
It does not matter.

This is the "problem":
```
/usr/bin/telegraf -config /usr/bin/telegraf
```

Telegraf does not check that it is trying to parse a binary file and starts to consume a lot of CPU an have to be killed with SIGKILL

**Comment by sjwang90** [comment]
Thanks - this is feature is something we're looking to implement in a future larger project. We'll add this as a requirement.

**Comment by Hipska** [comment]
I think there are already open issues that mention the same problem.

Anyway, I want this feature as well!

**Comment by powersj** [comment]
> Telegraf does not check that it is trying to parse a binary file

Ah I did not gather from the original posting that this was the use case. 

```s
❯ ./telegraf -config ./telegraf
^C2022-08-11T21:42:10Z E! [telegraf] Error running agent: Error loading config file ./telegraf: Error parsing data: line 1: invalid TOML syntax
```

It does timeout eventually after it loads the full binary, but this could be handled better.

Next steps: verify if config file to load is text or not (e.g. [IsTextFile](https://pkg.go.dev/golang.org/x/tools/godoc/util#IsTextFile)

**Comment by Hipska** [comment]
I suggest to also run the plugin inits, but not the Start/Gather.. That way you can correctly validate the config file values without also doing an initial collection.

It could still be a wrong config file even while it is valid TOML..

**Comment by Hipska** [comment]
This functionality is finally added with v1.32.0 which now has a command to actually check the config. See https://github.com/influxdata/telegraf/pull/15732
