### ISSUE TITLE
Add XML input data format

### ISSUE THREAD

**Issue by neographikal** [influxdata/telegraf#8757]
## Feature Request

Implement XML data format like the input json parser:
https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json

### Use case: 

Same as the json parser, but not everything is json. XML is a valid file format still. I'd use it for the http input plugin.

**Comment by Hipska** [comment]
Hi, do you think that the parser from #8047 would resolve your request?

**Comment by Hipska** [comment]
After a second look, it seem this is a duplicate of #1758
