### ISSUE TITLE
Statsd should expose "separator" configuration

### ISSUE THREAD

**Issue by kri5** [influxdata/telegraf#876]
When using templates using statsd, it seems that it uses a graphite parser, which is good because it reuses existing code.

The main issue here is that https://github.com/influxdata/telegraf/commit/e619493ece6b26078eac4fbebc9a948de9476af0 introduces a change in the way it is working, as it uses a "." separator, instead of a "_" previously.

The best would be to provide a way of specifying a separator in the statsd configuration.

Looking at the tests i don't know how they are still passing.

I have no good idea on how to implement that.

**Comment by sparrc** [comment]
Can you be more specific? What is not expected? Give some input/output examples

**Comment by kri5** [comment]
@sparrc Considering the documentation of the module, it's expected to have something like that

> `templates = [`
`    "cpu.* measurement.measurement.region",`
`    "mem.* measurement.measurement.host"`
`]`
which would result in the following transformation:

>`cpu.load.us-west:100|g`
=> `cpu_load,region=us-west 100`

>`mem.cached.localhost:256|g`
=> `mem_cached,host=localhost 256`

But it result in having dotted measurement like

`mem.cached.localhost:256|g`
=> `mem.cached,host=localhost 256`

**Comment by sparrc** [comment]
@kri5 What version are you running and can you show me your config? that should not happen if the `convert_names = true` option is set

**Comment by kri5** [comment]
@sparrc i do not use convert_names, as that is not what i want to do here

it seems caused because the graphite template parser is called with a '.' separator https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L434 

Before https://github.com/influxdata/telegraf/commit/e619493ece6b26078eac4fbebc9a948de9476af0 the parser was called with '_'

convert_names implies that my dashes '-' would transform to '__' and that's not the behaviour i expect.

**Comment by sparrc** [comment]
okay, that option was added because some users actually _want_ to keep the dot-separated metrics. So I think this issue is basically about separating out two options in the config:

1. convert . -> _
1. convert - -> __

**Comment by kri5** [comment]
@sparrc i was more thinking about adding a separator config that would be passed to the graphite parser, to be consistent with the statsd and graphite template documentation, instead of simply passing ".".

**Comment by sparrc** [comment]
that's a good idea too, and actually should be fairly simple

**Comment by veverjak** [comment]
@sparrc I have for example metric `system.io.r_s` -> my metric separator is `.` 
What should be my config to keep it this way?

**Comment by veverjak** [comment]
ok, I can see the problem is in ouput plugin - 

https://github.com/influxdata/telegraf/blob/master/plugins/outputs/datadog/datadog.go#L74  - this is really weird default behavior...

**Comment by sparrc** [comment]
can you open a separate issue for that?

**Comment by veverjak** [comment]
done https://github.com/influxdata/telegraf/issues/1024
