### ISSUE TITLE
inputs.ping: Old/default "exec" method segfaults

### ISSUE THREAD

**Issue by asantoni** [influxdata/telegraf#8766]
I just upgraded to Telegraf 1.17.1 and it segfaults for me now due to a bug in inputs.ping. It looks like a new "native" method of pinging was introduced in this release, but for compatibility the default is to use the old "exec" method. However, the old exec method seems to segfault. I tested the new native method and that works. Would be great if the old method could be fixed for compatibility. Thank you!

### Relevant telegraf.conf:

```toml
[[inputs.ping]]
   urls = ["www.google.com", "www.apple.com", "www.redacted.com", "ams-ix.net"]

```

### System info:

Telegraf 1.17.1 on Ubuntu 18.04 and 16.04

### Docker

No Docker.

### Steps to reproduce:

1. Use the config above
2. Run telegraf. It will segfault when it runs the ping check. See log below.

### Expected behavior:
 
It used to work and ping the hosts successfully.

### Actual behavior:

It segfaults!

### Additional info:

Log:
```
Jan 28 05:34:10 host telegraf[23893]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 28 05:34:10 host telegraf[23893]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2542a]
Jan 28 05:34:10 host telegraf[23893]: goroutine 80 [running]:
Jan 28 05:34:10 host telegraf[23893]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc000170380, 0xc000222a21, 0xa, 0x34ae180, 0xc000202ec0)
Jan 28 05:34:10 host telegraf[23893]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x18a
Jan 28 05:34:10 host telegraf[23893]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc000170380, 0x34ae180, 0xc000202ec0, 0xc000222a21, 0xa)
Jan 28 05:34:10 host  telegraf[23893]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x9b
Jan 28 05:34:10 host  telegraf[23893]: created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
Jan 28 05:34:10 host telegraf[23893]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0xd2
```

**Comment by mkowalski** [comment]
I can confirm, the same happens using `telegraf:latest` (ID `d9cdf69cbb5f`, version 1.17.1)

**Comment by dimdin** [comment]
All of my site monitoring is down, since telegraf stopped working on all instances due to this ping bug. It crashes and after a few restarts it stops crashing but does nothing.

My config is using the default "exec" mode, and I a duplicating the parameters in the command line because after introducing '-4' to ping only ipv4 addresses it ignores them.
```
[[inputs.ping]]
  urls = [.....]
  count = 5
  ping_interval = 0.5
  timeout = 1.0
  deadline = 8
  arguments = ["-4","-c","5","-i","0.5","-W","1","-w","8"]
```
The problem affects all architectures running latest debian stable.
intel and arm examples of the crash:
```
2021-01-28T09:36:30Z I! Tags enabled: host=pi-base
2021-01-28T09:36:30Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"pi-base", Flush Interval:10s
2021-01-28T09:36:30Z I! [inputs.socket_listener] Listening on udp://127.0.0.1:4444
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130c860]
goroutine 100 [running]:
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0x51f3950,0x5523281, 0x7, 0x27a4828, 0x500a5a0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x11c0, 0x27a4828, 0x500a5a0, 0x5523281, 0x7)
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0x51f3950, 0x27a4828, 0x500a5a0, 0x5523281, 0x7)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0xc0
created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0x9
```
```
2021-01-28T09:33:50Z I! Starting Telegraf 1.17.1
2021-01-28T09:33:50Z I! Loaded inputs: cpu dns_query docker exec (2x) file influxdb ntpq ping socket_listener
2021-01-28T09:33:50Z I! Loaded aggregators:
2021-01-28T09:33:50Z I! Loaded processors:
2021-01-28T09:33:50Z I! Loaded outputs: influxdb
2021-01-28T09:33:50Z I! Tags enabled: host=nuc
2021-01-28T09:33:50Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"nuc", Flush Interval:10s
2021-01-28T09:33:50Z I! [inputs.socket_listener] Listening on udp://127.0.0.1:4444
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2542a]
goroutine 128 [running]:
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc0001f8380, 0xc000211001, 0x7, 0x34ae180, 0xc000206760)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x18a
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc0001f8380, 0x34ae180, 0xc000206760, 0xc000211001, 0x7)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x9b
created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0xd2
```

**Comment by Alcarin** [comment]
Same here, before downgrading to previouse version I lost a lot of data in many servers due this bug.

Jan 28 09:13:00 localhost telegraf[5427]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 28 09:13:00 localhost telegraf[5427]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92f030f]
Jan 28 09:13:00 localhost telegraf[5427]: goroutine 376 [running]:
Jan 28 09:13:00 localhost telegraf[5427]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc59ce10, 0xc8ef651, 0x21, 0xa824ec0, 0xc688ac0)
Jan 28 09:13:00 localhost telegraf[5427]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x13f
Jan 28 09:13:00 localhost telegraf[5427]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc59ce10, 0xa824ec0, 0xc688ac0, 0xc8ef651, 0x21)
Jan 28 09:13:00 localhost telegraf[5427]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x85
Jan 28 09:13:00 localhost telegraf[5427]: created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
Jan 28 09:13:00 localhost telegraf[5427]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0x91
Jan 28 09:13:00 localhost systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 28 09:13:00 localhost systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jan 28 09:13:00 localhost systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Jan 28 09:13:00 localhost systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 61.
Jan 28 09:13:00 localhost systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 28 09:13:00 localhost systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Starting Telegraf 1.17.1
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Loaded inputs: cpu disk diskio kernel mem ping (69x) processes snmp (61x) swap system
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Loaded aggregators:
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Loaded processors: converter regex
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Loaded outputs: influxdb
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! Tags enabled: nms=localhost
Jan 28 09:13:00 localhost telegraf[5949]: 2021-01-28T09:13:00Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"", Flush Interval:10s
Jan 28 09:14:00 localhost telegraf[5949]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 28 09:14:00 localhost telegraf[5949]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92f030f]
Jan 28 09:14:00 localhost telegraf[5949]: goroutine 363 [running]:
Jan 28 09:14:00 localhost telegraf[5949]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc887a70, 0xc8845d1, 0x22, 0xa824ec0, 0xc880be0)
Jan 28 09:14:00 localhost telegraf[5949]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x13f
Jan 28 09:14:00 localhost telegraf[5949]: github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc887a70, 0xa824ec0, 0xc880be0, 0xc8845d1, 0x22)
Jan 28 09:14:00 localhost telegraf[5949]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x85
Jan 28 09:14:00 localhost telegraf[5949]: created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
Jan 28 09:14:00 localhost telegraf[5949]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0x91
Jan 28 09:14:00 localhost systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 28 09:14:00 localhost systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jan 28 09:14:00 localhost systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Jan 28 09:14:00 localhost systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 62.
Jan 28 09:14:00 localhost systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 28 09:14:00 localhost systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Starting Telegraf 1.17.1
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Loaded inputs: cpu disk diskio kernel mem ping (69x) processes snmp (61x) swap system
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Loaded aggregators:
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Loaded processors: converter regex
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Loaded outputs: influxdb
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! Tags enabled: nms=localhost
Jan 28 09:14:00 localhost telegraf[6470]: 2021-01-28T09:14:00Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"", Flush Interva

**Comment by leonv024** [comment]
same issue here. Just updated and now it's broken. My server metric monitoring still works but Ping and SNMP broke.

```2021-01-28T14:25:27Z I! Starting Telegraf 1.17.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2542a]

goroutine 16 [running]:
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc00018c380, 0xc00031fc41, 0xb, 0x34ae180, 0xc00053a000)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x18a
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc00018c380, 0x34ae180, 0xc00053a000, 0xc00031fc41, 0xb)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x9b
created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0xd2```
