### ISSUE TITLE
sctp monitoring support request

### ISSUE THREAD

**Issue by prakpm** [influxdata/telegraf#8773]
Hi Telegraf! 

We have recently started using Grafana/InfluxDB/Telegraf monitoring system for our capacity tests on Telecommunication Application Servers. Though we can monitor TCP/UDP Protocols and the sockets we are really missing SCTP monitoring feature. SCTP being widely used in Telecom industry, we would appreciate if telegraf can support SCTP protocol monitoring for no. of sockets established, netstat - Send-Q/Recv-Q etc.

**Comment by sjwang90** [comment]
We reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
