### ISSUE TITLE
inputs.multifile input plugin not working

### ISSUE THREAD

**Issue by Arunika** [influxdata/telegraf#8780]
Hi All, I am trying to use multiple file plugin to gather data from multiple jsons and then forward it to wavefront output plugin. My input plugin looks like below :

[[inputs.multifile]]

  [[inputs.multifile.file]]
    file = "C:/Program Files/Telegraf/a.json"
	dest = "abc"
    data_format = "json"
	conversion = "string"
  [[inputs.multifile.file]]
    file = "C:/Program Files/Telegraf/b.json"
    data_format = "json"
	dest = "abc"
	conversion = "string"

Data is not send to the output/wavefront, Any pointer to solve this?

**Comment by srebhan** [comment]
Do you have any error message in telegraf? Do you see any output if you send the data to `stdout` using the `file` output plugin? Sorry for asking but my crystal-ball is broken. ;-)

**Comment by srebhan** [comment]
@Arunika is this issue still valid? Did you solve your problem?

**Comment by ravinayag** [comment]
@Arunika , Have you tried this?
```

[[inputs.tail]]
  ## files to tail.
  files = ["C:/Program Files/Telegraf/**.json"]
```
