### ISSUE TITLE
input.snmp influxdb ifName

### ISSUE THREAD

**Issue by solune** [influxdata/telegraf#8781]
### Relevant telegraf.conf:

```
[[inputs.snmp]]
  interval = "60s"
  agents = [ "sw54rg1:161" ]
  version = 2
  community = "public"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "temp"
    oid = ".1.3.6.1.2.1.99.1.1.1.4.25"
    conversion = "float"
  [[inputs.snmp.table]]
    name = "switch-interfaces"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true
```

### System info:
telegraf 1.17.2
influxdb 1.8.3

### Steps to reproduce:
influxdb request filtering on ifName, ex:
SELECT non_negative_derivative(mean("ifHCInOctets"), 1s) FROM "switch-interfaces" WHERE "hostname" = 'sw54rg1' AND "ifDescr" = 'A17'  AND $timeFilter GROUP BY time($__interval), "ifDescr" fill(null)

### Expected behavior:
The request give results

### Actual behavior:

Since telegraf 1.7.1 and still in 1.7.2, the request return no data.
When i do 'SELECT * FROM "switch-interfaces" WHERE "hostname" = 'sw54rg1' AND time >= now() - 1h' I can see a new column named 'ifName_1' filled with with good values an 'ifName' is empty.

Why telegraf have created this new column ?

**Comment by solune** [comment]
according to this doc : https://docs.influxdata.com/influxdb/v1.8/troubleshooting/frequently-asked-questions/#tag-and-field-key-with-the-same-name it's beause telegraf has made a tag and a field key with name ifName. Why ?

**Comment by Hipska** [comment]
Could you run the config with `--test`? We only need to see some of the `switch-interfaces` lines. That way we can see what Telegraf would have sent to InfluxDB.
