### ISSUE TITLE
Proxmox VE cluster monitoring plugin

### ISSUE THREAD

**Issue by niasar** [influxdata/telegraf#8789]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add capability to Proxmox input to get cluster state
### Current behavior:
Proxmox input plugin can't get metrics about cluster state
### Desired behavior:
Proxmox plugin can be used to monitor cluster setups
### Use case: 

Current implementation of Proxmox input plugin have no ability to monitor current state of a cluster (quorum presence, online node count, etc). Proxmox is very popular virtualization platform and it used in clustered setups pretty often. You need to response very quickly in case your cluster is experienced any quorum-related problem, so monitoring current cluster state is essential thing when you operating this kind of setup. Currently I forced to use a custom script in combination with exec plugin to get this data to InfluxDB and it will be nice if Telegraf maintainers add this ability to specialized plugin.

**Comment by powersj** [comment]
Hi,

Would you be willing to share your script with the community here to help others, but also for us to evaluate how this could get added to Telegraf?

Thanks!
