### ISSUE TITLE
Add retry support on inputs

### ISSUE THREAD

**Issue by gallofeliz** [influxdata/telegraf#8794]
## Feature Request

Telegraf calls a lot of inputs to have metrics but some of them are network or third-party dependant and can ponctualy fail. I would like a retry feature to request to the input (for example http) x times.

### Current behavior:

- The http input calls an API that depends on a third-party API
- The API returns an error or reach a timeout
- Telegraf writes an error in the logs and skip the http input
- At the end, an error is in the logs and it misses a point in the measurement

### Desired behavior:

- The http input calls an API that depends on a third-party API
- The API returns an error or reach a timeout
- Telegraf retries x times
- In case of success, there is not error in logs and the measurement is complete
- In case of error, there is an error in logs and it misses a point in the measurement
- At the end, only few sometimes there is an error in the logs and it misses a point on the metric ; small network errors or very short problems don't impact the measurement

### Use case:

I call with http intermediate API that calls bluetooth objects or third-party API that are unstable but just need to retry sometimes. I need to add a retry support on every intermediate API that cost work, and some existing API projects cannot be easily extended.

It's not a big impact as it misses some points in the measurement, but I need to increase the Grafana alert time to avoid "NO DATA" alert, and to ignore errors in Telegraf logs (that are collected to another measurement).

Retry is a very basic feature and can improve the quality of the collect.

Thanks,
Regards

**Comment by sjwang90** [comment]
retry feature implemented here: https://github.com/influxdata/telegraf/pull/8803
