### ISSUE TITLE
Win_services: case sensitive in service names

### ISSUE THREAD

**Issue by sbuldakov** [influxdata/telegraf#8796]
Hi all,

I've just met with strange (from point of view of administrator of windows systems) behavior of win_services input plugin. If I'm using capitalization that differ from service name win_services plugin can't find out this service.

For example, _Get-Service "iisadmin"_ and _Get-Service "IISADMIN"_ give equal result. 
But win_service can find out only last service.

**Comment by powersj** [comment]
Hi,

The Windows services are looked up using Go's windows services tools. There may not be anything Telegraf can even do about this, but the next step would be to confirm that this is how the library works and if there are any other options there.

Thanks

**Comment by srebhan** [comment]
@sbuldakov can you please test the binary in #14684, available once CI finished the build!? Let me know if this solves your request!
