### ISSUE TITLE
README minimal Go version is too minimal (1.14 instead of 1.13 is requred)

### ISSUE THREAD

**Issue by gsauthof** [influxdata/telegraf#8799]
The `README.md` currently [reads](https://github.com/influxdata/telegraf/blob/9166a16577502d7accc3c209c9dbd9e4fa7e5c5a/README.md):

> Install Go >=1.13 (1.15 recommended)

However, building with go 1.13 fails.

### System info:

CentOS 7 with Go version 1.13

### Steps to reproduce:

1. git clone https://github.com/influxdata/telegraf.git
2. git checkout release-1.17
3. make telegraf

### Expected behavior:

A successful build of the telegraf build.

### Actual behavior:

Build fails with:

```
build github.com/influxdata/telegraf/cmd/telegraf: cannot load hash/maphash: cannot find module
providing package hash/maphash
```

### Additional info:

From the Golang changelog I gather that `hash/maphash` which is used e.g. in [`metric/series_grouper.go`](https://github.com/influxdata/telegraf/blob/3b8df55b9c8c15353b8778ab3a19f0b1a5021d29/metric/series_grouper.go#L5) appeared in Go 1.14: https://golang.org/doc/go1.14

Thus, it seems necessary to increase the minimum version requirement in `README.md` from 1.13 to 1.14.

**Comment by sjwang90** [comment]
Thanks for pointing this out. We removed Go 1.13 support in the past. 

Opened a PR with the fixes.
