### ISSUE TITLE
Building Telegraf 1.17.2 fails due to unknown-revision error of the wireguard dependency

### ISSUE THREAD

**Issue by gsauthof** [influxdata/telegraf#8800]
### System info:

Telegraf 1.17.2, Fedora 33, go version 1.15.6

(build is started in a completely pristine `$HOME` without any go environment variables (such as `GOPATH`) set)

### Steps to reproduce:

1. git clone https://github.com/influxdata/telegraf.git
2. git checkout release-1.17
3. make telegraf

### Expected behavior:

The telegraf binary is build sucessfully.

### Actual behavior:

```
go build -mod=mod -ldflags " -X main.commit=74011e22 -X main.branch=release-1.17 -X main.goos=linux -X main.goarch=amd64 -X main.version=1.17.2" ./cmd/telegraf
go: golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20200205215550-e35592f146e4 requires
	golang.zx2c4.com/wireguard@v0.0.20200121: reading golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200121: unknown revision v0.0.20200121
make: *** [Makefile:90: telegraf] Error 1
```

### Additional info:

I did the same steps 1 or 2 weeks ago (on another system) where it succeeded! Perhaps some referenced git repository changed their published tags or something like that?

**Comment by ricrug** [comment]
I don't think it's related to the telegraf version at all. I've tried it with other versions and it still happens.

**System info:**
Telegraf 1.17.2/1.14.5/..., Fedora 33, go version 1.15.6

**Comment by ricrug** [comment]
Problem solved! A round of applause for me!
```export GOPROXY=https://proxy.golang.org,direct```
```export GOSUMDB=sum.golang.org```

than `go mod download` will work!
I hope it works for everyone and that I have been helpful!

**Comment by gsauthof** [comment]
Hm, as someone who hasn't that much experience with Go modules, it isn't obvious to me what's behind this and why @ricrug settings work around it. Can somebody post a short explanation?

**Comment by sspaink** [comment]
@gsauthof I've created a pull request to resolve this issue that includes two links with more information on the problem, I recommend looking there to learn more: #9620.

@ricrug thank you for providing a workaround!
