### ISSUE TITLE
ping plugin broken by commit c237989

### ISSUE THREAD

**Issue by 0x0a11c0de** [influxdata/telegraf#8805]
[This commit](https://github.com/influxdata/telegraf/commit/c2379896312ba0582a1e7a9be79f9dc826a955a2#diff-1e6bedd7550baa6b9ff9469e1c2d12cfde952f9acce4b2abd928b4c46e6962d2) introduced two problems:

1. [It sets the go-ping timeout to the per-ping timeout value](https://github.com/influxdata/telegraf/blob/c2379896312ba0582a1e7a9be79f9dc826a955a2/plugins/inputs/ping/ping.go#L173). The timeout in `go-ping` is not the per-ping timeout. [It is the timeout for exiting the pinger](https://github.com/go-ping/ping/blob/b6486c6f1f2d7aa4e017c9571730d467c4d4a2b8/ping.go#L372). The `go-ping` timeout should be set to the `deadline` value. `go-ping` does not appear to have a way to set the per-ping timeout value.
2. It removed the sorting of the rtts before calculating the percentiles, which means the percentile calculation cannot work.

**Comment by psarossy** [comment]
Was this change actually released?

The documentation is updated, stating that as of 1.7.0 the percentiles are available, but when running the 1.7.2 docker image I get:
```
│ 2021/02/17 18:52:12 E! Error parsing /etc/telegraf/telegraf.conf, line 25: field corresponding to `percentiles' is not defined in `*ping.Ping'                                                                                               │
```
