### ISSUE TITLE
Azure Active Directory (AAD) authentication support in SQL Server input plugin

### ISSUE THREAD

**Issue by avinash-nigam** [influxdata/telegraf#8808]
## Feature Request

Enable support for Azure Active Directory (AAD) authentication in the SQL Server input plugin

### Proposal:

- Azure SQL Database supports 2 main methods of authentication: [SQL authentication and AAD authentication](https://docs.microsoft.com/en-us/azure/azure-sql/database/security-overview#authentication). The recommended practice is to [use AAD authentication when possible](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-overview). AAD is a more modern authentication protocol, allows for easier credential/role management, and can eliminate the need to include passwords in a connection string
- To enable support for AAD authentication, we can leverage the existing AAD authentication support in the [SQL Server driver for Go](https://github.com/denisenkom/go-mssqldb#azure-active-directory-authentication---preview)

### Current behavior:

- The only authentication method currently supported by the SQL Server input plugin is SQL authentication

### Desired behavior:

- AAD authentication would also be supported by the SQL Server input

### Use case: 

- The recommended practice for Azure SQL Database is to [use AAD authentication when possible](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-overview). AAD is a more modern authentication protocol, allows for easier credential/role management, and can eliminate the need to include passwords in a connection string
- Many organizations using Azure SQL Database have security policies that require AAD authentication. Such organizations would be unable to use telegraf to monitor Azure SQL Database without support for AAD authentication

**Comment by avinash-nigam** [comment]
@ssoroka @srebhan @Trovalo @denzilribeiro - Thoughts?
@masree @coquagli @bhsu-ms - FYI

**Comment by srebhan** [comment]
Reviewed the PR. The feature makes totally sense to me.
