### ISSUE TITLE
SQL Server Plugin issues

### ISSUE THREAD

**Issue by VasuBalakrishnan** [influxdata/telegraf#881]
I'm trying to collect metrics from a SQL Server 2008 R2 instance. 

I'm getting the following errors:

1. String or binary data would be truncated.

    This is due to fact that some of the databases on this server happens to have name more than 64 characters. Refer to sqlDatabaseProperties variable. Can we make DatabaseName field in #Databases table match sysname datatype which is nvarchar(128).

2. Invalid column name 'pages_kb'

   MemoryClerk query is failing as the field doesn't exist in [SQL 2008 R2](https://blogs.msdn.microsoft.com/sqlosteam/2012/07/11/memory-manager-surface-area-changes-in-sql-server-2012/). Can we add a fallback for 2008 R2 which is to add single_pages_kb + multi_pages_kb field?

**Comment by sparrc** [comment]
both proposals sound fine, PR is welcome :)

**Comment by sparrc** [comment]
closed by https://github.com/VasuBalakrishnan/telegraf/commit/ba06533c3ecf0dee88105cab452e508698cd88d6
