### ISSUE TITLE
[SQL Server Input plugin] Override app name property = "telegraf" in SQL connection string

### ISSUE THREAD

**Issue by masree** [influxdata/telegraf#8810]
## Feature Request
Override app name property in SQL connection string to "telegraf" to identify the connection string as telegraf monitoring.
Example:
Server=testsvr.database.windows.net;Port=1433;database=testdb;User Id=test_telegraf;Password=xxx;**app name = telegraf**

### Proposal:
Customers today can specify an arbitrary application name in connection string(telegraf.conf) while connecting to Azure SQL DB from telegraf. While this good if they are running their own custom application, however for monitoring it might be better to tag those connections explicitly. Including application name property in the connection string and tagging it as telegraf will make the troubleshooting also simpler if the DBA is investigating. If the connection string in telegraf.conf has app name = telegraf, we leave it as-is, however if user enters a different app name in telegraf.conf, we override that information to be "telegraf" by adding the logic [SQL server input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver). This enables 2 things:
1. Able to differentiate connections coming from telegraf to Azure SQL databases, making it easier for troubleshooting
2. On Azure SQL databases (Paas) engine, we can lookup based on this property and specify resource limits like CPU, physical I/O, and memory that a monitoring service can use. This would build a safety set for customers and ensures that their workload always have enough resources. 
Example:
Server=testsvr.database.windows.net;Port=1433;database=testdb;User Id=test_telegraf;Password=xxx;**app name = telegraf**

### Current behavior:
Customer can enter any arbitrary string for app name and there is no way to differentiate connections from telegraf vs others

### Desired behavior:
For Azure SQL DB only:
1. If the user does not specify app name, we add app name = telegraf in the connection string before connecting to Azure SQL DB
2. If the user specifies a different app name in telegraf.conf, we override it with "telegraf"
3. If user specifies app name = telegraf, we leave it as-is

### Use case: 
1. Able to differentiate connections coming from telegraf which could be leveraged to setup Resource Governance on Azure SQL databases to cap resource usage from telegraf  - https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-logical-server . Enables to build safety net to run customer workloads efficiently.
2. Troubleshooting will also be easier knowing where the connection is coming from

I'm willing to make the change, but wanted to gather feedback before I create a PR.

**Comment by masree** [comment]
@ssoroka @srebhan @Trovalo @denzilribeiro - Please let me know your thoughts.
@avinash-nigam @coquagli @bhsu-ms - FYI

**Comment by Trovalo** [comment]
That's fine to me.
So far I've always specified it myself in the connection string but having it as a default value will be useful.

**Comment by denzilribeiro** [comment]
I agree could be useful to measure impact of all queries coming from telegraf on the SQL side irrespective of if specified in connection string. This should be something that is common accross all not just Azure SQL. I think you should treat the property as an override only aka if AppNameOverride is specified then that takes precedence over anything specified in individual connection strings, if not, then whatever the user specifies remains true ( rather than just overriding "some" connection strings if app name not specified).

**Comment by srebhan** [comment]
I don't have a problem with this iff (if and only if)

1. This can be overwritten by the user.
2. It does not effect the telegraf output _or_ it keeps the current output by default (i.e. opt-in).

**Comment by masree** [comment]
Thanks for the feedback! I'm wondering if we can make it an opt-out feature rather than opt-in - By default the property AppNameOverride is always set to true unless user wishes to change it. If any concerns, please let me know. I'll work on the PR and link it here.

**Comment by srebhan** [comment]
Does this option change the metric **output** of telegraf?

**Comment by Trovalo** [comment]
> Thanks for the feedback! I'm wondering if we can make it an opt-out feature rather than opt-in - By default the property AppNameOverride is always set to true unless user wishes to change it. If any concerns, please let me know. I'll work on the PR and link it here.

I like the idea of the opt-out approach as you described it, to summarize it:
- the configuration parameter is always active and has a default value like "telegraf" (I'd use a name like "ConnectionAppName" just to be really explicit about what it does, but any name is fine)
- its value can be changed by specifying it explicitly in the plugin configuration
- _what if the value is specified in the connection string itself? (as it is now in my case)_
  - in this case I'd give precedence to the value already specified in the conn string itself

As @denzilribeiro said this should be valid for all the connection type (not only Azure SQL)

@srebhan, this won't change the telegraf metric output, it's just a way to better (centralized) way to manage a connection parameter of SQL Server. The parameter itself is called "Application Name" and is useful to track the name of client program that initiated the session (on SQL Server)

**Comment by denzilribeiro** [comment]
I agree, I like the approach too, will simplify not having to pass the param in every connection string too!

**Comment by srebhan** [comment]
Well in this case I'm fine with whatever you guys come up with! ;-P Seriously, an opt-out is fine in this case, but please make sure you respect the user's setting if he/she passes an "Application Name" in the connection string already.

**Comment by srebhan** [comment]
Is this still a thing?
