### ISSUE TITLE
Prometheus input ---- histograms issue: le="+Inf" series gets lost when serializing to influx_data or json for prometheus histograms

### ISSUE THREAD

**Issue by vishiy** [influxdata/telegraf#8811]
1.16.3

### Steps to reproduce:
le=+Inf bucket timeseries disappears when serializing  prometheus histograms to influx_data or json

ex;- rest_client_request_duration_seconds_bucket{hostName="aks-lpool-dddd-vmss000000",job="apiserver",scrapeUrl="https://dddd-dev-1-dns-e76b4ef0.hcp.westus2.azmk8s.io:443/metrics",url="https://localhost:443/healthz",verb="GET",le="+Inf"} 15

### Expected behavior:

the above time series is preserved in influx, json

### Actual behavior:

+Inf time series are lost when serializing to influx_data and json formats, making the histogram meaningless

**Comment by powersj** [comment]
Hi @vishiy,

How should Telegraf handle these positive infinite numbers? Would you expect the influx parser to use max int value?

Thanks

**Comment by powersj** [comment]
> its not about representing infinite values. 'Inf' bucket is missing.

You said it is dropped when transformed to a different datatype like JSON or influxdb. Is this silently dropped? or is there an error message?

Additionally, what data type is Inf considered in prometheus? I'm trying to understand what Inf is/should be converted to when you make the conversation, or am I going about this the wrong way?
