### ISSUE TITLE
Error report of Telegraf integrated kafka

### ISSUE THREAD

**Issue by Yu-MR1019** [influxdata/telegraf#8827]
Hello, seniors
I am doing telegraf to collect information and use it in combination with kafka plug-in. After configuration, I started successfully, but I still reported an error by checking the log. The error message is as follows:
E! [inputs.kafka_consumer] Error in plugin: EOF；
The version information I use is as follows:
Kafka version：2.10.x
Zookeeper version: 2.4.x
Influxdb version: 1.8.x
Telegraf version:1.7.x
In order to facilitate you to quickly locate the problem, attach the telegraf.cof file
#egrep -v "#|^$" /etc/telegraf/telegraf.conf
[[inputs.kafka_consumer]]
brokers = ["192.168.60.103:9092"]
topics = ["stskafkainflux"]
topic_tag = "stskafkainflux"
offset = "oldest"
max_message_len = 1000000
data_format = "json"
data_type = "string"
name_override = "topicB"
tag_keys = ["moduleName"]
json_string_fields = ["operation","createdate","userIp","userName","operResult","reqUrl"]
json_query = "msg"
[[outputs.influxdb]]
urls = ["http://192.168.60.104:8086"]
database = "mydb"
retention_policy = ""
precision = "s"
timeout = "5s"
username = ""
password = ""

**Comment by helenosheaa** [comment]
Can I confirm what version of Telegraf you are using, as we are currently on 1.17.2?

Also if you add debug = true into the agent portion of your config do you see anything else in the logs? And is it outputting anything to Influxdb or just showing the error? 

Could be helpful to see an example of the json message that is within that topic also if possible?
