### ISSUE TITLE
Inputs.Modbus Float 32bit  byte swap not get real value

### ISSUE THREAD

**Issue by karan369** [influxdata/telegraf#8855]
Hi,
I tried following setting, the result is different
`  holding_registers = [
    { name = "voltage1", byte_order = "CDAB",   data_type = "FLOAT32", scale=0.01,  address = [2,3]},
  ]
`

Two holding register (2,3), This combines 2 16 bit Modbus register, 
Data type: 32 bit float, little endian byte swap

Tested Result  shown below ( is not final value)
`type=holding_register voltage1=11313223.24 1613223318000000000
`
Final Value should be  between 238.45  to 239.10

how to convert or improve this, Kindly provide your best solutions.

**Comment by srebhan** [comment]
@karan369 you have to use `FLOAT32-IEEE` as datatype. Please close this issue once your problem is fixed!
