### ISSUE TITLE
Telegraf Installation on Teltonika TLT-RUT900 Router

### ISSUE THREAD

**Issue by albertshanhandoko** [influxdata/telegraf#8857]
Hi,
I have problem installing telegraf on mips architecture device. 
Here is the specification of my device
1. OS = Busybox v1.30.1
2. CPU info
![image](https://user-images.githubusercontent.com/20452261/107904484-81d95b00-6f7e-11eb-898d-53036cab53a3.png)

Here are things that I have done
1. Download software using wget command ( wget https://dl.influxdata.com/telegraf/releases/telegraf-1.17.2_linux_mips.tar.gz)
2. Extract the file using tar command ( tar xzvf telegraf-1.17.2_linux_mips.tar.gz)
3. Move the binary and library files to root directory

After that when I run telegraf command its return 'Ilegal Instruction'
Please check the screenshot below
![image](https://user-images.githubusercontent.com/20452261/107904681-0f1caf80-6f7f-11eb-9029-cbc2e48ce130.png)

Please help and advise

Thank you

**Comment by srebhan** [comment]
Hey @albertshanhandoko,

IIRC AR9344 is a softfloat CPU. So according to the [golang wiki](https://github.com/golang/go/wiki/GoMips#teltonika-rut955) for a similar router with the same CPU you have to specify softfloat. The prebuilt packages are all hardfloat...

So in case you have the chance, download the source-code to a desktop machine with GO available and run
```
GOOS=linux GOARCH=mips GOMIPS=softfloat go build -ldflags "-X main.goos=${GOOS} -X main.goarch=${GOARCH}" ./cmd/telegraf/
```
in the telegraf directory. This will build a MIPS-softfloat version of telegraf. Can you give it a try!?

**Comment by srebhan** [comment]
@albertshanhandoko did you solve your problem? Let me know if the command above solved your problem, maybe we can ask Influx ppl to also build a softfloat image...

**Comment by srebhan** [comment]
@albertshanhandoko is your problem solved? If so, you might want to document your solution here so the next poor guy having the same problem has some starting point.

**Comment by ziehmon** [comment]
@srebhan while I am not @albertshanhandoko, I still would like to thank you because your approach worked. I don't use a TLT-RUT900, but a Speedlink 5501, which also has a MIPS CPU and requires soft float. 

I was wondering how I'd have to modify the Makefile for building with these settings, just for the sake of consistency? Also, would it make sense to document this somewhere else than this issue?

Thanks again!

**Comment by powersj** [comment]
> I was wondering how I'd have to modify the Makefile for building with these settings, just for the sake of consistency? 

You can pass those same env variables to the make file:

```s
$ GOOS=linux GOARCH=mips GOMIPS=softfloat make build
$ file telegraf
telegraf: ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=c6iO7XSoQaTsd0fjPe0j/R5HunZ0YaBNgFHYjenFV/JJ2Sj4_jAD3oDFTMPy3c/VabuZ6B1mZXF36vBrXku, with debug_info, not stripped
```

> Also, would it make sense to document this somewhere else than this issue?

If you want to add how pass custom GO variables with the Makefile that would be totally appreciated. Looking in Docs I don't see a good file quickly, but you could create a new one called BUILD.md.
