### ISSUE TITLE
Updated ZFS measurements for OpenZFS 2.0

### ISSUE THREAD

**Issue by tjnome** [influxdata/telegraf#8862]
### Proposal:

With release of OpenZFS 2.0 the telegraf plugin should be updated

### Current behavior:

Alot of metrics are locked on linux to old behavior of ZFS 0.7-0.8

### Desired behavior:

With release of ZFS 2.0 the codebased have been unified between FreeBSD and Linux where commands and metrics should be available for both OS. 

### Use case: 

With current behavior for linux we can't collect criticial data to ensure pool is healthy.

**Comment by sjwang90** [comment]
@tjnome If you would like to submit a PR we would gladly take a look

**Comment by aaronjwood** [comment]
Pool metrics seem to have stopped working with ZFS 2.1.x. I'd be happy to submit a PR for this + support for the new metrics but I'm very tight on time. I will see what I can do over the next few months.
