### ISSUE TITLE
[inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000)

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/telegraf#8871]
### Relevant telegraf.conf:
N/A
```toml

```

### System info:

Windows Server 2012 R2 - Telegraf 1.17

### Docker

N/A

### Steps to reproduce:

1. Using an OPCUA server (Kepware) on my side, create at least 2 variables. 
2. First, both with Good quality to check plugin works fine. 
3. After this check, force one of them to Bad quality.

### Expected behavior:

Point with Good quality should be read and stored in InfluxDB. Point with Bad quality, not.

### Actual behavior:

[inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000) 
Error in log file. 
None of configured points is stored in influxDB, at least, point with Good quality should be stored.

### Additional info:

[inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000)

**Comment by zwl-sun** [comment]
Have you solved your problem please?

**Comment by alexmc1510** [comment]
No. And nobody has helped to solve it.

**Comment by R290** [comment]
I can reproduce this behavior with the following configuration using the `open62541` docker image:
```
  nodes = [
    {name="badnode", namespace="1", identifier_type="i", identifier="1337"}, # BadUserAccessDenied (0x801f0000)
    {name="goodnode", namespace="1", identifier_type="s", identifier="the.answer"}, # Good (0x00000000)
  ]
```
The good node is skipped, while we would expect to see it in the output. The problem arises from returning the error instead of just logging the error. I'll reference this issue in a commit with an example solution in the near future.

**Comment by R290** [comment]
In commit https://github.com/R290/telegraf/commit/c931908d99abc8ed522295877123e02fbd0eb95a I've added the standard telegraf logger and replaced the return error by a `Log.Errorf`. I also expanded the tester to show the behavior that I wanted to change. The node `badnode` now prints an error, wheras the node `goodnode` is processed normally.

I can open a pull request if this is an acceptable solution.
