### ISSUE TITLE
Unable to add a new Aggregator Plugin to the telegraf build

### ISSUE THREAD

**Issue by nidhanda** [influxdata/telegraf#8879]
I am working on a customized version of telegraf to be used only for my purposes, For this I created a modified version of basicstats aggregator plugin, following the documentation at - https://github.com/influxdata/telegraf/blob/master/docs/AGGREGATORS.md#aggregator-plugin-guidelines
https://www.youtube.com/watch?v=0qqSSmJV8WI

However I can't seem to add the absolute or relative path to my plugin file in the plugins/aggregators/all/all.go file. It shows an error saying - 

`plugins/aggregators/all/all.go:5:2: package plugins/aggregators/mdmratmetrics is not in GOROOT (/usr/local/go/src/plugins/aggregators/mdmratmetrics)`

For context, I am creating the new plugin directory at the same directory structure as existing telegraf aggregator plugins. 
![image](https://user-images.githubusercontent.com/48528782/108440038-48ffe700-7207-11eb-87df-88c88b484c2f.png)

and if I add it to the all.go in the same format as the existing aggregator plugin paths - 

"github.com/influxdata/telegraf/plugins/aggregators/mdmratmetrics"
![image](https://user-images.githubusercontent.com/48528782/108441125-5322e500-7209-11eb-8291-745d56105b52.png)

Then it ignores that file and doesn't build it along with the binary. When I run the telegraf binary with my config it says - 

`2021-02-19T00:44:48Z E! [telegraf] Error running agent: Error parsing telegraf.d/network.conf, Undefined but requested aggregator: mdmratmetrics` 

Am I missing a step for linking/registering the plugin? I can confirm that I am calling the aggregators.Add in the init function as well. I am simply cloning the telegraf source code from a forked repo and running "make" to build telegraf and not through go get to clone the code, I did do the
`go get github.com/influxdata/telegraf`
during my debug to see if that helps with the build but that command exited instantly without any error 

How do I provide the path to my local .go file containing the code for this custom aggregator plugin to be build within telegraf binary? Any help is appreciated! Thanks.

**Comment by Hipska** [comment]
Please see the [#telegraf-dev](https://influxcommunity.slack.com/archives/C019JDRJAE7) channel on Slack.

**Comment by ssoroka** [comment]
This looks like it's an issue with Go modules or has to do with the path you're using. I'd recommend checking Telegraf out to the matching path, eg ~/go/src/github.com/influxdata/telegraf.
As this isn't an issue with Telegraf, I'm going to close it. feel free to follow up with the community channel posted above.
