### ISSUE TITLE
Bug or a feature?

### ISSUE THREAD

**Issue by PPerminov** [influxdata/telegraf#8889]
https://github.com/influxdata/telegraf/blob/2372db9028dbe6c88b45254ec31fa3e85d9d5533/plugins/inputs/kube_inventory/kube_state.go#L217

Isn't it a bug to have "*" in that line? Because according to the function Match of IncludeExcludeFilter if you will have anything in "exclude" and anything in "include" then "exclude" will overwrite include. So by default you need to explicit an empty array in config for exclude to avoid that.

**Comment by srebhan** [comment]
Well the mentioned value matches the default documented in the `sampleConfig` field but does **NOT** match the text description above the option.

We have two options, either make the options match the text ("all included by default") by changing 
```golang
SelectorExclude: []string{"*"},```
to
```golang
`SelectorExclude: []string{""},
```
**OR** to change the description that everything is _ex_cluded by default.

I think the first option makes more sense, but as this was already be published in releases ppl might rely on this...

@ssoroka, @sspaink, @reimda what do you think?

**Comment by sspaink** [comment]
Sorry for the late response, the first option does make more sense but it could break backward compatibility. Maybe for now we update the description, and we could update the option to match the text in 2.0? 

We are tracking breaking changes here: https://github.com/influxdata/telegraf/issues/9478

**Comment by srebhan** [comment]
@sspaink I guess the question goes to @PPerminov!? :-)
