### ISSUE TITLE
In plugin input.elasticsearch cluster name in different tags

### ISSUE THREAD

**Issue by greenx** [influxdata/telegraf#8893]
In some metrics, the name of the cluster is passed in the tag **name** , and in some in the tag  **cluster_name**. This is confusing and difficult to work with.

**Comment by powersj** [comment]
hi @greenx,

It does look like telegraf switches between name and cluster_name in a few places. Can you confirm that we use "name" for these two metrics:

* `elasticsearch_cluster_health`
* `elasticsearch_cluster_health_indices`

Are there any others that should also use "cluster_name" to be consistent.

Thanks
