### ISSUE TITLE
Add General Expression Support for Cloudwatch Input

### ISSUE THREAD

**Issue by lawliet89** [influxdata/telegraf#8894]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

The CloudWatch [`GetMetricData`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) API call has the capability to use an Expression for arbitrary computation on returned metrics.

This is an extension of the feature request detailed in https://github.com/influxdata/telegraf/issues/7951. This is a more generalised request than #7951.

### Current behavior:

Only 'minimum, maximum, sum, samplecount, average' are supported metric values. There is no extendedmetrics available which would be used by extended metrics.

### Desired behavior:

Support creating new time series from arbitrary Expressions.

### Use case: 

I am trying to fetch service quota metrics from CloudWatch under the `AWS/Usage` namespace. I would like to monitor the percentage of a service quota that is being used. Currently, the only way to get the quota is to use the function `SERVICE_QUOTA` in an expression. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Quotas-Visualize-Alarms.html

**Comment by powersj** [comment]
@lawliet89,

How is this different than #7951, they both seem to be asking for the ability to request to use arbitrary expressions with cloudwatch?

Thanks!
