### ISSUE TITLE
Update gosnmp module to 1.30

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#8896]
Telegraf uses soniah/gosnmp 1.25 and gosnmp/gosnmp 1.29.  The gosnmp org took over the project from soniah.  Telegraf should only use one version.

Gosnmp just released 1.30.  It has many bugfixes, including one for #8823
https://github.com/gosnmp/gosnmp/releases/tag/v1.30.0

**Comment by Hipska** [comment]
The quest to have only one version is already addressed in #8660.
