### ISSUE TITLE
AMQP protocol support for Azure Simple Queue

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8899]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Looking for a plugin similar to the GCP pub/sub plugin and AWS SQS plugin for Azure Simple Queue. It should be able to work with any of the Telegraf input data formats.

### Current behavior:
At the moment AMQP protocol support isn’t available in Azures Simple Queue unlike AWS SQS. At the moment they have to use many APIs (.Net, Python, Java, Javascript) to do this but that would leave the logic of handling the queues to each individual.

### Desired behavior:
Looking for a replacement that brokers the connection, reads queue items and only deletes queue items once confirmed that the item has been processed by Telegraf.

**Comment by powersj** [comment]
Assuming this is the same as Azure Storage queue, I am not entirely clear if they even support AMQP still and instead require users to go over HTTP requests. As such this does not seem like something we would want to grow and maintain in Telegraf. If I am mistaken or they have changed that, then we could re-evaluate.

Thanks
