### ISSUE TITLE
Add a starlark example showing how to obtain IOPS (to aggregate, to produce max_iops).

### ISSUE THREAD

**Issue by thatsafunnyname** [influxdata/telegraf#8903]
Hello and thanks for telegraf,

### Proposal:

Review and add a starlark example showing how to obtain IOPS (to aggregate, to produce `max_iops`).
Where the `max_iops` is the peak IO per second rate seen over a period (and not a maximum of means of IO "per second").
In my example the period is 60s.

### Current behavior:

No example of how to do this (that I could find).

### Desired behavior:

An example star file in `telegraf/plugins/processors/starlark/testdata/`

### Use case: 

I asked in https://community.influxdata.com/t/can-telegraf-be-used-to-aggregate-max-iops if what I wanted to do was possible or not, and after some guidance to look at the starlark processor was able to get it working.

My goal is to use the `max_iops` (along with other diskio metrics) when viewing usage of, and provisioning IOPS on disks.

I did spend some time searching the telegraf github project for mention of IOPS, and I think if an example had been present then it would have saved me some time.

I have attached `iops.star` , if you think a PR for it is appropriate then please let me know.

[iops.star.txt](https://github.com/influxdata/telegraf/files/6038341/iops.star.txt)

Thanks.

**Comment by sjwang90** [comment]
@thatsafunnyname Can you open a PR with your example like you did for the shared state example?

**Comment by sjwang90** [comment]
Closed in #8996
