### ISSUE TITLE
add proxy support to cloudwatch

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#8904]

**Comment by danatinflux** [comment]
To support case https://na83.lightning.force.com/lightning/r/Case/5001S00001DMs3HQAT/view , the customer would like a spot to put 'http_proxy' for the Cloudwatch input plugin. Please let me know if there's anything else I can do to help out.

**Comment by ssoroka** [comment]
supporting this is pretty easy, check to see how the http listener plugins do it.
