### ISSUE TITLE
InfluxDB/Telegraf-Array

### ISSUE THREAD

**Issue by danishv** [influxdata/telegraf#8906]
I have perl script returning values in an array. when i tried to write this in to influx am getting time stamp only for last line. Is there any way to get this time stamp to each line of the array. time stamp will be same for each line.

beow is code : 

#use strict;
#use Shell qw(lynx);

my @myarr1=qx(snmpwalk -v2c -c 'test1' 10.1.4.21 1.3.6.1.2.1.71.1.3.3.1.4);

#$myarr1=@myarr1;
#print "$myarr\n";

my @lines = @myarr1;

foreach (my $i=0; $i <= $#lines; $i++) {
#foreach (my $i=0; $i <= 0; $i++) {

                my @ip1 = split / /, $lines[$i];
                my @ip11 = chomp($ip1[6]);
                my $tunip = hex($ip1[3]).".".hex($ip1[4]).".".hex($ip1[5]).".".hex($ip1[6]);
                printf "dmvpn,host_name=GSM,Tunnel_IP=$tunip";
                printf "\n";
};

telegraf output:

![image](https://user-images.githubusercontent.com/58603597/109134257-e78bcb00-7766-11eb-9bd8-bb0515fae05a.png)

**Comment by srebhan** [comment]
Hey,

your line protocol does not have any field, but line-protocol [requires at least one field](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#field-set).

Is there a reason why you don't use the SNMP plugin? Please check the #telegraf slack channel and post more information about your config.

**Comment by danishv** [comment]
Snmp output is in hex, that’s reason I use Perl script to convert Hex to decimal. Is there any way I can add field to this script to get actual output with time stamp ?

**Comment by Hipska** [comment]
See the `conversion` option for [snmp fields](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp#field).

**Comment by srebhan** [comment]
@danishv I think the easiest way is to actually use the existing SNMP plugin and rather invest the time in reading the [plugin documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp). If you need more help, please ask in the Slack-channel. If you really find a missing feature, please open an issue and request the feature.

**Comment by danishv** [comment]
@srebhan  In my case snmp plugin will not help because its output is in Hex. I managed to pull out data. But with data_type= " influx" am getting error. Can you please help me to write my script out put in line protocol format.                                                                                                                                          

This is my full Script
#########################################
#use strict;
#use Shell qw(lynx);
my @myarr1=qx(snmpwalk -v2c -c '47sky!Direct11' 10.13.4.201 1.3.6.1.2.1.71.1.3.3.1.4);
my @myarr2=qx(snmpwalk -v2c -c '47sky!Direct11' 10.13.4.201 1.3.6.1.2.1.71.1.3.3.1.6);
#$myarr1=@myarr1;
#print "$myarr\n";
my @line = @myarr1;
my @line1 = @myarr2;
foreach (my $i=0; $i <= $#line; $i++) {
#foreach (my $i=0; $i <= 0; $i++) {
                my @ip1 = split / /, $line[$i];
                my @ip11 = chomp($ip1[6]);
                my @ip2 = split / /, $line1[$i];
                my @ip22 = chomp($ip2[6]);
                my $tunip = hex($ip1[3]).".".hex($ip1[4]).".".hex($ip1[5]).".".hex($ip1[6]);
                my $simip = hex($ip2[3]).".".hex($ip2[4]).".".hex($ip2[5]).".".hex($ip2[6]);
                printf "dmvpn,host_name=GSM Tunnel_IP=$tunip,SIM_IP=$simip";
                printf "\n";
};
#########################################
perl output sample
dmvpn,host_name=GSM Tunnel_IP=10.31.64.4,SIM_IP=10.158.205.168
dmvpn,host_name=GSM Tunnel_IP=10.31.64.6,SIM_IP=10.158.205.117
dmvpn,host_name=GSM Tunnel_IP=10.31.64.7,SIM_IP=10.158.205.116
dmvpn,host_name=GSM Tunnel_IP=10.31.64.3,SIM_IP=10.158.205.92
dmvpn,host_name=GSM Tunnel_IP=10.31.64.2,SIM_IP=10.158.195.124
#########################################telegraf input plugin
[[inputs.exec]]
  commands = ["perl /etc/telegraf/telegraf.d/HEX5.pl"]
  data_format = "influx"
  interval = "60s"
  timeout = "5s"
# Output Plugin InfluxDB
[[outputs.influxdb]]
  database = "telegraf"
  urls = [ "http://127.0.0.1:8086" ]
  username = "telegraf"
  password = "telegraf"
#########################################
Telegraf test error
root@danish-PowerEdge-1950:/etc/telegraf/telegraf.d# telegraf --test --config dmvpn.conf
2021-03-01T08:49:32Z I! Starting Telegraf 1.15.3
2021-03-01T08:49:32Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:36: "dmvpn,host_name=GSM Tunnel_IP=10.31.48.2,SIM_IP=10.158.195.42"
2021-03-01T08:49:32Z E! [telegraf] Error running agent: input plugins recorded 1 errors
root@danish-PowerEdge-1950:/etc/telegraf/telegraf.d

**Comment by Hipska** [comment]
@danishv The `conversion = "ipaddr"` is exactly for this use-case where you would have HEX values otherwise.

**Comment by srebhan** [comment]
@danishv first of all the error message tells you the same as I did:

> 2021-03-01T08:49:32Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:36: "dmvpn,host_name=GSM Tunnel_IP=10.31.48.2,SIM_IP=10.158.195.42"

You need a field for influxdb! Anyway, I'm not sure that using IP-Addresses (especially changing ones like the tunnel-IP) are a good candidate for tags. Please read on [series cardinality](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#series-cardinality)! I suggest you use a machine name (controlled by you) as tag and the two IP-Addresses as fields...

Anyway,  what happens if you use
```toml
  [[inputs.snmp.field]]
    oid = "1.3.6.1.2.1.71.1.3.3.1.4"
    name = "GSM Tunnel_IP"
    is_tag = true
    conversion = "ipaddr" 
```

Using a php-script to solve this kind of problem seems fundamentally wrong and hacky to me.

**Comment by danishv** [comment]
@srebhan thanks it worked i was not aware that snmp plugin supports direct conversion
