### ISSUE TITLE
Correct common question in the Starlark Processor README about shared state.

### ISSUE THREAD

**Issue by thatsafunnyname** [influxdata/telegraf#8907]
Hello and thanks for telegraf.

After https://github.com/influxdata/telegraf/pull/8447 , this common question in the Starlark Processor README.md should be updated to reflect the newly available shared state:

https://github.com/influxdata/telegraf/blame/8ddbab47a46e256281392ad0aac876715189c117/plugins/processors/starlark/README.md#L166

>   **How can I save values across multiple calls to the script?**
> 
>   Telegraf freezes the global scope, which prevents it from being modified.
>   Attempting to modify the global scope will fail with an error.

Suggest replacing this with:

  A shared global dictionary named "state" exists, this can be used by the apply function.
  See an example of this in `plugins/processors/starlark/testdata/compare_metrics.star`

Thanks

**Comment by sjwang90** [comment]
@thatsafunnyname would you want to submit a PR for changes to the README?

**Comment by thatsafunnyname** [comment]
I can do, I just need to wait for approval from my employer to sign the Individual CLA.
