### ISSUE TITLE
FreeBSD ARM support - Where did you go?

### ISSUE THREAD

**Issue by SomKen** [influxdata/telegraf#8922]
After reviewing my older post from https://github.com/influxdata/telegraf/issues/5282, it seemed as if telegraf would start building freebsd arm packages. After having then installed the 1.15 version of telegraf onto my pfsense, it has survived every version of pfsense Ive upgraded it to since. So, at least in this one case, it still works, but I don't see any new builds.

**Comment by rsletten** [comment]
Would like this as well.

**Comment by FreeWillyB** [comment]
Sign me up as well. I'm working on a pilot network right now. If all goes well, it would involve deploying about 13 or so of the Netgate SG-3100 across the state. I had planned on using Telegraf for metric reporting, but didn't realize the agent wasn't supported.

**Comment by strman** [comment]
@SomKen any chance you could share the steps you took to install telegraf 1.15?

**Comment by SomKen** [comment]
https://forum.netgate.com/topic/142836/telegraf-for-arm-systems-e-g-netgate-sg-3100/65

I'm tracking my progress here. There was a guide I found for building, funny enough, ARM packages on the SG-3100 using qemu / freebsd 12.2. Testing that now.

**Comment by SomKen** [comment]
I just added https://forum.netgate.com/topic/142836/telegraf-for-arm-systems-e-g-netgate-sg-3100/69. I've included the then built version of telegraf. Please note this version is over 2 years old, but is still running on my SG-3100 after all the updates over the two years. I haven't had to do ANYTHING to get it working between updates. This must be the difference between PFSense and FreeBSD.... >_>

I attempted to build a new version last night, but as expected (i believe) GO failed to build after a few hours. Looking at logs, it seems to be because of a run away build, but I haven't had time to really look. I'll dig more tonight. 

Please Influx, please help us here. I will send you an SG-3100 if needed. Netgate is being less than helpful here. After seeing the recent drama related to Wiregurad and their response, it makes sense. 

https://www.reddit.com/r/networking/comments/m6zjie/wireguard_netgate_pfsense_drama/ and https://docs.opnsense.org/history/thefork.html if you want to cry.

**Comment by SomKen** [comment]
Figured out how to build the armv7 packages for Freebsd without the need of an SG-3100, code changes, or emulation. I'll report back later, but GO is amazing.

**Comment by SomKen** [comment]
`GOARM=7 GOOS=freebsd GOARCH=arm go build ./cmd/telegraf`

Can you please publish a telegraf for FreeBSD armv7 (and friends)? GO can cross compile, even from x86 to ARM, so building on any machine should be doable.

**Comment by SomKen** [comment]
bamp?

**Comment by sjwang90** [comment]
Hey @SomKen, where are you looking for the FreeBSD builds? They're not on our downloads page but on our GitHub releases page: https://github.com/influxdata/telegraf/releases

**Comment by SomKen** [comment]
> 
> 
> Hey @SomKen, where are you looking for the FreeBSD builds? They're not on our downloads page but on our GitHub releases page: https://github.com/influxdata/telegraf/releases

There are no arm builds for Freebsd

**Comment by reimda** [comment]
None of the 1.15 releases included an arm FreeBSD build either.  For example, see 1.15.1: https://github.com/influxdata/telegraf/releases/tag/v1.15.1

I wonder if the 1.15 build on your pfsense box is an unofficial build made by a third party.

**Comment by SomKen** [comment]
https://www.youtube.com/watch?v=Cfr-tDnG5oA

You can build it from source yourself using any x86 machine.

**Comment by sjwang90** [comment]
We don't officially support arm builds for FreeBSD. We started a PR doc #9100 to clarify the platforms and builds we do support.

**Comment by SomKen** [comment]
@sjwang90 With that page being created, what is the status of building for ARM Freebsd? As I showed above, building for Freebsd ARMv7 is doable from any x86 machine.

**Comment by reimda** [comment]
@SomKen @rsletten @FreeWillyB Could you test the FreeBSD ARM build in #9200?

CI build artifacts are automatically added as a comment to PRs and are valid for 30 days.  I think this is the one from #9200 that you're looking for: https://87796-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.19.0%7E80ba0909_freebsd_armv7.tar.gz

**Comment by SomKen** [comment]
No issues with the build at all. Just checked this morning and the processes has been running since starting / no issues to report. Metrics are all in influx.
