### ISSUE TITLE
Output.http plugins multiple metrics problem

### ISSUE THREAD

**Issue by albertshanhandoko** [influxdata/telegraf#8924]
Hi,
Here is the issue detail

Goals =
- Using output http to send multiple modbus input metrics

Problem =
- Output http only send 1 metrics 
- There is an error that stated "Client.Timeout exceeded while awaiting headers"

telegraf.conf =
![image](https://user-images.githubusercontent.com/20452261/109622638-ea275f80-7b6e-11eb-93fd-1aa5a840d773.png)

telegraf Log =

![image](https://user-images.githubusercontent.com/20452261/109622432-af252c00-7b6e-11eb-83c6-8ecef36d051f.png)

**Comment by helenosheaa** [comment]
Hi, Have you tried increasing the timeout in the output config?
