### ISSUE TITLE
Modbus without discrete_inputs or coils

### ISSUE THREAD

**Issue by bausi2k** [influxdata/telegraf#8925]
My problem is, I don't have discrete_inputs or coils. If I delete them in the config- > TOML config file error. If i fill the with dummy values, I just get a timeout, because there is nothing to read. So what should I do if I just want to use olding_registers and input_registers?

Am I doing something wrong?

**Comment by srebhan** [comment]
@bausi2k without a config or error message it is impossible to help...

**Comment by bausi2k** [comment]
here is the config of the modbus module:

```[[inputs.modbus]]
  ## Device name
  name = "wrl"

  ## Slave ID - addresses a MODBUS device on the bus
  ## Range: 0 - 255 [0 = broadcast; 248 - 255 = reserved]
  slave_id = 20

  ## Timeout for each request
  timeout = "5s"



  # TCP - connect via Modbus/TCP
  controller = "tcp://192.168.1.32:502"

  ## Measurements
  ##

  ## Digital Variables, Discrete Inputs and Coils

  ## address     - variable address

  discrete_inputs = [
    ]
  coils = [
    ]

  ## address    - variable address

  holding_registers = [
    { name = "Auszentemperatur",      byte_order = "AB",   data_type = "UINT16", scale=0.1,   address = [30]},
    { name = "Fortlufttemperatur",    byte_order = "AB",   data_type = "UINT16", scale=0.1,   address = [31]},
	{ name = "Ablufttemperatur",      byte_order = "AB",   data_type = "UINT16", scale=0.1,   address = [32]},
	{ name = "Zulufttemperatur",      byte_order = "AB",   data_type = "UINT16", scale=0.1,   address = [33]},
 ]
  input_registers = [
    { name = "Lüftungsstufe",   byte_order = "AB",   data_type = "UINT16",   scale=0.1,     address = [2]},
  ]```

The error is that the config couldn't be validated by the TOML Validator on launch of telegraf

**Comment by srebhan** [comment]
Works for me with 
[this config](https://github.com/influxdata/telegraf/files/6089815/issue-8925.conf.txt). Please validate your config e.g. using an [online TOML validator](https://www.toml-lint.com/) as I guess the problem is somewhere else.

**Comment by bausi2k** [comment]
woks now

**Comment by bausi2k** [comment]
case can be closed - don't know if I can do that myself

**Comment by srebhan** [comment]
@bausi2k glad it works now. What was your problem? You might want to document your solution here, if someone else finds the same issue. Anyway, you can close the ticket yourself with the "Close with comment" button. :-)

I'll do it for you now, but would be glad if you could document your solution if not trivial.
