### ISSUE TITLE
Please add daemonize switch

### ISSUE THREAD

**Issue by DocMAX** [influxdata/telegraf#8932]
Could you please add a switch like -d --daemonize?
I have to work with nohup telegraf & at the moment which is not nice.
Thanks!

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you yet.

If you need to use Telegraf as a daemon it is suggested to use one of our pre-built RPM or DEB packages, which will setup Telegraf as a service. This way you do not need to mess with nohub or other methods. We don't believe we would add any further options to the CLI at this time given these other options.

Thanks!
