### ISSUE TITLE
Telegraf nightly deb links not working

### ISSUE THREAD

**Issue by VasuBalakrishnan** [influxdata/telegraf#894]
I'm getting 403 errors when trying to download nightly build images

https://s3.amazonaws.com/telegraf/telegraf_nightly_amd64.deb

**Comment by sparrc** [comment]
cc @rossmcdonald

**Comment by rossmcdonald** [comment]
@VasuBalakrishnan Where did you get that link?

The correct one is: https://s3-us-west-1.amazonaws.com/telegraf-nightly/telegraf_nightly_amd64.deb

**Comment by VasuBalakrishnan** [comment]
Thanks for the update.

I was going by this link - https://influxdata.com/downloads/#influxdb

I didn't find a link for Telegraf's nightly build, so I used the influxdb url and replaced it with telegraf hoping it would work.

**Comment by sparrc** [comment]
@rossmcdonald maybe we should make that consistent, do we have a `telegraf` bucket that we could put everything into? I've been using get.influxdb.org for the regular releases but it would probably be better to make it look the same across the stack.

**Comment by rossmcdonald** [comment]
@sparrc Unfortunately the `telegraf` bucket is unavailable. Kapacitor nightlies currently go to `kapacitor-nightly`, so it's only InfluxDB that doesn't have a `-nightly` bucket. I actually tried moving them over to an `influxdb-nightly` but people complained, so I put them back.

I'll just update the Downloads page to include the full URL until we have a better solution.

**Comment by rossmcdonald** [comment]
Downloads page has been updated: https://influxdata.com/downloads/#telegraf-nightly

**Comment by sparrc** [comment]
thx @rossmcdonald
