### ISSUE TITLE
how can I use plugin.snmp in telegraf to collect data as the command "snmpwalk" ?

### ISSUE THREAD

**Issue by juri1987** [influxdata/telegraf#895]
when i use "snmptable -c xxx -v2c -m ALL 192.168.1.1 .1.3.6.1.4.1.3375.2.2.5.1.2.1.1"  in command line, it can work.
but i don't know how to use snmpwalk in telegraf, who can teach me about this ?

**Comment by sofixa** [comment]
You can try with the command:

telegraf -usage snmp

And telegraf will show you how to use it, with a description and an
example. This works for all output plugins.

**Comment by sparrc** [comment]
@juri1987 snmp plugin should cover that, let me know if there are more questions but please read the README first
