### ISSUE TITLE
How to compile telegraf on Visual studio code in Windows?

### ISSUE THREAD

**Issue by AhmetYenign** [influxdata/telegraf#8965]
I have developed some plugins and I want to add them to telegraf. I compiled it on Visual Studio Code and the .exe file was generated but it doesn't run as a service. What should I do?

PS C:\Users\user1\Desktop\GO\telegraf-master\cmd> go build .\telegraf\
PS C:\Users\user1\Desktop\GO\telegraf-master\cmd>

**Comment by denispershin** [comment]
Try
`GOOS=windows GOARCH=386 make`
or
`GOOS=windows GOARCH=amd64 make`
in telegraf folder

**Comment by AhmetYenign** [comment]
Thank you for your answer. Which file will I make this setting in?  Makefile or something else?

**Comment by denispershin** [comment]
Firstly try in cmd
`make` instead `go build .\telegraf`
if its not work try
`dir C:\Users\user1\Desktop\GO\telegraf-master`
`GOOS=windows GOARCH=386 make`
if its not work try
`dir C:\Users\user1\Desktop\GO\telegraf-master`
`set GOOS=windows`
`set GOARCH=386`
`make`

**Comment by AhmetYenign** [comment]
I tried the following operations but it did not work. How else can I compile it?

C:\Users\MONSTER\Desktop\GO\telegraf-master\cmd>go version
go version go1.16.1 windows/amd64

C:\Users\User1\Desktop\GO\telegraf-master\cmd>set GOOS=windows set GOARCH=386 make

C:\Users\User1\Desktop\GO\telegraf-master\cmd>go build .\telegraf
cmd/go: unsupported GOOS/GOARCH pair windows set GOARCH=386 make/amd64

I changed it to amd64 but it still didn't happen.

C:\Users\User1\Desktop\GO\telegraf-master>set GOOS=windows set GOARCH=amd64 make

C:\Users\User1\Desktop\GO\telegraf-master>go build
cmd/go: unsupported GOOS/GOARCH pair windows set GOARCH=amd64 make/amd64


"set GOOS=windows set GOARCH=386 make" or "set GOOS=windows set GOARCH=amd64 make"   it doen't work PowerShell

**Comment by AhmetYenign** [comment]
The problem solved . I followed the steps below.
cmd -> cd C: \ Users \ User1 \ Desktop \ GO \ telegraf-master> set GOOS = windows set GOARCH = amd64 make

and then I opened a New Terminal in Visual Studio Code.

I ran the following command
PS C: \ Users \ User1 \ Desktop \ GO \ telegraf-master \ cmd> go run. \ Telegraf \

and then I ran the following command
PS C: \ Users \ User1 \ Desktop \ GO \ telegraf-master \ cmd> go build. \ Telegraf \

finally the .exe file occurred. The resulting .exe file is running as a service.

Thanks for your help. :)
