### ISSUE TITLE
Telegraf cannot build docker image

### ISSUE THREAD

**Issue by VasuBalakrishnan** [influxdata/telegraf#897]
I'm trying to build a docker image for the 0.11 release and its failing with this error. I was able to build 0.10.4 with no issues.

> Created symlink from /etc/systemd/system/telegraf.service to /lib/systemd/system/telegraf.service.
> Created symlink from /etc/systemd/system/multi-user.target.wants/telegraf.service to /lib/systemd/system/telegraf.service.
> Failed to get D-Bus connection: Unknown error -1
> /var/lib/dpkg/info/telegraf.postinst: line 67: deb-systemd-invoke: command not found
> dpkg: error processing package telegraf (--install):
>  subprocess installed post-installation script returned error exit status 127
> Errors were encountered while processing:
>  telegraf
> 

This is my docker file

```
FROM debian:jessie
MAINTAINER Vasu Balakrishnan <xxxx>

ENV TELEGRAF_VERSION=0.10.4.1-1

RUN apt-get update \
    && apt-get install -y curl

RUN curl -s -o /tmp/telegraf_latest_amd64.deb http://get.influxdb.org/telegraf/telegraf_${TELEGRAF_VERSION}_amd64.deb \
 && dpkg -i /tmp/telegraf_latest_amd64.deb \
 && rm /tmp/telegraf_latest_amd64.deb \
 && rm -rf /var/lib/apt/lists/* 
    
VOLUME ["/etc/telegraf"] 
VOLUME ["/var/log/telegraf"] 

EXPOSE 8125
EXPOSE 8125/UDP

CMD ["/usr/bin/telegraf", "-config", "/etc/telegraf/telegraf.conf"]

```

**Comment by sparrc** [comment]
not sure why the docker image doesn't have deb-systemd-invoke? http://manpages.debian.org/cgi-bin/man.cgi?&query=deb-systemd-invoke

What happens if you try ubuntu?

**Comment by VasuBalakrishnan** [comment]
It builds fine with ubuntu. However I see an error, not sure if it has any impact 

invoke-rc.d: policy-rc.d denied execution of restart.

```
unnpacking telegraf (0.11.1-1) ...
Setting up telegraf (0.11.1-1) ...
 Adding system startup for /etc/init.d/telegraf ...
   /etc/rc0.d/K20telegraf -> ../init.d/telegraf
   /etc/rc1.d/K20telegraf -> ../init.d/telegraf
   /etc/rc6.d/K20telegraf -> ../init.d/telegraf
   /etc/rc2.d/S20telegraf -> ../init.d/telegraf
   /etc/rc3.d/S20telegraf -> ../init.d/telegraf
   /etc/rc4.d/S20telegraf -> ../init.d/telegraf
   /etc/rc5.d/S20telegraf -> ../init.d/telegraf
invoke-rc.d: policy-rc.d denied execution of restart.
 ---> b36b4ebb653e
Removing intermediate container acab25a5f689
Step 6 : VOLUME /etc/telegraf
 ---> Running in 7d31a34ec71b
 ---> 934d0eece45e
Removing intermediate container 7d31a34ec71b
Step 7 : VOLUME /var/log/telegraf
 ---> Running in ebbbe2103044
 ---> 6204ffd59689
Removing intermediate container ebbbe2103044
Step 8 : EXPOSE 8125
 ---> Running in fe4a3061aa5e
 ---> ec9bce5f0419
Removing intermediate container fe4a3061aa5e
Step 9 : EXPOSE 8125/UDP
 ---> Running in 7200671393b8
 ---> f6e2593185da
Removing intermediate container 7200671393b8
Step 10 : CMD /usr/bin/telegraf -config /etc/telegraf/telegraf.conf
 ---> Running in 52949a08d847
 ---> 8d91ef1fe7ed
Removing intermediate container 52949a08d847
Successfully built 8d91ef1fe7ed
```

**Comment by sparrc** [comment]
@VasuBalakrishnan Another option would be to just use the apt repos for this, see our official docker images: https://github.com/influxdata/telegraf-docker/blob/telegrafImage/0.10/Dockerfile
