### ISSUE TITLE
Problem with special characters in influxdb output plugin

### ISSUE THREAD

**Issue by collinlambert** [influxdata/telegraf#898]
In `plugins.outputs.influxdb.influxdb.go`
```
// Create Database if it doesn't exist
_, e := c.Query(client.Query{
    Command: fmt.Sprintf("CREATE DATABASE IF NOT EXISTS %s", i.Database),
})
```
The database name needs to be captured in double quotes. Any database with special characters (i.e. '-') will not be created and, surprisingly enough, does not produce an error in the query call. The result is failed writes to InfluxDb.

**Comment by sparrc** [comment]
thx for reporting, that'll be an easy fix :)
