### ISSUE TITLE
processors.starlark support math module

### ISSUE THREAD

**Issue by tacuna** [influxdata/telegraf#8985]
## Feature Request

Starlark supports basic math functions out of the box (+,-,/,*,...) but for some conversions more extended functions are desired (cos, sin, exp, ...). Starlark supports them by the [math.star](https://pkg.go.dev/github.com/qri-io/starlib@v0.2.0/math) module but it is not supported by Telegraf.

### Proposal:

Add support to load the math module in starlark scripts, or even load it by default (if there is no overhead, i have no knowledge of starlark's internals/design).

### Current behavior:

```
[[processors.starlark]]
  source = '''
load('math.star', 'math') 
def apply(metric):
	return metric
'''
```

Error: `[telegraf] Error running agent: could not initialize processor starlark: cannot load math.star: module math.star is not available`

### Desired behavior:

Use more extended math functions in starlark through `[[processors.starlark]]`; loading the math module.

### Use case:

In value conversions use functions like exp(...), cos(...), ect as they cannot be implemented by the default available math functions (+,-,/,*) and are required in some conversions.

**Comment by ssoroka** [comment]
looks like @essobedo is willing to take this on

**Comment by essobedo** [comment]
The corresponding PR https://github.com/influxdata/telegraf/pull/9042
