### ISSUE TITLE
kube_inventory: add stats for current cpu and mem usage for pods

### ISSUE THREAD

**Issue by ict-one-nl** [influxdata/telegraf#8998]
## Feature Request

Add stats for current cpu and mem usage for pods, also add calculated metrics like k9s does for cpu/mem against both request and limits

### Current behavior:
-

### Desired behavior:
Expose metrics

### Use case: 
So we can monitor our pods and scale up/down according to trends / insights.

**Comment by sspaink** [comment]
Hello @ict-one-nl, there is pull request open that extends the kube_inventory plugin: https://github.com/influxdata/telegraf/pull/9627 it seems related to the metrics you are requesting, is this what you are looking for?

**Comment by ict-one-nl** [comment]
Yes it is :)
