### ISSUE TITLE
processors.parser: Respect metric timestamp specified by input data format

### ISSUE THREAD

**Issue by LINKIWI** [influxdata/telegraf#9002]
## Feature Request

The current implementation of `processors.parser` only [parses fields from a metric](https://github.com/influxdata/telegraf/blob/f5552944d153a01d8c54be838e28c1e310371025/plugins/processors/parser/parser.go#L63) and does not consider the parsed metric timestamp, for example from the parameter [`json_time_key`](https://github.com/influxdata/telegraf/blame/f5552944d153a01d8c54be838e28c1e310371025/plugins/parsers/json/README.md#L49) in the case of a JSON input data format.

### Proposal:

The `processors.parser` plugin should support setting the metric timestamp as dictated by the data input format, optionally behind an opt-in parameter.

### Current behavior:

Setting `json_time_key` and `json_time_format` in the `processors.parser` input plugin has no effect on the output metric timestamp.

### Desired behavior:

Setting `json_time_key` and `json_time_format` in the `processors.parser` input plugin should update the metric timestamp in the resulting processed metric.

### Use case: 

The true timestamp of the data point may only be available in the parsed field.

In my particular case, I have a stream of messages ingested by Telegraf that look like:

```
{"id": 1, "payload": "{\"timestamp\": 123456, \"data\": \"foo\"}"}
```

`payload` is itself a serialized JSON blob. I use `processors.parser` to do a "double parse" of the JSON data inside `payload`, from which I need to extract the timestamp.

**Comment by ssoroka** [comment]
In the mean time you might have more luck parsing this with processors.Starlark, which has json support.

**Comment by powersj** [comment]
This now exists with the `merge = "override-with-timestamp"` option.
