### ISSUE TITLE
processors.parser: drop_original parameter incompatible with tracked metrics

### ISSUE THREAD

**Issue by LINKIWI** [influxdata/telegraf#9006]
### Summary

Some inputs, like [`kafka_consumer`](https://github.com/influxdata/telegraf/tree/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/inputs/kafka_consumer) uses [tracked metrics](https://github.com/influxdata/telegraf/blob/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/inputs/kafka_consumer/kafka_consumer.go#L277) to register callbacks when metrics are delivered to outputs. This is exposed with the [`max_undelivered_messages`](https://github.com/influxdata/telegraf/blob/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/inputs/kafka_consumer/kafka_consumer.go#L99) parameter.

It seems like the way this is implemented is with a [call to `AddTrackingMetricGroup`](https://github.com/influxdata/telegraf/blob/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/inputs/kafka_consumer/kafka_consumer.go#L383) whose return value implements `telegraf.Metric` and transparently wraps a gathered metric with delivery tracking.

However, the implementation of `processors.parser` parses the text as a raw `telegraf.Metric` which has [no attached delivery tracking](https://github.com/influxdata/telegraf/blob/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/processors/parser/parser.go#L117). I believe this causes the input plugin to effectively never receive a callback that the metric was successfully delivered to the output, but only when `drop_original` is set to `true`.

In practice, the symptom I observe is:

1. Telegraf consumes 1000 messages (default value of `max_undelivered_messages`) from Kafka
2. The processor plugin successfully parses the line according to the data input specification
3. Telegraf writes 1000 metrics to InfluxDB successfully (`select count(*) from measurement` returns 1000 rows)
4. Telegraf never commits an offset for the Kafka topic, presumably because it thinks the 1000 metrics it consumed are still in-flight to the output, since the logic never receives the `onDelivery` callback. So consumption is stalled forever at this point.
5. Disabling the `drop_original` parameter causes Telegraf to commit offsets to Kafka properly, presumably because both the tracked metric *and* the parsed, non-tracked message are [returned from the processor](https://github.com/influxdata/telegraf/blob/1746f96f15e9c43749329a748ecf9b8eec197698/plugins/processors/parser/parser.go#L60). I'm assuming the "original" metric is the same object that was wrapped with tracking, so the delivery callbacks proceed properly.

### Relevant telegraf.conf:

```toml
[[inputs.kafka_consumer]]
  ...
  data_format = "json"
  name_override = "test"
  json_string_fields = ["payload"]

[[processors.parser]]
  namepass = ["test"]
  parse_fields = ["payload"]
  drop_original = true
  merge = "override"
  data_format = "json"

[[outputs.influxdb]]
  ...
```

Input into Kafka is 1000s of messages shaped like this:

```
{"id": "foo", "payload": "{}"}
```

### System info:

```
$ telegraf --version
Telegraf 1.16.3 (git: HEAD c7f21728)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux SOLARA 4.4.0-193-generic #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Docker

N/A

### Steps to reproduce:

1. Use the config pasted above
2. Start Telegraf
3. Write 1000 + n messages to the Kafka topic, for n > 0

### Expected behavior:

1. Observe that all 1000 + n metrics are written to InfluxDB
2. Observe that a Kafka offset for the topic is commited with value 1000 + n

### Actual behavior:

1. Observe that exactly 1000 metrics were written to InfluxDB and no further metrics are written
2. Observe that a Kafka offset for the topic is not committed

### Additional info:

There are no error messages from Telegraf.

**Comment by powersj** [comment]
next steps: look into how parsers can look into the type of metrics that are parsed

**Comment by srebhan** [comment]
@LINKIWI this should be fixed in latest master. Can you please check a nightly build!?!
