### ISSUE TITLE
Add cron syntax for interval

### ISSUE THREAD

**Issue by Franky1** [influxdata/telegraf#9010]
## Feature Request

Add cron syntax for interval

### Proposal:

Add **cron** syntax for `interval` or introduce a new keyword `cron` that can be used (instead of interval) in the agent or plugins config.

### Current behavior:

Not implemented

### Desired behavior:

cron syntax possible for interval or a new keyword `cron` that can be used in the agent or plugins config.

### Use case: 

Query metrics at defined points in time instead of at intervals.

**Comment by ssoroka** [comment]
This is definitely interesting, but I think cron is sort of famously difficult to work with. There's websites that have spawned just to translate between cron syntax and something more human readable.

Can you tell me more about the use case? We have the ability to round the intervals to the nearest hour, for example, with `round_interval`. Are you looking for some other features, like specifying when in the hour, or to avoid collecting at certain times?

**Comment by Franky1** [comment]
> cron is sort of famously difficult to work with

Yes you are right ;-)

> Are you looking for some other features, like specifying when in the hour, or to avoid collecting at certain times?

Yes for example.
Or if I want to collect a metric once a day at a certain time, I can't do that with `interval` and `round_interval`

**Comment by mpolla** [comment]
I'm interested in collecting new data as soon as it is available at a specific time of day, e.g. 12:00:00. Using a short interval, say `interval="1m"` would do the job but would cause 1339 unnecessary excecutions during a 24h cycle when a single execution at 12:00:01 would suffice.

**Comment by Hipska** [comment]
You can just run telegraf once using cron itself for that.

**Comment by Franky1** [comment]
> You can just run `telegraf --once` using cron itself for that.
This would of course be a workaround.

But it would be nicer to have all Telegraf tasks in one config in one place.

**Comment by Hipska** [comment]
It’s not a workaround, it is the intended use for `—once`. I’ll talk with the team about this.

**Comment by Hipska** [comment]
I have had a chat with the team and came to the conclusion that implementing cron syntax is hard to cover all edge cases like DST, timezones, leap years, leap seconds, ...
Cron(tab) is the way to go for this in combination with the `--once` parameter of the telegraf command.

**Comment by Hipska** [comment]
@Franky1 you might be interested in PR #10545 as well..

**Comment by alexitheodore** [comment]
The cron-style behavior would be GREAT feature - I am very surprised that it isn't one already. Also just putting my opinion out there... I agree that using the `--once` parameter would be a work-around as Frankly1 said. I would like all my configuration/etc. in one place. Using cron to execute stuff, while technically operable, breaks the containment pattern that having everything in a config file works towards.

**Comment by knollet** [comment]
Cron-style syntax could also enable things like interval="@reboot", where the telegraf could automatically create grafana annotations when restarted. This wouldn't make sense with `--once`, because the telegraf process started by cron with `--once` wouldn't be the one I want to annotate about.

**Comment by Hipska** [comment]
@knollet I would love to see your specific use-case for grafana annotations in a new feature request.
