### ISSUE TITLE
Default to gzip=true

### ISSUE THREAD

**Issue by alsargent** [influxdata/telegraf#9018]
## Feature Request

Default Telegraf to use gzip compression to speed data ingest. 

### Proposal:

Setting `enable_gzip=True` seems to speed up ingest ~3-5x, according to benchmarks we ran about a year ago. It's a little tweak that makes a big difference and isn't well-publicized.

Right now, `enable_gzip=False` is the default if nothing is specified. This feature request is to flip that, to make the default `enable_gzip=True` is nothing is set.

### Current behavior:

If nothing is specified, Telegraf doesn't use gzip compression.

### Desired behavior:

Have Telegraf default to using gzip compression. This can be overridden in the Telegraf configuration, by setting `enable_gzip=False`.

### Use case: 

An easy way to speed up time series data ingest.

**Comment by ssoroka** [comment]
Gzip is the default for all InfluxDB outputs. Is there anything else you wanted it enabled for?

**Comment by ssoroka** [comment]
followed up with Al elsewhere. Confirmed that gzip is enabled by default as of Telegraf 1.17 for outputs.influxdb, and was always enabled for outputs.influxdb_v2. closing
