### ISSUE TITLE
fix "duplicate proto type registered"

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#9021]
Full error message: `2021/03/18 16:19:25 proto: duplicate proto type registered: k8s.io.apimachinery.pkg.api.resource.Quantity`

There are two different protobuf libaries being used, `github.com/gogo/protobuf v1.3.1` and `github.com/golang/protobuf v1.4.3`.
This could be causing the issue, but there might be another cause.

**Comment by jacobmarble** [comment]
Thank you @sspaink !
