### ISSUE TITLE
Add Master/Slave support for ActiveMQ

### ISSUE THREAD

**Issue by fabide** [influxdata/telegraf#9024]
## Feature Request
We use ActiveMQ in [Master/Slave](https://activemq.apache.org/shared-file-system-master-slave) mode. Fetching metrics from every Node in a single config and preventing Log flooding whit a master_slave opition would be awesome.

### Proposal:
Add `urls` instead of `url` and parse from an array as you can see in jolokia2_agent/http input.
Add `master_slave` to prevent flooding the logs when node is in slave mode

### Current behavior:
`url = "http://127.0.0.1:8161"`
no `master_slave` option available

### Desired behavior:
`urls = ["http://activemq01:8161", "http://activemq02:8161"]`
`master_slave = true/false`

### Use case:
In my use case we use a single telegraf machine that collects data for our services. Multiple URLs would be perfect for that situation.

**Comment by powersj** [comment]
Hi,

The option to look at multiple URLs does seem like something that would be nice, although you can always add multiple ActiveMQ plugins pointing at each system.

However, I am not certain I fully understand how the `master_slave` option would work/is necessary? Is the intention to drop any slave-specific metrics that are collected?

Thanks!
