### ISSUE TITLE
Failed to start The plugin-driven

### ISSUE THREAD

**Issue by alexrebell** [influxdata/telegraf#9025]
Good day!
I can not run Telegraf, error:

```
┌ (root💀kali)
└ systemctl restart telegraf.service 
┌ (root💀kali)
└ systemctl status telegraf.service 
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2021-03-19 13:11:01 UTC; 38ms ago
       Docs: https://github.com/influxdata/telegraf
    Process: 2555 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=exited, status=1/FAILURE)
   Main PID: 2555 (code=exited, status=1/FAILURE)
        CPU: 128ms

мар 19 13:11:01 kali systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
мар 19 13:11:01 kali systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
мар 19 13:11:01 kali systemd[1]: telegraf.service: Start request repeated too quickly.
мар 19 13:11:01 kali systemd[1]: telegraf.service: Failed with result 'exit-code'.
мар 19 13:11:01 kali systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
```

Stopped and started in debug mode:
```
┌──(root💀kali)
└─# telegraf -debug
2021-03-19T13:21:18Z I! Starting Telegraf 1.17.3
2021-03-19T13:21:18Z I! Using config file: /etc/telegraf/telegraf.conf
2021-03-19T13:21:18Z E! [telegraf] Error running agent: Error: no inputs found, did you provide a valid config file?
```

I used the instructions for setting up https://medium.com/@dorian599/iot-raspberry-pi-container-and-system-pontainering-with-influxdb-telegraf-influxdb-telegraf-and-grafana-a1767c38c109 and took from there information for the Telegraf file.

With these parameters, Telegraf does not start, tell me, please, what's wrong? What is wrong with the parameters? I'm in this case a beginner, and I can't figure out what parameters in the configuration fala are key and what you need to pay attention!
Thank you very much!

**Comment by zak-pawel** [comment]
@alexrebell It seems that you have no input plugins enabled in config file: `/etc/telegraf/telegraf.conf`.

In article you mentioned there is manual how to do that (you need to edit `/etc/telegraf/telegraf.conf` and configure plugins which you need).

**Comment by alexrebell** [comment]
Hey!

Sorry, I completely forgot about this question.
Yes, I managed to solve the problem, thank you to those who help in this topic:

https://community.influxdata.com/t/can-not-run-the-telegraf-service/18987
