### ISSUE TITLE
Docker image for linux i386

### ISSUE THREAD

**Issue by trygvis** [influxdata/telegraf#9027]
## Feature Request

Make images for linux/386 so I can run Telegraf on my Linux i386 hosts.

I'm not sure which exact images are used as upstream for the `telegraf` build, but the `alpine` ones at least have i386 images available.

### Use case:

I would be super to be able to run Telegraf on some older i386 hosts that we are required to run for compatability. There are Debian images available (yay), but it would be easier for us to just use the existing docker-compose setup we have for all other hosts. Being able to add our Linux i386 hosts to ansible helps us.

**Comment by powersj** [comment]
Hi,

Thanks for the request. We store all our Dockerfiles and entrypoints [in this repo](https://github.com/influxdata/influxdata-docker/tree/master/telegraf), which is used to generate the official DockerHub Telegraf images.

I don't think we have seen much interest in 32-bit only docker images, and as such, I am inclined to close this. I however want to point out that you could pretty easily build your own based on the above images with a small update to what package is pulled down and installed.

Thanks!
