### ISSUE TITLE
inputs.nfsclient ErrRange NFS v4.1

### ISSUE THREAD

**Issue by keith6014** [influxdata/telegraf#9028]
### Relevant telegraf.conf:

```toml
[[inputs.nfsclient]]

```

### System info:

NFS v4 (v4.1 to be precise)

### Steps to reproduce:

1. Run telegraf 1.18.0 client
2. Get an error ErrRange: line: [[EXCHANGE_ID: .... ]]

**Comment by micoq** [comment]
Same problem here:

`I! ErrRange: line:[[SETCLIENTID: 218 216 0 53568 12960 18446744073709531008 134 197]] raw:[18446744073709531008] -> parsed:[9223372036854775807]`

Maybe `uint64` should be used instead of `int64` to store these values ?

NFS v4.0
telegraf-1.18.0-1.x86_64 (RPM package)
