### ISSUE TITLE
Input: AWS Kinesis Consumer - New line delimited JSON string support 

### ISSUE THREAD

**Issue by mooyoul** [influxdata/telegraf#9031]
## Feature Request

Opening a feature request kicks off a discussion.

### Use case: 

Currently, AWS Kinesis Consumer expects single Kinesis Stream record only contains single JSON document. but single Kinesis Stream record can contain multiple JSON documents by inserting newline (\n) delimiter.

For me, this is preferred way to saving multiple log entries since this data serialization method can compatible with major data analytics softwares like Google BigQuery, AWS Athena, Presto, etc.

I think this limit can be solved easily by switching parsing method to `Parser#ParseLine` from `Parser#Parse`. Currently Kinesis Consumer implementation does not use  Parser#ParseLine method.

**Comment by sjwang90** [comment]
@mooyoul Can you provide an example of the JSON from Kinesis? 

Is this also how you think it should be solved in the new [json_v2 parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2)? This parser is where we would implement the changes. 
> I think this limit can be solved easily by switching parsing method to Parser#ParseLine from Parser#Parse. Currently Kinesis Consumer implementation does not use Parser#ParseLine method.
