### ISSUE TITLE
[AWS ECS Plugin] Collected mem_usage_percent is to small.

### ISSUE THREAD

**Issue by czd890** [influxdata/telegraf#9037]
Collected mem_usage_percent is to small (3.2330138566294421E-09).

![image](https://user-images.githubusercontent.com/4011549/112106462-ab724b80-8be8-11eb-84e0-bd312b73bce1.png)

Aws Ecs Fargate version: 1.4.0

My telegraf.conf
```conf
[agent]
  interval = "1s"
  flush_interval = "5s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 20000

[[outputs.influxdb]]
  urls = ["***"]
  database = "***"
  username = "***"
  password = "***"

[[inputs.ecs]]
  # endpoint_url = ""
  container_name_exclude = ["telegraf"]
  ecs_label_exclude = ["com.amazonaws.ecs.*"]

  # timeout = "5s"
```

**Comment by Jagularr** [comment]
Thanks for the issue. Which version of Telegraf is this? Around how high would you expect that this value should be?

From what I can find in the plugin code, it looks like this might be calculated with the following equation: `usage / limit * 100`. `usage` and `limit` should be fields that are sent along with this field, so you might be able to check that calculation. If this number is wrong, those potentially may look wrong as well.

**Comment by czd890** [comment]
My telegraf Dockerfile
```
FROM telegraf as base  # i think the imageid is b6fcc27083d0

COPY ./telegraf.conf /etc/telegraf/telegraf.conf
```
![image](https://user-images.githubusercontent.com/4011549/112248959-dd8bb800-8c91-11eb-86e8-605a45364975.png)

**Comment by czd890** [comment]
Hi @Jagularr, I think i find the root reason.

The Task Definition` added 2 containers(primary and telegraf), and the primary container not set cpu and memory/hard limits.

memory_stats.limit is 9223372036854771712 in my case.

**Comment by Jagularr** [comment]
Okay, good to hear. Is that something you were able to resolve for yourself then, or is there anything needed on the Telegraf end?

**Comment by czd890** [comment]
Thanks @Jagularr, Telegraf doesn't need to do, Maybe it can be added to https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ecs as a configuration item that needs attention.
