### ISSUE TITLE
Telegraf starts with a wrong config after installation on Debian/Ubuntu

### ISSUE THREAD

**Issue by sofixa** [influxdata/telegraf#905]
As i mentioned in #747 that isn't very practical in some use cases, but, most importantly, the Getting started docs don't mention that. Could someone please update them ?

**Comment by kostasb** [comment]
The getting started docs have been updated in v0.11 which is the latest.

https://github.com/influxdata/docs.influxdata.com/blob/master/content/telegraf/v0.11/introduction/getting-started-telegraf.md
