### ISSUE TITLE
XML parser not working in [[processors.parser]]

### ISSUE THREAD

**Issue by MilanJaro** [influxdata/telegraf#9052]
### Relevant telegraf.conf:

```
[agent]
  interval = "10s"
  round_interval = false
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "1s"
  precision = "1ms"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

# sample.xml: <xml>  <tag>t2</tag>  <field>22</field> </xml>
[[inputs.file]]
  files = ["sample.xml"]
  name_override = "xml"
  data_format = "xml"
  [[inputs.file.xml]]
    [inputs.file.xml.tags]
      tag = "/xml/tag"
    [inputs.file.xml.fields]
      field = "/xml/field"

[[processors.defaults]]
  order = 1
  [processors.defaults.fields]
    xml_field  = '<xml_field>222</xml_field>'

# add field from xml structure
[[processors.parser]]
  order = 2
  data_format = "xml"
  merge = "override"
  drop_original = false
  parse_fields = ["xml_field"]
  [[processors.parser.xml]]
    [processors.parser.xml.fields]
      xml_field = "/xml_field"
```

### System info:

Telegraf 1.18.0
ubuntu 20.04 LTS
uname -a
Linux xxx 5.8.0-33-generic #36~20.04.1-Ubuntu SMP Wed Dec 9 17:01:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Docker

n/a

### Steps to reproduce:
Execute "telegraf --config telegref.conf --test"

### Expected behavior:

Telegraf config containing [[processors.parser]] will be able to use XML parser

### Actual behavior:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91cffd]

goroutine 10 [running]:
github.com/influxdata/telegraf/plugins/parsers/xml.(*Parser).Parse(0xc0000ee120, 0xc000582040, 0x1a, 0x20, 0x1a, 0x20, 0x0, 0x1, 0xc00006dd7c)
        /go/src/github.com/influxdata/telegraf/plugins/parsers/xml/parser.go:61 +0x4fd
github.com/influxdata/telegraf/plugins/processors/parser.(*Parser).parseField(...)
        /go/src/github.com/influxdata/telegraf/plugins/processors/parser/parser.go:117
github.com/influxdata/telegraf/plugins/processors/parser.(*Parser).Apply(0xc000126700, 0xc00053e310, 0x1, 0x1, 0xc00053e300, 0xc00006ded8, 0x7b8e2a)
        /go/src/github.com/influxdata/telegraf/plugins/processors/parser/parser.go:68 +0x4e6
github.com/influxdata/telegraf/plugins/processors.(*streamingProcessor).Add(0xc0002c53e0, 0x42e8238, 0xc0005f2f50, 0x42dc618, 0xc00007e720, 0xc00007de01, 0xc000070101)
        /go/src/github.com/influxdata/telegraf/plugins/processors/streamingprocessor.go:37 +0x82
github.com/influxdata/telegraf/models.(*RunningProcessor).Add(0xc0002c5530, 0x42e8238, 0xc0005f2f50, 0x42dc618, 0xc00007e720, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/models/running_processor.go:95 +0x108
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc000227930, 0xc00029d350)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:559 +0x157
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors
        /go/src/github.com/influxdata/telegraf/agent/agent.go:554 +0x91

### Additional info:

```
cat >sample.xml <<EOF
<xml>
        <tag>t2</tag>
        <field>22</field>
</xml>
EOF
```

**Comment by JarD55** [comment]
+1

**Comment by sjwang90** [comment]
Resolved in https://github.com/influxdata/telegraf/pull/9283
