### ISSUE TITLE
Input plugin mysql.conf "gather_binary_logs" is not compatible for mysql 8.0

### ISSUE THREAD

**Issue by zzcpower** [influxdata/telegraf#9063]
Hi there,

The error log  is generated by "gather_binary_log" in mysql.conf for mysql 8.0

Telegraf runs successfully in mysql 5.7. And it runs successfully if I comment the "gather_binary_logs = True" for mysql 8.0

In my opinion, the problem is occurred because of the update of binary log in mysql 8.0
If we look at the difference of binary log between 8.0 and 5.7, we can find that there is one more column "Encrypted" in mysql 8.0. It seems that our code mysql.go has not been compatible with this update yet.

See the difference of binary logs in the links below.
https://dev.mysql.com/doc/refman/8.0/en/show-binary-logs.html
https://dev.mysql.com/doc/refman/5.7/en/show-binary-logs.html

THANKS
Zichu

**Comment by Jagularr** [comment]
Hi, this makes sense and thanks for the issue. Would you be able to add an example of an error log you receive when this error occurs?

**Comment by zzcpower** [comment]
Sure
E! [inputs.mysql] Error in plugin: sql: expected 3 destination arguments in Scan, not 2

**Comment by Jagularr** [comment]
This should be simple enough to implement, will hopefully get to this at some point.
