### ISSUE TITLE
Add default configuration params to plugin docs

### ISSUE THREAD

**Issue by ingria** [influxdata/telegraf#9065]
### Proposal:

I suggest mentioning the default params (like `order` and `alias` in processors, or metric filtering anywhere) in the plugin documention.

### Use case: 

This is completely unobvious for a new users (like myself) that there are some config params common for all plugins. I was stuck for a couple of days until I've found [this](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) page, which describes some very important features. I was using the [official docs](https://docs.influxdata.com/telegraf/v1.18) and it doesn't mention about that common params until the very end (in "Administration" section, which is the last one).

For example, here's my workflow (I've never used Telegraf before):

- I open the [docs page](https://docs.influxdata.com/telegraf/v1.18)
- Read about processors
- Decide that I definitely need some plugin (e. g. clone)
- Open the [plugin docs](https://github.com/influxdata/telegraf/blob/release-1.18/plugins/processors/clone/README.md)
- Have no idea of how to apply this processor for only specific metrics or execute this processors before others

**Comment by ingria** [comment]
Maybe something like this in the end of the README.md:
```diff
+This plugin also supports [metric filtering](CONFIGURATION.md#metric-filtering) and some [additional common options](CONFIGURATION.md#processor-plugins).
```

**Comment by sjwang90** [comment]
Thanks for for bringing up the issue @ingria. This is really helpful feedback about the obstacles you were running into. 

We're going to discuss this internally with our documentation team. We'll reach out if we have any other questions about your experience using the docs to get started with Telegraf.

**Comment by ingria** [comment]
So the logparser is the the only plugin that uses order and alias fields?

**Comment by powersj** [comment]
> So the logparser is the the only plugin that uses order and alias fields?

You are right I totally botched this... let me figure out how to either mass add this or add this in a more central location.

**Comment by powersj** [comment]
Yep I was looking at docs issues today and got your recommendation and my investigation of #3296 mixed up. I'll circle back in the morning.

**Comment by powersj** [comment]
@sjwang90, @reimda,

Alright, here is my proposal for what we add to all four types of READMEs. I am doing this in a comment, rather than an MP as I don't want to go edit a few hundred files till we have this somewhat figured out:

Add the following to the Configuration section if it exists, or create it:

```
## Configuration 

In addition to the plugin-specific configuration settings, plugins
support additional global configuration settings. These settings are 
used to modify metrics, tags, and field or create aliases and configure
ordering, etc. See the CONFIGURATION.md for more details.
```

See the [example.md](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/example/README.md) for what we use as the template for README.md. This section may need to be added to some output, aggregator, and processor plugins.

**Comment by sjwang90** [comment]
LGTM! Thanks!

**Comment by hassanbabaie** [comment]
> @sjwang90, @reimda,
> 
> Alright, here is my proposal for what we add to all four types of READMEs. I am doing this in a comment, rather than an MP as I don't want to go edit a few hundred files till we have this somewhat figured out:
> 
> Add the following to the Configuration section if it exists, or create it:
> 
> ```
> ## Configuration 
> 
> In addition to the plugin-specific configuration settings, plugins
> support additional global configuration settings. These settings are 
> used to modify metrics, tags, and field or create aliases and configure
> ordering, etc. See the CONFIGURATION.md for more details.
> ```
> 
> See the [example.md](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/example/README.md) for what we use as the template for README.md. This section may need to be added to some output, aggregator, and processor plugins.

Hi @powersj just checking if this got updated, I have rasied a similar issue

https://github.com/influxdata/telegraf/issues/11668

Based on looking at the [running_aggregator.go](https://github.com/influxdata/telegraf/blob/64c85eb4f83c7710cfe62cede20cbd7ff873f2b1/models/running_aggregator.go#L68) it doesn't support the ordering feature?

**Comment by powersj** [comment]
@hassanbabaie,

Correct, order is only used for [processor plugins](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#processor-plugins).

**Comment by powersj** [comment]
Going to re-open until we have this in all the plugin READMEs
