### ISSUE TITLE
Doc search for v1.18 doesn't work

### ISSUE THREAD

**Issue by ingria** [influxdata/telegraf#9066]
[1.18](https://docs.influxdata.com/telegraf/v1.18/):
![118](https://user-images.githubusercontent.com/2178368/112873755-bc302f00-90ca-11eb-80b5-c2482684dafc.png)

[1.17](https://docs.influxdata.com/telegraf/v1.17/) and older:
![117](https://user-images.githubusercontent.com/2178368/112873768-c0f4e300-90ca-11eb-8f82-d05df95df863.png)

**Comment by sjwang90** [comment]
Hey @ingria - Thanks for the issue! Issues for our docs.influxdata.com site are actually on the https://github.com/influxdata/docs-v2/tree/master/content/telegraf/v1.18 repo.

Could you open the issue there? Thanks!

**Comment by ingria** [comment]
Sure. https://github.com/influxdata/docs-v2/issues/2362
