### ISSUE TITLE
[inputs.exec] doesn't return docker's volume size

### ISSUE THREAD

**Issue by gogainda** [influxdata/telegraf#9070]
### Relevant telegraf.conf:

```toml
[[inputs.exec]]
 commands = ["/dsize.sh"]
 timeout = "10s"
 data_format = "influx"
```
```bash
#!/bin/bash


for d in `docker ps -a | awk '{print $1}' | tail -n +2`; do
    d_name=`docker inspect -f {{.Name}} $d`

	VOLUME_IDS=$(docker inspect -f "{{.Config.Volumes}}" $d)
	VOLUME_IDS=$(echo ${VOLUME_IDS} | sed 's/map\[//' | sed 's/]//')
	
	array=(${VOLUME_IDS// / })
	for i in "${!array[@]}"
	do
		VOLUME_ID=$(echo ${array[i]} | sed 's/:{}//')
		VOLUME_SIZE=$(docker exec -ti $d_name du  -d 0 ${VOLUME_ID} | awk '{print $1}' | sed 's/$/i/')
		echo "exec,conainer=$d_name volume_size=$VOLUME_SIZE,v=1i" 
	done

done
exit 0
```

### Steps to reproduce:
If I run dsize.sh it give me correct output (with `size` values), but when I do a test run using telegraf it returns such error: 
```
 Error in plugin: metric parse error: expected field at 1:66: "exec,conainer=/kurim_web.1.h210jqwk6l3t80l5m5eg3lp66 volume_size=,v=1i"

```
which means that  `size` was not populated

### Expected output
```
exec,conainer=/kurim_web.1.h210jqwk6l3t80l5m5eg3lp66 volume_size=4i,v=1i
```

**Comment by x70b1** [comment]
You don't get a response from the docker daemon when a container is stopped.
You should see log lines like:

```
Error response from daemon: Container xxxxxxxx is not running
```

If you use `docker ps` instead of `docker ps -a` in line 3, it works.

As another recommendation, you should use the JSON api together with [`jq`](https://stedolan.github.io/jq/tutorial/).
This makes the script less buggy.

**Comment by gogainda** [comment]
in my case it happens even for running containers, `volume_size` is empty

**Comment by x70b1** [comment]
Well, then the script is still broken.

**Comment by gogainda** [comment]
I checked the logs here : less /var/log/telegraf/telegraf.log
and it printed such error : `The input device is not a TTY` which means that I shouldn' use `-t` for `docker exec` command.
Fixed!
