### ISSUE TITLE
Bring additional libraries to starlark

### ISSUE THREAD

**Issue by ricrug** [influxdata/telegraf#9071]
## Feature Request
It would be useful to be able to integrate functionality into the starlark plugin that would allow access to external resources, e.g. for data enrichment.

### Proposal:
It would be a great help if the starlark interpreter could have libraries like Starlib to access external resources.
[StarLib](https://github.com/qri-io/starlib)

### Current behavior:
N.A.

### Desired behavior:
`load("encoding/csv","csv")`
`data = csv.read_all(...)`

### Use case: 
Data enrichment using starlark scripts is very useful but the integration of many functionalities, such as those provided by starlib, could be of considerable help in overcoming some of the current limitations of the stack.

**Comment by ssoroka** [comment]
FYI we've already added math and time support, and regular expression support is on the way. 

Regarding csv importing via HTTP requests: allowing the processors to make network calls would kill the performance of them, but it might make sense if there was such a thing as a Starlark input plugin. Could be a good suggestion there.

**Comment by ricrug** [comment]
> FYI we've already added math and time support, and regular expression support is on the way.
> 
> Regarding csv importing via HTTP requests: allowing the processors to make network calls would kill the performance of them, but it might make sense if there was such a thing as a Starlark input plugin. Could be a good suggestion there.

I agree with you about performances. 
But, maybe I didn't explain myself well. Actually my comment was, incorrectly, too vague. I have a csv file that I want to use to enrich my data coming through mqtt messages.

**Comment by Hipska** [comment]
Hi @ricrug, You can achieve this with [the execd processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors).

**Comment by powersj** [comment]
Closing this as the execd processor as pointed out above allows the remaining functionality.
