### ISSUE TITLE
inputs.http should allow setting Transfer Encoding

### ISSUE THREAD

**Issue by jmbwell** [influxdata/telegraf#9078]
## Feature Request

Provide a means for telling the go http client to use Transfer-Encoding: identity instead of chunked.

### Proposal:

Add a parameter such as `transfer_encoding` allowing plugin users to specify `identity` when needed.

I'm not a go developer, but it might look something like this.

From here:

https://github.com/influxdata/telegraf/blob/885bf273a929e1f92f242f75dc27749b193e3a90/plugins/inputs/http/http.go#L20-L25

…could add TransferEncoding:

```
type HTTP struct {
	URLs            []string `toml:"urls"`
	Method          string   `toml:"method"`
	Body            string   `toml:"body"`
	ContentEncoding string   `toml:"content_encoding"`
	TransferEncoding []string   `toml:"transfer_encoding"`
```

And then somewhere down below this:

https://github.com/influxdata/telegraf/blob/885bf273a929e1f92f242f75dc27749b193e3a90/plugins/inputs/http/http.go#L192-L195

…add something like this (TransferEncoding is expected to be a list. Can copy directly from plugin config?):

```
	if h.TransferEncoding != "" {
		request.TransferEncoding = h.TransferEncoding
	}

```

### Current behavior:

The http plugin indicates no preference for transfer encoding to the go http client and provides no way for the user to indicate this preference to the go http client.

### Desired behavior:

The http plugin provides a means for specifying the transfer encoding to be used by the go http client.

### Use case: 

- An API host might not be liberal in what it accepts.
- Changes to the API host queried by telegraf may not be possible, such as with embedded systems, closed systems, or systems managed by another entity. 
- The API host may not accept chunked requests, but the telegraf http plugin cannot make anything except chunked requests.
- If the API host cannot accept chunked requests, the telegraf http plugin cannot be used.

telegraf plugin: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http/http.go
go http client documentation: https://golang.org/pkg/net/http/#Request (see "TransferEncoding")

Sample request posted to API host by current plugin — note the chunk size value preceding the request body and the '0' trailing it — API hosts not expecting a chunked request or not able to handle it may reject the request as being invalid:

```
POST / HTTP/1.1
Host: 127.0.0.1
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Content-Type: text/plain
Accept-Encoding: gzip

114
<request body>
0
```

How the same request would look without chunked encoding — note the absence of the length values:

```
POST / HTTP/1.1
Host: 127.0.0.1
User-Agent: Go-http-client/1.1
Transfer-Encoding: identity
Content-Type: text/plain
Accept-Encoding: gzip

<request body>

```

**Comment by MyaLongmire** [comment]
Thank you for the feature request. Unfortunately after some digging into the plugin the net/http package no longer supports identity as a transfer encoding option as it is a security issue. Please refer to this [link](https://github.com/golang/go/issues/38867) for more information. Is there an option to add chunked support to you API?

**Comment by jmbwell** [comment]
In the case that prompted my submission, no, the API is proprietary and controlled by a commercial third party and cannot readily be updated to support chunked. Thank you!

**Comment by Ctrl-LeftAlt-Delete** [comment]
Did you find a way around this?
Telegraf is sending POST requests as Transfer-Encoding: chunked for me and the equipment I'm querying does not like that. When I query it from a regular web browser, the request goes in a single frame and it works OK.

**Comment by jmbwell** [comment]
We developed our own intermediary agent to pull from the device API and then push to influxdb.

**Comment by piotrp** [comment]
@MyaLongmire how about dropping `Tranfer-Encoding` header from requests and using plain POST with `Content-Length` header?
