### ISSUE TITLE
[inputs.ping] ping failed: failed to run pinger: socket: permission denied

### ISSUE THREAD

**Issue by BEN-59** [influxdata/telegraf#9084]
``can someone help me please, i run telegraf with docker and i have this error :

2021-04-01T21:02:10Z E! [inputs.ping] ping failed: failed to run pinger: socket: permission denied
`````

**Comment by sspaink** [comment]
I believe this change should help you fix this problem: https://github.com/influxdata/telegraf/pull/9072
You can grab the artifacts linked in the comment by the bot telegraf-tiger.
