### ISSUE TITLE
aggregators.valuecounter.tags does not work as expected

### ISSUE THREAD

**Issue by ihard** [influxdata/telegraf#9085]
### Relevant telegraf.conf:

```
[global_tags]
  my_tag_period = "10s"


[[inputs.tail]]
  files = ["/var/log/my.log"]
  data_format = "grok"
  grok_patterns = ['%{TIMESTAMP_ISO8601:logdate} %{NUMBER:pid:int} %{LOGLEVEL:level} %{GREEDYDATA:data:drop}']

[[aggregators.valuecounter]]
  period = "30s"
  drop_original = true
  fields = ["level"]

  [aggregators.valuecounter.tags]
    my_tag_period = "30s"

```

### System info:

Ubuntu 18.04 
Telegraf 1.18.0

### Expected behavior:

Metric with tag my_tag_period=30s

### Actual behavior:

Metric with tag my_tag_period=10s

**Comment by powersj** [comment]
Hi,

Unfortunately, it looks like global tags take precedence and get applied last. You can take a look [here](https://github.com/influxdata/telegraf/blob/381dc2272390cd9de1ce2b047a953f8337b55647/models/makemetric.go#L34).

I am going to go ahead and close this as changing this behavior is not something we would want to do to prevent breaking others who expect this.

Thanks!
