### ISSUE TITLE
telegraf tail plugin character limit per line

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/telegraf#9089]
### Relevant telegraf.conf:

```toml

```

### Steps to reproduce:

1. enable telegraf tail plugin and monitor a file
2. push logs where each line is 1mb long

### Expected behavior:

Provide a config option to restrict the maximum number of characters for each line ( which can be truncated ) so that it doesnt throw a 413 entity too large when pushed to influx and it doesnt hold a lot of memory.
### Actual behavior:

When telegraf tries to flush 1000 metrics to influx ( default batch size ) , it throws a 413 entity too large and holds around 1gb of memory.

**Comment by Jagularr** [comment]
Hi, could you provide an example of your tail config, to get a sense of the type of data you're ingesting? I think if we want tail to be able to stop reading a line at a certain point and pick up after it, it would need to be able to intelligently break that line up into individual metrics. What causes one megabyte of characters to be written to a single line in your file, or does this long line actually represent many separate metrics?

**Comment by prashanthjbabu** [comment]
@Jagularr  Thanks for your response .  Here's a sample config
```
[[inputs.tail]]
  files = ["/home/ubuntu/experiment/log/simulation.log"]
  data_format = "value"
  data_type = "string"
```
`simulation.log` is a file generated by a third party application which we have no control of . Incase that application outputs a 10,00,000 character string ( which we have no control of ) it could cause this issue. 
For example : Consider the following snippet
```
a := "xxxx" // where xxx is the 10,00,000 character string
log.Println(a) // printing the 10,00,000 character string as ONE line
```
Although an application shouldnt have such log prints as it is bad practice , telegraf should have a way to prevent itself from eating too much memory because of this and instead think of dropping it ( based on some character limit config )

**Comment by Jagularr** [comment]
I suppose we could implement a line length check and drop metrics that are too large, although reading that 1mb line might still at least temporary use 1mb of memory, unless we read it character-by-character. Since in your case it seems like it's one metric per line, I don't see a good way of splitting it up

**Comment by prashanthjbabu** [comment]
@Jagularr thanks for your  response. The line length check makes sense . Even though we read it character-by-character we will still end up holding 1mb of memory for a bit until the metrics are flushed by telegraf!

**Comment by powersj** [comment]
The length of strings produced by inputs is outside of our control. The 413 received by InfluxDB is also outside our control. Users can use the split extremely large metrics with the starlark processor or large strings using groups and regex.
