### ISSUE TITLE
Input Plugin filecount question

### ISSUE THREAD

**Issue by gallofeliz** [influxdata/telegraf#9094]
Hi,

I am using filecount plugin to have directories size. A `du -hs` on a directory returns "300M" and filecount "150M" (a directory with a lot of small files).

After investigation, I understand :
- `du -hs` give the sum() of each files/dirs size on the disk
- filecount give the sum() of each files (dirs also ?) content (equiv `du -hs --apparent-size`)

Am I right ?

Regards.

**Comment by Jagularr** [comment]
This plugin should count all files that exist within the configured directory, as well as all files that exist within all sub-directories of your configured directory, unless the `recursive` flag is set to false, in which case it will only count files (not folders) in only the directory that you've configured. It will return a total count of files and total sum of the sizes of all the files, per the documentation. Let me know if this clears it up at all, wasn't sure exactly what to clarify.

**Comment by gallofeliz** [comment]
Hi @Jagularr,

Thanks for your anwser. What is size of a file ? a file that contains 1 char will have 1 byte size, or a block (4.0K in my case) ?

For example :
- `echo -n 'a' > /tmp/test`
- `du -hs /tmp/test` will show "4,0K"
- `ls -lh /tmp/test` will show "1"

I have not particular knowledge about filesystems but as I know this file will use 4K on my disk, so 4096 * the real place. That is not a detail.

So, what will return telegraf filecount ? 1 or 4096 ? The file content size or the memory the file takes on the disk ?

It is possible my question is stupid, and I'm sorry. But my directory has 300M with `du` and 150M with filecount, and I can't ignore that if I am serious.

Thanks.
Regards.

**Comment by gallofeliz** [comment]
Other point : The filecount doesn't count the directories (and subdirectories), only files ? With a lot of directories, that can make a big difference.

I suppose filecount is not what I search, but it should be great to be clear about what it does. On a system, is it more interesting to have content size or disk usage ?

Regards.

**Comment by Jagularr** [comment]
Good question, I believe the [golang function](https://stackoverflow.com/questions/40795488/get-the-actual-file-size-vs-apparent-size-in-go) we are using returns what is equivalent to 'apparent size', which should be smaller than the actual disk size taken up, if I gather what I've read correctly. For example, if I have it stat a file with just a '1', it will return byte size of 1. 

When I tested it just now it appears to not include folders in its file 'count'. It will count the files within those folders, but not the presence of a folder itself.

**Comment by Jagularr** [comment]
That makes sense to me, we appreciate the suggestions! I will keep this in mind for future upgrades. Definitely should update the documentation.
