### ISSUE TITLE
[input.vsphere] Support vSphere version 7.0

### ISSUE THREAD

**Issue by nagavenkateshgowru** [influxdata/telegraf#9102]
## Feature Request

As of now, the vSphere plugin supports version 5.5 through 6.7 as per the documentation.  Would you please provide the support for the latest vSphere version 7.0

### Proposal:
Please support the vSphere plugin for version 7.0

### Current behavior:
Currently, this plugin supports 5.5 to 6.7 versions.

### Desired behavior:
Support the vSphere plugin for version 7.0

### Use case: 
With the latest features in the vSphere 7.0 most of the enterprises would upgrade to 7.0 and supporting this latest version really helps.

**Comment by jorgedlcruz** [comment]
I am using it on vSphere 7.0 Update 2, and ran from 7.0, 7.0 U1, never had an issue, must be just a small thing to edit on the documentation, perhaps.

**Comment by mattpoel** [comment]
I also implemented it today in a 7.0 something environment and didn’t face an issue so far.

**Comment by prydin** [comment]
vCenter 7.0 is supported. Just pushed a PR with an update to the README to reflect that.
