### ISSUE TITLE
Add OpenTelemetry Output plugin

### ISSUE THREAD

**Issue by codeboten** [influxdata/telegraf#9108]
## Feature Request

This feature request is to provide an output plugin from telegraf to the OpenTelemetry protocol (OTLP).

### Proposal:
Add an output plugin for OTLP.

### Current behavior:
No such output exists.

### Use case:
Using telegraf I want to be able to send metrics data to OTLP backends.

**Comment by jacobmarble** [comment]
FYI https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2951

**Comment by sjwang90** [comment]
Included in https://github.com/influxdata/telegraf/pull/9228
