### ISSUE TITLE
Remove Telegraf repo Wiki content

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9119]
### Goals
Remove Telegraf GitHub Wiki content - all developer guides and GitHub information going forward should be in [docs folder](https://github.com/influxdata/telegraf/tree/master/docs) or [CONTRIBUTING.md](https://github.com/influxdata/telegraf/blob/master/CONTRIBUTING.md)

### To do
under /docs:
- Create `developers` folder
  - Create a file for each [bullet point in Wiki > Developers](https://github.com/influxdata/telegraf/wiki/Developers#contents)
- Create `maintainers` folder
  - Create a file for each [bullet point in Wiki > Maintainers](https://github.com/influxdata/telegraf/wiki/Maintainers#contents)

in [CONTRIBUTING.md](https://github.com/influxdata/telegraf/blob/master/CONTRIBUTING.md):
- link to /docs/developers folder so users can find developer wiki content

Add redirects in Wiki of new locations
- Create redirect links to new location in Wiki for a minimum of 6 months

### Summary 
Location of information in Wiki (Existing >> New)
- Developers >> docs/developers (with a link in the contributing.md)
- Maintainers >> docs/maintainers
- Users >> [customer facing docs](docs.influxdata.com)

**Comment by ssoroka** [comment]
> for a minimum of 6 months

Let's make that permanent. Never know what links there.
