### ISSUE TITLE
inputs.nfsclient unable to collect operations beyond read and write

### ISSUE THREAD

**Issue by timmyj** [influxdata/telegraf#9127]
i am looking to collect stats on NFS metadata operations from our clients
with configuration below and full stat without "include_operations" I still only see read and write metrics (and none of the other operations being collected.
 ```
[[inputs.nfsclient]]
    fullstat = true
    include_operations = ["READ","WRITE","READDIRPLUS","READDIR"]
```

**Comment by papey** [comment]
Hi @timmyj I faced this problem yesterday too and i am currently working on/testing a fix, everything is in #9128 if you want to build against the branch and test it.
