### ISSUE TITLE
Telegraf inputs.prometheus will add new field host and URL and it will overwrite existent prometheus labels

### ISSUE THREAD

**Issue by valdemarpavesi** [influxdata/telegraf#9137]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

create a new flag   omit_url=true

[agent] 
  omit_hostname=true
   omit_url=true
   
   
   and change the field names to be:  "thost" and "turl" to not create any trouble to existent Prometheus labels.

### Current behavior:

it overwrites existent Prometheus labels. host and URL

### Desired behavior:

new flag and rename the fields

**Comment by Jagularr** [comment]
Hi! Looks like we have an option for omit_hostname and looks like the url tag can be named in a configurable way in the prometheus plugin. Using these, are you able to prevent overlap? Or is your request more-so to free up those specific words? Thank you.

**Comment by valdemarpavesi** [comment]
Hi @Jagularr, yes, it will require more.

we do have several metrics from Prometheus with URL, like got response 400, and here is the URL.

but, Telegraf during the conversion will add a hardcode URL with a federate URL.

We shall have the option:

[agent]
omit_hostname=true/false
omit_url=true/false

if false,  the new field added by Telegraph shall not overwrite the existent Prometheus-labels.

thost= telegraf.host
turl="HTTP://federate.address.com 


host = have the origin hostname
url = have the origin url

**Comment by valdemarpavesi** [comment]
example:

it is stored into influxDB

using omit_hostname=true
`
prometheus_http_request_duration_seconds_bucket {group="prom", handler="/api/v1/label/:name/values", instance="localhost:9090", job="prometheus", le="+Inf", url="http://localhost:9090/federate?match[]={__name__=~".*"}"}`

**Comment by helenosheaa** [comment]
As @Jagularr said you can change the url tag to be something different if you look [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L55)

Maybe I'm missing something, could you provide an example of a Prometheus input, the output in influxDB currently and what you would the influxDB output to be instead?

**Comment by redbaron** [comment]
@valdemarpavesi , you can rename tag used to record target url used to collect metrics from with `url_tag` plugin option.

`hostname` is added by Telegraf to all metrics and can be removed with `omit_hostname` agent option.

**Comment by powersj** [comment]
closing this one as well. Thanks @redbaron for the comment.
