### ISSUE TITLE
Procstat plugin truncates process_name with spaces on macOS

### ISSUE THREAD

**Issue by jblesener** [influxdata/telegraf#9145]
The procstat plugin of telegraf truncates the name of any process on macOS that contains spaces. This is a not uncommon occurence on macOS, some examples are Google Chrome, Docker Desktop, and System Preferences. I have upstreamed a fix into gopsutil (https://github.com/shirou/gopsutil/issues/1034) that fixes the underlying issue.

### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
  pattern = "Google"
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### System info:

Telegraf 1.18.0
macOS 11.2.3

### Steps to reproduce:

1. Start an executable with spaces in the name like Google Chrome, Docker Desktop, System Preferences, etc.
2. Use the procstat module to get information about the process

### Expected behavior:

The process_name field should contain spaces:
procstat,host=mbp.local,pattern=Google,process_name=Google\ Chrome\ Helper\ (Renderer),user=localuser memory_data=0i,memory_usage=0.21712779998779297,cpu_time_nice=0,cpu_time_steal=0,cpu_time_guest_nice=0,memory_swap=0i,memory_vms=43527802880i,memory_locked=0i,pid=85403i,cpu_time_system=0.68,cpu_time_soft_irq=0,memory_rss=37302272i,cpu_time_iowait=0,cpu_time_irq=0,cpu_usage=0,memory_stack=0i,num_threads=15i,created_at=1618109781000000000i,cpu_time_user=0.64,cpu_time_idle=0,ppid=48436i,cpu_time_guest=0 1618728160000000000

### Actual behavior:

procstat,host=mbp.local,pattern=Google,process_name=Google,user=localuser cpu_time_system=17.39,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_steal=0,cpu_time_guest=0,memory_swap=0i,memory_data=0i,memory_locked=0i,memory_usage=0.44155120849609375,created_at=1618088866000000000i,cpu_time_user=110.5,cpu_time_soft_irq=0,memory_vms=43659759616i,ppid=48436i,pid=76537i,num_threads=17i,cpu_time_idle=0,cpu_time_guest_nice=0,memory_rss=75857920i,memory_stack=0i 1618728370000000000

**Comment by sspaink** [comment]
Resolved in: #9224
