### ISSUE TITLE
Add null output

### ISSUE THREAD

**Issue by joshuaspence** [influxdata/telegraf#915]
We are running Telegraf in different environments. In our production environment, we have Telegraf configured with a single output. In our dev environment, however, we currently have no environments configured. It seems that Telegraf cannot run with no outputs configured:

```
> sudo telegraf -config /etc/telegraf/telegraf.conf -test
2016/03/22 20:06:32 Error: no outputs found, did you provide a valid config file?
```

**Comment by sparrc** [comment]
You could just use the file output (and send to /dev/null)

**Comment by sparrc** [comment]
Maybe I don't fully understand the use-case, but you can just do this:

```toml
[[outputs.file]]
  files = ["/dev/null"]
```

you can also specify just "stdout" to get it to print the metrics to the screen.

**Comment by joshuaspence** [comment]
Yes, a file set to `/dev/null` would work, but it just feels a bit odd to me. Why should Telegraf care if there are no outputs configured?

**Comment by sparrc** [comment]
I can't really think of a logical behavior without outputs configured, what would you expect it to do?

**Comment by joshuaspence** [comment]
I'd expect Telegraf to run but to just not route the output anywhere.

**Comment by sparrc** [comment]
but why would you want to do that? IMO that's misconfigured, and it should exit. You could easily imagine someone doing that on accident and then not realizing that telegraf isn't doing anything, since it doesn't fail.

**Comment by joshuaspence** [comment]
For consistency across different environments, I'd like to run Telegraf everywhere... even if we don't have anywhere to send the output to. I don't think that this is a misconfiguration, but you could output a warning instead of a hard fail perhaps?

**Comment by sparrc** [comment]
I think I'm going to keep it as-is, outputting a warning is great if everyone pays attention to the logs, but in practical situations I don't think that's realistic. IMHO it's working as intended, and I think setting up [[outputs.file]] for you is a reasonable workaround.
