### ISSUE TITLE
poll_interval_disabled

### ISSUE THREAD

**Issue by falon** [influxdata/telegraf#9155]
https://github.com/influxdata/telegraf/blob/916ac99675a321ba679bd6f0b4f3188770b92c0c/plugins/common/shim/example/cmd/main.go#L16

Maybe did you mean "disable plugin" if `true`?

Or maybe if `true` does Telegraf control the polling using `interval` from plugin configuration file?

**Comment by ssoroka** [comment]
Should say `"set to true to disable polling. You want to use this when you are sending metrics on your own schedule"`, will update.
