### ISSUE TITLE
snmp include/exclude regex ?

### ISSUE THREAD

**Issue by glz-io** [influxdata/telegraf#916]
Hi,

It seems exclude_instances and include_instances for "inputs.snmp.host.table" are not regex but exact name of the instance.

Is it possible to change that to regex match ?

This way, we can exclude all "Vlan" interfaces or include all "Fa0/" interfaces

Regards

**Comment by titilambert** [comment]
Hello ! Regex are not adapted to keep good performance in Telegraf.
What about check if instances "contains" or not the "pattern" ?

**Comment by glz-io** [comment]
@titilambert  That's ok for me.

**Comment by sparrc** [comment]
@titilambert you could also do a Glob match, same as how namedrop, tagdrop, etc. do it. see https://github.com/influxdata/telegraf/blob/master/internal/internal.go#L131

**Comment by sparrc** [comment]
for more flexibility and power we could also move to using this glob library: https://github.com/gobwas/glob

**Comment by danielnelson** [comment]
@glz-io @titilambert  A lot has changed since this issue was opened, does the new snmp plugin along with the measurement filtering options now provide what you need?

**Comment by glz-io** [comment]
Hi

I have a new job since a few months and I did not use anymore the snmp plugin for telegraf. So I have no way to test.

**Comment by danielnelson** [comment]
@glz-io Thanks for the update and congrats on the new job!

I'm going to close this issue, @titilambert, if it is still an issue please reopen with an update.

**Comment by crawc** [comment]
I had this same need to only collect data for interfaces matching regex patterns or by interface name, description, alias, etc. Is there any way to do this?
