### ISSUE TITLE
Add proxy support for inputs plugin x509_cert 

### ISSUE THREAD

**Issue by jia2** [influxdata/telegraf#9174]
## Feature Request

Add proxy support for inputs plugin x509_cert 

### Proposal:
add option **http_proxy**  as in http_response to support access a target via proxy

### Current behavior:
no proxy support

### Desired behavior:
proxy support is added

### Use case: 
Can't access a target site directly and need to configure a proxy

**Comment by powersj** [comment]
next steps: review #9319 after a rebase
