### ISSUE TITLE
Collect Network collisions in Net plugin

### ISSUE THREAD

**Issue by clever-trevor** [influxdata/telegraf#9176]
## Feature Request
I would like to see # collisions per Network interface being collected as part of the Net Input plugin to provide better data and therefore better monitoring

### Proposal:
Add "collisions" as metric in Net plugin

### Current behavior:
Not available

### Use case
Whilst Net plugin has many useful metrics, collisions are not present.

The value is present in an "ifconfig" as shown below :
```
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.121  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 08:00:27:6e:52:31  txqueuelen 1000  (Ethernet)
        RX packets 211  bytes 49920 (48.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 71  bytes 10511 (10.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And also in /proc/net/dev under the cols column
```
 cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:   69629     563    0    0    0     0          0         0    69629     563    0    0    0     0       0          0
enp0s3:  101327     470    0    0    0     0          0         4    21669     153    0    0    0     0       0          0
```

**Comment by powersj** [comment]
next steps: looks like gopsutil is used to collect network stats, see if this is already exposed and add it as an additional field
