### ISSUE TITLE
Log rotation detection issue when fail2ban scanning the same file

### ISSUE THREAD

**Issue by sbouchex** [influxdata/telegraf#9186]
### Relevant config:

fail2ban jail:
root@vps819892:~# cat /etc/fail2ban/jail.d/sgdf.conf
```
[nginx-noscript-get]
port    = http,https
logpath = %(nginx_access_log)s
```

fail2ban filter:
root@vps819892:~# cat /etc/fail2ban/filter.d/nginx-noscript-get.conf
```
[Definition]
failregex = ^<HOST> -.*GET.*(\.php|\.asp|\.exe|\.pl|\.cgi|\.scgi)
ignoreregex =
```

telegraf config:
```
[[inputs.logparser]]
  files = ["/var/log/nginx/access.log"]
  from_beginning = true
  name_override = "nginx_access_log"
  [inputs.logparser.grok]
    patterns = ["%{COMBINED_LOG_FORMAT}"]
```

### System info:

root@vps819892:~# telegraf --version
Telegraf 1.18.1 (git: HEAD d3ac9a3f)

root@vps819892:~# cat /etc/debian_version
9.13

Fail2Ban v0.9.6 (from debian distribution)

### Steps to reproduce:

1. Install nginx to have some web traffic
2. Configure fail2ban to scan the /var/log/nginx/access.log file (see above)
3. Configure telegraf to scan the /var/log/nginx/access.log file (see above)
4. Wait to log rotation (done by crond)

### Expected behavior:

nginx telegraf metrics should not be interrupted (i.e. empty)

### Actual behavior:

nginx telegraf metrics stops once the nginx logs are rotated

**Comment by powersj** [comment]
Hi,

Can you provide the actual error that occurs at the time metrics stop coming through? I'd like to understand what telegraf thinks happens and then we can determine a course of action.

Thanks!
