### ISSUE TITLE
gogo/protobuf is likely to be discontinued

### ISSUE THREAD

**Issue by helenosheaa** [influxdata/telegraf#9193]
According to [this thread](https://github.com/gogo/protobuf/issues/691) gogo/protobuf is looking for maintainers/ may soon be discontinued

We currently use it in:
- riemann_listener
- prometheusremotewrite parser
- prometheus serializer 
- prometheusremotewrite serializer

Refactor the above to no longer use gogo/protobuf so we don't depend on this

**Comment by powersj** [comment]
Fixed in #10019
