### ISSUE TITLE
Feature request: uWSGI input plugin.

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/telegraf#920]
uWSGI can be configured to [expose stats](http://uwsgi-docs.readthedocs.org/en/latest/StatsServer.html).

**Comment by botzill** [comment]
Can this be achieved  using `socket listener service input plugin` ?

**Comment by danielnelson** [comment]
You won't be able to do this with the stats server, but you can use the [statsd output from the metrics subsystem](https://uwsgi-docs.readthedocs.io/en/latest/Metrics.html#statsd) with the statsd input.
