### ISSUE TITLE
How to use 2 different influxdb for postgresql_extensible

### ISSUE THREAD

**Issue by sivasusheendar** [influxdata/telegraf#9212]
We have requirement - need to take 2 different query record from same database and loaded 2 different influx db - measures.

How to leverage this option using below options.

[[inputs.postgresql_extensible]]
[[inputs.postgresql_extensible.query]]

**Comment by sjwang90** [comment]
Hi @sivasusheendar - please make sure you check out the postgresql documentation. Here is more information about sample queries: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/postgresql_extensible#sample-queries-

If you are looking it output to two different InfluxDB instances you can just do it by adding 2 `outputs.influxdb_v2`  plugins and it'll dual write your postgresql data to both instances. 

We reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
