### ISSUE TITLE
input.dovecot: Add support for unix domain sockets

### ISSUE THREAD

**Issue by isodude** [influxdata/telegraf#9215]
## Feature Request

Add support for protocol 'unix' in input-plugin dovecot

### Current behavior:
only tcp is allowed

### Desired behavior:
allow unix as well

### Use case: 
cPanel uses unix domain sockets for statistics by default in their dovecot configuration.

Plus it's more safe!

I have forked and patched the code already in https://github.com/isodude/telegraf/branches/all?query=patch

**Comment by helenosheaa** [comment]
Hi @isodude, sounds reasonable. If you open a PR of your patch we'd be more than happy to review it!

**Comment by isodude** [comment]
Pushed! Not sure how much testing needs to be added for this patch.

**Comment by helenosheaa** [comment]
Thanks! I just added a comment as I think adding a test would be useful.

**Comment by isodude** [comment]
Tests have been added!
