### ISSUE TITLE
The docs are not clear in a couple of lines

### ISSUE THREAD

**Issue by mirath** [influxdata/telegraf#9226]
Line 435 of the [docs/Configuration](https://github.com/influxdata/telegraf/blob/1a86fd1a2dd30dcd60d7a704873500acaa752f0e/docs/CONFIGURATION.md ) says:
```
- **tags**: A map of tags to apply to a specific input's measurements.
```
However, that line is in the `Aggregators` section of the file, so it's not clear why is it referencing inputs

Also, in line 279 of the same file, it is unclear what happens if I setup a global tag (as described in line 143), and an input tag with the same tag key. Does the input tag overwrites the global tag? or viceversa?

**Comment by helenosheaa** [comment]
Hi @mirath, I think the line on aggregators could be might be made clearer by changing it to something like -- 

`A map of tags to apply to the measurement - behavior varies based on aggregator `

As the aggregators are not universal in their approach to tags: a lot of them don't apply tags / tags are left unchanged. I'm happy to open a PR or if you would like to suggest a change we would welcome that as well.

In regards to your other question: If you have a duplicate tag keys defined in global_tags and in an input the inputs tag value will take precedence.

**Comment by mirath** [comment]
I can create a PR later this week, or you may create one. I'm fine with either way.

**Comment by mirath** [comment]
@helenosheaa better late than never: #9461
