### ISSUE TITLE
signalfx output plugin

### ISSUE THREAD

**Issue by cep21** [influxdata/telegraf#923]
Hello,

I would like to add a SignalFx output plugin to telegraf.  Would this be merged?  There is a SignalFx go client library.  Can I add that dependency?  The most efficient wire format is protocol buffers.

**Comment by sparrc** [comment]
Sure, we could merge that. No problem with adding a dependency either

**Comment by amoghe** [comment]
https://github.com/influxdata/telegraf/pull/5204

**Comment by darinfisher** [comment]
closing due to more recent activity, see https://github.com/influxdata/telegraf/pull/6714

**Comment by sjwang90** [comment]
We'll keep this open until PR is merged 
> closing due to more recent activity, see #6714

**Comment by mcmiv413** [comment]
Sure,

We are doing work to establish SLIs and SLOs, signalfx has deeper alerting and detecting mechanisms and is cloud based so for us it would act as a single pane of glass to look at critical sli related metrics coming through telegraf as statsd data. We still want the bulk of the data to go to influx but need to leverage this additional tool to have data from statsd sit alongside data we are getting from other sources (Kubernetes, site24x7, elk, etc.).  This goes alongside the question I recently asked in the community channel about routing metrics to 2 different places but dropping the stuff related to timing. We ended up going down the route of something like this:

(very much sudo code)

GlobalTag
                Sre_part-of = default

Input over 8125

Processor override
Namepass = otherapp*
                                Sre_part-of = otherapp

Output -> influx

Output-> signalfx
                Namepass = otherapp*
                Tagpass Metric_type = counter

Ultimately we would expect the teams to add to their code to pass the sre_part-of (as well as other tags) in addition to a tag metric:sfx this would then accept the metric as important for slis and send the data to both places. Right now to accomplish this we need to use a build of telegraf from signalfx which isn’t ideal but serves our purposes. We would very much prefer this to be an officially supported plugin.

Thanks,
Michael
