### ISSUE TITLE
Use a regex to define OIDs in SNMP input

### ISSUE THREAD

**Issue by 6monlambert** [influxdata/telegraf#9240]
## Feature Request

Hello !

I am working with the SNMP input plugin, and am facing an issue on specific devices with a table that is not accessible in SNMP. I can't use the [[inputs.snmp.table]], and the field that I want to get from this table follows this syntax : 

RITTAL-CMC-III-MIB::cmcIIIVarValueInt.X.22 (with X increasing from 2 to 11).

### Proposal:

Define the OID as a simple SNMP field that matches a regular expression, and return the values as if it was pull using the SNMP table method.

### Current behavior:

I have to define the fields like this : 

```
[[inputs.snmp.field]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="pdu-watts-1"
        oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt.1.22"

[[inputs.snmp.field]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="pdu-watts-2"
        oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt.2.22"

[[inputs.snmp.field]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="pdu-watts-3"
        oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt.3.22"
```

Up to 11.

### Desired behavior:

Be able to do something like this : 

```
 [[inputs.snmp.field]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="pdu-watts"
        oid = "^RITTAL-CMC-III-MIB::cmcIIIVarValueInt.(1-11).22$"
```

### Use case: 

Having more concise configuration files.
Being able to aggregate all the values using the basicstats aggregator for example (Rather than Starlark or something else)

**Comment by Hipska** [comment]
What happens if you do an snmpwalk on `RITTAL-CMC-III-MIB::cmcIIIVarValueInt`?

It seems that `cmcIIIVarTable` is a table with 2 fields as index and you want only the ones with `cmcIIIVarIndex` = 22?
You could poll the complete table and then drop all the metrics where the index is not 22?

**Comment by 6monlambert** [comment]
Thanks for your reply

The snmpwalk returns a lot of values (1173) with the syntax specified in my issue : 

RITTAL-CMC-III-MIB::cmcIIIVarValueInt.X.Y (with 1 <= X <= 13, and 1 <= Y <= 89)


```
# snmpwalk -m+ALL -v2c -c public X.X.X.X RITTAL-CMC-III-MIB::cmcIIIVarValueInt | wc -l
1173
```
From these value, I want to get those : `RITTAL-CMC-III-MIB::cmcIIIVarValueInt.X.22 (with 2 <= X <= 13)`


Still it's better, I realised I could poll from the table and it is not really "Not Accessible".
I was trying the snmptable command but was not patient enough I guess (I get the reply in like 2-3 minutes).

Nevertheless, if I poll the complete table, I won't be able to filter the results because everything under cmcIIIVarValueInt is returned as cmcIIIVarValueInt : 

Config : 
```
  [[inputs.snmp.table]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="VarTable"
        oid = "RITTAL-CMC-III-MIB::cmcIIIVarTable"
```

Sample of the result : 

```
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III cmcIIIVarAccess=2i,cmcIIIVarConstraints="integer: min 0, max 2000000000, scale /10, step 1",cmcIIIVarDatatype=2i,cmcIIIVarEntPhysicalIndex=501009i,cmcIIIVarLastChange=98923706i,cmcIIIVarName="PSM_CAN.Energy.Active.Value",cmcIIIVarQuality=2i,cmcIIIVarScale=-10i,cmcIIIVarSteps=1i,cmcIIIVarType=2i,cmcIIIVarUnit="kWh",cmcIIIVarValueInt=268010i,cmcIIIVarValueStr="26801.0 kWh" 1620222128000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III cmcIIIVarAccess=2i,cmcIIIVarConstraints="enum: 0-12",cmcIIIVarDatatype=4i,cmcIIIVarEntPhysicalIndex=0i,cmcIIIVarLastChange=7925130i,cmcIIIVarName="PSM_CAN.Socket 07.Socket Type",cmcIIIVarQuality=2i,cmcIIIVarScale=0i,cmcIIIVarSteps=0i,cmcIIIVarType=44i,cmcIIIVarValueInt=2i,cmcIIIVarValueStr="C13" 1620222128000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III cmcIIIVarAccess=2i,cmcIIIVarConstraints="enum: 1,4,6,7,8,9",cmcIIIVarDatatype=4i,cmcIIIVarEntPhysicalIndex=0i,cmcIIIVarLastChange=0i,cmcIIIVarName="System.Supply 24V.Status",cmcIIIVarQuality=2i,cmcIIIVarScale=0i,cmcIIIVarSteps=0i,cmcIIIVarType=7i,cmcIIIVarValueInt=4i,cmcIIIVarValueStr="OK" 1620222128000000000
```

----

Another example to filter on cmcIIIVarValueInt : 

Config : 

```
[[inputs.snmp.table]]
    ## OID to get. May be a numeric or textual module-qualified OID.
    name="VarTable"
    [[inputs.snmp.table.field]]
       name="VarValueInt"
       oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt"
```

Sample of the result : 

```
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=109982760i 1620222397000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=11i 1620222397000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=0i 1620222397000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=0i 1620222397000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=1i 1620222397000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,type=pdu-cmc-III VarValueInt=11i 1620222397000000000
```

From here I can't determine which of these value is the `RITTAL-CMC-III-MIB::cmcIIIVarValueInt.X.22`

For the moment, I poll the data with 12 `[[inputs.snmp.field]]`, and then I sum them up using Starlark.
It works but it is not optimized I guess

**Comment by Hipska** [comment]
Hi, you also need to specify your indexes as tag:
```toml
  [[inputs.snmp.table]]
    name = "VarTable"

    [[inputs.snmp.table.field]]
       name = "DevIndex"
       oid = "RITTAL-CMC-III-MIB::cmcIIIDevIndex"
       is_tag = true
    [[inputs.snmp.table.field]]
       name = "VarIndex"
       oid = "RITTAL-CMC-III-MIB::cmcIIIVarIndex"
       is_tag = true

    [[inputs.snmp.table.field]]
       name = "ValueInt"
       oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt"  

  # only keep index 22 (this must be set as the last item on inputs.snmp)
  [inputs.snmp.tagpass]
    VarIndex = ["22"]
```
See [Metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) for more information.

Also have a look on the [pivot](https://github.com/influxdata/telegraf/tree/master/plugins/processors/pivot) processor if you would also want to poll `cmcIIIVarName` and let the field name be replaced by the value of it.

**Comment by 6monlambert** [comment]
Hi,

I found a solution using your advice. I used the `index_as_tag` in my table and then I'm able to poll the values with their indexes : 

```
[[inputs.snmp.table]]
        ## OID to get. May be a numeric or textual module-qualified OID.
        name="VarTable"
        #oid = "RITTAL-CMC-III-MIB::cmcIIIVarTable"
        index_as_tag=true
     [[inputs.snmp.table.field]]
       name="VarValueInt"
       oid = "RITTAL-CMC-III-MIB::cmcIIIVarValueInt"
```


The result (an extract) for the test is this : 

```
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=5.31,type=pdu-cmc-III VarValueInt=233i 1620822476000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=11.71,type=pdu-cmc-III VarValueInt=4i 1620822476000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=2.63,type=pdu-cmc-III VarValueInt=0i 1620822476000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=5.42,type=pdu-cmc-III VarValueInt=0i 1620822476000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=8.52,type=pdu-cmc-III VarValueInt=11i 1620822476000000000
```

From there, I can get the values with tags [2-13].22 using the glob syntax with a tagpass : 

```
...
  [inputs.snmp.tagpass]
     index = ["{[2-9].22,1[0-3].22}"]
```

As expected, I get the values I wanted : 

```
...
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=7.22,type=pdu-cmc-III VarValueInt=816i 1620822676000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=8.22,type=pdu-cmc-III VarValueInt=110i 1620822676000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=12.22,type=pdu-cmc-III VarValueInt=1068i 1620822676000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=11.22,type=pdu-cmc-III VarValueInt=815i 1620822676000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=13.22,type=pdu-cmc-III VarValueInt=678i 1620822676000000000
> VarTable,agent_host=X.X.X.X,host=9825ed5a69dc,index=3.22,type=pdu-cmc-III VarValueInt=944i 1620822676000000000
...
```

**Comment by Hipska** [comment]
Okay, thanks for giving feedback. I'll close this issue.

Is there any specific reason why you need to filter on index 2 to 13? Are the others not good?

**Comment by 6monlambert** [comment]
I am monitoring the electrical consumption of different devices plugged on PDUs. 
Those PDUs are composed of 12 units, indexed from 2 to 13 in the variable table, and the distributed power is given by index 22.

The 1.22 index returns another value that does not interest me : cmcIIIVarName="Input 1.Category"
All the others returns : cmcIIIVarName="PSM_CAN.Power.Active.Value"

Thanks a lot for your help !
Simon
