### ISSUE TITLE
Allow input plugin to be run on start

### ISSUE THREAD

**Issue by lucassardois** [influxdata/telegraf#9245]
## Feature Request
Allow Telegraf inputs plugins to be run on start

### Proposal:
Allow Telegraf inputs plugins to be run on start trough a new configuration attribute `onstart` which default to false, but when set to true would run the input plugin after Telegraf has started.

### Current behavior:
Input plugins are run every interval or round_interval.

### Desired behavior:
I want the input plugin to be run right after Telegraf start.

### Use case: 
I fetch an HTTP API every 3 hours thanks to the `http` plugin. This fetch then insert the resulting data in InfluxDB. I want to be able to run the first fetch right after Telegraf start so my database will directly have data and clients don't need to wait 3 hours before querying InfluxDB.

**Comment by Hipska** [comment]
Doesn't setting the [round_interval](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent) to false already do that?

Otherwise, you could shedule this collection with a cron job every 3 hours with the `--once` parameter..

**Comment by sjwang90** [comment]
@lucassardois - if you set `round_interval = false` as hipska mentioned your Telegraf will run and collect right away and continue collecting every 3 hours from there.

**Comment by Hipska** [comment]
The #10545 might also interest you.
