### ISSUE TITLE
Uninstalling telegraf through YUM remove does not remove all system unit files

### ISSUE THREAD

**Issue by M-Flexi** [influxdata/telegraf#9251]
Uninstalling Telegraf through YUM remove does not remove all system unit files

I spend quite some time troubleshooting persistent service unit settings for Telegraf and finally found out that a service unit file with a higher priority that the one in /usr/lib/systemd/system is not being removed by yum remove.

So when reinstalling Telegraf for whatever reason, the old service-unit file will be used rather than the new one: /etc/systemd/system/multi-user.target.wants/telegraf.service

### System info:

OS: RHEL 7.9 Maipo
Telegraf: 1.17

### Steps to reproduce:

1. Uninstall telegraf rpm through yum remove command
2. Sudo run `find -name telegraf.service`
3. Notice that /etc/systemd/system/multi-user.target.wants/telegraf.service is still present

### Expected behavior:

Clean uninstall included all configuration files.

### Actual behavior:

Incomplete uninstall causing issues with the new installation.

**Comment by popey** [comment]
I'm unable to reproduce this with telegraf 1.18 on a clean Centos 7.9 install. I installed disabled, enabled, removed the telegraph package as per https://docs.influxdata.com/telegraf/v1.18/introduction/installation and during the removal the symlink `/etc/systemd/system/multi-user.target.wants/telegraf.service` was indeed removed (and mentioned during the removal).

Is this still an issue for you, on 1.18?
Is your the path further up in `/etc/systemd/system/multi-user.target.wants/` a symlink? If so, perhaps could be related to systemd issue [10578](https://github.com/systemd/systemd/issues/10578)?

**Comment by powersj** [comment]
@M-Flexi were you ever able to reproduce this?
