### ISSUE TITLE
influxdb_v2 output fails to reconnect properly

### ISSUE THREAD

**Issue by Aqualie** [influxdata/telegraf#9273]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
 interval = "20s"
 round_interval = true
 metric_batch_size = 1000
 metric_buffer_limit = 99999
 collection_jitter = "0s"
 flush_jitter = "0s"
 precision = ""

 debug = false
 quiet = false
 logfile = ""
 logfile_rotation_interval = "7d"
 logfile_rotation_max_archives = 3

 hostname = "REPLACED"
 omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["https://REPLACED"]
  organization = "REPLACED"
  bucket = "telegraf"
  token = "REPLACED"
  content_encoding = "gzip"

[[inputs.cpu]]

```

### System info:

telegraf 1.18.1 & 1.18.2
### Steps to reproduce:

1. Run telegraf with an influxdb_v2 output
2. Restart influxdb 2.0 DB or wait until any connection issue occurs
3. telegraf fails to re-establish a successful connection

### Expected behavior:

Telegraf successfully re-establishes a connection to influxdb 2.0 after any maintenance event or intermittent connection issue.
### Actual behavior:

Telegraf continuously fails to re-establish a connection after any connection issue with influxdb 2.0 and below errors are repeated in the logs/console until a manual service restart is triggered which resolves the problem. The issue occurs on all Telegraf agents.

### Additional info:

```
2021-05-15T18:49:26Z E! [outputs.influxdb_v2] When writing to [https://REPLACED]: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-15T18:49:26Z E! [agent] Error writing to outputs.influxdb_v2: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-15T18:49:36Z E! [outputs.influxdb_v2] When writing to [https://REPLACED]: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-15T18:49:36Z E! [agent] Error writing to outputs.influxdb_v2: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-15T18:49:46Z E! [outputs.influxdb_v2] When writing to [https://REPLACED]: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-15T18:49:46Z E! [agent] Error writing to outputs.influxdb_v2: Post "https://REPLACED/api/v2/write?bucket=REPLACED&org=REPLACED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```

**Comment by helenosheaa** [comment]
Hi @Aqualie, 

What happens if you increase the timeout in `[[outputs.influxdb_v2]]` something like:

`timeout = "60s"`

We had [another issue](https://github.com/influxdata/telegraf/issues/9151) recently with the same error message which was resolved by doing this, so I'm interested if the same helps here.

Let us know if that doesn't help and will try and debug further.

**Comment by srebhan** [comment]
@Aqualie how is telegraf started when the error occurs?

**Comment by Aqualie** [comment]
> Hi @Aqualie,
> 
> What happens if you increase the timeout in `[[outputs.influxdb_v2]]` something like:
> 
> `timeout = "60s"`
> 
> We had [another issue](https://github.com/influxdata/telegraf/issues/9151) recently with the same error message which was resolved by doing this, so I'm interested if the same helps here.
> 
> Let us know if that doesn't help and will try and debug further.

I've made the change on one of my agents and will watch and compare for when this occurs again and update here with my findings. 



> @Aqualie how is telegraf started when the error occurs?

The service is restarted on all hosts there is no manual running of telegraf anywhere.

**Comment by srebhan** [comment]
@Aqualie do you start by systemd or anything else or do you run `telegraf --config ...` from commandline?

**Comment by Aqualie** [comment]
@srebhan On the linux/unix machines they're using systemd on the BSD machines they're using service/init.d

**Comment by srebhan** [comment]
I'm asking because I had problems with other services using systemd in the past where the network was not yet up (it was initializing slowly) when the service started due to a missing dependency to ` network-online.target`. Not sure it's related, but maybe you can give it a try... You can find some [documentation here](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/).

**Comment by Aqualie** [comment]
Yes I don't believe this is related as this issue is occurring across numerous hosts on varying platforms (Also forgot to mention Windows as well) that have been online for quite some time. The key thing here is that the influxdb is the one that would be having the problem (maintenance events for upgrades etc...) The problem seems to be centered around perhaps the socket that telegraf had open to influxdb not being closed and a new one created so it keeps trying to establish a connection over a closed channel hence why we keep seeing the context deadline timeout error meanwhile there actually is no connection being opened to influxdb.

**Comment by sjwang90** [comment]
@Aqualie Are you still seeing this issue? We haven't had any similar issue coming up for influxdb_v2 output.

**Comment by sjwang90** [comment]
Closing this issue. Feel free to re-open if there are still open questions
