### ISSUE TITLE
`inputs.exec`, `inputs.execd`: add an option to pass a custom environment to their child process

### ISSUE THREAD

**Issue by micoq** [influxdata/telegraf#9281]
### Proposal:
Add an option in `inputs.exec` and `inputs.execd` to pass custom environment variables to their child process.

### Current behavior:
Currently, if you want to pass some values to the child process, you can only use the command line parameters or the whole environment of Telegraf.

### Desired behavior:
For `inputs.execd`, there is always a single command so we could have an option like this:
```
[[inputs.execd]]

command = ["/path/to/my/process"]

[inputs.execd.env]
CUSTOM_VAR_1 = "var1"
CUSTOM_VAR_2 = "var2"
CUSTOM_VAR_2 = "var3"
```

### Use case: 
This can be useful to easily customize the child process behavior without having a separate configuration file and not display this information in the command line (e.g. for credentials)

**Comment by ssoroka** [comment]
This is a good idea. 👍🏼

**Comment by rajiv-k** [comment]
I'd like to take this up.

**Comment by ssoroka** [comment]
@rajiv-k go for it. :)
