### ISSUE TITLE
[inputs.modbus] Handle coils and discrete_inputs as booleans

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/telegraf#9284]
### Proposal:

Coils and Discrete_Inputs in modbus are boolean values by definition of the standard. It can be useful to store them in the DB as boolean values then, instead of integers, to replicate the meaning that those values have in the standard.

### Current behavior:

Right now the values read from coils and discrete_inputs are exported in line protocol as integers, and if you want to save them as booleans, you need to convert them with a dedicated processor.

### Desired behavior:

Maybe, for backward compatibility, this can be added as a configuration option, more or less like
```toml
coils = [
    { name = "...", measurement="...", data_type="BOOL/INT", address = [...]},
]
```

**Comment by powersj** [comment]
@srebhan as you have done a bunch of work on the modbus plugin do you have any thoughts on this feature request? Thanks!

**Comment by srebhan** [comment]
I will look into this as it sounds reasonable.

**Comment by srebhan** [comment]
@mirkocomparetti-synesis can you please try the binary built in PR #12825 once CI finished the tests? Let me know if this works for you!
