### ISSUE TITLE
Multiline is not working for tail plugin with regex pattern

### ISSUE THREAD

**Issue by kavityp** [influxdata/telegraf#9288]
I'm using below telegraf input tail plugin for multi line log file monitoring however using regex pattern it gives me error: "Error running agent: Error parsing /etc/telegraf/telegraf.d/log.conf, line 16: field corresponding to `multiline' is not defined in tail.Tail"

Not sure of what I'm missing here..

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################
# # Parse the new lines appended to a file
[[inputs.tail]]
  files = ["/home/use/api.txt"]
  from_beginning = true
  name_override = "GET_TOKEN_HELLO"
  [inputs.tail.multiline]
    pattern = "^%{GET_TOKEN_HELLO}"
    match_which_line = "previous"
============================
log file pattern is 
15:30:54,612 [INFO ] [ABC:70] - [LOGS] JHMRSRP6GH|GenericToken|GET_TOKEN_HELLO|PAY|20210429153054516|20210429153054612|0.093s|SUCCESSFUL

OS is RHEL 7.x

**Comment by helenosheaa** [comment]
Closing as I replied on the [community forum](https://community.influxdata.com/t/multiline-is-not-working-for-tail-plugin-with-regex-pattern/20012/2).
