### ISSUE TITLE
inputs.net.tag?

### ISSUE THREAD

**Issue by theotherguy2175** [influxdata/telegraf#9291]
Please please tell me there is a way to use the interface description for this plugin. I tried for hours doing this for a PFsense setup with no luck.

Is there any way to use the "ifconfig" description for a tag for input.net?

I was able to make an input.exec setup using bash. 

Even doing a telegraf --test --config showed the proper results:

 net,host=pfSense.casteel.internal,interface=igb0,interface_desc=Management i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=igb1,interface_desc=WAN4 i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=bge0,interface_desc=LACPTest i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=enc0,interface_desc=Servers i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=lo0,interface_desc=Admin i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=lagg0,interface_desc=IoT i=0 1621748627000000000
> net,host=pfSense.casteel.internal,interface=igb0.20,interface_desc=Guest i=0 1621748627000000000

But In Grafana the tags showed up as "undefined".

**Comment by sjwang90** [comment]
Hey @theotherguy2175 - sorry for the delay. If you --test is showing up the way you want it but in Grafana it isn't there must be something going wrong in between. If you are using InfluxDB, i'd be curious if there's something up in Grafana. 

We reserve Telegraf issues for bugs for reproducible problems.  If you want to find me in our [Community Slack](influxdata.com/slack) I can help you. Or [Community Page](https://community.influxdata.com/) and just make sure to provide full details of your set up, especially where your net data is outputting to (is it InfluxDB?) before it hits Grafana.
