### ISSUE TITLE
Missing repository builds for Ubuntu 20.10 and 21.04

### ISSUE THREAD

**Issue by popey** [influxdata/telegraf#9294]
1. Install Ubuntu 20.10 (Groovy Gorilla) or 21.04 (Hirsute Hippo) - the latest non-LTS interim releases
2. Attempt to install telegraf deb via installation instructions at https://docs.influxdata.com/telegraf/v1.18/introduction/installation/

### Expected behavior:

`apt update` should return successful.

### Actual behavior:

`apt update` fails.

```
E: The repository 'https://repos.influxdata.com/ubuntu hirsute Release' does not have a Release file.
```

### Additional info:

The following page lists supported releases of Ubuntu: https://wiki.ubuntu.com/Releases
The InfluxData repo indeed has no files for "groovy" and "hirsute" (the release codenames: https://repos.influxdata.com/ubuntu/dists/

**Comment by codyshepherd** [comment]
This issue should be able to be closed now.

**Comment by sjwang90** [comment]
Thank Cody!! @popey Can you confirm this is fixed?
