### ISSUE TITLE
aws rds enhanced monitoring metrics

### ISSUE THREAD

**Issue by kissofgod** [influxdata/telegraf#9298]
Can getting enhanced RDSOSMetrics metrics from AWS accounts be taken into consideration?

#get enhanced monitoring metrics
def aws_enhanced_to_influx(arg1, arg2, arg3):
	##try:
	timestamp_now = time.time()
	time1 = int(timestamp_now) - 20
	result=client.get_log_events(**{
	'logGroupName':'RDSOSMetrics', 
	'logStreamName': arg1,
	'startTime':time1,
	'limit':1
	}).get('events')[0].get('message').decode('utf-8')
	data = json.loads(result)
	InstanceID = data["instanceID"]
	indexstr = InstanceID.find(gathering_env) + 5
	InstanceID = InstanceID[indexstr:]
	fields_enhanced = {
				'task_total' : data["tasks"]["total"]
				,'task_zombie' : data["tasks"]["zombie"]
				,'task_blocked' : data["tasks"]["blocked"]
				,'task_running' : data["tasks"]["running"]
				,'task_stopped' : data["tasks"]["stopped"]
				,'task_sleeping' : data["tasks"]["sleeping"]
				,'diskIO_readIOsPS' : data["diskIO"][0]["readIOsPS"]
				,'diskIO_writeIOsPS' : data["diskIO"][0]["writeIOsPS"]
				,'diskIO_readLatency' : data["diskIO"][0]["readLatency"]
				,'diskIO_writeLatency' : data["diskIO"][0]["writeLatency"]
				,'diskIO_diskQueueDepth' : data["diskIO"][0]["diskQueueDepth"]
				,'diskIO_readThroughput' : data["diskIO"][0]["readThroughput"]
				,'diskIO_writeThroughput' : data["diskIO"][0]["writeThroughput"]
				,'Aurora_diskIO_tps' : data["diskIO"][1]["tps"]
				,'Aurora_diskIO_util' : data["diskIO"][1]["util"]
				,'Aurora_diskIO_await' : data["diskIO"][1]["await"]
				,'Aurora_diskIO_device' : data["diskIO"][1]["device"]
				,'Aurora_diskIO_readKb' : data["diskIO"][1]["readKb"]
				,'Aurora_diskIO_rrqmPS' : data["diskIO"][1]["rrqmPS"]
				,'Aurora_diskIO_wrqmPS' : data["diskIO"][1]["wrqmPS"]
				,'Aurora_diskIO_writeKb' : data["diskIO"][1]["writeKb"]
				,'Aurora_diskIO_avgReqSz' : data["diskIO"][1]["avgReqSz"]
				,'Aurora_diskIO_readKbPS' : data["diskIO"][1]["readKbPS"]
				,'Aurora_diskIO_readIOsPS' : data["diskIO"][1]["readIOsPS"]
				,'Aurora_diskIO_writeKbPS' : data["diskIO"][1]["writeKbPS"]
				,'Aurora_diskIO_writeIOsPS' : data["diskIO"][1]["writeIOsPS"]
				,'Aurora_diskIO_avgQueueLen' : data["diskIO"][1]["avgQueueLen"]
				,'memory_free' : data["memory"]["free"]
				,'memory_slab' : data["memory"]["slab"]
				,'memory_dirty' : data["memory"]["dirty"]
				,'memory_total' : data["memory"]["total"]
				,'memory_active' : data["memory"]["active"]
				,'memory_cached' : data["memory"]["cached"]
				,'memory_mapped' : data["memory"]["mapped"]
				,'memory_buffers' : data["memory"]["buffers"]
				,'memory_inactive' : data["memory"]["inactive"]
				,'memory_writeback' : data["memory"]["writeback"]
				,'memory_pageTables' : data["memory"]["pageTables"]
				,'memory_hugePagesFree' : data["memory"]["hugePagesFree"]
				,'memory_hugePagesRsvd' : data["memory"]["hugePagesRsvd"]
				,'memory_hugePagesSize' : data["memory"]["hugePagesSize"]
				,'memory_hugePagesSurp' : data["memory"]["hugePagesSurp"]
				,'memory_hugePagesTotal' : data["memory"]["hugePagesTotal"]
				,'cpuUtilization_irq':data["cpuUtilization"]["irq"]
				,'cpuUtilization_idle':data["cpuUtilization"]["idle"]
				,'cpuUtilization_nice':data["cpuUtilization"]["nice"]
				,'cpuUtilization_user':data["cpuUtilization"]["user"]
				,'cpuUtilization_wait':data["cpuUtilization"]["wait"]
				,'cpuUtilization_guest':data["cpuUtilization"]["guest"]
				,'cpuUtilization_steal':data["cpuUtilization"]["steal"]
				,'cpuUtilization_total':data["cpuUtilization"]["total"]
				,'cpuUtilization_system':data["cpuUtilization"]["system"]
				,'swap_in' : data["swap"]["in"]
				,'swap_out' : data["swap"]["out"]
				,'swap_free' : data["swap"]["free"]
				,'swap_total' : data["swap"]["total"]
				,'swap_cached' : data["swap"]["cached"]
				,'network_rx' : data["network"][0]["rx"]
				,'network_tx' : data["network"][0]["tx"]
				,'network_interface' : data["network"][0]["interface"]
				,'fileSys_name' : data["fileSys"][0]["name"]
				,'fileSys_used' : data["fileSys"][0]["used"]
				,'fileSys_total' : data["fileSys"][0]["total"]
				,'fileSys_maxFiles' : data["fileSys"][0]["maxFiles"]
				,'fileSys_usedFiles' : data["fileSys"][0]["usedFiles"]
				,'fileSys_mountPoint' : data["fileSys"][0]["mountPoint"]
				,'fileSys_usedPercent' : data["fileSys"][0]["usedPercent"]
				,'fileSys_usedFilePercent' : data["fileSys"][0]["usedFilePercent"]
				,'loadAverageOne' : data["loadAverageMinute"]["one"]
				,'loadAveragefive' : data["loadAverageMinute"]["five"]
				,'loadAveragefifteen' : data["loadAverageMinute"]["fifteen"]
				,'engine' : data["engine"]
				,'uptime' : data["uptime"]
				,'numVCPUs' : data["numVCPUs"]
				,'version' : data["version"]
			}
	json_enhanced = {
				"measurement": arg3,
				"tags":{
						"instanceid": InstanceID,
						"regin":"ap-northeast-2"
					},
				"fields": fields_enhanced,
				"time": arg2,
			}
	json_influx_enhanced=[]
	json_influx_enhanced.append(json_enhanced)
	clientInflux.write_points(json_influx_enhanced, database='PERF', time_precision='ms', protocol='json')
	##except:
		##log.debug('aws_enhanced gathering error')

**Comment by kissofgod** [comment]
Please refer to the url.

https://github.com/hellofresh/rds_exporter/blob/master/enhanced/metrics_data_test.go

**Comment by powersj** [comment]
@kissofgod,

Is this something you are still interested in collecting? if so were you hoping for a new plugin or a modification to an existing plugin?

Thanks
