### ISSUE TITLE
procstat : no host tag ?

### ISSUE THREAD

**Issue by glz-io** [influxdata/telegraf#930]
Hi,

when using procstat plugin, there is no tag for the host:
`> procstat,pid=29935,process_name=apache2 cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_stolen=0,cpu_time_system=8.43,cpu_time_user=12.34,involuntary_context_switches=66i,memory_rss=16302080i,memory_swap=0i,memory_vms=106422272i,num_fds=21i,num_threads=1i,read_bytes=0i,read_count=101746i,voluntary_context_switches=272420i,write_bytes=119632i,write_count=119632i 1458918786545550155
`

So we can not match the hostname if this plugin is running for apache2 on multiple servers.

Can you fix this ? Please

**Comment by sparrc** [comment]
there is no host tag in the `-test` output, it will be there when telegraf is actually running
