### ISSUE TITLE
Test failure (github.com/influxdata/telegraf/agent) on Ubuntu Impish/armhf

### ISSUE THREAD

**Issue by sergiodj** [influxdata/telegraf#9302]
The Ubuntu telegraf package (version 1.18.3) is building fine on armhf, but when we try to run the testsuite we see the following error:

```
# github.com/influxdata/telegraf/agent.test
net(.text): direct call too far: .plt 879bbe
net(.text): direct call too far: .plt 879bb3
net(.text): direct call too far: .plt 879b9a
net(.text): direct call too far: .plt 879b8b
net(.text): direct call too far: .plt 879b89
net(.text): direct call too far: .plt 879b82
net(.text): direct call too far: .plt 879b7f
net(.text): direct call too far: .plt 879b6a
runtime/cgo(.text): direct call too far: .plt 879b58
runtime/cgo(.text): direct call too far: .plt 879b55
runtime/cgo(.text): direct call too far: .plt 879b55
runtime/cgo(.text): direct call too far: .plt 879b57
runtime/cgo(.text): direct call too far: .plt 879b48
runtime/cgo(.text): direct call too far: .plt 879b44
runtime/cgo(.text): direct call too far: .plt 879b40
runtime/cgo(.text): direct call too far: .plt 879b2f
runtime/cgo(.text): direct call too far: .plt 879b1c
runtime/cgo(.text): direct call too far: .plt 879b24
runtime/cgo(.text): direct call too far: .plt 879b1b
runtime/cgo(.text): direct call too far: .plt 879b0e
runtime/cgo(.text): direct call too far: .plt 879b10
/usr/lib/go-1.16/pkg/tool/linux_arm/link: too many errors
FAIL	github.com/influxdata/telegraf/agent [build failed]
```

Here is the full build log with the failure:

https://launchpadlibrarian.net/540402842/buildlog_ubuntu-impish-armhf.telegraf_1.18.3+ds1-0ubuntu1~ppa2_BUILDING.txt.gz

### System info:

Ubuntu Impish (development version) on armhf.  The other supported architectures work fine.

Golang version `2:1.16~0ubuntu1`.

**Comment by sergiodj** [comment]
This may be a Golang issue, btw.  I haven't investigated further.

**Comment by reimda** [comment]
I'm not sure what's going on here. Telegraf official releases are cross compiled on amd64 so we don't run the tests on arm before release. It's not encouraging to see them fail but I'm I can't tell you if it's a problem with your setup or with the tests.

What hardware are you running on? In the logs I see the kernel is built for aarch64. I'm not too familiar with arm but I understand aarch64 isn't always compatible with armv7. Maybe that could be the problem?
 
Is this a new build or something that has been working for some time and just stopped working?

**Comment by sergiodj** [comment]
> I'm not sure what's going on here. Telegraf official releases are cross compiled on amd64 so we don't run the tests on arm before release. It's not encouraging to see them fail but I'm I can't tell you if it's a problem with your setup or with the tests.

Thanks for the reply.

For what it's worth, this is the telegraf package we build for Ubuntu.  I'm not entirely sure about the underlying setup of the machine, but I can say it's building on a real ARM machine (it may be an arm64 that is emulating armhf, but I'm not sure).

> What hardware are you running on? In the logs I see the kernel is built for aarch64. I'm not too familiar with arm but I understand aarch64 isn't always compatible with armv7. Maybe that could be the problem?

I don't think so.  This is the way we (Ubuntu) perform all our builds.

> Is this a new build or something that has been working for some time and just stopped working?

Yeah, this is a new failure we're seeing.  The previous version of the package (1.18.1) did not have this problem, as you can see from the logs here:

https://launchpadlibrarian.net/540443798/buildlog_ubuntu-impish-armhf.telegraf_1.18.3+ds1-0ubuntu1_BUILDING.txt.gz

**Comment by popey** [comment]
> Yeah, this is a new failure we're seeing. The previous version of the package (1.18.1) did not have this problem, as you can see from the logs here:

> https://launchpadlibrarian.net/540443798/buildlog_ubuntu-impish-armhf.telegraf_1.18.3+ds1-0ubuntu1_BUILDING.txt.gz

This log is also for 1.18.3, not 1.18.1?

Also, could it be related to: https://github.com/golang/go/issues/30949

**Comment by sergiodj** [comment]
> > Yeah, this is a new failure we're seeing. The previous version of the package (1.18.1) did not have this problem, as you can see from the logs here:
> 
> > https://launchpadlibrarian.net/540443798/buildlog_ubuntu-impish-armhf.telegraf_1.18.3+ds1-0ubuntu1_BUILDING.txt.gz
> 
> This log is also for 1.18.3, not 1.18.1?

Ops, sorry, here's the correct log:

https://launchpadlibrarian.net/535917879/buildlog_ubuntu-impish-armhf.telegraf_1.18.1+ds1-0ubuntu1_BUILDING.txt.gz

> Also, could it be related to: [golang/go#30949](https://github.com/golang/go/issues/30949)

Hm, this looks promising indeed.  I will do a few tests here and get back to you.  Thanks!

**Comment by sergiodj** [comment]
I've just packaged and uploaded the latest upstream release to impish, and I don't see the error anymore.  I'm closing this issue.
