### ISSUE TITLE
Partial plugin config file(in ./telegraf.d)  disable

### ISSUE THREAD

**Issue by denizzengin** [influxdata/telegraf#9304]
## Feature Request

We are using telegraf to collect data.  There are multiple (hundreds file in telegraf.d) input plugin config files and we need to disable temporarily some of them so we need a parameter like "disabled" in config file and can be filtered -without default behaviour change- at run time.

### Proposal:
![issue](https://user-images.githubusercontent.com/12685380/119678962-a8921200-be48-11eb-9b11-0e1f4afbc126.PNG)

### Use case: 
1.  When there are a lot of partial input config files in telegraf.d and temporarily not collect metrics from some devices

**Comment by ssoroka** [comment]
Looks like it only considers files with a `.conf` suffix. Would renaming the file to something like `.conf.ignore` work for you?

**Comment by denizzengin** [comment]
Sure, it solves.I will try above solution.  
Thanks a a lot for solution.
