### ISSUE TITLE
Not able to parse xml string input

### ISSUE THREAD

**Issue by anaghabide** [influxdata/telegraf#9308]
I want to parse XML string in tcp input.  But telegraf is considering each line as a separate string. Can you help me how can I parse same.
sample XML:-
```xml
<MSG>
    <header> 
        <version>1</version>
    </header>
    <body>
           <msg1>test</msg1>
           <id>1</id>  
     </body>
</MSG>
```

**Comment by srebhan** [comment]
@anaghabide I think something went wrong with your example XML. Can you please post your XML so we can reproduce the issue.

**Comment by ssoroka** [comment]
I fixed the xml in your post.

You may be able to do this using the socket listener, but I think you might have problems with how individual documents are separated... not sure.

something like... 
```toml
[[inputs.socket_listener]]
  service_address = "tcp4://:8094"
  data_format = "xml"
  [[inputs.file.xml]]
    id = "number(MSG/body/id)"
```
See the [xml docs](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xml) for more info.

**Comment by anaghabide** [comment]
@ssoroka  this configuration is giving me below error
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Starting Telegraf 1.18.3
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Using config file: /etc/telegraf/telegraf.conf
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Loaded inputs: file socket_listener
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Loaded aggregators: 
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Loaded processors: 
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Loaded outputs: file
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! Tags enabled: host=mcr_gateway
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"mcr_gateway", Flush Interval:10s
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z D! [agent] Initializing plugins
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z D! [agent] Connecting outputs
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z D! [agent] Attempting connection to [outputs.file]
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z D! [agent] Successfully connected to outputs.file
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z D! [agent] Starting service inputs
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:23Z I! [inputs.socket_listener] Listening on tcp4://0.0.0.0:8094
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:33Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:41Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected EOF
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:41Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected EOF
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:41Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected end element </header>
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:41Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected EOF
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:41Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected end element </body>
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:43Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:51Z E! [inputs.socket_listener] Unable to parse incoming line: XML syntax error on line 1: unexpected end element </MSG>
gcp_telegraf.1.x7xjucp1nt65@debian    | 2021-05-28T01:43:53Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics

**Comment by srebhan** [comment]
@anaghabide I think the problem is that `socket_listener` is parsing **each received packet**. If your sender now sends each line separately (e.g. by calling `send` linewise) you will end up in the behavior above. So the easiest solution is to make your sender to send the XML at once.

Alternatively, we would need to extend the `socket_listener` such that you can specify a _"separation token"_ and make the sender also sending it.

**Comment by anaghabide** [comment]
Actually, my sender is sending the whole XML at once.

**Comment by srebhan** [comment]
Please try to use
```toml
[[inputs.socket_listener]]
  service_address = "tcp4://:8094"
  data_format = "value"
  data_type = "string"
```
to see what the socket_listener plugin is actually sending to the parser.

**Comment by anaghabide** [comment]
Tried with the above configuration with minified XML.
It received full XML in the field but every character gets appended with "\u003c" 
I have tried with minified XML and data_format = "XML" also.
It worked but I have to specify each field in configuration to get its data. 
Is there any way to get all fields without specifying each field in configuration?

**Comment by srebhan** [comment]
> It received full XML in the field but every character gets appended with "\u003c"

Can you please paste the output with the `value` parser so I can see how that looks like.

> I have tried with minified XML and data_format = "XML" also.
It worked but I have to specify each field in configuration to get its data.
Is there any way to get all fields without specifying each field in configuration?

To tell for sure, I would need an example of your exact XML structure. You can use `metric_selection` to specify nodes that for a new metric each and `field_selection` to specify the field pattern (see e.g. [this example](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xml#batch-field-processing-with-multi-node-selection)). You might also want to take a look at [the testcases](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xml/testcases). Keep in mind that the test-case configurations need to be adapted to the actual telegraf config.
