### ISSUE TITLE
Podman input plugin

### ISSUE THREAD

**Issue by rogercoll** [influxdata/telegraf#9314]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add a new input plugin for Podman (https://podman.io/)

### Current behavior:

Not implemented

### Desired behavior:

Very similar to the Docker plugin one. You can easily launch a Podman unix socket and with Go communicate with it.

### Use case: 

Same as Docker. Nowadays, Podman is becoming more popular as a daemonless container engine, thus it could be very useful in some light environments.

Do you plan to unify same type of input plugins in directories? For example, for container engines: instead of `plugins/input/docker` && `plugins/input/podman`, have `plugins/input/containers/docker` &&  `plugins/input/containers/podman`. Maybe this has been covered before but input level one directories can increase a lot.

**Comment by rogercoll** [comment]
If you agree that could be useful I can start working on it.

**Comment by akrantz01** [comment]
Since Podman is intended to be a drop-in replacement for Docker, you should be able to change the `endpoint` in the input configuration to Podman's unix socket. The only immediate restriction I see is that `gather_services` cannot be enabled since Podman does not support Docker Swarm.

**Comment by rogercoll** [comment]
@akrantz01 @popey Could you take a look at https://github.com/influxdata/telegraf/pull/9634 ?

Initial PR with some basic monitoring for Podman.

Best regards

**Comment by samarjoe** [comment]
Was reviewing this issue, should this be marked as closed?

**Comment by leonise** [comment]
Hi, the PR seems closed but not published, may I know if there's any solution on PODMAN monitoring pls?
thanks

**Comment by DStrand1** [comment]
Is there anything that a Podman plugin would be required for that the Docker plugin could not already do?
