### ISSUE TITLE
Unable to get SNMP , telegraf & influxd

### ISSUE THREAD

**Issue by teckiller7** [influxdata/telegraf#9318]
hello im trying to monitor my meraki MR wireless devices using grafana , influxdb a, telegraf , i did set up all good ,

im able to snmpwalk snmp. meraki .com is OK !

but when runing :

systemctl status telegraf

i get :

[admin@centos-local ~]$ systemctl status telegraf

May 28 23:41:40 centos-local telegraf[108467]: 2021-05-28T22:41:40Z E! [inputs.snmp] Error in plugin: agent sn mp.meraki.com: performing get on field hostname: request timeout (after 3 retries)
May 28 23:41:50 centos-local telegraf[108467]: 2021-05-28T22:41:50Z W! [inputs.snmp] Collection took longer than expected; not complete after interval of 10s

or
gathering table snmp: performing bulk walk for field ifName: reque>

PS: when using acess point local ip’s its works fine
i dont know what is the issue

my telegraph .conf
[[inputs.snmp]]
agents = [ “snmp.mraki.com” ]
version = 2
community = “*******”
name = “snmp”

[[inputs.snmp.field]]
name = “hostname”
oid = “RFC1213-MIB::sysName.0”
is_tag = true

[[inputs.snmp.table]]
name = “snmp”
inherit_tags = [ “hostname” ]
oid = “IF-MIB::ifTable”

[[inputs.snmp.table.field]]
  name = "ifName"
  oid = "IF-MIB::ifName"
  is_tag = true
thanks

**Comment by popey** [comment]
Conversation over on the community page. https://community.influxdata.com/t/unable-to-get-snmp-telegraf-influxdb/20130
