### ISSUE TITLE
procstat: include children / sum totals / pss

### ISSUE THREAD

**Issue by zarnovican** [influxdata/telegraf#932]
It would be nice if `procstat` had some additional features..
- child processes - Sometimes it is not possible to match easily a service together with all descendants. It would be nice if you could specify something like:
  
  ```
  pid_file = "/var/run/nginx.pid"
  include_children = true
  ```
  
  While specifying only the top process, it would include all direct and indirect descendants in the measurements.
- sum totals - Plugin could optionally do the aggregation at the source. Similar to what 'cpu' plugin does.
  
  ```
  perprocess = false
  totalprocess = true
  ```
  
  This makes a lot of sense for services that fork off short-lived children. Currently, telegraf will create a new measurement in Influx for every new child (it contains child's pid). Totals might be hard to implement, as it is not obvious which metrics are "aggregate"able and how.
- measure PSS too - Plugin could include also stats from Linux `smaps`
  
  ```
  include_smaps = true
  ```
  
  Why? For a group of processes it makes more sense to sum PSS values of each process rather than RSS. PSS is available on Linux from `/proc/<pid>/smaps` (requires root access). Sum of PSS is much closer to answering the question "How much memory is this service using..?"

These three features could be useful each independently. Let me know if you would like to split them into three tickets.

Because those features were missing in current `procstat` plugin, I had to implement them on my own. Here is a crappy bash version of CPU/mem usage.
https://gist.github.com/zarnovican/9840d171d9a9c6de1766

```
# /usr/lib/telegraf/scripts/sumproc.sh -u postgres
sumproc utime=6.9,stime=40.58,nprocess=8i,pss=24326144i
```

**Comment by powersj** [comment]
next steps: need to see which of these still need to be done

**Comment by zarnovican** [comment]
I'm closing the ticket. I have switched to monitoring systemd units istead of individual processes.

If any of the subscribers think, that something should be implemented after all, feel free to reopen the ticket.
