### ISSUE TITLE
Release sha changed

### ISSUE THREAD

**Issue by andig** [influxdata/telegraf#9334]
Noticed during Homebrew/homebrew-core#78666 that the release sha has changed.

```
❯ brew install --build-from-source telegraf
==> Downloading https://github.com/influxdata/telegraf/archive/v1.18.3.tar.gz
Already downloaded: /Users/andig/Library/Caches/Homebrew/downloads/cfd3ec653608392ca183cf0ec1481558fd23e0b4fd699d2eae3ed91fbc8280b9--telegraf-1.18.3.tar.gz
Error: SHA256 mismatch
Expected: 877496fb440d9d18713cafc01df8e24c0b1cfd5945f5a5c6cf5fb0df62b0f2c3
  Actual: 18131af75eea19d0fa7ac3c0c97d9cf941a4e77acf233be6324b208833d02cea
    File: /Users/andig/Library/Caches/Homebrew/downloads/cfd3ec653608392ca183cf0ec1481558fd23e0b4fd699d2eae3ed91fbc8280b9--telegraf-1.18.3.tar.gz
```

Has this been re-released?

**Comment by reimda** [comment]
Hi, thanks for the report and for repackaging telegraf in homebrew!

I'm not sure I completely understand homebrew's process, so correct me if I'm wrong: I think you have an automated download that grabs a telegraf tarball soon after we tag a release. Later when you build telegraf for homebrew, you download the tarball again and check that the hashes of the two tarballs match.

I'm pretty sure I did move the tag for 1.18.3 so this hash mismatch shouldn't be a problem.

I'd like to find a way to be able to move the tag without triggering a sha change for homebrew. Under what conditions does the automated process download releases? Could we avoid the download by flagging the release as it as pre-release in github? We have used the pre-release flag for a while for rc releases, but we could also flag final releases as pre-release until our build succeeds and we're sure the tag isn't going to move. Would that help?

**Comment by SMillerDev** [comment]
> I think you have an automated download that grabs a telegraf tarball soon after we tag a release. Later when you build telegraf for homebrew, you download the tarball again and check that the hashes of the two tarballs match

Basically every time we build any software we check the download hash. And in this case it changed.

**Comment by andig** [comment]
This is what @carlocab wrote in https://github.com/linkerd/linkerd2/issues/6233#issuecomment-856310162: 

> Just FYI, it'd be nice if you had just cut a new release tag instead of re-tagging the existing one. The Git docs have some pretty strong words about re-tagging.

**Comment by SMillerDev** [comment]
> I'd like to find a way to be able to move the tag without triggering a sha change for homebrew. Under what conditions does the automated process download releases?

When people notice a release in the repo they send in a pull request to update the software. If this is not the place to look for releases we have ways to stop it. We just have to know.

**Comment by carlocab** [comment]
>We have used the pre-release flag for a while for rc releases, but we could also flag final releases as pre-release until our build succeeds and we're sure the tag isn't going to move. Would that help?

I think this could help, yes.

**Comment by reimda** [comment]
I understand that we should avoid retagging. Unfortunately the current telegraf process doesn't start the release build until we tag the git repo. It should be the other way around- we should tag after we have a successful build. I'll look into changing the release process but that may take some time.

In the mean time we'll flag all releases on github as pre-release and then only remove the flag when we're sure the tag won't change.

**Comment by carlocab** [comment]
Thanks, @reimda. That's much appreciated.
