### ISSUE TITLE
toml: can not parse empty array with comments

### ISSUE THREAD

**Issue by coanor** [influxdata/telegraf#9337]
Following toml works ok:

```
abc = [
"a", "b", "c",
# some comments...
]
```

but following parse failed: `line 2: invalid TOML syntax`

```
abc = [
# "a", "b", "c",
# some comments...
]
```

**Comment by sspaink** [comment]
This is a duplicate of: #3642
There seems to be a test already implemented for it that is being skipped at the moment: 
- [test code](https://github.com/influxdata/telegraf/blob/master/config/config_test.go#L256)
- [test config](https://github.com/influxdata/telegraf/blob/master/config/testdata/slice_comment.toml)

It is quite an old issue, it will need to be revisited to see what the best approach is to fix it. Closing this issue to keep the discussion to #3642. Hopefully this isn't a blocking bug for you?
