### ISSUE TITLE
Add routing_key to kafka_consumer input plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9340]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add `routing_key` config option to kafka_consumer input plugin

### Current behavior:
No option to config in input plugin. `routing_key` configuration exists in outputs.kafka

### Desired behavior:
Configure `routing_key`

### Use case: 
Wish to consume messages from a specific partition

**Comment by akrantz01** [comment]
I don't think that this should be implemented into Telegraf. From what I've read, it seems as though all data within a topic should be the same, so reading from a random set of partitions should be no different than reading from a specific partition.

Using partitions to segment events within a topic based on their data appears to be an anti-pattern, and as such, I don't think we should support it.
