### ISSUE TITLE
expose multiple samples for a time series in prometheus_client output plugin

### ISSUE THREAD

**Issue by jbbernar** [influxdata/telegraf#9354]
## Feature Request

The prometheus_client output plugin exposes only a single sample for any time series. I'd like it to at least optionally expose all of them.

### Proposal:

Expose all the samples.

### Current behavior:

telegraf --test gives:

```
> test,node=46,host=d50 write_latency_ms=0 1623440407000000000
> test,node=46,host=d50 write_latency_ms=0 1623440397000000000
> test,node=46,host=d50 write_latency_ms=3.51 1623440387000000000
> test,node=46,host=d50 write_latency_ms=0 1623440377000000000
> test,node=46,host=d50 write_latency_ms=0 1623440367000000000
> test,node=46,host=d50 write_latency_ms=3.656 1623440357000000000
> test,node=46,host=d50 write_latency_ms=0 1623440347000000000
> test,node=46,host=d50 write_latency_ms=0 1623440337000000000
> test,node=46,host=d50 write_latency_ms=0 1623440327000000000

```
curl -sk localhost:9273 gives:

`test_write_latency_ms{node="46"} 0 1623440407000000000
`
### Desired behavior:

```
test_write_latency_ms{node="46"} 0 1623440407000000000
test_write_latency_ms{node="46"} 0 1623440397000000000
test_write_latency_ms{node="46"} 0 1623440387000000000
test_write_latency_ms{node="46"} 0 1623440377000000000
test_write_latency_ms{node="46"} 0 1623440367000000000
test_write_latency_ms{node="46"} 0 1623440357000000000
test_write_latency_ms{node="46"} 0 1623440347000000000
test_write_latency_ms{node="46"} 0 1623440337000000000
test_write_latency_ms{node="46"} 0 1623440327000000000
```

### Use case: 

The current behavior complicates backfilling, and makes it necessary to run the input collector and prometheus scrape at tight intervals.

**Comment by powersj** [comment]
Hi,

Using the `--test` option will not run any of the configured outputs. It will instead print the metrics in line protocol format to stdout as you have discovered. When run without the `--test` option, the Prometheus client should be writing the metrics in a familiar Prometheus output style.

If there is something we missed with this report, feel free to let us know. 

Thanks!
