### ISSUE TITLE
Azure Monitor output plugin not delivering all metrics

### ISSUE THREAD

**Issue by Purneau** [influxdata/telegraf#9361]
### Relevant telegraf.conf:

```toml
[[outputs.azure_monitor]]
  timeout = "60s"
```

### System info:
- RHEL 7
- Telegraf 1.15.4 (git: release-1.15 41628ee9)

### Docker
N/A

### Steps to reproduce:

On multiple VMs simultaneously:
1. Add a new input section to the config
2. Restart Telegraf service

### Expected behavior:

New metrics are consistently delivered to Azure monitor on all VMs.

### Actual behavior:

New metrics are fully visible on x VMs, partly visible on y VMs and not visible on z VMs.
Over time (days) the affected VMs gradually start sending more and more metrics. 

### Additional info:

- No errors or unexpected logging when enabling debug mode.
- Configuration is applied on multiple system simultaneously. This rules out any configuration differences or drift between the different machines.

**Comment by reimda** [comment]
I think there have been updates to this plugin since 1.15.4. Could you retry with the latest telegraf build?

**Comment by Purneau** [comment]
We are suffering from: https://github.com/influxdata/telegraf/issues/9266
I can't test this at scale using a nightly build, so I will get back on this once we have rolled out a stable build on all these systems.

**Comment by Purneau** [comment]
Cannot reproduce using 1.19.0-1. Closing issue, thanks for the hint.
