### ISSUE TITLE
[Feature Request] Multiple Conditions on Filters

### ISSUE THREAD

**Issue by collinlambert** [influxdata/telegraf#937]
Name_, Field_, Tag\* filters have a "if a single one passes/fails then emit/don't emit". It would be nice to have "if these X pass" or "if these X fail" then "emit" or "don't emit".

An example would be:

```
[outputs.kafka.tagpass.all]
    x = ["y"]
    z = ["a"]
```

Then the metric would only be emitted if both x = "y" and z = "a".

I would be a fan of anything that solves this problem (multiple conditions for passing metrics), it doesn't have to be the example I proposed.

**Comment by kostasb** [comment]
To clarify, my understanding is that you are requesting a variation of tagpass & tagdrop, fieldpass & fielddrop that will work with AND instead of OR logic.

Currently, as stated in the documentation these work with "OR" logic only: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tagpass-and-tagdrop

**Comment by danielnelson** [comment]
It would be useful if we had some concrete use cases for this feature.

**Comment by danielnelson** [comment]
This suggested format above is implemented on #2591 but I think it is too complex to use in practice and still might not give as much control as one might want.  I wonder if we should come up with a new mini language for this, something like `country::tag == usa and value::field == 42`, but it is probably something we need to spend a bit of time designing.

**Comment by tkanos** [comment]
What is the next step for this topic @danielnelson ?

**Comment by danielnelson** [comment]
I think we may want to investigate using [flux](https://github.com/influxdata/flux) here.  We need to experiment with it a bit to see if it is a good fit.

**Comment by TheGreatYamcha** [comment]
Does flux work with telegraf?
This is a really basic feature. I don't understand why it's not supported yet.

**Comment by ssoroka** [comment]
Hey @TheGreatYamcha, I'm glad to see you are also interested in seeing greater integration of Flux in Telegraf; we are as well! Though I don't agree that addressing the concerns around adding support for an additional language, especially one that is frequently changing, under development, and spanning two languages (Go & Rust) could be considered "basic". That said, we are carefully considering this, and in what capacity it makes the most sense.

If you're interested in discussing Flux integration, I'd suggest opening a [new issue](https://github.com/influxdata/telegraf/issues/new/choose), detailing what kind of use case you had in mind for Flux. It'd be very valuable to hear from someone who would be trying to solve a concrete problem with it. Include whether you looking for Flux to help with configuration, like in this ticket, or more with scripting of data flow, like plugins.

Thoughtful discussion and contributions are always welcome. Thanks!

**Comment by TheGreatYamcha** [comment]
@ssoroka I think you misunderstood me. I was referring to being able to do AND logic on the conditions as a necessity. 
Whether flux supports that or will be integrated with Telegraf isn't that important for me. Thanks.

**Comment by ssoroka** [comment]
@TheGreatYamcha thanks for clarifying! I think we might have a solution for this soon. We are prototyping some solutions and will update this ticket with the results.

**Comment by lucasbritos** [comment]
Great to hear you are working on this!
Meanwhile, anyone have a workarround for this ?
I wrote this stackoverflow, maybe you can use it as another use case
https://stackoverflow.com/questions/61601440/add-static-tag-given-other-tags-present-on-telegraf

**Comment by ssoroka** [comment]
There have been some updates on this! As of writing, Telegraf 1.15-rc2 is out and includes some really flexible processors (Turing-complete!). At this point, there is no limit to how you can filter and modify metrics.

Take a look at [processors.starlark](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark) and [processors.execd](https://github.com/influxdata/telegraf/tree/master/plugins/processors/execd). (there's also execd versions of input and output plugins)

You can start using these today with the nightly and 1.15-rc2 build and will be a permanent part of 1.15 and Telegraf going forward.

Going to close this issue as these new processors address the original ask.

**Comment by Tower450** [comment]
i would need this feature too, i don't think processor are fixing this need @ssoroka  since you are talking about manipulating the metrics but here we want to filter them and only keep those who fits x = "y" and z = "a"
