### ISSUE TITLE
When running as non-root user, intel_rdt plugin has no output

### ISSUE THREAD

**Issue by xavpaice** [influxdata/telegraf#9380]
### Relevant telegraf.conf:

```toml
[[inputs.intel_rdt]]
cores = ["0-5,8-13"]
```

### System info:

Telegraf: 1.18.3+git-6ef3e51f~202105250953~ubuntu18.04.1 from  http://ppa.launchpad.net/telegraf-devs/ppa/ubuntu
Ubuntu Bionic, with kernel 5.4 (HWE)
intel-cmt-cat 4.1 from source (Bionic's package is older)

### Steps to reproduce:

1. configure the intel_rdt plugin per documentation
2. Ubuntu packages run telegraf as user 'telegraf', not as root

### Expected behavior:

Expected metrics, such as:

```
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="IPC"} 0.88
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="LLC"} 9984
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="LLC_Misses"} 305356
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="MBL"} 18.9
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="MBR"} 0.3
  rdt_metric{cores="0,1,2,3,4,5,8,9,10,11,12,13",host="controller:ubuntu-1",juju_application="ubuntu",juju_model="controller",juju_unit="ubuntu-1",name="MBT"} 19.
```

### Actual behavior:

pqos would need to have priv escalation (sudo?) as part of the plugin in order for telegraf to run as anything other than the root user, if this plugin is to work.  Currently we see no data in metrics from the intel_rdt plugin, logs show that pqos fails:

```
2021-06-16T03:42:13Z E! [inputs.intel_rdt] Error: pqos: exit status 1
2021-06-16T03:42:13Z E! [inputs.intel_rdt] failed to shut down pqos: os: process already finished
```

### Additional info:

Running telegraf in the foreground as root works perfectly - this issue is purely that due to security requirements telegraf is not to run as root.

**Comment by xavpaice** [comment]
https://github.com/xavpaice/telegraf/tree/issues/9380 has a potential fix, need to get the CLA signed before making a PR.

**Comment by reimda** [comment]
Hi @xavpaice, thanks for the issue. Using sudo is a good option here. Let us know when you've signed the CLA and can submit a PR.

Your readme.md changes say sudo is mandatory if telegraf isn't running as root, but that's not quite true. One other option for running pqos as root is to make the pqos executable setuid root. That's less secure than sudo but doesn't require any changes to telegraf.
