### ISSUE TITLE
Multiple docker inputs possible?

### ISSUE THREAD

**Issue by MichiFr** [influxdata/telegraf#9392]
Very basic question regarding telegraf.conf and docker monitoring:
Can I have multiple endpoints in section [[inputs.docker]] or multiple sections?

Background: I'm running telegraf on one machine and can monitor this local host. OTH, I'm running a second machine with a second docker instance, not running any telegraf daemon and would like to remotely monitor this instance, too.

Any hints available? Thanks!

**Comment by reimda** [comment]
You can have multiple [[inputs.docker]] sections in your telegraf.conf, for example one for your local docker and another for docker on your second machine.

By default, docker only listens on a unix socket. You may have to change docker on your second machine so it listens on tcp before you can connect to it. (see https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option) Be careful with this as it can be less secure.

Please also use the community slack or community messageboard for questions like this in the future. Github issues are meant for telegraf bugs and feature requests.
