### ISSUE TITLE
smart scan with configurable device types

### ISSUE THREAD

**Issue by DEvil0000** [influxdata/telegraf#9397]
## Feature Request
Adding a config option for device types to scan for when using smart input plugin.

### Current behavior:
Currently the smart input uses `smartctl --scan` and `smartctl --scan --d nvme` to search for devices to monitor.

### Desired behavior:
I would like to see a config option containing a list of device types to scan for or command list for scans.

### Use case:
In case of some HP raid controllers this will however not provide a complete device list.
For some controllers on G10 this works as expected but for others on G9 it does only list devices with:
`smartctl --scan -d scsi`

**Comment by MyaLongmire** [comment]
Can you please provide an example of what devices are not shown up? To my knowledge `smartctl --scan` should return all devices.
