### ISSUE TITLE
Plugin SMCIPMITool

### ISSUE THREAD

**Issue by Novgor** [influxdata/telegraf#9418]
Hello.
Will there be support for the SMCIpmiTool plugin in the latest versions? Plugin documentation is missing. 
https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/smc_ipmi/README.md
best regards.

**Comment by reimda** [comment]
The contributor of the smc ipmi tool plugin made the plugin external. It is not part of telegraf but can be run by telegraf using exec. See the instructions at https://github.com/jhpope/smc_ipmi.
