### ISSUE TITLE
Telegraf on Kubernetes : Error: Service "telegraf" is invalid: spec.ports: Required value

### ISSUE THREAD

**Issue by chandhukeenz** [influxdata/telegraf#9420]
**what do I want to do?**
I'm trying to deploy telegraf in my Kubernetes cluster so that I can use Telegraf's **Prometheus** input plugin to read the data (metrics) from a particular URL and write the metrics in a file using telegraf's output **file** plugin.
**what did I do?**
I used the telegraf [helm chart](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf) to deploy telegraf on kubernetes. I changed the following config changes.
**The original telegraf yaml file:**
![image](https://user-images.githubusercontent.com/55447161/123103336-85607f80-d453-11eb-8649-40ca26dc86ce.png)
**The changes I made to it:**
![image](https://user-images.githubusercontent.com/55447161/123103104-521df080-d453-11eb-9f7f-5476d25fc935.png)
And when I applied the helm chart along with the changes I got 
**Error: Service "telegraf" is invalid: spec.ports: Required value** and my deployment failed.
![image](https://user-images.githubusercontent.com/55447161/123103675-dec8ae80-d453-11eb-86d0-ad89da09d1c8.png)
Please do help me if I'm making any mistakes on the changed YAML configuration since I didn't find any resource for yaml format of telegraf's input and output plugin.
Additional link for reference: 
[telegraf .conf file](https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf)

**Comment by akrantz01** [comment]
Does your telegraf need to listen on any ports? If not, setting `service.enabled` to false in your values.yaml should fix it.

**Comment by reimda** [comment]
We can't provide helm support here. Please use slack or the community message boards.
