### ISSUE TITLE
2021-06-23T17:14:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster 2021-06-23T17:14:10Z E! InfluxDB Output Error: Post http://127.0.0.1:8086/write?consistency=any&db=telegraf: dial tcp 127.0.0.1:8086: getsockopt: connection refused

### ISSUE THREAD

**Issue by chandhukeenz** [influxdata/telegraf#9424]
**what I want to do?**
I want to get the data from prometheus /metrics using inputs.prometheus plugin and write it in a file using outputs.file plugin by telegraf.
**what I did?**
![image](https://user-images.githubusercontent.com/55447161/123144986-ee5aee00-d479-11eb-9869-3054e16007f8.png)
![image](https://user-images.githubusercontent.com/55447161/123145125-1fd3b980-d47a-11eb-9ab1-f03263b4fead.png)
![image](https://user-images.githubusercontent.com/55447161/123145215-3c6ff180-d47a-11eb-9c8b-587af36a96ba.png)
It deployed successfully, but I'm getting this error in telegraf logs message.
**2021-06-23T17:14:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2021-06-23T17:14:10Z E! InfluxDB Output Error: Post http://127.0.0.1:8086/write?consistency=any&db=telegraf: dial tcp 127.0.0.1:8086: getsockopt: connection refused**

**Comment by reimda** [comment]
It looks like the telegraf.conf in your yaml file isn't being used when telegraf runs. The log output mentions influxdb output which is not in your yaml configuration. I would guess your yaml config isn't placing the telegraf.conf in the expected location and telegraf is using a default telegraf.conf in the image.

This is not an issue with telegraf, but with your kubernetes configuration. Please don't open issues for support requests like this. Instead, try slack or the community messageboards in the future.
