### ISSUE TITLE
x509 do not gather information about cross-certs and root-certs

### ISSUE THREAD

**Issue by VorobevPavel-dev** [influxdata/telegraf#9427]
## Feature Request

Allow user to chose gather info about root certs or not via some kind of config field

### Proposal:

Add field to config allowing user not to gather info not from target cert.

### Current behavior:
Info gathered from target cert (green line) and cross, root certs (blue and orange lines)
![Скриншот от 2021-06-24 14-38-37](https://user-images.githubusercontent.com/66829073/123257052-56511900-d4fa-11eb-9e12-f9104bcb5740.png)

### Desired behavior:

No data from unrelated certs

### Use case: 

In most cases it is not neccessary to know about root certs. Filtering via Telegraf's metric filtering may be inconvenient when there are lots of certificates

**Comment by VorobevPavel-dev** [comment]
@jaroug  @srebhan @ssoroka please take a look

**Comment by srebhan** [comment]
@VorobevPavel-dev makes sense to me. Pull-requests welcome. ;-)

**Comment by jjh74** [comment]
@VorobevPavel-dev Can you check if PR https://github.com/influxdata/telegraf/pull/9822 excludes root/intermediate certs like you requested ?

**Comment by VorobevPavel-dev** [comment]
@jjh74 seems like it will help. Thanks
