### ISSUE TITLE
[inputs.modbus] long value error -- exception '3' (illegal data value), function '131' 

### ISSUE THREAD

**Issue by temp5mr** [influxdata/telegraf#9430]
Device's (OWEN ME110) manual says: 
`Integer value of measured voltage  0x0019, 0x001A  Signed long Read only`
A asked holding registers (telegraf 1.19.0,  RTU 9600/8N1):
`byte_order = "ABCD",  data_type = "INT32", scale=1.0,  address = [25,26]`
and
`byte_order = "ABCD",  data_type = "FIXED", scale=1.0,  address = [25,26]`
both give the message:
`Error in plugin: modbus: exception '3' (illegal data value), function '131'  `
(all other bytes orders - the same).

When I asked
`byte_order = "AB",  data_type = "INT16", scale=1.0,  address = [25]`
and
`byte_order = "AB",  data_type = "INT16", scale=1.0,  address = [26]`
both return
`name=24,slave_id=16,type=holding_register U1=10i`

**Comment by srebhan** [comment]
Hey @temp5mr, does the problem still persist with current master?

**Comment by temp5mr** [comment]
Hi. I could not solve the problem, so the device was changed and we use other scheme for logging.

**Comment by srebhan** [comment]
So it seems we don't have any way of testing this anymore? Are you OK with closing this issue?

**Comment by temp5mr** [comment]
Yes, close please. (But I hope try check this device with the new version later.)

**Comment by srebhan** [comment]
Perfect. Feel free to reopen this issue in case the problem persists.
