### ISSUE TITLE
Add integration test for dovecot

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#9435]
#9415 happened because of a linter fix in code that wasn't covered with tests. A docker integration test would make sense here and would have caught the regression.

We also need to check if there's a better api to use to gather dovecot stats. The current one we use "old_statistics" requires us to ignore a timeout.

https://doc.dovecot.org/configuration_manual/stats/old_statistics/#old-statistics

**Comment by pablocarreraest** [comment]
Hey @reimda  how config stats on dovecot? I'm trying but don't know where to put the metrics? con dovecot.conf? if you can guide I really appreciate :)
