### ISSUE TITLE
telegraf doesn't report in which file there is an error

### ISSUE THREAD

**Issue by rubycut** [influxdata/telegraf#944]
In case of having multiple config files, filename is not reported, only line number:

```
telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -test
2016/03/31 04:20:40 toml: line 5: parse error
```

**Comment by sparrc** [comment]
thanks for the report, I was working on some config file things anyways so I'll get a fix for this in with #948
