### ISSUE TITLE
Statsd percentile setting fails on integer values

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#9441]
Before 1.19.0, the statsd percentile setting would accept integer or floating point values. After 1.19.0, it doesn't accept integer values.

This config snippet was valid before 1.19.0:
```toml
[[inputs.statsd]]
  percentiles = [90]
```

On 1.19.0 it will trigger an error like this:
`Error loading config file /etc/telegraf/telegraf.conf: error parsing statsd, line 186: (statsd.Statsd.Percentiles) cannot unmarshal TOML integer into float64`

Since users of the statsd with percentiles before 1.19.0 may have entered percentiles as integers, it's likely this will cause a failure when they upgrade to 1.19.0. (see #9407)

The setting parsing changed in #8969 as part of a cleanup refactor. 

Expected fix: make the setting work like before and accept integer values as well as floating point values.

As a workaround, users can change their telegraf.conf to have floating point values for this setting. The failing config above works with ".0" added to the setting:
```toml
[[inputs.statsd]]
  percentiles = [90.0]
```

**Comment by liorfranko** [comment]
+1
