### ISSUE TITLE
Rename `kubernetes_node` measurements in inputs.kube_inventory or inputs.kubernetes

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9451]
### Proposal:
The same measurement name causes conflicts for those users that have both `inputs.kube_inventory` and `inputs.kubernetes` plugins. 

### Current behavior:
`kubernetes_node` metric is emitted by both `inputs.kube_inventory` and `inputs.kubernetes` but each emit different field and tag keys. This causes problems and confusion when both input plugins are enabled. 

Example query:
```sql
select capacity_cpu_cores, cpu_usage_core_nanoseconds / 1000000000 from kubernetes_node where time > now() - 12h group by kubernetes_cluster;
```

Resulting in output such as:
```
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 1.200665496
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32 1.275632175
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32
2021-03-15T20:41:30Z 32
```

### Desired behavior:
One of the metrics should be renamed.

### Use case: 
When the customer tries to query a kubernetes_node measurement, they get no or incorrect results results, and it seems there is a conflict preventing results from showing up. A Telegraf user in Kubernetes is likely to enable both plugins so this could be a common problem.

**Comment by chunleiz** [comment]
it could be achieved through configuration

[[inputs.kube_inventory]]
  fieldpass = ["capacity_cpu_cores"]
[[inputs.kubernetes]]
  fieldpass = ["cpu_usage_core_nanoseconds "]
[[processors.rename]]
  [[processors.rename.replace]]
    measurement = "kube_inventory"
    dest = "kubernetes_node"
  [[processors.rename.replace]]
    measurement = "kubernetes"
    dest = "kubernetes_node"

**Comment by sjwang90** [comment]
Thanks @chunleiz - is adding a processor sufficient for you? If it is we'll just have this as an item to add to plugin READMEs.
