### ISSUE TITLE
inputs.docker plugin writes to AWS timestream error

### ISSUE THREAD

**Issue by lcgogo** [influxdata/telegraf#9452]
I want to collect docker stats by telegraf docker plugin.

My config is like below:
```shell
# BEGIN ANSIBLE MANAGED BLOCK
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = true
  total = false
  docker_label_include = []
  docker_label_exclude = []
  tag_env = ["JAVA_HOME", "HEAP_SIZE"]
# END ANSIBLE MANAGED BLOCK
```
However, the telegraf log shows
```
.......
Jun 30 03:12:50 ip-172-30-0-26 telegraf[13942]: 2021-06-30T03:12:50Z E! [outputs.timestream] Failed to write to Timestream database 'CoboInfraMonitorTimestream' table 'docker_container_cpu'. Skipping metric! Error: 'ValidationException: The dimension name is invalid. Dimension name can only contain alphanumeric characters and underscores. It can only start with an alphabet and cannot end with an underscore.'
Jun 30 03:12:50 ip-172-30-0-26 telegraf[13942]: 2021-06-30T03:12:50Z E! [outputs.timestream] Failed to write to Timestream database 'CoboInfraMonitorTimestream' table 'docker_container_blkio'. Skipping metric! Error: 'ValidationException: The dimension name is invalid. Dimension name can only contain alphanumeric characters and underscores. It can only start with an alphabet and cannot end with an underscore.'
......
```

**Comment by lcgogo** [comment]
Find the docker name option like --name xxx_yyy_xxx information doesn't send to timestream.

**Comment by lcgogo** [comment]
@zak-pawel Can you help to trouble shooting for my issue? Or it is caused by timestream data models?

**Comment by lcgogo** [comment]
@shatil Can you help to trouble shooting for my issue? Or it is caused by timestream data models?

**Comment by sjwang90** [comment]
This looks like a timestream error. @piotrwest can you assist?

**Comment by piotrwest** [comment]
Hi, the error you are getting:

`Failed to write to Timestream database 'CoboInfraMonitorTimestream' table 'docker_container_cpu'. Skipping metric! Error: 'ValidationException: The dimension name is invalid. Dimension name can only contain alphanumeric characters and underscores. It can only start with an alphabet and cannot end with an underscore.'`

means one of the dimension names (most probably one of the tags name) do not meet one of Timestream dimension name requirements. Please check the requirements here: https://docs.aws.amazon.com/timestream/latest/developerguide/ts-limits.html - section **Naming Constraints**.

You can use [Rename Processor Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/processors/rename) to rename the tag name (which is mapped to dimension name).

**Comment by lcgogo** [comment]
> Hi, the error you are getting:
> 
> `Failed to write to Timestream database 'CoboInfraMonitorTimestream' table 'docker_container_cpu'. Skipping metric! Error: 'ValidationException: The dimension name is invalid. Dimension name can only contain alphanumeric characters and underscores. It can only start with an alphabet and cannot end with an underscore.'`
> 
> means one of the dimension names (most probably one of the tags name) do not meet one of Timestream dimension name requirements. Please check the requirements here: https://docs.aws.amazon.com/timestream/latest/developerguide/ts-limits.html - section **Naming Constraints**.
> 
> You can use [Rename Processor Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/processors/rename) to rename the tag name (which is mapped to dimension name).

Many thanks. I find the rename processor plugin example is used to change the tag name
- network_interface_throughput,hostname=backend.example.com lower=10i,upper=1000i,mean=500i 1502489900000000000
+ throughput,host=backend.example.com min=10i,max=1000i,mean=500i 1502489900000000000

However, what I want to change is the content of container_name like

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker

container_name=zen_ritchie       to        container_name=zen-ritchie 

because
I find the docker name option like --name xxx_yyy_xxx information doesn't accept by timestream.

**Comment by piotrwest** [comment]
In Timestream Output plugin, tags will be mapped to Timestream dimensions. Therefore, `container_name=zen_ritchie` will become dimension name `container_name` with value `zen_ritchie`. This is a valid dimension name and dimension value. The other variation you specified - ` container_name=zen-ritchie` is also valid dimension name and dimension value.

Therefore, I believe the error is somewhere else. Please provide full log of written records to Timestream, along with the exception message you are getting. To enable logging see: https://github.com/influxdata/telegraf/tree/master/plugins/outputs/timestream#logging
