### ISSUE TITLE
Support 'port' tag in ClickHouse plugin

### ISSUE THREAD

**Issue by rvql** [influxdata/telegraf#9463]
## Feature Request

Support metrics collecting on a system with multiple ClickHouse instances.

### Proposal:

Add a 'port' field in metric tags to support multiple instance.

### Current behavior:

An example point:

```
clickhouse_tables,database=system,host=h1,source=127.0.0.1,table=query_log bytes=696182i,parts=5i,rows=7615i 1625130161000000000
```

### Desired behavior:

Add port field:

```
clickhouse_tables,database=system,host=h1,port=8123,source=127.0.0.1,table=query_log bytes=696182i,parts=5i,rows=7615i 1625130161000000000
```

### Use case:

Metrics collected from multiple ClickHouse instances deployed on a single host cannot be differentiated by present tags.

Adding a 'port' tag will solve the problem.

**Comment by cnkei** [comment]
A possible fix.
```
diff --git a/plugins/inputs/clickhouse/clickhouse.go b/plugins/inputs/clickhouse/clickhouse.go
index 3a46390b..b2af079f 100644
--- a/plugins/inputs/clickhouse/clickhouse.go
+++ b/plugins/inputs/clickhouse/clickhouse.go
@@ -541,6 +541,7 @@ func (ch *ClickHouse) tables(acc telegraf.Accumulator, conn *connect) error {
 func (ch *ClickHouse) makeDefaultTags(conn *connect) map[string]string {
 	tags := map[string]string{
 		"source": conn.Hostname,
+		"port": conn.url.Port(),
 	}
 	if len(conn.Cluster) != 0 {
 		tags["cluster"] = conn.Cluster
```

**Comment by srebhan** [comment]
@cnkei we should guard this change with an user-configurable option (disabled by default) e.g. `output_port` and then add the port to the `source` tag as this is what other plugins do. We need the flag to be backward compatible and not break other peoples queries.

Do you want to submit a PR?

**Comment by cnkei** [comment]
Sure.

**Comment by srebhan** [comment]
Cool! Thanks a bunch! Please add the flag as discussed and assign me to the PR. I'll try to review in a timely manner...

**Comment by sspaink** [comment]
@rvql are you still interested in submitting a PR?
