### ISSUE TITLE
Procstat input incorrectly identifies PID of Windows service process when it stopped

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#9469]
### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
  win_service = "some_service_name"
  pid_finder = "native"
#  namepass = [ "procstat_lookup" ]
```

### System info:
Windows Server 2016
Telegraf version - 1.18.0

### Expected behavior:
When Windows service is stopped, field `running` in `procstat_lookup` measurement will be `0`

### Actual behavior:
Native PID finder misidentifies process:
```
2021-07-06T11:08:04Z I! Starting Telegraf 1.18.0
procstat,host=HOST.LOCAL,process_name=[System\ Process],win_service=some_service_name num_threads=2i,pid=0i,ppid=0i 1625569685000000000
procstat_lookup,host=HOST.LOCAL,pid_finder=native,result=success,win_service=some_service_name pid_count=1i,result_code=0i,running=1i 1625569685000000000
```
Also, `sc query "some_service_name"` returns correct state - STOPPED

### Additional info:
The Telegraf service was created in the standard way - `telegraf.exe ...... -service install`

**Comment by sspaink** [comment]
next steps: investigate how procstat determines running state for Windows

**Comment by srebhan** [comment]
@M0rdecay does that issue still exist?
