### ISSUE TITLE
some fields are collapsed in input.snmp_trap 

### ISSUE THREAD

**Issue by SorryGames** [influxdata/telegraf#9470]
Good day!

I have the following Telegraf topology: 
```
input.snmp_trap -> output.http
```

I have upgraded Telegraf agent within the version of 1.19.0. For the same SNMP and Telegraf configuration I have different SNMP trap messages.

For an old version of Telegraf (installed from apt repositories):
```
admin@st2-prod:~$ telegraf --version
Telegraf 1.19.0 (git: HEAD ed412d7f)

# SNMP trap message coming from output.http
{
  "metrics": [
    {
      "fields": {
        "enterprises.232.165.1.1.1": 0,
        "enterprises.232.165.1.1.2": "Test Trap",
        "enterprises.232.165.1.1.3": "http://172.17.17.7",
        "enterprises.232.165.1.1.4": "SN: 3C89411919       PN: 326528-002       MN: R5500 XR",
        "enterprises.232.165.1.1.5": "HP UPS Management Module",
        "sysName.0": "hpe_battery",
        "sysUpTimeInstance": 593913227
      },
      "name": "snmp_trap",
      "tags": {
        "agent_address": "172.17.17.7",
        "community": "public",
        "host": "matvey-pc",
        "mib": "SNMPv2-SMI",
        "name": "enterprises.232.165.0.3",
        "oid": ".1.3.6.1.4.1.232.165.0.3",
        "source": "172.17.17.7",
        "version": "1"
      },
      "timestamp": 1625566614
    }
  ]
}
```

For a new version of [nightly-telegraf](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb):
```
admin@st2-prod:~$ telegraf --version
Telegraf unknown (git: master 17e86ab4)

# SNMP trap message coming from output.http
{
  "metrics": [
    {
      "fields": {
        "enterprises": "http://172.17.17.7",
        "sysName": "hpe_battery",
        "sysUpTimeInstance": 593979402
      },
      "name": "snmp_trap",
      "tags": {
        "agent_address": "172.17.17.7",
        "community": "public",
        "host": "matvey-pc",
        "mib": "SNMPv2-SMI",
        "name": "enterprises",
        "oid": ".1.3.6.1.4.1.232.165.0.3",
        "source": "172.17.17.7",
        "version": "1"
      },
      "timestamp": 1625567276
    }
  ]
}
``` 

Seems like the fields of `enterprises` are collapsed into the one in the new version of Telegraf. What do you think about?

**Comment by Hipska** [comment]
Seems to be introduced by #9343, but I don't see why.

**Comment by SorryGames** [comment]
> Seems to be introduced by #9343, but I don't see why.

The reason [here](https://github.com/influxdata/telegraf/pull/9307) as I see.

**Comment by Hipska** [comment]
That PR wasn't merged into telegraf. It seems more like this is the reason:
https://github.com/influxdata/telegraf/blob/17e86ab4ca97af454e19d34d6d0e815c248e3a08/plugins/inputs/snmp_trap/snmp_trap.go#L408

@MyaLongmire would `node.RenderOID` be better to use?

**Comment by MyaLongmire** [comment]
Looking at the functions available [here](https://pkg.go.dev/github.com/sleepinggenius2/gosmi) I am not seeing a `RenderOID()`. I also tried changing the code to n`ode.RenderOID()` and I get an error `node.RenderOID undefined (type gosmi.SmiNode has no field or method RenderOID)`

**Comment by Hipska** [comment]
@MyaLongmire I'm talking about this one: https://pkg.go.dev/github.com/sleepinggenius2/gosmi@v0.4.3/smi#RenderOID

**Comment by MyaLongmire** [comment]
`RenderQualified()` returns the mib name ex. IF-MIB::ifPhysAddress. `RenderOID()` is nested in gosmi and I am still getting errors everytime I try to call it. This is the documentation I am using https://pkg.go.dev/github.com/sleepinggenius2/gosmi

**Comment by Hipska** [comment]
Example usage:
https://github.com/sleepinggenius2/gosmi/blob/841095eac905c34222076a761d6d534d1fc8fef6/node.go#L37-L39

**Comment by Hipska** [comment]
@MyaLongmire? This should be fixed in order to get telegraf deployed as the trap receiver for a very big client of us.

**Comment by Hipska** [comment]
@MyaLongmire ?

**Comment by MyaLongmire** [comment]
I cannot just call `RenderOID()` as it is nested in the function `RenderNumeric()`. I will not have time to work on this until after the holidays

**Comment by MyaLongmire** [comment]
@SorryGames if you will please test out [this pr](https://github.com/influxdata/telegraf/pull/10430) and see if it fixes your issue. Thank you!
