### ISSUE TITLE
Add working_directory or similar to procstat fields

### ISSUE THREAD

**Issue by pmalek-sumo** [influxdata/telegraf#9473]
## Feature Request

Add working_directory or similar to procstat fields

### Proposal:

This should be fairly easy to add since it's already available in the underlying implementation of `gopsutil` that telegraf uses: https://github.com/shirou/gopsutil/blob/v3.21.3/process/process.go#L368-L371 via the 

```go
func (p *Process) Cwd() (string, error)
```

function.

I am willing to submit a PR if the idea gets accepted.

### Current behavior:

No such field is available in procstat plugin

### Desired behavior:

Make it available

**Comment by pmalek-sumo** [comment]
@pmalek-sumo Unfortunately I won't have time to work on this, now. It should be relatively easy to pick up, though.

**Comment by srebhan** [comment]
I'm closing this due to missing interest. If you need this feature, please feel free to reopen the issue or create a new one!
