### ISSUE TITLE
Make breaking changes that require a major version update (2.0)

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9478]
Just because 2.0 isn’t required to be backward compatible doesn’t mean we can ignore usability for current users.  When we remove something people use we should replace it with a clear error so people know a change has been made and they need to adapt.  

The errors should recommend a migration path or actively allow users push an update to their config.  For example, the udp_listener will be removed.  If someone tries to use it there should be an error saying to migrate to socket_listener.  It shouldn’t be a warning that the user can ignore, but instead be a fatal error that requires the user to adapt their config before continuing to use telegraf.

### Entire Plugins

- [x] [inputs.cassandra](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cassandra) -> inputs.jolokia2 w/ example [cassandra.conf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2/examples/cassandra.conf)
- [ ] [inputs.http_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener) -> inputs.influxdb_listener (already renamed - make sure it's completely removed)
- [x] [inputs.httpjson](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/httpjson) -> inputs.http
- [ ] [inputs.jolokia](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia) ->  inputs.jolokia2
- [x] [inputs.kafka_consumer_legacy](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kafka_consumer_legacy) -> inputs.kafka_consumer
inputs.kafka_consumer_legacy is the only way to use kafka version <0.8. When remove legacy plugin, note that plugin only supports Kafka v0.8+
- [ ] [inputs.leofs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/leofs) -> inputs.snmp
- [ ] [inputs.logparser](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser) -> inputs.tail
- [x] [inputs.snmp_legacy](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp_legacy) -> inputs.snmp
- [x] [inputs.tcp_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tcp_listener) -> inputs.socket_listener
- [x] [inputs.udp_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/udp_listener) -> inputs.socket_listener
- [x] [outputs.reimann_legacy](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/riemann_legacy) -> outputs.reimann

Partially resolved in: https://github.com/influxdata/telegraf/pull/9609

### Refactor plugins

- [x] #11108
- [ ] [inputs.file](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/file). Rename to inputs.value_file to avoid confusion

### Input plugin settings

- [ ] Activemq `server` and `port`
- [ ] Aerospike `enable_ssl`
- [ ] Amqp_consumer `url`
- [ ] Consul `datacentre`
- [ ] Disk `mountpoints`
- [ ] Docker `container_names`
- [ ] Docker `perdevice`
- [ ] Docker `total`
- [ ] Filecount `directory`
- [ ] Http_listener_v2 `path`
- [ ] Http_response `address`
- [ ] Httpjson `name`
- [ ] Influxdb_listener `max_line_size`
- [ ] Mongodb `ssl_enabled` and `cacerts`
- [ ] MQTT Consumer `metric_buffer`
- [ ] MQTT Consumer `servers` format without scheme
- [ ] NATS Consumer `metric_buffer`
- [ ] Nsq `name`
- [ ] Nsq_consumer `server`
- [ ] Openldap `ssl` and `ssl_ca`
- [x] #4872
- [ ] Rabbitmq `name`
- [ ] Rabbitmq `queues`
- [ ] Smart `path`
- [ ] Sqlserver `query_version` and `azuredb`
- [ ] Statsd `convert_names`
- [ ] Statsd `parse_data_dog_tags`
- [ ] Statsd `udp_packet_size`
- [ ] Vsphere `force_discover_on_init`
- [ ] Win_perfcounters `PreVistaSupport`
- [ ] Zookeeper `enable_ssl`

### Output plugin settings

Resolved in: https://github.com/influxdata/telegraf/pull/11748

- [ ] AMQP `database` and `retention_policy`
- [ ] AMQP `precision`
- [ ] AMQP `url`
- [ ] Influxdb `precision`
- [ ] Influxdb `url`
- [ ] Kinesis `partitionkey` and `use_random_partitionkey`
- [ ] Librato `source_tag`
- [ ] Wavefront `string_to_number` subtable

### Processor plugin settings

- [ ] #8011

### Serializers

- [ ] Should consider consistent behavior via https://github.com/influxdata/telegraf/issues/8830

### Common settings

- [ ] `flush_buffer_when_full`
- [ ] `utc`
- [ ] Kafka `enable_tls`
- [ ] TLS `ssl_ca`, `ssl_cert` and `ssl_key`

### Metric formats

- [ ] System input plugin `uptime_format field`
- [ ] ~Prometheus input and prometheus_client output `metric_version = 1` (May be more difficult than we think to remove)~
- [ ] Consul input `metric_version=1`
- [ ] Minecraft input tag `server`
- [ ] Net_response input fields `result_type` and `string_found`
- [ ] Kube_inventory input field `terminated_reason`
- [ ] [MySQL](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql) `metric_version = 1` (only existed for backwards compatibility for those on < Telegraf 1.6)
- [x] #4413
- [ ] Procstat empty cpu fields #11768 

## Internal APIs

- [ ] Metric interface: Tags(), Fields(), AddPrefix(), AddSuffix()
- [ ] [plugins/inputs/execd/shim](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd/shim) -> [plugins/common/shim](https://github.com/influxdata/telegraf/tree/master/plugins/common/shim)
- [x] #7993
- [x] #8016

## Builds, Packaging

- [ ] https://github.com/influxdata/telegraf/pull/10426

## Support only one v1/v2 plugins
Remove version nomenclature from plugin

- [ ] JSON Parser
  - [parsers.json](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json)
  - [parsers.json_v2](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2)
- [ ] HTTP Listener Input
  - [inputs.http_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_listener)
  - [inputs.http_listener_v2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener_v2)
- [ ] Jolokia Input
  - [inputs.jolokia](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia)
  - [inputs.jolokia2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2)

Note that the two InfluxDB output plugins will remain. They are named influxdb and influxdb_v2, but in this case the version doesn't refer to the plugin but the compatible version of influxdb.
- InfluxDB Output
  - [outputs.influxdb](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb)
  - [outputs.influxdb_v2](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb_v2)
- InfluxDB Listener Input
  - [inputs.influxdb_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_listener)
  - [inputs.influxdb_v2_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_v2_listener)

**Comment by sspaink** [comment]
Looks like `inputs.udp_listener` has a flaky tests, so will be nice to get that removed.
Example of failed test: https://app.circleci.com/pipelines/github/influxdata/telegraf/5841/workflows/83257327-ac12-47a2-961a-035a253a096c/jobs/104391/parallel-runs/0/steps/0-110

We should figure out when we can start removing these plugins.

**Comment by Hipska** [comment]
I'm not sure if the deprecation of `inputs.snmp.name` is a good thing, since the given alternative gives undesired results.
https://github.com/influxdata/telegraf/blob/4321f8ae67a95f152aa5e83074e1e06f588811c1/plugins/inputs/snmp/snmp.go#L118

**Comment by MyaLongmire** [comment]
deprecate inputs.mysql metric version 1 as it is recommended for user to use metric version 2

**Comment by Hipska** [comment]
@sjwang90 I believe this should be also the case for the influx inputs, no?
> Note that the two InfluxDB output plugins will remain. They are named influxdb and influxdb_v2, but in this case the version doesn't refer to the plugin but the compatible version of influxdb.

**Comment by Hipska** [comment]
@sspaink You ticked off all deprecated plugins as being removed by #9609, but that isn't correct. The first one I checked isn't removed by that PR. Can you revisit that PR or the checkboxes in that list so there is none forgotten?

**Comment by Hipska** [comment]
@sspaink?

**Comment by srebhan** [comment]
I removed all checkmarks as it is confusing given the fact that this is not yet done in master. Let's revisit this topic when we actually merge the PRs.

**Comment by Hipska** [comment]
@redbaron correct! See https://github.com/influxdata/telegraf/issues/12675. PR are appreciated!

**Comment by tguenneguez** [comment]
The plugin procstat doesn't have the same result with different mode.
The native mode with "exec" shoud filter on /proc/(pid)/comm and not on /proc/(pid)/exe.

https://github.com/influxdata/telegraf/issues/6174#issuecomment-1929748530

**Comment by powersj** [comment]
In v1.30.0 we finally removed some long-deprecated config options and plugins. We do not plan to remove anything else in the short-term. I am going to close this issue as we have no plans for a 2.x. We were keeping this open for a while to ensure we deprecated config options and plugins, but that is in a decent state at this point.
