### ISSUE TITLE
get logged on username as telegraf windows service

### ISSUE THREAD

**Issue by runningAgain** [influxdata/telegraf#9480]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
The agent can use some windows api to get the loggend on username from session 1 if there is a session 1. If there is no session then fallback to the normal behavior, but the username from the system account ist not really usefull.

### Current behavior:
On windows platform normally the agent is running in SYSTEM context. If use the environment var $username the value is system.

### Desired behavior:
If var $username is requested in config then ...
Telegraf agents looks if there is a session logged on the system and then the agent overwrites the value of $username.

### Use case: 
There are a lot of windows performance counter wich are only usefull if there is a reference (tag) to the logged on user.
Without these reference you must everytime look on the system which user was logged on and this is only possible when the system is running

there is a little executable wich do this, as an example .. start cmd.exe as system with psexec. Then run the command "query user". the result is the following.

![2021-07-08_09h19_41](https://user-images.githubusercontent.com/25197235/124880099-3592c400-dfce-11eb-86bc-1400b56f804d.jpg)

C:\Users\Username>query user
 USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME
>Username             console             1  Active      none   01.07.2021 08:11

**Comment by sspaink** [comment]
@runningAgain just to clarify, are you requesting that the `inputs.win_services` plugin adds the username as a tag? Looking at the README it doesn't look like the plugin adds any username information currently. Could tells us more about why the performance counters need a reference to the user?

**Comment by runningAgain** [comment]
@sspaink 
The determination of Windows performance counters is normally based on the system itself.
So you have a 1:1 reference between the performance data and the system name (computer name). For Windows Server this is also ok. 
If you want to evaluate the performance data in a Windows client environment with changing system - user relationship it is advantageous to have not only the computer name as tag but also the user name of the logged in user. Regardless of which Windows performance counter / plugins I want to use. 
As an example can serve here e.g. a VDI environment. From the user's perspective, the user logs on to a different virtual computer every day. If you want to analyze performance problems reported by the user afterwards, you have no reference between user / time and system. 
You can certainly merge this based on a duplicate investigation downstream. So on the one hand I have my performance data + time + system, on the other hand I determine with other plugins a user + time + system reference. I then have 2 data sources and then merge them again in e.g. Grafana. But the whole thing is too complicated.
It is simpler, the Telegraf service runs with system permissions and can thus determine the logged in user via a dedicated "Windows API function". If no user is logged in, the account under which the service runs is taken as the username/tag.

**Comment by powersj** [comment]
Is this still something you are interested in? If so, can you confirm it was for the windows services plugin?
