### ISSUE TITLE
serializers/msgpack: Freeze MessagePack serialization behavior for int64s and uint64s

### ISSUE THREAD

**Issue by shenghaoyang** [influxdata/telegraf#9482]
## Feature Request

Maybe also a partial documentation bug 😅 ?

### Proposal:

Document that Telegraf's MessagePack output format will:
- always serialize unsigned integer field values (`uint64`s) using unsigned MessagePack integer formats.
- always serialize signed integer field values (`int64s`) using signed MessagePack integer formats.

Maintain documented behavior in future releases.

### Current behavior:

Telegraf provides no such documentation in the [serializer README](https://github.com/influxdata/telegraf/tree/master/plugins/serializers/msgpack).

### Desired behavior:

That behaviour is documented and does not remain an implementation detail.
Telegraf maintains the documented serialization behaviour for future releases.

### Use case: 

The MessagePack type system [does not have](https://github.com/msgpack/msgpack/blob/master/spec.md#type-system) the notion of unsigned / signed integers - those concepts only exist for MessagePack formats.

The MessagePack specification likewise [does not mandate](https://github.com/msgpack/msgpack/issues/164) that conforming implementations always use unsigned integer wire formats when serializing unsigned integers (likewise for signed integers). Most implementations appear to use unsigned integers for positive values, regardless of the sign of the application type.

The current implementation used in Telegraf [offers that guarantee](https://github.com/tinylib/msgp/wiki/Type-Mapping-Rules#rule-3-sign-matters), but there are other implementations like [msgpack-c](https://github.com/msgpack/msgpack-c) that do not.

Having this behaviour is useful because it lets us easily recover the field value's type. If an implementation were to vary the signedness of wire formats it uses to serialize a Go signed integer / unsigned integer to optimize for the lowest message size - the deserializing application cannot tell what the original field's type was without including extra information in the message (though one could argue that using specific wire formats _is_ embedding that information, because it does not result in the smallest message size for all cases). 

Being unable to recover the types may cause issues when writing data back into InfluxDB after deserializing the measurement from the MessagePack format.

**Comment by shenghaoyang** [comment]
Ah, sorry - it seems like that rule in `msgp` doesn't apply anymore (or I've likely misinterpreted it). In our tests we've seen `24i` being written out as a positive fixint.

Apologies for the noise - but this does mean that there's no way for downstream applications to recover the type of the original field value.

**Comment by srebhan** [comment]
As a workaround you can change the type of that field to uint64 in telegraf using e.g. the starlark processor.

**Comment by shenghaoyang** [comment]
Ah, I see what you mean  - that would work but also cause the serializer to encode `-1` using 8 bytes instead of 1 =/, and we have to assume that every deserialized `uint64` with the MSB set was originally an `int64`, i.e. the MSB is now being used to encode type information.

Thanks for the idea, though! We might end up using it if there's nothing else we can easily do (after doing some checks on the range of our `uint64` field values, of course 😄 )

**Comment by srebhan** [comment]
@shenghaoyang well you are free in how you convert `int64` to `uint64` in e.g. starlark, so you can shuffle the bits around as you like. After you have your `uint64` value as you like, you either create a new field or override the field with the `uint64` datatype and value. This way the metric should show a `24u`. Assuming `msgpack` itself does a correct encoding, this should give you a msgpack encoded unsigned int that you can decode on the other end, persisting the unsigned information.

For the bits, you might want to collect them in a `uint64`. This can also be done in `starlark` IIRC. However, I'm aware that this means you introduce a certain semantic to the new field that is not explicit in your message. You have to decide which of "saving some bits" or "preserving semantics" is more important. Alternatively, converting your bit into an `uint8` field _might_ work, but not sure.
