### ISSUE TITLE
inputs.exec plugin - option to ignore return code

### ISSUE THREAD

**Issue by runningAgain** [influxdata/telegraf#9483]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
For the exec input plugin there is an option to ignore the returncode from the executable (linux and windows)

### Current behavior:
Testet with windows agent, i use the exec plugin to execute the command "query user". These executable returns always an errorcode 1. But if i use this command native i'll get some data returned.

### Desired behavior:
If the new option "ignore_error_code = true" is set and the command returns other than 0 as returncode, the output of the command is used to processed the metric.

### Use case: 
The usage of the exec plugin is only helpfull with this option because there are a lot of applications/executables which doesnt return 0 as errorcode but returns data to work with them.

**Comment by reimda** [comment]
Would it solve the problem to run the `query user` command in a batch file? Most commands return 0 for success so I'm not sure adding a new option is worth it.

**Comment by runningAgain** [comment]
I also don't know if it's worth the work. What I do know from my 20 years of IT script experience is that there are always return codes that are different from what you expect or are not implemented correctly. Therefore such a "standard option" would make sense.
Especially for a plugin that directly calls an executable and should interpret the return code correctly. That also makes sense.
Of course, in such a case you can write your own "wrapper" which then again "ignores" the actual return code and only returns its own, such as in a batch file.
