### ISSUE TITLE
Add InfluxDB Protobuf Data Protocol as data format output

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9492]
## Feature Request

Add **InfluxDB Protobuf Data Protocol** as a data format to output metrics in this new format

This protocol defines formatting and rules to write data to [InfluxDB/IOx](https://github.com/influxdata/influxdb_iox).
The protocol is optimized for efficient ingestion into IOx, and is also a good choice for transporting timeseries data generally.
It is not intended to replace [line protocol](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/), but should be considered a good alternative to line protocol.

See more: https://github.com/influxdata/influxdb-pb-data-protocol

### Use case: 
Telegraf will require a method to output metrics in InfluxDB Protobuf Data Protocol to work with efficient ingestion into IOx.

**Comment by sjwang90** [comment]
@jacobmarble Would you or someone on your team be able to do a review on this PR and test it with IOx if possible?

**Comment by reimda** [comment]
It sounds like this feature is on hold. See the comments in #10187. Closing for now, but could revisit in the future.
