### ISSUE TITLE
Telegraf 1.19 lack of memory with couchbase plugin

### ISSUE THREAD

**Issue by Levarix** [influxdata/telegraf#9495]
I've tested this, and now we have another huge problem. I applied a new version of telegraf in a production environment and telegraf processes consumes a lot of memory and don't purge it. Memory usage is still increasing until instance stopped work. It happens only with telegraf with couchbase plugin

![image](https://user-images.githubusercontent.com/34714430/125412400-2db49480-e3bf-11eb-8c4a-ccb25355c768.png)

![Zrzut ekranu 2021-07-13 o 09 47 15](https://user-images.githubusercontent.com/34714430/125412550-bbe943f5-c89a-47e3-96df-d0f024245e4e.png)
In the second screenshot, you can see memory usage increasing and after downgrade to 1.18.3 back to normal stable consumption

Thread started here: https://github.com/influxdata/telegraf/pull/9448

**Comment by srebhan** [comment]
@Levarix can you please test #9536 and let me know if it helps? You can use the [artifacts built by the CI bot](https://github.com/influxdata/telegraf/pull/9536#issuecomment-885601169) (click the small black triangle).

**Comment by srebhan** [comment]
@Levarix can you please test the fix of @akrantz01 in #9544? The CI artifacts can be found [here](https://github.com/influxdata/telegraf/pull/9544#issuecomment-887089046).

**Comment by Levarix** [comment]
Yes, @srebhan I will try test it today or tommorrow

**Comment by Levarix** [comment]
@srebhan Tested version 1.19.2 and the same issue

**Comment by Levarix** [comment]
I'm testing version from there now

> @Levarix can you please test the fix of @akrantz01 in #9544? The CI artifacts can be found [here](https://github.com/influxdata/telegraf/pull/9544#issuecomment-887089046).

**Comment by Levarix** [comment]
Looks like we have stable solution now
![Zrzut ekranu 2021-08-13 o 14 52 19](https://user-images.githubusercontent.com/34714430/129359858-6d0c31b4-db28-41d8-a9bc-76c3e413a5a9.png)

**Comment by srebhan** [comment]
@Levarix sorry I was afk for some time. Could you please comment on #9544 that it fixed your issue to let the guys know!?
