### ISSUE TITLE
ProcStat not getting all the process stats on Telegraf 1.19.1

### ISSUE THREAD

**Issue by vsenapathy** [influxdata/telegraf#9499]
I am trying to get ProcStat data and I only get telegraf data, no other process data i am getting.

Conf file
# Global tags can be specified here in key="value" format.
[global_tags]

# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000  
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

  ## Override default hostname, if empty use os.Hostname()
  hostname = "___HOSTNAME___"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
   urls = ["https://___DBURL___"]
   database = "___DBNAME___"

[[inputs.procstat]]
  pattern = ".*"
  ## I have even tried pattern like pattern = "java"
  pid_tag = true

Telegraf version 1.19.1. I am trying to get VMPeak for every single process that is running, but i am not able to. Can someone help me with this. 

Thanks,

Vignesh

**Comment by vsenapathy** [comment]
Hello,

Can someone help me out with this

Thanks,

vignesh

**Comment by kapsh** [comment]
@vsenapathy 
1. How do you run telegraf? If this is docker container, ensure you have all necessary mounts and settings. If this is system service, try to run it as root (since not all information may be available for restricted user).
2. Have you checked any logs? Can you post them here? 
3. What procstat_lookup measurement is saying in details?
