### ISSUE TITLE
Filtering datastore by esxi host cluster

### ISSUE THREAD

**Issue by lihtian285** [influxdata/telegraf#9515]
## Feature Request
I am trying to display datastore by cluster on Grafana. I am trying to explore the metrics being collected by this plugin and cannot find cluster information in datastore measurements.

Opening a feature request kicks off a discussion.

### Current behavior:
vSphere plugin has no cluster information in Datastore metrics. It couldn't filter datastore by cluster.

### Desired behavior:
Cluster information to be collected by Datastore metric. So it allows us to query the cluster information from datastore metrics. 

### Use case: 
The vCenter contains a lot of the datastores. Filter datastore by cluster or host could make the user life easy to view the datastore which is important to them.

**Comment by reimda** [comment]
Were you able to find a solution for this?
