### ISSUE TITLE
Does ping support distributed Ping the target website from multiple locations

### ISSUE THREAD

**Issue by louishot** [influxdata/telegraf#9516]
## Feature Request

Opening a feature request kicks off a discussion.

**Comment by popey** [comment]
Great idea. Sadly the ping plugin we currently have doesn't have this capability. Unless of course you run telegraf in multiple locations, and ping from different networks, from telegraf. If there's a service which can do this, and has an API, perhaps a telegraf plugin could be created to leverage that. Might be worth discussing on the [forums](https://community.influxdata.com/tag/telegraf).
