### ISSUE TITLE
Do not change permissions on upgrade for RPM

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9521]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Request for RPM to be modified to not change permissions on upgrade.

### Current behavior:
When upgrading Telegraf via RedHat RPMs, it changes the permissions on the Telegraf directories off of `/etc` which then flags a security issue.

### Desired behavior:
When upgrade Telegraf, permissions for telegraf.d remains the same and do not get overwritten

### Use case: 
Telegraf should retain  root permission changes on upgrades. Flags as a security issue when Telegraf gets upgraded and permissions reset to root.

**Comment by sjwang90** [comment]
Notes about how implementation of changes would affect all platform builds not just rpm:
> Telegraf builds packages for multiple linux distributions as well as mac, windows, and freebsd. To remove the need to have the build process know how to build each package for each platform, telegraf uses a packaging tool called FPM. (https://github.com/jordansissel/fpm) Since telegraf isn't building rpms directly, the change Techniker Krankenkasse is requesting may not be possible. If it is possible to do through FPM, it will likely affect the other platforms as well so it would affect all telegraf users who upgrade packages. The change would require manual testing upgrades on rpm and deb platforms. In short, this change would not be as easy or free of side effects as it sounds.

**Comment by 1tft** [comment]
I want to clarify again: During Telegraf RPM update ONLY following directory permissions are changed "/etc/telegraf/telegraf.d"
No files inside are changed, and also lobal directory /etc/telegraf is untouched.
So I still think its a bug and could be fixed without changing complete packaging infrastructure. If it would a general FPM issue, there should also /etc/telegraf be affected but only /etc/telegraf/telegraf.d is changed, Please can you check this again?

**Comment by powersj** [comment]
@1tft,

Looking at other rpm's I see the same behavior. As configuraiton files and folders are put down permissions are reset. /etc should really be owned by root or some user the service belongs to.

**Comment by 1tft** [comment]
@powersj Thank you for your answer. It would be also OK, when /etc/telegraf would be assigned to telegraf group. Than we could add our mangement user to this telegraf group (already done) and manage telegraf config without root user.

**Comment by powersj** [comment]
> /etc/telegraf would be assigned to telegraf group. Than we could add our mangement user to this telegraf group (already done) and manage telegraf config without root user.

ok! Given we create a telegraf user already and [run as the telegraf user](https://github.com/influxdata/telegraf/blob/master/scripts/telegraf.service#L10) this might be a safe change.

Let me put a note down and talk about this in the new year with folks.

**Comment by 1tft** [comment]
@powersj Have to clarify (after testing again), telgraf (yum) update resets /etc/telegraf/telegraf.d permission and owner. It does not reset /etc/telegraf
So currently /etc/telegraf/telegraf.d has 755 (no write right for group). So members of group telegraf can not write to /etc/telegraf/telegraf.d . So we need two change (to get desired state - configure telegraf config without root user):
chown root:telegraf /etc/telegraf/telegraf.d
and
chmod 775 /etc/telegraf/telegraf.d

But currently no "telegraf" group is created by rpm package (only user). So its more than a little change...

So I think, best way would be, not to reset /etc/telegraf/telegraf.d permission and group, during rpm update.

**Comment by powersj** [comment]
> best way would be, not to reset /etc/telegraf/telegraf.d permission and group, during rpm update.

I do not believe we can make this change. This is how the RPM is built not something we, telegraf, are stating to do.

**Comment by 1tft** [comment]
That was also the answer (after 1 year) in my InfluxData Support ticket. They said, they cant modify rpm deployment because its managed by fpm or sth. like this and its not possible to change something here. They said, they want to fix it at next telegraf major version (2.x).

But I think, because rpm update does not change /etc/telegraf but /etc/telegraf/telegraf.d its sth. custom for application/telegraf and maybe its possible also with fpm.
Next year I will ask a fpm professional for a analysing this. Because telegraf is open source, we can analyse it on our own. So maybe next year we get an answer what could be changed. I will post it here...

**Comment by 1tft** [comment]
> Next year I will ask a fpm professional for a analysing this.

@powersj Now we have received the FPM/RPM analysis results by our professional linux consultant. He said, that FPM or better RPM, does not handle config directories. Thats why Telegraf package creators should work with a simple placeholder/dummy file inside /etc/telegraf/telegraf.d directory to avoid overriding of /etc/telegraf/telegraf.d (with initial permissions) during update process.
Thats why he created a patch regarding the used Makefile where he used a dummy file named ".ignore" to successfully avoid directory overriding during RPM update:
![image](https://user-images.githubusercontent.com/8899007/217083287-35e92b64-e322-448e-ad5d-035d343f3058.png)

He also mentioned that dpkg/apt management system works similar, thats why you will find such a placeholder file on debian/ubuntu: `/etc/cron.d/.placeholder` (with content: `# DO NOT EDIT OR REMOVE # This file is a simple placeholder to keep dpkg from removing this directory`)
So please can you verify this easy solution on your FPM environment (adding a .placeholder file inside config.d directory) for telegraf rpm package.

**Comment by jdstrand** [comment]
@powersj asked me to comment.

* I question 775 of the `/etc/telegraf/telegraf.d` directory (or other files in `/etc/telegraf`) as a default. Most of the time one wants to limit the access to root (read/write), telegraf (read) and with 'other' having no access (consider secrets in the file). There might be situations where telegraf writing might be desirable, but that seems site-specific
* adding a `telegraf` group seems quite reasonable and by default having `/etc/telegraf` and `/etc/telegraf/**` use this group seems very reasonable. By adding the group, you setup the user to be able to change the permissions easily (I suggest only calling chgrp on install and not upgrades though to avoid potentially breaking existing installs).
* I'd keep the normal 755/644 permissions as a default at least for 1.x. For 2.x, could consider 750/640 permissions
* assuming it works going back to at least centos7, `/etc/telegraf/telegraf.d/.ignore` seems like a reasonable thing to do. We just want to make sure the directory is there; we don't want to manage it. I'd suggest putting a comment in it though:
    ```
    # DO NOT EDIT OR REMOVE
    # This file prevents rpm from changing permissions on this directory and the files within it
    ```
    (or similar)
* I'm not sure that `/etc/telegraf/telegraf.d/.ignore` is needed for debs though unless we're seeing a similar issue. IIRC, I think it is ok with permissions on upgrades and will only remove the directory on package removal if the directory is empty. Someone should test that

**Comment by powersj** [comment]
Thanks for the response @jdstrand and for loop back around @1tft 

For the purpose of this issue, I have created #12643. This creates the .ignore file for the RPM packaging only. Next steps are to go through the test cases listed in that PR.

For the different permissions and group, I'll work with Sven to determine when we might land those changes in a future PR.

Thanks again!

**Comment by powersj** [comment]
@1tft can you take a look at the artifacts in the attached PR and confirm this would work in your situation?

Thanks!

**Comment by 1tft** [comment]
@powersj Thank you for that fast PR.
Tried different install/upgrade processes and I think it does exactly what expected: /etc/telegraf/telegraf.d is not resetted regarding permissions by telegraf RPM updates (any longer).

Two notes:
Maybe  "_.placeholder_" would be a better/common file name (instead of "_.ignore_")?
I would remove "_and the files within it_" from content of the new .placeholder/.ignore file, because by user added files to this empty dir have been already untouched without this PR/ignore file "hack".

**Comment by powersj** [comment]
> Tried different install/upgrade processes and I think it does exactly what expected: /etc/telegraf/telegraf.d is not resetted regarding permissions by telegraf RPM updates (any longer).

Excellent! thank you for confirming

> Maybe ".placeholder" would be a better/common file name (instead of ".ignore")?
> I would remove "and the files within it" from content of the new .placeholder/.ignore file, because by user added files to this empty dir have been already untouched without this PR/ignore file "hack".

Ah good point on the wording. I will update it to only mention the directory. I am going to keep the file named .ignore since we won't be replacing it with anything.

Thanks again - I'll get this reviewed and part of next week's v1.25.2
