### ISSUE TITLE
vSphere - Not receiving metric for each host to aggregate total memory

### ISSUE THREAD

**Issue by wzamlynny** [influxdata/telegraf#9525]
## Problem
I am looking for a way to deterministically get the total memory in a vSphere cluster by aggregating host metrics. The number of hosts in the cluster may change and cannot be assumed.

This is to work around the [cluster limits for a vCenter with large number of VMs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/vsphere#cluster-metrics-and-the-max_query_metrics-setting). The cluster metric to be simulate is `vsphere_cluster_mem | totalmb_average` and I am summing up the host metric `vsphere_host_mem | totalCapacity_average`.

## Description
During the aggregation period, not all hosts have metrics come in. For example, out of three hosts, I may only get 1 or 2 counts for this metric. A metric for each host does come in about half the time, and in this case the sum matches up to the total memory. It does not look like these metrics are being delayed as there are no metrics dropped outside the aggregation period window (logging this to debug) and the sum of hosts does not spike above the expected sum (max count has been 3).

My aggregation period is the same as the telegraf pulling period - 5 minutes. I have both aligned to start at round increments (ie. 01:05:00). I am using a custom function to aggregate, with logic is referenced from basicstats / [custom aggregators](https://github.com/influxdata/telegraf/blob/master/docs/AGGREGATORS.md) and the period logic from the [running_aggregator](https://github.com/influxdata/telegraf/blob/fa65a82ef36f0783f11bbad1f6cf2a2cbf7910a7/internal/models/running_aggregator.go).

## Questions
- Why does each host not have a metric populated during each telegraf pull cycle?
-  Is there a metric from the vSphere plugin to get the current number of hosts? (To potentially skip if data is missing or fill in the blanks while reacting to potential changing number of hosts).
- Is there a better equivalent host metric?

Any alternatives you could suggest to aggregate the total memory in a cluster using the host metrics would be useful. Thanks!

### Relevant telegraf.conf
Set to pull metrics every 5 minutes at round intervals. Showing relevant host config.
```
[agent]
  interval = "300s"
  round_interval = true
  metric_batch_size = 9
  metric_buffer_limit = 15000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "15s"

[[inputs.vsphere]]
 
  tagexclude = ["source", "vcenter", "moid", "dcname", "cpu", "disk"]

  host_metric_exclude = [
    "disk.*",
    "net.*",
    "power.*",
    "vmop.*",
  ]
 
  insecure_skip_verify = true

  max_query_metrics = 256
  collect_concurrency = 3
```

### Logs from aggregation function
```
2021-07-21T22:05:00Z E! [processors.execd] stderr: "2021/07/21 22:05:00 Aggregated (sum) vsphere_host_mem.totalCapacity_average -> vsphere_cluster_mem_agg.totalmb_average, sum: 1.092328882176e+12, count: 2, avg: 5.46164441088e+11"

2021-07-21T22:15:00Z E! [processors.execd] stderr: "2021/07/21 22:15:00  Aggregated (sum) vsphere_host_mem.totalCapacity_average -> vsphere_cluster_mem_agg.totalmb_average, sum: 1.638734495744e+12, count: 3, avg: 5.462448319146667e+11"
```
### Graph over time - upper bound at 1.6TB is when all three hosts get aggregated during the period.
![image](https://user-images.githubusercontent.com/4238686/126568294-388936ad-35fb-43ab-9318-2163d49ea3ee.png)

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you yet.

> Why does each host not have a metric populated during each telegraf pull cycle?

I have not played with the vsphere input plugin that much, but I do find this surprising. Are you able to reproduce this without the use of any processors or aggregators? The config you provided seems to have omitted any processor or aggregors that you are using and I'm wondering if a setting there is causing things to get dropped.

> Is there a metric from the vSphere plugin to get the current number of hosts? (To potentially skip if data is missing or fill in the blanks while reacting to potential changing number of hosts).

I do not believe so.

I am curious about my question above and if you are still facing a similar issue or you were able to resolve this?

Thanks!
