### ISSUE TITLE
[vSphere] metrics missing in influxdb

### ISSUE THREAD

**Issue by morgan9220** [influxdata/telegraf#9528]
21-07-21T23:39:04Z I! Starting Telegraf 1.19.1
21-07-21T23:39:04Z I! Loaded inputs: vsphere (3x)
21-07-21T23:39:04Z I! Loaded aggregators:
21-07-21T23:39:04Z I! Loaded processors:
21-07-21T23:39:04Z I! Loaded outputs: influxdb
21-07-21T23:39:04Z I! Tags enabled: host=Trunks-Dashboard
21-07-21T23:39:04Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Trunks-Dashboard", Flush Inte>
21-07-21T23:39:04Z I! [inputs.vsphere] Starting plugin
21-07-21T23:39:05Z I! [inputs.vsphere] Starting plugin
21-07-21T23:39:06Z I! [inputs.vsphere] Starting plugin
g The plugin-driven server agent for reporting metrics into InfluxDB...
21-07-22T00:06:19Z I! [inputs.vsphere] Stopping plugin
21-07-22T00:06:19Z I! [inputs.vsphere] Stopping plugin
21-07-22T00:06:19Z I! [inputs.vsphere] Stopping plugin
21-07-22T00:06:19Z I! [agent] Hang on, flushing any cached metrics before shutdown
21-07-22T00:06:19Z I! [agent] Stopping running outputs
f.service: Succeeded.
 The plugin-driven server agent for reporting metrics into InfluxDB.
 The plugin-driven server agent for reporting metrics into InfluxDB.
me="2021-07-21T20:06:19-04:00" level=error msg="failed to create cache directory. /etc/telegraf/.cache/s>
me="2021-07-21T20:06:19-04:00" level=error msg="failed to open. Ignored. open /etc/telegraf/.cache/snowf>
21-07-22T00:06:19Z I! Starting Telegraf 1.19.1
21-07-22T00:06:19Z I! Loaded inputs: vsphere (3x)
21-07-22T00:06:19Z I! Loaded aggregators:
21-07-22T00:06:19Z I! Loaded processors:
21-07-22T00:06:19Z I! Loaded outputs: influxdb
21-07-22T00:06:19Z I! Tags enabled: host=Trunks-Dashboard
21-07-22T00:06:19Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Trunks-Dashboard", Flush Inte>
21-07-22T00:06:19Z I! [inputs.vsphere] Starting plugin
21-07-22T00:06:20Z I! [inputs.vsphere] Starting plugin
21-07-22T00:06:20Z I! [inputs.vsphere] Starting plugin

I can run

/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d

Output:

2021-07-22T00:12:43Z I! Starting Telegraf 1.19.1
2021-07-22T00:12:43Z I! Loaded inputs: vsphere (3x)
2021-07-22T00:12:43Z I! Loaded aggregators: 
2021-07-22T00:12:43Z I! Loaded processors: 
2021-07-22T00:12:43Z I! Loaded outputs: influxdb
2021-07-22T00:12:43Z I! Tags enabled: host=Trunks-Dashboard
2021-07-22T00:12:43Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Trunks-Dashboard", Flush Interval:10s
2021-07-22T00:12:43Z I! [inputs.vsphere] Starting plugin
2021-07-22T00:12:44Z I! [inputs.vsphere] Starting plugin
2021-07-22T00:12:44Z I! [inputs.vsphere] Starting plugin
^C2021-07-22T00:16:26Z I! [inputs.vsphere] Stopping plugin
2021-07-22T00:16:26Z I! [inputs.vsphere] Stopping plugin
2021-07-22T00:16:26Z I! [inputs.vsphere] Stopping plugin
2021-07-22T00:16:26Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-07-22T00:16:26Z I! [agent] Stopping running outputs

I run:
/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --test

output: 
2021-07-22T00:16:40Z I! Starting Telegraf 1.19.1
2021-07-22T00:16:41Z I! [inputs.vsphere] Starting plugin
2021-07-22T00:16:41Z I! [inputs.vsphere] Starting plugin
2021-07-22T00:16:42Z I! [inputs.vsphere] Starting plugin
> vsphere_datastore_disk,dcname=****** and so on

When I run it the second time with the test I get all of the output I would expect to go into influx from the ESXI host. I'm lost as to what the difference is. Any help would be appreciated and I'll provide any info needed to help resolve this.

**Comment by srebhan** [comment]
@morgan9220 the title of your issue is not very informative, please choose some speaking text next time.

This being said, the `--test` option will *only* output data to the console. From the help (`telegraf --help`):
```
  --once                         enable once mode: gather metrics once, write them, and exit
  --test                         enable test mode: gather metrics once and print them
```
So if you want to collect your metrics once and push it through your whole telegraf pipeline you should use `--once`.

**Comment by morgan9220** [comment]
@srebhan Sorry for not providing enough info. Problem I'm having is not getting any info from telegraf into influx, telegraf keeps stopping the plugin. 

usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --once
2021-07-22T23:12:33Z I! Starting Telegraf 1.19.1
2021-07-22T23:12:33Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:33Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-07-22T23:12:34Z I! [agent] Stopping running outputs





/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --test
2021-07-22T23:15:08Z I! Starting Telegraf 1.19.1
2021-07-22T23:15:08Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:15:08Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:15:09Z I! [inputs.vsphere] Starting plugin
> vsphere_datastore_disk,dcname=testname,disk=instance-total,dsname=1TB\ NVME,host=Trunks-Dashboard,moid=datastore-10,source=1TB\ NVME,vcenter=1.1.1.1 capacity_latest=976486400i,provisioned_latest=725411842i,used_latest=725411840i 1626746580000000000
> vsphere_datastore_disk,dcname=testname,disk=instance-total,dsname=Shenron,host=Trunks-Dashboard,moid=datastore-11,source=Shenron,vcenter=1.1.1.1 capacity_latest=1865154560i,provisioned_latest=1503232i,used_latest=1503232i 1626746580000000000
> vsphere_datastore_disk,dcname=testname,disk=instance-total,dsname=6TB\ RED,host=Trunks-Dashboard,moid=datastore-12,source=6TB\ RED,vcenter=1.1.1.1 capacity_latest=5860491264i,provisioned_latest=31254528i,used_latest=31254528i 1626746580000000000
> vsphere_datastore_disk,dcname=testname,disk=instance-total,dsname=Datastore1,host=Trunks-Dashboard,moid=datastore-14,source=Datastore1,vcenter=1.1.1.1 capacity_latest=976486400i,provisioned_latest=1317193731i,used_latest=696538112i 1626993720000000000
> vsphere_datastore_disk,dcname=testname,disk=instance-total,dsname=6TB\ Red\ 1,host=Trunks-Dashboard,moid=datastore-13,source=6TB\ Red\ 1,vcenter=1.1.1.1 capacity_latest=5860491264i,provisioned_latest=353662983i,used_latest=353662976i 1626746580000000000
> vsphere_host_cpu,cpu=20,dcname=testname,esxhostname=1.1.1.1,host=Trunks-Dashboard,moid=host-9,source=1.1.1.1,vcenter=1.1.1.1 coreUtilization_average=9.68,idle_summation=9151i,usage_average=5.403333333333333,used_summation=1081i,utilization_average=6.17 1626995640000000000
> vsphere_host_cpu,cpu=29,dcname=testname,esxhostname=1.1.1.1,host=Trunks-Dashboard,moid=host-9,source=1.1.1.1,vcenter=1.1.1.1 coreUtilization_average=9.396666666666667,idle_summation=9183i,usage_average=4.516666666666667,used_summation=904i,utilization_average=5.6 1626995640000000000
> vsphere_host_cpu,cpu=9,dcname=testname,esxhostname=1.1.1.1,host=Trunks-Dashboard,moid=host-9,source=1.1.1.1,vcenter=1.1.1.1 coreUtilization_average=1.84,idle_summation=9882i,usage_average=0.6466666666666666,used_summation=130i,utilization_average=1.0166666666666666 1626995640000000000
> vsphere_host_sys,dcname=testname,esxhostname=1.1.1.1,host=Trunks-Dashboard,moid=host-9,source=1.1.1.1,vcenter=1.1.1.1 uptime_latest=335196i 1626995640000000000



If I run test it seems to pull info from esxi, but no other way.

**Comment by srebhan** [comment]
@morgan9220 ok I changed the issue title myself. ;-)

Regarding your problem: The `--test` run shows that telegraf _collects_ the data correctly from the input side (you see the collected metrics). Do you agree? So the issue has to be on the output part... Do you see any error message? Can you post the influx configuration? Does the problem only happen with the `vSphere` plugin?

> Problem I'm having is not getting any info from telegraf into influx, telegraf keeps stopping the plugin.
>
> usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --once
2021-07-22T23:12:33Z I! Starting Telegraf 1.19.1
2021-07-22T23:12:33Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:33Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Starting plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [inputs.vsphere] Stopping plugin
2021-07-22T23:12:34Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-07-22T23:12:34Z I! [agent] Stopping running outputs

Hmmm what do you expect? You run with `--once`, therefore, telegraf starts the plugins (`[inputs.vsphere] Starting plugin` You seem to have configured three `inputs.vsphere`.), collects the metric **once** and then stop the plugins again (`[inputs.vsphere] Stopping plugin`). Afterwards it tries to flush the data to the outputs before exiting.
The strange thing is, that telegraf is **not** seeing any *output* plugin (you would see `[outputs.influxdb] Starting plugin`). Are you **sure** that you have an `influxdb output` configured?

**Comment by morgan9220** [comment]
Sorry for taking so long to reply, and I really appreciate your assistance. 



# Configuration for sending metrics to InfluxDB

[[outputs.influxdb]]

    urls = ["http://1.1.1.1:8086"]

    database = "vmWareStats"

    timeout = "0s"

    username = "influxuser"

    password = "influxuserpassword"

	

	

	# Read metrics from VMware vCenter

 [[inputs.vsphere]]

 ## List of vCenter URLs to be monitored. These three lines must be uncommented

 ## and edited for the plugin to work.

 vcenters = [ "https://1.1.1.1/sdk" ]

    username = "user"

    password = "password"

 #

 ## VMs

 ## Typical VM metrics (if omitted or empty, all metrics are collected)

 vm_metric_include = [

      "cpu.demand.average",

      "cpu.idle.summation",

      "cpu.latency.average",

      "cpu.readiness.average",

      "cpu.ready.summation",

      "cpu.run.summation",

      "cpu.usagemhz.average",

      "cpu.used.summation",

      "cpu.wait.summation",

      "mem.active.average",

      "mem.granted.average",

      "mem.latency.average",

      "mem.swapin.average",

      "mem.swapinRate.average",

      "mem.swapout.average",

      "mem.swapoutRate.average",

      "mem.usage.average",

      "mem.vmmemctl.average",

      "net.bytesRx.average",

      "net.bytesTx.average",

      "net.droppedRx.summation",

      "net.droppedTx.summation",

      "net.usage.average",

      "power.power.average",

      "virtualDisk.numberReadAveraged.average",

      "virtualDisk.numberWriteAveraged.average",

      "virtualDisk.read.average",

      "virtualDisk.readOIO.latest",

      "virtualDisk.throughput.usage.average",

      "virtualDisk.totalReadLatency.average",

      "virtualDisk.totalWriteLatency.average",

      "virtualDisk.write.average",

      "virtualDisk.writeOIO.latest",

      "sys.uptime.latest",

    ]

 # vm_metric_exclude = [] ## Nothing is excluded by default

 # vm_instances = true ## true by default

 #

 ## Hosts

 ## Typical host metrics (if omitted or empty, all metrics are collected)

 host_metric_include = [

      "cpu.coreUtilization.average",

      "cpu.costop.summation",

      "cpu.demand.average",

      "cpu.idle.summation",

      "cpu.latency.average",

      "cpu.readiness.average",

      "cpu.ready.summation",

      "cpu.swapwait.summation",

      "cpu.usage.average",

      "cpu.usagemhz.average",

      "cpu.used.summation",

      "cpu.utilization.average",

      "cpu.wait.summation",

      "disk.deviceReadLatency.average",

      "disk.deviceWriteLatency.average",

      "disk.kernelReadLatency.average",

      "disk.kernelWriteLatency.average",

      "disk.numberReadAveraged.average",

      "disk.numberWriteAveraged.average",

      "disk.read.average",

      "disk.totalReadLatency.average",

      "disk.totalWriteLatency.average",

      "disk.write.average",

      "mem.active.average",

      "mem.latency.average",

      "mem.state.latest",

      "mem.swapin.average",

      "mem.swapinRate.average",

      "mem.swapout.average",

      "mem.swapoutRate.average",

      "mem.totalCapacity.average",

      "mem.usage.average",

      "mem.vmmemctl.average",

      "net.bytesRx.average",

      "net.bytesTx.average",

      "net.droppedRx.summation",

      "net.droppedTx.summation",

      "net.errorsRx.summation",

      "net.errorsTx.summation",

      "net.usage.average",

      "power.power.average",

      "storageAdapter.numberReadAveraged.average",

      "storageAdapter.numberWriteAveraged.average",

      "storageAdapter.read.average",

      "storageAdapter.write.average",

      "sys.uptime.latest",

    ]

 # host_metric_exclude = [] ## Nothing excluded by default

 # host_instances = true ## true by default

 #

 ## Clusters

 cluster_metric_include = [] ## if omitted or empty, all metrics are collected

 # cluster_metric_exclude = [] ## Nothing excluded by default

 # cluster_instances = false ## false by default

 #

 ## Datastores

 datastore_metric_include = [] ## if omitted or empty, all metrics are collected

 # datastore_metric_exclude = [] ## Nothing excluded by default

 # datastore_instances = false ## false by default for Datastores only

 #

 ## Datacenters

 datacenter_metric_include = [] ## if omitted or empty, all metrics are collected

# datacenter_metric_exclude = [ "*" ] ## Datacenters are not collected by default.

 # datacenter_instances = false ## false by default for Datastores only

 #

 ## Plugin Settings

 ## separator character to use for measurement and field names (default: "_")

 # separator = "_"

 #

 ## number of objects to retreive per query for realtime resources (vms and hosts)

 ## set to 64 for vCenter 5.5 and 6.0 (default: 256)

 # max_query_objects = 256

 #

 ## number of metrics to retreive per query for non-realtime resources (clusters and datastores)

 ## set to 64 for vCenter 5.5 and 6.0 (default: 256)

 # max_query_metrics = 256

 #

 ## number of go routines to use for collection and discovery of objects and metrics

 # collect_concurrency = 1

 # discover_concurrency = 1

 #

 ## whether or not to force discovery of new objects on initial gather call before collecting metrics

 ## when true for large environments this may cause errors for time elapsed while collecting metrics

 ## when false (default) the first collection cycle may result in no or limited metrics while objects are discovered

 # force_discover_on_init = false

 #

 ## the interval before (re)discovering objects subject to metrics collection (default: 300s)

 # object_discovery_interval = "300s"

 #

 ## timeout applies to any of the api request made to vcenter

 # timeout = "60s"

 #

 ## Optional SSL Config

 # ssl_ca = "/path/to/cafile"

 # ssl_cert = "/path/to/certfile"

 # ssl_key = "/path/to/keyfile"

 ## Use SSL but skip chain & host verification

 insecure_skip_verify = true





influx -username influxuser -password influxuserpassword
Connected to http://localhost:8086 version 1.6.4
InfluxDB shell version: 1.6.4
> use vmWareStats
Using database vmWareStats
> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
processes
swap
system
vsphere_datacenter_vmop
vsphere_datastore_datastore
vsphere_datastore_disk
vsphere_host_cpu
vsphere_host_datastore
vsphere_host_disk
vsphere_host_hbr
vsphere_host_mem
vsphere_host_net
vsphere_host_power
vsphere_host_rescpu
vsphere_host_storageAdapter
vsphere_host_storagePath
vsphere_host_sys
vsphere_host_vflashModule
vsphere_vm_cpu
vsphere_vm_datastore
vsphere_vm_disk
vsphere_vm_mem
vsphere_vm_net
vsphere_vm_power
vsphere_vm_rescpu
vsphere_vm_sys
vsphere_vm_virtualDisk
>

**Comment by srebhan** [comment]
@morgan9220 next time, please attach the config as a file. Just pasting without using a pre-formatted section makes it really hard to read.

So from your `influx` query I see many `vsphere_*` measurements, so to me it seems like you are getting data into the database. What issue do you experience exactly? Your initial post made me believe you don't receive data on the database side...

**Comment by morgan9220** [comment]
Sorry for making it difficult to read. 

When I try to look in grafana to build any dashboards no info show up for esxi, it test successfully to influx.


Jul 27 18:43:55 Trunks-Dashboard systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: time="2021-07-27T18:43:55-04:00" level=error msg="failed to create cache directory. /etc/telegraf/.cache/snowflake, >
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: time="2021-07-27T18:43:55-04:00" level=error msg="failed to open. Ignored. open /etc/telegraf/.cache/snowflake/ocsp_>
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Starting Telegraf 1.19.1
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Loaded inputs: vsphere (3x)
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Loaded aggregators:
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Loaded processors:
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Loaded outputs: influxdb
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! Tags enabled: host=Trunks-Dashboard
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Trunks-Dashboard", Flush Interval:10s
Jul 27 18:43:55 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:55Z I! [inputs.vsphere] Starting plugin
Jul 27 18:43:56 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:56Z I! [inputs.vsphere] Starting plugin
Jul 27 18:43:56 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:43:56Z I! [inputs.vsphere] Starting plugin
Jul 27 18:44:08 Trunks-Dashboard systemd[1]: Stopping The plugin-driven server agent for reporting metrics into InfluxDB...
Jul 27 18:44:08 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:44:08Z I! [inputs.vsphere] Stopping plugin
Jul 27 18:44:08 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:44:08Z I! [inputs.vsphere] Stopping plugin
Jul 27 18:44:08 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:44:08Z I! [inputs.vsphere] Stopping plugin
Jul 27 18:44:08 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:44:08Z I! [agent] Hang on, flushing any cached metrics before shutdown
Jul 27 18:44:08 Trunks-Dashboard telegraf[18699]: 2021-07-27T22:44:08Z I! [agent] Stopping running outputs
Jul 27 18:44:08 Trunks-Dashboard systemd[1]: telegraf.service: Succeeded.
Jul 27 18:44:08 Trunks-Dashboard systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Jul 27 18:56:18 Trunks-Dashboard systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: time="2021-07-27T18:56:19-04:00" level=error msg="failed to create cache directory. /etc/telegraf/.cache/snowflake, >
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: time="2021-07-27T18:56:19-04:00" level=error msg="failed to open. Ignored. open /etc/telegraf/.cache/snowflake/ocsp_>
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Starting Telegraf 1.19.1
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Loaded inputs: vsphere (3x)
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Loaded aggregators:
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Loaded processors:
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Loaded outputs: influxdb
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! Tags enabled: host=Trunks-Dashboard
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"Trunks-Dashboard", Flush Interval:10s
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! [inputs.vsphere] Starting plugin
Jul 27 18:56:19 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:19Z I! [inputs.vsphere] Starting plugin
Jul 27 18:56:20 Trunks-Dashboard telegraf[18762]: 2021-07-27T22:56:20Z I! [inputs.vsphere] Starting plugin

**Comment by srebhan** [comment]
Why is telegraf started and stopped so often? Maybe it could not collect the metrics in the meantime?

**Comment by morgan9220** [comment]
Not sure why it stopped, but after running since then:
Jul 28 18:55:15 Trunks-Dashboard telegraf[18762]: 2021-07-28T22:55:15Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: points beyond retentiuxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: points beyond retention policy dropped=2

**Comment by srebhan** [comment]
As the error message states, the metrics you are writing will be deleted instantaneously by InfluxDB as they are older than what the retention policy (`retentiuxdb`) will keep. That's also the reason why you likely don't see any metric in the database. Please check how long you keep the metrics in the database by checking how long your `retentiuxdb` retention policy will keep data.

**Comment by morgan9220** [comment]
[agent] ["outputs.influxdb"] did not complete within its flush interval
I'm getting that now. I appreciate all of your help!

**Comment by srebhan** [comment]
@morgan9220 this indicates that the write could not be completed within the write interval. Without more information it's hard to guess _why_ that happens...
