### ISSUE TITLE
SQLServer Plugin: Throwing Errors when HADR DB Not Readable

### ISSUE THREAD

**Issue by simonwhybrow** [influxdata/telegraf#9530]
### Relevant telegraf.conf:
```toml
[[inputs.sqlserver]]
  servers = ["Server=xxxxxxxxxxx;Port=1433",]

  exclude_query = []

  database_type = "SQLServer"
```

### System info:
All Windows versions
Telegraf version 1.18.0

### Steps to reproduce:
Setup the sqlserver input plugin to collect data against a SQL Server instance that is hosting secondary databases in an AlwaysOn Availability group. These databases aren't configured for read-only access.

No queries are excluded from the sqlserver input plugin.

### Expected behavior:

No errors to be thrown

### Actual behavior:

The below errors are thrown as the database can't be queried:

[inputs.sqlserver] Error in plugin: Script SQLServerRequests failed: mssql: The target database, 'xxxxxxxxxx', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

[inputs.sqlserver] Error in plugin: mssql: The target database, 'xxxxxxxxxx', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

**Comment by srebhan** [comment]
@masree do you have any comment on this?

**Comment by masree** [comment]
@denzilribeiro / @[dimitri](https://github.com/dimitri-furman) : SQLServerRequests queries are throwing errors only for SQL Server instance that is hosting secondary databases in an AlwaysOn Availability group. And these databases aren't configured for read-only access. DMV queried for SQLServerRequests namespace are dm_exec_requests  and dm_exec_sessions. Is the above error expected or do we need to add any filter before executing SQLServerRequests? Can you help share insights?

**Comment by denzilribeiro** [comment]
@simonwhybrow  what is your connection string? are you connecting to the DB or master?

**Comment by denzilribeiro** [comment]
So do you get the same error if you run the sql requests query logging on via SSMS? Are you sure the default login is master?
https://github.com/influxdata/telegraf/blob/1872037eb759d5ca82506592e53bd0d2c3df28d8/plugins/inputs/sqlserver/sqlserverqueries.go#L1023

**Comment by simonwhybrow** [comment]
Running the sql requests query via ssms works fine. In fact I tested all of them and they work fine.

Just to show the configuration I have set up..

The service is configured as below:
![image](https://user-images.githubusercontent.com/55552369/128140336-aca35988-a45b-4bad-ba44-1e5babdd18a3.png)

The telegraf.conf contains the below:
![image](https://user-images.githubusercontent.com/55552369/128140606-bac23d66-b4e4-450b-baae-e9efc5099f60.png)

And the default database is master:
![image](https://user-images.githubusercontent.com/55552369/128140784-9cb150ec-0484-47db-93dd-e380f69896dc.png)

I have even changed the connection string in the telegraf.conf to include "database=master" and that still caused the error to occur.

It's very confusing as running the queries through ssms works fine, but for some reason the telegraf connection doesn't always honour the default database setting, It's not consistent either, so most collections are fine, but one every 2-3 minutes fails.
Could this be an issue with the go-mssqldb driver?

**Comment by denzilribeiro** [comment]
You could try auditing/Xevents to see what login comes as when it fails what auth context is using and what DB connects to. We shouldn't block this query from running on the secondary as it is useful for sure. I would definitely specify the database in connection string - does this happen with only a windows login? Can you repro this with simple golang app with windows auth? https://stackoverflow.com/questions/48310201/how-to-connect-to-sql-server-using-windows-auth

**Comment by simonwhybrow** [comment]
Sorry for the delay in replying to this - been away and caught up in other projects.
However, I've had time to get in to testing today...
I've set up Xevents to capture the login from the telegraf account and the error that occurs.

I have trie sql logins vs windows auth, including the "database" option in the connection string and not including it, running telegraf as a service and running from the command line. Which ever configuration I use the error will always occur.
I can see that the session used for the login comes in to master every time then for some reason on _some_ occasions it runs the query against a database other than master.

I have also set up a very simple golang app to make a connection to the database. This uses either windows auth or a sql login (both accounts have their default database set to master) and this consistently connects to the master database - I get the connection to run a query and return the DB it's run in.

I'm at a bit of a loss as to why this error is occurring with the telegraf connection though.

**Comment by deweter** [comment]
Today I did some testing and it is a bug inside SQL Server itself. 

Repro is just as easy as running SELECT * FROM sys.dm_exec_requests via stress tool against secondary replica (I used SQLQueryStress in this case):
![image](https://user-images.githubusercontent.com/13314610/211033848-386f9de0-c5a5-445a-94c2-a5e6f119deb9.png)

![image](https://user-images.githubusercontent.com/13314610/211034048-9abfad11-941d-4ed6-ac67-a0d2052949bb.png)

Full error msg:
`The target database, '', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.
`

Changing application intent to read-only is not helping either.

**Comment by powersj** [comment]
@deweter thank you for the offer! I would need to defer to @Trovalo or the others with more sql knowledge. Filtering out this error to work around a SQL server issue, while not ideal, does seem like a nice improvement.

I'll add this to our maintainers chat for next week if no one responds before then.

**Comment by deweter** [comment]
The try catch fix would check for a specific error code 976 (please, see the example). 

I believe, there is no real reason, why this specific error should be raised, when we are asking just for a requests' output => no "genuine errors" could be really lost.

Our current log was full of these errors in our environment (we monitor dozens of instances with AOAG). The fix I suggested helped to hide them (I have implemented this fix in my custom build already).

**Comment by Trovalo** [comment]
Sorry about the wait.
My point is that if someone actually queries a `replica not enabled for read access` that error is genuine.
Is it an important/relevant error? I can't tell for sure (as I've no experience in availability groups) but it doesn't seem essential or critical. I've nothing against suppressing it to avoid log flooding

**Comment by srebhan** [comment]
After thinking a bit about this, how about just logging this once or every X encounters instead of try-catch the error. This would prevent log-flooding but also leaves a trail in the log-files. What do you guys think?

**Comment by deweter** [comment]
I should probably explain it better. The query which is failing is a select to a DMV [sys.dm_exec_requests](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-ver16). It normally returns a set of running queries. This DMV should never return this error as it is never part of AOAG (see [point 1](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-ver15#RequirementsDb)). It is true even for [contained availability groups](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16), which are new in SQL Server 2022.

Another explanation could be. When the error is:
`The target database, '', is participating in an availability group and is currently not accessible for queries`

If there is a database which is not accessible for queries - no queries from that database should be shown (= we should not get the error)
If there is a database which is accessible for queries - a query should be shown (and we should not get this error as the database must be queryable).

_It is just a guess, but what is most likely happening in the background of this DMV, is that there are some internal checks for additional details about some internal process (I am getting this error on standard edition too - despite the fact, that it does not support readable replicas at all) and this check is not handled properly for AOAG nonreadable databases._

The solution which @srebhan suggests is ok for me, but I don't think that count of failures for individual queries is persisted at this moment. It needs code changes inside "plugin" logic. Try catch is handled inside SQL Server query only and has no impact on other queries.

**Comment by Trovalo** [comment]
As @deweter said _logging this once or every X encounters_ requires persisting data, which is something we don't want to do in SQL Server ofc, but I doubt we want to do that even inside the plugin.

Now that I got a better context for the error I agree with @deweter about completely suppressing the error and doing so in TSQL itself

**Comment by srebhan** [comment]
Ok if you guys agree it's fine with me as long as there is no instance where this error should arrive at the user i.e. where it is a valid error to report. :-)

**Comment by parvez-cet21** [comment]
Re: https://github.com/influxdata/telegraf/issues/9530#issuecomment-1373736605

I have a configuration like this and I want to run a custom query on SQL Server to fetch data from the test table into Postgresql Database. 
`

# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  metric_buffer_limit = 10000


  collection_jitter = "0s"


  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"

  ## Override default hostname, if empty use os.Hostname()
  hostname = "52.146.17.139"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false



# Publishes metrics to a postgresql database
[[outputs.postgresql]]
  connection = "postgres://test:XXXX@localhost/telegraf?sslmode=disable"

  ## Postgres schema to use.
  schema = "public"


  ## Templated statements to execute when creating a new table.
  create_templates = [
      '''CREATE TABLE {{ .table }} ({{ .columns }})''',
  ]
  add_column_templates = [
      '''ALTER TABLE {{ .table }} ADD COLUMN IF NOT EXISTS {{ .columns|join ", ADD COLUMN IF NOT EXISTS " }}''',
  ]
  tag_table_add_column_templates = [
      '''ALTER TABLE {{.table}} ADD COLUMN IF NOT EXISTS {{.columns|join ", ADD COLUMN IF NOT EXISTS "}}''',
  ]


###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################


# Read metrics from Microsoft SQL Server
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings.
  servers = [
     "Server=192.168.1.10;Port=1433;Database=master;User Id=SA;Password=XXXXX;app name=telegraf;log=1;",
  ]

  ## 0 value means no timeout
  # query_timeout = "0s"

  ## valid methods: "connection_string", "AAD"
  # auth_method = "connection_string"

  ## Possible values for database_type are - "SQLServer" or "AzureSQLDB" or "AzureSQLManagedInstance" or "AzureSQLPool"
  database_type = "SQLServer"

  ## A list of queries to include. If not specified, all the below listed queries are used.
  include_query = []
    
  ## A list of queries to explicitly ignore.
  exclude_query = ["SQLServerAvailabilityReplicaStates", "SQLServerDatabaseReplicaStates","SQLServerSchedulers", "SQLServerRecentBackups", "SQLServerDatabaseIO", "SQLServerMemoryClerks", "SQLServerProperties", "SQLServerRequests", "SQLServerVolumeSpace", "SQLServerCpu", "SQLServerPerformanceCounters", "SQLServerWaitStatsCategorized"]
  ## Version 2 - is compatible from SQL Server 2012 and later versions and also for SQL Azure DB
  # query_version = 2

`

**Comment by srebhan** [comment]
@parvez-cet21 I cannot see how this is related to this issue. Please open a new issue instead of commenting on this one!
