### ISSUE TITLE
use absolute path to sensors command in sensors plugin 

### ISSUE THREAD

**Issue by dthpulse** [influxdata/telegraf#9533]
Hello

telegraf user may have not access to env. variable $PATH on all systems. 

It would be really more efficient to use absolute path to `sensors` command instead by just calling the command itself and relay on env. variable $PATH

Then there wouldn't be needed to use this slice of code:

```
	if len(s.path) == 0 {
		return errors.New("sensors not found: verify that lm-sensors package is installed and that sensors is in your PATH")
	}
```

and code will get more professional look.

thx!

**Comment by powersj** [comment]
Please see my comment on the PR.

Next steps: resolve the PR
