### ISSUE TITLE
Consider to add support for chassis data for ipmi_sensor

### ISSUE THREAD

**Issue by espenfl** [influxdata/telegraf#9548]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Add support for also extracting info from `chassis status` for `ipmi_sensor`.

### Current behavior:

Not supported.

### Desired behavior:

Supported.

### Use case: 

To get e.g. power state, failures etc. Also, `selftest` status can also be queried for additional details.

**Comment by reimda** [comment]
The ipmi_sensor plugin uses the ipmitool program. I think the next step for this is to figure out how to get the information you want from ipmitool directly, then we can look into adding it to the plugin.

Have you used ipmitool to get chassis info? Do you already have a command line that grabs the info you want?

**Comment by powersj** [comment]
@espenfl,

Are you still interested in this feature? If so, could you get us answers to these questions:

> Have you used ipmitool to get chassis info?
> Do you already have a command line that grabs the info you want?

Thanks!
