### ISSUE TITLE
Build: Reduce Binary Size by excluding Plugins

### ISSUE THREAD

**Issue by JonnyTischbein** [influxdata/telegraf#9556]
Hi, 
I'm trying to build small telegraf binary versions for using them on embeded systems like routers with only less memory.

Because I didn't found a way in the [Makefile](https://github.com/influxdata/telegraf/blob/master/Makefile) to exclude plugins, I uncomment them in `plugins/{input,output}/all/all.go`.
I managed to reduce size to 75MB. 
Than I started to look at `plugins/processors/all/all.go` but wasn't sure what is safe to exclude here.

My questions are:
- Is that desired way to exlcude plugins or is there another (better) one ?
- Do you know any other things that can be left out safely ?

Thanks in advance!

**Comment by sspaink** [comment]
As you noticed, there isn't a way to build Telegraf with a subset of plugins with the makefile at the moment. I do think this would be a good feature to have so I've added the `feature request` label to this issue to research how we'd want to do this.

Commenting out the plugins as you did in the `all.go` files seems like a good approach in the meantime. Be sure to build without the debug symbols as well by passing the following flag `-ldflags "-s -w"`, should help reduce the size if you haven't already. I don't have any other suggestions what could be excluded safely at the moment.

**Comment by JonnyTischbein** [comment]
Thanks for your reply! I managed to further reduce the size to 34M and 16M without any plugins. It is still too much but I guess there is nothing else I can do now.

**Comment by russorat** [comment]
do you mind sharing what device you are trying to load telegraf on?

**Comment by JonnyTischbein** [comment]
I'm developing currently on the raspberry pi 3 model B, where I do not have any memory restrictions, but I would love to run telegraf on our other routers, which are mostly [TP-Link Archer C7 AC1750 v2](https://openwrt.org/toh/tp-link/archer_c7#hardware_highlights) with about 16M flash memory.
I guess we still have some TP-Link WDR3600 with only 8M, but I guess that will never be possible.

Btw. I found the tool upx and could achieve a 6M binary (with excluded debug symbols and plugins), but it might not be possible with the compressed squashfs. I will need to test that. I linked some sources in the [openwrt forum](https://forum.openwrt.org/t/package-makefile-compress-binary-with-upx/102595/6) if you are interessted.

**Comment by phemmer** [comment]
#9615 is similar to this one

See also #9649, which is a proposal for a new external plugin API which would allow externalizing all these built-in plugins.

**Comment by wz2b** [comment]
In addition to code space they also contribute to more stuff in the sample configuration file.  That's lines of text 99% of people don't need so IMO it's just noise. I think that's another reason to migrate these out by externalizing them over time.  If you decide that it isn't worth doing this right now that's probably fine, but if there are any changes to these seldom-used plugins then encouraging them to go external is something I definitely support.
