### ISSUE TITLE
Add support change metric name in plugins/processors/regex

### ISSUE THREAD

**Issue by ihard** [influxdata/telegraf#9557]
Please add the ability to change the name of the metric using the plugins/processors/regex.
Perhaps this is implemented in some other way (plugin), but could not be found.
Case - mass renaming of incoming metrics using regular expressions.

**Comment by srebhan** [comment]
Related to #5159.

**Comment by srebhan** [comment]
@ihard can you please check if #9561 is what you had in mind? You can use the [artifacts built by CI](https://github.com/influxdata/telegraf/pull/9561#issuecomment-889909005) (click the small black triangle). If you encounter any problem, please let me know.

**Comment by ihard** [comment]
@srebhan Yes, that's what you need!
