### ISSUE TITLE
how to use inuts.http plugin for the http APIs which return XML data

### ISSUE THREAD

**Issue by pavannayakanti** [influxdata/telegraf#9572]
Hello Support Team,

Am using **[[inputs.http]]** to fetch the outcome from a REST API.
However, am the REST API is is returning xml data instead of json.
am using `data_format = "xml"`, but it doesn't works though. Just wondering if this plugin works for xml. 

```
[root@h0012345 naypavk]# telegraf --config /home/naypavk/src/telegraf/mutedtests.conf -test
2021-08-02T15:51:17Z I! Starting Telegraf 1.19.1
2021-08-02T15:51:17Z D! [agent] Initializing plugins
2021-08-02T15:51:17Z D! [agent] Starting service inputs
2021-08-02T15:51:17Z D! [agent] Stopping service inputs
2021-08-02T15:51:17Z D! [agent] Input channel closed
2021-08-02T15:51:17Z D! [agent] Stopped Successfully
```
Do we have alternative plugin/method to entertain the http APIs which return xml data. Please advise.

**Comment by srebhan** [comment]
Hmmm did you configure the XML parser? There is an example in the [documentation](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath)... If you do not specify _what_ should be parsed, there will be no output.

**Comment by sjwang90** [comment]
Closing this issue as we reserve Telegraf issues for bugs for reproducible problems.  Please reach out to us in our [Community Slack](influxdata.com/slack) or [Community Page](https://community.influxdata.com/) and we can get this question answered quickly.
