### ISSUE TITLE
Add Support Kusto Azure Synapse Workspace 

### ISSUE THREAD

**Issue by yogilad** [influxdata/telegraf#9580]
The recently added Kusto plugin is using version 0.3.2 of azure-kusto-go SDK.
This version is not able to authenticate to Kusto clusters inside Synapse Workspaces, due to some URI incompatibility which is fixed in v0.3.3.

Can you please update Telegraf to take v0.3.3 of Kusto SDK?

Thanks!
Yochai

**Comment by reimda** [comment]
The azure-kusto-go module has been updated to v0.6.0. It sounds like telegraf should have the URI fix you're looking for.
