### ISSUE TITLE
OPCUA Input: client should be set to nil after closing

### ISSUE THREAD

**Issue by milgner** [influxdata/telegraf#9582]
Bug in the `opcua` input:

In [`disconnect`](https://github.com/influxdata/telegraf/blob/de01d37a36288fd1688797ec50a5f58a578dab76/plugins/inputs/opcua/opcua_client.go#L507), the connection is closed which leads to `Connect` being invoked on the next `Gather` cycle which in turn finds tries to invoke [`CloseSession`](https://github.com/influxdata/telegraf/blob/de01d37a36288fd1688797ec50a5f58a578dab76/plugins/inputs/opcua/opcua_client.go#L409) on an already-closed connection.

This results in the looped error output which cannot be recovered from:
> Error in plugin: opcua: sechan: secure channel not open.

We'll test out adding `client = nil` and create a merge request if that turns out to fix the issue.

**Comment by srebhan** [comment]
This seems related to the problem arising in #9551...
