### ISSUE TITLE
Mention the Ubuntu telegraf package in the documentation

### ISSUE THREAD

**Issue by sergiodj** [influxdata/telegraf#9589]
Hi there,

Ubuntu has offered a `telegraf` package for its users for a few releases now (see https://launchpad.net/ubuntu/+source/telegraf), so I would like to request that it be listed in the official documentation if possible.

I didn't know what would be proper type for this issue so I chose "Feature request"; I hope that's OK.

Thanks in advance!

**Comment by pierwill** [comment]
Thanks, @sergiodj! We'll add this to our docs here: https://docs.influxdata.com/telegraf/v1.19/introduction/installation/.

What's the earliest Ubuntu version with the telegraf package?

**Comment by sergiodj** [comment]
Thanks, @pierwill!

The earlier Ubuntu version with telegraf is Hirsute.

Cheers.

**Comment by pierwill** [comment]
Closed in https://github.com/influxdata/docs-v2/pull/3025.
