### ISSUE TITLE
gNMI Input : GPB compact / protobuf support

### ISSUE THREAD

**Issue by EricRemote** [influxdata/telegraf#9590]
## Feature Request
It would be interesting to add the support of GPB compact (as "opposed" to KV / key-value) to the gNMI plugin. There is a similar request ([#7172](https://github.com/influxdata/telegraf/issues/7172)) for the cisco_telemetry_mdt plugin.

### Proposal:
Add support of GPB to the gNMI plugin. The project "gNMIc" (for Nokia SR OS) does it : you can specify an "external" (not compiled) proto file to decode the GPB compact packets.

### Current behavior:
Not handling GPB compact / proto files

### Desired behavior:
Handling GPB compact / proto files **OR** at least change the documentation of the gNMI plugin. At the moment it's not clear and says that you can specify "proto" as an encoding but 1) crashes when I do 2) doesn't look like it's handled in the code (as there is no option to specify a proto file to decode the GPB packet).

### Use case: 
GPB compact is way smaller than GPB-KV (key/value) and/or JSON. It would allow us to minimize traffic for collecting metrics. Instead of receiving 40-80Mb on metrics per collection/push it will be more like 5-20Mb.

**Comment by reimda** [comment]
Is this still happening in recent builds? Could you provide reproduction steps for the crash?

You mentioned taking a look in the code. Are you able to work on this and provide a PR that implements GPB compact?

**Comment by EricRemote** [comment]
Hello, it is not a crash, there is just no option to specify a proto file to decode the GPB-compact data.

I'm not a dev, I can just barely decipher this Go module, but reading the code + comments it still seems that GPB compact is not supported.

**Comment by srebhan** [comment]
@EricRemote any news on this issue? Does it still crash?

**Comment by EricRemote** [comment]
@srebhan hello Sven, sorry but in the meantime I changed company and I'm not able to test anymore :(

**Comment by srebhan** [comment]
@EricRemote no worries and thanks for the quick response!

Will close this for now. If anybody comes across this and the issue still persists, please reopen this issue or create a new one!
