### ISSUE TITLE
Get English performance counters on different languages

### ISSUE THREAD

**Issue by wp-davga** [influxdata/telegraf#9593]
Hello Support,

we upgraded our telegraf to 1.19.2 but we are having issues getting perfcounters in english on non-english systems

it's critical for us to use UseWildcardExpansion but if we use it all the metrics arrive in the system's local language, not in english.
We would like to be able to use UseWildcardExpansion but also get the metrics (e.g. Process, CPU, etc.) in english and not in the local language. Is it possible to archive both?

We searched in the closed tickets but it's not clear how we can manage that. The last issue about this problem was handled in 2018

Thanks for your time.

Regards

**Comment by helenosheaa** [comment]
Removing the support label based on [this](https://influxcommunity.slack.com/archives/CH99HUH8V/p1628176600063400) slack thread as I think it requires more investigation.

**Comment by wp-davga** [comment]
opened a ticket with the support: 00099719
still in investigation

**Comment by powersj** [comment]
Hi,

I believe this was resolved with PR #10101. If not, please feel free to re-open.

Thanks!
