### ISSUE TITLE
HTTP Response Input: Support pre-request script to add dynamic headers.

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#9596]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior: Currently, the headers are hard-coded in configurations

```conf
  # HTTP Request Headers (all values must be strings)
    [inputs.http_response.headers]
      Signature = "MySignature"
```

### Desired behavior: Use scripts(not necessarily JS) to calculate headers in runtime.

```conf
  # Pre-request Scripts
    [inputs.http_response]
      scripts = "timestamp = (Date.now()/1000).toFixed()"

  # Export the variable to environment variable
    [inputs.http_response.script_set_env]
      TIMESTAMP= "timestamp"

  # HTTP Request Headers
  # Reference environment variable using ${TIMESTAMP} notation
    [inputs.http_response.headers]
      x-timestamp = "${TIMESTAMP}"
```

### Use case: 

Some HTTP request needs pre-scripts to generate signatures or tokens in headers. This feature will enable this plugin to support this use case.

**Comment by reimda** [comment]
It looks like #9897 has stalled and been closed, so I'm closing the issue
