### ISSUE TITLE
Capture /proc/schedstat CPU metrics

### ISSUE THREAD

**Issue by mkrysiak** [influxdata/telegraf#9603]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Augment the existing CPU plugin, or develop a new plugin, that captures metrics from /proc/schedstat on Linux.  In particular, the time a CPU spent running a process, and the time spent by processes waiting to run on a CPU are useful metrics.

### Current behavior:

The data is not captured.

### Desired behavior:

Two new metrics are captured per core, CPU time spent running a process and time processes wait to run on a CPU.

### Use case: 

The amount of time a process spends waiting to run on a CPU is a more meaningful metric than CPU utilization or load average when trying to understand the latency within a system.

**Comment by powersj** [comment]
Hi,

Sorry no one has not gotten back to you yet.

Would your request be resolved with the use of the `procstat` input plugin? That shows process-specific CPU information which seems to fit your use case. Although your desired behavior is specific to CPU measurements.

Let us know, thanks!
