### ISSUE TITLE
Rpm install

### ISSUE THREAD

**Issue by guenneguezt** [influxdata/telegraf#9613]
When you install telegraf-1.17.3-1.x86_64.rpm with the "--prefix" option the install doesn't complete.
There is error on copy telegraf.service which isn't in /usr/lib/telegraf/scripts/telegraf.service.

If we copy the good telegraf.service file we must change the ExecStart.

Thanks
Thomas

**Comment by powersj** [comment]
Hi,

My understanding of `--prefix` is it added the given prefix to the install path to "relocate" where files are installed. Not all packages enable this feature either.

Given the RPM has specific log and config files and systemd service settings, I am not sure we would even want to try to support the ability to relocate telegraf.

Thoughts?

Thanks
