### ISSUE TITLE
[inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])

### ISSUE THREAD

**Issue by andrema2** [influxdata/telegraf#9614]
Trying to get unbound plug in to work is getting this error

[inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])

### Relevant telegraf.conf:
[[inputs.unbound]]
   binary = "/usr/local/sbin/unbound-control"
   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true

### System info:
OPNSense 27.1.1
FreeBSD 12.1
Telegraf 1.19.0

### Expected behavior:
If I ran the telegraf test command it runs fine. 

### Actual behavior:
[inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])

I tried to point to different unbound.conf files witht the same error and also created a symlink to the default file, same problem. 

I added the telegraf user to unbound and wheel group but the issue persists

**Comment by powersj** [comment]
Hi,

> If I ran the telegraf test command it runs fine.

What are you doing differently when you remove `--test`? It sounds like a possible permissions issue, but it would be good to know how you are running telegraf without the `--test` option.

Thanks!
