### ISSUE TITLE
Page for xml parsers is not working

### ISSUE THREAD

**Issue by pavannayakanti** [influxdata/telegraf#9631]
Hello Support,

below page seems to be broken. please advise.
https://github.com/influxdata/telegraf/blob/master/plugins/parsers/xml

**Comment by sjwang90** [comment]
It's now a more general xpath plugin: https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath

Where were you originally directed to from this link? We'll make sure we get it fixed there.

**Comment by pavannayakanti** [comment]
here the link for XML among the list at - https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
