### ISSUE TITLE
Some questions about Telegraf 

### ISSUE THREAD

**Issue by rightlef** [influxdata/telegraf#9643]
Could anyone tell me how to select the batch size in telegraf-1.19.2? I'd like to store datas into influxdb as few as they can in one time.

**Comment by MyaLongmire** [comment]
the agent in the config file has `metric_batch_size` as an option. It has Telegraf send metrics to outputs in batches of at most metric_batch_size metrics. This controls the size of writes that Telegraf sends to output plugins.

Is that what you are looking for?

**Comment by rightlef** [comment]
> 配置文件中的代理`metric_batch_size`作为一个选项。它让 Telegraf 将指标以最多 metric_batch_size 指标的批量发送到输出。这控制 Telegraf 发送到输出插件的写入大小。
> 
> 这就是你要找的吗？

yes，and I want to know how to change the capacity of the metric_batch_size？I cannot find the option in the telegraf.conf.Thanks a lot.

**Comment by rightlef** [comment]
> > 配置文件中的代理`metric_batch_size`作为一个。它让 Telegraf 将指标以最大限度的度量_batch_size 指标的选项细节发送到输出。这控制 Telegraf 发送到输出插件的大小。
> > 这就是你要找的吗？
> 
> 是的，我想知道如何更改metric_batch_size的容量？我在telegraf.conf中找不到该选项。非常感谢。

oh，I found it，thanks again😘

**Comment by MyaLongmire** [comment]
Happy to help :)
