### ISSUE TITLE
Capture `drop_unroutable` RabbitMQ metric

### ISSUE THREAD

**Issue by d-mankowski-samsung** [influxdata/telegraf#9648]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Capture `drop_unroutable` metric from RabbitMQ's API. It should be only a minor change, since the similar metric - `return_unroutable` - is already implemented. This metric was added in 3.8.0 version of RabbitMQ.

### Current behavior:

Metric is not captured.

### Desired behavior:

Metric is captured.

### Use case: 

Calculate a number and ratio of dropped unroutable messages.

**Comment by sspaink** [comment]
Sorry you haven't received a response in a while, are you still interested in having this metric added to the rabbitmq plugin?
Are you perhaps interested in creating a pull request to add this feature? Do you have any documentation you could share about this API endpoint?
