### ISSUE TITLE
collectd input for telegraf?

### ISSUE THREAD

**Issue by tusharsonawanes** [influxdata/telegraf#9666]
Hello,

Since I couldn't find a solution to the issue mentioned below, listing it here

Issue name: Collectd as input for telegraf

What we want to achieve

1. Collect system metrics [RAM, CPU] using collected
2. Send this data to influxdb [latest version]

Overviewing the article below, it can be understood that, for collectd to send data to influxdb, we need to send it through telegraf

https://docs.influxdata.com/telegraf/v1.19/data_formats/input/collectd/

Somehow we are unable to configure the same. 

Do we have any reference quide, sample telegraf/ collectd.conf to achieve this?

**Comment by srebhan** [comment]
@tusharsonawanes did you try the [example configuration](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/collectd#configuration)? What errors do you get?

**Comment by tusharsonawanes** [comment]
Hi @srebhan 

correct me if I am wrong. This is my scenario

1. Ubuntu Virtual Machine ( Installed collectd - apt install collectd )
2. Docker containers for InfluxDB and Telegraf
3. Now, referring to the link you shared above, should I just add the configuration mentioned there to telegraf.conf?

If yes, what are the additional things I need to add/ configure in it?
