### ISSUE TITLE
add tags to each input only within configuration file

### ISSUE THREAD

**Issue by SorryGames** [influxdata/telegraf#9667]
Good day! 

It will be a good feature to implement tags are used only within one configuration file.
We have some configuration files. Each file describes **inputs** for specific Network Device:
```
telegraf.d/
--- cisco_prod.conf
--- cisco_lab.conf
--- fortigate_edge.conf
telegraf.conf
```

I want to add the same tag to the all inputs within **.conf** file. 
What do you think about it? Some kind of feature like `[[config.tags]]`?

**Comment by srebhan** [comment]
Unfortunately that's not how the TOML parser works. I fear you'll have to duplicate your `tags` section for each plugin within the config file...

**Comment by SorryGames** [comment]
thank you for reply.
It's pity to hear. No way, that's time for automation tools...

**Comment by srebhan** [comment]
@SorryGames having the same issue, I'm generating my config files from an underlying database... ;-)
