### ISSUE TITLE
Improvings for buffer logging

### ISSUE THREAD

**Issue by abra7134** [influxdata/telegraf#967]
Hello!
Here standard output of the collector of metrics:

> Starting Telegraf (version 0.12.0)
> Loaded outputs: influxdb file
> Loaded inputs: processes swap system cpu disk diskio mem
> Tags enabled: host=localhost
> Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"ssl1.www.gootax.pro", Flush Interval:10s 
> Gathered metrics, (10s interval), from 7 inputs in 11.283118ms
> Wrote 10 metrics to output file in 13.644µs
> Gathered metrics, (10s interval), from 7 inputs in 11.283118ms
> Database creation failed: Get http://localhost:8086/query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22telegraf%22: dial tcp [::1]:8096: getsockopt: connection refused
> Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
> ERROR writing full metric buffer to output influxdb, Could not write to any InfluxDB server in cluster
> Wrote 10 metrics to output influxdb in 139.644µs

I suggest to add the following information (it is highlighted in bold):

> Agent Config: Interval:10s, **Buffer:1000metrics,** Debug:false, Quiet:false, Hostname:"ssl1.www.gootax.pro", Flush Interval:10s 
> Gathered **10** metrics **to buffers (total - influxdb:10, file:10 / remained - influxdb:990, file:990)**, (10s interval), from 7 inputs in 11.283118ms
> Gathered **10** metrics **to buffers (total - influxdb:20, file:10 / remained - influxdb:980, file:990)**, (10s interval), from 7 inputs in 11.283118ms
> ERROR writing full metric buffer **(1000 metrics)** to output **[**influxdb**]**, Could not write to any InfluxDB server in cluster. **All metrics have been DESTROYED.**
> Wrote 10 metrics **from buffer** to output **[**influxdb**]** in 139.644µs

My offer is directed better to understand what happens to the buffer during inaccessibility of the server of metrics to estimate time before his overflow.
In addition I suggest to enter counters for statistics (from last start) and to periodically place them in output:

> **Statistics: Total gathered:10345 metrics, Buffers overflows:0 times, Max buffers usage:768 of 1000 metrics, Total lost:1345 metrics.**

**Comment by sparrc** [comment]
@abra7134 I'm currently working on a PR to refactor buffer handling that will include this #1096
