### ISSUE TITLE
Aug 25 16:57:26 monitor telegraf[3065570]: 2021-08-25T11:57:26Z E! [inputs.ipmi_sensor] Error in plugin: failed to run command sudo -n /usr/bin/ipmitool -H 192.168.1.1 -U Administrator -P mypassword -I lanplus sdr elist: Command timed out. - Error: Unable to establish IPMI v2 / RMCP+ session

### ISSUE THREAD

**Issue by concept-trainer** [influxdata/telegraf#9680]
Hi
I am getting this issue as attached logs to get help on this. please read the below errors and advise what is the issue with this.

Aug 25 16:57:26 monitor telegraf[3065570]: 2021-08-25T11:57:26Z E! [inputs.ipmi_sensor] Error in plugin: failed to run command sudo -n /usr/bin/ipmitool -H 192.168.1.1 -U Administrator -P mypassword -I lanplus sdr elist: Command timed out. - Error: Unable to establish IPMI v2 / RMCP+ session

**Comment by concept-trainer** [comment]
2021-08-25T12:12:14Z E! [inputs.ipmi_sensor] Error in plugin: failed to run command sudo -n /usr/bin/ipmitool -H

**Comment by concept-trainer** [comment]
but my issue is still persist no anyone tried to respond here. i dont know why people doing this if they are not willing to help then what is the reason to use this channel.

**Comment by stone-98** [comment]
I have this problem too, I don't understand.
