### ISSUE TITLE
telegraf_windows.conf is missing at least 2 plugins

### ISSUE THREAD

**Issue by TCL735** [influxdata/telegraf#9681]
`telegraf_windows.conf` located here: https://github.com/influxdata/telegraf/blob/master/etc/telegraf_windows.conf is missing the following plugins. Please add them.

- [ ] `win_eventlog` which exists at https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_eventlog but not in telegraf_windows.conf
- [ ] `win_services` which exists at https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_services but not in telegraf_windows.conf

**Comment by reimda** [comment]
Hi Timmy, we don't have an automated process that updates telegraf_windows.conf yet. We're working on it in https://github.com/influxdata/telegraf/pull/9684.

I expect to have this updated manually for the 1.20.0 release. The missing sections were added in the 1.20.0-rc0 release to etc/telegraf.conf by mistake. For the final release they'll be moved to etc/telegraf_windows.conf.

You can also generate a complete up-to-date sample config on any windows machine by running `telegraf config > telegraf_windows.conf`
