### ISSUE TITLE
collect bond traffic error 

### ISSUE THREAD

**Issue by jaywayjayway** [influxdata/telegraf#9682]
### Relevant telegraf.conf:

```toml


[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

```

### System info:

2.6.32-642.11.1.el6.x86_64

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

increasing   by time  `net_bytes_recv` in `[[inputs.net]]`

### Actual behavior:
In prometheus like this:

```
0:Array[1629945075,52156762419119]
1:Array[1629945090,52156762419119]
2:Array[1629945105,52156763067542]
3:Array[1629945120,52156763067542]
4:Array[1629945135,52156819036574]   //ERR
5:Array[1629945150,52156819036574]   //ERR
6:Array[1629945165,52156780668032]
7:Array[1629945180,52156780668032]
8:Array[1629945195,52156782141385]
9:Array[1629945210,52156782141385]
10:Array[1629945225,52156782474794]
11:Array[1629945240,52156782474794]
```

### Additional info:

all erros just in `bond ` interfaces.

**Comment by powersj** [comment]
Hi,

Thanks for the report, but we are going to need some more information to reproduce and understand the issue you are reporting.

Can you please provide a telegraf config, and what type of system you are collecting this on as well as what distribution are you using?

Thanks!
