### ISSUE TITLE
What is the minimum permission required to allow Telegraf access to the service manager? 

### ISSUE THREAD

**Issue by boomcubist** [influxdata/telegraf#9704]
I've created a service account for running Telegraf and if I open PowerShell as that user and run `Get-Service`, I can see the status of all services, however Telegraf fails to read services information and throws the following error: 

> [inputs.win_services] Error in plugin: Could not open service manager: Access is denied. 

I don't want to make the account a local or domain admin. 

Can you please offer some guidance on how I can read services without making the account a local or domain admin.

**Comment by powersj** [comment]
Telegraf currently requires Administrator-level permissions to open and read the service manager.
