### ISSUE TITLE
Add "up" field to http_response input plugin

### ISSUE THREAD

**Issue by xoxys** [influxdata/telegraf#9723]
### Proposal:

Add another field e.g. `up` that reflects if the target is up or down regardless of the reason. IMO, a simple solution would be to add something like this (pseudocode):

```
if result_code == 0 {
    fields["up"] = 1
} else {
     fields["up"] = 0
}
```

### Use case:

With the currently provided plugin output, It's pretty hard to calculate percentile up-/ and downtime of a target, which might be helpful in some situations.

**Comment by srebhan** [comment]
@xoxys thanks for the suggestion. You can already do this by using the `starlark` plugin. The issue is, for some services other return code e.g. `200` also suggest that the service is up and running.

**Comment by xoxys** [comment]
Thanks for your fast reply. I totally forgot about processor plugins... I'll look into it.

**Comment by srebhan** [comment]
@xoxys if you find that the processors are a suitable solution, please do not forget to close the issue here and maybe report how you solved it (for the next one).
Otherwise, please let me know and we will find a solution.

**Comment by xoxys** [comment]
Works like a charm, thanks again and sorry for the delay.

**Comment by xoxys** [comment]
> report how you solved it (for the next one)

```
[[inputs.http_response]]
  urls = ["https://google.de"]

  follow_redirects = true
  method = "GET"
  response_timeout = "5s"

  response_status_code = 200

[[processors.starlark]]
  namepass = ["http_response"]

  source = '''
def apply(metric):

  if metric.fields["result_code"] == 0:
      metric.fields["success"] = 1
  else:
      metric.fields["success"] = 0

  return metric
'''
```
