### ISSUE TITLE
Error while installing in RHEL7 using rpm

### ISSUE THREAD

**Issue by pckeyan** [influxdata/telegraf#973]
Hi,

I am planning to use telegraf to capture the metrics within Docker Container. I do not have yum installed in my Base RHEL7 image and would not be allowed to do. Can you please let me know how to install the package? I tried with rpm and got the following error:

error: Failed dependencies:
	lsof is needed by telegraf-0.11.1-1.x86_64

Any help is appreciated.
Thanks
Karthik

**Comment by sparrc** [comment]
install lsof first, then telegraf

**Comment by pckeyan** [comment]
I tried, lsof has dependencies on Perl and my image is getting fat. Can you please advice?

**Comment by sparrc** [comment]
use the standalone binaries, I believe only the netstat plugin has the lsof dependency anyways

**Comment by pckeyan** [comment]
I could not find any instructions on installing the standalone libraries, can you please share any link on RHEL7?

**Comment by sparrc** [comment]
https://github.com/influxdata/telegraf#linux-tarballs

**Comment by sparrc** [comment]
fyi: Telegraf 0.12.1 will no longer require lsof, this is actually a packaging mistake (see https://github.com/influxdata/telegraf/issues/974)

**Comment by pckeyan** [comment]
When will I get this version to try?

**Comment by sparrc** [comment]
1-2 weeks
