### ISSUE TITLE
Handle new Influxdb_v2 write limits

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#9744]
InfluxDB cloud API has had a compressed write payload limit for some time. A decompressed write payload limit was recently added. These payload limits are in bytes. If a request is too large InfluxDB cloud should return a 413 http.StatusRequestEntityTooLarge. 

In Telegraf, the number of metrics in an output batch is configurable with the agent setting `metric_batch_size`. Since this is the number of metrics, it's not a precise way to limit the size in bytes. Currently, if the influxdb_v2 output sends a batch that is too large and receives a 413 response, it doesn't retry sending the batch.

The influxdb_v2 output should be changed to check InfluxDB cloud's limits and not send requests that are too large, by either the compressed or uncompressed limits. If a metric batch is too large it could be split into two or more smaller requests that aren't too large.

When the influxdb_v2 output no longer sends requests that are too large it shouldn't ever receive a 413 response. When that is the case we should rethink what the plugin does if it receives a 413 response.

**Comment by reimda** [comment]
@philjb Could you check that I got the details right in this issue? Thanks for letting us know about the change to cloud!

**Comment by philjb** [comment]
@reimda - looks great!

**Comment by philjb** [comment]
Hey @powersj - 

* These rate limits only apply to InfluxDB Cloud. If someone hosted their own instance of InfluxDB the 413 response would not be seen? Or is this configurable there as well?

I'm not sure with Influxdb OSS does or is capable of for rate limits.

* Is the rate limit specific to a single request body size or overtime? (i.e. the cloud pricing page has different data-in limits for free vs usage-based)

There's several limits. For a single request, there's a currently 50MB payload size enforced at the edge - this is the max no matter it being compressed or not. There is then a decompressed limit that is currently 250MB per request. These should get you a 413. Then organizations have rate limits that are measured over time - these are what you see on the cloud pricing page. These should return 429.

* Is the rate limit value static or dynamic?

The per request payload size is static but changeable - we do not expect to change it frequently but we may.

* Is there a way to query for the rate limit value?

I don't know of a way to query for the per request payload size limits currently.

* The original post makes reference to both compressed and decompressed limits. Are those published somewhere?

The 50MB payload limit is in the docs but I don't believe the 250MB is yet. I believe the docs team is working on that one.

**Comment by powersj** [comment]
@philjb, thanks for the background. A few follow-ups:

For the purpose of this feature request, it then sounds like we are explicitly concerned with Telegraf receiving a 413 response from only InfluxDB Cloud. In which case, we could warn the user and attempt to reduce the payload size (i.e., split in half) and try again. Any additional 413 responses, could error out saying we tried to reduce, but the requests are still too larger. And dealing with 429s would be a separate initiative.

Telegraf does not differentiate between InfluxDB Cloud and OSS, so I would want to confirm that this would not cause any issues with OSS deployments. So this is something we would want to close on before digging too far into this.

Are there stats on how often the cloud returns 413s?

**Comment by philjb** [comment]
New docs update for the 250MB limit! https://github.com/influxdata/docs-v2/pull/3392

I am concerned with Telegraf receiving a 413 response from InfluxDB Cloud, as I'm a c2 engineer, but 413 is a general purpose error - I don't see why telegraf shouldn't handle that error generically for all influxdb destinations or for all output plugins - I believe it should. I suggest starting with 413 logic for cloud2 though as it helps us doubly. 

A one retry attempt for 413 seems like a good approach - half the payload size on the retry. The logic can be improved farther afterwards.
