### ISSUE TITLE
redfish input plugin - multiple input URLs

### ISSUE THREAD

**Issue by ctyjiuh** [influxdata/telegraf#9754]
## Feature Request
ability to put multiple addresses to scrab from
### Proposal:
convert address variable form string to array
### Current behavior:
every single BMC under separate input plugin section
### Desired behavior:
multiple addresses for single input plugin section
### Use case: 
Actually many users face with multiple identical servers. This means that we can use single input section for multiple servers, Therefore, if address variable should be array instead of string

**Comment by powersj** [comment]
Hi! Access to a redfish interface requires a hostname as well as a username and password. Because of this, I do not think this is something we would want to do as it would imply all hosts are using the same credentials.

I am going to close this, but let us know if you think there is a different possible solution.

**Comment by mollycule** [comment]
Hi, @powersj! Some data centers restrict direct access to the OOBM from the OS and only allow access through a management network for security purposes. In this case, having access to redfish interfaces for multiple addresses within one or more instance(s) of the redfish input plugin might be really helpful!

For the username/password logic, maybe it could follow a similar style as the [ipmi_sensor input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ipmi_sensor) where the default address is `127.0.0.1` and there's an [option to specify more than one address with the username and password included](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ipmi_sensor/README.md?plain=1#L46). I know that currently, it's possible to have the redfish input plugin defined multiple times in one telegraf instance for each separate address, but I'm not sure how resource-intensive that could get.

Let me know if you think this is too much of an edge case!

**Comment by saymonaraujo** [comment]
This feature would really be useful, can we reopen this discussion ? @ctyjiuh
