### ISSUE TITLE
Out of order Log lines returning to Metric queue after returning an error in Loki

### ISSUE THREAD

**Issue by jammiemil** [influxdata/telegraf#9755]
### Relevant telegraf.conf (taken from my Helm values):

```   
outputs:
   - loki:
          domain: "http://loki-gateway.monitoring.svc.cluster.local"
          namepass:
            - "GCS Logs"
inputs:
   - cloud_pubsub:
        name_override: "GCS Logs"
        interval: "1s"
        project: "xxx"
        subscription: "xxx"
        max_extension: -1
        data_format: "json"
        json_string_fields:
          - "*"
        json_time_key: "timestamp"
        #2021-09-10T19:24:04.115665Z
        json_time_format: "2006-01-02T15:04:05.999999Z"
        #data_format: "value"
        #data_type: "string"
        credentials_file: "xxx"


```

### System info:

Running in k8s using version "1.19-alpine", Writing to Loki 2.3

### Steps to reproduce:

1. Have out of order Log lines in your Loki Output Queue
2. Telegraf Output receives Status code 400 for out of order Log lines

### Expected behavior:

Out of order log lines should be dropped from the Output queue to prevent them from being resent, This in turn should be setting the log in GCP pubsub to Acknowledged so it isnt resent

### Actual behavior:

Out of order log lines are returned to the Output queue and/or left unacknowledged in GCP and build up until the metric buffer is full generating errors at every interval as the out of order lines are resent repeatedly

### Additional info:

Telegraf 1.20 and Loki 2.4 will help alleviate this somewhat as the changes to the Telegraf output plugin will sort the lines by timestamp + Loki 2.4 will allow out of order logs for a certain period, However the behaviour still needs addressing whereby Log lines that generate errors are being retried repeatedly until the telegraf agent is restarted, rather than being dropped from the buffer. For Example:

Telegraf receiving status code 400:
![image](https://user-images.githubusercontent.com/54275278/133217022-371a85cd-02ed-4212-a959-1a5cd1adc8a1.png)
Loki returning Entry out of order:
![image](https://user-images.githubusercontent.com/54275278/133217325-5c1995be-b3d1-466a-8da4-542dc4dffeac.png)
Output buffer filling up until hitting its limit as out of order log lines build up:
![image](https://user-images.githubusercontent.com/54275278/133217551-b30081ad-4b61-442a-853b-24e6915e0f8e.png)

**Comment by jammiemil** [comment]
Trying a few things out to understand what is happening under the hood with this one a little better. One thing ive noticed is that my input plugin cloud pubsub is not marking messages as acknowledged until they are written to the output, This means that when loki returns the out of order message the input plugin will just pull the message down again even if its dropped from the metric buffer. Im going to reconfigure my pubsub so that logs expire sooner to stop this from happening however i still dont think the 'metrics' are being dropped from the output buffer as the metrics_dropped field is not incrementing.

**Comment by jammiemil** [comment]
After upgrading to 1.20 (With the sorting in the output plugin for loki) The issue is reduced as there are less out of order log lines due to sorting but it still happens, out of order lines have filled up the queue until they time out on the pubsub

**Comment by jammiemil** [comment]
Updated my Loki install to grafana/loki:k62-d40814b which allows out of order lines and this has resolved the issue, Not sure if threes still value in still addressing out of order lines being left in the buffer though as there's limits to how far out of order the lines can be.

**Comment by sspaink** [comment]
@jammiemil sorry you never received a response, since you've updated Loki is this issue now been completely resolved for you?
