### ISSUE TITLE
APCUPS plugin - add LASTXFER parameter

### ISSUE THREAD

**Issue by artstar-es** [influxdata/telegraf#9761]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 
Requesting the addition of the LASTXFER parameter to the apcups plugin for capture by Telegraf

### Current behavior: 
LASTXFER is not being captured at the moment.

### Desired behavior: 
LASTXFER is to be captured in addition to all existing data already being captured by the apcups plugin.

### Use case: 
To give visibility of reason behind the UPS battery being used for detailed analysis of the UPS' performance.

**Comment by powersj** [comment]
Hi,

Thanks for the feature request.

It looks like this field is already exposed in the upstream library. Would you be willing to create a PR adding this field?

Thanks

**Comment by artstar-es** [comment]
Happy to. Pardon my n00bness but what's a PR? :)

**Comment by artstar-es** [comment]
Thanks for the reply!

I'm considerably lost on creating a pull request for this, given that requires me to be a contributor, which I'm far from! 😁

I'll just take the lazy way out and search the logs FTP'ed from the UPS correlating with the battery event.

**Comment by olivergregorius** [comment]
@artstar-es PR #12014 has been created, adding LASTXFER and other fields.
