### ISSUE TITLE
telegraf/plugins/inputs/prometheus/ - only prometheus metrics

### ISSUE THREAD

**Issue by RickJCronin** [influxdata/telegraf#9766]
Successfully configured the prometheus plugin and receiving a bunch of metrics but they are internal prometheus metrics. Cannot see any collected metrics such as Bosh or Consul. I can see them if I use the URL in a browser but they are not flowing.

**Comment by helenosheaa** [comment]
Hey @RickJCronin I [replied](https://influxcommunity.slack.com/archives/CH99HUH8V/p1631813478219100) to your post on slack, let's continue the thread there.
