### ISSUE TITLE
Please, can you add support for 'value' telegraf input data format in mqtt_consumer

### ISSUE THREAD

**Issue by rapport** [influxdata/telegraf#978]
I am using the MQTT consumer https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer

Most of the data on our MQTT broker has only topic and a value e.g. 

kitchen/light/switch on
kitchen/temperature 19
[...]

Is it possible to add the 'value' input data format to the mqtt_consumer to support this-out-the box?

It appears the value format is the only type from the set that is not currently supported...
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

I imagine this is a common requirement. And, that many users would like to have values short and concise with the meta data in the topic name!

**Comment by sparrc** [comment]
value is supported....what makes you think it isn't?

you might need to upgrade to 0.12

**Comment by rapport** [comment]
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer

It says Data format to consume. This can be "json", "influx" or "graphite"

... but doesn't mentioned value it also did not appear to work with value when I tested. I will just check the version!.

**Comment by rapport** [comment]
I am using version 0.12.0-1    [...]   I will double check the data. I presume value can deal with number and strings. Maybe the fact the strings are in quotes is causing a problem but the number appear not to work also.

**Comment by sparrc** [comment]
I can help more if you post your config, are you specifying the data format?

**Comment by rapport** [comment]
[data_config_logdata.txt](https://github.com/influxdata/telegraf/files/205406/data_config_logdata.txt)

**Comment by rapport** [comment]
I have attached snippet with data, config and log. I am specifying data_format = "value"

**Comment by sparrc** [comment]
you need to specify data_type also, https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#value

**Comment by rapport** [comment]
When I add the data_type it cannot read the telegraf.conf file

telegraf.conf

data_format = "value"
data_type = "integer"

telegraf.log

2016/04/05 22:14:38 Error parsing /etc/telegraf/telegraf.conf, line 125: field corresponding to `data_type' is not defined in `*mqtt.MQTT'

**Comment by rapport** [comment]
Hold on a sec... it looks like my regex may have added a second data_type in [[outputs.mqtt]] I will need to re-test probably it is working with your correction!

**Comment by rapport** [comment]
Many thanks for your help as it is all working now. I just needed both the 

data_format = "value"
data_type = "integer"

... and only in [[inputs.mqtt_consumer]] and not in [[outputs.mqtt]] also! 

Maybe you could add to documentation https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer

The bit that says 'This can be "json", "influx" or "graphite"'

... and can also be "value" (but a value MUST have its data_type defined as well)

**Comment by sparrc** [comment]
yes, my bad, I'm working to get these READMEs updated, thanks for pointing me to that
