### ISSUE TITLE
collect nvidia-smi errors as metric 

### ISSUE THREAD

**Issue by lage2104** [influxdata/telegraf#9785]
## Feature Request

Add a additional field if an error occurs during a nvidia-smi call.

### Proposal: 
collect nvidia-smi errors

### Current behavior: 
no metrics at all are collect if an error occurs.

### Desired behavior: 
collect metric if an error occurs.

### Use case: 
easier detection if nodes have GPU failures.

**Comment by powersj** [comment]
Hi,

There are a number of errors that can occur when collecting data. Do you have some example errors you could share that might help determine the next steps?

Thanks!

**Comment by staeglis** [comment]
Hi,

we are thinking about errors like ```Unable to determine the device handle for GPU 0000:04:00.0: Unknown Error```

Best,
Stefan

**Comment by powersj** [comment]
> we are thinking about errors like Unable to determine the device handle for GPU 0000:04:00.0: Unknown Error

Is this error constantly printing out or only occasionally?

Looking around it looks like this can be due to a number of issues, including errors from the GPU that would show up in a syslog.

**Comment by staeglis** [comment]
Yes can see it in syslog when the error happens. But we want monitor the current state. And for this purpose it's more convenient to catch the error message when the exit code of nvidia-smi is unequal to zero instead of delivering no data at all.

**Comment by powersj** [comment]
When that error happens it sounds like no data is able to be collected. If you run the nvidia-smi command does it work at all?

**Comment by staeglis** [comment]
Yes when the error occurs there is no GPU data collected because the output is the error messages instead of the expected information. The error can be mitigated by a reboot.

**Comment by powersj** [comment]
What then is your desired behavior for Telegraf? In the original report you said:

> collect metric if an error occurs.

You just said there is no data to collect, so I'm not sure I follow.

**Comment by powersj** [comment]
Hmm I am inclined not to say we would not make this change. If a plugin is unable to collect data, the typical behavior is and should be to fail. This could cause issues for users who think that as telegraf continues to run then everything is collected as expected.

I think your workaround is a good one for your particular desired behavior.

**Comment by staeglis** [comment]
A DAU might think all it's fine when the plugin don't collect any GPU load etc. but only a error message. But I don't think that a DAU will use telegraf.

But actually the purpose of this plugin is to monitor nvidia based GPUs. And GPU errors are an important information when you want to monitor your GPUs.

**Comment by powersj** [comment]
> A DAU might think all it's fine when the plugin don't collect any GPU load etc

I disagree. If Telegraf is not collecting and your output is not getting any reports, then clearly there is a problem that requires attention from the user.

> But actually the purpose of this plugin is to monitor nvidia based GPUs. And GPU errors are an important information when you want to monitor your GPUs.

You can look at many of the other inputs, collecting errors and reporting them is not in scope. I appreciate the request, but this is outside what Telegraf provides.
