### ISSUE TITLE
GNMI subscription

### ISSUE THREAD

**Issue by doxuanquang** [influxdata/telegraf#9806]
## Feature Request
Allow inputs.gnmi.subscription to return data in one single json instance
Opening a feature request kicks off a discussion.

### Proposal:
inputs.gnmi.subscription gets streaming data from devices and automatically separate data into different series, making it hard to correlate later in InfluxDB or Prometheus
### Current behavior:
`{"fields":{"description":"spn-onyc-002"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114634854}
{"fields":{"dynamically_configured":false},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114635124}
{"fields":{"enabled":true},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114635127}
{"fields":{"established_transitions":4,"last_established":1626710982292103680},"name":"network_bgp","tags":{"host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","openconfig:/network-instances/network-instance/protocols/protocol/name":"BGP","path":"openconfig:/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"messages/received/UPDATE":2842666},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163237623599}
{"fields":{"messages/sent/UPDATE":455364},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163234480719}
{"fields":{"neighbor_address":"10.253.35.130"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"peer_as":4210200800},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"peer_group":"WAN"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114634854}
{"fields":{"send_community":"NONE"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114635124}
{"fields":{"session_state":"ESTABLISHED"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"10.253.35.130","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"description":"clf-lab-001-b"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634855}
{"fields":{"dynamically_configured":false},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114635124}
{"fields":{"enabled":true},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114635128}
{"fields":{"established_transitions":4},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"last_established":1626783884890929920},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"messages/received/UPDATE":1128489},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163237623000}
{"fields":{"messages/sent/UPDATE":2503780},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163237623599}
{"fields":{"neighbor_address":"172.22.255.181"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"peer_as":64512},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634853}
{"fields":{"peer_group":"LEAF"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634855}
{"fields":{"send_community":"NONE"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114635124}
{"fields":{"session_state":"ESTABLISHED"},"name":"network_bgp","tags":{"/network-instances/network-instance/protocols/protocol/name":"BGP","host":"ed33371ec3f8","identifier":"BGP","name":"default","neighbor_address":"172.22.255.181","path":"","source":"172.22.255.254"},"timestamp":163114634853}`
### Desired behavior:
`[
  {
    "time": "1970-01-01T07:30:00+07:30",
    "updates": [
      {
        "Path": "network-instances/network-instance[name=default]/protocols/protocol[identifier=BGP][name=BGP]/bgp/neighbors/neighbor[neighbor-address=172.22.255.180]/state",
        "values": {
          "network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state": {
            "openconfig-network-instance:description": "clf-lab-001-a",
            "openconfig-network-instance:dynamically-configured": false,
            "openconfig-network-instance:enabled": true,
            "openconfig-network-instance:established-transitions": "3",
            "openconfig-network-instance:last-established": "1626783884891099136",
            "openconfig-network-instance:messages": {
              "received": {
                "UPDATE": "2503654"
              },
              "sent": {
                "UPDATE": "1128483"
              }
            },
            "openconfig-network-instance:neighbor-address": "172.22.255.180",
            "openconfig-network-instance:peer-as": 64512,
            "openconfig-network-instance:peer-group": "LEAF",
            "openconfig-network-instance:send-community": "NONE",
            "openconfig-network-instance:session-state": "ESTABLISHED"
          }
        }
      }
    ]
  }
]`
### Use case: 
GNMI is most promising protocol for streaming telemetry data for network monitoring and there's no good GNMI client in the market at the moment

**Comment by bewing** [comment]
Any chance of prettyprinting the current/desired behavior for readability?

**Comment by srebhan** [comment]
@doxuanquang does this issue still exist with current Telegraf?
