### ISSUE TITLE
Small nuance

### ISSUE THREAD

**Issue by shmidtelson** [influxdata/telegraf#9829]
https://github.com/influxdata/telegraf/blob/f489cff3eadd150123c894121fe45424b0828f38/plugins/outputs/loki/loki.go#L60

Hi, guys!
I found one nuance

`http_headers` doesnt work
but `headers` - works ok

**Comment by helenosheaa** [comment]
Thanks for opening the issue. There was a discrepancy between the toml tag which is headers and the readme which says it's http_headers, I've put in a PR so that http_headers is correct.
