### ISSUE TITLE
Is it possible to specify new database for a input plugin.

### ISSUE THREAD

**Issue by yuyang0** [influxdata/telegraf#983]
I can specify database in the influxdb configure section, but sometimes, I want to store the data  from a special input plugin(developed by myself) to a new database, Is it possible or do you have any plan to support this feature?

**Comment by sparrc** [comment]
you can use drop/pass configuration to specify which metrics will go to which outputs. https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-fieldpass-and-fielddrop
