### ISSUE TITLE
Change data collection interval at runtime

### ISSUE THREAD

**Issue by jnangle** [influxdata/telegraf#9834]
## Feature Request

I request a feature in which the Telegraf is able to change it's data collection interval dynamically at runtime, including turning data collection on and off.

### Proposal:

This feature would allow data logging in Telegraf to respond in real time, allowing data to be saved at different intervals.  It would also allow data collection to be started and stopped dynamically without needing to start/stop the Telegraf application.

### Current behavior:
Telegraf currently logs data at a fixed rate once the application is started, set by the `interval` parameter.  In addition, there is no way to control whether or not data is logged except by starting and stopping the application.

### Desired behavior:
In my use case (IoT in a research environment), it is desirable to start and stop data logging and to control the rate at which data is logged in response to changes in an experiment setup.  In this case, the Telegraf `interval` would be changed dynamically at runtime by listening to an OPC UA (or other protocol) variable coming from a PLC or other application.

Perhaps another way to do this would be to change the logging interval for the OPC UA, client apart from changing Telegraf as a whole.

### Use case: 
In my use case, I have PLCs that collect data from sensors that are measuring data for a research project.  This data is collected and logged in Influx via the Telegraf OPCUA plugin.  I would like to be able to set a variable in the PLC code to signal Telegraf to start and stop logging data based on conditions in the experiment.  

For example, a button on an HMI screen that sets a PLC variable to True or False.  Telegraph then reads this variable via OPC UA and dynamically starts or stops data logging.  This would also allow Telegraf to respond to changing conditions in the experiment, e.g. if a voltage reading in the experiment goes above a certain value, start logging data or start logging data at a different rate.

Another use case is changing the rate at which data is logged from a project.  As seen previously, there may be conditions in an experiment that warrant collecting data at a different frequency.  For example, if everything in an experiment is running normally, data is logged at 1s intervals.  If conditions change, then start logging at 100ms until conditions reset.

**Comment by powersj** [comment]
Hi,

The feature to have dynamic changes to Telegraf's operations based on external events is not something I see us adding. In the past, there have been proposals to have an API or other type of dynamic updating process. However, ultimately we never reach consensus as to what this would look like, without much larger changes to Telegraf, with limited benefit.

I am going to close this as not planned.

Thanks
