### ISSUE TITLE
Add docs on how to better use the Telegraf CLI binary

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9835]
Provide more guidance for users on how and why to use the Telegraf CLI. 

~Currently have manually created docs of Telegraf's [commands and flags](https://github.com/influxdata/telegraf/blob/master/docs/COMMANDS_AND_FLAGS.md) that essentially outlines all the information from `-help`. These flags may get updated in usage.go and doc may get outdated.~

~To-do: Automate information in [usage.go](https://github.com/influxdata/telegraf/blob/master/internal/usage.go) to docs so if usage.go gets updated so will the docs~

**Comment by powersj** [comment]
@sjwang90 what about rather than constantly keeping that page up to date, we replace the page with pointers on how to use the telegraf CLI binary. And users can use the CLI to get the latest help information, flags, and options?

**Comment by sjwang90** [comment]
That sounds good! @powersj Makes sense like just having a docs page when the user could just type `-help` isn't that useful. 

I'll change the goal of the issue - if anyone from the community has anything they'd like to add and see please let me know.
