### ISSUE TITLE
Integer Overflows in GLOBAL STATUS variables in MySQL Input Plugin

### ISSUE THREAD

**Issue by Viajaz** [influxdata/telegraf#9836]
As far as I can tell, the conversion from a string to integer `strconv.Atoi()` is resulting in a 32-bit integer which makes monitoring 64-bit GLOBAL STATUS integers ([technically ulint](https://github.com/mysql/mysql-server/blob/5.7/storage/innobase/include/srv0srv.h#L892)) losslessly impossible in the MySQL Input Plugin, resulting in integer overflows in MySQL status variables such as `Innodb_buffer_pool_bytes_data`

https://github.com/influxdata/telegraf/blob/56398237c4a931dba438db553a1ee1487926c072/plugins/inputs/mysql/mysql.go#L816

https://stackoverflow.com/questions/21532113/golang-converting-string-to-int64

**Comment by powersj** [comment]
Hi! 

The Atoi call you point out is run when the metric version is set to 1. Metric version 2, the default version, introduced a lot of fixes specifically around types that should fix this situation.

I am going to close this, but if you are running across this with metric version 2 please feel free to re-open and include some details on what you are seeing. 

Thanks!
