### ISSUE TITLE
telegraf can not stop gracefully when intel_rdt plugin enabled, even running as root

### ISSUE THREAD

**Issue by guoqiao** [influxdata/telegraf#9844]
### Relevant telegraf.conf:

```toml
   [[inputs.intel_rdt]]
   cores = ["0-23"]
```

### System info:

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

apt list --installed | grep telegraf
telegraf/now 1.20.0-1 amd64 [installed,local]
```

the deb package is downloaded from [official repo](https://repos.influxdata.com/ubuntu/pool/stable/t/telegraf/telegraf_1.20.0-1_amd64.deb)

### Steps to reproduce:

1. install latest official deb pkg:

   wget https://repos.influxdata.com/ubuntu/pool/stable/t/telegraf/telegraf_1.20.0-1_amd64.deb
   sudo apt install ./telegraf_1.20.0-1_amd64.deb

2. enable `intel_rdt` plugin in `/etc/telegraf/telegraf.conf`:

   [[inputs.intel_rdt]]
   cores = ["0-23"]

3. modify systemd service file to run telegraf as root

By default, the deb package run telegraf service as non-root user `telegraf`. While `pqos` must run as root. This issue is already coverd by Issue #9380 and PR #9527.

In this bug, I am running telegraf as root:

```
   sudo -i
   vim /lib/systemd/system/telegraf.service
   # modify user: User=root
   systemctl daemon-reload
   service telegraf restart
   ps -ef | grep telegraf  # confirm telegraf user is root
   # root     14621 ... /usr/bin/telegraf ...
   ps -ef | grep pqos  # confirm pqos is running
   # root ... /usr/sbin/pqos -r --iface-os --mon-file-type=csv --mon-interval=10 ...
```

4. stop telegraf as root and monitor time

```
   time service telegraf stop
```

### Expected behavior:

telegraf service and pqos process should stop successfully.

### Actual behavior:

```
   time service telegraf stop
   real    1m30.887s
   user    0m0.102s
   sys     0m0.075s
```

above cmd will hang for about 90s and timeout, which is default systemd service behavior when SIGTERM in ExecStop not responding.

### Additional info:

In `service telegraf status`:

It will show this when waiting:

```
Active: deactivating (stop-sigterm) since Thu 2021-09-30 23:41:17 UTC; 14s ago
```

and finally show this after 90s/timeout:

```
service telegraf status
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Thu 2021-09-30 23:47:37 UTC; 145ms ago
     Docs: https://github.com/influxdata/telegraf
  Process: 16344 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=killed, signal=KILL)
 Main PID: 16344 (code=killed, signal=KILL)

Sep 30 23:44:52 hutton systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 30 23:44:52 hutton telegraf[16344]: 2021-09-30T23:44:52Z I! Starting Telegraf 1.20.0
Sep 30 23:46:07 hutton systemd[1]: Stopping The plugin-driven server agent for reporting metrics into InfluxDB...
Sep 30 23:47:37 hutton systemd[1]: telegraf.service: State 'stop-sigterm' timed out. Killing.
Sep 30 23:47:37 hutton systemd[1]: telegraf.service: Killing process 16344 (telegraf) with signal SIGKILL.
Sep 30 23:47:37 hutton systemd[1]: telegraf.service: Main process exited, code=killed, status=9/KILL
Sep 30 23:47:37 hutton systemd[1]: telegraf.service: Failed with result 'timeout'.
Sep 30 23:47:37 hutton systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
```

However, a interesting fact is, when the stop cmd is fired, `pqos` process actually disappear from `ps` output very quickly, and `strace` tells us, it does get the `SIGTERM` signal form systemd:

```
strace -p $PQOS_PID
...
nanosleep({tv_sec=0, tv_nsec=939173000}, {tv_sec=0, tv_nsec=367271276}) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=1, si_uid=0} ---
+++ killed by SIGTERM +++
```

This may relate to following code:

https://github.com/influxdata/telegraf/blob/70afc94d121c4bb75ded3f8177859436355c4dfa/plugins/inputs/intel_rdt/intel_rdt.go#L336-L348

The `shutDownPqos` does stopped the pqos process, while err is still returned and considered as failed.
(I might be wrong, since I didn't see that err msg in telegraf.log though)

**Comment by KubaTrojan** [comment]
Hi @guoqiao,

Could you apply [these changes](https://github.com/influxdata/telegraf/pull/9527/files#diff-623e31993589bb59405f9757412c6a68e1518ed7ffbbc6a23b9e26d922f932a0L279-R297) from [Patched Intel RDT PR ](https://github.com/influxdata/telegraf/pull/9527)and tell if this resolves the issue?

Thanks

**Comment by guoqiao** [comment]
@KubaTrojan   I had a try, yes, it does fix it. PR#9850 created. Thank you!
