### ISSUE TITLE
Implement throttling for inputs.execd when Buffer fullness is reaching the max as metrics are dropped & data is lost.

### ISSUE THREAD

**Issue by vainkop** [influxdata/telegraf#9847]
## Feature Request

Implement throttling for `inputs.execd` when `Buffer fullness` is reaching the max as metrics are dropped & data is lost.

### Proposal:
Implement throttling for `inputs.execd` when `Buffer fullness` is reaching the max.
currently a lot of not very smart logic like sleeps need to be used inside the command script as well as in agent intervals which still doesn't guarantee that Buffer fullness isn't reached & data isn't lost which is highly undesirable.

### Current behavior:
When Buffer fullness reaches the max metrics are dropped & data is lost.

### Desired behavior:
At X% (should be configurable) (90% by default?) of `Buffer fullness` a throttling/sleep can be implemented so the `inputs.execd` plugin will take care of that & metrics aren't lost.

### Use case: 
When `Buffer fullness` reaches the max metrics are dropped & data is lost.

**Comment by reimda** [comment]
Telegraf has a concept of tracking metric (see the telegraf.TrackingAccumulator type in the codebase). I think this could be used in the execd plugin to implement something similar to what you want. We would need to add a setting to execd that lets users opt into the new behavior.

Are you able to work on this and contribute a PR to implement it? Thanks
