### ISSUE TITLE
SNMP plugin: include_instances with RegExp

### ISSUE THREAD

**Issue by cesaroni** [influxdata/telegraf#986]
Hi,
first I love Telegraf and the SNMP plugin :)
It should be nice to add a RegExp in the include_instances array

like:
[[inputs.snmp.host.table]]
      name = "cpu"
      include_instances=["/^Routing Engine*/","/^FPC*/" ]

**Comment by titilambert** [comment]
@cesaroni please check before open an issue, this is already opened... see here: https://github.com/influxdata/telegraf/issues/986

@sparrc I think you could close this one in favour of https://github.com/influxdata/telegraf/issues/986
