### ISSUE TITLE
Windows counters with "/" seem to result in select error in version 0.12.x

### ISSUE THREAD

**Issue by codenaked** [influxdata/telegraf#987]
I just upgraded my InfluxDB to 0.12 and a few of my graphs are now failing. The graphs include performance counters for our ASP.NET app, notably "Requests / Sec". It seems that the "/" is now causing problems with the select statement used by Grafana.

Any ideas on how to work around this (assuming it's true)?

Thanks!

**Comment by sparrc** [comment]
I'm not sure, sorry, you should open this case against influxdb though, not Telegraf

**Comment by codenaked** [comment]
I dug a little deeper and it appears to be an issue with Grafana, but was a breaking change with InfluxDB:

https://github.com/grafana/grafana/pull/4580
