### ISSUE TITLE
Issue with oAuth2 client in HTTP Input Plugin of telegraf

### ISSUE THREAD

**Issue by sameer-ranjan-kumar** [influxdata/telegraf#9879]
### Relevant telegraf.conf:
```
[[inputs.http]]
  urls = ["<url>"]
  client_id = "<client_id>"
  client_secret = "<client_secret>"
  token_url = "<token_url>"
  data_format = "json"

```

### Steps to reproduce:

1. Install telegraf
2. Getting this error from telegraf :
`[telegraf] Error running agent: Error loading config file telegraf/telegraf.conf: Error parsing http, line 86: field corresponding to `client_id' is not defined in http.HTTP`

### Issue:

Due to this, unable to use OAuth authentication. Basic authentication works fine.

**Comment by sspaink** [comment]
Have you tried this with the latest version of Telegraf? Are you still seeing the same issue?
