### ISSUE TITLE
sql server grafana dashboard

### ISSUE THREAD

**Issue by ragesaq** [influxdata/telegraf#988]
Does somebody have a dashboard json for grafana for the sqlserver plugin? The subpage on the plugin has a lot of good looking screenshots related to SQLServer but no example, would be greatly appreciated!

**Comment by sparrc** [comment]
@zensqlmonitor could you provide dashboards?

**Comment by erSitzt** [comment]
any news on this ? the plugin is providing quite a lot metrics and it would be nice to have a sample dashboard to start with.

@zensqlmonitor ***please*** could you provide them ?

**Comment by zensqlmonitor** [comment]
Hi, 
it has been published some time ago: 
https://grafana.net/dashboards/409

**Comment by erSitzt** [comment]
Ok, thanks ! :)
