### ISSUE TITLE
[inputs.mongodb] Don't try to collect col stats on views

### ISSUE THREAD

**Issue by micoq** [influxdata/telegraf#9883]
I would like to collect the stats of all the collections in MongoDB without knowning their names:
```
[[inputs.mongodb]]
col_stats_dbs = []
```
but I got this error in the log: 
```
[inputs.mongodb] error getting col stats from "xxx": (CommandNotSupportedOnView) Namespace xxx is a view, not a collection
```
It could be useful to automatically filter the db list to keep only the real collections, not the views.

**Comment by reimda** [comment]
Hi, were you able to find a way to make this work? I see in the documentation and code that if col_stats_dbs is empty, it should read from all databases.

If this isn't working for you, could you do a quick test that should give us more information? Using the same config file, enter a valid database name in the col_stats_dbs setting and try again. If that works, we will know everything else in the plugin configuration is valid (server addresses, tls config, etc) and it will imply more strongly that there's a bug.

Thanks!

**Comment by micoq** [comment]
Hi reimda,
Yes, it works with `col_stats_dbs = []`. In this case, Telegraf send me the metrics of all databases but it also try to get the stats from the views and so that's we get this error message.
You can reproduce this behavior on a fresh installation of mongodb (5.0): just create a database with a single collection and a view pointing on it:
```
use test
db.test.insert({test: "Test"})
db.createView("test_view","test",[])
```
and configure Telegraf:
```
[[inputs.mongodb]]
servers = ["mongodb://127.0.0.1:27017/?connect=direct"]
gather_col_stats = true
col_stats_dbs = []
```
In this case, we got this error:
```
E! [inputs.mongodb] error getting col stats from "test_view": (CommandNotSupportedOnView) Namespace test.test_view is a view, not a collection
```
Of course, it disappear if you exclude the view by specifying the database but we didn't want to have to list all the databases in the configuration:
```
col_stats_dbs = ["test"]
```
