### ISSUE TITLE
Read failed: opcua: invalid extension object with id ns=4;i=5086

### ISSUE THREAD

**Issue by vdkost** [influxdata/telegraf#9900]
Hi,

I want to use telegraf agent to transfer data from opcua server to influxDB.
The opcua servers I have to connect to publishes some data as complexDataTypes (ExtensionObjects). Trying to read these extensionObject nodes I get the error message:
`E! [inputs.opcua] Error in plugin: get Data Failed: RegisterNodes Read failed: opcua: invalid extension object with id ns=4;i=5086`
Can anybody assist me in configuring telgraf opcua plugin to be able to handle extensionObjects? Is it possible at all? what alternatives exists?
Thanks

**Comment by srebhan** [comment]
I think we should still track this issue here.

**Comment by sjwang90** [comment]
@vdkost & @jnangle Can you share your Telegraf configs that you're receiving this error?

**Comment by powersj** [comment]
Hi,

Due to the lack of response and the reference of extension objects, I am going to close this issue as a duplicate of #9911.

Thanks
