### ISSUE TITLE
`Illegal instruction` on i585 openwrt

### ISSUE THREAD

**Issue by zeus86** [influxdata/telegraf#9924]
I have got a rather old so-called "ALIX" (amd-geode-based single-core low-power i585-SBCs with multiple NICs, best to use with pfsense or openwrt, manufactured by "PC-Engines"), model 2D3 (https://www.alix-board.de/produkte/alix2d3.html).
Due to the fact, that these are 32-bit boards, one cannot just run pfsense on these anymore, the only slim enough system available today to run on this HW is OpenWrt. I use this as emergency vpn-gateway to a remote location, because these things are rock-solid and basically indestructable. Unfortunately the i386-binary of telegraf refuses to start. 

### Relevant telegraf.conf:
```
irrelevant
```

### System info:

```
# uname -a
Linux alix2d3 4.14.221 #0 Mon Feb 15 15:22:37 2021 i586 GNU/Linux
```
```
Exact OpenWrt-Version:  
OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.044.30835-34e0d65
```
```
# cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 5
model           : 10
model name      : Geode(TM) Integrated Processor by AMD PCS
stepping        : 2
cpu MHz         : 498.016
cache size      : 128 KB
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu de pse tsc msr cx8 sep pge cmov clflush mmx mmxext 3dnowext 3dnow cpuid 3dnowprefetch vmmcall
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 996.03
clflush size    : 32
cache_alignment : 32
address sizes   : 32 bits physical, 32 bits virtual
power management:
```
```
# cat /proc/meminfo | head -1
MemTotal:         253348 kB
```
```
Telegraf-Version: telegraf-1.20.2
```
### Steps to reproduce:
1. Download and extract mentioned telegraf-release onto OpenWrt-Device
2. copy files to designated locations
3. make binary executable
4. use known-working minimal config 
4. run

### Expected behavior:

Telegraf starting up

### Actual behavior:

telegraf instantly exiting with `Illegal Instruction` (even on `--help`:
```
# /usr/bin/telegraf
Illegal instruction
# echo $?
132
#
```
from dmesg:
```
[1312808.917044] traps: telegraf[20451] trap invalid opcode ip:808e511 sp:bfd51f74 error:0 in telegraf[8048000+3203000]
[1312835.116618] traps: telegraf[20453] trap invalid opcode ip:808e511 sp:bf97bb34 error:0 in telegraf[8048000+3203000]
[1314035.777828] traps: telegraf[20479] trap invalid opcode ip:808e511 sp:bf9f1044 error:0 in telegraf[8048000+3203000]
[1314041.517699] traps: telegraf[20480] trap invalid opcode ip:808e511 sp:bfae5334 error:0 in telegraf[8048000+3203000]
[1314108.371587] traps: telegraf[20481] trap invalid opcode ip:808e511 sp:bfde12e4 error:0 in telegraf[8048000+3203000]
```

**Comment by zeus86** [comment]
`file` is not available on openwrt, and i could copy it to my workstation and check, but what's the point? The CHECKSUM IS THE SAME, therefore it is indeed the same file. That's what checksums are for. I checked the checksum of the downloaded archive beforehand as well, the files are not corrupt.

**Comment by Hipska** [comment]
It's to know what your OpenWRT thinks it is 😉 But okay, that seems not to be available.

golang 1.17 seems to be available as package for OpenWRT, so you could try to build it on the router itself. But how to do that exactly might be a thing to ask on OpenWRT community.

**Comment by powersj** [comment]
Hi,

I tried doing some digging on this and came across [this arch forum post](https://bbs.archlinux.org/viewtopic.php?id=147061).

Based on some of the comments, it sounds like your processor, the [AMD Geode LX 800](https://www.pcengines.ch/alix.htm). I've seen some call it an i586-compatible processor because it is missing some required flags, like PAE and SSE. Others say it truly is an i686-compatible processor but may require some kernel command-line options. 

In either case, if you search for "$GO386" on [go source docs](https://go.dev/doc/install/source) page you will see that by default it requires sse2. If you build with GO386=softfloat, you might get it to work.

I am going to go ahead and close this as I don't see a strong need for us to create a softfloat 386 build and users can build their own.

Thanks!
