### ISSUE TITLE
inputs.jti_openconfig_telemetry: Canceled desc = grpc: the client connection is closing

### ISSUE THREAD

**Issue by Jayclifford345** [influxdata/telegraf#9939]
### Relevant telegraf.conf:
```toml
[[inputs.jti_openconfig_telemetry]]
servers = [“myswitch:50051”]

sample_frequency = “60000ms”
username = “”
password = “”
client_id = “mytest”

sensors = [“interfaces /junos/system/linecard/interface/”,
“ifaceDesc /interfaces/interface/state/description/”,
“lsps /junos/services/label-switched-path/usage/”,
“cpu /junos/system/linecard/cpu/memory/”,
“npu /junos/system/linecard/npu/memory/”,
]

```

### System info:
Telgraf log:
```log
2021-10-13T14:08:49Z I! Starting Telegraf 1.20.2
2021-10-13T14:08:49Z D! [agent] Initializing plugins
2021-10-13T14:08:49Z D! [agent] Starting service inputs
2021-10-13T14:08:49Z D! [inputs.jti_openconfig_telemetry] Opened a new gRPC session to myswitch on port 50051
2021-10-13T14:08:49Z D! [agent] Stopping service inputs
2021-10-13T14:08:49Z E! [inputs.jti_openconfig_telemetry] Error in plugin: could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing
2021-10-13T14:08:49Z E! [inputs.jti_openconfig_telemetry] Error in plugin: could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing
2021-10-13T14:08:49Z E! [inputs.jti_openconfig_telemetry] Error in plugin: could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing
2021-10-13T14:08:49Z E! [inputs.jti_openconfig_telemetry] Error in plugin: could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing
2021-10-13T14:08:49Z E! [inputs.jti_openconfig_telemetry] Error in plugin: could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing
2021-10-13T14:08:49Z D! [agent] Input channel closed
2021-10-13T14:08:49Z D! [agent] Processor channel closed
2021-10-13T14:08:49Z D! [agent] Processor channel closed
2021-10-13T14:08:49Z D! [agent] Stopped Successfully
2021-10-13T14:08:49Z E! [telegraf] Error running agent: input plugins recorded 5 errors

```

myswitch config:
set system services extension-service request-response grpc clear-text port 50051
set system services extension-service request-response grpc skip-authentication
set system services extension-service notification allow-clients address 0.0.0.0/0

### Steps to reproduce:
There appears to be a race condition where the client connection is closing before a read is taking place. Errors are received within the same second, so no timeout is happening. As said before, jtimon works fine: https://github.com/nileshsimaria/jtimon/

Adding further debug to Telegraf config does not yield any more results. Have also tried the following:

1. Tried only one sensor with the same sample_frequency as jitmon
2. tried setting enable_tls to true or false and insecure_skip no effect.

### Notes
This ticket was first raised on the community forums.

**Comment by hvdort** [comment]
I was the original reporter... Which type of logs do you need?

**Comment by tfc-stripe** [comment]
I'm having the same issue using a similar config and connecting to a Juniper EX3400.  

I get slightly different results if I have jtimon running though.  It reads data for a bit then hits the same errors:

2022-06-29T19:26:29Z E! [inputs.jti_openconfig_telemetry] Error in plugin: E! Failed to read from rpc error: code = Canceled desc = grpc: the client connection is closing: myswitch
2022-06-29T19:26:29Z E! [inputs.jti_openconfig_telemetry] Error in plugin: E! Could not subscribe to myswitch: rpc error: code = Canceled desc = grpc: the client connection is closing

Any ideas how to fix this?

**Comment by powersj** [comment]
Hi @tfc-stripe @hvdort, 

Sorry for not seeing the earlier response.

I was looking up this error message and it comes from the Go grpc library itself ([docs here](https://pkg.go.dev/google.golang.org/grpc#pkg-variables)) after an attempt is made to subscribe to telemetry by Telegraf. Upstream has an entire section of their [README](https://github.com/grpc/grpc-go#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing) dedicated to this error with the following possible causes.

In this case I think these two apply:

- Do either of you have a proxy set or are using a proxy anywhere in your environment?
- Does the Juniper server have an option to modify `[MaxConnectionAgeGrace](https://pkg.go.dev/google.golang.org/grpc/keepalive?tab=doc#ServerParameters)`?
- Can you enable logging on the server and see what additional log messages appear?

Thanks!

**Comment by tfc-stripe** [comment]
> * Do either of you have a proxy set or are using a proxy anywhere in your environment?

No proxy but there's a VPN connection in between the telegraf server and the EX3400:
Log Host w/ Telegraf -> VPN Tunnel -> Linux Host (terminates the tunnel) -> EX3400

It doesn't seem to be causing any issues; I've tried adjusting with MTU with no effect and JTIMon works fine.

> * Does the Juniper server have an option to modify [MaxConnectionAgeGrace](https://pkg.go.dev/google.golang.org/grpc/keepalive?tab=doc#ServerParameters)?

Based on...
https://www.juniper.net/documentation/us/en/software/junos/jet-developer/topics/ref/statement/grpc-edit-system-jet.html
and
https://www.juniper.net/documentation/us/en/software/junos/interfaces-telemetry/interfaces-telemetry.pdf

it doesn't seem like there is, or at least one that's easily accessible.

> * Can you enable logging on the server and see what additional log messages appear?

I've got the follow config for Telegraf:
```
## Log at debug level.
debug = true
## Log only error level messages.
# quiet = false
```
But only get the same output as the first comment :(. 

On the Juniper side, there are logs for na-grpcd which show the connections being setup and subscriptions being created.  However, it looks like the client (Telegraf) might be closing the connection:

```
Jun 30 16:35:08  #3946# grpc....
Jun 30 16:35:08  #3947# telemetrySubscribe->path_list { path: "/junos/system/linecard/cpu/memory" sample_frequency: 5000 }
Jun 30 16:35:08  #3948# grpc....
... <removed>
Jun 30 16:35:08  #3956# telemetrySubscribe->path_list { path: "/junos/system/linecard/interface/" sample_frequency: 5000 }
... <removed>
Jun 30 16:35:21  #4020# Channel disconnected or Subscription expired: ID = 2, Expired : 0, Client Disconnects : 1, Closing due to sigterm is : 0, Close flag set to : 0
... <removed>
Jun 30 16:35:49  #4071# Channel disconnected or Subscription expired: ID = 1, Expired : 0, Client Disconnects : 1, Closing due to sigterm is : 0, Close flag set to : 1
```

I checked the logs after running JTIMon and they look similar.  They have the same connect / setup sequence but then hit a steady state of no logs until I ctrl+c the process and then the disconnect is the same sequence.

Questions:
* Should I enable / check any other logs on the server?
* Anything else I can provide to help?

**Comment by tfc-stripe** [comment]
Thanks for the quick follow up!

> Can you run telegraf on the linux host or not through a VPN tunnel to eliminate this as possible issues with that? I ask since the grpc docs make it pretty clear that this is not usually an issue with the client itself, but something along the path of networking or with the server.

It's actually an Opengear console server, which runs linux, but I'll give it shot and report back.

> I have no knowledge of JTIMon. Are they even connecting in the same manner that we are. Are they using GRPC as well? If so are they using the same protobuff version and configuraiton as Telegraf?

Yeah, GRPC as well but I'm not sure about protobuff version / configuration.  Here's the github for it:
https://github.com/Juniper/jtimon

**Comment by tfc-stripe** [comment]
When running telegraf, does the `--test` flag cause telegraf to run for a bit then exit?  If so, that was my issue :(

When I kick telegraf off normally everything works fine.   Sorry for the wild goose chase! :(

**Comment by powersj** [comment]
> When running telegraf, does the `--test` flag cause telegraf to run for a bit then exit? If so, that was my issue :(
> When I kick telegraf off normally everything works fine. Sorry for the wild goose chase! :(

ha! I am actually glad that is the case. `--test` does not play well with the service inputs like jti_openconfig_telemetry. If you wanted to do something similar you could use the `--test-wait` option and have Telegraf wait at least 30-60 seconds to see if it connects.

In that case @hvdort could you take a look at my earlier comment re: proxy + server-side logging?

Thanks!
