### ISSUE TITLE
Telegraf SNMP multiple hosts stops after timeout

### ISSUE THREAD

**Issue by cesaroni** [influxdata/telegraf#995]
Hi,
I have a configuration with multiple hosts, like:

[[inputs.snmp.host]]
    address = "host1:161"
    [[inputs.snmp.host.table]]
      name = "<...>"

  [[inputs.snmp.host]]
    address = "host2:161"
    [[inputs.snmp.host.table]]
      name = "<...>"

  [[inputs.snmp.host]]
    address = "host3:161"
    [[inputs.snmp.host.table]]
      name = "<...>"

If one host is not reachable Telegraf doesn't gather the results from the following hosts.

**Comment by glz-io** [comment]
Hi,

I have the same issue.

**Comment by titilambert** [comment]
I just reproduced this bug. I will try to fix it next week.

**Comment by titilambert** [comment]
@sparrc This bug is fixed !
