### ISSUE TITLE
key-value pair client_id="Telegraf" for plugin outputs.kafka is not uploaded to Kafka

### ISSUE THREAD

**Issue by lingenavd** [influxdata/telegraf#9969]
### Relevant telegraf.conf:

```# Configuration for the Kafka server to send metrics to
[[outputs.kafka]]
  # Only accept "win_eventlog" data:
  namepass = ["win_eventlog"]

  ## URLs of kafka brokers
  brokers = ["some_broker:9092"]
  ## Kafka topic for producer messages
  topic = "my_vdi"

#   ## The value of this tag will be used as the topic.  If not set the 'topic'
#   ## option is used.
#   # topic_tag = ""
#
#   ## If true, the 'topic_tag' will be removed from to the metric.
#   # exclude_topic_tag = false
#
#   ## Optional Client id
    client_id = "Telegraf_my_vdi"
#
#   ## Data format to output.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
    data_format = "json"
```

### System info:
Telegraf version 1.20.2 on Windows 10

### Steps to reproduce:

1. open a powershell prompt:
2. eventcreate.exe /L Application /T INFORMATION /ID 999 /SO "loki-test" /D "This is a test event, created in Powershell on my-vdi"
SUCCESS: An event of type 'INFORMATION' was created in the 'Application' log with 'loki-test' as the source.
3. the message in the Kafka topic "my-vdi" looks like:

Data:"This is a test event, created in Powershell on my-vdi"
EventRecordID:124644
Message:"Dit is een test event, aangemaakt met Powershell op Andre zijn VDI om te pushen naar Loki"
ProcessName:"[System Process]"
UserID:"S-1-5-21-1960408xxxxxxxxxx"
UserName:"domein\user"
Version:0
name:"win_eventlog"
Channel:"Application"
Computer:"my_vdi.domain.local"
EventID:"999"
Keywords:"Classic"
Level:"4"
LevelText:"Information"
Opcode:"0"
OpcodeText:"Info"
Source:"loki-test"
Task:"0"
TaskText:""
host:"my_vdi"
timestamp:1634814174

### Expected behavior:

I expect the key-value pair: client_id = "Telegraf_my_vdi" in the Kafka message

### Actual behavior:

the key-value pair: client_id = "Telegraf_my_vdi" is NOT in the Kafka message

**Comment by powersj** [comment]
Hi,

The default used by the sarama library is "sarama", however, we are setting this to "Telegraf" only if you are not setting it in the client_id setting. Do you have any log messages with those values?

Thanks!
