### ISSUE TITLE
Telegraf `--watch-config` doesn't support directories

### ISSUE THREAD

**Issue by 8none1** [influxdata/telegraf#9985]
### System info:

Telegraf 1.20 docker image running in a k8s container

### Steps to reproduce:

1. Configure telegraf with the `--watch-config inotify` and `--config-directory` options
2. Have multiple config files inside the config directory
3. Change one of them

### Expected behavior:

I would expect Telegraf to spot that a config file has been changed and restart.

### Actual behavior:

It appears that Telegraf is unaware of the changed file and does not restart.

### Additional info:

https://github.com/influxdata/telegraf/pull/9485
https://github.com/influxdata/telegraf/commit/9508d4f09c13628a8c177a560531a9a0874a1476

**Comment by conorevans** [comment]
I've submitted a draft PR that fixes this issue. I want to come back to it to add testing and do some more spot-checking.
Interestingly, I found that if you modify a/the `config-file`, it _does_ pick up the change to a config file in a/the config-directory. This also makes me inclined to go back and check.

**Comment by Jesse-Lee-Hughes** [comment]
Hi all,

Is this suposed to work currently? 

I'm running: --config-directory /etc/telegraf/telegraf.d --watch-config poll command in my docker container. The changes are coming from a newly created config file in the telegraf.d directory. I've tested the config works when passing SIGHUP however I can't get it working automatically without SIGHUP.
